### ISSUE TITLE
Automatically Turn off Clarifai when reach API limit per month

### ISSUE THREAD

**Issue by CharlesCCC** [InstaPy/InstaPy#1001]
## Expected Behavior
Whenever reached the 5000 Clarifai API call limit, the script will stop Clarifai API call but fall back to the default comment; 

## Current Behavior
Whenever reached the 5000 Clarifai API call limit,  the script will log a API call error without leave any comment then move on to next image. 

## Possible Solution (optional)
manually disable Clarifai api call for now.

**Comment by timgrossmann** [comment]
@CharlesCCC Sounds like a great idea to make everything more convenient!
Thank you
Are you able to implement and PR this?

**Comment by sionking** [comment]
It easy to implement based on my limit per hour / limit per day module.
