### ISSUE TITLE
still facing issue installing emoji

### ISSUE THREAD

**Issue by drcyber975** [InstaPy/InstaPy#1002]
i followed the steps of  issue #297 and it still didnt work for me. I already have emoji as a directory however when i use the command python setup.py install i recieve an error message decsibed below )=

InstaPy$ git clone https://github.com/carpedm20/emoji.git
fatal: destination path 'emoji' already exists and is not an empty directory.
lubuntu@lubuntu:~/InstaPy$ cd emoji
lubuntu@lubuntu:~/InstaPy/emoji$ python setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-3745.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.

lubuntu@lubuntu:~/InstaPy/emoji$

**Comment by dreamyUB** [comment]
You want to use emojis for? Just wondering?

**Comment by drcyber975** [comment]
No I fixed the issue i am just tying to work out how to edit the QuickStart.py file to allow me to follow people.

Sent from Yahoo Mail for iPhone


On Wednesday, November 29, 2017, 11:39 AM, dreamyUB <notifications@github.com> wrote:


You want to use emojis for? Just wondering?
