### ISSUE TITLE
Delay seems to not always work

### ISSUE THREAD

**Issue by jmurphy45** [InstaPy/InstaPy#1003]
Output

INFO - --> Ongoing follow 1, now following: niablackmore
INFO - --> Ongoing follow 2, now following: mosscreekmallards
INFO - --> Ongoing follow 3, now following: jgray1865
INFO - --> Ongoing follow 4, now following: thomascolepike
INFO - --> Ongoing follow 5, now following: rodriguezman
INFO - --> Ongoing follow 6, now following: calharriss7
INFO - --> Ongoing follow 7, now following: j_t_w_4
INFO - --> Ongoing follow 8, now following: dallasrogers
INFO - --> Ongoing follow 9, now following: andrew.maxwell63
INFO - --> Ongoing follow 10, now following: pcraw_75
INFO - sleeping for about 10 minutes
INFO - --> Ongoing follow 11, now following: k.gray16
INFO - --> Ongoing follow 12, now following: officialjohnblake
INFO - --> Ongoing follow 13, now following: watsonpersinger___
INFO - --> Ongoing follow 14, now following: owen_hutchinson99
INFO - --> Ongoing follow 15, now following: bpickett85
INFO - --> Ongoing follow 16, now following: morrow4444
INFO - --> Ongoing follow 17, now following: _daddy.wes
INFO - --> Ongoing follow 18, now following: tony_tavizon
INFO - --> Ongoing follow 19, now following: justin_delgado01
INFO - --> Ongoing follow 1, now following: will.martinez.51
INFO - --> Ongoing follow 2, now following: sam___scott
INFO - --> Ongoing follow 3, now following: ryfrutiger
INFO - --> Ongoing follow 4, now following: tamburkee
INFO - --> Ongoing follow 5, now following: huntermueller99
INFO - --> Ongoing follow 6, now following: johncra25
INFO - --> Ongoing follow 7, now following: a_redhead22
INFO - --> Ongoing follow 8, now following: will_cantu
INFO - --> Ongoing follow 9, now following: dylweed39
INFO - --> Ongoing follow 10, now following: tl_waterfowl
INFO - sleeping for about 10 minutes

session.follow_user_followers(['drakewaterfowl', 'sitkagear'], amount=20, randomize=True, sleep_delay=600)

It should stop after every 10 right?

**Comment by hestuppfodarn** [comment]
I have the same experience,

**Comment by Ndjemhi** [comment]
Same here! Sleep delay randomly stopped working and my whole unfollow util is just not acting normally. The unfollows happen almost instantly, when the util actually works.
