### ISSUE TITLE
Interact with someones followers not working correctly

### ISSUE THREAD

**Issue by addiman** [InstaPy/InstaPy#1008]
## Expected Behavior
should interact with given number of someone followers 

## Current Behavior
Info says 41 and then starts with 1/21:
also repository example code not working, if not adding the upperlimit.
and also getting into loop if getting to user wich has too much followers.
and the do-like-false argument is ignored. why is it in example code?

INFO - Session started - 2017-11-29 03:46:41
INFO - Logged in successfully!
WARNING - username -> Less users to follow than requested.
INFO - --> Users: 41
INFO - Username [1/21]
INFO - --> b'aaaaaa'
INFO - Getting aaaaaa image list...
INFO - Interaction begin...
INFO - --> Now following
INFO - Post [1/3]

## InstaPy configuration
session.set_user_interact(amount=3, randomize=True, percentage=50, media='Photo')
session.set_upper_follower_count(limit = 90000000)
session.set_lower_follower_count(limit = 1)
session.set_do_follow(enabled=True, percentage=70)
session.set_do_like(enabled=False, percentage=70)
session.set_comments(["Sehr schön :)", "Super! :)", "Toll ;)"])
session.set_do_comment(enabled=True, percentage=80)
session.interact_user_following(['username'], amount=100, randomize=True)

**Comment by converge** [comment]
hey @addiman , I think we already fixed this bug, are you using the latest version ?

**Comment by addiman** [comment]
hey @converge. Yes its a todays fresh git clone.
