### ISSUE TITLE
Raspberry Pi?

### ISSUE THREAD

**Issue by Rchristo** [InstaPy/InstaPy#101]
Hi thanks for this amazing work.

Will it be possible to run this on an raspberry pi? Would love to try this for a longer period of time.

**Comment by maxinedotdev** [comment]
You should read the Medium post by Tim Großmann, a lot is explained there or have links/references to it.

https://medium.freecodecamp.com/my-open-source-instagram-bot-got-me-2-500-real-followers-for-5-in-server-costs-e40491358340

EDIT:ß

**Comment by eduardocalazansjr** [comment]
It has enough ram?
It runs chrome?
If all that are true, you will run this project as an normal computer.

Edit: you will need both chromedriver and chrome compiled for arm.
