### ISSUE TITLE
Direct Messaging feature

### ISSUE THREAD

**Issue by kevXZY** [InstaPy/InstaPy#1012]
## Expected Behavior
Ability to send direct messages to followed users as example
## Possible Solution (optional)
Using python-api it seems to be possible, as discussed here 

https://github.com/LevPasha/Instagram-API-python/issues/181#issuecomment-347909638

**Comment by charliecode** [comment]
Has anyone found out whether this is a possibility or not. Just looking at the desktop version I don't see how it would be possible, but I am open to suggestions.

**Comment by vsgobbi** [comment]
check igdm-master and make it compliance
