### ISSUE TITLE
problem with python setup.py

### ISSUE THREAD

**Issue by Tokyysek** [InstaPy/InstaPy#1013]
https://ctrlv.cz/eN5g

**Comment by Tokyysek** [comment]
@converge can you help me please

**Comment by converge** [comment]
Yes, extend your issue with detailed informations.

**Comment by Tokyysek** [comment]
Specify detailed information

**Comment by RomeoJuliett** [comment]
@Tokyysek how far have you gone in the install?

**Comment by Tokyysek** [comment]
gdi32.lib canon be opened 
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.10.25017\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
