### ISSUE TITLE
exit code when dealing with my followers list (?)

### ISSUE THREAD

**Issue by pedryvo** [InstaPy/InstaPy#1014]
## Current Behavior

`selenium    | 19:33:51.210 INFO - To upstream: {"script": "return window._sharedData.entry_data.ProfilePage[0].user.followed_by.count", "args": [], "sessionId": "ce8d5470ef8f70410d2154658bd0d917"}`
`selenium    | 19:33:51.228 INFO - To downstream: {"sessionId":"ce8d5470ef8f70410d2154658bd0d917","status":0,"value":586}`
`selenium    | 19:33:51.267 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3c9530c`
`selenium    | 19:33:51.268 INFO - Handler thread for session ce8d5470ef8f70410d2154658bd0d917 (chrome): Executing DELETE on /session ce8d5470ef8f70410d2154658bd0d917/cookie (handler: ServicedSession)`
`selenium    | 19:33:51.885 INFO - To downstream: {"sessionId":"ce8d5470ef8f70410d2154658bd0d917","status":0,"value":null}`
`selenium    | 19:33:51.902 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3c9530c`
`selenium    | 19:33:51.903 INFO - Handler thread for session ce8d5470ef8f70410d2154658bd0d917 (chrome): Executing DELETE on /session/ce8d5470ef8f70410d2154658bd0d917/window (handler: ServicedSession)`
`selenium    | 19:33:52.080 INFO - To downstream: {"sessionId":"ce8d5470ef8f70410d2154658bd0d917","status":0,"value":null}`
`web_1       | INFO - Session ended - 2017-11-29 19:33:52`
`web_1       | INFO - --------------------`
`web_1       | `
`web_1       | `
`instapy_web_1 exited with code 0`

## InstaPy configuration

`bot = InstaPy(username=insta_username, password=insta_password, selenium_local_session=False)`
`bot.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub')`
`bot.login()`
`bot.set_upper_follower_count(limit=2500)`
`bot.set_do_comment(True, percentage=10)`
`bot.set_comments([':)', ':D'])`
`bot.like_by_tags(['rockbaiano', '#rockbaiano', 'feiranoise', '#feiranoise'], amount=300)`
`#bot.like_by_locations(['318261109/dubliners-irish-pub-salvador/'], amount=100)`
`#bot.follow_user_followers(['coletivosuicabahiana', 'taro_oficial'], amount=100, randomize=False, sleep_delay=60)`
`bot.end()`

**Comment by converge** [comment]
hey mate, this is a known issue https://github.com/timgrossmann/InstaPy/search?q=window._sharedData.entry_data.ProfilePage%5B0%5D&type=Issues&utf8=%E2%9C%93

need to be fixed

**Comment by pedryvo** [comment]
thanks @converge i'll test it on another machine
