### ISSUE TITLE
What is the reason for this error?

### ISSUE THREAD

**Issue by Affenjimbo** [InstaPy/InstaPy#1015]
Hello together,
this error appears after a certain time every time I run instapy .

[3/12]
Image from: b'clemmography'
Number of Followers: 192
Link: b'https://www.instagram.com/p/BcF6otVFasF/?tagged=bleachmyfilm'
Description: b'American Idiot\n\n#portraits #portrait #portraits_ig #pixel_ig #p
ortraiture #expofilm3k #portrait_perfection #portraitstyles_gf #snowisblack #por
traits_universe #featurepalette #bleachmyfilm #portraitmood #featurepalette  #rs
a_portraits #makeportraits #profile_vision #top_portraits #life_portraits #postt
hepeople #quietthechaos #2instagood #way2ill #justgoshoot #artofvisuals #l0tsabr
aids #ftwotw #igPodium_portraits #theatre'
--> Image Liked!
Traceback (most recent call last):
  File "C:\Users\Egon\Documents\GitHub\InstaPy\quickstart-comment.py", line 9, in
 <module>
    session.like_by_tags(['bleachmyfilm', 'globe_visuals', 'underrated_shots', '
l0tsabraids', 'portraitgames', 'portraitvision', 'featurepalette', 'featuremeofh
', 'featuremeseas', 'seamyphotos', 'seekingthestars', 'seekmests', 'pursuitofpor
traits', 'funsizedaccount', 'portraitpage', 'creativesontherise', 'depthobsessed
', '???????????', 'streetart', 'travelgram', 'serialshooters', 'of2humans', 'str
eets_vision', 'hvmansouls', 'visualmasterz', 'doports', 'bnw_workers'], amount=2
5)
  File "C:\Users\Egon\Documents\GitHub\InstaPy\instapy\instapy.py", line 624, in
like_by_tags
    self.browser, comments)
  File "C:\Users\Egon\Documents\GitHub\InstaPy\instapy\comment_util.py", line 25,
 in comment_image
    comment_input[0].send_keys("\b")
  File "C:\Program Files (x86)\lib\site-packages\selenium\webdriver\remote\webel
ement.py", line 350, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Program Files (x86)\lib\site-packages\selenium\webdriver\remote\webel
ement.py", line 499, in _execute
    return self._parent.execute(command, params)
  File "C:\Program Files (x86)\lib\site-packages\selenium\webdriver\remote\webdr
iver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\lib\site-packages\selenium\webdriver\remote\error
handler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot fo
cus element
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b2
33)

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Egon\Documents\GitHub\InstaPy\instapy\instapy.py", line 1419, in
 end
    self.browser.delete_all_cookies()
  File "C:\Program Files (x86)\lib\site-packages\selenium\webdriver\remote\webdr
iver.py", line 733, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "C:\Program Files (x86)\lib\site-packages\selenium\webdriver\remote\webdr
iver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\lib\site-packages\selenium\webdriver\remote\error
handler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unhandled
 inspector error: {"code":-32601,"message":"'Network.deleteCookie' wasn't found"
}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b2
33 

Does anyone know a solution for that?
Thanks you guys!!

**Comment by converge** [comment]
Hey mate, could you update your chrome driver and try again?

**Comment by Affenjimbo** [comment]
Thanks a lot for the quick reply!
 I think that solved the issue. InstaPy just ran for 2 hours without any errors!
