### ISSUE TITLE
TypeError when interacting with an accounts followers

### ISSUE THREAD

**Issue by jeometry** [InstaPy/InstaPy#1016]
I am getting a TypeError when running the script for following specified accounts followers. The error is below:

>  session.follow_user_followers(['usernames'], amount=10, randomize=False, interact=True)
> TypeError: follow_user_followers() got an unexpected keyword argument 'randomize'

I copied the code directly from the code page as follows:

> session.follow_user_followers(['usernames'], amount=10, randomize=False, interact=True)

**Comment by RomeoJuliett** [comment]
Can you include more of the trace before and after those lines?

**Comment by jeometry** [comment]
Here is the full output from running my script:

 

> Logged in successfully!
> 
> Session ended
> 
> Traceback (most recent call last):
>   File "C:\Python Scripts\InstaPy-master\quickstart.py", line 27, in <module>
>     session.follow_user_followers(['usernames'], amount=10, randomize=False, interact=True)
> TypeError: follow_user_followers() got an unexpected keyword argument 'randomize'

My code is as follows:

```
from instapy import InstaPy

insta_username = 'xxxx'
insta_password = 'xxxx'

session = InstaPy(username=insta_username, password=insta_password)
session.login()

session.follow_user_followers([‘usernames’], amount=10, randomize=False, interact=True)

# end the bot session
session.end()



```

**Comment by converge** [comment]
@jeometry could you update InstaPy, try again and paste all the error message ?

**Comment by jeometry** [comment]
Hello All,

I have updated the file and now I no longer get the error. Thank you all for your help!
