### ISSUE TITLE
ImportError: No module named clarifai.rest

### ISSUE THREAD

**Issue by RafaelLee** [InstaPy/InstaPy#1024]
In my first run on DigitalOcean I run python quickstart.py

And get this error: ImportError: No module named clarifai.rest

I try run pip install clarifai
try clarifai.rest too
and without sucess, someone knows how to solve that?

I follow all the tutorial of instapy, and just edit the essencial things in the quickstart.py

Some help, please

**Comment by converge** [comment]
Hey @RafaelLee , I made a video tutorial teaching step by step how to setup InstaPy on Digital Ocean, take a look: https://www.youtube.com/watch?v=2Ci-hXU1IEY

**Comment by RafaelLee** [comment]
Hey @converge, thanks for your video, actually I in that step thanks for you.

Im following your tutorial. But I get stuck here.

In the red error you say in the video 'dont consurn about that'... is there my problem. And I cant continue.

If you can help me with another solution.

Thanks anyway.

**Comment by converge** [comment]
sorry, english is not my first language. 

what's the error message ?

**Comment by RafaelLee** [comment]
Não é a minha primeira língua também amigo @converge .

Eu estou conectado no console da DigitalOcean, por isso ainda não consegui copiar o texto, não manjo como faz igual você faz, de mandar a parada pelo console da sua máquina física, acho que é por SSH.

Enfim, o que tá pegando, eu vou deixar os prints aqui:

![image](https://user-images.githubusercontent.com/681629/33493550-8f1d0c44-d6a7-11e7-939a-e39e4504f98f.png)


That is what happends

If can you help, thanks :)

**Comment by converge** [comment]
@RafaelLee estava cansado de pensar em inglês ! haha , easy fix:
```sudo apt-get install python-dev```
or if your python --version says 3.x:
```sudo apt-get install python3-dev```

**Comment by RafaelLee** [comment]
Thanks @converge, thats really help me.

Lets go, continue the process.
