### ISSUE TITLE
Crash on trying to follow a user with a long username

### ISSUE THREAD

**Issue by uni1783** [InstaPy/InstaPy#1025]
When running the script with the GUI (Chrome), the follow button/link is not visible if the username is 30 characters or longer. The follow button appears when the window is resized (smaller)

## Expected Behavior
Script clicks on the visible follow button

## Current Behavior
Crash:
```
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.2 x86_64)
```
## Possible Solution (optional)

Run the GUI in a smaller/narrow resolution ?

## InstaPy configuration
session = InstaPy(username=insta_username, password=insta_password)
session.login()

session.set_upper_follower_count(limit=9500)
session.set_lower_follower_count(limit=400)
session.set_do_follow(enabled=True, percentage=84, times=2)
session.set_user_interact(amount=184, randomize=True, percentage=42, media='Photo')
session.set_dont_unfollow_active_users(enabled=True, posts=5)
session.like_by_tags(['altmodel', 'alternativemodel'], amount=121)

**Comment by converge** [comment]
hey @uni1783 , when was last time you updated InstaPy ? 

To catch this error I do need a 30 characters longer username and reduze the chrome windows size to which size ?

**Comment by uni1783** [comment]
I updated it yesterday I think, or the day before

Resize the browser to 850px width should do it and the user it crashed on was https://www.instagram.com/p/BZ4Dhc4g0Z7/ (the rest of the images might not be safe for work)

**Comment by converge** [comment]
tried to reproduce the error without success.
