### ISSUE TITLE
OnlyNotFollowMe not doing anything

### ISSUE THREAD

**Issue by Ndjemhi** [InstaPy/InstaPy#1029]
## Expected Behavior
This simple script does absolutly nothing. I can't find the reason why and couldn't find anyone here that had the same problem. I don't know if it's working for everybody else, but The more people I follow, the less i'm able to unfollow afterwards.

## Current Behavior
INFO - Session started - 2017-12-01 23:01:53
CRITICAL - Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO - Logged in successfully!
INFO - Number of people followed automatically remaining: 5681
INFO - --> Total people unfollowed : 0 
INFO - Session ended - 2017-12-01 23:02:13
INFO - --------------------

## InstaPy configuration
session = InstaPy()
session.login()
session.unfollow_users(amount=100,onlyInstapyFollowed = False, onlyNotFollowMe=True)
session.end()

**Comment by sionking** [comment]
I tried to look for a Y. but it seems that you don't capture all of your follower/following since rate is too high and instagram blocks you.
Try add this:
unfollow_util.py 
line 175 add a sleep after the while:
while has_next_data:
    **sleep(10)**


You need to add the sleep after the while

**Comment by Ndjemhi** [comment]
Thanks for the reply, Still experiencing exactly the same results though. Should I just delete some of the followers from the list?

**Comment by converge** [comment]
It's sad when people don't recognize the work done by some many people, has 0 contributions and says "This simple script does absolutly nothing".

But, I always prefer to share the love, here is the bug fix #1031

**Comment by Ndjemhi** [comment]
I;m sorry, maybe i didn't express myself correctly, I'm not familiar at all with git and would love to contribute, I actually thought that this would be a common bug. I meant no dissrespect and absolutly love your work. If I can contribute in any way, please tell me how.

**Comment by eduaero** [comment]
I am having the same problem when using onlyNotFollowMe=True

I can see how the browser opens a a website, but it shows the html attached. So there are no buttons were to click.

![image](https://user-images.githubusercontent.com/16412674/34890373-ed1a6e86-f7d1-11e7-8864-4ae4312a5fad.png)

Is it still working for u? I have tried it with my raspberry and on my laptop with Windows and Chrome and I have had the same result for both.

Thank you very much beforehand!! :)

Edu

**Comment by converge** [comment]
it´s just how graphql works, it´s working correctly :)
