### ISSUE TITLE
In log say Liked but not like in real

### ISSUE THREAD

**Issue by RafaelLee** [InstaPy/InstaPy#1030]
Im monitoring in the general log, and we have that:
![image](https://user-images.githubusercontent.com/681629/33517775-492f460a-d771-11e7-9407-1b6fa7657237.png)

But, in real what happends: nothing
![image](https://user-images.githubusercontent.com/681629/33517781-6600f65c-d771-11e7-932c-52f64671c142.png)

And that is my quickstart file:
![image](https://user-images.githubusercontent.com/681629/33528749-b584a378-d84c-11e7-81f0-2afe3ff0a05e.png)

If someone know how help me, thanks :+1:

**Comment by ugurozturk** [comment]
@RafaelLee You are right. Mine is also didn't liked. And i checked from the instagram history, im realized, my bot did like 1 day ago. Tried manuel like and yeah i can do it without problem. So the bot fails.

Edit : It does work well in Windows10. Going to checksomething
Edit2 : restarted the script and changed blacklist name and it did work. It did like
Edit3 : Did revert blacklistname to old one and it looks liking again...
Edit4 : Sometimes it does like, sometimes it doesn't like doesn't know the reason

**Comment by ugurozturk** [comment]
@converge blacklist has something wrong on likes

**Comment by ugurozturk** [comment]
New detail : it does adds well blacklist. Checked the username and activity in blacklist. There is no liked/followed to this user before

**Comment by RafaelLee** [comment]
I think that dont affect me, because I dont use blacklist.

**Comment by ugurozturk** [comment]
@RafaelLee and your quickstart file is not visible

**Comment by RafaelLee** [comment]
Im sorry @ugurozturk, I edit now the post...

I try with locations and without, with comment and without, coments with a percentage of 10, 50 and 100.

Likes by hashtags dont work :/

**Comment by ugurozturk** [comment]
@RafaelLee asking for beeing clear, is your code doesn't like all the time?

It must do likes even like this
```
session = InstaPy(username=insta_username, password=insta_password, nogui=True)
session.login()
session.set_upper_follower_count(limit=2500)
session.like_by_tags(['tag','tag2'], amount=amountLike)
session.end()
```

**Comment by RafaelLee** [comment]
Well, I dont know what is happening...

This is my file:
![image](https://user-images.githubusercontent.com/681629/33531730-3c8dadda-d878-11e7-9d1a-212d8ab58836.png)

The problem continue. If someone can help me, thanks.

**Comment by gerdmueller2** [comment]
In the Readme is this hint - maybe you can try this!
Put `like_by_location` under the comments...

Essentially, all the `set_`* methods have to be before `like_by_tags` or `like_by_locations` or unfollow. This is also implicit in all the exmples and quickstart.py

**Comment by NewyorkDev** [comment]
I had this happen to me,  found our that it was that Instagram blocked liking on my account - it happended twice to two accounts. One was only after about 250 likes.  Different IP'S different everything.

**Comment by espipj** [comment]
@NewyorkDev did the log said "Image Liked". Could you at that moment post likes from the mobile/web manually?
In facing this issue...

**Comment by gerdmueller2** [comment]
@davidrocket posted an solution for this: (same problem, other issues: 
[#1030](https://github.com/timgrossmann/InstaPy/issues/1030) [#1083](https://github.com/timgrossmann/InstaPy/issues/1083) [#993](https://github.com/timgrossmann/InstaPy/issues/993)

To Fix "Like"-Problem, please replace the line 537 in `like_util.py` with this line

like_elem[0].click()

Tested and works!

**Comment by espipj** [comment]
More info here: https://github.com/timgrossmann/InstaPy/pull/1105

**Comment by Boredude** [comment]
Issue persists for me as well. Comments and following works well. I do not use the blacklist feature
