### ISSUE TITLE
clarifai API Key Returns error !!

### ISSUE THREAD

**Issue by mcnaveen** [InstaPy/InstaPy#1035]
Whenever I'm using Clarifai API. It returns an Error.

I can't find any proper guide for Using this. 

Here is the Error : https://imgur.com/a/fxs3c

Here is my Configuration : https://imgur.com/a/fcvK0

**Comment by timgrossmann** [comment]
@the-mcnaveen You can't put the `export` statement into the quickstart.py file.
You have to execute that from the command line.

Simply put it as a parameter in the `set_use_clarifai` method instead of using the export method

**Comment by mcnaveen** [comment]
Can you Post some Example Code? Can't get it !! Completly new to Python.

Thanks :)

**Comment by Naramsim** [comment]
@the-mcnaveen please do not use the double exclamation points since you are also new to Python.

When you are in your shell give these commands

```sh
export CLARIFAI_API_KEY ....
python quickstart.py
```

**Comment by timgrossmann** [comment]
@the-mcnaveen I'd recommend just doing this:

```python
# default enabled=False , enables the checking with the clarifai api (image
# tagging) if secret and proj_id are not set, it will get the environment 
# variables 'CLARIFAI_API_KEY'

session.set_use_clarifai(enabled=True, api_key='xxx')
```
