### ISSUE TITLE
unexpected error when executing script

### ISSUE THREAD

**Issue by drcyber975** [InstaPy/InstaPy#1036]
All i am trying to do is execute the script so it follows and likes the amount specified in an hour but the script doesnt work when i execute it and the code looks correct. I used the same commands in the example and just swapped the information. This is what i used;

```python
from instapy import InstaPy

insta_username = 'username'
insta_password = 'password'

session.set_upper_follower_count(limit=900)
  
session.follow_user_followers(['kimkardashian', 'selnagomez', 'cosplay.world_','realdonaldtrump'], amount=17, randomize=True, sleep_delay=60)
session.like_by_tags(['natgeo', 'girl', 'cute'], amount=33)
session.follow_user_followers(['kimkardashian', 'selnagomez', 'cosplay.world_','realdonaldtrump'], amount=17, randomize=True, sleep_delay=3600)

session.end()
```

this was the error message the received.

lubuntu@lubuntu:~/InstaPy$ python script.py
Traceback (most recent call last):
  File "script.py", line 6, in <module>
    session.follow_user_followers(['kimkardashian', 'selnagomez', 'cosplay.world_','realdonaldtrump'], amount=17, randomize=True, sleep_delay=60)
NameError: name 'session' is not defined
lubuntu@lubuntu:~/InstaPy$ 

what am i doing wrong?

**Comment by timgrossmann** [comment]
@drcyber975 Please read the documentation...

the quickstart file gives you a start out of that exact reason... You're missing the constructor:

```python
# if you want to run this script on a server, 
# simply add nogui=True to the InstaPy() constructor
session = InstaPy(username=insta_username, password=insta_password)
session.login()

```
