### ISSUE TITLE
If follow request has been sent to private account, unfollow behaviour is incorrect

### ISSUE THREAD

**Issue by danniefraim** [InstaPy/InstaPy#1037]
If InstaPy has sent a follow request to a private account, and then tries to unfollow that account while the request is still pending, the user will simply be deleted from the follow pool, which means that if the follow request is approved later, that user will never be automatically unfollowed by InstaPy if `onlyInstapyFollowed`is true.

## Expected Behavior

Pending follow request should be handled better than simply removing the user from the pool.

## Current Behavior

The user is deleted from the follow pool and will not be unfollowed in the future.

## Possible Solution (optional)

Identify that a follow request is pending. Either do nothing for now, and try unfollowing again later. Or delete the pending request. Perhaps the best solution would be a combination of both. Add a configuration flag for how long to wait for pending requests, such as three days or something like that. If the request was sent within that time period, ignore the user. If the time period has elapsed, then remove the follow request.

The problem is here, after the unfollow button could not be identified (because it's not yet available): https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py#L118

**Comment by danniefraim** [comment]
I have noticed that the number of people I follow on Instagram continually grows, despite not doing any manual following since starting to use InstaPy and unfollowing as many as I'm following with InstaPy and trying to keep the InstaPy follow pool at around 400-500 people. It might be because of this issue, or it might have other causes (in which case I will post another issue if and when I discover the cause).

**Comment by sionking** [comment]
Good catch!
I am getting the same increase in followers despite pool is empty.
It might be the reason.
BTW, is it configurable to follow private account or is it like this by defualt?

**Comment by danniefraim** [comment]
@sionking It's not configurable, but there's a feature request for it (with a bounty!) here: https://github.com/timgrossmann/InstaPy/issues/1006

**Comment by sionking** [comment]
So how can you say "InstaPy has sent a follow request to a private account" if this feature not yet implemented ?

**Comment by danniefraim** [comment]
@sionking I misunderstood your question. I thought you asked if there's a configuration option that lets you choose whether to follow private accounts or not. There's no such option. InstaPy will follow private and public accounts alike, without making any difference between them.
