### ISSUE TITLE
unfollow_user does not remove all users (but no error-message)

### ISSUE THREAD

**Issue by gerdmueller2** [InstaPy/InstaPy#1041]
hi guys,

the command:
_session.unfollow_users(amount=100, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60 )_

does not remove all users from the pool.

does this relates to [#1037](https://github.com/timgrossmann/InstaPy/issues/1037)?

## Expected Behavior
should unfollow all 100 users

## Current Behavior
INFO - --> Ongoing Unfollow From InstaPy 2, now unfollowing: ******
INFO - --> Ongoing Unfollow From InstaPy 3, now unfollowing:  ******
INFO - --> Ongoing Unfollow From InstaPy 4, now unfollowing:  ******
INFO - --> Ongoing Unfollow From InstaPy 5, now unfollowing:  ******
INFO - --> Ongoing Unfollow From InstaPy 6, now unfollowing: ******
INFO - --> Ongoing Unfollow From InstaPy 7, now unfollowing: ******
INFO - --> Ongoing Unfollow From InstaPy 8, now unfollowing: ******
INFO - --> Ongoing Unfollow From InstaPy 9, now unfollowing: ******
INFO - --> Ongoing Unfollow From InstaPy 10, now unfollowing: ******
WARNING - sleeping for about 1min
INFO - --> Ongoing Unfollow From InstaPy 11, now unfollowing: ******
INFO - --> Ongoing Unfollow From InstaPy 12, now unfollowing: ******
********************************************************
INFO - --> Ongoing Unfollow From InstaPy 100, now unfollowing: ******

## Possible Solution (optional)
But when i look at specific users, they are NOT unfollowed and still in my account.
but they are removed from "_logs/USERNAME_followedPool.csv_"

can someone fix this?

**Comment by sionking** [comment]
Look at my post:
https://github.com/timgrossmann/InstaPy/issues/992

at the IMPORTANT :
*** Something improtant ***
Related to the file "userX_followedPool.csv", it contain many usernames without ',' at the end of the line before the \n.
Maybe an old syntax leftovers? it results in not removing the username from list after unfollowing it !!!!

**Comment by gerdmueller2** [comment]
thanks @sionking, but your solution fixes the following case:
"it removes the username from list (CSV) after unfollowing it"

--> BUT my case is different: the user are correctly deleted from the CSV but not unfollowed in my account

or did i get it wrong?

**Comment by sionking** [comment]
If you have a corrupted CSV which not contain all followed users by instaPy, than the only solution for you is to read the json file, which contain all ever followed users, and check each user to unfollow.

Another thing I do with my clients is to save all current followers/following before starting the automation, it is a good starting point for recovery, I will do a PR for this feature soon.

**Comment by gerdmueller2** [comment]
@sionking my CSV is not corrupted. each line has a "," at the end...

in round about 50% of the cases the user is not deleted (maybe it belongs to the bug, that this is a private account)?

as i mentioned: the "Number of people followed automatically remaining:" is decreasing but the users are still in my account.
and instapy is running: "INFO - --> Ongoing Unfollow From InstaPy" XXX , now unfollowing: XXX
and deletes the account from the CSV but not from instagram.
