### ISSUE TITLE
don't comment on the same pic twice

### ISSUE THREAD

**Issue by gerdmueller2** [InstaPy/InstaPy#1045]
Because of this bug [InstaPy log Like Photo => No Like at Instagram](https://github.com/timgrossmann/InstaPy/issues/993) instaPy comment in the next running session sometimes on the same pictures.

can someone implement a check, if user already commented on the pic (and dont allow a second comment...) ?
thanks

**Comment by timgrossmann** [comment]
@gerdmueller2 Feel free to post a nice big bounty on this issue: https://www.bountysource.com/issues/51974209-instapy-like-photo-no-like-at-instagram

I'm pretty sure there will be someone who'd love to resolve this issue then.
