### ISSUE TITLE
How can I set up proxy in Instapy

### ISSUE THREAD

**Issue by sky660099** [InstaPy/InstaPy#1049]
I`m from China, so you know, we have to visit instagram through proxy.

I`ve tried to install switchomega to set up proxy everytime the chrome window shows up. However, when I restart the quickstart, the switchomega disappears and so do the setting of proxy.

So, is there any solution to set proxy in instapy properly?

**Comment by timgrossmann** [comment]
@sky660099 Try adding 

```python
chrome_options.add_argument('--proxy-server=http://<ip_of_proxy>')
```

to the instapy constructor in https://github.com/timgrossmann/InstaPy/blob/db6b7cc4670884cb8b000cabad336b26dc865ebb/instapy/instapy.py#L154-L160

**Comment by sky660099** [comment]
@timgrossmann That works, thank you!

**Comment by timgrossmann** [comment]
@sky660099 Awesome! Enjoy

**Comment by pr0f-f4rn5w0rth** [comment]
Thanks @timgrossmann for help on this. Had a follow-up question: how do you add login details in case I have for my proxy?

**Comment by timgrossmann** [comment]
@sky660099 I'm not 100% sure but in most cases you just use

`<username>:<password>@<proxy_url>:<port>`

**Comment by sky660099** [comment]
@timgrossmann got it, thx. Btw, unfortuanately today my account is restricted by ins. Even not able to add any caption or comment at my own post. How long will it be recovered?  Is there any good suggestions in using instapy or setting the parameter? Now I unfollow 20 users every hour and view 30 posts under each hashtag, others are all default.

**Comment by timgrossmann** [comment]
@sky660099 I'm sorry, but the setup changes from account to account... 
There is no "general" rule as it seems

**Comment by ghost** [comment]
I have created a PR for proxy authentication https://github.com/timgrossmann/InstaPy/pull/1531
Check please.

**Comment by priyanka271** [comment]
Hello. Are you able to use proxy in headless browser?
