### ISSUE TITLE
Invalid Syntax time_util.py

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#105]
Hi,

I get the following error:

`
from .instapy import InstaPy
  File "/home/tibor/InstaPy/instapy/instapy.py", line 12, in <module>
    from .comment_util import comment_image
  File "/home/tibor/InstaPy/instapy/comment_util.py", line 5, in <module>
    from .time_util import sleep
  File "/home/tibor/InstaPy/instapy/time_util.py", line 2
    import random import gauss
                       ^
SyntaxError: invalid syntax
`

**Comment by AlainPilon** [comment]
@tibor there is already a PR to fix this. Until it is merged, just go in `instapy/time_util.py` and replace `import random import gauss` with `from random import gauss` and do the same for the next line.

it is PR #104

**Comment by tibor** [comment]
Thanks, Sorry
