### ISSUE TITLE
Can I use InstaPy running on termux!

### ISSUE THREAD

**Issue by sudo-judo** [InstaPy/InstaPy#1050]

**Comment by sudo-judo** [comment]
@timgrossmann can you tell me step by step to run InstaPY on termux? Do i need to install chromedriver or leave it on my default web browser which is miui browser

**Comment by timgrossmann** [comment]
@sudo-judo I am sorry but I have no experience with this platform... Maybe there is someone else that can help you 😉

**Comment by sudo-judo** [comment]
@timgrossmann ok thanks for the answer, how about if  i just run the tool without selenium installed? I had selenium installed on my termux but show me some error with chromedriver.
Thanks in advance

**Comment by Areahints** [comment]
`pip install instapy` and `pip install instapy --ignore-installed`

are both leading to the same error

```
error: invalid argument '-std=gnu99' not allowed with 'C++'

Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-dbds33us/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-_zitw7ge/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-dbds33us/grpcio/
```

**Comment by mrallanodreman** [comment]
Some one have some solution?
