### ISSUE TITLE
Instagram disconnect my account after the bot have scroll the first hashtag.

### ISSUE THREAD

**Issue by PaulPoul** [InstaPy/InstaPy#1051]
Hi,
I use InstaPy from France for weeks and thanks @timgrossmann by the way! 
Today, i have an unexpected error:
my script is running, connecting myself and go scrolling the first hashtag page, going to an account then a photo, and it seems that something disconnect my account before any interaction (like & follow).
On my console it's written: 

"--> Warning: Comment Button Not Found: May cause issues with browser windows of smaller widths
WARNING - --> Warning: Comment Action Likely Failed: Comment Element not found"

Somebody have ever seen that ?
Thanks by advance for your answers.
Romain

**Comment by Naramsim** [comment]
Maybe because it is ran on a server distant to you
