### ISSUE TITLE
Firefox for raspberry pi(Don't work)

### ISSUE THREAD

**Issue by universalxtv** [InstaPy/InstaPy#1052]
Hi! Thanks for this awesome project, but im trying to install it in my raspberry pi 3 and followed the instructions but i can't be able to install firefox. When i do apt-get install firefox it tells that doesn't exist in the repository and i added the repo of q4os. Any solution?

**Comment by ghost** [comment]
@universalxtv just type into terminal `sudo apt-get install firefox-esr` and it should work on your raspberry pi 3 

I am running v52 and it works fine

**Comment by universalxtv** [comment]
@peterglynch Thank you very much i could install firefox but now i have another issue..  when i try sudo xvfb-run python quickstart.py or python quickstart.py i get a runtimeerror exception : "could not find firefox in your system path". I have firefox-esr installed... any solution? Thank you!

**Comment by ghost** [comment]
@universalxtv could you please post your quickstart.py code?

**Comment by gitpatrickhub** [comment]
@universalxtv what version of python, selenium, and geckodriver are you using?

Can confirm it works with the below, but necessarily required to get working;

Raspbian Jessie
Python 3.5
Selenium 2.53.6
Firefox 52.3.0
Geckodriver updated to 0.19.0

**Comment by universalxtv** [comment]
@peterglynch is the original quickstart.py. @gitpatrickhub i am using the latest raspbian scratch i need to use jessie?

**Comment by universalxtv** [comment]
Sorry original quickstart.py with usefirefox=True,pagedelay=25 i am trying to follow the steps of the guide another time... my raspbian is raspbian scratch lite

**Comment by universalxtv** [comment]
I have to reinstall firefox-esr i dont know why.. but is working!!! Thanks for your help and patience:)
