### ISSUE TITLE
help Error problem 

### ISSUE THREAD

**Issue by edwardium** [InstaPy/InstaPy#1058]
hi after i download the file 
i try to run the Quickstart.py but not working 

i got this erorr

**ModuleNotFoundError: No module named 'pyvirtualdisplay'**

any help please

**Comment by timgrossmann** [comment]
@edwardium https://github.com/timgrossmann/InstaPy/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+pyvirtualdisplay
