### ISSUE TITLE
Cannot Run InstaPy

### ISSUE THREAD

**Issue by botpadawan** [InstaPy/InstaPy#1059]
Got the latest version in repo and when I run the quickstart.py, I encountered this error

> Traceback (most recent call last):
>   File "quickstart.py", line 9, in <module>
>     session.login()
>   File "/home/contact/igbots/bot1/InstaPy/instapy/instapy.py", line 184, in login
>     self.switch_language):
>   File "/home/contact/igbots/bot1/InstaPy/instapy/login_util.py", line 15, in login_user
>     "//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_b
> y_xpath
>     return self.find_element(by=By.XPATH, value=xpath)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
>     'value': value})['value']
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_respo
> nse
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
> from unknown error: missing or invalid 'entry.level'
>   (Session info: chrome=63.0.3239.84)
>   (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.10.0-40-generi
> c x86_64)

**Comment by deronsizemore** [comment]
I just downloaded the latest copy of the software and am also getting this. I'm sure it's something I'm doing wrong, but I've thus been unable to figure it out. Please post back if you resolve it.

**Comment by enrico-semrau** [comment]
Same issue here with other software - It might not really related to InstaPy. Guess its somehow Webdriver / Chromium related.

**Comment by botpadawan** [comment]
Problem solved, just update the chrome driver, see it here https://github.com/timgrossmann/InstaPy/issues/1088

**Comment by deronsizemore** [comment]
Worked for me. Thanks
