### ISSUE TITLE
Create a Telegram Group?

### ISSUE THREAD

**Issue by universalxtv** [InstaPy/InstaPy#1063]
Would you like that i create a telegram group of instapy? I think its a great idea to talk about this great tool and exchange views

**Comment by timgrossmann** [comment]
@universalxtv Good idea, feel free to do so!
We already have a [Slack Channel](https://join.slack.com/t/instapy/shared_invite/enQtMjYzNTgwMDg3MDEyLTk2NWI0MjY2MTVjYmM2NjFlYjVmMmE0ZjU1OGQ0OWM2MTQwOTc1NTIyOGVhZDEwMTFkYzFmODE5ZWIxZjhjMTQ) where a lot of people discuss what they come across

**Comment by universalxtv** [comment]
I didn't know about slack! So telegram group is not necessary then! Thanks mister!
