### ISSUE TITLE
Getting less followers and likes in the last days - instagram filtering?

### ISSUE THREAD

**Issue by Radzam** [InstaPy/InstaPy#1066]
The bot was working great for me but in the last couple of days Im getting almost no new followers or likes. Is there something going on with instagram, perhaps doing some actions against bots?

**Comment by sionking** [comment]
As long the like and follow works, there is nothing they can do since the notification which "catch" the user is exist.

**Comment by gitpatrickhub** [comment]
I’m having similar results. The bot appears to run successfully, but drastically lower results.

**Comment by gerdmueller2** [comment]
Same here.
After get InstaPy running with [CRITICAL - Wrong login data!](https://github.com/timgrossmann/InstaPy/issues/1062) the results are following:
only commenting/following are working. liking is only working in some cases.
I guess this relates to: [InstaPy Like Photo => No Like at Instagram](https://github.com/timgrossmann/InstaPy/issues/993) 

Can someone please fix this "Liking Problem - InstaPy vs. Instagram" first?

**Comment by timgrossmann** [comment]
@Radzam We have to restructure some things in order to preserve it working... This will not be minor refactors but some bigger ones that also cover the stated problem...

If you guys could help out, here's the link to support the dev: [Support InstaPy](https://www.paypal.me/supportInstaPy)

This will definitely result in stuff being resolved faster

**Comment by gitpatrickhub** [comment]
I’ve checked my log and am not experiencing the wrong login data issue and have verified several posts are being liked as indicated in log. However, in the last 2-3 days my likes and follows have dropped 75%+

**Comment by espipj** [comment]
I don't know if the issue I have is the same but for me the log says that it "liking" and "following" but not actually...
