### ISSUE TITLE
set_user_interact() got an unexpected keyword argument 'random'

### ISSUE THREAD

**Issue by nocomp** [InstaPy/InstaPy#1067]
## Current Behavior
hi, i ve followed the example file but i get this error when i run it

INFO - Session started - 2017-12-09 03:36:58
INFO - Logged in successfully!
Traceback (most recent call last):
  File "follow.py", line 8, in <module>
    session.set_user_interact(amount=5, random=True, percentage=50, media='Photo')
TypeError: set_user_interact() got an unexpected keyword argument 'random'

thxx for helping!!

here is my conf file:

session.set_user_interact(amount=5, random=True, percentage=50, media='Photo')
session.set_comments(["Cool", "Super!", "Top"])
session.follow_user_followers(['name1', 'name2', 'name3v'], amount=100, randomize=True, interact=True)
#session.unfollow_users(amount=30, onlyNotFollowMe=True, sleep_delay=120)

session.end()

**Comment by converge** [comment]
random was updated to randomize
```session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')```

**Comment by nocomp** [comment]
thxx a lot, i am trying now. no error so far, no comments either :/

**Comment by converge** [comment]
you should add the like_by_tags() action to your config file.

**Comment by nocomp** [comment]
ok i do that now, thxxx
