### ISSUE TITLE
Run Bot Through Proxy

### ISSUE THREAD

**Issue by FiboStore** [InstaPy/InstaPy#1068]
I have searched up and down for a method to run the bot through a proxy but unfortunately I had no results.

I found this line:
chrome_options.add_argument('--proxy-server=http://<178.238.231.234:3128>')

        else:
                        chromedriver_location = './assets/chromedriver'
                        chrome_options = Options()
			chrome_options.add_argument('--dns-prefetch-disable')
                        chrome_options.add_argument('--no-sandbox')
                        chrome_options.add_argument('--lang=en-US')
                        chrome_options.add_argument('--disable-setuid-sandbox')    
			chrome_options.add_argument('--proxy-server=http://<178.238.231.234:3128>')

I tried it like this but it doesn't work.
The browser doesn't recognize the proxy. It doesn't connect to the internet. 
What am I doing wrong? I really appreciate any help here.

Thank you.

**Comment by timgrossmann** [comment]
@FiboStore Remove the `<` and `>` characters

**Comment by FiboStore** [comment]
`Traceback (most recent call last):
  File "C:\Users\MrPip\Desktop\Bots\ClashRoyale - Copy\b royalegoldx.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\MrPip\Desktop\Bots\ClashRoyale - Copy\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "C:\Users\MrPip\Desktop\Bots\ClashRoyale - Copy\instapy\instapy.py", line 157
    chrome_options.add_argument('--dns-prefetch-disable')
    ^
IndentationError: unexpected indent`

That's the report I get when I try without the <  >

**Comment by FiboStore** [comment]
Traceback (most recent call last):
  File "C:\path\quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\path\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "C:\path\instapy\instapy.py", line 157
    chrome_options.add_argument('--dns-prefetch-disable')
    ^
IndentationError: unexpected indent


That's the report I receive when I try without the <   >

**Comment by timgrossmann** [comment]
@FiboStore You have to make sure that the file is correctly indented

**Comment by FiboStore** [comment]
Thank you very much, Tim.
