### ISSUE TITLE
Switch language to ¿Dutch? And fails to login

### ISSUE THREAD

**Issue by espipj** [InstaPy/InstaPy#1071]
Switch the webpage language from English (default) to Dutch and then fails to login.

https://github.com/timgrossmann/InstaPy/blob/db6b7cc4670884cb8b000cabad336b26dc865ebb/instapy/login_util.py#L16-L21

**Comment by timgrossmann** [comment]
@espipj You don't want to change the language...
The whole thing will fail at several points if you change the language, what do you think is the advantage if you change it?

**Comment by espipj** [comment]
Yes I mean in the execution Firefox starts with English for Instagram by default, and suddlenly It goes through that if clause and execute that line, which in my case the result is that the instagram webpage turns into ¿dutch? language instead continue being in english... I'm executing it from Spain.

Solved it by commeting that 2 lines.

**Comment by timgrossmann** [comment]
@espipj Which lines?

**Comment by espipj** [comment]
Lines 16 to 22

**Comment by espipj** [comment]
My fault! Just seen the firefox example and it sets the "set_switch_language" to False.
So sorry! ;)
