### ISSUE TITLE
Chrome driver keeps on crashing 

### ISSUE THREAD

**Issue by justinf102** [InstaPy/InstaPy#1072]
## Current Behavior
So every time I start the bot it would type my username in half way (sometimes not even a single letter) and then just stop and crash saying "chrome driver has stopped working"

**Comment by zknicker** [comment]
No idea why, but nuking the last 5 commits (arbitrary number but it works) and then pulling again seems to fix the problem.

    git reset --hard HEAD~5
    git pull

I've reproduced the problem and fixed it doing this twice now. Sorry, I'm not familiar enough with this codebase to be much more insightful.

**Comment by justinf102** [comment]
Didn't work, here is the error message 
![screenshot_20171211-084232](https://user-images.githubusercontent.com/31114105/33833992-79967bda-de4f-11e7-8244-ca90fa5e30f7.png)

**Comment by converge** [comment]
hello @justinf102 , your chrome driver is outdated, update it and try again. Let me know if it fixed the issue.

**Comment by thebitbrine** [comment]
same problem, have the latest chrome driver

`Error: (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)`

**Comment by justinf102** [comment]
yea still not working, I recently updated windows and it started screwing up right after, could that possibly be it?

**Comment by FreakyBoy** [comment]
I have the same problem with the lates Chromedriver... 
My solution is to downgrade Chrome to 62.0.3202.75 and now it works.

**Comment by NewyorkDev** [comment]
Here's what you have to do download Chrome Version 62.0.3202.62 (Official Build) (64-bit)
and then stop it from updating 

Easy solution :
1- Go to "C:\Program Files (x86)\Google\ and find the folder "update".
2- There are a couple of options to choose from:

 A) first method: Rename the folder:

(WORK ON WINDOWS) - Rename both the folder and the installer to whatever - you won't be able to rename the folder until you close down everything with google in the name.

**Comment by dwilliams141** [comment]
NewyorkDev's solution above worked for me. Win7 x64. Downgraded to chrome 62.0.3202.62 and disabled update.
