### ISSUE TITLE
Follow and like media likers

### ISSUE THREAD

**Issue by Oyetomi** [InstaPy/InstaPy#1075]
Hello guys , Thank you for the bot , please can you implement follow and like media likers of a particular given user? Thanks

**Comment by converge** [comment]
is this wha you need ?
https://github.com/timgrossmann/InstaPy#interact-with-specific-users

**Comment by Oyetomi** [comment]
No , bot has to follow and like the liners of a particular user lastest
picture

**Comment by Oyetomi** [comment]
@converge can you please help?

**Comment by converge** [comment]
@virginsince1997 unfortunately we don't have this feature. 

Do you know BountySource ? There is some open bounties, some are hard to develop and some have low value. If you place a nice bounty maybe someone can develop it for you.

**Comment by Oyetomi** [comment]
@converge alright thank you

**Comment by Oyetomi** [comment]
@timgrossmann @converge hello guys , please any help or update on this?
