### ISSUE TITLE
InstaPy not starting up?

### ISSUE THREAD

**Issue by sunnypatel165** [InstaPy/InstaPy#1076]
Hi, InstaPy has recently stopped to startup. 
I thought it was one of my silly modifications that broke the code, but that's not the case - just took the latest version and still breaks.
Error screen:
![image](https://user-images.githubusercontent.com/9017668/33804582-2943ca6a-ddce-11e7-9d4a-2fecca197a04.png)

Qickstart:
```Python
dont_like = ['naked', 'sex']

InstaPy(username='abc', password='abc')\
  .login()\
  .set_dont_like(dont_like) \
  .set_do_follow(enabled=True, percentage=30, times=2)\
  .set_lower_follower_count(limit = 350) \
  .like_by_tags([ '#chocolate', '#dessert', '#sweettooth', '#jj'], amount=50)\
  .end()
```

Any ideas?

**Comment by converge** [comment]
@sunnypatel165 try again using this syntax https://github.com/timgrossmann/InstaPy/blob/master/quickstart.py

**Comment by sunnypatel165** [comment]
@converge Tried already, same error!

**Comment by converge** [comment]
never saw it before. looks like you got disconnected. your selenium is 2.56 , the actual version is 3.x maybe it can help.

**Comment by sunnypatel165** [comment]
Updated selenium, no luck! :(
This is especially weird because I am working on a fresh install :(

**Comment by converge** [comment]
@sunnypatel165 what happens if you try to run it at another network ?

**Comment by sunnypatel165** [comment]
Updating Chrome Driver fixed this :/
Thanks @converge for your help :)
