### ISSUE TITLE
SyntaxError, like_util.py

### ISSUE THREAD

**Issue by maxinedotdev** [InstaPy/InstaPy#108]
Syntax error: Missing parentheses in call to 'print' in like_util.py, line 80

Original:   print "Number of Followers: ", num_followers
Correction:   print( "Number of Followers: ", num_followers)

PS: There is also a mix of single and double quotes on line 77-79 vs 80.

**Comment by AlainPilon** [comment]
Is this version dependant? Because I get no errors in the python interpreter if I dont put the parentheses.

On a separate note, I think we should use `"something {}".format("cool")` to format our strings instead of concatenations.

**Comment by maxinedotdev** [comment]
Yes, but one should follow the new protocol of Py3.

Running Py3.5.2 through Powershell and VS Code.
The linter in VS Code is, however, quite sensitive. Flags for every damn thing.

**Comment by AlainPilon** [comment]
I suggest you create a PR, go over all the code fix these in a single commit. Then again, some of the PEP8 standards are pretty anal so I dont know how @timgrossmann feels about the project following the standard.

**Comment by maxinedotdev** [comment]
> some of the PEP8 standards are pretty anal
Put that on a t-shirt.
