### ISSUE TITLE
Error message after completion

### ISSUE THREAD

**Issue by DanielSemmelrock** [InstaPy/InstaPy#1080]
## Current Behavior
![image](https://user-images.githubusercontent.com/17365427/33834491-67e35e92-de83-11e7-8cf2-499adb0e34e2.png)

**Comment by converge** [comment]
hey mate, update you chrome driver and try again. Let me know if it fixed the issue.

**Comment by FreakyBoy** [comment]
I have the same problem with the lates Chromedriver... 
My solution is to downgrade Chrome to 62.0.3202.75 and now it works.
