### ISSUE TITLE
Chromedriver is missing 

### ISSUE THREAD

**Issue by CiprianDe** [InstaPy/InstaPy#1081]
## InstaPy configuration

Hey Guys! 

I search a tool to automatize my instagram, and I found your project. 

The thing is that I did all the steps (many times) and I'm encoutering the same problem. 

![ice_screenshot_20171211-230247](https://user-images.githubusercontent.com/34459675/33856147-78a948b0-dec7-11e7-9f2b-a941d6b5b6a4.png)

Can anyone to help!

**Comment by converge** [comment]
wrong place mate.

https://github.com/ahmadudin/electron-instaPy-GUI
