### ISSUE TITLE
UTF8 tags are not supported

### ISSUE THREAD

**Issue by farshadseifi** [InstaPy/InstaPy#1082]
an issue with Persian language tags in quickstart.py
syntaxerror non-ascii character

![git1](https://user-images.githubusercontent.com/21032757/33860846-f7d398de-deef-11e7-852c-02308b4d16ab.JPG)
![git2](https://user-images.githubusercontent.com/21032757/33860847-f7feed68-deef-11e7-818b-8cc9648b5299.JPG)

**Comment by converge** [comment]
wrong place mate.

https://github.com/Nemixalone/GUI-tool-for-InstaPy-script
