### ISSUE TITLE
Can't Log in

### ISSUE THREAD

**Issue by biggt22** [InstaPy/InstaPy#1084]
Been using Instapy on ubuntu for a while. Suddenly can't get past the login in page. Tried troubleshooting but no luck so far. Any ideas?? Returning the following
![image](https://user-images.githubusercontent.com/34463187/33862518-23df5f38-deb1-11e7-9b9b-adb903b43fd6.png)
![image](https://user-images.githubusercontent.com/34463187/33862532-30221fce-deb1-11e7-8627-f0a0a082fcfb.png)

**Comment by justinf102** [comment]
same error for me

**Comment by zknicker** [comment]
Had the same issue. Updating my chromedriver in the assets folder and running 'pip install .' again fixed it.

**Comment by justinf102** [comment]
Pip install What?

**Comment by justinf102** [comment]
Nvm it worked

**Comment by biggt22** [comment]
Yes that worked, thanks!

**Comment by alessiomtt** [comment]
Same problem for me.. I really don't understand what I have to do

**Comment by Jhhoo** [comment]
pip install chromedriver and it worked

**Comment by biggt22** [comment]
ugh very frustrating... worked this morning, now getting the same issue

**Comment by timgrossmann** [comment]
@Jhhoo You don't simply `pip install chromdriver`...
Please check out the *Getting Started* part of the README, there is the link to the chromedriver download

Just download it and replace the old one in your assets folder....

**Comment by biggt22** [comment]
got it again! 2.34 seems to be the one that is working for me. Missed that the chromedriver zip files rename 1,2,3.... Kept trying the same one over and over... ><
working great again :)

**Comment by alessiomtt** [comment]
It work! Re installed everithig, update chromedriver and it work!
Sorry for all my problem and thanks!!
