### ISSUE TITLE
Issue with chrome drive

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1085]
Hi guys

I got this problem when I launch my file.

INFO - Session started - 2017-12-12 04:57:49
INFO - Logged in successfully!
INFO - Tag [1/5]
INFO - --> b'#instagood'
Traceback (most recent call last):
  File "test3.py", line 9, in <module>
    .like_by_tags(['#instagood','#picoftheday','#startup','#entrepreneurship', '#likeforfollow'], amount=70)\
  File "/root/InstaPy/instapy/instapy.py", line 632, in like_by_tags
    skip_top_posts)
  File "/root/InstaPy/instapy/like_util.py", line 180, in get_links_for_tag
    body_elem = browser.find_element_by_tag_name('body')
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 389, in find_element_by_tag_name
    return self.find_element(by=By.TAG_NAME, value=name)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 2.6.32-042stab123.9 x86_64)

Do you have a solution ? 

Cheers, 

Dylan

**Comment by jacg34** [comment]
Probably your chrome was updated: you have version 63.0.3239.84
Chromedriver 2,33 Supports Chrome v60-62, so you need to update your chromedriver.

**Comment by FreakyBoy** [comment]
I have the same problem with the lates Chromedriver... 
My solution is to downgrade Chrome to 62.0.3202.75 and now it works.

**Comment by ghost** [comment]
And how did you downgrade it ?

**Comment by davidrocket** [comment]
- Uninstall the current chrome version
- Then install the older one! You have to find out the appropriate one, sometime you have to download it manually!

**Comment by alessiomtt** [comment]
also you have to disable chrome autoupdate..
I tried this method but still not work

**Comment by converge** [comment]
chromedriver 2.34 should fix this issue

**Comment by ghost** [comment]
The point is that I already did it with the chromedriver 2.34. With the last version of the doc.

**Comment by lowtar** [comment]
Hey @dolax did you fix problem? I have a similar one.

**Comment by ghost** [comment]
Didn"t fix it actually

**Comment by ghost** [comment]
Do you have solution ?

**Comment by davidrocket** [comment]
@dolax Please try the installation on other CLEAN systems (OSs), and go through the doc carefully with ... I hope you will then understand more about the problem, then fix it by yourself. 

You can use docker, vagran... to create an virtual system (OS) on your current host system.

**Comment by ghost** [comment]
Hi David,

Already tried on other CLEAN systems.

Best regards.

2018-01-22 10:25 GMT+01:00 David <notifications@github.com>:

**Comment by davidrocket** [comment]
Please try then with firefox, to make sure all plausibel problems are solved.
