### ISSUE TITLE
set_upper_follower_count skipping users despite being below limit

### ISSUE THREAD

**Issue by Cineda** [InstaPy/InstaPy#1087]
## Expected Behavior
InstaPy to skip interaction if the user I am interacting with has more than 2000 followers.

## Current Behavior
It skips every interaction despite users having less than 2000 followers.
For example, @_llccr has only 1,087 followers and 469 following, which is way below the 2000 followers limit I have set, but InstaPy still skips her interaction.

Note: I am using **'Interact with someone else's followers'** feature.

```
INFO - Username [1/100]
INFO - --> b'________brian__________'
INFO - ---> User ________brian__________ exceeds followers limit
INFO - Username [2/100]
INFO - --> b'salty.clouds'
INFO - ---> salty.clouds account is private, skipping user...
INFO - Username [3/100]
INFO - --> b'fuwa.png'
INFO - ---> User fuwa.png exceeds followers limit
INFO - Username [4/100]
INFO - --> b'woshiikah'
INFO - ---> woshiikah account is private, skipping user...
INFO - Username [5/100]
INFO - --> b's.baoxiang_'
INFO - ---> User s.baoxiang_ exceeds followers limit
INFO - Username [6/100]
INFO - --> b'fan_r_b'
[1616:1664:1212/203909.284:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
[1616:1664:1212/203909.284:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
[1616:1664:1212/203909.285:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
[1616:1664:1212/203909.285:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
INFO - ---> fan_r_b account is private, skipping user...
INFO - Username [7/100]
INFO - --> b'_llccr'
INFO - ---> User _llccr exceeds followers limit
INFO - Username [8/100]
INFO - --> b'strictlyorganicssg'
INFO - ---> strictlyorganicssg account is private, skipping user...
INFO - Username [9/100]
INFO - --> b'ccggyy3639'
INFO - ---> User ccggyy3639 exceeds followers limit
INFO - Username [10/100]
INFO - --> b'lohwenjie_'
INFO - ---> User lohwenjie_ exceeds followers limit
```

## Possible Solution (optional)
Possibly some sort of logic error when comparing the user's followers count with the limit?

## InstaPy configuration
```
session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
session.set_do_follow(enabled=True, percentage=100)
session.set_do_like(enabled=True, percentage=100)
session.set_comments(['Awesome', 'Nice!'])
session.set_do_comment(enabled=True, percentage=20)
session.interact_user_followers(['zjiasi'], amount=100, randomize=True)
session.set_upper_follower_count(limit = 2000)

```

**Comment by Cineda** [comment]
Note: I tried removing the 'session.set_upper_follower_count(limit = 2000)' from my config but somehow InstaPy is still skipping users with exceed followers error.

```
INFO - ---> User sg.eyecandies exceeds followers limit
INFO - Username [12/100]
INFO - --> b'shembled_eggs'
INFO - ---> User shembled_eggs exceeds followers limit
INFO - Username [13/100] 
```

**Comment by Cineda** [comment]
After further tests with quickstart.py, it seems like this problem only occur when I try to 'Interact with someone else's followers'. InstaPy works perfectly fine for liking/following by geolocation or tag.

**Comment by Cineda** [comment]
Solved it. 
For some reason session.set_upper_follower_count(limit = 2000) needs to be set before the interaction command. I guess that makes sense.

**Comment by converge** [comment]
@Cineda great to hear that!

That's why show your config file is important, so we can understand better what's going on.

**Comment by TR0X** [comment]
I've the same behaviour without any limit set:

```
session = InstaPy(username=insta_username, password=insta_password, use_firefox=True, nogui=True)
session.login()
session.set_user_interact(amount=8, randomize=True, percentage=50, media='Photo')
session.set_do_like(enabled=True, percentage=50)
session.interact_user_followers(['danielkordan', 'kai.boet'], amount=10, randomize=True)

```

Any ideas?

**Comment by jeremycjang** [comment]
@TR0X Don't know if you figured it out, but I found a bodge to fix it. I believe the way the interact code is written, an upper follower count limit does have to be defined, so to workaround it you could set an upper count with a high follower number that probably no user has and it will work perfectly :)
