### ISSUE TITLE
Can't log in too

### ISSUE THREAD

**Issue by alessiomtt** [InstaPy/InstaPy#1088]
Hi guys I can't log in like https://github.com/timgrossmann/InstaPy/issues/1084, I read the comments for the issues that I linked but I really don't undersand what I have to do for fix it

**Comment by FreakyBoy** [comment]
I have the same problem with the lates Chromedriver... 
My solution is to downgrade Chrome to 62.0.3202.75 and now it works.

**Comment by alessiomtt** [comment]
Hi @FreakyBoy, I have just downgraded Chrome to  62.0.3202.75, using the latest Chromedriver and It doen't work...

What info can I give to you for  let you help me better?

**Comment by FreakyBoy** [comment]
@alessiomatt1 Can you open in Chrome this site `chrome://settings/help` and make a Screenshot ? 
Maybe you have the Auto-Update feature activated?

**Comment by alessiomtt** [comment]
![cattura](https://user-images.githubusercontent.com/34484439/33909852-3ab2a076-df8d-11e7-8e7b-9ea96a75aec4.PNG)

Yes.. autoupdate is active, now i google how to remove it !

**Comment by alessiomtt** [comment]
![cattura1](https://user-images.githubusercontent.com/34484439/33910941-ccc3a020-df90-11e7-9f87-6c5cb7880a8e.PNG)

AutoUpdate disabled, it start but look like this..

EDIT:
I think this is the problem

selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}
  (Session info: chrome=62.0.3202.75)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.16299 x86_64)

EDIT2:

Same problem but a different error now

DevTools listening on ws://127.0.0.1:12018/devtools/browser/8ebdcad4-1cce-4b25-8d2b-d5cfa7a0820a
INFO - Session started - 2017-12-13 00:48:38
CRITICAL - Sorry, Record Activity is not working on Windows. We're working to fix this soon!
Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    session.login()
  File "C:\Users\insta\Desktop\InstaPy-master\instapy\instapy.py", line 219, in login
    self.switch_language):
  File "C:\Users\insta\Desktop\InstaPy-master\instapy\login_util.py", line 45, in login_user
    ActionChains(browser).move_to_element(login_button).click().perform()
  File "C:\Users\insta\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\action_chains.py", line 83, in perform
    action()
  File "C:\Users\insta\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\action_chains.py", line 293, in <lambda>
    Command.MOVE_TO, {'element': to_element.id}))
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by tierten** [comment]
I have a similar issue. I run it on 2 accounts. After updating both accounts' chromedriver.exe, one account is able to log in, and the other one experiences the same login problem.

**Comment by alessiomtt** [comment]
Fresh reinstalled everithing but still compile the wrong form, seem that doesn't click on the Log in button for switch the div

![cattura](https://user-images.githubusercontent.com/34484439/33934356-f1175cf6-dff8-11e7-8acf-27f08102264f.PNG)

**Comment by FreakyBoy** [comment]
@alessiomatt1 Don`t click in die Chrome windows when you start your script. I have the problem only when I click with the mouse in die Chrome windows or try to resize the window... 

Start your script and do nothing :)

**Comment by NewyorkDev** [comment]
THE FIX-->
Here's what you have to do download Chrome Version 62.0.3202.62 (Official Build) (64-bit)
and then stop it from updating 

Easy solution :
1- Go to "C:\Program Files (x86)\Google\ and find the folder "update".
2- There are a couple of options to choose from:

 A) first method: Rename the folder:

(WORK ON WINDOWS) - Rename both the folder and the installer to whatever - you won't be able to rename the folder until you close down everything with google in the name.

**Comment by 6seven8** [comment]
I am getting this error:

'Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}'

I tried downgrading chrome to 62 but when the instapy script was initiated it would open the chrome window then stick on ;:data in the url bar. Nothing would happen. 

Also, I was getting an error that selenium needed chrome 68+ while I was on chrome 62

Any thoughts?

**Comment by gitpatrickhub** [comment]
update the login_util.py as detailed in issue #3020
