### ISSUE TITLE
Wrong Login Data - No time to fill in security code

### ISSUE THREAD

**Issue by hestuppfodarn** [InstaPy/InstaPy#1090]
## Expected Behavior
When security code is requested, we should have time to access our email, get the security code and enter it.

Also experiences a major problem with login in, in general. 

## Current Behavior
Cannot log in, since Instagram recognises the login as a suspicious login attempt.
Then going to my email to get the security code, the browser with Instagram shuts down before the security email gets delivered (some delay in between)

## Possible Solution (optional)
Longer the time until the browser closes. 

```
17-12-13 09:52:02 INFO - Session started
17-12-13 09:52:33 CRITICAL - Wrong login data!
17-12-13 09:52:36 INFO - Session ended - 2017-12-13 09:52:36
17-12-13 09:52:36 INFO - --------------------
```

Running Mac OS, from my home IP and home computer. 
- Also, this is only a problem when login in with InstaPy, if I login using the browser myself (manually) it's no problem.

**Comment by davidrocket** [comment]
Without having a change in instapy, You can try to copy the security code of previous mail, then paste in when being asked!  

In some case, instagram will "always" keep asking the security code!

**Comment by converge** [comment]
did you test #1079 ?

**Comment by hestuppfodarn** [comment]
@davidrocket, I did and  it worked, but next time the script ran the same problem occurred. Did manage to verify 3 times, but the 4th time it requests security code again
@converge, haven't tried it. Will do later, thanks!
