### ISSUE TITLE
like_by_tags amount=75 -->different amount in session INFO - [1/18]

### ISSUE THREAD

**Issue by gerdmueller2** [InstaPy/InstaPy#1091]
I set the like_by_tags amount=75 but in the session (running on aws ubuntu) it likes a different amount. Here [1/18]

## Expected Behavior
INFO - [1/75]

## Current Behavior
INFO - [1/18]

## InstaPy configuration
session.like_by_tags(['test'], amount=75)

**Comment by travisday** [comment]
I am having a similar issue, I set mine to '100' but it shows INFO - [1/12]

**Comment by CharlesCCC** [comment]
Are you guys using smart_tag ? if yes, it possible the top tag from the website only have 18 not 75.

**Comment by gerdmueller2** [comment]
no, i am only using:

```
session.set_upper_follower_count
session.set_do_comment
session.set_comments
session.set_dont_include
session.set_dont_like
session.set_ignore_users
```
and
`session.like_by_tags`


and at the beginning:

```
session.browser.get("https://www.instagram.com")
for cookie in pickle.load(open("instacookies.pkl", "rb")):
        session.browser.add_cookie(cookie)
```



i also changed the amount to 200, and it does not change anything: its: `INFO - [X/18]`

**Comment by johnstsai** [comment]
same issue, follow

**Comment by thomsonza** [comment]
Same issue, I get different results when running from my laptop and from a linux server. Linux server [x/18] and laptop shows [x/21] with the exact same script. Simplified my script as follows, no change. 

```
session = InstaPy(username=insta_username, password=insta_password)
session.login()
session.like_by_tags(['tag'],amount=37)
session.end()
```

Update: Laptop is running an older version of InstaPy

**Comment by thomsonza** [comment]
Tested this with another account and seems to be account specific. It works fine on one account, not on the other.

**Comment by sionking** [comment]
maybe Instagram loading more images got stuck in this moment/account.

**Comment by javier2k2** [comment]
Same issue, getting [x/21] on Windows 10, I set it to 97

**Comment by Necromant1k** [comment]
```INFO - [1/18]``` - you have 18 tags and for each tag = 75 likes

**Comment by goobz** [comment]
I found the problem.

Some accounts on Insta may be flagged, because of their growth.
Because of that, if you search for tags the divs in the "Latest posts" section get replaced instead of just added.

In line 189 following Code scrolls the page and the divs get replaced:
`# scroll down to load posts
            for i in range(int(ceil(amount/12))):
                browser.execute_script(
                    "window.scrollTo(0, document.body.scrollHeight);")
                sleep(2)`

even if you would create a list(set()), line 256 would reset everything:
`link_elems = main_elem.find_elements_by_tag_name('a')`

for now i did following workaround:
`def get_links_for_tag(browser,
                      tag,
                      amount,
                      logger,
                      media=None,
                      skip_top_posts=True):
    """Fetches the number of links specified
    by amount and returns a list of links"""
    if media is None:
        # All known media types
        media = ['', 'Post', 'Video']
    elif media == 'Photo':
        # Include posts with multiple images in it
        media = ['', 'Post']
    else:
        # Make it an array to use it in the following part
        media = [media]

    browser.get('https://www.instagram.com/explore/tags/'
                + (tag[1:] if tag[:1] == '#' else tag))
    # update server calls
    update_activity()
    sleep(2)

    # clicking load more
    body_elem = browser.find_element_by_tag_name('body')
    sleep(2)

    #new
    if skip_top_posts:
        main_elem = browser.find_element_by_xpath('//main/article/div[2]')
    else:
        main_elem = browser.find_element_by_tag_name('main')

    link_elems = [link_elem.get_attribute('href') for link_elem in main_elem.find_elements_by_tag_name('a')
             if link_elem and link_elem.text in media]
    #new

    abort = True
    try:
        load_button = body_elem.find_element_by_xpath(
            '//a[contains(@class, "_1cr2e _epyes")]')
    except:
        try:
            # scroll down to load posts
            logger.warning(
                'Load button not found, scrolling now')
            for i in range(int(ceil(amount/12))):
                browser.execute_script(
                    "window.scrollTo(0, document.body.scrollHeight);")
                logger.warning(
                    'scrolling')
                sleep(4)
                #new
                if skip_top_posts:
                    temp_main = browser.find_element_by_xpath('//main/article/div[2]')
                else:
                    temp_main = browser.find_element_by_tag_name('main')
                temp_elems = [link_elem.get_attribute('href') for link_elem in temp_main.find_elements_by_tag_name('a')
                         if link_elem and link_elem.text in media]
                link_elems = link_elems + temp_elems
                #new
        except:
            logger.warning(
                'Load button not found, working with current images!')
        else:
            abort = False
            body_elem.send_keys(Keys.END)
            sleep(2)
            # update server calls
            update_activity()
    else:
        abort = False
        body_elem.send_keys(Keys.END)
        sleep(2)
        load_button.click()
        # update server calls
        update_activity()

    body_elem.send_keys(Keys.HOME)
    sleep(1)


    # Get links
    #if skip_top_posts:
    #    main_elem = browser.find_element_by_xpath('//main/article/div[2]')
    #else:
    #    main_elem = browser.find_element_by_tag_name('main')

    #link_elems = main_elem.find_elements_by_tag_name('a')
    link_elems= list(set(link_elems))
    total_links = len(link_elems)
    logger.warning(total_links)


    links = []
    filtered_links = 0
    try:
        if link_elems:
            #links = [link_elem.get_attribute('href') for link_elem in link_elems
            #         if link_elem and link_elem.text in media]
            links = link_elems
            filtered_links = len(links)

    except BaseException as e:
        logger.error("link_elems error {}".format(str(e)))

    while (filtered_links < amount) and not abort:
        amount_left = amount - filtered_links
        # Average items of the right media per page loaded
        new_per_page = ceil(12 * filtered_links / total_links)
        if new_per_page == 0:
            # Avoid division by zero
            new_per_page = 1. / 12.
        # Number of page load needed
        new_needed = int(ceil(amount_left / new_per_page))

        if new_needed > 12:
            # Don't go bananas trying to get all of instagram!
            new_needed = 12

        for i in range(new_needed):  # add images x * 12
            # Keep the latest window active while loading more posts
            before_load = total_links
            body_elem.send_keys(Keys.END)
            # update server calls
            update_activity()
            sleep(1)
            body_elem.send_keys(Keys.HOME)
            sleep(1)
            link_elems = link_elems #main_elem.find_elements_by_tag_name('a')
            total_links = len(link_elems)
            abort = (before_load == total_links)
            if abort:
                break

        #links = [link_elem.get_attribute('href') for link_elem in link_elems
        #         if link_elem and link_elem.text in media]
        links = link_elems
        filtered_links = len(links)
        
    return links[:amount]`

I know, it is everything else from clean, but it works. Everything that isn't needed is commented out. If someone can clean this up make a pull request, feel free :)

Edit: Sorry for the butchered code blocks, i hope you can figure it out...

**Comment by gerdmueller2** [comment]
i changed the file `like_util.py` as you said.

but now the session ended with and TypeError:
```
File "/home/ubuntu/InstaPy/instapy/instapy.py", line 645, in like_by_tags
    for i, link in enumerate(links):
TypeError: 'NoneType' object is not iterable
```


this is what the console printed...

```
INFO - Session started - 2018-01-05
INFO - Logged in successfully!
INFO - Tag [1/7]
INFO - --> TAG XXXXXX
WARNING - Load button not found, scrolling now
WARNING - scrolling
WARNING - scrolling
WARNING - scrolling
WARNING - scrolling
WARNING - scrolling
WARNING - 96
INFO - Session ended - 2018-01-05
```

can some one help / fix it?

**Comment by fisheseses** [comment]
Having the same error.
