### ISSUE TITLE
ERROR - Firefox on Raspberry - Webdriver exception: window shareddata is undefined

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1093]
## Expected Behavior
Working 
## Current Behavior
Webdriver exception: "window._sharedData si undefined"

**Comment by gitpatrickhub** [comment]
I am experiencing the same issue and have been for some time now, but is intermittent.

**Additional information:** 
after the error message in the description is;
```
at anonymous (https://www.instagram.com/accountname line 69 > function: 1) at handleEvaluateEvent (https://www.instagram.com/accountname:69)
```

**Comment by ghost** [comment]
@gitpatrickhub same. Sometimes it stops, sometimes works

**Comment by gitpatrickhub** [comment]
This is the only thing I could find that appears related on a google search;

https://reformatcode.com/code/javascript/selenium-webdriver-executescript-can39t-execute-custom-methods-and-external-javascript-files

**Comment by gitpatrickhub** [comment]
@ffext are you running more than one account when this happens? It seems to only happen when I run 2 accounts at the same time and wondering if it is related to memory.

**Comment by ghost** [comment]
@gitpatrickhub no, only 1 account running

**Comment by randomdev42** [comment]
After a lot of experimentation and running with a head view this seem to happen when more than X number of like are done on the same hashtag and instagram throws the "Sorry, something went wrong" error page. X for my testing seems to be 50ish but may be scaled to the number of followers you have. I have not seen the error when using under 40 likes per hashtag.

The resolution to this I think should be detecting the something went wrong page, creating a correct error and stopping the session.
