### ISSUE TITLE
syntaxerror: Unexpected Identifier

### ISSUE THREAD

**Issue by lukahans** [InstaPy/InstaPy#1095]
I've been using instapy to like photo's from certain users, however, an error occurs after the script likes a certain amount of pictures (sometimes 4, sometimes 10). I installed on two different computers - chrome web driver is up to date.

I appreciate any help! Thanks in advance!

**The following error**

 File "/Users/lukahans/InstaPy/instapy/instapy.py", line 1026, in interact_by_users
    self.logger)
  File "/Users/lukahans/InstaPy/instapy/comment_util.py", line 50, in comment_image
    "arguments[0].value = '" + rand_comment + " ';", comment_input[0])
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 543, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.evaluate threw exception: SyntaxError: Unexpected identifier
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.12.4 x86_64)

**Comment by lukahans** [comment]
Update: I’ve installed it on a windows machine and the same error occurs

**Comment by saxenauts** [comment]
Same. Can't understand. What's the fix?

**Comment by lukahans** [comment]
No idea - still doesn’t work

**Comment by SHELA** [comment]
I have issue when use ' symbol in text.
` browser.execute_script("arguments[0].value = '" + rand_comment + " ';", comment_input[0])`
they have  '" + rand_comment + " ' so in JS it's error. 

you can replace to:
` browser.execute_script( 'arguments[0].value = "' + rand_comment + ' ";', comment_input[0])` 

or use try except. so have 1 variant with ' and in except have ". or remove from text '

**Comment by ghoeffner** [comment]
@SHELA got the right answer. The problem resides in using ' - it's not escaped properly.

**Comment by ghost** [comment]
@SHELA It could be nice to do a **pull request** of this. 
Each time I clone the project I get this issue.

**Comment by mkMcMahon** [comment]
I've recently been playing with instapy and was having this issue. Couldn't figure out problem until I saw this thread. Not sure if other newbies would encounter a similar situation.
