### ISSUE TITLE
How can I follow by tag?

### ISSUE THREAD

**Issue by alessiomtt** [InstaPy/InstaPy#1096]
I know that maybe it's a very stupid question, but how can I follow a profile that have posted a photo whith a specific tag without liking the image?

**Comment by mvaldes14** [comment]
you mean following people with certain tags in their posts?
or you want to see all posts tied to a tag sort of like twitter?

**Comment by camilaavilarinho** [comment]
I did a modification of the function like_by_tags and was possible to follow the user without liking the image. It worked for me, but I don't know if is good enough to do a PR...

**Comment by timgrossmann** [comment]
@camilaavilarinho Please feel free to share your changes, I'm pretty sure that all of us can work on it together if that is a feature people want to have.

Thank you very much and Happy Holidays!
