### ISSUE TITLE
got float

### ISSUE THREAD

**Issue by iflybrains** [InstaPy/InstaPy#11]
Hi, 

first of all GREAT work!
Liked your reply to the first "issue" :)

When executing the script it all works till it loads the first hashtag and tries to like some.
 
I see this in terminal:

    for _ in range(new_needed):  # add images x * 12
TypeError: range() integer end argument expected, got float.

What do I need to change?
Thanks!
M

**Comment by timgrossmann** [comment]
Could you provide some context? 
What number of images did you enter as "amount" here?
```python
session.like_by_tags([], amount=100)
```

Really weird case because at this line I do:

```python
ceil((amount - 33) / 12)
```

I'll update the codebase to do:

```python
int(ceil((amount - 33) / 12))
```


###### Should be an edge case... Please still provide the amount you entered

**Comment by timgrossmann** [comment]
Should be solved by [this commit](https://github.com/timgrossmann/InstaPy/commit/a2b0d60698254a51b01a99d942d8983d87c429d4)

##### So just do a `git pull` and you should be ready to go 😉
