### ISSUE TITLE
problem with chrome driver , ubuntu 512mb RAM

### ISSUE THREAD

**Issue by sugionodjojo** [InstaPy/InstaPy#110]
hello,

have this issue 

root@ubuntu-512mb-nyc2-01:/InstaPy# python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    InstaPy(username=os.getenv('xxxxxx'), password=os.getenv('xxxxxx'))\
  **File "/InstaPy/instapy/instapy.py", line 34, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)**
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-66-generic x86_64)

**Comment by eduardocalazansjr** [comment]
Read the entire documentation

**Make sure to use the 1GB RAM version (or better)**

**Comment by jasezzx** [comment]
Hi, 
I still got same errors after upgrading to 1GB RAM version. please help. Thanks!

root@ubuntu-512mb-sfo2-01:~/InstaPy# free
              total        used        free      shared  buff/cache   available
Mem:        1016180       46764      575400        3128      394016      789852
Swap:             0           0           0
root@ubuntu-512mb-sfo2-01:~/InstaPy#
root@ubuntu-512mb-sfo2-01:~/InstaPy# python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    InstaPy(username='test', password='test')\
  File "/root/InstaPy/instapy/instapy.py", line 34, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-72-generic x86_64)

**Comment by sugionodjojo** [comment]
first , it is not 1gb, it is 512 mb,

and you might want to chmod +x and chmod 755 , chromedriver in assets

read more on https://github.com/timgrossmann/InstaPy/issues/48

**Comment by jasezzx** [comment]
Thanks for your quick response. I have already done what you mentioned.
and my droplet is 1GB, you could see the attached screenshot and also total mem info below is 1016180. I guess just the name hasn't been updated. thanks


root@ubuntu-512mb-sfo2-01:~/InstaPy/assets# ls -l
total 7332
-rwxr-xr-x 1 root root 7500280 Apr  3 18:21 chromedriver
-rw-r--r-- 1 root root     489 Apr 18 07:00 unicodes.md
root@ubuntu-512mb-sfo2-01:~/InstaPy/assets# free
              total        used        free      shared  buff/cache   available
Mem:        1016180       49424      569676        4408      397080      785880
Swap:             0           0           0
root@ubuntu-512mb-sfo2-01:~/InstaPy/assets# 
<img width="493" alt="screen shot 2017-04-18 at 6 33 38 pm" src="https://cloud.githubusercontent.com/assets/5484028/25121670/d25a1cc6-2465-11e7-8d37-d06d33476860.png">

**Comment by sugionodjojo** [comment]
have you uncomment #27 and #28 on instapy.py file? related to pyvirtualdisplay
/InstaPy/assets/instapy/instapy.py

**Comment by jasezzx** [comment]
Yes, seems the default setting in instapy.py file is uncommented like below.

class InstaPy:
  """Class to be instantiated to use the script"""
  def __init__(self, username=None, password=None):
    #self.display = Display(visible=0, size=(800, 600))
    #self.display.start()
    chrome_options = Options()

**Comment by sugionodjojo** [comment]
delete the #, so that script can work (uncomment)

**Comment by jasezzx** [comment]
So sorry. What a stupid mistake. Thank you so much: D
