### ISSUE TITLE
Whether it is liking pictures, following or unfollowing people, the program stops midway and returns the following error?

### ISSUE THREAD

**Issue by NoobTove** [InstaPy/InstaPy#1103]
## Expected Behavior
This program has been so wonderful to use, I sometimes encounter this error repeatedly. For context, I entered 300 photos as a parameter for liking photos on my local pc.
## Current Behavior
It stopped at about 148 pictures and returned the following lines.
<img width="873" alt="error" src="https://user-images.githubusercontent.com/29563338/34095916-589bc0ca-e3f9-11e7-9c0f-843a3313086e.PNG">
## InstaPy configuration
My InstaPy was configured in the following way I believe:
<img width="609" alt="instapy config" src="https://user-images.githubusercontent.com/29563338/34095998-b67116dc-e3f9-11e7-8f44-6786d5f31698.PNG">

Thank you so much!

**Comment by sionking** [comment]
poor internet connection ?

**Comment by superjacke** [comment]
Same issue?
<a href="https://github.com/SeleniumHQ/selenium/issues/5189#issuecomment-351605839" class="issue-link js-issue-link tooltipped tooltipped-ne" data-error-text="Failed to load issue title" data-id="280351139" data-permission-text="Issue title is private" aria-label="SeleniumHQ/selenium#5189 (comment), Chrome Driver, ERROR:process_metrics.cc(105)] NOT IMPLEMENTED">SeleniumHQ/selenium#5189 (comment)</a>

**Comment by NoobTove** [comment]
It was because of the internet connection and thank you :)
