### ISSUE TITLE
FollowerNum.txt does not log username

### ISSUE THREAD

**Issue by thomsonza** [InstaPy/InstaPy#1106]
When using multiple accounts in InstaPy, the FollowerNum.txt does not log the username when logging the follower count of the user, making it difficult to differentiate between user account follower data. 

I am curious as to whether anyone else is using this data and if it would be useful to anyone else. Happy to do a pull request and make the change. 

## Expected Behavior
```
2017-12-18 22:36 7870 joeblogs
2017-12-18 22:45 813 peterpan
```
## Current Behavior
```
2017-12-18 22:36 7870
2017-12-18 22:45 813 
```
## Possible Solution (optional)
Modify print_log_writer.py to also log the username as part of the output:
```
    with open('./logs/followerNum.txt', 'a') as numFile:
        numFile.write(
            '{:%Y-%m-%d %H:%M} {} {}\n'.format(datetime.now(), followed_by or 0,username))
```

**Comment by CharlesCCC** [comment]
what would be better is have one log file for each user. so it will be
`followerNum-joeblogs.txt`
`followerNum-peterpan.txt`
etc.

This could go with other files as well.
e.g.
`general-joeblogs.txt`
`general-peterpan.txt`
