### ISSUE TITLE
Where are the unfollowed users stored?

### ISSUE THREAD

**Issue by tibor-stefan** [InstaPy/InstaPy#1110]
I'm new to instapy and I'm trying to find out where instapy stores the users, which have been followed and unfollowed, to make sure they are not followed a second time.

My understanding is, that the log/usernameFollowedPool.csv keeps the actual followed users, but not the ones who have been followed previously.

Thanks for your help!

**Comment by sionking** [comment]
there is a json file in this folder with the number of times been followed.

**Comment by tibor-stefan** [comment]
Well, the json file stores the username of the account which followers I follow - but not a list of the individual users. in my case it just has one line, but it would need to have a list of hundred users...right?

It just says:
{"username": 10}

**Comment by nilkesede** [comment]
instapy already have this feature, but I think there's a bug. this pr fix it #1118

**Comment by timgrossmann** [comment]
@TiborMuc Can you please try again?

**Comment by tibor-stefan** [comment]
@timgrossmann 
It doesn't work.
Now, it stores all the users in the jason file like:
"username":timesfollowed
But - it ignores the count. 
I was running the following scripts twice, with unfollowing them in between, but it just increases the count from 1 to 2 instead of bypassing the user...

session.login()
session.set_do_follow(enabled=True, times=1)
session.follow_user_followers(['famous_account'], amount=5, randomize=False, sleep_delay=60)

What it should do from my understanding, is follow 5 followers of "famous_account" from the top without randomising, checking if they are in the json file already.
instead it ignores, that they are already listed in the json file and simply increases the count by one.

Any idea? your help is very much appreciated!

Tibor

**Comment by daz99m** [comment]
ERROR - set_automated_followed_pool error [Errno 2] No such file or directory: './logs/xxxxxxx_followedPool.csv
anyone know a fix to this error?
