### ISSUE TITLE
ImportError: No module named clarifai.rest

### ISSUE THREAD

**Issue by billycoco6** [InstaPy/InstaPy#1111]
I have installed clarifai using 'pip install clarifai' and can use it in the command line, however, when I tried running quickstart.py. I got an import error said No module named clarifai.rest.

<img width="572" alt="screen shot 2560-12-20 at 16 48 03" src="https://user-images.githubusercontent.com/13674274/34200981-9d9a55c6-e5a5-11e7-8964-568739349797.png">

I am appreciated with every help. Thank you!

**Comment by billycoco6** [comment]
This screenshot just to show that I can run clarifai from the command line

**Comment by converge** [comment]
hey, what python --version and pip --version shows ?

**Comment by billycoco6** [comment]
python --version => Python 2.7.12
pip --version => pip 9.0.1 from /home/billy/.local/lib/python2.7/site-packages (python 2.7)

**Comment by converge** [comment]
```pip install clarifai ; python quickstart.py```

**Comment by billycoco6** [comment]
That's suppose to work. I installed clarifai already, but still getting the error. I save the screenshot of the problem below.

![untitled](https://user-images.githubusercontent.com/13674274/34210885-f2bea218-e5c9-11e7-8553-16a112b5ba88.png)

**Comment by converge** [comment]
no idea..

I shouldn't say that, but a workaround is comment this line
```from clarifai.rest import ClarifaiApp, Image as ClImage```
from clarifai_util.py

**Comment by billycoco6** [comment]
The problem solved, I have multiple python versions and have not installed clarifai to python 2.7. In case any one found this issue, 
 -> run 'pip list' to see whether you have installed clarifai.
If not,
 -> run 'sudo python -m pip install clarifai', so it will install to the right python version (2.7)

**Comment by GUNJAN10** [comment]
Did you managed to get rid of below error ? I tried all what ou have suggested above but still same error. 

from clarifai.rest import ClarifaiApp
ImportError: No module named rest

**Comment by zadro** [comment]
I tried all above as well and still getting:

ImportError: No module named clarifai.rest

Did anyone solve this? Thanks.

**Comment by zadro** [comment]
this solved the problem for me:

sudo pip install clarifai==2.0.20
