### ISSUE TITLE
Q: why inappropriate do unfollow?

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#1114]
## Expected Behavior
skip next user / make it adjustable.

## Current Behavior
if image found inappropriate we do unfollow (I disabled it)

What do you think? many users have there own following that can be sometimes inappropriate we shall not do unfollow to them.

**Comment by ldevalbray** [comment]
You can specify 

`session.set_dont_include(['friend1', 'friend2', 'friend3'])`

for the friends you don't want to act on (unfollow / comment)

**Comment by sionking** [comment]
Sure, but you work with 20 different accounts, they updated their following regularly, they won't add it to this list! I think it should not do unfollow, no matter what, I don't see the logic?

**Comment by ldevalbray** [comment]
@sionking 
Well yes there should be options to choose wether or not you want to follow/unfollow/like ... act or not on inapproriate accounts I guess

**Comment by converge** [comment]
it can be done extending blacklist feature
