### ISSUE TITLE
INTERACT WITH USER LATEST MEDIA

### ISSUE THREAD

**Issue by Oyetomi** [InstaPy/InstaPy#1115]
```
INTERACT WITH USER LATEST MEDIA
```
Is it possible to Follow and like the likers of a particular user latest media

**Comment by timgrossmann** [comment]
@virginsince1997 No, not yet...

This will be easy to implement once we use some of the graphql endpoints that let us retrieve all the likers, comments etc. of each specific post... You can check out the docu here: https://github.com/timgrossmann/InstaPy-Research

**Comment by Oyetomi** [comment]
@timgrossman , alright thank you , I anticipate👍

**Comment by timgrossmann** [comment]
@virginsince1997 There always is the possibility of increasing the bounty for that specific task, this will get more devs interested in implementing it!
[Issue](https://github.com/timgrossmann/InstaPy/issues/1073)

Even a small amount of money (if several people do it), will give the feature quite a boost!
https://www.bountysource.com/issues/52527329-priority-refactor-change-scrolling-parts-to-graphql

**Comment by Oyetomi** [comment]
@timgrossmann alright I added something to the bounty , cheers👍

**Comment by timgrossmann** [comment]
@virginsince1997 Awesome! This will be a huge step for InstaPy!
Once we have the graphQL endpoints in use, we will be able to easily implement many more features that not only include the likers of a picture.

This will be huge, so thanks for helping out!

**Comment by Oyetomi** [comment]
Thank you 👍

**Comment by Oyetomi** [comment]
@timgrossmann please any help or update on this?
