### ISSUE TITLE
It doesn't follow anyone and gives TypeError 

### ISSUE THREAD

**Issue by harrycha** [InstaPy/InstaPy#1119]
I read another issue in which it was said to update, yet I downloaded it 2 days ago.
How come it doesn't follow? 

CRITICAL - Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO - Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    session.follow_user_followers(['xxxxxxxx' ], amount = 30, random=False, delay=730)
TypeError: follow_user_followers() got an unexpected keyword argument 'random'
[11896:7108:1221/171931.694:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
[11896:7108:1221/171931.695:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
[11896:7108:1221/171931.695:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
[11896:7108:1221/171931.696:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED

**Comment by converge** [comment]
```session.follow_user_followers(['xxxxxxxx' ], amount = 30, random=False, delay=730)```
randomize , not random.

**Comment by harrycha** [comment]
No the xxxxxx was a generic user I gave, but it does that with any user.

**Comment by converge** [comment]
no.. you're doing it:
```session.follow_user_followers(['xxxxxxxx' ], amount = 30, random=False, delay=730)```
and the correct is:
```session.follow_user_followers(['xxxxxxxx' ], amount = 30, randomize=False, delay=730)```

**Comment by harrycha** [comment]
I went back into quickstart.py and changed random to randomize it however it doesn't show up when command is launched. I am running this from the gui

**Comment by converge** [comment]
are you using the last version ? what's the output of quickstart.py ?

**Comment by harrycha** [comment]
I believe so, the gui and the codes are the newest, I pulled from the master branch 2 days ago. I believe this is the output builtins.TypeError: follow_user_followers() got an unexpected keyword argument 'delay'

**Comment by converge** [comment]
are you using the GUI ? it uses another InstaPy core version, don't know how to help you with that, maybe they can help you here https://github.com/Nemixalone/GUI-tool-for-InstaPy-script

**Comment by harrycha** [comment]
Ended up fixing it by ditching the gui and just plugging the follow code in session.follow_user_followers(['xxxxxxxx'], amount=50, randomize=False, sleep_delay=600) thanks!
