### ISSUE TITLE
Fix OSx and Linux scripts

### ISSUE THREAD

**Issue by eduardocalazansjr** [InstaPy/InstaPy#112]
I've tried to use the automate installation scripts and the OSx one didn't work OOB.
And i think that the Linux scripts could be merged in only one, since there's how to distinguish if is x86 or x86_64.

- [x] Fix the OSx script and make sure that it works with OOB OSx installations
- [x] Merge the two linux scripts into just one
- [x] Check if is possible to move them to another folder (just to cleanup)

**Comment by binhonglee** [comment]
> Check if is possible to move them to another folder (just to cleanup)

Pretty sure it is. Just the pathing needs to be updated.

**Comment by timgrossmann** [comment]
@binhonglee Could you submit a PR for the cleanup and update the pathing?
