### ISSUE TITLE
Newbie here.  Need some help no len issue

### ISSUE THREAD

**Issue by Vesuvius333** [InstaPy/InstaPy#1127]
Hi All,

I'm getting this error"

TypeError: object of type 'NoneType' has no len ()

A new instance of Google Chrome is opened but nothing happens afterwards.  I have populated the instapy username and password field.  Please let me know what else I need to check.  Thanks I really appreciate it!

**Comment by converge** [comment]
hi @Vesuvius333 , please paste your setup (quickstart.py) and the full error message.

**Comment by daz99m** [comment]
this is my setup, how do i make it run 24/7? as it stops after a few hours and also how do i make it unfollow any random user

```
from instapy import InstaPy

insta_username = ''
insta_password = ''

# if you want to run this script on a server,
# simply add nogui=True to the InstaPy() constructor
session = InstaPy(username=insta_username, password=insta_password)
session.login()

# set up all the settings
session.set_upper_follower_count(limit=2500)
session.set_lower_follower_count(limit = 200)
session.set_do_comment(True, percentage=33)
session.set_comments(['Great shot!', 'nice shot!', 'Nice!'])
session.set_dont_include([''])
session.set_dont_like(['pizza', 'girl'])
session.set_do_follow(enabled=True, percentage=50, times=600)
# do the actual liking
session.like_by_tags(['', ], amount=300)

# end the bot session
session.end()
```

**Comment by converge** [comment]
@daz99m like by tags amount=300 is too much, go for 40, 60..

what's the error ? InstaPy is at development, it's common to see errors. When you serve full error informations, it's easier to someone try to fix it.

**Comment by daz99m** [comment]
i dont get an error code , it just says that the session ended.
