### ISSUE TITLE
Latest version not working correctly.

### ISSUE THREAD

**Issue by thatc0der** [InstaPy/InstaPy#1128]
## Expected Behavior
Previous working behavior where I get a successful log in
## Current Behavior
root@haginCodes-t440p:~/InstaPy# python3 hagin.py 
INFO - Session started - 2017-12-23 00:38:55
Cookie file not found, creating cookie...
Unable to locate email or phone button
CRITICAL - Wrong login data!
INFO - Session ended - 2017-12-23 00:40:26
INFO - --------------------

## Possible Solution (optional)
Remove updated materials like cookies and stuff
## InstaPy configuration
Latest commit

**Comment by sebmer-com** [comment]
yeah, sadly it doesn't  work its the same error in #1123

**Comment by converge** [comment]
@HaginCodes @Basti922 how is your config (quickstart) file ?

**Comment by Basti922** [comment]
from instapy import InstaPy

InstaPy(username='katjademming.lifecoach', password='LC2014kd%!', nogui=True)\
  .login()\
  .set_do_comment(True, percentage=30)\
  .set_comments([u':v: :v: :v:', u'wow', u':ok_hand: :ok_hand: :ok_hand:', ':heart_eyes: :heart_eyes: :heart_eyes:', 'nice <3'])\
  .set_upper_follower_count(limit = 15000)\
  .set_lower_follower_count(limit = 20)\
  .set_dont_like(['child', 'erotic', 'men', 'sex', 'fotze', 'injur', 'blood' ,'porn' ,'bbw' ,'vagina' ,'dick' ,'penis' ,'abs' ,'muscle'])\
  .set_ignore_if_contains(['naked', 'sex' ,'men' , 'man' ,'diba' ,'commerzbank' ,'deutschebank' ,'boy'])\
  .set_use_clarifai(enabled=True, api_key='ba687e8b45874ea4a4abbf943aff59be')\
  .clarifai_check_img_for(['nsfw'])\
  .like_by_tags(['mindset', 'coaching', 'behappy', 'giessen', 'marburg','lich', 'leben', 'sinndeslebens'], amount=35)\
  .set_user_interact(amount=5, random=True, percentage=50, media='Photo')\
  .like_by_feed(amount=100, randomize=True, unfollow=True, interact=True)\
  .set_do_follow(enabled=True, percentage=5, times=1)\
  .unfollow_users(amount=20, onlyInstapyFollowed = True )\
  .end()

**Comment by sebmer-com** [comment]
from instapy import InstaPy

InstaPy(username='XXX', password='XXX', nogui=True)\
  .login()\
  .set_do_comment(True, percentage=30)\
  .set_comments([u':v: :v: :v:', u'wow', u':ok_hand: :ok_hand: :ok_hand:', ':heart_eyes: :heart_eyes: :heart_eyes:', 'nice <3'])\
  .set_upper_follower_count(limit = 15000)\
  .set_lower_follower_count(limit = 20)\
  .set_dont_like(['child', 'erotic', 'men', 'sex', 'fotze', 'injur', 'blood' ,'porn' ,'bbw' ,'vagina' ,'dick' ,'penis' ,'abs' ,'muscle'])\
  .set_ignore_if_contains(['naked', 'sex' ,'men' , 'man' ,'diba' ,'commerzbank' ,'deutschebank' ,'boy'])\
  .set_use_clarifai(enabled=True, api_key='ba687e8b45874ea4a4abbf943aff59be')\
  .clarifai_check_img_for(['nsfw'])\
  .like_by_tags(['mindset', 'coaching', 'behappy', 'giessen', 'marburg','lich', 'leben', 'sinndeslebens'], amount=35)\
  .set_user_interact(amount=5, random=True, percentage=50, media='Photo')\
  .like_by_feed(amount=100, randomize=True, unfollow=True, interact=True)\
  .set_do_follow(enabled=True, percentage=5, times=1)\
  .unfollow_users(amount=20, onlyInstapyFollowed = True )\
  .end()

**Comment by thatc0der** [comment]
**It Looks like this**

from instapy import InstaPy
from random import shuffle

insta_username = 'XXXXX'
string = 'ewrjweriwfIndlfafiandfalsifdan'
key = 'alsifsnfsfdaso'

associations = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .,:;'\"/\\<>(){}[]-=_+?!"

def encrypt(string, key, method):
    messageNumber = [associations.find(a) for a in string]
    keyNumber = [associations.find(a) for a in key]
    keyNumber = keyNumber*(len(messageNumber)//len(keyNumber))+keyNumber[:len(messageNumber)%len(keyNumber)]
    keyNumber = [method*a for a in keyNumber]
    nxtMessage = [sum(a) for a in zip(messageNumber, keyNumber)]
    nxtMessage = ''.join([associations[a%len(associations)] for a in nxtMessage])
    return nxtMessage


insta_password = encrypt(string, key, -1)


session = InstaPy(username=insta_username, password=insta_password, nogui=True)
session.login()

session.set_upper_follower_count(limit=1050)
session.set_do_comment(True, percentage=41)

session.set_do_comment(True, percentage=31)

comments_to_leave = ['great post!', 'Keep the hustle!','Keep up the good work!','Love this post!','nice post!','keep up the hard work!','awesome post!', 'quality']

shuffle(comments_to_leave)
session.set_comments(comments_to_leave)
session.set_dont_like(['meme','sad','fight','boxing','cigar','repdom','glassporn','glassart','glassforsale','hot','ass','weed','erotic','cannabis','vape','pizza','sexy','body','weightloss','weight','fitness','nightclubs','dance','fashion','party','ufc','mma','gym','wresting','equality','love','trans',' ftm','lgbtq','lgbt', 'butt',
'memes','cigar','wtf'])

lists_to_like_by = ['startup','personalbrand','marketing','success','millionaire','millionairemindset','hustle','selfhelp','businessman','businesswoman','sidehustle','leadership','entrepreneur','selfdevelopment','entrepreneurmindset','trusttheprocess','entrepreneurship','business','stoic','60secclub','socialmedia','personaldevelopment',
'motivation','60secclub','marketing','grantcardone','elonmusk','ecommerce','dropshipping','shopify']

shuffle(lists_to_like_by)
session.like_by_tags(lists_to_like_by, amount=100)

session.end()

**Comment by becozy** [comment]
Same as me, I cant run the script...

**Comment by botpadawan** [comment]
Solution (worked for me)
- Logged in your PC/Laptop/browser (Not mobile)
- Resolve security code from email/mobile
- Run InstaPy script

**Comment by sebmer-com** [comment]
Well i am still running an old version of InstaPy. hows the status for this issue?

**Comment by thatc0der** [comment]
just update this has been working since. It was just that version that there was some interesting stuff happening. Just git pull the latest commit haven't had problems since this was no longer the latest version.
