### ISSUE TITLE
i can't execute quickstart.py :( | NEWBIE |

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1131]
## Expected Behavior
I want to execute quickstart.py in order to get follow unfollow
## Current Behavior
But i can't execute it, that's my error message : 
from .instapy import InstaPy
File "/home/pierre-louis/Desktop/InstaPy/InstaPy/instapy/instapy.py", line 11, in <module>
from pyvirtualdisplay import Display
Import Error : No module named pyvirtualdisplay
## InstaPy configuration
from instapy import InstaPy

insta_username = ''
insta_password = ''

session = Instapy(username=insta_username, password='insta_password)
session.login()

session.follow_users_followers(['appleipy', 'legittechinfo'], amount=5, randomyze=False, sleep_delay =60)
session.unfollow_users(amount=10, onlyInstapyFollow=True, onlyInstapyMethod="LIFO", sleep_delay=60)

session.end()

**Comment by FreakyBoy** [comment]
try `pip install pyvirtualdisplay`

**Comment by ghost** [comment]
Thank you ! I installed all modules and now it works ;)

**Comment by Hrithik2797** [comment]
when I execute quickstart.py ,no error, the file executes but no window opens.Can someone help?
