### ISSUE TITLE
Smart Hashtags - umlauts aren't welcome 

### ISSUE THREAD

**Issue by TR0X** [InstaPy/InstaPy#1133]
Hi,

I've tried the new smart hashtag feature and I get the following error message:
```
  File "/home/pi/InstaPy/instapy/instapy.py", line 408, in set_smart_hashtags
    print('[smart hashtag generated: {}]'.format(item))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 0: ordinal not in range(128)

```

I found also the reason for this error: If you search at displaypurposes.com with an hashtag where the **result** includes an umlaut the script fails: For example: #munich -> #munich **#münchen** #oktoberfest #bavaria #munichcity #bayern 

Thanks! :)

**Comment by aclowkey** [comment]
It works for me..

> [smart hashtag generated: germany]
> [smart hashtag generated: munich]
> [smart hashtag generated: deutschland]
> **[smart hashtag generated: münchen]**
