### ISSUE TITLE
Interaction based on Public or Private

### ISSUE THREAD

**Issue by pedro639** [InstaPy/InstaPy#1134]
Hello,

so, i find a feature very needed in this script, that is, Interaction based on Public or Private profile, with this I mean that There should be an option to either follow only private profiles or public profiles, and why? because, when u follow private ones u get more follow backs!

**Comment by converge** [comment]
hey @pedro639 , the feature is on the way, but there is only $8usd at the moment to bounty it.

https://www.bountysource.com/issues/52103366-feature-request-exclude-private-users-or-only-private-users

you could add some words at the issue about your idea as well:
https://github.com/timgrossmann/InstaPy/issues/1006

**Comment by daz99m** [comment]
i think there should be a feature to only follow active profiles also, as theres more chance that theyll follow back

**Comment by daz99m** [comment]
how do i make the bot run 24/7? 
INFO - Liked: 90
INFO - Already Liked: 0
INFO - Inappropriate: 90
INFO - Commented: 30
INFO - Followed: 46
INFO - Session ended - 2017-12-24 18:38:37
INFO - --------------------
