### ISSUE TITLE
ERROR: Sample larger than population

### ISSUE THREAD

**Issue by canitb** [InstaPy/InstaPy#1142]
Running the code section:
session.set_smart_hashtags(['acim', 'yoga'], limit=3, sort='random', log_tags=True)
session.like_by_tags(amount=100, use_smart_hashtags=True)

## Expected Behavior
Expect it to run regardless of if the tag returned is low in numbers. Assuming this is the issue, but needs to be tested more.

## Current Behavior
ERROR: Sample larger than population
<img src="https://d1ro8r1rbfn3jf.cloudfront.net/ms_92450/yMwj8AvhVYjWR7zmhGUfmHzw6LppmT/Screen%2BShot%2B2017-12-26%2Bat%2B13.58.22.png?Expires=1514380478&Signature=FzIt~gZm8l2wbygC5hY5dXEgDY4x7qUCegI4oBOJzPd8yPcA3k1gIZ65qY0S1kAu7yM-y8sAxtLJx-mRPIhMjNVURn2a0qpKD7ctlCpbah4Nbz0lYROqZBn6hOVWo--6z~t2Bx15RfiDnMi9TUMDZZdAJLJpPICw2iNDj0fB~sMzMfQF~VsxIRwy0N9BDksWoew-72~TY~k4A64N6wuos~DFnwpXUav0DB2H6gVwHl-IUe5vjCGBcb2rjOnmGe24iVWrEuOD9LUG66ZQxf5ZEeMi3hX9lDF0err~jV4hW~2qBXrkuD8laVL9kDJvWLgzJdptKr4ast5h~wjmQUcewQ__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA">

## InstaPy configuration
session.set_smart_hashtags(['acim', 'yoga'], limit=3, sort='random', log_tags=True)
session.like_by_tags(amount=100, use_smart_hashtags=True)

**Comment by mpaolor** [comment]
i have the same problem, any news?
