### ISSUE TITLE
Cookie login makes the bot not working

### ISSUE THREAD

**Issue by Naramsim** [InstaPy/InstaPy#1143]
## Expected Behavior
When logging in with a cookie, everything should be fine
## Current Behavior
When logging in with the cookie, the works seems to work normally, but in reality, it does nothing at all
## Possible Solution (optional)
Delete the cookie after each run
## InstaPy configuration
Docker-compose, Azure, Netherland

**Comment by sekred18** [comment]
the same

**Comment by ghost** [comment]
@Naramsim @sekred18 Check my solution at #1140
