### ISSUE TITLE
Optimizing like speed and delay

### ISSUE THREAD

**Issue by patrickdundas** [InstaPy/InstaPy#1145]
I have recently been testing the like functionality of InstaPy to use for engagement rounds, where multiple accounts engage with each other over a short period of time. I've found in my testing that it takes about 30 seconds to like each user's post using the code shown below:

```python

# if you don't provide arguments, the script will look for INSTA_USER and INSTA_PW in the environment
session = InstaPy(username='user', password='pass', page_delay=0)

"""Logging in"""
# logs you in with the specified username and password
session.login()

session.set_upper_follower_count(limit = 999999999)
session.set_lower_follower_count(limit = 0)

session.like_by_users(usernames=usernamelist, amount=1)
```

It seems that there are built-in delays aside from `page_delay`, as this whole process takes about 30 seconds per user even when `page_delay` is set to `0`. This is simply too slow for my usage, as I need to like about 200 posts within an hour or 45 minutes. That would be about one like per 12 seconds, so I need to cut the current speed pretty much in half. Where should I look for the other delays, and how can I get rid of them? I understand that liking too many pictures all at once will result in a ban or such, and I'm not super worried about that as I can put my own delays where I see fit. Thanks for the awesome work.

**Comment by patrickdundas** [comment]
I was able to remove the delays from the `like_by_users` function by removing all the `sleep()` functions from `instapy/like_util.py`. This isn't the way InstaPy is intended to be used, but this solves my issue. If you are doing this in production I would suggest creating a `like_instantly_util.py` and a function such as `like_instantly_by_users` so that you can use both the intended behavior and the instant behavior I mentioned above. Use caution while doing this!!!

**Comment by Abzidian** [comment]
Patrick, I've been having the same issue, but that's with tags. I tried removing all the sleep() functions from instapy/like_util.py. I know this is n't how InstaPy was not intended to be used, but I still am not getting any faster like times.
