### ISSUE TITLE
need help! when running gui it says some files are missing download all files from file menu

### ISSUE THREAD

**Issue by rodrigogarcia7** [InstaPy/InstaPy#1146]

**Comment by converge** [comment]
hey mate, the GUI project is here: https://github.com/ahmadudin/electron-instaPy-GUI

**Comment by rodrigogarcia7** [comment]
hey! downloaded the files and set them in the Instapy folder, still getting the same message. sorry im fairly new to this  

    On Wednesday, December 27, 2017 12:16 PM, João Paulo Vanzuita <notifications@github.com> wrote:
 

 hey mate, the GUI project is here: https://github.com/ahmadudin/electron-instaPy-GUI—
