### ISSUE TITLE
Unexpected keyword argument 'delay'

### ISSUE THREAD

**Issue by rudygc** [InstaPy/InstaPy#1148]
I'm using the "session.follow_user_followers",

I was blocked at "random" which changed to "randomize".

Now the argument delay is not recognized. Maybe it changed like the "random" argument but i don't find what is the new argument. (or maybe i'm wrong and this is not the problem)

`  DevTools listening on ws://127.0.0.1:12571/devtools/browser/ea4b661a-29c4-4c1a-b48f-c0a23d76ac7a
INFO - Session started - 2017-12-28 14:25:09
WARNING - Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO - Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 6, in <module>
    session.follow_user_followers(['xxxxxxxx' ], amount = 100, randomize=False, delay=120)
TypeError: follow_user_followers() got an unexpected keyword argument 'delay'`

Thanks.

**Comment by timgrossmann** [comment]
@rudygc Did you update InstaPy in the last weeks?

**Comment by converge** [comment]
@rudygc it's always nice to check our documentation, it should be ```sleep_delay```.

**Comment by rudygc** [comment]
@timgrossmann Yep I just installed it 2 days ago.

@converge Thanks a lot it works :-) silly me didn't take the time to look attentively there.

Well, thanks a lot for sharing your work and helping :-) hope this issues will help people as distracted as me.

**Comment by BlaneWins** [comment]
im having this issue also and when i change it to sleep_delay it just overwrites it back to delay

**Comment by converge** [comment]
@Blaney update to latest version.
