### ISSUE TITLE
Option to save log files by username

### ISSUE THREAD

**Issue by dvlprlife** [InstaPy/InstaPy#1149]
## Feature Request

- Saving the log files by username allows the execution IntaPy within one location for multiple accounts.

- Add a parameter to determine if the log files should be stored in a separate log file subfolder by username use the existing one log folder structure

-  This will store the log files either in a separate log folder by username or within one log folder, as it is today

**Comment by timgrossmann** [comment]
@dvlpr-life Awesome, thank you!
We'll review and get back to you once we are ready to merge/you have to do some changes :wink:

**Comment by dkbast** [comment]
I'm really looking forward to this one :) if there is anything I can do to help, just let me know!
