### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by Caitiegh** [InstaPy/InstaPy#1154]
![image](https://user-images.githubusercontent.com/34644461/34429181-80c6a7e0-ecb9-11e7-96e9-c1c2f4108c2d.png)

I've installed the InstaPy GUI and it seems to be stuck on "InstaPy running..." and not doing a lot. I was trying to test it by using a hashtag that there is only 3 images tagged under so I can see if it works but it can't find them?

**Comment by therealgt4** [comment]
i am having the same issue, did you find any result?

**Comment by joshwwhite** [comment]
I'm having the same issue.
