### ISSUE TITLE
Create Whitelist Of Current Following In A text file 

### ISSUE THREAD

**Issue by Oyetomi** [InstaPy/InstaPy#1155]
## Expected Behavior
Bot should be able to create/download whitelist of current following before botting which helps to store initial followers/friends (get ids of following and store in a whitelist.text file ), which should be imported to quickstart.py like this whitelist_file="whitelist.py" .

**Comment by Adoncino** [comment]
I have created another module to handle thigs like this. I something simply like:

```
def updateCSV(self):
        
        self.whitelist = self.loadListFromCSV('data/{}/whitelist.csv'.format(self.insta_username))
        self.taglist = self.loadListFromCSV('data/{}/tag.csv'.format(self.insta_username))
        self.locationlist = self.loadListFromCSV('data/{}/location.csv'.format(self.insta_username))
        self.commentlist = self.loadListFromCSV('data/{}/comment.csv'.format(self.insta_username))
        self.inappropriate = self.loadListFromCSV('data/{}/inappropriate.csv'.format(self.insta_username))
        self.interactionlist = self.loadListFromCSV('data/{}/interact.csv'.format(self.insta_username))

def loadListFromCSV(self,path):
        listCSV = []
        fn = os.path.join(os.path.dirname(__file__), path)
        with open(fn) as f:
            reader = csv.reader(f)
            listCSV = [row[0] for row in reader]

        return listCSV

```
I edit only external CSV now :)

I know it's not the best and elegant pieces of code, but they works XD

**Comment by Oyetomi** [comment]
@Adoncino thanks , I appreciate it , how do I run it?

**Comment by Adoncino** [comment]
I load every CSV from a custom module I created to handle InstaPy, you can use a single line to load CSV before using InstaPy instructions.

**Comment by sionking** [comment]
https://github.com/timgrossmann/InstaPy/pull/1047

**Comment by sionking** [comment]
this will get all users from user name and store it as pickle

**Comment by Oyetomi** [comment]
Thanks , why wasn't your "Add limit per hour and limit per day feature" approved ?

**Comment by Oyetomi** [comment]
Thank you @adoncino , I appreciate it

**Comment by sionking** [comment]
@virginsince1997 I don't know I am still using it, do you >?
