### ISSUE TITLE
Once setup on digital ocean, is it possible to monitor the performance of the script?

### ISSUE THREAD

**Issue by saunlani** [InstaPy/InstaPy#1160]
I've tried "python quickstart.py > monitorlog.txt", the monitorlog.txt is created, but does not contain any content.

Is this possible?  I'm essentially trying to monitor the performance of the script, to ensure it does not run into any issues.

**Comment by converge** [comment]
```tail -f logs/general.log```

**Comment by saunlani** [comment]
thank you!
