### ISSUE TITLE
Personalize comment with each user name?

### ISSUE THREAD

**Issue by bsoum** [InstaPy/InstaPy#1165]
Hello,

It's possible to comment a post with the user name account? Exemple: 'Great @user! 😃🎉👏'

It's just for personalize each comments.

Thank you.

**Comment by juan0822031** [comment]
#1165

**Comment by juan0822031** [comment]
@caroflores___

**Comment by timgrossmann** [comment]
@bsoum Not possible at the moment... However, this should be pretty straight forward to implement.
If you put a bounty on this issue, I'm sure there soon will be someone having a working solution  for you ready.
https://www.bountysource.com/issues/53225694-personalize-comment-with-each-user-name?show_profile_modal=1

Thank you, all the best and
Happy Holiday

**Comment by aclowkey** [comment]
#1240
It could also be possible to add other users than OP to the comment. 
For example: I want to comment on memes, tagging other random pages on instagram.

What do you think?
