### ISSUE TITLE
Can't log

### ISSUE THREAD

**Issue by moises-javier** [InstaPy/InstaPy#1166]
I trying to use it but I can't login. This is my screenshot.
I'm tracking the possible error. I just commented on the method of line 234 in instapy.py file 
`log_follower_num (self.browser, self.username) `
And now it works correctly.
### But I still can not correct the problem.

![screenshot](https://user-images.githubusercontent.com/12815238/34457497-8be8cbb2-ed77-11e7-9ce2-d5d7d32639b7.png)

**Comment by converge** [comment]
delete your cookie file and try again. For some reason cookies expiry isn't bein respected and IG recognizes it as invalid cookie.

your cookie file is at ./logs/your_username_cookie.pkl
