### ISSUE TITLE
Element is not clickable

### ISSUE THREAD

**Issue by gitpatrickhub** [InstaPy/InstaPy#1167]
## Expected Behavior
Bot operates without crashing
## Current Behavior
Bot crashes on first image with error message below (started since last git pull):

```
Error running InstaPy: Message: Element is not clickable at point (28, 36.383331298828125). Other element would receive the click: <div class="_5rnaq"></div>
```

**Comment by gitpatrickhub** [comment]
Can't get the latest git pull to work, continues to crash with previously reported error message. Reverted back to:  7a6c9ff98e2db42881d1acff08342b6752796bed

Running on:
Raspberry Pi Jessie
Firefox-ESR 52.3
Python 3.5.4
Selenium 2.53.6
Geckodriver 0.19.0

Anyone able to get the latest pull to work on Raspberry Pi? If so, please let me know your configuration.

**Comment by rvoets** [comment]
I just did a pull and get the same error every time I run the script.

**Comment by rvoets** [comment]
@timgrossmann I just undid the pull request and now it's working again. Therefore it seems that the following commit breaks the script:

https://github.com/timgrossmann/InstaPy/commit/89753aeba66a6f0785c94e944119636d5509e91b

I'm not using a Raspberry Pi. Script running locally on my macbook.

**Comment by flo1t** [comment]
same error on ubuntu with nogui. in my case it happens some times when the script wants to follow a user. i changed now back to b40533e

**Comment by githubuser345** [comment]
I have the same error. Is it possible to download an older pull request from Github? I have the latest version of InstaPy, but I don't know how to download the older version of InstaPy. Any tips? Is it even possible?

**Comment by gitpatrickhub** [comment]
Try this url:
https://githowto.com/getting_old_versions

I left the branch that works for me and @flo1t left another branch in their comment.

**Comment by ghost** [comment]
So what is the best solution for this problem?

**Comment by ppx45** [comment]
Having the same issue after last git pull. On Raspberry Pi 3 and Firefox headless:

selenium.common.exceptions.WebDriverException: Message: Element is not clickable at point (28, 73.33332824707031)

**Comment by githubuser345** [comment]
Had the same problem. Thanks @gitpatrickhub for referring to tutorial on how to download old version.
I suggest download this version for time being: https://github.com/timgrossmann/InstaPy/tree/7a6c9ff98e2db42881d1acff08342b6752796bed
It's now working perfectly on my Raspberry Pi 3 model b!

**Comment by canitb** [comment]
@timgrossmann Is this getting fixed? I keep having this error.

**Comment by Venni27** [comment]
Me too on Raspberry3

**Comment by gustafsom** [comment]
Even using the old version, did not work for me with Raspberry Pi3. Error occurs: Message: Element is not clickable at point ...
