### ISSUE TITLE
InstaPy bot, Login error

### ISSUE THREAD

**Issue by zappin** [InstaPy/InstaPy#1168]
## Expected Behavior
Login
## Current Behavior
I get this message whenever I run the script:
File "example.py", line 17
   password="password", C***********3
                ^
SyntaxError: invalid syntax

## InstaPy configuration
This is the configuration I am using- https://github.com/instabot-py/instabot.py 
I did not change anything

**Comment by acuciureanu** [comment]
@zappin assuming that C>>>>3 is your actual password, did you try password='C>>>>3' ?

**Comment by saily89** [comment]
I am having the same issue tried that and now getting this:

Sailemyss-MacBook-Air:instaPy-master Saily$ python saily.py
Traceback (most recent call last):
  File "saily.py", line 34, in <module>
    session.end()
NameError: name 'session' is not defined
Sailemyss-MacBook-Air:instaPy-master Saily$

**Comment by Drippydh** [comment]
I have the same issue.
Error: SyntaxError: invalid syntax
InstaPy ended

I put my password in correctly, both in the script as in the GUI.
