### ISSUE TITLE
Skipping inappropriate images without being told to

### ISSUE THREAD

**Issue by patrickdundas** [InstaPy/InstaPy#1171]
I have the following code:

```python
# if you don't provide arguments, the script will look for INSTA_USER and INSTA_PW in the environment
session = InstaPy(page_delay=0)

"""Logging in"""
# logs you in with the specified username and password
session.login()

session.set_upper_follower_count(limit = 999999999)
session.set_lower_follower_count(limit = 0)

session.like_by_users(usernames=usernamelist, amount=1)
```
It seems as though when this finishes running, it says that it has skipped x number of images that were inappropriate. How can I disable that? It seems like this is supposed to be disabled by default (according to the readme), but it keeps happening even when I just use the above code.

**Comment by gvonbergen** [comment]
Same issue for me.

**Comment by gvonbergen** [comment]
In the file: instapy/instapy.py

I had to change the following line:
self.dont_like = ['sex', 'nsfw'] to
self.dont_like = ['nsfw']

for my keywords around clothes it removed a lot of stuff with 'unisex' and so on.

**Comment by converge** [comment]
all you have to do is:
```session.set_dont_like([])```

**Comment by patrickdundas** [comment]
My bad, should have been able to figure that out on my own. Thanks!

**Comment by jumartinzik** [comment]
hello guys !
I'm facing the same issue, but when I add `session.set_dont_like([])` to my script it still don't like posts containing 'sex'.
Any thoughs ? Thanx
