### ISSUE TITLE
Failed building wheel for Pillow

### ISSUE THREAD

**Issue by loredev10** [InstaPy/InstaPy#1173]
An error `pip install .`: 

Failed building wheel for Pillow

Command "/home/machine/Documents/py4e/inst/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ds0ru341/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5mzwpzzk-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/machine/Documents/py4e/inst/env/include/site/python3.5/Pillow" failed with error code 1 in /tmp/pip-build-ds0ru341/Pillow/

**Comment by A-S-C-I-I** [comment]
Was a solution ever found for this issue?  It began occurring today after a system update.

**Comment by DjianR** [comment]
in debian strech i had to:
`apt-get install libjpeg-dev zlib1g-dev`

**Comment by DjianR** [comment]
on Debian 9 i had to do
`apt-get install libjpeg-dev zlib1g-dev`
to fix it
