### ISSUE TITLE
nameError: same "session' is not defined

### ISSUE THREAD

**Issue by grakercub** [InstaPy/InstaPy#1176]
I'm very new to this and probably don't know what im doing, but when i input 

~/instapy$ python quickstart.py

i get:

Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.end()
NameError: name 'session' is not defined
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x100df8790>> ignored

and thats it... please help!

**Comment by beranPro** [comment]
have you unzipped the chromedriver.zip ?

**Comment by lennardboehnke** [comment]
I had the same error. I'm running the script on an Ubuntu 16.04 server, and after adding the nogui attribute I still get the NameError for session.

**Comment by SeanFacer** [comment]
Same!

**Comment by SeanFacer** [comment]
Using ubuntu 16.04 aswell

**Comment by Jamelle-Boose** [comment]
Same, Ubuntu 16.04

**Comment by grakercub** [comment]
I figured it out. problem was that i didn't have a lot of other stuff installed. 

i did python3 quickstart.py and it started working
