### ISSUE TITLE
Feature Request: Statistics of the best Follower Source

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1188]
I don't get where I can open a Bounty Feature Request, so I hope this will also find the way.

**WHY?**

It is pretty hard to figure out or decide on which profiles or tags we should focus on to get the most outcome. There is plenty of possibilities, so we need to test them.

There should be a way to make statistics, where we get the most follow backs

**HOW?**

I read, that all the already followed users get already saved into a database, so we don't follow them twice.

**WHAT?**

How would it be, when we just add the additional information of how we got them, e.g. #vegan or @vegangainz into this database and get a script to run or better a weekly/monthly email about the progress, which source is the best. So we can target more on them.

Now we can improve our targeting to the max and target only the group of people who also want to follow back. Like the auto-correction of Facebook Ads targeting.

**Comment by sionking** [comment]
didn't get it

**Comment by ghost** [comment]
That's exactly what I'm looking for!  Donnerstag, 22 Februar 2018, 09:21vorm. +01:00 von dkbast  notifications@github.com :
