### ISSUE TITLE
Log messages printed multiple times when using Schedule

### ISSUE THREAD

**Issue by anwari666** [InstaPy/InstaPy#1189]
Hi, I'm new to python so please bear with me. 

I currently run my setup like this:
```
schedule.every().day.at("21:01").do(like_only)
schedule.every().day.at("21:03").do(like_only)
```

When the second schedule run, the log messages (both on screen & on logs/general.log) are printed multiple times. In this case, the second scheduled run is at 21:03 (the lower part of the log below) are printed twice.

```
INFO - Session started - 2018-01-03 21:01:02
INFO - Logged in successfully!
INFO - Session ended - 2018-01-03 21:02:35
INFO - --------------------


INFO - Session started - 2018-01-03 21:03:02
INFO - Session started - 2018-01-03 21:03:02
INFO - Logged in successfully!
INFO - Logged in successfully!
INFO - Session ended - 2018-01-03 21:04:32
INFO - Session ended - 2018-01-03 21:04:32
INFO - -------------------- 
```

I tried to clear the `session` object with `del` and `None`, explicitly calls `logging.shutdown()`, `logging.close()`, `self.logger.removeHandler()`, etc but the issue remains.

How can I make it logs once? Any suggestions? Thanks!

**Comment by ghost** [comment]
Check my topic #1195 and make a file for yourself.

**Comment by davisonio** [comment]
Getting the same problem

**Comment by davisonio** [comment]
-
