### ISSUE TITLE
[WIN] GUI tool for InstaPy script

### ISSUE THREAD

**Issue by komad1na** [InstaPy/InstaPy#119]
Hell everyone,

When I saw this script first time I liked it a lot. Real people are responding and following back not bots. So I experimented a lot with functions, i know it's simple (at least for us programmers) to use it, but what if people, who don't know how to use it, discover it and they would be probably like "what is this this ain't app.". So i thought maybe i should make some simple GUI tool for the script (windows for now).

My idea:
I am, let's say, "decent" with C# and win forms so my question is should I proceed with this and do you guys/girls have anything to add or to say, any comment or idea is appreciated. If I make it how should I share it merge it with this (since i want open source gui tool) or should i create a new repository with project only and to add only .exe in this repository ?

I will post it [on this repository](https://github.com/Nemixalone/GUI-tool-for-InstaPy-script) whole project when I finish it.

Nemanja Komadina

**Comment by timgrossmann** [comment]
#44 😉

**Comment by AlainPilon** [comment]
You can give it a try if you want, but my worry is that the project is still too new, LOTS of things are going to change. Also, if you only target the Win platform, less people are going to be able to contribute.

**Comment by eduardocalazansjr** [comment]
I have the same thoughts of @AlainPilon 
Is TOO early to do a thing like that.

And sadly, if instagram see this, they will end with that so fast.
With an Windows GUI this would be with less time.

GUI for installation and setup: OK
GUI for use: Nah, i guess no.

**Comment by komad1na** [comment]
I am working only with his functions and arguments I dont go into code it self.
Basically if you tick option program will write down "session.login()" or any of the functions. Who knows C# can check out on link down.

I have made first working version which needs polishing of course. You guys can download it [here](https://github.com/Nemixalone/GUI-tool-for-InstaPy-script). File is InstaPy.exe in main folder(still don't know how to use github, i'm ***noob***)

EDIT: You need to put .exe file in folder where are all files for InstaPy

**Comment by timgrossmann** [comment]
@Nemixalone I think this is not too bad.
The problem is, like they mentioned, it'll change really fast.

I still think, this is nice to start with. 
What you should definitely  do, @Nemixalone , is add a Readme.md file to your project with explains what your tool is doing and provide one or two pictures of the GUI, this will maybe attract a few users.

But thanks for building something for InstaPy!

**Comment by komad1na** [comment]
I will try to keep up, I only need how you call functions e.g. 
 `session.set_do_follow(enabled=True, percentage=10, times=2)`
Program works that way when you tick checkbox and add tags or percent and click **RUN !** button it will generate whole **quickstart.py** file from begging till end. Then it will create a little batch file to set UTF-8 coding and call for quickstart.py, the rest is up to your script.

I have added README file. I hope you guys like the first version of program.

No problem I am glad that I am part of this project. :100:

**Comment by bhavincb** [comment]
hi @Nemixalone , your repo is not working

**Comment by andresmazzo** [comment]
What about https://github.com/breuerfelix/instapy-gui ?
