### ISSUE TITLE
Newbie on old iMac needs help!

### ISSUE THREAD

**Issue by barbarix** [InstaPy/InstaPy#1193]
Hi

First thanks Tim for your effort and this script. I'm a newbie to python but really want to learn to get it running.
I downloaded everything, did the adjustments.
I'm running an old iMac with OS 10.6.8. with Chrome (does no updates)
If I run the quickstart.py, i get the following issue and that python was closed unexpectedly.

python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    session.end()
NameError: name 'session' is not defined

Thank you very much for some help for a newbie.

**Comment by rzfzr** [comment]
Paste the full .py so we can help you

**Comment by barbarix** [comment]
I tried the....

python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to instagram_py.egg-info/requires.txt
writing instagram_py.egg-info/PKG-INFO
writing top-level names to instagram_py.egg-info/top_level.txt
writing dependency_links to instagram_py.egg-info/dependency_links.txt
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
reading manifest file 'instagram_py.egg-info/SOURCES.txt'
writing manifest file 'instagram_py.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_py
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.macosx-10.6-intel/egg
creating build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying instagram_py.egg-info/PKG-INFO -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying instagram_py.egg-info/SOURCES.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying instagram_py.egg-info/dependency_links.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying instagram_py.egg-info/requires.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
copying instagram_py.egg-info/top_level.txt -> build/bdist.macosx-10.6-intel/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/instagram_py-0.0.1-py2.7.egg' and adding 'build/bdist.macosx-10.6-intel/egg' to it
removing 'build/bdist.macosx-10.6-intel/egg' (and everything under it)
Processing instagram_py-0.0.1-py2.7.egg
Removing /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/instagram_py-0.0.1-py2.7.egg
Copying instagram_py-0.0.1-py2.7.egg to /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
instagram-py 0.0.1 is already the active version in easy-install.pth

Installed /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/instagram_py-0.0.1-py2.7.egg
Processing dependencies for instagram-py==0.0.1
Searching for emoji==0.4.5
Best match: emoji 0.4.5
Processing emoji-0.4.5-py2.7.egg
emoji 0.4.5 is already the active version in easy-install.pth

Using /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/emoji-0.4.5-py2.7.egg
Searching for PyVirtualDisplay==0.2.1
Best match: PyVirtualDisplay 0.2.1
Processing PyVirtualDisplay-0.2.1-py2.7.egg
PyVirtualDisplay 0.2.1 is already the active version in easy-install.pth

Using /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyVirtualDisplay-0.2.1-py2.7.egg
Searching for clarifai==2.0.31
Best match: clarifai 2.0.31
Processing clarifai-2.0.31-py2.7.egg
clarifai 2.0.31 is already the active version in easy-install.pth
Installing clarifai script to /Library/Frameworks/Python.framework/Versions/2.7/bin

Using /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/clarifai-2.0.31-py2.7.egg
Searching for selenium==2.53.6
Best match: selenium 2.53.6
Processing selenium-2.53.6-py2.7.egg
selenium 2.53.6 is already the active version in easy-install.pth

Using /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg
Searching for EasyProcess==0.2.3
Best match: EasyProcess 0.2.3
Processing EasyProcess-0.2.3-py2.7.egg
EasyProcess 0.2.3 is already the active version in easy-install.pth

Using /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/EasyProcess-0.2.3-py2.7.egg
Searching for Pillow==2.9.0
Best match: Pillow 2.9.0
Adding Pillow 2.9.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Searching for enum34==1.1.6
Best match: enum34 1.1.6
Adding enum34 1.1.6 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Searching for jsonschema==2.5.1
Best match: jsonschema 2.5.1
Adding jsonschema 2.5.1 to easy-install.pth file
Installing jsonschema script to /Library/Frameworks/Python.framework/Versions/2.7/bin

Using /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Searching for configparser==3.5.0
Best match: configparser 3.5.0
Adding configparser 3.5.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Searching for requests==2.13.0
Best match: requests 2.13.0
Adding requests 2.13.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Searching for future==0.15.2
Best match: future 0.15.2
Adding future 0.15.2 to easy-install.pth file
Installing pasteurize script to /Library/Frameworks/Python.framework/Versions/2.7/bin
Installing futurize script to /Library/Frameworks/Python.framework/Versions/2.7/bin

Using /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Searching for functools32==3.2.3.post2
Best match: functools32 3.2.3.post2
Adding functools32 3.2.3.post2 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Finished processing dependencies for instagram-py==0.0.1
macintosh-3:instapy pesa$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    session.end()
NameError: name 'session' is not defined

**Comment by rzfzr** [comment]
Ok... So it installed fine, the problem seems to be in the quickstart.py, can you paste its contents? Remember to not show your username and password.

**Comment by barbarix** [comment]
from instapy import InstaPy

insta_username = ''
insta_password = ''

# set headless_browser=True if you want to run InstaPy on a server
try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False)
    session.login()

    # settings
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.like_by_tags(['sport', 'hiking', 'healthyfood', ], amount=100)

finally:
    # end the bot session
    session.end()

**Comment by luigifaticoso** [comment]
If you are running chrome try to remove the version of python you have installed using this  guide https://stackoverflow.com/questions/3819449/how-to-uninstall-python-2-7-on-a-mac-os-x-10-6-4
and use the default python. It worked to a friend of mine that had the same issue
