### ISSUE TITLE
Can't unfollow people

### ISSUE THREAD

**Issue by rayanakiki** [InstaPy/InstaPy#1194]
Hello.... i am getting this error when i try to unfollow people that dont follow back
INFO - Session started - 2018-01-04 20:10:17
INFO - Logged in successfully!
ERROR - set_automated_followed_pool error [Errno 2] No such file or directory: './logs/soundbasix_followedPool.csv'

**Comment by hestuppfodarn** [comment]
Please add you quickstart file so we can see what you have written

**Comment by amauryleproux** [comment]
vim logs/soundbasix_followedPool.csv
save
chmod -R 755 logs/

should be fix it

**Comment by mbancha** [comment]
Sorry, I don't really understand, I'm not meant to paste that code into the script am I? Not sure what vim is...

My unfollow script: 
```
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException
from instapy import InstaPy
import schedule
import time


session = InstaPy(username='---', password='---')

session.login()

session.unfollow_users(amount=1000, onlyInstapyFollowed = True, sleep_delay=600)
```
and the error returned: 

> ERROR [2018-05-17 12:16:55] [---]  set_automated_followed_pool error [Errno 2] No such file or directory: 'C:\\Users\\Matt\\Documents\\GitHub\\InstaPy\\logs\\---_followedPool.csv'
> INFO [2018-05-17 12:16:56] [---]  --> Total people unfollowed : 0
> Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x061C03F0>>
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 163, in __del__
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 139, in stop
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
> ImportError: sys.meta_path is None, Python is likely shutting down
>

**Comment by julzKB** [comment]
@Spiz Did you try creating the .csv file yourself ?

create an empty text file here 

> C:\Users\Matt\Documents\GitHub\InstaPy\logs\soundbasix_followedPool.csv

**Comment by mbancha** [comment]
@julzKB oh well that's interesting, no I didn't, but when I checked the followedPool.csv that's generated in my folder there, it's totally empty. At this point there's some 1800 names that I want to unfollow, so it seems like the easiest way might just be doing it manually this time, no?
