### ISSUE TITLE
When using Follow followers of X, it follows, unfollows, and then refollows the same person

### ISSUE THREAD

**Issue by rohan11103** [InstaPy/InstaPy#1197]
## Expected Behavior
The bot should follow the first 10 users (unfollow them), then follow the next 10 (unfollow them), then follow the following 10 (unfollow these 10) etc.

## Current Behavior
The bot seems to be following and unfollowing the same set of 10 users from the profile XYZ

## InstaPy configuration

```python
from instapy import InstaPy
import os
session = InstaPy(username='brohan_sharma', password='rhea2005')
session.login()
session.set_dont_unfollow_active_users(enabled=True, posts=3)
session.unfollow_users(amount=10, onlyNotFollowMe=True, sleep_delay=60)


session.follow_user_followers(['XYZ'], amount=10, randomize=False)
session.set_do_follow(enabled=True, percentage=70)
session.set_user_interact(amount=10, randomize=True, percentage=50, media='Photo')

session.like_by_feed(amount=100, randomize=True, unfollow=False, interact=False)
session.set_ignore_users(['sourpsycho'])
session.set.end()
```

**Comment by vibhuarul** [comment]
Hey - Fairly new to instapy myself, if this is still an issue for you. 

change:
`session.set_do_follow(enabled=True, percentage=70)
`
to 

`session.set_do_follow(enabled=True, percentage=70, times=1)
`

Also, you're going to want to swap the order of the statements. ".set_" should go before the action you want to perform. So it should look like this:

```
session.set_do_follow(enabled=True, percentage=70, times=1)
session.set_user_interact(amount=10, randomize=True, percentage=50, media='Photo')
session.follow_user_followers(['XYZ'], amount=10, randomize=False)

session.set_ignore_users(['sourpsycho'])
session.like_by_feed(amount=100, randomize=True, unfollow=False, interact=False)
session.set.end()
```
