### ISSUE TITLE
Log says logged in successfully, but I'm not actually logged into instagram

### ISSUE THREAD

**Issue by shreyas-n** [InstaPy/InstaPy#1198]
Here's how my log looks in context to what I'm talking about

```
INFO - Session started - 2018-01-04 18:14:31
INFO - Logged in successfully!
INFO - Tag [1/2]
```

This all looks fine, but when I run with the browser showing, I can see that InstaPy is not actually logged in, and it can't interact with any of the posts. Does anyone else have this problem or know how to fix it?

Thanks

**Comment by sionking** [comment]
need to add double check for every module here

**Comment by SeoMinbong** [comment]
@sionking 
did u add double check for every module?? 
can I see what u did?

**Comment by balakedev** [comment]
@sionking did you find a fix for this???
