### ISSUE TITLE
Is it possible to use InstaPy without Clarifai?

### ISSUE THREAD

**Issue by mbancha** [InstaPy/InstaPy#12]
Alright I worked my way through getting this to work as far as I could, and this is just beyond my Python ability. 

Running this script:

#########################################
dont_like = ['food', 'girl', 'hot']
ignore_words = ['pizza']
friend_list = ['friend1', 'friend2', 'friend3']

InstaPy(username='xxxx', password='xxxx')\
  .login()\
  .set_do_comment(True, percentage=0) \
  .set_comments(['Cool!', 'Awesome!', 'Nice!']) \
  .set_dont_include(['friends here']) \
  .set_dont_like(dont_like) \
  .set_do_follow(True, percentage=0) \
  .unfollow_users(amount=100) \
  .set_ignore_if_contains(ignore_words) \
  .like_by_tags(['fit', '#muaythai'], amount=0) \
  .set_use_clarifai(enabled=False) \
  .end()
##########################################

getting this error:

##########################################

C:\Users\Matt>C:\Users\Matt\Desktop\InstaPy-master\quickstart.py
Traceback (most recent call last):
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matt\Desktop\InstaPy-master\quickstart.py", line 10, in <module>
    InstaPy(username='xxxx', password='xxxx')\
  File "C:\Users\Matt\Desktop\InstaPy-master\instapy\instapy.py", line 31, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 62, in __init__
    self.service.start()
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x0000023F33295FD0>>
Traceback (most recent call last):
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 173, in __del__
    self.stop()
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 145, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'

**Comment by timgrossmann** [comment]
#### I was pretty amazed, that you got this error and tested your case. Everything works as expected.

Make sure to include the
```python
from instapy import InstaPy
```

Also, if you want python to continue on the next line (like in the method chaining example here) you need to add a backslash on each line:

```python
InstaPy()\
.login()\
.set_do_comment(True, percentage=0)\
.set_comments(['Cool!', 'Awesome!', 'Nice!'])\
.set_dont_include(['friends here'])\
.set_dont_like(dont_like)\
.set_do_follow(True, percentage=0)\
.unfollow_users(amount=100)\
.set_ignore_if_contains(ignore_words)\
.like_by_tags(['fit', '#muaythai'], amount=0)\
.end()
```

And if you take a look at the documentation, the default of clarify is `False` so you don't need to set it explicitly.

> Note: If you write 
> \```python
> #you can write code here
> \```

**Comment by timgrossmann** [comment]
So just replace your code with this:

```python
from instapy import InstaPy

dont_like = ['food', 'girl', 'hot']
ignore_words = ['pizza']
friend_list = ['friend1', 'friend2', 'friend3']

InstaPy()\
.login()\
.set_do_comment(True, percentage=0)\
.set_comments(['Cool!', 'Awesome!', 'Nice!'])\
.set_dont_include(['friends here'])\
.set_dont_like(dont_like)\
.set_do_follow(True, percentage=0)\
.unfollow_users(amount=100)\
.set_ignore_if_contains(ignore_words)\
.like_by_tags(['fit', '#muaythai'], amount=0)\
.end()
```

and try `python3.5 <name of your file>`

**Comment by timgrossmann** [comment]
#### If your problem still is there, did you do ?

`pip install git+git://github.com/Clarifai/clarifai-python.git`

**Comment by mbancha** [comment]
Ok, sorry, been away for a long while. Back at it with the latest code. When I use the code you pasted here, or example.py in /examples/, I still get the 'No module named 'clarifai' error. This happens even though, like you say, the use_clarifai defaults to false ("session.set_use_clarifai(enabled=False, secret='xyz', proj_id='123')" in the default example.py, which I didn't touch).

Is there something I'm missing about just  using the script w/o Clarifai?

**Comment by timgrossmann** [comment]
@Spiz Make sure to use python3 and make sure the install is with `pip3` instead of only `pip`

**Comment by mbancha** [comment]
I am using python3, and do you mean pip3 for the install of clarifai? I'm trying to see if there's a way to use instapy without using clarifai at all..

That being said, to try it, I installed clarifai with pip3, and tried running the same script, now I'm getting the error:
" C:\Users\Matt>c:\users\matt\desktop\instapy-master\example.py
Traceback (most recent call last):
  File "C:\Users\Matt\Desktop\instapy-master\example.py", line 5, in <module>
    session = InstaPy(username='xxx', password='xxx')
  File "C:\Users\Matt\Desktop\instapy-master\instapy\instapy.py", line 40, in __init__
    self.logFile = open('./logs/logFile.txt', 'a')
FileNotFoundError: [Errno 2] No such file or directory: './logs/logFile.txt''"

which is very strange because the logfile.txt is most definitely there. If I go into instapy.py and change the log file location to the full location instead of './logs/logfile.txt' it skips that (and then I get the same error for './logs/followrestriction.json'...) - is that indicative of something specific I'm doing wrong?

**Comment by timgrossmann** [comment]
@Spiz If you want to use it without clarifai you can do that.

Where is your quickstart.py file located? Did you change something in the folder structure?

**Comment by mbancha** [comment]
It's in the main directory, but to be doubly sure, I just redownloaded the zip. I used the exact default quickstart.py with my login info and run it from an administrator command window and get the same error (no such file or directory: './logs/logfile.txt'). Same thing in powershell. Is there something I'm missing?

**Comment by timgrossmann** [comment]
@Spiz Please try to use git instead of downloading the zip...

Download git for windows and then do a `git pull https://github.com/timgrossmann/InstaPy.git` to download the repository. Then follow the install instructions

**Comment by mbancha** [comment]
Oh man, so sorry, and reading back through I see those were exactly the instructions you give. Thanks so much for you patience and help, I'm obviously new to this. And that worked, thanks!

While I'm learning, if you don't mind, why exactly does it only work if cloned through git? The download is simply the most recent version of the code anyway right?
