### ISSUE TITLE
Images are not liked

### ISSUE THREAD

**Issue by Naramsim** [InstaPy/InstaPy#1201]
## Expected Behavior
Like every image it should
## Current Behavior
Like only 5% or less of the images
## Possible Solution (optional)
Dont know
## InstaPy configuration
Docker-compose latest Azure

It seems that the .click() method does not work, or it works only sometimes. Even adding a 1-second sleep (to load the element) does not help

(Comments works)

**Comment by Naramsim** [comment]
This happens only on my Azure machine, not locally

**Comment by ghost** [comment]
Got similar issues with my DigitalOcean Debain Server.
Will set it up again soon.. Hope it helps.

Try to wait 24h without any script running, delete the cookie file in the log folder and start it then again without following more than 20 people per hour

**Comment by Naramsim** [comment]
Yep, I quit it yesterday, I will resume it tomorrow 👍
