### ISSUE TITLE
can't install pyvirtualdisplay

### ISSUE THREAD

**Issue by bestit-co** [InstaPy/InstaPy#1203]
## Expected Behavior
**I can't install pyvirtualdisplay**
## Current Behavior
please show this error:
`root@bot1:~/InstaPy#`` python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 15, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay`
`root@bot1:~/InstaPy# python --version
Python 2.7.12`
`root@bot1:~/InstaPy# pip --version
pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)`
`root@bot1:~/InstaPy# python3 --version
Python 3.5.2`
`root@bot1:~/InstaPy# pip install pyvirtualdisplay
Requirement already satisfied: pyvirtualdisplay in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: EasyProcess in /usr/local/lib/python3.5/dist-packages (from pyvirtualdisplay)`
`root@bot1:~/InstaPy# sudo pip install pyvirtualdisplay
Requirement already satisfied: pyvirtualdisplay in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: EasyProcess in /usr/local/lib/python3.5/dist-packages (from pyvirtualdisplay)`

**Comment by converge** [comment]
```pip2.7 install pyvirtualdisplay```
