### ISSUE TITLE
unable to like, follow or comment !

### ISSUE THREAD

**Issue by vedsarkar** [InstaPy/InstaPy#1204]
Nothing is happening after the bot logs in to my account. It only keeps on scrolling down but is unable to like, follow or comment. Here are  the parameters i am using.

`session = InstaPy(username='username', password='password')
session.login()

session.like_by_tags(['sketch', 'sketchbook', 'draw', 'doodle',
                      'pencil', 'sketching', 'instaart', 'painting', 'pen', 'artoftheday',
                      'drawings', 'artsy', 'instaartist', 'ink', 'illustrator', 'watercolor',
                      'creative', 'graphic', 'paint', 'sketches', 'digitalart', 'myart', 'wip', 'paper',
                      'arte', 'pencildrawing', 'fanart', 'dibujo', 'manga', 'arts_help'], amount=1000)

#set following
session.set_do_follow(enabled=True, percentage=100, times=2)
session.set_upper_follower_count(limit=2500)

#set comment
session.set_do_comment(enabled=True, percentage=100)
session.set_comments(['Awesome', 'Really Cool', 'I like your work'])

session.set_dont_like(['pizza', 'girl'])

session.end()`

and this is what I get in the terminal

> INFO - Session started - 2018-01-07 15:04:07
> WARNING - Sorry, Record Activity is not working on Windows. We're working to fix this soon!
> INFO - Logged in successfully!
> INFO - Tag [1/30]
> INFO - --> b'sketch' 

and it only goes on scrolling new images and does not like follow or comment

**Comment by gitpatrickhub** [comment]
Have you tried to like an image manually on the same Windows machine? The error states instagram activity is not working on windows.

**Comment by vedsarkar** [comment]
By putting the like parameter after #set comment it started to work.....I dont know how !!!

**Comment by johnvfitness** [comment]
hi guy this my problem crash 


INFO - --> Image Liked!
INFO - --> Commented: Excelent!
INFO - Session ended - 2018-01-08 16:44:12
INFO - --------------------


Traceback (most recent call last):
  File "start.py", line 23, in <module>
    session.like_by_tags(['musculation','teamshape','fitness','crossfit','beastmode','workout','fitspo','getfit','aesthetic','motivation'], amount=10)
  File "/Users/Retina/Desktop/InstaPy/instapy/instapy.py", line 725, in like_by_tags
    self.logger)
  File "/Users/Retina/Desktop/InstaPy/instapy/unfollow_util.py", line 341, in follow_user
    follow_button.click()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button class="_qv64e _iokts _4tgw8 _njrw0">...</button> is not clickable at point (669, 9). Other element would receive the click: <div class="_5rnaq _cyf06">...</div>
  (Session info: headless chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.2 x86_64)

macbook-pro-de-mac:instapy Retina$

**Comment by vedsarkar** [comment]
Hi brother,

Sorry I can't fix this as I dont have macbooks, canyou sen me your master
folder so that I can run and check it in windows !!
