### ISSUE TITLE
How to put proxy ID and password in start file ?

### ISSUE THREAD

**Issue by rudygc** [InstaPy/InstaPy#1205]
Hi,

I want to use proxies to run several account.

But i don't know where i should put the ID and the password of my proxy in the file.

Here is an exemple from the documentation of Instapy : 

![image](https://user-images.githubusercontent.com/34854141/34648898-ceacb756-f3a3-11e7-81fa-1ef9ce38c5d3.png)

I'm used to this kind of authentification 

![image](https://user-images.githubusercontent.com/34854141/35364456-8bf89fcc-016f-11e8-9a53-cecc67e3dcd8.png)

Thanks for your help!

**Comment by VBMH** [comment]
did you figure it out? i am having the same issue....

**Comment by rudygc** [comment]
Nop didn't yet, i'm focusing on only 1 account atm.. but yes i'd like to find how

**Comment by ghost** [comment]
I have created a PR for proxy authentication https://github.com/timgrossmann/InstaPy/pull/1531
Check please.
