### ISSUE TITLE
Hi session crash chrome driver 

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#1206]
INFO - --> Image Liked!
INFO - --> Commented: Propre!
INFO - Session ended - 2018-01-08 18:59:59
INFO - --------------------

Traceback (most recent call last):
  File "start.py", line 23, in <module>
    session.like_by_tags(['musculation','teamshape','fitness','crossfit','beastmode','workout','fitspo','getfit','aesthetic','motivation'], amount=10)
  File "/Users/Retina/Desktop/InstaPy/instapy/instapy.py", line 725, in like_by_tags
    self.logger)
  File "/Users/Retina/Desktop/InstaPy/instapy/unfollow_util.py", line 341, in follow_user
    follow_button.click()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button class="_qv64e _iokts _4tgw8 _njrw0">...</button> is not clickable at point (243, 9). Other element would receive the click: <div class="_catib">...</div>
  (Session info: headless chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.2 x86_64)

macbook-pro-de-mac:instapy Retina$ python start.py

my configuration

from instapy import InstaPy

insta_username = 'XXXXXX'
insta_password = 'XXXXXX'

# set headless_browser=True if you want to run InstaPy on a server
try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=True)
    session.login()

    # settings
    session.set_dont_like(['pizza', 'porn','herbalife'])
    session.set_upper_follower_count(limit=1500)
    session.set_lower_follower_count(limit = 50)
    session.set_do_comment(True, percentage=20)
    session.set_comments(['Bien!','Jolie Profil!','Super!','Bravo!',], media='Photo')
    session.set_comments(['Excelent!','Propre!','Jolie!','Good Bro!',], media='Video')
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    # actions
    session.set_do_follow(enabled=True, percentage= 50, times=30)
    session.like_by_tags(['musculation','teamshape','fitness','crossfit','beastmode','workout','fitspo','getfit','aesthetic','motivation'], amount=10)
    
    session.like_by_tags(['musculation','teamshape','fitness','crossfit','beastmode','workout','fitspo','getfit','aesthetic','motivation'], amount=10)
    
    session.like_by_tags(['musculation','teamshape','fitness','crossfit','beastmode','workout','fitspo','getfit','aesthetic','motivation'], amount=10)
    
    session.like_by_tags(['musculation','teamshape','fitness','crossfit','beastmode','workout','fitspo','getfit','aesthetic','motivation'], amount=10)
    
    session.like_by_tags(['musculation','teamshape','fitness','crossfit','beastmode','workout','fitspo','getfit','aesthetic','motivation'], amount=10)
    
    session.like_by_tags(['musculation','teamshape','fitness','crossfit','beastmode','workout','fitspo','getfit','aesthetic','motivation'], amount=10)
    
    session.like_by_tags(['musculation','teamshape','fitness','crossfit','beastmode','workout','fitspo','getfit','aesthetic','motivation'], amount=10)
    
    session.like_by_tags(['musculation','teamshape','fitness','crossfit','beastmode','workout','fitspo','getfit','aesthetic','motivation'], amount=10)
    
    session.like_by_tags(['musculation','teamshape','fitness','crossfit','beastmode','workout','fitspo','getfit','aesthetic','motivation'], amount=10)
    
    session.like_by_tags(['musculation','teamshape','fitness','crossfit','beastmode','workout','fitspo','getfit','aesthetic','motivation'], amount=10)

    session.unfollow_users(amount=105, onlyNotFollowMe=True, sleep_delay=600)
    session.unfollow_users(amount=105, onlyNotFollowMe=True, sleep_delay=600)
    session.unfollow_users(amount=105, onlyNotFollowMe=True, sleep_delay=600)
    session.unfollow_users(amount=105, onlyNotFollowMe=True, sleep_delay=600)
    session.unfollow_users(amount=105, onlyNotFollowMe=True, sleep_delay=600)

     # Prevents unfollow followers who have liked one of your latest 5 posts

    session.set_dont_unfollow_active_users(enabled=True, posts=5)
    
    session.like_by_locations(['440751671'], amount=0)

finally:
    # end the bot session
    session.end()

**Comment by chrismaltais** [comment]
Hey there @johnvfitness !

Does this crash still happen when you disable the `headless_browser` feature in the InstaPy constructor?

Let me know!

**Comment by johnvfitness** [comment]
I do not know for the moment that I do not do it again
