### ISSUE TITLE
0 people to follow

### ISSUE THREAD

**Issue by nocomp** [InstaPy/InstaPy#1209]
hi,

since today no more script are working, i got this type of messages:

this type: 
WARNING - account_name -> Less users to follow than requested.
ERROR - follow loop error Sample larger than population
INFO - --> Total people followed : 0 
INFO - --> User followed: []
INFO - Liked: 0
INFO - Already Liked: 0
INFO - Inappropriate: 0
INFO - Commented: 0
INFO - Session ended - 2018-01-09 13:20:57
INFO - --------------------

this is the code i use
session.login()

#session.set_user_interact(amount=25, randomize=True, percentage=50, media='Photo')
#session.set_comments(["Cool", "Super!", "Top"])
session.follow_user_followers(['user_name'], amount=300, randomize=True, interact=True)

i ve changed the account name by user_name in the text above.

any idea what can be wrong?

thxx for your time

**Comment by Cineda** [comment]
Try using their new qucikstart.py configuration, you might have done the config wrongly.

**Comment by nocomp** [comment]
hi,
this script used to work fine, didn t changed anything, no it says "zero", weird
