### ISSUE TITLE
Edit built in delays?

### ISSUE THREAD

**Issue by ArdySan2012** [InstaPy/InstaPy#1210]
Gentlemen, is there a way to slow this amazing machinery down a bit? E.g. edit built in delays between iterations... Would highly appreciate a clue here...

**Comment by ArdySan2012** [comment]
It is just that apparently different accounts would have different amount of likes/follows per hour permitted (new vs old vs those recently receiving a warning etc). 
Would be really nice to be able to control operations per hour ... is that possible?

**Comment by ArdySan2012** [comment]
Looks like editing sleep time in Like util fine does it...

**Comment by Adoncino** [comment]
I really hate the delay after a tag/location page. It's too much. It's great if you run 200 actions on the same page, but very poor if you mix a lot of interaction across hundreds of hashtags. I try to edit the code but I'm missing something, and I wasn't able to fix it.
