### ISSUE TITLE
Q: How to lower the chances of getting banned?

### ISSUE THREAD

**Issue by luigifaticoso** [InstaPy/InstaPy#1212]
Any tips on how to lower the chances of getting banned? Like how many likes should I put every day, how many unfollows/follows and so on. 
Thank you

**Comment by ghost** [comment]
max 20 Follows or Unfollows per Hour

Likes, good question..

Tim used to like 2.5k-3k per day with 7% commenting.

I have still issues with being banned or so.. 
Or maybe my server is not properly installed, will reinstall all from new and try again.

**Comment by sionking** [comment]
bests tip is not to use a server with proxy.
likes can reach 2K a day depends on account.
unfollows/follows instagram not really likes.
