### ISSUE TITLE
Like amount incorrect

### ISSUE THREAD

**Issue by fisheseses** [InstaPy/InstaPy#1220]
## Environment
Ubuntu server on virtual box
chrome
chromedriver V2.34
headless

## Expected Behavior
Like each tag 30 times [1/30]
## Current Behavior
Like each tag 15 times [1/15]
Started in Nov each tag like dropped from 30 to 21 to 15
## Possible Solution (optional)
Please advise
## InstaPy configuration
session.like_by_tags(['portraits', ' portrait', 'portraits_ig', 'pixel_ig', 'portraiture', 'expofilm3k',
 'portrait_perfection', ' portraitstyles_gf', 'portraits_universe', 'portraitmood', 'rsa_portraits'], amount=30)
## Similar situation
[1091](https://github.com/timgrossmann/InstaPy/issues/1091)

**Comment by rangabears** [comment]
I am experiencing the same thing. Was allowing me to like_by_tags 100, then got limited to 18, now 15. 
No issues when running interact_user_followers.

**Comment by fisheseses** [comment]
@tmurphy00 I stopped the script for about a week and it was back to normal after that. Confirmed that it is a temporary limit on specific accounts. Closing thread.
