### ISSUE TITLE
NameError: name 'session' is not defined

### ISSUE THREAD

**Issue by SimoneRaimondiCominesi** [InstaPy/InstaPy#1222]
Hi guys, i need some help on my raspberry.
I followed the guide but at least i had some problems...

This is the Output:
Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.end()
NameError: name 'session' is not defined

I installed Firefox and all...

**Comment by luigifaticoso** [comment]
I think there is some trouble with the `try` and `finally` in the code
Can you post your config file, please?

**Comment by SimoneRaimondiCominesi** [comment]
My configuration is the **same** of the original file.
I only added my _username and pass._

from instapy import InstaPy

insta_username = 'nameofmyaccount'
insta_password = 'mypassword'


try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False)
    session.login()


    session.set_upper_follower_count(limit=2500)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])


    session.like_by_tags(['natgeo'], amount=1)

finally:

    session.end()

**Comment by luigifaticoso** [comment]
Can you upload the code(be sure to remove your account info) so i can check it? python is a pain in the a$$ with indentation and stuff

**Comment by SimoneRaimondiCominesi** [comment]
I changed something but the result is the same.

from instapy import InstaPy

insta_username = 'myname'
insta_password = 'mypass'

# set headless_browser=True if you want to run InstaPy on a server
try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,use_firefox=True, page_delay=25)
    session.set_switch_language(False)
    session.login()

    # settings
    session.set_upper_follower_count(limit=2500)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.like_by_tags(['natgeo'], amount=1)

finally:
    # end the bot session
    session.end()

**Comment by luigifaticoso** [comment]
I mean the .py file

**Comment by luigifaticoso** [comment]
#1176 
check this one out

**Comment by vaporstatic** [comment]
I've been encountering the same lately, and it's really killing my traffic. I didn't change anything, one day I restarted the script, and this crops up. Since I'm not a coder, it's been a real bitch trying to get this thing to work right continuously. This error can be apparently be caused my numerous different things, but so far none of the solutions work. 

Instapy doesn't error out until it hits the session.end(). You can test that by putting a print command before the session close. Unfortunately, I don't know what the hell that means.

Are you getting the JSONDecodeERROR: Expecting value: line 1 column 1 <char 0>?

**Comment by SimoneRaimondiCominesi** [comment]
@luigifaticoso i checked it and i followed the steps, but i'm on raspberry and i use firefox not chrome.

@shikyi i put the **(print "ok")** before **session.end()** and i saw 'ok' on command line, so the **finally** works good...

The problem could be the session.end() or other files that i have not modified.

**Comment by converge** [comment]
some error is occurring, to know the error you just need to remove or comment the try/except lines, and the real error message will show up.

**Comment by vaporstatic** [comment]
I fixed my issue by backing up my quickstart.py, nuking the Instapy folder, and having GitHub re-clone everything. I then downloaded the latest chromedriver, threw the exe into the assets folder, and it worked.

**Comment by SimoneRaimondiCominesi** [comment]
Thanks @converge, this is my error now:

`Traceback (most recent call last):
  File "quickstart.py", line 9, in <module>
    page_delay=25)
  File "/home/pi/Desktop/InstaPy/instapy/instapy.py", line 135, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Desktop/InstaPy/instapy/instapy.py", line 170, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpMueeTO If you specified a log_file in the FirefoxBinary constructor, check it for details.
` 


and this is the code used:
from instapy import InstaPy

insta_username = 'user'
insta_password = 'pass'


#try:
session = InstaPy(username=insta_username,
                      password=insta_password,
                      use_firefox=True,
                      page_delay=25)
session.login()

    # settings
session.set_upper_follower_count(limit=2500)
session.set_do_comment(True, percentage=10)
session.set_comments(['Nice shot!'], media='Photo')
session.set_dont_like(['pizza', 'girl'])
session.follow_user_followers(['suicidegirls'], amount=100, randomize=False, sleep_delay=60)
    # actions
session.like_by_tags(['natgeo'], amount=1)

#finally:
    # end the bot session
session.end()

**Comment by leegabriel** [comment]
Not sure if this will help, but maybe check if ```chromedriver``` is running? Perhaps the session could not be established, leading to the error. For the record, @shikyi 's solution worked for me.

**Comment by luigifaticoso** [comment]
If you are running chrome try to remove the version of python you have installed using this  guide https://stackoverflow.com/questions/3819449/how-to-uninstall-python-2-7-on-a-mac-os-x-10-6-4
and use the default python. It worked to a friend of mine that had the same issue

**Comment by riccardorighettiphoto** [comment]
Hello,
I have the same issue: running Instapy on a CentOS 7.x VPS. I tried almost everything late night.
Anyone has any idea to get solved the matter?

**Comment by marcusk77** [comment]
I'm a newbie and I too have the same problem: using Raspberry Pi 3 model B with Firefox.

**Comment by SimoneRaimondiCominesi** [comment]
Hey guys, i solved the problem.
After a long time and tests, discovered that it was enough to install Firefox esr,
contrary to what is written in the official guide.
Thank you all guys for the support.

**Comment by marcusk77** [comment]
Unfortunately I already have Firefox esr installed.

**Comment by krazylearner** [comment]
Getting same error on windows 10

```
python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.end()
NameError: name 'session' is not defined
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x05A5F730>> ignored
```
