### ISSUE TITLE
does anyone have notice any update from follow action?

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1223]
I've taken a lot of spam flag from Instagram, I'm doing 20 follow in the max/hour

**Comment by joselitinho1** [comment]
I've taken a lot of spam flag from Instagram, I'm doing 20 follow in the max

**Comment by owenchew** [comment]
I found this problem 7 hours ago. Before that time, I did not do any actions no matter follow or unfollow.

**Comment by ghost** [comment]
same here..

Are you using also DigitalOcean?

**Comment by owenchew** [comment]
yes. until now it still doesn't work.

**Comment by sas300** [comment]
Yeah, Im suffering the same problem. Still not sure what it is, but Im confused why it could be related to a specific account. Selenium still makes the browser load up enough images but the script  only selects the first 15, which makes me think that something changed on the Instagram website that affects the Instapy code.

Thoughts anyone?

**Comment by owenchew** [comment]
after fixing some codes, the follow action works, but like action is still unavailable.
