### ISSUE TITLE
Error with conversion

### ISSUE THREAD

**Issue by komad1na** [InstaPy/InstaPy#123]
Just got error for trying to convert int to string. I hope you can see from image.
Lower limit was 100.
Upper limit was 2500.

![jbg](https://cloud.githubusercontent.com/assets/7568344/25074814/60239fda-2305-11e7-88f2-b5cd8918195f.png)

**Comment by komad1na** [comment]
File **like_util.py** 
Add str (num_followers) in this line -> print('Number of Followers: ' + **str(**num_followers**)**)

**Comment by pekapa** [comment]
#122 should fix this.
