### ISSUE TITLE
How to count number of interactions + advice on my script

### ISSUE THREAD

**Issue by arthurecommerce** [InstaPy/InstaPy#1238]
Hello,

First, thanks for this amazing bot !
I'm running it on AWS and I'd like to automate it so it runs 24/7.
For this, I'll need to count the exact number of interactions (likes + follows).

My goal is to follow people following a specific list of accounts and then like 3 pictures from their account.
Sometimes I can't like pics of accounts I followed because it is private but I still add +3 to my interaction variable.

Here is my code, It's kind of working now but if you can help me.
I'm not a coder but I love to learn. I know my code isn't optimized but I'd love to improve it.

```
from instapy import InstaPy
import schedule
import time

insta_username = ''
insta_password = ''

session = InstaPy(username=insta_username, password=insta_password)

def job():
    try:
        session.login()

        i = 0  #counts the number of interactions
        #list of influencers accounts to interact with their followers
        list_accounts = ['account1','account2', 'account3']

        for elt in list_accounts:
            session.set_upper_follower_count(limit = None)
            session.set_lower_follower_count(limit = 50)
            #like 3 pictures of each account followed
            session.set_user_interact(amount=3, randomize=True, percentage=100)
            #follow 10 accounts
            session.follow_user_followers(elt, randomize=False, amount=10, interact=True)
            print("Number of interactions", i)  #show how much I interacted
            i = i+40  #add 40 interactions 10 accounts followed and 30 pictures liked
            if i > 500:  
                print("End of the session")  #end of the session if more than 500 interactions
                break

       #unfollow session
        session.set_upper_follower_count(limit = 5000)  #only unfollow small accounts
        session.unfollow_users(amount=100, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO')

    except:
        import traceback
        print(traceback.format_exc())

job()
schedule.every(24).hours.do(job)  #do this everyday

while True:
    schedule.run_pending()
    time.sleep(1)
```

Thank you !

**Comment by andrewjburnett** [comment]
Have you had any issues with the bot crashing? You don't restart it in anyway?

**Comment by arthurecommerce** [comment]
@andrewjburnett I changed the script a bit, I added a `session.end()`
Sometimes Chromium crashes after 2h, sometimes after 3 days, I don't know why.
But most of the times I can run it for several days on a server.

**Comment by andrewjburnett** [comment]
@arthurecommerce Can you give me a quick run through of how you got it up and running on AWS? I’m trying to do the same but have had concerns about it running from a different geographical region than the clients that are accessing their accounts via their phones. Has this been a problem?

**Comment by arthurecommerce** [comment]
@andrewjburnett it's really easy use VNC on an EC2 Instance (Ubuntu 16), I followed this http://www.brianlinkletter.com/how-to-run-gui-applications-xfce-on-an-amazon-aws-cloud-server-instance/
Then just install and run InstaPy as you normally would on Linux.
I had no problems for the moment about geographical regions (i use a 5 years account and two 3 months accounts).

**Comment by 2firstnames** [comment]
Hey @arthurecommerce are you able to run this on a T2.micro instance without being charged?

**Comment by arthurecommerce** [comment]
@2firstnames Yes, AWS charges you on a per hour basis and it is free the first year.

**Comment by timojaask** [comment]
@andrewjburnett @arthurecommerce Have you guys run it without any issue? In another issue here https://github.com/timgrossmann/InstaPy/issues/1845 another user is saying that you are likely to get banned running it from AWS IPs. What's your experience so far?

**Comment by mgconejero** [comment]
@arthurecommerce are you running more than one account? Is it possible to do that in AWS?
