### ISSUE TITLE
Error 'onlyNotFollowMe'

### ISSUE THREAD

**Issue by guilhermeherzer** [InstaPy/InstaPy#1242]
Hello,

When I try to execute onlyNotFollowMe gives an error.

ERROR - set_automated_followed_pool error [Errno 2] No such file or directory: './logs/guilherme.sublop_followedPool.csv'
unable to get followers and following information
 'after'

Help me

**Comment by aleducode** [comment]
same problem...

**Comment by gregsadetsky** [comment]
Here's the fix: change https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py#L163

from

```
del variables['after']
```

to

```
if 'after' in variables:
    del variables['after']
```

making sure to keep the indentation correct (i.e. the `if` should be at the same level than where the `del  ...` was. the `del` statement should now be one level more indented).

I'll open a PR later for this..!

**Comment by luigifaticoso** [comment]
If the problem is solved, you can close the issue
