### ISSUE TITLE
session.like_by_tags : ending after 15 posts liked, regardless of the amount

### ISSUE THREAD

**Issue by KKVSGM** [InstaPy/InstaPy#1243]
Hello

When I launch the command "python quickstart.py", everything is working, except "Error reading broker pipe: Le canal de communication a ÚtÚ fermÚ. (0x6D)"  ("The pipe has been ended" in English), and it likes 15 pictures then stops, but I would like to be able to choose the amount.

I'm unexperienced, so do you have any idea about how to solve the problem ? 

My parameters : 

try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False)
                      
    session.login()

    # settings
    session.set_do_comment(False, percentage=10)
    session.set_comments(['Wooow', 'Nice !'], media = 'Photo')
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['nsfw'])

    # actions
    session.like_by_tags(['aaaaa'], amount=100)
    
finally:
    # end the bot session
    session.end()

Regards.

**Comment by eduaero** [comment]
It is also happening to me

**Comment by PaulMucheke** [comment]
I have the same problem right now
