### ISSUE TITLE
Cron job example for docker? 

### ISSUE THREAD

**Issue by quintendewilde** [InstaPy/InstaPy#1246]
Hi, 

Is the example for the cron jobs also valid for setting up the docker container. This is not clear to me and I can't find a direct answer on how to do this. And rather ask before making errors from this. 

`25**** docker-compose up -d --build 
`
would this be a valid cron job for docker? And should I make one the close it after some time? Or will this do it automatically?

**Comment by westondeboer** [comment]
That is correct. 

25 * * * * docker-compose up -d --build

it runs until it completes and then runs it again when it is minute 25. 

I had multiple accounts going at the same time and would close it just before it ran again just in case. But there is no reason to do that.
