### ISSUE TITLE
no module named "pyvirtualdisplay"

### ISSUE THREAD

**Issue by jaysdeadmoon** [InstaPy/InstaPy#1247]
tried installing pyvirtualdisplay, error
then tried pip2.7 install pyvirtualdisplay
fix?

<img width="659" alt="pyvirt" src="https://user-images.githubusercontent.com/35543391/35069989-1aeacffc-fb99-11e7-96da-5d2a6f87b618.png">

**Comment by Sunnysidedown916** [comment]
I ran "pip install pyvirtualdisplay" and worked for me to fix this.
