### ISSUE TITLE
NameError: name 'session' is not defined

### ISSUE THREAD

**Issue by matteoFeduzi** [InstaPy/InstaPy#1249]
## Expected Behavior

I have this error, how can I solve it?

Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    session.end()
NameError: name 'session' is not defined

**Comment by pieperz** [comment]
I'm having the same issue. I'm running on rpi3 with chrome.

This is the error I'm receiving.

> Traceback (most recent call last):
  File "quickstart.py", line 27, in <module>
    session.end()
NameError: name 'session' is not defined
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x75d9e410>> ignored

**Comment by converge** [comment]
the magic is, remove the try/except and run again, the full error message will show up.

**Comment by Eisblume77** [comment]
I got the same error. Chromium is installed on my rpi3. Do I have to install chrome instead. Where can I find the correct package for chrome on rpi3 (raspbian)?

**Comment by luigifaticoso** [comment]
If you are running chrome try to remove the version of python you have installed using this  guide https://stackoverflow.com/questions/3819449/how-to-uninstall-python-2-7-on-a-mac-os-x-10-6-4
and use the default python. It worked to a friend of mine that had the same issue
