### ISSUE TITLE
ImportError?

### ISSUE THREAD

**Issue by taihoang** [InstaPy/InstaPy#125]
Hi! 

I was testing out this project, however, when I tried to run it using "python3.5 quickstart.py" it gives me this error: 

> root@Desktop/home/em/InstaPy# python3.5 quickstart.py
> Traceback (most recent call last):
>   File "quickstart.py", line 1, in <module>
>     from instapy import InstaPy
>   File "/home/em/InstaPy/instapy/__init__.py", line 1, in <module>
>     from .instapy import InstaPy
>   File "/home/em/InstaPy/instapy/instapy.py", line 5, in <module>
>     from pyvirtualdisplay import Display
> ImportError: No module named 'pyvirtualdisplay'

Am I doing something wrong? Do you know how I can fix this error? 

Thanks!

**Comment by pekapa** [comment]
Have you ran `pip install .`?
(or, to run locally and just install the dependencies, `pip install -r requirements.txt`)

**Comment by taihoang** [comment]
Yes, I have done both of those! ):

**Comment by pekapa** [comment]
I see that you're using `python3.5`
Any chance that your `pip` is actually `pip3` as well?

**Comment by taihoang** [comment]
pip3?

**Comment by taihoang** [comment]
Whoooopssss, I'm dumb, the dependencies were being installed in python2.7 because of that. My bad!

A new issue appears when I run it now: 

> Traceback (most recent call last):
>   File "quickstart.py", line 15, in <module>
>     InstaPy(username='myusername', password='passworddd')\
>   File "/home/em/InstaPy/instapy/instapy.py", line 34, in __init__
>     self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
>   File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
>     self.service.start()
>   File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 96, in start
>     self.assert_process_still_running()
>   File "/usr/local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
>     % (self.path, return_code)
> selenium.common.exceptions.WebDriverException: Message: Service ./assets/chromedriver unexpectedly exited. Status code was: 127

**Comment by converge** [comment]
this error means you don't have chrome browser installed, https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md
