### ISSUE TITLE
InstaPy on Raspberry Pi 2B

### ISSUE THREAD

**Issue by matteomaggioni89** [InstaPy/InstaPy#1250]
Trying to run InstaPy on Raspberry Pi 2B.
I've seen and followed the how to guide for installing on Raspberry Pi by@timgrossmann but having problem when running the simple firefoxExample.py script.

Has anyone managed to install and run on Pi2B?
I've also tried to use firefox-esr and update geckodriver to 0.19 without any success.

**Comment by gitpatrickhub** [comment]
what is the error you are getting?

**Comment by matteomaggioni89** [comment]
Here is my configuration:

> Description: Raspbian GNU/Linux 9.3 (stretch)
> Release: 9.3
> Codename: stretch
> Linux raspberrypi 4.9.59+ # 1047 Sun Oct 29 11:47:10 GMT 2017 armv6l GNU/Linux
> 
> Python 2.7.13
> selenium 3.8.1
> PyVirtualDisplay 0.2.1
> firefox-esr 52.5.2 (32-bit)
> geckodriver v0.19.0-arm7hf

Here is the error that I get from terminal when launching: python firefoxExample.py
```
Traceback (most recent call last):
  File "firefoxExample.py", line 18, in <module>
    InstaPy(username='user', password='pass!', use_firefox=True, page_delay=25)\
  File "/home/pi/InstaPy/instapy/instapy.py", line 135, in __init__
    self.set_selenium_local_session()
  File "/home/pi/InstaPy/instapy/instapy.py", line 170, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpnNVhZk If you specified a log_file in the FirefoxBinary constructor, check it for details.

```

**Comment by gitpatrickhub** [comment]
are you running headless? if headless, you need to use xvfb-run
have you tried running using "sudo"?

```
sudo python quickstart.py

```

**Comment by matteomaggioni89** [comment]
Tried with just sudo python and sudo xvfb-run python. In both cases is not working. Probably it is possible to run only on Raspberry Pi 3.

**Comment by gitpatrickhub** [comment]
Not sure why it wouldn't work on version 2. Curious if the error message changed using the sudo command. In any case, I use selenium version 2.53.6. It may be worth a try?

and just to confirm you ran these steps:
```
tar -xvzf geckodriver-v*
chmod +x geckodriver
sudo cp geckodriver /usr/local/bin/
```

**Comment by matteomaggioni89** [comment]
Yes I've done also the geckodriver steps.
I've googled my error and found that it better to downgrade to Firefox 46 but don't know how.
Either how can I try to go back to selenium 2.53.6?

**Comment by luigifaticoso** [comment]
Same problem here using raspberry 2
how can i fix this? 
```
Traceback (most recent call last):
  File "quickstart.py", line 14, in <module>
    session = InstaPy(username=insta_username, password=insta_password,use_firefox=True)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 135, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 170, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpM2bsn7 If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

**Comment by matteomaggioni89** [comment]
@luigifaticoso that's the same problem I have. I think the best chance is to move to Pi3 instead of wasting time trying to make it work with Pi2.

**Comment by gitpatrickhub** [comment]
@matteomaggioni89 if you want to try to downgrade selenium;

```
pip uninstall selenium
pip install selenium==2.53.6
```

**Comment by matteomaggioni89** [comment]
I've downgraded to selenium 2.53.6 but got the same error.
`    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpv5ZPK8 If you specified a log_file in the FirefoxBinary constructor, check it for details.
`

**Comment by gitpatrickhub** [comment]
I just realized this note;

Firefox is not currently working correctly on Pi 2, to install a working version the following commands should be used:
Pi2.1. wget https://launchpad.net/~ubuntu-mozilla-security/+archive/ubuntu/ppa/+build/10930950/+files/firefox_49.0+build4-0ubuntu0.14.04.1_armhf.deb
Pi2.2 sudo dpkg -i firefox_49.0+build4-0ubuntu0.14.04.1_armhf.deb


You mentioned above you are using v52

**Comment by luigifaticoso** [comment]
i used the one in the guide as you mentioned, as soon as i come home i will check the installed version

**Comment by gitpatrickhub** [comment]
@luigifaticoso sorry, that comment was meant for @matteomaggioni89 as they posted their configuration. It may be worth trying to downgrade your version of selenium with the firefox v49, beyond that I'm out of ideas.

**Comment by matteomaggioni89** [comment]
I've tried as well with 49 but with that version I can't even start the browser...I will try to purge out everything and install back, then I will let you know.

**Comment by luigifaticoso** [comment]
i've tried it but now it says that he can't find selenium even tho i reinstalled it, going to install everything back again, in the meanwhile ordering rpi3

**Comment by luigifaticoso** [comment]
Ok i got this problem, i've installed selenium 3.8 something, the last version
```
 File "/home/pi/Proj/InstaPy/instapy/instapy.py", line 13, in <module>
    from selenium.common.exceptions import NoSuchElementException
ImportError: cannot import name NoSuchElementException 
```
sounds like we are almost there

**Comment by quintendewilde** [comment]
```
I'm getting this error : 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "instapy/instapy.py", line 127, in __init__
    self.set_selenium_local_session()
  File "instapy/instapy.py", line 188, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmponCFq1 If you specified a log_file in the FirefoxBinary constructor, check it for details.

```

**Comment by Marto32** [comment]
I was getting a similar error but worked my way around it to a different error :) Noted in #1298 

I have a Pi 3, but I suggest trying to downgrade both selenium and the geckodriver and installing firefox-esr:

```
Raspbian GNU/Linux 9 (stretch) (I'm running with no gui)
Selenium 2.53.6
Mozilla Firefox 52.6.0 (downloaded via sudo apt-get install firefox-esr)
Geckodriver 0.18.0
```

**Comment by luigifaticoso** [comment]
It works with raspberry pi 3, i'm gonna try again rapsberry pi 2 in a week!

**Comment by jdloaner** [comment]
>  File "/home/pi/Proj/InstaPy/instapy/instapy.py", line 13, in <module>
>     from selenium.common.exceptions import NoSuchElementException
> ImportError: cannot import name NoSuchElementException 

How were you able to solve this?  Running Pi3, Python 3.5, Chromium

**Comment by Nocturnal-2** [comment]
@luigifaticoso Did you manage to run successful in Rapsberry Pi 2? Could you please share the installation steps if it was successful?

**Comment by JamRockJJ** [comment]
Hi there,

I am getting the same error as mentioned here, is there a way to run InstaPy on Raspberry Pi 2 successfully. Please Please Please!
