### ISSUE TITLE
Set_comments media parameter not working

### ISSUE THREAD

**Issue by jeremycjang** [InstaPy/InstaPy#1257]
## Expected Behavior
InstaPy will comment with one of three comments designated for photos on photo posts and comment with one of three comments from another set designated for videos on video posts.
## Current Behavior
InstaPy is disregarding the media parameter and adding comments that are meant for photos onto videos and vice versa. It is using comments other than the thumbs up emoji on the inappropriate media.
## InstaPy configuration
session.set_do_comment(enabled=True, percentage=75)
session.set_comments([':thumbsup:', ':raising_hands:', 'Fresh!'], media='Photo')
session.set_comments(['Keep it up!', 'Dope', ':thumbsup:'], media='Video')

**Comment by spikeyhair** [comment]
Yes, you are right. I am facing this issue too.

**Comment by guifelix** [comment]
#885
