### ISSUE TITLE
bypass_suspicious_attempt not storing cookie after session

### ISSUE THREAD

**Issue by jeremycjang** [InstaPy/InstaPy#1258]
Hello and thank you all for this wonderful project! I am admittedly new to this and only have a basic understanding of Python. I believe this is an issue I am encountering based off of the Terminal message received after a successful login and am concerned that this would interfere with full automation of my program further down the line.

## Expected Behavior
After one or two runs of the program/logins and manual entries of the confirmation code, a cookie is saved that prevents the need for bypass_suspicious_attempt to be set to True and the need for confirmation code re-entry upon every program run (I've found that I'm only able to bypass the second factor authentication by manually inputting the code into the browser once the program pauses on the screen).

## Current Behavior

No cookie is saved and it is necessary to receive a confirmation code and input said code on the second login screen every single time the program is run and a new session is started.

## InstaPy configuration
from instapy import InstaPy

insta_username = 'xxxxx'
insta_password = 'xxxxx'

# set headless_browser=True if you want to run InstaPy on a server
try:
    session = InstaPy(username=insta_username,
                      password=insta_password, use_firefox=True, page_delay=25, bypass_suspicious_attempt=True,
                      headless_browser=False)
    session.set_switch_language(False)
    session.login()

Running on a brand new RaspberryPi 3, hence the FireFox setup. used Quickstart.py as a template and added the use_firefox param from the FireFox example file. Thank you in advance!

**Comment by CharlesCCC** [comment]
You said `based off of the Terminal message received` Have you actually `cd` to the log folder and verify the cookies file has been created ?

**Comment by jeremycjang** [comment]
Hi @CharlesCCC , could you please walk me through how to do that?  I navigated to the logs folder using the File Manager and confirmed that there is a file username_cookie.pkl that appears to have stored cookie values inside the file.

**Comment by jeremycjang** [comment]
Received a suspicious login email from Instagram today asking to reset my password; confirmed that this is not working properly. Is something wrong in my code configuration? I followed all of the RaspberryPi setup steps from the main page.

**Comment by CharlesCCC** [comment]
`Received a suspicious login email from Instagram today asking to reset my password; confirmed that this is not working properly.` this is normal.   as long as the `cookie` created, that meant it worked.

**Comment by lucanello** [comment]
I get the same error. The bypass doesn't really work since I don't get an e-mail from Instagram. There are cookie files laying in the logs folder which aren't loaded when I create the session. It always says a new cookie is generated. I'm using the same configuration like @jeremyccheung but with the headless chromedriver since I'm running it from a server.
My problem is that I can't login because of "wrong login data". Instagram always asks if the session started on the server is trustable, which means no cookies are loaded since I already logged in correctly once.

EDIT: Is there a possibility to copy the session-cookie into the cookie-file and load it correctly? The problems could be solved all at once with this solution.

**Comment by jeremycjang** [comment]
@Lucanello brings up a good point; it could be that the expected behavior isn't happening because the saved cookies in the cookie.pkl file aren't being loaded.

@CharlesCCC Perhaps I should clarify; the suspicious login email I received was not the one containing a security code to input in the terminal. It was a mandatory password reset email that I received several hours after I ran the program and logged in to my account. When I was running sessions with the program, I was being sent the security codes through mobile and was inputting those directly into the web browser instead of seeing a LXTerminal prompt appear to authenticate. I had to double authenticate during every session run, so the cookies must either not have been save or are not being loaded in properly when the session is started.

Thank you both for your responses!

**Comment by jeremycjang** [comment]
I previously had left the bypass_suspicious_login_attempt parameter set to true and gathered several cookies. After reading through the loginutil.py file, I set the parameter to false. The cookies still did not load into the session and I was prompted with a security code, upon which I received the wrong login data error and the session ended. Has anyone found a way to get the cookies to load into the session?

**Comment by rodrigolopezguerra** [comment]
@jeremycjang did you manage to solve this?

**Comment by wahengchang** [comment]
@rodrigolopezguerra   did you manage to solve this?

**Comment by jeremycjang** [comment]
@wahengchang 2FA has to be disabled.
