### ISSUE TITLE
Error when trying to run quickstart.py

### ISSUE THREAD

**Issue by gabriansa** [InstaPy/InstaPy#1259]
Hello! 
This is the issue I'm getting when I try to open quickstart.py

_Gabrieles-MacBook-Pro:~ gabrieleansaldo$ cd InstaPy
Gabrieles-MacBook-Pro:InstaPy gabrieleansaldo$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.end()
NameError: name 'session' is not defined
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x103423790>> ignored_

Any suggestion on how to fix this?

Thanks!

**Comment by rushabhsooni** [comment]
what are u running the script in

**Comment by gabriansa** [comment]
@rushabhsooni on the terminal of my Mac

**Comment by serpia** [comment]
Same here on Mac and Debian

**Comment by rushabhsooni** [comment]
try runnung quikstart.py first

**Comment by converge** [comment]
if you delete try/exception lines in quickstart.py you will be able to see the full error message.

**Comment by steliosnikas** [comment]
I'm trying to set up on a Raspberry Pi3 and I'm getting this same error. Works fine on my Mac, used virtually the same process. Any thoughts?

**Comment by jermainee** [comment]
This issue usually happens when Chrome is not installed

**Comment by steliosnikas** [comment]
Just did a purge/reinstall on chromium and no change. Here's the full error:

Traceback (most recent call last):
  File "quickstart.py", line 26, in <module>
    session.end()
NameError: name 'session' is not defined
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x75d88e90>> ignored

**Comment by luigifaticoso** [comment]
Do you have chromedriver in your assets?

**Comment by steliosnikas** [comment]
Yes, I actually got it to work with firefox. Still same error with chromium.

I exported the driver in assets and used the command below and it works (only in ff)

export PATH=$PATH:~/path/to/assets folder
