### ISSUE TITLE
Chrome Driver for Raspberry Pi

### ISSUE THREAD

**Issue by jokim1** [InstaPy/InstaPy#126]
Hi,

I read Tim's medium post and wanted to try to get InstaPy running on Raspberry Pi 3. 

Sorry for not being super technical here, but I'm pretty much stuck when I try to run quickstart.py.

I followed all of the instructions including purchasing and installing Exagear and Chrome as per the instructions from Tim's medium post here: https://eltechs.com/run-google-chrome-on-raspberry-pi/

I believe my problem is likely the Chrome Driver I'm using. Which one should I use?

I've tried installing various versions of the chromedriver by trial and error and get a lot of errors from: "'Service' object has no attribute 'process'" to "Chrome version must be >= 56" to "unknown error: unable to discover open pages"

Seems like I'm really close to getting this to work and after banging my head on this for a while would definitely appreciate anyone else who knows how to solve this part. Please advise!

**Comment by eduardocalazansjr** [comment]
You need the latest stable chrome or chromium (v56-58) and latest chromedriver, both compiled for ARM.

And Exagear won't help in this scenario.

**Comment by nijaru** [comment]
I could be wrong, but AFAIK chromedriver is not compatible on ARM

**Comment by eduardocalazansjr** [comment]
If you compile, It is compatible.

**Comment by timgrossmann** [comment]
Also, you probably could change the code to your needs to use FireFox 😉 
https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=129320

**Comment by cazaa** [comment]
I had the exact same issue. Downloading an earlier version of chromedriver that supports Chrome version 48 fixed the issue for me: https://chromedriver.storage.googleapis.com/2.21/chromedriver_linux32.zip

**Comment by ghost** [comment]
@cazaa did you install exaGear?

**Comment by cazaa** [comment]
@imakethefish Yes, I bought and installed exaGear.

**Comment by ghost** [comment]
@cazaa I keep getting the below error, have you had similar issues? 

```session deleted because of page crash from unknown error: cannot determine loading status from tab crashed```

**Comment by andrewjburnett** [comment]
Can anyone help with further instructions on setting this up on a Raspberry Pi 3?

**Comment by andrewsyc** [comment]
Here's the problem I had and the reason I don't think this is going to work. Raspian Stretch has it's very own Chrome 60 which can actually be run in headless mode and is used on the Raspberry Pi 3 using the command line, of course, that is very limited if you can only run the command line. 

I installed exagear and it and it runs under their light weight virtualization where I put an x86 version of chromedriver. Problem is chrome driver has only been made to 64 bit for a while now which most likely not work at all with Chromium 60. 

What I did in my selenium script was to tell selenium to point to the chrome driver under "/opt/exagear/images/debian-8/usr/bin/ " which was the virtualization environment I started running "exagear" 

Unfortunately, the script keeps crashing and I think we are doomed on all fronts right now. Meanwhile, the abanoned PhantomJS is all I have which mostly works ok but I'd like to control a common browser.

So unless someone can come up with compiling chromium driver for the pi it's going to be a little difficult. I learned a lot though, so Plus on that.

**Comment by snakelab** [comment]
You can find the newest ones here:

https://github.com/electron/electron/releases

**Comment by Milkdrop** [comment]
I was able to install chromedriver on my Raspberry Pi on Lubuntu by doing
`sudo apt-get install chromium-chromedriver`

Then I used `dpkg -L chromium-chromedriver` to see where it installed it, and the rest was piece of cake.

**Comment by realvorl** [comment]
> I was able to install chromedriver on my Raspberry Pi on Lubuntu by doing
> `sudo apt-get install chromium-chromedriver`
> 
> Then I used `dpkg -L chromium-chromedriver` to see where it installed it, and the rest was piece of cake.

Saved me soooo much TIME man, thank you !
