### ISSUE TITLE
Error running chromedriver 2.9 and instapy

### ISSUE THREAD

**Issue by samducker** [InstaPy/InstaPy#1260]
## Error Message

        selenium.common.exceptions.WebDriverException: Message: unknown error: unrecognized Chrome version: HeadlessChrome/63.0.3239.132
          (Driver info: chromedriver=2.9.248304,platform=Linux 4.4.0-98-generic x86_64)

## How I got there

Installing latest version of instapy, chrome and chromedriver 2.9

## InstaPy configuration

        # if you want to run this script on a server,
        # simply add nogui=True to the InstaPy() constructor
        session = InstaPy(username=insta_username, password=insta_password, headless_browser=True)

        session.login()

        session.set_do_follow(enabled=True, percentage=100, times=1)
        session.set_upper_follower_count(limit = 600)
        session.set_lower_follower_count(limit = 100)
        session.like_by_tags(['ui'], amount=70, media=None)

        session.end()

**Comment by chrismaltais** [comment]
Hey there @samducker!

Is there any particular reason you're using chromedriver **2.9**?
Have you tried using the latest version (**2.35**)?

I found this on the release notes for chromedriver:
<img width="710" alt="screen shot 2018-01-22 at 11 28 13 am" src="https://user-images.githubusercontent.com/17098959/35231733-8551c4e6-ff67-11e7-9802-16cdee1b9716.png">

The first issue resolved in the above photo may be an explanation (and a fix) to your issue.

Try it out and let me know!

**Comment by samducker** [comment]
@chrismaltais isn't 2.9 the latest version?

**Comment by chrismaltais** [comment]
@samducker it's a little confusing how they decided to number the versions. 2.35 is more recent than 2.9.

Check out [this](https://sites.google.com/a/chromium.org/chromedriver/downloads) link for news on the most up to date versions!
