### ISSUE TITLE
button is not clickable at point

### ISSUE THREAD

**Issue by jermainee** [InstaPy/InstaPy#1263]
The script is running fine on my debian server (nogui=True) until it stops after random count of likes/comments and throws the following error message:

> Traceback (most recent call last):
  File "./script.py", line 25, in <module>
    # actions
  File "/root/InstaPy/instapy/instapy.py", line 764, in like_by_tags
    self.logger)
  **File "/root/InstaPy/instapy/unfollow_util.py", line 341, in follow_user
    follow_button.click()**
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
**selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button class="_qv64e _iokts _4tgw8 _njrw0">...</button> is not clickable at point (241, 9). Other element would receive the click: <div class="_catib">...</div>**
  (Session info: headless chrome=63.0.3239.132)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 3.16.0-4-amd64 x86_64)

Anyone who has an idea how to fix this?

**Comment by Namaslayer** [comment]
I'm having the same issues! Who know's how to help?

**Comment by jermainee** [comment]
The error "Element ... is not clickable at point (x, y)" seems to be a common selenium error if the browser window is too small. So the element is not in the visible view. Eventually the simulated browser window of selenium is too small with nogui=True

Maybe it is possible to resize the simulated window to a common display size... I'll try

edit:
Resizing the simulated window worked for me.
Go to instapy/instapy.py and change the display size in line 67 to a modern standard resolution like 1280×720 pixels or 1920×1080 pixels.

`self.display = Display(visible=0, size=(1920, 1080))`

Consider that it's likely that this modification will increase the RAM consumption of the script.

**Comment by FranklinClinton** [comment]
I'm having the same error. Any Ideas on this? Running on Ubuntu Server 16.04 LTS with Chrome. Of course I have set nogui=true and headless_browser=true.

**Comment by estebancortero** [comment]
I increased the display size but the error still occurs...
