### ISSUE TITLE
Sorry, something went wrong

### ISSUE THREAD

**Issue by ArdySan2012** [InstaPy/InstaPy#1265]
“Sorry, something went wrong” appears on the chrome page.
Does anyone have this one?
(Bot obviously stops working).
Manual refresh of the chrome page helps to start it again, but I wonder if that could be done automatically? (No problems with internet at the machine its running)...

**Comment by chrismaltais** [comment]
Hey @ArdySan2012 ! Thanks for opening an issue.

Can you provide some detail:
1) Your `quickstart.py` file
2) Your chrome version
3) Your chrome driver version

Thanks!

**Comment by ArdySan2012** [comment]
Apologies, that may be after all internet quality related. I think I stopped getting this error now..

**Comment by ArdySan2012** [comment]
I thought the issue to be related to the internet connection...  But just bumped into it again, with internet working perfectly. So here we go.
**What happens:**  In the chrome window - instead of the instagram page it displays a gray page with Facebook logo saying:
"Sorry, something went wrong. We're working on it and we'll get it fixed as soon as we can"

Chrome version is 63 and chromedriver is 2.35

1. Quickstart file (but happens with ANY quickstart file configurations, after some time - usually 30 to 90 minutes).
`from instapy import InstaPy
import os
session = InstaPy(username='  ', password='  ')
session.login()
session.set_do_comment(enabled=True, percentage=30)
session.set_comments([ 'This is special for sure! :)', u'This is quite special :)'])
session.set_do_follow(enabled=True, percentage=30, times=1)
#session.unfollow_users(amount=20)
session.set_upper_follower_count(limit =1500)
session.set_lower_follower_count(limit = 2)
session.like_by_tags(['tag'], amount=150)

session.end()`

**QUESTION**
Wondering if anyone at all seen this and if there is a way to make script notice this page (check for text "sorry, something went wrong" - and just refresh the page again (that seem to return an original instagram page in chrome to working state)

**Comment by ArdySan2012** [comment]
And the error in the script window looks like that:
`INFO - Image from: b'laekt_dk'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\InstaPy-master\START INNA.py", line 10, in <module>
    session.like_by_tags(['bryllup'], amount=150)
  File "C:\Users\User\Desktop\InstaPy-master\instapy\instapy.py", line 659, in like_by_tags
    self.logger)
  File "C:\Users\User\Desktop\InstaPy-master\instapy\like_util.py", line 483, in check_link
    "return window._sharedData.entry_data."
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined`

**Comment by ArdySan2012** [comment]
I get this error all the time, is it really that no one else gets it?

**Comment by spacewaffle** [comment]
Just started getting this today. Haven't had it before though.

**Comment by acekreations** [comment]
Also just started getting this today.

**Comment by ArdySan2012** [comment]
Chrome version 64 rolled out yesterday (or around it). But still getting the same error...

Is there a simple way to make script refresh the page if chrome page displays “can’t load/not found/sorry something went wrong” type of things?

**Comment by ArdySan2012** [comment]
https://github.com/timgrossmann/InstaPy/issues/877

Here is the same one issue - was left without a solution I understand...
