### ISSUE TITLE
script stuck on login page

### ISSUE THREAD

**Issue by rushabhsooni** [InstaPy/InstaPy#1268]
Is any one having a working fully functional instapy setup running , i am not able to login and script stops at login page , plz put up some video with new interface of instagram functioning so that , lots of issue can be solved , using the video footage start to end ,
Thanks.

**Comment by spacewaffle** [comment]
Having the same issue, was working earlier today, now I'm getting kicked out on login with error:

`unknown error: Cannot read property '0' of undefined`

Desktop login works fine. I did notice a "Suspicious login attempt" notification and was prompted to change my password. Password was changed and script was updated.

**Comment by mpaolor** [comment]
i too am having trouble logging in since today. i think instagram banned my IP because from home i can't login to any account while log in works fine from other pcs outside of the home network..

**Comment by spacewaffle** [comment]
I can still login from home on my laptop and phone. Just the script doesn't work.

**Comment by spacewaffle** [comment]
Nvm looks like I fixed the issue. After a forced password reset this issue popped up. I had to delete the cookie file in my logs folder to get it working again.

**Comment by Wisdomlocker** [comment]
@spacewaffle thanks for this fix.  did it for me !
