### ISSUE TITLE
change the HTTP referer header

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#1269]
Info:
The HTTP referer (originally a misspelling of referrer) is an HTTP header field that identifies the address of the webpage (i.e. the URI or IRI) that linked to the resource being requested. By checking the referrer, the new webpage can see where the request originated.

Issue:
We mainly have issue with capturing all the link from a page than rolling over them one by one...
The refer header will have the previous link and not the place we captured the link.
It seems suspicious.

Solution:
We can try use some chrome extension ?
https://chrome.google.com/webstore/detail/referer-control/hnkcfpcejkafcihlgbojoidoihckciin?hl=en
Or is it passable with chromedriver?

SC.

**Comment by sionking** [comment]
We can also, try open links in new tabs and keep old linked page.

**Comment by sionking** [comment]
I found we can use this :
chrome_options.add_argument("--Referer=https://www.owler.com")

But can it be changed before entering any link? how do we change it ?

**Comment by ganeshkrishnan1** [comment]
chrome_options.add_argument("--no-referrers")

**Comment by ganeshkrishnan1** [comment]
1. Adding no referrers or randomizing them
2. Random user agent on startup
3. Random Sleep delay (rather than 1 minute)

We need to add all three to maximum the chances of not being detected.

I will create a pull request for random sleep delay soon

**Comment by sionking** [comment]
Adding no referrers or randomizing them, Why not just setting the ref as the page that really ref them ?!
like someone followers == ref is this someone page.
tag image list ? this tag page.
...

**Comment by sionking** [comment]
BTW I am working on solution to open links directly on page instead of getting to saved link
Best solution is to open in new TAB.
Will PR soon

**Comment by sionking** [comment]
This is super important ! Each new link we go we send the previous one as referer  !I will add fiddler capture soon to explain.

But Instagram can easy analyze this and see those 2 links are not linked !

== execute browser.get will send referr of the current url....

**Comment by sionking** [comment]
Best solution and easy one is to open each new link in a tab than close the tab when done.
So the search tag / feed / capture following in user page will stay open all the time and will use as refer.
