### ISSUE TITLE
TypeError?

### ISSUE THREAD

**Issue by taihoang** [InstaPy/InstaPy#127]
I tried it out and it seemed to be working for about 2 seconds. After a bit, I get a typecast error like this one: 

> Traceback (most recent call last):
>   File ".\quickstart.py", line 23, in <module>
>     .like_by_tags(['landscape', 'ocean'], amount=10) \
>   File "C:\Users\em\Desktop\InstaPy\instapy\instapy.py", line 235, in like_by_tags
>     self.username, self.like_by_followers_upper_limit, self.like_by_followers_lower_limit)
>   File "C:\Users\em\Desktop\InstaPy\instapy\like_util.py", line 100, in check_link
>     print('Number of Followers: ' + num_followers)
> TypeError: Can't convert 'int' object to str implicitly

What do you think could cause this? Should I use a different version of Python (I'm currently using 3.5.0)?

Thanks!

**Comment by timgrossmann** [comment]
@taihoang Sorry, this was solved in #122
