### ISSUE TITLE
NameError: name 'session' is not defined

### ISSUE THREAD

**Issue by 01xVS** [InstaPy/InstaPy#1270]
Hey guys, I'm having trouble running "python quickstart.py". I get the following error:

  File "quickstart.py", line 26, in <module>
    session.end()
NameError: name 'session' is not defined

Any help would be really appreciated!

**Comment by converge** [comment]
hey @valstripe , if you delete the try/exception , you will be able to see the full error message.

**Comment by valstripe** [comment]
I'm getting indentation error? But I don't see any problems in the file. I made a screen of the quickstart.py

<img width="1440" alt="screen shot 2018-01-23 at 1 30 26 pm" src="https://user-images.githubusercontent.com/33891470/35278396-c9cd345e-0041-11e8-8f54-f797a7210739.png">

Valentinass-MacBook-Pro:~ valentinasstripeika$ cd desktop.instapy
-bash: cd: desktop.instapy: No such file or directory
Valentinass-MacBook-Pro:~ valentinasstripeika$ cd desktop/instapy
Valentinass-MacBook-Pro:instapy valentinasstripeika$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 26, in <module>
    session.end()
NameError: name 'session' is not defined
Valentinass-MacBook-Pro:instapy valentinasstripeika$ python quickstart.py
  File "quickstart.py", line 8
    session = InstaPy(username=insta_username,
    ^
IndentationError: unexpected indent

**Comment by 01xVS** [comment]
Nevermind, its working! I placed the chromedriver in the wrong folder. Thanks converge!
