### ISSUE TITLE
Cookie file not found, creating cookie... Wrong login data!

### ISSUE THREAD

**Issue by shaune1** [InstaPy/InstaPy#1273]
I've tried to set this program up with Linode and now Digital Ocean but with no success on either. Currently unable to set the cookie to log in. Confirmed that the login credentials are ok (possible issue using special characters in the password?).

Is it possible to add any additional logging to show what is happening on the server?

## Expected Behavior
Set the cookie and use it to log in.

## Current Behavior
2018-01-24 11:33:48 - INFO - Session started - 2018-01-24 11:33:48
Cookie file not found, creating cookie...
2018-01-24 11:33:59 - CRITICAL - Wrong login data!
2018-01-24 11:34:01 - INFO - Session ended - 2018-01-24 11:34:01
2018-01-24 11:34:01 - INFO - --------------------

## InstaPy configuration
from instapy import InstaPy

insta_username = 'removed'
insta_password = 'removed'

""" set headless_browser=True if you want to run InstaPy on a server
try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=True,
                      multi_logs=True)
    session.login()

    """ settings
    """ actions
    session.like_by_tags(['natgeo'], amount=1)

finally:
   """ end the bot session
    session.end()

**Comment by ganeshkrishnan1** [comment]
set the self.switch_language = False in instapy.py

**Comment by shaune1** [comment]
I tried that and had no luck with it. I'll also tried it again with the bypass_suspicious_attempt=True, but this did not work either.
I checked the logs file and there'sno cookie being created. I don't know if it's an issue with a setting or with there being special charcaters in the password that is causing an issue with the login, or an issue creating the cookie. As it's on the server i'm unsure how to see what is happening.
Open to any suggestions on what it could be.

**Comment by ganeshkrishnan1** [comment]
change your password to a simple one and try. Next add some exception handling to quickstart.py and check the output

**Comment by iFede94** [comment]
I had the same similar issue yesterday and I think that Instagram was blocking logins from my IP. Even from my laptop I couldn't login but if I tried from my iPhone with LTE I could login as usual.
After some hours I could login again from my laptop and from InstaPy.

I have that error now and by logging in manually from the browser it fails and the error says: "The username you inserted does not belong to any Instagram account. Check your username and try again.".

**Comment by shaune1** [comment]
Confirming that this was due to a unique character in the password. I changed the password and ran for two Instagram accounts I use and it worked.
