### ISSUE TITLE
Not logging in anymore

### ISSUE THREAD

**Issue by luigifaticoso** [InstaPy/InstaPy#1279]
## Expected Behavior
To log in
## Current Behavior
cannot click the log in button:
```
    session.login()
  File "/Users/luigicali/Downloads/InstaPy-7a6c9ff98e2db42881d1acff08342b6752796bed copy/instapy/instapy.py", line 213, in login
    self.switch_language):
  File "/Users/luigicali/Downloads/InstaPy-7a6c9ff98e2db42881d1acff08342b6752796bed copy/instapy/login_util.py", line 18, in login_user
    "//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav[@class='_luodr']/ul[@class='_g8wl6']/li[@class='_538w0'][10]/span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.2 x86_64)
```

**Comment by Xander8** [comment]
I am also getting this error. Vote up!

**Comment by huntersfuntime** [comment]
It looks like they changed the login to a register page, so you have to make the web-driver click the  login link on the register page, then reinitialize the original script with the new class for the login button which is _qv64e _gexxb _4tgw8 _njrw0.

**Comment by Xander8** [comment]
Which script in the instapy folder contains this function? And also which method in that script?

**Comment by mindakronik** [comment]
Possible solution
just comment on lines: login_until.py

if switch_language:
        browser.find_element_by_xpath(
            "//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["
            "@class='_luodr']/ul[@class='_g8wl6']/li[@class='_538w0'][10]/"
            "span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option"
            "[text()='English']").click()

it will work

**Comment by biggt22** [comment]
Yes commenting on those lines worked for me, thanks @mindakronik

**Comment by mindakronik** [comment]
You're welcome @biggt22

**Comment by rb2066** [comment]
Damn, I just tried updating this and I think I screwed the whole script up... Can anyone point to where I might have messed up?

Rahuls-MacBook-Pro:instapy i_will_be_RB$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/i_will_be_RB/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/Users/i_will_be_RB/InstaPy/instapy/instapy.py", line 23, in <module>
    from .login_util import login_user
  File "/Users/i_will_be_RB/InstaPy/instapy/login_util.py", line 6, in <module>
    from .util import update_activity
ImportError: cannot import name update_activity

**Comment by CharlesCCC** [comment]
created: [Pull request ](https://github.com/timgrossmann/InstaPy/pull/1280) to fix the issue based of the suggestion from @mindakronik

**Comment by ganeshkrishnan1** [comment]
You can just set the Switch language to False.
In instapy.py

make 

`self.switch_language = False`

**Comment by rfargetton** [comment]
@ganeshkrishnan1 , this worked for me :
`self.switch_language = False`

Thanks !

**Comment by luigifaticoso** [comment]
this worked!

>You can just set the Switch language to False.
In instapy.py
make
`self.switch_language = False`

**Comment by Essbuisness** [comment]
after 
self.switch_language = False
i started getting a wrong login detail error
when it actually correct

**Comment by xbno** [comment]
i did to, turned out all you have to add is `sleep(1)` before the input_username part in login_util.py.

```    # Enter username and password and logs the user in
    # Sometimes the element name isn't 'Username' and 'Password'
    # (valid for placeholder too)
    sleep(1)
    input_username = browser.find_elements_by_xpath(
        "//input[@name='username']")```
