### ISSUE TITLE
Login button not found

### ISSUE THREAD

**Issue by NoobTove** [InstaPy/InstaPy#1281]
<img width="960" alt="error" src="https://user-images.githubusercontent.com/29563338/35369998-1d7b09f8-01b1-11e8-8ef3-e65b705317df.PNG">

This was an error I've been getting repeatedly today and did not see a similar request previously. Thank you :)

**Comment by mindakronik** [comment]
this issue has been opened here
[Login Issue](https://github.com/timgrossmann/InstaPy/issues/1279)

**Comment by NoobTove** [comment]
@mindakronik Thank you so much!
