### ISSUE TITLE
ImportError: cannot import name update_activity

### ISSUE THREAD

**Issue by rb2066** [InstaPy/InstaPy#1282]
## Expected Behavior
When the  python quickstart.py command is entered, it engages InstaPy

## Current Behavior
It gets stuck:

Rahuls-MacBook-Pro:instapy i_will_be_RB$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/i_will_be_RB/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/Users/i_will_be_RB/InstaPy/instapy/instapy.py", line 23, in <module>
    from .login_util import login_user
  File "/Users/i_will_be_RB/InstaPy/instapy/login_util.py", line 6, in <module>
    from .util import update_activity
ImportError: cannot import name update_activity

I am not sure why this is happening. Sorry if this is a quick fix... I am a n00b when it comes to programming.

**Comment by luigifaticoso** [comment]
Have you done the command
`sudo pip install .` ?

**Comment by Wisdomlocker** [comment]
experiencing the same issue.  @luigifaticoso apologies, can you clarify what that means?

**Comment by luigifaticoso** [comment]
@Wisdomlocker to run the command ` sudo pip install . ` using the **terminal** in InstaPy folder so that it install InstaPy library and stuff
