### ISSUE TITLE
First run and impossible to execute the script

### ISSUE THREAD

**Issue by Aouah** [InstaPy/InstaPy#1286]
Hello,

I installed the script on a VPS from the French cloud computing company OVH (as I'm located in France). It is running on Ubuntu 16.04 (64 bits) with 2 GB of RAM. The server has been installed from scratch following your guidelines : https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md

I set up my quickstart.py file with this content :

```
from instapy import InstaPy

insta_username = 'My username'
insta_password = 'My pass'

# set headless_browser=True if you want to run InstaPy on a server
try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=True,
                      multi_logs=True)
    session.login()

    # settings
    session.set_upper_follower_count(limit=2500)
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.like_by_tags(['paris'], amount=3)

finally:
    # end the bot session
    session.end()
```

and at the first run I get that :

```
The program 'python' can be found in the following packages:
 * python-minimal
 * python3
Try: apt install <selected package>
```

What is the problem ?

Thank you

**Comment by Aouah** [comment]
Ok, as the shell suggests it I ran these commands :

```
apt install python-minimal
```
and
```
apt install python3
```
It installs Python and now I have this return :
```
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 11, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay
```

Still stuck...

**Comment by Aouah** [comment]
Still searching...

I try :
```
pip install pyvirtualdisplay
```

But I get that :
```
Requirement already satisfied: pyvirtualdisplay in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: EasyProcess in /usr/local/lib/python3.5/dist-packages (from pyvirtualdisplay)
```

**Comment by Aouah** [comment]
It's a big mess... I don't understand...

I found that I have Python 2.7.12 and Pip 9.0.1 (python 3.5) with these commands :
```
python --version
pip --version
```
So, I tried to upgrade the VPS to Python 3.5 with this tutorial :

> As you must have already noticed that Ubuntu 16.04 has 'python 2.7.12' by default. To check the default python version, run below line
> 
>    $ python -V
> it should return 'Python 2.7.12'
> 
> It is recommended that we don't try to modify/uninstall this default package of python because there could be many other system files/applications depending on it, and it might create some unexpected errors or issues if we uninstall this default python package.
> 
> So, to use the latest version of python, it would be better to go for creating a virtual environment ('virtualenv'). This is a module inside python which facilitates us to use multiple python versions on the same system.
> 
> Step-1: First install python3 -
> 
> $ sudo apt-get update
> $ sudo apt-get install python3
> Step-2: Now install 'virtualenv'-
> 
> $ pip install virtualenv
> Step-3: Now set the path of virtualenv to your desired directory. lets first create a desired directory-
> 
> $ mkdir MYENV
> it will create a folder in the current directory with the name 'MYENV'
> 
> Step-4: set the path of virtualenv to the created(desired) directory-
> 
> $ sudo virtualenv -p python3 MYENV
> Step-5: Activate the virtualenv
> 
> $ source MYENV/bin/activate
> done.. you should be able to get (MYENV) as prefix in the terminal command line. Now run below command
> 
> $ python -V
> it should return 'python 3.5.2' 

And finally I install pyvirtualdisplay
```
pip3 install pyvirtualdisplay
```

And now I get that :
```
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 12, in <module>
    from selenium import webdriver
ImportError: No module named 'selenium'
```
It's endless...

**Comment by Aouah** [comment]
After Selenium he asks to install requests, and after clarifai, etc...

I don't understand, why do I have to install all the apps twice ?
It seems that the problem comes from the pip3.5 + Python2.7 configuration but how to solve this ?
Nobody to help ?

FI, I was running the script with an older version until now without problem and I upgrated it because of the Xpath change on the login button.
I should have stayed on the older version... I am disgusted.

**Comment by Aouah** [comment]
Ok, solved it :)

The problem comes from the **pip3.5 + Python2.7** configuration as I expected.

So, in fact I had to create my virtual environment first to make sure that I run a **pip3.5 + Python3.5** configuration. The tutorial above explains how to do it (you can find it here : https://askubuntu.com/a/867145).
Then, when I'm logged into the (MYENV) environment I can follow the steps to install all the packages as described here : https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md

Don't forget to add "_headless_browser=True_" and "_nogui=True_" into your **quickstart.py** file and to switch the "_self.switch_language_" to _False_ into your **instapy.py** file too.

It works again !

**Comment by Aouah** [comment]
It runs well just one time and now I have this error :

```
Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 260, in login
    log_follower_num(self.browser, self.username, self.logfolder)
  File "/root/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/root/MYENV/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/root/MYENV/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/root/MYENV/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: headless chrome=64.0.3282.119)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.4.0-108-generic x86_64)
```

I'm giving up...

**Comment by Aouah** [comment]
I installed chromedriver 2.35 but I have still the same error.

**Comment by Aouah** [comment]
Finally... I have absolutely no clue but it works again. I cleaned my server and reinstall everything following this tutorial which I used the first time I ran Instapy : https://medium.com/@mcnamee/using-open-source-software-to-build-your-instagram-followers-205f908cf657

I don't know which difference makes it running well now.
I close this issue, thank you.

**Comment by AntoineIN** [comment]
Salut, si tu as réussi à installer le script sur ton VPS OVH, je serai bien intéressé par un coup de main !
Car j'ai des erreurs à chaque installation... Impossible de le mettre en place...

**Comment by Aouah** [comment]
Hello.

Oui, ça fonctionne très bien.
Il suffit de suivre la procédure sur le site dont j'ai donné l'adresse au dessus : https://medium.com/@mcnamee/using-open-source-software-to-build-your-instagram-followers-205f908cf657
> Installer Ubuntu et activer SSH
> Suivre la procédure 1) à la lettre : 
```
# Check for any server updates before we start
sudo apt-get update
# Install unzip, so we can unzip .zip packages
apt install unzip
# Install screen to let scripts run in the
# background, when we close SSH
apt-get install screen
# Install XVFB, for InstaPy
apt install xvfb
# Install Python's package manager
sudo apt-get install python3-pip
# Install Google Chrome, for InstaPy
cd /tmp && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
sudo apt-get -f install
# Make python accessible to the command line
sudo ln -s /usr/bin/python3 /usr/bin/python
```
> Suivre la procédure 2) : 
```
Create a home for the InstaPy at ~/instapy
mkdir ~/instapy && cd ~/instapy
Clone the repo from Git
git clone https://github.com/timgrossmann/InstaPy.git .
Run the installer: python setup.py install
Download the Chromedriver, placing it into /assets:
cd assets && wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
# Unzip the package
unzip chromedriver_linux64.zip
```
Et revenir au guide ici.
