### ISSUE TITLE
Cannot read property 'entry_data' of undefined - Happens only if Laptop Screen is Off or lid is closed

### ISSUE THREAD

**Issue by ArdySan2012** [InstaPy/InstaPy#1292]
I think I was able to pinpoint that "Cannot read property 'entry_data' of undefined" error which bugs quite a lot of people here. 

It happens when the laptop screen is switched off (or lid closed) - and usually within an hour as that happens (meaning script keeps working just fine for some time, and then):

`INFO - Image from: b'laekt_dk' Traceback (most recent call last): File "C:\Users\User\Desktop\InstaPy-master\START INNA.py", line 10, in <module> session.like_by_tags(['bryllup'], amount=150) File "C:\Users\User\Desktop\InstaPy-master\instapy\instapy.py", line 659, in like_by_tags self.logger) File "C:\Users\User\Desktop\InstaPy-master\instapy\like_util.py", line 483, in check_link "return window._sharedData.entry_data." File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script 'args': converted_args})['value'] File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute self.error_handler.check_response(response) File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of `undefined"`

Does anyone have any idea how to change that? (apart from keeping it bright all night). 
Happens regardless of the configuration of the instapy file (even on basic like only function), in Chrome, on the latest Chrome driver and Chrome versions (2.35 and 64 respectively)

**Comment by ArdySan2012** [comment]
Happens even with screen on now :(

**Comment by RoyBkker** [comment]
Having the same error

**Comment by ArdySan2012** [comment]
Happens on average once in an hour. Can’t figure out what to do :(

**Comment by mpaolor** [comment]
happens to me too..
in like_util.py
add import for formatNumber
then replace:
num_followers = browser.execute_script(
            "return window._sharedData.entry_data."
            "ProfilePage[0].user.followed_by.count")
with:
num_followers = (formatNumber(browser.find_element_by_xpath("//a[contains"
                     "(@href,'followers')]/span").text))
