### ISSUE TITLE
Newbie Login Issue

### ISSUE THREAD

**Issue by callahanryang** [InstaPy/InstaPy#1297]
Hello Everyone. I just got instaPy semi working. I cant get it past the initial login screen. Instead of clicking "Log in" in the bottom of the screen it is defaulting to the signup form and then glitching. I guess instagram changed their home screen. Is there something i need to setup in chrome first? It is opening a new chrome window where none of my sign ins or cookies exist. or is there a code change to get it to the proper login screen? the only thing i changed in the instapy.py script was "#from .clarifai_util import check_image" as the instructions indicated. Then python wanted like 20 to be indented. Those are the only changes I have made.

Thanks in advance. 

Ryan

**Comment by jeremycjang** [comment]
Hi Ryan,

That is how the program is set to run; it opens a new session (new browser instance on your device), navigates to Instagram, then logs in using the credentials you specified. The default screen is the signup form, but the program's written to navigate to the signup from there. Have you let the program do a full run before closing?

**Comment by callahanryang** [comment]
I suspect not. Does the login process usually take a few minutes?

**Comment by callahanryang** [comment]
![screenshot 4](https://user-images.githubusercontent.com/35872542/35475390-6311a838-0363-11e8-9c97-4fe390221b6c.png)

Heres the screen shot of whats happening...

**Comment by mark9009** [comment]
![bot](https://user-images.githubusercontent.com/32074028/35475595-974a13ea-03a1-11e8-9093-e8af39b1b11c.jpg)

**Comment by callahanryang** [comment]
I have fixed my issue.

Go into instapy\login_util.py Change lines 113 - 118 to comments (ie add # infront of the text) and it will login with no issues. My browser was set to English by default and this code tripped it up. :-)

**Comment by andrewshatnyy** [comment]
Also if you really need to have english set `//*[@id="react-root"]/section/footer/div/nav/ul/li[11]/span/select/option[6]` selector did the tick for me

**Comment by mark9009** [comment]
fixed thank you 
 
#    browser.find_element_by_xpath("//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["
    #                                 "@class='_luodr']/ul[@class='_g8wl6']/li[@class='_538w0'][10]/"
    #                                  "span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option"
    #                                  "[text()='English']").click()

**Comment by luigifaticoso** [comment]
If the problem is solved, you can close the issue

**Comment by obviousdonkey** [comment]
I have the same issue but had InstaPy running well for a while so Instagram must have changed something?

Not sure what you mean by this: 
Go into instapy\login_util.py Change lines 113 - 118 to comments (ie add # infront of the text).

How do I do that?

(Big time beginner speaking here) Thank you for your help!

**Comment by callahanryang** [comment]
Obvious, it's inside of the actual program files. Folder: instapy-master\(next folder)instapy\login_util.py (that's the name of the file. Right click to edit. When to document opens scroll down to line 113 highlights to 118 and hit delete. Save the file and you're good to go
