### ISSUE TITLE
Publish InstaPy on PyPi

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#13]
#### Would be nice if you could just install InstaPy with `pip install instapy` instead of downloading the repo

- [ ] get information about how to bundle a pypi package
- [ ] build pypi package
- [ ] publish it on pypi

**Comment by seemethere** [comment]
You could automate this through travis using https://docs.travis-ci.com/user/deployment/pypi/

**Comment by timgrossmann** [comment]
@seemethere This is really nice, I hope I'll find some time to do this!
Thanks for the link.

**Comment by rahulkapoor90** [comment]
Also, for digitalocean it would be really easy. do i have to copy and paste each individual files for it to run on digitalocean?

**Comment by timgrossmann** [comment]
@rahulkapoor90 You're completely right, it would make things a bit easier. Like I mentioned, I'll instantly look into it when I find some time to.

Thank you for your comment.

Also, you can just zip the whole folder and scp it onto your machine... Or way easier, just clone it directly onto your machine

**Comment by littleswany** [comment]
@rahulkapoor90 Unfortunately I don't think this is possible to do for DO, it has been requested for DO to create such a feature but at present it does not exist.

@timgrossmann Here is a [link](https://packaging.python.org/distributing/) on how to create a distributable for PyPi

**Comment by timgrossmann** [comment]
@littleswany Thank you!
This will be added for V1

**Comment by PJUllrich** [comment]
There seems to be a package on PyPi with this name already: https://pypi.python.org/pypi/instapy

Would be nice to have a package of this library on PyPi soon!

**Comment by timgrossmann** [comment]
@PJUllrich thank you for checking that out...

Yes, we'll try to make that happen pretty soon.

**Comment by Syslog777** [comment]
I did this for psak. Do you want help?
