### ISSUE TITLE
Error runing the bot in windows with everything installed correctly. Please help

### ISSUE THREAD

**Issue by marcosgb** [InstaPy/InstaPy#1300]
This is the error message the console gives me when I run the bot:

DevTools listening on ws://127.0.0.1:12520/devtools/browser/5ea60e29-26ba-432d-accd-478256e09eea                                            [4072:3332:0127/225843.298:ERROR:gpu_process_transport_factory.cc(1009)] Lost UI shared context.                                            [1908:1800:0127/225843.762:ERROR:command_buffer_proxy_impl.cc(115)] ContextResult::kFatalFailure: Shared memory handle is not valid         2018-01-27 22:58:44 - INFO - Session started - 2018-01-27 22:58:44    2018-01-27 22:58:44 - WARNING - Sorry, Record Activity is not working on Windows. We're working to fix this soon!                           Cookie file not found, creating cookie...                             Traceback (most recent call last):                                      File "C:\Users\Administrator\Downloads\InstaPy-master\InstaPy-master\quickstart.py", line 4, in <module>                                      session.login()                                                     File "C:\Users\Administrator\Downloads\InstaPy-master\InstaPy-master\instapy\instapy.py", line 253, in login                                  self.bypass_suspicious_attempt):                                    File "C:\Users\Administrator\Downloads\InstaPy-master\InstaPy-master\instapy\login_util.py", line 115, in login_user                          "//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\webdriver.py", line 293, in find_element_by_xpath                      return self.find_element(by=By.XPATH, value=xpath)                  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\webdriver.py", line 752, in find_element                               'value': value})['value']                                           File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\webdriver.py", line 236, in execute                                    self.error_handler.check_response(response)                         File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\errorhandler.py", line 192, in check_response                          raise exception_class(message, screen, stacktrace)                selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav[@class='_luodr']/ul[@class='_g8wl6']/li[@class='_538w0'][10]/span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option[text()='English']"}                     (Session info: chrome=64.0.3282.119)                                  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.14393 x86_64)                                                                                        Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x035B9B90>>                    Traceback (most recent call last):                                      File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 163, in __del__                                    File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 139, in stop                                       File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command             ImportError: sys.meta_path is None, Python is likely shutting down    [4072:3952:0127/225915.038:ERROR:connection.cc(1947)] Cookie sqlite error 1555, errno 0: UNIQUE constraint failed: cookies.creation_utc, sql: INSERT INTO cookies (creation_utc, host_key, name, value, encrypted_value, path, expires_utc, secure, httponly, firstpartyonly, last_access_utc, has_expires, persistent, priority) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)                                                              [4072:3952:0127/225915.041:ERROR:connection.cc(1947)] Cookie sqlite error 1555, errno 0: UNIQUE constraint failed: cookies.creation_utc, sql: INSERT INTO cookies (creation_utc, host_key, name, value, encrypted_value, path, expires_utc, secure, httponly, firstpartyonly, last_access_utc, has_expires, persistent, priority) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)                                                              [4072:3952:0127/225915.042:ERROR:connection.cc(1947)] Cookie sqlite error 1555, errno 0: UNIQUE constraint failed: cookies.creation_utc, sql: INSERT INTO cookies (creation_utc, host_key, name, value, encrypted_value, path, expires_utc, secure, httponly, firstpartyonly, last_access_utc, has_expires, persistent, priority) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)                                                              [4072:3952:0127/225915.046:ERROR:connection.cc(1947)] Cookie sqlite error 1555, errno 0: UNIQUE constraint failed: cookies.creation_utc, sql: INSERT INTO cookies (creation_utc, host_key, name, value, encrypted_value, path, expires_utc, secure, httponly, firstpartyonly, last_access_utc, has_expires, persistent, priority) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?

**Comment by harrydet** [comment]
See [https://github.com/timgrossmann/InstaPy/issues/1299](url)
