### ISSUE TITLE
How many account on same PC and same IP ?

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#1301]
I know that finger rule is 1 PC and 1 IP for account.
But researching online show that 3 account on same IP is OK.

My Q is, what about using same PC (not proxy-server) for more than 1 account ?
How safe is that ?
- user-agent that is the same
- Cookies are been deleted.
- what about Super-cookies ?

 what else should we consider ?

**Comment by wemakefuture** [comment]
Latly i was running 8 accounts on one IP this was way to much and i run into a hidden ban. No groth no interaction, felt just like something is offline. 
I will try it now with 2 accounts running over a proxy.

**Comment by sionking** [comment]
Hi, but those it matter if it the same PC or Instagram only check same IP ?

BTW, try use residential backoff proxy or SSL proxy...

**Comment by CharlesCCC** [comment]
Use a VPN usually helps.

**Comment by sionking** [comment]
This is not the question, I want to use the same PC (not a server nor VPN) home regular laptop with domestic IP address, and to run 2 different users on the same PC.

So I ask if it OK or they can know that this PC uses for 2 accounts.?

**Comment by CharlesCCC** [comment]
I had my two accounts running at all time. no problem here.

**Comment by converge** [comment]
Private proxies are good options, 1 proxy per IP, if some account is compromised, it wont affect the other ones.
