### ISSUE TITLE
Potential issue with random instagram Captcha Verification

### ISSUE THREAD

**Issue by CharlesCCC** [InstaPy/InstaPy#1302]
Issue:

Today, while i was randomly looking at the script i set up to run. I have noticed some sort of Instagram captcha verication window pops-up, the first time it just went to quickly and then the second time it just stuck in there without doing anything, i have manually typing the verification code in order to make sure it continue to run. (I did took a scree-shot of that if anybody interested to see)  

Not sure how many people have noticed it, I assume people usually like to set it to no-gui or headless mode, or like me, never actually monitor the running status. 

## Expected Behavior
Somehow bypass the captcha verification ?(not sure if it even possible) 
## Current Behavior
Stuck/Doing nothing
## Possible Solution (optional)
Manually input the verification code 
## InstaPy configuration
all the default setting with my username/password

**Comment by sionking** [comment]
I saw something related to notifican On/Off

**Comment by CharlesCCC** [comment]
@sionking nope, it is not about the notification.  I have seen it before, it usually showing at the very beginning of each run. but the recaptcha verification code is display in the middle of running.
