### ISSUE TITLE
Follow & Unfollow in between not follow back

### ISSUE THREAD

**Issue by aaronhimself** [InstaPy/InstaPy#1303]
Hey Tim & everyone else,
great work!
not sure if this is the right way to ask a question!?

Im read the wiki and cant get my head around how to let the bot add followers all day from #friend1 #friend2 and inbetween unfollow everyone that didnt follow me back within 24 hours (only people instapy followed). so it keeps running the whole time.

this is my quickstart that is of course not doing what i want. can someone bring me in the right direction? thx.

from instapy import InstaPy

insta_username = 'username'
insta_password = 'password'

# if you want to run this script on a server,
# simply add nogui=True to the InstaPy() constructor
session = InstaPy(username=insta_username, password=insta_password)
session.login()

# set up all the settings
session.set_upper_follower_count(limit=2500)
# session.set_do_comment(True, percentage=10)
# session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
# session.set_dont_include(['friend1', 'friend2', 'friend3'])
# session.set_dont_like(['pizza', 'girl'])

# do the actual liking
# session.like_by_tags(['natgeo', 'world'], amount=100)
session.follow_user_following(['friend1', 'friend2'], amount=10, randomize=False, sleep_delay=60)
session.unfollow_users(amount=10, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60 )

# end the bot session
session.end()

**Comment by lucanello** [comment]
I know this doesn't solve your problem completely, but atleast it is a workaround:

You could add `time.sleep(86400)` between following and unfollowing them again. This means it will wait 24 hours before the unfollowing starts. You'll need to `import time` to do that.

To make it run all the time you can add a while-Loop. Just paste `while True:` before your actions. Problem is: this will cause it to never correctly end the bot session.
