### ISSUE TITLE
Questions on Multi-account functionality

### ISSUE THREAD

**Issue by gitpatrickhub** [InstaPy/InstaPy#1306]
Does Multi-account overwrite existing logs? Or does it add new logs? How many accounts can it support? Does it support running concurrently? 

Thanks!

**Comment by CharlesCCC** [comment]
Go read the wiki and run it locally to experiment it. This kind of question is really busy to be answered if you just run the program.

**Comment by gitpatrickhub** [comment]
@CharlesCCC agree it's easily answered with a bit of experimentation, but was curious if anyone had already done the experimentation.

**Comment by CharlesCCC** [comment]
Please read

https://github.com/timgrossmann/InstaPy#running-multiple-accounts

`Use the multi_logs parameter if you are going to use multiple accounts and want the log files stored per account.`

**Comment by gitpatrickhub** [comment]
@CharlesCCC I understand what it does. My questions are a bit different. I'll have time to experiment with it this weekend. Don't worry about answering these items.
