### ISSUE TITLE
Instant cmd termination: 'InstaPy' object has no attribute 'logger'

### ISSUE THREAD

**Issue by Honigbrot** [InstaPy/InstaPy#1310]
## Expected Behavior
Start chrome, run the bot

## Current Behavior
Instant cmd termination - Powershell says (username and pw changed to xxx):

PS C:\Users\david\Documents\GitHub\InstaPy> py quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    session = InstaPy(username='xxx', password='xxx')
  File "C:\Users\david\Documents\GitHub\InstaPy\instapy\instapy.py", line 131, in __init__
    self.logger = self.get_instapy_logger(show_logs)
  File "C:\Users\david\Documents\GitHub\InstaPy\instapy\instapy.py", line 165, in get_instapy_logger
    self.logger = logging.LoggerAdapter(self.logger, extra)
AttributeError: 'InstaPy' object has no attribute 'logger'

On my notebook the bot works sort of fine (still getting that bug where only 12 posts are liked). Tried it on my main machine today and can't get past the basic setup.

Tried looking the issue up, but only found something about "aborting" or something about different lines.

## InstaPy configuration
completely basic was just used for testing - quickstart:
from instapy import InstaPy
import os

session = InstaPy(username='xxx', password='xxx')

session.login()

session.like_by_tags(['fitinn'], amount=50, media='Photo')

session.end()

Dowloaded and installed all software by the books and up-to-date
Python 3.6.4
Chromedriver 2.35
Up-to-date repository from github
Win 10 Pro 64 Bit

Thanks

**Comment by gruvismalt** [comment]
Same issue here using basic setup. Also Windows 10. Was running fine as of last night.

**Comment by Namaslayer** [comment]
Same issue here! fresh install as of about 10 minutes ago.

**Comment by gruvismalt** [comment]
To update, I reverted to a previous version from a few days ago and it's running fine so something in the new update is causing the error.

**Comment by Namaslayer** [comment]
@gruvismalt awesome! can you advise on how to do that?

@converge any ideas on how to fix with the current version?

**Comment by LordSuricato** [comment]
The same thing happens to me, I used the last version of day 27 and everything was fine

**Comment by Namaslayer** [comment]
@LordSuricato How to you revert back to and older version? I'm not sure how to do this.

**Comment by jasonheckman** [comment]
I removed the lines added in 

[https://github.com/timgrossmann/InstaPy/commit/d22808ccaaaec6b1c4b549896942d8536b641f8f#diff-de2ecb8866219bb53ba97e8377a2f26dL154](url)

and put the old removed line back and the script works again.

**Comment by davegallant** [comment]
Here's a fix:
https://github.com/timgrossmann/InstaPy/pull/1313

temporary workaround here:
https://github.com/timgrossmann/InstaPy/issues/1311

**Comment by uluQulu** [comment]
Alrighty guys, no need to remove those lines.

**Comment by uluQulu** [comment]
Alrighty guys, no need to remove those lines, the error is obvious
**The error is that it's accessing self.logger before it is ever assigned to**
Line 165 of that paste is assigning to self.logger (for the first time), but it is also trying to access self.logger
So let's not do that:
I am thinking that both instances of self.logger on that line should just be logger.
### Replace both to plain `logger`
It's fairly basic that they are different because they refer to entirely different things, logger and self.logger

**Comment by davegallant** [comment]
uluQulu, you're right. I need sleep. #1313 doesn't return the right logger.

**Comment by uluQulu** [comment]
hey dave, you should update your commit :-)

**Comment by Namaslayer** [comment]
@uluQulu just did a git pull and got this long string of errors. Any ideas?

<img width="920" alt="screen shot 2018-01-29 at 11 51 12 pm" src="https://user-images.githubusercontent.com/31394074/35554153-847bef54-054f-11e8-940a-5b4c77480076.png">

**Comment by Honigbrot** [comment]
Fetched origin and everything works fine again!
(had to change "self.switch_language" to "=False" though)

Thanks for your fast and awesome help!
Keep up the good work

**Comment by uluQulu** [comment]
@Namaslayer try renaming `self.logger` to `logger` in line 165 at `instapy.py`
```python
self.logger = logging.LoggerAdapter(logger, extra)   #you will change this line to below
```
becomes
```python
logger = logging.LoggerAdapter(logger, extra)
```
