### ISSUE TITLE
Error with session.follow_user_followers that occur suddenly after the last few commit

### ISSUE THREAD

**Issue by clevebounce** [InstaPy/InstaPy#1312]
## Expected Behavior

was working before. This punkhippie account has 3.5 million followers.

I tried another account that has less instagram followers and the error is the same.

## Current Behavior
WARNING - punkhippie -> Less users to follow than requested.
ERROR - follow loop error Sample larger than population or is negative
INFO - --> Total people followed : 0 
INFO - Number of people followed automatically remaining: 0
INFO - --> Total people unfollowed : 0

**Comment by uluQulu** [comment]
I think you're out of scroll

> in `util.py` find `scroll_bottom` function
try this:
```python
if range_int > 50:
    range_int = 150   #it will scroll page 75 (150/2 ) times now instead of 25 (50/2)
```
or if not works, remove `if range_int>50:` and simply put: 
```python
range_int = 150   #don't forget to indent back 4 spaces
```

**Comment by clevebounce** [comment]
@uluQulu still didn't seem to solve the problem, I specified 200 likes for 1 tag. but it only found 12 instances in one tag to 'like' even using the most popular tags
