### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by sninos** [InstaPy/InstaPy#1314]
## Expected Behavior
Help me to run the script and enjoy the code

## Current Behavior
ERROR 1
`Error: File "quickstart.py", line 16
 session.follow_user_followers(['monochrome.co.il', 'bootlegclub', 'fomo2.0'], amount=300, sleep_delay=, randomize=True, interact=False)
 ^
 SyntaxError: invalid syntax`

ERROR 2
`Cookie file not found, creating cookie...

Error: 2018-01-30 09:40:37 - INFO - Session started - 2018-01-30 09:40:37
 2018-01-30 09:40:37 - WARNING - Sorry, Record Activity is not working on Windows. We're working to fix this soon!
 Traceback (most recent call last):
 File "quickstart.py", line 5, in <module>
 session.login()
 File "C:\Users\amit\AppData\Local\Programs\InstaPyGUI\InstaPy-master\instapy\instapy.py", line 253, in login
 self.bypass_suspicious_attempt):
 File "C:\Users\amit\AppData\Local\Programs\InstaPyGUI\InstaPy-master\instapy\login_util.py", line 115, in login_user
 "//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav["
 File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 293, in find_element_by_xpath
 return self.find_element(by=By.XPATH, value=xpath)
 File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 752, in find_element
 'value': value})['value']
 File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
 self.error_handler.check_response(response)
 File "C:\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//footer[@class='_s5vm9']/div[@class='_g7lf5 _9z659']/nav[@class='_luodr']/ul[@class='_g8wl6']/li[@class='_538w0'][10]/span[@class='_pqycz _hqmnd']/select[@class='_fsoey']/option[text()='English']"}
 (Session info: chrome=63.0.3239.132)
 (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 6.1.7600 x86_64)
 
 Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x000001F95B7B2A20>>
 Traceback (most recent call last):
 File "C:\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 163, in __del__
 File "C:\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 139, in stop
 File "C:\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
 ImportError: sys.meta_path is None, Python is likely shutting down

`

![default](https://user-images.githubusercontent.com/35900324/35553841-2aae9c1c-05a2-11e8-9b1d-6604791836d7.PNG)

## InstaPy configuration
`from instapy import InstaPy

session = InstaPy(username='XXXXX', password='XXXX')

session.login()

session.set_dont_like(['bootleg'])
session.set_do_follow(enabled=True, percentage=70, times=5)
session.set_do_comment(enabled=True, percentage=70)
session.set_comments([uBOOM], media=None)
session.set_upper_follower_count(limit = 200000)
session.set_lower_follower_count(limit = 200)
session.like_by_tags(['telaviv', 'bootleg', 'fomo', 'igotfomo', 'party', 'techno', 'rave', 'adika', 'monochrome', ''], amount=100, media=None)
session.like_by_locations(['7645170/bootleg/'], amount=10000, media=None)

session.follow_user_followers(['monochrome.co.il', 'bootlegclub', 'fomo2.0'], amount=300, sleep_delay=, randomize=True, interact=False)
session.follow_user_following(['monochrome.co.il', 'bootlegclub', 'fomo2.0'], amount=300, sleep_delay=, randomize=True, interact=False)

session.end()`

**Comment by uluQulu** [comment]
@sninos 
Yeah, that code'll do that
Actually, it's not surprise that it does give a TypeError on line 16 or... a SyntaxError, really, because of that empty `sleep_delay=` argument
Also perhaps you wanna quote `uBOOM` in an argument inside set_comments when you call it?
```python
session.set_comments(['uBOOM'], media=None)
```
or if uBOOM is a list of comments, it should be
```python
uBOOM = ['Wow this is my comment!', 'WOOW another comment']   #uBOOM is a variable containing a list
session.set_comments(uBOOM, media=None)
```
The rest should work, also remove that empty quotes at the end of like_by_tags' tags

**Comment by sninos** [comment]
now the code is right ?

`from instapy import InstaPy

insta_username = 'c'
insta_password = 'c'

# set headless_browser=True if you want to run InstaPy on a server
try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      multi_logs=True)
    session.login()

    # settings
    session.set_upper_follower_count(limit=2500)
    session.set_do_comment(True, percentage=50)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Boom!'])


    # actions
	session.like_by_tags([
    'bootlegclub',
    'igotfomo',
    'technotelaviv',
    'adika',
    'monochrome',
    'beitmaariv',
    ], amount=1000, media=None)

	session.like_by_locations(['007645170/bootleg/'], amount=1000)
	session.follow_user_followers([
	'monochrome.co.il',
	'voodoobartlv',
	'bootlegclub',
	'fomo2.0',
	'alphabet_club',
	'technodrome.il',
	'omercohen_',
	'dean7gilad',
    ], amount=3000, sleep_delay=5, randomize=True, interact=False)
	session.follow_user_following([
	'monochrome.co.il',
	'voodoobartlv',
	'bootlegclub',
	'fomo2.0',
	'alphabet_club',
	'technodrome.il',
	'omercohen_',
	'dean7gilad',
    ], amount=3000, sleep_delay=5, randomize=True, interact=False)	
	



finally:
    # end the bot session
    session.end()
`

**Comment by uluQulu** [comment]
Yes it is, but don't forget the indentation blocks after `try` and `finally`
```python
try:
    session = InstaPy(username=insta_username,           #4 spaces (or 1 Tab -don't mix these)
    password=insta_password,                                         #indent
    headless_browser=False,                                             #after try
    multi_logs=True)                                                          #statements
    session.login()
    #some code here
```
and same for `finally`
```python
finally:
    #end the bot session
    session.end()
```
You might have knew it, above in the paste it's unindented, so I said in any case.
Hope helped! :-)

**Comment by sninos** [comment]
thank you so much, buddy but now there is a new problem

```


from instapy import InstaPy

insta_username = zzz
insta_password = zzz

# set headless_browser=True if you want to run InstaPy on a server
try:
	session = instapy.InstaPy(username=insta_username,
	password=insta_password,
	headless_browser=False,
	multi_logs=True)
	session.login()

	# settings
	session.set_do_comment(True, percentage=50)
	session.set_comments(['aMEIzing!', 'So much fun!!', 'Boom!'])

	# actions
	session.like_by_tags([
	'bootlegclub',
	'igotfomo',
	'technotelaviv',
	'adika',
	'monochrome',
	'beitmaariv',
	], amount=1000, media=None)

	session.like_by_locations(['007645170/bootleg/'], amount=1000)
	session.follow_user_followers([
	'monochrome.co.il',
	'voodoobartlv',
	'bootlegclub',
	'fomo2.0',
	'alphabet_club',
	'technodrome.il',
	'omercohen_',
	'dean7gilad',
	], amount=3000, sleep_delay=5, randomize=True, interact=False)
	session.follow_user_following([
	'monochrome.co.il',
	'voodoobartlv',
	'bootlegclub',
	'fomo2.0',
	'alphabet_club',
	'technodrome.il',
	'omercohen_',
	'dean7gilad',
	], amount=3000, sleep_delay=5, randomize=True, interact=False)	
finally:
	# end the bot session
	session.end()
	


```
error : 

> 
> `PS C:\Users\amit\AppData\Local\Programs\InstaPyGUI\InstaPy-master> python quickstart.py
> Traceback (most recent call last):
>   File "quickstart.py", line 8, in <module>
>     session = instapy.InstaPy(username=insta_username,
> NameError: name 'instapy' is not defined
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "quickstart.py", line 51, in <module>
>     session.end()
> NameError: name 'session' is not defined`
> 



hope that this is it

**Comment by uluQulu** [comment]
@sninos 
```python
try:
	session = instapy.InstaPy(username=insta_username,
	password=insta_password,
	headless_browser=False,
	multi_logs=True)
```
is wrong, remove `instapy` from `instapy.InstaPy(username...`
You are starting a new instance of InstaPy class named `session`, use InstaPy only once,
correct form is:
```python
try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      multi_logs=True)
```

**Comment by converge** [comment]
[fixed](https://github.com/timgrossmann/InstaPy/pull/1328)
