### ISSUE TITLE
Not finding pyvirtualdisplay

### ISSUE THREAD

**Issue by EvilDrAaron** [InstaPy/InstaPy#1316]
When I try to run quickstart.py, it says there is no module found for pyvirtualdisplay. However, when I attempt to install it with pip, it says requirement already satisfied. Help!

**Comment by chrismaltais** [comment]
Hey @EvilDrAaron! Thanks for submitting an issue.
Can you provide your `quickstart.py` file?
Are you trying to run without having the chrome GUI appear?

**Comment by txaiwieser** [comment]
Same thing here, downloaded a clean version and had the same error again

**Comment by patricmutwiri** [comment]
Me too

**Comment by cauvery-guda-eb** [comment]
same issue
