### ISSUE TITLE
KeyError: 'username'

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#1317]
## Expected Behavior
Script Start / Login

## Current Behavior
```Logged from file like_util.py, line 502
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
KeyError: 'username'
Logged from file like_util.py, line 502
```

**Comment by guilhermeherzer** [comment]
It's happening to me too.

**Comment by ShiftingKill** [comment]
Same here

**Comment by mkraffa** [comment]
same here

**Comment by mxmzb** [comment]
However it doesn't seem to be a very severe issue, as it still works fine.

**Comment by flo1t** [comment]
same here. it looks like verything else works normal, except the logging part. but you can check the stats using the db.

**Comment by uluQulu** [comment]
Okey guys, it's not important issue,
in line 165 of `instapy.py`
replace `self.logger` with `logger`
```python
self.logger = logging.LoggerAdapter(logger, extra)
```
should be
```python
logger = logging.LoggerAdapter(logger, extra)
```
of `get_instapy_logger()` method ...
@tibor @flo1t @mxmzb @mkraffa @ShiftingKill @guilherme199 
[details](https://github.com/timgrossmann/InstaPy/issues/1310#issuecomment-361485160)

**Comment by flo1t** [comment]
@uluQulu thanks for the solutions! works fine now.

**Comment by mkraffa** [comment]
@uluQulu 
nice one, works for me too,.
thanks!
