### ISSUE TITLE
Stuck on Login, issue with devtools?

### ISSUE THREAD

**Issue by adamaarts** [InstaPy/InstaPy#1318]
I had Instapy working like 6 months ago, I tried again this week and it wasn't working. I updated everything and this is now what I get, seems to just sit on the login page wothout attempting to login.

> D:\GearFindr\Github\InstaPy-master>set PYTHONIOENCODING=UTF-8
> 
> D:\GearFindr\Github\InstaPy-master>py quickstart.py
> 
> DevTools listening on ws://127.0.0.1:12268/devtools/browser/74f426ba-d0c8-405f-8
> 5a5-5f5868238821
> [5476:9400:0130/142936.873:ERROR:gl_surface_egl.cc(819)] eglInitialize D3D11 fai
> led with error EGL_NOT_INITIALIZED, trying next display type
> 2018-01-30 14:29:38 - INFO - Session started - 2018-01-30 14:29:38
> 2018-01-30 14:29:38 - WARNING - Sorry, Record Activity is not working on Windows
> . We're working to fix this soon!
> Traceback (most recent call last):
>   File "quickstart.py", line 4, in <module>
>     session.login()
>   File "D:\GearFindr\Github\InstaPy-master\instapy\instapy.py", line 245, in log
> in
>     self.bypass_suspicious_attempt):
>   File "D:\GearFindr\Github\InstaPy-master\instapy\login_util.py", line 95, in l
> ogin_user
>     update_activity()
>   File "D:\GearFindr\Github\InstaPy-master\instapy\util.py", line 45, in update_
> activity
>     conn = sqlite3.connect('./db/instapy.db')
> sqlite3.OperationalError: unable to open database file
>

**Comment by GOliveira10** [comment]
Same, any resolution?

**Comment by dc0d** [comment]
Inside `/usr/local/lib/python3.5/dist-packages/instapy/settings.py` I have added:

```
INSTAWD=os.environ['INSTAWD']
if INSTAWD != "":
    BASE_DIR = INSTAWD
```

And then defined an env var, `export INSTAWD=$PWD`.

Now I am struggling with relative paths. I am no Python guru, but using relative paths does not sound right to me. If absolutely necessary, `$PYTHONPATH` should be used for that purpose (using specialized/shortened/modified paths).
