### ISSUE TITLE
Question - way to stop the bot in the middle of the cycle, AND  see the report (liked-followed-inappropriate, etc)?

### ISSUE THREAD

**Issue by ArdySan2012** [InstaPy/InstaPy#1319]
Subj. Is it possible to stop the bot half way and see that report which is usually displayed only if the full cycle is accomplished?

**Comment by sionking** [comment]
Can be accomplished but complicated.

**Comment by sionking** [comment]
Better to just stop the loop .... showing the results is the difficult issue

**Comment by ArdySan2012** [comment]
Thank you!

**Comment by Marto32** [comment]
If you're kicking this off from the command line, you can write to logs an then just look through the logs.

```
python quickstart.py >> /path/to/your/log/file.log 2>&1
```

**Comment by sionking** [comment]
also ... 
```
    except KeyboardInterrupt:
        session.end()
        quit()
```

Can work but need some workarounds

**Comment by sionking** [comment]
ctrl + c
