### ISSUE TITLE
{{Feature Request}} Interactions based on the number of posts a user has

### ISSUE THREAD

**Issue by victorsandovalmattar** [InstaPy/InstaPy#1320]
To avoid following/liking/commenting on fake profiles, it would be awsome if someone could develop a script to prevent taking action on users profiles that do not have a certain amount of posts

**Comment by sionking** [comment]
Put a bounty on it....
BTW, it easy to do.

**Comment by victorsandovalmattar** [comment]
Would you please teach me how to do it?

**Comment by sionking** [comment]
I will soon PR some features just about that
