### ISSUE TITLE
Not liking or Commenting (Using Mac GUI)

### ISSUE THREAD

**Issue by underclass** [InstaPy/InstaPy#1326]
## Expected Behavior
Like and Comment on images

## Current Behavior
Appears to be trying to like images

## Possible Solution (optional)
tried #1083 https://github.com/timgrossmann/InstaPy/issues/1083

## InstaPy configuration
session.login()
```
session.set_dont_like([''])
session.set_do_follow(enabled=True, percentage=70, times=1)
session.set_do_comment(enabled=True, percentage=50)
session.set_comments([u'LovelyPic!', u'AmazingPhoto!'], media='Photo')
session.set_upper_follower_count(limit = 1000)
session.set_lower_follower_count(limit = 100)
session.like_by_tags(['weddingphotography'], amount=2, media='Photo')

session.end()
```
InstaPy seems to run, but never gets past accessing posts, I can't generate error logs, followed.txt shows 0.

I'm also running into this error;

Error: (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.12.6 x86_64)

and also this;
Error: Logged from file instapy.py, line 1581

**Comment by underclass** [comment]
Successfully working through terminal (python 3.6), but still having issues with python 2.7 and gui

**Comment by riccardorighettiphoto** [comment]
Hello, I am totally unable to comment any post...
