### ISSUE TITLE
NameError: name 'comment_image' is not defined

### ISSUE THREAD

**Issue by spikeyhair** [InstaPy/InstaPy#1327]
Found this error:
_Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.interact_user_followers(['kihonglee', 'fitness.union', 'dylanobrien'
], amount=10, randomize=True)
  File "C:\Insta Script\GitHub\InstaPy\instapy\instapy.py", line 1176, in intera
ct_user_followers
    self.user_interact_media)
  File "C:\Insta Script\GitHub\InstaPy\instapy\instapy.py", line 928, in like_by
_users
    commented += comment_image(self.browser,
NameError: name 'comment_image' is not defined_

The script just ended here.

This is what I put in the quickstart.py:
    session.set_upper_follower_count(limit=2500)
    session.set_do_comment(True, percentage=80)
    session.set_comments(['wow!', 'So much fun!!', 'Nicey!', 'hmmm...'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    #session.set_dont_like(['pizza', 'girl'])
    session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
    session.set_dont_unfollow_active_users(enabled=True, posts=5)
    session.set_do_follow(enabled=False, percentage=70)
    session.set_do_like(enabled=False, percentage=70)

    # actions
    #session.like_by_tags(['natgeo'], amount=1)
    #session.like_by_tags(['swag'], amount=1)
    session.follow_user_followers(['kihonglee', 'fitness.union', 'dylanobrien'], amount=10, randomize=True, sleep_delay=60)
    session.interact_user_followers(['kihonglee', 'fitness.union', 'dylanobrien'], amount=10, randomize=True)
    session.unfollow_users(amount=10, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60 )

Can anyone help?

**Comment by converge** [comment]
are you running the latest version ? Seems like a fixed issue.

**Comment by spikeyhair** [comment]
I just downloaded the script 2 days ago. When was the fix release and where can I download it?

**Comment by converge** [comment]
that's weird, I feel like I fixed it some months ago.

**Comment by spikeyhair** [comment]
@converge I remembered I read it some where here but now i can't seem to find it anymore. can you help me, please?

**Comment by spikeyhair** [comment]
I found out the root cause. It's because of this block of codes:
if os.name != 'nt':
    from .clarifai_util import check_image
from .comment_util import comment_image
from .like_util import check_link

From the setup instruction in https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Windows.md 
it ask me to comment "from .clarifai_util import check_image". After commenting this line and run quickstart.py, it gives me an indentation error and pointed at "from .comment_util import comment_image". So I indented "from .comment_util import comment_image" in order to be able to run the script but when the script wanted to comment an image, it will stopped and throw the error above (NameError: name 'comment_image' is not defined).

Therefore, I uncommented "from .clarifai_util import check_image", revert to the original script and then everything back to normal. The script able to comment images now.

**Comment by CheapInMadrid** [comment]
I am getting the same error but commenting and uncommenting doesnt give a solution:(

**Comment by riccardorighettiphoto** [comment]
Same here. I have just tried @spikeyhair hint, but I could not fix the problem.

**Comment by balakedev** [comment]
plz help

**Comment by Tjorriemorrie** [comment]
Can someone post a stacktrace again please. The OP's stacktrace is out of date with master.
@spikeyhair please update to master and post results.

**Comment by rodriguesprobr** [comment]
Same error here.
  File "/dados/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/dados/InstaPy/instapy/instapy.py", line 22, in <module>
    from .comment_util import comment_image
ImportError: cannot import name 'comment_image'
