### ISSUE TITLE
Delay period before unfollowing

### ISSUE THREAD

**Issue by underclass** [InstaPy/InstaPy#1330]
From the examples of the unfollow function;
`session.unfollow_users(amount=10, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60)`

This would unfollow 10 users every 60 minutes.

Is there a way to add a delay so that after following a user, unfollow can't be activated for a variable period eg:
`session.unfollow_users(amount=10, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60, unfollow_delay=10080)`

This would unfollow 10 users every 60 minutes, but only if account had been followed for 7 days or more.

**Comment by apolo-damasco** [comment]
This would be awesome!

**Comment by underclass** [comment]
I wonder if you could schedule this as a separate job with an offset;
https://github.com/timgrossmann/InstaPy#automate-with-schedule

**Comment by CharlesCCC** [comment]
Definitely a great idea, I believe this would potentially huge improve the throughput.

**Comment by sionking** [comment]
I have done a feature that unfollow each time we get to max followeing by user so we can drop unfollow_users

**Comment by underclass** [comment]
@sionking could you explain how you've achieved this please?

**Comment by sionking** [comment]
coding ... I will PR soon

**Comment by uluQulu** [comment]
[Here](https://github.com/timgrossmann/InstaPy/pull/1336) it is guys,
@underclass for delay of week, use
```python
unfollow_users(unfollow_after=168*60*60)
```
or just
_`unfollow_after=604800`_

> it's just seconds, for ease use `hours*minutes*seconds` format (1 week is 168 hours)

Also, the time is unique for every user..
@migueldierssen @CharlesCCC

_Hey_ @sionking _I didn't know you were working on this xD
I just wrote this yesterday, that I was to push but slept earlier.._

**Comment by CharlesCCC** [comment]
@uluQulu @sionking you guys are the best 👍
