### ISSUE TITLE
Multiple account support

### ISSUE THREAD

**Issue by harrydet** [InstaPy/InstaPy#1334]
InstaPy/examples/multi-account.py

This is the file in question. I just wanted a clarification on whether this example is supposed to work currently or if it is just an example for how it "would" work once the feature is implemented. I can't get this to run at the moment. It gets to the point where it is able to log in with both processes but then throws an exception when trying to locate elements of the website.

**Comment by lucanello** [comment]
Why don't you simply duplicate your quickstart.py with different login-data and run it e.g. in a screen? That's how I am solving it right now.

**Comment by CharlesCCC** [comment]
quickstart1.py
quickstart2.py
quickstart3.py
...
