### ISSUE TITLE
Non like issue

### ISSUE THREAD

**Issue by Dn4g** [InstaPy/InstaPy#1337]
Hello.
Yestorday try to use a quickstart.py, everything was okey.
But today bot write:
`INFO [user_support]  Image from: user
INFO [user_support]  Session started - 2018-02-02 13:35:56
INFO [user_support]  Logged in successfully!
INFO [user_support]  Username [1/1]
INFO [user_support]  --> user
INFO [user_support]  Getting user image list...
INFO [user_support]  Interaction begin...
INFO [user_support]  Post [1/500]
INFO [user_support]  Description:  image description
INFO [user_support]  --> Not following
**INFO [user_support]  --> Image Liked!**
INFO [user_support]  --> --> Commented: go dota

Comment have added, but like does not add.
There are no like at fact.
Via browser can add like without mistakes.
Try a another account and another user, but have some result. What I need to check?

Use a VPS with Debian _headless_browser=True nogui=True_

**Comment by FreakyBoy** [comment]
I have the same problem -_- 
see -> #993 

And bugfix #1105 not help in my case

**Comment by Dn4g** [comment]
Thanks for your answer.
After 24 hours like works now. May be, it was a soft ban from Instagram.

And I have a question:
Can I like a certain image from user?

**Comment by uluQulu** [comment]
@Dn4g 
`like_by_users()` or `like_from_image()` features can help
