### ISSUE TITLE
"Image not liked: None" (Image not liked count way too high)

### ISSUE THREAD

**Issue by flo1t** [InstaPy/InstaPy#1339]
## Current Behavior
If a Post contains a word from session.set_ignore_if_contains(['xyz']) the Image will be flagged as Inappropriate. The log says: "Image not liked: None".

## Expected Behavior
Don't Flag the post as inappropriate.

## Solution
Change Line 509 in like_util.py (switch True to **False**):
```
if any((word in image_text for word in ignore_if_contains)):
return False, user_name, is_video, 'None' 
```

**Comment by converge** [comment]
hey mate, you're missing something, check it out: https://github.com/timgrossmann/InstaPy#restricting-likes

**Comment by flo1t** [comment]
hi converge, when i set:
```
session.set_dont_like(['food'])
session.set_ignore_if_contains(['alp'])
session.like_by_tags(['mountains'], amount=5)
```

and the post is marked with: #food #dinner #swissalps #mountains

the post should be liked, right? at least this was the behaviour in the last version i used. or did the behaviour change?
because of this i changed line 509.

**Comment by flo1t** [comment]
i'm still experience this issue. or do i understand something wrong with the "set_ignore_if_contains"?

**Comment by Tjorriemorrie** [comment]
Can you check the log for what appears after `Description: ` or otherwise please attach that user's general.log

**Comment by flo1t** [comment]
INFO [2018-03-14 20:21:29] [xyz]  --> Image not liked: b'None'

-> with the posted fix it work's like it should

**Comment by CodeMaster1** [comment]
I have faced the same issue as pointed here and did the same thing to get it resolved.
