### ISSUE TITLE
Problem with session.like_by_tags function since the last few commits

### ISSUE THREAD

**Issue by clevebounce** [InstaPy/InstaPy#1340]
## Current Behavior
the function session.like_by_tags has a problem which it does not have before.. If I specify 6 tags each 200 likes for instances, it would only do 200 likes for the first tag.. the rest of the tags maybe each 12. that is what is happening to me

**Comment by lucanello** [comment]
What tags did you specify? This could happen when the provided tags don't contain more than 200 posts to like.

**Comment by clevebounce** [comment]
it is quite impossible are these are big tags like #instadaily 
I tried restarting the bot after it found 12 tags for the 2nd tag in the order and place it as the first tag. It found 200 post to like; however, the 2nd and 3rd tag each only found 12. Again I place the 3rd tag as the first tag in the order, it found 200 post.

This problem seems to have been solve after the last commit.. let me test it further

**Comment by clevebounce** [comment]
no.. the error is still present after trying

**Comment by lucanello** [comment]
I see, this is now also happening to me. Only 27 images are loaded each tag even though I specified more. Also the runtime which I capture additionally is about 30% shorter than usually. Strange that this problem affects me now - 2 days later. Maybe it's a versioning problem? Or else the 2 days can be explained as a cache effect.
Could you run a session with the browser visible and capture it? This could help us understand what is going wrong.

**Comment by Naramsim** [comment]
Hi, same problem on my side, only 27 images are liked, no matter what `amount` is. This occurs only in like_by_tags, not like_by_feed

**Comment by Naramsim** [comment]
It is something around this line:
https://github.com/timgrossmann/InstaPy/blob/e410d1ded99b43df94f93df73f5de6d6ef98046b/instapy/like_util.py#L193

Probably the bot cant scroll the `amount/12` of times, so it sees only the initial images loaded.
