### ISSUE TITLE
Can't start session on Raspberry Pi 3

### ISSUE THREAD

**Issue by estebancortero** [InstaPy/InstaPy#1345]
I'm struggeling to get InstaPy running on my Pi 3. I followed the instructions [here](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Raspberry.md), but I always get the following error when running `python3 quickstart.py`:

```
Traceback (most recent call last):
  File "quickstart.py", line 11, in <module>
    multi_logs=False)
  File "/home/pi/git-repos/InstaPy/instapy/instapy.py", line 134, in __init__
    self.set_selenium_local_session()
  File "/home/pi/git-repos/InstaPy/instapy/instapy.py", line 198, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status: 1


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 28, in <module>
    session.end()
NameError: name 'session' is not defined
```

Running with `sudo` doesn't change anything. My `quickstart.py` looks as follows (just with username and password):

```
from instapy import InstaPy

insta_username = ''
insta_password = ''

# set headless_browser=True if you want to run InstaPy on a server
try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      use_firefox=True,
                      multi_logs=False)
    session.login()

    # settings
    session.set_upper_follower_count(limit=2500)
    session.set_lower_follower_count(limit=50)
    session.set_do_comment(True, percentage=30)
    session.set_comments(['Nice!', 'Love it :)', 'Perfect!', 'Great picture! @{}'], media='Photo')
    session.set_do_follow(enabled=True, percentage=50, times=2)

    # actions
    session.unfollow_users(amount=30, onlyNotFollowMe=True)
    session.like_by_tags(['travel'], amount=1)
    session.like_by_feed(amount=20, randomize=True, unfollow=True, interact=True)

finally:
    # end the bot session
    session.end()
```

I believe, it's a problem with Firefox. I had problems with the suggested workflow and had to install Firefox with [these instructions](https://www.raspberrypi.org/forums/viewtopic.php?t=150438). But now Firefox should be working and I downloaded and copied geckodriver as instructed.

**Comment by gitpatrickhub** [comment]
Updated how to instructions under #1253

**Comment by VBMH** [comment]
running in the same issue

**Comment by Marto32** [comment]
It's working fine for me on RPi 3. I pulled from master this morning and have it up and running fine. Here is my setup:

```
Raspbian GNU/Linux 9 (stretch)
Python 3.6.4
Mozilla Firefox 52.6.0 (downloaded via sudo apt-get install firefox-esr)
Geckodriver v0.18.0
```
Here is my quickstart excerpt:

```
try:
    session = InstaPy(
        username=insta_username,
        password=insta_password,
        use_firefox=True,
        page_delay=25,
        nogui=True)
    session.switch_language = False
    session.login()

    # settings
    session.set_comments(['some list of comments'])

    # actions
    session.set_do_comment(True, percentage=50)
    session.set_user_interact(
        amount=3, randomize=True, percentage=100, media='Photo')
    session.like_by_tags(['tags'], amount=10, interact=True)

finally:
    # end the bot session
    session.end()
```

I launch the script using `xvfb-run -a python quickstart.py`

I've gotten an automated setup to work for Raspberry Pi 3 via ansible which you can check out [here](https://github.com/Marto32/ansible-raspi-playbooks). It's based on [this guide](https://sendgrid.com/blog/complete-guide-set-raspberry-pi-without-keyboard-mouse/) and forked from [this setup](https://github.com/garthvh/ansible-raspi-playbooks).

Hope this helps you both!

**Comment by estebancortero** [comment]
Hm, thanks for the help. I'm wondering, why I had to go through the trouble of removing firefox-esr and download a different version. I now installed firefox-esr again and adjusted my `quickstart.py` to look like yours, but unfortunately, it still doesn't work. I get the same error just with error code 4 instead of 1 now.

However, `python3` on my RPi3 is Python 3.5.3. Also, I have Geckodriver v0.19.1. And I still have the other firefox version installed. Do you think this is causing me trouble? At least the Python and the Geckodriver version shouldn't cause any trouble....

**Comment by Marto32** [comment]
@estebancortero I think the issue is your geckodriver. If you look on their [releases page](https://github.com/mozilla/geckodriver/releases), starting with v0.19.0 they recommend firefox 55 and above. I believe the version of firefox-esr that's installed via apt-get is 52.

```
Note that with geckodriver v0.19.0 the following versions are recommended:

Firefox 55.0 (and greater)
Selenium 3.5 (and greater)
```

I would downgrade to geckodriver v0.18.0. Also, I believe there is a PR out for this, but in the mean time I would change your display size in [this line](https://github.com/timgrossmann/InstaPy/blob/e410d1ded99b43df94f93df73f5de6d6ef98046b/instapy/instapy.py#L69) to be 1900 x 1200 just to be safe (this caused me a lot of issues).

**Comment by estebancortero** [comment]
Perfect thanks a lot!

Deleting my [previously installed version of firefox](https://www.raspberrypi.org/forums/viewtopic.php?t=150438) with `sudo apt-get remove firefox`, installing firefox-esr, replacing geckodriver with v18, and adjusting the display size to be larger fixed my problem :)

**Comment by quintendewilde** [comment]
@Marto32 Hi is it possible to not run it headless?

**Comment by Marto32** [comment]
@BLCKPSTV probably but I haven't tried it. i don't have a monitor or keyboard for my RPi so I always run headless and ssh in.
