### ISSUE TITLE
Cyrillic in command line

### ISSUE THREAD

**Issue by denisemenov** [InstaPy/InstaPy#1350]
## Expected Behavior

`INFO [alpajessica]  Session started - 2018-02-04 13:58:10`
`INFO [alpajessica]  Logged in successfully!`
`INFO [alpajessica]  Tag [1/9]`
`INFO [alpajessica]  --> зенненхунд`

## Current Behavior
`INFO [alpajessica]  Session started - 2018-02-04 13:51:15`
`INFO [alpajessica]  Logged in successfully!`
`INFO [alpajessica]  Tag [1/9]`
`INFO [alpajessica]  --> b'\xd0\xb7\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xb5\xd0\xbd\xd1\x85\xd1\x83\xd0\xbd\xd0\xb4'`

## Possible Solution (optional)
Remove `.encode('utf-8')` from all files.

## InstaPy configuration
Digital Ocean, Ubuntu 16.04.3 LTS, Python 3.5.2

**Comment by uluQulu** [comment]
We should definetely remove it from logger messages
