### ISSUE TITLE
name 'session' is not defined

### ISSUE THREAD

**Issue by LoneWolfsMoon** [InstaPy/InstaPy#1351]
>>> python quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 26, in <module>
    session.end()
NameError: name 'session' is not defined

**Comment by lucanello** [comment]
How does your quickstart.py look like? Can you provide some more informations to make it easier to help you?
Try defining session like this:
`session = InstaPy(username=insta_username, password=insta_password)`

**Comment by LoneWolfsMoon** [comment]
![screenshot at 2018-02-05 12-40-00](https://user-images.githubusercontent.com/30674228/35804931-b9baa8aa-0a71-11e8-90b3-60a267bc0325.png)

**Comment by LoneWolfsMoon** [comment]
I think I actually have accidentaly ran " wait-for-selenium.sh " file ....

**Comment by LoneWolfsMoon** [comment]
![error](https://user-images.githubusercontent.com/30674228/35919256-70fc667a-0c0c-11e8-96a1-196c2c8e74b9.png)

**Comment by DavidMolinari** [comment]
Have you already done this step ?
4. Download ```chromedriver``` for your system [from here](https://sites.google.com/a/chromium.org/chromedriver/downloads). Extract the .zip file and put it in ```/assets``` folder.

**Comment by LoneWolfsMoon** [comment]
Thank you , it works .. It looks like I have ran "wait-for-selenium.sh" and it deleted it ...

**Comment by LoneWolfsMoon** [comment]
Is there a feature that you can follow users who liked specific photo ?
