### ISSUE TITLE
The bot has cannot seem to execute session.follow_user_followers

### ISSUE THREAD

**Issue by clevebounce** [InstaPy/InstaPy#1353]
## Expected Behavior
punkhippie has more that 3 million followers
## Current Behavior
 punkhippie -> Less users to follow than requested.
ERROR [chan.cleve]  follow loop error Sample larger than population or is negative
INFO [chan.cleve]  --> Total people followed : 0 
ERROR [chan.cleve]  set_automated_followed_pool error [Errno 2] No such file or directory: '

**Comment by uluQulu** [comment]
@clevebounce 

First check if you have `myusername_followedPool.csv` file in `logs` folder

How many of followers did you already follow of _punkhippie_?

**Comment by clevebounce** [comment]
@uluQulu the log file is empty

**Comment by clevebounce** [comment]
WARNING [myusername]  punkhippie -> Less users to follow than requested.
ERROR [chan.cleve]  follow loop error Sample larger than population or is negative
INFO [chan.cleve]  --> Total people followed : 0 
ERROR [chan.cleve]  set_automated_followed_pool error [Errno 2] No such file or directory: './logs/myusername/myusername_followedPool.csv'

**Comment by uluQulu** [comment]
maybe you have already followed about 1000 users from `punkhippie` so that it can't find more people to follow cos of the current scroll limit, did you?

**Comment by clevebounce** [comment]
@uluQulu  i doubt that.. I have tried other user, and every user returns the same error

**Comment by driesketels** [comment]
Same problem here. Did you already found a solution? I cannot seem to find one.

**Comment by SDKFJ55LDK8K2** [comment]
Same problem here. Did you already found a solution? I cannot seem to find one. 
Greetings

**Comment by SDKFJ55LDK8K2** [comment]
#1386  Think these two are linked. Not sure though.

**Comment by SDKFJ55LDK8K2** [comment]
Ps I'm facing the following error:
 - ERROR - follow loop error sample larger than population
And have no clue where it comes from 

@clevebounce 
For the second error your myusername_followedPool.csv shouldn't be empty. Taking the error into account, if this is not the first time you are using the bot, your script is probably not linking to the right csv file.
