### ISSUE TITLE
Anybody knows how to automate InstaPy on Pi 3?

### ISSUE THREAD

**Issue by alexsmedile** [InstaPy/InstaPy#1354]
I'm struggeling to get InstaPy running on schedule using Crontab.
`30 6 * * * /usr/bin/python /home/pi/Projects/InstaPy/AntidoteBot_Quickstart_v2.py`

Error:
```
Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/AntidoteBot_Quickstart_v2.py", line 10, in <module>
    bot.login()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 257, in login
    self.bypass_suspicious_attempt):
  File "/home/pi/Projects/InstaPy/instapy/login_util.py", line 96, in login_user
    update_activity()
  File "/home/pi/Projects/InstaPy/instapy/util.py", line 46, in update_activity
    conn = sqlite3.connect('./db/instapy.db')
sqlite3.OperationalError: unable to open database file
```
I've changed all the folders and files permission. It still doesn't work.

**Anybody knows how to automate InstaPy on Pi 3?**
I've tried schedule for python but once the first session is completed my code does not want to go on. #1235

**Comment by ganeshkrishnan1** [comment]
You need to set the script working folder to /home/pi/Projects/InstaPy/ before you run the script. Else cron is going to run the script from it's folder and the script is looking for db in the cron's working folder.
I hope I am making it clear.

Two ways to solve it.
create a bash script which will cd to the folder and then execute the python script (This is my preferred method)
or

`30 6 * * *  cd /home/pi/Projects/InstaPy/ &&  /usr/bin/python /home/pi/Projects/InstaPy/AntidoteBot_Quickstart_v2.py`

**Comment by alexsmedile** [comment]
@ganeshkrishnan1 Yeah! Sounds logic. Thanks for your reply!

But... :(
I added the script to my crontab, but it doesn't start. What am I failing?
By starting it `cd /home/pi/Projects/InstaPy/ && /usr/bin/python /home/pi/Projects/InstaPy/AntidoteBot_Quickstart_v2.py` from the folder terminal everything works fine.

**Comment by ganeshkrishnan1** [comment]
@rRexee 
create a script that changes working directory to the project directory and starts execution. I will add a pull request for a sample script today but it's very easy to create it..

Also "doesn't start" doesn't mean much. Whats the exact error? log files? stack trace?

**Comment by alexsmedile** [comment]
@ganeshkrishnan1 

Oh sorry, I didn't see any terminal open so I thought it wouldn't even start. I run `grep CRON /var/log/syslog` , that's what I got:
```
Feb  8 17:00:01 raspberrypi_alex CRON[15665]: (pi) CMD (cd /home/pi/Projects/InstaPy/ && /usr/bin/python /home/pi/Projects/InstaPy/like_smartnews_tag.py)
Feb  8 17:00:04 raspberrypi_alex CRON[15659]: (CRON) info (No MTA installed, discarding output)
Feb  8 17:17:01 raspberrypi_alex CRON[15696]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Feb  8 17:40:01 raspberrypi_alex CRON[15733]: (pi) CMD (cd /home/pi/Projects/InstaPy/ && /usr/bin/python /home/pi/Projects/InstaPy/AntidoteBot_Quickstart_v2.py)
Feb  8 17:40:05 raspberrypi_alex CRON[15729]: (CRON) info (No MTA installed, discarding output)
```
I installed MTA postfix (following a guide) `sudo apt-get install postfix` as local
and in crontab I added this as first line: `MAILTO=""`

I changed working directory. Let's see if that works.....
`44 18 * * * root cd /home/pi/Projects/InstaPy/ && run-parts --report /etc/cron.hourly`

**NOPE :(**
Nothing happens.
```
Feb  8 18:44:01 raspberrypi_alex CRON[17105]: (pi) CMD (root cd /home/pi/Projects/InstaPy/ && run-parts --report /etc/cron.hourly)
Feb  8 18:45:01 raspberrypi_alex CRON[17115]: (pi) CMD (cd /home/pi/Projects/InstaPy/ && /usr/bin/python /home/pi/Projects/InstaPy/like_smartpop_tag.py)
Feb  8 19:00:01 raspberrypi_alex CRON[20851]: (pi) CMD (cd /home/pi/Projects/InstaPy/ && /usr/bin/python /home/pi/Projects/InstaPy/like_business_tag.py)
```
