### ISSUE TITLE
Feature: Print screenshot at end (also when getting error)

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#1356]
It is good to see the last screen before we got error that sent us to end function.

so just add:
```
        #save the last mode screenhoot
        self.browser.get_screenshot_as_file('./logs/screen.png')
```
at the end function.

**Comment by sionking** [comment]
need to change to logfolder for multi users

**Comment by CharlesCCC** [comment]
Great idea, this could help us catch issue like this issue that I opened #1302 
Are you able to make a pull request and also add the log for multipler users ? Thank you @sionking

**Comment by CharlesCCC** [comment]
another question, Will this working with Headless browser ???
