### ISSUE TITLE
Skipping log in and just viewing posts. 

### ISSUE THREAD

**Issue by balakedev** [InstaPy/InstaPy#1358]
## Expected Behavior
Log in screen > enters account info > starts working normally.
## Current Behavior
Log in screen > gos to google > goes to account page > starts viewing posts.
## what ive done
i had a look around at other posts, i cleared cache and settings for the chrome driver. Seems to only be isolated on this account. 

So whats happening is the bot is basically skipping logging in, its just viewing posts now and there is a banner (see image) which suggests that the view should make an account or log in. 

<img width="790" alt="screen shot 2018-02-05 at 12 17 15 am" src="https://user-images.githubusercontent.com/20205385/35794268-f7ab04e2-0a09-11e8-856f-31e835edabd6.png">

**Comment by balakedev** [comment]
managed to fix this myself. To anyone who comes across this issue:

head to the instaPy-master file > logs > *delete cookie* ( you have to delete cookie from file. Should work after that :)

**Comment by hoseinit** [comment]
Solve my problem too, tnx
