### ISSUE TITLE
Making InstaPy able to run system-wide

### ISSUE THREAD

**Issue by lucanello** [InstaPy/InstaPy#1362]
Hello!

InstaPy is currently only available through the Github repository. This makes it really unhandy to work with since the Python scripts which start a InstaPy-session are located inside the cloned folder.
When updating this folder the changes made to your `quickstart.py` will be overwritten by the standard example `quickstart.py`. And also the chromedriver, your logs and so on will be replaced.
Furthermore the installation of InstaPy isn't possible with `pip install instapy-bot` (or anything else since the package instapy is already existing). That's because the paths directing to the database (`./db/instapy.db`), to the chromedriver (`./assets/chromedriver`) and to the logs (`./logs/`) are relative.

To change this, the repository needs to be cloned into your Python library folder (e.g. `/usr/lib/python3.4/InstaPy`). But then the problem appears that InstaPy can't locate the chromedriver and database since the `quickstart.py` Python script isn't located in the InstaPy folder.

I solved this problem by adding a new global variable called `Settings`. With
```
Settings.browser_location = "/usr/lib/pythonX.X/InstaPy/assets/chromedriver"
Settings.database_location = "/usr/lib/pythonX.X/InstaPy/db/instapy.db"
```
the locations for the two files can be changed. This gives the opportunity to place all files (`quickstart.py`, `instapy.db` and `chromedriver`) wherever you want.

These changes make InstaPy also compatible with the Python Package Index, so you can install InstaPy with `pip install instapy-bot` or so.

My pull request can be found here: https://github.com/timgrossmann/InstaPy/pull/1355 where I also addressed this issue: https://github.com/timgrossmann/InstaPy/issues/1342 which makes it possible to read the informative variables which are logged after each action ran.

Next problem I will address is the relative variable for logging. Right now, when running the `quickstart.py` Python script from anywhere else of the system, the `logs/` folder will be created in the directory the `quickstart.py` is located. This doesn't really matter, but it would be also nice to be  able to adjust this via:
```
Settings.logs_location = "/path/to/logs/folder/"
```

Thank you.

**Comment by CharlesCCC** [comment]
Instead of change this two location, we can simply exclude those two from git unless there is change that require to update those two files.

**Comment by lucanello** [comment]
Hey @CharlesCCC, thanks for your response. But this doesn't solve the problem I described above. When we're simply excluding the `chromedriver` (which must be downloaded from google anyways, it isn't included in the repository) and the database, it doesn't change anything on the fact, that the InstaPy folder will be overwritten when updating from the repository. Which also overwrites your `quickstart.py` script and your logs.
