### ISSUE TITLE
What are some good parameters that are neither too aggressive nor too conservative for InstaPy?

### ISSUE THREAD

**Issue by instanetk** [InstaPy/InstaPy#1363]
I tried Gramista for 100 days to some really good results. In the activity tab I could often see the program taking "breaks" or "going to sleep for the night." All in the effort of staying within the parameters of not being flagged for abusive behavior. 

As I'm trying to learn with InstaPy, I have learned to recognize that a lot of the most successful and largest Instagram accounts are in fact running automation bots. 

But unlike Gramista or any other service, InstaPy is completely configurable by the end user. My question is, how can we get to a calibrated set of parameters that would be optimized to achieve the maximum growths while maintaining the safety of our accounts?

How many follows, likes and unfollows per session and then how many times to schedule the cron job?

Is there any insights or data into this?

**Comment by ganeshkrishnan1** [comment]
This is not an issue. We need to have a forum or discord to talk about these to keep the issue tracker clean.

please close this.

**Comment by instanetk** [comment]
Agreed.
