### ISSUE TITLE
Restrict Comments/Likes/Follows by Location

### ISSUE THREAD

**Issue by underclass** [InstaPy/InstaPy#1367]
I'm trying to understand the like by locations feature, and if it can be used in conjunction with Comments/Likes/Follows. I've read through the issues and docs, but can't find confirmation of what I am trying to do.

I would like to leave comments and follow **only in the specified location area**, based on two tags;

```
# Comments
session.set_do_comment(True, percentage=20)
session.set_comments(['Great Shot!', 'This is wonderful', 'So good!', 'Lovely!!'], media='Photo')

# Follow from the tags, only once
session.set_do_follow(enabled=True, percentage=50, times=1)

# actions
session.like_by_locations(['224442573/salton-sea/'], amount=100)
session.like_by_tags(['wedding', 'weddingphotography'], amount=2)
```

Is this possible?

**Comment by uluQulu** [comment]
hi @underclass 
initially, the `like_by_locations()` feature is able to do what is intended
```python
##SETTINGS
#Likes' state
session.set_do_like(enabled=True, percentage=85)
#Comments' state
session.set_do_comment(enabled=True, percentage=20)
session.set_comments(comments=['Geat Shot!', 'So good', 'Etc..'], media='Photo')
#Followings' state
session.set_do_follow(enabled=True, percentage=50, times=1)

##ACTIONS
session.like_by_locations(locations=['224442573/salton-sea/'], amount=100, media=None, skip_top_posts=False)
```
It will do in the order of, getting **links** of 100 pictures from _salton-sea_ tagged Instagram location, then open them **one by one** 
**and**
it will **check** if likes enabled and/or comments (or clarifai specific comments) enabled and/or follows enabled
**and** 
if **any** of the actions (like, comment and follow) is enabled, for each post, if will first try to like, then try to comment and then try to follow [..**considering** their percentages, actually..]

actually, you **can** understand the procedure of any feature by **reading** it's method in InstaPy class at `instapy.py`
is this what you wanted?

**Comment by underclass** [comment]
Hello @uluQulu 

So, to confirm with your code, this will;

Like any post
Comment on any photo
Follow any user
**Within location: 224442573/salton-sea/**

I would like to do the following;

Like only posts tagged 'foo' or 'bar'
Comment only photos from the tags 'foo' or 'bar'
Follow from the tags 'foo' or 'bar'
**Within location: 224442573/salton-sea/**

The idea is that I could restrict the considered users to a geographical area, to keep them relevant.

**Comment by underclass** [comment]
I think it's similar to this: https://github.com/timgrossmann/InstaPy/issues/1104

**Comment by uluQulu** [comment]
Well, i guess it's the same idea I realized when saw your issue xD

You **wanna** do some stuff while all those interactions take place at users from **certain** location(s)
e.g. doing some acitivities, such as,
like_by_tags, follow_by_tags, etc
and still stick to the salton-sea only location while ignoring posts from other locations..

**well it's practically possible, but not effective..**
while you do like_by_tags (_or other activity_), it can check posts' **tagged** location; first location can be **empty**, second it has a very rare **chance** the location is as intended (unless you choose e.g. the US ) so that so many posts will be skipped just bcos not matching that location

our feature, like_by_locations is **getting** a ready list of pics from that location and does interactions based on those pictures

**at last**, getting geolocation of a post (pic or a video) is done by reading it's **tagged** location
you know, you can't guess people who write **caption** in turkish is located in Turkey, or those in english are britanians..

> i don't know maybe some technic can help us get geolocation predictions...

**Comment by underclass** [comment]
I think below demonstrates what I'm trying achieve;

```
##SETTINGS
#Like
session.set_do_like(enabled=True, percentage=85)
#Comments
session.set_do_comment(enabled=True, percentage=20)
session.set_comments(comments=['Comment1', 'Comment2'], media='Photo')
#Follow
session.set_do_follow(enabled=True, percentage=50, times=1)

#Tags
session.set_by_tags(['foo', 'bar'], media='Photo')

##ACTIONS
session.like_by_locations(locations=['GB/united-kingdom/'], amount=100, media='Photo')
```

I did wonder what ```media=None``` would do from your example?

**Comment by uluQulu** [comment]
It will **first** like by tags (_it will not care what the posts' location is_) normally, **then** will do like by locations (_will find pictures tagged with the location you defined_)
 and those _settings_ of `set_do_like()`, `set_do_comment()`, `set_comments()` and `set_do_follow()` configuration will be the same for both activities
if you want to have these settings different configuration for each activity, you can simply declare them again before DO'er actions, e.g.,
for having different comment ratio for different activities :
```python
#some settings
#...
#actions
session.set_do_comment(enabled=True, percentage=20) #commenting percentage is 20 from now
session.like_by_tags(['foo', 'bar'])

session.set_do_comment(enabled=True, percentage=77)  #commenting percentage is 77 from now on..
session.like_by_locations(locations=['GB/united-kingdom/'], amount=100, media='Photo')
```
this style is very recommended, almost all my activities use standalone **specific** configuration in settings to provide randomized casual **usage** . . .
`media = None` chooses both 'Photo' and 'Video', it just doesn't care the type of media, .. i just wanted to include all default arguments . . .

**Comment by underclass** [comment]
Ah, I see, this is how I thought InstaPy would handle this at the moment, but the activity ratio illustrated above is very useful :). 

What I'd like the functionality to do is what we mentioned earlier, performing the actions of commenting, liking and following based on specific #tags, within a specified geo location, (UK) as one action.
