### ISSUE TITLE
name 'session' is not defined 

### ISSUE THREAD

**Issue by LoneWolfsMoon** [InstaPy/InstaPy#1369]
python quickstart.py
Traceback (most recent call last):
File "quickstart.py", line 26, in
session.end()
NameError: name 'session' is not defined

![screenshot at 2018-02-05 12-40-00](https://user-images.githubusercontent.com/30674228/35881831-0430643e-0b7a-11e8-826c-6452ad65bf2f.png)

**Comment by professorfabioandrade** [comment]
Same here. Using raspberry pi 3, raspbian jessie and firefox.

**Comment by professorfabioandrade** [comment]
I solved my issue installing geckodriver 0.18, firefox-esr (version 52.6), changing the screen size to 1900x1200, putting nogui=True and changing from .set_switch_language(False) to .set_switch_language = False
