### ISSUE TITLE
Comments eventually get blocked

### ISSUE THREAD

**Issue by Namaslayer** [InstaPy/InstaPy#1371]
## Expected Behavior
runs script from crontab and leaves random comment from set of 4

## Current Behavior
scripts ran fine for the initial 8-12 hours, then bot will only like photos, comments don't "stick". When I go to verify actions on my phone, I can see that the account liked a photo, but no comments are left.

## InstaPy configuration
There's a set of 4 comments, and 24 scripts, each script targets a different hashtag, and interacts with 7 users, 3 images per user, and leaves comments 50% of the time. Each script runs once per day, one new script every hours.

**Comment by Namaslayer** [comment]
Could it be too many comments interactions? Not enough variation in comment options and IG Is catching on and blocking specific comments?!

What are the theories here?

**Comment by Tachenz** [comment]
Set of 4 is too few, 8-12 hours with current bot speed - is way too much. That is instagramm blocking account from commenting more, I am afraid

**Comment by CharlesCCC** [comment]
yes, it seems like you account got temp blocked from follow/comment. you will need slow down.

**Comment by Namaslayer** [comment]
@Tachenz @CharlesCCC Thanks! I'm trying that and it seems to be working! Appreciate the feed back guys

**Comment by timojaask** [comment]
Any update on this? Experiencing the same problem. When I look at what's happening, when InstaPy posts a comment, Instagram shows a banner saying "Cannot post comment". However, I don't get any errors in a log and InstaPy still counts it as a successful comment.
