### ISSUE TITLE
Regarding 'Suspicious activity' workaround

### ISSUE THREAD

**Issue by antonbj3** [InstaPy/InstaPy#1377]
My account has been flagged by security due to multiple login attempts, changing linked email-account when I had forgot my password.
As of now, the suspicious login screen is present independent of location,computer and language settings.
It's been 3 days since this, and I don't except my account to get unflagged anytime soon. And getting  hold of any kind of human support from Instagram is impossible as it can be.

I would, however still like to use InstaPy in a semi-automatic way. But the script gets shut down after about 40-50sec with critical login error, not enough time for me receive enter verification code, as it take 2-3minutes for this to reach my inbox.

Could someone familiar with the code suggest some modification to avoid the error above?

**Comment by ganeshkrishnan1** [comment]
Change your IP
