### ISSUE TITLE
Image not liked: Number of followers exceeds limit

### ISSUE THREAD

**Issue by neugii** [InstaPy/InstaPy#1378]
why is instapy skipping ?

InstaPy(username='xxxxx', password='xxx', use_firefox=True, page_delay=25)\
    .set_switch_language(True)\
    .login()\
    .set_upper_follower_count(limit=300000)\
.set_upper_follower_count(limit = 1)\
.set_user_interact(amount=3, randomize=True, percentage=100)\
    .like_by_tags(['tag1,'tag2', amount=3)\
.set_dont_like([])\
.end()

log: 
INFO []  Image from: 21_tage_stoffwechse
INFO []  Number of Followers: 101
INFO []  --> Image not liked: Number of followers exceeds limit
INFO []  [3/3]

**Comment by professorfabioandrade** [comment]
.set_upper_follower_count(limit=300000)
.set_upper_follower_count(limit = 1)

You are setting the upper twice. So it is using "1".

This is how it should be:
.set_upper_follower_count(limit=300000)
.set_lower_follower_count(limit = 1)

**Comment by neugii** [comment]
a you are right.

i'll check if this ist in the script or a copy/paste error

thx
