### ISSUE TITLE
Only interact with who doesn't follow you?

### ISSUE THREAD

**Issue by professorfabioandrade** [InstaPy/InstaPy#1379]
Hey guys, I just started to use InstaPy yesterday and I would like to know if it is possible to interact only with those who don't follow you. The reason is that I don't need to like and comment pictures of people who already follow me. I couldn't find this option anywhere in the code (I haven't looked deeply yet) and I would be ready to help implementing this feature if you guys agree. Btw, amazing job you are doing here.

**Comment by SDKFJ55LDK8K2** [comment]
The only way at the moment is to put those people in 
"""Like util"""
 completely ignore liking images from certain users
session.set_ignore_users[ 'someuser', 'differentuser' ]

Ps I think that's more then enough. There are definitely other issues that take higher priority at the moment.

**Comment by thejeromelouis** [comment]
I'm looking for a similar feauture. If I use something like:
```
    session.set_user_interact(amount=3, randomize=False, percentage=100, media= None)
    session.set_do_like(enabled=True, percentage=65)
    session.set_do_comment(enabled=False, percentage=0)
    session.set_do_follow(enabled=True, percentage=60)
    session.interact_user_followers (users, amount = 100, randomize = False)
```
Then I want to be sure that Instapy only likes and follows people that **do not follow me**.
