### ISSUE TITLE
I can't run InstaPy... chromedriver error... Could you help me, please?

### ISSUE THREAD

**Issue by samille** [InstaPy/InstaPy#1380]
I don't know exactly whats going on... I installed all the packages it said was necessary, but when I try to run the GUI, I receive this message:
"Error: (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.13.0-32-generic x86_64)"

I've already uninstalled and re-installed the latest version of chromedriver, put in the assets folder etc.
Anyone could help me to fix it? 

Thank you very much :)

**Comment by uluQulu** [comment]
hi @samille 
can you provide the full traceback error?

**Comment by samille** [comment]
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    session = InstaPy(username='******', password='*******')
  File "/home/samille/instapy/instapy.py", line 142, in __init__
    self.set_selenium_local_session()
  File "/home/samille/instapy/instapy.py", line 230, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

____________________________________________________________
I tried to change the chromedriver from the folder /assets to the same as quickstart.py file, to make a test, but nothing happened.

I also tried to run with IDLE3 but didn't work too.

using cached selenium-3.9.0-py2.py3-none-any.whl

**Comment by uluQulu** [comment]
@samille 
what about Chrome browser version?

**Comment by ganeshkrishnan1** [comment]
chrome driver is not in path. Unfortunately chrome installation drops it in a folder ( /usr/lib/chromium-browser/chromedriver) which is not usually in PATH

Do this

`sudo cp /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver`

OR

`sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver`

For a good measure check if it has execute permissions else 

`chmod u+x /usr/local/bin/chromedriver`

**Comment by samille** [comment]
@ganeshkrishnan1 I tried but I got this message: 

~$ sudo cp /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver
cp: impossível obter estado de '/usr/lib/chromium-browser/chromedriver': Arquivo ou diretório não encontrado 
samille@muska-Lenovo-G40-80:~$ sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver
ln: falhou ao criar link simbólico '/usr/local/bin/chromedriver': Arquivo existe

Its in portuguese, but it says "file not found" and with the ln says that it's not possible to create the link cos the file exists.
______________________________________________________________________
@uluQulu Google Chrome 64.0.3282.140
____________________________________________________________________
I've updated my chrome version and then, when I tried to run the GUI I received this:
Cookie file not found, creating cookie...

Error: INFO [samillef] Session started - 2018-02-08 21:20:45 Traceback (most recent call last): File "quickstart.py", line 5, in <module> session.login() File "/home/samille/InstaPy-master/instapy/instapy.py", line 264, in login self.bypass_suspicious_attempt): File "/home/samille/InstaPy-master/instapy/login_util.py", line 108, in login_user browser.get('https://www.instagram.com') File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 324, in get self.execute(Command.GET, {'url': url}) File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute self.error_handler.check_response(response) File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.WebDriverException: Message: chrome not reachable (Session info: chrome=64.0.3282.140) (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.13.0-32-generic x86_64)
InstaPy ended Stop

**Comment by uluQulu** [comment]
would you mind downgrading chrome?
also have you not configured proxy by chance

**Comment by bharat0** [comment]
No solution yet?

**Comment by bgottschling** [comment]
I am also having this issue. I am going to follow the trace through the scripts to see where the issue could be.

**Comment by sahalsaad** [comment]
Facing same problem . You can try this to fix the issues.

1. Download the latest chromedriver
2. Give permission
```bash
$ chmod +x chromedriver
$ chmod 755 chromedriver
```
3. If still not working . Try to update your google chrome. In my case I use linux . So I download the `.deb` and install it.
