### ISSUE TITLE
Image not liked because inappropriate

### ISSUE THREAD

**Issue by riccardorighettiphoto** [InstaPy/InstaPy#1384]
Hello,
another issue here.
I have just run the program and many pictures were not liked because of inappropriateness: "sex" whitin a tag of "sexy". It is a little bit weird because I have never setup any tag or word to be excluded from the third-party GUI.

**Comment by CharlesCCC** [comment]
it not really `inappropriate`  as we normal would think, the `inappropriate` from the log just meant it not meet you requirement. 

For example:

if you set you you upper follower limit to 500 and lower limit to 50. Any one's photo that is out of the range will be consider as `inappropriate` in this case. i believe there is similar issue/propoal on how to solve this issue, but nothing has settle yet.

**Comment by riccardorighettiphoto** [comment]
Dear Charles, you probably did not read well.
I have never set any requirements about the tag to be excluded! I only defined the tags to be liked and number of photos. No other options setup there.
So, what requirements you did refer?

Another bug for me. Thank you.

**Comment by yellawood** [comment]
I'm running into this as well and don't see a way to override this behavior. 

`INFO [2018-08-06 23:13:57] [gravychef]  --> Image not liked: b'Inappropriate! ~ contains "sex" in "b\'sextoys\'"'
`

**Comment by ghost** [comment]
I believe this is the message you are inquiring about: 

`INFO [2018-08-06 23:13:57] [accountname]  --> Image not liked: b'Inappropriate! ~ contains "sex" in "b\'sextoys\'"'
`

I added this to my .py script
`session.set_dont_like([])`
