### ISSUE TITLE
Integer division or modulo by zero error

### ISSUE THREAD

**Issue by S1mplyCompl3x** [InstaPy/InstaPy#1385]
## Expected Behavior
Login >Like & Follow > Quit

## Current Behavior
Login>Start liking but encounter this error after 10 minutes:

![error](https://user-images.githubusercontent.com/22415367/36003403-ec0358fc-0cfb-11e8-8c1f-8331c73a5dc0.png)

## Possible Solution (optional)
Prevent total links from going to zero i guess

## InstaPy configuration

```
 session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=True, use_firefox=True)
    session.login()
    
    # settings
    session.set_upper_follower_count(limit=2500)
    session.set_use_clarifai(enabled=False)
    session.set_do_follow(enabled=True, percentage=50)
    
    # actions
    session.like_by_tags(['followforfollow',.......])
```

**Comment by sionking** [comment]
I will add the fix to my PR

**Comment by petersimeth** [comment]
@S1mplyCompl3x had the same issue, check if you have by mistake set the same hashtag twice. In my case that was the probelm.

example: 
`session.like_by_tags(['followforfollow', 'follow4like', 'followforfollow])`

**Comment by S1mplyCompl3x** [comment]
@risaar i checked and all the tags and they are all different but the same problem still happens.

**Comment by wyvers** [comment]
I've recently noticed this similar error as well. I tried to narrow it down to a single tag and I'm still seeing the same error immediately.



> 
> INFO [User]  Session started - 2018-02-10 22:40:49
> WARNING [User]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
> INFO [User]  Logged in successfully!
> INFO [User]  Tag [1/1]
> INFO [User]  --> b'like4like'
> Traceback (most recent call last):
>   File "L4L.py", line 12, in <module>
>     session.like_by_tags(['like4like'], amount=200)
>   File "C:\Users\User\Documents\GitHub\InstaPy\instapy\instapy.py", line 673, in like_by_tags
>     skip_top_posts)
>   File "C:\Users\User\Documents\GitHub\InstaPy\instapy\like_util.py", line 237, in get_links_for_tag
>     new_per_page = ceil(12 * filtered_links / total_links)
> ZeroDivisionError: division by zero

**Comment by uki-uki** [comment]
```
File "/InstaPy-master/instapy/instapy.py", line 673, in like_by_tags
    skip_top_posts)
  File "/InstaPy-master/instapy/like_util.py", line 237, in get_links_for_tag
    new_per_page = ceil(12 * filtered_links / total_links)
ZeroDivisionError: integer division or modulo by zero
```

Same problem here, note that all comments here point to tags of similar kind, 'like4like' 'followforfollow' etc, after I've changed the tags set, it always stop at 'like4like' one , with different tags and in random time, what about the _skip_top_posts_  maybe it is related? 

The following info may help:
https://stackoverflow.com/questions/14578790/python-integer-division-error-modulo-by-zero-but-divisor-0

**Comment by imv7** [comment]
`

# settings

session.set_do_follow(enabled=True, percentage=100, times=2)

session.set_do_like(enabled=True, percentage=100)

session.set_do_comment(enabled=True, percentage=100)
session.set_comments([u'\u1F43E \u1F43E \u1F43E \u1F499', u'\u1F648 \u1F43E \u1F43E']);

# actions

session.like_by_tags(['shitzulovers2'], amount=999)




session.end()


`
Didn't work above

**Comment by imv7** [comment]
Now worked! Hashtag "shitzu" instead of "shitzulovers2" ... seems the first hashtag is greater than permitted.
