### ISSUE TITLE
Is there a way to select language before login ?

### ISSUE THREAD

**Issue by CharlesCCC** [InstaPy/InstaPy#1388]
## Expected Behavior
I'm a Chinese speaker user, I would like to choose instagram.com default language to Chinese before run the program, so I don't get the random "suspicious" verifcation/recaptha during each run 

## Current Behavior
there is no way to choose the default language 

## InstaPy configuration
default configure with follow tags only.

**Comment by uluQulu** [comment]
I think, if you change language, web page elements- e.g. some _class names_, _lang_ flags and possibly _buttons_ would have different chinese names, that's why english is set for portable functionality..

**Comment by CharlesCCC** [comment]
@uluQulu you are correct my friend, I did some research and found out the select element are all hard-coded based off English language. So, if any other language is been selected, it will not find the corresponding element.  The worst case I can think of is to create a dictionary that including all the language for all the login elements. and then we can change the language at login and then after login, it switch back to English. (not sure if this even feasible).

**Comment by uluQulu** [comment]
i also thought about it, logging in then changing lang +
for me, yet, I've not had such an issue, but it would really be helpful if you collect those **language names** (which, I think, _rarely see updates_) for those who also face the same issue...
