### ISSUE TITLE
Fail to import log_uncertain_unfollowed_pool

### ISSUE THREAD

**Issue by DavidMolinari** [InstaPy/InstaPy#1389]
## Expected Behavior
Since last commit, it's trying to import non existing functions from print_log_writer.py on unfollow_utils.py
```python
from .print_log_writer import log_uncertain_unfollowed_pool
from .print_log_writer import log_record_all_unfollowed
``` 
## Current Behavior
```
from .print_log_writer import log_uncertain_unfollowed_pool
ImportError: cannot import name 'log_uncertain_unfollowed_pool'
```
## Possible Solution (optional)
Comments for now
```python
#from .print_log_writer import log_uncertain_unfollowed_pool
#from .print_log_writer import log_record_all_unfollowed
```

**Comment by sionking** [comment]
I added it to the PR by mistake.
Should I PR this fix ?

**Comment by sionking** [comment]
https://github.com/timgrossmann/InstaPy/pull/1390

**Comment by itseasy21** [comment]
+1 to the issue, commenting the two lines fixed for now

**Comment by briandragon** [comment]
+1 for issue. Commenting also fixed

**Comment by sionking** [comment]
There is a PR

**Comment by Moatsem12347** [comment]
+1 for the issue have same

**Comment by DavidMolinari** [comment]
(Reopen) Still people having issues with this

**Comment by ghost** [comment]
Having issues with this also.
