### ISSUE TITLE
these two imports don't work

### ISSUE THREAD

**Issue by smhjamalii** [InstaPy/InstaPy#1392]
https://github.com/timgrossmann/InstaPy/blob/a024ecba18729c00b63ee153f2e301c7fac68f5a/instapy/unfollow_util.py#L12

**Comment by kristojorg** [comment]
same

**Comment by felipewove** [comment]
Same here

to quick fix it, comment these lines on unfollow_util.py: 12, 13, 135, 136 and 140

I'll not create a PR because don't know if those methods was deleted or not implemented (merge conflict)

**Comment by sionking** [comment]
There is a PR to fix it
