### ISSUE TITLE
 cannot import name 'log_uncertain_unfollowed_pool 

### ISSUE THREAD

**Issue by mdavis184** [InstaPy/InstaPy#1399]
C:\Users\User\Downloads\InstaPy-master>python quickstart.py
Traceback (most recent call last):
File "quickstart.py", line 1, in 
from instapy import InstaPy
File "C:\Users\User\Downloads\InstaPy-master\instapy_init_.py", line 2, in 
from .instapy import InstaPy
File "C:\Users\User\Downloads\InstaPy-master\instapy\instapy.py", line 35, in 
from .unfollow_util import get_given_user_followers
File "C:\Users\User\Downloads\InstaPy-master\instapy\unfollow_util.py", line 12, in 
from .print_log_writer import log_uncertain_unfollowed_pool
ImportError: cannot import name 'log_uncertain_unfollowed_pool' from 'instapy.print_log_writer' (C:\Users\User\Downloads\InstaPy-master\instapy\print_log_writer.py)

what do i do?

**Comment by jetwix** [comment]
I have the same problem ..
![qmyf_o4ltx2if0m1snvkwq](https://user-images.githubusercontent.com/33786078/36062665-d7bd5dd4-0e81-11e8-9c54-b51eea9d2d92.png)

**Comment by dennisvandalen** [comment]
See https://github.com/timgrossmann/InstaPy/issues/1389

**Comment by jetwix** [comment]
after that I had it like_image() missing 1 required positional argument: 'logfolder'

**Comment by mdavis184** [comment]
I don't understand what to do

**Comment by jetwix** [comment]
ty brah it works!!

**Comment by urbizupi** [comment]
What's the fix apart from just puting # in front od the two lines?
