### ISSUE TITLE
Add check for follower number

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#14]
#### Would be nice if you could define an upper bound of followers an author of the posts you like should have. The more followers the account, the less likely it is that they will follow you back, so you can simply save that interaction

Could look somewhat like this:
```python
.set_upper_follower_count(1000) # default is INT Max
```

- [x] implement account check for each post
- [x] add check for more than given upper bound

**Comment by 7ruth** [comment]
This would be a great feature to have!

Do you have plans to make a feature for similar upper check but on likes? (for example on liking posts that have below a certain amount of likes...for the same reasons, its more impactful for people that don't have mega accounts). I am brand new to Python and just got to play around with your tool today, its really awesome!

**Comment by timgrossmann** [comment]
@7ruth yes this feature actually is meant to exclude these accounts completely, no liking, no commenting, no following... Accounts with a lot of followers won't do any interaction with your account and that means it'll just cost Instagram interactions which will have no impact on your profile

**Comment by littleswany** [comment]
@timgrossmann I will work on this issue

**Comment by thecolorblue** [comment]
Would it be better to add in generic filtering for any attribute on an account or post?

**Comment by timgrossmann** [comment]
@thecolorblue That's an interesting question. 
What besides the follower count and the following count could be interesting to check?

**Comment by pekapa** [comment]
@timgrossmann I believe the number of likes and comments on the current picture should be used as a filter.

**Comment by timgrossmann** [comment]
@pekapa Well if you'd do that, the filter would be really dependent on the timing... Even a profile with thousands of followers could have a post with only few likes and comments directly after they posted them.

**Comment by littleswany** [comment]
I have submitted a pull request adding this

**Comment by pekapa** [comment]
@timgrossmann that's very right indeed, but one can use that together with the follower count.

**Comment by timgrossmann** [comment]
solved by #91
