### ISSUE TITLE
Not able to find any post if there is no "Top Post" for the tag

### ISSUE THREAD

**Issue by CharlesCCC** [InstaPy/InstaPy#1400]
## Expected Behavior
will still grab the most recent post 
## Current Behavior
error out with can't divide by zero 
## Possible Solution (optional)
if the tag does not have "Top post" it should skip it as usual and then still grab the normal recent post as targets.

**Comment by uluQulu** [comment]
Hey @CharlesCCC 
it seems that this is a new issue,
if there is not any `Top Posts` in the tag page, it's page elements will be different,
just add three more lines to detect it if any...
```python
if not link_elems:   #this tag does not have `Top Posts` or it really is empty..
    main_elem2 = browser.find_element_by_xpath('//main/article/div[1]')
    link_elems = main_elem2.find_elements_by_tag_name('a')
```
I've included it in my scroll approach [here](https://github.com/timgrossmann/InstaPy/issues/1365#issuecomment-364775408)
