### ISSUE TITLE
Limit MAX likes, follows, unfollows, comments per day/hour

### ISSUE THREAD

**Issue by riccardorighettiphoto** [InstaPy/InstaPy#1402]
Hello,
This is not an issues. I have read a couple of PR and suggestions about limiting the max per day/hour of likes, follow/unfollows and so.
Unfortunately I did not understand how to setup (if not implemented) or configure (if already merged from past PR) this feature.
I have read the Readme but did not find anything.

Thank you.

**Comment by Doom666** [comment]
same here, all I found is 
https://github.com/timgrossmann/InstaPy/issues/797
but still not sure if its already implemented, if it requires some modding of the original code or how to use it...
