### ISSUE TITLE
Improved spam filtering for Smart Hashtags

### ISSUE THREAD

**Issue by RayZorJ3lade** [InstaPy/InstaPy#1406]
## Expected Behavior
For the returned set of smart hashtags to be fairly similar to the response from the DP website.

## Current Behavior
Generating a very spammy list of generic, overused terms.

## Possible Solution (optional)
Change Line 425 in instapy/instapy.py from:
data['results'], key=lambda d: d['rank'], reverse=True)
to:
data['results'], key=lambda d: d['absRelevance'], reverse=True)

**Comment by sionking** [comment]
Can it be set to bring same results as Instagram suggestions when searching ?

**Comment by CharlesCCC** [comment]
what is "absRelevance" ? compare to "rank" ?

**Comment by RayZorJ3lade** [comment]
Its one of the fields returned by https://d212rkvo8t62el.cloudfront.net/tag/{} - unsure of the calculation it represents but I did determine that it defines the order of recommend results on the DP site as you reduce the number of results on the slider in increments of 1
