### ISSUE TITLE
TypeError: like_image() takes exactly 5 arguments (4 given)

### ISSUE THREAD

**Issue by anthonyattard** [InstaPy/InstaPy#1408]
I have been stuck on this puzzling issue for hours. When I run quickstart.py I get an error "TypeError: like_image() takes exactly 5 arguments (4 given)"

I have tried everything including updating pip, python2, tried running it in docker (to rule out version issues), and using different Instagram accounts. Mind you these were are done with a fresh clone of the repo.

Any insights on this? Thanks.

**Comment by sq5rix** [comment]
I get similar error with newest code:
TypeError: like_image() missing 1 required positional argument: 'logfolder'

**Comment by FranklinClinton** [comment]
Same happens to me

**Comment by sionking** [comment]
https://github.com/timgrossmann/InstaPy/pull/1395

**Comment by Freddorick** [comment]
Had the same error. There is a simple fix for this:

In the instapy.py file search for the like_image instances and pass an additional argument self.logfolder, for example like this:

like_image(self.browser, user_name, self.blacklist, self.logger, self.logfolder)

**Comment by anthonyattard** [comment]
@Freddorick Thanks so much! That fixed it. This bug needs to be cleared up in the main repo quick.

**Comment by josefhelie** [comment]
That did the trick but I ran into other problems afterwards, tried on or two things but that did not work... The whole log thing seems to be broken :(

**Comment by FranklinClinton** [comment]
@mojoego For Logging problems see https://github.com/timgrossmann/InstaPy/issues/1407

**Comment by urbizupi** [comment]
@Freddorick Thank you so much! If anyone is still experiencing problems of the bat file not wanting to start up after Freddorick's fix check if you added comma's on the line before self.logfolder like this:
(self.browser,
                                                        self.follow_restrict,
                                                        self.username,
                                                        user_name,
                                                        self.blacklist,
                                                        self.logger, <---
                                                        self.logfolder)

**Comment by gitpatrickhub** [comment]
This fix worked for me as well.

**Comment by luigifaticoso** [comment]
Can you please close the issue so we keep the issues list clean? thanks!
