### ISSUE TITLE
Firefox on Raspberry Pi3 without images

### ISSUE THREAD

**Issue by quintendewilde** [InstaPy/InstaPy#1410]
## Expected Behavior
Running the instapy on Raspberry pi3 with geckodriver should show me images.

## Current Behavior
Shows no images, only tags and text. And outlines of where the images should be. 

Is there anybody who can confirm if he or she has been able to create a working and visible instapy run on the raspberry pi 3?

<img width="1065" alt="screen shot 2018-02-11 at 19 40 58" src="https://user-images.githubusercontent.com/6031569/36076939-9178a210-0f63-11e8-961f-aba6eba4cf71.png">

**Comment by uluQulu** [comment]
hi @BLCKPSTV 
you're using firefox and it's image load is disabled by default.

to **allow** images load, find this line in  `instapy.py` :
 `firefox_profile.set_preference('permissions.default.image', 2)`
and simply **comment** it out

**or** replace `2` with `1` (_to allow all images load.._)

> here is an ongoing **conversation** about disabling images, have a [look](https://github.com/timgrossmann/InstaPy/pull/1364#issuecomment-364676231)

**Comment by keusta** [comment]
@BLCKPSTV yes using firefox with no images and raspberry
but i prefer to have a better loading time with reduced bandwith !

**Comment by quintendewilde** [comment]
Works! I needed option 3 :) Thank you
