### ISSUE TITLE
Fix: remove b' from output (safe way)

### ISSUE THREAD

**Issue by uluQulu** [InstaPy/InstaPy#1413]
_This is not a typical issue but I already got a PR there so posted **here**..._
**
It is appearing in **Python 3 only** (Python 2 doesn't have this issue)

> READ UPDATED COMMENT below : for python 2 & 3 portable solution

**

### In output (_at consoles_) I see lots of **b'** in many places, e.g. :
```
Description: b'#pelican #animal #oiseau #france #normandie #montsaintmichel #vol #canon #canon700d #canonphotography #nature #naturelovers #naturephotography #love #amazing'
```
or
```
Image from: b'corinne_genier'
```
## Previous Behavior & Reason
Basically we see `b'some_string'` bcos _we encoded it_ to a utf-8 bytestring and **we encoded bcos** if that string had some unsopported characters by console (e.g. arabian chars) it would result a crash.

But, also, the `b'some_string'` is just a **python** notation of **bytestrings**, **it's not really there**, it only gets printed out in _output_.

**So** we are **safe** to remove it from output by slicing, e.g. for `Description` part... :
```python
logger.info('Description: {}'.format(image_text.encode('utf-8')))
logger.info('Image from: {}'.format(user_name.encode('utf-8')))
```
**will be**
```python
logger.info('Description: {}'.format(str(image_text.encode('utf-8'))[2:-1]))

logger.info('Image from: {}'.format(str(user_name.encode('utf-8'))[2:-1]))
```
## Current Behavior
Now it prints out as :
```
Description: #pelican #animal #oiseau #france #normandie #montsaintmichel #vol #canon #canon700d #canonphotography #nature #naturelovers #naturephotography #love #amazing

Image from: corinne_genier
```
a way more clear, ain't?
## Offered Solution
**Adding**,   `str(` to start **and**   `)[2:-1]`  to the end of **every** (or needed) lines of strings encoded **to** 'utf-8'
`str(some_string.encode('utf-8'))[2:-1]`

**Comment by uluQulu** [comment]
To provide **compatibility between** Python 2 and 3 I added **a class variable** `self.bye_b` to define slices

**if** Python version starts with **2**, it **will not** slice (cos it doesn't show `b''` in output)..
**if** Python version starts with **3**, it **will slice** and remove `b''` bytestring stamps..

**added** this to InstaPy class:
```python
import platform

if platform.python_version().startswith('3'):
    self.bye_b = slice(2, -1)   #equialent to 'somewords'[2:-1]
else:
    self.bye_b = slice(None, None)   #equialent to 'somewords'[:]
```
also lines with `sometext.encode('utf-8')` becomes `str(sometext.encode('utf-8'))`
then I add `self.bye_b` to slice and remove annoying `b''` letters:

so inside `instapy.py` I just used `self.bye_b`
e.g.:
```python
self.logger.info('--> {}'.format(str(location.encode('utf-8'))[self.bye_b]))
```

then in other locations I passed `self.bye_b` to them in parameters
e.g. to use in `check_link()` function:
when calling `check_link()` from `InstaPy()` class,
```python
check_link(self.browser,
                                   link,
                                   self.dont_like,
                                   self.ignore_if_contains,
                                   self.ignore_users,
                                   self.username,
                                   self.like_by_followers_upper_limit,
                                   self.like_by_followers_lower_limit,
                                   self.logger,
                                   self.bye_b)   #pass parameter
```
then to use inside `check_link()` function,
```
def check_link(browser,
               link,
               dont_like,
               ignore_if_contains,
               ignore_users,
               username,
               like_by_followers_upper_limit,
               like_by_followers_lower_limit,
               logger,
               bye_b):   #new default parameter

#for example, once to output Description
logger.info('Description: {}'.format(str(image_text.encode('utf-8'))[bye_b]))
```

I've checked, there are 20 places we used `.encode('utf-8') and they are all text strings

After applying this to **all places** (only `instapy.py`, `like_util.py`, comment_util.py` and unfollow_util.py`  files has this encoding scenarios), it is working flawlessly with no any `b''` bytestring stamps in console output & log files

**I've tested** on Python 3 in my **Windows locally**, and for Python 2 and 3 **on Linux at** pythonanywhere.com servers

What do you think about this? @timgrossmann

**Comment by alex-wahl** [comment]
As I can see, in the current version it still doesn't work.

**Comment by uluQulu** [comment]
Hi @studyentwickler 
What does not work?

**Comment by alex-wahl** [comment]
Hi @uluQulu,

it is still a letter "b" in the command  line  and you can see also an error with encoding "utf8"
<img width="569" alt="2018-10-14 23 52 24" src="https://user-images.githubusercontent.com/43057040/46922646-77080780-d00c-11e8-96f1-259d7b9c618e.png">

**Comment by nidhipathak** [comment]
I am facing the same issue, just checking, any solution yet?
