### ISSUE TITLE
Feature Request: Interact with recent likers

### ISSUE THREAD

**Issue by HermanoCrespo** [InstaPy/InstaPy#1415]
A very effective way to gain followers is by interacting with people in your niche.

I used to to the follow/unfollow game by hand with accounts, that recently liked the most recent post of a target account within my niche.

Example

Niche:
Nature

Account:
National Geographic

Requested action:
interact with users content that recently liked natgeo's post. 
follow a percentage as well.

That works wonders to growth, I only stopped because it was a mind-numbing activity. Would be great to automate it, I don't think I'd use tags anymore after an implementation like that.

**Comment by sionking** [comment]
What is the difference NG followers and likers ?

**Comment by HermanoCrespo** [comment]
Depends. If it is specific and works on recently active followers (last hours), then yes, it could be effective and work but if it only works on all followers I have my reservations. Big accounts have "dead" users there.

Is there a function to interact with someones likers? I must have missed that that might be what I was after.

Cheers

**Comment by clevebounce** [comment]
I think this make perfect sense 👍

**Comment by sionking** [comment]
We can check the followers activity, last image post date etc...

**Comment by SDKFJ55LDK8K2** [comment]
@sionking Hmm didn't knew we can check last image they posted etc. I'm clearly missing out on some of the features added lately. 

Anyway this doesn't show anything about how active users are when it comes down to liking etc. 35% of users just post but never really interact with other users by liking or commenting on their stuff so ... I guess the feature interacting with likes could be interesting and a nice added feature for the bot.

**Comment by SDKFJ55LDK8K2** [comment]
Also ... For those who have an engaging following and sometimes come in the discovery page of other users, it could be nice to be able to interact with people who liked your latest post but are not following you. 

When you come in the discovery page a good 20-50% of the likes on your post come from people who don't follow you and would easily follow if you interact with them.
