### ISSUE TITLE
Get statistics data from LOG file

### ISSUE THREAD

**Issue by riccardorighettiphoto** [InstaPy/InstaPy#1417]
Hello,
this is not an issue, but a post to open a conversation on how to implement my following thoughts.
The LOG file has (potentially) really important and valuable information which could be gather for statistics purposes (number of likes, comments, followings, tags liked/commented, user or post liked/commented, followers of users liked...).
I have tried to put the log data in a "DB structured-like" style using Excel, but the sequence of information is not always predefined and fixed, for instance: if I put in place a max/min limit, the log returns less rows for picture analyzed.

Do someone have any idea on the matter?
Thank you. Bye.

**Comment by sionking** [comment]
Don't use this log parsing for DB 
Add your own.
I use pickle for over 3 months. with not issues.

**Comment by riccardorighettiphoto** [comment]
Sorry, but I did not understand you at all. Please consider I am completely newbie, so I don't know what is pickle, how use it or how/where "add my own", as you wrote.

**Comment by riccardorighettiphoto** [comment]
For whom are interested in, I am working on a VBA project inside an Excel file to manage the log file and create a ";" separated text for statistics purposes in Excel or Access.
It is in a very alpha version and it is working pretty well so far, but if anyone may help me (with some tests) or contribute to a more customized fashion style file is really appreciated.
Bye.

**Comment by tomburgerch** [comment]
Also interested in this. Please let me know once there's an update!
