### ISSUE TITLE
Feature: Spintext comments

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#1419]
It is very easy to implement some more complicated comments.

Some spinning text for regular words like:
hi/hello/hey this is a lovely/nice/great picture/image
1. hi this is a lovely image
2. hello this is a nice picture 
....

?

**Comment by SDKFJ55LDK8K2** [comment]
Advice: 
In general people are not stupid... It's ridiculously easy to filter out bot accounts who comment, and a one size fits all comment doesn't exist. My recommendation would be... Do the liking and following partially automated but ... If you want to connect do the research and commenting manually. :)

**Comment by uluQulu** [comment]
_Well, it is a nice feature to exist, and I do like the idea considering content will be precious_
But I think, a successful commenting strategy is using unrepetead patterns which can hardly generated by a computer.
e.g. personally, I do target mostly `landscape photography` and some of my comments are
```
thank you're for sharing your miraculous pics and experience with us!!!!
```
and whilst some are shorter
```
you have outdone yourself!
```
even more shorter
```
top notch!
```
But **well**, it will be very **valuable feature** for those who do not have a good list of comments and even once **tried hard** it can generate some remarkably stylish comments!
It would be very nice to implement it, can you do it, @sionking ?

**Comment by sionking** [comment]
@uluQulu sure we can trty this : 
spinrewriter 

I will let you know

**Comment by sionking** [comment]
I set comments to 5% only... with a variety of around 60 different comments.
I would have like to spin an emoji concated to a word  so it will get instead of 1 line a 15 different one.
