### ISSUE TITLE
Ignore accounts I have followed myself

### ISSUE THREAD

**Issue by raffg** [InstaPy/InstaPy#142]
Ignore all accounts I followed manually. Only automatically unfollow accounts which were followed by the bot.

**Comment by AlainPilon** [comment]
So obvious I dont understand why we did not think about it earlier!

**Comment by timgrossmann** [comment]
I think it would be also really nice if you could unfollow LIFO instead of only FIFO... like #74 already suggested.
That way we would not instantly unfollow the just followed accounts

**Comment by AlainPilon** [comment]
@timgrossmann I was planing to extract that feature tonight, if time allows.

**Comment by timgrossmann** [comment]
@vlntdds Would be awesome!

**Comment by timgrossmann** [comment]
#349

**Comment by ghost** [comment]
How do I activate this feature?
