### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by alessiomtt** [InstaPy/InstaPy#1421]
Hi, I have re-downloaded all the project and follow the installation guide
Like 2 months ago I was able to run Instapy without any problems but now I'm in trouble

I attach the screen of the errors and hope someone can help me
thank you so much
![cattura](https://user-images.githubusercontent.com/34484439/36147918-66f2b35c-10ba-11e8-82b1-def508b55d84.PNG)

**Comment by jgoranson4** [comment]
have you tried:
pip install pyvirtualdisplay
 or:
sudo pip install pyvirtualdisplay

**Comment by alessiomtt** [comment]
Yes, it says Requirement already satisfied

**Comment by FranklinClinton** [comment]
If you install it with pip, make sure you are using the command "python quickstart.py" If you would use python3, then you would have to install pyvirtualdisplay with the command pip3.
