### ISSUE TITLE
NameError: name 'session' is not defined ( For Digital Ocean)

### ISSUE THREAD

**Issue by jgoranson4** [InstaPy/InstaPy#1422]
I think I am getting this error because my chromedriver is not in the assets folder. But having problems moving it on ubunto (digital ocean). Hoping for some help to address this issue. I have tried everything outlined in all of the related issues.

<img width="428" alt="screen shot 2018-02-13 at 12 08 59 pm" src="https://user-images.githubusercontent.com/36408997/36149214-cf3d10be-10b6-11e8-9b45-01d6f538d805.png">

**Comment by DavidMolinari** [comment]
You can't move chromedriver in assets folder ?
```bash
mv ~/InstaPy/chromedriver ~/InstaPy/assets/chromedriver
```
If it's the case you can fix it temporarily by changing the path on settings.py
```python
    browser_location = "./chromedriver"
```

**Comment by jgoranson4** [comment]
I was able to move it, but still getting the same error.

Here is my start up script:

    insta_username = '****'
    insta_password = '*****'
    try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=True,
                      multi_logs=True)
    session.login()

    # settings
    session.set_upper_follower_count(limit=2500)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.like_by_tags(['natgeo'], amount=10)

    finally:
    # end the bot session
    session.end()

**Comment by riccardorighettiphoto** [comment]
Did you fix it?
I am experiencing the same issue on a CentOs VPS. I tried anything...
