### ISSUE TITLE
import error after new updated

### ISSUE THREAD

**Issue by Radzam** [InstaPy/InstaPy#1423]
It worked great until I did a git pull and then started getting this error. I also did a fresh install and the same error happens. Anyone know why?

```
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/code/instagram/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/code/instagram/instapy/instapy.py", line 35, in <module>
    from .unfollow_util import get_given_user_followers
  File "/code/instagram/instapy/unfollow_util.py", line 12, in <module>
    from .print_log_writer import log_uncertain_unfollowed_pool
ImportError: cannot import name 'log_uncertain_unfollowed_pool'
 ✘ macbook@macbook  /code/instagram   master ● 
```

**Comment by DavidMolinari** [comment]
You can try to comment those two lines in instapy/unfollow_util.py ( line 12 and 13 )
```python
#from .print_log_writer import log_uncertain_unfollowed_pool
#from .print_log_writer import log_record_all_unfollowed
``` 


See #1389

**Comment by uluQulu** [comment]
hi Radzam,
it is importing functions which does not exist (_latest PR was incomplete..._)
have a look at https://github.com/timgrossmann/InstaPy/issues/1407#issuecomment-364749937
you will add some lines in there to the end of `print_log_writer.py` file, i guess, it will be included in the next PR
