### ISSUE TITLE
Unusual Authorisation detected

### ISSUE THREAD

**Issue by vladislav-vasilenko** [InstaPy/InstaPy#1424]
## Expected Behavior

I would like to have imitation input User and Pass like it's doing user (with random pause 0.5-1.9 sec after typewriting each symbol), and possibility randomly change pauses coefficient in Config file.

## Current Behavior

Currently instagram detects Unsual login Attempts:

"We Detected An Unusual Login Attempt"
<img width="459" alt="screen shot 2018-02-13 at 20 31 07" src="https://user-images.githubusercontent.com/1023797/36154954-9c0e620c-1105-11e8-9f4e-66d62cb54afe.png">

**Comment by balakedev** [comment]
Hey, what do you mean by this? Should be fine after the account's email verifies the location, I've run into this a bit.

**Comment by smackeveryone** [comment]
Hello I just got an iPhone 8+ today switching from an iPhone 6 and Instagram is not letting me log in. On any device, on any network or VPN. It says it needs a verification code, I press send the verification code to my phone number which is connected to the account and it doesn’t send or I am not getting it. Very infuriarating I have been dealing with this for the past 8 hours.
