### ISSUE TITLE
Desktop Doesn't follow - possible desktop ban?

### ISSUE THREAD

**Issue by vibhuarul** [InstaPy/InstaPy#1425]
## Expected Behavior
Instapy 'clicks' follow button, and follow is requested to account.

## Current Behavior
Instapy clicks follow button, loading spinner appears for a second, and then button reverts back to 'Follow' instead of Following or Requested. This happens when I manually try to follow people, across other browsers (chrome, safari, mobile safari). On the instagram app, I am able to follow people.

## InstaPy configuration
Using the follow_by_list

**Comment by sionking** [comment]
suspicious activity

**Comment by thealgor** [comment]
@vibhuarul  how many people are you following per day and per hour?
