### ISSUE TITLE
Indentation Error

### ISSUE THREAD

**Issue by b13kjack** [InstaPy/InstaPy#1427]
Everything worked fine until recent update. I am getting indentation related errors:

File "quickstart3.py", line 12
    session = InstaPy(username=insta_username,
                                                                           ^
IndentationError: unindent does not match any outer indentation level

Is there anything I can do to fix it? Arrow is pointing at the end of the line.

**Comment by FranklinClinton** [comment]
Please post your full quickstart3.py file
