### ISSUE TITLE
Indent error on InstaPY

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1428]
Haven't been able to run InstaPY... Had success on a separate computer with few issues, this is a different computer and I definitely did everything the same.

![image](https://user-images.githubusercontent.com/36463914/36189145-9b4b3a16-111e-11e8-83c3-fdfabc1fcfe3.png)

My quickstart.py:

```
from instapy import InstaPy
import os
session = InstaPy(username='x', password='x')
session.login()
session.set_ignore_users(['x' ])
session.friend_list = ['x' ]
session.set_do_comment(enabled=True, percentage=25)
session.set_comments(['x' ])
session.set_do_follow(enabled=True, percentage=25, times=2)
session.set_upper_follower_count(limit = 1000)
session.like_by_tags(['x'], amount=50)

session.end()
```

My __init__.py:
```
from .settings import Settings
from .instapy import InstaPy
```
My line 20 on instapy.py:
```
if os.name != 'nt':
    #from .clarifai_util import check_image
from .settings import Settings
from .comment_util import comment_image
from .like_util import check_link
```

Any help appreciated!

**Comment by FranklinClinton** [comment]
change line 20 in instapy/instapy.py from  `#from .clarifai_util import check_image` to  `from .clarifai_util import check_image`
If this doesnt work try removing the whole if-block:
```
if os.name != 'nt':
    #from .clarifai_util import check_image
```

**Comment by ghost** [comment]
Removing it worked.. Thanks!
