### ISSUE TITLE
Raspberry Installation, Chrome

### ISSUE THREAD

**Issue by gabriansa** [InstaPy/InstaPy#1430]
Hello, I'm trying to install InstaPy to my Raspberry Pi 3. I'm following the instructions but I got stucked in the chrome section.

![screen shot 2018-02-14 at 11 07 38 am](https://user-images.githubusercontent.com/35652944/36198594-4b84cfa2-1177-11e8-9227-92a6baa8c235.png)

Everything is okay till step 2. At 3. I get some errors. Here they are:

![whatsapp image 2018-02-12 at 20 15 55](https://user-images.githubusercontent.com/35652944/36198739-aeeabf84-1177-11e8-9f9d-d4a7be522d47.jpeg)

I tried with: sudo apt-get update, but nothing changes.

Thanks!!

**Comment by Lazydrippa** [comment]
Try this: 
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553 && apt-get update`

**Comment by gabriansa** [comment]
That's what i get

root@raspberrypi:/home/pi# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553 && apt-get update
Executing: /tmp/apt-key-gpghome.5WG6etMtUf/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.5WG6etMtUf/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr

**Comment by gabriansa** [comment]
I've also tried to install Firefox, but also here i get the same error after sudo apt-get update



pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://mirrordirector.raspbian.org/raspbian stretch InRelease
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [63.0 kB]
Ign:2 http://security.debian.org/debian-security stretch/updates InRelease
Hit:3 http://archive.raspberrypi.org/debian stretch InRelease
Get:4 http://q4os.org/qextrepo q4os-rpi-firefox-cn InRelease [2,481 B]
Fetched 65.4 kB in 6s (10.7 kB/s)                                              
Reading package lists... Done
W: GPG error: http://security.debian.org/debian-security stretch/updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9D6D8F6BC857C906 NO_PUBKEY 8B48AD6246925553
W: The repository 'http://security.debian.org/debian-security stretch/updates InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
pi@raspberrypi:~ $

**Comment by Lazydrippa** [comment]
Try running this then run the previous command again

`sudo apt-get install dirmngr --install-recommends`

If that doesn't work you can attempt to manually install it via the deb file,
to do this you'll need to download a copy of the file from a mirror listed [here](https://packages.debian.org/stretch/amd64/dirmngr/download)

once you wget the file from a mirror just install it using dpkg -I [deb file]

you should then be able to install the key for the security.debian.org repository and apt-get should run as normal

**Comment by gabriansa** [comment]
from: sudo apt-get install dirmngr --install-recommends
that's what i get, seems to have no problems

pi@raspberrypi:~ $ sudo apt-get install dirmngr --install-recommends
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  pinentry-gnome3 tor
The following NEW packages will be installed:
  dirmngr
0 upgraded, 1 newly installed, 0 to remove and 32 not upgraded.
Need to get 546 kB of archives.
After this operation, 963 kB of additional disk space will be used.
Get:1 http://mirror.transip.net/raspbian/raspbian stretch/main armhf dirmngr armhf 2.1.18-8~deb9u1 [546 kB]
Fetched 546 kB in 1s (420 kB/s)  
Selecting previously unselected package dirmngr.
(Reading database ... 123881 files and directories currently installed.)
Preparing to unpack .../dirmngr_2.1.18-8~deb9u1_armhf.deb ...
Unpacking dirmngr (2.1.18-8~deb9u1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up dirmngr (2.1.18-8~deb9u1) ...

**Comment by Lazydrippa** [comment]
The package had been successfully installed, you should now be able to execute the following command,
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553 && apt-get update`

**Comment by gabriansa** [comment]
```
pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# echo "deb http://security.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list
root@raspberrypi:/home/pi# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553 && apt-get update
Executing: /tmp/apt-key-gpghome.fx5JBtTcA1/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553
gpg: key 8B48AD6246925553: public key "Debian Archive Automatic Signing Key (7.0/wheezy) <ftpmaster@debian.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Hit:1 http://q4os.org/qextrepo q4os-rpi-firefox-cn InRelease
Hit:2 http://mirrordirector.raspbian.org/raspbian stretch InRelease
Hit:3 http://archive.raspberrypi.org/debian stretch InRelease        
Get:4 http://security.debian.org/debian-security stretch/updates InRelease [63.0 kB]
Fetched 63.0 kB in 11s (5,692 B/s) 
Reading package lists... Done
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:8
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:8
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:8
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:8
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:9
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:9
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:9
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:9
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:6
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:7
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:8
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:8
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:8
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:8
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:9
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:9
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:9
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:9
root@raspberrypi:/home/pi# 

```

**Comment by Lazydrippa** [comment]
Alright looks like theres a few duplicates in your sources.list, please post the output of sources.list

`cat /etc/apt/sources.list`

**Comment by gabriansa** [comment]
Here it is:

root@raspberrypi:/home/pi# cat /etc/apt/sources.list
deb http://mirrordirector.raspbian.org/raspbian/ stretch main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspbian.org/raspbian/ stretch main contrib non-free rpi
deb http://security.debian.org/debian-security stretch/updates main
deb http://security.debian.org/debian-security stretch/updates main
deb http://security.debian.org/debian-security stretch/updates main
deb http://security.debian.org/debian-security stretch/updates main
deb http://security.debian.org/debian-security stretch/updates main
deb http://security.debian.org/debian-security stretch/updates main
root@raspberrypi:/home/pi#

**Comment by gabriansa** [comment]
```
root@raspberrypi:/home/pi# cat /etc/apt/sources.list
deb http://mirrordirector.raspbian.org/raspbian/ stretch main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspbian.org/raspbian/ stretch main contrib non-free rpi
deb http://security.debian.org/debian-security stretch/updates main
deb http://security.debian.org/debian-security stretch/updates main
deb http://security.debian.org/debian-security stretch/updates main
deb http://security.debian.org/debian-security stretch/updates main
deb http://security.debian.org/debian-security stretch/updates main
deb http://security.debian.org/debian-security stretch/updates main
root@raspberrypi:/home/pi# 

```

**Comment by Lazydrippa** [comment]
here's the issue, 
`root@raspberrypi:/home/pi# cat /etc/apt/sources.list
deb http://mirrordirector.raspbian.org/raspbian/ stretch main contrib non-free rpi
#deb-src http://archive.raspbian.org/raspbian/ stretch main contrib non-free rpi
deb http://security.debian.org/debian-security stretch/updates main
deb http://security.debian.org/debian-security stretch/updates main<----
deb http://security.debian.org/debian-security stretch/updates main<----
deb http://security.debian.org/debian-security stretch/updates main<----
deb http://security.debian.org/debian-security stretch/updates main<----
deb http://security.debian.org/debian-security stretch/updates main<----
root@raspberrypi:/home/pi# `

if you look you have the same repository printed multiple times

open up /etc/apt/sources.list with nano
`nano /etc/apt/sources.list`

remove all lines I have placed an arrow at the end of with CTRL+K
then save the file with CTRL+X and enter y when prompted

**Comment by gabriansa** [comment]
perfect! I did that

**Comment by Lazydrippa** [comment]
Is everything working perfectly now? :)

**Comment by gabriansa** [comment]
should I just go for:
`apt-get update`

or
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553 && apt-get update`

**Comment by Lazydrippa** [comment]
You want to go for the second command, it will add the key and run apt-get update for you.

**Comment by gabriansa** [comment]
I get a similar error:

```
pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# echo "deb http://security.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list
root@raspberrypi:/home/pi# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553 && apt-get update
Executing: /tmp/apt-key-gpghome.aEuA3EQfE6/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553
gpg: key 8B48AD6246925553: "Debian Archive Automatic Signing Key (7.0/wheezy) <ftpmaster@debian.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Hit:1 http://q4os.org/qextrepo q4os-rpi-firefox-cn InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Hit:3 http://mirrordirector.raspbian.org/raspbian stretch InRelease
Hit:4 http://security.debian.org/debian-security stretch/updates InRelease     
Reading package lists... Done                                                  
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:5
root@raspberrypi:/home/pi# 
```

**Comment by Lazydrippa** [comment]
looks like, most of the issues have been resolved, let's fix those last ones, run
`cat /etc/apt/sources.list`
once more and paste the outputs here for me.

Just looks like one more duplicate that is causing this.

**Comment by gabriansa** [comment]
I already checked and yes there was still something duplicated. I ran thecommand: `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553 && apt-get update` again and that's what i get. I think it worked
```
root@raspberrypi:/home/pi# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553 && apt-get update
Executing: /tmp/apt-key-gpghome.YK1EnCzCh6/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553
gpg: key 8B48AD6246925553: "Debian Archive Automatic Signing Key (7.0/wheezy) <ftpmaster@debian.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Hit:1 http://mirrordirector.raspbian.org/raspbian stretch InRelease
Hit:2 http://security.debian.org/debian-security stretch/updates InRelease                               
Hit:3 http://archive.raspberrypi.org/debian stretch InRelease                                            
Hit:4 http://q4os.org/qextrepo q4os-rpi-firefox-cn InRelease         
Reading package lists... Done             
root@raspberrypi:/home/pi# 


```

**Comment by Lazydrippa** [comment]
Yeah, that looks about right, you should be able to install chrome without issue now, Hope this helped!

**Comment by gabriansa** [comment]
Yes! installed! 

`root@raspberrypi:/home/pi# apt-get install chromium-browser
Reading package lists... Done
Building dependency tree       
Reading state information... Done
chromium-browser is already the newest version (60.0.3112.89-0ubuntu0.14.04.1.1010+1).
0 upgraded, 0 newly installed, 0 to remove and 32 not upgraded.
`

Thanks!!

**Comment by Lazydrippa** [comment]
No problem, If you have any more questions feel free to message me or even DM me on insta @lazydrippin 

I've been getting 100+ followers a day since I started using this script 3 days ago!!

**Comment by gabriansa** [comment]
Another issue here :)

```
root@raspberrypi:/home/pi# apt-get install chromedriver
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  chromium chromium-driver fonts-liberation libminizip1 libre2-3
Suggested packages:
  chromium-l10n chromium-shell chromium-widevine
The following NEW packages will be installed:
  chromedriver chromium chromium-driver fonts-liberation libminizip1 libre2-3
0 upgraded, 6 newly installed, 0 to remove and 32 not upgraded.
Need to get 42.3 MB of archives.
After this operation, 119 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://mirror.transip.net/raspbian/raspbian stretch/main armhf libminizip1 armhf 1.1-8 [18.3 kB]
Get:2 http://mirror.transip.net/raspbian/raspbian stretch/main armhf libre2-3 armhf 20170101+dfsg-1 [149 kB]
Get:3 http://mirror.transip.net/raspbian/raspbian stretch/main armhf fonts-liberation all 1:1.07.4-2 [827 kB]
Get:4 http://security.debian.org/debian-security stretch/updates/main armhf chromium armhf 63.0.3239.84-1~deb9u1 [38.3 MB]
Get:5 http://security.debian.org/debian-security stretch/updates/main armhf chromium-driver armhf 63.0.3239.84-1~deb9u1 [2,890 kB]
Get:6 http://security.debian.org/debian-security stretch/updates/main armhf chromedriver armhf 63.0.3239.84-1~deb9u1 [124 kB]    
Fetched 42.3 MB in 1min 13s (578 kB/s)                                                                                           
Selecting previously unselected package libminizip1:armhf.
(Reading database ... 123900 files and directories currently installed.)
Preparing to unpack .../0-libminizip1_1.1-8_armhf.deb ...
Unpacking libminizip1:armhf (1.1-8) ...
Selecting previously unselected package libre2-3:armhf.
Preparing to unpack .../1-libre2-3_20170101+dfsg-1_armhf.deb ...
Unpacking libre2-3:armhf (20170101+dfsg-1) ...
Selecting previously unselected package chromium.
Preparing to unpack .../2-chromium_63.0.3239.84-1~deb9u1_armhf.deb ...
Unpacking chromium (63.0.3239.84-1~deb9u1) ...
Selecting previously unselected package chromium-driver.
Preparing to unpack .../3-chromium-driver_63.0.3239.84-1~deb9u1_armhf.deb ...
Unpacking chromium-driver (63.0.3239.84-1~deb9u1) ...
Selecting previously unselected package chromedriver.
Preparing to unpack .../4-chromedriver_63.0.3239.84-1~deb9u1_armhf.deb ...
Unpacking chromedriver (63.0.3239.84-1~deb9u1) ...
Selecting previously unselected package fonts-liberation.
Preparing to unpack .../5-fonts-liberation_1%3a1.07.4-2_all.deb ...
Unpacking fonts-liberation (1:1.07.4-2) ...
Setting up libminizip1:armhf (1.1-8) ...
Processing triggers for mime-support (3.60) ...
Processing triggers for desktop-file-utils (0.23-1) ...
Setting up libre2-3:armhf (20170101+dfsg-1) ...
Setting up fonts-liberation (1:1.07.4-2) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Setting up chromium (63.0.3239.84-1~deb9u1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Processing triggers for gnome-menus (3.13.3-9) ...
Processing triggers for hicolor-icon-theme (0.15-1) ...
Processing triggers for fontconfig (2.11.0-6.7) ...
Setting up chromium-driver (63.0.3239.84-1~deb9u1) ...
Setting up chromedriver (63.0.3239.84-1~deb9u1) ...
root@raspberrypi:/home/pi# mv /usr/bin/chromedriver /path/to/InstaPy/assets/chromedriver
mv: cannot move '/usr/bin/chromedriver' to '/path/to/InstaPy/assets/chromedriver': No such file or directory
root@raspberrypi:/home/pi# 

```

**Comment by Lazydrippa** [comment]
This article by the author of InstaPy should help you,

https://eltechs.com/run-google-chrome-on-raspberry-pi/

**Comment by Lazydrippa** [comment]
It might be called chromium-driver, since the app it installed had that name, just check and see if that’s it, I’m not sure though because I haven’t setup on an rpi before
