### ISSUE TITLE
session.unfollow_users: 0 people to unfollow

### ISSUE THREAD

**Issue by FranklinClinton** [InstaPy/InstaPy#1432]
## Expected Behavior
session.unfollow_users(amount=300) will cause the script to unfollow 300 users.
## Current Behavior
session.unfollow_users(amount=300) does the following:
```
INFO [***]  Number of people followed automatically remaining: 591
WARNING [***]  There are 0 people to unfollow
```
## InstaPy configuration
Running headless on Ubuntu 16.04 server. Python 3.5 with chromedriver.
Full Script:
```
from instapy import InstaPy

insta_username = '***'
insta_password = '***'

# set headless_browser=True if you want to run InstaPy on a server
session = InstaPy(username=insta_username,
                      password=insta_password,
                      nogui=True)
session.login()

    # actions
session.unfollow_users(amount=300)
    # end the bot session
session.end()

```

**Comment by lucanello** [comment]
There is a general problem with unfollowing users since Instagram seems to have its Markup updated:
```
ERROR - unfollow loop error Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), 'Follow')]"}
  (Session info: headless chrome=64.0.3282.167)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 3.16.0-5-amd64 x86_64)

INFO - --> Total people unfollowed : 0 
```
It works when I don't switch language with: `session.switch_language = True`
This can lead to another problem when switching language is important so Instagram doesn't think it's a suspicious login attempt.

**Comment by FranklinClinton** [comment]
As far as I know I don't use session.switch_language = True

**Comment by FranklinClinton** [comment]
Solved it. It was caused due to a password change. **This should be added to the readme.md!** If you change your password, you have to delete the cookie file in die log directory!
Everything is working fine now.
