### ISSUE TITLE
log_uncertain_unfollowed_pool( ) breaks unfollow_util.py

### ISSUE THREAD

**Issue by jeremycjang** [InstaPy/InstaPy#1436]
I just pulled the latest commits into my local repo and added the missing ```print_log_writer.py``` code referenced in #1407 and attempted to run my follow/unfollow program today. 

Though I am still unclear of the purpose of the new ```log_uncertain_unfollowed_pool()``` function, it causes the unfollow action to end very prematurely with the following message:

```
INFO [bboygermy]  --> Ongoing Unfollow From InstaPy 33, now unfollowing: aissaadz
ERROR [bboygermy]  unfollow loop error log_uncertain_unfollowed_pool() takes exactly 4 arguments (3 given)
```

It may also have affected the ```follow_user_followers``` function, which also ended prematurely. I believe more important changes may be missing from the latest commits.

**Comment by uluQulu** [comment]
hi @jeremyccheung 
I've seen main repo and it seems that
```python
log_uncertain_unfollowed_pool(username, person, logger)
```
and
```python
log_record_all_unfollowed(username, person, logger)
```
is missing `logfolder` argument

find them both in `unfollow_util.py` and that missing arg to the end of args
```python
log_uncertain_unfollowed_pool(username, person, logger, logfolder)
```
and
```python
log_record_all_unfollowed(username, person, logger, logfolder)
```

**Comment by jeremycjang** [comment]
Hi @uluQulu 

Thank you for that catch; I will make those additions to the code and test the updated program tomorrow!

**Comment by Venni27** [comment]
Perfect. Now working again! :-)

**Comment by jeremycjang** [comment]
Confirmed on my end too that this fixed the program. Thank you @uluQulu !

**Comment by datteba** [comment]
@timgrossmann I have the same error. Could you add @uluQulu corrections to the main project?
