### ISSUE TITLE
instapy scrolling through images but not liking them

### ISSUE THREAD

**Issue by jukedd** [InstaPy/InstaPy#1437]
## Expected Behavior
to like and comment on images
## Current Behavior
scrolls through them quickly and likes and comments on none
## InstaPy configuration
instapy gui windows

**Comment by blesson3** [comment]
@jukedd does the output to the terminal suggest it's liking and commenting, but the website doesn't reflect those clicks/actions?

**Comment by jukedd** [comment]
@blesson3 no it says image not liked: none

**Comment by jzos** [comment]
@blesson3 I'm having an issue with one of my accounts to where in the log it's stating that it liked the image, but not showing up in the posts that I've liked in my instagram app. Any ideas?
