### ISSUE TITLE
log_followed_pool is not defined

### ISSUE THREAD

**Issue by supm3n** [InstaPy/InstaPy#1443]
Getting this error message, i tryed to search it but didnt find a clue on how to fix.

![immagine](https://user-images.githubusercontent.com/36124577/36340211-838656f6-13d8-11e8-9fc7-426ccdaff5bf.png)

**Comment by uluQulu** [comment]
do you have
```python
from .print_log_writer import log_followed_pool
```
at top of `unfollow_util.py`?

**Comment by supm3n** [comment]
Theres a # infront of that line, removed it, now its working, Thanks:)
