### ISSUE TITLE
SUSPICIOUS ACTIVITY LOGIN

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1444]
## Expected Behavior
Being able to login from anywhere on the bot.

## Current Behavior
Every time I get in, I'm stuck in the "verification loop", where I have to open the app or the website and click "It was me". Still, that doesn't fix the issue.

## Possible Solution (optional)
I have no idea but InstaPy is currently not usable at all. I had it run for less than 24h before this error started happening.

## InstaPy configuration
Basic, mode 0.

**Comment by sionking** [comment]
Do you use same account with mobile?
Are you using proxy?
Is the proxy located in different country when mobile access?

Try changing proxy.

**Comment by mdrzn** [comment]
I'm OP, I posted the issue with the wrong account.

I use the same account on Android, I'm located in Italy while the bot is running on a VM with German IP.
I'm not using any proxy, neither on the android or the server.

Let's say I find a free proxy that allows me to fake connect from an italian IP from the server, how to tell InstaPy to use it?

**Comment by CharlesCCC** [comment]
there is a setting you can set if you go to the wiki page and search proxy setting.

**Comment by sionking** [comment]
don't use free proxy. buy one anonymous one. 2 dollar a month

**Comment by jackpot001** [comment]
sionking, could you please tell me where you buy anonymous proxy for that price?

Thanks in advance.
