### ISSUE TITLE
Anyone willing to try? Emotion detector

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#1447]
There are many tools online and free to recognize face emotion / text emotion.
Let's go pro and comment according to emotion !

To read:
https://github.com/manid2/Python_OpenCV_Emotion_Detection
http://www.paulvangent.com/2016/08/05/emotion-recognition-using-facial-landmarks/#more-565
https://github.com/collab-uniba/Emotion_and_Polarity_SO

SC

**Comment by david-vendel** [comment]
I'm up for this! Who'll code it? :D
