### ISSUE TITLE
Question: Session Unfollow User

### ISSUE THREAD

**Issue by boldestfortune** [InstaPy/InstaPy#1448]
Wanted to get some clarification on the unfollow command. Does it unfollow accounts you have followed using the "session.follow_user_followers". Unless I missed something, I didn't see anything in the readme. 

Thank you!

**Comment by uluQulu** [comment]
hi @boldestfortune 
currently `unfollow_users()` feature has **unfollow** 3 methods

1. **only unfollow users auto-followed by Instapy (_unfollows every user followed by InstaPy, regardless of feature it was followed in..._)**
```python
session.unfollow_users(amount=50, onlyInstapyFollowed=True, onlyNotFollowMe=False)
```
2. **only unfollow users who are not following you (generally)**
```python
session.unfollow_users(amount=50, onlyInstapyFollowed=False, onlyNotFollowMe=True)
```
3. **unfollow everybody (_whether follows you or not..._)**
```python
session.unfollow_users(amount=50, onlyInstapyFollowed=False, onlyNotFollowMe=False)
```

**Comment by boldestfortune** [comment]
Thank you @uluQulu. 
`session.unfollow_users(amount=50, onlyInstapyFollowed=True, onlyNotFollowMe=True)`

Will running unfollow in this config break the script?

**Comment by uluQulu** [comment]
For the example above,
according to the current state of `unfollow()` function in `unfollow_util.py`  it will only execute `onlyInstapyFollowed=True` method and leave **that** `unfollow_users()` feature

You can actually get other results by changing conditional statements in `unfollow()` function
Currently there are 3 conditions, from top to down:
```python
if onlyInstapyFollowed is True:
```
```python
elif onlyInstapyFollowed is False and onlyNotFollowMe is True:
```
```python
elif onlyNotFollowMe is not True:
```
And it returns a value only after checking all these conditions..
What you would like to achieve? @boldestfortune

**Comment by boldestfortune** [comment]
I see. Perhaps I'm confused. Say for example I want instapy to unfollow only the users that the script followed, which are not following me back, **and not the users that i have personally followed, who are not following me back.** 

**Does** 
`session.unfollow_users(amount=50, onlyInstapyFollowed=False, onlyNotFollowMe=True)` 
**achieve this?**

**Comment by uluQulu** [comment]
Nope,

```python
session.unfollow_users(amount=50, onlyInstapyFollowed=True, onlyNotFollowMe=False)
```
**does** it

Just keep onlyInstapyFollowed=**True**, it will not touch other methods even if they are True..

> _i understand you, somehow, method names puzzled my mind at first, too_

**Comment by boldestfortune** [comment]
Great, Thanks for the clarification @uluQulu 

This is an amazing script, so a big thanks to the devs & contributors. Keep up the great work.
