### ISSUE TITLE
Configuring Firefox on Digital Ocean/Ubuntu so I can use a proxy

### ISSUE THREAD

**Issue by RayZorJ3lade** [InstaPy/InstaPy#1450]
I'm struggling to get proxies working. So far I have tried manually configuring the proxy settings for chrome in instapy.py:
`chrome_options.add_argument('--proxy-server=http://<ip_of_proxy>')`
But that didn't work so instead I tried using firefox which does support proxies, unfortunately firefox wasn't installed on the ubuntu server I'm using so I did a 

`sudo apt-get install firefox`

This appeared to install but still didn't work so I tried putting the latest geckodriver in the assets folder and making it executable using:

`wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz`
`tar -xvzf geckodriver*`
`chmod +x geckodriver`

But this resulted in the following error when i ran my quickstart.py:
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmsasdh8hyy If you specified a log_file in the FirefoxBinary constructor, check it for details.

Can anyone suggest a way I can either get proxies working on chrome or advise how to get firefox working?

**Comment by fiorellamezarine** [comment]
i am having the same error

**Comment by priyanka271** [comment]
Hello. I also need to run dynamic proxy on headless chrome. 
But problem is chrome does not support proxy in headless mode. 
Are you able to solve your issue?
