### ISSUE TITLE
running instapy on ubuntu server

### ISSUE THREAD

**Issue by HassanMehdi17** [InstaPy/InstaPy#1451]
```
root@insta-bot:~/InstaPy# python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 16, in <module>
    import requests
ImportError: No module named requests
```

when i run the below code, i get the above error. i followed the "do for ubuntu" tutorial. but i still get this error. i somehow got it working on my local machine just fine.

im running it on vultr, with ubuntu 16.04 server

```
from instapy import InstaPy

insta_username = 'XXXXXX'
insta_password = 'XXXXXX'

# set headless_browser=True if you want to run InstaPy on a server
try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      multi_logs=True)
    session.login()

    # settings
    session.set_lower_follower_count(limit=100)

    # actions
    session.follow_by_tags(['vintage', 'car', 'cars', 'vintagecars'], amount=600)
    
finally:
    # end the bot session
    session.end()
```

**Comment by shuhikari** [comment]
Have you installed the instapy required modules?

https://github.com/timgrossmann/InstaPy#basic-installation

**Comment by jgoranson4** [comment]
The same thing is happening to me. I have followed (and downloaded) everything outlined in the instapy Guide (How to Ubuntu (64-Bit) ). Not sure how to resolve this.

**Comment by syond** [comment]
Just udpate the python and run the command in the instapy folder:

`python setup.py install`

In my case i executed `python3 setup.py install`

**Comment by miltongoncalvesjunior** [comment]
from instapy import smart_run
from instapy import InstaPy

#set 
my_username = '#youruser'
my_password = '#yourpassword'


session = InstaPy(username=my_username,
                  password=my_password,
                  headless_browser=False)
with smart_run(session):
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=50,
                                    min_followers=30,
                                    min_following=50)

    #settings
    session.set_do_follow(True, percentage=100)
    
    #actions
    session.set_dont_like(['#yourtag', '#yourtag', '#yourtag'])

    session.like_by_tags(['#yourtag', '#yourtag'], amount=100)
