### ISSUE TITLE
Can't install pyvirtualdisplay, please help!!!

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1453]
Hey guys, when I try to install pyvirtualdisplay typing "pip3.6 install pyvirtualdisplay" (which is the only one working), I get this:

 Collecting pyvirtualdisplay
  Using cached PyVirtualDisplay-0.2.1.tar.gz
Collecting EasyProcess (from pyvirtualdisplay)
  Using cached EasyProcess-0.2.3.tar.gz
Installing collected packages: EasyProcess, pyvirtualdisplay
  Running setup.py install for EasyProcess ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/l5/cp386r7x6md4_z9l8tmdvgv40000gq/T/pip-build-zkkhpx7v/EasyProcess/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/l5/cp386r7x6md4_z9l8tmdvgv40000gq/T/pip-nucvwust-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/easyprocess
    copying easyprocess/unicodeutil.py -> build/lib/easyprocess
    copying easyprocess/__init__.py -> build/lib/easyprocess
    copying easyprocess/about.py -> build/lib/easyprocess
    creating build/lib/easyprocess/examples
    copying easyprocess/examples/hello.py -> build/lib/easyprocess/examples
    copying easyprocess/examples/cmd.py -> build/lib/easyprocess/examples
    copying easyprocess/examples/log.py -> build/lib/easyprocess/examples
    copying easyprocess/examples/timeout.py -> build/lib/easyprocess/examples
    copying easyprocess/examples/__init__.py -> build/lib/easyprocess/examples
    copying easyprocess/examples/ver.py -> build/lib/easyprocess/examples
    Fixing build/lib/easyprocess/unicodeutil.py build/lib/easyprocess/__init__.py build/lib/easyprocess/about.py build/lib/easyprocess/examples/hello.py build/lib/easyprocess/examples/cmd.py build/lib/easyprocess/examples/log.py build/lib/easyprocess/examples/timeout.py build/lib/easyprocess/examples/__init__.py build/lib/easyprocess/examples/ver.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    Fixing build/lib/easyprocess/unicodeutil.py build/lib/easyprocess/__init__.py build/lib/easyprocess/about.py build/lib/easyprocess/examples/hello.py build/lib/easyprocess/examples/cmd.py build/lib/easyprocess/examples/log.py build/lib/easyprocess/examples/timeout.py build/lib/easyprocess/examples/__init__.py build/lib/easyprocess/examples/ver.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running install_lib
    creating /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/easyprocess

    **error: could not create '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/easyprocess': Permission denied**

----------------------------------------------------------------------------------------------------

After that I get:

 "Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/l5/cp386r7x6md4_z9l8tmdvgv40000gq/T/pip-build-zkkhpx7v/EasyProcess/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/l5/cp386r7x6md4_z9l8tmdvgv40000gq/T/pip-nucvwust-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/l5/cp386r7x6md4_z9l8tmdvgv40000gq/T/pip-build-zkkhpx7v/EasyProcess/" 

It seems like I don't have the sudo permissions to access the library. 
But I am the admin so I have sudo permissions. What do you guys think? 
Help much appreciated!

**Comment by ghost** [comment]
Update: almost done. Installed pyvirtualdisplay by going full root using sudo and removing  "session.set_dont_like(['pizza', 'girl'])" from the quickstart.py code.

Installed selenium successfully and now have another problem:

`ModuleNotFoundError: No module named 'clarifai'`

Installed clarifai through the root, but when I launch 

`python3.6 quickstart.py` 
it work until it gets to 
`ModuleNotFoundError: No module named 'clarifai'`. 

What could have happened?

**Comment by FranklinClinton** [comment]
remove line 18 and 19 from instapy/instapy.py:
```
if os.name != 'nt':
    #from .clarifai_util import check_image
```
If u remove those, clarifai won't get imported as far as I know
