### ISSUE TITLE
Hey Guys! im not sure why! looked around in the issues box but cant find anyone with this problem.... im locked to only liking 27 posts, cant see why... cant find a solution... please help (im using the quickstart.py)

### ISSUE THREAD

**Issue by Emilbackhausen** [InstaPy/InstaPy#1455]

**Comment by uluQulu** [comment]
hi @Emilbackhausen 
if you have not solved it yet, you may apply the fix in [here](https://github.com/timgrossmann/InstaPy/issues/1365#issuecomment-366526517)

**Comment by kevXZY** [comment]
@uluQulu I applied the fix, still no luck. Only 27 posts liked/followed...

**Comment by uluQulu** [comment]
@neomh 
Have you applied the fix correctly?
cos if you did and if it didn't work for you would get like `12` or maybe `9` but not 27, it means you missed sth

**Comment by kevXZY** [comment]
@uluQulu I replaced my like_util.py with https://gist.github.com/54a2cf26345a05355c5c21c433bf6616.git
Didn't notice any change..

**Comment by uluQulu** [comment]
@neomh 
I see, it is weird, I haven't seen anybody getting 27 pictures after applying my approach, but I should also say that it is only fixed for `like_by_tags()` feature, for others (e.g. `like_by_locations()`) you should apply the fix similarly

**Comment by kevXZY** [comment]
@uluQulu Indeed I was using like by location... :flushed: Thanks!
