### ISSUE TITLE
set_do_like is not applicable

### ISSUE THREAD

**Issue by m190** [InstaPy/InstaPy#1458]
Documentation or code issue.

In [Interact with someone else's followers](https://github.com/timgrossmann/InstaPy#interact-with-someone-elses-followers) or [Interact with users that someone else is following](https://github.com/timgrossmann/InstaPy#interact-with-users-that-someone-else-is-following) is said that 

>\# set_do_comment, set_do_follow and set_do_like are applicable

But due to code `set_do_like` is not applicable.

## Expected Behavior
`set_do_like` is applicable in `interact_user_following` and `interact_user_followers` or the documentation should contains that `set_do_like` is not applicable in that actions

## Current Behavior
`set_do_like` is not applicable in `interact_user_following` and `interact_user_followers`

## InstaPy configuration
see example for that methods

**Comment by salbatron** [comment]
@BernardoGO @timgrossmann  shouldn't that be implemented?
