### ISSUE TITLE
"Cannot read property of 'is_video' of undefined

### ISSUE THREAD

**Issue by taihoang** [InstaPy/InstaPy#146]
I ran it and got this error: 

> 
> selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'is_video' of undefined
>   (Session info: chrome=57.0.2987.133)
>   (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.14393 x86_6
> 4)

Does anyone know how to fix it?

**Comment by tibor** [comment]
I guess that has to do with #131

**Comment by blesson3** [comment]
That was just fixed in PR #131
