### ISSUE TITLE
Zero Devision Error

### ISSUE THREAD

**Issue by SkylimiTY** [InstaPy/InstaPy#1461]
Hey, guys, this is the error it gives out since a few days. Can you give me a hand on fixing it?

## Current Behavior
![error](https://user-images.githubusercontent.com/36607594/36356270-24328d8c-14f0-11e8-9afb-cbbdfd2d9b31.JPG)

## InstaPy configuration
session = InstaPy(username=insta_username, password=insta_password, headless_browser=False)
session.login()
session.unfollow_users(amount=500, onlyNotFollowMe=True, onlyInstapyMethod = 'FIFO', sleep_delay=60)
session.set_do_follow(enabled=True, percentage=90, times=1)
session.like_by_tags(['blogger', 'travelblog', 'travel', 'couple', 'destination', 'likeforfollow', 'like4follow', 'followme', 'follow4follow', 'instafollow', 'followback'], amount=50)
session.end()

**Comment by sionking** [comment]
I think I fixed it in last commit ?

**Comment by SkylimiTY** [comment]
Which post is it, I couldn't find it?
