### ISSUE TITLE
name 'session' is not defined - running on a VPS

### ISSUE THREAD

**Issue by riccardorighettiphoto** [InstaPy/InstaPy#1462]
Ok,
it is about 5 hours I am trying to run InstaPy on an VPS server for which I received a coupon.
The server has a CentOS 7.x installation with Python2.7.5 preinstalled. I then installed Python3.6.4.

Here below the list of tasks performed:
- cloned the repository;
- ran `pip install .` (I got some errors in red, but I cannot print stamp those at the moment);
- copied the last version of chromdriver in /assets directory;
- edited `quickstart.py` file by adding `nogui=True` snippet in the constructor.
- finally I had run `python3.6 quickstart.py` and got errors: "name 'session' is not defined.

I then tried multiple variations: removing `nogui=True` and adding `headless_browser=True`, or adding the latter along with `nogui=True`. No chance to get logged.
I even tried with `python quickstart.py` and `python2.7 quickstart.py`.

Really frustrated... I got able to run the application on two windows machines and not on a Linux Server! Really disappointing!

**Comment by joaopdb** [comment]
It was happening to me right now and I discovered that I just needed to install the chorme lol.
install chrome
following this tutorial
https://askubuntu.com/questions/79280/how-to-install-chrome-browser-properly-via-command-line

**Comment by riccardorighettiphoto** [comment]
@joapdb
Are you running on a server as me?
Is it needed installing Chrome (or Chronium) even if the script will run on a server?

**Comment by julianNNss** [comment]
I had the same problem, I just downloaded chromedriver (https://sites.google.com/a/chromium.org/chromedriver/) and I put the .exe in /assets (I have windows, I don't know how to do it in CentOS)

**Comment by riccardorighettiphoto** [comment]
@julianNNss 
already done that, as in my first message.

**Comment by riccardorighettiphoto** [comment]
Ok gentlemen,
I was finally able to get running, even with a ton of issues, tries and hours spent (not less than 10).
I should have to move from a standard installation suggested in the Read Me section to a customized one, by installing (sometimes) manually some modules (e.g. Xfvb, Chromium, Google Chrome...). Unfortunately, the instructions for a Debian/Ubuntu installation on Digital Ocean VPS are not always correct for an installation on CentOS 7.x.
Anyway, I hope to remember the procedeure I have followed and report details in the future. :)

Bye.

**Comment by riccardorighettiphoto** [comment]
Very sad, I had to purge my server, now I have reinstalled InstaPy and (of course) I get again this horrible error and I cannot understand where is the matter!
