### ISSUE TITLE
End report

### ISSUE THREAD

**Issue by cbyrt** [InstaPy/InstaPy#1463]
## InstaPy configuration

Is there a code to see how many likes and comments the bot has done in one session?

**Comment by uluQulu** [comment]
hi @cbyrt 
sure you can do it by calling available InstaPy instances

_we had lively updated `followed` value  before and recently @lucanello shared an amazing commit #1355 to provide `like`, `already liked`, `comment`, `unfollow`, `inappropriate images` **values** keep updated after **most** of the features, so they are counting up during the session
now you can access all of them as in below_

for example, add these lines below  to your **quickstart** before your `session.end() line`
```python
print ("\n    ~ Sessional Live Report ~\n\n->\
   {} images were LIKED\n->\
   {} images were ALREADY_LIKED\n->\
   {} images were COMMENTED\n->\
   {} users were FOLLOWED\n->\
   {} users were UNFOLLOWED\n->\
   {} images were found INAPPROPRIATE\n\n->\
   currently got {} FOLLOWERS\n\n\
       ~       ~       ~       ~".format( 
                session.liked_img,
                session.already_liked,
                session.commented,
                session.followed,
                session.unfollowNumber,
                session.inap_img,
                session.followed_by,
                 )
         )
```

similarly you can use that `print()` line above anywhere in your quickstart scrtip just after initiating **session** (`session=InstaPY()`),  e.g. **between** `follow_user_followers` and next feature `like_by_feed` to see the new reportş..

> **to simplify**, write that `print()` line in a function at quickstart and call only that function when needed detailed report again, instead of pasting those big lines...
