### ISSUE TITLE
Error Follows by Location 

### ISSUE THREAD

**Issue by codc3** [InstaPy/InstaPy#1464]
![image](https://user-images.githubusercontent.com/25847896/36385275-de251310-1570-11e8-8f67-73bed905fedc.png)
  code

```
(...)
session = InstaPy(username=insta_username,
                      password=insta_password,
                      nogui=True)
    session.login()
    session.like_by_locations(locations=['224442573/salton-sea /'], amount=3, media=None)
inally:
    # end the bot session
    session.end()
```

**Comment by uluQulu** [comment]
hi @codc3 
Python is very serious about indentation where you can only use either **tabs** or **spaces** for indentation.
**1 tab **equals to** 4 spaces**
_so check out your quickstart script near `session.like_by_locations()` to use either one of them_

> * some text editors can show invisible characters like **tab**s, **space**s **return**s, use it to see your invisible characters in order to fix

> * also make sure your editor converts tabs to 4 spaces and or vice verse, from now on
