### ISSUE TITLE
interact_by_users should not comply with "upper/lower follower_count"

### ISSUE THREAD

**Issue by CharlesCCC** [InstaPy/InstaPy#1465]
## Expected Behavior
If I know I'm gonna interact with user X,  I should already knew how many follower it has. and It doesn't matter how many followers it has. The interaction should still happens
## Current Behavior
If I set `interact_by_users` for user X and I have `upper_follower_count` set to 500, if the user X has 5001 followers. It will be getting `--> Image not liked: Number of followers exceeds limit` 
## Possible Solution (optional)
set `upper_follower_count`  to 5002, but this will change for everything. which is not desired. 
## InstaPy configuration
N/A

**Comment by uluQulu** [comment]
Hi @CharlesCCC 
you're so right, we should interact regardless of the amount
**to solve**, open up `interact_by_users()` method at `instapy.py` file

**1**. add these after `followed=0` line 
```python
upper_follower_limit = None
lower_follower_limit = None
```
**2**. and pass **these** values to `check_link()` instead of class's _sessional_ `self.like_by_followers_upper_limit` and `self.like_by_followers_lower_limit` values
```python
check_link(self.browser,
    link,
    self.dont_like,
    self.ignore_if_contains,
    self.ignore_users,
    self.username,
    upper_follower_limit,   #you will modify this line
    lower_follower_limit,   #this line too
    self.logger,
    self.bye_b)
```

_now it **will not** check for upper **or** lower limit_

> also this applies only to `interact_by_users()` feature whilst isn't affected in others...

**Comment by CharlesCCC** [comment]
@uluQulu that didn't work.

I have to replace the following parameter to `0` instead

```
                                   self.like_by_followers_upper_limit,
                                   self.like_by_followers_lower_limit,
```

**Comment by uluQulu** [comment]
@CharlesCCC 
in check_link() it checks for `if like_by_followers_upper_limit or like_by_followers_lower_limit:`
`None` gets the job done, it works for me, **did you** apply correctly? (_I **edited** code several times after posting, get the latest state xD_)

_BTW, do not equalize `self.like_by_followers_upper_limit` sessional parameters to zero, cos it will nullify upper follower number from that time on, so in the next features, upper limit will also be 0_ 

I think `like_by_users()` also needs this, eh?
