### ISSUE TITLE
Running quickstart.py on Raspberry Pi 3

### ISSUE THREAD

**Issue by gabriansa** [InstaPy/InstaPy#1468]
hello! I followed all the steps in order to run InstaPy on my Raspberry Pi 3. I decided to use firefox esr. So far everything went fine except when i try to run my file quickstart.py. I already modified it putting use_firefox=True.

Here is what i get:

```
pi@raspberrypi:~/Projects/InstaPy $ xvfb-run -a python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.end()
NameError: name 'session' is not defined
```
Thanks!

**Comment by quintendewilde** [comment]
Try it again, It sometimes does it on my RPi3 and than I try it again and it works. Still need to find out how to speed things if when running with view :)

**Comment by mikestan** [comment]
I had same problem and got this to work by following this thread: https://www.raspberrypi.org/forums/viewtopic.php?t=194176

Essentially, the chromedriver for Raspberry Pi wasn't right (I did an update before installing InstaPy) and also the first library in the link wasn't installed (second two were)...
