### ISSUE TITLE
Keep getting same error

### ISSUE THREAD

**Issue by maxinedotdev** [InstaPy/InstaPy#147]
I am getting the same error and I cannot see where that 'b' is coming from. I saw the same error in #135, but without much explanation for why this is so.

--> b'#technology'
[1/100]
Image from: b'picoplay'
Link: b'https://www.instagram.com/p/BTCO87NlkgJ/?tagged=technology'
Description: b'Peaple Get Earwax Extractions For The First Time!\n\xd8\xaf\xd8\xb1\xd9\x88\xd9\x86 \xda\xaf\xd9\x88\xd8\xb4 \xd8\xb4\xd9\x85\xd8\xa7 \xda\x86\x
d9\x82\xd8\xaf\xd8\xb1 \xda\xa9\xd8\xab\xdb\x8c\xd9\x81 \xd8\xa7\xd8\xb3\xd8\xaa\xd8\x9f\n.\n.\n\xd9\xbe\xdb\x8c\xd8\xac \xd8\xb3\xd9\x88\xd9\x85\xd9\x85\xd9\x
88\xd9\x86 \xd9\xbe\xdb\x8c\xda\xa9\xd9\x88\xd9\x81\xda\xa9\xd8\xaa \xd8\xb1\xd9\x88 \xd9\x85\xdb\x8c\xd8\xaa\xd9\x88\xd9\x86\xdb\x8c\xd8\xaf \xd8\xaf\xd9\x86\
xd8\xa8\xd8\xa7\xd9\x84 \xda\xa9\xd9\x86\xdb\x8c\xd8\xaf\xf0\x9f\x91\x87\n@picofact\n@picofact\n@picofact\n____________________\n#PicoPlay #Science #Technology
 #Amazing #ear\n#\xd8\xb9\xd9\x84\xd9\x85#\xd8\xaa\xda\xa9\xd9\x86\xd9\x88\xd9\x84\xd9\x88\xda\x98\xdb\x8c#\xd9\xbe\xdb\x8c\xda\xa9\xd9\x88\xd9\xbe\xd9\x84\xdb
\x8c #\xda\xaf\xd9\x88\xd8\xb4'
Traceback (most recent call last):
  File ".\run.py", line 17, in <module>
    session.like_by_tags(['#technology', '#futurism', '#tech', '#minimalism', '#minimalist', '#vr'], amount=100)
  File "C:\Users\waagn\Documents\GitHub\InstaPy\instapy\instapy.py", line 271, in like_by_tags
    self.username, self.like_by_followers_upper_limit, self.like_by_followers_lower_limit)
TypeError: 'NoneType' object is not iterable

**Comment by timgrossmann** [comment]
@hillockink  Please provide your quickstart.py setup

**Comment by timgrossmann** [comment]
http://stackoverflow.com/questions/6269765/what-does-the-b-character-do-in-front-of-a-string-literal

**Comment by maxinedotdev** [comment]
I run mine from a external file, run.py, but I get the same error with an unadulterated quickstart.py, apart from my login information of course.

[2/100]
Image from: b'goldenretrievers'
Number of Followers: 360076
Link: b'https://www.instagram.com/p/BTCuQ7MDn9w/?tagged=dog'
Description: b"Cruisin' \xf0\x9f\x9a\x97 \nBy @lifeofscout_\n\n@lifeofscout_ \xe2\x9d\xa4\xef\xb8\x8f\xe2\x9d\xa4\xef\xb8\x8f\xe2\x9d\xa4\xef\xb8\x8f"
Traceback (most recent call last):
  File "./quickstart.py", line 23, in <module>
    .like_by_tags(['dog', '#cat'], amount=100) \
  File "C:\Users\waagn\Documents\GitHub\InstaPy\instapy\instapy.py", line 271, in like_by_tags
    self.username, self.like_by_followers_upper_limit, self.like_by_followers_lower_limit)
TypeError: 'NoneType' object is not iterable

**Comment by pekapa** [comment]
@hillockink, can you please update and see if it persists?

**Comment by maxinedotdev** [comment]
Yes, the script is now running fine.

The 'b', however, is still very persistent.

**Comment by imovertheinternet** [comment]
Thanks @pekapa 
I was about to open a similar issue. Your commit seemed to fix my "TypeError: 'NoneType' object is not iterable" and Im not receiving any "b" error.

**Comment by pekapa** [comment]
Good!

The `b` seems to be related on the `unicode` changes between python2 and python3.
Since it's not raising any problems, I'm closing this issue.
