### ISSUE TITLE
How to confirm InstaPy is running properly

### ISSUE THREAD

**Issue by anthonyattard** [InstaPy/InstaPy#1470]
I'm looking for an automated method to confirming the bot is running as expected when automated with cron on a server. Something like another bot following some of the links that were interacted with and check if it actually did. A simpler method would be to have a notification sent out if the bot fails with an error. 

Have has anyone come up with any methods to do this?

**Comment by sionking** [comment]
I done it complicated, but the simple solution is:
Just every like update a json/pickle file with like amount and timestamp.
From out side read this file and check every hour the timestamp is updated.

**Comment by iFede94** [comment]
I have made something similar that sends me telegram messages in some cases I defined:
- every time the script fails to tell me the exception causing it
- every time the script finishes a task to tell me the stats of that task

I'm using it because I have the script automated by cron and I need to see if the script is running correctly or not.

**Comment by anthonyattard** [comment]
@iFede94 How did you integrate InstaPy with cron and Telegram? Have any resources you'd recommend to accomplish this?

**Comment by iFede94** [comment]
@anthonyattard The idea is to have the InstaPy script automated by cron and the python telegram bot running with it. When InstaPy script starts, it creates an instance of the bot so it can send messages to me.
The telegram bot idea came from the one linked in the readme but mine can only send messages to allowed chat IDs and can't receive any command.
Basically if you look at quickstart.py, I start the bot at the top of the run function and I send a message when starting and finishing every task or when any exception occurs.
If you want today I can upload my code on github and create a readme on how to use it.

**Comment by anthonyattard** [comment]
@iFede94 Thanks that gives me some valuable pointers. A repo of your code would be great! Much appreciated.

**Comment by iFede94** [comment]
You can find my repo [here](https://github.com/iFede94/telegram-bot). You may need to change the path to get the general.log file because I'm using an old version of InstaPy and I don't know if they changed the path or not in the newer commits.

**Comment by anthonyattard** [comment]
@iFede94 Thanks so much!

**Comment by miguelrodriguezpro** [comment]
It would be possible to notify me through telegram when finished and with the exacts Follows/unfollows/likes performed during the session? thanks!

**Comment by miguelrodriguezpro** [comment]
> It would be possible to notify me through telegram when finished and with the exacts Follows/unfollows/likes performed during the session? thanks!

@iFede94

**Comment by iFede94** [comment]
> It would be possible to notify me through telegram when finished and with the exacts Follows/unfollows/likes performed during the session? thanks!

It was developed to work like this. My code is old so you should update it to reflect the changes made to InstaPy.

**Comment by rajrpatel62499** [comment]
### I am getting this bunch of errors while creating just instance of Instapy. Please help with this.
bot = InstaPy(username=insta_username,password=insta_password,headless_browser=False)

> ``C:\Users\rajrp\PycharmProjects\InstapyTrial\venv\Scripts\python.exe C:/Users/rajrp/PycharmProjects/InstapyTrial/InstapyTrial.py
InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/rajrp/AppData/Roaming/SPB_Data/InstaPy"
Traceback (most recent call last):
  File "C:/Users/rajrp/PycharmProjects/InstapyTrial/InstapyTrial.py", line 22, in <module>
    bot = InstaPy(username=insta_username,
  File "C:\Users\rajrp\PycharmProjects\InstapyTrial\venv\lib\site-packages\instapy\instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\rajrp\PycharmProjects\InstapyTrial\venv\lib\site-packages\instapy\browser.py", line 111, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\rajrp\PycharmProjects\InstapyTrial\venv\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\rajrp\PycharmProjects\InstapyTrial\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\rajrp\PycharmProjects\InstapyTrial\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\rajrp\PycharmProjects\InstapyTrial\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\rajrp\PycharmProjects\InstapyTrial\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by Viktor19931** [comment]
I got this error
`
Starting InstaPy with quickstart
====================
Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/Users/victor/Library/Python/2.7/lib/python/site-packages/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users/victor/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 21, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined
`
