### ISSUE TITLE
SOLVED: username and password with selenium and chrome (proxy)

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#1472]
It is very simple:
https://stackoverflow.com/questions/8885137/selenium-using-python-enter-provide-http-proxy-password-for-firefox/35293222

goto solution "Create a zip file proxy.zip containing two files:"

and add add_extension line in instapy.py
```
            chrome_prefs = {
                'intl.accept_languages': 'en-US'
            }
            chrome_options.add_extension("assets/proxy.zip")
```

SCK

**Comment by sionking** [comment]
I will PR soon

**Comment by ghost** [comment]
I have created a PR https://github.com/timgrossmann/InstaPy/pull/1531
Check please.

**Comment by rohitsingh093** [comment]
It does work for chrome without headless but when It dosen't work with headless chrome and throws  org.openqa.selenium.WebDriverException: unknown error: failed to wait for extension background page to load: chrome-extension.

**Comment by maxvgi** [comment]
@roronoa007 , That is because headless chrome does not support extensions: https://bugs.chromium.org/p/chromium/issues/detail?id=706008

You could run chrome via xvfb or use headless firefox.
