### ISSUE TITLE
target users who liked/commented the latest post of someone

### ISSUE THREAD

**Issue by DanielSemmelrock** [InstaPy/InstaPy#1473]
# Idea
_(let's assume you want to grow an Instagram page about dancing)_
### In my opinion the best way to find users who are interested in your topic is:
1. go to a big page i.e. the page of "_Gillian Murphy_" who is a famous ballet dancer
2. click on one of her latest posts
3. find users who liked or commented that particular post
4. interact with those users (like one of their posts, like their comment, follow them, send a dm)

_EDIT:
It would be useful to only interact with users who you aren't already following / who aren't already following you. When you click on the likes of a post, all the users you are following, are shown on top and the other users on bottom so that could be a little problem._

## Current Behavior
I couldn't find a way to automate the 4 steps described above.
I think there is only the `like_by_tags()` function and not a `like_by_latest_post_of("Gillian Murphy")` function.

### My configuration
windows 10 latest version of InstaPy (20.02.2018)

Thanks,

Daniel Semmelrock
IG: @giantsofrock

**Comment by uluQulu** [comment]
hi @DanielSemmelrock, it is currently not available but `@mrteacherman123` at our Slack channel is implementing it: _a new feature to interact with likers & commenters as well_

> also **I think** you can DM _only using_ official/non-official mobile app or API and is not available for web browsers which we use in InstaPy, for now

**Comment by DanielSemmelrock** [comment]
Thanks for your reply @uluQulu 
Can users join the Slack channel or follow the developers?
When will he be finished?

> also I think you can DM only using official/non-official mobile app or API and is not available for web browsers which we use in InstaPy, for now

true forgot about that

**Comment by uluQulu** [comment]
It is very easy!
simply install Slack app for your OS
then [Join InstaPy Slack channel!](https://join.slack.com/t/instapy/shared_invite/enQtMjYzNTgwMDg3MDEyLTk2NWI0MjY2MTVjYmM2NjFlYjVmMmE0ZjU1OGQ0OWM2MTQwOTc1NTIyOGVhZDEwMTFkYzFmODE5ZWIxZjhjMTQ)
_we already got 319 ppl in there_
and maybe you would write to @mrteacherman123 about your ideas to also include in the new feature, he is a professional programmer :-)

**Comment by sionking** [comment]
think will get deprecate here since you will go to the same user and post day after day so you will interact with the same likers / commenters how can you avoid saturation?

**Comment by uluQulu** [comment]
@sionking 
storing the interacted users' list (_even including the interaction level info_) per root user in a local file would help to avoid repetition and allow further analytic interactions
since this will be an effective feature, one more log file would do no harm :-)

**Comment by keusta** [comment]
@uluQulu very good idea, every user got unique id, could be fast to compare it !
@DanielSemmelrock when you said "all the users you are following, are shown on top and the other users on bottom so that could be a little problem" its true only if logged, maybe if we logout, record the list and log again is possible

**Comment by KingKorSin** [comment]
Did this feature get finished by any chance?
