### ISSUE TITLE
Interact with someone's followers shows invalid syntax

### ISSUE THREAD

**Issue by rayanakiki** [InstaPy/InstaPy#1479]
Hello,
I am running the bot in ubuntu terminal. I would like to interact with someone's followers.
However, when i run the script, i get SyntaxError: invalid syntax
This is the InstaPy configuration:
```
from instapy import InstaPy

insta_username = 'myusername'
insta_password = 'mypassword'

# set headless_browser=True if you want to run InstaPy on a server
try:
    # set these if you're locating the library in the /usr/lib/pythonX.X/ directory
    # Settings.database_location = '/path/to/instapy.db'
    # Settings.browser_location = '/path/to/chromedriver'
    
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      multi_logs=True)
    session.login()
    session.set_user_interact(amount=3, randomize=True, percentage=50, media='Photo')
    session.set_do_like(enabled=False, percentage=70)
    session.interact_user_followers(['natgeo'], amount=10, randomize=True)
    

finally:
    # end the bot session
    session.end()
```
I get this in terminal:
```
File "quickstart.py", line 20
    session.set_user_interact(amount=3, randomize=True, percentage=50, media='Photo')
          ^
SyntaxError: invalid syntax
```

**Comment by loic-hamdi** [comment]
Hi @rayanakiki ,
Same issue - How did you fix it please ?

**Comment by rayanakiki** [comment]
i reverted to the original quickstart.py and editted it to suit my needs to
interact with the followers. There might be an error in your file such as
wrong spacing.

On Jun 3, 2018 8:38 PM, "zzterrozz" <notifications@github.com> wrote:

Hi @rayanakiki <https://github.com/rayanakiki> ,
Same issue - How did you fix it please ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/timgrossmann/InstaPy/issues/1479#issuecomment-394178332>,
or mute the thread
