### ISSUE TITLE
Why is the pillow working?

### ISSUE THREAD

**Issue by harrycha** [InstaPy/InstaPy#1483]
I reinstalled InstaPy, I am having a hard time pip installing all these packages. Does anyone have like a simple rundown of this?

My code is:

from instapy import InstaPy
import os
session = InstaPy(username='xxxxx', password='xxxxxx')
session.login()
session.follow_user_followers(['yyyyyyyy' ], amount = 30, random=False, delay=730)
session.like_by_tags(['vibes', ' toronto'], amount=0)

session.end()

I get many errors but I have resolved a lot how ever this is what I get from not having clarifai installed:

  File "c:\Users\Harry's HP envyx360\Desktop\Python\InstaPy-master\InstaPy-master\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Image as ClImage
builtins.ModuleNotFoundError: No module named 'clarifai'

So I go to install clarifai:
pip install clarifai

The error I get is: 
  Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow

This is my pip list:
certifi (2018.1.18)
chardet (3.0.4)
chromedriver (2.24.1)
configparser (3.5.0)
EasyProcess (0.2.3)
emoji (0.4.5)
enum34 (1.1.6)
future (0.15.2)
idna (2.6)
jsonschema (2.5.1)
pillow (5.0.0)
pip (9.0.1)
pypiwin32 (220)
PyVirtualDisplay (0.2.1)
requests (2.13.0)
selenium (3.8.1)
setuptools (33.1.1)
urllib3 (1.22)
wheel (0.30.0)

How do I fix this and I feel there are more issues in properly installing instapy, if by chance anyone knows all the code I need to type to cmd can you please let me know?

I am on Windows 10, and new to installing through pip. I know how to code but not set up environments  with heavy linking.

**Comment by uluQulu** [comment]
hi @OGHARRY 
it can be cos of clarifai using pillow v2.9
I see already got v5.0 over there, downgrading would help

**Comment by ghost** [comment]
I do get the same error when installing clarifai with pip. Please let us now if someone finds a solution to this.
