### ISSUE TITLE
Is it possible to import a list of accounts? 

### ISSUE THREAD

**Issue by gdesiato** [InstaPy/InstaPy#1484]
Hi, my question is if there is the possibility to like the posts from a list of specific account.
I know that it is possible manually. But Can I import the list of 100 accounts without writing them one by one?
Thanks

**Comment by CharlesCCC** [comment]
one computer one ip and one account is the basic rule. 
with 100, even with 10 accounts, seems very very dangerous to do. Instagram may block all of the activities for that IP address if not sensed any strange activities.

**Comment by gdesiato** [comment]
Hi thank you for your reply.
Maybe there was a misunderstanding.
I was wondering if there is a way to like the photos of specific accounts, or to interact with specific users, for example:

session.interact_by_users(['user1', 'user2', 'user3']

but without inputting all the names manually. and, instead, reading the names of the accounts from a list.
thank you

**Comment by CharlesCCC** [comment]
Yea, with the list of accounts defined in a file you can follow this Stackoverflow question to implement that
[Answer](https://stackoverflow.com/questions/17225287/python-2-7-write-and-read-a-list-from-file)

**Comment by gdesiato** [comment]
ok! thank you very much.
I will try it!
