### ISSUE TITLE
Division par zero error...

### ISSUE THREAD

**Issue by MrStefaan** [InstaPy/InstaPy#1485]
Hello all, I reinstalled Instapy with the lastest version and python 3.6.3 on W7, and I still have division par zero error.
It happens randomly on any tag, after 1min or 1 hour, has anyone found effective solution yet?

> Traceback (most recent call last):
>   File "quickstart.py", line 17, in <module>
>     session.like_by_tags(['cool', 'like4like', 'foodporn', 'love', 'followme', 'instagood', 'photooftheday', 'picoftheday', 'macro', 'nature', 'nofilter', 'flower', 'happy', 'naturephotography', 'winter'], amount=20)
>   File "C:\Users\Stefan\Documents\GitHub\InstaPy-master\instapy\instapy.py", line 824, in like_by_tags
>     skip_top_posts)
>   File "C:\Users\Stefan\Documents\GitHub\InstaPy-master\instapy\like_util.py", line 237, in get_links_for_tag
>     new_per_page = ceil(12 * filtered_links / total_links
> ZeroDivisionError: division by zero

And here is my quickstart 

>  from instapy import InstaPy
> 
> insta_username = ''
> insta_password = ''
> 
> session = InstaPy(username=insta_username, password=insta_password)
> 
> session.login()
> 
> session.set_upper_follower_count(limit=5000)
> 
> session.like_by_tags(['cool', 'like4like', 'foodporn', 'love', 'followme', 'instagood', 'photooftheday', 'picoftheday', 'macro', 'nature', 'nofilter', 'flower', 'happy', 'naturephotography', 'winter'], amount=20)
> 
> session.end()

**Comment by cctij69** [comment]
I think it's an instagram issue. It only happens on some hashtags. If you even visit the page on your phone or website for that certain tag, it won't load any posts. So I think instagram has broken something. It seems to be the more popular hashtags that don't work. For example....

https://www.instagram.com/explore/tags/like4like/

Nothing loads when I go on that link. Where as if you visit the same page but for your "cool" tag, it loads fine.

**Comment by CharlesCCC** [comment]
@cctij69 that is so strange tho, why the most popular tag is not able to load any image... either, This should be handled just to prevent the script from crushing.

**Comment by MrStefaan** [comment]
Looks like I have to check my tag sometimes, I deleted the bugged and now it works, thank you!

**Comment by martinkuna** [comment]
We should add a check for this...

**Comment by cctij69** [comment]
I think instagram fixed the hashtags as the ones that didn't work before are now working again

**Comment by martinkuna** [comment]
Every single time I run the bot this happens to me, with vastly popular tags, even if I run a single tag :(

**Comment by martinkuna** [comment]
I fixed it similarly to the way we check if new_per_page == 0 , it no longer crashes and it retries if it cannot grab the images first try. https://github.com/timgrossmann/InstaPy/blob/20e54e6014ece6d8137e05522bb33bb4f950f2ee/instapy/like_util.py#L239 c
