### ISSUE TITLE
Can't unfollow anyone

### ISSUE THREAD

**Issue by michaloslav** [InstaPy/InstaPy#1487]
## Expected Behavior
should unfollow (duh)

## Current Behavior
I get this error everytime:
`INFO [2018-02-22 21:56:05] [{username}]  Number of people followed automatically remaining: 701
INFO [2018-02-22 21:56:12] [{username}]  {user},
 removed from csv
ERROR [2018-02-22 21:56:12] [{username}]  unfollow loop error log_record_all_unfollowed() missing 1 required positional argument: 'logfolder'
INFO [2018-02-22 21:56:12] [{username}]  --> Total people unfollowed : 0`

## Possible Solution (optional)
I think a problem might be that I use(d) a for loop for the tasks. Look down at the config.

## InstaPy configuration

Ubuntu 16.04 LTS, 64-bit, 3.9GB RAM, 3.30 GHz * 2 (it's running inside VirtualBox)

quickstart.py:
(for some reason, I can't get GitHub to display this section properly as code so I just put it here as plain text, sorry if it's a little messy)

from instapy import InstaPy

insta_username = '{username}'
insta_password = ''

# set headless_browser=True if you want to run InstaPy on a server
try:
    # set these if you're locating the library in the /usr/lib/pythonX.X/ directory
    # Settings.database_location = '/path/to/instapy.db'
    # Settings.browser_location = '/path/to/chromedriver'
    
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      multi_logs=True)
    session.login()

    # settings
    session.set_upper_follower_count(limit=1000)
    session.set_lower_follower_count(limit=5)
    session.set_user_interact(amount=5, randomize=True, percentage=20, media='Photo')
    session.set_do_follow(enabled=True, percentage=60)
    session.set_do_like(enabled=True, percentage=20)
    # session.set_smart_hashtags(['martingarrix', 'mikewilliams', 'thechainsmokers'], limit=3, sort='top', log_tags=True)
    session.set_do_comment(enabled=True, percentage=5)
    session.set_comments(['AMAZING!', 'Awesome!!', 'Nice!', 'Love it!'])
    session.set_dont_include([])
    session.set_dont_like(['musician', 'beats', 'housemusic', 'musicproducer', '#producer'])
    session.set_dont_unfollow_active_users(enabled=True, posts=16)

    # actions
    for i in range(10):
        # session.like_by_tags(amount=100, use_smart_hashtags=True)
        # session.follow_user_followers(['martingarrix', 'mikewilliamsdj'], amount=5, randomize=True)
        session.unfollow_users(amount=50, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', onlyNotFollowMe=True, sleep_delay=60)
        session.interact_user_followers(['martingarrix'], amount=100, randomize=True)

finally:
    # end the bot session
    session.end()

**Comment by michaloslav** [comment]
I figured it out, the problem was that the first person on the followed list deleted his account so InstaPy was trying to unfollow an account that no longer existed. I'm going to open a feature request for this since it seems like the kind of exception that should be handled somehow

**Comment by michaloslav** [comment]
I tested it out again and for some reason, I get the same error as I did before, help!

**Comment by ximhotep** [comment]
Updating line 140 in unfollow_util.py fixed the issue for me:

log_record_all_unfollowed(username, person, logger, logfolder)

**Comment by tdkonsta** [comment]
Executing this part of quickstart.py: 

`session.unfollow_users(amount=x, onlyInstapyFollowed = True, onlyNotFollowMe=True, onlyInstapyMethod = 'FIFO', sleep_delay=x)`

Gave me this error:

`unfollow loop error log_uncertain_unfollowed_pool() missing 1 required positional argument: 'logfolder' `

so I modified instapy/unfollow_util.py line 136:
`log_uncertain_unfollowed_pool(username, person, logger) `
to
`log_uncertain_unfollowed_pool(username, person, logger, logfolder)`

Then executing it again raised the following error

`unfollow loop error log_record_all_unfollowed() missing 1 required positional argument: 'logfolder' `

so I modified instapy/unfollow_util.py  line 140: 
`log_record_all_unfollowed(username, person, logger)`
to
`log_record_all_unfollowed(username, person, logger, logfolder)`
 
Now it works like a charm

Not sure if it's related to #1394

**Comment by condomfighters** [comment]
thanks, tdkonsta & ximhotep for the great help!
unfortunately the problem is not solved 100% for me
Every time the bot passes on someone's profile where the button is on "Requested" it stops and crashes
I think we should find a way to skip or ignore profiles that are deleted & on Requested.
Because I don't want to hijack this issue I made a new one (https://github.com/timgrossmann/InstaPy/issues/1508)

Thanks again for the help

**Comment by MrBeardedGuy** [comment]
I believe we can close this. It was solved here https://github.com/timgrossmann/InstaPy/pull/1521

**Comment by michaloslav** [comment]
@MrBeardedGuy You're right, I downloaded the last version of InstaPy and it works fine
Thanks to everyone who replied here
