### ISSUE TITLE
Send Keys don't work 

### ISSUE THREAD

**Issue by Caradepastel** [InstaPy/InstaPy#1488]
When I get the part "browser.find_element_by_tag_name", the code does not work. 
Please, can anyone help me?

`from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

browser = webdriver.Chrome ('C:\Webdrivers\chromedriver.exe')
browser.get("https://www.instagram.com/accounts/login/")

username = browser.find_element_by_name('username')
username.send_keys('username')

password = browser.find_element_by_name('password')
password.send_keys('password')

browser.find_element_by_xpath("//button[contains(.,'Entrar')]").click()

body_elem = browser.find_element_by_tag_name("body")

for _ in range(3):
    body_elem.send_keys(Keys.END)
    sleep(2)
    body_elem.send_keys(Keys.HOME)
    sleep(2)
`

**Comment by uluQulu** [comment]
hi @ArielEcker 
have a look at `click_element()` function in **util.py** and try to click your element similarly within its JS class instead of Selenium's `click()` or `send_keys('\n')`
```python
browser.execute_script("document.getElementsByClassName('" +  element.get_attribute("class") + "')[0].click()")
```
_and for scrolls, too, executing JS commands is better..._
