### ISSUE TITLE
comment util

### ISSUE THREAD

**Issue by jukedd** [InstaPy/InstaPy#1489]
## Expected Behavior
comment
## Current Behavior
crash

"C:\Users\xxx\Desktop\InstaPy-master (1)\InstaPy-master\instapy\comment_util.py", line 66, in comment_image
 logger.info("--> Commented: {}".format(rand_comment.encode('utf-8')))
 UnicodeEncodeError: 'utf-8' codec can't encode characters in position 19-22: surrogates not allowed

**Comment by uluQulu** [comment]
it seems to be in Windows side, what is your console's default encoding (if you have changed) & console font (default raster fonts or some truetype) and also python version?

**Comment by balakedev** [comment]
getting this too
