### ISSUE TITLE
instapy crashed?

### ISSUE THREAD

**Issue by anoirinoh** [InstaPy/InstaPy#1492]
Hi,
I am running instapy script on my pc, it works good but it stops after a time I don't know why and should i run it manually from the CMD every time it stoped? and what push it to stop? here is what i get:

 ```
Traceback (most recent call last):
  File "booom.py", line 62, in <module>
    session.like_by_tags(['#catsofinstagram', '#catstagram', '#instacat', '#catlover', '#kitty' '#kitten', '#catoftheday', '#meow', '#kittens', '#catsagram', '#ilovemycat', '#catlovers', '#pets', '#cats_of_instagram', '#lovecats', '#petstagram', '#bestmeow', '#catsofig', '#instagramcats', '#cutecat', '#cat_features', '#kittycat', '#instacats'], amount=10, media='Photo')
  File "C:\Users\Anoirinoh\Documents\instabots\InstaPy-master\instapy\instapy.py", line 692, in like_by_tags
    self.logger)
  File "C:\Users\Anoirinoh\Documents\instabots\InstaPy-master\instapy\like_util.py", line 483, in check_link
    "return window._sharedData.entry_data."
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: chrome=64.0.3282.167)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)


C:\Users\Anoirinoh\Documents\instabots\InstaPy-master>[10652:10012:0223/202115.780:ERROR:latency_info.cc(158)] RenderWidgetHostImpl::OnSwapCompositorFrame, LatencyInfo vector size 827 is too big.
```
Also I want to increase following limit, how to do it? Thank you very much. 
Note: I am running the bot since a month now.

**Comment by ghost** [comment]
Interesting, same happened to me since yesterday. I've been having multiple errors which I've fixed over the past couple of months. For instance, changing back to older chromedrivers and an installing an older version of chrome, and keeping chrome from updating itself. But for the past week I had everything fixed, no issue, and I have the same error as you. It starts with Traceback. 
(Session info: chrome=62.0.3202.75)
 (Driver info: chromedriver=2.32.498550 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)

Anybody know a fix?

**Comment by mehrab-wj** [comment]
same happened to me and i can't fix them
if anybody can fix it please help us!

**Comment by ghost** [comment]
Mehrab, try out different versions of chrome-drivers, maybe one works. It worked for me to just try a couple out.

**Comment by mehrab-wj** [comment]
@Noodlesstom what version you are use now ?
