### ISSUE TITLE
Less users to follow than requested - while Interacting with someone else followers

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#1493]
So this happens  if I use the following configuration (latest Chrome and driver):

`session = InstaPy(username='', password='')
session.login()
session.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')
session.set_do_like(enabled=True, percentage=100)
session.set_do_comment(enabled=True, percentage=30)
session.set_do_follow(enabled=True, percentage=30, times=1)
session.set_comments([ 'comments'])
session.set_upper_follower_count(limit=2000)
session.interact_user_followers(['user1'], amount=100)
session.end()`

![2222222](https://user-images.githubusercontent.com/36073534/36629008-2e396560-1948-11e8-93e3-c92807aa85b6.jpg)

As you can see it skips some users on the ground of not having enough followers (though all of them have thousands), then shows the same warning for a 3rd one - and starts working on 470 (random each time), though was asked only for 100. Sometimes it returns this error for all the usernames, and just stops.

Would be grateful for help @uluQulu :)!

**Comment by uluQulu** [comment]
hi @Tachenz 
I tried to edit **minimally**
open up `unfollow_util.py` and modify `get_given_user_followers()` function like this:
**replace**
```python
if amount >= len(follow_buttons):
    amount = len(follow_buttons)
    logger.warning("{} -> Less users to follow than requested."
        .format(user_name))
```
**with**
```python
counted_buttons = len(follow_buttons)
try_again = 0
if amount > allfollowing:
    amount = allfollowing
    logger.info("{} -> Less users to follow than requested."
        .format(user_name))
while amount > len(follow_buttons):
    scroll_bottom(browser, dialog, 6)
    follow_buttons = dialog.find_elements_by_xpath(
        "//div/div/span/button[text()='Follow']")
    sleep(3)
    if counted_buttons == len(follow_buttons):
        try_again += 1
        if try_again > 2:
           amount = len(follow_buttons)
           logger.info("{} -> Failed to load desired amount of users."
               .format(user_name))
           break
    else:
        counted_buttons = len(follow_buttons)
        try_again = 0
```
**This** **should** **solve** the issue of getting **less** usernames than desired **for** `interact_user_followers()` feature

_Also, in the output, it shows you the sum of all collected links, so if you have 4 users to interact and with amount of 100, expect it to output `Users: 400`
This doesn't mean it gets 400 usernames from one user you have given, but it is just the total of the links it took from all of the users (100 from each of 4)..
And it starts interactions after getting all of the links from all users.._

> I have not tested, if not works, please notify to check again :_)

**Comment by Tachenz** [comment]
Thank you @uluQulu tried that - but getting an error:
while amount > len(follow_buttons):

Syntax Error: invalid syntax

**Comment by uluQulu** [comment]
@Tachenz 
what is the full traceback?

**Comment by cemaytekin** [comment]
same problem here as well says syntax error

**Comment by Tachenz** [comment]
hey @uluQulu , here is the full traceback of that one! 
![error](https://user-images.githubusercontent.com/36073534/36842613-198e2a92-1d44-11e8-8521-518fd34affc0.jpg)

**Comment by uluQulu** [comment]
Zzz ... @Tachenz @cemaytekin
there is a surplus **opening brace** in the logger line before that __while statement__
```python
logger.info(("{} -> Less users to follow than requested."
        .format(user_name))
```
**will be**
```python
logger.info("{} -> Less users to follow than requested."
        .format(user_name))
```
>Python has crazy error reporting and I really got problems with these sytax errors 💤

__I also have updated that problematic line in the post above__
