### ISSUE TITLE
Session not defined

### ISSUE THREAD

**Issue by AlexLamprianidis** [InstaPy/InstaPy#1497]
I get this error every time I run python quickstart.py
`Traceback (most recent call last):
  File "quickstart.py", line 26, in <module>
    session.end()
NameError: name 'session' is not defined
`

This on raspberry pi 3
Running apt show chromedriver returns a version of 63.0.3239.84-1~deb9u1

**Comment by mikestan** [comment]
I had same problem and got this to work by following this thread: https://www.raspberrypi.org/forums/viewtopic.php?t=194176

Essentially, the chromedriver for Raspberry Pi OS wasn't right (I did an update before installing InstaPy) and also the first library in the link wasn't installed (second two were)... 

I also set headelss_browser=True in quickstart.py.

Maybe just a setup /doc issue?

**Comment by AlexLamprianidis** [comment]
Unpacking chromedriver from the link does nothing (unzips other zipped files)

Also I cant install libwebpmux2

> Package libwebpmux2 is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'libwebpmux2' has no installation candidate

**Comment by AlexLamprianidis** [comment]
I get this error 

> Traceback (most recent call last):
>   File "quickstart.py", line 13, in <module>
>     headless_browser=True)
>   File "/home/pi/Instagram2/InstaPy/instapy/instapy.py", line 142, in __init__
>     self.set_selenium_local_session()
>   File "/home/pi/Instagram2/InstaPy/instapy/instapy.py", line 230, in set_selenium_local_session
>     chrome_options=chrome_options)
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
>     desired_capabilities=desired_capabilities)
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
>     self.start_session(desired_capabilities, browser_profile)
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
>     response = self.execute(Command.NEW_SESSION, capabilities)
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: session not created exception: Chrome version must be >= 61.0.3163.0
> 
With this quickstart.py

> from instapy import InstaPy
> 
> insta_username = 'name'
> insta_password = 'pass'
> 
>  set headless_browser=True if you want to run InstaPy on a server
> try:
>     # set these if you're locating the library in the /usr/lib/pythonX.X/ directory
>     # Settings.database_location = '/path/to/instapy.db'
> 
>     session = InstaPy(username='insta_username',
>                       password='insta_password',
>                       headless_browser=True)
>     session.login()
>     # settings
>     session.set_upper_follower_count(limit=6500)
> 
>     # actions
>     session.like_by_tags(['tag1', 'tag2', 'tag3'], amount=1)
>     session.end()
> finally:
>     # end the bot session
>     print('ok')
>

**Comment by mikestan** [comment]
@alexlab963, one thing I also always do is update my Raspberian OS before giving my pi a new use. Here's the page on how to do that: https://www.raspberrypi.org/documentation/raspbian/updating.md. I suspect something's out of date (or missing).

Even with your quickstart.py file this runs on my RPi 3, so you might try blowing away your InstaPy folder and doing another git, essentially doing the basic setup again: https://github.com/timgrossmann/InstaPy#basic-installation (don't forget to grab the chrome driver, but get the Debian one I said above.

**Comment by riccardorighettiphoto** [comment]
Did you install chromium? You should install it along with chromedriver.

**Comment by AlexLamprianidis** [comment]
As  a matter of fact, I did, thats where I am posting on github from. I have tried installing instapy multiple times already.

**Comment by mikestan** [comment]
I also noticed a typo in the quickstart.py file you pasted: remove the tickmarks around the variable names, insta_username and insta_password in the session block. It should read like this because you defined them above ('name' and 'pass' are your login credentials, right?):

```
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)
session.login()
```

Having the ticks would give you a different error than you posted, though.

Here's the file I successfully used (indenting is important, too):
```
from instapy import InstaPy

insta_username = 'my_ID'
insta_password = 'my_pass'

#set headless_browser=True if you want to run InstaPy on a server
try:
# set these if you're locating the library in the /usr/lib/pythonX.X/ directory
# Settings.database_location = '/path/to/instapy.db'

    session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

    session.login()
    # settings
    session.set_upper_follower_count(limit=6500)

    # actions
    session.like_by_tags(['tag1', 'tag2', 'tag3'], amount=1)
    session.end()
finally:
# end the bot session
    print('ok')
    session.end()
```

**Comment by AlexLamprianidis** [comment]
Thats basically saying that my username is insta_username and my pass is insta_pass, shouldn't give any errors at all, just a wrong login credentials message

**Comment by mikestan** [comment]
Sort of. What you had pasted as your config file said, 

- _set my username and password to 'X' and 'Y' (on line 3 and 4)_
- _use literal string 'username' and 'password' for your login credentials <-- these need to **not** have the tick marks around them on lines 11 and 12_

Python is case- and indent-sensitive, too. Basically, try my config file above and replace my_ID and my_pass with your login credentials.
