### ISSUE TITLE
Hey !!

### ISSUE THREAD

**Issue by roothaxor** [InstaPy/InstaPy#15]
Please add requirements list for ease, thankyou

**Comment by timgrossmann** [comment]
I'm not sure if i can follow you...

Everything needed is explained in the readme 

```bash
pip3.5 install selenium
pip3.5 install git+git://github.com/Clarifai/clarifai-python.git
```

**Comment by renatoalencar** [comment]
It's important to add this in order to keep a compatible version listing of the libs, and this is a community pattern.

**Comment by timgrossmann** [comment]
@renatoalencar ahh ok, thank you!
I'll add that as soon as possible.

**Comment by timgrossmann** [comment]
added at #17
