### ISSUE TITLE
session.set_ignore_users([currentfriendlist(?)])

### ISSUE THREAD

**Issue by elmarcomilani** [InstaPy/InstaPy#1503]
Hi,

is it possible to ignore all current followers? I don't want to like pictures from my old mates whose I've been following since 2010 and now suddenly I like a pic of theirs, that's really awkward, is there a way to prevent this? Something like session.set_ignore_users() but for ALL friends I already follow?

**Comment by sionking** [comment]
yes there is I use pickle to store list of my current following

**Comment by sionking** [comment]
and capture them with GRAPHQL

**Comment by elmarcomilani** [comment]
Could you post your code, please?

**Comment by elmarcomilani** [comment]
Instabot has a simple function like: `bot.get_user_following("username")`.
It's weird that InstaPy doesn't have any or am I looking at the wrong wiki?
