### ISSUE TITLE
error: selenium.common.exceptions.TimeoutException: Message: timeout

### ISSUE THREAD

**Issue by riccardorighettiphoto** [InstaPy/InstaPy#1504]
Hello,
I recently received an unexpected session end before the completion with this error message:
`selenium.common.exceptions.TimeoutException: Message: timeout`
Any idea?

Thank you.

**Comment by riccardorighettiphoto** [comment]
Hello,
I continue to get this error, I gues about 1 time every three runs. Does anyone know what is the matter?

**Comment by riccardorighettiphoto** [comment]
This morning (3:00 AM) again this issue. It is more time I cannot get it working than times I get working... really frustrated.
Any idea?

This is the log error:
`Traceback (most recent call last):
  File "./quickstart.py", line 30, in <module>
    session.like_by_tags(['tag_1', 'tag_2', 'tag_3'], amount=100)
  File "/home/my_username/InstaPy/instapy/instapy.py", line 846, in like_by_tags
    self.logger)
  File "/home/my_username/InstaPy/instapy/like_util.py", line 490, in check_link
    browser.get(userlink)
  File "/usr/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 3.10.0-514.21.1.el7.x86_64 x86_64)`

**Comment by kushpvo** [comment]
Started getting the same error.

**Comment by Ericwonne** [comment]
The same error on python selenium crawler tool. Finding ways...

**Comment by issamarmas** [comment]
same

**Comment by eneasz** [comment]
+1

**Comment by minh-bui-solibri** [comment]
Same error running UI integration test with python. I did not get any error until one certain unit test. The code for other unit test are basically the same and they all work.

**Comment by MinhDBui** [comment]
Same error running UI integration test with python. I did not get any error until one certain unit test. The code for other unit test are basically the same and they all work.
