### ISSUE TITLE
'liked_img' referenced before assignment

### ISSUE THREAD

**Issue by alexsmedile** [InstaPy/InstaPy#1505]
```
Traceback (most recent call last):
  File "InstaList_v3.py", line 165, in <module>
    instalist()
  File "InstaList_v3.py", line 161, in instalist
    bot.interact_by_users(users_list, amount=1, randomize=False)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 1280, in interact_by_users
    self.liked_img += liked_img
UnboundLocalError: local variable 'liked_img' referenced before assignment
```

**Comment by MrBeardedGuy** [comment]
Just had the same issue...  I've found this thread. It might be useful https://stackoverflow.com/questions/10851906/python-3-unboundlocalerror-local-variable-referenced-before-assignment

You might try to use global variables to fix the issue.... you can simply add:

`global Var1, Var2`

**Comment by alexsmedile** [comment]
@MrBeardedGuy Thank you. I understand the ussue (in a logical manner), but I'm not able to fix it. I'm a noob. I tryed to find the error in `instapy.py`, but I think there are only local variables. I don't know why the code doesn't work.

Reference:
https://github.com/timgrossmann/InstaPy/blob/245abd05b1677cc117dac86abc785989f6f51efb/instapy/instapy.py#L1280

**Comment by heyimjames** [comment]
also having this issue 😩
