### ISSUE TITLE
#quickstart.py error

### ISSUE THREAD

**Issue by drcyber975** [InstaPy/InstaPy#1507]
Can anyone explain why quickstart.py isnt working? Eeverytime i try to use quickstart.py I receieve an error messages saying session is not defined.   session.login() and session.end() are not working for some reason. Below is the code i used it is exactly the same as quciksatart.py i added in my usdername and password correctly. And at the very bottom was the rror messages i recieve. Please help me I have no idea how to tackle this issue asI am using correct commands. Eeverything is installed correctly, I have got this to work before but cant seem to understand why its not working now. 

from instapy import InstaPy

insta_username = 'username'
insta_password = 'password'

# set headless_browser=True if you want to run InstaPy on a server
try:
    # set these if you're locating the library in the /usr/lib/pythonX.X/ directory
    # Settings.database_location = '/path/to/instapy.db'
    # Settings.browser_location = '/path/to/chromedriver'
    
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      multi_logs=True)
    session.login()

    # settings
    session.set_upper_follower_count(limit=2500)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.like_by_tags(['natgeo'], amount=1)

finally:
    # end the bot session
    session.end()

lubuntu@lubuntu:~$ cd
lubuntu@lubuntu:~$ cd InstaPy
lubuntu@lubuntu:~/InstaPy$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 32, in <module>
    session.end()
NameError: name 'session' is not defined
lubuntu@lubuntu:~/InstaPy$

**Comment by drcyber975** [comment]
can anyone help?

**Comment by liamcloss** [comment]
Are you running this from CLI?

What response do you get if you try and print the session object?
