### ISSUE TITLE
ERROR unfollow loop error log_uncertain_unfollowed_pool() missing 1 required positional argument: 'logfolder'

### ISSUE THREAD

**Issue by condomfighters** [InstaPy/InstaPy#1508]
## Expected Behavior
unfollow or skip private accounts
## Current Behavior
ERROR unfollow loop error log_uncertain_unfollowed_pool() missing 1 required positional argument: 'logfolder'
## Possible Solution (optional)
Skip or click on the "requested" button
## InstaPy configuration
Hi there,
I love instapy and it is amazing how well it works.
Since I'm still a noob in python i would love to have your help in this issue
When I run a script to unfollow profiles the bot crashes and shows the following error: 
ERROR [2018-02-27 14:13:46] [myname]  unfollow loop error log_uncertain_unfollowed_pool() missing 1 required positional argument: 'logfolder'
the reason why this happens is because some accounts are private and the button is still on "requested".
I would like to change the script so it automatically skips these profiles or just unfollow them by clicking on the request button.
How should I proceed with doing this?
I already added "logfolder" in unfollow_util in line 140 and it fixed some other errors but not this one
thank you in advance!

**Comment by ikillfairies** [comment]
The currently checked in version of unfollow_util.py is missing `logfolder` from `log_uncertain_unfollowed_pool` and `log_record_all_unfollowed` on lines 154 and 158. If you add them it should work.

**Comment by condomfighters** [comment]
thanks a lot, ikillfairies !
worked perfectly.
however, it opens 3 blank commands prompts for some reason.
