### ISSUE TITLE
InstaPy on RaspberryPi 3 won't run

### ISSUE THREAD

**Issue by skaeslin** [InstaPy/InstaPy#1510]
Hello everyone

I'm a total newbie to all of this. Luckily I made it trough your installation guide for the Raspberry and everything went pretty good.

In the end I added my instagram username and password and tried to run it. (I opened the quickstart.py and pressed "run"). But nothing happened. Not even an error appears. What did I do wrong? Or how can I fix this?

I thank you all a lot in advance for your help! :)

**Comment by gitpatrickhub** [comment]
Open a Terminal session and change directory to InstaPy and then;

```
sudo python quickstart.py
```

depending on what versions of python you installed;
```
sudo python3 quickstart.py
```

If you are running headless with XVFB and python3,
```
sudo xvfb-run python3 quickstart.py
```

**Comment by skaeslin** [comment]
It worked! Thanks a lot! Really cool to see it work! :D 
Is there also a possibility to run it 24/7 on the raspberry pi 3 (rasbian) ?

**Comment by gitpatrickhub** [comment]
@skaeslin search the issues for scheduling or 24/7 and you will see how others have implemented it.

**Comment by imbarismustafa** [comment]
Hey. How did u manage to install on raspberry pi 3? I am getting error for python imaging. It says that my sources.list is empty.

**Comment by skaeslin** [comment]
@gitpatrickhub 
Thank you! Did that and tried with cron. But somehow I can't get it to work 
My cron looks like this:

"* 21 * * * cd Projects/instapy && sudo xvfb-run python quickstart.py# 

I don't know. It worked for others...

**Comment by skaeslin** [comment]
@imbarismustafa
I managed to install on raspberry pi with the read me. I don't know how to solve your problem.

**Comment by imbarismustafa** [comment]
managed to make it somehow. now is working and i am trying to learn and combine the comments. If you guys have any recommendations i will be so happy to try them.
