### ISSUE TITLE
NameError: name 'Settings' is not defined

### ISSUE THREAD

**Issue by indigoelite13** [InstaPy/InstaPy#1514]
Hi! I've followed the guide and installed instapy on windows. Have chrome driver in the assets folder in both 'chromedriver' and 'chromedriver.exe' format (read somewhere that that might have been the issue). Any help is absolutely welcome! 😄

**Comment by tnarue** [comment]
try editing settings.py inside instapy

change path of browser_location from "./assets/chromedriver" to your chromedriver direct path and do the same thing with database location

Hope it works! This solution solved my case!

**Comment by indigoelite13** [comment]
Hi, tnarue! thank you for helping out. Tried it out didn't help in my case. Error still comes back "Error: NameError: name 'Settings' is not defined" 😭
