### ISSUE TITLE
Refuses to follow by tag

### ISSUE THREAD

**Issue by granddaddysmoke** [InstaPy/InstaPy#1517]
INFO [2018-02-28 20:45:17] [gds_real]  --> User not followed: None
INFO [2018-02-28 20:45:17] [gds_real]  [2/100]
INFO [2018-02-28 20:45:17] [gds_real]  https://www.instagram.com/p/Bfwzczmj2ua/?tagged=twitch
INFO [2018-02-28 20:45:19] [gds_real]  Image from: b'osrs_alan'
INFO [2018-02-28 20:45:23] [gds_real]  Number of Followers: 401
INFO [2018-02-28 20:45:23] [gds_real]  Link: b'https://www.instagram.com/p/Bfwzczmj2ua/?tagged=twitch'
INFO [2018-02-28 20:45:23] [gds_real]  Description: b'You feel you can win, then you go back to Lumbridge!\xf0\x9f\x98\x81\xf0\x9f\x98\x81\xf0\x9f\x98\x81\n_\n_\ntags: #runescape #runescape3 #runescape2007 #runescape07  #runescapegirl #oldschoolrunescape #osrs #osrs2007 #osrs07 #pc #itslit #twitchtv #play #mmorpg #twitch #rs07 #gamer #leagueoflegends #counterstrike #pcgamer #pubg #overwatch #fifa #oldschoolrs #csgo #games #rs3 #jagex #game'
INFO [2018-02-28 20:45:23] [gds_real]  --> User not followed: None
INFO [2018-02-28 20:45:23] [gds_real]  [3/100]
INFO [2018-02-28 20:45:23] [gds_real]  https://www.instagram.com/p/BfwzjHpFz-x/?tagged=twitch
INFO [2018-02-28 20:45:26] [gds_real]  Image from: b'misterwirruclown'
INFO [2018-02-28 20:45:30] [gds_real]  Number of Followers: 754
INFO [2018-02-28 20:45:30] [gds_real]  Link: b'https://www.instagram.com/p/BfwzjHpFz-x/?tagged=twitch'
INFO [2018-02-28 20:45:30] [gds_real]  Description: b'My livestream is now offline but will probably livestream again tomorrow\xf0\x9f\x98\x89 #livestream #streamer #gamer #game #onlinegame #gamerboy #twitch #online #live #overwatch #gameplay #lvling #blizzard #battlenet #twitchtv #worldofwarcraft'
INFO [2018-02-28 20:45:30] [gds_real]  --> User not followed: None
INFO [2018-02-28 20:45:30] [gds_real]  [4/100]
INFO [2018-02-28 20:45:30] [gds_real]  https://www.instagram.com/p/BfwzhDah-BO/?tagged=twitch
Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    session.follow_by_tags(['twitch', 'twitchstreamers'], amount=100)
  File "C:\Users\GrandDaddySmoke\Desktop\InstaPy-master\instapy\instapy.py", line 1813, in follow_by_tags
HELP :(

**Comment by MrBeardedGuy** [comment]
Have you checked this? https://github.com/timgrossmann/InstaPy#followunfollowexclude-not-working

**Comment by ghost** [comment]
I'm getting the same issue. I've looked at that same thing MrBeardedGuy and it did not fix it. Even if it put that line of code in the beginning or end of the script.
