### ISSUE TITLE
BUG or Instagram issue  -- Super Strange behavior on Likes recently  

### ISSUE THREAD

**Issue by CharlesCCC** [InstaPy/InstaPy#1519]
This is a really strange problem, I'm not sure how many of you have noticed(since it is so hard to notice). 
I have two of my account running on my personal computer with multiple_logs set to true. 

In the past 2-3 days, I have noticed something super strange happening. I confirmed by observer the script run on my computet screen and checking on my phone at the same time. 

here is the issue:

Account1 is running with the script with the following setting:
```
		session = InstaPy(username=insta_username,
						  password=insta_password,
						  headless_browser=False,
						  bypass_suspicious_attempt=False,
						  multi_logs=True)
		session.login()
		
		# settings
		session.set_upper_follower_count(limit=1000)
		session.set_lower_follower_count(limit=25)
		session.set_do_follow(enabled=follow, percentage=10, times=1)
		session.set_do_comment(True, percentage=10)
		session.set_comments("awesome, great")
		session.unfollow_users(amount=10, onlyInstapyFollowed=True, onlyInstapyMethod = 'FIFO', sleep_delay=60)
		session.set_smart_hashtags([Drone,Photography], limit=10, sort='top', log_tags=True)
		session.like_by_tags(amount=20, use_smart_hashtags=True)

```
I logged Account2 on my phone which has followed Account1.

I kick off the script for account1, make sure the account1 liked one of the image for UserA, I see the webpage showing it being liked. And then I pull up my phone using Account2 to check the "Following Activities",  Account1's like didn't showing under there (which previously always shows). And then I manually typed the UserA name in the search box and find the one image that was being liked, nothing. the Account1 didn't show up under the liked list.  Even though I saw it been liked by the script on the webpage with my own eye.  
 
I would like to see if anybody have noticed this behavior or not, the reason why I did this, is because recently I have noticed there are much less likes and follows from the daily check. even thought the number of likes showing under the `general` log shows the same amount as before. 

I'm not sure if this is a bug in the script or it is something Instagram did to prevent automated activites like this.

**Comment by sionking** [comment]
I have fixed it in my code, instagram changed the method
If you do like but you liked banned, you will still see the like on webpage but if you refresh it will disappre.
I did check "reload the page" in randomly each 5  likes, and if after reload the like disapper I stop to script for 1 hour, it works great !

**Comment by stainless33** [comment]
@CharlesCCC  If I run the script a few times in a day on the same account it appears to become inoperable for that specific account. I can switch to a different account and it'll work fine, so I know it's not the script. But it's as if Instagram has blocked the script because it has recognized a pattern. I'm still able to like images manually and my account isn't 'banned' but maybe new restrictions have been imposed because of the automated behaviour.

**Comment by CharlesCCC** [comment]
@sionking  so it sounds like there is a "soft" banned from Instagram side, When I say "soft" banned, it meant the user still able to like the image through the phone app, relative to "hard" banned, which is not able to  interact with user at all, not even through the phone app. 

I guess the issue sounds like my account might have liked too many images per day, I knew in the wiki it says don't like 1000 image per day, I did my calculation, i have schedule it to run 12 times per day and it likes about 200 image per run, so it like 2400 likes per day(probably far over it limit). 

I'm wondering what the total amount of likes has been given each day for your account @sionking and @stainless33 and @anthonyattard 

Maybe we can find a similar pattern. 

anyway, I did decrease the amount of like to about 100 likes each run, we will see if this gonna help.

**Comment by CharlesCCC** [comment]
Guys, I confirmed my setting was too aggressive.  Make sure never like more than 100 per hour and like more than 2400 per day. When I think about it, it only 1440 minutes per day. no human being is capable like 2400+ pic per day 24X7... it just not realistic.

**Comment by stainless33** [comment]
@CharlesCCC  I only run the script 2-3 times per day, but my mistake was probably increasing the number of likes to 250 per run. I've been trying to find the correct numbers and some resources say that the hourly maximum is 350, but from what I have experienced, this clearly cannot be correct.

**Comment by CharlesCCC** [comment]
@stainless33 that make sense, As I mentioned from the previous message, don't go over 100 per hour, schedule it to run couple more times should be okay. so smaller batch, but multiple batches.

**Comment by stainless33** [comment]
@CharlesCCC Cheers. I'll have to try it out and set up a cron to get that going then. Haven't been able to sort it yet as it doesn't seem to want to run.

**Comment by MrBeardedGuy** [comment]
Maybe it's a dumb question but how can you know the total number of likes? Should you derive it from all the functions in your intsapy code? Isn't there a better way to spit out this number? 

Looking at CharlesCCC I see
**10x2 tags here** 
`session.set_smart_hashtags([Drone,Photography], limit=10, sort='top', log_tags=True)`
**20x(10x2) = 400 likes per run**
`session.like_by_tags(amount=20, use_smart_hashtags=True)`

Assuming it ran 12 times a day, that's **400x12= 4800 likes (200 likes a day)!!!**

This is kinda a tricky calculation to do. especially if you're randomizing the amount every pass. Is there a way to calculate all this stuff automagically and maybe store it in the DB??

**Comment by CharlesCCC** [comment]
@MrBeardedGuy you can tell from the log
```
INFO - Liked: 93
INFO - Already Liked: 0
INFO - Inappropriate: 75
INFO - Commented: 13
INFO - Followed: 7
INFO - Session ended - 2018-02-17 07:10:50
INFO - --------------------
```
So, even thought I set the total amount is like 400 per run, but in reality, about 40-50% of the images didn't get liked due to `inappropriate`. the main reason it is been `inappropriate` is because their followers is not within the limit I set (25 - 1000 followers).  Anyway, that is another issue need be addrssed for sure. 

@MrBeardedGuy After one more day of testing, I have noticed the issue still persist. Basically, I currently have it running for small batch (50~ likes per run) and it only getting like 10-20 likes per run. afterwards, it went to the `soft` banned state again. 

maybe @sionking  can provide a little bit more insight.

**Comment by stainless33** [comment]
@CharlesCCC I can confirm that aiming for 50 likes in a single session provides my account with a soft ban for 24 hours. Maybe there needs to be more of a delay between likes?

**Comment by CharlesCCC** [comment]
@stainless33 that doesn't make sense. Can you please post your configure along with the latest stats output from generallog to here as I did?

**Comment by sionking** [comment]
I have 15 account non got banned, but real accounts connected to same ip with the phone app.
I have my own supervision limits, not more than ~100 per hour (likes) and total 1200 a day.
I do get soft banned for 1-2 hour sometimes,  so I stop the run when this happen
This is my like image code:

```
def like_image(browser, username, blacklist, logger, logfolder):
    """Likes the browser opened image"""
    like_elem = browser.find_elements_by_xpath(
        "//a[@role='button']/span[text()='Like']/..")
    if len(like_elem) == 1:
        # sleep real quick right before clicking the element
        sleep(2)
        click_element(browser, like_elem[0])
        logger.info('--> Image Liked!')
        update_activity('likes')
        if blacklist['enabled'] is True:
            action = 'liked'
            add_user_to_blacklist(
                browser, username, blacklist['campaign'], action, logger, logfolder
            )
        sleep(2)
        # like element seems to be clicked but it not really so we should check
        if random.randint(1, 5) == 1:
            # to see if really liked we need to refresh
            browser.execute_script("location.reload()")
            sleep(2)
            # check now we have unlike instead of like
            liked_elem = browser.find_elements_by_xpath(
                "//a[@role='button']/span[text()='Unlike']")
            if len(liked_elem) == 1:
                return True
            else:
                # if like not seceded wait for 60 min
                msg = '--> Image was not able to get Liked! maybe blocked ?'
                logger.warning(msg)
                send_telegram_msg(msg, logfolder)
                sleep(3600)
        else:
            return True
    else:
        liked_elem = browser.find_elements_by_xpath(
            "//a[@role='button']/span[text()='Unlike']")
        if len(liked_elem) == 1:
            logger.info('--> Image already liked! ')
            return False

    logger.info('--> Invalid Like Element!')
    return False
```

**Comment by ghost** [comment]
sionking, thanx, it is better way to check if we are really liked image!

**Comment by CharlesCCC** [comment]
@sionking great idea, I believe similar logic could/should be applied during `following`. (from this issue #1541 )

**Comment by anthonyattard** [comment]
@CharlesCCC I was running 11 times per day with a random number of likes between 10-25 for 11 tags. So on average 17.5 (likes per tag) * 11 (times per day) * 11 (tags) = 2,150 per day. But I have filters in place like followers limit etc so it's probably closer to 1,500 per day in my estimation. Still that is far beyond what I thought I had set so I'm going to lower the number of likes and see if that fixes things.

**Comment by SDKFJ55LDK8K2** [comment]
Guys guys guys woooow. 

The limits are most definitely way lower then all of this... if your liking 2400 or 1500 or ... your account has most definitely red flags and gets degraded therefore limiting your reach in a very subtle way. 

The limits are for each account different based on the amount of followers, previous red flags and bans, amount of engagement, the niche that you're in, etc. 

For the majority of accounts the like limits are in between 300- 500 likes a day at the moment of writing. The follow limits are even lower. Old accounts with engagement rates of 1000+ likes a post have higher limits but if you have a young account of a few thousand followers with around 200 likes a post the limits are pretty restricted. 

It also depends on what and when you like... If you for example like images of your followers right after posting a post to trigger engagement the red flags kick almost immediately in...

**Comment by anthonyattard** [comment]
I have changed Digital Ocean servers to get around ban. I have also set max like count to 275 per day. Will report back if it works. Thanks for the advice @SDKFJ55LDK8K2

**Comment by CharlesCCC** [comment]
@SDKFJ55LDK8K2 I'm just curious how did you get those numbers from ?
`For the majority of accounts the like limits are in between 300- 500 likes a day at the moment of writing. The follow limits are even lower. Old accounts with engagement rates of 1000+ likes a post have higher limits but if you have a young account of a few thousand followers with around 200 likes a post the limits are pretty restricted.`
