### ISSUE TITLE
Error when image has no caption

### ISSUE THREAD

**Issue by taihoang** [InstaPy/InstaPy#152]
I got this.

> Traceback (most recent call last):
>   File ".\quickstart.py", line 23, in <module>
>     .like_by_tags(['landscape'], amount=97) \
>   File "C:\Users\em\Desktop\InstaPy-master\instapy\instapy.py", line 271, in like_by_tags
>     self.username, self.like_by_followers_upper_limit, self.like_by_followers_lower_limit)
>   File "C:\Users\em\Desktop\InstaPy-master\instapy\like_util.py", line 144, in check_link
>     image_text = image_text[0]['nodes']['text'] if image_text else None
> KeyError: 'nodes'

**Comment by pekapa** [comment]
Fixed by PR #159 
Let us know if it completely solves for you.
