### ISSUE TITLE
Except get_media! ERROR

### ISSUE THREAD

**Issue by saily89** [InstaPy/InstaPy#1522]
## Current Behavior

Hello, I am having issues with my bot. I log in and all I am getting is this:

Except on get_media!
Get media id by tag: holyspirit
Except on get_media!
Get media id by tag: worship
Except on get_media!
Get media id by tag: mercy
Except on get_media!
Get media id by tag: christian
Except on get_media!
Get media id by tag: inspirational
Except on get_media!
Get media id by tag: teamjesus
Except on get_media!
Get media id by tag: inspirational
Except on get_media!
Get media id by tag: proverbs31woman
Except on get_media!

please help!

**Comment by MrBeardedGuy** [comment]
Can you plz post your Instapy code as well
