### ISSUE TITLE
Instapy Chromedriver is missing

### ISSUE THREAD

**Issue by nodope7** [InstaPy/InstaPy#1524]
![inst](https://user-images.githubusercontent.com/36537539/36886278-80c9c2ee-1de3-11e8-8c6f-7fc448359ef0.png)
 I have done each and every step correctly
I have copied chromedriver to assets folder
but still showing this message
im frustrated and tried all ways. Help needed

**Comment by timgrossmann** [comment]
@nodope7 Sorry to hear that, but please post this an issue at the actual GUI repository.
Thank you
