### ISSUE TITLE
Refuses to follow/like by tag 

### ISSUE THREAD

**Issue by granddaddysmoke** [InstaPy/InstaPy#1525]
So everything seems to be working fine, but when the bot gets to follow by tags and also like by tags it will do everything it should but it won't like the picture. Im pretty sure it is automaticly deeming it inaprocite maybe it has something to do with clarifai but im no expert would appreciate some help here is a example of what it is saying to me.
--> Image not liked: b'None'

**Comment by cormo1990** [comment]
Probably you can find an help here

https://github.com/timgrossmann/InstaPy/issues/1452
