### ISSUE TITLE
Error occurred when I was testing the "Interact with users that someone else is following"

### ISSUE THREAD

**Issue by chkrishnadheeraj** [InstaPy/InstaPy#1527]
## Expected Behavior
It should like the posts of the user that he/she is following
## Current Behavior
I was trying out the interacting with users that someone else is following and I got this error message
Traceback (most recent call last):
  File "quickstart.py", line 33, in <module>
    session.interact_user_following(['shriyakotta_'], amount=10, randomize=True)
  File "/home/kdtops/InstaPy/instapy/instapy.py", line 1381, in interact_user_following
    self.user_interact_media)
  File "/home/kdtops/InstaPy/instapy/instapy.py", line 1115, in like_by_users
    self.liked_img += liked_img
UnboundLocalError: local variable 'liked_img' referenced before assignment

## InstaPy configuration
Ubuntu 16.04 LTS 64bit

**Comment by andersjohansenn** [comment]
I'm having the same problem

**Comment by martinkuna** [comment]
Me too.
