### ISSUE TITLE
Stops after a few likes because of a "Error reading broker pipe".

### ISSUE THREAD

**Issue by wesleytrying** [InstaPy/InstaPy#1538]
Hello! I am new to all of this, like, completely new to this. I am running into an issue where the InstaPy likes about 15-20 pictures per session then stops. I have the amount set to 300, though. The error coming up says: "[28732:28736:0303/173630.273:ERROR:broker_win.cc(57)] Error reading broker pipe: The pipe has been ended. (0x6D)"

## InstaPy configuration

 settings
    session.set_upper_follower_count(limit=3000)
    session.set_lower_follower_count(limit=200)
    session.set_dont_like(['MAGA','blessed','godisgood','godislove','praisegod','God', 'church', 'churchlife'])

     actions
    session.like_by_tags(['pitbull', 'akita','tattoo','ink','tattooed', 'writing','puppy', 'writer', 'photography', 'pittie', 'writerscommunity', 'writerslife', 'wildlifephotography', 'elephant', 'redpanda', 'octopus','writersofig', 'SaltLakeCity', 'donut', 'inked', 'utah'], amount=300)
    session.like_by_locations(['213381527','212999109'], amount=20, skip_top_posts=True)"

Any help would be muchly appreciated, thank you!

**Comment by CodeMaster1** [comment]
I am also running into the same issue. Line no. 222 in like_util.py returns very less list of pictures. (26 in my case everytime)

**Comment by uluQulu** [comment]
hi @CodeMaster1 @wesleytrying 
have you seen #1365?
