### ISSUE TITLE
Not able to Follow anymore

### ISSUE THREAD

**Issue by CharlesCCC** [InstaPy/InstaPy#1541]
## Expected Behavior
Follow the user when the folliwng message shows:
```
INFO - --> Image Liked!
INFO - --> Commented: b'lovely ~ '
INFO - --> Now following
```
## Current Behavior

But when I manually check, it didn't actual follow. 
I have checked this block of code, everything seems okay to me:

```
def follow_user(browser, follow_restrict, login, user_name, blacklist, logger, logfolder):
    """Follows the user of the currently opened image"""

    try:
        follow_button = browser.find_element_by_xpath(
                "//button[text()='Follow']")

        # Do we still need this sleep?
        sleep(2)

        if follow_button.is_displayed():
            click_element(browser, follow_button) # follow_button.click()
            update_activity('follows')
        else:
            browser.execute_script(
                "arguments[0].style.visibility = 'visible'; "
                "arguments[0].style.height = '10px'; "
                "arguments[0].style.width = '10px'; "
                "arguments[0].style.opacity = 1", follow_button)
            click_element(browser, follow_button) # follow_button.click()
            update_activity('follows')

        logger.info('--> Now following')
        log_followed_pool(login, user_name, logger, logfolder)
        follow_restrict[user_name] = follow_restrict.get(user_name, 0) + 1
        if blacklist['enabled'] is True:
            action = 'followed'
            add_user_to_blacklist(
                browser, user_name, blacklist['campaign'], action, logger, logfolder
            )
        sleep(3)
        return 1
    except NoSuchElementException:
        logger.info('--> Already following')
        sleep(1)
        return 0
```

Maybe someone else can point me to the right direction. 

## Possible Solution (optional)

Not sure 

## InstaPy configuration

```
# set up all the settings
session.set_upper_follower_count(limit=1000)
session.set_lower_follower_count(limit=25)
session.set_do_follow(enabled=True, percentage=10, times=1)

session.set_do_comment(True, percentage=10)
session.set_comments(['lovely ~ ', 'I like It ~', 'cute ~'],media='Photo')

#session.set_dont_unfollow_active_users(enabled=True, posts=5)
session.unfollow_users(amount=5, onlyInstapyFollowed=True, onlyInstapyMethod='FIFO', sleep_delay=60)

session.set_smart_hashtags(['cat','kitty'], limit=5, sort='top', log_tags=True)
session.like_by_tags(amount=10, use_smart_hashtags=True)
```

**Comment by CharlesCCC** [comment]
It felt like Instagram preventing any automated tool to follow users, I tried manually click the "follow" link from the Automated Chrome browser window, it acting like nothing happened. but I was able to follow the same user when I'm open it from another normal Chrome browser window. ???? 

super strange.

**Comment by jeremycjang** [comment]
@CharlesCCC perhaps it's only affecting Chrome; I ran my follow program on Firefox (Pi 3) last night and it worked successfully, though I used the `follow_user_followers` program instead of your configuration to follow through `like_by_tags`.

**Comment by CharlesCCC** [comment]
@jeremyccheung it possible but so strange at the same time.

**Comment by CharlesCCC** [comment]
![screen shot 2018-03-04 at 5 02 52 pm](https://user-images.githubusercontent.com/7534809/36951526-d5638dbc-1fd2-11e8-88a9-8b524d87c60f.png)

After further investigation, it is getting 400 for the most follows, I set it to follow 10 people from `follow_user_followers`. and 1 one of 10 get actual followed, everybody else getting `400` status code even when i manually click `follow`.

**Comment by jeremycjang** [comment]
Does the request you send from a native Chrome browser look identical? There must be a difference if it’s returning different responses consistently

**Comment by CharlesCCC** [comment]
@jeremyccheung To be honestly I can't tell (I didn't compare). After two days, the amount of not able to follow seems decreased, I suspect this is one of the scenario fall into "soft" banned. because my account follow/unfollowed too much last week.
