### ISSUE TITLE
Edit quickstart.py but the bot do things that i don't want

### ISSUE THREAD

**Issue by alessiomtt** [InstaPy/InstaPy#1542]
Hi, I have edited quickstart.py with my code:

`
from instapy import InstaPy

insta_username = 'username'

insta_password = 'pass'

try:

    session = InstaPy(username=insta_username,

                      password=insta_password,

                      headless_browser=False,

                      multi_logs=True)

    session.login()

    session.set_do_comment(enabled=True, percentage=100)
    session.like_by_tags(['#suicidegirls'], amount=100)
    session.set_comments([u'Wow! \u2764 \u2764', u'\u2764', u'Cool! \u2728 \u2728'])
    
    

finally:

    

    session.end()
`

but when I run the script, the tag it's right, but the comments no (the bot comment with Looks good and something like that) and he always look for the number of followers that the users have...

**Comment by MrBeardedGuy** [comment]
It seems that this problem is due to the fact that your `set` functions are **after** `like_by_tags `

Take a look here to fix the issue https://github.com/timgrossmann/InstaPy#followunfollowexclude-not-working

**Comment by alessiomtt** [comment]
thank you so much!
