### ISSUE TITLE
💡[IDEA] Implement a `set_do_reply` function to respond to post comments received from followers

### ISSUE THREAD

**Issue by MrBeardedGuy** [InstaPy/InstaPy#1543]
## What
I'm thinking whether it's worth having some sort of function like 'set_do_comment' that replies to followers comments instead of leaving comments on someone's post. 
This function, let's call it `set_do_reply` would fetch all the comments left from my followers and would reply to all of them with a set value of canned responses (that might be set with a `set_replies` function)

## Why 
It might be interesting analyzing how followers respond when engaged in a conversation started with their own comment.

## How
```
session.set_do_reply(True, percentage=10)
session.set_replies(['Thank you  @{}!', ':heart:', 'Thanks!!!'])
```

Thoughts?

**Comment by CharlesCCC** [comment]
Great idea.

**Comment by balakedev** [comment]
love it.

**Comment by martinkuna** [comment]
Good idea

**Comment by uluQulu** [comment]
Hey @MrBeardedGuy
It's a bit late response but recently, I wrote a feature- **Interact by Comments**, that, hopefully will fulfill your request - shared at #3318 (_live PR_).

---

Cheers 😁
---
