### ISSUE TITLE
Like by Location problem

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#1544]
Hello, 
there is a problem while liking and commenting by location, it only likes 27 even if the amount is higher, any idea?  

thank you.

**Comment by andersjohansenn** [comment]
Same problem for me, updated "like_until.py" yesterday and that fixed the tag problem, but not location

**Comment by ctoveloz** [comment]
same problem here

**Comment by Edhim** [comment]
any one please ?
