### ISSUE TITLE
Wrong login Data after entering security code

### ISSUE THREAD

**Issue by userlip** [InstaPy/InstaPy#1545]
Hey just found this project and thought I'd give it a try.

I am (like many others) stuck in the verification loop but the thing is, that after I put in the code I get via email it says 
`CRITICAL [2018-03-04 23:18:27] [myaccount]  Wrong login data!`

Which obviously cannot be right as I've already gotten an email with the code and you can only do that when you are already logged in.

Any input regarding this issue is appreciated.

**Comment by mikestan** [comment]
I get this, too, and am relegated to "the way Instagram gods" do a soft ban on my account(s) when I run the scripts too aggressively. When I get that error I have to wait until the next day to run script (evident by the dreaded invalid login popup on your phone's app...

- Had this issue regularly with follow/comment combined with unfollow directives.
- Turned my headless Raspberry Pi server crontab down to run once-a-day: to like/follow (per account)
- Turned my headless Raspberry Pi server crontab down to run once-a-day: to unfollow (per account)
- No need to do code authentication - seems like Instagods are on to scripts that run too fast to be human

Note the strategic use of "seem" above. Can others verify that a slow run is best?
