### ISSUE TITLE
Load button not found - location 

### ISSUE THREAD

**Issue by arminorlik** [InstaPy/InstaPy#1550]
## Expected Behavior
Hi,
I try to like pics using location, but unfortunately after few seconds activity below exception is throw out 
## Current Behavior
![obraz](https://user-images.githubusercontent.com/26714333/36982908-53b61586-2091-11e8-84ea-bf7d27f36805.png)

quick setup-up
## InstaPy configuration
![obraz](https://user-images.githubusercontent.com/26714333/36982284-cae3a8f0-208f-11e8-9bda-e9b0fd2b1844.png)

**Comment by DamnGoodWebsites** [comment]
Any solution to this?

**Comment by Tjorriemorrie** [comment]
Are you using windows?
That exception does not look like the problem: is that the whole stacktrace?
It seems that the connection to chrome was lost during the test
