### ISSUE TITLE
How can I get InstaPy to check how many accounts I'm following?

### ISSUE THREAD

**Issue by gustafsom** [InstaPy/InstaPy#1552]
Good morning guys, I'm a beginner on InstaPy and I'm pissed how powerful it is. I spend the day studying and testing some possibilities.

I'm interested in automating the amount of Follows and Unfollows per day based on how many people I'm following.

How can I get InstaPy to check how many accounts I'm following?

**Comment by martinkuna** [comment]
I do not think it has the functionality directly, but you can have it set to follow people everyday, for a few days, without unfollowing anyone. This will build up your followed pool, you then can add a line to your configuration to unfollow the same number of people you follow in a given day, so the count of who you follow remains consistent.

Day one follow: 50 people
Day two follow: 50 people
Day three follow: 50 people

Follow pool = 150 people
Day 4: unfollow + follow 50 people with FIFO only

This will mean the bot will follow people for 2 days, then unfollow them and get a new 50, all while keeping your follow count consistent. Unless you set to not unfollow active users.

Hope this helps!

**Comment by gustafsom** [comment]
@martinkuna thank you very much for the answer. I did this even as you suggested. By InstaPy you follow 1000 accounts. But the problem is that some have a private account and a request is sent. So the number of accounts I'm following is not equal to the number of people set up not InstaPy. I thought of setting up for InstaPy to check how many accounts I'm following and depending on that number the "`amount`" field in "`session.follow_user_followers`" was automatic. Same thing for "`session.unfollow_users`".

But I'm not sure how to get InstaPy to check how many accounts I'm following.

**Comment by martinkuna** [comment]
That’s odd, I set follow_users_followers on my girlfriends account and it followed her cousin, who has a private account.. I heard others saying the bot will not follow private accounts, but mine appears to have done that. Weird.. I know Tim has an Instagram profile scrapper that gets the number of followers, I wonder if you could use that code to add to this project and add that functionality.

I did notice if I set it to, say for example, follow 1000 people, it will most likely follow less than 1000 people, but for me the amount of people I follow is pretty consistent with the method I described above. Though sometimes I do have to set unfollow_users higher or lower to help it.

If instaPy could check the number of accounts you’re following, it definitely would make it much easier.. as far as I know this doesn’t exist in InstaPy, but it should.

**Comment by randysinnott** [comment]
I hacked together something for this.

When you want to get the followers, you need to have the browser object available and run this line:

    following = browser.execute_script(
        "return window._sharedData.""entry_data.ProfilePage[0]."
        "user.follows.count")

**Comment by gustafsom** [comment]
@randysinnott 

thanks for the great help, as well as more studies to learn more. But I'm still doubtful. Does this code I put in `instapy.py` and `print_log_writer.py`?

**Comment by randysinnott** [comment]
So I created a different object that has the property of storing the amount of followers and the number I'm following.  There's a bunch of other stuff I'm doing with that object as well, but here's some code snippets that should help understand what's going on.

print_log_writer.py
----
from instapy import database_util

def log_follower_num(browser, username, logfolder):
    """Prints and logs the current number of followers to
    a seperate file"""
    browser.get('https://www.instagram.com/' + username)

    followed_by = browser.execute_script(
        "return window._sharedData.""entry_data.ProfilePage[0]."
        "user.followed_by.count")
    following = browser.execute_script(
        "return window._sharedData.""entry_data.ProfilePage[0]."
        "user.follows.count")

    with open('{}followerNum.txt'.format(logfolder), 'a') as numFile:
        numFile.write(
            '{:%Y-%m-%d %H:%M} {}\n'.format(datetime.now(), followed_by or 0))

    database_util.update_run_followers(num_followers = followed_by, num_following = following )
    return followed_by


database_util.py (does a bunch of other stuff as well)
---
def update_run_followers( num_followers , num_following ) :
  this.following = num_following
  this.followers = num_followers

**Comment by HaimBendanan** [comment]
@randysinnott Awesome - thanks for sharing :)
I changed your code a bit to suit my need. I only need these as functions:

```
def get_followers_count(browser, username):
    browser.get('https://www.instagram.com/' + username)
    return browser.execute_script(
        "return window._sharedData.""entry_data.ProfilePage[0]."
        "user.followed_by.count")


def get_following_count(browser, username):
    browser.get('https://www.instagram.com/' + username)
    return browser.execute_script(
        "return window._sharedData.""entry_data.ProfilePage[0]."
        "user.follows.count")

```

**Usage** (Can be called from the quickstart file)
```
        followers = get_followers_count(session.browser, username)
        following = get_following_count(session.browser, username)
```

**Comment by gustafsom** [comment]
@randysinnott and @HaimBendanan 
Thank you for your help. But unfortunately I could not put the codes that you put to work. Sorry, it's lack of knowledge.

I was able to make an adjustment to: `print_log_writer.py`
```
followed_by = browser.execute_script (
         "return window._sharedData." "entry_data.ProfilePage [0]."
         "user.followed_by.count")
```
per:

```
followed_by = browser.execute_script (
         "return window._sharedData." "entry_data.ProfilePage [0]."
         "user.follows.count")
```

I asked Python to read the file: `followerNum.txt` and use the information I need.

This form is not ideal. But that's what I was able to do.

**Comment by randysinnott** [comment]
Glad the code was of some help for you Haim -- I'm doing something
super-specific in my code, so I know it wasn't totally generalizable, but
glad it provided the start of a solution.

gustafson, you'll get there.  print_log_writer is the place I was doing it
as well, as it's already got broswer.  That isn't the "right" place, but it
works for certain limited use cases :)

**Comment by gustafsom** [comment]
@HaimBendanan and @randysinnott

with the general problem that occurred yesterday. I had to make the adjustments to Issue [https://github.com/timgrossmann/InstaPy/pull/1610/files](url)

So the changes I made are causing Instapy to fail, and I can not tell how many people I'm following.

Can you help me make the adjustments again?

**Comment by randysinnott** [comment]
following = browser.execute_script(
        "return window._sharedData.""entry_data.ProfilePage[0]."
        "graphql.user.edge_follow.count")

**Comment by gustafsom** [comment]
@randysinnott 

Thank you. I'll test here.

**Comment by andrebrener** [comment]
> @randysinnott Awesome - thanks for sharing :)
> I changed your code a bit to suit my need. I only need these as functions:
> 
> ```
> def get_followers_count(browser, username):
>     browser.get('https://www.instagram.com/' + username)
>     return browser.execute_script(
>         "return window._sharedData.""entry_data.ProfilePage[0]."
>         "user.followed_by.count")
> 
> 
> def get_following_count(browser, username):
>     browser.get('https://www.instagram.com/' + username)
>     return browser.execute_script(
>         "return window._sharedData.""entry_data.ProfilePage[0]."
>         "user.follows.count")
> ```
> **Usage** (Can be called from the quickstart file)
> 
> ```
>         followers = get_followers_count(session.browser, username)
>         following = get_following_count(session.browser, username)
> ```

Hey! thanks for this. My noob questions are:
- where are the functions are in print_log_writer.py?
- to call them do you import them directly from there or is there anything else I should do?
