### ISSUE TITLE
Cron Problem Raspberry Pi 3

### ISSUE THREAD

**Issue by skaeslin** [InstaPy/InstaPy#1553]
## Expected Behavior
Schedule Instapy with cron
## Current Behavior
Cron is set up with "crontab -e" 

then 

"56 12 * * * cd /home/pi/Projects/instapy && /usr/bin/python quickstart.py"

I save it with "CTRL X -> Y -> Enter" but it won't work (no reaction at the time it should start). Instapy works well if i execute it manually. 
## Possible Solution (optional)
?
## InstaPy configuration
Raspberry Pi 3 B, Raspian

Thanks a lot in advance for your help! 
PS: This is such a cool project :D

**Comment by mikestan** [comment]
Are you sure those are the correct editor commands to write-save the crontab? You can check using crontab -l...


Also, please be sure crond is running: start cron service by running `sudo /etc/init.d/cron start`

**Comment by skaeslin** [comment]
@mikestan Thank you for your answer.

If I check with crontab -l it is listed there. 

crond is running. If I enter what you wrote it responds with "[ ok ] Starting cron (via systemct1): cron.service. 

I changed the scheduled time in crone so I could see if it works. Still the same as before... any other ideas?

**Comment by mikestan** [comment]
Other simple things to check is that your time is set up right - check by running the 'date' command.

Also be sure to use 24 hour time in crontab, so your example would be 12:56pm.

Lastly, you can execute 'sudo tail -f /var/log/syslog' (CTRL-C to exit) right before your crontab should run to see any errors while they happen. You can view that log to see what happened recently or 'zcat' the previous day's log (the 'syslog.2.gz' file).

**Comment by martinkuna** [comment]
Try specifying the full path just for the hell of it, this is how mine is setup
‘’’10 5 * * * cd /home/pi/repos/InstaPy/ && sudo xvfb-run -a /usr/bin/python /home/pi/repos/InstaPy/quickstart.py’’’

**Comment by martinkuna** [comment]
Try specifying the full path just for the hell of it, this is how mine is setup, using crontab:

10 5 * * * cd /home/pi/repos/InstaPy/ && sudo xvfb-run -a /usr/bin/python /home/pi/repos/InstaPy/quickstart.py

You could also remove the hour and set it to run in a few minutes from the current time, while watching your logs with “watch tail /var/log/syslog“

Another helpful tip after you get this working is to setup cron to email you, everyday I get a log showing the output of instaPy.

**Comment by skaeslin** [comment]
@mikestan Thanks again for your answer! 
The time is correct. When I let it run hourly it also doesnt work. 
If I execute "sudo tail -f /var/log/syslog" + CTRL-C and let the cron run a few minutes later nothing happens. I don't see any errors. 

@martinkuna Thank you too for your answer! I hope we can solve this together. :)
I specified the full path now with help of your example and removed the hour. 
in "watch tail /var/log/syslog" this is shown: 

Mar 7 12:57:01 raspberrypi cron[341]: (pi) RELOAD (crontabs/pi)
Mar 7 12:57:01 raspberrypi CRON[7391]: (pi) CMD (cd /home/pi/Projects/instapy/ && sudo xvfb-run -a /usr/bin/python /home/pi/Projects/instapy/quickstart.py)

And that's it. But nothing happens. Any idea what else I could try out?

Thank you in advance!

**Comment by martinkuna** [comment]
So we know cron is working and executing that command! Also, xvfb-run -a is to run it “headless”, it puts it in a virtual display buffer, so you will not see anything. Try opening terminal and copy pasting your cron command, and you should see instaPy run in that terminal.

cd /home/pi/Projects/instapy/ && sudo xvfb-run -a /usr/bin/python /home/pi/Projects/instapy/quickstart.py

You can take out xvfb if you don’t want it to run headless, but if you do want it to run that way, add headless=True to your instaPy QuickStart, see main page for how; I’m on my phone responding to you right now.

**Comment by skaeslin** [comment]
Alright @martinkuna ! :D 

It really works!! I can't belive this! Soo cool! Just for a test I restarted my Pi and planned with cron another start for instapy. well exactly at said time a new chromium command opens with quite a bit CPU usage. It also turns out that I've been running Instapy the whole afternoon without even knowing it. (Following went up +200)

Thanks a lot to you two! 

@martinkuna @mikestan 

(I think this thread can be closed)

**Comment by martinkuna** [comment]
Glad you were able to get it working!

**Comment by skaeslin** [comment]
@martinkuna Yeah me too! Now I'm trying to find the therad you mentioned above. Where I can get cron to E-Mail me the avtivity report :)
Perhaps you can help me again?`^^
