### ISSUE TITLE
Is this line supposed to return true?

### ISSUE THREAD

**Issue by CodeMaster1** [InstaPy/InstaPy#1555]
I have not gone through the whole code but due to this line many of the images are not getting liked.

https://github.com/timgrossmann/InstaPy/blob/20e54e6014ece6d8137e05522bb33bb4f950f2ee/instapy/like_util.py#L514

**Comment by CodeMaster1** [comment]
Any comments on this issue?

**Comment by Tjorriemorrie** [comment]
It returns there if a word is found in the image that is set to be ignored. Check your ignore list at `session.set_ignore_if_contains`

**Comment by CodeMaster1** [comment]
Due to this, many of images were getting ignored. Kindly re-check.

**Comment by CodeMaster1** [comment]
Also, I have seen only 25-27 images are being iterated from any tag even if i give a larger number.
