### ISSUE TITLE
Customize sleep times between likes/follows/comments

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1557]
Where is the root settings for the delays between follows/likes/comments so my bot does not follow so quickly and get me banned for example i only want to follow the like by tags feature 60 -120 seconds randomly to avoid ban.....  Example :

session.follow_by_tags(['tag1', 'tag2'], time.sleep(random.randint(60,120)), amount=10)

But it throws error so where is rooting settings for delays for liking and following through quickstart.py

**Comment by imbarismustafa** [comment]
i think is in instapy folder text file called instapy.
