### ISSUE TITLE
Session not defined

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1558]
I'm trying to host my script on the Cloud Service Cloud9 but if I start the quickstart.py script I get this error.

Traceback (most recent call last):
  File "/home/ubuntu/workspace/InstaPy/quickstart.py", line 27, in <module>
    session.end()
NameError: name 'session' is not defined

Can anyone help me?

**Comment by yxorp** [comment]
This is because an error occurred in your script before the session object is created, so when your finally clause is executed it tries to use that object and you get this error.

You should check what is going on before or whilst the session object is being created, could possibly be a connection issue stopping the script from communicating with instagram?

**Comment by ghost** [comment]
But in the code before the session object is used several times and there's no problem with it.

**Comment by wemakefuture** [comment]
had the same issue. 

make sure
 
cd assets/
chmod +x chromedriver 

and what helped was 
(raspi)
sudo xvfb-run python2.7 quickstart.py

**Comment by ghost** [comment]
Where do I need to type in all this stuff?
Can you explain it a little bit more accurate for me?

**Comment by wemakefuture** [comment]
check out #1163 
on what system are you running it?

**Comment by ghost** [comment]
I'm running it on Python 2.7

2018-03-10 19:35 GMT+01:00 wecanfuture <notifications@github.com>:

**Comment by wemakefuture** [comment]
@Nikeless i ment what system Headless server ubuntu, mac, windows. Cause my problem was related so something which happend on a raspberry Pi3 debian stretch.

**Comment by ghost** [comment]
I'm trying to run it on Cloud9 Webhosting Server

**Comment by wemakefuture** [comment]
Setup a vps on DO with ubuntu 16.04 or 16.10 and run as explained the readme 
[https://m.do.co/c/4d8ec2d2cb60 ](https://m.do.co/c/4d8ec2d2cb60 )

**Comment by ghost** [comment]
I gotta pay for it right? And is it possible to run more than one script on DO?

**Comment by wemakefuture** [comment]
yeah you can run 100s of scripts

**Comment by ghost** [comment]
And how much is the monthly cost for it?

**Comment by wemakefuture** [comment]
10$ is quite fair.

**Comment by ghost** [comment]
Thank youfor everything.

**Comment by wemakefuture** [comment]
You welcome

Nikeless <notifications@github.com> schrieb am Sa., 10. März 2018, 22:00:

**Comment by ghost** [comment]
Do I need to create a new droplet for every instagram bot?

**Comment by wemakefuture** [comment]
Check out my profile there is an email address, write me, I will guide you.

Nikeless <notifications@github.com> schrieb am So., 11. März 2018, 10:52:
