### ISSUE TITLE
Did Instagram change some elements?

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1559]
Since today I get an error when trying to call the following function:
"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/following-sibling::div"}"

And also when trying to like by hashs:
"selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'"

Has anybody the same problems? Login to instagram works as usual.

**Comment by sionking** [comment]
not me, check that chrome did not upgraded it self and chrome driver is latest (there is a new one)

**Comment by ghost** [comment]
@sionking Yes you were definitly right! Updated my Chrome Driver and now everything works perfectly again. Thanks alot!
