### ISSUE TITLE
Run InstaPy minified

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#156]
Hi,

I’ve been running InstaPy on my MacBook while working.
Since one of the last versions the InstaPy Chrome Browser always get into focus so that I can’t work in other programs parallel. Is there a way to get the old behaviour back?

Kind regards

Tibor

**Comment by eduardocalazansjr** [comment]
On old OSx versions this is an SO behaviour.

Not reproducible on latest Sierra build and it's not InstaPy related, since selenium doesn't bring the chrome window up.

**Comment by tibor** [comment]
Hi,

this behaviour is occuring on both of my MacBooks which are running the latest version of macOS Sierra (10.12.4) and started only yesterday.
All versions of InstaPy before didn’t show this behaviour.
So I assume that some changes on InstaPy are responsible for this behaviour.

Further information: This behaviour occurs only while InstaPy is scrolling.
As soon as a post is selected and the liking/commenting starts, I can safely minify Chrome.

**Comment by eduardocalazansjr** [comment]
As i said, OS or Chrome related.

![screen shot 2017-04-19 at 07 35 12](https://cloud.githubusercontent.com/assets/5658870/25175971/060d415c-24d3-11e7-8038-ba49e799f6d9.png)

![screen shot 2017-04-19 at 07 36 22](https://cloud.githubusercontent.com/assets/5658870/25175973/071eb198-24d3-11e7-87d5-44bf3eb27679.png)

If you check the code, there no changes in the scrolling part of code.

**Comment by eduardocalazansjr** [comment]
@tibor please, could you check my comment on https://github.com/timgrossmann/InstaPy/commit/fb336bf94ad10cc05d0aec054a0e926ecbb824fd and remove the lines that i said?

**Comment by tibor** [comment]
Hi @vlntdds ,

I commented both lines 70 and 73 and Chrome stays in the background now.
Thanks for reopening!

**Comment by timgrossmann** [comment]
@tibor I removed them from the script...
Should be good to go now
