### ISSUE TITLE
error: ASCII can't encode character u'\xa0' in position 3: ordinal not in range(128)

### ISSUE THREAD

**Issue by riccardorighettiphoto** [InstaPy/InstaPy#1560]
Hello,
I got a never seen error before today, this is the log:

``
Traceback (most recent call last):
  File "./quickstart.py", line 32, in <module>
    session.like_by_tags(['tag1', 'tag2', 'tag3', 'tag3'], amount=100)
  File "/home/my_user_name/InstaPy/instapy/instapy.py", line 894, in like_by_tags
    self.logger)
  File "/home/my_user_name/InstaPy/instapy/like_util.py", line 542, in check_link
    'Inappropriate! ~ contains \'{}\' in \'{}\''.format(iffy, quashed))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 3: ordinal not in range(128)
``

Any idea?
InstaPy runs on a CentOS 7 server, plus Python v2.7.5.
Thank you.

**Comment by MrBeardedGuy** [comment]
It might have to do with emojis check out here https://github.com/timgrossmann/InstaPy#emoji-support

**Comment by riccardorighettiphoto** [comment]
@MrBeardedGuy 
I don't know what you referred to, anyway, emoji is installed.
I got one more time this error. Nobody?

**Comment by Tjorriemorrie** [comment]
Not sure, but it looks like your tags contains a line break. Delete the tags and try typing it in manually. Seems like a copy&paste error.

**Comment by riccardorighettiphoto** [comment]
Hello, which tags you referred to? those in the ‘quickstart.py’ file?

**Comment by CamiloB** [comment]
@riccardorighettiphoto  hi i had the same issue, this happen when i copy and paste all the tags 
` session.like_by_tags(['vivienda', 'viviendas', 'viviendanueva', 'casanueva', 'casa',
              'casas', 'hogar', 'hogardulcehogar', 'hogarfeliz', 'hogares',
              'hogarideal', 'hogaresfelices', 'familia', 'familiar',
              'familianumerosa', 'familias', 'familiarreunida', 'familiafeliz',
              'apartamentosenventa', 'apartamentoenventa', 'apartamento',
              'apartamentos', 'residencia', 'hijo', 'hija', 'hijos'], amount=100) ` 
I fix this by put tag by tab by my self, looks like when you copy paste, he paste some blank spaces and the code got that error

**Comment by riccardorighettiphoto** [comment]
Hello @CamiloB,
I don't think this is my case. I always write tags one by one, without copying them from elsewhere. Furthermore, the issue comes up randomly; if it was due to what you had written, I would get every time, but that's not my case.
Anyway, thank you.

**Comment by riccardorighettiphoto** [comment]
Anyone experiencing something like that? I randomly get this error and I don’t know why, but the run ends with an error.

**Comment by finan** [comment]
I have the same problem. Please help.

**Comment by nocomment-bln** [comment]
I got the same problem:

line 538, in set_smart_hashtags
    print(u'[smart hashtag generated: {}]'.format(item))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 26-27: ordinal not in range(128)

**Comment by sohumsanu** [comment]
It's because the smart hashtags that it's generating contain an emoji which it cannot decode. Just manually put hashtags so the error will not occur.

**Comment by riccardorighettiphoto** [comment]
@awesome205
What does it mean "... Just put hashtags so the error will not occur"?
Which hastags, where? My quickstart file is a plain vanilla one, no exotic or complex stuffs.

**Comment by axlright** [comment]
I just got this same error. Seems to have barfed out on an emoji in an image description, not in the hashtag itself.

Image that caused the script to barf out:
https://www.instagram.com/p/BkRhLVbFgWF/

Error message:
```
Traceback (most recent call last):
  File "user-xxx-hashtag-architecturelovers.py", line 63, in <module>
    session.like_by_tags(['#architecturelovers'], amount=636)
  File "/Users/my_name/Documents/Code/InstaPy/instapy/instapy.py", line 1315, in like_by_tags
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 53: ordinal not in range(128)
```

Relevant settings:
`session.like_by_tags(['#architecturelovers'], amount=636)`

**Comment by csdhao** [comment]
you can add a convert 
convertName = function(name) {
      var nbsp = new RegExp(String.fromCharCode(160), "g");
      return name.replace(nbsp, ' ');
    }

**Comment by rdavidwu** [comment]
I think this whole UnicodeDecodeError thing happens because of the way python handles strings. 
https://www.azavea.com/blog/2014/03/24/solving-unicode-problems-in-python-2-7/
