### ISSUE TITLE
Liked photos not showing in "Posts, i have liked"

### ISSUE THREAD

**Issue by kristofenyi** [InstaPy/InstaPy#1561]
Hello,

I am runnging a digital ocean droplet. It worked perfectly.  After few days trying out some possibilities with the script i decided to make it simple. I just go over 5 tags, 50 photos each tag and make interaction with 80% of those where the interaction means to like 3 more photos randomly from the feed. 

**The problem is, that since last time i have run the script, when i go to my instagram profile and want to look on the "Photos, i have liked" i don't see any that was liked with the script. That has not happen before and even if i open some of the photos, that the bot has shown in the terminal that has been liked and open that photo on my instagram i can see it has not been liked** 

Any ideas?

## InstaPy configuration
    # settings
    session.set_dont_like(['nfsw'])
    session.set_do_follow(enabled=True, percentage=10, times=2)
    session.unfollow_users(amount=30, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60 )

    # actions
    session.set_user_interact(amount=3, randomize=True, percentage=80, media='Photo')
    session.like_by_tags(['czechvegan', 'dnesnosim', 'czech_insta', 'dnescestujem', 'dnesjemvegan'], amount=50, interact=True)

**Comment by sionking** [comment]
like blocked from web,
You need to take my module of checking for like block every 5 likes by refreshing the page.
Do you see the image was liked when you enter the web from the log ?

**Comment by kristofenyi** [comment]
No, when i out the link in the web i dont see the image like eventhough it says it likes the image (in the ssh terminal)

But i see engagement on my profilem from the tags that i like. When i run the sript and it likes only around 150 photos i see them in the profile under “posts i liked” but if it is more like 300 pics, then they just don’t show there and when opening the links to the photos it seems like they are not liked. Could this be some kind of shadow ban ?

**Comment by dremendes** [comment]
Watching this thread because I have the same problem as @3p1demicz 
I can see engagement from the likes but they do not always appear under "posts I liked" and I suspect it's some kind of shadow ban from Instagram

**Comment by kristofenyi** [comment]
@andremendesc and when you run only few likes, you se it in the “post I have liked” ? Or

**Comment by dremendes** [comment]
@3p1demicz I see only a few likes from the bot on "posts I liked" page. Like if InstaPy says it liked 54 images, I can see less than 10 new liked photos on that page.

**Comment by GabrieleCalarota** [comment]
I've got the same issue .. from the last 2 or 3 days I noticed picture are liked from terminal but on chrome driver there's an url like this one: 

https://www.instagram.com/web/likes/1732194991415356450/like/

Moreover, I've checked with the phone,in the end pics are not liked or commented, although it seemed so in the first place from web

For a month everything worked fine and I haven't done any major changes in the code in the last week.

Any guesses?

**Comment by Tentt** [comment]
Hey guys! 
Any updates? Recommendations? Things?
That's not a ban - bc when I like ~50 posts in app on smartphone - I see all that ~50 likes in “post I have liked”
But when works instapy I see in “post I have liked” just 5-10 for full session of ~300 likes 
And it's not like first 5-10 - it seems like random
What's happened? What to do?
