### ISSUE TITLE
Unable to start instapy

### ISSUE THREAD

**Issue by StromboliKQ** [InstaPy/InstaPy#1566]
## Expected Behavior
I am able to run instapy via docker on ubuntu
## Current Behavior
i get the following error

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "docker_quickstart.py", line 18, in worker
    bot.login()
  File "/code/instapy/instapy.py", line 264, in login
    self.bypass_suspicious_attempt):
  File "/code/instapy/login_util.py", line 94, in login_user
    browser.get('https://www.instagram.com')
AttributeError: 'NoneType' object has no attribute 'get'`

## InstaPy configuration
import random 
from instapy import InstaPy
import os
import multiprocessing
import datetime
import time
`
instaUser = ['XXX', 'XXX']
instaPass = ['XXX', 'XXX']
followersToFollow = [['tylerthecreator', 'OldInglish', 'youngkrizzle', 'FreddieGibbs', 'MyFabolousLife', 'APRoth', 'PhillyFreeway', 'konquestagram', 'wrecktherebel'], ['stonesthrow', 'rhymesayers', 'eonemusic', 'mellomusicgroup', 'cinematicmusicgroup', 'ofwgkta', 'funkvolume', 'strangemusicinc', 'duckdownmusic']]
smartTags = [['TEAMKONQUEST', 'KonQuestNow', 'verseborn', 'newmusic', 'newrelease', 'debut', 'indieartist', 'radioplay', 'livebroadcast', 'hiphop', 'allbaymusic', 'thizzler', 'wethewest', 'bayareacompass ', 'eonemusic', 'mellomusicgroup', 'pandoramusic ', 'cinematicmusicgroup', 'oddfuture', 'funkvolume', 'strangemusic', 'stonesthrow', 'duckdown', 'rawkus', 'rhymesayers', 'ViperRecords'], ['supportlocal', 'cinematicmusicgroup','oddfuture','funkvolume','strangemusic','electriccoolaidrecords','teamkonquest','stonesthrow','duckdown','rawkus','vmg','verseborn','rhymesayers','qn5','ViperRecords','mellomusicgroup','brainfeeder','eone','CutthroatHippieGang','GypsyGang','KonQuestNow','konquest','HipHop','WestCoast','teamkonquest','klamathfalls','ktec','Oregon','medfordoregon','portland','southernoregon','californiamusic']]
followLocation = ['', '']

def worker(selection):
    
    print("MULTI - Started as",instaUser[selection],"at",datetime.datetime.now().strftime("%H:%M:%S"))
    session = InstaPy(username=instaUser[selection], password=instaPass[selection], selenium_local_session=False)
    session.login()

    session.set_dont_unfollow_active_users(enabled=True, posts=7)
    session.set_user_interact(amount=2, randomize=True, percentage=20, media='Photo')
    session.set_upper_follower_count(limit = 500)

    session.like_by_feed(amount=random.randint(5,11), randomize=True, unfollow=True, interact=True)
    print("MULTI -",instaUser[selection],"finished liking by feed at",datetime.datetime.now().strftime("%H:%M:%S"))

    if not followLocation[selection] == '':#if no location given for that account, just ignore this step
        session.like_by_locations(followLocation[selection], amount=10)
        print("MULTI -",instaUser[selection],"finished liking by location",datetime.datetime.now().strftime("%H:%M:%S"))

    session.unfollow_users(amount=random.randint(7,10), sleep_delay=(random.randint(44,111)))
    print("MULTI -",instaUser[selection],"finished unfollowing at",datetime.datetime.now().strftime("%H:%M:%S"))
      
    if followersToFollow[selection]:
        session.follow_user_followers(followersToFollow[selection], amount=random.randint(44,55), randomize=False, interact=True, sleep_delay=111)
        print("MULTI -",instaUser[selection],"finished following followers at",datetime.datetime.now().strftime("%H:%M:%S")) 
   
    if smartTags[selection]:
        session.set_smart_hashtags(smartTags[selection], limit=3, sort='top', log_tags=True)
        session.like_by_tags(amount=random.randint(2,5), use_smart_hashtags=True)
        print("MULTI -",instaUser[selection],"finished smartTags at",datetime.datetime.now().strftime("%H:%M:%S"))

    session.end()
    print("MULTI -",instaUser[selection],"finished run at",datetime.datetime.now().strftime("%H:%M:%S"))

if __name__ == '__main__':        
    print("MULTI -","Starting at",datetime.datetime.now().strftime("%H:%M:%S"))
    jobs = []
    for i in range(len(instaUser)):
        p = multiprocessing.Process(target=worker, args=(i,))
        jobs.append(p)
        p.start()
        time.sleep(66);#no delay cause some instances of chrome to give errors and stop`

**Comment by benjamin-ollier** [comment]
Unable to launch the command

<img width="489" alt="capture d ecran 2018-03-08 a 23 17 06" src="https://user-images.githubusercontent.com/33257076/37179729-ea764ab2-2326-11e8-8681-ceeff4f083a7.png">

POSSIBLE SOLUTION ?
