### ISSUE TITLE
Unable to start instapy

### ISSUE THREAD

**Issue by benjamin-ollier** [InstaPy/InstaPy#1568]
Unable to launch the command

<img width="489" alt="capture d ecran 2018-03-08 a 23 17 06" src="https://user-images.githubusercontent.com/33257076/37179729-ea764ab2-2326-11e8-8681-ceeff4f083a7.png">

POSSIBLE SOLUTION ?

**Comment by DavidMolinari** [comment]
Might be quotes problem :  

``` insta_username = 'justepleasure' ```
instead of 
``` insta_username = ‘justepleasure‘ ```
