### ISSUE TITLE
Docker container is failing

### ISSUE THREAD

**Issue by amitbend** [InstaPy/InstaPy#157]
Hi,
I'm using InstaPy with Docker, following exactly the readme, but every time i see this error on the logs -
`Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    InstaPy()\
  File "/InstaPy/instapy/instapy.py", line 35, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-71-generic x86_64)
`
Any idea what's the issue?

**Comment by eduardocalazansjr** [comment]
Do you have sufficient ram for run chrome?

**Comment by amitbend** [comment]
Running on a laptop with 8GB,
It suppose to be sufficient @vlntdds right?

**Comment by eduardocalazansjr** [comment]
Are you sure that your DOCKER CONTAINER have sufficient resources for run chrome?
Also check for issues with this error, there a bunch of duplicates of this (#110, for example)

**Comment by amitbend** [comment]
@vlntdds I'm not very experienced with docker, 
is there a way to allocate more ram to the specific container to validate that this is the issue?

this is what i see from `docker stats`

`CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
5ae0ad45c0da        2.38%               16.56 MiB / 7.699 GiB   0.21%               1.35 kB / 648 B     0 B / 61.4 kB       10
`

**Comment by eduardocalazansjr** [comment]
Have you checked the #110, that say that this could be an issue with pyvirtualdisplay lines?

**Comment by amitbend** [comment]
Yeah! that was the issue @vlntdds

**Comment by timgrossmann** [comment]
@amitbend Sorry for the late response... Saw your issue at work, but couldn't comment...
I'll add that instruction to the docker part of the readme.

**Comment by eduardocalazansjr** [comment]
@timgrossmann you could replace the lines in the docker script, without user intervention, right?

**Comment by amitbend** [comment]
Hi @timgrossmann!
Is there a particular reason to keep those lines commented?

**Comment by timgrossmann** [comment]
@amitbend Yes, because you don't want to use that if you run the script 'locally' without Docker

It was added to be able to run it on e.g. a Server

**Comment by eduardocalazansjr** [comment]
@timgrossmann `sed -ie 's/#self.display/self.display/g' instapy.py` seems to do the trick, could you please test?

**Comment by timgrossmann** [comment]
@vlntdds Yeah, nice! Also thought of using sed, I'll try this out ASAP

**Comment by timgrossmann** [comment]
@vlntdds works really nice! Thank you I'll update that!
