### ISSUE TITLE
Import error: no module named 'pyvirtualdisplay'

### ISSUE THREAD

**Issue by mlwrose** [InstaPy/InstaPy#1572]
## Expected Behavior

Launch window display

## Current Behavior

Traceback saying the module is not there but when i list the modules installed pyvirtualdisplay is there. 

## Possible Solution (optional)

It makes further progress if i run the script using python and not python3, but then the display runs but does not display images or just a whiote screen? please help

**Comment by DavidMolinari** [comment]
Have you tried ```pip3 install pyvirtualdisplay ``` for python3 ?

**Comment by MrBeardedGuy** [comment]
Watch out which version of Python3 you have. `Pyvirtualdisplay` does not support the latest 3.6 https://pypi.python.org/pypi/PyVirtualDisplay

**Comment by mlwrose** [comment]
Hi thanks so ,uch for the feedback. Did help a bit i have Selenium and
Emoji and pyvirtualdisplay installed now.

program now executes but then fails with this message.

Traceback (most recent call last):
  File "quickstart2.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password,
use_firefox=True)
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 130, in
__init__
    self.set_selenium_local_session()
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 154, in
set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File
"/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py",
line 162, in __init__
    keep_alive=True)
  File
"/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py",
line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File
"/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py",
line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File
"/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py",
line 312, in execute
    self.error_handler.check_response(response)
  File
"/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py",
line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

Any advice?

Thanks again guys.
