### ISSUE TITLE
Unfollow loop error

### ISSUE THREAD

**Issue by alessiomtt** [InstaPy/InstaPy#1573]
Hi, I want to unfollow people thet only instapy have followed, after a succesfull login, I can see the number of people followed automatically remaining but i have this error:

unfollow loop error name 'log_uncertain_unfollowed_pool' is not defined

In my script I use this function:

`session.unfollow_users(amount=200, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60 )`

In my logs folder I have the pool and everithing, how can I resolve this problem?

Thank you so much!

**Comment by MrBeardedGuy** [comment]
This issue has been fixed in a previous PR. as mentioned over here. Just pull the latest version of Instapy or follow the instructions here https://github.com/timgrossmann/InstaPy/issues/1487
