### ISSUE TITLE
NameError: name 'session' is not defined

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1575]
I'm still getting this Error. Can anyone help me?
![screenshot_11](https://user-images.githubusercontent.com/26581443/37231372-361a0732-23eb-11e8-92f9-3cc4d0fb8959.png)

**Comment by imbarismustafa** [comment]
delete the code and copy paste the code from github example. then it should work fine.

**Comment by ghost** [comment]
Thank you for your fast response. But which github example are you talking about? About the file quickstart.py?

**Comment by Tjorriemorrie** [comment]
Nothing to do without stacktrace. (I'm not a fan of that try-catch). Be that as it may, add the following before the `finally` in the last lines to be the following to get the stacktrace, then post it here:
```
except Exception as e:
    print(e)

finally:
    # end the bot session
    session.end()
```

**Comment by ghost** [comment]
Now I'm getting this kind of error

![screenshot_13](https://user-images.githubusercontent.com/26581443/37240843-f9365a9e-2450-11e8-88bd-08d529dfa3f8.png)

**Comment by Tjorriemorrie** [comment]
The script cannot find the chrome browser. Did you download and extract the chromedriver to the assets folder?

Otherwise define it explicity on L10:
```
# Settings.browser_location = '/path/to/chromedriver'
```

**Comment by ghost** [comment]
What is the right path?
Sorry,I'm really new to python.

![screenshot_14](https://user-images.githubusercontent.com/26581443/37240961-6fd0a456-2452-11e8-8236-6c6022ef34e2.png)

**Comment by Tjorriemorrie** [comment]
There is no right or wrong path. You just need to specify wherever it is.

It looks like you missed step 4 from [installation](https://github.com/timgrossmann/InstaPy#basic-installation)

**Comment by ghost** [comment]
I did it. In the assets folder you can see the chromedriver.

**Comment by Tjorriemorrie** [comment]
Then it might be your IDE setup. See if you can run it from the command line. I know for Pycharm you have to add it to the contents roots.

**Comment by ghost** [comment]
What is a IDE setup?
