### ISSUE TITLE
Follow loop error sample larger than population

### ISSUE THREAD

**Issue by cormo1990** [InstaPy/InstaPy#1577]
Hello fam,
during the follow user followers action, i found that error and the bor stopped immediatly.
can you help me please?

"ERROR - follow loop error sample larger than population"

thanks in advance

**Comment by tanmald** [comment]
I too am having this error. But it only happens after following the followers of the first user on the list.

WARNING [2018-03-13 10:33:00] [xxx]  "user2" -> Less users to follow than requested.
ERROR [2018-03-13 10:33:00] [xxx]  follow loop error sample larger than population

**Comment by ekumar96** [comment]
I am having the exact same issue as you tanmald, but it will not happen is terminal is active/in the front/foreground on my Desktop. Pretty perplexing.

**Comment by britotiagos** [comment]
I got this error when using the smat_hashtag, what I did to overcome it was changing the 
sort='random' 
to
sort = 'top'
