### ISSUE TITLE
ERROR [#]  Image check error: name 'check_image' is not defined

### ISSUE THREAD

**Issue by balakedev** [InstaPy/InstaPy#1579]
Hey im getting an error relating to:

`ERROR [#]  Image check error: name 'check_image' is not defined`

I commented out: `from .clarifai_util import check_image`  but the bot crashes on launch with it commented out. 

The bot is working, im just not getting my clarifai comments - which is sort of my bread and butter because i have so many different arguments / comments based on detection. 

Has anyone patched this up yet? I noticed when i updated to the current build, the likeCompetitors seems to be crashing a lot so i reverted to an old build. Im getting a index out of range for trying to follow another accounts followers. 

Also, if i update to the current version of instapy - im still getting the same bug.
ERROR [#] Image check error: name 'check_image' is not defined

Cheers guys

**Comment by blakemmw** [comment]
Also, if i update to the current version of instapy - im still getting the same bug. 
`ERROR [#] Image check error: name 'check_image' is not defined`

**Comment by balakedev** [comment]
@converge any ideas mate?

**Comment by Tjorriemorrie** [comment]
Please paste the whole stracktrace from the master build, thanks.

**Comment by balakedev** [comment]
@Tjorriemorrie do you mean what shows up in the CMD? Thats the only error line. it pops right after "Image liked" and then it goes to a default random comment afterwards, skipping a clarifai comment.

**Comment by balakedev** [comment]
@Tjorriemorrie 
```
INFO [2018-03-12 17:49:11] [#]  --> Image Liked!
ERROR [2018-03-12 17:49:13] [#]  Image check error: name 'check_image' is not defined
INFO [2018-03-12 17:49:13] [#]  --> Commented: b'Awesome feed, we love it \xf0\x9f\x98\x8d'
INFO [2018-03-12 17:49:16] [#]  --> Not following

```

**Comment by Tjorriemorrie** [comment]
I haven't used clarifai yet, sorry. I can try to help:
Change the import to:
```
from .clarifai_util import check_image
```
meaning delete the if on L18 and unindent the import of check_image. 
What happens then?

**Comment by balakedev** [comment]
@Tjorriemorrie I think i love you. Worked. Thanks mate!!! <3

**Comment by Tjorriemorrie** [comment]
@timgrossmann ^ I don't think that condition should be on the import

**Comment by CodeMaster1** [comment]
Yes, it works on windows as well. No need for that conditon
