### ISSUE TITLE
LIKE FAILED RECENTLY (Worked before)

### ISSUE THREAD

**Issue by GabrieleCalarota** [InstaPy/InstaPy#1580]
Since the last 2 or 3 days I noticed picture are liked from terminal but on chrome driver there's an url like this one:

https://www.instagram.com/web/likes/1732194991415356450/like/

Moreover, I've checked with the phone,in the end pics are not liked or commented, although it seemed so in the first place from web

For a month everything worked fine and I haven't done any major changes in the code in the last week.

Any guesses? (From the phone I'm not blocked, and I strictly control the amount of like and comment the process does per day, so I would say it ain't a visible block)

**Comment by sionking** [comment]
Soft block for web only or that Instagram had web issues.
I got it to 25% of my accounts in the same 10 minute time frame.
I changed all stops/delays/sleep configuration.

**Comment by GabrieleCalarota** [comment]
My sleep on comments and like are cool (4 seconds)...a lot slower than a human can do @sionking

**Comment by GabrieleCalarota** [comment]
How do you see a web soft block??? @sionking

**Comment by sionking** [comment]
you refresh the page and see if the like is there.
I can still like from your mobile btw

**Comment by sionking** [comment]
*you

**Comment by sionking** [comment]
check my solution in one of the posts here for checking like not blocked every 5 liking

**Comment by GabrieleCalarota** [comment]
@sionking  I saw your solution of waiting 120 seconds ... But I don't think this is it...I haven't been able to like from web for the last 4 days, and I've never forced it..I mean I runned test, saw it didn't work and waited the next day to try again

**Comment by GabrieleCalarota** [comment]
@sionking Besides I tested on chrome and I'm able to like, but still not able to like from chrome-driver or instapy

**Comment by GabrieleCalarota** [comment]
I've managed to solve it by removing cookie and reset password. Don't know why.

**Comment by sionking** [comment]
You got chrome updated and cookie file not, that is Y.
Need to have some check on it.

**Comment by Tjorriemorrie** [comment]
@sionking but if that were the case then you shouldn't be able to continue a logged in session
