### ISSUE TITLE
is there a way to detect ghost followers and unfollow them ?

### ISSUE THREAD

**Issue by cemaytekin** [InstaPy/InstaPy#1581]

**Comment by sionking** [comment]
There are some apploications, but I would lile to get recommandation as well

**Comment by LeftyGlick36** [comment]
Well, just a thought if you could scan the user's activity of your profile. Such as amount of comments/likes left on your page if their numbers are < 3 then they would be considered a ghost follower. I'm sure there is a way to examine this in JSON

**Comment by Tjorriemorrie** [comment]
Why do you want this? Meaning are you trying to build a following of only active users? I'm just asking because this project is mainly a bot to just get a high number of follower count

**Comment by martinkuna** [comment]
@Tjorriemorrie So your account isn’t following tons of accounts, if they are ‘ghost’ accounts, it’s unlikely they will be unfollowing you anytime soon.

**Comment by Tjorriemorrie** [comment]
You want to look at [don't unfollow active users](https://github.com/timgrossmann/InstaPy#dont-unfollow-active-users). Then if you have an unfollow action, you are much more likely to just unfollow ghosts.

**Comment by martinkuna** [comment]
@Tjorriemorrie Yes, I am aware of that feature, though now that you bring it up, I am wondering why this question/issue exists. I thought there may be another way to check a user's activity, i.e. if the user themselves have been inactive for over a year.

@cemaytekin Does https://github.com/timgrossmann/InstaPy#dont-unfollow-active-users answer your question? If so, let's close this issue.
