### ISSUE TITLE
Install Issues 

### ISSUE THREAD

**Issue by thelovedr** [InstaPy/InstaPy#1583]
After Downloading all the files and installing them per the wiki, I am getting this error:

running install
running bdist_egg
running egg_info
writing instagram_py.egg-info\PKG-INFO
writing dependency_links to instagram_py.egg-info\dependency_links.txt
writing requirements to instagram_py.egg-info\requires.txt
writing top-level names to instagram_py.egg-info\top_level.txt
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
reading manifest file 'instagram_py.egg-info\SOURCES.txt'
writing manifest file 'instagram_py.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
warning: install_lib: 'build\lib' does not exist -- no Python modules to install

Anyone smarter than me willing to help?

**Comment by bertlandh** [comment]
### Basic Installation:

```bash
1. git clone https://github.com/timgrossmann/InstaPy.git
2. cd InstaPy
3. pip install .
or
3. python setup.py install
```
4. Download ```chromedriver``` for your system [from here](https://sites.google.com/a/chromium.org/chromedriver/downloads). Extract the .zip file and put it in ```/assets``` folder.

line 91 - 100 of the readme... does this help?
