### ISSUE TITLE
[Question] Adding sleep delay to "Follow by Tags"

### ISSUE THREAD

**Issue by walachewaka** [InstaPy/InstaPy#1589]
## Question/Feature request

Would it possible to integrate the same delay used in the "follow user followers" function?
By this I mean, since the follow user followers function stops @ every 10 users, it sleeps for a set amount of time. Would it be possible to add that same rule to the "follow by tags" function? That way we don't risk getting banned for following too many users, therefore we can  avoid surpassing the Instagram threshold.

**Comment by itayoron** [comment]
+1 !!! Thanks

**Comment by UtkuKaan** [comment]
For those who would like to have this functionality in the pursuit of purposes such as to decrease the likelihood of getting flagged, a work-around may be in the form of:

```
from time import sleep

for _ in range(5):
  session.follow_by_tags(['example', 'example2'], amount=10)
  sleep(601)
```
