### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by mlwrose** [InstaPy/InstaPy#1592]
## Current Behavior

Connection Refused error.

program now executes but then fails with this message.

Traceback (most recent call last):
  File "quickstart2.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password,
use_firefox=True)
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 130, in
__init__
    self.set_selenium_local_session()
  File "/home/pi/Desktop/InstaPy-master/instapy/instapy.py", line 154, in
set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File
"/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py",
line 162, in __init__
    keep_alive=True)
  File
"/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py",
line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File
"/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py",
line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File
"/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py",
line 312, in execute
    self.error_handler.check_response(response)
  File
"/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py",
line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

## Possible Solution (optional)

Not sure where to start

**Comment by rodriguesprobr** [comment]
Same problem here.

**Comment by mlwrose** [comment]
Did you figure it out bro? I think im going to start from scratch again.

**Comment by rodriguesprobr** [comment]
Yes. Try to update all python dependency packages with pip. It worked fine for me.
