### ISSUE TITLE
InstaPy basic setup error

### ISSUE THREAD

**Issue by adix70** [InstaPy/InstaPy#1593]
## I seem to getting this error while running the python quickstart.py command
Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.end()
NameError: name 'session' is not defined
<img width="1182" alt="screen shot 2018-03-12 at 1 47 18 pm" src="https://user-images.githubusercontent.com/17376260/37272750-a7009d3a-25fd-11e8-936e-3338b9f65361.png">
<img width="632" alt="screen shot 2018-03-12 at 1 49 02 pm" src="https://user-images.githubusercontent.com/17376260/37272869-0c24c952-25fe-11e8-9da2-cbff8b6b4f89.png">

**Comment by Tjorriemorrie** [comment]
Most likely your chromedriver is not installed. Double check that.

If that doesn't resolve, please add the following before finally:
```
except Exception as e:
    print(e)

finally:
```
and post the error, thanks

**Comment by adix70** [comment]
I have installed the chrome driver and pasted it in the assets folder.

**Comment by adix70** [comment]
@Tjorriemorrie I am getting the error even after including the exception you mentioned.  I'm attaching the screenshots Kindly have a look. 
<img width="1027" alt="screen shot 2018-03-12 at 3 04 59 am" src="https://user-images.githubusercontent.com/17376260/37282005-e86997d4-2618-11e8-8ad4-d69e5c435c25.png">
<img width="673" alt="screen shot 2018-03-12 at 5 09 06 pm" src="https://user-images.githubusercontent.com/17376260/37282016-f513f0ba-2618-11e8-9e8d-a041edbf2c00.png">

**Comment by Tjorriemorrie** [comment]
The chromedriver cannot find Chrome.
Not sure, but maybe reinstall Chrome for all users?
Otherwise you're going to have to edit instapy.instapy.InstaPy#set_selenium_local_session and add at around L218:
> chrome_options.setBinary("C:\\ThePAthtoChrome.exe");
