### ISSUE TITLE
Why it collect less users than requested? 

### ISSUE THREAD

**Issue by max-si-m** [InstaPy/InstaPy#1595]
Insta user has more than 2k followers but collects for interacting less than 100.

## Expected Behavior
we have `2,396 followers` (possibly parsed) and I expect that we will parse more than 100 :) 

## Current Behavior

`WARNING [2018-03-12 12:15:05] [xxxx]  karolina.lengvinaite -> Less users to follow than requested. == 90`

## InstaPy configuration
`.interact_user_followers(['karolina.lengvinaite', 'olja__pagas', 'ivanovalenok01', 'juliia_gunenko', 'yanamelnechuk369', 'aniken_88'], amount=900, randomize=True) \`

**Comment by Tjorriemorrie** [comment]
It seems that it looks on that user's profile for that user's followers. Then it only counts profiles who you can follow, which is the `amount` value. However, it seems it only scrolls once to the bottom and not continually till the end, which to me seems that it might not work for their infinite loading, and thus only have 90 on the page. Seems like a bug.
