### ISSUE TITLE
UnboundLocalError: local variable 'liked_img' referenced before assignment

### ISSUE THREAD

**Issue by adrianalter** [InstaPy/InstaPy#1599]
## Expected Behavior
I'm not 100% sure about the configuration, but it should simply interact with the profiles from the list.

## Current Behavior
root@InstagramAdrian:~/InstaPy# python3 adrianfollow.py
INFO [2018-03-12 16:31:16] [adrianalter]  Session started - 2018-03-12 16:31:16
INFO [2018-03-12 16:31:17] [adrianalter]  Logged in successfully!
WARNING [2018-03-12 16:31:45] [adrianalter]  Can't interact with private account
WARNING [2018-03-12 16:32:12] [adrianalter]  Can't interact with private account
WARNING [2018-03-12 16:32:39] [adrianalter]  Can't interact with private account
INFO [2018-03-12 16:32:39] [adrianalter]  --> Users: 0

INFO [2018-03-12 16:32:39] [adrianalter]  Liked: 0
INFO [2018-03-12 16:32:39] [adrianalter]  Already Liked: 0
INFO [2018-03-12 16:32:39] [adrianalter]  Inappropriate: 0
INFO [2018-03-12 16:32:39] [adrianalter]  Commented: 0
INFO [2018-03-12 16:32:39] [adrianalter]  Session ended - 2018-03-12 16:32:39
INFO [2018-03-12 16:32:39] [adrianalter]  --------------------

Traceback (most recent call last):
  File "adrianfollow.py", line 21, in <module>
    session.interact_user_followers(['djsnake', 'dukedumont', 'skrillex'], amount=200, randomize=True)
  File "/root/InstaPy/instapy/instapy.py", line 1344, in interact_user_followers
    self.user_interact_media)
  File "/root/InstaPy/instapy/instapy.py", line 1115, in like_by_users
    self.liked_img += liked_img
UnboundLocalError: local variable 'liked_img' referenced before assignment

## InstaPy configuration
from instapy import InstaPy

insta_username = 'adrianalter'
insta_password = 'censored'

try:
    session = InstaPy(username=insta_username, password=insta_password, headless_browser=True, multi_logs=True, nogui=True)
    session.login()

    session.set_user_interact(amount=200, randomize=True, percentage=65, media='Photo')
    session.set_do_follow(enabled=True, percentage=70)
    session.set_do_like(enabled=True, percentage=70)
    session.set_comments(["Cool :)", "Super!"])
    session.set_do_comment(enabled=True, percentage=20)

    session.interact_user_followers(['djsnake', 'dukedumont', 'skrillex'], amount=200, randomize=True)

finally:
    session.end()

**Comment by Tjorriemorrie** [comment]
This has been fixed. Can you please pull from master and try again.
