### ISSUE TITLE
Unable to start InstaPy

### ISSUE THREAD

**Issue by benjamin-ollier** [InstaPy/InstaPy#1600]
<img width="489" alt="capture d ecran 2018-03-08 a 23 17 06" src="https://user-images.githubusercontent.com/33257076/37297475-1921d5bc-261e-11e8-8400-5e9f99a475bf.png">
<img width="579" alt="capture d ecran 2018-03-12 a 17 47 49" src="https://user-images.githubusercontent.com/33257076/37297476-1948db9e-261e-11e8-9573-53186206c9a6.png">
Where is the problem ? I can't play the script

**Comment by windgan** [comment]
I am not sure, but try to use `'` from `'natgeo'` literal in your login and password variables instead of `‘…’`

**Comment by martinkuna** [comment]
Please do not make duplicate issues, simply respond to your original issue https://github.com/timgrossmann/InstaPy/issues/1568
@timgrossmann close old issue please


That and in the future try a different editor, character encoding is off
Did you get it working?
