### ISSUE TITLE
Request: Add funtion of liking pictures of certain accounts

### ISSUE THREAD

**Issue by jerihub** [InstaPy/InstaPy#1605]
Hey there,

since I know exactly who my competitors are - I am wondering if it's possible to add a line to set the bot only on liking the followers of certain accounts.

Since I am new on github - I hope this request wasn't asked somewhere before. Didn't find it.

Maybe this function will help some others in the same position. Thx!

**Comment by Tjorriemorrie** [comment]
[Interact with someone else's followers](https://github.com/timgrossmann/InstaPy#interact-with-someone-elses-followers)
