### ISSUE TITLE
Hi guys there is a way for run the instapy in a infinity loop without breaking the instagram rules?

### ISSUE THREAD

**Issue by CamiloB** [InstaPy/InstaPy#1608]
## Expected Behavior
Hi guys there is a way for run the instapy in a infinity loop without breaking the instagram rules?
## InstaPy configuration
i use the quickstart.py

**Comment by westondeboer** [comment]
You can set it up in cron or whatever scheduling software to run it every hour or so. Just keep in mind of how many likes and follows will happen in a day when you do this.

**Comment by CamiloB** [comment]
@westondeboer  ok thanks which free software did you advice me for this  or which are the spechs to run it, sorry i just don't know to much about that

**Comment by martinkuna** [comment]
If you are on Linux, use cron:
http://www.unixgeeks.org/security/newbie/unix/cron-1.html
https://crontab.guru/

If you are on Windows, use Task Scheduler:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa384006(v=vs.85).aspx

**Comment by keusta** [comment]
@CamiloB if you're planning to use cron, you have to create a .sh file that launch your quickstart, to chmod the .sh file to make it executable and to define the path to the .sh file in your cron task. I was unlucky trying to launch the .py from cron directly because of python root path!

**Comment by martinkuna** [comment]
@keusta python root path? Are you modifying the root users/system cron or your users cron? Are you using crontab to modify cron?

Specify the absolute path to python and your .py in your cron and it will do just fine launching within the cron environment:

sudo xvfb-run -a /usr/bin/python /home/pi/Projects/instapy/quickstart.py

See: https://github.com/timgrossmann/InstaPy/issues/1553

**Comment by CamiloB** [comment]
yes i will use cron on ubuntu 14.0.4, i'm searching tutorials to see how to schedule the instapy if i can do it ill te you guys thanks a lot

**Comment by martinkuna** [comment]
@CamiloB
Just open terminal and type ‘crontab -e’
This will open your cron scheduler with your editor. You must add a line to the end of that file containing the command you wish to run, use ‘absolute paths’ for python and the QuickStart.py and be sure to include the leading time settings. Using the links I provided above you should be able to do it :) also an example of my cron entry is above.

Good luck!

**Comment by CamiloB** [comment]
@martinkuna hey man thanks a lot! i already follow your steps but now im wondering how can i set the time when i want to activate i use this, i want to run it every 6 hours

sudo xvfb-run -a /usr/bin/python/ home/ubuntu/InstaPy/quickstart.py

as you tell me but i don't know where the time settings

**Comment by martinkuna** [comment]
The time goes before sudo, in crontab it shows you an example. A little confusing at first but check out this tool to make it easier: https://crontab.guru/ and google how to configure cron time, it’s difficult to explain quickly other than it’s a series of numbers before your command that translates into a time or frequency of time(s)

**Comment by joanroig** [comment]
You can use my code snippet from here, you'll need to install schedule module:

#1632

**Comment by CamiloB** [comment]
@joanroig  ok thanks a lot man ill try that to  @martinkuna i already see the cron guru and now i set that up thanks a lot

**Comment by CamiloB** [comment]
@martinkuna hi i already do that but i got this error `/usr/bin/python/: not found` i literally copy and paste the path but i have 3 diferent python folders python, python2, python3

**Comment by CamiloB** [comment]
@keusta hi i was reading again to see where i was failed and i see that you tell me abot the .sh file so how can i create that? i guess my trouble is for that

**Comment by CamiloB** [comment]
Hi guys i already did it i install the schedule and i need to reboot and put in the same folder the schedule https://github.com/dbader/schedule repo and now is working just fine i use your example but i change some things @joanroig  thanks a lot to everyone
