### ISSUE TITLE
Unfollows stop at 246

### ISSUE THREAD

**Issue by westondeboer** [InstaPy/InstaPy#1612]
I have it setup to unfollow 1000 and it seems to always stop at 246 unfollows

## Expected Behavior
I expect it to unfollow 1000 users. 

## Current Behavior
It stops at unfollowing at 246 users.

I am going to assume that this is because of when it goes down the follow list, it doesn't go down the list of followed users enough.

**Comment by windgan** [comment]
Same problem.
