### ISSUE TITLE
Feature request: move through videos faster when using set_dont_unfollow_active_users

### ISSUE THREAD

**Issue by michaloslav** [InstaPy/InstaPy#1617]
Hey, I use the set_dont_unfollow_active_users function all the time but I've noticed a small problem with it. When it's getting the list of people who liked a photo I posted, it works great but when it gets to a video post, it freezes for a while. I'm guessing it's trying to get the list of people who liked it but since it can't get it, it stops for like half a minute before moving on to the next post. This isn't a big issue, it works fine eventually but it slows down the start of each session by several minutes and it's really unnecessary. Would it be possible to move to the next post quicker if you can't get the likes? It should be quite easy to do, you'd probably just have to change one number and it would make it go through the start of the session a lot quicker

**Comment by Tjorriemorrie** [comment]
I think it can't find an element and times out after the given 25 implicit wait.

**Comment by michaloslav** [comment]
I think that might be the case but honestly, as someone who uploads tons of videos on Insta, this can mean like 5 minutes of wasted time at the beginning of every session which seems pretty stupid since you could just change the wait time and it could go through the videos in a few seconds. Alternatively, you could check if there is a play button on top of the post, if there is, that means it's a video and you should go to the next post. The latter could require a bit more coding (and honestly, I don't know how Selenium works so I'm not gonna be the one to do it) but the performance could be a lot better.
