### ISSUE TITLE
Problem updating with Git pull

### ISSUE THREAD

**Issue by Namaslayer** [InstaPy/InstaPy#1618]
## Expected Behavior
updates automatically when using git pull command

## Current Behavior
Update aborts because of an error:

```
From https://github.com/timgrossmann/InstaPy
   2a611cc..bace317  master     -> origin/master
Updating 2a611cc..bace317
error: Your local changes to the following files would be overwritten by merge:
	instapy/instapy.py
Please, commit your changes or stash them before you can merge.
```

I made a manual update to the code a while back, but can't remember exactly what I did. Is there a way to authorize an override so it still updates without me changing the code back?

**Comment by Tjorriemorrie** [comment]
`git stash`
` git pull`
`git stash pop`
