### ISSUE TITLE
Issues After latest update

### ISSUE THREAD

**Issue by DamnGoodWebsites** [InstaPy/InstaPy#1619]
## Expected Behavior
Functional script after updating
## Current Behavior
Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 270, in login
    self.bypass_suspicious_attempt):
  File "/root/InstaPy/instapy/login_util.py", line 133, in login_user
    "//select[@class='_fsoey']/option[text()='English']").click()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: headless chrome=65.0.3325.162)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.9.0-6-amd64 x86_64)
## InstaPy configuration

Quickstart.py modified for headless=true, 

Configured using [step by step](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md) which was previously used without issue. 

Any ideas?

**Comment by Tjorriemorrie** [comment]
Update your chromedriver to 2.36

**Comment by cormo1990** [comment]
![traceback](https://user-images.githubusercontent.com/36590321/37388899-875c620a-2762-11e8-82aa-291f307434fb.png)
Is the same error? can you help me please
thanks a lot

**Comment by PJUllrich** [comment]
I receive the same Exception even with `chromedriver` at `2.36`

**Comment by cormo1990** [comment]
i solve the issue reinstalling InstaPy...

**Comment by PJUllrich** [comment]
Confirmed. I could solve the error by pulling the latest updates.

**Comment by windgan** [comment]
@cormo1990 
> Cannot read property 'followed_by'

This error was fixed in #1610

**Comment by CharlesCCC** [comment]
if confirmed issue fixed by PR #1610 please close this issue @DamnGoodWebsites

**Comment by DamnGoodWebsites** [comment]
@CharlesCCC I reinstalled Chromedriver & Instapy with the latest version - same issues: 


```
Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    session.login()
  File "/home/username/InstaPy/instapy/instapy.py", line 270, in login
    self.bypass_suspicious_attempt):
  File "/home/username/InstaPy/instapy/login_util.py", line 133, in login_user
    "//select[@class='_fsoey']/option[text()='English']").click()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_respo
nse
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: headless chrome=65.0.3325.162)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.9.0-6-amd64 x8
6_64)
```

**Comment by CharlesCCC** [comment]
@DamnGoodWebsites the issue you are having is different than this one. please check other thread to see if someone have similar solution or not, if not feel free to open a new thread.

**Comment by DamnGoodWebsites** [comment]
This only began to occur after the issues (#1610) from yesterday, am not sure what to do at this point. I don't feel like it's necessary to open another thread with the same title & information @CharlesCCC

**Comment by CharlesCCC** [comment]
@DamnGoodWebsites this seems a issue caused by the Instapy not able to select the language through the page, it had nothing to do with the change from #1610 . 

I believe similar issue has already created.

**Comment by DamnGoodWebsites** [comment]
@CharlesCCC - I understand they're not related only mentioned it because this is the error I received after updating from the issue causing 1610. That said, I am still non-functional, even after testing the proposed solution. If I need to, I will be happy to create another issue, but seems redundant.

**Comment by CharlesCCC** [comment]
@DamnGoodWebsites delete this piece of code for now 
https://github.com/timgrossmann/InstaPy/blob/master/instapy/login_util.py#L131-L133 
Until there is better solution out there. Assume your browser is using English for Instagram.com

**Comment by DamnGoodWebsites** [comment]
Thank you! I will give that a shot & report back when I am able!

**Comment by DamnGoodWebsites** [comment]
@CharlesCCC - you're the man! Thank you for your continued assistance. This is officially closed, now! 

```
INFO [2018-03-14 18:38:29] [damngoodwebsites]  Logged in successfully!
INFO [2018-03-14 18:38:30] [damngoodwebsites]  Tag [1/1]
INFO [2018-03-14 18:38:30] [damngoodwebsites]  --> natgeo
```

**Comment by ghost** [comment]
Deleting that piece of code worked!! Thank you so much!!
