### ISSUE TITLE
what is wrong? instapy crash..

### ISSUE THREAD

**Issue by gedankenstrom** [InstaPy/InstaPy#1620]
pi@raspberrypi:~ $ ./instagram-username.sh 
INFO [username]  Session started - 2018-03-14 09:38:13
Cookie file not found, creating cookie...
INFO [username]  Logged in successfully!
Traceback (most recent call last):
  File "username.py", line 36, in <module>
    .set_switch_language(False)\
  File "/home/pi/bot/InstaPy/instapy/instapy.py", line 271, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "/home/pi/bot/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: window._sharedData.entry_data.ProfilePage[0].user is undefined
Stacktrace:
    at anonymous (https://www.instagram.com/username/ line 69 > Function:1)
    at handleEvaluateEvent (https://www.instagram.com/username/:69)
pi@raspberrypi:~ $

**Comment by cormo1990** [comment]
Hi @bjo3rns ,
probably you can find your answer in the following post

#1619 and #1610

**Comment by gedankenstrom** [comment]
@cormo1990 thank you. 

InstaPy like only 27 pictures. can you help?

In my config I have set:
.like_from_image(url='https://instagram.com/p/xxxx/', amount=100) \

**Comment by Subway19** [comment]
@bjo3rns  yes here also it likes 25 pictures no matter what I set the value

**Comment by cormo1990** [comment]
Hi @bjo3rns and @Subway19 
below the reference for a similar solution for yours issue.


#1513 #1590 #1456

**Comment by Subway19** [comment]
@cormo1990 it it merged in the master branch?

**Comment by cormo1990** [comment]
@Subway19 yes i suppose that because I've just reinstall the master branch and i don't have that issue.
let me know if it works.

**Comment by gedankenstrom** [comment]
```
pi@raspberrypi:~/bot/InstaPy $ git pull
Already up-to-date.
pi@raspberrypi:~/bot/InstaPy $ 
```

its not in the master branch..

**Comment by cormo1990** [comment]
@bjo3rns man, i suggest you to reinstall all InstaPy.
this morning i did that and now works fine.

**Comment by gedankenstrom** [comment]
@cormo1990 i have now reinstall the master branch. 

> INFO [2018-03-14 11:00:56] [user]  Image from: b'parkroyalpickering'
> INFO [2018-03-14 11:01:11] [user]  Number of Followers: 7702
> INFO [2018-03-14 11:01:11] [user]  --> Image not liked: b'Number of followers exceeds limit'
> INFO [2018-03-14 11:01:11] [user]  [2/27]
> INFO [2018-03-14 11:01:11] [user]  https://www.instagram.com/p/BgTKfZ8DKl5/?tagged=archdaily
> INFO [2018-03-14 11:01:18] [user]  Image from: b'graham_atkinshughes'
> INFO [2018-03-14 11:01:33] [user]  Number of Followers: 1096
> INFO [2018-03-14 11:01:33] [user]  Link: b'https://www.instagram.com/p/BgTKfZ8DKl5/?tagged=archdaily'
> INFO [2018-03-14 11:01:33] [user]  Description: b'brighten up your thinking space, love this image, simple and graphic and #colourful\n\nStyling @susiecleggstylist shot for @duluxuk\n#photography #designphotography #interiordesign #interiorlovers #interiordesign #homedesign #interiorsphotography\n#architecture #architects #archilovers #architecturelovers\n#builtin #interiors #interiorinspo #designblogger #instainteriors #interiordesign #design #interiordesigner #house\n#minimalistism #contemporary #minimalism #wonderful #architecture #archdaily #housegoals #homedetails #modern #homeinspo #homeinspiration #minimal #atmosphere #colour #colourtherapy #dreamoffice #dreamstudy #studyroom #study'
> INFO [2018-03-14 11:01:40] [user]  --> Image Liked!
> INFO [2018-03-14 11:01:42] [user]  --> Not commented
> INFO [2018-03-14 11:01:44] [user]  --> Not following
> INFO [2018-03-14 11:01:45] [user]  [3/27]
> INFO [2018-03-14 11:01:45] [user]  https://www.instagram.com/p/BgTKcmXlsD3/?tagged=archdaily
> INFO [2018-03-14 11:01:53] [user]  Image from: b'hyla_architects'
> INFO [2018-03-14 11:02:08] [user]  Number of Followers: 1634
> INFO [2018-03-14 11:02:08] [user]  Link: b'https://www.instagram.com/p/BgTKcmXlsD3/?tagged=archdaily'
> INFO [2018-03-14 11:02:08] [user]  Description: b'#conservation #shophouse at #kampongglam \n#architecture #architecturelovers #archilovers #architectureporn #art #architecturaldesign #architectura #arquitetura #arquitectura #dezeen #archdesign #archinect #archdaily #archinectprojects #housedaily\n#beautiful #building #interiors #interiordesign #house #style #housedecor #designboom #architecturalphotography #derekswalwell'

**Comment by cormo1990** [comment]
@bjo3rns ok, #1365 may be the solution for that

**Comment by Subway19** [comment]
@cormo1990  The issue is still there. It likes 25 images only. good work done at #1365  but looks like its not yet merged in the master branch
