### ISSUE TITLE
Unable to unfollow

### ISSUE THREAD

**Issue by michaloslav** [InstaPy/InstaPy#1624]
## Expected Behavior
should unfollow people

## Current Behavior
I get this:

`INFO [2018-03-14 14:37:23] [mikemaxden]  Number of people followed automatically remaining: 54
unable to get user information
 'user'
Iteration 1 finished.
INFO [2018-03-14 14:37:28] [mikemaxden]  Session ended - 2018-03-14 14:37:28
INFO [2018-03-14 14:37:28] [mikemaxden]  --------------------

Traceback (most recent call last):
  File "quickstart.py", line 38, in <module>
    session.unfollow_users(amount=40, onlyNotFollowMe = True, sleep_delay = 60)
  File "/home/michaloslav/InstaPy/instapy/instapy.py", line 1507, in unfollow_users
    self.logfolder)
  File "/home/michaloslav/InstaPy/instapy/unfollow_util.py", line 189, in unfollow
    variables['id'] = user_data['id']
UnboundLocalError: local variable 'user_data' referenced before assignment`

## InstaPy configuration
`from instapy import InstaPy

insta_username = 'mikemaxden'
insta_password = ''

# set headless_browser=True if you want to run InstaPy on a server
try:
    # set these if you're locating the library in the /usr/lib/pythonX.X/ directory
    # Settings.database_location = '/path/to/instapy.db'
    # Settings.browser_location = '/path/to/chromedriver'

    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      multi_logs=True)
    session.login()

    # settings
    session.set_upper_follower_count(limit=1000)
    session.set_lower_follower_count(limit=5)
    session.set_user_interact(amount=5, randomize=True, percentage=20, media='Photo')
    session.set_do_follow(enabled=True, percentage=60)
    session.set_do_like(enabled=True, percentage=20)
    # session.set_smart_hashtags(['area21', 'mikewilliams', 'r3hab'], limit=5, sort='top', log_tags=True)
    session.set_do_comment(enabled=True, percentage=5)
    session.set_comments(['AMAZING!', 'Awesome!!', 'Nice!', 'Love it!'])
    session.set_dont_include([])
    session.set_dont_like(['musician', 'beats', 'housemusic', 'musicproducer', '#producer', '#promoter'])
    session.set_dont_unfollow_active_users(enabled=True, posts=23)

    # actions
    for i in range(10):
        try:
            # session.like_by_tags(amount=50, use_smart_hashtags=False, tags=['area21', 'mikewilliams', 'r3hab'])
            # session.follow_user_followers(['area21', 'r3hab'], amount=20)
            # session.unfollow_users(amount=100, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', onlyNotFollowMe=True, sleep_delay=60)
            # session.interact_user_followers(['r3hab', 'area21'], amount = 30)
            session.unfollow_users(amount=40, onlyNotFollowMe = True, sleep_delay = 60)
        finally:
            print("Iteration " + str(i + 1) + " finished.")

finally:
    # end the bot session
    session.end()
`

**Comment by windgan** [comment]
This issue was fixed in PR #1616

**Comment by michaloslav** [comment]
You're right, I got the new merge and it works fine
