### ISSUE TITLE
Best settings for quickstart.py?

### ISSUE THREAD

**Issue by ManuCit** [InstaPy/InstaPy#1625]
Hi guys, I just wanna know your settings for the main file, the quickstart, like percentage of the comments or of the follower, so in this way it's easier for the new users who use instapy to find a good configuration, what do you think?

**Comment by ghost** [comment]
```
session.set_do_comment(True, percentage=50)
session.set_do_like(True, percentage=70)
session.set_do_follow(True, percentage=70)
```
This. Is okay. 
Multiple times if I put more than 50% to session.set_do_comment, i'm banned 24h from posting any comments and post's captions.

`session.interact_user_followers(['friend1'], amount=1000, randomize=True)`
This is okay too.

**Comment by imbarismustafa** [comment]
@ValentinMebarki How do you solve the issue with liking only 27 posts?

**Comment by ManuCit** [comment]
@ValentinMebarki  thanks, that's a good way for comments, but the percentage of the following? Is not too high?
@imbarismustafa I resolved yesterday that problem with this thread #1365

**Comment by ghost** [comment]
I used this conf during 2 weeks. In 24h you can follow and interact with 1000 guys in a row.
So 70% of following is OK.

**Comment by ManuCit** [comment]
@ValentinMebarki ok thanks.

**Comment by buecherclub** [comment]
hey can someone pls send me his settings 
with the activitys and general settings 
thx
