### ISSUE TITLE
Error: ImportError: No module named pyvirtualdisplay InstaPy ended

### ISSUE THREAD

**Issue by MericFournier** [InstaPy/InstaPy#1626]
I get this error when trying the InstaPy GUI for the first time.
Then trying "pip install pyvirtualdisplay" but get --> 

" Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/s1/9zbmhb_s4tz081cqb5dx7fr40000gn/T/pip-build-uw9QDZ/EasyProcess/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/s1/9zbmhb_s4tz081cqb5dx7fr40000gn/T/pip-WmWohk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/s1/9zbmhb_s4tz081cqb5dx7fr40000gn/T/pip-build-uw9QDZ/EasyProcess/ " 

Anyone could help ? :)

**Comment by Tjorriemorrie** [comment]
is that the whole stacktrace?

**Comment by julzKB** [comment]
@MericFournier Did you get any resolution on this ?
