### ISSUE TITLE
Bug in _sharedData.entry_data

### ISSUE THREAD

**Issue by cheemengs** [InstaPy/InstaPy#163]
Options:
dont_like = ['fuck', 'shit', 'bad', 'lousy', 'spit', 'porn', 'disgusting', 'ass']
ignore_words = ['fuck', 'shit', 'bad', 'lousy', 'spit', 'porn', 'disgusting', 'ass']
friend_list = ['xxx']
#like_tags = ['homemade', 'tasty']
like_tags = ['tasty', 'delicious']
InstaPy(username="xxx", password="xxx")\
  .login() \
  .set_use_clarifai(enabled=True, secret='xxx', proj_id='xxx') \
  .set_dont_include(friend_list) \
  .set_dont_like(dont_like) \
  .set_ignore_if_contains(ignore_words) \
  .like_by_tags(like_tags, amount=950) \
  .clarifai_check_img_for(['nsfw']) \
  .clarifai_check_img_for(like_tags, comment=False) \
  .end()

> [340/950]
> Traceback (most recent call last):
>   File "F:\projects\instapy\quickstart.py", line 20, in <module>
>     .set_ignore_if_contains(ignore_words) \
>   File "F:\projects\instapy\instapy\instapy.py", line 271, in like_by_tags
>     self.username, self.like_by_followers_upper_limit, self.like_by_followers_lower_limit)
>   File "F:\projects\instapy\instapy\like_util.py", line 94, in check_link
>     post_page = browser.execute_script("return window._sharedData.entry_data.PostPage")
>   File "C:\Python27\lib\site-packages\selenium-2.53.6-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 465, in execute_script
>     'args': converted_args})['value']
>   File "C:\Python27\lib\site-packages\selenium-2.53.6-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 236, in execute
>     self.error_handler.check_response(response)
>   File "C:\Python27\lib\site-packages\selenium-2.53.6-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
>   (Session info: chrome=57.0.2987.133)
>   (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.14393 x86_64)

**Comment by timgrossmann** [comment]
@cheemengs This won't solve the problem, but you have to use `.like_by_tags` as the last command.
`.clarifai_check_img` has to be initialized before running the liking.

**Comment by cheemengs** [comment]
thank you @timgrossmann

**Comment by imovertheinternet** [comment]
I have this issue as well. Also using python 2.7 & chromedriver 2.9 Im on linux though.

**Comment by timgrossmann** [comment]
@imovertheinternet I don't really get why you would want to use python2 ???...

**Comment by kamushadenes** [comment]
I have something similar just after login, whe trying to get user follower count:

Traceback (most recent call last):
  File "leiatambem.py", line 16, in <module>
    session.login()
  File "/dropbox/kamushadenes/Projects/InstaPy/instapy/instapy.py", line 88, in login
    log_follower_num(self.browser, self.username)
  File "/dropbox/kamushadenes/Projects/InstaPy/instapy/print_log_writer.py", line 10, in log_follower_num
    followed_by = browser.execute_script("return window._sharedData.entry_data.ProfilePage[0].user.followed_by.count")
  File "/home/kamushadenes/.pyenv/versions/InstaPy/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 484, in execute_script
    'args': converted_args})['value']
  File "/home/kamushadenes/.pyenv/versions/InstaPy/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "/home/kamushadenes/.pyenv/versions/InstaPy/lib/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 164, in check_response
    raise exception_class(value)
