### ISSUE TITLE
Memory Leak - filling memory at 500MB/s during follow users.

### ISSUE THREAD

**Issue by GitNees** [InstaPy/InstaPy#1630]
## Expected Behavior
No excessive memory usage
## Current Behavior
During random sessions, it will start to eat all memory. When I caught it doing it, it happened while following users. It writes about 500MB/s to memory. I have 24GB RAM, it fills it up and then it starts to write to the swapfile. I noticed my SSD has written 400GB EXTRA after a session when this happens. This means It cannot be ran anymore unattended, as it would destroy an SSD this way. So I killed the process while I saw it filling the memory This has happened several time I guess, since my drive has written about 1.7TB extra that would otherwise not have been written by me, in a few days.

Not sure what triggers it when the memory leak starts to happen.

If there is a way to troubleshoot, I would gladly help.

**Comment by igisho** [comment]
Same issue here. You probably using follow_user_followers which is causing the memory leak. It is also documented here: https://github.com/timgrossmann/InstaPy/issues/1231

**Comment by GitNees** [comment]
Aha thx! I was looking of someone has it, but couldn't really find the issue, yes indeed using follow_user_followers

Been reading a bit on memory debuggin on python. trying some stuff out. Just weird it isn't happening always.

**Comment by martinkuna** [comment]
Interesting, I run on a raspberry pi 3 with a tiny SD card (8 GB?!) and have not noticed any issues like this! What are you running (Operating system) @GitNees and @igisho !?

**Comment by GitNees** [comment]
Im running it on windows. @martinkuna When I don't follow user followers, doesn't happen. If you read the other documented issue, seems it is related when script wants to follow someone, that you already followed.

**Comment by igisho** [comment]
I'm running Mac OS High Sierra

**Comment by igisho** [comment]
@GitNees what python version you running?

**Comment by GitNees** [comment]
@igisho 3.7

**Comment by jabrekadabre** [comment]
I am experiencing the same problem. I'm running it on Ubuntu. Everything starts to lag to the point where the process of follow user followers cannot be done.

**Comment by Tjorriemorrie** [comment]
What is the size of your db? I think the write from update_activity might be a factor that should be investigated as well. It's triggered by by scroll_bottom. You could try to uncomment it at instapy.util.scroll_bottom and see if you have better performance? Can be a quick check to see what it's effect is

**Comment by jabrekadabre** [comment]
Sorry, don't exactly know how to do that, but I have tried changing Randomize to False, so that there is almost no scrolling involved and it worked fine since. I'm not sure if there is even any order in followers list, so the result is probably the same.

**Comment by Tjorriemorrie** [comment]
@jabrekadabre what is the size of `db/instapy.db`?

**Comment by jabrekadabre** [comment]
8,2 kB

**Comment by Tjorriemorrie** [comment]
`tracemalloc` dump for `follow_user_followers`:

`amount=10`:
```
Top 10 lines
#1: instapy\\unfollow_util.py:546: 13.4 KiB
    btnPerson = list(zip(follow_buttons, person_list))
#2: json\decoder.py:355: 9.3 KiB
    obj, end = self.scan_once(s, idx)
#3: remote\webdriver.py:262: 4.8 KiB
    converted[key] = self._wrap_value(val)
#4: lib\sre_parse.py:416: 2.8 KiB
    not nested and not items))
#5: urllib\\request.py:604: 2.4 KiB
    opener.add_handler(klass())
#6: json\encoder.py:256: 1.9 KiB
    self.skipkeys, _one_shot)
#7: lib\sre_compile.py:146: 1.3 KiB
    _compile(code, p, (flags | add_flags) & ~del_flags)
#8: <string>:14: 1.2 KiB
#9: urllib\\request.py:2671: 1.1 KiB
    return getproxies_environment() or getproxies_registry()
#10: instapy\\unfollow_util.py:587: 1.1 KiB
    follow_restrict[person] = follow_restrict.get(person, 0) + 1
125 other: 45.3 KiB
Total allocated size: 84.7 KiB
```

`amount=100`:
```
Top 10 lines
#1: lib\queue.py:169: 219.7 KiB
    while not self._qsize():
#2: _pydevd_bundle\pydevd_comm.py:442: 109.8 KiB
    cmd = self.cmdQueue.get(1, 0.1)
#3: lib\queue.py:176: 67.1 KiB
    return item
#4: lib\threading.py:304: 66.9 KiB
    self._acquire_restore(saved_state)
#5: lib\threading.py:291: 66.9 KiB
    saved_state = self._release_save()
#6: lib\threading.py:286: 66.9 KiB
    if not self._is_owned():
#7: lib\queue.py:158: 66.9 KiB
    with self.not_empty:
#8: lib\queue.py:173: 54.9 KiB
    self.not_empty.wait(remaining)
#9: email\_policybase.py:316: 36.5 KiB
    return self._sanitize_header(name, value)
#10: email\_policybase.py:287: 36.5 KiB
    if _has_surrogates(value):
506 other: 1323.1 KiB
Total allocated size: 2115.4 KiB
```

It seems the queue grows.

**Comment by GitNees** [comment]
It's been a while, haven't had time to debug and didn't follow any more updates.

Guess this still is a problem?
