### ISSUE TITLE
Session end error. Name "Session" is not defined. Raspberry Pi

### ISSUE THREAD

**Issue by imbarismustafa** [InstaPy/InstaPy#1631]
The error that i am getting is:

Traceback (most recent call last):
  File "quickstart.py", line 37, in <module>
    session.end()
NameError: name 'session' is not defined
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x75e4d6b0>> ignored

How can I solve this? Thanks! 
I run the code on Raspberry Pi 3 Noobs 4.7

**Comment by imbarismustafa** [comment]
I changed the code little bit and now i am getting this:

Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    multi_logs=True)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 145, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 236, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x75e506b0>> ignored

How can I solve this? Thanks!
I run the code on Raspberry Pi 3 Noobs 4.7

**Comment by imbarismustafa** [comment]
I found that chromedriver is the issue. I tried to install and move to the folder but i get this issue:

root@raspberrypi:/home/pi# apt-get install chromedriver
Reading package lists... Done
Building dependency tree       
Reading state information... Done
chromedriver is already the newest version (63.0.3239.84-1~deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@raspberrypi:/home/pi# mv /usr/bin/chromedriver /path/to/InstaPy/assets/chromedriver
mv: cannot move '/usr/bin/chromedriver' to '/path/to/InstaPy/assets/chromedriver': No such file or directory
root@raspberrypi:/home/pi# 

How can I solve this? Thanks!
I run the code on Raspberry Pi 3 Noobs 4.7

**Comment by imbarismustafa** [comment]
I went to the bin folder and i did not see the chromedriver folder. It says its installed but its not in the location. How can I find and move it?

How can I solve this? Thanks!
I run the code on Raspberry Pi 3 Noobs 4.7

**Comment by imbarismustafa** [comment]
I did this: 

pi@raspberrypi:~ $ find chromedriver
find: ‘chromedriver’: No such file or directory

still no luck...

**Comment by condomfighters** [comment]
I get this error:   
`File "C:\Users\A\Desktop\Insta\instapy\instapy.py", line 271, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\Users\A\Desktop\Insta\instapy\print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "C:\Users\A\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "C:\Users\A\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\A\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: chrome=65.0.3325.162)
  (Driver info: chromedriver=2.36.540470 (e522d04694c7ebea4ba8821272dbef4f9b818c91),platform=Windows NT 10.0.16299 x86_64)`

I installed latest chrome driver but it did not fix it
did you try with geckodriver?
EDIT: fixed issue by following this https://github.com/timgrossmann/InstaPy/pull/1610

**Comment by imbarismustafa** [comment]
@condomfighters I restarted the raspberry pi 3 and installed everything again because of the issue you provided. The issue is merged and it should be in the file right? I did sudo git clone and cloned the updated files that are merged but I have the issues provided in my previous comments.

**Comment by Tjorriemorrie** [comment]
Are you sure your chromedriver is in assets? Otherwise check its permissions.

**Comment by imbarismustafa** [comment]
@Tjorriemorrie its not in my assests. Also is not in its default place. I tried to move to assets but it says that its not there in its original location. With permission i dont understand what do you mean by that? I had a permission error with another script and I was not able to edit any file in the folder but that was different from instapy. In instapy i can edit the files but as i described previously i am getting errors.

**Comment by Tjorriemorrie** [comment]
Ah, I don't have rasberry :(
You can try run `which chromedriver`
if you don't have an output then it's not installed, otherwise use that path and put the string in settings.py for the browser_location.
