### ISSUE TITLE
Script Execution is Too Fast

### ISSUE THREAD

**Issue by xxxfinelinexxx** [InstaPy/InstaPy#1635]
Since the update of repository files and chromedriver the execution of the script is too fast.
Less than 10 seconds to select a photo+like it+comment it
Before it was taking a lot to do this process
What's happened?
Can someone help me?
Thanks in Advance

**Comment by alessiomtt** [comment]
Try to use:

`session.set_sleep_reduce(120)`

percentage >100 to increese the sleep time

**Comment by xxxfinelinexxx** [comment]
I've tried it, the speed seems to be quite the same...maybe a little less
Can I try to increase the sleep time?

ie.
session.set_sleep_reduce(200)

**Comment by xxxfinelinexxx** [comment]
with 200 seems to be better!

just another info, I'm receiving a lot of these errors....what does they mean?

[14144:5948:0315/115526.694:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED

**Comment by sionking** [comment]
chromedriver and chrome issue.
I wish chrome wouldn't push the updates since 62 is ideal version.

**Comment by alessiomtt** [comment]
@sionking , #1633 this is another issue related to chromedriver?
