### ISSUE TITLE
Gender recognition: https://genderize.io/#overview

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#1636]
## Expected Behavior
to recognize gender

## Current Behavior
can't recognize gender

## Possible Solution (optional)
using the https://genderize.io/#overview which check the name with optional country / language for a db that return results male/female

Is that enough ? maybe we can set it to true only when probability is 1.
Should I implement ?

**Comment by riccardorighettiphoto** [comment]
Interesting.

**Comment by isaniomoraes** [comment]
Sounds good.

Also anyone knows how private/paid instagram bots has this gender filter?

like:
![screenshot-from-2018-03-15-15-56-29](https://user-images.githubusercontent.com/3224086/37485182-8778cb54-2869-11e8-80a6-59ccb24090b4.png)

source: https://growsoci.al/en/

**Comment by isaniomoraes** [comment]
Hey @sionking, did you saw #975 :slightly_smiling_face:

**Comment by sionking** [comment]
Hi  @isaniomoraes
Thanks I am now the bounty hunter for this.
I really don't know how can someone recognize the gender beside name/image reco.
I mostly think it is just an advertisement, I have the another very complicated bot that don't have this option.

**Comment by sionking** [comment]
maybe they use:
https://docs.opencv.org/2.4/modules/contrib/doc/facerec/tutorial/facerec_gender_classification.html
or google images.
There is a lot of tools but we need some one to implement it ! I will try my best soon.

**Comment by sionking** [comment]
https://www.kairos.com/features
emotion detection can use for comments

**Comment by sionking** [comment]
implemented and testing

**Comment by isaniomoraes** [comment]
Nice @sionking!
Looking forward to test the gender filter.
Great job so far.
