### ISSUE TITLE
ImportError: sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by alessiomtt** [InstaPy/InstaPy#1638]
After a succesfull login I have this error:

`ImportError: sys.meta_path is None, Python is likely shutting down`

,searched on the web bot did not find anything that can help me.

Maybe it's a chromdiriver issue or it's related to the google chrome version?

**Comment by Tjorriemorrie** [comment]
it's the chromedriver trying to stop the process. There should be another error why it is stopping though. anything in general.log?
