### ISSUE TITLE
Image appropriate check – false positives 

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#164]
I just checked some of those images that weren’t liked because they were marked as inappropriate and all of them seem appropriate to me:

https://www.instagram.com/p/BTE7VZhDnAg/
https://www.instagram.com/p/BTFFMr-Bc-X/
https://www.instagram.com/p/BTGSYmlDoDn/
https://www.instagram.com/p/BTFioTUjQlP
https://www.instagram.com/p/BTGVtK7FeC_/

For me, this is a bug because the check
- is very sensitive to errors and
- marks a lot of images

I’m aware that this check isn’t a InstaPy feature, but maybe we should make filtering inappropriate images an optional setting?

**Comment by timgrossmann** [comment]
@tibor Did you close this issue because you realised that just leaving `dont_like` out of your script does exactly that?
