### ISSUE TITLE
SyntaxError: invalid token

### ISSUE THREAD

**Issue by thepoison606** [InstaPy/InstaPy#1641]
Somebody know whats wrong? Running InstaPy on a Raspberry Pi 3 with Firefox. Can't login anymore.

<img width="761" alt="bildschirmfoto 2018-03-15 um 15 27 36" src="https://user-images.githubusercontent.com/37410136/37469549-c8adf184-2865-11e8-9c41-4ea3699c9d10.png">

**Comment by bgunsberger** [comment]
I have the same problem.

**Comment by C4T4** [comment]
You have to use Python 3.x or replace 
`security_code = input('Type the security code here: ')`
with
`security_code = raw_input('Type the security code here: ')`

raw_input is deprecated and only for python 2.x
