### ISSUE TITLE
unknown error: Cannot read property 'followed_by' of undefined

### ISSUE THREAD

**Issue by imewish** [InstaPy/InstaPy#1642]
Receiving this error on Ubuntu 16.04 server,
  
File "cap.py", line 10, in <module>
    session.login()
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 271, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "/home/ubuntu/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.4.0-1052-aws x86_64)

Help needed

**Comment by furk4no** [comment]
use the newest version of print_log_writer.py and like__util.py

**Comment by CharlesCCC** [comment]
make sure you pull the latest version of instapy

**Comment by imewish** [comment]
I did a fresh install of InstaPy. Now it just only likes/comment 27 users. (Which issue I have faced earlier)

**Comment by imewish** [comment]
@CharlesCCC @furk4no

**Comment by furk4no** [comment]
I don‘t really know about this problem.. I would recommend opening a new issue for that.

**Comment by CharlesCCC** [comment]
@imewish if you have read through the existing issue list, you have noticed there are multiple people have reported this issue.  the main thread is here #1365  and that is totally different than the issue you are having here.

**Comment by CharlesCCC** [comment]
@furk4no Please don't encourage people open a new issue before you or other have confirmed there are no existing one out there.

**Comment by imewish** [comment]
@CharlesCCC Brother, let me explain it again,

I had faced the issue (Only choose 27 users ) a few weeks ago, I have also reported it in a fresh thread that time. I had fixed it with #1365  
As per @uluQulu  new like_utl.py script and it worked smoothly until a few days ago.  

Then I started getting a new error which is this threads headline. 

So as you suggested, I did a fresh pull of  Instapy which is supposed to fix this issue and the issue is solved.  But again now the script stops at 27 Users.

I changed the like_utl.py again as per this #1365  which results `Cannot read property 'followed_by' of undefined ` 

How do I make it work without these two errors?

**Comment by CharlesCCC** [comment]
@imewish apparently whatever the change you made from #1365 didn't get updated with the latest version of Instagram.com web API change.  If you would like to, you can manually change the code based off the PR #1610 .   @uluQulu Not sure the status on the change your made, but you might want to PR that so we will not getting conflicting change back and forth  :P

**Comment by uluQulu** [comment]
@CharlesCCC it is not a new issue, see #1338, anyways,.
It's a pity that you've not followed ongoing conversation in #1365 
In the fix at #1365 the only place you will modify in default code is `get_links_for_tag()` function which does not and will not conflict with #1610 or any other similar commit cos that function has no any `entry_data` query

The fix [there](https://github.com/timgrossmann/InstaPy/issues/1365#issuecomment-366526517) is up-to-date for today, it's just that @imewish possibly took a ready out-dated `like_util.py` file I shared for some people there who could not manually apply the fix of 3 simple steps.

@CharlesCCC As you are a collaborator, you might want to PR yourself if wants, but unless there is no single issue I will not do that.

**Comment by CharlesCCC** [comment]
@uluQulu Yea, I agree and understand.  Thank you for keep that #1365 up and going. It is sometimes hard for me to follow every single issue when I was doing a full time job and also need help out here. 
But I appreciated any help you have provide to this great community.  
@imewish As @uluQulu have pointed out, You are likely have get a the older version of Instapy. So, please make sure you get the latest version of Instapy first and then re-apply the change @uluQulu put together from #1365
