### ISSUE TITLE
Spits out this Error

### ISSUE THREAD

**Issue by SkylimiTY** [InstaPy/InstaPy#1644]
Hey, guys, I recently tried to install Heroku and run the script on there. As soon as I installed the client and set the PATH directory. It didn't run and I tried running it throught the console as regular but it spit out this error: 

![capture](https://user-images.githubusercontent.com/36607594/37481030-f5f3ffd8-2880-11e8-977b-5f0c724414a2.JPG)

Here is my InstaPy configuration:

session = InstaPy(username=insta_username, password=insta_password, headless_browser=True)

session.login()

session.unfollow_users(amount=1000, onlyNotFollowMe=True, onlyInstapyMethod = 'FIFO', sleep_delay=60)

session.set_do_follow(enabled=True, percentage=100, times=1)

session.like_by_locations(['212999109/los-angeles-california/', '207409165/prague-czech-republic/'], amount=500)

session.like_by_tags(['traveltheworld', 'travelphotography', 'blogger', 'travelblog', 'travelgram', 'travelpic', 'destination', 'likeforfollow', 'like4follow', 'followme', 'follow4follow', 'instafollow', 'followback', 'followtrain', 'instadaily', 'instatravel', 'bloggerlife', 'blogpost'], amount=60)

session.end()

**Comment by CharlesCCC** [comment]
make sure you have the latest version of Instapy.
