### ISSUE TITLE
Raspberry Pi 3 Chrome Driver Cannot Be Found After Install

### ISSUE THREAD

**Issue by imbarismustafa** [InstaPy/InstaPy#1652]
## Expected Behavior

To be able to find chromedriver in usr/bin and move to InstaPy/assets.

## Current Behavior

root@raspberrypi:/home/pi# apt-get install chromedriver
Reading package lists... Done
Building dependency tree
Reading state information... Done
chromedriver is already the newest version (63.0.3239.84-1~deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@raspberrypi:/home/pi# mv /usr/bin/chromedriver /path/to/InstaPy/assets/chromedriver
mv: cannot move '/usr/bin/chromedriver' to '/path/to/InstaPy/assets/chromedriver': No such file or directory
root@raspberrypi:/home/pi#

## Comment (Notes)

I followed the steps for installing instapy on raspberry py but i am stuck at moving the chromedriver to assets. I checked the folder usr/bin but chromedriver is not there. Any suggestions, solutions or alternatives for getting this to work or raspberry pi 3 noobs raspberrian os?

**Comment by joanroig** [comment]
'/path/to/InstaPy/assets/chromedriver' -> You need to change this path to your current installation path, probably is '/home/pi/Desktop/Projects/InstaPy/assets'

**Comment by imbarismustafa** [comment]
@joanroig thanks for the advice. I have tried that but unfortunately the main issue is that chromedriver folder after installation is not in  /usr/bin/chromedriver and thats why i get the error no such file or directory. 

If you have any other suggestions or ideas on your mind i will be more than happy to try them. I appreciate the time. Thanks

**Comment by joanroig** [comment]
Hi again @imbarismustafa , chromedriver is not a folder, it's a file:

<img width="348" alt="captura de pantalla 2018-03-16 a las 23 06 09" src="https://user-images.githubusercontent.com/12451419/37546754-ac12313e-296e-11e8-85d7-a82450d9c408.png">

If you don't see the file in /usr/bin you can remove and install it again:

```
sudo apt-get remove chromedriver
sudo apt-get install chromedriver
```

**Comment by imbarismustafa** [comment]
@joanroig THANK YOU!

**Comment by Dijenek91** [comment]
I still have the same issue after removing the chromedriver, and reinstalling it. 
There is no chromedriver file in that location :(

Please any help?
