### ISSUE TITLE
Traceback (most recent call last):   File "quickstart.py", line 30, in <module>     session.end() NameError: name 'session' is not defined

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1654]
Traceback (most recent call last):
  File "quickstart.py", line 30, in <module>
    session.end()
NameError: name 'session' is not defined

how to fix it ... thank you..

**Comment by furk4no** [comment]
wow your title is perfect. could you post your quickstart.py?

**Comment by david-vendel** [comment]
You need to download and place new chromedriver.exe to folder assets.
(just dl it from internet)
