### ISSUE TITLE
Element not clickable at point (during security code login)

### ISSUE THREAD

**Issue by thepoison606** [InstaPy/InstaPy#1655]
Hello,

i just experienced this error. Seems like it can't send my entered security code. I am using the latest pull on a raspberry pi 3 with firefox. Any workarounds?

<img width="1415" alt="bildschirmfoto 2018-03-16 um 10 23 18" src="https://user-images.githubusercontent.com/37410136/37513991-e8adc4d6-2906-11e8-94ec-8a168ce22634.png">

Thanks so far!
Daniel

**Comment by sionking** [comment]
MANY CHROMEDRIVER ERRORS SHOULD RESOLVED BY RESTARTING THE BROWSER, WE ARE WAITING FOR THIS PR.!

**Comment by CharlesCCC** [comment]
@sionking which PR ? what you mean by restarting the browser ? Do you know what was the cause ?
