### ISSUE TITLE
Still no Pull Request for new get_links_for_tag function

### ISSUE THREAD

**Issue by FranklinClinton** [InstaPy/InstaPy#1661]
## Expected Behavior
I tell the script to like 800 pictures of the tag _vegan_. Script will find 800 pictures and like them.
## Current Behavior
I tell the script to like 800 pictures of the tag _vegan_. Script will only find 27 pictures, even if there are more.
## Possible Solution (optional)
See here: https://github.com/timgrossmann/InstaPy/issues/1365
This comment  fixxes it: https://github.com/timgrossmann/InstaPy/issues/1365#issuecomment-366526517

Everytime I clone the newest version of this repo, I have to apply this fix. Could somebody please tell me, that I'm not the only one?
And also, can somebody please create a Pullrequest for this?

## InstaPy configuration
Running on Ubuntu Server 16.04 64bit,  chrome=63.0.3239.132, chromedriver=2.35.528139 
python 3.5

**Comment by FranklinClinton** [comment]
@uluQulu Can you tell us more about this? Why is there no pull request?

**Comment by ghost** [comment]
@FranklinClinton You're right. Each time I clone the project, I must apply at least 5 fix for it to run properly.
I would also like to know what's going on here.

**Comment by Moein-9** [comment]
+1

**Comment by gruvismalt** [comment]
Same problem here, and after the most recent update, I am unable to make it work after applying the fix from https://github.com/timgrossmann/InstaPy/issues/1365

**Comment by uluQulu** [comment]
Hi guys
@FranklinClinton have a [read](https://github.com/timgrossmann/InstaPy/issues/1365#issuecomment-373394922)
@gruvismalt can you post the _traceback of the error_ or the _details of the problem_ you are getting in #1365?

**Comment by OkayDokayOkay** [comment]
@ValentinMebarki can you explain how I update my InstaPy through the MacTerminal?

**Comment by gruvismalt** [comment]
@uluQulu It was an oversight on my part. It still functions as expected once the fix is applied. Thanks again!
