### ISSUE TITLE
Questions about running multiple accounts

### ISSUE THREAD

**Issue by furk4no** [InstaPy/InstaPy#1668]
Hello guys,

I have got 3 accounts I want to run with instapy. Currently I'm using a droplet to run one account and I'd like to add 2 more.

I am executing a bash script on crontab which executes InstaPy in a screen. 
I thought it would be better to run other 'quickstart.py' files modified for the other Instagram accounts in the same screen.. Just on other times of the day that the runs do not overlap.

Another thing is that I'm not really confident about the idea to run 3 accounts  over the same Ip address. Does anyone have any experience with this??

Thank you in advance..

**Comment by DemOnJR** [comment]
Check this https://github.com/timgrossmann/InstaPy/blob/master/examples/multi-account.py

**Comment by joanroig** [comment]
I'm currently running two accounts, simply duplicate your quickstart.py and put something like the snippet I've posted here:

https://github.com/timgrossmann/InstaPy/issues/1632

Then you can set the proper times for each account at the end of the scripts. Open two terminals and you're ready to go, no crontab needed.

**Comment by Areahints** [comment]
hello I'm getting this error when I try to run multiple accounts

``Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 329, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "/root/InstaPy/instapy/print_log_writer.py", line 8, in log_follower_num
    browser.get('https://www.instagram.com/' + username)
TypeError: cannot concatenate 'str' and 'list' objects``
