### ISSUE TITLE
Selenium / Webdriver error on Digital Ocean

### ISSUE THREAD

**Issue by tekcor** [InstaPy/InstaPy#1674]
## Expected Behavior

After running multiple times through all available installation guides (official and unofficial) for installing on DigitalOcean Droplet with standard Ubuntu, I would expect a simple example to run, but I get the bellow error. Even if I reinstall the Chromium Webdriver it still throws this error. I also tried both with python 2.7 and python 3.5 and corresponding pip. I tried step by step install of the dependencies and of course the "pip intstall ." I always get this error.
I got it to work already once on Windows quite easily so I could test that my python files (quickstart.py etc) are working.

## Current Behavior

root@tek1:~/InstaPy# python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    session = InstaPy(username=insta_username, password=insta_password, nogui = True)
  File "/root/InstaPy/instapy/instapy.py", line 145, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 236, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 86, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 99, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service ./assets/chromedriver unexpectedly exited. Status code was: 127

## Possible Solution (optional)

Any Ideas?

## InstaPy configuration

latest version from github

Cheers and thanks for the good work!

**Comment by DemOnJR** [comment]
https://github.com/timgrossmann/InstaPy/issues/1667 :|

**Comment by tekcor** [comment]
Yes i saw your post but i could not reproduce it.
What is actually different from here? https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md

is it all about using python 3.4 instead of 3.5?
Other people successfully use 3.5 and 2.7 without problem, so i am confused about that..
