### ISSUE TITLE
getting this error after running instapy on my windows VPS 

### ISSUE THREAD

**Issue by millw0rm** [InstaPy/InstaPy#1675]
Hi im trying to run instapy i guess i have all requirments installed but still i get this one 

Error: file "quickstart.py" , line 8 session.follow_user_following([''],amount=,sleep_delay=,randomize=False,interact=False) ^ SyntaxError:invalid syntax

**Comment by eversionsystems** [comment]
I'm also having this issue when I try and run the script from a terminal or via CRON.  After googling it says the following

/usr/bin/python ./quickstart.py

> Looks like your problem is that you are trying to run python test.py from within the Python interpreter, which is why you're seeing that traceback.
> 
> Make sure you're out of the interpreter, then run the python test.py command from bash or command prompt or whatever.

How do I correctly run the script?  I also read that you should use a shebang before the script execution **#!/usr/bin/env** which removes the error but doesn't seem to do anything...

**Comment by sionking** [comment]
^  ?

**Comment by Tjorriemorrie** [comment]
@millw0rm paste that line from your quickstart, you've just made a typo somewhere.
From looking at what you posted, it seems you are missing the values for `amount` and `sleep_delay` after the equal sign. You can just delete those and it should work then.
