### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by eversionsystems** [InstaPy/InstaPy#1676]
When I run the script from a terminal or via CRON I get the following error.

**/usr/bin/python ./quickstart.py**

> Traceback (most recent call last):
>   File "./quickstart.py", line 1, in ?
>     from instapy import InstaPy
>   File "/home/groupcom/public_html/InstaPy/instapy/__init__.py", line 1
>     from .settings import Settings
>          ^
> SyntaxError: invalid syntax

After googling the issue is states the following

> Looks like your problem is that you are trying to run python test.py from within the Python interpreter, which is why you're seeing that traceback.
> 
> Make sure you're out of the interpreter, then run the python test.py command from bash or command prompt or whatever.

How do I correctly run the script? I also read that you should use a shebang before the script execution #!/usr/bin/env which removes the error but doesn't seem to do anything...

**Comment by Tjorriemorrie** [comment]
It's still invoked from a different working directory. Use absolute paths.
I'm not sure why it doesn't work if you run it from the terminal though.

**Comment by eversionsystems** [comment]
@Tjorriemorrie thanks for getting back to me :)  If I run the command `python quickstart.py` from the root directory of the code I get the same issue.  It works on my Windows machine just not on CentOS.  Could it be the version of python being used?  The server has 2.4.3 installed.

**Comment by eversionsystems** [comment]
@Tjorriemorrie I tried a different version of python installed on the server `python2.7 quickstart.py` and now I get a different error saying 

> ImportError: No module named pyvirtualdisplay

I should have this working after I install the missing module if my hosting provider allows me to.

**Comment by Tjorriemorrie** [comment]
Python 2.4 is not supported. 
Running the specific version like you did with 2.7: you'll have to install the dependencies for that version.
You should change your system default python to be python2.7+
