### ISSUE TITLE
TypeError: get_links_for_tag() takes from 3 to 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by emyabdel** [InstaPy/InstaPy#1679]
hi

im runing under windows10 64bits.
And the issue that I got: TypeError: get_links_for_tag() takes from 3 to 5 positional arguments but 6 were given

this is all the log:

Error: INFO [2018-03-18 19:42:47] [mark] Session started - 2018-03-18 19:42:47
WARNING [2018-03-18 19:42:47] [mark] Sorry, Record
Activity is not working on Windows. We're working to fix this soon!
INFO [2018-03-18 19:43:28] [mark] Logged in successfully!
INFO
[2018-03-18 19:43:32] [mark] Tag [1/1]
INFO [2018-03-18 19:43:32] [mark] --> b'cat'
Traceback (most recent call last):
File
"quickstart.py", line 7, in 
session.like_by_tags(['cat'], amount=66, media=None)
File "C:\Users\ME\Desktop\instapy\instapy\instapy.py"
, line 831, in like_by_tags
skip_top_posts)
TypeError: get_links_for_tag() takes from 3 to 5 positional arguments but 6 were given
InstaPy ended

**Comment by CharlesCCC** [comment]
If you are downloading from the link, you are using the latest version. When you say got another `issue`, you need be specific what the issue is. People here are to help, without any detail. People can't help you.

**Comment by emyabdel** [comment]
I thought that when I download from clone or download green button it's not the latest version, thanks for your answer and this is the issue that I got: TypeError: get_links_for_tag() takes from 3 to 5 positional arguments but 6 were given

this is all the log:

Error: INFO [2018-03-18 19:42:47] [mark] Session started - 2018-03-18 19:42:47
 WARNING [2018-03-18 19:42:47] [mark] Sorry, Record
 Activity is not working on Windows. We're working to fix this soon!
 INFO [2018-03-18 19:43:28] [mark] Logged in successfully!
 INFO 
[2018-03-18 19:43:32] [mark] Tag [1/1]
 INFO [2018-03-18 19:43:32] [mark] --> b'cat'
 Traceback (most recent call last):
 File
 "quickstart.py", line 7, in <module>
 session.like_by_tags(['cat'], amount=66, media=None)
 File "C:\Users\ME\Desktop\instapy\instapy\instapy.py"
, line 831, in like_by_tags
 skip_top_posts)
 TypeError: get_links_for_tag() takes from 3 to 5 positional arguments but 6 were given
InstaPy ended

**Comment by emyabdel** [comment]
I cant edit with my phone just to tell you tyat im runing under windows10 64bits

**Comment by CharlesCCC** [comment]
@emyabdel please go to here [https://github.com/timgrossmann/InstaPy](https://github.com/timgrossmann/InstaPy) and read the instruction on how to set it up.
