### ISSUE TITLE
Follow people who like a publication

### ISSUE THREAD

**Issue by SEOAlexRamon** [InstaPy/InstaPy#1680]
Hello everybody! I'm a InstaPy user. I have a question: Is it possible to make the Bot follow the users who "Like" a particular publication? I'm looking for this option because to gain active followers is very useful. Thanks!

**Comment by david-vendel** [comment]
Yes it is possible.
I could do it.

**Comment by Tjorriemorrie** [comment]
What is a publication? A tag, a user? an area?

**Comment by SEOAlexRamon** [comment]
@Tjorriemorrie a publication. Follow 10 people who gave like the last publication of @elonmusk. It's an example...

**Comment by david-vendel** [comment]
Hello, I have added this feature, creating 2 functions: input to the function is url address or array of usernames

**Comment by SEOAlexRamon** [comment]
Thanks for all @justdvl!

**Comment by SEOAlexRamon** [comment]
@justdvl the last question. When I enter the code that tells me (session.follow_likers("https://www.instagram.com/p/BgO7uCihPl8/", amount = 50)) it appears: 'undeclared function'. How can I declare this function? Thanks and regards.

**Comment by david-vendel** [comment]
It is not yet officially included in main code so you need to update the code manually - go to 1682 and see what changes I made and copy those functions..
Or get my fork from my profile here..
Or wait...

**Comment by SEOAlexRamon** [comment]
Okey! Thanks! I already have it! It works perfect!

**Comment by david-vendel** [comment]
Thanks.
What would you way to being able to follow users directly when the like window is opened? (But then you cant check how many followers they have).
Or when you follow them via their profile also open 2 random photos from first 9 and like them?

**Comment by SEOAlexRamon** [comment]
Good. I do not understand the question. I speak Spanish and I have a very basic level of English. Can you ask me the simplest question so that I can understand it? Another thing. I just realized that he throws me an error. I leave you a capture so you can see it.
![captura](https://user-images.githubusercontent.com/37023161/37679349-ea6b5afe-2c80-11e8-9586-35bbd98fb123.JPG)

**Comment by david-vendel** [comment]
Hi, your error was because that function was design to accept array of urls, not just 1 url as a string.
I have fixed it, now it can accept also just url.
Update your code and it will work.
