### ISSUE TITLE
Error GUI

### ISSUE THREAD

**Issue by Caradepastel** [InstaPy/InstaPy#1681]
Hello, this error appears when I run the GUI. Can you help me?

Error: File "quickstart.py", line 8
 session.set_do_follow(enabled=True, percentage=, times=)
 ^
 SyntaxError: invalid syntax

**Comment by Tjorriemorrie** [comment]
If you don't want to change the last two parameters, then you can just use:
```
 session.set_do_follow(enabled=True)
```
