### ISSUE TITLE
hi guys there is a way to give like and comment to my followers?

### ISSUE THREAD

**Issue by CamiloB** [InstaPy/InstaPy#1683]
## Expected Behavior
Like and coment my own followers ramdom
## Current Behavior
Just and comment like by tags  and location
## Possible Solution (optional)
Can i use Interact with someone else's followers?

**Comment by Tjorriemorrie** [comment]
[Interact with someone else's followers](https://github.com/timgrossmann/InstaPy#interact-with-someone-elses-followers)?

The expected differ from your solution? But your expected is a bit strange. This library isn't a CRM, it's to gain followers, but I'm sure that can be implemented as a retention strategy.

**Comment by CamiloB** [comment]
@Tjorriemorrie yes i already use Interact with someone else's followers and works i just add a second job on my code i have de principal job schedule, when this ended start to interact whit my users thanks  a lot
