### ISSUE TITLE
The bot like random image and videos? 

### ISSUE THREAD

**Issue by CamiloB** [InstaPy/InstaPy#1684]
I launch 6 times the bot, and always he goes to the same images on the tags  that i put or the location, that's normal ?
there's a way to put some code that the like or comment always goes in a random way?

## InstaPy configuration
'
from instapy import InstaPy
import schedule
import time

insta_username = ' '
insta_password = ' '

#Definir el nombre del trabajo para organizar los horarios en que se prende
def job():

 try:
    # set these if you're locating the library in the /usr/lib/pythonX.X/ directory
    # Settings.database_location = '/path/to/instapy.db'
    # Settings.browser_location = '/path/to/chromedriver'

    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      multi_logs=True)
    session.login()

    # settings
    session.set_do_comment(True, percentage=50)
    session.set_do_like(True, percentage=70)
    session.set_do_follow(True, percentage=70)
    session.set_upper_follower_count(limit=12500)
    session.set_lower_follower_count(limit = 100)
    session.set_dont_unfollow_active_users(enabled=True, posts=5)
    session.set_comments([u'ameizing! :sunglasses: ', u'Nicey pic! :sunglasses: '])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.like_by_tags(['vivienda', 'viviendas', 'viviendanueva', 'casanueva', 'casa',
              'casas', 'hogar', 'hogardulcehogar', 'hogarfeliz', 'hogares',
              'hogarideal', 'hogaresfelices', 'familia', 'familiar',
              'familianumerosa', 'familias', 'familiarreunida', 'familiafeliz',
              'apartamentosenventa', 'apartamentoenventa', 'apartamento',
              'apartamentos', 'residencia', 'hijo', 'hija', 'hijos',
              'bienestar', 'comodidad', 'sueños', 'sueños', 'casasoñada',
              'casafutura', 'hogarsoñado', 'construcción', 'construcciones',
              'arquitecto', 'constructora', 'constructoras',  'inmboliriaria',
              'matrimonio', 'matrimoniofeliz', 'matrimonioscolombia',
              'matrimonios', 'vidaenpareja', 'pareja',  'mama',
              'mamaprimeriza', 'papa', 'boda', 'bodas', 'proyectos',
              'proyectosnuevos', 'independiente', 'inversion',
              'inversionista', 'fincaraiz', 'metroxmetro', 'metrocuadrado',
              'vivendo', 'compravirtual', 'virtual', 'realidadvirtual', 'vr' ], amount=2)
    session.unfollow_users(amount=10, onlyNotFollowMe=True, sleep_delay=60)

    #locaciones

    session.comment_by_locations(['250809402/sena-centro-de-la-construccion/'], amount=2)
    session.like_by_locations(['250809402/sena-centro-de-la-construccion/'], amount=50)

    session.comment_by_locations(['973286596/jardin-plaza-pagina-oficial/'], amount=2)
    session.like_by_locations(['250809402/sena-centro-de-la-construccion/'], amount=50)

    session.like_by_locations(['284478607/unicentro-cali/'], amount=50)

    session.like_by_locations(['1095302003906653/la-diva-ciudad/'], amount=50)

    session.like_by_locations(['417739215001048/club-campestre/'], amount=50)
     
 except:
   import traceback
   print(traceback.format_exc())

 
 finally:
    # end the bot session
    session.end()
    

schedule.every().day.at("5:30").do(job)
schedule.every().day.at("8:30").do(job)
schedule.every().day.at("12:30").do(job)
schedule.every().day.at("16:30").do(job)
schedule.every().day.at("20:30").do(job)
schedule.every().day.at("1:30").do(job)

while True:
    schedule.run_pending()
    time.sleep(1)
'

**Comment by Tjorriemorrie** [comment]
Most likely the tags are not popular enough for new content at 3-4 hour intervals.
