### ISSUE TITLE
Question for contributors

### ISSUE THREAD

**Issue by komad1na** [InstaPy/InstaPy#169]
Emoji Support
You have to convert your comment to Unicode. This can safely be done by adding an u in front of the opening apostrophe: u'\u1234 some comment'

session.set_comments([ u'\u1234 WOW' , u'Nice' ])

Is it wrong to Unicode comment without emoji like second one?
Is this correct format of function call for emoji support ?

**Comment by tibor** [comment]
That's the correct way and you may also convert comments without emoji to unicode.

**Comment by komad1na** [comment]
Thanks @tibor :1st_place_medal:
