### ISSUE TITLE
[SOLVED] [MacOS]: Message: unknown error: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by akogay** [InstaPy/InstaPy#1692]
INFO [2018-03-20 22:12:47] [##@my.com]  Session started - 2018-03-20 22:12:47
INFO [2018-03-20 22:13:18] [##@my.com]  **Logged in successfully!**
**Message: unknown error: Cannot read property '0' of undefined**
  (Session info: chrome=65.0.3325.162)
  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.12.6 x86_64)

INFO [2018-03-20 22:13:20] [##@my.com]  Session ended - 2018-03-20 22:13:20
INFO [2018-03-20 22:13:20] [##@my.com]  --------------------

**Comment by akogay** [comment]
quickstart.py open browser, log in my instagram acc, wait a bit and close.
What step I have to see to repair that?

**Comment by CharlesCCC** [comment]
Please post your configure as well.

**Comment by akogay** [comment]
from instapy import InstaPy

insta_username = '##@my.com'
insta_password = '###'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()
    session.like_by_tags(['dance'], amount=10)

except Exception as e:
    print(e)

finally:
    # end the bot session
    session.end()

**Comment by akogay** [comment]
macOS Sierra
**iMac:InstaPy imac$ python --version
Python 3.6.4 :: Anaconda, Inc.**

**Comment by Tjorriemorrie** [comment]
@akogay can you pull the latest from master and run it again, and provide the full stacktrace please?

**Comment by akogay** [comment]
Thank you gyus so much. It work now!

**Comment by roliag** [comment]
Hi, exactly the same thing happens to me, how did you solve it?

**Comment by roliag** [comment]
I solved it, my problem was that I put the email in the user and not the user
