### ISSUE TITLE
Instagress is shutting down

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#170]
Not an InstaPy issue, but maybe this is interesting news for some of us:

https://petapixel.com/2017/04/20/instagram-shuts-popular-botting-service-instagress/

I think it's a big plus for InstaPy that we don't rely on
1. a centralized server/IP system
2. oAUTH

**Comment by eduardocalazansjr** [comment]
Not a big plus.
Instagram could take down the repo at anytime.
