### ISSUE TITLE
several errors it used to work like a charm nothing changed

### ISSUE THREAD

**Issue by eth030** [InstaPy/InstaPy#1700]
## Current Behavior
python quickstart.py
INFO [user]  Session started - 2018-03-21 12:24:22
INFO [user]  Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 6, in <module>
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 263, in login
    log_follower_num(self.browser, self.username, self.logfolder)
  File "/root/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: chrome=64.0.3282.167)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 3.10.0-514.26.2.el7.x86_64 x86_64)

## Possible Solution (optional)
n/a
## InstaPy configuration

from instapy import InstaPy

#if you don't provide arguments, the script will look for INSTA_USER and INSTA_PW in the environment

session = InstaPy(username='username', password='password',nogui=True)
session.login()

#likes specified amount of posts for each hashtag in the array (the '#' is optional)
session.like_by_tags(['#photooftheday', '#fit', 'fitness', 'instafit',  'travel'], amount=150)

session.end()

**Comment by sionking** [comment]
update to latest

**Comment by dataidroj** [comment]
Same problem

**Comment by Tjorriemorrie** [comment]
@dirtyissa please run ` git log | grep e1eba4dd67348015c64b8014b9dd2919019b291a` and see if you see the commit, otherwise you are not on latest master.

**Comment by dataidroj** [comment]
@dirtyissa I updated the Chromedriver file and worked again.
Go to [ChromeDriver](https://sites.google.com/a/chromium.org/chromedriver/downloads) and download the last version.
Then update your _chromedriver.exe_ file in your _/assets_ folder.

**Comment by balakedev** [comment]
Getting exactly the same thing, downloading new version of chromium driver did not help :/
