### ISSUE TITLE
"ImportError: No module named 'pyvirtualdisplay'"

### ISSUE THREAD

**Issue by michelleN27** [InstaPy/InstaPy#1707]
## Expected Behavior

It was working perfectly fine. Not sure what's wrong!
I ran quickstart.py and this is what popped up: 
## Current Behavior

Traceback (most recent call last):
  File "quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/Users/Michelle/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/Users/Michelle/InstaPy/instapy/instapy.py", line 12, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named 'pyvirtualdisplay'

**Comment by michelleN27** [comment]
I uninstalled and reinstalled the files and all is good now! Works perfectly

**Comment by therealyamashita** [comment]
Tried running it on the cloud server and I encountered this also.

**Comment by cauvery-guda-eb** [comment]
I am having same issue on my mac and on linux server.  I did  pip install pyvirtualdisplay.
Exhausted all other options and nothing fixed. Need help

**Comment by exhelios** [comment]
same as cauveryguda
