### ISSUE TITLE
Like Fresh HashTags

### ISSUE THREAD

**Issue by Mehran** [InstaPy/InstaPy#1708]
i add some hash tag like #natgeo and amount=100 , my question is how can i tell it like 10 Fresh ( New Post) images ? after 10 like  Finish , Search again and Like another 10 Fresh

**Comment by CharlesCCC** [comment]
go to `logs` folder and open `general.txt` to check the log.

**Comment by Mehran** [comment]
it work well i just wants know i can do like just 10 new Hashtags ?
