### ISSUE TITLE
Feature Request: Only unfollow people followed by InstaPy who are not following me

### ISSUE THREAD

**Issue by fbomb** [InstaPy/InstaPy#1714]
## Current Behavior
Currently, the unfollow functionallity seems to support 2 choices:
 (a) Unfollow people not following me, with onlyNotFollowMe=True. In my experience, this is not so useful because it can unfollow people followed by me personally (not followed by InstaPy), and also it seems to unfollow people that I most recently followed.
(b) Unfollow people followed by InstaPy, FIFO style. This is great, except it also unfollows people who are following me.

## Feature Request
I would suggest that the method unfollow_users suppors both arguments, like
session.unfollow_users(onlyInstapyFollowed=True, onlyInstapyMethod='FIFO', onlyNotFollowMe=True)
Currently, this is not supported. This would be an awesome feature to have.

Thanks for the great project, and I hope this makes sense.

**Comment by CharlesCCC** [comment]
```
# You can only unfollow user that won't follow you back by adding
# onlyNotFollowMe = True it still only support on profile following
# you should disable onlyInstapyFollowed when use this
session.unfollow_users(amount=10, onlyNotFollowMe=True, sleep_delay=60)
```
Is this what you need ?

**Comment by fbomb** [comment]
@CharlesCCC yep, indeed. That would be very nice.

**Comment by CharlesCCC** [comment]
@fbomb that feature already exists. I copy and paste that from the wiki page. Please configure that accordingly.

**Comment by fbomb** [comment]
@CharlesCCC sorry, I misread your comment. I mean I would like support for both onlyNotFollowMe=True AND onlyInstapyFollowed=True. Right now, it says that these two are mutually exclusive. =)
