### ISSUE TITLE
comment and like latest specific users post

### ISSUE THREAD

**Issue by emyabdel** [InstaPy/InstaPy#1715]
HI I'm newbie and I searched but didn't find an answer.

I want to add specific users for example (user1, user2) and make one comment (great) and one like to their latest post.

what should I put? thanks

**Comment by david-vendel** [comment]
It is in the readme file:

Interact with specific users
# Interact with specific users
# set_do_like, set_do_comment, set_do_follow are applicable

session.set_do_follow(enabled=False, percentage=50)
session.set_comments(["Cool", "Super!"])
session.set_do_comment(enabled=True, percentage=80)
session.set_do_like(True, percentage=70)
session.interact_by_users(['user1', 'user2', 'user3'], amount=5, randomize=True, media='Photo')

**Comment by emyabdel** [comment]
yes thank you but I think that it should be modified to comment and like latest specific users post
