### ISSUE TITLE
@uluQulu fix on "get_links_for_tag" function not implemented yet?

### ISSUE THREAD

**Issue by therealyamashita** [InstaPy/InstaPy#1717]
## Expected Behavior
Problem addressed here: #1661
I'm using the latest commit and still the function "get_links_for_tag" is not working as expected.
I set the amount to 200 " session.like_by_tags(['coffee'], amount=200)"
## Current Behavior
Only 27 post loaded.
## Possible Solution (optional)

The link below is the fix:
https://github.com/timgrossmann/InstaPy/issues/1365#issuecomment-366526517

**Comment by denisemenov** [comment]
I have the same issue.
