### ISSUE TITLE
set_comments is not commenting with the correct comments

### ISSUE THREAD

**Issue by deronsizemore** [InstaPy/InstaPy#1721]
## Expected Behavior

I expect that the comments left would be from the list of comments above.

## Current Behavior

The current behavior is that it's leaving comments not in the list of comments in `set_comments`. As you can see from the screenshot, the comment left was "Nice!" which doesn't appear in the list of comments in the `set_comments` list.

![image](https://user-images.githubusercontent.com/68437/37837350-600f91c4-2e8b-11e8-94e1-4e7d4389a04e.png)

## InstaPy configuration

    #settings
    session.set_do_follow(True, percentage=80, times=1)
    session.set_lower_follower_count(limit=50)
    session.set_do_comment(enabled=True, percentage=15)
    session.set_user_interact(amount=3, randomize=True, percentage=100)

    # actions
    session.like_by_tags(like_tags, amount=100, interact=True)
    session.set_comments([u'Nice shot! :heart:', u'Really nice! :thumbsup:', u'Loving your work! :smile:', u'This photo is :fire:', u'Great work! :heart:', u'Love it! :heart: :thumbsup:'])

**Comment by DavidMolinari** [comment]
You should put your settings before your actions



```
#settings
session.set_do_follow(True, percentage=80, times=1)
session.set_lower_follower_count(limit=50)
session.set_comments([u'Nice shot! :heart:', u'Really nice! :thumbsup:', u'Loving your work! :smile:', u'This photo is :fire:', u'Great work! :heart:', u'Love it! :heart: :thumbsup:'])
session.set_do_comment(enabled=True, percentage=15)
session.set_user_interact(amount=3, randomize=True, percentage=100)


# actions
session.like_by_tags(like_tags, amount=100, interact=True)
```

Can you try ? I can't verify it now

**Comment by deronsizemore** [comment]
Ah, right you are. Totally missed that. It appears to be working now.

Thanks!
