### ISSUE TITLE
time between likes

### ISSUE THREAD

**Issue by emyabdel** [InstaPy/InstaPy#1723]
hi

for instapy, what's the default time between likes  and how to change it to the value that I want

**Comment by lucanello** [comment]
Welcome @emyabdel. You can change the delay with the `sleep_delay=60` argument. Just set any time in seconds you wish.

For example:
```
session.follow_user_followers(['friend1', 'friend2', 'friend3'], amount=10, randomize=False, sleep_delay=60)
```
as shown in the README.md file.

**Comment by emyabdel** [comment]
Thanks but i want the delay between likes and not between follow

**Comment by lucanello** [comment]
Just add the `sleep_delay` argument to the like function.

**Comment by emyabdel** [comment]
ok thank you

**Comment by jzos** [comment]
@lucanello sleep_delay won't work with like_by_tags, because it's not supported like_by_tags function in the instapy.py script. You'll have to add the following to the def like_by_tags function in the instapy.py file.

**Here:**

def like_by_tags(self,
                     tags=None,
                     amount=50,
                     media=None,
                     skip_top_posts=True,
                     use_smart_hashtags=False,
                     interact=False,
                     sleep_delay=60):

**And here before the links = get_links_for_tag**

            try:
                sleep(sleep_delay) 
                links = get_links_for_tag(self.browser,
                                          tag,
                                          amount,
                                          self.logger,
                                          media,
                                          skip_top_posts)
