### ISSUE TITLE
Please help,old version stop working so I install new instapy and new driver but i get error

### ISSUE THREAD

**Issue by webdesignkorenjak** [InstaPy/InstaPy#1725]
![screenshot_2](https://user-images.githubusercontent.com/37159896/37853981-3fc20308-2ee9-11e8-91a4-0884bac26c7c.png)

**Comment by Doom666** [comment]
long call but could you go to the new chromedriver extension, get into properties, and uncheck the highlighted checkbox, and then click on the change for all users button ?
![possible solution](https://user-images.githubusercontent.com/8590333/37858078-c6487666-2f00-11e8-99d6-4dabdd9df0f5.png)
Im not an expert by all means, but seems that some of the files that instapy is using , needs to be unchecked,

**Comment by Doom666** [comment]
if that dosnt help,. wait for someone else to come to the rescue as im in linux mostly

**Comment by omidedipidizi** [comment]
same here #1730  !!

**Comment by webdesignkorenjak** [comment]
Yes this whas help,thank you Doom666

**Comment by webdesignkorenjak** [comment]
Yes this whas help,thank you Doom666
