### ISSUE TITLE
please help with this error in instagram: The username you entered doesn't belong to an account. Please check your username and try again.

### ISSUE THREAD

**Issue by avaaaa** [InstaPy/InstaPy#1727]
hi, please help me with this problem! I'm freaking out.... all of a sudden i'm getting this error on the attempt to log in to both of my instagram accounts: "The username you entered doesn't belong to an account. Please check your username and try again."

I tried this way: "Tap Need more help? below Send Login Link", but doesn't help. 
I even try to log in with my email address. Is there any way to contact them for help?!

**Comment by sionking** [comment]
1. look for your username, is it deleted ?
2. if not, try reset password with you mail/phone
3. it is a known instagram bug - don't worry.

**Comment by avaaaa** [comment]
thanks for your response.
1- I did and it appears and also my friends can see my account.
2- I changed and received an email for it's confirmation, but still can't log in.

**Comment by avaaaa** [comment]
now everytime I'm trying to login it says: "We Detected An Unusual Login Attempt, To secure your account, we'll send you a security code to verify your identity." and I went through this process a few times but doesn't work! 
what should I do? is there anyway that i ask my friends to delete my account (I'm afraid someone else is 
using my account) ? or is there any way to ask help from Instagram?

**Comment by lauwood321** [comment]
the same thing just started happening to me too! You could try to ask for help from instagram but the chances they reply + take action on your request it quite small.

**Comment by avaaaa** [comment]
so what should we do?

**Comment by lauwood321** [comment]
I just read online someone had the same problem 2 years ago. they just tried logging in using 3g instead of wifi and that worked for them...idk if that will work now though

**Comment by avaaaa** [comment]
I tried that, but it doesn't work for me.

**Comment by sionking** [comment]
try changing password from mobile

**Comment by avaaaa** [comment]
it doesn't show the first message again but  everytime I'm trying to login it says: "We Detected An Unusual Login Attempt, To secure your account, we'll send you a security code to verify your identity." and I went through this process a few times but doesn't work!

**Comment by davidmurdoch** [comment]
Same here. Looks like instagram is soft-banning IP addresses. I can only log in to accounts via facebook login on this particular network now. ALL login attempts for any account via username/password return the error message: "The username you entered doesn't belong to an account. Please check your username and try again."

They may be doing some more advanced network/computer fingerprinting as well, as I changed my public IP address, cleared all cookies, and tried a different browser I hadn't used for Instagram before and still couldn't log in with a username/password to any account (but I could via another computer on another network).

**Comment by avaaaa** [comment]
hey thanks, I just login with another IP address! finally it works!!! hope it'll work for the others.

**Comment by xnamash** [comment]
Hey can you guys help me as well?

I logged out of my account, tried logging back in and it said on my app (i use an android emulator) "sorry your request is not available at the moment". Then i tried my browser and it said "the username does not exist for this account". Yet my account is actually online, i had friends check for me.

I tried it on 2 other accounts i have and same thing happened, they are band/music accounts so theres nothing offensive on them. the accounts are still online like i said but i simply can not log in.

I tried resetting my password, nothing. When i do it prompts me to a site that says "this link is not valid".
When i try to log in through an email by instagrams assistance, same thing.

How did you reset or change your IP avaaa? I would really like some help as the accounts are essential for promoting my musical projects.
Thank you.

**Comment by avaaaa** [comment]
I think there are some application for that but you can use the OvpnSpider. I hope it works for you.

**Comment by KwesiMemory** [comment]
Hi, This issue is frustrating me and on the edge of losing a client. I need HELP.
I am not able to get into my clients instagram account for about 3days now. The last time the account was active was December last year. I have tried almost everything to recover the password but not successful. On web, i am told "Sorry we can't send you a link to reset password, contact help on instagram" . Nothing leads me anywhere for solution. The account is linked to its facebook page. I am able to reply messages and comments via facebook but not able to get to the account.  I NEED URGENT HELP.

**Comment by kofimyke** [comment]
i have same problem here...tried different ip address and its still not working ....whenever i try to login ....it says this username name doesnt belong to any account.. trying password recovery also says users not found

**Comment by SaiduHephzibah** [comment]
i too have the same problem but even my friends cannot see my instagram account

**Comment by SaiduHephzibah** [comment]
please help me

**Comment by bhumidevninja** [comment]
> i have same problem here...tried different ip address and its still not working ....whenever i try to login ....it says this username name doesnt belong to any account.. trying password recovery also says users not found

I'm also having the same issue.

**Comment by I-am-Josh** [comment]
same for me :( constant f$%ing instagram login problems

**Comment by AshuOPragmatikosThrylos** [comment]
same problem

**Comment by VapiSoft** [comment]
same problem

**Comment by alimoezzi** [comment]
I'm getting this after disabling my account what should I do ?!
"We have encountered an error while resetting your password. Please try again."
