### ISSUE TITLE
Anyone had issues with Suspicious Activity Detected?

### ISSUE THREAD

**Issue by Luisetty** [InstaPy/InstaPy#1729]
Today I used the last version of the GIT PY with the fix of like_util.py from @uluQulu . So i had working without any issue and more than 27 tags. But I notice that started to comment faster I didn't change anything before. 

My comment percentage is: 30% was enough for me.

After an hour probably I received a email from instagram that my account had a suspicious activity and of course the logs and chrome showed that i was logoff.

My guess is that my instapy started to comment more than usual and giving probably more likes? what would be a safe procedure now?

ninja edit: yep, it was like_util.py haha, it was too late for me :)

**Comment by uluQulu** [comment]
`insta_like_py`? I have not shared anything in that name. If you have applied the fix correctly you should know that it has nothing to do with the `comment`**er** engine (_or the `like`**r**_)
What that fix changed is the way of grabbing the links from a `tag` page and then returning it to the caller function.
If you have grabbed some out-dated `like_util.py` from #1365, try just to apply the fix manually (simple 3 steps) on up-to-date file....

But to decrease overall latency, you can always increase sleep time with `set_sleep_reduce(percentage=170)` with percentages over 100 right from quickstart script...

**Comment by Luisetty** [comment]
thank you. I notice from march 23th and today (24th) i couldn't login from phone, tablet or pc. I saw some trends on twitter and social networks that instagram is having issues with logins and the rumor of changing again their feeds.

I just don't want to get banned :(
