### ISSUE TITLE
Use OAuth instead of asking username and password

### ISSUE THREAD

**Issue by rohitsinha54** [InstaPy/InstaPy#173]
I am not sure if there are any challenges which I am not seeing but will it not be possible to use instagram OAuth to fetch the access token and then use that to make request to instagram and consume the pages as InstaPy does currently with BeautifulSoup or something ? 

This will remove the need of an user giving their username and password away.

**Comment by pekapa** [comment]
Doesn't it make more prune for an instaban? Like the mentioned in #170 ?

We would need to actually create an instagram app to validade the OAuth with instagram, centralising all the requests... and probably in need to stay within API limits.

On the other hand, we would be able to change everything to the api (that is well documented) and avoid having the script break whenever instagram changes it's website.

**Comment by eduardocalazansjr** [comment]
Will lead to bans AND you can't Interact through pages with oAuth

**Comment by rohitsinha54** [comment]
@pekapa : Yes that makes sense. I didn't thought about the ban thing.

@vlntdds : I am new to Python so I might be wrong but in general all OAuth services also allow getting access token either independently or i exchange of oauth which can be sent with the httprequest to fetch pages. While glancing through the requests python module I saw it support passing access token.

**Comment by eduardocalazansjr** [comment]
It's not python related.
You don't Interact with Pages, you Interact with the API, that doesn't fit instapy needs.
You must read the Instagram documentation for that and see the limits.
Won't happen.

**Comment by rohitsinha54** [comment]
@vlntdds Agree. My bad earlier I meant fetch pages as in the response of the call not exactly the "html page". The code needed to be changed to handle api responses.

**Comment by rohitsinha54** [comment]
Closing this issue as switching to OAuth is not even a possibility due to chances of ban.
