### ISSUE TITLE
Comment only by tags

### ISSUE THREAD

**Issue by sapaholics** [InstaPy/InstaPy#1731]
Is there a way I could only comment a post based on certain tags. 
For example, search a post with the tag "car" and comment 'nice car', then move on to the next post with the tag "car" and so on?

**Comment by Tjorriemorrie** [comment]
Just set it before liking by tag, e.g.
set_comments('nice car')
like_by_tag(['car'])
set_comments('nice hotdog')
like_by_tag(['hotdog'])
