### ISSUE TITLE
RPi3 Firefox is not commenting

### ISSUE THREAD

**Issue by deniskrafczyk** [InstaPy/InstaPy#1736]
Hi,
referencing to issue 494 im not able to autocomment on my rpi3 with headless firefox setup.
 I am getting the following error:

`INFO [2018-03-24 15:28:44] [xxx] Commented: 0 --> Warning: Comment Button Not Found: May cause issues with browser windows of smaller widths WARNING [2018-03-24 15:30:00] [xxx] --> Warning: Comment Action Likely Failed: Comment Element not found INFO [2018-03-24 15:30:00] [xxx] --> Commented: 👌`

It says that it commented on this, but surely it didnt, i checked all the logs and feeds itself.
## InstaPy configuration
```
InstaPy(username='xxx', password='xxx', use_firefox=True, page_delay=25)\
.set_do_comment(True, percentage=13)\
.set_comments([':+1:', ':heart_eyes:', 'Nice!',':ok_hand:'])\
```

Please let me know, if i can provide further information or something like that.

I love Instapy, thanks for this project.

Cheers
Denis

**Comment by Ninnix** [comment]
same problem here on firefoxESR
