### ISSUE TITLE
Raspberry Pi - Chromedriver Version Issue

### ISSUE THREAD

**Issue by jcpsimmons** [InstaPy/InstaPy#1738]
## Expected Behavior

Installed according to the Raspberry Pi instructions in the tutorial. Ran quickstart.py with requisite login info.

## Current Behavior

Received following error:

`Traceback (most recent call last):
  File "quickstart.py", line 18, in <module>
    multi_logs=True)
  File "/home/pi/projects/InstaPy/instapy/instapy.py", line 152, in __init__
    self.set_selenium_local_session()
  File "/home/pi/projects/InstaPy/instapy/instapy.py", line 267, in set_selenium_local_session
    float(matches.groups()[0]), Settings.chromedriver_min_version))
instapy.instapy.InstaPyError: chromedriver 2.33 is not supported, expects 2.36+
`

## Possible Solution (optional)

I went into /InstaPy/instapy/settings.py and changed the final line from

`chromedriver_min_version = 2.36`

to

`chromedriver_min_version = 2.33`

and everything seems to run fine now. Why was minimum version set at 2.36 in the first place?

**Comment by rodriguesprobr** [comment]
Same problem here

**Comment by FreakyBoy** [comment]
@jcpsimmons YES! chromedriver min version of 2.36 is really bullshit... all Raspberry user need chromedriver 2.33 because of the 32bit architecture

**Comment by Tjorriemorrie** [comment]
@FreakyBoy please note that previous versions had a bug, and there were a lot of issues raised where all they needed to do was update their chromedriver. Who still uses 32bit anyway :p

It's a Setting as @jcpsimmons pointed out, these are meant to configured for your setup. Changing it lower is what it is there for. The default is still 2.36 to handle most users going forward.

**Comment by rodriguesprobr** [comment]
@Tjorriemorrie I understand that we need to move forward, but how RPi users will deal with this issue, considering that RPi only had chromedriver in x86 arch?

**Comment by Tjorriemorrie** [comment]
Yes it's a lesser of two evils unfortunately. But changing settings/configuration is common practice, so just changing it what you did is standard, especially for deployment like that. I would like make it 2.33, but then this repo gets flooded with issues around the bug and the like.

I think I'll have to put a step in the readme to make the change for the RPi setup.

**Comment by rodriguesprobr** [comment]
@Tjorriemorrie it's a good idea, indeed

**Comment by joanroig** [comment]
Hi all, anybody knows if there will be a new chromedriver version compatible with Raspberry Pi?

**Comment by sunil-sandhu** [comment]
Changing to 2.33 fixed things for me :)
