### ISSUE TITLE
Deploying on digital ocean with docker

### ISSUE THREAD

**Issue by nonsou** [InstaPy/InstaPy#174]
Hello, 

However I am not a techie but I know with a bit of guidance I can get things to work, I have created a docker server but I can not seem to install your script with the instruction on you github
page. 
docker build -t instapy 

I have also tried 
docker build https://github.com/timgrossmann/InstaPy

`root@docker-512mb-nyc2-01:~# docker build https://github.com/timgrossmann/InstaPy
Downloading build context from remote url: https://github.com/timgrossmann/InstaDownloading build context from remote url: https://github.com/timgrossmann/InstaPy  104.8kB
Sending build context to Docker daemon  106.5kB
Error response from daemon: Dockerfile parse error line 7: Unknown instruction: <!DOCTYPE
`

Please help...

I have also tried docker build https://github.com/timgrossmann/InstaPy/blob/master/Dockerfile

**Comment by fwartner** [comment]
The correct usage is ```docker build -t instapy .```

**Comment by fwartner** [comment]
https://github.com/timgrossmann/InstaPy#build-the-image

**Comment by calebfornari** [comment]
It's worth noting that the Digital Ocean 512 MB and 1 GB Droplets don't seem to have enough memory to run this. So you'll need the 2 GB droplet at a minimum.
