### ISSUE TITLE
Multiple accounts terminal name incorrect

### ISSUE THREAD

**Issue by dimmable** [InstaPy/InstaPy#1746]
## Expected Behavior
When the script is running and updates the time at each action, it should display the name of the account it made the action on as well.
## Current Behavior
The account name is not changing when it switches to the next account after session.end() yet the actions it is making are on the second account. It simply is just not changing the name of the account displayed.

**Comment by Tjorriemorrie** [comment]
Are you using `multi_logs` as True?

**Comment by dimmable** [comment]
Yes, it is. I don't understand why it is displaying incorrectly in the terminal.

**Comment by dimmable** [comment]
And after looking at it further, it seems that general.log is generated in the folder with the first account listed for the multiple account run. This is also the only username displayed throughout the terminal and general.log responses, despite the activities actually alternating between accounts. Any and all help is appreciated.
