### ISSUE TITLE
How can I run InstaPy with my old chrome profile (wrong login data)

### ISSUE THREAD

**Issue by furk4no** [InstaPy/InstaPy#1747]
I have deleted my InstaPy folder completely and cloned the new version completely..
I also downloaded and installed the new version of chromedriver (2.37) I was using the 2.36 one before. 
Somehow I am getting a critical error while InstaPy is trying to create cookies which tells me that my login data is wrong.. 

Is there any way to let it work again?

**Comment by stevenharris-dev** [comment]
You will have to use the 2.36 version of the chromedriver. The 2.37 version didn't work for me either but works great when you revert to the older one.

Also, when it is trying to create cookies, you have to [bypass suspicious login attempts](https://github.com/timgrossmann/InstaPy#bypass-suspicious-login-attempt) so the cookie can be created and the regular login will work.

**Comment by furk4no** [comment]
Thanks! I'll try it..

**Comment by furk4no** [comment]
It seems really strange.. cookie cannot be created and the bypass method doesn't work?

` Session started - 2018-03-25 20:52:28
Cookie file not found, creating cookie...
Unable to locate email or phone button, maybe bypass_suspicious_login=True isn't needed anymore.
`

**Comment by stevenharris-dev** [comment]
Don't know what to say here. I would try turning it off, running it again and see what happens. 🤔

**Comment by furk4no** [comment]
I destroyed my droplet now I'm doing everything by scratch.. I'll tell you more.

Might be a problem caused by a soft ban I thought..

**Comment by furk4no** [comment]
I still have the same problem.. even with a brand new Ip address...

`~/instapy#  cd ~/instapy/ && python3.5 ~/instapy/quickstart.py
INFO [2018-03-25 21:52:45] [###]  Session started - 2018-03-25 21:52:45
Cookie file not found, creating cookie...
CRITICAL [2018-03-25 21:52:57] [[###]]  Wrong login data!
INFO [2018-03-25 21:52:59] [[###]]  Session ended - 2018-03-25 21:52:59
INFO [2018-03-25 21:52:59] [[###]]  --------------------
`

**Comment by furk4no** [comment]
I installed VNC for my DigitalOcean droplet and saw that the problem is at the instagram side.. It tells that my username couldn't be assigned to an existing account.. I don't know how to solve this! I am able to login over my mobile!

**Comment by stevenharris-dev** [comment]
Issue #1734 seems to suggest that it might be an ipban. It may be even a wide IP ban for DO Droplets. Try setting it up with another VPS provider perhaps? Or use a proxy.

**Comment by furk4no** [comment]
Wow.. the problem got fixed after 7 or 8 hours.. I didn't do anything!

**Comment by riccardorighettiphoto** [comment]
still have the same issue. It is since last friday night my InstaPy has not been running on server. Really annoying.

**Comment by furk4no** [comment]
I‘d say make a snapshot/backup and destroy your droplet/vps if you have the opportunity.. getting a new ip address would be a solution.. (same country ip address as normal logins) but don‘t forget that you could have need the suspicious login bypass and verify over the console that it‘s you. You could try this.
