### ISSUE TITLE
session.like_by_feed doesnt seem to be working?

### ISSUE THREAD

**Issue by Marvol1** [InstaPy/InstaPy#1748]
Using chrome, all the like by tags are working perfect, the like by feed wont though. Ive tried running it on its own and just ends the session after logging in.

session = InstaPy(username=insta_username, password=insta_password, headless_browser=False)
        session.login()
        
        # settings
        session.set_do_follow(enabled=True, percentage=10, times=(random.randint(10,15)))
        session.set_dont_unfollow_active_users(enabled=True, posts=5)   
        session.unfollow_users(amount=(random.randint(15,20)), onlyInstapyFollowed = True,
        onlyInstapyMethod='FIFO', onlyNotFollowMe=True, sleep_delay=600, unfollow_after=(7*24*60*60))
          
        # actions
        session.like_by_feed(amount=50, randomize=True)
        session.end()

    except Exception as e:
        print(e)

**Comment by patrickdundas** [comment]
Could you show the output of your console?

**Comment by denisemenov** [comment]
```
INFO [2018-03-24 20:39:39] [username] Session started - 2018-03-24 20:39:39
INFO [2018-03-24 20:40:12] [username] Logged in successfully!
INFO [2018-03-24 20:40:15] [username] Session ended - 2018-03-24 20:40:15
INFO [2018-03-24 20:40:15] [username] --------------------
```
The same issue.

**Comment by Marvol1** [comment]
INFO [2018-03-26 07:32:55] [username]  Session started - 2018-03-26 07:32:55
WARNING [2018-03-26 07:32:55] [username]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO [2018-03-26 07:33:26] [username]  Logged in successfully!
INFO [2018-03-26 07:33:31] [username]  Session ended - 2018-03-26 07:33:31
INFO [2018-03-26 07:33:31] [username]  --------------------

yea that's exactly what I'm getting as well, ran it on its own with no settings

**Comment by deklyn12** [comment]
Have also experienced similar behavior, all other functions I have been using the bot for work just as they should - however with this one it seems like its "ignored" by the bot.

**Comment by kristofenyi** [comment]
Hi !

I have the same issue - everyhting else is working only session.like_by_feed is not

**Comment by douwevandermeij** [comment]
PR #1782 should fix this problem.

**Comment by Marvol1** [comment]
PR #1782 worked perfectly, thank you!
