### ISSUE TITLE
InstaPyError('Clarifai is not supported on Windows')

### ISSUE THREAD

**Issue by balakedev** [InstaPy/InstaPy#1753]
`Traceback (most recent call last):
  File "C:\#####\InstaPy\ST04.py", line 27, in <module>
    session.set_use_clarifai(enabled=True, api_key='######')
  File "C:\#####\InstaPy\instapy\instapy.py", line 444, in set_use_clarifai
    raise InstaPyError('Clarifai is not supported on Windows')
instapy.instapy.InstaPyError: Clarifai is not supported on Windows

`

never encountered this before. This is a result of updating Chromedriver

**Comment by Tjorriemorrie** [comment]
I think some people said there is some problems on Windows. I can change this into a warning instead if you have had it working on windows?

**Comment by balakedev** [comment]
@tjorriemorrie been using clarifying this whole time! Super weird! I commented out the line in the instapy.py file but then what happened was the original issue before the update occurred. It doesn’t seem to sick the top posts and somehow, the error code still states the chrome driver is still 2.34. I’ve downloaded and extracted the new version in the assets folder... not sure what else I can do!

**Comment by balakedev** [comment]
@converge any ideas mate?

**Comment by ghost** [comment]
also having this problem. bump.

**Comment by matousek-martin** [comment]
anything?

**Comment by Tidle999** [comment]
also having this problem...
