### ISSUE TITLE
Blacklist feature first run

### ISSUE THREAD

**Issue by ohio36** [InstaPy/InstaPy#1754]
## Expected Behavior
When I comment on a user's photo, I don't ever want to comment on his photos again (but likes are fine!). When using more eleborate comments, it seems very strange to give a similar comment on multiple photos. 

## Current Behavior
I used the blacklist function like this:

    session.set_blacklist(enabled=True, campaign='test-campaign')
    session.set_do_comment(True, percentage=90)
    session.like_by_tags(['test'], amount=100, media='Photo')

However, within the first run of this campaign, I still comment on multiple pictures of the same user. I do see the user in the blacklist though. Is the blacklist only working when first scraping photos?

## Possible Solution (optional)
Before the actual comment is done, check the blacklist.

**Comment by sionking** [comment]
The issue is that the blacklist file is updated only at the end of this run.
Next run will contain this user...

 As far as I remember.

**Comment by patrickdundas** [comment]
With slight modification to your own code, you could save the usernames that you've commented on into a text file or database and check that database before the next comment. This would require modification on some of the _util files, so you will need to be comfortable modifying that on your own.

**Comment by ohio36** [comment]
@sionking: I think the session.set_blacklist command triggers the script to add all the users from a certain campaign to the dont_include variable, so before you start your session. 

I tried to modify the code and I managed to get it to do a real-time check if the user is added to the blacklist before placing any comments. I changed the basic comment_image function, so should work regardless of what function you used to add comments. Same goes for the change in the like function. 

I have no previous experience with Python, and only a little bit with other languages like PHP, so don't expect anything fancy. Maybe somebody can make it work in a neat manner and add it to a new release of Instapy? Here is what I changed: 

Added a function to util.py: 

```
"""Real-time check if user is on the blacklist"""    
def check_user_on_blacklist(username, logger, logfolder):

    user_on_blacklist = False
    
    try:
        with open('{}blacklist.csv'.format(logfolder), 'r') as blacklist:
            reader = csv.DictReader(blacklist)
            for row in reader:
                if row['username'] == username:
                    user_on_blacklist = True
    except Exception as err:
        logger.info('Not able to open the blacklist before posting comment.')
        logger.error(err)
        
    return user_on_blacklist
```

Changed function comment_image in comment_util.py to: 

```
def comment_image(browser, username, comments, blacklist, logger, logfolder):
    """Checks if it should comment on the image"""
    rand_comment = (choice(comments).format(username))
    rand_comment = emoji.demojize(rand_comment)
    rand_comment = emoji.emojize(rand_comment, use_aliases=True)
    
    """User was not on blacklist when starting the session. This variable is used to 
    do an extra check to see if the user has not been addes during this session to 
    prevent comments to multiple posts of the same user within a single session. """
    user_on_blacklist = check_user_on_blacklist(username, logger, logfolder)
    
    """Only comment if user is not on the blacklist."""
    if user_on_blacklist:
        logger.info("--> Not commented: Already commented to {} in this session.".format(username))
    else:
        open_comment_section(browser)
        comment_input = get_comment_input(browser)

        if len(comment_input) > 0:
            comment_input[0].clear()
            comment_input = get_comment_input(browser)

            browser.execute_script(
                "arguments[0].value = '" + rand_comment + " ';", comment_input[0])
            # An extra space is added here and then deleted.
            # This forces the input box to update the reactJS core
            comment_input[0].send_keys("\b")
            comment_input = get_comment_input(browser)
            comment_input[0].submit()
            update_activity('comments')
            if blacklist['enabled'] is True:
                action = 'commented'
                add_user_to_blacklist(
                    browser, username, blacklist['campaign'], action, logger, logfolder
                )
        else:
            logger.warning('--> Warning: Comment Action Likely Failed:'
                           ' Comment Element not found')

        logger.info("--> Commented: {}".format(rand_comment.encode('utf-8')))
        
    sleep(2)

    return 1

```
Commented out the following code in function like_image in like_util.py: 

```
""" Do not call add_user_to_blacklist when liking posts. Multiple likes is fine, just not multiple comments. 
                add_user_to_blacklist(
                    browser, username, blacklist['campaign'], action, logger, logfolder
                )"""
```

**Comment by Cerebrock** [comment]
I just added "if action == 'liked': return None" to add_user_to_blacklist in .utils, I believe it should do the job, right?
