### ISSUE TITLE
cannot import name 'formatNumber'

### ISSUE THREAD

**Issue by furk4no** [InstaPy/InstaPy#1755]
I added the code of someone to my like_util.py to fix the 27 like limit and it throws this error:

```
Traceback (most recent call last):
  File "/root/instapy/quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File "/root/instapy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/root/instapy/instapy/instapy.py", line 24, in <module>
    from .like_util import check_link
  File "/root/instapy/instapy/like_util.py", line 14, in <module>
    from .util import formatNumber
ImportError: cannot import name 'formatNumber'

```

**Comment by Tjorriemorrie** [comment]
It was refactored to `format_number`. Check the `utils.py` file. You can search and replace all instances then of it.

**Comment by furk4no** [comment]
Thank you..

**Comment by uluQulu** [comment]
@furk4no 
`someone` 🤣 already updated the _code_ to support [that change](https://github.com/timgrossmann/InstaPy/issues/1365#issuecomment-372049879) **2 weeks ago**, _make sure_ to use the updated code before reports an error ☹
