### ISSUE TITLE
Can't login with proxy

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1756]
## Expected Behavior
Run bot with proxy.
## Current Behavior
File "myunfollow.py", line 13, in <module>
    session = InstaPy(username=insta_username, password=insta_password, headless_browser=True, bypass_suspicious_attempt=True, proxy_address='184.174.44.46', proxy_port=21233)
  File "/root/InstaPy/instapy/instapy.py", line 152, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 238, in set_selenium_local_session
    proxy = ":".join([self.proxy_address, self.proxy_port])
TypeError: sequence item 1: expected str instance, int found

## Possible Solution (optional)
Modify the login command.

**Comment by patrickdundas** [comment]
Your `proxy_port=21233` needs to be changed to `proxy_port='21233'`, as it is taken as a string rather than an integer, as the error tells you.

**Comment by ghost** [comment]
@patrickdundas 
After change.

  File "/root/InstaPy/instapy/instapy.py", line 152, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 236, in set_selenium_local_session
    if self.proxy_address and self.proxy_port > 0:
TypeError: unorderable types: str() > int()

**Comment by nicobts** [comment]
I'm having the same issues trying to use a proxy. Anyone Knows a good solution for this issue? Proxies are essential if you want to avoid to be banned if you run more accounts on the same machine I think..

**Comment by ceribbo** [comment]
fixed it by setting     
`if self.proxy_address and int(self.proxy_port) > 0:` 
on line 210 and 241 of instapy.py file

**Comment by nickcaoz** [comment]
@ceribbo changing it solved the starting error for me, but always getting:
WARNING [2018-05-18 20:16:55] [accountname]  Can't interact with private account

now, some tips from you guys?
