### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'past'

### ISSUE THREAD

**Issue by surfjoh** [InstaPy/InstaPy#1758]
Error: ModuleNotFoundError: No module named 'past'

When running the Gui after inserting my login data and selecting like by tag the following error message pops up: Error: ModuleNotFoundError: No module named 'past'
Same problem if I execute the quickstart.py without the Gui.
Any ideas how to fix it?

**Comment by animetrk** [comment]
I solved the same error by searching on internet. They say
`pip install future`
will fix it but when I tried it I get an error. So I tried other things,
`pip install --upgrade future`
and it upgraded it. And the "No module named 'Past' error dissappeared.

**Comment by surfjoh** [comment]
Thanks for your reply @animetrk ! However now it tells me that my chromedriver apparently is version 2.34 but that I need 2.36+...
I already tried to update it with pip install --upgrade chromedriver and manually via downloading and extracting the file to the \assets folder but it didn't solve the problem.

**Comment by Tjorriemorrie** [comment]
Give me the link to the download - then I can look at that specific version on my side

**Comment by surfjoh** [comment]
https://chromedriver.storage.googleapis.com/index.html?path=2.36/
https://chromedriver.storage.googleapis.com/index.html?path=2.37/

I tried both versions. Downloaded, unpacked to the \assets directory and also tried with adding the path to the windows environment variables.
The pip install --upgrade chromedriver also didn't work.

Thanks for checking @Tjorriemorrie !

**Comment by Tjorriemorrie** [comment]
I just checked both those versions. It works correctly:

2.36
![2018-03-27 10_20_57-instapy c__users_jaco jansen_code_instapy - _tests_test_instapy py instapy](https://user-images.githubusercontent.com/1099093/37938206-cf270f72-31a8-11e8-9af1-3e5add2e565a.png)

2.37
![2018-03-27 10_22_05-instapy c__users_jaco jansen_code_instapy - _instapy_instapy py instapy -](https://user-images.githubusercontent.com/1099093/37938280-d469b156-31a8-11e8-83e0-c421c0206859.png)

It means you are not extracting it correctly to the assets folder, or it is using another chromedriver.

If you do not come right, you can just change the setting lower in `settings.py`: `min_chrome_version` to 2.34. But you should try to find the problem with your environment.

**Comment by surfjoh** [comment]
Okay thank you very much!
Im still new to Python, so it's not gonna be easy to figure out I guess hahaha.
Maybe it could be because I didn't istall it via virstualenv?
I just ran the windows.ps1 again and this is what shows up:
I followed all the prior installation steps tho so no Idea why I'm getting these errors...

--------------------

InstaPy Windows Setup
=============================================================================================
Installing Selenium
Requirement already satisfied: selenium in c:\users\surfj\appdata\local\programs\python\python36\lib\site-packages
Requirement already satisfied: pyvirtualdisplay in c:\users\surfj\appdata\local\programs\python\python36\lib\site-packages
Requirement already satisfied: EasyProcess in c:\users\surfj\appdata\local\programs\python\python36\lib\site-packages (from pyvirtualdisplay)
C:\Users\surfj\AppData\Local\Programs\Python\Python36\python.exe: can't open file 'get-pip.py': [Errno 2] No such file or directory

Installing GUI Tool
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At C:\Users\surfj\Documents\GitHub\InstaPy\scripts\windows.ps1:10 char:1
+ $webclient.DownloadFile("https://github.com/Nemixalone/GUI-tool-for-I ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

mv : Cannot find path 'C:\Users\surfj\Documents\GitHub\InstaPy\scripts\InstaPy-GUI.exe' because it does not exist.
At C:\Users\surfj\Documents\GitHub\InstaPy\scripts\windows.ps1:11 char:1
+ mv "$pwd\InstaPy-GUI.exe" "$pwd\..\InstaPy-GUI.exe"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\surfj\...InstaPy-GUI.exe:String) [Move-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand


Downloading Chrome Driver...
Chrome Driver download completed.

Unzipping Chrome Driver...
mv : Cannot create a file when that file already exists.
At C:\Users\surfj\Documents\GitHub\InstaPy\scripts\windows.ps1:26 char:1
+ mv "$pwd\assets\chromedriver.exe" "$pwd\assets\chromedriver"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\surfj\...hromedriver.exe:FileInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveFileInfoItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand

Unzipping completed.

Removing unneeded files...
Removal completed.

running install
running bdist_egg
running egg_info
writing instagram_py.egg-info\PKG-INFO
writing dependency_links to instagram_py.egg-info\dependency_links.txt
writing requirements to instagram_py.egg-info\requires.txt
writing top-level names to instagram_py.egg-info\top_level.txt
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
reading manifest file 'instagram_py.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'instagram_py.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\clarifai_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\comment_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\feed_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\instapy.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\like_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\login_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\print_log_writer.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\settings.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\time_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\unfollow_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\__init__.py -> build\bdist.win-amd64\egg\instapy
byte-compiling build\bdist.win-amd64\egg\instapy\clarifai_util.py to clarifai_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\comment_util.py to comment_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\feed_util.py to feed_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\instapy.py to instapy.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\like_util.py to like_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\login_util.py to login_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\print_log_writer.py to print_log_writer.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\settings.py to settings.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\time_util.py to time_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\unfollow_util.py to unfollow_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\util.py to util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\__init__.py to __init__.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying instagram_py.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying instagram_py.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying instagram_py.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying instagram_py.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying instagram_py.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
instapy.__pycache__.settings.cpython-36: module references __file__
creating 'dist\instagram_py-0.0.1-py3.6.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing instagram_py-0.0.1-py3.6.egg
removing 'c:\users\surfj\appdata\local\programs\python\python36\lib\site-packages\instagram_py-0.0.1-py3.6.egg' (and everything under it)
creating c:\users\surfj\appdata\local\programs\python\python36\lib\site-packages\instagram_py-0.0.1-py3.6.egg
Extracting instagram_py-0.0.1-py3.6.egg to c:\users\surfj\appdata\local\programs\python\python36\lib\site-packages
instagram-py 0.0.1 is already the active version in easy-install.pth

Installed c:\users\surfj\appdata\local\programs\python\python36\lib\site-packages\instagram_py-0.0.1-py3.6.egg
Processing dependencies for instagram-py==0.0.1
Searching for Pillow==2.9.0
Reading https://pypi.python.org/simple/Pillow/
Downloading https://pypi.python.org/packages/62/7d/a6decd77e926197621ca13f63e4f37333a462e1be18a8b5928b692f7ae24/Pillow-2.9.0.tar.gz#md5=46f1729ece27981d54ec543ad5b37d14
Best match: Pillow 2.9.0
Processing Pillow-2.9.0.tar.gz
Writing C:\Users\surfj\AppData\Local\Temp\easy_install-qnuwrc4b\Pillow-2.9.0\setup.cfg
Running Pillow-2.9.0\setup.py -q bdist_egg --dist-dir C:\Users\surfj\AppData\Local\Temp\easy_install-qnuwrc4b\Pillow-2.9.0\egg-dist-tmp-9j3z8ydu
Single threaded build, not installing mp_compile: 4 processes
error: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
Setup is completed.
Press Enter to continue...:

**Comment by surfjoh** [comment]
I changed the required chrome version to 2.34 now in the settings.py file.
At least the Gui starts working now but shows up this error messages:
It also opens up chrome and goes to instagram but fails to log in.

--------------------

## **InstaPy Process**

Cookie file not found, creating cookie...

Error: INFO [2018-03-27 03:01:37] [johannesgirke] Session started - 2018-03-27 03:01:37
 WARNING [2018-03-27 03:01:37] [johannesgirke] Sorry, Record Activity is not working on Windows. We're working to fix this soon!
 Traceback (most recent call last):
 File "quickstart.py", line 5, in <module>
 session.login()
 File "C:\Users\surfj\Documents\GitHub\InstaPy\instapy\instapy.py", line 302, in login
 self.bypass_suspicious_attempt):
 File "C:\Users\surfj\Documents\GitHub\InstaPy\instapy\login_util.py", line 132, in login_user
 "//select[@class='_fsoey']/option[text()='English']").click()
 File "C:\Users\surfj\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
 self._execute(Command.CLICK_ELEMENT)
 File "C:\Users\surfj\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
 return self._parent.execute(command, params)
 File "C:\Users\surfj\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
 self.error_handler.check_response(response)
 File "C:\Users\surfj\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
 (Session info: chrome=65.0.3325.181)
 (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.16299 x86_64)
 
InstaPy_ ended Stop

**Comment by Tjorriemorrie** [comment]
`call function result missing 'value'` is what was fixed in the new chromedriver version.

**Comment by Huixxi** [comment]
> I solved the same error by searching on internet. They say
> `pip install future`
> will fix it but when I tried it I get an error. So I tried other things,
> `pip install --upgrade future`
> and it upgraded it. And the "No module named 'Past' error dissappeared.

It works to me! Thank you very much
