### ISSUE TITLE
Error -bash: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by iYahiaa** [InstaPy/InstaPy#1760]
## InstaPy configuration

Hi I tried to run in my Terminal:

session = InstaPy(username='test', password='test', nogui=True)

and got the following error.

-bash: syntax error near unexpected token `('

**Comment by jlopezfisica** [comment]
if you cpy pasted maybe change the symbols again

**Comment by Tjorriemorrie** [comment]
~Make sure all the apostrophes are `'` and not `~

**Comment by iYahiaa** [comment]
> Make sure all the apostrophes are ' and not `

Where ? in all files? or in session command 

> session = InstaPy(username='test', password='test', nogui=True)

**Comment by denisemenov** [comment]
You need to run "python3 quickstart.py" in terminal, don't write "sesssion ..." in terminal.
Line "session..." must be in quickstart.py.
