### ISSUE TITLE
Instagram does not allow me to log in on google chrome nor firefox

### ISSUE THREAD

**Issue by jlopezfisica** [InstaPy/InstaPy#1761]
## Expected Behavior
the bot works fine but apparently chrome and firefox does not recognize my account. I tried to login in android and work perfectly. Do you have the same? 

That is the output in chrome: The username you entered doesn't belong to an account. Please check your username and try again

**Comment by Tjorriemorrie** [comment]
Are you using the username and not the email address?

**Comment by furk4no** [comment]
I think it is an instagram problem. I had this yesterday and also today.. After trying to login a few times I waited some hours tried again and again and I was able to login then somehow.. I don‘t really know what solved this problem..

**Comment by sionking** [comment]
Log using facebook sovled it to me.
I had only 1 account with this issue, that can log in from different ip.
I temporery solved it by using chrome default profile where I loged in with facebook.

Hope it is really an IG issue not a bot blocker by ip.

**Comment by sionking** [comment]
Now we can login as we used to :) IG fixed
