### ISSUE TITLE
Best Script to Grow a Profile

### ISSUE THREAD

**Issue by alessiomtt** [InstaPy/InstaPy#1764]
Hi,

I know that the "perfect script" to grow a profile it is very subjective and depends on case by case;
according to you, what can be the best sequence of operations that can be carried out 24/24 and 7/7?

Could someone post an example kindly? In such a way that we can work on it.

Thanks a lot!

**Comment by sionking** [comment]
I do analytics.
I count the number of actions per tag/profile/location, check my new  followers and see where they came from and div it in the first.
so the more this ratio is high the more this tag/profile/location is better.

good tag is 1 new follower for 100 actions (follow/like/comment is 1 action).

* I can tell you from this that you can't know what is a good script from the beginning.
BTW, in this way I also know if a profile have many fake account (ratio is low)

**Comment by animetrk** [comment]
- Following the followers of some crowded pages like yours and interacting with them
- Liking the feed (not working right now)
- unfollowing the ones that didn't return after X day
- not unfollowing the ones that are active, the ones that liked your last posts (not working right now)

I'm getting around 50 active users each day just by following 400-500 people a day with my 10k+ page.

I hope they fix the "like feed" and "dont unfollow active users" problems soon.
