### ISSUE TITLE
sleep_delay problem

### ISSUE THREAD

**Issue by shine6666** [InstaPy/InstaPy#1765]
I have this problem the _delay sleep does not work well.
if I insert any value to the following function, for example sleep_delay = 120 or sleep_delay = 60 etc.
I have intervals of 13-16 seconds for each follower that I follow.
this is the example:
from instapy import InstaPy

session = InstaPy(username='xx', password='xxxx')

session.login()

session.follow_user_followers(['xxx'], amount=2, sleep_delay=60, randomize=True, interact=False)

session.end()

can someone help me?

**Comment by Tjorriemorrie** [comment]
Just a quick glance seems it only sleeps every 10th follow:
`followNum % 10 == 0`
Is that what you are experiencing?

**Comment by sionking** [comment]
yes

**Comment by MMeybodi** [comment]
i have the same issue as well, GUI follows users every ~15 seconds which is so risky
