### ISSUE TITLE
Extra keyword constraints

### ISSUE THREAD

**Issue by ohio36** [InstaPy/InstaPy#1766]
I like being restrictive in which posts I like. I therefore added some code so you can add must have keywords that must exist in the location and/or description of a post. For example: let's say Madonna recently performed in the O2 Arena. I want to like posts with hashtag #madonna, but only those that mention 'O2 Arena' or that were taken in the O2 Arena. 

Multiple keywords are possible, and you can define wether or not all (or just some) must be present. 

Maybe somebody could help improving my implementation (I don't have Python experience, so don't expect fancy code) and add it to a future release. I made the following changes: 

Changed the check_links method in like_util.py. Added to params, get the location information from Instagram, and added the actual search bit at the end.

```
def check_link(browser, link, dont_like, ignore_if_contains, ignore_users, username,
               like_by_followers_upper_limit, like_by_followers_lower_limit, logger, must_haves=None, must_haves_strict=False):
    """
    Check the given link if it is appropriate

    :param browser: The selenium webdriver instance
    :param link:
    :param dont_like: hashtags of inappropriate phrases
    :param ignore_if_contains:
    :param ignore_users:
    :param username:
    :param like_by_followers_upper_limit:
    :param like_by_followers_lower_limit:
    :param logger: the logger instance
    NEW: :param must_haves: keywords that must be in description or location 
    NEW: :param must_haves_strict: if strict than all keywords must be present. if not strict than one keyword is enough.
    :return: tuple of
        boolean: True if inappropriate,
        string: the username,
        boolean: True if it is video media,
        string: the message if inappropriate else 'None'
    """
    browser.get(link)
    # update server calls
    update_activity()
    sleep(2)

    """Check if the Post is Valid/Exists"""
    post_page = browser.execute_script(
        "return window._sharedData.entry_data.PostPage")
    if post_page is None:
        logger.warning('Unavailable Page: {}'.format(link.encode('utf-8')))
        return True, None, None, 'Unavailable Page'

    """Gets the description of the link and checks for the dont_like tags"""
    graphql = 'graphql' in post_page[0]
    if graphql:
        media = post_page[0]['graphql']['shortcode_media']
        is_video = media['is_video']
        user_name = media['owner']['username']
        image_text = media['edge_media_to_caption']['edges']
        image_text = image_text[0]['node']['text'] if image_text else None
        '''NEW: Get location from the post from Graphql data.'''
        location = media['location']
        location_name = location['name'] if location else None
        owner_comments = browser.execute_script('''
      latest_comments = window._sharedData.entry_data.PostPage[0].graphql.shortcode_media.edge_media_to_comment.edges;
      if (latest_comments === undefined) latest_comments = Array();
      owner_comments = latest_comments
        .filter(item => item.node.owner.username == '{}')
        .map(item => item.node.text)
        .reduce((item, total) => item + '\\n' + total, '');
      return owner_comments;
    '''.format(user_name))
    else:
        media = post_page[0]['media']
        is_video = media['is_video']
        user_name = media['owner']['username']
        image_text = media['caption']
        owner_comments = browser.execute_script('''
      latest_comments = window._sharedData.entry_data.PostPage[0].media.comments.nodes;
      if (latest_comments === undefined) latest_comments = Array();
      owner_comments = latest_comments
        .filter(item => item.user.username == '{}')
        .map(item => item.text)
        .reduce((item, total) => item + '\\n' + total, '');
      return owner_comments;
    '''.format(user_name))

    if owner_comments == '':
        owner_comments = None

    """Append owner comments to description as it might contain further tags"""
    if image_text is None:
        image_text = owner_comments
    elif owner_comments:
        image_text = image_text + '\n' + owner_comments

    """If the image still has no description gets the first comment"""
    if image_text is None:
        if graphql:
            image_text = media['edge_media_to_comment']['edges']
            image_text = image_text[0]['node']['text'] if image_text else None
        else:
            image_text = media['comments']['nodes']
            image_text = image_text[0]['text'] if image_text else None
    if image_text is None:
        image_text = "No description"

    logger.info('Image from: {}'.format(user_name.encode('utf-8')))

    """Find the number of followes the user has"""
    if like_by_followers_upper_limit or like_by_followers_lower_limit:
        userlink = 'https://www.instagram.com/' + user_name
        browser.get(userlink)
        # update server calls
        update_activity()
        sleep(1)
        num_followers = browser.execute_script(
            "return window._sharedData.entry_data."
            "ProfilePage[0].graphql.user.edge_followed_by.count")
        browser.get(link)
        # update server calls
        update_activity()
        sleep(1)
        logger.info('Number of Followers: {}'.format(num_followers))

        if like_by_followers_upper_limit and \
           num_followers > like_by_followers_upper_limit:
                return True, user_name, is_video, \
                    'Number of followers exceeds limit'

        if like_by_followers_lower_limit and \
           num_followers < like_by_followers_lower_limit:
                return True, user_name, is_video, \
                    'Number of followers does not reach minimum'

    logger.info('Link: {}'.format(link.encode('utf-8')))
    logger.info('Description: {}'.format(image_text.encode('utf-8')))

    """Check if the user_name is in the ignore_users list"""
    if (user_name in ignore_users) or (user_name == username):
        return True, user_name, is_video, 'Username'

    if any((word in image_text for word in ignore_if_contains)):
        return True, user_name, is_video, 'None'

    dont_like_regex = []

    for dont_likes in dont_like:
        if dont_likes.startswith("#"):
            dont_like_regex.append(dont_likes + "([^\d\w]|$)")
        elif dont_likes.startswith("["):
            dont_like_regex.append("#" + dont_likes[1:] + "[\d\w]+([^\d\w]|$)")
        elif dont_likes.startswith("]"):
            dont_like_regex.append("#[\d\w]+" + dont_likes[1:] + "([^\d\w]|$)")
        else:
            dont_like_regex.append(
                "#[\d\w]*" + dont_likes + "[\d\w]*([^\d\w]|$)")

    for dont_likes_regex in dont_like_regex:
        quash = re.search(dont_likes_regex, image_text, re.IGNORECASE)
        if quash:
            quashed = (((quash.group(0)).split('#')[1]).split(' ')[0]).split('\n')[0]   # dismiss possible space and newlines
            iffy = ((re.split(r'\W+', dont_likes_regex))[3] if dont_likes_regex.endswith('*([^\\d\\w]|$)') else   # 'word' without format
                     (re.split(r'\W+', dont_likes_regex))[1] if dont_likes_regex.endswith('+([^\\d\\w]|$)') else   # '[word'
                      (re.split(r'\W+', dont_likes_regex))[3] if dont_likes_regex.startswith('#[\\d\\w]+') else     # ']word'
                       (re.split(r'\W+', dont_likes_regex))[1])                                                    # '#word'
            inapp_unit = 'Inappropriate! ~ contains "{}"'.format(
                quashed.encode('utf-8') if iffy == quashed else
                '" in "'.join([iffy, quashed]).encode('utf-8'))
            return True, user_name, is_video, inapp_unit
    
    """NEW: Append location to image_text so we can search through both in one go. """
    if location_name:
        logger.info('Location: {}'.format(location_name.encode('utf-8')))
        image_text = image_text + '\n' + location_name

    """NEW: Search for must_haves in location and description. """
    if must_haves is not None:
        for must_have in must_haves:
            found_must_have = re.search(must_have, image_text, re.IGNORECASE)
            if must_haves_strict:
                """ If strict, then inappropiate if a single keyword is not found. """
                if found_must_have is None:
                    inapp_unit = 'Inappropiate! ~ does not contain must have keyword "{}"'.format(must_have)
                    return True, user_name, is_video, inapp_unit
            else:
                """ If not strict, than NOT inappropiate if a single keyword is found. """
                if found_must_have:
                    logger.info('Found one of must have keywords: {}'.format(must_have))
                    return False, user_name, is_video, 'None'
        if not must_haves_strict:
            """ If not strict, then inappriopiate if none of the keywords are found. """
            inapp_unit = 'Inappropiate! ~ does not contain must have keywords "{}"'.format(', '.join(must_haves))
            return True, user_name, is_video, inapp_unit

    return False, user_name, is_video, 'None'
```

In instapy.py I added two variable declarations:

 ```
      """ NEW: must_haves variable to store must have keywords. """
        self.must_haves = []
        self.must_haves_strict = False
```

In instapy.py I added a new method to set the must have keywords: 

```
   """ NEW: Must have keywords. If strict then all keywords must be present. 
    If not strict one of the keywords must be present. """
    def set_must_haves(self, tags=None, strict=False):
        
        if self.aborting:
            return self

        if not isinstance(tags, list):
            self.logger.warning('Unable to use your must_haves '
                                'configuration!')
            self.aborting = True

        self.must_haves = tags or []
        
        self.must_haves_strict = strict

        return self
```

In instapy.py, everywhere check_link is called, add the two new params. Code doesn't break if you forget it somewhere because the params are optional, but your must have keywords constraint will then be ignored. 

```
check_link(self.browser,
                                   link,
                                   self.dont_like,
                                   self.ignore_if_contains,
                                   self.ignore_users,
                                   self.username,
                                   self.like_by_followers_upper_limit,
                                   self.like_by_followers_lower_limit,
                                   self.logger,
                                   self.must_haves,
                                   self.must_haves_strict)
```

And finally, set your must have keywords. The strict parameter indicates wether all keywords (True) or one of the keywords (False) must be present. 

`session.set_must_haves(['O2', 'Arena'], strict=True)`

**Comment by sionking** [comment]
Nice thanks!
To strict for me (it wil lskip 99% of the profiles I guess)

**Comment by ohio36** [comment]
Thank you! I tend to search for specific hashtags that give me 90% or so good results, but there are always some false positives. Most posts in those 90% also have some other predictable keywords, while the false positives do not.  But yes, if you use this for a very broad hashtag, most of the initial set of posts will probably get marked as inappropriate.

**Comment by ohio36** [comment]
I'll try to give some better examples. Let's take the Madonna example again, but turn it around. You have been to Madonna's concert in the O2 Arena. You know that in the coming hours/days, many people will post pictures of the concert. You want to lead them to your profile with a very specific comment: "I loved the concert! I was able to take some great photos of Madonna!". With my new function you: 

Use the like_by_location method to search for the O2 Arena. Instead of commenting on everything you get, including photos of a concert last week from Beyonce, you add some must have keywords. If the post contains the word 'Madonna', you'll leave your comment. This prevents you from commenting on photos of Beyonce in the O2 Arena. Of course, this particular use case will get less effective once a new concert has been held by some other artist. 

If you are interested in photos of concerts of Madonna in general, you could also use like_by_tags with #madonna and then include a long list of non-strict keywords like concert, live, O2 Arena, concert venue X, concert venue Y, etc. Just put in a list with all the stadiums she is played at in the last year and you'll get very accurate results.

Another example: in my language the word vegetarian is often abbreviated to vega. Let's say I want to comment "I love to take photos of my vega food" and I use like_by_tags with #vega. Most photos will indeed be photos of vegetarian food. However, once every while there is a picture of the character Vega from video game Street Fighter. I could try to exclude those posts by using the set_dont_like method on 'streetfighter', but sometimes people don't use other hashtags which still gives me false positives (and a very dumb comment). Instead, now I can choose to only comment on photos that also include the words food, burger, or recipe. 

I might miss a couple of photos this way, but in my view that is better than leaving comments that lead to people questioning why the hell you placed that comment on their post. I could also use more generic comments like 'Nice one!', but I believe more specific comments are more effective and lead to more engagement.

**Comment by Tjorriemorrie** [comment]
@ohio36 this would be great, it requires some work to implement, it's basically a xboolean operation. But it's exactly like @sionking said: it's too sparse for the effort of listing multiple feeds and combining them for the number of entries you'll receive in the end.

**Comment by ohio36** [comment]
My implementation works wonders if you have quite a homogenous result set and you want to filter out the occasional mismatch. It will be terrible if you your result set has all kinds of results and you want to filter out a small subset. 

The hashtags I use tend to give quite homogenous results. About 90% of the result set is what I expected and relevant for my target. I use specific comments that I think result in a higher interaction rate. However, I look stupid when I post specific comments on those 10% of the result set that is totally different from what I expected to find based on the hashtag. So I really need to prevent those results from being in the result set. 

If you use generic comments like 'Nice post' there really isn't any use for my functionality, because it applies to whatever the post is about. In my experience, that is less effective in getting users to interact back though.

**Comment by webdevandeverythingelse** [comment]
Appreciate you taking the time to post this @ohio36! I'm going to give this a shot as I've been wanting to do compound hashtags for a while. Will update here if any tweaks are needed to make it work

**Comment by visualheroes** [comment]
_This is really something that needs to be added!

Liking only pictures with a certain tag at a specified geolocation is the holy grail for me. ;)
How can we help to make it happen?_

**EDIT: Forget what i wrote, i just tested like by location with mandatory words and it works. I feel like a fool now. ;)**

**Comment by webdevandeverythingelse** [comment]
Hey, @visualheroes - would you mind sharing with me how you do both location and mandatory words? Could you show a snippet of your config? Thanks! :)

**Comment by cprkrn** [comment]
> Hey, @visualheroes - would you mind sharing with me how you do both location and mandatory words? Could you show a snippet of your config? Thanks! :)

Sort by location, then session.set_mandatory_words(['#food', '#instafood'])!
