### ISSUE TITLE
Load button not found, working with current images!

### ISSUE THREAD

**Issue by dimmable** [InstaPy/InstaPy#1769]
## Expected Behavior
To like photos after retrieving the desired tag. 
## Current Behavior
Throwing an error saying load button not found, working with current images.

**Comment by Tjorriemorrie** [comment]
Can you copy and paste the log or output of that section with the error please?

**Comment by envieid0c** [comment]
WARNING [2018-03-30 14:01:49] [instauser]  Load button not found, working with current images!
WARNING [2018-03-30 14:01:49] [instauser]  Could not locate Chrome: Message: no such session
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.4.0-116-generic x86_64)

INFO [2018-03-30 14:01:49] [instauser]  Session ended - 2018-03-30 14:01:49
INFO [2018-03-30 14:01:49] [instauser]  --------------------


Message: no such session
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.4.0-116-generic x86_64)

**Comment by envieid0c** [comment]
WARNING [2018-03-30 14:13:54] [instauser]  Load button not found, working with current images!
WARNING [2018-03-30 14:13:54] [instauser]  Could not locate Chrome: Message: no such session
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.4.0-116-generic x86_64)

INFO [2018-03-30 14:13:54] [instauser]  Session ended - 2018-03-30 14:13:54
INFO [2018-03-30 14:13:54] [instauser]  --------------------


Message: no such session
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.4.0-116-generic x86_64)

**Comment by lairdep23** [comment]
Same Error here but here's my output:

Load button not found, working with current images!
Traceback (most recent call last):
  File "evan.py", line 29, in job
    session.like_by_tags(['lifemotivation','fitnessmotivation' 'peanutbutter', 'entrepreneurmindset', 'fitness'], amount=50)
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 568, in like_by_tags
    skip_top_posts)
  File "/home/ubuntu/InstaPy/instapy/like_util.py", line 203, in get_links_for_tag
    body_elem.send_keys(Keys.HOME)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webelement.py", line 320, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': keys_to_typing(value)})
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.4.0-1049-aws x86_64)

**Comment by MrBeardedGuy** [comment]
Update to the latest chromedriver here https://sites.google.com/a/chromium.org/chromedriver/ and make sure you pulled the latest master

**Comment by d7laungani** [comment]
I did and I still have the issue
