### ISSUE TITLE
Error when trying to run docker container on Ubuntu

### ISSUE THREAD

**Issue by dlt** [InstaPy/InstaPy#177]
I'm getting the following error when trying to run InstaPy on an Ubuntu machine + docker

> Traceback (most recent call last):
>   File "quickstart.py", line 15, in <module>
>     InstaPy()\
>   File "/InstaPy/instapy/instapy.py", line 37, in __init__
>     self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
>     desired_capabilities=desired_capabilities)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
>     self.start_session(desired_capabilities, browser_profile)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
>     response = self.execute(Command.NEW_SESSION, capabilities)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
>   (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-72-generic x86_64)

**Comment by pekapa** [comment]
just add `nogui=True` to the `InstaPy` constructor in your `quickstart.py`

**Comment by pattersonrptr** [comment]
I'm having the same problem but it did not help put nogui=True in the constructor, it still gives the same error. Did you get it fixed?
