### ISSUE TITLE
Cron - When scheduling to run task, they always end sooner with error

### ISSUE THREAD

**Issue by kristofenyi** [InstaPy/InstaPy#1772]
Hello,

When i run my scripts normally through bash they execute until the end just fine.
When i put them in cron jobs to be executed they usually end sooner with an error.

Any ideas how to resolve this?

## general.log output

INFO [2018-03-28 16:51:52] [username]  Username [13/40]
INFO [2018-03-28 16:51:52] [username]  --> veronika_povova
INFO [2018-03-28 16:51:57] [username]  Getting veronika_povova image list...
INFO [2018-03-28 16:52:25] [username]  Interaction begin...
INFO [2018-03-28 16:52:58] [username]  --> Not following
INFO [2018-03-28 16:52:59] [username]  Post [1/4]
INFO [2018-03-28 16:52:59] [username]  https://www.instagram.com/p/8Q2cWIB3n6/?taken-by=veronika_povova
INFO [2018-03-28 16:53:05] [username]  Image from: veronika_povova
INFO [2018-03-28 16:53:14] [username]  Number of Followers: 176
INFO [2018-03-28 16:53:14] [username]  Link: https://www.instagram.com/p/8Q2cWIB3n6/?taken-by=veronika_povova
INFO [2018-03-28 16:53:14] [username]  Description: Svatováclavská vinice a vinobraní nad Prahou 🍷😍
INFO [2018-03-28 16:53:17] [username]  --> Image Liked!
INFO [2018-03-28 16:53:19] [username]  --> Not commented
INFO [2018-03-28 16:53:20] [username]  Post [2/4]
INFO [2018-03-28 16:53:20] [username]  https://www.instagram.com/p/9imit0h3gJ/?taken-by=veronika_povova
INFO [2018-03-28 16:53:26] [username]  Image from: veronika_povova
INFO [2018-03-28 16:53:34] [username]  Number of Followers: 176
INFO [2018-03-28 16:53:34] [username]  Link: https://www.instagram.com/p/9imit0h3gJ/?taken-by=veronika_povova
INFO [2018-03-28 16:53:34] [username]  Description: #pičovinky 😂😂😍
INFO [2018-03-28 16:53:37] [username]  --> Image Liked!
INFO [2018-03-28 16:53:39] [username]  --> Not commented
INFO [2018-03-28 16:53:40] [username]  Post [3/4]
INFO [2018-03-28 16:53:40] [username]  https://www.instagram.com/p/7f4Xs3B3kS/?taken-by=veronika_povova
WARNING [2018-03-28 16:53:44] [username]  Could not locate Chrome: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=65.0.3325.146)
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.13.0-37-generic x86_64)

INFO [2018-03-28 16:53:44] [username]  Session ended - 2018-03-28 16:53:44
INFO [2018-03-28 16:53:44] [username]  --------------------

**Comment by Tjorriemorrie** [comment]
What's the time difference from when it starts and end?
