### ISSUE TITLE
Prevent duplicate comments on the same post?

### ISSUE THREAD

**Issue by deronsizemore** [InstaPy/InstaPy#1774]
## Expected Behavior

Comment on a post once.

## Current Behavior

I noticed this morning after a user replied to one of my auto-comments that I auto-commented on this post twice. Makes it pretty obvious that it's a bot.

## InstaPy configuration

    session.set_do_comment(enabled=True, percentage=15)
    session.set_comments([u'Nice shot! :heart:', u'Really nice! :thumbsup:', u'Loving your work! :smile:', u'This is :fire:', u'Great work! :heart:', u'Love it! :heart: :thumbsup:', u'Very nice!'])

**Comment by CharlesCCC** [comment]
I don't see this happing, because, the Instapy will check if the image already liked or not, if it already liked, it will not like it again( apparently you can't like it twice), without liking, the Instapy will not left any comment.

**Comment by MrBeardedGuy** [comment]
I had this issue happening multiple times to... Also reported here https://github.com/timgrossmann/InstaPy/issues/1693

@CharlesCCC Could it be that when used together`like_by_feed` and `like_by_tags`might cause this bug?

**Comment by deronsizemore** [comment]
@MrBeardedGuy 

Could be, but that's not my issue since I'm not using both of those together. Here's my full settings and actions right now:

    # settings
    session.set_do_follow(True, percentage=80, times=1)
    session.set_lower_follower_count(limit=50)
    session.set_do_comment(enabled=True, percentage=15)
    session.set_user_interact(amount=3, randomize=True, percentage=100)
    session.set_comments([u'Nice shot! :heart:', u'Really nice! :thumbsup:', u'Loving your work! :smile:', u'This is :fire:', u'Great work! :heart:', u'Love it! :heart: :thumbsup:', u'Very nice!'])

    # actions
    session.like_by_tags(like_tags, amount=100, interact=True)

**Comment by CharlesCCC** [comment]
I think @MrBeardedGuy had a point, similar with @deronsizemore 's setting
`session.set_user_interact(amount=3, randomize=True, percentage=100)` 

what if you two turn off those two setting for a bit and then to see if the issue still persist or not, if it is, then we can confirm that is the issue and we can go back debug/fix it. Thank you.

**Comment by deronsizemore** [comment]
Thanks. I'll do that and report back

**Comment by deronsizemore** [comment]
I've had set_user_interact removed for a little while now and haven't noticed any duplicates

**Comment by CharlesCCC** [comment]
@deronsizemore thank you for report back, now at least we confirmed the `set_user_interact` is the issue, we should able to have someone spare sometime to debug the issue and hopefully fix this issue soon.

**Comment by deronsizemore** [comment]
@CharlesCCC Any new developments on this?
