### ISSUE TITLE
Message: unknown error: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by alessiomtt** [InstaPy/InstaPy#1776]
![errore](https://user-images.githubusercontent.com/34484439/38106280-c1e9d1cc-338e-11e8-9c95-c3097c2f6355.JPG)

Fresh installed InstaPy and this appened..

Setup alredy done

**Comment by uluQulu** [comment]
Hey @alessiomatt1 
There is a [workaround](https://github.com/timgrossmann/InstaPy/issues/1338#issuecomment-377719941) for it in #1338
