### ISSUE TITLE
Problem Downloading GUI

### ISSUE THREAD

**Issue by alexi26** [InstaPy/InstaPy#1778]
Hi,

i just tried to install the instabot, but i am not able to download the GUI. 
this link is not working:
[https://github.com/Nemixalone/GUI-tool-for-InstaPy-script]

can someone help me?

Cheers

**Comment by BoneS38** [comment]
Not working for me neither.

**Comment by trosky777** [comment]
i think its this one... 
https://github.com/ahmadudin/electron-instaPy-GUI
