### ISSUE TITLE
Unfollow Error; Raspberry pi

### ISSUE THREAD

**Issue by skaeslin** [InstaPy/InstaPy#1779]
Hello everyone

First of all thanks a lot for this awesome tool for my raspberry pi 3 and the community! Since the beginning Instapy would not unfollow the people it followed before with `onlyInstapyFollowed = True`. I tried to reinstall everything and tried different scripts but it just would not work. Can ayone help me please?

## Expected Behavior
`session.unfollow_users(amount=100, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60 )`
## Current Behavior

```
INFO [2018-03-30 00:44:37] [XXXXX]  Session started - 2018-03-30 00:44:37
INFO [2018-03-30 00:45:09] [XXXXX]  Logged in successfully!
INFO [2018-03-30 00:45:16] [XXXXX]  Number of users available to unfollow: 0
INFO [2018-03-30 00:45:20] [XXXXX]  --> Total people unfollowed : 0 
INFO [2018-03-30 00:45:20] [XXXXX]  Session ended - 2018-03-30 00:45:20
INFO [2018-03-30 00:45:20] [XXXXX]  --------------------
```
-> I know there are around 40 people it should have to unfollow. 

## Possible Solution (optional)
???
## InstaPy configuration
Raspberry Pi 3

```
from instapy import InstaPy

insta_username = 'XXXXXX'
insta_password = 'password'


session = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
session.login()
                                                                                                                                                                                                    
session.unfollow_users(amount=100, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60 )

session.end()
```
Thanks a lot for all of your answers! :D # #

**Comment by Luisjanz** [comment]
Same here do you fixed it?

**Comment by skaeslin** [comment]
Sadly no...
