### ISSUE TITLE
InstaPy on Chromebook

### ISSUE THREAD

**Issue by imovertheinternet** [InstaPy/InstaPy#178]
For anyone interested, its possible and currently running great for me. Originally was going to try @timgrossmann way of setting it up on a raspberry pi but didnt want to pay exagear and remembered I had an old chromebook (intel chipset). Installed crouton to get Linux on the machine, then install python and its dependencies, the Chromium browser works great with the new Webdrivers, and youre golden. Figured Id spread the word as im happy to have this humming on my CB and not tying up my MBP anymore! Let me know if you have any questions.

**Comment by axlright** [comment]
@imovertheinternet I'm glad you posted this. I'm thinking of doing the same thing. I didn't know about paying exagear. But with the cheapness of Chromebooks and the having a screen and keyboard, this seems like a good idea.

Do you have any recommended devices to look for / keep away from? Any other suggestions / info?

THXXX 💯
