### ISSUE TITLE
instapy crashing shortly after login

### ISSUE THREAD

**Issue by dariusd3** [InstaPy/InstaPy#1780]
Hello developers. I absolutely love this forum and all of the great feed back. However I cannot figure out how to solve this problem. Please note that this is my first post on a forum and I am brand new to programming. I have downloaded all of the required files and still not able to properly run instapy. Login is successful and then about a second later I get this code....

Traceback (most recent call last):
File "quickstart.py", line 17, in 
session.login()
File "/Users/d/Desktop/InstaPy-master/instapy/instapy.py", line 271, in login
self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
File "/Users/dariusdio/Desktop/InstaPy-master/instapy/print_log_writer.py", line 11, in log_follower_num
"return window._sharedData.""entry_data.ProfilePage[0]."
File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
'args': converted_args})['value']
File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
self.error_handler.check_response(response)
File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
(Session info: chrome=65.0.3325.181)
(Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.12.6 x86_64)

I downloaded python 3 but 2.7 keeps popping up. I'm not sure if thats a problem but I hope someone can help. Thank you for all your help.

**Comment by dariusd3** [comment]
Hello developers. I absolutely love this forum and all of the great feed back. However I cannot figure out how to solve this problem. Please note that this is my first post on a forum and I am brand new to programming. I have downloaded all of the required files and still not able to properly run instapy. Login is successful and then about a second later I get this code....

Traceback (most recent call last):
  File "quickstart.py", line 17, in <module>
    session.login()
  File "/Users/d/Desktop/InstaPy-master/instapy/instapy.py", line 271, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "/Users/dariusdio/Desktop/InstaPy-master/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.12.6 x86_64)

I downloaded python 3 but 2.7 keeps popping up. I'm not sure if thats a problem but I hope someone can help. Thank you for all your help.

**Comment by riccardorighettiphoto** [comment]
same here, but only after having applied the fix proposed by @uluQulu in the #1365 issue.
I have as you Chrome v65.0.3325, Chromedriver v2.37, python 2.7, running on a Centos 7 VPS.
When I run InstaPy without the @uluQulu's fix, I don't get any error, but only 27 images analyzed for liking. :(

**Comment by GithubStarmedia** [comment]
i have the next problem: 
INFORMACIÓN: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
org.openqa.selenium.SessionNotCreatedException: session not created exception
from disconnected: unable to connect to renderer
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.13.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.00 seconds
Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
System info: host: 'MacBook-Pro-de-Abraham.local', ip: '192.168.0.16', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_60'
Driver info: driver.version: RemoteWebDriver


Any ideas?

**Comment by uluQulu** [comment]
hi @dariusd3 have you seen the [approach](https://github.com/timgrossmann/InstaPy/issues/1338#issuecomment-363067955) in #1338?

**Comment by dariusd3** [comment]
@uluQulu I just took a look but I am running mac os. I have no clue what happened. I downloaded python 3.6 and when I run the script the error still shows 2.7 and when I run python3.6 quickstart.py I get 

Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    session.login()
  File "/Users/darius/Desktop/InstaPy-master/instapy/instapy.py", line 264, in login
    self.bypass_suspicious_attempt):
  File "/Users/darius/Desktop/InstaPy-master/instapy/login_util.py", line 130, in login_user
    click().send_keys(username).perform()
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/action_chains.py", line 74, in perform
    action()
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/action_chains.py", line 267, in <lambda>
    Command.SEND_KEYS_TO_ACTIVE_ELEMENT, {'value': keys_to_typing(keys_to_send)}))
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/utils.py", line 150, in keys_to_typing
    for i in range(len(val)):
TypeError: object of type 'NoneType' has no len()
dariuss-MacBook-Pro:instapy-master d$ python3.6 quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/dariusdio/Desktop/InstaPy-master/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/Users/dariusdio/Desktop/InstaPy-master/instapy/instapy.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests

**Comment by uluQulu** [comment]
@dariusd3 why did you change Python version?
all you had to do was to handle one line in **print_log_writer.py**...
anyways, from my experiences, python 2 & 3 installed on the same machine makes troubles unless you precisely set environmental variables, so, in your case, for ease, keep either one version in your machine

> and for the error above you must install `requests` from pip

**Comment by dariusd3** [comment]
@uluQulu When I was looking for solutions to see why instapy was crashing in the beginning I opened up "read me" and figured I needed python 3 to run the terminal. 

@timgrossmann 
[![built with Python3](https://img.shields.io/badge/built%20with-Python3-red.svg)](https://www.python.org/)
[![Travis](https://img.shields.io/travis/rust-lang/rust.svg)](https://travis-ci.org/timgrossmann/InstaPy)

I thought it wouldn't hurt but I was getting same results. Would you help me delete python 3.6 now and correct the print_log_writer.py
Thank you!

**Comment by uluQulu** [comment]
@dariusd3 
if you mean the error you have started this issue with, it really is in IG side, meaning a temporary outage from FB servers, if you see other errors else than this, I don't know about them..
but there are lots of people using InstaPy with Python 2, although Python 3 is always better to use (_cos it is the latest version of python and python guys will keep to support version 2 for some more time..._)

i have no idea why you find difficulty removing it but try to simply remove it by default uninstallers and web is full of the information on this topic, just hit google engines xD
also _attach your **print_log_writer.py** file, I will see and tell where and how to edit_

**Comment by dariusd3** [comment]
@uluQulu 
So I uninstalled python 3.6 and ran the program hoping it was the python install. I don't think python 3.6 is compatible with insta-py because although the script still failed to start is at least opened instagram and tried to run. It left this error in the end....

INFO [2018-04-04 15:42:31] [None]  Session started - 2018-04-04 15:42:31
Cookie file not found, creating cookie...
INFO [2018-04-04 15:42:35] [None]  Session ended - 2018-04-04 15:42:35
INFO [2018-04-04 15:42:35] [None]  --------------------


print log writer file is as follows: 

Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    session.login()
  File "/Users/dariusdio/Desktop/InstaPy-master/instapy/instapy.py", line 264, in login
    self.bypass_suspicious_attempt):
  File "/Users/dariusdio/Desktop/InstaPy-master/instapy/login_util.py", line 130, in login_user
    click().send_keys(username).perform()
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/action_chains.py", line 74, in perform
    action()
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/action_chains.py", line 267, in <lambda>
    Command.SEND_KEYS_TO_ACTIVE_ELEMENT, {'value': keys_to_typing(keys_to_send)}))
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/utils.py", line 150, in keys_to_typing
    for i in range(len(val)):
TypeError: object of type 'NoneType' has no len()

My print_log_writer.py is ...

"""Module only used to log the number of followers to a file"""
from datetime import datetime


def log_follower_num(browser, username, logfolder):
    """Prints and logs the current number of followers to
    a seperate file"""
    browser.get('https://www.instagram.com/' + username)

    followed_by = browser.execute_script(
        "return window._sharedData.""entry_data.ProfilePage[0]."
        "user.followed_by.count")

    with open('{}followerNum.txt'.format(logfolder), 'a') as numFile:
        numFile.write(
            '{:%Y-%m-%d %H:%M} {}\n'.format(datetime.now(), followed_by or 0))

    return followed_by


def log_followed_pool(login, followed, logger, logfolder):
    """Prints and logs the followed to
    a seperate file"""
    try:
        with open('{0}{1}_followedPool.csv'.format(logfolder, login), 'a+') as followPool:
            followPool.write('{},\n'.format(followed))
    except BaseException as e:
        logger.error("log_followed_pool error {}".format(str(e)))

    # We save all followed to a pool that will never be erase
    log_record_all_followed(login, followed, logger, logfolder)


def log_uncertain_unfollowed_pool(login, unfollowed, logger, logfolder):
    """Prints and logs the uncertain unfollowed to
    a seperate file"""
    try:
        with open('{0}{1}_uncertain_unfollowedPool.csv'.format(logfolder, login), 'a+') as followPool:
            followPool.write('{},\n'.format(unfollowed))
    except BaseException as e:
        logger.error("log_uncertain_unfollowed_pool error {}".format(str(e)))


def log_record_all_unfollowed(login, unfollowed, logger, logfolder):
    """logs all unfollowed ever to
    a seperate file"""
    try:
        with open('{0}{1}_record_all_unfollowed.csv'.format(logfolder, login), 'a+') as followPool:
            followPool.write('{},\n'.format(unfollowed))
    except BaseException as e:
        logger.error("log_record_all_unfollowed_pool error {}".format(str(e)))


def log_record_all_followed(login, followed, logger, logfolder):
    """logs all followed ever to a pool that will never be erase"""
    try:
        with open('{0}{1}_record_all_followed.csv'.format(logfolder, login), 'a+') as followPool:
            followPool.write('{},\n'.format(followed))
    except BaseException as e:
        logger.error("log__record_all_followed_pool error {}".format(str(e)))

**Comment by uluQulu** [comment]
@dariusd3 
InstaPy is definetely compatible with python 3. You might had a problem with suspicious login, try to solve it. (_also, it seems your InstaPy still used selnium from Python 2 packages_)
Sharing long code in comments is a headache, indentation errors, blah blah... can you [gist](https://gist.github.com/) that file so that I can easily edit or send full file by dragging and dropping to this comment box?

**Comment by gannicus4431** [comment]
Anyone getting this error message after a few tries?

Traceback (most recent call last):
  File "/Users/Jimmy/InstaPy/quickstart.py", line 35, in <module>
    session.like_by_tags(['natgeo', 'world'], amount=100)
  File "/Users/Jimmy/InstaPy/instapy/instapy.py", line 892, in like_by_tags
    self.logger)
  File "/Users/Jimmy/InstaPy/instapy/like_util.py", line 564, in check_link
    '" in "'.join([iffy, quashed]))
TypeError: sequence item 1: expected str instance, bytes found

**Comment by dariusd3** [comment]
@uluQulu 
I ended up deleting python 3 and the instapy off my computer then reinstall. That fixed the problem for me. 
Note taken for the gist. Sorry I had no clue how to put the code on the forum. :) Thank you for your help. 
Also is there a forum that shows how to follow and unfollow without deleting your own friends?

**Comment by uluQulu** [comment]
hi @dariusd3 
```python
# completely ignore liking images from certain users
session.set_ignore_users(['random_user', 'another_username'])
```
```python
# will prevent commenting on and unfollowing your good friends (the images will still be liked)
session.set_dont_include(['friend1', 'friend2', 'friend3'])
```
those are existing features (_see docs_)
>BTW `gist`ing is _very easy_, [**try**](https://gist.github.com/) pasting your code!

**Comment by dariusd3** [comment]
Hi @uluQulu : I have to manually insert all 300+ friends in the prevent unfollowing. There isn't a copy past version? I sound lazy but just wanted to make sure. ahhhh. :D 

Also where can I find the emoji codes? Thank you so much for your undying help UluQulu!!!

**Comment by uluQulu** [comment]
hi @dariusd3,
Well, I believe _one cannot have 300 friends_, **maybe** you mean the people who follow you :)
**You can** get that list of people who follow you through a graphql query easily **and** the `only NotFollowMe=True` paramter in `unfollow_users` feature is just for that reason!
##### I've got couple of emoji codes in my quickstart I will share with you,
```powershell
comments_list = [
u'you deserve a big applause!!! @{} ☃⛄👑📷😂',
u'📷courteous😊😎😉👍 @{}',
u'@ {}, stupendous! 😂😅🤣',
u'rich in implication,,, brilliant artwork, @{}! 💪😄☃',
u'sensational, @{}! 🙂😊😎😉',
u'a plus work, @{} ! 👍',
u'@{}, what an imagination! 📸🤗',
]
session.set_comments(comments=comments_list, media='Photo')
```
>Most of the emojis in high-end mobile phones are supported by IG interface, so feel free to use the ones you like, by just adding `u` before comments which adds support for emojis.

**Comment by dariusd3** [comment]
hey @uluQulu 
This is so awesome! Thank you so much. I am very grateful to be able to learn from the master! 

The 300 friends is actual people I know that I follow and I don't want to unfollow them. Are you saying when I run the unfollow/ follow code that the people I actually know will be protected and not unfollowed? Or do I have to manually add them in the code to not unfollow? 
Thank you!

**Comment by uluQulu** [comment]
Welcome, @dariusd3,
You can get the list of those people through a graphql query and whitelist them using,
```python
set_dont_include( friends=None)
```
feature.
> I am far from being a master, but thank you :P
