### ISSUE TITLE
Error: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by 0xkvai** [InstaPy/InstaPy#1785]
## Expected Behavior
Bot runs fine

## Current Behavior
but will randomly exit with the following error
"selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined"

## Possible Solution (optional)
I have tried changing my ubuntu version between 16 & 14.
I have tried changing my Chrome verision to  62 and chromedriver 2.34
I have tried changing my chrome version to most up to date with chromedriver 2.37
I have tried changing my chromedriver to 2.36

## InstaPy configuration
Running on ubuntu server.

from instapy import InstaPy

insta_username = 'Username'
insta_password = 'Password'

try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      multi_logs=True,
                      headless_browser=True)
    session.login()

    # settings
    session.set_upper_follower_count(limit=3000)
    session.set_do_comment(True, percentage=10)
    session.set_comments([u'Great Shot!', 'Love it!', 'Great Photo!', u'Awesome! 📸'])
    session.follow_user_followers(['userName'], amount=1, randomize=False, sleep_delay=60)

    # actions
    session.like_by_tags(['tagone','tagtwo','tagthree', 'tagfour'], amount=3)
    session.like_by_locations(['location'], amount=5)

finally:
    # end the bot session
    session.end()

**Comment by 0xkvai** [comment]
![screen shot 2018-03-30 at 3 21 06 pm](https://user-images.githubusercontent.com/14112830/38158402-8ce80420-3448-11e8-9785-d80a382efc51.png)

**Comment by uluQulu** [comment]
Hey @Kylescottw 
There is a [workaround](https://github.com/timgrossmann/InstaPy/issues/1338#issuecomment-377719941) for it in #1338

**Comment by 0xkvai** [comment]
@uluQulu 
Thank you so much,
i will review this again.

**Comment by morrigan** [comment]
I've started receiving this error 2 days ago. It's constant and resetting everything can't seem to fix it. Linux distro

**Comment by rohrz4nge** [comment]
Here having the same issue since yesterday on the latest version.

**Comment by rohrz4nge** [comment]
Do you have the error on business accounts? For my private account everything works fine, I only get the error with my business account.

**Comment by morrigan** [comment]
@rohrz4nge yes, business account.
