### ISSUE TITLE
like_by_feed in instapy stops working without throwing any error

### ISSUE THREAD

**Issue by dgunawan** [InstaPy/InstaPy#1786]
## Expected Behavior
like_by_feed should start liking the user's feed depending on the amount of likes it should do

## Current Behavior
like_by_feed has been refactored early March to call another method, like_by_feed_generator.

Without throwing any error the session will just end without doing any likes whatsoever. This is what was shown in the log file:
```

INFO [2018-03-31 10:46:40] [username]  Session started - 2018-03-31 10:46:40
INFO [2018-03-31 10:47:11] [username]  Logged in successfully!
INFO [2018-03-31 10:47:13] [username]  Session ended - 2018-03-31 10:47:13
INFO [2018-03-31 10:47:13] [username]  --------------------
```

As can be seen, the session ended less than a minute from when it was started!

## InstaPy configuration
The session was started from within this block of code:

```
try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=True,
                      multi_logs=True)
    session.login()

    session.like_by_feed(amount=100, randomize=True, unfollow=True, interact=True)

finally:
    # end the bot session
    session.end()
```
Using Google Chrome, and the driver was recently updated to v2.37 (20 March)

**Comment by kekbait** [comment]
Same problem here.
like_by_feed() function never starts, and bot's session ends directly.

**Comment by kekbait** [comment]
I worked around it by checking out the commit just before d968fbee88580cea2fc3031f6ccae20b980b5351  
`git checkout 486543cf25a980106ab3f4440aa4bf9362175896`
and it worked.

Still, we need to fix this bug introduced by d968fbee88580cea2fc3031f6ccae20b980b5351

**Comment by kekbait** [comment]
Looks like it has already been fixed here : https://github.com/timgrossmann/InstaPy/pull/1782

**Comment by dgunawan** [comment]
Thanks @kekbait, I'll monitor the pull request, pull master once it's merged, test and close this issue when I've verified that the fix works.

**Comment by CharlesCCC** [comment]
Please pull down the latest version, the PR #1782 has been merged.
