### ISSUE TITLE
Windows script downloads an old chromedriver

### ISSUE THREAD

**Issue by Honigbrot** [InstaPy/InstaPy#1788]
## Expected Behavior
Windows instalation script (scripts/windows.ps1) should install (apart from GUI and selenium etc.) the latest chromedriver.

## Current Behavior
Installs chromedriver 2.34
Upon start instapys says it reguires 2.36+

## Possible Solution (optional)
Change the windows.ps1 script 
lines in windows.ps1:
echo "Downloading Chrome Driver..."
$webclient = New-Object System.Net.WebClient
$webclient.DownloadFile("https://chromedriver.storage.googleapis.com/2.34/chromedriver_win32.zip","$pwd\chromedriver.zip")
echo "Chrome Driver download completed."

**Comment by CharlesCCC** [comment]
apparently the ` windows.ps1` is outdated, try not using that at the moment until somebody get it fixed. 
use the `setup.py` script instead, You can find the instruction in the main page.
