### ISSUE TITLE
pip install . error

### ISSUE THREAD

**Issue by bwalsh1181** [InstaPy/InstaPy#1789]
I am trying to set it up (OS X) and when I run "pip install ." I get this error

```
Processing /Users/*username*/Desktop/InstaPy
Collecting Selenium ==2.53.6 (from Instagram-py==0.0.1)
Trace/BPT trap: 5
```

The I get a popup "Python quit unexpectedly" error

**Comment by MrBeardedGuy** [comment]
You might want to try `sudo easy_install pip` before running `pip install .`
or try the second installation method `python setup.py install`

**Comment by converge** [comment]
hey @bwalsh1181 this setup is outdated, do pip install selenium, it will download the 3.x version
