### ISSUE TITLE
ImportError: cannot import name 'InstaPy'

### ISSUE THREAD

**Issue by hgoldenberg** [InstaPy/InstaPy#1792]
Hi, i am trying to run Basic Setup with quickstart.py and have the following error:
ImportError                               Traceback (most recent call last)
<ipython-input-21-c798bc0bbdc5> in <module>()
      5 from selenium.common.exceptions import NoSuchElementException
      6 
----> 7 from instapy import InstaPy
      8 
      9 
ImportError: cannot import name 'InstaPy'

I am using Mac OS Sierra High 10.13.3, Google Chrome Versión 63.0.3239.84 (Build oficial) (64 bits), the latest version of chromedriver (into InstaPy/assets) and Jupyter notebook

On the other hand y tried via Command Line and have the following error: InstaPyError: ensure chromedriver is installed at /Users/hernangoldenberg/InstaPy/assets/chromedriver.

Please, could you help me?? thanks in advance,
Hernan

**Comment by hgoldenberg** [comment]
I solved the command line issue but i still have the problem with jupyter notebook as mentioned above....thanks
Hernan

**Comment by CharlesCCC** [comment]
have you followed the instruction run the `setup.py` ?

**Comment by hgoldenberg** [comment]
Hi Charles, i run the setup.py but i have the following error:

Last login: Tue Apr  3 12:02:52 on ttys000
MacBook-Air-de-Hernan:~ hernangoldenberg$ cd Instapy
MacBook-Air-de-Hernan:Instapy hernangoldenberg$ python setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
MacBook-Air-de-Hernan:Instapy hernangoldenberg$ 
What am I doing wrong??
Thanks

**Comment by CharlesCCC** [comment]
please read the instruction carefully https://github.com/timgrossmann/InstaPy#basic-installation 

```
1. git clone https://github.com/timgrossmann/InstaPy.git
2. cd InstaPy
3. pip install .
or
3. python setup.py install
```
