### ISSUE TITLE
Lost Followpool list

### ISSUE THREAD

**Issue by condomfighters** [InstaPy/InstaPy#1795]
## Expected Behavior
Followpool list not empty
## Current Behavior
followpool list empty without reason or error
## Possible Solution (optional)
copy the the name of the people i follow and paste them there
## InstaPy configuration
custom file.

Today i tried to let instapy unfollow but always stopped
I check the followpool file and it was empty, i have no idea why
Is there a way to fix this?
If i could get my hands on the list of people i follow it would not matter
but since i'm a noob i don't know how to do this.
Anyone had the same issue or knows the solution to this problem
I'm still not sure what happened to the list atm but i'm trying to figure it out.
all other lists are fine.

thanks

**Comment by timmoh** [comment]
i had the same issue before but i restored the file via mac os time machine. 
wouldn't it be better to save all data to the database instead of table?
It would be easy give the user a flag (in a db column) if it isn't followed anymore

**Comment by condomfighters** [comment]
i just formatted my laptop recently and don't have a restore file.
from now on i'm saving all data manually somewhere just to be safe.
i had no idea this was possible actually.

**Comment by CharlesCCC** [comment]
if it empty, that meants it has already unfollowed every single user you has followed through InstaPy,

**Comment by condomfighters** [comment]
that's not possible because I have 3k+ people following on my Instagram account right now

**Comment by CharlesCCC** [comment]
@condomfighters Oops... I guess you can try get the list back from the `followRestriction.json` Otherwise, I can't think of any better way to get the list back.

**Comment by condomfighters** [comment]
i'm trying to find a way to export my followings to an excel file that should fix the problem. I thought more people would have this problem but apparently, i'm the only one.
maybe i did something wrong.

**Comment by mkraffa** [comment]
same issue here;
it looks like it has already unfollowed every single user it has followed through InstaPy; but that's just not possible...
must be a cleaner way that resrtoring the file to a previous version?

**Comment by CharlesCCC** [comment]
@mkraffa why that is not possible ? if you have followed 100 people, and currently you only follow 1 people each time, then 10 times later, you will have nobody left in the followed pool.

**Comment by mkraffa** [comment]
@CharlesCCC 
instapy alone follows 90% of all.
so if I follow 2500 accounts, 2250 should be in the followpool file no?
and right now I have 0 available for unfollow

**Comment by CharlesCCC** [comment]
@mkraffa well, i meant,it also depend on how many people you unfollow on each run. 
let say you have followed 10% of 100 likes, and then unfollowed 10 users each time.
in reality there should have no-one left in the followedpool file after each run.

**Comment by mkraffa** [comment]
@CharlesCCC 
the problem here, is that I had a followpool, which is now empty... not because they were unfollowed

**Comment by CharlesCCC** [comment]
@mkraffa I understand that.  There must be a reason why it is empty. 
If you open your `general.txt` log file,  you should have see the long list of "unfollowed" people.
