### ISSUE TITLE
No like photo with some words.

### ISSUE THREAD

**Issue by gustafsom** [InstaPy/InstaPy#1796]
Good morning friends, the setting: `session.set_dont_like (['#matmatch', '[startswith', '] endswith', 'broadmatch'])`

no like in the photo containing the hashtag. ['#matmatch', '[startswith', '] endswith', 'broadmatch'])`

but I wish it were not liked the photos that contain those words also in the **commentaries**.

how can I do this?

**Comment by MrBeardedGuy** [comment]
I believe it's not possible. InstaPy doesn't read comments, only post descriptions...

**Comment by gustafsom** [comment]
Hi, @MrBeardedGuy  thanks for your attention.

I think I expressed myself poorly. I want instapy to check the description of the post and not the comments.

If the instapy finds some unwanted word it does not like the photo.

Excuse me.

**Comment by MrBeardedGuy** [comment]
Check the guide here https://github.com/timgrossmann/InstaPy#restricting-likes

`.set_dont_like` is the function you're looking for

> searches the description and owner comments for hashtags and won't like the image if one of those hashtags are in there

**Comment by gustafsom** [comment]
I use this function. It checks for Hashtags only.

I would like to check some words also in the description of the photo.
