### ISSUE TITLE
Don't unfollow friends

### ISSUE THREAD

**Issue by lucanello** [InstaPy/InstaPy#1797]
Since the unfollowing action doesn't quite work especially when users change their name, I have thought of a different solution which might already work.
What about defining a blacklist of friends that shouldn't be unfollowed and the rest is being unfollowed? Is this already possible with the dont_include/friends parameter?

**Comment by CharlesCCC** [comment]
a little search function is your best friend [Unfollow-Excluding-Friends](https://github.com/timgrossmann/InstaPy#excluding-friends)
