### ISSUE TITLE
FEATURE REQUEST: Interact in Follow_by_tags

### ISSUE THREAD

**Issue by RafNadler** [InstaPy/InstaPy#1799]
FEATURE REQUEST
## Expected Behavior
Like 5 pictures of the account I followed by follow_by_tag
## Current Behavior
Not possible
## Possible Solution (optional)
I tried coding it myself but no luck yet ...

**Comment by CharlesCCC** [comment]
Is this what you are looking for ? [https://github.com/timgrossmann/InstaPy#like-by-tags-and-interact-with-user](https://github.com/timgrossmann/InstaPy#like-by-tags-and-interact-with-user)

**Comment by RafNadler** [comment]
No it is not. This likes pictures by tags and then likes pictures of the poster. I want to Follow by tags and then like pictures of that person.
