### ISSUE TITLE
Add docker

### ISSUE THREAD

**Issue by apertureless** [InstaPy/InstaPy#18]
Thought about dockerizing it ? Would be way easier to deploy.

**Comment by timgrossmann** [comment]
Yes, I just lately thought about that.

I don't have enough knowledge in this area by now but I'm open to PR's 😉 
I mean, writing a Dockerfile shouldn't be too hard and time consuming, but right now I sadly don't have the time to cover any of the open Issues...

**Comment by stephane-archer** [comment]
Done ;) see pool request :D

**Comment by timgrossmann** [comment]
@stephane-archer Awesome thank you!
Fixed by #32 

Edit: Still open till merge

**Comment by timgrossmann** [comment]
#77 will resolve this issue...
Just the encoding isn't working... Does someone have an idea?
@apertureless @stephane-archer @jaycegregg0

**Comment by timgrossmann** [comment]
Fixed by #77

**Comment by apertureless** [comment]
@timgrossmann Maybe because of wrong locale?

**Comment by timgrossmann** [comment]
@apertureless  Yes, but it can't set it. 
Or more like, it set's it but still throws the same error
