### ISSUE TITLE
Question: Auto kill previous run when the new started

### ISSUE THREAD

**Issue by nickbullll** [InstaPy/InstaPy#180]
If I'm running my script on ubuntu server every 4 hours with cronjob (`0 */4 * * *`)
how to kill all processes caused by the script (like `chrome`) when the new script starts running ?

**Comment by timgrossmann** [comment]
@abraztsov The script will, if run correctly, terminate all the used processes once it's done...

**Comment by nickbullll** [comment]
@timgrossmann `> once it's done...`
Yes, but if it's not done and new script starts running ?

PS: Tested on local machine with (* * * * *) cronjob and it's seems like chrome open new window every minute without ending old process (all ok, this is expected).

**Comment by timgrossmann** [comment]
@abraztsov Ahh ok, why would you want this? You'll definitely get banned if the script runs all day...
You're right, with every start a new chrome tab will be opened.

I'm not really sure what you want to do, but I run my script via cron every 4 hours, too.
But by then, the old run stopped like 3 hours ago.

**Comment by nickbullll** [comment]
@timgrossmann It depends of how much script logic you have (tags, comments percent, etc..)

Because if a new process starts on a weak machine, CPU will take off to the skies and the server will fall.

But it's just an interest in optimizing the script.
It'll be profitable for your project if someone says how to solve it

**Comment by timgrossmann** [comment]
@abraztsov Yes you're right.
But I don't really think with the current tools involved (Selenium, Chrome) you won't get that done.
And I'm not really sure if I want that for this project. This shouldn't turn into something everyone just takes and builds a paid service out of it...

**Comment by nickbullll** [comment]
@timgrossmann Ok. I closed it
