### ISSUE TITLE
Sorry, Record Activity is not working on Windows. We're working to fix this soon!

### ISSUE THREAD

**Issue by mdavis184** [InstaPy/InstaPy#1800]
Hi, I'm having some trouble fixing the problem of "Record Activity is not working on Windows",
I tried updating python as well as downloading las instapy folder, but still no fix.
the thing is that the script works ok with following & like but once I do add unfollowing it jams up
p.s. I removed session. unfollow but still see the "Record Activity is not working on Windows"..

My script(with unfollow): 
session.unfollow_users(amount=500,
                           onlyInstapyFollowed = True,
                           onlyInstapyMethod = 'FIFO',
                           onlyNotFollowMe=False,
                           sleep_delay=600,
                           unfollow_after=48*60*60)
cmd: 
DevTools listening on ws://127.0.0.1:12044/devtools/browser/c1edccbb-bfc3-47af-9b94-ae65a6e918ab
INFO [2018-04-03 09:57:28] [*****]  Session started - 2018-04-03 09:57:28
WARNING [2018-04-03 09:57:28] [******]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
Cookie file not found, creating cookie...
INFO [2018-04-03 09:57:41] [******]  Logged in successfully!
....

**Comment by MrBeardedGuy** [comment]
See if https://github.com/timgrossmann/InstaPy/issues/1130 might help
