### ISSUE TITLE
Follow Someone else's follower doesn't work anymore.

### ISSUE THREAD

**Issue by groundo** [InstaPy/InstaPy#1802]
## Expected Behavior
It should follow someone else followers
## Current Behavior
It shows it follows the following 10 users however when the user is checked manually it is still not followed.

INFO [2018-04-03 18:46:01] [xxxxxx]  Logged in successfully!
[2392:9500:0403/184602.737:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
INFO [2018-04-03 18:46:47] [xxxxxx]  --> Ongoing follow 1, now following: b'xyz'
INFO [2018-04-03 18:47:03] [xxxxxx]  --> Ongoing follow 2, now following: b'xyz1'
INFO [2018-04-03 18:47:14] [xxxxxx]  --> Ongoing follow 3, now following: b' xyz2’
INFO [2018-04-03 18:47:29] [xxxxxx]  --> Ongoing follow 4, now following: b' xyz3'
INFO [2018-04-03 18:47:45] [xxxxxx]  --> Ongoing follow 5, now following: b' xyz4'
INFO [2018-04-03 18:48:01] [xxxxxx]  --> Ongoing follow 6, now following: b' xyz5'
INFO [2018-04-03 18:48:09] [xxxxxx]  --> Ongoing follow 7, now following: b' xyz6'
INFO [2018-04-03 18:48:27] [xxxxxx]  --> Ongoing follow 8, now following: b' xyz7’
INFO [2018-04-03 18:48:38] [xxxxxx]  --> Ongoing follow 9, now following: b' xyz8'
INFO [2018-04-03 18:48:52] [xxxxxx]  --> Ongoing follow 10, now following: b' xyz9’
INFO [2018-04-03 18:49:08] [xxxxxx]  --> Total followNum reached: 10
INFO [2018-04-03 18:49:08] [xxxxxx]  --> Total people followed : 10

## Possible Solution (optional)
??

**Comment by CharlesCCC** [comment]
make sure you account didn't get "soft-banned".  `soft-banned` means your account have followed/liked exceed amount that Instagram.com preventing you from following more people.  You can test this by, manually login to your account and click following/like on others account.

**Comment by groundo** [comment]
I can follow and unfollow manually from my phone.

**Comment by CharlesCCC** [comment]
@groundo  are you able to do it in your computer ? the computer that running InstaPy

**Comment by fabriciogava** [comment]
I'm having the exact same issue.
I used to follow about 800 users a day using follow_user_followers function and get about 100~120 new follower a day. Now I'm getting about 20 new followers a day.
I checked the logs and everything seems fine, just like @groundo 's. But those profiles listed in the logs are not actually being followed.
I'm having this problem for about 4 days, exactly when @groundo opened this thread.

InstaPy is updated with last version and I can manually follow, unfollow and like on Instagram app.

Please tell me how can I be useful to help debug this.

**Comment by CharlesCCC** [comment]
@groundo @rediv you guys are got soft-banned... reduce the amount of likes/following/unfollowing

oh just totally stop for couple days.
