### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2

### ISSUE THREAD

**Issue by riccardorighettiphoto** [InstaPy/InstaPy#1806]
Hello, this is the error I am getting almost every time I run InstaPy (VPS Centos 7, python 2.7):

`
File "/home/my_username/InstaPy/instapy/instapy.py", line 987, in like_by_tags
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 48: ordinal not in range(128)
`
Any idea?

**Comment by MrBeardedGuy** [comment]
Make sure you've pulled the latest changes. If it doesn't work, check https://github.com/timgrossmann/InstaPy/issues/1365

**Comment by riccardorighettiphoto** [comment]
?
What?
