### ISSUE TITLE
Bot keeps crashing at random intervals "full log"

### ISSUE THREAD

**Issue by supmag** [InstaPy/InstaPy#1807]
So it was working fine around 3 weeks ago. I pulled the newest version to the current version and I keep getting this error over and over...sometimes It will run for 3 hours sometimes 10 minutes...

InstaPy Process
Error: INFO [2018-04-04 19:39:25] [********] Session started - 2018-04-04 19:39:25
 WARNING [2018-04-04 19:39:25] [********] Sorry, Record Activity is not working on Windows. 

I read the log and basically it says 11/11 and once its done with that post the bot stops. I set it to 50 in the instapy gui

**Comment by MrBeardedGuy** [comment]
Try taking a look here for the fix https://github.com/timgrossmann/InstaPy/issues/1130

**Comment by ShiftingKill** [comment]
Same situation here I have no idea why mine is crashing and I can't sit around long enough to find it crash. Logs are healthy just randomly ends...

**Comment by bhuiyanmobasshir94** [comment]
same problem need solution thanks
