### ISSUE TITLE
[Question] Is it possible to run just some sessions some under a proxy? 

### ISSUE THREAD

**Issue by MrBeardedGuy** [InstaPy/InstaPy#1810]
## Question
The community recently introduced a way to run InstaPy with a proxy (https://github.com/timgrossmann/InstaPy/pull/1531/). I was wondering if it's possible to set up 2 InstaPy sessions to run with proxy and 1 with the regular machine IP. 

Maybe tweaking `multi-account.py`. Not sure though if it's feasible.

**Comment by CharlesCCC** [comment]
how about make a copy of InstaPy folder ?

**Comment by MrBeardedGuy** [comment]
I was thinking about a multi-threaded approach but that might work as well... I'll need to test it out to see if it drains memory.

**Comment by CharlesCCC** [comment]
@MrBeardedGuy before there is multiple accounts support, i had 2 accounts running without problem. memory is not an issue at all.

**Comment by Areahints** [comment]
If I duplicate my **instapy folder** and set another account on it. Won't I have issues with Instagram? Multi-account.py gives me error and I only changed the usernames and passwords

**Comment by leoch20** [comment]
@Areahints Were you able to solve your issue? I think I am having the same issue, some help would be nice
