### ISSUE TITLE
[erro] Assets/chromedrive I am using the digital ocean server

### ISSUE THREAD

**Issue by thonyhenrique** [InstaPy/InstaPy#1811]
Hello, I'm Brazilian and I do not understand anything about python, without having to get there, and there is no tutorial on youtube, but I ended up getting the error. ask to install the man but it is already in the installed folder.

Someone with the same error and could you help me please?

![unnamed](https://user-images.githubusercontent.com/37970224/38423313-f4630498-3983-11e8-86ce-15402de70846.png)

I am using the digital ocean server

**Comment by CharlesCCC** [comment]
can you please provide what you have done first ? like what steps you have finished in set-up ?

**Comment by thonyhenrique** [comment]
Well first, I made the installation following the GITHUB manual and the video provided.

First mistake that appeared was.

![unnamed 1](https://user-images.githubusercontent.com/37970224/38443059-bef9601c-39c0-11e8-9350-0a778540c16f.png)


After downloading the chrome driver and zip the file, I executed quickstarta.py, gave the second error.

![unnamed 2](https://user-images.githubusercontent.com/37970224/38443161-154400c6-39c1-11e8-8204-c4e34b259dea.png)

Ai seeing the topic I saw somewhere everything that has module + name do pip install
installed everything that could be, until arriving at the clarifor also installed seeing the tutorial after I installed this appeared this error.

Only file I edited was quickstart.py, 
Where is red

![image](https://user-images.githubusercontent.com/37970224/38443460-1a3bb9d8-39c2-11e8-92fb-f30f16b72ea4.png)

Desculpe o texto foi traduzido no google e não entendo nada em ingles. ><
Sorry, the text has been translated into Google and I do not understand anything in English. > <

Thank you very much and I look forward to your help.

**Comment by CharlesCCC** [comment]
uhh, okay, i saw you have manually did pip install. but why don't you try use 
`python setup.py install' which also clearly instructed in the main page.

**Comment by thonyhenrique** [comment]
@CharlesCCC really had not installed this way everything in the hand, now install, but even so appears the same error as the chormedrive and it is already in the folder assets, unzip.

delete and do the whole process again only chrome after qhe already installed this way?
