### ISSUE TITLE
Problem: Cannot read property 'entry_data' of undefined

### ISSUE THREAD

**Issue by hestuppfodarn** [InstaPy/InstaPy#1815]
## Expected Behavior

To work as usual, have been using it for 9 months,

## Current Behavior

Login works,
Then error message ending with this:

File "/Users/xx/InstaPy/venv/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Cannot read property 'entry_data' of undefined
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.13.3 x86_64)

## Possible Solution (optional)

Something with the lastest Chrome Version?
I have downloaded the lasted Chromedriver,

## InstaPy configuration

Mac OS X 10.13.3 x86_64
chrome=65.0.3325.181
chromedriver=2.37.544337

**Comment by MrBeardedGuy** [comment]
This issue has been highlighted here https://github.com/timgrossmann/InstaPy/issues/1338 and it should have already been fixed in this PR https://github.com/timgrossmann/InstaPy/pull/1673. Have you tried pulling the latest master?
