### ISSUE TITLE
Session not changed multiple users

### ISSUE THREAD

**Issue by dogukanaras** [InstaPy/InstaPy#1818]
Hello there,

I have tested for multiple users as follows, but the user does not change. Only the labels are changing and continuing to work.

Is there a solution to this?
try:   
    session =  InstaPy(username='username1', password='******',multi_logs=True,headless_browser=True,bypass_suspicious_attempt=True)
    session.login()
    session.like_by_tags(['love'], amount=1, media='Photo')
finally:
    session.end()

try:
    session =  InstaPy(username='username2', password='******',multi_logs=True,headless_browser=True,bypass_suspicious_attempt=True)
    session.login()
    session.like_by_tags(['bike'], amount=1, media='Photo')
finally:
    session.end()

INFO [2018-04-08 01:25:42] [username1]  Session started - 2018-04-08 01:25:42
INFO [2018-04-08 01:26:12] [username1]  Logged in successfully!
**INFO [2018-04-08 01:26:13] [username1]  Tag [1/1]
INFO [2018-04-08 01:26:13] [username1]  --> love**
INFO [2018-04-08 01:26:49] [username1]  [1/1]
INFO [2018-04-08 01:26:49] [username1]  https://www.instagram.com/p/BhSTLWyFAQy/?tagged=love
INFO [2018-04-08 01:26:52] [username1]  Image from: gianerojass
INFO [2018-04-08 01:26:59] [username1]  Number of Followers: 633
INFO [2018-04-08 01:26:59] [username1]  Link: https://www.instagram.com/p/BhSTLWyFAQy/?tagged=love
INFO [2018-04-08 01:26:59] [username1]  Description: Mi ❤ peludo .
INFO [2018-04-08 01:27:01] [username1]  --> Image Liked!
INFO [2018-04-08 01:27:03] [username1]  --> Not commented
INFO [2018-04-08 01:27:04] [username1]  --> Not following
INFO [2018-04-08 01:27:06] [username1]  Liked: 1
INFO [2018-04-08 01:27:06] [username1]  Already Liked: 0
INFO [2018-04-08 01:27:06] [username1]  Inappropriate: 0
INFO [2018-04-08 01:27:06] [username1]  Commented: 0
INFO [2018-04-08 01:27:06] [username1]  Followed: 0
INFO [2018-04-08 01:27:06] [username1]  Session ended - 2018-04-08 01:27:06
INFO [2018-04-08 01:27:06] [username1]  --------------------

INFO [2018-04-08 01:27:07] [username1]  Session started - 2018-04-08 01:27:07
INFO [2018-04-08 01:27:36] [username1]  Logged in successfully!
**INFO [2018-04-08 01:27:38] [username1]  Tag [1/1]
INFO [2018-04-08 01:27:38] [username1]  --> bike**
.
.
.
.

**Comment by MrBeardedGuy** [comment]
If you're running multiple accounts there's a file called [multi_account.py](https://github.com/timgrossmann/InstaPy/blob/master/examples/multi-account.py) you should use this one instead of replicating your quickstart code.
