### ISSUE TITLE
Session not defined due to expected chromedriver version not available for Raspberry Pi

### ISSUE THREAD

**Issue by mikestan** [InstaPy/InstaPy#1820]
## Expected Behavior
InstaPy running on Raspberry Pi starts up.

## Current Behavior
Error occurs upon startup:
```
Traceback (most recent call last):
  File "quickstart-unfollow_TLFP.py", line 54, in <module>
    session.end()
NameError: name 'session' is not defined
```

## Possible Solution (optional)
Need updated chromedriver for Raspberry Pi (2.33 is the latest available for Raspberry Pi yet Google has released 2.37 and InstaPi wants 2.36+)

Workaround: edit ~/InstaPy/instapy/settings.py and change chromedriver_min_version = 2.33

Updated Raspberian, dependencies, Chromium, and InstaPy and still needed to edit settings file.

**Comment by DemOnJR** [comment]
https://github.com/timgrossmann/InstaPy/issues/1816#issuecomment-379749811
