### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by holymolly** [InstaPy/InstaPy#1826]
Hello,
I follow the guide for windows to install except gui. What am i missing to start?
Python 3.6.5

  File "quickstart.py", line 28
    session.set_do_follow(enabled=True,percentage=10,times=1)
          ^
SyntaxError: invalid syntax

**Comment by holymolly** [comment]
i fix it anyway thanks.

**Comment by holymolly** [comment]
I get mad. I install every module and quickstart.py was start then i editing quickstart.py for followers, i saw the first error issue.

**Comment by tirkarthi** [comment]
Can you please post your quickstart.py as a gist to look at it?

**Comment by holymolly** [comment]
i fix this now works perfectly but some times get this "ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED" but it is continue to work. the unfollow doesn't work i think.

is the unfollow line correct? 

`session.set_upper_follower_count(limit=2500)

session.set_do_follow(enabled=True, percentage=10, times=1) 

session.follow_by_tags(['followforfollow','follow4follow','followback','followme'],amount=10)

session.unfollow_users(amount=10,onlyInstapyFollowed=True,onlyInstapyMethod='FIFO',sleep_delay=60)`

and now i get this it was end the session

Traceback (most recent call last):
  File "quickstart.py", line 28, in <module>
    session.follow_by_tags(['followforfollow','follow4follow','followback','followme'],amount=10)
  File "C:\Users\Desktop\InstaPy-master\instapy\instapy.py", line 1883, in follow_by_tags
    self.logger)
  File "C:\Users\Desktop\InstaPy-master\instapy\like_util.py", line 564, in check_link
    '" in "'.join([iffy, quashed]))
TypeError: sequence item 1: expected str instance, bytes found
