### ISSUE TITLE
[HELP] Newbie help

### ISSUE THREAD

**Issue by jdrussell78** [InstaPy/InstaPy#183]
Hi,

I was wondering if someone can help, newbie to most of this including git etc.

My quickstart.py file looks like this

from instapy import InstaPy
import os

# Write your automation here
# Stuck ? Look at the github page or the examples in the examples folder

# dont_like = ['food', 'girl', 'hot']
# ignore_words = ['pizza']
# friend_list = ['friend1', 'friend2', 'friend3']

# If you want to enter your Instagram Credentials directly just enter
# username=<your-username-here> and password=<your-password> into InstaPy
# e.g like so InstaPy(username="instagram", password="test1234")

session = InstaPy(username='xxxx', password='xxxx')
session.login()
session.set_upper_follower_count(limit = 2500) 
session.set_do_comment(True, percentage=25) 
session.set_comments(['Lovely photo!', 'Awesome!', 'Nice!'], media='Photo') 
session.set_comments(['Great Video!'], media='Video')
session.set_dont_include(friend_list) 
session.set_dont_like(['food', 'girl', 'hot']) 
session.set_ignore_if_contains(['pizza'])
session.set_use_clarifai(enabled=True, secret='xxxx', proj_id='xxxx)
session.like_by_tags(['xxxx', '#xxxx', '#xxxx', '#xxxx', '#xxxx'], amount=100) 
session.end()

It is in the instapy directory where the other *.py files are located.

When I run python quickstart.py I get:

Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/jusername/instapy/InstaPy-master/instapy/instapy.py", line 10, in <module>
    from .clarifai_util import check_image
ValueError: Attempted relative import in non-package

- Is the quickstart.py file in the InstaPy directory? (Like you cloned it)
Yes it is in the instapy directory
- Did you run: pip install . (in the terminal in the InstaPy directory) ?
If I run this in the instapy directory I get "Directory '.' is not installable. File 'setup.py' not found."
- Did you download the right chromedriver for your system and put it in the /assets folder?
I downloaded the mac64 version from here - https://chromedriver.storage.googleapis.com/index.html?path=2.29/ I am on an apple MacBook pro
- Are you using python3.5 quickstart.py to start it?
No if I run that I get "-bash: python3.5: command not found" and if i run "python2.7 quickstart.py"

I get 

Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/jonathanrussell/instapy/InstaPy-master/instapy/instapy.py", line 10, in <module>
    from .clarifai_util import check_image
ValueError: Attempted relative import in non-package

I have Python 2.7.10 installed.

Thanks,
Jon

**Comment by timgrossmann** [comment]
@jdrussell78 

Please install python3. https://www.python.org/downloads/

Please take a look at the folder structure in this repository. Don't move the quickstart file anywhere, please!

so this should look like this:
```bash
InstaPy/
   - assets/
   - docs/
   .
   .
   .
   - instapy/
      - instapy.py
      .
      .
      .
   - quickstart.py
```

Make sure that quickstart.py is in the root directory, not where the other `.py` files are

**Comment by jdrussell78** [comment]
Hi Tim,

Thanks.

Ok the file structure is as follows (see uploaded image below:

<img width="253" alt="screen shot 2017-04-22 at 18 44 33" src="https://cloud.githubusercontent.com/assets/25438393/25306761/cfc5d012-278b-11e7-9fdf-35471d785593.png">


I have downloaded python 3.6.1 for mac os.

I then ran

python3.6 quickstart.py

and got 

Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/user/instapy/InstaPy-master/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/Users/user/instapy/InstaPy-master/instapy/instapy.py", line 5, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'

**Comment by jdrussell78** [comment]
after this i ran

pip install --user pyvirtualdisplay

and got


Requirement already satisfied: pyvirtualdisplay in /Library/Python/2.7/site-packages/PyVirtualDisplay-0.2.1-py2.7.egg
Requirement already satisfied: EasyProcess in /Library/Python/2.7/site-packages/EasyProcess-0.2.3-py2.7.egg (from pyvirtualdisplay)

**Comment by timgrossmann** [comment]
@jdrussell78 pip3.{your version} e.g. 3.5 install ;)

So for you: 

```
pip3.6 install pyvirtualdisplay
```

**Comment by jdrussell78** [comment]
ok, getting there.... i then had a problem with selenium, don't think i had hat installed

i ran

python3.6 quickstart.py

and got

Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/jonathanrussell/instapy/InstaPy-master/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/Users/jonathanrussell/instapy/InstaPy-master/instapy/instapy.py", line 6, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

so ran

sudo easy_install selenium

which resulted in...

Password:
Searching for selenium
Best match: selenium 2.53.6
Processing selenium-2.53.6-py2.7.egg
selenium 2.53.6 is already the active version in easy-install.pth

Using /Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg
Processing dependencies for selenium
Finished processing dependencies for selenium

and then retried

python3.6 quickstart.py

and got:

Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/jonathanrussell/instapy/InstaPy-master/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/Users/jonathanrussell/instapy/InstaPy-master/instapy/instapy.py", line 6, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

thanks for helping with this Tim

**Comment by timgrossmann** [comment]
did you do pip install . ?

You just need to install it with pip.. best would be pip3.6 install selenium

**Comment by jdrussell78** [comment]
ok I have done that, and then did similar for clarifai too

Oooh oooh

Logged in successfully!

Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    session.set_dont_include(friend_list) 
NameError: name 'friend_list' is not defined

and then i commented out

session.set_dont_include(friend_list) 

what is the syntax for the friend_list?

This is great thanks !!

**Comment by jdrussell78** [comment]
Looks like this is working now. Thanks for all your help Tim. Can you tell me how it handles the screen saver ? I turned it off as it seemed to interrupt it ?

**Comment by timgrossmann** [comment]
@jdrussell78 The syntax for the friend_list should be alright...

I don't really know how he handles it, I'm solely running it on a server.
It should be better to be turned off, but I think it could work with the screensaver on.

**Comment by jdrussell78** [comment]
ok, and this is the last question (for now) quite a lot of the images are not liked and the script says "Image not liked: Inappropriate" why is that? where is that controlled in the script?

**Comment by timgrossmann** [comment]
I'm really sure, that this has to do with these lines...

```python
session.set_dont_like(['food', 'girl', 'hot'])
session.set_use_clarifai(enabled=True, secret='xxxx', proj_id='xxxx)
```

dont_like searches the image test for given words. If one of the words is included, it won't like the picture.

If using clarifai, you also have to use `.clarifai_check_img_for(['some_tag'])\`. Because I didn't test what happens if you  specify no check at all.


e.g. here is my clarifai setup:
```python
.set_use_clarifai(enabled=True)\
.clarifai_check_img_for(['nsfw'])\
.clarifai_check_img_for(['food', 'lunch', 'dinner'], comment=True, comments=foodComments)\
.clarifai_check_img_for(['lake', 'landscape', 'mountain'], comment=True, comments=natureComments)\
```

**Comment by jdrussell78** [comment]
thanks Tim, where do you define foodcomments and naturecomments?

**Comment by jdrussell78** [comment]
can you explain clarifai ? 
Ok, I get what clarifai does, but do I have to use it ?

My clarifai setting is

session.clarifai_check_img_for(['tree', 'landscape', 'drone'], comment=True, comments=['Awesome photo!', 'Lovely shot!!!'])

Does this mean, it will only comment if all three of those checks are passed? (tree, landscape, drone?)

What about the part of the script where the comments are set:

session.set_do_comment(True, percentage=25)
session.set_comments(['Lovely photo!', 'Awesome!', 'Nice!'], media='Photo')
session.set_comments(['Great Video!'], media='Video')

Does clarifai override this?

**Comment by timgrossmann** [comment]
@jdrussell78 Absolutely not..
It's just another layer of "security" to make sure people are not trolling with their description of the image...

e.g. I've seen people using "#vegan" a lot and actually posting images of cut off pig heads  or something like that.
In such a case you can simply enable clarifai and let it check for "blood" or something like that and make sure there really is no cut off pig head in the image before commenting and following that profile.

**Comment by maverjk** [comment]
Personally I was thinking the right same thing, would be really useful to have a kind of customized log for each account (of course if someone is thinking to use it with more than one account).

One more thing that I'm looking at is a kind of list or function to save all following accounts before to start any session so to unfollow only new following accounts. Is there anything like that? How to accomplish that?

**Comment by ghost** [comment]
Didn't want to start a new issue and I'm only at beginner level of programming could some let me know if below is correct for clarifai?

InstaPy(username='xxxx', password='xxxx.')\
	.login()\
	.set_dont_like(tag_list)\
	.set_dont_include(friendList)\
	.set_ignore_if_contains(ignore_list)\
	.set_do_comment(enabled=True, percentage=5)\
	 .set_do_follow(enabled=True, percentage=10, times=1)\
        .set_comments(comments=normalComments)\
	.set_use_clarifai(enabled=True, secret='client secret', proj_id='client id?')\
	    .clarifai_check_img_for(['nsfw'])\
	    .clarifai_check_img_for(['food', 'lunch', 'dinner'], comment=True, comments=foodComments)\
	    .clarifai_check_img_for(['lake', 'landscape', 'mountain'], comment=True, comments=natureComments)\
	    .like_by_tags((like_tag_list), amount=tag1)\
	    .like_by_tags((like_tag_list, 1), amount=tag2)\
	    .like_by_tags((like_tag_list, 1), amount=tag3)\
	    .end()

**Comment by Javampas** [comment]
aah, 
can I get help with the selenium thing, I'm not very familiar with the python console and I'm on PC
the GUI says that something is wrong with the quickstart file, I opened it in the editor and it says that a syntax error is in "instapy.py" : "pyvitualdesplay" does not exist.
Second error is in "__init__.py" : "from .instapy import InstaPy"
my python version is: 3.4 (also have 2.7 installed aswell)
