### ISSUE TITLE
UnicodeDecodeError: ASCII code can't decode byte...

### ISSUE THREAD

**Issue by riccardorighettiphoto** [InstaPy/InstaPy#1830]
Continuously getting this error. Any idea?
CentOS 7.x, Python 2.7

`Traceback (most recent call last):
  File "./quickstart.py", line 39, in <module>
    session.like_by_tags(['tag1', 'tag2', 'tag3', 'tag4'], amount=100)
  File "/home/my_name/InstaPy/instapy/instapy.py", line 987, in like_by_tags
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 49: ordinal not in range(128)
`

**Comment by axlright** [comment]
I just got this same error. Seems to have barfed out on an emoji in an image description.

https://www.instagram.com/p/BkRhLVbFgWF/

```
Traceback (most recent call last):
  File "user-xxx-hashtag-architecturelovers.py", line 63, in <module>
    session.like_by_tags(['#architecturelovers'], amount=636)
  File "/Users/my_name/Documents/Code/InstaPy/instapy/instapy.py", line 1315, in like_by_tags
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 53: ordinal not in range(128)
```

**Comment by timgrossmann** [comment]
The issue is bound to your terminal output and the standard decoding that is set (seems like Ascii). 
If you change the decoding, it should work.
