### ISSUE TITLE
Unfollow leads to a not authorized page

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1831]
## Expected Behavior
When running the unfollow function by itself, it should go through and unfollow people on my list with the settings I have chosen.
## Current Behavior
What is currently happening is it leads to unauthorized page and then the application crashes since it doesn't know how to continue.
Any help is appreciated.

I am able to run the script just fine as soon as I remove the unfollow function.
## Possible Solution (optional)
Is the method we are currently using no longer working to unfollow users?
## InstaPy configuration
Latest instapy build as of today.

**Comment by omidedipidizi** [comment]
Yea having same issue !!!!

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/3760127/38653494-0b0668b2-3dd9-11e8-8ee9-8f61dd28b144.png)

Here's the photo for reference. 

```
    session.unfollow_users(amount=1, onlyInstapyFollowed=False, onlyNotFollowMe=True, onlyInstapyMethod='FIFO',
                           sleep_delay=60)
```

Here's my code snippet.

**Comment by botpadawan** [comment]
Got also issue using headless browser
![cannotunfollow](https://user-images.githubusercontent.com/30112936/38653785-ed680868-3e3e-11e8-89a5-d5ad7a3d41fa.png)

**Comment by sionking** [comment]
instagram blocked access to ?__a=1 but it easyly can be scarped from page source
this will return the JSON in JS

This is only happen when you want to capture all of your followers to a list, bed idea as it is to fake some url requests that is not how human behave! 

Currently: change onlyInstapyFollowed to True for now.

**Comment by sionking** [comment]
this will return the JSON in JS

**Comment by sionking** [comment]
We use it to get the user id (bad usage) since it can be take from page:

change:
```
        # unfollow only not follow me
        try:
            browser.get(
                'https://www.instagram.com/' + username + '/?__a=1')
            pre = browser.find_element_by_tag_name("pre").text
            user_data = json.loads(pre)['graphql']['user']
        except BaseException as e:
            print("unable to get user information\n", str(e))

        graphql_endpoint = 'https://www.instagram.com/graphql/query/'
        graphql_followers = (
            graphql_endpoint + '?query_id=17851374694183129')
        graphql_following = (
            graphql_endpoint + '?query_id=17874545323001329')

        all_followers = []
        all_following = []

        variables = {}
        variables['id'] = user_data['id']
        variables['first'] = 100

```
to:
```
        # unfollow only not follow me
        user_data = {}

        graphql_endpoint = 'https://www.instagram.com/graphql/query/'
        graphql_followers = (
            graphql_endpoint + '?query_id=17851374694183129')
        graphql_following = (
            graphql_endpoint + '?query_id=17874545323001329')

        all_followers = []
        all_following = []

        variables = {}
        user_data['id'] = browser.execute_script(
            "return window._sharedData.entry_data.ProfilePage[0]."
            "graphql.user.id")
        variables['id'] = user_data['id']
        variables['first'] = 100

```


Tested and working.

**Comment by visualheroes** [comment]
Something changed.
I have the "ooops, something went wrong.." message in chrome while using *onlyinstapyfollowed*, nothing is unfollowed.

`session.unfollow_users(amount=loop_dquota_unfollow, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=600, unfollow_after=72*60*60)`

It's on and off since this morning.
Edit: latest everything /instapy-master/chrome/selenium

**Comment by omidedipidizi** [comment]
@sionking tanks buddy !  it work

**Comment by ghost** [comment]
Fixed by latest commits
