### ISSUE TITLE
Hopeless Noob Can't Set Up InstaPy :(

### ISSUE THREAD

**Issue by f43154** [InstaPy/InstaPy#1832]
## Expected Behavior
Currently stuck on 

_3. Simple setup:
Download (or clone - open in GitHub Desktop BUTTON) the repository.
Go to the scripts folder.
Right click on "windows.ps1" and select "Run as administrator"._

I was expecting all text to remain white, saying things like "successfully installed".
## Current Behavior
![error installing gui tool](https://user-images.githubusercontent.com/16504760/38653527-370889a4-3dd9-11e8-96c4-d06908b9f79c.PNG)
## Possible Solution (optional)
I have no idea T_T

**Comment by ghost** [comment]
dont know if this is helpful but when you installed python 3 - make sure you have that path option selected on the bottom of the install.

![image](https://user-images.githubusercontent.com/3760127/38653898-f2383ee4-3dda-11e8-8425-fadc5a1dec63.png)
at least this way you dont have to navigate to the python folder to do anything, you can do it right from instapy.

also helpful for  troubleshooting: https://dev.to/el_joft/installing-pip-on-windows

**Comment by f43154** [comment]
@halalfood that didn't seem to help but THANK YOU! :)

**Comment by bhuiyanmobasshir94** [comment]
Can you guys help me with quickstart.py configuration
