### ISSUE TITLE
Unfollow issue

### ISSUE THREAD

**Issue by cormo1990** [InstaPy/InstaPy#1837]
The InstaPy crashed during the unfollowing action.

below the traceback...someone can help?

![unfollow_issue](https://user-images.githubusercontent.com/36590321/38677291-20184560-3e5e-11e8-9ae0-5c68683d9d81.png)

**Comment by sionking** [comment]
I PR fix

**Comment by cormo1990** [comment]
@sionking I Don't understand

**Comment by nafferro** [comment]
it's ok on mac os, but can't unfollow with ubuntu

**Comment by condomfighters** [comment]
mine crashed after unfollowing +/-10 profiles and crashed.
i fixed it by doing this:
1. update chromedriver
2. pip uninstall -r requirements.txt
3. pip install -r requirements.txt

**Comment by nafferro** [comment]
On Mac OS:
('unable to get user information\n', 'Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}\n  (Session info: headless chrome=65.0.3325.181)\n  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.13.4 x86_64)\n')
On Ubuntu:
unable to get user information
 Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.4.0-1054-aws x86_64)
