### ISSUE TITLE
Script terminates sessions before regular ending

### ISSUE THREAD

**Issue by marudon** [InstaPy/InstaPy#184]
I'm running instaPy on Python 3.6.1 and an Win7 PC

After starting the script I get at once the error message:

--> b' photoart'
Load button not found, working with current images!
Too few images, aborting

Session ended

Hardcopy of the chrom browser just before the session cancel:
![image](https://cloud.githubusercontent.com/assets/27830829/25306723/7846762c-2793-11e7-807f-268869d1d5d7.png)

**Comment by littleswany** [comment]
@marudonart Would you be able to post your script that you are using?

But it looks as if the hashtag you are using has no images.

**Comment by timgrossmann** [comment]
@marudonart the b'' in front of the string is probably the problem... Could you test it again and copy the URL when the first tag is searched? This will probably be an invalid URL

**Comment by marudon** [comment]
I found the error reason!
I had a blank within the quotes **' photoart'**  
After removing it to **'photoart'** the script works 

@littleswany: 
you are right. if the hashtag has no images the script aborts. 

@timgrossmann: 
is it by intention that the script terminates if a hashtag has no images? 
I think it would be better to log this and go on working :-)

**Comment by timgrossmann** [comment]
@marudon Yes, you're right... This is not intended but a bug
