### ISSUE TITLE
Cannot read property 'followed_by'

### ISSUE THREAD

**Issue by nickbota** [InstaPy/InstaPy#1840]
## Current Behavior
It used to work fine on both my desktop and my laptop and now it shows this error:
"Cannot read property 'followed_by' of undefined"  
![issue](https://user-images.githubusercontent.com/30750879/38705284-bc247f66-3eb1-11e8-876f-254288f0f1ff.png)

The quickstart.py hasn't been modified so that's not the cause considering it's been working properly for almost a month.

Any idea how to fix it?

## Possible Solution (optional)
I've tried deleting it +Python and installing it again, nothing changed.

## InstaPy configuration

**Comment by nickbota** [comment]
Nevermind, I deleted all the files and installed them again and it works perfectly fine now. Sorry for the pointless issue.

**Comment by timgrossmann** [comment]
@nickbota Glad it is resolved now.
