### ISSUE TITLE
Huge disk consumption on Ubuntu after crash

### ISSUE THREAD

**Issue by sq5rix** [InstaPy/InstaPy#1841]
Hi!
I have very strange behavior - when InstaPy crashes it hogs the disk space, hundreds of Gigabytes. I am unable to find the huge space, use of du shows normal sizes, while df -h shows 90% of used disk space. 
/var/log is normal, no huge files. 
Please help

**Comment by GitNees** [comment]
Check your memory when it happens. There is a bug where noone really followed up upon, and it eats memory and writes infit to swapfile. It ate "500GB" but was not written peranently, perhaps your swapfile is set dynamic and keeps enlarging till disk full and then everything goes BOOM!

**Comment by sq5rix** [comment]
Thanks!!  

I found out that:

kern.log and syslog in /var/log grow a lot and/or
some unallocated space is created, which fortunately disappears after reboot, I assume that chrome process writes a log but cannot close the file
I simply delete huge logs and if there is still some unusual space, I reboot. I must find some tool to reclaim this space without reboot, I will post it here. 
------------------------------
I found out that it is better to use truncate instead of rm 
------------------------------
I found out that the command 
lsof -nP | grep '(deleted)'
shows many files which hog my disk 
The example file is
VideoChil 28557 28583              tom   40u      REG               0,24        40         42 /dev/shm/org.chromium.YOPwVD (deleted)
 There is a million and one of those files !! 
There is similar command 
lsof +L1 
which yields the same result 
it seems thet rebooting will release those files, who are simple orphans of killed processes**

**Comment by sq5rix** [comment]
Thanks!!  

I found out that two files - kern.log and syslog in /var/log grow a lot and/or
some unallocated space is created, which fortunately disappears after reboot, I assume that chrome process writes a log but cannot close the file
I simply delete huge logs and if there is still some unusual space, I reboot. I must find some tool to reclaim this space without reboot, I will post it here. 
------------------------------
I found out that it is better to use truncate instead of rm 
------------------------------
I found out that the command 
lsof -nP | grep '(deleted)'
shows many files which hog my disk 
The example file is
VideoChil 28557 28583              tom   40u      REG               0,24        40         42 /dev/shm/org.chromium.YOPwVD (deleted)
 There is a million and one of those files !! 
There is similar command 
lsof +L1 
which yields the same result 
it seems thet rebooting will release those files, who are simple orphans of killed processes**

**Comment by sq5rix** [comment]
Thanks!!  
I found out that kern.log and syslog in /var/log grow a lot and/or
some unallocated space is created, which fortunately disappears after reboot, I assume that chrome process writes a log but cannot close the file
I simply delete huge logs and if there is still some unusual space, I reboot. I must find some tool to reclaim this space without reboot, I will post it here. 
------------------------------
I found out that it is better to use truncate instead of rm 
------------------------------
I found out that the command 
lsof -nP | grep '(deleted)'
shows many files which hog my disk 
The example file is
VideoChil 28557 28583              tom   40u      REG               0,24        40         42 /dev/shm/org.chromium.YOPwVD (deleted)
 There is a million and one of those files !! 
There is similar command 
lsof +L1 
which yields the same result 
it seems thet rebooting will release those files, who are simple orphans of killed processes**

**Comment by sq5rix** [comment]
Thanks!!  
I found out that kern.log and syslog in //var//log grow a lot and//or
some unallocated space is created, which fortunately disappears after reboot, I assume that chrome process writes a log but cannot close the file
I simply delete huge logs and if there is still some unusual space, I reboot. I must find some tool to reclaim this space without reboot, I will post it here. 
------------------------------
I found out that it is better to use truncate instead of rm 
------------------------------
I found out that the command 
lsof -nP | grep '(deleted)'
shows many files which hog my disk 
The example file is
VideoChil 28557 28583              tom   40u      REG               0,24        40         42 /dev/shm/org.chromium.YOPwVD (deleted)
 There is a million and one of those files !! 
There is similar command 
lsof +L1 
which yields the same result 
it seems thet rebooting will release those files, who are simple orphans of killed processes**

**Comment by sq5rix** [comment]
Thanks!!  

I found out that two files - kern.log and syslog in /var/log grow a lot 
and/or
some unallocated space is created, which fortunately disappears after reboot.

I assume that chrome process writes a log but cannot close the file
I simply delete (it is better to use truncate huge files instead of simple rm) huge logs and if there is still some unusual space, I reboot. 

I found out that the command 
`lsof -nP | grep '(deleted)'`
shows many files which hog my disk 
The example file is
VideoChil 28557 28583              tom   40u      REG               0,24        40         42 /dev/shm/org.chromium.YOPwVD (deleted)
There is a million and one of those files !! 
There is similar command 
`lsof +L1`
which yields the same result 
it seems that rebooting will release those files, which are simple orphans of killed processes
