### ISSUE TITLE
Does Amazon AWS Traffic look spammy?

### ISSUE THREAD

**Issue by agcty** [InstaPy/InstaPy#1845]
I was wondering if anyone has experience with using the bot in the cloud. I plan to use it 2-3 times a day, liking ~200 pics each session. Do you think traffic from AWS will get flagged in any form or the account gets banned in the worst case?

**Comment by sionking** [comment]
yes

**Comment by sionking** [comment]
Only Real anonymous proxy (use the AWS and connect with 2 dollar proxy).
But best option is to use home ip address.
I am wondring if there is any device that set proxy at the home router?
