### ISSUE TITLE
This my error after update 

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#1846]
File "startstef.py", line 39, in <module>
    session.like_by_tags(['musculation','teamshape','getfit','fit','fitnessmodel','fitspo','crossfit','muscu','shooting','fitfrenchies'], amount=10)
  File "/Users/Retina/Desktop/Instapy/instapy/instapy.py", line 987, in like_by_tags
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 39: ordinal not in range(128)

**Comment by timgrossmann** [comment]
@johnvfitness Could you make sure that your terminal encoding is set to UTF-8, please?
