### ISSUE TITLE
This my problem after Update

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#1849]
Traceback (most recent call last):
  File "startstef.py", line 39, in <module>
    session.like_by_tags(['musculation','teamshape','getfit','fit','fitnessmodel','fitspo','crossfit','muscu','shooting','fitfrenchies'], amount=10)
  File "/Users/Retina/Desktop/Instapy/instapy/instapy.py", line 1030, in like_by_tags
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 48: ordinal not in range(128)

**Comment by athena15** [comment]
+1

**Comment by converge** [comment]
try python 3

**Comment by johnvfitness** [comment]
Thx bro 
I'm testing

**Comment by johnvfitness** [comment]
Hi bro I’m sorry after uninstall and update python 3
This my problem 

MacBook-Pro-de-Mac:~ Retina$ cd desktop
MacBook-Pro-de-Mac:desktop Retina$ cd instapy
MacBook-Pro-de-Mac:instapy Retina$ python startstef.py
Traceback (most recent call last):
  File "startstef.py", line 5, in <module>
    from selenium.common.exceptions import NoSuchElementException
ImportError: No module named selenium.common.exceptions
MacBook-Pro-de-Mac:instapy Retina$
