### ISSUE TITLE
Utilising the built in GitHub Wiki

### ISSUE THREAD

**Issue by littleswany** [InstaPy/InstaPy#185]
It would be great if we could add Wiki documentation to the project here similar to what is [here](https://github.com/google/material-design-lite/wiki).

We could use it for How To Guides, How To Contribute etc etc.

I am happy to start this, I am just not sure that if I do this on my forked repo that a PR merges it across, so if anyone could tell me how to practically do this that would be great 😄

**Comment by timgrossmann** [comment]
@littleswany That would be awesome!

Especially the part with how to contribute would be perfect!
In the worst case, we can just copy it.

**Comment by timgrossmann** [comment]
@littleswany I think you can now simply edit the wiki in this repo 😉
