### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by condomfighters** [InstaPy/InstaPy#1853]
After finding a solution to avoid following people that already follow me (thanks to uluQulu)
I came across this new problem.
When the bot tries to access the graphql queries instagram show this error:

> Access to www.instagram.com was denied
>You don't have authorization to view this page.
>HTTP ERROR 403

after doing alot of googling i found this topic on [reddit](https://www.reddit.com/r/Instagram/comments/86wjdy/access_denied/).

Does anyone know how to fix this problem or use the site of the redditor to fix the error? 

thank you for reading
if you have any question or want more info don't hesitate to ask.

**Comment by GitNees** [comment]
Is a network issue, not related to instapy, might be a proxy issue. Try on another network. Try tethering from your cellphone.

**Comment by condomfighters** [comment]
@GitNees thanks for clearing that up, you are awesome!!!

**Comment by GitNees** [comment]
Not sure if sarcastic... or fixed your issue...

**Comment by condomfighters** [comment]
@GitNees no that actually solved it lol thanks man 👍
