### ISSUE TITLE
How to follow 25% users, like 100%, comment 100%

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1854]
## Current Behavior
Just follows if they meet follower limit

## InstaPy configuration
session.set_upper_follower_count(limit=1500)
session.follow_by_tags(['bodybuilding', 'fit', 'fitness', 'gym', 'fitnessmotivation'], amount=50)
session.set_do_comment(True, percentage=100)
session.set_dont_like(['gay', 'fag', 'instagay', 'boy', 'motivationalquotes', 'fitgirl', 'toptags', 'model', 'Fitgirl'])
session.like_by_tags(['bodybuilding', 'fit', 'fitness', 'gym', 'fitnessmotivation'], amount=100)
session.set_comments([u'Great job! :fire:', u'Looking great! :100:'])

## Notes
I'm new to InstaPy, just playing with it right now. Are there any public configurations besides whats on the Git?

**Comment by uluQulu** [comment]
hey @bretie, this will do it:
```python
#some SETtings below
session.set_do_follow(enabled=True, percentage=25, times=1)  #25%
session.set_do_like(enabled=True, percentage=100)   #100%
session.set_do_comment(enabled=True, percentage=100)   #100%

#some ACTions below
session.like_by_tags(['nikontop', 'hills'], amount=200)
```
And always write **set**tings before **act**ions in your quickstart script, otherwise, it will not work properly _(most of the settings start with `set`, such as, session.`set`_do_like())_
> Read documentation, it is written well with great examples
