### ISSUE TITLE
setup.py not working: "No local packages or working download links found for emoji"

### ISSUE THREAD

**Issue by joshlorschy** [InstaPy/InstaPy#1856]
## Expected Behavior
I followed all of the instructions provided (in fact, I already have it working on my old computer but I just got a new laptop and I'm trying to set it up - I'm working on a Macbook in case that is relevant). I'm just expecting to be able to set up the InstaPy package.

## Current Behavior
Everything is downloaded (or appears to be).
When I enter 'python setup.py install' it says I don't have permission to write the files.
When I enter 'sudo python setup.py install' I get an error that reads:

Installed /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/instagram_py-0.0.1-py2.7.egg
Processing dependencies for instagram-py==0.0.1
Searching for emoji
Reading https://pypi.python.org/simple/emoji/
Download error on https://pypi.python.org/simple/emoji/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) -- Some packages may not be found!
Couldn't find index page for 'emoji' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) -- Some packages may not be found!
No local packages or working download links found for emoji
error: Could not find suitable distribution for Requirement.parse('emoji')

This also appears further above, which seems problematic but I'm not sure (it just looks like it can't find the necessary files):

writing dependency_links to instagram_py.egg-info/dependency_links.txt
writing dependency_links to instagram_py.egg-info/dependency_links.txt
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
reading manifest file 'instagram_py.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'instagram_py.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_py
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found

Would really appreciate any help!

**Comment by adecelle** [comment]
I am also having this error. Using a Macbook pro version 10.12.6, and an updated version of Google Chrome.

Thank you!

**Comment by anpin** [comment]
Hello everybody, 

I'm having the same issue on Ubuntu 14.04.5 in AWS, but on my local machine with the same OS everything is fine. I've tried install it both through pip and python setup.py install

**Comment by gaberamos** [comment]
Same issue on Macbook Pro 10.12.6

Ran: sudo python setup.py install
