### ISSUE TITLE
Not unfollowing all the users. 

### ISSUE THREAD

**Issue by lokmanm** [InstaPy/InstaPy#1859]
## Current Behavior
The count of users to unfollow shows up as: 300 but after 20-30 it stops.
## InstaPy configuration
Windows 10 Machine local
INFO [2018-04-15 17:26:02] ### Logged in successfully!
INFO [2018-04-15 17:26:06] ###  Number of users available to unfollow: 336

INFO [2018-04-15 17:38:23] ### --> Total people unfollowed : 24
INFO [2018-04-15 17:38:26] ###  Session ended - 2018-04-15 17:38:26
INFO [2018-04-15 17:38:26] ###  --------------------

**Comment by ghost** [comment]
What is your current configuration?
