### ISSUE TITLE
Exact match for negative Keywords

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#186]
It seems as if the function ```set_dont_like``` not only skips the selected hashtags but also skips all hashtags that starts with the selected hashtags. While this might be useful, too, I guess we should implement an exact match feature as well.

I stumbled upon this issue when I set "#me" as a negative keyword and images with hashtags like "#meindeutschland" wouldn’t be liked anymore.

**Comment by pekapa** [comment]
I had that with the word "hot", it would skip every post tagged with "photo" or something related. I changed to skip " hot" (with a space before).
I think the solution would be to do a split on spaces to find words and on hashes to find hashtags

**Comment by tibor** [comment]
Yeah, but I think it would be nice to have both options (broad match and exact match).
