### ISSUE TITLE
Bug After update

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#1861]
Traceback (most recent call last):
  File "john.py", line 51, in <module>
    session.like_by_tags(['musculation','teamshape','getfit','fit','fitnessmodel','fitspo','crossfit','muscu','shooting','fitfrenchies'], amount=10)
  File "/Users/jonathanverdier/Desktop/instapy/instapy/instapy.py", line 1031, in like_by_tags
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 39: ordinal not in range(128)

**Comment by timmoh** [comment]
which python version do you use? check it on console => python --version
Perhaps you have to change the encoding of john.py to utf8

**Comment by johnvfitness** [comment]
Hi Python 3.6.5
How can I change my encoding please

**Comment by seballero** [comment]
I have the same issue in Python 2.7.12

**Comment by johnvfitness** [comment]
what is the command in the terminal for update the python Please

**Comment by finan** [comment]
Same issue in Python 2.7.13
