### ISSUE TITLE
What are the major differences between Instapy and Instabot?

### ISSUE THREAD

**Issue by FarhadG** [InstaPy/InstaPy#1864]
It would be extremely useful to outline the major differences between these leading libraries ([Instapy](https://github.com/timgrossmann/InstaPy) and [Instabot](https://github.com/instabot-py/instabot.py)). This would provide the community useful information to be able to make more informed decisions in choosing the correct library for their use case. More importantly, it would attract the appropriate users to use and contribute back to its source.

That said, a major difference that I've seen are that `Instabot` only uses `http requests` whereas `Instapy` uses a browser automation tool (i.e. `selenium`) to drive user actions. What are some other major differences? How do their approaches compare? Which should you use when, where and why?

Thank you, in advance, for your time and help.

**Comment by spikeyhair** [comment]
You have raised a good question here. I haven't try instabot before but according to what you said here (only use http requests), it might required lower resources on the display? Because I did notice that instapy using browser automation, during page refresh and load, the content is coming slow and sometimes cause a time out issue.

**Comment by redstang33** [comment]
I just tried to give it a shot but it's not working at all. Seems it was using the old ?__a=1 API that instagram got rid of. Generally with all the changes instagram is making it seems to be that InstaPy is more sustainable as it uses chromedriver to simulate real users instead of going through the API.

**Comment by mdrzn** [comment]
I can't get chromedriver to work tho, while using InstaBot is pretty simple, just edit the example.py and launch it.

**Comment by FarhadG** [comment]
Thanks for giving a try, @redstang33. `InstaBot` is not using any API, as far as I'm aware of. They're leveraging the same techniques of driving user interactions via Instagram's interface. I believe they're simply parsing HTTP requests to query elements as needed.

I do agree that it's important to note the differences (pros/cons) of these tools, @spikeyhair. It's only then we can drive meaningful contributions to these libraries and their respective methodologies.

Looking forward to gathering more feedback here...

**Comment by redstang33** [comment]
hmm... interesting. So you're saying it's actually working? I tried to get it to work yesterday and couldn't and looking at the source code I see it accessing the ...?__a=1 that now returns a HTTP 403 access denied error. I admit though that I didn't spend too much time with it so I'll try again.

**Comment by mdrzn** [comment]
I've been using InstaBot.Py since mid-february. and apart from a couple issues here and there that got fixed, it's still working. Now it has an issue with unfollowing, but liking/commenting/following works with no issues.
I just wish I managed to make InstaPy work to test 'em both.

**Comment by redstang33** [comment]
mdrzn, what's not working for you as it's working here quite nicely. You will have to download chromedriver and save it in the assets subfolder of InstaPy.

**Comment by mdrzn** [comment]
I'm having random issues, from changing language to installing the chromedrivers. I tried fixing dependencies and stuff, I googled around a couple fixes, but got stuck. I'll open a ticket detailing my troubles soon.

**Comment by FarhadG** [comment]
Great, @mdrzn! I'm hoping some of the core contributors can chime about the inner workings of these modules. I've also created a similar issue within the `InstaBot` repo.

It would definitely be the case that a `request` based solution would be more efficient than a `browser driven` approach. However, there may be other things to consider that would be great to find out.

**Comment by mdrzn** [comment]
Turns out that my VM runs wheezy (Debian GNU/Linux 7.11) and there's no compatible 64x chromedriver.

**Comment by bardascat** [comment]
Instabot is easily detected as a bot. You will be banned very fast.

**Comment by davisonio** [comment]
There's also this one https://github.com/instagrambot/instabot which is more feature full than the original instabot.py

**Comment by Rhydderch** [comment]
> 
> 
> Instabot is easily detected as a bot. You will be banned very fast.

bardascat, why would it be detected faster as a bot ?

**Comment by bardascat** [comment]
I tried instabot for a long time and in many ways and sooner or later I was
temporary banned.

I guess because the api is easily tracked by instagram while the phantomjs
approach is closer to a human behaviour.
