### ISSUE TITLE
InstaPy detects maximum 270 followers

### ISSUE THREAD

**Issue by timojaask** [InstaPy/InstaPy#1865]
It seems InstaPy is not able to see more than 270 followers of each user. The following error appears on every run, no matter which user is used (usernames changed to xxx and yyy):
```
INFO [2018-04-16 08:48:03] [xxx]  Session started - 2018-04-16 08:48:03
INFO [2018-04-16 08:48:08] [xxx]  Logged in successfully!
WARNING [2018-04-16 08:48:41] [xxx]  yyy -> Less users to follow than requested. == 270 
WARNING [2018-04-16 08:49:36] [xxx]  zzz -> Less users to follow than requested. == 270 
INFO [2018-04-16 08:50:02] [xxx]  --> Users: 540 

INFO [2018-04-16 08:50:02] [xxx]  Username [1/540]

...
```

This happens despite users having way more than 270 followers -- they have thousands if not millions of followers.

Here's the relevant part from `docker_quickstart.py`. As you can see, `interact_user_followers` is set to 400:
```
bot.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')
bot.set_upper_follower_count(limit=250)
bot.set_do_comment(enabled=False, percentage=70)
bot.set_do_follow(enabled=False, percentage=50)
bot.set_do_like(enabled=True, percentage=100)
bot.interact_user_followers(['yyy', 'zzz'], amount=400, randomize=True)
```

## Expected Behavior
Bot detects 800 followers in total (400 each) and attempts interacting with them if their follower limit is met.

## Current Behavior
Bot detects only 540 followers in total (270 each).

## InstaPy configuration

```
from instapy import InstaPy

# Write your automation here
# Stuck ? Look at the github page or the examples in the examples folder

insta_username = 'xxx'
insta_password = 'password'

bot = InstaPy(username=insta_username, password=insta_password, selenium_local_session=False)
bot.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub')
bot.login()
bot.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')
bot.set_upper_follower_count(limit=250)
bot.set_do_comment(enabled=False, percentage=70)
bot.set_do_follow(enabled=False, percentage=50)
bot.set_do_like(enabled=True, percentage=100)
bot.interact_user_followers(['yyy', 'zzz'], amount=400, randomize=True)
bot.end()
```

**Comment by uluQulu** [comment]
hi @timojaask, the current scroller in the `get_given_user_followers` (_which is used by `interact_user_followers` feature to retrieve a list of usernames per users_) function (_at **unfollow_util.py** file_) can't handle higher amounts well (_can send max of 25 scrolls_), it needs to be rewritten to support both smaller and higher amounts with higher precision and lesser requests to server
>If YOU can write, in the same function you would replace `scroll_bottom` function with some standalone scroller function & add a link grabber + recheck the lenght of the `follow_buttons` in each cycle to break when satisfied
