### ISSUE TITLE
Stop unfollow_util when there are no users left to unfollow

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#187]
It seems as if the unfollow function gets into an endless loop when you have a larger unfollow amount selected than persons to unfollow are available:

![img_0575](https://cloud.githubusercontent.com/assets/3136416/25315103/166f9c0e-2850-11e7-8873-808b4a2b74bf.PNG)

**Comment by timgrossmann** [comment]
@tibor Yes, that really is an issue...
Same if the currently top 10 followed people are all mentioned in `dont_include`...
