### ISSUE TITLE
Unfollow script doesn't work anymore!!

### ISSUE THREAD

**Issue by anoirinoh** [InstaPy/InstaPy#1878]
Hi, 
since yesterday I don't know what's gong wrong with the script, every time I launch the script it returns this message on the browser 

> {"message": "execution failure", "errors": [{"message": "Something is wrong. Please check your input and try again.", "locations": []}], "data": {"user": null}, "status": "fail"}

and this on the terminal: 
`DevTools listening on ws://127.0.0.1:12636/devtools/browser/9ee08258-c3e9-40ef-bd9a-3e866e5f3e63
INFO [2018-04-18 10:58:50] [all_cats_lovers]  Session started - 2018-04-18 10:58:50
WARNING [2018-04-18 10:58:50] [all_cats_lovers]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO [2018-04-18 10:59:50] [all_cats_lovers]  Logged in successfully!
[1960:7620:0418/105951.159:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
[1960:7620:0418/105953.921:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
[1960:7620:0418/105953.926:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
[1960:7620:0418/105957.336:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
unable to get followers and following information
 'NoneType' object is not subscriptable
INFO [2018-04-18 10:59:57] [all_cats_lovers]  --> Total people unfollowed : 0
INFO [2018-04-18 11:00:45] [all_cats_lovers]  Session ended - 2018-04-18 11:00:45
INFO [2018-04-18 11:00:45] [all_cats_lovers]  --------------------`

any solution please? Thank you.

**Comment by GabrieleCalarota** [comment]
same here
something changed in graphic query

**Comment by GabrieleCalarota** [comment]
You need to change:

For follower:
` ?query_id=17851374694183129  ==> into ==> ?query_hash=37479f2b8209594dde7facb0d904896a`

For following:
`?query_id=17874545323001329 ==> into ==> ?query_hash=58712303d941c6855d4e888c5f0cd22f`

Also change first result to a maximum of 50 (so change `variables['first'] = 50` instead of 100)

**Comment by alxhoff** [comment]
Thanks for the reply. This seems to work but eventually crashes giving the error message

```
unable to get followers and following information 
 Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}
  (Session info: chrome=64.0.3282.119)
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 4.15.15-1-ARCH x86_64)

```

Where can one read up on this stuff?

**Comment by holymolly** [comment]
same here

**Comment by timgrossmann** [comment]
@GabrieleCalarota Could you maybe create a PR for that, please? 👍

**Comment by GabrieleCalarota** [comment]
@timgrossmann I did

#1883

**Comment by GabrieleCalarota** [comment]
#1883

**Comment by anoirinoh** [comment]
Thank you all friends, I have added onyInstapyFollowed=True, but start getting this error :  set_automated_followed_pool error line contains NULL byte. how to deal with this?
sorry i am a newbie at this

**Comment by GitNees** [comment]
Just tested my unfollowscript and it still works...

**Comment by anoirinoh** [comment]
i think i have lost the followedpool.csv

**Comment by CharlesCCC** [comment]
for those who lost the `followedpool.csv` go find the `general.txt` and then find the list of unsuccessful unfollowed user and re-add it back, you should be fine. (some manually work but still better than nothing)
