### ISSUE TITLE
Unfollow stopped working. " 'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by alxhoff** [InstaPy/InstaPy#1879]
## Expected Behavior
Unfollow onlyNotFollowMe is True and onlyInstapyFollowed is False.
## Current Behavior
Throwing error 
```
unable to get followers and following information 
 'NoneType' object is not subscriptable

```

## Possible Solution (optional)
I pulled master yesterday, I think it was wheb this behavior started
## InstaPy configuration

> session.unfollow_users(amount=tmp_unfollow_amount, onlyNotFollowMe = True,                       unfollow_after=72*60*60, sleep_delay=randint(10,13) * 60)

Any help appreciated.

Cheers

**Comment by flothousand** [comment]
Have the same issue :)

**Comment by timmoh** [comment]
Duplicate of #1878

**Comment by holymolly** [comment]
same here
