### ISSUE TITLE
Unfollow issue with verified users

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#188]
My account unfollowed three users although they were in the list ```set_dont_include```. Also, console has echoed „Verified“ when unfollowing these accounts.

![img_0576](https://cloud.githubusercontent.com/assets/3136416/25315211/dc036a94-2851-11e7-8a3f-65652d7d721d.PNG)

It seems as if InstaPy ignores the setting made in ```set_dont_include``` when the user is verified.

**Comment by timgrossmann** [comment]
@tibor Ahh, good to know! Yes, it just compares the text of the username... Thank you!

**Comment by tibor** [comment]
Should be working correctly with #193
