### ISSUE TITLE
Comment if description contains X

### ISSUE THREAD

**Issue by koenvdlist** [InstaPy/InstaPy#1880]
Hi All, 

I was wondering if there is a way to post a comment on a picture when the description of this picture contains X. 

For example, if someone writes 'have a nice day' or 'wish you a wonderful day' in their image description, is there a way to automatically post a comment which states 'have a nice day too!'?

**Comment by uluQulu** [comment]
hi @koenvdlist,
It is an interesting idea but declare your thoughts clearly in details cos practically at this stage it will be inefficient to just look for a post with "_Have a nice day!_" in caption and then post, also, you (_all of the users using it_) must generate a lots of "_Have a nice day, too!_" style return comments, moreover, the caption saying "_Have a nice day!_" may mean sth else and your return comment would look awkward.
_Clear up those questions and write down tips, it is really easy to implement it_
>Also, there is a similar feature, `clarifai_check_img_for`, which sends comment only after the picture verified by clarifai (_visually_) matches with the desired _#hashtags_
