### ISSUE TITLE
log unfollow users and time.

### ISSUE THREAD

**Issue by venomoustoad** [InstaPy/InstaPy#1884]
## Expected Behavior
Log unfollows with time stamp in the general log. The idea is to get to know when you unfollowed specific users in the log so that you could perform analytics on follows vs unfollows. 
## Current Behavior
we log follows and likes etc. Unfollow count appears in the log
## Possible Solution (optional)
out put the log in the general file as well

**Comment by visualheroes** [comment]
You can do something like this with some small programing.
I've done a simple separate log for "follow/unfollow/like" per session/loop with a custom variable using "session.unfollowNumber".
You can print it the same way instapy print the log file:
```
with open(yourlogfile, 'a') as numFile:
    numFile.write('{:%Y-%m-%d %H:%M} {} {} {}\n'.format(datetime.now(), yourvariable_session_likes or 0, yourvariable_session_followed or 0, yourvariable_session_unfollow or 0)))
```
I really think we need a place to exchange our script ideas. ;)

**Comment by sionking** [comment]
I use black list as my clog to file

**Comment by uluQulu** [comment]
hi @venomoustoad,
Obviously you are using `OnlyNotFollowMe` method cos other methods already record time.
To solve it, find this line below in **unfollow_util.py** and replace `print` word with `logger.info`,
```python
                    print('--> Ongoing Unfollow ' + str(unfollowNum) +
                          ', now unfollowing: {}'
                          .format(person.encode('utf-8')))
```
Now it will record ongoing unfollows with time as it does with likes...
> The difference is, `print` is just a simple python _output_ command and it doesn't write to our logs, but using `logger` feature, it will record to logs with time included.

_In `unfollow` function of **unfollow_util.py** file, there are 4 more lines using `print` as an output command, you might want to replace them all to `logger.info` for more awareness._
