### ISSUE TITLE
I lost the followedPool.csv!!

### ISSUE THREAD

**Issue by anoirinoh** [InstaPy/InstaPy#1886]
Hi,
every time i run the unfollowing script it returns this error msg:
`DevTools listening on ws://127.0.0.1:12419/devtools/browser/5780b14f-8f6d-483b-bd1c-904b4cd49f07
INFO [2018-04-19 20:33:45] [username]  Session started - 2018-04-19 20:33:45
WARNING [2018-04-19 20:33:45] [username]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO [2018-04-19 20:34:37] [username]  Logged in successfully!
[4172:10972:0419/203439.085:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
ERROR [2018-04-19 20:34:43] [username]  set_automated_followed_pool error [Errno 2] No such file or directory: 'C:\\Users\\Anoirinoh\\Documents\\instabots\\logs\\username_followedPool.csv'
INFO [2018-04-19 20:34:46] [username]  --> Total people unfollowed : 0
INFO [2018-04-19 20:34:53] [username]  Session ended - 2018-04-19 20:34:53
INFO [2018-04-19 20:34:53] [username]  --------------------`
how to fill the csv file with my +2000 following? Thanks

**Comment by CharlesCCC** [comment]
for those who lost the followedpool.csv go find the general.txt and then find the list of unsuccessful unfollowed user and re-add it back, you should be fine. (some manually work but still better than nothing)

**Comment by davidrocket** [comment]
the file to search for is general.log instead general.txt
