### ISSUE TITLE
Follow function does not work

### ISSUE THREAD

**Issue by gustafsom** [InstaPy/InstaPy#1887]
Hi friends, I'm having a problem in following accounts by Instapy.

Instapy reports that the account has been followed but Instagram does not follow.

The "Follow" button on the web site and the Instagram App work correctly, but only through Instapy that the function does not run.

**Comment by sionking** [comment]
try refresh the page to check if it really followed

**Comment by NAIJULU** [comment]
Same problem here

**Comment by ghost** [comment]
#1842 Same thing but with likes...
No solution.

**Comment by ghost** [comment]
Anyone figure out how to resolve this one?
