### ISSUE TITLE
Unable to run after login

### ISSUE THREAD

**Issue by spikeyhair** [InstaPy/InstaPy#1891]
## Expected Behavior
It supposed to be able to run the script, start commenting and liking photos.

## Current Behavior
It failed to run after logging in and went into my profile, this is the log I saw on the screen:

DevTools listening on ws://127.0.0.1:12172/devtools/browser/10e2168c-7ec2-495e-b
f62-8a0c2e0d641d
[4928:4992:0421/191705.936:ERROR:gl_surface_egl.cc(840)] eglInitialize D3D11 fai
led with error EGL_NOT_INITIALIZED, trying next display type
INFO [kev.ckw]  Session started - 2018-04-21 19:17:06
WARNING [kev.ckw]  Sorry, Record Activity is not working on Windows. We're worki
ng to fix this soon!
Cookie file not found, creating cookie...
[4708:4568:0421/191717.348:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
INFO [xxx]  Logged in successfully!
[4708:4568:0421/191722.067:ERROR:upload_data_presenter.cc(73)] NOT IMPLEMENTED
INFO [xxx]  Session ended - 2018-04-21 19:17:28
INFO [xxx]  --------------------
                                          
Anyone facing the same problem?

**Comment by Sleeeepy** [comment]
Same here, it actually fails to log in. There is a message in red underneath after InstaPy enters the credentials and presses the button saying that no account is associated with that username.
It then goes to the account page without being logged in. Logging then in manually with the same credentials works fine.

**Comment by CharlesCCC** [comment]
this sounds like an old issue, probably your IP get blocked and/or your account got softbanned. basically, you can't login through web but can sign-in through mobile client. You will have to wait for couple days and try it again.

**Comment by Sleeeepy** [comment]
no, definitely not banned. I could log in using the same chrome session instapy was using, same account, same IP only seconds later.

**Comment by CharlesCCC** [comment]
@Sleeeepy anyway, it is an issue from Instagram.com, not something InstaPy really able to handle/prevent.

**Comment by spikeyhair** [comment]
I can also login manually using chrome, everything is fine. I was able to run the script perfectly 2 months back but I stopped using it until now. Now when I run it again, it gives me this error. 

Who else are facing this issue?
Is there any new update on the script?
