### ISSUE TITLE
Sorry, Record Activity is not working on Windows. We're working to fix this soon!

### ISSUE THREAD

**Issue by koky462** [InstaPy/InstaPy#1894]
When I run the script, I am able to login to my account then search the first tag "jupiter" but I am unable to like the post and it shows the error message below.

My code of quickstart.py

```
from instapy import InstaPy

session = InstaPy(username='xxx', password='xxx')

session.login()

session.set_do_comment(enabled=True, percentage=70)
session.set_comments([u'Nicepost!', u'Greatsharing!'], media=None)
session.like_by_tags(['jupiter', 'jupiterz', '3dlamp', 'lamp', 'lamps', 'homedecor', 'homedecoration'], amount=300, media='Photo')
session.like_by_locations(['212988663/new-york-new-york/'], amount=300, media=None)


session.end()
```

_Error: INFO [2018-04-22 13:02:51] [ourcomfyhq] Session started - 2018-04-22 13:02:51 WARNING [2018-04-22 13:02:51] [ourcomfyhq] Sorry, Record Activity is not working on Windows. We're working to fix this soon! INFO [2018-04-22 13:03:20] [ourcomfyhq] Logged in successfully! INFO [2018-04-22 13:03:22] [ourcomfyhq] Tag [1/7] INFO [2018-04-22 13:03:22] [ourcomfyhq] --> b'jupiter' Traceback (most recent call last): File "quickstart.py", line 7, in <module> session.like_by_tags(['jupiter', 'jupiterz', '3dlamp', 'lamp', 'lamps', 'homedecor', 'homedecoration'], amount=300, media='Photo') File "C:\Users\CheeHao\Desktop\InstaPy-master\InstaPy-master\instapy\instapy.py", line 915, in like_by_tags skip_top_posts) File "C:\Users\CheeHao\Desktop\InstaPy-master\InstaPy-master\instapy\like_util.py", line 199, in get_links_for_tag "window.scrollTo(0, document.body.scrollHeight);") File "C:\Users\CheeHao\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script 'args': converted_args})['value'] File "C:\Users\CheeHao\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute self.error_handler.check_response(response) File "C:\Users\CheeHao\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value' (Session info: chrome=66.0.3359.117) (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 6.3.9600 x86_64)_

**Comment by uluQulu** [comment]
hi @koky462,
It is a well-known bug in Chrome part, your web browser is not compatible with its webdriver.
_Either_ downgrade Chrome browser to some old version compatible with chromedriver v2.34;
_Or_ upgrade your chromedriver to some newer version compatible with Chrome browser v66;
>Read more here in similar [SO thread](https://stackoverflow.com/questions/49162667/unknown-error-call-function-result-missing-value-for-selenium-send-keys-even).
_Hope it will solve your problem, otherwise ask me, I will help_
