### ISSUE TITLE
new get_links_for_tag return only 7 links.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#1899]
I am not sure as I am using my test-user which is new so don't see the top posts in each tag, but I get only 7 posts and the following line:

Tag [1/3]
--> b'baby'
This tag has so less pictures than expected...

Configurations:
skip_top_posts=True
amount=50 (show 49)

I will investigate but, please do more testing before committing this important function!

UPDATE:
I think it related to not having top-posts but I do skip it so I am not in the main scope

UPDATE 2:
Since we think we have top posts we set the "default_load" to 21, but we don't have it (also real users don't always have it) so it should be 12.

FIX:
Check if top posts exist and decide for default_load

**Comment by cbyrt** [comment]
Hi
I can see this "default_load = 21 if not skip_top_posts else 12" But I can't find the top posts? 
Where, what do I need to change?
Thanks

**Comment by sionking** [comment]
@cbyrt I did not implement the fix yet.

**Comment by uluQulu** [comment]
Hey @sionking, @cbyrt,
Main repo uses the old fix found in #1365 where it relied on default load..
Using the latest [gist](https://gist.github.com/uluQulu/162b0c1d387157ef6e163d796f9cdf7e) (`get_links_for_tag`) shared in the same thread would help.
