### ISSUE TITLE
Not commenting

### ISSUE THREAD

**Issue by fidel95** [InstaPy/InstaPy#19]
I get this error when the app is running and tries to leave a comment:

> [3/100]
Invalid Page: Message: no such element: Unable to locate element: {"method":"class name","selector":"_nk46a"}
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.25.426935 (8***),platform=Mac OS X 10.12.3 x86_64)

**Comment by timgrossmann** [comment]
@fcfidel 
It's hard to debug this problem without the actual page...
Could you provide the Instagram link to the post?

**Comment by aamirc** [comment]
I also am getting this error.

Link to page it was on. https://www.instagram.com/p/BSfVUFpAfa6/

`Invalid Page: Message: no such element: Unable to locate element: {"method":"class name","selector":"_nk46a"}
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.28.455520 (cc17746adff54984afff480136733114c6b3704b),platform=Windows NT 10.0.10586 x86_64)`

**Comment by aamirc** [comment]
Seems like the class has changed.

I fixed it by changing line number 51 in file '`like_util.py`' to look for the following class '`_31wak`' instead of '`_nk64a`'.

`  user_div = browser.find_element_by_class_name('_31wak')`

**Comment by timgrossmann** [comment]
@fcfidel  @aamirc 
Should be fixed by #21

**Comment by timgrossmann** [comment]
When checking the classes, it still was "_nk64" for me, @vlntdds mentioned, that it is different for other locations, so he changed it to use xPath instead of class 👍

**Comment by aamirc** [comment]
Cool thanks.
