### ISSUE TITLE
/assets folder missing when installing via venv

### ISSUE THREAD

**Issue by zdebevec** [InstaPy/InstaPy#1901]
Hi,

I installed the InstaPy using the venv as specified in the manual here. But the /assets folder is missing and consequently the PATH is not appropriate for the chromdriver. Any suggestions what to do?

tnx,

Ziga

**Comment by Syslog777** [comment]
go to the InstaPy directory
Run mkdir assets/

**Comment by fernaoguerra** [comment]
Hi @zdebevec, did you fix this? I got the same problem

@Syslog777, I tried adding the chromedriver to the /assets folder on the Instapy directory.  It did not work

#help 
Thanks!
