### ISSUE TITLE
ImportError: No module named selenium.common.exceptions - quickstart.py [CENTOS 7]

### ISSUE THREAD

**Issue by sewdough** [InstaPy/InstaPy#1903]
**Upon fresh CentOS 7 install, fresh python + packages + pip installations as mentioned in the guide I'm getting the following:**

[root@InstaPy]# python quickstart.py
```
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    from selenium.common.exceptions import NoSuchElementException
ImportError: No module named selenium.common.exceptions
```

**## Current Behavior**
ImportError: No module named selenium.common.exceptions

**Note:** 
```
# pip3.6 install selenium
Requirement already satisfied: selenium in /usr/lib/python3.6/site-packages
```

## InstaPy configuration
```
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = '*******'
insta_password = '*******'

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#   Settings.database_location = '/path/to/instapy.db'
#   Settings.chromedriver_location = '/path/to/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_upper_follower_count(limit=2500)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.like_by_tags(['natgeo'], amount=1)

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

```

Please help me.

**Comment by uluQulu** [comment]
hi @sewdough,
do you have multiple versions of python and pip?
_checking enviromental variables to know which python with selenium installed executes script would help_

**Comment by imbarismustafa** [comment]
python3 quickstart.py should solve the problem. Atlest for me it did solve. Thank you @uluQulu for saying multiple versions otherwise i would never be able to solve it thank you!

**Comment by uluQulu** [comment]
Eyvallah qardaş @imbarismustafa,
if needs help about this repository anytime, just mention my nick, I will hopefully help 🖐

**Comment by callum8004** [comment]
@uluQulu I am having the same error:

pi@raspberrypi:~/InstaPy $ sudo python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    from selenium.common.exceptions import NoSuchElementException
ImportError: No module named 'selenium'

Using raspberry Pi and have the chrome driver in assets folder.

**Comment by uluQulu** [comment]
@callum8004 
Wish I could help you, try to write down
+ What have you done?
+ What happened?
+ What do you think is the problem?
>Also write down the python versions installed on the system.

**Comment by c0d3x27** [comment]
@sewdough i had the same problem. you should do your install in the venv it will solve everything thats what i did

**Comment by britotiagos** [comment]
Happened the same with me.

Problem explanation: 
When you close the terminal which terminated the session you are in, also terminate the environment "Virtualenv" as well. So when you open a new terminal window and try to run the python quickstart.py it will get the error as you are out of the environment "Virtualenv" which you created before and were inside of it while running the bot.

Solution:
Before running the python quickstart.py you need to run " source ven/bin/activate ", which will start your virtual environment. After that, you can run " python quickstart.py " and it should run as before.

PS: remember to change the command/path "source ven/bin/activate" to suit your path if you have changed it before.

Hopefully, it will help. ;)
