### ISSUE TITLE
{"message": "rate limited", "status": "fail"}

### ISSUE THREAD

**Issue by pablodalma93** [InstaPy/InstaPy#1905]
## Expected Behavior
Unfollowing users

## Current Behavior
Error {"message": "rate limited", "status": "fail"}

## InstaPy configuration

from instapy import InstaPy

session = InstaPy(username='username', password='password')

session.login()

session.set_dont_include(['userwhatever'])

session.unfollow_users(amount=3700,onlyNotFollowMe=True)

**Comment by sionking** [comment]
amount=3700 ?!?!?!??!?!?!??!?!?!?
Go to unfollow file and change the sleep to 10 sec

**Comment by pablodalma93** [comment]
What's the problem with unfollow 3700? It worked fine for the first 3000 or so

**Comment by pablodalma93** [comment]
There are 21 calls to sleep() in the unfollow_util.py file, which one do I have to change? All of them?
