### ISSUE TITLE
auto direct message

### ISSUE THREAD

**Issue by emyabdel** [InstaPy/InstaPy#1907]
Hello

is there a way to send an auto direct message on instagram to everyone who follows me with instapy or any another solution?

**Comment by sionking** [comment]
instagram private api

**Comment by sionking** [comment]
but generally, no.

**Comment by emyabdel** [comment]
could you explain more please

**Comment by sionking** [comment]
There is no APi  officialy let you DM.
There is no DM with web mobile/PC.
The only DM is when you simulate the application reqs (private api"")

**Comment by wizarduk** [comment]
best paying for a service loads at $1 a month that do this

**Comment by emyabdel** [comment]
Which service do you advice me to use

**Comment by joshuachinemezu** [comment]
> Hello
> 
> is there a way to send an auto direct message on instagram to everyone who follows me with instapy or any another solution?

Yes @emyabdel, I have found a way to make this work, you can send direct messages on the mobile version of the instagram web app, using this approach https://github.com/timgrossmann/InstaPy/issues/4496#issuecomment-497947408, you can run web driver from a mobile app browser thus enabling access to sending direct messages and other features which are not available on the instagram desktop web version. I will create a pull request of my solution to this issue. Thanks

**Comment by hadifarnoud** [comment]
> > Hello
> > is there a way to send an auto direct message on instagram to everyone who follows me with instapy or any another solution?
> 
> Yes @emyabdel, I have found a way to make this work, you can send direct messages on the mobile version of the instagram web app, using this approach [#4496 (comment)](https://github.com/timgrossmann/InstaPy/issues/4496#issuecomment-497947408), you can run web driver from a mobile app browser thus enabling access to sending direct messages and other features which are not available on the instagram desktop web version. I will create a pull request of my solution to this issue. Thanks

since this change, it would be doable to add sending or accepting DM requests actions to InstaPy. would that be possible @timgrossmann ?
