### ISSUE TITLE
Cron & Raspberry pi3

### ISSUE THREAD

**Issue by JMuffin** [InstaPy/InstaPy#1914]
I've tried many different ways but no luck.
I have InstaPy script in /home/pi/InstaPy-jmuffin named JMuffin2.py
It is working good only when i run it from terminal as: sudo python /home/pi/InstaPy-jmuffin/JMuffin2.py
So I want to schedule it with Cron
When I add this to crontab as   cd /home/pi/InstaPy-jmuffin && sudo python JMuffin2.py
it starts (session is opened) and after about 40 sec. session is closed

Can anybody help me with this ?
I'm a newbie in linux and RPi

**Comment by remybrillet** [comment]
Hi,

Can you try with this line in your crontab : 
`cd /home/pi/InstaPy-jmuffin && /usr/bin/python3 ./JMuffin2.py`

**Comment by ghost** [comment]
`chmod +x /home/pi/yourscript.py `
make sure file has executable permission 
`sudo crontab -e `
use sudo to make sure can run script
`*/15 * * * * cd /home/pi/instapyfollow && /usr/bin/python3.5 ./yourscript.py`
run script every 15 minutes

**Comment by JMuffin** [comment]
Thanks. 
It's obviously permission fault.
I've added a line:
15 15 * * * root cd /home/pi/InstaPy-jmuffin && sudo python JMuffin.py
to anacron file in cron.d and it worked like a charm :)
I'll try later with adding to crontab and setting permissions with chmod +x

**Comment by JMuffin** [comment]
It was the permission fault as I thought.
chmod +x solved any problems :)
Thank You all.

**Comment by joanroig** [comment]
One question @JMuffin, which Chromedriver version can you use on RPI3? I'm using a RPI2 and I have only access to legacy versions of it, just wanted to know if the x64 processor from the RPI3 with a 64bit OS can run the most updated one.

**Comment by kushpvo** [comment]
I've successfully setup cron for the script on my Pi3B+ but how do I know if it is working? Where can I see the logs? 

Cron will run the script in backend, right?
