### ISSUE TITLE
Hellp Update

### ISSUE THREAD

**Issue by thonyhenrique** [InstaPy/InstaPy#1915]
Como consigo fazer a atualização no no servidor Digital Ocean ?
Usei o git pull em cd InstaPy mas não deu certo..

How do I upgrade to the Digital Ocean server?
I used **git pull** in **cd InstaPy** but it did not work ..

**Comment by ghost** [comment]
Just 'google' for tutorials....... and maybe learn some python........

**Comment by CharlesCCC** [comment]
You are not following the issue report format. Issue will be closed, please re-open it by following the format


## Expected Behavior

## Current Behavior

## Possible Solution (optional)

## InstaPy configuration
