### ISSUE TITLE
Jarvee? did anyone used it ?

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#1921]
It is I think the most famous one... how is it different from instaPY ?

**Comment by sionking** [comment]
We sure need to read this:
https://jarvee.com/instagram-follow-block-this-action-is-blocked-tips-solutions/

Since Jarvee is very popular, IG can use it and see the holes in it and the way it act, and block it.
I think many ppl now getting this follow blocks (previous javree like account manager with 10 accounts costumer of mine that got limited).

**Comment by solehpolysas** [comment]
Story Viewer that will view stories for you (bots don’t do that, right?)

Like this feature if can implement to InstaPy. 😎

**Comment by sionking** [comment]
@solehpolysas very easy to implement ... on my todo list.

**Comment by solehpolysas** [comment]
Yes please. This will be good. There is a lot features in Jarvee that we can implement in InstaPy.

This will make we botting like human behaviour. 😁

**Comment by sionking** [comment]
Any one know how Jarvee works ? is it also a selenium based ?
