### ISSUE TITLE
Almost works until value error? Rasbperry pi 3 (help please)

### ISSUE THREAD

**Issue by sebbiee** [InstaPy/InstaPy#1924]
It logs in but then one minute in it give me this
pi@raspberrypi:~/projects/Instapy $ sudo xvfb-run python quickstart.py
INFO [2018-04-28 22:33:02] [jazzyy.jinx]  Session started - 2018-04-28 22:33:02
INFO [2018-04-28 22:33:38] [jazzyy.jinx]  Logged in successfully!
INFO [2018-04-28 22:33:42] [jazzyy.jinx]  Tag [1/1]
INFO [2018-04-28 22:33:42] [jazzyy.jinx]  --> natgeo
INFO [2018-04-28 22:33:54] [jazzyy.jinx]  Session ended - 2018-04-28 22:33:54
INFO [2018-04-28 22:33:54] [jazzyy.jinx]  --------------------

Traceback (most recent call last):
  File "quickstart.py", line 41, in <module>
    session.like_by_tags(['natgeo'], amount=1)
  File "/home/pi/projects/Instapy/instapy/instapy.py", line 934, in like_by_tags
    skip_top_posts)
  File "/home/pi/projects/Instapy/instapy/like_util.py", line 196, in get_links_for_tag
    "//span[contains(@class, '_fd86t')]").text)
  File "/home/pi/projects/Instapy/instapy/util.py", line 342, in format_number
    return int(formatted_num)
ValueError: invalid literal for int() with base 10: ''
pi@raspberrypi:~/projects/Instapy $

**Comment by uluQulu** [comment]
hi @sebbiee,
_It seems to get stucked when getting possible posts' count where I just checked, and saw that, that part's page layout is **visually** changed, although, the same code works _well for me_, it means page **elements** are still the same._
**For you**, _for some reasons_, **either** your accaunt is affected by possible update in page elements **or** your Raspberry opens browser window in smaller sizes which would cause page elements **dislocate** **or** everything works fine except `format_number` function still _returns float instead of integer value_ which gives you that error.
**But**, _apply this change_, in **like_util.py** file:
**replace** this line
```python
possible_posts = format_number(browser.find_element_by_xpath(
                            "//span[contains(@class, '_fd86t')]").text)
```
**with**
```python
possible_posts = browser.execute_script(
    "return window._sharedData.entry_data."
    "TagPage[0].graphql.hashtag.edge_hashtag_to_media.count")
```
_Hopefully, you will not see that error again_

**Comment by sebbiee** [comment]
@uluQulu  It almost works! The only problem I have is that the session ends too quickly for some reason... (see below please.)

pi@raspberrypi:~/projects/InstaPy $ sudo xvfb-run python quickstart.py
INFO [2018-04-30 00:09:59] [jazzyy.jinx]  Session started - 2018-04-30 00:09:59
INFO [2018-04-30 00:10:44] [jazzyy.jinx]  Logged in successfully!
INFO [2018-04-30 00:10:47] [jazzyy.jinx]  Tag [1/1]
INFO [2018-04-30 00:10:47] [jazzyy.jinx]  --> natgeo
INFO [2018-04-30 00:10:57] [jazzyy.jinx]  desired amount: 1  |  top posts [disabled]: 9  |  possible posts: 11294624
INFO [2018-04-30 00:11:05] [jazzyy.jinx]  [1/1]
INFO [2018-04-30 00:11:05] [jazzyy.jinx]  https://www.instagram.com/p/BiLIm7EAUmV/?tagged=natgeo
INFO [2018-04-30 00:11:13] [jazzyy.jinx]  Image from: i.arun.kashyap
INFO [2018-04-30 00:11:20] [jazzyy.jinx]  User: i.arun.kashyap >> followers: 3532  |  following: 6240  |  relationship ratio: 1.0
INFO [2018-04-30 00:11:20] [jazzyy.jinx]  --> Image not liked: User i.arun.kashyap's following count exceeds maximum limit
INFO [2018-04-30 00:11:20] [jazzyy.jinx]  Liked: 0
INFO [2018-04-30 00:11:20] [jazzyy.jinx]  Already Liked: 0
INFO [2018-04-30 00:11:20] [jazzyy.jinx]  Inappropriate: 1
INFO [2018-04-30 00:11:20] [jazzyy.jinx]  Commented: 0
INFO [2018-04-30 00:11:20] [jazzyy.jinx]  Followed: 0
INFO [2018-04-30 00:11:22] [jazzyy.jinx]  Session ended - 2018-04-30 00:11:22
INFO [2018-04-30 00:11:22] [jazzyy.jinx]  --------------------

**Comment by uluQulu** [comment]
@sebbiee,
There is no any problem.
Check your quickstart script... (_maybe increase amounts for more  interaction_)
And if wonders why it says:
```
Image not liked: User i.arun.kashyap's following count exceeds maximum limit
```
just read about `set_relationship_bounds` feature in the README section, customize it for your needs or simply deactivate it

**Comment by sebbiee** [comment]
@uluQulu  Thank you so much for your patience and help it works!
