### ISSUE TITLE
Follow users of user - Scroll problem

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#1931]
Hello, when trying to follow users of user, the scroll stops at a point, is it possible to go further and see more users ?

**Comment by uluQulu** [comment]
hi @Edhim,
You have to loop until gets desired amount.
_A few weeks back, I have posted a solution to it_, get it [here](https://github.com/timgrossmann/InstaPy/issues/1548#issuecomment-372803884)

**Comment by Edhim** [comment]
@uluQulu Ok Thank you

**Comment by aleeepp** [comment]
Hello, @Edhim is it work?, in my case it is not working.

**Comment by Edhim** [comment]
@uluQulu @aleeepp i tried but didnt work neither for me :(

**Comment by uluQulu** [comment]
@Edhim,
Which feature you have used and how it does not work.
Can you describe you problem in details?

**Comment by Edhim** [comment]
@uluQulu when trying to follow users of a user who has many followers, the scroll stop at the 1000 last of his followers

**Comment by uluQulu** [comment]
@Edhim,
It can be that you have incorrectly applied modifications found in https://github.com/timgrossmann/InstaPy/issues/1548#issuecomment-372803884.
Recently those changes (_with slight update_) are merged into the main repo with #2012.
Having considering you mean `follow_user_followers` feature, please, pull latest updates try again and see if it is solved.
If you still get unwanted behavior, ask me again.

**Comment by Edhim** [comment]
@uluQulu 
I applied all changes, 
i am using this : 
session.follow_user_followers(['USER'], amount=250, randomize=False, sleep_delay=90)

but now it skips users to follow 
USER is not a potential user with the relationship ratio of 'RATIO'

**Comment by uluQulu** [comment]
@Edhim,
Use relationship bounds as you wish or just turn it off, it is up to you 😂
_e.g., to turn it off before running `follow_user_followers` feature, write it like this :_ 
```erlang
session.set_relationship_bounds(enabled=False)   ##FROM now on, verification based on relationship bounds, is disabled
session.follow_user_followers(['USER'], amount=250, randomize=False, sleep_delay=90)
```
>Hint: maybe you just want to turn off `potency_ratio` and keep `max` & `min` values used, eh? (_see `README`_)

**Comment by Edhim** [comment]
@uluQulu 
Sorry i am not very good 😂 

I wasn't using the relationshipbound before neither
Well i applied what you said but still not working 

INFO [2018-05-17 22:15:15] [soloticamaroc]  Session started - 2018-05-17 22:15:15
INFO [2018-05-17 22:15:44] [soloticamaroc]  Logged in successfully!
INFO [2018-05-17 22:15:45] [soloticamaroc]  User 'USER' [1/1]
INFO [2018-05-17 22:16:01] [soloticamaroc]  Failed to load desired amount of users
INFO [2018-05-17 22:16:01] [soloticamaroc]  Simulated follow : 1
INFO [2018-05-17 22:16:01] [soloticamaroc]  Not followed 'shalom.gotar'  ~inappropriate user
INFO [2018-05-17 22:16:02] [soloticamaroc]  ---> shalom.gotar has already been followed more than 1 times
INFO [2018-05-17 22:16:06] [soloticamaroc]  --> basma.aby instagram account is opened...
INFO [2018-05-17 22:16:17] [soloticamaroc]  ---> Now following: basma.aby
INFO [2018-05-17 22:16:22] [soloticamaroc]  Follow [1/4]  |  Total Follow: 1
INFO [2018-05-17 22:16:25] [soloticamaroc]  --> elhoussisalma instagram account is opened...
INFO [2018-05-17 22:16:38] [soloticamaroc]  ---> Now following: elhoussisalma
INFO [2018-05-17 22:16:43] [soloticamaroc]  Follow [2/4]  |  Total Follow: 2
INFO [2018-05-17 22:16:47] [soloticamaroc]  --> mazine_essaqi instagram account is opened...
INFO [2018-05-17 22:16:56] [soloticamaroc]  ---> Now following: mazine_essaqi
INFO [2018-05-17 22:17:03] [soloticamaroc]  Follow [3/4]  |  Total Follow: 3
INFO [2018-05-17 22:17:03] [soloticamaroc]  --> Followed total of 3 people

INFO [2018-05-17 22:17:03] [soloticamaroc]  Session ended - 2018-05-17 22:17:03
INFO [2018-05-17 22:17:03] [soloticamaroc]  --------------------


and actually not working anymore : 

Traceback (most recent call last):
  File "quickstartsolf.py", line 29, in <module>
    session.follow_user_followers(['USER'], amount=250, randomize=False, sleep_delay=90)
  File "/Users/Edhim/Desktop/INSTAPYMAISOL/instapy/instapy.py", line 1864, in follow_user_followers
    self.logfolder)
  File "/Users/Edhim/Desktop/INSTAPYMAISOL/instapy/unfollow_util.py", line 750, in get_given_user_followers
    logger, logfolder)
  File "/Users/Edhim/Desktop/INSTAPYMAISOL/instapy/unfollow_util.py", line 575, in get_users_through_dialog
    quick_button = follow_buttons[quick_index]
IndexError: list index out of range

**Comment by uluQulu** [comment]
@Edhim,
I couldn't see the error.
_if you mean_,
```erlang
INFO [2018-05-17 22:16:01] [soloticamaroc] Failed to load desired amount of users
```
_you should provide the amount BUT if it is the same amount in your previous post- 250, then you have burnt scroll requests, I would recommend to take some rest on that account_

Also, please, be precise while reporting **errors** 🤣

**Comment by Edhim** [comment]
@uluQulu  will give it some rest and try again ^_^

**Comment by gastonreal** [comment]
@uluQulu,

How does this "burnt scroll requests" happen? Is it Instagram banning requests after some criteria?
How can I estimate how much I can do before "burning" scroll requests?

You guys are great!

Thank you!
