### ISSUE TITLE
Bot stopped working after an hour

### ISSUE THREAD

**Issue by Stewler** [InstaPy/InstaPy#1933]
Hi guys.

I'm having problem with the bot, after 1 hour +- of running time the bot stops working and giving me the following error:

> 17:11:56] [XXX] --> Ongoing Unfollow 3, now unfollowing: b'XXX'
 INFO [2018-05-01 17:12:15] [XXX] --> Total people unfollowed : 3 
 INFO [2018-05-01 17:12:19] [XXX] Session ended - 2018-05-01 17:12:19
 INFO [2018-05-01 17:12:19] [XXX] 

How do I fix it? and make the bot work 24/7?
Thanks.

**Comment by CharlesCCC** [comment]
You are not following the issue report format. Issue will be closed, please re-open it by following the format


## Expected Behavior

## Current Behavior

## Possible Solution (optional)

## InstaPy configuration
