### ISSUE TITLE
Bot stopped working after an hour

### ISSUE THREAD

**Issue by Stewler** [InstaPy/InstaPy#1934]
Hi guys.

I'm having problem with the bot, after 1 hour +- of running time the bot stops working and giving me the following error:

17:11:56] [XXX] --> Ongoing Unfollow 3, now unfollowing: b'XXX'
INFO [2018-05-01 17:12:15] [XXX] --> Total people unfollowed : 3
INFO [2018-05-01 17:12:19] [XXX] Session ended - 2018-05-01 17:12:19
INFO [2018-05-01 17:12:19] [XXX]

How do I fix it? and make the bot work 24/7?
Thanks.

## Expected Behavior
I want the bot to work 24/7 without stops, liking photos and following.

## Current Behavior
Bot is liking photos, following,  after 1 hour +- of running time the bot stops working and giving me the following error:

> 

 [XXX] --> Ongoing Unfollow 3, now unfollowing: b'XXX'
INFO [2018-05-01 17:12:15] [XXX] --> Total people unfollowed : 3
INFO [2018-05-01 17:12:19] [XXX] Session ended - 2018-05-01 17:12:19
INFO [2018-05-01 17:12:19] [XXX]

> 

## InstaPy configuration
*It is too long to copy, won't let me paste it, any help?*

**Comment by uluQulu** [comment]
@darokif,
Attach your quickstart file in a zip, I will help

**Comment by Stewler** [comment]
@uluQulu 
[quickstart.zip](https://github.com/timgrossmann/InstaPy/files/1964941/quickstart.zip)

**Comment by uluQulu** [comment]
@darokif,
_I see that `unfollow_users` feature is the last action to take in your quickstart script_
##### So would you clearly state your needs?
**a)** You want to loop over some features in your quickstart script periodically
**b)** You just want `unfollow_users` feature to unfollow all 300 users (_taken from your traceback posted above, there it only unfollowed 3 users.._)
> You should know that quickstart script by default has no loop functionality, if you want, just make it to!

**Comment by Stewler** [comment]
@uluQulu
I want the bot to run 24/7 if it followed 300 users and they are not following back then I would like to unfollow these 300 users. Is it possible to do this?

Thanks for the help friend!

**Comment by uluQulu** [comment]
Welcome, @darokif,
For your quickstart repetite your actions 24/7, you must put them into a loop.
_e.g._,
```powershell
from instapy import InstaPy
session = InstaPy(username='x', password='x')
session.login()

zx = True
while zx==True:   # it will repeat actions forever, cos `zx` is equal to the value of `True`, above
    session.like_by_tags(['summertime'], amount=2000, media='Photo')
    session.like_by_locations(['213087839/sochi-russia/'], amount=600, media=None)

    session.follow_user_followers(['selenagomez'], amount=100, sleep_delay=10, randomize=True, interact=False)
    session.follow_by_list(['selenagomez'], times=1)
    session.unfollow_users(amount=300, sleep_delay=20)

session.end()
```

Your quickstart is not using lots of settings, have a good read at README and there are plenty of useful settings (_those start with `set_`, e.g., `set_relationship_bounds`_) but not using them is not really a problem
* For unfollowing users who do not follow you, you can use `onlyNotFollowMe=True` parameter in `unfollow_users` feature: 
```powershell
session.unfollow_users(amount=300, sleep_delay=20, onlyNotFollowMe=True)
```

**Comment by huangwaylon** [comment]
How long is a session by default then? When does Instapy know to stop if we do not run it in a loop?

For instance, if I want to unfollow 300 users, shouldn't the session last as long as it takes to complete the unfollowing process?

**Comment by Stewler** [comment]
@uluQulu
Oh I understand now...
Thank you for the detailed explanation, I will check the README file when I’ll get home, also will try the bot again!
I can’t thank you enough! 🤗

@huangwaylon
I’m new to these things don’t have much knowledge, trying to absorb as much as possible!

**Comment by uluQulu** [comment]
My pleasure @darokif,
Feel free to ask questions I can help of!

hi @huangwaylon,
I said like that above in `b)` variant, cos @darokif would have problems with `unfollow_users` feature to not unfollow all of the desired amount.
##### Loop is something different and it does repeat the actions inside the loop block.
A typical session lasts accordingly to your quickstart script, in particular, if you want to unfollow 300 users (`unfollow_users(amount=300, sleep_delay=20)`), then it **should** unfollow _all of them_ and then look for the next possible action in the quickstart script **and if** there is no action to do in the list, then it will _end session_ successfully.

**Comment by uluQulu** [comment]
@darokif,
>Okay I've tried the settings you've created for me, the bot runs for about 1.5h and then crashes, I don't get any error or anything else, it just exits itself

I guess you`ve encountered an error.
Post the full error output from console, I will investigate it.
_If there is no error, post the output where it _crashes_._

**Comment by Stewler** [comment]
@uluQulu 
I changed the settings I hope it works now, I'll keep you updated!
Okay so I added the "following" feature:

session.set_do_follow(enabled=True, percentage=10, times=2)

Bot doesn't seem to follow anyone :\

I wish there could be a quickstart file that has all the features already built-in, for example - following, un-following, liking, commenting.

**Comment by uluQulu** [comment]
@darokif,
Well, the methods (_functions_) starting with `set` (_e.g., `set_do_follow`, `set_comments`_) are just **set**tings and you need **act**ions (e.g., `follow_user_followers`, `like_by_tags` ) to use those settings and do something.
Those settings alone are nothing, so, use them before actions. e.g.,
```powershell
session.set_do_follow(enabled=True, percentage=10, times=2)
session.like_by_tags(amount=30, media='Photo', skip_top_posts=False, interact=True)
```

If you understand above, and still don't get any follows, try this:
1. set percentage to 100 for test purposes and see if it follows any
```powershell
session.set_do_follow(enabled=True, percentage=100, times=2)
#if it follows, then there is no problem
```
2. provide more details and maybe attach your zipped quickstart script to investigate further...

**Comment by Stewler** [comment]
@uluQulu 
Hey, I've added these and tried to run the bot for about 1 hour, no crashes so far - but it is not following, added 100 percentage, won't follow either.

Attached a zip file,
Thanks again for the help my friend!
[quickstart.zip](https://github.com/timgrossmann/InstaPy/files/1972109/quickstart.zip)

**Comment by uluQulu** [comment]
It's clear now, @darokif,
You have started `set_do_follow` setting after `like_by_tags` and `like_by_locations` features, that's why those features will NOT follow anybody and their amount is big in there (_2000 per tag, 600 for locations_), that's why you don't see anybody to be followed.
**It is a good** style that starting **set**tings (_e.g., `set_do_follow`_) before actions (_e.g., `like_by_tags`_).
So, you should use,
```python
## some quickstart code...

zx = True
while zx==True:
    session.set_do_follow()   # SET settings before actions to be used with

    session.like_by_tags()
    session.like_by_locations()
    session.follow_user_followers()
    session.follow_by_list(()
    session.unfollow_users()

## some other code...
```
> Side note: all **set**tings are in effect with the **act**ions _which_ are **located after** them.

**Comment by nafferro** [comment]
I dont know if this is related
but the script stops before follow 400 users and unfollow 450

last time report:
Followed
159
Unfollowed
165
Session Started
2018-05-03 08:00:07
Session Ended
2018-05-03 10:58:12

my script file:
session.follow_user_followers(['xxx'], amount=400, randomize=False, interact=False, sleep_delay=60)
session.unfollow_users(amount=450, onlyNotFollowMe=True, unfollow_after=24*60*60, sleep_delay=60)

**Comment by Stewler** [comment]
@uluQulu 
I understand now.. fixed it again, the bot was running for about 28 hours!
After that the bot crashed with the following error:

Traceback (most recent call last):
  File "C:\Users\dvlav\Desktop\InstaPy-master\InstaPy-master\quickstart.py", line 14, in <module>
    session.follow_user_followers(['selenagomez','justinbieber', 'therock', 'zacefron', 'cristiano'], amount=10, sleep_delay=10, randomize=True, interact=False)
  File "C:\Users\dvlav\Desktop\InstaPy-master\InstaPy-master\instapy\instapy.py", line 1504, in follow_user_followers
    self.follow_times)
  File "C:\Users\dvlav\Desktop\InstaPy-master\InstaPy-master\instapy\unfollow_util.py", line 819, in follow_given_user_followers
    callbacks=[])
  File "C:\Users\dvlav\Desktop\InstaPy-master\InstaPy-master\instapy\unfollow_util.py", line 500, in follow_through_dialog
    "//div[text()='Followers' or text()='Following']/following-sibling::div")
  File "C:\Users\dvlav\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\dvlav\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\webdriver.py", line 752, in find_element
    'value': value})['value']
  File "C:\Users\dvlav\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Users\dvlav\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/following-sibling::div"}
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.16299 x86_64)

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x0000022CEBE0C080>>
Traceback (most recent call last):
  File "C:\Users\dvlav\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 163, in __del__
  File "C:\Users\dvlav\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 139, in stop
  File "C:\Users\dvlav\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down
[5032:4740:0505/172722.470:ERROR:latency_info.cc(164)] RenderWidgetHostImpl::OnSwapCompositorFrame, LatencyInfo vector size 252 is too big.

**Comment by uluQulu** [comment]
hi @darokif,
it's not your mistake now,
can you confirm that `follow_user_followers` and/or `follow_user_following` features work for you any?

**Comment by Stewler** [comment]
@uluQulu 
Well, un-following does not work I think.. because last night I followed 200 people, today I checked and I have 1,300 following, so I don't think it works?

**Comment by uluQulu** [comment]
@darokif,
of course it works, although it can be, that you've surpassed limits, just be carefully and use a smaller amount between different features instead of one huge instance..
but for the error above, can you confirm the last statement in my previous comment?

**Comment by Stewler** [comment]
@uluQulu 
Yes it works, `follow_user_followers`
It is following people as I can see at the moment.

**Comment by uluQulu** [comment]
Fine, @darokif,
open up **unfollow_util.py** file and apply this _modification_:
find and **replace**
```python
    dialog = browser.find_element_by_xpath(
      "//div[text()='Followers' or text()='Following']/following-sibling::div")
```
**with**
```python
    try:
        dialog = browser.find_element_by_xpath(
          "//div[text()='Followers' or text()='Following']/following-sibling::div")
    except NoSuchElementException:   # in case of couldn't find required elements..
        logger.info("Couldn't find 'Followers' or 'Following' dialog box :/")
        return person_followed
```
_It will handle the possible misbehavior you have encountered and will prevent the program crash._

**Comment by Stewler** [comment]
@uluQulu 
Awesome, thanks!
I'll leave it overnight and will update tomorrow morning if it crashed!
Thanks a lot for the help my friend!

**Comment by Stewler** [comment]
Hi @uluQulu 
So It's been a couple of days and the bot works fine, no crashes and no errors.

The only thing that is bothering me is that the bot is following more people that it un-follows.
So I end up following 4,000 people after a day 💃 

I updated the un-follow code to:
 `session.unfollow_users(amount=3000, onlyInstapyFollowed=True, sleep_delay=1, unfollow_after=3030, onlyInstapyMethod = 'FIFO', onlyNotFollowMe=True)`

And the follow code to:
` session.follow_user_followers(['selenagomez','justinbieber', 'therock', 'zacefron', 'cristiano'], amount=10, sleep_delay=10, randomize=True, interact=False)`

Also, when unfollowing I also get this error:
`--> Cannot Unfollow From InstaPy 6, now unfollowing: b'xxx'`
Sometimes InstaPy is 6,5,2,0,1 But my following tab is slowly reducing, so I guess it is fine.

Do you think it will be okay now? 👍 
Thanks for helping out!

**Comment by uluQulu** [comment]
hi @darokif,
it's amazing! xD
> try to use values within allowed range, e.g., `600` is a good value for daily follow, and always unfollow less than you follow,..

_using excessively is dangerous, but if you want to run your script 24/7, then add sleep delays between loops...._
cheers!

**Comment by neversleeps** [comment]
Sorry for gravedigging, but can you please post your quickstart and how you got that loop

**Comment by Stewler** [comment]
Hi again @uluQulu 
I've encountered another error, hope you can help with that one too!
This time, the bot stops working after a few minutes of running.

```
TypeError: unfollow_users() got an unexpected keyword argument 'onlyInstapyFollowed'
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x000001B72DFA7208>>
Traceback (most recent call last):
  File "C:\Users\dvlav\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 163, in __del__
  File "C:\Users\dvlav\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 139, in stop
  File "C:\Users\dvlav\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-2.53.6-py3.6.egg\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
ImportError: sys.meta_path is None, Python is likely shutting down
```
Any idea what that might be?
Thanks!
