### ISSUE TITLE
Doesn't run upto the limit set

### ISSUE THREAD

**Issue by Nocturnal-2** [InstaPy/InstaPy#1935]
## Expected Behavior

I have the following setting in quickstart.py 

# actions
    session.set_do_follow(enabled=True, percentage=10, times=40)
    session.like_by_tags(['marais'], amount=400)

I am expecting the program to run until it likes 400 images for the specified tag and follow upto 40 users. 

## Current Behavior

It likes only 27 images.

Log from display:

DevTools listening on ws://127.0.0.1:12968/devtools/browser/34707ab7-6313-4a61-97a5-b899f38bccf3
INFO [2018-05-01 23:31:15] [myaccount_name]  Session started - 2018-05-01 23:31:15
WARNING [2018-05-01 23:31:15] [myaccount_name]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
[708:1764:0501/233123.162:ERROR:shader_disk_cache.cc(238)] Failed to create shader cache entry: -2
INFO [2018-05-01 23:31:56] [myaccount_name]  Logged in successfully!
INFO [2018-05-01 23:31:58] [myaccount_name]  Tag [1/1]
INFO [2018-05-01 23:31:58] [myaccount_name]  --> b'marais'
INFO [2018-05-01 23:33:51] [myaccount_name]  [1/27]

As you can see in the last line, it has already set the limit as 27. 

INFO [2018-05-01 23:39:30] [myaccount_name]  Liked: 16
INFO [2018-05-01 23:39:30] [myaccount_name]  Already Liked: 9
INFO [2018-05-01 23:39:30] [myaccount_name]  Inappropriate: 2
INFO [2018-05-01 23:39:30] [myaccount_name]  Commented: 1
INFO [2018-05-01 23:39:30] [myaccount_name]  Followed: 2
[3676:10356:0501/233932.317:ERROR:broker_win.cc(57)] Error reading broker pipe: The pipe has been ended. (0x6D)
INFO [2018-05-01 23:40:05] [myaccount_name]  Session ended - 2018-05-01 23:40:05
INFO [2018-05-01 23:40:05] [myaccount_name]  --------------------

## InstaPy configuration

I am sorry, I am new to InstaPy (and also Python). I am not sure what configuration I should copy as  instapy.py is a big file. So I have attached the complete file.

[instapy.zip](https://github.com/timgrossmann/InstaPy/files/1965352/instapy.zip)

**Comment by uluQulu** [comment]
hi @Madhu-sudhanan,
From your console output, I can tell that you're running an old version of files, please update to the latest files (_do `git pull master` or `re-download` (or `re-clone`) InstaPy repository_) and try again, it is already fixed.  
> In particular, just update **like_util.py** file to see the effect, but updating full repository is a better choice

**Comment by Madhu-sudhanan** [comment]
@uluQulu  Thanks for the response! 

I updated the full repository. With the latest version I am getting the following error :

C:\D drive\Workspace\InstaPy\InstaPy>python quickstart.py
INFO - Session started - 2018-05-02 10:18:49
C:\D drive\Workspace\Python\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py:50: DeprecationWarning: use options instead of chrome_options
  warnings.warn('use options instead of chrome_options', DeprecationWarning)
INFO - Logging in with credentials for: myusername
ERROR - Inputs and Elements missmatch
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    session.login()
  File "C:\D drive\Workspace\InstaPy\InstaPy\instapy\instapy.py", line 76, in login
    success = self.landing.login(self.username, self.password)
  File "C:\D drive\Workspace\InstaPy\InstaPy\instapy\views\landing.py", line 17, in login
    self.fill_form(inputs=[username, password])
  File "C:\D drive\Workspace\InstaPy\InstaPy\instapy\utils\views_mixin.py", line 251, in fill_form
    return self.fill_form_by_xpath("//form/div/input", inputs)
  File "C:\D drive\Workspace\InstaPy\InstaPy\instapy\utils\views_mixin.py", line 232, in fill_form_by_xpath
    raise FormError('Inputs and Elements missmatch!')
instapy.utils.exceptions.FormError: Inputs and Elements missmatch!

Apart from this error, four instances of Chrome are opening - one looks like normal browser and three looks like terminal.

**Comment by Nocturnal-2** [comment]
@uluQulu Thanks for the response!

I have cloned the latest version from the repository. I am getting the following error:

Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    session.login()
  File "C:\D drive\Workspace\InstaPy\instapy\instapy.py", line 317, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\D drive\Workspace\InstaPy\instapy\print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage."
  File "C:\D drive\Workspace\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "C:\D drive\Workspace\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\D drive\Workspace\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'user' of undefined
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.16299 x86_64)

Should I start a new thread for this?

I have attached my quickstart.py below

[quickstart.zip](https://github.com/timgrossmann/InstaPy/files/1966612/quickstart.zip)

**Comment by uluQulu** [comment]
Welcome @Madhu-sudhanan,
It is a very fresh issue you have encountered and the solution is found at #1936.
_I guess it also is merged, try to update again and see if it works?_

**Comment by Nocturnal-2** [comment]
I have updated and run, a new error this time. Possible that I did something wrong this time 

Traceback (most recent call last):
  File "quickstart.py", line 33, in <module>
    session.like_by_tags(['marais'], amount=100)
  File "C:\D drive\Workspace\InstaPy\instapy\instapy.py", line 957, in like_by_tags
    self.logger)
  File "C:\D drive\Workspace\InstaPy\instapy\like_util.py", line 461, in check_link
    media = post_page['media']
TypeError: list indices must be integers or slices, not str

**Comment by uluQulu** [comment]
You have done nothing, @Madhu-sudhanan 😅,
Have a read this fresh solution at https://github.com/timgrossmann/InstaPy/issues/1946#issuecomment-386116515

**Comment by Nocturnal-2** [comment]
Followed the instructions in [#1946 (comment)](https://github.com/timgrossmann/InstaPy/issues/1946#issuecomment-386116515). Got past my previous error, but I am getting another error. 

Traceback (most recent call last):
  File "quickstart.py", line 33, in <module>
    session.like_by_tags(['marais', 'mylittleparis'], amount=100)
  File "C:\D drive\Workspace\InstaPy\instapy\instapy.py", line 957, in like_by_tags
    self.logger)
  File "C:\D drive\Workspace\InstaPy\instapy\like_util.py", line 459, in check_link
    '''.format(user_name))
  File "C:\D drive\Workspace\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "C:\D drive\Workspace\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\D drive\Workspace\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'shortcode_media' of undefined
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.16299 x86_64)

[3388:10272:0503/010109.660:ERROR:broker_win.cc(134)] Error sending sync broker message: The pipe is being closed. (0xE8)

**Comment by uluQulu** [comment]
@Madhu-sudhanan,
Well, it is weird, attach zipped **like_util.py** file, I will look further

**Comment by Nocturnal-2** [comment]
Thank you! I have attached it here. I am also attaching **print_log_writer.py**

[like_util.zip](https://github.com/timgrossmann/InstaPy/files/1969855/like_util.zip)
[print_log_writer.zip](https://github.com/timgrossmann/InstaPy/files/1969862/print_log_writer.zip)

**Comment by uluQulu** [comment]
Welcome, @Madhu-sudhanan,
in **like_util.py**,
```powershell
window._sharedData.entry_data.PostPage.graphql.shortcode_media.edge_media_to_comment.edges;
```
should be
```powershell
window._sharedData.entry_data.PostPage[0].graphql.shortcode_media.edge_media_to_comment.edges;
```
_you have missed putting `[0]` back in there_

**Comment by Nocturnal-2** [comment]
This particular line appears to be commented. Should I still add there?

**Comment by uluQulu** [comment]
@Madhu-sudhanan,
Yes of course, since _triple single quotes_ in there are the way to send **multi-line JS statements** with `{}` python formatter rather than typical `arguments[i]` JS notation, **and** is not a typical python multi-line triple quotes _comment_.

**Comment by Nocturnal-2** [comment]
Thank you so much! Its running fine now!!
