### ISSUE TITLE
"Cannot read property 'graphql' of undefined"

### ISSUE THREAD

**Issue by robpettinato** [InstaPy/InstaPy#1936]
## Expected Behavior
Booting script, should work! 
## Current Behavior
receiving error: selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'graphql' of undefined

Didn't make any changes at all. Was working just fine, went to run the script again and have been getting this error.

**Comment by CharlesCCC** [comment]
looks like instagram.com might have changed their data structure again. i'm having the same issue, looking into it.

**Comment by joanroig** [comment]
Same issue here

**Comment by craigricker** [comment]
@CharlesCCC I was going to look into this as well. Have you reduced the search area for what may be causing the issue at all? Thanks, whatever information you have would be helpful.

**Comment by CharlesCCC** [comment]
Based off initial research, their (Instagram.com) removed the `graphql` from the `entry_data` entirely if you logged in. but apparently the data still there if you don't login and just visit the profile page ?(strange).  we need figure out another way to grab those data.

**Comment by joanroig** [comment]
I've solved the first problems changing this line, please check this out:
line 11 from instapy/print_log_writer.py 

`"return window._sharedData.""entry_data.ProfilePage[0]."`
to 
`"return window._sharedData.""entry_data.ProfilePage."`

But after the login and firsts steps seems to fall again here:

`instapy/like_util.py", line 438, in check_link graphql = 'graphql' in post_page[0]`

**Comment by CharlesCCC** [comment]
@joanroig that won't work, I tried that already. after you logged in, the "ProfilePage" just disappeared from the page.

**Comment by CharlesCCC** [comment]
this is what I see after I logged in 

```
   "supports_es6":true,
   "country_code":"US",
   "language_code":"en",
   "locale":"en_US",
   "entry_data":{  
      "FeedPage":{  
         "graphql":null
      }
   },
```

**Comment by joanroig** [comment]
@CharlesCCC mine seems to work fine step by step, changing those [0] to non-arrays, I'm also changing this code from instapy/like_util.py:

```
    graphql = 'graphql' in post_page[0]
    if graphql:
        media = post_page[0]['graphql']['shortcode_media']
```

to

```
    graphql = 'graphql' in post_page
    if graphql:
        media = post_page['graphql']['shortcode_media']
```

Seems like there are no more post_page and ProfilePage arrays there.

**Comment by CharlesCCC** [comment]
Looks like there will be possible solution:

1.  find the web element and grab that value
```html
<a class="_t98z6 " href="/followers/"><span class="_fd86t " title="14,153">14.1k</span> followers</a>
```

2. grab the value before log in ? (assume if they decide keep the `graphql` in the not logged in profile page forever).

**Comment by joanroig** [comment]
@CharlesCCC I got the quickstart.py working right now using my code posted before, I'll try to commit my changes after a quick review.

**Comment by CharlesCCC** [comment]
@joanroig thank you for the quick fix.  I believe this fix might work on some people. because my two account doesn't have the `entry_data` after logged in. 

I currently have to remove the line that will grab that information to get it going.

**Comment by CharlesCCC** [comment]
find a old piece of code might actually helped with my issue, not sure why is get changed with the new version:

```python
    try:
        followed_by = browser.execute_script(
            "return window._sharedData.""entry_data.ProfilePage."
            "graphql.user.edge_followed_by.count")
    except WebDriverException:   #handle the possible `entry_data` error
        try:
            browser.execute_script("location.reload()")
            followed_by = browser.execute_script(
                "return window._sharedData.""entry_data.ProfilePage."
                "graphql.user.edge_followed_by.count")
        except WebDriverException:
            followed_by = None
```

**Comment by joanroig** [comment]
@CharlesCCC seems strange to me 😣 @robpettinato please check if my last pull request works for you too.

**Comment by craigricker** [comment]
@joanroig it fails for me. The obvious difference for me is I am interacting with a User's followers vs the quickstart.

Edit: I didn't see the full breadth of your changes. Pulling from your commit and testing now.

**Comment by joanroig** [comment]
@craigricker some options tested right now, I've added my tested features in the pull request description. I hope this solves your issues too, mine seems to work like before again :)
Edit: Pull request re-referenced again from my branch 'master', I was on the wrong one.

**Comment by craigricker** [comment]
@joanroig pulling from your most recent commit (d82f706) from [this ](https://github.com/joanroig/InstaPy/tree/d82f70692efde57f551c088cdeb1a030cbcda528) does not fix my issues sadly! But I am glad you are up and running.

**Comment by joanroig** [comment]
@craigricker please clone my forked repo and check it again:
https://github.com/joanroig/InstaPy
Probably you need to refresh your .pyc compiled files, otherwise please copy paste your issue here.

**Comment by ghost** [comment]
how do you troubleshoot this problem ?

**Comment by craigricker** [comment]
@joanroig currently working, thanks! I believe you are right, it was related to the .pyc files being refreshed properly.

**Comment by joanroig** [comment]
@craigricker I'm glad to listen that :) @loopypanda just pick the code changes from this pull request:
https://github.com/timgrossmann/InstaPy/pull/1940

**Comment by G0DZ** [comment]
@joanroig working for me, thx!

**Comment by uluQulu** [comment]
hi guys,
actually, before latest update, **graphql** `dictionary` was in the first `list` of PostPage (_may/would apply to FeedPage and others, too_) entry.  
But now, that list is removed and we no more need the index of `[0]`
It's a good catch @joanroig, awesome!
_There is one more thing, too, did this update hit entire or partial userbase?_

**Comment by ximhotep** [comment]
@joanroig Just tested your changes and they work for me.  Ty.

**Comment by CharlesCCC** [comment]
@uluQulu probably partial user for now. (consider their huge user base) it might take sometime to get the change deployed cross all of their servers.

**Comment by joanroig** [comment]
Seems like the [0] is back again, can anyone look for it please?

**Comment by uluQulu** [comment]
Yes @joanroig, I checked,
![screenshot 306](https://user-images.githubusercontent.com/33269249/39500792-11fffd96-4dc8-11e8-9bf8-fdaa4158efc4.png)
Now I think, @CharlesCCC, if there will be a change, it will possibly apply to all as it is so easy to switch changes at no time

**Comment by sionking** [comment]
I don't have this update yet.

**Comment by sionking** [comment]
Good to know you all getting those fails before I do lol si I can prepare (geo update probably)

**Comment by akyzer** [comment]
Me too i dont have anything !

**Comment by joanroig** [comment]
@timgrossmann Instagram will probably switch again using the index [0], I think we can have a branch with my last changes to switch if the list removal is definitive.

**Comment by joanroig** [comment]
Issues solved by reverting the last adaption to Instagram changes:
https://github.com/timgrossmann/InstaPy/pull/1954

I think it solves all of these open issues:
https://github.com/timgrossmann/InstaPy/issues/1953
https://github.com/timgrossmann/InstaPy/issues/1952
https://github.com/timgrossmann/InstaPy/issues/1951
https://github.com/timgrossmann/InstaPy/issues/1949
https://github.com/timgrossmann/InstaPy/issues/1946
https://github.com/timgrossmann/InstaPy/issues/1944

[Here](https://github.com/joanroig/InstaPy/tree/array_removed_feature) is my branch without the [0] that we mentioned, @timgrossmann shall we make this branch for the future? Otherwise we can check the code from the previous commit, I hope there will be no more changes for now 😅

**Comment by CharlesCCC** [comment]
@joanroig it is so strange why Instagram change back and forth on this ? (Ideally, for each of those location we should check both scenario like the following approach), so we don't need switch back and forth on each branch:

```python
    try:
        followed_by = browser.execute_script(
            "return window._sharedData.""entry_data.ProfilePage."
            "graphql.user.edge_followed_by.count")
    except WebDriverException:   #handle the possible `entry_data` error
        try:
            browser.execute_script("location.reload()")
            followed_by = browser.execute_script(
                "return window._sharedData.""entry_data.ProfilePage[0]."
                "graphql.user.edge_followed_by.count")
        except WebDriverException:
            followed_by = None
```

**Comment by sionking** [comment]
Maybe this is how they tests bots? since they fail the right after page layout changes ?

**Comment by joanroig** [comment]
@CharlesCCC yes I think it will be the best method, these days I have no time to check all code and make a pull request while checking that nothing is broken, I hope anyone else can do it so.
Probably they've tested a new version that will be live in some days...

**Comment by wizel10** [comment]
@joanroig just wanted to let you know I've committed your fork and updated instapy.py with:
    def like_by_feed(self, **kwargs):
        """Like the users feed"""
        for i in self.like_by_feed_generator(**kwargs):
            pass
        return self

and it's working great.

Moltes merces!!!
