### ISSUE TITLE
Errors from GraphQL (I think)

### ISSUE THREAD

**Issue by watty62** [InstaPy/InstaPy#194]
When running the test script I get the following output. I raised this with Tim (who suggested that I create this issue) and he thought that this was coming from GraphGL? 

Any ideas / solutions? 

[1/93]
Traceback (most recent call last):
  File "/Users/ian/development/InstaPy/from instapy import InstaPy.py", line 10, in <module>
    .like_by_tags([‘dog', ‘#cat'], amount=100)\
  File "/Users/ian/development/InstaPy/instapy/instapy.py", line 224, in like_by_tags
    self.ignore_if_contains, self.username)
  File "/Users/ian/development/InstaPy/instapy/like_util.py", line 56, in check_link
    user_name = browser.execute_script("return window._sharedData.entry_data.PostPage[0].media.owner.username")
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'owner' of undefined
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.4 x86_64)

[Finished in 59.8s with exit code 1]
[shell_cmd: python -u "/Users/ian/development/InstaPy/from instapy import InstaPy.py"]
[dir: /Users/ian/development/InstaPy]
[path: /usr/bin:/bin:/usr/sbin:/sbin]

**Comment by littleswany** [comment]
@watty62 I was having a similar issue with an older codebase, are you using the most up to date version?

**Comment by watty62** [comment]
Thanks @littleswany How can I tell my version? I will check. Thanks!

**Comment by littleswany** [comment]
No worries. I'm not sure that you can at the moment.

@timgrossmann İt might be a good thing to include going forward?

**Comment by watty62** [comment]
@littleswany Running pip list it says: "instapy (0.1.dev0) "

If I run
>> sudo pip install instapy --upgrade 
will it upgrade?

Ian

**Comment by littleswany** [comment]
İt might but i don't think it will as we have not got that setup yet i don't think.

How did you install it in the first place and what platform are you on?@

**Comment by timgrossmann** [comment]
@watty62 No you have to do:

```bash
git pull
```

In the directory of InstaPy

**Comment by watty62** [comment]
That worked @timgrossmann (Thanks too @littleswany ).

The git pull updated the application. 

The script ran. 

I'd limited the number of likes to 10 to test the script. 

I used:
>>  .like_by_tags(['tv_depthoffield', 'europe_bnw'], amount=10)\ 
as these two tags are ones which should reflect on my own account well. 

But I noticed that I got repeated messages: 

-->  Image not liked: Inappropriate

The summary at the conclusion was: 
Liked: 1
Already Liked: 0
Inappropriate: 19
Commented: 0
Followed: 0

Session ended
-------------

** of the 19 'inappropriate' ones, 1 was my own image - which it flagged as 'username' and the other 18 were supposedly inappropriate images. Looking at them manually none were what I would call inappropriate. **

Another step forward.

Thanks

Ian

**Comment by timgrossmann** [comment]
@watty62 
Please post your quickstart.py setup

Inappropriate comes from the `dont_like`method 😉

**Comment by watty62** [comment]
Ah. Ok @timgrossmann 

I think we should close this issue - as the original purpose is served. I will have a look at the don't_like method and make changes, and test again. 

If there continues to be a problem I will raise a new issue. 

Many thanks

Ian
