### ISSUE TITLE
InstaPy instance has no attribute 'set_upper_follower_count'

### ISSUE THREAD

**Issue by aku6640** [InstaPy/InstaPy#1941]
## Current Behavior

Traceback (most recent call last):
  File "custom.py", line 20, in job
    session.set_upper_follower_count(limit=3000)
AttributeError: InstaPy instance has no attribute 'set_upper_follower_count'

I am getting this error, had no prior issues with this?

**Comment by uluQulu** [comment]
hi @ahmetu66,
It is obvious to state that your quickstart script (or **custom.py**) is using deprecated feature(s).
**Recently**, `set_upper_follower_count` and `set_lower_follower_count` features **are replaced** with **more enhanced** version: `set_relationship_bounds` feature,
```powershell
session.set_relationship_bounds(enabled=True,
			 potency_ratio=-1.21,
			  delimit_by_numbers=True,
			   max_followers=4590,
			    max_following=5555,
			     min_followers=45,
			      min_following=77)
```
_Just **make sure** your InstaPy files are up-to-date and you use the new feature in your quickstart scripts._
>See README **for** detailed usage of the `set_relationship_bounds` feature.

**Comment by aku6640** [comment]
working now, thank you!

When I git pull, it will not update the code automatically, because I have named it different. Is it recommended to use quickstart.py as the script name for future updates?

**Comment by uluQulu** [comment]
@ahmetu66,
Actually `git` is a little bit sophisticated tool, but worths mastering.
Early days I started using InstaPy, I used customized names instead of `quickstart` word but with the course of time I see that it reeally does not matter at all, oppositely being familiar with the term `quickstart` makes easier to cooperate with other folks using the project, it is a nice term who thought of...
_Personally I got one main quickstart script called **quickstart_new_design.py** and it keeps all of my customizations and I always keep **quickstart.py** file untouched for the ease of merging from master._

**Comment by joanroig** [comment]
Hi @uluQulu, is there any way to disable this `set_relationship_bounds` completely? It seems to run as default, but if I try to put it into my code and set it to `enabled=False` it runs as when it is set to true saying:

`Image not liked: uluQulu is not a potential user with the relationship ratio of 1.0`

**Comment by uluQulu** [comment]
Hi @joanroig,
you're a good catcher 😉
Yes, actually, it was a logical misbehavior and was my mistake but I realized it late and then included its _small_ fix inside #1919. 
For now, you can simply apply the affected lines in #1919:
![changed lines](https://user-images.githubusercontent.com/33269249/39575570-19e0deb6-4eec-11e8-86af-8b43ab8fa94e.png)
> Also, without modifying any bit, if you give `enabled=True, potency_ratio=None, delimit_by_nubers=False`, then it will deactivate, too).  
But after the #1919 merge, you will simply use `enabled=False` to deactivate it.

**Comment by joanroig** [comment]
@uluQulu awesome, many thanks for the update!

**Comment by RteV** [comment]
Hi @uluQulu,

I can't get it right. I have the feeling it's related to this thread. 
Installed the latest versions of instapy and instapy gui.
I have this error:

InstaPy Process
Cookie file not found, creating cookie...

Error: INFO [2018-05-13 10:54:36] [My Insta Name] Session started - 2018-05-13 10:54:36
 WARNING [2018-05-13 10:54:36] [My Insta Name] Sorry, Record Activity is not working on Windows. We're working to fix this soon!
 INFO [2018-05-13 10:54:54] [My Insta Name] Logged in successfully!
 Traceback (most recent call last):
 File "quickstart.py", line 8, in <module>
 session.set_upper_follower_count(limit = 1250)
 AttributeError: 'InstaPy' object has no attribute 'set_upper_follower_count'
 Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x05C09AB0>>
 Traceback (most recent call last):
 File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 163, in __del__
 File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 139, in stop
 File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 110, in send_remote_shutdown_command
 ImportError: sys.meta_path is None, Python is likely shutting down
InstaPy ended Stop  

Can you help me with that?

**Comment by uluQulu** [comment]
Hi @RteV,
First solve this,
>Traceback (most recent call last):
File "quickstart.py", line 8, in 
session.set_upper_follower_count(limit = 1250)
AttributeError: 'InstaPy' object has no attribute 'set_upper_follower_count'

_your quickstart script seems to have a piece of old feature_
Get rid of deprecated features (`set_upper_follower_count` and `set_lower_follower_count`) and use `set_relationship_bounds` (see README)

**Comment by RteV** [comment]
thanks, @uluQulu! Not so easy to try it though, every time I start Instapy GUI it overwrites the handmade changes in quickstart.py.
Without the option Upper Count and Lower Count in Following Parameter the GUI works for about an hour or so, than it breaks down and has the same error code.

I'm gonna try several ways to make the changes, if you have the shortcut than I will be happy to  hear about it too :-)

PS. Sorry for incidentally removing my first post

**Comment by uluQulu** [comment]
Welcome, @RteV,
I understand now, GUI tool works with pre-defined parameters, well you can change that parameter inside it's source code.
_But I would recommend you using handmade **quickstart.py** xD_
Write your own quickstart and start it through console! It is the way you can get the best out of InstaPy.
* Hint: Start by getting the list of all available features (_**set**tings and **act**ions_) and then categorise them according to the priorities. After it, select the most useful features you want and then write them down in a quickstart file to get started.
> See the definitions (_starts with `def`_) in **instapy.py** file to see all of the available features you can use..
