### ISSUE TITLE
Error after update ( Like by location )

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#1946]
Traceback (most recent call last):
  File "john.py", line 42, in <module>
    session.like_by_locations(['6889842'], amount=10)
  File "/Users/jonathanverdier/Desktop/InstaPy/instapy/instapy.py", line 658, in like_by_locations
    self.logger)
  File "/Users/jonathanverdier/Desktop/InstaPy/instapy/like_util.py", line 461, in check_link
    media = post_page['media']
TypeError: list indices must be integers or slices, not str

**Comment by uluQulu** [comment]
hi @johnvfitness,
Follow #1936 for that issue, it is already solved there and I guess is merged, too.

**Comment by johnvfitness** [comment]
hi @uluQulu I do not see where is the solution

**Comment by uluQulu** [comment]
@johnvfitness,
This comment includes the generic solution by @joanroig :  
https://github.com/timgrossmann/InstaPy/issues/1936#issuecomment-385815295
>_also read the comments at bottom which explains some stuff_

Have you pulled the latest commits from `master`? _It should work fine_..

**Comment by ogerasymenko** [comment]
Have same error :
Traceback (most recent call last):
  File "insta.py", line 26, in <module>
    session.like_by_tags(['#test'], amount=5, media='Photo')
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 960, in like_by_tags
    self.logger)
  File "/usr/local/lib/python3.5/dist-packages/instapy/like_util.py", line 461, in check_link
    media = post_page['media']
TypeError: list indices must be integers or slices, not str

Version:
commit 339680f48f1f2b69dde110ad173857596478a9f6
Merge: d81705b de9117d
Author: Tim Grossmann
Date:   Wed May 2 17:03:50 2018 +0200
    Merge pull request #1939 from CharlesCCC/master
    Additional Fix the issue that cant get followed by count

**Comment by craigricker** [comment]
@uluQulu I think this is a separate issue than #1396 . I pulled from master this morning, and am also having this issue.

**Comment by uluQulu** [comment]
Hey guys, after @ogerasymenko's accurate feedback, I rechecked again and it is the same situation as stated in here: https://github.com/timgrossmann/InstaPy/issues/1936#issuecomment-385836821
For the current situation, the commit #1940 should be reverted back.
You can manually revert those lines yourselves, you will just add back `[0]` in all `ProfilePage`, `PostPage` and `post_page` queries as in this [sheet](https://github.com/timgrossmann/InstaPy/pull/1940/files)
So, they will be, `ProfilePage[0]`, `PostPage[0]` and `post_page[0]`.

>Hey @timgrossmann, #1940 seems to need a revertback
@craigricker, of course, I wrote #1936 but not #1396 🙂
_@johnvfitness, apart from @ogerasymenko's report, have you pulled latest commit of #1940, if not, then you should not see any problems as of now_

**Comment by johnvfitness** [comment]
Thx @uluQulu its good bro :)

**Comment by samrap** [comment]
@uluQulu Looks like your solution works if I keep `post_page` as is (not adding `post_page[0]`).

**Comment by ghost** [comment]
@uluQulu after removing post_page[0] it works. maybe post this on the issues page. so people can find easier.
