### ISSUE TITLE
Help please.I whas put new update quickstart.py and have error(object has no attribute)

### ISSUE THREAD

**Issue by webdesignkorenjak** [InstaPy/InstaPy#1947]
I whas change the old quickstart.py with new one updated ( 	Replaced deprecated feature with new in sample quickstart scripts ) and have a error (Object has no attribute Set_relationship_bounds).Do I have to upload more files???
![screenshot_7](https://user-images.githubusercontent.com/37159896/39537614-6baf421c-4e3a-11e8-9f36-44636ab90258.png)

**Comment by uluQulu** [comment]
hi @webdesignkorenjak,
Yes, you must get the updated InstaPy files which included that _feature enhancement_, just do `git pull master` or re-download repository.

**Comment by webdesignkorenjak** [comment]
Thank you,I see you have a loot of working with new instagram change with post0. I dont wont to mass my instapy.Is it ok to download repository and change my instapy files with new one copy and paste.Or i have to install?which is the simplest way to do this.Thank you in advance because I seeing that you have a lot of work.

**Comment by uluQulu** [comment]
My pleasure, @webdesignkorenjak,
Did you **mean**, you have your personal modifications in your **instapy** core files, so that you don't want to merge it with `master`?
**OR** it is difficult to you to apply the latest changes in **instapy** files to your existing ones?

> having the latest version of files is always better

**Comment by webdesignkorenjak** [comment]
![screenshot_1](https://user-images.githubusercontent.com/37159896/39539740-c64cc6bc-4e40-11e8-8467-0682e3453fc0.png)
No i dont have personal modifications,but I've changed so many times because of the errors It all made me confused.I always have a problem error From instapy import instapy when i download your latest update files of instapy.Must be in the same directori like Python or what?  I've read your instructions in detail for installation several times but confused.When i download your zip files where i must put theme?

**Comment by webdesignkorenjak** [comment]
How do i make git pull master,from windows comand prompt or i must use a paython ?

**Comment by uluQulu** [comment]
It's clear now, @webdesignkorenjak,
For you, modifications will be very easy. Just download full InstaPy repo and replace it with yours.
Just make sure to copy your customized quickstart script (_or other data files if you have_) to other location and after updating entire folder with new ones, then paste back your old (customized) quickstart script.

I am also a Windows user, if you want the ease of updating Github repositories without fuss, just download Github's desktop app and clone the InstaPy repo to there. The app will automatically update your InstaPy files in a button click!  
> Feel free to ask me for further help, it is very easy!

**Comment by webdesignkorenjak** [comment]
Thank you @uluQulu appreciate your work

**Comment by webdesignkorenjak** [comment]
I get again the error 
![screenshot_2](https://user-images.githubusercontent.com/37159896/39544781-741fdd02-4e4f-11e8-92b2-2d4de3bc9aff.png)

**Comment by uluQulu** [comment]
@webdesignkorenjak,
_Requests is not a built in module (does not come with the default python installation), so you will have to install it._
in command prompt, run:
```powershell
pip install requests
```
> requests is imported in **instapy.py** to be used with _clarifai_

I think we should add `requests` module to [requirements.txt](https://github.com/timgrossmann/InstaPy/blob/master/requirements.txt), cos people don't know it should also be downloaded...
Maybe you can PR that change, eh?

**Comment by webdesignkorenjak** [comment]
Working like a charm,thanks @uluQulu you are the king.Oll the best for you,chao closing
