### ISSUE TITLE
Instagram asks for verification every time, deployed on Azure

### ISSUE THREAD

**Issue by amitbend** [InstaPy/InstaPy#195]
Hi,
I deployed a simple instance on an Azure cloud VM.
enabled the `nogui` option, and every time i try to run instagram asks me to verify my account *every time*.

Did anyone had a similar issue? what could be the fix for it?

**Comment by tibor** [comment]
Hi,

I had the same problem on my VPS.
Try my solution mentioned in #181.

Kind regards

Tibor

**Comment by eduardocalazansjr** [comment]
1 - Don't login your account in another region of the world
2 - Don't abuse of this script
3 - If your account is flagged (verify account/change pwd/another stuff) STOP using if for a while, it will lead you to a hard-ban.
4 - If your account is a business or verified account, the #181 won't work, the code changes on every page request.

**Comment by tibor** [comment]
4 - That’s not true. I’ve got a business account and the code stays the same.

**Comment by eduardocalazansjr** [comment]
Tested NOW with three accounts, just one doesn't change.
Original logged app: BR
Script region: West EU

**Comment by tibor** [comment]
Okay, so it may not work in all cases. For me, it worked without any problem.
Located in: Austria
Script region: Germany (but Instagram recognizes it as UK)

**Comment by timgrossmann** [comment]
I got this with the first run on the server because I, stupidly, used a NYC server...
But after the first click on the approve button it never appears again
