### ISSUE TITLE
TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by thankmelater23** [InstaPy/InstaPy#1952]
$ python /Users/AndreVillanueva_Com/Dropbox/Bots/InstaPy/belize-lottery.py
INFO [2018-05-02 22:29:59] [belize_lottery]  Session started - 2018-05-02 22:29:59
INFO [2018-05-02 22:30:30] [belize_lottery]  Logged in successfully!
INFO [2018-05-02 22:30:40] [belize_lottery]  Getting active users who liked the latest 10 posts:
  ~collecting the usernames from posts with the boundary of 500

INFO [2018-05-02 22:30:55] [belize_lottery]  Post 1  |  Likers: found 37, catched 12
INFO [2018-05-02 22:31:16] [belize_lottery]  Post 2  |  Likers: found 37, catched 12
INFO [2018-05-02 22:32:36] [belize_lottery]  Post 4  |  Likers: found 26, catched 12
INFO [2018-05-02 22:32:57] [belize_lottery]  Post 5  |  Likers: found 13, catched 12
INFO [2018-05-02 22:33:30] [belize_lottery]  Post 6  |  Likers: found 9, catched 9
INFO [2018-05-02 22:35:02] [belize_lottery]  Post 8  |  Likers: found 10, catched 10
INFO [2018-05-02 22:35:35] [belize_lottery]  Post 9  |  Likers: found 4, catched 4
INFO [2018-05-02 22:36:08] [belize_lottery]  Post 10  |  Likers: found 2, catched 2
INFO [2018-05-02 22:36:10] [belize_lottery]  Gathered total of 36 unique active followers from the latest 10 posts in 5 minutes and 29 seconds
INFO [2018-05-02 22:36:10] [belize_lottery]  Location [1/8]
INFO [2018-05-02 22:36:10] [belize_lottery]  --> 227402338/belize-city-belize
INFO [2018-05-02 22:36:23] [belize_lottery]  [1/5]
INFO [2018-05-02 22:36:23] [belize_lottery]  https://www.instagram.com/p/BiTaHx0HRos/?taken-at=227402338
Traceback (most recent call last):
  File "/Users/AndreVillanueva_Com/Dropbox/Bots/InstaPy/belize-lottery.py", line 154, in <module>
    session.comment_by_locations(belizeLocation, amount=5, skip_top_posts=True)
  File "/Users/AndreVillanueva_Com/Dropbox/Bots/InstaPy/instapy/instapy.py", line 806, in comment_by_locations
    self.logger)
  File "/Users/AndreVillanueva_Com/Dropbox/Bots/InstaPy/instapy/like_util.py", line 461, in check_link
    media = post_page['media']
TypeError: list indices must be integers, not str
INFO [2018-05-02 22:36:26] [belize_lottery]  Session ended - 2018-05-02 22:36:26
INFO [2018-05-02 22:36:26] [belize_lottery]  --------------------

**Comment by ceribbo** [comment]
same error here

**Comment by Rendiere** [comment]
+1

**Comment by Nocturnal-2** [comment]
Please check [#1946 (comment)](https://github.com/timgrossmann/InstaPy/issues/1946#issuecomment-386116515) for solution

**Comment by agcty** [comment]
same here

**Comment by SummitKaiju** [comment]
Same!

**Comment by austinbeauch** [comment]
+1
