### ISSUE TITLE
('unable to get followers and following information \n', "'data'")

### ISSUE THREAD

**Issue by pablodalma93** [InstaPy/InstaPy#1955]
## Expected Behavior
Get Followers

## Current Behavior
('unable to get followers and following information \n', "'data'")
Error {"message": "rate limited", "status": "fail"}

## InstaPy configuration
from instapy import InstaPy

session = InstaPy(username='username', password='password')

session.login()

session.set_dont_include(['userwhatever'])

session.unfollow_users(amount=1000,onlyNotFollowMe=True)

**Comment by uluQulu** [comment]
Hi @pablodalma93,
I think it's the result of querying with old graphql endpoints.  
Try pulling latest commits.
> If it still not works, post the **full** error output from the console, I will help.
