### ISSUE TITLE
Follow_user_likers flaws: broken followed count/No sleep delays

### ISSUE THREAD

**Issue by jeremycjang** [InstaPy/InstaPy#1956]
I created a program using the new ```follow_user_likers``` function and observed two issues.

1. There are currently no sleep delays in the function. ```follower_user_followers``` sleeps after every 10 follows by default to avoid going over Instagram's rate limit. I believe this code can be used in ```follow_user_likers``` as well.

2. The ```followed``` count is not working (no ++?). After the program followed multiple accounts, the count remained at 1. This is dangerous because even if issue 1 is remediated, issue 2 will prevent it from working.

Program log example, observe the "Followed" number:

```
INFO [2018-05-03 08:20:26] [username]  --> robertflores83 instagram account is opened...
INFO [2018-05-03 08:20:39] [username]  ---> Now following: robertflores83
INFO [2018-05-03 08:20:39] [username]  --> robertflores83 added to blacklist for follow campaign (action: followed)
INFO [2018-05-03 08:20:42] [username]  Followed: 1
INFO [2018-05-03 08:20:49] [username]  --> cesarnabu instagram account is opened...
INFO [2018-05-03 08:21:07] [username]  ---> Now following: cesarnabu
INFO [2018-05-03 08:21:07] [username]  --> cesarnabu added to blacklist for follow campaign (action: followed)
INFO [2018-05-03 08:21:09] [username]  Followed: 1

```

I saw the code master @uluQulu is back; any thoughts?

**Comment by uluQulu** [comment]
Hey @jeremyccheung,
I have not used that feature ever,
if you write down:
1. What you want to do?
2. What you have done to achieve it?
3. What help do you need?

_it's just a word flow, we can make it work!_ 🙂 _with a good cup of tea_ ☕

**Comment by jeremycjang** [comment]
@uluQulu sounds awesome!

To answer your questions,

1. I want to follow 100 users of the two most recent photos on two accounts (follow 400 total), but want to do so while paced within Instagram’s rate limits 

2. This is my current code: ```session.follow_user_likers(['user1' , 'user2'], photos_grab_amount=2, follow_likers_per_photo=15, randomize=False)```, was planning to modify the base code to use the sleep for 10 mins function of the other code, but haven't done so yet

3. I need help in finding a good way to integrate it. when testing this new function using a safe follow number (15 names from each picture so 60 total) I noticed that the program also does not do the like/comment part of a user interaction, so am leaning towards abandoning this function altogether but it would still be good to figure out to make the program more complete!

**Comment by uluQulu** [comment]
hi @jeremyccheung,
Your requests are ready, but we must make a design choice:
**1**. Would you like to keep current operation mechanism of `follow_user_likers` which does get a user list from a username and then follows those people, and then **continues** with the next username...?
**2**. Or you would like to get entire user lists of all usernames and only after then **start** following?
* _2nd version's difference is **lots of** simplicity, **less** mess and a big advantage of having only one **break time** handler (_1st version needs **3** handlers_)._

**Comment by uluQulu** [comment]
@jeremyccheung,
I've decided not to change that mechanism.
You can see the code at #1981.

**Comment by jeremycjang** [comment]
@uluQulu Thank you so much for all your work! I re-opened this issue after testing; please refer to my observations in my reply to #1981 !
