### ISSUE TITLE
Like feed no working

### ISSUE THREAD

**Issue by westworldcj** [InstaPy/InstaPy#1958]
Issue with liking my own feed
## Expected Behavior
I am trying to run this here
session.like_by_feed(amount=100, randomize=True, unfollow=True, interact=True)
## Current Behavior
seems that it logs in and then session ends. no error codes
## InstaPy configuration
christophers-MacBook-Pro:instapy-master christophergore$ python likefeed.py
INFO [2018-05-03 11:31:56] [scatpackchrisjames]  Session started - 2018-05-03 11:31:56
INFO [2018-05-03 11:32:26] [scatpackchrisjames]  Logged in successfully!
INFO [2018-05-03 11:32:27] [scatpackchrisjames]  Session ended - 2018-05-03 11:32:27
INFO [2018-05-03 11:32:27] [scatpackchrisjames]  --------------------

christophers-MacBook-Pro:instapy-master christophergore$

**Comment by uluQulu** [comment]
hi @westworldcj,
_put that line into a try/except block and raise the exception occurred, so that we can find the problem_:
```python
# some lines from quickstart script

try:
    session.like_by_feed(amount=100, randomize=True, unfollow=True, interact=True)
except:
    raise

# some other lines
```
then post the full console output containing crash information

**Comment by westworldcj** [comment]
Do i need to add something after the except:  ? I do this try and except block and it does not seem to be pulling anything into the console

**Comment by wizel10** [comment]
@uluQulu I've had similar issue. iI is not a crash, it just ends normally after a few seconds but with no likes to the feed.

**Comment by uluQulu** [comment]
@westworldcj,
Right, if there is no exception occurs then it means you're running an old version of InstaPy which had this issue. _(it was solved lately)_
Try pulling latest commits, if the issue persists, just ask me again.

**Comment by uluQulu** [comment]
@westworldcj, I've checked myself and it did not work either with the latest files.  
Then I saw @wizel10's [post](https://github.com/timgrossmann/InstaPy/issues/1936#issuecomment-386386684) and it seems working, so apply it:
in **instapy.py** file, find and **replace**:
```python
self.like_by_feed_generator(**kwargs)
return self
```
**with**
```python
for i in self.like_by_feed_generator(**kwargs):
    pass
return self
```

**Comment by westworldcj** [comment]
Thank you very much. that worked! odd. I had researched the past issues and found that and thought I changed that but its working again. Thanks!

**Comment by uluQulu** [comment]
Welcome, @westworldcj, that's right, a bit of consufion :D
I've investigated further and found the cause.
Well, that issue was solved with #1782.
A few days after it, #1682 did (_mistakenly_) overwrite that fix to replace with old line.
##### So it is what causing confusion :)
I've just opened another PR- #1960, for returning back #1782.

_Thanks to @wizel10, otherwise I would hardly realize that #1782 was mistakenly overwriten.._

**Comment by sionking** [comment]
@uluQulu  you are amazing, your control over github and your comments are a big pleasure to read !

**Comment by uluQulu** [comment]
I am impressed! @sionking,
_since you've got a huge share in my quick **start** at this project where I started by using datetime tips in your easy pickle tool to design QS when I literally had no knowledge off python_ :D
##### I also want to thank you publicly for your hard work and dedication on this project!!
Keep it up! 🏇🏼

**Comment by eddyizm** [comment]
Another thanks. My fork was almost 300 commits behind so I updated all the commits but for some reason this part was still no working after fixing all my bugs. Thanks again to @uluQulu !
