### ISSUE TITLE
Instagram reseted the password of my Instagram Account

### ISSUE THREAD

**Issue by marudon** [InstaPy/InstaPy#196]
After quite intensiv use of InstaPy, Instagram reseted the password of my Instagram Account.
This was quite scary, are there any experiences about that problem ?

After editing a new Password,  I could go on in Instagram, but maybe it was a warn signal?

Unfortunately I can't say how many likes/comments I posted in what time with InstaPy as there is no session summary

**Comment by littleswany** [comment]
@marudon I think you have answered your own question, intensive usage will bring up warning flags with IG.

The limit for the number of likes is 300 an hour.

If you check the logFile.txt in the logs folder you will be able to find out the number of interactions.

**Comment by eduardocalazansjr** [comment]
You're now flagged.
If you continue with abusive use of the script, you will lead to an soft-ban/hard-ban.

@littleswany weird, i passed the 300/hour and nothing happened, but with other account got flagged with 50 comments.

**Comment by littleswany** [comment]
@vlntdds Interesting. I keep meaning to create some accounts and just test them to the limits because at the moment I am just working off what I have seen on the internet. Did you reach an upper limit for the number of likes?

**Comment by eduardocalazansjr** [comment]
I'm testing that right now, mixing login locations and checking the accounts original users habits.
For now one thing is right: the values for ban is not precise, it depends of the account behaviour before the ban flag.

**Comment by marudon** [comment]
I've heard to advise not to post more than 1000 likes or comments (or likes and comments alltogether?) per day. 

Does day means 24 following hours or from 0:00 A.M. to 0:00 A.M. ?

New Feature:
It is hard to configure the script to a certain or max. number of posts as you loose posts when the follower range is not matched (only way to range from 0 to endless number ..
So it would be nice to have a **Max Post Counter** so InstaPy stops working when you reach your upper wish border.

**Comment by marudon** [comment]
what are the exact meanings of soft-ban and hard-ban?

**Comment by eduardocalazansjr** [comment]
Soft-ban: the like and comments Will not work (but appears to, the heart icon gets red)
Hard-ban: on a soft-ban, If you keep doing likes, your account gets locked/deleted.

**Comment by eduardocalazansjr** [comment]
There's already an issue for that, like @littleswany mentioned.
Closing that for duplicate.
