### ISSUE TITLE
Unable to access media key - exception

### ISSUE THREAD

**Issue by lvkins** [InstaPy/InstaPy#1961]
## Current Behavior

After a fresh pull, InstaPy throwing an exception as soon as it comes to posts interaction.
Using Python 3.5.3

> Traceback (most recent call last):
>   File "./quickstart.py", line 76, in <module>
>     session.like_by_tags(['hike', 'ride', 'mountains'], amount=20)
>   File "/InstaPy/instapy/instapy.py", line 1008, in like_by_tags
>     self.logger)
>   File "/InstaPy/instapy/like_util.py", line 461, in check_link
>     media = post_page['media']
> TypeError: list indices must be integers or slices, not str

## InstaPy configuration
Default

**Comment by lamepost** [comment]
clone this clone  https://github.com/joanroig/InstaPy 
see this https://github.com/timgrossmann/InstaPy/issues/1936

**Comment by lvkins** [comment]
Closing this issue then as it has been referenced.
