### ISSUE TITLE
TypeError: list indices must be integers or slices, not str [SOLVED]

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#1963]
To fix this error please manually revert these lines yourselves, you will just add back [0] in all ProfilePage, PostPage and post_page queries as in this [https://github.com/timgrossmann/InstaPy/pull/1940/files](url)
So, they will be, ProfilePage[0], PostPage[0].

credit for fix goes to @samrap @uluQulu

**Comment by samrap** [comment]
Just to clarify, **do not** add `[0]` back to `post_page`. Only `ProfilePage` and `PostPage` :)
