### ISSUE TITLE
Issue starting bot with feature

### ISSUE THREAD

**Issue by supmag** [InstaPy/InstaPy#1966]
## Expected Behavior
Normally the bot would follow the users image that it liked
## Current Behavior
I keep getting an error on the starting of the script with "Insufficient amount of tabs and spaces in session.set_do_follow(enabled=True, percentage=30)"
## Possible Solution (optional)
Can someone please post a working quickstart.py? Im really terrible at scripting and always have trouble trying to add features like unfollowing and following and taking breaks wtc in one session...
## InstaPy configuration
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = ''
insta_password = ''

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#   Settings.database_location = '/path/to/instapy.db'
#   Settings.chromedriver_location = '/path/to/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_do_follow(enabled=True, percentage=30)
	session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.21,
				  delimit_by_numbers=True,
				   max_followers=10000,
				    max_following=5555,
				     min_followers=80,
				      min_following=200)
    session.set_do_comment(False, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.like_by_tags(['photo', 'photography', 'photoshoot', 'model', 'fashion', 'fashionmodel', 'fashionphotography', 'fashionphotographer', 'canon', 'canonphotography', 'indoor', 'editorial', 'studio', 'studiophotography', 'grunge', 'highsnobiety', 'highsnob', 'fashionshoot', 'fashionweek', 'fashionista', 'editorial', 'retouch', 'retouching', 'retoucher', 'lightroom', 'highend', 'postproduction'], amount=60, media='Photo')

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

**Comment by DavidMolinari** [comment]
Simple advice, you have 27 hashtags, and an amount of 60 for each of them
27*60=1620 if everything matches you'll break IG limits

#### Based on your quickstart here is a working example tested on windows with headless_browser=False


> Put 'headless_browser=True' on a server



```python
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = ''
insta_password = ''


session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.21,
				  delimit_by_numbers=True,
				   max_followers=10000,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])
    session.set_do_follow(enabled=True, percentage=30, times=2)


    # actions
    session.like_by_tags(['your', 'list','of', 'tags'], amount=20)

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

```

**Comment by uluQulu** [comment]
Hey @supmag,
>I keep getting an error on the starting of the script with "Insufficient amount of tabs and spaces in session.set_do_follow(enabled=True, percentage=30)"

You have mixed tabs with spaces in your quickstart script which is what making problem.
_Just keep in mind that `python` is literally **based on** _indentation_ and it **allows** using **only** EITHER `tab`s **OR** `space`s for indentation **in a file**._ 
* _activate `see invisible characters` option in your text editor to see `tab`s and `space`s and then fix those conflicting lines_

**Comment by supmag** [comment]
@DavidMolinari Hey thanks for the file! unfortunately this is the file I already have, I just want to know how to add the feature that allows the bot to follow users from the liked images.
I was using the Gui before, however since the update the guick doesn't work anymore as it creates a new quick start file.
