### ISSUE TITLE
Potency_ration=None doesn't take effect

### ISSUE THREAD

**Issue by wizel10** [InstaPy/InstaPy#1968]
## Expected Behavior
    session.set_relationship_bounds(enabled=False,
				 potency_ratio=None,
				  delimit_by_numbers=True,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
Expected that setting  potency_ratio=None the ratio will not take effect giving likes to any picture independently of the ration between followers and following.
Considering max, min is OK.

## Current Behavior
Turning to None the potency ratio is still using a value to determine whether like or pass.
Looking at instapy/instapy.py there is a line that overwrites that setting:
Line #142 self.potency_ratio = 1.3466

## Possible Solution (optional)
        #self.potency_ratio = 1.3466
        self.potency_ratio = None

## InstaPy configuration
running in Linux.

**Comment by uluQulu** [comment]
hi @wizel10,
have you got the latest files?
paste `set_relationship_bounds` method inside `InstaPy` class, I will look

**Comment by wizel10** [comment]
@uluQulu thanks. Works fine with the latest files.
