### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by marudon** [InstaPy/InstaPy#197]
1: Safety Feature for a better ban control:
It is hard to configure the script to a maximun number of posts as you loose posts when the follower range is not matched (only way to confiure the range from 0 to an endless number ..)
So it would be nice to have a **Max Post Counter**. And InstaPy will stop working when it reaches your edited my post number.

2: Summary report
Summary log after sessions: number of posted likes, comments, following/unfollowing and in what time period

3: Match search for target followers 
Example: With the hashtag "model" you will also find users topmodel, fashionmodel, sexymodel etc.

4: New algorithm for target users:
Look for all users that liked or commented one of my photos/Videos, but do not yet follow me. 
So you find users that already recognized yourself, but forget or was not yet convinced to follow you .. then work with this user group

**Comment by littleswany** [comment]
Number 2 is being addressed by #143

**Comment by eduardocalazansjr** [comment]
1 - As i said in another issue, It depends of the user behaviour before the flag. An empty account will not pass 50 likes/hour, but an old account get 1k+.

2 - Already exists

4 - You can't get a list os follow/followers from other users on Instagram web.

**Comment by littleswany** [comment]
**Point 1**
Currently you can stipulate the number of posts you like by adding amount=x after the tags:

`.like_by_tags(['#photography'], amount=1) \`

**Point 2**
A summary report is given when the script is completed and is logged in the logFile.txt in the logs folder and the summary looks like this:

> Liked: 0
Already Liked: 1
Inappropriate: 0
Commented: 0
Followed: 0
Session ended - 2017-04-24 17:44:33

**Point 3**
This looks like something that could potentially be built into the follow utility with maybe something like tagMatch=true:

`session.set_do_follow(enabled=True, percentage=10, tagMatch=true)`

But I am not quite sure what the point of such a feature would be, could you explain a bit more?
**Point 4**
Again an interesting point, but I am not sure I see the point as like you say that user has already interacted with you

**Comment by Albertmoiseev** [comment]
4. - I think it would be more beneficial to add a scaper which scapers all the followers from a given account/accounts.

However, it is not easy to do this feauture )

**Comment by timgrossmann** [comment]
@Albertmoiseev 

> 4 - You can't get a list os follow/followers from other users on Instagram web.

**Comment by Albertmoiseev** [comment]
@timgrossmann 
Tim, hi.  Well, It's possible. 

However, I am working on some issues. 

The first approach is just to open instagram.com/account/followers/ with selenium and scrape all the users and scroll down the page - then scrape again and scroll down. Then, go over this loop until the end. 

I have coded the script which does the scraping process. However, need to think what to do with the scrolling. If an account has hundreds of followers - it would be fine, but if an account has thousands of followers - it would be the issue due to the looong runtime.

The second approach would be to work with requests directly and getting json from instagram servers. Unfortunately, I haven't yet managed to find the sufficient amount of time to research i.  If somebody would help - it will be very appreciated )

Anyway, I'll try to deliver this feature. Looking forward to the discussion or some help with the implementation of this feature. )

**Comment by timgrossmann** [comment]
@Albertmoiseev I think we lost track of the actual idea...

> Look for all users that liked or commented one of my photos/Videos, but do not yet follow me.
So you find users that already recognized yourself, but forget or was not yet convinced to follow you .. then work with this user group

This is not possible. You can't click on the `1xxx Likes` and check who liked the picture with the web interface

**Comment by eduardocalazansjr** [comment]
> Tim, hi. Well, It's possible.

From other users isn't possible, just for your account, and it's a kinda of heavy work for nothing.

> The second approach would be to work with requests directly and getting json from instagram servers. Unfortunately, I haven't yet managed to find the sufficient amount of time to research i. If somebody would help - it will be very appreciated )

The API has a request limit, needs an authkey and it's easy to detect an "abuse" with that.

> The first approach is just to open instagram.com/account/followers/ with selenium and scrape all the users and scroll down the page - then scrape again and scroll down. Then, go over this loop until the end.

You get your followers, in a horrible way, also in instagram web you can't see WHO liked your picture. Seems like a useless data mining.

**Comment by Albertmoiseev** [comment]
@timgrossmann @vlntdds  That is true, it is not possible to click on the 1xxx Likes and check who liked the picture with the web interface.

However, I was talking about another feature - scrape the followers of a given account (it's could be a good targeting) and then follow those users. It can give a good follow back ratio. And this feature is also implemented in such social media tools as mass planner and followliker.

@timgrossmann  please, clarify this point for me - does the aforementioned feature aligns with your product vision?) If not, i'll just switch for other issues or features )

**Comment by eduardocalazansjr** [comment]
> However, I was talking about another feature - scrape the followers of a given account (it's could be a good targeting) and then follow those users.

But you can only scrape YOUR followers, not OTHER accounts followers.

Edit: it only works in some personal accounts, verified accounts the "Followers/Following" information is not interactable. Also, the link informed here leads to nowhere, but the profile page.

Also, like some other researches, mining all this data and FOLLOWING this accounts would lead you to a possible ban.

Thinking in a ban-avoid way, the script will have the work of checking ALL your followers (seems a weird waste of time) and check other profiles followers (if your account have this feature) (and also seems a lot of waste of time, again) and compare those, for following 5 or 10 profiles/hour?

**Comment by timgrossmann** [comment]
@Albertmoiseev if you're developing this feature, I'll be happy to see how and if this works.
Especially, what follow back ratio you could get with this approach.

Like @vlntdds mentions, you have to handle these edge cases (verified profile) and so on.

If you think people will like this feature, give it a go. We'll see where this is going!

**Comment by generalu** [comment]
This was actually a feature I was hoping would get developed. In the meantime, I found an unconventional way to scrape another users list, then use the follow_by_list command to follow.
- Go to Piknu dot com (Instagram web viewer) then find users following list.
- Install WebScraper (Chrome extension) and create appropriate session per tutorial. Then Scrape. You may not be able to get the entire list (if thousands - max I got was ~7,500).
- Remove @, Concatenate, transpose, etc. in Excel to create a string that can be pasted directly into the follow_by_list command. 

A quick hack that works for me as I don't follow more than 10-100 users at a time.
