### ISSUE TITLE
Requesting feature! really simple but affective

### ISSUE THREAD

**Issue by supmag** [InstaPy/InstaPy#1973]
## Expected Behavior
Randomise custom comments efficiently
## Current Behavior
currently no mater how many comments you type in the feature it will most likley use the same comment up to 5 times before using a new one
## Possible Solution (optional)
Make it so it doesnt use the same comment that was posted before to fast...this way we can make a list of 40-50 custom comments without being afraid of being shadow ban...which has happened to me on multiple occasions using the commenting feature

**Comment by lvkins** [comment]
It doesn't really matter what you comment, it matters *how* you comment.
Like real people mostly comment with heart emoji, and its not being considered as spam.

Anyways, can do.

**Comment by supmag** [comment]
The commenting feature brings in massive engagement more than liking or following...if you are really smart about what you say targeted towards the niche...it works like a charm

**Comment by lvkins** [comment]
> The commenting feature brings in massive engagement more than liking or following

Agreed, but here we speak about posting the same comment twice. You will be fine with the current functionality as long as you won't post same comment twice to the same person. It really depends on how big is your target group. If it's big enough (and it should be) to not hit the same person twice it's fine. Otherwise the feature you requested could be useful.

**Comment by uluQulu** [comment]
@pompex,
Multi-commenting a content on the same user is really disturbing, I've had this in mind to solve, I will look again if gets free time.
I mean it's not a problem for @supmag's idea which is also great and easy to do (_and **must** be done_) but I had something more exiciting in mind:
Well sometimes we can't **write** down hundreds of unique comments but we can generate unique emoji sets for the same content, so it would look alright xD
"_This is a comment👍🏆_"
"_This is a comment👌👌👌👌📸_"
"_🤸‍♂️This is a comment_"
"_This is a 🖐👆😎☕comment💯_"
* kind of unique emoji generator, also we can add `mood` parameter to set emojis for that, e.g.(`mood='sad'` or `mood='chill'`)

That idea will work on **all** `not-too specific` comments.
_What do you say?_

**Comment by lvkins** [comment]
Comment customization is a good idea. I'd say, anything that would help make a bot to behave more natural is a good thing in general. 

The idea you provided is fairly simple and can be done within the configuration file so you don't have to dive into the InstaPy files, for example:

```
from random import choice
from random import randint

emojis = ['😀', '💪', '👌', '😌', '👽']
emojisCount = 1, 5 # Min, max
comments = [
  'My comment {}',
  'My {} comment'
]

parsed = [_.format(choice(emojis) * randint(*emojisCount)) for _ in comments]

session.set_comments(parsed)
```

See: https://repl.it/repls/WoefulMundaneAggregators

For each run, you will be having unique comments with random emojis.

**Comment by uluQulu** [comment]
@pompex,
that's right, but I want to implement it inside commenting engine and all we would do is just set a parameter rather than choosing emojis each time, randomizing them,,... not many people can do that manually from quickstarts..
e.g.,
```python
set_comments(comments=['Nice pic'], eomjize=True, emojizing_mood='cool', media='Photo')
```
_anyways, guys I don't think it's a good idea cos lots of my comments are a bit specific_
good luck!

**Comment by supmag** [comment]
I think someone misunderstood, the bot is likely to post the same comment more than a few times...not on the same user but in general...emoji comments are a bit useless as they don't really bring in that much engagement.

I want to make a huge list of custom comments and for the bot to randomize it so that it knows no tto post the comment it just posted again for a while...

**Comment by supmag** [comment]
I'm ripping my hair out, Ive tried everything almost and its still giving me this error

https://gyazo.com/e9eea657c903103299a278bdaf940186

________________________________

**Comment by Shotkikk** [comment]
Try to add this function to Your quickstart.py:
`def generate_comments_from_patterns(
        patterns=None,
        amount=10
):
    rendered_comments = []
    build_comment = ""
    patterns = patterns or []

    for i in range(amount):
        random_patterns_table_index = random.randint(0, (len(patterns) - 1))
        selected_pattern = patterns[random_patterns_table_index]
        for row in selected_pattern:
            build_comment += row[random.randint(0, (len(row) - 1))]
        rendered_comments.append(build_comment)
        build_comment = ""

    return rendered_comments`

Then use it within ".set_comments" function like this:
`session.set_comments(generate_comments_from_patterns(patterns=comment_patterns, amount=30))`

From now on You just need to add array with comments under username / password  declaration:
`comment_patterns = [
    [
        ["That's ", "It's "],
        ['beautiful', 'brilliant', 'epic', 'perfect', 'great', 'good', 'cool', 'amazing', 'magnificent', 'magical',
         'lovely', 'glorious', 'excellent', 'masterful', 'unique'],
        [' @{}'],
        ['.', '!', '! :smile:', ' :satisfied:', ' :blush:', ' :smile:', ' :wink:', ' :yum:']
    ],
    [
        ['Like it :stuck_out_tongue:', 'I like it', 'Good work! :open_mouth:', ':heart:']
    ]
]`

**Comment by Shotkikk** [comment]
Try to add this function to Your quickstart.py:
`
def generate_comments_from_patterns(patterns=None,amount=10):
    rendered_comments = []
    build_comment = ""
    patterns = patterns or []

    for i in range(amount):
        random_patterns_table_index = random.randint(0, (len(patterns) - 1))
        selected_pattern = patterns[random_patterns_table_index]
        for row in selected_pattern:
            build_comment += row[random.randint(0, (len(row) - 1))]
        rendered_comments.append(build_comment)
        build_comment = ""

    return rendered_comments
`

Then use it within ".set_comments" function like this:
`session.set_comments(generate_comments_from_patterns(patterns=comment_patterns, amount=30))`

From now on You just need to add array with comments under username / password  declaration:
`comment_patterns = [
    [
        ["That's ", "It's "],
        ['beautiful', 'brilliant', 'epic', 'perfect', 'great', 'good', 'cool', 'amazing', 'magnificent', 'magical',
         'lovely', 'glorious', 'excellent', 'masterful', 'unique'],
        [' @{}'],
        ['.', '!', '! :smile:', ' :satisfied:', ' :blush:', ' :smile:', ' :wink:', ' :yum:']
    ],
    [
        ['Like it :stuck_out_tongue:', 'I like it', 'Good work! :open_mouth:', ':heart:']
    ]
]`

**Comment by kacpermaciejevvski** [comment]
Try to add this function to Your quickstart.py:

    def generate_comments_from_patterns(patterns=None,amount=10):
        rendered_comments = []
        build_comment = ""
        patterns = patterns or []

        for i in range(amount):
            random_patterns_table_index = random.randint(0, (len(patterns) - 1))
            selected_pattern = patterns[random_patterns_table_index]
            for row in selected_pattern:
                build_comment += row[random.randint(0, (len(row) - 1))]
            rendered_comments.append(build_comment)
            build_comment = ""

        return rendered_comments


Then use it within ".set_comments" function like this:
`session.set_comments(generate_comments_from_patterns(patterns=comment_patterns, amount=30))`

From now on You just need to add array with comments under username / password  declaration:
`comment_patterns = [
    [
        ["That's ", "It's "],
        ['beautiful', 'brilliant', 'epic', 'perfect', 'great', 'good', 'cool', 'amazing', 'magnificent', 'magical',
         'lovely', 'glorious', 'excellent', 'masterful', 'unique'],
        [' @{}'],
        ['.', '!', '! :smile:', ' :satisfied:', ' :blush:', ' :smile:', ' :wink:', ' :yum:']
    ],
    [
        ['Like it :stuck_out_tongue:', 'I like it', 'Good work! :open_mouth:', ':heart:']
    ]
]`
