### ISSUE TITLE
Did you send too many requests?

### ISSUE THREAD

**Issue by supmag** [InstaPy/InstaPy#1976]
## Expected Behavior
Normaly the bot will work for hours
## Current Behavior
Stops randomly with the wrror
Insuffecient amount of links trying again

followed by Cor! Did you send too many requests? lets rest some...and it stays stuck there
## InstaPy configuration
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.21,
				  delimit_by_numbers=True,
				   max_followers=10000,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])
    session.set_do_follow(enabled=True, percentage=45, times=2)

    # actions
    session.like_by_tags(['canonphotography', 'studio', 'studiophotography', 'grunge', 'highsnobiety', 'highsnob', 'fashionshoot', 'fashionweek', 'fashionista', 'editorial', 'retouch', 'retouching', 'retoucher', 'lightroom', 'highend', 'postproduction', 'potrait', 'dreamy', 'tonimahfud', 'daydreaming', 'naturallight', 'happyme', 'troublemaker', 'mrstealyourgirl', 'niceforwhat', 'spring2018', 'summer2018', 'instasummer', 'yakuza', 'blackboymagic', 'streetstyle', 'milliondollarsmile', 'beard', 'streetfashion', 'blackandred', 'hotboys', 'guystyle', 'ulzzangboys', 'ulzzang', 'kpop','photoshop', 'lightroom', 'cannon5d', 'retouch', 'editorial'], amount=35)

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

**Comment by uluQulu** [comment]
hi @supmag,
It is not an error and it handles the situations happened after you sent (_spent_) too many requests (_mostly scroll_) and it should just sleep some 10 mins and then continue...
Can you clearly state the problem:
**a**) did it crash after showing that?
**b**) does it not return correct amount of links?
_Please, show the screenshot of the cases above which you have.._

**Comment by supmag** [comment]
It just stays at that error for hours

https://gyazo.com/15a4411f77e2b6516b08ccab15b45a2e

**Comment by uluQulu** [comment]
@supmag,
I can't find answers to my questions and that you see is not an error at all but a helpful string saying it will sleep ~10 minutes for good, also, in that screenshot I do not see time of staying there for hours as you said
![screenshot 118](https://user-images.githubusercontent.com/33269249/39678362-62c7c20e-519c-11e8-894e-5586d2d4901c.png)
good luck!

**Comment by supmag** [comment]
I recreated the error but normally I can leave it like that for an hour or two and the script doesn't continue :/

**Comment by CharlesCCC** [comment]
@supmag make sure you right click the `command` window and uncheck "quick/insert" mode. 
This is known will pause the script from running.

**Comment by supmag** [comment]
@charlesCCC I'm unable to rightclick the comand window, this issue is continuing to presist and I'm not sure how to fix it :/ It doesn't take a break for 10 minutes it just stays at that error and then the script ends

**Comment by supmag** [comment]
Still getting this issue if someone can help I would greatly appreciate it!

**Comment by CharlesCCC** [comment]
@supmag take a full screen-shot of the last thing you seem as you mentioned `it just stays at that error and then the script ends`

**Comment by supmag** [comment]
https://gyazo.com/e9eea657c903103299a278bdaf940186

**Comment by supmag** [comment]
I am ripping my hair out, I have tried almost everything now and Im still getting this error


https://gyazo.com/e9eea657c903103299a278bdaf940186


________________________________

**Comment by mpaolor** [comment]
hi! I have a similar problem.
My log is:

INFO [2018-05-14 00:41:29] [xxx]  Session started - 2018-05-14 00:41:29
WARNING [2018-05-14 00:41:29] [xxx]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO [2018-05-14 00:42:03] [xxx]  Logged in successfully!
INFO [2018-05-14 00:42:11] [xxx]  Getting active users who liked the latest 5 posts:
  ~collecting the usernames from posts with the boundary of 500

INFO [2018-05-14 00:44:15] [xxx]  Too Many Requests sent! ~will sleep some :>
INFO [2018-05-14 00:56:10] [xxx]  Too Many Requests sent! ~will sleep some :>
INFO [2018-05-14 01:08:06] [xxx]  Too Many Requests sent! ~will sleep some :>
[... more of the same here...]
INFO [2018-05-14 13:42:10] [xxx]  Too Many Requests sent! ~will sleep some :>
INFO [2018-05-14 13:54:07] [xxx]  Too Many Requests sent! ~will sleep some :>
INFO [2018-05-14 14:06:04] [xxx]  Too Many Requests sent! ~will sleep some :>

**Comment by uluQulu** [comment]
hi @mpaolor,
it is weird cos you should see
```powershell
Cor! ~failed to get the desired amount of usernames, trying again!
```
message before seeing
```powershell
Too Many Requests sent! ~will sleep some :>
```
##### Can you provide concrete details and a good screenshot?
Also, have you done any custom modifications in `get_active_users` definition of **util.py** file?

**Comment by mpaolor** [comment]
i've never modified any file..
i downloaded the latest version 2 days ago.
a screenshot won't be helpful because you will see the same lines that I copied and pasted before only with new date times :)

my quickstart:
try:
   session.login()

   # settings
   session.set_relationship_bounds(enabled=True,
				 potency_ratio=1.10,
				  delimit_by_numbers=True,
				   max_followers=2000,
				    max_following=None,
				     min_followers=100,
				      min_following=None)
   session.set_user_interact(amount=4,	 percentage=50,   randomize=True,   media='Photo')
   session.set_dont_unfollow_active_users(enabled=True, posts=2)
   session.set_delimit_liking(enabled=True, max=200, min=None)
   session.set_smart_hashtags(['travel', 'viaggiare'], limit=3, sort='top', log_tags=True)
   
   # actions
   session.follow_user_followers(user_followers, amount=10, randomize=False, interact=True)
   ession.follow_likers (user_followers, photos_grab_amount = 2, follow_likers_per_photo = 3, randomize=True, sleep_delay=600, interact=True)
   session.follow_commenters(user_followers, amount=2, daysold=5, max_pic = 5, sleep_delay=600, interact=True)
   session.unfollow_users(amount=10, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=600, unfollow_after=48*60*60)
   session.like_by_feed(amount=10, randomize=True, unfollow=True, interact=True)

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

**Comment by uluQulu** [comment]
@mpaolor,
It's like saying "I like pears" to the "How many apples you ate?" question xD
The quickstart script has nothing to do with that issue.
Please provide that screenshot, I must be sure of the process.
> And if you can, _post the content_ of **your** `get_active_users` definition of **util.py** file in a **gist**

**Comment by mpaolor** [comment]
![capture](https://user-images.githubusercontent.com/12829453/40148511-a7ab2788-596e-11e8-9abc-77fa9127e585.JPG)


`def get_active_users(browser, username, posts, boundary, logger):
    """Returns a list with usernames who liked the latest n posts"""

    browser.get('https://www.instagram.com/' + username)
    sleep(2)

    total_posts = format_number(browser.find_element_by_xpath(
        "//span[contains(@class,'_t98z6')]//span").text)

    # if posts > total user posts, assume total posts
    if posts >= total_posts:
        # reaches all user posts
        posts = total_posts

    # click latest post
    browser.find_element_by_xpath(
        "(//div[contains(@class, '_si7dy')])[1]").click()

    active_users = []
    sc_rolled = 0
    start_time = time.time()
    too_many_requests = 0  # this will help to prevent misbehaviours when you request the list of active users repeatedly within less than 10 min of breaks

    message = (("~collecting the entire usernames from posts without a boundary!\n") if boundary is None else
               (
               "~collecting only the visible usernames from posts without scrolling at the boundary of zero..\n") if boundary == 0 else
               ("~collecting the usernames from posts with the boundary of {}\n".format(boundary)))
    # posts argument is the number of posts to collect usernames
    logger.info("Getting active users who liked the latest {} posts:\n  {}".format(posts, message))

    for count in range(1, posts + 1):
        try:
            sleep_actual(2)
            likes_count = format_number(browser.find_element_by_xpath(
                "//a[contains(@class, '_nzn1h')]/span").text)

            browser.find_element_by_xpath(
                "//a[contains(@class, '_nzn1h')]").click()
            sleep_actual(5)


            dialog = browser.find_element_by_xpath(
                "//div[text()='Likes']/following-sibling::div")

            scroll_it = True
            try_again = 0

            while scroll_it != False and boundary != 0:
                scroll_it = browser.execute_script('''
                    var div = arguments[0];
                    if (div.offsetHeight + div.scrollTop < div.scrollHeight) {
                        div.scrollTop = div.scrollHeight;
                        return true;}
                    else {
                        return false;}
                    ''', dialog)

                if sc_rolled > 91 or too_many_requests > 1:  # old value 100
                    logger.info("Too Many Requests sent! ~will sleep some :>")
                    sleep_actual(600)
                    sc_rolled = 0
                    too_many_requests = 0 if too_many_requests >= 1 else too_many_requests
                else:
                    sleep_actual(1.2)  # old value 5.6
                    sc_rolled += 1

                tmp_list = browser.find_elements_by_xpath(
                    "//a[contains(@class, '_2g7d5')]")
                if boundary is not None:
                    if len(tmp_list) >= boundary:
                        break

                if (scroll_it == False and
                                likes_count - 1 > len(tmp_list)):
                    if ((boundary is not None and likes_count - 1 > boundary) or
                                boundary is None):
                        if try_again <= 1:  # you can increase the amount of tries here
                            logger.info(
                                "Cor! ~failed to get the desired amount of usernames, trying again!  |  post:{}  |  attempt: {}".format(
                                    posts, try_again + 1))
                            try_again += 1
                            too_many_requests += 1
                            scroll_it = True
                            nap_it = 4 if try_again == 0 else 7
                            sleep_actual(nap_it)

            tmp_list = browser.find_elements_by_xpath(
                "//a[contains(@class, '_2g7d5')]")
            logger.info("Post {}  |  Likers: found {}, catched {}".format(count, likes_count, len(tmp_list)))

        except NoSuchElementException:
            try:
                tmp_list = browser.find_elements_by_xpath(
                    "//div[contains(@class, '_3gwk6')]/a")
                if len(tmp_list) > 0:
                    logger.info("Post {}  |  Likers: found {}, catched {}".format(count, len(tmp_list), len(tmp_list)))
            except NoSuchElementException:
                logger.error('There is some error searching active users')

        if len(tmp_list) is not 0:
            for user in tmp_list:
                active_users.append(user.text)

        sleep_actual(1)
        # if not reached posts(parameter) value, continue
        if count +1 != posts +1 and count != 0:
            try:
                # click next button
                browser.find_element_by_xpath(
                    "//a[@class='_3a693 coreSpriteRightPaginationArrow']"
                    "[text()='Next']").click()
            except:
                logger.error('Unable to go to next profile post')

    real_time = time.time()
    diff_in_minutes = int((real_time - start_time) / 60)
    diff_in_seconds = int((real_time - start_time) % 60)
    # delete duplicated users
    active_users = list(set(active_users))
    logger.info(
        "Gathered total of {} unique active followers from the latest {} posts in {} minutes and {} seconds".format(len(active_users),
                                                                                                     posts,
                                                                                                     diff_in_minutes,
                                                                                                     diff_in_seconds))

    return active_users`

**Comment by supmag** [comment]
Hey man! So I got the bot to start working again, however it still sometimes give me the too many links error. Do you have a working quickstart?

________________________________

**Comment by CharlesCCC** [comment]
@supmag what's your exsiting quickstart config ? how many times you ran each day.
