### ISSUE TITLE
Installing using virtual env + pip cant run quickstart.py

### ISSUE THREAD

**Issue by Rendiere** [InstaPy/InstaPy#1982]
## Expected Behavior

* Install using the "Preferred method" on the readme
    - ie create virtual env
    - pip install with git + repo url
* Copy the `quickstart.py` as is from the repo
* Fill in username password details
* run `python quickstart.py`

These steps above are expected to work.

## Current Behavior

Currently, installing using virtualenv and pip + git, firstly the chromedriver needs to be manually added to the python `site_packages/assets` dir. The `assets` directory needs to be created first. 
This is relatively easy to solve (just download and paste in the right directory).

However, the database (`instapy.db`) is also not properly set up using this method of installation and this I have not been able to solve. 

I have created the `site_packages/db` folder and pasted `instapy.db`from the repo to that dir, but I'm getting errors such as the following:

```
Traceback (most recent call last):
  File "quickstart.py", line 9, in <module>
    session.login()
  File "/Users/renierbotha/anaconda3/envs/test-insta/lib/python3.6/site-packages/instapy/instapy.py", line 322, in login
    self.bypass_suspicious_attempt):
  File "/Users/renierbotha/anaconda3/envs/test-insta/lib/python3.6/site-packages/instapy/login_util.py", line 100, in login_user
    update_activity()
  File "/Users/renierbotha/anaconda3/envs/test-insta/lib/python3.6/site-packages/instapy/util.py", line 43, in update_activity
    cur.execute("SELECT * FROM statistics WHERE created == date('now')")
sqlite3.OperationalError: no such table: statistics
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x1089c06a0>>
```

## Possible Solution (optional)

The main issue here is that the user does not have any control over where the database is stored. It would be great if we could specify that during the creation of the `InstaPy` instance. Same goes for the logging and the chromedriver location. 

I am aware that these locations seems to be configurable in `settings.py`, but using a pip installation, altering this file is not user friendly and would confuse the hell out of most novice python users. 

## InstaPy configuration

Not sure what to paste here?

**Comment by Rendiere** [comment]
@timgrossmann mind having a look? Would be great if we can do a pip install of instapy and get it running as a normal library but doesn't seem to work right now (for me at least)

**Comment by vastopa** [comment]
Check [Issue 2067](https://github.com/timgrossmann/InstaPy/issues/2067). Helped solve the same problem for me!

**Comment by jaybocc2** [comment]
@Rendiere see https://github.com/timgrossmann/InstaPy/pull/2080#issuecomment-392996932
