### ISSUE TITLE
follow_user_likers functionality does not work for me.

### ISSUE THREAD

**Issue by HermanoCrespo** [InstaPy/InstaPy#1984]
I wrote a new function to test it for my script

`def jobLeech():
    try:
        session = InstaPy(username=insta_username,
                          password=insta_password,
                          headless_browser=True)
        session.login()

        users_to_leach_on = ['user1', 'user2']

        session.follow_user_likers(users_to_leach_on, photos_grab_amount=2, follow_likers_per_photo=3, randomize=False)

    finally:
        # end the bot session
        session.end()`

## Expected Behavior

Judging the documentation, follow_user_likers should be implemented and work

## Current Behavior

This happens:
AttributeError: 'InstaPy' object has no attribute 'follow_user_likers'

Cheers!

**Comment by wangur** [comment]
FREE BOT LIKE INSTAGRAM http://www.indotagram.com/
