### ISSUE TITLE
Odd behaviour. Script caps at 27 likes per tag.

### ISSUE THREAD

**Issue by HermanoCrespo** [InstaPy/InstaPy#1985]
Hello,

I have a list containing 18 tags that I use to perform actions on.

my code:

```

likeTags = ['tag1', '...', 'tag18']

 for i in range(0, len(likeTags)):  # loop over list of Tags
            likeTagInLoop = []  # create a blank list
            likeTagInLoop.append(likeTags[i])  # append Tag to blank list
            like_count = (randint(41, 50))  # randomize like count
            session.like_by_tags(likeTagInLoop, amount=like_count)  # execute liking functionality
```

## Expected Behavior

I would expect the script to loop over my 18 tags and like on each tag between 41 and 50 times with a random distribution of interactions per tag and 45.5 times per tag on average over time.

## Current Behavior

Currently, I get 27 likes for each tag. I can see that in the logs going back as far as I checked. It never goes beyond 27. Odd.

Now, I am quite new to coding but I am fairly confident that there is no issue with my code.

Is a 27 cap per tag hard coded into the instapy script?

Cheers!

**Comment by HermanoCrespo** [comment]
It occurred to me to test the code with different variables.

Instead of 41, 50 for the range in randint() I just tried (am trying actually, still running) 18, 24. That works. First tag was 18, second tag was 21.

So I think my code is fine.

My workaround to get to my desired 45.5 * 18 = 820 interactions per run is by cutting the number in half to 22.75 and running it back to back twice with a randint(19,27) and randint(18,26).

**Comment by CharlesCCC** [comment]
@uluQulu Is the other thread already deprecated or ?

**Comment by uluQulu** [comment]
Hey guys,
@CharlesCCC, it is still open #1365 xD

>AttributeError: 'InstaPy' object has no attribute 'follow_user_likers'

_saw it in your other fresh thread (#1984) , @HermanoCrespo, smells like your files are old...._
try pulling latest files and re-check again, if the issue persists, just post the details and output if any,
good luck!

**Comment by HermanoCrespo** [comment]
Trying now. Files were old, good catch. Running now, will let you know.
Cheers

**Comment by HermanoCrespo** [comment]
Works now, I can like more than 27 per post. It was the installation and I would guess, that the other feature just was not available yet as well. 

Following up, would you be worried over the "Too Many Requests sent!" part from below log output? 

> INFO [DATE TIME] [user]  Post 1  |  Likers: found 458, catched 458
> INFO [DATE TIME] [user]  Post 2  |  Likers: found 754, catched 504
> INFO [DATE TIME] [user]  Too Many Requests sent! ~will sleep some :>
> INFO [DATE TIME] [user]  Post 3  |  Likers: found 652, catched 504
> INFO [DATE TIME] [user]  Post 4  |  Likers: found 837, catched 504
> INFO [DATE TIME] [user]  Cor! ~failed to get the desired amount of usernames, trying again!  |  post:5  |  attempt: 1
> INFO [DATE TIME] [user]  Too Many Requests sent! ~will sleep some :>
> INFO [DATE TIME] [user]  Post 5  |  Likers: found 521, catched 504

I have not seen this with the older code. Is that too much activity?

**Comment by uluQulu** [comment]
It's great that it works for you, @HermanoCrespo,
That message is pointing that you have sent too many scroll requests and it will take a nap in order to keep be able to scroll again after new `timeout` opens.  
_Yes, previously there were literally no requests limits that's why there were no need for the part I explained above._
_Recommendation is, although you will be able to (_mostly_) get the desired amount you defined, it is best to use small amounts with rich feature set in your  quickstart script by which performance will boost._
> For the particular log you've attached above, it belongs to `set_dont_unfollow_active_users` feature and you cannot separate it into small parts but, I would take a smaller range in `boundary` parameter, but it is optional.
