### ISSUE TITLE
Still getting the "too many requests error"

### ISSUE THREAD

**Issue by supmag** [InstaPy/InstaPy#1987]
## Expected Behavior
The script should run without pauses or crashing
## Current Behavior
The script crashes every time without fail, I thought it was taking a break but I watched it multiple times and left the error for a while. The script either crashes or stays on the same error.

The error is "Cor! did you send to many requests" and/or "too many links requested"
## InstaPy configuration
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = '******'
insta_password = '8******'

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#   Settings.database_location = '/path/to/instapy.db'
#   Settings.chromedriver_location = '/path/to/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.21,
				  delimit_by_numbers=True,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    session.set_do_follow(enabled=True, percentage=30, times=2)

    # actions
    session.like_by_tags(['dreamy','tonimahfud','daydreaming','naturallight','happyme','troublemaker','mrstealyourgirl','niceforwhat','spring2018','summer2018','instasummer','yakuza','blackboymagic','streetstyle','milliondollarsmile','beard','streetfashion','blackandred','hotboys','guystyle','ulzzangboys','ulzzang','kpop','photoshop','lightroom','cannon5d','retouch','editorial'], amount=20)

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

**Comment by uluQulu** [comment]
It is very weird,
Provide your system details (_OS_ & _python_ `version`)
try a few things for now,
* in `get_links_for_tag` function of **like_util.py** file,
replace
```python
logger.info("Cor! Did you send too many requests? ~ let's rest some")
sleep(600)
```
with
```python
logger.info("Cor! Did you send too many requests? ~ let's rest some")
for i in range(6):
    sleep(100)
```
I mean separate sleep into parts..

* Also, you can try this..
at top of that file, **import** `time` and use that `time.sleep()` instead
```python
import time
#some code.....
logger.info("Cor! Did you send too many requests? ~ let's rest some")
time.sleep(600)
```

* Also,
write a simple python script
```python
from time import sleep as real_sleep

print("I am gonna sleep 10 mins")
real_sleep(600)
print("I just woke up from sleep,,,")
```
_and see if waking up from sleep is working_ 

> if none of them works, provide those system details and other troubleshoot information in order to slove it...

**Comment by CharlesCCC** [comment]
why you keep opening new issues ?  keep it together if it is the same issue. you are spamming the community.

**Comment by CharlesCCC** [comment]
any additional issue related, please keep to #1976
