### ISSUE TITLE
Flag/ban thresholds for actions

### ISSUE THREAD

**Issue by AlexBailey** [InstaPy/InstaPy#199]
Unless I have completely missed this, we've not added anywhere a (rough?) threshold guideline of the maximum amount unfollows, follows, comments, likes and so on per hour an account can do per hour before getting flagged, soft banned or banned. I have heard that some thresholds are user specific, but we surely must be able to come up with a rough guideline and perhaps keep it up to date in the wiki in accordance to my previous thread #192 (a record of all recorded user bans and preferences used along with runtime) where we can learn more about these thresholds. However, any knowledge known right now would be great to have documented.

**Comment by eduardocalazansjr** [comment]
There's an existing discussion about that.
Why open another? Why don't comment on #192?

Also, instagram bans are purely random based on ip/subnet (VPS are the most trackable for now) and the account history.

There's no threshold, could be 10 or 1000. Today for one account could be 10000, but tomorrow instagram could track this repo and limit this to 2 for every account with the same behaviour. 

Adding that could lead to serious problems, there's already an BIG disclaimer on the repo page.

Stop having all the spotlights to that theme, enjoy the tool while it lasts and as the disclaimer said "I’m also not responsible if your accounts get banned due to **extensive use** of this tool".
Extensive or dumb, maybe.

**Comment by AlexBailey** [comment]
@vlntdds 

> There's no threshold, could be 10 or 1000. Today for one account could be 10000, but tomorrow instagram could track this repo and limit this to 2 for every account with the same behaviour.

There's a lot of evidence that stacks against that, but they are threshold ranges, not accurate numbers.
> Also, instagram bans are purely random based on ip/subnet (VPS are the most trackable for now) and the account history.

As you even said yourself [here](https://github.com/timgrossmann/InstaPy/issues/89#issuecomment-294295863), they flag on instagramweb page interaction, not just a 'if your connection is on a list' approach, not sure why you made that comment?

If you look at the infamous PokemonGo-bot repo, you can see that their ban log and finding a rough guideline to inputs (in this case in their JSON file) was able to tie their community together and everyone was on the same page, as opposed to having countless issues flooding up due to X, Y and Z people getting banned. I do however understand your point of view and I am **not** saying create a guide to evade a ban, as that would be impossible regardless, just a 'how not to use this app extensively 101'.

**Comment by eduardocalazansjr** [comment]
> There's a lot of evidence that stacks against that, but they are threshold rages, not accurate numbers.

Show me that, i'm currently testing on 15th account (just today) and there's no threshold, not today. Got an locked account just for logging and repeat the like function for 9 times.
Got another account locked just for using MANUAL interaction on the same subnet that the previously 9 likes-account got locked.

Also check the closed issues before opening another, update the infos, check #196, for example.

**Comment by AlexBailey** [comment]
> Show me this

I'm purely going off of the copious amounts of people claiming to have been banned for X threshold of Y action, the volume of reports suggested there was a range - apologies if your findings are different to what users have reported, I was not trying to spread misinformation

Sorry, I did miss that one.
