### ISSUE TITLE
delay between likes and Randomize wait time

### ISSUE THREAD

**Issue by emyabdel** [InstaPy/InstaPy#1990]
hello how to setup delay between likes on quickstart and how to Randomize wait time for example to 25%

thanks

**Comment by sionking** [comment]
No option yet.

**Comment by sionking** [comment]
Working on minimum sleep time

**Comment by emyabdel** [comment]
if the like delay time is the same the account could be banned

**Comment by bgunsberger** [comment]
This should apply to following too.

**Comment by c0d3x27** [comment]
@emyabdel i already solved it. i even made a pull request on this. try it, and if this work please closed this problem.

**Comment by c0d3x27** [comment]
https://github.com/timgrossmann/InstaPy/pull/2735

this is the link
