### ISSUE TITLE
can not use russian cyrillic tags

### ISSUE THREAD

**Issue by godowsky** [InstaPy/InstaPy#1991]
## Expected Behavior
session.like_by_tags(['итальянскаякухня']
## Current Behavior
self.logger.info('--> {}'.format(tag.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)

**Comment by sk1980** [comment]
Try to use UTF8 codepage (65001) of the command script file. I use some cyrillic tags and they works good.

**Comment by godowsky** [comment]
Hi, thank you.  I'm quite new on phython. I tried implementing the utf8 code in front of every py script but no results. Can you please advice on how i can do that?

**Comment by sk1980** [comment]
So, as for me - I use Far Manager to edit scripts. This is an example on the screenshot
[http://sam73.ru/pic.png](http://sam73.ru/pic.png)
