### ISSUE TITLE
Catched 12

### ISSUE THREAD

**Issue by dbmathis** [InstaPy/InstaPy#1992]
I’ve been running Instapy for about 5 days on my Mac. Today I started seeing the following which seems wrong/excluding active users. Why 12 and not the actual number of active users?

INFO [2018-05-08 16:06:57] [xx]  Post 1  |  Likers: found 75, catched 75
INFO [2018-05-08 16:07:17] [xx]  Post 2  |  Likers: found 73, catched 73
INFO [2018-05-08 16:07:36] [xx]  Post 3  |  Likers: found 77, catched 77
INFO [2018-05-08 16:07:59] [xx]  Post 4  |  Likers: found 70, catched 12
INFO [2018-05-08 16:08:20] [xx]  Post 5  |  Likers: found 110, catched 12
INFO [2018-05-08 16:08:41] [xx]  Post 6  |  Likers: found 58, catched 12
INFO [2018-05-08 16:09:02] [xx]  Post 7  |  Likers: found 54, catched 12
INFO [2018-05-08 16:09:23] [xx]  Post 8  |  Likers: found 74, catched 12
INFO [2018-05-08 16:09:44] [xx]  Post 9  |  Likers: found 52, catched 12
INFO [2018-05-08 16:10:05] [xx]  Post 10  |  Likers: found 97, catched 12
INFO [2018-05-08 16:10:26] [xx]  Post 11  |  Likers: found 73, catched 12
INFO [2018-05-08 16:10:47] [xx]  Post 12  |  Likers: found 81, catched 12
INFO [2018-05-08 16:11:09] [xx]  Post 13  |  Likers: found 90, catched 12
INFO [2018-05-08 16:11:29] [xx]  Post 14  |  Likers: found 83, catched 12
INFO [2018-05-08 16:11:51] [xx]  Post 15  |  Likers: found 62, catched 12
INFO [2018-05-08 16:12:12] [xx]  Post 16  |  Likers: found 94, catched 12
INFO [2018-05-08 16:12:33] [xx]  Post 17  |  Likers: found 98, catched 12
INFO [2018-05-08 16:12:54] [xx]  Post 18  |  Likers: found 64, catched 12
INFO [2018-05-08 16:13:15] [xx]  Post 19  |  Likers: found 73, catched 12
INFO [2018-05-08 16:13:36] [xx]  Post 20  |  Likers: found 94, catched 12
INFO [2018-05-08 16:13:37] [xx]  Gathered total of 200 unique active followers from the latest 20 posts in 7 minutes and 7 seconds

**Comment by uluQulu** [comment]
hi @dbmathis,
smells like you've either spent excessive amount of scroll requests right before starting `set_dont_unfollow_active_users` method, OR, the default timeout for that scroller is decreased
_do make sure that you are not using hard scrolling activity which is not welcomed and try to test a few times. If it results the same, ask again, I would have a look at the timeout range, again_

**Comment by dbmathis** [comment]
Thanks @uluQulu 

What is hard scrolling and how do I not do that?

**Comment by uluQulu** [comment]
Welcome @dbmathis,
I mean the excessive usage of scrollers,
e.g., starting mostly scroller based features with higher amounts one after another
> actually, this is not a problem but it is a good practice

**Comment by dbmathis** [comment]
This issue continues to intermittently happen. What does the catched part mean and should I be concerned? Does it mean that I am unfollowing people who liked my photos?

**Comment by uluQulu** [comment]
@dbmathis 
```powershell
INFO [2018-05-08 16:07:59] [xx] Post 4 | Likers: found 70, catched 12
```
means

From your latest 4th post, it found 70 usernames who did like that post and it could only catch (_or grab_) the usernames of 12 of them.

Those usernames will be saved in a sessional variable and will not let any of those users to be unfollowed, cos of they are active followers.

**Comment by dbmathis** [comment]
Thanks. Going back to your original response a few weeks ago. I have not changed any timeouts or similar. I am not aware of any excessive scrolling. This is still running on a cronjob on an iMac 4 times a day. Most of the time I don’t see the catch 12 issue and I do add people I like to the do not include list, but it would be better if this could be fixed somehow. I wish I knew python.

**Comment by uluQulu** [comment]
@dbmathis 
I did not get your point.
It is not an issue, it just catches only 12 usernames cos it cannot scroll more to catch more usernames cos you have either scrolled excessively previously or there is a problem to be fixed.

If you want to use your own `do not include` list, go ahead and use it and disable `set_dont_unfollow_active_users` feature, it is optional.

Python is so easy, go ahead and learn it, so that you can solve your problems 👍

**Comment by dbmathis** [comment]
Sorry, my point was that I don’t actively use the iMac so I don’t know what would have scrolled excessively other than Instapy. It seems like there’s an instapy issue that happens first (perhaps it’s excessiv scrolling or something else) and then the catch code just reports that it couldn’t catch as a result, which is a sort of pointer to the  real problem.

**Comment by dbmathis** [comment]
This continues to happen. Has anyone else noticed this?

**Comment by dbmathis** [comment]
Could there be an issue with selenium? For example, it found 58: catched 12 (which seems to mean there was 12 on the first page and since it could not scroll it could only grab those 12). Why can't it scroll? Selenium issue? Instapy issue?

I am losing loyal followers because people who consistently like my posts are being unfollowed. I appreciate Instapy and the number of followers it brings is better than the loyal followers I lose because of this issue, however, if I can avoid this issue, it would be great.

Any ideas would be wonderful.

**Comment by uluQulu** [comment]
@dbmathis 
I see that you are still tackling around this issue. Lemme tell you a few bits,.
Recently, before I did add that smart scroller which could go grab all of the usernames at desired boundary from desired amount of posts, so before that, there were no any scroller, it was just opening posts and grabbing only the visible usernames without scrolling.

So now it has a smart scroller and it works pretty fine for lots of people.
The problem you have is probably you put it so high amount of posts and then it scrolls so much where it faces a scroll timeout. Then it cannot scroll and will return only the visible amount of usernames- 12 most of time.

What can be done?

Sure it can be improved to support all of the worst conditions but it will slow down the process.
You get what you pay for here.

Regards, Shahriyar

**Comment by dbmathis** [comment]
I get that it's free, no complaints there at all, as I said before I would rather lose followers if the gain is like it is with Instapy. Overall it's a win. I just figured others might have run into and fixed this or might know where to look to get closer to a fix. I am not convinced it's due to excessive scrolling because recently, intermittently, I get a catched 12 on the very first post.

**Comment by uluQulu** [comment]
Uhm, well, @dbmathis 
I meant that you get the result out of the care you give.
If you want a better smart scroller, I think you want.
Provide solid details about
+ What you do
+ What you get
+ What you want
+ What you need
+ What is best
+ What you do expect

_But the answers must be really accurate, details are so important._
>The answers should be within the context of the smart scroller.

Only then if there is a really good reason to write new lines, I can help you.

**Comment by dbmathis** [comment]
Thanks for your replies.

What I want, is for the likers found to match the likers catched, so that people who are liking my posts don't get unfollowed. It's a great idea, but it doesn't work for me.

**What I do is run the following on a cronjob 4 times a day:**

```
from instapy import InstaPy

insta_username = ''
insta_password = ''

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#   Settings.database_location = '/path/to/instapy.db'
#   Settings.chromedriver_location = '/path/to/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True,
                  bypass_suspicious_attempt=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
                 potency_ratio=-1.21,
                  delimit_by_numbers=True,
                   max_followers=4590,
                    max_following=5555,
                     min_followers=45,
                      min_following=77)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['Nicely done!', 'Nice!', 'Love it!', 'Nice one @{}!', 'Brilliant!', 'Nice @{}', 'Great photo', 'Lovely!', 'Great shot @{}', 'Great @{}', 'Nice job @{}', 'Very Nice', 'Keep up the good work.'])
    session.set_dont_include(['60 or so people . here'])
    session.set_dont_like(['pizza', 'girl', 'sex'])
    session.set_dont_unfollow_active_users(enabled=True, posts=10)
    # default enabled=False, follows ~ 10% of the users from the images, times=1
    # (only follows a user once (if unfollowed again))

    session.set_do_follow(enabled=True, percentage=40, times=2)

    session.unfollow_users(amount=10, onlyInstapyFollowed=True, onlyInstapyMethod='FIFO', sleep_delay=600, unfollow_after=48*60*60)

    session.like_by_tags(['birds', 'travel', 'wonderlust', 'adventure', 'birds_nature', 'insects', 'insects_macro','naturephotography', 'nature', 'mountains', 'naturelovers', 'outdoors', 'hiking', 'wildlife', 'wildlifephotography', 'outdoorphotography', 'photography', 'macrophotography', 'naturelovers', 'macro_captures', 'raw_insects', 'gf_macro', 'igbest_macros', 'masters_in_macro', 'total_macro', 'bns_macro', 'loves_united_macro', 'macro_kings', 'top_macro', 'excellent_macros', 'fuzzy_favorites', 'macro_captures', '25k_macro', 'insectguru'], amount=3)

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()
```
**What I get is:**
More likes and followers then I could without Instapy. There is, however, this issue of people who like my last 10 posts who are getting unfollowed, as mentioned above.

**What I want is:**
What I have now, but without the likers of the last 10 posts being missed and unfollowed. People appear to be able to see when I unfollow them and may feel hurt and then they rightfully unfollow me.

**What I need is:**
Help to figure out why this code that was designed to collect the likers by scrolling, stops scrolling, only collects 12 as a result, which then results in unwanted unfollowes.

**What is best is:**
That we understand why this isn't working so that it can be improved for me and others. 

**What I expect is:**
Well,it depends. 

If you are asking what I expect from you, well nothing. I would, however, hope that you take pride in what you do, even if it's free, and want to solve the issue. If not, oh well, I will either figure this out on my own or just live with it.

If you are asking what I expect from the code then I simply expect it to do what the documentation says.

**Comment by uluQulu** [comment]
Great @dbmathis! 
I see some accuracy there, it's much better now to go through a solution. 🛰

+ How often you do initiate cron jobs or that **quickstart**?
>I have to know the time between **quickstart** initiations, it is so important.
_e.g. after 50 minutes or 6  hours or 10 minutes, or irregular (mention how)_

+ Do you really have `posts=10`?
>I think you have put a lot higher amount than 10.

+ Do you use boundary parameter (_if yes- how_)?
e.g.
```python
sesssion.set_dont_unfollow_active_users(enabled=True, posts=10, boundary=500)
```

Again, answers have to be accurate.

>By helping out people I learn lots of knowledge, that's enough to me.
Although, I don't know how long I will stay in this project, I will help you solve that particular problem.

Cheers
