### ISSUE TITLE
UnboundLocalError: local variable 'allfollowing' referenced before assignment

### ISSUE THREAD

**Issue by caburet** [InstaPy/InstaPy#1993]
## Expected Behavior
Follow
## Current Behavior
[....]  <-- meaning a lot of tags...
Error:

WARNING [2018-05-09 13:32:22] [noe_hebal]  maxdreampuntaalta -> Less users to follow than requested.
ERROR [2018-05-09 13:32:22] [noe_hebal]  follow loop error sample larger than population
INFO [2018-05-09 13:32:22] [noe_hebal]  --> Total people followed : 91 
WARNING [2018-05-09 13:32:48] [noe_hebal]  There are 0 people to follow
ERROR [2018-05-09 13:33:13] [noe_hebal]  following_link error list index out of range
INFO [2018-05-09 13:33:14] [noe_hebal]  Session ended - 2018-05-09 13:33:14
INFO [2018-05-09 13:33:15] [noe_hebal]  --------------------

Traceback (most recent call last):
  File "quickstart.py", line 41, in <module>
    session.follow_user_following(['bahiablancaplazashopping',  [....]  ,'uno bahia club'], amount=100, randomize=True, sleep_delay=160)
  File "/home/joel/InstaPy/instapy/instapy.py", line 1680, in follow_user_following
    self.follow_times)
  File "/home/joel/InstaPy/instapy/unfollow_util.py", line 863, in follow_given_user_following
    allfollowing,
UnboundLocalError: local variable 'allfollowing' referenced before assignment

/InstaPy$ git pull
Already up-to-date. 

## InstaPy configuration
[....]  <-- meaning a lot of tags...
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.21,
				  delimit_by_numbers=True,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['Wow!', 'Hermoso!!', 'que lindo!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])
    session.set_do_follow(enabled=True, percentage=30, times=2)
    session.follow_user_followers(['bahiablancaplazashopping'  [.... ]  ,'uno bahia club'], amount=100, randomize=True, sleep_delay=160)
    session.follow_user_following(['bahiablancaplazashopping'    [....]      ,'uno bahia club'], amount=100, randomize=True, sleep_delay=160)
    # actions
    session.like_by_tags(['bahiablancaplazashopping'], amount=1)

**Comment by timmoh** [comment]
same here.

**Comment by uluQulu** [comment]
Hi @caburet, @timmoh,
That's a bug, do this to fix it:
open up **unfollow_util.py** file and modify `follow_given_user_following` definition as:
**replace**
```python
logger.warning('There are 0 people to follow')
```
with
```python
logger.warning("Could not determine if {} has followers  ~skipping to the next user".format(user_name))
return []   #return empty list
```
_this particular change will solve the issue in your log, @caburet, it will not crash again_
> I see that there are other definitions having this bug too, it would be great to generalize this and make a PR.
