### ISSUE TITLE
Feature Request: Using Tor

### ISSUE THREAD

**Issue by westondeboer** [InstaPy/InstaPy#2000]
Using tor to mask ips? 

Is that how tor works?

**Comment by mrkcds** [comment]
I don't think this is a good idea. Tor ips are really easy to detect and I'm not sure Instagram/Facebook tolerates it. Either way they will know you're using Tor and there's a good chance you're sharing the ip with many other people.

**Comment by FranklinClinton** [comment]
I used TOR for Instagram. It is very slow. Instagram also forces you to have a phone number bound to your account if it detects TOR IP address.

**Comment by westondeboer** [comment]
Who came up with such a terrible idea then? please close this.
