### ISSUE TITLE
ImportError: cannot import name verify_liking

### ISSUE THREAD

**Issue by aku6640** [InstaPy/InstaPy#2002]
## Current Behavior

Traceback (most recent call last):
  File "custom.py", line 8, in <module>
    from instapy import InstaPy
  File "/home/pi/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/home/pi/InstaPy/instapy/instapy.py", line 24, in <module>
    from .like_util import verify_liking
ImportError: cannot import name verify_liking

this happend after pulling.. anyone ideas to fix this?

**Comment by uluQulu** [comment]
@ahmetu66,
Check if `verify_liking` function exists in **like_util.py** file, so that it can import it and make sure **custom.py** uses the pulled latest files.

**Comment by aku6640** [comment]
Strange, the function didn't exist. Shouldn't that be pulled too? I have now added the function and it works again. Thanks!

**Comment by uluQulu** [comment]
@aku6640,
These are the list of commits, https://github.com/timgrossmann/InstaPy/commits/master
See if you have pulled all of the latest ones.
But for that particular function, #1919 is sufficient.

**Comment by aku6640** [comment]
what is the best way to pull without getting errors? I use git pull most of the time, but it seems there must be a better way?

**Comment by uluQulu** [comment]
@aku6640,
`git` is the only way to pull from GitHub repositories (_I guess so_).
I use GitHub Desktop app which runs the `git` commands in background and yet for some actions, I still do run `git` in command prompt, e.g., for `stash`, `pop`, `rebase` and etc. (_GitHub Desktop app does have limited capabilities_)
It is best to learn `git` which is used in many places as a source control mechanism, e.g., latest MS Visual Studio has an official GitHub extension and installs `git` by default...
Having said those, alternatively, you can either re-download zipped source files from repository and replace with your old ones OR see the commits history and apply the changes manually.
Goood luck!
> Hint: learn more about `solving conflicts` after a `git` pull and use a dedicated text editor like Atom to see the `unstaged` changes easily!
