### ISSUE TITLE
Code doesn't follow relationship bounds

### ISSUE THREAD

**Issue by harrycha** [InstaPy/InstaPy#2003]
## Expected Behavior
I expect this code to sort through a given profiles followers and follow only the ones with the relationship bounds
## Current Behavior
It ends up following all of the users even though I've set potency_ratio at 1.20 meaning it wont interact with users under it
## InstaPy configuration

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=1.20,
				  delimit_by_numbers=True,
				   max_followers=7000,
				    max_following=5555,
                                     min_followers=45,
				      min_following=77)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['nice', 'nioce'])
    session.set_delimit_liking(enabled=True, max=1020, min=20)
    session.set_delimit_commenting(enabled=True, max=200, min=5)
    session.set_user_interact(amount=3, randomize=True, percentage=30, media='Photo')
    session.set_do_follow(enabled=True, percentage=100)
    session.set_delimit_liking(enabled=True, max=1020, min=20)
    session.set_delimit_commenting(enabled=True, max=200, min=0)
    session.set_do_like(enabled=True, percentage=70)
   # actions
    session.follow_user_followers(['XXXXXX'], amount=1000, randomize=True)

**Comment by uluQulu** [comment]
hi @OGHARRY,
It is working inside a dialog box where you can't expect to verify user's relationship bounds.
Previously it has been issued at #1858 by @Dimlsaev and I got it implemented yesterday, soon, will share it in a PR
> Lots of design has changed! (_watch PRs_)
