### ISSUE TITLE
Differentiate media type and comment issue

### ISSUE THREAD

**Issue by Patrikkk-zz** [InstaPy/InstaPy#2007]
## Expected Behavior

# you can also set comments for specific media types (Photo / Video)

session.set_comments(['Nice shot!'], media='Photo')
session.set_comments(['Great Video!'], media='Video')

I'm trying to use this feature. But instapy comments "Nice video!" on photos... anyone else has this issue?
I can grab some logs if required.

**Comment by uluQulu** [comment]
Hi @Patrikkk,
Which feature(s) are you using having this misbehavior? (_e.g. `like_by_tags`_)

**Comment by ghost** [comment]
i confirm,

session.set_comments(['Nice shot!'], media='Photo')
session.set_comments(['Great Video!'], media='Video')
session.like_by_tags(['#tesla','#spacex','#nasa','#therock'], amount=100)

it comments Great Video on pictures ...
Thanks

**Comment by uluQulu** [comment]
@ilmetu 
Right, I will try to have a look into commenting engine.
I must be revised.

Regards

**Comment by arcasoy** [comment]
I am still having this problem, is anyone else still having this? Same issue where, in like_by_tags, it does not follow the media type.

**Comment by butaminas** [comment]
Having the same issue.
