### ISSUE TITLE
Not just follow but also like and comment for follow_user_following

### ISSUE THREAD

**Issue by FranklinClinton** [InstaPy/InstaPy#2009]
## Expected Behavior
- InstaPy follows every person on the following list
- Instapy likes one picture of the person
- Instapy comments on the same picture
## Current Behavior
- InstaPy follows every person on the following list
- Instapy **does not** like one picture of the person
- Instapy **does not** comment on the same picture
## Possible Solution (optional)
Tell me :-(
## InstaPy configuration
My Script:
```
import sys
from instapy import InstaPy

insta_username = sys.argv[1]
insta_password = sys.argv[2]

session = InstaPy(username=insta_username,
                      password=insta_password,
                      nogui=True)
session.login()

session.set_relationship_bounds(enabled=True,
                         potency_ratio=None,
                          delimit_by_numbers=True,
                           max_followers=4590,
                            max_following=5555,
                             min_followers=45,
                              min_following=45)

session.set_user_interact(amount=1, randomize=True, percentage=100, media='Photo')
session.set_do_like(enabled=True, percentage=100)
session.set_comments([u':heart_eyes: :heart_eyes:', u'Nice :heart:'])
session.set_do_comment(enabled=True, percentage=100)

session.follow_user_following(['THEUSERNAME'], amount=100, randomize=False, interact=True)

session.end()
```

**Comment by uluQulu** [comment]
hi @FranklinClinton,
Currently interactions happen after following the **all of** the users, and after then you can get likes & comments at those interactions..
But **soon** I am gonna share enhanced versions of a few functions, where for `follow_user_followers` feature, interactions will happen right after following a user, also, then the users can be matched against relationship bounds

**Comment by FranklinClinton** [comment]
@uluQulu Thank you for all your efford. It's not the first time I see you fixing things! For now I will just use session.interact_user_following which seems to be working for me. Instapy ignores all bounds in regard of following. He follows everybody and does not respect the bounds in that matter. But that's  another issue. Thank you!

**Comment by uluQulu** [comment]
Welcome, @FranklinClinton,
_In that PR, comes that feature, too!_
I have added **relationship bounds** _verification_ support for `follow_user_followers` and some others missing it. (_watch PRs_)
