### ISSUE TITLE
Problem with the graphql

### ISSUE THREAD

**Issue by samihamine** [InstaPy/InstaPy#2010]
## Expected Behavior
Unfollows accounts 

## Current Behavior
I have this screen on Mozilla Firefox and the bot keep running without unfollowing any accounts : 

![capture](https://user-images.githubusercontent.com/32743644/39971471-e53d2cba-56fb-11e8-9c7b-fcb3c6cebc6f.JPG)

Thanks for your help 👍 

## InstaPy configuration
Running on a raspberry pi on Mozilla Firefox

**Comment by uluQulu** [comment]
hi @SammyHam,
It's the way getting data through graphql queries work and is pretty normal.
It must get data and start doing actions, maybe you have put a big amount and it takes a big time.
But if it just stops at that screen for hours doing nothing, then there is a problem.

**Comment by samihamine** [comment]
Hello @uluQulu 
Thank you so much ! It work. 

I will close this Issue (y)
