### ISSUE TITLE
prevent duplicate cronjob running ( using run-one )

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#2014]
My working cronjob 
`*/59 * * * * cd /home/ubuntu/igbot/InstaPy-master && /usr/bin/python3.5 ./quickstart.py`

**How do i code it so i dont get errors with run-one ?**
`sudo run-one cd /home/ubuntu/igbot/InstaPy-master && /usr/bin/python3.5 ./quickstart.py`
`flock: failed to execute cd: No such file or directory`
**thank you**

**Comment by CharlesCCC** [comment]
google is your friend :)
