### ISSUE TITLE
issues with unfollow_users() sometimes

### ISSUE THREAD

**Issue by HermanoCrespo** [InstaPy/InstaPy#2016]
`session.unfollow_users(amount=10, onlyNotFollowMe=True, sleep_delay=60, unfollow_after=48 * 60 * 60)`

seems not to work. 

Behaviour: unresponsive command line for some time. I could not wait it out, however I have used it for some days and not realised there was an issue and my followedPool.csv is massive (1500 lines) but I am not following that many people. the instagram app tells me I am following only 834.

So maybe it does the job but does not log it and does not put it on the command line?

`session.unfollow_users(amount=10, onlyInstapyFollowed=True, onlyInstapyMethod='FIFO', sleep_delay=600, unfollow_after=96 * 60 * 60)`
works 

It does not work on two accounts who both have recently seen their files updated 5-6 days ago.

By the way, is there a version number somewhere to know when my files are up to date?

**Comment by sionking** [comment]
please update to latest

**Comment by HermanoCrespo** [comment]
Done. Running the latest files.

Issue still there.

No output on the command line with this code
`session.unfollow_users(amount=10, onlyNotFollowMe=True, sleep_delay=60, unfollow_after=2 * 24 * 60 * 60)`

I get that:
`INFO [2018-05-15 15:21:45] [user]  Logged in successfully!`

And then the script seems stuck for minutes on end.

Edit:
for what it's worth, I just interrupted the execution with ctrl c

The command line reads:

```
^Cunable to get followers and following information 
 
unfollow loop error 
 [Errno 104] Connection reset by peer
INFO [2018-05-15 15:30:05] [user]  --> Total people unfollowed : 0
Interupt 
```

**Comment by HermanoCrespo** [comment]
I wanted to run the script just now on the new files (updated today) and it produced an error:

`session.follow_user_likers(leeching_on, photos_grab_amount=1, follow_likers_per_photo=3, randomize=False)
AttributeError: 'InstaPy' object has no attribute 'follow_user_likers'`

That is odd because the script works on InstaPy files from now 7 days ago. I always keep the old version around to verify it works when upgrading. No issue there. Just with the latest files.

**Comment by therealahall** [comment]
This last one is because follow_user_likers has been refactored to follow_likers.  Update that portion of your quickstart.py and it should continue past there.

**Comment by HermanoCrespo** [comment]
Thanks Aaron, I will do just that for tonights schedule.
