### ISSUE TITLE
Issue with "cor did you send too many requests"

### ISSUE THREAD

**Issue by supmag** [InstaPy/InstaPy#2017]
## Expected Behavior
Just to say, I'm not trying to spam the community, I have had this issue for 2 weeks now and the topic keeps getting buried. I depend on this amazing script for a multitude of things and would love some help!

"the script use to run fine for hours"
## Current Behavior
The script keeps stoping after a short duration with the error "cor did you send to many requests?"
https://gyazo.com/e9eea657c903103299a278bdaf940186
It stays that way for hours and then eventually just crashes. I have even sat and watched to see if something else would happen but it doesn't

I have the latest python and newest pull from the instapy 
## InstaPy configuration
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = '****
insta_password = '****

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#   Settings.database_location = '/path/to/instapy.db'
#   Settings.chromedriver_location = '/path/to/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.21,
				  delimit_by_numbers=True,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    session.set_do_comment(False, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.like_by_tags(['photo', 'photography', 'photoshoot', 'model', 'fashion', 'fashionmodel', 'fashionphotography', 'fashionphotographer', 'canon', 'canonphotography', 'indoor', 'editorial', 'studio', 'studiophotography', 'grunge', 'highsnobiety', 'highsnob', 'fashionshoot', 'fashionweek', 'fashionista', 'editorial', 'retouch', 'retouching', 'retoucher', 'lightroom', 'highend', 'postproduction'], amount=20, media='Photo')

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

**Comment by CharlesCCC** [comment]
Thank you for sharing your configuration this time:
```
['photo', 'photography', 'photoshoot', 'model', 'fashion', 'fashionmodel', 'fashionphotography', 'fashionphotographer', 'canon', 'canonphotography', 'indoor', 'editorial', 'studio', 'studiophotography', 'grunge', 'highsnobiety', 'highsnob', 'fashionshoot', 'fashionweek', 'fashionista', 'editorial', 'retouch', 'retouching', 'retoucher', 'lightroom', 'highend', 'postproduction'], amount=20, media='Photo')
```
based off the setting you have. you got 27 tags with 20 likes each, that is 540 per run.  if you read the wiki carefully,  it clearly says don't like more than 1000 photos per day. I'm not sure how often you run. 
but, as the WARNING message said `cor did you send too many requests`    -- > you did sent too many request. so, please change the number of tags or amounts to lower number. let say `amount=5` and then let us know if you still having issue.

**Comment by supmag** [comment]
I tried it with just 2 tags aswell, I received the same issue

**Comment by CharlesCCC** [comment]
@supmag you already get "soft"banned from instagram.com. stop for couple days (3 days at least) and then try it again with less than 100 total likes per hour. (no more than 1000 likes per day).

**Comment by supmag** [comment]
Nope no soft-ban, I tested it. Also it behaves the same on multiple other accounts...

**Comment by CharlesCCC** [comment]
@supmag yes, because your IP is been soft-banned and blacklisted. any account run under that IP will prevent from like and follow.
