### ISSUE TITLE
Unable to get followers and following information - Unfollow task is not working

### ISSUE THREAD

**Issue by neonvandal** [InstaPy/InstaPy#2021]
Hello everyone, how are you?
I already uploaded an issue about this but it is still happening to me, maybe someone can help me out.
When starting any unfollow task for example:
session.unfollow_users(amount=10, onlyNotFollowMe=True, sleep_delay=60)
I get the following error on the navigator screen, it seems to try to update information but it just stays this way. The log in works fine.
![unfollow issues](https://user-images.githubusercontent.com/38476899/40014487-1919547e-5787-11e8-8b65-b6cdb220094b.png)
My current quickstart.py is looking like this (All other tasks seem to be working fine, but I just want to try the unfollow one since is not working for me anymore) 
![unfollow instapy](https://user-images.githubusercontent.com/38476899/40014648-766269b8-5787-11e8-8f02-ee25d71be150.png)

This is my current Pull status, I got all new modifications:
![status](https://user-images.githubusercontent.com/38476899/40014667-8661fcfc-5787-11e8-8bce-6e37b0f8ef2d.png)

This is the console Error data:
![error unfollow](https://user-images.githubusercontent.com/38476899/40014820-f24c9c06-5787-11e8-8d62-8abbf99bb572.png)

Please, if someone can help me out I would really appreciate it.

Best!

**Comment by redsector72** [comment]
You are missing the last part of the quickstart.py file.
these 2 lines.

```
finally:
    session.end()
```

**Comment by neonvandal** [comment]
The quickstart.py file si complete, I just added my configuration part for more information

![complete](https://user-images.githubusercontent.com/38476899/40019079-93b38ecc-5794-11e8-94d4-9066b2c77f51.png)

**Comment by neonvandal** [comment]
Maybe @uluQulu knows about this? :)

**Comment by uluQulu** [comment]
hi @neonvandal,
`onlyNotFollowMe` method of `unfollow_users` feature uses graphql queries to get data. But if you use other method- `onlyInstaPyFollowed`, it will not request that screen, instead will get data from a local CSV file (**username_followedPool.csv**).
Please, have a read https://github.com/timgrossmann/InstaPy/issues/2010#issuecomment-388662620.
If you still have a problem, ask again, Hopefully, I will help.

**Comment by neonvandal** [comment]
Thank you so much! @uluQulu 
I will try to complete this task and see if it is working correctly.
One quick question : It is possible that staying in that query state for long periods will result on any type of ban or something? Is there a safety check ? 
Cheers!

**Comment by uluQulu** [comment]
My pleasures @neonvandal,
To be honest, I think querying too much (_like, getting the list of hundred thousands of users_) in **short** periods of time would bring unwanted results.
Also staying in the same page too long does not matter.
