### ISSUE TITLE
ERROR [2018-05-15 09:24:56] [XXX]  following_link error list index out of range

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2024]
Hi,
I get the error ERROR [2018-05-15 09:24:56] [XXX]  following_link error list index out of range
when trying to unfollow.
It has always worked before and now suddenly it stopped working, I've tried to just unfollow one person and so on but nothing makes it work.

Any clue?

**Comment by ceribbo** [comment]
Same error here

**Comment by thesamgoodman** [comment]
same error!

**Comment by fgisslen** [comment]
Solved in #2031 with:
this change will solve your issue:
open up unfollow_util.py file,

find and replace

following_link = browser.find_elements_by_xpath(
    '//article//ul//li[3]')
with

following_link = browser.find_elements_by_xpath(
    '//section//ul//li[3]')
just replaced article with section
