### ISSUE TITLE
Error: Couldn't get user profile. Moving on..

### ISSUE THREAD

**Issue by tanmald** [InstaPy/InstaPy#2025]
I can't seem to be able to use "follow_commenters" today. Yesterday it was working fine. I already updated instaPy, but I still get the same error, even though I can see Chrome is at the user profile - it seems that it cant select any pictures, and thus it gives this error. 

INFO [2018-05-15 08:37:09] [XXX]  Following commenters of 'YYY' from pictures in last 365 days...
Scrapping wall..

Error: Couldn't get user profile. Moving on..
INFO [2018-05-15 08:37:35] [XXX]  Noone commented, noone to follow.

**Comment by kangxianying** [comment]
got the same problem..

**Comment by ravashjalil** [comment]
same issue as well

**Comment by umluizlima** [comment]
Same issue here.

**Comment by michaellafrasse** [comment]
News about this issue?

**Comment by GangsterEmpire1** [comment]
I have have the same error. Any update?

**Comment by tanmald** [comment]
no news here, I am still having this issue even with latest release

**Comment by davidkessler-ch** [comment]
yes same here.. quite an important feature failing.. this needs to get fixed soon

**Comment by johnowe04** [comment]
Same issue for me.

**Comment by johnowe04** [comment]
Does anyone want to share any of their scripts they have up and working?  I am working on a project for a fashion blogger and would like any tips possible!  This is a feature I would love to have working though...

**Comment by argentgagner** [comment]
Same here!
This function was created by @justdvl (see this pull: #1682)

**Comment by sambrucejoseph** [comment]
Anyone has any updates on this?
I think the problem is with the `xpath` or updated class names by Instagram

**Comment by david-vendel** [comment]
Hello guys, I made the fixes and created pull requests.
https://github.com/timgrossmann/InstaPy/pull/2134
For impatient ones, or to test, those are 3 files to update: 
[instapy.zip](https://github.com/timgrossmann/InstaPy/files/2059371/instapy.zip)

**Comment by tanmald** [comment]
Thank you so much David! 👏🏼
