### ISSUE TITLE
Bot doesnt work after 1week

### ISSUE THREAD

**Issue by oniek** [InstaPy/InstaPy#2027]
Hello, I installed bot like 1 week ago and everything was fine. Bot was working with crontab on debian server (digitalocean, SMP Debian 4.9.88-1+deb9ul) but today it doesnt work right.

## Current Behavior
Script/configuration file is running w/o any problems. I got information about logged into my account etc (logs below). Bot says about liked, commented or followed someone but he didnt do that - after or during every session I was checking any given like or comment in my instagram app and I didnt see anything 👎 .

`INFO [2018-05-15 13:48:46] [getemspider]  [1/50]
INFO [2018-05-15 13:48:46] [getemspider]  https://www.instagram.com/p/BizAV-ylnBH/?tagged=polishgir                  l
INFO [2018-05-15 13:48:53] [getemspider]  Image from: szlagowskamagda
INFO [2018-05-15 13:49:00] [getemspider]  User: szlagowskamagda >> followers: 830  |  following: 75                  02  |  relationship ratio: 0.11
INFO [2018-05-15 13:49:00] [getemspider]  --> Image not liked: szlagowskamagda is not a potential u                  ser with the relationship ratio of 0.11
INFO [2018-05-15 13:49:00] [getemspider]  [2/50]
INFO [2018-05-15 13:49:00] [getemspider]  https://www.instagram.com/p/BizAVtRAAez/?tagged=polishgir                  l
INFO [2018-05-15 13:49:05] [getemspider]  Image from: mymixedlife_
INFO [2018-05-15 13:49:12] [getemspider]  User: mymixedlife_ >> followers: 1967  |  following: 992                    |  relationship ratio: 1.98
INFO [2018-05-15 13:49:12] [getemspider]  Link: https://www.instagram.com/p/BizAVtRAAez/?tagged=pol                  ishgirl
INFO [2018-05-15 13:49:12] [getemspider]  Description: #lunch#at#work#watermelon #watermelon🍉 #arb                  uz#arbuzowelove #i#love#spring#happy#me#polishmum#polishgirl#
INFO [2018-05-15 13:49:15] [getemspider]  --> Image Liked!
INFO [2018-05-15 13:49:17] [getemspider]  --> Not commented
INFO [2018-05-15 13:49:19] [getemspider]  --> Not following`

**Comment by sionking** [comment]
Sure you got like blocked. Digital Ocean ip address are marked.

**Comment by oniek** [comment]
@sionking  For sure I dont have block because I can like, comment or follow anyone on my app. Do you mean ip server could get ban? Anyway before that I had poblem only with liking (somedays) now Bot cant do anything

**Comment by CharlesCCC** [comment]
@sionking is correct. you got blocked on that IP. you can still do whatever on your app, but not through that IP address. this is so-called "soft-banned". please stop for couple days, and reduce amount of likes.
