### ISSUE TITLE
Getting number of likes per post

### ISSUE THREAD

**Issue by thehon** [InstaPy/InstaPy#203]
Would it be possible to add a feature whereby the number of likes per post found is recorded?

**Comment by timgrossmann** [comment]
Could you specify this more?

I'm not really sure what you mean...

**Comment by thehon** [comment]
I think it would be helpful if the tool could record the number of likes/views each post has when it stumbles across them through the like_by_tags. Furthering on from this it would be a great extension to have a threshold of likes similar to follows

**Comment by s0kil** [comment]
Like Media, if less or more than X amount of likes.

**Comment by timgrossmann** [comment]
@thehon @DanielSokil 
This already is a feature...

```python
session.set_lower_follower_count(limit = 1)
session.set_upper_follower_count(limit = 250)
```

Check out the readme to get an explanation of what this does

**Comment by thehon** [comment]
That is different to what I am suggesting . That limits followers not the
amount of likes on the individual post

**Comment by timgrossmann** [comment]
@thehon I'm not really sure what this feature should be good for...
The amount of likes on a post is highly dependant on time... Even a large account will have very few likes if it has been posted like 5 seconds ago. 

A time dependant feature (which depends on seconds / followers at least on minutes or hours) will probably not have a high priority, sorry.

**Comment by thehon** [comment]
Fair enough thanks anyway

**Comment by timgrossmann** [comment]
@thehon Feel free to develop this feature and contribute to InstPy 😉

**Comment by thehon** [comment]
Working on it

**Comment by ujazzz** [comment]
I think what OP means is when liking based on tags or geo locations there would be some post that might have more than 1K likes. It really wouldnt be necessary to like those posts as they will be buried under lots of like notifications. It would be better to set a limit to the likes a post has. so basically telling the system to like the posts only when the posts has less than 100 likes for example and to skip if the like exceeds 100.
