### ISSUE TITLE
Question regarding like_by_feed()

### ISSUE THREAD

**Issue by HermanoCrespo** [InstaPy/InstaPy#2030]
Hi

I've checked the help file and am a bit confused by the behaviour of 

`session.like_by_feed(amount=like_count_feed, randomize=True, interact=True)`

In the help it says:
`# This is used to perform likes on your own feeds`

and I always assumed that the function would interact with my community of people that I am previously following.

However, the log file tells a different story.

`INFO [2018-05-14 18:21:54] [user]  New link found...`
`INFO [2018-05-14 18:21:54] [user]  [1 posts liked /3 amount]`
`INFO [2018-05-14 18:21:54] [user]  https://www.instagram.com/p/LINK/`
`INFO [2018-05-14 18:21:58] [user]  Image from: b'user2'`
`INFO [2018-05-14 18:22:05] [user]  User: user2 >> followers: 871  |  following: 3312  |  relationship ratio: 3.80`
`INFO [2018-05-14 18:22:05] [user]  Link: b'https://www.instagram.com/p/LINK/'`
`INFO [2018-05-14 18:22:05] [user]  Description: "REMOVED"`
`INFO [2018-05-14 18:22:08] [user]  --> Image Liked!`
`INFO [2018-05-14 18:22:10] [user]  --> User followed: ['user2']`
`INFO [2018-05-14 18:22:10] [user]  Username [1/1]`
`INFO [2018-05-14 18:22:10] [user]  --> b'user2'`
`INFO [2018-05-14 18:22:10] [user]  Getting user2 image list...`
`INFO [2018-05-14 18:22:41] [user]  Interaction begin...`

It looks to me as if it interacts with a user that I was not following before, hence the line

`INFO [2018-05-14 18:22:10] [user]  --> User followed: ['user2']`

So, question:
What feed is it using if not my followings?
Is there a way to interact only with people that I am following already?

**Comment by uluQulu** [comment]
Well @HermanoCrespo,
Actually `like_by_feed` feature really is getting links from your `FeedPage` but there is an interesting thing. In your feed page, IG shows up feed also from new people to you whom you are not following but might interest you.  
That's why it does do `follow` those new people sometimes (_but well, you can disable following, with `set_do_follow` setting before running that feature_).
Also, if you really want to interact with the people you are following, then run `interact_user_following` with your own `username` xD
>But you can actually customize `like_by_feed` to interact only with the people you are following, but it will not be efficient approach.

**Comment by HermanoCrespo** [comment]
Thanks uluQulu, I understand a bit better now and will implement your suggestions.

Just to make sure:
`session.interact_user_following()` is an action and can be run with other actions without affecting the settings, right?

**Comment by uluQulu** [comment]
Not at all, @HermanoCrespo,
Right. Actions cannot modify settings, they just use settings.

**Comment by HermanoCrespo** [comment]
That's quite smart by the way to use this function for my own feed with my username. Hats off :)

**Comment by HermanoCrespo** [comment]
Following up, there are 
`session.interact_user_following(['natgeo'], amount=10, randomize=True)`
`session.interact_user_followers(['natgeo'], amount=10, randomize=True)`

The help says the same thing for both functions
`# Interact with the people that a given user is following`

If I want to interact with the followers of natgeo, I use `interact_user_followers`
if I want to interact with whoever natgeo is following I use `interact_user_following`

Is my understanding correct?
Thanks

**Comment by uluQulu** [comment]
That's right @HermanoCrespo,
The mechanism works correctly as you have expected but in documentation it is written wrong and it is what causes confusion.
```erlang
### Interact with someone else's followers
```python
# Interact with the people that a given user is following
```

must be
```erlang
### Interact with someone else's followers
```python
# Interact with the followers of a given user
```
Can you PR the correct form of README?

**Comment by HermanoCrespo** [comment]
Thank you, that's what I thought.

> Can you PR the correct form of README?

Are you asking me? I guess not. But if you are, I do not understand the question and think 'no' is the answer.

Cheers

**Comment by uluQulu** [comment]
It is your catch, @HermanoCrespo, so I thought you could pull a request containing that change and really, it is very easy to pull a request!
I am sure you like to contribute, helping out people, don't you? 😁

**Comment by HermanoCrespo** [comment]
Done.

**Comment by uluQulu** [comment]
Great @HermanoCrespo
I think you should first merge it into your fork and then pull a request in main repo with your fork.  
_so that it could be merged into main repo_

**Comment by spikeyhair** [comment]
I am expecting this feature is to like the posts on my feed only but I notice it also comment posts (even with the interact option set to false). Is it supposed to work this way or this is a logical bug in the script?

session.like_by_feed(amount=4, randomize=True, unfollow=False, interact=False)
