### ISSUE TITLE
InstaPy crashes on like_by_tags

### ISSUE THREAD

**Issue by danieledelsale** [InstaPy/InstaPy#2032]
## Expected Behavior

session.like_by_tags(['natgeo', 'world'], amount=10) should like 10 photos tagged with "natgeo" and "world"
## Current Behavior

Crash after selecting first tag.

 File "quickstart.py", line 38, in <module>
    session.like_by_tags(['natgeo', 'world'], amount=10)
  File "/home/delsi/Programs/InstaPy/instapy/instapy.py", line 1082, in like_by_tags
    skip_top_posts)
  File "/home/delsi/Programs/InstaPy/instapy/like_util.py", line 197, in get_links_for_tag
    "//span[contains(@class, '_fd86t')]").text)
  File "/home/delsi/Programs/InstaPy/instapy/util.py", line 342, in format_number
    return int(formatted_num)
ValueError: invalid literal for int() with base 10: ''

#InstaPy Configuration

This is my quickstart.py

import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = 'DELETED'
insta_password = 'DELETED'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()

    session.set_relationship_bounds(enabled=True,
				 potency_ratio=None,
				  delimit_by_numbers=True,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    session.set_delimit_liking(enabled=True, max=300, min=5)

    session.set_user_interact(amount=2, randomize=True, percentage=50, media='Photo')
    session.like_by_tags(['natgeo', 'world'], amount=10)
    session.follow_likers (['humansafari' , 'seantuck'], photos_grab_amount = 2, follow_likers_per_photo = 3, randomize=True, sleep_delay=600, interact=False)
except Exception as exc:
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    raise

finally:
    session.end()

**Comment by uluQulu** [comment]
Hi @ddelsi,
It looks weird.
Please, open up **util.py** file and make these modifications to `format_number` definition:
```erlang
    print("\n\nNumber == `{}`  |  type: {}\n".format(number, type(number)))   ##ADD this line
    formatted_num = number.replace(',', '')
    print("\n\nFormatted_num1 == `{}`\n".format(formatted_num))   ##ADD this line
    formatted_num = re.sub(r'(k)$', '00' if '.' in formatted_num else '000', formatted_num)
    print("\n\nFormatted_num2 == `{}`\n".format(formatted_num))   ##ADD this line
    formatted_num = re.sub(r'(m)$', '00000' if '.' in formatted_num else '000000', formatted_num)
    print("\n\nFormatted_num3 == `{}`\n".format(formatted_num))   ##ADD this line
    formatted_num = formatted_num.replace('.', '')
    print("\n\nFormatted_num4 == `{}`  |  type: {}\n\n".format(formatted_num, type(formatted_num)))   ##ADD this line
    return int(formatted_num)
```
After adding those lines, start up `like_by_tags` feature and post the output of those new lines from console.
After taking a screenshot, you can remove those test lines.
_I wonder where it does purge that number into empty string, maybe it does not even get correct number from the element, but we will determine it after this test._

Also, have a read https://github.com/timgrossmann/InstaPy/issues/1924#issuecomment-385247307 for other workaround.

Good luck!

**Comment by danieledelsale** [comment]
Output:

INFO [2018-05-17 14:42:59] [USERNAME]  Session started - 2018-05-17 14:42:59
INFO [2018-05-17 14:43:28] [USERNAME]  Logged in successfully!
INFO [2018-05-17 14:43:29] [USERNAME]  Tag [1/2]
INFO [2018-05-17 14:43:29] [USERNAME]  --> b'natgeo'


Number == ``  |  type: <class 'str'>



Formatted_num1 == ``



Formatted_num2 == ``



Formatted_num3 == ``



Formatted_num4 == ``  |  type: <class 'str'>


INFO [2018-05-17 14:43:37] [USERNAME]  Session ended - 2018-05-17 14:43:37
INFO [2018-05-17 14:43:37] [USERNAME]  --------------------


Traceback (most recent call last):
  File "Programs/InstaPy/quickstart.py", line 38, in <module>
    session.like_by_tags(['natgeo', 'world'], amount=10)
  File "/home/delsi/Programs/InstaPy/instapy/instapy.py", line 1082, in like_by_tags
    skip_top_posts)
  File "/home/delsi/Programs/InstaPy/instapy/like_util.py", line 197, in get_links_for_tag
    "//span[contains(@class, '_fd86t')]").text)
  File "/home/delsi/Programs/InstaPy/instapy/util.py", line 347, in format_number
    return int(formatted_num)
ValueError: invalid literal for int() with base 10: ''

Hope this helps... I'll try to take a better look at the code myself during this weekend and if i find anything I'll let you know.

**Comment by danieledelsale** [comment]
Now it works just by himself. Never edited anything of the code. Really don't know what to think. Maybe some changes serverside(?). Anyway if it keeps working for the next 24h i'll close the issue

**Comment by uluQulu** [comment]
It's clear now @ddelsi,
It returns an empty string by hitting a wrong element after a possible layout change. And it's best to add the workaround in https://github.com/timgrossmann/InstaPy/issues/1924#issuecomment-385247307 as an alternative in case of element absences.  
>I will try to look at it after my current PR moves around.
