### ISSUE TITLE
Chrome tries to click the follow button but get error 400

### ISSUE THREAD

**Issue by Amirala7** [InstaPy/InstaPy#2035]
## Expected Behavior
follow given users followers 
## Current Behavior
Instapy has been normally working, I'm using the follow user followers session, in the console everything is working perfectly, and the csv is getting filled with the new users getting "followed" but what actually is happening is that chrome clicks the follow button but receives the following error in the chrome console : Failed to load resource: the server responded with a status of 400 () but the error does not interfere with instapy so it keeps going. I tried with different users and all are same, but like function seems to be working. Also the same users have been checked and they are not blocked and can follow users via safari, Firefox and the app.

**Comment by Amirala7** [comment]
@timgrossmann @uluQulu any ideas ?

**Comment by uluQulu** [comment]
@Amirala7,
_smells like a targeted restriction_
Would you mind testing with other logins within the same setup?
>It can be due to the excessive usage, think about it whether you have did and if so, immediately stop further excessive interactions on that login and give it a good rest to recover new requests back 👍
