### ISSUE TITLE
Not able to let Instapy work

### ISSUE THREAD

**Issue by Pithub90** [InstaPy/InstaPy#2036]
Hello everyone, I'm trying to install and use Instapy but i am not able, in the point 3.1 of the installation guide

> (Install Selenium
> Go to C:\Program Files (x86)\Python36-32\Scripts
> press Shift + Right click and open command window (with admin rights !!) and type
> pip install selenium
> python -m pip install pyvirtualdisplay
> py get-pip.py) 

when I try to do the command "py get-pip.py" I get **[Errno 2] No such file or directory**

I tryed also to go ahed with the installation and when i open the gui and i set for example to like 5 photos with a hashtag and i press RUN  i get "Instapy running" but nothing happens

(and btw right now i need the bot to like the newest photo from a list of for example 300 usernames, how can i do that?)

thank you so much

**Comment by uluQulu** [comment]
hi @Pithub90,
Well, you should know that,
>`pip` is already installed if you are using Python 2 >=2.7.9 or Python 3 >=3.4 downloaded from python.org

If you insist to re-install it through `get-pip.py` which is the ways of installing `pip` manually, alongside `setuptools` and `wheel` (_you can install the other two with pip, too_)
first [download](https://bootstrap.pypa.io/get-pip.py) `get-pip.py` securely by running
```erlang
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
```
then install it with
```erlang
python get-pip.py
```
or
```erlang
py get-pip.py
```  


And for the usage, I would recommend getting familiar with quickstart script and writing your own script by hand (_read `README` and see examples_).
Particularly for liking fresh content of a set of users,
```erlang
session.set_do_like(enabled=True, percentage=100)
session.like_by_users(usernames=['user1', 'user2', 'user3', 'user299', 'user300'], amount=1, randomize=False, media='Photo')
```
_will like 1 photo from top of feed of all 300 users_

**Comment by Pithub90** [comment]
thank you so much for your reply, the problem is that i am really new to this, so i am not able to follow your instructions, if you can explain me better, considering that I do not understand anything about python  i will be really really grateful

thank you

**Comment by uluQulu** [comment]
Not at all, @Pithub90,
Alright, considering that you have not installed `get-pip.py`, now run these commands to get `setuptools` and `wheel` which are very useful,
```erlang
pip install -U setuptools
```
after it installs, install the other
```erlang
pip install -U wheel
```

Now I can guess that you have everything installed to run the program.
It is time to start **quickstart** script!
_navigate to the folder holding your InstaPy files_,
```erlang
cd C:\Users\shahr\Documents\GitHub\InstaPy_fork\
```
_and start your quickstart script_,
```erlang
python quickstart.py
```
_or_
```erlang
py quickstart.py
```

The rest is up to your **quickstart** style, if gets any other error, just ask me for help ✌️ 
>Note: You will need a good text editor like **Notepad++** or **Atom** to edit **quickstart** script and other files.

**Comment by Pithub90** [comment]
> after it installs, install the other
> 
> pip install -U wheel

I am here, then i don't know how can i do what you said next

> ( It is time to start quickstart script! etc..)

  hahaha please help me

EDIT
by the way i don't know also what this means from the guide

> 4. Edit the instapy.py file
> Open file instapy.py an disabling the clarifai import
> comment the line "from .clarifai_util import check_image"
> from .clarifai_util import check_image

**Comment by uluQulu** [comment]
@Pithub90,
I think those steps are very clear.
Could you at least install `wheel`?

4. point means you must comment out that line
so, in **instapy.py** file
```erlang
from .clarifai_util import check_image
```
will be
```erlang
#from .clarifai_util import check_image
```

**Comment by Pithub90** [comment]
yes i installed wheel ( or i think so)

point means you must comment out that line
so, in instapy.py file   **# <---- where is this file?** 
from .clarifai_util import check_image
will be

#from .clarifai_util import check_image

**Comment by uluQulu** [comment]
@Pithub90,
Now navigate to that folder and start **quickstart** script
What is that you cannot do?

**Comment by Pithub90** [comment]
i don't know how can i start quickstart script?  (and also what is quickstart script)

**Comment by uluQulu** [comment]
@Pithub90,
It is just a python source file with `.py` extension which can be of any name, but calling **quickstart** makes it easy to understand amongst many people.
_start your quickstart script simply by running_
```erlang
python quickstart.py
```
_in command prompt_

**Comment by Pithub90** [comment]
so on my keyboard i press the windows simbol+R then cmd, then i write "python quickstart.py" 

i get some error, like python quickstart.py is not a comand

**Comment by uluQulu** [comment]
@Pithub90,
Before running
```erlang
python quickstart.py
```
You must navigate to the folder holding **quickstart,py** file otherwise command prompt will not be able to find it to execute.

Also, it seems you must add Python to your PATH in order to execute `python` commands.

**Comment by Pithub90** [comment]
don't know this things are difficult for me, how can i add python to my path?

thank you so much for the help btw

if was this 

> 2. Set python evironment:
> Open Control Panel » System » Advanced » Environment Variables.
> Click New and type the path where you have installed Python + /Scripts
> Usually PATH: C:\Program Files (x86)\Python36-32\Scripts\ and C:\Program Files (x86)\Python36-32\
> Win7 and Win10 PATH: C:\Users\YOUR_USER_NAME\AppData\Local\Programs\Python\Python36\ and C:\Users\YOUR_USER_NAME\AppData\Local\Programs\Python\Python36\Scripts\
> Restart PC (recommended).

i think i have done this,

**Comment by uluQulu** [comment]
@Pithub90,
1. Find where Python is installed in your system, for example for me it is
```erlang
C:\Users\shahr\AppData\Local\Programs\Python\Python36\
```
2. Press `Windows key`+`Pause` key in your keyboard to open up `System`
3. On the left panel find and click `Advanced System Settings`
4. In the opened window click `Advanced` tab and then click on `Enviromental Variables`
5. On the top side, click on `PATH` and then click on `Edit`
6. Click on `New`
 * Paste the location of `Python` and press `Enter`
```erlang
    C:\Users\shahr\AppData\Local\Programs\Python\Python36\
```
 * Paste the location of `Python` `Scripts` and press `Enter`
```erlang
    C:\Users\shahr\AppData\Local\Programs\Python\Python36\Scripts\
```
7. Click on `OK` buttons.
You are done!

**Comment by Pithub90** [comment]
> 5 On the top side, click on PATH and then click on Edit
> 6 Click on New

if i click on edit will change something that was already there, or am i wrong?

(btw if we can talk via a messaging app, like google hangouts will be so much better so i could send you also some photo of the screen of the pc to understand better what am i doing)

**Comment by uluQulu** [comment]
@Pithub90,
It can change something or add a new thing.
Well I got [FB](https://www.facebook.com/shahriyar.guliyev) if is helpful.

**Comment by Pithub90** [comment]
yes it's ok, sent a message there

**Comment by uluQulu** [comment]
At the year of 2012, GitHub removed Private Messaging feature 🔨 🤒
Email is still the best way to contact someone and if you want to contact me, please see the public email address at my profile.
>Onwards, I do not really use mobile messaging apps ✌️ 

_Also you can join the Slack channel of InstaPy and get help by thousands!_

**Comment by Pithub90** [comment]
okok i sent you a message on facebook, or if you want we can talk also here, since i think you almost solved my problem, thanks again

**Comment by uluQulu** [comment]
Not at all, @Pithub90,
_We learn more when helping out people, especially beginners :)_

**Comment by jp-sjc** [comment]
Nice, this issue helped me a lot.Ty
