### ISSUE TITLE
Error python quickstart.py

### ISSUE THREAD

**Issue by S4nderr** [InstaPy/InstaPy#2037]
Hi guys,

I've done all the installations from [https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Windows.md](url)

Except:

3.2 Download the GUI (optional)
Download the zip-File from the GUI-tool-for-InstaPy-script.
follow the install instructions on this page.
don't forget to copy the *.exe files in the folder InstaPy-master.
[https://github.com/Nemixalone/GUI-tool-for-InstaPy-script]

Because site is not found.

When I run: `python quickstart.py`

I got the following errror:

`C:\Users\Sander\Documents\GitHub\InstaPy>python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 7, in <module>
    from instapy import InstaPy
  File "C:\Users\Sander\Documents\GitHub\InstaPy\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "C:\Users\Sander\Documents\GitHub\InstaPy\instapy\instapy.py", line 19, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

Hope someone can help I am really new to this.

Sander

**Comment by uluQulu** [comment]
Hi @S4nderr,
You must have `requests` module in order to use it, install it by running
```erlang
pip install -U requests
```
in command prompt

**Comment by S4nderr** [comment]
Thanks!
