### ISSUE TITLE
session.like_by_tags with 5 or more tags sets amount from 100 to 32

### ISSUE THREAD

**Issue by saphuttu** [InstaPy/InstaPy#204]
session.like_by_tags(['#a','#b','#c','**#d**','**#e**','**#f**','#g','#h','#i'], **amount=100**)

When i'm having more than 5 tags the amount is changing from 100 -> 32. Anyone else having this? Can i test something that could be affecting this?

Tag [4/9]
--> #d
**[1/100]**

Tag [5/9]
--> #e
**[1/32]**

Tag [6/9]
--> #f
**[1/32]**

**Comment by pekapa** [comment]
Looks like your Chrome window in in the background and the script is unable to fetch more images so, instead of getting stuck waiting for you to bring focus to the browser it works with the images it was able to fetch (i.e. the ones from the page loaded + the first extra load)

**Comment by timgrossmann** [comment]
@saphuttu yes, that's the problem with minimizing or moving the window in the background...

**Comment by saphuttu** [comment]
OK thanks guys!
