### ISSUE TITLE
follow_likers(interact = True) does not interact

### ISSUE THREAD

**Issue by HermanoCrespo** [InstaPy/InstaPy#2045]
## Expected Behavior
The code
`session.set_relationship_bounds(enabled=True, potency_ratio=-1.22, delimit_by_numbers=True, max_followers=1585, max_following=5555, min_followers=45, min_following=77)`
`session.set_do_comment(False)`
`session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')`
`session.set_do_follow(enabled=True, percentage=18, times=2)`

`session.follow_likers(['List1', 'List2'], photos_grab_amount=1, follow_likers_per_photo=5, randomize=True, sleep_delay=500, interact=True)`

Should interact with likers of List1's and List2's images. I would expect it to like three of their images and then follow them.

## Current Behavior

The log
`INFO [2018-05-17 22:51:49] [USER]  Starting to follow likers..`
`INFO [2018-05-17 22:52:13] [USER]  --> USER2 instagram account is opened...`
`INFO [2018-05-17 22:52:23] [USER]  ---> Now following: USER2`
`INFO [2018-05-17 22:52:26] [USER]  Total Follow: 1`
`INFO [2018-05-17 22:52:30] [USER]  --> USER3 instagram account is opened...`
`INFO [2018-05-17 22:52:42] [USER]  ---> Now following: USER3`
`INFO [2018-05-17 22:52:44] [USER]  Total Follow: 2`

No interaction is happening.

## InstaPy configuration
latest files, updated 14 hours ago before running today's batch.

Cheers

**Comment by matthewhannan** [comment]
I'm having this same problem - I would also appreciate a solution!

**Comment by HermanoCrespo** [comment]
I checked interact on hashtags with the same files and it works fine, for what it's worth.

So far only follow_likers is affected.

**Comment by uluQulu** [comment]
Hi @HermanoCrespo, @matthewhannan,
Have a read https://github.com/timgrossmann/InstaPy/issues/2019#issuecomment-388889341 to understand the mechanism and find a solution.
Good luck!

**Comment by HermanoCrespo** [comment]
Thank you. I had a look and from what I understand now I need to enable likes as well with

`session.set_do_like(enabled=True)`

Enabling interactions is not enough, you need to tell the script how to interact.

also for comments:
`session.set_do_comment(enabled=True, percentage=10)`

One more thing, following up on that. I know one should define settings before actions.

However, my script has become quite nested with a lot of different kinds of activity and I would like to change settings between them.

Can I run one setting first, say

`session.set_do_like(Settings)`
`session.set_user_interact(Settings)`
`session.follow_likers()`


Then do some other activity
`Do other stuff here, like unfollow`

and then come back to settings and change them?
`session.set_do_like(different settings)`
`session.set_user_interact(different settings)`
`session.follow_commenters()`

Cheers!

**Comment by uluQulu** [comment]
Glad to help @HermanoCrespo,
_every new **set**ting line overwrites its previous values_
Moreover, re-starting **set**tings with new values generates more fascinating and efficient activity flow

**Comment by HermanoCrespo** [comment]
That's what I thought, cool. Thanks.
A lot of tweaking can be done on the script, wow. It is quite powerful

**Comment by charlyonboard** [comment]
Hello ! I'm having an issue a bit different from the one above. 

The set_user_interact command CRASH everytime I'm running the code.

Does anyone have an idea of how to make it work ?

session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
session.set_do_like(enabled=True, percentage=70)
session.interact_user_followers(['tasjoui'], amount=10, randomize=True)

Same error withe the following request : 
session.follow_user_followers(['tasjoui'], amount=10, randomize=True, sleep_delay=900)

Thank you guys !
