### ISSUE TITLE
link_elems error Message: no such element: Unable to locate element

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2046]
Getting xxx image list...
ERROR [2018-05-18 06:41:36] [xxxw]  link_elems error Message: no such element: Unable to locate element: {"method":"tag name","selector":"main"}
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.16299 x86_64)

I am getting it in all my accounts.

**Comment by CharlesCCC** [comment]
mine seems fine ? are you still having this issue ?

**Comment by sionking** [comment]
not any more, probably local server issue.
