### ISSUE TITLE
Absolute paths

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#205]
I ran twice in issues with paths in instapy.py:
1. When I tried to add a cronjob for ```python /my/path/to/instapy/quickstart.py``` and tested it with bash mode `env -i /bin/bash --noprofile --norc`
2. When I tried to use InstaPy with [command on command line](https://unix.stackexchange.com/a/101531) mode

InstaPy would stop executing with following message:

```
File "/usr/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x246cfd0>> ignored
```

Both could be resolved by using absolute paths for ```/assets/chromedriver``` and all other relative paths (e.g. logs)

I guess we should update instapy.py accordingly.

**Comment by eduardocalazansjr** [comment]
Absolute path will break this in other OSes.

The error is pretty clear, just add the InstaPy path to your path variables before running the script (and you can call python quickstart.py)

(Also could happen when you ALREADY have chromedriver installed in another directory (/usr/bin)

**Comment by tibor** [comment]
Why would [`os.path.abspath`](https://docs.python.org/2/library/os.path.html) break the script in other OS?

**Comment by eduardocalazansjr** [comment]
`os.path.realpath` with windows depending of the directory full path length will break.

It doesn't seems like a right way out, since every binary on python scripts on the web that runs via cronjob or another automation system needs to be on PATH variable.
Take another look on the error, see the message, chromedriver itselfs says that it needs to be on PATH.

**Comment by tibor** [comment]
So, how would I do this in CentOS?

If this is a necessary step, we should add it in the how to guides, too I’d think.

**Comment by timgrossmann** [comment]
Absolute path is not good...
The cronjob simply starts a new command line session, so the solution to this to to use this as the command to Ben executed...

```
cd /home/InstaPy && python3.5 QuickStart.py

**Comment by tibor** [comment]
Yeah, I’m using this already in my crontab (copied from #46).

What would be your solution to keep InstaPy running on the server when you aren’t connected anymore via SSH? At the moment InstaPy stops then, so command on command-line was my try to solve this.

**Comment by timgrossmann** [comment]
@tibor That's not a InstaPy related Issue...

I also tried that, but couldn't find a working solution. But I need to mention that I did not try out the given tools to only start the script on the machine. I don't know what they were called anymore...

Also, the `cd /home/InstaPy && python3.5 QuickStart.py` one works... I'm using that for nearly 5 months now

**Comment by eduardocalazansjr** [comment]
Use `nohup` before calling the script.

Use `export PATH=/Path/to/instapy:$PATH` to add the instapy folder to the PATH variable BEFORE running the script.

Also, read your distro documentation for basic knowledge of background service/tasks, since @timgrossmann said "That's not a InstaPy related Issue..."
