### ISSUE TITLE
problem with using proxy 

### ISSUE THREAD

**Issue by nickcaoz** [InstaPy/InstaPy#2052]
## Expected Behavior
running with proxy
## Current Behavior
proxy_port=8800, => TypeError: unorderable types: str() > int()
proxy_port='8800', => TypeError: sequence item 1: expected str instance, bytes found

changing 
"if self.proxy_address and self.proxy_port > 0:" 
to
"if self.proxy_address and int(self.proxy_port) > 0:"
in instapy.py 
solved the start problem, but always getting this Warning/Error while interacting:
WARNING [2018-05-18 20:16:55] [accountname] Can't interact with private account

without proxy everything works fine, but I need to run multiple acc at the same time, so proxy would be necessary, hope you guys can help me

**Comment by ShiftingKill** [comment]
It's hard to be anonymous on the internet, are you sure you need a proxy? Unless you're hiding from others on your network. Instagram will always see your ip I think.
Running 2 accounts on the same network no matter what is a little sketchy.
https://security.stackexchange.com/questions/67748/will-the-cookies-crumble-when-it-comes-to-proxy-servers
