### ISSUE TITLE
How to backup folowers and following

### ISSUE THREAD

**Issue by Nocturnal-2** [InstaPy/InstaPy#2053]
## Expected Behavior

I have been running this tool for past couple of weeks, mostly liking and commenting. I am planning to run follow methods for the first time. Before I do that I would like to backup my current followers and following for two reasons:

1. I would know whom I willingly followed to see their content
2. If in case my account is blocked, I create a new account and follow the users whom I am current following

## Possible Solution (optional)

I would like to know if InstaPy already keeps track of whom it followed.

**Comment by uluQulu** [comment]
hi @Madhu-sudhanan,
>I would like to know if InstaPy already keeps track of whom it followed.

Yes, it is stored in **username_followedPool.csv** file in **logs** folder

_But getting the list of all of your current `followers` & `following` is another story. Do you really want to implement it?_

**Comment by Nocturnal-2** [comment]
@uluQulu I apologize for the delay in reply. Yes, I think this will be useful!

By the way, I changed my display name :)

**Comment by uluQulu** [comment]
Hey @Nocturnal-2 
After your and some other guys requests, I made it happen and implemented those features and a few others and now they are ready to use.

I will share them in my next PR after the current one #2086 :)

**Comment by Nocturnal-2** [comment]
Thank you so much @uluQulu ! 

I hope to get better at Python and start contributing soon! :)
