### ISSUE TITLE
Similar issue to Newbie Help - Example.py error

### ISSUE THREAD

**Issue by SamuelMTDavies** [InstaPy/InstaPy#206]
Hi,

I am rather new to Python and have been learning primarily in python 2.7.

I have both 2.7 and 3.5 installed and I have installed Selenium and pyvirtualdriver using pip3.5

I have been trying to run my example.py file and I receive the following error.

`Traceback (most recent call last):
  File "example.py", line 2, in <module>
    from instapy import InstaPy
  File "/Users/Sam/sm_bots/Instagram/InstaPy-master/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/Users/Sam/sm_bots/Instagram/InstaPy-master/instapy/instapy.py", line 10, in <module>
    from .clarifai_util import check_image
  File "/Users/Sam/sm_bots/Instagram/InstaPy-master/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.client import ClarifaiApi
ImportError: No module named 'clarifai'`

My scripts have more login credentials for my Instagram and Clarifai in them.

I understand that it is not finding the clarifai module - but I am unsure where it should be finding it.

@timgrossmann I want to thank you for putting this together. 

The issue I believe myself and other people newer to programming are getting is there is a big step up between knowing the basics and then moving to larger more complex programs such as this and the jump in online materials goes from too simple to too complex with little in between.

I would really appreciate the opportunity to work through the issues I am having so that I learn as much as possible and avoid making the same mistakes in the future.

Best Regards,

Sam

**Comment by timgrossmann** [comment]
@SamuelMTDavies 
```bash
pip install clarifai
#or
pip3.5 install clarifai
```

If it says `No module named x`, just do `pip install x`

**Comment by SamuelMTDavies** [comment]
Wow. I feel a little silly now. I missed that it was a library that needed to be installed. 

I will check to see if it now works and report back. 

Can you keep the issue open until I confirm?

Thanks

**Comment by SamuelMTDavies** [comment]
I got it all working thanks. Works a treat. 

Does the script run quicker if it's run without the gui? 

What are the limits in terms of number of likes before we get on Instagrams radar do you reckon?

**Comment by s0kil** [comment]
@SamuelMTDavies 
1000 likes in 24hr

**Comment by SamuelMTDavies** [comment]
Thanks Daniel. 

I have everything up and running now. 

Really useful to learn by going through the code. 

Tim - out of curiosity how did you find out and come across selenium and clarifai? 

Being new to python I was wondering where is best to find new modules and what they do/can be used for?

Can you maybe message me and close the issue as I'm aware of not clogging up the issues.

**Comment by timgrossmann** [comment]
@SamuelMTDavies 
Selenium: https://automatetheboringstuff.com
Clarifai: Through a Hackathon 😉 

Just search for problems, e.g. AR in the web browser and google for it. I don't think you will just search for modules you have no use for...
Also, you can subscribe to python newsletters to get information about the newest most interesting tolls
