### ISSUE TITLE
Selenium Logging Location?

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#2063]
Having an issue where likes are saying they happen but don't actually happen. 

I am running my script on a digital ocean droplet, with crontab. A month of so back likes were taking place. But now, they say they happen, but when visiting the asset not action has taken place.

I can run the same script on my local and it works as intended.

Does anyone know where selenium logs write to? Any other assistance is much appreciated.

**Comment by sionking** [comment]
digital ocean  IP are in IG black pool.

**Comment by ghost** [comment]
Ah, makes sense. Closing as non issue.

**Comment by ghost** [comment]
@sionking - Do you know if this is spoofable?
