### ISSUE TITLE
function interact_user_following

### ISSUE THREAD

**Issue by ThomasViennet-zz** [InstaPy/InstaPy#2064]
Hi ! 

I have this problem when I use this  function interact_user_following :
`INFO [2018-05-20 20:51:04] [Chats_de_nos_vies]  Session started - 2018-05-20 20:51:04
INFO [2018-05-20 20:51:42] [Chats_de_nos_vies]  Logged in successfully!
ERROR [2018-05-20 20:52:14] [Chats_de_nos_vies]  following_link error list index out of range
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20180520-205241.html
**********************************************************************
INFO [2018-05-20 20:52:41] [Chats_de_nos_vies]  Session ended - 2018-05-20 20:52:41
INFO [2018-05-20 20:52:41] [Chats_de_nos_vies]  --------------------`

and my quickstart.py
`        session.login()
        # settings
        session.set_user_interact(amount=2, randomize=True, percentage=100)
        session.set_do_follow(enabled=False)
        session.set_do_like(enabled=True, percentage=100)
        session.set_do_comment(enabled=True, percentage=50)
        session.set_comments(["Cool", "Super!", "Top", "Magnifique", "Je suis fan de ton compte"])

        session.interact_user_following(['Chatoune_france'], amount=25, randomize=True)`

Thanks for your help !

**Comment by uluQulu** [comment]
@ThomasViennet
Its fix is included in #2042.
Please read https://github.com/timgrossmann/InstaPy/issues/2058#issuecomment-390434173 for more information.
