### ISSUE TITLE
Instagram action limits?

### ISSUE THREAD

**Issue by bardascat** [InstaPy/InstaPy#2069]
Just a question:

What are the limits for the following instagram actions so that you won't get banned ?
1. Liking  per day
2. Following per day
3. Unfollowing per day

Thanks

**Comment by sionking** [comment]
There is no one answer.
Working on real account and at list 1 year old, 12 hours a day:
1. 60 likes per hour~
2. 25 follow per hour
3. 25 ...

**Comment by bardascat** [comment]
60 likes and 25 follow in the same hour or separate hours, meaning a total
of 2 hours for 60 likes and 25 follow.

Dis you ever got banned with this settings?

Thanks

**Comment by visualheroes** [comment]
I wrote a +-60mins random loop that limit Instapy to 18 interactions per 12 minutes (follow/like/unfollow). I run that loop +-6 times per 24 hours on a very old account (6*90 interactions). 

Before that i used to run Instapy without any limit untill i had a couple of hourly bans. 

**I think the safe number is below 100 interactions per 60mins and below 700 per 24 hours.**

Edit: i gain around 25-30 followers / days with this loop. My gf does the same loop without any following/unfollowing and gains around 5 per days. It's not to aggressive and as my "following" stay the same, it's cleaner. ;)

**Comment by sionking** [comment]
@visualheroes I have only one issue with what you wrote -- the 24/7 run.
We need to act human, run only 10-12 hours a day with breaks.

**Comment by bardascat** [comment]
@visualheroes Do you have any technique regarding what posts you  like/follow(user) in order to boost the return of likes/follow ?
Or you just  specify some regular instagram hashtags inspired by your instagram countent ?

**Comment by visualheroes** [comment]
@sionking 
I think you misunderstood. I never ever run 24/7. Only 4-6 hours per day and those 4-6 hours are scheduled around the busy times of the day: mid-day break (on monday = best engagement), end of the day commute break and evening. 
Also, as i do only 18 interactions max per 12 minutes, my bot sleeps a lot. On some # the 18 interactions are done very quickly and sometimes it takes the full 12 minutes. I also do a random pause between each 12 minutes runs and a +- 10 mins pause between each 1 hour commands. 
It looks way more human that way!

Code wise it's just simple "while loops" as i never coded anything in python before. It's not pretty but it works well.

**Comment by visualheroes** [comment]
@bardascat 
I have all my hashtags on external .txt files, separated by interests (eg: adventure, photography, etc.). I load the external files on random and choose random tags. I also have some displaypurposes hashtag list for each category/interests. 
Usually when i do a new post i switch my hashtag list to a targeted one for some of the loops that day. It works quite well. 

Finally my account is not very focused as i am a photographer and shoot quite a lot of different style for my clients. I think it all depends on your content. It's easier if you have a main focus/style!

**Comment by BalrogFlame** [comment]
Hi @visualheroes , thanks for your tips! 
I am starting with Python as well.
Could you share how you structured the while loop based on time?
Thanks for it!

**Comment by CTZNkjs** [comment]
^ i would like the same if someone is willing to share.  I was trying to ask the same thing on the slack channel.  It would be nice to see some other ideas.  All this info is good to know though.  Thank you

**Comment by visualheroes** [comment]
Hey guys,
My code is very heavily customized so i'll just copy an idea of my structure under here (for you to have a general idea of how i did it.
It's a bit barbarish like this, sorry ;)

```
# loop limits
visualhero_loop_limit_like = 6
visualhero_loop_limit_follow = 6
visualhero_loop_limit_unfollow = 6
visualhero_loop_limit_actions = visualhero_loop_limit_like + visualhero_loop_limit_follow + visualhero_loop_limit_unfollow

print("VHBOT - INFO - START LOOP ONE - YOURTEXTHERE")

visualhero_follow_underlimit = max(visualhero_follow_limit - session_start_following, 0)

print("VHBOT - DEBUG -", visualhero_follow_underlimit,"followers underlimit")

visualhero_loop_total_likes = 0
visualhero_loop_total_follow = 0
visualhero_loop_total_unfollow = 0

visualhero_loopstartime = datetime.now()

visualhero_loopendtime = visualhero_loopstartime + timedelta(minutes = visualhero_loop_time)

print("VHBOT - INFO - Loop start:", visualhero_loopstartime,"- Loop end:", visualhero_loopendtime)
print("VHBOT - INFO - Run Time:", visualhero_loop_time,"minutes - Quota:", visualhero_loop_limit_actions, "actions")

"""Loop One Action"""
print("VHBOT - DEBUG - Loop limit actions:", visualhero_loop_limit_actions)

while datetime.now() < visualhero_loopendtime:
    if visualhero_loop_total_likes < visualhero_loop_dquota_like:
        session.liked_img = 0
        session.followed = 0

        """YOUR CODE HERE = LIKE & FOLLOW (until it reach the limit)"""

        visualhero_loop_total_likes = visualhero_loop_total_likes + session.liked_img
        visualhero_session_likes = visualhero_session_likes + session.liked_img
        print("VHBOT - DEBUG - Loop liked images:", visualhero_loop_total_likes)
        visualhero_loop_total_follow = visualhero_loop_total_follow + session.followed
        visualhero_session_followed = visualhero_session_followed + session.followed
        print("VHBOT - DEBUG - Loop followed users:", visualhero_loop_total_follow)
    else:
        visualhero_action_limiter = visualhero_loop_limit_actions - visualhero_loop_total_likes - visualhero_loop_total_follow - visualhero_loop_total_unfollow
        print("VHBOT - DEBUG - action limiter =", visualhero_action_limiter)
        if visualhero_action_limiter > 0:
            if visualhero_loop_dquota_unfollow <= visualhero_follow_underlimit:
                print("VHBOT - DEBUG - Unfollow limit <= Follow Underlimit")
                session.followed = 0
                
                """YOUR CODE HERE"""
               
                visualhero_loop_total_follow = visualhero_loop_total_follow + session.followed
                visualhero_session_followed = visualhero_session_followed + session.followed
            else:
                print("VHBOT - DEBUG - Unfollow limit > Follow Underlimit")
                session.unfollowNumber = 0
                if visualhero_action_limiter > visualhero_loop_dquota_unfollow:
                    print("VHBOT - INFO - Unfollow", visualhero_loop_dquota_unfollow, "from Instapy followers - No active followers")
                     
                    """YOUR CODE HERE"""

                    visualhero_loop_total_unfollow = visualhero_loop_total_unfollow + session.unfollowNumber
                    visualhero_session_unfollow = visualhero_session_unfollow + session.unfollowNumber
                    print("VHBOT - DEBUG - Loop unfollowed users:", visualhero_loop_total_unfollow)
                    visualhero_action_limiter = visualhero_loop_limit_actions - visualhero_loop_total_likes - visualhero_loop_total_follow - visualhero_loop_total_unfollow
                    while visualhero_action_limiter > 0 and datetime.now() < visualhero_loopendtime:
                        session.followed = 0
                        
                     """YOUR CODE HERE""" 

                        visualhero_loop_total_follow = visualhero_loop_total_follow + session.followed
                        visualhero_session_followed = visualhero_session_followed + session.followed
                        visualhero_action_limiter = visualhero_loop_limit_actions - visualhero_loop_total_likes - visualhero_loop_total_follow - visualhero_loop_total_unfollow
                    break
                else:
                    print("VHBOT - INFO - Unfollow", visualhero_action_limiter, "from Instapy followers - No active followers")
                    session.set_dont_unfollow_active_users(enabled=False, posts=1)
                     """YOUR CODE HERE"""
                    visualhero_loop_total_unfollow = visualhero_loop_total_unfollow + session.unfollowNumber
                    visualhero_session_unfollow = visualhero_session_unfollow + session.unfollowNumber
                    #print("VHBOT - DEBUG - Loop unfollowed users:", visualhero_loop_total_unfollow)
                    break
        else:
            break

print("VHBOT - INFO - Loop liked images:", visualhero_loop_total_likes, "- Loop Followed users:", visualhero_loop_total_follow, "- Loop Unfollowed users:", visualhero_loop_total_unfollow)

if datetime.now() < visualhero_loopendtime:
    visualhero_sleep_loop = visualhero_loopendtime - datetime.now()
    print("VHBOT - INFO -", visualhero_sleep_loop.total_seconds(), "seconds till loop end - Sleeping")
    sleep(visualhero_sleep_loop.total_seconds())
    print("VHBOT - INFO - End of nap")
else:
    visualhero1random = randint(60, 120)
    print("VHBOT - INFO - Cooling off, sleeping for", visualhero1random, "seconds")
    sleep(visualhero1random)
    print("VHBOT - INFO - End of nap")


print("VHBOT - INFO - Session liked images:", visualhero_session_likes, "- Session Followed users:", visualhero_session_followed, "- Session Unfollowed users:", visualhero_session_unfollow)
```

**Comment by BalrogFlame** [comment]
Thanks for sharing it @visualheroes !
It's going to be helpful

**Comment by CTZNkjs** [comment]
Thanks !! @visualheroes

**Comment by visualheroes** [comment]
Sorry it's a bit unreadable like this as i replaced my short name with "visualhero" to anonymize it. 
My loops stay inside a 12 minutes time frame and i follow roughly the same amount of account i unfollow so my "following" count doesn't jump everyday. ;)
Everything is randomized and all my tags and variables are loaded randomly from txt files (easier to edit).
I modified part of the instapy script too, mostly to let me follow without liking and things like that. 
As i said, i never coded anything in python before, maybe someone will do something a little bit more efficient in the future. 
Anyway, it works well even if it's not pretty!

**Comment by bianpratama** [comment]
Thanks for sharing your setup, @visualheroes !

I'm currently trying to work on my own setup with interaction/action counter to limit the interaction/action per session. And I'd like to implement some of your setup to mine. I'm still trying to understand your setup, and do have some questions:

1. How can I use the `visualhero_follow_underlimit`? Do I need to set the `visualhero_follow_limit` and `session_start_following` first?
2. How can I use the `visualhero_loop_dquota_like` and `visualhero_loop_dquota_unfollow`? From you setup file, They are only used for comparison.
3. Can you share the function to load external files?
4. Are you using multiple accounts with InstaPy? If yes, do you separate the accounts by folders or just different files?

I'm still getting used to Python, go easy with this newbie 😞
