### ISSUE TITLE
Ideal presset for medium-sized accounts

### ISSUE THREAD

**Issue by kivkaucet** [InstaPy/InstaPy#2070]
Hey guys,

i am new in InstaPy and i am just trying pressets for this great platform around the one month. I tried more than 20 combinations of interactions (like follows, unfollows, comments, likes, follow followers, a lot of possibilities of delaying and so on) and i want to ask, if somebody have some ideal presset for medium sized account for inspiration. I dont have any medium sized accounts, only small, but i want t just check some ideas about ideal numbers and combinations of interacting :) Is it possible for sombody to share it with me?

Thank you very much and sorry for my english, kivka

**Comment by kivkaucet** [comment]
Cause i did somethign like this for testing. Will be happy to share experiences with us guys :) Thank you very much.

# settings
    session.set_relationship_bounds(enabled=False,
                                 potency_ratio=-1.21,
                                  delimit_by_numbers=True,
                                   max_followers=5500,
                                    max_following=10000,
                                     min_followers=45,
                                      min_following=100)
    session.set_do_comment(False, percentage=10)
    session.set_comments(['XXX!', 'XXX!!', 'XXX!'])
    #session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['sex', 'porn', 'XXX', 'XXX'])
    session.set_do_follow(enabled=True, percentage=20, times=200)
    session.follow_user_followers(['XXX'], amount=20, randomize=False, sleep_delay=60)
    session.follow_by_tags(['XXX', 'instagram', 'photooftheday', 'XXX', 'XXX'])
    session.unfollow_users(amount=10, onlyNotFollowMe=True, sleep_delay=60)

    # actions
    session.like_by_tags(['XXX', 'instagram', 'photooftheday', 'XXX', 'XXX'], amount=10)

**Comment by sionking** [comment]
session.unfollow_users(amount=50, onlyNotFollowMe=True, sleep_delay=60)
