### ISSUE TITLE
Because in the settings below the urge is following 10 people instead of like? I do not want him to follow I just want him to like

### ISSUE THREAD

**Issue by zsvendo** [InstaPy/InstaPy#2072]
## Expected Behavior

Because in the settings below the urge is following 10 people instead of like? I do not want him to follow I just want him to like?

from instapy import InstaPy

session = InstaPy(username='zueira_gremista', password='Mudar1234@', headless_browser=True)
session.login()
session.set_relationship_bounds (enabled=True, potency_ratio=None, delimit_by_numbers=False)
session.set_user_interact(amount=1, randomize=False, percentage=100, media=None)
session.set_do_like(enabled=True, percentage=100)
session.interact_user_followers(['gremio'], amount=1000, randomize=False)

session.end()

**Comment by redsector72** [comment]
I have already pointed out the bug in #2075

**Comment by zsvendo** [comment]
Where can I get this?

**Comment by uluQulu** [comment]
@zsvendo 
It's intentionally following to simulate a real activity flow.
Read https://github.com/timgrossmann/InstaPy/pull/2042#issuecomment-390261042 for more.

@redsector72 it isn't a bug, but a feature
