### ISSUE TITLE
the web page instagram does not load

### ISSUE THREAD

**Issue by CamiloB** [InstaPy/InstaPy#2074]
## Expected Behavior
when i go to load the web page of instagram is in white 

## Current Behavior
this appear on the console 

`Traceback (most recent call last):
  File "/home/ubuntu/InstaPy/sagrada.py", line 30, in like
    session.set_dont_unfollow_active_users(enabled=True, posts=5)
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 1740, in set_dont_unfollow_active_users
    self.logger)
  File "/home/ubuntu/InstaPy/instapy/util.py", line 118, in get_active_users
    "//span[contains(@class,'_t98z6')]//span").text)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(@class,'_t98z6')]//span"}
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36.540471 (9c759b81a907e70363c6312294d30b6ccccc2752),platform=Linux 3.13.0-143-generic x86_64)
`

## InstaPy configuration

`from instapy import InstaPy
import schedule
import time

insta_username = 
insta_password = 

def like():

    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      bypass_suspicious_attempt=False,
                      multi_logs=True)
    session.login()

    session.set_do_comment(True, percentage=50)
    session.set_do_like(True, percentage=70)
    session.set_do_follow(True, percentage=70)
    session.set_upper_follower_count(limit=12500)
    session.set_lower_follower_count(limit = 100)
    session.set_dont_unfollow_active_users(enabled=True, posts=5)
    session.set_comments([u'ten un feliz dia! :beers: :sunglasses: ',
                          u'Que tengas un buen dia :pizza: :sunglasses: '])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like([ 'girl'])

 
    session.like_by_tags(['amigos', 'bebidas', 'cervezaartesanal', 'pizza',
                          'sandwich', 'comida', 'comiendo', 'comiendopizza'], amount=0)
   

    session.like_by_locations(['490255575/lolasclubcolombia/'], amount=10, random=True)

    session.like_by_locations(['824770378/sagsa-bar/'], amount=10)

    session.like_by_locations(['1010056746/la-pergola-clandestina/'], amount=10)

    session.like_by_locations(['943711403/museo-la-tertulia/'], amount=10)

    session.like_by_locations(['413232913/centro-comercial-chipichape/'], amount=10)

    session.like_by_locations(['1023143344/cantina-la-15/'], amount=10)

    session.like_by_locations(['237277827/la-tinaja-restaurante-bar/'], amount=10)

    session.like_by_locations(['398123053955998/tardes-calenas/'], amount=10)

    session.like_by_locations(['404314594/rio-pance-cali/'], amount=10)

    session.like_by_locations(['982128617/teatro-al-aire-libre-los-cristales/'], amount=10)

    session.like_by_locations(['219095525179520/sonido-central/'], amount=10)

    session.like_by_locations(['238766526/el-penon-valle-del-cauca-colombia/'], amount=10)

    session.like_by_locations(['243302604/dapa-valle-del-cauca-colombia/'], amount=10)

    session.like_by_locations(['139022346514470/cerro-de-las-tres-cruces/'], amount=10)

    session.like_by_locations(['346979118/dtoluca/'], amount=10)

    session.like_by_locations(['386175081737481/gastroteca/'], amount=10)

    session.unfollow_users(amount=0, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60 )
     
 except:
   import traceback
   print(traceback.format_exc())

 
 finally:
  
    session.end()

def job():

    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      bypass_suspicious_attempt=False,
                      multi_logs=True)
    session.login()

    session.set_user_interact(amount=2, randomize=True, percentage=50,
                              media='Photo')
    session.set_do_follow(enabled=False, percentage=70)
    session.set_do_like(enabled=False, percentage=70)
    session.set_comments(["Que tengas un buen dia :D ",
                          u"Sonrie, feliz dia :D  :pizza:"
                          u"¡Deseamos un lindo dia para ti!  :beers: "])
    session.set_do_comment(enabled=True, percentage=80)
    session.set_upper_follower_count(limit=12500)
    session.set_lower_follower_count(limit = 100)
    session.interact_user_followers(['cervecería.sagrada'], amount=30,
                                    randomize=True)

  
     
 except:
   import traceback
   print(traceback.format_exc())

 
 finally:

    session.end()
    

schedule.every().day.at("21:54").do(like)
schedule.every().day.at("17:30").do(job)
schedule.every().day.at("19:27").do(like)
schedule.every().day.at("0:30").do(job)
schedule.every().day.at("1:30").do(like)
schedule.every().day.at("4:30").do(job)
schedule.every().day.at("5:30").do(like)
schedule.every().day.at("9:30").do(job)
schedule.every().day.at("10:30").do(like)
schedule.every().day.at("21:29").do(job)

while True:
    schedule.run_pending()
    time.sleep(1)`

**Comment by uluQulu** [comment]
@CamiloB 
Is that issue happening persistently?
Although you can apply this to solve it,
in **util.py** file find and **replace**
```python
total_posts = format_number(browser.find_element_by_xpath(
    "//span[contains(@class,'_t98z6')]//span").text)

# if posts > total user posts, assume total posts
if posts >= total_posts:
    # reaches all user posts
    posts = total_posts
```

**with**
```python
try:
    total_posts = browser.execute_script(
        "return window._sharedData.entry_data."
        "ProfilePage[0].graphql.user.edge_owner_to_timeline_media.count")
except WebDriverException:
    try:
        total_posts = (browser.find_element_by_xpath(
            "//span[contains(@class,'_t98z6')]//span").text)
        if total_posts: #prevent an empty string scenario
            total_posts = format_number(total_posts)
        else:
            logger.info("Failed to get posts count on your profile {}  ~empty string".format(count))
            total_posts = None
    except NoSuchElementException:
        logger.info("Failed to get posts count on your profile {}".format(count))
        total_posts = None

# if posts > total user posts, assume total posts
posts = posts if total_posts is None else total_posts if posts > total_posts else posts
```

**Comment by sionking** [comment]
It happens now and then that instagram return white page. Better delete cookies, reboot computer and try again.

@uluQulu  We also need to check it, as it might remove users from follow pool when unfollowing thinking user does not exist any more !

**Comment by sexD** [comment]
I am not sure if Instgram returned a white page since I am running headless on a server, but I get the same exact error. If I remove the unfollow line in my quickstart.py, it seems to be working but InstaPy says "Too few images to like", "Nobody to follow" etc etc. I pulled the latest version today and I can't get Instapy to work at all. I suspect that the webpage isn't loading correctly even though it says "Logged in". Any idea how to troubleshoot?

**Comment by univers3** [comment]
I never stopped the script with a CRTL+C combo.
I'm getting this since yesterday.

**Comment by univers3** [comment]
Same problem here #2131 
Maybe Instagram changed some classes

**Comment by uluQulu** [comment]
@univers3 
It has nothing to do with keyboard interruption, instead, right- there is a new change in page elements.
_See https://github.com/timgrossmann/InstaPy/issues/2131#issuecomment-393531365 to fix it_

**Comment by CamiloB** [comment]
Hi this error i already fixed by deleting the cokies of the browser and restarting the pc thanks a lot for all the help
