### ISSUE TITLE
InstaPy GUI endlessly running...

### ISSUE THREAD

**Issue by gjuqw** [InstaPy/InstaPy#2078]
Hi,

after some hazzle I finally installed InstaPy and the electron-instaPy-GUI.
Amazing that you can find such a a bot for free, great job!
When I start the GUI tho it now shows me that all files are in place, but when i try to run the bot it just says InstaPy running... and no process at all is shown.
I checked my profile and indeed nothing is happening.

At the beginning of the installation I had problems running the windows.ps1, so I installed everything manually.
Im running Windows 64-Bit and I am not into coding at all...

Thanks for the help

**Comment by gjuqw** [comment]
Bump and edit: so the bot is working now, i can use it from the quickstart.py, the GUI still shows a blank page when i press run tho, can someone help?

**Comment by LeoKolade** [comment]
@gjuqw Hello. please how do you use  quickstart.py to run it. i know nothing about programming ....please help
