### ISSUE TITLE
Be able to configure instapy settings.py without editing instapy lib.

### ISSUE THREAD

**Issue by jaybocc2** [InstaPy/InstaPy#2079]
## Expected Behavior
Be able to configure instapy settings.py without editing instapy lib.
IE: set db path or chromedriver path.

## Current Behavior
settings.py is not configurable without manual edits

## Possible Solution(s) (optional)
Load settings from environment
Pass settings into InstaPy class initialization

**Comment by CharlesCCC** [comment]
Thank you for the PR
https://github.com/timgrossmann/InstaPy/pull/2080
