### ISSUE TITLE
Anyone experiencing white pages?

### ISSUE THREAD

**Issue by redsector72** [InstaPy/InstaPy#2085]
I'm experiencing a strange behavior.
Chrome does not display the page, even if it has the source.
Obviously without rendering the page the script stops.
I've got the problem on 2 different mac, on one even on the login page.

I've tried different combinations of versions (even chrome-driver) but the problem is still there.

**Comment by sionking** [comment]
Try delete cookies and reboot PC

**Comment by sionking** [comment]
Please write you chrome version and OS

**Comment by redsector72** [comment]
Chrome 66.0.3359.181 and on the other was Chrome 65.something.
I have tryed everything, even deleting chrome (and cromedriver).
I suppose #2087 is the same issue. Probably is not looking at the machine (maybe headless).

**Comment by sionking** [comment]
I had one windows 8 that worked after reboot.

**Comment by sionking** [comment]
Maybe instagram server issues.

**Comment by sionking** [comment]
R U middle east area ?

**Comment by redsector72** [comment]
I am US east coast.
I suppose all the latest "issues" reported are the same problem. They should try to "look" at the screen and not at the log.
I can't understand if it is a chrome problem, an instapy problem, or if they have a way to discriminate.

**Comment by therealyamashita** [comment]
Same here. I Can't view Instagram page in any browser yesterday. But now it's working fine again.
