### ISSUE TITLE
Randomize comments for MASSIVE engagment

### ISSUE THREAD

**Issue by supmag** [InstaPy/InstaPy#2088]
## Expected Behavior
Randomize coments
## Current Behavior
So I have a list of 100 comments, specific comments for my niche. I got a soft ban on one of my accounts and had a look at what was going on on my account. The comments were not being randomized. It posted the the same comment 3-4 times in a period of 1 hour even though there are 99 other comments to choose from.
## Possible Solution (optional)
Have a code that either adds a random emoji to the comments or don't use the same comment more than once over a longer period of time?

**Comment by CharlesCCC** [comment]
I don't think you get soft-banned by the comment. 

but I do agree with your suggestion to improve the comment function (randomization).

**Comment by xvx29a** [comment]
Python's random library is not the greatest, but you should be able to fix this easily.

In instapy/comment_util.py change:

`from random import choice`
to
`import random`

under comment_image add this to the top:

`sr = random.SystemRandom()`
and change
`rand_comment = (choice(comments).format(username))`
to
`rand_comment = (sr.choice(comments).format(username))`

That should use urandom for better randomization. I havent tested this, but use this code elsewhere to randomly pick tags to interact with.
