### ISSUE TITLE
instapy IndexError: list index out of range

### ISSUE THREAD

**Issue by Areahints** [InstaPy/InstaPy#2091]
hello, my instapy ran into this error

`Traceback (most recent call last):
  File "quickstart.py", line 40, in <module>
    session.follow_user_followers(['nollywoodonline', 'peterpsquare', 'tontolet', 'nollywoodonset', 'ghanianswedding', 'playground_ng', 'yvonnenelsongh', 'nollywoodscenes'], amount=20, randomize=False, sleep_delay=600)
  File "/home/areahints/software/InstaPy/instapy/instapy.py", line 1864, in follow_user_followers
    self.logfolder)
  File "/home/areahints/software/InstaPy/instapy/unfollow_util.py", line 750, in get_given_user_followers
    logger, logfolder)
  File "/home/areahints/software/InstaPy/instapy/unfollow_util.py", line 575, in get_users_through_dialog
    quick_button = follow_buttons[quick_index]
IndexError: list index out of range`

# InstaPy configuration

# settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.21,
				  delimit_by_numbers=True,
				   max_followers=5000,
				    max_following=500,
				     min_followers=50,
				      min_following=70)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['Cool!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])
    session.set_do_follow(enabled=True, percentage=20, times=200)
    session.follow_user_followers(['nollywoodonline', 'peterpsquare', 'tontolet', 'nollywoodonset', 'ghanianswedding', 'playground_ng', 'yvonnenelsongh', 'nollywoodscenes'], amount=20, randomize=False, sleep_delay=600)
    session.follow_by_tags(['design', 'webdesign', 'photooftheday', 'lagos', 'naija'])
    session.unfollow_users(amount=10, onlyNotFollowMe=True, sleep_delay=60)
    
# actions
    session.like_by_tags(['design', 'webdesign', 'photooftheday', 'lagos', 'naija'], amount=10)

**Comment by uluQulu** [comment]
@Areahints 
Get latest files, it is fixed
