### ISSUE TITLE
Unfollow Bug 

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#2092]
INFO [2018-05-23 21:06:54] [mr_and_mrs_vfit]  Logged in successfully!
INFO [2018-05-23 21:07:21] [mr_and_mrs_vfit]  --> Ongoing Unfollow 1, now unfollowing: b'eat_jess_run'
INFO [2018-05-23 21:07:30] [mr_and_mrs_vfit]  --> Ongoing Unfollow 2, now unfollowing: b'dominicanosfit'
INFO [2018-05-23 21:07:39] [mr_and_mrs_vfit]  --> Ongoing Unfollow 3, now unfollowing: b'enom07'
INFO [2018-05-23 21:07:49] [mr_and_mrs_vfit]  --> Ongoing Unfollow 4, now unfollowing: b'fahad.amjad_123'
INFO [2018-05-23 21:08:00] [mr_and_mrs_vfit]  --> Ongoing Unfollow 5, now unfollowing: b'coach_4fit'
INFO [2018-05-23 21:08:10] [mr_and_mrs_vfit]  --> Ongoing Unfollow 6, now unfollowing: b'mawgotfit'
INFO [2018-05-23 21:08:19] [mr_and_mrs_vfit]  --> Ongoing Unfollow 7, now unfollowing: b'alihadhugehoo'
INFO [2018-05-23 21:08:28] [mr_and_mrs_vfit]  --> Ongoing Unfollow 8, now unfollowing: b'aalexandre_g'
INFO [2018-05-23 21:08:38] [mr_and_mrs_vfit]  --> Ongoing Unfollow 9, now unfollowing: b'suhassbudhawant'
INFO [2018-05-23 21:08:47] [mr_and_mrs_vfit]  --> Ongoing Unfollow 10, now unfollowing: b'manon_mnb'
INFO [2018-05-23 21:08:52] [mr_and_mrs_vfit]  sleeping for about 10min
INFO [2018-05-23 21:12:16] [mr_and_mrs_vfit]  --> Ongoing Unfollow 11, now unfollowing: b'bohdana_nastich'
INFO [2018-05-23 21:12:26] [mr_and_mrs_vfit]  --> Ongoing Unfollow 12, now unfollowing: b'clem_fill'
INFO [2018-05-23 21:12:30] [mr_and_mrs_vfit]  --> Total people unfollowed : 12 
INFO [2018-05-23 21:12:30] [mr_and_mrs_vfit]  Session ended - 2018-05-23 21:12:30
INFO [2018-05-23 21:12:30] [mr_and_mrs_vfit]  --------------------

cuts himself alone without having done 1000 unfollow What?
My script : 
    session.unfollow_users(amount=1000)

**Comment by johnvfitness** [comment]
@uluQulu Sorry bro but I do not understand why it closes before

**Comment by uluQulu** [comment]
hi @johnvfitness 
It was just `session.unfollow_users(amount=1000)`?
Cos if you used `onlyInstapyFollowed` then maybe there are not many people in your **followedPool.csv** file and even if used `unfollow_after`  parameter, it would affect.

If there is no problems with those, then `unfollow_users` definition needs a revision.

**Comment by johnvfitness** [comment]
@uluQulu  
This code bro?
session.unfollow_users(amount=2000, onlyInstapyFollowed = True, sleep_delay=60)

**Comment by sionking** [comment]
2000? Too much. I think 100 is more human

**Comment by uluQulu** [comment]
@johnvfitness 
Go to your logs folder and find the **yourusername_followedPool.csv** file and see how many lines there are.
You should know that `onlyInstapyFollowed` method uses that CSV file to generate a list of people to unfollow, so it will unfollow as much as there are, nothing more, nothing less.

Also, @sionking is right about the amount, although any amount is available to use, it is recommended to unfollow some huge amount (e.g. `200`) in a quick time and not unfollow for a while, I mean unfollowing thousands of people **continuously** is a bad practice and should be avoided.

Also, 60 seconds of sleep delay is too low. the The default delay time is 600 seconds, try to use delay time around that value.

**Comment by johnvfitness** [comment]
Ok thx bro @uluQulu 
I'm going to lower the number of follow-ups and use the method FIFO 48hr 👍
