### ISSUE TITLE
Share your statistics

### ISSUE THREAD

**Issue by dbknv** [InstaPy/InstaPy#2096]
Hi guys.
I use InstaPy for 10 months everyday and I'd like to share with you my statistic. I'm trying to post 1 photo everyday, but I had a couple of months without any photos. At the first time followers are gained incredible (about 600-800 per month). After 6 months my account reached about 3000 followers. 

Nowdays I use settings like that
```
session.set_relationship_bounds(enabled=True,
                                potency_ratio=1.1,
                                delimit_by_numbers=True,
                                max_followers=50000,
                                max_following=50000,
                                min_followers=40,
                                min_following=40)
session.set_delimit_liking(enabled=True, max=1000, min=10)
session.set_delimit_commenting(enabled=True, max=70, min=2)

session.set_do_comment(enabled=True, percentage=85)
session.set_comments(['Nice DJI shot. @{}, Keep going',
                      'Awesome drone pic. @{}, do not stop)))',
                      'Perfect view. @{}, do you like that place?',
                      'WOW-WOW, easy. @{}, it is awesome!'])

session.set_do_follow(enabled=True, percentage=5, times=1)

session.set_user_interact(amount=2, randomize=True, percentage=50)
session.like_by_tags(['phantom4', 'djiphantom'], amount=35, interact=True)

session.unfollow_users(amount=10, onlyInstapyFollowed=True, onlyInstapyMethod='FIFO', unfollow_after=60*60*24)
```

[My bot statistic per day](https://dl.dropboxusercontent.com/s/b5ro302bxf7a6z8/DB%20Browser%20for%20SQLite_2018-05-24_14-17-00.png):
-1000 likes
-500 comments
-110 follows

I noticed my account stops growing last months. It hangs on ~3800. Has anyone faced with this issue? How to solve it?

Share your bot settings and acount statistic :)

**Comment by sionking** [comment]
do much less comments, or even none. easyiest way to detect bot when 500 comments and all are almost the same. use image reco for mor sophisticated comments.

**Comment by sionking** [comment]
Change targets profile and tags now and then
