### ISSUE TITLE
High ratio of lost followers

### ISSUE THREAD

**Issue by marudon** [InstaPy/InstaPy#210]
Working with InstaPy brought me a quiet nice number of new followers.
But in the following 48 or 72 hour about 70-80% of this new followers unfollow me again.

Is this high number normal or did I do something wrong using the script? 
Obviously I attract a high number of bots .. loosing nearly every of the new followers is quiet frustating :-(

**Comment by timgrossmann** [comment]
@marudon Yes it is...
Especially if you're using tags like '#follow4follow' and these kind of things...

**Comment by marudon** [comment]
I didn't use any tags like #follow4follow #likeforlike # picoftheday #instamood etc.  I just had regular tags fitting to my topics ..  

Do you have similar experiences using the script?

**Comment by timgrossmann** [comment]
@marudon Yes, that's the way it is :D
