### ISSUE TITLE
Don't follow users who you already sent an invitation

### ISSUE THREAD

**Issue by aku6640** [InstaPy/InstaPy#2101]
## Current Behavior
Now the script in session.follow_users_followers follows people, but when they don't accept your follow, the script later tries it again, sometimes up to alot of times when people get irritated. 

Is there a way to set the number of following of 1 person to like 1 or 2 times max when they don't accept my invitation?

**Comment by uluQulu** [comment]
@aku6640 
Sure you can use `times` parameter for that reason,
```python
set_do_follow(enabled=True, percentage=70, times=1)
```
_It will set max **follow times** as you wish_

**Comment by aku6640** [comment]
It is not working good. I am getting daily messages of people why I am following and unfollowing them all the time!

**Comment by uluQulu** [comment]
@aku6640 
How huge is your **followRestriction.json** file?
To have it work good you first have to keep that JSON healthy.

_Have a look at my PR #2086 which addresses that situation :)_

**Comment by aku6640** [comment]
@uluQulu 
thanks for your time again, I've read PR #2086 a few times but I couldn't find the solution. 

is it this or am I not seeing it? 

 for follwedPool.csv,

from .util import interruption_handler

with interruption_handler():
    with open('{0}{1}_followedPool.csv'.format(logfolder, login), 'a+') as followPool:
        followPool.write('{} ~ {},\n'.format(logtime, followed))

add this?

**Comment by uluQulu** [comment]
It's a pleasure @aku6640 
_**followedPool.csv** file has no relationship with you situation._
It is using the data kept in **followRestriction.json** file and #2086 is meant to bring safety to it.
