### ISSUE TITLE
Randomizing set of tags

### ISSUE THREAD

**Issue by tanmald** [InstaPy/InstaPy#2102]
Hi, I'd like to know if it is possible to randomize a list of tags so that Instapy doesn't always follow the same order of tags. For example, having:

session.like_by_tags(['gpmundo', 'wonderfuldestinations', 'exploreourearth', 'thetravelwomen'], amount=3, interact=True)

how can i randomize these?

Thanks

**Comment by ghost** [comment]
add this to top of the quickstart.py script
import random
from random import randint 

session.like_by_tags([(random.randint('gpmundo', 'wonderfuldestinations', 'exploreourearth', 'thetravelwomen')], amount=3, interact=True)

you might have to switch up the punctuation i have never done it but random.randint will solve that problem if anybody can parse the code better
