### ISSUE TITLE
Multiple Account question

### ISSUE THREAD

**Issue by cormo1990** [InstaPy/InstaPy#2104]
Hello Fam, I have an important question.

If I run InstaPy with 3 different account in 3 different schedule of terminal...are there any risk to will be banned or something else?
thanks in advance

**Comment by loopypanda** [comment]
it takes forever to build large accounts unless you post quality content so over a year you might gain 5k with follow/unfollow but it should be 2-3 accs per proxy

**Comment by loopypanda** [comment]
it takes forever to build large accounts unless you post quality content so over a year you might gain 5k with follow/unfollow but it should be 2-3 accs per proxy

**Comment by gitpatrickhub** [comment]
@cormo1990 i’ve been running 4 accounts from same raspberry pi with no issues for a year.

**Comment by davisonio** [comment]
Use a proxy for each account to reduce risk
