### ISSUE TITLE
Unfollowing not working correctly

### ISSUE THREAD

**Issue by VerusK** [InstaPy/InstaPy#2105]
Getting exception when finding XPath for `Following`
`selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Following']/following-sibling::div"}`

but if I change it to correct one 
`dialog = browser.find_element_by_xpath("//a[contains(@href,'following')]")`

I get empty `person_list_a` at `instapy/unfollow_util.py:335`

**Comment by Raziel15** [comment]
Same issue

**Comment by VerusK** [comment]
Forgot to mention, I start with params
```
session.unfollow_users(
            amount=700,
            sleep_delay=600, unfollow_after=48 * 3600,
            onlyNotFollowMe=False, # if set to True then it's working
        )
```

**Comment by timokueck** [comment]
Anyone got it fixed? @Raziel15 @VerusK

**Comment by VerusK** [comment]
@TechsCode no, as far as I know, but I didn't try it since then.
