### ISSUE TITLE
Not generating Smart Hashtags on Mac when running as Cronjob

### ISSUE THREAD

**Issue by lisibachramon** [InstaPy/InstaPy#2108]
I tried to use cron to automate the bot. Everything was working as expected when i configured it and started it on the terminal. But as soon as i try to run it via cron it won't comment, follow nor generate smart hashtags. It just stops after the login

Cron:
42 19 * * * cd /Users/{myuser}t/Documents/Instabots/&& /usr/local/bin/python3 ./quickstart.py
Quckstart.py
   session.set_relationship_bounds(enabled=True,
				 potency_ratio=0.69,
				  delimit_by_numbers=True,
				   max_followers=9900,
				    max_following=1000,
				     min_followers=35,
				      min_following=50)
    session.set_do_comment(True, percentage=10)
    session.set_do_follow(enabled=True, percentage=10, times=4)
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.like_by_locations(['214122044/zurich-switzerland/'], amount=500)
    session.set_do_follow(enabled=True, percentage=10, times=4)
    session.like_by_locations(['17326249/moscow-russia/'], amount=700)
    session.set_do_follow(enabled=True, percentage=10, times=4)
    session.set_dont_like(['pizza', 'girl'])
    session.set_do_follow(enabled=True, percentage=10, times=4)
    session.set_smart_hashtags(['bucarest', 'moscow', 'retro', 'follow4follow', 'zurich', 'seoul'], limit=100, sort='top', log_tags=True)
    session.like_by_tags(amount=50, use_smart_hashtags=True)

**Comment by redsector72** [comment]
Is your mac sleeping or password locked?

**Comment by lisibachramon** [comment]
No, not at all. I even tried to disarm the firewall. Everything else works as expected...

**Comment by lisibachramon** [comment]
INFO [2018-05-28 11:42:02]  Session started - 2018-05-28 11:42:02
INFO [2018-05-28 11:42:34]  Logged in successfully!
INFO [2018-05-28 11:42:38]  Session ended - 2018-05-28 11:42:38
INFO [2018-05-28 11:42:38]   --------------------
