### ISSUE TITLE
session.unfollow_users with onlyNotFollowMe=True buggy

### ISSUE THREAD

**Issue by HermanoCrespo** [InstaPy/InstaPy#2109]
`session.unfollow_users(amount=50, onlyNotFollowMe=True, onlyInstapyMethod='FIFO', sleep_delay=60, unfollow_after=4 * 24 * 60 * 60)`
## Expected Behavior
Unfollow users after 96 hours if user is not following back and do it in order FIFO

## Current Behavior
I have just witnessed it unfollows users it has followed in the last run a day ago. unfollow_after not working. 
Does not do FIFO either.

**Comment by uluQulu** [comment]
Hi @HermanoCrespo 
**FIFO** and **LIFO** are part of `onlyInstapyFollowed` method.
And at this stage `unfollow_after` parameter supports only `onlyInstapyFollowed` method.

But in my next PR I will make `unfollow_after` parameter work with other unfollow methods, too!
_Of course, it will work only if that user is followed within InstaPy :)_

**Comment by HermanoCrespo** [comment]
Thank you. I was not aware.
