### ISSUE TITLE
[request] Two-step authentication

### ISSUE THREAD

**Issue by tanmald** [InstaPy/InstaPy#2118]
Hey guys, so I'm thinking that it would be a great security improvement to allow us using two-step autentication with InstaPy. As of today, if you have this option on, instapy fails. However, since instagram gives us a few security codes, wouldn't it be possible to feed instapy those codes so that it could work having this feature enabled?

Thanks! :)

**Comment by imbarismustafa** [comment]
I think you can use the bypass suspicious login attempt option.

**Comment by davisonio** [comment]
This would be awesome!

**Comment by davisonio** [comment]
-

**Comment by Tr1pke** [comment]
i have the two step on, first i start instapy that you see chrome starting up, asking for the numbers they send you, i fill in the numbers and i quit.
Then you can start in in de background again

**Comment by davisonio** [comment]
.

**Comment by elulcao** [comment]
Closing for now,
Merge #5938 closed
