### ISSUE TITLE
Feature Request - Whitelist for Unfollowing

### ISSUE THREAD

**Issue by CalebBuxton** [InstaPy/InstaPy#2119]
## WHY
I think it is important to continue to follow accounts that you find interesting or with good content and these accounts should be excluded from all unfollow session runs.

## HOW
In the most simple form, have a text file that is a list of accounts to whitelist. In this case the whitelist can be updated on servers without disrupting the loop or schedule as the whitelist can be imported for each specific run through the job.

## WHAT
Users still have content to engage with they are interested in by specific accounts they have chosen to continue to follow. This will be a user generated list of accounts to continue to follow and can be used in conjunction with `session.set_dont_unfollow_active_users`

**Comment by sionking** [comment]
# set_dont_include:
        # will prevent commenting on and unfollowing your good friends
        # (the images will still be liked)
        session.set_dont_include(inputs['original_all_following'] + inputs['usersToIgnore'])

        # set_ignore_users: completely ignore liking images from certain users
        session.set_ignore_users(inputs['original_all_following'] + inputs['usersToIgnore'])

**Comment by CalebBuxton** [comment]
Ah, and I can just get that `usersToIgnore` to be a parsed document. Awesome!
