### ISSUE TITLE
Likes do not appear in Instagram app

### ISSUE THREAD

**Issue by ketaminehigh** [InstaPy/InstaPy#2121]
Hi everyone, 

I know this issue was mentioned many times before, however I cannot find any working solution.

Script seemingly works fine, showing '**Image Liked!**' info, however likes do not appear in the Instagram app. What is even more interesting, everything works fine once I run the script from locally stored repository. Issue arises when I try to run it on the **DO server**. Yesterday everything worked like a charm and suddenly something happened today. 

I am using **chrome browser** and **nogui** parameter. 

Is there any working fix to this?
Many thanks in advance!
KH

**Comment by sionking** [comment]
don't nogui.
dont DO.
