### ISSUE TITLE
Multiaccount  should use Clarifai with proxy.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2123]
using proxy only for chrome is not enogth since if you ran 2 or more aacount on same server you will end up using Clarifai with same ip for all and get mostly blocked.

What is the proper solution to run the image check with proxy ?

**Comment by CharlesCCC** [comment]
why would you it matter ? I don't think Clarifai care about where does the request coming from. (the same IP vs. different IP)

**Comment by sionking** [comment]
Sure they do, I get many times request block .. payment request.
Anyway I see they use general 
 res = requests.get(url, params=params, headers=headers)
We can inject some parameters ...

**Comment by CharlesCCC** [comment]
As long as you using within it limit/or pay for it service, I can't see why they will care where the service request coming from ?  Assume you are large application that using 10 millions of request to Clarifai, how could they say, "hey, there is too many request coming from your server, please use proxy or VPN, so we don't block your request ???" doesn't make any sense to me at all.

**Comment by sionking** [comment]
Try using 10 different **free account** on same IP.
It  will get blocked.

**Comment by CharlesCCC** [comment]
@sionking LOL you should have said that earlier :)

**Comment by sionking** [comment]
So it is not hard to implement. Anyone willing ? I will try to do my best.
