### ISSUE TITLE
Instapy stop with error: ConnectionResetError: [WinError 10054]

### ISSUE THREAD

**Issue by gustafsom** [InstaPy/InstaPy#2124]
Hi friends, I use Instapy with scheduled at times, but Instapy is stopping when the error occurs: ConnectionResetError: [WinError 10054].

I've already been able to get Instapy to run again when other errors occur, but with the error: ConnectionResetError: [WinError 10054] Instapy stops completely and does not restart.

The end of my code looks like this:

```
except:
         import traceback
         print (traceback.format_exc ())
         job ()
         session.end ()
         job ()
        
     to sleep (5)
     session.end ()
     to sleep (5)

job ()
```

**Comment by sionking** [comment]
ConnectionResetError mean you closed the chrome and tried to run webdriver command.

**Comment by gustafsom** [comment]
Exactly that @sionking, but instapy itself is closing the chrome. And when this happens, the system stops completely and does not restart.
