### ISSUE TITLE
How to determine Instagram limits, recommendations, etc.?

### ISSUE THREAD

**Issue by FarhadG** [InstaPy/InstaPy#2127]
Reading through the documentation, I see several references about conforming to Instagram limits, recommendations, etc. to ensure that `Instapy` works as expected. What is a good resource to understand these limits, best practices, etc.?

**Comment by axlright** [comment]
@FarhadG I just opened up an incognito window of Chrome and a VPN and started Googling. My take on it is that no one knows. It's like Google + SEO. Instagram isn't going to say what the exact limits are just like Google isn't going to say how its algorithm works. It also seems that things change a lot over time. Instagram banned a bunch of the web services that did automated marketing.

**Comment by FarhadG** [comment]
Thanks for the quick response, @axlright. If that's the case, it would be great for us to crowd-source that data from the individuals using this service. Thoughts?

**Comment by axlright** [comment]
@FarhadG My understanding is there's a Slack channel for this. I need to find the address.

**Comment by CharlesCCC** [comment]
no more than 1000 per day. no more than 100 per hour. thinkling like a `human behavior` how fast how long can a person interact per day(with,eating, sleeping, showering) ?  we are using bot to not be detect as a bot, so acting like "human"
