### ISSUE TITLE
session.follow_likers loses effectivity over time

### ISSUE THREAD

**Issue by HermanoCrespo** [InstaPy/InstaPy#2138]
## Expected Behavior

`session.follow_likers()` is enormously useful if you've never used it. It gave my following a massive boost when I started using it, 60 per day up from 20 per day.
`#setup`
`session.set_do_follow(enabled=True, percentage=20, times=2)`
 `session.set_relationship_bounds(enabled=True, potency_ratio=-1.21, delimit_by_numbers=True, max_followers=1585, max_following=5555, min_followers=45, min_following=77)`
`session.set_do_like(enabled=True, percentage=90)`
`session.set_user_interact(amount=interactions, randomize=True, percentage=100, media='Photo')`

`# Execution`
`session.follow_likers(influencer, photos_grab_amount=1, follow_likers_per_photo=followLikers, randomize=True, sleep_delay=500, interact=True)`

## Current Behavior

After using if for 14 days on 20 different influencer accounts that are within my niche, it has exhausted itself. It now skips almost every interaction because of relationship ratio. Before, I would get about 50% interactions which was ok.

## Possible Solution (optional)

I suggest a revamp. Currently, the bot follows the user first with no regard to settings, then interacts and checks for relationship ratio etc and interacts only if those settings are met. Still, the initial follow counts toward the activity of `follow_likers()`. I think it would be very much advantageous, to (1) get a longer list of users from the website and (2) then check each user for the criteria (relationship ratio etc) and only count interactions if something actually has happened (likes, follows etc.) In that case, you'd get more bang for the buck out of the method.

Cheers

**Comment by sionking** [comment]
Thanks ! I will give it a try, but I don't understand what is the problem ?

**Comment by HermanoCrespo** [comment]
I think that instagram sends a list of people you already follow first and people with high engagement, that would be the big accounts and those are not the sheep we are after. I have not verified that yet but I can clearly see from the logs how it works well in the beginning and then degrades over time. Application of the relationship ratio much earlier as a filter would do the trick, so that the method would filter out big accounts and only get the relevant ones. In that case, it would keep working well. I do not know how many likers per influencer are required to achieve that but more than the current 25 for sure.

**Comment by lostion** [comment]
@HermanoCrespo 
Does `follow_likers_per_photo=followLikers` result in grabbing the full amount of likers?


@sionking
Is it possible to tweak the code so that the `likers `in `follow_likers_per_photo `are stored and never touched again in `follow_likers `? Maybe this is already done?

**Comment by meinert** [comment]
Good suggestions in this thread. I have the same problem with the follow_likes method.

The method could easily be change to get a longer list of likers, but still only follow a defined number of users. 

As far as I can tell the code is structured so that it checks if the user is "valid" - i.e. meets the configured criteria - and only follows then. Afterwards it only interacts with users that are followed.

@lostion 
You can always modify the code to get all likers, followers og following of a specific image or user, save it to a file, and then do a follow_by_list on this list.....is it something similar to that you are suggesting?
