### ISSUE TITLE
Clarifai Issue

### ISSUE THREAD

**Issue by amauryleproux** [InstaPy/InstaPy#2148]
I would like to use clarifai to comment specific images

I've set up my quickstart file as the demo one on the wiki but I got this error 

Image check error: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//img[@class = "_2di5p"]"}

Any idea?

Also I've got an update message : "Hey! Clarifai Python Client v%s upgrade available. 2.2.3"

**Comment by CharlesCCC** [comment]
duplicated issue. have nothing to do with clarifai

**Comment by amauryleproux** [comment]
Duplicated with which one..?

**Comment by CharlesCCC** [comment]
@amauryleproux  this just one of the first issue https://github.com/timgrossmann/InstaPy/issues/2131

**Comment by ghoeffner** [comment]
@CharlesCCC #2131 does not contain any comment about this specific case. The fix today didn't include a fix for this problem.

**Comment by CharlesCCC** [comment]
I'm saying this error have nothing to do with `Clarifai` and it is an issue that introduced by instagram.com lately due to the css change. this is not the only issue. if there is more, please point out in the existing issue. thanks.

**Comment by marcomokastyle** [comment]
I'm new to python, so I don't know if is the best way to fix it, but for now it works, I have fixed this problem changing the code in clarifai_util.py with this:

def get_imagelink(browser):
    """Gets the imagelink from the given webpage open in the browser"""
    sleep(1)
    url = browser.find_element_by_xpath('(//img[@class="FFVAD"])[last()]') \
        .get_attribute('src')
    print("Url image for Clarifi: {}".format(url))
    return url

**Comment by mathyouf** [comment]
That code didn't work for me, it threw the same Image Check Error: Unable to Locate Element selector //img[@Class="FFVAD"])[last()]

**Comment by marcomokastyle** [comment]
@11fishem this is old, and indeed wrong, check this #2260
