### ISSUE TITLE
Using arabic in comments is not working

### ISSUE THREAD

**Issue by almzro3e** [InstaPy/InstaPy#2149]
Can we have a solution for arabic in comments?

**Comment by uluQulu** [comment]
Hi @almzro3e 

_Arabic language is the greatest language for me, so I feel obliged to help you :)_
And actually there is not much thing to do to get it work cos it already is supported!
##### Just make sure your text editor supports Arabic characters.

E.g. my machine is in English and the non-Unicode language is Russian and I have no any Arabic language support in my system.

**And** in **Notepad++** (_latest version_) text editor, it shows all Arabic characters in question marks `"??????"` if I directly enter characters in there.
```python
comments = ["??? ?????", "???? ?????"]
```
And while it tries to send those comments, it does not send anything.

But if you add `u` Unicode notation before the comments,
```python
comments = [u"??? ?????", u"???? ?????"]
```
It sends comments, but sends only those questions marks :D

**But** in other text editor- **Atom**, as I enter Arabic characters, it accepts them as they are
```python
comments = ["جيد", "جيد جدا"]
```
This time you don't even need `u` Unicode notation (_use if you will add emojis_)
It will work plain simple!

>And well you don't just need to use Atom text editor for this purpose, **the point is** to make your text editor accept the wanted characters. Playing with the settings of your existing text editor might help.

**Alternatively**, you can write your comments in Arabic language in a simple text file and save in either UTF-8 or Unicode encoding style (_but not ANSI_) and then load it into your **quickstart** script (_this solution will work regardless of the text editor_).

**Comment by almzro3e** [comment]
I couldn’t get it to work, im using atom but still couldn’t get arabic to work ..
