### ISSUE TITLE
Cookie file not found, creating cookie...

### ISSUE THREAD

**Issue by Tonners15** [InstaPy/InstaPy#2150]
Error: INFO [2018-06-01 12:45:24] [instausername] Session started - 2018-06-01 12:45:24 Traceback (most recent call last): File "quickstart.py", line 5, in <module> session.login() File "/Users/username/Downloads/InstaPy-master/instapy/instapy.py", line 322, in login self.bypass_suspicious_attempt): File "/Users/usernname/Downloads/InstaPy-master/instapy/login_util.py", line 136, in login_user "//select[@class='_fsoey']/option[text()='English']").click() File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath return self.find_element(by=By.XPATH, value=xpath) File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element 'value': value})['value'] File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute self.error_handler.check_response(response) File "/Library/Python/2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='_fsoey']/option[text()='English']"} (Session info: chrome=66.0.3359.181) (Driver info: chromedriver=2.39.562713 (dd642283e958a93ebf6891600db055f1f1b4f3b2),platform=Mac OS X 10.13.4 x86_64)
InstaPy ended Stop  

HELP!!

**Comment by CharlesCCC** [comment]
duplicated issue.
