### ISSUE TITLE
Instapy Closes quickly after it Starts

### ISSUE THREAD

**Issue by forgottensword** [InstaPy/InstaPy#2152]
[20180602-063638.zip](https://github.com/timgrossmann/InstaPy/files/2064540/20180602-063638.zip)

## Expected Behavior
To start the Instapy with quickstart.py

## Current Behavior

Not Starting up. Closes instantaneously after it looks for the cookie file.

**Comment by claraabelha** [comment]
Me too!! 
It says "Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20180601-222248.html " but I don't know how to do that lol

**Comment by forgottensword** [comment]
same issue is facing here @claraabelha

**Comment by forgottensword** [comment]
I tried clearing everything.. did fresh install... cleared temp files... cookies... everything.. updated chromedriver.... checked account details and tried changing credentials too

**Comment by claraabelha** [comment]
I tried re-download InstaPy but the issue still there... I think it's because Instagram had a new update in the login page! But I can't update InstaPy's one...

**Comment by forgottensword** [comment]
@claraabelha yeah... I kinda think so... Anyways.. keep me posted if anything comes up ...

**Comment by solehpolysas** [comment]
Hello,
Did you check new open PR?

Here some help for your error:
Check discussion #2133 
Check PR #2137 

The same PR for 2137 is #2146 

My tips, please read other closed or open issue first.
Then read new open or closed PR.

Sometimes there already fixed for running error, just not get merged.

Hope that help.

**Comment by forgottensword** [comment]
@solehpolysas  hey thanks for the help ... your login utils fixed the issue ... should i close this topic as this is a replica...

**Comment by uki-uki** [comment]
Same problem here, but this is after changing class to hztqj , it did run ok yesterday but today it crashed at the loggin page. It only run by clicking in the back button in the browser after it look for cookie.

```
Traceback (most recent call last):
  File "quickpy4.py", line 17, in <module>
    session.login()
  File "/home/uki/InstaPy/InstaPy-master/instapy/instapy.py", line 322, in login
    self.bypass_suspicious_attempt):
  File "/home/uki/InstaPy/InstaPy-master/instapy/login_util.py", line 151, in login_user
    click().send_keys(username).perform()
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/action_chains.py", line 74, in perform
    action()
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/action_chains.py", line 87, in <lambda>
    Command.CLICK, {'button': 0}))
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: Element is not currently visible and so may not be interacted with

```
[20180531-151554.html.log](https://github.com/timgrossmann/InstaPy/files/2064626/20180531-151554.html.log)

**Comment by ghost** [comment]
i keep getting `Wrong login data!`

**Comment by sohumsanu** [comment]
@uki-uki I'm getting that same problem as well and am not sure how to fix it.

**Comment by dreck142** [comment]
same here, have changed the class but receive "Wrong login data!" as a result. Anyone can help please?

**Comment by claraabelha** [comment]
Same here, @dreck142! The password is filled but the username doesn't. That's why it says the login is wrong...

**Comment by dreck142** [comment]
@claraabelha Managed to make it work... I logged in manually while Instapy was trying to go through (got to be fast!) and I was in.. sad solution but it works for now...

**Comment by plaksel** [comment]
This solved the cookie and login issue for me:

change line 136 of login_util.py: `//select[@class='_fsoey']/option[text()='English']").click()` 

to

`"//select[@class='hztqj']/option[text()='English']").click()
`
and add 

`sleep(2)
`
in between line 149:    ` # (valid for placeholder too)`
and: `input_username = browser.find_elements_by_xpath(`

**Comment by myDeveloperJourney** [comment]
@plaksel 

Thanks for adding that solution. I edited my login_util.py and got it working!

**Comment by stefanobg** [comment]
This solved my problem!! Thanks

**Comment by ceylanayberk** [comment]
@plaksel  can you upload your login_util.py
