### ISSUE TITLE
Wrong login credentials

### ISSUE THREAD

**Issue by Baniyal** [InstaPy/InstaPy#2153]
## Expected Behavior
normal functioning of the script
## Current Behavior
in spite of the chrome window opening and the automatically logging into my Instagram.i can view it on the chrome window that is generated. Although soon after that the window abruptly closes and the error displayed is "Wrong login credentials".Yes i have verified the credentials ! 

Thankyou in advance

**Comment by imbarismustafa** [comment]
Can you share the error with us. Thanks.

**Comment by sionking** [comment]
R u using any server like AWS / DO ?

**Comment by solehpolysas** [comment]
Can you try this #2133 
Maybe its related to your issue.

Hope that help.
