### ISSUE TITLE
New account - not filling the username.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2157]
It only fills the password and throw wrong login data.
anyone managed to solve it ?

**Comment by solehpolysas** [comment]
@sionking  already done here https://github.com/timgrossmann/InstaPy/issues/2133#issuecomment-394098747

using open PR #2146  but need to ADD small delay `sleep(1)` at new line 147.
Mine working fine. 👍 

Feel free to check & update.

**Comment by ghost** [comment]
works for me on ubuntu 
added sleep(1) at new line 147 in instapy/login_util.py

**Comment by axlright** [comment]
Had this same issue and after banging my head against the keyboard for an hour or two, PR #2146 and https://github.com/timgrossmann/InstaPy/issues/2133#issuecomment-394098747 worked perfect. 👍 🥇

**Comment by sambrucejoseph** [comment]
Still doesn't work after changing the class name and adding the sleep(1)
It still doesn't key in the username
