### ISSUE TITLE
Script ignores .set_dont_include, unfollows all users

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#216]
I noticed a few days ago that the script wont unfollows all of my followings, regardless if they are in my set_dont_include or not.

I’ve just checked my instagram page if instagram has changed something regarding the xpath but everything seems to be the same so far.

Has anyone noticed the same or perhaps an idea how to fix this?

**Comment by timgrossmann** [comment]
@tibor Weird, I'm using this feature like 4 months now and never had a problem.
Make sure the usernames are written correctly (by now, even case **sensitive**)

**Comment by tibor** [comment]
Yep, they’re all written correctly.

I’m running scripts for two accounts from the same VPS / InstaPy installation, sometimes also parallel. Can this lead to such errors?

I’m wondering because I’ve never noticed such behaviour on my Mac (where I also ran two accounts parallel)

**Comment by raulafrosa** [comment]
I'm having the same issue.
In my case I'm using InstaPy GUI so the quick start creats a section.friend_list but in instapy.py the name should be dont_include, so I chage all dont_include for friend_list in instapy.py and in unfollow_util.py (but in unfollow_util.py I don't think that is necessary).

**Comment by tibor** [comment]
Tested #233, works now without problems
