### ISSUE TITLE
IG Python script - scraping is taking too long

### ISSUE THREAD

**Issue by bluewhale9** [InstaPy/InstaPy#2160]
Hello, this is not an issue with your app, but I am a python newbie starting to develop my own IG analytics tool (not a bot). I hope I can ask you a question?

I'm running into an issue during scraping a user's followers. After scraping X amount of followers, IG Temp blocks my actions, so I put a wait timer in the script to retry & continue after Y minutes. This seems to work well, but its taking forever. On a user with 50,000 followers, it has taken my python script 30+ Hours to complete. Do you have a suggestion (or an example inside your script) of how to speed this up? 

Thank you

**Comment by sionking** [comment]
In this method you can't scrap 50K users.
There are other ways... like scraping with another user and save to list, then feed your real users.

**Comment by bluewhale9** [comment]
Thank you for your insight! Are you referring to multithreading with python?

So if I use multithreading with multiple different users with different user-agents?

**Comment by sionking** [comment]
no no don't complicate it.
scrap the user (take a week let say) than feed  the user.
