### ISSUE TITLE
Changing a username of Instagram account

### ISSUE THREAD

**Issue by ArdySan2012** [InstaPy/InstaPy#2162]
This is rather a question... Has anyone done it?
The issue is - after changing the username with instagram, the bot (due to multi account support) - essentially "starts over" for this new account. E.g. ignoring all the users u've followed-unfollowed in the past already. 
Is there a way to "transfer" this database to a new username?

**Comment by sionking** [comment]
I think just change the string you login with leave the rest untouched.

**Comment by ArdySan2012** [comment]
I tried that - but it creates a separate account folder under new username, and starts following users which I followed/unfollowed in the past... :(

**Comment by sionking** [comment]
Withou multilog this worked for me

**Comment by ArdySan2012** [comment]
How do you disable it?
