### ISSUE TITLE
Need your Help This my error Pythonanywhere :)

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#2164]
12:55 ~/InstaPy (master)$ pip3 install .                                                                                                  
Processing /home/johnvfitness/InstaPy                                                                                                     
Collecting selenium==2.53.6 (from instagram-py==0.0.1)                                                                                    
Collecting clarifai==2.0.32 (from instagram-py==0.0.1)                                                                                    
Collecting pyvirtualdisplay (from instagram-py==0.0.1)                                                                                    
Collecting emoji (from instagram-py==0.0.1)                                                                                               
Collecting enum34==1.1.6 (from clarifai==2.0.32->instagram-py==0.0.1)                                                                     
Requirement already satisfied: requests==2.13.0 in /usr/local/lib/python3.6/dist-packages (from clarifai==2.0.32->instagram-py==0.0.1)    
Collecting configparser==3.5.0 (from clarifai==2.0.32->instagram-py==0.0.1)                                                               
Collecting jsonschema==2.5.1 (from clarifai==2.0.32->instagram-py==0.0.1)                                                                 
Collecting Pillow==2.9.0 (from clarifai==2.0.32->instagram-py==0.0.1)                                                                     
Collecting future==0.15.2 (from clarifai==2.0.32->instagram-py==0.0.1)                                                                    
Requirement already satisfied: EasyProcess in /usr/local/lib/python3.6/dist-packages (from pyvirtualdisplay->instagram-py==0.0.1)         
Installing collected packages: selenium, enum34, configparser, jsonschema, Pillow, future, clarifai, pyvirtualdisplay, emoji, instagram-py
  Found existing installation: selenium 3.0.2                                                                                             
    Uninstalling selenium-3.0.2:                                                                                                          
Exception:                                                                                                                                
Traceback (most recent call last):                                                                                                        
  File "/usr/lib/python3.6/shutil.py", line 538, in move                                                                                  
    os.rename(src, real_dst)                                                                                                              
OSError: [Errno 18] Invalid cross-device link: '/usr/local/lib/python3.6/dist-packages/selenium-3.0.2.dist-info/DESCRIPTION.rst' -> '/tmp/
pip-f6ww3vb4-uninstall/usr/local/lib/python3.6/dist-packages/selenium-3.0.2.dist-info/DESCRIPTION.rst'                                    
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.6/dist-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python3.6/dist-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python3.6/dist-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python3.6/dist-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python3.6/shutil.py", line 553, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/selenium-3.0.2.dist-info/DESCRIPTION.rst'
12:55 ~/InstaPy (master)$

**Comment by johnvfitness** [comment]
@uluQulu

**Comment by uluQulu** [comment]
Hi @johnvfitness 
I have so less information about PythonAnywhere installations.
I can say,
It wants to install selenium v2.53.6 but there already is a newer version of selenium currently installed v3.0.2
```powershell
Collecting selenium==2.53.6 (from instagram-py==0.0.1)

Installing collected packages: selenium

Found existing installation: selenium 3.0.2
Uninstalling selenium-3.0.2:
```
It complains about having no privileges to remove selenium
```powershell
OSError: [Errno 18] Invalid cross-device link: '/usr/local/lib/python3.6/dist-packages/selenium-3.0.2.dist-info/DESCRIPTION.rst' -> '/tmp/
```
And it has no privileges to move selenium file to **/tmp/** location while removing it
```powershell
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/selenium-3.0.2.dist-info/DESCRIPTION.rst'
```

What you can do is to run you commands with higher privileges as `sudo` or `su -` according to your OS and see if it works

Also, installing old version of selenium is no good, why don't you install up-to-date InstaPy?  
I think you can do it easily using `git`.

**Comment by johnvfitness** [comment]
I do not know the password
I never put.....
@uluQulu
