### ISSUE TITLE
Wrong Login Data

### ISSUE THREAD

**Issue by sandy1812** [InstaPy/InstaPy#2169]
Hello
I deployed InstaPy on the digital ocean and tested it for a new Instagram account and it worked really well, but when I changed (My own Instagram)the account I am getting error" Wrong login data"

I tried changing the codes per several other threads but it is messed up.
Tried changing the files as per new PRs but getting other errors like - 

INFO - Session started - 2018-06-03 22:19:02
CRITICAL - Wrong login data!
Traceback (most recent call last):
  File "quickstart.py", line 9, in <module>
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 226, in login
    log_follower_num(self.browser, self.username)
  File "/root/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    "return window._sharedData.""entry_data.ProfilePage[0]."
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'followed_by' of undefined
  (Session info: chrome=67.0.3396.62)
  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.4.0-127-generic x86_64)

I am not much into Python, so please help me.

**Comment by andreescocard** [comment]
Wrong login data seems to be a ban from Instagram. If you login to your account you will see a challenge url asking to confirm if it was you, even if you confirm, when you run the script again, it will show the same error. I got some accounts with the same behavior.

**Comment by mkhattar** [comment]
Same error here. Instapy is working perfectly on one account, but whenever I try to use it with a new account I get the error "Wrong login data". Any suggested solution?

**Comment by Doom666** [comment]
try:
bypass_suspicious_attempt=True
in your sessions settings
this will send an email with a code, and instapy will prompt you to enter the code, and then , boila! you are in

**Comment by Areahints** [comment]
hello, when you use such code, must you always use it or can you remove it after the first run, because it requires a code sent to the email address and im wondering if instapy has to request that code on every run @charlesccc @uluqulu

**Comment by Areahints** [comment]
currently all my accounts (4) are having the suspicious login issue, im hoping that i dont lose any accounts and have temporarily shut down my runs till i get this sorted

**Comment by CharlesCCC** [comment]
@Areahints it will only request code if the prompt from the website. after you confirmed all the accounts has successfully created cookie file, you can turn it off.

**Comment by Areahints** [comment]
i have been able to login all previous accounts running before, i cant add new accounts tho! does anyone know how msny accounts per ip is permissible (currently on 3)

**Comment by JuanSpada** [comment]
Did u fix this? Same issue
