### ISSUE TITLE
Chrome headless

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#217]
@vlntdds @pekapa @AlainPilon @littleswany You guys probably heard and read about it... Chrome headless is here and I think this should be part of InstaPy_V1!

What do you think?

**Comment by littleswany** [comment]
I hadn't head of it yet, will blame that on being too busy with school stuff.

Will do some more research but from a quick glance looks like it could be useful.

https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by tibor** [comment]
Just wanted to open this issue as well :)
[Here is the Blog post](http://blog.chromium.org/2017/05/chrome-59-beta-headless-chromium-native.html) from the official Chromium blog.

**Comment by pekapa** [comment]
I've just tried using PhantomJS and I have bad news...
The image load problem, it can only fetch the first images and it is unable to get more images as the browser is now always out of sight.

I was trying to understand how IG actually load those images. It's a POST request to query them and somehow it's injected into the page after but this injection seems to only happen if it have OS focus (any ideas how?). Maybe we could try to get those images simulating the same POST request.

**Comment by timgrossmann** [comment]
@pekapa Yup, that's why the most simple solution with the current version was to simply go to the top then the bottom, again and again.
You could do all the automation with the requests only, you just had to get the initial session token on login. But this would look like a bot, and probably get banned really quick.

**Comment by timgrossmann** [comment]
#416
