### ISSUE TITLE
instapy.instapy.InstaPyError: ensure chromedriver is installed at "dummyurl/pythonEnvironments/instapy_env/InstaPy/assets/chromedriver"

### ISSUE THREAD

**Issue by tifDev** [InstaPy/InstaPy#2179]
When i try to run quickstart.py i get this error: 

`instapy.instapy.InstaPyError: ensure chromedriver is installed at "dummyurl/pythonEnvironments/instapy_env/InstaPy/assets/chromedriver"`

I've checked and the chrome driver (extracted) is there. 

How can i solve this?

**SO: Ubuntu 18.04 TLS Server
ChromeDriver version: 2.39
I've used virtualenv to create a virtual environment for instapy
**

**Comment by Doom666** [comment]
try this
https://github.com/timgrossmann/InstaPy/issues/2215

**Comment by Marow** [comment]
Same problem here... 

I tryied #2215 but its also not working

I get 
```
WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.13.0-39-generic x86_64)

instapy.instapy.InstaPyError: ensure chromedriver is installed at /var/www/instapy/InstaPy/assets/chromedriver
```

**Comment by SimplSam** [comment]
You may also need to upgrade your version of Chrome.

```
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb; sudo apt-get -fy install
```

**Comment by ghost** [comment]
i'm having a similar issue, with chromedriver , chrome and proxies , headless true ...

if i turn off headless it works.

if i turn on headless and without a proxy it works ... any ideas ?

**Comment by holayeah** [comment]
Check the logs /logs/general.log to identify the correct issue, the error for me was misleading. 

The issue was that my chrome was version 66 and the chrome drive i have requires 67
