### ISSUE TITLE
Problem with starting InstaPy

### ISSUE THREAD

**Issue by All4MyChan** [InstaPy/InstaPy#2181]
I was using InstaPy for 5 months then I paused for 2 weeks maybe and now when i`m trying to use bot i got this problem. 
Bot doesn`t fill login info just password and then there is an error "Wrong login data"
## Specs
OS Win7
Latest Chrome browser
Latest Chromedriver
## Log from cmd
C:\Users\bravo\Downloads\InstaPy-master>py start.py
[3184:4092:0605/111354.163:ERROR:install_util.cc(589)] Unable to create registry
 key HKLM\SOFTWARE\Policies\Google\Chrome for reading result=2

DevTools listening on ws://127.0.0.1:50483/devtools/browser/048751d9-d381-4956-a
26b-763650968f9d
[2840:4856:0605/111354.453:ERROR:gl_surface_egl.cc(844)] eglInitialize D3D11 fai
led with error EGL_NOT_INITIALIZED, trying next display type
[2840:4856:0605/111355.524:ERROR:gl_surface_egl.cc(844)] eglInitialize D3D9 fail
ed with error EGL_NOT_INITIALIZED
[2840:4856:0605/111355.524:ERROR:gl_initializer_win.cc(232)] GLSurfaceEGL::Initi
alizeOneOff failed.
[2840:4856:0605/111355.524:ERROR:viz_main_impl.cc(199)] Exiting GPU process due
to errors during initialization
[3184:4092:0605/111355.597:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI
 shared context.
[1644:2064:0605/111355.614:ERROR:command_buffer_proxy_impl.cc(114)] ContextResul
t::kFatalFailure: Shared memory handle is not valid
INFO [2018-06-05 11:13:55] [not_shafran]  Session started - 2018-06-05 11:13:55
WARNING [2018-06-05 11:13:55] [not_shafran]  Sorry, Record Activity is not worki
ng on Windows. We're working to fix this soon!
Cookie file not found, creating cookie...
CRITICAL [2018-06-05 11:14:10] [xxx]  Wrong login data!
INFO [2018-06-05 11:14:13] [xxx]  User 'user1' [1/5]
ERROR [2018-06-05 11:14:46] [xxx]  Could not determine if masha.smo has
followers
INFO [2018-06-05 11:14:50] [xxx]  Session ended - 2018-06-05 11:14:50
INFO [2018-06-05 11:14:50] [xxx]  --------------------

Traceback (most recent call last):
  File "start.py", line 42, in <module>
    'user1'], amount=190, randomize=False, sleep_delay=120)
  File "C:\Users\bravo\Downloads\InstaPy-master\instapy\instapy.py", line 1907,
in follow_user_followers
    self.logfolder)
ValueError: not enough values to unpack (expected 2, got 0)

C:\Users\bravo\Downloads\InstaPy-master>

## InstaPy configuration
from selenium.common.exceptions import NoSuchElementException
from instapy import InstaPy

insta_username = 'xxx'
insta_password = 'xxx'

    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      )
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
			 potency_ratio=-1.21,
			  delimit_by_numbers=True,
			   max_followers=4590,
			    max_following=5555,
			     min_followers=45,
			      min_following=77)
    session.set_do_comment(False, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    session.follow_user_followers(['masha.smo', 'alexandramitroshina','profil_govno', 'tom_vverh_dnom',
    'sshimanskaya'], amount=190, randomize=False, sleep_delay=120)

    # Like posts based on hashtags and like 3 posts of its poster
    session.like_by_tags(['tag1', 'tag2', 'tag3', 'tag4', 'tag5'], amount=27)

finally:
    # end the bot session
    session.end()

**Comment by uluQulu** [comment]
@All4MyChan 
Pull latest files and see if it works, if not report back.

Cheers

**Comment by All4MyChan** [comment]
It`s working for 100%. Thank you @uluQulu.
