### ISSUE TITLE
[ERROR] " Cannot unfollow from InstaPy" Unfollow skips everyone without unfollowing

### ISSUE THREAD

**Issue by edobranchi** [InstaPy/InstaPy#2184]
## Expected Behavior
Unfollow people in the .csv file in the logs folder
## Current Behavior

 The bot start, but can't unfollow anyone.
I tried to turn off the headless browser and I saw that the bot can open instagram, than opens the page of the account I wish to unfollow but then just skips to the next one printing out what's below.
(I'm on the last version)

>INFO [2018-06-06 00:19:01] [My_user]  Session started - 2018-06-06 00:19:01
>INFO [2018-06-06 00:19:30] [My_user]  Logged in successfully!
>INFO [2018-06-06 00:19:33] [My_user]  --> unfollow_users, amount: 82 
>INFO [2018-06-06 00:19:33] [My_user  Number of users available to unfollow: 1442
>WARNING [2018-06-06 00:19:36] [My_user]  --> Cannot Unfollow From InstaPy 0, now unfollowing: b'xxxxxxxxxxxxxx'
>WARNING [2018-06-06 00:19:41] [My_user]  --> Cannot Unfollow From InstaPy 0, now unfollowing: b'xxxxxxxxxxxxxx'
>WARNING [2018-06-06 00:19:46] [My_user]  --> Cannot Unfollow From InstaPy 0, now unfollowing: b'xxxxxxxxxxxx'
>WARNING [2018-06-06 00:19:51] [My_user]  --> Cannot Unfollow From InstaPy 0, now unfollowing: b'xxxxxxxxxxxxxxxxxx'
>WARNING [2018-06-06 00:19:56] My_user]  --> Cannot Unfollow From InstaPy 0, now unfollowing: 
> b'xxxxxxxxxxxxxxxx

## Possible Solution (optional)
Don't know

## InstaPy configuration

        insta_username = 
	insta_password = 
	# set headless_browser=True if you want to run InstaPy on a server

	# set these in instapy/settings.py if you're locating the
	# library in the /usr/lib/pythonX.X/ directory:
	#   Settings.database_location = '/path/to/instapy.db'
	#   Settings.chromedriver_location = '/path/to/chromedriver'

	session = InstaPy(username=insta_username,
	                  password=insta_password,
	                  headless_browser=False,
	                  multi_logs=False)

	try:
	    session.login()

	    # settings
	    
	    session.set_do_comment(enabled=False, percentage=10)
	    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
	    session.set_dont_include(['friend1', 'friend2', 'friend3'])
	    session.set_dont_like(['pizza', 'girl'])
	    

	    # actions

	    session.unfollow_users(amount=(randint (70,100)),onlyInstapyFollowed=True,sleep_delay=650,unfollow_after=23*60*60)

	except Exception as exc:
	    # if changes to IG layout, upload the file to help us locate the change
	    if isinstance(exc, NoSuchElementException):
	        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
	        with open(file_path, 'wb') as fp:
	            fp.write(session.browser.page_source.encode('utf8'))
	        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
	            '*' * 70, file_path))
	    # full stacktrace when raising Github issue
	    raise

	finally:
	    # end the bot session
	    session.end()

`

**Comment by sionking** [comment]
New confirmation msg show when unfollow!

**Comment by edobranchi** [comment]
@sionking I don't know if it's this case, I tried to unfollow manually from the browser , it works normally and the confirmation message didn't show up.

**Comment by sionking** [comment]
1/50 times it do show something like this:
![image](https://user-images.githubusercontent.com/7851877/41039033-d980da86-69a0-11e8-9320-83fdcd8b9f10.png)

**Comment by edobranchi** [comment]
Don't know, I have never saw this kind of pop-up.
Let's wait to see if anyone is experiencing this

**Comment by edobranchi** [comment]
UPDATE : A lot of people that was already "unfollowed" were still in the csv so I got the error.
I don't know why they weren't deleted  but I have an advice
In case of already unfollowed launch a particular error like "Person already unfollowed" and not a generic "cannot unfollow from intsapy"

Now i'm solving it running the unfollow and see at which point it stops giving errors, than I search the last username in the csv file and delete everyone before following that person, practically i'm cleaning it
