### ISSUE TITLE
Quickstart wont start

### ISSUE THREAD

**Issue by kixanai** [InstaPy/InstaPy#2185]
## Expected Behavior
Quickstart.py working 
## Current Behavior
Quickstart.py opens and then instantly closes
## InstaPy configuration

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1,
				  delimit_by_numbers=False)
    session.set_do_comment(False)

    # actions
    session.like_by_feed(amount=50, randomize=True, unfollow=True, interact=True)
    session.follow_user_followers(['_dinis'], amount=100, randomize=False, sleep_delay=30)
    session.set_do_follow(enabled=True, percentage=70, times=2)
    session.unfollow_users(amount=150, onlyNotFollowMe=True, sleep_delay=30)

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

CMD LOG:

C:\Users\kixan\InstaPy>python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "C:\Users\kixan\InstaPy\instapy\instapy.py", line 119, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "C:\Users\kixan\InstaPy\instapy\unfollow_util.py", line 822, in load_follow_restriction
    return json.load(followResFile)
  File "C:\Program Files (x86)\Python36-32\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Program Files (x86)\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by uluQulu** [comment]
@kixanai
https://github.com/timgrossmann/InstaPy/issues/1732#issuecomment-383390727

**Comment by kixanai** [comment]
I've found this solution earlier, yet couldnt make it to work, I cant find get_watchers function, should I add it?

**Comment by uluQulu** [comment]
@kixanai 
#1732 thread is for other purpose, so is `get_watchers` definition.
You just need to apply the steps explained in that particular comment I shared link of.

**Comment by kixanai** [comment]
followRestriction.json seems fine

**Comment by kixanai** [comment]
You right, saw on the wrong file durp
