### ISSUE TITLE
Saving Posts

### ISSUE THREAD

**Issue by kenstowe** [InstaPy/InstaPy#2188]
Is there a way for instapy to be set to save a post? 

If not, can this feature be added? It will help boost engagement.

**Comment by uluQulu** [comment]
Yes @TruthLore 
_How it helps to boost it?_

**Comment by kenstowe** [comment]
@uluQulu 
Engagement is based on likes, comments, views, saves, shared posts, DM’s, etc.  The reach of a post is based on the amount of interactions(engagement) a posts gets, heavily weighted to the interactions received shortly after posting. So if an instapy bot can like, comment, and save a post it will create higher engagement than just liking and commenting.

Another benefit from the ability to save is in creating a bot with more variability, hopefully making it seem more like a real person. If the bot likes 75% of posts, comments on 50%, and saves 25% it will have more varied actions and may look more realistic.

**Comment by uluQulu** [comment]
@TruthLore 
Right, it is good for the first-user (_who posted_).  
But I couldn't get what is its return for the second-user (_who saved that post_).

Adding a feature always costs time of support and it should be added only if it has a benefit.

>BTW generally, only ~ 1 - 5 % of posts are being saved, so it is not so crucial for having in activity flow.

_Also, some users would not like to mess their _Saved Posts_ gallery in their main accounts_ ☕️

**Comment by uluQulu** [comment]
@TruthLore 
I didn't mean any to suppress your idea 😀
If you like, I can help you achieve it, it is so easy to implement!

**Comment by kenstowe** [comment]
@uluQulu 
No worries, it'd be great if you could help implement.
