### ISSUE TITLE
Problem!

### ISSUE THREAD

**Issue by gmatteo679** [InstaPy/InstaPy#2195]
Hello
I have problems ... here is the screen of the terminal.
what can it be?
I followed each step carefully and tried to run instapy on other PCs but the same error happens

![screen](https://user-images.githubusercontent.com/40022013/41097743-58c38f38-6a59-11e8-9e2b-556d6c1d502b.png)

**Comment by edobranchi** [comment]
Seems a chrome driver issue, try reinstalling it following the instruction https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md

**Comment by gmatteo679** [comment]
altro errore... ma è possibile?
i have reinstalled all driver...
![schermata del 2018-06-07 23-37-39](https://user-images.githubusercontent.com/40022013/41127646-e3b48e42-6aab-11e8-92c9-a07a1ed71fe1.png)

**Comment by edobranchi** [comment]
In quickstart.py go to the section "session=(............., multi_log=True)" and change it to " False"

**Comment by gmatteo679** [comment]
nothing .. always the same mistake.
this is in the code of quickstart.py
![1](https://user-images.githubusercontent.com/40022013/41151978-a88b12de-6b12-11e8-96c3-95c055e513cd.png)
![2](https://user-images.githubusercontent.com/40022013/41151980-a8aee4c0-6b12-11e8-9349-8a47898b839f.png)

**Comment by gmatteo679** [comment]
....
