### ISSUE TITLE
Simulated follow - when trying to load someone else followers for interaction

### ISSUE THREAD

**Issue by ArdySan2012** [InstaPy/InstaPy#2200]
I understand this is a new workaround not being able to scroll through someone else followers.

Is there a way to control how often it "simulated follows". I'd rather it not being able to load the required amount of users than produce follows/unfollows at such speed (It did about 5 follows in a minute).

Need some insight here :)

**Comment by ArdySan2012** [comment]
Do I understand correctly that some of these numbers below is responsible for how often it "simulated follows"?
I just can't figure which one :)

        # Will follow a little bit of users in order to simulate real interaction
        if (simulator_counter > random.randint(5, 17) or
                abort==True or
                    total_list >= amount or
                        sc_rolled==random.randint(3, 5)):
quick_amount = 1 if not total_list >= amount else random.randint(1, 4)

**Comment by uluQulu** [comment]
Hi @ArdySan2012 
Yes exactly, insights will be good to improve mechanisms.

That's right, Those lines are the conditional statement for triggering simulated follows.
There are certain situations I did consider while implementing:
+ per amount of scrolls
+ near exit
+ near enter

Actually, I did write that feature in so quick time and having more sophisticated triggering algorithm for it will be so handy, do you have any suggestions to improve it?

**Comment by ArdySan2012** [comment]
You know me @uluQulu I am not much of a programmer :D But - that is what I've done:

>                         sc_rolled==random.randint(0, 0)):
>             quick_amount = 1 if not total_list >= amount else random.randint(1, 1)

That somehow results in no more than 2 simulated follows per 200-250 loaded users for each account (which is what I wanted)

**Comment by uluQulu** [comment]
That's a good start, @ArdySan2012 😄
Programming is done only to achieve what you wanted and I see you made it happen 💪🏼
