### ISSUE TITLE
Seems to fail when using "set_delimit_commenting(enabled=True..."

### ISSUE THREAD

**Issue by lemon6949** [InstaPy/InstaPy#2202]
## Current Behavior

Ive encountered a few issues with the most painful being it seems to fail when I used the session.set_delimit_commenting(enabled=True, max=32, min=0)

Ive read through the PR and haven't been able to find a clear/similar problem and solution, but new to this all so I might have missed something

tried versions
  selenium 2.53.6
  chromedriver 2.40

current versions
  selenium-3.12.0
  chromedriver 2.36
  chrome=67.

(to deviate for a second, I did have problem randomly with session.set_do_comment and #set_delimit_commenting (commented out) where it would randomly just fail, but seems more stable with chromedriver 2.36)

(venv) 192-168-1-2:InstaPy user$ python quickstart.py 
INFO [2018-06-08 18:40:46] [instagramuser]  Session started - 2018-06-08 18:40:46
INFO [2018-06-08 18:41:20] [instagramuser]  Logged in successfully!
INFO [2018-06-08 18:41:25] [instagramuser]  Tag [1/10]
INFO [2018-06-08 18:41:25] [instagramuser]  --> outfitoftheday
INFO [2018-06-08 18:41:35] [instagramuser]  desired amount: 50  |  top posts [disabled]: 9  |  possible posts: 30175226
INFO [2018-06-08 18:42:02] [instagramuser]  [1/50]
INFO [2018-06-08 18:42:02] [instagramuser]  https://www.instagram.com/p/BjweDLOgoaB/?tagged=outfitoftheday
INFO [2018-06-08 18:42:06] [instagramuser]  Image from: jupiterjewelry
INFO [2018-06-08 18:42:06] [instagramuser]  Link: https://www.instagram.com/p/BjweDLOgoaB/?tagged=outfitoftheday
INFO [2018-06-08 18:42:06] [instagramuser]  Description: "tetrahedron pearl series"
You’ll make a very stylish woman!
☆
☆
☆
#outfitoftheday#fashionblogger#fashionstyle#fashionable#instafollow#instajewelry#london#accessorise#ring#earrings#necklace#bracelet#gift#beautiful#watch#ootd#outfit#coordinate#ootdfashion#tokyofashion
INFO [2018-06-08 18:42:35] [instagramuser]  User: jupiterjewelry >> followers: 2417  |  following: unknown  |  relationship ratio: unknown
INFO [2018-06-08 18:42:40] [instagramuser]  --> Image Liked!
INFO [2018-06-08 18:42:42] [instagramuser]  --> User followed: [u'jupiterjewelry']
INFO [2018-06-08 18:42:42] [instagramuser]  Username [1/1]
INFO [2018-06-08 18:42:42] [instagramuser]  --> jupiterjewelry
INFO [2018-06-08 18:43:11] [instagramuser]  User: jupiterjewelry >> followers: 2418  |  following: unknown  |  relationship ratio: unknown
INFO [2018-06-08 18:43:11] [instagramuser]  Getting jupiterjewelry image list...
INFO [2018-06-08 18:43:36] [instagramuser]  Interaction begin...
INFO [2018-06-08 18:44:07] [instagramuser]  --> Not following
INFO [2018-06-08 18:44:08] [instagramuser]  Liked: 0
INFO [2018-06-08 18:44:08] [instagramuser]  Already Liked: 0
INFO [2018-06-08 18:44:08] [instagramuser]  Commented: 0
INFO [2018-06-08 18:44:08] [instagramuser]  Inappropriate: 0
INFO [2018-06-08 18:44:08] [instagramuser]  Not valid users: 0

INFO [2018-06-08 18:44:10] [instagramuser]  Failed to check comments' status for verification...

INFO [2018-06-08 18:44:10] [instagramuser]  Session ended - 2018-06-08 18:44:10
INFO [2018-06-08 18:44:10] [instagramuser]  --------------------

Traceback (most recent call last):
  File "quickstart.py", line 52, in <module>
    session.like_by_tags(['outfitoftheday', 'lookbook', 'instastyle', 'lookoftheday','streetfashion','fashiondiaries','fashionblog','oftd','streetstyle','seattlefashion'], amount=50, interact=True)
  File "Projects/user/InstaPy/instapy/instapy.py", line 1247, in like_by_tags
    self.commenting_approved, disapproval_reason = verify_commenting(self.browser, self.max_comments, self.min_comments, self.logger)
  File " Projects/user/InstaPy/instapy/comment_util.py", line 88, in verify_commenting
    "return window._sharedData.entry_data."
  File "Projects/user/InstaPy/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 629, in execute_script
    'args': converted_args})['value']
  File " Projects/user/InstaPy/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File " Projects/user/InstaPy/venv/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: chrome=67.0.3396.79)
  (Driver info: chromedriver=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8),platform=Mac OS X 10.13.4 x86_64)

note: I get the same traceback with

  session.set_delimit_commenting(enabled=True, max=32, min=None)
    or
  session.set_delimit_commenting(enabled=True, max=32)

as another deviation; has anyone had any luck with commenting by tag without liking the photo.
I read a PR that said it would be possible as comment_by_locations already does this but couldn't what to change in instapy.py

I tried a cheeky session.set_do_like(enabled=False) with the session.like_by_tags but that didnt work :)

Id like to be able to comment on photos without filling my 'photos you liked' up, as nasty hack to turn likes off on the session.like_by_tags would do me fine

## InstaPy configuration

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
                 potency_ratio=None,
                  delimit_by_numbers=True,
                   max_followers=50000,
                    max_following=2000,
                     min_followers=45,
                      min_following=77)
    
    session.set_do_comment(True, percentage=100)
    session.set_delimit_commenting(enabled=True, max=32, min=0)
    session.set_comments(['Amazing!'])
    session.set_do_like(enabled=True, percentage=0) 
    session.set_delimit_liking(enabled=True, max=250, min=0)
    
    # actions
    var = 1
    while var == 1 :

        session.like_by_tags(['outfitoftheday', 'lookbook', 'instastyle', 'lookoftheday','streetfashion','fashiondiaries','fashionblog','oftd','streetstyle','seattlefashion'], amount=50, interact=True)

        time.sleep(600)

**Comment by lemon6949** [comment]
Update: I found a nasty hack to fix my comment without liking problem

like_util.py

find: def like_image
comment out click_element(browser, like_elem[0])
change unlike to Like       liked_elem = browser.find_elements_by_xpath(
            "//a[@role='button']/span[text()='unlike']") 
change to Image Not Liked! logger.info('--> Image Liked!')

Still trying to understand the issue with set_delimit_commenting

**Comment by uluQulu** [comment]
Hey @lemon6949 
Actually, it's a bit of my mistake! 😂

To **solve**, open up **comment_util.py** file and remove both of the `raise` lines in `verify_commenting` definition.
It would be great if you could PR this change.

_The **reason** is, `raise` is good for troubleshooting and by raising the last exception occured, it also terminates the program at that position. And I did forgot about it while writing that function._
