### ISSUE TITLE
Not able to run must functions (Request for a total UPDATE)

### ISSUE THREAD

**Issue by Essbuisness** [InstaPy/InstaPy#2203]
The whole script gave me, quite alot of issues to fix before, I was even able to log in to instagram
without no errors
Finally logged in today :-) after following all the possible solutions step by step (which took me alot of time). i dont really know much about coding and stuff so this is quite a challenge 
Was about to run the script to do some liking function but it did not work
tried following function still did not work
No function works at all
Please HELP
Here is my LOG
`[7620:6272:0608/110837.941:ERROR:install_util.cc(597)] Unable to read registry value HKLM\SOFTWARE\Policies\Google\Chrome\MachineLevelUserCloudPolicyEnrollmentToken for writing result=2

DevTools listening on ws://127.0.0.1:12197/devtools/browser/e8a28922-fcc7-4995-a8bb-8df01e7b8d71
INFO [2018-06-08 11:08:43] [walkjoice]  Session started - 2018-06-08 11:08:43
WARNING [2018-06-08 11:08:43] [walkjoice]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO [2018-06-08 11:10:13] [walkjoice]  Logged in successfully!
INFO [2018-06-08 11:10:23] [walkjoice]  Starting to follow likers..
('\nGetting likers from user: ', 'benedictaaaa', '\n')
('Got ', 12, ', returning ', 2, ' links: ', [u'https://www.instagram.com/p/BjPe7bvgtQS/?taken-by=benedictaaaa', u'https://www.instagram.com/p/BiOUW5mArD_/?taken-by=benedictaaaa'])
opening likes
Some problem
Message: unknown error: call function result missing 'value'
  (Session info: chrome=67.0.3396.79)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.14393 x86_64)

opening likes
Some problem
Message: unknown error: call function result missing 'value'
  (Session info: chrome=67.0.3396.79)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.14393 x86_64)

('\nGetting likers from user: ', 'picturesbyhaniff', '\n')
('Got ', 24, ', returning ', 2, ' links: ', [u'https://www.instagram.com/p/BjiSEoklxmp/?taken-by=picturesbyhaniff', u'https://www.instagram.com/p/BjAoLjplVqk/?taken-by=picturesbyhaniff'])
opening likes
Some problem
Message: unknown error: call function result missing 'value'
  (Session info: chrome=67.0.3396.79)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.14393 x86_64)

opening likes
Some problem
Message: unknown error: call function result missing 'value'
  (Session info: chrome=67.0.3396.79)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.14393 x86_64)

('\nGetting likers from user: ', 'boy.like.russ9ll', '\n')
('Got ', 3, ', returning ', 2, ' links: ', [u'https://www.instagram.com/p/BikKo7JnCJI/?taken-by=boy.like.russ9ll', u'https://www.instagram.com/p/BhzYBG1HIzY/?taken-by=boy.like.russ9ll'])
opening likes
Some problem
Message: unknown error: call function result missing 'value'
  (Session info: chrome=67.0.3396.79)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.14393 x86_64)

opening likes
Some problem
Message: unknown error: call function result missing 'value'
  (Session info: chrome=67.0.3396.79)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.14393 x86_64)

INFO [2018-06-08 11:12:56] [walkjoice]  Finished following likers!

INFO [2018-06-08 11:12:56] [walkjoice]  Tag [1/3]
INFO [2018-06-08 11:12:56] [walkjoice]  --> natgeo
INFO [2018-06-08 11:13:16] [walkjoice]  desired amount: 200  |  top posts [disabled]: 9  |  possible posts: 11794611
INFO [2018-06-08 11:13:26] [walkjoice]  Session ended - 2018-06-08 11:13:26
INFO [2018-06-08 11:13:26] [walkjoice]  --------------------

Traceback (most recent call last):
  File "C:\Users\USER\Desktop\Insta Bot\InstaPy-master\InstaPy-master\quickstart.py", line 42, in <module>
    session.like_by_tags(['natgeo', 'newuzi', 'kanye'], amount=200)
  File "C:\Users\USER\Desktop\Insta Bot\InstaPy-master\InstaPy-master\instapy\instapy.py", line 1133, in like_by_tags
    skip_top_posts)
  File "C:\Users\USER\Desktop\Insta Bot\InstaPy-master\InstaPy-master\instapy\like_util.py", line 252, in get_links_for_tag
    "window.scrollTo(0, document.body.scrollHeight);")
  File "C:\Python27\lib\site-packages\selenium-2.53.6-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "C:\Python27\lib\site-packages\selenium-2.53.6-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium-2.53.6-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=67.0.3396.79)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.14393 x86_64)`
PLEASE HELP

**Comment by Essbuisness** [comment]
@uluQulu Please help

**Comment by Areahints** [comment]
I think an update will solve most of your problems. run `git status` in the `InstaPy folder`

**Comment by uluQulu** [comment]
Hi @Essbuisness 
Update your webdriver (_`chromedriver`_), web browser (_`Chrome`_) and `selenium`.

It will solve all of your problems.

**Comment by Essbuisness** [comment]
@uluQulu if i update selenium get this error message
`instapy requires selenium==2.53.0 `
and how do i update the chromedriver

**Comment by uluQulu** [comment]
@Essbuisness 
Have you downloaded from `pip`?

**Comment by uluQulu** [comment]
@Essbuisness 
I mean have you downloaded **InstaPy** itself using `pip`?

**Comment by Essbuisness** [comment]
@uluQulu my chrome browser is up to date

**Comment by Essbuisness** [comment]
@uluQulu no I installed instapy manually

**Comment by Essbuisness** [comment]
please how do i do that

**Comment by uluQulu** [comment]
Fine, @Essbuisness 
Running
```powershell
pip install -U selenium
```
will update `selenium` for you.

If you see this warning
```powershell
instagram-py 0.0.1 has requirement selenium==2.53.6, but you'll have selenium 3.12.0 which is incompatible.
```
just ignore it. It's cos `pip` configuration is not updated.

To download fresh new `chromedriver`, go to [this page](https://chromedriver.storage.googleapis.com/index.html?path=2.40/) and grab the correct package for your platform and then put it into your assets folder at InstaPy directory (_replace it with the old version in there_).

**Comment by Essbuisness** [comment]
this is now my current LOG
`[8444:4872:0609/191109.028:ERROR:install_util.cc(597)] Unable to read registry value HKLM\SOFTWARE\Policies\Google\Chrome\MachineLevelUserCloudPolicyEnrollmentToken for writing result=2

DevTools listening on ws://127.0.0.1:12339/devtools/browser/977f9635-1028-4720-95ec-e15a97775379
INFO [2018-06-09 19:11:20] [kelly_jnr1]  Session started - 2018-06-09 19:11:20
WARNING [2018-06-09 19:11:20] [kelly_jnr1]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO [2018-06-09 19:12:19] [kelly_jnr1]  Logged in successfully!
INFO [2018-06-09 19:12:34] [kelly_jnr1]  Tag [1/3]
INFO [2018-06-09 19:12:34] [kelly_jnr1]  --> natgeo
INFO [2018-06-09 19:12:49] [kelly_jnr1]  desired amount: 15  |  top posts [disabled]: 9  |  possible posts: 11812056
INFO [2018-06-09 19:13:00] [kelly_jnr1]  Session ended - 2018-06-09 19:13:00
INFO [2018-06-09 19:13:00] [kelly_jnr1]  --------------------


Traceback (most recent call last):
  File "C:\Users\USER\Desktop\Insta Bot\InstaPy-master\InstaPy-master\quickstart.py", line 38, in <module>
    session.like_by_tags(['natgeo', 'newuzi', 'kanye'], amount=15)
  File "C:\Users\USER\Desktop\Insta Bot\InstaPy-master\InstaPy-master\instapy\instapy.py", line 1148, in like_by_tags
    skip_top_posts)
  File "C:\Users\USER\Desktop\Insta Bot\InstaPy-master\InstaPy-master\instapy\like_util.py", line 252, in get_links_for_tag
    "window.scrollTo(0, document.body.scrollHeight);")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 629, in execute_script
    'args': converted_args})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=67.0.3396.79)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.14393 x86_64)`

**Comment by Essbuisness** [comment]
@uluQulu i updated selenium and chromuim driver

**Comment by uluQulu** [comment]
@Essbuisness 
The last LOG's last lines says your chromdriver is still using old version- `2.34`
```powershell
(Session info: chrome=67.0.3396.79)
(Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.14393 x86_64)`
```

Have you applied everything correctly?

**Comment by Spizzy15** [comment]
I found this problem, I do not know how to solve it
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/Users/Ludo/Desktop/InstaPy-master/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/Users/Ludo/Desktop/InstaPy-master/instapy/instapy.py", line 13, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'

**Comment by uluQulu** [comment]
@Spizzy15 
Install that module named `pyvirtualdisplay`.
```powershell
pip install pyvirtualdisplay
```

**Comment by Spizzy15** [comment]
yep, i solved it on my mac, but now on my rb

File "quickstart.py", line 22, in <module>
    multi_logs=False)
  File "/home/pi/Desktop/InstaPy/instapy/instapy.py", line 174, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Desktop/InstaPy/instapy/instapy.py", line 285, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by Essbuisness** [comment]
@uluQulu 
Hi i downloaded from the link
and replaced with the old chrome driver
in the asset folder
but it still says 

(Session info: chrome=67.0.3396.79)
(Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.14393 x86_64)

**Comment by Essbuisness** [comment]
DevTools listening on ws://127.0.0.1:12368/devtools/browser/b7442491-1217-4d33-9036-18737f66bb8e
INFO [2018-06-13 01:29:19] [kelly_jnr1]  Session started - 2018-06-13 01:29:19
WARNING [2018-06-13 01:29:19] [kelly_jnr1]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
[2636:7432:0613/012943.918:ERROR:shader_disk_cache.cc(237)] Failed to create shader cache entry: -2
                     INFO [2018-06-13 01:31:22] [kelly_jnr1]  Logged in successfully!
INFO [2018-06-13 01:31:42] [kelly_jnr1]  Tag [1/3]
INFO [2018-06-13 01:31:42] [kelly_jnr1]  --> natgeo
INFO [2018-06-13 01:33:25] [kelly_jnr1]  desired amount: 15  |  top posts [disabled]: 9  |  possible posts: 11853273
INFO [2018-06-13 01:33:37] [kelly_jnr1]  Session ended - 2018-06-13 01:33:37
INFO [2018-06-13 01:33:37] [kelly_jnr1]  --------------------


Traceback (most recent call last):
  File "C:\Users\USER\Desktop\Insta Bot\InstaPy-master\InstaPy-master\quickstart.py", line 38, in <module>
    session.like_by_tags(['natgeo', 'newuzi', 'kanye'], amount=15)
  File "C:\Users\USER\Desktop\Insta Bot\InstaPy-master\InstaPy-master\instapy\instapy.py", line 1148, in like_by_tags
    skip_top_posts)
  File "C:\Users\USER\Desktop\Insta Bot\InstaPy-master\InstaPy-master\instapy\like_util.py", line 252, in get_links_for_tag
    "window.scrollTo(0, document.body.scrollHeight);")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 629, in execute_script
    'args': converted_args})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=67.0.3396.79)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.14393 x86_64)

**Comment by Essbuisness** [comment]
@uluQulu i just deleted the old source file and downloaded it afresh
it seems to be working no
though i have only tried the like feature

**Comment by Essbuisness** [comment]
who has an idea how i can run this on a server

**Comment by Essbuisness** [comment]
@uluQulu updating the source file actually helped thanks for your help
appreciate it

**Comment by uluQulu** [comment]
Glad that helped, @Essbuisness.
