### ISSUE TITLE
Like a specific post

### ISSUE THREAD

**Issue by ceribbo** [InstaPy/InstaPy#2207]
I think there is a pretty simple solution but how to like a single image?
I have the url of an image, i initialise the session and them?
how can i just like a single post?
thanks

**Comment by uluQulu** [comment]
Hi @ceribbo 
There is a feature `like_from_image` which can get the tags from a given image URL and do like by tags.
But if you like to like the image at a given URL itself, you have to write a new feature.

**Comment by uluQulu** [comment]
Just wrote a fresh new feature to do that, @ceribbo.
```python
interact_by_URL(urls=[], media=None, interact=False)
```

You can provide URLs in these styles
+ **full**: `"https://www.instagram.com/p/Bj0J4bJgY7r/?taken-at=628416221"`
+ **or**: `"https://www.instagram.com/p/Bj0J4bJgY7r/"`
+ **or**: `"Bj0J4bJgY7r/?taken-at=628416221"`
+ **or** just image code: `"Bj0J4bJgY7r"`

Get it https://gist.github.com/uluQulu/e1065fe51a92c81454481d42ec8017ce.
>Adding that new method to InstaPy class will be sufficient.

**Comment by ceribbo** [comment]
Hey @uluQulu I'm so sorry for the late answer.
Actually I've seen it only now.
By the way that's exactly was i was searching for!! 
thank you very much!!

**Comment by rsabir** [comment]
@uluQulu How can we use the script?

**Comment by uluQulu** [comment]
Which script, @rsabir?

**Comment by rsabir** [comment]
I mean how can I use the interact_by_url?
