### ISSUE TITLE
Not unfollowing users that have followed me?

### ISSUE THREAD

**Issue by rollbahn** [InstaPy/InstaPy#221]
Is there any way to not unfollow users that have followed me. It seems the script just unfollows everyone?

**Comment by timgrossmann** [comment]
@rollbahn right now there isn't... You could add every single one of them to `don't_include` list, but at the moment, this is the only way...

**Comment by rollbahn** [comment]
Ok thanks that's a bummer. I don't think manually adding them to a list is going to be scalable for me at this stage. Hopefully this functionality comes at some point as the rest of everything works well.

**Comment by mblodorn** [comment]
If we find a way to fetch all followers this can be easily done with some sort of "contains" method. The only problem is how to deal with a large number of followers. Next weekend i'll check this.
