### ISSUE TITLE
chromedriver not detected at execution

### ISSUE THREAD

**Issue by epokheio** [InstaPy/InstaPy#2215]
I'm on ubuntu/AWS, despite having properly installed chromedriver following the "How to run InstaPy on a digital ocean Ubuntu droplet" documentation I get the following error message when I want to execute instapy:

`instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/ubuntu/InstaPy/assets/chromedriver`

**Comment by Doom666** [comment]
in your script, be sure that your session settings are correct:
by default is:
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)
For Digital Ocean and AWS:
change Headlesbrowser to True, and ad nogui:True
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True,
                 nogui=True)

**Comment by Marow** [comment]
I have the same error, that doesnt helped for me :/

**Comment by Doom666** [comment]
I see,  then I don't know, I had started with a new installation and run into the same issue and this solved, I don't really know much more....

**Comment by epokheio** [comment]
It worked for me! Thanks a lot.

**Comment by kushpvo** [comment]
Didn't work for me.

**Comment by fernaoguerra** [comment]
I was having the same problem and the problem was that I did not have chrome installed on my new machine. In order to chromedriver to work you must have chrome installed on your server/machine.

Besides that, just change headless_browser=False to headless_browser=True on the quickstart.py file and run it. It should work.
