### ISSUE TITLE
Avoid re-following users I have just unfollowed?

### ISSUE THREAD

**Issue by rollbahn** [InstaPy/InstaPy#222]
Is it possible to avoid re-following users I have just unfollowed - the unfollows don't appear to be logged anywhere?

**Comment by timgrossmann** [comment]
@rollbahn Yes it is.
just use `.set_do_follow(enabled=True, percentage=10, times=1)`, where `times` is the number of times, you want to follow a person (and unfollow again using `.unfollow()`)

**Comment by rollbahn** [comment]
Thanks - I noticed that in the documentation but I couldn't see how it worked. I tested by unfollowing a few people from my account but I couldn't see anywhere where those user id/names were stored in a file for the script to be able to refer to them when following users later?

**Comment by fbessigu** [comment]
Hey te liking by # works well but i can't find out how to set the follow unfollow things my quick start look like this 
dont_like = ['nude', 'girl', 'hot',]
ignore_words = ['pizza']
friend_list = ['friend1', 'friend2', 'friend3']


# If you want to enter your Instagram Credentials directly just enter
# username=<your-username-here> and password=<your-password> into InstaPy
# e.g like so InstaPy(username="instagram", password="test1234")

InstaPy(username="****", password="********")\
  .login()\
  .set_upper_follower_count(limit = 2000) \
  .set_do_comment(True, percentage=12) \
  .set_comments([':)!', '<3 <3!',]) \
  .set_dont_include(friend_list) \
  .set_dont_like(dont_like) \
  .set_ignore_if_contains(ignore_words) \
  .like_by_tags(['veggies','vegan','nature','landscape','healthyfood'], amount=100) \
  .set_do_follow(enabled=True, percentage=100, times=1) \
  .set_unfollow(True, percentage=10, times=1) \
  .end()
i've set the percentage to 100 to try it out but still dosent work 
i have no idea what i messed up 
thanks

**Comment by timgrossmann** [comment]
@rollbahn They are stored in a JSON file in the logs folder.
