### ISSUE TITLE
Unable to find element exception (looks like another one this time)

### ISSUE THREAD

**Issue by ArdySan2012** [InstaPy/InstaPy#2220]
Gentlemen - any ideas?
![exception](https://user-images.githubusercontent.com/31565232/41254919-d8c60bd2-6dbc-11e8-80ef-e69811a8ed40.jpg)

**Comment by ArdySan2012** [comment]
It is indeed a weird Instagram behaviour in chrome...  As in https://github.com/timgrossmann/InstaPy/issues/2219
if I manually click on followers - just the user page gets refreshed

**Comment by AdamMoffitt** [comment]
I get the same error :/ haven't been able to resove it

**Comment by uluQulu** [comment]
This is the result of the latest changes in page design, also, for **unfollow** feature, it only affected the `onlyNotFollowMe=False` and `onlyInstapyFollowed=False` condition where it unfollows every user you are following.

The new PR I will do is gonna fix it, read more at #2222.

**Comment by gregkopp** [comment]
Seems that IG has fixed it's code. I can now click on followers in any browser.

**Comment by uluQulu** [comment]
Hey @gregkopp 
Thanks for this fantastic news!
