### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/following-sibling::div"}

### ISSUE THREAD

**Issue by LoneWolfsMoon** [InstaPy/InstaPy#2224]
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/following-sibling::div"}

![ss2](https://user-images.githubusercontent.com/30674228/41288229-e5d4320c-6e45-11e8-90a4-79cd2d3aea80.png)

**Comment by Mehran** [comment]
same as me on Ubuntu 18 fresh install every thing but not work .

**Comment by samihamine** [comment]
@uluQulu Any idea how to get around this problem in the desktop version ?

**Comment by Diddy512** [comment]
Same for me on CentOS
edit: Issue already opened for this error

**Comment by Mehran** [comment]
as @torbenberger mention  add below on `instapy.py ` on line `262 `

```
mobile_emulation = {"deviceName": "Nexus 5"}
chrome_options.add_experimental_option("mobileEmulation", mobile_emulation)
```

**Comment by LoneWolfsMoon** [comment]
Thanks @Mehran !!!!!!!!!!! <3
as @torbenberger mention add below on instapy.py on line 262

/InstaPy/instapy/instapy.py

`mobile_emulation = {"deviceName": "Nexus 5"}
chrome_options.add_experimental_option("mobileEmulation", mobile_emulation)`

![fix1](https://user-images.githubusercontent.com/30674228/41295106-fd6e6810-6e59-11e8-9d2b-74ae784ee546.png)

**Comment by LoneWolfsMoon** [comment]
Yes but now it says:
`
Failed to load desired amount of users
`
..

**Comment by olirock** [comment]
The same with me..

**Comment by uluQulu** [comment]
Hi guys
@SammyHam I have prepared a general solution. Please follow the most active thread for it- #2222
I will share the solution in there, and soon include a PR myself.

**Comment by botpadawan** [comment]
Just remove set_relationship_bounds, it worked for me

**Comment by HCWcoder** [comment]
I did not know that its available to bot act as a mobile !

is it safer to use ?
