### ISSUE TITLE
Follow by tag

### ISSUE THREAD

**Issue by cormo1990** [InstaPy/InstaPy#2225]
Hello, is it possible introduce a sleep delay time (for example after followed 10 user) in that action?
at the moment I can't set this option

thanks to everybody

@uluQulu Your help will be so appreciated 🥇

**Comment by uluQulu** [comment]
Hi @cormo1990 
It is very easy, I will have a look at it when gets a free time.

**Comment by bgunsberger** [comment]
+1.
