### ISSUE TITLE
unfollow all users and remove on database also if it exist

### ISSUE THREAD

**Issue by Mehran** [InstaPy/InstaPy#2226]
`session.unfollow_users(amount=250, onlyInstapyFollowed = False, sleep_delay=600)`

Please add this feature when bot unfollow all users if it exist on database remove it also .

**Comment by uluQulu** [comment]
@Mehran 
It already exists it just doesn't have a parameter.
Give `onlyInstaPyFollowed=False` and `onlyNotFollowMe=False`, it will unfollow all of the users you are following.

I made it a new parameter and added all of the support as in other methods to it, will COME in my new PR.

**Comment by Mehran** [comment]
@uluQulu you mean These parameter `onlyInstaPyFollowed=False and onlyNotFollowMe=False` remove username from follower in CSV file ?

**Comment by uluQulu** [comment]
@Mehran 
They must remove, but I can't be sure, needs to check current Instapy files.
My files has the latest modifications from my new implementation and in mine I added all of the missing activities to it.

But you don't worry it, soon I will PR new tools which will include all of the changes you are thinking of.
>If you wanna check it, open up **unfollow_util.py** file and see if it has `delete_line_from_file` call in all of the three available conditions which removes _usernames with timestamps of record_ from its CSV
