### ISSUE TITLE
follow unfollow does not  work ?

### ISSUE THREAD

**Issue by 404Fel** [InstaPy/InstaPy#223]
Hey the liking by # works well but i can't find out how to set the follow unfollow things my quick start look like this
dont_like = ['nude', 'girl', 'hot',]
ignore_words = ['pizza']
friend_list = ['friend1', 'friend2', 'friend3']

If you want to enter your Instagram Credentials directly just enter
username= and password= into InstaPy
e.g like so InstaPy(username="instagram", password="test1234")

InstaPy(username="****", password="********")
.login()
.set_upper_follower_count(limit = 2000) 
.set_do_comment(True, percentage=12) 
.set_comments([':)!', '<3 <3!',]) 
.set_dont_include(friend_list) 
.set_dont_like(dont_like) 
.set_ignore_if_contains(ignore_words) 
.like_by_tags(['veggies','vegan','nature','landscape','healthyfood'], amount=100) 
.set_do_follow(enabled=True, percentage=100, times=1) 
.set_unfollow(True, percentage=10, times=1) 
.end()
i've set the percentage to 100 to try it out but still dosent work
i have no idea what im missing
thanks

**Comment by tibor** [comment]
Can you describe further what isn’t working? E. g. do you get an error message, is the whole script not working or is just the part of following not working?

However, for `.set_unfollow` you have to use `amount` instead of `percentage`

You should also use a backslash at the end of all lines from `.login` to `.set_unfollow`

**Comment by 404Fel** [comment]
well the the whole follow and unfollow part don't work and 
i have a backslash at the end of each lines it on the actual script 
i'm getting an error message at the end of my script execution 
there it is 
"Liked: 0
Already Liked: 0
Inappropriate: 3
Commented: 0
Followed: 0
Traceback (most recent call last):
  File "quickstart.py", line 24, in <module>
    .set_do_follow(enabled=True, percentage=100, times=1) \
AttributeError: InstaPy instance has no attribute 'set_unfollow'"
thanks for the support

**Comment by tibor** [comment]
You have to use `.unfollow_users` instead of `.set_unfollow`

**Comment by timgrossmann** [comment]
@404Fel Please read the documentation...
A quick side not: methods that actually do something, e.g. liking or unfollowing don't have a `.set` in front of the method name
