### ISSUE TITLE
Issue with unfollow

### ISSUE THREAD

**Issue by HCWcoder** [InstaPy/InstaPy#2230]
**Please instapy followed to many but couldnt unfollow them ?

can someone give me a good  InstaPy configuration ?

thanks.**

## Current Behavior
INFO [2018-06-12 20:41:45] []  --> unfollow_users, amount: 20
INFO [2018-06-12 20:41:45] []  Number of users available to unfollow: 53
WARNING [2018-06-12 20:42:11] []  There are 0 people to unfollow
ERROR [2018-06-12 20:43:04] []  --> Unfollow error with b'barbararibo', maybe no longer exists...
ERROR [2018-06-12 20:43:04] []  unfollow loop error local variable 'follow_button' referenced before assignment
## InstaPy configuration

def job():
    try:

        #create instance
        session = InstaPy(username=insta_username, password=insta_password,
                          headless_browser=True, bypass_suspicious_attempt=True)
        session.login()
        # use smart hashtags
        #session.set_smart_hashtags(taglist, limit=3, sort='top', log_tags=True)

        #limits
        session.set_relationship_bounds(enabled=True,
            				 potency_ratio=-1.21,
            				  delimit_by_numbers=True,
            				   max_followers=4590,
            				    max_following=5555,
            				     min_followers=45,
            				      min_following=77)
        session.set_do_comment(enabled=True, percentage=40)
        session.set_comments(['Great shot', 'Amazing','Fantastic!!', 'wow','nice post!','keep up the hard work!','Excellent!'])
        session.set_dont_include(['friend1', 'friend2', 'friend3'])
        session.set_dont_like(['polishboy', 'boobs', 'tits'])
        session.set_do_follow(enabled=True, percentage=30, times=1)

        session.like_by_tags(
                ['fashion', 'stylish', 'blog', 'outfitoftheday'], amount=3, media='Photo')

        # unfollow
        session.unfollow_users(amount=20, onlyInstapyFollowed=True, onlyInstapyMethod='FIFO', sleep_delay=60)

        print("do the actual liking by feed")
        #session.like_by_feed(amount=15)

		# unfollow
        session.unfollow_users(amount=20, onlyInstapyFollowed=True, onlyInstapyMethod='FIFO', sleep_delay=60)
                

        # unfollow
        session.unfollow_users(amount=20, onlyInstapyFollowed=True, onlyInstapyMethod='FIFO', sleep_delay=60)

        # end the bot session
        session.end()
    except KeyboardInterrupt:
        session.end()
    except WebDriverException:
  # do something or skip ->
        pass
    except:
        import traceback
        print(traceback.format_exc())

job()
schedule.every().day.at("16:44").do(job)
schedule.every().day.at("17:00").do(job)
schedule.every().day.at("18:00").do(job)
schedule.every().day.at("19:00").do(job)
schedule.every().day.at("20:00").do(job)
schedule.every().day.at("21:00").do(job)
schedule.every().day.at("22:00").do(job)
schedule.every().day.at("23:00").do(job)

while True:
    schedule.run_pending()
    time.sleep(1)

**Comment by Marow** [comment]
Wait some hours... instagram has issues

**Comment by uluQulu** [comment]
Hi guys
I'm gonna share a new work which also touch unfollow feature, it will improve some situations, check new PRs soon.
