### ISSUE TITLE
An easy way not to follow Private accounts?

### ISSUE THREAD

**Issue by ArdySan2012** [InstaPy/InstaPy#2233]
I do remember that was a default at some point (user is private, skipping). But not anymore, and follow requests are piling like crazy...
Any way for a rookie to make script ignore/skip private accounts?
Thank you :)

**Comment by marcomokastyle** [comment]
/instapy/util.py
add 
def is_private_user(browser, username):
    link = 'https://www.instagram.com/'+username+'/'
    web_adress_navigator(browser, link)
    try:
        isPrivate = browser.execute_script(
            "return window._sharedData.entry_data."
            "ProfilePage[0].graphql.user.is_private")
    except WebDriverException:   #handle the possible `entry_data` error
        try:
            browser.execute_script("location.reload()")
            isPrivate = browser.execute_script(
                "return window._sharedData.entry_data."
                "ProfilePage[0].graphql.user.is_private")
        except WebDriverException:
            isPrivate = None
    return isPrivate

/instapy/util.py after (validate_username)
    if username in blacklist:
        return False, \
                "---> {} is in blacklist  ~skipping user\n".format(username)

add
    if is_private_user(browser, username):
          return False, \
              "---> {} is private ~skipping user\n".format(username)

**Comment by ljacobo** [comment]
is this tested?

Thx

**Comment by marcomokastyle** [comment]
Yes, is what I'm using in my InstaPy. And it's working.

**Comment by ljacobo** [comment]
Perfect.

Thnks

**Comment by ljacobo** [comment]
Hi Marco,

I did every change you said but is still requesting follow to private accounts, can you attach a copy of your util.py file? to compare with mine.

thks.

**Comment by marcomokastyle** [comment]
[instapy.txt](https://github.com/timgrossmann/InstaPy/files/2099604/instapy.txt)
[util.txt](https://github.com/timgrossmann/InstaPy/files/2099605/util.txt)

**Comment by marcomokastyle** [comment]
I added some functions that i needed, as skip private profile, skip users with less posts than a specific number, and (not tested yet) skip user without a profile pic.

session.set_skip_users(skip_private=True, skip_no_profile_pic=True, min_media=25)

I'm a beginner in Python, so, if someone want improve or correct me, is nice :)

**Comment by ArdySan2012** [comment]
Thank you @marcomokastyle ! Trying it now - works so far (needs lots of changes to instapy.py as well - so just used your version)

**Comment by ljacobo** [comment]
Thanks @marcomokastyle.!!

**Comment by ljacobo** [comment]
Working perfect @marcomokastyle, @timgrossmann this should be added in a PR. Really helpful..!

**Comment by marcomokastyle** [comment]
Glad that I was helpful :) if someone, want improve my version, i'm glad too. 
P.S. this is my first week I use Python, always used Java :P

**Comment by marcomokastyle** [comment]
Just a little correction, i forgot to change <= to <, if you set min_media=25 in my previous version,if the user has 25 posts is skipped, because is equal to 25.
[util.txt](https://github.com/timgrossmann/InstaPy/files/2100135/util.txt)

**Comment by marcomokastyle** [comment]
Forgot to comment here, I added in PR #2242

**Comment by ljacobo** [comment]
Nice.

@marcomokastyle have you notice that when you use skip_private and you have set to interact with user follower or follow likers, if the amount per user is 4 and if the first user of the first picked users is private, you missed the interaction with the followers or likers of that account?

Seeing this in code:

def job():
	try:
            session = InstaPy(username=insta_username, 
                              password=insta_password, 
                              headless_browser=False, 
                              use_firefox=True,
                              multi_logs=True)
            session.login()

            #Settings
            session.set_skip_users(**skip_private=True**, skip_no_profile_pic=True, min_media=10)
            session.set_relationship_bounds(enabled=True,
                                            potency_ratio=None,
                                            delimit_by_numbers=True,
                                            max_followers=5000,
                                            max_following=7000,
                                            min_followers=10,
                                            min_following=10)

            session.set_do_like(enabled=True, percentage=100)
            session.set_user_interact(amount=1, randomize=True, percentage=100, media='Photo')
            
            #Actions
            session.follow_likers(['influencer1', 
                                                 'influencer2', 
                                                 'influencer3', 
                                                 'influencer4'], photos_grab_amount=1, follow_likers_per_photo=5, randomize=True, sleep_delay=200, interact=True)
        finally:
            session.end()


If the firsts 5 users picked from the post of influencer1 are private, the bot continues interacting with the influencer2, but you have 0 interaction with the influencer1. So, there is a way to increment the amount of interactions based if the selected user is private? 

I am point this out because if you want to have a specific amount of interaction per hour (20 likes, 20 follows, etc), taking care of the Instagram limits, of course, without this setting, you will be missing interactions.

Thks.!

**Comment by marcomokastyle** [comment]
One possible solution could be, filter from the list of picked users all the private accounts, so you will interact only with public users, I'll try to implement it later.

**Comment by sionking** [comment]
graphql might have a bug, not failing on " #handle the possible entry_data error" but jsut taking previous person checked (if we jump from profile to profile) so the returned is_private might be incorrect.

**Comment by ArdySan2012** [comment]
Sorry for newbie remark. If using @marcomokastyle util.py - private users are dealt with perfectly. But the old error surfaces again - applying the fix from here helped https://github.com/timgrossmann/InstaPy/issues/2131  (I think it had old Xpathes)

**Comment by ArdySan2012** [comment]
Hey @marcomokastyle !   Are you still alive?  (I hope so).

Would you mind making a PR just for the private user skipping? Or writing up a bit more how do you do that (just adding lines from the first post don't cut it). And the main version has changed so much, that we can't use your files anymore (those attached above).

Thanks!!

**Comment by Areahints** [comment]
I'm looking for a solution for this also! +1

**Comment by marcomokastyle** [comment]
@ArdySan2012 Sorry, I was quite busy, as soon as I can I update the PL.

**Comment by joanroig** [comment]
We need this on a PR, trying to interact with private users is such a pain, and the bot loses a lot of time :( @marcomokastyle

**Comment by marcomokastyle** [comment]
@joanroig I'm working on this with @uluQulu  and is almost finished.

**Comment by joanroig** [comment]
@marcomokastyle @uluQulu I really appreciate this

**Comment by greggjaskiewicz** [comment]
could you guys actually push a PR for this?

**Comment by greggjaskiewicz** [comment]
how isn't this merged yet?
