### ISSUE TITLE
Problem with follow_user_followers function

### ISSUE THREAD

**Issue by olirock** [InstaPy/InstaPy#2236]
I have been using the program for about 1 month and have always used the same function as follow_user_followers. Since two days ago, I started having problems with this function. When I define the function, it opens the users profile and says simulate the follow-up. And before she did not enter the profiles, she just rolled the page and followed one by one. Would you like to return to this version of the function, does anyone help?

![image](https://user-images.githubusercontent.com/13512611/41367747-50690180-6f16-11e8-8129-f5aa39a8a3fd.png)

![image](https://user-images.githubusercontent.com/13512611/41367761-5b00b084-6f16-11e8-9fe8-725cbc4228e3.png)

![image](https://user-images.githubusercontent.com/13512611/41367790-71dadd5c-6f16-11e8-8099-e2fc71c57fd5.png)

My problem is that: The actually function open the profile for follow...

![image](https://user-images.githubusercontent.com/13512611/41368536-9c778a2c-6f18-11e8-99f2-71080bfd7ff9.png)

**Comment by uluQulu** [comment]
Hi @raphagk7 
I see that you have utterly minimal setup.

It's fine but look at the features InstaPy offers, try to use them to improve efficiency!

More than that, previously `follow_user_followers` feature could not verify users through relationship bounds and also couldn't do on-the-go interactions and it's sleep delay was per user.

Now all of them and some more is solved with new design.

The simulated follows are to provide a healthy activity flow and I will look again to it's algorithm to write more smarter conditions to decrease the simulation amount someday.

Also if you do not want to use relationship bounds verification, just disable it by adding `set_relationship_bounds(enabled=False)` to your quickstart script.

Regards
