### ISSUE TITLE
Correction in clarifai_util.py

### ISSUE THREAD

**Issue by marcomokastyle** [InstaPy/InstaPy#2241]
I changed the part of the code to retrieve the image url, using graphql.shortcode_media.display_url
[clarifai_util.txt](https://github.com/timgrossmann/InstaPy/files/2099998/clarifai_util.txt)

**Comment by botboteverywhere** [comment]
Hey @marcomokastyle, seems you fixed my long time problem regarding how the bot fetched the image's url for Clarifai. Thanks so much! Contextualizing commenting is everything with InstaPy :pray:

**Comment by CharlesCCC** [comment]
@marcomokastyle great work, Can you please PR(Pull Request) that, so everybody else can benefit from your contribution. thank you.

**Comment by marcomokastyle** [comment]
Is already in PR with also some new features, see #2242

**Comment by ghost** [comment]
can we separate this as the other PR seems to be stuck or getting too big? @marcomokastyle

**Comment by marcomokastyle** [comment]
Done, PR #2260
