### ISSUE TITLE
interact_user_followers is following users even if its not enabled

### ISSUE THREAD

**Issue by Pormientras** [InstaPy/InstaPy#2244]
Hey there! This is part of my quickstart.-

session.set_user_interact(amount=3, randomize=True, percentage=50, media='Photo')
session.set_do_follow(enabled=False, percentage=35)
session.set_do_like(enabled=True, percentage=90)
session.set_do_comment(enabled=False, percentage=80)
session.interact_user_followers(['somepage'], amount=500, randomize=True)

I have been using InstaPy for a while now, and always used it to follow and like but now that I only want to Like the images from this followers the program still follows them, this message appears.-

INFO [2018-06-13 20:32:24] [myuser]  Simulated follow : 1
INFO [2018-06-13 20:32:25] [myuser]  --> Followed b'someuser'
INFO [2018-06-13 20:32:24] [myuser]  Simulated follow : 2
INFO [2018-06-13 20:32:25] [myuser]  --> Followed b'someuser'
And so on...

I suppose this is a bug or am I doing something wrong? 
Thank you in advance, you are all a great community.

**Comment by sionking** [comment]
Seems like a bug.

**Comment by uluQulu** [comment]
Comon @sionking you know it is not a bug 😁

@Pormientras it is gonna follow only while getting the usernames from a dialog box and that amount of simulated follows is so less.

Well, I admit, the algorithm of simulations is not so good right now, that's why it can look a bit confusing for now but simulation is needed for a healthy activity flow and I will try to revise that mechanism soon.

Also, simulations will happen regardless of you have enabled following or not. It's a health factor and is a safety belt for your account.

Also keep in mind that if a user followed by simulation is not valid according to your settings (_e.g. relationship bounds_) it will be unfollowed soon after gets required data from the dialog.

Regards

**Comment by sionking** [comment]
@uluQulu 
Ok, not a bug. I know that you think the simulation is important, I do also.
I also know you thought of this simulation not checking this parameter, as it might not be that important to **you**. 
But there are some ppl that manage some account who don't want to do any follow-unfollow procedure.
This is why I think the simulation need to respect those configuration.
And please don't remove it.

**Comment by uluQulu** [comment]
Heh @sionking 
I have to say that you are right. There are many people thinking and doing like that.
But I still think that simulation have to happen in any activity of that kind.

But again it is a topic of a big discussion, let me open my new PR and say some fresh words out of new paradigms coming with new tool sets, then, you will understand much better.
>Well by the way those words will be opposite of simulation which is sad.

Regards

**Comment by spikeyhair** [comment]
I fully understood where the idea of simulation following came from but can we have an option to enable or disable it? Be it healthy or not, will IG ban the account or not, I guess it's up to the individual user to take the risk and you can put this warning in the readme (user manual). Thanks for the thought of putting this feature in.

**Comment by uluQulu** [comment]
Hey @spikeyhair 
It is a must have activity.  
Saying again - the algorithm which is triggering it is so basic and I WROTE it as I thought and the reason I say this is- now, it can do more simulations more than enough which can look unwanted.  
I hope it will be improved by some (_or by me if gets some free time_).

For you and others, there is a good news:
With the latest implementation of **relationship tools**, there comes a new class-wide variable- `self.simulation`.

If you want to disable it easily, just give it the value of False in the **instapy.py** file.
```python
self.simulation = False
```

Also, cos of it is a must have activity, it must be just set, so I don't see a point to make it optional and add a documentation for it (_yes well, I think the future of it: with an improved algorithm_).

Cheers

**Comment by timgrossmann** [comment]
@uluQulu Could you add a short comment somewhere appropriate in the README file so people find that note if they encounter this "issue" here, please?
Thank you

P.S. love the simulated follows 😉

**Comment by uluQulu** [comment]
hmm, @timgrossmann 
I really wish it had a wiser algorithm.
And to be honest, most of the users will always wonder what a simulated follow is.
Or in all other simulation happened cos the scope of the idea is big- to add it to all of the required places, e.g. scrolling to get data, unfollowing from a dialog box.
Those places must also have supported smartly with simulations.

At this point, it is good to add that information and I think to add a new section for it and other similar information.
Sth like:
+ Feature:
some features
+ Relationship tools:
some tools
+ Extras:
Simulations
etc.

does it sound good?

UPDATE:
I see that **Extra information** section already exist. Is it a good spot for that?

**Comment by timgrossmann** [comment]
@uluQulu Thank you very much for pointing out possible places to mention this.

I think the **Extra Information** section is a good place for it to quickly describe the reason it ist there. However it might be best to also link it at some other points in the documentation with the most frequently used features (and the ones that are initially used in the quickstart) so most people will see it.

**Comment by uluQulu** [comment]
Okay @timgrossmann I'll do that.

**Comment by davisonio** [comment]
Any update on this? This just really confused me and I don't get how it works.

**Comment by timojaask** [comment]
It's in the readme now -- you can disable or reduce the simulated follows. Read it here: https://github.com/timgrossmann/InstaPy#simulation

This issue can probably be closed now @uluQulu
