### ISSUE TITLE
Create specific logs for each InstaPy file

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#225]
When you have multiple quickstart files (e. g. different topics for the same account or different accounts), stats and log files like `followRestriction` will likely be overwritten or mashed up.

I guess we should generate those files specific for each session / quickstart file or dependend on the account name (for example, using the account name as a suffix).

Currently in progress #228

**Comment by TheRealJAG** [comment]
I noticed when the scripts complete they output some data. # of likes, follows, etc. How about a running log file that stores this data?

**Comment by gitpatrickhub** [comment]
It would be great to log more info to perform additional analysis. At a minimum it would be great to log number of actions per tag (likes, comments, follows). Currently it logs a summary of all tags.

**Comment by brunomiguelleal** [comment]
Not sure if you're still waiting for a kind of solution to this, but what I did was having separate InstaPy folders for each of the running scripts.
