### ISSUE TITLE
With Enable notification pop-up on feed application is stuck on : "Total of links feched for analysis: 1"

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2250]
Need to check first no pop up exist, or to never start with like by feed.

**Comment by sionking** [comment]
Running for 2 hours !!! stuck on this confirmation, PR soon.

![image](https://user-images.githubusercontent.com/7851877/41510824-e26e4760-7273-11e8-9747-2518862d456a.png)


WARNING [2018-06-17 17:57:35] [xx]  Post Randomly Skipped...
INFO [2018-06-17 **16:08**:17] [xx]  Total of links feched for analysis: 1
INFO [2018-06-17 **17:59**:27] [xx]  Total of links feched for analysis: 1
INFO [2018-06-17 17:59:27] [xx]  ~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ghost** [comment]
same here

**Comment by ghost** [comment]
@sionking  can you please attach the page_source of this instagram page so i can intercept the button "Not Now" and make a pr.

Thanks

**Comment by lerra** [comment]
@ilmetu  Here you go!

![image](https://user-images.githubusercontent.com/18061206/42410673-a7c47222-81ed-11e8-802f-be2dd7435127.png)

**Comment by lerra** [comment]
@ilmetu have you had time to look at it?

**Comment by ghost** [comment]
Hi @lerra yes i solved already a lot time ago but i didn't commit to the master ...

ok i will make a PR soon

bye
