### ISSUE TITLE
Interaction and like in follower images

### ISSUE THREAD

**Issue by zsvendo** [InstaPy/InstaPy#2251]
@uluQulu 
I did not understand how the part of like works in the pictures.
I'll cite one example, I want to give like in all followers of my competitor who has 1M followers.

I do like this:
session.interact_user_followers (['guild'], amount = 1000, randomize = False)
session.set_user_interact (amount = 1, randomize = False, percentage = 100, media = None)

Each time he runs he searches for 700 or 600 users but he does not search for the last user who liked the photo?

**Comment by uluQulu** [comment]
Hey @zsvendo 
I think I failed to understand your problem.

But the configuration you have posted clearly says about the problem:
+ always start settings before actions,, so it should be like this
```python
session.set_user_interact (amount = 1, randomize = False, percentage = 100, media = None)
session.interact_user_followers (['guild'], amount = 1000, randomize = False)
```

Also, you have not initiated like, comment, follow settings for the interactions.
Apply all of the corrections and see if you get the expected result.

Regards

**Comment by sionking** [comment]
@uluQulu You should get paid for costumers support.
