### ISSUE TITLE
Quickstart Error

### ISSUE THREAD

**Issue by olirock** [InstaPy/InstaPy#2255]
![image](https://user-images.githubusercontent.com/13512611/41482473-220043fc-70ac-11e8-947e-3625a89ce89b.png)
Can anyone tell me what's going on?

**Comment by uluQulu** [comment]
Hi @raphagk7 
Have a read https://github.com/timgrossmann/InstaPy/pull/2086#issuecomment-394117784 to solve it.

Regards
