### ISSUE TITLE
SYNTAX ERROR in quickstart.py

### ISSUE THREAD

**Issue by AlanInsam** [InstaPy/InstaPy#2256]
I wanted to set up the bot, but when I edit the bot with follow, like.. instructions this error appears:
 File "quickstart.py", line 47
    session.unfollow_users(amount=12, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60)
                                                                                                            ^
IndentationError: unindent does not match any outer indentation level

**Comment by uluQulu** [comment]
@AlanInsam 
There is a wrong indentation in that **quickstart** script.  
Find and fix it.
If you can't find it, attach that file in a zip (_without personal information_) to help you get it work.

**Comment by michaelBielang** [comment]
https://stackoverflow.com/a/39531488/8006882
