### ISSUE TITLE
Question? Insufficient amount of links

### ISSUE THREAD

**Issue by titanas159** [InstaPy/InstaPy#2258]
Insufficient amount of links ~ trying again: 1
Insufficient amount of links ~ trying again: 2
nsufficient amount of links ~ trying again: 3
Cor! Did you send too many requests? ~ let's rest some

I run the code, and it did nothing and already getting rest. After some time it work properly fine, i just wonder what cause this to stop working?
And it's every time writing the same thing (Insufficient amount of links ~ trying again: 1) after starting new tag.

The thing is i want that program work more like human, and don't do any unnecessary actions.
P.s. I am not a programmer and new to python, just trying to understand stuff.

**Comment by dimahadgi** [comment]
Have same issue last time:

```
..............................................................
INFO [2018-06-25 15:07:46] [dkhadzhy]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-06-25 15:07:49] [dkhadzhy]  Location [1/1]
INFO [2018-06-25 15:07:49] [dkhadzhy]  --> b'225219858/dnipropetrovsk-ukraine/'
INFO [2018-06-25 15:07:58] [dkhadzhy]  desired amount: 2000  |  top posts [disabled]: 9  |  possible posts: 2074771
INFO [2018-06-25 15:08:11] [dkhadzhy]  Insufficient amount of links ~ trying again: 1
INFO [2018-06-25 15:08:30] [dkhadzhy]  Insufficient amount of links ~ trying again: 2
INFO [2018-06-25 15:08:54] [dkhadzhy]  Insufficient amount of links ~ trying again: 3
INFO [2018-06-25 15:08:57] [dkhadzhy]  Cor! Did you send too many requests? ~ let's rest some
```
Tried with Like by Locations and Like by Tags. Desired amount: 800, 1000, 2000 etc.
InstaPy loaded 21.06.2018

@uluQulu maybe you can help? Thanks in advance!

**Comment by yaca8** [comment]
Hi I got same issue here, not sure what is causing this, any advice?

**Comment by dajdabartosz** [comment]
Me too.

wt., 26 cze 2018, 09:58 użytkownik yaca8 <notifications@github.com> napisał:

**Comment by dimahadgi** [comment]
Looks like instagram changed location ID:
From:
`225219858/dnipropetrovsk-ukraine/`
To:
`749889026/dnipro/`
Not sure, is it for all or only my location.

**Comment by Porapon** [comment]
Try reduce desired amount

**Comment by dimahadgi** [comment]
> Try reduce desired amount

Tried with 500. Got this message time to time.
Sometime it works fine.

**Comment by gotsomequestions** [comment]
Same problem here, before every tag, even with low desired amount. After the rest of 10 minutes it works for the desired tag. Any new information?
