### ISSUE TITLE
Unfollow is not really unfollowing

### ISSUE THREAD

**Issue by Doom666** [InstaPy/InstaPy#2259]
I've made the tests, the bot has been unfollowing, it prompts as if it is unfollowing, but yet I check the account afterwards and it's still the same, that explains why the list has been growing like crazy in the last days, you know any solution to this?

**Comment by Doom666** [comment]
I've re checked and searched for one of those names that says to have unfollowed, and it wasn't.
How can this happen?

**Comment by sionking** [comment]
IG blocks you from unfollowing
I have a working solution.
You can refresh the page after unfollowing and see if it really happened.

**Comment by Doom666** [comment]
Funny though is that I unfollowed one person and it worked

**Comment by Doom666** [comment]
Dosnxt should throw an error and stop the script? 
And if it blocked the account from unfollowing. Why I can do it manually? Ip block?

**Comment by spikeyhair** [comment]
I tried to manually unfollow people, when I keep doing this (1 after another), I noticed at the 11th unfollow activity, it showed I have unfollowed but when I refresh the page, I am still following that profile. I have to wait for 1~2 mins, do it again and it works.

It should be the temp soft banning from IG for unfollowing too many users consecutively non stop.

**Comment by Doom666** [comment]
Well, the bot said 5o have unfollowed 450 , and when I checked didn't unfollowed a single one, this with the 10 minutes pause of the default settings, so i found it strange

**Comment by spikeyhair** [comment]
In my case, I set the bot to unfollow let's say 500 but ended up it only unfollowed 400 or lesser (even with a min rest after every 10 unfollow activities) but at least it did its job. Your case is really strange.

**Comment by sionking** [comment]
Don't do headless.
Don't run from google cloud\AWS\digital ocean.

**Comment by sionking** [comment]
refresh the page each unfollow to check it worked, I can PR this feature one day.

**Comment by aleeepp** [comment]
I have this problem [https://github.com/timgrossmann/InstaPy/issues/2187](url) , am I alone whith this ?

**Comment by alexmourer** [comment]
@aleeepp 

I run headless on Ubuntu and was running into this issue where it was reporting that it was unfollowing the user but it was not. The script was getting hung on the new Unfollow Prompt.

As a workaround for my situation, I added the following code to unfollow_util.py on line 441. Hopefully, this can be of help someone else. 

`sleep(2)`
`prompt_button = browser.find_element_by_xpath("//button[contains(., 'Unfollow')]")`
`click_element(browser, prompt_button)`

**Comment by Doom666** [comment]
Well, I do run it in AWS, but why would that all the sudden be a problem @sionking ?

**Comment by tuliosousapro** [comment]
@alexmourer I try your advice but didn't work either :-1:
