### ISSUE TITLE
Can't start quickstart.py

### ISSUE THREAD

**Issue by fanto88** [InstaPy/InstaPy#2262]
The shell open for like 1 second and then close itself with an error, but i'm not able to read it.
I just read something related to chromedriver, like "ensure chromedriver is installed in assets folder" or something like this. I have chromedriver 2.4 into that folder, is that okay? My google chrome is on latest version.

The GUI say "chromedriver is missing" but it's not, it's inside the folder :\

**Comment by juandelacruz-calvo** [comment]
Make sure the permissions are OK

**Comment by fanto88** [comment]
Permission are OK

**Comment by juandelacruz-calvo** [comment]
Is this the first time you us the application?
Was it working and suddenly stopped working?
Could you please give us some details regarding what parameters have you been using with it?

**Comment by fanto88** [comment]
I used it for a while and everything was ok, i stopped for about 1 month and now doesn't start.
I'm not using anything special, i'm using the GUI and as tags i put "dogs"

**Comment by juandelacruz-calvo** [comment]
I have the feeling that you didn't update your scripts, the code evolves and the options of it change easily, make sure you have your quickstart.py using updated commands

**Comment by fanto88** [comment]
This is the quickstart.py code


import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = ''
insta_password = ''

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#   Settings.database_location = '/path/to/instapy.db'
#   Settings.chromedriver_location = '/path/to/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.21,
				  delimit_by_numbers=True,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    # actions
    session.like_by_tags(['pugs'], amount=200)

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

**Comment by fanto88** [comment]
Nothing, still saying that ChromeDriver is not inside assets folder.
![untitled](https://user-images.githubusercontent.com/10716240/41744724-f1f71746-75a4-11e8-8446-b18570d004c2.png)

**Comment by juandelacruz-calvo** [comment]
Mate, you downloaded the Linux binary of Chromedrive and you seem to be trying to use it on Windows :p

**Comment by fanto88** [comment]
oh, emh.... ops?

Thanks mate :P

**Comment by juandelacruz-calvo** [comment]
you are welcome!

**Comment by fanto88** [comment]
now i can use the scripts, but this message keep appearing, any solutioon?

![untitled](https://user-images.githubusercontent.com/10716240/41767258-7047495e-7609-11e8-9d04-f04b11687df3.png)

**Comment by juandelacruz-calvo** [comment]
Sounds like Two factors authentication is enabled, try with this https://help.instagram.com/566810106808145

**Comment by fanto88** [comment]
That function is off, already checked.

**Comment by juandelacruz-calvo** [comment]
Try changing your password, any raging ex-girlfriend?
