### ISSUE TITLE
Script Generator to randomize activities

### ISSUE THREAD

**Issue by spikeyhair** [InstaPy/InstaPy#2264]
I want to ask is there a script generator to randomize the bot activities? If not then I will work on one.

First of all I would like to state my purpose but correct me if my idea doesn't work.

Purpose:
So that it's more difficult for IG to track certain patterns from the bot.

Example:
I am using a few types of functions in the bot. At this point of time, I might start it with interact_user_followers, like_by_feed and follow_likers. After the bot completed, the next round I want it to run with a different sequence e.g. follow_likers, interact_user_followers and like_by_feed.
OR
I can even set different parameters/users/hashtags to the functions:
follow_likers=5 users, interact with 10 users, unfollow 20 users, interact with 5 users and then unfollow 8 users again.

Now every time I have to manually change the sequence and parameter settings in quickstart.py before I run it again. So I am thinking if there is a "script generator", I just punch in which functions I want to use, what parameters to put in and with a click of a button, it generates the quickstart.py for me.

Sorry, I hope I am not confusing you all and you are able to get the meaning of this so called "script generator".

**Comment by rorloj** [comment]
python has a random module that allows you to use fuctions like "random.randint(1,10)" to set a random amount of likes, follows, or whatever between 1 and 10. Just not sure if it is that simple to integrate it to random all the actions Instapy does, just a matter of trying I guess ;)
