### ISSUE TITLE
Simple way to made changes in the code for personal use

### ISSUE THREAD

**Issue by marcomokastyle** [InstaPy/InstaPy#2267]
Hi, i'm also changing some things for my self, and not all the changes I think are suitable for a PL, i'm thinking to implement a new Class that extends InstaPy. So my changes are in my class, that inherits InstaPy.

I'm looking a simple way, to manage my edits, and the constant changing of the code here in GitHub, and make very little edits, but maintain the base code updated. 

Is it a good idea? Or maybe could be a better solution to this problem? 
I don't want change every time the code when I update from gitHub.

**Comment by sionking** [comment]
You totally right !
My suggestion is to put all your "includes/vars/functions" at the end of the section.
This way it easy to maintain.
Maybe inherit from different class is a good solution 2, tell me what you did.

**Comment by marcomokastyle** [comment]
I'll made some experimenting, and I'll share what i have done, i'm currently trying the path of a new class.
