### ISSUE TITLE
Constant number of pictures for tags except first one

### ISSUE THREAD

**Issue by CodeMaster1** [InstaPy/InstaPy#227]
Hi,

When I am using multiple tags with multiple tag number, the number of pictures instapy navigates for first tag is correct but from second tag, it only picks up 33 images to navigate. For example:

Here is the line to pick up tag number:
tag1 = randint(100, 200)
tag2 = randint(200, 300)
tag3 = randint(50, 100)

and here is the execution to like by tag:
  .like_by_tags(['#instago'], amount=tag1, media='Photo')\
  .like_by_tags(['#passportready'], amount=tag2, media='Photo')\
  .like_by_tags(['#tourism'], amount=tag3, media='Photo')\

For first tag, it picks up any random number between 100 and 200, which is expected.
But for second and third, it only picks 33 images to navigate through.

For first tag:
![image](https://cloud.githubusercontent.com/assets/7813918/25701386/d9c01cfa-30e9-11e7-809f-fdd32b968cfb.png)

For second and subsequent tags:
![image](https://cloud.githubusercontent.com/assets/7813918/25701318/86098092-30e9-11e7-9402-c4a5a168274a.png)

Has any one else seen this bug?

Thanks!

**Comment by tibor** [comment]
Probably related to #204 and #220.

**Comment by CodeMaster1** [comment]
Thank you! I should have searched better, :)

**Comment by tibor** [comment]
No problem. Hopefully this will be fixed, maybe with Chromes headless mode :)
