### ISSUE TITLE
Could be an UTF8 Bug in don't like regex structure?

### ISSUE THREAD

**Issue by redsector72** [InstaPy/InstaPy#2271]
I am not that good in python, but I suppose there is a bug in the don't like check.
If I have a tag like "#snapchat👻" it seems to quit without any warning.
I leave this check to you.
If the problem is not in there, I will try to debug better.

**Comment by jeremycjang** [comment]
https://github.com/timgrossmann/InstaPy/blob/master/README.md#emoji-support

**Comment by redsector72** [comment]
@jeremycjang I am supposing there is a bug, I have no problem with emoji.
If there is a tag in the comments of a picture, and the tag include an UTF-8, like in the example I have shown, Instapy quits.
I am not able to debug where and why quits.

**Comment by the-unknown** [comment]
same here, can confirm this bug. 
When a hashtag includes an emoji or an UTF-8 character, InstaPy quits. 
I will post the exact error, next time I run into it.

**Comment by the-unknown** [comment]
This is the error I get:

Traceback (most recent call last):
  File "./quickstart.py", line 24, in <module>
    session.like_by_tags(['stayandwander], amount=100, media=None)
  File "/home/user/InstaPy/instapy/instapy.py", line 1315, in like_by_tags
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 53: ordinal not in range(128)

**Comment by timgrossmann** [comment]
The issue is bound to your terminal output and the standard decoding that is set (seems like Ascii). 
If you change the decoding, it should work.

**Comment by kushpvo** [comment]
If anyone can help by explaining how to change the decoding in terminal output?
My Rasp Pi is setup as UTF-8 but the terminal is still outputting ASCII.
