### ISSUE TITLE
Only post one comment per user

### ISSUE THREAD

**Issue by alwaysmisterright** [InstaPy/InstaPy#2274]
Hi there,

I wanna set up my script in a way that it only posts one comment on one photo of 100 of someone else's followers.

But it seems to be posting comments for all photos.

   session.set_user_interact(amount=100, randomize=True, percentage=100, media='Photo')
    session.set_do_follow(enabled=True, percentage=100)
    session.set_comments(["example"])
    session.set_do_comment(enabled=True, percentage=100)
    session.interact_user_followers(['example'], amount=100, randomize=True)
    

Besides, I also want it to follow 100 of someone's followers, but I only seem to be getting a few. What's wrong?

**Comment by redsector72** [comment]
session.set_user_interact(amount=1, randomize=True, percentage=100, media='Photo')
and the rest is ok
