### ISSUE TITLE
chromedriver 2.34 is not supported, expects 2.36+

### ISSUE THREAD

**Issue by jufelka** [InstaPy/InstaPy#2275]
After the last update I got this error:
instapy.instapy.InstaPyError: chromedriver 2.34 is not supported, expects 2.36+
I've tried apt-get update but still get the same error.

**Comment by wemakefuture** [comment]
What system you running at?

You can apt-get update chromedriver. 
download newest version of chromedriver and put it executeable into assests. 

if you run raspy

1. Move the driver into the InstaPy/assets directory `mv /usr/bin/chromedriver /path/to/InstaPy/assets/chromedriver`
1. nano instapy/settings.py
1. change "chromedriver_min_version = 2.36" to "chromedriver_min_version = 2.33" & save file

**Comment by jufelka** [comment]
Thank you. It works!

**Comment by CluelessPandaTheFirst** [comment]
@xxxZedxxx @wecanfuture Hi, sorry for bothering the two of you. I got the exact same error today as well: could you explain this solution further? (Like, how to change the minimum version) I'm completely new to all of this and a bit lost, sorry again.

**Comment by theBhumbak** [comment]
hey guys i'm on PC with win10 same error
