### ISSUE TITLE
Hi Guys This my error after update 

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#2277]
Traceback (most recent call last):
  File "start.py", line 46, in <module>
    session.unfollow_users(amount=300, onlyInstapyFollowed =True, sleep_delay=300, unfollow_after=48*60*60 )
TypeError: unfollow_users() got an unexpected keyword argument 'onlyInstapyFollowed'

**Comment by marcomokastyle** [comment]
@johnvfitness I think that this parameter was changed in InstapyFollowed. 
Try InstapyFollowed=True instead.

**Comment by johnvfitness** [comment]
Thx my friend 👌
