### ISSUE TITLE
logfile based on account username

### ISSUE THREAD

**Issue by CodeMaster1** [InstaPy/InstaPy#228]
Hi, 

I have personally found logfile cumbersome if the code is run for different account so I modified the code to dump logfile based on account it is running. 

Please let me know if I can check-in my changes,

Thanks!

**Comment by CodeMaster1** [comment]
Found this is already created. Bummer! :/

**Comment by tibor** [comment]
If you’ve modified and tested the code already, feel free to make a pull request.

For now it’s just an issue (#225)

**Comment by CodeMaster1** [comment]
Yes, I have tested the change for log files based on username and it works fine for me. 
What should be the initial value for followrestriction.json because the empty file gives an error during initialization.

**Comment by tibor** [comment]
I guess the same like the initial in /logs/followrestriction.json: `{}`

Maybe @timgrossmann can approve this?

**Comment by timgrossmann** [comment]
@CodeMaster1 @tibor yes, just an empty JavaScript object

**Comment by CodeMaster1** [comment]
What is the process to check-in my changes? 

I have changes to check-in for two issues - #225 and #244.

**Comment by littleswany** [comment]
@CodeMaster1 Do you mean getting submitting them to the codebase? Like you have made changes?

If so create a pull request explaining what you have done and someone will review it.

https://github.com/timgrossmann/InstaPy/wiki/How-to-Contribute
