### ISSUE TITLE
follow_user_followers inapproriate user problems

### ISSUE THREAD

**Issue by torbenberger** [InstaPy/InstaPy#2281]
Hi guys,

i make heavy use of the follow user followers function. by following 1000 accounts and then unfollow them again and repeat the process i can gain up to 500 followers per week.

currently i am running into an issue where the bot gives me a lot of `inappropriate user not followed` logs. because of this my follow process has slowed down drastically because only 1/10 users is actually followed.

i debugged this down to the reason: the user has already been followed some time. so actually this is not a false behavior but its inefficient.

The problem seems to be the scraping of the followers. as i can understand the bot opens the follower list of the given user, and scrapes his followers by scrolling this list and collection users from the elements. at this point there is no checking if the user already has been followed some time. so if i try to gain followers from multiple accounts that are in the same genre, i also get a large amount of same users from this method as instagram seems to sort the followers somehow resulting in partly identical list.

i came up with an solution but wanted to know what you guys think of it:

i am now using @uluQulu 's new relationship feature (awesome btw) 

```
    # get all already followed users from logs
    my_restricted_users = session.follow_restrict.keys()

    # grab all followers of a user
    all_followers_of_user = session.grab_followers(username="USERNAME", amount="full", live_match=True, store_locally=True)

    # exclude all followers of this user that you already followed
    all_not_followed_followers_of_user = np.setdiff1d(all_followers_of_user,my_restricted_users).tolist()

    # randomize the users
    random.shuffle(all_not_followed_followers_of_user)

    # slice the users to desired follow amount
    to_follow_users = all_not_followed_followers_of_user[0:1000]

    print("Now following ", len(to_follow_users), " Users")

    # follow
    session.follow_by_list(to_follow_users, times=1, sleep_delay=660, interact=False)
```

this method is working really well so far but i am a little concerned about less interaction. with the original follow_user_followers method there is a lot of scrolling and fake interaction to trick the IG bot detection. with my solution there is nearly no interaction at all..

*what do you guys think, will this be a problem?*

(another solution would be to upgrade the `get_users_through_dialog` function in unfollow_util to be more fast and only return users that havent been followed before, but i think this will have impact to other functions aswell as this method is not only used by follow as i see)

**Comment by sammydigits** [comment]
Why does following so many accounts, and then unfollowing them all, gain you so many followers?
