### ISSUE TITLE
Action blocked

### ISSUE THREAD

**Issue by nakaori** [InstaPy/InstaPy#2282]
Hey,

i'm getting action blocked from instagram for some time now. i stopped running the script with cron for now to avoid being banned.

the exact same configuration i had running for nearly 3 weeks before this started to happen. has instagram changed my daily limits because they suspect botting?

is there a way to find out, which of the steps is causing this? like is it the following, unfollowing or the image liking step? i would want to adjust my limits - is there a way to plot out an overview on all figures about steps the script has done per run?

**Comment by spikeyhair** [comment]
This is what I worry too. That's why I change the pattern (config) every time and each time it runs around 10 - 12 hours only. After running, rest for a few hours before starting another session where the pattern is different again. This is what I am doing.

**Comment by sionking** [comment]
Also try to sleep for 30~ each 2-3 hours

**Comment by nakaori** [comment]
it looks like my "action blocked" was popping up, because i was using vpn which endpoint was in a datacenter. it appears that my subnet is banned by ig. if i disconnect from vpn everything works.

**Comment by AKwoKWH** [comment]
I am having the same issue
My like action got block everyday and right after it is unblock after 24 hours.

It is ridiculous
I just like 1 pic then I get blocked again
Days after days
