### ISSUE TITLE
ERROR   set_automated_followed_pool error

### ISSUE THREAD

**Issue by nocomment-bln** [InstaPy/InstaPy#2283]
Starting to unfollow users..
ERROR   set_automated_followed_pool error local variable 'fword' referenced before assignment
 Unfollowing the users followed by InstaPy

Any ideas how I can fix that ?

Thanks Guys

**Comment by nocomment-bln** [comment]
I dont know what

 "ERROR set_automated_followed_pool error local variable 'fword' referenced before assignment
Unfollowing the users followed by InstaPy"

means :(

**Comment by cuspid17** [comment]
how did you solve?
