### ISSUE TITLE
Is anyone interested in monthly cost (5$) gender and age checking (dedicated server for instapy)

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2284]
I am working on image recognition application installation with some other checks that will tell you the gender and age by inputting the image url and profile name.
I am already using it on my accounts, and it gives great results. 
but I think we should have use it.

This maintain and server cost is a bit high so I thought of sharing to the community, so it will be unlimited checks (100k / month) for 5$ instead of using the limited (5k/ month) Clarifai api.

Is it in anyone interest ?

**Comment by converge** [comment]
Im interested for the next month

**Comment by sionking** [comment]
I am not sure when it will be ready :() hopefully soon but good to know you are in.
It basically uses some OpenCV open source and other stuff. we can improve it as time goes by.
Also it is not as accurate as clarifai but we got good results.

**Comment by imjustin** [comment]
I think this is interesting and I'd be interested. I don't currently use the clarifai in my script though; what kind of profiles do you have that you need to filter what you like? my account is all portraits so the users/hashtags i'm engaging with are other portrait communities.

**Comment by sionking** [comment]
@imjustin  show me one tag that contain only portraits ?
And most of my client point female gender, that is the main use for clarifai but I do get to pay extra 4k more images per user that is 4.8$ for each account, expensive !

**Comment by imjustin** [comment]
@sionking some tags that are almost exclusively portraits: portrait_ig, moodyports, pursuitofportraits.

but i guess my question was more around whether you're using it to filter out inappropriate pics to therefore not comment on, or are you using it to select in  which images you do engage with? or are you using it to ID what demographic the account you're engaging with falls into?

**Comment by sionking** [comment]
Gender check for profile picture mainly.
Smart comment only with clarifai.

**Comment by imjustin** [comment]
got it. that makes sense. I don't currently use commenting, but i can definitely see how clarifai would be really useful there. love all the work y'all are doing, would love to help where i can.

**Comment by isaniomoraes** [comment]
I'm definitely interested as well :+1:
