### ISSUE TITLE
potency_ratio checking for wrong logic (opinion)

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2285]
@uluQulu 
> e.g., target user has 2000 followers & 3000 following and you set potency_ratio = -1.7.
> Now it will not interact with this user, cos the user's relationship ratio is 3000/2000==1.5 and 1.5 is below desired potency_ratio of 1.7 (note that, negative - sign is only used to determine your style, nothing more

I think the desired potency_ratio should be checked against ratio that are too high, and not looking for high ratios:
Now:
```
relationship_ratio < potency_ratio 
   return false
```
Should be:
```
relationship_ratio > potency_ratio
   return false
```

I want to avoid users with following/followers **higher** than 1.7 not **lower** than.
So in the example above we **will** interact with users with 3400/2000 (following/followers) but won't interact with users with 3000/2000 ? don't we want to avoid **massive followers**?

**Comment by sionking** [comment]
Am I missing something ?

**Comment by timgrossmann** [comment]
@sionking That's a good point here.
Intentionally, I'd say you're right. Maybe @uluQulu has a different view on this since he's the one who introduced it.

But I'd definitely say that we want to have the value as an "upper" bound instead of a "lower" one, so we should change it.
