### ISSUE TITLE
follow_user_followers feature not working

### ISSUE THREAD

**Issue by rexonat** [InstaPy/InstaPy#2289]
My setup is Rpi3,python 2.7, firefox ESR with geckodriver as chromedriver would not work.
I have spent a few days on this and asking on here as a last resort.  I am a newbie so could be something really basic but I have searched lots through google, and github and tried to figure out whats happening but no, I am about to smash a frying pan against my head at this point in time.

I can get the quickstart script to execute on just liking photos alone - although it may take several tries in a row where nothing changes which is baffling, when I add the line;

`session.follow_user_followers(['userid'], amount=10, randomize=True)`

To run the script I enter-
```
sudo xvfb-run python2.7 quickstart_merimtest.py
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-06-21 01:52:28] [xxxx]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...

................................................................
INFO [2018-06-21 01:53:54] [xxxx]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-06-21 01:54:12] [xxxx]  User 'xxxx' [1/1]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-06-21 01:55:06] [xxxx]  Session ended - 2018-06-21 01:55:06
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "quickstart.py", line 35, in <module>
    session.follow_user_followers(['206532146'], amount=10, randomize=False)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 2014, in follow_user_followers
    self.logfolder)
  File "/home/pi/Projects/InstaPy/instapy/unfollow_util.py", line 827, in get_given_user_followers
    "//span[contains(@class,'g47SY')]")[1].text)
IndexError: list index out of range

```
PLEASE SEND HELP!

**Comment by sionking** [comment]
did you update to latest
 ?

**Comment by rexonat** [comment]
I think I have done before I uninstalled it and started over again but have just updated again which included a few fixes, error has changed to the following; (also I have tried inputting the targeting users id as the number id as above and the instagram 'user friendly' (alphabetical) id

```
Traceback (most recent call last):
  File "quickstart_merim.py", line 23, in <module>
    multi_logs=True)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 189, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 251, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmph0FV1u If you specified a log_file in the FirefoxBinary constructor, check it for details.

```

**Comment by converge** [comment]
the issue is related to the connection between geckodriver and FF

**Comment by Themesaul** [comment]
Same problem. From clean installation right now.

`
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-06-21 18:22:32] [xxx]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

....................................................................
INFO [2018-06-21 18:23:05] [xxx]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-06-21 18:23:10] [xxx]  User 'yyy' [1/9]
ERROR [2018-06-21 18:24:02] [xxx]  `followers_link` error list index out of range
INFO [2018-06-21 18:24:02] [xxx]  Grabbed 0 usernames from yyyy's `Followers` to do following.
INFO [2018-06-21 18:24:02] [xxx]  User 'hhh' [2/9]
ERROR [2018-06-21 18:24:55] [xxx]  `followers_link` error list index out of range
`

**Comment by converge** [comment]
double check the docs, you're not using lists when setting the config file.

**Comment by rexonat** [comment]
@converge  do you recommend any particular version of geckodriver which runs best with ff-esr?
(currently running v18)

How do I check that Im not using lists?

**Comment by rexonat** [comment]
Im going to mess around with different versions of geckodriver - how do I perform a rollback in the terminal?  I have tried uninstalling but not getting any luck here either.
Or if anyone can suggest an easier alternative than working with firefox and geckodriver? 
Im running this experiment on a rpi3

**Comment by rexonat** [comment]
getting the following when trying to update geckodriver from v18;

```
pi@raspberrypi:~/Projects/InstaPy $ tar -xvzf geckodriver-v*
tar: geckodriver-v0.18.0-linux64.tar.gz: Not found in archive
tar: Exiting with failure status due to previous errors
```

**Comment by jorgeolarte** [comment]
I fixed the trouble the follow_user_followers function. You only need to do is keep maximize your browser... thats all.

**Comment by xk7612** [comment]
exactly same error, I have updated to the lasted files, can anyone help on this issue? Thanks
