### ISSUE TITLE
dont_unfollow_active_users not working

### ISSUE THREAD

**Issue by michaelBielang** [InstaPy/InstaPy#2291]
## Expected Behavior
unfollow users

## Current Behavior

Traceback (most recent call last):
  File "quickstart.py", line 68, in <module>
    session.set_dont_unfollow_active_users(enabled=True, posts=5)
  File "/home/n-rg/venv/bin/InstaPy/instapy/instapy.py", line 2533, in set_dont_unfollow_active_users
    self.dont_include.update(active_users)
ValueError: dictionary update sequence element #0 has length 25; 2 is required

## InstaPy configuration

session.set_dont_unfollow_active_users(enabled=True, posts=5)

Don't know what else to add :)

**Comment by alvaroschipper** [comment]
Having this issue as well.

**Comment by sionking** [comment]
try to change this
under def set_dont_include(self, friends=None):
self.dont_include = set(friends) or {}
to:
self.dont_include = set(friends) or set()

If no friend exist it might consider as dict.

please let us know.

**Comment by michaelBielang** [comment]
Doesn't work for me.

ValueError: dictionary update sequence element #0 has length 13; 2 is required

**Comment by michaelBielang** [comment]
last merge fixed for me
