### ISSUE TITLE
Issue Unfollow

### ISSUE THREAD

**Issue by cormo1990** [InstaPy/InstaPy#2293]
Hello! anyone with the same problem? I suppose that it happen after the latest updates of IG

![schermata 2018-06-21 alle 21 07 22](https://user-images.githubusercontent.com/36590321/41740117-5dce1626-7597-11e8-97ac-94ff82a3a474.png)

@uluQulu I tag you in order to keep you updated

**Comment by michaelBielang** [comment]
yes have now the same issue

**Comment by sionking** [comment]
IG profile page did not work for some hour .
YOU SHOULD THANK ME check out _uncertain_unfollowedPool.csv (I added it), all the unfollowed is there.

**Comment by michaelBielang** [comment]
ty! Do I have to import the names from that list to the followedPool.csv? If yes, do I also have to bring it in the same format then, like adding the date and time?

Edit:
I observed it. There is something wrong. Instagram is online, the users are also still existing. But the page instapy is calling always says that the user is no longer existing

**Comment by sionking** [comment]
Now IG back to work.
Just copy paste don't add date.

**Comment by michaelBielang** [comment]
No its definitely broken. I observed it. Even when the users are there and the site shows his/her profile in chrome, he says user maybe no longer exists!

**Comment by luism123mb** [comment]
I am also having the same issue, have you guys found any solution? Thanks @timgrossmann

**Comment by sionking** [comment]
Do you get the confirmation msg ?

**Comment by cormo1990** [comment]
As reported @sionking now works good! thanks for the file uncertain_unfollowedPool.csv

**Comment by michaelBielang** [comment]
What do you mean with "confirmation msg" ?

I talk about, that users, whose profile is existing, displayed and tried to be unfolled, end with that error message and are not unfollowed.

**Comment by ghost** [comment]
same error here, instapy say 

--> Ongoing Unfollow 9, now unfollowing: lamagnoliacarwash

but not really unfollow ...

any suggestion ?

ps. i try manually to unfollow people and it works.

Thanks

**Comment by ghost** [comment]
sorry , it works correctly . it was my fault ...
cya

**Comment by ArdySan2012** [comment]
@ilmetu Did you fix it? How?

**Comment by cormo1990** [comment]
@ArdySan2012 it was an IG issue, the problem was solved automatically after 5 hours more or less.

check the file uncertain_unfollowedPool.csv by @sionking to be sure to have all the users list

**Comment by nadavdrukker** [comment]
I have a similar issue, currently. Seems like the uncertain unfollows remain in followpool file.

See beginning of successive unfollow sessions. The first 5 in follow pool don't exist:

ERROR [2018-06-24 12:33:55] [nadavdrukker]  --> Unfollow error with matilda_3210, maybe no longer exists...
ERROR [2018-06-24 12:34:23] [nadavdrukker]  --> Unfollow error with riarq98, maybe no longer exists...
ERROR [2018-06-24 12:34:51] [nadavdrukker]  --> Unfollow error with zalkaraskaraliev5, maybe no longer exists...
ERROR [2018-06-24 12:35:18] [nadavdrukker]  --> Unfollow error with jalalfarhaditoomaj, maybe no longer exists...
ERROR [2018-06-24 12:35:46] [nadavdrukker]  --> Unfollow error with victorcavalcantivitti, maybe no longer exists...

Then some are unfollowed and there are two more errors along the way, which is fine. But then next time I unfollow, in 20 minutes, it tries to unfollow those 5+2 again. And they are still sitting at the top of my followerpool file.

ERROR [2018-06-24 12:58:12] [nadavdrukker]  --> Unfollow error with matilda_3210, maybe no longer exists...
ERROR [2018-06-24 12:58:40] [nadavdrukker]  --> Unfollow error with riarq98, maybe no longer exists...
ERROR [2018-06-24 12:59:09] [nadavdrukker]  --> Unfollow error with zalkaraskaraliev5, maybe no longer exists...
ERROR [2018-06-24 12:59:37] [nadavdrukker]  --> Unfollow error with jalalfarhaditoomaj, maybe no longer exists...
ERROR [2018-06-24 13:00:05] [nadavdrukker]  --> Unfollow error with victorcavalcantivitti, maybe no longer exists...
ERROR [2018-06-24 13:00:34] [nadavdrukker]  --> Unfollow error with stoney_and_boney_no.2, maybe no longer exists...
ERROR [2018-06-24 13:01:02] [nadavdrukker]  --> Unfollow error with rafaelrequiaofotos, maybe no longer exists...

**Comment by ghost** [comment]
@ArdySan2012 i didn't do anything ... i just wait 24 hours and then the script start to unfollow correctly :)

**Comment by michaelBielang** [comment]
are you sure? Do you observe it?
