### ISSUE TITLE
Install Chromedriver on Google Cloud Platform

### ISSUE THREAD

**Issue by asheshinsta** [InstaPy/InstaPy#2296]
I have just tried to install Instapy on my google cloud account so that i can practically access it from everywhere including my work, but there is the error of installing chromedriver...

how do i Install Chromedriver in google cloud.....please help

File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/home/ashesh_jain/InstaPy/instapy/instapy.py", line 189, in __init__
    self.set_selenium_local_session()
  File "/home/ashesh_jain/InstaPy/instapy/instapy.py", line 300, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/ashesh_jain/InstaPy/assets/chromedriver

**Comment by jakeseaton** [comment]
1) Is the chromedriver present on the server? If not you can download it with `wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip`, then unzip it and move it to `InstaPy/assets`.

2) Is chromium installed? If not you can install it with `sudo apt-get install chromium`. This fixed the problem for me.

**Comment by nutansahoo** [comment]
I have installed

**Comment by nutansahoo** [comment]
Hi I want to scrape google search results (links, title and description) in Google cloud platform. So for that I installed latest version of chrome driver. But when I tried running using it, I am getting the following error: 
`WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

The code that I am using is:

```
from selenium import webdriver
driver = webdriver.Chrome() 
options = Options(executable_path='/home/jupyter/chromedriver.exe')
def basic_clean_html(the_page):
    the_page = re.sub('<!--m-->','', the_page)
    the_page = re.sub('<!--n-->','', the_page)
    the_page = re.sub('\s+',' ', the_page)
    the_page = re.sub('>\s<','><', the_page)
    the_page = re.sub('&amp;','&', the_page)
    return the_page


def get_page(gu_name_cleaned):
    base_url = 'https://www.google.co.in/search?q='
    url_suffix = gu_name_cleaned.replace(' ', '+')
    url_suffix = gu_name_cleaned.replace('&', '%26')
    link = base_url + url_suffix
    time.sleep(2)
    driver.get(link)
    the_page = driver.page_source
    the_page=basic_clean_html(the_page)
    return(the_page)
get_page("Python")

```
I have installed chromium using the above code. 
Yet I am facing the same error that ` 'chromedriver' executable needs to be in PATH`. 
Can anyone please help me figure this out?

**Comment by rehanmahmood** [comment]
> 1. Is the chromedriver present on the server? If not you can download it with `wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip`, then unzip it and move it to `InstaPy/assets`.
> 2. Is chromium installed? If not you can install it with `sudo apt-get install chromium`. This fixed the problem for me.

Hey, When I try this my system returns 
`-bash: wget: command not found`
any idea what the issue could be?
