### ISSUE TITLE
discussion: save user_id also with to usernames.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2297]
So if someone change his username we don't have a lost data.
I think user id can't change while username can.

**Comment by marcomokastyle** [comment]
@sionking Interesting, I'm also wondering the same, what happen if a user change it's user name. I also think that user id will be the same.

**Comment by sionking** [comment]
I get many times username not avaialbe after trying to unfollow, so it either deleted or renamed.

**Comment by ghost** [comment]
@sionking where can we take the userid , what page / api ? 

Thanks

**Comment by marcomokastyle** [comment]
@sionking @ilmetu I saw user id in graphql, I don't remember where, but I remember, that was there.

**Comment by ghost** [comment]
@marcomokastyle i think is in a json hidden in the instagram page when logged in...

**Comment by marcomokastyle** [comment]
@ilmetu exactly,is what a meant to say. should be in window._sharedData = {...}

**Comment by marcomokastyle** [comment]
@ilmetu @sionking _sharedData.entry_data.ProfilePage[0].graphql.user.id

**Comment by sionking** [comment]
How can we convert userId to username, that is my concern ...

**Comment by marcomokastyle** [comment]
@sionking we must check if there is a way to get from public api. And I'm not sure if is possible right now.

**Comment by sionking** [comment]
Why public API if it is possible from _sharedData.entry_data.ProfilePage[0].graphql.user.id ??

**Comment by marcomokastyle** [comment]
@sionking but if user name is changed how can we get the new user name? I'm wondering if is possible to get user name from user id. _sharedData is taken from the profile page url. So if user is not anymore the same... I don't know yet if we can get the username from a graphql query from https://www.instagram.com/graphql/query/

**Comment by sionking** [comment]
@marcomokastyle  that is what I was think also....

**Comment by nadavdrukker** [comment]
If you search for a username that no longer exists, Instagram often suggests the new username. If we have the original and new  id, we can confirm that it's indeed the correct account.
