### ISSUE TITLE
I'm working on a new feature save users to db

### ISSUE THREAD

**Issue by marcomokastyle** [InstaPy/InstaPy#2299]
@timgrossmann 
I'm working on a new feature save_likers_to_db, is just like follow_likers but instead of follow people, this save valid users in a db. Is an idea the came me while working on my skip profile feature.
User is stored in a sqlite db, I store in a table the source target, the user to follow, and the date of add. After you can call follow_by_db for a fixed amount of users to follow or follow_by_db_all for all the pending following saved. Maybe when it's ready i do a PR also for that.

**Comment by sionking** [comment]
Nice. A lot of work if you want to do it well.
Please also look at @uluQulu  latest features.... doing almost the same

**Comment by marcomokastyle** [comment]
@sionking @uluQulu is it in PR? If is so, I didn't noticed it :P
