### ISSUE TITLE
Why you choose to use webDriver, not through InstagramApi?

### ISSUE THREAD

**Issue by xiyouMc** [InstaPy/InstaPy#23]
InstagramApi is public and is also restricted for each Api. But the implementation speed should be faster than webDriver

### Like Example: 
* API
   https://www.instagram.com/web/likes/%s/like/

* Test:
  https://www.instagram.com/web/likes/1470104102175250269/like/

**Comment by timgrossmann** [comment]
I'm not sure if given example is from the real InstagramApi or if you mean the api calls, Instagram makes once clicking on the buttons.

For the real API, I read that it has a limitation of 500 likes per day... And you need an auth token, which I think is really annoying.

For the other idea, I think InstaBot is using the actual API calls which is pretty damn nice.
I didn't want to invest the time to reverse engineer their API structure.

If you've come here from the medium article, I explained that it actually started as a small project to learn how to use Selenium 😉

**Comment by schonert** [comment]
@timgrossmann there might be a point in considering using the web endpoints. We might be able to speed things up a bit and use less resources running the Bot. 

As soon as we sign in to Instagram the cookies are set - we’ll be able to use their endpoints as long as we include credentials. 

I’m not at my laptop - I’ll do a bit more research ☝🏻

**Comment by timgrossmann** [comment]
@schonert That sounds great, thank you!
This could also get rid of a lot of the problems when searching/clicking buttons.

I just read through this thread again and realised, that I just didn't understand what @xiyouMc was walking about. Now it makes a lot more sense and I really think this has to be observed some more so thank you @schonert  for your contribution!

**Comment by xiyouMc** [comment]
@timgrossmann That's my mistake，Sorry. Because I am a Chinese developer, all the words used is not very clear . Hahahaha
