### ISSUE TITLE
Lot`s of errors in quickstart.py

### ISSUE THREAD

**Issue by AlanInsam** [InstaPy/InstaPy#2303]
Hello, as I have lots of errors in my quickstart. py and, as I am not a programmer can someone please share with me his working quickstart.py with autolike,follow,unfollow and comment? Without personal information surely...

**Comment by michaelBielang** [comment]
It's all here: https://github.com/timgrossmann/InstaPy#instapy-available-features

**Comment by AlanInsam** [comment]
Yea I have implemented those lines of code in my quickstart.py but there are lots of errors for each function

**Comment by AlanInsam** [comment]
See: https://github.com/timgrossmann/InstaPy/issues/2256
