### ISSUE TITLE
Is this dangerous:  "LatencyInfo vector size 102 is too big"

### ISSUE THREAD

**Issue by ortegafernando** [InstaPy/InstaPy#2307]
## Expected Behavior
Script without errors.

## Current Behavior

Sometimes I get this error:

```
INFO [2018-06-25 08:25:10] [xxxxxxxxxx]  ---> Now following: yyyyyyyyy
[6604:5748:0625/082721.302:ERROR:latency_info.cc(164)] Display::DrawAndSwap, LatencyInfo vector size 102 is too big.
```

## InstaPy configuration
i am following a list of usernames

```
session.set_relationship_bounds(enabled=False)
session.follow_by_list(list_to_follow, times = 1)
time.sleep(20)
```

This code is inside a loop, and list_to_follow is only 1 item. (I need to do this way as I'm using an external list of usernames (txt file) and as I follow one, I have to remove the entry in the file.

This code has been working since 6 months ago. Yesterday I update the source code of Instapy after 3 months (sorry) and I am getting randomly the message about LatencyInfo.

**Comment by Nocturnal-2** [comment]
I am getting this way quiet often

**Comment by Nocturnal-2** [comment]
I was trying to find exactly where in code the message "Display::DrawAndSwap, LatencyInfo vector size xxx is too big." is generated. But I couldn't find it.  I assume this message is generated from places in the program. Can someone please help me understand this?
