### ISSUE TITLE
My account is blocked, detecting it as bot

### ISSUE THREAD

**Issue by priyanka271** [InstaPy/InstaPy#2309]
I am working with the InstaPy code for conditional liking and commenting. Everything works fine in my local system but the server sends a "suspicious" login message to the account owner and even on confirmation, it does not allow the bot to login. Please help on what can be done. and if proxy server is the solution, then how can we set it up.

**Comment by sionking** [comment]
Where do you run it from ? digital ocean servers ?

**Comment by sionking** [comment]
stop commenting

**Comment by priyanka271** [comment]
@sionking  Yes. Digital ocean server and by stopping comment prevents this issue?

**Comment by Areahints** [comment]
how many accounts are you running on the server

**Comment by priyanka271** [comment]
Currently using 10 accounts but that may increase.

**Comment by Areahints** [comment]
intresting? are you using proxies now? how do you configure them in quickstart.py

**Comment by priyanka271** [comment]
I have modified the code and creating chrome extension for different proxies.

**Comment by priyanka271** [comment]
But Now my problem is, how can I run cron at the same time for different proxies?

**Comment by Areahints** [comment]
can you share your modifications and chrome extensions' since you're using linux server like me, it should work well? im trying to use luminati


for multiple scripts running via cron https://unix.stackexchange.com/questions/287166/how-to-run-multiple-scripts-at-a-same-time

**Comment by priyanka271** [comment]
Multiple proxy works but the problem is, at any time we can use one one proxy in chrome but when i have many accounts  running over 10 proxies, the users target wont complete
Are you getting my point?

**Comment by Areahints** [comment]
i see, in this case you want a situation where each instance of chrome would be using its own dedicated proxy right?

**Comment by Nocturnal-2** [comment]
@priyanka271 Did you manage to find a way?
