### ISSUE TITLE
Uncertain unfollows are not removed from FollowedPool file

### ISSUE THREAD

**Issue by nadavdrukker** [InstaPy/InstaPy#2311]
## Expected Behavior

After a "Unfollow error with ***, maybe no longer exists..." expect user to be removed from CSV file and moved to uncertain_unfollowd_pool

## Current Behavior

User remains at the top of the FollowedPool file, so next time an unfollow routine is called, their page is looked for again (and all subsequent unfollowing sessions).

## Possible Solution (optional)

Note that unfollow_util has a routine get_following_status which should be doing this, but it's not called, instead it's copied below.

## InstaPy configuration

Latest instapy pull 24/6/18. MacOS 10.13.5. python 2.7.10.

Here is a sample script:
from instapy import InstaPy
insta_logfolder = 'logs/'
session = InstaPy(username=***,  password=***)
session.login()
session.unfollow_users(amount=2, InstapyFollowed=(True, "all"), style='FIFO', sleep_delay=500)
session.unfollow_users(amount=2, InstapyFollowed=(True, "all"), style='FIFO', sleep_delay=500)
session.end()

The output is as follows. Note that the first users in both unfollow sessions are identical.

Thanks for your help!

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-06-25 20:41:31] []  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

..................................................................
INFO [2018-06-25 20:42:07] []  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

_______________________________________________________________________
INFO [2018-06-25 20:42:11] []  Starting to unfollow users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-06-25 20:42:11] []  Unfollowing the users followed by InstaPy

INFO [2018-06-25 20:42:12] []  Total 4685 users available to unfollow  ~didn't pass `unfollow_after`: 0

ERROR [2018-06-25 20:42:41] []  --> Unfollow error with v2_wernher_von_braun, maybe no longer exists...
ERROR [2018-06-25 20:43:09] []  --> Unfollow error with mayssa_dhaoui, maybe no longer exists...
INFO [2018-06-25 20:43:14] []  --> Removed '2018-06-07 16:05 ~ dulcementa_mx' from followedPool.csv file
WARNING [2018-06-25 20:43:14] []  --> Cannot Unfollow From InstaPy 0, maybe dulcementa_mx was unfollowed before...

INFO [2018-06-25 20:43:22] []  --> Ongoing Unfollow From InstaPy 1/2, now unfollowing: marthamcaleer.artist
INFO [2018-06-25 20:43:22] []  --> Removed '2018-06-07 16:05 ~ marthamcaleer.artist' from followedPool.csv file

INFO [2018-06-25 20:43:45] []  --> Ongoing Unfollow From InstaPy 2/2, now unfollowing: artesfidelina
INFO [2018-06-25 20:43:45] []  --> Removed '2018-06-07 16:05 ~ artesfidelina' from followedPool.csv file

WARNING [2018-06-25 20:43:58] []  --> Total unfollows reached it's amount given 2

INFO [2018-06-25 20:43:58] []  --> Total people unfollowed : 2

_______________________________________________________________________
INFO [2018-06-25 20:43:58] []  Starting to unfollow users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-06-25 20:44:02] []  Unfollowing the users followed by InstaPy

INFO [2018-06-25 20:44:02] []  Total 4682 users available to unfollow  ~didn't pass `unfollow_after`: 0

ERROR [2018-06-25 20:44:29] []  --> Unfollow error with v2_wernher_von_braun, maybe no longer exists...
ERROR [2018-06-25 20:44:57] []  --> Unfollow error with mayssa_dhaoui, maybe no longer exists...
INFO [2018-06-25 20:45:05] []  --> Ongoing Unfollow From InstaPy 1/2, now unfollowing: audelouiscarves
INFO [2018-06-25 20:45:05] []  --> Removed '2018-06-07 16:24 ~ audelouiscarves' from followedPool.csv file

INFO [2018-06-25 20:45:29] []  --> Ongoing Unfollow From InstaPy 2/2, now unfollowing: anastasiastylianou
INFO [2018-06-25 20:45:29] []  --> Removed '2018-06-07 16:24 ~ anastasiastylianou' from followedPool.csv file

WARNING [2018-06-25 20:45:42] []  --> Total unfollows reached it's amount given 2

INFO [2018-06-25 20:45:42] []  --> Total people unfollowed : 2

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-06-25 20:45:42] []  Session ended - 2018-06-25 20:45:42
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by sionking** [comment]
Check you have , at the end of the username
, , , , , , ,

**Comment by nadavdrukker** [comment]
Do you mean that there is comma at the end of each line in the Followed_Pool file? If so, this is the file generated by instapy and does have commas at the end of all lines

**Comment by nadavdrukker** [comment]
@sionking, everything works fine for other users in the file. Only those that don't exist anymore are not removed. It all worked fine on my old computer with a built from 2 months ago. I imported the old log files into the new built. Could that have been the problem?

**Comment by sionking** [comment]
I know the bug
The follow_button is not found (but checked for non-exist users) and therefore rise an error.
Sometimes Ig also showing the page "oops something went wrong.." that is not an IG temple at all.
Will PR soon.

**Comment by nadavdrukker** [comment]
Thanks!

**Comment by edobranchi** [comment]
Same for me, can be very annoying because you have to manually remove it from the csv
