### ISSUE TITLE
Will InstaPy follow someone that already has been followed and then unfollowed?

### ISSUE THREAD

**Issue by linus-dev** [InstaPy/InstaPy#2312]
Hello!

As the title, will the bot follow "user1" after it has been followed AND unfollowed once before?

Thanks!

**Comment by nadavdrukker** [comment]
by default not, but you can control it via times=number. See the lines in the explanation in the main page:

# default enabled=False, follows ~ 10% of the users from the images, times=1
# (only follows a user once (if unfollowed again))

session.set_do_follow(enabled=True, percentage=10, times=2)
# default enabled=False, follows ~ 10% of the users from the images, times=1
# (only follows a user once (if unfollowed again))

session.set_do_follow(enabled=True, percentage=10, times=2)

**Comment by linus-dev** [comment]
Thank you!

**Comment by ghost** [comment]
Does it get this information from `general.log` ?
