### ISSUE TITLE
  Sorry, an error occured: unfollow() takes exactly 15 arguments (14 given)

### ISSUE THREAD

**Issue by christoskolovos** [InstaPy/InstaPy#2314]
## Expected Behavior
unfollow all instep followed
## Current Behavior
error
## InstaPy configuration
session.unfollow_users(amount=60, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)

**Comment by sionking** [comment]
whitelist feature added please update
