### ISSUE TITLE
Sleep delay when scrolling user followers

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#2315]
Gentlemen, would you direct me please where to insert a sleep delay?

Lately, when loading other user followes   “failed to load desired amount, starting 1/12” happenning waaay to often. 
I wonder if I make the program rest 10 seconds after each scroll (or whatever), maybe it will reduce this occurance.

But I don’t know where this mechanism is located :)

**Comment by SPQRBrutus** [comment]
util.py line 396
