### ISSUE TITLE
I keep getting this error and I cant figure it out. 

### ISSUE THREAD

**Issue by ManicMartin** [InstaPy/InstaPy#2317]
woul you help me figuring out whats the problem and how to fix it ? 
![capture](https://user-images.githubusercontent.com/39764938/41900551-d9b13742-78e3-11e8-945a-06f03576ddf7.PNG)

**Comment by dajdabartosz** [comment]
There's no problem

wt., 26 cze 2018, 10:55 użytkownik ManicMartin <notifications@github.com>
napisał:

**Comment by ManicMartin** [comment]
so why doesn't work ?

**Comment by edobranchi** [comment]
@ManicMartin Try commenting the "from selenium.common.exception..." with a # like:
" #from selenium.common.exception..."
should fix the error.
