### ISSUE TITLE
like is not working

### ISSUE THREAD

**Issue by makita00** [InstaPy/InstaPy#2319]
## Expected Behavior
Like images by tags
## Current Behavior
It says that it is liking the images, but when I follow the link of the images they are not liked. Likely this is due to a recent InstaPy update.
I'm running it on digital ocean. I also changed the IP but it didn't  work. All the other features are working properly

Thank you!

**Comment by sionking** [comment]
don't use digital ocean

**Comment by Florenz23** [comment]
@sionking 
Hey, which vps/server provider can you recommend? 

does anyone has experience with contabo.com?

**Comment by sionking** [comment]
I have my own system.

**Comment by Florenz23** [comment]
@sionking 
I see, are you using proxies? It would be very nice if you could provide more information which are the best system settings, or just provide a link
thanks a lot sionking

**Comment by sionking** [comment]
Sorry, I can't.
I don't use proxy services online, I use ppl home ip address as the proxy.... but it is complicated.

**Comment by Florenz23** [comment]
thanks @sionking 
I tried to google ppl home ip address, but without success, can you give me a keyword to get some information about it 
thanks
