### ISSUE TITLE
Unfollow / New confirmation msg / Not Work

### ISSUE THREAD

**Issue by aleeepp** [InstaPy/InstaPy#2320]
Hello, After two weeks with this problem, I couldn't solve this, I can't use Intsapy because I can't end a cycle of Follow and Unfollow.

I search in the Issue and I found this:

[Pull](https://github.com/timgrossmann/InstaPy/pull/2245)  
[Issue](https://github.com/timgrossmann/InstaPy/issues/2187) 
[Issue](https://github.com/timgrossmann/InstaPy/issues/2259) 

I don't know if I do wrong the modification but It doesn't work, what can i do? , I don't know  what is the problem.

![image](https://user-images.githubusercontent.com/35710167/41925566-546067a6-7943-11e8-86f2-c6d222716dd3.png)

**Comment by ghost** [comment]
hi @aleeepp i will make a pr soon, i solved this issue
