### ISSUE TITLE
ERROR: gpu_process_transport_factory.cc(1017)] Lost UI shared context.

### ISSUE THREAD

**Issue by zsvendo** [InstaPy/InstaPy#2321]
C:\InstaPy>python 1.py
[0626/133052.535:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:63946/devtools/browser/4cec5161-5f22-42e3-bf05-c59a8987a4a4

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-06-26 13:30:53] [****]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

[0626/133056.568:WARNING:spdy_session.cc(2961)] Received WINDOW_UPDATE for invalid stream 33
Issue with cookie for user ****. Creating new cookie...

...............................................................
CRITICAL [2018-06-26 13:31:08] [****]  Wrong login data!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-06-26 13:31:12] [******]  Session ended - 2018-06-26 13:31:12
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by sionking** [comment]
You are on a server I think with no GPU not a real error.

**Comment by zsvendo** [comment]
See why you give this error? I updated everything chrome drive everything: @uluQulu @sionking 

![capturar](https://user-images.githubusercontent.com/28624361/41973354-1b0b1700-79eb-11e8-9572-cc9ae24f96de.JPG)

**Comment by sionking** [comment]
wrong password or ip blocked.

**Comment by zsvendo** [comment]
password, thakssssssssssssssssssssss

**Comment by antonio-piha** [comment]
Please close this one.
