### ISSUE TITLE
After update, session.end doesn't close Chrome and CPU is 99%  (no-sandbox option related?)

### ISSUE THREAD

**Issue by ortegafernando** [InstaPy/InstaPy#2322]
## Expected Behavior
session.end() would close and end session.
After that, python would close cmd window and chrome close perfectly.
## Current Behavior
I can see chrome closed (no windows), but I can see chrome in tas manager, using 99% of CPU
## InstaPy configuration
maybe related with chromedriver? I am using last version of chrome, chromedriver and Instapy and Selenium

Thanks

**Comment by converge** [comment]
is your script setup using the try/catch approach ?

**Comment by ortegafernando** [comment]
Hi @converge 
This is my script:
```
def main():
	try:
		.....
		session.logger.info('Finish')
		session.end()
	except Exception as e: 
		print('Error: {}'.format(e))
		if need_send_email:
			send_email(.....)		
```

I am calling the script by Window's task manager (cmd /c), and after `session.logger.info('Finish')` I could see also the "session end" message in log file.
I haven't changed anything in my script since a lot of time, so I suppose that is not script related. I don't know. 
May be "session.end()" doesn't close properly ?

But after that, I can see the cmd windows still open (as "cmd /c python ..." doesnt finish), chrome closed, but still in task manager using 99% of cpu.

I don't know where to start to get more information about this problem. It seems to be related with chrome driver (2.40v), Chrome (last version) or  ......

Any clue?
Thanks

**Comment by sionking** [comment]
I suffered a lot from this in Windows.
You should turn off the no-sandbox option for chrome (why we need it ?)

**Comment by ortegafernando** [comment]
> I suffered a lot from this in Windows.
You should turn off the no-sandbox option for chrome (why we need it ?)

Hi, I can't find sandbox option in chrome. I have found these settings that may be related to.. 

Continue running background apps when Google Chrome is closed: is ON by default
Use hardware acceleration when available: is ON by default

May be any of two is related to ?

Thanks a lot

**Comment by sionking** [comment]
in the code at __init__ there are chrome pref comment the line for sandbox:
file: instapy.py

**Comment by ortegafernando** [comment]
Hi @sionking , in instapy.py I have this:

```
chromedriver_location = Settings.chromedriver_location
chrome_options = Options()
#chrome_options.add_argument("--disable-infobars")
chrome_options.add_argument("--mute-audio")
chrome_options.add_argument('--dns-prefetch-disable')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--lang=en-US')
chrome_options.add_argument('--disable-setuid-sandbox')
```

What you say is to change to this, don't you?: 

```
chromedriver_location = Settings.chromedriver_location
chrome_options = Options()
#chrome_options.add_argument("--disable-infobars")
chrome_options.add_argument("--mute-audio")
chrome_options.add_argument('--dns-prefetch-disable')
#chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--lang=en-US')
chrome_options.add_argument('--disable-setuid-sandbox')
```

Or this one?:

```
chromedriver_location = Settings.chromedriver_location
chrome_options = Options()
#chrome_options.add_argument("--disable-infobars")
chrome_options.add_argument("--mute-audio")
chrome_options.add_argument('--dns-prefetch-disable')
#chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--lang=en-US')
#chrome_options.add_argument('--disable-setuid-sandbox')
```

Hope your answer

Best regards,

**Comment by ortegafernando** [comment]
I want to add some info.

Here say also to remove no-sandbox option: [https://github.com/SeleniumHQ/selenium/issues/5600](https://github.com/SeleniumHQ/selenium/issues/5600)

May be we have to do change instapy source code, does this change affect ?

**Comment by sionking** [comment]
chromedriver_location = Settings.chromedriver_location
chrome_options = Options()
#chrome_options.add_argument("--disable-infobars")
chrome_options.add_argument("--mute-audio")
chrome_options.add_argument('--dns-prefetch-disable')
#chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--lang=en-US')
#chrome_options.add_argument('--disable-setuid-sandbox')

**Comment by sionking** [comment]
I suffered for days !

**Comment by ortegafernando** [comment]
Ok, I will try and write again in a few days. Thanks a lot.

**Comment by ortegafernando** [comment]
Hi, I have check with this:

```
            chromedriver_location = Settings.chromedriver_location
            chrome_options = Options()
            #chrome_options.add_argument("--disable-infobars")
            chrome_options.add_argument("--mute-audio")
            chrome_options.add_argument('--dns-prefetch-disable')
            #chrome_options.add_argument('--no-sandbox')
            chrome_options.add_argument('--lang=en-US')
            chrome_options.add_argument('--disable-setuid-sandbox')
```

And now it works perfectly, it closes cmd and chrome.

I am going to do a pull request. I don't now exactly if it affects to other OS.

Regards,

**Comment by xvx29a** [comment]
You can not straight up disable the sandbox option or you need to do some sort of check here for windows.  This breaks headless browsers on linux and stops Instapy from running.

**Comment by douwevandermeij** [comment]
I agree with @xvx29a, it also broke my script. Please revert (or better: fix). For example put a boolean for the option in Settings class.

**Comment by douwevandermeij** [comment]
See my PR https://github.com/timgrossmann/InstaPy/pull/2363
