### ISSUE TITLE
Simulated-follow reports the new followers as if they have been followed previously

### ISSUE THREAD

**Issue by nadavdrukker** [InstaPy/InstaPy#2323]
## Expected Behavior

Should not report for every simulated follow "user already been followed more than 1 times" even if they were not in the followRestriction file.

## Current Behavior

Here it picked up two users, one followed previously and one not. It followed only the second, but then reported that it has bee followed previously (though it probably wasn't since I cannot find it n a my backup of my followRestriction file).

INFO [2018-06-26 20:21:05] []  User 'xxxxxx' [1/1]
INFO [2018-06-26 20:21:12] []  Simulated follow : 1
INFO [2018-06-26 20:21:12] []  Not followed 'pottery.of.insta'  ~inappropriate user
INFO [2018-06-26 20:21:12] []  Simulated follow : 1
INFO [2018-06-26 20:21:13] []  --> Followed annies_pots

INFO [2018-06-26 20:21:17] []  Grabbed 7 usernames from xxxx's `Followers` to do following.
INFO [2018-06-26 20:21:17] []  User 'annies_pots' [1/7]
INFO [2018-06-26 20:21:21] []  User: annies_pots >> followers: 104  |  following: 283  |  relationship ratio: 0.37
INFO [2018-06-26 20:21:21] []  User: annies_pots >> followers: 104  |  following: 283  |  relationship ratio: 0.37
INFO [2018-06-26 20:21:21] []  ---> annies_pots has already been followed more than 1 times

The script did not follow the first one, but did follow the second, though it shouldn't have, and didn't even subsequently unfollow it.

## Possible Solution (optional)

Maybe make simulated following optional?

If not, treat all the simulated following in one batch after the simulation, stating that they are the simulated follows that are now verified that they should indeed be followed. And remove the "has already been followed more than 1 times" log.

Another alternative, since the purpose of simulated follow is to justify scrolling through the list. Why not just forgo the simulation and from the scrolling click on the last grabbed user and follow it from its profile (if it matches the criteria). This is a very natural behaviour when you scroll down a list, to find one user, go to its profile and interact with it.

## IinstaPy Configuration

It was a follow from user's followers loop. I cannot simulate it and don't know why one user in my followRestriction was not followed and another was (and many others were also followed in other loops).

## Comment

To me this feature introduces an immense complexity to the code and subsequently such bugs. All this extra randomisation is excessive to me. There are so many easy ways for IG to detect us if they wanted. They know that we load pages that are not linked to each other. No human types 100s of URLs into a browser Window. No human remembers 100s of users that he requested to follow but they never appeared on his following list. I'm terrified like everybody else that IG will shut us down, but the reason they don't is not because they cannot catch us, it's because they don't care. We generate a lot of traffic and activity on IG and users don't complain too much about our activities to prompt IG to act. So my advice: keep it simple.

And please introduce a kill switch for simulated follow.

**Comment by nadavdrukker** [comment]
I know that I can set self.simulation=False in instapy.py, but I think this should not require changing the code.

**Comment by sionking** [comment]
I do agree with the comment.
