### ISSUE TITLE
Rapidly removing users from followedPool without unfollowing them

### ISSUE THREAD

**Issue by therealahall** [InstaPy/InstaPy#2325]
## Expected Behavior
Users being removed from the following pool are actually unfollowed
## Current Behavior
Large swaths of the followedPool.csv file are being removed without actually unfollowing the users
## Possible Solution (optional)
I've tried manually re-inserting the users following the same format the others are in, but they get swept up and removed again without unfollowing.  Grepping for their username in all of the log files show them in the record_all_followed.csv, followRestriction.json, and general.log
## InstaPy configuration

session.unfollow_users(amount=500, InstapyFollowed=(True, "all"), style='FIFO', sleep_delay=600, unfollow_after=72*60*60)

## Example log
In this example I was still following two of these users, but the others were unfollowed

INFO [2018-06-27 06:51:57] [<my_username>]  --> Removed '2018-06-25 18:29 ~ guypanet' from followedPool.csv file
INFO [2018-06-27 06:51:57] [<my_username>]  --> Removed '2018-06-25 19:07 ~ houcine_out' from followedPool.csv file
INFO [2018-06-27 06:51:57] [<my_username>]  --> Removed '2018-06-25 20:04 ~ ghayhurst' from followedPool.csv file
INFO [2018-06-27 06:51:57] [<my_username>]  --> Removed '2018-06-25 20:23 ~ syrin_faust' from followedPool.csv file

This differs from the normal logs such as:
INFO [2018-06-27 06:32:15] [<my_username>]  --> Ongoing Unfollow From InstaPy 112/500, now unfollowing: mattsuessphoto
INFO [2018-06-27 06:32:15] [<my_username>]  --> Removed '2018-05-09 15:53 ~ mattsuessphoto' from followedPool.csv file

**Comment by therealahall** [comment]
Looking at the individual accounts that it is not unfollowing, I cannot find a common thread among them.

Followed on different dates/times
Mix of private vs public accounts
Mix of high follower/following count and low follower/following count

**Comment by CharlesCCC** [comment]
this might realated with the unfollow confirmation dialog that is pop-up from time to time.

you should keep you eyes on the browser while the instapy is dong it unfollowing work.

**Comment by therealahall** [comment]
Yeah I have been. It goes from one user, to the next, then it removes the group of users without even loading them in the browser and moved on to the next one after the group that was removed.

**Comment by therealahall** [comment]
It appears that the list of users that it is removing are users that were entered in multiple times somehow.  It is still concerning the way it displays that, but it appears to be attempting to unfollow those users eventually as time passes.  Closing for now.
