### ISSUE TITLE
comment only one time per user

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#2326]
Hi, it is possible to not post multiple comment to the same user ?
i would like to just post a comment to a user only one time.

Can you help me with the conf ?

Thanks.

```
session.set_comments(['hi :)','wow','lol'])
session.set_do_comment(enabled=True, percentage=10)
...
session.set_user_interact(amount=1, randomize=True, percentage=100, media='Photo')
session.set_do_follow(enabled=True, percentage=100)
session.set_comments(['hi :)','wow','lol'])
session.set_do_comment(enabled=True, percentage=100)
session.interact_user_followers(['therock','elonmusk'], amount=20, randomize=True)
```

**Comment by redsector72** [comment]
Yes, there is the blacklist feature.
session.set_blacklist(enabled=True, campaign='onlyonce')

**Comment by ghost** [comment]
@redsector72 thank you so much , i will try it.

**Comment by yxorp** [comment]
> Yes, there is the blacklist feature.
> session.set_blacklist(enabled=True, campaign='onlyonce')

this is not in the documentation? I also could not find it in the code.

**Comment by jravouna** [comment]
Im gonna need this feature as well.
Any news on this command @yxorp ?
Does it work ?

**Comment by yxorp** [comment]
@jravouna Yes it does, the campaign is an arbitrary string that is used to identify accounts followed in a particular campaign.
