### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by nadavdrukker** [InstaPy/InstaPy#2330]
## Expected Behavior

Is there any work-around to prevent it from crashing, or older version that is stable?

## Current Behavior

This happens about twice a day:
INFO [2018-06-29 03:46:11] []  ---> Now following: amyjstoddard
INFO [2018-06-29 03:46:17] []  Follow [7/20]  |  Total Follow: 7
INFO [2018-06-29 03:46:17] []  User 'lagorradelafro' [9/20]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-06-29 03:47:10] [nadavdrukker]  Session ended - 2018-06-29 03:47:10
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "follow.py", line 90, in <module>
    session.follow_user_followers([source[0]], amount=source[1], sleep_delay=slowness*400)
  File "/instapy.py", line 2068, in follow_user_followers
    followed = self.follow_by_list(person, self.follow_times, sleep_delay, interact)
  File "/instapy.py", line 690, in follow_by_list
    self.logger)
  File "/util.py", line 77, in validate_username
    followers_count, following_count = get_relationship_counts(browser, username, logger)
  File "/util.py", line 513, in get_relationship_counts
    "//span[contains(@class,'g47SY')]")[1].text))
IndexError: list index out of range

## InstaPy configuration

        session.set_relationship_bounds(enabled=True,
				 potency_ratio=None,
				  delimit_by_numbers=True,
				   max_followers=10000,
				    max_following=2000,
				     min_followers=5,
				      min_following=5)
        session.follow_user_followers(xxxx, amount=20, sleep_delay=600)

**Comment by pedromoto4** [comment]
Same problem here :/

**Comment by Floflokiki** [comment]
On **util.py** file, replace:
```
followers_count = format_number((browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")[1].text))
```
With:
```
topCount_elements = browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")
if topCount_elements:
    followers_count = format_number(topCount_elements[1].text)
else:
    logger.error("Failed to get followers count of '{}'  ~empty list".format(username))
    followers_count = None
```
And, replace:
```
following_count = format_number(browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")[2].text)
```
With:
```
topCount_elements = browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")
if topCount_elements:
    following_count = format_number(topCount_elements[2].text)
else:
    logger.error("Failed to get following count of '{}'  ~empty list".format(username))
    following_count = None
```

On **unfollow_util.py** file, replace :
```
allfollowers = format_number((browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")[1].text))
```
With:
```
topCount_elements = browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")
if topCount_elements:
    allfollowers = format_number(topCount_elements[1].text)
else:
    logger.error("Error occured during getting the followers count of '{}'  ~empty list".format(username))
    allfollowers = None
```
And replace:
```
allfollowing = format_number((browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")[2].text))
```
With:
```
topCount_elements = browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")
if topCount_elements:
    allfollowing = format_number(topCount_elements[2].text)
else:
    logger.error("Error occured during getting the following count of '{}'  ~empty list".format(username))
    allfollowing = None
```

Hope it helps!
Based on @uluQulu proposal!
