### ISSUE TITLE
Feature Request: Do not exceed a certain like and/or comment limit

### ISSUE THREAD

**Issue by the-unknown** [InstaPy/InstaPy#2331]
## WHAT
I am suggesting, to implement an absolute limit for likes and comments which will not be exceeded within 24h

## WHY
Instagram has a like and comment limit per day (24h) which a user should not exceed. Otherwise the user will be blocked for the exceeded action and can not comment or like anymore until the block has been removed. 
With the current implementation, it is hard to keep track on how many posts have been liked or commented, which can lead to a block in one of these functions easily. For example: I added a few more hashtags to comment and like on, but forgot to adjust the amount of posts to comment on per hashtag. As an result, I got banned on commenting for 24h. 

## HOW
Let the user define a like/comment limit inside the quickstart.py
The bot will track the number of posts which have been liked and commented on and will not exceed this given limit. 
e.g: 
session.set_like_limit(1000)
session.set_comment_limit(200)

## WHAT
The result would be a better control of likes and comments and prevents Instagram from blocking an account.

**Comment by c0d3x27** [comment]
isnt this implemented by default already? thats what it say in the home page here

**Comment by MrBeardedGuy** [comment]
Yes it has been merged see... #2771
