### ISSUE TITLE
Feature Request: Follow/Like Requirements based on Bio

### ISSUE THREAD

**Issue by Nuzzo235** [InstaPy/InstaPy#2333]
## Current Behavior

Search only possible for description and owner comments

##Why

By checking the bio, you can get a precise classification of other "professionals" among a large number of fans. 

##How

.set_profile_requirements searches the profile info for buzzwords and only like images and/or follow the user if one of those buzzwords are in there

session.set_profile_requirements(['#artist', '[painter', ']artist', 'painter'])

##What

Sally is a painter and wants to connect with other artists. The Museum of Modern Art has milion of subscribers, among which are many artists. Sally wants to check every fan, but wants to follow only "real" artists, so she's looking for profiles of people who call themselves artists.

Cheers

**Comment by sionking** [comment]
I will try commit my work

**Comment by Nuzzo235** [comment]
Thank you @sionking ! Looking forward, but no hurry!

**Comment by Nuzzo235** [comment]
@sionking Have you found some time to work on that topic? Best, Nuzzo

**Comment by raulafrosa** [comment]
This will be an amazing feature.
I'm trying to build for myself but don't have experience in Phyton.

In my case, I want to exclude people with specific words in the bio.
Now, I'm using dont_like but it only looks for hashtags and in pictures, not in the bio.

**Comment by ghost** [comment]
yes i think will be better to implement it here:

https://github.com/timgrossmann/InstaPy/pull/2242

**Comment by Nuzzo235** [comment]
@ilmetu @raulrosa89 I'd like to see the "Skip private users"-feature merged to the master as it is now. I would rather expand the two methods "Mandatory Words" and "Restricting Likes" to something like this:

`session.set_mandatory_words(post=['#exactmatch', '[startswith'], bio=[']endswith', 'broadmatch'])`
and
`session.set_banned_words(post=['#exactmatch', '[startswith'], bio=[']endswith', 'broadmatch'])`

An additional AND & OR Option would be superb, but I think that @InfinityWebMe is already looking for a solution.

Cheers

**Comment by papillon-unix** [comment]
Would be very important to get this option : selecting/excluding acconts based on bio.
please!
