### ISSUE TITLE
Not working on private users: browser.find_element_by_xpath("//a[contains(@href,'followers')]/span").text

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2334]
Can someone find a solution ?

Thanks.

**Comment by drewscott** [comment]
I've got the same issue

**Comment by sionking** [comment]
any selenium-web guy to fix ?
We look for **link** while private users don't have links.

**Comment by jeremycjang** [comment]
@sionking Are you referring to not being able to see the users of a private account that you are not following? Because this is disallowed by Instagram by default.
