### ISSUE TITLE
[Feature Request] Don't increment count of follow/like/comment when the bot skips a post

### ISSUE THREAD

**Issue by archit-p** [InstaPy/InstaPy#2338]
## What?
Currently when you set a pre-defined number of likes/follows you're looking for, the bot doesn't always get the exact number since a lot of posts are skipped due to not meeting the relationship constraints set. This can be an issue when the relationship constraints are very narrow and specific.

## How?
I think should be an easy fix, by changing the line where the count is being incremented.

## Why?
Changing this behavior would result in better control over the number of likes/follows, and also reduce the number of dry runs when very few likes/follows are made.

**Comment by mexusbg** [comment]
+1

**Comment by archit-p** [comment]
I think this is an easy change. Any reasons preventing its inclusion?

**Comment by KingKorSin** [comment]
I thinks this should be implemented all over the bot, and not only with likes and followers but also with interactions, and it should be merged after this pull request : https://github.com/timgrossmann/InstaPy/pull/2242

I just looked into this a bit and found out it's not as easy as just changing the line for the count, this requires a bit of refactoring to the counts in the bot.
Now we have several counts that are not related to each other, for example the amount of users to interact with that you take from another user is based on your configured number, so if you try to create a set amount of interactions you will need to get an unknown number of users from the base user. 

This may be easier in terms of like_by_tags and like_by_locations and so on, but not on the interaction functions.

**Comment by LotusPainter** [comment]
@timgrossmann  Any thoughts on this? It is quite important for me and I believe many others that prefer to have very niche relationship rules and also what to specify the amount accurately.

**Comment by Xelanor** [comment]
I think this feature might be very important. For example; I set the follow amount as 10 but with heavy relationship bounds it just follows 1 maybe even 0 and sleep for the rest of the hour. 

If the counter increases as it is actually followed it will be much more useful.

Thanks.
