### ISSUE TITLE
follow specific account's followers

### ISSUE THREAD

**Issue by aliajoudanian** [InstaPy/InstaPy#234]
I want to get follow back from specific account's followers

**Following by a list**
```
#would be useful for the precise targeting. For example, if one needs to get followbacks from followers of a chosen account/group of accounts.
```

It would be great if we have a method to follow the specific amount of last followers automatically.

**Comment by tibor** [comment]
Hi,

you can’t get the followers of a specific account since Instagram has no list available in the web version.

With the following by a list feature you can only specify a list of instagram accounts you’d like to follow. InstaPy will then follow them for you while probably staying in the limits from Instagram.

You may also want to read #197 where this feature was discussed already.

**Comment by aliajoudanian** [comment]
@tibor Hi, Recently followers and following lists are available in the web version. In web version if you click on amount of followers in profile page you redirect to ~/followers url and you can see users in a modal box.

**Comment by mattdeveluk** [comment]
This one is must have !

**Comment by atomhax** [comment]
@aliajoudanian I can do this. I just want to make sure we flesh out the feature completely. Do we need to set a limit to how people the bot will follow before it takes a break or do we let it run until it finishes following all of the targeted user's followers.

**Comment by aliajoudanian** [comment]
@atomhax In my idea set a limitation is better. like as Like by tag

> like_by_tags(['dog', '#cat'], amount=100)\

Maybe user wants to follow/unfollow user and if there isn't any limitation it caused a problem.

**Comment by AlexBGoode** [comment]
I would also like to confirm here that the feature of following of the followers of the specified account would be really useful! 
As for now, the method follow_by_list() just follows specified accounts straight forward meanwhile its description sound to me much more promising and making me believe that all followers of the specified accounts would be followed according to available  restrictions

**Comment by tyler601** [comment]
im wondering if you got this feature working ?

**Comment by timgrossmann** [comment]
@tyler601 Why not? The question is not if, but when someone finds the time to do it 😉

**Comment by smallredcape** [comment]
Hi guys - any update on this feature? In my experience with bots, this is by far the most successful way to attract more followers. I'd love to find a way to impliment this into the script!

**Comment by timgrossmann** [comment]
#477

**Comment by ASMRcode** [comment]
is there a way to have multiple accounts follow one specific account? I dont know if this community is still active or not
