### ISSUE TITLE
Hi Guys This my error   "//span[contains(@class,'g47SY')]")[1].text))

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#2340]
Traceback (most recent call last):
  File "start.py", line 46, in <module>
    session.follow_user_followers(['tiboinshape','jujufitcats','justinegallice','stanimal9','antonao','carolineclnfit', 'fitbyclem','chloe_fit_','mmjhottie','__bigwill__'], amount=10, randomize=True, interact=True, sleep_delay=260)
  File "/Users/jonathanverdier/Desktop/Alpha/instapy/instapy.py", line 2059, in follow_user_followers
    self.logger)
  File "/Users/jonathanverdier/Desktop/Alpha/instapy/util.py", line 77, in validate_username
    followers_count, following_count = get_relationship_counts(browser, username, logger)
  File "/Users/jonathanverdier/Desktop/Alpha/instapy/util.py", line 513, in get_relationship_counts
    "//span[contains(@class,'g47SY')]")[1].text))
IndexError: list index out of range

**Comment by DarkSilence** [comment]
Have the same issue sometime :(

**Comment by Floflokiki** [comment]
On **util.py** file, replace:
```
followers_count = format_number((browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")[1].text))
```
With:
```
topCount_elements = browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")
if topCount_elements:
    followers_count = format_number(topCount_elements[1].text)
else:
    logger.error("Failed to get followers count of '{}'  ~empty list".format(username))
    followers_count = None
```
And, replace:
```
following_count = format_number(browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")[2].text)
```
With:
```
topCount_elements = browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")
if topCount_elements:
    following_count = format_number(topCount_elements[2].text)
else:
    logger.error("Failed to get following count of '{}'  ~empty list".format(username))
    following_count = None
```

On **unfollow_util.py** file, replace :
```
allfollowers = format_number((browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")[1].text))
```
With:
```
topCount_elements = browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")
if topCount_elements:
    allfollowers = format_number(topCount_elements[1].text)
else:
    logger.error("Error occured during getting the followers count of '{}'  ~empty list".format(username))
    allfollowers = None
```
And replace:
```
allfollowing = format_number((browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")[2].text))
```
With:
```
topCount_elements = browser.find_elements_by_xpath(
    "//span[contains(@class,'g47SY')]")
if topCount_elements:
    allfollowing = format_number(topCount_elements[2].text)
else:
    logger.error("Error occured during getting the following count of '{}'  ~empty list".format(username))
    allfollowing = None
```

Hope it helps!
Based on @uluQulu proposal!

**Comment by uluQulu** [comment]
Thanks for spreading the code around, @Floflokiki 😁🎉🎉🎉
One thing you have missed, the _username_ variable in **unfollow_util.py** file should `user_name` rather than `username`.
Cheers 😁

**Comment by Floflokiki** [comment]
Many thanks for your help, I've done the "username" change. Hope it works fine now!
Thanks again @uluQulu
