### ISSUE TITLE
Unfollow instapyfollowed doesn't deleting users in csv file

### ISSUE THREAD

**Issue by dule91sd** [InstaPy/InstaPy#2342]
## Expected Behavior
When I call function unfollow_users, function starting to unfollow user from followedPool.csv and it should be delete unfollowed user from this csv file.
## Current Behavior
But when I call second time the same function, function starting to unfollow the same users from beginning which is pointless. It should be start unfollowing new users.
## Possible Solution (optional)
How to setup instapy to be sure that unfollowed users will be deleted from followedPool.csv file.
## InstaPy configuration
session.unfollow_users(amount=200, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=345600, sleep_delay=480)

**Comment by sionking** [comment]
plesase add log

**Comment by texmex44** [comment]
I think it's normal ! That prevent it avoids to follow / unfollow all the time the same Instagram account.

**Comment by dule91sd** [comment]
@texmex44 I think it's not because that is prevented whith this line of code:
session.set_do_follow(enabled= True, percentage= 100, times= 1)
So you can follow only once users.

@sionking 

NFO [2018-07-01 17:29:20] []  Total 7318 users available to unfollow  ~didn't pass `unfollow_after`: 3508

INFO [2018-07-01 17:29:30] []  --> Ongoing Unfollow From InstaPy 1/200, now unfollowing: always_hungry_s
ERROR [2018-07-01 17:30:17] []  --> Unfollow error with , maybe no longer exists...
INFO [2018-07-01 17:30:27] []  --> Ongoing Unfollow From InstaPy 2/200, now unfollowing: a.kaca9
ERROR [2018-07-01 17:31:13] []  --> Unfollow error with , maybe no longer exists...



INFO [2018-07-01 18:16:51] []  Starting to unfollow users..
INFO [2018-07-01 18:16:53] []  Unfollowing the users followed by InstaPy

INFO [2018-07-01 18:16:58] []  Total 7318 users available to unfollow  ~didn't pass `unfollow_after`: 3508

WARNING [2018-07-01 18:17:05] []  --> Cannot Unfollow From InstaPy 0, maybe always_hungry_s was unfollowed before...
ERROR [2018-07-01 18:17:39] []  --> Unfollow error with , maybe no longer exists...
WARNING [2018-07-01 18:17:45] []  --> Cannot Unfollow From InstaPy 0, maybe a.kaca9 was unfollowed before...
ERROR [2018-07-01 18:18:18] []  --> Unfollow error with , maybe no longer exists...
WARNING [2018-07-01 18:18:27] []  --> Cannot Unfollow From InstaPy 0, maybe a.daca82 was unfollowed before...
ERROR [2018-07-01 18:19:01] []  --> Unfollow error with , maybe no longer exists...
WARNING [2018-07-01 18:19:09] []  --> Cannot Unfollow From InstaPy 0, maybe tasi.02 was unfollowed before...
ERROR [2018-07-01 18:19:43] []  --> Unfollow error with , maybe no longer exists...
WARNING [2018-07-01 18:19:49] []  --> Cannot Unfollow From InstaPy 0, maybe adnankatkic1234 was unfollowed before...
ERROR [2018-07-01 18:20:22] []  --> Unfollow error with , maybe no longer exists...
WARNING [2018-07-01 18:20:28] []  --> Cannot Unfollow From InstaPy 0, maybe gicicmelissa was unfollowed before...
ERROR [2018-07-01 18:21:02] []  --> Unfollow error with , maybe no longer exists...
INFO [2018-07-01 18:21:14] []  --> Ongoing Unfollow From InstaPy 1/200, now unfollowing: trenerke_povoljno
ERROR [2018-07-01 18:22:04] []  --> Unfollow error with , maybe no longer exists...
INFO [2018-07-01 18:22:15] []  --> Ongoing Unfollow From InstaPy 2/200, now unfollowing: smuncan_00
ERROR [2018-07-01 18:23:03] []  --> Unfollow error with , maybe no longer exists...
INFO [2018-07-01 18:23:14] []  --> Ongoing Unfollow From InstaPy 3/200, now unfollowing: bikovic__
ERROR [2018-07-01 18:23:59] []  --> Unfollow error with , maybe no longer exists...
WARNING [2018-07-01 18:24:05] []  --> Cannot Unfollow From InstaPy 3, maybe bozana94 was unfollowed before...
ERROR [2018-07-01 18:24:38] []  --> Unfollow error with , maybe no longer exists...
INFO [2018-07-01 18:24:49] []  --> Ongoing Unfollow From InstaPy 4/200, now unfollowing: sabickaa_35
ERROR [2018-07-01 18:25:33] []  --> Unfollow error with , maybe no longer exists...
ERROR [2018-07-01 18:26:01] []  --> Unfollow error with kiki_bursac_mihajlovic97, maybe no longer exists...

**Comment by ximhotep** [comment]
@dule91sd I'm still testing the long term impact of this change but if you add 

delete_line_from_file('{0}{1}_followedPool.csv'.format(logfolder, username),
                                              person + ",\n", logger)

after line 275 in unfollow_util.py it will remove the entries from followedPool.csv  

What I was seeing was a large number of accounts that were deleted from IG and every time I would run an unfollow it would start at the beginning and cycle through these accounts because I was using FIFO and these entries weren't being removed.

**Comment by dule91sd** [comment]
@ximhotep 

I added this line and it's working but now i have another problem.
Each time when i call unfollow onlyinstapyfollowed i got this log:
INFO [2018-07-04 22:25:09] []  Unfollowing the users followed by InstaPy

INFO [2018-07-04 22:25:16] []  Total 4546 users available to unfollow  ~didn't pass `unfollow_after`: 3480

WARNING [2018-07-04 22:25:27] []  --> Cannot Unfollow From InstaPy 0, maybe always_hungry_s was unfollowed before...

WARNING [2018-07-04 22:25:35] []  --> Cannot Unfollow From InstaPy 0, maybe a.kaca9 was unfollowed before...

WARNING [2018-07-04 22:25:44] []  --> Cannot Unfollow From InstaPy 0, maybe a.daca82 was unfollowed before...

WARNING [2018-07-04 22:25:55] []  --> Cannot Unfollow From InstaPy 0, maybe tasi.02 was unfollowed before...

WARNING [2018-07-04 22:26:04] []  --> Cannot Unfollow From InstaPy 0, maybe adnankatkic1234 was unfollowed before...

WARNING [2018-07-04 22:26:12] []  --> Cannot Unfollow From InstaPy 0, maybe gicicmelissa was unfollowed before...

WARNING [2018-07-04 22:26:21] []  --> Cannot Unfollow From InstaPy 0, maybe trenerke_povoljno was unfollowed before...

WARNING [2018-07-04 22:26:29] []  --> Cannot Unfollow From InstaPy 0, maybe smuncan_00 was unfollowed before...

Whatching the code after **logger.warning** in line 336 it writes **delete_line_from_file** but it seems that it's not working. I don't get it.

**Comment by dule91sd** [comment]
Can anyone help me with this issue?
It seems that the line 336 delete_line_from_file it's not working and that is a reason why each time when I call function **unfollowing user** starting to unfollow the same users from begging of followedPool.csv.

**Comment by ximhotep** [comment]
@dule91sd Try my changes https://github.com/ximhotep/InstaPy/blob/master/instapy/unfollow_util.py, line 90 is probably what you need.

**Comment by dule91sd** [comment]
@ximhotep  I'm afraid that the function **delete_line_from_file** doesn't working. That is problem.
When you see the following code:

   
```
delete_line_from_file('{0}{1}_followedPool.csv'.format(logfolder, username),
                                              person + ",\n", logger)
# save any unfollowed person
log_record_all_unfollowed(username, person, logger, logfolder)

 logger.warning( "--> Cannot Unfollow From InstaPy {}"
                            ", maybe {} was unfollowed before..."
                            .format(str(unfollowNum), person.encode('utf-8')))

delete_line_from_file('{0}{1}_followedPool.csv'.format(logfolder, username),
                                              person + ",\n", logger)
```

When logger writes for example:
**Cannot Unfollow From InstaPy 0, maybe always_hungry_s was unfollowed before...**
After that it has to delete that user from line in **followedpool.csv** but it doesn't happen.
I'm running on raspberry Pi.
Could you help me with this problem?

**Comment by ximhotep** [comment]
Give PR #2402 a try.  @sionking made some changes to my PR.  See if that works for you.

**Comment by dule91sd** [comment]
I made some changes in the code and I proved that I 'm right. Function **delete_line_from_file** doesn't working.
Code:
```
logger.warning("line 330")
delete_line_from_file('{0}{1}_followedPool.csv'.format(logfolder, username),
                                              person + ",\n", logger)
# save any unfollowed person
log_record_all_unfollowed(username, person, logger, logfolder)
logger.warning("line 335")
logger.warning(
                            "--> Cannot Unfollow From InstaPy {}"
                            ", maybe {} was unfollowed before..."
                            .format(str(unfollowNum), person.encode('utf-8')))
logger.warning("line 340")
delete_line_from_file('{0}{1}_followedPool.csv'.format(logfolder, username),
                                              person + ",\n", logger)
                        
                        
logger.warning("line 345")
```
Logger:
```
WARNING [2018-07-10 08:35:35] []  line 330
WARNING [2018-07-10 08:35:35] []  line 335
WARNING [2018-07-10 08:35:35] []  --> Cannot Unfollow From InstaPy 0, maybe always_hungry_s was unfollowed before...
WARNING [2018-07-10 08:35:35] []  line 340
WARNING [2018-07-10 08:35:35] []  line 345

WARNING [2018-07-10 08:35:40] []  line 330
WARNING [2018-07-10 08:35:40] []  line 335
WARNING [2018-07-10 08:35:40] []  --> Cannot Unfollow From InstaPy 0, maybe a.kaca9 was unfollowed before...
WARNING [2018-07-10 08:35:40] []  line 340
WARNING [2018-07-10 08:35:40] []  line 345

WARNING [2018-07-10 08:35:47] []  line 330
WARNING [2018-07-10 08:35:47] []  line 335
WARNING [2018-07-10 08:35:47] []  --> Cannot Unfollow From InstaPy 0, maybe a.daca82 was unfollowed before...
WARNING [2018-07-10 08:35:47] []  line 340
WARNING [2018-07-10 08:35:47] []  line 345

WARNING [2018-07-10 08:35:55] []  line 330
WARNING [2018-07-10 08:35:55] []  line 335
WARNING [2018-07-10 08:35:55] []  --> Cannot Unfollow From InstaPy 0, maybe tasi.02 was unfollowed before...
WARNING [2018-07-10 08:35:55] []  line 340
WARNING [2018-07-10 08:35:55] []  line 345


```

**Comment by dule91sd** [comment]
@ximhotep 
I updated right know on my RaspberryPi and still nothing, it's not working **delete_line_from_line**
Whay is that? What is a problem?
Logger:
```
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-07-17 18:37:11] []  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo


.......................................................................
INFO [2018-07-17 18:37:58] []  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-07-17 18:38:18] []  --> _a10del_22.1_
 instagram account is opened...
INFO [2018-07-17 18:38:31] []  ---> Now following: _a10del_22.1_

INFO [2018-07-17 18:38:35] []  Total Follow: 1
INFO [2018-07-17 18:38:39] []  --> andjela.kostadinovic
 instagram account is opened...
INFO [2018-07-17 18:38:52] []  ---> Now following: andjela.kostadinovic

INFO [2018-07-17 18:38:58] []  Total Follow: 2
INFO [2018-07-17 18:39:02] []  --> a._.angeloski
 instagram account is opened...
WARNING [2018-07-17 18:39:36] []  ---> a._.angeloski
 is already followed
INFO [2018-07-17 18:39:45] []  --> milenkoracic
 instagram account is opened...
WARNING [2018-07-17 18:40:18] []  ---> milenkoracic
 is already followed
INFO [2018-07-17 18:40:30] []  --> ivagosnjicc
 instagram account is opened...
INFO [2018-07-17 18:40:38] []  ---> Now following: ivagosnjicc

INFO [2018-07-17 18:40:42] []  Total Follow: 3
INFO [2018-07-17 18:40:49] []  --> sladjan.ikonic
 instagram account is opened...
INFO [2018-07-17 18:41:04] []  ---> Now following: sladjan.ikonic

INFO [2018-07-17 18:41:08] []  Total Follow: 4
INFO [2018-07-17 18:41:17] []  --> __anjamilojkovic
 instagram account is opened...
INFO [2018-07-17 18:41:32] []  ---> Now following: __anjamilojkovic

INFO [2018-07-17 18:41:37] []  Total Follow: 5
INFO [2018-07-17 18:41:41] []  --> tijaanaa_06
 instagram account is opened...
WARNING [2018-07-17 18:42:16] []  ---> tijaanaa_06
 is already followed
INFO [2018-07-17 18:42:29] []  --> aidaibro_
 instagram account is opened...
INFO [2018-07-17 18:42:41] []  ---> Now following: aidaibro_

INFO [2018-07-17 18:42:47] []  Total Follow: 6
INFO [2018-07-17 18:42:55] []  --> _minecraft_12345678910
 instagram account is opened...
INFO [2018-07-17 18:43:06] []  ---> Now following: _minecraft_12345678910

INFO [2018-07-17 18:43:10] []  Total Follow: 7
INFO [2018-07-17 18:43:16] []  --> betmen_u_penziji
 instagram account is opened...
INFO [2018-07-17 18:43:27] []  ---> Now following: betmen_u_penziji

INFO [2018-07-17 18:43:31] []  Total Follow: 8
INFO [2018-07-17 18:43:39] []  --> milos_tomic91
 instagram account is opened...
INFO [2018-07-17 18:43:55] []  ---> Now following: milos_tomic91

INFO [2018-07-17 18:44:00] []  Total Follow: 9
INFO [2018-07-17 18:44:12] []  --> nemanja_babic05
 instagram account is opened...
INFO [2018-07-17 18:44:25] []  ---> Now following: nemanja_babic05

INFO [2018-07-17 18:44:31] []  Total Follow: 10
INFO [2018-07-17 18:44:31] []  Followed 10 new users  ~sleeping about 1.0 minutes


OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-07-17 18:46:08] []  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo


.......................................................................
INFO [2018-07-17 18:46:56] []  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

____________________________________________________________________________
INFO [2018-07-17 18:47:11] []  Starting to unfollow users..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-07-17 18:47:14] []  There are less users to unfollow than you have requested:  8/200  ~using available amount

INFO [2018-07-17 18:47:14] []  Unfollowing the users followed by InstaPy

INFO [2018-07-17 18:47:14] []  Total 20 users available to unfollow  ~didn't pass `unfollow_after`: 0

INFO [2018-07-17 18:47:31] []  --> Ongoing Unfollow From InstaPy 1/8, now unfollowing: _a10del_22.1_

ERROR [2018-07-17 18:48:18] []  --> Unfollow error with , maybe no longer exists...
WARNING [2018-07-17 18:48:18] []  --> Cannot Unfollow From InstaPy 1, maybe  was unfollowed before...
INFO [2018-07-17 18:48:18] []  	Removed '' from followedPool.csv file
INFO [2018-07-17 18:48:18] []  	Removed '' from followedPool.csv file
INFO [2018-07-17 18:48:18] []  	Removed '' from followedPool.csv file
INFO [2018-07-17 18:48:18] []  	Removed '' from followedPool.csv file
INFO [2018-07-17 18:48:18] []  	Removed '' from followedPool.csv file
INFO [2018-07-17 18:48:18] []  	Removed '' from followedPool.csv file
INFO [2018-07-17 18:48:18] []  	Removed '' from followedPool.csv file
INFO [2018-07-17 18:48:18] []  	Removed '' from followedPool.csv file
INFO [2018-07-17 18:48:18] []  	Removed '' from followedPool.csv file
INFO [2018-07-17 18:48:18] []  	Removed '' from followedPool.csv file

INFO [2018-07-17 18:48:39] []  --> Ongoing Unfollow From InstaPy 2/8, now unfollowing: andjela.kostadinovic

ERROR [2018-07-17 18:49:26] []  --> Unfollow error with , maybe no longer exists...
WARNING [2018-07-17 18:49:27] []  --> Cannot Unfollow From InstaPy 2, maybe  was unfollowed before...

INFO [2018-07-17 18:49:46] []  --> Ongoing Unfollow From InstaPy 3/8, now unfollowing: ivagosnjicc

ERROR [2018-07-17 18:50:36] []  --> Unfollow error with , maybe no longer exists...
WARNING [2018-07-17 18:50:36] []  --> Cannot Unfollow From InstaPy 3, maybe  was unfollowed before...

INFO [2018-07-17 18:50:54] []  --> Ongoing Unfollow From InstaPy 4/8, now unfollowing: sladjan.ikonic

ERROR [2018-07-17 18:51:43] []  --> Unfollow error with , maybe no longer exists...
WARNING [2018-07-17 18:51:43] []  --> Cannot Unfollow From InstaPy 4, maybe  was unfollowed before...

INFO [2018-07-17 18:52:08] []  --> Ongoing Unfollow From InstaPy 5/8, now unfollowing: __anjamilojkovic

ERROR [2018-07-17 18:53:00] []  --> Unfollow error with , maybe no longer exists...
WARNING [2018-07-17 18:53:01] []  --> Cannot Unfollow From InstaPy 5, maybe  was unfollowed before...

INFO [2018-07-17 18:53:50] []  --> Ongoing Unfollow From InstaPy 6/8, now unfollowing: aidaibro_

ERROR [2018-07-17 18:54:43] []  --> Unfollow error with , maybe no longer exists...
WARNING [2018-07-17 18:54:43] []  --> Cannot Unfollow From InstaPy 6, maybe  was unfollowed before...

INFO [2018-07-17 18:55:09] []  --> Ongoing Unfollow From InstaPy 7/8, now unfollowing: _minecraft_12345678910

ERROR [2018-07-17 18:55:56] []  --> Unfollow error with , maybe no longer exists...
WARNING [2018-07-17 18:55:56] []  --> Cannot Unfollow From InstaPy 7, maybe  was unfollowed before...

INFO [2018-07-17 18:56:25] []  --> Ongoing Unfollow From InstaPy 8/8, now unfollowing: betmen_u_penziji

WARNING [2018-07-17 18:56:41] []  --> Total unfollows reached it's amount given 8

INFO [2018-07-17 18:56:41] []  --> Total people unfollowed : 8
```

**Comment by jp-sjc** [comment]
@ximhotep nice, worked for me, ty so much.
