### ISSUE TITLE
--> Invalid Like Element! Randomly New issue

### ISSUE THREAD

**Issue by ajankuv** [InstaPy/InstaPy#2343]
## Expected Behavior
Like the Photo as normal

## Current Behavior
--> Invalid Like Element!

## InstaPy configuration
Simple like photo on hashtag

This has been working for about 2 weeks now. Randomly today it just stopped working. It's not the account as it happens on more then one when testing.

**Comment by marcomokastyle** [comment]
@ajankuv seems that is changed the xpath, i'm trying right now with these new ones in like_util.py on like_image func.

    like_xpath = "//button/span[text()='Like']/.."
    unlike_xpath = "//button/span[text()='Unlike']"
	
    # fetch spans fast
    spans = [x.text.lower() for x in browser.find_elements_by_xpath("//article//button/span")]

**Comment by ajankuv** [comment]
@marcomokastyle bingo that fixed it, thanks!
