### ISSUE TITLE
--> Invalid Like Element!

### ISSUE THREAD

**Issue by HansDaigle** [InstaPy/InstaPy#2344]
## Expected Behavior
--> Image Liked!
## Current Behavior
--> Invalid Like Element!
## Possible Solution (optional)
Replace the xpaths with these one in the like_util.py like_image function: 

```
def like_image(browser, username, blacklist, logger, logfolder):
...
    like_xpath = "//article//button[contains(@class, 'Heart')]/span[text()='Like']/.."
    unlike_xpath = "//article//button[contains(@class, 'Heart')]/span[text()='Unlike']/.."
    spans = [x.text.lower() for x in browser.find_elements_by_xpath("//article//button[contains(@class, 'Heart')]/span")]
...
```

**Comment by marcomokastyle** [comment]
@HansDaigle is working also with this

    like_xpath = "//button/span[text()='Like']/.."
    unlike_xpath = "//button/span[text()='Unlike']"
	
    # fetch spans fast
    spans = [x.text.lower() for x in browser.find_elements_by_xpath("//article//button/span")]

**Comment by Tachenz** [comment]
Yep, gettin  this one as well

**Comment by ArdyBeheshti** [comment]
Me as well.

**Comment by dbmathis** [comment]
Same

**Comment by Mehran** [comment]
Same for me Today .

**Comment by ArdyBeheshti** [comment]
@HansDaigle this guy has the right solution!! Thank you!

def like_image(browser, username, blacklist, logger, logfolder):
...
    like_xpath = "//article//button[contains(@class, 'Heart')]/span[text()='Like']/.."
    unlike_xpath = "//article//button[contains(@class, 'Heart')]/span[text()='Unlike']/.."
    spans = [x.text.lower() for x in browser.find_elements_by_xpath("//article//button[contains(@class, 'Heart')]/span")]
...

Putting that in the like_util.py is the right solution.

**Comment by CodeDem** [comment]
@HansDaigle  Thanks man it's working again, please raise a PR for this.

**Comment by sionking** [comment]
Works

**Comment by monkeymars** [comment]
@HansDaigle Works!

**Comment by CharlesCCC** [comment]
@ArdyBeheshti  great job, can you PR that ?

**Comment by HansDaigle** [comment]
It's already in [master](https://github.com/timgrossmann/InstaPy/commit/c3a63b18b7d848ae7a904b1294cf885d7602f7a0) guys 👍!

**Comment by misskbar** [comment]
It isn't working for me when the post is a collection
