### ISSUE TITLE
selenium error, unable to install

### ISSUE THREAD

**Issue by baaswietse** [InstaPy/InstaPy#2349]
Hi,

I am using windows10 and the latest version of instapy (3 July 2018)

after following these 4 steps with succes I can't run the quickstart.py:
1. git clone https://github.com/timgrossmann/InstaPy.git
2. cd InstaPy
3. python setup.py install
4. Download chromedriver for your system from here. Extract the .zip file and put it in /assets folder.

When I run the quickstart.py I get the error:
_Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    from selenium.common.exceptions import NoSuchElementException
ModuleNotFoundError: No module named 'selenium'_

So I tried to install selenium with the pip command and get the error:
_Requirement already satisfied: selenium in c:\users\wietse 
delclef\appdata\local\programs\python\python37-32\lib\site-packages\selenium-2.53.6-py3.7.egg (2.53.6)
clarifai 2.0.32 requires configparser==3.5.0, which is not installed.
clarifai 2.0.32 requires enum34==1.1.6, which is not installed.
clarifai 2.0.32 requires future==0.15.2, which is not installed.
clarifai 2.0.32 requires jsonschema==2.5.1, which is not installed.
clarifai 2.0.32 has requirement Pillow==2.9.0, but you'll have pillow 5.2.0 which is incompatible.
clarifai 2.0.32 has requirement requests==2.13.0, but you'll have requests 2.19.1 which is incompatible._

I already did some research on the internet but couldn't find anyone with the same problem, so I hope someone will be able to help me here. 
Thanks a lot

**Comment by frankpitale** [comment]
me too, there are some youtube video abou, but not so clear in this process.
