### ISSUE TITLE
droplet ram size issue

### ISSUE THREAD

**Issue by ericxor61a0c0d** [InstaPy/InstaPy#235]
This is how I set up my quickstart
`while(True):
	InstaPy(username="blah",password="blah",nogui=True)\
	  .login()\
	  .set_upper_follower_count(limit = 2500) \
	  .set_do_comment(True, percentage=10) \
	  .set_comments(['Beautiful!', 'This is gold!', 'This is amazing!']) \
	  .set_dont_include(friend_list) \
	  .set_dont_like(dont_like) \
	  .set_ignore_if_contains(ignore_words) \
	  .like_by_tags(['travel','nyc','dogs','photography','hype'], amount=160) \
	  .end()
	time.sleep(60*60*10)
	`
But after I check in after a while, the docker container is gone, not stopped. I can't see what caused the script to stop because the container is killed, no logs are preserved.

**Comment by TheRealJAG** [comment]
@ericchenmelt was it a memory issue?

**Comment by ericxor61a0c0d** [comment]
@TheRealJAG I have a server with 1gb ram, most likely not. I'm suspecting that the CPU had issue because the droplet was running at 120%

**Comment by TheRealJAG** [comment]
@ericchenmelt maybe the process isn't closing and the process hangs causing CPU #'s to spike. Why are you in a while? Can you run it on a hourly process so you don't kill the server?

**Comment by calebfornari** [comment]
@ericchenmelt @TheRealJAG I tested this with docker on Digital Ocean 512MB and 1 GB droplets, it doesn't work on either of them. It's working fine now on a server with 2GB memory.

**Comment by thenayr** [comment]
If you run a `docker ps -a` what is the status of that container that is no longer running? 

You can also run a `docker logs $container-id` to get the log output from a non running container.

**Comment by alvinlee123** [comment]
running in the same issue. I have a droplet running on 512MB that's just getting hammered. The issue has to do with selenium and chrome driver. You can try switching to firefox or getting more ram like what caleb suggested.

**Comment by sdiepend** [comment]
I'm guessing you're running it on a dedicated droplet? Why run in it in Docker? just run it on your vm using crontab to run it every x time.
