### ISSUE TITLE
everything works, only liking on like_by_tags does not work

### ISSUE THREAD

**Issue by Florenz23** [InstaPy/InstaPy#2351]
## Current Behavior
Everything was working very fine in the first session, next session, liking stopped working

## InstaPy configuration
self.session.set_do_comment(enabled=True,
                                        percentage=100)
            self.session.set_comments(commentData)
self.session.like_by_tags(instaHashtagData,
                                          amount=15,
                                          media='Photo')
self.session.follow_by_tags(instaHashtagData, amount=40)
used:
comment_by_tag
like_by_tag
Actions per hour, (10 hours per day)
follow: 40
comments:15
likes:15

**Comment by HansDaigle** [comment]
It's fix now, you should git pull `master`.
