### ISSUE TITLE
Bot can't like and self aborting

### ISSUE THREAD

**Issue by spikeyhair** [InstaPy/InstaPy#2353]
## Expected Behavior

Like and comment

## Current Behavior
It was running fine until few hours back. I notice "Invalid Like Element!". I updated with the latest like_util.py from here but still couldn't work. Anyone facing the same issue? I also notice a lot of "self aborting prevented".

What does "self aborting prevented" means? Why this warning message?

I also notice no more commenting even tho i have been running the bots for a few hours.

**Comment by GabrieleCalarota** [comment]
same here
