### ISSUE TITLE
Unfollow Users leads to incorrect 'ERROR: Username might be blocked' message

### ISSUE THREAD

**Issue by archit-p** [InstaPy/InstaPy#2355]
## Expected Behavior
Adding this line
```python
session.unfollow_users(amount=10, nonFollowers=True, style="FIFO", unfollow_after=20*60*60, sleep_delay=655)
```
should ideally unfollow users.
## Current Behavior
Unfollow doesn't occur, instead an error saying 'Username <username> might be blocked'. This error isn't correct because I can unfollow users through the mobile app and web browser without any trouble.
## Possible Solution (optional)
Investigating the website revealed that instagram now has popups when you click on 'Following', and the bot needs to click on 'Unfollow' in order to unfollow the user. Since this second click isn't present in the code the error message is displayed. 
This can be fixed by adding a few lines of code. I've made a fix locally however, not sure if it meets the coding style guidelines here.
https://github.com/archit-p/InstaPy/blob/master/instapy/unfollow_util.py

**Comment by kwstasna** [comment]
I get the same error message with the following code

`session.unfollow_users(amount=5000, InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=48*60*60, sleep_delay=501)`

Even though i'm not blocked

**Comment by archit-p** [comment]
@kwstasna Yes the issue isn't with users being blocked, even though I was worried of that. The issue is that Instagram's layout has changed.

**Comment by dbmathis** [comment]
@archit-p your link doesn't work for me.

**Comment by alxhoff** [comment]
am also getting the same error

**Comment by joanroig** [comment]
Same issue here, I've tried this: https://github.com/timgrossmann/InstaPy/pull/2345
Works, but after some unfollows it says the same error

**Comment by ximhotep** [comment]
@joanroig Change sleep(1) to sleep(5) from #2345.  I was getting through 3 unfollows before it was crashing, but if I single stepped through the code it was working fine.  Adding the additional delay seems to fixed the issue.

**Comment by joanroig** [comment]
@ximhotep Which one of all sleep(1)? I can see three in changes, thanks in advance!
Edit: tried changing all of them and works like a charm, thanks

**Comment by spikeyhair** [comment]
I am getting this error:
Traceback (most recent call last):
  File "quickstart_verify.py", line 7, in <module>
    from instapy import InstaPy
  File "D:\Dropbox\Instapy\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "D:\Dropbox\Instapy\instapy\instapy.py", line 42, in <module>
    from .unfollow_util import get_given_user_followers
  File "D:\Dropbox\Instapy\instapy\unfollow_util.py", line 286
    except Exception,e:
                    ^
SyntaxError: invalid syntax

**Comment by cormo1990** [comment]
i can't find where edit the sleep time..can you show me please? thanks in advance

**Comment by ortegafernando** [comment]
Could you merge this to master branch ?

EDIT: Thanks, I have seen that this error is already merged. Thanks.

**Comment by alxhoff** [comment]
i tried #2345 but to no effect. Still getting the same error

**Comment by Techie-Inc** [comment]
@alxhoff see my original fix for this issue relating to the sleep fix in thread [#2346](https://github.com/timgrossmann/InstaPy/issues/2346) working 100% for me in several instances. The sleep time will depend on the speed of your internet connection to IG from the server. For me 4 seconds worked, some people never even experienced the issue with default of 1 second. Parameter varies per server.

**Comment by ghost** [comment]
see my pr https://github.com/timgrossmann/InstaPy/pull/2364

**Comment by Techie-Inc** [comment]
@ilmetu thanks for adding the pr.

**Comment by spikeyhair** [comment]
This is strange, I tested on 2 accounts, it works on 1st acc but couldn't work on 2nd account. Anyone facing the same issue?

1st acc: unfollowed 1st user, second user start giving "user might be blocked"
2nd acc: can unfollow all the amount of users I specify without throwing "user might be blocked" error.

Anyone facing the same issue?

**Comment by archit-p** [comment]
This seems to be fixed by #2364. I made the change manually to my code and it worked fine. Thanks for the PR @ilmetu.

**Comment by archit-p** [comment]
@dbmathis Sorry had to delete the repo when i realized my username and password was exposed.

**Comment by spikeyhair** [comment]
I fixed the code manually as suggested in #2364 as well, that's why the 2nd acc can unfollow without the error but it is strange my 1st account can only unfollow the 1st user, second user onwards throw this error and the unfollow process is terminated (didn't try to continue).

**Comment by archit-p** [comment]
@spikeyhair I'm not sure why that behavior is occurring. No issues as such on my side. It is working fine since the last ~20 hours.

**Comment by spikeyhair** [comment]
Thanks, I will let it run for a few hours again, then see what's the outcome.
