### ISSUE TITLE
My Bot is skipping everything...

### ISSUE THREAD

**Issue by tolgaada** [InstaPy/InstaPy#2357]
## Expected Behavior
It worked just fine but then within 40 mins it changed.
## Current Behavior
 ....   is not a massive follower with the relationship ratio of 0.06  ~skipping user
Now it is skipping everybody and everything. Not doing anything
## InstaPy configuration

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.21,
				  delimit_by_numbers=True,
				   max_followers=99999,
				    max_following=99999,
				     min_followers=45,
				      min_following=22)

    session.follow_likers (['reflectionsmn' ,'schecterguitarsofficial', 'j4r3dd1n3s', 'robscallon', 'steventerreberry', 'deathcore.memes' 'polyphia'], photos_grab_amount = 10, follow_likers_per_photo = 10, randomize=True, sleep_delay=60, interact=True)
    session.set_do_follow(enabled=True, percentage=50, times=2)
    session.set_do_comment(enabled=True, percentage=30)
    session.set_comments(['talent!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like([])

    # actions
    session.follow_user_followers(['j4r3dd1n3s' , 'robscallon', 'steventerreberry', 'reflectionsmn',], amount=10, randomize=False)
    session.like_by_tags(["deathcore", "djent",], amount=5)
    session.follow_by_tags(['deathcore','guitar', 'djent', 'thall'], amount=10)
except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

**Comment by HansDaigle** [comment]
Are you sure it's skipping everything? Your potency_ratio is negative (-1.21) which is pretty rare. You should try to set your potency_ratio=0.80 and see what happen.

Good luck!

**Comment by tolgaada** [comment]
Hi thanks for the reply. Could you tell me where to change the ratio?

**Comment by HansDaigle** [comment]
Of course, here :
```
session.set_relationship_bounds(enabled=True,
			 potency_ratio=-1.21,                     <--- change to 0.80 or a positive value
			 delimit_by_numbers=True,
			 max_followers=99999,
			 max_following=99999,
			 min_followers=45,
			 min_following=22)
```

**Comment by tolgaada** [comment]
I don't know why, but the Bot is still skipping about 90% of every user

**Comment by HansDaigle** [comment]
Before the `~skipping user` the log will always tell you why the user was skipped.

**Comment by tolgaada** [comment]
This is the line im getting:
_info.cc(164)] Display::DrawAndSwap, LatencyInfo vector size 102 is too big.
INFO [2018-07-04 06:20:27] [user]  User: user >> followers: 7577  |  following: 19  |  relationship ratio: 398.79
Not a valid user: User user's following count is less than minimum limit  ~skipping user

**Comment by HansDaigle** [comment]
So if you read the error you can see that you are filtering user with a low following count.
```
session.set_relationship_bounds(enabled=True,
			 potency_ratio=0.80,                    
			 delimit_by_numbers=True,         #<--- =False will ignore min, max limit below
			 max_followers=99999,
			 max_following=99999,
			 min_followers=45,                       #<--- Mine is set to 45
			 min_following=22)                       #<--- Mine is also set to 45
```

**Comment by tolgaada** [comment]
Hmm thanks. But it is still the same issue :/

**Comment by tolgaada** [comment]
It's working now! Thank you sooo much :)

**Comment by HansDaigle** [comment]
Can you close the issue :) ?
