### ISSUE TITLE
Is there any way to run the bot without open that chrome tab?

### ISSUE THREAD

**Issue by tuliosousapro** [InstaPy/InstaPy#2360]
## Current Behavior
Is there any way to run the bot without open that chrome tab?

**Comment by ccozkan** [comment]
like running headless?

**Comment by tuliosousapro** [comment]
Yes

**Comment by tuliosousapro** [comment]
Only viewing the prompt and saving some RAM

**Comment by ccozkan** [comment]
https://github.com/timgrossmann/InstaPy#running-on-a-headless-browser

**Comment by tuliosousapro** [comment]
Thank You ozkc
