### ISSUE TITLE
Is like Element in instagram changed. Instapy is giving "Invalid Like Element" from last 24 hours.

### ISSUE THREAD

**Issue by MrDebashis** [InstaPy/InstaPy#2367]

**Comment by ghost** [comment]
please update the master:

`git pull origin master`

**Comment by MrDebashis** [comment]
Thanks for reply. But is there any changes for ChromeDriver. Even if chromedriver is in assets dir, and chmod with 755, its strill giving error for chromedriver with error message "ensure chromedriver is installed at /home/debas/InstaPy/assets/chromedriver"

Please guide

**Comment by ghost** [comment]
please uncomment:

`chrome_options.add_argument('--no-sandbox')`

in your instapy.py

**Comment by MrDebashis** [comment]
This worked. Thanks a lot :)
