### ISSUE TITLE
In current code, how does clarifai skip tags? is this right? 

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#2368]
## Expected Behavior

to skip tags, my configuration is below but im not sure if it fully works. is this correct? 
## InstaPy configuration
```
session.set_use_clarifai(enabled=True, api_key='whatever my api key is')
session.clarifai_check_img_for(['tags i want to comment on'], comment=True, comments=['my comments'])
session.clarifai_check_img_for(['tag i want to skip'])
```

is this wrong?

**Comment by sionking** [comment]
tags: man
skip_tags: woman
image1: man - > skipped
image2: woman -> Ok
image3:  man and woman -> Ok

**Comment by ghost** [comment]
thats in future implementation right? what about current implementation @sionking? 

session.set_use_clarifai(enabled=True, api_key='whatever my api key is')
session.clarifai_check_img_for(['woman'], comment=True, comments=['my comments'])
session.clarifai_check_img_for(['man'])

does this do  what your above comment says? ^

**Comment by sionking** [comment]
current ....
