### ISSUE TITLE
Unfollows instead of following 

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#2375]
I downloaded the latest master pull and updated chromedriver and my bot runs fine but it is not following on my account like i am shadow-banned but can still follow on phone...

How to troubleshoot my bot not following and not throwing error ?!

**Comment by archit-p** [comment]
Could you visit Instagram on your browser and try to follow?  If you're seeing any popups then it might be an issue with the layout. 

A screenshot or more info would be appreciated!
