### ISSUE TITLE
Feature request: send welcome DM to new followers

### ISSUE THREAD

**Issue by theRouter** [InstaPy/InstaPy#2380]
## Expected Behavior
hi
I want to send DM to new followers. can anybody help me?

**Comment by penandlim** [comment]
You can't send Direct Messages on Web version of Instagram so this is not possible with InstaPy unless Instagram decides to implement new DM features for Web.

I suggest you to look for private APIs.

**Comment by joshuachinemezu** [comment]
> ## Expected Behavior
> hi
> I want to send DM to new followers. can anybody help me?
> 
> ## Current Behavior
> ## Possible Solution (optional)
> ## InstaPy configuration

Using this https://github.com/timgrossmann/InstaPy/issues/4496#issuecomment-497947408, you can run the web driver from an Android Browser thus having access to features which are not available on the desktop web version of instagram. Planning on creating a pull request for my solution to this issue.

**Comment by MCilento93** [comment]
Actually now you can send messages from ig Web

**Comment by ashikbanjade** [comment]
is there an update on this request? can we get this feature somehow?
