### ISSUE TITLE
session.follow_likers is not working in last two days

### ISSUE THREAD

**Issue by daliborg** [InstaPy/InstaPy#2383]
## Current Behavior

Initially script starts working, log in, move to specified user, open the like dialog and get the likers to follow.
Then it starts following users but after few users it just freezes and then crashes. At the same time when it's crashed I see in chrome page with the message: "Sorry, this page isn't available.
I am attaching terminal log, as well as the screenshot. I've tried it several times, with several users and it's always the same. I also tried to change interact setting from true to false but that did not help as well.
If you need any more info/details/check please let me know.

## InstaPy configuration

```
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-0.7)

    session.set_dont_like(['porn', 'butik'])
    session.set_ignore_users(['angela_vjencanice'])
	
    session.set_user_interact(amount=5, randomize=True, percentage=70, media='Photo')
    #Follow 
    session.follow_likers(['markodvetackev'], photos_grab_amount = 12, follow_likers_per_photo = 50, randomize=True, sleep_delay=600, interact=False)

  except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

  finally:
    # end the bot session
    session.end()
```

[instapy_log_git_report.txt](https://github.com/timgrossmann/InstaPy/files/2168070/instapy_log_git_report.txt)
![instapy_log_screenshot](https://user-images.githubusercontent.com/39854462/42345486-c4ffc7f0-809f-11e8-850c-94f9d84684d1.png)

**Comment by SPQRBrutus** [comment]
I have same problem with follow_user_followers. Accounts I followed have me blocked

**Comment by daliborg** [comment]
It's not the case here.
I've checked the users from the list and none of them blocked me.
