### ISSUE TITLE
unfollow users never seems to work with the code 

### ISSUE THREAD

**Issue by Rupchand** [InstaPy/InstaPy#2387]
## Expected Behavior
unfollow users
## Current Behavior
does not unfollow users with the given code

**Comment by kiankji** [comment]
+1

**Comment by HaimBendanan** [comment]
+1

**Comment by abeledovictor** [comment]
Add this `else statement` to `if` at line 286 in file **/unfollow_util.py**

```
                        else:
                            try:
                                browser.find_element_by_xpath("//button[text()='Unfollow']").click()
                                unfollowNum += 1
                                sleep_counter += 1

                                update_activity('unfollows')

                                if person in relationship_data[username]["all_following"]:
                                    relationship_data[username]["all_following"].remove(person)

                                logger.info(
                                    '--> Ongoing Unfollow From InstaPy {}/{},'
                                    ' now unfollowing: {}'
                                    .format(str(unfollowNum), amount, person.encode('utf-8')))

                                delete_line_from_file('{0}{1}_followedPool.csv'.format(logfolder, username), person +
                                                ",\n", logger)

                                print('')
                                sleep(15)
                            except:
                                logger.error("Unfollow error!  ~username {} might be blocked\n".format(username))
                                # stop the loop
                                break
```

**Comment by MikeLewin** [comment]
I'm not sure if it's anything to do with this, but I just found I can't unfollow anyone because IG has put an ajax popup 'confirm unfollow' box now.
The class of unfollow is 'aOOlW -Cab_'    I am going to try and figure this out for myself, but I'm still a noob when it comes to Python.

**Comment by abeledovictor** [comment]
@MikeLewin you’re right. Check the function at unfollow_util. Code posted above adresses instagram’s update. You can replace the entire if statement with the code I posted. I added it as an else to the existing if just in case, because I’m new to python and was the first time I saw the code from this repo

**Comment by MikeLewin** [comment]
I saw that snippet but can't figure out where it's supposed to go.  
To me line 286 looks like the middle of the routine.  
286 is between 
           unfollowNum % 10 == 0):    
and
           print('sleeping for about {}min'

**Comment by abeledovictor** [comment]
Yeah, you're right, it was a bit confusing.

Here is a gist of the whole unfollow routine with modifications:
[unfollow routine gist](https://gist.github.com/abeledovictor/160eab16cf691cc157b3296806540d2d)

Fix starts at line ```216``` of the gist and ends at ```240```

**Comment by MikeLewin** [comment]
replaced the whole routine, now getting 'syntax error: return outside function'..  for the 'return unfollowNum' last line

**Comment by MikeLewin** [comment]
in but on running it bombs out immediately after going to my page with:
 unfollow() missing 3 required positional arguments 'sleep_delay', 'logger' and 'logfolder'

**Comment by MikeLewin** [comment]
I had to manually edit it and the snippet is in the correct place,  but not clicking the confirmation 'unfollow'
I'll wait for the final version.
