### ISSUE TITLE
Problem with comments

### ISSUE THREAD

**Issue by gushtas** [InstaPy/InstaPy#2388]
Hello

When i activate comments on the InstaPy GUI i get error:

Error: INFO [2018-07-06 18:52:36] [cadouri_unicate] Session started!
 INFO [2018-07-06 18:53:19] [cadouri_unicate] Logged in successfully!
 Traceback (most recent call last):
 File "quickstart.py", line 9, in <module>
 session.set_comments([uHey.Thephotolooksgreatfollow@1234567], media='Photo')
 NameError: name 'uHey' is not defined

ANY HELP? PLEASE

**Comment by HansDaigle** [comment]
You are missing the quotes, comment are str objects, you should do :+1: 
```
session.set_comments([u"Hey.Thephotolooksgreatfollow@1234567"], media='Photo')
```
