### ISSUE TITLE
Commenting question

### ISSUE THREAD

**Issue by TheRealJAG** [InstaPy/InstaPy#239]
Is there a check that prevents a photo from being commented on more than once? A user would comment multiple times on the same photo.

**Comment by TheRealJAG** [comment]
I just confirmed it will comment multiple times on a photo.

**Comment by timgrossmann** [comment]
@TheRealJAG It won't...
Once the photo is liked, it will not comment on it again...

Are you sure your "Liking" is still working?
Or are you temporarily banned from liking? Then you actually should stop the script until you're unbanned

**Comment by TheRealJAG** [comment]
@timgrossmann I was seeing multiple comments on images when I ran the re-ran the process on the same tag(s), but I'm not sure if I unliked them in testing. I will keep an eye on it over the next couple of days.

**Comment by timgrossmann** [comment]
@TheRealJAG Any updates ?

**Comment by TheRealJAG** [comment]
@timgrossmann I haven't had time to mess around lately. Maybe this weekend. I'll keep you posted.

**Comment by TheRealJAG** [comment]
@timgrossmann just a thought... If I was running 2 tags that are similar and have matching images, does your script check to see if a tag comments on X user or is it user defined? This might be where the duplicates are coming from...

**Comment by timgrossmann** [comment]
@TheRealJAG It will only comment if the image is not yet liked. This is defined in the code, so there can't be any exceptions.

Only if you've been banned from liking and the actual like was removed because you're not allowed to like anymore...
