### ISSUE TITLE
error while unfollowing

### ISSUE THREAD

**Issue by riccardorighettiphoto** [InstaPy/InstaPy#2390]
Hello,
since the last update, I get this error while trying to unfollow:

`INFO [2018-07-07 02:00:38] [my_username]  Total 162 users available to unfollow  ~didn't pass unfollow_after: 214
ERROR [2018-07-07 02:00:44] [my_username]  Unfollow error!  ~username my_username might be blocked`

In the quickstart I have this code about unfollowing:
`session.unfollow_users(amount=20, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=168*60*60, sleep_delay=600)`

Could you help me please? Thank you. Bye.

**Comment by sionking** [comment]
Do you run from server ip ?

**Comment by abeledovictor** [comment]
Add this `else statement` to `if` at line 286 in file **/unfollow_util.py**

```
                        else:
                            try:
                                browser.find_element_by_xpath("//button[text()='Unfollow']").click()
                                unfollowNum += 1
                                sleep_counter += 1

                                update_activity('unfollows')

                                if person in relationship_data[username]["all_following"]:
                                    relationship_data[username]["all_following"].remove(person)

                                logger.info(
                                    '--> Ongoing Unfollow From InstaPy {}/{},'
                                    ' now unfollowing: {}'
                                    .format(str(unfollowNum), amount, person.encode('utf-8')))

                                delete_line_from_file('{0}{1}_followedPool.csv'.format(logfolder, username), person +
                                                ",\n", logger)

                                print('')
                                sleep(15)
                            except:
                                logger.error("Unfollow error!  ~username {} might be blocked\n".format(username))
                                # stop the loop
                                break
```

**Comment by sionking** [comment]
Can you explain?

**Comment by abeledovictor** [comment]
@sionking Instagram now prompts a modal with a cancel and unfollow button when you try to unfollow someone. The code I posted just makes selenium click the button inside that modal. I added an else to the if statement in line 286 just not to break anything, but I think you can replace the entire if with the try/except code I posted above

Here is a gist of the whole unfollow routine with modifications:
[unfollow routine gist](https://gist.github.com/abeledovictor/160eab16cf691cc157b3296806540d2d)

Fix starts at line ```216``` of the gist and ends at ```240```
