### ISSUE TITLE
Expecting ':' delimiter: line 1 column 213179 (char 213178)

### ISSUE THREAD

**Issue by smhjamalii** [InstaPy/InstaPy#2391]
## Expected Behavior
I run python3.6 quickstart.py and get this behaviour : 

## Current Behavior
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/home/git/InstaPy/instapy/instapy.py", line 132, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "/home/git/InstaPy/instapy/unfollow_util.py", line 978, in load_follow_restriction
    return json.load(followResFile)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 213179 (char 213178)

## InstaPy configuration
README normal configuration

**Comment by marcomokastyle** [comment]
@smhjamali check the file "followRestriction.json" in your log folder, it seems that is corrupted. the correct syntax for JSON is:
{"username": 1, "username": 1, "username": 1, "username": 1}
 
where 1 is just for example, is the parameter times of set_do_follow.

The error says that is missing a ":" so check where, and correct it. Check also if is correctly terminated by "}"
I think probably the error is at the end of the file. Maybe was truncated so is missing the final part.
If some data was lost, you can restore it manually from followedPool, is a little bit annoying but is possible.

**Comment by ortegafernando** [comment]
work for me.  Thanks.
