### ISSUE TITLE
Warning: Comment Button Not Found

### ISSUE THREAD

**Issue by coreyallen-dop** [InstaPy/InstaPy#2392]
## Expected Behavior
Expecting InstaPy to comment on an image according to session parameters. 
## Current Behavior
InstaPy is returning the following message, "Warning: Comment Button Not Found: May cause issues with browser windows of smaller widths". Likes and follows appear to be working fine, just not comments. 
## InstaPy configuration
Currently running InstaPy on RPI3, headless with the latest commit and chrome driver updated.

**Comment by anuragbjain** [comment]
Hi @austinallen01 
I had the same issue (i run with the browser in the background), a quick fix is to reduce the zoom level of the browser to <80%. It will fix the comments. 

Hope this helps.

**Comment by guillaumeteillet** [comment]
I have the same issue as you, I am running it on a Ubuntu server so I can't reduce the zoom level :(

**Comment by MikeLewin** [comment]
I can confirm this.  
Readjusting zoom level did nothing..
I have also tried with a couple of different versions of Chromedriver (2.36 fixed it before)
With this, and the like button, and the unfollow modal, they've been busy recently..  :(

**Comment by MikeLewin** [comment]
@guillaumeteillet
Try this:
in comment_util.py   find   open_comment_section(browser):
under     comment_elem = browser.find_elements_by_xpath(         change
"//a[@role='button']/span[text()='Comment']/..")
to
"//button/span[text()='Comment']/..")

this now works for me

**Comment by MikeLewin** [comment]
@guillaumeteillet and @austinallen01 
Try this:
in comment_util.py   
find  -  
open_comment_section(browser):

under  -   
comment_elem = browser.find_elements_by_xpath(    

change
"//a[@role='button']/span[text()='Comment']/..") 
to
"//button/span[text()='Comment']/..")

Hope it helps :)

**Comment by marcomokastyle** [comment]
change the line in comment_util.py:
```python
comment_elem = browser.find_elements_by_xpath(
        "//button/span[text()='Comment']/..")
```

**Comment by MikeLewin** [comment]
LOL, that's what I said.. :)

**Comment by jeremycjang** [comment]
@MikeLewin @marcomokastyle Can you confirm that your updated ```xpath``` works when running without GUI? My applied fix was to change the ```comment_input``` variable ```xpath``` to the following and run with GUI (since the add a comment input field only appears in the generated source):

```
comment_input = browser.find_elements_by_xpath(
        '//textarea[contains(@placeholder,"Add a comment…")]')
```
Which works because there's only one ```placeholder``` attribute containing that value lol

**Comment by kushpvo** [comment]
I'm getting the same error on RPi3B+

**Comment by jeremycjang** [comment]
@Mikelewin yours works with noGUI then?

**Comment by davidrocket** [comment]
At the current version of instapy, despite having the "Warning ..." shown, the comment is successful posted by instapy!

**Comment by Ninnix** [comment]
I'm getting the same error on RPi3B and firefoxESR
