### ISSUE TITLE
Liking Via Compound Hashtags (e.g., #dogs & #cute, but only when tagged together in the same post)

### ISSUE THREAD

**Issue by webdevandeverythingelse** [InstaPy/InstaPy#2399]
## Expected Behavior
Two hashtags with a space between each other (and not separated by a comma), should result in a compound hashtag, essentially an "AND" operator. This would like photos tagged with both #dogs and #cute, but **not** an image with _only_ #dogs or _only_ #cute. I am using InstaPy GUI.
------------------
![image](https://user-images.githubusercontent.com/14143034/42453554-17c0b91e-835b-11e8-93a2-39e76015f271.png)
------------------
![image](https://user-images.githubusercontent.com/14143034/42453656-653a93a4-835b-11e8-9b49-ec5b14cfebdd.png)

## Current Behavior
The hashtags are combined and the space is stripped out (e.g., #dogs and #cute, only #dogscute is used when the  bot is crawling).

## Possible Solution (optional)
Interpret the space as an "AND" operator, or provide an explicit character to denote a compound hashtag rule.

## InstaPy configuration
Using InstaPy GUI: https://github.com/ahmadudin/electron-instaPy-GUI

**Comment by sionking** [comment]
Please try the hashtag search in IG not combination possiable

**Comment by brb72** [comment]
Hey @sionking, would it be possible to set a "primary" hashtag, which would search Instagram for all those posts - **then** further filter those posts by doing a search in the post's text for certain secondary keywords.

This way you would still only have to search for one hashtag, but wouldn't take action on a post unless it contained one or more of the secondary keywords specified.

Let me know if that makes sense. Thanks!

**Comment by ohio36** [comment]
I actually made this a while back, see https://github.com/timgrossmann/InstaPy/issues/1766. It's a pain in the ass to update the script though after you have made some changes to it that are not adopted into Instapy. I am trying out some new functionality that's available in the new version of Instapy, but not having this functionality is still an issue for me. 

I would still love it if someone could implement this in a neat way and add it to Instapy's code!

/edit: I found a section on mandatory words in the readme of the latest version. That might just be what I need. :)

**Comment by webdevandeverythingelse** [comment]
What functionality are you referring to?

**Comment by ohio36** [comment]
The mandatory words functionality is pretty much what I implemented in https://github.com/timgrossmann/InstaPy/issues/1766. I only think it's too strict, because ALL words have to be in the description. I changed it to ANY and then it works exactly as I like. I will open a new pull request so you can change the strictness of the mandatory words. 

The OP could use the mandatory words to get what he wants (more or less). Only works well of course when your mandatory words are quite common in your selected set of images. Otherwise you will end up not liking most of the images you have selected.
