### ISSUE TITLE
[Request] Compare follow_user_followers to blacklists before pulling links

### ISSUE THREAD

**Issue by jeremycjang** [InstaPy/InstaPy#2408]
The current ```follow_user_followers``` pulls a list account links to follow and then compares them against the blacklist one by one. As a result, there's a high chance you will not follow several users if the account you are getting the followers of is not constantly growing.

This is inefficient for your own page growth (Ex. you want to follow 300 accounts, but InstaPy pulls 200 you've already followed so you only follow 100).

To increase the efficiency of ```follow_user_followers``` when working with blacklists, I believe the blacklist should be compared when the program is first pulling links so that only new user accounts are pulled. The older ```follow_user_followers``` seems to have been able to do this when grabbing accounts from scrolling the list.

Definitely down to pour into the code and figure out how to make this work, I just haven't been able to find what part of the code dictates how and when the blacklist is used with different InstaPy actions!

**Comment by sionking** [comment]
Good luck :)

**Comment by jeremycjang** [comment]
@sionking @timgrossmann Do you know if the legacy ```follow_user_followers``` had code in place that compared usernames to a blacklist while it was gathering follow buttons? I have that code saved but have been unable to find it, though it appeared to only follow new users while a blacklist was ```enabled=True``` every time
