### ISSUE TITLE
Success with nogui or headless?

### ISSUE THREAD

**Issue by andrewjburnett** [InstaPy/InstaPy#2409]
Is anyone experiencing a successful run with either nogui=True or headless_browser=True?

If so, are you using Firefox or Chrome? 

Running multiple instances of this script off a single machine without nogui or headless_brower set to True can be taxing. I'm looking for someone who can point me in the right direction of how to run the script successfully without having to have a GUI or browser open and active.

**Comment by Mehran** [comment]
@andrewjburnett im using    `headless_browser=True`  and  `nogui=True,` with chrome and not have any problem .

**Comment by andrewjburnett** [comment]
@Mehran Thanks. Have you had any issues setting headless_browser=True? When I set either of those true on their own (separately), my scripts fail. I haven't tried together. As far as I understand it, headless browsing is detectable.

Anyone else?

**Comment by sionking** [comment]
Headless don't dl images. Bot

**Comment by andrewjburnett** [comment]
@sionking So headless is not advisable? Have you been able to successfully run using Chrome and nogui=True?
