### ISSUE TITLE
Got blocked

### ISSUE THREAD

**Issue by koni06** [InstaPy/InstaPy#2411]
## Expected Behavior
Script running without block

## Current Behavior
After 2x 24h where the script was running fine, i have been blocked for 24h.
## Possible Solution (optional)
Dont know why?

## InstaPy configuration
Like 5 image in 5 different # every 300 seconds.

**Comment by kushpvo** [comment]
That's about 1440 images liked per day; maybe that's why Instagram blocked you?

**Comment by koni06** [comment]
Yeah, it's maybe too much, but some friend are running the exact same code without and block. Is the limit différent for any users ?

**Comment by andrewjburnett** [comment]
@koni06 The limit is **definitely** different depending on a number of factors, a major one being the age of the account and the general level of activity on the account.

**Comment by jseps** [comment]
how do you know you were blocked?

**Comment by nopariffic** [comment]
Do not run continuously, pause for 4-6 hours per day at a sleep like time. Make sure the script acts irregularly, not always liking, comment, etc the same numbers of accounts, tags, so forth. Use only residential IP addresses. All IG limits scale with account size and an internal rating they use to assess what you are contributing to the platform. From what I can tell they don't actually care if you are using a bot as long as you are contributing real original content and not spamming.

This issue should be closed.
