### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by waseem312** [InstaPy/InstaPy#2412]
I followed the steps on Ubuntu to install InstaPy.On running quickstart.py file i am getting below error:
ModuleNotFoundError: No module named '_sqlite3'

sqlite is already installed on my System still getting the above error.

**Comment by marcomokastyle** [comment]
@waseem312 try sudo apt-get install libsqlite3-dev

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)
