### ISSUE TITLE
unable to unfollow

### ISSUE THREAD

**Issue by jseps** [InstaPy/InstaPy#2414]
## Expected Behavior
Unfollow
## Current Behavior
returns message stating it is unfollowing, but no actual effect on instagram
everything worked great until about 10 days ago
## InstaPy configuration
until roughly 10 days ago I was using
`session.unfollow_users(amount=300, onlyNotFollowMe=True, sleep_delay=60*10)
`
with no issues, but since then the code has been running and saying it's unfollowing but having no actual effect

`session.unfollow_users(amount=30, sleep_delay=450)`
returns
```
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Following']/following-sibling::div"}
(Session info: headless chrome=xx)
(Driver info: chromedriver=2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011),platform=Mac OS X 10.11.6 x86_64)

```

instapy version is 0.1.dev0

**Comment by botpadawan** [comment]
update to latest version of InstaPy, onlyNotFollowMe is not supported in the latest version
