### ISSUE TITLE
Strategies and Results Discussion

### ISSUE THREAD

**Issue by nopariffic** [InstaPy/InstaPy#2416]
An issue maybe isn't the right place for this but I didn't really see another (the wiki doesn't seem that active).

I've been using instapy for about 6-7 months and I feel like the results have been pretty good so far. I run a small business and use an instagram account to promote the things I make and sell in a specific niche. I post twice or more per day, every day. I run instapy every day in multiple sessions that like, comment, follow and unfollow. I am now around 4,000 followers that seem to be pretty organic as people buy my stuff. Throughout the use of instapy I've seem a growth rate that is pretty modest, at the earliest from 5-10 followers per day and now more often 15-30. I'm curious what other peoples experiences have been.

My posts are pretty high quality original content and generate between 1-50 comments depending on what the post is and whether I specifically call out for engagement.

For the past 1-2 months it seems like growth has stalled out at that 15-30 per day mark and I am wondering if it is possible to push that higher?

What strategies work best for organic follower growth? For me in reviewing things overwhelmingly following is the action that produces followers. I then unfollow accounts that don't follow me.

Likes seem to produce little to no following activity. Comments are a mixed bag. I comment a very small percent, 1%, from a set of 25 simple comments. I used to do more but in testing it just doesn't seem to produce results. I use keywords and anti-keywords as carefully as possible but of course there have been whoopsies. The keywords relating to memorials/deaths/accidents, should probably be defaulted as off limits. Saying "fantastic!" to a post where someone is relating the death of a loved one is awful.

Specifics:
Like by tag, 10-15 tags, 25-45 likes per session.
Unfollow 100ish per session
Like 5ish random posts of followers per session
Some specific follow people who are following X
I have never been blocked or shadow banned as far as I am aware. All the activity comes from home IP addresses.

Questions:
How do these results compare to other folks?
It seems like the only thing I could speed up is the overall delays between actions as the bot runs a good portion of the day? With 4000 followers what percentage is safe to increase those speeds?
Are there other types of engagements/actions that people have had success with?

Finally thanks so much to Tim and other contributors, this tool has allowed me to start an almost successful business that I probably couldn't have otherwise.

**Comment by realmane** [comment]
wow that is great, I avg. about 19.1 a day with LifeStyle Content and a wide audience.

**Comment by sionking** [comment]
can you share your keywords (memorials/deaths/accidents)?
15-30 is the average I get for all my X accounts.
10 is kind of not so good.
30 is very good account (don't have a lot more then that)
700 likes a day/ 300 follow / 2 comments (*botty) ~~~
I do use image reco a lot.
I also scrap accounts before use since tags dont have much popularity in my place.

**Comment by sionking** [comment]
I also do analytics once a month to every account, removing non so successful targets.

**Comment by mz462** [comment]
Yeah, likes don't get followers. I usually follow my target account's follower. That gets me around 0.5% follower growth a day. Does anyone know how to avoid following private users?

**Comment by nopariffic** [comment]
With respect to memorial type content I mostly had problems early on. My response was two-fold, I'm in a niche to I expanded the required keywords quite a bit. The exclude tags I use are #rip, #accident, #instamemorials #gonebutneverforgotten #gonetoosoon #pet . Fortunately nothing ever happened with a person's post being liked/commented but with people's pets. Fido died, I'm heart broken --- "that's outstanding!" [like]

So for efficiency then it sounds as though I should cut way back on the likes and up the follow other followers. I will try that. What is "image reco"? Have you altered the default timings at all and if so by what percent speedup?

**Comment by sionking** [comment]
my defaults is 90%. but I sometimes change it to 60-80, if blocked automatic mechanism slow down.
I remove every target that get me less than 1% for followers growth.

BTW, I do likes, maybe you should look at the profile visits not only the follower growth, I think it will be much less without likes. I do have 1000 - 2000 a week on average for 3000-8000 followers account.

**Comment by gitpatrickhub** [comment]
This is great info! I primarily only use Interact_User_Followers to Like 3 posts and Comment on 20%, but have noticed my added followers is minimal ~10/day. I'd like to implement the Follow/Unfollow for those who have not Followed me back features. It would be great to get your strategy @sionking for how you Unfollow, i.e., within same session/quickstart as the Follow interaction or separate session. How many do you unfollow at a time, etc...

**Comment by nopariffic** [comment]
After this discussion I moved to the psuedo-code below. I run it in batches for 1-2 hours at a time. I use a computer at a home internet connection. I use different values than the rand ranges below, you need to set those ranges in proportion to your account size. This has bumped my growth from 10-30 to about 30-50, at least for the past several days. Which is a major improvement. 

By liking less the script is able to follow more, following = followers. I guess I am at the point where I see that everything besides following is just a beard to pace the follow activity. The ongoing small unfollows are also more efficient than the large batch unfollows I was doing before.



tag1,2,3 are the IG tags relevant to your account topic
followtarget1,2,3 is a larger account with a lot of followers relevant to your topic

---

 session.set_comments(['comment1','comment2'])
 session.set_do_comment(True, percentage=1)

session.like_by_tags(['tag1'], amount=random.randint(1,3))
session.follow_user_followers(['followtarget1'], amount=random.randint(2,5), randomize=True)
session.unfollow_users(amount=random.randint(1,4), nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)
session.like_by_tags(['tag2'], amount=random.randint(1,3))
session.follow_user_followers(['followtarget2'], amount=random.randint(2,5), randomize=True)
session.unfollow_users(amount=random.randint(1,4), nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)
session.like_by_tags(['tag3'], amount=random.randint(1,3))
session.follow_user_followers(['followtarget3'], amount=random.randint(2,5), randomize=True)
session.unfollow_users(amount=random.randint(1,4), nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)

...etc

**Comment by marcomokastyle** [comment]
I'm working on my fully automated bot, running on Lubuntu 18.04 on a HP ProBook 4310s (one of my old unused laptops).
I wrote a lot of custom functions, I store almost everything on a MySql database. 
I have a table, with a list of targets, a table where I store all the people i follow plus the source target, I store also all the people skipped, so I can speed up, and clear from the users grabbed from Instapy, all the users already skipped. Thanks to the pretty new relationship tools, I store all my followers, so I can use a query to make stats, like conversion for a target (followbacks/followed).  I also have a table for the white list.
I store followed pool on the db, and I have a table, with the pool settings, size is 2048, when the people followed (ignoring people on white list) is equal to 2048, i swap to unfollow.
Currently, I use for following follow_likers.
My main script use schedule, I scheduled every day starting at 7:30 and finish 22:30 (16 h).
I follow about 32/34 users every hour. Random interaction between 10 to 20%, when interaction is True, interacts with N posts, random in the range 1-3 posts.  Comments percentage random in the range 30-50%, I use clarifai, I have a table, with the tag lists, and another table with all the comments. When the followed pool reach the value stored in the settings table (2048) the bot stops, and schedule unfollowing for the next day. To make sure to not exceed follows limit, I have also a safeguard, I update a table with date and followeds, so if is > of a certain value, I can break all the loops, and stop following or unfollowing people.

Is still a work in progress. For now I reached from 70 to 97 new followers per day.

**Comment by nopariffic** [comment]
@marcomokastyle Sounds interesting... what is you account size approximately? Also what did you do to speed up the following settings to, what specific value from default? Why not share your code, doesn't matter how unpolished/messy.

**Comment by marcomokastyle** [comment]
@nopariffic my account right now is about 1100 followers, in the beginning,before my mod was about 700. I could share something, but I have to make some order here and there, a lot of edits I have done on a new class that i called MyInstaPy that inherits all the code base from InstaPy, and I have overloaded some methods and added new ones. Just to avoid to mess too much with InstaPy class. But if you don't mind using another class, maybe is fine. When I have a bit of time, maybe I fork again the repo, and add this mods.

**Comment by furiont** [comment]
i cant run it any ideas??
![image](https://user-images.githubusercontent.com/9002428/43033345-2b2385b4-8cc9-11e8-87b2-9ce16144311c.png)

**Comment by leviwinks** [comment]
Only 1 week in but roughly gaining 50-60 followers per day running script 4 times a day! Very impressed!
