### ISSUE TITLE
Can someone help me?

### ISSUE THREAD

**Issue by iransales** [InstaPy/InstaPy#2417]
[12100:1236:0712/234127.538:ERROR:install_util.cc(589)] Unable to create registry key HKLM\SOFTWARE\Policies\Google\Chrome for reading result=2

DevTools listening on ws://127.0.0.1:12722/devtools/browser/d18a2545-06eb-4b0f-90ef-1f1d96ee973d
INFO [2018-07-12 23:41:28] [projetando3d]  Session started - 2018-07-12 23:41:28
WARNING [2018-07-12 23:41:28] [projetando3d]  Sorry, Record Activity is not working on Windows. We're working to fix this soon!
INFO [2018-07-12 23:42:06] [projetando3d]  Logged in successfully!
INFO [2018-07-12 23:42:13] [projetando3d]  Session ended - 2018-07-12 23:42:13
INFO [2018-07-12 23:42:13] [projetando3d]  --------------------

Traceback (most recent call last):
  File "C:\Users\iran\Desktop\InstaPy-master\InstaPy-master\Projetando3d unfollow.py", line 30, in <module>
    session.unfollow_users(amount=60, InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)
TypeError: unfollow_users() got an unexpected keyword argument 'InstapyFollowed'

**Comment by CharlesCCC** [comment]
1st, make sure you have latest version of the code
2nd, make sure you follow the instruction from the wiki page. 
3rd, please post your configuration files.

**Comment by iransales** [comment]
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = ''
insta_password = ''

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#   Settings.database_location = '/path/to/instapy.db'
#   Settings.chromedriver_location = '/path/to/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

##some code
try:
    session.login()



    session.unfollow_users(amount=60, InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)






except Exception as exc:
##some other code
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

**Comment by iransales** [comment]
I followed all the instructions, but still the same error. @CharlesCCC

**Comment by CharlesCCC** [comment]
Settings.chromedriver_location = '**/path/to/chromedriver**'

please update that... you need take step by step through the instruction.
