### ISSUE TITLE
5xx Server Error

### ISSUE THREAD

**Issue by LoneWolfsMoon** [InstaPy/InstaPy#2419]
![error1](https://user-images.githubusercontent.com/30674228/42709337-80d956a8-86e0-11e8-92f9-167efba6c7bb.png)

**Comment by LoneWolfsMoon** [comment]
I have fixed it.

I removed pip.. I guess some versions didn't match.

**Comment by HCWcoder** [comment]
it was a instagram server issue i guess

**Comment by nopariffic** [comment]
This was an IG issue, this issue should be closed.
