### ISSUE TITLE
 InstaPy for Dummies :( - 2

### ISSUE THREAD

**Issue by tricepad** [InstaPy/InstaPy#242]
https://github.com/timgrossmann/InstaPy/issues/240

**Comment by timgrossmann** [comment]
http://lmgtfy.com/?q=-bash%3A+pip%3A+command+not+found

**Comment by tricepad** [comment]
@timgrossmann 
I understand your annoyance. But I do not know the code, and I can not understand the explanations.
Sorry to disturb you. But if you could just let other members help me by reopening issue 240 ...

**Comment by timgrossmann** [comment]
@tricepad This is not because I'm annoyed.
This simply is way easier for everyone involved than to post an issue here.

They/We can't really tell you something different than google does, since that is the way to do it.
