### ISSUE TITLE
session.set_user_interact not working

### ISSUE THREAD

**Issue by shakmuscles** [InstaPy/InstaPy#2421]
## Expected Behavior
It should like posts of users that it follows before ending session. 
## Current Behavior
Doesn't like any posts at all
## InstaPy configuration
![screenshot 4](https://user-images.githubusercontent.com/40909221/42720218-aeb0ab1e-86e8-11e8-93c6-fb277a57167e.png)

I was using this template: 
Follow someone else's followers/following
# For 50% of the 30 newly followed, move to their profile
# and randomly choose 5 pictures to be liked.
# Take into account the other set options like the comment rate
# and the filtering for inappropriate words or users

session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
session.follow_user_followers(['friend1', 'friend2', 'friend3'], amount=10, randomize=False, interact=True)

**Comment by LoneWolfsMoon** [comment]
Try adding this line before your actions code:

 # actions
`
    session.like_by_tags(['natgeo'], amount=1)`

**Comment by shakmuscles** [comment]
So the line that was originally in the quickstart.py script? I should keep that line in there? 

Sorry I'm new to python.

**Comment by shakmuscles** [comment]
INFO [2018-07-14 16:53:37] [scenicshak]  Tag [1/1]
INFO [2018-07-14 16:53:37] [scenicshak]  --> b'natgeo'
INFO [2018-07-14 16:53:46] [scenicshak]  desired amount: 1  |  top posts [disabled]: 9  |  possible posts: 12254952
INFO [2018-07-14 16:53:53] [scenicshak]  [1/1]
INFO [2018-07-14 16:53:53] [scenicshak]  https://www.instagram.com/p/BlOlVg7n8NC/?tagged=natgeo
INFO [2018-07-14 16:53:56] [scenicshak]  Image from: b'yana_cielo'
INFO [2018-07-14 16:53:56] [scenicshak]  Link: b'https://www.instagram.com/p/BlOlVg7n8NC/?tagged=natgeo'
INFO [2018-07-14 16:53:56] [scenicshak]  Description: b'Greens of English summer #leeds #england #uk #visitengland #lovegreatbritain #travelbritain\n#natgeotravel #natgeo #getoutside #globetrotter  #traveltheworld #wanderlust #arountheworld #getaway #explore #artistfound #travelgram #instatravelling #travelgram #travelpics #travelphotography #soyuncielo'
INFO [2018-07-14 16:53:59] [scenicshak]  User: yana_cielo >> followers: 696  |  following: 196  |  relationship ratio: 0.28
INFO [2018-07-14 16:53:59] [scenicshak]  yana_cielo is not a massive follower with the relationship ratio of 0.28  ~skipping user

INFO [2018-07-14 16:53:59] [scenicshak]  Tag: b'natgeo'
INFO [2018-07-14 16:53:59] [scenicshak]  Liked: 0
INFO [2018-07-14 16:53:59] [scenicshak]  Already Liked: 0
INFO [2018-07-14 16:53:59] [scenicshak]  Commented: 0
INFO [2018-07-14 16:53:59] [scenicshak]  Followed: 0
INFO [2018-07-14 16:53:59] [scenicshak]  Inappropriate: 0
INFO [2018-07-14 16:53:59] [scenicshak]  Not valid users: 1

INFO [2018-07-14 16:53:59] [scenicshak]  User 'doyoutravel' [1/4]
INFO [2018-07-14 16:54:13] [scenicshak]  Simulated follow : 1
INFO [2018-07-14 16:54:14] [scenicshak]  --> Followed b'annatourta'
INFO [2018-07-14 16:54:17] [scenicshak]  Simulated follow : 2
INFO [2018-07-14 16:54:18] [scenicshak]  --> Followed b'chaseroftheworld'

INFO [2018-07-14 16:54:32] [scenicshak]  Grabbed 30 usernames from doyoutravel's `Followers` to do following.
INFO [2018-07-14 16:54:32] [scenicshak]  User 'chaseroftheworld' [1/30]
INFO [2018-07-14 16:54:36] [scenicshak]  User: chaseroftheworld >> followers: 255  |  following: 586  |  relationship ratio: 2.3
INFO [2018-07-14 16:54:36] [scenicshak]  User: chaseroftheworld >> followers: 255  |  following: 586  |  relationship ratio: 2.3
INFO [2018-07-14 16:54:36] [scenicshak]  ---> chaseroftheworld has already been followed more than 1 times
INFO [2018-07-14 16:54:38] [scenicshak]  User 'nayarasallesns' [2/30]
INFO [2018-07-14 16:54:41] [scenicshak]  User: nayarasallesns >> followers: 205  |  following: 1042  |  relationship ratio: 5.08
INFO [2018-07-14 16:54:41] [scenicshak]  --> nayarasallesns instagram account is opened...
INFO [2018-07-14 16:54:51] [scenicshak]  ---> Now following: nayarasallesns
INFO [2018-07-14 16:54:58] [scenicshak]  Follow [1/30]  |  Total Follow: 1
INFO [2018-07-14 16:54:58] [scenicshak]  User 'realrobgama' [3/30]
INFO [2018-07-14 16:55:01] [scenicshak]  User: realrobgama >> followers: 22100  |  following: 648  |  relationship ratio: 0.03
INFO [2018-07-14 16:55:01] [scenicshak]  --> Not a valid user: User realrobgama's followers count exceeds maximum limit  ~skipping user

INFO [2018-07-14 16:55:03] [scenicshak]  User 'annarevta' [4/30]
INFO [2018-07-14 16:55:06] [scenicshak]  User: annarevta >> followers: 1585  |  following: 273  |  relationship ratio: 0.17
INFO [2018-07-14 16:55:06] [scenicshak]  --> Not a valid user: User annarevta's followers count exceeds maximum limit  ~skipping user

INFO [2018-07-14 16:55:07] [scenicshak]  User 'ana_fdez4' [5/30]
INFO [2018-07-14 16:56:00] [scenicshak]  User: ana_fdez4 >> followers: 588  |  following: 724  |  relationship ratio: 1.23
INFO [2018-07-14 16:56:00] [scenicshak]  --> ana_fdez4 instagram account is opened...
INFO [2018-07-14 16:56:13] [scenicshak]  ---> Now following: ana_fdez4
INFO [2018-07-14 16:56:18] [scenicshak]  Follow [2/30]  |  Total Follow: 2
INFO [2018-07-14 16:56:18] [scenicshak]  User 'marculett' [6/30]
INFO [2018-07-14 16:56:23] [scenicshak]  User: marculett >> followers: 3052  |  following: 755  |  relationship ratio: 0.25
INFO [2018-07-14 16:56:23] [scenicshak]  --> Not a valid user: User marculett's followers count exceeds maximum limit  ~skipping user

Unfortunately it is still not working

**Comment by shakmuscles** [comment]
![6_2_2](https://user-images.githubusercontent.com/40909221/42728761-e99e886e-8787-11e8-92df-3628a0c5821c.jpg)
These are my settings

**Comment by shakmuscles** [comment]
![screenshot 5](https://user-images.githubusercontent.com/40909221/42728764-0626463e-8788-11e8-8a58-21901fb20acb.png)
There are my settings now btw

**Comment by LoneWolfsMoon** [comment]
I think that should finish the job because it has some sort of weird bug where it has to create cache files. I had a similar problem.
