### ISSUE TITLE
How do I make instapy to like, follow, comment on 10 users then wait for 10 minutes. 

### ISSUE THREAD

**Issue by brocool** [InstaPy/InstaPy#2428]
I guess it's easy to do but i'm a newbie. thanks alot

**Comment by brocool** [comment]
I guess it's easy to do but i'm a newbie. thanks alot

**Comment by brocool** [comment]
I guess it's easy to do but i'm a newbie. thanks alot

**Comment by brocool** [comment]
I guess it's easy to do but i'm a newbie. thanks alot

**Comment by 1yonatan** [comment]
i recommed you to use instabot.py
its a lot more easy and simple to setup.
