### ISSUE TITLE
Lower/upper limits should not be counted in the total number of likes?

### ISSUE THREAD

**Issue by sunnypatel165** [InstaPy/InstaPy#243]
When I say 
```
session.set_lower_follower_count(limit = 1000)
```
I wish to like/comment/follow only people with >1000 followers. 
Let's say I have set likes count to 20. 
```
session.like_by_tags(['#eatingfortheinsta' , '#foodphotography', '#mumbaifoodie'], amount=20)
```
It is likely that a lot of the found pictures will not meet my criteria, because the top posts are fine, they have many likes and followers coz they're actually trending, but the most recent posts(after the first 9 - [sample](https://www.instagram.com/explore/tags/sunny/) ) are not guaranteed to have many followers, in such cases generally 7 to 9 out of 20 are not liked, I feel that my count isn't working as expected. 

What I propose is:
when I say
```
session.like_by_tags(['#eatingfortheinsta' , '#foodphotography', '#mumbaifoodie'], amount=20)
```
I want **20 interactions**(likes/comments/follows) to happen(disarding those which dont meet the criteria).  And **not** 'find 20 images and check if they meet the criteria'.

Hope I make sense.

**Comment by pekapa** [comment]
I'm quite sure I've seen a similar issue but I can't find it right now... =/

If I'm not mistaken it was marked as a v1 improvement.

**Comment by sunnypatel165** [comment]
Can't find either. But the issue(if you consider it to be one) still persists.

**Comment by tibor** [comment]
#153 is a similar issue.

While I understand the issue, I’m not sure if this is a good idea. Depending on the user settings it could lead to a endless loop / unnatural behaviour with many page views and only a few likes. On the other hand, those numbers would be probably less predictable than the current settings.

**Comment by sunnypatel165** [comment]
Hmmm, makes sense @tibor !
