### ISSUE TITLE
Not just another library

### ISSUE THREAD

**Issue by instapyLover** [InstaPy/InstaPy#2431]
Hello to everyone!
I want to congrats @timgrossmann and all the contributors for this python library that i run for almost 3 months now and i've been with 5 different women since then!

My profile has gained more than 2k followers and more than 600likes/post !

It really pumped my social profile and i've been liked and followed even been asked to promote events from people that I knew no one would talk to me at all! It also changed my image in the firm that i work, all my co-workers ask me what i do and i have so many followers and likes!

But wait a sec.... Is this normal? Should i feel that way? Should i go from one partner to another just using InstaPy?
This is beyond programming... 

Have a nice Sunday people ! 💘

**Comment by brocool** [comment]
it's kind of a funny story... but hey, if they ask you just tell them im using an automation software... i think there's no big deal :)...

**Comment by sionking** [comment]
paying IG ads **or** using free automation tool == advertising.

**Comment by furiont** [comment]
hey @instapyLover  can you share with us what methods/tactics are you using? thanks

**Comment by instapyLover** [comment]
@brocool yeah sure hahaha
@sionking 😍 programming to get women 😍 

@furiont So it depends the occasion or the style that you support. For example i like sk8ing clothes, going to trap events etc. So i found some cool dj's from these type of events or some cool guys that have not so many followers and they sk8 or some "popular" guys that girls follow but below 3k followers, and i started following their followers. Also i interact with 3 likes in random images from the users i follow. So in some time i had like followers: 2k. and following 4.5k

Then i got all the users that are not following me and interacted with 2 likes in their posts randomly just for a bump ! 

In the meantime when i used the "follow_users_followers" I used to post a cool image flexing a beautiful view, or any old image from the places i've traveled. 

Don't forget to like lots of images in your feed.

After i did all the above, i rested for 2 weeks, got some girls 😉  and afterwards i started unfollowing, first the users that don't follow me back and then some other users that don't care about instagram a lot. Those users are the ones that have lets say 300 followers and 2k following.

Good luck !

**Comment by furiont** [comment]
@instapyLover  i have problem with interacting 
![image](https://user-images.githubusercontent.com/9002428/42738320-3fe61e76-8882-11e8-9b19-c7d77556bab5.png)

**Comment by shakmuscles** [comment]
@instapyLover Hey I see that you are also using session.follow_user_followers and set_user_interact. 

However for me, the set user interact has not been working. Is there anything special you did to make it work. In my situation, it just follows people but does not interact with them. I tried putting the set_user_interact above the other lines but no luck.

**Comment by instapyLover** [comment]
@shakmuscles put this line before your interaction line 


session.set_do_like(True, percentage=100)

**Comment by shakmuscles** [comment]
@instapyLover Alright will try it out.

Thanks!
