### ISSUE TITLE
dont unfollow

### ISSUE THREAD

**Issue by RaidenDragneel** [InstaPy/InstaPy#2434]
why says " unfollow error- username firstbladeclan might be blocked
![schermata da 2018-07-14 14-57-38](https://user-images.githubusercontent.com/19179484/42764881-04311210-8917-11e8-94f2-5675752550f6.png)

**Comment by andrei2306** [comment]
i have the same issue what i am doing wrong?

**Comment by maexsim** [comment]
the same

**Comment by RaidenDragneel** [comment]
anyone dont have solution?
