### ISSUE TITLE
false unfollow results, users still followed after removal from followedPool.csv

### ISSUE THREAD

**Issue by rowellr** [InstaPy/InstaPy#2435]
## Expected Behavior
Simply that the unfollow will be successful and there are error outputs if its not
## Current Behavior
attempt to unfollow using session.unfollow will state that user has blocked me as a result of not finding the unfollow button on the page due to changes in the instagram website, the unfollow now asks for confirmation in a modal popup.

User interactions where it will follow and unfollow, seem to also be affected. 
where it says it has unfollowed someone, I can verify still being followed, and they are being removed from the followedPool.csv preventing me from keeping track of those that have been followed.

INFO [2018-07-16 13:07:25] [xxx]  User 'owningnations' [4/5]
INFO [2018-07-16 13:07:31] [xxx]  User: owningnations >> followers: 23  |  following: 188  |  relationship ratio: 0.12
INFO [2018-07-16 13:07:31] [xxx]  User owningnations's followers count is less than minimum limit  ~skipping user

INFO [2018-07-16 13:07:31] [xxx]  Simulated unfollow: 13  ~not valid user
WARNING [2018-07-16 13:07:32] [xxx]  --> Unfollowed 'owningnations' due to Inappropriate Content
INFO [2018-07-16 13:07:32] [xxx]  --> Removed '2018-07-16 13:03 ~ owningnations' from followedPool.csv file
## Possible Solution (optional)

additional check if button exists and if not, throw an error appropriate to it, also adjust for the modal popup. double check that user has been successfully unfollowed before removing them from the followed pool list.

**Comment by sionking** [comment]
don't use DO ip address

**Comment by rowellr** [comment]
This issue is outside of the IP address issues at Digital Ocean, it is isolated to just the behaviour of the code.

**Comment by grantbey** [comment]
This is happening to me too.
