### ISSUE TITLE
Like the first post of a followed page //  loop structure in python

### ISSUE THREAD

**Issue by BalrogFlame** [InstaPy/InstaPy#2439]
Hi guys,
new here, thanks for the amazing work you are doing.
I was wondering if there is a way to like the first post of a profile that instaPy just followed.

Second question:
Can you suggest me a basic structure to loop different routine at different times or after a given time. 

Thanks for the help.

**Comment by marcomokastyle** [comment]
@frank-hs to the first question I don't have an answer, but for the second question, you can use schedule, it's simple, and pretty flexible. Take a look here https://github.com/dbader/schedule

**Comment by BalrogFlame** [comment]
Thanks @marcomokastyle !
