### ISSUE TITLE
Error with unfollow : list index out of range

### ISSUE THREAD

**Issue by dpayet** [InstaPy/InstaPy#2444]
## Expected Behavior

Unfollow users

## Current Behavior

Throw an error just after login

## InstaPy configuration

A very simple conf

`try:
    session.login()

    # actions
    session.unfollow_users(amount=100, nonFollowers=True, style="RANDOM", unfollow_after=72*60*60, sleep_delay=60)
`

Doesn't work neither with
`session.unfollow_users(amount=94, InstapyFollowed=(True, "all"), style="RANDOM", unfollow_after=48*60*60, sleep_delay=600)`

The error : 

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
ERROR [2018-07-17 10:37:43] [****.com]  Sorry, an error occured: list index out of range

Did I miss something ? :)

**Comment by CharlesCCC** [comment]
seems like you had internet connection issue.

**Comment by dpayet** [comment]
It's on a dedicated server and since few days now, I don't think so :)

Problem perhaps with the csv ?
