### ISSUE TITLE
'bool' object has no attribute '__getitem__'  -  Error while unfollowing users

### ISSUE THREAD

**Issue by kushpvo** [InstaPy/InstaPy#2450]
## Expected Behavior
Unfollow users

## Current Behavior
Getting this error only while the bot tries to unfollow users. 

![capture](https://user-images.githubusercontent.com/511577/42858280-695728f0-8a6b-11e8-9472-336d9d9b361d.PNG)
## InstaPy configuration

In the middle of the quickstart.py, i just have one simple line for unfollowing
`session.unfollow_users(amount=unfollowAmount, allFollowing=True, style="FIFO", unfollow_after=172800, sleep_delay=180)`

**Comment by kushpvo** [comment]
@timgrossmann Sorry for tagging you but i think this issue is important. 
I did reinstall Rasbian on my Pi and reinstalled InstaPy and just ran a simple quickstart.py that was meant to unfollow users. It is still giving the same error. Forgive me if the issue isn't too important.

**Comment by griffr10** [comment]
I am also receiving this issue.

**Comment by andrei2306** [comment]
i have the same probleme all the unfollow commands do the same

**Comment by lowtar** [comment]
same here
