### ISSUE TITLE
Commenting On a Specific Post

### ISSUE THREAD

**Issue by LeftyGlick36** [InstaPy/InstaPy#2452]
## Expected Behavior
Would like for the script to comment all 3 comments on this specific Instagram post

## Current Behavior
Only checks if it liked the post or not. Does not attempt to like.

## Possible Solution (optional)

```
session = InstaPy(username=insta_username, password=insta_password)
session.login()

# set up all the settings
session.set_relationship_bounds(enabled=True,
                  delimit_by_numbers=True)
session.set_do_comment(True, percentage=100)
session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])

# do the actual liking
session.interact_by_URL(urls=["BlV7KzuD9U1"], randomize=False, interact=True)

# end the bot session
session.end()
```
^^^ This is the code i am using am I missing something obvious?

**Comment by LeftyGlick36** [comment]
If there is any other way I can explain this I can.

**Comment by merianos** [comment]
Same here. I have the same problem.

**Comment by TrapTheOnly** [comment]
@LeftyGlick36 have you found answer for your issue?
