### ISSUE TITLE
TypeError: unfollow_users()

### ISSUE THREAD

**Issue by aku6640** [InstaPy/InstaPy#2454]
## Current Behavior
Traceback (most recent call last):
  File "custom.py", line 47, in job
    session.unfollow_users(amount=800, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=300, unfollow_after=48*60*60)
TypeError: unfollow_users() got an unexpected keyword argument 'onlyInstapyFollowed'

what to do?

**Comment by DavidMolinari** [comment]
You probably have an older version of the doc, the keywords onlyInstapyFollowed and onlyInstapyMethod don't exist I guess

Take a look at this part of the [README.md](https://github.com/timgrossmann/InstaPy#unfollowing)

```python

session.unfollow_users(amount=60, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)

````
