### ISSUE TITLE
Following problem ?

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#2461]
Hello is there any problem on following ? always get this error even if i put amout=1

INFO [2018-07-19 00:34:45] [xxx]  Failed to load desired amount of users

INFO [2018-07-19 00:34:45] [xxx]  Grabbed 0 usernames from xxx's `Followers` to do following.

Any ideas ? 
Thanks

**Comment by AlejandroSeok** [comment]
Same problem

**Comment by austinbeauch** [comment]
+1

**Comment by alezhke** [comment]
+1

**Comment by botpadawan** [comment]
+1

**Comment by spikeyhair** [comment]
Same here

**Comment by dds14** [comment]
There may have been an IG change. I am trying to follow the users who like photos of specific accounts. It has worked perfectly until a few hours ago. 

If you guys want to give it a quick run to confirm that it may be IG, I'm running the following line of code (which is also on the main InstaPy page).

`session.follow_likers(
         ['account1', 'account2'], photos_grab_amount = 2, follow_likers_per_photo = 20, sleep_delay=0, randomize=False, interact=False)`

and receiving the following:

`opening likes
('Scrolling down... ', 0, '->', 0, ' / ', 20)
Like window closed
('\nGot ', 0, ' likers shuffled randomly, who you can follow:\n', [], '\n')`

**Comment by torbenberger** [comment]
Hi,
yes IG seems to have changed smth. The xpaths changed so instapy wont find the elements

**Comment by torbenberger** [comment]
I provided a PR with updated Xpath at least for the follow/unfollow functionality

**Comment by spikeyhair** [comment]
Thanks. it works now.

**Comment by botpadawan** [comment]
Does not work using 
session.follow_user_followers(['friend1', 'friend2', 'friend3'], amount=10, randomize=False)

**Comment by CharlesSOo** [comment]
Yes, seems to be an issue still. I'll look into it as well once I get some free time.

**Comment by Tachenz** [comment]
Have this one as well!

**Comment by CTZNkjs** [comment]
plus one on this as well. going to try the updated xpath


**So far it is working now. Thank You
