### ISSUE TITLE
Failed to load desired amount of users

### ISSUE THREAD

**Issue by kushpvo** [InstaPy/InstaPy#2462]
## Expected Behavior
Should unfollow users
## Current Behavior

> Failed to load desired amount of users

How do i solve this error?
## InstaPy configuration

`session.unfollow_users(amount=25, allFollowing=True, style="FIFO", unfollow_after=172800, sleep_delay=180)
`

**Comment by zheskiel** [comment]
it seems like Instagram has been changing the HTML DOM

to fix this, go to **unfollow_util.py** and remove "**/span**" from  line **658** & **662**
example below:

```
        if channel == "Follow":
            buttons = dialog.find_elements_by_xpath(
                "//div/div/span/button[text()='Follow']") **### -> remove /span**

        elif channel == "Unfollow":
            buttons = dialog.find_elements_by_xpath(
                "//div/div/span/button[text()='Following']") **### -> remove /span**

```

**Comment by joanroig** [comment]
@idpelago I have the same issue when using follow_likers, after trying to get likers from a photo it returns 0 users. Do you know if this fix will work as well? Thanks in advance

**Comment by HCWcoder** [comment]
I tried that  @idpelago **working** thanks for sharing !

**Comment by testornot** [comment]
Here is the solution https://github.com/timgrossmann/InstaPy/pull/2463/files

**Comment by gitpatrickhub** [comment]
This worked for me as well, thanks for sharing @idpelago !

**Comment by kushpvo** [comment]
@idpelago Was the code changed in the latest pull? Because the code on line 658 & 662 is different for me.

**Comment by kushpvo** [comment]
Removed /span but still getting the same error. 

![capture](https://user-images.githubusercontent.com/511577/42984566-ccebf83c-8c0a-11e8-9164-b6ec31cc304f.PNG)

**Comment by griffr10** [comment]
I am also receiving the same error as mentioned above.

**Comment by zheskiel** [comment]
well actually if you pull the latest updates, everything should work

**Comment by mattionline** [comment]
@testornot 

When i try that file i get the following errors:

> ____________________________________________________________________
> INFO [2018-07-21 12:50:50] [xxx]  Starting to unfollow users..
> """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> INFO [2018-07-21 12:50:50] [xxx]  Unfollowing the users you are following
> INFO [2018-07-21 12:51:00] [xxx]  Failed to load desired amount of users
> ERROR [2018-07-21 12:51:00] [xxx]  Sorry, an error occured: 'bool' object has no attribute '__getitem__'
> 
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2018-07-21 12:51:00] [xxx]  Session ended - 2018-07-21 12:51:00
> ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

@idpelago 

When i try the unfollow file in this repository (5 days ago):

>  ...............................................................
> INFO [2018-07-21 13:01:57] [xxx]  Logged in successfully!
> '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
> 
> ____________________________________________________________________
> INFO [2018-07-21 13:02:00] [xxx]  Starting to unfollow users..
> """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> INFO [2018-07-21 13:02:00] [xxx]  Unfollowing the users you are following
> INFO [2018-07-21 13:02:56] [xxx]  Failed to load desired amount of users
> ERROR [2018-07-21 13:02:56] [xxx]  Sorry, an error occured: 'bool' object has no attribute '__getitem__'
> 
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2018-07-21 13:02:56] [xxx]  Session ended - 2018-07-21 13:02:56
> ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
>

**Comment by bgunsberger** [comment]
Still not working for me. Pretty sure it's related to the 12-user max follows mentioned in other issues.

**Comment by A-S-C-I-I** [comment]
@bgunsberger 
I have found that you can get around that 12 user issue by simply repeating their name in your list.  it's 12 per entry, but this seems to be a useable (if awkward) workaround.
