### ISSUE TITLE
ValueError:signal only works in main thread

### ISSUE THREAD

**Issue by codingsett** [InstaPy/InstaPy#2464]
Hello am trying to intergrate the library in my app and when i try to start a new thread to check followers of  a user i get the following error.....
`Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\InstaPy-master\instapy\relationship_tools.py", line 168, in get_followers
    with interruption_handler():
  File "C:\Python36\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\InstaPy-master\instapy\util.py", line 567, in interruption_handler
    original_handler = signal.signal(SIG_type, handler)
  File "C:\Python36\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread`

How can i resolve this ...any help appreciated

**Comment by richardwardza** [comment]
I had the same problem and worked around it by creating a "custom" `session.end()` function.

```py
#call it as follows (instead of session.end() do:

end_instapy(session)

#the function
def end_instapy(session):
    """Closes the current session"""
    # delete cookies
    try:
        session.browser.delete_all_cookies()
    except Exception as exc:
        if isinstance(exc, WebDriverException):
            session.logger.exception("Error occurred while deleting cookies from web browser!\n\t{}"
                                    .format(str(exc).encode("utf-8")))

    # close web browser
    try:
        session.browser.quit()
    except Exception as exc:
        if isinstance(exc, WebDriverException):
            session.logger.exception("Error occurred while closing web browser!\n\t{}"
                                    .format(str(exc).encode("utf-8")))

    # close virtual display
    if session.nogui:
        session.display.stop()

    # write useful information
    dump_follow_restriction(session.username, session.logger, session.logfolder)
    dump_record_activity(session.username, session.logger, session.logfolder)

    with open('{}followed.txt'.format(session.logfolder), 'w') as followFile:
        followFile.write(str(session.followed))

    # output live stats before leaving
    session.live_report()

    message = "Session ended!"
    highlight_print(session.username, message, "end", "info", session.logger)
    print("\n\n")
```

I copy-pasted the session.end() function and removed the `with interruption_handler():` and fixed the indents.
Then, I changed all `self.` in my new `end` function to `session.`.
Lastly, in my script, instead of `session.end()` I did `end_instapy(session)`

This all worked out well for me so far.

**Comment by ttresslar** [comment]
Hey, I'm also getting this error. Has this been implemented at all in the overall package?
