### ISSUE TITLE
Error Getting active users who liked the latest 5 posts

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#2467]
Hi,

using `session.set_dont_unfollow_active_users(enabled=True, posts=5)`

i'm experiencing this error:

INFO [2018-07-19 09:30:07] [xxx]  Getting active users who liked the latest 5 posts:
  ~collecting the usernames from posts with the boundary of 500

ERROR [2018-07-19 09:31:30] [xxx]  Unable to go to next profile post
INFO [2018-07-19 09:31:46] [xxx]  Post 2  |  Likers: found 67, catched 72
ERROR [2018-07-19 09:32:13] [xxx]  Unable to go to next profile post
ERROR [2018-07-19 09:32:15] [xxx]  Unable to append users to active_users : 'int' object is not iterable

someone else with this errror ?

**Comment by testornot** [comment]
same here! :(

Here is the solution https://github.com/timgrossmann/InstaPy/pull/2463/files

**Comment by ghost** [comment]
it works! thanks
