### ISSUE TITLE
Grabbed 0 usernames issue

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#2468]
session.interact_user_followers(['instgram33'], amount=500, randomize=True)

INFO [2018-07-19 00:11:41] [botname]  Grabbed 0 usernames from instgram33' `Followers` to do interaction.

**Comment by testornot** [comment]
https://github.com/timgrossmann/InstaPy/pull/2463/files

**Comment by andreescocard** [comment]
Pulled today and same error in following

**Comment by AdamMoffitt** [comment]
same issue

**Comment by andreescocard** [comment]
Try this:
https://github.com/timgrossmann/InstaPy/commit/e07aa4acace39e498e8dcf49f8bbd2ef92dfcd37

**Comment by LoneWolfsMoon** [comment]
I get this errror:

`python quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 7, in <module>
    from instapy import InstaPy
  File "/home/aleksandar/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/home/aleksandar/InstaPy/instapy/instapy.py", line 50, in <module>
    from .unfollow_util import follow_restriction
ImportError: cannot import name follow_restriction`
