### ISSUE TITLE
Randomize Hashtags?

### ISSUE THREAD

**Issue by the-unknown** [InstaPy/InstaPy#2471]
I would like to setup a larger list of hashtags, and the bot should randomly select 10 out of that list to work with. Is there a way to do so?

**Comment by DavidMolinari** [comment]
Maybe 
```python
random.sample([1, 2, 3, 4, 5],  3)
# output => [4, 1, 5]
````

**Comment by marcomokastyle** [comment]
@the-unknown I do something like this for targets to follow, you can do something like this:
```python
import random
hashtags = ['tag1', 'tag2', 'tag3', 'tagN']
random.shuffle(hashtags)
ten_hashtags = hashtags[:10]
```

**Comment by c0d3x27** [comment]
@marcomokastyle sorry for being stupid but how can i use this thing that you just post? do i have to make a cript and save it as .py and put it in instapy folder?or i just have to add this to my quickstart?
