### ISSUE TITLE
Got  0  likers shuffled randomly, who you can follow:" 

### ISSUE THREAD

**Issue by tolgaada** [InstaPy/InstaPy#2472]
Hey guys, I have a problem. The follow Bot is not working anymore.
"opening likes
Scrolling down...  0 -> 0  /  15
Like window closed
Got  0  likers shuffled randomly, who you can follow:" 

that's all i get ...

Can someone help me ?

**Comment by daliborg** [comment]
Same here for following user followers and following likers...

**Comment by dds14** [comment]
Hey guys - this issue has been fixed. #2463

**Comment by joanroig** [comment]
@dds14 @torbenberger I've tested the purposed solution but I cannot get it working, I receive the same issue up here when following likers, did you got this feature work with the fix?

**Comment by tolgaada** [comment]
Doesn't work for me either..

**Comment by dds14** [comment]
@joanroig @tolgaada I am now receiving the same issue when trying the proposed solution. I added another comment in #2463

**Comment by daliborg** [comment]
Fix doesn't work...

**Comment by dds14** [comment]
@joanroig @tolgaada have you guys tried any other solutions?

**Comment by tolgaada** [comment]
@dds14 i searched online but was not able to find something to help get rid of the problem

**Comment by slayerkey** [comment]
having same issue here :)

**Comment by daliborg** [comment]
@slayerkey you can check this [#2476](https://github.com/timgrossmann/InstaPy/pull/2476/commits/e64ca7e4eb70a083d057d1d6e2be06808079e384)

**Comment by behookd** [comment]
Can confirm @swznd fix works in #2476
