### ISSUE TITLE
Unknown error: Chrome failed to start (tested several times, can't figure it out)

### ISSUE THREAD

**Issue by rowellr** [InstaPy/InstaPy#2473]
I had InstaPy working beautifully until Instagram altered their unfollow to create a popup modal window two weeks ago. I then stopped using instaPy to let the code get updated. I have just pulled from master replacing everything to the new version and now cannot get it to function correctly. 

I have chromedriver ver 2.7, and this whole thing is running on Ubuntu using a Pi.

Perhaps someone with more experience can help me get back to a working point again.

here is the error I am getting after waiting about 10 seconds for the terminal to provide feedback:

ERROR [2018-07-19 08:03:14] [redacted]  Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.37 (0),platform=Linux 4.4.38-v7+ armv7l)
Traceback (most recent call last):
  File "/home/ryan/Documents/InstaPy/instapy/instapy.py", line 297, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.37 (0),platform=Linux 4.4.38-v7+ armv7l)

Traceback (most recent call last):
  File "start.py", line 3, in <module>
    session = InstaPy(username='redacted', password='redacted', nogui=False)
  File "/home/ryan/Documents/InstaPy/instapy/instapy.py", line 190, in __init__
    self.set_selenium_local_session()
  File "/home/ryan/Documents/InstaPy/instapy/instapy.py", line 301, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/ryan/Documents/InstaPy/assets/chromedriver

any help would be much appreciated, I have been making small progress each day trying to figure it all out over the past week and a half that I have not been able to run.

**Comment by joanroig** [comment]
Which Raspberry do you have? Remember that modern chromedriver is now only available for x64 processors, and rpi2 has a 32bit cpu. I use this version of chromedriver for a rpi2, which is the last x32 supported version for Linux:

https://chromedriver.storage.googleapis.com/index.html?path=2.32/

Remember to change the configuratoin file for reducing the chromedriver version requirement.

P.S. not related question, anybody knows if there is any x64 OS for rpi3? I'm interested switching to it for using the lastest chromedriver, but I don't really know if will work. A friend of mine has a x64 pi but he uses the x32 version of chromedriver (x64 does not work because the installed Raspbian is x32).

**Comment by rowellr** [comment]
I am using chromium-chromedriver_67.0.3396.99-0ubuntu0.16.04.2_armhf version 2.7 available from the repository. I will try using the version you have supplied, though this is the version I was using when it was all working before.

https://launchpad.net/ubuntu/xenial/armhf/chromium-chromedriver/67.0.3396.99-0ubuntu0.16.04.2

**Comment by PJUllrich** [comment]
And make sure that you actually have chrome installed
You can install it on Debian like explained [here](https://github.com/timgrossmann/InstaPy/issues/2179#issuecomment-397460795)
