### ISSUE TITLE
follows but does not like photos with set_user_interact

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#2477]
```
quickstart.py
session.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')
session.follow_user_followers(['exampleuser'], amount=800, randomize=False, interact=True)  

```

EDIT: Should i change interact in instapy.py to True ?? is this why it only follows but not likes ?

def follow_user_followers(self,
                              usernames,
                              amount=10,
                              randomize=False,
                              interact=False,
                              sleep_delay=600):

**Comment by daliborg** [comment]
No need to change def function.
You are missing: "session.set_do_like(enabled=True, percentage=70)"

session.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')
session.set_do_like(enabled=True, percentage=70)
session.follow_user_followers(['exampleuser'], amount=800, randomize=False, interact=True)
