### ISSUE TITLE
How to like, follow, comment per day? like instabot.py

### ISSUE THREAD

**Issue by brocool** [InstaPy/InstaPy#2479]
title says all

**Comment by DavidMolinari** [comment]
[Automate InstaPy](https://github.com/timgrossmann/InstaPy#automate-instapy)

**Comment by brocool** [comment]
@DavidMolinari do you personally use it? if so, It would be of great help if you show me yours settings and how you did it

**Comment by DavidMolinari** [comment]
If you're on windows just follow the guide : 
### [Windows Task Scheduler](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383614(v=vs.85).aspx)

You can use Window's built in Task Scheduler to automate InstaPy, using a variety of trigger types: time, login, computer idles, etc. To schedule a simple daily run of an Instapy script follow the below directions
1. Open [Windows Task Scheduler](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383614(v=vs.85).aspx)
2. Select "Create Basic Task"
3. Fill out "Name" and "Description" as desired, click "Next"
4. On "Trigger" screen select how frequently to run, click "Next" (Frequency can be modified later)
5. On "Daily" screen, hit "Next"
6. "Action Screen" select "Start a program" and then click "Next"
7. "Program/script" enter the path, or browse to select the path to python. ([How to find python path on Windows](https://stackoverflow.com/questions/647515/how-can-i-get-python-path-under-windows))
8. "Add arguments" input the InstaPy script path you wish to run. (Example: C:\Users\USER_NAME\Documents\GitHub\InstaPy\craigquick.py)
9. "Start in" input Instapy install location (Example: C:\Users\USER_NAME\Documents\GitHub\InstaPy\). Click "Next"
10. To finish the process, hit "Finish"


* And on Linux you'll have to add a new line in your crontab
so you type in your console : 
```bash
crontab -e
```
And copy paste your line : Here is an example for executing your script every day at 8pm
```
 0 20 * * * cd /home/user/InstaPy && /usr/bin/python ./quickstart.py
```
The syntax is : 
*[cron expression]* cd *[path to your instapy folder]* && *[path to your python binary]* *[path to your script]*


You can check your cron expression on this website for example [crontab.guru](https://crontab.guru/)

**Comment by brocool** [comment]
thanks alot @DavidMolinari for your reply and i respect your time. But that's not what I mean... What I mean is how to increase or decrease the speed of liking in the software, so i can make it like 20 pictures per hour, and because the bot is too fast

**Comment by succulentia** [comment]
@DavidMolinari I can't get it work with

`50 22 * * * cd /root/InstaPy && python3 quickstart.py

I have searched about the log files on google and on my lubuntu system and I'm not sure which one has the error.

I can get it working with python3, python command gives lots of crap.

`
