### ISSUE TITLE
Unfollow oldest followed accounts first?

### ISSUE THREAD

**Issue by deronsizemore** [InstaPy/InstaPy#248]
Maybe this is already built into the script, but it seems like it would be useful to unfollow the oldest accounts you're following first? I don't want to follow someone and then unfollow them soon after. Is it possible to start with the oldest first when you're unfollowing?

**Comment by pekapa** [comment]
I believe that's exactly how it works.
There's a pull request pending #151 that should allow the user to set it's preferred method. But it's only going in for the V1, I think.

**Comment by deronsizemore** [comment]
Thanks

**Comment by deronsizemore** [comment]
Thanks.

Sorry for my ignorance, but what is "FIFO" from that #151 thread?

**Comment by timgrossmann** [comment]
@deronsizemore First in First out

**Comment by deronsizemore** [comment]
Ah thanks @timgrossmann

**Comment by deronsizemore** [comment]
So, I just tested this is and it looks like it doesn't unfollow the oldest first unless it's just more confusion on my part in how the script works. 

As an example, I went into instagram and followed an account. I then ran my script which is set to unfollow and the very first account it unfollowed was the one I just followed a few minutes before running the script. 

If it's possible I'd love to be able to start at the bottom of my following list and work my way back to the most recently followed when it comes to unfollowing. I'm not sure if that's even an option though.

**Comment by dylancaponi** [comment]
Also, I think InstaPy should only unfollow accounts that it followed to begin with to not affect accounts the user manually followed.  Not sure if it does this, need to read through the code.

**Comment by deronsizemore** [comment]
@dylancaponi I could see that being a useful option. For me, I'd use that later once I got my following numbers under control. As it is, I've followed a lot of accounts manually so I'll need to unfollow those first but I really don't want to unfollow accounts that I just followed the day before.

**Comment by timgrossmann** [comment]
@dylancaponi that's already in the Todo's for V_1 😉

**Comment by jungfish** [comment]
what do you think of making instead a pool of automated followed and unfollow them in FIFO ? 
https://github.com/timgrossmann/InstaPy/issues/326

I can do it !

**Comment by timgrossmann** [comment]
@jungfish Feel free to do so!
Would love to have your feature in InstaPy

**Comment by jungfish** [comment]
@timgrossmann deal ! I commit it in master or dev ?

**Comment by timgrossmann** [comment]
@jungfish Do it in master. It seems there are some problems with unfollow anyway so this is a good opportunity to get rid of them 😉 

Looking forward to your PR.

**Comment by sweb1** [comment]
+1 for this feature. Unfollow oldest first, except accounts on friends list (https://github.com/timgrossmann/InstaPy#excluding-friends)

**Comment by sweb1** [comment]
Is this already released or what is the current unfollowing behaviour?

**Comment by timgrossmann** [comment]
@sweb1 Nope, there is another feature which will only unfollow the accounts that have been followed by InstaPy itself. So if you use that from the beginning of your account you will get what you want. But it's not exactly what this issue is here for

**Comment by jeffreylm** [comment]
What would also be a nice added feature. So many people have alot of manual followers they would like removed with InstPy. In my case I wanted to remove 800 people, but when I set it to 800, the scripts just started doing the normal batch of ten and waiting 10 minutes.

**Feature**
Whenever an amount is given above 10, let the script do the first batch of 10 then continue with the rest of the script then comeback in 10 min to continue to unfollowing people and go so on and so on, so we don't waste time.

**Comment by texmex44** [comment]
Finally any way to unfollow from bottom ?

**Comment by yassinbm** [comment]
Yeah, @timgrossmann @uluQulu  @deronsizemore please tell me this feature exists by now. My accounts are unfollowing immediately after following. I tried with an without the FIFO method. Any other ideas or updates?

**Comment by uluQulu** [comment]
hi @yassinbm 
I've written a few lines to do delayed unfollow and it was merged a few days back
Now you can define desired time to unfollow users after that time with `unfollow_after` parameter, find usage [here](https://github.com/timgrossmann/InstaPy#unfollowing)

> old usernames in the `username_followedPool.csv` that do not have datetime stamp will not be affected by that change (_old usernames are those that were recorded before `unfollow_after` commit was merged that now stores datetime stamp alongside followed usernames_)
[more details](https://github.com/timgrossmann/InstaPy/pull/1336#issue-166764801)

_But if you dont want **certain** delay period, I think, FIFO should work fine, just make sure your `username_followedPool.csv` keeps recording correctly_

**Comment by yassinbm** [comment]
You´re awesome @uluQulu ! 
Is it enough to just include the unfollow_after parameter or do I need to change other lines of code so that the followers get recorded with the timestamp from now on?

**Comment by uluQulu** [comment]
Thanks @yassinbm ^.^
Everything is fully applied to provide proper functionality, _just_ start by adding `unfollow_after` parameter to `unfollow_users()` feature with a desired amount of time in seconds

**Comment by yassinbm** [comment]
Amazing! I appreciate the amount of work you put in @uluQulu Thanks for your help as well in the Instapy Slack. Same goes for Tim of course.

**Comment by yassinbm** [comment]
Got an error unfortunately :/ @uluQulu Seems that it didn´t work by just adding the parameter, any ideas?

`session.unfollow_users(amount=100, unfollow_after=144*60*60)
TypeError: unfollow_users() got an unexpected keyword argument 'unfollow_after'
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x10aef8f28>>
Traceback (most recent call last):  ........`

**Comment by Tjorriemorrie** [comment]
Update your code to latest: `git pull`

**Comment by uluQulu** [comment]
Hi @yassinbm 
You need to provide changes in order to use `unfollow_after` parameter
Try pulling latest commits (or redownload latest InstaPy files), or apply changes manually ☺

**Comment by yassinbm** [comment]
Thanks guys, it worked :)
