### ISSUE TITLE
Video has no likes?

### ISSUE THREAD

**Issue by slayerkey** [InstaPy/InstaPy#2480]
just updated to newest version now i keep getting this error message

 # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=None,
				  delimit_by_numbers=True,
				   max_followers=2000,
				    max_following=300,
				     min_followers=None,
				      min_following=None)
    session.follow_likers (['ninja']), photos_grab_amount = 5, follow_likers_per_photo = 10, randomize=False, interact=True, sleep_delay=600,)

when i run this is the return

Getting likers from user:  ninja 

Got  12 , returning  5  links:  ['https://www.instagram.com/p/Blb-gtnBB_W/?taken-by=ninja', 'https://www.instagram.com/p/Blb1mZihW8A/?taken-by=ninja', 'https://www.instagram.com/p/BlZgce2hJ_w/?taken-by=ninja', 'https://www.instagram.com/p/BlZOoNBBZdD/?taken-by=ninja', 'https://www.instagram.com/p/BlYvEe4BTT7/?taken-by=ninja']
Video has no likes?
Moving on..
opening likes
Scrolling down...  0 -> 0  /  600
Like window closed

Got  0  likers shuffled randomly, who you can follow:
 [] 

opening likes
Scrolling down...  0 -> 0  /  600
Like window closed

Got  0  likers shuffled randomly, who you can follow:
 [] 

opening likes
Scrolling down...  0 -> 0  /  600
Like window closed

Got  0  likers shuffled randomly, who you can follow:
 [] 

opening likes
Scrolling down...  0 -> 0  /  600
Like window closed

Got  0  likers shuffled randomly, who you can follow:
 []

**Comment by sionking** [comment]
This is a bug I saw as well

**Comment by diegoca80** [comment]
Same issue here. Tried different versions of chromedriver but it doesn't work. Does anyone has one solution for that?

**Comment by dds14** [comment]
@diegoca80 was this issue able to be resolved?

**Comment by sionking** [comment]
We can't see the likes for video so we shall skip.

**Comment by finan** [comment]
I have the same issue on RaspberryPi 3. Any solutions for this issue?

**Comment by tE3m** [comment]
I have the same issue, also on a RPi 3.
