### ISSUE TITLE
There is an issue with the bot that can easily be fixed-- possible solution (commenting with @{})

### ISSUE THREAD

**Issue by brocool** [InstaPy/InstaPy#2482]
## Expected Behavior
The expected behavior is for the software to comment with the username. For example: 'Awesome post @{}', Which will be converted to Awesome post @username-- when commenting
## Current Behavior
The current behavior is that it gives an error when @{} to is added to comments and left to like like 3-11 posts, and comment on them
## Possible Solution (optional)
The possible solution is to fix line 41, in comment_util.py in the instapy folder, and fix to accept @{}
## InstaPy configuration
File "C:\Users\brocool\Downloads\InstaPy-mastertest\instapy\comment_util.py", line 41, in comment_image
    rand_comment = (choice(comments).format(username))
IndexError: tuple index out of range

**Comment by HCWcoder** [comment]
is it working ?
