### ISSUE TITLE
Unfollowing issue

### ISSUE THREAD

**Issue by lucanello** [InstaPy/InstaPy#2488]
## Expected Behavior
You can see my configuration below. I used this configuration for months in order to unfollow all users except a few which defined in an external "friends"-list. This list contains all people I do not want to unfollow. So I want InstaPy to ignore all "friends" and unfollow users I don't really want to follow.

## Current Behavior
InstaPy now unfollows only 6, 8, 30 or X people instead of the number I defined (e.g. 120 in the configuration below). It seems that it can't capture the amount of people I really want to unfollow which makes it unusable since my following bot ran for hours without unfollowing.
```
________________________________________________________________________
INFO [2018-07-20 16:24:34] [XXX]  Starting to unfollow users..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-07-20 16:24:34] [XXX]  Unfollowing the users you are following
INFO [2018-07-20 16:25:28] [XXX]  Failed to load desired amount of users
INFO [2018-07-20 16:25:37] [XXX]  Total 6 users available to unfollow  ~not found in 'followedPool.csv': 0  |  didn't pass `unfollow_after`: 42
INFO [2018-07-20 16:25:37] [XXX]  Could not grab requested amount of usernames to unfollow:  6/120  ~using available amount
INFO [2018-07-20 16:25:47] [XXX]  --> Ongoing Unfollow 1/6, now unfollowing: b'XXX'
INFO [2018-07-20 16:25:47] [XXX]  --> Removed '2018-07-19 11:03 ~ XXX' from followedPool.csv file
```

## Possible Solution (optional)
How can I use the InstaPy unfollowing feature like before without all those new updates and features like the possibility to unfollow only not-follow-backs? It worked so great to define a list of "friends" and only unfollow people that are not on the "friends"-list.

## InstaPy configuration
```
session.set_dont_include(friends)
#session.unfollow_users(amount=120, onlyInstapyFollowed = False, onlyInstapyMethod = 'FIFO', sleep_delay=120) [PREVIOUS CONFIGURATION]
session.unfollow_users(amount=120, allFollowing=True, style="FIFO", unfollow_after=12*60*60, sleep_delay=120)
```

**Comment by davidkessler-ch** [comment]
Same issue for me!
I tried all unfollowiung methods, always only unfollows 48 accounts.
Everything should be up to date, good internet connection and no modifications made.

Here is my setup:

from instapy import InstaPy

session = InstaPy(username='my_acc', password='my_pwd', headless_browser=True, multi_logs=True)

session.login()

session.unfollow_users(amount=500, allFollowing=True, style="FIFO")

session.end()

Here is what it logs:

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-07-29 12:37:20] [my_acc]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo


...............................................................
INFO [2018-07-29 12:37:58] [my_acc]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

____________________________________________________________________
INFO [2018-07-29 12:38:06] [my_acc]  Starting to unfollow users..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-07-29 12:38:07] [my_acc]  Unfollowing the users you are following
INFO [2018-07-29 12:39:04] [my_acc]  Failed to load desired amount of users
INFO [2018-07-29 12:39:26] [my_acc]  Total 48 users available to unfollow  ~not found in 'followedPool.csv': 0  |  didn't pass `unfollow_after`: 0
INFO [2018-07-29 12:39:26] [my_acc]  Could not grab requested amount of usernames to unfollow:  48/500  ~using available amount

...

There are no errors except this one for me.
