### ISSUE TITLE
Possible ? Don't interact with post that have more than X likes allready

### ISSUE THREAD

**Issue by c20xh2** [InstaPy/InstaPy#249]
Question is in the title, I'm really sorry if it's already documented somewhere.

**Comment by littleswany** [comment]
You can do it based on the number of followers a user has, I don't think we have implemented something like this.

I seem to recall it being discussed before but the issue being a post just posted will have very few regardless of the number of followers so the chance of an interaction back is reduced.

**Comment by c20xh2** [comment]
> I seem to recall it being discussed before but the issue being a post just posted will have very few regardless of the number of followers so the chance of an interaction back is reduced.

Make sense ! Thank you :)
