### ISSUE TITLE
Failed to load desired amount of users

### ISSUE THREAD

**Issue by texmex44** [InstaPy/InstaPy#2490]
Since some hours Instapy are not able to get user followers ... Instagram change web interface ?

## Console
INFO [2018-07-20 14:28:32] [username]  User 'deviantart' [1/1]
INFO [2018-07-20 14:29:33] [username]  **Failed to load desired amount of users**

INFO [2018-07-20 14:29:33] [username]  Grabbed 0 usernames from deviantart's `Followers` to do interaction.
INFO [2018-07-20 14:29:33] [username]  --> Interacted total of 0 people

## InstaPy configuration
```
session.set_relationship_bounds(enabled=True,
                                    potency_ratio=-1.21,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                    max_following=5555,
                                    min_followers=45,
                                    min_following=77)
session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
session.set_do_follow(enabled=True, percentage=100)
session.set_do_like(enabled=True, percentage=50)
session.interact_user_followers(['deviantart'], amount=40, randomize=True)
```
Any idea ?

**Comment by AnwarAhmedPSU** [comment]
I'm having the same issue. Any update?

**Comment by Areahints** [comment]
Same issue also

**Comment by alezhke** [comment]
@texmex44 @AnwarAhmedPSU @Areahints 
#2463

**Comment by narchiii** [comment]
Same issue here

**Comment by tunidev** [comment]
same here

**Comment by Areahints** [comment]
I've pulled the latest commit yet still same issue

**Comment by mekalok** [comment]
same issue.
git pull doesn't help

**Comment by havlicekp** [comment]
Same issue. I noticed that when using session.interact_by_URL, the number of followers is read properly

INFO [2018-07-21 15:54:12] [testuserblah04]  User: testuserblah01 >> **followers: 2**  |  following: unknown  |  relationship ratio: unknown

**Comment by stmoreau** [comment]
same issue!

**Comment by mattionline** [comment]
same here

**Comment by texmex44** [comment]
Issue fixed since last pull, all work for me now !
