### ISSUE TITLE
UPDATED TUTORIAL?

### ISSUE THREAD

**Issue by SEOAlexRamon** [InstaPy/InstaPy#2491]
Hi, I'm trying to install InstaPy on my Windows 10 64 bit laptop and I can not get it. Is there a tutorial that is updated? Because the one that appears in the readme is outdated and following the way it indicates does not work.
Greetings and many thanks.

**Comment by alezhke** [comment]
@seoalexramon Open Readme.md everythin is inside

**Comment by SEOAlexRamon** [comment]
@alezhke i followed it 8 times and it does not work for me.

**Comment by starbuck614** [comment]
@seoalexramon I installed it on Windows 10 64 bit several days ago. What are you having trouble with?

**Comment by SEOAlexRamon** [comment]
@starbuck614 

https://fotos.subefotos.com/5cf4ebdb3182f7041b412cd84772efc4o.jpg

**Comment by starbuck614** [comment]
The clarifai issues your having is because you didn't do this step:

4. Edit the instapy.py file
Open file instapy.py an disabling the clarifai import
comment the line “from .clarifai_util import check_image”
from .clarifai_util import check_image

The reason you're getting from `instapy import InstaPy` error is because you didn't move the .exe file into the master folder, which is step 3.2.

**Comment by SEOAlexRamon** [comment]
@starbuck614 regarding step 3.2, the link does not work. What should I do exactly?

https://fotos.subefotos.com/1c4d77b06f63bd9c343e5e0c0b664043o.jpg

**Comment by Wraitheye** [comment]
this version is obsolete but the gui has been taken over by someone else there is a link on the initial repo page.

However, gui uses old values that are depreciate, just load the script

**Comment by SEOAlexRamon** [comment]
I have done everything you tell me but I still have this problem.

https://fotos.subefotos.com/8f2843c437c4abdc8cb15b883b82d081o.jpg

**Comment by fxmeister** [comment]
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

https://landinghub.visualstudio.com/visual-cpp-build-tools returns a 404 error. Where do I download these elusive build tools for Windows?

**Comment by norm-l** [comment]
@ogtimothymiller [Try here](https://visualstudio.microsoft.com/visual-cpp-build-tools/)
