### ISSUE TITLE
Raspberry Pi issue, I'm lost...

### ISSUE THREAD

**Issue by skaeslin** [InstaPy/InstaPy#2492]
## Expected Behavior
Run Script on raspberry Pi 3 with chromedriver 2.33 like it did for a few months. Just to be sure I downloaded the newest instapy and installed it. It produced the error as shown below.

## Current Behavior
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-07-20 22:53:44] [USER]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

...................................................................
INFO [2018-07-20 22:54:23] [USER]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-07-20 22:54:30] [USER]  Tag [1/18]
INFO [2018-07-20 22:54:30] [USER]  --> justgoshoot
INFO [2018-07-20 22:54:42] [USER]  desired amount: 20  |  top posts [disabled]: 9  |  possible posts: 21951621

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-07-20 22:54:47] [USER]  Session ended - 2018-07-20 22:54:47
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "quickstart.py", line 41, in <module>
    session.like_by_tags(['justgoshoot'], amount=20)   
  File "/home/pi/Projects/instapy2/instapy/instapy.py", line 1189, in like_by_tags
    self.logger)
  File "/home/pi/Projects/instapy2/instapy/like_util.py", line 254, in get_links_for_tag
    "window.scrollTo(0, document.body.scrollHeight);")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: headless chrome=67.0.3396.87)
  (Driver info: chromedriver=2.33 (undefined),platform=Linux 4.14.52-v7+ armv7l)

## Possible Solution (optional)
I tried to apply the solution from thread [1338](https://github.com/timgrossmann/InstaPy/issues/1338#issuecomment-377718322) but I could not find the mentioned line in the script. I think it got changed over time. 

## InstaPy configuration
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = 'XXX'
insta_password = 'XXX'

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#   Settings.database_location = '/path/to/instapy.db'
#   Settings.chromedriver_location = '/path/to/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=1,
				  delimit_by_numbers=True,
				   max_followers=10000,
				    max_following=2000,
				     min_followers=400,
				      min_following=50)
    session.set_dont_include(['friend1'])
    session.set_dont_like(['pizza', 'girl', 'nsfw', 'naked'])
    session.set_delimit_liking(enabled=True, max=None, min=30)

    # actions
    session.like_by_tags(['justgoshoot'], amount=20)   
    session.follow_user_followers(['justgoshoot'], amount=1, randomize=False, sleep_delay=60)
    session.follow_by_tags(['justgoshoot'], amount=1)
    session.unfollow_users(amount=60, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)

    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

I'd be happy to hear any solutions or ideas how to fix this. Thanks a lot in advance!

**Comment by scizerr** [comment]
If i'm right chrome and chromedriver are not supported on raspberry because the arch is armhf

You can try it with firefox and geckodriver

**Comment by skaeslin** [comment]
Did that perhaps change recently? Because it worked for quite a while. 
But I'll try it with firefox for now, unless there's another solution. 
Thanks a lot!

**Comment by ccozkan** [comment]
Did you try with python 3

**Comment by JMuffin** [comment]
Have you tried to change chromedriver min. version in settings.py after update?
It keeps changing to 2.36 instead of 2.33 after every update :/

**Comment by andreescocard** [comment]
Follow the tutorial described in readme
If you have trouble with the chromedriver, download it again from here: https://packages.debian.org/stretch/armhf/chromium-driver/download
And move chromedriver to assets folder
Give permissions to chromedriver in assets folder
Use ", nogui=True" after set the password on Instapy function

Working for me here in raspberry pi 3 stretch

**Comment by skaeslin** [comment]
@ozkc I'll try to update to python 3, but I do not know how or if theres even a version 3 for the raspberry. But I'll find out! :D 

@JMuffin yes I konw. I changed that already. Thanks you! 

@andreescocard where can I set nogui=true  ?

**Comment by dds14** [comment]
@skaeslin you can set nogui=true in quickstart.py

**Comment by skaeslin** [comment]
@dds14 Thank you! 

I now know a bit more... I am actually able to login into instapy now. I don't what changed. BUT... instapy stops shortly after the login and first action with the same error description as above.

**Comment by skaeslin** [comment]
Alright now I changed the command to sudo python3.5 quickstart.py (so it will start with python3.5) and a new problem popped up:

 Traceback (most recent call last):
  File "quickstart.py", line 7, in <module>
    from instapy import InstaPy
  File "/home/pi/Projects/instapy2/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/home/pi/Projects/instapy2/instapy/instapy.py", line 22, in <module>
    from .comment_util import comment_image
  File "/home/pi/Projects/instapy2/instapy/comment_util.py", line 11, in <module>
    import emoji
ImportError: No module named 'emoji'


Tried this already #297 and it did install the emojis but... it still does not work.
