### ISSUE TITLE
interact_user_followers gives message: 'target_user' page does not contain a picture

### ISSUE THREAD

**Issue by daliborg** [InstaPy/InstaPy#2496]
Hi guys,

I am running 'interact_user_followers' and since last update I can see lot of below messages.
Did anyone face the same?

INFO [2018-07-21 10:50:06] [user]  User 'user1' [5/1000]
INFO [2018-07-21 10:50:06] [user]  Interaction [5/1000]  |  Total Interaction: 5
INFO [2018-07-21 10:50:06] [user]  Username [1/1]
INFO [2018-07-21 10:50:06] [user]  --> b'user1'
INFO [2018-07-21 10:50:59] [user]  User: user1 >> followers: 206  |  following: 501  |  relationship ratio: 2.43
INFO [2018-07-21 10:50:59] [user]  Getting user1 image list...
INFO [2018-07-21 10:51:24] [user]  Interaction begin...
INFO [2018-07-21 10:51:51] [user]  'user1' page does not contain a picture
INFO [2018-07-21 10:52:20] [user]  'user1' page does not contain a picture
INFO [2018-07-21 10:52:47] [user]  'user1' page does not contain a picture
INFO [2018-07-21 10:53:15] [user]  'user1' page does not contain a picture
INFO [2018-07-21 10:53:42] [user]  'user1' page does not contain a picture
INFO [2018-07-21 10:54:10] [user]  'user1' page does not contain a picture
INFO [2018-07-21 10:54:37] [user]  'user1' page does not contain a picture
INFO [2018-07-21 10:55:05] [user]  'user1' page does not contain a picture
INFO [2018-07-21 10:55:05] [user]  There are possibly less posts than 1 in user1's profile page!
INFO [2018-07-21 10:55:05] [user]  -------------
INFO [2018-07-21 10:55:05] [user]  --> Given amount not fullfilled, image pool reached its end

## InstaPy configuration

`    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-0.7)

    session.set_user_interact(amount=1, randomize=True, percentage=100, media='Photo')
    session.set_do_like(enabled=True, percentage=100)
    session.interact_user_followers(['user'], amount=1000, randomize=True)`

**Comment by spikeyhair** [comment]
Yes, I notice these error messages today.

**Comment by spikeyhair** [comment]
Anyone else notice this error messages? How do I fix it?

**Comment by gitpatrickhub** [comment]
@spikeyhair I'm seeing the same issue and appears to happen when the bot reaches a private account. Will try to look into further today.

**Comment by spikeyhair** [comment]
@gitpatrickhub yes I notice that too but not happen on all the private accounts.

**Comment by meinert** [comment]
To reduce the issue I have changed the retry attempt from 7 to 2 and changed the log message accordingly:

```
        if len(links) == len(initial_links):
            if attempt >= 2:
                logger.info("There are possibly less posts than {} in {}'s profile page or the profile is private!!".format(amount, username))
                break
            else:
                attempt += 1
```

**Comment by gitpatrickhub** [comment]
In the like_util.py file the get_links method is missing the check for Private Accounts. I've modified the code to the below.

```
def get_links(browser, page, logger, media, element):
    # Check for private account
    try:
        is_private = body_elem.find_element_by_xpath(
            '//h2[@class="rkEop"]')
    except:
        logger.info('Interaction begin...')
        # Get image links in scope from hashtag, location and other pages
        link_elems = element.find_elements_by_tag_name('a')
        sleep(2)
        links = []
        try:
            if link_elems:
                new_links = [link_elem.get_attribute('href') for link_elem in link_elems
                             if link_elem and link_elem.text in media]
                links.extend(new_links)
            else:
                logger.info("'{}' page does not contain a picture".format(page))
        except BaseException as e:
            logger.error("link_elems error {}".format(str(e)))
        return links
    else:
        if is_private:
            logger.warning('This user is private...')
            return False
```    
However, it's not finding the XPath for the Private Account

<img width="702" alt="screen shot 2018-07-27 at 11 57 06 am" src="https://user-images.githubusercontent.com/29474212/43335093-483541cc-9194-11e8-9096-6513372b104d.png">

Need someone with more XPath experience to help figure this one out. @uluQulu any chance you can point me in the correct direction?

**Comment by uluQulu** [comment]
Hi @gitpatrickhub 
I can help you find its XPATH.
Just right-click on the inspected code and choose **Copy XPATH** and then check it in the **Console** by running this,
```python
$x("\some\XPATH('here')")
```
But the thing is you don't need those modifications.
Why?
Cos `get_links` definition is just for grabbing links from a readily loaded page.
And it is being called from several main functions, such as `get_links_for_username` WHICH is checking the profile for **privateness**.

I can assume that it failed to function properly at that stage and it is obvious cos the current code of checking privateness is sometimes misfunctions cos of the beta updates in its XPATH.
There is an open PR which is touching that issue, have a read it and apply its modification by hand, and it will solve all your issues in that matter.

>BTW your efforts are great, keep writing code, you are improving so fast!
  
**BONUS**: I have talked a bit about it in https://github.com/timgrossmann/InstaPy/issues/2484#issuecomment-406616225 where you can see and applying that required change for checking **privateness**.


Chill 😎

**Comment by gitpatrickhub** [comment]
@uluQulu thanks for the quick reply. I see there are 2 separate PRs on this topic with different approaches and both are awaiting to pass checks/merge. 

I see the better place to make the change in the code, as you suggest in your comment. However, from my screenshot above the XPath appears to be correct and should still work as I have implemented it. When I use your method to get XPath, it returns this;
```
//*[@id="react-root"]/section/main/div/div[2]/article/div/div/h2
```
I validate it in the console 

<img width="556" alt="screen shot 2018-07-27 at 2 23 02 pm" src="https://user-images.githubusercontent.com/29474212/43342540-9ecbf562-91a8-11e8-8e39-a04dfecc5298.png">

So what is the proper method to refer to this element in the code?
