### ISSUE TITLE
Unfollow Only script - onlyInstapyFollowed breaks script

### ISSUE THREAD

**Issue by boldestfortune** [InstaPy/InstaPy#2499]
## Expected Behavior
Typical Unfollow command
## Current Behavior
[18824:5396:0721/190147.200:ERROR:install_util.cc(589)] Unable to create registry key HKLM\SOFTWARE\Policies\Google\Chrome for reading result=2

DevTools listening on ws://127.0.0.1:52139/devtools/browser/2cb2f725-f0cb-45c7-a932-4e3a48dc1dd2

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-07-21 19:01:48] [username]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo

...............................................................
INFO [2018-07-21 19:02:20] [username]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-07-21 19:02:26] [username]  Session ended - 2018-07-21 19:02:26
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "unfollow.py", line 26, in <module>
    session.unfollow_users(amount=150, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=600 )
TypeError: unfollow_users() got an unexpected keyword argument 'onlyInstapyFollowed'
## InstaPy configuration
session.login()
    session.unfollow_users(amount=300, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=655, unfollow_after=48*60*60)
    session.set_dont_unfollow_active_users(enabled=True, posts=3)

except Exception as exc:
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    raise

finally:
    # end the bot session
    session.end()

edit: I was able to make the xpath changes as per the xpath Issue in unfollow_util, but the error seems to be with "onlyinstapyfollowed" Command

Thank you.

**Comment by HCWcoder** [comment]
please Check this : 

https://github.com/timgrossmann/InstaPy#unfollowing
