### ISSUE TITLE
Cor! Did you send too many requests? ~ let's rest some

### ISSUE THREAD

**Issue by 46960** [InstaPy/InstaPy#2506]
Getting this _all the time_ when trying to like hashtags. Even if I didn't even like as many. Like after 3-5 likes I get it. I dont like super fast or send too many requests, yet still i'm getting it. Any idea why this is happening and how to resolve it?

**Comment by 46960** [comment]
Has no one else gotten this?

**Comment by eGancio** [comment]
yes me too, and I can't edit the code to skip it.
