### ISSUE TITLE
'bool' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by lowtar** [InstaPy/InstaPy#2508]
Hope you guys can help me on this one. This "FIX: updated xpath in unfollow util #2463" doesn't work for me. Have tested it.

## Expected Behavior
Unfollow all users except the ones that liked your previous 5 posts.

## Current Behavior
Error: 
"Sorry, an error occured: 'bool' object has no attribute '__getitem__'"

## InstaPy configuration
    session.set_dont_unfollow_active_users(enabled=True, posts=5)
    session.unfollow_users(amount=2000, allFollowing=True, style="RANDOM", sleep_delay=300)

**Comment by michaelBielang** [comment]
Sadly it doesn't work for a lot of people here, me included -_- 
I am not so deep into Github and these things but I guess that this repository will no longer be updated? I see some open pull request which are open now for weeks.
Is there another fork that is working and active in development?

**Comment by uluQulu** [comment]
@lowtar, @realsony 
Hey guys
I had a chance to look at the issue and found out the cause and solved it.  
Please read https://github.com/timgrossmann/InstaPy/issues/2501#issuecomment-407318433 to see the solution 🎊!


Hey @realsony, it works flawlessly most of time, from time to time issues raise up to this- one of the most active software in GitHub 😁 and once there is an issue, there are tons of great people ready to solve it, just ask away 🙋🏼‍♂️!
GitHub has a very easy interface, all you need is to read instructions to do whatever you like, unless you decide to mess up with `git` 😂😂😂😂😂🤩  
I think cos of it is hot summer and people having lots of stuff to do, it is not as active as was in spring 😎 but the repo has no any serious issues I know of.

Yes there are bunch of **open** PRs for a long time, well, some of them are not yet in good shape, some of them are still in discussion, others are not fully agreed but good news is all are still there and once gets ready will immediately be merged, etc.
**master** is the only most active best branch to use cos it is actively getting a piece of code from tons of people 🎉
@realsony. reading your words above, I felt to reply it 😉


Cheers 😁

**Comment by michaelBielang** [comment]
Ty a lot ulu! Great work, it is running again <3

**Comment by mattionline** [comment]
@uluQulu works. thanks
