### ISSUE TITLE
issue with my code ?

### ISSUE THREAD

**Issue by HCWcoder** [InstaPy/InstaPy#2514]
## Current Behavior
    sometimes :
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\testing\Documents\GitHub\InstaPy\xxx.py", line 31, in job
    session.interact_user_followers(['x', 'xx', 'xxx','xxxx'], amount=25, randomize=True)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\instapy.py", line 1856, in interact_user_followers
    self.user_interact_media)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\instapy.py", line 1576, in interact_by_users
    self.logger)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\util.py", line 77, in validate_username
    followers_count, following_count = get_relationship_counts(browser, username, logger)
  File "C:\Users\testing\Documents\GitHub\InstaPy\instapy\util.py", line 513, in get_relationship_counts
    "//span[contains(@class,'g47SY')]")[1].text))
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\testing\Documents\GitHub\InstaPy\xxx.py", line 47, in <module>
    job()
  File "C:\Users\testing\Documents\GitHub\InstaPy\xxx.py", line 42, in job
    except WebDriverException:
NameError: name 'WebDriverException' is not defined
## InstaPy configuration
        session.set_user_interact(amount=1, randomize=True, percentage=100, media='Photo')
        #session.set_skip_users(skip_private=True, skip_no_profile_pic=True, min_media=10)
        session.set_do_follow(enabled=True, percentage=100)
        session.set_do_like(enabled=True, percentage=100)
        
        session.set_comments(['Great shot', 'Amazing','wow habet'])
        session.set_do_comment(enabled=True, percentage=25)
        
        session.set_use_clarifai(enabled=True, api_key='xxx')
        session.clarifai_check_img_for(['nsfw'])
        session.clarifai_check_img_for(['food', 'lunch', 'cake', 'sweet', 'chicken', 'tasty', 'barbecue'], comment=True, comments=['Tasty!', 'Yum!', 'Delicious'])
        session.clarifai_check_img_for(['people', 'woman', 'adult', 'man', 'group'], comment=True, comments=['Epic !!', 'look nice'])

        session.interact_user_followers(['x', 'xx', 'xxx','xxxx'], amount=25, randomize=True)
        #
        #session.follow_likers (['x' , 'xx', 'xxx','xxxx'], photos_grab_amount = 2, follow_likers_per_photo = 3, randomize=True, sleep_delay=600, interact=True)
        #session.follow_commenters(['x', 'xx', 'xxx', 'xxxx'], amount=100, daysold=365, max_pic = 100, sleep_delay=600, interact=False)
        #
        # unfollow
        session.unfollow_users(amount=60, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)

        session.end()
    except KeyboardInterrupt:
        session.end()
    except WebDriverException:
        pass
    except:
        import traceback
        print(traceback.format_exc())
job()
schedule.every().day.at("08:15").do(job)
schedule.every().day.at("10:15").do(job)
schedule.every().day.at("13:00").do(job)
schedule.every().day.at("15:13").do(job)
schedule.every().day.at("17:00").do(job)
schedule.every().day.at("19:00").do(job)
schedule.every().day.at("21:00").do(job)
schedule.every().day.at("23:00").do(job)
schedule.every().day.at("04:00").do(job)

while True:
    schedule.run_pending()
    time.sleep(1)

**Comment by Tachenz** [comment]
Yep - getting a lot of folks with this one - https://github.com/timgrossmann/InstaPy/issues/2513
