### ISSUE TITLE
Unfollow not following issue

### ISSUE THREAD

**Issue by HCWcoder** [InstaPy/InstaPy#2517]
## Current Behavior
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-07-24 09:14:39] [xxx]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo

............................................................
INFO [2018-07-24 09:15:16] [xxx]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

_________________________________________________________________
INFO [2018-07-24 09:15:21] [xxx]  Starting to unfollow users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-07-24 09:15:21] [xxx]  Unfollowing the users who do not follow back

INFO [2018-07-24 09:15:21] [xxx]  Retrieving live `Followers` data of xxx at "full" range
  3601/10300 [============+-----------------------]  34%    |> Elapsed: 4.07 minutes    |> ETA: 7.9 minutes

INFO [2018-07-24 09:19:31] [vixoo7]  Queried too much! ~ sleeping a bit :>
  3618/10300 [============+-----------------------]  35%    |> Elapsed: 16.32 minutes    |> ETA: 30.31 minutes

ERROR [2018-07-24 09:32:21] [xxx]  Sorry, an error occured: 'NoSuchElementException' object has no attribute 'encode'

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-07-24 09:32:23] [xxx]  Session ended - 2018-07-24 09:32:23
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
## InstaPy configuration
def job():
    try:
        session = InstaPy(username=insta_username, password=insta_password, bypass_suspicious_attempt=True, multi_logs=True, headless_browser=True)
        session.login()

        # unfollow

        session.unfollow_users(amount=126, nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)

        session.end()
    except KeyboardInterrupt:
        session.end()
    except WebDriverException:
        pass
    except:
        import traceback
        print(traceback.format_exc())

**Comment by HCWcoder** [comment]
Worked after trying more !
closed

**Comment by Wraitheye** [comment]
Hi, I have kind of the same issue, how did you solve it?

Starting to unfollow users..
INFO [2018-07-26 20:25:20] [x]  Unfollowing the users followed by InstaPy

INFO [2018-07-26 20:25:20] [x]  Retrieving live `Followers` data of arthur_le_goff at "full" range
ERROR [2018-07-26 20:25:47] [x]  Sorry, an error occured: 'NoSuchElementException' object has no attribute 'encode'
INFO [2018-07-26 20:25:52] [x]  Getting active users who liked the latest 5 posts:
  ~collecting the usernames from posts with the boundary of 500
INFO [2018-07-26 20:26:19] [x]  Failed to get likers count on your post 1
INFO [2018-07-26 20:27:37] [x]  Failed to get likers count on your post 2
...
INFO [2018-07-26 20:32:23] [x]  Gathered total of 0 unique active followers from the latest 5 posts in 6 minutes and 31 seconds
INFO [2018-07-26 20:32:24] [x]  Session ended - 2018-07-26 20:32:24

**Comment by dixitpatel89** [comment]
_________________________________________________________________
INFO [2018-07-28 05:02:37] []  Starting to unfollow users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-07-28 05:02:37] []  Unfollowing the users who do not follow back

INFO [2018-07-28 05:02:37] []  Retrieving live `Followers` data of  at "full" range


ERROR [2018-07-28 05:02:40] []  Sorry, an error occured: 'AttributeError' object has no attribute 'encode'

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-07-28 05:02:40] [byhues]  Session ended - 2018-07-28 05:02:40
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by ammiratafabiano** [comment]
@dixitpatel89 I have the same problem. Did you fix it?

**Comment by w4ngel** [comment]
Getting the same error except with this:
` Unable to get `Followers` data:
        Message: Unable to locate element: pre`
