### ISSUE TITLE
Invalid Like Element!

### ISSUE THREAD

**Issue by RobertoGD** [InstaPy/InstaPy#2531]
## Expected Behavior
Like
## Current Behavior
Nothing
## InstaPy configuration
Basic

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.21,
				  delimit_by_numbers=True,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    # session.set_do_comment(True, percentage=10)
    # session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    # session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'stupid'])

    # actions
    session.like_by_tags(['travel'], amount=5)

I set everything correctly, bot is checking each post, works without issue except one. Not liking.
I can always see this:

--> Invalid Like Element!

Don't know why. Instagram changed again buttons for that?
I'm running it locally on my Mac 

I've been looking for all existing solutions but nothing work. like_util.py is up to date.
Actually I have Master branch with all latest updates.

Could you help me?

Thanks

**Comment by maxxfly** [comment]
I have the same issue here

**Comment by delongg** [comment]
same here

**Comment by andradjp** [comment]
Same problem

**Comment by ianzitow** [comment]
I created a fix, not sure if it's good: https://github.com/timgrossmann/InstaPy/pull/2532

**Comment by will-holley** [comment]
+1

**Comment by Mehran** [comment]
Same today .

**Comment by ghost** [comment]
same here

**Comment by HCWcoder** [comment]
Its fixed after updating this code !
@ianzitow thanks

**Comment by ghost** [comment]
@ianzitow it works thanks!
