### ISSUE TITLE
Limit daily count of follows/likes

### ISSUE THREAD

**Issue by mattdeveluk** [InstaPy/InstaPy#254]
Is there a way you can limit amount of daily follows/likes for bot ?

**Comment by newme616** [comment]
yeah that would be great to know, especially if you want to run it 24/7

**Comment by brodydrey2296** [comment]
I think it would be good to have an hourly limit of 200 follows, because at around 250 an hour your password will be reset. And also setting a total follow goal so you can run 24/7

**Comment by snakelab** [comment]
I am working on that PR (https://github.com/timgrossmann/InstaPy/pull/680), and will add also an hourly limit (which i also run into) - work in progress...

**Comment by converge** [comment]
our friend @snakelab closed his PR, after #853 merge we can have it. The feature is 90% done, just need to check the limits while running, at the moment is just checking when beginning interaction.
```python
session.set_daily_interactions(likes=100, comments=100, follows=100, unfollows=100, server_calls=1000)
```

there is a point to be done, should we have pre defined values for the limitations ?

**Comment by converge** [comment]
one day after, we're again at 90% , I thought it would be easier, had to change somethings, there is a PR #859 (work in progress, needing help)

**Comment by ugurozturk** [comment]
it would be amazing

**Comment by ShiftingKill** [comment]
For likes, running 24/7 means hitting around 2000 likes in 24 hours. 2000/24=83.33 likes per hour.
(60 minutes/1hour)/83.33 likes maximum per hour =  .7200 * (60 seconds/1 min) = 43.2 seconds/ 1 like.
To verify there are 86,400 seconds in a day divided by 43.2 seconds = 2000 likes.
So set your page_delay in instapy.py to like 38 or something. But don't take my word for it. This is all based on being shadowbanned 4 times and learning the speed limit of running 24/7. Don't let those "350 an hour like limits" fool you.
