### ISSUE TITLE
error while unfollowing

### ISSUE THREAD

**Issue by HCWcoder** [InstaPy/InstaPy#2542]
## Current Behavior
ERROR [2018-07-26 15:11:52] [xxx]  --> Unfollow error with b'example', maybe no longer exists... ERROR [2018-07-26 15:11:52] [xxx]  Unfollow loop error:  Message: unknown error: Cannot read property 'activity_counts' of undefined   (Session info: headless chrome=67.0.3396.99)   (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.16299 x86_64)
## InstaPy configuration
session.unfollow_users(amount=100, nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=400)

**Comment by the-unknown** [comment]
same here..

**Comment by ghost** [comment]
and here

**Comment by meinert** [comment]
Same here. Have tried to debug but the variable in the error message is nowhere to be found? activity_counts?

**Comment by ramzi111** [comment]
and here

**Comment by gitpatrickhub** [comment]
I'm receiving this error for quite a few accounts;

"maybe username has changed or he/she blocked you..."

The error message is accurate, many cases the user has changed their name. But in other cases, I can see the bot navigate to the page and the "Unfollow' does not occur. I do not see anything on the page that is "blocking/blocked".

Any one else experiencing this issue?

**Comment by the-unknown** [comment]
Same issue here. And what is bothering me with this: I was running the bot for the last 2 weeks non-stop. And now I did a "unfollow all". What happens is: I have about 600 Followers, that the bot is unable to unfollow. And that's quite annoying as I have to unfollow these by hand now.

**Comment by HCWcoder** [comment]
@the-unknown did you update and re install instapy ?

**Comment by the-unknown** [comment]
@HCWcoder  I did now.. just yesterday.. don't have recent data to confirm if the issue is still there.
