### ISSUE TITLE
session.set_blacklist(enabled=True, campaign='jjj') is not working

### ISSUE THREAD

**Issue by brocool** [InstaPy/InstaPy#2545]
the bot just commented on 2 pictures of the same account... it is not working. i thought it should comment and like only once in an account with session.set_blacklist(enabled=True, campaign='jjj')?

**Comment by brocool** [comment]
here's the proof 
![untitled](https://user-images.githubusercontent.com/41244025/43265568-29984cea-90fa-11e8-8036-0c16c7094b80.png)

**Comment by sionking** [comment]
The issue is known, once the action is done, it will only sit in the disk but the memory still don't know of this user activity until next time we start the application.

**Comment by brocool** [comment]
@sionking ohhh i see... so it will only apply once i restart the software?
