### ISSUE TITLE
Insufficient amount of links trying again...

### ISSUE THREAD

**Issue by gotsomequestions** [InstaPy/InstaPy#2546]
## Expected Behavior
start with the new hashtag and like desired amount 
## Current Behavior
Insufficient amount of links ~ trying again: 1
Insufficient amount of links ~ trying again: 2
Insufficient amount of links ~ trying again: 3
Cor! Did you send too many requests? ~ let's rest some

this happens before EVERY hashtag

## InstaPy configuration
got the latest patch, but have this problem since 5 days..... 
maybe relevant: I added in the instapy file to execute the bot in incognito chrome mode to run 2 accounts at the same time

 #chrome_options.add_argument("--disable-infobars")
            chrome_options.add_argument("--incognito")
            chrome_options.add_argument('--dns-prefetch-disable')
            chrome_options.add_argument('--lang=en-US')
            chrome_options.add_argument('--disable-setuid-sandbox')

thanks for helping

**Comment by HCWcoder** [comment]
what is your instapy setup ? @gotsomequestions

**Comment by gotsomequestions** [comment]
This is my setup:
potency_ratio=-1.21,
max_followers=4569,
max_following=5555,
min_followers=45,
min_following=77,
amount=60.
Maybe it's because of the incognito mode?

**Comment by botboteverywhere** [comment]
@gotsomequestions @HCWcoder I've had the same pb for more than a week as well. I don't use any incognito mode though.
Usually I solve the pb by pressing CMD + down arrow, to force the page to load more images (and therefore get more links). But it is strange as there seems to be already plenty enough of links on the initial page. 

Manual intervention for every hashtag is far from convenient

**Comment by 46960** [comment]
I'm getting the _Cor! Did you send too many requests? ~ let's rest some_ every. damn. time. It's been weeks now. it's just not working for me anymore. there doesn't seem to be any solution to this, I have almost completely given up on using the like bot anymore. Would really appreciate some help!

**Comment by kukkakeppi** [comment]
I got exactly the same message when I had too many hashtags or if I had "banned" hashtags in my criteria.

Try to use more common or general hashtags and be careful how many interactions you want to make.

I also kept ~3 days break from running the script, which might have helped. Just wanted to make sure I didn't have "soft ban".

**Comment by gotsomequestions** [comment]
@46960 @botboteverywhere , I solved the problem for me, if I dont minimize the Chrome Windows, where you can watch the bot work, it works as usual. Just keep it open all the time, maybe it also works for you. And I work it on Spyder instead of the windows command like before..
