### ISSUE TITLE
instapy for newbies ? Question about : why the  script don't work 

### ISSUE THREAD

**Issue by newbie-dev7** [InstaPy/InstaPy#255]
hello and hi everyone 
after multiple attempt i still not able to find out why the only things that work is the ''like/comment'' 
the '' follow /unfollow ''never worked i'm a bit in the mud , is there a good samaritan to drive me into this 
i'm running on OSX 
this is what my quickstart.py look like 
InstaPy(nogui=False , username="smth", password="smth")\
  .login()\
  .set_upper_follower_count(limit = 2000) \
  .set_do_comment(True, percentage=7) \
  .set_comments(['nice shot)!', 'lovely', ':)',]) \
  .set_comments(['Nice Vid!'], media='Video') \
  .set_dont_include(friend_list) \
  .set_dont_like(dont_like) \
  .set_ignore_if_contains(['amblard']) \
  .like_by_tags(['tag1','veggies','tag3','tag','tag','landscape',], amount=100) \
  .set_do_follow(enabled=True, percentage=50, times=2) \
  .unfollow_users(True, percentage=10, times=1) \
  .end()
thanks a lot

**Comment by converge** [comment]
@newbie-dev7 hey, show us the error message.

**Comment by newbie-dev7** [comment]
this is the error message if i put percentage on both set_do_follow and set_unfollow 
Traceback (most recent call last):
  File "quickstart2.py", line 24, in <module>
    .set_do_follow(enabled=True, amount=10, times=1) \
TypeError: set_do_follow() got an unexpected keyword argument 'amount'


and this is the error message if i put amout 
  File "quickstart2.py", line 24, in <module>
    .set_do_follow(enabled=True, percentage=10, times=1) \
AttributeError: InstaPy instance has no attribute 'set_unfollow'

and with both methodes its dosnt either follow or unfollow any acc :/

**Comment by converge** [comment]
**set_do_follow** usage is:
session.set_do_follow(enabled=True, percentage=10, times=2)

there is no **set_unfollow**, to unfollow use:
session.unfollow_users(amount=10)

**Comment by newbie-dev7** [comment]
its look like instagram servers is down 
i'll try this as soon as it came back online and keep you updated 
lots of thanks for the support .

**Comment by sunnypatel165** [comment]
@newbie-dev7 do you still face this? If not, kindly close this. Let's keep the issues section clean - too many help wanted's already.

**Comment by sunnypatel165** [comment]
PS - I wouldn't believe the "Instagram server is down" part. I've never faced such an issue with insta yet. Show us your quickstart, to see why it's not following/unfollowing people. @newbie-dev7

**Comment by newbie-dev7** [comment]
sorry for the delay i was on final school test .
ok so there is what it look like now and its still does not follow anyone 

 .login()\
  .set_upper_follower_count(limit = 1700) \
  .set_lower_follower_count(limit = 55) \
  .set_dont_include(friend_list) \
  .set_dont_like(dont_like) \
  .set_ignore_if_contains(['mum']) \
  .like_by_tags(['color',], amount=103) \
  .set_do_follow(enabled=True, percentage=30, times=2) \
  .end()

sorry for the delay i was on final school test .
ok so there is what it look like now and its still does not follow anyone 
i'm still confused i didnt tried the ''.unfollow_users(amount=10)'' yet because there is no point since he dosent follow anyone new i would have just lost my actual real life friends on instagram  .

Side question : do i have to handwrite my friendlist in the .*** here ''set_dont_like(****)'' or is there any way i can get my friendlist in a txt to prevent unfollowing my friends before i start using this line 
''.unfollow_users(amount=10)?''

**Comment by sunnypatel165** [comment]
```set_do_follow``` needs to be before ```like_by_tags```.
 See the updated doc in the README.
PS - Don't think there is a way you can specify entire friend list - unfortunately.
