### ISSUE TITLE
When running unfollow

### ISSUE THREAD

**Issue by Wraitheye** [InstaPy/InstaPy#2552]
## Expected Behavior
Log separately and unfollow non followers

## Current Behavior
____________________________________________________________________
INFO [2018-07-27 12:42:42] [x]  Starting to unfollow users..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-07-27 12:42:49] [x]  Unfollowing the users who do not follow back

INFO [2018-07-27 12:42:49] [x]  Retrieving live `Followers` data of grumpriam at "full" range

ERROR [2018-07-27 12:43:16] [x]  Sorry, an error occured: 'NoSuchElementException' object has no attribute 'encode'

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-07-27 12:43:16] [x]  Session ended - 2018-07-27 12:43:16
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

## Possible Solution (optional)

I must admit I'm lost

## InstaPy configuration

from instapy import InstaPy

/# Write your automation here
/# Stuck ? Look at the github page or the examples in the examples folder

insta_username = 'x'
insta_password = 'x'

friend_list = ['']

/# If you want to enter your Instagram Credentials directly just enter
/# username=<your-username-here> and password=<your-password> into InstaPy
/# e.g like so InstaPy(username="instagram", password="test1234")

session = InstaPy(username=insta_username, password=insta_password, bypass_suspicious_attempt=True, multi_logs=True, headless_browser=True)
session.login()

/# Log separately for Multiple Accounts

session = InstaPy(username=insta_username, password=insta_password, multi_logs=True)

/# Unfollow the users WHO do not follow you back:

session.unfollow_users(amount=126, nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)

session.end()

**Comment by dixitpatel89** [comment]
I am also getting same error _________________________________________________________________
INFO [2018-07-28 04:55:58] [byhues]  Starting to unfollow users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-07-28 04:55:59] [byhues]  Unfollowing the users who do not follow back

INFO [2018-07-28 04:55:59] [byhues]  Retrieving live `Followers` data of byhues at "full" range


ERROR [2018-07-28 04:56:01] [byhues]  Sorry, an error occured: 'AttributeError' object has no attribute 'encode'

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-07-28 04:56:01] [byhues]  Session ended - 2018-07-28 04:56:01
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by dixitpatel89** [comment]
_________________________________________________________________
INFO [2018-07-28 04:55:58] []  Starting to unfollow users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-07-28 04:55:59] []  Unfollowing the users who do not follow back

INFO [2018-07-28 04:55:59] []  Retrieving live `Followers` data of user at "full" range


ERROR [2018-07-28 04:56:01] []  Sorry, an error occured: 'AttributeError' object has no attribute 'encode'

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-07-28 04:56:01] []  Session ended - 2018-07-28 04:56:01
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by RafNadler** [comment]
I have the same issue, any idea ?
