### ISSUE TITLE
Follow Likers not working

### ISSUE THREAD

**Issue by s-h-a-d-o-w-pixel** [InstaPy/InstaPy#2554]
## Expected Behavior
Follow likers of the latest photo. Everything was fine a couple days ago.

## Current Behavior
Now I get this (replaced names and links with "****"):

('\nGetting likers from user: ', '0000', '\n')
('Got ', 12, ', returning ', 1, ' links: ', [u'https://0000'])
opening likes
Scrolling finished
Like window closed
('\nGot ', 0, ' likers shuffled randomly, who you can follow:\n', [], '\n')

## InstaPy configuration

session.follow_likers(['0000'], photos_grab_amount=1, follow_likers_per_photo=3, randomize=False, sleep_delay=600, interact=True)

Thanks

**Comment by meinert** [comment]
See #2526 ......I have made a merge request (#2556) with a fix
