### ISSUE TITLE
FollowUsersFollowers: IndexError: list index out of range

### ISSUE THREAD

**Issue by sunnygill** [InstaPy/InstaPy#2555]
I have been keeping up with the latest tip but since last week I have seeing below error every couple of hours  when trying to follow user followers. Does anybody has a solution for it. 

Traceback (most recent call last):
  File "/local/mnt/workspace/sgill/build217/InstaPy/stufffollow.py", line 351, in <module>
    followUserFollowers()
  File "/local/mnt/workspace/sgill/build217/InstaPy/stufffollow.py", line 114, in followUserFollowers
    session.follow_user_followers(settingsstuff.getRandomUsers(30), amount=10, randomize=True, interact=True, sleep_delay=140)
  File "/local/mnt/workspace/sgill/build217/InstaPy/instapy/instapy.py", line 2040, in follow_user_followers
    self.logfolder)
  File "/local/mnt/workspace/sgill/build217/InstaPy/instapy/unfollow_util.py", line 872, in get_given_user_followers
    simulation, channel, logger, logfolder)
  File "/local/mnt/workspace/sgill/build217/InstaPy/instapy/unfollow_util.py", line 679, in get_users_through_dialog
    if quick_username[0] not in simulated_list:
IndexError: list index out of range

**Comment by LeoKolade** [comment]
same problem here

**Comment by bongo48** [comment]
same issue

**Comment by sunnygill** [comment]
@uluQulu any solution for this mate?

**Comment by uluQulu** [comment]
Hi @sunnygill 
Do you have the latest files? (_see `git status`_)

**Comment by sunnygill** [comment]
Hi @uluQulu,  
Yes i synced it today afternoon and git status does not have any pending changes. 
Below is the snippet of git log

> commit dec5da75199e76b14d828e8e49b67a96de3cc425
Merge: 647dc3d a8a8108
Author: Tim Großmann <t.grossmann1994@web.de>
Date:   Fri Aug 3 17:45:09 2018 +0200

    Merge pull request #2609 from timgrossmann/pr/2426
    
    Faster way to check if user is private

commit 647dc3d14c1d4329267218da69d27d3f702df41f
Merge: 601592b 17ca8d3
Author: Tim Großmann <t.grossmann1994@web.de>
Date:   Fri Aug 3 14:01:25 2018 +0200

    Merge pull request #2605 from rafaelfcsouza/fix-on-create-db
    
    Fix Problem on Create Database

commit 17ca8d3a99755dbb887db0761ef1802da0b016d2
Author: Rafael Souza <rafael.souza@careem.com>
Date:   Fri Aug 3 13:43:50 2018 +0200

    Fix Problem on Create Database
    
    Small refactor on Create Database and Get Database Logic on instapy/database_engine.py
    Separated logic into small functions for better redability and removed comments (functions names have full name now)
    Separated SQL into constants
    
    Fixes #2588

commit a8a8108010527a5084db8298be4b55c83bf96553
Author: timgrossmann <t.grossmann1994@web.de>
Date:   Fri Aug 3 12:30:07 2018 +0200

    add sionking and mehdichekori changes to is_private

commit 601592b14bb9c1fefd4940fa54df35fdabbe51b1
Merge: d86c660 087be04
Author: Tim Großmann <t.grossmann1994@web.de>
Date:   Fri Aug 3 11:41:53 2018 +0200

    Merge pull request #2607 from uluQulu/master
    
    Fix for the most nasty bug off #2563

commit 087be0443d0594c775615ae19b04ca170ef6b9f3
Author: Qulu <shahriyarguliyev@hotmail.com>
Date:   Fri Aug 3 03:06:01 2018 +0400

    Fix for the most nasty bug off #2563
    
    """
    Heeh! Error occured while getting a DB profile for 'None':
    	b'NOT NULL constraint failed: profiles.name'
    """

commit d86c660d4887fb47a833bf9ce1c8e46d71bb162b
Merge: 5ccdbc5 72cd28a
Author: Tim Großmann <t.grossmann1994@web.de>
Date:   Thu Aug 2 13:21:15 2018 +0200

    Merge pull request #2600 from timgrossmann/hotfix/nonetypeDB
    
    hot-fix for NoneType DB

>

**Comment by uluQulu** [comment]
Alright, @sunnygill, I have looked into your issue and since there is no any problems in my side I couldn't debug the problem.  

If you provide a troubleshoot information, I can help you solve it.  

* _**Open** up **unfollow_util.py** file_,
  
**1**-) in `get_users_through_dialog` definition, **add** a new `print` line as below:
```python
print("\n\nDEBUGGER:\n\t", quick_button, "\n\t", quick_username, "\n\n")   ##NEW DEBUG LINE
if quick_username[0] not in simulated_list:
```
  **2**-) in `dialog_username_extractor` definition, **add** a new `raise` line:
```python
except IndexError:
    raise   ##NEW DEBUG LINE
    pass  # Element list is too short to have a [1] element
```

* Do you get that error always or sometimes?

------------------



Cheers 😁

**Comment by sunnygill** [comment]
Hi @uluQulu 

I can reproduce 100% of time. Find the below debug logs you asked for:

`INFO [2018-08-04 12:07:26] [stf]  --> Followed b'ourshadesofgreen'
INFO [2018-08-04 12:07:29] [stf]  Simulated follow : 2


DEBUGGER:
         <selenium.webdriver.remote.webelement.WebElement (session="f66f2486ba31b5e5b97c2676215ae725", element="0.19588227572136252-43")>
         ['kimikokibo']


INFO [2018-08-04 12:07:31] [stf]  --> Followed b'kimikokibo'
INFO [2018-08-04 12:07:32] [stf]  Simulated follow : 3


DEBUGGER:
         <selenium.webdriver.remote.webelement.WebElement (session="f66f2486ba31b5e5b97c2676215ae725", element="0.19588227572136252-21")>
         ['angelamatovska']


INFO [2018-08-04 12:07:34] [stf]  --> Followed b'angelamatovska'

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-08-04 12:08:02] [stf]  Session ended - 2018-08-04 12:08:02
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "stufffollow.py", line 351, in <module>
    followUserFollowers()
  File "stufffollow.py", line 114, in followUserFollowers
    session.follow_user_followers(settingsstuff.getRandomUsers(30), amount=10, randomize=True, interact=True, sleep_delay=140)
  File "/local/mnt/workspace/sgill/build217/InstaPy/instapy/instapy.py", line 2031, in follow_user_followers
    self.logfolder)
  File "/local/mnt/workspace/sgill/build217/InstaPy/instapy/unfollow_util.py", line 871, in get_given_user_followers
    channel, logger, logfolder)
  File "/local/mnt/workspace/sgill/build217/InstaPy/instapy/unfollow_util.py", line 695, in get_users_through_dialog
    person_list = dialog_username_extractor(buttons)
  File "/local/mnt/workspace/sgill/build217/InstaPy/instapy/unfollow_util.py", line 720, in dialog_username_extractor
    .find_elements_by_tag_name("a")[1].text)
IndexError: list index out of range
`

**Comment by uluQulu** [comment]
It's clear, @sunnygill 
To **solve**, **open** up **unfollow_util.py** file,
**find** `get_users_through_dialog` definition and **replace**:
```python
if quick_username[0] not in simulated_list:
```
**with**
```python
if quick_username and quick_username[0] not in simulated_list:
```
And remove all of the **debug** lines from the previous post.

----------

_Although this will solve the program from crashing, I could not understand why such a follow button could behave so_ 🤔

* My bonus questions are:
**1**-) Do you see that problem too many times (_e.g. in every session_)
**2**-) Have you faced that problem before the recent times?

-------------

Cheers 😁

**Comment by sunnygill** [comment]
thanks @uluQulu . I have made the change and giving it a try.  Will let you know how it goes. 

1-) Do you see that problem too many times (e.g. in every session)
yes i see it in every session, right after few mins. 
2-) Have you faced that problem before the recent times?
no i haven't faced this problem before. I synced to the tip last a week back once i start seeing "invalid like element issue". After that this issue was consistent. 

I am using ubuntu 14.04 and didn't updated anything on it.

**Comment by MacroAnarchy** [comment]
If anyone ever stumbles upon this again:

It happens if you write any usernames in the config file in CAPITAL letters. 
Don’t use capital letters in usernames, since Instagram doesn’t, and your good to go. 🙏
