### ISSUE TITLE
Couple questions: unfollow max per day and using app while script runs?

### ISSUE THREAD

**Issue by deronsizemore** [InstaPy/InstaPy#256]
My intention is to start the script in the morning and let it run most of the day. Can anyone recommend a max number for `.unfollow_users()`?

Given that instagram only allows unfollowing 10 users every 10 minutes, that means over the course of a day while working and letting the script run, I'd unfollow around 240 people. Is that too much? Should I set the `amount=` parameter lower than 240 to ensure I don't trigger any instagram flags?

Just curious what others have seen after their testing.

I was also curious if I can still use the instagram app and follow, unfollow, post, like, etc. while the script runs?

**Comment by timgrossmann** [comment]
Here's my setup on a server:

4-6 sessions per day
450 likes per session
right now, unfollow none => if enough followers, unfollow 1-1.5 times the users i followed last time
comment on 10% (~300 Comments each for standard, food and travel)
follow ~10%

**Comment by deronsizemore** [comment]
Thanks @timgrossmann 

Would you mind sharing your code for that? I guess I'm having trouble picturing how you're unfollowing 1-1.5 times the users you followed last time?

**Comment by timgrossmann** [comment]
@deronsizemore 😄 alright... 

here's my tester.py:

```python
#!/usr/bin/env python3.5

from random import randint
from random import sample
from time import sleep
from instapy import InstaPy

import comments

tag_list = ['sex','nude','naked','beef','pork','seafood',
            'egg','chicken','cheese','sausage','lobster',
            'fisch','schwein','lamm','rind','kuh','meeresfrüchte',
            'schaf','ziege','hummer','yoghurt','joghurt','dairy',
            'meal','food','eat','pancake','cake','dessert',
            'protein','essen','mahl','breakfast','lunch',
            'dinner','turkey','truthahn','plate','bacon',
            'sushi','burger','salmon','shrimp','steak',
            'schnitzel','goat','oxtail','mayo','fur','leather',
            'cream', 'hunt','gun', 'shoot', 'slaughter', 'pussy',
            'breakfast', 'dinner', 'lunch']

like_tag_list = ['veganfoodshare', 'veganfood', 'whatveganseat', 'nature',
                'govegan', 'veganism', 'environment', 'landscape', 'vegansofig',
                 'veganfoodshare', 'veganrecipes', 'veganfit', 'forest', 'veggies',
                'travel', 'landscape', 'iphoneonly', 'woods', 'animals', 'veganfoodie',
                'animal', 'veganism', 'good', 'mountain', 'gopro', 'holiday', 'vacation',
                'enjoy']

friendList = ['friends here']

ignore_list = ['vegan', 'veggie', 'plantbased']

normalComments = comments.normal_comments

foodComments = comments.food_comments

natureComments = comments.nature_comments

followed = 0

with open('./logs/followed.txt', 'r') as followFile:
  followed = int(followFile.read())

def startScript():
  tag1 = randint(200, 300)
  tag2 = randint(50, 350 - tag1)
  tag3 = 450 - tag1 - tag2

  InstaPy()\
    .login()\
    .set_dont_like(tag_list)\
    .set_dont_include(friendList)\
    .set_ignore_if_contains(ignore_list)\
    .set_do_comment(enabled=True, percentage=5)\
    .set_do_follow(enabled=True, percentage=10, times=1)\
    .set_comments(comments=normalComments)\
    .set_use_clarifai(enabled=True)\
    .clarifai_check_img_for(['nsfw'])\
    .clarifai_check_img_for(['food', 'lunch', 'dinner'], comment=True, comments=foodComments)\
    .clarifai_check_img_for(['lake', 'landscape', 'mountain'], comment=True, comments=natureComments)\
    .unfollow_users(amount=randint(followed, followed * 1.5))\
    .like_by_tags(['vegan'], amount=tag1)\
    .like_by_tags(sample(like_tag_list, 1), amount=tag2)\
    .like_by_tags(sample(like_tag_list, 1), amount=tag3)\
    .end()

runFile = open('./logs/run.txt', 'a')

if randint(0,10) < 9:
  try:
    runFile.write('started\n')
    runFile.close()
    sleep(randint(0, 60 * 10))
    startScript()
  except Exception as err:
    with open('../erros.log', 'a') as errLog:
      errLog.write(str(err) + '\n')

else:
  runFile.write('not started\n')
  runFile.close()
```

**Comment by deronsizemore** [comment]
Wow... you have a lot going on there. That's awesome! So you're saving the number of people you followed the previous time to a log file, correct? That's only a number and not actually who was followed? Seems like you'd just be unfollowing the people you just follow the last session? Is there some way to add the people you recently followed to a list so that you can ignore those users on the next unfollow session?

And do you run multiple instances of the script (for multiple instagram accounts) at the same time? Or is that a no-no? What about using the instagram mobile app while the script runs? Any reports of banning from that?

**Comment by timgrossmann** [comment]
@deronsizemore 
Wow, these are a lot of questions... 

> Just for clarification, this is not supposed to be used commercially. Any commercial usage of this will not be supported from me.

Remembering followers is not a part of the tool right now.
Right now it's only n profiles from the top of your following list.

No, only my own account on a DO ubuntu droplet. Mobile usage is no problem if choosing the settings right

**Comment by deronsizemore** [comment]
>Wow, these are a lot of questions...

Sorry. I'll put a moratorium on my question asking unless it's an actual problem. :)

I'm not using this commercially though. I have two accounts. One account for my personal Instagram and one account for a website that own. I'm trying to figure out the best approach to managing both.

*sigh* I know I said no more questions, but...

>Right now it's only n profiles from the top of your following list.

So how do you manage (or do you) to not unfollow people that you just followed? I don't want to follow someone on a Monday and then unfollow that same user a couple days later.

>Mobile usage is no problem if choosing the settings right

Any documentation on the "right" settings for that?

**Comment by timgrossmann** [comment]
@deronsizemore Well, the right settings, for me, are my settings.
I have no problems with them. I can use Instagram on my phone how I did before and don't have to be careful.

I just don't care... Right now, I first follow people until I got around the same number of followers and following and then I set it up to unfollow 1.5x the amount I'm following until I'm back to around 1.5k following. Works like charm.

**Comment by deronsizemore** [comment]
Thanks. 

Maybe it's an irrational worry, but I guess if I figured it'd be easy to spot that a bot was doing some of the work given that it wouldn't be difficult (I don't think) for Instagram to tell that there's liking, following, unfollowing, etc. from one IP while more, different activity from another IP (where I'm using my phone to post, browse, like, comment, etc).

I appreciate all your help.
