### ISSUE TITLE
Got  0  likers shuffled randomly

### ISSUE THREAD

**Issue by collaxd** [InstaPy/InstaPy#2561]
## Expected Behavior
Getting likers from user:  chapolinsincero

shuffling links
Got  12 , returning  1  links:  ['https://www.instagram.com/p/Blx82yDnlcn/?taken-by=chapolinsincero']
opening likes
Scrolling finished
Like window closed

Got  0  likers shuffled randomly, who you can follow:
 []

## InstaPy configuration
try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=False,
				 potency_ratio=-1.21,
				  delimit_by_numbers=False,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['TOP!', 'OTIMO!!', 'SHOW!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.follow_likers (['chapolinsincero'], photos_grab_amount = 1, follow_likers_per_photo = 3, randomize=True, sleep_delay=600, interact=False)

**Comment by meinert** [comment]
See #2526
