### ISSUE TITLE
"Failed to load desired amount of users" both when unfollowing and following!

### ISSUE THREAD

**Issue by davidkessler-ch** [InstaPy/InstaPy#2565]
So I have changed the unfollowing methods, following methods and amounts to follow and unfollow.. nothing changed

Everything should be up to date and I have a good internet connection..
Same thing happens when my crontabs run the script or i run it manually

Please help!

## Expected Behavior

Following & unfollowing normally

## Current Behavior

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-07-29 11:00:58] [my_account]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

.......................................................................
INFO [2018-07-29 11:01:34] [my_account]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-07-29 11:01:41] [my_account]  User 'user1' [1/3]
INFO [2018-07-29 11:02:40] [my_account]  Failed to load desired amount of users

INFO [2018-07-29 11:02:40] [my_account]  Grabbed 0 usernames from user1's `Followers` to do following.
INFO [2018-07-29 11:02:40] [my_account]  User 'user2' [2/3]
INFO [2018-07-29 11:03:39] [my_account]  Failed to load desired amount of users

INFO [2018-07-29 11:03:39] [my_account]  Grabbed 0 usernames from user2's `Followers` to do following.
INFO [2018-07-29 11:03:39] [my_account]  User 'user3' [3/3]
INFO [2018-07-29 11:04:39] [my_account]  Failed to load desired amount of users

INFO [2018-07-29 11:12:39] [my_account]  Grabbed 0 usernames from user3's `Followers` to do following.
INFO [2018-07-29 11:12:39] [my_account]  --> Followed total of 0 people

INFO [2018-07-29 11:12:39] [my_account]  Liked: 0
INFO [2018-07-29 11:12:39] [my_account]  Already Liked: 0
INFO [2018-07-29 11:12:39] [my_account]  Commented: 0
INFO [2018-07-29 11:12:39] [my_account]  Followed: 0
INFO [2018-07-29 11:12:39] [my_account]  Inappropriate: 0
INFO [2018-07-29 11:12:39] [my_account]  Not valid users: 0

____________________________________________________________________________
INFO [2018-07-29 11:12:39] [my_account]  Starting to unfollow users..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-07-29 11:12:45] [my_account]  Unfollowing the users you are following
INFO [2018-07-29 11:13:41] [my_account]  Failed to load desired amount of users
INFO [2018-07-29 11:14:02] [my_account]  Total 48 users available to unfollow  ~not found in 'followedPool.csv': 48  |  didn't pass `unfollow_after`: 0
INFO [2018-07-29 11:14:02] [my_account]  Could not grab requested amount of usernames to unfollow:  48/500  ~using available amount

## Possible Solution (optional)

No idea but it has worked a few weeks ago..

## InstaPy configuration

from instapy import InstaPy

session = InstaPy(username='my_account', password='my_password', headless_browser=True, multi_logs=True)

session.login()

session.set_do_comment(enabled=True, percentage=75)
session.set_comments(['my comments'])

session.set_relationship_bounds(enabled=True,
                                 potency_ratio=-0.8,
                                  delimit_by_numbers=False,
                                   max_followers=990,
                                    max_following=5555,
                                    min_followers=9,
                                     min_following=65)

session.set_user_interact(amount=2, randomize=True, percentage=50, media='Photo')

session.follow_user_followers(['some accounts'], amount=80, randomize=False, interact=True)

session.unfollow_users(amount=500, allFollowing=True, style="LIFO")

session.end()

**Comment by harrycha** [comment]
Do you by any chance have multiple quickstart.py files? I had to use the original one from github because it gave me similar errors. Check quickstart.py and insta.py files
