### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by asemaniko** [InstaPy/InstaPy#2567]
File "quickstart.py", line 39
    session.follow_by_tags(['followforfollowback', 'f4follow'], amount=50)
                                                                         ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by marceljm** [comment]
[https://stackoverflow.com/questions/5685406/inconsistent-use-of-tabs-and-spaces-in-indentation](url)

**Comment by sreejeet** [comment]
Python does not allow you to use tabs and spaces in the same file for indentation. Most likely your line 39 does not follow the same type of indentation as the rest of the file above line 39. replaces the tabs using spaces, it might solve the problem.

**Comment by asemaniko** [comment]
IndentationError: unexpected indent

**Comment by asemaniko** [comment]
new problem
