### ISSUE TITLE
Error occured while getting DB for XXX 

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#2569]
## InstaPy configuration
after pull request #2563 it stopped working @uluQulu @timgrossmann - it gets stuck on multi_logs 
![image](https://user-images.githubusercontent.com/3760127/43396584-fee7083c-93cf-11e8-9686-a5aa66b8cc57.png)

**Comment by uluQulu** [comment]
Hi @halalfood 🙋🏼‍♂️
_I can guess that you have **just** cloned that fresh new repo_ 😋
Make a new folder (_simply empty folder_) named `db` in the project root folder (_near `assets`, `docs`, etc._) to solve that issue **temporarily** (_and permanently_).

I will write a few lines and **share** with you in a PR and explain **why** it happened,  soon.

Cheers 😁

**Comment by CalebBuxton** [comment]
@uluQulu Adding the db folder now gets me to a new error

`TypeError: 'NoneType' object is not iterable`

![image](https://user-images.githubusercontent.com/16494209/43410794-c26bc2a8-93ed-11e8-9ed0-1f74d5d917ee.png)

**Comment by uluQulu** [comment]
Hey @CalebBuxton 
#### I think you have not provided a `username` for the InstaPy instance.
```python
session=InstaPy(username=insta_username, password=insta_password)
```
It shows `None` in there. And I wonder why 😀

>If you have provide a username properly while instantiating and it is another issue, then let me know to think about it

**Comment by redsector72** [comment]
Hi @uluQulu, check if #2576 is also related to this update

**Comment by uluQulu** [comment]
@halalfood @CalebBuxton @redsector72 
The promised PR is live at #2578.

**Comment by ghost** [comment]
I have verified. #2578 fixes my issue. Thank you @uluQulu for your very hard work. @timgrossmann feel free to merge in. works nicely!
