### ISSUE TITLE
I am not too familiar with code and I am working on Windows - It was not successful

### ISSUE THREAD

**Issue by vnd030289** [InstaPy/InstaPy#257]
I am not too familiar with code and I am working on Windows. I have tried out this tool to set up the settings:  [InstaPy Windows GUI](https://github.com/Nemixalone/GUI-tool-for-InstaPy-script)
I have completed the steps with the success message as image: [see image](http://prntscr.com/f8l4l5)
But when I start the app, it opens cmd and closes about 1 sec, and when I check my Instagram profile it is not liking or following anyone.
And this is my error message:

C:\InstaPy-master>py quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\InstaPy-master\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "C:\InstaPy-master\instapy\instapy.py", line 10, in <module>
    from .clarifai_util import check_image
  File "C:\InstaPy-master\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.client import ClarifaiApi
ModuleNotFoundError: No module named 'clarifai'

Please guide me fix it.
Thank you.

**Comment by converge** [comment]
I dont know much about windows, someone can have a better answer on how to do it, but you need install clarifai python module.
**ModuleNotFoundError: No module named 'clarifai'**

**Comment by vnd030289** [comment]
I installed clarifai python module and Visual C++ build tool 14.0 => "Boom" It worked :)
However, after the program automatically logs into Instagram it has encountered an error message: "Sorry, this page isn't available. The link you followed may be broken, or the page may have been removed. Go back to Instagram." [See Screenshots](http://prntscr.com/f8pw2t)
Command line in CMD:

> C:\InstaPy>set PYTHONIOENCODING=UTF-8
> 
> C:\InstaPy>py quickstart.py
> [3520:7688:0517/101159.248:ERROR:policy_loader_win.cc(519)] GetAppliedGPOList sc
> ope 1: The operation completed successfully. (0x0)
> Logged in successfully!
> Traceback (most recent call last):
>   File "quickstart.py", line 4, in <module>
>     session.login()
>   File "C:\InstaPy\instapy\instapy.py", line 88, in login
>     log_follower_num(self.browser, self.username)
>   File "C:\InstaPy\instapy\print_log_writer.py", line 10, in log_follower_num
>     followed_by = browser.execute_script("return window._sharedData.entry_data.P
> rofilePage[0].user.followed_by.count")
>   File "C:\Users\VND\AppData\Local\Programs\Python\Python36-32\lib\site-packages
> \selenium\webdriver\remote\webdriver.py", line 487, in execute_script
>     'args': converted_args})['value']
>   File "C:\Users\VND\AppData\Local\Programs\Python\Python36-32\lib\site-packages
> \selenium\webdriver\remote\webdriver.py", line 252, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\VND\AppData\Local\Programs\Python\Python36-32\lib\site-packages
> \selenium\webdriver\remote\errorhandler.py", line 194, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot re
> ad property '0' of undefined

What experience do you have to overcome this?
Thank you @converge @timgrossmann

**Comment by komad1na** [comment]
You should enter you username of Instagram not Email. Unless your username is email.

**Comment by vnd030289** [comment]
It's done :+1: 
Thank you @Nemixalone
