### ISSUE TITLE
`followers_link` error list index out of range

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2571]
This happens when trying to get followers. How to fix?

INFO [2018-07-30 14:46:09] [xx]  User 'xxx' [1/1]
ERROR [2018-07-30 14:46:37] [xx]  `followers_link` error list index out of range

INFO [2018-07-30 14:46:37] [xx]  Grabbed 0 usernames from xxx's `Followers` to do following.

**Comment by Jenuan** [comment]
Exactly same error here.

**Comment by sunny744** [comment]
@fgisslen @Jenuan Hi guys, I am also facing the same error but only to the usernames which are having dot (.)
Have you checked that? Does anyone have a solution for this?

**Comment by JulianPedro** [comment]
Exactly same error here too. Solution?

**Comment by sergiosre** [comment]
same error , some help?

**Comment by doronshai** [comment]
Hi All,

Please give some advices how to solve it out.
it doesn't happen for all accounts.... but when it does it is not possible to use this amazing tool! which is a disaster :(

Doron

**Comment by Joyen12** [comment]
Getting this error too :(

I have never been able to use this tool. Everytime getting different errors depend of what I want to do but always getting errors
