### ISSUE TITLE
Hello, I have the following error, 'conn'

### ISSUE THREAD

**Issue by thonyhenrique** [InstaPy/InstaPy#2575]
Hello, I have the following error, 'conn', I would like a help to solve, I understand very little about python.

Actually what I'm learning I'm seeing here. with insta py.

![image](https://user-images.githubusercontent.com/37970224/43408554-126ad5f0-93f8-11e8-9371-4e3a2b5d2b61.png)

**Comment by CalebBuxton** [comment]
Currently discussing this on #2569
