### ISSUE TITLE
dictionary update sequence element #0 has length 7; 2 is required

### ISSUE THREAD

**Issue by redsector72** [InstaPy/InstaPy#2576]
I read this in the log, just at the end, I suppose is "closing session" time.

Pow! Error occured while dumping record activity data to a local JSON:
	dictionary update sequence element #0 has length 7; 2 is required

My .json file are 2 byte long and incude only "{}"
I see from the log that this error come from a DB routine "dump_record_activity" but I was not able to understand where is raise an exception

**Comment by fgisslen** [comment]
same here

**Comment by uluQulu** [comment]
Hey guys
@redsector72, @fgisslen 
Please, have a read #2578 to get solutions 🎉

**Comment by fgisslen** [comment]
Thank you @uluQulu .
