### ISSUE TITLE
POW! Error..dumping record activity data

### ISSUE THREAD

**Issue by anselayala** [InstaPy/InstaPy#2579]
ERROR [2018-07-30 15:34:15] [iamlovelll]  Pow! Error occured while dumping record activity data to a local JSON:
	dictionary update sequence element #0 has length 7; 2 is required

**Comment by ShiftingKill** [comment]
Same, at the end of my general.log.

**Comment by bianpratama** [comment]
@anselayala @ShiftingKill,

Make sure you have the latest version, check #2578
