### ISSUE TITLE
InstaPy on Digital Ocean

### ISSUE THREAD

**Issue by AlexLeKid** [InstaPy/InstaPy#258]
Hey guys, 

I'm trying to set up InstaPy on Digital Ocean following this tutorial: https://medium.com/@mcnamee/using-open-source-software-to-build-your-instagram-followers-205f908cf657

But since I have no knowledge in coding, I have problems. I am stuck at the second part where I need to install setup.py. When I try "python setup.py install" I have this error 
`root@pss2:/var/www/instapy# python setup.py install 
python: can't open file 'setup.py': [Errno 2] No such file or directory`

The problem is, the file is actually in the right place 
`root@pss2:/var/www/instapy# ls */ 
assets  Dockerfile  docs  examples  instapy  LICENSE  logs  quickstart.py  README.md  requirements.txt  scripts  setup.py`

So can somebody please help with that ? Thanks a lot !

**Comment by tibor** [comment]
Well, it’s a bit difficult to read without linebreaks.
You can add a code block with three backticks before and three backticks after the code block.

I assume, your problem has something to do with relative/absolute paths. Can you try `python /var/www/instapy/setup.py install`?

**Comment by AlexLeKid** [comment]
Hey, 

Sorry about that. That command doesnt work either, it's the same thing: 
```
root@pss2:/# python /var/www/instapy/setup.py install 
python: can't open file '/var/www/instapy/setup.py': [Errno 2] No such file or directory
```

**Comment by timgrossmann** [comment]
@AlexLeKid try `pip install .` instead of `python setup.py install`

**Comment by AlexLeKid** [comment]
Hey Tim this is what I got: 
```
root@pss2:/var/www/instapy# pip install setup.py
Collecting setup.py
  Could not find a version that satisfies the requirement setup.py (from versions: )
No matching distribution found for setup.py
root@pss2:/var/www/instapy# 
```

**Comment by timgrossmann** [comment]
@AlexLeKid Please read my comment...

Do `pip install .` not `pip install setup.py`

**Comment by AlexLeKid** [comment]
Sorry ! 
```
root@pss2:/var/www/instapy# pip install .
Directory '.' is not installable. File 'setup.py' not found.

**Comment by timgrossmann** [comment]
No problem ;)

alright, so here is what you should do now.

Delete the droplet and start over following [this tutorial](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu.md) and you'll be good to go.

Feel free to reopen this issue if you still have problems.
