### ISSUE TITLE
Like from other ppl Likers

### ISSUE THREAD

**Issue by collaxd** [InstaPy/InstaPy#2580]
## Expected Behavior
Why i Set to see 1500 followers and the bot only grab 154, and every new round is the same ppl and no follow any1

I want to see 21k followers, follow and unfollow everyone and no repeat, have solution?
## Current Behavior
INFO [2018-07-30 23:29:50] [xxx]  Grabbed 154 usernames from milkpoint's `Followers` to do following.
WARNING [2018-07-30 23:32:41] [xxx]  ---> xxx is already followed

## InstaPy configuration
  # actions
    session.follow_user_followers(['xxx'], amount=1500, randomize=True)

**Comment by sionking** [comment]
scrappers
