### ISSUE TITLE
Feature Request: Follow and Mute

### ISSUE THREAD

**Issue by the-unknown** [InstaPy/InstaPy#2581]
As Instagram introduced the new mute function, it would be awesome to combine this with the follow function.

If you don't know what mute is: If you follow someone but don't like his content but don't want to unfollow as you don't want to hurt that person's feelings, you can set him to "mute" and will not see his content in your feed.

Now it would be awesome if I could set everyone the bot follows to "mute" instantly - as by this way I will only see the content of the people I followed on purpose.

**Comment by sionking** [comment]
good idea, but a bit boti, maybe we shall have a percentage for that.

**Comment by ghost** [comment]
@sionking how do we can do that ? is not possible to mute from web ...
we need to implement some unofficial api calls like the other bots out there ...

is a very interesting feature btw ... 

@timgrossmann what do you think about ?

cheers

**Comment by bylezz** [comment]
Hello, Is it possible to do follow and mute instantly?. Thx so much :)

**Comment by GaWr26** [comment]
+1
I would absolutely second this. It would keep the feed clean and one could still be able to use instagram to browse the users followed outside InstaPy.
https://socialcaptain.com/ also offers this option and it works well there.

**Comment by the-unknown** [comment]
@flashguy22 that was the initial intention why I made this feature request. But the problem is: InstaPy would need to change at it's core to make this happen. InstaPy currently uses the Instagram website with a Chrome or Firefox browser. The Instagram website does not support the mute function. It's simply not available there. 

In order to make this work, InstaPy would need to get completely away from using a browser and instead simulate the Instagram Android app. This is possible and there are APIs out there to base this on, but as said, it would fundamentally change InstaPy at it's core. Social Captain does this for example. That's why they can offer such a feature.

However, simulating a real Instagram App would unlock a ton of other features, like interacting with the explore-page on its different tabs or distinguish between "Top" posts on Hashtags and "New" posts on hashtags. 

Additionally, the number of likes and comments are much higher when using the app and not the website. 

So the actual feature request needs to be: simulate an Android app instead of using a browser.

**Comment by GaWr26** [comment]
Ok, got it now. Thanks! 

I wasn't aware the function is not available on the website.
Makes total sense now!
