### ISSUE TITLE
Comment only one picture of a user

### ISSUE THREAD

**Issue by the-unknown** [InstaPy/InstaPy#2585]
As I run the bot 24/7 on 30 different but similar hashtags, it happens that I comment the same comment on 3 or more pictures of the same user. I got many users complaining I should stop to spam in their images. Therefore I would like to limit the bot in a way, that it only comments on one picture per user. It can like as many posts as he wants, but should comment only one post. 

How can I achieve this?

**Comment by brocool** [comment]
session.setblacklist

**Comment by the-unknown** [comment]
session.setblacklist would stop all interaction with a user. But as I said, I only want the comments to stop. Not the likes.
