### ISSUE TITLE
Why am I seeing duplicate "unfollowing username" showing up in terminal?

### ISSUE THREAD

**Issue by deronsizemore** [InstaPy/InstaPy#259]
I'm running the script locally from my Mac in terminal. I've got it set to unfollow and like at the moment. It's currently in the unfollow stage and I'm seeing this in terminal:

http://i.imgur.com/qHBMkWt.png

Is there something wrong? Why the duplicate `"now unfollowing _user_"` entries?

**Comment by timgrossmann** [comment]
Did you `pull` the newest version with `git pull` ?

**Comment by deronsizemore** [comment]
Ah, no. Sorry. Should have thought of that. I'll give it a go.

**Comment by deronsizemore** [comment]
working now. Thanks.
