### ISSUE TITLE
set_user_interact liking leads to "element not found, skipping this user" error

### ISSUE THREAD

**Issue by HelpImAnInstaAddict** [InstaPy/InstaPy#2596]
## Expected Behavior
The script goes through liking by tag, interacting with/following each user whose photo it likes by tag. After following a user, the script will output:
Getting _____'s image list...
Interaction begin...
And then will like 3 photos for the user with which I am interacting (current settings are: session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo') )
## Current Behavior
Instead of liking the user's photos, the script outputs a "element not found, skipping this username" error, prints the Liked: 0, Already Liked: 0, Commented: 0, etc stats it usually prints when done with a username, and then moves on to liking the next photo by tag and following that user.
## Possible Solution (optional)
Is it possible that instagram recently updated something and now the 'like' button is no longer where the script expects? That's my best guess, but I'm new to this package and not familiar enough with the code to have tracked down where the error is arising from yet (especially without a traceback). 
## InstaPy configuration
I was originally running this script on windows with a version of InstaPy pulled on July 22nd and chrome. The interact feature worked perfectly then. I have since migrated to a rasppi and am running on firefox there, using an InstaPy version pulled on Aug 1st. I have not edited any of the functions since pulling from git, and followed the instructions to setup on a rasppi exactly, with no additional issues (beyond needing to create a db folder).

**Comment by nicopetremann** [comment]
If you resize the browser, the script is not able to find the buttons on the responsive layout. Let the browser at the size it was when you launched the script.

**Comment by TR0X** [comment]
I've the same issue on a RPi without GUI. I tried `headless_browser=True` and `headless_browser=False` neither of them worked.
