### ISSUE TITLE
Sorry, an error occured: 'NoSuchElementException' object has no attribute 'encode'

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2597]
## Expected Behavior

Unfollowing

## Current Behavior

Sorry, an error occured: 'NoSuchElementException' object has no attribute 'encode'

**Comment by Wraitheye** [comment]
Same Issue : https://github.com/timgrossmann/InstaPy/issues/2552

**Comment by HCWcoder** [comment]
having the same issue ! after update
