### ISSUE TITLE
[feature request] random hashtags

### ISSUE THREAD

**Issue by converge** [InstaPy/InstaPy#260]
would it be a good idea to InstaPy use a configurable number of hashtags every time it's called ?

for example, I set a list of 6 hashtags: #a #b #c #d #e #f

when InstaPy start, it chooses 4 random hashtags in my list, next time InstaPy start, it will random my hashtags again, in this way InstaPy is always using different hashtags.

what do you think ?

**Comment by timgrossmann** [comment]
@converge You can simply do that with:

```python
from random import choice

hash_tags = ['#tag', '#hash', '#doit']

.like_by_tag(choice(hash_tags), ...)
