### ISSUE TITLE
Question about "likes" features

### ISSUE THREAD

**Issue by YannikFirre** [InstaPy/InstaPy#2603]
Hello,

Thank you for this wonderful script :)

I have a question about the features of likes.

If I put "like_by_tags" and "like_by_locations", the script will do a combination of the two or it will like separately ?

Regards,

Yannik

**Comment by JosteinFraNorge** [comment]
If you add both to your script in the order you mention it will **first** like by given tags, **then** like by location. See example below:

```
session.like_by_tags(['cat', 'dog'], amount=5, media='Photo')
session.like_by_locations(['123456789/SomeLocation/'], amount=7), media=None)
```
This will first like 5 images with the hashtag #cat, then 5 images with the hashtag #dog, then 7 posts (both images and videos) from the location 'SomeLocation'. This will result in a total of 17 likes given by your account.

Hope this helps.

**Comment by YannikFirre** [comment]
@herrgutt Thanks for the fast reply :)

We can not likes  photos in "SomeLocation" who have the hashtags "dog" ? 

It's a planned features ?
