### ISSUE TITLE
Getting ERROR:latency_info.cc - Vector size 102 is too big.

### ISSUE THREAD

**Issue by JosteinFraNorge** [InstaPy/InstaPy#2606]
When using the instaPy script i **randomly** get error:
`[87244:84740:0802/222701.105:ERROR:latency_info.cc(163)] Display::DrawAndSwap, LatencyInfo vector size 102 is too big.`

I dont know what causes this, nor do i know if its limiting the script in some way. From my understanding it's related to selenium.

Has anyone encountered this before, why is this occuring randomly?

## Possible Solution (optional)
I don't know.

## InstaPy configuration
Using a modified quickstart.py where I have added more sessions. Nothing crazy.

Thanks in advance.

**Comment by santhoshraje** [comment]
I have been getting this recently too. Most of the time the script continues working as expected despite printing the error message, but I am just curious what causes this error.
