### ISSUE TITLE
Feature Request: Add 'times = x' parameter to follow_user_followers

### ISSUE THREAD

**Issue by 46960** [InstaPy/InstaPy#2608]
It's already in the title. I mostly use _session.follow_user_followers_ and would like to follow those people only once. But the "_times_" parameter does not work when I put it into the code. 

I get the error: 

_TypeError: follow_user_followers() got an unexpected keyword argument 'times'_

Is there any way the "times" type can be integrated into follow user folloewers?

**Comment by uluQulu** [comment]
Hey @46960 
Actually it is already integrated into it and is working properly.  

It is not a parameter of `follow_user_followers`, instead you should set the `times` parameter inside `set_do_follow` configuration.
```python
session.set_do_follow(enabled=True, percentage=100, times=3)    #set `times` parameter here
session.follow_user_followers("""desired parameters here""")
```
_Note that, `enabled` and `percentage` parameters above does not have any usage for `follow_user_followers` feature, but `times` parameter has._ It means you can just set `times` parameter alone for it as, 
```python
session.set_do_follow(times=3)   ## did not give arguments to `enabled` and `percentage` parameters
```

Cheers 😁

**Comment by orimarti** [comment]
It doesn't work for me, have tried with times=1 and times=2 and it repeats the same follows.

tried with something like this (repeating it):
```
    session.unfollow_users(amount=60, InstapyFollowed=(True, "all"), style="RANDOM", unfollow_after=60, sleep_delay=636)
    session.set_do_follow( times=1)
    session.follow_user_followers(['username'], amount=1, randomize=False)
```

**Comment by uluQulu** [comment]
@orimarti 

It is not possible for it not to work.  
You should know that, after the follow restriction mechanism was changed from JSON to DB from my recent PR, that data is being written from scratch.  
So if you want to test it working
+ make sure you have the latest files
+ go ahead and follow a person after that (_by InstaPy_)
+ put `times` parameter and check now

If you did it properly and still got a problem, just ask me to get further help ☄

------------

Cheers 😁

**Comment by orimarti** [comment]
Ok, working!
Thanks a lot @uluQulu  :)
