### ISSUE TITLE
Likes on Recent hashtag post

### ISSUE THREAD

**Issue by icaring31** [InstaPy/InstaPy#261]
Hi everyone, 

I have one question. When the script's running, it going to like media from hashtag. But it start to like from the best medias on hashtag list and not random media or most recent. How could I do if I want it to like random media from hashtag list or to start by the most recent post? 

Thanks in advance, 
Geoff.

**Comment by timgrossmann** [comment]
@icaring31 Right now, you can't...

The first few posts always are the most popular, from then on it'll like the most recent ones.

**Comment by icaring31** [comment]
Do you think that there is an issue for that or nah ?

**Comment by timgrossmann** [comment]
@icaring31 If, by issue, you mean a GitHub issue here, then no.
If you mean if that could be a feature, then I'd ask you, what you think the usage of that would be?

Why would you want random posts instead of just using the most recent ones?

**Comment by icaring31** [comment]
I would it because liking the most popular pictures on hashtag is useless. It doesn't help us to grow. What help us to grow is to like the recents post but ok no problem your script is realy cool

**Comment by timgrossmann** [comment]
@icaring31 Check out

```python
#This is used to check the number of followers a user has and if this number exceeds the number set then no further interaction happens

session.set_upper_follower_count(limit = 250)

#This is used to check the number of followers a user has and if this number does not pass the number set then no further interaction happens

session.set_lower_follower_count(limit = 1)
