### ISSUE TITLE
Feature Request -> like post of followers

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#2610]
## Expected Behavior

i would like the BOT likes one or more picture of my followers

**Comment by timgrossmann** [comment]
@ilmetu You can achieve this by using the `interact_user_followers`-method using your own username. Just use `.set_do_interact` and only do `set_do_like`

**Comment by ghost** [comment]
very interesting hack :) i will try it for sure

Thanks @timgrossmann

**Comment by timgrossmann** [comment]
@ilmetu Haha, yeah maybe this deserves a (bigger) mention in the README 😅
