### ISSUE TITLE
Pause and resume the session

### ISSUE THREAD

**Issue by tompicca** [InstaPy/InstaPy#2615]
Hey there you are doing a great job with InstaPy! I successfully run Instapy on my terminal (first time I use python) but I quickly faced with this dilemma: run the session 24/7 is really dangerous because Instagram pays attention to some kind of prolonged night pause (about 4/5 hours is enough to make the automations more human). Also, all the professional services for insta growth have the option to make the process sleep for some hours and they recommends to avoid 24hours no stop.
At the end, there's a way to pause the process at 12.00am and resume it at 8.00am?

**Comment by HelpImAnInstaAddict** [comment]
Check out the python package "schedule". You can write a function that does all the liking, following etc you want it to do, and then use schedule to call that function at certain times during the day. There's some code showing how to use schedule under issue #1476.

**Comment by tompicca** [comment]
Thanks for your reply! However my request is slightly different.
Let's say that I want to set InstaPy to do the following actions repeatedly forever:
1. Follow 3.000 users
2. Like 30% of their photos
3. Unfollow the 3.000 users
4. Start again from point 1
Now let's say that I start my process at 8.00am and want to make it more human with a physiological pause of 6 hours during the night, let's say at 2.00am.
Again, let's say that at the end of the first day, before the pause, the process followed 500users. 
How can I resume the process at 8.00am to allow the process start to follow user 501?
Maybe adding a second sleep_delay at a certain time?
