### ISSUE TITLE
Extract total amount of comments at the end of a session

### ISSUE THREAD

**Issue by the-unknown** [InstaPy/InstaPy#2617]
I need some help from a python specialist. I've got blocked again (3rd time now) for commenting too much.
As the "daily amount of comment" feature is not there yet, I'd like to write it on my own. I know a bit of python, but I don't know the code of the bot very well. I'd like to extract the total amount of comments the end of a session, and save it into a log file.
Then, whenever the bot wants to comment on something, it should calculate the total amount of comments given. if it is lower a certain number given, the bot should comment.
If not, he should skip the comment.

Anyone willing to help me on that?

**Comment by uluQulu** [comment]
Hey @the-unknown 
Having read your issue and some other new issues, I think to bring back the **Quota Supervisor** into spot once again.  
It has all of the functionalities to serve your needs and much more!
Have a read [its README lines](https://github.com/uluQulu/InstaPy-with-QS#quota-supervisor) to see its capabilities 😀  

-----------------

Cheers 😁

**Comment by the-unknown** [comment]
Wow, this is simply amazing. Bringing it back would be awesome.
Why is this not part of the master-branch???
It would solve so many issues!!

**Comment by the-unknown** [comment]
Any news regarding the Quota Supervisor?

**Comment by uluQulu** [comment]
@the-unknown, I'm working on it 🐍
Needs to change internal design a bit and integrate into current InstaPy.
_Will share it with you as soon as finalizes work_.
>Just watch out new PRs, maybe gets ready 😎 today

**Comment by the-unknown** [comment]
@uluQulu  thank you so much!! makes life so much easier!! 😃
