### ISSUE TITLE
running from linux (windows became expensive)

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2621]
What is the proper setting ?
Should I change the useragent to windows ?
Is it not more "bot" to run from linux ?

**Comment by MattiaMarchiorato** [comment]
i use headless_browser=True option, that is awesome for linux server.

**Comment by sionking** [comment]
I know but it has no proxy support with authentication

**Comment by sionking** [comment]
don't you set any user agent ?

**Comment by MattiaMarchiorato** [comment]
No

Il sab 4 ago 2018, 20:54 sionking <notifications@github.com> ha scritto:

**Comment by Areahints** [comment]
Im having issues on linux with suspicious login, even after using the code for `bypass suspicious login` is it that i have to use it everytime?

**Comment by MattiaMarchiorato** [comment]
I don't use sospecious login.

Il dom 5 ago 2018, 08:58 Areahints <notifications@github.com> ha scritto:

**Comment by Areahints** [comment]
@sionking did you get it running?

**Comment by sionking** [comment]
I am running some fake nogui account from Linux no real accounts
