### ISSUE TITLE
Trying to use minimal bandwidth

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2623]
Hi,
I'm using instapy over a proxy server and want to use as little bandwidth as possible.
I'm using nogui=true and headless_browser=false now.
Shall I try another setup?

//Fredrik

**Comment by sionking** [comment]
firefox have load_image false...

**Comment by fgisslen** [comment]
@sionking Nice! How do i set that up? I use linux ubuntu server and proxy.
Does it work with authentication?

**Comment by fgisslen** [comment]
@sionking does headless_browser download images?

**Comment by fgisslen** [comment]
@uluQulu

**Comment by timgrossmann** [comment]
#1364

**Comment by fgisslen** [comment]
@timgrossmann okey, nice. But how do I implement this in nogui mode?
