### ISSUE TITLE
Following/Followers grabbing: ETA far off, progress bar not moving

### ISSUE THREAD

**Issue by ghoeffner** [InstaPy/InstaPy#2629]
## Expected Behavior
ETA should show 2-3 Minutes

## Current Behavior
ETA shows 150+ minutes.

## InstaPy configuration
![](http://i.yt.gl/get/44ecc/rymoo.png)

Here is a picture further in
![](http://i.yt.gl/get/44ecc/oaste.png)

**Comment by ghoeffner** [comment]
@uluQulu - it seems you introduced this in https://github.com/timgrossmann/InstaPy/commit/ac72f72cfedcc58e989cd3dbf57c285c74f8a819 
Cheers

**Comment by uluQulu** [comment]
Hi @ghoeffner 
Can you provide all of the details about the problem?
Also,
+ What is your system- OS, python version, etc.
+ Plus sign also does not move?
+ Does it always misbehave like that?
+ Have you had these problems from the start or it popped up at some time?

>It is a very easy progress bar, I am sure it will work for you, too! 🙌

-------

Cheers 😁

**Comment by sionking** [comment]
@uluQulu  great progress bar !!!
