### ISSUE TITLE
No module named __main__.clarifai_util';'__main__' is not a package

### ISSUE THREAD

**Issue by brodydrey2296** [InstaPy/InstaPy#263]
C:\Users\rache\AppData\Local\Programs\Python\Python36-32\python.exe C:/Users/rache/Downloads/InstaPy-master/instapy/instapy.py
Traceback (most recent call last):
  File "C:/Users/rache/Downloads/InstaPy-master/instapy/instapy.py", line 10, in <module>
    from .clarifai_util import check_image
ModuleNotFoundError: No module named '__main__.clarifai_util'; '__main__' is not a package

Process finished with exit code 1

**Comment by timgrossmann** [comment]
@brodydrey2296 What command did you run?

**Comment by brodydrey2296** [comment]
i just ran insta.py

**Comment by timgrossmann** [comment]
@brodydrey2296 Please actually read the Readme.md...
You should start the quickstart.py after modifying it to your needs.

there isn't even a file called insta.py...

**Comment by brodydrey2296** [comment]
I tried reinstalling and setting everything up again, and here is the error I am getting, I think it is almost the same as the first, I am new to programming and don't know how to fix, I have set everything up and when I run instapy.py it doesn't work which is where the error comes in.

C:\Users\rache\AppData\Local\Programs\Python\Python36-32\python.exe C:/Users/rache/PycharmProjects/InstaPy/InstaPy-master/instapy/instapy.py
Traceback (most recent call last):
  File "C:/Users/rache/PycharmProjects/InstaPy/InstaPy-master/instapy/instapy.py", line 10, in <module>
    from .clarifai_util import check_image
ModuleNotFoundError: No module named '__main__.clarifai_util'; '__main__' is not a package

Process finished with exit code 1

**Comment by timgrossmann** [comment]
@brodydrey2296 Why are you running instapy.py? 

You **HAVE** to run **quickstart.py**!

`python3.5 quickstart.py` 

Please don't even touch the content of the instapy folder

**Comment by brodydrey2296** [comment]
Ok, I will try it, thanks.

**Comment by brodydrey2296** [comment]
Ok, so I ran quickstsart.py and then it pulls up the Instagram login page
and nothing else, then I ran instapy.py again and am still getting the same
error

**Comment by timgrossmann** [comment]
@brodydrey2296 **Please, please, please read the Readme...**

You have to modify the quickstart.py file and enter your credentials into `InstaPy(username="", password="")`

Once you entered your credentials, the script should log in and start.
You then can **READ THE DOCUMENTATION** and modify the quickstart.py to use your tags and so on...

**DON'T RUN** instapy.py...

**Comment by brodydrey2296** [comment]
Oh..... ok, thanks that clears things up. On my mac I always run instapy
and it works, thats why I was trying to do it on windows

**Comment by brodydrey2296** [comment]
It works now, case closed, thank you so much for your help, and being
patient with me even when I was being an idiot, I really appreciate it.
