### ISSUE TITLE
Not valid users issue

### ISSUE THREAD

**Issue by shaikhmasud147** [InstaPy/InstaPy#2635]
## Expected Behavior
INFO [2018-08-06 14:42:28] [test90288]  Liked: 0
INFO [2018-08-06 14:42:28] [test90288]  Already Liked: 0
INFO [2018-08-06 14:42:28] [test90288]  Commented: 0
INFO [2018-08-06 14:42:28] [test90288]  Followed: 100
INFO [2018-08-06 14:42:28] [test90288]  Inappropriate: 0
INFO [2018-08-06 14:42:28] [test90288]  Not valid users: 0

## Current Behavior
INFO [2018-08-06 14:42:28] [test90288]  Liked: 18
INFO [2018-08-06 14:42:28] [test90288]  Already Liked: 0
INFO [2018-08-06 14:42:28] [test90288]  Commented: 3
INFO [2018-08-06 14:42:28] [test90288]  Followed: 9
INFO [2018-08-06 14:42:28] [test90288]  Inappropriate: 0
INFO [2018-08-06 14:42:28] [test90288]  Not valid users: 82

## Possible Solution (optional)
How to remove not valid users. I need to increase followed

## InstaPy configuration
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.21,
				  delimit_by_numbers=True,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    session.set_do_like(enabled=True, percentage=85)
    #Comments' state
    session.set_do_comment(enabled=True, percentage=20)
    session.set_comments(comments=['Geat Shot!', 'So good', 'Nice'], media='Photo')
    #Followings' state
    session.set_do_follow(enabled=True, percentage=50, times=1)
   session.like_by_locations(locations=['test90288'], amount=100, media=None, 
   skip_top_posts=False)

**Comment by EduardKov** [comment]
maybe they are outside the parameters set_relationship_bunds?

**Comment by shaikhmasud147** [comment]
@EduardKov Can you tell me what was the issue in session.set_relationship_bounds()

I need to follow all users.

**Comment by EduardKov** [comment]
in instapy.py there is such code:
```
854   #validate user
                        validation, details = validate_username(self.browser,
                                                       user_name,
                                                       self.username,
                                                       self.ignore_users,
                                                       self.blacklist,
                                                       self.potency_ratio,
                                                       self.delimit_by_numbers,
                                                       self.max_followers,
                                                       self.max_following,
                                                       self.min_followers,
                                                       self.min_following,
                                                       self.logger)
                        if validation != True:
                            self.logger.info("--> Not a valid user: {}".format(details))
                            not_valid_users += 1
                            continue
```
which just increases this counter

**Comment by shaikhmasud147** [comment]
@EduardKov  Ok, Thanks!
