### ISSUE TITLE
Could anyone help me with best settings?

### ISSUE THREAD

**Issue by crashado007** [InstaPy/InstaPy#2636]
Hi!

I tried using InstaPy for about month and i get 300 followers. I am using likes by hashtag and interact with user followers
Here is my settings:
session.set_relationship_bounds(enabled=True,
				  delimit_by_numbers=True,
				   max_followers=1000,
				    max_following=900,
				     min_followers=20,
				      min_following=10)
session.set_delimit_liking(enabled=True, max=200, min=0)
session.set_do_like(enabled=True, percentage=100)
session.set_delimit_commenting(enabled=True, max=10, min=0)
session.set_do_follow(enabled=True, percentage=38, times=2)
session.set_do_comment(True, percentage=20)
session.set_user_interact(amount=5, randomize=True, percentage=100)

but i dont know actually how to improve it, could anyone help me please?
I am trying to target people who want a photoshooting / couple shoots / wedding photographer

**Comment by tompicca** [comment]
Hi, I'd make these changes:

```
session.login()
    session.set_relationship_bounds(enabled=True,
			    potency_ratio=None,
			    delimit_by_numbers=True,
			    max_followers=6000,
				max_following=3000,
				min_followers=30,
				min_following=30)

    amount_number=500

    session.set_user_interact(amount=1, randomize=True, percentage=20, media='Photo')

    session.set_do_like(enabled=True, percentage=100)

    session.set_do_comment(enabled=False, percentage=0)
	
    session.set_do_follow(enabled=False, percentage=0)
	
    session.follow_user_followers(['travelawesome'], amount=amount_number, randomize=False, interact=True, sleep_delay=300)
```


I'm avoiding comments because words like 'Cool' or 'Great' are indicative of a bot action. 

According to my experience a new profile should not add more than 300 users a day but you can add 600 users without any block if your profile is old enough with a good base of followers and photos.

Run this during the day from morning (it should take 8-9 hours to add 500 users) than shut it down during the night. 

With these settings I'm getting 60/70 followers / day and I never got a block from instagram.

😁

**Comment by lostion** [comment]
@tompicca Could you please explain why your settings result in 

> Simulated follow 'user1' 
> Simulated follow 'user2' 
> Simulated follow 'user3' 
> Simulated follow 'user4' 
> Simulated follow 'user5' 

> 

Shouldn't the action grab only **one user** from the 'travelawesome' to do amount_number follows **instead of 5** 


> 

> session.set_user_interact(**amount=1,**


Thanks!

**Comment by tompicca** [comment]
Simulated follows makes the bot more human. If you want to know more please read the extensive guide. amount 1 for set_user_interact means that the bot will like 1 photo for the 20% of the total followed users.

**Comment by crashado007** [comment]
Thank you a lot and to unfollow people should i do this?
`session.unfollow_users(amount=300, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)`

**Comment by cbyrt** [comment]
Great post

**Comment by balakedev** [comment]
I wrote this up to help keep things random and safe, might be of use to people here: 


```
import random

"TAG POOL"

"TAG DELCARATION"
group_of_items = {'#fitness','#yoga','#yogapants','#women','#tights','#leggings','#gym','#fit','#workout','#fitfam','#health','#bodybuilding','#fitspo','#weightloss',
'#cleaneating','#muscle','#exercise','#healthyfood','#strength''#gains','#fitlife','#healthyeating','#healthylifestyle','#healthyliving','#weightlossjourney','#shredded','#transformation','#gymrat','#transformationtuesday',
'#bodybuilder','#gymtime','#cleaneats,''#gymflow','#fatloss','#cleanfood','#weightlossmotivation','#fitfamily','#bodybuildingmotivation','#workoutmotivation','#bodygoals',
'#workouts','#weightlosstransformation','#fattofit','#gymselfie','#bodytransformation','#strongbody','#strongerthanyesterday','#bodybuilderlifestyle','#exercising','#fatlossjourney',
'#healthydiet','#strongissexy','#gymjunkie','#cleanliving','#fitfreak','#fat2fit','#fatburn','#musclefood','#fitfriends','#fitinspiration','#workoutflow','#strongisthenewsexy','#bodyunderconstruction','#swolelife',
'#cleaneatingjourney','#cleaneatingaddict','#fattofitjourney''#gainscity','#cleaneatingforlife','#musclemass','#gyminspiration','#workoutlife','#cleanbulk','#workouthard','#fitfamlife','#cleaneater','#swoleandflexy',
'#gainsfordays','#shreddedlife','#shrednation','#swolefie','#rippedbody','#fitfaminstagram','#transformationjourney','#rippedfreak','#stronglife','#gainsongains','#shredzville','#gainsgainsgains','#transformationstory',
'#rippedabs','#transformationpic','#shredfat','#exerciseforlife','#gainsallday','#swolefam','#swoleoclock','#gainsovereverything','#swolefamily','#swolecity','#swoleteam6','#gainslife','#fitfamnation'}               # TAG POOL
num_to_select = 20                           # set the number to select here.
list_of_random_items = random.sample(group_of_items, num_to_select)
first_random_item = list_of_random_items[0]
second_random_item = list_of_random_items[1]
third_random_item = list_of_random_items[2]
fourth_random_item = list_of_random_items[3]
fifth_random_item = list_of_random_items[4]
sixth_random_item = list_of_random_items[5]
seventh_random_item = list_of_random_items[6]
eighth_random_item = list_of_random_items[7]
ninth_random_item = list_of_random_items[8]
tenth_random_item = list_of_random_items[9]
eleventh_random_item = list_of_random_items[10]
twelvth_random_item = list_of_random_items[11]
thirteenth_random_item = list_of_random_items[12]
fourteenth_random_item = list_of_random_items[13]
fifteenth_random_item = list_of_random_items[14]
sixteenth_random_item = list_of_random_items[15]
seventeenth_random_item = list_of_random_items[16]
eighteenth_random_item = list_of_random_items[17]
nineteenth_random_item = list_of_random_items[18]
twentieth_random_item = list_of_random_items[19]


for x in range(1):
  myRandomFeed = random.randint(5,18)

session.like_by_feed(amount=myRandomFeed, randomize=True) # WILL INTERACT WITH USER FEED (LIKES ONLY) based on the no. that the var has been assigned 


# LIKE BY TAG
# Creates var, picks random number declared range and returns to var:

for x in range(1):
  myRandomLike = random.randint(35,45)

session.like_by_tags([first_random_item,second_random_item,third_random_item, fourth_random_item,fifth_random_item,sixth_random_item,seventh_random_item,eighth_random_item,ninth_random_item,tenth_random_item], amount=myRandomLike)

# LIKE BY TAG
# Creates var, picks random number declared range and returns to var:

for x in range(1):
  myRandomLike = random.randint(35,45)

session.like_by_tags([eleventh_random_item,twelvth_random_item,thirteenth_random_item,fourteenth_random_item,fifteenth_random_item,sixteenth_random_item,eighteenth_random_item,nineteenth_random_item,twentieth_random_item], amount=myRandomLike) #LIKE BY TAGS WITH NEW VAR no.

```

**Comment by imjustin** [comment]
@tompicca with the settings you shared, i'm curious what this does

> session.set_do_follow(enabled=False, percentage=0)
> session.follow_user_followers(['travelawesome'], amount=amount_number, randomize=False, interact=True, sleep_delay=300)

Do those two together mean that you go to a users following, interact with 20% of them, and do not follow them?

**Comment by tompicca** [comment]
@imjustin 

`session.follow_user_followers` is an option for `set_user_interact`. Since that I already followed with this: `session.follow_user_followers`  there's no need to ask python to follow again. By default `session.set_do_follow(enabled=False, percentage=0)` is false so you can delete or let it as it is. . 

The code explained:

How many users I want to process:
`amount_number=500`

Interact with the 20% of the amount number, only photos and only 1 photo for each user:
`session.set_user_interact(amount=1, randomize=True, percentage=20, media='Photo')`

Which interaction you want to perform?:

Like 1 photo for each user followed:
`session.set_do_like(enabled=True, percentage=100)`

DO not comment any photo:
`session.set_do_comment(enabled=False, percentage=0)`

Do not follow (since that I follow with the next piece of code):
`session.set_do_follow(enabled=False, percentage=0)`

Follow the amount number of users from the user 'travelawesome', interact with them according to options above and sleep 300seconds each ~10 users processed:
`session.follow_user_followers(['travelawesome'], amount=amount_number, randomize=False, interact=True, sleep_delay=300)`

**Comment by imjustin** [comment]
@tompicca ah understood. So every time you run your script, you follow 500 people, like 1 photo of 100 of those people? And that gets you 60-70 growth per day? That's incredible from just follows. 

I don't automate follows right now, I only automate likes with interact_user_followers right now. 

have you run into an issue where any time you trigger "interact" with a user, it slows down your script a lot? I think it's because it goes to the user's profile and loads all the images, and it slows that down a lot. any thoughts on how to speed that up?

**Comment by tompicca** [comment]
@imjustin 
I created a new instagram profile 6 days ago to test this script. The first 3 days I only followed and liked people. The 4th day was my day off so I was on the beach and my Mac was turned off. 5th day and today I just unfollowed 600 users / day. Consider that you gain followers mostly when you run the follow script. During the unfollow process I never get followers and it's not uncommon realize that you lost some followers driven by bot. The engagement also decrease during the unfollow.
I notice that my rate is more than 10% of follow back. It means that every 100 followed, more than 10 users follow back your profile. If you follow 500 users / days for 3 days, you need 3 days more to unfollow them. If your rate is 10% you should get 150 followers every 6 days and 750 each month.

This is the [PROFILE](https://www.instagram.com/awsmplace/) I'm testing.

For now I don't want to push the script over the edge. Consider that follow more that 500 users a day is a bit risky for a new profile. For an old profile is pretty safe push the script until 700. I know that there are people that follow 1000 users/day but the risk of be banned definitively is too high if you care to your profile.
That's it!

**Comment by imjustin** [comment]
@tompicca interesting. I've been seeing an average of 20 followers per day net growth from just automating likes. 

i think you're right with the volume limits; don't want to interact on too many accounts at once.

**Comment by sionking** [comment]
Don't believe to ppl on network saying follow back is 30-40%, it is not.
I works with many previous booted profile and not so good is 250 a month and good once are 500+.
If you get 10% that is also for good targeting and good profile, most get 3% (follows +likes).
I would have not recommend more than 300 follow/unfollow a day.

**Comment by sionking** [comment]
Also if engagement is important, try only likes.

**Comment by Areahints** [comment]
It takes 16 days for me to generate 1000 followers, the key is in shorter runtimes. If you have a script that is going to run for more than 3 hours, it will likely be ineffective, mine runs for 1hour, so I set a cronjob that restarts it's very 2 hours, which gives me 100 follows everyday

**Comment by imjustin** [comment]
@Areahints what kind of activities are you running / are you running it 24 hours a day? if you run it for 18 hrs a day that means your script runs 6 times?

**Comment by Areahints** [comment]
```
0 3,5,7,9,11,13,15,17,19,21 * * * cd ~/InstaPy && /usr/bin/python3 ./my script.py
```
thats my cron schedule, as you can see its starting 3am everyday, but by 4am its done, theres a cooldown period of 1hour and by 5am its begun again, its repeating this cycle daily.
i typically do *user followers* about 150 from 4-5 different people , then i like about 125 posts from 5 hashtags, i also do comments on photos media but i make sure the comment mentions the owner of the account, so they reply and its helps my engagement.
one thing i noticed is that a lot of users here want to do follow, like, mention and unfollow. i unfollow manually, i dont automate it, it makes me slow but it gives accounts more chances to eventually follow up

**Comment by Ninnix** [comment]
Ciao @tompicca, could you kindly talk about how you handle unfollows? there should be something like this in your file:

`session.unfollow_users(amount=100, InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=48*60*60, sleep_delay=501)
`

Thanks

**Comment by jirachi155** [comment]
I agree, @tompicca could you please explain what's your setup for unfollowing? Thank you :)

**Comment by tompicca** [comment]
Sorry for the late reply guys.
About unfollow session, I just use this script:

```session.unfollow_users(amount=600, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=1*60*60, sleep_delay=90)```

I don't use any other method because my main purpose is unfollow all the users I previously followed, regardless if they follow me or not. Usually is a good idea to follow from 2.000 to max 3.000 users (it depends from how old is your account and how many followers you have: for very new accounts never go over 2.000), then switch to unfollow when your account is following this many accounts. Follow more than 3.000 is always a bad idea. Let's say that you have an old enough account, you can set up a cycle that follow 3.000 then unfollow 3.000. The most import part is that you can't follow or unfollow 3.000 in just one time, but you should split this number keeping in mind the day limit I explained in my previous posts: 600/700 users per day is a good number for old enough profile, otherwise the limit is 300/400 per day. 
Also, my sleep_delay is 90 sec, I use this number after several attempts but each account is different. You should start with 300/400 then you can decrease if no IG block occurs.
Hope this can help!

Have a great Sunday

**Comment by photogsy** [comment]
> ```
> 0 3,5,7,9,11,13,15,17,19,21 * * * cd ~/InstaPy && /usr/bin/python3 ./my script.py
> ```
> thats my cron schedule, as you can see its starting 3am everyday, but by 4am its done, theres a cooldown period of 1hour and by 5am its begun again, its repeating this cycle daily.

Would really love to see your follow script - would you share it please?

**Comment by muba00** [comment]
Why don't we just follow people manually?) even if you are going to follow 100 people within a day it takes 5-10 minutes, do it when you are in toilet.

**Comment by m-henderson** [comment]
@Areahints could you share your follow script please?

**Comment by yogaheart** [comment]
@tompicca Do you use quota supervisor for your script?

**Comment by brandonmalonson** [comment]
Below is my running config that I have in IDLE. I just got action blocked and I'm trying to figure out why. Not very good at writing code in general and I was wondering if I could get some assistance? All I really would like to do is like & follow (not 100% of the time). I tried to apply simulation as well thinking that would help but I'm not sure where I need to put it. You'll notice that I put it in two different spots. Do I need to add more or take away?


from instapy import InstaPy
from instapy import smart_run

insta_username = ''
insta_password = ''

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

# let's go! :>
with smart_run(session):
    # general settings
    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=6000,
                                    max_following=3000,
                                    min_followers=30,
                                    min_following=30)
    amount_number=500

    session.set_user_interact(amount=1, randomize=True, percentage=20,
                              media='Photo')
    session.set_simulation(enabled=True, percentage=75)
    session.set_do_like(enabled=True, percentage=100)
    session.set_do_comment(enabled=False, percentage=0)
    session.set_do_follow(enabled=False, percentage=0)
    
    # activity		
    session.set_simulation(enabled=True, percentage=75)
    session.follow_user_followers(['jeffreestar'], amount=amount_number, randomize=False, interact=True, sleep_delay=300)
    session.like_by_tags(["eyeshadow" ], amount=0)

    # unfollow activity
    session.unfollow_users(amount=500, instapy_followed_enabled=True, instapy_followed_param="all", style="FIFO", unfollow_after=90*60*60, sleep_delay=501)

    """ Joining Engagement Pods...
    """
    session.set_do_comment(enabled=True, percentage=35)
    session.set_comments(comments)
    session.join_pods(topic='fashion', engagement_mode='normal')

**Comment by FrozGR** [comment]
> ```
> 0 3,5,7,9,11,13,15,17,19,21 * * * cd ~/InstaPy && /usr/bin/python3 ./my script.py
> ```
> 
> thats my cron schedule, as you can see its starting 3am everyday, but by 4am its done, theres a cooldown period of 1hour and by 5am its begun again, its repeating this cycle daily.
> i typically do _user followers_ about 150 from 4-5 different people , then i like about 125 posts from 5 hashtags, i also do comments on photos media but i make sure the comment mentions the owner of the account, so they reply and its helps my engagement.
> one thing i noticed is that a lot of users here want to do follow, like, mention and unfollow. i unfollow manually, i dont automate it, it makes me slow but it gives accounts more chances to eventually follow up

Could you please post your script? 

Thanks in advance
