### ISSUE TITLE
Unfollow is getting stuck when the most recent followed is on the dont_unfollow list

### ISSUE THREAD

**Issue by datavistics** [InstaPy/InstaPy#264]
Unfollow starts at the top of followed users and goes down. If the top user is on the dont_include list then instapy wont unfollow anyone.

**Comment by deronsizemore** [comment]
Are you placing each new followed user into a list so you can use dont_include for the next unfollow session? If so, how are you going about that? If I follow someone right now, and then start an unfollow session, then I simply unfollow the people I just followed so I need a way to get by that.

**Comment by datavistics** [comment]
Ill try to write it out in a scenario:

# Scenario 1

Friends list (in order):
- user_1
- user_2
- user_3

```
friend_list = ['user_3', 'user_4']

InstaPy(username='user', password='pass')\
  .login()\
  .set_dont_include(friend_list)\ #rest of setup follows as expected
```

Friends list after will show:
- user_3


# Scenario 2

Friends list (in order):
- user_3
- user_1
- user_2

```
friend_list = ['user_3', 'user_4']

InstaPy(username='user', password='pass')\
  .login()\
  .set_dont_include(friend_list)\ #rest of setup follows as expected
```

Friends list after will show:
- user_3
- user_1
- user_2
