### ISSUE TITLE
UnBoundLocalError

### ISSUE THREAD

**Issue by Samugrof** [InstaPy/InstaPy#2641]
Hi, i cant launch example.py, because it says:

> Traceback (most recent call last):
>   File "example.py", line 46, in <module>
>     unfollow_whitelist=['example_user_1', 'example_user_2'])
>   File "/root/instabot.py/src/instabot.py", line 234, in __init__
>     self.login()
>   File "/root/instabot.py/src/instabot.py", line 283, in login
>     csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
> UnboundLocalError: local variable 'r' referenced before assignment
> 
> 

Please help me to fix, thank you.

**Comment by Areahints** [comment]
might be related to #2628
