### ISSUE TITLE
Sleep_delay to set like speed

### ISSUE THREAD

**Issue by lightseb** [InstaPy/InstaPy#2642]
## Expected Behavior
Is it possible to add speed-delay to all the action we want ?
I would like to set a delay to the likes cause I have been blocked by IG (temp) for liking too fast.
if possible, is sleep_delay=30 enought ?

Thanks for help

**Comment by zsvendo** [comment]
any idea @timgrossmann @sionking @uluQulu ?

Thanks

**Comment by jeremycjang** [comment]
You could try analyzing the sleep code in the ```unfollow_util.py``` yourself and digging into how the like function works to see if the code is modifiable to do what you want. 

Alternately (though way less code efficient), you could just break up your likes into smaller amounts and use python's native ```time.sleep`` function to make the delay.

Ex. instead of 
```
session.like_by_whatever(['value'], amount=100, skip_top_posts=False)
```
do
```
session.like_by_whatever(['value'], amount=50, skip_top_posts=False)
time.sleep(3600) #Note: Python sleep is in seconds. 3600= 1 hour
session.like_by_whatever(['value'], amount=50, skip_top_posts=False)
```

**Comment by lightseb** [comment]
Oh thank you jeremycjang, I will try this, I think it's a really good option !
Regards
