### ISSUE TITLE
Help, like does not apply

### ISSUE THREAD

**Issue by AymericStark** [InstaPy/InstaPy#2648]
I have a problem, the logs indicate that my account like photos, but when I go to see "publications you like" in the application, I do not see them

**Comment by sionking** [comment]
Use residential proxy

**Comment by ghost** [comment]
i can suggest [https://luminati.io/](https://luminati.io/?affiliate=ref_5b43dfdfeebad2ae1d7ff104)

**Comment by AymericStark** [comment]
Proxy was the solution, thx @sionking

**Comment by AymericStark** [comment]
Sorry, it worked for a single photo, then despite the proxy, I still have the same problem

**Comment by ghost** [comment]
Hi @AymericStark for bypass the instagram security yes you need to use a proxy but not a normal proxy like dedicated proxy or datacenter proxy , you need to use strong residential proxy. that's why i suggest [luminati](https://luminati.io/?affiliate=ref_5b43dfdfeebad2ae1d7ff104) they provide an undetectable proxy. it works really well for me and my clients. give it a try!

**Comment by sionking** [comment]
But aren't it expensive ? like you can't work with images....

**Comment by sionking** [comment]
is it new account ?

**Comment by AymericStark** [comment]
It's not a new account, last week everything worked very well, i'm up to date, logs print "liked!" but no effect on my account @sionking

**Comment by ghost** [comment]
it happens to me also, using [luminati](https://luminati.io/?affiliate=ref_5b43dfdfeebad2ae1d7ff104) worked well for me .. now my accounts doesn't need verification and likes / follow comments and everything works well.

i'm able to work without images , headless false, nogui true

@sionking  yes they are pretty expensive but if you get in touch with them they will get a good discount ... they are very good company. i'm totally satisfied.

**Comment by ghost** [comment]
@AymericStark the only solution for now for you if you don't want to use residential proxies is to wait that insta* will unflag your ip / account

**Comment by sionking** [comment]
Do  they have middle east proxies ?what is the price we can get ?
Working without dl images is ~~~

**Comment by ghost** [comment]
@sionking yes they have proxies all over the world , you can choose the country and even the city ... and you can choose also the mobile carrier and other cool things ... like user agent , latency ecc ...

the price you can get is variable about how much bandwith you want to use and latency ecc ... they have also datacenter proxy and dedicated proxy and also ... Mobile proxy ... that is awesome ...

[luminati](https://luminati.io/?affiliate=ref_5b43dfdfeebad2ae1d7ff104)

give it a try, they can provide for you a trial period.

**Comment by sionking** [comment]
I do have my own IPs, but I think I am having too much work to keep those proxy works (my own).
And it is also more expensive !

**Comment by HCWcoder** [comment]
@sionking  im from middleEast too !

@ilmetu  can we use Data Center Dedicated ips ? and how much brandwith do we need like normaly over a month with no gui ?

**Comment by Mehran** [comment]
@ilmetu  to use luminati need username and password ? is it auth work on InstaPy ?

**Comment by ghost** [comment]
Hi @Mehran you can choose to whitelist your server ip ip with [luminati](https://luminati.io/?affiliate=ref_5b43dfdfeebad2ae1d7ff104) but you can also modify the code of the instapy for run a proxy with authentication.

you can find more info [here](https://botproxy.net/docs/how-to/setting-chromedriver-proxy-auth-with-selenium-using-python/)

and on luminati you can find whitelist option [here](https://luminati.io/faq#start-whitelist_ips)

hope it helps!

**Comment by Mehran** [comment]
@ilmetu yes i added whitelist where can i found Port of Proxy ?

**Comment by ghost** [comment]
@Mehran you can look at the Api Example page of [luminati](https://luminati.io/?affiliate=ref_5b43dfdfeebad2ae1d7ff104)

in my case is : 22225 i think it's default

**Comment by Mehran** [comment]
@ilmetu ```
Traceback (most recent call last):
  File "quickstart.py", line 20, in <module>
    session = InstaPy(username=insta_username, password=insta_password, proxy_address='xxxxx', proxy_port=22225 )
  File "/root/InstaPy/instapy/instapy.py", line 193, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 279, in set_selenium_local_session
    proxy = ":".join([self.proxy_address, self.proxy_port])
TypeError: sequence item 1: expected str instance, int found
```

**Comment by ghost** [comment]
proxy_port='22225'

use a string instead of an int for the proxy port ...

**Comment by Mehran** [comment]
@ilmetu  hhm another issue

```
Traceback (most recent call last):
  File "quickstart.py", line 20, in <module>
    session = InstaPy(username=insta_username, password=insta_password, proxy_address='xxxx', proxy_port='22225', nogui=True)
  File "/root/InstaPy/instapy/instapy.py", line 193, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 277, in set_selenium_local_session
    if self.proxy_address and self.proxy_port > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by ghost** [comment]
go to the line 227 of instapy.py and change:

if self.proxy_address and self.proxy_port > 0:

to 

if self.proxy_address and len(self.proxy_port) > 0:

**Comment by Mehran** [comment]
@ilmetu This happen just when use proxy 

`Too few images, skipping this tag`

**Comment by ghost** [comment]
are you sure to be logged in  correctly ?

**Comment by Mehran** [comment]
@ilmetu every time i run it , it said` Cookie file not found, creating cookie...` and `Logged in successfully!`

is is possible for `headless_browser=True` ?  but when i `headless_browser=False` it got error 

```
Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    session = InstaPy(username=insta_username, password=insta_password, proxy_address='xxxx', proxy_port='22225', nogui=True, headless_browser=False, multi_logs=False)
  File "/root/InstaPy/instapy/instapy.py", line 194, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 305, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /root/InstaPy/assets/chromedriver

```

**Comment by ghost** [comment]
you need to use headless_browser=False and nogui=True

so instapy will use Xvfb package (python-display)

**Comment by Mehran** [comment]
@ilmetu` xvfb is already the newest version (2:1.19.6-1ubuntu4)` installed and last chrome driver in folder , `nogui=True`  and `headless_browser=True` work well without `proxy`
