### ISSUE TITLE
Unfollowing who doesn't follow back [issue for big accounts]

### ISSUE THREAD

**Issue by HCWcoder** [InstaPy/InstaPy#2652]
## Expected Behavior
unFollow all unfollowing accounts
## Current Behavior
INFO [2018-08-09 12:17:35] [xxx]  Unfollowing the users followed by InstaPy

INFO [2018-08-09 12:17:35] [xxx]  Retrieving live `Followers` data of xxxat "full" range
  1581/5589 [==========+-------------------------]  28%    |> Elapsed: 1.31 minutes    |> ETA: 3.36 minutes

ERROR [2018-08-09 12:21:25] [xxx]  Sorry, an error occured: 'NoSuchElementException' object has no attribute 'encode'

## Possible Solution (optional)
Its only happening with some big accounts 

account with 2k followers or following are working.
## InstaPy configuration

session.unfollow_users(amount=126, nonFollowers=True, style="RANDOM", unfollow_after=36*60*60, sleep_delay=400)

**Comment by ManfredHam** [comment]
There is a general Problem with unfollow it seems:

INFO [2018-08-09 11:41:04] [account]  Unfollowing the users followed by InstaPy
INFO [2018-08-09 11:41:04] [account]  Retrieving live `Followers` data of account at "full" range
  507/509 [===================================+]  99%    |> Elapsed: 44.02 seconds    |> ETA: 0.44 seconds

INFO [2018-08-09 11:41:50] [account]  Grabbed 507 usernames from `Followers` in 44.02 seconds
INFO [2018-08-09 11:41:50] [account]  Stored `Followers` data at E:\git\instapy\logs\account\/relationship_data/account/follo

INFO [2018-08-09 11:41:50] [account]  Zz :[ time to take a good nap  ~sleeping 1.0 minutes
INFO [2018-08-09 11:42:56] [account]  Yawn :] let's go!

INFO [2018-08-09 11:42:56] [account]  Found 98 loyal followers!  ~will not unfollow them
INFO [2018-08-09 11:42:56] [account]  Total 150 users available to unfollow  ~didn't pass `unfollow_after`: 139

INFO [2018-08-09 11:42:56] [account]  You have requested more amount: 300 than 150 of users available to unfollow  ~using ava
ERROR [2018-08-09 11:43:26] [account]  --> Unfollow error with b'kikis_fadenspiel', maybe no longer exists...
ERROR [2018-08-09 11:43:26] [account]  Unfollow loop error:  Message: unknown error: Cannot read property 'activity_counts' o
  (Session info: headless chrome=68.0.3440.84)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by sionking** [comment]
The issue is that you have no internet/ IG blocked you IP for a second / IG server is down.
That can happen alot during the day ! and you will have a blank window, so instead of getting error we should wait and refresh the page until it visible. @uluQulu  made some changes no ?

**Comment by ManfredHam** [comment]
@sionking Yes uR right, it's traffic slowness, that is the problem. The Requests does take too long and instead of skipping and running it does crash.

**Comment by sionking** [comment]
Who want to fix it ? I will give a try but better do it right

**Comment by HCWcoder** [comment]
Thanks alot for @sionking and @manfredhamlescher

Yes this is happening only while trying to get the big lists

I hope we can find a fix or delat for that.

Thanks alot!!

**Comment by redasef** [comment]
Hi 
I tried to reduce the time sleep in **get_following** and **get_followers** as :
    sleep_t = sc_rolled***2** 
instead of 
sleep_t = sc_rolled***6** 
it seems to be working...

**Comment by fgisslen** [comment]
@redasef that works sometimes for me but last time that didn't work either.

**Comment by fgisslen** [comment]
@uluQulu is this something you could look at?

**Comment by uluQulu** [comment]
Hey guys
I see that people are having different kinds of errors in this thread.
So, in which problem you think I could look at?

@fgisslen,
Post all of the troubleshoot information I will need, hopefully will help you solve it.

-----------

Cheers 😁
---------

**Comment by fgisslen** [comment]
@uluQulu 

I mean this error which occur when you try to unfollow only non followers.

INFO [2018-08-09 12:17:35] [xxx] Unfollowing the users followed by InstaPy

INFO [2018-08-09 12:17:35] [xxx] Retrieving live Followers data of xxxat "full" range
1581/5589 [==========+-------------------------] 28% |> Elapsed: 1.31 minutes |> ETA: 3.36 minutes

ERROR [2018-08-09 12:21:25] [xxx] Sorry, an error occured: 'NoSuchElementException' object has no attribute 'encode'

**Comment by uluQulu** [comment]
Hm @fgisslen
It was fixed 2 days ago at #2683
You should really use up-to-date files before raising an **Issue**.

---------

Cheers 😁
------------

**Comment by HCWcoder** [comment]
I can confirm thats its fixed and its working for big accounts now great job.
Thanks
