### ISSUE TITLE
Message: unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2654]
Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-29-generic x86_64)
Traceback (most recent call last):
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 304, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-29-generic x86_64)

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 304, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-29-generic x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/5b4c26e666f1b500142d47c6.py", line 14, in <module>
    session = InstaPy(username=insta_username, password=insta_password, proxy_chrome_extension=proxy_chrome_extension, headless_browser=False, nogui=True, multi_logs=True, bypass_suspicious_attempt=True)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 193, in __init__
    self.set_selenium_local_session()
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 308, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/fredrik/InstaPy/assets/chromedriver

This happens often.

**Comment by Areahints** [comment]
in `home/fredrik/InstaPy/assets` run `ls -lah` and paste output here

**Comment by fgisslen** [comment]
@Areahints okey, here:

fredrik@minidator-1:~/InstaPy/assets$ ls -lah
total 8.0M
drwxrwxr-x  3 fredrik fredrik 4.0K Aug  2 07:21 .
drwxrwxr-x 14 fredrik fredrik 4.0K Aug 10 21:42 ..
-rwxr-xr-x  1 fredrik fredrik 8.0M Jul 27 12:25 chromedriver
drwxrwxr-x  2 fredrik fredrik 4.0K Aug  4 15:05 chrome_extensions
-rw-rw-r--  1 fredrik fredrik   61 Jul 17 19:39 .gitignore
-rw-rw-r--  1 fredrik fredrik  489 Jul 17 19:39 unicodes.md

**Comment by Areahints** [comment]
seems ok to me, let me start by asking you to change this 
`headless_browser=False` to `headless_browser=True`

if the error still persists you might want to check this link as it gives a few options to check out since the bug is linux specific

https://stackoverflow.com/questions/50642308/org-openqa-selenium-webdriverexception-unknown-error-devtoolsactiveport-file-d

in particular adding the argument `--disable-dev-shm-usage` seems to be the best fix

im assuming from seeing the folder/file `chrome_extensions` that you tweaked this yourself or you run chrome visually to be able to achieve this? how did you achieve this?

**Comment by fgisslen** [comment]
@Areahints I can't use headless_browser=True because I use proxies with authentication so I use nogui=true , headless_browser=false.

Where do i change --disable-dev-shm-usage ?

**Comment by Mehran** [comment]
@Areahints 
same for me i try several servers debian , ubuntu but same  . 
headless_browser=True, nogui = True    Work Well
headless_browser=False , nogui = True  not work and i can't use Proxy .

**Comment by Areahints** [comment]
if anyone could understand this link it holds the answer

https://stackoverflow.com/questions/46002582/chrome-in-headless-mode-provide-credentials-auth-for-proxy

i think we won't get much love from instapy community on this one since its a linux-chrome issue

@fgisslen i think you pass that to your chrome via terminal or append to it's shortcut, im not yet on my pc to try it out. still reading stackoverflow for possible noob solutions

**Comment by Mehran** [comment]
@Areahints headless_browser=True, nogui = True Work Well
headless_browser=False , nogui = True not work. Is Chrome bug?

**Comment by luquitared** [comment]
Just spent a lot of time on this error and finally fixed it. I am running this on ubuntu server and this crash only happened when I ran this in python2.7. When I use python3 I do not encounter this error. Hopefully this helps others!

**Comment by Mehran** [comment]
@luquitared are your config file is `headless_browser=False , nogui = True`     ? or both is `True `?

**Comment by luquitared** [comment]
Both is True. I am also using a proxy. If you have more trouble send your
session = instapy constructor and I can try to help

**Comment by Mehran** [comment]
@luquitared 
```
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = 'xxxx'
insta_password = 'xxxx'

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#   Settings.database_location = '/path/to/instapy.db'
#   Settings.chromedriver_location = '/path/to/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  nogui=True,
                  proxy_address='xxxx', 
                  proxy_port='xxxxx'
                  multi_log s=False)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
                                 potency_ratio=-1.21,
                                  delimit_by_numbers=True,
                                   max_followers=4590,
                                    max_following=5555,
                                     min_followers=45,
                                      min_following=77)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
    session.like_by_tags(['natgeo'], amount=1)

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()
```

**Comment by gherkins** [comment]
i was able to resolve this with using the chromedriver beta from electron:

the lastest armv7l release from this page https://github.com/electron/electron/releases   
https://github.com/electron/electron/releases/download/v3.0.0-beta.5/chromedriver-v3.0.0-beta.5-linux-armv7l.zip

installed chromium-browser via apt-get (v68) and then pip install the dependencies.
worked like charme... hopefully this helps somebody
