### ISSUE TITLE
someone help me  (quickstart.py "Traceback" error )

### ISSUE THREAD

**Issue by waseem-brinsi** [InstaPy/InstaPy#2656]
when I run the quickstart.py script....it give me this error:
----------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brins\Desktop\InstaPy-master\quickstart.py", line 7, in <module>
    from instapy import InstaPy
  File "C:\Users\brins\Desktop\InstaPy-master\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "C:\Users\brins\Desktop\InstaPy-master\instapy\instapy.py", line 19, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
---------------------------------------------------------------------------------------------------------
note: my os is win 10 
          my python version is 3.7 the last version.
          the pip and selenium is installed correctly

**Comment by doubledare704** [comment]
You should install http://docs.python-requests.org/en/master/ this one to start using requests library

**Comment by Areahints** [comment]
if you start quickstart.py with `python quickstart.py` run `pip install requests` if its  `python3 quickstart.py` run `pip3 install requests`

**Comment by waseem-brinsi** [comment]
thanks a lot, @Areahints and @doubledare704, the problem solved,  the script is working now
