### ISSUE TITLE
So, what does 'percentage' really mean?

### ISSUE THREAD

**Issue by imkimchi** [InstaPy/InstaPy#2658]
`session.set_do_follow(enabled=True, percentage=44)`

It's really confusing me about what `percentage` really does, there's literally no documentation about this parameter so I have no idea how I should use it. Can anybody explain what it is? I'd be really appreciated 👍

**Comment by timgrossmann** [comment]
```python
# default enabled=False, ~ every 4th image will be commented on

session.set_do_comment(enabled=True, percentage=25)
```

```python
# default enabled=False, follows ~ 10% of the users from the images

session.set_do_follow(enabled=True, percentage=10)
```

And there is a lot more documentation giving examples and explaining what it does.

I can absolutely understand that it might confuse some people, but there definitely is documentation... A lot of it.
I'm sorry if it confused you.

The simplest solution is that for all the pictures it looks at, it decided whether to follow or not based on this parameter.
`percentage=25` simply means around 25% of the posts that are looked at, the owner will be followed.
There is nothing more behind it.
`percentage=100` means 100% (all) will be followed etc.

If there should be any more unclear things, please feel free to ask 😊

**Comment by imkimchi** [comment]
Thanks a lot for the explaination, what gets me more confused is the difference between percentage and amount. then what's the difference between these? can they both used at the same time?

`session.set_do_follow(enabled=True, percentage=10)`
`session.follow_by_tags(['something'], amount=1)`
