### ISSUE TITLE
Could anyone help me get a healthy account again? 

### ISSUE THREAD

**Issue by Luisetty** [InstaPy/InstaPy#2662]
--Intro--

So, eventually I got the famous shadowban according to Insta, they don't do that but I test it with other accounts and your post, comments and likes are invisible, only you can see them but other won't be able to see it.

Anyways after two months it seems one account is cleared and ready to go. 
Also the new algorithm or things that push insta, it seems I only have like 45 real followers or at least that interact with that account.

--Help---
in one account I have 1520 followers and 4655 following ( this was in like 8-9 months using instapy).

Is there any way to unfollow those 4655 in a few months? in non suspicious way? not sure what new settings I should try. or at least to get close to 1520?

I don't want to follow or comment because I'm afraid that will trigger the suspicious bot for instagram. at least at the moment I just want reduce the amount of following and just keep the people who really interacts with that account.

my database with the followers was corrupted or at least i couldn't read it, so in case I don't have it, is there any way to create the insta.py just to start cleaning? how many unfollows per day is possible, it would be possible to add some rest/sleep?

any advice

thank you

**Comment by ghost** [comment]
hi @Luisetty i suggest you to use residential proxies to avoid any ban here: [luminati](https://luminati.io/?affiliate=ref_5b43dfdfeebad2ae1d7ff104)

**Comment by Areahints** [comment]
250 unfollows a day is a safe margin
