### ISSUE TITLE
Unfollow Problem

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#2663]
Hello getting this error while unfollowing users, any idea please ? 

session.unfollow_users(amount=200, nonFollowers=True, style="RANDOM", sleep_delay=180)

____________________________________________________________________________
INFO [2018-08-11 17:33:28] [xxx]  Starting to unfollow users..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-08-11 17:33:28] [xxx]  Unfollowing the users who do not follow back

INFO [2018-08-11 17:33:28] [xxx]  Retrieving live `Followers` data of xxx at "full" range

ERROR [2018-08-11 17:33:30] [xxx]  Sorry, an error occured: 'exceptions.AttributeError' object has no attribute 'encode'

any idea please ? many thanks 

@uluQulu

**Comment by waseem-brinsi** [comment]
the same problem

**Comment by uluQulu** [comment]
Hey guys
@Edhim, @wassim1995 

I am unsure about the problem you have encountered but the program crashing at that stage is a mistake of mine cos I forgot that `Exception` class has no attribute of _encode_.
#### Gonna make a fresh fix for it.


_After you get the fix I will share soon, test again and at THAT time you will see the message of the real problem you have encountered. Then post it in full details, I hope I will help you solve it_ 🔑🤝🏼
 
-------

Cheers 😁
------------

**Comment by Edhim** [comment]
Thank you so much @uluQulu , working now 😄

**Comment by waseem-brinsi** [comment]
hi @uluQulu
when I use the unfollow users option it works without doing any unfollowing
session.unfollow_users(amount=200, nonFollowers=True, style="RANDOM", sleep_delay=180)

result:
------------------------------------------------------------
INFO [2018-08-20 23:01:59] [xxx]  Session started!
ooooooooooooooooooooooooooooooooooooooooo
..............................................................................
INFO [2018-08-20 23:02:34] [xxx]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
___________________________________________________________________________________
INFO [2018-08-20 23:02:49] [xxx]  Starting to unfollow users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-08-20 23:03:44] [xxx]  Failed to get followers count of 'xxx'  ~empty list
INFO [2018-08-20 23:04:35] [xxx]  Failed to get following count of 'xxx'  ~empty list
WARNING [2018-08-20 23:04:35] [xxx]  Unable to find the count of users followed  ~leaving unfollow feature
INFO [2018-08-20 23:04:35] [xxx]  --> Total people unfollowed : 0
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-08-20 23:04:39] [xxx]  Session ended - 2018-08-20 23:04:39
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by uluQulu** [comment]
hi @wassim1995 
how frequently you do get that problem?
