### ISSUE TITLE
Potency Ratio [not a tech. issue]

### ISSUE THREAD

**Issue by boldestfortune** [InstaPy/InstaPy#2664]
Hi, Sorry for posting this here as it is not an actual issue. The script is amazing. I just wanted to see peoples thoughts on Potency Ratios. 
Right now I'm having a hard time finding a good ratio. Personally, I've put it very low to ensure that the bot likes posts and doesn't skip many profiles, but is that really a good thing? Setting it too high you will end up burning bandwidth going through profiles to meet quotas (I'm using modified chrome headless which I believe does not download images.). 
The examples in the readme are very general, and I'm wondering what other peoples experience is using potency ratios. If this isn't the place for a post like this then could you direct me to where it would be. 

Thanks for all the hard work.

**Comment by JodyHicks** [comment]
This is a good topic. I wish more were open about their strategies for boosting their profiles. Personally, I adjust my potency ratios so the program follows those who have more following than followers. People who typically follow/unfollow have less following than followers, so I set my potency ratios to weed them out. Sure, I may get some dead followers, but I have scripts for like harvesting and unfollowing others.

**Comment by booksix** [comment]
I'm into this too - I love the concept, but sometimes NONE of the accounts meet the ratio and I end up doing nothing. I'd like to see the code acknowledge that the potency ratio wasn't met and NOT count that toward meeting the "amount" variable.

**Comment by boldestfortune** [comment]
Thanks for feedback guys.  I'm with you Jody. It's better to target those with more followers. I guess it comes down to experimenting until you find something that works well & avoids the fake & spam accounts.

Cheers!
