### ISSUE TITLE
Image was not able to get Liked! maybe blocked ?

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2665]
When trying to like I get this.
I am 100% sure that the account isn't blocked..

**Comment by CharlesCCC** [comment]
you liked too much, make sure you don't like more than 1000 photos per day.

**Comment by Mehran** [comment]
@CharlesCCC can tell me Proxy is work or no ? 
```
headless_browser=True, nogui = True Work Well
headless_browser=False , nogui = True not work
```

then i can't use Proxy is it Chrome issue or Insapy ?

**Comment by Florenz23** [comment]
@CharlesCCC would you suggest not to do more than 1000 actions in total (like, follow, comment, unfollow) per day, or only not more then 1000 liked per day?

**Comment by CharlesCCC** [comment]
@Florenz23 In general, meant `1000 liked` per day. (which I believe comment, follow are by-product of the main action `like`)

**Comment by CharlesCCC** [comment]
@Mehran we need more detail, can you please create a new issue to ask the question with my specific detail including your configue file ?

**Comment by Florenz23** [comment]
@CharlesCCC very true, thanks for the reply!
