### ISSUE TITLE
InstaPy following private account without tracking for future unfollow

### ISSUE THREAD

**Issue by dixaborah** [InstaPy/InstaPy#2666]
I was monitoring my followers and accounts I follow (my account is following more but little to unfollow in "myIGaccount_followedPool.cv") and notice private pages are not included in the "xxxxxxx_followedPool.cv" which makes me tend to follow more than getting more followers. I do unfollow after 12 hours and it works fine but I am not able to unfollow private accounts because their follow records are been remove from "xxxxxxx_followedPool.cv" once a follow request is been sent.
Thanks

**Comment by yoannes** [comment]
I am having this same problem but for random accounts.. some users are not being added to the followedPool.csv. Anybody else having this problem?
