### ISSUE TITLE
are possible to follow by like in insatpy?

### ISSUE THREAD

**Issue by waseem-brinsi** [InstaPy/InstaPy#2667]

**Comment by Nuzzo235** [comment]
@wassim1995 The **Follow the likers of photos of users** method should fit your needs

`session.follow_likers (['user1' , 'user2'], photos_grab_amount = 2, follow_likers_per_photo = 3, randomize=True, sleep_delay=600, interact=False)`

Cheers

**Comment by waseem-brinsi** [comment]
@Nuzzo235 thank you it works
