### ISSUE TITLE
Custom callback for commenting

### ISSUE THREAD

**Issue by ribtoks** [InstaPy/InstaPy#2669]
Would be nice if it was possible to set custom callback for commenting that would accept some sort of `context` (tags, description, username - everything that relates to the post being commented) and return comment string. 

Based on picture information user of InstaPy would make better decision what to comment instead of random selection.

**Comment by CharlesCCC** [comment]
you can use the Image recognition API to help determine which comment to use.

**Comment by ribtoks** [comment]
@CharlesCCC can you pls be more specific?

what I mean is that I would like to use whatever logic to determine which comment to use. But this is impossible with current API. Having a user's callback that will return a comment for the given post will make it very flexible and enable users to have any logic for commenting.
