### ISSUE TITLE
Follow button clicks no longer registering!

### ISSUE THREAD

**Issue by jeremycjang** [InstaPy/InstaPy#2671]
This morning I ran the ```follow_user_followers``` function with GUI enabled and realized that though the terminal states that a user is followed and it does appear that the follow button is clicked in the browser, the Selenium browser click seems to no longer be actually sending the follow request. I.E. the button is clicked, but the user is not actually followed and the button does not change to "Following".

There's a chance that Instagram has made some kind of change that stops our function that finds the button by xpath and clicks it from actually working. I have attempted changing the xpath to ```"//button[text()='Follow']"``` but the result is the same.

@sionking @uluQulu @timgrossmann can you please confirm if you are observing the same behavior and if we might need to find another solution for the ```click``` function? I will attempt testing without GUI later today to see if users are followed.

**Comment by ghost** [comment]
I think you / your ip was banned ... maybe too many actions ...
try using a proxy or wait some hour before to continue.

**Comment by jeremycjang** [comment]
@ilmetu I can still perform follow actions from my IP when using a native browser and from mobile. Are selenium browsers read differently?

**Comment by CharlesCCC** [comment]
@jeremycjang have you tried refresh the page after your clicked the "follow" or "like" ?
