### ISSUE TITLE
 'NoneType' object is not iterable  Need help !

### ISSUE THREAD

**Issue by Gearb0x** [InstaPy/InstaPy#2675]
Hi guys !

I am still struggling with  "python quickstart.py :(" .
Being new to this domain and even after checking the related issues i can't find out how to solve the error 

python --version
Python 2.7.10

macOS Sierra 10.12.6

Thank you for your help !!

## Current Behavior

MacBook-Air-de-Kevork:InstaPy Gearb0x$ python quickstart.py
WARNING [2018-08-14 17:36:23] [None]  Heeh! Error occured while getting a DB profile for 'None':
        NOT NULL constraint failed: profiles.name
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/Users/Gearb0x/InstaPy/instapy/instapy.py", line 190, in __init__
    get_database(make=True)
  File "/Users/Gearb0x/InstaPy/instapy/database_engine.py", line 43, in get_database
    id = get_profile(name, address, logger) if id is None or make else id
  File "/Users/Gearb0x/InstaPy/instapy/database_engine.py", line 129, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable

**Comment by Areahints** [comment]
try using python3 instead

**Comment by Gearb0x** [comment]
I tried already doesnt work😩

**Comment by Gearb0x** [comment]
I tried already doesnt work😩

**Comment by Areahints** [comment]
is the error the same with python3? post error message here

**Comment by Gearb0x** [comment]
Same error with python2.7 and python3

MacBook-Air-de-Kevork:InstaPy Gearb0x$ python3 quickstart.py
WARNING [2018-08-15 14:20:58] [None]  Heeh! Error occured while getting a DB profile for 'None':
        b'NOT NULL constraint failed: profiles.name'
Traceback (most recent call last):
  File "quickstart.py", line 22, in <module>
    multi_logs=True)
  File "/Users/Gearb0x/InstaPy/instapy/instapy.py", line 190, in __init__
    get_database(make=True)
  File "/Users/Gearb0x/InstaPy/instapy/database_engine.py", line 44, in get_database
    id = get_profile(name, address, logger) if id is None or make else id
  File "/Users/Gearb0x/InstaPy/instapy/database_engine.py", line 130, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable

**Comment by Gearb0x** [comment]
Just had to restart sorry for bothering you guys

**Comment by Fannolo** [comment]
Hey @Gearb0x how did you solve the issue, I tried to restart the server but it keeps showing me the error

**Comment by kkcy93** [comment]
What was the solution to this? I'm having the same problem. Total beginner here.

**Comment by sandy1812** [comment]
> Just had to restart sorry for bothering you guys

Restart didn't work for me :(

**Comment by callum8004** [comment]
I'm also having the same issue.

**Comment by WestphalM** [comment]
Having the same issue here. Did anyone fix it?

**Comment by RashminDungrani** [comment]
> Having the same issue here. Did anyone fix it?
Try to call instaPy method with your geckodriver or chromedriver location 

session = InstaPy(username="username", password="password",geckodriver_path = '/path/to/your/geckdriver/browser')
