### ISSUE TITLE
Image for Raspberry Pi 3 Model B+ anyone?

### ISSUE THREAD

**Issue by gherkins** [InstaPy/InstaPy#2676]
## Expected Behavior

...install instapy on a raspberry pi in a few minutes

## Current Behavior

spend hours of debugging outdated libraries and finding out current version of chromedriver does not work etc...

## Possible Solution (optional)

someone provided an image for the Raspberry Pi 3 Model B+
w/ instapy / chrome / chromedriver working out of the box

**Comment by meinert** [comment]
Did you get an image?

**Comment by gherkins** [comment]
@meinert 
no, actually i thought this might be a bit much to ask for.

thought of maybe posting a bounty for an raspberry image with chromium and chromedriver working

**Comment by meinert** [comment]
Planning on making an image..... Didn't expect it to be that hard......

**Comment by meinert** [comment]
Thought about running it in a docker container and deploy that on the RPI of maybe Google cloud
