### ISSUE TITLE
Like image in 1M followers

### ISSUE THREAD

**Issue by zsvendo** [InstaPy/InstaPy#2681]
I want to give like to an image of all followers that has 1M of seguiodres
How do you stop the likes of this user who owns 1M? Because the intapy only reaches the last 1000 likes right?

@uluQulu @sionking @timgrossmann @marcomokastyle

**Comment by uluQulu** [comment]
Hi @zsvendo 
Please explain clearly to get help from me 😛

-----

Cheers 😁

**Comment by zsvendo** [comment]
sorry the English.
the limit of likes in a given follower is 1000 daily, for example:
beyonce 117million followers
How do I like these 117M without repeating every day the 1000 likes in the same images?

**Comment by uluQulu** [comment]
@zsvendo 
So as far as I understood,
You want to like the images of the Big Accaunts' **followers** AND you want to like new images every time.
In other words, you don't want to see "_already liked_" message.

Right?

>Also, the limit? WHERE is limit? I don't get it.
You mean 1000 likes for a day is a daily like limit or you consider it as a good limit? - ok.

_If it is hard to explain, you can write in your own language, I will use a translator service to convert into my language_ 🤓

**Comment by zsvendo** [comment]
Obrigado por continuar respondendo.
Bom, eu gostaria de dar like em pelo menos uma imagem desses 117 milhões, não queria que repetisse os usuários, pois todos os dias o bot fica gostando dos últimos 1000 usuários correto?

**Comment by CharlesCCC** [comment]
@uluQulu  it sounds like @zsvendo would like to interact with the 117 million follower that beyonce have. 
I guess if you set interact with some specific user's follower, it should achieve his goal.

**Comment by zsvendo** [comment]
Yes that's right, but I've tried ...
Every day the bot takes the first 1000 likes in images, but I wanted to hit the ones I never reached ...

**Comment by CharlesCCC** [comment]
@zsvendo okay, the bot is acting it suppose be, because all the interaction is driven from the user posts. 
but based off your idea, it should keep interact with the list of 117 million followers, and then keep going down the list and keep track of the people you already had interaction with. uhhh, I don't think Instapy is able to achieve that at the moment, but I think it will be a very good feature to be implemented tho.

**Comment by zsvendo** [comment]
How can we put this in the next update?

**Comment by imkimchi** [comment]
Also +1 on this feature but,
if you are only trying to achieve the goal maybe it'll be easier to just code it with pupeeteer.

**Comment by CrazedRaven** [comment]
Other option for feature will be something like offset. So for example first follower to interact will be not first in someone's flowers list but 500.

To be clear:

Beyonce  followers list, we put offset 500:
1. follower - pass
2. follower - pass
.....
499 - follower - pass
500 - follower - we start here

**Comment by zsvendo** [comment]
I think if today gave 1000 likes, tomorrow it should mark the last user who gave like and get the like of 1001
