### ISSUE TITLE
Could not locate Chrome: Message: timeout

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2684]
WARNING [2018-08-15 11:03:10] [xxx]  Could not locate Chrome: Message: timeout
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-32-generic x86_64)

This happens alot. Cannot understand why?
Is it possible to solve this?

**Comment by fgisslen** [comment]
this is the log before,
so it waits 10 minutes before it throws the error.

Is it maybe possible to reload if not get result after x minutes?

INFO [2018-08-15 10:52:56] [xxx]  --> Image Liked!
INFO [2018-08-15 10:52:57] [xxx]  --> Not commented
INFO [2018-08-15 10:52:59] [xxx]  --> Not following
INFO [2018-08-15 10:52:59] [xxx]  [66/70]
INFO [2018-08-15 10:52:59] [xxx]  https://www.instagram.com/p/BmfumKOgRCy/?tagged=lookoftheday

**Comment by booksix** [comment]
Having a similar problem - would love to know whats going on or how to make it retry (possibly wifi drop outs causing this)!

**Comment by fgisslen** [comment]
#2686
