### ISSUE TITLE
which version of selenium should I use?

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2685]
Hi,
is there any reason selenium is of version 2.53? upgraded to version 3.14 and it seems to work? or am I missing anything?

**Comment by uluQulu** [comment]
Yes, @fgisslen, for selenium, it is best to upgrade to the latest version **all the time**.
>The same does not apply to web browsers & web drivers cos sometimes this combo becomes incompatible and you should always update web browser if it has a compatible web driver.
_Just read the version compatibility while downloading new web driver, it is mostly written in **release notes**._ 

If you really wonder why you see exactly `2.53.6`, open up **setup.py** file in the project root folder to see the `requirements` _list_ containing default versions written some time ago which are now out-dated and should be updated.

Maybe you can make a PR containing that list with the updated versioning, eh? 🤓

----------
Cheers 😁
------

**Comment by fgisslen** [comment]
Here you have a typical error:
It not only happens with like_by_feed, it can happen with all kinds of requests.

I think probably it happens when the request to the proxy server fails and it just waits until timeout.

INFO [2018-08-16 09:41:35] [xxx]  Post [2/5]
INFO [2018-08-16 09:41:35] [xxx]  https://www.instagram.com/p/BmiKSNyHieG/?taken-by=joshi_ji_1111
WARNING [2018-08-16 10:01:35] [xxx]  Could not locate Chrome: Message: timeout
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-32-generic x86_64)


OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-08-16 10:01:35] [xxx]  Session ended - 2018-08-16 10:01:35
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "/home/fredrik/InstaPy/5b62a628a5231c0014b19e48.py", line 25, in <module>
    session.like_by_feed(amount=60, randomize=True, unfollow=False, interact=True)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 2327, in like_by_feed
    for i in self.like_by_feed_generator(**kwargs):
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 2456, in like_by_feed_generator
    self.user_interact_media)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 1462, in like_by_users
    self.logger)
  File "/home/fredrik/InstaPy/instapy/like_util.py", line 405, in check_link
    web_adress_navigator(browser, post_link)
  File "/home/fredrik/InstaPy/instapy/util.py", line 596, in web_adress_navigator
    browser.get(link)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-32-generic x86_64)
