### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MrJamsn** [InstaPy/InstaPy#2688]
As i want to write a HTML site (for private use only) it would be nice if the Username and Password could be stored outside the quickstart.py file. so that every time the scripts starts, it calls for this file while logging in. 

I am really new to Python so i can't do it on my own, i don't know where to start. 
Sorry if i wrote this feature request wrong, inform me and delete it if so :)

**Comment by doubledare704** [comment]
you can create new .py file in same dir as quickstart.py, in that file set username and password, save it.
In quickstart.py import file as 
import newfile
then use constants from those file:
session = InstaPy(username=newfile.username,
                  password=newfile.password,
                  headless_browser=False,
                  multi_logs=True)
It will work only if you have set username and password in new file

**Comment by MrJamsn** [comment]
thanks for that!! another point i'm thinking about is - does 2FA work with the bot?

**Comment by doubledare704** [comment]
@MrJamsn , i think it doesn't, as 2FA was not mentioned in features, and 2FA is difficult to implement as single library: 2nd factor could be sms, email, or telegram one time code e.g.

**Comment by MrJamsn** [comment]
okay thank you - i can live with that :)

One more questions. i've searched but nothing found and i don't want to open many threads:

1) anyway possible to youe  a txt or csv file instead of the list of tag in quickstart.py?
2) any way to change the path of the logs outside? so that i can see general_log within my apache?

Thanks!

**Comment by doubledare704** [comment]
1. https://docs.python.org/2/tutorial/inputoutput.html#methods-of-file-objects
2. https://docs.python.org/2/howto/logging.html#logging-to-a-file

**Comment by MrJamsn** [comment]
thank you! Log i found by my self. The link helps me for 1)
