### ISSUE TITLE
Location based tags (feature request)

### ISSUE THREAD

**Issue by dylancaponi** [InstaPy/InstaPy#269]
Would be nice to like based on geo location, eg:
https://www.instagram.com/explore/locations/86195/petersen-automotive-museum/

**Comment by ghost** [comment]
@dylancaponi you could use the location code from here https://www.instagram.com/explore/locations/ look up your area code you want to here and make a function the searched for it eg. like_by_location instead of like_by_tags.

**Comment by timgrossmann** [comment]
#3

**Comment by arisanguinetti** [comment]
It is possible to use Instagram API to get a list of post on certain latitudes/longitud and then apply the hashtag rules on that list. For example look all posts in certain area with the API and then for each one, check the hashtags, ignored words, ignored users, etc.

**Comment by timgrossmann** [comment]
@arisanguinetti I specifically didn't use the InstagramAPI and probably won't do it with the newer features.
You can do the same thing with the link given by @imakethefish

**Comment by dylancaponi** [comment]
Sent merge request.

**Comment by timgrossmann** [comment]
#276

**Comment by Tozzato** [comment]
@timgrossmann It's possible to filtering posts by location and after make a another filtering only by tags ?
