### ISSUE TITLE
Instagram does not log in 

### ISSUE THREAD

**Issue by Jenuan** [InstaPy/InstaPy#2693]
when I run with headless mode off, I can see that instapy is directly going to try to like and comment before even log in. 
It seems that instapy can't log in and then it just jumps to work and Instagram does not allow it to do stuff because im not logged in.

**Comment by JosteinFraNorge** [comment]
How do you start the program?
Have you supplied your login details in eg quickstart.py?

**Comment by Jenuan** [comment]
yes I have supplied the login details @herrgutt
