### ISSUE TITLE
Language independent 

### ISSUE THREAD

**Issue by rafo** [InstaPy/InstaPy#27]
The like function isn't language independent.

**Comment by timgrossmann** [comment]
Could you give an example of your "like"-method call?
Or what do you mean by "The like function isn't language independent." ? Could you give me an explanation? 
Thanks

**Comment by rafo** [comment]
The problem is that when you are using chrome on another locale - let's say German - the instagram like btn isn't lanes "like" anymore but "Gefällt mir". So your "if else" condition will never like an image if you are running the browser or os in a different language than English.

**Comment by timgrossmann** [comment]
Ohh, well that really is a big problem...
I'll try to look into that as soon as possible

Thanks for pointing that out!

**Comment by timgrossmann** [comment]
Issue is #28
