### ISSUE TITLE
Discussion - Best tips to 10k Followers 

### ISSUE THREAD

**Issue by Areahints** [InstaPy/InstaPy#2700]
So I'm wondering if you have any tips you want to share with the community on how to get to the much coveted *k* amount of followers using InstaPy, I'm hoping everyone can contribute so this can be used as a guide! Please add your tips. 

- Always shuffle your hashtag parameters. 

- Comments work better when you mention  the account but don't over use them. 

- A script that runs for shorter ranges of time is more effective. 

- it's better to create a script for follows, for likes and comments, then for unfollows, helps with troubleshooting too.

**Comment by imjustin** [comment]
Not so much a direct tip but more of a strategic thing: be patient. It's easy to discover a tool like instapy and immediately crank it all the way up. And you'll just get banned/blocked right away. If you have to ask "Is this many X too many" the answer is probably yes, you should slow down and work your way up to it.
