### ISSUE TITLE
proxy without auth

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2702]
set_selenium_local_session
   proxy = ":".join([self.proxy_address, self.proxy_port])
ypeError: sequence item 1: expected str instance, int found

I converted the port to int so the check for > 0 will not fail but it fails on this one.
No one experienced that ?

**Comment by sionking** [comment]
```
           # Proxy for chrome
            if self.proxy_address and self.proxy_port > 0:
                prox = Proxy()
                proxy = ":".join([self.proxy_address, self.proxy_port])
                prox.proxy_type = ProxyType.MANUAL
                prox.http_proxy = proxy
                prox.socks_proxy = proxy
                prox.ssl_proxy = proxy
                prox.add_to_capabilities(capabilities)
```

**Comment by fgisslen** [comment]
You can do this:
proxy = ":".join([self.proxy_address, str(self.proxy_port)])

**Comment by sionking** [comment]
@fgisslen I know how to solve but anyone ever got yet ? how is that passable ?

**Comment by fgisslen** [comment]
@sionking I use that solution I sent to you.

**Comment by Mehran** [comment]
@sionking  `if self.proxy_address and self.proxy_port > 0:`  to `if self.proxy_address and len(self.proxy_port) > 0:` . solved my issue .

also use `proxy_port = '1234'`

**Comment by imkimchi** [comment]
having the same issue.

**Comment by fgisslen** [comment]
@imkimchi on line 299 in instapy, cast str() to the port

**Comment by imkimchi** [comment]
@fgisslen yea thanks, I solved it by fixing it but did anyone make a PR for this?
