### ISSUE TITLE
Two Instagram accounts acting differently 

### ISSUE THREAD

**Issue by rooleyzee123** [InstaPy/InstaPy#2706]
So I have two different Instagram accounts using instaPy both with the same script (same like by tag,tags and amount). But one account gets very little attention compared to what it used to get whilst the other gets as much as the other one used to and is carrying on getting it.

I know Shadow bans are a thing but im not 100% what that entails. 

Just wanting to see if anyone has any ideas what might be causing basically two identical accounts with the same script, one now failing to get the likes/follows it used to vs the other one which does?

**Comment by c0d3x27** [comment]
how can you run 2 accounts at the same time im trying but no luck
