### ISSUE TITLE
multiple accounts not working

### ISSUE THREAD

**Issue by c0d3x27** [InstaPy/InstaPy#2708]
insta_username = 'bangi'
insta_password = 'flowers'

 set headless_browser=True if you want to run InstaPy on a server

 set these in instapy/settings.py if you're locating the
 library in the /usr/lib/pythonX.X/ directory:
   Settings.database_location = '/path/to/instapy.db'
   Settings.chromedriver_location = '/path/to/chromedriver'
session = InstaPy(username='maria', password='D198d9')
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

im trying to run both my accounts but is not working any help please??

**Comment by jeremycjang** [comment]
@Banginpadr I'd recommend editing your post and removing the usernames and passwords immediately if those are the actual credentials.

**Comment by c0d3x27** [comment]
@jeremycjang did thanks bro

**Comment by mikestan** [comment]
I'm curious about this one. Can you provide more detail on what's happening, i.e. use the template when you click the new issue button? What OS? What's the error? Has this ever worked?

At first glance I'm leaning toward "you can't do it that way." I run multiple accounts and have a quickstart.py file for each. Then (on UNIX) I run them via a cron job at different times of the day.

**Comment by c0d3x27** [comment]
> At first glance I'm leaning toward "you can't do it that way." I run multiple accounts and have a quickstart.py file for each. Then (on UNIX) I run them via a cron job at different times of the day.

yes thats how it works now

**Comment by Madgeniusblink** [comment]
@mikestan 
Hi Mike,

Could you show us an example of how each quickstart.py file should look like?

Correct me if I am wrong but let’s say I have four accounts and I would like to put the engagement on autopilot, so I would create 4 different quickstart.py files with the "multi_logs=True and each file with its own proper credentials and then afterwards, create a main file to execute each quickstart.py file one by one?

**Comment by c0d3x27** [comment]
> @mikestan
> Hi Mike,
> 
> Could you show us an example of how each quickstart.py file should look like?
> 
> Correct me if I am wrong but let’s say I have four accounts and I would like to put the engagement on autopilot, so I would create 4 different quickstart.py files with the "multi_logs=True and each file with its own proper credentials and then afterwards, create a main file to execute each quickstart.py file one by one?

yeah i think is the only way about multiple accounts. you just cant fire up all 4 at once in the same pc. at least from what i understood here
