### ISSUE TITLE
it keep stoping

### ISSUE THREAD

**Issue by c0d3x27** [InstaPy/InstaPy#2709]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-08-18 05:59:38] [banpa]  Session ended - 2018-08-18 05:59:38
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "quickstart.py", line 48, in <module>
    session.like_by_tags(['sexy', 'fit', 'gym', 'fitlife', 'bike', 'biker', 'ducati', 'workout', 'travel', 'fitness'], amount=800,interact=True)
  File "/Users/banginpadr/Downloads/InstaPy/instapy/instapy.py", line 1348, in like_by_tags
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 48: ordinal not in range(128)

Traceback (most recent call last):
  File "quickstart2.py", line 51, in <module>
    session.like_by_tags(['sexy', 'fit', 'gym', 'fitlife', 'fitnessmodel', 'girl', 'model', 'workout', 'ass', 'travel', 'modeling', 'gymgoal'], amount=800,interact=True)
  File "/Users/banginpadr/Downloads/InstaPy/instapy/instapy.py", line 1348, in like_by_tags
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 48: ordinal not in range(128)

i keep getting this errors it runs only for a bit

**Comment by kushpvo** [comment]
Same here.

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
