### ISSUE TITLE
EasyProcess InstaPy GUI

### ISSUE THREAD

**Issue by gitjayjay** [InstaPy/InstaPy#271]
So my cmd is telling me: C:\Users\Desktop\InstaPy-master>pip install EasyProcess
Requirement already satisfied (use --upgrade to upgrade): EasyProcess in c:\users\anaconda3\lib\site-packages

Is my path for easyprocess wrong? B/c every single file has been downloaded but can't seem to get the GUI to work on my windows... Thank you for all the help whoever responds!!!

**Comment by timgrossmann** [comment]
@gitjayjay You should probably also post this issue at the github repo of the GUI tool

**Comment by gitjayjay** [comment]
@timgrossmann  I have, Nemanja told me to ask on here cause none of his solutions worked haha

**Comment by timgrossmann** [comment]
@gitjayjay Ahh, good to know.
Let's see if there's someone with the same problems  😄 

Did you try installing EasyProcess with pip3?`pip3.5 install EasyProcess`
