### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by elijahhezekiah12** [InstaPy/InstaPy#2716]
## Expected Behavior
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-08-19 18:38:41] [symmetricsplit]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Issue with cookie for user symmetricsplit. Creating new cookie...

....................................................................
INFO [2018-08-19 18:39:00] [symmetricsplit]  Logged in successfully!
## Current Behavior
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-08-19 20:37:02] [symmetricsplit]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Issue with cookie for user symmetricsplit. Creating new cookie...

..............................................................
CRITICAL [2018-08-19 20:37:18] [symmetricsplit]  Wrong login data!
## InstaPy configuration
I am running this on a digital ocean sever and it usually works but I don't know what is going on now

**Comment by CharlesCCC** [comment]
cookie seems expired. delete the existing one and re-login again.

**Comment by sionking** [comment]
DO not working with IG

**Comment by CharlesCCC** [comment]
@sionking is the proxy will help him ?

**Comment by dixaborah** [comment]
My user name and password is actually inputted on the landing page ( instagram.com) before the login page is opened, which causes  the error

.................................................................
CRITICAL [2018-08-23 06:57:43] [MyInstagramUsername]  Wrong login data!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

**Comment by dixaborah** [comment]
I figured out how to make it work but requires manual manipulations, that is after instapy automatically logs in, the link the app opens next is instagram.com/YourUsername/ so after trying so many times, I decided to login myself (that is after running quickstart.py) then open my IG page (instagram.com/YourUsername/ ).
Instapy automatically continues with 
.......................................................................
INFO [2018-08-23 07:33:11] [MyIGUserName]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
I am running it on my laptop.
I hope this helps.

**Comment by meinert** [comment]
Have the same problem.....but for some reason only for one specific account. I have another account that works fine....even if I delete the cookiefile it is create again.

**Comment by meinert** [comment]
My workaround was a breakpoint here:
```
 # Check if user is logged-in (If there's two 'nav' elements)
    nav = browser.find_elements_by_xpath('//nav')
```
Before proceding I logged in using mail instead of the username and enterede the code recieved by mail. Then everything has worked afterwards.

But login using my username does not work - not only using Instapy but everywhere - anyone else experienced that?

**Comment by dixaborah** [comment]
Any Help ?
My method works fine but after Instapy following users, commenting, liking, it cannot unfollow users. 
@CharlesCCC is the cookie file found in instapy/logs/MyIGUsername/MyIGUsername_cookie.pkl ?
I extracted instapy-master and just copied my quickstart.py file into it but still can't login in automatically.
