### ISSUE TITLE
Failed to load desired amount of users

### ISSUE THREAD

**Issue by cormo1990** [InstaPy/InstaPy#2721]
Latest version of InstaPy

Can someone help me please?
this error happen during following followers

thanks in advance friends

@uluQulu

**Comment by santhoshraje** [comment]
I've been getting this error today too. Was working fine yesterday.

**Comment by Mehran** [comment]
same error today

**Comment by cormo1990** [comment]
the issue persists, i tried with other account and I have the same problem...

@sionking @uluQulu @timgrossmann  can you please help us to fix this issue?
thanks in advance

**Comment by cormo1990** [comment]
UPDATE:
The problem persists also during when you try to follow the likers of a user's post.
so i think IG has changed the scroll method or something similar...
i hope that info can be helpful for fix that problem

**Comment by sionking** [comment]
I see that the followers/following list of a user not updating when scrolling...

**Comment by sionking** [comment]
I hope it is temporary (seen that before)

**Comment by sionking** [comment]
I found out that it is working after following a few ppl from the list first (maybe turn on the simulated follow @uluQulu for this temporary fix) anyway I don't use it ...

**Comment by Mehran** [comment]
@sionking Also this happen when `unfollow `users .

**Comment by sionking** [comment]
@Mehran which unfollow do you do, which configurations?
BTW, it is like this in the mobile as well.

**Comment by Mehran** [comment]
@sionking ` session.unfollow_users(amount=550, allFollowing=True, style="RANDOM", sleep_delay=450)`

**Comment by cormo1990** [comment]
@sionking the simulated follow is on to the default settings right? how can i check if is on?
BTW i agree with you, the problem is on the scrolling step

thanks for the support buddy

**Comment by sionking** [comment]
I think it is on, but this not gurentee scrolling to work it just something I noticed helpinmg ...

**Comment by cormo1990** [comment]
@sionking ok thanks, i've just check and simulated follow is active but the problem persists...hope that @uluQulu can support us...I don't know if this happen also to other user

**Comment by cormo1990** [comment]
UPDATE:
Now also during the Unfollowing action the issue persists.

can someone help please? Thank you so much

**Comment by DavidMolinari** [comment]
Is it happening with large amount of users ?
I've done some following / unfollowing few sec ago and it seems to work

```python
{"XXX": {"2018-08-20": {"likes": 0, "comments": 0, "follows": 0, "unfollows": 50, "server_calls": 53}, "2018-08-21": {"likes": 0, "comments": 0, "follows": 0, "unfollows": 50, "server_calls": 52}}}
```



```bash
INFO [2018-08-21 16:05:20] [XXX]  --> Followed total of 5 people

INFO [2018-08-21 16:05:20] [XXX]  Liked: 0
INFO [2018-08-21 16:05:20] [XXX]  Already Liked: 0
INFO [2018-08-21 16:05:20] [XXX]  Commented: 0
INFO [2018-08-21 16:05:20] [XXX]  Followed: 5
INFO [2018-08-21 16:05:20] [XXX]  Inappropriate: 0
INFO [2018-08-21 16:05:20] [XXX]  Not valid users: 5

INFO [2018-08-21 16:05:23] [XXX]  Session ended - 2018-08-21 16:05:23
```

**Comment by cormo1990** [comment]
yes, around 800 more or less to follow and unfollow.
I continue to have this issue

**Comment by santhoshraje** [comment]
I have tried with a relatively small amount (100 follows). Still having this issue too.

**Comment by mrb** [comment]
The issue is that the scroll window isn't loading more than 12 users (e.g. visit https://www.instagram.com/USERNAME/followers/ in a web browser when logged in and you'll see it caps at 12, and the scrolldown no longer works)

**Comment by cormo1990** [comment]
Exactly, i don't know how to fix that problem :(

i believe that this problem happen to all the user... or not?

**Comment by jeremycjang** [comment]
@cormo1990 What @mrb pointed out is that this isn't a problem with our program, but rather that Instagram is currently only loading 12 users when you go to someone's "Followers" list on desktop. 

This could be another glitch by Instagram or could be intended behavior. If the latter, I confirmed that full scrolling still works on mobile, so perhaps we could look into launching a mobile simulation again, which I remember we looked into when there was another Instagram desktop glitch :)

**Comment by ilmetu** [comment]
same error here

**Comment by ghost** [comment]
same error here

@jeremycjang i just try to see if in mobile desktop work the scrolling method but it doesn't work either

it fetch another 12 followers only if you click on the "Follow" button of the last follower ...
and so on ...

it's definetly a glitch, if you resize the page , will appear 12 more
and then if you resize again will appear another 12 ...

maybe we can write a workaround:

browser.set_window_size(480, 320)
browser.set_window_size(800, 600)
...

just give it a try

**Comment by ilmetu** [comment]
it fetch another 12 followers only if you click on the "Follow" button of the last follower ... 
and so on ...

**Comment by ilmetu** [comment]
it's definetly a glitch, if you resize the page , will appear 12 more
and then if you resize again will appear another 12 ...

just give it a try

**Comment by cormo1990** [comment]
thanks to all for the support, can someone guide me to implement the code in the correct place in order to try if it works? thanks

**Comment by santhoshraje** [comment]
@ilmetu you are right. Every time I resize the browser window, new followers are loaded. More followers are loaded when the browser window is made either bigger or smaller, even by a tiny amount. 

I guess a loop to resize the browser window after each load should work?

**Comment by ghost** [comment]
@santhoshraje yes should work but i think it's just a glitch ... maybe instagram will fix this soon

**Comment by tompicca** [comment]
Same problem here when try to follow users. Any Update?

**Comment by breurlucas** [comment]
Same here, did anyone get that resize loop to work?

**Comment by sionking** [comment]
It was like this few monthes a go and came back. followers are public by instagram terms of use. dont worry.

**Comment by ghost** [comment]
@tompicca i'm working on it

**Comment by ghost** [comment]
hi everybody , 

i just found a very easy hack , is a very very temporary solution.

in the file util.py , the scroll_bottom function need some modifications check this gists

https://gist.github.com/ilmetu/b8544ff2c0feafa1c5cfb248b498b05d

as i said ... it's a very temporary solution but it works well

**Comment by ghost** [comment]
i modified the gists so it can be used all the time without any problems

before the scroll i modified the size height and after the scroll i reset to the previous setting.

so far so good.

**Comment by sionking** [comment]
wait it will came back to normal. any way I recommend scrapping

**Comment by sionking** [comment]
It works now

**Comment by ghost** [comment]
@sionking  for me it doesn't work yet ... 

any way i just made a PR  https://github.com/timgrossmann/InstaPy/pull/2725

**Comment by breurlucas** [comment]
Good stuff @ilmetu thank you

**Comment by tompicca** [comment]
Works like a charm now! Thanks @ilmetu

**Comment by cormo1990** [comment]
@ilmetu awesome work buddy! it works! thanks again, I'll close the issue

**Comment by raulafrosa** [comment]
Not working here, even after changes :/

**Comment by zsvendo** [comment]
Not working here, even after changes :/

**Comment by cormo1990** [comment]
@raulrosa89 @zsvendo I've just tried again and works good, are you sure that the modify in file util.py is correct?

see #2725 

Let me know

**Comment by santhoshraje** [comment]
@raulrosa89 @zsvendo Im testing it right now. Seems to be working fine. What is the error that you are getting?

**Comment by raulafrosa** [comment]
When I'm using dont_unfollow_active_users it only catch 12: 
Post 1  |  Likers: found 98, catched 12

Other things work normally.

**Comment by uluQulu** [comment]
@raulrosa89 
It has a custom scroller,
to solve it, add these `3` lines into `get_active_users` definition in **util.py** file
1.
```python
            try_again = 0
            window_size = browser.get_window_size()   ## NEW LINE
```
2.
```python
                        return false;}
                    ''', dialog)

                window_size["width"] = window_size["width"]+1 if sc_rolled%2==0 else window_size["width"]-1   ## NEW LINE
                browser.set_window_size(window_size["width"], window_size["height"])   ## NEW LINE
```

**Comment by raulafrosa** [comment]
\o/ thx a lot, work fine.

**Comment by bgunsberger** [comment]
Didn't work for me. Also, this might be a stupid question, but how/when do fixes like this get added? How long do we need to need to maintain our own tweaks to the code?

**Comment by uluQulu** [comment]
specify details, @bgunsberger
+ What didn't work?
+ What does not work?

**Comment by bgunsberger** [comment]
I still get the same 12-user limit, even with the lines above added.

**Comment by berateyuboglu** [comment]
@ilmetu thanks, your code worked perfectly. but;

after i got this error

```
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-08-24 04:17:29] [testuser]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo


................................................................
INFO [2018-08-24 04:18:01] [testuser]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-08-24 04:18:04] [testuser]  User 'USERBLABLA' [1/1]
INFO [2018-08-24 04:18:23] [testuser]  Simulated follow : 1
INFO [2018-08-24 04:18:26] [testuser]  --> Followed b'guta.iaroslav'
Traceback (most recent call last):
  File "berat.py", line 12, in <module>
    session.follow_user_followers(['USERBLALA'], amount=100, sleep_delay=600, randomize=True, interact=False)
  File "C:\Users\berate\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg\instapy\instapy.py", line 2052, in follow_user_followers
    self.logfolder)
  File "C:\Users\berate\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg\instapy\unfollow_util.py", line 900, in get_given_user_followers
    channel, logger, logfolder)
  File "C:\Users\berate\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg\instapy\unfollow_util.py", line 661, in get_users_through_dialog
    scroll_bottom(browser, dialog, 2)
  File "C:\Users\berate\AppData\Local\Programs\Python\Python36-32\lib\site-packages\instagram_py-0.0.1-py3.6.egg\instapy\util.py", line 431, in scroll_bottom
    "arguments[0].scrollTop = arguments[0].scrollHeight", element)
  File "C:\Users\berate\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 635, in execute_script
    'args': converted_args})['value']
  File "C:\Users\berate\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\berate\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.10586 x86_64)
```

**Comment by meinert** [comment]
Used the concept of the modification suggested by @ilmetu on likers_from_photo method.....works again :-)
