### ISSUE TITLE
Xvfb / rPi3 / noGui / no monitor connected - resolution change

### ISSUE THREAD

**Issue by JMuffin** [InstaPy/InstaPy#2722]
I'n running InstaPy on rPi3 without monitor connected. 
Xvfb shows screen 0 resolution of 800x600x24 in cron status.
My main resolution is way bigger so is there easy option to change that Xvfb res?

I think it's the cause of constatnly getting "Button not found" errors :/

**Comment by 0x000777** [comment]
I think this is due to the weak power of rPi. The browser does not have time to display the page and the script is already looking for the button, but can not find it.
