### ISSUE TITLE
want to use ' in comments

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2723]
Hi,
If i want to use ' in comments, is it just to write \' ?

**Comment by jeremycjang** [comment]
Try escaping it with \ 

```
session.set_comments([‘that\’s the way’])
```

Without escaping, you’re going to break the string and probably stop your program from running since there’ll be an un-closed string

**Comment by fgisslen** [comment]
@jeremycjang Thx, I will try that
