### ISSUE TITLE
Quickstart.py not working

### ISSUE THREAD

**Issue by c0d3x27** [InstaPy/InstaPy#2728]
i have "session = InstaPy(username='test', password='test', headless_browser=False)" so i can see what profiles im following, liking ect but is not working. it was working before i changed it from True. now that i put it back to False is not working. why is that??

    #like by locations
    session.like_by_locations(['213050058', '70694933', '213928996', '683118252', '251927110144',
    '214219534', '249785880', '213545145', '215787651', '6949103', '214249380', '213830427', '214548286',
    '235570143', '214914621', '213105555', '215882656', '696520589', '219114734',
    '214283362', '218445886', '213033286', '215042939', '213774714', '217646677'], amount=10, skip_top_posts=True)
    session.comment_by_locations(['213050058', '70694933', '213928996', '683118252', '251927110144',
    '214219534', '249785880', '213545145', '215787651', '6949103', '214249380', '213830427', '214548286',
    '235570143', '214914621', '213105555', '215882656', '696520589', '219114734',
    '214283362', '218445886', '213033286', '215042939', '213774714', '217646677'], amount=10, skip_top_posts=True)

this is the only changed i did to my file..

**Comment by CharlesCCC** [comment]
what error message are you getting ?

**Comment by c0d3x27** [comment]
@CharlesCCC chrome not opening even having headless_browser= false...but is all good i will have a work around. thank you for asking. i will close it
