### ISSUE TITLE
Delays for Likes

### ISSUE THREAD

**Issue by c0d3x27** [InstaPy/InstaPy#2730]
how can i set-up a delay between Likes on quickstart.py also Randomize the time between likes for example to 50%?

**Comment by jzos** [comment]
So, if I understand you correctly, you want to randomize the time between each like, correct? If so, you can do this:

Open instapy/instapy.py and go to def like_by_tag and add this:

`sleep_delay=60`

So it should look like this:

```
    def like_by_tags(self,
                     tags=None,
                     amount=50,
                     skip_top_posts=True,
                     use_smart_hashtags=False,
                     interact=False,
                     randomize=False,
                     media=None,
                     sleep_delay=60):
```



Then look for this under the function:

```
            try:
                links = get_links_for_tag(self.browser,
```

and add this:

`sleep(sleep_delay)`
                
So it should look like this:

```
try:
                sleep(sleep_delay)
                links = get_links_for_tag(self.browser,


```


In your code on your page, you can use this:

```
import random

session.like_by_tags(
            ['sunset', 'photography', 'camping', 'hiking', 'offroad'],
            amount=1, sleep_delay=(random.randrange(60,240,3)))

```

This will randomize the likes between 60 seconds and 240 seconds.

**Comment by c0d3x27** [comment]
@jzos bro you are the man

**Comment by c0d3x27** [comment]
@jzos is giving me this ./instapy/instapy.py:2791:23: F821 undefined name 'sleep_delay'
                sleep(sleep_delay)
                      ^
