### ISSUE TITLE
instagram is only showing list of 12 following

### ISSUE THREAD

**Issue by sunnygill** [InstaPy/InstaPy#2731]
Is anybody else seeing this issue. I am only able to unfollow 12 users. I tried login from firefox and chrome browser also and found out that instagram is only showing a list of 12 users in "following"

**Comment by x225am** [comment]
Same issue for me. Checked 2 accounts tried reinstall InstaPy. Looks like something global happened

**Comment by ghost** [comment]
duplicated question , please check https://github.com/timgrossmann/InstaPy/issues/2721#issuecomment-414787035
