### ISSUE TITLE
Failed to load desired amount of users

### ISSUE THREAD

**Issue by assafzeek** [InstaPy/InstaPy#2733]
## Expected Behavior
Allow interacting with at least a few hundreds of users
## Current Behavior
Can't load more than 40. I've pulled the latest version including the scrolling fix. The error is "Less users to follow than requested." or "Failed to load desired amount of users"

## InstaPy configuration
Running it with a basic script:
`
session.set_user_interact(amount=3, randomize=True, percentage=80)

session.follow_user_followers(['usernames''], amount=140, randomize=True, interact=True, sleep_delay=60)`

**Comment by clevebounce** [comment]
same problem here

**Comment by 0x000777** [comment]
Me too, have this problem...

**Comment by cormo1990** [comment]
I've just tried again and works good, are you sure that the scrolling fix implemented in your util.py is correct?

see #2725 and try again, let me know

**Comment by assafzeek** [comment]
Working partially. At some point 'about' variable results in True. In other words, about = before_scroll == total_list (in while loop in get_users_through_dialog method

**Comment by assafzeek** [comment]
@cormo1990 could this be an issue with the linux version? It works well on Mac

**Comment by JonathandelaSen** [comment]
Same problem here on Ubuntu.

**Comment by NightMachinery** [comment]
Same problem, it works on my macOS but on my Ubuntu server (which used to work properly). The codebase is exactly the same. (I have this problem when unfollowing users. I haven't tested the user interactions part.)
