### ISSUE TITLE
Issue with follow users followers funtion

### ISSUE THREAD

**Issue by luiztim** [InstaPy/InstaPy#2737]
The "follow user followers" functions gets hung sometimes.
When the automation "clicks" on the account profile followers link, a modal pops up and, the code tries to follow the users listed there. Instagram does not pulls the complete list of followers a user has and, when Instagram brings me a full list of users that I´m already following, the code can´t populate the array and hangs...

I attached a print screen when instaPy hangs - you will notice that the code works fine until it encounters a situation described above... doesn't matter if you´re using headless browser or not...

![bug2](https://user-images.githubusercontent.com/35818924/44471790-0abbe980-a603-11e8-9a08-357e9d2ae357.png)

**Comment by samihamine** [comment]
Same problem here !

**Comment by samihamine** [comment]
@luiztim it's has already been solved by @uluQulu at [#2555](https://github.com/timgrossmann/InstaPy/issues/2555#issuecomment-410475845)

**Comment by luiztim** [comment]
Hey @SammyHam !! Thank you so much - just updated my code - left the robot running / test
I´ll post my results once test finished 
;)

**Comment by luiztim** [comment]
Seems solved.... @SammyHam  how can we commit the change to the master ?

**Comment by samihamine** [comment]
@luiztim Great! it's already merged with the master 😊 you just have to clone the current master! 
Could you at the same time close this issue ?  👌

**Comment by luiztim** [comment]
Awesome !!
You guys rocks !!
