### ISSUE TITLE
 Unfollow loop error:  unknown error: 

### ISSUE THREAD

**Issue by wrhsescp** [InstaPy/InstaPy#2738]
when using the unfollow feature, after retreiving data i get this message: 
 Unfollow loop error:  Message: unknown error: Cannot read property 'activity_counts' of undefined
 (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565498

**Comment by succulentia** [comment]
Well, I could not solve this problem either by the solution @uluQulu suggested as the user in my case no longer exists. I tried to resolve but no luck. I changed my crontabs to do regular unfollow to bring things back to normal as my follow number piled up big time.

**Comment by uluQulu** [comment]
I did not suggest anything to your problem, @succulentia 😂


For your issue, @wrhsescp 
Have a look at https://github.com/timgrossmann/InstaPy/issues/2717#issuecomment-414160468 to see the solution.


------------

Cheers 😁
----------

**Comment by krystofcelba** [comment]
@wrhsescp @succulentia Try simply remove this [piece of code](https://github.com/timgrossmann/InstaPy/blob/d8fca75481ae3891090a47c4dbc84d69b8cfa9c3/instapy/unfollow_util.py#L309-L316) from unfollow_util.py. It fixes the issue for me. I've wanted to add a condition which would checks if the user is logged the same way as [here](https://github.com/timgrossmann/InstaPy/blob/d8fca75481ae3891090a47c4dbc84d69b8cfa9c3/instapy/login_util.py#L119-L120) and try to get logged in again if not. But I think that it would need some bigger changes in architecture, and it seems it works quite good even without that at all. At least for me.

**Comment by uluQulu** [comment]
@krystofcelba 
In case of a REAL invalid connection you will **simply remove** ALL of the usernames from your followed pool by **simply removing** THAT piece of code 😂
I have suggested an initial fix for the problem at https://github.com/timgrossmann/InstaPy/issues/2717#issuecomment-415238939, feel free to use it.

-----------

Cheers 😁
-------------
