### ISSUE TITLE
[HELP ME] Install InstaPy (TeamViewer)

### ISSUE THREAD

**Issue by SEOAlexRamon** [InstaPy/InstaPy#2741]
Could someone help me install InstaPy on my laptop through TeamViewer? Thanks in advance.

**Comment by Mehran** [comment]
what is your Operating System ?

**Comment by SEOAlexRamon** [comment]
Windows 10

**Comment by headebeast** [comment]
I need help as well if someone could help me with teamviewer aswell

**Comment by headebeast** [comment]
btw I am on windows 10
