### ISSUE TITLE
Following problem ?

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#2751]
Hello, trying to follow users of a user or following commenters of a user but same problem,
its says in the terminal that its following but in reality its not following.

Any idea please ? 
Many thanks

**Comment by dpashutskii** [comment]
The same problem but with likes.
It says it likes, but it's not in real life.

**Comment by CharlesCCC** [comment]
@Edhim @guar47 you get `soft` banned from Instagram. please reduce the amount of engagement (like, following).

**Comment by dpashutskii** [comment]
@CharlesCCC Why I can like manually and comments working?

**Comment by Edhim** [comment]
@CharlesCCC - same i can manually follow, comment .. ;-) - didn't even use the script for 1 week

**Comment by CharlesCCC** [comment]
yea, that the reason it called `soft banned`  we have seeming this so many times. 
basically, you can like/follow through your phone app, but not on the web. 

one thing you can try is reboot your modem and get a new IP address.  otherwise, stop it for few days/reduce the amount for a bit.

**Comment by Edhim** [comment]
@CharlesCCC  @guar47 right, i changed the ip and seems to work now

**Comment by sionking** [comment]
@charlesCCC do you think soft ban is also with applications like Jravee which simulate  a phone? I think it is not related to web but to the machine that do the actions.

**Comment by CharlesCCC** [comment]
@sionking possible, I can't tell for sure because haven't notice any obvious evidence yet.
