### ISSUE TITLE
Failed to load desired amount of users

### ISSUE THREAD

**Issue by raulafrosa** [InstaPy/InstaPy#2760]
I correct the same problem of #2754 but now I note able to load more than 9-12 peoples in interact_user_followers.

I have already made changes proposed in #2725.
I think they change again the scroll :/

**Comment by raulrosa89** [comment]
same as #2745, just see now

**Comment by martinsnajdr** [comment]
I have the same problem. +1

**Comment by raulrosa89** [comment]
fixed in #2745

**Comment by raulafrosa** [comment]
fized in #2757

**Comment by walteralleyz** [comment]
Instead of using "amount" I looped the desired amount, and left "amount" = 1.
Not the best solution, but it works for now.
