### ISSUE TITLE
Correct way to update InstaPy?

### ISSUE THREAD

**Issue by deronsizemore** [InstaPy/InstaPy#2761]
I installed InstaPy following the "Preferred Installation" steps:

1. virtualenv venv
2. source venv/bin/activate
3. pip install git+https://github.com/timgrossmann/InstaPy.git

I haven't used it for a few months and wanted to update things to ensure I've got the latest, but I'm not real sure how to do that?

Is it as simple as doing:

`pip install git+https://github.com/timgrossmann/InstaPy.git --upgrade`?

I've customized my `quickstart.py` file like I assume everyone has. I'm afraid that it will get overwritten during the upgrade process and I want to ensure that I keep all my custom settings. Is that possible? Or should I just copy those settings out to a new file and then replace them in the updated quickstart.py file after the upgrade?

Thanks

**Comment by Benjaminlooi** [comment]
quickstart.py is one of the files listed to be ignored during git operations
see ".gitignore" file

And usually, i cd into Instapy and do `git pull origin master`

**Comment by deronsizemore** [comment]
Thanks. So I'm pretty inexperienced using git. I ended up just starting from scratch. I created a new directory for my InstaPy, cd into it and installed virtualenv and did `pip install git+https://github.com/timgrossmann/InstaPy.git`

That installs all of the packages necessary, correct? From there, what's the best approach for installing the .py files necessary to run the application, e.g., quickstart.py? I believe the last time (which was a while ago so I don't quite remember) I just downloaded the package as a .zip file and extracted it into the correct location into my virtual environment. I assume there's an easier way?

**Comment by deronsizemore** [comment]
Sorry... I think I've figured it out by throwing enough stuff at the wall! ;)

I did a git clone [repo url] and that worked for pulling everything in.

So next question (and hopefully final) is that if quickstart.py is in .gitignore so it's not updated, how should one go about updating it? Just manually I guess? I know with new releases, the quickstart.py changes to accommodate new features and such so it would need to be updated at some point?

**Comment by Benjaminlooi** [comment]
I suggest you try reading  [InstaPy/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md ](url)

best of luck

**Comment by deronsizemore** [comment]
Thanks

**Comment by Benjaminlooi** [comment]
I suggest you try reading [how to ubuntu](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md)

best of luck

**Comment by mikestan** [comment]
I have the same Q. So is the solution to do a new install each update? What happened to `git pull origin master`?

**Comment by deronsizemore** [comment]
@mikestan I think git pull origin master will likely work. I'm just inexperienced with using git and decided to do everything from scratch. So what I ended up doing was `pip install https://github.com/timgrossmann/InstaPy.git` after creating my virtualenv and then did `git clone https://github.com/timgrossmann/InstaPy.git` to pull in all the .py files. I assume if you wanted to do an update you could use `git pull https://github.com/timgrossmann/InstaPy.git master` and that should work? But again... I'm a novice with using git.
