### ISSUE TITLE
Session ended after first follow

### ISSUE THREAD

**Issue by jozefpis** [InstaPy/InstaPy#2767]
Hello,

in last 4 days i have issue, that follow function stop after first follow.
In general.log it looks like

INFO [2018-08-25 17:17:04] [account]  Session started!
INFO [2018-08-25 17:17:34] [account]  Logged in successfully!
INFO [2018-08-25 17:17:38] [account]  User 'dominikazakova' [1/5]
INFO [2018-08-25 17:17:48] [account]  Simulated follow : 1
INFO [2018-08-25 17:17:50] [account]  --> Followed b'dtb.crew'
INFO [2018-08-25 17:17:55] [account]  Session ended - 2018-08-25 17:17:55

thanks for any help

**Comment by aliirezaaa** [comment]
i think this issue related to this #2760

**Comment by jozefpis** [comment]
@aliirezaaa no, that lines is updated

**Comment by AvocadoStyle** [comment]
I have the same problem, this issue is not related to #2760

**Comment by AvocadoStyle** [comment]
Sorry for writing this again but some one solve this problem? I’ve tried anything...

**Comment by jozefpis** [comment]
@AvocadoStyle im waiting too, still not working

**Comment by AvocadoStyle** [comment]
I think its happening only for us, no one is disturbed from this bug except us @jozefpis

**Comment by gitpatrickhub** [comment]
Same problem on Raspberry Pi 3. After latest pull, no error is output to the console, but the bot does not perform the interact_user_followers (like, comment) it simply moves on to the next operation (in this case unfollow). This occurs immediately after the first simulated follow.  I can see that the scroll is working, but as soon as the simulated follow occurs the bot skips all remaining functions for the interact_user_followers method.

**Comment by jozefpis** [comment]
@AvocadoStyle @gitpatrickhub  Set `session.set_simulation(enabled=False)` helped me
(dont know if its good fix, or just hotfix)
