### ISSUE TITLE
Commenting stopped working

### ISSUE THREAD

**Issue by sas300** [InstaPy/InstaPy#277]
Weird problem Im wondering if anyone else has recently come across. The commenting functionality was previously working however I have noticed that it has stopped tonight. The output log shows the comment as normal however nothing is posted.

I can manually comment on pics (so its not like Ive been block or anything), and dropping some debug print commands in the comment_util.py indicates that the comment_input variable is not found (ie len(comment_input = 0)) 

From what I can tell the ('//input[@placeholder="Add a comment…"]') part is correct and hasnt been changed in the Instagram page html. Is there anything Im missing with this or is it affecting anyone else at the moment?

**Comment by sunnypatel165** [comment]
Could you post your quickstart?

**Comment by atomhax** [comment]
The bot could use sightly better error reporting while running. Basically in the version you're using if the bot isn't able to find the comment box (for whatever reason.. maybe the page took to long to load IDK), it skips trying to post the comment. Yet the terminal outputs as if it had commented. We should make it instead print that the comment failed.

Now I see in the current version of the comment_util.py the if statement that would have caused this behavior was actually removed. We'll just have to track if this becomes an issue for a large amount of people.

**Comment by amitbend** [comment]
same issue here

**Comment by madebybav** [comment]
Same issue here. 
Invalid Page: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@placeholder = "Add a comment…"]"}
  (Session info: chrome=58.0.3029.110)
  (Driver info: chromedriver=2.29.461591

**Comment by sas300** [comment]
Looks like its working for me now. Thanks!

**Comment by timgrossmann** [comment]
#288
