### ISSUE TITLE
Session logs in and out in a loop - selenium exception handling

### ISSUE THREAD

**Issue by FeriX64** [InstaPy/InstaPy#2773]
## Expected Behavior
Session should log in and start following and working
## Current Behavior
Instead it just logs in and follows one user and logs out due to selenium exception handling
## InstaPy configuration
On follow some pages' followers and unfollow "InstaPy" followed after 7 days.

The Sample output:
INFO [2018-08-26 12:29:26] [username]  Session started!
INFO [2018-08-26 12:29:58] [username]  Logged in successfully!
INFO [2018-08-26 12:30:02] [username]  User 'user1' [1/1]
INFO [2018-08-26 12:30:09] [username]  Simulated follow : 1
INFO [2018-08-26 12:30:12] [username]  --> Followed b'user1'
INFO [2018-08-26 12:30:15] [username]  Sleeping for 120 seconds for selenium exception handling | attempt number: 29

INFO [2018-08-26 12:32:15] [username]  Ending Session

INFO [2018-08-26 12:32:16] [username]  Session ended - 2018-08-26 12:32:16
INFO [2018-08-26 12:32:17] [username]  Session started!
INFO [2018-08-26 12:32:49] [username]  Logged in successfully!
INFO [2018-08-26 12:32:52] [username]  User 'user2' [1/1]
INFO [2018-08-26 12:33:06] [username]  Simulated follow : 1
INFO [2018-08-26 12:33:09] [username]  --> Followed b'user2'
INFO [2018-08-26 12:33:12] [username]  Sleeping for 120 seconds for selenium exception handling | attempt number: 30

INFO [2018-08-26 12:35:12] [username]  Ending Session

INFO [2018-08-26 12:35:12] [username]  Session ended - 2018-08-26 12:35:12
INFO [2018-08-26 12:35:14] [username]  Session started!
INFO [2018-08-26 12:35:45] [username]  Logged in successfully!
INFO [2018-08-26 12:35:48] [username]  User 'user3' [1/1]
INFO [2018-08-26 12:36:05] [username]  Simulated follow : 1
INFO [2018-08-26 12:36:08] [username]  --> Followed b'user3'
INFO [2018-08-26 12:36:12] [username]  Sleeping for 120 seconds for selenium exception handling | attempt number: 31

INFO [2018-08-26 12:38:12] [username]  Ending Session

**Comment by FeriX64** [comment]
It all started from this log:
INFO [2018-08-25 02:44:27] [username]  --> Ongoing Unfollow From InstaPy 23/50, now unfollowing: b'user3'
INFO [2018-08-25 02:44:27] [username]  	Removed '2018-08-18 01:24 ~ user3' from followedPool.csv file
INFO [2018-08-25 02:44:56] [username]  --> Ongoing Unfollow From InstaPy 24/50, now unfollowing: b'user4'
INFO [2018-08-25 02:44:56] [username]  	Removed '2018-08-16 16:14 ~ user4' from followedPool.csv file
INFO [2018-08-25 02:45:22] [username]  --> Ongoing Unfollow From InstaPy 25/50, now unfollowing: b'user5'
INFO [2018-08-25 02:45:22] [username]  	Removed '2018-08-16 22:23 ~ user5' from followedPool.csv file
**ERROR [2018-08-25 02:46:03] [username]  --> Unfollow error with b'user6', maybe no longer exists...
ERROR [2018-08-25 02:46:03] [username]  Unfollow loop error:  Message: unknown error: Cannot read property 'activity_counts' of undefined
  (Session info: headless chrome=68.0.3440.84)
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 3.10.0-862.9.1.el7.x86_64 x86_64)**


INFO [2018-08-25 02:46:03] [username]  --> Total people unfollowed : 25

INFO [2018-08-25 02:46:03] [username]  Sleeping for 813.1764705882352 seconds between unfollow and follow (likers)

INFO [2018-08-25 02:59:37] [username]  User 'page1' [1/1]
INFO [2018-08-25 03:00:06] [username]  Sleeping for 120 seconds for selenium exception handling | attempt number: 1

INFO [2018-08-25 03:02:06] [username]  Ending Session

INFO [2018-08-25 03:02:06] [username]  Session ended - 2018-08-25 03:02:06
INFO [2018-08-25 03:02:08] [username]  Session started!
INFO [2018-08-25 03:02:39] [username]  Logged in successfully!
INFO [2018-08-25 03:02:42] [username]  User 'page2' [1/1]
INFO [2018-08-25 03:03:11] [username]  Sleeping for 120 seconds for selenium exception handling | attempt number: 2

INFO [2018-08-25 03:05:11] [username]  Ending Session

INFO [2018-08-25 03:05:11] [username]  Session ended - 2018-08-25 03:05:11
INFO [2018-08-25 03:05:13] [username]  Session started!
INFO [2018-08-25 03:05:44] [username]  Logged in successfully!
INFO [2018-08-25 03:05:47] [username]  User 'page3' [1/1]
INFO [2018-08-25 03:06:16] [username]  Sleeping for 120 seconds for selenium exception handling | attempt number: 3

INFO [2018-08-25 03:08:16] [username]  Ending Session

**Comment by samihamine** [comment]
Same problem #2774
