### ISSUE TITLE
InstaPy-Light (fork)

### ISSUE THREAD

**Issue by converge** [InstaPy/InstaPy#2777]
Hey guys!

Just released a light version of InstaPy:
https://github.com/converge/InstaPy-Light

InstaPy is amazing, and it's growing fast, but I prefer a minimalism approach and that's the only reason I forked it.

@timgrossmann , I don't know if this is the right place to share it, feel free to close it if isn't the right place.

**Comment by timgrossmann** [comment]
@converge Absolutely the right place to share this.

I think we should also put this information in the README so people can quickly find it.
Do you think you could find the right spot to put this information and PR this to InstaPy? 

Thank you very much

**Comment by joanroig** [comment]
I think this will be cool for low-power devices like my Raspberry :)

**Comment by Areahints** [comment]
would it still require the same install process as before?

**Comment by CTZNkjs** [comment]
very nice and clean

**Comment by converge** [comment]
@Areahints yes, but I'll add an easier way to install it in the future.

**Comment by timgrossmann** [comment]
@converge looking forward to this, maybe we can adapt this easier way to InstaPy itself.

**Comment by uluQulu** [comment]
🤩Wow

**Comment by converge** [comment]
just released version 0.1

https://github.com/converge/InstaPy-Light
