### ISSUE TITLE
Not unfollowing all users followed by InstaPy

### ISSUE THREAD

**Issue by EliotHyenne** [InstaPy/InstaPy#2778]
In my session, I follow 36 people and unfollow 45 to make sure they're all unfollowed. Unfortunately, only maybe 50-65% of the users followed by InstaPy are unfollowed.

This is my unfollow code:
`session.unfollow_users(amount=45, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=None, sleep_delay=90)`

## Expected Behavior

Unfollow all users that were followed by InstaPy.

## Current Behavior

Unfollowing only a fraction of the users followed by InstaPy during the session.

Please let me know if any more details need to be given.

**Comment by Benjaminlooi** [comment]
Could be because they changed their username

**Comment by EliotHyenne** [comment]
I don't think so, I'm only following celebrities

**Comment by rodriguesprobr** [comment]
Same here. The unfollowing routine speed was severe impact by some updates.

**Comment by EliotHyenne** [comment]
I don’t think it’s necessarily the speed, it’s just that it doesn’t unfollow all users followed by InstaPy like it was told to.

This causes my following count to keep rising, unless I manually unfollow, which is what a bot should do for me.

**Comment by rodriguesprobr** [comment]
I'll investigate my logs to see what's going on. I feel the same effect here.

**Comment by sionking** [comment]
you might got unfollow blocked, you removed the user from the list, but neverr unfollwoed him.

**Comment by EliotHyenne** [comment]
I don't think so, I can unfollow manually just fine

**Comment by EliotHyenne** [comment]
Because my unfollow_after is set to None, it won't unfollow:

`Total 213 users available to unfollow  ~didn't pass unfollow_after: 0`

Not sure why

**Comment by EliotHyenne** [comment]
I get this here:
`--> Cannot Unfollow From InstaPy 20, maybe b'tripadvisor' was unfollowed before...
Removed '2018-08-27 23:14 ~ tripadvisor ~ 248181152' from followedPool.csv file
Removed '2018-08-28 01:12 ~ tripadvisor ~ 248181152' from followedPool.csv file`

**Comment by CharlesCCC** [comment]
@EliotHyenne next time run, keep you runs on the browser seem what is actually doing (along with the log)
