### ISSUE TITLE
Install scripts

### ISSUE THREAD

**Issue by binhonglee** [InstaPy/InstaPy#278]
There seems to have no explanation and documentations as to their existence and what they do. Should they be included in the README.md as part of the instructions? Or just removed? I felt like its only being brought up in the issues when someone face a problem with installation but no one else really knows why they were there.

**Comment by timgrossmann** [comment]
@binhonglee Well, you're actually right.

Could you add a section in the Readme and docs/index.md for that, please?

I thought the people who'd use them know what they do.
Also we could refactor them to live in a separate scripts folder

**Comment by binhonglee** [comment]
I think they are already in a separate scripts folder but yea, I can definitely word on adding a section to the README.md and docs/index.md

**Comment by timgrossmann** [comment]
#279
