### ISSUE TITLE
Add a follow based off of active users option

### ISSUE THREAD

**Issue by kylehar222** [InstaPy/InstaPy#2781]
Hi I am unsure if this is the correct area to write this, but I would like to make an added suggestion: 

A session.follow_user_active_followers function that would follow the designated amount of users based off of a a list of logins, but would only follow followers of that user if the followers account had posted a picture in the past X amount of time.  This way it is ensured that 'dead' accounts are not being followed.

**Comment by CharlesCCC** [comment]
i believe this feature already existed, please heading to the main page and read the list of feature.
