### ISSUE TITLE
Empty line in followedPool

### ISSUE THREAD

**Issue by dule91sd** [InstaPy/InstaPy#2789]
## Expected Behavior

> 2018-08-19 10:25 ~ tomic__lana_
> 2018-08-19 12:07 ~ lana.s.1
> 2018-08-19 12:22 ~ _milovanovicka_l
> 

## Current Behavior

> 2018-08-19 10:25 ~ tomic__lana_
> 
> 2018-08-19 12:07 ~ lana.s.1
> 
> 2018-08-19 12:22 ~ _milovanovicka_l
> 

## Possible Solution (optional)

Now instapy saving followed users in followedpool with empty line between them but
it has be saved without empty line.
Therefore unfollowing (instapyfollowed=True) not working.
Could somebody help me to remove in code where adding this empty line?

**Comment by CharlesCCC** [comment]
uhh, first time seeing this, are you having latest version ?

**Comment by sionking** [comment]
@CharlesCCC did you made changes in this no?

**Comment by CharlesCCC** [comment]
@sionking yea, there are some change to it, but I'm not able to reproduce the issue locally and not seeing anybody else having the same issue.

**Comment by dule91sd** [comment]
@CharlesCCC 
I updated InstaPy on my RaspberryPi and I got following:
Followedpool looks like:
> 2018-08-29 21:50 ~ sara_mikec
>  ~ 2902958902
> 2018-08-29 21:51 ~ _elmin_kall
>  ~ 5910589660

When I run unfollowing (OnlyInstapyFollowed = True) I got following:

>INFO [2018-08-29 22:10:00] []  --> Ongoing Unfollow From InstaPy 1/26, now unfollowing: sara_mikec
> INFO [2018-08-29 22:10:00] []  	Removed '2018-08-29 21:50 ~ sara_mikec
> ' from followedPool.csv file
> 
> ERROR [2018-08-29 22:10:43] []  --> Unfollow error with 2902958902, maybe no longer exists....
> ERROR [2018-08-29 22:10:43] []  --> Unfollow error with 2902958902, maybe username has changed or he/she blocked you...
> ERROR [2018-08-29 22:10:43] []  --> Unfollow error with 2902958902, maybe no longer exists...
> INFO [2018-08-29 22:11:00] []  --> Ongoing Unfollow From InstaPy 2/26, now unfollowing: _elmin_kall
> INFO [2018-08-29 22:11:00] []  	Removed '2018-08-29 21:51 ~ _elmin_kall
> ' from followedPool.csv file
> 
> ERROR [2018-08-29 22:11:46] []  --> Unfollow error with 5910589660, maybe no longer exists....
> ERROR [2018-08-29 22:11:46] []  --> Unfollow error with 5910589660, maybe username has changed or he/she blocked you...
> ERROR [2018-08-29 22:11:46] []  --> Unfollow error with 5910589660, maybe no longer exists...

Now I don't understand what is happening. It's writing some numbers that not make sense. This numbers are totally unnecessary.
Could you somehow help me to solve this issue?
Thank you in advance.

**Comment by CharlesCCC** [comment]
@dule91sd  those number are not random, those are userid for the followed user. the reason why those get logged is in case if the user changed username, you might not able to unfollow them based off "username". so it will fall back to use the userid to trace it back to the user. 

when I test it, it should log it as one line like this 
```
2018-08-29 21:50 ~ sara_mikec ~ 2902958902
2018-08-29 21:51 ~ _elmin_kall ~ 5910589660
``
I really wasn't sure why there are additional line break under your environment. Are you able to run it on your local computer, instead of the Rasperry Pi ? because I want to see if that is isolated problem to the Pi or not.

**Comment by dule91sd** [comment]
@CharlesCCC 
I tried right now on win10 platform and it seems that is the same:

> 2018-08-29 23:06 ~ sara_mikec
>  ~ 2902958902,
> 2018-08-29 23:06 ~ _elmin_kall
>  ~ 5910589660,

**Comment by CharlesCCC** [comment]
can you please upload your raw followedpool.csv here ? thank you.

**Comment by sionking** [comment]
@dule91sd I think you have a broken merge ~

**Comment by dule91sd** [comment]
@CharlesCCC 
FollowedPool from win10 platform:
[followedPool.zip](https://github.com/timgrossmann/InstaPy/files/2336719/followedPool.zip)
I Opened this file in Excel and in the PyCharm and it's the same like in LibreOffice(raspberryPi)
@sionking 
Can you help to solve this issue if you have any idea how?

**Comment by CharlesCCC** [comment]
@dule91sd I think @sionking had a point. consider you are the only person reported this issue, it is high likelihood you got some bad merge. 

one thing you can try is to pull down the latest version of instapy to a separate folder and run it through there.

**Comment by dule91sd** [comment]
@CharlesCCC @sionking 
Wait wait I think that you get me to the point.
I'm reading users from txt file like this:

> sara_mikec
> elmin_kall

And there is aditional "/n" and when it's writing it's writing with "/n" which is a problem.
Do you know how I can trim this "/n" on the and of string or how to read this txt file in array without "/n"?
Thank you guys, you've helped me a lot.

**Comment by CharlesCCC** [comment]
@dule91sd I'm glad you figured out the problem, I hate to say this, but your questions very generic, a quick google search should help you 👍
