### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2793]
@uluQulu 
Hi, even after the fix you helped me with I get this sometimes.
Do you know why? and if it can be fixed in the same way you fixed the other?

WARNING [2018-08-29 09:29:27] [xxx]  Could not locate Chrome: Message: timeout
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-33-generic x86_64)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-08-29 09:29:27] [xxx]  Session ended - 2018-08-29 09:29:27
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/instapy/util.py", line 602, in web_adress_navigator
    browser.get(link)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-33-generic x86_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/5b5ee8569afadd001464d368.py", line 24, in <module>
    session.follow_user_followers(['mikcosentino','dariovignali','marcomontemagno','franzdiolosa'], amount=50, randomize=False, interact=True)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 2101, in follow_user_followers
    followed = self.follow_by_list(person, self.follow_times, sleep_delay, interact)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 757, in follow_by_list
    self.user_interact_media)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 1639, in interact_by_users
    self.logger)
  File "/home/fredrik/InstaPy/instapy/like_util.py", line 407, in check_link
    web_adress_navigator(browser, post_link)
  File "/home/fredrik/InstaPy/instapy/util.py", line 609, in web_adress_navigator
    str(link).encode("utf-8"), str(exc).encode("utf-8")))
selenium.common.exceptions.TimeoutException: Message: Retried 7 times to GET 'b'https://www.instagram.com/p/BXyCAcvAcmJ/?taken-by=x'' webpage but failed out of a timeout!
        b'Message: timeout\n  (Session info: headless chrome=68.0.3440.106)\n  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-33-generic x86_64)\n'

**Comment by fgisslen** [comment]
Now I actually saw that it is that error but it timed out 7 times. hmm

**Comment by uluQulu** [comment]
@fgisslen 
How often do you get timeouts?

**Comment by fgisslen** [comment]
@uluQulu 
I run on proxy servers but they say that the problem isn't at them.
once a day maybe. Running some accounts and maybe one gets it.

**Comment by uluQulu** [comment]
@fgisslen
Right it is directly related to the connection health.
Try to increase the page delay while instantiating InstaPy at your **quickstart** script.
```python
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True,
                  page_delay=100)   # seconds
```
you can test with higher values, or maybe just `30` seconds may help (_currently it is `25`_), it is up to your connection health.

Try it for now and it if does not help, let me know.

---------

Cheers 😁
----------

**Comment by fgisslen** [comment]
@uluQulu 
because it's no problem with the network. I am running on 1000mbit/s .
I will try with 30 first.

**Comment by CharlesCCC** [comment]
try remove the proxy and run it.

**Comment by fgisslen** [comment]
@CharlesCCC I think that helps actually, can't try it though cause I have the server on an other place.

**Comment by uluQulu** [comment]
@fgisslen 
The connection health is different than speed, timeout is a matter of stability.
It can happen only some short period of time in your high-speed bandwith out of,
+ connection unstability 🤔
+ webdriver & web browser incompatibility (_always use newest **compatible** versions_)
+ selenium misbehavior (_always **update**_)
+ having browser cache filled in low memory 🤤
+ etc.

In any case it can be solved, try by the `page_delay` I told you, don't be scared of the longer amount. It will return once locates the requested element in the DOM or loads the page, it is an implicit wait.

-------

Cheers 😁
-------

**Comment by fgisslen** [comment]
@uluQulu okey, thanks!
Hope this works, I really appreciate your help! 

I tried to email you about an other thing.

**Comment by uluQulu** [comment]
@fgisslen 
I think I did not see 😟 it

**Comment by fgisslen** [comment]
@uluQulu what is your email adress?

**Comment by uluQulu** [comment]
@fgisslen 
It is the one in my profile page- `shahriyarguliyev@hotmail.com`

**Comment by fgisslen** [comment]
Tried to email again. @uluQulu

**Comment by uluQulu** [comment]
Hey @fgisslen it is received, both 🙋🏼‍♂️
>It's just Mail app in my Windows which marked them as Junk for some reasons I don't know of..

---------

Cheers 😁
-------

**Comment by fgisslen** [comment]
@uluQulu
Answered you again :)

**Comment by uluQulu** [comment]
@fgisslen 
Yes I saw 😁
I will write back soon 🤝🏼

Just prepared a new solution to ongoing problem with some users- a new generic **explicit wait** function which can also help to solve your issues with lots of timeouts **completely**.

--------

Cheers 😁
------

**Comment by jeremycjang** [comment]
@uluQulu Has the generic explicit wait been rolled out to the main branch? Currently running into the timeout issue too, but trying to increase ```page_delay``` to solve it right now 😅

**Comment by jeremycjang** [comment]
This issue appears to have been fixed in the latest version of the master branch, at least for me!

**Comment by rabb1t0x21** [comment]
For me this happens when I configure my script to build a large list of people to follow from someone's photo likes. I was trying to pull a list of up to 2000 names to follow from the likers of another user's photos, and the it would crash with this error at about 1100 likes:

('Scrolling down... ', 859, '->', 871, ' / ', 2000)
('Scrolling down... ', 871, '->', 883, ' / ', 2000)
('Scrolling down... ', 883, '->', 895, ' / ', 2000)
('Scrolling down... ', 895, '->', 907, ' / ', 2000)
('Scrolling down... ', 907, '->', 919, ' / ', 2000)
('Scrolling down... ', 919, '->', 931, ' / ', 2000)
('Scrolling down... ', 931, '->', 943, ' / ', 2000)
('Scrolling down... ', 943, '->', 955, ' / ', 2000)
('Scrolling down... ', 955, '->', 967, ' / ', 2000)
('Scrolling down... ', 967, '->', 979, ' / ', 2000)
('Scrolling down... ', 979, '->', 991, ' / ', 2000)
('Scrolling down... ', 991, '->', 1003, ' / ', 2000)
('Scrolling down... ', 1003, '->', 1015, ' / ', 2000)
('Scrolling down... ', 1015, '->', 1027, ' / ', 2000)
('Scrolling down... ', 1027, '->', 1039, ' / ', 2000)
Some problem occred!
	Message: timeout
  (Session info: headless chrome=65.0.3325.181

Going to decrease this number and see if it stops crashing.

**Comment by finedesignz** [comment]
I am having this issue with the latest version... the `page_delay` fix is not working for me... any other suggestions?

**Comment by fblasco1** [comment]
I am having the same problem that @finedesignz. I am running the bot locally with instapy.io, if i deploy instapy on heroku will this improve ?
