### ISSUE TITLE
Unfollow only that doesn't follow back (Issue) 

### ISSUE THREAD

**Issue by HCWcoder** [InstaPy/InstaPy#2796]
## Expected Behavior

To only unfollow the ones that is not following back
## Current Behavior
Randomly unfollowing people that does follow back
## InstaPy configuration

session.unfollow_users(amount=126, nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)

**Comment by sionking** [comment]
Are you sure ?
You should print the followers and following list captured and compare.
