### ISSUE TITLE
Random error while interact_user_followers

### ISSUE THREAD

**Issue by RafNadler** [InstaPy/InstaPy#2799]
## Expected Behavior
I am trying to follow specific users' followers and like a few of their posts each time. Super simple routine that worked great until now.
## Current Behavior

It is odd, it may work for a few follows and then unexpectedly it crashes and I can't pinpoint why. I ran it with firefox and chrome with the same results. It really crashes at various times. Sometimes right away, sometimes after following 1 person, smetimes after 10. Can't understand why.
I had cleaned up the logs for the people I had previously unfollowed, and also updated to the lastest version of Instapy.

Here is what I see:

Traceback (most recent call last):
  File "followlike.py", line 45, in <module>
    session.interact_user_followers(['user1',user2', 'user3'], amount=5, randomize=True)
  File "C:\XXXX\InstaPy\instapy\instapy.py", line 1816, in interact_user_followers
    self.logfolder)
  File "C:\XXXX\instapy\unfollow_util.py", line 924, in get_given_user_followers
    channel, logger, logfolder)
  File "C:\XXXX\instapy\unfollow_util.py", line 712, in get_users_through_dialog
    quick_username = dialog_username_extractor(quick_button)
  File "C:\XXXX\instapy\unfollow_util.py", line 760, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "C:\XXXX\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "C:\XXXX\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\XXXX\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\XXXX\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17134 x86_64)

######################################################################
Here is my config:
##
```
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = 'XXXXX'
insta_password = 'XXXXX'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  #use_firefox=True,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=None,
				  delimit_by_numbers=True,
				   max_followers=200000,
				    max_following=None,
				     min_followers=None,
				      min_following=10)
    session.set_do_follow(enabled=True, percentage=100)
    session.set_do_like(enabled=True, percentage=100)
    session.set_do_comment(enabled=False, percentage=80)
    # actions
    i = 0
    while (i < 6):
        session.set_user_interact(amount=3, randomize=True, percentage=70, media='Photo')
        session.interact_user_followers(['user1','user2', 'user3'], amount=5, randomize=True)
        i = i + 1
    

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

```
##################################################

**Comment by payca** [comment]
same here

**Comment by CharlesCCC** [comment]
this is a duplicate with #2745 close this issue for now
