### ISSUE TITLE
Going to follow top 50 users. error

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2800]
@uluQulu new error of some sort.

INFO [2018-08-30 09:12:00] [xxx]  Going to follow top 50 users.

INFO [2018-08-30 09:12:01] [xxx]  >>> self aborting prevented
INFO [2018-08-30 09:12:05] [xxx]  --> xxx instagram account is opened...
INFO [2018-08-30 09:12:15] [xxx]  ---> Now following: xxx

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-08-30 09:12:16] [xxx]  Session ended - 2018-08-30 09:12:16
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/5b86fc386c927700141ddfc6.py", line 29, in <module>
    session.follow_commenters(['x','xx','xx','xx','xx','xx','xxx','xxx','xxx'], amount=50, daysold=365,max_pic = 100, sleep_delay=600, interact=True)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 608, in follow_commenters
    followed = self.follow_by_list(commenter, self.follow_times, sleep_delay, interact)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 737, in follow_by_list
    self.logfolder)
  File "/home/fredrik/InstaPy/instapy/unfollow_util.py", line 615, in follow_given_user
    userid = browser.execute_script("return window._sharedData.entry_data.ProfilePage[0].graphql.user.id")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 635, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property '0' of undefined
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-33-generic x86_64)

**Comment by uluQulu** [comment]
@fgisslen 
It and many other weakly handled situations are covered in my PR.
I recommend you to use it for the latest solutions by me.
>Just download my fork and put your quickstart script into it, everything else is the same.
You should also `install` plyer module from pip.

If you wonder, it happened out of temporary outage while getting the `userid` through **grapqhl** in the `follow_given_user` definition at **unfollow_util.py** file.
In my PR it is using a generic `find_user_id()` function which reloads the page in case of it is undefined and etc.



--------------

Cheers 😁
------

**Comment by fgisslen** [comment]
@uluQulu 

Do you know when your PR will be merged?

Btw. I answered your email.

**Comment by uluQulu** [comment]
@fgisslen 
Because of it is my PR I cannot tell when, it is up to the community 🙂
Will write back now. 🤝🏼

------

Cheers 😁
-------

**Comment by sionking** [comment]
@uluQulu thank you for contributing !
