### ISSUE TITLE
interact_user_followers sleep delay

### ISSUE THREAD

**Issue by jtrieuDev** [InstaPy/InstaPy#2801]
Hi,

I recently got blocked because I like too much photos.
"
session.set_user_interact(amount=5, randomize=True, percentage=100, media='Photo')
session.set_do_like(enabled=True, percentage=80)
session.interact_user_followers(['username'], amount=1000, randomize=False)
"

I think it can be a good idea to add a sleep delay

**Comment by nosecretz** [comment]
@jtrieuDev  you run 24 hours? or its just a few hours?

**Comment by forgottensword** [comment]
@jtrieuDev  yeah.. it's a notable point. And also if you set the session to not follow users, Instagram usually bans the user to interact further. I think we need to develop another separate mod for interactions with more delays without having to follow and unfollow a lot of users.

**Comment by jtrieuDev** [comment]
I did it for like 12 hours
