### ISSUE TITLE
Sorry, an error occured: local variable 'passed_time' referenced before assignment

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2802]
@uluQulu Any suggestions?

INFO [2018-08-30 07:31:03] [xxx]  Post 1  |  Likers: found 21, catched 12
INFO [2018-08-30 07:31:16] [xxx]  Post 2  |  Likers: found 38, catched 12
INFO [2018-08-30 07:31:31] [xxx]  Post 3  |  Likers: found 33, catched 24
INFO [2018-08-30 07:31:47] [xxx]  Post 4  |  Likers: found 40, catched 24
INFO [2018-08-30 07:32:00] [xxx]  Post 5  |  Likers: found 59, catched 12
INFO [2018-08-30 07:32:02] [xxx]  Gathered total of 63 unique active followers from the latest 5 posts in 1 minutes and 8 seconds

_______________________________________________________________________
INFO [2018-08-30 07:32:02] [xxx]  Starting to unfollow users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-08-30 07:32:07] [xxx]  Unfollowing the users who do not follow back

INFO [2018-08-30 07:32:07] [xxx]  Retrieving live `Followers` data of xxx at "full" range

INFO [2018-08-30 07:33:26] [xxx]  Unable to get `Followers` data:
        b'Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}\n  (Session info: headless chrome=68.0.3440.106)\n  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-33-generic x86_64)\n'

ERROR [2018-08-30 07:33:26] [xxx]  Sorry, an error occured: local variable 'passed_time' referenced before assignment

**Comment by uluQulu** [comment]
Hey @fgisslen 
`INFO [2018-08-30 07:31:16] [xxx] Post 2 | Likers: found 38, catched 12`
catching lots of `12`s means you have most probably burnt requests to the server.
Or, if you always catch lesser amounts than found then it means there is a problem
Either it is in  your side
+ weak connetion [unhealthy, unstable, laggy, etc. that causes slowers pageload] 
+ memory issue [either browser or machine]
+ etc.

OR there is a problem in the scrollers' engine internally.

_I wrote that particular part and it is a smart scroller. It means it scrolls down until hits the bottom - it auto detects it itself and stops scrolling and continues with the next._

Having said it, the second problem seems is retrieving Followers data through graphql queries.
Again smells of a request burnt to the server that it does not allow any more.

I think if you start to use Quota Supervisor, you can simply add a daily and hourly server calls peaks, such as `peak_server_calls = (450, 4900)` and add hourly server calls to sleep. Then you will less likely get similar misbehaviours.

That `UnboundLocalError`- referencing `passed_time` before assignment is not the part of your issue, it is just a bug I forgot to handle in relationship tools. See its fix in here: https://github.com/uluQulu/InstaPy/commit/c66144958378f01521fa361d87ec76d8a97e2ba5.

--------

Cheers 😁
-------

**Comment by fgisslen** [comment]
@uluQulu 
have you answered my email? :)
