### ISSUE TITLE
Have  Instagram learned how to identify Instapy?

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#2803]
It is really interesting. For the last 4 days I see the following behaviour.

1. Whenever I am under home wifi on my mobile - I can follow as much as I want.

2. Whenever I launch Instapy from under the same wifi - after the first follow attempt from the script, follow is blocked. And follow is blocked on the mobile as well.

3. I restart router - it changes IP. FOllow is unblocked on the mobile from under the wifi again (follow 1-2 people).

4. Run the Instapy - the first follow, does not go through. Try from the mobile from under the same network - blocked.

Etc. Etc. Tried in different variations, giving it couple days of rest, etc. But basically it is AS IF Instagram now knows when browser version is following, AND banning it as soon as... 

Anyone experiencing this? Thoughts / advice?

**Comment by CharlesCCC** [comment]
can you please share your full config

**Comment by Tachenz** [comment]
Of course:

from instapy import InstaPy
import os
session = InstaPy(username='blabla', password='wkji3298kjfkj329')
session.login()
session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
session.set_relationship_bounds (enabled=True, potency_ratio=None, delimit_by_numbers=True, max_followers=3000, max_following=900, min_followers=50, min_following=50)
session.set_simulation(enabled=False)
session.set_do_like(enabled=True, percentage=100)
session.set_ignore_users(['myata.group'])
session.set_do_comment(enabled=True, percentage=35)
session.set_do_follow(enabled=True, percentage=40, times=1)
session.set_comments(...)
session.interact_user_followers(..)
session.end()

**Comment by Tachenz** [comment]
Oh - how did I close it is there a way to reopen?? :) Sorry - farfinger!


PS I also have custom delay after each like to sleep for a minute, so it does not really follow more than 3-4 people an hour at this point.


Also this account has been successfully instapying for more than a year now...

**Comment by CharlesCCC** [comment]
I can't tell how many interaction(like, follow,comment) you will give on each run.

is very like your got soft-banned from instagram, you should be recover by reduce the amount or stop it for couple days.

**Comment by Tachenz** [comment]
Jeez mate, you did not read the first post, did you? :D

**Comment by CharlesCCC** [comment]
@Tachenz I read it fully, that is the reason I call it `soft-banned` I have seem so many instance like this in here.

**Comment by Tachenz** [comment]
The main worrisome fact - is that this "soft ban" is just for the PC. From the phone (both PC AND PHONE are under same wifi network, e.g. got same IP) - follow works fine.  This is not normal softban behaviour...

**Comment by CharlesCCC** [comment]
@Tachenz yes, that is the reason it called `soft-banned` it detect you are using PC automation/bot. 
if you got `hard-banned` you won't able to do anything at all.   As if you still don't believe this is not a normal softban, please share your insight what a normal softban is ?

**Comment by Tachenz** [comment]
Normal soft-ban is when you can not follow, REGARDLESS of the device. Be that from your phone, or computer (assuming they all got the same IP address). In this one - i CAN follow from my phone, but CAN'T from Instapy.

**Comment by ghost** [comment]
@Tachenz have you tryied with a residential proxy ? for example [luminati](https://luminati.io/?affiliate=ref_5b43dfdfeebad2ae1d7ff104) ?

**Comment by CharlesCCC** [comment]
@Tachenz okay, I have seem both happing before, the most common scenario is the one i mentioned earlier. regardless which scenario is, the solution won't change, which is decrease engagement amount.

**Comment by Tachenz** [comment]
@ilmetu Thank you - I have not, I might. But I was just keeping my router off for an hour - that changes the IP... Still banned after 3-4 follows (3-4 only!)  I will give proxy a shot
