### ISSUE TITLE
HELP: Chrome failed to start: exited abnormally  - Linux

### ISSUE THREAD

**Issue by andifds** [InstaPy/InstaPy#2805]
Followed all instruction of install on Ubuntu and on a Raspberry Pi, but still getting error with chromedriver in both systems. First time i got this (after updating clone), after few months using it. 

Got chromedriver from locations referred on How-To's and also directly from http://chromedriver.chromium.org/

If I try with Firefox, the script runs normally, but I want to use it headless.
## Expected Behavior
Start a session normally
## Current Behavior
Every time I try to get it start I receive this:

> ERROR [2018-08-30 16:32:58] [instagramusername]  Message: unknown error: Chrome failed to start: exited abnormally
>   (unknown error: DevToolsActivePort file doesn't exist)
>   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
>   (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-33-generic x86_64)
> Traceback (most recent call last):
>   File "/home/username/InstaPy/instapy/instapy.py", line 300, in set_selenium_local_session
>     chrome_options=chrome_options)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
>     desired_capabilities=desired_capabilities)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
>     self.start_session(desired_capabilities, browser_profile)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
>     response = self.execute(Command.NEW_SESSION, capabilities)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
>   (unknown error: DevToolsActivePort file doesn't exist)
>   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
>   (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-33-generic x86_64)
> 
> Traceback (most recent call last):
>   File "/home/username/InstaPy/instapy/instapy.py", line 300, in set_selenium_local_session
>     chrome_options=chrome_options)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
>     desired_capabilities=desired_capabilities)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
>     self.start_session(desired_capabilities, browser_profile)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
>     response = self.execute(Command.NEW_SESSION, capabilities)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
>   (unknown error: DevToolsActivePort file doesn't exist)
>   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
>   (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-33-generic x86_64)
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "quickstart.py", line 22, in <module>
>     multi_logs=True)
>   File "/home/username/InstaPy/instapy/instapy.py", line 193, in __init__
>     self.set_selenium_local_session()
>   File "/home/username/InstaPy/instapy/instapy.py", line 304, in set_selenium_local_session
>     Settings.chromedriver_location))
> instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/username/InstaPy/assets/chromedriver

**Comment by dule91sd** [comment]
Also I have the same problem but i don't know why.
Can anybody help us to solve this problem?
Thank you

**Comment by wizel10** [comment]
Same here. Did a clean install with same issue. Chrome failed to start (I can start chrome manually with no issues).

**Comment by celestinsoum** [comment]
Same here !

**Comment by thEpisode** [comment]
Guys follow this issue #2678

**Comment by melnikovic** [comment]
This problem still exist, atleast for me :)

**Comment by diegotorreslopez81** [comment]
Try to run instapy with Chrome in background:

`# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=**True**)`
