### ISSUE TITLE
Unfollowing really slowly

### ISSUE THREAD

**Issue by cryptobench** [InstaPy/InstaPy#2806]
Hey there, new user to this tool. 

I am currently using this setting `session.unfollow_users(amount=458, allFollowing=True, style="FIFO", unfollow_after=None, sleep_delay=1)`

And i've been running it for around 3 hours now, and so far it has only unfollowed around 400 people. Is this normal speed? It seems a bit slow to me, so is there any way to tweak it?

**Comment by CharlesCCC** [comment]
yes, there is limit on how many you can unfollow every 10 minutes/hour/day/.
