### ISSUE TITLE
Failed to load desired amount of users

### ISSUE THREAD

**Issue by FeriX64** [InstaPy/InstaPy#2811]
## Expected Behavior
Should load desired amount of users
## Current Behavior
only gets about 15 to 20 user to follow each time from someone's page

log file:
INFO [2018-08-29 20:24:55] [username]  User 'page1' [1/1]
INFO [2018-08-29 20:25:02] [username]  Failed to load desired amount of users
INFO [2018-08-29 20:25:02] [username]  Simulated follow : 1
INFO [2018-08-29 20:25:06] [username]  --> Followed b'user1'
INFO [2018-08-29 20:25:37] [username]  Grabbed 22 usernames from page1's `Followers` to do following.

## InstaPy configuration
session.follow_user_followers(user_to_follow,
                                              amount=100,
                                              randomize=True,
                                              sleep_delay=1200)

**Comment by feri0010** [comment]
This is the log file
INFO [2018-08-29 20:24:55] [pinghint]  User 'mia._.plays' [1/1]
INFO [2018-08-29 20:25:02] [pinghint]  Failed to load desired amount of users
INFO [2018-08-29 20:25:02] [pinghint]  Simulated follow : 1
INFO [2018-08-29 20:25:06] [pinghint]  --> Followed b'sonu_rajput_123'
INFO [2018-08-29 20:25:37] [pinghint]  Grabbed 22 usernames from mia._.plays's `Followers` to do following.

**Comment by A-S-C-I-I** [comment]
I have been having the same issue.

**Comment by Marichka310** [comment]
I am having the same issue too

**Comment by ceribbo** [comment]
Same issue

**Comment by A-S-C-I-I** [comment]
As a quick workaround, you can repeat your follow list.  It will only follow a few from each one on each pass, but will then make multiple passes.
