### ISSUE TITLE
Headless bot doesn't like nor follow but log file says it does

### ISSUE THREAD

**Issue by rvoets** [InstaPy/InstaPy#2813]
Hi guys, 

I've been running the bot on my macbook without any issues. Last week I moved everything to a server (digitalocean) in order to periodically run it using a crontab. The strange thing is, according to the log file on the server, everything remains the same. Posts are liked, users unfollowed, etc. However, if I check the insta app, then no likes nor follows have been performed.

I already tried to delete the cookie file (username_cookie.pkl) but this doesn't make any difference. Is there anything else I can try?

I'm now back to using my macbook again but obviously running the script on a server would be a way better option.

**Comment by sionking** [comment]
DO ip not working on instagram

**Comment by sionking** [comment]
proxy don't work with instagram anymore, maybe just to follow

**Comment by ghost** [comment]
@sionking what do you mean proxy don't work with instagram anymore ?
i am using proxies a lot and everything works fine.
i am using [luminati datacenter or residential proxies](https://luminati.io/?affiliate=ref_5b43dfdfeebad2ae1d7ff104)

do you experiencing any problem with other proxies ?

**Comment by rvoets** [comment]
So Instagram blocks IP addresses of Digital Ocean servers? That explains why the bot (like/follow) isn't working on my server. My unfollow script does seem to work though.

@ilmetu you're using a DO server in combination with a proxy?

**Comment by ghost** [comment]
no i didn't use digital ocean server , but if you use a proxy it doesn't matter .
and yes, digital ocean ip are blacklisted from instagram.

**Comment by rvoets** [comment]
It seems that the blacklisting only has influence on liking and following. Unfollowing works as normal.

Anyways thanks guys for the clarification.

**Comment by sionking** [comment]
@ilmetu soon the luminati proxy will be blackedlisted.
the only solution is to build your own proxy server with ISP address buying directly.

**Comment by ghost** [comment]
@sionking residential proxies in general cannot be banned.

**Comment by sionking** [comment]
you right but what if it get abused ? those "residantial" are not really belongs to homes, the owner is the proxy provider. can you show the https://whatismyipaddress.com/ of luminti? I want to know the ISP

**Comment by sionking** [comment]
BTW I used once "Instagram residntial Ip" from https://highproxies.com it was the wrost thing I made to the account. none of those ip can even do like to even very old account.

**Comment by ghost** [comment]
@sionking highproxies are very bad proxies ... 

[luminati](https://luminati.io/?affiliate=ref_5b43dfdfeebad2ae1d7ff104) ips residential belongs to homes ... and you can even choose the country, the city , and the ISP  and in case of mobile proxies you can even choose the Mobile Provider AS Vodafone or AT&T and so on ...

they are really awesome ...

**Comment by luquitared** [comment]
Use buyproxies.org

**Comment by sionking** [comment]
@ilmetu but you pay alot for gb, you need not to DL images, which is not a solution as it looks bot.
I but IP drictly from the ISP and built my own proxy server but it is a hasle.

**Comment by ghost** [comment]
@sionking what software do you use for the proxy server ?

**Comment by sionking** [comment]
@ilmetu pfsense/ checkpoint750/ ccproxy... 
BTW in my country https://luminati.io/?affiliate=ref_5b43dfdfeebad2ae1d7ff104 do have res proxies but only 512, it mean that IG maybe know about it.

**Comment by sionking** [comment]
@ilmetu so you use  firefox and disable images ?

**Comment by sionking** [comment]
@ilmetu can I contact you in any way ?
I want to start using luminati but not sure how and what is the correct configuration.
thanks.

**Comment by sionking** [comment]
@ilmetu How do you handle that the IP is always changing ?

**Comment by luquitared** [comment]
@sionking Hey man do you have a discord? my username is aneonl#9246. Contact me there and I can help you fix this.

**Comment by sionking** [comment]
@luquitared Hi ! where should I find you with this username slack ?
