### ISSUE TITLE
how to stop the bot?

### ISSUE THREAD

**Issue by Luisjanz** [InstaPy/InstaPy#2815]
how to stop the bot when i started it with "sudo python quickstart.py &"
?

**Comment by ghost** [comment]
it depends on the type of script you wrote , if is in a loop the bot will never close itself.
otherwise will cose when the session reach the end.

in any case you can kill the bot by using the kill command ex:

sudo kill "python quickstart.py"

give it a try , i am not sure :)

**Comment by Luisjanz** [comment]
dont work.

**Comment by rvoets** [comment]
You can look up the process ID of your python script using

`ps aux | grep python`

Write down the process ID and run 

`kill -9 <process id>`

**Comment by ghost** [comment]
kill all chromedriver processes with:

```
ps | grep chrome | awk '{print $1}' | xargs kill
```

**Comment by ghost** [comment]
sudo ps ax |grep quickstart

take the number to the left and:

sudo kill -9 NUMBER

**Comment by Luisjanz** [comment]
sudo kill -9 21582
kill: (21582): No such process

**Comment by jis0324** [comment]
Do you solve this problem?
I have same problem.
help me

**Comment by aryanh289** [comment]
turn the internet off

**Comment by jis0324** [comment]
hi, aryanh289!
thank you for your reply.
but I can't turn off the internet.
I must kill the process as remote.

**Comment by aryanh289** [comment]
sure no problem, but I stopped it by turning the internet off as I was running it on my personal laptop
