### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by thatc0der** [InstaPy/InstaPy#282]
Could you also include information about how to do this using Macs? To the setup tutorial?

**Comment by atomhax** [comment]
I've set it up on MacOS and Linux using the instructions on the github. MacOS is based on Unix. It should the the same instructions. Did you run into any errors/problems while following the instructions?

**Comment by thatc0der** [comment]
can't even enter wget commands listed on the page, most of the terminal commands for ubuntu there don't work, you also can't install deb files as such on mac.

**Comment by converge** [comment]
cd InstaPy
python setup.py install

**Comment by gitpatrickhub** [comment]
Trying to run this on a Mac using Python 3.6. Receive the following error;

 File "quickstart.py", line 14, in <module>
    InstaPy(username="xusername", password="password")\
TypeError: 'module' object is not callable

Any ideas?

confirmed setup.py install was successful. 

I modified __init__.py :

from instapy import InstaPy (removed the '.' in front of instapy, if I leave it in, I receive an error: mportError: No module named instapy)

**Comment by timgrossmann** [comment]
@gitpatrickhub Never touch the code.... 

This is not recommended...
> I modified init.py

Make sure the quickstart file is at the right place... You need the same folder structure as in the repo

**Comment by gitpatrickhub** [comment]
Ok, so I reverted the code back to original state. And I have verified the same file structure (screenshot below);

![image](https://user-images.githubusercontent.com/29474212/27287844-c7eeff8e-54b9-11e7-9825-5da84aea82f3.png)

Error below from executing the code with original __init__.py code;

Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/Applications/Python 3.6/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
ImportError: No module named instapy

**Comment by timgrossmann** [comment]
@gitpatrickhub That's weird, do you start the quickstart file with 
`python3 quickstart.py` ?

Did you install all the dependencies ?

**Comment by gitpatrickhub** [comment]
I was only using the command; python quickstart.py
but just tried it with python3 quickstart.py and same error.

The dependencies look to be the issue;

writing manifest file 'instagram_py.egg-info/SOURCES.txt'
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
reading manifest file 'instagram_py.egg-info/SOURCES.txt'
writing manifest file 'instagram_py.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.10-x86_64/egg
running install_lib
running build_py
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

Not sure what happened here. Any ideas?

**Comment by timgrossmann** [comment]
@gitpatrickhub Never've seen that...

Could you clone the repo to a different location and simply do:

```
cd InstaPy
python setup.py install
```

?

**Comment by gitpatrickhub** [comment]
Created a new directory "production" and executed the clone command on the git repo. Then executed the install (same errors see attached). Lastly ran the python quickstart.py (error now related to pyvirtualdisplay)

[terminal_v1.txt](https://github.com/timgrossmann/InstaPy/files/1085559/terminal_v1.txt)

**Comment by timgrossmann** [comment]
@gitpatrickhub `pip install pyvirtualdisplay`?

**Comment by gitpatrickhub** [comment]
Before I execute the command, what directory should I be executing it from? I had initially installed at the Python 3.6 directory. Should I execute from Python 3.6/production/InstaPy or Python 3.6/production or Python 3.6?

**Comment by timgrossmann** [comment]
@gitpatrickhub doesn't mind. Everywhere is fine

**Comment by gitpatrickhub** [comment]
Looks like it was installed correctly;

Dallass-MacBook-Air:InstaPy dallasdenver$ pip install pyvirtualdisplay
Requirement already satisfied: pyvirtualdisplay in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: EasyProcess in /usr/local/lib/python2.7/site-packages (from pyvirtualdisplay)

**Comment by timgrossmann** [comment]
@gitpatrickhub 

`pip3 install pyvirutaldisplay` of course this is not working if you install things for 2.7 but use 3 to execute the quickstart file 😉 

Let's see if this fixes things

**Comment by gitpatrickhub** [comment]
Doh! Ok, I think I need to revert to Python 2.7, as it doesn't appear that 3.6 is supported for pyvirtualdisplay

**Comment by timgrossmann** [comment]
@gitpatrickhub It is 😉
