### ISSUE TITLE
Docker Running 2 Accounts at the same time

### ISSUE THREAD

**Issue by c0d3x27** [InstaPy/InstaPy#2821]
is there a way to run 2 accounts at the same time using docker? from my understanding the only way is to clone this repo twice 1 repo for each accoun, first run `docker-compose up -d --build` and make your containers than stop it then modify `dock-allinone.yml`, `dock_compose.yml`, `docker_dev.yml`,  `docker-prod.yml`, `docker-swarm.yml` even making up a new port in `docker-swarm.yml` since the default (`5900`) will be taken by deafult `docker_quickstart.py` then run `docker-compose up -d --build` again. this way you will have 4 containers 2 for each account since 1 account make 2 containers. this is the only way? any help

**Comment by luquitared** [comment]
Just use this:
https://github.com/timgrossmann/InstaPy/blob/master/examples/multi-account.py

**Comment by c0d3x27** [comment]
and how ima gonna use it on docker?? that only work using the py filr not docker
