### ISSUE TITLE
 blacklist dictWrite error 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by redsector72** [InstaPy/InstaPy#2824]
I get this error every action.
I dont' really need the blacklist, but it is related to the campaign.

**Comment by sionking** [comment]
maybe related to latest update

**Comment by sionking** [comment]
in add_user_to_blacklist
change to this:
        with open('{}blacklist.csv'.format(logfolder), 'a+') as blacklist:
from this:
        with open('{}blacklist.csv'.format(logfolder), 'a+', encoding="utf-8") as blacklist:

I don't know why you getting this error due.

**Comment by redsector72** [comment]
HI @sionking is already like this (an update?)
But I still get the same message.
I have even deleted the blacklist.csv file and seems like it is not getting generate/written anymore.
I'm on a mac.

the full log line is
ERROR [2018-09-02 08:20:42] [Username]  blacklist dictWrite error 'encoding' is an invalid keyword argument for this function

**Comment by redsector72** [comment]
No news?

**Comment by jeremycjang** [comment]
@sionking  Encountering this issue as well and trying to read up more on the ```Dictwrite``` function. At first I thought it might be because the utf-8 string uses double ticks instead of single, but that didn't seem to fix it

https://docs.python.org/3.1/library/csv.html
>import csv
with open('some.csv', newline='', encoding='utf-8') as f:
    reader = csv.reader(f)
    for row in reader:
        print(row)

**Comment by jeremycjang** [comment]
@redsector72  In the interim, I've confirmed that you can fix it by removing ```encoding="utf-8"``` so your ``` add_user_to_blacklist'``` code should look like this:

```
 open('{}blacklist.csv'.format(logfolder), 'a+'
```
Hope that helps!

**Comment by timgrossmann** [comment]
#3107
