### ISSUE TITLE
Could not locate Chrome: Message: timeout

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#2825]
@uluQulu 
This timeout appeared today.

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-09-02 06:08:05] [xxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...

.....................................................................
INFO [2018-09-02 06:09:48] [xxx]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
WARNING [2018-09-02 06:20:37] [xxx]  Could not locate Chrome: Message: timeout
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-33-generic x86_64)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-09-02 06:20:37] [xxx]  Session ended - 2018-09-02 06:20:37
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/5b735342c1cf060014570afc.py", line 16, in <module>
    session.login()
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 364, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "/home/fredrik/InstaPy/instapy/print_log_writer.py", line 11, in log_follower_num
    browser.get('https://www.instagram.com/' + username)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-33-generic x86_64)

**Comment by uluQulu** [comment]
@fgisslen 
in **print_log_writer.py** file
**replace**
```python
browser.get('https://www.instagram.com/' + username)
```
**with**
```python
user_link = "https://www.instagram.com/{}".format(username)
web_address_navigator(browser, user_link)
```
_There are 2 of that line_.

`web_address_navigator()` will handle it.


----------

Cheers 😁
----------

**Comment by fgisslen** [comment]
@uluQulu thx,
Do I have to import web_address_navigator() and from where?

**Comment by uluQulu** [comment]
@fgisslen 
Yes yes.
```python
from .util import web_address_navigator
```

**Comment by fgisslen** [comment]
@uluQulu thank you mate
