### ISSUE TITLE
Question - optimisation likes requests

### ISSUE THREAD

**Issue by YannikFirre** [InstaPy/InstaPy#2827]
Hello,

I have an optimization proposal about the like feature.

If we run the script often and / or on weak hashtags, we quickly have images already liked.

If I'm not mistaken the script takes the list of the most recent posts, so we could add an option that would give the possibility to stop the script for the current hastags if they fall on a post already liked.

We would save time and requests.

What do you think ?

**Comment by Nocturnal-2** [comment]
I agree!

**Comment by sionking** [comment]
Simple imlementation, database the liks

**Comment by YannikFirre** [comment]
Or just stop the script when the returned post is already liked ^^ No need database ;-)

**Comment by sionking** [comment]
I have implemented both I need to PR

**Comment by YannikFirre** [comment]
Anyone have a opinion on this ? interesting feature?
