### ISSUE TITLE
How long does a 'soft ban' typically last?

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#2830]
I recently got InstaPy up and running on a DigitalOcean (DO) droplet and let a basic interaction script (similar to `quickstart.py`) run every 3 hours. While tweaking the parameters a bit, I accidentally input a set of fairly liberal parameters which resulted in ~200 likes and ~50 follows in a time duration of only ~1 hour on one of the iterations. This probably raised some red flags.

After this, I discovered that the likes were being attempted and reported as successful on my droplet (cloud server) process, but posts were not showing up as liked in the IG iOS app. After some research (#1519 among others), it seems that I've been 'soft banned'.

I can still successfully run the script from my laptop from my home IP, so it seems like the Digitalocean droplet IP specifically is flagged. I even tried starting from scratch on a new droplet, but it still did not work.

So, a couple of questions for the community:

1.) How long does a soft ban typically last?
2.) The soft ban seems to be associated with an IP. In the case of Digitalocean, are ALL Digitalocean IPs then red-flagged for a given account once a soft ban is issued?
3.) Will it be eventually possible to run on Digitalocean at some future point, or do I need to move to another cloud service?

Any advice on the topic would be appreciated.

**Comment by CharlesCCC** [comment]
1) couple days
2) consider they are static ip, the chances are most of them are blocked
3) home networks is highly recommend, consider it is not static ip for the most part.

**Comment by ghost** [comment]
Thanks, @CharlesCCC! I can see why a home network is probably less risky. After a couple (2-3) days though would you guess that it'd be possible to run on DO again?  As in, do they ever get un-blocked? I realize it's hard to say for sure, but any general idea?

**Comment by sionking** [comment]
NO DO

**Comment by sionking** [comment]
soft ban = 15 minutes~
long ban (with data center ips) 5 hours ~ and much faster (liking)

**Comment by samrap** [comment]
I switched from running locally at home to an automated DO droplet weeks ago and have had no issues so I don't think DO IPs are blacklisted. It is less likely any activity from me would be flagged though since my account is aged well (~ 5 years old).

**Comment by ghost** [comment]
Good to hear, @samrap. I'm waiting a little longer to try again on DO to let the smoke clear a bit first, but will report back when I do. I had somewhat accidentally allowed one automated session to interact very heavily, which I think triggered the ban in the first place. Whether or not the ban on my acct is permanent (from a DO IP) is now the question.

In the meantime I've been using InstaPy from home successfully, with a little tweaking of some functions in order to more carefully control the number of likes and follows per session, and keeping the like/follow rates within reasonable limits.

**Comment by imkimchi** [comment]
I have no issues with DO either.

**Comment by ghost** [comment]
Yep, as of today I can confirm it's not a DO issue
