### ISSUE TITLE
[Bug] Follow Dialog changed - Follow/Interact_user_followers/ing not working anymore

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#2831]
## Expected Behavior
Follow/Interact the followers of a specific account

## Current Behavior
Follow/Interact with suggested accounts instead of followers of given account
![whatsapp image 2018-09-02 at 09 33 15](https://user-images.githubusercontent.com/16529337/44957362-ca494f00-aed1-11e8-9a42-ee3bbdd5077b.jpeg)

Looks like they're currently doing an A/B-Test since I only see this in some accounts... 
Probably will deploy this to all the accounts soon.

**Comment by forgottensword** [comment]
Okay. I think that's what happening to me right now.


> Traceback (most recent call last):
>   File "E:\Temp\instabot\InstaPy-master\instapy\unfollow_util.py", line 100, in get_following_status
>     "//*[contains(text(), 'Requested')]")
>   File "C:\Users\RSR\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.p
> y", line 368, in find_element_by_xpath
>     return self.find_element(by=By.XPATH, value=xpath)
>   File "C:\Users\RSR\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.p
> y", line 858, in find_element
>     'value': value})['value']
>   File "C:\Users\RSR\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.p
> y", line 311, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\RSR\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandle
> r.py", line 237, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"x
> path","selector":"//*[contains(text(), 'Requested')]"}
>   (Session info: chrome=68.0.3440.106)
>   (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.3.9600 x8
> 6_64)
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\Temp\instabot\InstaPy-master\quickstart.py", line 116, in <module>
>     session.like_by_tags(['usa'], amount=204)
>   File "E:\Temp\instabot\InstaPy-master\instapy\instapy.py", line 1340, in like_by_tags
>     self.logfolder)
>   File "E:\Temp\instabot\InstaPy-master\instapy\unfollow_util.py", line 535, in follow_user
>     are_we_following, follow_button = get_following_status(browser, user_name, logger)
>   File "E:\Temp\instabot\InstaPy-master\instapy\unfollow_util.py", line 108, in get_following_status
>     raise Exception
> Exception
>

**Comment by sionking** [comment]
suggested are also good ! lol lucky me the a-b tests gets to my country 12 hours later.

**Comment by sionking** [comment]
Any work on that ?

**Comment by forgottensword** [comment]
Any Update Yet

**Comment by joanroig** [comment]
Same issue here but only when running multiple accounts at once.
