### ISSUE TITLE
Need help updating InstaPy virtual environment installations

### ISSUE THREAD

**Issue by jeremycjang** [InstaPy/InstaPy#2834]
Hi community! I tried researching a lot to figure this out, but I concede defeat. 

My current setup is 3 virtual environments made with the intention of running three InstaPy programs for different accounts at the same time.

Problem is when I try ```git pull origin master``` or ```pip install git+https://github.com/timgrossmann/InstaPy.git``` it does not actually fetch or update to the latest files despite what the terminal says. I need help fixing the configuration to actually pull updates.

Here's how I set them up:

1. Originally only had one InstaPy program installed in a folder called ```InstaPy``` following the [RaspberryPi Setup Guide](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Raspberry.md) . 
2. Created a virtualenv using
 ```
1. virtualenv venv1
2. source venv/bin/activate
3. pip install git+https://github.com/timgrossmann/InstaPy.git
```
then moved **all** my previous ```InstaPy``` files into the venv1 folder. 
3. Did ```virtualenv-clone venv1 venv2``` to make second virtual environment.
4.  Did ```virtualenv-clone venv1 venv3``` to make third virtual environment.

Could the installation be messed up since I first created the ```InstaPy``` folder using ```git clone https://github.com/timgrossmann/InstaPy.git``` and used to update it directly with ```git pull origin master```?

Any help would be appreciated!

**Comment by axlright** [comment]
@jeremycjang I may ping you back to get some help from you on how you've configured your setup. I'm trying to do the exact same thing. I'm not that smart, though.

>3 virtual environments made with the intention of running three InstaPy programs for different accounts at the same time.

I'm trying to do exactly this (maybe more than three). Anyway, I'll stay in touch with you if you don't mind.

Thanks!

**Comment by jeremycjang** [comment]
Ended up uninstalling all virtual environments and hard installing 3 InstaPy copies. Determined this effectively meets the same goal in less time with stability
