### ISSUE TITLE
24/7 Bot?

### ISSUE THREAD

**Issue by karlsruhegraphy** [InstaPy/InstaPy#2837]
Hello, I want to run the bot unlimeted. After an Hour the Bot says "Session Ended".

**Comment by dolnma** [comment]
Hello.
Just add to into #actions section this:
```
    for cycle in range(10):
        print("\n\nLOOP {}\n".format(cycle+1))
        # session.interact_user_followers(['worldcode', 'creativroom', 'thebeeest'], amount=100, randomize=True)
        time.sleep(50)   #take a 50 seconds of break after finishing the feature above
        session.unfollow_users(amount=20, sleep_delay=60 )
        time.sleep(30)   #take some more break after finishing unfollows
        session.like_by_tags(['webdesign', 'coding', 'frontend'], amount=30)
        time.sleep(60)
        session.follow_by_tags(['webdesign', 'coding', 'frontend'], amount=30)
```
where, `for cycle in range(10):` is number of cycles.

**Comment by karlsruhegraphy** [comment]
but this is not 24/7 if I use cycles ?

**Comment by karlsruhegraphy** [comment]
I have this error 💃 
:~/InstaPy$ python3 quickstart.py
  File "quickstart.py", line 41
    for cycle in range(10):
      ^
SyntaxError: invalid syntax

**Comment by sebblessing** [comment]
Please send your code. Thats an SyntaxError so probably you indent the code wrong

**Comment by karlsruhegraphy** [comment]
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = '--'
insta_password = '--'

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#   Settings.database_location = '/path/to/instapy.db'
#   Settings.chromedriver_location = '/path/to/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.21,
				  delimit_by_numbers=True,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])

    # actions
for cycle in range(10):
        print("\n\nLOOP {}\n".format(cycle+1))
        # session.interact_user_followers(['worldcode', 'creativroom', 'thebeeest'], amount=100, randomize=True)
        time.sleep(50)   #take a 50 seconds of break after finishing the feature above
        session.unfollow_users(amount=20, sleep_delay=60 )
        time.sleep(30)   #take some more break after finishing unfollows
        session.like_by_tags(['karlsruhe', 'karlsruhetweets', 'karlsruhefood'], amount=300)
        time.sleep(60)
        session.follow_by_tags(['karlsruhe', 'karlsruhetweets', 'karlsruhefood'], amount=30)
except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

**Comment by karlsruhegraphy** [comment]
[quickstart.zip](https://github.com/timgrossmann/InstaPy/files/2347516/quickstart.zip)

**Comment by karlsruhegraphy** [comment]
Here is my Quickstart.py

**Comment by dolnma** [comment]
@karlsruhegraphy 
ok, so if `Exception` (error) occurs, `finally:` will repeat `def` from the start:

```
def Job():
    try:
        session.login()

        # settings
        session.set_relationship_bounds(enabled=True,
                    potency_ratio=-1.21,
                    delimit_by_numbers=True,
                    max_followers=4590,
                        max_following=5555,
                        min_followers=45,
                        min_following=77)
        session.set_do_comment(True, percentage=20)
        session.set_do_follow(True, percentage=80)
        session.set_comments(['Great work!', 'So much fun!!', 'Nice!!' , 'Well done! :)', 'Good job! :))'])

        # actions
        for cycle in range(20):
            print("\n\nLOOP {}\n".format(cycle+1))
            # session.interact_user_followers(['worldcode', 'creativroom', 'thebeeest'], amount=100, randomize=True)
            time.sleep(50)   #take a 50 seconds of break after finishing the feature above
            # session.unfollow_users(amount=60, InstapyFollowed=(True), style="FIFO", sleep_delay=501)
            session.unfollow_users(amount=40, allFollowing=True, style="LIFO", unfollow_after=3*60*60, sleep_delay=450)
            time.sleep(30)   #take some more break after finishing unfollows
            session.like_by_tags(['webdesign', 'coding', 'frontend'], amount=20)
            # time.sleep(60)
            # session.follow_by_tags(['webdesign', 'coding', 'frontend'], amount=30)

    except Exception as exc:
        # if changes to IG layout, upload the file to help us locate the change
        if isinstance(exc, NoSuchElementException):
            file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
            with open(file_path, 'wb') as fp:
                fp.write(session.browser.page_source.encode('utf8'))
            print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
                '*' * 70, file_path))
        # full stacktrace when raising Github issue
        raise
        # pass

    finally:
        # end the bot session
        # session.end()
        Job()

Job()
```

**Comment by Luisjanz** [comment]
@karlsruhegraphy just posted your username and pw in the zip lol

**Comment by karlsruhegraphy** [comment]
this is not my real password :)

**Comment by Luisjanz** [comment]
it is/was

**Comment by karlsruhegraphy** [comment]
can you help me with the code?

**Comment by karlsruhegraphy** [comment]
Hello 😆

**Comment by karlsruhegraphy** [comment]
ubuntu@ip-172-31-43-2:~/InstaPy$ python3 quickstart.py
  File "quickstart.py", line 35
    session.set_do_comment(True, percentage=10)
    ^
whats that ? :D

**Comment by karlsruhegraphy** [comment]
Hello
