### ISSUE TITLE
Windows 7 Selenium

### ISSUE THREAD

**Issue by enosV** [InstaPy/InstaPy#2840]
## InstaPy configuration

I am having trouble getting the quickstart.py file to run. I'm guessing it's something to do with selenium not being properly configured? I do have it installed. And I followed all the instructions on the instapy for windows page on here.

Attached screen shot of the error I get

I'm on windows 7
![missingmodule](https://user-images.githubusercontent.com/24397196/45002980-152a9b80-af92-11e8-8b1b-19e566cc6cb3.PNG)

**Comment by davisonio** [comment]
Use python3

**Comment by enosvazquez** [comment]
Thanks for the reply but I am running python 3
![p3](https://user-images.githubusercontent.com/24397196/45069959-e2f96680-b083-11e8-841a-fff92b5aa2df.PNG)

**Comment by enosV** [comment]
Success!

Of course I had to run as admin. and install 2 more modules, requests and emoji. But after that... OH BABY!
