### ISSUE TITLE
What's the best spec for running 20+ instapy?

### ISSUE THREAD

**Issue by imkimchi** [InstaPy/InstaPy#2842]
I'm sorry this is not related to any issues from InstaPy but there's no community that I can discuss about this type of question.

I'm trying to run multiple instapy for multiple accounts but seems like clouds are not ideal option to run these programs, as It'd only need a couple memories, CPU and not a lot of storage. so I was planning to buy my own machine and run programs on it. Is there anyone who is currently running with multiple accounts at own server? any helps would be really appreciated 🙏

**Comment by sionking** [comment]
i7 8700K can run 50+ non headless.
0.5GB memory for aaccount.

**Comment by imkimchi** [comment]
@sionking what If I run them headless? there's no need to run without headless so

**Comment by sionking** [comment]
I don't know please update.

**Comment by imkimchi** [comment]
👌👌👌

**Comment by Mizi91** [comment]
How do you run multiple instapy on 1 machine? Just with multi_logs=True and mutliple quickstart.py files? @imkimchi @sionking

**Comment by sionking** [comment]
No I have a folder for each user.
