### ISSUE TITLE
Follow users followers not working anymore

### ISSUE THREAD

**Issue by luiztim** [InstaPy/InstaPy#2844]
Hi..

Instagram changed the account followers modal box and i guess this change makes InstaPy robot hung...

Check out the console message:

![bug](https://user-images.githubusercontent.com/35818924/45036526-1bbd1f80-b033-11e8-8d1e-f590342a45ce.png)

**Comment by victorsandovalmattar** [comment]
Same problem here

**Comment by Areahints** [comment]
+1

**Comment by booksix** [comment]
Same prob...

**Comment by luiztim** [comment]
It works... you need to download the last version of the project and compile it using this command:
pip install -r requirements.txt
