### ISSUE TITLE
Unfollow error

### ISSUE THREAD

**Issue by dpashutskii** [InstaPy/InstaPy#2846]
## Expected Behavior
Unfollow users

## Current Behavior
With unfollow, I always get the error

```
ERROR [2018-09-05 07:27:52] [<username>]  --> Unfollow error with b'ms.goggler', maybe username has changed or he/she blocked you...
ERROR [2018-09-05 07:27:52] [<username>]  --> Unfollow error with b'ms.goggler', maybe no longer exists...
ERROR [2018-09-05 07:27:52] [<username>]  --> Unfollow error with b'mik_michele_', maybe username has changed or he/she blocked you...
ERROR [2018-09-05 07:27:52] [<username>]  --> Unfollow error with b'mik_michele_', maybe no longer exists...
```
etc. for all userrs. Although unfollowing work with browser.

## InstaPy configuration
unfollow part:
```
    session.unfollow_users(
        amount=150,
        nonFollowers=True,
        style="RANDOM",
        unfollow_after=42*60*60,
        sleep_delay=655
    )
```

@uluQulu could you please help?

**Comment by underclass** [comment]
Same error here

`session.unfollow_users (amount=30,
                                InstapyFollowed=(True, "nonfollowers"),
                                style="FIFO",
                                sleep_delay=700,
                                unfollow_after=168*60*60)`

**Comment by underclass** [comment]
INFO [2018-09-05 20:25:03] []  Unfollowing the users you are following
ERROR [2018-09-05 20:25:30] []  Sorry, an error occured: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/following-sibling::div"}
  (Session info: headless chrome=68.0.3440.106)
  (Driver info: chromedriver=2.40.565386 (45a059dc425e08165f9a10324bd1380cc13ca363),platform=Mac OS X 10.13.6 x86_64)

**Comment by uluQulu** [comment]
@guar47 @underclass 
Both of those problems are solved in my PR, feel free to get it

------

Cheers 😁
---------

**Comment by dpashutskii** [comment]
@uluQulu Thanks, it indeed solved in new PR. Tested.
