### ISSUE TITLE
Unfollow all function is not working

### ISSUE THREAD

**Issue by spikeyhair** [InstaPy/InstaPy#2851]
I follow the example given in the readme file:
session.unfollow_users(amount=40, allFollowing=True, style="LIFO", unfollow_after=3*60*60, sleep_delay=450)

and I get this error:
Failed to load desired amount of users

Anyone facing this issue?

**Comment by spikeyhair** [comment]
It works after updating the unfollow_util.py. Thanks.

**Comment by Luisjanz** [comment]
How can i update it?i have the same problem
