### ISSUE TITLE
Help With Virtual Environments

### ISSUE THREAD

**Issue by axlright** [InstaPy/InstaPy#2853]
## Expected Behavior

Virtual environment to run when following

```
$ cd ~/Documents/Code/InstaPy/
$ source user-xxxxx/bin/activate
$ python user-xxxxx/script.py
```

## Current Behavior

Error that Chrome Driver isn't in the correct place:
`Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home` and many other errors following.

## Questions

1) To run multiple virtual environments with multiple InstaPy sessions at once, should I have one root install of InstaPy and all the virtual environments in that same directory?

2) Where should Chrome Driver go?

3) How are InstaPy updates handled - just update the one root install at `~/Documents/Code/InstaPy/` or does every virtual environment's copy of InstaPy need to be updated independently?

THANK YOU!

## InstaPy configuration

Mac with Python 3.7 running via Homebrew

Have been running InstaPy for months not in a virtual environment with no problems. Looking to move to virtual environments to run multiple sessions for multiple users at once.

Basic Installation:
```
1. git clone https://github.com/timgrossmann/InstaPy.git
2. cd InstaPy
3. pip install .
or
3. python setup.py install
```

_and then also on top of that_

Preferred Installation:
```
1. virtualenv user-xxxxx
2. source user-xxxxx/bin/activate
3. pip install git+https://github.com/timgrossmann/InstaPy.git
```

Have Chrome Driver installed at root of project `~/Documents/Code/InstaPy/assets/chromedriver`

InstaPy works inside `~/Documents/Code/InstaPy` when not using a virtual environment

**Comment by axlright** [comment]
I'm also wondering what the difference is between a setup of multiple virtual environments versus having each Instagram account have its own dedicated install of the repository and running multiple instances of InstaPy at once but with each instance having its own dedicated master install.

Thanks! 🙏

**Comment by Benjaminlooi** [comment]
The virtual environment is for python and its libraries only. It is written as the recommended way to run Instapy to make a virtual python environment that is installed with the dependencies for Instapy so it won't mess up the python libraries in the default location.

**Comment by axlright** [comment]
Thanks @Benjaminlooi. I'll close this ticket as it's not an issue with InstaPy. I'll work on learning more about virtual environments.
