### ISSUE TITLE
Is there any chance on getting banned on this environment?

### ISSUE THREAD

**Issue by imkimchi** [InstaPy/InstaPy#2854]
currently I'm running 5+ accounts on the same AWS instance, and each of them usually like 2.7k~2.9k posts everyday. the thing is that they use the same IPs so total likes everyday will be above 10k with the IP.

I'm trying to run more accounts but how can I avoid getting banned? 
Is it really that necessary to use proxy server or not? 

Is there anyone who is running multiple accounts without getting blocked ❓

**Comment by sionking** [comment]
AWS 5+ accounts ? 3K likes? you are blocked long time ago, you don't really get those likes check it manually.
NO ban but shadow.

**Comment by imkimchi** [comment]
@sionking always appreciate for the help, and yeah they were blocked for like a day, now I'm trying to figure out other way to avoid getting blocked. what's your setup look like?
