### ISSUE TITLE
Using like_by_locations with like_by_tags

### ISSUE THREAD

**Issue by igrekoni** [InstaPy/InstaPy#2859]
Greetings.

Using subj functions is understandable and easy to use.
But it is needed to use both of them, for example: i need to like all pictures with keyword 'cars' in location 'Los Angeles'. 
How can i implement this way?

**Comment by sionking** [comment]
no way

**Comment by Nuzzo235** [comment]
This should work but create a lot of servers calls and inappropriate posts

```
session.set_mandatory_words(['#cars'])
session.like_by_locations(['212999109/los-angeles-california'], amount=100)
`````

**Comment by sionking** [comment]
You will get 1/2 posts in each 500.
Better use clarifai to check for cars in image.

**Comment by igrekoni** [comment]
@Nuzzo235 thanks, seems this way is working

@sionking can you please explain why i will get only 1\2?

**Comment by igrekoni** [comment]
@Nuzzo235 i try you way, but it doest work. post text contain keyword, but not liked it
