### ISSUE TITLE
Chromedriver issue on UbuntuServer

### ISSUE THREAD

**Issue by AlexandruAcea** [InstaPy/InstaPy#286]
Hey guys! I was using InstaPy for some time and it worked perfectly, but I tried to use it from a UbuntuServer machine. Now, the issue is that when I'm starting it, it gives this error:
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally

Have you experienced this before? Thanks in advance!

**Comment by umangahuja1** [comment]
Try uninstalling and reinstalling chrome driver
Try this then:
sudo mv /opt/google/chromedriver /opt/
sudo ln -fs /opt/chromedriver /usr/local/bin/chromedriver
