### ISSUE TITLE
what is the recommended amount of like per day?

### ISSUE THREAD

**Issue by imkimchi** [InstaPy/InstaPy#2862]
I have 4 hashtags that It likes 21 times of the each hashtag in given time like code below.

so basically the program likes 1848 posts a day but I'm wondering If the amount of like would let the acount to get banned from like or not. Is there any recommended the best option to like posts everyday? I want to see any examples here thanks!

```

def job(index=0):
	try:
		start_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
		print("MULTI - Started as", instaUser[index], start_date)

		session = InstaPy(username=instaUser[index], password=instaPass[index], bypass_suspicious_attempt=True, headless_browser=True, nogui=True)
		session.login()
		session.set_relationship_bounds(enabled=True, potency_ratio=None, delimit_by_numbers=True)    

		session.set_user_interact(amount=2, randomize=True, percentage=100)
		session.set_dont_like(blackWords)
		session.set_do_like(enabled=True, percentage=100)
		session.set_do_follow(enabled=True, percentage=1)
		
		session.like_by_tags(['a', 'b', 'c', 'd'], amount=21, interact=True)
	except:
           import traceback
           print(traceback.format_exc())

	finally:
           	session.end()

times = ['8:03', '9:04', '12:07', '14:09', '15:10', '18:13', '19:14', '21:16', '22:17', '23:19', '00:20']

for idx, val in enumerate(times):
	schedule.every().day.at(val).do(multiJob)

```

**Comment by ghost** [comment]
The exact number of allowed actions (like, follow, unfollow, comment) per unit time is somewhat of a mystery in terms of how Instagram calculates it, and likely depends on multiple factors including your account age, number of followers/following, number of posts, average engagement, number of IPs used to access ig, etc, so it's hard to give a definite number. For a fairly young account with O(500) followers for example, the number is roughly 350 per 24 hr period. Liking 1848 posts per day (and presumably following a fair percentage of those users too) with a "young" account will almost definitely get you a temporary ban. Start slow and work your way up incrementally, and be patient.

**Comment by Nocturnal-2** [comment]
On the same line, how many server calls would be safe for a day? 

What is the maximum you have reached without a problem?  :)

I am concerned about this because I use a severely restricted liking and commenting strategy. Because of this, my server calls to number of likes ratio is quiet high.

**Comment by ghost** [comment]
In my most recent case, about 3000 server calls were issued before trouble began, but I'm not really sure if this number is relevant when determining if you've "overdone it". Again, it's hard to pinpoint exactly which metrics are used to calculate an acct's ban threshold, and from some simple research you'll see that there are many differing opinions out there. The best thing to do IMO is keep it conservative at first and work your way up. Keep your metrics within reasonable human limits and be patient!

**Comment by sionking** [comment]
Server call can be much less use fake account to scrawl
