### ISSUE TITLE
ALL THE TIME "Failed to load desired amount of users"

### ISSUE THREAD

**Issue by Marichka310** [InstaPy/InstaPy#2867]
## Expected Behavior
I expect that after:
`session.interact_user_followers(['blah-blah'], amount=1000, randomize=True)`
I will get 1000 users to interact with.
## Current Behavior
After:
`session.interact_user_followers(['blah-blah'], amount=1000, randomize=True)`
I get ~19-22 first users to interact with.
This bug is not fixed after https://github.com/timgrossmann/InstaPy/pull/2725 was merged.
## InstaPy configuration
My branch is uptodate with master.  
This bug is heppening on Ubuntu server and locally on my Mac.

**Comment by ceribbo** [comment]
sam problem here

**Comment by sammierlening** [comment]
Same Issue, and I am using myself as the user

**Comment by S4nderr** [comment]
Same here!
