### ISSUE TITLE
Hi this my problem after update  ( File "start.py", line 7, in <module>)

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#2868]
Traceback (most recent call last):
  File "start.py", line 7, in <module>
    from instapy import InstaPy
  File "/Users/jonathanverdier/Desktop/John/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/Users/jonathanverdier/Desktop/John/instapy/instapy.py", line 23, in <module>
    from .comment_util import comment_image
  File "/Users/jonathanverdier/Desktop/John/instapy/comment_util.py", line 7, in <module>
    from .util import update_activity
  File "/Users/jonathanverdier/Desktop/John/instapy/util.py", line 20, in <module>
    from .quota_supervisor import quota_supervisor
  File "/Users/jonathanverdier/Desktop/John/instapy/quota_supervisor.py", line 7, in <module>
    from plyer import notification
ModuleNotFoundError: No module named 'plyer'

**Comment by benniphilipp** [comment]
ihi, i have the same problem!

**Comment by oscady** [comment]
Yep same issue, although I was able to run the script but came across errors with unfollowing and I am having this issue on the up to date uluQulu fork

**Comment by ghost** [comment]
`sudo pip install plyer`

what's the problem?

**Comment by oscady** [comment]
yep @hotdogcannon that fixed it, although i then ran into an issue because i no longer had chromedriver in assets but it just wasn't unzipped

**Comment by ghost** [comment]
well, then install pip!

`sudo easy_install pip`

https://stackoverflow.com/questions/17271319/how-do-i-install-pip-on-macos-or-os-x

**Comment by johnvfitness** [comment]
yes it's good I have 
thx @hotdogcannon 
I always have the same mistake look

Jonathans-MacBook-Pro:john jonathanverdier$ pip install pyler
Collecting pyler
  Downloading https://files.pythonhosted.org/packages/74/d5/5b85750f13e45aea2881fb839e09d449c80c5115358410b7239b9578e5cd/pyler-0.2.0.tar.gz
  Running setup.py (path:/private/var/folders/3p/8_l8b6t547lbcb1tcsx_vmhm0000gn/T/pip-install-fDEo6i/pyler/setup.py) egg_info for package pyler produced metadata for project name unknown. Fix your #egg=pyler fragments.
Requirement already satisfied (use --upgrade to upgrade): unknown from https://files.pythonhosted.org/packages/74/d5/5b85750f13e45aea2881fb839e09d449c80c5115358410b7239b9578e5cd/pyler-0.2.0.tar.gz#sha256=f4c5a99ef2b5ca3db4371c8107f66ba9985d0089fb94b17f652ca87b5a26f24d in /Library/Python/2.7/site-packages
Jonathans-MacBook-Pro:john jonathanverdier$ python3 start.py
Traceback (most recent call last):
  File "start.py", line 7, in <module>
    from instapy import InstaPy
  File "/Users/jonathanverdier/Desktop/John/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/Users/jonathanverdier/Desktop/John/instapy/instapy.py", line 23, in <module>
    from .comment_util import comment_image
  File "/Users/jonathanverdier/Desktop/John/instapy/comment_util.py", line 7, in <module>
    from .util import update_activity
  File "/Users/jonathanverdier/Desktop/John/instapy/util.py", line 20, in <module>
    from .quota_supervisor import quota_supervisor
  File "/Users/jonathanverdier/Desktop/John/instapy/quota_supervisor.py", line 7, in <module>
    from plyer import notification
ModuleNotFoundError: No module named 'plyer'

**Comment by ghost** [comment]
try installing `plyer` instead of `pyler`

`sudo pip install plyer`

i misspelled it in my original answer, my bad!

**Comment by johnvfitness** [comment]
Thx bro 
I need to target the python folder 3
because it installs me in python 2.7

You have command for this bro ? Thx ;) @hotdogcannon

**Comment by ghost** [comment]
not sure, you'll have to google it

https://stackoverflow.com/questions/18425379/how-to-set-pythons-default-version-to-3-x-on-os-x/18425592#18425592

**Comment by johnvfitness** [comment]
Yes Buddy it's Good Thx ;) Bro
@hotdogcannon

**Comment by redsector72** [comment]
The latest update is a real mess. It does not update properly and seems like not working on a Mac Python.

There is an issue related to pip itself, as mac pip (2.7) seems not liking the ssl signature of current plyer. It has to be manually updated.

This means it will never run unless some hacking.

here is the hack
curl https://bootstrap.pypa.io/get-pip.py | python

**Comment by jufelka** [comment]
just make `sudo pip3 install plyer`
