### ISSUE TITLE
Interract Fonction doesn't work [session.follow_user_followers]

### ISSUE THREAD

**Issue by rmalosse** [InstaPy/InstaPy#2876]
Hello, 

I have problem with interact function. It doesn't work, below my configuration. 
With session.follow_user_following I follow 2 people of 'friends1' but after interact doesn't start. I try with another function & interact action (session.follow_user_followers)... 

Please said me if you have an issue I don't understand, this configuration works well 2 month ago..

I try  session.like_by_tags and like works well. 

## InstaPy configuration
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=False,
                                 potency_ratio=-1.21,
                                  delimit_by_numbers=False,
                                   max_followers=4590,
                                    max_following=5555,
                                     min_followers=45,
                                      min_following=77)
    session.set_do_comment(True, percentage=100)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'], media='Photo')
    # actions
    session.like_by_tags(['natgeo'], amount=1)
    session.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')
    session.follow_user_following(['friend1'], amount=2, randomize=False, interact=True)

**Comment by MrBeardedGuy** [comment]
One thing you should check is the position/order of ` set_*` methods in your script. Essentially, all the` set_*` methods have to be before `like_by_tags` or `like_by_locations` or `unfollow` etc... 

In your case just move up `session.set_user_interact` before `like_by_tags`

**Comment by rmalosse** [comment]
Thank you MrBeardedGuy, it's a mistake yes but I tried to change & I have the same problem.. 

  # settings
    session.set_relationship_bounds(enabled=False,
                                 potency_ratio=-1.21,
                                  delimit_by_numbers=False,
                                   max_followers=4590,
                                    max_following=5555,
                                     min_followers=45,
                                      min_following=77)
    session.set_do_comment(True, percentage=100)
    session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'], media='Photo')
    session.set_dont_include(['friend1', 'friend2', 'friend3'])
    session.set_dont_like(['pizza', 'girl'])
    session.set_do_follow(enabled=True, percentage=100, times=2)
    session.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')
    # actions                    
   session.like_by_tags(['natgeo'], amount=1)
    session.follow_user_following(['friends1'], amount=2, randomize=False, interact=True)

**Comment by MrBeardedGuy** [comment]
Strange, I'm using a similar code and everything works fine. 

My suggestion is to make sure to pull the latest version of InstaPy with `git pull origin master`

Also, are you getting any errors or it just does follow anyone?
Maybe check that the username you have in `session.follow_user_following` exists... You could have misspelled it.

**Comment by rmalosse** [comment]
Really don't understand, yes I use the account called "instagram" for my test.. 

I have the latest version because I re install server to try .. 

root@vultr:~/InstaPy# python3 quickstart.py

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-09-11 20:29:27] [romayn69]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo


..............................................................
INFO [2018-09-11 20:29:55] [romayn69]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-09-11 20:29:58] [romayn69]  User 'instagram' [1/1]

INFO [2018-09-11 20:30:29] [romayn69]  Grabbed 1 usernames from instagram's `Following` to do following.
INFO [2018-09-11 20:30:29] [romayn69]  User 'coco_pinkprincess' [1/1]
INFO [2018-09-11 20:30:32] [romayn69]  --> coco_pinkprincess instagram account is opened...
INFO [2018-09-11 20:30:42] [romayn69]  ---> Now following: coco_pinkprincess
INFO [2018-09-11 20:30:50] [romayn69]  Follow [1/1]  |  Total Follow: 1
INFO [2018-09-11 20:30:50] [romayn69]  --> Followed total of 1 people

INFO [2018-09-11 20:30:50] [romayn69]  Liked: 0
INFO [2018-09-11 20:30:50] [romayn69]  Already Liked: 0
INFO [2018-09-11 20:30:50] [romayn69]  Commented: 0
INFO [2018-09-11 20:30:50] [romayn69]  Followed: 0
INFO [2018-09-11 20:30:50] [romayn69]  Inappropriate: 0
INFO [2018-09-11 20:30:50] [romayn69]  Not valid users: 0


OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-09-11 20:30:51] [romayn69]  Session ended - 2018-09-11 20:30:51
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by rmalosse** [comment]
Can you send me your configuration with interact function please ? Thanks

**Comment by MrBeardedGuy** [comment]
``` import random
from instapy import InstaPy
import os
import multiprocessing
import datetime
import time

instaUser = ['username1', 'username2']
instaPass = ['pass1', 'pass2']
followersToFollow = [['acc1RelatedtoUser1', 'acc2RelatedtoUser1'], ['acc1RelatedtoUser2']]
smartTags = [['tag1User1', 'tag2User1'], ['tag1User2']]

def worker(selection):

    print("MULTI - Started as",instaUser[selection],"at",datetime.datetime.now().strftime("%H:%M:%S"))
    session = InstaPy(username=instaUser[selection], password=instaPass[selection], headless_browser=True)
    session.login()

    session.set_dont_unfollow_active_users(enabled=True, posts=7)
    session.set_user_interact(amount=2, randomize=True, percentage=20, media='Photo')
    session.set_relationship_bounds(enabled=True,
             potency_ratio=-1.21,
              delimit_by_numbers=True,
               max_followers=4590,
                max_following=5555,
                 min_followers=45,
                  min_following=77)

    session.like_by_feed(amount=random.randint(5,11), randomize=True, unfollow=True, interact=True)
    
    session.unfollow_users(amount=random.randint(7,10), sleep_delay=(random.randint(44,111)))

    if followersToFollow[selection]:
        session.follow_user_followers(followersToFollow[selection], amount=random.randint(44,55), randomize=False, interact=True, sleep_delay=111)

    if smartTags[selection]:
        session.set_smart_hashtags(smartTags[selection], limit=3, sort='top', log_tags=True)
        session.like_by_tags(amount=random.randint(2,5), use_smart_hashtags=True)

    session.end()
    print("MULTI -",instaUser[selection],"finished run at",datetime.datetime.now().strftime("%H:%M:%S"))

if __name__ == '__main__':
    print("MULTI -","Starting at",datetime.datetime.now().strftime("%H:%M:%S"))
    jobs = []
    for i in range(len(instaUser)):
        p = multiprocessing.Process(target=worker, args=(i,))
        jobs.append(p)
        p.start()
        time.sleep(66);#no delay cause some instances of chrome to give errors and stop ```
