### ISSUE TITLE
follow_likers add check for retry followed

### ISSUE THREAD

**Issue by EduardKov** [InstaPy/InstaPy#2877]
## Expected Behavior
we need the follow_likers function to check how many times we previously followed to a certain account and did not follow if we enabled the restriction on repeated follow (for example, times = 2)

## Current Behavior
the follow_likers function followed many times on the same accounts

## Possible Solution
Enable checking for repeated follow in the follow_likers function, similar to the set_do_follow settings (enabled = True, percentage = 10, times = 2)
It might be worthwhile to add a repeat follow check to set_relationship_bounds

**Comment by EduardKov** [comment]
@uluQulu 
is there a way to control following in the follow_likers function?

**Comment by uluQulu** [comment]
Yes @EduardKov 
Just set the desired repeated follow times value inside `set_do_follow()` setting and make sure that line resides before the feature you are gonna run inside your quickstart script.
```python
""" inside Quickstart script """
# code code
session.set_do_follow(enabled=True, percentage=100, times=2)

# code code
session.follow_likers()
```

It shall work for you.

`set_relationship_bounds()` is configuring a bit different setting but I got your point, I will think of it some time.

_If not works or any questions, just ask away_ 💭

------

Cheers 😁
----
