### ISSUE TITLE
Warning: Comment Button Not Found: May cause issues with browser windows of smaller widths

### ISSUE THREAD

**Issue by greggjaskiewicz** [InstaPy/InstaPy#2880]
## Expected Behavior
comments should be posted

## Current Behavior
Console log: Warning: Comment Button Not Found: May cause issues with browser windows of smaller widths

## InstaPy configuration
Pretty much default configuration, out of the box - with additional accounts to follow, hashtags and comments. 

## logs

INFO [2018-09-09 16:24:04] [xxxx]  [20/20]
INFO [2018-09-09 16:24:04] [xxxx]  xxx1
INFO [2018-09-09 16:24:09] [xxxx]  Image from: ferguszzz_hippo
INFO [2018-09-09 16:24:09] [xxxx]  Link: xxx
INFO [2018-09-09 16:24:09] [xxxx]  Description: 食好西 轆車仔 ❤

#tomy #tomica #tomytec #honda #civic #hondacivic #typer #civictyper #collector #collectible #collection #xh1 #fujifilm #fujinon #fujifilmxh1 #mirrorless #mirrorlesscamera #photoshoot #photography #photographer #dailylife #citylife #urban #nerdsdaily #fergusfocus @honda @honda_hk @typeruk
INFO [2018-09-09 16:24:15] [xxxx]  User: ferguszzz_hippo >> followers: 585  |  following: 2186  |  relationship ratio: 3.74
INFO [2018-09-09 16:24:29] [xxxx]  --> Image Liked!
WARNING [2018-09-09 16:24:56] [xxxx]  --> Warning: Comment Button Not Found: May cause issues with browser windows of smaller widths
INFO [2018-09-09 16:24:58] [xxxx]  --> Commented: Nice shot!
INFO [2018-09-09 16:25:00] [xxxx]  --> Not following
INFO [2018-09-09 16:25:01] [xxxx]  Tag [8/12]

**Comment by MrBeardedGuy** [comment]
Not sure why there's always that warning, but the comment has been actually posted correctly if you take a look at the picture.

**Comment by greggjaskiewicz** [comment]
doh! so much for anonymity
