### ISSUE TITLE
shadow ban using unfollow

### ISSUE THREAD

**Issue by jtrieuDev** [InstaPy/InstaPy#2882]
Hi everyone, I am trying to use the unfollow methods

but every time I am launching the script, i got this:

"There is a serious issue: 'shadow ban'!	~leaving Unfollow-Users activity
INFO [2018-09-10 01:09:48] [username]  --> Total people unfollowed : 1
"

Here is my script:
    session.login()
    session.set_relationship_bounds(enabled=False,
				 potency_ratio=-1.21,
				  delimit_by_numbers=False,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    session.set_simulation(enabled=False)
    session.unfollow_users(amount=400, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=None, sleep_delay=501)

**Comment by davidvee7** [comment]
I'm also running into this issue

**Comment by kukkakeppi** [comment]
Same here.. No idea what to do.

**Comment by timgrossmann** [comment]
@jtrieuDev @davidvee7 @kukkakeppi Could you guys pull and try again, please?
@uluQulu should have fixed it 😉

**Comment by jtrieuDev** [comment]
it is still happening for me.. 
sometimes it goes until more than 1x unfollows but sometimes still stop after 2-3 unfollowers

**Comment by uluQulu** [comment]
Hey guys
@timgrossmann I just noticed that bug while running a test for this problem,
>There is a serious issue: 'shadow ban'! ~leaving Unfollow-Users activity

I mean my latest PR solves another bug but not the one above.
It's a bit mystery, needs more feedback.

It happens once it clicks to unfollow a user and then it checks again and user is still not unfollowed then points out a possible shadow ban.

@jtrieuDev Can you run this test?
Open the session in graphical mode and watch what happens:
+ Does it click on "_Following_" or "_Requested_" button?
+ Does the "_Unfollow_" dialog pop up?  & Does it click on it?
+ Does that button now is "_Follow_" or "_Follow Back_"?

It's the same procedure introduced by @sionking, I have not changed anything in that part, just error message has changed 😉

_Anybody having that exact error message could run that test_.

-----

Cheers 😁
--------

**Comment by jtrieuDev** [comment]
Hi @uluQulu thank you for your answer,
I just did the test and

Yes, it does click on "Following" or "Requested" button
Yes, the "Unfollow" dialog does pop up, and it clicks on it
Yes, that button is either "Follow" for "Follow back"

**Comment by uluQulu** [comment]
Amazing @jtrieuDev 
So where it did crash?

Can you watch it until crashes? 😀
Cos you have said it crashes so early..

I want that information of it which leads to a crash.

So, with the steps in above comment, I have additions,
+ Does it crash after the button changes from "_Following_"/"_Requested_" to "_Follow_"/"_Follow Back_"?
+ Does it crash after the button does not change from "_Following_"/"_Requested_"?
+ Anything else? [new button? 🤤]

---------

Cheers 😁
-----------

**Comment by jtrieuDev** [comment]
@uluQulu ok so the crash is happening after it is on the user's page, and the button is still on "Following" and then it crashes, (the unfollow dialog doesn't pop up)

But when I launched the script again, the user is unfollowed (button "Follow"/"Follow back"), seems like his name didn't got removed from the CSV

The weird thing is that it is working well on my other account.
Maybe is it due to my account ? but why ? thank you for your help !

and the last logs are:
"
INFO [2018-09-11 01:04:16] [username]  Ongoing Unfollow [7/300]: now unfollowing 'unfollower'...
WARNING [2018-09-11 01:04:38] [username]  --> Unfollow error!	~username 'username' might be blocked from unfollowing

WARNING [2018-09-11 01:04:38] [username]  There is a serious issue: 'shadow ban'!	~leaving Unfollow-Users activity
INFO [2018-09-11 01:04:38] [username]  --> Total people unfollowed : 6
"

**Comment by uluQulu** [comment]
@jtrieuDev 
It's a bit mysteric to debug, this kind of issues needs direct observation to solve.
I have a guess that it crashes out of **Unfollow** dialog does not pop up.

Add this new debug line to your `confirm_unfollow()` definition in **unfollow_util.py** file
```python
                click_element(browser, unfollow_button)
                print("\nunfollow popup was clicked\n")   # ADD THIS LINE
```
Then, tell me what happens during a crash, will it print that debug line or not...

-------

Cheers 😁
--------

**Comment by jtrieuDev** [comment]
`INFO [2018-09-11 11:27:08] [user]  Ongoing Unfollow [4/300]: now unfollowing 'watashi_._'...

unfollow popup was clicked

WARNING [2018-09-11 11:27:19] [user]  --> Unfollow error!	~username 'user' might be blocked from unfollowing

WARNING [2018-09-11 11:27:19] [user]  There is a serious issue: 'shadow ban'!	~leaving Unfollow-Users activity
INFO [2018-09-11 11:27:19] [user]  --> Total people unfollowed : 3`

Hi @uluQulu this is what I got :(, thank you for your time

**Comment by uluQulu** [comment]
@jtrieuDev 
Did the unfollow dialog pop up at that scenario?

**Comment by jtrieuDev** [comment]
@uluQulu Alright my bad, the Unfollow pop up dialog does come out, then it seems like it is clicking on the "Unfollow" then it crashes right after,

logs are:
`INFO [2018-09-11 13:22:59] [jowti]  Ongoing Unfollow [5/300]: now unfollowing 'melanie_costa66'...

unfollow popup was clicked

WARNING [2018-09-11 13:23:09] [user]  --> Unfollow error!	~username 'jowti' might be blocked from unfollowing

WARNING [2018-09-11 13:23:09] [user]  There is a serious issue: 'shadow ban'!	~leaving Unfollow-Users activity
INFO [2018-09-11 13:23:09] [user]  --> Total people unfollowed : 4`

So I think, it crashes right before the step that print "the user has been unfollowed correctly and removed from CSV" even if the user has been unfollowed

**Comment by uluQulu** [comment]
Alright, @jtrieuDev 
Try this,
Increase the sleep delay after confirming unfollow from the popup
```python
                click_element(browser, unfollow_button)
                print("\nunfollow popup was clicked\n")
                sleep(7)   # MODIFY THIS LINE: 2 seconds -> 7 seconds
```

------------

Cheers 😁
--------

**Comment by jtrieuDev** [comment]
@uluQulu oh it seems like it it working well ! Thanks a lot 👍 It keeps going to at least 5x unfollows then crashes haha
By the way I wanted to ask, I want to put a delay for liking picture, where exactly in the code I need to put it ? Because my account is blocked everytime I put a huge amount, i just want to do it so it takes longer, like all day to like 900 pictures
this is the code I am using
`    session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
    session.set_do_like(enabled=True, percentage=80)
    session.interact_user_followers(['username'], amount=900, randomize=True)`

Thanks a lot for your time !

**Comment by uluQulu** [comment]
@jtrieuDev Can you verify how stable it is?
Cos you said it works and then updated it does not.
Increase that sleep time to 15 seconds or 1 minute 😁

But in any case I think the problem lays in there. I also noticed an issue similar to that part.
On some account while unfollowing somebody after clicking the unfollow button in the popup, it take a big delay sometimes.
And even sometimes it needs a reload and then retry to properly do that action.

Why it could happen? - several reasons.
And good news is having observed those situations I will write a stable solution using explicit wait and add some situation handlers.

For now, @jtrieuDev, do that sleep delay increasement and keep up continuous feedbacking.
I will write the solution soon and share with you.


@jtrieuDev 
>By the way I wanted to ask, I want to put a delay for liking picture, where exactly in the code I need to put it ? 

Hmm, be specific - where and why do you need that delay.  
But for general you can use `session.set_sleep_reduce(percentage=140)` at desired percentage. (_see `README`_)

>Because my account is blocked everytime I put a huge amount, i just want to do it so it takes longer, like all day to like 900 pictures

Why don't you use quota supervisor for that? (_see `README`_)

-----

Cheers 😁
-----

**Comment by uluQulu** [comment]
Hey guys
I did my promise- wrote a stable solution using explicit wait and added situation handlers and shared at #2901 

Now it should solve your issues, fully 💯

-----

Cheers 😁
------

**Comment by davidvee7** [comment]
@uluQulu , haven't tried your latest solution, but the one earlier worked!  The hardcoding to 7 is good.  Thanks!

**Comment by ghost** [comment]
I can also confirm that simply increasing the sleep interval solved the problem for me too. Still looking forward to the fancier fix being merged. Thanks @uluQulu !

**Comment by jtrieuDev** [comment]
@uluQulu I also confirm, it's working well with the hard coding 7 seconds sleep, you are the best thanks 👍 
I will try the quota supervisor that you coded haha, I just wanted to have a delay between each Likes

**Comment by meinert** [comment]
I am experiencing the same.....from my debugging the problem relates to get_following_status....see https://github.com/timgrossmann/InstaPy/issues/2926
