### ISSUE TITLE
Liking feed images

### ISSUE THREAD

**Issue by misterscraper** [InstaPy/InstaPy#2887]
Is there any way to adjust the command for liking all the images in your feed? 

I'm running the following:
`session.like_by_feed(amount=500, randomize=False)`

But sometimes I get the following message when I'm trying to like some images:
 `User example followers count exceeds maximum limit  ~skipping user`

**Comment by uluQulu** [comment]
Hey @nkycldn 
Take a few seconds to read on using `set_relationship_bounds` in **README**.
>User example followers count exceeds maximum limit ~skipping user

You can turn off verification based on relationship bounds
+ `session.set_relationship_bounds(enabled=False) `

OR control it as wanted
+ `session.set_relationship_bounds(enabled=True, delimit_by_numbers=True, max_followers=20000, min_followers=100)`

------

Cheers 😁
------
