### ISSUE TITLE
Help installing on Ubuntu droplet?

### ISSUE THREAD

**Issue by mattsafaii** [InstaPy/InstaPy#289]
I created a new Ubuntu 16.04 droplet and did the express install:
```
git clone https://github.com/timgrossmann/InstaPy.git
$ cd scripts
$ ./unix.sh
```
After that, I went to my droplet's IP address in Chrome and it gave me an error. It said the site can't be reached. Then I went to the instapy.py file and changed "nogui=False" to "nogui=True". Refreshed the browser and it's still not working.

What am I doing wrong here?

**Comment by timgrossmann** [comment]
@mattmaker Try to use the Advanced setup and install everything separately 😉

**Comment by sdiepend** [comment]
@mattmaker I don't think the the ip address is supposed to serve something, just run the python program from the server itself.
