### ISSUE TITLE
Users not being removed from followed list

### ISSUE THREAD

**Issue by therealahall** [InstaPy/InstaPy#2890]
## Expected Behavior
Users get removed from the followed list after being unfollowed
## Current Behavior
Users are being unfollowed properly, but because the list contains entries prior to a recent update, they are not actually removed
## Possible Solution (optional)

Not sure if this will solve it, but I did notice that some of the new follows show  ~ unknown, at the end of the line.  It may be possible to add these to the other, older, lines and allow them to remove properly.  Otherwise the preferred solution would be to make the unfollow removal process backwards compatible with previous versions of the followedPool.csv file.

## InstaPy configuration
I don't think the configuration file is the issue here, I think it's the formatting of the followedPool.csv file.

For example, prior to doing a git pull, my followedPool showed:
2018-08-13 12:53 ~ username,

New users added after the git pull show as:
2018-09-09 20:47 ~ username ~ numeric string,

I'm assuming the removal is looking for this additional string but am not 100% sure

**Comment by therealahall** [comment]
I can confirm that adding ~ unknown to the end of the line does allow the line to be removed so there is a workaround available.

**Comment by uluQulu** [comment]
@aaron-hall-7,
You have done lots of guessing 🤓

It is a known bug, hopefully, @CharlesCCC will solve it soon. 

----------

Cheers 😁
---------

**Comment by therealahall** [comment]
Thank you @uluQulu, Python is not my best language so I didn't want to go traipsing through the code.  I figured some good ol' detective work could help figure it out. Glad to know there's a potential solution coming through!

**Comment by benzakenelad** [comment]
in unfollow_util at the function confirm_unfollow, change:

            elif isinstance(exc, NoSuchElementException):
                sleep(1)
                pass

to

            elif isinstance(exc, NoSuchElementException):
                sleep(1)
                break

in addition(at the same function), change:

            button_xp = "//button[text()='Unfollow']"  # "//button[contains(text(), 'Unfollow')]"
            unfollow_button = browser.find_element_by_xpath(button_xp)
            attempt += 1

to

            button_xp = "//button[text()='Unfollow']"  # "//button[contains(text(), 'Unfollow')]"
            attempt += 1
            unfollow_button = browser.find_element_by_xpath(button_xp)


the problem was infinite loop at confirm_unfollow function...

**Comment by uluQulu** [comment]
@aaron-hall-7 
Glad to help 👋🏼

@benzakenelad 
Thanks for reminding about the infinite loop case.

That infinite loop can only be occurred once Unfollow dialog does not pop up AND these days it always pops up. But that scenario must be handled.
`attempt += 1` line should really be located as you said.

But do not replace `pass` with `break` in there. It is intentional.
That loop will break after 3 attempts.

Also, you are looking for solution in wrong place cos the issue outlined in this thread is different, but thanks for that bug fix 🎊
Can you PR that line, @benzakenelad?


-------

Cheers 😁
-----
