### ISSUE TITLE
ImportError: No module named plyer

### ISSUE THREAD

**Issue by Benjaminlooi** [InstaPy/InstaPy#2891]
## Current Behavior
```
Traceback (most recent call last):
  File "com_unfollow.py", line 8, in <module>
    from instapy import InstaPy
  File "/home/michael/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/home/michael/InstaPy/instapy/instapy.py", line 23, in <module>
    from .comment_util import comment_image
  File "/home/michael/InstaPy/instapy/comment_util.py", line 7, in <module>
    from .util import update_activity
  File "/home/michael/InstaPy/instapy/util.py", line 20, in <module>
    from .quota_supervisor import quota_supervisor
  File "/home/michael/InstaPy/instapy/quota_supervisor.py", line 7, in <module>
    from plyer import notification
ImportError: No module named plyer
```

## Possible Solution (optional)
So i thought I didn't have the plyer module so i tried pip install plyer but: Requirement already satisfied: plyer in /usr/local/lib/python3.6/dist-packages (1.3.0)

## InstaPy configuration
I believe theres nothing to with my configuration but here is it:

```
import os
import time
import subprocess
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = 'xxx'
insta_password = 'xxx'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True,
                  bypass_suspicious_attempt=True)
try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
    			 potency_ratio=-1.00,
    			  delimit_by_numbers=True,
    			   max_followers=9000,
    			    max_following=9000,
    			     min_followers=45,
    			      min_following=77)

    
    accs = ['nina','ellagross','kimkardashian','taylorswift','selenagomez','dailydose','igbenlee','goodlife','briandevans','therock','natgeo']
    session.follow_user_followers(accs, amount=50, randomize=True, sleep_delay=60)

    

#except:


finally:
    # end the bot session
    session.end()
    subprocess.Popen(['python', 'com_follow.py'])

```

**Comment by gS32tom** [comment]
Same error here.

Edit: pip install plyer fixed it for me.

**Comment by benzakenelad** [comment]
pip uninstall plyer
pip install plyer

**Comment by Benjaminlooi** [comment]
> pip uninstall plyer
> pip install plyer

did not work, but running it on python3 solved the issue.
`python3 quickstart.py`

**Comment by BPiepmatz** [comment]
Hey had this issue when I wanted to install it via pip install plyer:

> Collecting plyer
>   Using cached https://files.pythonhosted.org/packages/c4/19/f7cf7658e0f671294d8675a0bcc5d76883e8e738cc1e78dd097e2ea5fa72/plyer-1.3.0.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-hvc4tve3/plyer/setup.py", line 28, in <module>
>         changelog = fd.read()
>       File "/anaconda3/envs/instapy/lib/python3.6/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4636: ordinal not in range(128)
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-hvc4tve3/plyer/



I use Ubuntu and Conda as an virtual environment. I figured out to solve this with the following and built plyer from source: 
> pip install git+https://github.com/kivy/plyer.git@master

Maybe this helps someone else! best

**Comment by benzakenelad** [comment]
Sory I am abroad until the September 25, if some one can PR this it will be
great.
Thanks!!

Elad.

**Comment by mobilal951** [comment]
> Same error here.
> 
> Edit: pip install plyer fixed it for me.

Same Thanks man :)

**Comment by ghost** [comment]
i have installed pyler by pip install pyler but it is showing error

answer: just do
pip install "plyer==1.4.2"
