### ISSUE TITLE
Setting up a Schedule?

### ISSUE THREAD

**Issue by misterscraper** [InstaPy/InstaPy#2892]
Is there any way to set up my bot to start and stop actions at a specific time of day?

I'm using the following command on Mac OS:

```
from instapy import InstaPy

insta_username = 'username'
insta_password = 'password'

# if you want to run this script on a server,
# simply add nogui=True to the InstaPy() constructor
session = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
session.login()

# set up all the settings
session.set_relationship_bounds(enabled=True,
				   max_followers=3000000,
				     min_followers=1,)

# Interact with the people that a given user is following
# set_do_comment, set_do_follow and set_do_like are applicable

session.set_user_interact(amount=5, randomize=False, percentage=50, media='Photo')
session.set_do_follow(enabled=False, percentage=70)
session.set_do_like(enabled=True, percentage=70)
session.set_comments([u':fire: :fire:', u':heart_eyes: :heart_eyes:'])
session.set_do_comment(enabled=True, percentage=80)
session.interact_user_following(['username'], amount=500, randomize=True)

# do the actual liking
session.like_by_feed(amount=500, randomize=False)

# end the bot session
session.end()

```

**Comment by FarkasLabs** [comment]
Use schedule!
Install it with:
`pip install schedule`

Example:
`import schedule`

```
schedule.every().day.at("20:30").do(function) 
schedule.every().day.at("22:00").do(function) 
schedule.every().day.at("23:30").do(function) 

while True:
    schedule.run_pending()
    time.sleep(1)
```

**Comment by misterscraper** [comment]
> Use schedule!
> Install it with:
> `pip install schedule`
> 
> Example:
> `import schedule`
> 
> ```
> schedule.every().day.at("20:30").do(function) 
> schedule.every().day.at("22:00").do(function) 
> schedule.every().day.at("23:30").do(function) 
> 
> while True:
>     schedule.run_pending()
>     time.sleep(1)
> ```

So my code should look like the following to start a Schedule?

```
from instapy import InstaPy
import schedule

insta_username = 'username'
insta_password = 'password'

# if you want to run this script on a server,
# simply add nogui=True to the InstaPy() constructor
session = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
session.login()

# set up all the settings
session.set_relationship_bounds(enabled=True,
				   max_followers=3000000,
				     min_followers=1,)

# Interact with the people that a given user is following
# set_do_comment, set_do_follow and set_do_like are applicable

session.set_user_interact(amount=5, randomize=False, percentage=25, media='Photo')
session.set_do_follow(enabled=False, percentage=70)
session.set_do_like(enabled=True, percentage=70)
session.set_comments([u':fire: :fire:', u':heart_eyes: :heart_eyes:'])
session.set_do_comment(enabled=True, percentage=80)
session.interact_user_following(['username'], amount=250, randomize=True)
session.unfollow_users(amount=100, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)

# do the actual liking
session.like_by_feed(amount=500, randomize=False)

# end the bot session
session.end()

schedule.every().day.at("01:30").do(function)
schedule.every().day.at("12:00").do(function)
schedule.every().day.at("21:30").do(function) 

while True:
    schedule.run_pending()
    time.sleep(1)
```

**Comment by FarkasLabs** [comment]
no, you should put your instapy code inside a function, like this:


```python
from instapy import InstaPy
import schedule

insta_username = 'username'
insta_password = 'password'

def myinstastrategy():
    # if you want to run this script on a server,
    # simply add nogui=True to the InstaPy() constructor
    session = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
    session.login()

    # set up all the settings
    session.set_relationship_bounds(enabled=True,
                       max_followers=3000000,
                         min_followers=1,)

    # Interact with the people that a given user is following
    # set_do_comment, set_do_follow and set_do_like are applicable

    session.set_user_interact(amount=5, randomize=False, percentage=25, media='Photo')
    session.set_do_follow(enabled=False, percentage=70)
    session.set_do_like(enabled=True, percentage=70)
    session.set_comments([u':fire: :fire:', u':heart_eyes: :heart_eyes:'])
    session.set_do_comment(enabled=True, percentage=80)
    session.interact_user_following(['username'], amount=250, randomize=True)
    session.unfollow_users(amount=100, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)

    # do the actual liking
    session.like_by_feed(amount=500, randomize=False)

    # end the bot session
    session.end()

schedule.every().day.at("01:30").do(myinstastrategy)
schedule.every().day.at("12:00").do(myinstastrategy)
schedule.every().day.at("21:30").do(myinstastrategy) 

while True:
    schedule.run_pending()
    time.sleep(1)
```

**Comment by misterscraper** [comment]
> no, you should put your instapy code inside a function, like this:
> 
> ```python
> from instapy import InstaPy
> import schedule
> 
> insta_username = 'username'
> insta_password = 'password'
> 
> def myinstastrategy():
>     # if you want to run this script on a server,
>     # simply add nogui=True to the InstaPy() constructor
>     session = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
>     session.login()
> 
>     # set up all the settings
>     session.set_relationship_bounds(enabled=True,
>                        max_followers=3000000,
>                          min_followers=1,)
> 
>     # Interact with the people that a given user is following
>     # set_do_comment, set_do_follow and set_do_like are applicable
> 
>     session.set_user_interact(amount=5, randomize=False, percentage=25, media='Photo')
>     session.set_do_follow(enabled=False, percentage=70)
>     session.set_do_like(enabled=True, percentage=70)
>     session.set_comments([u':fire: :fire:', u':heart_eyes: :heart_eyes:'])
>     session.set_do_comment(enabled=True, percentage=80)
>     session.interact_user_following(['username'], amount=250, randomize=True)
>     session.unfollow_users(amount=100, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)
> 
>     # do the actual liking
>     session.like_by_feed(amount=500, randomize=False)
> 
>     # end the bot session
>     session.end()
> 
> schedule.every().day.at("01:30").do(myinstastrategy)
> schedule.every().day.at("12:00").do(myinstastrategy)
> schedule.every().day.at("21:30").do(myinstastrategy) 
> 
> while True:
>     schedule.run_pending()
>     time.sleep(1)
> ```

Thanks, but I'm getting the following error:

```
Traceback (most recent call last):
  File "quickstart.py", line 41, in <module>
    time.sleep(1)
NameError: name 'time' is not defined
```

**Comment by FarkasLabs** [comment]
`import time`

inserting this on the top should fix it

**Comment by misterscraper** [comment]
> `import time`
> 
> inserting this on the top should fix it

Yay! thanks so much!, so logically I can setup different 'myinstastrategy' tags for different times of the days for different activities?

**Comment by FarkasLabs** [comment]
> > `import time`
> > inserting this on the top should fix it
> 
> Yay! thanks so much!, so logically I can setup different 'myinstastrategy' tags for different times of the days for different activities?

Exactly. You can also run different strategies on specific days for example.

Here are some examples:
```python
schedule.every(10).minutes.do(job)
schedule.every().hour.do(job)
schedule.every().day.at("10:30").do(job)
schedule.every(5).to(10).minutes.do(job)
schedule.every().monday.do(job)
schedule.every().wednesday.at("13:15").do(job)
```

**Comment by misterscraper** [comment]
> > > `import time`
> > > inserting this on the top should fix it
> > 
> > 
> > Yay! thanks so much!, so logically I can setup different 'myinstastrategy' tags for different times of the days for different activities?
> 
> Exactly. You can also run different strategies on specific days for example.
> 
> Here are some examples:
> 
> ```python
> schedule.every(10).minutes.do(job)
> schedule.every().hour.do(job)
> schedule.every().day.at("10:30").do(job)
> schedule.every(5).to(10).minutes.do(job)
> schedule.every().monday.do(job)
> schedule.every().wednesday.at("13:15").do(job)
> ```

This is amazing, thanks so much. I look forward to making all kinds of schedules :)

**Comment by Apao123** [comment]
Hello @fmorva  - do you ever combine smart_run and schedule? i'm lost here

**Comment by workinprogressgh** [comment]
I tried this code and had the following error, I'd be grateful if you can help me fix it:

Traceback (most recent call last):
  File "hot_schedule.py", line 2, in <module>
    import schedule
  File "/root/hot/schedule.py", line 19, in <module>
    schedule.every().day.at("6:35").do(job)
AttributeError: module 'schedule' has no attribute 'every'

**Comment by FarkasLabs** [comment]
> I tried this code and had the following error, I'd be grateful if you can help me fix it:
> 
> Traceback (most recent call last):
> File "hot_schedule.py", line 2, in 
> import schedule
> File "/root/hot/schedule.py", line 19, in 
> schedule.every().day.at("6:35").do(job)
> AttributeError: module 'schedule' has no attribute 'every'

Don't call your python file schedule.py because it conflicts with the schedule library itself. Rename your file and it should work!

**Comment by spryder89** [comment]
can you help me 
How it works with raspberry pi?

**Comment by hafis11** [comment]
Traceback (most recent call last):
  File "quickstart.py", line 17, in <module>
    with smart_run(session):
NameError: name 'session' is not defined

help me to resolve..

**Comment by Polkyanik** [comment]
i still have the same problem ..
has anyone solved?

**Comment by diogoribeirodev** [comment]
Anyone with this error? selenium.common.exceptions.WebDriverException: Message: [Exception... "Data conversion failed because significant data would be lost"  nsresult: "0x80460003 (NS_ERROR_LOSS_OF_SIGNIFICANT_DATA)"  location: "<unknown>"  data: no]

i get it one : schedule.run_pending() line
