### ISSUE TITLE
Unfollow not working

### ISSUE THREAD

**Issue by ceribbo** [InstaPy/InstaPy#2894]
unfollow is not working, it can't find the unfollow people.
updated to the last version.

## Current Behavior
INFO [2018-09-11 14:31:10] [user] --> Total people unfollowed : 0 
WARNING [2018-09-11 14:31:10] [user] Unable to find the count of users followed ~leaving unfollow feature 
INFO [2018-09-11 14:31:10] [user] Failed to get following count of 'user' ~empty list 
INFO [2018-09-11 14:30:20] [user] Failed to get followers count of 'user' ~empty list 
b"[Errno 2] No such file or directory: 'logs/user_followedPool.csv'" 
ERROR [2018-09-11 14:29:23] [user] Error occured while generating a user list from the followed pool! 
INFO [2018-09-11 14:29:23] [user] Starting to unfollow users.. 
INFO [2018-09-11 14:29:03] [user] Logged in successfully! 
INFO [2018-09-11 14:28:29] [user] Session started!

**Comment by crowg** [comment]
same issue.

**Comment by rodriguesprobr** [comment]
Same issue.

**Comment by ceribbo** [comment]
up

**Comment by S4nderr** [comment]
Same problem

**Comment by IsmaelAbadToaldo** [comment]
same

**Comment by sionking** [comment]
The issue is clear:
'logs/user_followedPool.csv'"
user shall be user and not 'user'.

**Comment by sionking** [comment]
anyway just clone new repo and make a compare since I don't see anything wrong in the code.

**Comment by Drazozo** [comment]
Same issue.

**Comment by Drazozo** [comment]
C:\xampp\htdocs\insta>python unfollow.py

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/mrmet/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
INFO [2019-03-30 18:10:59] [drazozo]  Using built in instapy-chromedriver executable (version 2.46)

DevTools listening on ws://127.0.0.1:56793/devtools/browser/fdde8820-e31f-41c4-8ffb-a566c98ab4f0

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-03-30 18:11:01] [drazozo]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

.............................................................
INFO [2019-03-30 18:12:28] [drazozo]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-03-30 18:12:28] [drazozo]  Saving account progress...

__________________________________________________________________
INFO [2019-03-30 18:12:49] [drazozo]  Starting to unfollow users..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
ERROR [2019-03-30 18:12:49] [drazozo]  Error occurred while generating a user list from the followed pool!
        b"[Errno 2] No such file or directory: 'C:\\\\Users\\\\mrmet\\\\InstaPy\\\\logs\\\\drazozo\\\\drazozo_followedPool.csv'"
INFO [2019-03-30 18:12:49] [drazozo]  There are less users to unfollow than you have requested:  1176/5000  ~using available amount

INFO [2019-03-30 18:12:49] [drazozo]  Unfollowing the users followed by InstaPy

INFO [2019-03-30 18:12:49] [drazozo]  Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 0

INFO [2019-03-30 18:12:49] [drazozo]  There are no any users available to unfollow
INFO [2019-03-30 18:12:49] [drazozo]  --> Total people unfollowed : 0


INFO [2019-03-30 18:12:52] [drazozo]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 1176 users & had 1377 FOLLOWERS
[Session lasted 1.89 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-03-30 18:12:52] [drazozo]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by rafaelrpg** [comment]
Same here. Happens when `session.unfollow_users(..., allFollowing=True)`.

However, there's no error when `session.unfollow_users(..., nonFollowers=True)`.
