### ISSUE TITLE
Unfollowing flow breaks on deleted / renamed account

### ISSUE THREAD

**Issue by m-malkowski** [InstaPy/InstaPy#2898]
## Expected Behavior
If user changed the name - try to find by id
## Current Behavior
I followed the steps executed - 
1. Bot goes to account profile page
2. Navigate to profile to unfollow -> Page unavaiable
3. Navigates to another page -> login prompt displayed (and user is now logged out)
4. Goes to next user to unfollow page, detects that its not followed (as I'm no longer logged in)
5. Removes user from the followed list without actually interacting with them.

Log says that it checked if I'm logged in, but obviously it did not work:
```
INFO [2018-09-11 17:42:55] [user]  Ongoing Unfollow [1/74]: now unfollowing 'b'antonellaputignani''...
ERROR [2018-09-11 17:42:57] [user]  --> Unfollow issue with 'b'antonellaputignani''!      ~unable to detect the following status
INFO [2018-09-11 17:42:57] [user]  Pinging 'instagram.com' to check the connectivity...
PING instagram.com (34.207.2.165) 56(84) bytes of data.
64 bytes from * (*): icmp_seq=1 ttl=37 time=292 ms
--- instagram.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = */0.000 ms
INFO [2018-09-11 17:42:57] [user]  Checking if 'user' is logged in...
WARNING [2018-09-11 17:43:00] [user]  Maybe 'b'antonellaputignani'' has changed the username!     ~verifying through the user ID
ERROR [2018-09-11 17:43:03] [user]  --> Unfollow issue with 'b'antonellaputignani''!      ~unable to detect the following status
WARNING [2018-09-11 17:43:03] [user]  --> Couldn't access the profile page of 'b'antonellaputignani''!    ~user has either closed the profile or blocked you
INFO [2018-09-11 17:43:03] [user]         Removed '2018-09-09 07:36 ~ antonellaputignani ~ 424598988' from followedPool.csv file
```
## InstaPy configuration
Just running
`unfollow_users(amount=100, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=48*60*60, sleep_delay=8*60)`
in docker container.

**Comment by sionking** [comment]
I don't understand what logged you out ?!

**Comment by sionking** [comment]
https://github.com/timgrossmann/InstaPy/issues/2900

**Comment by m-malkowski** [comment]
From observation I cannot tell what was the reason I got logged out, I land on login page form after between 2 profiles pages. Is there any option to enable more verbose logs?

**Comment by sionking** [comment]
I am not sure but I can guess using this method:
https://www.instagram.com/web/friendships/{}/follow/
can log you out, as it not a valid instagram url, I would have not use it.

**Comment by rodriguesprobr** [comment]
Same issue here!

```
s.unfollow_users(\
        amount = unfollowAmountRandom,\
        InstapyFollowed = (True, "all"),\
        style = 'FIFO'\
    )
```
Results in:

INFO [2018-09-12 15:26:39] [x]  Total 315 users available to unfollow  ~didn't pass `unfollow_after`: 0
INFO [2018-09-12 15:26:39] [x]  Ongoing Unfollow [1/10]: now unfollowing 'b'ahmadnurhadirmw''...
ERROR [2018-09-12 15:27:08] [x]  --> Unfollow issue with 'b'ahmadnurhadirmw''!	~unable to detect the following status
INFO [2018-09-12 15:27:08] [x]  Pinging 'instagram.com' to check the connectivity...
CRITICAL [2018-09-12 15:27:12] [x]  There is no connection to the 'instagram.com' server!
WARNING [2018-09-12 15:27:12] [x]  There is a serious issue: 'not connected'!	~leaving Unfollow-Users activity
INFO [2018-09-12 15:27:12] [x]  --> Total people unfollowed : 0

**Comment by clevebounce** [comment]
same issue as @rodriguesprobr
