### ISSUE TITLE
Account problem

### ISSUE THREAD

**Issue by blackdayy** [InstaPy/InstaPy#29]
I have two accounts. With one of them, it worked and I saw auto likes. When I try the other account, Invalid page message is displayed.  Both accounts are public and don't have special characters.

`Invalid Page: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//article/div[2]/div[1]/ul[1]/li[1]"}   (Session info: chrome=57.0.2987.133)   (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.4 x86_64)`

**Comment by timgrossmann** [comment]
Could you provide a link to the image on which the error appeared?

**Comment by timgrossmann** [comment]
Did you run them manually or from a server?

**Comment by blackdayy** [comment]
tag is: "vsco"

An image: https://www.instagram.com/p/BSgrKkjDddm/

One of account likes photos with the tag and the other one does not.

I run them manually. I guess it is about my acccounts?

**Comment by timgrossmann** [comment]
@blackdayy Do you run the script locally (via python3.5 quickstart.py)
or automated from a server?

**Comment by timgrossmann** [comment]
@blackdayy yes exactly, Instagram asks you if the account gets operated from a different location, so I thought this could be the problem...

I'll look into it...

Sorry for the problem

**Comment by timgrossmann** [comment]
@blackdayy  could you pull the newest version and try again, please?

**Comment by blackdayy** [comment]
@timgrossmann  Thank you, I will try it.

I checked also if there are differences between these accounts, but there is no any differences.

**Comment by blackdayy** [comment]
Tried with my acoount: now I see image link and description but error occurred again for all images.

[2/93]
Image from: the.purple.sock
Link: https://www.instagram.com/p/BSgpRBkFInp/?tagged=dog
Description: My cold, rocky interior . . . . 🌑🌚🌑 (follow @cosmoskyle @cosmoskyle 😂😂)
Invalid Page: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//article/div[2]/section[1]/a[1]/span[1]"}
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.4 x86_64)

**Comment by timgrossmann** [comment]
Hmm ok thank you...
I'll try to get that fixed

**Comment by eduardocalazansjr** [comment]
@blackdayy Take a look at #34, it should fix the problem
