### ISSUE TITLE
Constant Logging Out During Session

### ISSUE THREAD

**Issue by forgottensword** [InstaPy/InstaPy#2900]
Constant logging out of the session.

No Ban
No Unexpected Activity
Instagram is still logged into my Regular chrome browser than the one bot controlled one
But still it's getting constantly logged out for no reason.

**Comment by sionking** [comment]
REmove cookies and relogin

**Comment by forgottensword** [comment]
I'm working on it now. I'll update and close the issue if it works. ow please lend me some help @sionking

**Comment by sionking** [comment]
remove the cookie file from logs folder that is it

**Comment by forgottensword** [comment]
Thats didn't work out. I cleared cookies, logs, temporary files and did a system clean including caches.
Still the same issue

**Comment by forgottensword** [comment]
This issue still remains unchecked

**Comment by forgottensword** [comment]
Unfollow Instapy followed has this problem

**Comment by mateuspestana** [comment]
Same thing here, always logging out when unfollowing people. And then, when I try to log in again (using InstaPy), it says there is an issue with the cookie and it tries to create another, and there is no success on this action, so I need to delete the previous cookie and it creates a new one.
