### ISSUE TITLE
Unfollow terminating early/putting incorrect users in dont_include list

### ISSUE THREAD

**Issue by jeremycjang** [InstaPy/InstaPy#2903]
Been encountering this for a while and trying different bodges to fix it with no avail.
My program chains the following 3 actions (comments enabled)
```
session.follow_user_followers(['user1', 'user2'], amount125, randomize=False, interact=True, sleep_delay=600)
session.follow_user_followers(['user3', 'user4'], amount=100, randomize=False, interact=False, sleep_delay=600)
session.unfollow_users(amount=1000, InstapyFollowed = (True,"all"), style = 'FIFO', unfollow_after=None, sleep_delay=600)
```
After the two ```follow_user_followers``` actions complete, the unfollow program runs but ends early without unfollowing all 450 followed users. I've attempted adding a second ```unfollow_users``` action following the first one to pick up where the first session cuts off, but it sends up saying every user in the Followed list is in the `dont_include` list. 

I end up having to run a separate program that performs the ```unfollow``` action and even then, I don't think it successfully unfollows the users in the list before ending. Is this a known issue?

**Comment by EduardKov** [comment]
is there a session.set_blacklist in your config?

**Comment by jeremycjang** [comment]
@eduardkov there is; would that affect the unfollow?

**Comment by EduardKov** [comment]
this will work:
```
session.set_blacklist(enabled=False, campaign='soccer_campaign')
session.unfollow_users(amount=1000, InstapyFollowed = (True,"all"), style = 'FIFO', unfollow_after=None, sleep_delay=600)
###
session.set_blacklist(enabled=True, campaign='soccer_campaign')
session.follow_user_followers(['user1', 'user2'], amount125, randomize=False, interact=True, sleep_delay=600)
session.follow_user_followers(['user3', 'user4'], amount=100, randomize=False, interact=False, sleep_delay=600)
```

**Comment by EduardKov** [comment]
@CharlesCCC @uluQulu how to make sure that set_blacklist does not affect unfollow?

**Comment by uluQulu** [comment]
@eduardkov i wrote about it some where but if you explain what you want to achieve I can help much more

**Comment by EduardKov** [comment]
@uluQulu 
if configurable, for example:
```
session.set_blacklist(enabled=True, campaign='soccer_campaign')
session.follow_user_followers(['user1', 'user2'], amount=25, randomize=False, interact=True, sleep_delay=600)
time.sleep(1*60*60)
session.follow_user_followers(['user3', 'user4'], amount=10, randomize=False, interact=False, sleep_delay=600)
time.sleep(12*60*60)
session.unfollow_users(amount=50, InstapyFollowed = (True,"all"), style = 'FIFO', unfollow_after=None, sleep_delay=600)
time.sleep(12*60*60)
session.follow_user_followers(['user5', 'user6'], amount=25, randomize=False, interact=True, sleep_delay=600)
time.sleep(1*60*60)
session.follow_user_followers(['user7', 'user8'], amount=10, randomize=False, interact=False, sleep_delay=600)
time.sleep(12*60*60)
```
and so in the cycle...

in this case unfollow does not work
and the reason in set_blacklist (enabled = True) at the beginning

I do not understand why set_blacklist affects the function unfollow
in this case, is it necessary?

**Comment by jeremycjang** [comment]
@eduardkov does the blacklist have to first be set to false and does the unfollow action have to happen before the follow actions? I just tried

```
session.set_blacklist(enabled=True, campaign='soccer_campaign')
session.follow_user_followers(['user1', 'user2'], amount125, randomize=False, interact=True, sleep_delay=600)
session.follow_user_followers(['user3', 'user4'], amount=100, randomize=False, interact=False, sleep_delay=600)
session.set_blacklist(enabled=False, campaign='soccer_campaign')
session.unfollow_users(amount=1000, InstapyFollowed = (True,"all"), style = 'FIFO', unfollow_after=None, sleep_delay=600)
```
And though more users were unfollowed than before, the program still ended the unfollow process early with no explanations

**Comment by jeremycjang** [comment]
@uluqulu what I’m trying to achieve used to work before but stopped working fully somewhere after updates a few months ago

Goal:

InstaPy follows a bunch of users/interacts with them and adds them to a blacklist, then once all the follow actions are completed it unfollows all of them that were followed during the session (aka followed by InstaPy)

Current:

InstaPy follows a bunch of users/interacts with them and adds them to a blacklist, then once all the follow actions are completed it unfollows some of them that were followed during the session then ends the program without explanation.

Last session 390 users were followed, my `FollowedPool.csv` had 810 names accumulated from times the program stopped unfollowing early, 375 users were unfollowed before the program ended and it looks like the program read several users as in the `dont_include` list but I have never specified anyone in that list.
