### ISSUE TITLE
interact_user_following : Failed to load desired amount of users!

### ISSUE THREAD

**Issue by sammierlening** [InstaPy/InstaPy#2906]
## Expected Behavior
I am trying to interact with the users that I am following, but It is saying failed to load desired amount of users. If I am logging in as myself, and interacting with my own following, how is that possible.

## Current Behavior
INFO [2018-09-12 11:13:37] [gunnerdoyle]  Session started!
INFO [2018-09-12 11:13:47] [gunnerdoyle]  Logged in successfully!
INFO [2018-09-12 11:13:50] [gunnerdoyle]  User 'gunnerdoyle' [1/1]
INFO [2018-09-12 11:13:56] [gunnerdoyle]  Failed to load desired amount of users!

INFO [2018-09-12 11:13:56] [gunnerdoyle]  Grabbed 0 usernames from 'gunnerdoyle's `Following` to do interaction.
INFO [2018-09-12 11:13:56] [gunnerdoyle]  Finished interacting 0 people from 1 users' `Following`! xD

INFO [2018-09-12 11:13:56] [gunnerdoyle]  Liked: 0
INFO [2018-09-12 11:13:56] [gunnerdoyle]  Already Liked: 0
INFO [2018-09-12 11:13:56] [gunnerdoyle]  Commented: 0
INFO [2018-09-12 11:13:56] [gunnerdoyle]  Followed: 0
INFO [2018-09-12 11:13:56] [gunnerdoyle]  Inappropriate: 0
INFO [2018-09-12 11:13:56] [gunnerdoyle]  Not valid users: 0

INFO [2018-09-12 11:13:56] [gunnerdoyle]  Sessional Live Report:
        |> LIKED 0 images  |  ALREADY LIKED: 0
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0
currently FOLLOWING 882 users & has got 42226 FOLLOWERS

## InstaPy configuration
from instapy import InstaPy

insta_username = 'gunnerdoyle'
insta_password = 'REMOVED'

bot = InstaPy(username=insta_username, password=insta_password, selenium_local_session=False)
bot.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub')
bot.login()

bot.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
bot.set_do_follow(enabled=True, percentage=70)
bot.set_do_like(enabled=True, percentage=70)
bot.set_comments(["#gunnerApproved"])
bot.set_do_comment(enabled=True, percentage=80)
bot.interact_user_following(['gunnerdoyle'], amount=10, randomize=True)

bot.end()

**Comment by S4nderr** [comment]
Got the same problem, any fix yet?

**Comment by gitpatrickhub** [comment]
Try adding;
```
session.set_simulation(enabled=False)
```

I still get the error, but it pulls ~30 users and runs with that. Better than not running at all for now.

**Comment by gitpatrickhub** [comment]
Anyone else still having this problem? I just did another git pull, but problem persists.

**Comment by gitpatrickhub** [comment]
Issue appears to be the same as #2989 although that issue was closed without providing the actual solution. For some accounts, when scrolling the list of an accounts Followers, the user is prompted with button for "See all suggestions'. When clicked, it takes the user to a different page. It appears to be an A|B test by Instagram, as I'm only seeing it on certain accounts.
