### ISSUE TITLE
Problem with hashtag caracter

### ISSUE THREAD

**Issue by rosartori** [InstaPy/InstaPy#291]
Hi, the script is running OK, but i'm using a Brazilian hashtag with "ç"!
I can't resolve the problem.... :(

When I run quickstart.py I get the following error:

Traceback (most recent call last):
  File "quickstart.py", line 19, in <module>
    .like_by_tags(['laçoemdupla', 'madeinroça', 'bruto', 'cowboy', 'country'], amount=50)\
  File "/Users/rodrigo/InstaPy/instapy/instapy.py", line 362, in like_by_tags
    print('--> {}'.format(tag.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)

**Comment by timgrossmann** [comment]
@rosartori Where are you running the script? 
local machine, server?

Do you have the latest version?

**Comment by rosartori** [comment]
in my MacbookPro - MacOS Sierra with the latest version

**Comment by rosartori** [comment]
Any help?

**Comment by timgrossmann** [comment]
@rosartori I'm sorry... Can't help you right now.
I'll leave this open so maybe someone else that faced the same problem has an answer.

**Comment by hojabbr** [comment]
Just add these lines to `quickstart.py` and `instapy.py`:

```
# -*- coding: UTF-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```
