### ISSUE TITLE
Shadow ban?

### ISSUE THREAD

**Issue by dbmathis** [InstaPy/InstaPy#2910]
## Expected Behavior
All 60 specified to be unfollowed

## Current Behavior
INFO [2018-09-12 12:17:45] [xx]  Ongoing Unfollow [11/58]: now unfollowing 'user1'...
WARNING [2018-09-12 12:17:55] [xx]  --> Unfollow error!	~username 'xx' might be
+blocked from unfollowing

WARNING [2018-09-12 12:17:55] [xx]  There is a serious issue: 'shadow ban'!   ~leaving Unfollow-Users
+activity
INFO [2018-09-12 12:17:55] [x]  --> Total people unfollowed : 10

## Possible Solution (optional)
Anyone else experiencing this? I have seen this for the last few days.

## InstaPy configuration
session.unfollow_users(amount=60, InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=24*60*60, sleep_delay=300)

**Comment by alxhoff** [comment]
+1

**Comment by sionking** [comment]
You maybe blocked from unfollowing, now we verify unfollowing.

**Comment by ghost** [comment]
You could be blocked from unfollowing... 60 at a time is not ridiculous, but after a 'busy day' consisting several other actions might very well have pushed you over the threshold.

You also might be experiencing problems related to issue #2882 for which there is already a fix waiting to be merged: #2901 

For me personally, the issue was fixed by simply extending the `sleep(4)` commands in `unfollow()` in `unfollow_util.py`. I changed them all to `sleep(30)` and I haven't had a problem since then.

**Comment by dbmathis** [comment]
I’m going it run it in the foreground in a bit and see if I’m actually being banned. I’ve been running Instapy for months at the same pace and this is the first I’ve seen this happen.

**Comment by dbmathis** [comment]
Looking good for the last 2 runs. Will keep an eye out for the warning again and then pull just in case it's related to the other issue mentioned.

**Comment by fgisslen** [comment]
I also get this problem, I'm not acctually shadow banned but instapy think so

**Comment by rodriguesprobr** [comment]
Same problem here.

**Comment by CTZNkjs** [comment]
try updating chromedriver as well

**Comment by karaan** [comment]
Unable to install Instapy in Windows from the steps mentioned on the site

**Comment by CTZNkjs** [comment]
update from last comment-

I'm still getting error. Chromedriver did not fix for me after running some time. Updating chromedriver doesn't hurt though. New update was released 9/13/18

**Comment by fgisslen** [comment]
#2901 fixes the problem

**Comment by dbmathis** [comment]
Has it been merged in?

**Comment by fgisslen** [comment]
No but you can add it yourself
