### ISSUE TITLE
Instagram blocking

### ISSUE THREAD

**Issue by AvocadoStyle** [InstaPy/InstaPy#2914]
Hey, i'm using this code:

>     session.follow_user_followers(['adirbriga7', 'or_shahar21'], amount=500, randomize=True, sleep_delay=60)
and the instagram is blocking me from doing following to people because it's saying the activity has been blocked because too many requests sent.

i'm trying to make the following action to be more slowly, but i dont know how to.

Thanks!

**Comment by JoeFertig** [comment]
IMO your settings are way too high. You follow 1000 people everytime you run the script. I follow 150 per day which is much more safe.

**Comment by AvocadoStyle** [comment]
> 
> try:
>     session.login()
> 
>     # settings
>     session.set_relationship_bounds(enabled=True,
> 				 potency_ratio=-0.03,
> 				  delimit_by_numbers=True,
> 				   max_followers=4590,
> 				    max_following=6555,
> 				     min_followers=45,
> 				      min_following=77)
>     session.set_simulation(enabled=False)
> 
>     session.follow_user_followers(['adirbriga7', 'or_shahar21'], amount=500, randomize=True, sleep_delay=400)
> 
> except Exception as exc:
>     # if changes to IG layout, upload the file to help us locate the change
>     if isinstance(exc, NoSuchElementException):
>         file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
>         with open(file_path, 'wb') as fp:
>             fp.write(session.browser.page_source.encode('utf8'))
>         print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
>             '*' * 70, file_path))
>     # full stacktrace when raising Github issue
>     raise
> 
> finally:
>     # end the bot session
>     session.end()
>     # time.sleep(5000)
>     time.sleep(1000)
>     os.system("quickstart.py")

this is my script, every time that it's fails or quite or ends it's starting again after 1000 seconds with os.system.
The only thing i want is to follow people more slowly, that it will start every time again for 24/7 but more slowly than it is right now.
how can i do it?

**Comment by jeremycjang** [comment]
`sleep_delay` adds break time in between to stay at IG’s follow limits; right now yours is set to 60 which means the program will wait around 1 minute every 10 or so follows before continuing. You should set the `sleep_delay` parameter to 600 (10 mins) or more because the rate is about 60 follows/hour 

Hope that helps!

**Comment by AvocadoStyle** [comment]
> `sleep_delay` adds break time in between to stay at IG’s follow limits; right now yours is set to 60 which means the program will wait around 1 minute every 10 or so follows before continuing. You should set the `sleep_delay` parameter to 600 (10 mins) or more because the rate is about 60 follows/hour
> 
> Hope that helps!

I will try it when my block will end, thanks!
