### ISSUE TITLE
Follow user Followers - blocked after few follows

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#2915]
Hello i get this problem since few weeks, each time i follow user followers, after few follows its can't follow anymore, like if i am blocked (but i can follow from my phone), i have to change my ip to work again. the sleep delay is very high though; in the terminal it shows that it follows but in reality there is no follow 

any one please ?

**Comment by sionking** [comment]
blocked ip

**Comment by Edhim** [comment]
@sionking  but each time after 10 follows
