### ISSUE TITLE
sqlite3.OperationalError: attempt to write a readonly database`

### ISSUE THREAD

**Issue by taibhse-designs** [InstaPy/InstaPy#2916]
This is the Error Traceback thats happening at the moment, 

`Traceback (most recent call last):
  File "G:\Users\user\Portable Programs\InstaPy-master\quickstart.py", line 135, in <module>
    session.like_by_tags(hashtags, amount=len(hashtags)+3)
  File "G:\Users\user\Portable Programs\InstaPy-master\instapy\instapy.py", line 1480, in like_by_tags
    self.logger)
  File "G:\Users\user\Portable Programs\InstaPy-master\instapy\util.py", line 113, in validate_username
    followers_count, following_count = get_relationship_counts(browser, username, logger)
  File "G:\Users\user\Portable Programs\InstaPy-master\instapy\util.py", line 566, in get_relationship_counts
    web_address_navigator(browser, user_link)
  File "G:\Users\user\Portable Programs\InstaPy-master\instapy\util.py", line 660, in web_address_navigator
    update_activity()
  File "G:\Users\user\Portable Programs\InstaPy-master\instapy\util.py", line 214, in update_activity
    data['unfollows'], data['server_calls'], id))
sqlite3.OperationalError: attempt to write a readonly database`

Here is my Quickstart script at the moment, 

`
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = "username"
insta_password = "password"

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=0.95,
				  delimit_by_numbers=True,
				   max_followers=50000,
				    max_following=10000,
				     min_followers=100,
				      min_following=25)

    #set max quotas to match being human (first param is per hour | second param is per day
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=False,
                              peak_likes=(30, 300),
                               peak_comments=(27, 127),
                                peak_follows=(47, 200),
                                 peak_unfollows=(15, 150),
                                  peak_server_calls=(None, 3000))

    #set percentage of posts to comment on
    session.set_do_comment(True, percentage=2)

    #generic comments to use on posts
    session.set_comments(['This is pretty cool :)',
                          u':red_heart: from :Ireland:',
                          u':heart_eyes: :heart_eyes: :heart_eyes:',
                          u':heart_eyes: :heart_eyes:',
                          u':heart_eyes:',
                          u':fire: :fire: :fire: :fire: :fire:',
                          u':fire: :fire: :fire:',
                          u':fire:'])
    
    #photo only comments / tag user
    session.set_comments(['Nice! @{}'], media='Photo')

    #exclusion list of users not to comment on or unfollow
    session.set_dont_include(['user1', 'user2', 'user3'])  #real userlist redacted for their privacy

    #dont comment on any posts with less than 5 comments already
    session.set_delimit_commenting(enabled=True, max=None, min=5)

    #dont like any post using any of the following in any given tag
    session.set_dont_like(['nsfw',
                           'instaadult',
                           'instansfw',
                           'instagramnsfw',
                           'instawoman',
                           'instafun',
                           'sex',
                           'porn',
                           'pr0n',
                           'xxx',
                           'furry',
                           'uber',
                           'lyft',
                           'thot',
                           ])

    #dont like posts that have more than 3000 likes or less than 5
    session.set_delimit_liking(enabled=True, max=3000, min=2)

    #list of hashtags to use to find posts
    hashtags = ['tag1', 'tag2', 'tag3'] #longer list of tags, in use, reduced for posting
    
    # Like posts based on hashtags
    session.like_by_tags(hashtags, amount=len(hashtags)+3)

    #generate smart list of hashtags from given ones to find posts to like
    session.set_smart_hashtags(hashtags, limit=len(hashtags)+3, sort='top', log_tags=True)

    #set interaction with new accounts followed, liking and commenting on their posts to entice follow back
    session.set_user_interact(amount=7, percentage=50, randomize=True, media='Photo')
    
    #follow given percentage of users whose posts are interacted with
    session.set_do_follow(enabled=True, percentage=23, times=2)

    # Prevents unfollow followers who have liked one of your latest 7 posts
    session.set_dont_unfollow_active_users(enabled=True, posts=7)
    
    #unfollow users instapy has followed after 7 days if they do not follow back
    session.unfollow_users(amount=60, InstapyFollowed=(True, "nonfollowers"), style="RANDOM", unfollow_after=168*60*60, sleep_delay=1200)

    

    # actions
    session.like_by_tags(amount=20, use_smart_hashtags=True) #like posts based on smart hashtags results

    #store followers records to local drive
    user_following = session.grab_following(username="user-name", amount="full", live_match=True, store_locally=True)

    #get record of those who have unfollowed and who have unfollowed while user is still following
    all_unfollowers, active_unfollowers = session.pick_unfollowers(username="user-name", compare_by="month", compare_track="first", live_match=True, store_locally=True, print_out=True)

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()`

**Comment by jeremycjang** [comment]
Check the official sqlite site to troubleshoot: 

https://www.sqlite.org/lockingv3.html
