### ISSUE TITLE
Remove "Description" from logging 

### ISSUE THREAD

**Issue by nbgabriel** [InstaPy/InstaPy#2922]
Hello there!

Can i remove the "Description:" field in logging? makes me confuse to read the log. I've look in the instapy.py but i did not found something (that i know, sure)

**INFO [2018-09-15 02:16:03] [myusername]  Description: Quetzalcoatl 
#mexicantattoo #mexican #culture #cultura #quetzalcoatl #skulltattoo #skull  #blackwork #black #inktattoo #inked #tattooart #tattoo #tatts #mexico #tatuajes #tatuadoresmexicanos #blackandgrey #original #onepiece #instaartist #instapic #instafood**

Thanks!

**Comment by sionking** [comment]
I did long timr ago but @timgrossmann  not like it.

**Comment by nbgabriel** [comment]
Oh, too bad. Do you remember how yo do it? 

Thanks @sionking!

**Comment by HCWcoder** [comment]
Yes i would like to know that trick too 
thanks.

**Comment by timgrossmann** [comment]
@nbgabriel @sionking I agree, it definitely bulges the log file. 
However, if you need to double check why your bot is liking weird stuff even though you "made sure" it has the right restrictions, it's very helpful to debug.

Maybe another optional thing for the Settings class? 😅

**Comment by nbgabriel** [comment]
> @nbgabriel @sionking I agree, it definitely bulges the log file.
> However, if you need to double check why your bot is liking weird stuff even though you "made sure" it has the right restrictions, it's very helpful to debug.
> 
> Maybe another optional thing for the Settings class?

Tim, hello!, first, thanks for this work, it's awesome. 

The bot is working fine, but sometimes i want to see what the bot is doing, and the Description field sometimes is anoying, all the people putting a long long long long long long long long description, with lots of dots, and.........  pffff exhausting. Its only visual, not for debug, But if It couldn't be done, no problem at all. Thanks!

**Comment by HCWcoder** [comment]
@nbgabriel 

you can do it by add a comment to this line 👍 

![asd](https://user-images.githubusercontent.com/9588426/49752339-c723e300-fcb8-11e8-83e5-113dc37c5a75.JPG)


Edited:

you are right more clear now 👍 
![asdd](https://user-images.githubusercontent.com/9588426/49752768-03a40e80-fcba-11e8-819f-f218e5c626b6.JPG)
