### ISSUE TITLE
bot breaks on launch.

### ISSUE THREAD

**Issue by boldestfortune** [InstaPy/InstaPy#2928]
downloaded latest instapy master, ran script, I get this error in powershell

from plyer import notification
ModuleNotFoundError: No module named 'plyer'
(acct) PS C:\Users\user1\dev\acct\instapy> python loc3.py
Traceback (most recent call last):
File "loc3.py", line 7, in <module>
from instapy import InstaPy
File "C:\Users\user1\dev\acct\instapy\instapy\__init__.py", line 2, in <module>
from .instapy import InstaPy
File "C:\Users\user1\dev\acct\instapy\instapy\instapy.py", line 23, in <module>
from .comment_util import comment_image
File "C:\Users\user1\dev\acct\instapy\instapy\comment_util.py", line 7, in <module>
from .util import update_activity
File "C:\Users\user1\dev\acct\instapy\instapy\util.py", line 20, in <module>
from .quota_supervisor import quota_supervisor
File "C:\Users\user1\dev\acct\instapy\instapy\quota_supervisor.py", line 7, in <module>
from plyer import notification
ModuleNotFoundError: No module named 'plyer'

any ideas? I can post the files referenced if necessary.

Cheers.

**Comment by CTZNkjs** [comment]
run this in command terminal

"pip install plyer"

without quotations

**Comment by boldestfortune** [comment]
didn't realize there was something new to install. awesome thanks.

**Comment by callum8004** [comment]
tried this, tried uninstalling over and over @CTZNkjs and still no luck on raspberry pi

**Comment by aku6640** [comment]
install python 3 and try sudo python3 quickstart.py 
after that install the modules that are being asked. 
This worked for me on raspberry pi3

**Comment by CTZNkjs** [comment]
@callum8004 did @aku6640 direction work for you?

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)
