### ISSUE TITLE
Feed still stuck

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#2929]
The fix someone did here is not enogh
I will PR soon I hope:
`INFO [2018-09-16 01:45:15] [xxxxx]  Total of links feched for analysis: 1
INFO [2018-09-16 01:45:15] [xxxxx]  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2018-09-16 01:45:15] [xxxxx]  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2018-09-16 01:45:15] [xxxxx]  This link has already been visited: https://www.instagram.com/p/BnvqLnpH2222
INFO [2018-09-16 01:50:12] [xxxxx]  Total of links feched for analysis: 1
INFO [2018-09-16 01:50:12] [xxxxx]  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2018-09-16 01:50:12] [xxxxx]  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARNING [2018-09-16 01:50:12] [xxxxx]  Post Randomly Skipped...

INFO [2018-09-16 01:55:16] [xxxxx]  Total of links feched for analysis: 1
INFO [2018-09-16 01:55:16] [xxxxx]  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2018-09-16 01:55:16] [xxxxx]  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARNING [2018-09-16 01:55:16] [xxxxx]  Post Randomly Skipped...`

**Comment by kamilk91** [comment]
`.like_by_tags(['dog', '#cat'], amount=2) \`

try to set amount, f.e. 1000.

**Comment by sionking** [comment]
I do like by feed ...

**Comment by ghost** [comment]
like by feed is super stuck! @sionking - also experiencing this.

**Comment by ghost** [comment]
In particular for all above -- it's the like by feed function that is out of wack.

**Comment by halalfood** [comment]
if anyone has time to take a look at this, would be greatly appreciated as its a core function i use  @uluQulu @sionking 

@timgrossmann maybe mark as bug?

**Comment by ghost** [comment]
@sionking or @uluQulu - if you have anytime to check this out 

like_by_feed function is not working still. @timgrossmann maybe mark as a bug?

`session.like_by_feed(amount=random.randint(250, 500), randomize=True, unfollow=True, interact=True)`

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/3760127/45992340-48bf8980-c057-11e8-918c-d6b5468449fd.png)

I'm not sure if it has anything to do with this annoying pop-up that comes up every single time the bot is started on the feed

**Comment by uluQulu** [comment]
Hi Mohammad,

**1**-) **add** this function to the _end_ of your **login_util.py** file
```python
def dismiss_notification_offer(browser, logger):
    """ Dismiss 'Turn on Notifications' offer on session start """
    offer_elem_loc = "//div/h2[text()='Turn on Notifications']"
    dismiss_elem_loc = "//button[text()='Not Now']"

    # wait a bit and see if the 'Turn on Notifications' offer rises up
    offer_loaded = explicit_wait(browser, "VOEL", [offer_elem_loc, "XPath"], logger, 4, False)

    if offer_loaded:
        dismiss_elem = browser.find_element_by_xpath(dismiss_elem_loc)
        click_element(browser, dismiss_elem)
```

**2**-) **add** this line _after_ `dismiss_get_app_offer(browser, logger)` line
```python
    dismiss_get_app_offer(browser, logger)
    dismiss_notification_offer(browser, logger)   # ADD THIS NEW LINE HERE
```
_This addition will dismiss the "Turn on Notifications" offer after just logging in by credentials_.

**3**-) **add** this line _to_ the `if len(login_elem) == 0` _statement_
```python
    if len(login_elem) == 0:
        dismiss_notification_offer(browser, logger)   # ADD  THIS NEW LINE HERE
        return True
```
_This addition will dismiss the "Turn on Notifications" offer after logging in by a cookie_.

----

Cheers 😁
----

**Comment by K3ub** [comment]
Thanks uluQulu! It worked for me

**Comment by ghost** [comment]
@K3ub @uluQulu @sionking after the latest merge for some reason i am still seeing this issue happen when using like by feed function. the popup still remains and I can't figure out why. are you seeing the same thing? I have the latest master and the only different file is my quickstart file

**Comment by syond** [comment]
> dismiss_notification_offer(browser, logger) # ADD THIS NEW LINE HERE

i just putted this line in the code and WORKED!! 

Thank you!

**Comment by K3ub** [comment]
@halalfood I have the latest master and the function now works perfectly for me

**Comment by ghost** [comment]
hmm okay i will try again @K3ub
