### ISSUE TITLE
How to launch terminal? HEELLLPPP

### ISSUE THREAD

**Issue by guigui739** [InstaPy/InstaPy#2932]
Hello,

Is there any document or video how to set the terminal. 

I have download everything in a proper way but i am not able to call the folders in order to open the bot. 

I do the following : 

Last login: Fri Sep 14 08:58:47 on ttys001
MacBook-Pro-de-Guillaume:~ guillaume$ 
MacBook-Pro-de-Guillaume:~ guillaume$ cd desktop
MacBook-Pro-de-Guillaume:desktop guillaume$ cd bot

I AM MISSING THE THIRD LINE  TO MAKE the bot open. Please someone can help?

<img width="432" alt="capture d ecran 2018-09-16 a 11 00 37" src="https://user-images.githubusercontent.com/43263344/45594732-c290ac80-b99f-11e8-90b0-f6cb8149a540.png">

<img width="726" alt="capture d ecran 2018-09-16 a 11 02 26" src="https://user-images.githubusercontent.com/43263344/45594744-07b4de80-b9a0-11e8-9826-1234e9f60653.png">

**Comment by kamilk91** [comment]
what exactly you want to do?

**Comment by ghost** [comment]
Guillaume, `quickstart.py` runs in python. That means that from the command line you have to run

`python quickstart.py`

...in order to run the script `quickstart.py` in python.

What do you mean "call the folders"? What are you trying to do?
