### ISSUE TITLE
Feature Request: Mandatory words in Bio

### ISSUE THREAD

**Issue by gS32tom** [InstaPy/InstaPy#2934]
Let's say you want to get new followers that are really relevant to you. Maybe you want them to be from the same hometown or interested in the same things as you.
In the past I achieved this by following the followers of a competitor. This competitor seems to have bought some followers, so those aren't relevant to me, but InstaPy still interacts with them.

I propose a mandatory words in bio function. That way InstaPy is able to ignore users that are not relevant because they didn't mention the right word in their bio.
I understand that this will weed out many users that are relevant but didn't include that specific word in their bio, but I think it's a great way to make sure to interact only with the most relevant users.

**Comment by sionking** [comment]
It will filter too much in my opinion

**Comment by Nuzzo235** [comment]
@gS32tom checking bio is highly desired, there has been some ideas in the past #2333 and #2242
