### ISSUE TITLE
Raspberry PI bug

### ISSUE THREAD

**Issue by ikbenignace** [InstaPy/InstaPy#2942]
During the install I run pip install . for the raspberry pi lite installation and I got this:

The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7ls7fN/Pillow/setup.py", line 807, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7ls7fN/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ZBq23C-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-7ls7fN/Pillow/

**Comment by waltermazzariol** [comment]
Hey, you need to run the following command: 

`sudo apt-get install libjpeg-dev`

after that you need to excecute 

`pip install pillow`

it worked for me
