### ISSUE TITLE
Cor did you send to many requests!

### ISSUE THREAD

**Issue by supmag** [InstaPy/InstaPy#2944]
## Expected Behavior
The bot should work for hours continuously, I have posted about this issue multiple times but no one has really committed to getting to the root of this issue, I have done a complete clean install of the script and the error is still persisting.
## Current Behavior
The error occurs after about 30 minutes of running the bot
cor did you send too many requests
## Possible Solution (optional)
I have tried to lower the requests to just two hashtags and a few likes and the error still occurs :/
## InstaPy configuration
try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.50,
				  delimit_by_numbers=True,
				   max_followers=1000,
				    max_following=2000,
				     min_followers=45,
				      min_following=50)
    session.set_do_follow(enabled=True, percentage=30, times=2)

    session.set_do_comment(enabled=True, percentage=25)
    session.set_comments(['@{}Rock on devil!', '@{}Dark I like it', '@{}Steet! loving it!', '@{}I like this one, actually...', '@{} I wanted to say something nice...im lost for words', '@{} Maybe I should cut my dreads now', '@{}THE DEMON WITHIN', '@{} liking the cyber feel!', '@{} another day another wolf!', '@{} I know nothing and im not even johnsnow...niceone!', '@{} Now this is what I call art!', '@{}someone did the right thing here!'])
    
	# actions
    session.like_by_tags(['666', 'photography', 'darkart', 'model', 'streetstyle', 'trap', 'moodygrams', 'evil', 'goth', 'hell', 'occult', 'xxxtentacion', 'ghostmane', 'scarlxrd', 'grunge', 'numb', 'lilpump', 'demon', 'gothfashion', 'streetgoth', 'cyberpunk', 'cybergoth', 'killer', 'lookatme', 'wolf', 'sad', 'hathred'], amount=50, media='Photo')
    
    
	
except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

**Comment by nazariyv** [comment]
I have it as soon as I start the liking by tags part. I have reduced the default sleep time of `600` in the `instapy/like_util.py` file (When it says this Cor blah blah part), but then I get a message that my tag may not have enough images, which is not true and then proceeds to like less images than I initially intended. It usually calculates that about 20 images to like is enough for me. It feels like this part of the code is buggy.
