### ISSUE TITLE
Unfollow the users WHO was followed by InstaPy doesn't work

### ISSUE THREAD

**Issue by imkimchi** [InstaPy/InstaPy#2945]
I follow users by the following code

```
session = InstaPy(username=instaUser[index], password=instaPass[index], headless_browser=True, nogui=True)
session.login()
session.set_relationship_bounds(enabled=True, potency_ratio=None,delimit_by_numbers=True)
session.set_user_interact(amount=2, randomize=True, percentage=100)
session.set_dont_like(blackWords)
session.set_do_like(enabled=True, percentage=100)
session.set_do_follow(enabled=True, percentage=4)
session.like_by_tags(forFollowers, amount=10, interact=True)
```

and when I try to unfollow users who was followed by instapy using
`session.unfollow_users(amount=200, nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)`

It doesn't find any user so doesn't work at all..

**Comment by FarkasLabs** [comment]
I'm having the same problem, could you check your youraccountname_followedPool.csv file in your logs folder? In my case all of the data disappears somehow, the oldest followed person is from 2 days ago (which is obviously not true) so my unfollow command (correctly) doesn't find any people to unfollow... the question is why do they get removed?

**Comment by cyberpz** [comment]
It works guys! Some fixes have been made to the source. If any error appears, open an issue.
