### ISSUE TITLE
Grab Following Users

### ISSUE THREAD

**Issue by nbgabriel** [InstaPy/InstaPy#2948]
Hello there!

I'm having a trouble, i do not know how to configure the option to get a list of the people that i follow, i try in these way, and did not work:
* MyUser_following = session.grab_following(username="MyUser", amount="full", live_match=True, store_locally=True)
* grab_following(username="MyUser", amount="full", live_match=True, store_locally=True)
* session.grab_following(username='MyUser', amount="full", live_match=True, store_locally=True)

In the 3 options, the error is something like:
  File "quickstart.py", line 48
    session.grab_following(username='MyUser', amount="full", live_match=True, store_locally=True)
    ^
IndentationError: unexpected indent
^C

P.S.: I search this here, in issues, but i did not find something usefull.

**Comment by Nuzzo235** [comment]
First version should work, remember to do interact with the given list of users, e.g.

```
lazySmurf_following = session.grab_following(username="lazy.smurf", amount="full", live_match=True, store_locally=True)
session.set_do_like(True, percentage=100)
session.set_user_interact(amount=random.randint(4,6), percentage=100, randomize=True, media='Photo')
session.follow_by_list(followlist=lazySmurf_following, times=1, sleep_delay=600, interact=True)
```

otherwise the list will just be saved as *..json into your logs folder, `~/InstaPy/logs/YourOwnUsername/relationship_data/lazy.smurf/following/` directory.

**Comment by nbgabriel** [comment]
Nuzzo, thanks for the reply.

I must doing something wrong, im putting this code in quickstart.py, in the #actions sections:
_MyUser_following = session.grab_following(username="MyUser", amount="full", live_match=True, store_locally=True)
session.set_do_like(True, percentage=100)
session.set_user_interact(amount=random.randint(4,6), percentage=100, randomize=True, media='Photo')
session.follow_by_list(followlist=MyUser_following, times=1, sleep_delay=600, interact=True)_

But still:
  _File "quickstart.py", line 41
    MyUser_following = session.grab_following(username="MyUser", amount="full", live_match=True, store_locally=True)
                      ^_

Thanks for the help.

**Comment by Nuzzo235** [comment]
Weird, one last (quick) try: If you use a dot in the username (e.g. "My.User") you have to remove it from the listname:

`MyUser_following = session.grab_following(username="My.User", amount="full", live_match=True, store_locally=True)`

**Comment by nbgabriel** [comment]
> Weird, one last (quick) try: If you use a dot in the username (e.g. "My.User") you have to remove it from the listname:
> 
> `MyUser_following = session.grab_following(username="My.User", amount="full", live_match=True, store_locally=True)`

Nuzzo!, nope, my user does not have a dot. Thanks!

**Comment by uluQulu** [comment]
@Nuzzo235 nice review 🎉
@nbgabriel 
>IndentationError: unexpected indent

Make sure you have indented lines properly.


List name can be anything [acceptable as a variable `name` in python], @Nuzzo235 

Also, @nbgabriel,
```python
# `MyUser_following` holds the 'Following' data of the user- "MyUser" AND with `store_locally=True` parameter it saved a copy of the data into a local file in your logs folder
MyUser_following = session.grab_following(username="MyUser", amount="full", live_match=True, store_locally=True)

# WRONG statement [considering you are running it inside Quickstart script]
grab_following(username="MyUser", amount="full", live_match=True, store_locally=True)

# TRUE statement but you are not using the return value THAT'S WHY it will just save a local copy cos `store_locally` parameter is `True`
session.grab_following(username='MyUser', amount="full", live_match=True, store_locally=True)
```
Above is basic python. Make sure you have read the documentation WHICH has all of the answers to your questions including the examples.

>But still:
File "quickstart.py", line 41
MyUser_following = session.grab_following(username="MyUser", amount="full", live_match=True, store_locally=True)
^

Post the full traceback while raising an issue in order to help us understand your problem.

---

Cheers 😁😁
----

**Comment by nbgabriel** [comment]
uluQulu, i dont know why, but now is working, now i see the three folders:
$ ls -c1 /home/user/Downloads/InstaPy/logs/myuser/relationship_data/myuser/
nonfollowers
following
followers

Before, i only see the "followers". 

Thanks all for the help!

**Comment by uluQulu** [comment]
Welcome, @nbgabriel 🙂

It is gonna be generated out of your usage.
+ If you have grabbed or picked any relationship data with the `store_locally` parameter being `True` then there should be that file
+ OR if you have used unfollow method `nonFollowers`, you could see both _followers_, _following_ and _nonfollowers_ folders with the data in them
OR if used `InstapyFollowed` and `customList` with "_nonfollowers_" track, then you could see _followers_ data in there

All that information is written in the README.

---

Cheers 😁
---

**Comment by nbgabriel** [comment]
uluQulu... oh is not magic! i did not read the readme, clearly. (RTFM :D )

In my case, is the option 2, method nonFollowers. I just enable that, thanks!.

I promess that i will read the README. 

Thanks a lot
