### ISSUE TITLE
"CRITICAL - There is no connection to the 'instagram.com' server!" Only on unfollow function

### ISSUE THREAD

**Issue by pagokrat0r** [InstaPy/InstaPy#2951]
I haven't mess with any file, i ve been running the same config for days.
Since this morning that's all I'm getting when trying to unfollow.

```
INFO [2018-09-19 02:56:42] [*****]  Ongoing Unfollow [1/800]: now unfollowing 'b'*****''...
ERROR [2018-09-19 02:57:10] [*****]  --> Unfollow issue with 'b'*****''!	~unable to detect the following status
INFO [2018-09-19 02:57:10] [*****]  Pinging 'instagram.com' to check the connectivity...
CRITICAL [2018-09-19 02:57:14] [*****]  There is no connection to the 'instagram.com' server!
WARNING [2018-09-19 02:57:14] [*****]  There is a serious issue: 'not connected'!	~leaving Unfollow-Users activity
INFO [2018-09-19 02:57:14] [*****]  --> Total people unfollowed : 0
```

**Comment by HelpImAnInstaAddict** [comment]
Bump on this. I'm having the exact same problem and I can't figure out why.

**Comment by converge** [comment]
I had this issue before, what fixed for me was:

1; navigate to other profiles
2; do some tag/people search for 1 or 2 minutes
3; try unfollowing again

**Comment by sionking** [comment]
@converge do you say that unfollowing so many in one time logged you out?

**Comment by converge** [comment]
@sionking not exactly. This issue is related to http not respoding for loading my profile following link to be able to unfollow who I´m following.

**Comment by ghost** [comment]
#2954 #2949 #2953 all same problem

**Comment by johnvfitness** [comment]
Hi Same problem

**Comment by sionking** [comment]
@converge  @uluQulu do we have a solution for this log out ?
Is it a real logged out or just a server not responding ?
I have old version and encourage none.

**Comment by pagokrat0r** [comment]
The program persists. Can someone verify this only occurs in Instapyfollowed method?
