### ISSUE TITLE
Unfollow not handling "Sorry, this page isn't available." and stops

### ISSUE THREAD

**Issue by GitNees** [InstaPy/InstaPy#2954]
## Expected Behavior
Detect page doesn't exist, remove user from list, go to next unfollow
## Current Behavior
Waits forever, then shows message it timed out waiting for a visual element and doesn't continue anymore.
This used to work on older versions (been more then a month I used it and just upgraded to newer version today and encountered this)
## Possible Solution (optional)
Detect if page isn't available at first before waiting for visual elements.

**Comment by GitNees** [comment]
This seems to be the problem:     # wait until the follow button is located and visible, then get it


def get_following_status(browser, person, logger):
    """ Verify if you are following the user in the loaded page """
    follow_button_XP = ("//button[text()='Following' or \
                                  text()='Requested' or \
                                  text()='Follow' or \
                                  text()='Follow Back']")

    # wait until the follow button is located and visible, then get it
    follow_button = explicit_wait(browser, "VOEL", [follow_button_XP, "XPath"], logger)


Not sure how this can be added to not wait the page contains "Sorry, this page isn't available"

**Comment by sionking** [comment]
I added a function to check unavailable pagr

**Comment by sionking** [comment]
@uluQulu can you please add this function before any other check:
```
def is_page_available(browser, logger):
    if "Page Not Found" in browser.title or "Content Unavailable" in browser.title:
        logger.warning('Intagram error: The link you followed may be broken, or the page may have been removed...')
        return False
    return True
```

**Comment by ghost** [comment]
hey @sionking if you put up a PR, i could test this for you

**Comment by sionking** [comment]
I will try but I am still not using the new module (my old one work perfectly for now)
