### ISSUE TITLE
Feature Request (Discussion): Unfollow users that were followed by InstaPy - only users who DO follow you

### ISSUE THREAD

**Issue by photogsy** [InstaPy/InstaPy#2963]
Since the point of this is to gain followers, I think it would make sense to be able to unfollow users that DID follow you back, since we can now stop interacting with that user.

This way, we can continue to interact with users that haven't followed back in the hope that doing so will encourage them to follow.

Once a user is following we can safely unfollow them.

Thoughts?

**Comment by uluQulu** [comment]
@photogsy 
I do not like the idea but will offer a solution to you.

**1**-) **add** a new track to `unfollow()` definition in the **unfollow_util.py** file,
```python
            if unfollow_track == "followers":
                all_followers = get_followers(browser,
                                               username,
                                                "full",
                                                 relationship_data,
                                                  False,
                                                   True,
                                                    logger,
                                                    logfolder)
                loyal_users = [user for user in unfollow_list if user in all_followers]
                logger.info("Found {} loyal followers!  ~will unfollow them :(".format(len(loyal_users)))
                unfollow_list = [user for user in unfollow_list if user in loyal_users]
```
Add it between the 
`if unfollow_track == "nonfollowers":`  and `elif unfollow_track != "all":` statements.

**2**-) **add** "_followers_" track into this statement in the same file,
`InstapyFollowed[1] in ["all", "nonfollowers"]`

**3**-) **start** unfollowing in the new track,
```python
session.unfollow_users(amount=70, InstapyFollowed=(True, "followers"), style="RANDOM", sleep_delay=450, unfollow_after=4*24*60*60)
```

----

Cheers 😁
-----

**Comment by photogsy** [comment]
Ok thanks, will have a tinker.
