### ISSUE TITLE
Following users in .json file

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#2964]
Hello,
I grabbed users, they are stocked in .json file 
How can i follow these users please ?

Thanks

**Comment by uluQulu** [comment]
Hi @Edhim 
It is easy than anything!
```python
import json

# select full path of the file
selected_file = "C:\Users\Edhim\Documents\GitHub\InstaPy\logs\Edhim\relationship_data\nancy_photography\followers\14-09-2018~full~7660.json"

# load that file
with open(selected_file) as followers_data_file:
    nancy_followers = json.load(followers_data_file)
```
Now `nancy_followers` is _list_ of the followers of the user- `nancy_photography`.

You can do whatever with it at this stage, e.g. follow the followers of her profile:
```python
session.follow_user_followers(usernames=nancy_followers, amount=10)
```

##### Pro: learn about `load_followers_data()` definition to auto-load any relationship data 😎
---

Cheers 😁
-----

**Comment by Edhim** [comment]
Thanks @uluQulu 

But i got this error :   

 liomet_followers = json.load(followers_data_file)
                  ^
IndentationError: expected an indented block


# select full path of the file
    selected_file = "/Users/Edhim/Desktop/INSTAPY/SAMAH/logs/samah89samah89/relationship_data/liomet_boutique/followers/20-09-2018\~full\~105822.json "

    # load that file
    with open(selected_file) as followers_data_file:
    liomet_followers = json.load(followers_data_file)


    # actions
    session.follow_user_followers(usernames=liomet_followers, amount=20, sleep_delay=240)

**Comment by uluQulu** [comment]
Welcome @Edhim 
It is just a full path of the file, I gave an example for Windows 😂 cos I have a one.
Yes, you should add it inside the **quickstart.py**.

---

Cheers 😁
------

**Comment by Edhim** [comment]
I am getting this error @uluQulu 

liomet_followers = json.load(followers_data_file)
^
IndentationError: expected an indented block

**Comment by uluQulu** [comment]
@Edhim,
_python_ is based on indentation, 

Attach your **quickstart.py** file in a zip [by removing personal information].
I will help you find the issue.

----

Cheers 😁
----

**Comment by Edhim** [comment]
Here you are @uluQulu 
[quickstart copie.py.zip]()


Thanks in advance :D

**Comment by uluQulu** [comment]
You've welcome, @Edhim 

Indent `liomet_followers = json.load(followers_data_file)` line `4` spaces forward

```python
    with open(selected_file) as followers_data_file:
        liomet_followers = json.load(followers_data_file)
```

----

Cheers 😁
---

**Comment by Edhim** [comment]
Big thanks @uluQulu  it worked :D

**Comment by uluQulu** [comment]
Sure, @Edhim 
[quickstart copie.zip](https://github.com/timgrossmann/InstaPy/files/2401750/quickstart.copie.zip)
Post full console output if something does not work as expected.

Also, make sure the full path of the JSON file is correct in `selected_file` variable.


-------

Cheers 😁
---
