### ISSUE TITLE
comment_util: ImportError: No module named emoji

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#297]
Hi,

I just updated InstaPy with `git reset --hard` and `git pull` and get now the following error:

```
Traceback (most recent call last):
  File "quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/InstaPy/instapy/instapy.py", line 11, in <module>
    from .comment_util import comment_image
  File "/InstaPy/instapy/comment_util.py", line 10, in <module>
    import emoji
ImportError: No module named emoji
```
Itried to `pip install emoji`, but the error persists. Do you have any idea how to fix this?

Until today I've used a weeks old version of InstaPy, so this is my first installation with the new emoji functionality (#272, #275).

I'm using CentOS.

**Comment by tibor** [comment]
I had to do the [following steps](https://pypi.python.org/pypi/emoji):

```
git clone https://github.com/carpedm20/emoji.git
cd emoji
python setup.py install
```

Now everything works.

**Comment by namhasiyosi** [comment]
if you use Python3 try this
pip3 install emoji
it worked for me

**Comment by jctommasi** [comment]
if you have only emoji unicode error:

`pip install unidecode`
