### ISSUE TITLE
Invalid Like Element!

### ISSUE THREAD

**Issue by dbmathis** [InstaPy/InstaPy#2972]
## Expected Behavior
Image to be liked

## Current Behavior
I pulled the latest yesterday.

My 8 AM run was fine today, but then the 1 PM run produced the following. There was also very slow execution of Instapy, 4 hours later it was still running  as opposed to the normal 1 - 2 hours. I ended up having to kill the process tree.

I get this for all images. 

INFO [2018-09-20 13:39:59] [xx]  --> Image was not able to get Liked! maybe blocked ?
INFO [2018-09-20 13:41:43] [xx]  --> Invalid Like Element!
INFO [2018-09-20 13:41:43] [xx]  [3/3]

## Possible Solution (optional)
None

## InstaPy configuration
```
import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = 'xx'
insta_password = 'xx'

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#Settings.database_location = '/xx/xx/InstaPy/db/instapy.db'
#Settings.chromedriver_location = '/xx/xx/InstaPy/assets/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
                 potency_ratio=None,
                  delimit_by_numbers=True,
                   max_followers=4590,
                    max_following=5555,
                     min_followers=10,
                      min_following=10)
    session.set_do_comment(True, percentage=10)
    session.set_comments(['Comments'])
    session.set_dont_include([''People here])
    session.set_dont_like(['pizza', 'girl', 'sex'])
    session.set_dont_unfollow_active_users(enabled=True, posts=3)
    # default enabled=False, follows ~ 10% of the users from the images, times=1
    # (only follows a user once (if unfollowed again))

    session.set_do_follow(enabled=True, percentage=50, times=2)

    #session.unfollow_users(amount=25, onlyInstapyFollowed=True, onlyInstapyMethod='FIFO', sleep_delay=600, unfollow_after=None)

    session.unfollow_users(amount=60, InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=24*60*60, sleep_delay=300)

    session.like_by_tags(['40 or so tags'], amount=3)

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()
```

**Comment by sionking** [comment]
you got liked blocked.
Image was not able to get Liked! maybe blocked ?
The invalid element is just another print. saying the unlike element is invalid == like blocked.

**Comment by dbmathis** [comment]
Wonderful. Based on my settings below, would you consider them to be too aggressive? I’ve been running these same settings for the past 7 months with no issues. The only thing that’s changed was the pull two days ago.

**Comment by dbmathis** [comment]
I run this 3 times daily every 5 hours.

**Comment by dbmathis** [comment]
What I have done is reduced the likes for cat to 1 and created more runs per day to keep likes under 60 per hour. Will see how that works.

**Comment by sionking** [comment]
The block check only added few commits ago, You should run only from residantial proxy.

**Comment by dbmathis** [comment]
Why?

**Comment by photogsy** [comment]
I started getting this error today as well.
However, if I open the same images in another browser window, I am able to like the image as expected... so it doesn't seem like I am 'like blocked'!

**Comment by dbmathis** [comment]
I thought a like block would be account specific, not IP. That's why I asked why above to the proxy question.

**Comment by photogsy** [comment]
Indeed - when I tried it manually I was at the same IP and obviously it was with the same account and it worked fine.

After I ended that session and started a new one, it has worked perfectly.

I think what is actually going on, is that the user is somehow being logged out and there isn't code to check for that scenario - since in that case, there would be a like button, but pressing it would not turn it into an 'unlike' button.

**Comment by dbmathis** [comment]
I  noticed something new in the Instapy output logs where it  was pinging the host. Not sure if it's always been there or if I just now ran into a scenario that activates the feature, but it did seem like Instapy thought there was a loss of connectivity a couple times. 

In any case, I spread my likes out across more jobs and have not seen any issues since.
