### ISSUE TITLE
Unfollow Issue

### ISSUE THREAD

**Issue by Wraitheye** [InstaPy/InstaPy#2975]
One of my accounts times out when running unfollow. I tried doing different settings (different version of the unfollow tool) in the hope of unlocking it with no success until now

## Expected Behavior
Run unfollow tool

## Current Behavior
Times ou on first unfollow, bot doesnt crash, just gets stuck

## Possible Solution (optional)
I removed the cookie to force it to create a new one in the hope that it would fix things.
Again i'm runnign 3 accounts, and the two others are doing fine.

## InstaPy configuration
Standard unfollow with the interract boundaries

**Comment by MelleNi** [comment]
Having similar issues. Tried it on multiple systems with multiple versions, but to no avail. Always freezes on first unfollow.
