### ISSUE TITLE
How to exit from: Last follow is not verified! ~smells of a shadow ban

### ISSUE THREAD

**Issue by tompicca** [InstaPy/InstaPy#2981]
My account is stucked at this warning:
`WARNING [2018-09-22 10:33:03] [user]  Last follow is not verified!    ~smells of a shadow ban`
The warning appears again even if I stop the bot and run it again.

Someone know how to exit from this impasse?

**Comment by naseefnazar** [comment]
Same here

**Comment by isaniomoraes** [comment]
Same here

**Comment by naseefnazar** [comment]
@tompicca Were you able to resolve it ?

**Comment by naseefnazar** [comment]
@uluQulu any idea about this?

**Comment by uluQulu** [comment]
Hi all
@naseefnazar 
**1**-) **update** your repository to the latest files;
**2**-) _open_ up **unfollow_util.py** file and _find_ `follow_user()` definition and there, _do_ this **modification** WHICH adds a **second attempt of follow** in case of it is not verified;
You will **replace** the  WHOLE code block **below** the
`# verify the last follow` line,
**until** `except NoSuchElementException:` line with this,
```python
            # verify the last follow   ## ALL OF THE LINES BELOW WILL BE REPLACED
            if not button_change:
                browser.execute_script("location.reload()")
                update_activity()
                sleep(2)

                # double check the following state
                following, follow_button = get_following_status(browser, track, user_name, logger)
                if following is None:
                    valid_page = is_page_available(browser, logger)
                    if valid_page:
                        sirens_wailing, emergency_state = emergency_exit(browser, user_name, logger)
                        if sirens_wailing == True:
                            logger.warning("There is a serious issue: '{}'!\n".format(emergency_state))
                            return False, emergency_state

                    if not valid_page or sirens_wailing == False:
                        logger.error("Unexpected failure happened after last follow!\n")
                        return False, "unexpected failure"

                if following == False:
                    # try to follow again
                    follow_button = browser.find_element_by_xpath(follow_xpath)
                    click_element(browser, follow_button)
                    # wait until it properly follows
                    button_change = explicit_wait(browser, "VOEL", [post_follow_element, "XPath"], logger, 9, False)

                    if not button_change:
                        # if the button still has not changed it can be a temporary block
                        logger.warning("--> Phew! Last follow is not verified."
                                            "\t~'{}' might be temporarily blocked from following\n"
                                                .format(username))
                        sleep(210)
                        return False, "temporary block"

                elif following in [True, "Requested"]:
                    logger.info("Last follow is verified after reloading the page!\n")


        except NoSuchElementException:   ## DO NOT CHANGE THIS LINE
```

Well, for some people, just pulling the latest files will solve the issue.
But that change in the 2nd step will solve all of the misbehaviours for everybody.

-----

Cheers 😁
---

**Comment by naseefnazar** [comment]
@uluQulu Thank you

**Comment by naseefnazar** [comment]
@uluQulu  have you made a PR for this ?

**Comment by uluQulu** [comment]
@naseefnazar 
Not yet.
First I will refactor the whole action verification block into a separate function and then make a clean PR.

-----

Cheers 😁
-------

**Comment by naseefnazar** [comment]
@uluQulu That's great , Looking forward for a solid PR!

**Comment by xiaomibrasil** [comment]
@uluQulu firstly thank you for fast comment <3
I try, but working but wrong(for me)
Now check every user each 8 minutes, i try change the configs delay
and i receive the message ("Phew! any things ")
But i´ll remove the folder n create again and say later the news for all

**Comment by xiaomibrasil** [comment]
Hi Friends
 have error on string
username (on code .format(username) not exist, i fix... for user_name
now running

But lock, and each 8 Minutes say for mi

Phew! Last follow is not verified.	~'username' might be temporarily blocked from following

and other use,r opther user, but 8 minutes...

Have way to verifdy my list?
Generate an list the follow, and compare with list that i NEED FOLLOW?



Have other way to FOLLOW AN LIST json generated from Instapy?

@sionking please =)

**Comment by uluQulu** [comment]
Hi @xiaomibrasil 
Alright. You say you have applied the code I shared above and gets that message of "_last follow is not verified_"
**1**-) If you have applied those changes **properly** then it will try to do follow again in case of it has not succeeded.
**2**-) As it has now happened 2 times and your button still does not want to follow, then there is a problem.

#### Can you run a graphical session and watch while it works and SEE that it really does not do FOLLOW or something ELSE?

Well, if it is correct and it does not do follow as I said, then the problem is in your side.
I mean you should look for ways to slow down the follow activity.
Sure, you can bypass that verification in your own and always send a follow, but if it will not follow properly, then the rest of the follow activity is gonna do worse [until you can follow properly again].

Waiting for new feedbacks. If you find English hard to speak, you can write in your native language- Portuguese or any other language you master, @xiaomibrasil 🐬 I will use translation software.

Since I have almost finished the code refactor, I will soon share that code in my new PR, so that you can easily pull and correctly test.

>Have other way to FOLLOW AN LIST json generated from Instapy?

Can you talk a bit more about this?

----

Cheers 😁
----

**Comment by tutiredoni** [comment]
@uluQulu I can't find that part of the code in my **unfollow_util.py** file. My repository is already updated but the code of the file is different. What could I do to use your solution?

**Comment by ebubekirboyun** [comment]
hi @uluQulu 
i cant add code. please share unfollow_util.py  file with me. i have this problem. thanks you

**Comment by uluQulu** [comment]
Hi @ebubekirboyun 
The changes I have suggested in this Issue has already been merged into the main repo and it has been evolved even further from that time.

What is your problem?
Although I have no free time, I will try to write a helpful reply.


Have a good time 🖐🏼
---

**Comment by ebubekirboyun** [comment]
hi @uluQulu 

when i start bot 1 time late given "Phew! Last follow is not verified. ~'rebelzeyna' might be temporarily blocked from following" error. i delete coocie and db work normally but 1 hour.

**Comment by o365geek** [comment]
I need help .

Phew! Last follow is not verified.~'username' might be temporarily blocked from following

Can anyone help? Is this shadow ban? is there specific script I need to include ?

Thanks

**Comment by GGaitanis** [comment]
+1

**Comment by martinkrulltott** [comment]
+1

**Comment by Sam-Morgan** [comment]
> 
> 
> I need help .
> 
> Phew! Last follow is not verified.~'username' might be temporarily blocked from following
> 
> Can anyone help? Is this shadow ban? is there specific script I need to include ?
> 
> Thanks

I has this issue. I found that the follow went ahead correctly, but was not registered by instapy (and unfortunately not added to the database). I found that having instapy operate in a browser (I use firefox) when full screened makes the issue dissappear, so maybe it is an issue with recognising UI changes. Try the full-screen fix.

**Comment by ortegafernando** [comment]
Hi @Sam-Morgan  what is "Try the full-screen fix." ?

**Comment by Sam-Morgan** [comment]
@ortegafernando  this one: having instapy operate in a browser (I use firefox) when full screened makes the issue dissappear. 
This only seemed to work temporarily however. I have since given up on the idea of Instapy as my account was frequently being suspended after using the bot for an hour or two. I'm guessing the mechanical movements of the bot give the game away.

**Comment by ortegafernando** [comment]
For me doesnt work.
I always use headless = false, so I can see everything that happens inside Firefox.
I dont know why, but Instapy sometimes doesnt detect when it follows someone,and when it unfollows someone. 
¿?

**Comment by ortegafernando** [comment]
https://github.com/timgrossmann/InstaPy/issues/5336

**Comment by Dacaramo** [comment]
problem persists in late 2020, @uluQulu is there a way to make it work? I have the UI window showing when I run my program file and when the bot clicks the follow button it just loads like 5sec and after that time it stills showing follow, the action is not beeing save or something like that
