### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'login'

### ISSUE THREAD

**Issue by S4nderr** [InstaPy/InstaPy#2982]
## Expected Behavior
Just run
## Current Behavior
Error:
Traceback (most recent call last):
  File "C:\Users\Sander\Documents\InstaPy\1quickstart.py", line 28, in <module>
    session.login()
AttributeError: 'tuple' object has no attribute 'login'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sander\Documents\InstaPy\1quickstart.py", line 58, in <module>
    session.end()
AttributeError: 'tuple' object has no attribute 'end'
## Possible Solution (optional)
?
## InstaPy configuration

session = InstaPy(username=insta_username,
                  password=insta_password,
                  multi_logs=True,
                  headless_browser=True,
                  proxy_address='188.166.121.36',
                  proxy_port=8080,
                  bypass_suspicious_attempt=True),

try:
    session.login()

    # settings
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(57, 585),
                               peak_comments=(21, 182),
                                peak_follows=(25), (100),
                                 peak_unfollows=(35, 402),
                                  peak_server_calls=(None, 4700))
    session.set_user_interact(amount=3, randomize=True, percentage=50, media='Photo')
    session.set_do_like(enabled=True, percentage=70)
    session.set_comments(["Cool", "Super!"])
    session.set_do_comment(enabled=False, percentage=80)
    session.set_simulation(enabled=True, percentage=66)
    session.unfollow_users(amount=60, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)
    session.interact_user_following(['natgeo'], amount=400, randomize=True)

except Exception as exc:
    # if changes to IG layout, upload the file to help us locate the change
    if isinstance(exc, NoSuchElementException):
        file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
        with open(file_path, 'wb') as fp:
            fp.write(session.browser.page_source.encode('utf8'))
        print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
            '*' * 70, file_path))
    # full stacktrace when raising Github issue
    raise

finally:
    # end the bot session
    session.end()

**Comment by uluQulu** [comment]
Hi @S4nderr 
You have a mistake in the **quickstart** script:
```python
session = InstaPy(username=insta_username,
password=insta_password,
multi_logs=True,
headless_browser=True,
proxy_address='188.166.121.36',
proxy_port=8080,
bypass_suspicious_attempt=True),   # <-- remove the comma
```

-----

Cheers 😂
------
