### ISSUE TITLE
Plyer Issue

### ISSUE THREAD

**Issue by cormo1990** [InstaPy/InstaPy#2983]
Hello Friends, I tried to solve the issue with update all but it persists, can someone help me please?

MBP-di-xxx:InstaPy xxx$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 7, in <module>
    from instapy import InstaPy
  File "/Users/xxx/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/Users/xxx/InstaPy/instapy/instapy.py", line 23, in <module>
    from .comment_util import comment_image
  File "/Users/xxx/InstaPy/instapy/comment_util.py", line 7, in <module>
    from .util import update_activity
  File "/Users/xxx/InstaPy/instapy/util.py", line 20, in <module>
    from .quota_supervisor import quota_supervisor
  File "/Users/xxx/InstaPy/instapy/quota_supervisor.py", line 7, in <module>
    from plyer import notification
ImportError: No module named plyer

My config:
certifi==2018.8.24
chardet==3.0.4
clarifai==2.3.1
configparser==3.5.0
EasyProcess==0.2.3
emoji==0.5.1
enum34==1.1.6
fake-useragent==0.1.10
future==0.16.0
grpcio==1.15.0
idna==2.7
instagram-py==0.0.1
jsonschema==2.6.0
Pillow==5.2.0
plyer==1.3.0
protobuf==3.6.1
PyVirtualDisplay==0.2.1
requests==2.19.1
selenium==3.14.1
six==1.11.0
urllib3==1.23

@uluQulu thanks for the support bro

**Comment by HCWcoder** [comment]
> Hello Friends, I tried to solve the issue with update all but it persists, can someone help me please?
> 
> MBP-di-xxx:InstaPy xxx$ python quickstart.py
> Traceback (most recent call last):
> File "quickstart.py", line 7, in 
> from instapy import InstaPy
> File "/Users/xxx/InstaPy/instapy/**init**.py", line 2, in 
> from .instapy import InstaPy
> File "/Users/xxx/InstaPy/instapy/instapy.py", line 23, in 
> from .comment_util import comment_image
> File "/Users/xxx/InstaPy/instapy/comment_util.py", line 7, in 
> from .util import update_activity
> File "/Users/xxx/InstaPy/instapy/util.py", line 20, in 
> from .quota_supervisor import quota_supervisor
> File "/Users/xxx/InstaPy/instapy/quota_supervisor.py", line 7, in 
> from plyer import notification
> ImportError: No module named plyer
> 
> My config:
> certifi==2018.8.24
> chardet==3.0.4
> clarifai==2.3.1
> configparser==3.5.0
> EasyProcess==0.2.3
> emoji==0.5.1
> enum34==1.1.6
> fake-useragent==0.1.10
> future==0.16.0
> grpcio==1.15.0
> idna==2.7
> instagram-py==0.0.1
> jsonschema==2.6.0
> Pillow==5.2.0
> plyer==1.3.0
> protobuf==3.6.1
> PyVirtualDisplay==0.2.1
> requests==2.19.1
> selenium==3.14.1
> six==1.11.0
> urllib3==1.23
> 
> @uluQulu thanks for the support bro

Try pip install future

**Comment by uluQulu** [comment]
Hi guys
@cormo1990 
Make sure you are targeting the right python version (_or environment_) while installing packages and running code.
_E.g. you might install plyer for python 2 and run **quickstart** script with python 3 which does not have a `plyer` module_ installed.

-------

Cheers 😄
-------

**Comment by cormo1990** [comment]
@uluQulu mmmm...probably I'm doing this wrong, I don't know how to be sure to targeting in the right place...can you teach me please?

I tried pip install but doesn't work :( @HCWcoder

**Comment by uluQulu** [comment]
@cormo1990 
Do you run python in a virtual environment? - If not, how do you run it?
Which python versions you have got installed?

-------

Cheers 😀
-----

**Comment by cormo1990** [comment]
NO, I have python 2.7 and 3.6, I have a Mac, start terminal and simply digit to install python

thanks @uluQulu

**Comment by uluQulu** [comment]
@cormo1990 
Try installing plyer with `pip3`

----

Cheers 😀
-------

**Comment by cormo1990** [comment]
@uluQulu done but I have the same issue...

**Comment by uluQulu** [comment]
@cormo1990 
Post the full traceback information.
Also does it at least install `plyer` properly or fails at that?

**Comment by HCWcoder** [comment]
@uluQulu how to disable image in headless mode im consuming ~3gb each day

**Comment by uluQulu** [comment]
@HCWcoder 
Recently, that feature,
`disable_image_load`
has been merged and now you can easily set it as a parameter at **InstaPy** instance:
```python
session=InstaPy(username=insta_username, password=insta_password, headless_browser=True, disable_image_load=True, multi_logs=True)
```

It does not matter whether you run a headless or graphical session, it just will disable images from loading.
If you want images load, turn off that parameter with the value of `False` or just remove it from the instantiation line (its default is `False`).
It will work for both Firefox and Chrome sessions [although  Firefox has no headless capability].

------

Cheers 🙂
-----

**Comment by cormo1990** [comment]
@uluQulu solved bro, the problem was that I installed python3 but it continue to use python2.
change the file and works! thanks again

**Comment by AdamMoffitt** [comment]
@cormo1990 how did you fix this? what file did you change?

**Comment by cormo1990** [comment]
@AdamMoffitt Hi Adam, have you already tried to download and reinstall the latest version of InstaPy?

if it doesn't work, you have to check your python version using terminal, and if your system is using the old one, you can follow the link below to set as default the newest version of python. feel free to ask other question or help if you don't fix this issue.

https://stackoverflow.com/questions/49704364/make-python3-as-my-default-python-on-mac
