### ISSUE TITLE
Grabbing followers returns error/Outdated readme code

### ISSUE THREAD

**Issue by CoderJoeW** [InstaPy/InstaPy#2986]
## Expected Behavior
When using `my_followers = bot.grab_followers(username="flameforgedprogramming", amount="full", live_match=True, store_locally=True)` I expect to store my current followers in the `my_followers` variable
## Current Behavior
What is happening instead is I recieve this error

`Traceback (most recent call last):
  File "example.py", line 26, in <module>
    my_followers = bot.grab_followers(username="flameforgedprogramming", amount="full", live_match=True, store_locally=True)
AttributeError: 'InstaBot' object has no attribute 'grab_followers'`
## Possible Solution (optional)
This code was taken directly from the readme file It would seem that `instabot.py` no longer contains `grab_followers` I would suggest updating the readme file with the correct code

**Comment by uluQulu** [comment]
@flaminggenius 
I think you are using another application.
Make sure you are using **InstaPy**.

----

Cheers 😄
-----

**Comment by CoderJoeW** [comment]
I'm using instapy however I was looking at another projects readme lol

Maybe this should be changed to a feature request
