### ISSUE TITLE
Image check error: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by velvetflower** [InstaPy/InstaPy#2987]
Console:
> [142/500]
> INFO [date] [nick-name]  https://www.instagram.com/p/abc/?tagged=tag
> INFO [date] [nick-name]  Image from: b'_name'
> INFO [date] [nick-name]  Link: b'https://www.instagram.com/p/abc/?tagged=tag'
> INFO [date] [nick-name]  Description: text
> INFO [date] [nick-name]  --> Image Liked!
> ERROR [date] [nick-name]  Image check error: 'NoneType' object is not iterable
> INFO [date] [nick-name]  --> Not commented
> INFO [date] [nick-name]  --> Not following

Error:
> ...
> ERROR [date] [nick-name]  Image check error: 'NoneType' object is not iterable
> ...

Nothing changed in sources. Here quicklaunch.py settings:

```
session.set_use_clarifai(enabled=True, api_key='key_here')
session.set_do_comment(True, percentage=20)
session.clarifai_check_img_for(['food', 'lunch', 'dinner', 'shoes', 'wear'])
session.set_comments(['text'], media='Photo')
session.set_user_interact(amount=2, randomize=True, percentage=50, media='Photo')
session.set_do_follow(enabled=False, percentage=30)
session.set_do_like(enabled=True, percentage=70)
session.like_by_tags(['cars'], amount=500, media='Photo')
```

What wrong?

**Comment by dfundingsland** [comment]
@velvetflower From what I've seen, this seems to be related to an issue with the `tags_skip` parameter having a value of `None`. I've submitted a PR (#3123) which addresses this issue amongst others. If you don't want to make any changes to your `instapy.py` file, the following change should fix the error. 

`session.clarifai_check_img_for(['food', 'lunch', 'dinner', 'shoes', 'wear'], [])`

With this change, an empty list (`[]`) should get passed to `check_image`. Let me know if that works.
