### ISSUE TITLE
How to unfollow just "normal" people not celebrities? And, is it possible just follow by gender?

### ISSUE THREAD

**Issue by pilarfc** [InstaPy/InstaPy#2990]
## Expected Behavior
I know this is a weird question, but is important for my Instagram account follow some celebrities. I want to unfollow just those ones that don't follow me back, but if they're famous or with some quantity of followers I want to still following them. Is it possible achieve it? Also I have another question, is it possible just follow by gender?

## Current Behavior
Right now InstaPy unfollow all those ones that don't follow you back.

**Comment by spikeyhair** [comment]
The only way I use is to add those users that I don't want to unfollow under the white list by using the set_dont_include function.

**Comment by pilarfc** [comment]
> The only way I use is to add those users that I don't want to unfollow under the white list by using the set_dont_include function.

But how about if you're using the randomize option? 😮

**Comment by pilarfc** [comment]
> The only way I use is to add those users that I don't want to unfollow under the white list by using the set_dont_include function.

But do you mean adding their usernames?

**Comment by spikeyhair** [comment]
whichever user that you don't want to unfollow.
