### ISSUE TITLE
Using Unfollow customList method with .csv/iterable containers

### ISSUE THREAD

**Issue by jeremycjang** [InstaPy/InstaPy#2994]
I saw on the `readme` that there's the following protip:

PRO: customList method can any kind of iterable container, such as list, tuple or set.

can someone provide a basic example code for how to call a `.csv` using the unfollow method?

I tried googling and searching for documentation for a few hours, this is what I came up with last but it still didn't work:

```
uncertainlist = open("| absolute path to uncertain_unfollowedPool.csv |", "rb")
readuncertainlist = csv.reader (uncertainlist)
session.unfollow_users(amount = 5, customList = (True, readuncertainlist, "all"), style = "FIFO", unfollow_after= None, sleep_delay=600)
```
I end up with the "error: no such file or directory" message, tried messing with `os.expanduser` as well but couldn't get it to work either. Any help would be appreciated!

What I'm trying to do is run the unfollow action on the ```uncertain_unfollowedPool.csv``` to go through users that weren't able to be unfollowed after doing a run with ```InstaPyFollowed```

**Comment by jeremycjang** [comment]
@uluQulu could you share any of your awesome insights into this or point me towards where to learn?

**Comment by uluQulu** [comment]
#### Hi @jeremycjang 
You're trying to read data from a CSV file and you can use lots of methods to achieve it.

_E.g._ by using the `csv` module's `reader()` function, you can read it like this:
```python
with open(filename, 'r') as uncertain_unf_file:
    line_data = list(csv.reader(uncertain_unf_file))
# extract only the names from the read data
names = [elem[0] for elem in line_data]
```


_Or_ reading it using plain `readlines()` function,
```python
with open(filename, 'r') as uncertain_unf_file:
    lines = uncertain_unf_file.readlines()
# remove the comma and newline char from lines
names = [line[:-2] for line in lines]
```
`filename` must be a **relative** path or a **full** path,
e.g. full path for Windows:
`"C:/Users/Jeremy/Documents/GitHub/InstaPy/logs/jeremy/jeremy_uncertain_unfollowedPool.csv"`

What you need to know to get it work yourself?
**1**-) Know the correct opening method - `'r'` or `'r+'` or `'a'`, etc. **It matters a lot**.
**2**-) Observe the data you got and split accordingly until satisfies:
e.g.  file looks like: 
```powershell
flyer_photgr205,
kamu.spotu,
```
+ `csv.reader()` returns
`[["flyer_photgr205", ""], ["kamu.spotu", ""]`

+ `readlines()` will return
`["flyer_photgr205,\n", "kamu.spotu,\n"]`

-----

Cheers ☕
-----
