### ISSUE TITLE
Quota Supervisor Exception at Plyr API in Windows 10

### ISSUE THREAD

**Issue by tiymfony** [InstaPy/InstaPy#2997]
## Expected Behavior
 Quota Supervisor: daily server calls reached quotient! ~going to sleep 10.0 hours long
        time for InstaPy to take a big good nap :-)
## Current Behavior
_

> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "c:\users\eva\appdata\local\programs\python\python37\Lib\threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "c:\users\eva\appdata\local\programs\python\python37\Lib\threading.py", line 865, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\EVA~1\DOCUME~1\CODE\venv\lib\site-packages\plyer\platforms\win\libs\balloontip.py", line 145, in balloon_tip
>     WindowsBalloonTip(**kwargs)
> TypeError: __init__() got an unexpected keyword argument 'ticker

_
the ticker argument appears on line 278 in quota_supervisor.py
## Possible Solution (optional)
At a different GitHub repo the problem seems to be Windows OS specific: [https://github.com/kivy/plyer/issues/333]
I will update with my findings:
EDIT: 
Perhaps removing the 'ticker' argument is the best solution
## InstaPy configuration
Windows 10, Python 3.7, Instapy since 9/22/18

**Comment by HCWcoder** [comment]
#2984
