### ISSUE TITLE
Unfollow function freezes script

### ISSUE THREAD

**Issue by MelleNi** [InstaPy/InstaPy#2998]
Unfollowing always freezes on me. I have tried several machines, updates, but nothing seems to change this. It simply tries to unfollow the same user for an endless amount of time. Does everyone have this problem, or is it just my poor luck?

`INFO [2018-09-24 09:33:11] [user]  Starting to unfollow users..`
`""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""`
`INFO [2018-09-24 09:33:11] [user]  Unfollowing the users you are following`
`INFO [2018-09-24 09:33:27] [user]  Total 60 users available to unfollow  ~not found in 'followedPool.csv': 2  |  didn't pass 'unfollow_after': 0`
`INFO [2018-09-24 09:33:27] [user]  Ongoing Unfollow [1/40]: now unfollowing 'b'user_to_unfollow''...`

My `quickstart.py` has the default unfollow:
`session.unfollow_users(amount=40, allFollowing=True, style="LIFO", unfollow_after=3*60*60, sleep_delay=450)`
But I have tried many different setups

**Comment by HCWcoder** [comment]
try to unfollow manually and delete the name from the files

**Comment by MelleNi** [comment]
> try to unfollow manually and delete the name from the files

What's the point of a script, if I'm just going to have to do it manually? I did unfollow a bunch of people, and removed them from followedPool.csv, then ran it with an empty file, but it still doesn't continue.

Edit: It does unfollow the first person, so there's nothing wrong with that. It just doesn't continue, as if it hasn't recognized the unfollow.

**Comment by HCWcoder** [comment]
@MelleNi 
share your setup of quickstarter
