### ISSUE TITLE
Problem with chromedirver on OSX 10.11

### ISSUE THREAD

**Issue by thekage91** [InstaPy/InstaPy#30]
I would try your script on my system but i have one problem.
I have osx 10.11 and i have install chromedriver with brew. 
` brew install chromedriver
`
This install version 2.29 under /usr/local/Cellar/chromedriver/2.29.
In this path, the folder bin contain a ./chromedriver file that i have put in the assets folder.
But when i start your example script with: 

`python quickstart.py 
`
the system return this error:

`selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service ./assets/chromedriver
`

I setup username and password trough default parameters.
I tried to download chromedriver from https://sites.google.com/a/chromium.org/chromedriver/downloads,
but the error is the same. 

This is the traceback of the error 
```
  File "quickstart.py", line 10, in <module>
    InstaPy(username='username', password='mypassword')\
  File "/Users/davide/Workspace SSD/GitHub Repo/InstaPy/instapy/instapy.py", line 31, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/common/service.py", line 92, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service ./assets/chromedriver


```

What i can do?
thanks!

**Comment by timgrossmann** [comment]
Do you have the latest chrome browser installed?
Do you have the right chromedriver (system and 32 or 64bit)?

**Comment by thekage91** [comment]
Yes, i have the latest chrome browser installed (57.0.2987.133 (64-bit))
 and the latest chromedriver that i have downloaded at https://chromedriver.storage.googleapis.com/index.html?path=2.29/ (mac64)

As if it were a selenium problem

**Comment by timgrossmann** [comment]
Hmm that's pretty weird.
Right now, I can't figure out what the problem is...

You could try to create a new file and put in the selenium stuff.
Just to try out if selenium works.

**Comment by eduardocalazansjr** [comment]
@thekage91 try to do the following changes in instapy.py

```
chrome_options = Options()
chrome_options.add_argument('--dns-prefetch-disable')
chrome_options.add_argument('--no-sandbox')
service_log_path = "./assets/chromedriver.log"
service_args = ['--verbose']
self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options, service_args=service_args, service_log_path=service_log_path)
self.browser.implicitly_wait(25) 
```

If the error persists, post the chromedriver.log file (located inside the assets folder)

**Comment by timgrossmann** [comment]
@thekage91 Any updates on this?

**Comment by thekage91** [comment]
@vlntdds i have edit instapy.py with provided code, but the error is the same and the log generated is empty

ps: sorry I closed the issue by mistake :)

**Comment by thekage91** [comment]
I have solve the issue! 
The problem is connected to my /etc/host file.
I have remove 127.0.0.1 localhost for my development purpose, and this generate this issue. 

In my case (and in [another case](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1589)), add 
`127.0.0.1 localhost` 
to my /etc/host resolve this issue. 

Try to replicate by delete this line from your host file.

For Mac user is possibile install chromedriver from homebrew
`brew install chromedriver` 
put the installation path in the environment variable PATH (with the bin folder).
In my case the path is `/usr/local/Cellar/chromedriver/2.29`
After this, remove `'./assets/chromedriver'` from webdriver.Chrome in the Instapy.py file, because the constructor check the environment path to find chromedriver.

Enjoy your automation 👍
