### ISSUE TITLE
interact with the likers and don't follow them

### ISSUE THREAD

**Issue by michaellafrasse** [InstaPy/InstaPy#3004]
Hi,

does anyone know if it is possible to interact with the likers of a post without following them? Just like for example 2 or 3 pictures of the person.

the only function I see that comes close to it is "session.follow_likers ". But I don't know if there's a way to get around the follow.

Thanks
Michael

**Comment by Zettt** [comment]
I'd also like to request the feature "like_likers".

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
