### ISSUE TITLE
Shadow ban

### ISSUE THREAD

**Issue by AvocadoStyle** [InstaPy/InstaPy#3005]
Why I’m allways getting shadow banned?
I’m following every 10 people i follow i wait 10 minutes, should i do it much more time than 10 minutes? Or it’s because my instagram account have been blocked before and it’s remmember my account as banned account?
Because I use the same times for following for 4 accounts and getting ׳shadow banned’ only for one of them.... with the same settings!!

**Comment by HCWcoder** [comment]
@AvocadoStyle  is your account new ?

**Comment by AvocadoStyle** [comment]
@HCWcoder
No...

**Comment by ghost** [comment]
@AvocadoStyle you mean shadow banned as in you can't follow for 24 hours ,,, or you mean your account is shadow banned from showing on feeds/suggestions as much ?
