### ISSUE TITLE
follwedpool.csv

### ISSUE THREAD

**Issue by S4nderr** [InstaPy/InstaPy#3006]
No issue,

Can someone explain the text "~ 192562021,"

In username_followed.pool.csv 2018-09-23 23:18 ~ schivanb ~ 192562021,

Can i manually add people here?

**Comment by IsNotMyIP** [comment]
As long as i Know that "numbers" is the id of the user on instagram. And the document you are on is the pool of the people that the bot has followed.

**Comment by sionking** [comment]
person id
