### ISSUE TITLE
Follow someone else's followers: user has already been followed

### ISSUE THREAD

**Issue by freezingbaby** [InstaPy/InstaPy#3007]
## Expected Behavior

follow_user_followers should follow new users everytime the script runs.

## Current Behavior

follow_user_followers tries to follow the same users every time which results in a lower number than expected.

---> "user" has already been followed 1 times

Im using pretty a "low" amount for the action (never tried it with more than 100 - 200 users). I guess this is connected to my problem as the follower list is much longer than the amount i am using (~5k) If i scroll down manually i can see that after a few more scrolls there are accounts which would fit my relationship.bounds but have never been followed by the script. I tried to use the boundary parameter mentioned in a similiar situation (dialog box not scrolling down far enough) but it did not work out the way i thought it should.

**Comment by mateuspestana** [comment]
Same happening here.
