### ISSUE TITLE
Sleep delay between each follow

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#3009]
Hello, 
how to increase the delay between each follow ? 

any idea @uluQulu 

Thanks

**Comment by AvocadoStyle** [comment]
@uluQulu +1!!!! Thanks.

**Comment by uluQulu** [comment]
Hi all

@Edhim 
Why you would want to do it?

There is a Quota Supervisor with the capability of controlling the follow actions smartly in both- hourly & daily intervals if you have not heard of.

If you have a specific reason, then I will ask 2 questions:
+ Do you want to have a delay after **every** follow in the program?
_e.g. `like_by_tags()` can also follow people, etc._

+ OR do you want to have a delay after follows in follow based features in the program?
_e.g. `follow_likers()` or `follow_user_followers()`, etc._

-----

Cheers 😁
----

**Comment by Edhim** [comment]
@uluQulu 
i am using follow_user_followers  
and between each follow i want put some delay

**Comment by uluQulu** [comment]
Right, @Edhim 
>**Why** you would want to do it?

**Comment by Edhim** [comment]
@uluQulu each time i am shadow banned from my mac (i need to change ip each time)
so i think increasing the delay between each follow (like 40s) would avoid this

**Comment by uluQulu** [comment]
@Edhim 
That's clear.
I think you should add that delay after every follow you do.

**Open** up **unfollow_util.py** file and find the `follow_user()` definition and at the end of that function, put the desired sleep time.
```python
    sleep(40)   # earlier it was: `sleep(3)`    ## YOU WILL MODIFY THIS LINE

    return True, "success"
```
Now it will sleep 40 seconds after each follow but it is a big amount I would say 🤔 (_maybe put 15 seconds?_)

-----

Cheers 🤩
------

**Comment by Edhim** [comment]
@uluQulu  thaaanks.

i will do some tests and see the best delay amount.

Many thanks!

**Comment by AvocadoStyle** [comment]
@uluQulu 
This will help me get rid of this shadow ban too!
Thanks!

**Comment by AvocadoStyle** [comment]
> 
> i will do some tests and see the best delay amount.
> 
> Many thanks!

@Edhim 
tell us if it stopped shadow ban you with the settings (sleep 40 seconds)
