### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by ZackVega** [InstaPy/InstaPy#3010]
Hey guys I notice there was no way to communicate as a community so I went ahead and created a Discord server. Maybe we can come together and share the best settings and best practices there. https://discord.gg/k4jDKnm Sorry if this is not allowed I just really love this project and I am currently in the process of learning python. This is helping a lot and making my learning really fun. Maybe we can come together and discuss issues and how to solve them! Once again this is the discord link! https://discord.gg/k4jDKnm

**Comment by mcost45** [comment]
Found this on the Discord server:

NEW ISSUE FIXED AND CONFIRMED 

Issue is directly related to the newest Mozilla Firefox update 74.0

File "C:\Users\mccune\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Timeout loading page after 300000ms

**Steps to fix: 
Downgrade to 73.0.1.**
