### ISSUE TITLE
Turn on notification

### ISSUE THREAD

**Issue by spikeyhair** [InstaPy/InstaPy#3013]
## Expected Behavior
Shouldn't have "Turn on Notification" pop up

## Current Behavior
When the bot starts and loaded the instagram user's timeline page, a new pop up appears and ask user whether to turn on the notification or not. Bot will hang there until I manually dismissed the pop up (either by selecting turn on or turn off).

**Comment by Nocturnal-2** [comment]
I get this pop up as well. But it doesn't affect the flow.

**Comment by JosteinFraNorge** [comment]
I get this popup and it holds the program about 50% of the times.

**Comment by HCWcoder** [comment]
@herrgutt 

in headless mode or not it will go straight to you profile after that and it will disappear 

try to use headless mode

**Comment by thejeromelouis** [comment]
I had the same problem. I added this after the "if switch language:"-part in the "login_util.py" and it solved my problem:
```
try:
     dismiss_notification_offer(browser, logger)
except:
     print("There is no Notification")
```
