### ISSUE TITLE
Bug ! unfollow_users :NonFollowers only

### ISSUE THREAD

**Issue by HCWcoder** [InstaPy/InstaPy#3015]
`session.unfollow_users(amount=126, nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)`

Im using this method to unfollow everyone on my following that doesn't follow back

and im still having friends and users that follow me back being removed and unfollowed .

To make sure of this i double checked my logs and i found out that's its true sometimes its unfollowing people even if they do follow back!
even my settings : 
```
session.set_dont_include(friendzy)
session.set_ignore_users(friendzy)
```
and friendzy is a list of my friends.

**Comment by sionking** [comment]
Now you saying this after using first time yesterday.

**Comment by HCWcoder** [comment]
@sionking 

i have been using this from the first day i joined this community and i never had a problem with it till my friends told me why you unfollowed us and you still liking our pics ?

so i checked the logs and i found out that he really did unfollowed them even they are in my friend list and they are following me !

**Comment by marcman6878** [comment]
So fucking what

**Comment by HCWcoder** [comment]
> So fucking what
@marcman6878 

what did you say ?
