### ISSUE TITLE
Logout during execution

### ISSUE THREAD

**Issue by Adoncino** [InstaPy/InstaPy#3018]
Hi there,

I was using successfully InstaPy 24/7, while I notice that since yesterday the bot is logging out randomly. It will try to like the pictures and continue the work, but it is unable to.

I fixed temporarily by ending and relaunching the session every 2 hours, but I hope that you would suggest me a better fix.

I already tried to clear the account cookie and to sign in "freshly" but it doesn't help.

**Comment by sionking** [comment]
Latest version ?

**Comment by o365geek** [comment]
I had the same issue today after installing InstaPy . It signed out after 1 min or 2 min . Is there a way to kep the session on all day...I ask because I can leave my workstation on all the or all night ..
