### ISSUE TITLE
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#3020]
@uluQulu and @sionking , any suggestions?

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-09-26 20:12:58] [xxx]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20180926-201355.html
**********************************************************************
INFO [2018-09-26 20:13:55] [xxx]  Sessional Live Report:
        |> LIKED 0 images  |  ALREADY LIKED: 0
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0
currently FOLLOWING 0 users & has got 0 FOLLOWERS

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-09-26 20:13:55] [xxx]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "5baaaa126a0bb9001392b800.py", line 16, in <module>
    session.login()
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 385, in login
    self.bypass_suspicious_attempt):
  File "/home/fredrik/InstaPy/instapy/login_util.py", line 239, in login_user
    "//form/span/button[text()='Log in']")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 393, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}
  (Session info: headless chrome=69.0.3497.100)
  (Driver info: chromedriver=2.36 (7165af0ca9863529f28e493568ae3d105eddcdef),platform=Linux 4.15.0-34-generic x86_64)

**Comment by d3rf** [comment]
Same error here, just one accout having these trouble, others are ok

**Comment by osvald0** [comment]
Update xpath to "//button[text()='Log in']" in login_util.py line 239.

**Comment by d3rf** [comment]
Thats works, I gonna try others now...

**Comment by fgisslen** [comment]
@osvald0 thanks mate!

**Comment by cyberpz** [comment]
I made a real quick PR, thank you @osvald0.

**Comment by dloges** [comment]
In my case, I changed the .click() to .send_keys(Keys.ENTER) and I was able to login.
File: login_util.py
Line: 239

```
# login_button = browser.find_element_by_xpath(
#     "//form/span/button[text()='Log in']")

# (ActionChains(browser)
#     .move_to_element(login_elem)
#     .click()
#     .perform())

(ActionChains(browser)
    .move_to_element(input_password[0])
    .click()
    .send_keys(Keys.ENTER)
    .perform())

```
You are no longer looking for the Log in button text that triggers the error.
Instead you focus the password box and press enter, like must human would do.
Voila, you are login.

**Comment by cyberpz** [comment]
Sounds human ahaha, nice intuition!

**Comment by cha-theo** [comment]
> Update xpath to "//button[text()='Log in']" in login_util.py line 239.

In my file there are 181 lines.

It fills the username + pass and says "Cookie file not found, creating cookie...", after a while stops.

I changed back to old account and worked.

**Comment by confusedgorkha** [comment]
{"method":"xpath","selector":"//form/span/button[text()='Log in']"}
still not working. It fills the username in one signup session and password in another login session
kindly suggest me.

**Comment by machieajones** [comment]
Change 
`login_button = browser.find_element_by_xpath(
        "//form/span/button[text()='Log in']")
`

to 
`login_button = browser.find_element_by_xpath(
        "//*[contains(text(), 'Log in')]")`

in login_util.py

**Comment by ajankuv** [comment]
> Change
> `login_button = browser.find_element_by_xpath( "//form/span/button[text()='Log in']")`
> 
> to
> `login_button = browser.find_element_by_xpath( "//*[contains(text(), 'Log in')]")`
> 
> in login_util.py

does not work

**Comment by decoge** [comment]
> In my case, I changed the .click() to .send_keys(Keys.ENTER) and I was able to login.
> File: login_util.py
> Line: 239
> 
> ```
> # login_button = browser.find_element_by_xpath(
> #     "//form/span/button[text()='Log in']")
> 
> # (ActionChains(browser)
> #     .move_to_element(login_elem)
> #     .click()
> #     .perform())
> 
> (ActionChains(browser)
>     .move_to_element(input_password[0])
>     .click()
>     .send_keys(Keys.ENTER)
>     .perform())
> ```
> You are no longer looking for the Log in button text that triggers the error.
> Instead you focus the password box and press enter, like must human would do.
> Voila, you are login.

This works, but you also need to add `from selenium.webdriver.common.keys import Keys` to the beginning of the file.
