### ISSUE TITLE
Getting stuck at login creating cookie (windows 10) 

### ISSUE THREAD

**Issue by chille9** [InstaPy/InstaPy#3021]
## Expected Behavior
after installing this again with six months not using it I expected it to log me in at least!
## Current Behavior
I start instapy by double-clicking quickstart.py, it starts and rolls to instagram, then it goes to google, back to instagram and puts in the username and password correctly. However the instapy doesnt log in and if I click it myself it just closes down.
The step it's stuck at is creating a cookie it seems.

## Possible Solution (optional)
Install it correctly ? I installed Microsoft Visual C++ 2017 instead of 2015 thinking it saved me a few GB. Not sure if this causes the program to not function properly.

**Comment by chille9** [comment]
This is what the command prompt gives me.

File "C:\Users\Roe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}

  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)

**Comment by chrokeefe** [comment]
Also having this issue. Puts in all my login info, stalls out, and then crashes. Have done everything listed on past threads. Seems to be an issue with "xpath"? I'm fairly new to all this so it doesn't make a lot of sense to me.

  File "C:\Users\croke\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\croke\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)

**Comment by ZackVega** [comment]
Update xpath to "//button[text()='Log in']" in login_util.py line 239.

**Comment by dloges** [comment]
In my case, I changed the .click() to .send_keys(Keys.ENTER) and I was able to login.
File: login_util.py
Line: 239

```
# login_button = browser.find_element_by_xpath(
#     "//form/span/button[text()='Log in']")

# (ActionChains(browser)
#     .move_to_element(login_elem)
#     .click()
#     .perform())

(ActionChains(browser)
    .move_to_element(input_password[0])
    .click()
    .send_keys(Keys.ENTER)
    .perform())
```

You are no longer looking for the Log in button text that triggers the error.
Instead you focus the password box and press enter, like must human would do.
Voila, you are login.

**Comment by chille9** [comment]
> Update xpath to "//button[text()='Log in']" in login_util.py line 239.

This worked for me!

**Comment by machieajones** [comment]
Change
`login_button = browser.find_element_by_xpath( "//form/span/button[text()='Log in']")`

to
`login_button = browser.find_element_by_xpath( "//*[contains(text(), 'Log in')]")`

in login_util.py
