### ISSUE TITLE
check_authorization unneccesery browsing of user profile page.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#3026]
@uluQulu is there a reason you added `web_address_navigator(browser, profile_link)` here ?
This check can be done on every page AFAIK.
```
def check_authorization(browser, username, method, logger):
    """ Check if user is NOW logged in """
    logger.info("Checking if '{}' is logged in...".format(username))

    # different methods can be added in future
    if method=="activity counts":

        profile_link = 'https://www.instagram.com/{}/'.format(username)
        web_address_navigator(browser, profile_link)
```

**Comment by uluQulu** [comment]
@sionking
It can be stucked in some unusual webpage.
But that must be visualized once again after all then it might be removed.

Also, note that at this stage of the program code, it request the authorization check only in rare cases where there really is some problem [possibly real not-logged-in] so keeping it stable as it is is a good idea for now.

----

Cheers 😁
----

**Comment by sionking** [comment]
I removed it for my app.
We maybe need to go the profile page only on **failure**
