### ISSUE TITLE
Can't login with no cookie - "Wrong login data"

### ISSUE THREAD

**Issue by sakowicz** [InstaPy/InstaPy#3029]
```
$ python3 quickstart.py

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-09-27 09:46:35] [xxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...

.........................................................
CRITICAL [2018-09-27 09:47:18] [xxx]  Wrong login data!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-09-27 09:47:21] [xxx]  Sessional Live Report:
        |> LIKED 0 images  |  ALREADY LIKED: 0
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0
currently FOLLOWING 43 users & has got 1992 FOLLOWERS


OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-09-27 09:47:21] [xxx]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo


```
What I can do with that?

**Comment by dloges** [comment]
In my case, I changed the `.click()` to `.send_keys(Keys.ENTER)` and I was able to login.
File: login_util.py
Line: 239

    # login_button = browser.find_element_by_xpath(
    #     "//form/span/button[text()='Log in']")

    # (ActionChains(browser)
    #     .move_to_element(login_elem)
    #     .click()
    #     .perform())

    (ActionChains(browser)
        .move_to_element(input_password[0])
        .click()
        .send_keys(Keys.ENTER)
        .perform())

You are no longer looking for the `Log in` button text that triggers the error.
Instead you focus the password box and press enter, like must human would do.
Voila, you are login.

**Comment by sakowicz** [comment]
@dnhype Its not seems like that problem. I solved it with [this](https://github.com/timgrossmann/InstaPy/pull/3022).
But its seems to be a problem with something different. I've got an emails with login attempts for my account. So I think that login-form related problem is solved but there is something else. I think Instagram blocks my login from my server even when I accepted that login via web browser.
I don't know how to handle this.

**Comment by ghost** [comment]
@sakowicz  maybe you need to purchase instagram pr0xies because your server ip's are banned. or just keep switch server ip and see if one is not banned.

**Comment by sakowicz** [comment]
@loopypanda Thanks. I figured it out. My server IP was banned and I wasn't able to login from my server. So I installed InstaPy on my Windows PC and copied cookie file to my linux server. Its working now.

**Comment by converge** [comment]
just wrote a bugfix, are you available to help testing it ? https://github.com/timgrossmann/InstaPy/pull/3384

**Comment by Polkyanik** [comment]
**help guys i have the same error; (**

instaPy Version: 0.6.10
.. .. .. .. .. .. .. ..
Workspace in use: "/home/pi/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-09-12 17:15:09] [..........] Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-09-12 17:15:09] [..........] -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-09-12 17:15:10] [..........] - Internet Connection Status: ok
INFO [2020-09-12 17:15:10] [..........] - Current IP is "..........." and it's from "Italy/IT"
INFO [2020-09-12 17:15:10] [..........] -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-09-12 17:15:10] [..........] - window.navigator.webdriver response: None
INFO [2020-09-12 17:15:10] [..........] - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
INFO [2020-09-12 17:15:10] [----------] Timed out with failure while explicitly waiting until title contains 'Login' string!
INFO [2020-09-12 17:15:10] [----------] Timed out with failure while explicitly waiting until visibility of element located!





InstaPy configuration
Raspberry Pi 4
InstaPy Version: 0.6.10
Mozilla Firefox 68.12.0esr
geckodriver 0.23.0 ( 2018-10-04)
python3.7
selenium 3.141.0
