### ISSUE TITLE
Message: "Error: ModuleNotFoundError: No module named 'chardet'" | "chrome driver is missing!"

### ISSUE THREAD

**Issue by syond** [InstaPy/InstaPy#3034]
## Expected Behavior
Follow user followers.

## Current Behavior
- When i click RUN it's showing message: "Error: ModuleNotFoundError: No module named 'chardet'". 
- InstapyGUI.exe showing message: "chrome driver is missing!", but the chrome driver was placed in "/assets" folder correctly.

## InstaPy configuration
All installed correctly according to [How to Windows](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Windows.md).

**Comment by davidelionetti** [comment]
A) Try to execute: sudo python3 quickstart.py 
B) Are u sure you moved the executable file in the /assets folder and not the .zip ?

**Comment by syond** [comment]
Thanks for your reply!

A) I'm using Windows 7, how can i use sudo ?
B) Yes, it's the chromedriver.exe

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)
