### ISSUE TITLE
Shut down computer when session is completed

### ISSUE THREAD

**Issue by davidelionetti** [InstaPy/InstaPy#3035]
Hello!

I'm running InstaPy locally on my MacBook Air. How can I have InstaPy shut down my pc once the session has come to its end?

It would be very helpful when leaving InstaPy open overnight.

Thanks!

**Comment by syond** [comment]
Hello.

I have a problem with my InstaPy on Windows 7 x64. Can you help me ?

[issues/3034](https://github.com/timgrossmann/InstaPy/issues/3034)

**Comment by IH4xx3R** [comment]
Have a look : https://stackoverflow.com/questions/34039845/how-to-shutdown-a-computer-using-python
