### ISSUE TITLE
Is there a way to exclude people who are already following you from being followed/interacted with?

### ISSUE THREAD

**Issue by pinkoveralls** [InstaPy/InstaPy#3040]
It doesn't seem to be a standard feature of InstaPy, and the closest thing I was able to find discussing it was #2263, but I'm looking for a way to ignore people following me completely from every action (definitely don't want to follow them, or like and comment on their stuff either).

If somebody knows how to do this it would be appreciated, I'm mainly interacting by hashtags. 

Thank you!

**Comment by GabrieleCalarota** [comment]
use don't include option and get a list of your followers through graphql query.

It is all already implemented you should look for get_follow_list() in util.py and for set_dont_include in instapy.py

**Comment by pinkoveralls** [comment]
Would you be able to walk me through how to do this? I'm fairly new to using python and haven't been able to figure it out on my own

**Comment by GabrieleCalarota** [comment]
Use the get_follow_list (you can find it in the code) than you use in the quickstart:

Session.set_dont_include(get_follow_list(your_username..etc))

**Comment by pinkoveralls** [comment]
Hi thanks for the reply, I think I understand the part in quickstart.py, but I don't understand the get_follow_list part or how to implement generating a list of my followers. get_follow_list isn't in util.py or anywhere else in the code, but I found the a section with 'get entire list of followers using graphql queries' in  relationship_tools.py, and that seems more like what I'm looking for. On the front page under relationship tools there is the code to grab followers of a user which I think is what i'm looking for, but I don't know what to do with it. 

Everything I've tried so far hasn't worked, so any help would be really appreciated

**Comment by GabrieleCalarota** [comment]
Yes ok they maybe moved it, else where. Basic idea is use the get follow list and include that list in session.set_dont_include() function that expect a list of users you want to exclude

**Comment by pinkoveralls** [comment]
It says that get_follow_list is undefined, so I think it was either renamed or removed, the current section in relationship_tools.py looks like this 


```
def get_followers(browser,
                   username,
                    grab,
                     relationship_data,
                      live_match,
                       store_locally,
                        logger,
                         logfolder):
    """ Get entire list of followers using graphql queries. """
    if username not in relationship_data:
        relationship_data.update({username: {"all_following":[], "all_followers":[]}})

    grab_info = "at \"full\" range" if grab=="full" else "at the range of {}".format(grab)
    tense = "live" if (live_match == True or not relationship_data[username]["all_followers"]) else "fresh"

    logger.info("Retrieving {} `Followers` data of {} {}".format(tense, username, grab_info))

    user_link = "https://www.instagram.com/{}/".format(username)
    web_address_navigator(browser, user_link)

```

and on the front page it lists this code to get followers of a user, so I feel that it may not be included right now (and if it is, I'm unsure of how)

```
popeye_followers = session.grab_followers(username="Popeye", amount="full", live_match=True, store_locally=True)
##now, `popeye_followers` variable which is a list- holds the `Followers` data of "Popeye" at requested time
```

I might open a new issue and close this one to see if somebody using the current version of the bot can help.
