### ISSUE TITLE
Raspberry Pi - Session Errors

### ISSUE THREAD

**Issue by shariqmoosa** [InstaPy/InstaPy#3044]
Dear All,

I am trying to setup Instapy on Raspberry Pi 3 B+ running Linux 4.14.70-v7+ (Rasberian) with Chrome,

Below is the error:
/InstaPy# python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    headless_browser=True)
  File "/home/pi/projects/InstaPy/instapy/instapy.py", line 217, in __init__
    self.set_selenium_local_session()
  File "/home/pi/projects/InstaPy/instapy/instapy.py", line 333, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

Quickstart File:
""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = 'user'
insta_password = 'xxx'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

with smart_run(session):
    """ Activity flow """
    # settings
    session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=4590,
                                        min_followers=45,
                                        min_following=77)
    
    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])
    
    
    # actions
    session.like_by_tags(["instagram"], amount=10)

Complete newbie on Raspberry but successfully running bot on Windows 10,

Thanks

**Comment by kiankji** [comment]
+1

**Comment by shariqmoosa** [comment]
Any update on this guys?

**Comment by kubelkowaty** [comment]
I have the same issue

**Comment by kubelkowaty** [comment]
I solved it! The problem is wrong version of chromedriver and chromium. Even i start chromium browser and check the version(was correct). But instapy display in error different version. I remove all version of chromium, than instal from Add/remove software, only package web chromium ver 65. 
Chrome driver i took from my previous instapy project, because i did not find 2.33 32bit on site. And now InstyPy is working but i have next error....
i do not know how to get chromedriver 2.36, because when i download it from chormedriver site is not working, only wokrs for me files from usr/bin, but when i donwload by apt-get install chromedriver, downloaded it 2.40 and chromium 69.... can someone help mi with downloading correct version? How to do this...

**Comment by Obsessi0n** [comment]
> I solved it! The problem is wrong version of chromedriver and chromium. Even i start chromium browser and check the version(was correct). But instapy display in error different version. I remove all version of chromium, than instal from Add/remove software, only package web chromium ver 65.
> Chrome driver i took from my previous instapy project, because i did not find 2.33 32bit on site. And now InstyPy is working but i have next error....
> i do not know how to get chromedriver 2.36, because when i download it from chormedriver site is not working, only wokrs for me files from usr/bin, but when i donwload by apt-get install chromedriver, downloaded it 2.40 and chromium 69.... can someone help mi with downloading correct version? How to do this...

Did you manage to get it working?

**Comment by shariqmoosa** [comment]
Hello All,

Any update on this? I have bought raspberry pi for this purpose only but nothing worked so far... anyone using raspberry pi with Instapy?

**Comment by kubelkowaty** [comment]
In the docs/ in how to raspberry file scroll down. and do the steps for raspbian lite ;) and after that should works ;)
