### ISSUE TITLE
IDEA: remove all sleep in program.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#3049]
I think we shall remove random sleeps.
We shall do random sleep in case of follow/like/servercall/comment.

In current approach we can have no like for 2-3 minutes, and 1 minute out of it is just a delay we create.

**Comment by ghost** [comment]
60 seconds x 60 minutes = 3600 seconds x 24 hours = 86400 seconds ÷ 60 seconds = 1440 interactions per day.  I use random sleep (52, 62) to make estimated 1400 follow per day and 1400 likes per day 

unfollow_util.py ( add sleeps after follow and unfollow )

```
    import time
    import random
    from time import sleep
    from random import randint

    print("sleeping for follow 52-62 seconds.")
    time.sleep(random.randint(52, 62))
    print("Done sleeping for follow.")
```

**Comment by sionking** [comment]
Working 24/7 will flag your account. Getting no engagement ? You must look human.

**Comment by ghost** [comment]
The account gets about 100 new followers and likes a day with offensive content.....its all about the maximum interaction for me but we all have different goals........ my ig username states that the account is a bot so no need to look human.

**Comment by redsector72** [comment]
I agree with Sion. We can put the additional delay as a default option that can be disabled

**Comment by ishandutta2007** [comment]
Delay is very important.
There are many past issues of entire account beling blocked(please search)
Even with current limit we are never sure when it might happen to us even with a small change in instagram algorithm.
It's better to be safe than sorry.
