### ISSUE TITLE
Best Settings Place Yours Here As Well!

### ISSUE THREAD

**Issue by didamos99** [InstaPy/InstaPy#3050]
# Please Do Exactly The Same As I do We Can Help Each Other Out with The Bot By Sharing Our Scripts!

## Features You Using
First script:
Comments
Likes
User interacting

Second Script:
Follow
Unfollow
Likes

## Results
First script:
Around 50 followers a day

Second script:
Around 70-100 followers a day

## cron script
First script: 
25 2,5,8,12,15,18,21 * * 2,4,6,0 

Second script:
3 1,7,13,19 * * 1,3,5 

As you can see I run 2 different scripts that's to switch them so I don't get banned for placing to many comments :)
1 script I only use on tuesday, thursday, saturday and sunday
and the otherone on monday, wednesday and friday.

## InstaPy configuration
Script 1: https://www.dropbox.com/s/qma7yajyi7ru6hy/script1.py?dl=0
Script 2: https://www.dropbox.com/s/y3pv9bdk3irnpqj/script2.py?dl=0

**Comment by sionking** [comment]
only tags? baa lots of shity stuff. quality talk nowdays
