### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by fredjo294** [InstaPy/InstaPy#3052]
## Current Behavior
when i use this code: session.interact_user_followers(['niloufsky'], amount=1000, randomize=True)
it stop and it happen with all command that related with somones account.
how i can solve this problem:
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=56833): Max retries exceeded with url: /session/260c4b65abeda518804d36f616b9321f/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019C899A6080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by Andercorp** [comment]
Same here.

**Comment by namesreallyblank** [comment]
Having Similar problem
