### ISSUE TITLE
Don't filter inappropriate

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#3055]
Hi,
I have an account that don't want to filter inappropriate. Is it possible?
@uluQulu @timgrossmann @sionking

**Comment by sionking** [comment]
Don't set any filters...

**Comment by fgisslen** [comment]
@sionking I don't set any filters

**Comment by ghost** [comment]
i think in instapy, it defaults to filter here:
`
self.dont_like = ['sex', 'nsfw']`

should we not set this to null now as the user should only set it if they want - not on by default
