### ISSUE TITLE
Business Categories

### ISSUE THREAD

**Issue by Nuzzo235** [InstaPy/InstaPy#3057]
Is there a list of the current Business Categories which are available for Instagram? This would be a nice addition in the Readme if `session.set_skip_users` together with `dont_skip_business_categories` is merged in the near future. Tested #3048 for my needs this afternoon without errors, thanks for the awesome work @GabrieleCalarota & @sionking!

**Comment by timgrossmann** [comment]
@Nuzzo235 Thank you for testing the PR!

Well, that's one thing we have to find out.
I think it shouldn't be a problem if somebody has a business account they can choose the business category for their business site.

**Comment by Nuzzo235** [comment]
Seems like these categories are far more general than I thought and different from the categories I expected (with the subcategories from Facebook in mind):

> 
> Creators & Celebrities
> Food & Personal Goods
> General Interest
> Home Goods Stores
> Home Services
> Lifestyle Services
> Non-Profits & Religious Organizations
> Personal Goods & General Merchandise Stores
> Professional Services
> Publishers
> Transportation & Accomodation Services

@timgrossmann #3097 Here are a few more categories. Best, Nuzzo

**Comment by ScorpionOO8** [comment]
I found some different categories. 

'Business & Utility Services', 'Food & Personal Goods', 'Local Events', 'Personal Goods & General Merchandise Stores', 'Home Services', 'General Interest'

Note that the categories returned by the graphql query are not the categories us business users of Instagram see when we pick our category. I haven't seen one exact matchup at all.

**Comment by Aldentec** [comment]
Any updates on this? I'd love to be able to narrow down some of my code to only interact with users that have a certain business category.
