### ISSUE TITLE
Error Installation Failed With Error Code 1

### ISSUE THREAD

**Issue by proschnoss** [InstaPy/InstaPy#3058]
## Error Installation 
I get installation error while i try to install InstaPy on my linux mint 19 cinnamon 
I run installation method from basic installation 
``` sudo python setup.py install ```
And
```sudo pip install . ```
```sudo python setup.py install```
And get this results : 
```Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-bs3c1p-build/ ```

**Comment by ghost** [comment]
try using python3 
`sudo apt-get install python3-setuptools`
`sudo python3 setup.py install`
`sudo pip3 install .`
`python3 quickstart.py`

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)
