### ISSUE TITLE
import emoji

### ISSUE THREAD

**Issue by sebmer-com** [InstaPy/InstaPy#306]
Hello, 

i had an issue to get the Instapy started. 

![emmoji bug](https://user-images.githubusercontent.com/29119470/26980080-5332ab08-4d31-11e7-8e2d-91fd602c3f44.PNG)

but outcommenting fixed it in the first place
![err emo](https://user-images.githubusercontent.com/29119470/26980056-3c6fd260-4d31-11e7-930f-0760a4da3584.PNG)

but later when the skript runs there reappears the emoji import error. 

As result the skript stops :(

![skript stops](https://user-images.githubusercontent.com/29119470/26980122-74aae82c-4d31-11e7-8f7b-13115300800c.PNG)

can you provide a solution?

chrome latest + win 10

GZ Basti

**Comment by timgrossmann** [comment]
@Basti922 Please don't touch the code if your not aware of what you are doing... This will generate more problems than it solves!

You have to revert your changes in the code (or simply clone the repo again) and simply install the emoji module like every other one of the modules.

Just do
```bash
pip install emoji
```

or if this is not working, find out the python3 version installed and do (for me its 3.5)

```bash
pip3.5 install emoji
```

**Comment by sebmer-com** [comment]
Thanks :)
