### ISSUE TITLE
Is there any way to use proxy in Ubuntu?

### ISSUE THREAD

**Issue by imkimchi** [InstaPy/InstaPy#3063]
The document says "proxy works only with Chrome and headless_browser=False" but when I set headless_browser=False in Ubuntu, It gives me error because It can't be displayed in nogui. 

I'm pretty sure there should be pretty much people who achieved this but I can't find anything in issues  from the repo. Would be really appreciate it if someone can help me out for this 🙏

**Comment by loopypanda** [comment]
x is burning in heII
