### ISSUE TITLE
OSX - Plyer: "ModuleNotFoundError: No module named 'pyobjus'"

### ISSUE THREAD

**Issue by visualheroes** [InstaPy/InstaPy#3064]
Hi,
I have a recurring Plyer error since the quota update: "ModuleNotFoundError: No module named 'pyobjus'"
There is no version of Pyobjus available for Python 3.6 on OSX and Pyobjus is required on the setup.py of Plyer. 
Any idea how to fix this?

**Comment by visualheroes** [comment]
Ok it seems to happen after a "coffee break" from the quota supervisor.

Full text:
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyer/utils.py", line 88, in _ensure_obj
>     mod = __import__(module, fromlist='.')
>   File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyer/platforms/macosx/notification.py", line 2, in <module>
>     from pyobjus import autoclass, protocol, objc_str, ObjcBOOL
> ModuleNotFoundError: No module named 'pyobjus'

**Comment by ghost** [comment]
i saw this too

**Comment by rkoxland** [comment]
I have the same problem. I switched off notify_me in session.set_quota_supervisor and it seems to have fixed it:

`session.set_quota_supervisor(notify_me=False)`

**Comment by yeyou4760** [comment]
ive tried this seems to be a ok work around for now!!

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)

**Comment by visualheroes** [comment]
@converge on OSX it is still not working even with the last requirements. Pyobjus is not available for python 3.7 on OSX and the only way to stop it happening is to switch notify_me to False as @rkoxland mentioned (thx by the way). ;)

**Comment by julienteyssier** [comment]
Same issue for me

**Comment by ishandutta2007** [comment]
> Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
> 
> ```
> pip3 install -r requirements.txt
> ```
> (if you use python3)

@converge  `pyobjus` is not there in `requirements.txt`.

@timgrossmann This is what this PR was for https://github.com/timgrossmann/InstaPy/pull/3864

I am still getting this error with latesst `instapy 0.1.3 `

This is the stacktrace:
> 
> INFO [2019-02-07 20:58:02] [top10in2mins]  Quota Supervisor: hourly follows reached quotient!	~going to sleep 4 minutes long
> 	take a coffee mexicano break? :>
> Traceback (most recent call last):
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/plyer/platforms/macosx/notification.py", line 8, in <module>
>     import pyobjus  # pylint: disable=unused-import
> ModuleNotFoundError: No module named 'pyobjus'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/plyer/utils.py", line 96, in _ensure_obj
>     mod = __import__(module, fromlist='.')
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/plyer/platforms/macosx/notification.py", line 11, in <module>
>     "pyobjus missing, please install it. "
> Exception: pyobjus missing, please install it. `python -m pip install git+http://github.com/kivy/pyobjus/`

@visualheroes Please reopen the issue, I don't see this being fixed.

**Comment by ishandutta2007** [comment]
@timgrossmann Please reopen the issue, I don't see this being fixed.

**Comment by xRyul** [comment]
>  "pyobjus missing, please install it. "

I get this message too. I just ignore it, the script still does all the interactions ( minus notifications) 

Though, would there be a proper fix in the near future?

**Comment by ishandutta2007** [comment]
> I just ignore it,

It is thrown when you overshoot quota limit right ? 
If you think it's meant to be ignored then what is the point of writing the code in the first place.
It's very important to get notified. You never know when you will get banned.

**Comment by xRyul** [comment]
> It is thrown when you overshoot quota limit right ?

Yep. Though, only on the first Quota reach. Notifications would be a nice feature. Not sure what @timgrossmann thinks about it. And whether its on his 'to do' list 😅 

For now I am just running it in my Terminal window in the background, I can always scrol through it to see how far it went (roughly). My quota, are not very big atm. Runs 24/7. I really need to find some time to drop it onto some Cluod Server. 

```
                                  peak_likes=(30,585),
                                  peak_follows=(24, 200),
                                  peak_comments=(24,200),
                                  peak_unfollows=(8, 200),
                                  peak_server_calls=(500, None))
```

**Comment by ishandutta2007** [comment]
My limits were similar but I got blocked 😅
Instagram has lots of logic beyond limits, so you can never be so sure.

**Comment by IamChhteri** [comment]
python3 -m pip install git+http://github.com/kivy/pyobjus/


above code for MacBook User.
due to pyobjus does not install defeault therefore the above command is used.
type the above line in your command line. It'll definitely work
