### ISSUE TITLE
How to make sure there is no errors when using crontab?

### ISSUE THREAD

**Issue by linus-dev** [InstaPy/InstaPy#3066]
Hello!

Can I in some way check if there is some errors when I have automated the bot using crontab on my raspberry pi? 

For example: check if the bot have had any errors and then view them on a web page. 
Add a line in my quickstart.py that upload the log to a web page maybe?

Is something of this possible?

Thanks!

**Comment by Mehran** [comment]
@linuscool2 

`0 8 * * * /usr/bin/python3 -xv /home/user/python3 quickstart.py >> /home/user/log.output`

you can see the output in `/home/user/log.output`

**Comment by linus-dev** [comment]
@Mehran 

Then I get this in my log.output:
```
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo


OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo




OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo


.....................................................................
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
```

**Comment by didamos99** [comment]
Try this 
24 2,8,9,13,15,16,19,23 * * * cd /home/yourfolder/instacron && /usr/bin/python3 ./instacron.py > /home/yourfolder/logs/nature/cronlognaturepost.txt 2>&1

**Comment by ghost** [comment]
http://lmgtfy.com/?q=check+logs+for+crontab+on+raspberrypi
