### ISSUE TITLE
HELP | Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by namesreallyblank** [InstaPy/InstaPy#3074]
I have the following issue whenever i try to run my template.

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-10-04 10:37:21] [myusername]  Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo

..............................................................
INFO [2018-10-04 10:37:55] [myusername]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-10-04 10:37:59] [myusername]  Sessional Live Report:
        |> LIKED 0 images  |  ALREADY LIKED: 0
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0
currently FOLLOWING 171 users & has got 869 FOLLOWERS

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-10-04 10:37:59] [myusername]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2018-10-04 10:37:59] [myusername]  Tag [1/3]
INFO [2018-10-04 10:37:59] [myusername]  --> tag1
Traceback (most recent call last):
  File "new.py", line 87, in <module>
    session.like_by_tags(random.sample(like_tag_list, 3), amount=random.randint(50, 100), interact=True)
  File "/root/InstaPy/instapy/instapy.py", line 1493, in like_by_tags
    self.logger)
  File "/root/InstaPy/instapy/like_util.py", line 209, in get_links_for_tag
    web_address_navigator(browser, tag_link)
  File "/root/InstaPy/instapy/util.py", line 778, in web_address_navigator
    current_url = get_current_url(browser)
  File "/root/InstaPy/instapy/util.py", line 1222, in get_current_url
    current_url = browser.execute_script("return window.location.href")
  File "/root/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 635, in execute_script
    'args': converted_args})['value']
  File "/root/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/root/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 375, in execute
    return self._request(command_info[0], url, body=data)
  File "/root/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/root/venv/local/lib/python2.7/site-packages/urllib3/request.py", line 72, in request
    **urlopen_kw)
  File "/root/venv/local/lib/python2.7/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/root/venv/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 322, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/root/venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/root/venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/root/venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/root/venv/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/root/venv/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=37513): Max retries exceeded with url: /session/2c3227ed91f15f768a6b04e5cfaa3bac/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6ca4ba0bd0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by Andercorp** [comment]
`import os
import time
import random
from instapy.util import smart_run
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = 'myusername'
insta_password = 'mypass'

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#   Settings.database_location = '/path/to/instapy.db'
#   Settings.chromedriver_location = '/path/to/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

like_tag_list = ['tag1', 'tag2', 'tag3']

dont_likes = ['sex','nude','naked','beef','pork','seafood',
            'egg','chicken','cheese','sausage','lobster',
            'schaf','ziege','hummer','yoghurt','joghurt','dairy',
            'eat','pancake','cake','dessert',
            'protein','essen','mahl','breakfast','lunch',
            'dinner','turkey','truthahn','plate','bacon',
            'sushi','burger','salmon','shrimp','steak',
            'schnitzel','goat','oxtail','mayo','fur','leather',
            'cream','hunt','gun','shoot','slaughter','pussy',
            'breakfast','dinner','lunch']
  
  
with smart_run(session):
    """ Activity flow """
    
session.set_quota_supervisor(enabled=True,
                             sleep_after=["likes_h", "comments_h", "follows_h", "unfollows_h", "server_calls_d"],
                             sleepyhead=True, stochastic_flow=True, notify_me=True,
                             peak_likes=(40, None),
                             peak_comments=(25, None),
                             peak_follows=(20, None),
                             peak_unfollows=(35, None),
                             peak_server_calls=(None, 3000))

session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.3,
 				  delimit_by_numbers=True,
 				   max_followers=10000,
 				    max_following=15000,
 				     min_followers=75,
 				      min_following=75)

session.set_simulation(enabled=False)


#                                                            **ACTIONS**
#                <<<<-------------------------------------------------------------------------------------------->>>>

    
    
#                                                        **INTERACTION SETTINGS**
#                <<<<-------------------------------------------------------------------------------------------->>>>

session.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')    
  
#                                                           **LIKES SETTINGS**
#                <<<<-------------------------------------------------------------------------------------------->>>>


session.set_delimit_liking(enabled=True, max=50, min=2)
session.set_dont_like(dont_likes)
session.set_do_like(enabled=True, percentage=100)
session.like_by_tags(random.sample(like_tag_list, 3), amount=random.randint(50, 100), interact=True)
    
    
#                                                            **COMMENTS SETTINGS**
#                <<<<-------------------------------------------------------------------------------------------->>>>

    # don't comment if a post already has more than 10 comments and a min of 2 comments
session.set_delimit_commenting(enabled=True, max=10, min=2)
session.set_do_comment(enabled=True, percentage=35)
session.set_comments(['some,' 'nice,' 'comments'])
    
    

#                                                           **FOLLOWING SETTINGS**
#                <<<<-------------------------------------------------------------------------------------------->>>>


session.set_do_follow(enabled=True, percentage=25, times=1)
  
  
  
#                                                          **UNFOLLOWING SETTINGS**
#                <<<<-------------------------------------------------------------------------------------------->>>>

    
session.set_dont_unfollow_active_users(enabled=True, posts=3)
session.unfollow_users(amount=random.randint(30,100), InstapyFollowed=(True, "all"),    
                           style="FIFO", unfollow_after=90*60*60, sleep_delay=501)
    
        

`

**Comment by namesreallyblank** [comment]
Here is my Quickstart Template

import os
import time
import random
from instapy.util import smart_run
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = 'myusername'
insta_password = 'mypass'

# set headless_browser=True if you want to run InstaPy on a server

# set these in instapy/settings.py if you're locating the
# library in the /usr/lib/pythonX.X/ directory:
#   Settings.database_location = '/path/to/instapy.db'
#   Settings.chromedriver_location = '/path/to/chromedriver'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

like_tag_list = ['tag1,' 'tag2', 'etc']
  
  
with smart_run(session):
    """ Activity flow """
    
session.set_quota_supervisor(enabled=True,
                             sleep_after=["likes_h", "comments_h", "follows_h", "unfollows_h", "server_calls_d"],
                             sleepyhead=True, stochastic_flow=True, notify_me=True,
                             peak_likes=(40, None),
                             peak_comments=(25, None),
                             peak_follows=(20, None),
                             peak_unfollows=(35, None),
                             peak_server_calls=(None, 3000))

session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.3,
 				  delimit_by_numbers=True,
 				   max_followers=10000,
 				    max_following=15000,
 				     min_followers=75,
 				      min_following=75)

session.set_simulation(enabled=False)


#                                                            **ACTIONS**
#                <<<<-------------------------------------------------------------------------------------------->>>>

    
    
#                                                        **INTERACTION SETTINGS**
#                <<<<-------------------------------------------------------------------------------------------->>>>

session.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')  
    
  
#                                                           **LIKES SETTINGS**
#                <<<<-------------------------------------------------------------------------------------------->>>>


session.set_delimit_liking(enabled=True, max=50, min=2)
session.set_dont_like(dont_likes)
session.set_do_like(enabled=True, percentage=100)
session.like_by_tags(random.sample(like_tag_list, 3), amount=random.randint(50, 100), interact=True)

    
    
#                                                            **COMMENTS SETTINGS**
#                <<<<-------------------------------------------------------------------------------------------->>>>

    # don't comment if a post already has more than 10 comments and a min of 2 comments
session.set_delimit_commenting(enabled=True, max=10, min=2)
session.set_do_comment(enabled=True, percentage=35)
session.set_comments(['nice comments'])
    
    

#                                                           **FOLLOWING SETTINGS**
#                <<<<-------------------------------------------------------------------------------------------->>>>


session.set_do_follow(enabled=True, percentage=25, times=1)
  
  
  
#                                                          **UNFOLLOWING SETTINGS**
#                <<<<-------------------------------------------------------------------------------------------->>>>

    
session.set_dont_unfollow_active_users(enabled=True, posts=3)
session.unfollow_users(amount=random.randint(30,100), InstapyFollowed=(True, "all"),    
                           style="FIFO", unfollow_after=90*60*60, sleep_delay=501)
