### ISSUE TITLE
install issues - (windows how-to #4 Clarifai

### ISSUE THREAD

**Issue by nate2799** [InstaPy/InstaPy#308]
Hey guys, I am trying to get this to work.  I have done all steps to date but get this when I run the GUI (or Start.bat  . 

![new error running gui](https://user-images.githubusercontent.com/29220989/27005277-24717de0-4de9-11e7-9a00-4ff07cdfdcee.png)

I have opened up instapy.py and can edit the file.  I am uncertain as to what to do here.  It says to:  4. Edit the instapy.py file

Open file instapy.py an disabling the clarifai import
comment the line "from clarifai.client import ClarifaiApi"
from clarifai.client import ClarifaiApi

I have done this but am uncertain if I have done it correctly or if I understand correctly.  Here is how I interpreted the instruction

![issues with install](https://user-images.githubusercontent.com/29220989/27005291-c28e864e-4de9-11e7-9a72-09871aa4a338.png)

**Comment by timgrossmann** [comment]
@nate2799 please post this issue at the GUI's repo... this is not InstaPy related. You shouldn't touch the instapy code .... ever!

**Comment by ahmadtibrahim** [comment]
Hey, did you solve the problem? I have the same problem too.

**Comment by Tidle999** [comment]
but in the manual it says to disable this string (step 4)
https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Windows.md
