### ISSUE TITLE
interact_by_users liking gives "element not found, skipping this user" error

### ISSUE THREAD

**Issue by jsib0** [InstaPy/InstaPy#3081]
## Expected Behavior
Takes a list of usernames and interacts with users based on the method written above interact_by_users(). In this case, I am taking my followers, and interacting with them through photo liking.

## Current Behavior
Once the application starts getting a user's image list - printed "Getting unclebudskitchen image list...", an error of "Element not found, skipping this username" is returned. 

## InstaPy configuration
    session = InstaPy(username='myusername',
                  password='mypassword',
                  headless_browser=True)

    with smart_run(session):
        """ Activity flow """
        # settings
        session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=4590,
                                        min_followers=45,
                                        min_following=77)
    
       #interact with followers
       popeye_followers = session.grab_followers(username="myusername", amount=10, live_match=True, store_locally=False)
       arr = [str(r) for r in popeye_followers]
       session.set_do_like(True, percentage=80)
       session.interact_by_users(arr, amount=3, randomize=True, media='Photo')

**Comment by VincenzoRu** [comment]
Hi @sibalajp ,
Did you find a solution to your problem?

I got exactly the same issue. Even if I use the other method **like_by_users** I got the same error. I'm surprised noone solved this yet.
