### ISSUE TITLE
Can you scale instapy ?

### ISSUE THREAD

**Issue by bardascat** [InstaPy/InstaPy#3083]
Hi Guys,

Does anybody tried scaling instapy for about 100 accounts in the same time ? 

I tried doing that using a 6 core cpu 32 GB ram and when i started about 50 instapy instances the cpu was about 100%.

I assume this is because of the chrome headless browser. I also tried disabling image rendering but no improvement.

I am only doing basic actions like scaning posts by hastags and liking them.

So do you have any tips for reducing instapy/chrome server footprint ? 

I was thinking to try using zombiejs instead of chrome. Is is said that zomiejs is a lighwaight and fast automated browser.

What do you have in mind about this topic ?

**Comment by timgrossmann** [comment]
@bardascat InstaPy is not meant for those purposes. It's meant for personal use or, at most, several accounts but not hundreds. 

If you choose to go that road, making money with it, be aware that I will personally make sure that you won't get any support at all. I've seen and talked to too many small companies/people that want/do make money with InstaPy and just abuse the Open-Source community around it by not giving a damn about giving back to them either through contributions or donations.

Please do understand this.
Thank you
Best
Tim
