### ISSUE TITLE
SETTING UP A NEW QUICKSART.PY FILE

### ISSUE THREAD

**Issue by AntonyS91** [InstaPy/InstaPy#3086]
Hi guys, I'm new to InstaPy.
I want to configure my own .py file to do lot's of things. For example I want to start adding the unfollow feature but I can't realize where I have to add this command in my quickstart.py file:

""session.unfollow_users(amount=126, nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)""
 
Do I have to create a new session?
And what the difference between "with smart_run(session):" and "session.login()" command that I see in some youtube tutorial?

Thanks a lot.

**Comment by HCWcoder** [comment]
@AntonyS91 

those examples might help you :[ click here](https://github.com/timgrossmann/InstaPy/issues/3033)

**Comment by AntonyS91** [comment]
Thank you so much @HCWcoder ! Now finally I have an idea how to structure the file! 
But I still miss something... What "with smart_run(session):" does? And how about "import random
from instapy import InstaPy" at the start of the code? They look something like c++ libraries...
Is there something that I can read to understand all the syntax?

**Comment by HCWcoder** [comment]
[this is all you need](https://github.com/timgrossmann/InstaPy/blob/master/README.md)
