### ISSUE TITLE
quickstart.py doesn't work on raspberry

### ISSUE THREAD

**Issue by AntonyS91** [InstaPy/InstaPy#3087]
I installed Instapy on a Raspberry pi3. When I lunch the quickstart, I get this error:

  File "quickstart.py", line 20
    session.set_relationship_bounds(enabled=True,
    ^
IndentationError: unexpected indent

This is my simple quickstart file....

```
# imports
from instapy import InstaPy


# login credentials
insta_username = 'xxx'
insta_password = 'xxx'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

                         
session.login()
    
    # settings
    session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=4590,
                                        min_followers=45,
                                        min_following=77)
    
    
    session.set_dont_like(["pizza", "#store"])
    
    
    # actions
    session.like_by_tags(["edm"], amount=5)

```
Where is the problem?
Thanks

**Comment by Nocturnal-2** [comment]
@AntonyS91 Please remove your id and password.

**Comment by AntonyS91** [comment]
yep! Thanks @Nocturnal-2 ! But it doesn't matter! It's an empty test account! It's not my personal! :)

**Comment by AntonyS91** [comment]
Please help... :(

**Comment by J2L-i** [comment]
I have the same issue. I get a "killed" returned when I run sudo xvfb-run python quickstart.py

Did this occur after recently updating it?
