### ISSUE TITLE
Kill InstaPy with sudo pkill -f 'scriptname.py' ??

### ISSUE THREAD

**Issue by linus-dev** [InstaPy/InstaPy#3089]
As the subject, can I kill InstaPy with `sudo pkill -f 'scriptname.py'` without destroying InstaPy?

If you kill the script with Ctrl+C you get 

> Session ended!
> oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
> 
> You have exited successfully.

etc...

I wonder if the pkill is a bad way of killing the script?

**Comment by ghost** [comment]
`Ctrl+z` stops my script
if you want to over complicate it, use:
```
ps aux | grep python
sudo kill -9 process #
```

**Comment by linus-dev** [comment]
@loopypanda 
Yes I can stop mine with `Ctrl+C` but I want to be able to stop it from the web by sending a command.
If I run `sudo pkill -f 'scriptname.py'`, then I dont get the message `You have exited successfully.`

I dont know if that last message matter or not...
