### ISSUE TITLE
Noob wants some help please <3

### ISSUE THREAD

**Issue by wemakefuture** [InstaPy/InstaPy#309]
Heyho, 

i am struggeling getting the InstaPy to run on Ubuntu 16.04 (1gb ram)

I used the fast install script from tim. I edited the instapy.py (nogui=True and no clarifai, outcommented, as i did it for windows)

When i want to run the quickstart it gets me following error: there is no pyvirtualdisplay
I case i want to install it it says its already there....i dont have a clue and didnt find any greatanswer in github or stackoverflow, so i am asking you <3

sorry to bother.  

![image](https://user-images.githubusercontent.com/28114725/27009564-d168e09e-4e91-11e7-9f10-a365998a69b3.png)

Kind regards basti

**Comment by MoritzGruber** [comment]
try run quickstart.py with python3:` python3 quickstart.py`

**Comment by wemakefuture** [comment]
Thank you thats it !
