### ISSUE TITLE
Date format for json files in 'relationship_data'

### ISSUE THREAD

**Issue by Nocturnal-2** [InstaPy/InstaPy#3090]
The JSON files written in 'relationship_data' folder has the date format as dd-mm-YYYY. This mixes up the old and new files when sorted by name (which is default). It will be convenient if it is in YYYY-mm-dd format. If others agree with it, I can make this change :)

**Comment by uluQulu** [comment]
Hi @Nocturnal-2 

>This mixes up the old and new files when sorted by name (which is default)

First of all let's clear what you are saying.
"_When I sort the relationship data files in my file explorer or through command utility, it happens so_"

_e.g._,
`11-08-2018~full~4608.json`
`11-08-2019~full~4608.json`   <-- this should be located at top [or bottom]
`14-09-2018~full~4660.json`

#### Fine, knowing that, I got your point.
But it is only for personal appearance, I mean, for internal usage, things does not work like that. I wrote that toolset and it uses a `glob` module in the appropriate datetime format to load the desired file for only one internal usage [yet].

Perhaps, your point is to be considered but the reason I chose **d-m-Y** over others is for readability.
Why do not you sort them by "date modified" or "date created" or "date added" or just by "date".

I still think **d-m-Y** is more readable and just for the purpose of having user sort them by name [for visual analysis] and seeing them in correct order [visually] costing from the readability does not pay.

----

Cheers 🐬
----

**Comment by Nocturnal-2** [comment]
@uluQulu 
> e.g.,
11-08-2018~full~4608.json
11-08-2019~full~4608.json <-- this should be located at top [or bottom]
14-09-2018~full~4660.json

Yes, this is what I meant.

> Perhaps, your point is to be considered but the reason I chose d-m-Y over others is for readability.

I agree with you!
