### ISSUE TITLE
Fail

### ISSUE THREAD

**Issue by JaviBalado** [InstaPy/InstaPy#3091]
Hi, i use this guide to debian: https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md   but i have the following fail:
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 12, in <module>
    import requests
ImportError: No module named requests
why?

**Comment by Nocturnal-2** [comment]
Try
`pip install -r requirements.txt`

**Comment by JaviBalado** [comment]
I have the same fail

**Comment by timgrossmann** [comment]
@JaviBalado Please try to use the search in the issues before opening up a new issue.
There are dozens of issue with the exact same problem.

You simply forgot to install the dependencies.
If you google for `no module named ...` there are dozens of results too.

Just do `pip install requests`. same for every other `no module named ...`

Please do understand that issues like this is taking away the focus on real issues.
Thank you for understanding.

Best
Tim

https://github.com/timgrossmann/InstaPy/issues?utf8=✓&q=is%3Aissue+no+module+named
https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests
