### ISSUE TITLE
Follow by location 

### ISSUE THREAD

**Issue by mhershfield** [InstaPy/InstaPy#3093]
## Why
Follow by location would be a valuable addition for users looking to grow their following in a certain geographic location. Currently there is the ability to 'like' by location to generate aware of your account by users that tagged themselves at that location. Following them seems like the next logical step.

## How
Create a new function with the same arguments as follow_user_following, except instead of usernames the function should accept an array of locations, similar to the 'like_by_locations' function. Based on the code that already exists it may be easier to repurpose the 'like_by_locations' function so that it clicks the follow button instead of like, but also with a sleep delay argument.

## What
Users will now be able to follow users that have tagged themselves in a particular geo

**Comment by sionking** [comment]
interact by location... and you should choose the percentage
