### ISSUE TITLE
Unfollow error with my own username

### ISSUE THREAD

**Issue by Miguel5252** [InstaPy/InstaPy#3095]
Instapy is no longer unfollowing. it terminates with **[MY USER ACCOUNT]** might be blocked. What does it means?

LOG:

INFO [2018-10-08 10:00:52] **[santaolallafoto]**  Starting to unfollow users..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-10-08 10:00:58] [santaolallafoto]  Unfollowing the users followed by InstaPy

ERROR [2018-10-08 10:01:27] [santaolallafoto]  --> Unfollow error with fabianaalejandrafrydman, maybe no longer exists...
INFO [2018-10-08 10:01:27] [santaolallafoto]  --> Removed '2018-10-08 09:56 ~ fabianaalejandrafrydman' from followedPool.csv file
ERROR [2018-10-08 10:01:58] [santaolallafoto]  --> Unfollow error with cristina.masso.7, maybe no longer exists...
INFO [2018-10-08 10:01:58] [santaolallafoto]  --> Removed '2018-10-08 09:57 ~ cristina.masso.7' from followedPool.csv file
ERROR [2018-10-08 10:02:09] [santaolallafoto]  Unfollow error!  ~**username santaolallafoto** might be blocked

**Comment by oscady** [comment]
I haven't looked into what mine's doing yet, was checking here to see if there were any recent unfollow errors solved. But my unfollow script is definitely not working anymore, the number of users I'm followig has  gone up loads in the last day or two.

I'll checkt to see if it's the same error I'm getting

**Comment by daniel-ed** [comment]
Same Error here! Unfollow doesn't work anymore since 2 or 3 days. There must be an issue!
