### ISSUE TITLE
issues retrieving likers count

### ISSUE THREAD

**Issue by gjbsaiia** [InstaPy/InstaPy#3096]
## Expected Behavior
retrieves likers count in order to guard likers from getting unfollowed
## Current Behavior
fails to pull down likers

**Comment by JosteinFraNorge** [comment]
What command in your script is failing? Can you post your quickstart.py script? (remember to remove username and password)

**Comment by gjbsaiia** [comment]
I'm using another tool as well as instapy, so I opted not to use quickstart.py.

essentially, I create the session in my main() - and pass it where I need it:
`insta_username = "john_doe"
insta_password = "changeMe"
session = InstaPy(username=insta_username, password=insta_password, headless_browser=True)`

It fails here:
`def unfollowUndesired(session):
	with smart_run(session):
		session.set_dont_unfollow_active_users(enabled=True, posts=5)
		session.unfollow_users(amount=500, allFollowing=True, style="RANDOM", unfollow_after=345600, sleep_delay=30)`

**Comment by gjbsaiia** [comment]
Sorry, I'm in Ireland and you're catching me at weird times

**Comment by gjbsaiia** [comment]
Specifically it fails on 'session.set_dont_unfollow_active_users(enabled=True, posts=5)', it's unable to retrieve likers from any posts

**Comment by gjbsaiia** [comment]
it's fine I built my own
