### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by derRoesser** [InstaPy/InstaPy#3099]
I followed the install instruction for ubuntu and no errors occurred by the installation. But if I execute the quickstart.py I get the following error:

`Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/home/multimediapc/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/home/multimediapc/InstaPy/instapy/instapy.py", line 12, in <module>
    import requests
ImportError: No module named requests
`

What can I do to make it work?

**Comment by timgrossmann** [comment]
#2956

**Comment by JanisSharma** [comment]
To install requests module on Debian/Ubuntu for Python2:

$ sudo apt-get install python-requests

And for Python3 the command is:

$ sudo apt-get install python3-requests

Full Source At [Here](https://icetutor.com/question/importerror-no-module-named-requests/)
