### ISSUE TITLE
The Content Security Policy directive 'upgrade-insecure-requests' is ignored when delivered in a report-only policy

### ISSUE THREAD

**Issue by HaimBendanan** [InstaPy/InstaPy#3102]
Hey :)

I see the following issue when doing every operation with instapy:
"The Content Security Policy directive 'upgrade-insecure-requests' is ignored when delivered in a report-only policy"

I am running in headless and without loading images. Maybe it is related?

![image](https://user-images.githubusercontent.com/14773715/46664945-0ce60180-cbcb-11e8-8093-92fff6f82f27.png)

**Comment by sionking** [comment]
> I am running in headless and without loading images. Maybe it is related?

related right

**Comment by JosteinFraNorge** [comment]
Im also getting this message. Anyone know why it happens?
Currently running in headless w/o images. Tried the oposite settings, but then the script froze for some strange reason.

Do you know if the message matters or not @uluQulu @sionking ?
Thanks

**Comment by Mizi91** [comment]
It seems related to headless browser. I turned it off and now script runs well.

**Comment by JosteinFraNorge** [comment]
Yes, this seems to be an issue only for Windows who runs Chrome in headless-mode. AFAIK the issue is known and is being worked on and is not interrupting with InstaPy in any way 😄
