### ISSUE TITLE
quota supervisor does account the "already" liked?

### ISSUE THREAD

**Issue by redsector72** [InstaPy/InstaPy#3105]
@uluQulu it's not clear to me if the quota supervisor does count the call to the like action or the actual successfull call.
I have a bunch of "already liked".
Maybe using the blacklist will help?
Thanks!

**Comment by uluQulu** [comment]
@redsector72 
Quota Supervisor does not have such a misbehavior as you have imagined.
**1**-) It checks the action [e.g. like] availability when entering the action [like] engine
**2**-) If a like is available, it tries to like
**3**-) If like is successful, it updates the likes record in the **recordActivity** table of the database

Shortly,
>it's not clear to me if the quota supervisor does count the call to the like action or the actual successfull call.

No. It will not update the likes' record in **recordActivity** table of the database which QS does use to check action availability cos "_already liked_" label is not a successful like.

If you read a bit of source code, you could realize all of that.

-------

Cheers 😀
-----

**Comment by redsector72** [comment]
thanks @uluQulu, I was unsure from the source code. I've not yet used it.
from the readme seems there is a jump out function, but it is not clear.
If I don't specify sleep, then it jump out?
