### ISSUE TITLE
When I try to add commenting in quickstart, I get a taberror and the programs shuts down

### ISSUE THREAD

**Issue by pinkoveralls** [InstaPy/InstaPy#3111]
It works with following and liking, but when I add commenting from the front page I get:

```
H:\InstaPy>python quickstart.py
  File "quickstart.py", line 32
    session.set_do_comment(enabled=True, percentage=25)
                                                      ^
TabError: inconsistent use of tabs and spaces in indentation
```

My configuration is:

```
""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = 'XXX'
insta_password = 'XXX'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # settings
    session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=4590,
                                        min_followers=45,
                                        min_following=77)
    
    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])
    session.set_do_follow(enabled=True, percentage=10, times=2)
	session.set_do_comment(enable=True, percentage=25)
	session.set_comments(['Awesome'])
    
    # actions
    session.like_by_tags(['XXX'], amount=10)
```

I'm not sure why the commenting is showing as extra tabbed in, it looks normal on my notepad and I copied it straight from the front page. I'm not sure what I'm doing wrong, any help would be appreciated. Also if anybody would be up for sharing their quickstart setup, I would really appreciate it!

**Comment by IH4xx3R** [comment]
The error says : "TabError: inconsistent use of tabs and spaces in indentation"
So you need do delete these spaces (red ones) :

![bildschirmfoto-2018-10-10-um-17 46 30](https://user-images.githubusercontent.com/29124225/46748797-ab9a5d00-ccb4-11e8-91d2-bb0aa67352a4.png)

**Comment by pinkoveralls** [comment]
@IH4xx3R 

Hi, thank you for your reply. They show up here when I copy and past the format here, but not in Notepad++ when I'm editing it (everything looks correct there). I've tried retyping it, but it still shows up as indented when I paste it, so I'm not sure how to remove them.

**Comment by GitNees** [comment]
Pasting can mess this up, it is python that is very sensitive to spaces /taberrors. Everything must be equally spaced per level. You will need to figure it out... Remove the spaces till it is ok. Cant help more then that.

**Comment by pinkoveralls** [comment]
I fixed the error by using multiple spaces instead of tab to indent, there was some weird grouping going on when I used tab in Notepad++ and it was grouping the subsequent lines under the top line even though everything looked correct.
