### ISSUE TITLE
smells of a temporary block

### ISSUE THREAD

**Issue by rayanakiki** [InstaPy/InstaPy#3117]
What does this mean?
Last follow is not verified!	~smells of a temporary block

**Comment by CharlesCCC** [comment]
it means "temporary block" 
try reduce your interaction amount and it should improve.

**Comment by Ronbalt** [comment]
@rayanakiki I get this too every time I reach 7500 Following count.

**Comment by CharlesCCC** [comment]
@Ronbalt 7500 following within 24 hours ???

**Comment by Ronbalt** [comment]
@CharlesCCC No, total amount.
When I reach 7500 following amount, I cannot follow new ones.

**Comment by CharlesCCC** [comment]
@Ronbalt If I remember right, 7500 is the limit set by Instagram. You will have to unfollow some users first, but make sure you don't follow too many users within a 24 hours period.

**Comment by Ronbalt** [comment]
@CharlesCCC I have some issues with unfollowing, maybe we can chat about this in private?
