### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by AlexandruAcea** [InstaPy/InstaPy#312]
Hey guys, I've been using the bot for a while, but lately it keeps giving this error: IndexError: list index out of range. It usually happens after 5 accounts liked, or less. Do you have any idea of how I can fix this? Thank you!

**Comment by RiboPg** [comment]
same problem
browser.execute_script("arguments[0].value = '" + rand_comment + " ';", comment_input[0]);
IndexError: list index out of range
but just for some tags

**Comment by bigcotton** [comment]
Absolute beginner here: I think I got the same problem, but it occurs only when it tries to comment a picture

![170615_bug](https://user-images.githubusercontent.com/24789653/27195756-466dc0b6-5208-11e7-9757-9ed4ce97e5eb.png)
^
I am thankful for any help

**Comment by Sancccc** [comment]
Same here. Happens only when I unfollow users.
I have 7 500 followed users (max limit set by Instagram I guess) but it also happened a while ago when I had back to 3k users followed

**Comment by awb715** [comment]
Traceback (most recent call last):
  File "index.py", line 4, in <module>
    session.login()
  File "/var/www/instapy/instapy/instapy.py", line 124, in login
    if not login_user(self.browser, self.username, self.password):
  File "/var/www/instapy/instapy/login_util.py", line 24, in login_user
    action = ActionChains(browser).move_to_element(inputs[0]).click().send_keys(username) \
IndexError: list index out of range

This just started happening for me also!

**Comment by westondeboer** [comment]
@awb715 I changed login_util.py line 23 from: 

`    inputs = browser.find_elements_by_xpath("//form/div/input")
`

to

`    inputs = browser.find_elements_by_xpath("//form/div/div/input")
`

and it works. did instagram change the location of the form?

**Comment by mihikadutta** [comment]
@westondeboer yes, i see that an additional div has been added in the input field wrapper in the login form.
