### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by namesreallyblank** [InstaPy/InstaPy#3126]
after I finished configuring my template, I went ahead test it but got this

`(venv) root@InstaBoosta:~/InstaPy# python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 12, in <module>
    import requests
ImportError: No module named requests`
Please can anyone help me?

**Comment by mehrabcz** [comment]
pip install requests

**Comment by mehrabcz** [comment]
> after I finished configuring my template, I went ahead test it but got this
> 
> `(venv) root@InstaBoosta:~/InstaPy# python quickstart.py Traceback (most recent call last): File "quickstart.py", line 4, in <module> from instapy import InstaPy File "/root/InstaPy/instapy/__init__.py", line 2, in <module> from .instapy import InstaPy File "/root/InstaPy/instapy/instapy.py", line 12, in <module> import requests ImportError: No module named requests`
> Please can anyone help me?
pip install requests

**Comment by guilhermelucasfreitas** [comment]
hello!

I try `sudo pip install requests` 
But I did not succeed.

  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 12, in <module>
    import requests
ImportError: No module named requests
