### ISSUE TITLE
InstaPy Firefox Headless

### ISSUE THREAD

**Issue by w4ngel** [InstaPy/InstaPy#3128]
Are there any particular problems with running InstaPy in Firefox headless? They have recently changed how Firefox deals with headless clients, it's a lot more efficient now.

**Comment by converge** [comment]
> it's a lot more efficient now

why ?

I only use FF on InstaPy-Light

**Comment by w4ngel** [comment]
> > it's a lot more efficient now
> 
> why ?
> 
> I only use FF on InstaPy-Light

Chrome doesn't support extensions in it's built-in headless mode and XVFB provides a whole host of issues with chrome when running over an extended period of time. But the main benefits of FF is that you can do all sorts of cool things to speed up load times and to save bandwidth. I am personally just wondering why it isn't an option but only default FF is, was there a particular reason against it or was it just never implemented? I know you have to use GeckoDriver with it, but that is really well maintained.

**Comment by sionking** [comment]
FF headless is kind of new thing ...

**Comment by w4ngel** [comment]
> FF headless is kind of new thing ...

Yeah I get that, I am going to run some tests with it. My main reasoning behind wanting to see it added is that FF headless supports extensions.

**Comment by w4ngel** [comment]
So I ran a couple of tests with FF, the extension creation process is slightly different to chrome, but it does work in headless. The actual browser itself takes slightly longer at loading certain elements, particularly the login screen so sleeps need to be increased or explicit waits. When I test a bit more I'll make a PR adding support for it.

**Comment by converge** [comment]
I was able to run chromedriver/chrome headless some months ago using uBlock extension for a project.
