### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown command

### ISSUE THREAD

**Issue by kamushadenes** [InstaPy/InstaPy#313]
Hello,

When I try to run the script, I get:

 /dropbox/kamushadenes/Projects/InstaPy   master *  python script.py                                                                                                                                                           Thu 02:03
Logged in successfully!                                    
Traceback (most recent call last):                         
  File "script.py", line 16, in <module>               
    session.login()                                        
  File "/dropbox/kamushadenes/Projects/InstaPy/instapy/instapy.py", line 89, in login                                  
    log_follower_num(self.browser, self.username)          
  File "/dropbox/kamushadenes/Projects/InstaPy/instapy/print_log_writer.py", line 10, in log_follower_num              
    followed_by = browser.execute_script("return window._sharedData.entry_data.ProfilePage[0].user.followed_by.count") 
  File "/home/kamushadenes/.pyenv/versions/InstaPy/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 484, in execute_script                                                                                            
    'args': converted_args})['value']                      
  File "/home/kamushadenes/.pyenv/versions/InstaPy/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 249, in execute                                                                                                   
    self.error_handler.check_response(response)            
  File "/home/kamushadenes/.pyenv/versions/InstaPy/lib/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 164, in check_response                                                                                         
    raise exception_class(value)                           
selenium.common.exceptions.WebDriverException: Message: unknown command: session/11545b19b14e893ff375595db0be4012/execute/sync

**Comment by kamushadenes** [comment]
If I set followed_by to a fixed number at print_log_writer.py, it proceeds fine until it's time to like something:

Traceback (most recent call last):                         
  File "leiatambem.py", line 24, in <module>               
    session.like_by_tags(like_tags, amount=100)            
  File "/dropbox/kamushadenes/Projects/InstaPy/instapy/instapy.py", line 383, in like_by_tags                          
    self.username, self.like_by_followers_upper_limit, self.like_by_followers_lower_limit)                             
  File "/dropbox/kamushadenes/Projects/InstaPy/instapy/like_util.py", line 170, in check_link                          
    post_page = browser.execute_script("return window._sharedData.entry_data.PostPage")                                
  File "/home/kamushadenes/.pyenv/versions/InstaPy/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 484, in execute_script                                                                                            
    'args': converted_args})['value']                      
  File "/home/kamushadenes/.pyenv/versions/InstaPy/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 249, in execute                                                                                                   
    self.error_handler.check_response(response)            
  File "/home/kamushadenes/.pyenv/versions/InstaPy/lib/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 164, in check_response                                                                                         
    raise exception_class(value)                           
selenium.common.exceptions.WebDriverException: Message: unknown command: session/278b0e6ab95a1a050842e38ba7c8f9fd/execute/sync

**Comment by kamushadenes** [comment]
Basically, it seems that I'm unable to execute any call to browser.execute_script()

**Comment by timgrossmann** [comment]
@kamushadenes Could you do `ps aux` on your server and check if there are several instances of chrome running? #319

**Comment by kamushadenes** [comment]
Apparently there is 

`kamusha+ 30981  1.2  0.1 204232 30860 pts/8    Sl+  09:07   0:00 ./assets/chromedriver --port=40491                    
kamusha+ 31026 17.1  0.7 1014220 129328 pts/8  Sl+  09:07   0:02 /opt/google/chrome/chrome --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disab --disable-web-resources --dns-prefetch-disable --enable-automation --enable-logging --ignore-certificate-errors --lang=en-US --load-extension=/tmp/.org.chromium.Chromium.M6YcEm/internal --log-level=0 --metrics-recording-only --no-first-run --no-sandbox --password-store=basic --remote-debugging-port=12317 --safebrowsing-disable-auto-update --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.SQCfyk data:,                                                   
kamusha+ 31041  0.0  0.2 375212 41900 pts/8    S+   09:07   0:00 /opt/google/chrome/chrome --type=zygote --enable-logging --log-level=0 --no-sandbox --user-data-dir=/tmp/.org.chromium.Chromium.SQCfyk                                        
kamusha+ 31042  0.0  0.0  26908  3560 pts/8    S+   09:07   0:00 /opt/google/chrome/nacl_helper --no-sandbox           
kamusha+ 31111  8.6  0.6 495680 109496 pts/8   Sl+  09:07   0:01 /opt/google/chrome/chrome --type=gpu-process --enable-loggi el=0 --no-sandbox --user-data-dir=/tmp/.org.chromium.Chromium.SQCfyk --supports-dual-gpus=false --gpu-driver-bug-workarounds=7,23,71 --gpu-vendor-id=0x10de --gpu-device-id=0x1c60 --gpu-driver-vendor=NVIDIA --gpu-driver-version=381.22 --gpu-driver-date --user-data-dir=/tmp/.org.chromium.Chromium.SQCfyk --enable-logging --log-level=0 --service-request-channel-token=903CC8399D698A144C4EA1DA694F352F --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd                     
kamusha+ 31519  0.8  0.3 1009104 62900 pts/8   Sl+  09:07   0:00 /opt/google/chrome/chrome --type=renderer --enable-logging --log-level=0 --no-sandbox --test-type=webdriver --primordial-pipe-token=0083E78462E65EAFD16E5F0D9FF62A1C --lang=en-US --user-data-dir=/tmp/.org.chromium.Chromium.SQCfyk --extension-process --disable-client-side-phishing-detection --enable-offline-auto-reload --enable-offline-auto-reload-visible-only --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --service-request-channel-token=0083E78462E65EAFD16E5F0D9FF62A1C --renderer-client-id=4 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd      
kamusha+ 31624 46.2  1.1 1190956 178772 pts/8  Rl+  09:07   0:02 /opt/google/chrome/chrome --type=renderer --enable-logging --log-level=0 --no-sandbox --test-type=webdriver --primordial-pipe-token=8F3D497E7DD9B0160252BACBE56EAC3C --lang=en-US --user-data-dir=/tmp/.org.chromium.Chromium.SQCfyk --disable-client-side-phishing-detection --enable-offline-auto-reload --enable-offline-auto-reload-visible-only --enable-pinch --num-raster-threads=4 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --service-request-channel-token=8F3D497E7DD9B0160252BACBE56EAC3C --renderer-client-id=5 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd   `


But they all belong to the process and were opened by it.

Also, I'm running it on a i7 with 32GB ram, so it's very unlikely it's a resource problem.

**Comment by kamushadenes** [comment]
Hey @timgrossmann, I still have the issue.

Have I missed something after your last commit?
