### ISSUE TITLE
 Failed to get posts count on your profile!  ~empty string

### ISSUE THREAD

**Issue by dataninjato** [InstaPy/InstaPy#3130]
## Expected Behavior
no error

## Current Behavior
  Failed to get posts count on your profile!  ~empty string
Traceback (most recent call last):
  File "qs1.py", line 16, in <module>
    session.set_dont_unfollow_active_users(enabled=True, posts=5)
  File "/home/insta1/InstaPy/instapy/instapy.py", line 3158, in set_dont_unfollow_active_users
    self.logger)
  File "/home/insta1/InstaPy/instapy/util.py", line 289, in get_active_users
    "//div[contains(@class, '_9AhH0')]")[0]

previous issues reviewed and checked around the format_number and total_posts in util.py but the code had changed in the meanwhile
you wanted people to let you know when it occurs again

util.py around line 289
`

    try:
        latest_post = browser.find_elements_by_xpath(
                            "//div[contains(@class, '_9AhH0')]")[0]
        click_element(browser, latest_post)

    except (NoSuchElementException, WebDriverException):
        logger.warning("Failed to click on the latest post to grab active likers!\n")
        return []
`

**Comment by metapodcod** [comment]
this problem seems to persist
