### ISSUE TITLE
Doesn't really unfollow every user.

### ISSUE THREAD

**Issue by tiaringhio** [InstaPy/InstaPy#3131]
## Expected Behavior
After the bot is done liking and following profiles, it should unfollow every profile it has followed.

## Current Behavior
The bot unfollows only some of the users, leaving my profile with 20ish more follower than before and i have to follow them manually. It removes the users from the blacklist though.

## InstaPy configuration

from instapy import InstaPy

insta_username = 'username'
insta_password = 'password'

try:
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      multi_logs=True)
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
                  delimit_by_numbers=True,
                   max_followers=20000,
                    max_following=5555,
                     min_followers=100,
                      min_following=30)

    # actions
    session.set_user_interact(amount=4, randomize=True, percentage=50, media='Photo')
    session.set_do_follow(enabled=True, percentage=75)
    session.set_do_like(enabled=True, percentage=30)
    session.set_dont_like(['nude', 'sex', 'porn', 'feet'])
    session.set_smart_hashtags(['portrait', 'follow', 'photography', 'like', 'landscape'], limit=5, sort='top', log_tags=True)
    session.like_by_tags(amount=8, use_smart_hashtags=True)
    session.set_blacklist(enabled=True, campaign='nope')
    session.unfollow_users(amount=80, InstapyFollowed = (True, "all"), style = 'FIFO', sleep_delay=60, unfollow_after=30 )

finally:
    # end the bot session
    session.end()

**Comment by GabrieleCalarota** [comment]
I see what you are saying and experienced that too. It seems like it is an unfollow problem, because people are removed from the followedPool even if they haven't really been unfollowed.

**Comment by tiaringhio** [comment]
That's exactly what the problem is! I really don't know how to resolve it though.

**Comment by sionking** [comment]
The issue is unfollow block you get.
The only way to verify unfollowing is to sync the profile every now and then with previous unfollowed.

And please don't unfollow more than 100-200 each time.

**Comment by tiaringhio** [comment]
Thank you sionking.
How do I resolve this issue? What do you mean with syncing the profile?
Also, the max amount of unfollow I have is usually 70/80.
Thank you for your time

**Comment by ghost** [comment]
@tiaringhio  The max you unfollow a day is only 70/80 ?very small amount....

**Comment by tiaringhio** [comment]
@loopypanda oh no I'm sorry, I thought he meant per session. A day it's a lot more I think

**Comment by GabrieleCalarota** [comment]
I don't think it's a block @sionking
I've noticed that if you unfollow from the automated pool, sometimes you delete one line even if you didn't really unfollowed that account. It's maybe in the check_unfollow function or something around there

**Comment by GabrieleCalarota** [comment]
any updates?

**Comment by tiaringhio** [comment]
Unfortunately the behavior has remained the same. It still unfollows only a certain amount of profiles but removes all the profiles it followed through the session
