### ISSUE TITLE
session.interact_user_followers regulary ends after simulated follow and then session ends "clean" but without further interaction

### ISSUE THREAD

**Issue by GitNees** [InstaPy/InstaPy#3138]
## Expected Behavior
session.interact_user_followers(['instauser'], amount=20, randomize=True)
Should interact with 20 user from certain account. This does work from time to time, but sometimes just ends the session after a simulated follow, as shown below. It stops the session, not errors and closes the script. So the next schedule cant run. When it does work, it will end session but keep the script open so next can start later. 

So something makes it crash, but there is no error anywhere in the logs. 
## Current Behavior
INFO [2018-10-12 18:33:39] [XXX]  User 'YYYYYYYY' [1/1]
INFO [2018-10-12 18:33:48] [XXX]  Simulated follow : 1
INFO [2018-10-12 18:33:51] [XXX]  --> Followed 'b'someuser''!
INFO [2018-10-12 18:33:57] [XXX]  Sessional Live Report:
	|> LIKED 79 images  |  ALREADY LIKED: 1

As you see, it goes from Followed some user, to the session live report with stats. 
When it does work out correctly, it grabs 19 users from that YYYYYYY-user and runs as expected.

## Possible Solution (optional)
Add more logging, seems something is broken but not always.

**Comment by boldestfortune** [comment]
So I had this issue a while ago, and someone found a temporary workaround for me. https://github.com/timgrossmann/InstaPy/issues/2809#issuecomment-418110236

I tried it again, and It seemed to fix the issue.
