### ISSUE TITLE
My log says Image liked! But actually it's not like anything.

### ISSUE THREAD

**Issue by tr1cky6uy** [InstaPy/InstaPy#3139]
I've seen some posts about it but none of them was helpful for me.
Thank you! :)

**Comment by ghost** [comment]
your shadow banned from liking ... stop running script for 24 hours and make sure at least 60-65 seconds goes by before each like.

**Comment by tr1cky6uy** [comment]
They can ban only from liking? Cause comments are working.

**Comment by sionking** [comment]
they fight liking

**Comment by tr1cky6uy** [comment]
where do i implement the delay between likes?
