### ISSUE TITLE
No4  on the guide doesnt make sense

### ISSUE THREAD

**Issue by ujazzz** [InstaPy/InstaPy#314]
https://timgrossmann.github.io/InstaPy/How_to_Windows.html

what does it mean to an disabling the clarify import?

**Comment by timgrossmann** [comment]
@ujazzz you have to comment the clarifai lines by just adding a "#" character

**Comment by ujazzz** [comment]
comment where?

**Comment by timgrossmann** [comment]
@ujazzz Google how to add comments to python code...

Please better ask this on the github page of the actual GUI. This is not a InstaPy issue.

**Comment by ujazzz** [comment]
but is it necessary to add the comment? whats the point of it?

**Comment by timgrossmann** [comment]
@ujazzz I don't know, sorry. Just use my script if you want me to help.
You have to ask the GUI that built the GUI why you should do that.
