### ISSUE TITLE
Maximum script efficiency for one machine

### ISSUE THREAD

**Issue by Mizi91** [InstaPy/InstaPy#3141]
Hi,
I'm opennig this topic for discussion about script efficiency on a single machine. For example: you have one working station at your home and you need to run instapy on multiple accounts with maximal time effectivity.

Basic questions:
**1) How many instapy scripts are safe for one IP?**
**2) How many scripts can average computer run?**
- #2842 (is it really 50+ on i7 8700K)?

**3) What would be best timing with quota_supervisor?**
- for example your first account reaches quota_supervisor and needs 7-8 hour rest. You can switch script to other account in the meantime? Can this be automated?

**Comment by Mizi91** [comment]
I'm now trying to run 2 instances of instapy at the same time with multi_logs=True.

**Comment by ghost** [comment]
you could use crontab to automate... cheap $100 laptop with linux can easily run 3 accounts..... maybe 10 maybe 20 but you need to have proxies and sms verification method to do this. just setup on a server and upscale if you need.

**Comment by Mizi91** [comment]
> you could use crontab to automate... cheap $100 laptop with linux can easily run 3 accounts..... maybe 10 maybe 20 but you need to have proxies and sms verification method to do this. just setup on a server and upscale if you need.

Thank you. So do you think 3 accounts are safe for one IP (home connection)?

**Comment by trooperas** [comment]
I run 4 of them on separate VMs and i have no problem so far!

**Comment by varun13169** [comment]
Considering IG app supports 5 accounts over same IP, it'll be safe to say 5.
