### ISSUE TITLE
Phone verification

### ISSUE THREAD

**Issue by IKDH** [InstaPy/InstaPy#3144]
## Current Behavior

Since few days, I have a lot of phone verification on my Instagram accounts. The Instagram accounts which had this phone verification were disable (it was impossible to find them on Instagram) and they have been reactivating after the phone verification. Have you guys noticed the same problem ?
All the impacted accounts are runing a follow / unfollow script from VPS.

**Comment by sionking** [comment]
fake accounts created in VPS ?

**Comment by IKDH** [comment]
No, real accounts. I have a lot of accounts and they are running on a lot of VPS since many months. Friday, a dozen of them (which are runing on the same hosteur and which have the same subnet : 123.22.33.1,123.22.33.2, ... for example) have experienced phone verification for the first time.

**Comment by sionking** [comment]
same VPS same ip, don't run more than 2-3 on same ip.

**Comment by HCWcoder** [comment]
im having the same issue it wasnt before and im running instapy since 9 months
