### ISSUE TITLE
Is it better to record everything in the instapy.db?

### ISSUE THREAD

**Issue by tiymfony** [InstaPy/InstaPy#3149]
Hi I'm relatively new to this repo and to coding in general. This is more of a question than a feature request which I hope I can get a quick answer to:
## Current Behavior
Why is instapy designed to make .csv files to keep certain records rather than recording everything to the DB that already exist. IG servers can't be throttled, so isn't there plenty of time and incentive to keep it in the DB?
## Possible Solution (optional)
 I imagine it would be easier to compare instances and then implement some short optimization scripts. I'm working through the api to refactor this for myself, if not just to sharpen my coding skills. I'd like to know if anyone would find this as an interesting feature.

**Comment by Nocturnal-2** [comment]
I have the same question. If there is a reason why we chose csv over writing to database, could some please refer me to those discussions? Thanks in advance!
