### ISSUE TITLE
I get an error message when I run InstaPy Gui

### ISSUE THREAD

**Issue by ujazzz** [InstaPy/InstaPy#315]
As soon as I put my login details in the GUI and select an option to like 50 tags at london. it starts the command prompt and closes in a second. I managed to take a screenshot and this is what it shows.

![instapy error](https://user-images.githubusercontent.com/29471597/27246964-1aaea7c2-52c3-11e7-95a4-d1e3d12da0b2.png)

https://ibb.co/eW6s7k

**Comment by timgrossmann** [comment]
@ujazzz https://pypi.python.org/pypi/past/0.11.1

`pip install future`

Please post issues regarding the GUI on the actual GitHub page...

**Comment by ujazzz** [comment]
works completely fine now. All I had to do was 
`pip install future`

in python and then run the GUI again.

Thanks for the help!
