### ISSUE TITLE
Recomanded provider for Proxy rent ?

### ISSUE THREAD

**Issue by HCWcoder** [InstaPy/InstaPy#3150]
Please can someone recommend a website to by good quality proxy and be safe ?
and what type of proxy i need 
thanks
@sionking 
@uluQulu 
@timgrossmann

**Comment by sionking** [comment]
None sorry.
At least none will give you the amount of liking and following you get with home address.
Please find my post about it.

**Comment by HCWcoder** [comment]
okey so what do you suggest ?

can you link that post im not finding it
@sionking 

edit : 
never mind i found it !

**Comment by Nocturnal-2** [comment]
@HCWcoder Could you please share your finding?

**Comment by converge** [comment]
hey guys, I have been using Blazing Proxies for more than a year, they have an amazing work, fast support channel and I had 0 bans and issues.

Something that I like is that you have to add your IP to a white list, that means, even if someone know your proxies setting (ip/port), they wont be allowed to use it.

this is my refferal code if you want to try it:
https://billing.blazingseollc.com/hosting/aff.php?aff=583

**Comment by converge** [comment]
*use dedicated proxy (not semi or shared)
