### ISSUE TITLE
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#3151]
@uluQulu hi my friend :) Any suggestions?

Traceback (most recent call last):
  File "/home/fredrik/InstaPy/5bba4f87475a3400131492df.py", line 26, in <module>
    session.interact_user_followers([xx], amount=70, randomize=True)
  File "/home/fredrik/InstaPy/instapy/instapy.py", line 2184, in interact_user_followers
    self.logfolder)
  File "/home/fredrik/InstaPy/instapy/unfollow_util.py", line 906, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/home/fredrik/InstaPy/instapy/unfollow_util.py", line 644, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 393, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"}
  (Session info: headless chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.15.0-36-generic x86_64)

**Comment by escariao** [comment]
> @uluQulu hi my friend :) Any suggestions?
> 
> Traceback (most recent call last):
> File "/home/fredrik/InstaPy/5bba4f87475a3400131492df.py", line 26, in 
> session.interact_user_followers([xx], amount=70, randomize=True)
> File "/home/fredrik/InstaPy/instapy/instapy.py", line 2184, in interact_user_followers
> self.logfolder)
> File "/home/fredrik/InstaPy/instapy/unfollow_util.py", line 906, in get_given_user_followers
> channel, jumps, logger, logfolder)
> File "/home/fredrik/InstaPy/instapy/unfollow_util.py", line 644, in get_users_through_dialog
> dialog = browser.find_element_by_xpath(dialog_address)
> File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 393, in find_element_by_xpath
> return self.find_element(by=By.XPATH, value=xpath)
> File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
> 'value': value})['value']
> File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
> self.error_handler.check_response(response)
> File "/home/fredrik/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"}
> (Session info: headless chrome=69.0.3497.100)
> (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.15.0-36-generic x86_64)

Same issue!!!

**Comment by fgisslen** [comment]
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"}
