### ISSUE TITLE
Work with the Database to unfollow users

### ISSUE THREAD

**Issue by jj870** [InstaPy/InstaPy#3153]
**Hi,**
**i would like to know hows doest it work with the database ?**
**when i following users than how can i save the profiles which i followed to unfollow them after?**

**do i need to install the database by myself or its done automatically?**

**thanks :)**

**Comment by arcasoy** [comment]
I also am wondering this. I was going to use SQLite on my Raspberry Pi but don't know how to grab the names of the users that are followed.
