### ISSUE TITLE
Windows task scheduler and smart_run

### ISSUE THREAD

**Issue by RafNadler** [InstaPy/InstaPy#3154]
## Expected Behavior
Windows to launch an instance of InstaPy at a given time

## Current Behavior
The task starts and stops instantly. If I run my .py files manually in command line, it works properly. It fails only when windows tries to launch them automatically.

## InstaPy configuration
I am using the smart_run with venv as described in the newest quickstart.py file. Since then, my scheduled tasks do not work. Any ideas on how to fix this ?

**Comment by alexsmedile** [comment]
Since I'm facing the same issue, and I am also not really that good understanding programming languages, I'd like to ask: what does the new _"with smart_run"_ do? Can I still use my older code or do I need to upgrade? What is _"with"_ ?
