### ISSUE TITLE
workaround for session.follow_user_followers problem & new issue

### ISSUE THREAD

**Issue by boldestfortune** [InstaPy/InstaPy#3161]
## Expected Behavior
`session.follow_users `breaks after following for a few minutes. I've had this problem before https://github.com/timgrossmann/InstaPy/issues/2809#issuecomment-418110236 and a workaround was posted there so full credit goes to @michelalbers. 

Anyone having this issue, give this a try. It fixed the problem again this time around for me.

**_New Issue_**

While `session.follow_user_followers` was running, Instapy was following suggested accounts not in anyway related to target account. Maybe Instagram made some overnight changes that's causing this? Is this something that you guys are already aware of? @uluQulu @timgrossmann @sionking . I can make a separate Issue if that's better, to keep these separate. 

## Possible Solution (optional)

 Around line 728 in `instapy/unfollow_util.py` edit the `dialog_username_extractor` to look as follows:

``` Python
def dialog_username_extractor(buttons):
    """ Extract username of a follow button from a dialog box """

    if not isinstance(buttons, list):
        buttons = [buttons]

    person_list = []
    for person in buttons:

        try:
            if person and hasattr(person, 'text') and person.text:
                try:
                    person_list.append(person.find_element_by_xpath("../../../*")
                            .find_elements_by_tag_name("a")[1].text)

                except IndexError:
                    pass  # Element list is too short to have a [1] element
        except StaleElementReferenceException:
            pass  # Dont know why this happens, just ignore

    return person_list

``` 

I didn't make PR because I'm an amateur and this isn't my code, but I can if it's preferred.

Cheers!

**Comment by Olcaey** [comment]
Seems like the same issue for me and your solution does not help. Bot still takes accounts from recommended list and tries to follow them afterwards.

**Comment by boldestfortune** [comment]
Yeah I know. This solution isn't for the recommended list issue. It's for
session.follow_user_followers crashing instapy partway through its
operation. Sorry for the mixup.

**Comment by michelalbers** [comment]
My "fix" is just an ignore statement and not really a fix for the underlying problem. Its like giving painkillers to someone with a broken leg. Lowers the pain but does not fix the leg ;) I would not recommend to merge this into master. Thanks for credit though!

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
