### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib3'

### ISSUE THREAD

**Issue by DNUSH** [InstaPy/InstaPy#3167]
## Current Behavior

D:\Documents\GitHub\InstaPy>$ python quickstart.py
"$" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

D:\Documents\GitHub\InstaPy>python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "D:\Documents\GitHub\InstaPy\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "D:\Documents\GitHub\InstaPy\instapy\instapy.py", line 12, in <module>
    import requests
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests-2.20.0-py3.6.egg\requests\__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'

D:\Documents\GitHub\InstaPy>

## InstaPy configuration

from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = 'g'
insta_password = 'tes'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # settings
    session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=4590,
                                        min_followers=45,
                                        min_following=77)
    
    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])
    
    
    # actions
    session.like_by_tags(["natgeo"], amount=10)

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)
