### ISSUE TITLE
"Chromedriver is missing"

### ISSUE THREAD

**Issue by DominicFrancois** [InstaPy/InstaPy#317]
Downloaded Chormedriver however when trying to run from the GUI it wont run as "Chromedriver is missing" any ideas?

![image](https://user-images.githubusercontent.com/26164537/27251747-844e1b68-5345-11e7-8e45-9f771c1a185c.png)

**Comment by timgrossmann** [comment]
@DominicFrancois I don't want to sound rude, but could you please check for similar issues before posting a new one?
This is an issue that appears like 10 times now and it's always the same answer...

Please follow the instructions in the readme...
You have to download the right `chromedriver` for your system and put it in the assets folder

Thank you

**Comment by DominicFrancois** [comment]
@timgrossmann thank you and apologies

**Comment by funstartshere** [comment]
rename chromedriver.exe to chromedriver
