### ISSUE TITLE
Bypass suspicious login attempt with phone number?

### ISSUE THREAD

**Issue by imkimchi** [InstaPy/InstaPy#3171]
for now, we can only bypass login attempt by security code from email but sometimes Instagram doesn't send email or user didn't add email to their instagram account so they only have mobile phone option.

I think It'd be really great to give an option for it.

**Comment by imkimchi** [comment]
It seems like there's no option for it, so I sent a PR right here https://github.com/timgrossmann/InstaPy/pull/3174 😊

**Comment by sionking** [comment]
login better be done manually
