### ISSUE TITLE
Same comment multiple times on different posts

### ISSUE THREAD

**Issue by varun13169** [InstaPy/InstaPy#3176]
People using **set_do_comment()**, please let me know how you tackle "[Same comment multiple times](https://help.instagram.com/161863397286564)" ban.

What is the minimum number of comments required in **set_comments()** to avoid getting banned ?
What is the interval between two comments ?

## Expected Behaviour
A post is liked and commented upon according to the set configuration.

## Current Behaviour
Post is being liked, and comments can be seen by the account with which comments has been made.
But comments can't be seen by any other account, although likes are being registered as they should be.

## Possible Solution 
By changing the comment resolves the issue, but using set of 5 different comments can be used 5 times only.
I even tried wrapping the comment in random 4 digit number, but that didn't help either.

## InstaPy configuration
  session.set_do_like(True, percentage=100)
  session.set_do_comment(enabled=True, percentage=100)
  session.set_comments(['comment 1', 'comment 2', 'comment 3', 'comment 4', 'comment 5'])
  session.set_user_interact(amount=5, percentage=100)
  session.like_by_tags(tagList, amount=20, interact=True)

**Comment by butaminas** [comment]
You should be able to fix this by adding my fix: https://github.com/timgrossmann/InstaPy/pull/3178

Cheers!

**Comment by varun13169** [comment]
@butaminas my issue is different.
Mine is the ban that Instagram puts when posting same comment even on different posts, "[Same comment multiple times](https://help.instagram.com/161863397286564)"

**Comment by butaminas** [comment]
> 
> 
> @butaminas my issue is different.
> Mine is the ban that Instagram puts when posting same comment even on different posts, "[Same comment multiple times](https://help.instagram.com/161863397286564)"

Perhaps just use more different comments?

**Comment by butaminas** [comment]
> 
> 
> @butaminas my issue is different.
> Mine is the ban that Instagram puts when posting same comment even on different posts, "[Same comment multiple times](https://help.instagram.com/161863397286564)"

Perhaps just use more different comments?

**Comment by varun13169** [comment]
@butaminas I have used 6 different comments yet after 6 different posts above-mentioned behavior starts occurring :(

I even tried wrapping comments in random 4 digit numbers; Eg: "xxxx <comment> yyyy"; still no success.
