### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by ashi1702** [InstaPy/InstaPy#318]
C:\Program Files (x86)\Python36-32\python.exe: can't open file 'get-pip.py': [Errno 2] No such file or directory. 
C:\Program Files (x86)\Python36-32\python.exe: can't open file 'setup.py': [Errno 2] No such file or directory
Getting these errors.

Also, python file contains 'clarifai.util ... ' and no 'from clarifai.client import ClarifaiApi'. Has it edited already ?

**Comment by timgrossmann** [comment]
@ashi1702 Could you give some context?
What command were you running?

You need to make sure all the dependencies are installed. Please read the Readme

**Comment by ashi1702** [comment]
Hey tim
yeah i worked on it more and now the script is working. Thanks !
Can you tell how can I get graphical results as done by you in your post ? :)

**Comment by timgrossmann** [comment]
@ashi1702 Awesome!

Haha, well I used the logs in the logs folder and pythons matplotlib library to create the graphical results 😉

**Comment by ashi1702** [comment]
Alright ! 
Thank you so much :D
