### ISSUE TITLE
Problem connection with the same quickstart.py ,

### ISSUE THREAD

**Issue by rmalosse** [InstaPy/InstaPy#3185]
Hi, 

I have 2 accounts, I deleted the logs for the first account to try something with unfollow function. And when i want to launch again my quickstart I have a problem. I upgrade InstaPy bot, chrome driver, pip but always same problem. 

I try the same quickstart with my another account (where i don't deleted the logs) and it works well. 

Can you help me please :) 

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-10-21 19:39:57] [romayn69]  Session started!
INFO:instapy.instapy:Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20181021-194033.html
**********************************************************************
INFO [2018-10-21 19:40:33] [xxxxx]  Sessional Live Report:
        |> LIKED 0 images  |  ALREADY LIKED: 0
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0
currently FOLLOWING 0 users & has got 0 FOLLOWERS

INFO:instapy.instapy:Sessional Live Report:
        |> LIKED 0 images  |  ALREADY LIKED: 0
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0
currently FOLLOWING 0 users & has got 0 FOLLOWERS

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-10-21 19:40:33] [xxxxxx]  Session ended!
INFO:instapy.instapy:Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "quickstart.py", line 27, in <module>
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 382, in login
    self.bypass_suspicious_attempt):
  File "/root/InstaPy/instapy/login_util.py", line 239, in login_user
    "//form/span/button[text()='Log in']")
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}
  (Session info: headless chrome=70.0.3538.67)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.4.0-134-generic x86_64)

## InstaPy configuration

import os
import time
from tempfile import gettempdir

from selenium.common.exceptions import NoSuchElementException

from instapy import InstaPy

insta_username = 'xxxxx'
insta_password = 'xxxx'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True,
                  nogui=True,
                  disable_image_load=True)

try:
    session.login()

    # settings
    session.set_relationship_bounds(enabled=True,
                                 potency_ratio=-1.2,
                                  delimit_by_numbers=False,
                                   max_followers=4590,
                                    max_following=None,
                                     min_followers=45,
                                      min_following=77)
    session.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')
    session.set_do_follow(enabled=True, percentage=75)
    session.set_do_like(enabled=True, percentage=100)
    session.set_comments([ 'Hello '], media='Photo')
    session.set_do_comment(enabled=True, percentage=50)

    session.unfollow_users(amount=100, allFollowing=True, style="FIFO", unfollow_after=22*60*60, sleep_delay=60)

**Comment by smokesmoke** [comment]
I have the same situation.
One account, was working for months with no problem.
Nothing deleted, nothing modified.
Just stopped working suddenly (today, 10.22.2018) with absolutely same error.

Here is the dumped HTML from /tmp (edited username and password)
https://drive.google.com/file/d/1bXuuPf0XRMfJ3YByGn7-gVqAFrgJm7jp/view?usp=sharing

**Comment by kristofenyi** [comment]
Hi,

I have the same one. worked for months. Today I got
`File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 24, in <module>
    from .comment_util import comment_image
  File "/root/InstaPy/instapy/comment_util.py", line 7, in <module>
    from .util import update_activity
  File "/root/InstaPy/instapy/util.py", line 24, in <module>
    from .quota_supervisor import quota_supervisor
  File "/root/InstaPy/instapy/quota_supervisor.py", line 7, in <module>
    from plyer import notification
ImportError: No module named plyer
`

**Comment by rmalosse** [comment]
UP , 

I try to reinstall all my server and now good surprised, nothing works  !

I have problem with chrome driver but don't understand what... 


OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-10-27 19:58:04] []  Session ended!
INFO:instapy.instapy:Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "quickstart.py", line 42, in <module>
    session.follow_user_followers(['tiboinshape','nabillanew','bigfloetoli','shannakress83'], amount=20, randomize=False, interact=True)
  File "/root/InstaPy/instapy/instapy.py", line 2490, in follow_user_followers
    self.logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 881, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 720, in get_users_through_dialog
    person_list = dialog_username_extractor(buttons)
  File "/root/InstaPy/instapy/unfollow_util.py", line 743, in dialog_username_extractor
    if person and hasattr(person, 'text') and person.text:
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=70.0.3538.77)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.4.0-127-generic x86_64)

**Comment by escariao** [comment]
> Hi,
> 
> I have 2 accounts, I deleted the logs for the first account to try something with unfollow function. And when i want to launch again my quickstart I have a problem. I upgrade InstaPy bot, chrome driver, pip but always same problem.
> 
> I try the same quickstart with my another account (where i don't deleted the logs) and it works well.
> 
> Can you help me please :)
> 
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2018-10-21 19:39:57] [romayn69] Session started!
> INFO:instapy.instapy:Session started!
> ooooooooooooooooooooooooooooooooooooooooooooooooooooooo
> 
> Cookie file not found, creating cookie...
> 
> If raising an issue, please also upload the file located at:
> /tmp/20181021-194033.html
> 
> INFO [2018-10-21 19:40:33] [xxxxx] Sessional Live Report:
> |> LIKED 0 images | ALREADY LIKED: 0
> |> COMMENTED on 0 images
> |> FOLLOWED 0 users | ALREADY FOLLOWED: 0
> |> UNFOLLOWED 0 users
> |> INAPPROPRIATE images: 0
> |> NOT VALID users: 0
> currently FOLLOWING 0 users & has got 0 FOLLOWERS
> 
> INFO:instapy.instapy:Sessional Live Report:
> |> LIKED 0 images | ALREADY LIKED: 0
> |> COMMENTED on 0 images
> |> FOLLOWED 0 users | ALREADY FOLLOWED: 0
> |> UNFOLLOWED 0 users
> |> INAPPROPRIATE images: 0
> |> NOT VALID users: 0
> currently FOLLOWING 0 users & has got 0 FOLLOWERS
> 
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2018-10-21 19:40:33] [xxxxxx] Session ended!
> INFO:instapy.instapy:Session ended!
> ooooooooooooooooooooooooooooooooooooooooooooooooooooo
> 
> Traceback (most recent call last):
> File "quickstart.py", line 27, in 
> session.login()
> File "/root/InstaPy/instapy/instapy.py", line 382, in login
> self.bypass_suspicious_attempt):
> File "/root/InstaPy/instapy/login_util.py", line 239, in login_user
> "//form/span/button[text()='Log in']")
> File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
> return self.find_element(by=By.XPATH, value=xpath)
> File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
> 'value': value})['value']
> File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}
> (Session info: headless chrome=70.0.3538.67)
> (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.4.0-134-generic x86_64)
> 
> ## InstaPy configuration
> import os
> import time
> from tempfile import gettempdir
> 
> from selenium.common.exceptions import NoSuchElementException
> 
> from instapy import InstaPy
> 
> insta_username = 'xxxxx'
> insta_password = 'xxxx'
> 
> session = InstaPy(username=insta_username,
> password=insta_password,
> headless_browser=True,
> multi_logs=True,
> nogui=True,
> disable_image_load=True)
> 
> try:
> session.login()
> 
> ```
> # settings
> session.set_relationship_bounds(enabled=True,
>                              potency_ratio=-1.2,
>                               delimit_by_numbers=False,
>                                max_followers=4590,
>                                 max_following=None,
>                                  min_followers=45,
>                                   min_following=77)
> session.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')
> session.set_do_follow(enabled=True, percentage=75)
> session.set_do_like(enabled=True, percentage=100)
> session.set_comments([ 'Hello '], media='Photo')
> session.set_do_comment(enabled=True, percentage=50)
> 
> session.unfollow_users(amount=100, allFollowing=True, style="FIFO", unfollow_after=22*60*60, sleep_delay=60)
> ```

I have the same problem! Only one account works. Del logs, created virtualenv, etc. But nothing works.
@uluQulu or @timgrossmann would you know about this? ;)

**Comment by smokesmoke** [comment]
OK guys, I updated InstaPy from github, updated chromedriver and chrome-stable and everything worked again.

**Comment by escariao** [comment]
@smokesmoke giv us details... i try update everything too...
but i get this:

`
pi@raspberrypi:~/Projects/Second $ python3 testy.py 

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-10-31 20:07:13] [login_here]  Session started!
INFO:login_here:Session started!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20181031-201411.html
**********************************************************************
INFO [2018-10-31 20:14:11] [login_here]  Sessional Live Report:
	|> LIKED 0 images  |  ALREADY LIKED: 0
	|> COMMENTED on 0 images
	|> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0
currently FOLLOWING 0 users & has got 0 FOLLOWERS

INFO:login_here:Sessional Live Report:
	|> LIKED 0 images  |  ALREADY LIKED: 0
	|> COMMENTED on 0 images
	|> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0
currently FOLLOWING 0 users & has got 0 FOLLOWERS


OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-10-31 20:14:11] [login_here]  Session ended!
INFO:login_here:Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "testy.py", line 23, in <module>
    session.login()
  File "/home/pi/Projects/Second/instapy/instapy.py", line 415, in login
    self.bypass_with_mobile):
  File "/home/pi/Projects/Second/instapy/login_util.py", line 182, in login_user
    "//select[@class='hztqj']/option[text()='English']")
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='hztqj']/option[text()='English']"}
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (82816abaad3930c3702cf23489f0506ba13b1529),platform=Linux 4.14.71-v7+ armv7l)
`

**Comment by escariao** [comment]
It's really the black hole... I've reinstalled the OS, and etc, but it does not change anything at all

**Comment by converge** [comment]
hey guys, Instagram is always updating their screens, so we need to keep up of the updates, that's why we're always updating InstaPy, you can update it using git command
```git pull``` if you downloaded it using git.

@3p1demicz you can fix is with: ```pip3 install plyer ; pip install plyer```

@escariao your issue is related to the login button, it works for most people, but it doesnt work for some others, we need wait someone propose a fix for it. *I can't fix because it doesnt happen to me.

@rmalosse sounds like there is some chrome process consuming all your free memory or your chrome is outdated or geckodriver is outdated.

**Comment by escariao** [comment]
Yes, my friend @converge... I have two and only one is giving this problem. I've tried everything!

**Comment by converge** [comment]
just wrote a bugfix for "cookie file not found", are you available to help testing it ? https://github.com/timgrossmann/InstaPy/pull/3384
