### ISSUE TITLE
Error using proxy - Need help

### ISSUE THREAD

**Issue by noamb3** [InstaPy/InstaPy#3188]
hello
i'm using the following command:
session = InstaPy(username=insta_username, password=insta_password, proxy_address='xx.xx.xx.xx', proxy_port=xxxxxx)

With real numbers ofcourse.
I'm getting the following error... 

Specifying 'socksProxy' requires an integer for 'socksVersion' 

Can you please help me out ?

**Comment by sionking** [comment]
did you upgrde to 2.43 chromedriver ? downgrade to 2.4.2

**Comment by noamb3** [comment]
Will try now. Thanks

**Comment by noamb3** [comment]
BTW anyway I can check the proxy is working ?

**Comment by nbgabriel** [comment]
> did you upgrde to 2.43 chromedriver ? downgrade to 2.4.2

Thanks SionKing!!!!!!!! I have the same problem, and fix it with the downgrade.

**Comment by noamb3** [comment]
Worked for me as well
Thanks
