### ISSUE TITLE
TypeError: 'NoneType' object is not iterable please help, newbie here

### ISSUE THREAD

**Issue by WestphalM** [InstaPy/InstaPy#3192]
Hello,
please help me I am getting this error message when trying to use quickstart.py. I am a total newbie so please tell me when I am doing something wrong even if its totally obvious.
thank you for your help!!

This is the error message I am getting:

WARNING [2018-10-22 21:59:57] [None]  Heeh! Error occurred while getting a DB profile for 'None':
	b'NOT NULL constraint failed: profiles.name'
Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    headless_browser=False)
  File "/Users/MerlinW/InstaPy/instapy/instapy.py", line 226, in __init__
    get_database(make=True)
  File "/Users/MerlinW/InstaPy/instapy/database_engine.py", line 43, in get_database
    id = get_profile(name, address, logger) if id is None or make else id
  File "/Users/MerlinW/InstaPy/instapy/database_engine.py", line 129, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable

**Comment by filmancco** [comment]
I have the same issue, please help

**Comment by converge** [comment]
not exactly a bug.

could you confirm that your quickstart.py has a username set ?

example:
```python
session = InstaPy(username='your_username,
                  password='your_password',
```

I was able to reproduce it if the ```username``` variable is empty
