### ISSUE TITLE
Let's rest some :>

### ISSUE THREAD

**Issue by samim91** [InstaPy/InstaPy#3195]
## Expected Behavior
Seamless activity, without interruptions

## Current Behavior

I have experienced interruptions and forced sleep patterns with these INFO messages:

INFO [2018-10-23 09:27:28] [xxxxxx]  Tag [49/50]
INFO [2018-10-23 09:27:28] [xxxxxx]  --> b'tourist'
INFO [2018-10-23 09:27:36] [xxxxxx]  desired amount: 20  |  top posts [disabled]: 9  |  possible posts: 24972652
INFO [2018-10-23 09:27:49] [xxxxxx]  Insufficient amount of links ~ trying again: 1
INFO [2018-10-23 09:28:08] [xxxxxx]  Insufficient amount of links ~ trying again: 2
INFO [2018-10-23 09:28:33] [xxxxxx]  Insufficient amount of links ~ trying again: 3
INFO [2018-10-23 09:28:37] [xxxxxx]  Cor! Did you send too many requests? ~ let's rest some

----- AND -----

[smart hashtag generated: earth]
INFO [2018-10-23 09:54:11] [xxxxxx]  Getting active users who liked the latest 10 posts:
  ~collecting the usernames from posts with the boundary of 500

INFO [2018-10-23 09:54:25] [xxxxxx]  Cor! ~failed to get the desired amount of usernames, trying again!  |  post:10  |  attempt: 1
INFO [2018-10-23 09:54:34] [xxxxxx]  Cor! ~failed to get the desired amount of usernames, trying again!  |  post:10  |  attempt: 2
INFO [2018-10-23 09:54:41] [xxxxxx]  Too Many Requests sent! ~will sleep some :>

Yesterday for the first time (I have recently launched InstaPy), at some point in the night, the bot started liking and following again.

## Possible Solution (optional)
My first guess is that the configurations are inconsistent to some extent... I did not change anything other than quickstart.py though...

## InstaPy configuration

""" Quickstart script for InstaPy usage """

from instapy import InstaPy
from instapy.util import smart_run

insta_username = 'xxxxxxx'
insta_password = 'xxxxxxx'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
		  disable_image_load=False,
                  multi_logs=True)

with smart_run(session):
    """ Activity flow """

    session.set_relationship_bounds(enabled=True,
				  delimit_by_numbers=True,
				   max_followers=7500,
				    max_following=2500,
				     min_followers=100,
				      min_following=60,
				       min_posts=30,
                        max_posts=1000)
    session.set_skip_users(skip_private=True,
                       private_percentage=95,
                       skip_no_profile_pic=True,
                       no_profile_pic_percentage=95,
                       skip_business=True,
                       business_percentage=85,
                       skip_business_categories=[],
                       dont_skip_business_categories=[])

    session.set_quota_supervisor(enabled=True, sleep_after=["likes_d", "follows_d", "unfollows_d", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(120, 2500),
                               peak_comments=(0, 0),
                                peak_follows=(None, 598),
                                 peak_unfollows=(50, None),
                                  peak_server_calls=(None, None))

    session.set_do_follow(enabled=True, percentage=15, times=1)

    session.set_dont_like(["nsfw"])

    session.set_delimit_liking(enabled=True, max=1060, min=3)

    session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')

    session.set_smart_hashtags(['travel', 'wanderlust', 'adventure', 'explore', 'world'], limit=35, sort='top', log_tags=True)

    session.set_dont_unfollow_active_users(enabled=True, posts=10)

    session.set_ignore_if_contains(['nsfw'])

    session.like_by_tags(amount=20, use_smart_hashtags=True)

    session.like_by_feed(amount=2, randomize=True, unfollow=True, interact=False)

    session.follow_user_followers(['damonandjo', 'jordhammond', 'lebackpacker', 'lostleblanc', 'chelseakauai', 'everchanginghorizon', 'doyoutravel', 'jannikobenhoff'], amount=5, randomize=False, sleep_delay=60, interact = True)

    session.follow_likers (['damonandjo', 'jordhammond', 'lebackpacker', 'lostleblanc', 'chelseakauai', 'everchanginghorizon', 'doyoutravel', 'jannikobenhoff'], photos_grab_amount = 3, follow_likers_per_photo = 3, randomize=False, sleep_delay=60, interact=True)

    session.follow_commenters(['damonandjo', 'jordhammond', 'lebackpacker', 'lostleblanc', 'chelseakauai', 'everchanginghorizon', 'doyoutravel', 'jannikobenhoff'], amount=100, daysold=365, max_pic = 100, sleep_delay=60, interact=True)

    session.unfollow_users(amount=50, allFollowing=True, style="FIFO", unfollow_after=3*24*60*60, sleep_delay=300)

**Comment by samim91** [comment]
So after some time, it wakes up again and goes on like:

INFO [2018-10-23 11:29:54] [xxxxxxx]  Tag [1/50]
INFO [2018-10-23 11:29:54] [xxxxxxx]  --> b'adventuretime'
INFO [2018-10-23 11:30:02] [xxxxxxx]  desired amount: 20  |  top posts [disabled]: 9  |  possible posts: 9062184
INFO [2018-10-23 11:30:14] [xxxxxxx]  Insufficient amount of links ~ trying again: 1
INFO [2018-10-23 11:30:32] [xxxxxxx]  Insufficient amount of links ~ trying again: 2
INFO [2018-10-23 11:30:55] [xxxxxxx]  Insufficient amount of links ~ trying again: 3
INFO [2018-10-23 11:30:57] [xxxxxxx]  Cor! Did you send too many requests? ~ let's rest some
INFO [2018-10-23 11:44:12] [xxxxxxx]  [1/20]
INFO [2018-10-23 11:44:12] [xxxxxxx]  https://www.instagram.com/p/BpRUgBiAkmH/?tagged=adventuretime
INFO [2018-10-23 11:44:15] [xxxxxxx]  Image from: b'm.gancarek'
INFO [2018-10-23 11:44:15] [xxxxxxx]  Link: b'https://www.instagram.com/p/BpRUgBiAkmH/?tagged=adventuretime'
INFO [2018-10-23 11:44:15] [xxxxxxx]  Description: b'Kuala Lumpur \xf0\x9f\x8f\x99\n.\n.\n.\n.\n.\n.\n.\n.\n.\n#kualalumpur #petronastowers #wonderful_places #honeymoon #husbandandwife #asia #malaysia #adventuretime #exploring #travel #anothercountry #travelgirl #bettertogether'
INFO [2018-10-23 11:44:18] [xxxxxxx]  User: m.gancarek >> followers: 225  |  following: 157  |  relationship ratio: 1.43
INFO [2018-10-23 11:44:29] [xxxxxxx]  --> Image Liked!
INFO [2018-10-23 11:44:31] [xxxxxxx]  --> Not commented
INFO [2018-10-23 11:44:32] [xxxxxxx]  --> Not following
INFO [2018-10-23 11:44:33] [xxxxxxx]  [2/20]
INFO [2018-10-23 11:44:33] [xxxxxxx]  https://www.instagram.com/p/BpRUfUkFN1-/?tagged=adventuretime
INFO [2018-10-23 11:44:36] [xxxxxxx]  Image from: b'szabokrisz82'

------
skipping some of the log
------


INFO [2018-10-23 12:35:30] [xxxxxxx]  User: shaynebrightt >> followers: 998  |  following: 601  |  relationship ratio: 1.66
INFO [2018-10-23 12:35:40] [xxxxxxx]  --> Image Liked!
INFO [2018-10-23 12:35:42] [xxxxxxx]  --> Not commented
INFO [2018-10-23 12:35:43] [xxxxxxx]  --> Not following
INFO [2018-10-23 12:35:44] [xxxxxxx]  [20/20]
INFO [2018-10-23 12:35:44] [xxxxxxx]  https://www.instagram.com/p/BpRboBPDs7g/?tagged=traveltheworld
INFO [2018-10-23 12:35:47] [xxxxxxx]  Image from: b'soniarterika'
INFO [2018-10-23 12:35:47] [xxxxxxx]  Link: b'https://www.instagram.com/p/BpRboBPDs7g/?tagged=traveltheworld'
INFO [2018-10-23 12:35:47] [xxxxxxx]  Description: b'LAF\xf0\x9f\x92\x9b\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n\xe2\x80\xa2\n#travel #adventure #wanderlust #vacation #travelgram #explore #holiday #travels #traveler #traveller #traveling #travelling #travelphotography #travelingram #travelblog #travelblogger #traveladdict #exploretocreate #passionpassport #tourism #mytravelgram #instapassport #tourist #traveltheworld'
INFO [2018-10-23 12:35:50] [xxxxxxx]  User: soniarterika >> followers: 1043  |  following: 543  |  relationship ratio: 1.92
INFO [2018-10-23 12:35:59] [xxxxxxx]  --> Image Liked!
INFO [2018-10-23 12:36:01] [xxxxxxx]  --> Not commented
INFO [2018-10-23 12:36:03] [xxxxxxx]  --> Not following
INFO [2018-10-23 12:36:03] [xxxxxxx]  Tag [5/50]
INFO [2018-10-23 12:36:03] [xxxxxxx]  --> b'travelpics'
INFO [2018-10-23 12:36:12] [xxxxxxx]  desired amount: 20  |  top posts [disabled]: 9  |  possible posts: 8286924
INFO [2018-10-23 12:36:24] [xxxxxxx]  Insufficient amount of links ~ trying again: 1
INFO [2018-10-23 12:36:40] [xxxxxxx]  Insufficient amount of links ~ trying again: 2
INFO [2018-10-23 12:37:06] [xxxxxxx]  Insufficient amount of links ~ trying again: 3
INFO [2018-10-23 12:37:09] [xxxxxxx]  Cor! Did you send too many requests? ~ let's rest some



And the Sessional Live Report says:

INFO [2018-10-23 12:39:45] [xxxxxxx]  Sessional Live Report:
	|> LIKED 0 images  |  ALREADY LIKED: 0
	|> COMMENTED on 0 images
	|> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0
currently FOLLOWING 4236 users & has got 9839 FOLLOWERS


OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-10-23 12:39:45] [xxxxxxx]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by samim91** [comment]
I have changed the sleep timer to 60, but is there no proper way to deal with this? Anyone?

**Comment by uluQulu** [comment]
Hi @samim91 
You have provided a long log output but have yet not told the main problem you are facing.
Can you clearly outline what you would like to do?

In any case, I should say that,
+ Those sleep delays are requirement.
_Well, they might need a revision but it would 90% be the same_.

-----

Cheers 🤩
---
