### ISSUE TITLE
Proxy with login\pass and headless chrome

### ISSUE THREAD

**Issue by kricha** [InstaPy/InstaPy#3199]
Hello, folks.

Is there way to user proxy with authentication for headless chrome? I can't setup it..

Thanks.

p.s. I'm trying to use proxy_extension but didn't help me.

**Comment by sionking** [comment]
no extenstions for headless chrome. please try firefox headless and let me know !!!

**Comment by escariao** [comment]
Proxy does not work anymore?

**Comment by octavius-1** [comment]
Did any of you guys make firefox with auth proxy work?
