### ISSUE TITLE
Number of images to be searched reduced automatically

### ISSUE THREAD

**Issue by sunnypatel165** [InstaPy/InstaPy#320]
Something really fishy I noticed today.
Here's my script:

```python
.set_lower_follower_count(limit = 750) \
.set_dont_like(dont_like) \
.set_do_follow(enabled=True, percentage=20, times=2)\
.like_by_tags(['#iphonephotography', '#foodphotography', '#blog', '#foodblog'], amount=40)\
```

Here are some log extracts:

> Logged in successfully!
> Tag [1/4]
> --> b'#iphonephotography'
> **[1/40]**
> .
> .
> .
> Tag [2/4]
> --> b'#foodphotography'
> **[1/40]**
> Image from: b'aimmafiaz'
> .
> .
> .
> Tag [3/4]
> --> b'#blog'
> **[1/32]**
> Image from: b'diys'
> .
> .
> .
> **[32/32]**
> Image from: b'berlin_cct'
> .
> .
> .
> Tag [4/4]
> --> b'#foodblog'
> **[1/40]**
> .
> .
> .
> Liked: 84
> Already Liked: 0
> Inappropriate: 68
> Commented: 0
> Followed: 14
> 
> Session ended
> 

Why did the 3rd tag search only for 32 images and not 40? for sure #blog has many images, much more than 40. 

Is this seen before?

**Comment by timgrossmann** [comment]
@sunnypatel165 Yes, that is the behaviour if you put the chrome window in the background or minimise it. The "aggregation" of images, by now, only works when the browser window is not minimised.
