### ISSUE TITLE
Viewing output from another terminal

### ISSUE THREAD

**Issue by GriffinCrown** [InstaPy/InstaPy#3201]
Hey all, I'm hosting InstaPy on a digital ocean droplet and using PuTTY as an SSH client. I have a PuTTY window open on my home pc running the quickstart.py file on a loop. If it wasn't on a loop I would just wait for it to end, but as of right now it will never stop running on its own.

I'm away from that computer and would like to stop the bot, make some changes, then start it again. Is there a way to do that without going back to my home PC? What about just viewing the output that I see in my home PuTTY client?

Thanks everyone!

**Comment by nakaori** [comment]
Hello,

you can run the process in screen. Just prepend "screen" to the command. If you do it manually you can press ctrl+a and then d to detach the console into the background. If you then type in screen -r you reattach the console.  you can do this from any terminal.

You can also run the command from cron. Just type crontab -e and insert your cronjob here to trigger it.
