### ISSUE TITLE
I need help understanding blacklist

### ISSUE THREAD

**Issue by redsector72** [InstaPy/InstaPy#3202]
HI there,
I am having trouble understanding how the blacklist works and I'm pretty sure there is a bug in there.
I need help understanding the code as my programming skills are newbie.

The fact is that I keep getting "--> Image already liked!" even with the blacklist active.
I considered that "maybe" the already liked was past likes, so I've modified the code to add to blacklist also the users that get into the "--> Image already liked!" process.

The problem is that I see duplicates entries in the blacklist.
This make me think there is a bug in the evaluate user process and the blacklist.

Can someone with more experience take a look inside the blacklist functions and tell if there is a bug?

**Comment by jeremycjang** [comment]
The blacklist works by creating a `.csv` of past users that you’ve interacted with through the program that it then references when it sees a link from a user you’ve already interacted with in the past. 

I haven’t opened the blacklist in a while, but believe it saves a line per action you’ve taken on a user (ex. One line for following user1, one line for liking user1’s posts). Not sure which actions you’re using, but the program grabs links dynamically then compares the links to the blacklist when deciding whether or not to action on them. If whatever list or hashtag you’re pulling from doesn’t have a lot of new posts or users, the program’s going to end up pulling a lot of links you’ve already interacted with then will display that message after realizing you’ve interacted with it before.

It might not even be related to the blacklist and could just be you’re finding posts using multiple hashtags that you’ve specified and is pulling the same link that you’ve already liked multiple times

Hope that helps!

**Comment by redsector72** [comment]
Hi @jeremycjang,
this is clear.
If I look at the source code, function validate_username I see that there is no "open file" o "file check".
there is only "if username in blacklist: return false"
My understanding of python is limited, but I'm pretty sure that the black list is not woking.
If I create a simple test, with any like function, and run it twice, i get 2 entry in the blacklist and I never see "is in blacklist  ~skipping user".
I suppose there is an error in the code, but I can'f figure it out

maybe @sionking can find it out!

**Comment by redsector72** [comment]
I have digged out more.
I suppose I have corrected the behavior.
It is definitely missing all the code regarding the file.
I will make a pull request
