### ISSUE TITLE
Hacked my account

### ISSUE THREAD

**Issue by theRouter** [InstaPy/InstaPy#3207]
I have several accounts that hacked one by one. Is it possible that the robot has a problem? 
Is some body that have same problem?

**Comment by HCWcoder** [comment]
no the code is clean , check what you did wrong from your end !

**Comment by sionking** [comment]
**don't save passwords in plain text**
your PC hacked not the application

**Comment by sionking** [comment]
I login manually and save the password encrypted.

**Comment by boldestfortune** [comment]
> 
> 
> I login manually and save the password encrypted.

what command is used to encrypt my password? Do you have to encrypt the quickstart.py?

**Comment by tiymfony** [comment]
Where were you hosting your setup?

**Comment by boldestfortune** [comment]
@sionking what do you use to encrypt password? command or do you have to install a lib?

**Comment by varun13169** [comment]
@

> I login manually and save the password encrypted.

@sionking can you please elaborate on how you do this. 
I was also looking for ways to not store the password in plain text.
