### ISSUE TITLE
Need to understand unfollow 

### ISSUE THREAD

**Issue by sunnygill** [InstaPy/InstaPy#3208]
I have 5000 following. 

Because of some issue in the current workspace, I synced to a new workspace. A new session cookie was created. Now when I try to unfollow users, the script only picks 22 user to unfollow

I am seeing below logs 

INFO [2018-10-23 18:24:16] []  Unfollowing the users you are following
INFO [2018-10-23 18:24:23] []  Failed to load desired amount of users!

INFO [2018-10-23 17:51:21] []  Total 22 users available to unfollow  ~not found in 'followedPool.csv': 22  |  didn't pass `unfollow_after`: 0

I tried copying the FollowerPool.csv from previous workspace, but still no effect.

I am using below command to unfollow
session.unfollow_users(amount=100, customList=all, allFollowing=True, style="FIFO", sleep_delay=150)

Any idea how to get around it.

**Comment by sunnygill** [comment]
synced to latest tip. The issue is gone

**Comment by VLNTNF** [comment]
k$

**Comment by Apao123** [comment]
@sunnygill  - how did you solve this?
