### ISSUE TITLE
What am I doing wrong? 

### ISSUE THREAD

**Issue by nicolasspragg** [InstaPy/InstaPy#321]
The program doesn't seem to be working how I thought it would with the parameters I have. 
This is what my quickstart.py looks like 

```
from instapy import InstaPy

# Write your automation here
# Stuck ? Look at the github page or the examples in the examples folder

dont_like = ['girl', 'hot']
ignore_words = ['pizza']
friend_list = ['friend1', 'friend2', 'friend3']

# If you want to enter your Instagram Credentials directly just enter
# username=<your-username-here> and password=<your-password> into InstaPy
# e.g like so InstaPy(username="instagram", password="test1234")

InstaPy()\
  .login()\
  .set_dont_include(friend_list) \
  .set_do_follow(enabled=True, percentage=100, times=1)\
  .set_dont_like(dont_like) \
  .set_ignore_if_contains(ignore_words) \
  .like_by_tags(['landscape', 'nature'], amount=1000) \
  .end()
```

im trying to like and follow 1000 images with the landscape tag, and then 1000 images with the nature tag.  However this is what happens 

Liked: 44
Already Liked: 3
Inappropriate: 65
Commented: 0
Followed: 44

Session ended

It doesn't like or follow anywhere close to 1000 images, and stops running after ~20mins.

**Comment by sunnypatel165** [comment]
I haven't seen this ever - but something similar I noticed yesterday- #320 - could you verify from your logs? - did you minimize Chrome?

**Comment by timgrossmann** [comment]
@nicolasspragg @sunnypatel165 Yes, this is the problem with minimising the chrome window or losing focus while it's "getting" new posts

**Comment by nicolasspragg** [comment]
That sucks. I never minimized it, I just put it on a separate desktop.

**Comment by timgrossmann** [comment]
@nicolasspragg It's easier to run this on a separate device, either an old laptop or a server
