### ISSUE TITLE
interact_by_users gives back "Element not found, skipping this username"

### ISSUE THREAD

**Issue by VincenzoRu** [InstaPy/InstaPy#3215]
Hi all,

When I use the method **interact_by_users** I got the message error "Element not found, skipping this username". I even tried **like_by_users**. Same issue. Anyone got the same issue before? What am I missing here?

Thank you 

_Originally posted by @VincenzoRu in https://github.com/timgrossmann/InstaPy/issues/3081#issuecomment-432790159_

**Comment by shenatiti** [comment]
Hello,
I'm getting the same error may be that instagram has modified its code and have to modify the xpath of like_utils.py

**Comment by VincenzoRu** [comment]
I tried everything @shenatiti but it's not xpath issue. Nobody has the same issue? :(
