### ISSUE TITLE
"Error accepted""Unset follow in account

### ISSUE THREAD

**Issue by jozefpis** [InstaPy/InstaPy#3221]
Hello,

after update few accounts return ""Error accepted""Unset follow in account ..." error after start following.

Any solution to fix this?

thanks

**Comment by jozefpis** [comment]
@CharlesCCC any idea pls? thanks

**Comment by CharlesCCC** [comment]
Can  you please provide more detail ? 
like the full log, screen-shot, 
you also mentioned `few accounts`, so it not all accounts getting those error ? what is the percentage ?
