### ISSUE TITLE
after git pull,stopped working

### ISSUE THREAD

**Issue by elbeye** [InstaPy/InstaPy#3222]
I just wanted to update instapy but just after git pull, I'm having error
What should I change extra?

![image](https://user-images.githubusercontent.com/17009671/47495036-d4e1ee00-d85b-11e8-80f9-6364c2cf26fa.png)

**Comment by jozefpis** [comment]
pip install workflow

**Comment by elbeye** [comment]
I did but still same :/

![image](https://user-images.githubusercontent.com/17009671/47504304-a91f3200-d874-11e8-8d66-24d1b074be07.png)

**Comment by jozefpis** [comment]
Edit instapy.py and comment line "from .clarifai_util import check_image"

**Comment by CharlesCCC** [comment]
you can try re-run the setpu script by doing
`python setup.py install`
