### ISSUE TITLE
follow_users_following Not Working. Message: stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by AntoliniMatteo** [InstaPy/InstaPy#3224]
## Current Behavior
I'm trying to follow followers of an user but every time the program fail and show this message. It doesn't crash, but it refresh the page and it do this again
```
INFO [2018-10-25 17:19:53] [********]  User '*********' [1/10]
Message: stale element reference: element is not attached to the page document
```
## Possible Solution (optional)
I've tryed to set the simulation on false but it doesn't work.
I read that it could be a javascript error of instagram and i read a post that say that javascript load 2 times the followers windows. So, when the program started and was going to follow users, i close the window and reopen by clicking manually on the "followers" button. It works but only for the first user. When the program passed to the next it shows the error and refresh the page and return to the first user
## InstaPy configuration
Quickstart sample configuration

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
