### ISSUE TITLE
How to update with virtualenv?

### ISSUE THREAD

**Issue by Zettt** [InstaPy/InstaPy#3231]
How do we go about updating the installation with a virtualenv? There is no documentation available, and no one who uses virtualenv actually ever seemed to be able to update the installation using Git. There are some folks who cloned the repo into the virtualenv installation but the steps to do this don't sound like a smart way to go about it. Is there an official documentation?

**Comment by deronsizemore** [comment]
I'm a novice and have yet to try to update everything when using virtualenv, but I believe you should be able to do it by activating your env and then doing `git pull https://github.com/timgrossmann/InstaPy.git master` for the updated files?

**Comment by ajankuv** [comment]
I run `pip install git+https://github.com/timgrossmann/InstaPy.git` to update my venv's

**Comment by Zettt** [comment]
@deronsizemore Except that `git pull` requires a Git repository in the first place. virtualenv does not install a repository in the virtual environments' directory -- at least in my case it didn't. 

@ajankuv I read somewhere in the other issues that running that command again, would not update the files. Is this true or false?

**Comment by deronsizemore** [comment]
@Zettt I was just messing with this a bit on my local machine. Again, I'm a novice so this may be completely off base, but it seems that if I start from scratch here's the steps that appear to work:

> Create folder
> Create virtualenv
> run `git init`
> enter `git clone https://github.com/timgrossmann/InstaPy.git`

From there, you should have a parent folder with two folders inside (InstaPy and VirtualEnv). You can cd into InstaPy and then do a: git pull https://github.com/timgrossmann/InstaPy.git.

When I do that it tells me everything is already up-to-date. So I assume if there had been a change to the master branch, then it would pull down those changes?

**Comment by ajankuv** [comment]
@Zettt looks like it's true. `pip install git+https://github.com/timgrossmann/InstaPy.git` does something but does not update the files. I thought it was this entire time.

**Comment by Zettt** [comment]
> @Zettt 
> > Create folder
> > Create virtualenv
> > run `git init`
> > enter `git clone https://github.com/timgrossmann/InstaPy.git`

@deronsizemore That would have been my go-to way as well but since there's no documentation, I'm hesitant. The reason is that this method would create a bunch of – seemingly unnecessary – folders inside the InstaPy folder. It's possible to check out certain files/folders from a  repo too, but again, there's no official statement whether that's the way to go, or if it's a more or less "live with it" situation.

@ajankuv Thanks for confirming. Bummer.

**Comment by ajankuv** [comment]
@Zettt https://gist.github.com/ajankuv/d05bdfb8d543d6b370ca4b438612191b

This is something I just wiped up to get mine all up to date and back up fast. It should work when needing to update fast.

**Comment by Zettt** [comment]
@ajankuv Thanks buddy. I'll munch on it some more.

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
