### ISSUE TITLE
Grabbed 0 usernames from 'XXXX' `Followers` to do following

### ISSUE THREAD

**Issue by andreescocard** [InstaPy/InstaPy#3232]
## Expected Behavior

Grab users from profiles to follow

## Current Behavior

Grabbing 0 users from profiles

## Possible Solution (optional)

A change in xpath as this fix: https://github.com/timgrossmann/InstaPy/commit/e07aa4acace39e498e8dcf49f8bbd2ef92dfcd37

## InstaPy configuration

Using a raspberry pi 3
My code:
`session.set_relationship_bounds(enabled=False)
session.follow_user_followers(['xxxx','xxxx'], amount=10, sleep_delay=60)`

**Comment by AntoliniMatteo** [comment]
follow_user_followers now is not working for an index error

**Comment by andreescocard** [comment]
Tried to use
`session.set_do_follow(enabled=True, percentage=10, times=2)`
but running the script seems to ignore this line
currently running follow by tags

**Comment by 46960** [comment]
Any news here?

**Comment by bbkjunior** [comment]
Can anybody explain how to fix that if possible?

**Comment by andreescocard** [comment]
It's working now, update the code
