### ISSUE TITLE
Not following account in private

### ISSUE THREAD

**Issue by Anson-CCChan** [InstaPy/InstaPy#3235]
## InstaPy configuration

session.follow_user_followers(['xxxx', 'xxxxx', 'xxxxx'], amount=10, randomize=True, sleep_delay=60)
session.follow_commenters(['xxxxx', 'xxxxxxx', 'xxxxxx'], amount=50, daysold=365, max_pic = 5, sleep_delay=300, interact=False)

When I go to the target account, if the target followers are private situation that the bot wont activate the follow button, but it is normal when the target is in public. 

How can I fix it?

<img width="625" alt="2018-10-27 11 00 22" src="https://user-images.githubusercontent.com/42989672/47599006-b99bed80-d9d7-11e8-9fbc-b0e1e972dfba.png">

**Comment by AntoliniMatteo** [comment]
Try to add this command on your program:

```
session.set_skip_users(skip_private=False, private_percentage=0)
```

**Comment by Anson-CCChan** [comment]
Is work great. thanks mate @AntoliniMatteo
