### ISSUE TITLE
Unfollow loop error:  Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#3239]
Any suggestions @uluQulu @sionking 

INFO [2018-10-27 06:52:34] [xx]  Ongoing Unfollow [1/396]: now unfollowing 'xx''...
ERROR [2018-10-27 06:56:04] [xx]  --> Unable to detect the following status of 'xx''!
WARNING [2018-10-27 06:56:04] [xx]  The page isn't available!  ~the link may be broken, or the page may have been removed...
WARNING [2018-10-27 06:56:04] [xx]  Maybe 'xx'' has changed the username!        ~verifying through the user ID
INFO [2018-10-27 06:56:04] [xx]  Trying to find the username from the given user ID by loading a post
ERROR [2018-10-27 06:58:16] [xx]  Unfollow loop error:  Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}

**Comment by AntoliniMatteo** [comment]
They are trying to fix that. It is a bug with instagram javascript, please be patient

**Comment by uluQulu** [comment]
Hi @fgisslen 
Out of your output, it has most likely happened at
`pre = browser.find_element_by_tag_name("pre").text`
line of **util.py** file while trying to get the username of a profile from a user ID.


Well, I have written that part of code and I can assure you that it handles all expected cases:
+ In case of a user profile has blocked you
+ Or a user is private
+ The user ID is invalid
+ Or the profile has been deleted

So, why you have had that annoyish error?
You are having connectivity issues.
+ Either the page does not load properly at time of selenium query. (That page is **too small** to load)
+ Or the page does not load at all.

In any case it needs more feedback from you to offer a solution.
+ Do you have this situation frequently?

@AntoliniMatteo can also be right [it being on IG side], but I don't think so. Do you have any source on it?

---

Cheers 😁
---

**Comment by fgisslen** [comment]
@uluQulu sorry, didn't saw that this was the same error.

I got some answers from my proxy provider. "The main error is reqClientIOProblem which means that you did not wait for a response and did interrupt connection."

I have tried to higher the timeout of expicit_wait. will see if that make any difference.

**Comment by uluQulu** [comment]
@fgisslen 
I could help you find an efficient solution if you gave a solid feedback.
Will ask again the question I asked previously:
+ _How frequently you are having such problems [out of connectivity issues]?_
You can write more details = better solution.

---

Cheers 😁
---

**Comment by fgisslen** [comment]
@uluQulu It's when I want to unfollow non-followers and it seems like it happens every time. 

INFO [2018-10-29 17:25:51] [xx]  Starting to unfollow users..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-10-29 17:25:51] [xx]  Unfollowing the users followed by InstaPy

INFO [2018-10-29 17:25:51] [xx]  Retrieving live `Followers` data of xx at "full" range
  4561/8100 [====================+---------------]  56%    |> Elapsed: 5.65 minutes    |> ETA: 4.44 minutes      

INFO [2018-10-29 17:31:38] [xx]  Queried too much! ~ sleeping a bit :>
  4611/8100 [====================+---------------]  56%    |> Elapsed: 15.47 minutes    |> ETA: 12.15 minutes      

INFO [2018-10-29 17:41:50] [xx]  Unable to get `Followers` data:
        b'Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}\n  (Session info: headless chrome=70.0.3538.67)\n  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.15.0-36-generic x86_64)\n'



INFO [2018-10-29 17:41:50] [xx]  Grabbed 4611 usernames from `Followers` in 15.47 minutes
INFO [2018-10-29 17:41:50] [xx]  Stored `Followers` data at /root/InstaPy/logs/xx//relationship_data/xx/followers/29-10-2018~full~4611.json local file

INFO [2018-10-29 17:41:50] [xx]  Zz :[ time to take a good nap  ~sleeping 6.0 seconds
INFO [2018-10-29 17:41:55] [xx]  Yawn :] let's go!

INFO [2018-10-29 17:41:55] [xx]  Found 39 loyal followers!  ~will not unfollow them
INFO [2018-10-29 17:41:55] [xx]  Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 0

INFO [2018-10-29 17:41:55] [xx]  There are no any users available to unfollow
INFO [2018-10-29 17:41:55] [xx]  --> Total people unfollowed : 0

**Comment by uluQulu** [comment]
@fgisslen 
>It's when I want to unfollow non-followers and it seems like it happens every time.

It's clear.
How many seconds you have put to **implicit wait**?
It is being controlled by the `page_delay` parameter of the InstaPy instance.
```python
session = InstaPy(username=insta_username,
                  password=insta_password,
                     page_delay=50)
```
Its default is 25 seconds.
Try increasing it to higher value(s) and see the effect.

### What is implicit wait?
+ See my https://github.com/timgrossmann/InstaPy/issues/2968#issuecomment-423352361 (_read the implicit wait part_).
+ The only thing an **implicit wait** is guaranteed to do in all implementations is wait for the existence of a element. It does not guarantee interactability (visibility, enabled-ness, etc.).
+ **Implicit waits** are "baked into" the remote end (IEDriverServer.exe, geckodriver, chromedriver, etc.)
but **explicit waits** are not.
+  **Implicit waits** are "baked in" means the first `find_element` call in **explicit wait** doesn't return until the **implicit wait** timeout expires. In other words it has higher priority than **explicit wait**.
+ You cannot set the poll time of an **implicit wait**; You can for an **explicit wait**.
+ **Explicit wait** makes more HTTP calls to the remote end than **implicit wait**.

Meanwhile, @timgrossmann & @sionking, I think the name - `page_delay` does not fit well for setting up the **implicit wait** and should be renamed cos apparently **implicit wait** has nothing to do with _page delay_ which is controlled by `page_load_timeout` feature of selenium..

@fgisslen, if increasing **implicit wait** time won't not help you, post a fresh comment containing new feedback, I will wait to see it.

### Notes:
+ Having an unhealthy connection will make much more problems than you have thought that's why you have to explain the problems details in full scale to understand and provide an efficient solution.


---

Cheers 😁
---

**Comment by fgisslen** [comment]
@uluQulu I have page_delay=100.
Running on digital ocean with proxies

**Comment by w4ngel** [comment]
Hi, I am getting this issue as well.

It is always preceded by; "The page isn't available!" with the username being changed or might have been removed. Then approximatly 30 seconds before the error happens, it is trying to find the username fromt he given user ID by loading a post. That is when I get the "Unfollow loop error: Message: unable to locate element: pre".

The configuration is set to unfollow all Instapy followed users, in a random style. Page_delay is at default. Running with proxies but no connection issues.

**Comment by thejeromelouis** [comment]
If I try to unfollow accounts that do not follow back I get the error: 

> INFO [2018-11-27 01:06:46] [my_account]  Session started!
> INFO [2018-11-27 01:07:23] [my_account]  Logged in successfully!
> INFO [2018-11-27 01:07:28] [my_account]  Starting to unfollow users..
> INFO [2018-11-27 01:07:29] [my_account]  Unfollowing the users who do not follow back
> 
> INFO [2018-11-27 01:07:29] [my_account]  Retrieving live `Followers` data of my_account at "full" range
> INFO [2018-11-27 01:07:45] [my_account]  Unable to get `Followers` data:
> 	**b'Message: Unable to locate element: pre\n'**
> 
> INFO [2018-11-27 01:07:45] [my_account]  Grabbed 0 usernames from `Followers` in time loop
> INFO [2018-11-27 01:07:45] [my_account]  Zz :[ time to take a good nap  ~sleeping 0.0 seconds
> INFO [2018-11-27 01:07:45] [my_account]  Yawn :] let's go!
> 
> INFO [2018-11-27 01:07:45] [my_account]  Retrieving live `Following` data of my_account at "full" range
> INFO [2018-11-27 01:08:06] [my_account]  Unable to get `Following` data:
> 	**b'Message: Unable to locate element: pre\n'**
> 
> INFO [2018-11-27 01:08:06] [my_account]  Grabbed 0 usernames from `Following` in time loop
> INFO [2018-11-27 01:08:06] [my_account]  Zz :[ time to take a good nap  ~sleeping 0.0 seconds
> INFO [2018-11-27 01:08:06] [my_account]  Yawn :] let's go!
> 
> INFO [2018-11-27 01:08:06] [my_account]   There are 0 Nonfollowers of my_account  ~the users my_account is following WHO do not follow back
> 
> INFO [2018-11-27 01:08:06] [my_account]  Stored Nonfollowers data at C:\Users\Jerome\Documents\GitHub\InstaPy\logs\my_account\/relationship_data/my_account/nonfollowers/27-11-2018~[0-0]~0(1).json local file
> 
> INFO [2018-11-27 01:08:06] [my_account] Total 0 users available to unfollow  ~not found in 'followedPool.csv': 0  |  didn't pass `unfollow_after`: 0
> 
> INFO [2018-11-27 01:08:06] [my_account]  There are no any users available to unfollow
> INFO [2018-11-27 01:08:06] [my_account]  --> Total people unfollowed : 0

I already tried to delete the cockie or to increase the page_delay with no success. Any idea what could be wrong? Maybe because I'm using firefox? I'm currently following 5 times more people than follow me, so there have to be some account.

**Comment by gitpatrickhub** [comment]
See fix in #3444 for the “pre\n” error

**Comment by ghost** [comment]
Hi guys,
I have started to play with this project and I am running into some issues similar to the ones described in this issue (and some others)

## Environment
- Mac
- Python 3.7
- Pipenv + instapy requirement.txt packages: `pipenv install -r requirements.txt`
- Instapy source code directly imported from `master` today
- Docker Selenium Chrome : `selenium/standalone-chrome-debug:3.141.59`
- ChromeDriver [72.0.3626.69](https://chromedriver.storage.googleapis.com/index.html?path=72.0.3626.69/)
- Docker Selenium Firefox : `selenium/standalone-firefox-debug:3.141.59`
- Firefox geckodriver [v0.24.0](https://github.com/mozilla/geckodriver/releases/tag/v0.24.0)

## Goal
Grab own following with `session.grab_following`

## Expected
A non-empty list of usernames

## How to reproduce
Run a docker selenium:
```bash
docker run -d --rm --name selenium \
		--publish "4444:4444" \
		--shm-size 128M \
		selenium/standalone-chrome-debug:3.141.59
```

Using a python interpreter:
```python
from instapy import InstaPy

session = InstaPy(username="XXX", password="ABC",
                      nogui=False,
                      selenium_local_session=False,
                      use_firefox=False,
                      browser_profile_path=None,
                      page_delay=25,
                      show_logs=True,
                      headless_browser=True,
                      proxy_address=None,
                      proxy_chrome_extension=None,
                      proxy_port=None,
                      disable_image_load=True,
                      bypass_suspicious_attempt=False,
                      bypass_with_mobile=False,
                      multi_logs=False)

session.set_selenium_remote_session(selenium_url="http://localhost:4444/wd/hub")

me_following = session.grab_following(username="XXX", amount="full", 
                      live_match=True, store_locally=True)
```

## Result
```
_____________________________________________________________________________
INFO [2019-02-11 00:00:46] [XXX]  Starting to get the `Following` data..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-02-11 00:00:46] [XXX]  Retrieving live `Following` data of XXX at "full" range
INFO [2019-02-11 00:00:52] [XXX]  Encountered an error to find `pre` in page!	~grabbed 0 usernames
	b'Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}\n  (Session info: chrome=72.0.3626.81)\n  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.9.125-linuxkit x86_64)\n'
```

(similar issue using firefox):
```
_____________________________________________________________________________
INFO [2019-02-10 22:56:14] [XXX]  Starting to get the `Following` data..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-02-10 22:56:14] [XXX]  Retrieving live `Following` data of XXX at "full" range
INFO [2019-02-10 22:56:20] [XXX]  Unable to get `Following` data:
	b'Expecting value: line 1 column 1 (char 0)'
INFO [2019-02-10 22:56:20] [XXX]  Grabbed 0 usernames from `Following` in time loop
INFO [2019-02-10 22:56:20] [XXX]  Zz :[ time to take a good nap  ~sleeping 0.0 seconds
INFO [2019-02-10 22:56:20] [manypozo]  Yawn :] let's go!
```

---

I wonder if there is some versioning issue in my environment related to chrome/firefox drivers...

It would be great if you could help me out with this ^^'

Let me know if I can provide you more information, I am glad to help to improve this tool =]

Thank you

**Comment by MaghnusM** [comment]
I am also having issues with this, can someone please help?

**Comment by GeoffreyPG** [comment]
Same error !
Unable to locate element: {"method":"tag name","selector":"pre"}\n
