### ISSUE TITLE
Following: Element <button class="_ah57t _84y62 _i46jh _rmr7s">...</button> is not clickable

### ISSUE THREAD

**Issue by FBosler** [InstaPy/InstaPy#325]
hi there,

had this happen twice now. The error pops up when trying to follow (not always though). First run was after roughly 250 pictures, second run after roughly 40. I did scale the timing function down to return t * 0.75 instead of t and am running on following 10%, but otherwise its as configured.

Please see below the error
` Element <button class="_ah57t _84y62 _i46jh _rmr7s">...</button> is not clickable at point (880, 14). Other element would receive the click: <div class="_df358">...</div>`

Cheers

**Comment by timgrossmann** [comment]
@FBosler Do you have the latest version of InstaPy? 

try doing `git pull`

**Comment by FBosler** [comment]
Think I do, downloaded it yesterday.

I am hesitant of overwriting the recent version, because somehow importing instapy wouldn't work, so I had to move my script to the folder in which the Instapy.py file is and then I also us to change all the other import dependencies (I kinda don't wanna overwrite that).

**Maybe I can give some more background information:**
I just had the bot run all night and there were no crashes. Only difference this time, it was in full screen.
The class that would receive the click "<div class="_df358">...</div>" seems to be the navbar
So my guess is that some pages are layouted differently and the script wants to click the follow button too fast, but then the navbar slides in. Thus, preventing the click.
Maybe scrolling up the page and then waiting a fraction of a second could solve the problem.

Cheers

PS: Sorry for closing the issue (github on phone is no good)

**Comment by timgrossmann** [comment]
@FBosler You can't close the window, this won't work. It always needs to stay in focus, that's why I recommend using a VPS like Digital Ocean

**Comment by FBosler** [comment]
Hi Tim,

hadn't really closed the window. I left it running all night, but maybe it was too small. Regardless it seems to be a weird (kind of unique) bug and therefore probably not too important. But I guess if it keeps happening more often you might want to add that scrolling up.

I have since switched to Digital Ocean, took a bit to set up, but works like a charm. Might be worth mentioning in the docu that people should run their script with python3.5 script.py (with 3.5 being the python version on their distribution and script.py being their script) instead of just python script.py.

For me this caused the import pyvirtualdisplay to fail.

Cheers!

**Comment by timgrossmann** [comment]
@FBosler Yes, making the window smaller triggers the page to change it's structure, also a bad thing 😄 

Perfect!
