### ISSUE TITLE
Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#3255]
Anyone knows why this is happening. If I look in the file record_all_following it says it 836 there.
@uluQulu @timgrossmann @sionking 

INFO [2018-10-29 10:23:43] [xx]  Unfollowing the users followed by InstaPy

INFO [2018-10-29 10:23:43] [xx]  Retrieving live `Followers` data of xx at "full" range
INFO [2018-10-29 10:25:37] [xx]  Unable to get `Followers` data:
        b'Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}\n  (Session info: headless chrome=70.0.3538.67)\n  
                 (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.15.0-36-generic x86_64)\n'

INFO [2018-10-29 10:25:37] [xx]  Grabbed 1645 usernames from `Followers` in 1.4 minutes
INFO [2018-10-29 10:25:37] [xx]  Stored `Followers` data at /root/InstaPy/logs/xx//relationship_data/xx/followers/29-10-2018~full~1645.json local file
INFO [2018-10-29 10:25:37] [xx]  Zz :[ time to take a good nap  ~sleeping 3.3 minutes
INFO [2018-10-29 10:29:03] [xx]  Yawn :] let's go!

INFO [2018-10-29 10:29:03] [xx]  Found 39 loyal followers!  ~will not unfollow them
INFO [2018-10-29 10:29:03] [xx]  Total 34 users available to unfollow  ~didn't pass `unfollow_after`: 0

INFO [2018-10-29 10:29:03] [xx]  You have requested more amount: 100 than 34 of users available to unfollow~using available amount

**Comment by uluQulu** [comment]
Hey @fgisslen 
It is the error of the same sort I recently have inspected at https://github.com/timgrossmann/InstaPy/issues/3239#issuecomment-433632208 WHERE you did not provide any further feedback.

---

Cheers 😁
---

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.

**Comment by GeoffreyPG** [comment]
Same error ! 
Unable to locate element: {"method":"tag name","selector":"pre"}\n
