### ISSUE TITLE
Make a pool of automated followup and use that pool for unfollow in FIFO

### ISSUE THREAD

**Issue by jungfish** [InstaPy/InstaPy#326]
InstaPy unfollow account that have been followed manually by the actual user. 
What I propose is that everytime there an automated follow, we write it in a csv and at the end of the script when we unfollow, we only unfollow the accounts from the csv in FIFO mode.

**Comment by jungfish** [comment]
@timgrossmann I'm ready to develop right now do you want to discuss it before I do it ?

**Comment by timgrossmann** [comment]
#349
