### ISSUE TITLE
UNFOLLOW - potency_ratio? 

### ISSUE THREAD

**Issue by lukepolq** [InstaPy/InstaPy#3261]
Hi, 

I'm looking for one additional option to unfollow script. 

## Expected Behavior
Unfollow user followed by instapy with potency_ratio higher than some value.
## Current Behavior
Unfollow but not taking session.set_relationship_bounds setting into considaration 
## InstaPy configuration
session.set_relationship_bounds(enabled=True, potency_ratio= -5.1)
session.unfollow_users(amount=100, InstapyFollowed=(True, "all"), style="RANDOM", unfollow_after=24*60*60, sleep_delay=700)

Tried below as well:
session.set_relationship_bounds(enabled=True, potency_ratio= -5.1)
session.unfollow_users(amount=100, InstapyFollowed=(True, "all"), style="RANDOM", sleep_delay=700)

Thank You in advance!

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
