### ISSUE TITLE
[Proposition] Adding callbacks to InstaPy interface

### ISSUE THREAD

**Issue by janekbaraniewski** [InstaPy/InstaPy#3268]
Hey!
I'm making an app to handle all my Instagram actions and I wanted to have some way to monitor the progress from the outside process.
So I thought about adding `callback` argument to methods like `interact_by_users`, `like_by_tags` etc. In my idea it would be just a simple callable which would take a `context` argument (I though about just using dict for that but maybe some more complex structure would be appropriate) and would allow user to do whatever he wants with the context. 
For now I only thought about adding to context info like tag/username/whatever that we're processing right now and (if we iterate over some collection of pictures and we usually do) which element of the collection are we processing right now.

What do you think about something like that? 
I would be more than happy to implement it.

**Comment by converge** [comment]
hey, sounds a good idea.

is your idea keep a history of actions (callback returns) or just the last action ?

If the idea is to keep track of the last action, maybe the state approach is easier/faster to implement.

**Comment by janekbaraniewski** [comment]
My idea is to report current state/status of the operation. 
Information about number of follows,comments,likes etc (lets call it `session_status`) is now stored on top object level and each method creates its local copies of some subset of those variables, usually set to 0 at the beginning. I was thinking about unifying that a bit. Each method would create its `local_status` - same set of variables as at the top level, always set to 0, to make it consistent - and with each iteration it would call callback method (if passed) like
```python
callback({
    status=local_status,
    progress=calculated % value of iteration progress,
})
```

**Comment by converge** [comment]
Thinking as a final user... what really matters for me is have a report or some way to follow the progress, and easier/simpler approach use to be the best, we could just refactor our ```update_activity``` to have a better understanding of the interactions (count follows, followings).

This can be also a initial idea about data science.

Please correct me if it doesn't make sense for you.

**Comment by janekbaraniewski** [comment]
I looked into `update_activity` but I don't really like idea of storing this in sqlite. I would like to run several InstaPy instances at once as Celery tasks and there is single sqlite file being used as db. I think it would be better to just have a simple data structure with which client can do whatever he wants - store it in some cache, yield it as a task status or store it in db - depending on the use case.

**Comment by converge** [comment]
> I looked into `update_activity` but I don't really like idea of storing this in sqlite. I would like to run several InstaPy instances at once as Celery tasks and there is single sqlite file being used as db.

It's the natural way for me, so we can filter it by profile using the profile_id (key).

> I think it would be better to just have a simple data structure with which client can do whatever he wants - store it in some cache, yield it as a task status or store it in db - depending on the use case.

Don't know, sounds a bit techie, the users are not used to it. I think it should be clean and easy, so everyone cold understand. We have been thinking about the module idea, so we could attach functionalities without changing the core structure of InstaPy.

What do you think ?
