### ISSUE TITLE
Cannot import name 'Workflow' at startup

### ISSUE THREAD

**Issue by mpaolor** [InstaPy/InstaPy#3270]
## Expected Behavior
instapy launches chrome and starts operating

## Current Behavior
when i launch the script i get this error:

from clarifai.rest import Workflow
Cannot import name 'Workflow'

![instapy](https://user-images.githubusercontent.com/12829453/47782342-4b6d6880-dd00-11e8-9ee4-f4b00256449b.JPG)

## InstaPy configuration
i'm running it on windows 7
default quickstart.py

**Comment by CharlesCCC** [comment]
seems like the clarifai didn't fully install correctly. 
try re-install clarifai package using pip.

**Comment by mpaolor** [comment]
thank you! i had to reinstall pip and python and then reinstall instapy but now it works

**Comment by michaelbigelow** [comment]
I'm having the same problem.  I reinstalled clarifai with pip and I still get the same error...

**Comment by Wisdomlocker** [comment]
Greetings!  @CharlesCCC apologies for asking a dumb question (clearly not a tech person here) - how does one "re-install clarifai package using pip" on windows? Thanks! 

I have just upgraded to pip 18.1 / same problem
