### ISSUE TITLE
ALWAYS FOLLOWING USER'S FOLLOWERS

### ISSUE THREAD

**Issue by c0d3x27** [InstaPy/InstaPy#3271]
## Expected Behavior
i only want to comment and like users followers
## Current Behavior
even thought i have "session.set_do_follow(enabled=False, percentage=100" it keep following thier followers
## InstaPy configuration
""" Quickstart script for InstaPy usage """
# imports
import random
import os
from instapy import InstaPy
from instapy.util import smart_run
import time
from tempfile import gettempdir
from selenium.common.exceptions import NoSuchElementException

# login credentials
insta_username = ''
insta_password = ''

ignore_users = ['selvajhdti_jasmin', 'justghdajuice', 'desrewmowoman_']
# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_simulation(enabled=True)
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=None,
				  delimit_by_numbers=True,
				   max_followers=3000,
				    max_following=2000,
				     min_followers=45,
				      min_following=10)
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(57, 585),
                               peak_comments=(21, 182),
                                peak_follows=(48, None),
                                 peak_unfollows=(35, 402),
                                  peak_server_calls=(None, 4700))

    session.set_dont_include(["salvati_jasmin", "justajuice", "desmowoman_"])
    session.set_dont_like(["pizza", "#store", "buy"])

    session.set_skip_users(skip_private=True,
                            skip_no_profile_pic=True)

    # activity
    session.set_user_interact(amount=5, randomize=True, percentage=100, media='Photo')
    session.set_do_follow(enabled=False, percentage=100, times=2)
    session.set_do_like(enabled=True, percentage=100)
    session.set_do_comment(enabled=True, percentage=100)
    session.set_comments([u'Mi piacciono le tue foto, belle! \U0001F929', u'belle foto, carina questa! \U0001F917', u'Troppo bella questa ;)! \U0001F60D'])
    session.set_comments(['ummm.. si mi piace questa, bel profilo! @{}'], media='Photo')
    session.interact_user_followers(['CNN'], amount=800, randomize=True)

    #limit for liking
    session.set_delimit_liking(enabled=True, max=150, min=5)
    session.set_delimit_commenting(enabled=True, max=20, min=None)
    session.unfollow_users(amount=800, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=90*60*60, sleep_delay=501)
    session.set_dont_unfollow_active_users(enabled=True, posts=5)

    # end the bot session
    session.end()

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.

**Comment by wimwa** [comment]
@Banginpadr did you solve this? because im encountering the same problem at the moment.

**Comment by c0d3x27** [comment]
> @Banginpadr did you solve this? because im encountering the same problem at the moment.

no bro nothing.... i just got a work around it... i just let it do what i want it to do and then unfollow manually those that it started following after i run this. normally they are only 4 or 8 people every time you want to run this. im sorry i didnt see your question before
