### ISSUE TITLE
No Comments 

### ISSUE THREAD

**Issue by zaras86** [InstaPy/InstaPy#3274]
## Expected Behavior
I want the bot to comment.

## Current Behavior
it is not commenting.

## Possible Solution (optional)
I'm a newbie and maybe it is tiny detail that I didn't recognize.^^

## InstaPy configuration
***my code****

 with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=4590,
                                        min_followers=45,
                                        min_following=77)
    
    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])
    
    
    # activity
    session.like_by_tags(["cars"], amount=19)
    session.set_do_comment(enabled=True, percentage=25)
    session.set_comments([' :+1:',' :clap:'])
+++++++
It's working but not commenting.

**Comment by converge** [comment]
hey, you should call the like action after the commenting setup.

```
session.set_do_comment(enabled=True, percentage=25)
session.set_comments([' :+1:',' :clap:'])
session.like_by_tags(["cars"], amount=19)
```
more logic 😄 
*reopen if you need more help
