### ISSUE TITLE
Unfollow people with N posts

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#3278]
Hello is there anyway unfollowing people with N posts.

Any idea please @uluQulu 

Many thanks.

**Comment by uluQulu** [comment]
Hi @Edhim 
Would you like to unfollow people [from a given list?] who has e.g. 500+ posts?
Try to explain in full, I will help you achieve it.

**Comment by Edhim** [comment]
@uluQulu I want to unfollow people that i follow that have 0 Post .. 1 post ..

**Comment by sionking** [comment]
could be a nice idea to implement a unfollow verification stage

**Comment by Edhim** [comment]
i think also something could be interesting, like by location ( using many locations at same time )
