### ISSUE TITLE
No error but stopped working

### ISSUE THREAD

**Issue by tierten** [InstaPy/InstaPy#3280]
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2018-11-02 14:21:02] [username]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Updated to the latest commit. The bot opened Chrome and it stays on the IG login page. Occasionally, the bot is able to login. The Chrome browser is not frozen. It's like the bot has paused.

**Comment by CharlesCCC** [comment]
please provide more detail, you configuration, your OS etc.

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
