### ISSUE TITLE
Running into a traceback error.

### ISSUE THREAD

**Issue by BlakeNoteee** [InstaPy/InstaPy#3286]
Traceback (most recent call last):
    File "Massive.py", line 10, in <module>
        from instapy import InstaPy
ImportError: No module named requests

Every quickstart template gives me this error. Anyone know whats the reasoning?

**Comment by converge** [comment]
hey, you will need to install requests package,
```pip install requests ; pip3install requests```

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)

**Comment by idnr** [comment]
Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
ImportError: No module named instapy
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
