### ISSUE TITLE
Step 0.3 on How_to_Windows.md needs updating

### ISSUE THREAD

**Issue by ShiftingKill** [InstaPy/InstaPy#3289]
## Expected Behavior
The link under step 0.3 Microsoft Visual C++ 2015 Build Tools brings us to https://landinghub.visualstudio.com/visual-cpp-build-tools
## Current Behavior
The link https://landinghub.visualstudio.com/visual-cpp-build-tools under Visual C++ 2015 Build Tools is outdated and gives a 404 error.
## Possible Solution (optional)
It seems like there is no direct link to the 2015 Build Tools, do users start using 2017?

**Comment by CharlesCCC** [comment]
Can you please find the latest/updated link so we can get that updated ?

**Comment by ShiftingKill** [comment]
> Can you please find the latest/updated link so we can get that updated ?

I have now thoroughly checked the visualstudio, as well as all the Microsoft sites that have to do with that particular download, I even checked under "old versions" whilst being signed into my Microsoft account and all of the results are missing. It seems they are forcing everyone to use C++ Build Tools 2017

TL:DR C++ 2017 Build Tools works and is the only way according to my investigation.

Idk about doing a pull request for this so I'll leave this issue open and hopefully another contributor that knows more about this subject can submit the right link in the PR.

**Comment by CharlesCCC** [comment]
@ShiftingKill I guess as long as the C++ 2017 works, we just need update the download link to the 2017 version.  thank you for looking into it and confirmed it worked.
