### ISSUE TITLE
How often do these processes get executed?

### ISSUE THREAD

**Issue by TiasTias** [InstaPy/InstaPy#3293]
Hello! I am new here and am forming my quickstart script. I don't fully understand how frequent these processes get executed and I cannot find this in the documentation. I believe follow_user_followers() runs continuously taking breaks when it reaches it's limit and sleeps for a while but how often does like_by_feed and like_by_location run?

    session.follow_user_followers(random_targets, amount=random.randint(30,60), randomize=True, sleep_delay=600, interact=True)
    session.like_by_feed(amount=100, randomize=True, unfollow=False, interact=False)
    session.like_by_locations(['213131048'], amount=5, skip_top_posts=False)

**Comment by converge** [comment]
it will run just after follow_user_followers() end, it will like 100 posts then like 5 posts from the 213131048 location.

**Comment by TiasTias** [comment]
And if it's inside smart_run(session): do these three function just loop indefinitely?

**Comment by converge** [comment]
@TiasTias I dont know much about how smart_run() is implemented, but it should behave the same way we had before (with try/catch).
