### ISSUE TITLE
Insuffisient number of links even after a long break

### ISSUE THREAD

**Issue by Nocturnal-2** [InstaPy/InstaPy#3295]
I am running the bot almost after 3 weeks. The moment I begin I get the message "Insufficient amount of links ~ trying again: 1". It never fetches more more than 24 images for a hashtag. 

Does this mean that there is something has gone wrong with my account? 

## InstaPy configuration

`session.like_by_tags(['discoverportrait', 'pursuitofportraits'], amount=100)`

**Comment by pinkoveralls** [comment]
I'm having the same issue, if I leave the chrome  window open without minimizing it works correctly, but I'd love to find an actual solution to the issue. It's also talked about here #2546

**Comment by converge** [comment]
trying to reproduce the issue without success.. is there some other detail that would help me reproduce it ?

**Comment by pinkoveralls** [comment]
@converge I just started having the issue today without any changes on my end, my quickstart.py looks like this if it helps

```
""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy.util import smart_run



# login credentials
insta_username = 'username'
insta_password = 'password'

dont_like = ['tags I don't want liked']

do_like = ['tags I want to like by']

say_things = ["list of comments to make"]
	
	
# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)
				  


with smart_run(session):
    """ Activity flow """
    # settings
    session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=7000,
                                        min_followers=50,
                                        min_following=77)
    
    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(dont_like)
	
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
	                          peak_likes=(41, 600),
                               peak_comments=(25, 400),
                                peak_follows=(41, 600),
                                 peak_unfollows=(0, 0),
                                  peak_server_calls=(None, 4700))
	
    # actions
    session.set_do_follow(enabled=True, percentage=50, times=2) #times=number of times to follow a user if unfollowed
    session.set_do_comment(enabled=True, percentage=30)
    session.set_comments(say_things, media='Photo')
    session.like_by_tags(do_like, amount=600, randomize=True, media='Photo')
```

**Comment by Nocturnal-2** [comment]
Here is my quickstart.py settings. I use the latest code

`insta_username = 'xxx'
insta_password = 'xxx'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)


with smart_run(session):
    # settings
    # don't like if a post already has more than 125 likes
    session.set_delimit_liking(enabled=True, max=150, min=0)

    # don't comment if a post already has more than 4 comments
    session.set_delimit_commenting(enabled=True, max=4, min=0)`

    # skip business accounts
    session.set_skip_users(skip_private=True,
                           skip_no_profile_pic=True,
                           skip_business=True,
                           business_percentage=100)

    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=-0.50,
                                    delimit_by_numbers=True,
                                    max_followers=1700,
                                    max_following=5000,
                                    min_followers=30,
                                    min_following=30)
    session.set_do_comment(False, percentage=20)
    session.set_do_follow(enabled=True, percentage=20, times=2)

    session.set_sleep_reduce(250)

    """ Check whether "set_quota_supervisor" is avalaible in the """

    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"],
                                 sleepyhead=True, stochastic_flow=True, notify_me=True,
                                 peak_likes=(100, 500),
                                 peak_comments=(25, 100),
                                 peak_follows=(48, 50),
                                 peak_unfollows=(35, 50),
                                 peak_server_calls=(None, 1500))

    """ Actions start here """

    session.like_by_tags(['discoverportrait', 'pursuitofportraits'], amount=100)
`

**Comment by julienteyssier** [comment]
Same issue for me :/

**Comment by lazlazlaz** [comment]
I'm having the same error with some of the tags.

Just so I understand. Can someone clarify the error? IS this happening because I hit the tag too often? There are plenty of possible posts, so how does that work? :) 

 desired amount: 15  |  top posts [disabled]: 8  |  possible posts: 1489764297
Insufficient amount of links ~ trying again: 1
Insufficient amount of links ~ trying again: 2
Insufficient amount of links ~ trying again: 3

Cor! Did you send too many requests? ~ let's rest some

**Comment by kev-mas** [comment]
Same issue here :( Just started running the script, and it has done one Tag, and then rested.
