### ISSUE TITLE
Need assistance to make my desired actions.

### ISSUE THREAD

**Issue by Solly95** [InstaPy/InstaPy#3298]
## Expected Behavior
I want the bot to follow a user's following and they are 72 followers and then wait 5 minutes and unfollow those same 72 followers, and repeat the whole process, is that possible? and if so, how...?

**Comment by sionking** [comment]
Y

**Comment by Solly95** [comment]
can anyone assist me?

**Comment by Solly95** [comment]
hello?

**Comment by Solly95** [comment]
> Y
@sionking 
can you kindly assist me writing this code? I'm so sorry to bother you, I'm not skilled at all.
