### ISSUE TITLE
Couldn't find user_div. Now getting 'Already Liked!'

### ISSUE THREAD

**Issue by ohitsbill** [InstaPy/InstaPy#330]
I was getting an error that the element with class name '_nk46a' couldn't be found and each selected image was just skipped. I think I worked out what it was looking for and changed the code to

`  user_div = browser.find_element_by_class_name('_99ch8')
`

But now every image isn't being skipped right away, but is coming up as Already Liked and then being skipped. Can't seem to work out why; I guess it's looking at the the wrong button or something? The issue seems to be in like_image in like_util.py

**Comment by timgrossmann** [comment]
@ohitsbill I don't think touching the code for such changes is not too good of an idea.

Could you post some links to Images that throw this error, please?
