### ISSUE TITLE
New Issue with google.protobuf.json_format - Need a Solution 

### ISSUE THREAD

**Issue by sohumsanu** [InstaPy/InstaPy#3300]
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 24, in <module>
    from .clarifai_util import check_image
  File "/root/InstaPy/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "/usr/local/lib/python2.7/dist-packages/clarifai-2.4.0-py2.7.egg/clarifai/rest/__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "/usr/local/lib/python2.7/dist-packages/clarifai-2.4.0-py2.7.egg/clarifai/rest/client.py", line 27, in <module>
    from clarifai.rest.grpc.grpc_json_channel import GRPCJSONChannel, dict_to_protobuf, protobuf_to_dict
  File "/usr/local/lib/python2.7/dist-packages/clarifai-2.4.0-py2.7.egg/clarifai/rest/grpc/grpc_json_channel.py", line 5, in <module>
    from clarifai.rest.grpc.custom_converters.custom_dict_to_message import dict_to_protobuf
  File "/usr/local/lib/python2.7/dist-packages/clarifai-2.4.0-py2.7.egg/clarifai/rest/grpc/custom_converters/custom_dict_to_message.py", line 1, in <module>
    from google.protobuf.json_format import _Parser
ImportError: No module named google.protobuf.json_format

I'm just running quickstart.py with nothing else added to it and I'm running into this error. I'm proficient in python and am unable to fix this error. Does anyone have a solution for this?

Thanks.

**Comment by converge** [comment]
- run it with a normal uses, not root
- use python3, it will probably fix the isssue

**Comment by sohumsanu** [comment]
Great that worked! 

Thank You!

**Comment by GabrieleCalarota** [comment]
I have this issue with clarifai ...I'm not running with sudo and I'm using python3. I'm having this issue since last night (I've received an email from clarifai for the changes introduced, but I haven't found a change in the documentation)

**Comment by sionking** [comment]
Me 2 !

**Comment by GabrieleCalarota** [comment]
Any workaround???

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)

**Comment by sionking** [comment]
@converge  after this req installation I see duplicated logs!

**Comment by converge** [comment]
@sionking same here, I was debugging it yesterday, couldn't find a solution, I guess it's something on our implementation of Logger. Before my update some people were complaining about duplicated logs, it's a good thing that it showed up, now we can fix it.

The big issue atm is that FileHandler is trowing message to stdout, it should only write to the file.

**Comment by GabrieleCalarota** [comment]
Which was the module missing? I've updated clarifai module too, but the issue still remains

**Comment by converge** [comment]
@GabrieleCalarota the requirements.txt was very outdated , no one was using it I guess, just updated it all.

**Comment by doemint** [comment]
Hello.
Sorry to bother, but I have the same problem
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/home/jordi/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/jordi/InstaPy/instapy/instapy.py", line 24, in <module>
    from .clarifai_util import check_image
  File "/home/jordi/InstaPy/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "/usr/local/lib/python3.4/dist-packages/clarifai/rest/__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "/usr/local/lib/python3.4/dist-packages/clarifai/rest/client.py", line 27, in <module>
    from clarifai.rest.grpc.grpc_json_channel import GRPCJSONChannel, dict_to_protobuf, protobuf_to_dict
  File "/usr/local/lib/python3.4/dist-packages/clarifai/rest/grpc/grpc_json_channel.py", line 5, in <module>
    from clarifai.rest.grpc.custom_converters.custom_dict_to_message import dict_to_protobuf
  File "/usr/local/lib/python3.4/dist-packages/clarifai/rest/grpc/custom_converters/custom_dict_to_message.py", line 1, in <module>
    from google.protobuf.json_format import _Parser
ImportError: No module named 'google.protobuf'

Any idea how to solve it? I can't manage to run the simple script :(
Thanks in advance

**Comment by xWHOISF** [comment]
> Hello.
> Sorry to bother, but I have the same problem
> Traceback (most recent call last):
> File "quickstart.py", line 3, in
> from instapy import InstaPy
> File "/home/jordi/InstaPy/instapy/**init**.py", line 3, in
> from .instapy import InstaPy
> File "/home/jordi/InstaPy/instapy/instapy.py", line 24, in
> from .clarifai_util import check_image
> File "/home/jordi/InstaPy/instapy/clarifai_util.py", line 3, in
> from clarifai.rest import ClarifaiApp
> File "/usr/local/lib/python3.4/dist-packages/clarifai/rest/**init**.py", line 3, in
> from clarifai.rest.client import ApiClient
> File "/usr/local/lib/python3.4/dist-packages/clarifai/rest/client.py", line 27, in
> from clarifai.rest.grpc.grpc_json_channel import GRPCJSONChannel, dict_to_protobuf, protobuf_to_dict
> File "/usr/local/lib/python3.4/dist-packages/clarifai/rest/grpc/grpc_json_channel.py", line 5, in
> from clarifai.rest.grpc.custom_converters.custom_dict_to_message import dict_to_protobuf
> File "/usr/local/lib/python3.4/dist-packages/clarifai/rest/grpc/custom_converters/custom_dict_to_message.py", line 1, in
> from google.protobuf.json_format import _Parser
> ImportError: No module named 'google.protobuf'
> 
> Any idea how to solve it? I can't manage to run the simple script :(
> Thanks in advance

I had the same problem and resolved by deleting and reinstalling it.

pip uninstall protobuf
pip uninstall google
pip install google
pip install protobuf
pip install google-cloud

FYI: if you're using pip version 3, try with this: pip3 uninstall or install....
