### ISSUE TITLE
InstaPy follows accounts I know/recommended accounts

### ISSUE THREAD

**Issue by 46960** [InstaPy/InstaPy#3303]
## Expected Behavior
Follow the followers of a user

## Current Behavior
Follows friends of friends, or accounts that a lot of friends follow (e.g. also people you want to avoid following and unfollowing :)).

## Thoughts
This has been uncomfortable because after unfollowing them people started getting confused and messaging me. Some of them were also people from work, too. Then I started noticing that the "follow a user's followers" feature first follows the people that instagram intelligently picks and suggests for you. Is there any way at all to circumvent this without changing the randomize setting to "TRUE"? I prefer to keep randomize false, because it will pick the most recent followers of an account, instead of random ones which might have become inactive. 

Looking forward to your replies!

**Comment by cainky** [comment]
Same issue as #3180

**Comment by Nocturnal-2** [comment]
This is also happening with interact_user_followers(). This is embarrassing...

**Comment by JonathandelaSen** [comment]
Same here, and yes, so embarrassing...
