### ISSUE TITLE
Following accounts but have no code set to follow

### ISSUE THREAD

**Issue by deronsizemore** [InstaPy/InstaPy#3306]
## Expected Behavior

Unfollow users

## Current Behavior

Seems to be following new accounts rather than unfollowing. I have a cron set up to run each morning. Yesterday morning I had 7192 following and today I'm at 7221. I have no code set up to follow accounts unless I'm missing something?

## InstaPy configuration

```
random_delay = random.randrange(0,350)

try:
    session.login()

    # settings
    session.set_relationship_bounds (
                    enabled=True,
                    potency_ratio=None,
                    delimit_by_numbers=True,
                    max_followers=None,
                    max_following=None,
                    min_followers=100,
                    min_following=None
                    )
    session.set_dont_include(friends)

    # actions
    session.unfollow_users(amount=100, allFollowing=True, style="LIFO", sleep_delay=random_delay)
    session.like_by_tags(like_tags, amount=100, interact=True)
```

**Comment by converge** [comment]
sounds like it's following the suggestion screen profiles

**Comment by IH4xx3R** [comment]
Do you follow private users too? If so, maybe they have accepted your follow-request, while your are unfollowing.

**Comment by deronsizemore** [comment]
@converge Is there something in my code telling the script to do that? What am I missing?

@IH4xx3R I do follow private profiles, but I haven't followed anyone in months and I don't use this Instapy script to follow accounts (only to unfollow and like) so I doubt that all of a sudden I would have had that many accept my request at once, but I guess anything's possible.

**Comment by converge** [comment]
@deronsizemore the thing is that IG added this new feature (suggestion profiles inside your following screen, when we hit the "following" button, it's somehow clicking on "follow"(suggestion) button)

**Comment by deronsizemore** [comment]
@converge Ah, I see. So is the unfollow feature working at all right now or is it broken as a result? I'll have to test it tomorrow but I think I let it auto-run with a cron a couple days in a row and I'm not sure it unfollowed anyone (and I actually followed more)

**Comment by converge** [comment]
Sometimes sounds like we have two working versions of Instagram, this behavior happens to just some accounts, that's why it's difficult to fix, it needs to happens to someone that is developing it to fix the issue.
