### ISSUE TITLE
Help!! I Cant unfollow 

### ISSUE THREAD

**Issue by DNUSH** [InstaPy/InstaPy#3307]
## Current Behavior

ERROR [2018-11-06 17:03:26] [x]  Sorry, an error occurred: HTTPConnectionPool(host='127.0.0.1', port=56975): Max retries exceeded with url: /session/73d5972e40e6a9c0b433667e7b6aeec0/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x047D7D50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Traceback (most recent call last):
  File "x.py", line 37, in <module>

## InstaPy configuration

import os
from instapy import InstaPy
from instapy.util import smart_run
insta_username = 'user'
insta_password = 'pass'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

with smart_run(session):

    session.set_relationship_bounds(enabled=True,
                                     potency_ratio=None,
                                     delimit_by_numbers=True,
                                      max_followers=6000,
                                      max_following=3000,
                                      min_followers=30,
                                      min_following=30)
    session.set_user_interact(amount=3, randomize=True, percentage=50, media='Photo')
    session.set_do_like(enabled=True, percentage=100)

ammount_number=2000
session.follow_user_followers(['x', 'xx', 'xxx', 'xxxx', 'xxxxx', 'xxxxxx, 'xxxxxxx', 'xxxxxxxx', 'xxxxxxxxx], amount=ammount_number, randomize=False, interact=True, sleep_delay=600)
 
session.unfollow_users(amount=18000, InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=24*60*60, sleep_delay=601)

session.follow_user_followers(['x', 'xx', 'xxx', 'xxxx', 'xxxxx', 'xxxxxx, 'xxxxxxx', 'xxxxxxxx', 'xxxxxxxxx], amount=ammount_number, randomize=False, interact=True, sleep_delay=600)
  

session.unfollow_users(amount=1800, InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=24*60*60, sleep_delay=601)

session.unfollow_users(amount=14000, InstapyFollowed=(True, "all"), style="RANDOM", unfollow_after=168*60*60, sleep_delay=600)

**Comment by Vulpixxx** [comment]
How many user you follow?

**Comment by DNUSH** [comment]
> How many user you follow?

3435

**Comment by DNUSH** [comment]
Now I also get the same error when following someone, before only happened with the unfollow but now with the follow also

**Comment by arshiyasolei** [comment]
"because the target machine actively refused it'))"
You probably got banned lol.
Hopefully, it will be only temp.

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
