### ISSUE TITLE
After successful login - wrong login data error

### ISSUE THREAD

**Issue by sweb1** [InstaPy/InstaPy#331]
I have installed Instapy on windows 10 following the setup instructions at https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Windows.md
Problem:
After starting the program via GUI or from command line, the chrome window appears, logs in successfully (I can see my instagram home screen) and shuts down after 1 second. Following errors message appears in the console:
Session started - 2017-06-20 21:49:51
Wrong login data!

Session ended - 2017-06-20 21:49:59

Here is some environment information:

C:\Users\Andreas\AppData\Local\Programs\Python\Python36\Scripts>pip install selenium
Requirement already satisfied: selenium in c:\users\andreas\appdata\local\programs\python\python36\lib\site-packages

C:\Users\Andreas\AppData\Local\Programs\Python\Python36\Scripts>python -m pip install pyvirtualdisplay
Requirement already satisfied: pyvirtualdisplay in c:\users\andreas\appdata\local\programs\python\python36\lib\site-packages
Requirement already satisfied: EasyProcess in c:\users\andreas\appdata\local\programs\python\python36\lib\site-packages (from pyvirtualdisplay)

C:\Users\Andreas\AppData\Local\Programs\Python\Python36\Scripts>py get-pip.py
C:\Users\Andreas\AppData\Local\Programs\Python\Python36\python.exe: can't open file 'get-pip.py': [Errno 2] No such file or directory

**Comment by timgrossmann** [comment]
@sweb1 Try to login yourself on the webpage.
You might have to click on a "This was me" Button in order to make it work :wink:

**Comment by sweb1** [comment]
Good idea but I guess there is no such button and if it was, chrome closes too fast to click it ;)

**Comment by timgrossmann** [comment]
@sweb1 

I mean in a normal browser window, not with the script.
Just log in to your instagram account like you would on the web page
