### ISSUE TITLE
follow user followers - blacklist.csv error

### ISSUE THREAD

**Issue by alekseitsvetkov** [InstaPy/InstaPy#3316]
## Current Behavior

`Traceback (most recent call last):
  File "quickstart.py", line 42, in <module>
    session.follow_user_followers(['thebeeest'], amount=800, randomize=False, interact=False, sleep_delay=60)
  File "/Users/mac/Documents/ig/InstaPy/instapy/instapy.py", line 2870, in follow_user_followers
    validation, details = self.validate_user_call(person)
  File "/Users/mac/Documents/ig/InstaPy/instapy/instapy.py", line 1110, in validate_user_call
    self.logger)
  File "/Users/mac/Documents/ig/InstaPy/instapy/util.py", line 134, in validate_username
    with open("{}blacklist.csv".format(logfolder), 'rt') as f:
IOError: [Errno 2] No such file or directory: '/Users/mac/Documents/ig/InstaPy/logs/myusername/blacklist.csv'`

## Possible Solution (optional)

I created the file manually while it works

## InstaPy configuration
session.set_relationship_bounds(enabled=True,
                                                          delimit_by_numbers=True,
                                                          max_followers=4590,
                                                          min_followers=30,
                                                          min_following=60)

 session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=False,
 peak_likes=(57, 585),
 peak_comments=(21, 182),
 peak_follows=(48, None),
 peak_unfollows=(35, 402),
 peak_server_calls=(None, 4700))
    
 session.set_skip_users(skip_private=True,
                                         private_percentage=100,
                                         skip_no_profile_pic=True,
                                         no_profile_pic_percentage=100)

**Comment by raphson93** [comment]
does it work ?

**Comment by alekseitsvetkov** [comment]
> does it work ?

Yes, this error occurred on startup

**Comment by ghost** [comment]
I also have the same issue, with the latest pull.

Haven't changed my code and didn't have this issue few days ago

**Comment by kwstasna** [comment]
same issue with the latest pull also!

**Comment by danialmoghaddam** [comment]
I am getting the same - started right after latest pull

**Comment by danialmoghaddam** [comment]
I temporarily fixed it by running `> /InstaPy/logs/username/blacklist.csv`
