### ISSUE TITLE
Unfollow / re follow and liking tags

### ISSUE THREAD

**Issue by balakedev** [InstaPy/InstaPy#332]
not so much an issue, but a couple of questions:

i have InstaPy working perfectly, yet i would like to know if you can set the instaPy to like most recent posts in a tag instead of most popular/trending?

secondly,

session.set_do_follow(enabled=True, percentage=10, times=2)

i know that the first part means that following is =true, and it will follow 10% of pages it interacts with. Can someone please further explain times=2? does this mean once the bot unfollows a user it will only follow them 1 more additional time then unfollow again and never return to it? thus limiting the amount of follows/ unfollows to said account?

additionally, is there any way to make the unfollowing random instead of most recent?

**Comment by timgrossmann** [comment]
@blakemmw The most recent posts are liked after the top posts... You can also set the `.set_upper_follower` to make sure the first 9 posts are not liked

secondly
Yes, exactly how you described the times feature.

No, by now there is no other unfollow feature

**Comment by balakedev** [comment]
So if I say .set_uppper_follower to say.. 10 it'll skip the first 10? I literally learnt python when discovered instaPy yesterday... still getting my head around it - havnt covered it at uni yet. 

Also, running the script takes about 3 hours, I have 16 hashtags and 22 likes for each. Is there a way to speed this up or is it like this to make sure it looks more like a human interaction? 

You're a legend for developing this btw. Top stuff.

**Comment by timgrossmann** [comment]
@blakemmw No, check the readme for documentation.

It says, that every account which has more than 10 follower (in case you provide 10) will be skipped.
Read the Readme please.

Haha, to be honest this is like a really really bad tactic. If you want to include all of the tags, simply do 5 each time.

Pick some with random, e.g. do 

```python
random.sample(['tag1', 'tag2', ...], 5)

**Comment by balakedev** [comment]
Also, I'm getting "throttled. Waiting 10 seconds" what does this mean ?

**Comment by timgrossmann** [comment]
@blakemmw 
Do you use Clarifai?

**Comment by balakedev** [comment]
Yeah I have an account and I put the secret and ID in correctly

**Comment by timgrossmann** [comment]
@blakemmw  Then you probably have exceeded the monthly limit of 5000 requests ;)

**Comment by balakedev** [comment]
thats weird, that was the first run i used with it...
