### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 54: ordinal not in range(128)

### ISSUE THREAD

**Issue by kushpvo** [InstaPy/InstaPy#3321]
## Current Behavior

  File "quickstart.py", line 48, in <module>
    session.like_by_tags(['#buildtheweb', '100daysofcode'], amount=randint(minTag, maxTag), skip_top_posts=True)
  File "/home/pi/Desktop/InstaPy/instapy/instapy.py", line 1737, in like_by_tags
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 54: ordinal not in range(128)

## InstaPy configuration
session.like_by_tags(['#buildtheweb', '100daysofcode'], amount=randint(minTag, maxTag), skip_top_posts=True)

**Comment by elulcao** [comment]
Hello Team,

I faced the same error at line 1737, I just added 10 words to set_ignore_if_contains() and other 10 to interact_user_followers(). So, the problem is not related to the amount of pictures or array list size. To me the problem is related to specials character, we are lucky if hit the problem which is not reproducible all the times due to the interaction changes across the time.

After a sever attempts I discovered that the line 1737 couldn't handle strings even when the code is using UTF-8. So, to avoid the problem I decide to ignore the "unreadable" text and move on; see lines below. Tested at local (no crontab) and finished without problems.

Seems to me that the following character is the culprit "ö", the quickstart failed all the time when reading the following hashtags (🤓):

Hashtags
```
#love #watchporn #skyporn #foodporn#sexymom #sexy #fuck #fucklove #kiss#kissingvideo #kisses #kisses💋 #boobsfordays#boobsvideo #hotboobs #boobsqueeze#boobsofinstagram #boob #böobs#bootybootybooty #bootypics #bootyfordays#bootylicious🍑 #bootyworkout #bootybuilding#hotsprings #life #bigboobsforlife
```

Traceback
```
Traceback (most recent call last):
  File "./quickstart_simple_interaction_test.py", line 41, in <module>
    'legs'], amount=10, interact=True)
  File "/Users/elulcao/Desktop/Projects/InstaPy/instapy/instapy.py", line 1737, in like_by_tags
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 43: ordinal not in range(128)
```

Code
```python        
1735             else:
1736                 self.logger.info(
1737                     '--> Image not liked: {}'.format(reason.encode('utf-8', 'ignore'))) #Added 'ignore'
1738                 inap_img += 1
```

$ git show-branch
[master] Merge pull request #3420 from timgrossmann/grab_likers_fix_xpath

Sharing this as W/A...

**Comment by oskarkrawczyk** [comment]
I have the exact same problem:

```
Traceback (most recent call last):
  File "qs-likes.py", line 71, in <module>
    session.like_by_tags(like_tag_list, amount=random.randint(50, 100), interact=True)
  File "/Users/oskarkrawczyk/Sites/InstaPy/instapy/instapy.py", line 1726, in like_by_tags
    self.user_interact_media)
  File "/Users/oskarkrawczyk/Sites/InstaPy/instapy/instapy.py", line 1939, in like_by_users
    '--> Image not liked: {}'.format(reason.encode('utf-8')))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 53: ordinal not in range(128)
```

**Comment by elulcao** [comment]
The encode cannot convert to unicode. If you run the same for encoding a string python (python2.7 in my case) trows the same stack. The only clue I have is that the string isn't a valid ASCII.

Added this line:  ``` # -*- coding: utf-8 -*- ```
at the very beginning of instapy.py as other attempt, I will let you know if it works.

```
$ bat ex.py
───────┬─────────────────────────────────────
       │ File: ex.py
───────┼─────────────────────────────────────
   1   │
   2   │ print "Hello World!"
   3   │
   4   │ utf_string = u'café'
   5   │ byte_string = utf_string.encode('utf-8')
   6   │ print byte_string
   7   │
   8   │ utf_string = u'cafö'
   9   │ byte_string = utf_string.encode('utf-8')
  10   │ print byte_string
```

```
$ python ex.py
  File "ex.py", line 3
SyntaxError: Non-ASCII character '\xc3' in file ex.py on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```


```
$ bat ex.py
───────┬─────────────────────────────────────
       │ File: ex.py
───────┼─────────────────────────────────────
   1   │ # -*- coding: utf-8 -*-
   2   │
   3   │ print "Hello World!"
   4   │
   5   │ utf_string = u'café'
   6   │ byte_string = utf_string.encode('utf-8')
   7   │ print byte_string
   8   │
   9   │ utf_string = u'cafö'
  10   │ byte_string = utf_string.encode('utf-8')
  11   │ print byte_string
───────┴─────────────────────────────────────
$ python ex.py
Hello World!
café
cafö
```

**Comment by Fellowes52** [comment]
Hi @Elulcao, did yours fix after this? I applied your suggestion in line 1737. However it's still persistent. Any other suggestions/ideas?

**Comment by elulcao** [comment]
@Fellowes52 

Added this line: # -*- coding: utf-8 -*-
at the very beginning of instapy.py as other attempt, It worked to me.

**Comment by Fellowes52** [comment]
@Elulcao

I tried this on line 1 of instapy.py, saved and ran the script.

Run straight into an issue on like the 30/40 like. Any other ideas lol

**Comment by elulcao** [comment]
@Fellowes52
But what is the error?
Better to share it to understand the issue

**Comment by Fellowes52** [comment]
@Elulcao

Sorry for slow reply I wanted to test again to see if any issues arrived. It did again :(

I am on my mobile browser so here's a link to my error (screenshot)

https://ibb.co/d4Nx770

**Comment by muad-dweeb** [comment]
I solved the issue on my end with this addition to `instapy.py`:

```
import sys
reload(sys)
sys.setdefaultencoding('utf8')
```

You can view the change on my fork here (Line 20):
https://github.com/muad-dweeb/InstaPy/blob/master/instapy/instapy.py
