### ISSUE TITLE
Image check error: Failed to parse models field: Failed to parse model_version field

### ISSUE THREAD

**Issue by bongo48** [InstaPy/InstaPy#3333]
## Current Behavior
ERROR [2018-11-09 12:10:57] [xxxxx]  Image check error: Failed to parse models field: Failed to parse model_version field: Message type "clarifai.api.ModelVersion" has no field named "train_stats".
 Available Fields(except extensions): [<google.protobuf.descriptor.FieldDescriptor object at 0x046BDA50>, <google.protobuf.descriptor.FieldDescriptor object at 0x046BDA90>, <google.protobuf.descriptor.FieldDescriptor object at 0x046BDAD0>, <google.protobuf.descriptor.FieldDescriptor object at 0x046BDAF0>, <google.protobuf.descriptor.FieldDescriptor object at 0x046BDB30>, <google.protobuf.descriptor.FieldDescriptor object at 0x046BDB50>, <google.protobuf.descriptor.FieldDescriptor object at 0x046BDB90>]
ERROR [2018-11-09 12:10:57] [xxxxxx]  Image check error: cannot unpack non-iterable NoneType object

## InstaPy configuration
import os
import time
from tempfile import gettempdir
from selenium.common.exceptions import NoSuchElementException
from instapy import InstaPy
session = InstaPy(username=insta_username,
password=insta_password,
headless_browser=False,
multi_logs=False)
try:
session.login()
##### clarifai api
session.set_use_clarifai(enabled = True, api_key = 'xxxxxxxxxxxxxxxxxxx')

session.unfollow_users(amount=1500, nonFollowers=True, style="RANDOM", unfollow_after=15*60*60, sleep_delay=600)        
session.set_relationship_bounds(enabled=True,
                 potency_ratio=-1.05,
                  delimit_by_numbers=True,
                   max_followers=30000,
                    max_following=7000,
                     min_followers=35,
                       min_following=77)
session.set_do_follow(enabled=True, percentage=90)
session.set_user_interact(amount=1, randomize=True, percentage=90, media='Photo')
session.set_do_comment(enabled=True, percentage=100)
session.set_comments([''])
session.set_delimit_commenting(enabled=True, max=32, min=2)
session.set_do_like(enabled=True, percentage=90)
session.clarifai_check_img_for (['nsfw', 'people', 'text', 'graphic design', 'pet', 'animal', 'food', 'women', 'low-quality', 'words', 'logo', 'fashion', 'child', 'baby', 'man', 'girl'])
session.clarifai_check_img_for (['landscape', 'travel', 'sunset', 'ocean', 'nature', 'road', 'sky', 'sun', 'beach'], comment=True, comments=[u'Wow! :ok_hand:'])

###### unfollow
session.unfollow_users(amount=1500, nonFollowers=True, style="RANDOM", unfollow_after=15*60*60, sleep_delay=600)   	

users_to_follow1 = session.grab_followers(username="xxxxxxxxxx", amount=300, live_match=True, store_locally=True)    
session.follow_by_list(users_to_follow1[:250], times=1, sleep_delay=100, interact=True)

**Comment by GabrieleCalarota** [comment]
Same here
See #3300

**Comment by bongo48** [comment]
First I tried `pip3 install -r requirements.txt` it didn't solve the issue, but... I uninstalled protobuf and installed again. Now works perfectly fine.
```
pip uninstall protobuf
pip install protobuf

```
