### ISSUE TITLE
'NoneType' Object is not iterable

### ISSUE THREAD

**Issue by jayyliss** [InstaPy/InstaPy#3335]
It try to run python quickstart.py but then I get this:

WARNING:root:Heeh! Error occurred while getting a DB profile for 'None':
	NOT NULL constraint failed: profiles.name
WARNING [2018-11-08 22:52:20] [None]  Heeh! Error occurred while getting a DB profile for 'None':
	NOT NULL constraint failed: profiles.name
Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    headless_browser=False)
  File "/Users/jordinlissone/InstaPy/instapy/instapy.py", line 229, in __init__
    get_database(make=True)
  File "/Users/jordinlissone/InstaPy/instapy/database_engine.py", line 41, in get_database
    id = get_profile(name, address, logger) if id is None or make else id
  File "/Users/jordinlissone/InstaPy/instapy/database_engine.py", line 126, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable
----------------------------------------------------------------------------
I tried to make an empty db folder, which didn't work. Still browsing around for solutions but not having any luck.

**Comment by filmancco** [comment]
I have tge same issue / error, please help

**Comment by bloggerstomper** [comment]
Same for me :(

**Comment by converge** [comment]
not exactly a bug.

could you confirm that your quickstart.py has a username set ?

example:
```python
session = InstaPy(username='your_username,
                  password='your_password',
```

I was able to reproduce it if the ```username``` variable is empty

**Comment by bloggerstomper** [comment]
> not exactly a bug.
> 
> could you confirm that your quickstart.py has a username set ?
> 
> example:
> 
> ```python
> session = InstaPy(username='your_username,
>                   password='your_password',
> ```
> 
> I was able to reproduce it if the `username` variable is empty

Username is indeed set

**Comment by jayyliss** [comment]
> not exactly a bug.
> 
> could you confirm that your quickstart.py has a username set ?
> 
> example:
> 
> ```python
> session = InstaPy(username='your_username,
>                   password='your_password',
> ```
> 
> I was able to reproduce it if the `username` variable is empty

Yes my username is set, and I'm still getting the error.

**Comment by membersnly** [comment]
> > not exactly a bug.
> > could you confirm that your quickstart.py has a username set ?
> > example:
> > ```python
> > session = InstaPy(username='your_username,
> >                   password='your_password',
> > ```
> > 
> > 
> > I was able to reproduce it if the `username` variable is empty
> 
> Username is indeed set

Got the same error I thought my username was set as well then I remembered to save the file I was working on...
After saving the file i re-ran the quickstart.py and it ran perfectly
Oopsie
