### ISSUE TITLE
Run two instances on DigitalOcean

### ISSUE THREAD

**Issue by AlexandruAcea** [InstaPy/InstaPy#334]
Hey guys, I bught a droplet from DigitalOcean and it's running really great. But I'm curious, could I run two bots at once in one droplet? Like having two terminal tabs open in MacOS. Thank you!

**Comment by timgrossmann** [comment]
@AlexandruAcea Yes you can if you time them (cronjob) without making them intersect.

E.g. 

Account 1: 0h 4h 8h 12h 16h 20h
Account 2: 2h 6h 10h 14h 18h 22h
