### ISSUE TITLE
Do you need help ? Check this

### ISSUE THREAD

**Issue by converge** [InstaPy/InstaPy#3341]
Hey guys, we have actually 1500+ open issues and it's a bit hard to respond everyone, identify what's a real bug and/or what's a setup issue.

We have this big group on Slack, but it isn't much active, so we thought about move our chat to Discord, organize it in channels (#general, #needing-help and #development).

**Feel free to join and help us organize the InstaPy community: https://discord.gg/FDETsht**

**Comment by Nocturnal-2** [comment]
I joined Discord group. How can I join the Slack group?

**Comment by converge** [comment]
@Nocturnal-2 welcome! I think we will delete the slack channel later and keep just the Discord channel.
