### ISSUE TITLE
Error: ImportError: No module named clarifai_util

### ISSUE THREAD

**Issue by bloggerstomper** [InstaPy/InstaPy#3346]
Hello all!

I've been trying to use the GUI of InstaPy and everytime I try to run it it just gives me that error

Error: ImportError: No module named clarifai_util

What am I doing wrong?

I'm running 
Python 2.7.10
on MacOs Mojave
I have clarify 2.4.1
Thank you!

**Comment by converge** [comment]
Hey, we did an update today, now everything you need to do to fix this kind (missing modules) of issue is:
```
pip3 install -r requirements.txt
```
(if you use python3)
