### ISSUE TITLE
Like by feed  liked old post like ???

### ISSUE THREAD

**Issue by jafaresk** [InstaPy/InstaPy#3349]
hi guys
Like by Feeds
session.like_by_feed(amount=100, randomize=True, unfollow=True, interact=True)

how  like new post  this for code up like  old post 
new postet no liked
plz help 
![1111](https://user-images.githubusercontent.com/44797335/48317289-f20d0f80-e604-11e8-870b-2f5fc2e25f22.jpg)

**Comment by converge** [comment]
Inactive issue, reopen if you still need assistance.
