### ISSUE TITLE
Follow_users_followers: tries to follow same business account (skip=True)

### ISSUE THREAD

**Issue by booksix** [InstaPy/InstaPy#3351]
## Expected Behavior
Tries to follow an account, sees it's a "business account" ... skips it and does not return to this account again.

## Current Behavior
    INFO [2018-11-11 19:00:01] [self]  Ongoing Follow [2/6]: now following 'food.fun.freebies'...
    INFO [2018-11-11 19:00:04] [self]  User: food.fun.freebies >> followers: 11  |  following: 7  |  relationship ratio: 1.57
    INFO [2018-11-11 19:00:04] [self]  food.fun.freebies has business account

    INFO [2018-11-11 19:00:04] [self]  Ongoing Follow [3/6]: now following 'food.fun.freebies'...
    INFO [2018-11-11 19:00:04] [self]  User: food.fun.freebies >> followers: 11  |  following: 7  |  relationship ratio: 1.57
    INFO [2018-11-11 19:00:04] [self]  food.fun.freebies has business account

## Possible Solution (optional)
A database or log would be a solution. HOWEVER, I'm more concerned with the fact that the exact same account is pulled from a users list of followers twice in a row, and often many more times within a single follow session (across multiple users follow lists). Also important to note is it's gotten pulled into to trying to follow this EXACT account within multiple login sessions (ie: instapy is completely shut down and restarted, with a new chrome session attached, etc... and still manages to find this account and try to follow it many times).

**Comment by DemonionFF** [comment]
Same problem here, but even for ```ignore_users``` list.

xxx = username
```
INFO [2019-01-23 15:56:12] [app]  Ongoing Follow [7/10]: now following 'xxx'...
INFO [2019-01-23 15:56:12] [app]  ---> 'xxx' is in the `ignore_users` list	~skipping user

INFO [2019-01-23 15:56:12] [app]  Ongoing Follow [8/10]: now following 'xxx'...
INFO [2019-01-23 15:56:12] [app]  ---> 'xxx' is in the `ignore_users` list	~skipping user

INFO [2019-01-23 15:56:12] [app]  Ongoing Follow [9/10]: now following 'xxx'...
INFO [2019-01-23 15:56:12] [app]  ---> 'xxx' is in the `ignore_users` list	~skipping user
```
