### ISSUE TITLE
Windows 10 with Ubuntu: Stuck on Cookie file not found, creating cookie 

### ISSUE THREAD

**Issue by Radzam** [InstaPy/InstaPy#3352]
It works on my mac but when I try it on Windows 10 that uses Ubuntu terminal as installed from windows store, it gets stuck on Cookie file not found, creating cookie. I tried reinstalling and following the ubuntu guide properly and I set headless browser to true but its just stuck on that message in the beginning. Anyone know why?

**Comment by Mehran** [comment]
where is your Ubuntu Server  ? in VPS?  I think your VPS IP has been blocked, you have two Options : 
1) try another VPS.
2) Copy cookie file from Mac to Ubuntu.

**Comment by converge** [comment]
just wrote a bugfix, are you available to help testing it ? https://github.com/timgrossmann/InstaPy/pull/3384

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
