### ISSUE TITLE
how do ac video to feed like plz see video to post 

### ISSUE THREAD

**Issue by jafaresk** [InstaPy/InstaPy#3359]
who like just feed my folowing just feed
plz see video just do it

![record_000005](https://user-images.githubusercontent.com/44797335/48356732-2daee480-e6ac-11e8-82fb-78403540f340.gif)

**Comment by uluQulu** [comment]
Hi @jafaresk 

All you want is "_Like by Feed_" feature of InstaPy:
```python
from instapy import InstaPy
from instapy.util import smart_run

session = InstaPy(username='', password='')

with smart_run(session):
    session.set_do_like(enabled=True, percentage=100)
    session.like_by_feed(amount=3)
```

---

Cheers 😁
---

**Comment by jafaresk** [comment]
how is file change ?

> Hi @jafaresk
> 
> All you want is "_Like by Feed_" feature of InstaPy:
> 
> ```python
> from instapy import InstaPy
> from instapy.util import smart_run
> 
> session = InstaPy(username='', password='')
> 
> with smart_run(session):
>     session.set_do_like(enabled=True, percentage=100)
>     session.like_by_feed(amount=3)
> ```
> 
> ## Cheers

which change file ?

**Comment by uluQulu** [comment]
@jafaresk 
Put it into your **quickstart.py** file.

**Comment by jafaresk** [comment]
not my video 
Your code will appear first find post then go to id following  and again  going post  and like

I want to thank the same page as Feed

> @jafaresk
> Put it into your **quickstart.py** file.

**Comment by jafaresk** [comment]
> @jafaresk
> Put it into your **quickstart.py** file.

plz see again video to Feed  just like  and  after post  like scroll down like post

**Comment by uluQulu** [comment]
@jafaresk 
I have given the simplest example for your need as I understood.

If it is not what you want, explain yourself clearly to get further help,
+ write in **proper** english
+ write in your language **grammatically** correct so that translators can translate it
+ ask some english-speaking _friend_ to translate it
+ invite @Mehran 🤝🏼 to translate it for you [from persian]
+ write in `azerbaijani` 😎 [if you know]

Other way, I have no way to help you.

---

Cheers 😛
---

**Comment by jafaresk** [comment]
> @jafaresk
> I have given the simplest example for your need as I understood.
> 
> If it is not what you want, explain yourself clearly to get further help,
> 
> * write in **proper** english
> * write in your language **grammatically** correct so that translators can translate it
> * ask some english-speaking _friend_ to translate it
> * invite @Mehran 🤝🏼 to translate it for you [from persian]
> * write in `azerbaijani` sunglasses [if you know]
> 
> Other way, I have no way to help you.
> 
> ## Cheers

I want the robot to come to Instagram
Then you're on the home page 
Just see the post
And likes it

and send email  mehran   send my problem

**Comment by jafaresk** [comment]
> @jafaresk
> I have given the simplest example for your need as I understood.
> 
> If it is not what you want, explain yourself clearly to get further help,
> 
> * write in **proper** english
> * write in your language **grammatically** correct so that translators can translate it
> * ask some english-speaking _friend_ to translate it
> * invite @Mehran 🤝🏼 to translate it for you [from persian]
> * write in `azerbaijani` sunglasses [if you know]
> 
> Other way, I have no way to help you.
> 
> ## Cheers

I want the robot to come to Instagram
Then you're on the home page
Just see the post
And likes it

and send email mehran send my problem

**Comment by uluQulu** [comment]
Well, @jafaresk 

_I will write in simple english for you to understand easily_.

The code I wrote above does exactly what you want.
It just works differently than you expect:
+ It takes the links of posts from your home page.
+ Then it opens those posts one by one and puts like on them.

What you expect is doing it right at the home page scrolling down..
But well, that is not how InstaPy works;
+ One advantage of opening pages in a separate page is you can view lots of data of the post..


---
_Use the code I wrote above and observe how it works, you will understand 👈🏼🎉easily🎉_.

Cheers 🤩
---

**Comment by jafaresk** [comment]
Mr @uluQulu 
yes i expect it right at home page scrolling down  
this code very easy  to home page scrolling down like scroll down like just

Code InstaPy very professional  
to algorithm Instagram  just  post is very view better in to like home page 
not link not hashtagh not location
