### ISSUE TITLE
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by sweb1** [InstaPy/InstaPy#336]
Using "Follow from list" in the GUI, it follows first one or two users ok, then script stops with this error message:
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=58.0.3029.110)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.15063 x86_64)

**Comment by timgrossmann** [comment]
@sweb1 This is probably not a problem with InstaPy itself, I'll leave this open, but also make sure to post this problem on the GUI Repo

**Comment by doremidom** [comment]
Getting this issue as well

**Comment by Mehnou** [comment]
I'm getting this as well, after downloading that last update

**Comment by timgrossmann** [comment]
@Nemixalone Could you look into that, please?

**Comment by doremidom** [comment]
I should add, I'm using the command line program on a mac, not the GUI.

**Comment by timgrossmann** [comment]
@doremidom Ahh good to know, thank you for the information! Well I'll look into it as well then...

**Comment by Mehnou** [comment]
Have you found the problem yet ? I'm using the GUI btw

**Comment by timgrossmann** [comment]
Well, I seriously have no idea why this happens (mostly) with the GUI. 
Couldn't get this error with the normal execution of the script and I'm not familiar enough with the GUI to solve his errors.

**Comment by komad1na** [comment]
I can check that out but my GUI is doing nothing else than generating python lines to execute(maybe bad formatting after InstaPy updates), I mean it has nothing with the background working of InstaPy. But sure I can see whats up. @sweb1 @Mehnou Can you please open up **quickstart.py** file and copy whole line with something like this and paste it here please. Thanks

**accs = ['therock','natgeo']
session.follow_by_list(accs, times=1)**

**Comment by doremidom** [comment]
I was able to fix this by removing sleep(10) at line 66, fyi

**Comment by Mehnou** [comment]
I removed it but it didn't work... It actually crashed sooner

**Comment by doremidom** [comment]
I'm not using the GUI, so my fix only works for the command line program

**Comment by Mehnou** [comment]
Well I think it's actually the same, the GUI just writes the code in the quickstart.py and executes it

**Comment by Mehnou** [comment]
@timgrossmann Any luck? If alot of people are having this problem then it probably has something to do InstaPy itself

**Comment by timgrossmann** [comment]
@Mehnou I'm running 4 accounts with this, never had that issue.

Could you please provide more informations about what system you are using, where you are located and so on...

**Comment by Mehnou** [comment]
I'm using Windows 7, python 2.7

**Comment by timgrossmann** [comment]
@Mehnou Try python3 like mentioned several times now.

**Comment by jedbanger** [comment]
I'm having this problem using Windows 7 from command line (not gui) with python 3.

**Comment by timgrossmann** [comment]
@jedbanger Could you try to find the post on which this happens, please?
Also post your quickstart file, please.

**Comment by jedbanger** [comment]
Sure tim (great proyect btw!) 

This my quickstart file, just erasing/replacing any kind of sensitive info.
```python
from instapy import InstaPy
import os
session = InstaPy(username= ****** pasword= *****)
session.login()
session.set_do_follow(enabled=True, percentage=25, times=1)
session.set_upper_follower_count(limit = 900)
session.set_lower_follower_count(limit = 50)
session.like_by_tags(['exampletag1', 'exampletag2'], amount=50, media='Photo')
array1 = ['lots', 'of different', 'usernames' ]
session.follow_by_list(array1, times=1)
session.unfollow_users(amount=30)
session.end()`
```

Tried modifying  `array1` to see whether if it was breaking when it encountered a private account, but i also saw the same error with public accounts.

**Comment by timgrossmann** [comment]
@jedbanger Did you miss the comma between username and password?

Could you try to do it with the chaining example? 
Like this:

```python
InstaPy(username='', password="") \
    .login() \
    .set_do_follow(enabled=True....)
    .
    .
    .
```

**Comment by jedbanger** [comment]
No, sorry, it was a typo when putting the ****. 
If i comment the `.follow_by_list` i got no problems with the script. I can run any other feature. Its just that one that gives me trouble.
just tried it with the chaining example. Same problem.

**Comment by timgrossmann** [comment]
@jedbanger Good to know the problem is with the `.follow_by_list`
Thank you this helps out a lot

**Comment by Mehnou** [comment]
@timgrossmann Nobody said it was only in following? My bad xD

**Comment by timgrossmann** [comment]
@Mehnou Ahh ok, good to know.

**Comment by omidedipidizi** [comment]
@timgrossmann so what we should do to solve the problem ?? i have the same problem when i enter a list of user to fallow !!

**Comment by omidedipidizi** [comment]
@doremidom in which file you made changes ?

**Comment by Mehnou** [comment]
@timgrossmann Hey tim, downloaded it again, now it just crashes immediately when you give it a list to follow, without even running..

**Comment by jedbanger** [comment]
Anyone managed to solve this?

**Comment by sweb1** [comment]
I have installed now latest Instapy version and run it from command line, still getting the error on first or second user (win 10, python 3.6).
@Nemixalone here is the quickstart.py content:

```python
accs = ['technik_tim','imtheonlycaptain','emilio.hasanov','serenacv96']
session.follow_by_list(accs, times=1)

**Comment by aReaSa** [comment]
I have installed now latest Instapy version and run it from command line, still getting the error on first running

**Comment by Mehnou** [comment]
Me too..

**Comment by komad1na** [comment]
@sweb1 Well the formatting from GUI is fine as i can see,but i get this error on first account with **command line**.

`--> technik_tim instagram account is opened...
Traceback (most recent call last):
  File "quickstart.py", line 6, in <module>
    session.follow_by_list(accs, times=1)
  File "C:\Users\Nemanja\Desktop\InstaPy-master\instapy\instapy.py", line 261, i
n follow_by_list
    followed += follow_given_user(self.browser, acc_to_follow, self.follow_restr
ict)
  File "C:\Users\Nemanja\Desktop\InstaPy-master\instapy\unfollow_util.py", line
149, in follow_given_user
    if follow_button.text == 'Follow':
  File "C:\Users\Nemanja\AppData\Local\Programs\Python\Python36\lib\site-package
s\selenium\webdriver\remote\webelement.py", line 73, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "C:\Users\Nemanja\AppData\Local\Programs\Python\Python36\lib\site-package
s\selenium\webdriver\remote\webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Nemanja\AppData\Local\Programs\Python\Python36\lib\site-package
s\selenium\webdriver\remote\webdriver.py", line 252, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Nemanja\AppData\Local\Programs\Python\Python36\lib\site-package
s\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale elemen
t reference: element is not attached to the page document
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5b
a8),platform=Windows NT 6.1.7601 SP1 x86_64)`

**Comment by sweb1** [comment]
@Nemixalone yes i get this error from command line and I would be happy to get it work from command line. GUI is not my priority

**Comment by timgrossmann** [comment]
@sweb1  @Mehnou  Could you guys try to change the `self.browser.implicitly_wait(25)` in the instapy.py file to more than 25 as it is right now and test again, please?

It's at line 103 in instapy/instapy.py

**Comment by snik123** [comment]
idk what y'all problem is but its working fine for me

**Comment by sweb1** [comment]
I tried with settings 50,100,1000. First run I got passed first entry and stopped at second entry. Consecutive runs all stopped at first entry.
@snik123 which software config do you have? (o/s, chromedriver, python...)

**Comment by komad1na** [comment]
@sweb1 I dont know how InstaPy is working (in background) I am here if GUI fucks up :smile:

**Comment by snik123** [comment]
@sweb1 windows 10 python 3.6.2 chromedriver 2.30.477700
```
from instapy import InstaPy
import os
session = InstaPy(username='#', password='#')
session.login()
session.unfollow_users(amount=10)
accs = ['nickelodeon', 'natgeo']
session.follow_by_list(accs, times=1)

session.end()
```

**Comment by pattymayo** [comment]
Mine started running fine after I turned off the follow by lists. Running GUI on Windows 10, Python 3.6. it's returning the same codes as above.
C:\InstaPy-master>quickstart.py
Logged in successfully!
--> rwnbyrawan instagram account is opened...
Traceback (most recent call last):
  File "C:\InstaPy-master\quickstart.py", line 7, in <module>
    session.follow_by_list(accs, times=1)
  File "C:\InstaPy-master\instapy\instapy.py", line 261, in follow_by_list
    followed += follow_given_user(self.browser, acc_to_follow, self.follow_restrict)
  File "C:\InstaPy-master\instapy\unfollow_util.py", line 149, in follow_given_user
    if follow_button.text == 'Follow':
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 73, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.15063 x86_64)

Quickstart below minus username/pass

from instapy import InstaPy
import os
session = InstaPy(username='###', password='###')
session.login()
session.set_do_follow(enabled=True, percentage=10, times=1)
session.like_by_tags(['denim', ' jeans', ' denimjacket', ' minimal', ' letsgosomewhere', ' pursuitpretty', 'whatiwore', ' strongcurves'], amount=50, media='Photo')

session.end()

**Comment by scheichi** [comment]
for me the same issue as for @sweb1 , but when i delete the line with `follow_by_list()`the bot is working!
running it with docker-compose on mac os

**Comment by lameei** [comment]
I can confirm that this is happening with private accounts. Any kind of solutions?

**Comment by KellyDelaCruz** [comment]
In my case Im getting this error with these following scenario:
1. Successful requests
2. Selecting a Xpath using find_elements_by_xpath (so it will return list element or empty [])
3. By using the same driver Im clicking a button then it will reload the list
4. HERE IS WHERE MY PROBLEM COMES along, when I manipulate the list from scenarion #2,
   since that list of element is not present anymore. then the selenium raises a StaleElementReferenceException.
*****my solution for this is to process the first before clicking a button(or rendering the page)**

**Comment by Nisthar** [comment]
@timgrossmann Is it fixed? I am still getting the same error.

**Comment by axd7832** [comment]
it seems to be random. I ran it once and it crashed, ran it again with the same settings and it was fine. Maybe it depends on the actual site?

**Comment by yoann9344** [comment]
I had this problem on this script : 
```python
browser.click_link_by_id('loginButton')
# sleep(5)
for iframe in browser.find_by_tag('iframe'):
    print(iframe['class'])
browser.quit()
```
That I solved by adding a print : 
```python
browser.click_link_by_id('loginButton')
# sleep(5)
for iframe in browser.find_by_tag('iframe'):
    print(iframe['class'])
print()
browser.quit()
```
Seems to be a buffer issue ! It could be the reason on random raising.
