### ISSUE TITLE
Image commenting & Clarafai

### ISSUE THREAD

**Issue by JoeFertig** [InstaPy/InstaPy#3360]
## Expected Behavior
1. Get all images with hashtag "movember"
2. Use Clarifai to check if images are "movember"-related
3. Like the picture
4. Comment the picture & follow the user

## Current Behavior
Clarifai is not working:
 Image check error: Failed to parse models field: Failed to parse model_version field: Message type "clarifai.api.ModelVersion" has no field named "train_stats".
 Available Fields(except extensions): [<google.protobuf.descriptor.FieldDescriptor object at 0x75a10190>, <google.protobuf.descriptor.FieldDescriptor object at 0x75a101b0>, <google.protobuf.descriptor.FieldDescriptor object at 0x75a101f0>, <google.protobuf.descriptor.FieldDescriptor object at 0x75a10230>, <google.protobuf.descriptor.FieldDescriptor object at 0x75a10250>, <google.protobuf.descriptor.FieldDescriptor object at 0x75a10290>, <google.protobuf.descriptor.FieldDescriptor object at 0x75a102b0>]
Image check error: 'NoneType' object is not iterable

## Additional Questions

How do I set the comments?
a: 
session.set_do_comment(True, percentage=100)
session.set_comments([u"Thank you!"])

OR

b:
session.clarifai_check_img_for(['movember',], comment=True, comments=[u"Thank you!"])

Do I need this for commenting: 
session.set_user_interact(amount=1, percentage=100, media='Photo')?

## Possible Solution (optional)

Is it possible to develope a function that just looks out for images with a specific hashtag and then put a comment on that pic without liking it?

## InstaPy configuration

Running on a RaspPi 3b+ 

""" Quickstart script for InstaPy usage """
```
import os
import schedule
import time
from instapy import InstaPy
from tempfile import gettempdir
from instapy.util import smart_run

insta_username = ''
insta_password = ''

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)


with smart_run(session):
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=-1.1,
				  delimit_by_numbers=True,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)
    
    session.set_dont_include(['User1'])
    session.set_do_follow(enabled=True, percentage=100, times=1)
    session.set_do_comment(True, percentage=100)
    session.set_delimit_commenting(enabled=True, comments_mandatory_words=['movember'])  
    session.set_user_interact(amount=1, percentage=100, media='Photo')
    session.set_comments([
                u"Thank you for participating the #movember movement! :pray: :thumbsup: :pray:",
                u"Thank's for your support :pray: :thumbsup: ! #movember2018 #moustache",
                u"Thank you! Because you care! :pray: :thumbsup: ! #movember  #movemberfoundation"])
    session.set_use_clarifai(enabled=True, api_key='XXX', full_match=True)
    session.set_quota_supervisor(enabled=True, peak_server_calls=(590, None), sleep_after=["server_calls_h"], sleepyhead=True, stochastic_flow=True)
    session.clarifai_check_img_for(['movember',], comment=True, comments=[
                u"Thank you for participating the #movember movement! :pray: :thumbsup: :pray:",
                u"Thank's for your support :pray: :thumbsup: ! #movember2018 #moustache",
                u"Thank you! Because you care! :pray: :thumbsup: ! #movember  #movemberfoundation"])
    

    session.like_by_tags(['movember'], amount=387, interact=True)
```

**Comment by GOliveira10** [comment]
Also having this problem

**Comment by GOliveira10** [comment]
Resolved by updating all of my packages. Run this:

`pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U`

**Comment by JoeFertig** [comment]
Thanks!
I runned the code and it took quite a while with some installations and updates. Some programs raised some errors (I listed two of them below). So I executed the code again with sudo su and it installed most of the stuff. Now I have to run and test if there are any changes :)


## Error

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main


## Another Error

creating build/temp.linux-armv7l-2.7/c
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Ub3vap/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-armv7l-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: Datei oder Verzeichnis nicht gefunden
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hQBLx6/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k6AMEN-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-hQBLx6/cffi/

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
