### ISSUE TITLE
InstaPy Dashboard (announcement)

### ISSUE THREAD

**Issue by converge** [InstaPy/InstaPy#3365]
hey guys, just provided an initial InstaPy Dashboard tool

https://github.com/converge/instapy-dashboard

**Comment by uluQulu** [comment]
Very nice idea 👏🏼

**Comment by imkimchi** [comment]
wow this is definitely gonna help me a lot. really appreciate for your work

**Comment by timgrossmann** [comment]
@converge Awesome!
Could you PR a link to this repo in the README of InstaPy, please?

Maybe it makes sense to give it another name though... It sounds like a general dashboard for several features. 
It's more like an activity/database explorer, isn't it?

**Comment by converge** [comment]
@timgrossmann thanks Tim !!
Just want to improve the documentation a little before PR. I want to test it on Windows also, sounds like ppl are having some issues to install it on Windows.

The initial idea is to scale it to be a general dashboard, next I'm thinking about adding a screen to watch logs.

**Comment by lucascaldax** [comment]
Very good work @converge !

**Comment by nummell** [comment]
Awsome!

Using it ;)

**Comment by converge** [comment]
preparing an update for the next week..

**Comment by Tkd-Alex** [comment]
I hope I can help asap

**Comment by converge** [comment]
@Tkd-Alex youre super welcome!

**Comment by converge** [comment]
new release (added live log feature): https://github.com/converge/instapy-dashboard
need test it on Windows, and I think it's ready to add to InstaPy readme.md
