### ISSUE TITLE
UnicodeDecodeError help

### ISSUE THREAD

**Issue by Fellowes52** [InstaPy/InstaPy#3366]
This seems to be a constant problem with the code ever since Instagram allowed Emoji's into their hashtags. The script always runs into an emjoi at some point, causing it to crash and not run until re-started again.

I have trawled Google and this forum looking for an answer to this. I did see a response from, Tim:

**"The issue is bound to your terminal output and the standard decoding that is set (seems like Ascii).
If you change the decoding, it should work."**

Although how do you change the decoding so this issue doesn't keeping cropping up? I have spent hours trying to find a solution but to no avail. Can someone please help with a hopeful easy-ish solution, if there is one!

I am running InstaPy on Raspberry Pi 3.

**Comment by turtlebking** [comment]
I am running InstaPy on Raspberry Pi 3+ and i have the same problem with utf8 code in hashtags.
i checked my raspbian is running with utf8 locale but still can't fix the problem.

**Comment by Fellowes52** [comment]
Hi @csvchou hopefully this will work for you, as all being well it has for me, so far!

1. Open the terminal in Raspberry Pi
2. pi@raspberrypi:~ $ locale
3. pi@raspberrypi:~ $ sudo dpkg-reconfigure locales
4. pi@raspberrypi:~ $ LANG=en_XX.UTF8 python

In step 2 locate the country you're in, this must also match the country you have the Raspberry Pi set too. 

One you have taken your countries code, In step 3 replace the XX with your countries code (I am in the UK so I will use GB). So mine would read **LANG=en_GB.UTF8 python**

One that's done, run, pi@raspberrypi:~ $ reboot.

Run Instapy and see if it runs into anymore problems.

PS. No harm in also running, sudo apt-get update and sudo apt-get dist-upgrade, to update the Pi. Of course a reboot would do no harm after this too.
