### ISSUE TITLE
Wrong login data, no issue find

### ISSUE THREAD

**Issue by AntoineIN** [InstaPy/InstaPy#3372]
Hello guys, i got this message when i try to launch my script :

Issue with cookie for user jewellene.shop. Creating new cookie...

..............................................................
CRITICAL [2018-11-14 22:12:20] [jewellene.shop]  Wrong login data!
CRITICAL:jewellene.shop:Wrong login data!

I know this topic have already been discute, but i didn't find an answer that i understand clearly, so can someone help me on this problem ?
I hear that i need to copy paste the cookie from instagram, but where do i paste it ?

Thanks...

**Comment by C4T4** [comment]
sounds like a an unusual login attempt problem.
[Add `bypass_suspicious_attempt=True` to InstaPy()](https://github.com/timgrossmann/InstaPy#bypass-suspicious-login-attempt)

**Comment by VNRARA** [comment]
I changed my password and this happened... Already tried the fix, but it didn't work.

EDIT: Just delete the cookie files and lists and other stuff from logs/'username'

**Comment by david-vendel** [comment]
Yes, you need to delete cookies.

**Comment by CamiloB** [comment]
did you solve this?

**Comment by AntoineIN** [comment]
Yes, deleting cookies files make it work again !

Thanks everyone !

**Comment by beeny10** [comment]
Where can I delete cookies file ?

**Comment by david-vendel** [comment]
They are saved in log folder

**Comment by beeny10** [comment]
I did that and again it didn't worked for me it justs refreshed the instagram page ,so what I did was to go and run the script in another computer then copying the cookie file from it .
