### ISSUE TITLE
Is it possible to filter out the gender I “like” or “follow”?

### ISSUE THREAD

**Issue by jamezun** [InstaPy/InstaPy#3380]
Is it possible to filter out the gender I “like” or “follow”?

**Comment by converge** [comment]
it's with deep learning, and Instagram API, but we dont have it actually.

**Comment by jamezun** [comment]
it might be a good idea to add this function in the future perhaps:-P

**Comment by converge** [comment]
you're super welcome to contribute to the project :)
Im closing it, reopen it if you need
