### ISSUE TITLE
Feature Request - chrome alternative

### ISSUE THREAD

**Issue by Areahints** [InstaPy/InstaPy#3387]
Hello everyone, been a while, so I stopped using Instapy so I could tinker some other stuff, I found a way to install Linux (Debian Jessie) on a rooted phone. trying to install instapy keeps failing because i cant get chrome or chromium on the phone, this is a selfish request but isn't there a way to make instaPy work without a browser? or at least a browser i could install on my OS?

**Comment by converge** [comment]
@Areahints that's sounds great! Try firefox (use_firefox=True)

**Comment by Areahints** [comment]
@converge thanks for the suggestion, but I just ran into another problem trying to install firefox on my phone, apparently Firefox doesn't have an armhf package so I am looking for that now!

**Comment by converge** [comment]
@Areahints did you downloaded it directly from FF website or using apt ?

**Comment by Areahints** [comment]
i used apt

**Comment by converge** [comment]
@Areahints for this I would download it, and try to install the missing libs by hand

**Comment by Areahints** [comment]
I used a method on this [link](https://raspberrypi.stackexchange.com/a/51633) to install both chromium and chromedriver, @converge  if you don't mind troubleshooting with me, i have a new issue with my whole OS now and i enumerated that on [Unix](https://unix.stackexchange.com/questions/482946/issues-with-apt-and-aptitude-on-debian-jessie-chroot-environment) but at least ive learned that i can use raspberrry sources to install chrome and chromedriver.

**Comment by converge** [comment]
sorry mate, Im quite busy. But I can give you advices, Im on our discord channel also.
