### ISSUE TITLE
Randomizing Comments

### ISSUE THREAD

**Issue by jamezun** [InstaPy/InstaPy#3392]
## Expected Behavior
The comment shall be randomly chosen within my list.

## Current Behavior
It always gives the same comment.

## InstaPy configuration

I am trying to randomize my comment by using the random choice function by importing random, but it always give the same result (e.g. goood), it appears that once the random comment was chosen, it applied to all forth coming commenting until the sessions end, how can I fix it?

`#session.set_comments([random.choice(['niceeee','goood','wowwww','coooool','ooooo!','wahhhh'])])`

**Comment by LotusPainter** [comment]
try this:
```

import random

comments = [ 'comment1', 'comment2', 'comment3']

random.shuffle(comments)
my_comments = comments[:3]

session.set_comments(my_comments)
```

You can change the number 3 in `my_comments = comments[:3]` to any number so long as you have that number of comments in the list. It will choose randomly that number of comments out of the comment list. Useful if some runs where you don't want to make use of every comment.

Edit: also not sure if it's intentional but you've put a # in front of that so it's commented out

**Comment by jamezun** [comment]
I mistyped the #,  anyway, let say I want to interact with 100 people with the same hashtag, and let say it randomly chooses comment2 in your sample, it will interact with them using comment2 in the 100 people right? How can I leave comment in a random manner within the 100 people?

**Comment by LotusPainter** [comment]
No it will shuffle all the comments, so for the first post it might do comment2, then next post comment3, then comment1.

Test it out if you aren't sure and check the log

**Comment by jamezun** [comment]
@LotusPainter 
Thanks! It seems working! But what if I want to make it more advance, lets say a comment  consists for three parts which have its own lists of words, how should I modify the code you wrote in order to combine into a full sentence such that for each comment it will randomly pick a word in the first_part list of comments, pick a word in the second_part list, and third_part list?

e.g 
first_part = ['this is','that is','it is']
second_part = ['really','quite','very']
third_part = ['good','nice','awesome']

**Comment by LotusPainter** [comment]
@jamezun Don't think you can, since once `session.set_comments` is active, it never calls back to the previous code as far as I know. It's better just to write every combination of comments you can. It's time consuming, but having 20-30+ comments all written out would help a lot
