### ISSUE TITLE
Instagram is onto us?

### ISSUE THREAD

**Issue by punkhop** [InstaPy/InstaPy#3394]
Wondering if InstaPy can get around this new Like-Blocking that IG is implementing.

https://www.theverge.com/2018/11/19/18098834/instagram-will-remove-fake-likes-and-follows

**Comment by yeyou4760** [comment]
no this is a message you'll get if your using a APP that is offered on app store or Google play.. there's no way to figure out PY is running unless your liking to fast or just doing things over the max allowed the you'll most likely get showdown banned and at that point is most likely because your likes and comments look like spammy to instagram because your doing this all wrong

**Comment by sionking** [comment]
> no this is a message you'll get if your using a APP that is offered on app store or Google play.. there's no way to figure out PY is running unless your liking to fast or just doing things over the max allowed the you'll most likely get showdown banned and at that point is most likely because your likes and comments look like spammy to instagram because your doing this all wrong

Bullshit.
IG know everything, they just like the traffic.
Go ahead and try to bot in FB, you can't.

**Comment by timgrossmann** [comment]
@sionking I totally agree with you. They need(ed) the traffic and engagement that bots brought to IG.
Without people using bots, the platform wouldn't be as popular as it is.

I'm really curious to see what happens once they "enable" this counter measurements. Fake comments are absolutely annoying, I agree to that. Let's see if they go all the way and remove anything that is received by "artificially" boosting your account.

Really wondering if they'll also cover the services that do this kind of engagement "by hand" 🤔

**Comment by ghost** [comment]
this is the complete instagram post 👍 

https://instagram-press.com/blog/2018/11/19/reducing-inauthentic-activity-on-instagram/?fbclid=IwAR2_bxYtEkLNbDsdNlimuhfOi9-H-8zEljT5nJ23c21QOvGrXaywINSci6E

**Comment by w4ngel** [comment]
> @sionking I totally agree with you. They need(ed) the traffic and engagement that bots brought to IG.
> Without people using bots, the platform wouldn't be as popular as it is.
> 
> I'm really curious to see what happens once they "enable" this counter measurements. Fake comments are absolutely annoying, I agree to that. Let's see if they go all the way and remove anything that is received by "artificially" boosting your account.
> 
> Really wondering if they'll also cover the services that do this kind of engagement "by hand" 🤔

I believe they will be targetting more spam like services, ones that have generic commenting, auto-replies etc. I also wonder how quickly their tools will be to adapt. They already have detection in place if you go over limits. So I presume these will just be looking for patterns.

**Comment by sionking** [comment]
Spam-my comments and fake accounts are the target not real B try to promote in IG since this brings all Business to their platform == Business  is  money

**Comment by tiaringhio** [comment]
First of all thank you for the amazing job you've done with this projects!
Do yuo guys think we have to worry?
Oh and since you've mentioned a 'max' of likes, follows and comments, do you mind sharing what those numbers are?
Thank you

**Comment by nadavdrukker** [comment]
I totally agree that if IG wanted to shut us down, they'll already do it. They know who we are... 
I'm still a bit worried, because:
1. They do loose some money due to engagebots. Many people who would otherwise promote themselves by paying IG are doing what we do.
2. IG introduced more and more links to "suggested" users and content everywhere around the app, so that they may think they don't need us to generate traffic - they'd rather do the botgagement themeselves in a way that maximizes their profits. They'll have to gauge it carefully, because they don't want users to get upset at their spam, better that they get upset at us.

But nothing to do other than wait and see, and check here if anybody gets blocked. I assume that they will introduce the breaks slowly to not stop all activity on IG at once. Hopefully we'll remain beneficial to MZ.

**Comment by sionking** [comment]
I think business will run away from IG to a different platform that supply them with the engagment thay want. IG became number 1 platform for business, and for that specific reason, if they will close botting, we can say #byebyeig

**Comment by edobranchi** [comment]
Maybe a coincidence but I've been "like blocked" for a day today without changing any setting in instapy for the past month.
Something is happening.

**Comment by w4ngel** [comment]
> Maybe a coincidence but I've been "like blocked" for a day today without changing any setting in instapy for the past month.
> Something is happening.

What settings did you have it on? They may have adjusted the limits along with the new restrictions they have put in place. If you go on the mobile app does it give any warning message like the one displayed in their blog post?

**Comment by edobranchi** [comment]
> > Maybe a coincidence but I've been "like blocked" for a day today without changing any setting in instapy for the past month.
> > Something is happening.
> 
> What settings did you have it on? They may have adjusted the limits along with the new restrictions they have put in place. If you go on the mobile app does it give any warning message like the one displayed in their blog post?

I have randomized intervals from 160 to 300 likes per session splitted on 4 hashtags, it worked fine until today for the past month.

Now i'm reducing it and BTW I have a similar follow routine but i'm not "follow Blocked"

If someone is intrested I can post my instapy.py setup. 

And no, no warning at all, only a pop-up that say i'm not allowed to like photos till 21/11/18 or 18/11/21

**Comment by w4ngel** [comment]
How many sessions do you run per day?

**Comment by edobranchi** [comment]
> How many sessions do you run per day? On 21 Nov 2018, at 12:02, Edoardo Branchi 

Just one, but lately I noticed that, without changing setup, that my Profile visits skyrocketed from 600 in a week to 1200 without posting. I can't figure out what's happening.

**Comment by Joyen12** [comment]
Yes I think the same, bot is making it growing, they like it.
Why you said on Facebook not possible ?
You can also use bot on FB but just not as much as IG.
So for sure they have different strategy.


Envoyé de mon iPhone

**Comment by w4ngel** [comment]
> > How many sessions do you run per day? On 21 Nov 2018, at 12:02, Edoardo Branchi
> 
> Just one, but lately I noticed that, without changing setup, that my Profile visits skyrocketed from 600 in a week to 1200 without posting. I can't figure out what's happening.

It would be interesting to see your setup.



> Yes I think the same, bot is making it growing, they like it. Why you said on Facebook not possible ? You can also use bot on FB but just not as much as IG. So for sure they have different strategy. Envoyé de mon iPhone
> […](#)
> Le 20 nov. 2018 à 07:19, sionking ***@***.***> a écrit : no this is a message you'll get if your using a APP that is offered on app store or Google play.. there's no way to figure out PY is running unless your liking to fast or just doing things over the max allowed the you'll most likely get showdown banned and at that point is most likely because your likes and comments look like spammy to instagram because your doing this all wrong Bullshit. IG know everything, they just like the traffic. Go ahead and try to bot in FB, you can't. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

A lot of it is because FB has a less direct way of businesses interacting with users. A business can't directly message or interact with a user unless the user interacts with them first.

**Comment by sionking** [comment]
> A lot of it is because FB has a less direct way of businesses interacting with users. A business can't directly message or interact with a user unless the user interacts with them first.

A man/woman that is not a business account but sell some service is what we have in FB.

**Comment by uluQulu** [comment]
@tiaringhio 
>..since you've mentioned a 'max' of likes, follows and comments, do you mind sharing what those numbers are?

Note that, each unique account has its individual limits per its age, activity, health, engagement, etc.
But, generally [for follow/unfollow & like], avoid actions over 60/hour and 600/day if you wanna go totally safe.

---

Cheers 🤑
---

**Comment by yeyou4760** [comment]
well if you closely on your app from a mobile phone it tells you how long your where using the device each day so its obvious that there looking to change something or counter target users that are not using mobile devices??

**Comment by Lando-L** [comment]
> Maybe a coincidence but I've been "like blocked" for a day today without changing any setting in instapy for the past month.
> Something is happening.

I ran into a similar problem and it is still not liking for three days in a row. Was it only a temporarly block? I haven't received any message in the app, and the bot is still running, saying I am apparently still liking images. Have you solved it yet?

**Comment by arcasoy** [comment]
^also have image liking block which is not there when I go to like images on my mobile device but is blocked for EVERY image InstaPy trys to like on my RPi 3
