### ISSUE TITLE
blocked by CORS policy

### ISSUE THREAD

**Issue by KingKorSin** [InstaPy/InstaPy#3396]
## Expected Behavior
Not having any errors in my log

## Current Behavior
The following error is in the log from the moment I start running the bot:
"Access to XMLHttpRequest at 'https://graph.instagram.com/logging_client_events' from origin 'https://www.instagram.com' has been blocked by CORS policy"

## Possible Solution (optional)
Not sure yet.

**Comment by converge** [comment]
![img](https://cdn.discordapp.com/attachments/510385886869979138/514429038211629056/Captura_de_Tela_2018-11-20_as_11.16.51.png)
