### ISSUE TITLE
interacting by user and url

### ISSUE THREAD

**Issue by aliabdulrab7** [InstaPy/InstaPy#3398]
## Expected Behavior
This is what i want to run on my shell
 `session.follow_likers (['hudabeauty' , 'toyartistry'], photos_grab_amount = 5, follow_likers_per_photo = 10, randomize=True, sleep_delay=600, interact=False)
` 
but i get an error 👇

## Current Behavior
<img width="1277" alt="screen shot 2018-11-20 at 7 21 04 pm" src="https://user-images.githubusercontent.com/42283405/48787282-8b20e200-ecf9-11e8-944d-03ab74d98b51.png">

Exception has occurred: urllib3.exceptions.MaxRetryError
HTTPConnectionPool(host='127.0.0.1', port=56749): Max retries exceeded with url: /session/6feed12b23463ffedad2289bc70f93ef/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1088f8a20>: Failed to establish a new connection: [Errno 61] Connection refused'))
  File "/Users/bnderyafai/Desktop/InstaPy/instapy/util.py", line 1263, in get_current_url
    current_url = None
  File "/Users/bnderyafai/Desktop/InstaPy/instapy/util.py", line 812, in web_address_navigator
    current_url = get_current_url(browser)
  File "/Users/bnderyafai/Desktop/InstaPy/instapy/commenters_util.py", line 358, in get_photo_urls_from_profile
    web_address_navigator(browser,'https://www.instagram.com/' + username +'/')
  File "/Users/bnderyafai/Desktop/InstaPy/instapy/instapy.py", line 861, in follow_likers
    photo_urls = get_photo_urls_from_profile(self.browser, username, photos_grab_amount, randomize)
  File "/Users/bnderyafai/Desktop/InstaPy/quickstart.py", line 26, in <module>
    session.follow_likers (['hudabeauty' , 'toyartistry'], photos_grab_amount = 5, follow_likers_per_photo = 10, randomize=True, sleep_delay=600, interact=False)

**Comment by JoeFertig** [comment]
Sorry to be OT but what Editor/Environment are you using?

**Comment by aliabdulrab7** [comment]
> Sorry to be OT but what Editor/Environment are you using?

VS code
