### ISSUE TITLE
After login successful - Ends

### ISSUE THREAD

**Issue by kille250** [InstaPy/InstaPy#340]
After the Console is giving me the output Login successful, the script ends. No Errors given.

**Comment by Kille250** [comment]
This is the script that i try out, from you. xd

`from random import randint
from random import sample
from time import sleep
from instapy import InstaPy

tag_list = ['fitness','sexy','gym','fit','love','fitfam',
            'motivation','workout','squats','hot','bodybuilding',
            'abs','fitspo','beautiful','ass','model','follow',
            'girl','bikini','body','legs','squats','girlswholift',
            'healthy','followme','glutes','training','cute','curves',
            'beauty']

like_tag_list = ['fitness','sexy','gym','fit','love','fitfam',
            'motivation','workout','squats','hot','bodybuilding',
            'abs','fitspo','beautiful','ass','model','follow',
            'girl','bikini','body','legs','squats','girlswholift',
            'healthy','followme','glutes','training','cute','curves',
            'beauty']

ignore_list = ['vegan', 'veggie', 'plantbased']

followed = 0

with open('./logs/followed.txt', 'r') as followFile:
  followed = int(followFile.read())

def startScript():
  tag1 = randint(200, 300)
  tag2 = randint(50, 350 - tag1)
  tag3 = 450 - tag1 - tag2

  InstaPy(username='bdyperfection', password='Dioderboss21051999')\
    .login()\
    .set_dont_like(tag_list)\
    .set_ignore_if_contains(ignore_list)\
    .set_do_comment(enabled=True, percentage=5)\
    .set_do_follow(enabled=True, percentage=10, times=1)\
    .set_comments('Love it', '<3', 'so beautiful')\
    .unfollow_users(amount=randint(followed, followed * 1.5))\
    .like_by_tags(['body'], amount=tag1)\
    .like_by_tags(sample(like_tag_list, 1), amount=tag2)\
    .like_by_tags(sample(like_tag_list, 1), amount=tag3)\
    .end()

runFile = open('./logs/run.txt', 'a')

if randint(0,10) < 9:
  try:
    runFile.write('started\n')
    runFile.close()
    sleep(randint(0, 60 * 10))
    startScript()
  except Exception as err:
    with open('../erros.log', 'a') as errLog:
      errLog.write(str(err) + '\n')

else:
  runFile.write('not started\n')
  runFile.close()`

**Comment by kille250** [comment]
This is the script that i try out, from you. 

```python
from random import randint
from random import sample
from time import sleep
from instapy import InstaPy

tag_list = ['fitness','sexy','gym','fit','love','fitfam',
            'motivation','workout','squats','hot','bodybuilding',
            'abs','fitspo','beautiful','ass','model','follow',
            'girl','bikini','body','legs','squats','girlswholift',
            'healthy','followme','glutes','training','cute','curves',
            'beauty']

like_tag_list = ['fitness','sexy','gym','fit','love','fitfam',
            'motivation','workout','squats','hot','bodybuilding',
            'abs','fitspo','beautiful','ass','model','follow',
            'girl','bikini','body','legs','squats','girlswholift',
            'healthy','followme','glutes','training','cute','curves',
            'beauty']

ignore_list = ['vegan', 'veggie', 'plantbased']

followed = 0

with open('./logs/followed.txt', 'r') as followFile:
  followed = int(followFile.read())

def startScript():
  tag1 = randint(200, 300)
  tag2 = randint(50, 350 - tag1)
  tag3 = 450 - tag1 - tag2

  InstaPy(username='username', password='Password')\
    .login()\
    .set_dont_like(tag_list)\
    .set_ignore_if_contains(ignore_list)\
    .set_do_comment(enabled=True, percentage=5)\
    .set_do_follow(enabled=True, percentage=10, times=1)\
    .set_comments('Love it', '<3', 'so beautiful')\
    .unfollow_users(amount=randint(followed, followed * 1.5))\
    .like_by_tags(['body'], amount=tag1)\
    .like_by_tags(sample(like_tag_list, 1), amount=tag2)\
    .like_by_tags(sample(like_tag_list, 1), amount=tag3)\
    .end()

runFile = open('./logs/run.txt', 'a')

if randint(0,10) < 9:
  try:
    runFile.write('started\n')
    runFile.close()
    sleep(randint(0, 60 * 10))
    startScript()
  except Exception as err:
    with open('../erros.log', 'a') as errLog:
      errLog.write(str(err) + '\n')

else:
  runFile.write('not started\n')
  runFile.close()

**Comment by timgrossmann** [comment]
@Kille250 Please don't simply copy and ignore what it says.

The errors are written into the file located at `../errors.log`. 
Could you post the content of this file here, please?

**Comment by timgrossmann** [comment]
@Kille250 Please don't simply copy and ignore what it says.

The errors are written into the file located at `../errors.log`. 
Could you post the content of this file here, please?
