### ISSUE TITLE
Feature Request: don't unfollow from a custom list

### ISSUE THREAD

**Issue by anitato** [InstaPy/InstaPy#3401]
Right now you can unfollow from a custom_list, but you can't do the opposite, where you *don't* unfollow from a custom list. The only "don't unfollow" scenario is `session.set_dont_unfollow_active_users()`

For example, maybe I would like to be able to unfollow all except for a custom list of users whom I interact with frequently (or always want in my feed).

Something like:
`
custom_dont_unfollow_list = ["user_1", "user_2", "user_49", "user332", "user50921", "user_n"]
session.unfollow_users(amount=40, allFollowing=True, style="LIFO", unfollow_after=3*60*60, sleep_delay=450)
`

Hopefully that makes sense!

**Comment by thejeromelouis** [comment]
I'm looking for the same feature! This would be great...
