### ISSUE TITLE
Image check error: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by bongo48** [InstaPy/InstaPy#3402]
## Expected Behavior

Clarifai checks all the pictures without an error. It's weird because it's working for first interactions let's say 10-20 and after this error comes up.

## Current Behavior
ERROR [2018-11-20 11:36:52] [xxxxx]  Image check error: 'NoneType' object has no attribute 'endswith'
ERROR [2018-11-20 11:36:52] [xxxxx]  Image check error: cannot unpack non-iterable NoneType object
INFO [2018-11-20 11:36:57] [xxxxxx]  --> Commented: b''
INFO [2018-11-20 11:36:59] [xxxxxx]  --> Not following
INFO [2018-11-20 11:37:00] [xxxxxxx]  Finished interacting on total of 1 images from 1 users! xD

## InstaPy configuration
import os
import time
from tempfile import gettempdir
from selenium.common.exceptions import NoSuchElementException
from instapy import InstaPy
session = InstaPy(username=insta_username,
password=insta_password,
headless_browser=False,
multi_logs=False)
try:
session.login()
##### clarifai api
session.set_use_clarifai(enabled = True, api_key = 'xxxxxxxxxxxxxxxxxxx')

session.unfollow_users(amount=1500, nonFollowers=True, style="RANDOM", unfollow_after=15*60*60, sleep_delay=600)        
session.set_relationship_bounds(enabled=True,
                 potency_ratio=-1.05,
                  delimit_by_numbers=True,
                   max_followers=30000,
                    max_following=7000,
                     min_followers=35,
                       min_following=77)
session.set_do_follow(enabled=True, percentage=90)
session.set_user_interact(amount=1, randomize=True, percentage=90, media='Photo')
session.set_do_comment(enabled=True, percentage=100)
session.set_comments([''])
session.set_delimit_commenting(enabled=True, max=32, min=2)
session.set_do_like(enabled=True, percentage=90)
session.clarifai_check_img_for (['nsfw', 'people', 'text', 'graphic design', 'pet', 'animal', 'food', 'women', 'low-quality', 'words', 'logo', 'fashion', 'child', 'baby', 'man', 'girl'])
session.clarifai_check_img_for (['landscape', 'travel', 'sunset', 'ocean', 'nature', 'road', 'sky', 'sun', 'beach'], comment=True, comments=[u'Wow! :ok_hand:'])

###### unfollow
session.unfollow_users(amount=1500, nonFollowers=True, style="RANDOM", unfollow_after=15*60*60, sleep_delay=600)   	

users_to_follow1 = session.grab_followers(username="xxxxxxxxxx", amount=300, live_match=True, store_locally=True)    
session.follow_by_list(users_to_follow1[:250], times=1, sleep_delay=100, interact=True)

 I have Python 3.7.1 works on Windows 10 x64. Pip packages below:

beautifulsoup4 4.6.3
certifi 2018.10.15
chardet 3.0.4
clarifai 2.4.1
Click 7.0
configparser 3.5.0
easyprocess 0.2.3
emoji 0.5.1
future 0.17.1
gitdb2 2.0.5
gitpython 2.1.11
google-cloud 0.34.0
googleapis-common-protos 1.5.5
grep 0.3.2
grpcio 1.16.0
idna 2.7
instagram-py 0.0.1
jsonschema 2.6.0
packaging 18.0
pillow 5.3.0
pip 18.1
pip-review 1.0
pip-tools 3.1.0
plyer 1.3.1
protobuf 3.6.1
pyparsing 2.3.0
pyvirtualdisplay 0.2.1
requests 2.20.1
selenium 3.141.0
setuptools 39.0.1
six 1.11.0
smmap2 2.0.5
urllib3 1.24.1
wheel 0.32.2

**Comment by bongo48** [comment]
@timgrossmann @uluQulu have you seen this before? It's random... sometimes it works for 500 follows and it's checking the content of pictures. Sometimes it stops after 5 follows. I can't find any pattern.

**Comment by sammylandstrom** [comment]
A bit new to python and debugging it so not sure I follow the whole process/flow, but seems to be something with the function get_source_link not always getting a match / getting the photo URL. Hence returning a None that breaks the code.

Also wouldn't it be good for the check_image to "return False, [], []" when exceptions above occur so that the default comments are not applied. Now I see cases when the bug happens and some sort of default comments are written.

After playing around a bit it seems to be a timing issue. Something that seemed to fix the issue from happening for me is adding something like to the get_source_link funktion
browser.implicitly_wait(15)
