### ISSUE TITLE
Is it possible to Follow by Location or Interact User by Location 

### ISSUE THREAD

**Issue by jamezun** [InstaPy/InstaPy#3406]
## Expected Behavior
Interact with user in a chosen location
## Current Behavior
Seems that follow by location is not possible 
## InstaPy configuration
Hello, I was wondering is there I way I could interact with the user in a chosen location? I have looked into like by location but it seems that the function does not come with an interact parameter, so I suppose we cannot interact with use by using that function? Plus I would like to know is it possible to set a percentage that I will like the person when I am using the like by location?

Because what I want to achieve is to like, follow and comment a person in a chosen location. I can still achieve comment by location, but I cannot find follow by location nor interaction parameter within the functions, any idea?

Thanks for your time!

**Comment by converge** [comment]
https://github.com/timgrossmann/InstaPy#like-by-locations
