### ISSUE TITLE
run on windows server error: [None]  Heeh! Error occurred while getting a DB profile for 'None' 

### ISSUE THREAD

**Issue by aghili371** [InstaPy/InstaPy#3407]
i run the application on Windows 10 on my local system it works fine. but i tried to run on windows server. I got this error:
[None]  Heeh! An error occurred while getting a DB profile for 'None'

**Comment by aghili371** [comment]
it works now just set 
 headless_browser=True
thank you

**Comment by gitpatrickhub** [comment]
@aghili371 I'm getting the same error on Raspberry Pi 3 new install. I tried the headless_browser=True, but the issue still persists. Can you share your quickstart.py file or other config info?
