### ISSUE TITLE
anybody got only "comment" blocked?

### ISSUE THREAD

**Issue by imkimchi** [InstaPy/InstaPy#3409]
liking a post actually works but when I comment with instapy, It doesn't show up to others but I can only see the comment. 

anybody had a similar experience?

**Comment by JoeFertig** [comment]
Do you have the @username and/or hashtags in the comment?

**Comment by imkimchi** [comment]
@JoeFertig No, nothing special in the comments. I have a emoji in the comments but I don't think that would be a issue.

**Comment by JoeFertig** [comment]
I ask because I had the same problem but only with comments with user mention and using hashtags. Think it is super easy for IG to check if you repeat to use the same comment.

**Comment by imkimchi** [comment]
@JoeFertig I have 4 different comments but still got blocked and even the new one didn't even show up so It's kindaaa weird!

**Comment by JoeFertig** [comment]
did you test it by doing the same comment with the IG app?

**Comment by imkimchi** [comment]
@JoeFertig Yeah, I tried it on IG app with different network and it worked. so I assumed I got ip banned for comments and tried Instapy with different ip but still not working. Are you having the same issue?

**Comment by JoeFertig** [comment]
Not the same issue but my experience was that while commenting with @ or # was blocked I was able to do comments without mentioning the user or using hashtags.
