### ISSUE TITLE
schedule not found

### ISSUE THREAD

**Issue by aghili371** [InstaPy/InstaPy#3410]
i used a template which using schedule but i got this error.
 File "xxx.py", line 15, in <module>
    import schedule
ModuleNotFoundError: No module named 'schedule'
the 15 line is import schedule.

**Comment by LotusPainter** [comment]
import schedule needs to be at the top with your other imports afaik

**Comment by aghili371** [comment]
i just using this Follow unfollow & send Telegram msg.py template. i think it can't find module named 'schedule'. where is this class?

**Comment by aghili371** [comment]
i found solution. it needs this at fist:
pip install schedule
