### ISSUE TITLE
Is it possible to comment after follow?

### ISSUE THREAD

**Issue by sourstripe** [InstaPy/InstaPy#3412]
Is it possible to post a comment like "I am going to follow you, your work is awesome" and then follow the person? I can't seem to find it by searching

**Comment by imkimchi** [comment]
I think setting comments and follow at the same time would work out?

**Comment by sourstripe** [comment]
> 
> 
> I think setting comments and follow at the same time would work out?

What do you mean by at the same time?

I want to have my normal set of comments, but when that comment is posted the bot will always follow right after, despite any other settings
