### ISSUE TITLE
Feature Request: Mandatory Words needs a list option ANY instead of ALL

### ISSUE THREAD

**Issue by visualheroes** [InstaPy/InstaPy#3416]
Well, i just discovered that Mandatory Words works with like_by_location, shame on me for not checking it sooner.

Anyway, i think it could be very helpful to have an option to load multiples possible mandatory words instead of multiples mandatory words (ANY instead of ALL).

Exemple:
Like by location > Zermatt
Mandatory Words > #hiking or #biking or ...

At the moment it works like this:
Mandatory Words > #hiking and #biking and ...

**I think this is a game changer for "like_by_tags" and "like_by_locations".**

Any ideas on how to implement this?

**Comment by visualheroes** [comment]
Ok, i made it work with a small edit of check_link in like_util.py.

>     if mandatory_words :
>         if not any ((word in image_text for word in mandatory_words)) :
>             return True, user_name, is_video, 'Mandatory words not fulfilled', "Not mandatory likes"

However i'm not sure if there is a typo in the original as mandatory_words for commenting is using ANY and not ALL. For liking it's the opposite.
**Any one knows if it was intended?**

A more elegant solution might be two separate variables: any_mandatory_words, all_mandatory_words. This way there won't be any confusion between the two.

What you think? 

@ohio36 Is this similar to what you wanted to add with the complementary keywords?

**Comment by oskarkrawczyk** [comment]
That explains a lot, I was absolutely mandatory words would pick ANY word from the list, not ALL.

**Comment by ohio36** [comment]
@visualheroes Actually in my installation of Instapy I had made the exact same change. ALL is much too strict for me, but I do like to be able to define a list of keywords. So far I only changed ALL to ANY in the code, just like you did. But I intend to add an extra parameter to the mandatory_words function so you can indicate weather or not you want ALL words to be present. Something like strict=True/False. Will try to add a new PR in the near feature.
