### ISSUE TITLE
Instagram login page changed?

### ISSUE THREAD

**Issue by sunnypatel165** [InstaPy/InstaPy#342]
Until 2 hours ago I was using this and when I executed this now, the script failed and on taking a quick look - I think Instagram login page has changed in some way. 
It doesn't seem to have the ID/Password login form by default!

This is what I see:

<img width="406" alt="screen shot 2017-06-26 at 9 27 57 pm" src="https://user-images.githubusercontent.com/9017668/27548477-a7c04062-5ab6-11e7-9886-f6a05e419421.png">

Is this a change on insta site? can we accommodate this in some way?
Are they mandating "login via Facebook" - that sucks! 🤕

**Comment by timgrossmann** [comment]
@I checked several browsers and locale settings, but couldn't get this page...

I still have the signup form with the little login link on the bottom of the page.

**Comment by sunnypatel165** [comment]
@timgrossmann  - probably they're rolling out in phases, maybe AB testing. 
If at all they change it permanently, we'll have to figure out a way around this.

**Comment by timgrossmann** [comment]
@sunnypatel165 I'm not really sure if they will remove the standard login mechanism completely...
But yes, we'll see and adapt once this becomes a big problem.

**Comment by sunnypatel165** [comment]
Owkay - not sure if it's already time to close this - the issue still remains, maybe for a fewer number of people, but it does!

**Comment by timgrossmann** [comment]
@sunnypatel165 Keeping every single issue open will flood the issues section and make it very hard to find anything or keep track of things.

I think this will get important if some people (more than one) faces this problem.

**Comment by DylanRichardPearson** [comment]
I'm seeing this issue also.

**Comment by ujazzz** [comment]
having the same issue

**Comment by scopalaffairs** [comment]
yes, this is on.

**Comment by RobertHosking** [comment]
I may be having the same issue:

```
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//footer[@class='_oofbn']/div[@class='_mhrsk _pcuq6']/nav[@class='_p1gbi']/ul[@class='_fh0f2']/li[@class='_fw3ds'][10]/span[@class='_17z9g']/select[@class='_nif11']/option[text()='English']"}
```
When calling `session.login`. This may also have something to do with an issue I was having with likes actually registering in IG. Detailed in #343

**Comment by timgrossmann** [comment]
@RobertHosking please do a `git pull` this issue should be covered by #347

**Comment by ashi1702** [comment]
similar issue

**Comment by IPYWorld** [comment]
I had the same issue as https://github.com/timgrossmann/InstaPy/issues/342#issuecomment-311766373 but the `git pull` (https://github.com/timgrossmann/InstaPy/issues/342#issuecomment-311796801) fixed it.

**Comment by Sem7** [comment]
Facing the same issue. The code get me to the same screen as sunnypatel165 and obvsly the code doesn't work :(

Thanks for the awesomeness Tim!

**Comment by scopalaffairs** [comment]
the updating commit seems to work, at least login works. thanks!

**Comment by scopalaffairs** [comment]
still, I get the same error -- the server became very slow after the update and the message persists:
[...]
` self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-81-generic x86_64)`

**Comment by timgrossmann** [comment]
@scopalaffairs Did you reboot your system?

**Comment by scopalaffairs** [comment]
@timgrossmann thanks, worked beautifully – this solved my issue

**Comment by sunnypatel165** [comment]
Good to close I think @timgrossmann - works fine again!
