### ISSUE TITLE
instapy Sessional live report not returning correct numbers

### ISSUE THREAD

**Issue by nicwilliams15** [InstaPy/InstaPy#3424]
When instapy is finished running the live report returns:
  Sessional Live Report:
	|> LIKED 0 images  |  ALREADY LIKED: 0
	|> COMMENTED on 0 images
	|> FOLLOWED 1 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0
currently FOLLOWING 3748 users & has got 28856 FOLLOWERS

The current FOLLOWING is correct. The has got 28856 FOLLOWERS is incorrect. I believe instapy grabs this report before the script runs. The correct number should be somewhere around 28906 Followers not sure why this is happening. Any help would be appreciated. Thanks.

**Comment by octavius-1** [comment]
Hey, that followers number is taken when the session is started, so the numbers may change.
