### ISSUE TITLE
Check if like was removed by instagram in order to avoid blocking

### ISSUE THREAD

**Issue by brunomiguelleal** [InstaPy/InstaPy#3429]
Hi all,

Not sure if this is the right place to put this idea, and I'm not even sure if this is implemented, but as you might know, when you abuse on liking (manually) Instagram just removes the like right after you click the heart icon. This way you know that you have liked too many posts too quick and you need to make a pause.

How hard will it be to change the code so after each like InstaPy checks if the like is still there? If not a pause should be done?

Thank you in advance and sorry if this is not the right place but I'm new to github.

Cheers,
Bruno

**Comment by sionking** [comment]
I think it already checked (by reloading the page)

**Comment by brunomiguelleal** [comment]
And what does InstaPy does with that information, do you know? 
I wonder if it automatically sleeps. If it does, we can put InstaPy to run without restrictions obtaining maximum amount of likes, no?
