### ISSUE TITLE
Logs say "liked" but no like on actual post

### ISSUE THREAD

**Issue by RobertHosking** [InstaPy/InstaPy#343]
Running the script this morning to find that although the scripts runs normally with normal output on the console, my account shows no record of liking the photos that it says I am liking. 

Did some playing around: 
When the script shows the post data then pauses for a bit before liking, I look up that post on my phone. Then with the post open, I refresh after the script has liked that post and it DOES show that I've liked the post (without manually pressing the like button, of course).

I will note that I had some login trouble with the script. I manually logged into the Instagram web interface form my browser and was greeted by a message stating that there was some strange login attempts and asked me to verify that this was me (which I did). After this the script login worked fine but now I have the issue stated here.

Any tips?

EDIT: just tried the same script with a different account and likes work just fine. So it's not an issue with InstaPy but rather Instagram and my account. I'm hoping someone knows how to fix this.

EDIT 2: Just tried again with the alternate (previously working) account, and I have the same problem. Also, I can still manually like posts on both accounts. I've been testing the script using small amounts that should'nt total to more that 100 likes per day

EDIT 3: Comments are working as usual however, the post that the comment belongs to is not liked

**Comment by timgrossmann** [comment]
@RobertHosking This sounds like your liking feature was temporarily banned. 
Could you check that by liking something by hand on that account? Should open up a modal that says that this feature is currently temporarily disabled for you

**Comment by RobertHosking** [comment]
I can still like by hand on mobile. I don't see why I would be banned. I've only been testing lately with small like numbers no more than 100/day.

**Comment by timgrossmann** [comment]
@RobertHosking Ok, good to know.

We'll, the described behaviour appeared for me when I was banned... 

The message that there was a strange login is alright, this happens with every new use. Sometimes you also have to verify your account by phone or mail as well.

Can you also like by hand in the web browser?

**Comment by RobertHosking** [comment]
Yes, browser liking works on both accounts.

Just tried the script again. No avail.

**Comment by timgrossmann** [comment]
@RobertHosking Hmm... thank you for checking this.

This is really weird 🤔 
You are probably running it on a server, aren't you?
Could you try to get it up and running on your local machine and watch it while it's running for a few posts? When it hit the like button, reload the page before the script continues.

**Comment by RobertHosking** [comment]
I got a local version running and it works! It likes posts whether I'm looking at them or not.
I have two instances of this script on two different servers. Neither of them are working for any of my accounts. They were working last week, no problem.

This doesn't resolve my issue (to be clear). I still need the script to work on my servers. Any thoughts so far?

**Comment by RobertHosking** [comment]
Alright, I've done the pull on #347. Still, the script fails to actually like post on all my servers, on all my accounts. 

If I bring up the targeted post on my phone before the script likes, then refresh on my phone after the script likes, the likes register. Otherwise no actual liking is happening. Comments work fine.

Running the script locally works fine on all accounts.

Just created a new IG account to test with and it work with this new account. Does this mean my other accounts have been banned/watched for suspicious activity?

Any idea what is going on?

**Comment by fran6will** [comment]
Same problem here! Have you found a solution?

**Comment by andrewjburnett** [comment]
Ideas?

**Comment by RobertHosking** [comment]
I occasionally get the issue but it works fine 95% of the time. No idea why it stops/starts working again.

**Comment by Fannolo** [comment]
This happened to me too and my best guess is that Instagram blocked the IP of your server from which the most of the liking and commenting were coming from on that particular account.
You might wanna stop for 24 hours before resuming, and slow down your schedule on the cron  jobs
