### ISSUE TITLE
Error occurred while deleting cookies from web browser! Message: no such session

### ISSUE THREAD

**Issue by tomtactom** [InstaPy/InstaPy#3436]
I have a problem, I have load the programm ca 12h
Than came these Error!

------------------------------------------------------------

ERROR [2018-11-26 00:14:55] [myinstaname]  Error occurred while deleting cookies from web browser!
	Message: no such session
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)
Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 3625, in end
    self.browser.delete_all_cookies()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 878, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: no such session
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)

ERROR:myinstaname:Error occurred while deleting cookies from web browser!
	Message: no such session
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)
Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 3625, in end
    self.browser.delete_all_cookies()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 878, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: no such session
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)

INFO [2018-11-26 00:14:55] [myinstaname]  Sessional Live Report:
	|> LIKED 0 images  |  ALREADY LIKED: 0
	|> COMMENTED on 0 images
	|> FOLLOWED 483 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0
currently FOLLOWING 311 users & has got 109 FOLLOWERS

INFO:myinstaname:Sessional Live Report:
	|> LIKED 0 images  |  ALREADY LIKED: 0
	|> COMMENTED on 0 images
	|> FOLLOWED 483 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0
currently FOLLOWING 311 users & has got 109 FOLLOWERS

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-11-26 00:14:55] [myinstaname]  Session ended!
INFO:myinstaname:Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by uluQulu** [comment]
@tom12aschmann 
That can happen from time to time for several reasons;
In its simplest form, it will be in chromedriver's side [out of a bug, incompatibility with its browser, etc.]

But if you get that problem always or too frequently, then there is a problem.

Also,
`Message: no such session` makes me think your browser instance has crashed and having known that you ran it 12 hours, I can guess that it is viable and can occur e.g. after the computer ran out of memory..

If I am right about the inspection above and you really have memory issues, then use different styles and do not keep a session instance for that long.

In any case using shorter styles is much more efficient than all-time longer running styles.
And you should retire session object after finishes working with it (_considering you don't have specific reasons to keep it_).
See @Mehran's quickstart template.

---

Cheers 😁
---
