### ISSUE TITLE
Instapy strange issue on set_dont_unfollow_active_users

### ISSUE THREAD

**Issue by brunomiguelleal** [InstaPy/InstaPy#3438]
## Expected Behavior
Function to get the list of users that liked X amount of posts.
## Current Behavior
First I had an issue where every time instaPy would crash when executing this function.

The problem was in this line in util.py / get_active_users:
     likes_button = browser.find_elements_by_xpath("//button[contains(@class, '_8A5w5')]")[1]
Basically in this list the likes button is not always on position 1, but as far as I understood the likes button is always the last in the list so I've changed the code accordingly.

Now the strange thing with InstaPy(...headless_browser=True ...) it doesn't work and I get:
      Failed to get likers count on your post 1

If I change the headless_browser to False (and so the browser is opened) it works perfectly:
      INFO:<my username>:Getting active users who liked the latest 10 posts:
        ~collecting the usernames from posts with the boundary of 100000

      INFO [2018-11-26 22:21:36] [<my username>]  Post 1  |  Likers: found 205, catched 205
      INFO:brunolealtravels:Post 1  |  Likers: found 205, catched 205

For now I'll be using this with the browser option but I find this very strange as it looks like headless_browser=False after all is not exactly the same as with True.

**Comment by ngalatis** [comment]
It happens to me as well, when one of the posts that is going to check is a video. If they are only photos it will work.
Found this bug a while ago.
