### ISSUE TITLE
 from instapy.util import smart_run

### ISSUE THREAD

**Issue by efaria** [InstaPy/InstaPy#3439]
InstaPy-master\InstaPy-master\quickstart.py", line 4, in <module>
    from instapy.util import smart_run
ImportError: cannot import name smart_run

**Comment by uluQulu** [comment]
Talk about how you do run InstaPy;
Possibly, there is a circular dependent import of `smart_run` function somewhere in your code.

**Comment by salas81** [comment]
I'm still experiencing this problem on macOS
