### ISSUE TITLE
live_match = False doesn't work

### ISSUE THREAD

**Issue by harrycha** [InstaPy/InstaPy#3441]
## Code
cinderella_followers = session.grab_followers(username="account", amount="full", live_match=False, store_locally=True)
## Current Behavior
Redownloading the jason files and making server requests. Which takes up to 5 mins at a time
## Possible Solution (optional)
Reiterate the code

**Comment by uluQulu** [comment]
@OGHARRY 
![image](https://user-images.githubusercontent.com/33269249/49256826-bb7b2580-f449-11e8-82f3-ef27e6f6cbbc.png)

#### If you really understood the documentation and correctly, then you should know also know this:

You can benefit the _smart_ **data-matching** algorithm per every unique alive session.

>In other words, if you retire a session object and then start another session or use another existing session, then you shouldn't expect `live_match` to help you.

There are several reasons I decided it like so and you can read the reasons in its PR description & comments in details.

Obviously, you want to take advantage of that speed by loading local files and hoping _smart_ **data-matching** algorithm work for it, then you, have to write some new lines manually 🙂

---

Cheers 😁
---
