### ISSUE TITLE
Is it possible to restrict likes by hashtag when liking media from some user's followers?

### ISSUE THREAD

**Issue by mroerkessler** [InstaPy/InstaPy#3446]

**Comment by mroerkessler** [comment]
I'm new to this and I'm trying to get up to speed as quick as I can. I am trying to restrict the code from liking posts for some user's followers media that have the tag travel.

If anyone can help me, it would be much appreciated.

Thx!

**Comment by amauryleproux** [comment]
I think that you can do it with the example code to interact with someone else followers, then you add the Mandatory code with the tag #travel 

To make it works you have to load between 5 and 10 pictures on each people instapy goes on, and then it will check if the hashtag #travel is in the post and will like or not
