### ISSUE TITLE
ModuleNotFoundError No Module named 'regex' or 'meaningcloud'

### ISSUE THREAD

**Issue by ShiftingKill** [InstaPy/InstaPy#3449]
With the new pull I got what the title says. Now after downloading regex through Windows PowerShell I saw I had to update a few other things, no problem, I figured all of this out on my own so far rightt? Start quickstart again and it crashes, I think to myself, "still no problem I was able to get everything else installed thus far." Then I screenshot CMD upon crash to find it said:
No Module named 'meaningcloud'
So I tried:
python -m pip install meaningcloud
But PowerShell says:
"Could not find a version that satisfies the requirement meaningcloud (from versions: )
No matching distribution found for meaningcloud"

Do I have to comment out something in InstaPy.py like how I do for clarifai utility? Do we have to opt out of this new feature manually?

**Comment by ShiftingKill** [comment]
Well, doing:
python -m pip install meaningcloud-python
installed it, and now it works flawlessly. Should've toyed around with it more. I saw https://github.com/timgrossmann/InstaPy/pull/3318#issuecomment-441365788
Shoutout to Mehran.

**Comment by Mizi91** [comment]
Worked to me with:
python -m pip install meaningcloud-python
python -m pip install regex

**Comment by mgconejero** [comment]
Had same issue, thanks @ShiftingKill  for the fix 👍

**Comment by nafferro** [comment]
I'm having this error right now:
ImportError: No module named 'meaningcloud'

even after "python -m pip install meaningcloud-python" or "python3 -m pip install meaningcloud-python" or "pip install meaningcloud-python" or "pip3 install meaningcloud-python" im using ubuntu on a raspberry

**Comment by gedegeyter** [comment]
I have this issue as well. I tried the fix above but doesnt do anything.

**Comment by pietrobelluno** [comment]
I run python -m pip install regex and its installed:
"Requirement already satisfied: regex in /Library/Python/2.7/site-packages (2019.2.21)"
and i run de bot continuous with:
ModuleNotFoundError: No module named 'regex'

**Comment by tE3m** [comment]
You probably mixed up python2.7 and python3

**Comment by pietrobelluno** [comment]
how can i do this?

**Comment by tE3m** [comment]
`python3 -m pip install regex`?

**Comment by pietrobelluno** [comment]
now im getting ModuleNotFoundError: No module named 'instapy_chromedriver'

**Comment by tE3m** [comment]
You didn't install instapy on python3. Run 
```
pip3 install instapy
```
That installs all dependencies

**Comment by pietrobelluno** [comment]
thanks for the help @TarekJ03  !
