### ISSUE TITLE
Use instagram query? in get_active_users

### ISSUE THREAD

**Issue by brunomiguelleal** [InstaPy/InstaPy#3452]
Hi everyone,

I was trying to figure out if it's possible to develop the get_active_users function using the instagram query? similarly to what is done to get the list of followers and following.
Anyone knows if this Instagram provides a query for this?

The problem with current version of get_active_users is that it's very hard to work when you have +3K likes in one photo let alone in multiple photos with +3K likes...

I was able to replicate parts of the code and I have now my first post opened and I can navigate to next one, I just can't figure out how to discover the query "hash" to do this if it's available.

Thanks in advance,
Bruno

**Comment by sionking** [comment]
I prepared something for that, I just capture the list to the DB and will not capture again for the next 24 hours, not the best solution but do works!

BTW, tell us your trick to get 3+ likes!

**Comment by brunomiguelleal** [comment]
Did you use the api queries or "normal" requests for that? I'm really interested in the query solution if there is any.

What do you mean by trick? Didn't follow on that... 🤔

**Comment by sionking** [comment]
> photos with +3K likes...

This trick 💯 

And not using query sorry

**Comment by brunomiguelleal** [comment]
haaaaaaa... no trick there...

I've been using a macro software on windows to do the same as InstaPy for the last 1 year or so...I don't post that many pictures so in 1 month I get +2k or +3k on each picture...

I'm now switching to InstaPy which is much more powerful and easy to control...

I'm trying to get the list of users that like each post with queries...fingers crossed! :)
