### ISSUE TITLE
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"}

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#3459]
@converge @timgrossmann @sionking @uluQulu 

Traceback (most recent call last):
  File "/root/InstaPy/5bfe91a9b72ae70014ad931a.py", line 24, in <module>
    session.interact_user_followers(['bowles','ecom_mentor','youngwithambition','rickygutierrezz','ecomwolf'], amount=70, randomize=True)
  File "/root/InstaPy/instapy/instapy.py", line 2596, in interact_user_followers
    self.logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 884, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/root/InstaPy/instapy/unfollow_util.py", line 651, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"}
  (Session info: headless chrome=70.0.3538.77)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 4.15.0-39-generic x86_64)

**Comment by nadavdrukker** [comment]
same here from follow_user_followers

**Comment by lbenassi** [comment]
I have the same error too from session.follow_user_followers

**Comment by zartaz** [comment]
same here

Traceback (most recent call last):
  File "quickstart.py", line 28, in <module>
    session.follow_user_followers(['example'], amount=10, randomize=False)
  File "/home/zartas/InstaPy/instapy/instapy.py", line 2907, in follow_user_followers
    self.logfolder)
  File "/home/zartas/InstaPy/instapy/unfollow_util.py", line 884, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/home/zartas/InstaPy/instapy/unfollow_util.py", line 651, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.15.0-39-generic x86_64)
try to build with pip3.6 also run with python3.6 quickstart.py tried installing & running with 2.7 same error

**Comment by mygreatventure** [comment]
same here.

**Comment by c0d3x27** [comment]
i have this same error what is happening?

**Comment by sergiosre** [comment]
Some one can fix it ??

**Comment by elbeye** [comment]
Oh god I'm not alone.

**Comment by Tachenz** [comment]
Yep, same here. I guess it happened for everyone :)

**Comment by sionking** [comment]
```
    # find dialog box
    try:
        dialog_address = "//div[text()='Followers' or text()='Following']/../../following-sibling::div"
        dialog = browser.find_element_by_xpath(dialog_address)
    except NoSuchElementException:
        dialog_address = "//div[contains(@class,'isgrP')]"
        dialog = browser.find_element_by_xpath(dialog_address)

```

**Comment by c0d3x27** [comment]
@sionking i already did this and isnt working

**Comment by c0d3x27** [comment]
after what happend today i advice everyone to hurry up and get as many follows as you all can because this is just too cute to be true and it can end at any time. today is a good example. i did a mistake by taking my time and taking it easy. now if i get to fix this i will hurry up and get my followers to where i want them( at least 11k im at 8k)

**Comment by ghost** [comment]
@Banginpadr it's just a change in the html maded by an update from instagram ... and the solutions provided works for me ... there is no need to alarm anyone.

**Comment by c0d3x27** [comment]
@ilmetu you are not getting my point. im not alarming anyone im saying it how it is. this tool is heaven and as anything good it can always end thats all. why are you talking it to the heart? is not like im wishing it since im using.

**Comment by fgisslen** [comment]
@sionking thanks, will try that now.

**Comment by sergiosre** [comment]
then some solution to fix it ?

**Comment by fgisslen** [comment]
@sergiosre @sionking sent this solution and it seems to work:
# find dialog box
    try:
        dialog_address = "//div[text()='Followers' or text()='Following']/../../following-sibling::div"
        dialog = browser.find_element_by_xpath(dialog_address)
    except NoSuchElementException:
        dialog_address = "//div[contains(@class,'isgrP')]"
        dialog = browser.find_element_by_xpath(dialog_address)

**Comment by sergiosre** [comment]
@fgisslen where i need to modify this?

**Comment by fgisslen** [comment]
@sergiosre in instapy/unfollow_util.py

**Comment by elbeye** [comment]
How kind of changes I will do?

**Comment by Tr1pke** [comment]
i get this now:

Traceback (most recent call last):
  File "ttt-follow-unfollow.py", line 1, in <module>
    from instapy import InstaPy
  File "/home/***/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/***/InstaPy/instapy/instapy.py", line 28, in <module>
    from .like_util import check_link
  File "/home/***/InstaPy/instapy/like_util.py", line 18, in <module>
    from .unfollow_util import get_following_status
  File "/home/***/InstaPy/instapy/unfollow_util.py", line 406
    dialog = browser.find_element_by_xpath(dialog_address)
    ^
IndentationError: unexpected indent

**Comment by fgisslen** [comment]
@Tr1pke there is a very nice message for you there :)
^
IndentationError: unexpected indent

**Comment by mygreatventure** [comment]
> ```
>     # find dialog box
>     try:
>         dialog_address = "//div[text()='Followers' or text()='Following']/../../following-sibling::div"
>         dialog = browser.find_element_by_xpath(dialog_address)
>     except NoSuchElementException:
>         dialog_address = "//div[contains(@class,'isgrP')]"
>         dialog = browser.find_element_by_xpath(dialog_address)
> ```

worked perfectly for me. thank you for such a prompt help, @sionking!

**Comment by sergiosre** [comment]
For me doesn't work , it throws invalid syntax...

**Comment by fgisslen** [comment]
@sergiosre if you write it correct it will work.
Write it with indentation..

**Comment by sergiosre** [comment]
now its correct now! jaja

**Comment by sergiosre** [comment]
work but throw the same error

**Comment by Tr1pke** [comment]
its working, i didn't add the 'try:' on top
thanks !

and its the **_second_** #find dialog box, not the first

    # find dialog box
    try:
        dialog_address = "//div[text()='Followers' or text()='Following']/../../following-sibling::div"
        dialog = browser.find_element_by_xpath(dialog_address)
    except NoSuchElementException:
        dialog_address = "//div[contains(@class,'isgrP')]"
        dialog = browser.find_element_by_xpath(dialog_address)_

**Comment by spikeyhair** [comment]
Still throwing the same error:

__________________________________________________________________
INFO [2018-11-30 18:40:40] [xxx]  Starting to unfollow users..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2018-11-30 18:40:40] [xxx]  Unfollowing the users you are following
INFO [2018-11-30 18:42:43] [xxx]  Too many requests sent!  attempt: 1  |  gathered links: 1080
~sleeping a bit
INFO [2018-11-30 18:54:32] [xxx]  Too many requests sent!  attempt: 2  |  gathered links: 2136
~sleeping a bit
ERROR [2018-11-30 19:13:48] [xxx]  Sorry, an error occurred: Message: no such element: Unable to
 locate element: {"method":"xpath","selector":"//div[text()='Following']/../../following-sibling::di
v"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows
 NT 6.1.7601 SP1 x86_64)
