### ISSUE TITLE
Why InstaPy instead of native instagram API?

### ISSUE THREAD

**Issue by emKaroly** [InstaPy/InstaPy#346]
Why is better this approach than using the instagram API. Is there any limiting factor of API?

**Comment by petriichuk** [comment]
Yes, to use the API you need to make a whole application than can use many people (can't be just for your project), and to get out of Sandbox mode, you need to submit your app for review. I am sure that the admins will not accept this type of application.

**Comment by timgrossmann** [comment]
Also, the API has a lot of restrictions and limits when it comes to hourly interactions.
You don't have that when using Selenium
