### ISSUE TITLE
Failed to load desired amount of users....

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#3467]
Grabbed 0 usernames from "username" to interact - is back at full force after the most recent update, unfortunately :(

@uluQulu   No chance to do something about that one?

**Comment by Tachenz** [comment]
There were few older issues dedicated to that one, but bot succesfully closed them :)

**Comment by DJRay57** [comment]
Be good to see what the issue was last time round?

**Comment by Tachenz** [comment]
@djray57 of course!!
It happens when in “interact with user followers mode”. And basically not picking any user followers at all after some consideration ;)

Here is the old one:
https://github.com/timgrossmann/InstaPy/issues/3085

And the screenshot:
https://user-images.githubusercontent.com/36073534/47759439-88f1d780-dca7-11e8-8e29-1d02c6e32b09.png

**Comment by Tachenz** [comment]
Noone?

**Comment by Venni27** [comment]
Same here...error when try to follow someone elses followers...no solution?

**Comment by julienteyssier** [comment]
Same for me

**Comment by universalxtv** [comment]
Same... not working
