### ISSUE TITLE
Some users are not unfollowed

### ISSUE THREAD

**Issue by brunomiguelleal** [InstaPy/InstaPy#3470]
## Expected Behavior
Unfollow all users that match the criteria. As per below code, in the log I see that 1000 users were unfollowed, but it's not true as some, after InstaPy execution I'm still following...

Anyone ever experienced this situation?

## Current Behavior
During the execution of unfollow_users some users are marked in the log as unfollowed, but when I go to instagram I am still following them.

## InstaPy configuration
        session.set_quota_supervisor(enabled=True,
                             sleep_after=["unfollows_h"],
                             sleepyhead=True, stochastic_flow=True, notify_me=False,
                             peak_unfollows=(200, None),
                             )
       
        session.unfollow_users(amount=1000, customList=(False, [], "all"), InstapyFollowed=(False, "all"), nonFollowers=True, allFollowing=False, unfollow_after=48 * 60 * 60, sleep_delay=5)

**Comment by brunomiguelleal** [comment]
No one else experiences this situation? From last night for example I have on my log +600 users unfollowed and when I start checking those users on my instagram most of them were not unfollowed...this is quite a strange situation as some are in fact unfollowed... :S

**Comment by brunomiguelleal** [comment]
Interesting is that the issues seems to be with Instagram in the browser. I just tried to unfollow one of the users that was not unfollowed by InstaPy and it showed everything as normal (blue button to follow appeared after confirming that I want to unfollow) but then when I refresh the page that user is still being followed. Went to the mobile app and successfully unfollowed that same user...

**Comment by oskarkrawczyk** [comment]
I'm also experiencing this issue. The script insists I have `0` users to unfollow that were auto-followed, but in fact I have at lest 300 more users that should have been unfollowed.

I've experienced this a few weeks before, which is why I opted out of using that feature, thought this might have been fixed so tried again.

I see some users keep having this issue, perhaps adding a `doublecheckUnfollow=True` option to the `unfollow_users` would make sense? I'd sacrifice some time, if it would make the script more accurate in unfollowing.

The piece of config I'm using:

```python
session.unfollow_users(
    amount=1000,
    InstapyFollowed=(True, "all"),
    style="FIFO",
    unfollow_after=1*60*60,
    sleep_delay=60
)
```

**Comment by brunomiguelleal** [comment]
My problem is different. In regards to InstaPyFollowed I have no issues at the moment. My problem is with the other options (unfollow users that don't follow back and custom unfollow).

My issue is that it unfollows (presses the button as I see in the browser) but some users are not unfollowed...I now use a different strategy. Extract all the listings by myself (with exception for InstaPyFollowed) and run the unfollow_users twice for each set of users to unfollow...

**Comment by oskarkrawczyk** [comment]
Gotcha, I'll post my issue as a new ticket then.
