### ISSUE TITLE
It cannot follow user's followers.

### ISSUE THREAD

**Issue by Ugar93** [InstaPy/InstaPy#3471]
I read all the issues about this topic, but none of it has helped me. Can someone tell me more what to do?
Screenshot down. 
Thanks for the answer!
![1](https://user-images.githubusercontent.com/45519981/49331616-67cf2000-f5a0-11e8-841f-489532fbce6f.png)

**Comment by varun13169** [comment]
#3455 check this out

**Comment by Ugar93** [comment]
No. I tried. I cloned again complete InstaPy in my GitHub desktop. Tried again to do, now shows this (bellow)
![1](https://user-images.githubusercontent.com/45519981/49345448-367c5000-f685-11e8-9633-fc400dd58e26.png)

**Comment by Ugar93** [comment]
Installed regex, now shows this
![1](https://user-images.githubusercontent.com/45519981/49345625-ccb17580-f687-11e8-82d9-40f721989a1d.png)

**Comment by Ugar93** [comment]
Done with truncate. Now shows this! Help, i will lose my mind literally :D 
![1](https://user-images.githubusercontent.com/45519981/49345742-89580680-f689-11e8-94c7-8ae0f5d0ff50.png)

**Comment by Pormientras1** [comment]
Hey @Ugar93 I am having the exact same problem, do you find a fix?

**Comment by billygorg2** [comment]
im having the same issue also

**Comment by billygorg2** [comment]
im having the same issue @Ugar93 @Pormientras1 Quickstart.py is working for me but the following does not

**Comment by syond** [comment]
Just go to Instapy directory and run this in admin mod (sudo):

`pip3 install --upgrade pip`
`pip3 install -r requirements.txt`

After that, run the quickstart with your parameters:

`python3 quickstart.py`

The **3** is very important here.
