### ISSUE TITLE
Python 2 // Python 3 problems

### ISSUE THREAD

**Issue by JoeFertig** [InstaPy/InstaPy#3478]
Hello Instapyers!

Is it possible that we switched from python2 to python3 after the last PR?
I have a tons of problems now to get my Raspberry Pi 3b+ running. It was running totally smooth and fine before the las PR. 

Would love to switch completely to python3 but everytime I execute I got errors like "no module named selenium", or this one:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from instapy import InstaPy
  File "/home/pi/instagram/Projects/instapy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/pi/instagram/Projects/instapy/instapy/instapy.py", line 13, in <module>
    from selenium import webdriver
ImportError: cannot import name 'webdriver'

Thing is when I try to install selenium for example it tells me it is already installed:
"Requirement already satisfied: selenium in /usr/local/lib/python2.7/dist-packages (3.141.0)"
--> but why is it using the python2.7 lib? 

Please guys I need help I really don't know how to handle this python2 / python3 problems :(

**Comment by samihamine** [comment]
Hello, 
an "pip install ." or "pip3 install ." (if python3) will solve the problem ;)

**Comment by JoeFertig** [comment]
Sorry but it won't and this answer is not very helpful as you can see I mentioned that "pip3 install ." or "pip3 install selenium" is not working.

**Comment by samihamine** [comment]
I'm sorry @JoeFertig  It was midnight i have probably misread your message :/

**Comment by JoeFertig** [comment]
All good mate... no problem :)

**Comment by notefortroy** [comment]
@JoeFertig - Having a tough time getting things working. Probably a similar setup running a raspberry pi 3b+ cron job setup on python 2.7

**Comment by Apao123** [comment]
if you use **pip3 install selenium** --> they wouldn't use: usr/local/lib/python2.7 as you mentioned. it should finding on python3.XX you installed in the server. Which python 3 version you installed?

**Comment by JoeFertig** [comment]
I have python2.7 and 3.5
But pip2 install package installs into 2.7 if it's not already installed there.

**Comment by petekirwan** [comment]
I have a similar problem. Package is installing into 2.7 and not sure how to get it into 3.6 instead. Tried using Pip3. I'm using a VM just for this so don't want to bother with creating a venv for it.
