### ISSUE TITLE
Installed the new version of InstaPy and now getting this error Type Error: 'type' object is not iterable.. Help please

### ISSUE THREAD

**Issue by JennaDoll** [InstaPy/InstaPy#3479]
I installed the new version on InstaPy yesterday after my old version stopped working and now im getting the following error below..

## Expected Behavior
Instapy application should run and open up chromebrowers to login to my instagram when i run python quickstart.py 

## Current Behavior
Getting the error below after I install and then enter the command python quickstart.py  
I've entered my username and passcode in the quickstart.py file. 
I've Installed Chromedriver and moved it to the /assets folder
I've deleted and tried to install package again and still got the same issues

My commands i've entered on my mac are below: Below I have the screenshot of the commands and below that the same commands but I copied and pasted from command prompt.

![image](https://user-images.githubusercontent.com/45544465/49345973-a3212b80-f640-11e8-8802-e3161ed0ffc3.png)

`Last login: Sun Dec  2 14:08:28 on ttys000
cs-iMac:~ cc$ git clone https://github.com/timgrossmann/InstaPy.git
Cloning into 'InstaPy'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 7357 (delta 6), reused 13 (delta 6), pack-reused 7338
Receiving objects: 100% (7357/7357), 77.21 MiB | 13.51 MiB/s, done.
Resolving deltas: 100% (4845/4845), done.
cs-iMac:~ cc$ cd InstaPy
cs-iMac:InstaPy cc$ sudo pip install .
Password:
The directory '/Users/cc/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/cc/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /Users/cc/InstaPy
Requirement already satisfied: certifi>=2018.10.15 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2018.10.15)
Requirement already satisfied: chardet>=3.0.4 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (3.0.4)
Requirement already satisfied: clarifai>=2.4.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2.4.2)
Requirement already satisfied: configparser>=3.5.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (3.5.0)
Requirement already satisfied: EasyProcess>=0.2.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (0.2.3)
Requirement already satisfied: emoji>=0.5.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (0.5.1)
Requirement already satisfied: future>=0.17.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (0.17.1)
Requirement already satisfied: googleapis-common-protos>=1.5.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.5.5)
Requirement already satisfied: grpcio>=1.16.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.16.1)
Requirement already satisfied: idna>=2.7 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2.7)
Requirement already satisfied: jsonschema>=2.6.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2.6.0)
Requirement already satisfied: plyer>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.3.2)
Requirement already satisfied: protobuf>=3.6.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (3.6.1)
Requirement already satisfied: PyVirtualDisplay>=0.2.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (0.2.1)
Requirement already satisfied: requests>=2.20.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2.20.1)
Requirement already satisfied: selenium>=3.141.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (3.141.0)
Requirement already satisfied: six>=1.11.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.11.0)
Requirement already satisfied: urllib3>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.24.1)
Requirement already satisfied: regex>=2018.11.22 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2018.11.22)
Requirement already satisfied: MeaningCloud-python>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.1.1)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from protobuf>=3.6.1->instagram-py==0.0.1) (39.0.1)
Installing collected packages: instagram-py
  Found existing installation: instagram-py 0.0.1
    Uninstalling instagram-py-0.0.1:
      Successfully uninstalled instagram-py-0.0.1
  Running setup.py install for instagram-py ... done
Successfully installed instagram-py-0.0.1
cs-iMac:InstaPy cc$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/Users/cc/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users/cc/InstaPy/instapy/instapy.py", line 12, in <module>
    import requests
  File "/Library/Python/2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "/Library/Python/2.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/Library/Python/2.7/site-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/Library/Python/2.7/site-packages/cryptography/x509/extensions.py", line 24, in <module>
    from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
  File "/Library/Python/2.7/site-packages/cryptography/x509/general_name.py", line 18, in <module>
    from cryptography.x509.name import Name
  File "/Library/Python/2.7/site-packages/cryptography/x509/name.py", line 28, in <module>
    _ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)
TypeError: 'type' object is not iterable
cs-iMac:InstaPy cc$ `
## InstaPy configuration
My quickstart file code is below: 

I"ve replaced my passode with #######

![image](https://user-images.githubusercontent.com/45544465/49345934-4b82c000-f640-11e8-880f-3d2160fd7b50.png)

**Comment by uluQulu** [comment]
Hi @JennaDoll 
It means,
`requests` module needs `pyopenssl` which needs `cryptography` module which itself needs `enum` module for enumerations and here is your bug at this stage,
```erlang
_ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type) TypeError: 'type' object is not iterable
```
You don't have `enum` module available to use.

Starting from python 3.4, `enum` is part of the standard library, but for older pythons you have to install its third-party distribution- `enum34` from pip. 

And you have a python 2 🔄
Also, if you already have `enum` installed, uninstall it before installing `enum34`,
```powershell
pip uninstall enum
pip install enum34
```

---
Also, I think you installed the packages from pip for python 3 (`sudo pip install .`) and then ran quickstart script using python 2 (`python quickstart.py`).
Make sure you are targeting the right python & pip versions.

---


Cheers 😁
---

**Comment by JennaDoll** [comment]
@uluQulu Thanks for the help, I have uninstalled and tried to reinstall a few times and im still getting the same error. Im still getting the error below and I have done pip uninstall enum and pip install enum34 and command is returning that the Requirement is already satisfied.  Would you happen to know what else i can do to troubleshoot this please. Thanks in advance. 

`    _ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)
TypeError: 'type' object is not iterable
cs-iMac:InstaPy cc$ pip install enum34
Requirement already satisfied: enum34 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (1.1.6)`


**Below is the whole code if that helps with troubleshooting.** 

> `Last login: Sat Dec  8 20:53:55 on ttys000
cs-iMac:~ cc$ git clone https://github.com/timgrossmann/InstaPy.git
Cloning into 'InstaPy'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 7524 (delta 16), reused 18 (delta 9), pack-reused 7493
Receiving objects: 100% (7524/7524), 77.35 MiB | 13.44 MiB/s, done.
Resolving deltas: 100% (4955/4955), done.
cs-iMac:~ cc$ cd InstaPy
cs-iMac:InstaPy cc$ pip install .
Processing /Users/cc/InstaPy
Requirement already satisfied: certifi>=2018.10.15 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2018.10.15)
Requirement already satisfied: chardet>=3.0.4 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (3.0.4)
Requirement already satisfied: clarifai>=2.4.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2.4.2)
Requirement already satisfied: configparser>=3.5.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (3.5.0)
Requirement already satisfied: EasyProcess>=0.2.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (0.2.3)
Requirement already satisfied: emoji>=0.5.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (0.5.1)
Requirement already satisfied: future>=0.17.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (0.17.1)
Requirement already satisfied: googleapis-common-protos>=1.5.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.5.5)
Requirement already satisfied: grpcio>=1.16.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.16.1)
Requirement already satisfied: idna>=2.7 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2.7)
Requirement already satisfied: jsonschema>=2.6.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2.6.0)
Requirement already satisfied: plyer>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.3.2)
Requirement already satisfied: protobuf>=3.6.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (3.6.1)
Requirement already satisfied: PyVirtualDisplay>=0.2.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (0.2.1)
Requirement already satisfied: requests>=2.20.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2.20.1)
Requirement already satisfied: selenium>=3.141.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (3.141.0)
Requirement already satisfied: six>=1.11.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.11.0)
Requirement already satisfied: urllib3>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.24.1)
Requirement already satisfied: regex>=2018.11.22 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2018.11.22)
Requirement already satisfied: MeaningCloud-python>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.1.1)
Collecting PyYAML==3.13 (from instagram-py==0.0.1)
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
    100% |████████████████████████████████| 276kB 5.2MB/s 
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from protobuf>=3.6.1->instagram-py==0.0.1) (39.0.1)
Installing collected packages: PyYAML, instagram-py
  Running setup.py install for PyYAML ... done
  Found existing installation: instagram-py 0.0.1
    Uninstalling instagram-py-0.0.1:
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instagram_py-0.0.1-py3.7.egg-info/dependency_links.txt'
Consider using the `--user` option or check the permissions.

cs-iMac:InstaPy cc$ SUDO pip install .
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
The directory '/Users/cc/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/cc/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /Users/cc/InstaPy
Requirement already satisfied: certifi>=2018.10.15 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2018.10.15)
Requirement already satisfied: chardet>=3.0.4 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (3.0.4)
Requirement already satisfied: clarifai>=2.4.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2.4.2)
Requirement already satisfied: configparser>=3.5.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (3.5.0)
Requirement already satisfied: EasyProcess>=0.2.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (0.2.3)
Requirement already satisfied: emoji>=0.5.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (0.5.1)
Requirement already satisfied: future>=0.17.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (0.17.1)
Requirement already satisfied: googleapis-common-protos>=1.5.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.5.5)
Requirement already satisfied: grpcio>=1.16.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.16.1)
Requirement already satisfied: idna>=2.7 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2.7)
Requirement already satisfied: jsonschema>=2.6.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2.6.0)
Requirement already satisfied: plyer>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.3.2)
Requirement already satisfied: protobuf>=3.6.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (3.6.1)
Requirement already satisfied: PyVirtualDisplay>=0.2.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (0.2.1)
Requirement already satisfied: requests>=2.20.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2.20.1)
Requirement already satisfied: selenium>=3.141.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (3.141.0)
Requirement already satisfied: six>=1.11.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.11.0)
Requirement already satisfied: urllib3>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.24.1)
Requirement already satisfied: regex>=2018.11.22 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (2018.11.22)
Requirement already satisfied: MeaningCloud-python>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (1.1.1)
Requirement already satisfied: PyYAML==3.13 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instagram-py==0.0.1) (3.13)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from protobuf>=3.6.1->instagram-py==0.0.1) (39.0.1)
Installing collected packages: instagram-py
  Found existing installation: instagram-py 0.0.1
    Uninstalling instagram-py-0.0.1:
      Successfully uninstalled instagram-py-0.0.1
  Running setup.py install for instagram-py ... done
Successfully installed instagram-py-0.0.1
cs-iMac:InstaPy cc$ $ python quickstart.py
-bash: $: command not found
cs-iMac:InstaPy cc$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/Users/cc/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users/cc/InstaPy/instapy/instapy.py", line 12, in <module>
    import requests
  File "/Library/Python/2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "/Library/Python/2.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/Library/Python/2.7/site-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/Library/Python/2.7/site-packages/cryptography/x509/extensions.py", line 24, in <module>
    from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
  File "/Library/Python/2.7/site-packages/cryptography/x509/general_name.py", line 18, in <module>
    from cryptography.x509.name import Name
  File "/Library/Python/2.7/site-packages/cryptography/x509/name.py", line 28, in <module>
    _ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)
TypeError: 'type' object is not iterable
cs-iMac:InstaPy cc$ pip install enum34
Requirement already satisfied: enum34 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (1.1.6)
cs-iMac:InstaPy cc$ `

**Comment by JennaDoll** [comment]
@uluQulu YAY I got it to work!!!!!!! i uninstalled a few times and installed again using step 3 instead of step 2 and BOOM!!! im back in business!! THANK YOU THANK YOU THANK YOU THANK YOU SO MUCHH!!!!!@uluQulu!!!!!!

1. git clone https://github.com/timgrossmann/InstaPy.git
2. cd InstaPy
3. pip install .
or
3. SUDO python setup.py install

**Comment by JennaDoll** [comment]
ISSUE DONE AND DUSTED

D&D!!!!! HAHAHA CHEERS ALL< HAPPY HOLIDAYS!!!!
