### ISSUE TITLE
What can be done having a bad connection at home

### ISSUE THREAD

**Issue by HCWcoder** [InstaPy/InstaPy#3482]
Dear @timgrossmann 

What do you suggest to do in this case ?

the script is stopping after 20 or 30 min after start.

please suggest something to restart the script or wait or refresh the page if connection lost .

Thanks.

**Comment by sionking** [comment]
we need to take out the webdriver handling from instapy, so it will handle such cases.

**Comment by HCWcoder** [comment]
@sionking how can i do that? Can you help with that

**Comment by tjuzen** [comment]
make it run on a cloud server

**Comment by HCWcoder** [comment]
> make it run on a cloud server

@EMYULT what about the ip ?
