### ISSUE TITLE
Create InstaPy official repo on Dockerhub (allowing auto update using Watchtower)

### ISSUE THREAD

**Issue by maximang** [InstaPy/InstaPy#3483]
Hi,

Is it possible to create a Dockerhub repo and configure [automated builds from GitHub](https://docs.docker.com/docker-hub/github/)?

This could allow users of InstaPy Docker to beneficie of auto update, without having to recreate the Docker manually each time.

Thanks in advance!

**Comment by DamienMrtl** [comment]
This would be great, I would be happy to help out on this one.
