### ISSUE TITLE
meaningcloud install 

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#3487]
Hello trying to install the meaningcloud but have install problem any ideas please ? 

pip3 install meaningcloud
Collecting meaningcloud
  Could not find a version that satisfies the requirement meaningcloud (from versions: )
No matching distribution found for meaningcloud

@uluQulu 

Many Thanks.

**Comment by dsmh** [comment]
Same problem here, why is it closed without solution?

**Comment by mkllabarca** [comment]
same
