### ISSUE TITLE
"//button[contains(@class, '_8A5w5')]")[1] IndexError: list index out of range

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#3492]
Traceback (most recent call last):
  File "/root/InstaPy/5bd8c2442736500013d05552.py", line 20, in <module>
    session.set_dont_unfollow_active_users(enabled=True, posts=5)
  File "/root/InstaPy/instapy/instapy.py", line 3574, in set_dont_unfollow_active_users
    self.logger)
  File "/root/InstaPy/instapy/util.py", line 461, in get_active_users
    "//button[contains(@class, '_8A5w5')]")[1]
IndexError: list index out of range

**Comment by w4ngel** [comment]
This is to do with if one of the latest posts is a video. I believe.

**Comment by fgisslen** [comment]
@w4ngel You are right. Any solutions?

**Comment by w4ngel** [comment]
There needs to be a check put in that setting that checks the media type and skips it if it's a video.

**Comment by w4ngel** [comment]
Looking at a potential solution.

**Comment by IH4xx3R** [comment]
Same error for me :/ It's really an video issue

**Comment by armantur** [comment]
Had the same issue. Setting a time.sleep(2) before getting the elements resolved the issue.
