### ISSUE TITLE
Error loading cookies

### ISSUE THREAD

**Issue by w4ngel** [InstaPy/InstaPy#3493]
## Expected Behavior
Loads the cookie and logs in fine.

## Current Behavior
Throws an invalid type error. 
Note; I am moving the cookie from one machine to another to prevent the security code from popping up (New security code with instagram A/B testing really hard to replicate.) When I move the cookie over I get the following error when I try and force load the cookie (Removing the try/except statement) the following error is thrown: 

`selenium.common.exceptions.InvalidArgumentException: Message: invalid type: floating point '1859047680.79461', expected u64 at line 1 column 123`

Any suggestions as to why it cannot load a cookie? I understand adding back in the try/except allows it to work but I can't get past the new security code section.

**Comment by nRsWork** [comment]
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'c:\\python\\lib\\site-packages\\instagram_py-0.0.1-py3.6.egg'

**Comment by xerZV** [comment]
Cant start, same cant loing
