### ISSUE TITLE
Only unfollow followed by InstaPy

### ISSUE THREAD

**Issue by fgisslen** [InstaPy/InstaPy#3494]
I have a lot of problems with this setting, anyone else who encounter problems with it?

**Comment by pttnx** [comment]
Could you provide more details please? Which problems?

**Comment by fgisslen** [comment]
@pttnx It finds 0 to unfollow. I run 300+ accounts and there is problems with that unfollow setting.
It works when running without.

**Comment by lscaldas** [comment]
u run more than 300 accounts? by yourself? how do you manage? Could you explain to me, I am really curious.

**Comment by fgisslen** [comment]
@tiranin I use proxies to manage it.

**Comment by octavius-1** [comment]
Sometimes the log files are corrupted and you just need to go to that file and delete the corrupted line.

**Comment by fgisslen** [comment]
> Sometimes the log files are corrupted and you just need to go to that file and delete the corrupted line.

@octavius-1 What file do you mean? the regular follow file?

**Comment by lucascaldax** [comment]
@fgisslen  Do you use a single PC with multiple proxies, or are you using droplets in digital ocean with multiple proxies?

**Comment by fgisslen** [comment]
@lucascaldax I use a lot of droplets and A LOT of proxies. It costs about 2K€/month

**Comment by lucascaldax** [comment]
@fgisslen  thanks for the answer, do you have any tips, like how to profit with an account, what number of followers it should have? Are you already covering your costs? Are you able to run more than one account in a droplet?

**Comment by octavius-1** [comment]
@fgisslen Could you help us sharing your proxy setup? I'm getting banned for running accounts in AWS server locations.
