### ISSUE TITLE
Unfollow doesn't work well 

### ISSUE THREAD

**Issue by rmalosse** [InstaPy/InstaPy#3498]
I have problem with my instapy configuration. I have quickstart with follow & unfollow after 24h. 

with smart_run(session):
    """ Activity flow """
    # general settings:
    session.set_relationship_bounds(enabled=True,
                                 potency_ratio=-1.2,
                                  delimit_by_numbers=False,
                                   max_followers=4590,
                                    max_following=None,
                                     min_followers=45,
                                      min_following=77)
    session.set_simulation(enabled=True, percentage=0)
    session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
    session.set_do_follow(enabled=False, percentage=75)
    session.set_do_like(enabled=True, percentage=100)
    session.set_comments([ ' '], media='Photo')
    session.set_do_comment(enabled=True, percentage=50)

   # actions
    session.follow_user_followers([,,,], amount=30, randomize=False, interact=True)
    session.unfollow_users(amount=80, allFollowing=True, style="FIFO", unfollow_after=24*60*60, sleep_delay=180)

In my log file only 2 users unfollow: 

INFO [2018-12-04 20:18:28] [xxx]  Starting to unfollow users..
INFO [2018-12-04 20:18:31] [xxx]  Unfollowing the users you are following
INFO [2018-12-04 20:18:57] [xxx]  Total 2 users available to unfollow  ~not found in 'followedPool.csv': 2  |  didn't pass `unfollow_after`: 70
INFO [2018-12-04 20:18:57] [xxx]  Could not grab requested amount of usernames to unfollow:  2/50  ~using available amount
INFO [2018-12-04 20:18:57] [xxx]  Ongoing Unfollow [1/2]: now unfollowing 'b'isiiturriaga''...
INFO [2018-12-04 20:19:04] [xxx]  --> Unfollowed 'isiiturriaga'!
INFO [2018-12-04 20:19:09] [xxx]  Ongoing Unfollow [2/2]: now unfollowing 'b'morteza._zzddss''...
INFO [2018-12-04 20:19:15] [xxx]  --> Unfollowed 'morteza._zzddss'!
INFO [2018-12-04 20:19:25] [xxx]  --> Total people unfollowed : 2

But when I read xxx_followedPool.csv i have 682 users and approximately 350 follow before 2018-12-03 14:03..

Can you said me why i can't unfollow more people? And why when I used allFollowing , Instapy try to search into log file ? I believed this log file xxx_followedPool.csv was only used when you put InstapyFollowed=(True,''all'') parameters. 

Thank you for your answer and advice

**Comment by chamo1116** [comment]
I have the same problem!!!

**Comment by insta783** [comment]
same problem! it doesn't unfollow...
