### ISSUE TITLE
Chromedriver continues to freeze/stall with a blank screen

### ISSUE THREAD

**Issue by anitato** [InstaPy/InstaPy#3499]
I brought this up previously in #3080. @sionking gave me a fix that worked. Subsequent versions of InstaPy fixed this problem. Now I am encountering the exact same issue again where Chromedriver shows a blank screen (and when I use headlessBrowser=True, InstaPy just stalls forever, but does not crash either). Not sure what's going on or why this happens?

Running the most updated version of InstaPy, and Chromedriver 2.44

**Comment by nbgabriel** [comment]
Hello,

Do you try with an older version of chromedriver?.

Are you using proxy?
