### ISSUE TITLE
Error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by lavedi** [InstaPy/InstaPy#350]
Hi, 

I tried to follow all the steps for Centos on digitalocean but this issue has been coming up and have no clue how to fix it? 

Thank you 
<img width="769" alt="screen shot 2017-06-29 at 00 44 23" src="https://user-images.githubusercontent.com/23012560/27665294-461b3100-5c64-11e7-9f82-74a0b79554b0.png">

**Comment by timgrossmann** [comment]
@lavedi It's probably easiest to simply use ubuntu instead of CentOS 😉
