### ISSUE TITLE
Starting QuickStart 

### ISSUE THREAD

**Issue by billygorg2** [InstaPy/InstaPy#3500]
I got a new computer and had to restart the whole software. I can't get past this issue when trying to launch QuickStart.py for the first time. 
<img width="747" alt="screen shot 2018-12-04 at 10 02 02 pm" src="https://user-images.githubusercontent.com/45157401/49488367-5ee68480-f814-11e8-859f-9be2b812c3b7.png">

**Comment by nbgabriel** [comment]
You need to install the module "requests", do you execute "pip install ." ?

**Comment by xerZV** [comment]
SAme, can't start, even can't login. No errors. Just can't start!
