### ISSUE TITLE
ImportError: No module named 'meaningcloud'

### ISSUE THREAD

**Issue by nafferro** [InstaPy/InstaPy#3506]
I'm having this error right now:
ImportError: No module named 'meaningcloud'

even after "python -m pip install meaningcloud-python" or "python3 -m pip install meaningcloud-python" or "pip install meaningcloud-python" or "pip3 install meaningcloud-python" im using raspbian on a raspberry

**Comment by notefortroy** [comment]
Same problem.

**Comment by rakabu** [comment]
pip install MeaningCloud-python

**Comment by nafferro** [comment]
> pip install MeaningCloud-python

same error

**Comment by nafferro** [comment]
quick fix:
open instapy.py
comment line 70 and 71

**Comment by mzparacha** [comment]
I fixed this with pip3 install meaningcloud-python
