### ISSUE TITLE
ImportError: No Module named Requests

### ISSUE THREAD

**Issue by highmountainwoody** [InstaPy/InstaPy#3507]
## Current Behavior
root@instapy:~/InstaPy# python myigname.py
Traceback (most recent call last):
  File "myigname.py", line 21, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 12, in <module>
    import requests
ImportError: No module named requests
## InstaPy configuration
root@instapy:~/InstaPy# pip list
Package                  Version
------------------------ ----------
certifi                  2018.11.29
chardet                  3.0.4
clarifai                 2.4.2
configparser             3.5.0
cryptography             1.7.1
EasyProcess              0.2.3
emoji                    0.5.1
future                   0.17.1
googleapis-common-protos 1.5.5
grpcio                   1.17.0
httplib2                 0.9.2
idna                     2.7
instagram-py             0.0.1
jsonschema               2.6.0
keyring                  10.1
keyrings.alt             1.3
MeaningCloud-python      1.1.1
pip                      18.1
plyer                    1.3.2
protobuf                 3.6.1
pyasn1                   0.1.9
pycrypto                 2.6.1
pycurl                   7.43.0
pygobject                3.22.0
python-apt               1.4.0b3
python-debian            0.1.30
python-debianbts         2.6.1
PyVirtualDisplay         0.2.1
pyxdg                    0.25
regex                    2018.11.22
reportbug                7.1.7
**requests                 2.20.1**
SecretStorage            2.3.1
selenium                 3.141.0
setuptools               33.1.1
six                      1.11.0
urllib3                  1.24.1
wheel                    0.29.0

**Comment by jujuradil56** [comment]
please provide how to use it

because i Beginner :-)
