### ISSUE TITLE
Disable all Likes

### ISSUE THREAD

**Issue by emKaroly** [InstaPy/InstaPy#351]
It is possible to disable all likes?

**Comment by emKaroly** [comment]
Can this be a workaround?
set_dont_like(['#cat'])
like_by_tags(['#cat'], amount=100)

**Comment by timgrossmann** [comment]
@emKaroly This won't work, since dont_like will also prevent commenting and following

**Comment by saurabh-kumar-vit** [comment]
can this be done is we separate out the comment and follow logic from the like logic. It would require a bit of refactoring but seems possible.

**Comment by converge** [comment]
Closing this issue because this feature is already available.
