### ISSUE TITLE
Does anyone tested the Yandex feature?

### ISSUE THREAD

**Issue by amauryleproux** [InstaPy/InstaPy#3515]
## Expected Behavior

Comment only pictures using french description

## Current Behavior

It does not comment on most of the post (who are in English) but it commented on several posts using English or Russian description

## InstaPy configuration

    session.set_use_yandex(enabled=True,
                       API_key='*******',
                       match_language=True,
                       language_code="fr")

    session.set_comments([u'WoW incroyable photo ! :heart_eyes: Les miennes sont moins bonnes :worried:'])

Is it because I use "WoW" / "heart_eyes" and worried inside the set_comment ? Do I need to use only french phrases?

Thank you

**Comment by uluQulu** [comment]
@amauryleproux 
**1**-) 
![image](https://user-images.githubusercontent.com/33269249/49629053-e7297d00-fa00-11e8-81f6-76029e8a8936.png)

Don't expect other features to use it.

**2**-) It is being used only for analyzing the content of **comments** (_read about Interact by Comments feature_).

Don't expect the description of posts to be analyzed by Yandex.

---

>Is it because I use "WoW" / "heart_eyes" and worried inside the set_comment ? Do I need to use only french phrases?

`session.set_comments()` is setting your own comments to be sent on posts, but Text Analytics - **Yandex** and **MeaningCloud** analyzes the comments of other people which are visible on posts.

>Comment only pictures using french description

In future, analyzing the content of the **post descriptions** can be also supported by using already existing text analysis services - **Yandex** and/or **MeaningCloud**.
It's very easy to implement, you can do it, too!

>Does anyone tested the Yandex feature?

Yes, I introduced that feature and I did take several tests (_you read more at #3318, https://github.com/timgrossmann/InstaPy/pull/3318#issuecomment-440474188_).

---

I am not gonna discuss the accuracy of Yandex 😛
I am just thankful that they offer a free plan unlike other 😀 _greedy_ giants.

---

Cheers 😁
---

**Comment by roberterzen** [comment]
This feature seems useless to me since Yandex no longer offer free APIs.
Here is what they say on translate.yandex.com:

> We do not issue free API keys for API Yandex.Translate anymore. To continue with machine translation from Yandex, please use Yandex.Translate service. It supports latest Neural Machine Translation (NMT) technologies and offers better pricing options. Service is available for legal entities worldwide and individuals who are residents of Russian Federation.
> Individuals from other countries may continue with current offer of API Yandex.Translate. To switch to the paid version, please fill out your account information and add funds to your account.
> 

You can buy lowest price package but it will cost you USD 15.00 **per month** for 1 million characters of which you would need a few thousand.
![2020-07-24 15_57_26-Pricing](https://user-images.githubusercontent.com/9428834/88399007-819d2680-cdc6-11ea-8f03-25d139aa9032.jpg)
