### ISSUE TITLE
Worked before, not working again

### ISSUE THREAD

**Issue by joaoleite20** [InstaPy/InstaPy#3516]
## Expected Behavior
Login and start working
## InstaPy configuration
Using Simple interaction (good for new starters).py

Worked before and i didnt change any configuration:

![image](https://user-images.githubusercontent.com/29962600/49595614-455a4f80-f970-11e8-8c0d-d7e609825a31.png)

**Comment by w4ngel** [comment]
@converge I believe you changed this last?

**Comment by lbenassi** [comment]
Same error. Does anyone know how to solve? Thanks

**Comment by Apao123** [comment]
I tried to changed my quickstart.py with only unfollow and the problem was gone. perhaps checkin on how updates and rotate script can works (temporary solution)

**Comment by xerZV** [comment]
SAme, can't start, even can't login. No errors. Just can't start!
