### ISSUE TITLE
Import users from file

### ISSUE THREAD

**Issue by Skygramgr** [InstaPy/InstaPy#3517]
Hello! I've used **.grab_followers()** to make a .json with users I want to follow.
Then, I use **.follow_by_list()** to start follow them...

But if I restart InstaPy it reads the list from the start again!
(they ignore them of course because they're already followed - but need a lot of time for a big list to do this check)
How can I prevent this?
For example, how can I delete a user from the .json file, after is followed? 

```
with open(PATH, "r") as read_file:
    data = json.load(read_file)

session.login()
session.follow_by_list(data, times=1, sleep_delay=600, interact=False)
session.end()
```

**Comment by uluQulu** [comment]
@Skygramgr 

>how can I delete a user from the .json file, after is followed?

Those relationship data files are state-of-time records.
E.g., see a sample filename,
`29-11-2018~full~7663.json`
it is not,
`NotYetFollowedUsers_29-11-2018~full~7663.json`
😁😂

So, how can you achieve the idea?
Maybe one of the simplest way to do it is using the **_followedPool.csv** file to eliminate the already followed users.
So,
```python
# inside quickstart script

from instapy.unfollow_util import set_automated_followed_pool

## some code 

# data_from_json is ready

follow_pool = set_automated_followed_pool(insta_username, None, session.logger, session.logfolder)
already_followed_users = follow_pool["all"].keys()

not_yet_followed_users = [user for user in data_from_json if user not in already_followed_users]
```
Plain and simple.

Yeah, it is just a quick idea to do it.
If you have further considerations, try writing customized code.

---

Cheers 😁
---

**Comment by Skygramgr** [comment]
Thank you...

As I could see, this doesn't delete a user from the followed_pool after being followed, but ignores them without seeing his profile again. So this does what I want finally. But I have another problem.

If it follows a user, unfollow him and try to follow him again, I get of course this warning "USERNAMER has already been followed {} times""
I don't want to navigate to these users again and if it's possible, to delete them from the pool.
What do you suggest?
