### ISSUE TITLE
Feature: Interact with only Private Users

### ISSUE THREAD

**Issue by varun13169** [InstaPy/InstaPy#3519]
Wouldn't it be great to have a tag, `skip_public` similar to `skip_private` in `set_skip_users()` method.
This way script will only interact with the private users and not with public users.

Why this is required?
I have observed that private users have a high tendency to follow-back, irrespective they accept your request or not. Moreover, private users tend to be genuine users and not spam or dead accounts hence getting a follow back from them results into more engagement with content.

Something mentioned in this #1006 but the PR that has been referenced had only `skip_private` #3048

**Comment by lucascaldax** [comment]
Really? I didn't notice this trend. Do you have numbers? A plus with privates, you don't need to spend likes and comments  ( you can't even if you wanted).

**Comment by varun13169** [comment]
@lucascaldax I don't have exact numbers, but while looking at all the follow backs that I got most of them were private(again didn't do any study), as I did unfollow them manually.

Would be nice to have `skip_public` option in place as well.

**Comment by octavius-1** [comment]
I confirm that behavior. Around two years ago I was manually doing this interaction and I noticed it. Apparently users think you're more interested in them when following them in private mode.

**Comment by sionking** [comment]
Those day many private account and fake accounts and it is hard to know it since they are private.
I do 50% public 10% business and 35% private I will analyze the results who follow back and will confirm.

**Comment by varun13169** [comment]
@sionking please let us know about your analysis on the same.

**Comment by msilin** [comment]
please see my solution here https://github.com/timgrossmann/InstaPy/issues/4431#issuecomment-632356545
