### ISSUE TITLE
Whitelist from external file not working

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#3520]
I‘d like to use an external file for my whitelist. However, when I move my whitelist to users.txt, it will be ignored by instapy. Anybody has an idea what is wrong with my code?

```
from instapy import InstaPy
users = open('users.txt', 'rb')

myfollowerlist = users.read().decode()

InstaPy(username='user',password='Password',headless_browser=True)\
  .login()\
  .set_dont_include(myfollowerlist)\
  .unfollow_users(amount=500, allFollowing=True, style="FIFO", sleep_delay=400)\
  .end()

users.close()
```

users.txt is something like
```
['user1', 'user2', 'user3', 'user4', '…']
``` 

## Expected Behavior
It should work like if the list is included directly in the python file

## Current Behavior
When I `print (myfollowerlist)` I get the result as expected, but the list is ignored by InstaPy

**Comment by octavius-1** [comment]
That's because you're not saving the users as a list. 
Try using something like
users =open('users.txt', 'r')
user_list = users.readlines()
(Maybe some \r\n characters are going to be save into that list too, just ensure to cut them off)

**Comment by tibor** [comment]
@octavius-1 that worked, many thanks!
