### ISSUE TITLE
This my Problem on windows 10

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#3521]
Traceback (most recent call last):
  File "dam.py", line 3, in <module>
    from instapy import InstaPy
  File "C:\Users\Xham\Desktop\InstaPy\instapy\__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "C:\Users\Xham\Desktop\InstaPy\instapy\instapy.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by johnvfitness** [comment]
Writing C:\Users\Xham\AppData\Local\Temp\easy_install-fl09wyp1\regex-2018.11.22\setup.cfg
Running regex-2018.11.22\setup.py -q bdist_egg --dist-dir C:\Users\Xham\AppData\Local\Temp\easy_install-fl09wyp1\regex-2018.11.22\egg-dist-tmp-1exhf0fu
error: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

C:\Users\Xham\Desktop\InstaPy>

**Comment by converge** [comment]
hey mate, have a look:
https://github.com/timgrossmann/InstaPy/search?q=ModuleNotFoundError%3A+No+module+named+%27requests%27&type=Issues

**Comment by johnvfitness** [comment]
Thx Bro it's good :)
