### ISSUE TITLE
We need to skip interaction with private users (No photos are displayed)

### ISSUE THREAD

**Issue by octavius-1** [InstaPy/InstaPy#3522]
## Expected Behavior
Everytime a private user profile is opened, we should skip looking for pictures to like (because there are none), when trying to get the post URL, the friend suggestion username URL is being shown instead.

**Comment by sionking** [comment]
I think I did add this check (private and not follwoing == don't look) but it might have a bug I need to PR.

**Comment by octavius-1** [comment]
@sionking Thank you! Could you please let me know any update?

**Comment by Ualas** [comment]
@octavius-1 Do you know if this issue has been fixed?
