### ISSUE TITLE
Having a 24/7 bot with quota supervisor

### ISSUE THREAD

**Issue by tjuzen** [InstaPy/InstaPy#3525]
Hey guys!

The bot is working like a charm on my raspberry pi, running 24/7 with the quota supervisor.
My problem is : it will unfollow only when I launch it, then like/interact and when the hourly limit is reached sleep for a while, then go back to interact! 
But I would like it to unfollow before going back to interaction.
Anyone could help me? ;)

  ```
session.set_quota_supervisor(enabled=True, sleep_after=["likes_h", "follows_h", "unfollows_h", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=False,
                              peak_likes=(35, 850),
                                peak_follows=(5, None),
                                 peak_unfollows=(32, 505),
                                  peak_server_calls=(random.randint(475, 525), None))

    session.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')
    session.set_do_follow(enabled=True, percentage=20)
    session.set_do_like(enabled=True, percentage=100)

    # activity
    session.unfollow_users(amount=random.randint(75,150), InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=48*60*60, sleep_delay=501)
    session.like_by_tags(like_tag_list, amount=(140), interact=True)
    session.follow_likers (['' , ''], photos_grab_amount = 15, follow_likers_per_photo = 3, randomize=True, sleep_delay=600, interact=True)
```

Thanks a lot :)

**Comment by Mehran** [comment]
as I understand your mean(Think), you Can't do this with on the same file. if you need this Task better you remove `unfollow `from this file and Create a new file for Just `unfollowing`.

**Comment by tjuzen** [comment]
nice, I didnt know I could have 2 bots running for 1 account!

**Comment by iPhra** [comment]
@EMYULT How did you run it on the Pi? I'm having troubles with Selenium, i think it's because i don't have Chrome on the PI

**Comment by Madgeniusblink** [comment]
> as I understand your mean(Think), you Can't do this with on the same file. if you need this Task better you remove `unfollow `from this file and Create a new file for Just `unfollowing`.

How would this work? is there any example I can take a look at?

**Comment by xerZV** [comment]
@EMYULT Can you share with us your config for 24/7 ?

**Comment by c0d3x27** [comment]
> nice, I didnt know I could have 2 bots running for 1 account!

you have 2 bots running one account?! can you tell us how please? thank you

**Comment by tE3m** [comment]
@Banginpadr simply start two scripts with the same login data?

**Comment by xerZV** [comment]
@EMYULT Can you share with us your config for 24/7 ?

**Comment by xerZV** [comment]
Anyone?

**Comment by tE3m** [comment]
@xerZV simply put it in an infinite loop, that'll make it run nonstop. But if you run 24/7 I'd recommend you use `Quota Supervisor`.

**Comment by xerZV** [comment]
Can someone share with us some 24/7 config with quota supervisor

**Comment by tE3m** [comment]
@xerZV dude did you read my message? Btw, there are 24/7 scripts <a href="https://github.com/timgrossmann/InstaPy/tree/master/quickstart_templates">here</a>.

**Comment by tourhuntr** [comment]
> Can someone share with us some 24/7 config with quota supervisor

while True:
    session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

    with smart_run(session):
        # general settings
        session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                      max_followers=15000,
                                      max_following=1500,
                                      min_followers=0,
                                      min_following=30)
        session.set_quota_supervisor(enabled=True,sleep_after=["likes"], sleepyhead=True, stochastic_flow=True, notify_me=True,peak_likes=(57, 700), peak_follows=(48, None), peak_unfollows=(35, 402), peak_server_calls=(500, None))
        #session.set_user_interact(amount=3, randomize=False, percentage=100, media='Photo')
        session.set_do_like(enabled=True, percentage=100)
        #session.set_do_comment(enabled=True, percentage=5)
        #session.set_comments(['Nice shot! @{}', 'I love your profile! @{}', '@{} Love it!', '@{} :heart::heart:',
        #                        '@{}:revolving_hearts::revolving_hearts:', '@{}:fire::fire::fire:'], media='Photo')

        # unfollow activity
        #session.unfollow_users(amount=500, InstapyFollowed = (True, "all"), style="FIFO", unfollow_after=36*60*60, sleep_delay=300)

        # like activity
        ammount_number=100
        session.set_user_interact(amount=5, randomize=False, percentage=50, media='Photo')
        #session.set_do_follow(enabled=True, percentage=70)
        #session.set_do_like(enabled=True, percentage=70)
        #session.set_do_comment(enabled=True, percentage=30)
        session.interact_user_followers(['xxx'], amount=ammount_number, randomize=True)
    session.end()

**Comment by c0d3x27** [comment]
> > Can someone share with us some 24/7 config with quota supervisor
> 
> while True:
> session = InstaPy(username=insta_username,
> password=insta_password,
> headless_browser=True,
> multi_logs=True)
> 
> ```
> with smart_run(session):
>     # general settings
>     session.set_relationship_bounds(enabled=True,
>                                   delimit_by_numbers=True,
>                                   max_followers=15000,
>                                   max_following=1500,
>                                   min_followers=0,
>                                   min_following=30)
>     session.set_quota_supervisor(enabled=True,sleep_after=["likes"], sleepyhead=True, stochastic_flow=True, notify_me=True,peak_likes=(57, 700), peak_follows=(48, None), peak_unfollows=(35, 402), peak_server_calls=(500, None))
>     #session.set_user_interact(amount=3, randomize=False, percentage=100, media='Photo')
>     session.set_do_like(enabled=True, percentage=100)
>     #session.set_do_comment(enabled=True, percentage=5)
>     #session.set_comments(['Nice shot! @{}', 'I love your profile! @{}', '@{} Love it!', '@{} :heart::heart:',
>     #                        '@{}:revolving_hearts::revolving_hearts:', '@{}:fire::fire::fire:'], media='Photo')
> 
>     # unfollow activity
>     #session.unfollow_users(amount=500, InstapyFollowed = (True, "all"), style="FIFO", unfollow_after=36*60*60, sleep_delay=300)
> 
>     # like activity
>     ammount_number=100
>     session.set_user_interact(amount=5, randomize=False, percentage=50, media='Photo')
>     #session.set_do_follow(enabled=True, percentage=70)
>     #session.set_do_like(enabled=True, percentage=70)
>     #session.set_do_comment(enabled=True, percentage=30)
>     session.interact_user_followers(['xxx'], amount=ammount_number, randomize=True)
> session.end()
> ```

wtf for real? all you have to do was make a loop? using while? crazy. will this work using docker too? like if i add while true, will the container start again automatically once it reach the goal i set for it?

**Comment by tourhuntr** [comment]
yes, it does exactly so.
