### ISSUE TITLE
error: idna 2.8 is installed but idna<2.8,>=2.5 is required by {'requests'}

### ISSUE THREAD

**Issue by contino23** [InstaPy/InstaPy#3526]
Hi, 
I see this kind of error when I'm trying to do py setup.py install 

"error: idna 2.8 is installed but idna<2.8,>=2.5 is required by {'requests'} "

How I can solve this?

Thanks

**Comment by francescolorenzo96** [comment]
Same issue here, and if i run it i get an exception when i import requests.
