### ISSUE TITLE
Worked and now doesnt

### ISSUE THREAD

**Issue by wemakefuture** [InstaPy/InstaPy#353]
Hey, 

it was working perfectly but since two days i get this error. 

![screenshot_20170629-123430](https://user-images.githubusercontent.com/28114725/27684161-06a98ffc-5cc9-11e7-9de9-d9fafa445a0f.png)

Sorry for asking but has anyone a clue? 

thanks

**Comment by AlainPilon** [comment]
Please, use the search, took me 3 seconds: https://github.com/timgrossmann/InstaPy/issues/344

**Comment by timgrossmann** [comment]
`git pull`
