### ISSUE TITLE
Is there functionality to get the amount of likes a post has?

### ISSUE THREAD

**Issue by SMarcinno** [InstaPy/InstaPy#3534]
I am currently working on a little statistic util for myself (if there is interest I could do a merge request..).
saving stats like Followercount, Followingcount, post count is working. Now I want to save the engagement rate for the last 10 posts. I cannot find a function returning how many likes one post has. Either I am blind or there is none?

would be nice if someone could help me

**Comment by converge** [comment]
join me: https://github.com/converge/instapy-dashboard

**Comment by SMarcinno** [comment]
> join me: https://github.com/converge/instapy-dashboard

I have something else in mind honstly.. i changed the instaPy.db and right now my server is accessing my page every day to save the follower, follows and so on. I then will create reports with python later on. My next step is to calculate the engagement-rate thats why i posted this question

**Comment by converge** [comment]
sounds good.
take a look: https://github.com/timgrossmann/InstaPy/pull/3531
