### ISSUE TITLE
follow_user_followers(), script stops with error after some minutes 

### ISSUE THREAD

**Issue by nkdsoft** [InstaPy/InstaPy#3535]
## Current Behavior
After running follow_user_followers(), the script starts working normally for some minutes but then stops with the following error:

File "../instapy/unfollow_util.py", line 1152, in unfollow_user
 post_unfollow_cleanup("successful", username, person, relationship_data, logger, logfolder)
TypeError: post_unfollow_cleanup() missing 1 required positional argument: 'logfolder'

**Comment by jtrieuDev** [comment]
Hi, I have almowt the same bug but it says:

"Unfollow loop error:  post_unfollow_cleanup() takes exactly 7 arguments (6 given)
"

**Comment by nkdsoft** [comment]
It is in fact a bug in the script. I solved my issue by changing line 1152 of unfollow_util.py to:
   ` post_unfollow_cleanup("successful", username, person, relationship_data, person_id, logger, logfolder)`

(person_id parameter was missing)

**Comment by nkdsoft** [comment]
Pull request #3539 sent with this fix

**Comment by axlright** [comment]
Thanks @nkdsoft for the solution - confirm working for me.

**Comment by sionking** [comment]
Sorry for that. How can code check not found it?
