### ISSUE TITLE
Get followers biography

### ISSUE THREAD

**Issue by aorzh** [InstaPy/InstaPy#3536]
Hi there!
Just a quick question.
On https://www.instagram.com/saints/?__a=1 I see 
`"graphql": {
		"user": {
			"biography": "The Official Instagram of the New Orleans Saints! #Saints #NOLA #SaintsGameday",
			"blocked_by_viewer": false,
			"country_block": false,
			"external_url": "http://www.nfl.com/probowl/ballot?team=NO",
			...`

Is there any way to get biography of some user?

**Comment by converge** [comment]
yes, you just have to navigate in the JSON object

**Comment by aorzh** [comment]
@converge , but how I can do it with InstaPy? Just can't find it in code and docs (maybe looking in wrong place)

**Comment by sionking** [comment]
This is API call don't use it.

**Comment by CharlesCCC** [comment]
@aorzh Best place to start is using Chrome go to somebody's profile page, and then F12(Windows) to open developer tool, then you should able to find the corresponding JSON regarding to user's profile info.

**Comment by aorzh** [comment]
@CharlesCCC , I don't think so. I need bio from 1 million followers, so there is any endpoint for getting users bio?

**Comment by CharlesCCC** [comment]
@aorzh no, i didn't meant to ask you go through those manually, (that will be stupid, isn't it). 
I'm telling you where you can find the JSON you need and then use the python program(either write your own or modify InstaPy) to server the purpose.
