### ISSUE TITLE
Issue during Unfollow Non-Followers action

### ISSUE THREAD

**Issue by cormo1990** [InstaPy/InstaPy#3546]
Hello friends,
I noticed this issue during the action "Unfollow Non-Followers". it happens only with this task, Unfollow general works.

INFO [2018-12-11 00:51:03] [XXX]  Ongoing Unfollow [2/1000]: now unfollowing 'b'YYYYYY''...
ERROR [2018-12-11 00:51:57] [XXX]  --> Unable to detect the following status of 'b'YYYYYY''!
WARNING [2018-12-11 00:51:57] [XXX]  The page isn't available!	~the link may be broken, or the page may have been removed...
WARNING [2018-12-11 00:51:57] [XXX]  Maybe 'b'YYYYYY'' has changed the username!	~verifying through the user ID
INFO [2018-12-11 00:51:57] [XXX]  Trying to find the username from the given user ID by loading a post
INFO [2018-12-11 00:51:59] [XXX]  Profile with ID 8556868319: no pics found
INFO [2018-12-11 00:51:59] [XXX]  Trying to find the username from the given user ID by a quick API call
ERROR [2018-12-11 00:52:00] [XXX]  Unfollow loop error:  Expecting value: line 1 column 1 (char 0)

INFO [2018-12-11 00:52:00] [XXX]  --> Total people unfollowed : 1

@uluQulu @sionking any suggestion?
thanks a bunch

**Comment by AdamMoffitt** [comment]
Having the same issue. Would love some help!

**Comment by ortegafernando** [comment]
SAme as [https://github.com/timgrossmann/InstaPy/issues/3523](https://github.com/timgrossmann/InstaPy/issues/3523)

**Comment by uluQulu** [comment]
Hi @cormo1990 
Actually, if you pull the upstream, you unlikely will encounter that problem.

The method of finding the username from the given user ID by a quick API call currently is unavailable and @sionking recently commented out that defected block at 58dd868c16366aa16b9945e12c7a018a7b11cad4.


---

Cheers 😁
---
