### ISSUE TITLE
Unfollow allFollowing appears to not find any users

### ISSUE THREAD

**Issue by alxhoff** [InstaPy/InstaPy#3547]
## Expected Behavior
Unfollow all users older than 2 days
## Current Behavior
Unfollowing none

## InstaPy configuration
`session.unfollow_users(amount=args.extra, allFollowing=True, style="FIFO", sleep_delay=60*10, unfollow_after=48*60*60)`

For a week or so now this unfollow action has stopped working. I am not sure why exactly as there should be hundreds and hundreds of people to unfollow. Log gives

> INFO [2018-12-11 11:11:38] [XXX]  Total 0 users available to unfollow  ~not found in 'followedPool.csv': 0  |  didn't pass `unfollow_after`: 216

Cheers

**Comment by felipefontoura** [comment]
Settings:

```python
session.unfollow_users(amount=500,
                           allFollowing=True,
                           style="LIFO",
                           unfollow_after=None,
                           sleep_delay=5*60)
```

Following the error log:

```
INFO [2018-12-11 17:49:22] []  Unfollowing the users you are following
ERROR [2018-12-11 17:49:49] []  Sorry, an error occurred: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"}
  (Session info: headless chrome=69.0.3497.100)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.19.8-arch1-1-ARCH x86_64)
```
