### ISSUE TITLE
InstaPy 24/7 is not cycling

### ISSUE THREAD

**Issue by elricmarci** [InstaPy/InstaPy#3548]
Hi All,

I'm tring to use InstaPy in my PI 3+.
But i meet some problems.

**_Here my quickstart.py:_**
""" Quickstart script for InstaPy usage """
from instapy import InstaPy
from instapy.util import smart_run

insta_username = ''
insta_password = ''

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)
with smart_run(session):
    """ Activity flow """

    session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=45900,
                                        min_followers=45,
                                        min_following=77)
    
    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])
    
    session.like_by_tags(["fineartphotography"], amount=10)

But after 10 likes, i receive the message **Session ended!**

![rasp](https://user-images.githubusercontent.com/43813821/49806235-76af9280-fd57-11e8-88ee-3cc34667e998.PNG)

Any way to create a cycle in the loop?

Thanks a lot

**Comment by tjuzen** [comment]
amount=10 means youll like 10 publications. add more tags for a 24/7, id say at least 5.
and increase the amount

**Comment by elricmarci** [comment]
> amount=10 means youll like 10 publications. add more tags for a 24/7, id say at least 5.
> and increase the amount

Do you mean, to duplicate activity lines like below?

    session.like_by_tags(["fineartphotography"], amount=10)
    session.like_by_tags(["fineartphotography"], amount=10)
    session.like_by_tags(["fineartphotography"], amount=10)
    session.like_by_tags(["fineartphotography"], amount=10)
    session.like_by_tags(["fineartphotography"], amount=10)
    session.like_by_tags(["fineartphotography"], amount=10)
    session.like_by_tags(["fineartphotography"], amount=10)
    session.like_by_tags(["fineartphotography"], amount=10)
    session.like_by_tags(["fineartphotography"], amount=10)
    session.like_by_tags(["fineartphotography"], amount=10)
    session.like_by_tags(["fineartphotography"], amount=10)
    session.like_by_tags(["fineartphotography"], amount=10)

**Comment by lucascaldax** [comment]
D;    Something like: session.like_by_tags(["fineartphotography","anotherone","anotherone","anotherone","anotherone","anotherone","anotherone","anotherone"], amount=50)

**Comment by elricmarci** [comment]
> D; Something like: session.like_by_tags(["fineartphotography","anotherone","anotherone","anotherone","anotherone","anotherone","anotherone","anotherone"], amount=50)

I'm trying, but i'm receiving the following error:

```
INFO [2018-12-12 10:12:24] Insufficient amount of links ~ trying again: 1
INFO [2018-12-12 10:12:51] Insufficient amount of links ~ trying again: 2
INFO [2018-12-12 10:13:16] Insufficient amount of links ~ trying again: 3
INFO [2018-12-12 10:13:19] Cor! Did you send too many requests? ~ let's rest some
```

**Comment by SMarcinno** [comment]
I do this:
`session.like_by_tags(sample(tags, 5), amount= 4)`

`sample(tags, 5)`  returns 5 random tags from my big array. (Class has to be imported --> `from  random import sample`)
and the `amount = 4` results in 4 likes every tag (5 in my case)
