### ISSUE TITLE
VNC viewer

### ISSUE THREAD

**Issue by gHashTag** [InstaPy/InstaPy#3549]
How to open a docker on a Mac?

## Expected Behavior
I want to see the logs

This description from the documentation is not clear:
- Install VNC viewer if you do not have one. 
- Run your VNC viewer, and type address and port localhost:5900. The password is secret.

Need to open this link?
vnc://localhost:5900

Where to get the secret?

## InstaPy configuration
default

**Comment by ramseys1990** [comment]
So what's your question? How to open a docker on Mac? What's the "secret? How to view the logs? Or what?

**Comment by gHashTag** [comment]
password === secret
