### ISSUE TITLE
Failed to get followers count of user

### ISSUE THREAD

**Issue by przemmaj** [InstaPy/InstaPy#3552]
## Expected Behavior

Unfollowing all followers from user list 

## Current Behavior

Failed to get followers count of 'USER'  ~empty list

## InstaPy configuration

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,nogui=True)

with smart_run(session):
    session.unfollow_users(amount=40, allFollowing=True, style="RANDOM", unfollow_after=None, sleep_delay=450)

**Comment by JoeFertig** [comment]
Same here
