### ISSUE TITLE
Skip Ahead when Collecting Users to Interct with

### ISSUE THREAD

**Issue by qwerty14022** [InstaPy/InstaPy#3553]
Hi, just wondering if there is a way to skip ahead on the list when using the Interact with a User's Followers feature. For example, if I wanted to work through an account with a large following, I don't want to keep interacting with the same users every time that are at the top of the list when it pulls up the followers list.

Is there a feature to continue where you left off interacting with a user's followers?
## Expected Behavior
To continue interacting where it last left off on the list of followers.
## Current Behavior
Grab list of followers and interact with the same people do to them being at the top of the list.
## InstaPy configuration

    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=4590,
                                        min_followers=20,
                                        min_following=31)

    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])
    session.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')
    session.set_do_follow(enabled=False, percentage=0)
    session.set_do_like(enabled=True, percentage=100)
    session.set_comments(["Cool", "Super!"])
    session.set_do_comment(enabled=False, percentage=0)

    # activity
    session.interact_user_followers(['natgeo'], amount=221, randomize=True)

**Comment by sionking** [comment]
grab followers with graphql, scrolling is lame :)

**Comment by qwerty14022** [comment]
> 
> 
> grab followers with graphql, scrolling is lame :)

Ohh could you explain this a bit more to me? Thank you for the response haha
