### ISSUE TITLE
Issues with “loop”

### ISSUE THREAD

**Issue by Frikkifrik** [InstaPy/InstaPy#3554]
I’ve created my instapy and its working very well, although while researching how to make it loop the script, I’ve hit dead ends all the time. Is anyone willing to help?

**Comment by elricmarci** [comment]
I'm in the same situation.

After the "X" amount per hashtag i'll receive the message Session ended.

Here my topic [3548](https://github.com/timgrossmann/InstaPy/issues/3548)

Maybe can help.
