### ISSUE TITLE
Cookie file not found, creating cookie...

### ISSUE THREAD

**Issue by mauromaiani** [InstaPy/InstaPy#3562]
**Hi, I was using python correctly and suddenly this error started.
I do not know what is happening? Can you help me?
Look for solutions to the same problem and I could not solve mine.
I do not have experience as a programmer!
Thank you!**

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-12-12 21:26:10] [xxxxxxxxxxx]  Session ended - 2018-12-12 21:26:10
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "uruguay.py", line 25, in <module>
    session.login()
  File "/Users/mauro/InstaPy/instapy/instapy.py", line 350, in login
    self.bypass_suspicious_attempt):
  File "/Users/mauro/InstaPy/instapy/login_util.py", line 162, in login_user
    "//form/span/button[text()='Log in']")
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 393, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 966, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5),platform=Mac OS X 10.13.6 x86_64)

**Comment by cormo1990** [comment]
Try to delete your cookie file and restart InstaPy.

your cookie file is located in InstaPy-master/logs/username/**username_cookie.pkl**

**Comment by mauromaiani** [comment]
Thanks forma the help.

I already deleted my cookies, and didn't work.

How can I restart instapy?

**Comment by anilgurses** [comment]
I am getting the same error. I guess it is related to html tag. It doesn't locate the log in button.

**Comment by mauromaiani** [comment]
You make it work with that?
How you can locate the log?

**Comment by taibhse-designs** [comment]
having the same error, a script that worked over a week ago now no longer works despite nothing having changed in the script, instapy or the system, anyone know how to fix this?

**Comment by anilgurses** [comment]
Just reinstall the instapy. That will resolve that problem. Also, ensure that you are using the latest version of chromedriver. This issue could be closed.

**Comment by mauromaiani** [comment]
> Just reinstall the instapy. That will resolve that problem. Also, ensure that you are using the latest version of chromedriver. This issue could be closed.

Thanks! i did that and it working!
