### ISSUE TITLE
Automated dependency installation

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#3568]
#### In order to at one point be able to do a simple setup of the whole InstaPy environment,  we need to have a "one click" or "one command" dependency installation

Advantages of this feature:
- Users won't need to install the dependencies themselves which would remove most of the problems of `module not found error`

Possible ways of achieving this while keeping control:
- Setup scripts for each platform that can be triggered by a simple "double click"
- Setup of dependencies when first starting InstaPy with a pre-step before doing the interactions
- Might be unnecessary due to #3569 

> [Bountysource this Issue](https://www.bountysource.com/issues/67477830-automated-dependency-installation)

--- 

###### Feel free to comment with adjustments and improvements

**Comment by Mehran** [comment]
I just created myself easy installation, I did it just by one command , maybe interest 

`curl -s https://gist.github.com/Mehran/970a4a6a705f5898ca465312e785f8f4#file-instapy-easy-sh | sh`

**Comment by jaimergp** [comment]
Have you considered using `conda` and `constructor`? It can produce self-contained `*.sh` installers for Linux/MacOS and `*.exe` for Windows.

https://github.com/conda/constructor

**Comment by timgrossmann** [comment]
@jaimergp This looks damn sexy! Thank you very much for communicating this, we'll definitely have to look into this.

Happy New Year 🙌

**Comment by jaimergp** [comment]
@timgrossmann 

Cool! If you need some help let me know!

**Comment by timgrossmann** [comment]
@jaimergp Thank you, we always appreciate great people contributing to InstaPy!
Did you already join the discord channel in the Readme? 😉 

Feel free to create a `constructor.yaml` file for InstaPy and test around a little bit if you're interested and have some time to spare, we'd really appreciate it.

**Comment by timgrossmann** [comment]
Will be solved by @uluQulu through #3569

**Comment by jaimergp** [comment]
Ok, @timgrossmann! I am sorry but I did not receive a notification of your comment edition, so I wasn't aware of your request. Glad @uluQulu is handling that, though.

**Comment by timgrossmann** [comment]
@jaimergp No worries, still thank you very much for the recommendation.
Maybe at one point you're interested in one part of InstaPy and are able to contribute there :v:

**Comment by timgrossmann** [comment]
#3887
