### ISSUE TITLE
The clarafi module. How can i use it for profile pic?

### ISSUE THREAD

**Issue by aReaSa** [InstaPy/InstaPy#357]
Hi everbody 
i have been use instapy for long time. and i am happy with it (thank you timgrossmann bytheway)

but i've a question for you

i wanna check the user profile pics. how can i do that?

thank you for answering 

regards..

**Comment by timgrossmann** [comment]
@aReaSa Unfortunately at the moment you can't.
This feature has not been added.

What would be the use case of this?

**Comment by aReaSa** [comment]
@timgrossmann i wanna check real person from profile pic. (by clarafai)

as you know there are alot of pages instagram...

**Comment by saurabh-kumar-vit** [comment]
So you wish to know wether the user corresponding to the current image is that of a real person and not to any organization/page etc.
And for doing this you are suggesting that we use clarafai for recognizing if the profile picture has a person in it or not.
What if the picture does not contain any person (lets say a dog, or a house) wouldn't it be misclassified  as a page?

Can you give us a better understanding of why you require this feature?

**Comment by jaredl531** [comment]
Hey @aReaSa - I made a tool during one of our internal hackathons that you might be interested in:

http://shouldimakethismyprofilepicture.com/

Checks for people, nudity, resolution, etc. And also for real people, not just celebrities.
