### ISSUE TITLE
windows.ps1 Issues

### ISSUE THREAD

**Issue by sonnyobrien** [InstaPy/InstaPy#358]
### After running windows.ps1 I receive some errors in red. Was this run successfully?
```
Security Warning
Run only scripts that you trust. While scripts from the Internet can be useful,
 this script can potentially harm your computer. Do you want to run
C:\Users\Sonny\Desktop\InstaPy-master\scripts\windows.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): y
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): r
InstaPy Windows Setup
===============================================================================
==============
Installing Selenium
Requirement already satisfied: selenium in c:\program files\python36-32\lib\site
-packages
Requirement already satisfied: pyvirtualdisplay in c:\program files\python36-32\
lib\site-packages
Requirement already satisfied: EasyProcess in c:\program files\python36-32\lib\s
ite-packages (from pyvirtualdisplay)
C:\Program Files\Python36-32\python.exe: can't open file 'get-pip.py': [Errno 2]
 No such file or directory

Installing GUI Tool
_Move-Item : Cannot create a file when that file already exists.
At C:\Users\Sonny\Desktop\InstaPy-master\scripts\windows.ps1:11 char:3
+ mv <<<<  "$pwd\InstaPy-GUI.exe" "$pwd\..\InstaPy-GUI.exe"
    + CategoryInfo          : WriteError: (C:\Windows\system32\InstaPy-GUI.exe
   :FileInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveFileInfoItemIOError,Microsoft.PowerShell.Com
   mands.MoveItemCommand_


Downloading Chrome Driver...
Chrome Driver download completed.

Unzipping Chrome Driver...
You cannot call a method on a null-valued expression.
At C:\Users\Sonny\Desktop\InstaPy-master\scripts\windows.ps1:24 char:42
+ $shell.Namespace("$pwd\assets\").copyhere <<<< ($item)
    + CategoryInfo          : InvalidOperation: (copyhere:String) [], RuntimeE
   xception
    + FullyQualifiedErrorId : InvokeMethodOnNull

Move-Item : Cannot find path 'C:\Windows\assets\chromedriver.exe' because it do
es not exist.
At C:\Users\Sonny\Desktop\InstaPy-master\scripts\windows.ps1:26 char:3
+ mv <<<<  "$pwd\assets\chromedriver.exe" "$pwd\assets\chromedriver"
    + CategoryInfo          : ObjectNotFound: (C:\Windows\assets\chromedriver.
   exe:String) [Move-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveI
   temCommand

Unzipping completed.

Removing unneeded files...
Removal completed.

C:\Program Files\Python36-32\python.exe: can't open file 'setup.py': [Errno 2] N
o such file or directory
Setup is completed.
The term 'pause' is not recognized as the name of a cmdlet, function, script fi
le, or operable program. Check the spelling of the name, or if a path was inclu
ded, verify that the path is correct and try again.
At C:\Users\Sonny\Desktop\InstaPy-master\scripts\windows.ps1:35 char:6
+ pause <<<<
    + CategoryInfo          : ObjectNotFound: (pause:String) [], CommandNotFou
   ndException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Windows\system32>

**Comment by timgrossmann** [comment]
@sonnyobrien Please try to `git clone` the repository again on a different place and try the setup again. This looks like you somehow already did some of the steps.
Thank you

**Comment by Suppnkasper** [comment]
![unbenannt](https://user-images.githubusercontent.com/29818783/27763461-56f29d8e-5e84-11e7-8722-7b06a3b426bb.PNG)
Hi,

i get the errors too! 
I have tryed it also on a Virtual Machine with a brand new Windows 7. 
I downloaded and unzipped the Files. I set the system Enviroment variables and run the Powershell as Administrator 

PS C:\Windows\system32> E:\InstaPy-master\InstaPy-master\scripts\windows.ps1
InstaPy Windows Setup
=============================================================================================
Installing Selenium
Collecting selenium
  Using cached selenium-3.4.3-py2.py3-none-any.whl
Installing collected packages: selenium
Successfully installed selenium-3.4.3
Collecting pyvirtualdisplay
  Using cached PyVirtualDisplay-0.2.1.tar.gz
Collecting EasyProcess (from pyvirtualdisplay)
  Using cached EasyProcess-0.2.3.tar.gz
Installing collected packages: EasyProcess, pyvirtualdisplay
  Running setup.py install for EasyProcess: started
    Running setup.py install for EasyProcess: finished with status 'done'
  Running setup.py install for pyvirtualdisplay: started
    Running setup.py install for pyvirtualdisplay: finished with status 'done'
Successfully installed EasyProcess-0.2.3 pyvirtualdisplay-0.2.1
py.exe : C:\Program Files (x86)\Python36-32\python.exe: can't open file 'get-pip.py': [Errno 2] No such file or directory
Bei E:\InstaPy-master\InstaPy-master\scripts\windows.ps1:6 Zeichen:3
+ py <<<<  get-pip.py
    + CategoryInfo          : NotSpecified: (C:\Program File...le or directory:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
 
Installing GUI Tool
Move-Item : Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist.

Bei E:\InstaPy-master\InstaPy-master\scripts\windows.ps1:11 Zeichen:3
+ mv <<<<  "$pwd\InstaPy-GUI.exe" "$pwd\..\InstaPy-GUI.exe"
    + CategoryInfo          : WriteError: (C:\Windows\system32\InstaPy-GUI.exe:FileInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveFileInfoItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
 
 
Downloading Chrome Driver...
Chrome Driver download completed.
 
Unzipping Chrome Driver...
Sie können keine Methode für einen Ausdruck mit dem Wert NULL aufrufen.
Bei E:\InstaPy-master\InstaPy-master\scripts\windows.ps1:24 Zeichen:42
+ $shell.Namespace("$pwd\assets\").copyhere <<<< ($item)
    + CategoryInfo          : InvalidOperation: (copyhere:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Move-Item : Der Pfad "C:\Windows\assets\chromedriver.exe" kann nicht gefunden werden, da er nicht vorhanden ist.
Bei E:\InstaPy-master\InstaPy-master\scripts\windows.ps1:26 Zeichen:3
+ mv <<<<  "$pwd\assets\chromedriver.exe" "$pwd\assets\chromedriver"
    + CategoryInfo          : ObjectNotFound: (C:\Windows\assets\chromedriver.exe:String) [Move-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand
 
Unzipping completed.
 
Removing unneeded files...
Removal completed.
 
python.exe : C:\Program Files (x86)\Python36-32\python.exe: can't open file 'setup.py': [Errno 2] No such file or directory
Bei E:\InstaPy-master\InstaPy-master\scripts\windows.ps1:33 Zeichen:7
+ python <<<<  setup.py install
    + CategoryInfo          : NotSpecified: (C:\Program File...le or directory:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Setup is completed.

**Comment by onyxim** [comment]
Try to [run with new docker micro services](https://github.com/timgrossmann/InstaPy#running-with-docker-microservices-manual). It completely solves all environment problems.
