### ISSUE TITLE
End Python 2.7 support

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#3580]
#### Always covering both versions is not necessary once we have an easier setup for InstaPy.

Advantages of this feature:
- Less issues with incompatible code and library versions
- Less code overhead or edge cases

Possible ways of achieving this while keeping control:
- After first release, slowly start removing Python2.7 specific code

> [Bountysource this Issue](https://www.bountysource.com/issues/67497353-end-python-2-7-support)

--- 

###### Feel free to comment with adjustments and improvements

**Comment by JoeFertig** [comment]
Hello Tim!
I have a lot of problems switching InstaPy from python2.7 to python3 on a Rasp Pi 3b+.
If we do this change we need to release a nice virtualenv manual to do so.
Just my 2 cents :)

**Comment by timgrossmann** [comment]
@JoeFertig That is really good to know, thank you very much for noting this!
I'm was not aware of this problems, since I'm not working with Pis anymore.

That's exactly the reason why we need the community in this 😉

**Comment by flackoon** [comment]
Hey, @timgrossmann 
Can you please take a look at this thread [#3573](https://github.com/timgrossmann/InstaPy/issues/3573)
I see that you opened a lot of feature request topics and somehow the problems of the community are left unnoticed.

Thank you

**Comment by uluQulu** [comment]
Hey @timgrossmann 
I see lots of good ideas and goals in your newly opened threads.

For this one, I really am not looking warm cos python portability is a strength of **InstaPy** or any other [python] application.
E.g., it is one of the reasons I chose InstaPy at the very early stage.
Yet I understand that lots of pro-coders do not like this style for some reasons, but I wish **InstaPy** can remain python portable as much possible.

And being very familiar to the InstaPy source code, I can say that we really have so less old code handlers and I don't find it a [big] problem to write a smooth portable code which also is kind of challenging 🙂

---

It's just my quick thoughts. I mean, maybe you have other ideas at higher priority in mind that I am unaware of to demand the retirement of old code.

---
_BTW if those issues has a _bounty_ on them, adding a `bounty` label will increase engagement_ 😋

Cheers 😁
---

<sub>By python portability I don't mean support for quite old and unused versions like `3.1`, `3.3` or `2.7.1`, but rather, I mean active up-to-date versions in use.</sub>

**Comment by JoeFertig** [comment]
I finally managed to do a fresh InstaPy installation on a new Raspberry Pi3b+ and run InstaPy with python2.7 and python3.5.
Holy moly that was tricky. In theory it's easy by just installing a virtualenv but somehow it's not that smooth in practice. Do you guys want me to send you the installation progress? I put all the install commands in a txt file so I can reproduce it :)

**Comment by sionking** [comment]
I never used 2.7 :)

**Comment by converge** [comment]
@JoeFertig sounds amazing! As RPi support is the only reason to keep 2.7, if now we're able to use python3 on RPi, that will be awesome.

I specially like the idea of deprecate support to python 2.7 because it will be faster/easier to maintain the code base.

Less heuristic code and less bugs to fix, means better code quality, and more space for improvements.

**Comment by timgrossmann** [comment]
@JoeFertig Yes please! This will help a lot of people 👍

**Comment by timgrossmann** [comment]
@opexa It's just a rough outline. And I'm really sorry if this sounds a little bit rough but you're attacking everyone who's investing his free time to maintain this project with a statement like "are left unnoticed". 

The current rate of covered issues is bigger than ever and to be honest a lot of the newly opened issues are issues that came up 100 times already. Like the `no module named xyz` error.
<img width="738" alt="screenshot 2018-12-15 at 23 08 12" src="https://user-images.githubusercontent.com/16529337/50047863-72200c80-00be-11e9-87ac-8f361dd05e31.png">

If you'd actually look through the issues section, there are very few issues that have no comments or suggestions on how to fix it.
Other than hating about it you could simply put up a $5-$10 bounty and the developers working on this stuff would probably be quicker in fixing it or whatever. 
But only being ungrateful and expecting with a community based non profit tool like InstaPy for which people like you are not even ready to donate $10 once, I think you should reconsider your statement.

I'm really sorry for this harsh words but sometimes I really wonder what people think when they use free tooling and only request, not seeing the amount of time that was invested like a tool like this.

**Comment by XavierRaul** [comment]
how ca nwe give you that $5-$10 ??? i use instapy everyday. 5-10 Dolls is not a problème

**Comment by timgrossmann** [comment]
@XavierRaul Good to hear that, thank you very much. The $5-$10 was just an example of how stingy people are when it comes to open source software. 
At the moment, we have ~1k downloads each week. If every person who is using InstaPy even "donated" like $1-$2, we would really have a lot more room for quick improvements and would be able to not only thank the people who are investing a lot of time into this project with a "thanks" but at least some gifts.
I (and probably everyone who ever worked on InstaPy) really appreciates your comment and your willingness.

There are two ways, at the moment. 
First one is using the PayPal link 
https://www.paypal.me/supportInstaPy linked in the Readme. This is a general pool of money that will be used for special issues or topics that come up on the way.

The other one is just putting bounties on issues that you care about yourself using bountysource.com 
Since bounty source changed its "owner", I'd prefer the PayPal style so the community can decide together where the money will be spent.

**Comment by JoeFertig** [comment]
@Timgrossmann how can I send you the txt file with the install codes?

**Comment by timgrossmann** [comment]
@JoeFertig Perfect, drop them at contact.timgrossmann@gmail.com 
Looking forward to updating the guides, thank you very much!

**Comment by timgrossmann** [comment]
@JoeFertig Any updates on the installation steps? 😉

**Comment by andreescocard** [comment]
Running on a rpi 3 here too with cron and python 3, working fine
I'll try to run on a orange pi too, but i am afraid the memory won't hold the chrome :(

**Comment by JoeFertig** [comment]
> @JoeFertig Any updates on the installation steps? 😉

You are absolutely right Sir!
Please check your mails ;)

**Comment by antwal** [comment]
Python 2.7 will reach the end of life in January 2020
Python 3.4 will reach the end of life in March 2019

**Comment by timgrossmann** [comment]
#4247 
Documentation is now focused on python3
