### ISSUE TITLE
Browser class abstraction

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#3581]
#### Chrome/Firefox should have a separate class from instapy, and should handle executions/errors and must have a recovery method that WILL NOT fail the instapy flow.

Advantages of this feature:
- Decoupled error handling of web driver problems
- Better recovery capabilities

Possible ways of achieving this while keeping control:
- Creating a abstraction with a Browser class the handles errors and cares about recovery 

> [Bountysource this Issue](https://www.bountysource.com/issues/67497396-browser-class-abstraction)

--- 

###### Feel free to comment with adjustments and improvements

**Comment by sionking** [comment]
I VOTE FOR IT :)

**Comment by timgrossmann** [comment]
#3596

**Comment by timgrossmann** [comment]
#3962
