### ISSUE TITLE
Follow the likers of photos of users

### ISSUE THREAD

**Issue by hddeus** [InstaPy/InstaPy#3586]
Follow the likers of photos of users does not work !

The issue:

'25,577 others' is already followed
Few likes, not guaranteed you don't follow these likers already.
Got photo likers:  ['adilsonvirgens', '29,687 others']

@timgrossmann

**Comment by JoeFertig** [comment]
Issue already opened:

#3573

**Comment by hddeus** [comment]
we need solution ... someone ?
