### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium'

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#3591]
i freshly installed ubuntu, followed the guide , everything went well untill: install pip .

so i did: 

pip install --upgrade --force-reinstall pip==9.0.3
pip install xxx --disable-pip-version-check
pip install --upgrade pip

Then when i want to start my instapy bot i get: 

/InstaPy$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from instapy import InstaPy
  File "/home/steven/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/steven/InstaPy/instapy/instapy.py", line 13, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by timgrossmann** [comment]
@Tr1pke Have you also tried `pip install selenium?

**Comment by Tr1pke** [comment]
didnt work, i had to this:

pip install --upgrade --force-reinstall pip==9.0.3
pip install xxx --disable-pip-version-check
REBOOT then
pip install --upgrade pip
and it worked

**Comment by kicka5h** [comment]
I get the same error even after trying your fix @Tr1pke .

**Comment by converge** [comment]
```
cd InstaPy
pip3 install -r requirements.txt
```

**Comment by Tr1pke** [comment]
> I get the same error even after trying your fix @Tr1pke .

sudo curl -s https://gist.githubusercontent.com/Mehran/970a4a6a705f5898ca465312e785f8f4/raw/1d3c46130fb1c6e8af140dd76fd690ab53210335/instapy-easy.sh | sh

**Comment by Tr1pke** [comment]
@kicka5h try this: sudo apt-get -y install python-selenium

_else start all over again with:_

sudo apt-get install curl; sudo curl -s https://gist.githubusercontent.com/Mehran/970a4a6a705f5898ca465312e785f8f4/raw/1d3c46130fb1c6e8af140dd76fd690ab53210335/instapy-easy.sh | sh

**Comment by redpredator8** [comment]
First, make sure you run all your commands as administrator then, re-run

python setup.py install

and them simply do

python quickstart.py

and it should work, did for me.
