### ISSUE TITLE
Auto-like my own followers posts

### ISSUE THREAD

**Issue by ExportEh** [InstaPy/InstaPy#3592]
Hi All!

First off, thank you for all the effort and knowledge share in the read me and all the posts. 
I'm currently running a follow & unfollow script flawlessly with 0 python and script knowledge thanks to all your info. 

Is it possible to add to my current script or create a new one that will do the following?
1) Like my current followers posts
2) Set a max post date (something like 24 hours)
3) Set a max amount of posts for my following users?

Searched high and low and can't figure out how I could do that. 
My current script interacts with New Followers but nothing to maintain my previous followers. 

Thank you in advance!

**Comment by spikeyhair** [comment]
you can use the like by feed feature.

**Comment by sionking** [comment]
@spikeyhair  be aware like by feed will probably find the most posting accounts == business

**Comment by ExportEh** [comment]
Thank you for the suggestions. 
I still love this program but find it odd there are no templates or discussions on maintaining those followed.

**Comment by ExportEh** [comment]
Ok, after some playing around I think I got it for those interested. 

`from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = ''
insta_password = ''

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True)

with smart_run(session):
    """ Activity flow """
    # settings

    session.set_relationship_bounds(enabled=False,
                                    potency_ratio=-1.00,
                                      delimit_by_numbers=True,
                                       max_followers=9000,
                                        min_followers=45,
                                        min_following=50)

    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True, peak_likes=(80, 700),)
    
    session.set_do_like(enabled=True, percentage=100)
    session.like_by_feed(amount=700, randomize=False, unfollow=True, interact=False)
    session.set_dont_include(['friend1, friend2'])
    session.set_dont_like(["pizza", "#store", "#bikini"])

# actions
`
I'm playing with the peak likes and the "Like by Feed" numbers to avoid being blocked. Just small increases for now.
