### ISSUE TITLE
Share your file.py and your stats!

### ISSUE THREAD

**Issue by tjuzen** [InstaPy/InstaPy#3593]
Hey! 

I couldn't find a place where everyone shared his script and performance. 
We could improve each others script and find the best way to grow the account.

Post your script, daily limits, and best tips 👍

**Comment by uluQulu** [comment]
Hi @EMYULT 
Have you seen the **quickstart_templates** folder?
It has lots of good styles and inside some of them writes about the performance of the script, etc.

Feel free to add your _quickstart script_ [in a PR] into that templates folder for others to benefit 😉
