### ISSUE TITLE
Get details of all the follower accounts for a given user

### ISSUE THREAD

**Issue by priyath** [InstaPy/InstaPy#3595]
I have successfully used the `grab_followers` method to get all the follower usernames for a given account. However, I need more information on each of these accounts. (things like number of posts, follower count etc)

Currently, I use a separate NodeJS script which loads this list of usernames and extracts a JSON object (the `sharedData` object in the `www.instagram.com/username` response) for each of the accounts. I can then process this set of JSON objects to get the info I need.

What I would like is to do all of this via a single script using `InstaPy`. Would this be possible?

**Comment by sionking** [comment]
I don't think it is a good idea to use the same user in automation and in data grabbing.
BTW, you can use the following link:
web_adress_navigator(session.browser, 'https://www.instagram.com/{}/?__a=1'.format(username))

To get the JSON

**Comment by priyath** [comment]
Thanks, this was helpful and opened up quite a few avenues for my task.
