### ISSUE TITLE
Module Error in Windows 

### ISSUE THREAD

**Issue by rahulkapoor90** [InstaPy/InstaPy#36]
I am getting this error even after replacing the file in assets. My OS is windows 10 and chrome is updated to latest version.

```
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\rahul\Desktop\InstaPy\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "C:\Users\rahul\Desktop\InstaPy\instapy\instapy.py", line 11, in <module>
    from .clarifai_util import check_image
  File "C:\Users\rahul\Desktop\InstaPy\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.client import ClarifaiApi
  File "C:\Users\rahul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\clarifai-2.0.20-py3.6.egg\clarifai\client\__init__.py", line 5, in <module>
  File "C:\Users\rahul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\clarifai-2.0.20-py3.6.egg\clarifai\client\client.py", line 4, in <module>
ModuleNotFoundError: No module named 'past'
```

**Comment by ujazzz** [comment]
I have the same problem. Do you have a solution?

**Comment by timgrossmann** [comment]
@ujazzz It probably simply was installing it: https://pypi.python.org/pypi/past/0.11.1

`pip install future`

**Comment by mcevadov** [comment]
I `pip install future`'d it and still get: 

>PS C:\Users\cevad\Downloads\InstaPy-master\InstaPy-master> py quickstart.py
>Traceback (most recent call last):
  >File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  >File "C:\Users\cevad\Downloads\InstaPy-master\InstaPy-master\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  >File "C:\Users\cevad\Downloads\InstaPy-master\InstaPy-master\instapy\instapy.py", line 14, in <module>
    from .clarifai_util import check_image
  >File "C:\Users\cevad\Downloads\InstaPy-master\InstaPy-master\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Image as ClImage
>ModuleNotFoundError: No module named 'clarifai'

**Comment by converge** [comment]
**ModuleNotFoundError: No module named 'clarifai'**
```pip install clarifai```

**Comment by mcevadov** [comment]
Yes thank you! I did some more digging and found this answer as well! I'd thought that since the instructions said to comment out the clarifai bit that it wouldn't be necessary to install clarifai.

**Comment by condomfighters** [comment]
@mcevadov How did you solve the problem
when i do pip instal clarifai it starts to uninstall pillow and crashes when trying to install it back
so i uninstalled pillow and tried to install clarifai
` error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
`
right now i'm installing updates for microsoft visua  c++ but i think it won't solve the problem
