### ISSUE TITLE
Updating the speed of liking. 

### ISSUE THREAD

**Issue by ELI7VH** [InstaPy/InstaPy#360]
Is this purposely slow when it comes to liking images? 

It takes 15 - 30 seconds to like an image

**Comment by saurabh-kumar-vit** [comment]
The delay is set to prevent you from getting banned. Instagram has some internal policy on how many like/comments a regular (not a bot) user makes. The delays are set so that you stay under that limit.

**Comment by ELI7VH** [comment]
Ok thank you, this is good to know. I appreciate the help :)
