### ISSUE TITLE
set_dont_include do not work

### ISSUE THREAD

**Issue by nbgabriel** [InstaPy/InstaPy#3600]
Hello there!!

I'm having an issue, that the set_dont_include is not working, Instapy is unfollowing users in this lists.

I have it configured like this:
    #Unfollow
    session.unfollow_users(amount=400, nonFollowers=True, style="RANDOM", unfollow_after=3*60*60, sleep_delay=100)
    session.set_dont_include(['user1','user2','andsoon'])

Exists a limit? i have 173 users in dont_include function. 

Thanks

**Comment by JoeFertig** [comment]
All set parameters must be written above your action code.
In your case:

#Unfollow
session.set_dont_include(['user1','user2','andsoon'])
session.unfollow_users(amount=400, nonFollowers=True, style="RANDOM", unfollow_after=36060, sleep_delay=100)

**Comment by nbgabriel** [comment]
@JoeFertig , after i put it i think "mmmmmm maybe its not in right order", thanks man! im testing right now!. 

Thanks a lot. 

I need hollidays :(
