### ISSUE TITLE
Unfollowers not working correctly

### ISSUE THREAD

**Issue by notahooper15** [InstaPy/InstaPy#3602]
## Expected Behavior
Unfollow 400 people then quit
## Current Behavior
Unfollowers anywhere from 20-150 then quits

## InstaPy configuration

this is in my quickstart.py file

session.unfollow_users(amount=400, InstapyFollowed=(True, "all"), style="RANDOM", unfollow_after=48*60*60, sleep_delay=600)

getting the error code

Unfollow loop error:  Expecting value: line 1 column 1 (char 0)

Randomly stops unfollowing after unfollowing for some time. Any help would be appreciated thanks.

**Comment by matthesv** [comment]
Change it to unfollow_after=48*60*60

**Comment by Tr1pke** [comment]
i use 
48*60*60
, maybe this helps?

**Comment by Tr1pke** [comment]
update you unfollow_util.py file , or download it again, i did it and no problems anymore (for now at least)
