### ISSUE TITLE
IP

### ISSUE THREAD

**Issue by AvocadoStyle** [InstaPy/InstaPy#3603]
Why i shouldn't run 4~5 accounts on the same IP?
Can you explain me why it's not good to do it, And how can I use different IPs for every account?
Thanks!
@converge @uluQulu

**Comment by Tr1pke** [comment]
because its obviously you run a bot, and how to use different ip's is up to you, do you have multiple ip's?
i use 2 accounts per IP, sometimes 3/IP i think 3 is the max to be safe if you do a lot of actions / hour

**Comment by AvocadoStyle** [comment]
> because its obviously you run a bot, and how to use different ip's is up to you, do you have multiple ip's?
> i use 2 accounts per IP, sometimes 3/IP i think 3 is the max to be safe if you do a lot of actions / hour

Ok thanks! can you give me a way to use 3,4 IPs in the same PC? just write the name of it and i will make the research, Thanks!

**Comment by HCWcoder** [comment]
I run 4 accounts on each pc

i schedule each account different time to login and do the job.

there is million ways to do it @AvocadoStyle   maybe put some nice `Avocados `

**Comment by Tr1pke** [comment]
> I run 4 accounts on each pc
> 
> i schedule each account different time to login and do the job.
> 
> there is million ways to do it @AvocadoStyle maybe put some nice `Avocados`

@HCWcoder its still the same IP
which i personally think its not a problem because imaging big places with public wifi, they all have the same external IP
im sure 3 active bots won't be a problem, 10 active bots, can cause a problem in the future but you'll get a warning first

**Comment by HCWcoder** [comment]
i was running 16 accounts 4 on each laptop and i wasnt blocked for 5 months

then i had a chance to run some on different IPs so i did and now each 2 laptops = 8 accounts and i have no issue at all

**Comment by Tr1pke** [comment]
@hcwcoder how many actions you do per hour and are the bots online 24-7?

**Comment by HCWcoder** [comment]
> @HCWcoder how many actions you do per hour and are the bots online 24-7?

i have set limits with Quota supervisor 

and yes its 247 non stop
