### ISSUE TITLE
session.unfollow_users(nonFollowers=True) unable to grab followers and following

### ISSUE THREAD

**Issue by arcasoy** [InstaPy/InstaPy#3605]
## Expected Behavior
My script currently has two actions, to unfollow non-followers and then like/follow by tag. I recently had both parts working perfectly but I accidentally deleted my script so I had to rewrite it. Now that I have rewrote the code, I am having problems with the unfollowing part. 

## Current Behavior
"Retrieving live 'Followers' data of ax_tv at "full" range"
Then the error:
"Unable to get 'Followers' data:
b'Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}\n"

I have looked at other issues in this repo about the same issues though none have fixed the problem I am having. I would love if someone could direct me to some suggestions as I am not the most experienced coder.

**Comment by sionking** [comment]
there is a new exception error return from instagram when you do it too fast. change sleep to 10 and try again

**Comment by arcasoy** [comment]
@sionking So I did that and it did not change anything. I am also getting an error saying "Wah! Error occured while getting a DB for 'user': b'database is locked'

the error then references the headless_browser=True line and refers to .../InstaPy/instapy/database_engine.py, line 129, in get_profile: profile=dict(profile) local variable 'profile' referenced before assignment

**Comment by arcasoy** [comment]
In addition, since it says the database is locked, I ensured that instapy.db was read/writeable by doing chmod 777 instapy.db.

**Comment by arcasoy** [comment]
Please disregard my most recent error. I realized that I had not updated the files from the GitHub in a while and decided to do so, seems like I was 330 commits behind. This update fixed the 'database is locked' error but my primary error still stands, the script cannot grab followers and following and returns the same error message as mentioned in my initial post. The behavior now though is that it will continue to run the remainder of the script, following users, even after failing to unfollow user. Prior to updating, the script would quit once it reached the error of not being able to unfollow.

**Comment by arcasoy** [comment]
Bump, error of grabbing 0 followers and following still persists

**Comment by GeoffreyPG** [comment]
Same error !
Unable to locate element: {"method":"tag name","selector":"pre"}\n
