### ISSUE TITLE
Selenium Error

### ISSUE THREAD

**Issue by Stewler** [InstaPy/InstaPy#3606]
Edit: request to close issue, solved.

**Comment by chamo1116** [comment]
Yeah, I have the same problem, I think it's because in instagram page when you click in followers, it shows a pop-up, so selenium couldn't find div called followers. But I don't know how to fix it

**Comment by Stewler** [comment]
@chamo1116 actually I haven’t gotten to the point that I managed to run Instagram, probably your having a different issue.

**Comment by chamo1116** [comment]
No, I think it's the same problem because I can not run it either and the error contains something with Selenium, I'm waiting for any way to fix it.

**Comment by chamo1116** [comment]
I opened up an issue #3604 look at that.

**Comment by Stewler** [comment]
@chamo1116
I found a way to fix my issue, I used the command: pip install selenium
