### ISSUE TITLE
Xpath Error with login

### ISSUE THREAD

**Issue by SMarcinno** [InstaPy/InstaPy#3607]
https://github.com/timgrossmann/InstaPy/wiki -->
## Suddently not working anymore :(

It is not finding some xpath for the login. I dont know why. I was so happy that I got everything working with my Pi yesterday and today it just stopped

![commandline](https://user-images.githubusercontent.com/43820577/50109120-378daf80-0237-11e9-973e-c8881c9d283c.png)

Does anybody have similar error? The funny thing it is still working on my windows maschine with cmd

**Comment by uluQulu** [comment]
It is very weird, @Smadman, can you attach your _quickstart_ script?

Also provide other details you have.
I know @converge is very good at this issue 🐬 and maybe can help 🚀
