### ISSUE TITLE
quickstart.py crash in seconds won't even let me capture the black screen

### ISSUE THREAD

**Issue by shinuuuuuu** [InstaPy/InstaPy#3609]
## Expected Behavior
quickstart.py run normally
## Current Behavior
won't even login
## InstaPy configuration
attached

i'm a beginner and i'm understand that such question might too "meh" for everyone but please anyone kindly help me. i've read somewhere about similar problem but i still don't get my solution mine still crash after 1 second after opened it won't let me capture anything

attached is the config i used (pardon if anything wrong) i ran mine @ windows 10 32bit

nb: blanked the username & password intentionally for attaching, not running the bot with it before the error
![untitled](https://user-images.githubusercontent.com/45971433/50159686-23c06880-028c-11e9-8b91-be0735cc61c7.png)

**Comment by uluQulu** [comment]
Hi @shinuuuuuu 
1-) Make sure whole activity flow is run with `smart_run()`,
![image](https://user-images.githubusercontent.com/33269249/50164176-653c2c80-02fb-11e9-86e8-ca5d118b253e.png)


2-) Post the console output of the issue you do get and/or provide error details.

---

Cheers 😁
---

**Comment by shinuuuuuu** [comment]
thank you so much for quick response, sir!

already done as you suggested but then again it made no changes. here's the very last black screen i'm able to capture 
![untitled2](https://user-images.githubusercontent.com/45971433/50166056-0f379c80-029b-11e9-8ed6-8bc48cb9fba2.png)

and here's the updated script as you suggest (although i'm not sure if it is right)
![untitled](https://user-images.githubusercontent.com/45971433/50166096-29717a80-029b-11e9-8ecb-c2509a4623f9.png)

in another hand, here's what popped up (i think this might be the error but pls help i don't know how to fix)
![untitled3](https://user-images.githubusercontent.com/45971433/50166199-66d60800-029b-11e9-8d87-07fc24edcb52.png)

just in case, attached is my chromedriver path
![untitled4](https://user-images.githubusercontent.com/45971433/50166279-938a1f80-029b-11e9-8120-71df4c719bcd.png)

**Comment by uluQulu** [comment]
Welcome, @shinuuuuuu 

1-)
![image](https://user-images.githubusercontent.com/33269249/50167004-94ee3300-0301-11e9-96bf-a54af7010e98.png)

Why don't you use just one `smart_run()` ?
```python
session = InstaPy()
with smart_run(session):
    """ Activity flow """
   # general settings (e.g. setting _quota supervisor_, _relationship bounds_, etc.) 

    # custom settings for activity 1    (e.g. _commenting_ enabled from now on)
    # activity 1 (e.g. _like by tags_)

    # custom settings for activity 2    (e.g. _commenting_ disabled from now on)
    # activity 2 (e.g. _interact by users_)

# End of file :)
```

2-) I think you execute the quickstart file inside IDLE, with its command prompt executor and it immediately closes that cmd window after execution finishes.
You can either configure it keep the cmd window open or execute the quickstart file in normal ways (_just open `cmd.exe` in _Run_ and `cd` to **InstaPy** folder and run `python quickstart.py`_)

---

![image](https://user-images.githubusercontent.com/33269249/50167676-21e5bc00-0303-11e9-923a-0a8b965abd5b.png)

At this moment, I don't know what is the problem in your side.
If you run your _quickstart_ script in normal ways as I said above and copy the error output from console window and share here, I will help more.

---

Cheers 😁
---

**Comment by shinuuuuuu** [comment]
do i need to create #custom setting for activity or can i just keep my #activity and everything below as it is? i am putting

session = InstaPy()
with smart_run(session):

right above """activity flow""" and deleted the one just right before #activity is that correct? (i'm referring to my latest screenshot)

my quickstart are both python file. here's what i do from editing to executing: right click > edit with idle > and when i finished i click save > exit as for executing i simply double clicked on the file and the black screen show up

as for the cmd i attached before, i did that to configure whether there's something wrong in my system (learnt from youtube) and it turns out that i need to downgrade(?) my clarifai? or not?

so sorry sir i'm completely all new to this TT__TT

**Comment by uluQulu** [comment]
I see, @shinuuuuuu 
1-) Make sure you have installed all of the dependencies of InstaPy from `pip` (_see **requirement.txt** file_)

2-) Edit _quickstart_ script as you wish using either IDLE, Notepad or any other text editor and save it.

3-) Open command prompt and navigate to the folder which holds your **quickstart.py** file.
```python
cd C:\Users\shinuuuuuu\Documents\InstaPy
```
4-) Run that _quickstart_ script now.

```powershell
python quickstart.py
```

5-) Enjoy InstaPy 😄

---

Double-click opening the python files:
`.py` is a source code extension of python, right. But opening source code files by double-clicking on them is not a good study. Open them inside command prompt manually as I explained in the 4th step.

>i need to downgrade(?) my clarifai? or not?

Hmm, why?

>do i need to create #custom setting for activity or...

I told it for better workflow, e.g. you can set the same setting for every activity and not have any custom setting for any activity.

>...is that correct?...

Better share code to see if is correct 🙂

---

Also, note that, settings should be written before actions.
E.g. I saw you wrote `set_quota_supervisor()` at the end of workflow - means, until that time, _quota supervisor_ will not be active.


---

Cheers 😁
---

**Comment by shinuuuuuu** [comment]
here's my latest update
![untitled](https://user-images.githubusercontent.com/45971433/50189284-7d9b4f80-02d9-11e9-9931-0629a44aeed3.png)

**Comment by shinuuuuuu** [comment]
hi @uluQulu fortunately (after i follow your instructions) everything goes well and the both started running without crashing after seconds

but another problem happened:
![untitled](https://user-images.githubusercontent.com/45971433/50189838-c5bb7180-02db-11e9-9802-cc705bd607a1.png)

**Comment by uluQulu** [comment]
Good, now you got it working @shinuuuuuu 😉🎉🎉🎉

Now there is one problem in your quickstart script.
You have instantiated InstaPy 2 times in there
![image](https://user-images.githubusercontent.com/33269249/50229741-6dac6a00-03c4-11e9-9636-4dca218434b6.png)
Remove the second one to be good.

Also the errors in your second screenshot with a console, just get the latest files of InstaPy, it will be fine 🐬 (_those errors are fixed AFAIK_)

---

Cheers 😁
---

**Comment by shinuuuuuu** [comment]
thank GOD you're here!!!!!

deleted the 2nd session:
![untitled](https://user-images.githubusercontent.com/45971433/50230410-7d469700-0361-11e9-94f5-bd1c2f0f4ba0.png)

one dumb question:
how to get the latest files of InstaPy? i downloaded just yesterday and recheck the latest files and it says it updated 2 days ago (which is one day before i download)

**Comment by uluQulu** [comment]
Amazing @shinuuuuuu 

>how to get the latest files of InstaPy?

+ I recommend you to install the **GitHub Desktop** app [for Windows] and then get used to it. It has the best interface to work with Github repositories.
You will just set the _remote repository_- `https://github.com/timgrossmann/InstaPy.git` and **fetch** it to find new commits and if there are any, start **pulling** them anytime, easily.

+ Other way is downloading the repository (_or some files_) manually from GitHub into the current folder.
+ And advanced way to it is using `git` in command line interface.


_In future things will be more easier, hopefully, you will just click on the Update button to do it, but now, it is done as explained above_ 🙂

---

Cheers 😁
---

<sub>Make sure you do not post your username and password or any other sensitive information anywhere.</sub>

**Comment by shinuuuuuu** [comment]
thankyou @uluQulu!! my bot is now working properly!!!

i delete and redownload because i messed up way too much, and it's now running. thankyou for being patient :-)
![untitled](https://user-images.githubusercontent.com/45971433/50261412-4bfdb380-03c1-11e9-9b0a-bfe38a3a78af.png)
