### ISSUE TITLE
any setting to skip the "top" in each hashtag?

### ISSUE THREAD

**Issue by ELI7VH** [InstaPy/InstaPy#361]
It's typicaly 9 of them, woud be nice to give instapy a way to skip them, to save time on the liking of pics.

**Comment by saurabh-kumar-vit** [comment]
By "top" you mean the the first few images that show up on the page? 

Is it that they are always same because Instagram has pinned them because of their popularity?

**Comment by ELI7VH** [comment]
Yeah they are always there during hashtag searches. So if you do the same tag multiple times in a day, you end up wasting a good 5-10 minutes just getting thru posts you already like.  

Actually it would be great if you could just skip posts you like before the timer starts

**Comment by timgrossmann** [comment]
You can simply use the `.set_upper_followers()` to make sure you won't interact with them. 
These accounts mostly have a lot of followers.

**Comment by GonzaloZiadi** [comment]
@timgrossmann Tim, let's say I set .set_upper_followers(limit=250). For some hashtag the first 20 pictures will be by users with large amounts of followers, so I won't like any of those pictures unless I set a really high number in like_by_tags.
Using set_upper_followers() works, but it takes a lot of time. I think a 'skip the "top" in each hashtag' feature would be beneficial.
