### ISSUE TITLE
Telegram and monitoring alerts

### ISSUE THREAD

**Issue by spikeyhair** [InstaPy/InstaPy#3610]
I saw lots of posts with "feature requests" but I don't know how to do that. 
I have a new feature request / suggestion here.

I know currently there is a script written to use telegram to control some function.
Can we add a few more monitoring reporting functions:
1. Whenever there is an error occurred such as xpath, elements not found, a message is sent to telegram automatically.
2. Whenever there is an exception error and the bot gets terminated, send a message to telegram automatically.

**Comment by Tkd-Alex** [comment]
Hi! The bot telegram i'ts already working in this way.
When a jobs end the output will be send to your Telegram. If the job ended because there was an exception the general.log lines will be messaged to you.

With the last commit I've write a method for parse the output of log but i forgot to parse the errors. ops.

**Comment by spikeyhair** [comment]
Is there a help or instructions file like the readme.md here to teach us how to use it?

Regards,
Kevin Cheng

On 19 Dec 2018, at 3:25 AM, Alessandro Maggio <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi! The bot telegram i'ts already working in this way.
When a jobs end the output will be send to your Telegram. If the job ended because there was an exception the general.log lines will be messaged to you.

With the last commit I've write a method for parse the output of log but i forgot to parse the errors. ops.

**Comment by HCWcoder** [comment]
@spikeyhair 

Hey mate yes its working like a charm !

check it out [Telegram-InstaPy-Scheduling](https://github.com/Tkd-Alex/Telegram-InstaPy-Scheduling)

and open README for help.

**Comment by spikeyhair** [comment]
That means i need to send /log to telegram bot to get the n lines of logs, right?
What I mean in the feature request is to get the message automatically whenever there is an error or bot gets terminated abnormally.

Can you also give me the link on how to setup telegram in python (windows)?

**Comment by spikeyhair** [comment]
Hit this error:
C:\Users\Administrator\Dropbox\Instapy\scripts>py main.py
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from scripts import scripts
ModuleNotFoundError: No module named 'scripts'

Can you give the step by step on how to setup?

**Comment by Tkd-Alex** [comment]
Have you read the README?

**Comment by spikeyhair** [comment]
Of cause I did


On 20 Dec 2018, at 6:10 PM, Alessandro Maggio <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you read the README?

**Comment by Tkd-Alex** [comment]
From README:
```
Rename scripts.py.dist in scripts.py and edit it.
```
