### ISSUE TITLE
Message: no such element: Unable to locate element: {"method":"xpath","selector":"pre"}\n

### ISSUE THREAD

**Issue by shinuuuuuu** [InstaPy/InstaPy#3611]
![untitled](https://user-images.githubusercontent.com/45971433/50191366-6dd43900-02e2-11e9-88a3-f50fc9c4b7c9.png)

anyone pls help

**Comment by arcasoy** [comment]
I also have the same issue, no followers grabbed and mentions that an element cannot be located. In my attempt to fix this problem I have also raised other issues such as database profile for my account being locked and that profile = dict(profile) is referenced before being assigned. I am very stuck on all of these.

**Comment by converge** [comment]
hey @shinuuuuuu @arcasoy , what's your browser, and version ?

**Comment by shinuuuuuu** [comment]
hello @converge, mine is the latest :-)
![untitled](https://user-images.githubusercontent.com/45971433/50211731-2d021180-032e-11e9-979d-fc9af9e2d381.png)

**Comment by converge** [comment]
I think it doesn't happen on Firefox, can anyone confirm ?

**Comment by arcasoy** [comment]
I use chromium on my RPi 3, shoukd be the newest version especially since I use a headless browser and just reinstalled chromedriver

**Comment by shinuuuuuu** [comment]
hi @uluQulu i got a question,
is the bot supposed to be closed by itself every time it finishes?
today i found out that the bot closes without me closing it and it said that it finished. i read somewhere that they need to even keep their PC turned on 24/7 just for the bot to keep working
so i'm curious, is it just me and my command that are too simple so it finish early or i did something wrong?
if mine is finished & closed, how about the "unfollowing" process that i set to unfollow after 48 hours?

**Comment by x225am** [comment]
I have same issue, any one has any solution for this?

**Comment by gitpatrickhub** [comment]
See #3444 for possible solution
