### ISSUE TITLE
Chromedriver issue on Raspberry Zero-W

### ISSUE THREAD

**Issue by francescolorenzo96** [InstaPy/InstaPy#3613]
## InstaPy configuration
```
session = InstaPy(username="username",
                  password="password",
                  headless_browser=True)

```

## What i tried
Running Raspberry Pi Zero-W with Raspbian Stretch.
I followed step-by-step https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Raspberry.md, tried to run quickstart.py and got the "Ensure chromedriver is installed at..", then tried the fix at the end of the document for this specific problem, but it didn't work, same issue. 
I tried removing wolfram and libreoffice* as suggested in #2678 but the problem is still there.

## Results
The log is the following:
```
Message: Service /home/pi/Desktop/instapy/assets/chromedriver unexpectedly exited. Status code was: -4
Traceback (most recent call last):
  File "/home/pi/Desktop/instapy/instapy/browser.py", line 117, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
WebDriverException: Message: Service /home/pi/Desktop/instapy/assets/chromedriver unexpectedly exited. Status code was: -4

Traceback (most recent call last):
  File "quickstart.py", line 16, in <module>
    headless_browser=True)
  File "/home/pi/Desktop/instapy/instapy/instapy.py", line 256, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Desktop/instapy/instapy/instapy.py", line 305, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/pi/Desktop/instapy/assets/chromedriver
```
  
   
   
            

## Update

I did a clean installation of raspbian stretch lite, and followed these exact steps:

> Installation with raspbian stretch lite (v4.14) 
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install chromium-browser python-pip git
git clone https://github.com/timgrossmann/InstaPy.git instapy
in the instapy folder: pip install .
in the assets folder: wget https://github.com/electron/electron/releases/download/v3.0.0-beta.5/chromedriver-v3.0.0-beta.5-linux-armv7l.zip
also in the assets folder: unzip chromedriver-v3.0.0-beta.5-linux-armv7l.zip
🎉

But nothing changed, still get the same error.  
This time there are no other things to uninstall like libreoffice* since this is stretch lite, so those steps should be enough to make it work.

**Comment by iPhra** [comment]
###Update 

I did a clean installation of raspbian stretch lite, and followed these exact steps:

> Installation with raspbian stretch lite (v4.14) 
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install chromium-browser python-pip git
git clone https://github.com/timgrossmann/InstaPy.git instapy
in the instapy folder: pip install .
in the assets folder: wget https://github.com/electron/electron/releases/download/v3.0.0-beta.5/chromedriver-v3.0.0-beta.5-linux-armv7l.zip
also in the assets folder: unzip chromedriver-v3.0.0-beta.5-linux-armv7l.zip
🎉

But nothing changed, still get the same error.

**Comment by Phoenix1112** [comment]
hello. it is same problem. but if you change (headless_browser=False with (headless_browser=True) 
it is working in background. but chrome web browser not opening. only it is working with terminal

**Comment by francescolorenzo96** [comment]
> hello. it is same problem. but if you change (headless_browser=True) with (headless_browser=False)
> it is working in background. but chrome web browser not opening. only it is working with terminal

Hi, i tried with headless_browser=False as well (both with nogui=True and nogui=False) but i still get chromedriver error. Are you using Stretch or Stretch lite?

If anyone has a working copy, can you tell me which version of chromium and which version of chromedriver you use?

**Comment by Phoenix1112** [comment]
I managed to do it yesterday.browser is currently opening. 

now listen me. i am using kali linux. delete the folder of the program you have previously downloaded and re-download.now load the following commands in order

sudo apt-get update && sudo apt-get upgrade
sudo apt-get install python3
sudo apt-get install python3-pip
sudo apt-get install python3-selenium
sudo apt-get install python3-pyvirtualdisplay
sudo apt-get install python3-dev
sudo pip3 install selenium
sudo pip3 install clarifai

need to have google chrome web browser installed on your computer.. if you have google chhrome browser in your compter, /usr/bin folder will have a file named google-chrome-stable.
Open the google-chrome-stable file with nano text editor

sudo nano /usr/bin/google-chrome-stable

See the bottom of the page after opening
you will see this article when you reach the bottom line >>    exec -a "$0" "$HERE/chrome" "$@"

now let's write --no-sandbox

 it will be like that   
 exec -a "$0" "$HERE/chrome" "$@" --no-sandbox

save and exit

sudo chmod +x /usr/bin/google-chrome-stable

now you will download google chrome web driver (i am using 2.45 version)
http://chromedriver.chromium.org/downloads

unzip chromedriver.zip

Copy chromedriver file to assets folder

NOW İNSTALL 
sudo python3  setup.py install

edit quickstart.py file after installation is complete...just type your username and password

now run program
sudo python3 quickstart.py

**Comment by francescolorenzo96** [comment]
@CyberTheReape Thank you for your answer. I only have one question, do you have Kali on Raspberry? Because as far as i know there are no ARM versions of Chrome.

**Comment by Phoenix1112** [comment]
You can install kali linux os in raspery 

You can install chromium . Maybe chromium browser can work instapy

https://tutorials-raspberrypi.com/google-chrome-for-raspberry-pi/

**Comment by francescolorenzo96** [comment]
Yeah but then the problem is the same, i can't follow your guide, it's not for ARM based processors, i need chromium and a different chromedriver (for ARM). 
The ARM guide is the one i followed, but it's not working.

**Comment by entttom** [comment]
i have the same problem with a zero W - any solutions so far?
also tried the 4.0 chromedriver - doesnt work

**Comment by francescolorenzo96** [comment]
@entttom none yet, still hoping someone with a working version will upload it for us.

**Comment by thehelvijs** [comment]
https://github.com/timgrossmann/InstaPy/issues/4033#issuecomment-466491400

**Comment by tE3m** [comment]
Oh, didn't see that one xD

**Comment by mwargan** [comment]
@Ewlbo followed the exact steps but it seems instapy still wants to use another version, errors is: 
```
INFO [2019-02-22 20:45:43] [xx]  Using built in instapy-chromedriver executable (version 2.46)
Traceback (most recent call last):
  File "quickstart.py", line 10, in job
    session = InstaPy(username='xx', password='xx', headless_browser=True, nogui=True,  disable_image_load=True)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 279, in __init__
    self.set_selenium_local_session()
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 331, in set_selenium_local_session
    self.logger)
  File "/usr/local/lib/python3.5/dist-packages/instapy/browser.py", line 135, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
```

**Comment by tE3m** [comment]
It still uses the built-in version... what is in your `assets/` folder?

**Comment by thehelvijs** [comment]
@mwargan I will try to do it from fresh install again and get back to you, Meanwhile try 

`sudo pip3 uninstall instapy-chromedriver`

Edit: and as @TarekJ03 mentioned - if there is chromedriver in /home/pi/InstaPy/assets, delete it.
Edit 2: it still says that it is using built-in 2.36.post0, but that is false I think as it logged in and ran the program successfully.

**Comment by mwargan** [comment]
@TarekJ03 empty. I also am not a fan that we have to `sudo` it on a Pi Zero, it's installed in the /root directory which isn't as friendly to get to :P

@Ewlbo thanks! Will do the same. Maybe you could send a PiBakery script?

an uninstall of instapy-chromedriver yielded another error:
```
Traceback (most recent call last):
  File "quickstart.py", line 10, in job
    session = InstaPy(username='xx', password='xx', headless_browser=True, nogui=True,  disable_image_load=True)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 279, in __init__
    self.set_selenium_local_session()
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 331, in set_selenium_local_session
    self.logger)
  File "/usr/local/lib/python3.5/dist-packages/instapy/browser.py", line 77, in set_selenium_local_session
    chromedriver_location = get_chromedriver_location()
  File "/usr/local/lib/python3.5/dist-packages/instapy/file_manager.py", line 224, in get_chromedriver_location
    from instapy_chromedriver import binary_path
ImportError: cannot import name 'binary_path'
```

**Comment by thehelvijs** [comment]
@mwargan what will this do:

`sudo python3 quickstart.py -u yourusername -p yourpassword` ?

else, try to run this with your username/password: 

```
from instapy import InstaPy

# Set login info with headless browser
session = InstaPy(
	username = '', 
	password = '', 
	headless_browser = True,
	nogui=True,
	multi_logs = True)

# Log in to the account
session.login()

# End session - log out
session.end()

```

**Comment by mwargan** [comment]
@Ewlbo its running exactly like that (the xx are just placeholders :P) - the quick-start script works fine on a Pi 3B+...

**Comment by thehelvijs** [comment]
@mwargan Zero is so damn slow. Do this:

```
sudo pip3 uninstall instapy-chromedriver
sudo pip3 install instapy-chromedriver==2.36.post0
sudo cp /usr/lib/chromium-browser/chromedriver /usr/local/lib/python3.5/dist-packages/instapy_chromedriver/chromedriver
```

Also edited the comment https://github.com/timgrossmann/InstaPy/issues/4033#issuecomment-466491400. Should work from fresh install as well.

**Comment by tE3m** [comment]
@mwargan empty means that you didn't download a chromedriver manually. Then it'll obviously use the built-in one xD
EDIT: only read the last part afterwards. That happens because it'll try to use the built-in chromedriver (which you uninstalled)

**Comment by mwargan** [comment]
@Ewlbo confirmed works after your comment changes! Thanks!
