### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by GabrieleCalarota** [InstaPy/InstaPy#3614]
### Bug in code
This is from instapy/unfollow_util.py
in function def follow_user():
```python3
    if track in ["profile", "post"]:
        if track == "profile":
            # check URL of the webpage, if it already is user's profile page, then do not navigate to it again
            user_link = "https://www.instagram.com/{}/".format(user_name)
            web_address_navigator(browser, user_link)
```
### Possible solution
```python3
    if track in ["profile", "post"]:
        if track == "post":
            # check URL of the webpage, if it already is user's profile page, then do not navigate to it again
            user_link = "https://www.instagram.com/{}/".format(user_name)
            web_address_navigator(browser, user_link)
```
I was like surprised that the bug is there since a lot of time .. so it made me think, do you all agree this is a bug that should be fixed?

**Comment by sionking** [comment]
@uluQulu 
I think track is where you came from, so it might be a bug but I would not be fixing it since
the thing is the follow element is the same for post and profile, it will work anyway.

**Comment by GabrieleCalarota** [comment]
@sionking 
Yes but since if you came from post you are not a user profile page and get_status_follow wants to know what's written in the button of the profile page of that specific user .. so I think it's a bug

**Comment by sionking** [comment]
get_status_follow  should work 2 I think as it the same element ?
But maybe some testing need to be done ?

**Comment by GabrieleCalarota** [comment]
@sionking I think if you are not on the profile page when in get_follow_status, then it won't work. To me it seems a bug, but since I'm the only one that is arguing that, it leaves me with a question mark in my head 😅😅

**Comment by GabrieleCalarota** [comment]
@sionking the system will not crash, it's only that you are not going to follow people from post

**Comment by uluQulu** [comment]
### Hi there!
>I was like surprised that the bug is there since a lot of time .. so it made me think, do you all agree this is a bug that should be fixed?

>But maybe some testing need to be done ?

###### Code is healthy guys 😂
And @sionking is right, it is a product of my mind so I should clarify a bit;

@GabrieleCalarota 
>Yes but since if you came from post you are not a user profile page and get_status_follow wants to know what's written in the button of the profile page of that specific user .. so I think it's a bug

Hmm, please read & visualize code accurately, you will see it has no leak.
Tracks work different than you think, e.g. `if track == "profile":` means, you are going to follow the user from profile page. It just doesn't _mean_/_care_ whether you are coming from or in a profile page [at the moment]..

@sionking  is right, `get_following_status()` function is smart enough to operate in all those tracks, no need to worry.

Those engines are highly generalized in first place to provide smoothness.

>I think if you are not on the profile page when in get_follow_status, then it won't work. 

Does it not work for you? I wonder.

>...it's only that you are not going to follow people from post

Following a user from a post page, okay.
There are 8 calls of `follow_user()` function with the track of `"post"` throughout _InstaPy_ class and per your consideration, it does not work. Hmm 🤔 SO why there are no any **Issues** on that BIG MISBEHAVIOUR? 🤔 Ever thought? 🤫

![zx](https://user-images.githubusercontent.com/33269249/50385039-584a7f00-06e7-11e9-9a6a-c06c1823e759.png)

---
If you have any BUG at runtime, let me know, please.
@timgrossmann #3615 

Cheers 😁
---


<sub>"_thinking it a bug_"/" _it seems a bug_" and "_being a bug_" are different terms</sub>

**Comment by GabrieleCalarota** [comment]
@uluQulu
Hey I wasn't working on the most updated version of Instapy, I was only looking at the code.

Thanks for the explanation, closing now
