### ISSUE TITLE
Interact cannot stop follow and unfollow

### ISSUE THREAD

**Issue by sannyd** [InstaPy/InstaPy#3617]
I am trying to do interact with others followers but only like and not follow or unfollow.  

Is it possible?

I tried two methods.  Using the syntax from the manual:

session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
session.set_do_follow(enabled=False, percentage=70)
session.set_do_like(enabled=True, percentage=70)
session.set_comments(["Cool", "Super!"])
session.set_do_comment(enabled=False, percentage=80)
session.interact_user_followers(['natgeo'], amount=10, randomize=True)

if i set false to comment and also follow it should only like, correcT?
i also tried the quickstart template
and tried to turn off follow and unfollow similarly
both still result in following of the targeted follower

**Comment by andreademasi** [comment]
Same problem

EDIT: I found a workaround by looking into the code. In my case i had `session.set_simulation(enabled=True)`  which enables the bot to follow some users to emulate human interaction. Easy fix, just change to `session.set_simulation(enabled=False)`
