### ISSUE TITLE
CentOS 7 Install errors  compilation terminated.

### ISSUE THREAD

**Issue by gethubuser24** [InstaPy/InstaPy#362]
I have a brand new install of CentOS 7 x64 and followed the instructions provided exact but have a number of errors.  I have attached them, any ideas on what is causing them?
[putty-insta.txt](https://github.com/timgrossmann/InstaPy/files/1119667/putty-insta.txt)

 #include "Python.h"
                      ^
  compilation terminated.
  In file included from libImaging/Imaging.h:14:0,
                   from libImaging/Resample.c:16:
  libImaging/ImPlatform.h:10:20: fatal error: Python.h: No such file or directory
   #include "Python.h"

**Comment by timgrossmann** [comment]
@gethubuser24 Well, I noticed, that a lot of people came across problems with the CentOS setup... I therefore removed it.

Please use Ubuntu.
Thank you
