### ISSUE TITLE
(beginner guide) how and where to put "scheduling"?

### ISSUE THREAD

**Issue by shinuuuuuu** [InstaPy/InstaPy#3620]
i'm a complete beginner so anyone would like help me on how and where to put the "scheduling"? i'm planning to go out of town and i would like to schedule the bot running just in case i forgot to run it manually. i would like to schedule mine to start running from 9am - finish. mine is currently running using a smart_run. how should i edit and where to put it? many thanks in advance!

**Comment by KirjoZzZ** [comment]
Here is what I did: https://www.youtube.com/watch?v=n2Cr_YRQk7o

**Comment by shinuuuuuu** [comment]
thanks so much! so if i want to start mine @ 9am everyday, does that mean that i should open the cmd before 9am or will it open by itself @ 9am?

**Comment by KirjoZzZ** [comment]
No need to open. It will do everything by itself.
