### ISSUE TITLE
Emojis in Comment are displayed incorrectly

### ISSUE THREAD

**Issue by thejeromelouis** [InstaPy/InstaPy#3622]
Every Comment Instapy does, there is this sign � in the end. Any help? Thanks!

## Current Behavior
For example the comment is displayes like: "Wonderful!! 😍 I would be honored if you would checkout my images and tell me what you think. 😉 �"

## InstaPy configuration
session.set_comments([u'What an amazing shot! :heart_eyes:',
                          u'What an amazing shot! :heart_eyes: I think you might also like mine. :wink:',
                          u'Wonderful!! :heart_eyes: I would be honored if you would checkout my images and tell me what you think. :wink:'],
                            media='Photo')

**Comment by the-unknown** [comment]
same with me!
