### ISSUE TITLE
follow_user_followers Session ended!

### ISSUE THREAD

**Issue by asdasdasdasdasdasdasdad** [InstaPy/InstaPy#3623]
Hello. I follow someone's followers. Here is my code:
```
from instapy import InstaPy

session = InstaPy(username='username', password='pass')

session.login()

session.follow_user_followers(['someone'], amount=150, sleep_delay=30, randomize=False, interact=False)

session.end()
```
Followed: 11
 INFO [2018-12-21 16:58:39] [username] Already followed: 0
 INFO [2018-12-21 16:58:39] [username] Not valid users: 136
 INFO [2018-12-21 16:58:44] [username] Sessional Live Report:
 |> LIKED 0 images | ALREADY LIKED: 0
 |> COMMENTED on 0 images
 |> FOLLOWED 11 users | ALREADY FOLLOWED: 0
 |> UNFOLLOWED 0 users
 |> LIKED 0 comments
 |> REPLIED to 0 comments
 |> INAPPROPRIATE images: 0
 |> NOT VALID users: 136
 
 On session start was FOLLOWING 191 users & had 425 FOLLOWERS
 [Session lasted 19.64 minutes]
 INFO [2018-12-21 16:58:44] [username] Session ended!

It follow just 11 user. I want 150 follows. Thank you

**Comment by asdasdasdasdasdasdasdad** [comment]
I fixed. I add 2 line codes
```
session.set_relationship_bounds(enabled=False)
session.set_skip_users(skip_private=False)
```

**Comment by moeinmohebbii** [comment]
somebody answer pls.
i keep getting Not a valid user: blahblahblah is private account, by default skip
and i cant turn the skipping off. i keep changing it false and 0 but still nothing changes.
