### ISSUE TITLE
Headless browser with auth proxy make problems

### ISSUE THREAD

**Issue by DHZ92** [InstaPy/InstaPy#3625]
Hi,
I have start using the proxy mode with Authentication, but when im trying to use Headless_browser set to True the proxt doesnt work at all... 

do u have any idea how can i work with auth proxy and headlessbrowser?
Thanks 👍

**Comment by sionking** [comment]
not with chrome

**Comment by amauryleproux** [comment]
@DHZ92 is the proxy working when you set up the headless browser at false?
