### ISSUE TITLE
improving options?! #help

### ISSUE THREAD

**Issue by ju5tis** [InstaPy/InstaPy#363]
# **Just checked the working flow.**

### 1.0  most popular vs recent pictures

- it takes a lot of time til the script likes the section of recent pictures.
  -> Thesis: liking recent pictures  let people check your site very quickly 

Solution: Did find a way, by using Adblocker, in order to block the div of most popular pictures.

 ### 2.0 Liking series (improving likes)

An option could be:

- after the bot liked a picture he could go on that account and like one or two more pictures.

 If combine this with the user following, in a  25 % rate then this would improve the output of likes and followers for sure.

  
What do you think is the second option possible?

p.s About instapy it's a nice option to experiment with a target group,
also to improve your likes and grow an audience.

**Comment by sionking** [comment]
Can you share the solution for 1.0 ?
