### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by vladgrish** [InstaPy/InstaPy#3634]
While running on a gcloud micro-f1 instance, with stable google chrome and latest driver I get an error:

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-12-26 22:53:56] [user]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
Cookie file not found, creating cookie...
.................................................................
CRITICAL [2018-12-26 22:54:58] [user]  Wrong login data!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-12-26 22:55:04] [user]  Sessional Live Report:
        |> No any statistics to show
On session start was FOLLOWING 318 users & had 225 FOLLOWERS
[Session lasted 1.27 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-12-26 22:55:04] [user]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

running in a vnc session I discovered the the session actually logs in successfully but browser closes right after that.
same thing happens in headless mode
tried increasing time.sleep() to 5  after creating cookie, didn't help
trying quickstart.py, no special configuration
anyone had this problem?

**Comment by w4ngel** [comment]
The browser closes due to it believing the session is ended, what has likely happened if you have the correct login data is Instagram are doing A/B testing meaning the //nav element is no longer there, if you add a sleep right after it dumps the cookie, a long sleep, does it login successfully?

**Comment by vladgrish** [comment]
The browser closes after session ends, the session ends because it thinks login was unsuccessful. While cookie generates the login page is greyed out, after login failure occurres, the profile starts loading.
Will try tommorow with longer sleep

**Comment by Good-Kat** [comment]
I have the same issue.


python36 quickstart.py 

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-12-26 17:48:52] [xxxxxxxxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...


...........................................................
CRITICAL [2018-12-26 17:50:18] [xxxxxxx]  Wrong login data!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2018-12-26 17:50:22] [xxxxxxxx]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 39 users & had 5975 FOLLOWERS
[Session lasted 1.53 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2018-12-26 17:50:22] [xxxxxx]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by Good-Kat** [comment]
recently made clean install and all fine! all working !

**Comment by AdamMoffitt** [comment]
Did you find a fix for this? having the same exact issue
