### ISSUE TITLE
Error error: jsonschema 3.0.0a3 is installed but jsonschema<3,>=2.5 is required by set(['clarifai'])﻿

### ISSUE THREAD

**Issue by harthf** [InstaPy/InstaPy#3636]

**Comment by Phoenix1112** [comment]
sudo apt-get install python3-pip

sudo pip3 install selenium

sudo apt-get install python3-pyvirtualdisplay

sudo apt-get install python3-dev

sudo pip3 install clarifai

**Comment by lovrom23** [comment]
Windows 10
______________

pip uninstall jsonschema
pip install jsonschema==2.6

**Comment by harthf** [comment]
Is it possible to explain this in detail because I am a novice in programming, thank you

**Comment by lovrom23** [comment]
In your command prompt (cmd) on Windows 10 type:
cd *location of Instapy directory* (it could be C:/Documents/Github...)
Now you are positioned in your Instapy directory. 
I'm assuming you then took command python setup.py install and got the error.
Now type pip uninstall jsonschema first and then pip install jsonschema==2.6

Try again python setup.py install and see if error shows.

**Comment by ynck-mxmln** [comment]
I have the same issue, 
Next issue cmd will not recognize commands pip nor sudo, it always responds : the command is either spelled wrong oder couldn't be found

**Comment by WSADKeysGaming** [comment]
pip says that jsonschema isn't installed in the first place, and when i install jsonschema==2.6 and run setup.py again it returns the same error
