### ISSUE TITLE
There are no any users available to unfollow

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#3639]
Unfollow stopped working as of tonight with this error:
![untitled](https://user-images.githubusercontent.com/36073534/50512362-6e5e9380-0a89-11e9-9f86-552c98790f50.jpg)
There are plenty users available to unfollow, but it still gives an error there are "none"

**Comment by Tachenz** [comment]
If I don’t use “instapy followed” - it works. So some sort of bug with register of instapy followed users, it looks like

**Comment by w4ngel** [comment]
I need to know;
Which browser are you using?
Is the followed_pool.csv filled with any names?
Can I see the line you are using in your quickstart.py in regards to the unfollow?

Cheers.

**Comment by Tidle999** [comment]
same for me, using chrome.

followed_pool.csv has 7500 entries.

quickstart.py looks like this:

session.unfollow_users(amount=500, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=12*60*60, sleep_delay=225)

newest instapy version installed, worked 1 month ago without any known changes.

referenced this here:
https://github.com/timgrossmann/InstaPy/issues/3753

**Comment by Danrrodrigues** [comment]
same for me, using chrome.

**Comment by bvstek** [comment]
Same issue here, using chrome, InstaPy updated yesterday

session.set_dont_unfollow_active_users(enabled=True, posts=12)
session.unfollow_users(amount=500, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=5*24*60*60, sleep_delay=60)

Log:
Gathered total of 723 unique active followers from the latest 12 posts in 0 minutes and 33 seconds
Unfollowing the users followed by InstaPy
Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 604
