### ISSUE TITLE
Failed to load desired amount of users. Grabbed 0 users to interact with (OLD AND PERSISTENT BUG)

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#3642]
## Expected Behavior
This renders unusable "follow someone else's followers" feature. When it worked, it would load a certain amount of target user followers and interact with them.
## Current Behavior
Instead of loading followers, this happens:
![47759439-88f1d780-dca7-11e8-8e29-1d02c6e32b09](https://user-images.githubusercontent.com/36073534/50538225-59a2fe00-0b64-11e9-8dfb-54c36ca5e23c.png)

It can skip through the entire list of users like that.   In the browser window, users are successfully loaded, BUT - in the script window it still says "grabbed 0".

@timgrossmann @uluQulu @sionking  Gentlemen, any ideas how to tackle this one?  
We do have quite a few people suffering from it, and looks like no one was able to come up with the solution...

**Comment by Tachenz** [comment]
Solution proposed here is not working -  https://github.com/timgrossmann/InstaPy/issues/3085
And couple more related topics got buried under the new issues:
https://github.com/timgrossmann/InstaPy/issues/3344
https://github.com/timgrossmann/InstaPy/issues/3467

**Comment by w4ngel** [comment]
Could you do a few things for me; 

Firstly, verify that the account actually logs in successfully- check this in the view of it rather than in headless.
Secondly, are those accounts that you are targeting private- and are you following them? 
Thirdly, could you send me the names of the accounts where it is happening- just some of the targets so I can test?

**Comment by Tachenz** [comment]
@w4ngel thank you - definitely logged in. The behaviour is - to load users from the target account SOMETIMES, and then hang in there skipping another 40-100 accounts with this error (to survive it I have a list of 100 accounts now, but sometimes it can go through it all without loading a single follower, or sometimes it can load couple hundred).

I also can see in browser window - script loading those accounts followers (while it says “loading users”). Then scrolling randomly stops (no error or anything in browser window) - and instapy returns this error and gets to the next target user. 
I do follow some of the users and don’t follow some of those where this error happens, none of them are private accounts.

I don’t think it is target user specific - as sometimes it grabs followers from the account it did not during the other run.
But some account examples from today would be:
Sfopera, musical.ly, songcovermusic

**Comment by Tachenz** [comment]
I also have latest pull, chromedriver, etc. But this bug happened on previous versions - as you can see from the links I’ve listed above. 
There was an attempt at solution here:
https://github.com/timgrossmann/InstaPy/issues/3085

But it stopped working, maybe same logic can be used again to fix it?

**Comment by Tachenz** [comment]
![6b4b7f20-9f7e-4d0c-bd70-54b43ed31835](https://user-images.githubusercontent.com/36073534/50538634-22cfe680-0b6a-11e9-8684-1b311477f59b.png)
This is happening in the browser window while the script gives an error.
Someone said it may have to do with dialogue showing “suggestions for you” at some point...

**Comment by w4ngel** [comment]
I will see if I can try and replicate.

**Comment by Tachenz** [comment]
You can see on the screenshot, under each user it says “new to instagram, or followed “by-your-friend”. 
That seems to be an indicator that it stopped loading plain followers and started on “suggestions for you”. Which instapy, maybe, does not know how to deal with...

**Comment by Tachenz** [comment]
@w4ngel no luck?

**Comment by Tachenz** [comment]
This night it was cycling through accounts without grabbing a single follower...

**Comment by w4ngel** [comment]
I haven't managed to replicate it yet. I am still trying can I see your configuration?

**Comment by Tachenz** [comment]
Sure - Mine is used in combination with putting a 40 sec sleep delay after every like the script does.
So then it runs 24/7 at rather slower speed, but without problems (so far). Would interact with user followers, liking 3 pictures, doing 1-2 comment - and 25% chance of follow (ratios which work the best for my account):

from instapy import InstaPy
import os
session = InstaPy(username=' ', password='')
session.login()
session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
session.set_relationship_bounds (enabled=True, potency_ratio=None, delimit_by_numbers=True, max_followers=3000, max_following=900, min_followers=50, min_following=50)
session.set_simulation(enabled=False)
session.set_do_like(enabled=True, percentage=100)
session.set_ignore_users(['])
session.set_do_comment(enabled=True, percentage=35)
session.set_do_follow(enabled=True, percentage=25, times=1)
session.set_comments(['])
session.set_ignore_if_contains([])
session.interact_user_followers([], amount=340)
session.end()

**Comment by Tachenz** [comment]
So the problem is that instagram showing “suggested” users instead of someone else followers.
And the button “see all suggestions” at the bottom of “followers” window.

Am I really the only one getting this? :)

**Comment by thejeromelouis** [comment]
I have the same problem. Do you already found a solution?

**Comment by Tachenz** [comment]
No solution... everyone just gave up I guess
