### ISSUE TITLE
quickstart.py error

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#3644]
Hello 

> sudo python3 quickstart.py

`Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/root/Documents/Bots/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/root/Documents/Bots/InstaPy/instapy/instapy.py", line 21, in <module>
    from .unfollow_util import follow_given_user
ImportError: cannot import name 'follow_given_user`

What is the problem please ?
`

**Comment by Tr1pke** [comment]
first of all don't do this as a root user, you can't run sh*t as an root user !
and how does you .py file looks like? can you paste it here?
seems there is something not correct in the quickstart.py maybe here or there you typed something wrong...
