### ISSUE TITLE
I want Follow Someone else's followers

### ISSUE THREAD

**Issue by EvraCloak** [InstaPy/InstaPy#3652]
Hi everybody. I just want follow someone else's followers one by one on followers list and with no skip and no relationship ratio. But I didn't succesful. I'm getting that error.

""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = 'xxxx'
insta_password = 'axxx'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=False,
				 potency_ratio=1.34,
				  delimit_by_numbers=True,
				   max_followers=8500,
				    max_following=4490,
				     min_followers=10,
				      min_following=56,
				       min_posts=10,
                max_posts=1000)
                session.set_skip_users(skip_private=True,
                       private_percentage=0)
    session.follow_user_followers(['japonixx'], amount=1000, randomize=False, sleep_delay=30)

**And my cmd panel's showed this error>**

C:\Users\WIN7\Desktop\InstaPy-master>py quickstart.py
  File "quickstart.py", line 31
    session.set_skip_users(skip_private=True,
    ^
IndentationError: unexpected indent

**Comment by nikartz** [comment]
The **IndentationError: unexpected indent**-Error is outputted because you have a problem with spacing. [There is already a way better explanation out there, than I could ever deliver.](https://stackoverflow.com/questions/1016814/what-to-do-with-unexpected-indent-in-python)

In shot: make sure you have the same spacing in the lines. The spacing should only change, if there is a new subblock.
Good:
```
    line1
    line2
```

Bad:
```
   line1
     line2
```

**Comment by AvocadoStyle** [comment]
```
session.set_skip_users(skip_private=True,
private_percentage=0)
```
write it in one line and check it 
`session.set_skip_users(skip_private=True, private_percentage=0)`
like that...
