### ISSUE TITLE
Unable to locate 'Followers' and 'Following'

### ISSUE THREAD

**Issue by abjoe91** [InstaPy/InstaPy#3653]
Hi all!
I get this message when I try to follow users followers:

NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Followers' or text()='Following']/../../following-sibling::div"}
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)

I know there were some similar issues regarding the ''Log in' button but I'm not sure how to solve this. Has anybody experienced the same problem?
Thanks in advance.

**Comment by AvocadoStyle** [comment]
can you make a screen record from the moment you run it to the moment it's exits?
configure:
`headless_browser=False`
and show me when it's exits... will be much easier for me/us to see exactly where it's fails without looking in the code.
### (screen record of the chrome driver i mean with the cmd logs in the same time)
