### ISSUE TITLE
How to get the list of follower of a given username ?

### ISSUE THREAD

**Issue by bioinfornatics** [InstaPy/InstaPy#3657]
Dear,
Firstly thanks for your amazing library. 

## Current Behavior
The following statement return always a list of 0 element:

```python
session.grab_followers(username="foo", amount="full", live_match=True, store_locally=True)
```

## Expected Behavior

I thought that the `grab_followers` function return the current list of follower
I would like to get for each follower the amount of follower and following

## InstaPy configuration
linux, python3, firefox

**Comment by gitpatrickhub** [comment]
It's likely related to the issue in #3444 given that you are using Firefox

**Comment by bioinfornatics** [comment]
@gitpatrickhub thanks for your quick reply.
I have done an update (git pull), build (bdist_wheel) and install and I have still the same problem.
So it seem that is not yet fixed

**Comment by gitpatrickhub** [comment]
Hmm...if you are running it non-headless can you see where it is failing in the browser?

**Comment by bioinfornatics** [comment]
@gitpatrickhub happy new year :+1: 

So I run the application in debug mode.

At the function:

```
def grab_following(self, username=None, amount=None,  live_match=False, store_locally=True)
```

the application state is:

```(Pdb) a
self = <instapy.instapy.InstaPy object at 0x7f158a9b9e80>
username = 'someoneToo'
amount = 'full'
live_match = True
store_locally = True
```

```
INFO [2019-01-01 16:42:14] [someone]  Retrieving live `Followers` data of someoneToo at "full" range



INFO [2019-01-01 16:42:45] [lucie_beartmagazine]  Unable to get `Followers` data:
	b'Message: Unable to locate element: pre\n'
```

Nonetheless I see from the latest commit your suggestion ( #3444 ) to set url to `view-source:...` at line 57 of `relationship_tools.py`

but the browser do not open with the given prefix. I will install and install again Instapy maybe the installer as found that they are nothing new  to do.

**Comment by bioinfornatics** [comment]
Ok I found it was a conflict between wheel and egg sorry.

Thanks for your help

have a nice day
