### ISSUE TITLE
How do I get the bot to comment and follow?

### ISSUE THREAD

**Issue by Pootisman1232** [InstaPy/InstaPy#3658]
I read the instructions given on the git file itself on how to make the bot comment and follow as well, but I still don't get it. My bot can only like at the moment. It would be great if someone could give me step by step instructions. Thanks!

**Comment by AvocadoStyle** [comment]
`session.follow_user_followers([name], amount=amount, randomize=True, sleep_delay=500)`
use this comment, in the `name` for example put the name of the instagram owner, for example:
`session.follow_user_followers(['daniel_biton'], amount=amount, randomize=True, sleep_delay=500)`
this comment will follow the user followers, so choose wisely the instagram account you gonna choose...
@Pootisman1232
