### ISSUE TITLE
issue while using pythonanywhere

### ISSUE THREAD

**Issue by irfumafazath** [InstaPy/InstaPy#3661]
i am getting this error while running example.py on pythonanywhere. i installed clarifai too.

ImportError: cannot import name 'get_user_info' from 'src.user_info' (/home/xxxxxx/instabot.py/src/user_info.py)

**Comment by irfumafazath** [comment]
which file should i run in order to make it work?

**Comment by timgrossmann** [comment]
@irfumafazath Wrong bot repo...
This is InstaPy, not `instabot.py`
