### ISSUE TITLE
Phew! Last follow is not verified.

### ISSUE THREAD

**Issue by roncam82** [InstaPy/InstaPy#3664]
im using the latest follo_unfollow but im getting

Phew! Last follow is not verified.

can you help please ?

**Comment by s-h-a-d-o-w-pixel** [comment]
Every follow I do gets me that error. Everything works fine on my phone.

**Comment by brahimdev** [comment]
me too time to time but finnaly when stoped for a while like 2 days,it will go oki

**Comment by x225am** [comment]
I had same messages some time. To fix it I have to stop bot for one or two days. However on one of the mine friend account it constantly shows this notification. Is it ban from Instagram?

**Comment by FN17** [comment]
Error Message:
Phew! Last follow is not verified - might be temporarily blocked from following

Hidden Username and Password for this Site
can anyone help? Many thanks

//My Script

import random
from instapy import InstaPy
from instapy.util import smart_run

insta_username = ''
insta_password = ''

dont_likes, targets, comments, ignore_users, friends, ignore_list = ([] for i in range(6))

dont_likes = ['porn', 'pommes', 'fritten', 'sex', 'nude', 'naked', 'beef', 'pork', 'seafood',
              'egg', 'chicken', 'cheese', 'sausage', 'lobster', 'dönner', 'milch', 'sex',
              'fisch', 'schwein', 'lamm', 'rind', 'kuh', 'meeresfrüchte', 'ente',
              'schaf', 'ziege', 'hummer', 'yoghurt', 'joghurt', 'dairy', 'ketchup',
              'meal', 'food', 'eat', 'pancake', 'cake', 'dessert', 'ei',
              'protein', 'essen', 'mahl', 'breakfast', 'lunch',
              'dinner', 'turkey', 'truthahn', 'plate', 'bacon',
              'sushi', 'burger', 'salmon', 'shrimp', 'steak',
              'schnitzel', 'goat', 'oxtail', 'mayo', 'fur', 'leather',
              'cream', 'hunt', 'gun', 'shoot', 'slaughter', 'pussy',
              'breakfast', 'dinner', 'lunch']

like_tag_list = ['smoothie', 'instafood', 'foodporn', 'foodie', 'yummi', 'pancakes',
                 'eatclean', 'glutenfree', 'salad', 'vegan', 'cleaneating', 'avocado',
                 'healthychoices', 'homemade', 'fruits', 'vegetables', 'lowcarb',
                 'rezept', 'recipe', 'fitfood', 'healthyfood', 'veganfood']

targets = ['target']

comments = [u'👍', u'🐸', u'👌']

for x in range(48):

## Browser unsichtbar im Hintergrund wegen headless_browser=True
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      	headless_browser=True,
                      		disable_image_load=True,
                      			multi_logs=True)

    with smart_run(session):

        ## Losgehts
        session.set_dont_include(friends)
        session.set_dont_like(dont_likes)
        session.set_ignore_if_contains(ignore_list)
        session.set_ignore_users(ignore_users)
        session.set_simulation(enabled=True)
        session.set_relationship_bounds(enabled=True,     
                    potency_ratio=None,                   
                    delimit_by_numbers=True,
                    max_followers=7500,                   
                        max_following=3000,               
                        min_followers=25,                
                        min_following=25,                
                        min_posts=10)                     
        session.set_skip_users(skip_private=True,         
                                    skip_no_profile_pic=True,   
                                    skip_business=True)   
                               
        
        session.set_user_interact(amount=2, randomize=True, percentage=80, media='Photo')
        session.set_do_like(enabled=True, percentage=90)
        session.set_do_comment(enabled=True, percentage=15)
        session.set_comments(comments, media='Photo')
        session.set_do_follow(enabled=True, percentage=40, times=1)
               
        
        number = random.randint(3, 5)
        random_targets = targets
        if len(targets) <= number:
            random_targets = targets
        else:
            random_targets = random.sample(targets, number)

        
     
        session.follow_user_followers(random_targets, amount=random.randint(50,80), randomize=True, sleep_delay=900, interact=True)

        session.unfollow_users(amount=random.randint(75,100), InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=24*60*60, sleep_delay=900)
        session.unfollow_users(amount=random.randint(75,100), InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=72*60*60, sleep_delay=900)

**Comment by GGaitanis** [comment]
+1
