### ISSUE TITLE
`unfollow_users` doesn't always unfollow + introduce `doublecheckUnfollow`

### ISSUE THREAD

**Issue by oskarkrawczyk** [InstaPy/InstaPy#3665]
Sometimes the script insists I have `0` users to unfollow that were auto-followed, but in fact I have at lest 300 more users that should have been unfollowed.

I've experienced this a few weeks before, which is why I opted out of using that feature, thought this might have been fixed so tried again. I see some users keep having this issue.

## Expected Behavior

`unfollow_users` should unfollow all bot-followed users if set up this way.

## Current Behavior

`unfollow_users` sometimes does unfollow all auto-followed users, but sometimes leaves hundereds as unfollowed when in actuality they are not.

## Possible Solution (optional)

While not a real solution to the bug, perhaps adding a `doublecheckUnfollow=True` option to the `unfollow_users` would make sense? I'd sacrifice some time, if it would make the script more accurate in unfollowing.

## InstaPy configuration

```python
session.unfollow_users(
    amount=1000,
    InstapyFollowed=(True, "all"),
    style="FIFO",
    unfollow_after=1*60*60,
    sleep_delay=60
)
```

**Comment by sionking** [comment]
unfollow_after put to None if you want to unfollow all no metter the time

**Comment by oskarkrawczyk** [comment]
Obviously I'm running that after the `unfollow_after` time has passed. Setting `None` makes no difference in my case.

**Comment by oskarkrawczyk** [comment]
I've checked this again, and the same thing happened.

Followed ~250 accounts, then ran unfollowing, but it unfollowed ~150, insisting there is nothing more to unfollow.

@sionking What info can I provide so it's easier to debug this?

**Comment by butaminas** [comment]
Same here. Followed a lot of users and it only shows there is 1 user to unfollow. Anyone else having this problem?

**Comment by oskarkrawczyk** [comment]
@butaminas never had this bug manifest to that extent (you sure you're using `unfollow_after=None`?), but it keeps happening over and over.

I can't really figure out how to replicate the problem or what debug info I can provide.

@timgrossmann any chance you could let me know how can I help providing debug info about this issue?

**Comment by oskarkrawczyk** [comment]
It just occurred to me, is it possible that the log file would get confused or misrepresented the correct state because two separate instances of InstaPy were running concurrently?

I know I've ran two scripts to follow and unfollow at the same time.

**Comment by oskarkrawczyk** [comment]
Tried again, resetted all, ran a single follow instance, and unfollow after the designated time.

Issue remains, from the 400 users that were followed, only ~200 were unfollowed.

**Comment by oskarkrawczyk** [comment]
A bit more info.

As you can see the script tells me users were unfollowed:

```
INFO [2019-01-10 07:29:30] [oskarkrawczyk]  Ongoing Unfollow [22/123]: now unfollowing 'b'jake.j.gerrard''...
INFO [2019-01-10 07:29:38] [oskarkrawczyk]  --> Unfollowed 'jake.j.gerrard'!
INFO [2019-01-10 07:29:38] [oskarkrawczyk]  	Removed '2019-01-09 17:26 ~ jake.j.gerrard ~ 206868217' from oskarkrawczyk_followedPool.csv file

INFO [2019-01-10 07:29:48] [oskarkrawczyk]  Ongoing Unfollow [23/123]: now unfollowing 'b'fuadshafiyev''...
INFO [2019-01-10 07:29:58] [oskarkrawczyk]  --> Unfollowed 'fuadshafiyev'!
INFO [2019-01-10 07:29:58] [oskarkrawczyk]  	Removed '2019-01-09 17:26 ~ fuadshafiyev ~ 3315033888' from oskarkrawczyk_followedPool.csv file

INFO [2019-01-10 07:30:10] [oskarkrawczyk]  Ongoing Unfollow [24/123]: now unfollowing 'b'v_e_d_a_5''...
INFO [2019-01-10 07:30:20] [oskarkrawczyk]  --> Unfollowed 'v_e_d_a_5'!
INFO [2019-01-10 07:30:20] [oskarkrawczyk]  	Removed '2019-01-09 17:27 ~ v_e_d_a_5 ~ 4332376006' from oskarkrawczyk_followedPool.csv file

INFO [2019-01-10 07:30:30] [oskarkrawczyk]  Ongoing Unfollow [25/123]: now unfollowing 'b'adembavictor''...
INFO [2019-01-10 07:30:40] [oskarkrawczyk]  --> Unfollowed 'adembavictor'!
INFO [2019-01-10 07:30:40] [oskarkrawczyk]  	Removed '2019-01-09 17:27 ~ adembavictor ~ 5631522099' from oskarkrawczyk_followedPool.csv file
```

In reality, none of them were - checked manually.

<img width="472" alt="screen shot 2019-01-10 at 07 33 39" src="https://user-images.githubusercontent.com/34213/50950383-10c73f80-14aa-11e9-8656-4a84872fb31d.png">
<img width="511" alt="screen shot 2019-01-10 at 07 33 29" src="https://user-images.githubusercontent.com/34213/50950385-11f86c80-14aa-11e9-9df6-1e522cb4f9ec.png">
<img width="479" alt="screen shot 2019-01-10 at 07 33 02" src="https://user-images.githubusercontent.com/34213/50950388-13c23000-14aa-11e9-9978-7e0b74d5c466.png">
<img width="503" alt="screen shot 2019-01-10 at 07 32 45" src="https://user-images.githubusercontent.com/34213/50950392-14f35d00-14aa-11e9-83e6-5778633fb564.png">

**Comment by oskarkrawczyk** [comment]
Looks like this issue is not going to be addressed.

Feel free to close the ticket if no work is planned to fix the problem.

**Comment by sionking** [comment]
@uluQulu changes to unfollow structure, ppl start getting those issues.
