### ISSUE TITLE
interact_user_followers <- Failed to get the user ID and image list to like

### ISSUE THREAD

**Issue by the-unknown** [InstaPy/InstaPy#3668]
## Expected Behavior
When using `interact_user_followers`, you should be able to like and comment on the pictures of these users.. but it seems that this is not the case... 
## Current Behavior
if I use `interact_user_followers` and want to like on the images of the picked accounts, I get the follwoing response:
```
INFO [2019-01-02 17:17:23]  Username [1/1]
INFO [2019-01-02 17:17:23]  --> account_name_here
INFO [2019-01-02 17:17:23]  username actions: following=True commenting=False liking=True
INFO [2019-01-02 17:17:23]  Getting account_name_here image list...
INFO [2019-01-02 17:17:50]  There are possibly less posts than 3 in account_name_here's profile page!
INFO [2019-01-02 17:17:52]   --> Followed 'account_name_here'!
ERROR [2019-01-02 17:18:18]  Failed to get the user ID of account_name_here' from post page!
INFO [2019-01-02 17:18:18]  --> account_name_here added to blacklist for steal_follower campaign (action: followed)
INFO [2019-01-02 17:18:22]  -------------
INFO [2019-01-02 17:18:22]  --> Given amount not fullfilled, image pool reached its end
```

The corresponding user does of course have quite a lot images, but somehow the script fails to get the links.

## InstaPy configuration

```
session.login()
session.set_action_delays(enabled=True, like=5, comment=5, follow=4, randomize=True, random_range=(70, 140))
session.set_skip_users(skip_private=True, skip_no_profile_pic=True, no_profile_pic_percentage=100)
session.set_blacklist(enabled=True, campaign='steal_follower')  
session.interact_user_followers(['large_account'], amount=3, randomize=True) 
session.end()
```

**Comment by eneasz** [comment]
I occasionally see the same problem, not sure what is causing it.

**Comment by KonstantinGreat** [comment]
Have the same logs 
my code:
`set_relationship_bounds()
set_skip_users()
set_simulation()
follow_by_locations()`

log:
> User: 'some_user'
> Last follow is verified after reloading the page!
> --> Followed 'some_user'
> **Failed to get the user ID of**'some_user' from post page!

then next account 


What means error about user ID?
