### ISSUE TITLE
Running start.bat guidance

### ISSUE THREAD

**Issue by DBS9** [InstaPy/InstaPy#367]
When I run start.bat, nothing happens it just closes instantly, and when I open Instapy GUI and try to run I get an error saying start.bat is denied? Can anyone help please. I've probably set things up wrong, and I admit that but I'd love some guidance.

**Comment by timgrossmann** [comment]
@DBS9 Do you run it with root rights?

**Comment by 100xlongx** [comment]
I'm also having this issue. I am running the program as an administrator. This is my setup.

```python
from instapy import InstaPy
import os
session = InstaPy(username='username', password='password')
session.login()
session.like_by_tags(['#animals'], amount=50, media='Photo')

session.end()
```

I don't have any logs or anything either.

**Comment by timgrossmann** [comment]
@raaedk Could you try removing the `media` parameter, please?

**Comment by 100xlongx** [comment]
Just an update that may help others. Removing the media parameter didn't change anything. I ended up deleting the folder and reinstalling after updating python and that solved my issue. There probably was an error in how I installed it.
