### ISSUE TITLE
Too Many Requests Sent! -sleeping a bit

### ISSUE THREAD

**Issue by EvraCloak** [InstaPy/InstaPy#3670]
I always get this error after 5 simulated follows. How can i fix it ? And I wonder to how can i reduce " slepping a bit " time ?

## InstaPy configuration

"""
This template is written by @loopypanda

What does this quickstart script aim to do?
- My settings is for running InstaPY 24/7 with approximately 1400 follows/day - 1400 unfollows/day running follow until reaches 7500 and than switch to unfollow until reaches 0.
"""

from instapy import InstaPy
from instapy.util import smart_run

# get a session!
session = InstaPy(username='xxx', password='xxx')

# let's go! :>
with smart_run(session):
    # general settings

    session.set_relationship_bounds(enabled=True, delimit_by_numbers=False, max_followers=12000, max_following=4500, min_followers=35, min_following=35)
    session.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')
    session.set_do_follow(enabled=True, percentage=100)
    session.set_do_like(enabled=True, percentage=100)
    session.set_comments(["👊", "👍"])
    session.set_do_comment(enabled=True, percentage=80)
    session.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')

    # activity

    session.interact_user_followers(['x1', 'x2'], amount=8000, randomize=True)
    session.follow_user_followers(['x1', 'x2'], amount=8000, randomize=False, interact=True)
    session.unfollow_users(amount=7500, nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=3)

My Terminal Showed me >
...............................................................
INFO [2019-01-03 01:19:52] [kblycolak]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-01-03 01:19:52] [kblycolak]  Saving account progress...
INFO [2019-01-03 01:19:58] [kblycolak]  User 'halilgokcez' [1/2]
INFO [2019-01-03 01:20:16] [kblycolak]  Simulated follow : 1
INFO [2019-01-03 01:20:20] [kblycolak]  --> Followed 'b'alptugrull''!

INFO [2019-01-03 01:20:39] [kblycolak]  Simulated follow : 2
INFO [2019-01-03 01:20:42] [kblycolak]  --> Followed 'b'aslibalci_photography''!

INFO [2019-01-03 01:21:05] [kblycolak]  Simulated follow : 3
INFO [2019-01-03 01:21:08] [kblycolak]  --> Followed 'b'aaleynakaratepe''!

INFO [2019-01-03 01:21:25] [kblycolak]  Simulated follow : 4
INFO [2019-01-03 01:21:29] [kblycolak]  --> Followed 'b'alliikeskin''!

INFO [2019-01-03 01:21:52] [kblycolak]  Simulated follow : 5
INFO [2019-01-03 01:21:57] [kblycolak]  --> Followed 'b'ece.levi''!

INFO [2019-01-03 01:22:31] [kblycolak]  Too many requests sent!  attempt: 1  |  gathered links: 1028    ~sleeping a bit
INFO [2019-01-03 01:31:45] [kblycolak]  Simulated follow : 6
INFO [2019-01-03 01:31:49] [kblycolak]  --> Followed 'b'yusuf.subasi''!

INFO [2019-01-03 01:32:09] [kblycolak]  Simulated follow : 7
INFO [2019-01-03 01:32:13] [kblycolak]  --> Followed 'b'_tubabalkz''!

INFO [2019-01-03 01:32:28] [kblycolak]  Simulated follow : 8
INFO [2019-01-03 01:32:33] [kblycolak]  --> Followed 'b'ogiminati''!

INFO [2019-01-03 01:32:48] [kblycolak]  Simulated follow : 9
INFO [2019-01-03 01:32:53] [kblycolak]  --> Followed 'b'samet_gbg''!

INFO [2019-01-03 01:33:08] [kblycolak]  Simulated follow : 10
INFO [2019-01-03 01:33:15] [kblycolak]  --> Followed 'b'serhateracun''!

INFO [2019-01-03 01:33:36] [kblycolak]  Simulated follow : 11
INFO [2019-01-03 01:33:41] [kblycolak]  --> Followed 'b'omer.caliskanerler''!

INFO [2019-01-03 01:33:55] [kblycolak]  Simulated follow : 12
INFO [2019-01-03 01:33:58] [kblycolak]  --> Followed 'b'aslndabirkonuvar''!

INFO [2019-01-03 01:34:18] [kblycolak]  Simulated follow : 13
INFO [2019-01-03 01:34:22] [kblycolak]  --> Followed 'b'naraquecyy''!

INFO [2019-01-03 01:34:49] [kblycolak]  Too many requests sent!  attempt: 2  |  gathered links: 2074    ~sleeping a bit

**Comment by chamo1116** [comment]
I have the same issue recently I start to unfollow

**Comment by marcellosa** [comment]
Yep, have the same issue here, any solutions? thank you!
