### ISSUE TITLE
How to randomize comment list ?

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#3671]
session.set_comments(["😀", "😁", "😂", "🤣", "😃", "😄", "😅", "😆", "😉", "😊", "😋", "😎", "😍", "😘", "😗")]

Does this comment from first to last, or how do i make it comment emoji in random order ?

**Comment by guifelix** [comment]
@loopypanda  just google how to select random element in python -> [here](http://lmgtfy.com/?q=python+how+to+select+random+element+from+array)
