### ISSUE TITLE
Account got banned after creating new cookie

### ISSUE THREAD

**Issue by octavius-1** [InstaPy/InstaPy#3673]
I’ve been running instapy for more than two months, today, after the session was started, a Message saying “Issue with cookie for user my_user. Creating new cookie... showed up and right after 20 minutes my account got banned for liking. Any ideas?
I never exceed more than 100 likes Per hour or 30 follows per hour

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by w4ngel** [comment]
Could I see your quickstart.py, how long did you run it daily? How old was your account? What following and follower counts were you on your actual account?

**Comment by octavius-1** [comment]
I run it all Day long with random sleep times at night. My account is 6 years old. The account has 5k followers and 1500 following.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by w4ngel** [comment]
I need to see your configuration, I am currently working on some more security features so it would help to know what settings you had everything on. 

Instagram is taking a bit of a stand against liking. 100 likes an hour is quite high, to be honest. Especially if it's running 24/7 with sleeps.

**Comment by octavius-1** [comment]
```
from instapy import InstaPy
from instapy.util import smart_run
import time
import random
from personal_lib import emoji_lib as mj
from personal_lib import botty_lib as bl
from personal_lib import wrappers as w
import datetime
from functools import partial
import sys

if len(sys.argv)!=2:
        print ("Usage: python instabot.py username")
        sys.exit(1)
info = __import__(sys.argv[1])


while True:
    exception_happened = False
    """
    Time handling is happening here
    """
    sleep_time = random.randint(0, 2)
    wake_time = random.randint(6,9)
    while True:
        actual_hour = datetime.datetime.now().hour
        if actual_hour < sleep_time or actual_hour >= wake_time:
            print ("*-*- Time is ok, continue")
            break;
        else:
            multiplier = random.randint(1,6)
            print ("*-*- Sleeping " + str(multiplier*10) +  " minutes because actual hour is " + str(actual_hour))
            time.sleep(multiplier*10*60)

    session = InstaPy(username=info.insta_username,
                      password=info.insta_password,
                      nogui=True,
                      headless_browser=True,
                      disable_image_load=True,
                      page_delay=info.page_delay
                      )

    bl.smart_sleep(min_range=1, max_range=30, multiplier=1, minimum=30)

    with smart_run(session):
        """ Activity flow """
        # settings
        w.initial_parameters_wrapper(session, info)

        while True:
            if exception_happened:
                break
            start_time = time.time()
            actual_hour = datetime.datetime.now().hour
            if actual_hour < sleep_time or actual_hour >= wake_time:
                print ("-*-* Executing because actual hour is : " + str(actual_hour))
                print ("-*-* And sleep/wake times are " + str(sleep_time) + "-" + str(wake_time) + " HRS")
                stats=bl.stats_save(session)
                """
                ACTIONS ARE WRITTEN HERE
                """
                actions=[]

                if info.list_of_emojis:
                    comments=mj.build_message(
                            info.list_of_emojis,
                            max_rep=3,
                            repeat_emoji=info.repeat_emoji
                            )
                    session.set_comments(comments)
                if info.like_by_tags_enabled:
                    actions.append(partial(w.like_by_tags_wrapper, session, info))
                if info.interact_user_followers_enabled:
                    actions.append(partial(w.interact_user_followers_wrapper, session, info))
                if info.follow_likers_enabled:
                    actions.append(partial(w.follow_likers_wrapper, session,info))
                if info.unfollow_users_enabled:
                    actions.append(partial(w.unfollow_users_wrapper, session, info))
                if info.like_by_locations_enabled:
                    actions.append(partial(w.like_by_locations_wrapper, session, info))
                if info.like_by_feed_enabled:
                    actions.append(partial(w.like_by_feed_wrapper, session, info))

                random.shuffle(actions)

                for action in actions:
                    try:
                        action()
                    except Exception as e:
                        print(e)
                        print ("Exception happened, restarting")
                        exception_happened = True
                        break

                    bl.smart_sleep(min_range=1, max_range=360, multiplier=1, minimum=60)

                if random.randint(1,10) == 5:
                    print ("*-*- Taking a nap")
                    bl.smart_sleep(min_range=1, max_range=300, multiplier=5, minimum=300)
                else:
                    print ("*-*- Not taking a nap this time, continuing")
                bl.stats_print(session, stats, time.time()-start_time)
            else:
                print ("-*-* Going to hibernate because actual hour is : " + str(actual_hour))
                print ("-*-* And sleep/wake times are " + str(sleep_time) + "-" + str(wake_time) + " HRS")
                break
```

**Comment by sionking** [comment]
any datacenter proxy is banned for likes lately you need more advanced setup

**Comment by octavius-1** [comment]
@sionking What do you mean with more advanced setup?

**Comment by w4ngel** [comment]
Can I see your limits? I notice you don't use quota supervisor as well?

**Comment by octavius-1** [comment]
@w4ngel Could you please share with me a basic setup of quota supervisor?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by octavius-1** [comment]
@w4ngel Nevermind, find an easy way to implement it inside my initial_wrappers method. Any recommended limits? The accounts getting banned were not even reaching 100 likes per hour and it sleeps at night from 5-9 hours daily.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by w4ngel** [comment]
Do you know how many likes it was getting to per hour?

**Comment by octavius-1** [comment]
@w4ngel Sure, it was getting no more than 60 likes per hour. Which limits should I use? Or the block I'm getting is because it is running in AWS?

**Comment by w4ngel** [comment]
> @w4ngel Sure, it was getting no more than 60 likes per hour. Which limits should I use? Or the block I'm getting is because it is running in AWS?

60 is a lot for an hour. Are you running any other accounts on AWS? I wouldn't run directly with your server IP. Especially if it's AWS./Google Cloud etc.

**Comment by octavius-1** [comment]
@w4ngel is one like per minute a lot? And yes, I run three accounts per server in AWS running using the server IP. Which solution do you guys use to obtain secure proxy servers?

**Comment by w4ngel** [comment]
> @w4ngel is one like per minute a lot? And yes, I run three accounts per server in AWS running using the server IP. Which solution do you guys use to obtain secure proxy servers?

Yeah cause 1 like a minute adds up over a few hours. Three accounts running on AWS, that would be a contributing factor. I have a private corporation that provides proxies not available to the public sadly :(

**Comment by octavius-1** [comment]
@w4ngel Do you recommend one account per server? Also, do you use the native instapy proxy handling? I'll try with 50 likes per hour as a limit.
One more thing: I noticed the same behavior with the block triggering "like event". When interacting by hashtags one picture is liked and then instapy goes to that user page and starts liking, when the tool tries to like a picture that was liked before interaction, the block ocurrs.

**Comment by w4ngel** [comment]
> @w4ngel Do you recommend one account per server? Also, do you use the native instapy proxy handling? I'll try with 50 likes per hour as a limit.
> One more thing: I noticed the same behavior with the block triggering "like event". When interacting by hashtags one picture is liked and then instapy goes to that user page and starts liking, when the tool tries to like a picture that was liked before interaction, the block ocurrs.

I have a custom built proxy solution with InstaPy. I would recommend 1 account to 1 proxy. Hmmm... I'll look into that, it shouldn't try and double like the picture.

**Comment by octavius-1** [comment]
@w4ngel Attaching the logs while interacting by tags:

```
INFO [2019-01-05 20:27:04] [my_username]  [2/3]
INFO [2019-01-05 20:27:04] [my_username]  https://www.instagram.com/p/URL/
INFO [2019-01-05 20:27:07] [my_username]  Image from: b'username'
INFO [2019-01-05 20:27:07] [my_username]  Link: b'https://www.instagram.com/p/URL/‘
INFO [2019-01-05 20:27:07] [my_username]  Description: b’description’
INFO [2019-01-05 20:27:10] [my_username]  User: 'username'  |> followers: 351  |> following: 339  |> relationship ratio: 1.03
INFO [2019-01-05 20:27:15] [my_username]  --> Image Liked!
INFO [2019-01-05 20:27:18] [my_username]  --> Not commented
INFO [2019-01-05 20:27:19] [my_username]  --> Not following
INFO [2019-01-05 20:27:20] [my_username]  --> User gonna be interacted: 'username'
INFO [2019-01-05 20:27:20] [my_username]  Username [1/1]
INFO [2019-01-05 20:27:20] [my_username]  --> b'username'
INFO [2019-01-05 20:27:23] [my_username]  User: 'username'  |> followers: 351  |> following: 339  |> relationship ratio: 1.03
INFO [2019-01-05 20:27:23] [my_username]  Getting username image list...
INFO [2019-01-05 20:27:26] [my_username]  --> Not following
INFO [2019-01-05 20:27:27] [my_username]  Post [1/3]
INFO [2019-01-05 20:27:27] [my_username]  https://www.instagram.com/p/URL/
INFO [2019-01-05 20:27:30] [my_username]  Image from: b’username’
INFO [2019-01-05 20:27:30] [my_username]  Link: b'https://www.instagram.com/p/URL/‘
INFO [2019-01-05 20:27:30] [my_username]  Description: b’description’
INFO [2019-01-05 20:28:05] [my_username]  --> Image already liked!
``` 

And that was the last image liked before the 24 hour like-block

**Comment by ishandutta2007** [comment]
> Do you know how many likes it was getting to per hour?

What has it got to do with getting likes, celeb accounts gets hundreds of thousands of likes per hour?
I think limits should remain on liking others photos/comments etc, getting is not in your hand afterall.

**Comment by w4ngel** [comment]
> > Do you know how many likes it was getting to per hour?
> 
> What has it got to do with getting likes, celeb accounts gets hundreds of thousands of likes per hour?
> I think limits should remain on liking others photos/comments etc, getting is not in your hand afterall.

That's not what I meant. I meant how many likes was InstaPy told to do each hour. Sorry, bad grammar on my part.

**Comment by ishandutta2007** [comment]
reopen it

**Comment by octavius-1** [comment]
@ishandutta2007 What happened?

**Comment by ishandutta2007** [comment]
nothing, just testing the bot, if it can reopen or not.
