### ISSUE TITLE
Problem with proxy and headless browser

### ISSUE THREAD

**Issue by patacalas** [InstaPy/InstaPy#3676]
I'm using proxy server with credidentials. MITMProxy creates a local http proxy that transferred network traffic through the auth proxy. [Get more help here](https://stackoverflow.com/questions/46002582/chrome-in-headless-mode-provide-credentials-auth-for-proxy)

## Expected Behavior
Http proxy without authentication should work fine in headless browser mode

## Current Behavior
Getting this error
> selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: proxy
from invalid argument: Specifying 'socksProxy' requires an integer for 'socksVersion'

Chromedriver version 2.45.615279

## Possible Solution (optional)
Solutions that worked for me.

First solution: add proxy config directly in browser.py 
```
        if headless_browser:
            chrome_options.add_argument('--headless')
            chrome_options.add_argument('--no-sandbox')
            chrome_options.add_argument("--proxy-server=http://127.0.0.1:8090")
```

Second solution: delete `prox.socks_proxy = proxy` in browser.py and use standard proxy configuration in quickstart.py

**Comment by w4ngel** [comment]
This is only for chrome correct?

**Comment by w4ngel** [comment]
And did you make any other changes other than the solutions provided?

**Comment by patacalas** [comment]
> This is only for chrome correct?

Yes

> And did you make any other changes other than the solutions provided?

I only made that modification in browser.py. Actually using second solution.

**Comment by w4ngel** [comment]
Can you check if that pull request fixes the issue, please?

**Comment by patacalas** [comment]
Yes, it's fully working. Thanks!

**Comment by w4ngel** [comment]
@timgrossmann please close this issue.

**Comment by octavius-1** [comment]
@patacalas Where are you getting the proxies? I’m getting my accounts banned after running them directly in AWS.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by patacalas** [comment]
@octavius-1  like block?

I got like block issue running Instapy in my residential Internet connection. 
Using proxies don't solve the problem.
I think the problem is Instagram detecting the headless browser. 
[Here is some information about making Chrome headless undetectable](https://intoli.com/blog/making-chrome-headless-undetectable/).

**Comment by w4ngel** [comment]
@patacalas can you close this issue please?

Also in regards to Instagram detecting headless browser, while this is possible it is a extremely hostile practice to block browsers with those options. Just to put it into perspective, there are so many different configurations available for browsers, that they would more than likely end up blocking non-automated users or preventing access to parts of their site, chances are they wouldn't even block the more sophisticated automation tools.
