### ISSUE TITLE
interact_user_following don't work

### ISSUE THREAD

**Issue by gHashTag** [InstaPy/InstaPy#3683]
## Expected Behavior
Interact user following
## Current Behavior
Closes session with a message: 
Please enable following or liking in settings in order to do interactions.
Sessional Live Report:
	|> No any statistics to show
## InstaPy configuration
```python
session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
session.set_do_follow(enabled=False, percentage=70)
session.set_do_like(enabled=False, percentage=70)
session.set_comments(["Cool", "Super!"])
session.set_do_comment(enabled=True, percentage=80)
session.interact_user_following(['user1'], amount=10, randomize=True)
```

**Comment by octavius-1** [comment]
Well, that’s because your lines two and three have the parameter enabled=False

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gHashTag** [comment]
@octavius-1  Thanks 🙏🏻
How to make them like, but did not follow?

**Comment by jonap339** [comment]
Hi @gHashTag, I have the same problem. Could you solve it? thank you

**Comment by fxhuhn** [comment]
Hi, I have a similar same problem. The script only follow users, it is not liking or commenting.
