### ISSUE TITLE
I am here from Instabot, this seems better but..

### ISSUE THREAD

**Issue by remyx11** [InstaPy/InstaPy#3685]
## Expected Behavior
I'd really like a super simple script, which seems very easy but Im getting a headache in searching..

I just need some tags that will be liked, no following/unfowlling and commenting. These tags need to be liked trough out the day, preferably during working hours and random. **Thats it.** 

With Instabot it just ran 24/7 and InstaPy runs only for one hour (or so) for some reason. I've heard about cron and so on, but I just don't have the knowledge to figure it out.. Is there like a really simple setting as in: run the whole day?

## Current Behavior
Tags are being liked, but it stops when all the tags are done. Also, im not sure if the set_action_delay command is working.

## InstaPy configuration
```
""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = ''
insta_password = ''

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=5500,
                                    min_followers=45,
                                    min_following=77)

    session.set_action_delays(enabled=True, like=10.2, randomize=True, random_range=(65, 150))
    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["naked", "sexy", 'sexy', 'hot', 'nsfw'])

    # activity
    session.like_by_tags(['tags, tags, tags'], amount=40)
```

**Comment by w4ngel** [comment]
If it's only running for an hour chance are you have limits to mean that it only runs for an hour, for example, it would only run for an hour or two when liking 40 images from three tags each. I would recommend using Quota Supervisor to make sure that appropriate sleeps are in place.

**Comment by Tr1pke** [comment]
to keep is simple just use crontab and screen
