### ISSUE TITLE
[QUESTION/SUGGESTION] IS there a way of "Get Likers" of photos/posts from hashtags

### ISSUE THREAD

**Issue by YHSX88** [InstaPy/InstaPy#3687]
## Expected Behavior
Steps:
1. Loop through list of hashtags
2. Get the posts (from hashtag) and randomly go from post to post
3. Open post
4. **GET LIKERS**
5. Interact with liker -> like, comment, follow
6. go to **next liker**
7. go to **next liker**
...
8. go to next **hashtag**

The point of this behavior is to target only users that have liked the certain photo from specific hashtag

## Current Behavior
Not possible currently with any function
```
session.follow_likers (img_users, 
                           photos_grab_amount = 5, 
                           follow_likers_per_photo = 2, 
                           randomize=True, 
                           sleep_delay=50, 
                           interact=True)
```
With the above function is possible to interact with likers but I need to know the users of the posts and I don't want to bother collecting users manually as it can get super time consuming.

By Using 
## Possible Solution (optional)
Can you tell me how I can change the current code locally to get the desire outcome.
Any suggestion is welcome.
For example #opalhouse has 8k posts, so imagine you want to target users interested in Opalhouse. So put the hashtag and then specify some limitations (to prevent from blocking) and you can do it so easy.

## InstaPy configuration
python 3.7
chromedriver 0.0.6

**Comment by Moneymaker01** [comment]
Hi there. I was trying to find an answer for the same "problem".
I've found a partial solution using the string **session.follow_likers (['user1' ']** in that way:

     session.follow_likers (["explore/tags/potatoes/"] ...)

Replacing 'user1' with "explore/tags/potatoes", using it as a username . It kinda works, but it only searches and follows EXPLORE photo's likers, as (I think) does not recognize the "/" symbol as a possible part of a username.

I hope someone could tell more about that. I would sincerely appreciate.

**Comment by YHSX88** [comment]
Hah, It won't be even marked with feature request label ...... such a wonderful and useful function.... It's just a shame !
