### ISSUE TITLE
'account' might be temporarily blocked from following but not

### ISSUE THREAD

**Issue by GraduErd** [InstaPy/InstaPy#3691]
When i try follow people manually i can follow, but since yesterday my bot is saying 'account' might be temporarily blocked from following . Is it instapys problem or accounts?

**Comment by octavius-1** [comment]
It could be a network block. I faced an issue like that months ago. I could not follow people when connected to my residencial WiFi (Bot was running there), but if I used my cellular connection instead, it was working the way it should.

**Comment by GraduErd** [comment]
> It could be a network block. I faced an issue like that months ago. I could not follow people when connected to my residencial WiFi (Bot was running there), but if I used my cellular connection instead, it was working the way it should.

I tried local and digitalocean. Both of them same :/

**Comment by GraduErd** [comment]
I tried my cellular, tried different droplet(digitalocean), tried different session(all of them about follow, i dont know like or comment is working or not) and i had no solution.

**Comment by lucanello** [comment]
From my investigations this follow/like block is bound to the specific Instagram account. Did you try to follow/like from the Instagram app or the web interface?
I once got the message that liking is disabled for my account for the next 24 hours. It might be the same for yours. But no worries, this ban is only temporary.

**Comment by mgconejero** [comment]
Somebody find a solution? same issue with AWS, cant follow there but i can with my phone

**Comment by DemonionFF** [comment]
Same here, likes/follows blocked from GCloud VM instance but works fine from mobile app.

**Comment by manuga93** [comment]
Same here, on my navigator I ca do it manually
