### ISSUE TITLE
Error while installing clarifai

### ISSUE THREAD

**Issue by irfumafazath** [InstaPy/InstaPy#3693]
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/PIL/.libs/libfreetype-6
ed94974.so.6.16.1'
Consider using the `--user` option or check the permissions.

--------------------------------------------------------
i am getting the above error while installing clarifai. i am running instapy in pythonanywhere

**Comment by zacjuntan** [comment]
@irfumafazath I'm having the same issue! Did you manage to figure it out?
