### ISSUE TITLE
Phyton learning newbie asking for a quick "tutoring"

### ISSUE THREAD

**Issue by Moneymaker01** [InstaPy/InstaPy#3695]
Hi everyone. Thanks to the "charm" of the script I'm starting to approach the world of programming. I'm taking Phython lessons on youtube, and slowly starting to understand something.
Starting from one of the templates, I've modified it a lot, and I've added many features. But more importantly, starting from scratch I have "studied" it, understanding the basic logic behind a Pyhthon script. (The road is still long...)

At this point, however, I need a quick tutoring on some points:
1) The script works well, but I would like to understand if _it is_ set up well, especially if all session.follow_likers and session.follow_commenters are all "tied" to the "only" session.set_user_interact. I can not understand if I have to repeat it every time.

2) I would like to add two functions, but I'm going crazy! I don't understand where and how  should I add them.

**The first one is to randomly like feed's posts:**
  ```
for x in range(1):
    myRandomFeed = random.randint(5,18)
    session.like_by_feed(amount=myRandomFeed, randomize=True)
```
**The second is to interact (example to comment) with people commenting/liking posts of a specific hashtag.** 
```
session.like_by_tags(['natgeo', 'world'], amount=10)
if self.interact_likers_of_tag_amount:
                                    self.logger.info('interact likers of tag:{}'.format(tag.encode('utf-8')))
                                    photo_likers = likers_from_photo(self.browser, self.interact_likers_of_tag_amount)
                                    self.interact_by_users(photo_likers,
                                                           amount=2,
                                                           randomize=randomize,
                                                           media=media,
                                                           source=('tag_likers', tag))
``` 

I hope someone can lose no more than 5 minutes, integrating the code with these two additions, and checking that everything is ok!
Humbly, all suggestions are welcome😊 

Thanks

**Comment by w4ngel** [comment]
So I am not too sure what you mean by the first question,
Regarding the second question though.

**The first one is to randomly like feed's posts:**
```
for x in range(1):
  myRandomFeed = random.randint(5,18)
  session.like_by_feed(amount=myRandomFeed, randomize=True)
```

You don't need to do this inside the `for` loop, you can just do it like this:

```
myRandomFeed = random.randint(5,18)
session.like_by_feed(amount=myRandomFeed, randomize=True)
```

**The second is to interact (example to comment) with people commenting/liking posts of a specific hashtag.**

```
session.like_by_tags(['natgeo', 'world'], amount=10)
if self.interact_likers_of_tag_amount:
                                    self.logger.info('interact likers of tag:{}'.format(tag.encode('utf-8')))
                                    photo_likers = likers_from_photo(self.browser, self.interact_likers_of_tag_amount)
                                    self.interact_by_users(photo_likers,
                                                           amount=2,
                                                           randomize=randomize,
                                                           media=media,
                                                           source=('tag_likers', tag))
```

Is this a suggestion to implement this feature?
