### ISSUE TITLE
Differentiate media type

### ISSUE THREAD

**Issue by axlright** [InstaPy/InstaPy#3703]
## Expected Behavior

```
session.set_comments(['Nice shot!'], media='Photo')
session.set_comments(['Great Video!'], media='Video')
```
Should function as described

## Current Behavior

Comments specified for `media='Video'` are added to images / non-videos

## InstaPy configuration

As described in https://github.com/timgrossmann/InstaPy#commenting

Issue also described in issues [#2007](https://github.com/timgrossmann/InstaPy/issues/2007) and [#1696](https://github.com/timgrossmann/InstaPy/issues/1696)

**Comment by m-ketan** [comment]
I'd be happy to look into this if someone can assign me this issue.
