### ISSUE TITLE
Feature Request: Following based on madatory words in the Bio

### ISSUE THREAD

**Issue by Nuzzo235** [InstaPy/InstaPy#3704]
## WHY

Happy new year to everyone! The topic was already in the discussion in the last year from time to time. It does not have a high priority for the masses, but can be helpful for a very targeted strategy in following competitors (and their followers) in a certain professional environment. Especially because the business categories are not helpful in this case. I have been quite successful in the past on large scaped follower lists and corresponding filters in Excel (semi-manually), do you think it makes sense to implement this directly in Instapy? 

## HOW

e.g. `session.follow_user_followers(['friend1'], amount=10, randomize=False, interact=True, bio_mandatory_words=['painter', 'artist'])`

## WHAT

Following based on madatory words in the bio of a user. This could be used to check the bio for the occurence of mandatory words before following. If none of the mandatory words is present, the user will not be followed. This feature could be helpful when you want to follow only users in very specific target groups.

Cheers, Nuzzo

**Comment by Tbit32** [comment]
Hi! I tried to insert this application but I'm having a bug:  "TypeError: follow_user_followers() got an unexpected keyword argument 'bio_mandatory_words''

Does anyone know how to fix it?

Thank you.

**Comment by Nuzzo235** [comment]
@Tbit32 Hey there, it doesn't work because it's not integrated into Instapy. Was just an idea / feature request as the heading already says. As long as it's not in the [documentation](https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md) it's not part of the code. Cheers!

**Comment by papillon-unix** [comment]
Does someone currently working on it? 
This feature would be very very useful to target more precisly the audience, 
also a way to not bother people who are not relevant.

**Comment by Nuzzo235** [comment]
@papillon-unix AFAIK an implementation is not planned at this time. I have neither the time and the knowledge, but also think that it is a good method of categorization of potential follower with only few errors. However, the many server requests for one match would be the bottleneck. Cheers
