### ISSUE TITLE
Traceback (most recent call last):   File "quickstart.py"

### ISSUE THREAD

**Issue by Thelooney** [InstaPy/InstaPy#3708]
Hey, I'm having a problem with opening quickstart.py I am pretty lost for a solution... Can anyone help me out or let me know what I've done wrong?

Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/Users/Jasper/Desktop/InstaPy-master/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users/Jasper/Desktop/InstaPy-master/instapy/instapy.py", line 14, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay
Jaspers-MBP:instapy-master Jasper$

**Comment by brocool** [comment]
write pip install pyvirtualdisplay

**Comment by Thelooney** [comment]
I get this...


error: could not create '/Library/Python/2.7/site-packages/easyprocess': Permission denied
error: could not create '/Library/Python/2.7/site-packages/easyprocess': Permission denied
--------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/xp/263yty916gg8j1mbtlm10jd00000gn/T/pip-install-exbXeD/EasyProcess/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/xp/263yty916gg8j1mbtlm10jd00000gn/T/pip-record-eIGPbi/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/xp/263yty916gg8j1mbtlm10jd00000gn/T/pip-install-exbXeD/EasyProcess/

**Comment by Thelooney** [comment]
> write pip install pyvirtualdisplay

I get this...

error: could not create '/Library/Python/2.7/site-packages/easyprocess': Permission denied
error: could not create '/Library/Python/2.7/site-packages/easyprocess': Permission denied
Command "/usr/bin/python -u -c "import setuptools, tokenize;file='/private/var/folders/xp/263yty916gg8j1mbtlm10jd00000gn/T/pip-install-exbXeD/EasyProcess/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /private/var/folders/xp/263yty916gg8j1mbtlm10jd00000gn/T/pip-record-eIGPbi/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/xp/263yty916gg8j1mbtlm10jd00000gn/T/pip-install-exbXeD/EasyProcess/
