### ISSUE TITLE
Ensure chromedriver is installed Raspberry Pi Model 3 B+

### ISSUE THREAD

**Issue by ReagentX** [InstaPy/InstaPy#3713]
## Expected Behavior

Quickstart script runs

## Current Behavior

Crashes with 
    instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/pi/Projects/InstaPy/assets/chromedriver
## Possible Solution (optional)

Solution listed under "Solve Ensure chromedriver is installed at .. (Tested on Raspberry Pi 3 B+)" at [this page](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Raspberry.md#solve-ensure-chromedriver-is-installed-at--tested-on-raspberry-pi-3-b) does not work.

## InstaPy configuration

Completely stock. 

## Enviornment
        (venv) pi@raspberrypi:~/Projects/InstaPy $ python --version
        Python 3.7.2
        (venv) pi@raspberrypi:~/Projects/InstaPy $ pip --version
        pip 18.1 from /home/pi/Projects/InstaPy/venv/lib/python3.7/site-packages/pip (python 3.7)
        (venv) pi@raspberrypi:~/Projects/InstaPy $ pip freeze
        certifi==2018.11.29
        chardet==3.0.4
        clarifai==2.5.1
        configparser==3.5.0
        EasyProcess==0.2.5
        emoji==0.5.1
        future==0.17.1
        googleapis-common-protos==1.5.5
        grpcio==1.17.1
        idna==2.8
        instagram-py==0.0.1
        jsonschema==2.6.0
        MeaningCloud-python==1.1.1
        plyer==1.4.0
        protobuf==3.6.1
        PyVirtualDisplay==0.2.1
        PyYAML==4.2b1
        regex==2018.11.22
        requests==2.21.0
        schedule==0.5.0
        selenium==3.141.0
        six==1.12.0
        urllib3==1.24.1
        (venv) pi@raspberrypi:~/Projects/InstaPy $ ls assets/
        business_categories.md  chromedriver

**Comment by JoeFertig** [comment]
Can you post the complete crash dialogue please?

**Comment by ReagentX** [comment]
pi@raspberrypi:~/Projects/InstaPy $ source venv/bin/activate
    (venv) pi@raspberrypi:~/Projects/InstaPy $ python --version
    Python 3.7.2
    (venv) pi@raspberrypi:~/Projects/InstaPy $ python quickstart.py
    ERROR [2019-01-11 23:31:39] [cs.photo]  Message: unknown error: Chrome failed to start: exited abnormally
    (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)
    Traceback (most recent call last):
    File "/home/pi/Projects/InstaPy/instapy/browser.py", line 122, in set_selenium_local_session
        chrome_options=chrome_options)
    File "/home/pi/Projects/InstaPy/venv/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
        desired_capabilities=desired_capabilities)
    File "/home/pi/Projects/InstaPy/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
        self.start_session(capabilities, browser_profile)
    File "/home/pi/Projects/InstaPy/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
        response = self.execute(Command.NEW_SESSION, parameters)
    File "/home/pi/Projects/InstaPy/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
        self.error_handler.check_response(response)
    File "/home/pi/Projects/InstaPy/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
        raise exception_class(message, screen, stacktrace)
    selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
    (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)

    Traceback (most recent call last):
    File "quickstart.py", line 14, in <module>
        headless_browser=False)
    File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 263, in __init__
        self.set_selenium_local_session()
    File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 315, in set_selenium_local_session
        raise InstaPyError(err_msg)
    instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/pi/Projects/InstaPy/assets/chromedriver

**Comment by ReagentX** [comment]
When I make [this line](https://github.com/timgrossmann/InstaPy/blob/31081d4bb0c11637750151fe13f4a678e9db52f4/quickstart.py#L14) `True` it seems to work and gets up to the point where it looks up hashtags, but then it crashes with the traceback people are reporting in #3712:

    Traceback (most recent call last):
    File "quickstart.py", line 30, in <module>
        session.like_by_tags(amount=10, use_smart_hashtags=True)
    File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 1674, in like_by_tags
        self.logger)
    File "/home/pi/Projects/InstaPy/instapy/like_util.py", line 537, in check_link
        ''', user_name)
    File "/home/pi/Projects/InstaPy/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
        'args': converted_args})['value']
    File "/home/pi/Projects/InstaPy/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
        self.error_handler.check_response(response)
    File "/home/pi/Projects/InstaPy/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
        raise exception_class(message, screen, stacktrace)
    selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'edges' of undefined
    (Session info: headless chrome=65.0.3325.181)
    (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)

**Comment by brunano21** [comment]
Hi, unfortunately, I'm having the same issue and setting `headeless_browser=True` didn't help.

**Comment by HCWcoder** [comment]
how many account you can run on RASPBERRY_Pi_3 ?
@brunano21 
@JoeFertig

**Comment by brunano21** [comment]
@HCWcoder I cannot run any script at the moment because of the `instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/pi/Projects/InstaPy/assets/chromedriver` error. By the way, I'm using a rpi B+ (revision 1.2).

**Comment by HCWcoder** [comment]
@brunano21 
oh thanks for reporting !
i was going to order my RPI B+ i will hold it for now

btw if its working how many account can you run on the same time ?

**Comment by JoeFertig** [comment]
> how many account you can run on RASPBERRY_Pi_3 ?
> @JoeFertig
You can run many accounts but you need a proxy.
I personaly run one account on one pi so every pi has its own ip.

**Comment by brunano21** [comment]
@ReagentX were you able to sort it out?

**Comment by HCWcoder** [comment]
> > how many account you can run on RASPBERRY_Pi_3 ?
> > @JoeFertig
> > You can run many accounts but you need a proxy.
> > I personaly run one account on one pi so every pi has its own ip.

so lets say 5 pi on the same wifi router will be safe ?

**Comment by JoeFertig** [comment]
> so lets say 5 pi on the same wifi router will be safe ?
Nope thats not safe.
For example: I have one Pi with two accounts and no proxie so I had to do a schedule routine that manages that there is only one account active per day.

Schedule:
Monday acc1
Tuesday acc2
Wednesday acc1
Thursday acc2
....

Otherwise insta is likely to ban your device and the IP.

**Comment by kinglabrador23** [comment]
I'm still getting the original error, chromedriver is definitely installed and in my PATH

**Comment by JoeFertig** [comment]
Then you haven't followed the steps correctly ;)
But no worries... I am testing a new tutorial for the Pi with Python3.7 and venv which is running pretty smooth atm.

**Comment by PhilippSPOTTERON** [comment]
Same Issue here: 
instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/pi/InstaPy/assets/chromedriver

(it should, installed via "Solve Ensure chromedriver is installed at .. (Tested on Raspberry Pi 3 B+)" section)

**Comment by PhilippSPOTTERON** [comment]
It seems the istructions are outdated:
this command:
echo "deb http://security.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list
uses a wrong url, which leads to install chromedriver not working.
the correct url is: http://security-cdn.debian.org/debian-security/

echo "deb http://security-cdn.debian.org/debian-security/ stretch/updates main" >> /etc/apt/sources.list
installs also the dependencies correctly, which seem to be missing otherwise. (should be updated)

With that, the command in the Solve Ensure chromedriver is installed at .. (Tested on Raspberry Pi 3 B+)" section
'sudo apt-get remove chromium'
works but.. still the same issue which running quickstart.py: instapy.instapy.InstaPyError: ensure chromedriver is installed at /home/pi/InstaPy/assets/chromedriver in the end :(

**Comment by brunano21** [comment]
@JoeFertig hey, any luck with the new tutorial?

**Comment by JoeFertig** [comment]
> @JoeFertig hey, any luck with the new tutorial?

Yes, tested and working fine.
I haven't PR now cause we had so much issues with instagram yesterday.
I will PR today.

**Comment by tomate10** [comment]
I have the same issue on my Pi 3. When I set `headless_browser=True` then it works fine, but I want to see the GUI. Can anyone help?

**Comment by PhilippSPOTTERON** [comment]
@JoeFertig : perhaps a stupid question: what means "PR"?

after unzipping the chromedriver-v3.0.0-beta.5-linux-arm7l.zip in the assets directory, is there another step which needs to be done? E.g. putting the directory in PATH (honestly, no idea how to do that)

**Comment by JoeFertig** [comment]
> @JoeFertig : perhaps a stupid question: what means "PR"?
PR = pull request. (google)
 
> after unzipping the chromedriver-v3.0.0-beta.5-linux-arm7l.zip in the assets directory, is there another step which needs to be done? E.g. putting the directory in PATH (honestly, no idea how to do that)
No you don't need a PATH but there are some final steps to do which are described in the tutorial ('chmod' stuff)
