### ISSUE TITLE
send auto DM to new followers -SOLUTION?

### ISSUE THREAD

**Issue by tranc3me** [InstaPy/InstaPy#3714]
Hi guys,

just wanted to know how do you send auto DM messages to new followers? Is there any way I can use this repo to make that feature available, If No what should I do ?

Can somebody point me in the right direction ?

**Comment by mkhattar** [comment]
You cannot send a DM when opening Instagram through a browser, so this feature is not available within Instapy.

**Comment by tranc3me** [comment]
@mkhattar I thought so,.. But there must be something you can do to make it happen?
Is there any other repo, program, anything that works without monthly charge?
