### ISSUE TITLE
Error on write *_followedPool.csv

### ISSUE THREAD

**Issue by TheXeon81** [InstaPy/InstaPy#372]
Error, when script open the file:

C:\InstaPy>py quickstart.py
Logged in successfully!
set_automated_followed_pool error
 list index out of range

**Comment by TheXeon81** [comment]
if delete the file i have this error

C:\InstaPy>py quickstart.py
Logged in successfully!
set_automated_followed_pool error
 [Errno 2] No such file or directory: './logs/thexeon_followedPool.csv'
Traceback (most recent call last):
  File "quickstart.py", line 6, in <module>
    session.unfollow_users(amount=10)
  File "C:\InstaPy\instapy\instapy.py", line 486, in unfollow_users
    unfollowNumber = unfollow(self.browser, self.username, amount, self.dont_include, onlyInstapyFollowed, self.automatedFollowedPool)
  File "C:\InstaPy\instapy\unfollow_util.py", line 37, in unfollow
    allfollowing = locale.atoi(browser.find_element_by_xpath("//li[3]/a/span").text)
  File "C:\Users\lucia\AppData\Local\Programs\Python\Python36\lib\locale.py", line 325, in atoi
    return int(delocalize(string))
ValueError: invalid literal for int() with base 10: '7,497'

**Comment by TheXeon81** [comment]
with another account i have this error:

C:\InstaPy>py quickstart.py
Logged in successfully!
set_automated_followed_pool error
 list index out of range
Traceback (most recent call last):
  File "quickstart.py", line 6, in <module>
    session.unfollow_users(amount=10)
  File "C:\InstaPy\instapy\instapy.py", line 486, in unfollow_users
    unfollowNumber = unfollow(self.browser, self.username, amount, self.dont_include, onlyInstapyFollowed, self.automatedFollowedPool)
  File "C:\InstaPy\instapy\unfollow_util.py", line 37, in unfollow
    allfollowing = locale.atoi(browser.find_element_by_xpath("//li[3]/a/span").text)
  File "C:\Users\lucia\AppData\Local\Programs\Python\Python36\lib\locale.py", line 325, in atoi
    return int(delocalize(string))
ValueError: invalid literal for int() with base 10: '7,497'

**Comment by timgrossmann** [comment]
@TheXeon81 Could you do a `git pull` and try again, please?

**Comment by TheXeon81** [comment]
after git pull...

C:\InstaPy>set PYTHONIOENCODING=UTF-8

C:\InstaPy>py quickstart.py
Logged in successfully!
set_automated_followed_pool error
 [Errno 2] No such file or directory: './logs/thexeon_followedPool.csv'
--> Ongoing Unfollow 1, now unfollowing: b'partyinmilan'

**Comment by timgrossmann** [comment]
@TheXeon81 don't you have the folder logs?

**Comment by TheXeon81** [comment]
![image](https://user-images.githubusercontent.com/5238466/27883759-fa4b03e0-61d1-11e7-96cd-992f693a5d8a.png)

![image](https://user-images.githubusercontent.com/5238466/27883776-09a86e9a-61d2-11e7-8da3-346c37eec859.png)

**Comment by TheXeon81** [comment]
![image](https://user-images.githubusercontent.com/5238466/27883791-1befbfa4-61d2-11e7-80b5-1c4ee2e82efb.png)


![image](https://user-images.githubusercontent.com/5238466/27883795-2102aa38-61d2-11e7-982d-0d586d1648b1.png)

**Comment by timgrossmann** [comment]
@TheXeon81 Hmm... I have to revisit that...
I'll get back once it's working

**Comment by timgrossmann** [comment]
@TheXeon81 Could you pull again?

**Comment by TheXeon81** [comment]
okay! now work! :-)

**Comment by sahilr2050** [comment]
set_automated_followed_pool error [Errno 2] No such file or directory: 'C:\\Users\\xxxx\\Downloads\\Compressed\\InstaPy-master\\logs\\xxxx_followedPool.csv'
INFO [2018-08-17 11:12:12] [xxxx]  Please select a proper unfollow method!  ~leaving unfollow activity

>> I have latest code
>> I have given access of this folder to 777 (Everyone in Win10)
>> There is no file with the name in logs folder.

Can you please give a solution? @timgrossmann

**Comment by bmind12** [comment]
@sahilr2050 try to pull the latest changes
