### ISSUE TITLE
recommand me proxy provider maybe the best in the market

### ISSUE THREAD

**Issue by HCWcoder** [InstaPy/InstaPy#3720]
Hello Everyone,

@timgrossmann  and all devs

please if someone can share with us a proxy provider  ?

thanks.

**Comment by sionking** [comment]
there is no. buy lte sticks and build one.

**Comment by sionking** [comment]
btw you can't use this script in the same pc for more than 1-2 users, it has many security leaks.

**Comment by sionking** [comment]
btw you can't use this script in the same pc for more than 1-2 users, it has many security leaks.

**Comment by dsmh** [comment]
> btw you can't use this script in the same pc for more than 1-2 users, it has many security leaks.

Is this true? I have 6 accounts per Rapi (3 raspi in total). May I know which security leaks are you talking about?

**Comment by dsmh** [comment]
> Hello Everyone,
> 
> @timgrossmann and all devs
> 
> please if someone can share with us a proxy provider ?
> 
> thanks.

I use this: https://www.proxynova.com/proxy-server-list/ but you need to change them quite often.

**Comment by sionking** [comment]
> > btw you can't use this script in the same pc for more than 1-2 users, it has many security leaks.
> 
> Is this true? I have 6 accounts per Rapi (3 raspi in total). May I know which security leaks are you talking about?

too many.

**Comment by dsmh** [comment]
> > > btw you can't use this script in the same pc for more than 1-2 users, it has many security leaks.
> > 
> > 
> > Is this true? I have 6 accounts per Rapi (3 raspi in total). May I know which security leaks are you talking about?
> 
> too many.

What do you mean? cloud you please be more specific?
