### ISSUE TITLE
[Help Needed] - Bypass Issue - Started a new droplet with Debian & Ubuntu 

### ISSUE THREAD

**Issue by HCWcoder** [InstaPy/InstaPy#3725]
Guys i got a new droplet with Debian
@timgrossmann 
followed all the right steps and the bot is running till it logins.
my login data is right but its says its wrong and i think its because of the verification ! even i did add this 
` bypass_suspicious_attempt=True `

please help

Instapy script 👍 
```
""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = 'xxx'
insta_password = 'xxx'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  nogui=True,
                  bypass_suspicious_attempt=True)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                    min_followers=45,
                                    min_following=77)

    # activity
    session.like_by_tags(["natgeo"], amount=10)

```
Logs

```
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-01-12 22:48:36] [xxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...

.............................................................
CRITICAL [2019-01-12 22:49:35] [xxx]  Wrong login data!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2019-01-12 22:49:38] [xxx]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 1073 users & had 4857 FOLLOWERS
[Session lasted 1.05 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-01-12 22:49:38] [xxx]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

```
if i use ` bypass_suspicious_attempt=True `
results

```
Cookie file not found, creating cookie...
Unable to locate email or phone button, maybe bypass_suspicious_login=True isn't needed anymore.

```

and im sure i have a email and password there in my profile

i tested the same quick start on my windows it worked easily

**Comment by rollsappletree** [comment]
same here :(

**Comment by HCWcoder** [comment]
@timgrossmann 
@uluQulu 
@sionking 
Can someone please guide us what are we doing wrong ?

or its a code issue ?

thanks.

**Comment by GoodBoyKimm** [comment]
I'm having the exact same issue here
It was working last week but when I tried creating a new droplet yesterday, I just received the same issue as @HCWcoder

**Comment by sillyonthestreet** [comment]
Samesies

**Comment by brocool** [comment]
maybe you got a phone number bypass message. if so, try to to bypass it by adding your phone number and try again

**Comment by HCWcoder** [comment]
> maybe you got a phone number bypass message. if so, try to to bypass it by adding your phone number and try again

@brocool 
Dear How can i add it ? yes im sure its a bypass message 
I have my email and phone number in Instagram account

what should i do ?

Edited:

I even removed my phone number and still getting the same issue
@timgrossmann any thoughts ?

**Comment by Tr1pke** [comment]
> > maybe you got a phone number bypass message. if so, try to to bypass it by adding your phone number and try again
> 
> @brocool
> Dear How can i add it ? yes im sure its a bypass message
> I have my email and phone number in Instagram account
> 
> what should i do ?
> 
> Edited:
> 
> I even removed my phone number and still getting the same issue
> @timgrossmann any thoughts ?

i had the same problem once, i started my instapy in de GUI mode and i clicked it myself, since then never had that problem anymore.

**Comment by timgrossmann** [comment]
Sorry for the problems guys...
Unfortunately I can't view every issue anymore. 
We are currently planning to add some centralised error reporting that would make issues like this be detected and removed way earlier.

If you can help test: https://github.com/timgrossmann/InstaPy/pull/3820
We can merge the PR and make it work as soon as it's approved 😉 

Thanks for the help
