### ISSUE TITLE
Add account info in the log

### ISSUE THREAD

**Issue by TheXeon81** [InstaPy/InstaPy#373]
i use the InstaPy whith 2 account.
is possible to use the account info (only name) in the log file?
or is possible to create more file of log for each account?

**Comment by timgrossmann** [comment]
@TheXeon81 Not for the first version...
It's a feature that will be in InstaPy_V1

Simply clone it again and have 2 separate folders.

You can help make InstaPy_V1 happen here: https://www.patreon.com/InstaPy
