### ISSUE TITLE
Unable to load desirable amount of followers and keep following the same user

### ISSUE THREAD

**Issue by Cokpan** [InstaPy/InstaPy#3730]
I've used Instapy for two months exclusively just for doing follow-unfollow botting. It works just fine. Today I tried to follow someone's followers and it cannot grab the desirable amount of their follower. This usually mean that my account got browser-banned thus it kinda blocks my browser activities, including scrolling stuff for listing the followers, for several hours while still able to do stuff on my phone. But I can see the images, stories, and it actually scrolls and doesn't look like I'm getting browser-banned. I tried using Chrome and it still works just fine. I also tried using another account, and also experience the same thing.

Anyone's experiencing this?

**Comment by jacksonterceiro** [comment]
I have the same problem too.

**Comment by henry0666** [comment]
same

**Comment by Tr1pke** [comment]
Same

**Comment by Ugar93** [comment]
+1

**Comment by denisdenes** [comment]
+1
I get some kind of timeout 
`selenium.common.exceptions.WebDriverException: Message: chrome not reachable`
when using `follow_user_followers` method.

Do you guys have the same problem?
