### ISSUE TITLE
_csv.Error: line contains NULL byte

### ISSUE THREAD

**Issue by escariao** [InstaPy/InstaPy#3732]
```
Traceback (most recent call last):
  File "quickstart.py", line 55, in <module>
    session.like_by_locations(['417103330/etc...etc/'], amount=130)
  File "/home/pi/Instapy/instapy/instapy.py", line 1275, in like_by_locations
    user_name)
  File "/home/pi/Instapy/instapy/instapy.py", line 1113, in validate_user_call
    self.logger)
  File "/home/pi/Instapy/instapy/util.py", line 161, in validate_username
    for row in reader:
_csv.Error: line contains NULL byte
```
It starts running and stops during the first set, either follow or by location... But, it works again when I delete (or rename) the login folder inside the /logs/ 
Ex.: /logs/newName
@uluQulu @converge Do you know something about this?

**Comment by uluQulu** [comment]
Hi @escariao 
All you can do is find and delete those lines.

@sionking explained it well, https://github.com/timgrossmann/InstaPy/pull/2154#issuecomment-394278962 here.

In future, atomic write or other kind of write stabilizer added will avoid such rare failure scenarios.

---

Cheers 😁
---

**Comment by escariao** [comment]
@uluQulu I tried, but it did not work. Also, I've done git pull
and commits...
"Atomic write and atomic pickling by flush to disk and os.replace #2154"

**Comment by uluQulu** [comment]
@escariao 
I have not advised to pull that PR or commits.
Generally, pulling old code directly causes conflicts and must be avoided.

You should see the picture in the post I have linked, and remove those null bytes manually.

**Comment by escariao** [comment]
Thanks! 
Do you talk about this?
https://user-images.githubusercontent.com/33269249/40990631-8347c1c8-6902-11e8-97bf-8762ac60eeb2.png

**Comment by uluQulu** [comment]
@escariao that's part of implementation discussions..
The link I shared above has only one picture in it- https://user-images.githubusercontent.com/7851877/40907393-5e21ac0e-67ec-11e8-8d5b-73c4ac3144bc.png.

**Comment by escariao** [comment]
Hmm OK. I saw this too, and thanks for that. But my problem seems to be unrelated to this.
I renamed the old file CVS. Instapy has created a new file. So it does not NULL character.

**Comment by sionking** [comment]
@uluQulu even atomic writer won't prevent NULL bytes.
Some buffers probably been written to disk to save place on disk before real write.
So no lost of data but having many NULL on power outage.

**Comment by anorouzi** [comment]
Simply can be fixed by opening csv files in log folder in gedit or notepad and delete the last lines in the csv files. 
It is because of unexpected exit of python run that couldn't save to the csv correctly and write some null character at the end of csv files.
