### ISSUE TITLE
Interact likers & interact followers with errors

### ISSUE THREAD

**Issue by JoeFertig** [InstaPy/InstaPy#3735]
## Expected Behavior
like & interact with likers & followers of an account
## Current Behavior

Getting likers from user:  xxx 

shuffling links
Got  24 , returning  3  links:  ['https://www.instagram.com/p/BpdEfe7gTQt/', 'https://www.instagram.com/p/BouXdDTgx39/', 'https://www.instagram.com/p/BqKoK3VgupX/']
opening likes
Some problem occred!
	b'Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()=\'Likes\']/following-sibling::div"}\n  (Session info: headless chrome=65.0.3325.181)\n  (Driver info: chromedriver=2.36 (d9e39391cfae447a84e276a402342cf8b4b5bcba),platform=Linux 4.14.79-v7+ armv7l)\n'

**Comment by henry0666** [comment]
same here /w follow users followers

**Comment by Xelanor** [comment]
I have the same issue. Can not find to follow

**Comment by GGaitanis** [comment]
Same for me!

**Comment by ejc** [comment]
+1

**Comment by Tr1pke** [comment]
Same

**Comment by itayoron** [comment]
+1

**Comment by flackoon** [comment]
+1

**Comment by marcosgb** [comment]
same here!! @timgrossmann

**Comment by mortezahei** [comment]
please help!!!

**Comment by Tr1pke** [comment]
Redownload your insta folder and replace it

**Comment by mortezahei** [comment]
Dont work

Please help me 🙏🙏😣😣😣

**Comment by Tr1pke** [comment]
And have you reinstalled everything again as of zero?
