### ISSUE TITLE
Follow likers is not working

### ISSUE THREAD

**Issue by mkhattar** [InstaPy/InstaPy#3737]
## Expected Behavior
Grabs likers of photos and follow them
## Current Behavior
It grabs likers from user as usual, but then the below error occurs:

opening likes
Some problem occred!
        Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Likes']/following-sibling::div"}
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.9.0-8-amd64 x86_64)

**Comment by GGaitanis** [comment]
Same for me!

**Comment by henry0666** [comment]
Same

**Comment by ejc** [comment]
Same here. Just started happening. Was working yesterday.

**Comment by Tr1pke** [comment]
Same

**Comment by atomhax** [comment]
_**Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()='Likes']/following-sibling::div"}**_

The error here is explicit. Either the page didn't load the element or the xpath (likely) to the element was changed by instagram (also very likely). They tend to do A/B groups for releases so some users might get an update while others wont right away.

**Comment by nicopetremann** [comment]
Same problem, looks like they have changed the element.

**Comment by AdamMoffitt** [comment]
same error here

**Comment by AdamMoffitt** [comment]
anyone have a fix?

**Comment by hw711** [comment]
I changed
   dialog = browser.find_element_by_xpath("//div[text()='Likes']/following-sibling::div")
to
  dialog = browser.find_element_by_xpath("/html/body/div[2]/div/div/div[2]/div")

it will find the dialog and scroll down is still not working so it will only get the top 12 likes

**Comment by JoeFertig** [comment]
> I changed
> dialog = browser.find_element_by_xpath("//div[text()='Likes']/following-sibling::div")
> to
> dialog = browser.find_element_by_xpath("/html/body/div[2]/div/div/div[2]/div")
> 
> it will find the dialog and scroll down is still not working so it will only get the top 12 likes

where did you put the changes? Which file?

**Comment by bobbyjer** [comment]
same

**Comment by doctorcassan** [comment]
same here

**Comment by itayoron** [comment]
@JoeFertig commenter_util.py  line 328

But now it is only trying to interact with the same liker 5 times in a raw and continue to the next link

@hw711 Do you have the same issue?

**Comment by Tr1pke** [comment]
> @JoeFertig commenter_util.py line 328
> 
> But now it is only trying to interact with the same liker 5 times in a raw and continue to the next link
> 
> @hw711 Do you have the same issue?

i have the same issue its always the same user

**Comment by tomijunior** [comment]
#3736

**Comment by hw711** [comment]
Never mind about my previous comment.  I didn't get the dialog xpath correctly that's why it wouldn't scroll down.

And to answer @JoeFertig's question.  The method that broke by IG's change is likers_from_photo() in commenters_util.py.

I'm not sure how IG coded the liker dialog box before but not only a bunch of xpaths changed, it seems like every time you scroll down, you get a different subset (instead of more and more buttons) of buttons so even when I changed the method to use the new xpath of buttons, the "counting growing # of buttons to know when to stop" loop would break prematurely.  I rewrote the whole find dialog box section of likers_from_photo and it seems to be working.

Basically instead of counting total number of buttons as I scrolls down, I add each subset of likers from each scroll down to a list of unique likers and stop scrolling when the number of unique likers stops increasing.

        # find dialog box
        dialog = browser.find_element_by_xpath("/html/body/div[2]/div/div/div[2]/div")
        
        person_list = set()
        previous_len=-1

        likers = browser.find_elements_by_xpath("/html/body/div[2]/div/div/div[2]/div/div//div/a")
        
        for person in likers:
            username_url = person.get_attribute('href')
            username = username_url_to_username(username_url)
            person_list.add(username)
        print("len(person_list)=",len(person_list))

        while (len(person_list) != previous_len) and (len(person_list)<amount):
            if previous_len+10 >= amount:
                print ("Scrolling finished")
                sleep(1)
                break

            previous_len=len(person_list)
            browser.execute_script("arguments[0].scrollTop = arguments[0].scrollHeight", dialog)
            sleep(1)

            likers = browser.find_elements_by_xpath("/html/body/div[2]/div/div/div[2]/div/div//div/a")
            for person in likers:
                username_url = person.get_attribute('href')
                username = username_url_to_username(username_url)
                person_list.add(username)

            print ("Scrolling down... ",previous_len,"->", len(person_list)," / ",amount)

        random.shuffle(list(person_list))
        sleep(1)

**Comment by doctorcassan** [comment]
@hw711 I tried putting your code in. Now I don't get "Some problem occred!" anymore. But it simply pulls out the same liker 17 times.

This is what it tells me:
Got 17 likers shuffled randomly whom you can follow:
['troty__', 'troty__', 'troty__', 'troty__', 'troty__', 'troty__', 'troty__', 'troty__', 'troty__', 'troty__', 'troty__', 'troty__', 'troty__', 'troty__', 'troty__', 'troty__', 'troty__']

**Comment by Tr1pke** [comment]
it doesn't scroll anymore, it just takes one username and follows that the amount of you gave, with me its 40 times

**Comment by hw711** [comment]
ignore my first change that @JoeFertig quoted and use the latest one I posted.  The person_list is a set so shouldn't have any repeats.

**Comment by octavius-1** [comment]
Basically since 'set' objects are not iterable, I just adapted @hw711 's fix and used lists instead (working now, tested it for different methods)

```
        # find dialog box
        dialog = browser.find_element_by_xpath("/html/body/div[2]/div/div/div[2]/div")

        person_list = []
        previous_len=-1

        likers = browser.find_elements_by_xpath("/html/body/div[2]/div/div/div[2]/div/div//div/a")

        for person in likers:
            username_url = person.get_attribute('href')
            username = username_url_to_username(username_url)
            person_list.append(username)
        print("len(person_list)=",len(person_list))

        while (len(person_list) != previous_len) and (len(person_list)<amount):
            if previous_len+10 >= amount:
                print ("Scrolling finished")
                sleep(1)
                break

            previous_len=len(person_list)
            browser.execute_script("arguments[0].scrollTop = arguments[0].scrollHeight", dialog)
            sleep(1)

            likers = browser.find_elements_by_xpath("/html/body/div[2]/div/div/div[2]/div/div//div/a")
            for person in likers:
                username_url = person.get_attribute('href')
                username = username_url_to_username(username_url)
                person_list.append(username)

            print ("Scrolling down... ",previous_len,"->", len(person_list)," / ",amount)

        random.shuffle(person_list)
        sleep(1)
```

**Comment by octavius-1** [comment]
We still need to check what's happening with that 'timeout' error.

**Comment by doctorcassan** [comment]
It doens't make any difference for me. It still just grabs one username multible times.

**Comment by Tr1pke** [comment]
Yesterday it worked , during the night or morning it stopped working

**Comment by hw711** [comment]
> Basically since 'set' objects are not iterable, I just adapted @hw711 's fix and used lists instead (working now, tested it for different methods)

you get repeats, that's why I used set while scrolling and turn the final set into list before shuffling

**Comment by Tr1pke** [comment]
> Basically since 'set' objects are not iterable, I just adapted @hw711 's fix and used lists instead (working now, tested it for different methods)
> 
> ```
>         # find dialog box
>         dialog = browser.find_element_by_xpath("/html/body/div[2]/div/div/div[2]/div")
> 
>         person_list = []
>         previous_len=-1
> 
>         likers = browser.find_elements_by_xpath("/html/body/div[2]/div/div/div[2]/div/div//div/a")
> 
>         for person in likers:
>             username_url = person.get_attribute('href')
>             username = username_url_to_username(username_url)
>             person_list.append(username)
>         print("len(person_list)=",len(person_list))
> 
>         while (len(person_list) != previous_len) and (len(person_list)<amount):
>             if previous_len+10 >= amount:
>                 print ("Scrolling finished")
>                 sleep(1)
>                 break
> 
>             previous_len=len(person_list)
>             browser.execute_script("arguments[0].scrollTop = arguments[0].scrollHeight", dialog)
>             sleep(1)
> 
>             likers = browser.find_elements_by_xpath("/html/body/div[2]/div/div/div[2]/div/div//div/a")
>             for person in likers:
>                 username_url = person.get_attribute('href')
>                 username = username_url_to_username(username_url)
>                 person_list.append(username)
> 
>             print ("Scrolling down... ",previous_len,"->", len(person_list)," / ",amount)
> 
>         random.shuffle(person_list)
>         sleep(1)
> ```

tried, but same issue, maybe in meanwhile they changed something again>?

**Comment by pmusolino** [comment]
Same problem here

**Comment by octavius-1** [comment]
Are you guys using Python3? The method I wrote above was working perfectly for me (before timeouts started screwing everything up)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Tr1pke** [comment]
Yes python3

**Comment by mkhattar** [comment]
Maybe @uluQulu can help us here, I believe it is only about finding the relative xpath

**Comment by uluQulu** [comment]
Hey all
I've shared the solution at https://github.com/timgrossmann/InstaPy/pull/3764.

---

Cheers 😁
---

**Comment by timgrossmann** [comment]
Please pull the latest master and try again.

Big thanks to @uluQulu (as always 😉 )
And thanks to @sionking for the initial testing!

**Comment by octavius-1** [comment]
@timgrossman Already testing... Let you know guys what happens

**Comment by octavius-1** [comment]
Didn’t work, opened a new issue

**Comment by octavius-1** [comment]
Actually, @hw711 solution works better than the actual one in master repo for getting likers (the one in master returns a list of lenght zero in my case). But we still need to check what's happening with those timeout errors when trying to get some user's followers list.

**Comment by hw711** [comment]
what timeout errors are you referring to?  I'm not getting any time out errors.

**Comment by gyrex** [comment]
I've pulled the most recent changes from the master which has fixed the initial issue but now I'm getting

"Got 0 likers shuffled randomly whom you can follow"

On every single user.

**Comment by octavius-1** [comment]
@hw711 Timeout errors when trying to get some user followers, I don’t know if that’s because of instagram or because of instapy 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tomijunior** [comment]
I use chromedriver and my setting
```
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True,
                  nogui=True,
                  proxy_chrome_extension=proxy_chrome_extension,
                  multi_logs=True)
```

this my diff in unfollow_util.py
```
diff --git a/instapy/unfollow_util.py b/instapy/unfollow_util.py
index 176c1e9..197d00c 100644
--- a/instapy/unfollow_util.py
+++ b/instapy/unfollow_util.py
@@ -704,7 +704,7 @@ def follow_user(browser, track, login, user_name, button, blacklist, logger,
 
 def scroll_to_bottom_of_followers_list(browser, element):
     browser.execute_script(
-        "arguments[0].children[1].scrollIntoView()", element)
+        "arguments[0].children[1].children[1].scrollIntoView()", element)
     sleep(1)
     return
 
@@ -737,7 +737,7 @@ def get_users_through_dialog(browser,
     sc_rolled = 0
 
     # find dialog box
-    dialog_address = "//div[3]/div/div/div[2]"
+    dialog_address = "//div[@role='dialog']"
     dialog = browser.find_element_by_xpath(dialog_address)
 
     # scroll to end of follower list to initiate first load which hides the
@@ -842,7 +842,7 @@ def dialog_username_extractor(buttons):
     for person in buttons:
         if person and hasattr(person, 'text') and person.text:
             try:
-                person_list.append(person.find_element_by_xpath("../../../*")
+                person_list.append(person.find_element_by_xpath("./../..")
                                    .find_elements_by_tag_name("a")[1].text)
             except IndexError:
                 pass  # Element list is too short to have a [1] element
```

and for util.py
```
diff --git a/instapy/util.py b/instapy/util.py
index 9291924..742310b 100644
--- a/instapy/util.py
+++ b/instapy/util.py
@@ -738,7 +738,7 @@ def scroll_bottom(browser, element, range_int):
 
     for i in range(int(range_int / 2)):
         browser.execute_script(
-            "arguments[0].scrollTop = arguments[0].scrollHeight", element)
+            "arguments[0].children[1].scrollTop = arguments[0].children[1].scrollHeight", element)
         # update server calls
         update_activity()
         sleep(1)
```
for like_util.py
```
diff --git a/instapy/like_util.py b/instapy/like_util.py
index 0066608..2463b2c 100644
--- a/instapy/like_util.py
+++ b/instapy/like_util.py
@@ -522,19 +522,20 @@ def check_link(browser, post_link, dont_like, mandatory_words,
         image_text = image_text[0]['node']['text'] if image_text else None
         location = media['location']
         location_name = location['name'] if location else None
-        owner_comments = browser.execute_script('''
-            latest_comments = window._sharedData.entry_data.PostPage[
-            0].graphql.shortcode_media.edge_media_to_comment.edges;
-            if (latest_comments === undefined) {
-                latest_comments = Array();
-                owner_comments = latest_comments
-                    .filter(item => item.node.owner.username == arguments[0])
-                    .map(item => item.node.text)
-                    .reduce((item, total) => item + '\\n' + total, '');
-                return owner_comments;}
-            else {
-                return null;}
-        ''', user_name)
+        owner_comments = None
+        # owner_comments = browser.execute_script('''ents[0])
+        #             .map(item => item.node.text)
+        #     latest_comments = window._sharedData.entry_data.PostPage[
+        #     0].graphql.shortcode_media.edge_media_to_comment.edges;
+        #     if (latest_comments === undefined) {
+        #         latest_comments = Array();
+        #         owner_comments = latest_comments
+        #             .filter(item => item.node.owner.username == argum
+        #             .reduce((item, total) => item + '\\n' + total, '');
+        #         return owner_comments;}
+        #     else {
+        #         return null;}
+        # ''', user_name)
 
     else:
         media = post_page[0]['media']
@@ -568,9 +569,9 @@ def check_link(browser, post_link, dont_like, mandatory_words,
     """If the image still has no description gets the first comment"""
     if image_text is None:
         if graphql:
-            image_text = media['edge_media_to_comment']['edges']
-            image_text = image_text[0]['node']['text'] if image_text else None
-
+            # image_text = media['edge_media_to_comment']['edges']
+            # image_text = image_text[0]['node']['text'] if image_text else None
+            image_text = None
         else:
             image_text = media['comments']['nodes']
             image_text = image_text[0]['text'] if image_text else None

```
just check for session.follow_user_followers and session.unfollow_users

**Comment by octavius-1** [comment]
@gyrex Were you able to get likers from photos?

**Comment by gyrex** [comment]
> @gyrex Were you able to get likers from photos?

No, I wasn't able to get it working.

**Comment by octavius-1** [comment]
@gyrex I'm still not able either and people around here think I'm crazy or stupid because I can't make it work.

**Comment by itayoron** [comment]
It is not working! This thread is closed with no solution, I opened another one with no responses at all. Keep getting the same liker several times...

**Comment by hw711** [comment]
I didn't try uluQulu's solution since mine works.  Though around 4:20PM PST, they changed the xpath of the dialog box.  I was trying to fix my code but now it seems like it's back to how it was earlier today again.

I also notice some profiles have a different layout (looks more like the ig app on the phone). 
![screen shot 2019-01-24 at 8 32 26 pm](https://user-images.githubusercontent.com/39748721/51725582-ee8c0080-2017-11e9-821d-ae04b6e38202.jpg)

Seems like instagram are doing partial roll outs of new code and sometimes rolling back.  Maybe that's why people are having so much issue because no version of the code on our end is going to work for all cases.

**Comment by fixmenu** [comment]
Hello , 

Yes follow likers was not working on me too. I debug the code and fix the problem.

In my case:
in commenters_util.py
There was a extra tab under while loop under the method likers_from_photo.

delete one tab before the below lines
        user_list = get_users_from_dialog(user_list, dialog)
        # write & update records at Progress Tracker
        progress_tracker(len(user_list), amount, start_time, None)

or copy paste the code below for the method

```
def likers_from_photo(browser, amount=20):

    liked_counter_button = "//div/article/div[2]/section[2]/div/div/a"

    try:
        liked_this = browser.find_elements_by_xpath(liked_counter_button)
        likers = []

        for liker in liked_this:
            if " like this" not in liker.text:
                likers.append(liker.text)

        if check_exists_by_xpath(browser, liked_counter_button):
            if " others" in liked_this[-1].text:
                element_to_click = liked_this[-1]

            elif " likes" in liked_this[0].text:
                element_to_click = liked_this[0]

            else:
                print("Few likes, not guaranteed you don't follow these"
                      " likers already.\nGot photo likers: {}\n"
                      .format(likers))
                return likers

        else:
            print("Couldn't find liked counter button. May be a video.")
            print("Moving on..")
            return []

        sleep(1)
        click_element(browser, element_to_click)
        print("opening likes")
        # update server calls
        # update_activity()

        sleep(1)

        # get a reference to the 'Likes' dialog box
        dialog = browser.find_element_by_xpath(
            Selectors.likes_dialog_body_xpath)

        # scroll down the page
        previous_len = -1
        browser.execute_script(
            "arguments[0].scrollTop = arguments[0].scrollHeight", dialog)
        update_activity()
        sleep(1)

        start_time = time.time()
        user_list = []

        while (not user_list
               or (len(user_list) != previous_len)
               and (len(user_list) < amount)):

            if previous_len + 10 >= amount:
                print("\nScrolling finished")
                sleep(1)
                break

            previous_len = len(user_list)
            scroll_bottom(browser, dialog, 2)

        user_list = get_users_from_dialog(user_list, dialog)

        # write & update records at Progress Tracker
        progress_tracker(len(user_list), amount, start_time, None)

        print('\n')
        random.shuffle(user_list)
        sleep(1)

        close_dialog_box(browser)

        print(
            "Got {} likers shuffled randomly whom you can follow:\n{}"
            "\n".format(
                len(user_list), user_list))
        return user_list

    except Exception as exc:
        print("Some problem occured!\n\t{}".format(str(exc).encode("utf-8")))
        return []
````

**Comment by Masisoft** [comment]
Same issue after git update: I get it to work commenting:

`# scroll_to_bottom_of_followers_list(browser, dialog) at Line 745 of unfollow_util.py`

i think it cause exception with nogui settings, it should be controlled.

my configuration is

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

**Comment by hw711** [comment]
Not only you can use no GUI, u need the window open (can’t be minimized) for it scrolling to work or you would only get 11 likers max

**Comment by Masisoft** [comment]
> 
> Not only you can use no GUI, u need the window open (can’t be minimized) for it scrolling to work or you would only get 11 likers max
> […](#)
> Sent from my iPhone
> On Feb 5, 2019, at 11:10, Masisoft ***@***.***> wrote: I just commented scroll_to_bottom_of_followers_list(browser, dialog) at Line 745 of unfollow_util.py i think it cause exception with nogui settings, it should be controlled. my configuration is session = InstaPy(username=insta_username, password=insta_password, headless_browser=True) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

It's just a temporary fix to get it work, that's the point. Thanks for the advice I'll check it later

**Comment by hw711** [comment]
*Can not use no GUI

**Comment by spikeyhair** [comment]
I tried with the "indentation" solution proposed by @fixmenu and it works. Thank you for that. 
Hopefully this minor bug fix can be merged into the master copy.

**Comment by Tr1pke** [comment]
Have you done a pip install instapy-U ?

**Comment by GeoffreyPG** [comment]
I try to change : Edit unfollow_util.py (line 809)
https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py#L809

Old
dialog_address = "//body/div[3]/div/div[2]"

New
dialog_address = "//body/div[@ROLE="presentation"]/div/div[2]"

But same error
