### ISSUE TITLE
Handshake failed error, please help!

### ISSUE THREAD

**Issue by burnoutuniversity** [InstaPy/InstaPy#3738]

**Comment by TRys8** [comment]
I also have this error.  Oddly enough, if I log into my account in a normal Chrome browser, I have no issue.  But when I manually take over the automated chrome browser that the program opens, I can no longer log in.  It's as if Instagram can detect that I'm trying to log in from a browser that can be controlled by an automated program.

Cookie file not found, creating cookie...
[23568:24760:0115/224235.333:ERROR:ssl_client_socket_impl.cc(1013)] handshake fa
iled; returned -1, SSL error code 1, net_error -100
[23568:24760:0115/224235.334:ERROR:ssl_client_socket_impl.cc(1013)] handshake fa
iled; returned -1, SSL error code 1, net_error -100
[23568:24760:0115/224235.348:ERROR:ssl_client_socket_impl.cc(1013)] handshake fa
iled; returned -1, SSL error code 1, net_error -100

**Comment by rafaelmpessoa** [comment]
Same error.
