### ISSUE TITLE
failed to get comments' count!

### ISSUE THREAD

**Issue by sunnygill** [InstaPy/InstaPy#3741]
Hi All, 

I just synced to the tip and I am getting below error while commenting on a post. Is there any solution for it. 

 8 INFO [2019-01-15 15:13:25] [X]  https://www.instagram.com/p/BsrFfcdBxJx/
 9 INFO [2019-01-15 15:13:28] [X]  Image from: b'sabatico_critico'
10 INFO [2019-01-15 15:13:28] [X]  Link: b'https://www.instagram.com/p/BsrFfcdBxJx/'
11 INFO [2019-01-15 15:13:28] [X]  Description: b'#sabatico_critico #SabaticoCritico #artiste #artwork #art_spotlight #blue #yellow #pic #pictures #editorial #digitals #digitalart #digitalsketch #people #female #woman #girl #erotic #skin'
12 INFO [2019-01-15 15:13:31] [X]  User: 'sabatico_critico'  |> followers: 36  |> following: 74  |> relationship ratio: 0.48
13 INFO [2019-01-15 15:13:37] [X]  --> Image Liked!
14 INFO [2019-01-15 15:13:39] [X]  --> Not commenting! Failed to get comments' count!
15     b"Message: unknown error: Cannot read property 'count' of undefined\n  (Session info: headless chrome=71.0.3578.98)\n  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 6.1.7601 SP1 x86_64)\n"

**Comment by sourstripe** [comment]
I am having the same issue as of late. I get this error

Not commenting! Failed to get comments' count!
	b"Message: unknown error: Cannot read property 'count' of undefined\n  (Session info: headless chrome=71.0.3578.98)\n  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.17763 x86_64)\n"

**Comment by ribtoks** [comment]
Same here: latest master and errors `Not commenting! Failed to get comments' count!
b"Message: unknown error: Cannot read property 'count' of undefined`

**Comment by kev-mas** [comment]
Got the same issue over here. Same error message. Scripts works fine, likes, follows, etc. Just doesn't comment because of this.

**Comment by MacroAnarchy** [comment]
Same :/ 
Probably a change in the website?

There then should be a fix by changing what it looks for to load and contain that comment count

**Comment by sunnygill** [comment]
@uluQulu any idea about this issue?

**Comment by MacroAnarchy** [comment]
How comes nobody cares about this?
There should be a quick fix if it’s actually just a different website layout, like one link changed.
Is no one using comments? 😅

**Comment by MacroAnarchy** [comment]
Workaround:
Disable min/max comments on picture eg.

session.set_delimit_commenting(enabled=True, max=32, min=0)

Disable it

**Comment by kev-mas** [comment]
I've just come back after a few days away, and re-started the bot without changing anything and commenting works now... The failed to get count error does also not appear anymore.
