### ISSUE TITLE
Keeps interacting with one user

### ISSUE THREAD

**Issue by nobodysguilthub** [InstaPy/InstaPy#3743]
Hey I have another problem. The bot keeps interacting with only one person.
Any suggestions?

**Comment by Cokpan** [comment]
Have same problem. #3730

**Comment by Tr1pke** [comment]
same problem, also it won't grab users from the follow list etc

**Comment by booksix** [comment]
Yup... same problem using "follow_user_followers"

**Comment by denisdenes** [comment]
+1
I get some kind of timeout 
`selenium.common.exceptions.WebDriverException: Message: chrome not reachable`
when using `follow_user_followers` method.

Do you guys have the same problem?

**Comment by oldtajik** [comment]
same problem here.. any solution?

**Comment by Tr1pke** [comment]
Yes. Update your bot.
