### ISSUE TITLE
Setting up InstaPy on Pythonanywhere

### ISSUE THREAD

**Issue by rishkebab** [InstaPy/InstaPy#3744]
I am currently attempting to set up InstaPy scripts on pythonanywhere. I installed InstaPy using the bash console and the files are all properly installed. However, when I attempt to run any scripts, the following error shows up: 

 from instapy import InstaPy
ModuleNotFoundError: No module named 'instapy'

Did I do something wrong when installing? How can I resolve this issue?

Thanks!

**Comment by rishkebab** [comment]
all good, I realised i needed to run "pip3 install --user ." instead of "pip install --user ."

**Comment by mgconejero** [comment]
hey im having the same issue, but im new to code and i get this: 

SyntaxError: invalid syntax
>>> pip3 install clarifai
  File "<stdin>", line 1
    pip3 install clarifai

Can you help me with this?

**Comment by rishkebab** [comment]
@mgconejero make sure that before you install, you run the command "cd ~" , and then use pip3 to install whatever you need, because you might not have the appropriate permissions to install unless you are in the home directory.

**Comment by taneeshk12** [comment]
Plz can you show this step by step?
