### ISSUE TITLE
Unable to locate xpath element when running session.follow_likers

### ISSUE THREAD

**Issue by itayoron** [InstaPy/InstaPy#3749]
Hello all!

I have just came into a problem when running session.follow_likers
I recieved the following error message:
Some problem occred!
	b'Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()=\'Likes\']/following-sibling::div"}\n  (Session info: chrome=71.0.3578.98)\n  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.17134 x86_64)\n'

Seems like it can't find the dialog box in commenters_util.py line 329

Anyone else had this issue today?
Any solution?

Thanks!!!

**Comment by JoeFertig** [comment]
Mate... there are like 5 open issues for this. Please read before opening a new one.

**Comment by itayoron** [comment]
I am sorry but I couldn`t find anything regarding this issue. Can you please reference me to these open issues?

**Comment by octavius-1** [comment]
@JoeFertig Which is the main opened issue for this? Can't find it
