### ISSUE TITLE
" Failed to load desired amount of users " for following !

### ISSUE THREAD

**Issue by EvraCloak** [InstaPy/InstaPy#3751]
## Expected Behavior
I want follow someone's followers and It was working yestarday but not working today !
## Current Behavior
Terminal says ,"Grabbed 30 usernames" and " Failed to load desired amount of users!" and bot trying follow same user 30 times.
## InstaPy configuration
"""
This template is written by @zackvega

What does this quickstart script aim to do?
- This is my simple but effective script.
"""

from instapy import InstaPy
from instapy.util import smart_run

insta_username = 'kblxxlak'
insta_password = 'apxxxx1'

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True,
                  page_delay=7)

# let's go! :>
with smart_run(session):
    # general settings
    session.set_relationship_bounds(enabled=True,
                                     potency_ratio=None,
                                     delimit_by_numbers=True,
                                      max_followers=100000,
                                      max_following=5000,
                                      min_followers=150,
                                      min_following=100)
    session.set_skip_users(skip_private=False)

    # activity
    session.follow_user_followers(['mustafaeneskaratas9'], amount=1893, randomize=True, interact=False, sleep_delay=3600)

#Log
INFO [2019-01-16 11:48:10] [kblycolak]  Session started!
INFO [2019-01-16 11:48:27] [kblycolak]  Logged in successfully!
INFO [2019-01-16 11:48:27] [kblycolak]  Saving account progress...
INFO [2019-01-16 11:48:31] [kblycolak]  Starting to follow user `Followers`..
INFO [2019-01-16 11:48:31] [kblycolak]  User 'mustafaeneskaratas9' [1/1]
INFO [2019-01-16 11:48:44] [kblycolak]  Failed to load desired amount of users!

INFO [2019-01-16 11:48:44] [kblycolak]  Simulated follow : 1
INFO [2019-01-16 11:48:44] [kblycolak]  ---> asenabjq has already been followed 1 times
INFO [2019-01-16 11:48:44] [kblycolak]  Not followed 'asenabjq'  ~inappropriate user
INFO [2019-01-16 11:48:53] [kblycolak]  Grabbed 30 usernames from 'mustafaeneskaratas9's `Followers` to do following

INFO [2019-01-16 11:48:53] [kblycolak]  Ongoing Follow [1/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [2/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [3/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [4/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [5/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [6/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [7/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [8/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [9/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [10/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [11/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [12/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [13/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [14/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [15/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [16/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [17/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [18/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [19/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [20/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [21/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [22/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [23/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [24/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [25/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [26/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [27/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [28/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [29/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Ongoing Follow [30/30]: now following 'asenabjq'...
INFO [2019-01-16 11:48:56] [kblycolak]  User: 'asenabjq'  |> followers: 15  |> following: 92  |> relationship ratio: 0.16
INFO [2019-01-16 11:48:56] [kblycolak]  User 'asenabjq's followers count is less than minimum limit  ~skipping user

INFO [2019-01-16 11:48:56] [kblycolak]  Finished following 1 users' `Followers`! xD

INFO [2019-01-16 11:48:56] [kblycolak]  Followed: 0
INFO [2019-01-16 11:48:56] [kblycolak]  Already followed: 0
INFO [2019-01-16 11:48:56] [kblycolak]  Not valid users: 30
INFO [2019-01-16 11:48:59] [kblycolak]  Sessional Live Report:
	|> LIKED 0 images  |  ALREADY LIKED: 0
	|> COMMENTED on 0 images
	|> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> LIKED 0 comments
	|> REPLIED to 0 comments
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 30

On session start was FOLLOWING 3080 users & had 2665 FOLLOWERS
[Session lasted 51.21 seconds]
INFO [2019-01-16 11:48:59] [kblycolak]  Session ended!

**Comment by SonGogann** [comment]
Same problem.

**Comment by cyberiainformatica** [comment]
Same

**Comment by andreademasi** [comment]
Same with `interact_user_followers`.
I think something changed again in the Instagram DOM.

**Comment by mgconejero** [comment]
Same

**Comment by doctorcassan** [comment]
same problem here

**Comment by Tr1pke** [comment]
+1

**Comment by Cokpan** [comment]
Same problem here.

**Comment by gabrielrey37** [comment]
+1

**Comment by Ugar93** [comment]
+1. Any solution? Thanks in advance

**Comment by tourhuntr** [comment]
Same Problem

**Comment by gregnh** [comment]
+1

**Comment by CheckInfo99** [comment]
+1

**Comment by Yosoycoder** [comment]
I got the same problem, for following and also unfollowing

**Comment by mgconejero** [comment]
Fixed with the new merge! update the code

**Comment by Yosoycoder** [comment]
> Fixed with the new merge! update the code

Which files did you update or change??

**Comment by mgconejero** [comment]
> > Fixed with the new merge! update the code
> 
> Which files did you update or change??

@uluQulu fixed it and merged it. You just need to clone the repo or download it again and overwrite it

**Comment by Ugar93** [comment]
Can you tell me detailes about that, can you inform me about the steps?

**Comment by Tachenz** [comment]
@mgconejero Does it work for you? Not for me. The script does not even open followers window now, and "timeouts"

**Comment by Yosoycoder** [comment]
The fix stopped working...

**Comment by Tr1pke** [comment]
Worked yesterday evening. Stopped working today

**Comment by iamdatman** [comment]
Anybody with a lasting solution yet? This issue is driving me crazy

**Comment by tourhuntr** [comment]
Worked yesterday but stopped working at night

**Comment by Tr1pke** [comment]
> Anybody with a lasting solution yet? This issue is driving me crazy

It’s free and open source. Feel free to find a solution and share it with us.

**Comment by mgconejero** [comment]
yeah same here, it stopped again

**Comment by joanroig** [comment]
Same error while unfollowing with this code:
`session.unfollow_users(amount=50, allFollowing=True, sleep_delay=450)`
Then, only 10 are detected: 
`Total 10 users available to unfollow`
If I try launch it on Chrome I can see it scrolls down in the follow list but then it doesn't load up more people, seems like it gets stuck at the bottom of the list and then the loader does not add more users in the list. Any idea @uluQulu ?

**Comment by brunano21** [comment]
I have the same issue.

**Comment by Tr1pke** [comment]
@brunano21 

What version do you have?

**Comment by brunano21** [comment]
@Tr1pke last commit is 90ca1c0299be71bd0d2f8349723dfc640458b708.

**Comment by andreademasi** [comment]
Same problem, everything is updated
