### ISSUE TITLE
Strange issue after days of working properly

### ISSUE THREAD

**Issue by vomblyat** [InstaPy/InstaPy#376]
I was able to use InstaPy perfectly for a few days (thanks Tim!) but then it suddenly stopped working at all a couple of days ago. Some Googling around hasn't shed any light on this problem - every time I run it I get the following error messages: 
![error](https://user-images.githubusercontent.com/29987799/27974573-943c0ad4-632c-11e7-9165-366b3845585e.png)

**Comment by TheXeon81** [comment]
i have this problem.... 
the post is here: https://github.com/timgrossmann/InstaPy/issues/374
