### ISSUE TITLE
SIGTERM leaves chrome zombies running

### ISSUE THREAD

**Issue by sydney-d** [InstaPy/InstaPy#3766]
## Expected Behavior
When instapy receives a `SIGTERM` signal it should stop, and close all chrome processes

## Current Behavior
When instapy receives a `SIGTERM` signal it stops
But chrome processes are kept running, causing a memory leak.

## InstaPy configuration
I use PHP to run instapy every hour, and setup a process timeout of 1 hour.
In my `quickstart` I have : 

```py
def handle_signal(signum, frame):
    session.end()

signal.signal(signal.SIGTERM, handle_signal)
```
On timeout, my function `handle_signal` is called.
Which calls `session.end` and `close_browser`

But `close_browser` seems to malfunction, it leaves chrome processes running (no errors are displayed).
If I comment the lines related to the cookie deletion https://github.com/timgrossmann/InstaPy/blob/d361f2800aa32f9fde3a2c3f01c490410efd0f0e/instapy/browser.py#L185-L192
Chrome processes are killed, leaving only chromedriver processes 
`/var/my-folder/chromedriver/chromedriver --port=46158`

-----

I can achieve the same like this : 
```py
def handle_kill(signum, frame):
    session.browser.quit()

signal.signal(signal.SIGTERM, handle_signal)
```

----

Am I doing something wrong ? 
Is it normal for the `chromedriver` processes to keep running ? 
Whats the good way to programmatically end a session ?

Thanks :)

**Comment by octavius-1** [comment]
I want to follow this, my servers are getting frozen after a while of running just three simultaneous bot jobs and I haven't been able to track why.

**Comment by sionking** [comment]
I always restart the entire process to prevent memory leak

**Comment by octavius-1** [comment]
@sionking When exactly do you restart the entire process?

**Comment by sydney-d** [comment]
Hello,

Does anyone know whats the good way to programmatically end a session ?

thans
