### ISSUE TITLE
instapy is not working anymore

### ISSUE THREAD

**Issue by roncam82** [InstaPy/InstaPy#3767]
instapy is not getting followers anymore

**Comment by Tr1pke** [comment]
Ok

**Comment by roncam82** [comment]
if you go on Instagram and click follower the browser freezes

**Comment by roncam82** [comment]
when Instagram is switched to mobile mode it works normally

**Comment by Tr1pke** [comment]
> when Instagram is switched to mobile mode it works normally

Does that works for you? And where did you changed it?

**Comment by roncam82** [comment]
No I checked on the browser in mobile mode and the followers come up

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Tr1pke** [comment]
The followers also come up in the normal browser with me. But it doesn’t scroll normal and the screen disappears and come back. The problem is Instagram itself I suppose

**Comment by jasonbleasdell** [comment]
Everything seems to be working now!

**Comment by roncam82** [comment]
Yes it issss 😀

**Comment by mz462** [comment]
Not for me

**Comment by Tr1pke** [comment]
Works for me thx !
