### ISSUE TITLE
Latest fix for getting liker list is not working

### ISSUE THREAD

**Issue by octavius-1** [InstaPy/InstaPy#3768]
_________________________________________________________________________
INFO [2019-01-17 16:19:35] [myuser]  Starting to follow likers..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

Getting likers from user:  user1

shuffling links
Got  24 , returning  1  links:  ['https://www.instagram.com/p/link/']
opening likes

Scrolling finished

Got 0 likers shuffled randomly whom you can follow:
[]

Getting likers from user:  user2

shuffling links
Got  24 , returning  1  links:  ['https://www.instagram.com/p/link2/']
opening likes

Scrolling finished

Got 0 likers shuffled randomly whom you can follow:
[]

Getting likers from user:  user3

shuffling links
Got  24 , returning  1  links:  ['https://www.instagram.com/p/link3/']
opening likes

Scrolling finished

**Comment by octavius-1** [comment]
@uluQulu @sionking Any comments with this?

**Comment by Tr1pke** [comment]
follow is not working either:

.....................................................................
INFO [2019-01-17 23:21:29] [steven.ag]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-01-17 23:21:29] [steven.ag]  Saving account progress...

____________________________________________________________________________________
INFO [2019-01-17 23:21:33] [steven.ag]  Starting to follow user `Followers`..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-01-17 23:21:33] [steven.ag]  User 'instaacc' [1/2]

hanging and then quit with:

Traceback (most recent call last):
  File "tests.steven.ag.py", line 22, in <module>
    session.follow_user_followers(['insta','insta'], amount=5, randomize=True, interact=False)
  File "/home/steven/InstaPy/instapy/instapy.py", line 3048, in follow_user_followers
    self.logfolder)
  File "/home/steven/InstaPy/instapy/unfollow_util.py", line 998, in get_given_user_followers
    logger, logfolder)
  File "/home/steven/InstaPy/instapy/unfollow_util.py", line 741, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.18.0-13-generic x86_64)

**Comment by octavius-1** [comment]
Just confirmed with "interact_user_followers"

INFO [2019-01-17 16:26:55] [myuser]  User 'user1' [1/3]

	Message: timeout
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.15.0-1031-aws x86_64)

**Comment by elypsis** [comment]
same problem

**Comment by gyrex** [comment]
Yep, I'm getting the same issue after pulling the changes from the master.

**Comment by JoeFertig** [comment]
U must do something wrong. It works on two systems like charm.
Did your last pull went well?

**Comment by octavius-1** [comment]
@JoeFertig Sure my last pull went well, I always pull twice until "no changes to be added" message is shown. could you please share your likers_from_photo code here? Just to ensure behaviour.

**Comment by Tr1pke** [comment]
Only adjust the files that has been changed.

**Comment by octavius-1** [comment]
@Tr1pke What do you mean? I pulled and then modified the likers_from_photo method to a version I saw in one issue posted here, that works fine for now but I'd like to just git pull in all my systems instead of doing that quick fix.

**Comment by octavius-1** [comment]
And just confirmed with another machine. Git pulled from 0 and this is being shown when follow_likers is running:

```
INFO [2019-01-18 17:07:28] [some_user]  Starting to follow likers..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

Getting likers from user:  user1

shuffling links
Got  24 , returning  1  links:  ['https://www.instagram.com/p/link/']
opening likes

Scrolling finished


Got 0 likers shuffled randomly whom you can follow:
[]
```

**Comment by Tr1pke** [comment]
> @Tr1pke What do you mean? I pulled and then modified the likers_from_photo method to a version I saw in one issue posted here, that works fine for now but I'd like to just git pull in all my systems instead of doing that quick fix.

mkdir temp; cd temp; git clone https://github.com/timgrossmann/InstaPy.git; cd /home/username/temp/Instapy/instapy; cp -rfv * /home/username/Instapy/instapy <enter>

so you have all the new files of the instapy folder in your bot/instapy folder

**Comment by gyrex** [comment]
It's definitely not working for me... Here's my output:

```
__________________________________________________________________
INFO [2019-01-19 15:08:50] [user_id]  Starting to follow likers..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
('\nGetting likers from user: ', '<username>', '\n')
('Got ', 24, ', returning ', 4, ' links: ', [u'https://www.instagram.com/p/xxxxxxxx/', u'https://www.instagram.com/p/xxxxxxxxxx/', u'https://www.instagram.com/p/xxxxxxxxxx/', u'https://www.instagram.com/p/xxxxxxxxxxx/'])
opening likes

Scrolling finished


Got 0 likers shuffled randomly whom you can follow:
[]

opening likes

Scrolling finished


Got 0 likers shuffled randomly whom you can follow:
[]

opening likes

Scrolling finished


Got 0 likers shuffled randomly whom you can follow:
[]

opening likes

Scrolling finished


Got 0 likers shuffled randomly whom you can follow:
[]
```

**Comment by Elmolesto** [comment]
I've fixed that commenting lines 353 to 356 in commenters_util.py:

```
if previous_len + 10 >= amount:
    print("\nScrolling finished")
    sleep(1)
    break
```
Now i'm testing and debugging the issue to solve the problem.

**Comment by spikeyhair** [comment]
Please let us know once you have the solution. Thanks.

**Comment by JoeFertig** [comment]
Suddenly this problem occured on one of my machines.
Is there any fix? 
@uluQulu I think this might be an A/B-Testing thing cause only one of 6 machines is affected atm.

**Comment by tE3m** [comment]
@JoeFertig I think as soon as #3931 gets merged, it'll be stable

**Comment by an0key** [comment]
Reopening?
