### ISSUE TITLE
Not all the profiles I follow are recorded in .csv file

### ISSUE THREAD

**Issue by azmankristjan** [InstaPy/InstaPy#3769]
Hi
Is it possible to create a list of users I currently follow? I want the program to unfollow everyone that Instapy follows expect the people on the list. I know that Instapy collects the names of profiles followed in the username_followedPool.csv file in the logs folder, but after some time there are a lot of unrecorded profiles that it has followed. In my case around 300. Is it possible that profiles followed when the program does the simulated follow after grabbing someone’s followers list aren’t recorded in the .csv  file? Thank you

**Comment by sionking** [comment]
Some unfollow might be blocked and than removed from pool but still follow.
only solution is to sync the lists eveny few days, comparing the ever follow to the current follow.

**Comment by azmankristjan** [comment]
> Some unfollow might be blocked and than removed from pool but still follow.
> only solution is to sync the lists eveny few days, comparing the ever follow to the current follow.

@sionking  is the best way just to copy usernames from ever follow to the current follow?
