### ISSUE TITLE
InstaPy is not working 

### ISSUE THREAD

**Issue by PythonFrank** [InstaPy/InstaPy#3771]
Hi everyone, 
this issue appeared two days ago following user followers.

ERROR [2019-01-18 11:22:03] [skaf]  Pow! Error occurred while dumping follow restriction data to a local JSON:
        b'Expecting value: line 1 column 1 (char 0)'
ERROR [2019-01-18 11:22:03] [skaf]  Pow! Error occurred while dumping record activity data to a local JSON:
        b'Expecting value: line 1 column 1 (char 0)'
INFO [2019-01-18 11:22:03] [skaf]  Sessional Live Report:
        |> LIKED 0 images  |  ALREADY LIKED: 0
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0
currently FOLLOWING 4639 users & has got 4421 FOLLOWERS

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-01-18 11:22:03] [skaf]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "quickstart.py", line 40, in <module>
    session.follow_user_followers(['simone_favi', 'pietrocortese', 'shinre'], amount=amount_number, randomize=False, interact=True, sleep_delay=300)
  File "C:\Users\Francesco\Downloads\InstaPy\instapy\instapy.py", line 2836, in follow_user_followers
    self.logfolder)
  File "C:\Users\Francesco\Downloads\InstaPy\instapy\unfollow_util.py", line 885, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "C:\Users\Francesco\Downloads\InstaPy\instapy\unfollow_util.py", line 657, in get_users_through_dialog
    buttons = get_buttons_from_dialog(dialog, channel)
  File "C:\Users\Francesco\Downloads\InstaPy\instapy\unfollow_util.py", line 1208, in get_buttons_from_dialog
    "//button[text()='Follow']")
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-3.141.0-py3.6.egg\selenium\webdriver\remote\webelement.py", line 381, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-3.141.0-py3.6.egg\selenium\webdriver\remote\webelement.py", line 685, in find_elements
    {"using": by, "value": value})['value']
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-3.141.0-py3.6.egg\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-3.141.0-py3.6.egg\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-3.141.0-py3.6.egg\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.14393 `x86_64)

What's happened? Any solution?

**Comment by Tr1pke** [comment]
> Hi everyone,
> this issue appeared two days ago following user followers.
> 
> ERROR [2019-01-18 11:22:03] [skaf] Pow! Error occurred while dumping follow restriction data to a local JSON:
> b'Expecting value: line 1 column 1 (char 0)'
> ERROR [2019-01-18 11:22:03] [skaf] Pow! Error occurred while dumping record activity data to a local JSON:
> b'Expecting value: line 1 column 1 (char 0)'
> INFO [2019-01-18 11:22:03] [skaf] Sessional Live Report:
> |> LIKED 0 images | ALREADY LIKED: 0
> |> COMMENTED on 0 images
> |> FOLLOWED 0 users | ALREADY FOLLOWED: 0
> |> UNFOLLOWED 0 users
> |> INAPPROPRIATE images: 0
> |> NOT VALID users: 0
> currently FOLLOWING 4639 users & has got 4421 FOLLOWERS
> 
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2019-01-18 11:22:03] [skaf] Session ended!
> oooooooooooooooooooooooooooooooooooooooooooooooooooo
> 
> Traceback (most recent call last):
> File "quickstart.py", line 40, in 
> session.follow_user_followers(['simone_favi', 'pietrocortese', 'shinre'], amount=amount_number, randomize=False, interact=True, sleep_delay=300)
> File "C:\Users\Francesco\Downloads\InstaPy\instapy\instapy.py", line 2836, in follow_user_followers
> self.logfolder)
> File "C:\Users\Francesco\Downloads\InstaPy\instapy\unfollow_util.py", line 885, in get_given_user_followers
> channel, jumps, logger, logfolder)
> File "C:\Users\Francesco\Downloads\InstaPy\instapy\unfollow_util.py", line 657, in get_users_through_dialog
> buttons = get_buttons_from_dialog(dialog, channel)
> File "C:\Users\Francesco\Downloads\InstaPy\instapy\unfollow_util.py", line 1208, in get_buttons_from_dialog
> "//button[text()='Follow']")
> File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-3.141.0-py3.6.egg\selenium\webdriver\remote\webelement.py", line 381, in find_elements_by_xpath
> return self.find_elements(by=By.XPATH, value=xpath)
> File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-3.141.0-py3.6.egg\selenium\webdriver\remote\webelement.py", line 685, in find_elements
> {"using": by, "value": value})['value']
> File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-3.141.0-py3.6.egg\selenium\webdriver\remote\webelement.py", line 633, in _execute
> return self._parent.execute(command, params)
> File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-3.141.0-py3.6.egg\selenium\webdriver\remote\webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium-3.141.0-py3.6.egg\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
> (Session info: chrome=71.0.3578.98)
> (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.14393 `x86_64)
> 
> What's happened? Any solution?

format c: , install ubuntu ;-)
redownload the newest files and your good to go

**Comment by Tr1pke** [comment]
Try a fresh git clone and start all over again. helped for me once

**Comment by PythonFrank** [comment]
Seems that it back to normal. Thanks guys!
