### ISSUE TITLE
cannot get the likers list.element not found

### ISSUE THREAD

**Issue by moeinmohebbii** [InstaPy/InstaPy#3772]
this is the error i get after opening likes:
Some problem occred!
        b'Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[text()=\'Likes\']/following-sibling::div"}\n  (Session info: chrome=71.0.3578.98)\n  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17134 x86_64)\n
anyone has any idea how it could be fixed?

**Comment by JoeFertig** [comment]
Git pull origin master
