### ISSUE TITLE
Proxy with auth does not seem to work with Chrome

### ISSUE THREAD

**Issue by amauryleproux** [InstaPy/InstaPy#3773]
I'd like to use a proxy (NordVPN) with Auth on my AWS server but I get an error from IG displaying an alert message asking if it was me trying to connect from Dublin.

My Instapy is up to date and here's my piece of code:

    from proxy_extension import create_proxy_extension    

    proxy = '*****:*****@'+proxy_value+':80'
    proxy_chrome_extension = create_proxy_extension(proxy)
    session = InstaPy(username=chunk['username'], password=chunk['password'], 
    proxy_chrome_extension=proxy_chrome_extension, nogui=True)

Do you have any idea what am I doing wrong? 

Thank you for your amazing work guys!

**Comment by octavius-1** [comment]
Did you find a way to make it work?
