### ISSUE TITLE
instapy liking and commeting same profile over and over

### ISSUE THREAD

**Issue by c0d3x27** [InstaPy/InstaPy#3774]
## Expected Behavior
interact with someone followers to comment and like 2 photos of each profile the bot finds.

## Current Behavior
like and comment every single photo in the same profile over and over and over
## InstaPy configuration

from instapy import InstaPy

# Write your automation here
# Stuck ? Look at the github page or the examples in the examples folder

# login credentials
insta_username = 'user'
insta_password = 'pass1223'

# If you want to enter your Instagram Credentials directly just enter
# username=<your-username-here> and password=<your-password> into InstaPy
# e.g like so InstaPy(username="instagram", password="test1234")

bot = InstaPy(username=insta_username, password=insta_password, selenium_local_session=False)
bot.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub')
bot.login()
bot.set_simulation(enabled=True)
bot.set_relationship_bounds(enabled=True,
             potency_ratio=None,
              delimit_by_numbers=True,
               max_followers=3000,
                max_following=2000,
                 min_followers=45,
                  min_following=10)
bot.set_quota_supervisor(enabled=True, peak_comments=(21, 240))
bot.set_dont_include(["salvati_jasmin", "justajuice", "desmowoman_"])
bot.set_dont_like(["pizza", "#store", "buy", "favorite", "food"])

#actions
bot.set_skip_users(skip_private=True, skip_no_profile_pic=True)

# activity
bot.set_user_interact(amount=2, randomize=True, percentage=100, media='Photo')
bot.set_do_follow(enabled=False, percentage=100)
bot.set_do_like(enabled=True, percentage=100)
bot.set_do_comment(enabled=True, percentage=100)
comments1 = [u'piacciono le tue foto, belle! \U0001F929', u'belle foto, carina questa! \U0001F917', u'Troppo bella questa ;)! \U0001F60D']
comments2 = ['ummm.. piace questa, bel profilo! @{}']
bot.set_comments(comments=comments1+comments2, media='Photo')
bot.interact_user_followers(['sofiaam'], amount=500, randomize =False)

**Comment by sionking** [comment]
known
