### ISSUE TITLE
Stopped working: session.set_dont_unfollow_active_users 

### ISSUE THREAD

**Issue by ExportEh** [InstaPy/InstaPy#3776]
`from` instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = 'xxxxx'
insta_password = 'xxxxx'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True)

with smart_run(session):
    """ Activity flow """
    # settings
    session.set_dont_unfollow_active_users(enabled=True, posts=6)
    session.set_dont_include([bunch of people'])

# actions
    session.unfollow_users(amount=50, allFollowing=True, style="FIFO", unfollow_after=480*60*60, `sleep_delay=450)`

Hey all!

For the last 2 days my clean up script isn't working. I've tried on 2 different machines with 2 different I.Ps and accounts. They both stopped. 

According to my previous log it use to scan each post. 
Getting active users who liked the latest 3 posts:
  ~collecting the usernames from posts with the boundary of 500

INFO [2018-12-20 09:55:37] [XXXX]  Post 1  |  Likers: found 227, catched 228
INFO [2018-12-20 09:56:22] [XXXX]  Post 2  |  Likers: found 254, catched 255
INFO [2018-12-20 09:57:16] [XXXX]  Post 3  |  Likers: found 336, catched 335

Now all it does is....
INFO [2019-01-18 21:23:26] [XXXX]  Getting active users who liked the latest 3 posts:
  ~collecting the usernames from posts with the boundary of 500

INFO [2019-01-18 21:26:38] [XXXX]  Gathered total of 0 unique active followers from the latest 3posts in 3 minutes and 11 seconds
INFO [2019-01-18 21:26:38] [XXXX]  Starting to unfollow users..
INFO [2019-01-18 21:26:42] [XXXX]  Unfollowing the users you are following
INFO [2019-01-18 21:34:19] [XXXX]  Total 2 users available to unfollow  ~not found in 'followedPool.csv': 2  |  didn't pass `unfollow_after`: 502
INFO [2019-01-18 21:34:19] [XXXX]  Could not grab requested amount of usernames to unfollow:  

It will then kick out the 2. It should be finding hundreds. 
It is not doing the Post: likers found, etc...

Any suggestions to get it up and going again?

**Comment by sionking** [comment]
def set_dont_unfollow_active_users(self,
                                       enabled=False,
                                       posts=4,
                                       boundary=500):
        """Prevents unfollow followers who have liked one of
        your latest X posts"""

        if self.aborting:
            return

        # do nothing
        if not enabled:
            return

        active_users = []
        
        # list of users who liked our media
        photo_urls = get_photo_urls_from_profile(self.browser, self.username, posts, randomize=False)
        sleep(1)

        if not isinstance(photo_urls, list):
            photo_urls = [photo_urls]

        for photo_url in photo_urls:
            active_users.extend(users_liked(self.browser, photo_url, boundary))

        # include active user to not unfollow list
        self.dont_include.update(active_users)

**Comment by ExportEh** [comment]
I appreciate the reply. 
I tried this in the quickstart.py and keep getting indent errors. 
I tabbed the beginning of each line. It still won't run. 

Any suggestions?

**Comment by ExportEh** [comment]
Here is more info on my last post. Hopefully this isn’t overkill….

On 2 computers (Windows 10 and windows 7), on 2 different profiles of just pictures (no videos) the following code is not scanning my last 6 posts.
session.set_dont_unfollow_active_users

It used to do the following:
Getting active users who liked the latest 3 posts:
~collecting the usernames from posts with the boundary of 500
INFO [2018-12-20 09:55:37] [XXXX] Post 1 | Likers: found 227, catched 228
INFO [2018-12-20 09:56:22] [XXXX] Post 2 | Likers: found 254, catched 255
INFO [2018-12-20 09:57:16] [XXXX] Post 3 | Likers: found 336, catched 335

It would then output the count and then start unfollowing.
Now my log hits 0 users… 

I’ve done a full uninstall, complete delete of the directory on 1 computer keeping the Log folder as a backup and put it back after. 
My other scripts for follow and unfollow non-following users works great. 
Chrome driver is the latest. 
Attached is my .py and the log of when it worked and the log as of this morning. 

[Old log.txt](https://github.com/timgrossmann/InstaPy/files/2776692/Old.log.txt)
[Recent Run log.txt](https://github.com/timgrossmann/InstaPy/files/2776693/Recent.Run.log.txt)

My .py code:
`from instapy import InstaPy
from instapy.util import smart_run



# login credentials
insta_username = 'XXXXX'
insta_password = 'XXXXX'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True)


with smart_run(session):
    """ Activity flow """
    # settings
    session.set_dont_unfollow_active_users(enabled=True, posts=6)
    session.set_dont_include(['Bunch of people added here'])

# actions
    session.unfollow_users(amount=500, allFollowing=True, style="FIFO", unfollow_after=150*60*60, sleep_delay=450)
`

**Comment by ExportEh** [comment]
> ```
> def set_dont_unfollow_active_users(self,
>                                    enabled=False,
>                                    posts=4,
>                                    boundary=500):
>     """Prevents unfollow followers who have liked one of
>     your latest X posts"""
> 
>     if self.aborting:
>         return
> 
>     # do nothing
>     if not enabled:
>         return
> 
>     active_users = []
>     
>     # list of users who liked our media
>     photo_urls = get_photo_urls_from_profile(self.browser, self.username, posts, randomize=False)
>     sleep(1)
> 
>     if not isinstance(photo_urls, list):
>         photo_urls = [photo_urls]
> 
>     for photo_url in photo_urls:
>         active_users.extend(users_liked(self.browser, photo_url, boundary))
> 
>     # include active user to not unfollow list
>     self.dont_include.update(active_users)
> ```

**I just made the change above. No change and an error...**


$ py clean.py                                                                                                                                                                                   
INFO [2019-01-20 15:00:52] [XXXXX]  Session started!                                                                                                                               
INFO [2019-01-20 15:01:27] [XXXXX]  Logged in successfully!                                                                                                                        
INFO [2019-01-20 15:01:27] [XXXXX]  Saving account progress...                                                                                                                     
INFO [2019-01-20 15:01:30] [XXXXX]  Getting active users who liked                                                                                                                 
the latest 6 posts:                                                                                                                                                                             
  ~collecting the usernames from posts with the boundary of 500                                                                                                                                 
                                                                                                                                                                                                
INFO [2019-01-20 15:07:54] [XXXXX]  Gathered total of 0 unique active followers from the latest 6posts in 6 minutes and 23 seconds                                                 
INFO [2019-01-20 15:07:54] [XXXXX]  Starting to unfollow users..                                                                                                                   
INFO [2019-01-20 15:07:57] [XXXXX]  Unfollowing the users you are following                                                                                                        
ERROR [2019-01-20 15:08:24] [XXXXX]  Sorry, an error occurred: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@ROLE='dialog']"}           
  (Session info: headless chrome=71.0.3578.98)                                                                                                                                                  
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.17763 x86_64)                                                                      
                                                                                                                                                                                                
INFO [2019-01-20 15:08:26] [XXXXX]  Sessional Live Report:                                                                                                                         
        |> No any statistics to show                                                                                                                                                            
                                                                                                                                                                                                
On session start was FOLLOWING 3701 users & had 4336 FOLLOWERS                                                                                                                                  
[Session lasted 7.62 minutes]                                                                                                                                                                   
INFO [2019-01-20 15:08:26] [XXXXX]  Session ended!

**Comment by ExportEh** [comment]
Ok... So I tried running it with Headless off... 
It loads up great. Goes to my first picture, Opens the list of people who liked my photo and stops there. 
It is not scrolling down the list. If I "X" out of the picture, it moves to the next picture but will not scroll down the list of users who clicked like. 

Hope that helps with the Diagnosing.

**Comment by derboris2000** [comment]
I have the same issue on my raspberry.

**Comment by ExportEh** [comment]
> I have the same issue on my raspberry.

If you figure it out before I do, please let me know. I'll keep you posted if I figure it out.

**Comment by ExportEh** [comment]
Corrected by https://github.com/timgrossmann/InstaPy/pull/3796
