### ISSUE TITLE
How to follow likers of top-comments on a certain page

### ISSUE THREAD

**Issue by daniel22-git** [InstaPy/InstaPy#3778]
Is it possible to follow the likers of the top comments from a certain instagram page?

Many thanks in advance!

**Comment by brahimdev** [comment]
HI @dandud100 these two options can do the job but it needs some creation to work 
''session.set_user_interact(amount=3,
				 percentage=32,
                  randomize=True,
                   media='Video')
session.follow_commenters(['user1', 'user2', 'user3'], amount=100, daysold=365, max_pic = 100, sleep_delay=600, interact=True)''
and this 
''session.set_user_interact(amount=2,
				 percentage=70,
                  randomize=True,
                   media='Photo')
session.follow_likers (['user1' , 'user2'], photos_grab_amount = 2, follow_likers_per_photo = 3, randomize=True, sleep_delay=600, interact=True)''

**Comment by daniel22-git** [comment]
@brahimdev i am sorry but i think this is not what i wanted. Thanks anyways!!
