### ISSUE TITLE
Help: issue with config for comments

### ISSUE THREAD

**Issue by Areahints** [InstaPy/InstaPy#3780]
## Expected Behavior
with the settings here, I'm expecting my bot to comment, follow and like

```
# let's go! :>
with smart_run(session):
    # settings
    session.like_by_tags(['tag 1', 'tag 2'], amount=10, interact=True)
    session.set_relationship_bounds (enabled=True,
                                      potency_ratio=0.5,
                                      delimit_by_numbers=True,
                                       max_followers=10000,
                                       max_following=5000,
                                       min_followers=0,
                                       min_following=0)
    session.set_ignore_if_contains(['death','sad','bad'])
    session.set_do_comment(enabled=True, percentage=55)
    session.set_comments(['awesome @{}','cool @{}', 'great @{}' ])
    session.set_user_interact(amount=4, randomize=True, percentage=50, media='Photo')

    # activity
    session.follow_likers (['account 1' , 'account 2'], photos_grab_amount = 3, follow_likers_per_photo = 30, randomize=False, sleep_delay=60, interact=False)

```

## Current Behavior

after a successful run, InstaPy follows and likes but does not comment.
i have no idea why?

Also is there a difference between code that starts under **#settings** and **#activity** . i feel like there should be a way in the readme to identify which code can run where

**Comment by jasonbleasdell** [comment]
Try setting interact=False to interact=True under the session.follow.likers. (The last line of the program)

#settings and #activity are simply comments. They do nothing but to visually separate the different parts of the program. You have to have the settings executed first before the actual actions execute otherwise your program will not run like expected.

**Comment by Areahints** [comment]
@jasonbleasdell thanks will try that. 

I know they are simply comments however I have no way to distinguish which code should be placed in the settings and which should be under activity.  I dunno if you understand what I'm saying. If I decided to put session set relationship bounds under the activity section it wouldn't run. But how am I supposed to know where it should be put.

**Comment by Areahints** [comment]
tried it and it didn't work

any pointers? @uluqulu @sionking

**Comment by Areahints** [comment]
tried setting all interact parameters to true still no luck @uluqulu

**Comment by uluQulu** [comment]
@Areahints 
![image](https://user-images.githubusercontent.com/33269249/52162544-f2421600-26ee-11e9-878c-73fbdced7560.png)
Your **quickstart** script is a python source code file.

It means what your write in there is gonna be executed in the order they are written.
And in your script,  you wrote `like_by_tags()` before other settings  (_e.g. commenting config_) and it's obvious that it will not put comments during that activity.

If you find difficulty to differentiate activities vs settings.
Just note that activities does something for you.
But settings does something for the activities and they start by **set_** prefix [mostly].

---

If you still don't get that straight-forward logic, let me know.

---

Cheers 😁
---

**Comment by uluQulu** [comment]
I also think, @Areahints 
You are **misusing** `set_ignore_if_contains()` feature;
See Readme.
![image](https://user-images.githubusercontent.com/33269249/52162582-ddb24d80-26ef-11e9-94bc-425104deb107.png)


Maybe you want `set_dont_like()` feature for that;
![image](https://user-images.githubusercontent.com/33269249/52162600-25d17000-26f0-11e9-8829-68c7966a1919.png)

---

Cheers 😁
---

**Comment by Areahints** [comment]
ok thanks! i will try this out now!
