### ISSUE TITLE
ModuleNotFoundError: No module named 'InstaPy'

### ISSUE THREAD

**Issue by memesemperor** [InstaPy/InstaPy#3785]
## Current Behavior
```
Traceback (most recent call last):
  File "C:\Users\princ\Documents\GitHub\InstaPy\quickstart.py", line 1, in <module>
    from InstaPy import instapy
ModuleNotFoundError: No module named 'InstaPy'
```

**Comment by memesemperor** [comment]
Traceback (most recent call last):
  File "C:\Users\princ\Documents\GitHub\InstaPy\quickstart.py", line 1, in <module>
    from InstaPy import instapy
ModuleNotFoundError: No module named 'InstaPy'

**Comment by mkhattar** [comment]
Follow the steps carefully to install Instapy

**Comment by memesemperor** [comment]
Could you send the link please

**Comment by timgrossmann** [comment]
@memesemperor https://github.com/timgrossmann/InstaPy#basic-installation
Hope this helps

**Comment by memesemperor** [comment]
I am still facing the same problem @mkhattar @timgrossmann 

**Traceback (most recent call last):
  File "C:\Users\princ\Documents\GitHub\InstaPy\quickstart.py", line 1, in <module>
    from InstaPy import instapy
ModuleNotFoundError: No module named 'InstaPy'
**
[Uploading 20190123_152140.jpg…]()

**Comment by santibatte** [comment]
same problem

**Comment by rajanverma-me** [comment]
same problem . can anybody check. I have ran `sudo pip install instapy --ignore-installed` on my ubuntu machine. It got installed successfully. But while running the script it shows

`Traceback (most recent call last):
  File "quickstart.py", line 2, in <module>
    from instapy import InstaPy
ImportError: No module named instapy`

**Comment by adelabdelli** [comment]
Same problem

**Comment by carlosacchi** [comment]
same problem too :(

**Comment by Jostino** [comment]
Same problem here after changed configuration from `pip3 install instapy` to `git clone ..., git checkout dev`
I'm on RaspBerry Pi 3+

**Comment by Jostino** [comment]
Solved:
`pip3 install --user instapy`

**Comment by muzhaqi16** [comment]
I have the same problem

**Comment by muzhaqi16** [comment]
I was able to fix it by using version 3.7.5 of python. It seems like it doesn't work well with version 3.8.x

**Comment by bhzdios** [comment]
same problem

**Comment by MatStar15** [comment]
same problem here, even using python 3.7.5

**Comment by azhang11** [comment]
same problem

**Comment by Hollywd** [comment]
Same problem after install.bat on Windows 8.1 Python 3.9.0

**Comment by Hollywd** [comment]
ASM Builds for BoringSSL currently not supported on: win-amd64
Found cython-generated files...
running install
running build
running build_py
running build_project_metadata
creating python_build
creating python_build\lib.win-amd64-3.9
creating python_build\lib.win-amd64-3.9\grpc
copying src\python\grpcio\grpc\_auth.py -> python_build\lib.win-amd64-3.9\gr

copying src\python\grpcio\grpc\_channel.py -> python_build\lib.win-amd64-3.9
c
copying src\python\grpcio\grpc\_common.py -> python_build\lib.win-amd64-3.9\

copying src\python\grpcio\grpc\_compression.py -> python_build\lib.win-amd64
\grpc
copying src\python\grpcio\grpc\_grpcio_metadata.py -> python_build\lib.win-a
-3.9\grpc
copying src\python\grpcio\grpc\_interceptor.py -> python_build\lib.win-amd64
\grpc
copying src\python\grpcio\grpc\_plugin_wrapping.py -> python_build\lib.win-a
-3.9\grpc
copying src\python\grpcio\grpc\_runtime_protos.py -> python_build\lib.win-am
3.9\grpc
copying src\python\grpcio\grpc\_server.py -> python_build\lib.win-amd64-3.9\

copying src\python\grpcio\grpc\_simple_stubs.py -> python_build\lib.win-amd6
9\grpc
copying src\python\grpcio\grpc\_utilities.py -> python_build\lib.win-amd64-3
rpc
copying src\python\grpcio\grpc\__init__.py -> python_build\lib.win-amd64-3.9
c
creating python_build\lib.win-amd64-3.9\grpc\aio
copying src\python\grpcio\grpc\aio\_base_call.py -> python_build\lib.win-amd
.9\grpc\aio
copying src\python\grpcio\grpc\aio\_base_channel.py -> python_build\lib.win-
4-3.9\grpc\aio
copying src\python\grpcio\grpc\aio\_base_server.py -> python_build\lib.win-a
-3.9\grpc\aio
copying src\python\grpcio\grpc\aio\_call.py -> python_build\lib.win-amd64-3.
pc\aio
copying src\python\grpcio\grpc\aio\_channel.py -> python_build\lib.win-amd64
\grpc\aio
copying src\python\grpcio\grpc\aio\_interceptor.py -> python_build\lib.win-a
-3.9\grpc\aio
copying src\python\grpcio\grpc\aio\_metadata.py -> python_build\lib.win-amd6
9\grpc\aio
copying src\python\grpcio\grpc\aio\_server.py -> python_build\lib.win-amd64-
grpc\aio
copying src\python\grpcio\grpc\aio\_typing.py -> python_build\lib.win-amd64-
grpc\aio
copying src\python\grpcio\grpc\aio\_utils.py -> python_build\lib.win-amd64-3
rpc\aio
copying src\python\grpcio\grpc\aio\__init__.py -> python_build\lib.win-amd64
\grpc\aio
creating python_build\lib.win-amd64-3.9\grpc\beta
copying src\python\grpcio\grpc\beta\implementations.py -> python_build\lib.w
md64-3.9\grpc\beta
copying src\python\grpcio\grpc\beta\interfaces.py -> python_build\lib.win-am
3.9\grpc\beta
copying src\python\grpcio\grpc\beta\utilities.py -> python_build\lib.win-amd
.9\grpc\beta
copying src\python\grpcio\grpc\beta\_client_adaptations.py -> python_build\l
in-amd64-3.9\grpc\beta
copying src\python\grpcio\grpc\beta\_metadata.py -> python_build\lib.win-amd
.9\grpc\beta
copying src\python\grpcio\grpc\beta\_server_adaptations.py -> python_build\l
in-amd64-3.9\grpc\beta
copying src\python\grpcio\grpc\beta\__init__.py -> python_build\lib.win-amd6
9\grpc\beta
creating python_build\lib.win-amd64-3.9\grpc\experimental
copying src\python\grpcio\grpc\experimental\gevent.py -> python_build\lib.wi
d64-3.9\grpc\experimental
copying src\python\grpcio\grpc\experimental\session_cache.py -> python_build
.win-amd64-3.9\grpc\experimental
copying src\python\grpcio\grpc\experimental\__init__.py -> python_build\lib.
amd64-3.9\grpc\experimental
creating python_build\lib.win-amd64-3.9\grpc\framework
copying src\python\grpcio\grpc\framework\__init__.py -> python_build\lib.win
64-3.9\grpc\framework
creating python_build\lib.win-amd64-3.9\grpc\_cython
copying src\python\grpcio\grpc\_cython\__init__.py -> python_build\lib.win-a
-3.9\grpc\_cython
creating python_build\lib.win-amd64-3.9\grpc\experimental\aio
copying src\python\grpcio\grpc\experimental\aio\__init__.py -> python_build\
win-amd64-3.9\grpc\experimental\aio
creating python_build\lib.win-amd64-3.9\grpc\framework\common
copying src\python\grpcio\grpc\framework\common\cardinality.py -> python_bui
ib.win-amd64-3.9\grpc\framework\common
copying src\python\grpcio\grpc\framework\common\style.py -> python_build\lib
-amd64-3.9\grpc\framework\common
copying src\python\grpcio\grpc\framework\common\__init__.py -> python_build\
win-amd64-3.9\grpc\framework\common
creating python_build\lib.win-amd64-3.9\grpc\framework\foundation
copying src\python\grpcio\grpc\framework\foundation\abandonment.py -> python
ld\lib.win-amd64-3.9\grpc\framework\foundation
copying src\python\grpcio\grpc\framework\foundation\callable_util.py -> pyth
uild\lib.win-amd64-3.9\grpc\framework\foundation
copying src\python\grpcio\grpc\framework\foundation\future.py -> python_buil
b.win-amd64-3.9\grpc\framework\foundation
copying src\python\grpcio\grpc\framework\foundation\logging_pool.py -> pytho
ild\lib.win-amd64-3.9\grpc\framework\foundation
copying src\python\grpcio\grpc\framework\foundation\stream.py -> python_buil
b.win-amd64-3.9\grpc\framework\foundation
copying src\python\grpcio\grpc\framework\foundation\stream_util.py -> python
ld\lib.win-amd64-3.9\grpc\framework\foundation
copying src\python\grpcio\grpc\framework\foundation\__init__.py -> python_bu
lib.win-amd64-3.9\grpc\framework\foundation
creating python_build\lib.win-amd64-3.9\grpc\framework\interfaces
copying src\python\grpcio\grpc\framework\interfaces\__init__.py -> python_bu
lib.win-amd64-3.9\grpc\framework\interfaces
creating python_build\lib.win-amd64-3.9\grpc\framework\interfaces\base
copying src\python\grpcio\grpc\framework\interfaces\base\base.py -> python_b
\lib.win-amd64-3.9\grpc\framework\interfaces\base
copying src\python\grpcio\grpc\framework\interfaces\base\utilities.py -> pyt
build\lib.win-amd64-3.9\grpc\framework\interfaces\base
copying src\python\grpcio\grpc\framework\interfaces\base\__init__.py -> pyth
uild\lib.win-amd64-3.9\grpc\framework\interfaces\base
creating python_build\lib.win-amd64-3.9\grpc\framework\interfaces\face
copying src\python\grpcio\grpc\framework\interfaces\face\face.py -> python_b
\lib.win-amd64-3.9\grpc\framework\interfaces\face
copying src\python\grpcio\grpc\framework\interfaces\face\utilities.py -> pyt
build\lib.win-amd64-3.9\grpc\framework\interfaces\face
copying src\python\grpcio\grpc\framework\interfaces\face\__init__.py -> pyth
uild\lib.win-amd64-3.9\grpc\framework\interfaces\face
creating python_build\lib.win-amd64-3.9\grpc\_cython\_cygrpc
copying src\python\grpcio\grpc\_cython\_cygrpc\__init__.py -> python_build\l
in-amd64-3.9\grpc\_cython\_cygrpc
creating python_build\lib.win-amd64-3.9\grpc\_cython\_credentials
copying src\python\grpcio\grpc\_cython\_credentials\roots.pem -> python_buil
b.win-amd64-3.9\grpc\_cython\_credentials
running build_ext
error: [WinError 2] The system cannot find the file specified

**Comment by alireza-es** [comment]
Just use `python3` instead of `python` to run your code. 
For an example: 
`$ python3 quickstart.py`
