### ISSUE TITLE
.set_dont_like not working in my code

### ISSUE THREAD

**Issue by wendyhouserules** [InstaPy/InstaPy#379]
Hi Tim or anyone that may be able to help.

I am currently having trouble with the .set_dont_like function. It's not working whether I put a string into the function itself or, if i put a variable in which contains a list. I have previously set this to ignore posts with '#model' in as well as '[model' and ']model' which when contained in the post are ignored and the image is liked and commented on anyway :/ . I'm using a variable/list here as more than one string in the .set_dont_like gives an error saying that the function only takes two arguments.

Otherwise i've found this pretty easy and a noob so thanks so much! It's awesome :)

My code:
```python
dontLike = ['#dontlike1', '[dontlike2', ']dontlike3', '#dontike4', 'dontlike5']

.login()\
    .set_do_follow(enabled=True, percentage=100, times=1)\
    .set_do_comment(enabled=True, percentage=20)\
    .set_comments([u':smiley:', 'Cool'], media='Photo')\
    .set_ignore_if_contains(['item1', 'item2', 'item3', 'item4', 'item5', 'item6'])\
    .set_dont_like('dontLike')\
	.set_use_clarifai(enabled=False, secret='***************************', proj_id='****************************')\
	.clarifai_check_img_for(['nsfw'])\
	.clarifai_check_img_for(['check1', 'check2', 'check3'], comment=True, comments=['Sweet!', 'Nice!', 'Awesome!'])\
	.clarifai_check_img_for(['check1', 'check2', 'check3', 'check4', 'check5'], comment=True, comments=['Amazing!', 'This is so cool', 'Awesome!'])\
    .like_by_tags(['#hash1', '#hash2', '#hash3'], amount=20)\
	.unfollow_users(amount=10, onlyInstapyFollowed = True )\
    .end()

**Comment by timgrossmann** [comment]
@wendyhouserules When using a variable in the braces `()` you should not use a string, this won't work.
You can pass a variable by just using the name without `''`

in you case the solution should be:

```python
 .set_dont_like(dontLike)\
```

instead of

```python
 .set_dont_like('dontLike')\
```

**Comment by wendyhouserules** [comment]
Hi Tim

Yes I know variables are not strings. I must have made an error when changing the code to add to this page. 

Unfortunately that is not the issue. Do you have any other advice please?

Thanks,

Chris

**Comment by timgrossmann** [comment]
@wendyhouserules The checks with clarifai also won't work like this, is this wanted behaviour?

The posts probably had something that you specified in `.set_ignore_if_contains()`. Could you give an example, please?
What don't likes did you use, what ignores did you use and what was the picture that was commented?
