### ISSUE TITLE
InstaPy and Raspberry Pi 3+ w/Docker

### ISSUE THREAD

**Issue by razki** [InstaPy/InstaPy#3792]
## Expected Behavior
I would like to run InstaPy on a Raspberry Pi using docker. So far I've tried everything I can think of, including an ARM specific selenium image. Tried docker networking also but no luck.

## Current Behavior
Doesn't work unfortunately and I'm out of ideas.

Would be interested to hear if anyone here has managed to do this?

Thanks.

_Worth noting that I've sunk quite a considerable amount of time into this myself before asking via discord (no luck there unfortunately) and now here_

**Comment by HCWcoder** [comment]
@razki did you follow those [steps](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Raspberry.md) ?

**Comment by razki** [comment]
@HCWcoder I think I've already covered that in my initial question. But to add, those steps do not involve docker, which is detailed in the initial question also. They merely explain how to get the bot working in a virtualenv.
