### ISSUE TITLE
Unfollow problem

### ISSUE THREAD

**Issue by Yosoycoder** [InstaPy/InstaPy#3793]
## Expected Behavior

Regular unfollow of user

## Current Behavior

It does not start to unfollow users, it shows the following messages instead (I have changed the account name with xxxxxx):

INFO [2019-01-21 20:12:16] [xxxxxxx]  Zz :[ time to take a good nap  ~sleeping 2.0 minutes
INFO [2019-01-21 20:13:42] [xxxxxxx]  Yawn :] let's go!

INFO [2019-01-21 20:13:42] [xxxxxxx]  Found 404 loyal followers!  ~will not unfollow them
INFO [2019-01-21 20:13:42] [xxxxxxx]  Total 1 users available to unfollow  ~didn't pass `unfollow_after`: 1251

INFO [2019-01-21 20:13:42] [xxxxxxx]  You have requested more amount: 49 than 1 of users available to unfollow~using available amount

INFO [2019-01-21 20:13:42] [xxxxxxx]  Ongoing Unfollow [1/1]: now unfollowing 'b'tylerrjoseph''...
INFO [2019-01-21 20:13:44] [xxxxxxx]  --> Already unfollowed 'tylerrjoseph'! or a private user that rejected your req

INFO [2019-01-21 20:13:47] [xxxxxxx]  --> Total people unfollowed : 0

After this messages, it continues to run the rest of the code without problems. I

Any suggestions? I updated the whole folder with the newest available files like 5 days ago and it has been working without problems until today. Also I have more than enough available people to unfollow according to my unfollow settings.

Thanks for your help!

**Comment by sionking** [comment]
set unfollow_after for lower

**Comment by aliceEddie** [comment]
having a similar problem. Can't unfollow anyone, no matter what I set `unfollow_after` to. 

always gives me this: 
```
INFO [2019-01-23 14:06:33] [xxxxxxxx]  Found 0 loyal followers!  ~will not unfollow them
INFO [2019-01-23 14:06:33] [xxxxxxxx]  Total 0 users available to unfollow  ~didn't pass 'unfollow_after': 0

INFO [2019-01-23 14:06:33] [xxxxxxxx]  There are no any users available to unfollow
INFO [2019-01-23 14:06:33] [xxxxxxxx]  --> Total people unfollowed : 0
```

worked fine two days ago. Instapy is up to date.
