### ISSUE TITLE
Web Instagram is not refreshing posts

### ISSUE THREAD

**Issue by octavius-1** [InstaPy/InstaPy#3797]
Has someone else noticed that lately instagram hasn't been refreshing the posts in the web version? I already tried with different accounts and same behavior happens every time. Is this a bug?

**Comment by tonykyriakidis** [comment]
hey there, did you update to the latest version of instapy and chromedriver?

**Comment by traincodesleep** [comment]
I believe I am seeing this also. Looking at the logs for my like_by_tags run, the majority of the posts were rejected as the users were already in the blacklist.
I verified that the posts were the same by checking the logs and comparing the URLs and they were identical, with the runs being 24 hours apart and it was a popular hashtag (so there should have been new posts).
Instagram.com has been having a lot of issues recently.
