### ISSUE TITLE
Process crashes on dead link/ if post has been deleted.

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#38]
> There are some deleted posts/ dead links when going through the to be liked pictures. Right now the process crashes when one of these pages shows up.

- [x] Fix the problem by catching the error and continuing with the other posts

**Comment by eduardocalazansjr** [comment]
check https://github.com/timgrossmann/InstaPy/issues/26#issuecomment-292138620

**Comment by timgrossmann** [comment]
Thanks!

@vlntdds why not make a PR? 👍

**Comment by eduardocalazansjr** [comment]
@timgrossmann i'm just waiting for the feedback from @ianjuma and @mareknebesar.
They have different instagram page style.

But will do the PR ASAP

**Comment by timgrossmann** [comment]
@vlntdds Awesome, you're the man!

**Comment by ianjuma** [comment]
I think a PR by @vlntdds might have fixed this for me? Have not run on this after using [like_util](https://gist.github.com/vlntdds/8ff796b629b2be89ae7e6f04dec68296) Can't any exception handling for an error; There's the missing post log, and the process continues running fine.

**Comment by timgrossmann** [comment]
Fixed with #39
