### ISSUE TITLE
Feature req. list of alive users (different from active_users)

### ISSUE THREAD

**Issue by ianmihura** [InstaPy/InstaPy#3802]
Just recently cloned the repo locally and started using it, extremely satisfied, a million thank you and congrats!

I had this feature in mind that I cannot see in the current system: to **unfollow dead users**

## Feature
From own following list, get a sub-list of users that have recently made a post in Instagram (recently: arbitrary length of time)
Add them to dont_include list (dont unfollow)

##### Note
Not the same as get_active_users()
I am of course not familiar with the code and a bit rusty in coding in general, tho I'd be happy to give it a try
Maybe this functionality is hidden somewhere and I can't find it tho! Thanks :)

**Comment by sionking** [comment]
you can just check for "last post" before you going to unfollow.

**Comment by ianmihura** [comment]
Are you aware of any global variable that stores it? Something like
> last_post
