### ISSUE TITLE
Action Blocked

### ISSUE THREAD

**Issue by nbgabriel** [InstaPy/InstaPy#3808]
Hello there!

Im getting constantly blocked, this are the options that i use, what can i do to avoid this?. Thanks.

    session.set_action_delays(enabled=True,
                randomize=True,
                  random_range=(70, 150),
                    like=40,
                      comment=10,
                        follow=40,
                          unfollow=60)

    session.set_quota_supervisor(enabled=True,
                 sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], 
                   sleepyhead=True, 
                    stochastic_flow=True, 
                     notify_me=True,
                       peak_likes=(45, 900), 
                         peak_follows=(50, None),
                           peak_unfollows=(50, 600), 
                             peak_server_calls=(500, None))

Im using a http proxy. 

Thanks!

**Comment by octavius-1** [comment]
What do you mean by blocked?

**Comment by nbgabriel** [comment]
> What do you mean by blocked?

The message that appears when i try to like a photo. "Action Blocked, based on previous use of this feature your account has been temporaly blocked from taking this action. This block will expire XX/XX/XX" 

Thanks

**Comment by Tr1pke** [comment]
instagram blocked you for a amount of time, configure your file so it do less actions

**Comment by nbgabriel** [comment]
> instagram blocked you for a amount of time, configure your file so it do less actions

Yes, but if a configure less than i have today, i will put likes every hour hahaha. 

Someone has configured the quota and delays and its working without problems?. 

Thanks!

**Comment by octavius-1** [comment]
I faced those issues and I adapted my quota like this:
peak_likes=(50, 700)
peak_comments=(20, 250)
peak_follows=(30, 400)
peak_unfollows=(30, 400)
peak_server_calls=(None, 5500)
Has been running for two weeks now with that config and no blockings since then.

**Comment by nbgabriel** [comment]
> I faced those issues and I adapted my quota like this:
> peak_likes=(50, 700)
> peak_comments=(20, 250)
> peak_follows=(30, 400)
> peak_unfollows=(30, 400)
> peak_server_calls=(None, 5500)
> Has been running for two weeks now with that config and no blockings since then.

Thanks! i will try that.

**Comment by potentowl** [comment]
@nbgabriel my accs used to like average  (55 likes/hr x 24/hrs = 1320 likes/day) with no block but they updated something now it blocks with just (40 likes/hr = 960 likes/day)

**Comment by nbgabriel** [comment]
> @nbgabriel my accs used to like average (55 likes/hr x 24/hrs = 1320 likes/day) with no block but they updated something now it blocks with just (40 likes/hr = 960 likes/day)

Thats what happens to me, first i put 60 likes hr, blocked, then 50, blocked, 40, blocked, OMFG!, whats the story? 20 likes ?. Also can be the mix, follow, like, comment, unfollow, maybe if we put less actions will be better, i do not know. 

Thanks for your reply.

**Comment by ltiwana** [comment]
I am thinking of taking a one week break and then try with peak 50 likes.

**Comment by Tr1pke** [comment]
What’s the goal of your bot ?

**Comment by ltiwana** [comment]
I do everything. Like and comment on hastags and feed.

**Comment by Tr1pke** [comment]
But what’s your main goal of your account?

**Comment by nbgabriel** [comment]
> I am thinking of taking a one week break and then try with peak 50 likes.

ltiwana, if you do that, please then, tell me how it goes, thanks!



> But what’s your main goal of your account?

Tr1pke, i'm helping a friend to gain followers for his family bussiness. The main goal is to reach as many people as possible.

**Comment by Tr1pke** [comment]
> > I am thinking of taking a one week break and then try with peak 50 likes.
> 
> ltiwana, if you do that, please then, tell me how it goes, thanks!
> 
> > But what’s your main goal of your account?
> 
> Tr1pke, i'm helping a friend to gain followers for his family bussiness. The main goal is to reach as many people as possible.

Then do only follow/unfollow. it goes faster

**Comment by nbgabriel** [comment]
> Then do only follow/unfollow. it goes faster

Thanks for the advice!! i will try that!!

**Comment by ltiwana** [comment]
> > Then do only follow/unfollow. it goes faster
> 
> Thanks for the advice!! i will try that!!

I have tried that, but the follower growth is better with commenting and likes.

**Comment by ltiwana** [comment]
> > I am thinking of taking a one week break and then try with peak 50 likes.
> 
> ltiwana, if you do that, please then, tell me how it goes, thanks!
> 
> > But what’s your main goal of your account?
> 
> Tr1pke, i'm helping a friend to gain followers for his family bussiness. The main goal is to reach as many people as possible.

Sure. I will let you know. I am trying to reach out to more people and grow my following.

**Comment by Tr1pke** [comment]
> > > I am thinking of taking a one week break and then try with peak 50 likes.
> > 
> > 
> > ltiwana, if you do that, please then, tell me how it goes, thanks!
> > > But what’s your main goal of your account?
> > 
> > 
> > Tr1pke, i'm helping a friend to gain followers for his family bussiness. The main goal is to reach as many people as possible.
> 
> Sure. I will let you know. I am trying to reach out to more people and grow my following.

I do this now for 3 months. It’s a big success

**Comment by sionking** [comment]
2019 is like blocker.
Don't use proxy only home IP.
Also headless is detectable if not handled right.

**Comment by nbgabriel** [comment]
Sionking, hello!

I'm using a proxy and headless...... Sh#t haha. Thanks for the comment.

**Comment by GabrieleAnsaldo** [comment]
If you still get blocked with InstaPy read this:

So I actually found a fix if you really want to have an instagram bot. Basically instagram got very good at detecting bots so I tried to work around that. Basically I have connected my old android phone to the Raspberry (you can connect it to any computer) and I just send a bunch of adb commands to it. I wrote a little script. Its been working so well.

I guess instagram finds it hard to find bots from someone using the app itself and not the browser version.

Hit me up if you are interested in developing this project with me, there is still a lot to do to make it very efficient.
