### ISSUE TITLE
Aborting after not finding enough pictures

### ISSUE THREAD

**Issue by wemakefuture** [InstaPy/InstaPy#381]
Hello, 

i just wondered why it got less the last days. Then i realized of i made a typo: summer[

this caused following:

![image](https://user-images.githubusercontent.com/28114725/27991615-1010aeac-647d-11e7-880d-07bf03d1edba.png)

would be nice if this happens that the code just jumps to the next hashtag instead of aborting. thanks ;)

**Comment by timgrossmann** [comment]
@wecanfuture The special characters don't work this way...
They only for work `.dont_like`
