### ISSUE TITLE
permission denied to followedPool.csv

### ISSUE THREAD

**Issue by aliceEddie** [InstaPy/InstaPy#3814]
Hi everyone, 

I was suddenly no longer able to unfollow users and I got the following error:
`	b"[Errno 13] Permission denied: '/Users/marcel/Documents/instapy/InstaPy/logs/darqueanddearest/darqueanddearest_followedPool.csv'"`

running my script as `sudo` fixes the permission error but I dont really know what caused it. 
Is there any way of fixing the permission without running the script with sudo?

Thanks!

**Comment by ghost** [comment]
Change the permissions of the folder, but this makes your folder more vulnerable, i always just used sudo in my commands.

**Comment by tE3m** [comment]
Yes, there is a way. Use a venv. Basically the command is 
```
python -m venv <foldername>
```
That at least fixed it for me on a RPi. For further information, see in the docs in readme: preferred installation
