### ISSUE TITLE
Headless Auth Proxy Not Working

### ISSUE THREAD

**Issue by timnlupo** [InstaPy/InstaPy#3815]
## Expected Behavior
From the README, `To use proxy with authentication you should firstly generate proxy chrome extension (works only with headless_browser=False unless using FF where it works with headless_browser=True).` The auth proxy works if using `headless_browser=False` and Google Chrome. Per the README, the auth proxy should work with Firefox using `headless_browser=True` or `headless_browser=False`.

## Current Behavior
The auth proxy does not work at all with Firefox.

## InstaPy configuration
```
from instapy import InstaPy
from instapy.util import smart_run
from proxy_extension import create_proxy_extension

# login credentials
insta_username = '...'
insta_password = '...'
users_to_interact = ['...']

proxy = 'username:pass@ip:port'
proxy_chrome_extension = create_proxy_extension(proxy)

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  proxy_chrome_extension=proxy_chrome_extension,
                  headless_browser=False,
                  disable_image_load=True,
                  multi_logs=True,
                  use_firefox=True)
```
Using Windows, latest Firefox, latest geckodriver.

**Comment by adisoe** [comment]
same issue

**Comment by tE3m** [comment]
The fix for that has been merged into `dev/`.
