### ISSUE TITLE
refollow accounts after a couple of months

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#3824]
all,

i would like to REFOLLOW the same users after a couple of months
what file i need to delete for that so i dont get this message anymore:
INFO [2019-01-24 19:55:48] [xxx]  ---> antonella_latorre has already been followed 1 times

Thanks

**Comment by ExportEh** [comment]
I've never had luck with deleting a file, I've had bigger issues occur when doing so. 
Search your quickstart (or .py file) you use for the following:
`session.set_do_follow(enabled=True, percentage=100, times=1)`
Bump the times=1 to 2 and you should be all set and less evasive in my opinion.

**Comment by hw711** [comment]
it's stored in the followrestriction table of database but it doesn't have a time column so hard to tell when the accounts were followed you don't really know which ones to delete to allow refollow.  doing what exportEh accomplish about the same thing (but easier for people who don't about database) but also same problem, you don't know when the accounts were followed so if you set the limit to 2, you may end up refollow accounts you did last week.

**Comment by Tr1pke** [comment]
can i delete these old files?:
/home/steven/InstaPy/logs/xxx//relationship_data/steven.triathlon/followers/25-01-2019~full~4197.json
and i'm using "session.set_do_follow(enabled=True, percentage=100, times=2)" works perfectly

**Comment by Tr1pke** [comment]
can i delete these old files?:
/home/steven/InstaPy/logs/xxx//relationship_data/xxx/followers/25-01-2019full4197.json
and i'm using "session.set_do_follow(enabled=True, percentage=100, times=2)" works perfectly

**Comment by sionking** [comment]
There should be a delay feature ..
