### ISSUE TITLE
Still not able to get likers

### ISSUE THREAD

**Issue by octavius-1** [InstaPy/InstaPy#3827]
When trying to get likers from photos, I'm still looking at this message:
``` 
Got 0 likers shuffled randomly whom you can follow:
[]
``` 
I already tried with python2 and 3, using a raspberry and an AWS instance getting the same results.
I checked with headless_browser = False and I'm able to watch the dialog box being opened and the scrolling happened.
And yes, I do have the latest version of the repo. Could anyone help please?

**Comment by octavius-1** [comment]
I also tried cloning the repo from zero, same results.
Got this numbers:
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.71-v7+ armv7l)

**Comment by octavius-1** [comment]
Closing this issue, magically was fixed, assuming an instagram delayed update on my accounts.

**Comment by torreslucas13** [comment]
Still not able to get likers
