### ISSUE TITLE
syntax to randomize comment list

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#3828]
`session.set_comments_random.choice(["😀", "😁", "😂")]`

AttributeError: 'InstaPy' object has no attribute 'set_comments_random'

```
import random
random.choice(['1', '2', '3')]
```

How would one add the above function with the `session.set_comments` attribute ?

**Comment by loopypanda** [comment]
bump

**Comment by potentowl** [comment]
bump
