### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: chrome not reachable

### ISSUE THREAD

**Issue by diveu** [InstaPy/InstaPy#383]
Running on Digital Ocean Droplet with these configs:
1 GB Memory / 20 GB Disk / AMS2 - Ubuntu 16.04.2 x64

I did the How To Ubuntu setup, but I get this issue:

`Traceback (most recent call last):
  File "index.py", line 2, in <module>
    InstaPy(username='userNameChangedForIssue', password='password', nogui=True) \
  File "/root/InstaPy/instapy/instapy.py", line 44, in __init__
    self.browser = webdriver.Chrome(chromedriver_location, chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium-2.53.6-py3.5.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
  selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57),platform=Linux 4.4.0-83-generic x86_64)`

I've seen the similar issue #338 , but I still have no idea why it doesn't work. Anyone?

UPD: Tried running this code in console:
`self.display = Display(visible=0, size=(800, 600))
      self.display.start()

    chrome_options = Options()
    chrome_options.add_argument('--dns-prefetch-disable')
    chrome_options.add_argument('--no-sandbox')
    chrome_options.add_argument('--lang=en-US')
    chrome_options.add_experimental_option('prefs', {'intl.accept_languages': 'en-US'})
    browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)`
And it worked just fine. Strange.

**Comment by diveu** [comment]
If anyone is interested:
Fixed it with removing the `chrome_options.binary_location = chromedriver_location` line. I guess this one should be the location of Chome instead of chromedriver.

**Comment by shapetheLOLa** [comment]
Same problem, and removing `chrome_options.binary_location = chromedriver_location` helped!

**Comment by SameerKhan** [comment]
Agreed! Removing above worked for me too!

**Comment by diveu** [comment]
@timgrossmann fixed it in [this](https://github.com/timgrossmann/InstaPy/commit/ef762701d25b9e15cddf22b0f48fdd88aa69f7fd) commit, so I think we could close it

**Comment by amauryleproux** [comment]
I've got the same problem :/ and I've got the last version.

Try to launch a cron on an Ubuntu server 14.04
