### ISSUE TITLE
Like and comment specific comment

### ISSUE THREAD

**Issue by ceribbo** [InstaPy/InstaPy#3830]
Is it possible to implement like/comment only to comments containing specific text on posts?
thank you
@uluQulu

**Comment by uluQulu** [comment]
Yes @ceribbo.
You can implement it easily.
Write down the full specification of your request, I will help.

---

 Cheers 😁
---

**Comment by ceribbo** [comment]
Thank you @uluQulu !! You are always very kind!! 
So starting from the comment interaction I'd like to be able just like or reply only a comment containing a specific text or from a specific user.
For example, when allowing when I start interacting with some posts if the post contains a specific a comment with the text "great" I can like it.
Differently from interact_by_comments function, we should create a function comment_interaction with the parameters (enabled,["text1","text2",...],percentage, media, reply)
Do you think something like this is possible?
thanks you

**Comment by ceribbo** [comment]
up @uluQulu
