### ISSUE TITLE
PLEASE TEST: session.set_dont_unfollow_active_users

### ISSUE THREAD

**Issue by ExportEh** [InstaPy/InstaPy#3832]
## Expected Behavior
Scan the last 3 posts for likes & Remove any users who have not liked any of the pictures. 
Only remove those added after a 24 hour period. 
## Current Behavior
Not finding any users to remove past the 24 hour period.

## InstaPy configuration
`from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = 'XXXXX'
insta_password = 'XXXXX'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True)

with smart_run(session):
    """ Activity flow """
  `  # settings
    session.set_dont_unfollow_active_users(enabled=True, posts=3)`

    # actions
    session.unfollow_users(amount=500, allFollowing=True, style="FIFO", unfollow_after=24*60*60, sleep_delay=450)

`
## System Info
Windows 10. Python 3.7.1. Chromedriver 2.45
## Tested:
Ran in cmd.exe
Ran in Git Bash 2.20
Ran in Linux Mint OS (Same log files)
Tried various unfollow_after (24/90/180/480 & None)
No change in any variables. 
## My profile
4,684 followers
3,549 following
Over 90% increased with only Instapy
## Output
INFO [2019-01-26 11:49:11] [XXXXX]  Gathered total of 968 unique active followers from the latest 3 posts in 15 minutes and 42 seconds
INFO [2019-01-26 11:49:11] [XXXXX]  Starting to unfollow users..
INFO [2019-01-26 11:49:15] [XXXXX]  Unfollowing the users you are following
INFO [2019-01-26 11:56:58] [XXXXX]  Total 0 users available to unfollow  ~not found in 'followedPool.csv': 0  |  didn't pass `unfollow_after`: 504
INFO [2019-01-26 11:56:58] [XXXXX]  There are no any users to unfollow
INFO [2019-01-26 11:56:58] [XXXXX]  --> Total people unfollowed : 0
INFO [2019-01-26 11:57:01] [XXXXX]  Sessional Live Report:
        |> No any statistics to show
On session start was FOLLOWING 3549 users & had 4684 FOLLOWERS
[Session lasted 36.36 minutes]
## Comments:
Shouldn't my XXXXX_followedPool.csv have more than 1840 lines (following) if I'm at 3549?
Can someone please test?
With only "Gathered total of 968 unique active followers from the latest 3 posts in 15 minutes and 42 seconds" I should have a few thousands available to remove.

**Comment by miromannino** [comment]
I submitted a change on this, it would be awesome to have that because it can partially solve this problem too by saving likers. Please comment pull #3836 so we better hope to get this functionality in the code
