### ISSUE TITLE
Error install setup.py on windows

### ISSUE THREAD

**Issue by DemOnJR** [InstaPy/InstaPy#3844]
I recive this error: Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status -1073741701 when i try to install the setup.py this is the tutorial https://youtu.be/AOUraeus-XA?t=157

full install error list:

PS C:\Users\bogda\Documents\GitHub\InstaPy> python setup.py install
D:\Program Files\Python\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing instagram_py.egg-info\PKG-INFO
writing dependency_links to instagram_py.egg-info\dependency_links.txt
writing requirements to instagram_py.egg-info\requires.txt
writing top-level names to instagram_py.egg-info\top_level.txt
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
reading manifest file 'instagram_py.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'db'
writing manifest file 'instagram_py.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
file i.py (for module i) not found
file n.py (for module n) not found
file s.py (for module s) not found
file t.py (for module t) not found
file a.py (for module a) not found
file p.py (for module p) not found
file y.py (for module y) not found
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\browser.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\clarifai_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\commenters_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\comment_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\database_engine.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\feed_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\instapy.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\like_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\login_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\monkey_patcher.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\print_log_writer.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\quota_supervisor.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\relationship_tools.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\settings.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\text_analytics.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\time_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\unfollow_util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\util.py -> build\bdist.win-amd64\egg\instapy
copying build\lib\instapy\__init__.py -> build\bdist.win-amd64\egg\instapy
byte-compiling build\bdist.win-amd64\egg\instapy\browser.py to browser.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\clarifai_util.py to clarifai_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\commenters_util.py to commenters_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\comment_util.py to comment_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\database_engine.py to database_engine.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\feed_util.py to feed_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\instapy.py to instapy.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\like_util.py to like_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\login_util.py to login_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\monkey_patcher.py to monkey_patcher.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\print_log_writer.py to print_log_writer.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\quota_supervisor.py to quota_supervisor.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\relationship_tools.py to relationship_tools.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\settings.py to settings.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\text_analytics.py to text_analytics.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\time_util.py to time_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\unfollow_util.py to unfollow_util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\util.py to util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\instapy\__init__.py to __init__.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying instagram_py.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying instagram_py.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying instagram_py.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying instagram_py.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying instagram_py.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
instapy.__pycache__.settings.cpython-36: module references __file__
creating 'dist\instagram_py-0.0.1-py3.6.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing instagram_py-0.0.1-py3.6.egg
removing 'd:\program files\python\lib\site-packages\instagram_py-0.0.1-py3.6.egg' (and everything under it)
creating d:\program files\python\lib\site-packages\instagram_py-0.0.1-py3.6.egg
Extracting instagram_py-0.0.1-py3.6.egg to d:\program files\python\lib\site-packages
instagram-py 0.0.1 is already the active version in easy-install.pth

Installed d:\program files\python\lib\site-packages\instagram_py-0.0.1-py3.6.egg
Processing dependencies for instagram-py==0.0.1
Searching for regex>=2018.11.22
Reading https://pypi.python.org/simple/regex/
Downloading https://files.pythonhosted.org/packages/aa/eb/8a56aaf3a0a2a70cf2e017a8fb1ac5b6bad64a143d3096b0c0282b17ead1/regex-2019.01.24.tar.gz#sha256=20b1601b887e1073805adda2f8a09bb4c86dc7629c46c0d7bf28444dcb32920d
Best match: regex 2019.1.24
Processing regex-2019.01.24.tar.gz
Writing D:\CACHE\TEMP\easy_install-gohux1pd\regex-2019.01.24\setup.cfg
Running regex-2019.01.24\setup.py -q bdist_egg --dist-dir D:\CACHE\TEMP\easy_install-gohux1pd\regex-2019.01.24\egg-dist-tmp-5znelqp0
D:\Program Files\Python\lib\site-packages\setuptools\dist.py:331: UserWarning: Normalizing '2019.01.24' to '2019.1.24'
  normalized_version,
error: Setup script exited with error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status -1073741701
PS C:\Users\bogda\Documents\GitHub\InstaPy>

**Comment by tE3m** [comment]
That tutorial seems to be old. Use either 
```
pip install .
```
Or 
```
pip install -r requirements.txt
```
