### ISSUE TITLE
I

### ISSUE THREAD

**Issue by ishandutta2007** [InstaPy/InstaPy#3845]
R

**Comment by sionking** [comment]
You don't know how detectable this chrome browser is even using proxy can detect real pc ip.
You should use many JS scripts to fail most detectable shits.

**Comment by sionking** [comment]
you can try manually login and register to clarifai.com and stubhub.com
If no captch - you are safe, they all use the same company to detect selenium and chtromedriver.

**Comment by ishandutta2007** [comment]
@sionking yes they all use the same conpany, I heard an interview of the founder too. Can't reall the name. Sites like gleam.io is using inhouse fraud detection to detect selenium. But Nothing concrete exists in opensource to counter apart from few answers on stackoverflow. Let's take baby steps in opensource too to create undetectable webdriver binaries.

As far as instagram is concerned I guess instagram kind of knows people use selenium and they are kind of okay with it provided you remain within limits.

**Comment by sionking** [comment]
I don't think they are ok with this.
Try using datacenter proxies, you can't.
