### ISSUE TITLE
Follow private accounts

### ISSUE THREAD

**Issue by serhatavcu** [InstaPy/InstaPy#3847]
Hello,
i am a new user,
how set for follow private accounts ?

**Comment by Herrox** [comment]
Hi @serquat,

Have you try with `set_skip_users(skip_private=True, private_percentage=0)` or `set_skip_users(skip_private=False)` ?

Regards,
Herrox

**Comment by serhatavcu** [comment]
> Hi @serquat,
> 
> Have you try with `set_skip_users(skip_private=True, private_percentage=0)` or `set_skip_users(skip_private=False)` ?
> 
> Regards,
> Herrox

@Herrox 
```
Traceback (most recent call last):
  File "C:\Users\Serquat\Desktop\InstaPy\basic_follow-unfollow_activity.py", line 47, in <module>
    set_skip_users(skip_private=True, private_percentage=0)
NameError: name 'set_skip_users' is not defined
```

`Traceback (most recent call last):
  File "C:\Users\Serhat\Desktop\InstaPy\basic_follow-unfollow_activity.py", line 47, in <module>
    set_skip_users(skip_private=False)
NameError: name 'set_skip_users' is not defined`

**Comment by serhatavcu** [comment]
i am using this settings
`session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                               
                                  delimit_by_numbers=True,
                                    max_followers=15000,
                                    min_followers=35,
                                    min_following=60)

    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])
    set_skip_users(skip_private=False)
    

    # activities
`

**Comment by ugurozturk** [comment]
@serquat probabby it should be session.set_skip_users

**Comment by serhatavcu** [comment]
`session.set_skip_users(skip_private=False)` works fine  thanks @ugurozturk @Herrox

**Comment by ugurozturk** [comment]
@serquat perhaps you can close this issue
