### ISSUE TITLE
Blacklist strange behavior

### ISSUE THREAD

**Issue by Herrox** [InstaPy/InstaPy#3849]
## Expected Behavior
Hello,

I'm using `follow_likers` with `interact=True` (cf full InstaPy's configuration below)  and if I use `set_blacklist` I expect users are added **after** interactions (at the end of all interactions: like, comment...)

## Current Behavior
No interaction are made with users because user, that just have been followed is added to the blacklist and considered  as not a valid user:

> INFO [2019-01-29 14:19:25] [xxx]  User: 'user1'  |> followers: x  |> following: x  |> relationship ratio: x 
> INFO [2019-01-29 14:19:27] [xxx]  --> Followed 'b'user1''! 
> INFO [2019-01-29 14:19:27] [xxx]  --> user1 added to blacklist for myblacklist campaign (action: followed) 
> 
> ____________________________________________________________________ 
> INFO [2019-01-29 14:19:31] [xxx]  Starting to interact by users..
> """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> INFO [2019-01-29 14:19:31] [xxx]  Username [1/1]
> INFO [2019-01-29 14:19:31] [xxx]  --> b'user1'
> INFO [2019-01-29 14:19:31] [xxx]  Username in BlackList: user1  
> INFO [2019-01-29 14:19:31] [xxx]  --> not a valid user: ---> user1 is in blacklist  ~skipping user
> 
> INFO [2019-01-29 14:19:32] [xxx]  Total Follow: 1 
## InstaPy configuration

> bot.set_blacklist(enabled=True, campaign='myblacklist')
> bot.set_relationship_bounds(enabled=True, potency_ratio=0, delimit_by_numbers=True, max_followers=xxx, max_following=xxx, min_followers=xxx, min_following=xxx)
> bot.set_user_interact(amount=4, randomize=True, percentage=100, media='Photo')
> bot.set_do_follow(enabled=True, percentage=75)
> bot.set_do_like(enabled=True, percentage=100)
> bot.set_simulation(enabled=True, percentage=100)
> bot.set_do_comment(enabled=False, percentage=0)
> bot.follow_likers (['user'], photos_grab_amount=2, follow_likers_per_photo=15, randomize=True, sleep_delay=100, interact=True)

**Comment by traincodesleep** [comment]
see #3805 and #3804.
If you would like to fix this, your hands are going to have to get dirty and change InstaPy's code.
You'll need to disable the blacklist validation for the interaction part of the routine.

If you take a look at `follow_likers` it eventually makes use of `follow_by_list` which suffers from the same logical bug mentioned in #3804 in which the method validates a user, performs some action(like/comment/follow/etc), adds the user to the blacklist, then calls `interact_by_users` to do the interaction which validates the user again, which by now exists in the blacklist and is considered inappropriate.

So the routine `follow_likers` goes like this when interaction is turned on:
`follow_likers` > `follow_by_list` > `interact_by_users`.

I recently noticed in the code of Instapy there is a context manager
`@contextmanager
    def feature_in_feature(self, feature, validate_users):
        """
         Use once a host feature calls a guest
        feature WHERE guest needs special behaviour(s)
        """`

an example of this being used is 
` with self.feature_in_feature("interact_by_users", True):
                        self.interact_by_users(per_post_interacted_commenters,
                                               self.user_interact_amount,
                                               self.user_interact_random,
                                               self.user_interact_media)`

which I found in the `interact_by_comments` method. So you're going to look for 
`self.interact_by_users(per_post_interacted_commenters,
                                               self.user_interact_amount,
                                               self.user_interact_random,
                                               self.user_interact_media)`

in the `follow_by_list` method in InstaPy.py and add
`with self.feature_in_feature("interact_by_users", True):` giving you the same block of code I included as an example. This should fix your issue. Let me know as I haven't tested this yet as I found it while answering your issue.

My guess is that similar code was left out in the `like_by_tags` and follow_likers` and probably a couple others I haven't come across yet.

**Comment by Herrox** [comment]
@emmanuelclarke Not sure to fully understand what to change/add, so I'll have a look to #3804 and #3805 
If you know how to fix the issue, could you please create a PR?

For me, the `blacklist` function is one of the most important to make InstaPy more accurate, less detectable and more efficient.
@timgrossmann

**Comment by Herrox** [comment]
@emmanuelclarke I just added a comment to your PR that should fix this issue but not sure if you will see it, so posting it here too:

---

Not sure if this PR is really working as expected.
In the logs of `InstaPy` I see something like `follower1 added to blacklist for mybalcklist campaign (action: followed)` but when I grep in the log files (especially in `blacklist.csv`) there is no such `follower1`. Moreover, `backlist.csv` file has not been modified since a while.

How may I help you guys fixing the issue ?

**Comment by Herrox** [comment]
@emmanuelclarke Thanks to your PR, this issue seems partly solved and now a user could be `followed` and `liked` at the same interactions. But it seems users are still not added to the `blacklist.csv` file. This file hasn't be modified
