### ISSUE TITLE
Failed to load desired amount of users!

### ISSUE THREAD

**Issue by EvraCloak** [InstaPy/InstaPy#3851]
...............................................................
INFO [2019-01-29 18:27:41] [kblycolak]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-01-29 18:27:41] [kblycolak]  Saving account progress...

_____________________________________________________________________________
INFO [2019-01-29 18:27:45] [kblycolak]  Starting to follow user `Following`..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-01-29 18:27:45] [kblycolak]  User 'berkayyokur' [1/1]
INFO [2019-01-29 18:28:01] [kblycolak]  Failed to load desired amount of users!

INFO [2019-01-29 18:28:53] [kblycolak]  Grabbed 21 usernames from 'berkayyokur's `Following` to do following

INFO [2019-01-29 18:28:53] [kblycolak]  Ongoing Follow [1/21]: now following 'melisauyyarr'...
INFO [2019-01-29 18:28:55] [kblycolak]  User: 'melisauyyarr'  |> followers: 114  |> following: 161  |> relationship ratio: 0.7
INFO [2019-01-29 18:28:55] [kblycolak]  User 'melisauyyarr's followers count is less than minimum limit  ~skipping user

INFO [2019-01-29 18:28:55] [kblycolak]  Ongoing Follow [2/21]: now following 'basakpelitci'...
INFO [2019-01-29 18:28:58] [kblycolak]  User: 'basakpelitci'  |> followers: 467  |> following: 218  |> relationship ratio: 2.14
INFO [2019-01-29 18:28:58] [kblycolak]  basakpelitci is private account, by default skip

INFO [2019-01-29 18:28:58] [kblycolak]  Ongoing Follow [3/21]: now following 'aleynaodabas_'...
INFO [2019-01-29 18:29:00] [kblycolak]  User: 'aleynaodabas_'  |> followers: 796  |> following: 164  |> relationship ratio: 4.85
INFO [2019-01-29 18:29:00] [kblycolak]  aleynaodabas_ is private account, by default skip

INFO [2019-01-29 18:29:00] [kblycolak]  Ongoing Follow [4/21]: now following 'sadiyeesemen'...
INFO [2019-01-29 18:29:03] [kblycolak]  User: 'sadiyeesemen'  |> followers: 593  |> following: 108  |> relationship ratio: 5.49
INFO [2019-01-29 18:29:03] [kblycolak]  sadiyeesemen is private account, by default skip

INFO [2019-01-29 18:29:03] [kblycolak]  Ongoing Follow [5/21]: now following 'deardaena'...
INFO [2019-01-29 18:29:06] [kblycolak]  User: 'deardaena'  |> followers: 329  |> following: 253  |> relationship ratio: 1.3
INFO [2019-01-29 18:29:06] [kblycolak]  deardaena is private account, by default skip

INFO [2019-01-29 18:29:06] [kblycolak]  Ongoing Follow [6/21]: now following 'ggamzegguler'...
INFO [2019-01-29 18:29:09] [kblycolak]  User: 'ggamzegguler'  |> followers: 1049  |> following: 371  |> relationship ratio: 2.82
INFO [2019-01-29 18:29:09] [kblycolak]  ggamzegguler is private account, by default skip

INFO [2019-01-29 18:29:09] [kblycolak]  Ongoing Follow [7/21]: now following 'helinfdnys'...
INFO [2019-01-29 18:29:12] [kblycolak]  User: 'helinfdnys'  |> followers: 816  |> following: 295  |> relationship ratio: 2.76
INFO [2019-01-29 18:29:12] [kblycolak]  helinfdnys is private account, by default skip

INFO [2019-01-29 18:29:12] [kblycolak]  Ongoing Follow [8/21]: now following 'gulshdrgn'...
INFO [2019-01-29 18:29:16] [kblycolak]  User: 'gulshdrgn'  |> followers: 2505  |> following: 763  |> relationship ratio: 3.28
INFO [2019-01-29 18:29:16] [kblycolak]  gulshdrgn is private account, by default skip

INFO [2019-01-29 18:29:16] [kblycolak]  Ongoing Follow [9/21]: now following 'gulten.cgr'...
INFO [2019-01-29 18:29:19] [kblycolak]  User: 'gulten.cgr'  |> followers: 1150  |> following: 124  |> relationship ratio: 9.27
INFO [2019-01-29 18:29:25] [kblycolak]  --> Followed 'b'gulten.cgr''!
INFO [2019-01-29 18:29:34] [kblycolak]  Follow per user: 1  |  Total Follow: 1

INFO [2019-01-29 18:29:34] [kblycolak]  Ongoing Follow [10/21]: now following 'solmazzpel'...
[900:7320:0129/182934.205:ERROR:latency_info.cc(144)] Display::DrawAndSwap, LatencyInfo vector size 102 is too big.
INFO [2019-01-29 18:29:36] [kblycolak]  User: 'solmazzpel'  |> followers: 497  |> following: 375  |> relationship ratio: 1.32
INFO [2019-01-29 18:29:36] [kblycolak]  solmazzpel is private account, by default skip

INFO [2019-01-29 18:29:36] [kblycolak]  Ongoing Follow [11/21]: now following 'didarkeless'...
INFO [2019-01-29 18:29:39] [kblycolak]  User: 'didarkeless'  |> followers: 872  |> following: 431  |> relationship ratio: 2.02
INFO [2019-01-29 18:29:39] [kblycolak]  didarkeless is private account, by default skip

INFO [2019-01-29 18:29:39] [kblycolak]  Ongoing Follow [12/21]: now following 'mehmetcandrd'...
INFO [2019-01-29 18:29:42] [kblycolak]  User: 'mehmetcandrd'  |> followers: 29  |> following: 44  |> relationship ratio: 0.65
INFO [2019-01-29 18:29:42] [kblycolak]  User 'mehmetcandrd's followers count is less than minimum limit  ~skipping user

INFO [2019-01-29 18:29:42] [kblycolak]  Ongoing Follow [13/21]: now following 'mehmetcandrd'...
INFO [2019-01-29 18:29:42] [kblycolak]  User: 'mehmetcandrd'  |> followers: 29  |> following: 44  |> relationship ratio: 0.65
INFO [2019-01-29 18:29:42] [kblycolak]  User 'mehmetcandrd's followers count is less than minimum limit  ~skipping user

INFO [2019-01-29 18:29:42] [kblycolak]  Ongoing Follow [14/21]: now following 'mehmetcandrd'...
INFO [2019-01-29 18:29:42] [kblycolak]  User: 'mehmetcandrd'  |> followers: 29  |> following: 44  |> relationship ratio: 0.65
INFO [2019-01-29 18:29:42] [kblycolak]  User 'mehmetcandrd's followers count is less than minimum limit  ~skipping user

INFO [2019-01-29 18:29:42] [kblycolak]  Ongoing Follow [15/21]: now following 'mehmetcandrd'...
INFO [2019-01-29 18:29:42] [kblycolak]  User: 'mehmetcandrd'  |> followers: 29  |> following: 44  |> relationship ratio: 0.65
INFO [2019-01-29 18:29:42] [kblycolak]  User 'mehmetcandrd's followers count is less than minimum limit  ~skipping user

INFO [2019-01-29 18:29:42] [kblycolak]  Ongoing Follow [16/21]: now following 'mehmetcandrd'...
INFO [2019-01-29 18:29:42] [kblycolak]  User: 'mehmetcandrd'  |> followers: 29  |> following: 44  |> relationship ratio: 0.65
INFO [2019-01-29 18:29:42] [kblycolak]  User 'mehmetcandrd's followers count is less than minimum limit  ~skipping user

INFO [2019-01-29 18:29:42] [kblycolak]  Ongoing Follow [17/21]: now following 'mehmetcandrd'...
INFO [2019-01-29 18:29:42] [kblycolak]  User: 'mehmetcandrd'  |> followers: 29  |> following: 44  |> relationship ratio: 0.65
INFO [2019-01-29 18:29:42] [kblycolak]  User 'mehmetcandrd's followers count is less than minimum limit  ~skipping user

INFO [2019-01-29 18:29:42] [kblycolak]  Ongoing Follow [18/21]: now following 'mehmetcandrd'...
INFO [2019-01-29 18:29:42] [kblycolak]  User: 'mehmetcandrd'  |> followers: 29  |> following: 44  |> relationship ratio: 0.65
INFO [2019-01-29 18:29:42] [kblycolak]  User 'mehmetcandrd's followers count is less than minimum limit  ~skipping user

INFO [2019-01-29 18:29:42] [kblycolak]  Ongoing Follow [19/21]: now following 'mehmetcandrd'...
INFO [2019-01-29 18:29:42] [kblycolak]  User: 'mehmetcandrd'  |> followers: 29  |> following: 44  |> relationship ratio: 0.65
INFO [2019-01-29 18:29:42] [kblycolak]  User 'mehmetcandrd's followers count is less than minimum limit  ~skipping user

INFO [2019-01-29 18:29:42] [kblycolak]  Ongoing Follow [20/21]: now following 'mehmetcandrd'...
INFO [2019-01-29 18:29:42] [kblycolak]  User: 'mehmetcandrd'  |> followers: 29  |> following: 44  |> relationship ratio: 0.65
INFO [2019-01-29 18:29:42] [kblycolak]  User 'mehmetcandrd's followers count is less than minimum limit  ~skipping user

INFO [2019-01-29 18:29:42] [kblycolak]  Ongoing Follow [21/21]: now following 'mehmetcandrd'...
INFO [2019-01-29 18:29:42] [kblycolak]  User: 'mehmetcandrd'  |> followers: 29  |> following: 44  |> relationship ratio: 0.65
INFO [2019-01-29 18:29:42] [kblycolak]  User 'mehmetcandrd's followers count is less than minimum limit  ~skipping user

INFO [2019-01-29 18:29:42] [kblycolak]  Finished following 1 users' `Following`! xD

INFO [2019-01-29 18:29:42] [kblycolak]  Followed: 1
INFO [2019-01-29 18:29:42] [kblycolak]  Already followed: 0
INFO [2019-01-29 18:29:42] [kblycolak]  Not valid users: 20

INFO [2019-01-29 18:29:45] [kblycolak]  Sessional Live Report:
        |> LIKED 0 images  |  ALREADY LIKED: 0
        |> COMMENTED on 0 images
        |> FOLLOWED 1 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> LIKED 0 comments
        |> REPLIED to 0 comments
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 20

On session start was FOLLOWING 2849 users & had 2983 FOLLOWERS
[Session lasted 2.39 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-01-29 18:29:45] [kblycolak]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

I DOWNLOADED ACTUAL GIT CLONE AND I TOOK THIS ERROR. AGAIN !

**Comment by notahooper15** [comment]
Been having similar issue....

**Comment by henry0666** [comment]
same

**Comment by Kevdome3000** [comment]
Same here

**Comment by Cokpan** [comment]
+1

**Comment by Ualas** [comment]
Same

**Comment by ghost** [comment]
+1
