### ISSUE TITLE
W

### ISSUE THREAD

**Issue by ishandutta2007** [InstaPy/InstaPy#3854]
I

**Comment by xerZV** [comment]
..............

**Comment by kev-mas** [comment]
@ishandutta

> Rate Limiting
> 
> The Instagram API uses the same rate limiting as the Graph API (200 calls per user per hour) with one exception: the /media/comments edge limits writes to 60 writes per user per hour. Please refer to the Graph API's rate limiting documentation for more information.

`https://developers.facebook.com/docs/instagram-api/overview/#rate-limiting
`

**Comment by kalebic** [comment]
Has there been any update on this? My server calls seem excessive as well.

**Comment by plastikmind** [comment]
### Real Limit.
peak_server_calls=(200, 4800)   

### I use this.
peak_server_calls=(195, 4700)

**Comment by Julianxo** [comment]
@LunaticZorr
> https://developers.facebook.com/docs/instagram-api/overview/#rate-limiting

I guess that's not the same api. As far as I now instapy is using the inofficial api, Instagrams frontend is using. I am pretty sure that they do not use instagrams Graph API.
Please correct me if I am wrong.
