### ISSUE TITLE
How to unfollow users that were NOT followed by InstaPy

### ISSUE THREAD

**Issue by sillyonthestreet** [InstaPy/InstaPy#3859]
I have more than 5000 followed users that I've manually followed through the years.

How do I unfollow them using InstaPy? When I use session.unfollow_users it says the follower pool is empty.

**Comment by SiRaZz** [comment]
Because instaPy saves followed users in file yourUserName_followedPool.csv. In your case you havent followed any users using Instapy?? You can try extract all users you are following and and use it as list for function unfollow_users

**Comment by Tr1pke** [comment]
Try this one

    session.unfollow_users(amount=200, InstapyFollowed=(False), style="RANDOM", sleep_delay=666)
