### ISSUE TITLE
Strange issue (not a duplicate)

### ISSUE THREAD

**Issue by vomblyat** [InstaPy/InstaPy#386]
Hi - I opened an issue a few days ago which was incorrectly closed for being a duplicate (somebody else referenced their problem in a reply, but we don't appear to be having the same error). 

Currently, when I run the script I get the first two lines of the following output (that is, both lines which end with "line 477". When I close the chrome window which the script opened up, the rest of the lines appear. I haven't been able to find any useful information about what those first two error lines are telling me on Google. Any help would be appreciated! 
![error1](https://user-images.githubusercontent.com/29987799/28023568-419c390c-655c-11e7-9377-442766e06a41.png)

**Comment by anton-shablyko** [comment]
After a quick google search, it looks like you have issues with rendering page in your web browser.
try:
1. Download fresh version of the [chromedriver ](https://chromedriver.storage.googleapis.com/index.html?path=2.30/) and put it in './assets/chromedriver'
2. Update drivers for your video card

**Comment by TheXeon81** [comment]
i have some problem... https://github.com/timgrossmann/InstaPy/issues/388
but not work...


3 PC... Same mistake ... :-(

**Comment by timgrossmann** [comment]
@vomblyat Make sure that your device got enough RAM, at least 1GB is needed.

**Comment by vomblyat** [comment]
I tried downloading a fresh version of chromedriver and updating drivers (which were apparently already up-to-date). My device also does have enough RAM. Somehow, I'm still getting the same error - any insight anyone has would be appreciated!

**Comment by timgrossmann** [comment]
@vomblyat Could you please paste your quickstart.py content?

**Comment by vomblyat** [comment]
from instapy import InstaPy





```python
import os
session = InstaPy(username='[redacted]', password='[redacted]')
session.login()
session.set_do_comment(enabled=True, percentage=25)
session.set_comments(['cool!', 'nice!' ])
session.set_do_follow(enabled=True, percentage=10, times=1)
session.set_lower_follower_count(limit = 0)
session.like_by_tags(['yoga', 'meditation'], amount=50)

session.end()

**Comment by timgrossmann** [comment]
Could you please try to [run with new docker micro services](https://github.com/timgrossmann/InstaPy#running-with-docker-microservices-manual).
