### ISSUE TITLE
Unfollowing users that shouldn't be unfollowed

### ISSUE THREAD

**Issue by AnwarAhmedPSU** [InstaPy/InstaPy#3862]
## Expected Behavior
It's unfollowing people that follow me back, why is that?
This is the line I'm using
"session.unfollow_users(amount=800, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=240)"

## Current Behavior
It's unfollowing people that follow me back
 Are others receiving this issue as well?

**Comment by Tr1pke** [comment]
session.unfollow_users(amount=200, InstapyFollowed=(True, "nonfollowers"), style="RANDOM", unfollow_after=29*60*60, sleep_delay=666)

**Comment by ishandutta2007** [comment]
Do you have simulation enabled, it can be because of that?
Check if you have written anything like this:
`session.set_simulation(enabled=True)`
