### ISSUE TITLE
Issue: NameError: name 'comment_image' is not defined

### ISSUE THREAD

**Issue by MSThedox** [InstaPy/InstaPy#3867]
##Hi, I found this error:

Traceback (most recent call last):
  File "C:\Users\Armaury\Documents\GitHub\InstaPy\test-quickstart.py", line 38,
in <module>
    amount=8000, randomize=True)
  File "C:\Users\Armaury\Documents\GitHub\InstaPy\instapy\instapy.py", line 2798
, in interact_user_followers
    self.user_interact_media)
  File "C:\Users\Armaury\Documents\GitHub\InstaPy\instapy\instapy.py", line 2253
, in interact_by_users
    comment_state, msg = comment_image(
NameError: name 'comment_image' is not defined

##This is what I put in the quickstart.py:

from instapy import InstaPy
from instapy.util import smart_run

# get a session!
session = InstaPy(username='///', password='///')

# let's go! :>
with smart_run(session):
    # general settings

    session.set_relationship_bounds(enabled=True,
    delimit_by_numbers=False, max_followers=12000, max_following=4500,
    min_followers=35, min_following=35)
    session.set_user_interact(amount=2, randomize=True, percentage=100,
    media='Photo')
    session.set_do_follow(enabled=True, percentage=100)
    session.set_do_like(enabled=True, percentage=100)
    session.set_comments(["Cool","Super!",'Amazing!','Awesome!!',u'Cool!💯',
                            'Good one!',u"🔥🔥🔥",u"Fire 🔥🔥🔥",u"👌",u"💯💯"
                            'Really good one','Love this!',u'Dope 🔥',
                            'Beautiful!','Great!',u"Wow 👌"])
    session.set_do_comment(enabled=True, percentage=50)
    session.set_user_interact(amount=2, randomize=True, percentage=100,
    media='Photo')

    # activity

    session.interact_user_followers(['marchenoirltd', 'aaucarre', 'mnml.la'],
    amount=8000, randomize=True)
    session.follow_user_followers(['marchenoirltd', 'aaucarre', 'mnml.la'],
    amount=8000, randomize=True, interact=True)
    session.unfollow_users(amount=7500, nonFollowers=True, style="RANDOM",
    unfollow_after=42*60*60, sleep_delay=3)
    session.like_by_tags(['hypebeast'], amount=8000)

If anyone can help I'll be really thankfull

**Comment by ishandutta2007** [comment]
Did you try a simple text comments list removing all the emojis?
I guess in code you have to write the text equivalent of emojis ie `:fire` instead of `🔥`

**Comment by MSThedox** [comment]
Yes I tried simple text like "Cool","Super!", but It stops with the same error unfortunately

**Comment by ishandutta2007** [comment]
which is  line 38 ?
are you are marketer or programmer ?

**Comment by MSThedox** [comment]
Line 38 is: 
session.interact_user_followers(['///', '///', '///'], amount=8000, randomize=True)

I am a marketer

**Comment by ishandutta2007** [comment]
> I am a marketer

As I guessed, comment out all other lines and run only that line, or take help of a programmer in person if you have one around you.

or better if you start with a template , here is one similar to your needs, https://github.com/timgrossmann/InstaPy/blob/04741a6431c05b5f74144e0bd8e5483fdcc47cd8/quickstart_templates/simple_interaction_good_for_beginners.py
Just plug in your users.

For a marketer debugging even a small issues might be a big headache, so start small.
