### ISSUE TITLE
M

### ISSUE THREAD

**Issue by ishandutta2007** [InstaPy/InstaPy#3868]
L

**Comment by austinemayer** [comment]
I believe these are known as pods and I think it would work great if the genres are the same but you might end up getting the wrong engagement that you were looking for, but thats just my opinion.

**Comment by ishandutta2007** [comment]
yes it would be great if you could track genres and engage likewise. Most `bots as a service` engage all of their clients among each other, once you have a greater userbase you can definitely prioritize based on genre. We can start small and figure out how many people are running `InstaPy` keeping trending/pods flag enabled and decide on the enhancement as you suggested.

Second option is to access and automate any open pod via bot, let us know if you have list of open pods for instagram. 
The risk with open pods is if pods are groups on the same platform then they scrutinize and remove those from time to time, I read of facebook groups being removed which served as pods, I guess it would be same for instagram.
