### ISSUE TITLE
installtion error

### ISSUE THREAD

**Issue by drcyber975** [InstaPy/InstaPy#3869]
I installed all the dependencies for the instapy but i believe their may be some missing. 

When i run "python quickstart.py" i get this error message

python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/home/cypher/Documents/Instapy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/cypher/Documents/Instapy/instapy/instapy.py", line 21, in <module>
    from .clarifai_util import check_image
  File "/home/cypher/Documents/Instapy/instapy/clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp
  File "/usr/local/lib/python2.7/dist-packages/clarifai-2.5.2-py2.7.egg/clarifai/rest/__init__.py", line 3, in <module>
    from clarifai.rest.client import ApiClient
  File "/usr/local/lib/python2.7/dist-packages/clarifai-2.5.2-py2.7.egg/clarifai/rest/client.py", line 14, in <module>
    from configparser import ConfigParser
  File "/usr/local/lib/python2.7/dist-packages/configparser-3.7.1-py2.7.egg/configparser.py", line 12, in <module>
    from backports.configparser import (
ImportError: cannot import name ConverterMapping

how do i fix this problem? 
I am trying to install Instapy on ubuntu

**Comment by tE3m** [comment]
Maybe try using python3?

**Comment by drcyber975** [comment]
I tried using python3 i am still receiving an error.

 python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/home/cypher/Documents/Instapy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/cypher/Documents/Instapy/instapy/instapy.py", line 22, in <module>
    from .comment_util import comment_image
  File "/home/cypher/Documents/Instapy/instapy/comment_util.py", line 8, in <module>
    from .util import update_activity
  File "/home/cypher/Documents/Instapy/instapy/util.py", line 7, in <module>
    import regex
ModuleNotFoundError: No module named 'regex'

what is my issue now?

**Comment by ishandutta2007** [comment]
install those dependancies as suggested, for me also(on mac high sierra and python 3.60) the dependancies in `requirements.txt` didn't suffice, I had to install a few outside that.

**Comment by drcyber975** [comment]
Do you know what I need to install by looking at this error message?


Sent from Yahoo Mail for iPhone


On Friday, February 1, 2019, 6:52 PM, ishan dutta <notifications@github.com> wrote:


install those dependancies as suggested, for me also(on mac) the dependancies in requirements.txt didn't suffice, I had to install a few outside that.

**Comment by ishandutta2007** [comment]
@drcyber975 https://github.com/timgrossmann/InstaPy/issues/3449

**Comment by tE3m** [comment]
If you haven't already, run 
```
python3 -m pip install .
```
In the InstaPy folder first, and then install what's missing. You probably installed all the packages for python2.7, but that doesn't install them for python3.

**Comment by drcyber975** [comment]
After running python3 -m pip install in the Instapy folder I received this error message
“ERROR: you must give at least one requirement to install (see pip help install)”
I tried the same command with Sudo at the start but made no difference. What do you recommend that I do now?


Sent from Yahoo Mail for iPhone


On Saturday, February 2, 2019, 2:27 AM, TarekJ03 <notifications@github.com> wrote:


If you didn't already run
python3 -m pip install .

In the InstaPy folder first, and then install what's missing. You probably installed all the packages for python2.7, but that doesn't install them for python3.

**Comment by tE3m** [comment]
That was no typo 😄 I really meant

```
python3 -m pip install .
```

The . at the end was not a mistake

**Comment by drcyber975** [comment]
Oh okay I was missing the dot hahaha I will try again now and let you know the results. By the way I just set up the script on my Windows machine and it’s working!!! I want to be able to set up on Ubuntu to!


Sent from Yahoo Mail for iPhone


On Saturday, February 2, 2019, 12:30 PM, TarekJ03 <notifications@github.com> wrote:


That was no typo 😄 I really meant

python3 -m pip install .

The . at the end was not a mistake

**Comment by matej2** [comment]
When i run `python3 -m pip install .` i am getting: 

> /usr/bin/python3: No module named pip

**Comment by codewithdripzy** [comment]
i also have his issue i've tried following the link you posted but it is redirecting me to a 404 page

**Comment by codewithdripzy** [comment]
i also have his issue i've tried following the link you posted but it is redirecting me to a 404 page
