### ISSUE TITLE
Like by feed not working if window is minimized

### ISSUE THREAD

**Issue by datteba** [InstaPy/InstaPy#387]
Hi!
If browser is minimized the like by feed is not working. It continues to show: "Total Likes uptil now..."

![likebyfeed](https://user-images.githubusercontent.com/30053143/28029801-93432956-65a1-11e7-9c5a-0e177470be0e.png)

**Comment by timgrossmann** [comment]
@datteba The aggregation as it is right now doesn't work when minimised.
Please use a separate device or a virtual server like DigitalOcean if you need to work on your device.
