### ISSUE TITLE
Failed to load desired number of users for unfollowing 

### ISSUE THREAD

**Issue by alexmattson** [InstaPy/InstaPy#3870]
I am seeing unexpected behavior when running a simple unfollow script. The given account has around 2000 following. I run the following script:

```
InstaPy(username='********', password='********')\
    .login()\
    .unfollow_users(amount=400, allFollowing=True, style="RANDOM", sleep_delay=450)\
    .end()
```

and it will give an output like this:

```
INFO [2019-02-01 16:06:12] [********]  Unfollowing the users you are following
INFO [2019-02-01 16:06:25] [********]  Failed to load desired amount of users!
INFO [2019-02-01 16:06:29] [********]  Total 42 users available to unfollow  ~not found in 'followedPool.csv': 42  |  didn't pass `unfollow_after`: 0
INFO [2019-02-01 16:06:29] [********]  Could not grab requested amount of usernames to unfollow:  42/400  ~using available amount
INFO [2019-02-01 16:06:29] [********]  Ongoing Unfollow [1/42]: now unfollowing '********'...
```

Specs:
Instapy: recloned and reinstalled 
Python: 3.7.2

## Expected Behavior

Continues to build list of unfollowable users until limit is reached or list of following users is exhausted. 

## Current Behavior

Will load a small subset of the available unfollowable users. I've seen the following numbers loaded in my testing: 36, 42, 76, 240.

**Comment by Kevdome3000** [comment]
I've experienced the same

**Comment by silentwalk** [comment]
Same here seems like a problem with the scroll

**Comment by gitpatrickhub** [comment]
Same issue after latest merge.

**Comment by Tachenz** [comment]
Same issue here!
