### ISSUE TITLE
Unfollow

### ISSUE THREAD

**Issue by napoletanopasquale** [InstaPy/InstaPy#3873]
I need to create a list of my following that have the following requirements: number of following greater than the number of followers of at least 500 people. How can I do? My goal is to eliminate these people.

**Comment by napoletanopasquale** [comment]
I need to create a list of my following that have the following requirements: number of following greater than the number of followers of at least 500 people. How can I do? My goal is to eliminate these people.

**Comment by ishandutta2007** [comment]
read about potency_ratio
https://github.com/timgrossmann/InstaPy#interactions-based-on-the-number-of-followers-andor-following-a-user-has
