### ISSUE TITLE
`followers_link` error list index out of range - new issue as the old #2571 is closed with no explanation.....

### ISSUE THREAD

**Issue by doronshai** [InstaPy/InstaPy#3877]
## Expected Behavior

in my script i have these steps, based on the **_basic_follow-unfollow_activity.py_** template

session.follow_user_followers( ['Barzomer','The_romi_frenkel','Reefneeman'], amount=500, randomize=False, interact=False)

I expect it to go over the user followers as it usually do and follow them.

## Current Behavior

I get this error

ERROR [2019-02-01 21:16:36] []  `followers_link` error
INFO [2019-02-01 21:16:36] []  Grabbed 0 usernames from 'Barzomer's `Followers` to do following

**### _Looks like something in the instagram UI has changed....._**

My general settings in the script is currently empty. I am running on DigitalOcean ubuntu 16.

**Comment by doronshai** [comment]
This issue is not reproducing on all servers.
I think that the IP got blocked or something and therefore the HTML that is returned is not as expected.
Still I think that the error message should represent the real status. as now it is really not clear what is the issue.

**Comment by doronshai** [comment]
@uluQulu What do you say?

**Comment by uluQulu** [comment]
Hi @doronshai 

Open up **unfollow_util.py** file and then do this modification:
**replace**
```python
logger.error("`followers_link` error {}".format(str(e)))
```
**with**
```python
logger.error("`followers_link` error {}".format(str(e)))
raise
```

Then, show me the full [error] output [without personal info] after a crash.

---

Cheers 😁
---

**Comment by gan-mel** [comment]
Not sure what i'm doing wrong, but changes I make to unfollow_util just don't take affect (tried restarting the bot ofcourse) ,

I tried modifying both the files in build and in instaPy

**Comment by gan-mel** [comment]
I tried adding the "raise" but it seems like any change I make to the files are not taking affect when running the bot.

I use the template "target_followers_of_similar_accounts_and_influencers" .

What am I missing to be able and modify the code?

If someone else is able to do so - just use the template with the user "Barzomer" and you should be able to reproduce the issue.

**Comment by gan-mel** [comment]
> Hi @doronshai
> 
> Open up **unfollow_util.py** file and then do this modification:
> **replace**
> 
> ```python
> logger.error("`followers_link` error {}".format(str(e)))
> ```
> 
> **with**
> 
> ```python
> logger.error("`followers_link` error {}".format(str(e)))
> raise
> ```
> 
> Then, show me the full [error] output [without personal info] after a crash.
> 
> ## Cheers 😁

Here is the raised logs of the error:

INFO [2019-02-08 18:54:46] [XXXX]  User 'XXXX' [1/1]
ERROR [2019-02-08 18:55:14] [XXXX]  `followers_link` error list index out of range

INFO [2019-02-08 18:55:14] [XXXX]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 14 users & had 10 FOLLOWERS
[Session lasted 1.12 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-02-08 18:55:14] [XXXX]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "target_followers_of_similar_accounts_and_influencers.py", line 160, in <module>
    interact=True)
  File "/usr/local/lib/python3.7/site-packages/instagram_py-0.0.1-py3.7.egg/instapy/instapy.py", line 3053, in follow_user_followers
    self.logfolder)
  File "/usr/local/lib/python3.7/site-packages/instagram_py-0.0.1-py3.7.egg/instapy/unfollow_util.py", line 991, in get_given_user_followers
    click_element(browser, followers_link[0])
IndexError: list index out of range
xx-mac:quickstart_templates xx$

**Comment by gan-mel** [comment]
Okay that was so silly.. I found the issue -
the reason it doesn't work is that this link is case sensitive, if you put in "Barzomer" and it's actually
"barzomer" it will fail.

So you can fix it just by making sure any user name you put it will always be lower case:

from:    user_name = user_name.strip()
to: user_name = user_name.strip().lower()

i sent a pull request for it

**Comment by gan-mel** [comment]
@timgrossmann this one can probably be closed
