### ISSUE TITLE
Accounts being blocked in AWS

### ISSUE THREAD

**Issue by octavius-1** [InstaPy/InstaPy#3878]
I have some instances in AWS each one running two instapy services (one for each account), suddenly, all my accounts got -like blocked- when they were running ok for months. Could someone help providing which proxy provider do you use with the Best results? Or am I doing something wrong?

**Comment by joanroig** [comment]
Seems like there is a change in like limits or so, because some accounts are getting like-banned

**Comment by sionking** [comment]
daaa no data center in IG anymore

**Comment by octavius-1** [comment]
@sionking Could you please help with a solution for this? I have no idea of how to handle proxies within instapy. I mean, I don't know which service should I use.
