### ISSUE TITLE
not open chromedriver

### ISSUE THREAD

**Issue by TheXeon81** [InstaPy/InstaPy#388]
the script run... but not open chromedriver :-(

![image](https://user-images.githubusercontent.com/5238466/28034795-8dc48680-65b2-11e7-8603-fe9fd8224eea.png)

and after many time... i have this error:

![image](https://user-images.githubusercontent.com/5238466/28034838-aea50352-65b2-11e7-9a6b-59e0accee0c9.png)

Up to 2 days it worked all ... :-(

**Comment by anton-shablyko** [comment]
@TheXeon81 Your issue is different than [#386](https://github.com/timgrossmann/InstaPy/issues/386) .
You are getting 10054 Error(""). I don't have enough knowledge to suggest the solution, but it looks like you are getting a rejection from the remote server. Perhaps your IP got banned?
Can you log into Instagram manually?
Also, on the second screenshot Username and Password are listed as "test'. Can you double check that you are passing correct credentials, please?

**Comment by TheXeon81** [comment]
in chrome login and navigate on my instagram profile!
I changed my username and password to make screenshots

**Comment by timgrossmann** [comment]
@TheXeon81 
What is your process on executing the script?

You have to "move" to the InstaPy folder in your terminal and then simply do a `python3 quickstart.py` you don't need to do anything with the python REPL...

**Comment by TheXeon81** [comment]
i open my directory in c:\instapy and execute InstaPy-GUI

![image](https://user-images.githubusercontent.com/5238466/28076833-2e52caf0-6660-11e7-916d-3ff60147393e.png)

after i insert:

1. my username
2. my password
3. check following box
4. check unfollowing box
5. check like from tags
6. add the tags
7. check photo
8. check video
9. press run to execute!!!

![image](https://user-images.githubusercontent.com/5238466/28076988-9a574aaa-6660-11e7-87a7-5a9810a38e62.png)

when running open a command window...

![image](https://user-images.githubusercontent.com/5238466/28077020-c4493170-6660-11e7-85a1-df643a2e1d3f.png)

At this point it stops ...
Same problem on 3 pcs

pc1 = windows 10 creator update version
pc2 = windows 10
pc3 = windows 7

All the pc worked a few days ago

**Comment by onyxim** [comment]
Try to [run with new docker micro services](https://github.com/timgrossmann/InstaPy#running-with-docker-microservices-manual). It completely solves all chromedriver problems.

**Comment by TheXeon81** [comment]
@onyxim  ok!!! in a docker now works!!!!!
my question: ... but the sequence is not too fast ????
