### ISSUE TITLE
Unaccountable issue never seen before

### ISSUE THREAD

**Issue by henriquedevelops** [InstaPy/InstaPy#3880]
I run 3 accounts, the function like by tags simply stopped working in one of them. I didn't change the quickstart file, it suddenly stopped working with the exact the same code as before.
It opens the browser, logs into the account, opens the tag page, selects the image and then it closes the browser instead of liking the photo.
I've searched everywhere and tried everything. I tried even using the most simple code possible. I tried switching the credentials with the quickstart file from the other account that is still working. 

Can someone please help me?

**Comment by tE3m** [comment]
Did you fix it?

**Comment by henriquedevelops** [comment]
> Did you fix it?

I read on another topic that this issue was solved with the update. 

Sorry that I am such a newbie, but the thing is I don't know how to update it HAHAHA
I tried clicking on "Pull origin" on GitHub Desktop, but then an error message comes out:

"error: Your local changes to the following files would be overwritten by merge:
instapy/instapy.py
quickstart.py
Please commit your changes or stash them before you merge.
Aborting"

I'm using it on Windows 7.

**Comment by tE3m** [comment]
Rename your quickstart.py or unselect it under "changes" in GitHub Desktop. Then try again
