### ISSUE TITLE
selenium.common.exceptions.WebDriverException unknown error: Cannot read property 'edges' of undefined

### ISSUE THREAD

**Issue by FAD28** [InstaPy/InstaPy#3882]
Hello people, I have recently received this error. Does one know what I have to do to fix this?

> `Traceback (most recent call last):
>   File "/Users/user/Library/Preferences/PyCharmCE2018.3/scratches/Bot (justFollow).py", line 27, in <module>
>     session.follow_by_tags(['nature', 'geo'], amount=10)
>   File "/Users/user/PycharmProjects/instapy/venv/lib/python3.7/site-packages/instapy/instapy.py", line 3863, in follow_by_tags
>     self.logger)
>   File "/Users/user/PycharmProjects/instapy/venv/lib/python3.7/site-packages/instapy/like_util.py", line 479, in check_link
>     ''', user_name)
>   File "/Users/user/PycharmProjects/instapy/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
>     'args': converted_args})['value']
>   File "/Users/user/PycharmProjects/instapy/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/Users/user/PycharmProjects/instapy/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'edges' of undefined
>   (Session info: chrome=72.0.3626.81)
>   (Driver info: chromedriver=2.45.615355 (d5698f682d8b2742017df6c81e0bd8e6a3063189),platform=Mac OS X 10.11.6 x86_64)`

I use the action follow by tags:

> session.follow_by_tags(['nature', 'geo'], amount=5)

I get the error after opening the first Tag.

**Comment by tE3m** [comment]
```
git pull
```
Should fix it
