### ISSUE TITLE
no more assets folder??

### ISSUE THREAD

**Issue by GreatTimeBand** [InstaPy/InstaPy#3891]
I attempted to pull the latest instapy repository and it totally broke my entire install.  Have since deleted the repo, recloned, reinstalled, and it seems to be missing the assets folder now?? I did everything exactly the same (have had it up and running for several months now) and now it seems to be totally broken.  Is this a known issue?? Am I doing something wrong??

**Comment by GreatTimeBand** [comment]
I also don't see it in the repo online.  Has something fundamentally changed about the way this works now?? Are all old installation methods no longer supported?

**Comment by tE3m** [comment]
It's not your fault:smile:. There has been an update to instapy. Try running 
```
pip install instapy
```
 to get all the new dependencies.

**Comment by GreatTimeBand** [comment]
I'm fairly scrubby at all this, would I just run this command from command prompt in the Instapy directory folder?

**Comment by GreatTimeBand** [comment]
For what it's worth, I'm still receiving the same error when attempting to run the quickstart:

Traceback (most recent call last):
  File "C:\Users\Zack\Documents\GitHub\InstaPy\quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "C:\Users\Zack\Documents\GitHub\InstaPy\instapy\__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "C:\Users\Zack\Documents\GitHub\InstaPy\instapy\instapy.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by JakeShore98** [comment]
im on the same page as @GreatTimeBand id appreciate some direction on how to properly update without corrupting eveyrhting

**Comment by tE3m** [comment]
pip doesn't have to do with Git. That means that you don't update the *files* , but the *dependecies*. Do you have different versions of python installed, @GreatTimeBand ? Because then use 
```
python3 -m pip install instapy
```

**Comment by Tr1pke** [comment]
mine is corrupted aswell, did a **_fresh_** install and i got now this:

### Traceback (most recent call last):
File "InstaPy/MYINSTAGRAMACCOUNT-follow-unfollow.py", line 23, in 
session.follow_user_followers(['dogs.lovers','dogs','dogsofinstagram','dogsofinstaworld'], amount=40, randomize=True, interact=False)
File "/home/steven/InstaPy/instapy/instapy.py", line 3068, in follow_user_followers
self.logfolder)
File "/home/steven/InstaPy/instapy/unfollow_util.py", line 998, in get_given_user_followers
logger, logfolder)
File "/home/steven/InstaPy/instapy/unfollow_util.py", line 745, in get_users_through_dialog
scroll_to_bottom_of_followers_list(browser, dialog)
File "/home/steven/InstaPy/instapy/unfollow_util.py", line 707, in scroll_to_bottom_of_followers_list
"arguments[0].children[1].scrollIntoView()", element)
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
'args': converted_args})['value']
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'scrollIntoView' of undefined
(Session info: headless chrome=72.0.3626.81)
(Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.18.0-13-generic x86_64)

**Comment by tE3m** [comment]
@JakeShore98 what I meant was that you don't need to update anything, just install the package form pip. The launch added a couple new dependencies, for example: the chromedriver.

**Comment by GreatTimeBand** [comment]
> pip doesn't have to do with Git. That means that you don't update the _files_ , but the _dependecies_. Do you have different versions of python installed, @GreatTimeBand ? Because then use
> 
> ```
> python3 -m pip install instapy
> ```

you are correct I have multiple versions of python installed (3.6 and 3.7, I can consolidate if recommended).  But this was never an issue before attempting to update today.  I'm guessing I just need to start completely clean?  I'm trying all these install methods, they appear to work, but then Instapy still won't run

**Comment by Tr1pke** [comment]
> I'm guessing I just need to start completely clean

didnt work for me ...

**Comment by tE3m** [comment]
@Tr1pke try again. Someone on discord just had that issue, too, but on the next run it was fixed

**Comment by GreatTimeBand** [comment]
Any way to revert back to the old version??  I'm down to pursue this new one but it just seems different for no apparent reason (old version was functioning totally fine, and is still running on another machine)

**Comment by tE3m** [comment]
@GreatTimeBand then do 
```
<the python version you use for instapy> -m pip install instapy
```

**Comment by tE3m** [comment]
It was never an issue because instapy was only launched to pypi today, which makes it available to download via pip. Since pip is a python module, it depends on the version.

**Comment by GreatTimeBand** [comment]
At this point nothing seems to be working at all lol.  I tried:

python3.6 -m pip install instapy

and I get the response:

the system cannot find the file specified

**Comment by Tr1pke** [comment]
> @Tr1pke try again. Someone on discord just had that issue, too, but on the next run it was fixed

same error, another clean install maybe? ...

**Comment by tE3m** [comment]
@GreatTimeBand maybe python36 instead of python3.6?

**Comment by JakeShore98** [comment]
@TarekJ03 so updating should resolve my issue? Any down falls to it?

**Comment by Tr1pke** [comment]
what python you use ? 3 or 3.6 as of now?

**Comment by GreatTimeBand** [comment]
> @GreatTimeBand maybe python36 instead of python3.6?

not recognized...let's say I want to start completely clean, remove all old files, delete repo, start brand new- is there any documentation for going about this new install?

**Comment by GreatTimeBand** [comment]
feels like I've tried everything but this new method is just totally incompatible with how I did it originally

**Comment by tE3m** [comment]
@JakeShore98 it's not really updating, it's more like installing new dependencies. But I think it is explained in the new readme.md

**Comment by GreatTimeBand** [comment]
@TarekJ03 really appreciate all the help.  Is there a reason why this was so fundamentally changed without much heads up?

**Comment by JakeShore98** [comment]
this is the error im recieving, even after updating the dependencies 


Traceback (most recent call last):
  File "quickstartcentral.py", line 35, in <module>
    session.follow_user_followers(['nytentsale', 'extrabutternyc', 'kith', 'americanashops','liltecca'], amount=1, randomize=False, sleep_delay=23, interact=True)
  File "/Users/JakeShore/Documents/workspace/env-InstaPy/InstaPy/instapy/instapy.py", line 3048, in follow_user_followers
    self.logfolder)
  File "/Users/JakeShore/Documents/workspace/env-InstaPy/InstaPy/instapy/unfollow_util.py", line 998, in get_given_user_followers
    logger, logfolder)
  File "/Users/JakeShore/Documents/workspace/env-InstaPy/InstaPy/instapy/unfollow_util.py", line 745, in get_users_through_dialog
    scroll_to_bottom_of_followers_list(browser, dialog)
  File "/Users/JakeShore/Documents/workspace/env-InstaPy/InstaPy/instapy/unfollow_util.py", line 707, in scroll_to_bottom_of_followers_list
    "arguments[0].children[1].scrollIntoView()", element)
  File "/Users/JakeShore/Documents/workspace/env-InstaPy/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/Users/JakeShore/Documents/workspace/env-InstaPy/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/JakeShore/Documents/workspace/env-InstaPy/env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: arguments[0].children[1] is undefined

**Comment by tE3m** [comment]
@GreatTimeBand then don't install it via git, if you start new. But I'd revommend backing up your scripts and your logs and db folder. Install it via pip. That's how the installation is supposed to happen for simple users who don't want to modify the core of the project. Read it in readme.md

**Comment by GreatTimeBand** [comment]
@TarekJ03 is it still possible to do it the old way?  or is it recommended to abandon all that and start clean?

**Comment by tE3m** [comment]
@GreatTimeBand to make installation and updating easier. It's more like a stable app one can download instead of a development repo.

**Comment by tE3m** [comment]
@GreatTimeBand I downloaded it with pip, copied my logs and db folder into the new workspace folder and everything works great for me.

**Comment by Tr1pke** [comment]
how do you download it with pip? if i type pip install instapy it wont do anything

**Comment by GreatTimeBand** [comment]
@TarekJ03 can you give a brief rundown start to finish of what exactly to do?  If not using git, should I just download the whole repo to my computer?  Seems like I'm missing something fundamental about the way this new version works

> how do you download it with pip? if i type pip install instapy it wont do anything

same here, how does this work?  From which window, where do I run this?  Scrubby programmer reporting for duty

**Comment by JakeShore98** [comment]
@GreatTimeBand are you on mac or pc?

**Comment by GreatTimeBand** [comment]
> @GreatTimeBand are you on mac or pc?

pc, windows 7 lol

**Comment by Tr1pke** [comment]
Linux

and i follow: https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md

**Comment by tE3m** [comment]
@GreatTimeBand you download instapy via pip. Then it's installed on your computer (globally!), which means you can put your script wherever you like. The core of this update is simply that instapy is now a python package/module, which can be imported with 
```
import instapy
```

**Comment by JakeShore98** [comment]
i use mac but i was able to do the whole thing thru terminal using this guide. I believe linux has a terminal also, not sure about windows https://www.youtube.com/watch?v=A1a8J_IjSPs

**Comment by octavius-1** [comment]
Hey @Tr1pke , I just git pulled, pip updated and I'm having the same 'ScrollIntoView' issue when trying to get following/follower users from any user. Let me know if you have more doubts regarding the instapy general update. I just performed it half an hour ago in AWS.

**Comment by tE3m** [comment]
@Tr1pke what do you mean 
"it won't do anything"?

**Comment by GreatTimeBand** [comment]
> @GreatTimeBand you download instapy via pip. Then it's installed on your computer (globally!), which means you can put your script wherever you like. The core of this update is simply that instapy is now a python package/module, which can be imported with
> 
> ```
> import instapy
> ```

as someone that's super new to python, how does one go about "downloading via pip"? is this from idle?  or command prompt?

**Comment by Tr1pke** [comment]
> @Tr1pke what do you mean
> "it won't do anything"?

steven@ST-Meise:$ pip install instapy
Requirement already satisfied: instapy in /usr/local/lib/python3.6/dist-packages (0.1.1)
Requirement already satisfied: EasyProcess>=0.2.3 in /usr/local/lib/python3.6/dist-packages (from instapy) (0.2.3)
Requirement already satisfied: MeaningCloud-python>=1.1.1 in /usr/local/lib/python3.6/dist-packages (from instapy) (1.1.1)
Requirement already satisfied: PyVirtualDisplay>=0.2.1 in /usr/local/lib/python3.6/dist-packages (from instapy) (0.2.1)
Requirement already satisfied: PyYAML>=3.13 in /usr/local/lib/python3.6/dist-packages (from instapy) (3.13)
Requirement already satisfied: certifi>=2018.10.15 in /usr/local/lib/python3.6/dist-packages (from instapy) (2018.11.29)
Requirement already satisfied: chardet>=3.0.4 in /usr/local/lib/python3.6/dist-packages (from instapy) (3.0.4)
Requirement already satisfied: clarifai>=2.4.1 in /usr/local/lib/python3.6/dist-packages (from instapy) (2.5.0)
Requirement already satisfied: configparser>=3.5.0 in /usr/local/lib/python3.6/dist-packages (from instapy) (3.5.0)
Requirement already satisfied: emoji>=0.5.1 in /usr/local/lib/python3.6/dist-packages (from instapy) (0.5.1)
Requirement already satisfied: future>=0.17.1 in /usr/local/lib/python3.6/dist-packages (from instapy) (0.17.1)
Requirement already satisfied: grpcio>=1.16.1 in /usr/local/lib/python3.6/dist-packages (from instapy) (1.17.1)
Requirement already satisfied: idna>=2.7 in /usr/local/lib/python3.6/dist-packages (from instapy) (2.8)
Requirement already satisfied: instapy-chromedriver==2.44 in /usr/local/lib/python3.6/dist-packages (from instapy) (2.44)
Requirement already satisfied: jsonschema>=2.6.0 in /usr/local/lib/python3.6/dist-packages (from instapy) (2.6.0)
Requirement already satisfied: plyer>=1.3.1 in /usr/local/lib/python3.6/dist-packages (from instapy) (1.3.2)
Requirement already satisfied: protobuf>=3.6.1 in /usr/local/lib/python3.6/dist-packages (from instapy) (3.6.1)
Requirement already satisfied: regex>=2018.11.22 in /usr/local/lib/python3.6/dist-packages (from instapy) (2018.11.22)
Requirement already satisfied: requests>=2.20.1 in /usr/local/lib/python3.6/dist-packages (from instapy) (2.21.0)
Requirement already satisfied: selenium>=3.141.0 in /usr/local/lib/python3.6/dist-packages (from instapy) (3.141.0)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.6/dist-packages (from instapy) (1.12.0)
Requirement already satisfied: urllib3>=1.24.1 in /usr/local/lib/python3.6/dist-packages (from instapy) (1.24.1)
Requirement already satisfied: googleapis-common-protos<2,>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from clarifai>=2.4.1->instapy) (1.5.5)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from protobuf>=3.6.1->instapy) (40.2.0)
steven@ST-Meise:$

**Comment by tE3m** [comment]
you open terminal(on windows cmd.exe) and type 
```
pip<optional:version> install instapy
```

**Comment by tE3m** [comment]
@Tr1pke you already have instapy installed.

**Comment by Tr1pke** [comment]
> @Tr1pke you already have instapy installed.

steven@ST-Meise:~$ instapy
instapy: command not found

**Comment by GreatTimeBand** [comment]
@TarekJ03 mine seems to indicate I already have it installed as well.  Yet it still doesn't run....how do we go about starting clean???  this isn't making much sense at this point, everything seems to suggest it's all up and running yet it still doesn't work

**Comment by tE3m** [comment]
@GreatTimeBand cmd. you either type in 
```
python<optional:version> -m pip install instapy
```
or 
```
pip<optional:version> install instapy
```

**Comment by Tr1pke** [comment]
So that whole GIT folder is not needed anymore?

**Comment by GreatTimeBand** [comment]
> @GreatTimeBand cmd. you either type in
> 
> ```
> python<optional:version> -m pip install instapy
> ```
> or
> 
> ```
> pip<optional:version> install instapy
> ```

all the results say "already satisfied"...

**Comment by tE3m** [comment]
@GreatTimeBand is your error that "scrollIntoView" thing? I'm not really sure about that

**Comment by JakeShore98** [comment]
@TarekJ03 did updating resolve this issue for you? It hasn't seemed to resolve it for me

**Comment by Tr1pke** [comment]
still got the same issue like before:

`Traceback` (most recent call last):
  File "dino.runs-follow-unfollow.py", line 23, in <module>
    session.follow_user_followers(['dogs.lovers','dogs','dogsofinstagram','dogsofinstaworld'], amount=40, randomize=True, interact=False)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 3068, in follow_user_followers
    self.logfolder)
  File "/usr/local/lib/python3.6/dist-packages/instapy/unfollow_util.py", line 998, in get_given_user_followers
    logger, logfolder)
  File "/usr/local/lib/python3.6/dist-packages/instapy/unfollow_util.py", line 745, in get_users_through_dialog
    scroll_to_bottom_of_followers_list(browser, dialog)
  File "/usr/local/lib/python3.6/dist-packages/instapy/unfollow_util.py", line 707, in scroll_to_bottom_of_followers_list
    "arguments[0].children[1].scrollIntoView()", element)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'scrollIntoView' of undefined
  (Session info: headless chrome=72.0.3626.81)
  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.18.0-13-generic 

> x86_64)

**Comment by GreatTimeBand** [comment]
> @GreatTimeBand is your error that "scrollIntoView" thing? I'm not really sure about that

this is the error I'm still receiving:


Traceback (most recent call last):
  File "C:\Users\Zack\Documents\GitHub\InstaPy\quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "C:\Users\Zack\Documents\GitHub\InstaPy\instapy\__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "C:\Users\Zack\Documents\GitHub\InstaPy\instapy\instapy.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by tE3m** [comment]
```
pip install requests
```
 @GreatTimeBand

**Comment by GreatTimeBand** [comment]
I guess at this point, I see myself as having two options (wondering which would be best)

1) completely uninstall instapy, remove all files, logs, etc, start completely fresh with this new system (which I would need a guide for, I can't seem to remove everything or install this correctly under the current circumstances)

2) copy the old version off my other machine and completely forego this new version

**Comment by GreatTimeBand** [comment]
> ```
> pip install requests
> ```
> @GreatTimeBand

"already satisfied"...

**Comment by Tr1pke** [comment]
> > ```
> > pip install requests
> > ```
> > @GreatTimeBand
> 
> "already satisfied"...

same for me

**Comment by GreatTimeBand** [comment]
if it's possible to go back to the way it was before today, I was totally fine with it being more of a "development repo"

**Comment by tE3m** [comment]
Okay, it seems like pretty much everyone has that 'scrollIntoView' thing. Maybe there was an update by ig?

**Comment by tE3m** [comment]
I have it too

**Comment by tE3m** [comment]
@GreatTimeBand @Tr1pke did you run it for the python version you use instapy on?

**Comment by Tr1pke** [comment]
> @GreatTimeBand @Tr1pke did you run it for the python version you use instapy on?

yes i did

**Comment by GreatTimeBand** [comment]
@TarekJ03 as far as I know, yes.  What does Tim have to say about all this?? Any kind of announcement?? Seems like a major update to just drop without any related documentation

**Comment by tE3m** [comment]
Well, the readme has been updated? So there is documentation.
But as long as we still have the scrollIntoView error, that doesn't even matter that much, because they changed something about their layout. Until that is fixed, there is going to be better documentation, I'm sure.

**Comment by Tr1pke** [comment]
SO lets say i start from 0
i install ubuntu on my server

apt install pip
pip install instapy

and thats it?

**Comment by tE3m** [comment]
Pretty much @Tr1pke

**Comment by tE3m** [comment]
But you should
```
apt-get install python3
```
. I think pip comes with it

**Comment by Tr1pke** [comment]
then when i do: pip install instapy i get 
Requirement already satisfied: instapy in /usr/local/lib/python3.6/dist-packages (0.1.1)

so i run python3.6 blabla.py right?

**Comment by tE3m** [comment]
Yes. But I think you have to add a line to your old file:
```
import instapy
```

**Comment by Tr1pke** [comment]
but that i can only do from X not in terminal
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/360.

**Comment by tE3m** [comment]
Sorry, I'm not a mac user. Can't help with that

**Comment by Tr1pke** [comment]
> Sorry, I'm not a mac user. Can't help with that

Its linux, im on linux not mac

**Comment by tE3m** [comment]
Ohh I think you misunderstood: 
```
import instapy
```
is not a bash command. You have to put it in your python script

**Comment by GreatTimeBand** [comment]
Let me know if there's ever any resolution with this...for now I'll keep tinkering with it and will hopefully find a solution.  At the very least, I'm going to reinstall the older version I had up and running

**Comment by JakeShore98** [comment]
@GreatTimeBand 

"hey, I had same problem changing Line 740 in instaPy/instapy/unfollow_util.py fixed it for me:

Change this:

-dialog_address = "//body/div[2]/div/div/div[2]"
got this from githubpatrick, it helped me

**Comment by potentowl** [comment]
@JakeShore98 Changing this code does not create an assets folder ?

**Comment by gyrex** [comment]
If you want to go back to a previous version that works without using pip install instapy, within your instapy directory, copy and paste the following:

`git reset --hard 1fcc2fdc8bfd9810dabfa576bc9d73500baad8a3`

**Comment by axlright** [comment]
I run ~6 instances of InstaPy on a Chromebook. Each time I would load any one instance, I'd run `git pull origin master` to make sure I was up-to-date with everything from the repo (which is how I stumbled upon this giant update that had no notice, but that's another story).

I'm understanding this new method will make InstaPy run globally - pretty cool. It also wants to know the path of each instance, which is also cool - can keep logs and scripts for each instance in a tidy place.

I get running `pip3  install instapy`

This was described above as being for novices that don't want to update a repo all the time. I still want to update the repo all the time (though a bit more notice on giant changes would be awesome).

So what's the protocol to update InstaPy moving forward now that it's a Python package? The standard `sudo apt-get update` then `sudo apt-get upgrade`?

Thanks!

**Comment by axlright** [comment]
FWIW I got the new setup working in ~45 min and I'm not too bright, so notice would have been nice but it seems to work okay. What's cool about this new setup is that I can version control the local workspace folder to GitHub and archive it there should anything happen to my little Chromebook. And I could then also run all installs from a few different machines (not at once, but at least have the option to) and push updates to scripts and logs up to GitHub.

**Comment by Tr1pke** [comment]
it works again ...
sudo pip install instapy -U

**Comment by potentowl** [comment]
@Tr1pke this code did not make the assets folder. @axlright what would you add to the /etc/apt/source.list in order to update with `sudo apt-get update` then `sudo apt-get upgrade` ??

**Comment by axlright** [comment]
@loopypanda Thanks for the response
>what would you add to the /etc/apt/source.list in order to update with `sudo apt-get update` then `sudo apt-get upgrade` ??

Maybe I asked it dumb. Just want to know how to pull daily changes each time I run InstaPy. Documentation says to update with `pip3 install instapy -U` so I'll try that moving forward. I used to run the standard `git pull origin master` each time. Just want to know how to keep my local code up-to-date with the repo now that its a python package.

**Comment by potentowl** [comment]
@axlright no you didn't ask it dumb, i want to figure out same thing, so i can update faster.

**Comment by tE3m** [comment]
@loopypanda if you *need* an assets folder, the new workspace creates one.

**Comment by nbgabriel** [comment]
Hello there! i'm still having this issue:

`INFO [2019-02-05 03:16:04] [myiguser]  Workspace in use: "/home/mylinuxuser/Downloads/InstaPy.worksplace/myiguser/InstaPy"
WARNING [2019-02-05 03:16:04] [None]  Heeh! Error occurred while getting a DB profile for 'None':
	NOT NULL constraint failed: profiles.name
Traceback (most recent call last):
  File "myiguser.py", line 23, in <module>
    session = InstaPy()
  File "/home/mylinuxuser/Downloads/venv1/local/lib/python2.7/site-packages/instapy/instapy.py", line 273, in __init__
    get_database(make=True)  # IMPORTANT: think twice before relocating
  File "/home/mylinuxuser/Downloads/venv1/local/lib/python2.7/site-packages/instapy/database_engine.py", line 54, in get_database
    id = get_profile(name, address, logger) if id is None or make else id
  File "/home/mylinuxuser/Downloads/venv1/local/lib/python2.7/site-packages/instapy/database_engine.py", line 137, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable
`

**Comment by Tr1pke** [comment]
steven@srv-yellow:~/InstaPy$ python3 MyIGacc-follow-unfollow.py 

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
No any custom workspace provided.	~using existing..

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/steven/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-02-05 09:29:03] [MyIGacc]  Using built in instapy-chromedriver executable (version 2.44)
ERROR [2019-02-05 09:29:03] [MyIGacc]  Message: 'chromedriver_linux64' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/instapy_chromedriver-2.44-py3.6.egg/instapy_chromedriver/chromedriver_linux64'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/instapy/browser.py", line 123, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver_linux64' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Traceback (most recent call last):
  File "MyIGacc-follow-unfollow.py", line 13, in <module>
    headless_browser=True)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 276, in __init__
    self.set_selenium_local_session()
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 328, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /usr/local/lib/python3.6/dist-packages/instapy_chromedriver-2.44-py3.6.egg/instapy_chromedriver/chromedriver_linux64
steven@srv-yellow:~/InstaPy$

**Comment by Tr1pke** [comment]
It only follows 10 usernames while I set 40. 
What could that be ?

Failed to load desired amount of users

**Comment by potentowl** [comment]
@Tr1pke @TarekJ03 After doing a fresh install of ubuntu i used pip3 install instapy instead of wget ( how i usually update ) but it creates no InstaPy-master folder so i had to use wget ........ so does pip3 install instapy not create a folder ?

**Comment by Tr1pke** [comment]
Wget what? You mean git ?

**Comment by axlright** [comment]
@Tr1pke wget is a Linux command for downloading a file. I know there's a lot of confusion here (for me, too) but with an open source project where no one's getting paid, it can be a good idea to do a quick Google search before adding more questions to the thread.

**Comment by Tr1pke** [comment]
@axlright

> @Tr1pke wget is a Linux command for downloading a file. I know there's a lot of confusion here (for me, too) but with an open source project where no one's getting paid, it can be a good idea to do a quick Google search before adding more questions to the thread.

but what do you want to wget? 
To make a InstaPy master folder i would NOT use wget but just "mkdir InstaPy" what is not needed because it creates itselfs ...........
And pip3 doesn't makes a master folder its a python script installer
And your instapy command creates a MASTER InstaPy folder AFTER you start your instapy bot, where you will find your logs

**Comment by axlright** [comment]
@Tr1pke Cool, thanks for the "duh"

It's not such a complicated setup. The new setup is well described in the updated readme. I'll butt out though. Lots of attitude in this issue thread. People expect other people to do things for them. It's an open source project. Figure it out or contribute. Or ask a polite question.

**Comment by Tr1pke** [comment]
Thats is true and i remove my comment, however Wget what? You mean git ? is not such negative sentence imo

**Comment by praful-dhabekar** [comment]
I got new Ubuntu droplet and when I clone InstaPy there's no assets folder inside InstaPy-master folder.

**Comment by Tr1pke** [comment]
You dont need that anymore. pip install instapy

**Comment by praful-dhabekar** [comment]
> You dont need that anymore. pip install instapy

well someone has to modify [How to run InstaPy on a digital ocean Ubuntu droplet](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md) tutorial.

**Comment by Tr1pke** [comment]
The readme has been updated. But imo not very detailed. Had some issues to in the beginning. Luckily there is a issues fora here

**Comment by tE3m** [comment]
@Tr1pke well, i think it's made for a fresh installation, not to explain how to move from the old installation to a new one. But you're right, there could've been more info about the transfer.

**Comment by greggjaskiewicz** [comment]
There's loads of users that have been using it via git HEAD, and one day we updated the repo to the latest - and it stopped working for us. 
I think a simple explanation of what's changed would help. Not everyone wants to just install it using pip or such :-)

**Comment by tE3m** [comment]
@greggjaskiewicz if you don't want to reinstall InstaPy from `pip`, I think only installing the dependency `instapy-chromedriver` would be enough. So try `pip install instapy-chromedriver`. But I obviously don't know your error.

**Comment by greggjaskiewicz** [comment]
that worked @TarekJ03 , the issue I had was the original error with chrome driver module missing .

**Comment by tE3m** [comment]
Yes, and what you just did was installing it :smile:

**Comment by greggjaskiewicz** [comment]
ok, confusing thing is - I had it installed previously. But probably not via pip.

**Comment by tE3m** [comment]
I think you had installed a chromedriver, but not the `pip` package `instapy-chromedriver`, which is now a dependency. Why? Because new users now don't have to install it manually anymore. But "old" users who've been here before InstaPy was released to PyPi already have a chromedriver, but since it's a dependency everyone at least has to *install* it now. Btw search in readme for 'workspace', then you'll find the other major change.

**Comment by greggjaskiewicz** [comment]
Thanks @TarekJ03 Workspaces is also a massive change. I had used different virtual environments previously to achieve this. Worked fine, as long as I kept things running in different directories. This is slightly more powerful.

**Comment by mwargan** [comment]
How does this affect installation on Raspian? Should we switch from using git clone?

**Comment by Tr1pke** [comment]
Yes you need to get the chrome driver by apt else it won’t work 
Rest is pip install instapy and update just put -U after it. Simple , many bots to come on Instagram now :-p

**Comment by mwargan** [comment]
@Tr1pke Great! So I'll need to create the assets folder in the workspace, right? What if I want to modify the log file to add a post request to my server? Would I need to clone the repo then?

**Comment by tE3m** [comment]
@mwargan @Tr1pke  that's not completely correct. Thanks to @scriptworld-git , we can now install the chromedriver for raspbian like this:
```
pip3 uninstall instapy-chromedriver
pip3 install instapy-chromedriver==2.36.post0
```
That's it. No need to create an assets folder and download a driver manually.

**Comment by Tr1pke** [comment]
That never worked for me. And I have 2 servers 
One is Ubuntu one is Debian. Always had to download the driver by apt 
I tried that.

**Comment by mwargan** [comment]
> @mwargan @Tr1pke that's not completely correct. Thanks to @scriptworld-git , we can now install the chromedriver for raspbian like this:
> 
> ```
> pip3 uninstall instapy-chromedriver
> pip3 install instapy-chromedriver==2.36.post0
> ```
> That's it. No need to create an assets folder and download a driver manually.

I'll give this a go on the next device I install this script onto. Though, does this mean that instapy installs its own chromedriver which is the wrong version? I've never had to remove a chromedriver for instapy before, I just added the other one to the assets folder and all was golden.

 @Tr1pke are your servers running on a Raspberry?

**Comment by tE3m** [comment]
@mwargan it installs the newest version. But that version isn't compatible with Raspbian's Chromium, which is v65. That's why we created a special version dedicated to Raspbian(2.36.post0)

**Comment by tE3m** [comment]
@Tr1pke that has been changed. We added a binary that fits Chromium v65, so from now on it's possible.

**Comment by mwargan** [comment]
> @mwargan it installs the newest version. But that version isn't compatible with Raspbian's Chromium, which is v65. That's why we created a special version dedicated to Raspbian(2.36.post0)

I'm coming from a PHP background and can't stop thinking of how, in Composer, you can specify the package version you need. Can't we have instapy install the correct version automatically?

Edit: I think I understand that this is a specific issue to Raspian so specifying the version isn't a good solution for everyone...

**Comment by Tr1pke** [comment]
> > @mwargan it installs the newest version. But that version isn't compatible with Raspbian's Chromium, which is v65. That's why we created a special version dedicated to Raspbian(2.36.post0)
> 
> I'm coming from a PHP background and can't stop thinking of how, in Composer, you can specify the package version you need. Can't we have instapy install the correct version automatically?

That would be too easy, where is the fun of that?

**Comment by tE3m** [comment]
@mwargan you mean installing it by getting the os? Because the working version is installed automatically, it just doesn't work for *ARM-devices*, since the newest Chromium available on ARM is v65.

**Comment by mwargan** [comment]
@TarekJ03 I meant by getting InstaPy - I thought that `pip3 uninstall instapy-chromedriver` removes a package that was previously installed by InstaPy but now I can see how the naming threw me off and instead it uninstalls the default OS chromedriver :P

Regardless, I've never had to uninstall previous chromedriver versions (in Raspian), I just added the additional chromedriver to InstaPy and all was working fine!

Does `install instapy-chromedriver` override the default OS chromedriver, or does it drop it in for use just by InstaPy?

**Comment by tE3m** [comment]
`instapy-chromedriver` is in fact a package that is installed by InstaPy and is *not* the default OS chromedriver. It's intentionally named *instapy*-chromedriver so that it' clear that it's a part of this project.
