### ISSUE TITLE
Trouble with new version

### ISSUE THREAD

**Issue by nbgabriel** [InstaPy/InstaPy#3894]
Hello there!! 

Im trying the new version, but i cannot make it work! 

Here is my error: 

INFO [2019-02-04 20:26:19] [user]  Workspace in use: "/home/myuser/Downloads/InstaPy.Test/InstaPy-master.1"
WARNING [2019-02-04 20:26:19] [None]  Heeh! Error occurred while getting a DB profile for 'None':
	NOT NULL constraint failed: profiles.name
Traceback (most recent call last):
  File "quickstart.py", line 23, in <module>
    session = InstaPy()
  File "/home/myuser/Downloads/InstaPy.Test/InstaPy-master.1/instapy/instapy.py", line 273, in __init__
    get_database(make=True)  # IMPORTANT: think twice before relocating
  File "/home/myuser/Downloads/InstaPy.Test/InstaPy-master.1/instapy/database_engine.py", line 54, in get_database
    id = get_profile(name, address, logger) if id is None or make else id
  File "/home/myuser/Downloads/InstaPy.Test/InstaPy-master.1/instapy/database_engine.py", line 137, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable
(venv) gnbratig@barleywine:/home/myuser/Downloads/InstaPy.Test/InstaPy-master.1# 

And my config file is:
```
""" Quickstart script for InstaPy usage """

# imports
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace


# set workspace folder at desired location (default is at your home folder)
#set_workspace = (/home/gnbratig/Downloads/InstaPy.Test/InstaPy-master.1)
set_workspace("/home/myuser/Downloads/InstaPy.Test/InstaPy-master.1")

insta_username = 'user'
insta_password = 'passw'
# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

# get an InstaPy session!
session = InstaPy()

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_user_interact(amount=3, randomize=True, percentage=90, media='Photo')
    session.set_do_comment(False, percentage=60)
    session.set_do_follow(enabled=True, percentage=70)
    session.set_do_like(enabled=True, percentage=50)

    session.like_by_locations(['307127281','436457027','495767396','1035579498','661870565','1013619841','317266165', '250284163','239469804','220510540','333217390','240152059','225357903','503651352'], amount=30, skip_top_posts=False)
```
What im missing?. 

I've clone the zip.

**Comment by GreatTimeBand** [comment]
see previous issue I opened up...lots of people seem to be having problems with the new version

**Comment by gyrex** [comment]
If you want to go back to a previous version that works without using pip install instapy, within your instapy directory, copy and paste the following:

`git reset --hard 1fcc2fdc8bfd9810dabfa576bc9d73500baad8a3`

**Comment by tE3m** [comment]
Did you provide your real user and pw in your local version @nbgabriel ?

**Comment by nbgabriel** [comment]
> Did you provide your real user and pw in your local version @nbgabriel ?

Yes!, i put it my quickstart.py

**Comment by tE3m** [comment]
And the path you provided is the folder where _db_ folder is in?

**Comment by nbgabriel** [comment]
> And the path you provided is the folder where _db_ folder is in?

Where i specify the _db_folder?. I put only the workspace. Thanks

**Comment by Tr1pke** [comment]
if i install instapy by git and clone it works
BUT
if i install it by pip install instapy i get this:

steven@srv-purple:$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from instapy import InstaPy
ModuleNotFoundError: No module named 'instapy'
steven@srv-purple:~$

**Comment by breuerfelix** [comment]
@Tr1pke you are executing with python3 so make sure to use `pip3 install instapy` and not just `pip install instapy`. 

you already did that ?  
also if you use virtual environments, make sure do install instapy in the correct one

**Comment by Tr1pke** [comment]
> @Tr1pke you are executing with python3 so make sure to use `pip3 install instapy` and not just `pip install instapy`.
> 
> you already did that ?
> also if you use virtual environments, make sure do install instapy in the correct one

i did, still the same
