### ISSUE TITLE
D

### ISSUE THREAD

**Issue by ishandutta2007** [InstaPy/InstaPy#3896]
F

**Comment by AnwarAhmedPSU** [comment]
@ishandutta2007 thanks for the update. It works except "Failed to load desired amount of users!" is occurring due to the script not being able to load the amount asked to follow from another user.

**Comment by Cokpan** [comment]
@ishandutta2007 Thanks for the update.
I got several unfollow successful (at least without any error notice), but after resting, there's some error notice that says this:

`Unfollow loop error: b'Message: stale element reference: element is not attached to the page document\n`

After every unfollow attempt.

**Comment by ishandutta2007** [comment]
Yes let this issue remain open untill "Failed to load desired amount of users" is resolved.

**Comment by sionking** [comment]
> Fixed here [8e4fb14](https://github.com/timgrossmann/InstaPy/commit/8e4fb1455ded426a1fc57407d9d08e4a56b6a308)

so it is not failing but not scrolling either
