### ISSUE TITLE
Migrate Docker config and documentation to instapy-docker repository

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#3900]
#### After finally releasing InstaPy on pip and adding releases, we want to clean up the InstaPy repository a bit. Therefore we will remove the content regarding docker setup and migrate it to https://github.com/InstaPy/instapy-docker

Advantages of this feature:
- Docker specific content is separated (and then linked in the readme)
- Core repository will get more organised

Possible ways of achieving this while keeping control:
- @scriptworld-git @funkypenguin Know more about this than I do 😁 

> [Bountysource this Issue](https://www.bountysource.com/issues/69649114-migrate-docker-config-and-documentation-to-instapy-docker-repository)

--- 

###### Feel free to comment with adjustments and improvements

**Comment by Herrox** [comment]
Please let me know how I may help you on this issue :)
And if I may, we also need to think about creating Docker setup for the additionals tools like instapy-dashboard for example

**Comment by timgrossmann** [comment]
https://github.com/InstaPy/instapy-docker
