### ISSUE TITLE
Bug fix: Stale element

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#3902]
#### One very common error is `stale element reference: element is not attached to the page document`. The biggest problem with this error is that it is non-deterministic and sometimes appears and fades with the next execution. 

Advantages of this feature:
- Error proneness when discovering a stale element exception

Possible ways of achieving:
- A decorator is added to each method automatically catching this error and triggering a reload of the page (which in most cases will solve the error). 
- This is done up to three times. If the error persists after that, an actual error is thrown and the tool still stops.
- The decorator wraps the whole method which won't add much code to the tool but only one line on the top e.g. `@stalereload(....)`. 

> [Bountysource this Issue](https://www.bountysource.com/issues/69650593-bug-fix-stale-element)

--- 

###### Feel free to comment with adjustments and improvements

**Comment by sionking** [comment]
I think it should be a part of browser file - class.

**Comment by timgrossmann** [comment]
@sionking Good idea, this will fit nicely into #3581

**Comment by timgrossmann** [comment]
#3962
