### ISSUE TITLE
not scrolling to pick some one also followers to interact

### ISSUE THREAD

**Issue by c0d3x27** [InstaPy/InstaPy#3903]
﻿
im having a problem just as the tittle say. yesterday my program was working well and since last night is acting up. im trying to interact with someone followers but when it opens the little windows to pickt he followers it wont scroll down or anything it will just kill the process for no reason.

**Comment by Tr1pke** [comment]
Got the same problem

Won’t scroll and keeps wanting to follow the same user. Then kills the session

**Comment by ishandutta2007** [comment]
We are tracking it here https://github.com/timgrossmann/InstaPy/issues/3896

**Comment by c0d3x27** [comment]
> Got the same problem
> 
> Won’t scroll and keeps wanting to follow the same user. Then kills the session

yeah

**Comment by tE3m** [comment]
It should be fixed. Try updating your files

**Comment by c0d3x27** [comment]
> It should be fixed. Try updating your files

i did it git pull and now yea is fix but it keep interacting with the same users

**Comment by tE3m** [comment]
Did you use 
``` 
pip install instapy -U
```
to update?

**Comment by c0d3x27** [comment]
> Did you use
> 
> ```
> pip install instapy -U
> ```
> 
> to update?

yyeah nothing is working. it keep interating with the same people over and over and only 37 people when im asking the program for 200

**Comment by Tr1pke** [comment]
I have the same. We need an update. IG changed something

**Comment by c0d3x27** [comment]
> I have the same. We need an update. IG changed something

yeah something is wrong
