### ISSUE TITLE
session.interact_user_followers grabs the same user over and over

### ISSUE THREAD

**Issue by Aouah** [InstaPy/InstaPy#3904]
## Expected Behavior
I had the "Grabbed no user" issue and I made the Xpath modification in my unfollow_util.py file as explained here: https://github.com/timgrossmann/InstaPy/issues/3890.
Now the script runs well again but I have another issue with the scrolling function.

## Current Behavior
It grabs the same user to interact with over and over.
Here is a example of what I have in my logs file after a run:

INFO [2019-02-05 10:28:30] [XXX]  Session started!
INFO [2019-02-05 10:29:04] [XXX]  Logged in successfully!
INFO [2019-02-05 10:29:04] [XXX]  Saving account progress...
INFO [2019-02-05 10:29:07] [XXX]  User 'chelseakauai' [1/1]
INFO [2019-02-05 10:29:46] [XXX]  Grabbed 30 usernames from 'chelseakauai's `Followers` to do interaction.
INFO [2019-02-05 10:29:46] [XXX]  User 'bertrand.fauconnier' [1/30]
INFO [2019-02-05 10:29:50] [XXX]  Interaction [1/30]  |  Total Interaction: 1
INFO [2019-02-05 10:29:50] [XXX]  Starting to interact by users..
... DOING INTERACTIONS
INFO [2019-02-05 10:30:17] [XXX]  User 'bertrand.fauconnier' [2/30]
INFO [2019-02-05 10:30:20] [XXX]  Interaction [2/30]  |  Total Interaction: 2
INFO [2019-02-05 10:30:20] [XXX]  Starting to interact by users..
... DOING INTERACTIONS
INFO [2019-02-05 10:30:17] [XXX]  User 'bertrand.fauconnier' [3/30]
INFO [2019-02-05 10:30:20] [XXX]  Interaction [3/30]  |  Total Interaction: 3
INFO [2019-02-05 10:30:20] [XXX]  Starting to interact by users..
... DOING INTERACTIONS

Sometimes it grabs another user but it returns to the first one after immediately.
Thanks for your help

**Comment by Tr1pke** [comment]
Got the same. It also kills the session

**Comment by truemarmalade** [comment]
Continues grabbing same initial user even after cycling through multiple targeted accounts. Bugged user does not appear to change between sessions.

**Comment by Aouah** [comment]
Duplicate of #3906 and resolved
