### ISSUE TITLE
Follow doesn't work "Cannot read property 'scrollIntoView' of undefined"

### ISSUE THREAD

**Issue by tourhuntr** [InstaPy/InstaPy#3906]
## Current Behavior
File "/home/pi/projects/InstaPy/instapy/instapy.py", line 2879, in follow_user_followers
    self.logfolder)
  File "/home/pi/projects/InstaPy/instapy/unfollow_util.py", line 892, in get_given_user_followers
    channel, jumps, logger, logfolder)
  File "/home/pi/projects/InstaPy/instapy/unfollow_util.py", line 658, in get_users_through_dialog
    scroll_to_bottom_of_followers_list(browser, dialog)
  File "/home/pi/projects/InstaPy/instapy/unfollow_util.py", line 621, in scroll_to_bottom_of_followers_list
    "arguments[0].children[1].scrollIntoView()", element)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'scrollIntoView' of undefined
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)

Instapy Running on a Raspi 3B+

**Comment by spikeyhair** [comment]
I have this issue too.

**Comment by andreescocard** [comment]
i am using git, git pull and problem solved, or check here https://github.com/timgrossmann/InstaPy/pull/3893#issuecomment-460433431

**Comment by tourhuntr** [comment]
Doesn't work, get 
"selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot read property 'scrollIntoView' of undefined" Error

**Comment by tourhuntr** [comment]
Works now, changed the unfollow_util.py:

https://github.com/timgrossmann/InstaPy/pull/3893/files

**Comment by tourhuntr** [comment]
Doesn't work until the end. Stopps in the middle of nowhere after about 20 followings (it should do 400) with no error message.

**Comment by ishandutta2007** [comment]
It still doesn't scroll and it still shows 

> Failed to load desired amount of users!

**Comment by ishandutta2007** [comment]
We already have issue tracked here https://github.com/timgrossmann/InstaPy/issues/3896

**Comment by Deamoroth** [comment]
even after the correction displays the following message: "Failed to load desired amount of users!"

suddenly begins with a small amount collected and at a certain moment, begins to loop in a single user

**Comment by tourhuntr** [comment]
same here

**Comment by tE3m** [comment]
@uluQulu seems to have a fix for
> Failed to load desired amount of users!

We just gotta wait until he opens a pr.

**Comment by Tr1pke** [comment]
Same here and got the latest version

**Comment by henry0666** [comment]
+1

**Comment by cyberiainformatica** [comment]
+1

**Comment by uluQulu** [comment]
https://github.com/timgrossmann/InstaPy/pull/3910

**Comment by spikeyhair** [comment]
after using the latest version but seems like the issue for "Got 0 likers shuffled randomly whom you can follow:" is still exist.

**Comment by tourhuntr** [comment]
> #3910

doesn't work. Wants to follow the same person time and time again.

**Comment by Banginpadr** [comment]
> > #3910
> 
> doesn't work. Wants to follow the same person time and time again.

i have this same problem. and only try to interact with 20 or 40 people when it should do 200 or 300. something is wrong

**Comment by tourhuntr** [comment]
me too. Only loads about 40 from 200 and trys to follow the same user

**Comment by c0d3x27** [comment]
> > #3910
> 
> doesn't work. Wants to follow the same person time and time again.

ok now is working. just to go the instapy file using terminal and run this command in terminal "git pull" and everything will work. the only problem that doesnt go away is that while it try to scroll down it also start following people. i dont want it to do that. even more because i dont even have the command in my file.  the only work around that is that while it try to follow those users i unfollow them right away.

**Comment by uluQulu** [comment]
Hey @Banginpadr 
Good that it works.

Why don't you configure your simulation setting?
![image](https://user-images.githubusercontent.com/33269249/52301937-1f1f5300-29a5-11e9-8b91-6fb92f2783b8.png)
![image](https://user-images.githubusercontent.com/33269249/52301945-28102480-29a5-11e9-8113-156948cf9db5.png)

https://github.com/timgrossmann/InstaPy#simulation

---

Cheers 😁
---

**Comment by gan-mel** [comment]
Can anyone help with what I have to do to get this to work again? I guess the fix is not pushed to master yet since I tried redownloading and the issue continues- which branch can I take for a fix that works?

doesn't work for me on Mac OSX Chrome 71

Thanks!

**Comment by c0d3x27** [comment]
> Hey @Banginpadr
> Good that it works.
> 
> Why don't you configure your simulation setting?
> ![image](https://user-images.githubusercontent.com/33269249/52301937-1f1f5300-29a5-11e9-8b91-6fb92f2783b8.png)
> ![image](https://user-images.githubusercontent.com/33269249/52301945-28102480-29a5-11e9-8113-156948cf9db5.png)
> 
> https://github.com/timgrossmann/InstaPy#simulation
> ## Cheers 😁

i will try this and let you know if it works. thank you, this will be very helpful because sometimes i have to go out of my house in a rush or something and i don't have the time to run the program, then wait until it start trying to follow "maria" followers then having to unfollow them manually. because all i want is my account to like and comment on "maria" followers.

**Comment by c0d3x27** [comment]
> Hey @Banginpadr
> Good that it works.
> 
> Why don't you configure your simulation setting?
> ![image](https://user-images.githubusercontent.com/33269249/52301937-1f1f5300-29a5-11e9-8b91-6fb92f2783b8.png)
> ![image](https://user-images.githubusercontent.com/33269249/52301945-28102480-29a5-11e9-8113-156948cf9db5.png)
> 
> https://github.com/timgrossmann/InstaPy#simulation
> ## Cheers 😁

you are the man thank you so much i did worked

**Comment by tourhuntr** [comment]
Works again for me. Only copied from the raw file, open the unfollow.py in notepad++ and overrite the content with the copied.

**Comment by Perkins27** [comment]
Still have the following issue "Got 0 likers shuffled randomly whom you can follow" 😣

**Comment by tE3m** [comment]
@Perkins27 that is being worked on: #3931
