### ISSUE TITLE
Quickstart.py on Raspberry Pi: OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by PhilippSPOTTERON** [InstaPy/InstaPy#3907]
## Expected Behavior
Execute Instapy quickstart.py
## Current Behavior
breaks with error: 
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

## InstaPy configuration
Installed new version by "pip3 install instapy" on Debian Stretch (Raspberry Pi),
Selected quickstart template (super_simple_setting_for_crontab.py) copy pasted in new .py file
Ran "python3 quickstart.py"
> OSError: [Errno 8] Exec format error

**Comment by tE3m** [comment]
It seems like your chromedriver binary and your chrome binary don't match. Did you install the correct chromedriver (v2.36 should work with Chromium v65)

**Comment by PhilippSPOTTERON** [comment]
regarding to the new package information, there is no need to install a chromedriver manually.
I just installed the new bundle package with "pip3 install instapy" - according to https://github.com/timgrossmann/InstaPy : "That's it 🍫☕"

(On a second raspberry pi, I did not manage to get Instapy running despite of hours put into it - mostly because of chromedriver issues.)

**Comment by tE3m** [comment]
Yes, but there is a file named ```How_to_Raspberry.md```. There it's described

**Comment by tE3m** [comment]
You don't have to follow all the steps(especially because it still relies on git installation) but in the "for chrome" section it's explained how you can get the driver which comes into the assets folder

**Comment by aliceEddie** [comment]
Had the same issue. Installing the chromedriver manually inside home/cherry/instapy/assets like it's explained in `How_to_Raspberry.md` fixed it for me.

EDIT: actually had another problem after this running `python3 myScript.py`. What has got it running again was copying the assets folder (with chromedriver) to /home/cherry/pi/.local/lib/python3.7/site-packages/ 

there was no assets folder for some reason, so also no chromedriver.

**Comment by PhilippSPOTTERON** [comment]
Thanks that was very helpful!
For everybody having the same issue:
With the new package, you just need to do the following steps:

* Installed new version by "pip3 install instapy" on Debian Stretch (Raspberry Pi),
* go to /home/pi/InstaPy/assets
> from https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Raspberry.md
* just do the following steps:
1) wget https://github.com/electron/electron/releases/download/v3.0.0-beta.5/chromedriver-v3.0.0-beta.5-linux-armv7l.zip
2) unzip chromedriver-v3.0.0-beta.5-linux-armv7l.zip
3) chmod 755 chromedriver
4) chmod +x chromedriver
5) sudo apt-get remove chromium
* edit thenameofyourscripttemplate.py and add your username and password
* Run Instapy by "python3 thenameofyourscripttemplate.py" in the right directory.

If you want to have your script executed by crontab automatically, do not forget to add "headless_browser=True" in it, otherwise there will by another chromdriver error!

Hope that helps others, too,
thanks again for solving.

**Comment by tE3m** [comment]
Hi @PhilippSPOTTERON, I think you can close this issue now since it has been solved, right?
