### ISSUE TITLE
Where is the log folder?

### ISSUE THREAD

**Issue by augustomaf** [InstaPy/InstaPy#3908]
## Expected Behavior
Before the update all logs (follows, unfollows, likes) where saved in the log folder.

## Current Behavior
I cant find the folder or the general file where all logs where saved.

**Comment by TarekJ03** [comment]
Look in readme.md under workspace folder. It has been changed due to the huge update.

**Comment by tE3m** [comment]
Look in readme.md under workspace folder. It has been changed due to the huge update. Generally it's in your user's home folder.

**Comment by Tr1pke** [comment]
In InstaPy/logs ?

**Comment by tE3m** [comment]
@Tr1pke I think what's meant is that changes aren't saved in the old logs folder anymore, except you use 
```
set_workspace(path=path/to/InstaPy/)
```
Without that it'll save it to ~/InstaPy/logs
(your user's home directory/InstaPy/logs)
