### ISSUE TITLE
 Message: 'chromedriver' executable may have wrong permissions.

### ISSUE THREAD

**Issue by RealMakAttak** [InstaPy/InstaPy#391]
I have tried everything to get rid of this error when I try to run any InstaPy script.

selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

I run with administrator cmd on windows 10, with full permissions (although the boxes are greyed out so im guessing those permissions are inherited)

What is wrong?!? Please help.

Thanks.

**Comment by onyxim** [comment]
Try to [run with new docker micro services](https://github.com/timgrossmann/InstaPy#running-with-docker-microservices-manual). It completely solves all chromedriver problem.

**Comment by RealMakAttak** [comment]
I will look in to that, thank you very much! @onyxim

**Comment by dc500** [comment]
If anyone has this problem on Mac try ` brew install chromedriver`

**Comment by hajaja** [comment]
for me (using linux), the problem is solved by installing geckodriver

**Comment by guymzee** [comment]
All my tinker has left me with the same problem, I either get a can not find Chrome binary or the permissions error.  Did anyone figure this problem out ?

**Comment by hecklerponics** [comment]
@guymzee same.   [this](https://gist.github.com/ziadoz/3e8ab7e944d02fe872c3454d17af31a5) looks promising, but I can't seem to resolve the `Message: 'chromedriver' executable may have wrong permissions.` error :(

**Comment by hecklerponics** [comment]
@guymzee navigate to the dir your driver is in and type this: `chmod a+x chromedriver` 

This solved the permissions issue for me, but now I'm having to troubleshoot this error `chrome driver unexpectedly exited. Status code was: 127` :\

**Comment by AlanInsam** [comment]
I got also the error 'chromedriver' executable may have wrong permissions anyone knows how to solve?

**Comment by shnigi** [comment]
Got this issue when running Google-Chrome on Jenkins server. I had to download latest chromedriver here: http://chromedriver.chromium.org/downloads I accidentally downloaded wrong version first, then I moved chromedriver to /usr/local/bin and set Jenkins to its owner, `chown jenkins /usr/local/bin/chromedriver` and nooow it works.

**Comment by gustafsom** [comment]
I performed the above procedure: 

> navigate to the dir your driver is in and type this: chmod a + x chromedriver

But now the following error occurs: `[Errno 8] Exec format error`

**Comment by hecklerponics** [comment]
There's no space between a+x

**Comment by gtkpr** [comment]
i'm getting the exact same error, `'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home` when trying to execute a spider that uses selenium on my CentOS 7 VPS

**Comment by gtkpr** [comment]
@hecklerponics on my CentOS 7 VPS i was getting the same error and i tried `chmod a+x chromedriver`, but now i get the following error:

`selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 3.10.0-862.3.3.el7.x86_64 x86_64)`

**Comment by hecklerponics** [comment]
@gtkpr  I don't know much about CentOS, but when I was using a Conda environment with it to run on an EC2+Ubuntu I had to make sure the chrome binary was accessible by the environment.  Also, make sure you're using the binary for chrome and not the .exe.

**Comment by gtkpr** [comment]
i think i figured it out... move `chromedriver` to `/usr/local/bin`.

but now i'm getting the following error: `'chromedriver' executable needs to be in PATH.`

**Comment by hecklerponics** [comment]
@gtkpr that's the error I got when the environment couldn't access the driver.  Are you declaring the path to the chromedriver here: `driver #= webdriver.Chrome('PATH/TO/chromedriver)` ?

**Comment by gtkpr** [comment]
@hecklerponics 
Sorry, i forgot to update its location in my script.

So once I moved it to `/usr/local/bin` and then updated the file location in my python script, then I started getting the following error:

`selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary`

And this absolutely baffles me, unless it means i need to download and install Chrome/Chromium?!?!?!

[1. update]

Just found [this thread](https://stackoverflow.com/questions/43287203/selenium-gives-unknown-error-cannot-find-chrome-binary-when-running-chrome-dr#43306178), which affirms my belief, so I'm going to install one or the other and see if that fixes the problem!

[2. update]

So I installed Chrome via the official repository. Now it's throwing the following error:
`DevToolsActivePort file doesn't exist`

When I try to launch Google Chrome on the VPS via SSH, I get an error `[83526:83526:0622/212649.156252:ERROR:zygote_host_impl_linux.cc(88)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.` which links to a page that is no longer available...

When I try to open Chrome with the `--no-sandbox` parameter, I then get the error: `(google-chrome-stable:85573): Gtk-WARNING **: cannot open display:
[0622/221013.556327:ERROR:nacl_helper_linux.cc(310)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly`

**Comment by gtkpr** [comment]
@hajaja but dont u need firefox to use geckodriver? for some reason i cant figure out how to download firefox on my centos 7 vps and get it working :(

**Comment by Sooryasanand** [comment]
> for me (using linux), the problem is solved by installing geckodriver

Where should I put the geckodriver?

**Comment by keerat21** [comment]
> **'chromedriver_win32' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home**
pls tell me the fix

**Comment by keerat21** [comment]
> > **'chromedriver_win32' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home**
> > pls tell me the fix

move the Chrome webdriver to Scripts then no need to enter path

> **browser = webdriver.Chrome()**

**Comment by LOH07** [comment]
> move the Chrome webdriver to Scripts then no need to enter path

Thank you very much.
YOU SAVED MY DAY!
I was getting the error:
"geckodriver" executable may have wrong permissions
