### ISSUE TITLE
Already used InstaPy before pip install instapy? <- Not Working

### ISSUE THREAD

**Issue by daliborg** [InstaPy/InstaPy#3915]
Hi Team,

On the page [https://github.com/InstaPy/instapy-quickstart](url) link
[https://github.com/timgrossmann/InstaPy/migrating-your-data-to-the-workspace-folder](url) is not working.
Can you please check it?

**Comment by timgrossmann** [comment]
@daliborg Thank you for letting us know. I'll fix it right away!
Here's the right link
https://github.com/timgrossmann/InstaPy#migrating-your-data-to-the-workspace-folder
