### ISSUE TITLE
Suspicious login attempt and how can I bypass!

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#3917]
Hello , I have a problem with instagram , I have one acount in instagram and I forgot my email password and now when I login to my instagram account instagram had an error this error is ((suspicious login attempt),(we’ve detected an unusual login attempt)) if it possible  can someone  tell me how can I by pass this error ?  I really need my account and I really appreciate. 
Best regards.

**Comment by tE3m** [comment]
Look in readme.md. bypass_suspicious_attempt is explained there.

**Comment by DemOnJR** [comment]
turn off the 2-step verification, and try again with bypass.

**Comment by groundd** [comment]
Hi i look in readme.md. And i install insta py but i have a problem in my insta py folder I don’t have assets folder can some body help me :((

**Comment by groundd** [comment]
If some one can help me for how to install insta py i really appreciate him i fllow all instraction but finally i cant run can some body send video for install insta py for windows 10 i see every video in you tube but finally I can’t login!! If it possibel please help me

**Comment by ghost** [comment]
> Look in readme.md. bypass_suspicious_attempt is explained there.

Hi i look in readme.md. And i install insta py but i have a problem in my insta py folder I don’t have assets folder can some body help me :((

**Comment by ghost** [comment]
> turn off the 2-step verification, and try again with bypass.

some one can help me for how to install insta py i really appreciate him i fllow all instraction but finally i cant run can some body send video for install insta py for windows 10 i see every video in you tube but finally I can’t login!! If it possibel please help me

**Comment by tE3m** [comment]
@groundd how did you install? Did you follow a guide?

**Comment by groundd** [comment]
> @groundd how did you install? Did you follow a guide?

I use this video 
https://m.youtube.com/watch?v=L6VDttSAt2k
And follow all instruction do you have any video that can help me?

**Comment by ghost** [comment]
@TarekJ03 
I use this video
https://m.youtube.com/watch?v=L6VDttSAt2k
And follow all instruction do you have any video that can help me?

**Comment by ghost** [comment]
@TarekJ03 I really appreciate you for helping me finally I solve my problem and i run instapy but now I have another question i read , readme.md , bypass_suspicious_attempt but when i run insta py and enter my username and password I don’t know where should i paste this code ((session = InstaPy(username=insta_username, password=insta_password, bypass_suspicious_attempt=True))) i mean in wich line in quickstart.py (( at the end i paste ))should i paste this code? and is it necessary to enter my username and password here i mean in this code again? And should i do any thing else if it possible please say what should i do . Best regards 
""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = ''  # <- enter username here
insta_password = ''  # <- enter password here

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                    min_followers=45,
                                    min_following=77)

    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])

    # activity
    session.like_by_tags(["natgeo"], amount=10)

**Comment by tE3m** [comment]
You simply need to add `, bypass_suspicious_attempt` after `headless_browser=True`.

**Comment by ghost** [comment]
@TarekJ03 that program driving me crazy 😭
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = myyyyy userrrrrnameeeeee'' # <- enter username here
insta_password = 'myyyyyy passsssworddddd' # <- enter password here

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=Myyyyyyy usernameeee,
password=Myyyyyyyyyyy passwordddddd,
headless_browser=Ture, bypass_suspicious_attempt=Ture)

with smart_run(session):
""" Activity flow """
# general settings
session.set_relationship_bounds(enabled=True,
delimit_by_numbers=True,
max_followers=4590,
min_followers=45,
min_following=77)

```
session.set_dont_include(["friend1", "friend2", "friend3"])
session.set_dont_like(["pizza", "#store"])

# activity
session.like_by_tags(["natgeo"], amount=10)
```


Dear my friend i have 2 question i fllow all things you say i set ((headless_browser=True)) and after that type bypass_suspicious_attempt=Ture and run application but in python shell says (cookie file not found , creating cookie...
Instagram detected an unusual login attempt
A security code was send to your email
Type security code here:—— )) after i see this message what should i do😭?(( I’m really confused please say it in simple way ))
And my another question are the codes on the top of screen is it correct? Thanks for helping me

**Comment by tE3m** [comment]
You set `bypass_suspicious_attempt=Ture`, but it should be `True` instead of `Ture`. About your 2. question: please read the docs, it's explained there.

**Comment by ghost** [comment]
@TarekJ03 i’m really sorry my friend🌹 i write true, but when i want to wite it here to show to you i write ture here but i want to know when i run this application after i run when i should  change this sentense to false ? 

If you're having issues with the "we detected an unusual login attempt" message, you can bypass it setting InstaPy in this way:

session = InstaPy(username=insta_username, password=insta_password, bypass_suspicious_attempt=True)
bypass_suspicious_attempt=True will send the verification code to your email, and you will be prompted to enter the security code sent to your email. It will login to your account, now you can set bypass_suspicious_attempt to False bypass_suspicious_attempt=False and InstaPy will quickly login using cookies.
 I’m really appreciate you💐💐

**Comment by tE3m** [comment]
Right after the cookie has been created, you can set it to false.

**Comment by ghost** [comment]
@TarekJ03 ![llllll](https://user-images.githubusercontent.com/47280437/52801623-8f0f9680-3093-11e9-9a85-7d1507a25b56.jpg) according to the picture should I change(( bypass login to False ))and press F5 again or do any thing else?
when I change to false and press F5 I face with this picture
![llllll2](https://user-images.githubusercontent.com/47280437/52804261-0bf13f00-3099-11e9-8f13-fc4621951291.jpg)
finally I don't know what should I do!!!

**Comment by tE3m** [comment]
You did everything correctly.Seems like there is a problem with the cookie usage/creation.

**Comment by ghost** [comment]
@TarekJ03 according to the your answer we can’t Bypass Suspicious Login Attempt by instapy finally I really appreciate you.
Good luck.

**Comment by anabitff** [comment]
Hi dear 

Did you know suspicious login attempt that out but im sad. I still didn’t work because im have changing new number than old number remain on my account. I wanna back right now 😔💔 ... now im need security code that before old number it when im over 😭. Just im disappointed. Please help me! You believe me though im waiting ..

**Comment by maaxzzz** [comment]
![image](https://user-images.githubusercontent.com/55713712/65453147-fa36fd80-de18-11e9-9dc1-f7eef7a5b70b.png)
someone help me?

**Comment by maaxzzz** [comment]
now it is - 
![image](https://user-images.githubusercontent.com/55713712/65453822-55b5bb00-de1a-11e9-8b7d-be1b2f793b7d.png)

**Comment by raunakshukla** [comment]
guysss please help me i really want to bypass suspicious login attemp pi dont have access to email or phone number please helpppppp

**Comment by pedro14701** [comment]
I’m one of the thousands of IG users affected by this farce, I’ve been lurking on this sub for a week now, searching on the web, reading every available bit of info, trying to find/contact any HUMAN that can actually help, but now I’m starting to realize my problem will not be easily solved, i was referred to Marieconsultancyoz@gmail com Also known as Marie_consultancy on 1nstagram. she was able to render a proper and genuine services to me by recoveing back my locked 1nstagram/ Facebook account successfully, you can also reach out to her

**Comment by Lindamckay** [comment]
I' ve got unlimited access to my husbands iPhone and PC and also have his activities in check thanks to this dude who is a Russian Hacker by his name Yuri I got introduced to from the UK who helped my friend boost her credit score. His assistance really meant a lot to me. I got access to my
husband's cell phone, WhatsApp calls, without his knowledge with just his cell phone number this badass did everything remotely, I don't know.if it's right to post his contact but I promised him referrals, alot of fake ass out here, also someone might need his help so welp. I'm grateful to Yuri.
Email is wisetechacker @gmail com
Good work always speak for itself, you should contact him!'!!

**Comment by Lindamckay** [comment]
My husband has been frequently deleting all messages for the last couple of days from his phone and he didn’t know i was peeping at him, then i asked him why he was deleting all messages from his phone but he claimed that his phone memory was full and needed more space. Immediately i went in search of a hacker who can get me deleted information and contents from my husband’s phone and luckily for me i came across this reputable ethical hacker , this hacker got the job done for me and provided me with results and i saw that my husband has been lying to me. He was simply deleting all pictures, call logs, chats and text messages between him and his secret lover so i wont get to see what he has been doing at my back. Thank God for reputable hackers who are ready to help. I must say am really impressed with the services i got from The hacker Detective and am here to say a very big thank you: contact him on (( hack4wise @gmail com))
