### ISSUE TITLE
Feature request - pull out number of followers

### ISSUE THREAD

**Issue by daliborg** [InstaPy/InstaPy#3918]
Hi Team,

Did you think about to add a function which will pull out the number of the current follower (I think this part is already present when loading script) and save this data to some for example .csv file, which can be used to import this data to some graphing tool so we can graph for analysis or present to somebody account growth trends?

Thank you!

**Comment by DemOnJR** [comment]
if you need analysis use the various websites and if you need your own script buy this: https://phpanalyzer.com/demo/ or https://phpstatistics.com/demo/

**Comment by tE3m** [comment]
@daliborg there are both `.csv` files and a visualizer for InstaPy already available. The `.csv` files are in `InstaPy/logs/user/`.@converge created the visualizer.

**Comment by daliborg** [comment]
Hi @TarekJ03, 
Thanks for the info, I am checking it.

**Comment by daliborg** [comment]
Hi @TarekJ03,
Thanks for reply, but I don't see there any .csv file with the number of current follower per day/per script run? What is the name of the file you are referring to?
