### ISSUE TITLE
ImportError: No module named 'instapy_chromedriver'

### ISSUE THREAD

**Issue by nikospaz** [InstaPy/InstaPy#3920]
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/home/pi/Projects/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 71, in <module>
    from .browser import set_selenium_local_session
  File "/home/pi/Projects/InstaPy/instapy/browser.py", line 16, in <module>
    from .file_manager import get_chromedriver_location
  File "/home/pi/Projects/InstaPy/instapy/file_manager.py", line 11, in <module>
    from instapy_chromedriver import binary_path
ImportError: No module named 'instapy_chromedriver'

In raspberry pi i get this error

**Comment by aliceEddie** [comment]
Try this: #3907

**Comment by MalteIwanicki** [comment]
same problem

**Comment by aliceEddie** [comment]
from @PhilippSPOTTERON
> Thanks that was very helpful!
> For everybody having the same issue:
> With the new package, you just need to do the following steps:
> 
>     * Installed new version by "pip3 install instapy" on Debian Stretch (Raspberry Pi),
> 
>     * go to /home/pi/InstaPy/assets
> 
> 
> > from https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Raspberry.md
> 
>     * just do the following steps:
> 
> 
>     1. wget https://github.com/electron/electron/releases/download/v3.0.0-beta.5/chromedriver-v3.0.0-beta.5-linux-armv7l.zip
> 
>     2. unzip chromedriver-v3.0.0-beta.5-linux-armv7l.zip
> 
>     3. chmod 755 chromedriver
> 
>     4. chmod +x chromedriver
> 
>     5. sudo apt-get remove chromium
> 
> 
>     * edit thenameofyourscripttemplate.py and add your username and password
> 
>     * Run Instapy by "python3 thenameofyourscripttemplate.py" in the right directory.
> 
> 
> If you want to have your script executed by crontab automatically, do not forget to add "headless_browser=True" in it, otherwise there will by another chromdriver error!
> 
> Hope that helps others, too,
> thanks again for solving.

my installation was at /home/cherry/pi/.local/lib/python3.7/site-packages/ for some reason. But the explanation above should fix it

**Comment by nikospaz** [comment]
i get this now OSError: [Errno 8] Exec format error: '/home/pi/.local/lib/python3.7/site-packages/instapy_chromedriver/chromedriver_linux64'

**Comment by nikospaz** [comment]
i did everything from the beginning and i get this ImportError: cannot import name 'binary_path' from 'instapy_chromedriver' (unknown location)

**Comment by aliceEddie** [comment]
could you post the path where instapy is looking for chromedriver?

I had the same error and for me it was beacuse Instapy was looking for the chromedriver in `/home/pi/.local/lib/python3.7/site-packages/` instead of `home/py/InstaPy`

I copied the assets folder (with chromedriver)from `home/py/InstaPy` to the path in the error message (in my case `/home/pi/.local/lib/python3.7/site-packages/`) and it fixed the issue.

**Comment by nikospaz** [comment]
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/home/pi/Projects/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 71, in <module>
    from .browser import set_selenium_local_session
  File "/home/pi/Projects/InstaPy/instapy/browser.py", line 16, in <module>
    from .file_manager import get_chromedriver_location
  File "/home/pi/Projects/InstaPy/instapy/file_manager.py", line 11, in <module>
    from instapy_chromedriver import binary_path
ImportError: cannot import name 'binary_path' from 'instapy_chromedriver' (unknown location)

**Comment by gitpatrickhub** [comment]
From the command line type:
sudo pip3 install instapy -U

Or comment out the import line for the instapy_chromedriver in the file_manager.py file

**Comment by tE3m** [comment]
Guys! On RPi the reason this doesn't work is that new chromedriver versions are only available as 64-bit versions. A Raspberry requires 32-bit binaries. That's why you need to put a chromedriver in InstaPy/assets, else it'll use the one installed with InstaPy, which is v2.44. That version only has a 64-bit chromedriver. Download the chromeedriver like it is explained in How_to_Raspberry:
```
cd InstaPy/assets/
wget <link>
unzip chromedriver-....
```

**Comment by nikospaz** [comment]
it doesn't work, i did it, the only one that worked was @gitpatrickhub solution

**Comment by tE3m** [comment]
Are you sure that you put the chromedriver inside  ~/InstaPy/assets ?

**Comment by nikospaz** [comment]
yes..

**Comment by DemOnJR** [comment]
you get this error on ubuntu server?

**Comment by nikospaz** [comment]
no, on raspberry

**Comment by DemOnJR** [comment]
hmm i get the same error on ubuntu server, but i find the problem is python or ram memory (i recommand 2GB+).
Now i use ubuntu desktop with "python 2.7.15rc1" and is work fine, no errors.

**Comment by nikospaz** [comment]
in another rasp i don't have issues

**Comment by DemOnJR** [comment]
you use the same veriosn of instapy on the another rasp?

**Comment by nikospaz** [comment]
yes

**Comment by DemOnJR** [comment]
i dont know i got the same problem with python3.7 , check python, reinstall it and try again.

**Comment by jeremycjang** [comment]
This issue appears to affect Raspberry Pi users (maybe others too?) after the last update

**Comment by jeremycjang** [comment]
@nikospaz Do you mean you fixed it on RPi by using ```sudo pip3 install instapy -U``` , or you mean you fixed it by commenting out the ```instapy_chromedriver``` line?

**Comment by tE3m** [comment]
@jeremycjang it probably effects everyone who moved to the `pip` installation. `instapy-chromedriver` is a dependency of the pip version. It's basically a chromedriver that gets installed automatically, and the version of `instapy-chromedriver` is the chromedriver's version.

**Comment by breuerfelix** [comment]
I will add 2.33 and 2.36 to instapy-chromedriver so as a Pi user you have to manually install instapy-chromederiver==2.33.  
But one Problem is, even thought you have your own chromedriver in the assets folder, it tries to import the instapy-chromedriver one. I will make a PR that it only tries to important from that package if there is NONE chromedriver in assets.  
So on Pi you don't have to comment that line out, you can just put your own chromedriver in the assets folder and you are done.

**Comment by breuerfelix** [comment]
could you please do the follow now:

`pip3 install --user instapy-chromedriver==2.33`

test again, see if it works.

if not:

`pip3 install --user instapy-chromedriver==2.36`
see if it works. Maybe you have to add the `--user` to the command but maybe you have to, just try both :)

I hope the PR is gonna get marched today so using your own chromedriver gets easier.

**Comment by nikospaz** [comment]
@jeremycjang i mean commenting the chromedriver

**Comment by nikospaz** [comment]
@scriptworld-git 
pip3 install --user instapy-chromedriver==2.36

This one worked, i will check everything, and i will repost if everything works well. For now this was my solution! Thank you!

**Comment by breuerfelix** [comment]
@nikospaz glad that it works ! that's a really nice and easy solution for Pi :)

**Comment by escariao** [comment]
> 
> 
> could you please do the follow now:
> 
> `pip3 install --user instapy-chromedriver==2.33`
> 
> test again, see if it works.
> 
> if not:
> 
> `pip3 install --user instapy-chromedriver==2.36`
> see if it works. Maybe you have to add the `--user` to the command but maybe you have to, just try both :)
> 
> I hope the PR is gonna get marched today so using your own chromedriver gets easier.

@uluQulu I did exactly all the procedures, include How _to_Raspberry,md. I created a second installation from scratch, "Second". But now this comes

```
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-02-07 14:20:12] [my_login.py]  Using built in instapy-chromedriver executable (version 2.36)
Traceback (most recent call last):
  File "my_login.py", line 20, in <module>
    nogui=False)
  File "/home/pi/Projects/Second/instapy/instapy.py", line 276, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/Second/instapy/instapy.py", line 326, in set_selenium_local_session
    self.logger)
  File "/home/pi/Projects/Second/instapy/browser.py", line 123, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
```

**Comment by nikospaz** [comment]
Did you set the right workspace?

**Comment by escariao** [comment]
I only have 1... At Raspberry I left it like this... How to change?

**Comment by escariao** [comment]
> 
> 
> Did you set the right workspace?

I only have 1... At Raspberry I left it like this... How to change?

**Comment by nikospaz** [comment]
set_workspace('path to your instapy installation')

**Comment by escariao** [comment]
> set_workspace

Why do not templates have this settings?

**Comment by tE3m** [comment]
@escariao because the templates haven't been updated. Some don't even include `smart_run`. It's only included in quickstart.py atm.

**Comment by escariao** [comment]
I added, but the same error continues.     
session.set_workspace('/home/pi/Projects/InstaPy/')

**Comment by nikospaz** [comment]
not session
just set_workspace('/home/pi/Projects/InstaPy/')

**Comment by escariao** [comment]
> 
> 
> not session
> just set_workspace('/home/pi/Projects/InstaPy/')

@nikospaz Thank you. but it only worked when I added this:

```
from instapy import smart_run
from instapy import set_workspace

set_workspace('/home/pi/Projects/Instapy')
```
Thank you, and thanks @TarekJ03 , this made me understand that this imports was missing...

Now its ok.

**Comment by nikospaz** [comment]
nice! yes you have to import them, sorry for not telling

**Comment by tE3m** [comment]
I think someone should update all templates provided on GitHub🤔

**Comment by escariao** [comment]
> 
> 
> I think someone should update all templates provided on GitHubthinking

Lets go!

**Comment by breuerfelix** [comment]
perfect so I might close this issue again if its working :)
