### ISSUE TITLE
If this project Defunct?

### ISSUE THREAD

**Issue by jxm90** [InstaPy/InstaPy#3926]
Everything I try this eventually crashes or errors out, even while using the example simple_but_effective quickstart template. My question... is this project defunct, should I spend anymore time trying to get it to work? Just to be thorough i'll include my latest crash info

> Traceback (most recent call last):
>   File "simplyeffective.py", line 48, in <module>
>     interact=True, sleep_delay=240)
>   File "/home/joe/InstaPy/instapy/instapy.py", line 3053, in follow_user_followers
>     self.logfolder)
>   File "/home/joe/InstaPy/instapy/unfollow_util.py", line 998, in get_given_user_followers
>     logger, logfolder)
>   File "/home/joe/InstaPy/instapy/unfollow_util.py", line 745, in get_users_through_dialog
>     scroll_to_bottom_of_followers_list(browser, dialog)
>   File "/home/joe/InstaPy/instapy/unfollow_util.py", line 707, in scroll_to_bottom_of_followers_list
>     "arguments[0].children[1].scrollIntoView()", element)
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
>     'args': converted_args})['value']
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'scrollIntoView' of undefined
>   (Session info: chrome=72.0.3626.81)
>   (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.15.0-45-generic x86_64)
>

**Comment by miguelrodriguezpro** [comment]
pip -U instapy
update it!

**Comment by miguelrodriguezpro** [comment]
pip -U Instapy*

**Comment by GreatTimeBand** [comment]
I too had problems with the new install after pulling from git (had originally installed via git).  I ended up reverting back to the old version and have had no issues since.

**Comment by GreatTimeBand** [comment]
everyone is saying to install via pip, though I was having problems with that too, possibly due to still having the old install and possibly due to multiple python versions.  gave up after a couple hours of fiddling

**Comment by tE3m** [comment]
@miguelikedeveloper the actual command would be 
```
pip install instapy -U
```

**Comment by CharlesCCC** [comment]
To answer you question, no this project is not defunct, it is awesome and lots of people are using it. 
if the pip install didn't working for you, try to clone the repo to your locally and run it.

**Comment by tE3m** [comment]
@CharlesCCC that `scrollintoview` error has already been fixed, so it should work now...

**Comment by jxm90** [comment]
I got it running much better after running a git pull update. This project is awesome. I'm going to try installing via pip to see if I can get smoother results.

**Comment by CharlesCCC** [comment]
@jxm90 please close the issue when the problem resolved. thank you for the feedback.
