### ISSUE TITLE
Keeps Following the same accounts

### ISSUE THREAD

**Issue by sohumsanu** [InstaPy/InstaPy#3928]
I have set it to follow followers from an multiple accounts that have 30k+ followers but it keeps refollowing the same account. I'm not really sure why its doing this or how to fix it. 

Does anyone have any suggestions?

Thanks!!

![code_screenshot](https://user-images.githubusercontent.com/39429855/52394455-3c185c80-2a5f-11e9-81eb-564f613b3824.png)

**Comment by unipython** [comment]
I have kind of the same issue here, keeps liking the pictures of the same accounts over and over.

**Comment by sionking** [comment]
@uluQulu made changes in grabbing followers of account, probably a bug that take the same accounts.
anyway it is not follow it skip ...

**Comment by uluQulu** [comment]
@sionking, 
If you look at the changes at #3910, you'll easily see that I've changed **only** the XPath of the dialog address with correct one.
![image](https://user-images.githubusercontent.com/33269249/52404214-dde08d80-2ae1-11e9-82fd-8e35c1301423.png)

Other changes occurred are **visual changes** that intended for the _Progress Tracker_ addition.

---

@awesome205,
 Does it always behave so?
Make sure you have updated successfully.

---

Cheers 😁
---

**Comment by sohumsanu** [comment]
@uluQulu 

I believe I have updated everything successfully. It behaves like this not all the time but half the time it keeps getting in a loop like this.
