### ISSUE TITLE
Issue with proxy (wo pw)

### ISSUE THREAD

**Issue by nbgabriel** [InstaPy/InstaPy#3933]
Hello there! 

Im having an issue with the new version and proxy (without password). 

I try in two ways:
1) session = InstaPy(username="user", password="pwd",proxy_address='11.22.33.44',proxy_port=8080)
2) python quickstart.py --proxy-address 11.22.33.44 --proxy-port 8888.

The message in both cases is the same:
Message: invalid argument: cannot parse capability: proxy
from invalid argument: Specifying 'socksProxy' requires an integer for 'socksVersion'

Any Ideas? 
Thanks!

**Comment by sionking** [comment]
comment out socksProxy in browser file

**Comment by nbgabriel** [comment]
Sionking!, hello!

Do you mean in browser.py ?.

If it is there, i cant fint the socksProxy line, i found this:
                #prox.socks_proxy = proxy
I commented, but is not working, also i try to search the socksproxy in some .py but, no luck:
.../site-packages/instapy# cat *.py | grep -i socksProxy
.../site-packages/instapy# cat *.py | grep -i socksversion
.../site-packages/instapy# 

Thanks!

**Comment by nbgabriel** [comment]
Sionking!

I've made a downgrade of chromedriver, and now proxy is working, i do not know if some other functionality are going to fail, but know is working, i will let you know if i found some complications. 

thanks!

**Comment by xnorcode** [comment]
Is it still working?
if yes, which chromedriver version you used?
how did you change the chromedriver, I can't get it to change by downloading and adding other chromedriver into the assets/ folder...?

**Comment by nbgabriel** [comment]
> Is it still working?
> if yes, which chromedriver version you used?
> how did you change the chromedriver, I can't get it to change by downloading and adding other chromedriver into the assets/ folder...?

Xnor, hello, i've downloaded the version 2.42 from the chromedriver site. Then i search "chromedriver" in my pc. and was in the virtual env that i've created. In my case, was in:
/home/myuser/Downloads/venv/lib/python2.7/site-packages/instapy_chromedriver/chromedriver

So i simply replace that file for the downloaded one. 

Still working, and i do not notice any issue at all.

**Comment by xnorcode** [comment]
> > Is it still working?
> > if yes, which chromedriver version you used?
> > how did you change the chromedriver, I can't get it to change by downloading and adding other chromedriver into the assets/ folder...?
> 
> Xnor, hello, i've downloaded the version 2.42 from the chromedriver site. Then i search "chromedriver" in my pc. and was in the virtual env that i've created. In my case, was in:
> /home/myuser/Downloads/venv/lib/python2.7/site-packages/instapy_chromedriver/chromedriver
> 
> So i simply replace that file for the downloaded one.
> 
> Still working, and i do not notice any issue at all.

@nbgabriel thanks, I was also using v2.42 until now and everything was working perfectly!
@uluQulu @timgrossmann Maybe we could add chromedriver v2.42 in instapy-chromedriver package?

**UPDATE:**
a) tested v2.42 + proxy on +headless off => worked
b) tested v2.42 + proxy on + headless on => error: Unable to locate element: {"method":"xpath","selector":"//select[@class='hztqj']/option[text()='English']"}
c) tested v2.42 + proxy off + headless off => worked
d) tested v2.42 + proxy off + headless on => worked

**Comment by nbgabriel** [comment]
> > > Is it still working?
> > > if yes, which chromedriver version you used?
> > > how did you change the chromedriver, I can't get it to change by downloading and adding other chromedriver into the assets/ folder...?
> > 
> > 
> > Xnor, hello, i've downloaded the version 2.42 from the chromedriver site. Then i search "chromedriver" in my pc. and was in the virtual env that i've created. In my case, was in:
> > /home/myuser/Downloads/venv/lib/python2.7/site-packages/instapy_chromedriver/chromedriver
> > So i simply replace that file for the downloaded one.
> > Still working, and i do not notice any issue at all.
> 
> @nbgabriel thanks, I was also using v2.42 until now and everything was working perfectly!
> @uluQulu @timgrossmann Maybe we could add chromedriver v2.42 in instapy-chromedriver package?
> 
> **UPDATE:**
> a) tested v2.42 + proxy on +headless off => worked
> b) tested v2.42 + proxy on + headless on => error: Unable to locate element: {"method":"xpath","selector":"//select[@Class='hztqj']/option[text()='English']"}
> c) tested v2.42 + proxy off + headless off => worked
> d) tested v2.42 + proxy off + headless on => worked

Nice test!
