### ISSUE TITLE
Raspberry Unfollow Issue

### ISSUE THREAD

**Issue by mafredas** [InstaPy/InstaPy#3935]
Hi,

After the huge update, i observe that the unfollow process doesn't work properly. I **have update my raspberry and my code**, but the unfollowing returns the following report 

>Starting to unfollow users..
>Unfollowing the users followed by InstaPy
>Retrieving live `Followers` data of........
>Found 0 loyal followers!  ~will not unfollow them
>Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 0
>There are no any users available to unfollow
>Total people unfollowed : 0
 
After that session closed. The following process works perfectly!!

Any idea?

**Comment by aliceEddie** [comment]
Did you copy the log files from the old installation to the new workspace destination?

**Comment by mafredas** [comment]
Yes, i have been copied all old logs at the new workspace...Also, i ran a new follow process (after update) but neither unfollow the new users. Returns the same message.

**Comment by tE3m** [comment]
@mafredas if I'm right, InstaPy doesn't interact with the logs. Those are only there for you to read. InstaPy actually uses `db`, if I'm not wrong.

**Comment by mafredas** [comment]
@TarekJ03 thanks for your reply..After the latest update i have forgotten to transfer the old db file at the new workspace but when realized that and transfered that the issue still exists..I can’t unfollow all the old followers. I use the same script!! However, I  do not know if this mistake affects my unfollow process...
