### ISSUE TITLE
Unfollow function broken - list index out of range

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#3938]
I’ve tried all 4 methods at this point and it would not unfollow, giving this error over and over
![b2a2317d-2d50-4a03-85d0-3647430aa72e](https://user-images.githubusercontent.com/36073534/52453204-3df02780-2b14-11e9-8b72-7da9319909d5.jpeg)

**Comment by Tachenz** [comment]
This is the config I am using in the screenshot above: session.unfollow_users(amount=340, allFollowing=True, style="LIFO", unfollow_after=24*60*60, sleep_delay=2450)

**Comment by Tachenz** [comment]
Or sometimes it will pick up 42 users only to unfollow (but never more than that)

**Comment by Tachenz** [comment]
Looks like it is stuck for good on the only method out of four - which works at least i  this way. Not sure why 42. 
Unfollow feature is broken. Summoning the gods of instapy @timgrossmann @sionking @uluQulu  for help!
Look:
![9823c6bb-ff80-40fa-b8cf-922891908548](https://user-images.githubusercontent.com/36073534/52489944-99142f80-2b91-11e9-866b-92dd7cab2a3c.jpeg)

**Comment by Tachenz** [comment]
Does it have to do with transition to DB from csv? 
It stubbornly picks only 42 users to unfollow, whatever the number set is (and giving the errors as per the last screenshot)

**Comment by aliceEddie** [comment]
have you found a solution to this? I have a similar problem since transitioning to db and `pip install`.

**Comment by Tachenz** [comment]
No solution at all... Unfollow is a complete mess at the moment.

don’t know why anyone else is not flagging this issue as critical :)

**Comment by tE3m** [comment]
Strange... unfollowing works perfectly fine for me... :thinking:

**Comment by Tachenz** [comment]
@tarekj03 which method are you using? Can you please share?

**Comment by Tachenz** [comment]
@uluQulu - you sound like you know something and not telling us :D

**Comment by Tachenz** [comment]
The only way I can make it work if I am doing allFollowing=True modifier AND then it loads only 42 users per session as per screenshot above...

**Comment by tE3m** [comment]
Did you also transfer the `.csv` files?

**Comment by aliceEddie** [comment]
> The only way I can make it work if I am doing allFollowing=True modifier AND then it loads only 42 users per session as per screenshot above...

doesn't work for me either : / I still get ` Total 0 users available to unfollow`. Copied db and csv files.

**Comment by Tachenz** [comment]
@tarekj03 I don’t think I’ve done that, when I update to the new build, I just overwrite the files in my installation folder with the files from the new version archive (so csv files are always there).
Have I botched it? :)

**Comment by tE3m** [comment]
I don't quite understand... *did* you transfer your `.csv` files from the old folder to the new one, or didn't you? Because InstaPy works with them.

**Comment by Tachenz** [comment]
I did, yes. And it does unfollow .. just 42 at a time for some reason...

**Comment by Tachenz** [comment]
That “list index out of range” what does it relate to?
After redoing copying of the log and cav files into Instapy folder, unfollow is now just stuck at this screen: (after loading all the users to unfollow)
![671244ba-d781-44cb-a822-ccef50afc309](https://user-images.githubusercontent.com/36073534/52613890-bda42c00-2e5d-11e9-93e8-4da3ac144b0f.jpeg)

**Comment by Tachenz** [comment]
Okay, got it working - thank you @TarekJ03 . Unfollow those followed by instapy is still bugged, but that seems to be me somehow fcking up the database migration, and not a problem with a script :)
