### ISSUE TITLE
Like by feed - AttributeError: 'NoneType' has no attribute 'end'

### ISSUE THREAD

**Issue by datteba** [InstaPy/InstaPy#394]
After this error the terminal closes.

![likebyfeed](https://user-images.githubusercontent.com/30053143/28083895-31b76a40-6677-11e7-8e79-4774fc5ff3a8.PNG)

**Comment by timgrossmann** [comment]
@datteba Could you please do a git pull and check that again?
I should've fixed the problem

**Comment by datteba** [comment]
@timgrossmann 

Thanks Tim! Now it's ok but I get this

![unable](https://user-images.githubusercontent.com/30053143/28159680-0a2a029c-67be-11e7-88bc-62a5fbd11913.png)

**Comment by timgrossmann** [comment]
@saurabh-kumar-vit Could you please look into this?

**Comment by saurabh-kumar-vit** [comment]
@datteba I am unable to reproduce this problem. Can you tell me the configuration of your browser when this error occurred.

In my knowledge this should happen only when selenium is unable to focus on the like button which might happen if you manually try to scroll the page while it is performing the likes.

**Comment by datteba** [comment]
Thanks for your reply @saurabh-kumar-vit 

Where can I see the browser config?
Yesterday worked perfectly but today I get that message. I'm not scrolling the page.

Maybe the problem is caused by this new instagram banner?

![insta](https://user-images.githubusercontent.com/30053143/28176415-989cdade-67f7-11e7-8f99-6507532e5563.PNG)

This is the source of the banner:
https://pastebin.com/dWaU1DSD

EDIT: if I manually close the banner it works again
