### ISSUE TITLE
insta py errror

### ISSUE THREAD

**Issue by taghaviali34** [InstaPy/InstaPy#3942]
hi its show this error    ImportError: No module named 'instapy'
pls help me thanks

**Comment by kvreem** [comment]
I get the following issue - 

```
Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File "/Users//Desktop/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users//Desktop/InstaPy/instapy/instapy.py", line 11, in <module>
    import requests
ImportError: No module named requests
```

Line four in my code is - 

`from instapy import InstaPy`

**Comment by taghaviali34** [comment]
So where can i enter this cod my friend?
Please explain more thanks my friend because I didn't understand and if you have any video please send me

**Comment by tE3m** [comment]
> 
> 
> hi its show this error ImportError: No module named 'instapy'
> pls help me thanks

```
pip install instapy
```

**Comment by tE3m** [comment]
> 
> 
> I get the following issue -
> 
> ```
> Traceback (most recent call last):
>   File "quickstart.py", line 4, in <module>
>     from instapy import InstaPy
>   File "/Users//Desktop/InstaPy/instapy/__init__.py", line 3, in <module>
>     from .instapy import InstaPy
>   File "/Users//Desktop/InstaPy/instapy/instapy.py", line 11, in <module>
>     import requests
> ImportError: No module named requests
> ```
> 
> Line four in my code is -
> 
> `from instapy import InstaPy`

```
pip install requests
```
