### ISSUE TITLE
unfollow_after seems to be incorrectly passed in session.unfollow_users

### ISSUE THREAD

**Issue by bvstek** [InstaPy/InstaPy#3944]
## Expected Behavior
The script should wait n days before a user is unfollowed if the parameter unfollow_after is set 

## Current Behavior
It's unfollowing users that have been followed **within** the last 5 days

## InstaPy configuration
session.set_dont_unfollow_active_users(enabled=True, posts=10)
session.unfollow_users(amount=70, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=5*24*60*60, sleep_delay=60)

**Comment by Tachenz** [comment]
Is this really true?
It seem to always have 100% users pulled eligible for unfollow - I wonder if that could be the reason...

**Comment by bvstek** [comment]
That seemed to be a one off so I’m closing the issue.

**Comment by Tachenz** [comment]
Is this really true?
It seem to always say 100% of the users following me pulled are eligible for unfollow - I wonder if that could be the reason (that he pulls recent users only). Going to test
