### ISSUE TITLE
Blacklist question

### ISSUE THREAD

**Issue by ccook22** [InstaPy/InstaPy#3945]
I don’t have an issue at the moment but just discovered the blacklist feature after getting several user messaging me asking them why I keep following and unfollowing them. My question is how big can the campaign get before there are performance issues or is this not an issue. I added all the users from my followed.csv in logs and now my blacklist has over 20k records. Just curious how many it can handle? Thanks in advance! BTW I’m a total newbie to Python but this not and site has helped a ton.

**Comment by andreademasi** [comment]
The best solution imho is to use a database to store usernames in the blacklist

**Comment by ccook22** [comment]
Is there a setting somewhere to point the blacklist campaign or instructions how to do this?

**Comment by Herrox** [comment]
Indeed this is a big issue for InstaPy and a lot of work must be done to rebuild correctly this feature which is the basement of how InstaPy could act more as an human being.
There is already some issues open about that but unfortunately I don't have the knowledge to handle it #3804, #3805 and #3849

Hope @timgrossmann and all his dev teams could have a look on it. On my side I have stopped InstaPy since few days cause of that...

**Comment by tE3m** [comment]
Actually, users usually don't get followed twice? Without adding any special argument, my bot skips all users in `followRestriction.json`, which is where users who are followed by InstaPy are saved.

**Comment by ccook22** [comment]
In my followers list of about 10k users there was about 200 duplicates so it does follow the same user more than once. Perhaps they are followers of multiple pages I am following users for. Blacklist seems to be working for me I just feel the csv will have performance hits as it grow.

**Comment by Herrox** [comment]
@TarekJ03 What this settings is? On my side, followers are sometimes follwed many times. I noticed a few has already been followed 3 or 4 times... Some sent me DMs, or I remembered some of the names or profiles pictures.

Let me know if I may help you more?

**Comment by tE3m** [comment]
@Herrox *you* help *me*? You are having issues, not me:joy:

**Comment by papillon-unix** [comment]
I have the same problem right now
