### ISSUE TITLE
Following likers of a post only loads 2000-2500 users

### ISSUE THREAD

**Issue by posittron** [InstaPy/InstaPy#3946]
## Expected Behavior
Following likers of a post full amount 5000
## Current Behavior
Only loads 2000-2500 users then shuffles and starts following

**Comment by gagna** [comment]
Post your Instapy script please

**Comment by posittron** [comment]
session = InstaPy(username=insta_username,

                  password=insta_password,

                  headless_browser=False)



with smart_run(session):

    """ Activity flow """

    # general settings

    session.set_skip_users(skip_private=False,
                       private_percentage=0)
    
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=-1.5,
                                    delimit_by_numbers=True,
                                    max_followers=3000,
                                    max_following=700,
                                    min_following=200,
                                    min_followers=100,
                                    min_posts=9)
    # activity
    session.follow_likers ([''], photos_grab_amount = 1, follow_likers_per_photo = 5000, randomize=False, sleep_delay=0, interact=False)

**Comment by posittron** [comment]
> Post your Instapy script please

session = InstaPy(username=insta_username,

                  password=insta_password,

                  headless_browser=False)



with smart_run(session):

    """ Activity flow """

    # general settings

    session.set_skip_users(skip_private=False,
                       private_percentage=0)
    
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=-1.5,
                                    delimit_by_numbers=True,
                                    max_followers=3000,
                                    max_following=700,
                                    min_following=200,
                                    min_followers=100,
                                    min_posts=9)
    # activity
    session.follow_likers (['leeleedrawings'], photos_grab_amount = 1, follow_likers_per_photo = 5000, randomize=False, sleep_delay=0, interact=False)

**Comment by gagna** [comment]
I think the problem is in the `set_relationship_bounds`

**Comment by posittron** [comment]
> I think the problem is in the set_relationship_bounds

really? what could be hampering loading the full amount of users?

**Comment by dmsfabiano** [comment]
The function takes a parameter ` follow_likers_per_photo` which is what I believe you are referring as the full amount of 5000. This does not mean that it will necessarily follow all 5000 of them. It grabs 5000 potential users yes, but you have a relationship bound; therefore, it will only interact with them if the criteria is met (i.e. `min_following=200` from your code).

However, please note that if you are using 5000 it will try to do 5000 for the amount of photos that you are requesting (`photos_grab_amount`).

Please make sure to give the documentation a read on this topic 👍

**Comment by posittron** [comment]
> The function takes a parameter  follow_likers_per_photo which is what I believe you are referring as the full amount of 5000. This does not mean that it will necessarily follow all 5000 of them. It grabs 5000 potential users yes, but you have a relationship bound; therefore, it will only interact with them if the criteria is met (i.e. min_following=200 from your code).
> However, please note that if you are using 5000 it will try to do 5000 for the amount of photos that you are requesting (photos_grab_amount).
> Please make sure to give the documentation a read on this topic 👍

Thanks for replying. I understand the script, my issue is that it does not load 5000 users to check the relationship bounds, I loads 2500 then applies the relationship bounds on them and follows only the ones that meet the requirements, it loads 2200 ish users and something weird happens with the scrolling and it goes to the shuffling and following part

**Comment by dmsfabiano** [comment]
> > The function takes a parameter  follow_likers_per_photo which is what I believe you are referring as the full amount of 5000. This does not mean that it will necessarily follow all 5000 of them. It grabs 5000 potential users yes, but you have a relationship bound; therefore, it will only interact with them if the criteria is met (i.e. min_following=200 from your code).
> > However, please note that if you are using 5000 it will try to do 5000 for the amount of photos that you are requesting (photos_grab_amount).
> > Please make sure to give the documentation a read on this topic 👍
> 
> Thanks for replying. I understand the script, my issue is that it does not load 5000 users to check the relationship bounds, I loads 2500 then applies the relationship bounds on them and follows only the ones that meet the requirements, it loads 2200 ish users and something weird happens with the scrolling and it goes to the shuffling and following part

I've seen this behavior before. Do you see the progress and then at some percentage just stops? and starts doing it's work?

I can track it down/fix it, but you've gotta help me to try and replicate the issue. When does it happen, does it always happen, etc...

**Comment by posittron** [comment]
> The function takes a parameter  follow_likers_per_photo which is what I believe you are referring as the full amount of 5000. This does not mean that it will necessarily follow all 5000 of them. It grabs 5000 potential users yes, but you have a relationship bound; therefore, it will only interact with them if the criteria is met (i.e. min_following=200 from your code).
> However, please note that if you are using 5000 it will try to do 5000 for the amount of photos that you are requesting (photos_grab_amount).
> Please make sure to give the documentation a read on this topic 👍
> 
> Thanks for replying. I understand the script, my issue is that it does not load 5000 users to check the relationship bounds, I loads 2500 then applies the relationship bounds on them and follows only the ones that meet the requirements, it loads 2200 ish users and something weird happens with the scrolling and it goes to the shuffling and following part
> 
> I've seen this behavior before. Do you see the progress and then at some percentage just stops? and starts doing it's work?
> I can track it down/fix it, but you've gotta help me to try and replicate the issue. When does it happen, does it always happen, etc...

For eg a post has 4000 or 5000 likes, It scrolls/loads up 2200 ish users regardless of the percentage its more of the number its always around 2200. It happens everytime the post has a higher number of likes than 2200 it loads till 2200 closes the like window and then starts following the 2200 collected users. Since it happens everytime the likes are higher than 2200 it should be easy for you to replicate the issue

**Comment by dmsfabiano** [comment]
I'll be working on this, expect a PR soon if I find the problem

**Comment by posittron** [comment]
> I'll be working on this, expect a PR soon if I find the problem

Thanks!

**Comment by posittron** [comment]
> I'll be working on this, expect a PR soon if I find the problem

any luck?

**Comment by an0key** [comment]
Believe this is still an issue?
