### ISSUE TITLE
Docker run doing nothing

### ISSUE THREAD

**Issue by eurunuela** [InstaPy/InstaPy#395]
Hi, I'd like to know what should happen once I run InstaPy with docker on the terminal. I get this code: ec7c4610ab425846fd57b66c22d8af200f6a766ffe13fc51de7e26b07eec1c04 but Chrome doesn't open and nothing happens. I have the latest chromedriver and have uninstalled and reinstalled the necessary packages.

**Comment by onyxim** [comment]
Docker image in the master branch seems to be broken now. I've made  [pull request](https://github.com/timgrossmann/InstaPy/pull/389) which have approved not so long time ago. I think Tim will merge it soon, when checked it.

If you want some really working solution with docker right now, just look at my private fork, [branch docker_microservice](https://github.com/onyxim/InstaPy/tree/docker_microservice). Look at the readme file - there are new instructions.

**Comment by eurunuela** [comment]
How am I supposed to open the docker_quickstart.py if when I clone or download the branch the file isn't there?

### # Edit:
Don't know why clone didn't work but the zip did. Seems to be working now. Thanks!

### # Edit 2:
I get this error message: 

ERROR: for instapy_selenium_1  Cannot start service selenium: driver failed programming external connectivity on endpoint instapy_selenium_1 (2ae7109a941deae7b32a3e53ff68b8e8ab320d3b5a1601c772315027b9b30890): Error starting userland proxy: Bind for 0.0.0.0:5900 failed: port is already allocated

**Comment by onyxim** [comment]
Your 5900 port simply have been already allocated with the old docker image. Either change port for selenium before ":" (to 5092 for example) or kill old docker image. And try again.

**Comment by eurunuela** [comment]
Okay thanks, and what about the username I get asked for along with the "secret" password?

**Comment by onyxim** [comment]
There is no username. Leave it blank or use [tighVNC](http://www.tightvnc.com/), which is not asks any usernames.

**Comment by RealMakAttak** [comment]
the password "secret" doesnt seem to work - am I being stupid?

**Comment by RealMakAttak** [comment]
Yes I was, have to set the password in tightVNC

**Comment by eurunuela** [comment]
I tried tighVNC but had no success. I have a Mac and I get this message:

> No security types supported. Server sent '[30,36,35]' security types, but we do not support any of their. Try another connection?

**Comment by onyxim** [comment]
Oh, Mac. You have to think different, you know:-) I've never tried docker on Mac, so I have clues about cheats and tricks on that platform. Try to changed vnc port in docker-compose file setting, as I described above.

By the way, tightVNC have no official support for Mac. Please, try to use other tool something like [realVNC](https://www.realvnc.com/en/download/vnc/macos/), which is officially support Mac OS. I've tried it on windows and it works flawlessly. 

Docker containers should run everywhere  without any troubles, that's the core idea of docker. If you resolve your problem, please, feel free and post there you solution. It may help other Mac's users.

**Comment by eurunuela** [comment]
Yeah, I tried realVNC. That's why I asked about the username. RealVNC asked for a username. I'll try once again... Do you know of any other VNC viewer I could check?

Of course I will post the solution. I guess I'm not the only one experiencing this problem so, if I can help other people, I will.

**Comment by eurunuela** [comment]
I managed to use realVNC with localhost:5902. It didn't work two days ago on localhost:5900. However, this is all I see:

![img_7315](https://user-images.githubusercontent.com/13706448/28181844-4c1cd660-680a-11e7-844c-026b9232d9c7.jpg)

**Comment by onyxim** [comment]
Click on the right arrow near "workspace 4" before there will be "workspace 1". When the bot is running, chrome window will be there.

**Comment by onyxim** [comment]
To rerun only bot service just type: `docker-compose up -d --build web`

**Comment by eurunuela** [comment]
It looks the same on every workspace.

**Comment by onyxim** [comment]
Type this `docker-compose up -d --force-recreate` and connect again.

**Comment by eurunuela** [comment]
There was an error:

`web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
web_1       |     encode_chunked=req.has_header('Transfer-encoding'))
web_1       |   File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
web_1       |     self._send_request(method, url, body, headers, encode_chunked)
web_1       |   File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
web_1       |     self.endheaders(body, encode_chunked=encode_chunked)
web_1       |   File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
web_1       |     self._send_output(message_body, encode_chunked=encode_chunked)
web_1       |   File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
web_1       |     self.send(msg)
web_1       |   File "/usr/local/lib/python3.6/http/client.py", line 964, in send
web_1       |     self.connect()
web_1       |   File "/usr/local/lib/python3.6/http/client.py", line 936, in connect
web_1       |     (self.host,self.port), self.timeout, self.source_address)
web_1       |   File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
web_1       |     raise err
web_1       |   File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
web_1       |     sock.connect(sa)
web_1       | ConnectionRefusedError: [Errno 111] Connection refused
web_1       | 
web_1       | During handling of the above exception, another exception occurred:
web_1       | 
web_1       | Traceback (most recent call last):
web_1       |   File "docker_quickstart.py", line 18, in <module>
web_1       |     bot.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub')
web_1       |   File "/code/instapy/instapy.py", line 102, in set_selenium_remote_session
web_1       |     desired_capabilities=DesiredCapabilities.CHROME)
web_1       |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
web_1       |     self.start_session(desired_capabilities, browser_profile)
web_1       |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 188, in start_session
web_1       |     response = self.execute(Command.NEW_SESSION, parameters)
web_1       |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 254, in execute
web_1       |     response = self.command_executor.execute(driver_command, params)
web_1       |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 464, in execute
web_1       |     return self._request(command_info[0], url, body=data)
web_1       |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 526, in _request
web_1       |     resp = opener.open(request, timeout=self._timeout)
web_1       |   File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
web_1       |     response = self._open(req, data)
web_1       |   File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
web_1       |     '_open', req)
web_1       |   File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
web_1       |     result = func(*args)
web_1       |   File "/usr/local/lib/python3.6/urllib/request.py", line 1346, in http_open
web_1       |     return self.do_open(http.client.HTTPConnection, req)
web_1       |   File "/usr/local/lib/python3.6/urllib/request.py", line 1320, in do_open
web_1       |     raise URLError(err)
web_1       | urllib.error.URLError: <urlopen error [Errno 111] Connection refused>`

**Comment by onyxim** [comment]
Please, post here your full bot code (without credential for sure). Or better attach it to message.

**Comment by Nkuutz** [comment]
There you go.
[InstaPy.zip](https://github.com/timgrossmann/InstaPy/files/1149116/InstaPy.zip)

**Comment by onyxim** [comment]
Please delete your credentials from archive and better change your insta password quick. Now it is obviously exposed.

**Comment by eurunuela** [comment]
Oh... I thought I only had to change them on quickstart! Thanks for the alert! Here it is.

[InstaPy.zip](https://github.com/timgrossmann/InstaPy/files/1149310/InstaPy.zip)

**Comment by onyxim** [comment]
Ok, @Nkuutz . I wish, but couldn't help you right now, because docker on mac  still very young, and have a lot of restrictions. And what is the worst fact, that I currently know nothing about this restrictions:-D 

So, I suggest you  prepare and post an issue to the [official docker repository](https://github.com/docker/for-mac/issues). Put there docker-compose.yml file and log above and describe behavior.

As I can see, somehow, there is no connection from one container to another.

After your creating an issue, put there link to it.

**Comment by eurunuela** [comment]
I just got a Raspberry so tomorrow I'll be trying it on NOOBS which is basically Linux, I hope it works. In case it doesn't, I would post an issue to the official docker repository.

Thank you very much for your patience, effort and help. I really appreciate it @onyxim .

**Comment by enadgermani** [comment]
Is there a solution right now?

**Comment by danniefraim** [comment]
Hi everyone! I am experiencing the same issue trying with Docker on a Mac, i.e. the Docker machine just sits there doing nothing. However, my logs point to a more specific error:

```
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
web_1       |     stdin=PIPE)
web_1       |   File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
web_1       |     restore_signals, start_new_session)
web_1       |   File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
web_1       |     raise child_exception_type(errno_num, err_msg, err_filename)
web_1       | FileNotFoundError: [Errno 2] No such file or directory: '/code/assets/chromedriver': '/code/assets/chromedriver'
web_1       | 
web_1       | During handling of the above exception, another exception occurred:
web_1       | 
web_1       | Traceback (most recent call last):
web_1       |   File "docker_quickstart.py", line 15, in <module>
web_1       |     session = InstaPy(username=insta_username, password=insta_password)
web_1       |   File "/code/instapy/instapy.py", line 148, in __init__
web_1       |     self.set_selenium_local_session()
web_1       |   File "/code/instapy/instapy.py", line 239, in set_selenium_local_session
web_1       |     chrome_options=chrome_options)
web_1       |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
web_1       |     self.service.start()
web_1       |   File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
web_1       |     os.path.basename(self.path), self.start_error_message)
web_1       | selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
web_1       | 
instapy_web_1 exited with code 1
```

I figured perhaps this is because my chromedriver file is the Mac 64 bit version, so I downloaded the Linux 64 bit version instead. This did not help, I still get the same error. And the error seems to say that the file is actually not found. Isn't "/code" mapped to the InstaPy directory on my Mac?

If I connect to the Docker image and open XTerm I can see that there is no "/code" folder at all on the machine. I figure that might be where things go wrong. However, I clearly see step 7 being executed when building the machine, i.e. copying "./" to "/code".

Does anyone have any suggestions on how to troubleshoot this further?

EDIT: My bad. I had forgotten the selenium_local_session=False parameter when initiating my bot in docker_quickstart.py. Now it works just fine.
