### ISSUE TITLE
could not find requirements.txt

### ISSUE THREAD

**Issue by jufelka** [InstaPy/InstaPy#3951]
I have moved my InstaPy files to another server, trying to make pip3 install -r requirements.txt but get error /usr/bin/pip3: No such file or directory

**Comment by tE3m** [comment]
That means that either python or at least pip is not installed.

**Comment by jufelka** [comment]
> That means that either python or at least pip is not installed.

~#pip3 install -r requirements.txt
The program 'pip3' is currently not installed. You can install it by typing:
apt install python3-pip
~# apt install python3-pip
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-pip is already the newest version (8.1.1-2ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.

Try again:
~# pip3 install -r requirements.txt
The program 'pip3' is currently not installed. You can install it by typing:
apt install python3-pip
~# apt install python3-pip
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-pip is already the newest version (8.1.1-2ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.

**Comment by tE3m** [comment]
Maybe try `python3 -m pip` instead of `pip3`?

**Comment by antwal** [comment]
> I have moved my InstaPy files to another server, trying to make pip3 install -r requirements.txt but get error /usr/bin/pip3: No such file or directory

`curl https://bootstrap.pypa.io/get-pip.py | python`

**Comment by tE3m** [comment]
@antwal he already has `python3` and `pip` installed, did you read his previous messages?

**Comment by antwal** [comment]
> @antwal he already has `python3` and `pip` installed, did you read his previous messages?

yes, you need install again pip, then working

check bugs list of ubuntu, is confirmed this bug

or it can try this:

sudo apt purge python3-pip  
sudo rm -rf '/usr/lib/python3/dist-packages/pip'  
sudo apt install python3-pip

**Comment by jufelka** [comment]
Still have the same problem

:~# pip3 install -r requirements.txt
bash: /usr/bin/pip3: No such file or directory

**Comment by jufelka** [comment]
I've got new server with debian, try to install again and after 
`pip3 install -r requirements.txt
`
get error:
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'

**Comment by tE3m** [comment]
I actually had that as well some time ago. Maybe upgrade pip,
```
pip install --upgrade pip
```
If that doesn't work, try using `python3 -m pip` instead of pip.

**Comment by jufelka** [comment]
> pip install --upgrade pip

Thanks. It works
