### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by johnyjin** [InstaPy/InstaPy#3955]
I ran instapy quickstart.py on ubuntu 16.04 server and I got below errors
Instapy said Logged in successfully but when It try to start follow i got these errors

`raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=60874): Max retries exceeded with url: /session/f7e8a4c01bd4b28f706dbf4044112013/execute (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff40e0a10f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
`

**Comment by antwal** [comment]
same problem with python 2.7, try use python >= 3.5 with virtualenv for test it

**Comment by AdamMoffitt** [comment]
same problem with python3.7

**Comment by antwal** [comment]
python 2.7 end support 2020; python 3.4 is backward compatible with 2.7 and has the same problems. The instapy code works fine with python 3.5, but has problems with 3.6 and 3.7; so you have to wait for the conversion to newer versions of python. I have already done this but I have not yet converted all the code; I hope shortly to publish a stable release
