### ISSUE TITLE
Failure to Load desired amount of Users

### ISSUE THREAD

**Issue by notahooper15** [InstaPy/InstaPy#3963]
I have been running follower other users following and have it running to follow 250 accounts. For some reason the program will only grab about 10 users instead of the whole 250 from the accounts.

Also:
I have this same script for two different accounts, but I get the error on only one of the accounts.

INFO [2019-02-10 13:12:41] [****]  User '***********' [2/2]

  13/750 [+-----------------------------------]  1%    |> Elapsed: 0.88 seconds    |> ETA: 1.45 minutes      
  13/750 [+-----------------------------------]  1%    |> Elapsed: 1.79 seconds    |> ETA: 2.96 minutes      
  16/750 [+-----------------------------------]  2%    |> Elapsed: 2.53 seconds    |> ETA: 2.06 minutes      
  16/750 [+-----------------------------------]  2%    |> Elapsed: 3.57 seconds    |> ETA: 2.92 minutes      
  17/750 [+-----------------------------------]  2%    |> Elapsed: 4.6 seconds    |> ETA: 3.75 minutes      
  17/750 [+-----------------------------------]  2%    |> Elapsed: 5.35 seconds    |> ETA: 4.37 minutes      
  17/750 [+-----------------------------------]  2%    |> Elapsed: 6.33 seconds    |> ETA: 5.17 minutes      
  17/750 [+-----------------------------------]  2%    |> Elapsed: 7.12 seconds    |> ETA: 5.82 minutes      
  17/750 [+-----------------------------------]  2%    |> Elapsed: 8.13 seconds    |> ETA: 6.64 minutes      
  17/750 [+-----------------------------------]  2%    |> Elapsed: 9.22 seconds    |> ETA: 7.53 minutes      
  17/750 [+-----------------------------------]  2%    |> Elapsed: 10.0 seconds    |> ETA: 8.17 minutes      
  19/750 [+-----------------------------------]  2%    |> Elapsed: 11.33 seconds    |> ETA: 9.25 minutes      INFO [2019-02-10 13:13:00] [***]  Simulated follow : 1
INFO [2019-02-10 13:13:03] [***]  --> Followed 'b'********''!
  19/750 [+-----------------------------------]  2%    |> Elapsed: 18.08 seconds    |> ETA: 14.76 minutes      
  19/750 [+-----------------------------------]  2%    |> Elapsed: 18.95 seconds    |> ETA: 15.47 minutes      
  19/750 [+-----------------------------------]  2%    |> Elapsed: 19.79 seconds    |> ETA: 16.16 minutes      
  19/750 [+-----------------------------------]  2%    |> Elapsed: 20.58 seconds    |> ETA: 16.81 minutes      INFO [2019-02-10 13:13:10] [******]  Failed to load desired amount of users!

This is the error I get when running the script.

Quickstart.py Configuration:

""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = '********'
insta_password = '**********'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=False, potency_ratio=0)
    session.set_skip_users(skip_private=False)
    session.follow_user_followers(['*************', '**************'], amount=250, randomize=True)

**Comment by joost-heijden** [comment]
Same issue over here. Someone got a solution?

**Comment by tE3m** [comment]
#3931 is working on that.

**Comment by brunano21** [comment]
I have the same issue...this happens after the first followed user.

**Comment by ExportEh** [comment]
Having the same issue but it's intermittent. 
I just changed the user in the session.follow_user_followers and it's running at the moment. Maybe try someone else?

**Comment by notahooper15** [comment]
@exporteh yes, it seems to work when it wants to
