### ISSUE TITLE
Quota Supervisor dont work

### ISSUE THREAD

**Issue by tourhuntr** [InstaPy/InstaPy#3965]
## Expected Behavior
I use follow Unfollow script with unfollowing until 500 und following 300. Quota Supervisor should stop after 300 follows.
the script run via cronjob every day from 7 a.m. til the unfollows and follows are reached

## Current Behavior
script doesn't stop after 300 follows...

## InstaPy configuration

rom instapy import InstaPy
from instapy.util import smart_run

insta_username = ''
insta_password = ''

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

# let's go! :>
with smart_run(session):
    # general settings
    session.set_relationship_bounds(enabled=True,
                                     delimit_by_numbers=True,
                                      max_followers=15000,
                                      max_following=700,
                                      min_followers=0,
                                      min_following=30)
    session.set_quota_supervisor(enabled=True,peak_follows=(None, 300),peak_unfollows=(None, 500))

    # unfollow activity
    session.unfollow_users(amount=500, InstapyFollowed = (True, "all"), style="FIFO", unfollow_after=36*60*60, sleep_delay=300)

    # follow activity
    ammount_number=200
    session.follow_user_followers(['xxx'], amount=ammount_number, randomize=True, interact=True, sleep_delay=600)

**Comment by tE3m** [comment]
You have to add `sleep_after=[follows],` . Please read the docs....

**Comment by tourhuntr** [comment]
how do i configure it that it starts next morning again and dont runs until this start? script runs via cron every day

**Comment by tE3m** [comment]
I simply added an if-statement that checks the time from the `time` module.

**Comment by tourhuntr** [comment]
Could you give an example?

**Comment by tE3m** [comment]
```
with smart_run(session):
    if time.localtime().tm_hour > hour you want to start with:
        <script>
```

**Comment by tourhuntr** [comment]
so the script will run 24/7 and pause after the unfollow and follow and i dont need a cron job?

**Comment by tE3m** [comment]
To do that, put the whole script into an infinte loop with ` while True:`.

**Comment by tourhuntr** [comment]
i'm sorry for asking, but could you give me an example how to do that?
the whole script is shown above in the first post under instapy cornfiguration

**Comment by tourhuntr** [comment]
made it work, just replaced the withsmart run with "while TRUE"
