### ISSUE TITLE
Need help with pip installation - lost...

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#3967]
Thoroughly confused here :)
So i was using Instapy in the local folder before (located on my desktop).
I understand now it has to be installed with:
pip install instapy

Which I have done. Went succesfully.

Then Readme says it will create Instapy folder in the c:/users/username/instapy once quickstart.py is downloaded (where to? Anywhere?) and launched. I’ve downloaded it, launched.

But it does not create that Instapy folder for me... Can anyone please help on what am I doing wrong?

**Comment by Tachenz** [comment]
Wait... so I was able to get script create users/user/instapy folder - only after copying quickstart.py into:

Appdata/local/programs/python/python36/lib/site-packages   (Where Instapy installation sits) and launching it from there....

Was that intended to work like that or am I doing something terribly wrong? :)

**Comment by Tachenz** [comment]
I’ve also copied folders (the one from logs directory, named as the account name) all over that Instapy folder in User files. But instapy.db file size remains 24kb with date modified few hours before.
That is after I’ve launched quickstart.py, with my logs files copied...
It looks like my logs don’t want to migrate?
Any help would be appreciated...

**Comment by tE3m** [comment]
@Tachenz you could've run that script from *anywhere* outside your "old" folder ;)

**Comment by tE3m** [comment]
@Tachenz the logs structure is the same as before:
.................logs/ -> user/ -> log files
.............../
InstaPy/-
...............\\
.................db/ -> instapy.db

**Comment by Tachenz** [comment]
@TarekJ03 Thank you so much for all the answers. I am not someone knowledgeable in programming, so I probably am doing something wrong :) Can you please help me understand these few things:

1. You saying that I could have launched quickstart.py from anywhere after pip install. But if I try to do that - I get this error (see screenshot)
![33aa0266-5d3e-48cd-86b4-e362e49c113e](https://user-images.githubusercontent.com/36073534/52642441-033a1680-2ea9-11e9-9d7d-5ac1165030ed.jpeg)
The only way it launches for me IF i copy quickstart.py into that deep folder in users/username/appdata/local.../python/libraries - wheee isntapy folder actually sits. Why?

2. I had 2 separate folders for 2 accounts from which I was running instapy. Account 1 and account 2. Obviously each had a separate logs folder named “1” and “2”. So I can copy those TWO maintaining the file structure. That is what I did
However. There is also instapy.db file in the db folder for EACH of them (so I have 2 of them)
What do I do with those?

3. For now, Once I’ve copied the logs folders (with txt and csv files). And launched the script, and ran it for the night (from that folder in appdata/local...) - the:
A) user/username/Instapy/db/instpay.db file size and modify date DID NOT CHANGE and remained 24kb and remained “date modified” at the date of pip install
B) The instapy.db file in the folder from which I was running the script these last few months, DOES have “date modified” as of this morning and size 288kb
QUESTION... - How is that possible? And where is my database? :D

**Comment by Tachenz** [comment]
My biggest concern here being that it starts follow users I’ve followed and unfollowed before of course. Also when script runs now - the first line says Workplace used - c:/users/user/Instapy (even though THAT db file does not change in size nor “modified date”)

**Comment by tE3m** [comment]
1.The problem is that you have a file named `instapy.py` which makes python think that it should import this instapy over your `pip` installation. If you move your script into the package's folder, it'll import from there. It seems strange, but it's python's import policy. Renaming *your* instapy.py fixes that. (Btw- why do you have a html-document named instapy.py? .py is for python files :smile:.
2. I'm not into sql databases, sorry. I have no clue how you could merge them. But there's not really a point in having two folders for two accounts, is there? I mean, every user's logs are automatically stored in *that user's* log folder. 
3. You shouldn't really have two seperate installations at the same time. Try backing up everything important (logs, scripts, db) and removing your github installation.

**Comment by Tachenz** [comment]
1. Understood
2. I think it was a legacy thing from when instapy did not support couple accounts under one installation (and delays were not incorporated into quickstart file, but I used to put them manually into the files - different for different accounts).

3. Well, main problem is that it does not pick up even one database...

**Comment by Tachenz** [comment]
Or maybe it did? And it is okay that db file in new location is 24kb while the old one was 288kb? As there are still csv files in logs folders, and maybe they retain all the info?
