### ISSUE TITLE
Pi3 Firefox method version not working

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#3968]
I use `sudo xvfb-run python quickstart.py` to start the python script but I get the following lines:

`pi@raspberrypi:~/Projects/InstaPy $ sudo xvfb-run python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    from instapy import InstaPy
  File "/home/pi/Projects/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 12, in <module>
    from selenium import webdriver
ImportError: No module named selenium
`

I´m thankfull for every help!

**Comment by tE3m** [comment]
Use `python3` over `python` since `python` refers to python2.7, which will be deprecated on 1.1.2020.

**Comment by ghost** [comment]
@TarekJ03 Hey, I tried it out but I get the same error again :/

**Comment by tE3m** [comment]
How did you install `instapy`? With `pip`?

**Comment by ghost** [comment]
I installed like in How_to_Raspberry.md described: [https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Raspberry.md], so I used: `git clone https://github.com/timgrossmann/InstaPy.git`.

**Comment by tE3m** [comment]
Did you install all the requirements? If you're not sure, run 
```
pip3 install -r requirements.txt
```
in the InstaPy folder.

**Comment by mwargan** [comment]
@johanneskapst the new way to install InstaPy is with `pip` - https://github.com/timgrossmann/InstaPy/pull/3973

**Comment by ghost** [comment]
@mwargan I´m going to flash the Pi. So I just need to do: `pip install instapy`? Or do I have to install chromedrive seperately, like you mentioned in #3973 ?

**Comment by tE3m** [comment]
```
pip3 install instapy
pip3 uninstall instapy-chromedriver
pip3 install instapy-chromedriver==2.36.post0
mkdir InstaPy
```
And then, put your scripts and stuff like that into `/InstaPy`
And you're set:tada:

**Comment by ghost** [comment]
@TarekJ03 
Thank you <3

**Comment by mwargan** [comment]
@johanneskapst, @TarekJ03 is correct - just make sure you do an `apt update` beforehand. And a side note, you can put your scripts anywhere as instapy will be installed globally.

**Comment by ghost** [comment]
@mwargan then I can name my scripts however I want, right?

**Comment by tE3m** [comment]
@johanneskapst yes:smile:

**Comment by mwargan** [comment]
@johanneskapst yes, but keep in mind others had issues if you name your script as the  program - so don't call it `instapy.py` (as pointed out by @TarekJ03 https://github.com/timgrossmann/InstaPy/issues/3967#issuecomment-462799149) - I usually just stick with `quickstart.py`

**Comment by ghost** [comment]
Everything is working perfectly now. Someone needs to update the how_to_rapberry.md. Thank you guys:)
