### ISSUE TITLE
unfollowing works only on 19 users

### ISSUE THREAD

**Issue by diveu** [InstaPy/InstaPy#397]
I'm not sure whether it's an Instagram policy or just a bug, but onfollowing works only twice (first 10 and then 9 users after 10 minute sleep).
Is there any workaround about it? I guess, I should probably try to set longer wait (approx. 12-15 minutes). Anyone got any suggestions?

**Comment by diveu** [comment]
Current quick fix is to run sessions with `unfollow_users(amount=20, onlyInstapyFollowed=True)` multiple times with sleep(725) between them.
Looks like a dirty hack, but it works anyway

**Comment by NewyorkDev** [comment]
it appears to only be on Linux for me - on the windows side it works. on ubuntu it stops at 19. When I have it set for 300.

**Comment by mbancha** [comment]
Python noob here, where exactly do I put "sleep(725)"?

**Comment by mbancha** [comment]
Can someone help me with this? I've tried writing the script as you've described, using both 'sleep' and 'session.sleep', and both give me this error:

Traceback (most recent call last):
  File "C:\Users\Matt\instapy\UNFOLLOW.py", line 13, in <module>
    session.sleep(725)
AttributeError: 'InstaPy' object has no attribute 'sleep'


To be clear, the script I'm using is: 

```python
session = InstaPy()
session.login()

session.unfollow_users(amount=50, onlyInstapyFollowed = True )
session.sleep(725)
session.unfollow_users(amount=50, onlyInstapyFollowed = True )
session.sleep(725)
session.unfollow_users(amount=50, onlyInstapyFollowed = True )
session.sleep(725)
session.unfollow_users(amount=50, onlyInstapyFollowed = True )
```

What am I doing wrong here?

**Comment by timgrossmann** [comment]
@Spiz There is no sleep function at InstaPy You have to use the 

```python
from time import sleep

sleep(725)
```

**Comment by mbancha** [comment]
@timgrossmann ah thank you!

**Comment by mbancha** [comment]
@timgrossmann ah, hmm, spoke too soon. I'm still getting the same "AttributeError: 'InstaPy' object has no attribute 'sleep'" error. This is my full code now:

```python
from instapy import InstaPy
from time import sleep

session.unfollow_users(amount=20, onlyInstapyFollowed = True )
session.sleep(725)
session.unfollow_users(amount=20, onlyInstapyFollowed = True )

```

By the way do you have anywhere I can donate to you or anything? This code is really great and I really appreciate the time you've taken to help me.

**Comment by timgrossmann** [comment]
@Spiz Well, the `session` still has no sleep method.

Instead of:

`session.sleep(725)`

you simply have to write

`sleep(725)`

Just leave out the `session`

You can support here:
[InstaPy](https://www.patreon.com/InstaPy)
