### ISSUE TITLE
Use multiple virtual environments or multiple users on a server?

### ISSUE THREAD

**Issue by bmsimo** [InstaPy/InstaPy#3970]
I would like to thanks @timgrossmann  and all of the people who committed on the project.
I've been reading and trying to understand all the features that InstaPy offers , im still new to python but already gave it a try and things are going great!

On an ubuntu instance, InstaPy doesn't consume CPU at all ( the most i've seen is a 20%). Im using it with the screen command so i can let it run 24/7.
I've had some thoughts about using InstaPy to manage multiple accounts. I have access to multiple VPS (most of them with 4gb RAM) and so i was thinking what would be the best way to do this ?

Should i just run it from different servers?
Should i create another user on the instance and run it from there? 
Or would it be better to just clone the repo with another name and run it at the same with another screen ?

Also , can it run multiple scripts at the same time? (like.py and follow.py for example) I think that would just get me banned ASAP but maybe im wrong.

**Comment by sionking** [comment]
maximum running profile is 3 if you dont modify your browser profile and use proxy.

**Comment by bmsimo** [comment]
> maximum running profile is 3 if you dont modify your browser profile and use proxy.

EDIT : Per users on a server? or per server?

**Comment by antwal** [comment]
> I would like to thanks @timgrossmann and all of the people who committed on the project.
> I've been reading and trying to understand all the features that InstaPy offers , im still new to python but already gave it a try and things are going great!
> 
> On an ubuntu instance, InstaPy doesn't consume CPU at all ( the most i've seen is a 20%). Im using it with the screen command so i can let it run 24/7.
> I've had some thoughts about using InstaPy to manage multiple accounts. I have access to multiple VPS (most of them with 4gb RAM) and so i was thinking what would be the best way to do this ?
> 
> Should i just run it from different servers?
> Should i create another user on the instance and run it from there?
> Or would it be better to just clone the repo with another name and run it at the same with another screen ?
> 
> Also , can it run multiple scripts at the same time? (like.py and follow.py for example) I think that would just get me banned ASAP but maybe im wrong.

check this PR #3840, i not have added the proxy in this PR
