### ISSUE TITLE
Mute automatically

### ISSUE THREAD

**Issue by bylezz** [InstaPy/InstaPy#3975]
Hello,

I want to know if it is possible to configure new follow to  mute automatically them at the same time.

Thanks so much.
Best regards,

**Comment by tE3m** [comment]
Wdym by "mute"?

**Comment by bylezz** [comment]
Mute publications and stories :)

**Comment by mwargan** [comment]
@bylezz What is it you'd like to achieve? Are you hoping that the bot follows people, and when you open Instagram for yourself, you don't see the stories and posts of the people the bot followed?

Don't think it's possible: if I was Instagram, I'd say - why'd you follow them in the first place :P?

Edit: I stand corrected, it's possible to mute (still, statement above applies :D). InstaPy does not have this built in - and it doesn't look like I can mute people from the browser (only in-app).

**Comment by bylezz** [comment]
> @bylezz What is it you'd like to achieve? Are you hoping that the bot follows people, and when you open Instagram for yourself, you don't see the stories and posts of the people the bot followed?
> 
> Don't think it's possible: if I was Instagram, I'd say - why'd you follow them in the first place :P?
> 
> Edit: I stand corrected, it's possible to mute (still, statement above applies :D). InstaPy does not have this built in - and it doesn't look like I can mute people from the browser (only in-app).

A while ago I hired a bot that did it (I suppose it was with Jarvee). Then I did not know if Instapy was possible. I have read the code and possibilities but I have not found it.

Is it possible to request that they include the option even if it is late or not? in my opinion it would be good tool-

**Comment by mwargan** [comment]
@bylezz not sure how easy it would be to implement. You'd need a selector and a couple of click simulations - nothing too hard.

The hard part is that InstaPy opens a desktop browser and therefore some functionality, such as mute, isn't even available to select.

**Comment by bylezz** [comment]
> @bylezz not sure how easy it would be to implement. You'd need a selector and a couple of click simulations - nothing too hard.
> 
> The hard part is that InstaPy opens a desktop browser and therefore some functionality, such as mute, isn't even available to select.

@mwargan  thank you very much for your words. Hopefully they can include the tool.

**Comment by spikeyhair** [comment]
i have this question in mind for quite sometimes and then I notice that the web version of IG doesn't have the mute function at all so it's not possible for the bot to do it unless the bot can run on an android simulator which runs IG.

Last time I saw someone posted some screen shots here before, it was running on IG app instead of using browser. I don't know how it works, seems like I couldn't find any info about it tho.

Anyway, followed and mute or followed but don't mute, this is up to individual. If this feature is available on the web, the bot can include this option. Again, up to the individual to turn it on or off. :)

**Comment by sionking** [comment]
I tried to did it:
I simulte another bot just for that.
Instapy sent all follow pool to online database, that the android bot read the database and mute the ppls.
Full of bugs, just use a J**** application that can do it.

**Comment by bylezz** [comment]
Do you think that someday you can mute?
