### ISSUE TITLE
blocked from another account

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#3977]
Hello i got blocked from an account which i am following users - anyway to keep following his followers/likers/comments people . Thanks

Anyidea please @uluQulu

**Comment by uluQulu** [comment]
Hey @Edhim 

Scrape from other account and pass to the account in use;
Or scrape and store then load and use;

---

Cheers 😁
---

**Comment by Edhim** [comment]
@uluQulu  How to do this :D

**Comment by uluQulu** [comment]
@Edhim 
If you like to get help, please write what you like.
I can't think of what you would like and also think of what code you need for it at the same time.

Shortly, I have outlined 2 styles above, choose the one you want or other style you think of.
And then tell me the technical difficulties I can help you with.

---

Cheers 😁
---

**Comment by sionking** [comment]
I did not understand the Q. funny @uluQulu  you even answer to him :)

**Comment by Edhim** [comment]
@uluQulu basically i should grab the followers from the account, 

xxx_followers = session.grab_followers(username="xxxx", amount="full", live_match=True, store_locally=True)
sleep(600)

Then i should follow that list right?

**Comment by Edhim** [comment]
Hello @uluQulu 

so i did this : 

xxx_followers = session.grab_followers(username="xxxx", amount="full", live_match=True, store_locally=True)
sleep(600)    

then
---
# select full path of the file
    selected_file = "/Users/Edhim/Desktop/InstaPyBot/scrapping/scrap/xxx.json"
    # load that file
    with open(selected_file) as followers_data_file:
        xxx_followers = json.load(followers_data_file)

    session.follow_user_followers(usernames=meslentillesma_followers, amount=10)
---

but its not doing what i want, it follow followers of the list, and i only want to follow the list(not their followers)

Can you help please ?
