### ISSUE TITLE
Grabbing followers when interacting user followers is returning an empty list.

### ISSUE THREAD

**Issue by octavius-1** [InstaPy/InstaPy#3979]
INFO [2019-02-13 11:04:19] [myuser]  User 'user1' [1/1]
ERROR [2019-02-13 11:04:57] [myuser]  `followers_link` error list index out of range
INFO [2019-02-13 11:04:57] [myuser]  Grabbed 0 usernames from 'user1's `Followers` to do interaction.
INFO [2019-02-13 11:04:57] [myuser]  Finished interacting 0 people from 1 users' `Followers`! xD

INFO [2019-02-13 11:04:57] [myuser]  Liked: 0
INFO [2019-02-13 11:04:57] [myuser]  Already Liked: 0
INFO [2019-02-13 11:04:57] [myuser]  Commented: 0
INFO [2019-02-13 11:04:57] [myuser]  Followed: 0
INFO [2019-02-13 11:04:57] [myuser]  Inappropriate: 0
INFO [2019-02-13 11:04:57] [myuser]  Not valid users: 0

Does anyone know what's happening here?
I already updated to the last version with `sudo pip3 install instapy -U`

**Comment by tourhuntr** [comment]
same problem

**Comment by mgconejero** [comment]
same

**Comment by devbry** [comment]
same

**Comment by shomanishikawa** [comment]
@timgrossmann any insight here? still seeing this error only on headless mode. Also tried the fix to change all my usernames to lowercase but it is still happening. thanks!
