### ISSUE TITLE
Exec Format Error on a Raspi 3+

### ISSUE THREAD

**Issue by tourhuntr** [InstaPy/InstaPy#3981]
## Expected Behavior

Working Bot ;)

## Current Behavior

Using built in instapy-chromedriver executable (version 2.44)
Traceback (most recent call last):
  File "simple_but_effective.py", line 21, in <module>
    multi_logs=True)
  File "/home/pi/projects/InstaPy/instapy/instapy.py", line 276, in __init__
    self.set_selenium_local_session()
  File "/home/pi/projects/InstaPy/instapy/instapy.py", line 326, in set_selenium_local_session
    self.logger)
  File "/home/pi/projects/InstaPy/instapy/browser.py", line 123, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
 **OSError: [Errno 8] Exec format error**

## InstaPy configuration

from instapy import InstaPy
#from instapy.util import smart_run

insta_username = 'xxx'
insta_password = 'xxx'

get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

let's go! :>
while True:

    # general settings
    session.set_relationship_bounds(enabled=True,
                                     delimit_by_numbers=True,
                                      max_followers=15000,
                                      max_following=700,
                                      min_followers=0,
                                      min_following=30)
    session.set_quota_supervisor(enabled=True,sleep_after=["likes"], sleepyhead=True, stochastic_flow=True, notify_me=True,peak_likes=(57, 700), peak_follows=(48, None), peak_unfollows=(35, 402), peak_server_calls=(500, None))
    #session.set_user_interact(amount=3, randomize=False, percentage=100, media='Photo')
    session.set_do_like(enabled=True, percentage=100)
    #session.set_do_comment(enabled=True, percentage=5)
    #session.set_comments(['Nice shot! @{}', 'I love your profile! @{}', '@{} Love it!', '@{} :heart::heart:',
    #                        '@{}:revolving_hearts::revolving_hearts:', '@{}:fire::fire::fire:'], media='Photo')

    # unfollow activity
    #session.unfollow_users(amount=500, InstapyFollowed = (True, "all"), style="FIFO", unfollow_after=36*60*60, sleep_delay=300)

    # like activity
    ammount_number=10
    session.set_user_interact(amount=5, randomize=False, percentage=50, media='Photo')
    #session.set_do_follow(enabled=True, percentage=70)
    session.set_do_like(enabled=True, percentage=70)
    #session.set_do_comment(enabled=True, percentage=30)
    session.interact_user_followers(['xxx], amount=ammount_number, randomize=True)

Installed it on raspi 3+ along the doc for the raspi.

**Comment by tE3m** [comment]
Exec format error means that the binary is not in the right format. The built-in Chromedriver doesn't work on RPis since their Chromium is v65 (which is old). Install the RPi-specific Chromedriver like this: 
```
pip3 uninstall instapy-chromedriver 
pip3 install instapy-chromedriver==2.36.post0
```
That fixes that :wink:

**Comment by tourhuntr** [comment]
Sadly don't fixes it. Get the same error after uninstall and install

@raspberrypi:~ $ pip3 uninstall instapy-chromedriver
Uninstalling instapy-chromedriver-2.36:
  /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver-2.36.dist-info/INSTALLER
  /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver-2.36.dist-info/LICENSE
  /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver-2.36.dist-info/METADATA
  /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver-2.36.dist-info/RECORD
  /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver-2.36.dist-info/WHEEL
  /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver-2.36.dist-info/top_level.txt
  /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver/__init__.py
  /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver/__pycache__/__init__.cpython-35.pyc
  /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver/chromedriver_linux64
  /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver/chromedriver_mac64
  /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver/chromedriver_win32.exe
Proceed (y/n)? y
  Successfully uninstalled instapy-chromedriver-2.36
pi@raspberrypi:~ $ pip3 install instapy-chromedriver==2.36.post0
Collecting instapy-chromedriver==2.36.post0
  Using cached https://files.pythonhosted.org/packages/41/0e/c8cac63ea1698c26cb3e8d009e1a12fb95b09cb30bbe0430bbc704a6d578/instapy_chromedriver-2.36.post0-py3-none-any.whl
Installing collected packages: instapy-chromedriver
Successfully installed instapy-chromedriver-2.36.post0
pi@raspberrypi:~ $ sudo python3 simple_but_effective.py python3: can't open file 'simple_but_effective.py': [Errno 2] No such file or directory
pi@raspberrypi:~ $ cd projects/
pi@raspberrypi:~/projects $ cd InstaPy/
pi@raspberrypi:~/projects/InstaPy $ sudo python3 simple_but_effective.py 

 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-02-14 12:02:24] [tourhuntr]  Using built in instapy-chromedriver executable (version 2.44)
Traceback (most recent call last):
  File "simple_but_effective.py", line 21, in <module>
    multi_logs=True)
  File "/home/pi/projects/InstaPy/instapy/instapy.py", line 276, in __init__
    self.set_selenium_local_session()
  File "/home/pi/projects/InstaPy/instapy/instapy.py", line 326, in set_selenium_local_session
    self.logger)
  File "/home/pi/projects/InstaPy/instapy/browser.py", line 123, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
pi@raspberrypi:~/projects/InstaPy $

**Comment by tE3m** [comment]
Could you please run
```
pip3 show instapy-chromedriver
```
Because if you look at it: it still says `Using built in instapy-chromedriver executable (version 2.44)` even though you installed `instapy-chromedriver==2.36.post0`

**Comment by tourhuntr** [comment]
i@raspberrypi:~/projects/InstaPy $ pip3 show instapy-chromedriver
Name: instapy-chromedriver
Version: 2.36.post0
Summary: chromedriver binaries for instapy
Home-page: https://github.com/InstaPy/instapy-chromedriver
Author: Felix Breuer
Author-email: felix@scriptworld.net
License: UNKNOWN
Location: /home/pi/.local/lib/python3.5/site-packages
Requires:

**Comment by tE3m** [comment]
Would it be possible that you have multiple instances of InstaPy?

**Comment by tourhuntr** [comment]
Until yesterday I had two installations of instapy. Then I deleted the folders via rm -r and installed it with the doc rapsberry.md

**Comment by tourhuntr** [comment]
Uninstalled instapy and installed again
uninstalled chromedriver 2.44 and installed 2.36post0

Same Error. Anyone an idea?

**Comment by tourhuntr** [comment]
Fixed it, but don't know how... done too much
