### ISSUE TITLE
Headless Browser cause LIKE action block?

### ISSUE THREAD

**Issue by jamezun** [InstaPy/InstaPy#3983]
## Expected Behavior
I just registered 5 new account and it works perfectly fine at first when I was setting headless browser to **false** so I can make sure everything runs well. It looks fine so I changed it to headless browser to **true** .

I am running likes on 5 hashtag with 100 likes & 3 interaction per hashtag, could this be the cause of being banned as I am using headless browser and IG detect that I might be using bots? or its because I am using AWS as proxy?

## Current Behavior 

I noticed that my like function was banned when I try to use the like function with the warning:
> "Based on previous use of this feature, your account has been temporarily blocked from taking this action...expire on 2019-02-14...Tell us if you think we made a mistake"
## InstaPy configuration
I am running five new accounts on the same proxy in AWS and all account face similar issues when I turn the headless browser to true.
I am currently using the latest update, but downgraded chromedriver to 2.42 as I am encountering proxy issues error when using version above 2.42.

```
session = InstaPy(username='fakedonaldtrump', password='trumpsucks',headless_browser=True, proxy_address='AWS', proxy_port=999, disable_image_load=True, multi_logs=True)

session.set_quota_supervisor(enabled=True,
                                  sleep_after=["likes", "comments_d", "follows", "unfollows"],
                                  sleepyhead=True, stochastic_flow=True, notify_me=True,
                                   peak_likes=(100, 700),
                                   peak_comments=(20, 200),
                                   peak_follows=(50, 700),
                                   peak_unfollows=(50, 700)) 
```

```
        hashtags = ['donald', 'trump', 'newworldorder', 'illuminati', '911isfake']
        my_hashtags = hashtags

        session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
        session.like_by_tags(my_hashtags, amount=100, media=None )
```

**Comment by sionking** [comment]
both cases. AWS and Headless

**Comment by sionking** [comment]
an tons of security issues we have here.
This project is 1 pc 1 ip only.

**Comment by jamezun** [comment]
@sionking Thanks for your prompt reply! I have noticed some people here encounter this issue too, but is there any suggested solution here? Perhaps I should change all headless browser to false and consider using another proxy services or at least limit the number of account per proxy to 1 only?

**Comment by Tachenz** [comment]
Don't use headless browser (though I know nothing about it). I am safely using this for 2 accounts per 1 IP, however, number of actions per account before soft ban - is generally less, than IF I were using 1 account per IP. 

Also, allowable number of actions (likes-follows-comments) for newly created accounts is WAY less than for established accounts. So you may be looking for as low as 3-4 follows an hour, for couple weeks on each account (if you have 2 accounts from same IP). Then do 10-15 follows, then ... you will probably hit soft ban, so wait 3-4 days and go back to last safe number.

**Comment by sionking** [comment]
mobile proxy with mobile emulator can do 250 follows a day in the first week for new account.
WEB BASED IG AUTOMATION is dead.

**Comment by oldtajik** [comment]
@sionking hey man. Could you tell more about mobile emu and how can you run instapy through it? Would really appreciate your knowledge

**Comment by jamezun** [comment]
I would also like to know how could it be done to run the script in an iphone if that's possible...

**Comment by jamezun** [comment]
Hi @sionking and other instapy users, I have been trying to limit my likes, follow and unfollow to maximum 30 per hour running five accounts in AWS and it appears that only the first account was not blocked in my second attempt, the remaining four of them was banned again, is it due to AWS in same IP? Does that mean if I use one IP per IP address would be fine? and would it be better if I use a less famous cloud service to run my proxy (not AWS, google, azure..etc)? The interesting thing is that my another five accounts running on the same IP in AWS **works perfectly fine in AWS without any BAN** (running since last November so its not really a new account, why those accounts were not banned? Any clue or solution... Any recommended low cost proxy?

**Comment by sionking** [comment]
Data center are banned / limited in 2019 IG.

**Comment by platramos** [comment]
I was having the same issue for a while and I kept thinking it had something to do with limits. I turned headless off and I haven't been having issues since. 

It should be noted that I'm running one account in a docker container and one account via python script on a cron job from the same ip. The docker account is relatively new with less than 100 followers. Here are the numbers I'm using currently.

```        
session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "follows"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=False,
                                 peak_likes=(39, 800),
                                 peak_comments=(25, 230),
                                 peak_follows=(25, 400))
```

I'm going to try and increase the numbers over the next week to see if I get blocked again.
