### ISSUE TITLE
Followers_link` error list index out of range" and "Grabbed 0 usernames from

### ISSUE THREAD

**Issue by tourhuntr** [InstaPy/InstaPy#3987]
## Expected Behavior
Running Bot

## Current Behavior
Using Instapy on Raspi 3B+
Get Message for "`followers_link` error list index out of range" and "Grabbed 0 usernames from"

Fresh Installation from today

## InstaPy configuration
from instapy import InstaPy
#from instapy.util import smart_run
from instapy import set_workspace

set_workspace('/home/pi/projects/InstaPy')

insta_username = 'txxx'
insta_password = 'xxx'

 get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True, nogui=False,
                  multi_logs=True)

 let's go! :>
while True:

    # general settings
    session.set_relationship_bounds(enabled=True,
                                     delimit_by_numbers=True,
                                      max_followers=15000,
                                      max_following=700,
                                      min_followers=0,
                                      min_following=30)
    session.set_quota_supervisor(enabled=True,sleep_after=["likes"], sleepyhead=True, stochastic_flow=True, notify_me=True,peak_likes=(57, 700), peak_follows=(48, None), peak_unfollows=(35, 402), peak_server_calls=(500, None))
    #session.set_user_interact(amount=3, randomize=False, percentage=100, media='Photo')
    session.set_do_like(enabled=True, percentage=100)
    #session.set_do_comment(enabled=True, percentage=5)
    #session.set_comments(['Nice shot! @{}', 'I love your profile! @{}', '@{} Love it!', '@{} :heart::heart:',
    #                        '@{}:revolving_hearts::revolving_hearts:', '@{}:fire::fire::fire:'], media='Photo')

    # unfollow activity
    #session.unfollow_users(amount=500, InstapyFollowed = (True, "all"), style="FIFO", unfollow_after=36*60*60, sleep_delay=300)

    # like activity
    ammount_number=10
    session.set_user_interact(amount=5, randomize=False, percentage=50, media='Photo')
    #session.set_do_follow(enabled=True, percentage=70)
    session.set_do_like(enabled=True, percentage=70)
    #session.set_do_comment(enabled=True, percentage=30)
    session.interact_user_followers(['xxx'], amount=ammount_number, randomize=True)

**Comment by tourhuntr** [comment]
Works again

**Comment by Joyen12** [comment]
What did you do to make it work ?
(It seems I have the same or very similar error)

**Comment by jlo-ryan** [comment]
I am also having the same issue.
