### ISSUE TITLE
Error install with raspberry. 

### ISSUE THREAD

**Issue by rmalosse** [InstaPy/InstaPy#3990]
Hi, 

I already used instapy on a ubuntu server --> no problem
I have acquired a raspbery B+ and i followed the guide : https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Raspberry.md

After part ''Install Instapy'' i have 2 repertories: 

/home/pi/Instapy with : 

- logs

- assets

- db

and another repertory under /home/pi/Projects/Instapy with all configuration files, instapy repertory, docker , tests, templates, docs, 

I download chromedriver under assets and take the good rights by following part ''For Chrome''. 

And i tried to launch the basic quickstart.py by default with headless_browser parameter. It doesn't work 

ERROR [$date] [$username] Message: unknown error: Chrome failed to start: exited normaly  

(Driver info : chromedriver=2.36 (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx), platform= Linux 4.14.79-v7+ armv71)

I think the new procedure about raspberry has errors because few days ago i have tried with the old instapy all is right...

**Comment by tE3m** [comment]
First of all, don't use that Raspberry doc. There is a PR open for an update, while that isn't merged:
Remove your current InstaPy folder in `/home/pi/Projects/InstaPy/`, then run 
```
pip3 install instapy
pip3 uninstall instapy-chromedriver
pip3 install instapy-chromedriver==2.36.post0
```
That will install InstaPy and the Raspberry Pi Chromedriver as `pip` packages. Now you can create/ edit scripts.

**Comment by rmalosse** [comment]
Thanks Tarek, i removed Instapy Folder 

Next i do :
source venv37/bin/activate
pip3 install instapy

Collecting googleapis-common-protos<2,>=1.5.0 (from clarifai>=2.4.1->instapy)
  Downloading https://www.piwheels.org/simple/googleapis-common-protos/googleapis_common_protos-1.5.8-py3-none-any.whl (69kB)
    100% |████████████████████████████████| 71kB 1.7MB/s 
Installing collected packages: urllib3, idna, chardet, certifi, requests, instapy-chromedriver, configparser, EasyProcess, PyVirtualDisplay, six, regex, protobuf, googleapis-common-protos, future, jsonschema, grpcio, clarifai, plyer, emoji, PyYAML, MeaningCloud-python, selenium, instapy
  Running setup.py install for regex ... done

It stays stuck here since 20 minutes and nothing is happening...

**Comment by rmalosse** [comment]
Oh it just finished so i continue: 

(venv37) pi@raspberry:~/Projects $ pip3 uninstall instapy-chromedriver
Uninstalling instapy-chromedriver-2.44:
  Would remove:
    /home/pi/Projects/venv37/lib/python3.7/site-packages/instapy_chromedriver-2.44.dist-info/*
    /home/pi/Projects/venv37/lib/python3.7/site-packages/instapy_chromedriver/*
Proceed (y/n)? y
  Successfully uninstalled instapy-chromedriver-2.44
You are using pip version 10.0.1, however version 19.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(venv37) pi@raspberry:~/Projects $ pip3 install instapy-chromedriver==2.36.post0
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting instapy-chromedriver==2.36.post0
  Using cached https://files.pythonhosted.org/packages/41/0e/c8cac63ea1698c26cb3e8d009e1a12fb95b09cb30bbe0430bbc704a6d578/instapy_chromedriver-2.36.post0-py3-none-any.whl
instapy 0.1.3 has requirement instapy-chromedriver==2.44, but you'll have instapy-chromedriver 2.36.post0 which is incompatible.
Installing collected packages: instapy-chromedriver
Successfully installed instapy-chromedriver-2.36.post0
You are using pip version 10.0.1, however version 19.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by rmalosse** [comment]
Don't understand i don't have Instapy folder under Projects with script docker ...

**Comment by tE3m** [comment]
That only installs the core files. You can download everything else on your own (e.g. docker files if you need them)

**Comment by rmalosse** [comment]
Don't understand where is repertory with quick start, templates? I need to do this: 
git clone https://github.com/timgrossmann/InstaPy.git

I already have one Instapy repertory under : 
/home/pi/InstaPy
with db assets and logs but in assets i don't have chrome driver. 

I am lost sorry i don't understand this new process.

**Comment by tE3m** [comment]
You *don't* need to download a chromedriver anymore. And you also don't need to clone the reppsitory. I'm sure you don't need all templates, simply download the template you need.

**Comment by rmalosse** [comment]
Yes of course i just need quickstart and quickstart templates. But how download only this? And i must put in a specific folder or there is not importance?

**Comment by tE3m** [comment]
1. Simply view the file on github, copy it and send it via ssh to your pi.
2. Since the pip installation is global, the location doesn't matter

**Comment by rmalosse** [comment]
I download quickstart.py  and try again :

(venv37) pi@raspberry:~ $ python3 quickstart.py 

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
No any custom workspace provided.       ~using existing..

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-02-19 21:00:31] [xxx]  Using built in instapy-chromedriver executable (version 2.36)
Traceback (most recent call last):
  File "quickstart.py", line 18, in <module>
    headless_browser=True)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 276, in __init__
    self.set_selenium_local_session()
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 326, in set_selenium_local_session
    self.logger)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/browser.py", line 123, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/local/opt/python-3.7.0/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/opt/python-3.7.0/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/.local/lib/python3.7/site-packages/instapy_chromedriver/chromedriver_linux64'


my quickstart.py


from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace


set_workspace(path=None)

insta_username='xxx'
insta_password='www'

session = InstaPy(username=insta_username,
                    password=insta_password,
                    headless_browser=True)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_dont_include(["friend1", "friend2", "friend3"])

    session.like_by_tags(["natgeo"], amount=10)

**Comment by tE3m** [comment]
Did you install `v2.36` instead of `2.36.post0`?

**Comment by rmalosse** [comment]
2.36.post0

**Comment by tE3m** [comment]
Are you sure? In the venv? Because it says `2.36` in your error output. It should say `2.36.post0`. Please check the versions in- and outside the venv.
