### ISSUE TITLE
Cron on Raspi 3

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#3993]
## Expected Behavior
My python script is running perfectly, now I want to automate it via cron.

## Current Behavior
in the `sudo tail -f /var/log/syslog` it shows the following messages: 
`(root) CMD (cd /home/pi/InstaPy/ && sudo /usr/bin/python /home/pi/InstaPy/first.py)` and
`(CRON) info (No MTA installed, discarding output)`

So it doesnt work :(

## InstaPy configuration
My script is named first.py and sleeps in the following folder: "/home/pi/InstaPy/first.py". 
My crontab is: ` * * * * * cd /home/pi/InstaPy/ && sudo /usr/bin/python /home/pi/InstaPy/first.py`, so I run it every minute which is also shown in the syslog. 

I also disabled headless mode in my python script.

I also tried ou the solution from #1553 but it didnt worked for me :/

Thank you for help!

**Comment by tE3m** [comment]
I simply ran 
```
* * * * * python3 /path/to/script.py
```
And that worked for me.

**Comment by ghost** [comment]
@TarekJ03 Do you use root as user?

**Comment by ghost** [comment]
When I run `python3 /home/pi/InstaPy/first.py` in the terminal it works, but when I use the same path in cron (`* * * * * python3 /home/pi/InstaPy/first.py`) it doesn´t work...

**Comment by tE3m** [comment]
I don't use it as root. What do you mean "it doesn't work"? Is there any error? If you expect cron to print sth out, it doesn't. That might be misleading if you expect that.

**Comment by ghost** [comment]
Hey. I don’t expect it to print something out. I expect, because I disabled headless mode, that Chromium pops up at the time I configured, like in our example above, every minute.

**Comment by tourhuntr** [comment]
i used crontab -e as the user and the command was:
0 6 * * * cd /home/pi/projects/InstaPy  && sudo /usr/bin/python3 ./simple_but_effective.py

Started every Day 6 o'clock

**Comment by tE3m** [comment]
@johanneskapst you know what I was just thinking about? You had used `python` to run InstaPy before right? Then it's no big surprise it doesn't work with `python3`... sorry, my bad. Try either installing InstaPy with `pip3` or use 
```
python /path/to/script.py
```
Instead of python3
xD

**Comment by ghost** [comment]
@TarekJ03 Yes thats right. I will try it! Thank you!!

**Comment by ghost** [comment]
Hey ho!
Cron is working now, but I get the following error, visible in the _logs/instausername/general.log_ data, every time right after cron started the script:

INFO [2019-02-19 15:41:51] [instausername]  Using built in instapy-chromedriver executable (version 2.36.post0)
ERROR [2019-02-19 15:43:01] [instausername]  Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/browser.py", line 135, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)

Cron is starting the script right after reboot, which I do every three hours (also done by cron).

EDIT:
Also weired is that it worked one single time, but afterwards it printed that error out^^

**Comment by ghost** [comment]
Sometimes I am too dumb xD
Had to set: headless_browser to "True"

**Comment by hg8** [comment]
For those who don't want `headless_browser=True` and are having this error. You need to pass a display in your cron command:

```
* * * * * export DISPLAY=:0; /home/pi/workspace/venv37/bin/python /home/pi/workspace/quickstart.py
```
