### ISSUE TITLE
Raspberry Pi - Login error

### ISSUE THREAD

**Issue by jeepsj** [InstaPy/InstaPy#3994]
Hi,
I'm trying to run Instapy on a Raspberry Pi3 to no avail.

I have installed the last available version of Instapy and downgraded chromedriver to match Raspbian Chromium, but I'm getting a login error.

Anybody know what's the issue?
Thanks!

`python quickstart.py

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Custom workspace set: "/home/pi/InstaPy" :]

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-02-15 15:04:43] [jeepsj]  Using built in instapy-chromedriver executable (version 2.36.post0)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-02-15 15:04:47] [jeepsj]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...

........................................................
CRITICAL [2019-02-15 15:05:53] [jeepsj]  Wrong login data!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2019-02-15 15:06:00] [jeepsj]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 388 users & had 161 FOLLOWERS
[Session lasted 1.28 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-02-15 15:06:00] [jeepsj]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo

`

**Comment by tE3m** [comment]
Try using `bypass_suspicious_attempt`, or just check on your mobile. You probably get an popup saying "we detected a suspicious login attempt". Check that, then try again.

**Comment by jeepsj** [comment]
Nothing changed when using `bypass_suspicious_attempt=True`
Nothing shows up on my mobile either.

After a while the account does log in, but when it does, the Chromium window closes immediately and ends the session.

**Comment by tE3m** [comment]
Then check your login data.

**Comment by jeepsj** [comment]
There are no errors in either password or username.

**Comment by jeepsj** [comment]
After reviewing, it doesn't log in. It simply loads my profile page, without being logged in an closes everything.

**Comment by tE3m** [comment]
Do you have " or \ or ' in your pw?

**Comment by jeepsj** [comment]
No, only numbers and letters.

Just to make sure I'm doing it right here are the commands I'm running on the RPi Terminal to launch InstaPy

```
pi@raspberrypi:~/Projects $ source venv37/bin/activate
(venv37) pi@raspberrypi:~/Projects $ cd InstaPy/
(venv37) pi@raspberrypi:~/Projects/InstaPy $ python quickstart.py
```

**Comment by tE3m** [comment]
What happens when you watch InstaPy trying to log in?

**Comment by jeepsj** [comment]
I changed my password and it worked!

**Comment by tE3m** [comment]
That would've been the next step xD. Since it's fixed, I think you can close this issue now.
