### ISSUE TITLE
Crash after few Minutes with missing 1 required positional argument: 'logfolder'

### ISSUE THREAD

**Issue by tourhuntr** [InstaPy/InstaPy#3995]
## Current Behavior
Fresh Instapy Installation from yesterday

After a few minutes of running i'm getting this error message:

------
Custom workspace set: "/home/pi/projects/InstaPy" :]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-02-15 21:24:52] [xx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

...............................................................
INFO [2019-02-15 21:25:30] [xx]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-02-15 21:25:30] [xx]  Saving account progress...
INFO [2019-02-15 21:25:35] [xx]  User 'xxt' [1/8]

INFO [2019-02-15 21:26:15] [xx]  Grabbed 5 usernames from 'xxxt's `Followers` to do interaction.
INFO [2019-02-15 21:26:15] [xx]  User 'spivacmarian' [1/5]

INFO [2019-02-15 21:26:15] [xx]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 197 users & had 10475 FOLLOWERS
[Session lasted 1.41 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-02-15 21:26:15] [xxx]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "simple_but_effective.py", line 38, in <module>
    session.interact_user_followers(['xxx'], amount=5, randomize=True)
  File "/home/pi/projects/InstaPy/instapy/instapy.py", line 2591, in interact_user_followers
    validation, details = self.validate_user_call(person)
  File "/home/pi/projects/InstaPy/instapy/instapy.py", line 1079, in validate_user_call
    self.logger)
TypeError: validate_username() missing 1 required positional argument: 'logfolder'

## InstaPy configuration

while True:
    with smart_run(session):
       # general settings
       session.set_relationship_bounds(enabled=True,
                                     delimit_by_numbers=True,
                                      max_followers=15000,
                                      max_following=1500,
                                      min_followers=0,
                                      min_following=30)
       session.set_quota_supervisor(enabled=True, sleep_after=["likes"], sleepyhead=True, stochastic_flow=True, notify_me=True,peak_likes=(57, 700), peak_follows=(48, None), peak_unfollows=(35, 402), peak_server_calls=(500, None))
       session.set_user_interact(amount=3, randomize=False, percentage=100, media='Photo')
       session.set_do_like(enabled=True, percentage=100)
       session.interact_user_followers(['xxx'], amount=5, randomize=True)

**Comment by tourhuntr** [comment]
did a complete reset of the pi and installed complete new because there are too much wrong.

**Comment by KMLnk** [comment]
Hi
you must change validate_user_call Function in the "instapy.py" line "1208", to:

```
    def validate_user_call(self, user_name):
        """ Short call of validate_username() function """
        validation, details = validate_username(self.browser,
                                                user_name,
                                                self.username,
                                                self.ignore_users,
                                                self.blacklist,
                                                self.potency_ratio,
                                                self.delimit_by_numbers,
                                                self.max_followers,
                                                self.max_following,
                                                self.min_followers,
                                                self.min_following,
                                                self.min_posts,
                                                self.max_posts,
                                                self.skip_private,
                                                self.skip_private_percentage,
                                                self.skip_no_profile_pic,
                                                self.skip_no_profile_pic_percentage,
                                                self.skip_business,
                                                False,
                                                self.skip_business_percentage,
                                                self.skip_business_categories,
                                                self.dont_skip_business_categories,
                                                self.logger,
                                                self.logfolder)
        return validation, details
```
