### ISSUE TITLE
Issue gathering liker's of a video post. 

### ISSUE THREAD

**Issue by crowg** [InstaPy/InstaPy#3996]
I've been having a issue where I get this message. 

"INFO [2019-02-15 14:58:55] [***********]  Post 1  |  Likers: found 78, catched 78

INFO [2019-02-15 14:59:24] [***********]  Failed to get likers count on your post 2
INFO [2019-02-15 14:59:51] [***********]  Failed to get likers count on your post 3
INFO [2019-02-15 15:00:18] [***********]  Failed to get likers count on your post 4
INFO [2019-02-15 15:00:45] [***********]  Failed to get likers count on your post 5
INFO [2019-02-15 15:00:45] [***********]  Gathered total of 78 unique active followers from the latest 5 posts in 2 minutes and 15 seconds"

It only seems to be happening on a video post. I have tried to look up solutions but they all seem to be for "photo post". I don't want to ruin any code by changing something that didn't need to be changed. can someone help me out. I think this is happening from confusion between viewers and likes on the post.

**Comment by crowg** [comment]
anything?

**Comment by clevebounce** [comment]
same problem here

**Comment by clevebounce** [comment]
any solution yet?

**Comment by crowg** [comment]
nope... @timgrossmann
