### ISSUE TITLE
Unfollow_after - gets either ignored or missinterpreted

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#3997]
## Expected Behavior
To unfollow users after following them for a set interval of time
## Current Behavior
With the configuration below, a bunch of users were loaded and unfollowed. I followed these users in the morning of that very day :(
## Possible Solution (optional)
I wish I knew
## InstaPy configuration

Latest version
disable_image_load=True)
session.login()
session.unfollow_users(amount=500, allFollowing=True, style="FIFO", unfollow_after=138*60*60, sleep_delay=5100)
session.end()

**Comment by Tachenz** [comment]
One example would be - the script with configuration above just unfollowed user:
iren_suzi

While all_followed csv has it -  2019-02-15 17:28 ~ iren_suzi ~ 3508584442   (e.g. followed yesterday)

**Comment by tE3m** [comment]
InstaPy can't know when *you* followed a user. That feature is only applicable on users followed by InstaPy.

**Comment by Tachenz** [comment]
@tarekj03 thank you - but do you mean:
1) This feature will work only IF using followed by instapy = True method
or
2) With allFollowers=True for users followed by instapy?
(as I don’t follow manually from the account, all the users are followed by instapy really)

ps. as the user in the example above was in the all followed pool csv and had the date of follow as well...

**Comment by tE3m** [comment]
Okay, I meant that the `unfollow_after` can only be applied to users followed by InstaPy, but if you say they were followed by InstaPy, I don't really have a clue

**Comment by Tachenz** [comment]
So what seems to be happening is this, after some testing:

You know when it loads users first (say 500/500). And then it vetoes them against unfollow_after function, saying something like 
“100/500 are eligible under unfollow_after condition”.

So that step got skipped 3 out of 10 times (resulting unfollow_after to be ignored 3 times our of 10 - and it just starts unfollowing 500/500). It worked during the other 7 attempts though...
