### ISSUE TITLE
instapy on Android

### ISSUE THREAD

**Issue by 10000hzl** [InstaPy/InstaPy#4008]
Hi, is there a way to run instapy on an Android device? Thanks :)

**Comment by tE3m** [comment]
If there is a python interpreter for Android that can install packages via `pip` it might be possible. Depends on your Chrome version and if there is an ARM binary for the corresponding Chromedriver.

**Comment by blkrt** [comment]
See this :
https://medium.com/@erfanghaffarie/install-and-running-instapy-on-android-b4b8dae85d5f
