### ISSUE TITLE
Interact with list of Accounts

### ISSUE THREAD

**Issue by kushpvo** [InstaPy/InstaPy#401]
Is it possible to provide a list of usernames and the bot will interact with the followers of that account?

**Comment by timgrossmann** [comment]
@kushpvo Sadly, that feature is not implemented by now...
I'm sorry

**Comment by kushpvo** [comment]
If it's possible, do work on it. It would be a really efficient feature for this script! 
Thanks a ton :)

**Comment by timgrossmann** [comment]
[You can help make it happen](https://www.patreon.com/InstaPy)
