### ISSUE TITLE
Chromedriver not in PATH (since the update, no assets folder to put it in after the install)

### ISSUE THREAD

**Issue by christinetanx** [InstaPy/InstaPy#4014]
## Expected Behavior
Running the quickstart_template

## Current Behavior
![image](https://user-images.githubusercontent.com/33068237/53020273-8e288d00-3424-11e9-9659-90c1fa09ca79.png)

## Possible Solution (optional)
I've tried uninstalling and reinstalling Python but that didn't really seem to have an effect. Not sure what to do next

## InstaPy configuration
Nothing regarding InstaPy was modified.

**Comment by iLeGiTiMx** [comment]
Just install requirements.txt again. There isn´t an assets folder anymore, it is working without it, just install it again :)

**Comment by christinetanx** [comment]
@iLeGiTiMx How would you do that? :)

**Comment by tE3m** [comment]
```
pip install instapy
```
That's it. Make sure to backup your files (scripts, db, logs(optional)) and put them into the new workspace folder. Then you can remove your old one.

**Comment by christinetanx** [comment]
@TarekJ03 So, remove the scripts, db, logs folders in Python then re-install? Because I did do the pip install instapy but with that, the chromedriver error popped up.

**Comment by tE3m** [comment]
Installing InstaPy from `pip` and using the old folder although is good for nothing. It'll import the `instapy` package from inside the folder instead of the `pip` installation. Back your files up, then remove the old folder. From now on it'll use the `pip` installation

**Comment by christinetanx** [comment]
@TarekJ03 Omg, that was it. Thank you!!!!!

For others - to remove and reinstall instapy, remove all folders that have Instapy in your Python folder under C:\Users\(your name)\AppData\Local\Programs\Python\Python37-32\Lib\site-packages if that's where your Python folder is located
