### ISSUE TITLE
Regex is not a package RaspberryPi

### ISSUE THREAD

**Issue by sk-t3ch** [InstaPy/InstaPy#4018]
After following the Raspberry Pi set up tutorial, I tried running the quickstart.py script.

I received an error of:
```  File "quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File "/home/pi/Projects/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 22, in <module>
    from .comment_util import comment_image
  File "/home/pi/Projects/InstaPy/instapy/comment_util.py", line 8, in <module>
    from .util import update_activity
  File "/home/pi/Projects/InstaPy/instapy/util.py", line 7, in <module>
    import regex
  File "/home/pi/Projects/venv37/lib/python3.7/site-packages/regex.py", line 400, in <module>
    import regex._regex_core as _regex_core
ModuleNotFoundError: No module named 'regex._regex_core'; 'regex' is not a package
```

And after searching why it occurred, I found out that python uses the `re` module in python3 not the `regex`.

Am I wrong? What can I do to get around this? 
Please help :)

**Comment by mkMcMahon** [comment]
I'm getting the same error when trying to install on mac osx

**Comment by sk-t3ch** [comment]
i think i remember seeing something in an earlier thread about needing to install x-code @mkMcMahon - this is specifically for a pi

**Comment by joanroig** [comment]
Same error here, I tried running the regex install with sudo with no success

**Comment by mkMcMahon** [comment]
@sebastiankelly123 yes this is similar to #4021 where @xander8 is using Ubuntu instead of raspbian ... I already have  xcode installed. Think it could be deeper ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Xander8** [comment]
Does anyone have a git branch where we can identify, when this bug started?

**Comment by timgrossmann** [comment]
Could you guys please try this: 
https://github.com/InstaPy/instapy-docs/blob/master/BUILD_TOOLS.md

And report back?

**Comment by ohduran** [comment]
Hi @timgrossmann, same issue here, with the added difficulty that I want to run it in a docker container. How should I do it? 

Thanks in advance,
Alvaro.

**Comment by mkMcMahon** [comment]
when I run the command:
xcode-select -print-path
I am returned with this:
/Library/Developer/CommandLineTools

I'm running mac osx.
