### ISSUE TITLE
Regex Issue

### ISSUE THREAD

**Issue by gregorio626** [InstaPy/InstaPy#4021]
I expect this script to run. 

I just ran the installation file for linux on the instapy_quickstart project(created by the same person. Same as this repo but with less files)getting an error:

python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/usr/local/lib/python3.6/dist-packages/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 22, in <module>
    from .comment_util import comment_image
  File "/usr/local/lib/python3.6/dist-packages/instapy/comment_util.py", line 8, in <module>
    from .util import update_activity
  File "/usr/local/lib/python3.6/dist-packages/instapy/util.py", line 7, in <module>
    import regex
  File "/usr/local/lib/python3.6/dist-packages/regex.py", line 400, in <module>
    import regex._regex_core as _regex_core
ModuleNotFoundError: No module named 'regex._regex_core'; 'regex' is not a package

**Comment by Xander8** [comment]
I am getting same error, this is with the "regex>=2018.11.22" dependency satisfied. 

Also there is another open issue for this, with comments. 


Duplicate of #4018

**Comment by Xander8** [comment]
> I am getting same error, this is with the "regex>=2018.11.22" dependency satisfied.
> 
> Also there is another open issue for this, with comments.
> 
> Duplicate of #4018

I am running on Ubuntu 16.04 and getting this Error output.

**Comment by alfijuan** [comment]
Hey guys, i had this issue too but was able to fix it.

This issue is related to a new version of regex launched on Feb 19.
Downgrading to the older version of it should work.

Simply run `pip install regex==2019.02.18`

**Comment by sk-t3ch** [comment]
Apologies, I remembered I was using another Pi image (next cloud). I put on the recommended raspbian image in the tutorial and now everything works fine.

**Comment by timgrossmann** [comment]
If problem persists, try: https://github.com/InstaPy/instapy-docs/blob/master/BUILD_TOOLS.md
