### ISSUE TITLE
Question - Instagram DM Bot?

### ISSUE THREAD

**Issue by sohumsanu** [InstaPy/InstaPy#4023]
Hi All, 

Does anyone know of a GitHub project that has a program where you can dm new followers a certain message, and stuff as such? 

If not, would anyone like to help me create one - I am pretty skilled in python and Java so I think ill be able to make it I'm just not sure how to start. 

Thanks!

**Comment by timgrossmann** [comment]
@awesome205 Sorry no. And we from InstaPy don't like that feature so this is really not the right place to advertise or search for something like this, sorry.
