### ISSUE TITLE
Action blocked not showing up in log

### ISSUE THREAD

**Issue by HermanoCrespo** [InstaPy/InstaPy#4025]
Hello

first off, I made sure my files are up to date.

I am gettig action blocked. The account is 3 years old with 6000 followers, 1000 Following.
Instapy took it from 2400 to 6000 over a year.

Settings:
- Liking only. 
- No Follow/Unfollow, 
- no commenting
- 24/7 script, 
- quota supervisor @ 1500 daily like limit, 
- 8 hours rest time.
- Bot runs at home, no datacenter.
- usage of follow_likers() for interactions with interact=True (2 times) and following disabled by commenting it out in instapy.py

Here is the odd bit:
I get the block in the app on the phone and the tablet. Not using the bot. It reports liking in genreral.log. However, if I check the links to the posts, the account has not liked them. That's an issue. 

I've not seen the browser window, running headless on the raspberry pi.

I've been seeing really anemic growth for days now and that got me thinking, have I been blocked all these days without realizing because I do not use the app and do not see it in the log?

I don't have a monitor for the pi so it is hard to see what's exactly happening. Might be replicable with a test account. 

Laying off for now. Tread carefully.

**Comment by gitpatrickhub** [comment]
Same issue running headless on Raspberry Pi 3. I am able to unfollow using InstaPy though. Trying to confirm if it is just a like ban.

**Comment by sionking** [comment]
when not setting it properly headless is detected

**Comment by platramos** [comment]
I've been having the same issues lately. My likes show up in the log, but not in the actual post. Comments; however, are still showing up.

**Comment by platramos** [comment]
I was able to finally solve this issue by turning headless mode off. I don't think the amount of likes, comments, follows is what got me blocked because I tried various amounts and I still got blocked. Only turning off headless mode made a difference. I'm currently running the script in a docker container on digital ocean.

**Comment by jinayG** [comment]
I am getting the same problem. I have stopped the script since two weeks. But it still says action blocked when I follow somebody in the app. However, after clicking it still follows the person despite showing the error message.

I am running the script on aws.
