### ISSUE TITLE
Linux Setup

### ISSUE THREAD

**Issue by kushpvo** [InstaPy/InstaPy#403]
Hello

I'm trying to set this up on a Digital Ocean Ubuntu but i'm unable to run it. There are no instructions on how to run and setup files. Please help!

**Comment by timgrossmann** [comment]
@kushpvo There even is a step by step instruction for DO... [Ubuntu Setup](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu.md)

**Comment by kushpvo** [comment]
@timgrossmann Yes I did follow that but i don't know what to do after that

**Comment by kushpvo** [comment]
@timgrossmann Could you please help me with the following?
1. How to change parameters in linux?
2. how to run the bot in linux?
