### ISSUE TITLE
how to set up a continuous session?

### ISSUE THREAD

**Issue by imsquare** [InstaPy/InstaPy#4030]
I'm using a modified version of the "target_followers_of_similar_accounts_and_influencers" template via CMD on windows 10 and I'm trying to set up a continuous session.

Right now the program will run for about an hour before it hits the "end of session" and requires that I "press any key to continue..." Is there any way to prevent this so that I don't have to press a key and the session just keeps running until I close the program?

**Comment by newcodemarc** [comment]
I would also be interested in that. I tried it with the scheduling but did not work for me always crashed :(

**Comment by tE3m** [comment]
You can do it. Put your script inside of an infinite loop.

**Comment by badmobile** [comment]
```
~~~~
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chuck-23** [comment]
> You can do it. Put your script inside of an infinite loop.

How can you do this?

**Comment by tE3m** [comment]
Put `while True:` in the line before you start the session via `with smart_run(session):`
```
while True:
    with smart_run(session):
        <script>
```

**Comment by chuck-23** [comment]
So it would look something like this?

    #activity
        while True:
            with smart_run(session):
            session.follow_likers(['username'], photos_grab_amount = 3, follow_liker...
            session.follow_commenters(['username'], amount=100, daysold=3, max_pic =...
            session.like_by_feed(amount=500, randomize=True, unfollow=True, interact=Tr...
            session.unfollow_users(amount=1500, allFollowing=True, style="LIFO",  unfoll...

`

**Comment by tE3m** [comment]
You need to indent everything after `with smart_run(session):` by clicking tab

**Comment by newcodemarc** [comment]
mhm I did indent everything after while True: and also after with but did not work for me

**Comment by TylerDavidBailey** [comment]
You need to end the session at the end of each loop. Warning: Keep the interactions very conservative and use a set_quota_supervisor, you may get a soft ban running it 24/7 without using set_quota_supervisor. 
```
#activity
    while True:
        with smart_run(session):
        session.follow_likers(['username'], photos_grab_amount = 3, follow_liker...
        session.follow_commenters(['username'], amount=100, daysold=3, max_pic =...
        session.like_by_feed(amount=500, randomize=True, unfollow=True, interact=Tr...
        session.unfollow_users(amount=1500, allFollowing=True, style="LIFO",  unfoll...
        session.end()
```

**Comment by chuck-23** [comment]
Where can I find the recommended `set_quota_supervisor` so I do not get banned? Another thing, Is there any possibility that I can follow likes or comments of locations I think right now I only follow th users of photos?

**Comment by chuck-23** [comment]
I'm using this template, but I am not getting it work with `while true` I text my script:

    """
    This template is written by @the-unknown
    
    What does this quickstart script aim to do?
    - This is my template which includes the new QS system.
      It includes a randomizer for my hashtags... with every run, it selects 10
      random hashtags from the list.
    
    NOTES:
    - I am using the bot headless on my vServer and proxy into a Raspberry PI I have at home, to always use my home IP to connect to Instagram. In my comments, I always ask for feedback, use more than 4 words and always have emojis. My comments work very well, as I get a lot of feedback to my posts and profile visits since I use this tactic.
    
      As I target mainly active accounts, I use two unfollow methods. 
      The first will unfollow everyone who did not follow back within 12h.
      The second one will unfollow the followers within 24h.
    """
    
    # !/usr/bin/python2.7
    import random
    from instapy import InstaPy
    from instapy import smart_run
    
    # get a session!
    session = InstaPy(username='username', password='password', headless_browser=True)
    
    # let's go! :>
    while True:
    with smart_run(session):
        hashtags = ['travelcouples', 'travelcommunity', 'passionpassport',
                    'travelingcouple',
                    'backpackerlife', 'travelguide', 'travelbloggers',
                    'travelblog', 'letsgoeverywhere',
                    'travelislife', 'stayandwander', 'beautifuldestinations',
                    'moodygrams',
                    'ourplanetdaily', 'travelyoga', 'travelgram', 'sunsetporn',
                    'lonelyplanet',
                    'igtravel', 'instapassport', 'travelling', 'instatraveling',
                    'travelingram',
                    'mytravelgram', 'skyporn', 'traveler', 'sunrise',
                    'sunsetlovers', 'travelblog',
                    'sunset_pics', 'visiting', 'ilovetravel',
                    'photographyoftheday', 'sunsetphotography',
                    'explorenature', 'landscapeporn', 'exploring_shotz',
                    'landscapehunter', 'colors_of_day',
                    'earthfocus', 'ig_shotz', 'ig_nature', 'discoverearth',
                    'thegreatoutdoors']
        random.shuffle(hashtags)
        my_hashtags = hashtags[:10]
    
        # general settings
        session.set_dont_include(["usernames"])
        session.set_mandatory_language(enabled=True, character_set='LATIN')
        session.set_dont_like(['sad', 'rain', 'depression'])
        session.set_do_follow(enabled=True, percentage=40, times=1)
        session.set_do_comment(enabled=True, percentage=30)
        session.set_comments([
                             u'What an amazing shot! :heart_eyes: What do '
                             u'you think of my recent shot?',
                             u'What an amazing shot! :heart_eyes: I think '
                             u'you might also like mine. :wink:',
                             u'Wonderful!! :heart_eyes: Would be awesome if '
                             u'you would checkout my photos as well!',
                             u'Wonderful!! :heart_eyes: I would be honored '
                             u'if you would checkout my images and tell me '
                             u'what you think. :wink:',
                             u'This is awesome!! :heart_eyes: Any feedback '
                             u'for my photos? :wink:',
                             u'This is awesome!! :heart_eyes:  maybe you '
                             u'like my photos, too? :wink:',
                             u'I really like the way you captured this. I '
                             u'bet you like my photos, too :wink:',
                             u'I really like the way you captured this. If '
                             u'you have time, check out my photos, too. I '
                             u'bet you will like them. :wink:',
                             u'Great capture!! :smiley: Any feedback for my '
                             u'recent shot? :wink:',
                             u'Great capture!! :smiley: :thumbsup: What do '
                             u'you think of my recent photo?'],
                         media='Photo')
        session.set_do_like(True, percentage=70)
        session.set_delimit_liking(enabled=True, max=100, min=0)
        session.set_delimit_commenting(enabled=True, max=20, min=0)
        session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=3000,
                                    max_following=2000,
                                    min_followers=100,
                                    min_following=50)

        session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "follows"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(100, 1000),
                                 peak_comments=(21, 250),
                                 peak_follows=(200, None))

        session.set_user_interact(amount=1, randomize=False, percentage=40)

        # activity
        session.like_by_tags(my_hashtags, amount=60, media=None)
        session.unfollow_users(amount=750, allFollowing=True, style="LIFO", unfollow_after=3*60*60, sleep_delay=450)
        session.end()

**Comment by newcodemarc** [comment]
I solved it with this one here. First I also had it like you infront of the `with smart run` but you also need to indent the entire block after your `while true` by one tab.

part of my code: 


```
while True:
    session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True,
                  multi_logs=True)

    with smart_run(session):
        # HEY HO LETS GO
        # general settings
        session.set_dont_include(friends)
        session.set_dont_like(dont_likes)
        session.set_ignore_if_contains(ignore_list)
        session.set_ignore_users(ignore_users)
        session.set_simulation(enabled=True)

        session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                                  peak_likes=(140, 1000),
                                   peak_comments=(30, 130),
                                    peak_follows=(50, 300),
                                     peak_unfollows=(300, 350),
                                      peak_server_calls=(None, 12000))

```

**Comment by chuck-23** [comment]
So I would leave something like this? I really appreciate you help! It still doesn't work...

    # !/usr/bin/python2.7
    import random
    from instapy import InstaPy
    from instapy import smart_run
    
    # get a session!
    while True:
    session = InstaPy(username='username', password='password', headless_browser=True)
    
    # let's go! :>
    # general settings
        with smart_run(session):
        session.set_dont_include(["usernames"])
        session.set_mandatory_language(enabled=True, character_set='LATIN')
        hashtags = ['travelcouples', 'travelcommunity', 'passionpassport',
                    'travelingcouple',
                    'backpackerlife', 'travelguide', 'travelbloggers',
                    'travelblog', 'letsgoeverywhere',
                    'travelislife', 'stayandwander', 'beautifuldestinations',
                    'moodygrams',
                    'ourplanetdaily', 'travelyoga', 'travelgram', 'sunsetporn',
                    'lonelyplanet',
                    'igtravel', 'instapassport', 'travelling', 'instatraveling',
                    'travelingram',
                    'mytravelgram', 'skyporn', 'traveler', 'sunrise',
                    'sunsetlovers', 'travelblog',
                    'sunset_pics', 'visiting', 'ilovetravel',
                    'photographyoftheday', 'sunsetphotography',
                    'explorenature', 'landscapeporn', 'exploring_shotz',
                    'landscapehunter', 'colors_of_day',
                    'earthfocus', 'ig_shotz', 'ig_nature', 'discoverearth',
                    'thegreatoutdoors']
        random.shuffle(hashtags)
        my_hashtags = hashtags[:10]
   
        session.set_dont_like(['sad', 'rain', 'depression'])
        session.set_do_follow(enabled=True, percentage=40, times=1)
        session.set_do_comment(enabled=True, percentage=30)
        session.set_comments([
                             u'What an amazing shot! :heart_eyes: What do '
                             u'you think of my recent shot?',
                             u'What an amazing shot! :heart_eyes: I think '
                             u'you might also like mine. :wink:',
                             u'Wonderful!! :heart_eyes: Would be awesome if '
                             u'you would checkout my photos as well!',
                             u'Wonderful!! :heart_eyes: I would be honored '
                             u'if you would checkout my images and tell me '
                             u'what you think. :wink:',
                             u'This is awesome!! :heart_eyes: Any feedback '
                             u'for my photos? :wink:',
                             u'This is awesome!! :heart_eyes:  maybe you '
                             u'like my photos, too? :wink:',
                             u'I really like the way you captured this. I '
                             u'bet you like my photos, too :wink:',
                             u'I really like the way you captured this. If '
                             u'you have time, check out my photos, too. I '
                             u'bet you will like them. :wink:',
                             u'Great capture!! :smiley: Any feedback for my '
                             u'recent shot? :wink:',
                             u'Great capture!! :smiley: :thumbsup: What do '
                             u'you think of my recent photo?'],
                         media='Photo')
        session.set_do_like(True, percentage=70)
        session.set_delimit_liking(enabled=True, max=100, min=0)
        session.set_delimit_commenting(enabled=True, max=20, min=0)
        session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=3000,
                                    max_following=2000,
                                    min_followers=100,
                                    min_following=50)

        session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "follows"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(100, 1000),
                                 peak_comments=(21, 250),
                                 peak_follows=(200, None))

        session.set_user_interact(amount=1, randomize=False, percentage=40)

        # activity
        session.like_by_tags(my_hashtags, amount=60, media=None)
        session.unfollow_users(amount=750, allFollowing=True, style="LIFO", unfollow_after=3*60*60, sleep_delay=450)
        session.end()

**Comment by newcodemarc** [comment]
almost. Everything after while True: must move a little back.
This should work try it out:
```
# get a session!
while True:
    session = InstaPy(username='username', password='password', headless_browser=True)

    # let's go! :>
    # general settings
        with smart_run(session):
        session.set_dont_include(["usernames"])
        session.set_mandatory_language(enabled=True, character_set='LATIN')
        hashtags = ['travelcouples', 'travelcommunity', 'passionpassport',
                    'travelingcouple',
                    'backpackerlife', 'travelguide', 'travelbloggers',
                    'travelblog', 'letsgoeverywhere',
                    'travelislife', 'stayandwander', 'beautifuldestinations',
                    'moodygrams',
                    'ourplanetdaily', 'travelyoga', 'travelgram', 'sunsetporn',
                    'lonelyplanet',
                    'igtravel', 'instapassport', 'travelling', 'instatraveling',
                    'travelingram',
                    'mytravelgram', 'skyporn', 'traveler', 'sunrise',
                    'sunsetlovers', 'travelblog',
                    'sunset_pics', 'visiting', 'ilovetravel',
                    'photographyoftheday', 'sunsetphotography',
                    'explorenature', 'landscapeporn', 'exploring_shotz',
                    'landscapehunter', 'colors_of_day',
                    'earthfocus', 'ig_shotz', 'ig_nature', 'discoverearth',
                    'thegreatoutdoors']
        random.shuffle(hashtags)
        my_hashtags = hashtags[:10]

        session.set_dont_like(['sad', 'rain', 'depression'])
        session.set_do_follow(enabled=True, percentage=40, times=1)
        session.set_do_comment(enabled=True, percentage=30)
        session.set_comments([
                             u'What an amazing shot! :heart_eyes: What do '
                             u'you think of my recent shot?',
                             u'What an amazing shot! :heart_eyes: I think '
                             u'you might also like mine. :wink:',
                             u'Wonderful!! :heart_eyes: Would be awesome if '
                             u'you would checkout my photos as well!',
                             u'Wonderful!! :heart_eyes: I would be honored '
                             u'if you would checkout my images and tell me '
                             u'what you think. :wink:',
                             u'This is awesome!! :heart_eyes: Any feedback '
                             u'for my photos? :wink:',
                             u'This is awesome!! :heart_eyes:  maybe you '
                             u'like my photos, too? :wink:',
                             u'I really like the way you captured this. I '
                             u'bet you like my photos, too :wink:',
                             u'I really like the way you captured this. If '
                             u'you have time, check out my photos, too. I '
                             u'bet you will like them. :wink:',
                             u'Great capture!! :smiley: Any feedback for my '
                             u'recent shot? :wink:',
                             u'Great capture!! :smiley: :thumbsup: What do '
                             u'you think of my recent photo?'],
                         media='Photo')
        session.set_do_like(True, percentage=70)
        session.set_delimit_liking(enabled=True, max=100, min=0)
        session.set_delimit_commenting(enabled=True, max=20, min=0)
        session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=3000,
                                    max_following=2000,
                                    min_followers=100,
                                    min_following=50)

        session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "follows"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(100, 1000),
                                 peak_comments=(21, 250),
                                 peak_follows=(200, None))

        session.set_user_interact(amount=1, randomize=False, percentage=40)

        # activity
        session.like_by_tags(my_hashtags, amount=60, media=None)
        session.unfollow_users(amount=750, allFollowing=True, style="LIFO", unfollow_after=3*60*60, sleep_delay=450)
        session.end()
```

**Comment by tE3m** [comment]
And you also shouldn't set a shebang with python2.7 xD

**Comment by chuck-23** [comment]
A little note, I do not understand in that script what this means `percentage=40`:

    session.set_do_follow(enabled=True, percentage=40, times=1)

**Comment by chuck-23** [comment]
The script does not run in a loop, It suddenly stops an closes the terminal window. Any idea?

**Comment by tE3m** [comment]
Maybe add a `session.end()` to the end of the loop
