### ISSUE TITLE
Definetly not working on Raspberry Pi (3B+) - *Updated Instructions*

### ISSUE THREAD

**Issue by andifds** [InstaPy/InstaPy#4033]
Ok, I got InstaPy running multiples times before the big update, even with some small issues with chromedriver. But recent update broke everything on RPi. I've reinstaled clean raspbian, this time Lite only with CLI and got nothing.

Followed instruction step by step, but it's impossible to make it work. There are some issues on the How To doc available to RPi

1. No assets folder, so is not clearly if it must be created under InstaPy dir from git or wherever
2. No clues about creating a venv and how this supports the current installation (why is this necesary? *Personal doubt
3. It's possible to install InstaPy only using `pip install instapy` on RPi??

## Current Behavior
After installing using How To Instructions and after `python3 -m pip install --user .` command, used this command under InstaPy dir, on venv37 active:

`python quickstart.py --username myusername --password mypassword`

to test the initation of script. The result was this:

`Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File "/home/pi/Projects/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

Then used:
`python3 quickstart.py --username myusername --password mypassword`

And the result was:
```
._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-02-20 20:39:12] [myusername]  Using built in instapy-chromedriver executable (version 2.44)
Traceback (most recent call last):
  File "quickstart.py", line 14, in <module>
    headless_browser=True)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 279, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 331, in set_selenium_local_session
    self.logger)
  File "/home/pi/Projects/InstaPy/instapy/browser.py", line 135, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/local/opt/python-3.7.0/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/opt/python-3.7.0/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/.local/lib/python3.7/site-packages/instapy_chromedriver/chromedriver_linux64'
```

## Possible Solution (optional)

By now, I will have to use my dual boot ubuntu to use the InstaPy, would be great a bit of help for all the users of RPi.

**Comment by rmalosse** [comment]
Same problem since remove asset folder ...

**Comment by joanroig** [comment]
I magically got it working using pip3 and python3.5, but then I have other internal issues as well :S

**Comment by imjustin** [comment]
Broken for me as well. I don't know the code well enough to dig through but I suspect it has to do with the fact that RPI3+ doesn't support the newest chromedrivers,

**Comment by joanroig** [comment]
> Broken for me as well. I don't know the code well enough to dig through but I suspect it has to do with the fact that RPI3+ doesn't support the newest chromedrivers,

Try to create the assets folder, and rename your chromedriver to chromedriver_linux, it solved my chromedriver issues.

**Comment by imjustin** [comment]
This is the error I'm getting now, which was after changing the filename from "chromedriver" to "chromedriver_linux"
```
Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    session = InstaPy(username="xxxx", password="xxxx")
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 276, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 328, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /home/pi/InstaPy/assets/chromedriver_linux

```

**Comment by joanroig** [comment]
@imjustin you've exposed your password

**Comment by imjustin** [comment]
> @imjustin you've exposed your password

LOL and this is why i don't comment on github. because i'm utter noob at this. thanks.

**Comment by tE3m** [comment]
Guys, you have to **uninstall** `instapy-chromedriver` with pip since the v2.44's binary doesn't fit the Raspberry's ARM structure. Then install `instapy-chromedriver==2.36.post0`

**Comment by orhan-drsn** [comment]
How can we uninstall the old driver and install the new driver on RPi? 
Will be there a guide (like earlier) for a clean install?

**Comment by HanschDennis** [comment]
@orhan-drsn It should work with:
`python3 -m pip install instapy-chromedriver==2.36.post0`

My InstaPy on RaspberryPi 3B works now.
I use:
-Raspbian Stretch
-Python 3.5
-Chromedriver 2.36
-Chromium 65

**Comment by orhan-drsn** [comment]
I have the same configuration and I installed it like you said. 

It doesn't work for me.😭

**Comment by tE3m** [comment]
What does it print out?

**Comment by orhan-drsn** [comment]
@TarekJ03 
`Traceback (most recent call last):`
`File "quickstart.py", line 4, in <module>`
`   from instapy import InstaPy `
`File "/home/pi/Projects/instapy/instapy/__init__.py", line 3, in <module>`
`   from .instapy import InstaPy `
`File "/home/pi/Projects/instapy/instapy/instapy.py", line 22, in <module> `
`   from .comment_util import comment_image `
`File "/home/pi/instapy/instapy/comment_util.py", line 8, in <module>`
`   from .util import update_activity `
`File "/home/pi/instapy/instapy/util.py", line 7, in <module>`
`   import regex`
`ImportError: No module named regex`

**Comment by tE3m** [comment]
Do you use `python` or `python3` to start the script? Depending on that, run
```
pip/pip3 install regex
```

**Comment by imjustin** [comment]
Where can I go to find a chromium 65? When I do apt-get install chromium, it installs 72.

**Comment by tE3m** [comment]
72 on a RPi?!:flushed:

**Comment by imjustin** [comment]
haha it didn't work. completely broken. but that's what got installed... so idk why that's happening or how to force it to install an older version

**Comment by tE3m** [comment]
I mean... v72 means that you added that version's download link manually via `deb`. Is it possible that you did that/followed a tutorial where this was described? If so, I'd like to know how you installed v72 on an ARM machine since support for ARM is officially dropped since v65.

**Comment by imjustin** [comment]
how can i reset that so it doesn't download the incorrect version? i've tried so many different things that it's totally possible i did exactly what you said. 

and when i say installed, i think it installed with errors, and it crashed on load so I don't think that counts ahha

**Comment by tE3m** [comment]
I would recommend a fresh install, if that's an option to you

**Comment by imjustin** [comment]
ugh yeah at this point i'm going to try that. time to go back to square one

**Comment by andifds** [comment]
> 
> 
> I would recommend a fresh install, if that's an option to you

I made a fresh install, but then I made so many changes that finally I don't know what was wrong. Could you please comment wiich are the extra steps to follow after the How To available. This considering that using
`python3 -m pip install instapy-chromedriver==2.36.post0` seems logic for the RPi compatibility

> 
> 
> Guys, you have to **uninstall** `instapy-chromedriver` with pip since the v2.44's binary doesn't fit the Raspberry's ARM structure. Then install `instapy-chromedriver==2.36.post0`

Also, should be great to note when this step should be done and which is the exact command to uninstall the first chromedriver. This because in my case, could't uninstall because wasn't installed yet (?).

I know this finally could seems more like a support page than an issues fix but definetly this could help to update the current instructions on the How To Raspberry.

**Comment by tE3m** [comment]
There are literally 3 steps required on a fresh install (but update and upgrade should be done nonetheless) :
```
pip3 install instapy
pip3 uninstall instapy-chromedriver
pip3 install instapy-chromedriver==2.36.post0
```
Now you have the InstaPy core files and the chromedriver that's compatible with an RPi.


_Sent from my Galaxy S9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by andifds** [comment]
> 
> 
> There are literally 3 steps required on a fresh install (but update and upgrade should be done nonetheless) :
> 
> ```
> pip3 install instapy
> pip3 uninstall instapy-chromedriver
> pip3 install instapy-chromedriver==2.36.post0
> ```
> 
> Now you have the InstaPy core files and the chromedriver that's compatible with an RPi.
>
So, according to this, the correct installation method for RPi is using `pip3 install instapy` and not the git clone mode? or what? Anyway, I will try it again.

**Comment by tE3m** [comment]
The 'correct'/recommended and easy installation is `pip`, not just on RPi, but on any device. The document is going to be changed soon.

**Comment by imjustin** [comment]
Fresh install seems to be working for me now. Not a great solution but it works. All i've run is the most basic quickstart, so jury is still out on longer runs and the rest of the features. but it logged in, and went to the natgeo tag properly

**Comment by andifds** [comment]
Nice! Could you please specify the method &steps and system configuration
used to make it work? Thanks

**Comment by imjustin** [comment]
clean reinstall of raspbian on a rp3+

sudo apt-get update
sudo apt-get upgrade
pip3 install instapy
pip3 uninstall instapy-chromedriver
pip3 install instapy-chromedriver==2.36.post0
sudo apt-get install chromium-browser (raspbian by default ships with chromium 60, installing new version gets you 65)

that was basically it.

**Comment by orhan-drsn** [comment]
But this will only work wirh the "normal" rasbian.
Is pip3 working on Stretch Lite?

**Comment by imjustin** [comment]
if you've already tried it and it doesn't work, I'd guess not. my best guess is that stretch lite removes too much, so even though you may be running headless mode selenium doesn't work properly.

**Comment by andifds** [comment]
> 
> 
> clean reinstall of raspbian on a rp3+
> 
> sudo apt-get update
> sudo apt-get upgrade
> pip3 install instapy
> pip3 uninstall instapy-chromedriver
> pip3 install instapy-chromedriver==2.36.post0
> sudo apt-get install chromium-browser (raspbian by default ships with chromium 60, installing new version gets you 65)
> 
> that was basically it.



> 
> 
> But this will only work wirh the "normal" rasbian.
> Is pip3 working on Stretch Lite?

Ok, I made it. On a fresh and clean install of **Raspbian Stretch Lite**. These are all the steps I followed to make the script start, from CLI via SSH. My RPi is an **Raspberry Pi 3B+**
### Installation ###
```
sudo apt-get update && sudo apt-get -y upgrade
sudo apt-get install python3-pip
sudo pip3 install instapy
sudo pip3 uninstall instapy-chromedriver
sudo pip3 install instapy-chromedriver==2.36.post0
sudo apt-get install chromium-browser
sudo reboot
```
### Generating quickstart.py ###
Then I created a dir to keep my scripts

```
mkdir scripts
cd scripts
```

Then writed down (or copy & paste quickstart.py from https://github.com/InstaPy/instapy-quickstart/blob/master/quickstart.py), just changed headless_browser to True.

`nano quickstart.py`
(pasted previously modified quickstart and saved)

### Optional ###
If you want to use nogui=True, I recomended you to install xvfb
```
sudo apt-get install xvfb
```
### Runing InstaPy ###
And finally started the script

`pyhton3 quickstart.py -u XXXXX -p XXXXX `

Then script started...
The login was registered by Instagram (received notification by email) and actions worked flawless.

So, I think this is the correct and only way to install InstaPy on  RPi 3B. By now everyone trying to install it, should avoid the "How To Raspberry" instructions and follow this.

**Comment by Venni27** [comment]
I used Python 2.7 before.
To get it back working again, this was needed on my raspi:

pip3 uninstall instapy-chromedriver
pip3 install instapy-chromedriver==2.36.post0
python3 -m pip install meaningcloud-python
python3 -m pip install regex

Then startet instapy with python3 and it works again.

**Comment by hg8** [comment]
Thanks @andifds !
Works for me on my Pi.
But I can not manage to manage to make it work of cronjob 🤔 
Do you have idea why ? Or can you reproduce ?

**crontab -e**
```
SHELL=/bin/bash
PATH=/usr/local/bin/:/usr/bin:/usr/sbin:/home/pi/InstaPy/assets
*/1 * * * * /home/pi/workspace/venv37/bin/python /home/pi/workspace/quickstart.py 
```

Output:

> ERROR [2019-02-22 11:59:04] [yaksoapco]  Message: unknown error: Chrome failed to start: exited abnormally
>   (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)
> instapy.exceptions.InstaPyError: ensure chromedriver is installed at /home/pi/InstaPy/assets/chromedriver

**EDIT:**
Sorry solved it, need to put display:
```
*/1 * * * * export DISPLAY=:0; /home/pi/workspace/venv37/bin/python /home/pi/workspace/quickstart.py 
```

**Comment by thehelvijs** [comment]
@andifds hey, Im trying to do the same on RPi Zero 1.3, but I get this:

```

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/pi/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
INFO [2019-02-22 16:46:07] [myusername]  Using built in instapy-chromedriver executable (version 2.36.post0)
ERROR [2019-02-22 16:46:08] [myusername]  Message: Service /usr/local/lib/python3.5/dist-packages/instapy_chromedriver/chromedriver unexpectedly exited. Status code was: -4
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/instapy/browser.py", line 135, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/lib/python3.5/dist-packages/instapy_chromedriver/chromedriver unexpectedly exited. Status code was: -4

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    headless_browser=True)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 279, in __init__
    self.set_selenium_local_session()
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 333, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /usr/local/lib/python3.5/dist-packages/instapy_chromedriver/chromedriver
```

'chromedriver' is inside /usr/local/lib/python3.5/dist-packages/instapy_chromedriver . And instapy.py has headless_browser=True and nogui=True. Also tried to run with xvfb, same error. 

Also tried putting chromedriver in /home/pi/InstaPy/assets but then I get the same error just instead of /usr/local/lib/python3.5/dist-packages/instapy_chromedriver being /home/pi/InstaPy/assets/chromedriver

**Comment by tE3m** [comment]
The problem is that an RPi 3B+'s structure is ARMv71, but the Pi Zero's is ARMv6, if I'm not wrong. That means that the binary is incompatible. But a user once told me he got it to work on a Pi Zero W like this:
```
If it helps anyone getting it working on Raspberry zero w, here it is:
sudo apt-get install chromium-chromedriver
sudo apt-get install chromium-browser 
cp /usr/lib/chromium-browser/chromedriver InstaPy/assets/ 
cd InstaPy/assets/ 
chmod 755 chromedriver 
chmod +x chromedriver 
(nano instapy/settings.py -> change version from 2.36 to 2.35)

Thanks a lot for everyones kind help 
```

**Comment by thehelvijs** [comment]
@TarekJ03 tried with chromium-chromedriver, but InstaPy warned about it being 2.35 but needed 2.36+, so I ditched it. Will try again with the one you provided, thanks. I will update if it works.

EDIT: IT WORKS! Thank you @andifds and @TarekJ03 !

If anyone wants to use Raspberry Pi **Zero 1.3** or Raspberry Pi **Zero W** (tested on **Zero 1.3** with fresh **Stretch lite**):

```
sudo apt-get update && sudo apt-get -y upgrade
sudo apt-get install -y python3-pip
sudo pip3 install instapy
sudo apt-get install -y chromium-browser
sudo apt-get install -y chromium-chromedriver
sudo pip3 uninstall -y instapy-chromedriver
sudo pip3 install instapy-chromedriver==2.36.post0
sudo cp /usr/lib/chromium-browser/chromedriver /usr/local/lib/python3.5/dist-packages/instapy_chromedriver/chromedriver
sudo apt-get install -y xvfb

(Find line 'chromedriver_min_version' and set it to 2.35):
sudo nano /usr/local/lib/python3.5/dist-packages/instapy/settings.py

(Not necessary, but restart can be made) 
sudo reboot
```

After that you can use your python program. In **InstaPy()** set **headless_browser = True** and **nogui = True** - run the program with **sudo python3** .

**chmod** wasn't necessary for me, but:

```
cd /usr/local/lib/python3.5/dist-packages/instapy_chromedriver/
sudo chmod 755 chromedriver 
sudo chmod +x chromedriver
```

Zero is pretty slow though.

Edit2: Fixed few things, now it works.

**Comment by tE3m** [comment]
Nice! But that's the reason I use a 3b+ :wink:

**Comment by Areahints** [comment]
how can i specify the version of chromium browser?
`sudo apt-get install chromium-browser` installs the 72 version

i am using userland linux app on armv71 phone (rooted)

**Comment by Areahints** [comment]
@TarekJ03 @andifds 


output of `sudo apt-get install chromium-browser`
```
kc@localhost:~$ sudo apt-get install chromium-browser
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  chromium-browser-l10n
Suggested packages:
  webaccounts-chromium-extension
  unity-chromium-extension adobe-flashplugin
The following NEW packages will be installed:
  chromium-browser chromium-browser-l10n
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/51.6 MB of archives.
After this operation, 155 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
dpkg-preconfigure: unable to re-open stdin: No such file or directory
Selecting previously unselected package chromium-browser.
(Reading database ... 40050 files and directories currently installed.)
Preparing to unpack .../chromium-browser_72.0.3626.119-0ubuntu0.18.04.1_armhf.deb ...
Unpacking chromium-browser (72.0.3626.119-0ubuntu0.18.04.1) ...
Selecting previously unselected package chromium-browser-l10n.
Preparing to unpack .../chromium-browser-l10n_72.0.3626.119-0ubuntu0.18.04.1_all.deb ...
Unpacking chromium-browser-l10n (72.0.3626.119-0ubuntu0.18.04.1) ...
Setting up chromium-browser (72.0.3626.119-0ubuntu0.18.04.1) ...
update-alternatives: using /usr/bin/chromium-browser to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/chromium-browser to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
Processing triggers for mime-support (3.60ubuntu1) ...
Setting up chromium-browser-l10n (72.0.3626.119-0ubuntu0.18.04.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...

```


Error i get

```
kc@localhost:~/InstaPy$ python area.py

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/kc/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
INFO [2019-03-09 09:55:32] [areahintsng]  Using built in instapy-chromedriver executable (version 2.36.post0)
ERROR [2019-03-09 09:56:35] [areahintsng]  Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 3.4.0-CAF armv7l)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/instapy/browser.py", line 135, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in init
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in init
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-
 /selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 3.4.0-CAF armv7l)

Traceback (most recent call last):
  File "area.py", line 18, in <module>
    session = InstaPy(username='areahintsng', password='socialmedia123@4', headless_browser=True, nogui=True)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 279, in init
    self.set_selenium_local_session()
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 333, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /usr/local/lib/python3.6/dist-packages/instapy_chromedriver/chromedriver
kc@localhost:~/InstaPy$
```

**Comment by thehelvijs** [comment]
@Areahints 

Try installing chromium chromedriver and replace instapy chromedriver with it:

```
sudo apt-get install -y chromium-chromedriver
sudo cp /usr/lib/chromium-browser/chromedriver /usr/local/lib/python3.6/dist-packages/instapy_chromedriver/chromedriver
```

**Comment by Areahints** [comment]
@ewlbo 

```
unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=72.0.3626.121,platform=Linux 3.4.0-CAF armv7l)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/instapy/browser.py", line 135, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=72.0.3626.121,platform=Linux 3.4.0-CAF armv7l)

Traceback (most recent call last):
  File "area.py", line 18, in <module>
    session = InstaPy(username='-------', password='------', headless_browser=True, nogui=True)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 279, in __init__
    self.set_selenium_local_session()
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 333, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /usr/local/lib/python3.6/dist-packages/instapy_chromedriver/chromedriver
```

**Comment by Areahints** [comment]
letting this go as the issue im having stems from the phone architecture {32 bit}. will just use on my pc.

**Comment by anitato** [comment]
@andifds 's directions work for me to get a clean install. (@timgrossmann, can we update the READ.me?)

However, I continue to encounter this dynamical error when running any script on my Raspberry Pi 3B+  #4192
