### ISSUE TITLE
Feature Request - Interact with likers (Without Follow)

### ISSUE THREAD

**Issue by s-h-a-d-o-w-pixel** [InstaPy/InstaPy#4039]
Hi,
I use the follow_likers and I was wondering why we don't have a like_likers or something.
I'm trying to give back likes to my own likers and that feature would be such a time saver.

**Comment by ThatDudeIsReal** [comment]
I was about to post a Feature Request as well. it would make so much sense to interact with active users that like posts no matter if users like your post or users that liked a post from other accounts. these users

**Comment by ThatDudeIsReal** [comment]
@timgrossmann is it possible to use "session.follow_likers" without following somehow similar to "session.set_do_follow(enabled=False)"

**Comment by DmytroDiachuk** [comment]
Good idea
