### ISSUE TITLE
Developer feature: Github Code Owners

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#404]
Hi,

not a bug/issue, but it might be interesting for the main developers that github supports [code owners](https://github.com/blog/2392-introducing-code-owners) since last week.

This way, all owners can review new pull requests:

> With that in place, code owners will automatically be requested for review whenever a pull request touches the files they own.

**Comment by timgrossmann** [comment]
@tibor Yes I saw that a few hours ago.
Could you work on that?

Thank you

**Comment by converge** [comment]
there is no interaction for a long time, pls, reopen if you need.
