### ISSUE TITLE
Unfollow peak quotient does not update in a single session

### ISSUE THREAD

**Issue by huy41** [InstaPy/InstaPy#4041]
If I unfollow in a single session the quotient doesn't update even though more than 1 hour have passed. That means every unfollow action gets skipped. 

However if I split it in multiple sessions then it works for some reason.

**Comment by badmobile** [comment]
```
~~~~
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danielbeltejar** [comment]
Still not fixed

**Comment by danielbeltejar** [comment]
@timgrossmann

**Comment by danielbeltejar** [comment]
Example
`		# Supervisor de acciones maximas por hora y dia. Y dormir siesta si se llega al maximo de follows por hora.
		session.set_quota_supervisor(enabled=True,
								 	 sleep_after=["server_calls_h", "server_calls", "follows_h"],
								 	 sleepyhead=False,
								 	 stochastic_flow=False,
								 	 notify_me=True,
								 	 peak_comments=(10, 120),
								 	 peak_likes=(35, 300),
								 	 peak_follows=(20, 300),
								 	 peak_unfollows=(20, 300),
								 	 peak_server_calls=(800, 16000))
						
		
		#Loop de hacer follow y unfollow
		while True:
			# Entrar aun POD
			session.join_pods()
			session.join_pods('food')
			# Aceptar solicitudes de seguimiento.
			session.accept_follow_requests(amount=random.randint(150, 200), sleep_delay=2)
		
			# Hacer unfollow a todo el mundo en modo FIFO
			session.unfollow_users(amount=random.randint(150, 200), InstapyFollowed=(True, "all"), style="RANDOM", unfollow_after=2*24*60*60, sleep_delay=600)
			
			# Cargar un usuario random de gente para obtener sus seguidores.
			random_target = random.choice(targets)
			
			# Seguir follows de la gente de la lista con el metodo random.
			session.follow_user_followers(random_target, amount=random.randint(150, 200),
										  randomize=True, sleep_delay=600,interact=True)`
