### ISSUE TITLE
Issue with x-path login button //button[text()='Log in'

### ISSUE THREAD

**Issue by couturelp** [InstaPy/InstaPy#4044]
New issue appeared this morning, it seems IG is doing some A-B testing on the login button.

Here is the fix : 

In file : File: login_util.py
Change
`login_button = browser.find_element_by_xpath( "//button[text()='Log in']")`

to
`login_button = browser.find_element_by_xpath( "//*[contains(text(), 'Log in')]")`

**Comment by zmcdbiz** [comment]
did this work for you? i am having the same issue and for some reason this did not help

**Comment by couturelp** [comment]
Yes, this works for me. Make sure you are modifying the right file that is being used.

**Comment by timgrossmann** [comment]
@couturelp @zmcdbiz Have you guys tried updating InstaPy?
We already changed and released that.

`pip install -U instapy`
