### ISSUE TITLE
Instapy-chromedriver

### ISSUE THREAD

**Issue by dlenskyi** [InstaPy/InstaPy#4048]
## Expected Behavior
Log in as usual
## Current Behavior
It can't log in my account, I have installed the newest version of instapy and requirements.
Log:
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[text()='Log in']"}   (Session info: headless chrome=72.0.3626.109)   (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.15.0-45-generic x86_64)
I tried chromedrivers 2.44-2.46, by the way, when I use 2.46, instapy assumes that it's 2.44.
google chrome is v72

**Comment by timgrossmann** [comment]
@dlenskyi It's not the chromedriver: {"method":"xpath","selector":"//button[text()='Log in']"}

We released a new version with the updates earlier today
`pip install -U instapy`
