### ISSUE TITLE
If anybody has got 'wrong login data', check this.Xpath is changed .

### ISSUE THREAD

**Issue by SeoMinbong** [InstaPy/InstaPy#4050]
## Possible Solution (optional)
Xpath is changed .
How about this?

    # Check if user is logged-in (If there's two 'nav' elements)
    nav = browser.find_elements_by_xpath('//nav')
    if len(nav) == 2:
        # create cookie for username
        pickle.dump(browser.get_cookies(), open(
            '{0}{1}_cookie.pkl'.format(logfolder, username), 'wb'))
        return True
to 

    web_address_navigator(browser, "https://www.instagram.com/"+username)
    # Check if user is logged-in (If there is profile button<span>)
    span_chk = browser.find_elements_by_xpath("//span[@aria-label='Profile']")
    if len(span_chk) > 0:
        # create cookie for username
        pickle.dump(browser.get_cookies(), open(
            '{0}{1}_cookie.pkl'.format(logfolder, username), 'wb'))
        return True

**Comment by AlexanderProd** [comment]
Hi @SeoMinbong 

I've encountered a problem where Instapy suddenly refused to login with my correct password. 
Did you try this fix and is it working for you?

**Comment by nazariyv** [comment]
why was this closed? I am experiencing this problem
