### ISSUE TITLE
Telegram API for notifications / Bot config and call in template

### ISSUE THREAD

**Issue by rudyvanbebu** [InstaPy/InstaPy#4053]
## Expected Behavior
Hi Tim and team,

I'm using one of the quickstart templates which intends to send a Telegram notification once actions start and end. 

The call appears in the template as 

requests.get(
        "https://api.telegram.org/******&text='InstaPy Follower Started @ {}'"
            .format(datetime.now().strftime("%H:%M:%S")))

I had already created a Telegram Bot and setup accordingly to the following guide 

https://github.com/Tkd-Alex/Telegram-InstaPy-Scheduling/blob/master/README.md

What would I need to change/populate in the request listed in the template for it to work.

requests.get(
        "https://api.telegram.org/******&text='InstaPy Follower Started @ {}'"
            .format(datetime.now().strftime("%H:%M:%S")))

Apologies for the rooki question, quite new to Python and Instapy hence the doubts.

Thanks

**Comment by rudyvanbebu** [comment]
You can close this ticket, I made it work altering the URL. Thanks

**Comment by atos93** [comment]
> You can close this ticket, I made it work altering the URL. Thanks

how?

**Comment by rudyvanbebu** [comment]
You can follow the URL structure below, naturally replacing BOT TOKEN and CHAT ID For your own values 

https://api.telegram.org/bot<TOKEN>/sendMessage?chat_id=<CHAT_ID>&text=<MESSAGE>
