### ISSUE TITLE
Asking for advice on how I can help learn to contribute to this project!

### ISSUE THREAD

**Issue by RealMakAttak** [InstaPy/InstaPy#406]
Hello All,

This is fantastic, I am captivated.

I will not lie I am not the best Python programmer but I want to use this project as my chance to learn.

What do I need to learn to pick this apart?

Selenium? Any books people can recommend? Not on Python programming but on what I need to understand this amazing project.

What I am trying to do is make it so that the program will only like/comment a list of users I give it - I can't see anywhere this is available.

Thanks!!

**Comment by timgrossmann** [comment]
@RealMakAttak Thank you!

There is a `.follow_by_list` feature, but this will only follow the people given in the list.
It would be awesome if you could develop that feature!

Maybe you could start with some simple automation with python and selenium. 
It's not too hard to pick up. 
I gave a talk about "Automating Instagram with Python and Selenium", you can take a look at it and check out the slides for it.
[Talk](https://youtu.be/-OTwbnxrCSI?t=6h57m56s) 
[Slides](http://slides.com/timgrossmann/deck-1#/)

**Comment by kushpvo** [comment]
Hello!

Just like you, even i'm amazed to have this script.

I'd like to contribute as well. The feature that I want on this script is to interact with followers of competitors. So, if i put in few usernames of my competitors accounts, the bot should like/comment/follow the followers of those accounts. 

I'm a beginner python programmer so I don't think I'd be able to do that at this stage, but i'll try. 👍

**Comment by timgrossmann** [comment]
@kushpvo Go for it!
Trying out is the best way to learn. You can simply work on the feature on your local copy and once it's working you can still contribute it 😉

**Comment by Pormientras** [comment]
Hey Tim this is my first post and first let me tell you a big Thank you!

Now, im interested in what kushpvo is asking for, which would be great for people trying to promote certain business. I just started learning python and I dont think im ready to jump for something like this but I found this Instagram API that gives you a full list of the followers of any account you enter https://www.magimetrics.com/ (You can register for free to try it out). And what is even better is that Magimetrics can get much more that just the name of the followers, it can also take a lot of their stats. Maybe if there was a way to get that same list directly from instagram we could do a script that goes to those accounts, likes 3 or 2 pictures and then follows them. This would be incredible usefull.

So what can I do to help with this project? as I said I just started learning python so this is a big step for me. Can some one guide me into what exactly I have to learn to archive this?

Thank you again Tim!

**Comment by RealMakAttak** [comment]
@timgrossmann Thank you very much Tim, I will do my best!
