### ISSUE TITLE
quickstart template in docker

### ISSUE THREAD

**Issue by SteveWSol** [InstaPy/InstaPy#4060]
Hi guys,

I'd like to execute the "target_followers_of_similar_accounts_and_influencers.py" quickstart example so I dragged in into my InstaPy root folder and executed it. I'm trying to run it on my Synology Nas using the docker application, but I keep getting this error:

> root@IG-Bot01:/InstaBot01/InstaPy# python target_followers_of_similar_accounts_and_influencers.
> py                                                                                             
>                                                                                                
>  ._.  ._.  ._.  ._.  ._.  ._.  ._.                                                             
> Workspace in use: "/root/InstaPy"                                                              
>                                                                                                
>  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
>  ._.  ._.                                                                                      
> INFO [2019-02-23 18:14:20] [Name]  Using built in instapy-chromedriver executable (versio
> n 2.46)                                                                                        
> ERROR [2019-02-23 18:14:21] [Name]  Message: Service /usr/local/lib/python3.7/site-packag
> es/instapy_chromedriver/chromedriver_linux64 unexpectedly exited. Status code was: 127         
> Traceback (most recent call last):                                                             
>   File "/InstaBot01/InstaPy/instapy/browser.py", line 135, in set_selenium_local_session       
>     chrome_options=chrome_options)                                                             
>   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73
> , in __init__                                                                                  
>     self.service.start()                                                                       
>   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 98, 
> in start                                                                                       
>     self.assert_process_still_running()                                                        
>   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 111,
>  in assert_process_still_running                                                               
>     % (self.path, return_code)                                                                 
> selenium.common.exceptions.WebDriverException: Message: Service /usr/local/lib/python3.7/site-p
> ackages/instapy_chromedriver/chromedriver_linux64 unexpectedly exited. Status code was: 127    
>                                                                                                
> Traceback (most recent call last):                                                             
>   File "target_followers_of_similar_accounts_and_influencers.py", line 52, in <module>         
>     multi_logs=True)                                                                           
>   File "/InstaBot01/InstaPy/instapy/instapy.py", line 279, in __init__                         
>     self.set_selenium_local_session()                                                          
>   File "/InstaBot01/InstaPy/instapy/instapy.py", line 333, in set_selenium_local_session       
>     raise InstaPyError(err_msg)                                                                
> instapy.exceptions.InstaPyError: ensure chromedriver is installed at /usr/local/lib/python3.7/s
> ite-packages/instapy_chromedriver/chromedriver_linux64    

   

I have no idea what to do. I'm quite new to this.

**Comment by JoooostB** [comment]
I'm experiencing the same issue and #4046 doesn't seem to fix the issue... Any ideas @timgrossmann ?

**Comment by kckai** [comment]
Also having this issue, previous updates did not fix it. Are we missing something? @timgrossmann Thank you!

**Comment by kckai** [comment]
Issue only occurs when I am using a **proxy** with Chrome. If I am not using a proxy it works out perfectly

**Comment by pmusolino** [comment]
Same issue here after updating to the last version

**Comment by pmusolino** [comment]
I would like to say that closing the issue does not help solve problems, rather it duplicates them, creating confusion.

**Comment by kckai** [comment]
The issue was closed due to inactivity by the stale bot. 

I managed to get it running after a while. Try to reinstall Chromedriver and make sure its in the right directory. 
Helpful: https://tecadmin.net/setup-selenium-chromedriver-on-ubuntu/

`instapy.exceptions.InstaPyError: ensure chromedriver is installed at /usr/local/lib/python3.7/s
ite-packages/instapy_chromedriver/chromedriver_linux64`

Hope this helps!
