### ISSUE TITLE
python 3.7 & pip 19.0.3 update on Raspberry Pi - Unable to run InstaPy

### ISSUE THREAD

**Issue by alexsmedile** [InstaPy/InstaPy#4061]
I'm trying to install InstaPy following the [Raspberry Pi installation process](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md#install-instapy):

1. `sudo apt-get update && sudo apt-get upgrade`
2. `mkdir Projects`
3. `cd Projects`
4. `python3 -m venv /home/pi/Projects/venv37`
5. `source venv37/bin/activate`
6. `git clone https://github.com/timgrossmann/InstaPy.git`
7. `cd InstaPy`
8. `python3 -m pip install --user .`

I've already successfully installed python3 following [the guide](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md#python-37-install-guide) on your doc. And I also set `alias python3='/usr/bin/python3.7'` as the guide suggests.

Now, let's get to the last step of your guide: `python3 -m pip install --user .`
This is what I get:
`You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

So, of course, I updated 'pip', but I'm still getting the message above. I think even though python is v3.7, pip is still running on 3.5. In fact, if I run `pip3 install --upgrade pip` I get this:
`Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple Requirement already up-to-date: pip in ./.local/lib/ **python3.5** /site-packages (19.0.3)`

I searched a few ways to fix this error and [what I found](https://stackoverflow.com/questions/39691860/pip-command-by-default-using-python-3-how-to-change-it-to-python-2) is that maybe by creating a link between pip and pip3 I'm able to run just the latest version, so I typed: `sudo ln -s /usr/local/bin/pip3 /usr/local/bin/pip` but with no success. `ln: failed to create symbolic link '/usr/local/bin/pip': File exists`

How can I fix this? I just need to properly run InstaPy on RaspianOS, with Python3.7 and the last version of pip module.

Thanks in advance.

**Comment by hg8** [comment]
Did you try to run Instapy? Because 

> You are using pip version 10.0.1, however version 19.0.3 is available. You should consider upgrading via the 'pip install --upgrade pip' command.

is just a warning and not an error message. I am pretty sure `python3 -m pip install --user .` command worked perfectly.

**Comment by alexsmedile** [comment]
Thanks for your anwser @hg8 . InstaPy is installed, you are right. But now I have problems with modules. If I run my script `python3 z_schedule.py` I get:
```
Traceback (most recent call last):
  File "z_schedule.py", line 2, in <module>
    from z_config import *
  File "/home/pi/Projects/InstaPy/z_config.py", line 7, in <module>
    import os, csv, json, time, requests, re, gspread, gspread_formatting
ModuleNotFoundError: No module named 'gspread'
```

**Comment by hg8** [comment]
Try:

    pip3.7 install gspread

**Comment by alexsmedile** [comment]
When I tried it a few hours ago it gave me something like: there is no compatible version. Now (I don't really know why), the terminal gave me this other response:
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting gspread
  Using cached https://files.pythonhosted.org/packages/43/f8/45bd4a1419fd65ecc02eeaceb92f9dc72aca20c32e766a18d495c68006db/gspread-3.1.0-py3-none-any.whl
Requirement already satisfied: requests>=2.2.1 in ./.local/lib/python3.7/site-packages (from gspread) (2.21.0)
Requirement already satisfied: idna<2.9,>=2.5 in ./.local/lib/python3.7/site-packages (from requests>=2.2.1->gspread) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.local/lib/python3.7/site-packages (from requests>=2.2.1->gspread) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./.local/lib/python3.7/site-packages (from requests>=2.2.1->gspread) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.7/site-packages (from requests>=2.2.1->gspread) (2018.11.29)
Installing collected packages: gspread
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/opt/python-3.7.0/lib/python3.7/site-packages/gspread'
Consider using the `--user` option or check the permissions.
```

I thought a little about it, and then I came up with this:
`sudo pip3.7 install gspread`.

It worked! I mean, I don't have any import module error if I use `sudo pip3.7`. But... I have to do it with every single imported module of my code.

**Comment by alexsmedile** [comment]
And, now I'm facing another issue :(
```
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-02-24 17:11:15] [alexsmedile]  Using built in instapy-chromedriver executable (version 2.44)
Traceback (most recent call last):
  File "z_schedule.py", line 4, in <module>
    from z_instabot import *
  File "/home/pi/Projects/InstaPy/z_instabot.py", line 15, in <module>
    page_delay=.5)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 279, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 331, in set_selenium_local_session
    self.logger)
  File "/home/pi/Projects/InstaPy/instapy/browser.py", line 135, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/local/opt/python-3.7.0/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/local/opt/python-3.7.0/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/.local/lib/python3.7/site-packages/instapy_chromedriver/chromedriver_linux64'
```

I've also installed chromedriver into the assets folder as specified in the guide. But there's a problem with that.

**Comment by andifds** [comment]
I recommend you to start on a fresh install and follow this instructions. I got my head broken for many days but finally make it work on my RPi 3B+

Here's the link to updated instructions
[Definetly not working on Raspberry Pi (3B+) - *Updated Instructions*](https://github.com/timgrossmann/InstaPy/issues/4033#issuecomment-466280659)

**Comment by ljacobo** [comment]
Hi,

you only need this:

pip3 install instapy
pip3 uninstall instapy-chromedriver
pip3 install instapy-chromedriver==2.36.post0

and when you run your quickstart.py file, do it with python3.5.
