### ISSUE TITLE
no module named instapy

### ISSUE THREAD

**Issue by noviss121** [InstaPy/InstaPy#4062]
![1](https://user-images.githubusercontent.com/47945951/53300950-7e64da80-3862-11e9-91f1-8ffd9de1c817.jpg)
this is my problem and idk how can fix it!!!!!!!!!!
help my thnx

**Comment by timgrossmann** [comment]
@noviss121 Please make sure to ask the right things. The problem that instapy is not properly installed (as seen in the error message) and not that the start script is not working 😊 
Make sure to install InstaPy using either
`pip install instapy`
or
`pip3 install instapy`

**Comment by noviss121** [comment]
I installed pip3 but it's still the same error, I'm not sure that the pip is installed.
but when i see this message from installation folder
![untitled](https://user-images.githubusercontent.com/47945951/53333514-58dfdb80-390b-11e9-80f9-46b226d84012.png)

i think instapy installed
