### ISSUE TITLE
Need Help for quota supervisor

### ISSUE THREAD

**Issue by tourhuntr** [InstaPy/InstaPy#4063]
Run this script since a week and i runs. Instapy also sleep when quota supervisor sad it.
But... it starts at midight... maan, this shouldn'd be like this. It should start about 7 - 9 am when normal people also start.
How do i manage this?

![grafik](https://user-images.githubusercontent.com/46623690/53302435-3f348a80-385e-11e9-9494-6bb60dea2c2a.png)

**Comment by tE3m** [comment]
I use an `if` and `elif` statement that gets the local time and only then executes the InstaPy script. Else it sleeps for 30s.

**Comment by tourhuntr** [comment]
Can you show me some code?

**Comment by HCWcoder** [comment]
[https://crontab.guru](https://crontab.guru)

Use Cron to schedule your job if you are on linux
or use windows scheduler

**Comment by tourhuntr** [comment]
Did you read my code? i have an infinite loop with quota. Quota sleeps after the likes. If i use cron, i have multiple sessions. I only want one session.

**Comment by tourhuntr** [comment]
no one?

**Comment by yaca8** [comment]
same problem here :/

**Comment by tourhuntr** [comment]
> 
> 
> I use an `if` and `elif` statement that gets the local time and only then executes the InstaPy script. Else it sleeps for 30s.

@TarekJ03 Can you help me with the code like you did with the while True?

**Comment by dontic** [comment]
Modified this by changing the code in line 207 of quota_supervisor.py:

Original:
`midnight = datetime.combine(tomorrow, time())`

If today is 28/04/2019 at 09:20 this code makes the variable "midnight" 29/04/2019 at 00:00:00

You can change this by inserting the desired time in time() with the format:
`time(hour, minutes, seconds)`

i.e.: I want InstaPy to sleep until 15:27 when daily limit is reached:
`midnight = datetime.combine(tomorrow, time(15, 27))`
