### ISSUE TITLE
Use the InstaPy code instead of the installed by pip - Development purposes

### ISSUE THREAD

**Issue by joanroig** [InstaPy/InstaPy#4065]
## Current Behavior
I've cloned InstaPy and installed its dependencies, after that I've runned the quickstart.py file and I've noticed it compiled and runned the code from the /instapy folder.
If I run code from another folder, like /instapy/custom/quickstart.py the code is runned from the pip dependency, so I cannot test my changes on the instapy core.
## Expected Behavior
There should be an easy way to point the InstaPy core for making changes on it.
## Possible Solution (optional)
I've tried setting the workspace folder but it seems that only points the logs folder, the core runs from the pip dependency.
## InstaPy configuration
Regular clone with basic configurations.

**Comment by timgrossmann** [comment]
@joanroig Awesome to hear you're planning to do some development on InstaPy 🙌 

I think what you are searching for is this:
```
pip install --help
...
  -e, --editable <path/url>   Install a project in editable mode (i.e. setuptools
                              "develop mode") from a local project path or a VCS url.
```

You might need to either deinstall instapy using `pip uninstall instapy` or use the `-I` flag to ignore the installed version when doing this to avoid `already satisfied`

Let me know if that helps 😊

**Comment by breuerfelix** [comment]
ahahah nooo this is waaaay easier ! and @uluQulu already wrote that in the readme :)

clone the repo and cd into the repo.  
execute `pip3 install -e .`
it will install the current folder as a package but it will refer to this package everytime you use it anywhere on your computer :)

so you can make local changes, start the quickstart anywhere on your systems, and it will use your local changes. you do not have to update something, its always 'live'.

/edit actualy readme entry http://prntscr.com/mppuf4

**Comment by joanroig** [comment]
Thanks! I've skipped the -e part in the docu
