### ISSUE TITLE
Login issue "//button//div[text()='Log in']

### ISSUE THREAD

**Issue by YannikFirre** [InstaPy/InstaPy#4067]
Hello,

i have this issue now : 
`selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button//div[text()='Log in']"}`

Thanks

**Comment by ndelphit** [comment]
I have the same problem

**Comment by hg8** [comment]
Pull Request for a fix is coming : https://github.com/timgrossmann/InstaPy/pull/4066

**Comment by joanroig** [comment]
I'll retest it now to see if I can catch it again
Edit: jup it's working, wait for the merge

**Comment by bylezz** [comment]
Hello,

Can you explain a little more in detail how you fixed it?. i put this:

    try:
        login_elem = browser.find_element_by_xpath(
            "//article//a[text()='Log in']")
    except:
    except NoSuchElementException:
        print("Login A/B test detected! Trying another string...")
        login_elem = browser.find_element_by_xpath(
            "//article//a[text()='Log In']")

 Error:

  File "C:\Users\guill\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 28, in <module>
    login_elem = browser.find_element_by_xpath(
NameError: name 'browser' is not defined

Thank you.
:)

**Comment by joanroig** [comment]
@bylezz you don't need to change anything inside quickstart, it's about the core code of Instapy. You need to change the code inside instapy/login_util.py, or wait for pulling changes when the merge is done.

**Comment by mgconejero** [comment]
the change worked for me 👍
