### ISSUE TITLE
cronjob to reboot server every 24 hours inside detached screen session ?

### ISSUE THREAD

**Issue by potentowl** [InstaPy/InstaPy#4068]
Hello, i use a detached screen session with instapy but how would i go about setting up a crontab to reboot the server every 24 hours and start instapy in a detached screen session, sort of a fail-safe incase i get errors and can't access internet...

**Comment by HCWcoder** [comment]
@loopypanda 

this might help you [https://crontab.guru](https://crontab.guru)

**Comment by potentowl** [comment]
@HCWcoder thanks, im pretty familiar with crontab the issue is starting the detached screen session inside of the crontab without having environment issues.

**Comment by ishandutta2007** [comment]
What do you mean by detached screen session?
Crons don't need any screen or even active terminal to be triggered.
I use this [script](https://github.com/InstaPy/instapy-scripts/blob/master/run_instapy_only_once_for_mac.sh) to restart the job for the next run, check if it helps.

**Comment by Tr1pke** [comment]
you want to reboot your server every day? ...
Just make a crontab that you insteps kills all screen and restart the bot every time 

I have it like this:

cat instagram.sh:

```
killall screen
sleep 1
screen -dmS IG sh -c 'python3 InstaPy/IG-follow-unfollow.py; exec bash'
screen -dmS IG sh -c 'python3 InstaPy/IG-follow-unfollow.py; exec bash'
sleep 1
screen -ls
```

crontab -e:
`0 */8 * * * /home/myusername/instagram.sh`

Every 8 hours it kills all my screens (so it kills the bot) and it restarts the bot again.
Works like a charm for many months now.

**Comment by potentowl** [comment]
@Tr1pke 

YES THIS MIGHT WORK I WAS USING A SEPERATE SCRIPT, I WILL POST WHEN I HAVE MORE TIME. 

BASICALLY JUST A FAIL-SAFE SO THE AUTOMATION NEVER STOPS :)

**Comment by Tr1pke** [comment]
The solution i proposed works 24/7
the only time it stops is when instagram changes their feed, but then everyones his bot stops ;-)
Try it and see it will be a succes :-)

**Comment by potentowl** [comment]
@tr1pke 

I suppose the next step would be to: automate: updating the instapy git pull, every 72 hours and updating the quickstart.py code. More fail-safes to make automation easier. ;)

**Comment by Tr1pke** [comment]
> @Tr1pke
> 
> I suppose the next step would be to: automate: updating the instapy git pull, every 72 hours and updating the quickstart.py code. More fail-safes to make automation easier. ;)

What if the pull is bad? it's offline for 72hrs at least and why don't you use pip to update?
Sometimes you just have to check it manually just to be sure :-P

**Comment by Tr1pke** [comment]
@loopypanda 

What if the pull is bad? it's offline for 72hrs at least and why don't you use pip to update?
Sometimes you just have to check it manually just to be sure :-P

**Comment by potentowl** [comment]
@tr1pke

Hey, im just throwing out ideas, IG wasted a lot of my time, anything to piss them off haha

**Comment by thomaslc66** [comment]
The problem is with selenium.
When you have some other process that are still running, you get this error.

you have to run : 
(sudo) pkill chromium -> this will kill all process with chromium in the name

Before you actually start you script. This will kill all remaining browser.
