### ISSUE TITLE
Is it possible to set window size?

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4071]
## Expected Behavior
is it possible to set an argument on headed mode to run at a certain resolution?

for example set window 640x640? I prefer to run in windowed mode but prefer to have it set window size for me.

**Comment by sionking** [comment]
yes

**Comment by ghost** [comment]
how? lol @sionking

**Comment by sionking** [comment]
def change_size(self):

        window_size = self.browser.get_window_size()
        randx = random.randint(80, 150)
        randy = random.randint(-70, 20)
        self.browser.set_window_size(window_size['width'] + randx, window_size['height'] + randy)

        return self
