### ISSUE TITLE
How can we get the latest instagram post link for a particular user with instapy?

### ISSUE THREAD

**Issue by alpaybi** [InstaPy/InstaPy#4075]
How can we get the latest instagram post link for a particular user with instapy?
I'll be happy if you can help me.

**Comment by SeoMinbong** [comment]
It can be if you can create a python file and get Xpath from instagram on chrome.

**Comment by alpaybi** [comment]
Thank you SeoMinbong. I'm really inexperienced about Python. Is there an example?
