### ISSUE TITLE
Doubt. Use instagram at the same time instapy is running

### ISSUE THREAD

**Issue by bylezz** [InstaPy/InstaPy#4076]
Hello,

I have now running instapy for my account. I have doubts about when I can use my instagram.

Can I use instagram at the same time as instapy?

There is a daily limit of likes, follow, unfollow and coments, can I stop instapy and give likes comment etc without anything bad happening? I'm in groups of instagram pods and I have to give likes etc, I do not want to have problems the day I publish in instagram. Any comments and help on this?

Do you recommend using a VPN to do it from the site that Instapy is working?

I have set the following limits 600 likes, 640 follow and 700 unfollow per day. The account is more than one year old. Is it reasonable?

Thank you so much for your help and time.

**Comment by Tr1pke** [comment]
ofc you can, just don't get crazy by follow/unfollow too much. keep it normal, do some other stuff, biking running swimming

**Comment by bylezz** [comment]
Ok thx
