### ISSUE TITLE
Where I can delete my cokies file

### ISSUE THREAD

**Issue by x225am** [InstaPy/InstaPy#4077]
Hi Sorry maybe for stupid question but I am ruining InstaPy on ubuntu. Now I have cookies error. I use to delete it before in log folder. Now it nothing there. Any ideas where to find it now?

**Comment by Tr1pke** [comment]
you@server:~/InstaPy/logs/IG/IGMyNextCompany_cookie.pkl
have you ever searched for it in the terminal? locate/find etc
it has cookie in the name ;-)

**Comment by x225am** [comment]
Thanks! problem solved Yes I did search. Issue was I use to run under super user. (sudo -i). All logs went under root directory.

**Comment by Tr1pke** [comment]
Very unsafe
