### ISSUE TITLE
Can I check if the accounts I follow are following me back?

### ISSUE THREAD

**Issue by xerZV** [InstaPy/InstaPy#4079]
Can I check if the accounts I follow are following me back?

**Comment by SeoMinbong** [comment]
@xerZV 
I think it can be if you can read a file that type of ".json"
Check your 
 \logs\relationship_data\username\nonfollowers

**Comment by SeoMinbong** [comment]
To open a file type of "json", you can use any editor or notepad(in case Windows OS).
I don't know any other OS.

**Comment by SeoMinbong** [comment]
Then you can check who doesn't follow you .
More tip,
\logs\relationship_data\username\following
You can check all you are following.

**Comment by xerZV** [comment]
Hi, @SeoMinbong ,
in C:\Users\user\InstaPy\ there is only "logs" folder.
In C:\Users\user\InstaPy\logs\ there is only one folder with my instagram account name. In that folder 
C:\Users\user\InstaPy\logs\instaUsername\ there is no file with name "nonfollowers" (look at the attachment file)
![da](https://user-images.githubusercontent.com/23699044/53550159-b60fa300-3b3e-11e9-9f2d-3fc2ecd5ed18.png)
.
Also I want to check all the following list, not only these which InstaPy followed

**Comment by sionking** [comment]
Check my follow backers PR.

**Comment by xerZV** [comment]
anyone?
