### ISSUE TITLE
Simulated Follow

### ISSUE THREAD

**Issue by tourhuntr** [InstaPy/InstaPy#4080]
I use a script to like 4 of the last posts of the followers of a specific account. While i used simulated follow, the follow counter goes higher and higher and i dont think instapy unfollows in the amount that follows.
How long does instapy follow the accounts and then does it unfollow?

**Comment by Herrox** [comment]
You have to use `unfollow_users` function to unfollow user previously followed by InstaPy.
Here is the link of the doc for this function https://github.com/timgrossmann/InstaPy#unfollowing

**Comment by tourhuntr** [comment]
i dont use any function to follow the users apart from the simulation from instapy itselfs.
So i dont understand why i should use the "unfollow_users" function

**Comment by timgrossmann** [comment]
@tourhuntr Simulation doesn't unfollow.people at the moment, sorry.

You gotta use unfollow if you want to do that.
You can set it to instapy followed only (check the readme for that 👍 )
