### ISSUE TITLE
Is it possible to follow and comment WITHOUT LIKING?

### ISSUE THREAD

**Issue by brocool** [InstaPy/InstaPy#4087]
Please, Is it possible to follow and comment WITHOUT LIKING? The reason im asking this because I get most of my followers from follow for follow and comments. And now instagram is not letting me like and it's annoying. Thats why I wanna disable liking but keep following and commenting. I'm sure it's possible but I don't know how to do it. Any help is appreciated. Thank you

**Comment by brocool** [comment]
.

**Comment by CharlesCCC** [comment]
well, you can definitely change the code to do that. but that was not the root cause of your problem, the root cause is you will need minimize the actions(like/comment/follow/unfollow) to certain limit, otherwise you risk your account been banned temporally or forever.

**Comment by jeremycjang** [comment]
What Charles said. There's a predefined threshold for every action type you can perform in a certain time frame and you need to make sure not to trip it
