### ISSUE TITLE
docker not working

### ISSUE THREAD

**Issue by c0d3x27** [InstaPy/InstaPy#4088]
## Expected Behavior
to work
## Current Behavior
Step 1/4 : FROM python:3.7-slim-stretch
 ---> bc5085cee55b
Step 2/4 : COPY ./requirements.txt /tmp
 ---> Using cache
 ---> 73a38b34911c
Step 3/4 : RUN apt-get update     && apt-get install -y --no-install-recommends --no-install-suggests       wget       gcc       g++     && pip install --no-cache-dir -r /tmp/requirements.txt     && apt-get purge -y --auto-remove       gcc       g++     && apt-get clean     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> a1e6a12b267f
Step 4/4 : CMD ["./code/wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "code/docker_quickstart.py"]
 ---> Using cache
 ---> f7554cc481fe
Successfully built f7554cc481fe
Successfully tagged instapy_web:latest
Starting selenium ... error

ERROR: for selenium  Cannot start service selenium: driver failed programming external connectivity on endpoint selenium (082d62d14aaa8ae28fce8f31da62ebb2ba8): Error starting userland proxy: Bind for 0.0.0.0:5900 failed: port is already allocated

ERROR: for selenium  Cannot start service selenium: driver failed programming external connectivity on endpoint selenium (082d62d14aaa831da62ebb2ba8): Error starting userland proxy: Bind for 0.0.0.0:5900 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
## Possible Solution (optional)
dont know
## InstaPy configuration
none yet

i dont have nothing running on that port this mac is clean but for some reason is telling the the port is being used for something also. how can i solve this please

**Comment by Herrox** [comment]
It looks like you already have something listening to port 5900. Could you please run this command and post the output ?
`netstat -tanp | grep 5900`

I think the selenium container is not starting because of that

**Comment by timgrossmann** [comment]
@Banginpadr Sorry, not working at the moment...
@funkypenguin Is fixing it. It'll be done in the coming days 👍
