### ISSUE TITLE
I can't make URLs work

### ISSUE THREAD

**Issue by FrancocDev** [InstaPy/InstaPy#4089]
## Expected Behavior
Make on one single photo multiple comments with one account.
## Current Behavior
Never login and can't start doing the process even if I login manually.
## Possible Solution (optional)
I see that changing "self.switch_language" to False (in instapy.py) will fix the login error, but I can't still login.

Note: I install all with instapy-quickstart in windows.

## InstaPy configuration
`
""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'account'
insta_password = 'password'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

#configs
session.set_do_like(enabled=False, percentage=0)
session.set_do_comment(enabled=True, percentage=99)
session.set_comments(["comment1", "comment2", "comment 3"])
session.set_do_follow(enabled=False, percentage=0)
session.set_user_interact(amount=3, randomize=False, percentage=0, media='Photo')

#activity
session.interact_by_URL(urls=["XxXXXxXXxXXX"], randomize=False, interact=True)
`

**Comment by tE3m** [comment]
Please provide the error output.

**Comment by FrancocDev** [comment]
@TarekJ03 How i can get that?

**Comment by FrancocDev** [comment]
@TarekJ03 on debug.log i get that:

[0301/145405.659:ERROR:process_reader_win.cc(123)] NtOpenThread: {Acceso denegado} Un proceso ha solicitado acceso a un objeto, pero no se le han concedido esos derechos de acceso. (0xc0000022)
[0301/145405.659:ERROR:exception_snapshot_win.cc(88)] thread ID 10032 not found in process
