### ISSUE TITLE
Can't unfollow anyone

### ISSUE THREAD

**Issue by s-h-a-d-o-w-pixel** [InstaPy/InstaPy#4092]
Can't unfollow users, every single user gives me the same error and deletes it from the followed pool.

## Expected Behavior
Unfollow users followed by instapy.

## Current Behavior
INFO [2019-03-02 14:08:52] [anotherguytravelling]  Ongoing Unfollow [1/26]: now unfollowing '****'...
INFO [2019-03-02 14:08:57] [anotherguytravelling]  --> Already unfollowed '****'! or a private user that rejected your req
INFO [2019-03-02 14:08:57] [anotherguytravelling]  	Removed '2019-02-05 01:19 ~ **** ~ ****' from ****_followedPool.csv file

## InstaPy configuration
Raspberry
Instapy Latest Version
session.unfollow_users(amount=400, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=24*60*60, sleep_delay=700)

**Comment by renmatheus** [comment]
Closed

**Comment by renmatheus** [comment]
Close

**Comment by renmatheus** [comment]
Close #4092

**Comment by sionking** [comment]
@uluQulu latest changes for unfollow util made unfollowing unstable. someone need to investigate it as I don't see anything that is wrong with the code.

**Comment by pnoeric** [comment]
Yeah I'm having the exact same problem. Very strange.

**Comment by pnoeric** [comment]
I'm having a similar issue - there's something odd where InstaPy does appear to be unfollowing properly, but the log file says `Already unfollowed ''! or a private user that rejected your req` for each one.

**Comment by GaWr26** [comment]
any updates on this? I have the same problem with one of my accounts.

**Comment by NLJames** [comment]
I am also having this problem!! Please drop here if you get a fix :)

**Comment by ortegafernando** [comment]
me too.

**Comment by matteool** [comment]
Same

**Comment by ortegafernando** [comment]
After some days without doing anything, yesterday I have restarted gain and it seems to work again. temporaly banned?
