### ISSUE TITLE
Problem retrieving user name

### ISSUE THREAD

**Issue by Joyen12** [InstaPy/InstaPy#4094]
## Expected Behavior

Unfollow some users

## Current Behavior

Timeout on the GET request

## Possible Solution (optional)

I have no idea

## InstaPy configuration

On Raspbian stretch Lite Raspberry PI Zero W
Here is the error message :

Sorry, an error occurred: Message: Retried 7 times to GET 'b'https://www.instagram.com/username/'' webpage but failed out of a timeout!
	b'Message: timeout\n  (Session info: headless chrome=65.0.3325.181)\n  (Driver info: chromedriver=2.35 (0),platform=Linux 4.14.98+ armv6l)\n

Thanks a lot if someone can help

Before, I had a very strange error with followedpool.csv but now getting this error

**Comment by oldtajik** [comment]
Same error on AWS Ubuntu server.

 self.logfolder)
  File "/home/ubuntu/InstaPy/instapy/util.py", line 182, in validate_username
    logger)
  File "/home/ubuntu/InstaPy/instapy/util.py", line 928, in get_relationship_counts
    web_address_navigator(browser, user_link)
  File "/home/ubuntu/InstaPy/instapy/util.py", line 1055, in web_address_navigator
    str(exc).encode("utf-8")))
selenium.common.exceptions.TimeoutException: Message: Retried 7 times to GET 'b'https://www.instagram.com/username/'' webpage but failed out of a timeout!
        b'Message: timeout: Timed out receiving message from renderer: 10.000\n  (Session info: headless chrome=72.0.3626.121)\n  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.15.0-1032-aws x86_64)\n'

**Comment by mgconejero** [comment]
same in AWS
