### ISSUE TITLE
Docker - Not writing/creating logs files and cookie

### ISSUE THREAD

**Issue by razki** [InstaPy/InstaPy#4096]
## Expected Behavior
I would expect when using the docker_quickstart.py and docker-compose.yml to see some log files written including a cookie.

## Current Behavior
Bot works fine, however it needs to create a cookie every time and there is no logs directory created

**Comment by Herrox** [comment]
I may be wrong, but it looks like files (logs, cookie, blacklist...) are saved under `~/InstaPy/logs` instead of `/code/InstaPy/logs`

I will have a look on how to fix this.

**Comment by Herrox** [comment]
@razki I just created the PR #4112 to fix this problem.
Waiting for the dev team to review the change and commiting it
