### ISSUE TITLE
Feature - Removing (New) Ghost Followers

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#4097]
@timgrossmann @sionking @uluQulu 
Gentlemen, Instapy is an amazing tool. And I am sure, that from the "perfectionist" point of view, it's goal is not just simply the growth of the "followers" figure, but the growth of the post engagement/likes. e.g. growth of active audience.

Instagram algorithm assesses your active followers to total followers ratio based on your recent posts. And if this one is small or declining, keeps shaping the reach of your future posts to your own followers - aka the phenomenon of "my followers grow but my photo likes - don't". 

There was this method, to block/unblock people to clean up your followers. Very few apps offer this functional AND they make tonnes of errors (I actually caught the best one out there blocking/unblocking active users as much as inactives).

Do you think it is a feature worth considering to add to Instapy? Similar to unfollow, - to crawl through a given number of posts, make a list of the users who liked those posts, and block/unblock the rest (as a result of that - those users just stop following you, that's all). 

/discuss

**Comment by Tachenz** [comment]
Aha, I see this was discussed before - https://github.com/timgrossmann/InstaPy/issues/2057

**Comment by sionking** [comment]
I think it is a good method but need to be done manually.
so scarpe the list by X Y Z parameters.
than let the user go over one by one and block

**Comment by Tachenz** [comment]
Some accounts might have thousands of those ghosts. Manually would be hard :) 

It looks like all the functional is almost there, right? Script can determine you “active” followers based on the last X images analysed

**Comment by Tachenz** [comment]
Actually, there is now a way to “Remove follower” as opposed to blocking.

But yeah, if the amount of ghosts is few thousands, as it will be for bigger accounts - doing it by hand will be a tedious task

**Comment by orlangure** [comment]
@Tachenz Did you find a way to "Remove follower" using IG web interface? As far as IG docs say, it is possible only when using an app.
