### ISSUE TITLE
Not working when TFA Enabled

### ISSUE THREAD

**Issue by marcotile** [InstaPy/InstaPy#41]

**Comment by eduardocalazansjr** [comment]
I think that TFA compatibility would kill the "automation spirit" in this tool.

But, for users that runs on console, asking for the TFA code would be nice and simple to implement.
It's a fight between "automation users" x "console users"

**Comment by mareknebesar** [comment]
It is working without issues for me. I am running it on my laptop and you just need to rewrite the SMS code to the Chrome window, that opens.
