### ISSUE TITLE
Liking limited

### ISSUE THREAD

**Issue by diveu** [InstaPy/InstaPy#410]
Hey, guys
I had my liking feature temporary blocked, but commenting and following still works.
It's not permanent as I can say, because some likes were set, but not as much as I needed.
How long does it usually take to restore the full liking ability? I guess, I went over the limit with almost 1000 likes per day and 150-175 new followers, which were unfollowed at the end of the day. I took a look at Tim's file and got some points out of it (like randomizing most of the numbers) and I guess they should work better

**Comment by timgrossmann** [comment]
@diveu It will take ~1 day to get back to normal (at least it was like this for me)...
