### ISSUE TITLE
[Feature] - limit on like_by_tags

### ISSUE THREAD

**Issue by tujimmy** [InstaPy/InstaPy#4106]
Hi,

I would like to request a new feature on the like_by_tags function which sets a limit on the number of interactions it can do for a follower in a session. I noticed on some tags it would interact with the same users quite often and would like the ability to limit the amount of interaction with the same users in a session. If this feature already exist in another method let me know as I was looking through the documentation but didn't see anything similar to this.

Proposal to add a new parameter (naming convention can be changed)
Track list of users interacted with during the session
Skip the user if previous interactions exceeds the limit specified. 

`session.like_by_tags(['natgeo', 'world'], amount=10, interact=True, times=2)`

**Comment by ghost** [comment]
this is what campaign does.

**Comment by tujimmy** [comment]
Oh thank you I must have skimped over that part not realizing what it was used for.

This issue can be closed
