### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by chuck-23** [InstaPy/InstaPy#4108]
## Current Behavior
Error during installation: 

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-12JV4m/plyer/`

    pip install instapy
    Collecting instapy
      Using cached    https://files.pythonhosted.org/packages/99/44/c75724e8228ae44afb966e6cd39678f6088a247fe928568252d331466097/instapy-0.2.3-py2.py3-none-any.whl
    Collecting configparser>=3.5.0 (from instapy)
      Using cached     https://files.pythonhosted.org/packages/dd/6a/d90db58ec96161e4cae7ced68310f0c5ca860352d35b8ed39f890df15632/configparser-3.7.3-py2.py3-none-any.whl
    Collecting certifi>=2018.10.15 (from instapy)
      Using cached     https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
    Collecting urllib3>=1.24.1 (from instapy)
      Using cached     https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
    Collecting MeaningCloud-python>=1.1.1 (from instapy)
      Using cached     https://files.pythonhosted.org/packages/28/c6/deb6c9d113f94ec99116ec4017b333660ce54344734d29f0cb98fdf32945/MeaningCloud_python-1.1.1-py2.py3-none-any.whl
    Collecting plyer>=1.3.1 (from instapy)
      Downloading     https://files.pythonhosted.org/packages/22/8c/3bdd25b9e489fa62b06937b51dc2611844e58108f458c8e12ea6de7c5db3/plyer-1.4.0.tar.gz (88kB)
        100% |################################| 92kB 2.2MB/s 
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
        ImportError: No module named setuptools
    
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-12JV4m/plyer/
## InstaPy configuration
Installed pip on Debian 9 Server.
`sudo apt install python-pip`
Current version:
```
pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

**Comment by FranklinClinton** [comment]
Run pip install setuptools
