### ISSUE TITLE
When Follow user follower I get : `followers_link` error list index out of range

### ISSUE THREAD

**Issue by Joyen12** [InstaPy/InstaPy#4109]
## Expected Behavior
Follow user follower
## Current Behavior
Not retrieving the users followers, it is empty list : []
## Possible Solution (optional)
I tried everything, even check the xpath, but it is right so I have no idea why it is always empty.
## InstaPy configuration
Raspbian stretch lite
Chromium 65.0.3325.181 Built on Raspbian , running on Raspbian 9.8
instapy-chromedriver==2.36.post0

Also it can't like images, it said I might have been blocked...But I'm not
grab follower is also impossible...

I really don't understand, maybe it can't work on raspbian PI W Zero ?
If it is please tell me, I already lost several weeks trying to make it work on it...Everytime I got an error, I was able to fix all the previous errors but now I'm really stuck

Thank you

**Comment by oldtajik** [comment]
I found out the what causing this problem. Somehow my followedPool list got absolutely empty even though I haven't changed anything in my InstaPy folder. I saw other threads with the same issue and as I see this problem appears with no reason and there's no any solution yet. 

For those who have same issue, u can change all_followed.csv list to followedpoll.csv to unfollow remain users. Also, you may not find your logs in your folder GitHub/Instapy/logs but will find it in User/Instapy/logs

**Comment by mikelebeuf** [comment]
Same thing for me I don’t know why
