### ISSUE TITLE
Automate using Crontab

### ISSUE THREAD

**Issue by kushpvo** [InstaPy/InstaPy#411]
I just deployed the script on my Vultr server and I'm about to setup automation using Crontab to run the script every 4 hours.
But what if the old running script takes more than 4 hours to end?
How do I determine how much time will it take for one script to end? Because I have lot of hashtags put in for the script to work on.. 

So what would be the ideal thing? To reduce the number of interaction in one script? Or to have a larger interval period?

**Comment by kushpvo** [comment]
Is this too much for the script to do? Will it result in a ban? 
Please help in optimizing in that case. 


```python
from instapy import InstaPy
import os

session = InstaPy(username='blah', password='blah')
session.login()

session.set_upper_follower_count(limit = 5000)

session.set_do_follow(enabled=True, percentage=25, times=1)

session.set_do_comment(enabled=True, percentage=40)
session.set_comments(['Awesome!', 'Really Cool!', 'Wonderful Shot!', 'Beautiful!', 'Amazing Shot!', 'This is so cool!', 'Stunning!'])


session.like_by_feed(amount=20)
session.like_by_tags(['#surat'], amount=200)
session.like_by_feed(amount=20)
session.like_by_tags(['#mumbai'], amount=200)
session.like_by_feed(amount=20)
session.like_by_tags(['#delhi'], amount=200)
session.like_by_feed(amount=20)
session.like_by_tags(['#chandigarh'], amount=200)
session.like_by_feed(amount=20)
session.like_by_tags(['#ludhiana'], amount=200)
session.like_by_feed(amount=20)
session.like_by_tags(['#indore'], amount=200)
session.like_by_feed(amount=20)
session.like_by_tags(['#khar'], amount=200)
session.like_by_feed(amount=20)
session.like_by_tags(['#raipur'], amount=200)
session.like_by_tags(['#bhopal'], amount=200)
session.like_by_tags(['#desi'], amount=200)
session.like_by_tags(['#india'], amount=200)
session.like_by_tags(['#bollywood'], amount=200)
session.like_by_tags(['#indian'], amount=200)


session.end()

**Comment by timgrossmann** [comment]
@kushpvo Just for your information, if you run that script, you'll most likely get banned in like 2-3 hours... 
You shouldn't use it this excessive...

To see how long it takes, let it run once and e.g. on the Digital Ocean Graph view of the server, you can see how long the activity there was.

**Comment by kushpvo** [comment]
@timgrossmann Yes, I did realize that. Later, i added random delays between activities and randomized the tag amount. 
And just FYI, to make it run indefinitely, I'm looping the script with multiple random delays and multiple points where it would end the session, wait for some time and then restart the session and stuff.

Thanks for the help! 👍

**Comment by ghost** [comment]
Hi everybody, can someone tell me why my script does not really run? So I installed everything correctly, set the crontab to run quickstart.py. If I check with "grep "quickstart.py" /var/log/syslog" it says the file is run every 3 hours... but I cannot see that I really follow anybody new or liked images. Can you help me?

When I start quickstart from mac terminal it runs through and works fine. But with crontab it seems like nothing happens..... :/
