### ISSUE TITLE
Doesn't unfollow full amount of users. "Windows_Update for Invalid stream"

### ISSUE THREAD

**Issue by oldtajik** [InstaPy/InstaPy#4110]
## Expected Behavior
So I'm getting a problem for unfollowing everyone InstaPy has followed.
InstaPy unfollows until ~1500users, but should be untill 150. And I can't get why, I don't have any errors or crushes, I didn't delete, change or update my repository so my logs should be fine.
I have disabled any follow activity to remove all accs i had to follow, but still.
 Although i am a noob so maybe I don't understand something full.

## Current Behavior
[===========================+--------]  76%    |> Elapsed: 3.32  3731/4806 [===========================+--------]  77%    |> Elapsed: 3.37  3780/4806 [============================+-------]  78%    |> Elapsed: 3.42 minutes    |> ETA: 57.92 seconds      [0304/220413.326:WARNING:spdy_session.cc(3127)] Received WINDOW_UPDATE for invalid stream 3
  3827/4806 [============================+-------]  79%    |> Elapsed: 3.45  3875/4806 [============================+-------]  80%    |> Elapsed: 3.49  3922/4806 [=============================+------]  81%    |> Elapsed: 3.54 minutes    |> ETA: 49.96 seconds      [0304/220420.960:WARNING:spdy_session.cc(3127)] Received WINDOW_UPDATE for invalid stream 7
  3972/4806 [=============================+------]  82%    |> Elapsed: 3.59  
## Possible Solution (optional)
I guess it might me because of the "invalid stream" but not sure.
## InstaPy configuration

def routine():
    # get a session!
    session = InstaPy(username='login', password='pass', headless_browser=True, disable_image_load=True, multi_logs=True)

    # let's go! :>
    with smart_run(session):
        # settings
        session.set_relationship_bounds(enabled=True,
                                        potency_ratio=None,
                                        delimit_by_numbers=True,
                                        max_followers=7500,
                                        max_following=3000,
                                        min_followers=25,
                                        min_following=20,
                                        min_posts=5)
        session.set_skip_users(skip_private=True,
                        skip_no_profile_pic=True,
                        skip_business=False,
                        business_percentage=100)

        session.set_quota_supervisor(enabled=True,
                                    sleep_after=["likes", "comments_d", "follows",
                                                "unfollows", "server_calls_h"],
                                    sleepyhead=True, stochastic_flow=True,
                                    notify_me=False,
                                    peak_likes=(130, 800),
                                    peak_comments=(25, 200),
                                    peak_follows=(70, 600),
                                    peak_unfollows=(99, 700))

        session.set_simulation(enabled=True)

        session.set_user_interact(amount=2, randomize=True, percentage=60,
                                media='Photo')

        session.set_do_like(enabled=True, percentage=80)
        session.set_do_follow(enabled=True, percentage=45, times=1)
        session.set_delimit_liking(enabled=True, max=150, min=10)
        session.set_do_comment(enabled=True, percentage=50)
        session.set_comments([u'comments'],
                         media='Photo')
        targets = ['targets']

        # UNFOLLOW activity
        """ Unfollow nonfollowers after one day...
        """
        session.unfollow_users(amount=random.randint(180, 199),
                            InstapyFollowed=(True, "nonfollowers"),
                            style="FIFO",
                            unfollow_after=6 * 60 * 60, sleep_delay=90)

        """ Unfollow all users followed by InstaPy after one week to keep the
        following-level clean...
        """
        session.unfollow_users(amount=random.randint(350, 450),
                            InstapyFollowed=(True, "all"), style="FIFO",
                            unfollow_after=12 * 60 * 60, sleep_delay=90)

**Comment by oldtajik** [comment]
I found out the what causing this problem. Somehow my followedPool list got absolutely empty even though I haven't changed anything in my InstaPy folder. I saw other threads with the same issue and as I see this problem appears with no reason and there's no any solution yet.

For those who have same issue, u can change all_followed.csv list to followedpoll.csv to unfollow remain users. Also, you may not find your logs in your folder GitHub/Instapy/logs but will find it in User/Instapy/logs

**Comment by tE3m** [comment]
If you don't set a workspace, `~/InstaPy/` will be used automatically. So even if your 'old' folder's logs are empty, the logs are still stored and used.
