### ISSUE TITLE
Scrolled too much

### ISSUE THREAD

**Issue by nitishkatariacs** [InstaPy/InstaPy#4121]
I wanna remove this sleep time while scrolling how to do and thanks for this amazing coding
![screenshot_20190307-230540](https://user-images.githubusercontent.com/48296840/53977044-2ebdc300-412e-11e9-8b21-e141441a3d6b.jpg)
And also I am using python 3.7.2

**Comment by tE3m** [comment]
You're saying you want to fetch 1k posts **without breaks??** :joy:

**Comment by nitishkatariacs** [comment]
Yeah

**Comment by nitishkatariacs** [comment]
And also i cant put sleep delay on the following part and got a shadow ban due to it
