### ISSUE TITLE
Cant start bot after first installation

### ISSUE THREAD

**Issue by SMarcinno** [InstaPy/InstaPy#4122]
## Expected Behavior
starting bot  and do its thing 
## Current Behavior

![20190305_220722](https://user-images.githubusercontent.com/43820577/53978005-83e7dd80-410a-11e9-81ac-a02e597c9a4e.jpg)

## InstaPy configuration
I am using a template with my account in it.
The old version was working fine. Now I wanted to update to the new version, since the older one is not working anymore... So I deleted all and startet over again. After running the setup.py file and fixing all kinds of dependency problems, I cant seem to find a fix for this.

(have the same Problem on my Windows Linux Bash and my Pi)

thanks in advance.

**Comment by octavius-1** [comment]
which chromedriver version do you have?
That excepction (Exec format error) is shown when a non-compatible version of something was found. Remember that for a raspberry you have to always choose armv7l stuff.

**Comment by SMarcinno** [comment]
I tought I dont need to download the chromdriver myself with the new version? Is this not right?
Can you eleborate on the armv7i Stuff? what do you mean exactly?

In the Error message it even says using build in chromedriver

**Comment by tE3m** [comment]
You don't have to download the chromedriver manually anymore, *but* on RPis you need to install `instapy-chromedriver==2.36.post0` which is a binary that fits the Pi's ARM architecture.

**Comment by SMarcinno** [comment]
Thank you guys. I did not know I needed to dowload the extra driver for my Pi. Plus I can not remember If I used it the last time I set it up.
