### ISSUE TITLE
Error at login, No any statistics to show

### ISSUE THREAD

**Issue by CamiloB** [InstaPy/InstaPy#4126]
## Expected Behavior

i change the username of my account was user123 and i changed for user345 but now the instapy does not login, i use other accounts and it works just fine.

## Current Behavior
Righ now instapy send me this error, i already update the instapy and errase the cookie file on tmp files 

`OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-03-07 18:44:28] [*****]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20190307-184506.html
**********************************************************************

INFO [2019-03-07 18:45:06] [***]  Sessional Live Report:
        |> No any statistics to show

[Session lasted 46.32 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-03-07 18:45:06] [***]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "prueba.py", line 16, in <module>
    with smart_run(session):
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/ninus/InstaPy/instapy/util.py", line 1662, in smart_run
    session.login()
  File "/home/ninus/InstaPy/instapy/instapy.py", line 373, in login
    self.bypass_with_mobile):
  File "/home/ninus/InstaPy/instapy/login_util.py", line 262, in login_user
    "//button[text()='Log in']")
  File "/usr/local/lib/python3.4/dist-packages/selenium-3.141.0-py3.4.egg/selenium/webdriver/remote/webdriver.py",
line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.4/dist-packages/selenium-3.141.0-py3.4.egg/selenium/webdriver/remote/webdriver.py",
line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.4/dist-packages/selenium-3.141.0-py3.4.egg/selenium/webdriver/remote/webdriver.py",
line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium-3.141.0-py3.4.egg/selenium/webdriver/remote/errorhandler.py",
line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such
element: Unable to locate element:
{"method":"xpath","selector":"//button[text()='Log in']"}
  (Session info: headless chrome=70.0.3538.77)
  (Driver info: chromedriver=2.43.600233
(523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux
4.4.0-31-generic x86_64)`

## Possible Solution (optional)
righ now im out of options i already try to read the issues but none have this error 

## InstaPy configuration
i use the the quick template [template of instapy](https://github.com/timgrossmann/InstaPy/blob/master/quickstart_templates/basic_follow-unfollow_activity.py )

**Comment by aliceEddie** [comment]
I am having the same problem. Weird thing is I have one account that works fine, but two that give me this error. 
One new one, that isn't able to login (suspicious login attempt is bypassed) and an older one where I changed the password and am now getting the error.

I have deleted the cookie file and even the entire folder connected to the account but nothing helps.

**Comment by CamiloB** [comment]
@aliceEddie hi ! I already solve this problem I have to delete the instapy folder, then I use the command line pip3 uninstall instapy, then I reset my Ubuntu pc, I run sudo pip3 install instapy, and then I run my .py and everything works just fine, I make a clean install and that resolve all mi issues

**Comment by aliceEddie** [comment]
thanks! ununstalling and reinstalling instapy fixed it!
