### ISSUE TITLE
Im still having the same issues with Chromedriver. 

### ISSUE THREAD

**Issue by crowg** [InstaPy/InstaPy#4127]
I have posted this issue before and have only gotten feedback that people are having the same issue. I have installed chrome driver into the file that is directed and nothing has changed. This is the message i receive while trying to run Quickstart.py. 

(Message:
'chromedriver_mac64' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy_chromedriver-2.44-py3.7.egg/instapy_chromedriver/chromedriver_mac64'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bbamagic/Desktop/InstaPy/instapy/browser.py", line 135, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver_mac64' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    disable_image_load=True)
  File "/Users/bbamagic/Desktop/InstaPy/instapy/instapy.py", line 279, in __init__
    self.set_selenium_local_session()
  File "/Users/bbamagic/Desktop/InstaPy/instapy/instapy.py", line 333, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at 

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy_chromedriver-2.44-py3.7.egg/instapy_chromedriver/chromedriver_mac64)

I have googled solutions but nothing is up to date due to the major instapy upgrade and it reverts me to using the assets folder that doesn't exist anymore. is there any insight that someone can give to help out?

**Comment by crowg** [comment]
@timgrossmann

**Comment by FranklinClinton** [comment]
You included almost no info about your configuration. Is it macOS? How does your script look like and when does the exception occur? Have you tried installing instapy with python-pip? 
`
pip install instapy
`
`
pip install instapy-chromedriver
`

After that use a quickstart template and place it in an empty folder and run it like this:
`python quickstart.py --username xxx --password yyy`

**Comment by crowg** [comment]
Sorry for the intense script... here is what happens when I do exactly what you referred. Thank you for the response btw. 

Last login: Mon Mar 11 12:34:20 on ttys000
*****-MacBook-Pro:~ ********$ pip3 install instapy
Requirement already satisfied: instapy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy-0.1.3-py3.7.egg (0.1.3)
Requirement already satisfied: certifi>=2018.10.15 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/certifi-2018.11.29-py3.7.egg (from instapy) (2018.11.29)
Requirement already satisfied: chardet>=3.0.4 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet-3.0.4-py3.7.egg (from instapy) (3.0.4)
Requirement already satisfied: clarifai>=2.4.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/clarifai-2.6.0-py3.7.egg (from instapy) (2.6.0)
Requirement already satisfied: configparser>=3.5.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/configparser-3.7.3-py3.7.egg (from instapy) (3.7.3)
Requirement already satisfied: EasyProcess>=0.2.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/EasyProcess-0.2.5-py3.7.egg (from instapy) (0.2.5)
Requirement already satisfied: emoji>=0.5.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/emoji-0.5.1-py3.7.egg (from instapy) (0.5.1)
Requirement already satisfied: future>=0.17.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/future-0.17.1-py3.7.egg (from instapy) (0.17.1)
Requirement already satisfied: grpcio>=1.16.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/grpcio-1.19.0-py3.7-macosx-10.9-x86_64.egg (from instapy) (1.19.0)
Requirement already satisfied: idna>=2.7 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idna-2.8-py3.7.egg (from instapy) (2.8)
Requirement already satisfied: jsonschema>=2.6.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instapy) (2.6.0)
Requirement already satisfied: plyer>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyer-1.4.0-py3.7.egg (from instapy) (1.4.0)
Requirement already satisfied: protobuf>=3.6.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/protobuf-3.7.0-py3.7-macosx-10.9-x86_64.egg (from instapy) (3.7.0)
Requirement already satisfied: PyVirtualDisplay>=0.2.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyVirtualDisplay-0.2.1-py3.7.egg (from instapy) (0.2.1)
Requirement already satisfied: requests>=2.20.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests-2.21.0-py3.7.egg (from instapy) (2.21.0)
Requirement already satisfied: selenium>=3.141.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg (from instapy) (3.141.0)
Requirement already satisfied: six>=1.11.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/six-1.12.0-py3.7.egg (from instapy) (1.12.0)
Requirement already satisfied: urllib3>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3-1.24.1-py3.7.egg (from instapy) (1.24.1)
Requirement already satisfied: regex>=2018.11.22 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/regex-2019.2.21-py3.7-macosx-10.9-x86_64.egg (from instapy) (2019.2.21)
Requirement already satisfied: MeaningCloud-python>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/MeaningCloud_python-1.1.1-py3.7.egg (from instapy) (1.1.1)
Requirement already satisfied: PyYAML>=3.13 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyYAML-5.1b3-py3.7-macosx-10.9-x86_64.egg (from instapy) (5.1b3)
Requirement already satisfied: instapy-chromedriver==2.44 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy_chromedriver-2.44-py3.7.egg (from instapy) (2.44)
Requirement already satisfied: googleapis-common-protos<2,>=1.5.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/googleapis_common_protos-1.6.0b9-py3.7.egg (from clarifai>=2.4.1->instapy) (1.6.0b9)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from protobuf>=3.6.1->instapy) (40.6.2)
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
*****-MacBook-Pro:~ ********$ pip3 install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-19.0.3
*****-MacBook-Pro:~ ********$ pip3 install instapy
Requirement already satisfied: instapy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy-0.1.3-py3.7.egg (0.1.3)
Requirement already satisfied: certifi>=2018.10.15 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/certifi-2018.11.29-py3.7.egg (from instapy) (2018.11.29)
Requirement already satisfied: chardet>=3.0.4 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/chardet-3.0.4-py3.7.egg (from instapy) (3.0.4)
Requirement already satisfied: clarifai>=2.4.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/clarifai-2.6.0-py3.7.egg (from instapy) (2.6.0)
Requirement already satisfied: configparser>=3.5.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/configparser-3.7.3-py3.7.egg (from instapy) (3.7.3)
Requirement already satisfied: EasyProcess>=0.2.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/EasyProcess-0.2.5-py3.7.egg (from instapy) (0.2.5)
Requirement already satisfied: emoji>=0.5.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/emoji-0.5.1-py3.7.egg (from instapy) (0.5.1)
Requirement already satisfied: future>=0.17.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/future-0.17.1-py3.7.egg (from instapy) (0.17.1)
Requirement already satisfied: grpcio>=1.16.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/grpcio-1.19.0-py3.7-macosx-10.9-x86_64.egg (from instapy) (1.19.0)
Requirement already satisfied: idna>=2.7 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/idna-2.8-py3.7.egg (from instapy) (2.8)
Requirement already satisfied: jsonschema>=2.6.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instapy) (2.6.0)
Requirement already satisfied: plyer>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/plyer-1.4.0-py3.7.egg (from instapy) (1.4.0)
Requirement already satisfied: protobuf>=3.6.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/protobuf-3.7.0-py3.7-macosx-10.9-x86_64.egg (from instapy) (3.7.0)
Requirement already satisfied: PyVirtualDisplay>=0.2.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyVirtualDisplay-0.2.1-py3.7.egg (from instapy) (0.2.1)
Requirement already satisfied: requests>=2.20.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests-2.21.0-py3.7.egg (from instapy) (2.21.0)
Requirement already satisfied: selenium>=3.141.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg (from instapy) (3.141.0)
Requirement already satisfied: six>=1.11.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/six-1.12.0-py3.7.egg (from instapy) (1.12.0)
Requirement already satisfied: urllib3>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3-1.24.1-py3.7.egg (from instapy) (1.24.1)
Requirement already satisfied: regex>=2018.11.22 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/regex-2019.2.21-py3.7-macosx-10.9-x86_64.egg (from instapy) (2019.2.21)
Requirement already satisfied: MeaningCloud-python>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/MeaningCloud_python-1.1.1-py3.7.egg (from instapy) (1.1.1)
Requirement already satisfied: PyYAML>=3.13 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyYAML-5.1b3-py3.7-macosx-10.9-x86_64.egg (from instapy) (5.1b3)
Requirement already satisfied: instapy-chromedriver==2.44 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy_chromedriver-2.44-py3.7.egg (from instapy) (2.44)
Requirement already satisfied: googleapis-common-protos<2,>=1.5.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/googleapis_common_protos-1.6.0b9-py3.7.egg (from clarifai>=2.4.1->instapy) (1.6.0b9)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from protobuf>=3.6.1->instapy) (40.6.2)
*****-MacBook-Pro:~ ********$ pip3 install instapy-chromedriver
Requirement already satisfied: instapy-chromedriver in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy_chromedriver-2.44-py3.7.egg (2.44)
*****-MacBook-Pro:~ ********$ cd desktop
*****-MacBook-Pro:desktop ********$ cd instapy
*****-MacBook-Pro:instapy ********$ python3 quickstart.py —********** —***************

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/********/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-03-11 12:45:24] [***********]  Using built in instapy-chromedriver executable (version 2.44)
ERROR [2019-03-11 12:45:24] [***********]  Message: 'chromedriver_mac64' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy_chromedriver-2.44-py3.7.egg/instapy_chromedriver/chromedriver_mac64'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy-0.1.3-py3.7.egg/instapy/browser.py", line 123, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium-3.141.0-py3.7.egg/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver_mac64' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Traceback (most recent call last):
  File "quickstart.py", line 15, in <module>
    disable_image_load=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy-0.1.3-py3.7.egg/instapy/instapy.py", line 276, in __init__
    self.set_selenium_local_session()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy-0.1.3-py3.7.egg/instapy/instapy.py", line 328, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy_chromedriver-2.44-py3.7.egg/instapy_chromedriver/chromedriver_mac64
*****-MacBook-Pro:instapy ********$ 


> You included almost no info about your configuration. Is it macOS? How does your script look like and when does the exception occur? Have you tried installing instapy with python-pip?
> `pip install instapy`
> `pip install instapy-chromedriver`
> 
> After that use a quickstart template and place it in an empty folder and run it like this:
> `python quickstart.py --username xxx --password yyy`

**Comment by FranklinClinton** [comment]
Are you running it as root, or as a normal user?
Also please try upgrading instapy with pip. And of course use a quickstart script from the examples folder in this repository.

**Comment by crowg** [comment]
i am on my laptop which i am the only one who uses it. so there are no guest settings if that is what you are referring too. 

and i use PIP primarily. I used pip3 to show that it does the same for both pip and pip3

**Comment by FranklinClinton** [comment]
Have you tried to update instapy with pip? While I can't fix your primary issue, I can give you a workaround: Download VirtualBox or some other kind of virtualization software and create a VM with Ubuntu Linux. Ubuntu Linux is easy to install and after that install instapy on ubuntu. Should be an easy task and will get you running in about 2 hours.

**Comment by tE3m** [comment]
Did you try `chmod`?
