### ISSUE TITLE
signal only works in main thread

### ISSUE THREAD

**Issue by dlenskyi** [InstaPy/InstaPy#4130]
## Expected Behavior
Storing all info in .csv files
## Current Behavior
Failed to store `Following` data in a local file :Z
b'signal only works in main thread'

I didn't find issue with this problem solved.
Please tell me what should I do?

**Comment by FranklinClinton** [comment]
Please me more specific. What versions are you running and how does your script look like?

**Comment by dlenskyi** [comment]
@FranklinClinton 
Im tryna run that byt this way:
main.py

from my_functions import inter_tag

inter_tag.inter_tag(constants.insta_username,
                                                constants.insta_password,
                                                str(constants.telegram_id),
                                                str(constants.my_telegram_id),
                                                constants.my_hashtags,
                                                constants.comments,
                                                constants.my_usernames)

inter_tag.py

#!/usr/bin/python
# coding: utf-8
from instapy import InstaPy
from instapy import Settings
from datetime import datetime
from instapy.util import truncate_float
import schedule
import time
import random
import requests

def inter_tag(insta_username,
            insta_password,
            telegram_id,
            my_telegram_id,
            my_hashtags,
            comments,
            my_usernames):
    try:
        Settings.database_location = "./db/instapy_{}.db".format(insta_username)
        session = InstaPy(username=insta_username, 
                        password=insta_password,  
                        headless_browser=True, 
                        multi_logs=True)
        session.login()
        ############SETTINGS##############
        session.set_skip_users(skip_private=False, 
                            private_percentage=0, 
                            skip_no_profile_pic=True, 
                            no_profile_pic_percentage=100)
        session.set_do_follow(enabled=True, 
        					percentage=45)
        session.set_do_comment(enabled=True, 
        					percentage=45)

        session.set_comments(comments)

        session.set_do_like(enabled=True, 
        					percentage=70)
        session.set_user_interact(amount=2, 
        						randomize=True, 
        						percentage=85, 
        						media='Photo')
        ############SETTINGS##############
        session.set_dont_unfollow_active_users(enabled=True, 
                                            posts=5)
        session.unfollow_users(amount=200, 
                            nonFollowers=True, 
                            style="RANDOM",
                            unfollow_after=35 * 60 * 60, 
                            sleep_delay=300)
        session.follow_by_tags(my_hashtags, 
                            amount=35, 
                            randomize=True)
        session.like_by_tags(my_hashtags, 
        					amount=35, 
                            randomize=True, 
        					interact=True)
        session.end()
    except:
        import traceback
        print(traceback.format_exc())

if __name__ == '__main__':
    inter_tag()

sorry for bad indentations in some lines

**Comment by dlenskyi** [comment]
I dont know why it is bad aligned..

**Comment by FranklinClinton** [comment]
Are you sure you are running latest version installed by pip/pip3? Verify that. Then run a quickstart example to verify configuration.

**Comment by tE3m** [comment]
The problem is that you are using `schedule` and `threaded`. I had been using that as well, but I didn't find a solution for that. Use a shell script that starts two different scripts instead of threading the functions.

**Comment by dlenskyi** [comment]
Problem was somehow solved itself :)

**Comment by hanagantig** [comment]
In my case the Exception `ValueError: signal only works in main thread` is heppaning when I run session in thread (not in main thread). The problem in `session.end()` method. It runs with `interruption_handler` context.
If you check `interruption_handler` you can see that it has parameter `threaded=False` by default. 
So, if I write  `with interruption_handler(threaded=threaded_session):` in` Instapy.end()` method and call `session.end(threaded_session=True)` it solves the problem.
