### ISSUE TITLE
Can i get help on how do i change sleep delay ?

### ISSUE THREAD

**Issue by hepton** [InstaPy/InstaPy#4133]
<!-- Is this a Feature Request ? Please, check out our Wiki first https://github.com/timgrossmann/InstaPy/wi

**Comment by FranklinClinton** [comment]
The sleep delay has its purpose. Please be more specific about your problem.

**Comment by hepton** [comment]
It sleeps after following less then 10 people, and its sleeping for 10 min. I want it to sleep 5 mins but after following like 50 people.

**Comment by FranklinClinton** [comment]
You can change delay with 
custom_list = ["user_1", "user_2", "user_49", "user332", "user50921", "user_n"]
session.unfollow_users(amount=84, customList=(True, custom_list, "all"), style="RANDOM", unfollow_after=55*60*60, sleep_delay=600) 

I don't know if you can change the amount of people to unfollow. Search the readme file of this repository for "sleep" and you will find even more examples.
