### ISSUE TITLE
target followers template 

### ISSUE THREAD

**Issue by followsmoke** [InstaPy/InstaPy#4140]
Hi, 

I would like to know if it was possible to interact without following?

Thanks a lot

**Comment by kev-mas** [comment]
Hi @followsmoke ,

Yes, it's possible to interact without following. You can comment the following line out by adding a `#` in front of it:

```
session.set_do_follow(enabled=True, percentage=75, times=1)
```

Or set it to false:

```
session.set_do_follow(enabled=False)
```

Regards.

**Comment by followsmoke** [comment]
Thank you for your answer @LunaticZorr but i already tried session.set_do_follow(enabled=False) and i think the problem comes from this line:

# FOLLOW+INTERACTION on TARGETED accounts
    """ Select users form a list of a predefined targets...
    """
    number = random.randint(3, 5)
    random_targets = targets

    if len(targets) <= number:
        random_targets = targets

    else:
        random_targets = random.sample(targets, number)

    """ Interact with the chosen targets...
    """
    session.follow_user_followers(random_targets,
                                  amount=random.randint(30, 60),
                                  randomize=True, sleep_delay=600,
                                  interact=True)

Would you have a solution?

Thanks.
