### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by tasselchof** [InstaPy/InstaPy#4141]
Using cached https://files.pythonhosted.org/packages/cc/3e/29f92b7aeda5b078c86d14f550bf85cff809042e3429ace7af6193c3bc9f/typing-3.6.6-py2-none-any.whl
clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.
Installing collected packages: six, grpcio, idna, urllib3, certifi, chardet, requests, EasyProcess, instapy-chromedriver, PyVirtualDisplay, emoji, functools32, pyrsistent, attrs, jsonschema, plyer, selenium, future, PyYAML, regex, configparser, protobuf, MeaningCloud-python, googleapis-common-protos, typing, clarifai, instapy
  Found existing installation: six 1.4.1
Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by tE3m** [comment]
Please install with `python3`, not `python2.7`
