### ISSUE TITLE
Proxy services discussion: Which to use?

### ISSUE THREAD

**Issue by octavius-1** [InstaPy/InstaPy#4142]
I've been using SmartProxy residential IPs service for around one week but damn, they are expensive as hell, I hadn't realized the amount of data instapy consumes even when running headless. I was wondering, which proxy services have you used to get your tool working in AWS or DigitalOcean? We all know that data center IPs are being banned when using instapy there.

**Comment by converge** [comment]
I have been using Blazing Proxy for more than a year, it's a good service:

Maybe there is a discount with my referral link: https://billing.blazingseollc.com/hosting/aff.php?aff=583

I use dedicated IP's.

**Comment by sionking** [comment]
You will get like block when using datacenter ip, so you need to do only follow.
Build your own 4/3g network is best solution.

**Comment by FranklinClinton** [comment]
I am located in Germany and I don't need a proxy at the moment. Instapy is hosted in a quite large datacenter but not in so called public clouds. Usually I comment and like 500 pictures a day. So far I haven't been blocked. How many pictures can you like/comment with a proxy?

If you need a lot of IPs you can just rent a server with a ipv6 address. Those usually come with a /64 subnet. Then you can install a proxy which listens on ports 10000-60000 and routes it to an individual ipv6 address. This could be a cheap solution and is definitely possible in my country.

**Comment by sionking** [comment]
ipv6 is less trusted than ipv4

**Comment by FranklinClinton** [comment]
Have you any proof for this? I haven't tried it myself yet but I heared that it works well

**Comment by lezlea** [comment]
I keep getting my likes blocked in the last month using AWS even though I'm only liking 200 a day (and I used to like over 900).  I automatically restart the service once a day so it's new IP addresses daily, could this be the problem?   I'm not entirely sure what proxy service to use or what I need so any advice very welcome.  Just looking in to blazingseollc as recommended above. Thanks!

**Comment by cararsevdi** [comment]
> You will get like block when using datacenter ip, so you need to do only follow.
> Build your own 4/3g network is best solution.

you said to build own 3/4g network but how many accounts can support ui mean is it need to proxy or not

**Comment by lezlea** [comment]
Sorry are you saying it is better to pay for 'mobile phone' IP addresses and use those as proxys?

**Comment by dpascoa** [comment]
Is it safe to run 2 bots without a proxy?

**Comment by octavius-1** [comment]
@dpascoa You can run even 3 but only if they're placed inside a residential network. Data center IPs are continuously banned.

**Comment by dpascoa** [comment]
@octavius-1 Thanks for your answer. I'm new in this topic. I'm using google cloud plataform, is that safe to use at least two bots? Or is it a data center? 

To run 3 in my residential network it means to keep my computer running 24/7?

Thanks once again.

**Comment by octavius-1** [comment]
@dpascoa We were all new at some point, don't worry.

Yes, google cloud, azure, AWS and DigitalOcean are all data centers. I'd recommend to stop using the tool without proxies there if you don't want a like-ban.

Yes, residential network means running it in your computer (or you could buy a Raspberry).

**Comment by dpascoa** [comment]
@octavius-1 Thanks! I understand what you say, but why data centers are likely to get banned?

Is that because there are a bunch of people using the same IP, and instagram detects it? Or is there another reason?

And it is safer from my residential network because it probably seems more human? Since from my own IP, I'm, probably, the only one using a bot?

I find this topic interesting :)
