### ISSUE TITLE
counting likers of post doesn't work with video

### ISSUE THREAD

**Issue by dlenskyi** [InstaPy/InstaPy#4146]
## Expected Behavior
Skip posts with video, or count users
## Current Behavior
Error, when function session.set_dont_unfollow_active_users(enabled=True, posts=5)
It cannot neither skip, nor grab users from video post
## InstaPy configuration
def inter_tag():
    try:
        session = InstaPy(username=insta_username, 
                        password=insta_password,  
                        headless_browser=True, 
                        multi_logs=True)
        session.login()
        session.set_skip_users(skip_private=False, 
                            private_percentage=0, 
                            skip_no_profile_pic=True, 
                            no_profile_pic_percentage=100)
        session.set_do_follow(enabled=True, 
        					percentage=45)
        session.set_do_comment(enabled=True, 
        					percentage=45)

        session.set_comments(comments)

        session.set_do_like(enabled=True, 
        					percentage=70)
        session.set_user_interact(amount=1, 
        						randomize=True, 
        						percentage=85, 
        						media='Photo')
        ############SETTINGS##############
        session.set_dont_unfollow_active_users(enabled=True, 
                                            posts=5)
        session.unfollow_users(amount=200, 
                            nonFollowers=True, 
                            style="RANDOM",
                            unfollow_after=35 * 60 * 60, 
                            sleep_delay=300)
        session.follow_by_tags(my_hashtags, 
                            amount=35, 
                            randomize=True)
        session.like_by_tags(my_hashtags, 
        					amount=35, 
                            randomize=True, 
        					interact=True)
        session.end()
    except:
        import traceback
        print(traceback.format_exc())

**Comment by octavius-1** [comment]
That's expected, dude.
You can't take a look of video likers when using instagram web, give it a try.

**Comment by dlenskyi** [comment]
So why instapy doesn’t skip it, but escapes?

**Comment by octavius-1** [comment]
Could you please paste the scenario you're looking at?

**Comment by dlenskyi** [comment]
I have already posted my configuration in 1st post
Function session.set_dont_unfollow_active_users don’t skip video posts, but throw an exception instead

**Comment by clevebounce** [comment]
me too
