### ISSUE TITLE
A new function request to skip following some usernames

### ISSUE THREAD

**Issue by hasangok** [InstaPy/InstaPy#415]
Hi!

I think it would be great if this script has a function something like set_ignore_users_if_usename_contains :)

I selected some locations and tags, following and commenting on posts to attact my target group for a while, and it's working very well. But I'm always following some blabla_photography and ig_blabla accounts. A function to skip all of them would be great!

Thanks!

**Comment by timgrossmann** [comment]
@hasangok Would be interesting to see how many people think this is an interesting feature.

**Comment by srtcoz** [comment]
Hi, 

I agree with @hasangok ,i think it would be useful to eliminate some similar type of accounts like some groups or promotion accounts, so we can have interaction with just personal accounts.

**Comment by converge** [comment]
There is few interest in this feature at the moment. Please reopen it if you need.
