### ISSUE TITLE
clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.

### ISSUE THREAD

**Issue by dvc2019** [InstaPy/InstaPy#4154]
Hello, I'm having all sorts of issues installing and/or running InstaPy on a droplet. I previously uninstalled and deleted my droplet because it was stuck on login. Now that I've installed on a new droplet, I'm getting this error (which is a new one for me): "clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible."

I've tried other solutions like uninstalling Json 3.01 and installing a version less than 3. Still no idea how to get InstaPy working.

**Comment by mikelebeuf** [comment]
Same mine crashes right when it opens and I don’t seem to be able to find the assets file so I don’t know were to put my chromedriver

**Comment by mikelebeuf** [comment]
Try installing jsonschema==2.6 it worked for me but didn’t fix the crashing bug that I think is created by my assets file missing

**Comment by crowg** [comment]
I don't have any answers that can help. But I think this is part of the same problem that I have been having in not getting my QuickStart.py file to work.

**Comment by crowg** [comment]
Change that! An update was just released that I believe addresses this issue. I did a pip update and now my quickstart.py file is going with no issue. Hopefully it works for you.

**Comment by dvc2019** [comment]
The new update didn’t work for me. What did work was installing InstaPy first via git clone, then doing Digital Ocean installation steps one by one. I still reached the same json error but at that point InstaPy was already installed and my quickstart already edited. I then finished up with the pip install InstaPy command and it didn’t overwrite my quickstart. I then was able to run quickstart.py

That doesn’t seem to be the way it should be, but at least I am able to run it. It says it liked 10 images and only liked 9.





On Mar 14, 2019, at 3:12 PM, crowg <notifications@github.com<mailto:notifications@github.com>> wrote:


Change that! An update was just released that I believe addresses this issue. I did a pip update and now my quickstart.py file is going with no issue. Hopefully it works for you.

**Comment by ExportEh** [comment]
Mine is running without issue and I have the "clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible."

I don't think your concern is related but I'm certainly no expert. I'm just mentioning so that you don't chase an error that is not directly related to your bigger issue.

**Comment by hscanlan** [comment]
I also have this issue - fresh install, Python 3.7.3

**Comment by itsvasugrover** [comment]
Well you can try this command in order to stop it crashing `pip install jsonschema==2.6.0`... If you are still having a problem please let me know, I will figure out a different way..

**Comment by hscanlan** [comment]
Whoops, I should've followed up. This is exactly what I did and it works wonderful

**Comment by ghost** [comment]
I have the same problem.

> Well you can try this command in order to stop it crashing `pip install jsonschema==2.6.0`... If you are still having a problem please let me know, I will figure out a different way..

This method didn't work with me. Can you show a different way?

**Comment by dvc2019** [comment]
For me, the solution was not installing on Digital Ocean via the install file steps like I had been, but doing exactly what Tim did on the new install video in February.

:)




On Apr 27, 2019, at 9:10 AM, ronconkreet <notifications@github.com<mailto:notifications@github.com>> wrote:


I have the same problem.

Well you can try this command in order to stop it crashing pip install jsonschema==2.6.0... If you are still having a problem please let me know, I will figure out a different way..

This method did'nt work with me. Can you show a different way?

**Comment by ghost** [comment]
Unfortunately...
Until recently, everything worked without problems.

**Comment by idnr** [comment]
> Well you can try this command in order to stop it crashing `pip install jsonschema==2.6.0`... If you are still having a problem please let me know, I will figure out a different way..

this took away the ERROR for jsonschema, but now i have this error, do you know how to correct it?

ERROR: Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by osekresvibe** [comment]
Same here, I haven't been able to get past this error: ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/idna'
Consider using the `--user` option or check the permissions. I have tried the --user option but to no avail. Anyone has any ideas they can share about how they bypassed any of such issues?

**Comment by eddie121** [comment]
> Same here, I haven't been able to get past this error: ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/idna'
> Consider using the `--user` option or check the permissions. I have tried the --user option but to no avail. Anyone has any ideas they can share about how they bypassed any of such issues?

having the same issue and have not found a fix yet

**Comment by eddie121** [comment]
> > Well you can try this command in order to stop it crashing `pip install jsonschema==2.6.0`... If you are still having a problem please let me know, I will figure out a different way..
> 
> this took away the ERROR for jsonschema, but now i have this error, do you know how to correct it?
> 
> ERROR: Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

having the same issue and not fix yet

**Comment by dusanvesovic** [comment]
I solve dis by using command
pip install tld --ignore-installed six --user

**Comment by iamdgarcia** [comment]
> > > Well you can try this command in order to stop it crashing `pip install jsonschema==2.6.0`... If you are still having a problem please let me know, I will figure out a different way..
> > 
> > 
> > this took away the ERROR for jsonschema, but now i have this error, do you know how to correct it?
> > ERROR: Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
> 
> having the same issue and not fix yet

To solve this error you can just type `pip install --ignore-installed six`

**Comment by danigarci1** [comment]
> > > Well you can try this command in order to stop it crashing `pip install jsonschema==2.6.0`... If you are still having a problem please let me know, I will figure out a different way..
> > 
> > 
> > this took away the ERROR for jsonschema, but now i have this error, do you know how to correct it?
> > ERROR: Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
> 
> having the same issue and not fix yet

Try to install instapy manually `pip install --user instapy`

**Comment by iamdgarcia** [comment]
> > Same here, I haven't been able to get past this error: ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/idna'
> > Consider using the `--user` option or check the permissions. I have tried the --user option but to no avail. Anyone has any ideas they can share about how they bypassed any of such issues?
> 
> having the same issue and have not found a fix yet

Try to install instapy manually `pip install --user instapy`
