### ISSUE TITLE
Instapy Crashed RPI 3

### ISSUE THREAD

**Issue by ljacobo** [InstaPy/InstaPy#4155]
Hi, 

is somebody experiencing issues running instapy in RPI3?

Everything was working ok, but since a few days the unfollow method is not working and if i update instapy nothing works.

**Comment by gitpatrickhub** [comment]
I just updated InstaPy on Raspberry Pi 3 and Unfollow action results in;

```
Unable to get `Following` data:
	b"'NoneType' object is not subscriptable"
```

**Comment by ljacobo** [comment]
Im using the instapy 0.2.0 version without problems, but i think instagram is having some issues.

**Comment by gitpatrickhub** [comment]
My issue appears to have been related to IG outage. Work as designed now.

**Comment by ljacobo** [comment]
The unfollow method is working with you? which version of instapy are you running?

**Comment by anitato** [comment]
I’m in the same situation. The problem started for me at the end of February. InstaPy runs for some amount of time (half a day to sometimes several days) but eventually crashes in my Raspberry Pi 3.

I saw some earlier threads discussing the same thing as well, and last I heard, people recognize a problem but it’s unclear if it’s actually being addressed?

Hope we can get it working again!

**Comment by gitpatrickhub** [comment]
@ljacobo sorry just getting back to you. I'm running version 0.3.2 on RPI3 using headless Firefox.

**Comment by fuckInvestments** [comment]
Having the same issue. It has happened a couple times over the last 25 or so days. I eventually completed reinstalled the OS and scripts to get it working again. But now I am back to the original problem.

**Comment by anitato** [comment]
I have a more detailed explanation of the problem here: #4192. This has been happening for me since the end of February (running an older version of InstaPy). I updated everything, clean install, and this problem persists even with the newest version.

The run time varies for me, as do the error messages (seems like it encounters a different problem each time? Does that mean multiple likely problems?). What can we do?
