### ISSUE TITLE
Oops, an error occured

### ISSUE THREAD

**Issue by zmcdbiz** [InstaPy/InstaPy#4156]
whenever started the instapy login works but then when it begins to do anything else it says "oops, an error occurred". any suggestions? it wont load anything

**Comment by lerra** [comment]
I am getting the same (it was working perfectly fine 8h ago), suspecting that I was running instapy maybe a little bit to hard while using the app at the mobile. My plan is to just wait a couple of days for it to get solved by it self, if not, I have a problem :-)

**Comment by lezlea** [comment]
Yeah I just got this with one of my accounts and a temporary action like ban.  Now I can't even post a story.  If anything happens on your end or you have any advice other than give it a break, please let me know.  Thanks, Lezlea

**Comment by MattB543** [comment]
I think Instagram is having issues. See this reddit [post ](https://www.reddit.com/r/Instagram/comments/b0nzcj/instagram_connection_issue/)

**Comment by lezlea** [comment]
Oh I've just been on google and Instagram are having issues - 

"We’re aware of an issue impacting people's access to Instagram right now. We know this is frustrating, and our team is hard at work to resolve this ASAP."

https://www.altpress.com/news/facebook-instagram-down/
