### ISSUE TITLE
Problem with install on raspberry pi

### ISSUE THREAD

**Issue by mlwrose** [InstaPy/InstaPy#4159]
## Expected Behavior
Launch the browser and login
## Current Behavior
'OSError: [Errno 8] Exec format error'

## Possible Solution (optional)
?

**Comment by tE3m** [comment]
You didn't follow the install guide for RPi. You have to run
```
pip3 uninstall instapy-chromedriver
pip3 install instapy-chromedriver==2.36.post0
```
