### ISSUE TITLE
After latest update, private users are not being followed.

### ISSUE THREAD

**Issue by octavius-1** [InstaPy/InstaPy#4163]
When trying to interact with a private_account these messages are shown now:

User username [1/10]
Starting to interact by users...
Username[1/1]
--> b'username'
username_actions: following=True commenting=False liking=True
Getting username image list...
Is private account you're not following
Element not found, skipping this username.

And this happens for all of the private users.

(This was tested when "Interact user followers" was enabled)

**Comment by bugre** [comment]
As far i know, you can only interact with private users ir you are following them.

**Comment by aliirezaaa** [comment]
@bugre that means the bot not send follow request to private accounts at all?

**Comment by bugre** [comment]
if you have set 'skip_private=true' i think it will not try to follow them. But i'm in no way an expert.
