### ISSUE TITLE
How can I make my bot follow private users? Is there a reason we don't follow private users?

### ISSUE THREAD

**Issue by lizechoo** [InstaPy/InstaPy#4168]
## Expected Behavior
Following private accounts
## Current Behavior
Not following private accounts
## InstaPy configuration
Just a normal follow_user_followers but it skips all private users, how can I make the bot follow private?

**Comment by bugre** [comment]
Dear @lzchoo and @aliirezaaa,

Please take a look at the documentation. There it's explained how to skip (or not if you want) private or business accounts.

https://github.com/timgrossmann/InstaPy#skipping-user-for-private-account-no-profile-picture-business-account

**Comment by lizechoo** [comment]
@bugre is there a reason why we might want to skip private?

**Comment by aliirezaaa** [comment]
I set skip private account to False but the bot say '' element not fount '' and skip the user :(

**Comment by bugre** [comment]
> I set skip private account to False but the bot say '' element not fount '' and skip the user :(

Are you sure that you are following the user that is skipped? If you're not following him, you can't interact with him. (as far i know at least). Instapy behaves like you would do it on a browser manually.

**Comment by bugre** [comment]
> @bugre is there a reason why we might want to skip private?

i don't want to interact (automatically) with my followers that have their account private. Only do it manually.
