### ISSUE TITLE
Are there any other ways to stop running bot except KeyboardInterrupt and kill process?

### ISSUE THREAD

**Issue by dlenskyi** [InstaPy/InstaPy#4169]
I need to stop bot automatically in particular moment, which I will write into script. Any keyboard insertions like Ctrl+C etc. don't fit my condition. Is there any way to do it?

**Comment by tE3m** [comment]
Well, if you know where to stop you can use either `time.sleep(time in seconds)` or `session.end()` if you want to finish the session instead of sleeping

**Comment by dlenskyi** [comment]
Well, thanks
