### ISSUE TITLE
Error on executing the example.py file

### ISSUE THREAD

**Issue by DeependraSinghC** [InstaPy/InstaPy#417]
I have followed all the steps mentioned on the home page but I still can't get to fix the below error:

```
sudo python example.py
Traceback (most recent call last):
  File "example.py", line 2, in <module>
    from instapy import InstaPy
**ImportError: cannot import name InstaPy**
```

I know it's a dependency error but how do I fix this? 
Thanks

**Comment by timgrossmann** [comment]
You need to make sure that the file you're executing is at the level of the `quickstart.py` file.
It won't work if your file is somewhere else

**Comment by DeependraSinghC** [comment]
Works now. Thanks! This is great. :)
