### ISSUE TITLE
Raspberry Pi 3B+ - Run multiple accounts, RAM problem

### ISSUE THREAD

**Issue by thejeromelouis** [InstaPy/InstaPy#4171]
Hello, I would like to run multiple accounts on my Pi. But the pi already hangs on 3 accounts. It also has to do with which command is executed. For example, I have no problems with unfollow. I would be happy for help.

**Comment by ljacobo** [comment]
Which version of instapy are you running?

**Comment by thejeromelouis** [comment]
Thanks for your message @ljacobo. I'm running the latest version of instapy. I think it's 0.3.3.

**Comment by thejeromelouis** [comment]
Thanks for your message @ljacobo. I'm running the version 0.3.3 of instapy with Chrome driver 2.36.post0

**Comment by ljacobo** [comment]
Good, so do i.

Running multiple accounts, are you running an instance of instapy at the same time or are you playing with schedule method or cron?

Because i used to run an instance 24/7 using supervisor quota and a "while true" loop.

thnks!!

**Comment by CharlesCCC** [comment]
uhhh, it sounds like a limitation of hardware and I don't think there is anything we can do about beside suggest you use a more powerful device...

**Comment by thejeromelouis** [comment]
Now I've added "disable_image_load=True" and it works fine for 4 Accounts. Thank you guys. But I would like to know how many accounts you guys manage with your Pi?

**Comment by juanmicl** [comment]
Can you show your .py content? I have some raspberries
