### ISSUE TITLE
How many accounts can be on one private proxy server?

### ISSUE THREAD

**Issue by dlenskyi** [InstaPy/InstaPy#4172]
I'm gonna run my script on a proxy server with multiple accounts. Before that I ran on my PC 3 accounts with same ip.
So Q is how many accounts are allowed to run on particular private proxy server?

**Comment by sionking** [comment]
0-2 those days.
0 if proxy is DC ort flageged.
2 if you got luckey no to be like blocked.

**Comment by dlenskyi** [comment]
Thanks
