### ISSUE TITLE
Search Location, then tags within location - we need this feature!

### ISSUE THREAD

**Issue by MoneyMikeOttawa** [InstaPy/InstaPy#4174]
I want to search a location.
Then within that location I want to like / follow specific tags.

Can you add this feature or explain to me how it works, cause ive tried many options with no success.

**Comment by visualheroes** [comment]
Already in there. I use it everyday.

Exemple:

> session.set_mandatory_words(['#matterhorn', '#mountain'])
> session.like_by_locations(['213933962/zermatt-switzerland/'], amount=50, skip_top_posts=True)

**Comment by MoneyMikeOttawa** [comment]
and that works for you? when i use it it keeps loading photos and more photos then error after it likes a random one. annoying!~!!

**Comment by visualheroes** [comment]
It works perfectly for me (i load mandatory words from an external text file).

Maybe your amount of post is to high? Or you don't have the right hashtags for this location.

**Comment by sionking** [comment]
search too tight
