### ISSUE TITLE
Error: cannot import name 'smart_run' from 'instapy'

### ISSUE THREAD

**Issue by Yosoycoder** [InstaPy/InstaPy#4179]
## Expected Behavior
Run quickstart normally
## Current Behavior
I cannot run properly the quickstart file, I get the following error message:

/Users/userxxxx/anaconda3/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    from instapy import smart_run
ImportError: cannot import name 'smart_run' from 'instapy' (/Users/userxxxx/anaconda3/lib/python3.7/site-packages/instagram_py-0.0.1-py3.7.egg/instapy/__init__.py)
MacBook-Air-de-xxxxx:instapy-quickstart-master userxxxx$ 

Also during the installation I got the following message: 

Installing collected packages: certifi, requests, instapy
  Found existing installation: certifi 2018.8.24
Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

## InstaPy configuration

I had the previous version of instapy, tried to install the new one with the simplified installation and run it. I changed the quickstart file with a template just to include the login info.

**Comment by FranklinClinton** [comment]
Please paste your whole quickstart.py file. Feel free to blank the username and password.

**Comment by vexersa** [comment]
Same behaviour here with using the demo quickstart.py as per the installation instructions. 


```
""" Quickstart script for InstaPy usage """		
# imports		
from instapy import InstaPy		
from instapy import smart_run		
	
# get an InstaPy session!		
session = InstaPy()		
	
with smart_run(session):		
    """ Activity flow """		
    # general settings		
    session.set_dont_include(["friend1", "friend2", "friend3"])		
	
    # activity		
    session.like_by_tags(["natgeo"], amount=10)
```		

Then ran the script with the --username and --password parameters.

**Comment by FranklinClinton** [comment]
@vexersa did the installation throw errors?

**Comment by Yosoycoder** [comment]
This is my quickstart file:

```
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'xxxxxxxxx'
insta_password = 'xxxxxxxxxx'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                    min_followers=45,
                                    min_following=77)

    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])

    # activities

    """ Massive Follow of users followers (I suggest to follow not less than
    3500/4000 users for better results)...
    """
    #session.follow_user_followers(['user1', 'user2', 'user3'], amount=800,
                                  #randomize=False, interact=False)

    """ First step of Unfollow action - Unfollow not follower users...
    """
    session.unfollow_users(amount=500, InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=601)

    """ Second step of Massive Follow...
    """
    #session.follow_user_followers(['user1', 'user2', 'user3'], amount=800,
                                  #randomize=False, interact=False)

    """ Second step of Unfollow action - Unfollow not follower users...
    """
    session.unfollow_users(amount=500, InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=601)

    """ Clean all followed user - Unfollow all users followed by InstaPy...
    """
    session.unfollow_users(amount=500, InstapyFollowed=(True, "all"),
                           style="FIFO", unfollow_after=24 * 60 * 60,
                           sleep_delay=601)
```
I think the problem is related with the installation error message that I mentioned. It seems there is no right way to uninstall properly the previous versions of instapy and that is messing with the installation of the new version.

```
Installing collected packages: certifi, requests, instapy
Found existing installation: certifi 2018.8.24
Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by Yosoycoder** [comment]
> This is my quickstart file:
> 
> ```
> # imports
> from instapy import InstaPy
> from instapy import smart_run
> 
> # login credentials
> insta_username = 'xxxxxxxxx'
> insta_password = 'xxxxxxxxxx'
> 
> # get an InstaPy session!
> # set headless_browser=True to run InstaPy in the background
> session = InstaPy(username=insta_username,
>                   password=insta_password,
>                   headless_browser=False)
> 
> with smart_run(session):
>     """ Activity flow """
>     # general settings
>     session.set_relationship_bounds(enabled=True,
>                                     delimit_by_numbers=True,
>                                     max_followers=4590,
>                                     min_followers=45,
>                                     min_following=77)
> 
>     session.set_dont_include(["friend1", "friend2", "friend3"])
>     session.set_dont_like(["pizza", "#store"])
> 
>     # activities
> 
>     """ Massive Follow of users followers (I suggest to follow not less than
>     3500/4000 users for better results)...
>     """
>     #session.follow_user_followers(['user1', 'user2', 'user3'], amount=800,
>                                   #randomize=False, interact=False)
> 
>     """ First step of Unfollow action - Unfollow not follower users...
>     """
>     session.unfollow_users(amount=500, InstapyFollowed=(True, "nonfollowers"),
>                            style="FIFO",
>                            unfollow_after=12 * 60 * 60, sleep_delay=601)
> 
>     """ Second step of Massive Follow...
>     """
>     #session.follow_user_followers(['user1', 'user2', 'user3'], amount=800,
>                                   #randomize=False, interact=False)
> 
>     """ Second step of Unfollow action - Unfollow not follower users...
>     """
>     session.unfollow_users(amount=500, InstapyFollowed=(True, "nonfollowers"),
>                            style="FIFO",
>                            unfollow_after=12 * 60 * 60, sleep_delay=601)
> 
>     """ Clean all followed user - Unfollow all users followed by InstaPy...
>     """
>     session.unfollow_users(amount=500, InstapyFollowed=(True, "all"),
>                            style="FIFO", unfollow_after=24 * 60 * 60,
>                            sleep_delay=601)
> ```
> I think the problem is related with the installation error message that I mentioned. It seems there is no right way to uninstall properly the previous versions of instapy and that is messing with the installation of the new version.
> 
> ```
> Installing collected packages: certifi, requests, instapy
> Found existing installation: certifi 2018.8.24
> Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
> ```

OK I updated Anaconda to the newest version, installed again Instapy and now it works!!
