### ISSUE TITLE
session.follow_likers(follow_likers_per_photo <10 ) is not working

### ISSUE THREAD

**Issue by DmytroDiachuk** [InstaPy/InstaPy#4182]
### What is Problem? 

When I start  **session.follow_likers**  with  **follow_likers_per_photo <10** instapy does not work. When I change  **follow_likers_per_photo** to 10 or more it works.

### What Do I see in terminal? 

> INFO [2019-03-17 16:10:20] [my_account]  Using built in instapy-chromedriver executable (version 2.46)
> INFO [2019-03-17 16:10:22] [my_account]  Session started!
> INFO [2019-03-17 16:10:56] [my_account]  Logged in successfully!
> INFO [2019-03-17 16:10:56] [my_account]  Saving account progress...
> INFO [2019-03-17 16:11:01] [my_account]  Starting to follow likers..
> INFO [2019-03-17 16:11:40] [my_account]  Finished following Likers!
> 
> INFO [2019-03-17 16:11:40] [my_account]  Followed: 0
> INFO [2019-03-17 16:11:40] [my_account]  Already followed: 0
> INFO [2019-03-17 16:11:40] [my_account]  Not valid users: 0
> INFO [2019-03-17 16:11:40] [my_account]  Liked: 0
> INFO [2019-03-17 16:11:40] [my_account]  Already Liked: 0
> INFO [2019-03-17 16:11:40] [my_account]  Commented: 0
> INFO [2019-03-17 16:11:40] [my_account]  Inappropriate: 0
> 
>  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
> Workspace in use: "/root/InstaPy"
> 

> Getting likers from user:  **_user_account_** 
> shuffling links
> Got  24 , returning  3  links:  ['link_to_photo', 'link_to_photo', 'link_to_photo']
> opening likes
> Scrolling finished
> Got 0 likers shuffled randomly whom you can follow:
> []

## Possible Solution (optional)
I am not python programmer  yet, but I think that  problem is hidding in https://github.com/timgrossmann/InstaPy/blob/master/instapy/commenters_util.py  function  **likers_from_photo**

## InstaPy configuration
```
from instapy import InstaPy
session = InstaPy(multi_logs=True, headless_browser=True)
session.login()

session.set_relationship_bounds(enabled=True,
             potency_ratio=0.71,
              delimit_by_numbers=True,
               max_followers=2200,
                max_following=1100,
                 min_followers=10,
                  min_following=30);

session.follow_likers(['user_account'], 
    photos_grab_amount = 3, 
      follow_likers_per_photo = 9 , 
       randomize=True, 
           sleep_delay=200, 
             interact=True);
```

P/S When I change **follow_likers_per_photo** to 10 or more it works.

**Comment by octavius-1** [comment]
Yeah, that happens. But actually using it with an amount less than 10 doesn't work because after a few runs you'll get always the same people in those first 10 elements.

**Comment by DmytroDiachuk** [comment]
@octavius-1  What is impact from **randomize=True**? This property has impact on **photos_grab_amount** or  **follow_likers_per_photo**, or both?
In my case, If under photo 500 likes and i set  **randomize=True**,  Must  robot  gets  9 users randomly?

**Comment by octavius-1** [comment]
Yes, just the first users shown are retrieved because the scrolling happens when bigger numbers are set.

**Comment by DmytroDiachuk** [comment]
@octavius-1 I think if I set **randomize=True**,  scrolling must work always.  I was expecting this behavior when I set **randomize=True**.

**Comment by an0key** [comment]
The number of users doesn't appear to be respected at higher numbers either, if I set it to say 1000, it gathers 17 users.... when the selected photo range (i.e. 3 previous) has over 1000 likes each...
