### ISSUE TITLE
Crash with smart_location

### ISSUE THREAD

**Issue by Zettt** [InstaPy/InstaPy#4187]
I'm running into an issue with the new `set_smart_location_hashtags` feature. It crashes suddenly, and because the browser closes too, I can't figure out which location it causes to crash. The list is too long to find the location *quickly* by trial and error. The crashlog is not helpful either. Any suggestions?

```
Traceback (most recent call last):
  File "me/start.py", line 184, in <module>
    session.set_smart_location_hashtags(['213281320/dubai-united-arab-emirates', '212988663/new-york-new-york', '213385402/london-united-kingdom', '213429964/edinburgh-united-kingdom', '73347620/dublin-ireland', '6889842/paris-france', '7226110/tokyo-japan', '222651085/shenzhen-guangdong', '17326249/moscow-russia', '213163910/sao-paulo-brazil', '212999109/los-angeles-california', '213174824/saint-petersburg-russia', '214427142/jakarta-indonesia', '212903416/istanbul-turkey', '213100244/barcelona-spain', '207409165/prague-czech-republic', '213633143/brussels-belgium', '31499759/rome-italy', '63134088/vienna-austria', '213326726/warsaw-poland', '213682323/bratislava-slovakia', '214578719/innsbruck-austria', '213205633/budapest-hungary', '213606897/ljubljana-slovenia', '213649265/zagreb-croatia', '213076173/athens-greece', '215730538/tirana-albania', '213076173/athens-greece', '213232307/sofia-bulgaria', '73959962/bucharest-romania', '212898659/kyiv-ukraine', '217478883/odessa-ukraine', '116231/amsterdam-netherlands', '213050058/milan-italy', '73347620/dublin-ireland', '7538318/copenhagen', '213211804/oslo-norway', '213094275/stockholm-sweden', '548627416/helsinkifinnland', '213819997/vancouver-british-columbia', '8351513/montreal-quebec', '217631504/casablanca-morocco'], radius=300, limit=3)
  File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 666, in set_smart_location_hashtags
    lat, lon = get_cord_location(self.browser, location)
  File "/usr/local/lib/python3.7/site-packages/instapy/util.py", line 2121, in get_cord_location
    lat = data['graphql']['location']['lat']
KeyError: 'graphql'
```

**Comment by bugre** [comment]
Hi @Zettt ,
one of your locations doesn't match IG locations database. 
I think we have some improvements we could/should do in the get_cord_location(), so the error doesn't propagate and crash InstaPy,  but instead generate log entry saying "...location xxx not found, skipping.." or something like that. 

Improvement's i mean:
 - limit the number of locations we can check to a max to avoid abuse.
 - check if the call to IG page+find..by_xpath did return a valid element
 - try/catch the json.load call
 - insert some delay/sleep time between call's.

I did a quick check on the location lists you've provided on your issue, they all fine. Problem is that with that many, IG does punish you with to many request's if you check them sequentially. Note the two last requests with HTTP 429 return code ( https://httpstatuses.com/429 )

Would suggest for now, run it with like 5 locations only, to not standout and get a ban (eventually).

```bash
06:12 $
(venv) ✔ ~/dsv/fixes/InstaPy/t [master|…1⚑ 4]
06:12 $ cat loc | while read loc; do res=`curl -sI "https://www.instagram.com/explore/locations/${loc}?__a=1" | head -1`; echo "Location: [$loc] - $res"; done
Location: [213281320/dubai-united-arab-emirates] - HTTP/1.1 200 OK
Location: [212988663/new-york-new-york] - HTTP/1.1 200 OK
Location: [213385402/london-united-kingdom] - HTTP/1.1 200 OK
Location: [213429964/edinburgh-united-kingdom] - HTTP/1.1 200 OK
Location: [73347620/dublin-ireland] - HTTP/1.1 200 OK
Location: [6889842/paris-france] - HTTP/1.1 200 OK
Location: [7226110/tokyo-japan] - HTTP/1.1 200 OK
Location: [222651085/shenzhen-guangdong] - HTTP/1.1 200 OK
Location: [17326249/moscow-russia] - HTTP/1.1 200 OK
Location: [213163910/sao-paulo-brazil] - HTTP/1.1 200 OK
Location: [212999109/los-angeles-california] - HTTP/1.1 200 OK
Location: [213174824/saint-petersburg-russia] - HTTP/1.1 200 OK
Location: [214427142/jakarta-indonesia] - HTTP/1.1 200 OK
Location: [212903416/istanbul-turkey] - HTTP/1.1 200 OK
Location: [213100244/barcelona-spain] - HTTP/1.1 200 OK
Location: [207409165/prague-czech-republic] - HTTP/1.1 200 OK
Location: [213633143/brussels-belgium] - HTTP/1.1 200 OK
Location: [31499759/rome-italy] - HTTP/1.1 200 OK
Location: [63134088/vienna-austria] - HTTP/1.1 200 OK
Location: [213326726/warsaw-poland] - HTTP/1.1 200 OK
Location: [213682323/bratislava-slovakia] - HTTP/1.1 200 OK
Location: [214578719/innsbruck-austria] - HTTP/1.1 200 OK
Location: [213205633/budapest-hungary] - HTTP/1.1 200 OK
Location: [213606897/ljubljana-slovenia] - HTTP/1.1 200 OK
Location: [213649265/zagreb-croatia] - HTTP/1.1 200 OK
Location: [213076173/athens-greece] - HTTP/1.1 200 OK
Location: [215730538/tirana-albania] - HTTP/1.1 200 OK
Location: [213076173/athens-greece] - HTTP/1.1 200 OK
Location: [213232307/sofia-bulgaria] - HTTP/1.1 200 OK
Location: [73959962/bucharest-romania] - HTTP/1.1 200 OK
Location: [212898659/kyiv-ukraine] - HTTP/1.1 200 OK
Location: [217478883/odessa-ukraine] - HTTP/1.1 200 OK
Location: [116231/amsterdam-netherlands] - HTTP/1.1 200 OK
Location: [213050058/milan-italy] - HTTP/1.1 200 OK
Location: [73347620/dublin-ireland] - HTTP/1.1 200 OK
Location: [7538318/copenhagen] - HTTP/1.1 200 OK
Location: [213211804/oslo-norway] - HTTP/1.1 200 OK
Location: [213094275/stockholm-sweden] - HTTP/1.1 200 OK
Location: [548627416/helsinkifinnland] - HTTP/1.1 200 OK
Location: [213819997/vancouver-british-columbia] - HTTP/1.1 200 OK
Location: [8351513/montreal-quebec] - HTTP/1.1 429 -
Location: [217631504/casablanca-morocco] - HTTP/1.1 429 -
(venv) ✔ ~/dsv/fixes/InstaPy/t [master|…1⚑ 4]
06:13 $
```

You could change the source-code if your familiar with coding, if not
Maybe tonight or tomorrow night i'll be able to provide a patch.

**Comment by Zettt** [comment]
Sounds fair enough. I was not thinking today. I should have guessed, this counts against my API usage limit. With 5 locations it's running better. I get a different kind of error at the end though. 

I know how to code but I'm not good enough to write code productively, i.e. it takes me a very long time.

```
Traceback (most recent call last):
  File "me/start.py", line 190, in <module>
    session.like_by_tags([], amount=6, interact=True)
  File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 1885, in like_by_tags
    self.logger.info('Tag: {}'.format(tag.encode('utf-8')))
UnboundLocalError: local variable 'tag' referenced before assignment
```

**Comment by bugre** [comment]
Is this using the same running environment? 
I did some digging and found a situation where it could happen, 'tag' variable not initialized. 
It happens using like_by_tags(), when the selected options result in no 'tags' selected. 
Could this be the case?

**Comment by bugre** [comment]
Hi,
Unfortunately i'll be unable to test or make an oficial PR for this for the next couple os days at least. 

If you wanna/can help test it, you could download the branch from: https://github.com/bugre/InstaPy/tree/fix/bugre-smart_location_crash-issue4187

Let me know if it crashes badly :)

It should address the two errors you reported.

**Comment by bugre** [comment]
Hi @Zettt 
Did you have the opportunity to test the patched code? Yesterday i've run a small test, but i don't use this functionality on my regular runs. 
let me know if it worked.

@timgrossmann What would be your recommended/expected approach, i can sometimes try to patch some issues that people find, but often not able to test it correctly or in the same way as the reporter the issue.

This patch isn't very complex, but could have side effects not foreseen (besides try/catch the Crash/Exception, also added some code lessen the chance of the error to happen (sleep) and report/log when it should happen. I've made a quick test run, but i hadn't used smart_locations_tags before, so no knowledge of the functionality itself.

**Comment by bugre** [comment]
Hi @timgrossmann Saw that you're active (don't know how much time you've available) but as this was a crash case, maybe we could try to merge it what you think? I've hadn't had the time to rebase it to the dev branch, this is the reason i've not PR'ed it yet. 
I'll try to do it tonight.

I've not heard back from @Zettt if he had the opportunity to test it himself.
