### ISSUE TITLE
Grab a list of my 'non followers' and comment on their photos

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4190]
hey guys, fine? 

Maybe this its so stupid question but... I'm trying to get my non followers list and, send one comment for these people. So... my question is... is here, anyway to do this? or I'll need to go to instabot to try something like? 

I already have a more and less 100+ examples to comment and, follow 1030 users, but, Im followed by 410... so, I just want to send a comment to these users who dont follow me to "remind" them to do it... 

_**Can someone help me with an example of how to do this?**_

**Comment by bugre** [comment]
Hi,
have a read on instapy documentation, please!
Specifically this is related to what you wanna do: https://github.com/timgrossmann/InstaPy#interact-by-comments

Please close this issue if it addresses your question.
