### ISSUE TITLE
ERROR! Follow by location and sleep delay

### ISSUE THREAD

**Issue by yunggoose** [InstaPy/InstaPy#4191]
## Expected Behavior

Would it possible to integrate the same delay used in the "follow user followers" function?
By this I mean, since the follow user followers function stops @ every 10 users, it sleeps for a set amount of time. Would it be possible to add that same rule to the "follow by location" and ''like by location'' function? That way we don't risk getting banned for following too many users, or liking to many pictures therefore we can avoid surpassing the Instagram threshold

## Current Behavior

It crashes and it doesn't work. Error:

![error](https://user-images.githubusercontent.com/45880561/54620592-b37dda80-4a66-11e9-86ac-b6b6862d72c7.PNG)

**Comment by sbug51** [comment]
I am facing the same issue, I am worried about running my code because I don't want to be banned.
