### ISSUE TITLE
cannot import name 'smart_run" from "Instapy'

### ISSUE THREAD

**Issue by salas81** [InstaPy/InstaPy#4196]
I'm getting this error when launching Instapy

`macbook:InstaPy lorenzo.decaria$ pip3 install instapy
Collecting instapy
  Using cached https://files.pythonhosted.org/packages/81/67/578dfc0dd0212983d8aca39035c775487cd93c3638dce6cdb0d94f099cd9/instapy-0.3.4-py2.py3-none-any.whl
Requirement already satisfied: emoji>=0.5.1 in /usr/local/lib/python3.7/site-packages (from instapy) (0.5.1)
Requirement already satisfied: PyVirtualDisplay>=0.2.1 in /usr/local/lib/python3.7/site-packages (from instapy) (0.2.1)
Requirement already satisfied: PyYAML>=3.13 in /usr/local/lib/python3.7/site-packages (from instapy) (5.1)
Requirement already satisfied: selenium>=3.141.0 in /usr/local/lib/python3.7/site-packages (from instapy) (3.141.0)
Requirement already satisfied: certifi>=2018.10.15 in /usr/local/lib/python3.7/site-packages (from instapy) (2019.3.9)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.7/site-packages (from instapy) (1.12.0)
Requirement already satisfied: MeaningCloud-python>=1.1.1 in /usr/local/lib/python3.7/site-packages (from instapy) (1.1.1)
Requirement already satisfied: grpcio>=1.16.1 in /usr/local/lib/python3.7/site-packages (from instapy) (1.19.0)
Requirement already satisfied: protobuf>=3.6.1 in /usr/local/lib/python3.7/site-packages (from instapy) (3.7.0)
Requirement already satisfied: chardet>=3.0.4 in /usr/local/lib/python3.7/site-packages (from instapy) (3.0.4)
Requirement already satisfied: instapy-chromedriver in /usr/local/lib/python3.7/site-packages (from instapy) (2.46)
Requirement already satisfied: jsonschema>=2.6.0 in /usr/local/lib/python3.7/site-packages (from instapy) (3.0.1)
Requirement already satisfied: future>=0.17.1 in /usr/local/lib/python3.7/site-packages (from instapy) (0.17.1)
Requirement already satisfied: urllib3>=1.24.1 in /usr/local/lib/python3.7/site-packages (from instapy) (1.24.1)
Requirement already satisfied: clarifai>=2.4.1 in /usr/local/lib/python3.7/site-packages (from instapy) (2.6.1)
Requirement already satisfied: configparser>=3.5.0 in /usr/local/lib/python3.7/site-packages (from instapy) (3.7.3)
Requirement already satisfied: EasyProcess>=0.2.3 in /usr/local/lib/python3.7/site-packages (from instapy) (0.2.5)
Requirement already satisfied: regex>=2018.11.22 in /usr/local/lib/python3.7/site-packages (from instapy) (2019.3.12)
Requirement already satisfied: plyer>=1.3.1 in /usr/local/lib/python3.7/site-packages (from instapy) (1.4.0)
Requirement already satisfied: requests>=2.20.1 in /usr/local/lib/python3.7/site-packages (from instapy) (2.21.0)
Requirement already satisfied: idna>=2.7 in /usr/local/lib/python3.7/site-packages (from instapy) (2.8)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from protobuf>=3.6.1->instapy) (40.5.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/site-packages (from jsonschema>=2.6.0->instapy) (19.1.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.7/site-packages (from jsonschema>=2.6.0->instapy) (0.14.11)
Requirement already satisfied: googleapis-common-protos<2,>=1.5.0 in /usr/local/lib/python3.7/site-packages (from clarifai>=2.4.1->instapy) (1.5.8)
Installing collected packages: instapy
Successfully installed instapy-0.3.4
macbook:InstaPy lorenzo.decaria$ python3 quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    from instapy import smart_run
ImportError: cannot import name 'smart_run' from 'instapy' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instagram_py-0.0.1-py3.7.egg/instapy/__init__.py)
macbook:InstaPy lorenzo.decaria$ `

This is the console output after having installed Instapy

**Comment by vexersa** [comment]
Same issue, 
` File "quickstart.py", line 4, in <module>
    from instapy import smart_run
ImportError: cannot import name smart_run
`
