### ISSUE TITLE
jsonschema & EnvironmentError: [Errno 13]

### ISSUE THREAD

**Issue by jakedaffern** [InstaPy/InstaPy#4199]
Error 1 - clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.

Error 2 - Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/certifi-2019.3.9.dist-info'
Consider using the `--user` option or check the permissions.

Does anyone know the problem causing this and how to resolve?

**Comment by tE3m** [comment]
Why are you using `python2.7`?

**Comment by jordanjoecooper** [comment]
@TarekJ03  I am guessing he is using it as it is the default version of Python included in Mac OS.

**Comment by jordanjoecooper** [comment]
If anyone else stumbles across this, the solution is the accepted answer: https://stackoverflow.com/questions/49704364/make-python3-as-my-default-python-on-mac
