### ISSUE TITLE
Don't follow own followers

### ISSUE THREAD

**Issue by mheubaum** [InstaPy/InstaPy#4201]
Hey guys, is there a way to jump every follow if the target user is already folowing me? I would prefer to change it for all features in the code but also for particular features like interact_user_followers would be great!

**Comment by sionking** [comment]
yes there is. the info is in the graphql

**Comment by mheubaum** [comment]
What do you mean with "the info is in the graphql"?

**Comment by pinkoveralls** [comment]
If somebody could give a more detailed explanation of how to set this up, it would be super helpful to me too.
