### ISSUE TITLE
followedPool disappeared

### ISSUE THREAD

**Issue by booksix** [InstaPy/InstaPy#4202]
I came home and checked my scripts and found an error, at the beginning of an unfollow session, that said the followedPool file did not exist. I double checked and it is certainly missing. I checked the trash, too (even though I knew I had not even been in the Instapy folders for a few days)... nothing, it's just gone. Seems very strange, and I'm assuming this will keep me from properly running any "unfollow after" options!

**Comment by oldtajik** [comment]
same here.. happens all the time

**Comment by yaca8** [comment]
yep happened to me couple of times as well, is there any way to prevent it or to restore it?
