### ISSUE TITLE
Recommended strategic approach

### ISSUE THREAD

**Issue by GaWr26** [InstaPy/InstaPy#4205]
Hey everybody,

installed InstaPy on a Raspberry Pi a couple of days ago and I love it.

I started off with the quickstart template _good_commenting_strategy_and_new_qs_system.py_, tweaked it a bit and run it from cron every morning at 6am with a random delay up to an hour to be as human as possible for 4 accounts. The script does likes, follows, comments and then unfollows and then ends. With this, I get around 25 new followers every day.

I want to rely on session.set_quota_supervisor to keep thing safe. I have the following configuration:
`session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "comments", "follows", "unfollows", "server_calls"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(60, 800),
                                 peak_comments=(21, 250),
                                 peak_unfollows=(None, 700),
                                 peak_follows=(50, 700),
                                 peak_server_calls=(600, 8000))`
The scripts run between 10 to 15 hours every day but not all limits are reached.
I see people use may different approaches. Some run a script every 3 hours, some run 24/7.

As I have some experience with other services which work with limits and sleep during the night to simulate human behaviour I'm thinking about how I can get the most out of the system.

My goal is to build a script that likes, comments, follows and unfollows until all limits are reached in approx. 18 hours and then ends. Is this actually a good strategy?

Does it make sense to loop and check for quota limits and skip to the next action if these are reached for one action? Is it possible to spread all interactions across a specified amount of time e.g. 800 likes, 250 comments, 700 unfollows, 700 follows in 18 hours every day?

Am I having the right approach or am I spoiled by other services?
How are you guys handling things? 

Would be great to get some insights on a decent strategy for getting the most out of every day the service runs.

Cheers!

**Comment by alexlle** [comment]
Hi! 
How did you manage to run it between hours?
I mean, how did you manage to stop it at 15 hours?

**Comment by GaWr26** [comment]
I configured my script so it would run approximately for this amount of time. Tweaking values for likes and follows makes this possible.
