### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by GeoffreyPG** [InstaPy/InstaPy#4206]
## Current Behavior

I have this error and I do not know what to do
I did what was said and looked for other issues, but I did not find anything

Starting InstaPy with quickstart
====================
Traceback (most recent call last):
  File "../quickstart.py", line 15, in <module>
    from instapy import InstaPy
ImportError: No module named instapy
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Opération terminée]

**Comment by GaWr26** [comment]
looks to my like you're not running it with python3. 

check `python --version`
