### ISSUE TITLE
Not an issue but a request for advice on "cron" in docker for windows

### ISSUE THREAD

**Issue by RealMakAttak** [InstaPy/InstaPy#421]
Hello all,

Would someone please point me in the direction of how to run timed docker-compose builds in docker on windows - at the moment I am having to manually run it from the command line throughout the day, bit annoying.

Many thanks!

Mak

**Comment by Naramsim** [comment]
Hey, consider this two solutions:
Use cron inside the container, use [schedule](https://github.com/dbader/schedule)

**Comment by RealMakAttak** [comment]
@Naramsim Thank you very much for your suggestions, I used a version of schedule and that has worked sufficiently for the time being.

Thanks again!
