### ISSUE TITLE
Quota Supervisor

### ISSUE THREAD

**Issue by pedro639** [InstaPy/InstaPy#4214]
Quota supervisor insists in not working, Ive read the docs 100 times, the configs are 100% the same and still doesnt work!

**Comment by AndreySurikov** [comment]
Yes! What happened?

My limit: peak_follows=(20, 200),

But InstaPy (follow_by_locations) in one hour made more than 20 follows...

And BAN? ))

___________________________________________________________________________
session.set_quota_supervisor(enabled=True, sleep_after=["likes", "follows"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(0, 0),
                               peak_comments=(20, 200),
                                peak_follows=(20, 200),
                                 peak_unfollows=(0, None))

session.follow_by_locations ([ '447991' ], amount = 50)
________________________________________________________________________

**Comment by ghost** [comment]
Same here

**Comment by danielbeltejar** [comment]
Same here

**Comment by danielbeltejar** [comment]
@pedro639 @AndreySurikov @ygorduraes you need to put quota supervisor before all others things

**Comment by pedro639** [comment]
I have it before all other lines, and still doesn't work

**Comment by danielbeltejar** [comment]
@pedro639 upload config then to check
