### ISSUE TITLE
Issue with interact_by_comments

### ISSUE THREAD

**Issue by primopierotz** [InstaPy/InstaPy#4215]
Hi, I'm suddenly experiencing a problem with interact_by_comment.
I'm using this template: https://github.com/InstaPy/instapy-quickstart

## Expected Behavior

Until this some days ago, I could like comments on specified profile's post, and like the last post on the commenters' profile.

## Current Behavior

Now, I get this message

> INFO [2019-03-26 13:19:55] [username]  Failed to get comments' count!
>         b"Message: unknown error: Cannot read property 'count' of undefined\n  (Session info: chrome=72.0.3626.121)\n  (Driver info: chromedriver=2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90),platform=Windows NT 10.0.17134 x86_64)\n"
> INFO [2019-03-26 13:19:55] [username]  No interaction did happen.
> 

Instapy pass on every post and I get the same message for all.

## InstaPy configuration
```python
""" Quickstart script for InstaPy usage """

from instapy import InstaPy
from instapy import smart_run


insta_username = 'username'
insta_password = 'password'


session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):

   
   session.set_do_reply_to_comments(enabled=False, percentage=0)
   session.set_comment_replies(replies=[], media="Photo")

   session.set_user_interact(amount=3, percentage=70, randomize=False, media="Photo")
   session.set_do_like(enabled=True, percentage=100)
   
   session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(62, 602),
                               peak_comments=(21, 182),
                                peak_follows=(48, None),
                                 peak_unfollows=(35, 402),
                                  peak_server_calls=(None, 4700))
                                  
   
   session.interact_by_comments(usernames=["buddy1","buddy2"], posts_amount=10, comments_per_post=5, reply=False, interact=True, randomize=True, media="Photo")
```

**Comment by GaWr26** [comment]
Same here for _session.set_do_comment._ Getting:

`--> Not commenting! Failed to get comments' count!`

Maybe Instagram changed something?

**Comment by bertlandh** [comment]
Same here..
Failed to get comments' count!
	b"Message: javascript error: Cannot read property 'count' of undefined\n  (Session info: chrome=73.0.3683.86)\n  (Driver info: chromedriver=2.46.628411

**Comment by m-ketan** [comment]
A quick workaround is to comment out ```session.set_delimit_commenting``` in your script.

**Comment by timgrossmann** [comment]
@primopierotz @flashguy22 @bertlandh Have you guys seen this error with other configurations, too?

**Comment by primopierotz** [comment]
@m-ketan  thanks for the tip!

@timgrossmann thanks for your reply! I haven't tried other configurations yet.

**Comment by GaWr26** [comment]
@timgrossmann I only have this one configuration running on two accounts
@m-ketan thanks, seems to comment again. Crazy how much impact commenting has..

**Comment by gyrex** [comment]
I'm getting the same error message. I've commented out "session.set_delimit_commenting" but I'd prefer to implement limits on commenting.

**Comment by primopierotz** [comment]
Sadly, in my script I have no session.set_delimit_commenting to comment out

**Comment by bertlandh** [comment]
Hi @timgrossmann I am still having this issue see my code below

import random
from instapy import InstaPy
from instapy.util import smart_run


# login credentials
insta_username = 'xxxx'
insta_password = 'xxx'

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True,)

# let's go! :>
with smart_run(session):


    session.set_action_delays(enabled=True,
                         like=60,
                         comment=90,
                         follow=4.17,
                         unfollow=28,
                         random_range=(70, 140))

    # general settings
    
    session.set_do_follow(enabled=False, percentage=4, times=1)
    session.set_do_comment(enabled=True, percentage=30)
    session.set_comments([
                             u'Great capture!! :smiley: :thumbsup: What do '
                             u'you think of my recent photo?'],
                         media='Photo')
    session.set_do_like(True, percentage=70)
    
    session.set_user_interact(amount=1, randomize=False, percentage=40)

    # activity
    session.interact_by_comments(usernames=["bertlandh",],
                             posts_amount=10,
                             comments_per_post=5,
                             reply=True,
                             interact=True,
                             randomize=True,
                             media="Photo")

**Comment by AndreySurikov** [comment]
I have a similar problem. About 5 days. Please, help ))
"... Cannot read property 'count'  ..."

**Comment by primopierotz** [comment]
@timgrossmann  i'm also having the issue in #4250 
Maybe Instagram is changing some things? Have your team some information about it?

**Comment by sudonitin** [comment]
goto 'C:\Users\HP\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\instapy'

open login_util.py goto line 262 edit the 'Log in' to 'Log In'.

Worked for me.

**Comment by kev-mas** [comment]
Having the same issue too

```
INFO [2019-04-05 13:36:39] [kevmasphoto]  --> Image Liked!
INFO [2019-04-05 13:37:12] [kevmasphoto]  --> Not commenting! Failed to get comments' count!
	Message: unknown error: Cannot read property 'count' of undefined
  (Session info: headless chrome=73.0.3683.103)
  (Driver info: chromedriver=2.45.615279 ,platform=Linux 4.4.0-96-generic x86_64)
```
