### ISSUE TITLE
Headless browser error

### ISSUE THREAD

**Issue by jiuguangw** [InstaPy/InstaPy#4219]
## Current Behavior

Instapy doesn't work when setting headless browser to true. I tried to grab my own following list with 

```
photog_follower = session.grab_following(
        username="testuser", amount="full", live_match=True, store_locally=True)
```

which produces this error: 

```
INFO [2019-03-27 11:50:26] [testuser]  Retrieving live `Following` data of testuser at "full" range
INFO [2019-03-27 11:50:53] [testuser]  Encountered an error to find `pre` in page! ~grabbed 0 usernames 
    b'Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}\n  (Session info: headless chrome=74.0.3729.28)\n  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.3 x86_64)\n'
```

However, when setting headless to false, the script works as expected.

**Comment by CharlesCCC** [comment]
Can you please provide a little bit more detail with your environment (OS, python version, Instapy version, how you install InstaPy etc.) and configure files ?

**Comment by jiuguangw** [comment]
MacOS 10.14.3, Anaconda Python 3.6.5. Latest Instapy, installed via pip (also tried direct clone from repo, same behavior). I used the same script as https://github.com/timgrossmann/InstaPy/issues/4134 because I was searching for the same error - "Encountered an error to find `pre` in page". Not sure how @FranklinClinton handled it, but changing the headless browser setting worked for me.

Even right now, with headless=false, I get this at times:

```
Insufficient amount of links ~ trying again: 1
INFO [2019-03-28 09:38:29] [jiuguangw]  Insufficient amount of links ~ trying again: 2
INFO [2019-03-28 09:38:54] [jiuguangw]  Insufficient amount of links ~ trying again: 3
INFO [2019-03-28 09:38:57] [jiuguangw]  Cor! Did you send too many requests? ~ let's rest some

```

**Comment by CharlesCCC** [comment]
okay, based off your descritpion:

> Insufficient amount of links ~ trying again: 1
> INFO [2019-03-28 09:38:29] [jiuguangw]  Insufficient amount of links ~ trying again: 2
> INFO [2019-03-28 09:38:54] [jiuguangw]  Insufficient amount of links ~ trying again: 3
> INFO [2019-03-28 09:38:57] [jiuguangw]  Cor! Did you send too many requests? ~ let's rest some

and @FranklinClinton 's update:

> Update: I found a way to watch the chrome browser and the problem is, that instapy is navigating chrome to
> https://www.instagram.com/graphql/query/?query_hash=37479f2b8209594dde7facb0d904896a&variables={%22id%22:%20%227744440002%22,%20%22first%22:%2050}
> but instagram.com returns http code 403 forbidden. I can't figure out what the problem is

It is very likely you have send too many request within 24 hrs, so the Instagram.com blocked your request(not sure why it is only happens under headless tho, it might have something todo with Instagram.com anti-bot mechanism ?) .  Can you share your detailed config on how many potential engagement you are given (and what's the currently running schedule) ?

**Comment by jiuguangw** [comment]
It's not clear to me that the number of requests is the problem. I encountered the error within 5 minutes of starting the script after a break of several days. All functionalities in app (like/follow/unfollow) remains unaffected. It's unlike previous soft ban behaviors I've seen

**Comment by CharlesCCC** [comment]
Okay, that shouldn't be the problem then. 
There are only two places that references the `pre` tag:

https://github.com/timgrossmann/InstaPy/blob/433b457bb93a21111917e01b0f2dda8b9a4ad2b6/instapy/util.py#L1586
https://github.com/timgrossmann/InstaPy/blob/1fcc2fdc8bfd9810dabfa576bc9d73500baad8a3/instapy/relationship_tools.py#L142  (Where your problem at) 

The other possible causes are the hash value that used to call those API maybe invalidated or their API structure has changed, the later one seems more possible. (with similar issue #4216 )

**Comment by GeoffreyPG** [comment]
Same error !
Unable to locate element: {"method":"tag name","selector":"pre"}\n

**Comment by rvoets** [comment]
Me too!

`Encountered an error to find `pre` in page!`
`no such element: Unable to locate element: {"method":"tag name","selector":"pre"}`
