### ISSUE TITLE
Errors always! (pip install)

### ISSUE THREAD

**Issue by imsilenzi** [InstaPy/InstaPy#422]
I can not install "instapy".
What I do?

(TUTORIAL)
1. For a start you need:
> To have Python 2.7 or 3.6 installed.
> Setted up path for PY command.
> Installed Selenium and pyvirtualdriver.

(ME)
- open terminal
- download Python (2.x and 3.x)
<img width="488" alt="screen shot 2017-07-21 at 00 30 43" src="https://user-images.githubusercontent.com/6278152/28441598-edbe727a-6dab-11e7-85cf-3c0c9cb38fd3.png">
<img width="490" alt="screen shot 2017-07-21 at 00 31 00" src="https://user-images.githubusercontent.com/6278152/28441600-f083e292-6dab-11e7-88b2-0f69e3e2d63c.png">

- Setted up path for PY command.
- I go to "Selenium site" (http://selenium-python.readthedocs.io/installation.html)
- Paste in terminal "pip install selenium" 
[ERROR!]
```
Last login: Fri Jul 21 00:30:54 on ttys000
You have new mail.
MBP-di-Niccolo:~ Niccolo$ pip install selenium
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
ImportError: No module named pip
MBP-di-Niccolo:~ Niccolo$ 

```
<img width="489" alt="screen shot 2017-07-21 at 00 33 04" src="https://user-images.githubusercontent.com/6278152/28441653-2dde5398-6dac-11e7-95f4-d06fe270234b.png">

Let's fix this for the moment...

Thank you! =)

**Comment by kushpvo** [comment]
Install pip first.
`sudo easy_install pip`

**Comment by imsilenzi** [comment]
If I write `sudo easy_install pip`

<img width="490" alt="screen shot 2017-07-21 at 11 39 04" src="https://user-images.githubusercontent.com/6278152/28458210-3b8d10a8-6e09-11e7-8c41-9a3334507933.png">

**Comment by commit-master** [comment]
You need to install pip.
Download this [file](https://bootstrap.pypa.io/get-pip.py) and save it as **get-pip.py**. Then in your terminal, in the same folder where you downloaded the file type in: `python get-pip.py`.

**Comment by NewyorkDev** [comment]
Just run this to install pip.

wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py

**Comment by CheapInMadrid** [comment]
Sorry...Im really clueless and a novice,how do we run a URL...do we nave to save it on a certain type of file of format...I mean the other things which were installed and run in Scripts were apps...
