### ISSUE TITLE
Comments Error [FIXED]

### ISSUE THREAD

**Issue by TheNeObr** [InstaPy/InstaPy#4221]
Comments do not workin, how i cant fix ?
![bot](https://user-images.githubusercontent.com/6601124/55110776-8e691780-50b7-11e9-968b-d883cb19b345.PNG)

```
Failed to get comments' count!
        b"Message: javascript error: Cannot read property 'count' of undefined\n  (Session info: headless chrome=73.0.3683.86)\n  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)\n"

```

NeO

**Comment by gyrex** [comment]
What's the fix? I'm getting this error too.

**Comment by GaWr26** [comment]
Same as #4215 

A quick workaround is to comment out session.set_delimit_commenting in your script.

**Comment by TheNeObr** [comment]
> 
> 
> Same as #4215
> 
> A quick workaround is to comment out session.set_delimit_commenting in your script.

Yes i read this topic and solve the problem.
