### ISSUE TITLE
[Feature Request] Auto repost media

### ISSUE THREAD

**Issue by DemOnJR** [InstaPy/InstaPy#4222]
## Hello
I will not write much i go directly to the subject.
I am currently using this application but I think it would be helpful to implement it in instapy,

## How does it work?
This script copies posts (images, video) from other profiles, hashtags, places (set by me) and posts them to my account with a certain description, tags, copyright ... (set by me).

And as you know, more settings can be made:
1. Auto Remove after a certain time.
2. Hashtags most commonly used on instagram (but be related to posting) for each post.
3. Media owner's name (for the copyright).
4. Speed and number of posts per day.
... and more

**Comment by DemOnJR** [comment]
Is just an example btw.

**Comment by shankch** [comment]
has this been successfully implemented yet in instapy?

**Comment by amjiddader** [comment]
upvote - this is cool feature and should be considered
