### ISSUE TITLE
Unfollow loop error

### ISSUE THREAD

**Issue by tz918** [InstaPy/InstaPy#4223]
Help needed, I was getting this message: 
ERROR Unfollow loop error:  log_followed_pool() takes 6 positional arguments but 7 were given

**Comment by awesomedevelop** [comment]
It happens only with delay_followbackers

    session.unfollow_users(amount=random.randint(300, 340),InstapyFollowed=(True,"all"),style="FIFO",unfollow_after=3*24*60*60,delay_followbackers=25*24*60*60)
