### ISSUE TITLE
How do I set a maximum following number without using quota supervisor?

### ISSUE THREAD

**Issue by dpascoa** [InstaPy/InstaPy#4225]
Hello!

I would like to place a maximum number of following inside session.follow_user_followers, and when it reached it simply jumped to the unfollow or if not unfollow, simply ended the session. 

Thanks!

**Comment by mheubaum** [comment]
I don't do it in follow_user_follwers, but I disable the follow interaction for eg interact_user_followers:

`        user_following_now = my_following_count(session.browser, insta_username) #grab number of own followings        

        if user_following_now > 790: #don't follow more if already followi
            print ("\n\rINFO - Following more than 790 - Follow is not an interaction")
            session.set_do_follow(enabled=False) 
        else:
            session.set_do_follow(enabled=True, percentage=75, times=1)`

in my session and

```
# Own following count

def my_following_count(browser, username):
    browser.get('https://www.instagram.com/' + username)
    return browser.execute_script(
        "return window._sharedData.""entry_data.ProfilePage[0]."
        "graphql.user.edge_follow.count")
```

as function in my quickstart.py

**Comment by dpascoa** [comment]
@discreated 

Looks great! But here in my code, where would you place each one of the things you posted up there? I'm afraid I mess the order of things. Big thanks to you!

import random
from instapy import InstaPy
from instapy import smart_run


# LOGIN CREDENTIALS
insta_username = 'x'
insta_password = 'y'


# TARGET DATA

targets = []


# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True,
                  multi_logs=True)


# let's go! :>
with smart_run(session):
    # general settings
    
    session.set_simulation(enabled=True)`

    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=7500,
                                    max_following=3000,
                                    min_followers=25,
                                    min_following=25,
                                    min_posts=10)

    session.set_skip_users(skip_private=True,
                           skip_no_profile_pic=True,
                           skip_business=False)

    session.set_user_interact(amount=2, randomize=True, percentage=65,
                              media='Photo')

    session.set_do_like(enabled=True, percentage=70)

    session.set_do_comment(enabled=False)


    # ACTIVITIES

    # FOLLOW + INTERACTION on TARGETED accounts

    session.follow_user_followers(targets,
                                  amount=230, 
                                  randomize=True,
                                  sleep_delay=601,
                                  interact=True)

    # UNFOLLOW ACTIVITY

    session.unfollow_users(amount=500, 
                           InstapyFollowed=(True, "all"), 
                           style="FIFO", sleep_delay=601)

**Comment by mheubaum** [comment]
> ```
> import random
> from instapy import InstaPy
> from instapy import smart_run
>
>
> # LOGIN CREDENTIALS
> 
> insta_username = 'x'
> insta_password = 'y'
>
> # own following count
>def my_following_count(browser, username):
>    browser.get('https://www.instagram.com/' + username)
>    return browser.execute_script(
>        "return window._sharedData.""entry_data.ProfilePage[0]."
>        "graphql.user.edge_follow.count")
>
>
> # target data
> targets = []
> # get a session!
> 
> session = InstaPy(username=insta_username,
> password=insta_password,
> headless_browser=True,
> disable_image_load=True,
> multi_logs=True)
> # let's go! :>
> 
> with smart_run(session):
> # general settings
> 
>
> session.set_simulation(enabled=True)`
> 
> session.set_relationship_bounds(enabled=True,
>                                 potency_ratio=None,
>                                 delimit_by_numbers=True,
>                                 max_followers=7500,
>                                 max_following=3000,
>                                 min_followers=25,
>                                 min_following=25,
>                                 min_posts=10)
> 
> session.set_skip_users(skip_private=True,
>                        skip_no_profile_pic=True,
>                        skip_business=False)
> 
> session.set_user_interact(amount=2, randomize=True, percentage=65,
>                           media='Photo')
> 
> session.set_do_like(enabled=True, percentage=70)
> 
> session.set_do_comment(enabled=False)
> 
>user_following_now = my_following_count(session.browser, insta_username) #grab number of own followings   
> if user_following_now > 790: #don't follow more if already followi
>        print ("\n\rINFO - Following more than 790 - Follow is not an interaction")
>        session.set_do_follow(enabled=False) 
>    else:
>        session.set_do_follow(enabled=True, percentage=75, times=1)
> 
> # ACTIVITIES
> 
> # FOLLOW + INTERACTION on TARGETED accounts
> session.interact_user_followers(targets,
>                               amount=230, 
>                               randomize=True,
>                               sleep_delay=601,
>                               interact=True)
> 
> # UNFOLLOW ACTIVITY
> 
> session.unfollow_users(amount=500, 
>                        InstapyFollowed=(True, "all"), 
>                        style="FIFO", sleep_delay=601)
> ```

I did not try it, but it should now only like the users if you are already following more than 790 users. For that I think the best is to change follow_user_followers to interact_user_followers. How do yo schedule your  script?

**Comment by dpascoa** [comment]
@discreated Thanks! I had to adjust a few things but it works.

Well... Unfortunatelly I do it manually, I turn my pc on everyday and set the bot, and then turn off automatically when it is done. How do you do it? I would really love to schedule it

**Comment by flavioaugusto08** [comment]
@dpascoa Hi, my code is like yours and I'm with the same problem. Can you post your solution?!

**Comment by dpascoa** [comment]
@flavioaugusto08 Hi! Unfortunatelly it isn't working anymore for me, the last days I couldn't look at it because I had no time. When I can, I'll try to see.
