### ISSUE TITLE
Login A/B test detected/If raising an issue... Error

### ISSUE THREAD

**Issue by siflyx** [InstaPy/InstaPy#4228]
The script logs into Instagram fine, but then it takes a while trying to create the cookie. Eventually it doesn't and gives me this:
---
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...
**********************************************************************
If raising an issue, please also upload the file located at:
C:\Users\User\AppData\Local\Temp\20190330-202630.html
**********************************************************************

INFO [2019-03-30 20:26:33] [nmnmnnnmnmnmmnnmnmmnnnmmnn]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 1.1 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-03-30 20:26:33] [nmnmnnnmnmnmmnnmnmmnnnmmnn]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

---

What should I do?

**Comment by akbarijedi** [comment]
Yep, After try to Login this message :
Issue with cookie for user ******. Creating new cookie...
Login A/B test detected! Trying another string...
???

**Comment by CharlesCCC** [comment]
Seems like you experienced the same issue as I do, I have PR the change which is pending for merge
https://github.com/timgrossmann/InstaPy/pull/4218

**Comment by siflyx** [comment]
@CharlesCCC Ok thank you! Can you please keep me updated?

**Comment by tlovestatus** [comment]
Try to visit instagram.com/challenge and verify it and done
This solved my issue

**Comment by Marzocchi666** [comment]
Hi, im having this issue, i've done this and that in the login_util.py but without success, any suggestions? ty.
