### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by kushpvo** [InstaPy/InstaPy#423]
I'm getting this error frequently. Everything else works fine.

`[82/191] Traceback (most recent call last): File "quickstart.py", line 28, in <module> session.like_by_tags(['#nyc', 'miami', 'chicago', 'losangeles'], amount=randint(minTag, maxTag)) File "/root/InstaPy/instapy/instapy.py", line 430, in like_by_tags self.like_by_followers_lower_limit) File "/root/InstaPy/instapy/like_util.py", line 176, in check_link browser.get(link) File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 248, in get self.execute(Command.GET, {'url': url}) File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute self.error_handler.check_response(response) File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.TimeoutException: Message: timeout (Session info: chrome=59.0.3071.115) (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-83-generic x86_64)`

**Comment by timgrossmann** [comment]
@kushpvo Do you have enough RAM?
Are there any zombie instances running? (ps aux)

**Comment by kushpvo** [comment]
Yes, 2GB RAM Server.
No, i checked for Zombie Instances, none running.

**Comment by jeffreylm** [comment]
How do you check for zombie instances on windows? I'm guessing starting the task manager and if it is so, what process am I looking for?

**Comment by timgrossmann** [comment]
@jeffreylm Exactly, you could start the Task Manager and check for duplicated Chrome instances. 
If you run it on a Server, you also would've to look for duplicated xvfb instances.

**Comment by ghost** [comment]
@kushpvo 
@timgrossmann 
I've had the same issue today.
Have you fixed it?
I'm using headless chrome on 2 GB RAM server, so it should be just fine

**Comment by patrickdundas** [comment]
Also had this issue today. Running 2GB RAM digital ocean droplet Ubuntu.

**Comment by william-reed** [comment]
Had the same issue. fixed it by killing all zombie instances that were running. I used
`kill $(ps aux | grep 'chrome' | awk '{print $2}')`
