### ISSUE TITLE
Can't make the sleep_delay work for likes by tag

### ISSUE THREAD

**Issue by jbathiat** [InstaPy/InstaPy#4231]
Hi ! 
I can't figure out what's missing but I'm trying to set a delay between each like but everytime I get an error because it doesn't recognize sleep_delay:

Traceback (most recent call last):
  File "quickstart.py", line 24, in <module>
    session.like_by_tags(["tag"], amount=301, sleep_delay=50)
TypeError: like_by_tags() got an unexpected keyword argument 'sleep_delay'

Thanks for your help (I had a look at similar issues before but nothing seems to help)

**Comment by highmountainwoody** [comment]
I am having the same issue 

 File "./simple.py", line 69, in <module>
    session.like_by_tags(['skiing', 'climbing'], use_smart_hashtags=True, amount=50, interact=True, sleep_delay=240)
TypeError: like_by_tags() got an unexpected keyword argument 'sleep_delay'
