### ISSUE TITLE
Image was not able to get Liked! maybe blocked ? - (I want like only last photo of a user.txt list)

### ISSUE THREAD

**Issue by fpibbs** [InstaPy/InstaPy#4232]
I built a simple script that passes a user.txt list that I want to like, the last post only.
It works well until I receive this error via message from Instapy:

INFO [2019-04-01 06:47:06] [XXX]  Location: Trasimeno Lake
INFO [2019-04-01 06:47:45] [XXX]  --> Image was not able to get Liked! maybe blocked ?
Image was not able to get Liked! maybe blocked ?

`## InstaPy configuration
import os
import time
from tempfile import gettempdir
from selenium.common.exceptions import NoSuchElementException
from instapy import InstaPy
session = InstaPy(username='myusername',
password='mypassword',
nogui=False,
headless_browser=True,
multi_logs=True,)
try:

  with open('Instapy_User_Export.txt', 'r') as text_file:
       user_list = text_file.read().split("\n")

       session.set_do_follow(enabled=False, percentage=50)
       session.set_comments(["Cool", "Super!"])
       session.set_do_comment(enabled=False, percentage=80)
       session.set_do_like(True, percentage=100)
       session.interact_by_users(user_list, amount=1)

finally:
    # end the bot session
    session.end()`

Any ideas?

**Comment by zsvendo** [comment]
Managed to solve? I'm interested in this script was looking for this.
Like a list of users

**Comment by fpibbs** [comment]
No, I'm in stuck...seems working better with Instabot, but I have to fine tune it...
