### ISSUE TITLE
follow_commenters not getting all the commenters

### ISSUE THREAD

**Issue by hw711** [InstaPy/InstaPy#4237]
## Expected Behavior
follow_commenters method should grab all the commenters in a post

## Current Behavior
Only grabs a handful of commenters, it just started happening maybe in the last week or so.  Anyone else noticing this?

## Possible Solution (optional)
I think instagram changed the structure of the comments dialog maybe?

**Comment by hw711** [comment]
There seems to be 2 types of comment dialogs on instagram right now maybe depending on your login.  The old kind and the new kind with profile picture next to commenter's name and condensed reply thread (see screenshot)
![Screen Shot 2019-04-02 at 10 09 57 AM](https://user-images.githubusercontent.com/39748721/55377716-aaddd780-552f-11e9-96a7-c1ccda4db8dc.jpg)

follow_commenters() doesn't work for the new commenter dialog

**Comment by PRlVXTE** [comment]
We really need this feature. Commenters are the best quality people

**Comment by anitato** [comment]
I also have the same problem
