### ISSUE TITLE
Export to the user list all the followers of a specific user.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#424]
I would like to get likes and follow/unfollow of all followers of a specific account in instagram.
For example I have a computer shop in Instagram and I would like to get all Intel followers to a list.

Thanks.
Sion.

**Comment by converge** [comment]
There is few interest in this feature at the moment. Please reopen it if you need.

**Comment by exnzo13** [comment]
I'm very interested of this feature
