### ISSUE TITLE
Follow someone else followers broke 

### ISSUE THREAD

**Issue by maibaumpflanzer** [InstaPy/InstaPy#4242]
Seems like this one isnt working anymore: 

session.follow_user_followers(['friend1', 'friend2', 'friend3'], amount=10, randomize=False)

It worked for 6 weeks but now the bot is shutting down instead of following someone elses followers. The bot is running when I delete this script

**Comment by mando15** [comment]
mines doing the same thing

**Comment by realsnad** [comment]
That's because dialog_address = "//body/div[2]/div/div[2]" is now an incorrect xpath in unfollow_util.get_users_through_dialog.

**Comment by mando15** [comment]
In unfollow_util.py

Temporary replace

dialog = browser.find_element_by_xpath(
        "//div[text()='Followers' or text()='Following']/../../following-sibling::div")
with

dialog = browser.find_element_by_xpath(
        "//div[contains(@class,'isgrP')]")


remember you must replace it in two  places that have #find dialog otherwise it wont work

**Comment by CharlesCCC** [comment]
@mando15 good catch, can you please PR the change, it seems like quite some people is having this issue. thank you.

**Comment by realsnad** [comment]
In my case the error was:

Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[1]"}

And I had to change from:

dialog_address = "//body/div[2]/div/div[2]"

to:

dialog_address = "//div[contains(@class,'isgrP')]"

in unfollow_util.get_users_through_dialog

In my unfollow_util.py it's line 809 (pypi instapy 0.3.4). And it works now.

**Comment by Deamoroth** [comment]
Go to unfollow_util.py on line 809 and change:

dialog_address = "//body/div[2]/div/div[2]"

 to

 dialog_address = "//body/div[3]/div/div[2]"

I just tested and it works perfectly for me

**Comment by nbgabriel** [comment]
> dialog_address = "//body/div[3]/div/div[2]"

Deamoroth, thanks! your solution works flawlessly for me.

**Comment by maibaumpflanzer** [comment]
> Go to unfollow_util.py on line 809 and change:
> 
> dialog_address = "//body/div[2]/div/div[2]"
> 
> to
> 
> dialog_address = "//body/div[3]/div/div[2]"
> 
> I just tested and it works perfectly for me

I changed it but it Isn't working for me... any suggestions?

**Comment by Hammer11** [comment]
> > Go to unfollow_util.py on line 809 and change:
> > dialog_address = "//body/div[2]/div/div[2]"
> > to
> > dialog_address = "//body/div[3]/div/div[2]"
> > I just tested and it works perfectly for me
> 
> I changed it but it Isn't working for me... any suggestions?

I changed mine the other night and still isnt working.// Help please!!!!!

**Comment by CharlesCCC** [comment]
@maibaumpflanzer @Hammer11 if you did the change, you might need manually clean up the python compiled cache file (*.pyc files).  Also, please post your log, if you still having issue, it might something different.

**Comment by schneid201** [comment]
@CharlesCCC Hey, I'm still having the same problem. What do I need to do to fix it? How to I manually Clean the python compiled cache file?

**Comment by CharlesCCC** [comment]
@schneid201 

http://www.letmegooglethat.com/?q=How+to+I+manually+Clean+the+python+compiled+cache+file
