### ISSUE TITLE
It does not work anymore  : "please also upload the file located at"

### ISSUE THREAD

**Issue by rob1p** [InstaPy/InstaPy#4244]
## Expected Behavior
Hi!
After a month of running 12 hours a day without problems, nothing works since this morning. Does anyone have any ideas?
thanks

## Current Behavior
Traceback (most recent call last):
...........................................................
INFO [2019-04-02 16:05:39] [###]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-04-02 16:05:39] [###]  Saving account progress...
INFO [2019-04-02 16:05:42] [###]  User '###' [1/12]
**********************************************************************
If raising an issue, please also upload the file located at:
/var/folders/wd/flm_v3n16mn4ps3m5ljzkwqc0000gn/T/20190402-160612.html
**********************************************************************

INFO [2019-04-02 16:06:12] [###]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING ### users & had ### FOLLOWERS
[Session lasted 1.12 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-04-02 16:06:12] [###]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooo
  File "../quickstart.py", line 96, in <module>
    session.interact_user_followers(["#####"], amount=1002)
  File "/Library/Python/2.7/site-packages/instapy/instapy.py", line 2801, in interact_user_followers
    self.logfolder)
  File "/Library/Python/2.7/site-packages/instapy/unfollow_util.py", line 1082, in get_given_user_followers
    logger, logfolder)
  File "/Library/Python/2.7/site-packages/instapy/unfollow_util.py", line 810, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.3 x86_64)

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by mrcguimaraes** [comment]
The same here.

**Comment by poloswe** [comment]
exact same problem since this morning. Was working perfectly yesterday.

**Comment by natobaye** [comment]
Same

**Comment by CharlesCCC** [comment]
duplicated issue issue check the answer from #4240

**Comment by mrcguimaraes** [comment]
@CharlesCCC I tried the solution of the issue #4240, but doesn't solve here. 

The problem continue:
"If raising an issue, please also upload the file located at:
...."

**Comment by gitpatrickhub** [comment]
@CharlesCCC Since InstaPy moved to PIP installation, I can't find the .py files to make my own updates, i.e., implement the fix posted in #4240 

I am running Instapy on RasberryPi 3. Appreciate any guidance you may have.
Thanks!

**Comment by arno1190** [comment]
@mrcguimaraes I just tried it and it worked. I had to change the code in the instapy lib in my virtualenv (~/.virtualenvs/instapy/lib/python3.6/site-packages/instapy)
@CharlesCCC doesn't it worth a pr ?

**Comment by mrcguimaraes** [comment]
@arno1190 It really worked here. My fault, sorry guys.

Thank you @CharlesCCC !

**Comment by rob1p** [comment]
@arno1190 Thanks ! Same issue than @mrcguimaraes with macOS : I don't know where are the lib files =/

**Comment by CharlesCCC** [comment]
@arno1190 It already been PR merged, should be fixed by next release.

**Comment by CharlesCCC** [comment]
@rob1p you need find where the library is installed, it shouldn't be too hard to found(Google "Mac where is pip installation folder" or something similar to that.

**Comment by rob1p** [comment]
I'm blind... 
HD > Library > Python > 2.7 > site-package > instapy

Thanks! It works!

**Comment by gitpatrickhub** [comment]
Thanks @CharlesCCC ! for anyone on Raspberry Pi: 
```
/usr/local/lib/python#.#/dist-packages/
```
