### ISSUE TITLE
Follow by list not working

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#425]
![image](https://user-images.githubusercontent.com/7851877/28494156-1c175aea-6f2f-11e7-93d9-17332709817b.png)

with the follow:
accs = ['therock','natgeo']
session.follow_by_list(accs, times=1)

**Comment by RealMakAttak** [comment]
yes there seems to be a problem here, @timgrossmann has been made aware by me before there is a bug, just waiting for a fix :) Thanks!

**Comment by hasangok** [comment]
It can be coincidence, but after surounding follow_given_user function with try/except, it started working for me.

**Comment by ato09** [comment]
@hasangok how do you do that surrounding thing? I face the same problem when trying to follow by list. Appreciate your guide.

**Comment by flothousand** [comment]
My following seems also to not work. Everything else is fine. Any updates here?

**Comment by converge** [comment]
@sionking some news about this issue ?

**Comment by converge** [comment]
No interaction for a long time. Please, reopen this issue if you need
