### ISSUE TITLE
Chromedrive inicia mas nao faz login, congela!

### ISSUE THREAD

**Issue by dedeehzinhuuh** [InstaPy/InstaPy#4252]
## Expected Behavior
Fazer login e deixar de seguir.

## Current Behavior

Ao iniciar o script Chromedriver inicializa mas congela na tela de login, Script nao realiza nenhuma ação a nao ser abrir o  chromedriver.

## InstaPy configuration

Estou usando a versão disponível do script ate a abertura desse post

INFO [2019-04-03 02:50:56] [user]  Using built in instapy-chromedriver executable (version 2.36)

DevTools listening on ws://127.0.0.1:12496/devtools/browser/33ff6e4d-57fa-430e-a812-9e4e366a4a70

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-04-03 02:51:16] [User]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by danielbeltejar** [comment]
caraho

**Comment by henrioliv** [comment]
Atualize o Chromedriver
