### ISSUE TITLE
People I follow start to decrease once the script is running

### ISSUE THREAD

**Issue by carlosmartinezmtz** [InstaPy/InstaPy#4258]
## Expected Behavior
follow users and keep them
## Current Behavior
I start to run the script and my account start to follow people, but whith the time 1 hour or less, the mount of people im following start to decrease, if I check some of the them, appear available to follow again, is this a kind of Instagram ban? my script is to smoth and im using digital ocean
## InstaPy configuration

from instapy import InstaPy
from instapy.util import smart_run

insta_username = '@@@@@'
insta_password = '&&&'

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  multi_logs=True)

# let's go! :>
with smart_run(session):
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=6000,
                                    max_following=3000,
                                    min_followers=10,
                                    min_following=10)
    session.set_skip_users(skip_private=False,
                       skip_no_profile_pic=True,
                       skip_business=False)
    session.set_simulation(enabled=True, percentage=66)
    session.set_user_interact(amount=1, randomize=True, percentage=70, media='Photo')
    # follow activity

    session.follow_user_followers(['ZZZZZ', 'XXXXX'], amount=200, randomize=True, interact=True, sleep_delay=600)
session.end()

**Comment by MontelAle** [comment]
Yeah, instgram is temporarely banning you because of your high number of actions in a small amount of time.
You should try adding a custom delay to the follow_user function inside unfollow_util.py
