### ISSUE TITLE
Deleting all pictures on ig - can this be done?

### ISSUE THREAD

**Issue by pabs24** [InstaPy/InstaPy#4262]
i am new to this and wanting to delete all my pictures  400+ 
is there anything out there already write to assist that someone has come across 
and if i am in the wrong section please point out as i said i am new to this and thank you

**Comment by CharlesCCC** [comment]
no you can't delete it through web interface.

**Comment by DemOnJR** [comment]
> 
> 
> i am new to this and wanting to delete all my pictures 400+
> is there anything out there already write to assist that someone has come across
> and if i am in the wrong section please point out as i said i am new to this and thank you

use the nextpost or others applications
