### ISSUE TITLE
Version 0.4.0 => Unfollow users function doesn't work

### ISSUE THREAD

**Issue by wawa210292** [InstaPy/InstaPy#4265]
## Expected Behavior

I set up the function like this => session.unfollow_users(amount=XX, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=6*XX*XX, sleep_delay=XX)

It's in a infinite while boucle with some other functions like follow and so on. 

Since I started to launch the bot I just increase my following and never success to unfollow even 1 user.

Does anyone have the same problem ? Please find bellow the error message

## Current Behavior

=> Failed to get following count of 'b'xxx''  ~empty list

## InstaPy configuration

Version : 0.4.0

**Comment by crowg** [comment]
similar issue. Mine Unfollows a few people then gives me a temporary block warning. I have had this problem before. i just don't know how to fix it.

**Comment by InfraRedApple** [comment]
@crowg Temporary blocks are from Instagram. You have been unfollowing/following people too quickly. The block usually lasts a couple of days. You should implement the quota supervisor.

**Comment by crowg** [comment]
> @crowg Temporary blocks are from Instagram. You have been unfollowing/following people too quickly. The block usually lasts a couple of days. You should implement the quota supervisor.

quota supervisor has been applied to my script for months now... and i could easily go unfollow people on the instagram app with no warning after i got my warning on instapy. it was an issue with an update. it has been fixed and havent had the same issue yet. but its happened to me in the past so i expect it will happen again in the future. no problems with that.
