### ISSUE TITLE
Raspberry Pi B+ ensure chromedriver is installed

### ISSUE THREAD

**Issue by furany** [InstaPy/InstaPy#4266]
## Current Behavior

```Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password, headless_browser=True, nogui=False)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 288, in __init__
    self.set_selenium_local_session()
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 342, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver/chromedriver 
```

## Possible Solution (optional)
I am getting the problem of the Chromedriver not being installed.
I followed the Guide on how to install it on a raspberry exactly as it mentioned (copied the driver to /home/pi/InstaPy/.../ and so on), 
also i already tried `headless_browser=True` and `nogui=True/False` every possible combination.

**Comment by andifds** [comment]
Which method did you used?

[Current method available on readme ](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md#install-instapy)doesn't require copying anything, just following the instructions and commands

**Comment by francescolorenzo96** [comment]
I have the exact same error, using the method with Chrome for Pi B+, everything goes fine but when i run the quickstart script i get the chromedriver issue.

**Comment by arsophan** [comment]
Same issue here. Raspberry Pi Zero W. Did all steps as recommended here: [https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md](url)

**Comment by arsophan** [comment]
@andifds
> [Current method available on readme ](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md#install-instapy)doesn't require copying anything, just following the instructions and commands

In line 10:

> cp /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver/chromedriver assets/

**Comment by furany** [comment]
> Which method did you used?
> 
> [Current method available on readme ](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md#install-instapy)doesn't require copying anything, just following the instructions and commands

Yes i followed every step there, uninstalled chromedriver, installed the one mentioned there copied it in the directory and so on but still doesn't works looks like many people here have the same problem.
it might be an raspian problem

**Comment by andifds** [comment]
Please follow this instructions. Don't know why Readme was updated again but those instructions doesn't work.

These are the one I use on my setup and by now have been working flawless.

https://github.com/timgrossmann/InstaPy/issues/4033#issuecomment-466280659

**Comment by furany** [comment]
> Please follow this instructions. Don't know why Readme was updated again but those instructions doesn't work.
> 
> These are the one I use on my setup and by now have been working flawless.
> 
> [#4033 (comment)](https://github.com/timgrossmann/InstaPy/issues/4033#issuecomment-466280659)

I will try this now and report later if it worked, thanks in advance  
Edit: I am still getting the same Error

**Comment by ghost** [comment]
I got this working yesterday. Took a bit of fiddling, but the instructions sourced above got me over the line (thank you!).

One issue I had was after uninstalling chromedriver with apt, it then wasn't available to be linked to in the script, so I had to change the path to:

`webdriver.Chrome('/home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver/chromedriver')`

Good luck!

(For completeness my full test code below)

```
import time
from selenium import webdriver

driver = webdriver.Chrome('/usr/local/lib/python3.5/dist-packages/instapy_chromedriver/chromedriver') 
driver.get('http://www.google.com/xhtml');
time.sleep(5) 
search_box = driver.find_element_by_name('q')
search_box.send_keys('ChromeDriver')
search_box.submit()
time.sleep(5)
driver.quit()
```

**Comment by furany** [comment]
> I got this working yesterday. Took a bit of fiddling, but the instructions sourced above got me over the line (thank you!).
> 
> One issue I had was after uninstalling chromedriver with apt, it then wasn't available to be linked to in the script, so I had to change the path to:
> 
> `webdriver.Chrome('/home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver/chromedriver')`
> 
> Good luck!
> 
> (For completeness my full test code below)
> 
> ```
> import time
> from selenium import webdriver
> 
> driver = webdriver.Chrome('/usr/local/lib/python3.5/dist-packages/instapy_chromedriver/chromedriver') 
> driver.get('http://www.google.com/xhtml');
> time.sleep(5) 
> search_box = driver.find_element_by_name('q')
> search_box.send_keys('ChromeDriver')
> search_box.submit()
> time.sleep(5)
> driver.quit()
> ```

Ok tried that now i am getting following Error @uilfut:
 ```
  File "quickstart.py", line 4, in <module>
    webdriver.Chrome('/usr/local/lib/python3.5/dist-packages/instapy_chromedriver/chromedriver')
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/lib/python3.5/dist-packages/instapy_chromedriver/chromedriver unexpectedly exited. Status code was: -4
 ```

**Comment by ghost** [comment]
hmm not sure... I have a spare pi I can try from scratch with original instructions - I'll try tomorrow for you and let you know.

I'd first attempted this more than a month ago, so need to do clean install for you, to comment. I haven't had that error code but others for sure. Best guess is chromedriver version / chrome version discrepancy.

**Comment by arsophan** [comment]
Any news here @uilfut ?

**Comment by ghost** [comment]
Hey @arsophan 

I just tried it on a fresh install on pi0w (slooow install) - not working, error code -4, just like @furany 

Not sure why - will keep trying and let you know if I fix this one (def working on another pi so got to be possible!)

**Comment by furany** [comment]
i also tried installing it with sudo pip3 (because it is then installed in root directory), but the same error occurs, i am also fiddeling around if i get it to work i will post it here. 
and thanks @uilfut for helping out :)

**Comment by ghost** [comment]
Hi again

I tried the same microSD card from the Pi0w in a Pi3b and my selenium test script works, so definitely some architecture issue with the Pi0w unfortunately...

I have a Pi2b here also which is in use for something else, but if helpful I can try it in that.

**Comment by arsophan** [comment]
@uilfut Do you run your Pi3b headlessly as well?

**Comment by ghost** [comment]
Yes I did. But I don't use Instpy, just Selenium. If you want me to try it on a specific test script I'd be happy to, just send it to me.

**Comment by Gabbo94** [comment]
> import time
> from selenium import webdriver
> 
> driver = webdriver.Chrome('/usr/local/lib/python3.5/dist-packages/instapy_chromedriver/chromedriver') 
> driver.get('http://www.google.com/xhtml');
> time.sleep(5) 
> search_box = driver.find_element_by_name('q')
> search_box.send_keys('ChromeDriver')
> search_box.submit()
> time.sleep(5)
> driver.quit()

where did you put this code? i don't get it

**Comment by Cerebrock** [comment]
Can't solve this issue as well, "ensure chrome driver is installed"...
Must google chrome be installed (as opposed to chromium)? It is tricky because of armhf arq

**Comment by titogarrido** [comment]
Guys please check if you have this line in your localhost:
127.0.0.1       localhost

I was getting:
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer

and it solved.

**Comment by mikediachenko** [comment]
Just remove `nogui` at all and it should work.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
