### ISSUE TITLE
Where are the files and folders

### ISSUE THREAD

**Issue by orhan-drsn** [InstaPy/InstaPy#4267]
Hi guys,
I made a clean install on my RPi and can't find the folders and files. 
I used `pip install instapy`. It created a folder named InstaPy.

But this folder is empty...
Where is quickstart.py or like_util.py??

I manually added a short quickstart.py and it works. The missing files seems to be there.
But how can I change the like_util.py for example?

**Comment by CharlesCCC** [comment]
depend on which version of python you are using. 

it might be `/usr/local/lib/python2.7/dist-packages/`

**Comment by orhan-drsn** [comment]
I'm using python3. 
Earlier it was everything in the InstaPy folder.

**Comment by CharlesCCC** [comment]
@orhan-drsn since you used pip package tool to install it, it will be put in the specific folder.

`/usr/local/lib/python3.X/dist-packages/` will be the location you should able to find Instapy

**Comment by orhan-drsn** [comment]
yes @CharlesCCC 

there is it! Thanks a lot

**Comment by d2vin** [comment]
Hello, I am currently having trouble finding any instapy files, and this method didn't solve my problem
