### ISSUE TITLE
I am Lost :/ Help please

### ISSUE THREAD

**Issue by n0sw34r** [InstaPy/InstaPy#427]
Hello
I set up new Ubuntu 14.04.5 x64 droplet with Digitalocean. Then I moved on Advanced Installation as showen here https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu.md .
Then I edited quickstart.py like this:

from instapy import InstaPy
session = InstaPy(username='myinstausername', password='myinstpass', nogui=True)
session.login()
session.unfollow_users(amount=10)
session.set_do_follow(enabled=True, percentage=10, times=2)
session.end()

Next I set cron job with path "cd /root/InstaPy && /usr/bin/python ./quickstart.py"
My InstaPy folder and python is corectly located.

Cron Log:
Jul 23 06:47:01 ubuntu14 CRON[10140]: (root) CMD (test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly ))
Jul 23 07:17:01 ubuntu14 CRON[10698]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 23 08:17:01 ubuntu14 CRON[11907]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 23 08:45:01 ubuntu14 CRON[13092]: (root) CMD (cd /root/InstaPy && /usr/bin/python ./quickstart.py)
Jul 23 08:45:01 ubuntu14 CRON[13091]: (CRON) info (No MTA installed, discarding output)
Jul 23 09:17:01 ubuntu14 CRON[13459]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 23 10:17:01 ubuntu14 CRON[14402]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 23 11:17:01 ubuntu14 CRON[15143]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 23 12:17:01 ubuntu14 CRON[15834]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 23 12:45:01 ubuntu14 CRON[16107]: (root) CMD (cd /root/InstaPy && /usr/bin/python ./quickstart.py)
Jul 23 12:45:01 ubuntu14 CRON[16106]: (CRON) info (No MTA installed, discarding output)
Jul 23 13:17:01 ubuntu14 CRON[16465]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 23 14:17:01 ubuntu14 CRON[17029]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 23 15:17:01 ubuntu14 CRON[17704]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 23 16:17:01 ubuntu14 CRON[18364]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 23 16:45:01 ubuntu14 CRON[18720]: (root) CMD (cd /root/InstaPy && /usr/bin/python ./quickstart.py)
Jul 23 16:45:01 ubuntu14 CRON[18719]: (CRON) info (No MTA installed, discarding output)
Jul 23 17:17:01 ubuntu14 CRON[19056]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 23 18:17:02 ubuntu14 CRON[19415]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

But It doesn't work :( What am I missing guys?

Thanks a lot for HELP! ;)

**Comment by mr-White** [comment]
Have you tried running the python script without a cronjob?

I found an issue with python versioning while setting this up in DigitalOcean a few minutes ago. I had to figure out the python version, then use that to install all proper dependencies 

```
pip3.5 install .
```

**Comment by n0sw34r** [comment]
I tried run with python3 quickstart.py but I got error "Wrong login data!" I have corect login data and also when I try to login to that acc after running InstaPy I got instagram message to verify myself with email code... So is it possible that script is getting same verification message?

**Comment by mr-White** [comment]
@n0sw34r fyi this script runs through a proxy. Instagram asked me if I was accessing my Instagram account from Ukraine, as it flagged it as unusual behavior.

@timgrossmann I haven't read anything in the documentation about the use of a proxy. Are you running it? To my understanding, Social Media services such as Instagram have a black list of IP's for popular web hosting services to limit bot usage. For example, DigitalOcean operates within a particular range of static IP's, so it would be easy to identify bots running on the DigitalOcean cloud. Hence, I'm glad this script is running through a proxy. 

However, it would be nice to have some kind of mention of the proxy so it doesn't surprise future developers/hobbyists.

**Comment by timgrossmann** [comment]
@mr-White Well, there is a PR about implementing a proxy, but there is none actually running... #273 
So I don't know where this is coming from

**Comment by mr-White** [comment]
@timgrossmann Strange. I'm going to have to check some logs later. 

Thank you for correcting my false assumption
