### ISSUE TITLE
join pods, how do I use it?

### ISSUE THREAD

**Issue by lizechoo** [InstaPy/InstaPy#4276]
I was wondering how to use the join_pods function? 

In the code I saw there was a section for adding a topic as a parameter, is there documentation for this?

**Comment by ishandutta2007** [comment]
Here is the documentation: https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#instapy-pods

There are few [quickstart templates](https://github.com/InstaPy/instapy-quickstart/tree/master/quickstart_templates) using it too, you can reuse them if you are not comfortable with programming.

Let me know if you face any issues.

**Comment by lizechoo** [comment]
@ishandutta2007  Hey! Thanks for the reply, I saw the documentation, but I don't understand what the function does. 

Like what happens when you do session.join_pods? 
Does it join a telegram group and like other people's photos?

**Comment by ishandutta2007** [comment]
`session.join_pods()` is all you need to do, that does everything for you.
1. It joins you to pod DB
2. It searches if you have any recent photo to share with pod members.
3. If so it uploads it to server.
4. It downloads Ids of posts of other pod members to your machine 
5. It engages with each of those posts(or sometimes a randomly selected subset depending on the volume).it likes, follows the poster as well as comments.

To answer your 2nd question, It doesn't join any external pod on instagram or facebook. All the pod members are from instapy users.

**Comment by lizechoo** [comment]
@ishandutta2007 thank you, that helped alot!!

Also for the pods, does it join a specific category? Or just a general pod.

**Comment by CharlesCCC** [comment]
@ishandutta2007  Just out of curiosity do we have a number how many user are joined the pod so far ?

**Comment by ishandutta2007** [comment]
> @ishandutta2007 thank you, that helped alot!!
> 
> Also for the pods, does it join a specific category? Or just a general pod.

In documentations there is listed available catagories, however at this initial stage we don't recomend you to chose any specifc catagory as those catagories may have very few users at this moment.

**Comment by ishandutta2007** [comment]
> @ishandutta2007 Just out of curiosity do we have a number how many user are joined the pod so far ?

@CharlesCCC Most of the old members have not updated their template yet, but we are growing by **5-10 post uploads every day** each upload coming from mostly unique user, so you can say we are growing uploaders by 5-10 per day(90% of whom are new users onboarding), plus there are few users who don't post regularly but are still using it, I haven't estimated their count yet but it fewer than the regular guys.

By end of the month I am expecting 100-200 more users to 'general' topic. Then we may have to suggest them to choose a niche.

**Comment by ishandutta2007** [comment]
@CharlesCCC I am not welcoming pod sizes of 1000 either, In such case we will most likely overshoot free tier on firebase and moreover it's coded in a way to perform optimally till 160 users. So 100-200 is the ideal number of posts per day we are looking at.

**Comment by rahatlukumich** [comment]
Can I leave the pod afterward? 

And how much engagement I will actually receive with this pod? I don't have much engagement right now and I don't want it to look suspicious if it produces spikes in comments trend.

**Comment by ishandutta2007** [comment]
> Can I leave the pod afterward?
>

What do you mean by leave? Here we don't do any kind of registration , if you run your template with `session.join_pods()` you are in the pod; next time if you modify your script and run without this line you are not in the pod, as simple as that.

> 
> And how much engagement I will actually receive with this pod? I don't have much engagement right now and I don't want it to look suspicious if it produces spikes in comments trend.

It depends on the amount of taffic at the moment. At present the `general` topic pod is running with 200+ posts and is hitting the free tier limits almost every day(probably we have lot more users than that). So by my estimate around around 60% of that so you will get aound 100-150 additional likes and a dozon or so comments provided your post happens to be those lucky 200-250 posts that somehow squeezes in the free tier limit.  To know more about Quota exceeded folllow this discussion https://github.com/timgrossmann/InstaPy/issues/4463

**Comment by rahatlukumich** [comment]
I got it, thank you.

**Comment by hugos** [comment]
The previous comments that have helped some of the users here, have been deleted, leaving no good info whatsoever.
