### ISSUE TITLE
quickstart templates

### ISSUE THREAD

**Issue by psynapse85** [InstaPy/InstaPy#4280]
Sorry, after selenium error, downloaded latest python and when i tried to get quickstart templates, cant find them

**Comment by Minnen** [comment]
The  most common and simple one thats also included in the official README.md is [this one](https://github.com/InstaPy/instapy-quickstart/blob/master/quickstart.py).

**Comment by TarekJ03** [comment]
The repo is `InstaPy/instapy-quickstart`

**Comment by ishandutta2007** [comment]
for more check [this](https://github.com/InstaPy/instapy-quickstart/tree/master/quickstart_templates) folder

**Comment by timgrossmann** [comment]
Please don't get me wrong, people... But please, at least try to read the first few sentences of the Readme :( 

---

...

## **Installation**
```elm
pip install instapy
```
**That's it! 🚀**   
If you're on Ubuntu, read the specific guide on [Installing on Ubuntu (64-Bit)](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_To_DO_Ubuntu_on_Digital_Ocean.md). If you're on a Raspberry Pi, read the [Installing on RaspberryPi](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md) guide instead.

Download a **[quickstart](https://github.com/InstaPy/instapy-quickstart)** script of your choice to your machine. It tells InstaPy how it should run, and this is the file you'll be working on when changing how InstaPy works.

- [Here is the easiest **quickstart** script you can use](https://github.com/InstaPy/instapy-quickstart/blob/master/quickstart.py)  

- [And here you can find lots of sophisticated **quickstart** templates shared by the community!](https://github.com/InstaPy/instapy-quickstart/tree/master/quickstart_templates) 

...
