### ISSUE TITLE
CRITICAL WRONG LOGIN DATA: After logging into Instagram

### ISSUE THREAD

**Issue by shailykumar** [InstaPy/InstaPy#4282]
Here there,

I am very new to python and was very impressed with the instapy process. Infact, I was so impressed that I made this my first project  to run and learn.

So, Thank you very much @timgrossmann for your help.

Now the challenge,
When I ran the project in Wndows, I could log into the Instagram account by keying in the username and password.
But then very quickly it exits with the following error:

-------------------------------------------------------------------
INFO [2019-04-08 13:58:46] [xxxx]  Using built in instapy-chromedriver executable (version 2.46)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-04-08 13:58:51] [xxxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

..........................................................
CRITICAL [2019-04-08 13:59:48] [xxxx]  Wrong login data!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2019-04-08 13:59:54] [xxxx]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 1.12 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-04-08 13:59:54] [xxxx]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo
-----------------------------------------------------------------------------------------------------

## Expected Behavior
It was expected to like based on hashtag, but it ends the session.

## Current Behavior
First logs into Instagram as I provide the username and password. Gets to the home screen and then exits.

I don't know why I can login but even then I get the Wrong Login message.

## InstaPy configuration

Please advise and help me to resolve this issue.

Regards,
Shaily

**Comment by ghost** [comment]
Go to quickstart.py, add this option into it: 
bypass_suspicious_attempt=True
Everything fix!

**Comment by nazariyv** [comment]
@huuphongnguyen this does not fix the issue

**Comment by ghost** [comment]
@nazariyv hmmm it’s working with me. Maybe let’s check it again

**Comment by nazariyv** [comment]
For me the problem was that I had to an action. So do not switch one the headless or no_gui mode straight away, do it with browser and see what action you are required to complete. Complete it, and then you should be able to login. Hope this helps.
