### ISSUE TITLE
RPI 3b+ : bot doesn't work anymore !

### ISSUE THREAD

**Issue by ar82249728** [InstaPy/InstaPy#4286]
Hello, since last week, the bot stop working with the following error :
I run the bot on a Raspberry PI 3b+. All worked fine before last week.
I update the script but nothing change.

QUESTIONS :
1. Am I the only one to get this error ?
2. Where is the problem ?

Thank you for your help !

---------------------------------------------------------------------
INFO [2019-04-08 15:43:15] [user]  Using built in instapy-chromedriver executable (version 2.36.post0)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-04-08 15:43:18] [user]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

.................................................................
INFO [2019-04-08 15:43:56] [user]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-04-08 15:43:56] [user]  Saving account progress...

_______________________________________________________________________________
INFO [2019-04-08 15:44:01] [user]  Starting to follow user `Followers`..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-04-08 15:44:01] [user]  User 'fred' [1/2]
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20190408-154434.html
**********************************************************************

INFO [2019-04-08 15:44:35] [user]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 220 users & had 5000 FOLLOWERS
[Session lasted 1.32 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-04-08 15:44:35] [user]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "quickstart.py", line 23, in <module>
    session.follow_user_followers(['fred,'gillet'], amount=1000, randomize=False, interact=False)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 3082, in follow_user_followers
    self.logfolder)
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 1019, in get_given_user_followers
    logger, logfolder)
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 747, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)

**Comment by ishandutta2007** [comment]
Can you paste your `quickstart.py` as well?

**Comment by ar82249728** [comment]
Yes, here it is the quickstart.py 👍 
-----------------------------------------
" Quickstart script for InstaPy usage "
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'username'
insta_password = 'password'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  bypass_suspicious_attempt=True)

with smart_run(session):
  " Activity flow "        
  # general settings            
  session.set_dont_include(["phoesuesr"])
  
  # activity            
  session.follow_user_followers(['fred','gilles'], amount=1000, randomize=False, interact=False)

**Comment by ar82249728** [comment]
To be more precise : the script is not able to load the follower as usual before beginning the follow session. Anyone have the same problem on his RPI ?

**Comment by tujimmy** [comment]
> To be more precise : the script is not able to load the follower as usual before beginning the follow session. Anyone have the same problem on his RPI ?

https://github.com/timgrossmann/InstaPy/pull/4245/files

**Comment by ar82249728** [comment]
@tujimmy Thanks for your reply. I will try that but I cannot find where are the INSTAPY files in RASPBIAN. The /home/pi/instapy doesn't content the file mentionned in /4245/.

So where are the files of instapy in a RPI3b+ ?

Thanks for your help ! :)

**Comment by tujimmy** [comment]
You can see the path in your error code

/usr/local/lib/python3.5/dist-packages/instapy

**Comment by ar82249728** [comment]
@tujimmy Thank you ! I searched a lot but never notice that it was written in the error message. Lesson learned ! Thks :)
