### ISSUE TITLE
Error occurred while generating a user list from the followed pool! 	b"local variable 'user' referenced before assignment"

### ISSUE THREAD

**Issue by newcodemarc** [InstaPy/InstaPy#4287]
## Expected Behavior
unfollows users which were followed by instapy but did not follow back in time
## Current Behavior
fails to do so

`INFO [2019-04-08 16:23:48] [*****]  Unfollowing the users followed by InstaPy

INFO [2019-04-08 16:23:48] [*****]  Retrieving live `Followers` data of ***** at "full" range
INFO [2019-04-08 16:27:10] [*****]  Grabbed 3919 usernames from `Followers` in 3.31 minutes
INFO [2019-04-08 16:27:10] [*****]  Stored `Followers` data at C:\Users\Marc\InstaPy\logs\*****\/relationship_data/*****/followers/08-04-2019~full~3919(6).json local file
INFO [2019-04-08 16:27:10] [*****]  Zz :[ time to take a good nap  ~sleeping 8.2 minutes
INFO [2019-04-08 16:37:05] [*****]  Yawn :] let's go!

INFO [2019-04-08 16:37:05] [*****]  Found 0 loyal followers!  ~will not unfollow them
INFO [2019-04-08 16:37:05] [*****]  Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 0

INFO [2019-04-08 16:37:05] [*****]  There are no any users available to unfollow
INFO [2019-04-08 16:37:05] [*****]  --> Total people unfollowed : 0

INFO [2019-04-08 16:37:05] [*****]  Starting to unfollow users..
ERROR [2019-04-08 16:37:05] [*****]  Error occurred while generating a user list from the followed pool!
	b"local variable 'user' referenced before assignment"
INFO [2019-04-08 16:37:08] [*****]  Unfollowing the users followed by InstaPy

INFO [2019-04-08 16:37:08] [*****]  Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 0

INFO [2019-04-08 16:37:08] [*****]  There are no any users available to unfollow
INFO [2019-04-08 16:37:08] [*****]  --> Total people unfollowed : 0
`

## InstaPy configuration
```"""
This template is written by @Nuzzo235

What does this quickstart script aim to do?
- This script is targeting followers of similar accounts and influencers.
- This is my starting point for a conservative approach: Interact with the
audience of influencers in your niche with the help of 'Target-Lists' and
'randomization'.

NOTES:
- For the ease of use most of the relevant data is retrieved in the upper part.
"""

import random
from instapy import InstaPy
from instapy.util import smart_run






# login credentials
insta_username = '*****'
insta_password = '******'

# restriction data
dont_likes = ["sex", "car", "football", "awesome"]
ignore_users = ['angtor23_']

""" Prevent commenting on and unfollowing your good friends (the images will 
still be liked)...
"""
friends = ['helenabeatz', 'lostleblanc', 'alina_shalin', 'sashaferrer1', 'franksay', 'camillamilja', 'labengale', 'theblondeabroad',
           'hbgoodie', 'doyoutravel', 'jaloulangeree', 'backpackwithme', 'backpackersglobe', 'sheisnotlost', 'elsas_wholesomelife',
           'hannahwhiteleyofficial', 'moonawhyte', 'annabelvw', 'colleenjcarroll', 'mikaili_sol', 'erubes1', 'bohobeautifullife',
           'tezza', 'saltyluxe', 'mycolourfulworld_', 'life.with.three', 'lisahomsy', 'danielkordan', 'nolanomura', 'saltinourhair',
           'mariefeandjakesnow', 'flipflopwanderers', 'gipsystraveleverywhere', 'jordhammond', 'chelseakauai', 'travelustbyus',
           'your_passport', 'dianamiaus', 'passportinonehand', 'jess.wandering', 'emmett_sparling', 'maya_gypsy','goralka102', 'jasonmpeterson']

""" Prevent posts that contain...
"""
ignore_list = []

# TARGET data
""" Set similar accounts and influencers from your niche to target...
"""
targets = ['helenabeatz', 'lostleblanc', 'alina_shalin', 'sashaferrer1', 'franksay', 'camillamilja', 'labengale', 'theblondeabroad',
           'hbgoodie', 'doyoutravel', 'jaloulangeree', 'backpackwithme', 'backpackersglobe', 'sheisnotlost', 'elsas_wholesomelife',
           'hannahwhiteleyofficial', 'moonawhyte', 'annabelvw', 'colleenjcarroll', 'mikaili_sol', 'erubes1', 'bohobeautifullife',
           'tezza', 'saltyluxe', 'mycolourfulworld_', 'life.with.three', 'lisahomsy', 'danielkordan', 'nolanomura', 'saltinourhair',
           'mariefeandjakesnow', 'flipflopwanderers', 'gipsystraveleverywhere', 'jordhammond', 'chelseakauai', 'travelustbyus',
           'your_passport', 'dianamiaus', 'passportinonehand', 'jess.wandering', 'emmett_sparling', 'maya_gypsy', 'goralka102']

""" Skip all business accounts, except from list given...
"""
target_business_categories = ['travel', 'vacation']

# COMMENT data
comments = ["One of the best galleries I've see all day!", "Nice shot! @{}", "We love your profile! You've got skill @{}", "Great picture. We Love it :heart_eyes: ", "@{} Love it!", "Amazing picture :heart_eyes: your pictures are really nice!",
            "@{} :heart::heart:","@{}:revolving_hearts::revolving_hearts:", "Great shot! We love your work. :heart_eyes:", " Wow, perfect shot :blush:",
            "I really enjoy your feed. Love it :heart_eyes:", "This photo is incredible, I love that place! :blue_heart: :blue_heart:", "this is the ultimate dream :purple_heart:", "love that vibe…hey!", "sending great vibes :yellow_heart: :heart: :green_heart: :blue_heart: :purple_heart:",
            "Original feed! Keep it up!", "sending good vibes :yellow_heart: :heart: :green_heart: :blue_heart: :purple_heart:",
            "Love conquers all! :raised_hands: :heart:", "I really love this picture!", "Living these vibes :thumbsup:", "This is so cute! :blush:",
            "I love the message your sending with your pics :camera: :sparkles:: thumbsup:", "Sweetest :sparkling_heart: :dizzy: :sparkles:",
            "This looks like paradise :heart:", "Fell in love with your page :sunflower: :sparkles:", "Nice :four_leaf_clover: :ok_hand:", "We like it! Keep it up!",
            "That’s pretty cool :sunglasses:", "You are such an inspiration! Love it :blush:", 
            "I love your profile! @{}", "Your feed is an inspiration :thumbsup:", "Just incredible :open_mouth:", "What camera did you use @{}?",
            "Love your posts @{}", "Looks awesome @{}", "Getting inspired by you @{}", ":raised_hands: Yes!", 
            "I can feel your passion @{} :muscle:"]


while True:
    # get a session!
    
    
    
    session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True,
                  multi_logs=True)

# let's go! :>

    with smart_run(session):
        # HEY HO LETS GO
        # general settings
        session.set_dont_include(friends)
        session.set_dont_like(dont_likes)
        session.set_ignore_if_contains(ignore_list)
        session.set_ignore_users(ignore_users)
        session.set_simulation(enabled=True)

        session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                                  peak_likes=(140, 1000),
                                   peak_comments=(30, 130),
                                    peak_follows=(70, 300),
                                     peak_unfollows=(200, 520),
                                      peak_server_calls=(None, 15000))



        session.set_relationship_bounds(enabled=True,
                                        potency_ratio=None,
                                        delimit_by_numbers=True,
                                        max_followers=2600,
                                        max_following=1560,
                                        min_followers=25,
                                        min_following=25,
                                        min_posts=10)

        session.set_skip_users(skip_private=True,
                               skip_no_profile_pic=True,
                               skip_business=False,
                               dont_skip_business_categories=[
                                   target_business_categories])

        session.set_user_interact(amount=3, randomize=True, percentage=80,
                                  media='Photo')
        session.set_do_like(enabled=True, percentage=89)
        session.set_do_comment(enabled=True, percentage=12)
        session.set_comments(comments, media='Photo')
        session.set_do_follow(enabled=True, percentage=80, times=1)

        # activities

        # FOLLOW+INTERACTION on TARGETED accounts
        """ Select users form a list of a predefined targets...
        """
        number = random.randint(5, 10)
        random_targets = targets

        if len(targets) <= number:
            random_targets = targets

        else:
            random_targets = random.sample(targets, number)

        """ Interact with the chosen targets...
        """
        session.follow_user_followers(random_targets,
                                      amount=random.randint(3, 5),
                                      randomize=True, sleep_delay=134,
                                      interact=True)

        # UNFOLLOW activity
        """ Unfollow nonfollowers after one day...
        """
        session.unfollow_users(amount=random.randint(70, 200),
                               InstapyFollowed=(True, "nonfollowers"),
                               style="FIFO",
                               unfollow_after=72 * 60 * 60, sleep_delay=300)

        """ Unfollow all users followed by InstaPy after one week to keep the 
        following-level clean...
        """
        session.unfollow_users(amount=random.randint(70, 200),
                               InstapyFollowed=(True, "all"), style="FIFO",
                               unfollow_after=168 * 60 * 60, sleep_delay=310)
        
        session.end()
        
        
```

**Comment by Minnen** [comment]
After reading your code i noticed something that caught my attention and i couldnt relate to my known read documentation about the project, i will copy your code below with what i think is triggering your issue in bold and below that the way i know to accomplish what your looking for obtained from [here](https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#unfollowing).

Your code: issue **random.randint(70, 200)**
`session.unfollow_users(amount=random.randint(70, 200), InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=72 * 60 * 60, sleep_delay=300)`

The documented unfollow nonfollowers feature after 48hs:
`session.unfollow_users(amount=94, InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=48*60*60, sleep_delay=600)`

IMO: Your issue lies in the amount you choose.

Hope this helps.

**Comment by newcodemarc** [comment]
Hi Minnen thanks for your help. I just tried it and unfortunately it did not solve the problem. I still get the same error. Also the code I posted was running all the time but since a few days, maybe after the latest update, it always had this error message.

**Comment by newcodemarc** [comment]
> After reading your code i noticed something that caught my attention and i couldnt relate to my known read documentation about the project, i will copy your code below with what i think is triggering your issue in bold and below that the way i know to accomplish what your looking for obtained from [here](https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#unfollowing).
> 
> Your code: issue **random.randint(70, 200)**
> `session.unfollow_users(amount=random.randint(70, 200), InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=72 * 60 * 60, sleep_delay=300)`
> 
> The documented unfollow nonfollowers feature after 48hs:
> `session.unfollow_users(amount=94, InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=48*60*60, sleep_delay=600)`
> 
> IMO: Your issue lies in the amount you choose.
> 
> Hope this helps.

Hi Minnen thanks for your help. I just tried it and unfortunately it did not solve the problem. I still get the same error. Also the code I posted was running all the time but since a few days, maybe after the latest update, it always had this error message.

**Comment by newcodemarc** [comment]
I found the problem which caused the error. 
InstaPy was writing in the first line of the followedPoll list two usernames in one line. This confused InstaPy when it wanted to read it.

Now it works again :)

**Comment by kev-mas** [comment]
> I found the problem which caused the error.
> InstaPy was writing in the first line of the followedPoll list two usernames in one line. This confused InstaPy when it wanted to read it.
> 
> Now it works again :)

Hey @newcodemarc how did you solve it? I'm having the same issue!

**Comment by willkwolf** [comment]
How do you solve this?, Instapy isn't unfollowing.

**Comment by JuanSpada** [comment]
> I found the problem which caused the error.
> InstaPy was writing in the first line of the followedPoll list two usernames in one line. This confused InstaPy when it wanted to read it.
> 
> Now it works again :)

How u solve this?
