### ISSUE TITLE
Amount is incorrect

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4290]
## Expected Behavior

I want to follow a amount of users, so I except the script stops after having followed this amount even if the script skips some followers.

## Current Behavior

The current behaviour is : the script counts followers even if there are skipped for any reason, so the amount of followed users is inferior to the amount choosen.

## Possible Solution (optional)

Don't make +1 in the count when a user is not followed

**Comment by flavioaugusto08** [comment]
Did you had solution? I'm needing too
