### ISSUE TITLE
Cannot comment

### ISSUE THREAD

**Issue by dlenskyi** [InstaPy/InstaPy#4291]
INFO [2019-04-09 00:14:22] [*login*]  --> Image Liked!
INFO [2019-04-09 00:14:24] [*login*]  --> Not commenting! Failed to get comments' count!
	b"Message: unknown error: Cannot read property 'count' of undefined\n  (Session info: chrome=73.0.3683.103)\n  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.15.0-47-generic x86_64)\n"

what's the problem can be here?

**Comment by dlenskyi** [comment]
I used feature 'session.set_delimit_commenting'

**Comment by GaWr26** [comment]
https://github.com/timgrossmann/InstaPy/issues/4215#issuecomment-476958276

A quick search would have found you a workaround.

**Comment by dlenskyi** [comment]
@flashguy22 I didn't find answer on my question there
