### ISSUE TITLE
like_by_locations not working

### ISSUE THREAD

**Issue by lguizi** [InstaPy/InstaPy#4292]
## Expected Behavior

I want to use follow_by_locations function but it is not working

## Current Behavior

It closes when i open the scrip, i tested the funcion with many different scripts and but the same thing happened:

[Session lasted 48.88 seconds]
INFO [2019-04-08 18:06:13] []  Session ended!
INFO [2019-04-08 18:07:09] []  Using built in instapy-chromedriver executable (version 2.46)
INFO [2019-04-08 18:07:11] []  Session started!
INFO [2019-04-08 18:07:37] []  Logged in successfully!
INFO [2019-04-08 18:07:37] []  Saving account progress...
INFO [2019-04-08 18:07:47] []  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 514 users & had 715 FOLLOWERS
[Session lasted 38.12 seconds]
INFO [2019-04-08 18:07:47] []  Session ended!

**Comment by jsib0** [comment]
Please post quickstart.py (without username and password of course)

**Comment by lguizi** [comment]
> 
> 
> Please post quickstart.py (without username and password of course)

import random
from instapy import InstaPy
from instapy.util import smart_run


insta_username = ''
insta_password = ''

dont_likes = ['']

friends = ['']

comments = ['']

like_tag_list = ['']

like_loc = ['']

ignore_list = ['']

accounts = ['']


session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

with smart_run(session):
    session.set_delimit_liking(enabled=True, max=450, min=0)
    session.set_relationship_bounds(enabled=True,
                                    max_followers=15000)

    session.set_dont_include(friends)
    session.set_dont_like(dont_likes)
    session.set_ignore_if_contains(ignore_list)

    session.set_user_interact(amount=3, randomize=True, percentage=83)
    session.set_do_follow(enabled=True, percentage=40)
    session.set_do_like(enabled=True, percentage=90)
    session.set_do_comment(enabled=True, percentage=21)
    session.set_comments(comments)

    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows","unfollows", "server_calls_h"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(100, 700),
                                 peak_comments=(25, 200),
                                 peak_follows=(48, 125),
                                 peak_unfollows=(35, 400),
                                 peak_server_calls=(None, 3000))


	
    session.like_by_locations(random.sample(like_loc, 3),
                         amount=random.randint(35, 85), interact=True)
						 
    session.like_by_tags(random.sample(like_tag_list, 1),
                         amount=random.randint(27, 45), interact=True)

    session.unfollow_users(amount=random.randint(75, 100),
                           InstapyFollowed=(True, "nonfollowers"), style="FIFO",
                           unfollow_after=4 * 60 * 60, sleep_delay=300)

    session.unfollow_users(amount=random.randint(75, 150),
                           InstapyFollowed=(True, "all"), style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=301)

**Comment by lguizi** [comment]
i found what was wrong, i was trying to use the parameter: 

`interact=True` 

on locations, this was crashing my script.
