### ISSUE TITLE
xpath issue ?

### ISSUE THREAD

**Issue by MSThedox** [InstaPy/InstaPy#4294]
## Current Behavior
I didn't use instapy for one week and now my quickstart doesn't work properly, here is the traceback

Traceback (most recent call last):
  File "C:\Users\Armaury\Documents\GitHub\InstaPy\quickstart.py", line 35, in <module>
    amount=8000, randomize=True)
  File "C:\Users\Armaury\Documents\GitHub\InstaPy\instapy\instapy.py", line 2801
, in interact_user_followers
    self.logfolder)
  File "C:\Users\Armaury\Documents\GitHub\InstaPy\instapy\unfollow_util.py", lin
e 1082, in get_given_user_followers
    logger, logfolder)
  File "C:\Users\Armaury\Documents\GitHub\InstaPy\instapy\unfollow_util.py", lin
e 810, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "C:\Users\Armaury\AppData\Local\Programs\Python\Python37-32\lib\site-pack
ages\selenium-3.141.0-py3.7.egg\selenium\webdriver\remote\webdriver.py", line 39
4, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Armaury\AppData\Local\Programs\Python\Python37-32\lib\site-pack
ages\selenium-3.141.0-py3.7.egg\selenium\webdriver\remote\webdriver.py", line 97
8, in find_element
    'value': value})['value']
  File "C:\Users\Armaury\AppData\Local\Programs\Python\Python37-32\lib\site-pack
ages\selenium-3.141.0-py3.7.egg\selenium\webdriver\remote\webdriver.py", line 32
1, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Armaury\AppData\Local\Programs\Python\Python37-32\lib\site-pack
ages\selenium-3.141.0-py3.7.egg\selenium\webdriver\remote\errorhandler.py", line
 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Una
ble to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}
  (Session info: headless chrome=73.0.3683.86)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361
e1),platform=Windows NT 6.1.7601 SP1 x86_64)

## InstaPy configuration

# get a session!
session = InstaPy(username='///', password='///', multi_logs=True,  headless_browser=True)

# let's go! :>
with smart_run(session):
    # general settings

    session.set_relationship_bounds(enabled=True,
    delimit_by_numbers=False, max_followers=12000, max_following=4500,
    min_followers=35, min_following=35)
    session.set_user_interact(amount=2, randomize=True, percentage=100,
    media='Photo')
    session.set_do_follow(enabled=True, percentage=100)
    session.set_do_like(enabled=True, percentage=100)
    session.set_comments([])
    session.set_do_comment(enabled=True, percentage=50)
    session.set_user_interact(amount=2, randomize=True, percentage=100,
    media='Photo')

    # activity

    session.interact_user_followers(['///', '///', '///'],
    amount=8000, randomize=True)
    session.follow_user_followers(['///', '///', '///'],
    amount=8000, randomize=True, interact=True)
    session.unfollow_users(amount=7500, nonFollowers=True, style="RANDOM",
    unfollow_after=42*60*60, sleep_delay=3)
    session.like_by_tags(['///'], amount=8000)

If someone could help me fix the issue I would really appreciate it !

**Comment by jomynow** [comment]
Same issue.

**Comment by InfraRedApple** [comment]
Same issue, looks like Instagram may have altered their layout.

**Comment by paulinawarachowska** [comment]
Same issue, i cant unfollow peaple

**Comment by sionking** [comment]
https://github.com/timgrossmann/InstaPy/pull/4245/files

**Comment by dare2smile** [comment]
Also getting this error, and I'm on the 0.4.1 release.

`ERROR [2019-04-08 20:13:24] [xxxxxxxxx]  Ku-ku! There is an error searching active users~    b'Message: no such element: Unable to locate element: {"method":"xpath","selector":"//h1[text()=\'Likes\']/../../following-sibling::div/div"}\n  (Session info: chrome=73.0.3683.86)\n  (Driver info: chromedriver=2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90),platform=Windows NT 10.0.17134 x86_64)\n'`

**Comment by poonasor** [comment]
same issue here, can't login as a new user

**Comment by GeoffreyPG** [comment]
I try to change : Edit unfollow_util.py (line 809)
https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py#L809

Old
dialog_address = "//body/div[3]/div/div[2]"

New
dialog_address = "//body/div[@ROLE="presentation"]/div/div[2]"

But same error
