### ISSUE TITLE
Sleep delay for interact user followers

### ISSUE THREAD

**Issue by followsmoke** [InstaPy/InstaPy#4295]
Hello everyone,

I would like to know if it is possible to add a sleeping time on the function interact_user_followers.
I have already tried to add this line sleep_delay = 600 but it does not work.

Instagram has already temporarily blocked my account twice.

Here is the script I use:

session.set_dont_include(friends)
    session.set_dont_like(dont_likes)
    session.set_ignore_if_contains(ignore_list)
    session.set_ignore_users(ignore_users)
    session.set_simulation(enabled=False)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=7500,
                                    max_following=3000,
                                    min_followers=25,
                                    min_following=25,
                                    min_posts=10)

    session.set_skip_users(skip_private=True,
                           skip_no_profile_pic=True,
                           skip_business=True,
                           dont_skip_business_categories=['art', 'Photographer'])

    session.set_user_interact(amount=1, randomize=True, percentage=95,
                              media='Photo')
    session.set_do_like(enabled=True, percentage=95)
    #session.set_do_comment(enabled=False, percentage=15)
    #session.set_comments(media='Photo')
    #session.set_do_follow(enabled=False, percentage=0, times=0)

    # activities

    # FOLLOW+INTERACTION on TARGETED accounts
    """ Select users form a list of a predefined targets...
    """
    number = random.randint(60, 63)
    random_targets = targets

    if len(targets) <= number:
        random_targets = targets

    else:
        random_targets = random.sample(targets, number)

    """ Interact with the chosen targets...
    """
    session.interact_user_followers(random_targets,
                                  amount=random.randint(100, 200),
                                  randomize=True)

thanks a lot!

**Comment by limboy95** [comment]
maybe you should make use of the quota supervisor to overcome a third time of blocking?

**Comment by followsmoke** [comment]
> maybe you should make use of the quota supervisor to overcome a third time of blocking?

Maybe! 

What would be the best setting? Knowing that I do not use the follow / unfollow function
