### ISSUE TITLE
Ku-ku! Error Searching Active Users? XPATH? I have no idea.

### ISSUE THREAD

**Issue by dare2smile** [InstaPy/InstaPy#4297]
## Expected Behavior
It continues the script after unfollowing.

## Current Behavior
The script ends after unfollowing.

## InstaPy configuration
I'm not great with code.  It's pretty standard.

This is the error I'm getting on the 0.4.1 release: 

`ERROR [2019-04-08 20:13:24] [xxxxxxxxx]  Ku-ku! There is an error searching active users~    b'Message: no such element: Unable to locate element: {"method":"xpath","selector":"//h1[text()=\'Likes\']/../../following-sibling::div/div"}\n  (Session info: chrome=73.0.3683.86)\n  (Driver info: chromedriver=2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90),platform=Windows NT 10.0.17134 x86_64)\n'`

**Comment by dare2smile** [comment]
Alternatively, if someone can teach me how to downgrade back to 3.4, assuming that still works with the other xpath issues I've noticed, I'd love that too!

**Comment by GeoffreyPG** [comment]
I try to change : Edit unfollow_util.py (line 809)
https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py#L809

Old
dialog_address = "//body/div[3]/div/div[2]"

New
dialog_address = "//body/div[@ROLE="presentation"]/div/div[2]"

But same error
