### ISSUE TITLE
Installation Issue - Chrome not installed (which is not true)

### ISSUE THREAD

**Issue by robman1992** [InstaPy/InstaPy#4299]
## Expected Behavior
"Normal" installation of instapy
## Current Behavior
When I launch installation - it installs pip, but i says chrome is not installed:

chrome not installed
you must install chrome before using InstaPy. please visit https://www.google.com/chrome/ and download the correct version for your operating system.

Thing is I have chrome installed -> I even tried putting chromedriver.exe in the same folder as instapy-quickstart-master-installation-windows
## InstaPy configuration
Just downloaded instapy-quickstart master - tried to follow this video:
https://www.youtube.com/watch?v=9DkEl2MrFQk&list=PLa4P1NPX9hthXV-wko0xyxFpbhYZFkW7o&index=11&t=40s

**Comment by Minnen** [comment]
I think the instapy installation didnt installed all the necessary components successfully.

In your case i would recommend clean reinstallation and after you run the `pip install instapy` command and the installation finishes copy the installation log to check for issues that could trigger this sort of things.

**Comment by robman1992** [comment]
@Minnen How do you do 'clean reinstallation' - how do you make sure it is properly uninstalled?:)

**Comment by thaysen13** [comment]
I have the same error anyone fixed it already?

**Comment by mareekkk** [comment]
Same issue til now. Can anyone share what they did to fix it?
