### ISSUE TITLE
Add a GitHub Pages Webpage to the project

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#43]
#### Would be nice if we had a static github pages webpage for InstaPy which tells a little about the features of the tool and has a small How-To. There also could be a part about the documentation given in the Readme.

- [x] create a basic github pages webpage
- [x] add a how to use it
- [x] add documentation to the webpage
- [x] make it pretty!

**Comment by littleswany** [comment]
Would be able to do this for the project.

**Comment by littleswany** [comment]
#63 Have created a pull request for this

**Comment by kristofdombi** [comment]
@littleswany , I would love to help you in this project as well! 
@timgrossmann , I can send you an email about myself and about my works so far. 😃

**Comment by timgrossmann** [comment]
@kristof0425 You're free to collaborate in any way possible.
Just either choose a feature issue or think about something on your own, @vlntdds and I will review it and if it works and fits, I'll merge the PR.
