### ISSUE TITLE
Says Liked but no actual likes are performed

### ISSUE THREAD

**Issue by XtraQ8** [InstaPy/InstaPy#430]
Hello,

I have this issue where the app says Liked in the shell, but when I check my liked images, none of the set images are liked. I've tried both liking by a tag and liking my own news feed.

**Comment by XtraQ8** [comment]
**_Solved:_**

Updated the chromedriver to the latest one but wasn't fixed until after a 6+ sleep.

Could be the updated driver or I just needed to wait..

**Comment by timgrossmann** [comment]
@XtraQ8 Maybe you'r account has been blocked for liking or something like that
