### ISSUE TITLE
Delay for like 

### ISSUE THREAD

**Issue by tooxiic49** [InstaPy/InstaPy#4302]
Hello, I would like to add a delay between each image like in Quickstart;
I use instapy quickstart-master
thanks

**Comment by itsvasugrover** [comment]
Well you can do it by putting this piece of code in your script...

`    session.set_action_delays(enabled=True, like=40)`

This will delay the next like by 40 seconds....

**Comment by tooxiic49** [comment]
thanks :D !!!
