### ISSUE TITLE
Feature Request: Like only photos of people that not followback you & Follow Requirements based on Bio

### ISSUE THREAD

**Issue by Tbit32** [InstaPy/InstaPy#4303]
Good afternoon.

I've been thinking about two commands, the second one has been thought by more people, to improve the bot based on my experience without the use of bot.

First, before unfollowing a profile, be able to automate that you will like to photos of that person. In this way, around 20% -30% of these users follow you later. Depending on the number of followers, if they have less than 1k, with 3 likes it is enough, from 1000 with 5 likes the odds increase (if possible, likes in some of their last 10 photos).

Second, follow profiles based on your bio. In this way, the number of value followers for your interest is increased significantly.
An example of someone who tried it is this: https://github.com/timgrossmann/InstaPy/issues/3704 or https://github.com/timgrossmann/InstaPy/issues/2333
However, that command has not been added yet.

With both commands, I think that the goal of having more followers and value, would be significantly increased.

Thank you in advance.

**Comment by papillon-unix** [comment]
> Second, follow profiles based on your bio. In this way, the number of value followers for your interest is increased significantly.
> An example of someone who tried it is this: #3704 or #2333
> However, that command has not been added yet.
> 

I agree! And need it!!
