### ISSUE TITLE
Instapy don't collect session.follow_user_followers

### ISSUE THREAD

**Issue by soullessita** [InstaPy/InstaPy#4305]
It used to work but for one entire week this function (session.follow_user_followers) doesn't work properly. I tried to reinstall instapy, the chromedriver, changed parameter but.. doesn't work.

Chrome's window normally open the user, the follower of that user but it doesn't scroll neither pick any user of the list.

After 20sec the window closes itself end the session ended (skipping the rest of the code).

• This is the screen that instapy shot on the error:
> [20190411-194906.zip](https://github.com/timgrossmann/InstaPy/files/3070167/20190411-194906.zip)

• This is the error message on CMD:
> Traceback (most recent call last):
>   File "E:\DATI\Soulless\Programmi\InstaPy-master\InstaPy-master\wsoulless_v3.py", line 42, in <module>
>     randomize=True,
>   File "E:\DATI\Soulless\Programmi\InstaPy-master\InstaPy-master\instapy\instapy.py", line 3140, in follow_user_followers
>     self.logfolder)
>   File "E:\DATI\Soulless\Programmi\InstaPy-master\InstaPy-master\instapy\unfollow_util.py", line 1081, in get_given_user_followers
>     logger, logfolder)
>   File "E:\DATI\Soulless\Programmi\InstaPy-master\InstaPy-master\instapy\unfollow_util.py", line 809, in get_users_through_dialog
>     dialog = browser.find_element_by_xpath(dialog_address)
>   File "C:\Users\Soulless\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
>     return self.find_element(by=By.XPATH, value=xpath)
>   File "C:\Users\Soulless\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
>     'value': value})['value']
>   File "C:\Users\Soulless\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\Soulless\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}
>   (Session info: chrome=73.0.3683.103)
>   (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 6.1.7600 x86_64)

• And this is the code used (I've censured mine nickname and credential):
> https://regexr.com/4c4bl

Hope you find a way :(

**Comment by soullessita** [comment]
Up :(

**Comment by davidkessler-ch** [comment]
same for me!!

**Comment by Dm1k** [comment]
Same.

**Comment by kiry32** [comment]
you solved?
if so how?

**Comment by papillon-unix** [comment]
Same, not solved

**Comment by soullessita** [comment]
I didn't solved yet, if someone find a way.. please share it :(

**Comment by adchsm** [comment]
Looks like it's related to this line `selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}`. Instagram has probably changed it's markup.

**Comment by papillon-unix** [comment]
> Looks like it's related to this line `selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}`. Instagram has probably changed it's markup.

nothing to do than wait for an Instapy update?

**Comment by cliftonhatfield** [comment]
Updating the xpath for the dialog worked for me. Sometimes it's the second div and other times it's the third div. So I used the role attribute to identify it.

Edit unfollow_util.py (line 809)
[https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py#L809](url)

Old
`dialog_address = "//body/div[3]/div/div[2]"`

New
`dialog_address = "//body/div[@role=\"presentation\"]/div/div[2]"`

**Comment by ciaciafelipe** [comment]
> Updating the xpath for the dialog worked for me. Sometimes it's the second div and other times it's the third div. So I used the role attribute to identify it.
> 
> Edit unfollow_util.py (line 809)
> [https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py#L809](url)
> 
> Old
> `dialog_address = "//body/div[3]/div/div[2]"`
> 
> New
> `dialog_address = "//body/div[@role=\"presentation\"]/div/div[2]"`

Works for me, thanks!

**Comment by papillon-unix** [comment]
it seems to work for me as well, thank you very much!

**Comment by soullessita** [comment]
Can't find the unfollow_util.py
Where is stored that file?

**Comment by ciaciafelipe** [comment]
> Can't find the unfollow_util.py
> Where is stored that file?

The file is inside this folder: InstaPy-master/instapy

**Comment by soullessita** [comment]
> > Can't find the unfollow_util.py
> > Where is stored that file?
> 
> The file is inside this folder: InstaPy-master/instapy

:( found it, changed but.. still same error:

![Cattura_nuova_inst](https://user-images.githubusercontent.com/49534364/56687099-704e0180-66cd-11e9-88d6-4f22d8cbeb9e.JPG)

**Comment by ciaciafelipe** [comment]
> > > Can't find the unfollow_util.py
> > > Where is stored that file?
> > 
> > 
> > The file is inside this folder: InstaPy-master/instapy
> 
> :( found it, changed but.. still same error:
> 
> ![Cattura_nuova_inst](https://user-images.githubusercontent.com/49534364/56687099-704e0180-66cd-11e9-88d6-4f22d8cbeb9e.JPG)

Strange, I just ran and it keeps running. Review the code again, if it does not work, update the chrome.

**Comment by soullessita** [comment]
> > > > Can't find the unfollow_util.py
> > > > Where is stored that file?
> > > 
> > > 
> > > The file is inside this folder: InstaPy-master/instapy
> > 
> > 
> > :( found it, changed but.. still same error:
> > ![Cattura_nuova_inst](https://user-images.githubusercontent.com/49534364/56687099-704e0180-66cd-11e9-88d6-4f22d8cbeb9e.JPG)
> 
> Strange, I just ran and it keeps running. Review the code again, if it does not work, update the chrome.

Deleted all InstaPy-master and recreated with the actual version.
Downloaded chromedrivers 2.46 from https://chromedriver.storage.googleapis.com/index.html?path=2.46/ and normally stored in the chromedriver folder inside python.
String on unfollow file changed as you said (check screen).

And reduced the code to only that action (check screen).

Same error...

![Cattura_nuova_inst_2](https://user-images.githubusercontent.com/49534364/56761982-a0ada280-6796-11e9-8f95-2934779b4e02.JPG)
![Cattura_nuova_inst_3](https://user-images.githubusercontent.com/49534364/56762032-c3d85200-6796-11e9-9ec1-7a01bdab8721.JPG)

**Comment by soullessita** [comment]
Nevermind <3 It worked! I wrote that string in the wrong directory (I figure out that I have 2 same instapy directory one on %appdata% and another around my users' program).

Thank you anyway for the help :3

**Comment by schneid201** [comment]
I'm still having the same problem. And my line 809 in the unfollow_util.py is not even close to what you guys are saying
