### ISSUE TITLE
Cycle through Tags and unfollow users - didn't pass `unfollow_after` keeps going up

### ISSUE THREAD

**Issue by olishingerz** [InstaPy/InstaPy#4306]
## Expected Behavior
I would like the bot to cycle through tags which it is doing by using the While True: function. This loops that particular line until it has finished liking all of the tags and then moves on to the unfollow users. However when it gets to the unfollow users, it is supposed to unfollow after 4 hours. But it seems as though the bot loops unfollowing aswell and the time keeps going up and up. If you take a look at the log here the didn't pass `unfollow_after` keeps going up from 3 to 4. Surely it's meant to go down? My code is at the bottom of this post. Any help would be so greatful.
```

INFO [2019-04-11 08:53:35] [**********]  Starting to unfollow users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-04-11 08:53:37] [**********]  Unfollowing the users followed by InstaPy

INFO [2019-04-11 08:53:37] [**********]  Retrieving fresh `Followers` data of jasminaaeats at "full" range

  50/268 [======+-----------------------------]  18%    |> Elapsed: 0.01 seconds    |> ETA: 0.07 seconds      

INFO [2019-04-11 08:53:39] [**********]  Grabbed 0 new usernames from `Followers` in 0.01 seconds  ~total of 268 usernames

INFO [2019-04-11 08:53:39] [**********]  The `Followers` data is identical with the data in previous query  ~not storing the file again

INFO [2019-04-11 08:53:39] [**********]  Zz :[ time to take a good nap  ~sleeping 0.0 seconds
INFO [2019-04-11 08:53:39] [**********]  Yawn :] let's go!

INFO [2019-04-11 08:53:39] [**********]  Found 3 loyal followers!  ~will not unfollow them
INFO [2019-04-11 08:53:39] [**********]  Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 3

INFO [2019-04-11 08:53:39] [**********]  There are no any users available to unfollow
INFO [2019-04-11 08:53:39] [**********]  --> Total people unfollowed : 0


_______________________________________________________________________
INFO [2019-04-11 08:53:39] [**********]  Starting to unfollow users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-04-11 08:53:42] [**********]  There are less users to unfollow than you have requested:  78/99  ~using available amount

INFO [2019-04-11 08:53:42] [**********]  Unfollowing the users followed by InstaPy

INFO [2019-04-11 08:53:42] [**********]  Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 6

INFO [2019-04-11 08:53:42] [**********]  There are no any users available to unfollow
INFO [2019-04-11 08:53:42] [**********]  --> Total people unfollowed : 0

LIKING PICS ........................ Removed this part


_______________________________________________________________________
INFO [2019-04-11 08:59:39] [**********]  Starting to unfollow users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-04-11 08:59:41] [**********]  Unfollowing the users followed by InstaPy

INFO [2019-04-11 08:59:41] [**********]  Retrieving fresh `Followers` data of jasminaaeats at "full" range

  50/268 [======+-----------------------------]  18%    |> Elapsed: 0.01 seconds    |> ETA: 0.07 seconds      

INFO [2019-04-11 08:59:44] [**********]  Grabbed 0 new usernames from `Followers` in 0.01 seconds  ~total of 268 usernames

INFO [2019-04-11 08:59:44] [**********]  The `Followers` data is identical with the data in previous query  ~not storing the file again

INFO [2019-04-11 08:59:44] [**********]  Zz :[ time to take a good nap  ~sleeping 0.0 seconds
INFO [2019-04-11 08:59:44] [**********]  Yawn :] let's go!

INFO [2019-04-11 08:59:44] [**********]  Found 3 loyal followers!  ~will not unfollow them
INFO [2019-04-11 08:59:44] [**********]  Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 4

INFO [2019-04-11 08:59:44] [**********]  There are no any users available to unfollow
INFO [2019-04-11 08:59:44] [**********]  --> Total people unfollowed : 0


_______________________________________________________________________
INFO [2019-04-11 08:59:44] [**********]  Starting to unfollow users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-04-11 08:59:47] [**********]  There are less users to unfollow than you have requested:  79/138  ~using available amount

INFO [2019-04-11 08:59:47] [**********]  Unfollowing the users followed by InstaPy

INFO [2019-04-11 08:59:47] [**********]  Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 7

INFO [2019-04-11 08:59:47] [**********]  There are no any users available to unfollow
INFO [2019-04-11 08:59:47] [**********]  --> Total people unfollowed : 0
```

## InstaPy configuration
import os
import time
import random

from instapy import InstaPy

from instapy import smart_run

dont_likes = ['barber', 'barbering']

like_tag_list = ['food','foodtag','foodblogger']

insta_username = '***********'
insta_password = '***********'

session = InstaPy(username=insta_username,
password=insta_password,
headless_browser=True)
#multi_logs=True)

try:
    session.login()

#with smart_run(session):
    
# settings
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=-0.50,
                                    delimit_by_numbers=True,
                                    max_followers=3000,
                                    max_following=3500,
                                    min_followers=25,
                                    min_following=25)

    # don't like if a post already has more than 150 likes
    session.set_delimit_liking(enabled=True, max=32, min=3)

    # don't comment if a post already has more than 4 comments
    session.set_delimit_commenting(enabled=False, max=4, min=0)
    session.set_dont_like(dont_likes)
    session.set_user_interact(amount=2, randomize=True, percentage=60)
    session.set_do_follow(enabled=True, percentage=15)
    session.set_do_like(enabled=True, percentage=80)

    session.set_quota_supervisor(enabled=False, sleep_after=['likes', 'comments_d', 'follows', 'unfollows', 'server_calls_h'], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(57, 400),
                                peak_follows=(3, 30))    
    

# actions
    while True:
        session.like_by_tags(like_tag_list, amount=6, interact=True)
        session.unfollow_users(amount=random.randint(75, 100),
                           InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=4 * 60 * 60, sleep_delay=600)
        session.unfollow_users(amount=random.randint(75, 150),
                           InstapyFollowed=(True, "all"), style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=501)

finally:
# end the bot session
    session.end()

**Comment by newcodemarc** [comment]
I had the same problem once. I think I solved it with duplicating and renaming the record followed pool file into the followedpool file. This worked for about a week. Now with the latest InstaPy version I get an error when it wanna read the file. Which InstaPy version are you running on ?

**Comment by olishingerz** [comment]
Version: Using built in instapy-chromedriver executable (version 2.46)
Any ideas?

**Comment by newcodemarc** [comment]
mhm no I mean the actual InstaPy version not the chromedriver.

**Comment by olishingerz** [comment]
oh sorry I had version 0.4.0 and i just installed 0.4.1. So my code looks fine? the While True: isn't causing the problem?

**Comment by newcodemarc** [comment]
Looks fine to me. I have the while True before the 
```
session = InstaPy(username=insta_username,
password=insta_password,
headless_browser=True)
#multi_logs=True)

```
 but should not make a difference

**Comment by olishingerz** [comment]
Could you explain how you fixed it before again please? I couldn't understand what you did from your previous post. Could you be a bit more specific ?

**Comment by newcodemarc** [comment]
![instapy](https://user-images.githubusercontent.com/46827392/56035781-63272f00-5d2b-11e9-994f-542d55aaa82b.JPG)

somehow instapy does not write all followers in the pool marked in yellow. So what you can do is just take the all_followed and copy/rename it to replace the pool file. 

you should find those files where instapy has it´s logs. usually in your user/InstaPy folder

**Comment by olishingerz** [comment]
Thanks for the reply. I did that but still getting the same issue. the time keeps going up not down. This is the only thing thats stopping me from being able to use my bot fully :(
