### ISSUE TITLE
Follow all users from a other user

### ISSUE THREAD

**Issue by psam25** [InstaPy/InstaPy#431]
How can I follow all users from a specific user or beter to follow all people who liked a recent media of this user?

**Comment by sionking** [comment]
I requested this as well, I might try to implement in my free time (none).

**Comment by jeffreylm** [comment]
This also something I am interested in. So I can choose an account that represents my target audience, and auto follow all there followers and auto unfollow down the line.

**Comment by timgrossmann** [comment]
#444
