### ISSUE TITLE
Not start on Raspberry pi 3 b+

### ISSUE THREAD

**Issue by matteool** [InstaPy/InstaPy#4312]
Hi, I'm on raspberry pi 3 b+
when I try to start quickstart.py it gives me this error. I think it's due to the version of chrome
in How-to_raspberry.md file i have find:

> The combination of the versions of chromium-browser and chromdriver is important. This combination is currently working 
> * Chromium 65.0.3325.181 Built on Raspbian , running on Raspbian 9.4
> * ChromeDriver 2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37) 

what command should I use to change installed versions

ERROR:
root@raspberrypi:/home/pi/InstaPy# python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/home/pi/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/pi/InstaPy/instapy/instapy.py", line 13, in <module>
    from selenium import webdriver
ImportError: No module named 'selenium'

**Comment by will-holley** [comment]
Try installing `selenium`.
