### ISSUE TITLE
Stop instapy without using CTRL+C 

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#4320]
Sometimes i would like to stop instapy and see the end log, i run my bots in a screen so  i prefer not the CTRL+C command because then screen closes directly and i cant see the end log.
Any ideas?

**Comment by jeremycjang** [comment]
The program automatically logs everything in your project folder under the "logs" folder

ctrl + C isn't a command specific to InstaPy, but is for Linux/MacOS terminal in general

**Comment by Tr1pke** [comment]
that i know, but in this case this is the only option that is available for me to shut down instapy (unless killing the screen but then i won't see the end log neither)

**Comment by Tr1pke** [comment]
haven't thought about this command:
tail -n 20 InstaPy/logs/instagramaccount/general.log
i will close this issue
