### ISSUE TITLE
Never like the same profile twice

### ISSUE THREAD

**Issue by rob1p** [InstaPy/InstaPy#4321]
Hi,
I run a loop script that likes pictures of subscribers in an account list. The script runs several times on certain profiles and likes a lot of pictures of the same person.
How to configure the script so that it never passes twice on the same account?
I configured him to like 2 or 3 photos of the account, but by passing several times on different photos, some people think I'm in love :D

Thank you.

## InstaPy configuration
Python 2.6 macOS

**Comment by meuschke** [comment]
Any updates here? Is there a way to get already liked / interacted users and then skip them?
