### ISSUE TITLE
set_user_interact doesn't work for follow_by_tags

### ISSUE THREAD

**Issue by kalebic** [InstaPy/InstaPy#4324]
## Expected Behavior
My objective is to select users based on a hashtag, like their post, follow them, and like 3 posts on their profile through the interaction feature. 

## Current Behavior
I'm able to interact with users when I use _like_by_tags_ e.g.:
```
  session.set_user_interact(amount=3,
                randomize=True,
                percentage=100)

  session.like_by_tags(["myhashtag"],
                amount=1,
                randomize=True,
                interact=True)
```
> Sessional Live Report:
	|> LIKED 4 images  |  ALREADY LIKED: 0
	|> COMMENTED on 0 images
	|> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> LIKED 0 comments
	|> REPLIED to 0 comments
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0

The above successfully selects one post by hashtag and likes three posts on that person's profile. But when I swap _like_by_tags_ with _follow_by_tags_ the interaction feature no longer works:
```
  session.set_user_interact(amount=3,
                randomize=True,
                percentage=100)

  session.follow_by_tags(["myhashtag"],
                amount=1,
                randomize=True,
                interact=True)
```
> 	|> LIKED 0 images  |  ALREADY LIKED: 0
	|> COMMENTED on 0 images
	|> FOLLOWED 1 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> LIKED 0 comments
	|> REPLIED to 0 comments
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0

Here I should be getting FOLLOWED 1 users and LIKED 3 images.

## InstaPy configuration

```
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'myusername'
insta_password = 'mypw'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

with smart_run(session):
  """ Activity flow """

  session.set_relationship_bounds(enabled=True,
                delimit_by_numbers=True,
                min_followers=100,
                min_posts=100)

  session.set_skip_users(skip_private=True,
                skip_no_profile_pic=True,
                no_profile_pic_percentage=100)

  session.set_action_delays(enabled=True, 
                like=3, 
                follow=4,
                unfollow=20,
                randomize=True, 
                random_range=(70, 140))
  
  session.set_user_interact(amount=3,
                randomize=True,
                percentage=100)

  session.follow_by_tags(["myhashtag"],
                amount=1,
                randomize=True,
                interact=True)
```

Thanks!

**Comment by hodisr** [comment]
Try to specify the media in set_user_interact,
```
session.set_user_interact(amount=3,
                randomize=True,
                percentage=100, media='Photo')
```
I could be guessing but it seems to set media as None by default and it might not interact if media type isn't specified,

**Comment by r3dh4nd5** [comment]
I have the same issue, how did you solve it?
