### ISSUE TITLE
MacOS - Could not install packages due to an EnvironmentError: [Errno 13] 

### ISSUE THREAD

**Issue by Abquhazar** [InstaPy/InstaPy#4330]
When running the install.command, i receive 2 errrors (perhaps i need to split this into 2 tickets. I'll let the code masters decide)

I am attempting to install instapy on a Mac mojave. I thought this it's a problem with my python version. My current python version is:

 -Mini:~ $ python --version
Python 2.7.10
Mini:~ $ python3 --version
Python 3.7.3

The 2 errors read:

1.) clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.

2.) Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/enum'
Consider using the `--user` option or check the permissions.

full trace below:

Python is installed
====================
Pip is installed
====================
Chrome is installed
====================
Installing InstaPy...
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting instapy
  Using cached https://files.pythonhosted.org/packages/35/c2/6cc48d95708e799eaf6c1a905b21c95c79062ea3e69a6f1b7d6fd1d09471/instapy-0.4.2-py2.py3-none-any.whl
Collecting grpcio>=1.16.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/ff/1f/edb62f53d1c0394db39d7e2f728974fad68b23b41fceaa1851294af4bbd6/grpcio-1.20.0-cp27-cp27m-macosx_10_9_x86_64.whl
Collecting idna>=2.7 (from instapy)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting protobuf>=3.6.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/6d/4d/b4ba2bb8bd7e7ef6846f295a095e07f61ce896c83786dcea48a1dd4149f5/protobuf-3.7.1-cp27-cp27m-macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting EasyProcess>=0.2.3 (from instapy)
Collecting instapy-chromedriver (from instapy)
Collecting PyVirtualDisplay>=0.2.1 (from instapy)
Collecting emoji>=0.5.1 (from instapy)
Collecting certifi>=2018.10.15 (from instapy)
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Collecting jsonschema>=2.6.0 (from instapy)
  Using cached https://files.pythonhosted.org/packages/aa/69/df679dfbdd051568b53c38ec8152a3ab6bc533434fc7ed11ab034bf5e82f/jsonschema-3.0.1-py2.py3-none-any.whl
Collecting chardet>=3.0.4 (from instapy)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting plyer>=1.3.1 (from instapy)
Collecting requests>=2.20.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting selenium>=3.141.0 (from instapy)
  Using cached https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl
Collecting future>=0.17.1 (from instapy)
Collecting regex>=2018.11.22 (from instapy)
Collecting six>=1.11.0 (from instapy)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting configparser>=3.5.0 (from instapy)
  Using cached https://files.pythonhosted.org/packages/ba/05/6c96328e92e625fc31445d24d75a2c92ef9ba34fc5b037fe69693c362a0d/configparser-3.7.4-py2.py3-none-any.whl
Collecting PyYAML>=3.13 (from instapy)
Collecting urllib3>=1.24.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting MeaningCloud-python>=1.1.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/28/c6/deb6c9d113f94ec99116ec4017b333660ce54344734d29f0cb98fdf32945/MeaningCloud_python-1.1.1-py2.py3-none-any.whl
Collecting clarifai>=2.4.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/d2/e3/5c2e868bd49db72a8a771e9c8fa66c96ef6e8fa1bc8b9de4a28c47a3e5c6/clarifai-2.6.1-py2-none-any.whl
Collecting enum34>=1.0.4; python_version < "3.4" (from grpcio>=1.16.1->instapy)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting futures>=2.2.0; python_version < "3.2" (from grpcio>=1.16.1->instapy)
  Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf>=3.6.1->instapy) (18.5)
Collecting functools32; python_version < "3" (from jsonschema>=2.6.0->instapy)
Collecting pyrsistent>=0.14.0 (from jsonschema>=2.6.0->instapy)
Collecting attrs>=17.4.0 (from jsonschema>=2.6.0->instapy)
  Using cached https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting googleapis-common-protos<2,>=1.5.0 (from clarifai>=2.4.1->instapy)
Collecting typing>=3.6 (from clarifai>=2.4.1->instapy)
  Using cached https://files.pythonhosted.org/packages/cc/3e/29f92b7aeda5b078c86d14f550bf85cff809042e3429ace7af6193c3bc9f/typing-3.6.6-py2-none-any.whl
clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.
Installing collected packages: enum34, six, futures, grpcio, idna, protobuf, EasyProcess, instapy-chromedriver, PyVirtualDisplay, emoji, certifi, functools32, pyrsistent, attrs, jsonschema, chardet, plyer, urllib3, requests, selenium, future, regex, configparser, PyYAML, MeaningCloud-python, googleapis-common-protos, typing, clarifai, instapy
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/enum'
Consider using the `--user` option or check the permissions.

====================
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
There was a problem installing InstaPy, please copy the error message and create an issue here: https://github.com/InstaPy/instapy-quickstart/issues

You can also manually install InstaPy with this guide: https://github.com/timgrossmann/InstaPy

Sorry for the inconveniences
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Abquhazar** [comment]
looks like other users have been posting about the clarifai 2.6.1  issue too

**Comment by bob4081** [comment]
I'm also getting this same error :'(

**Comment by timgrossmann** [comment]
@Abquhazar As stated in the Readme, please make sure to use Python3.
We won't support Python2 anymore.

Sorry

**Comment by Abquhazar** [comment]
Tim, 

please note above that i have 3.7 installed.

Spookys-Mini:~ spookyrobinson$ python3 --version
Python 3.7.3

for some reason it seems to be ignoring this and attempting to use python2.

**Comment by jordanjoecooper** [comment]
@Abquhazar  Did you find a workaround in the end ?

**Comment by Abquhazar** [comment]
@jordanjoecooper i coded my own selenium bot in java lmao
