### ISSUE TITLE
Restricting Likes to strict

### ISSUE THREAD

**Issue by GaWr26** [InstaPy/InstaPy#4332]
I really like the idea of restricting likes by using a blacklist. I have set up such blacklist and now many likes are skipped because some words contain elements of the blacklist. Any chance to only restrict when the full word is found and not just a part.

See this example:
--> Image not liked: b'Inappropriate! ~ contains "ass" in "b\'thecreatorcl**ass**\'"

:)

Just read the documentation and it's already implemented

**Comment by myasn1k** [comment]
Hi, I can't find this black list feature. Could you tell me where to look?
