### ISSUE TITLE
Getting blocked on likes

### ISSUE THREAD

**Issue by GaWr26** [InstaPy/InstaPy#4338]
This is something I'm struggling to get my head around. I've been browsing the issues and haven't found an answer. Maybe somebody had the same experience and can point me in the right direction.

Running Instapy on two of my accounts. The accounts have been existing for several years and one had 700 followers and the other 3000.
I started using Instapy three weeks ago. Before I used other payed services occasionally and never got a block. There I had limits like 700 likes per day and 60 per hour. All good.

I start my scripts manually in terminal and have them running 24/7 in a while loop on a raspberry pi3b at home with headless browser.

First I unfollow, then I like by tags.

After one week into Instpy with these limits I got the first like block on both accounts. I stopped for two days and reduced my limits drastically. For one week everything was fine and this morning one account had the likes block again. I use these settings:

```
session.set_skip_users(skip_private=True,
                               private_percentage=100,
                               skip_no_profile_pic=True,
                               no_profile_pic_percentage=100)
session.set_dont_like([blacklist])
session.set_do_follow(enabled=True, percentage=70, times=1)
session.set_do_comment(enabled=True, percentage=40)
session.set_comments([bla],media='Photo')
session.set_do_like(True,` percentage=70)
session.set_delimit_liking(enabled=True, max=100, min=0)
# session.set_delimit_commenting(enabled=True, max=20, min=0)
session.set_relationship_bounds(enabled=True,
                                potency_ratio=None,
                                delimit_by_numbers=True,
                                max_followers=3000,
                                max_following=2000,
                                min_followers=100,
                                min_following=50)
session.set_quota_supervisor(enabled=True,
                                sleep_after=["likes", "comments", "follows", "unfollows", "server_calls"],
                                sleepyhead=True, stochastic_flow=True,
                                notify_me=True,
                                peak_likes=(22, 300),
                                peak_comments=(10, 150),
                                peak_unfollows=(50, 500),
                                peak_follows=(50, 500),
                                peak_server_calls=(350, 5000))'
session.set_user_interact(amount=1, randomize=False, percentage=40)
```

Here's a screenshot of the activity for the last couple of days:
![Screenshot 2019-04-19 at 13 23 50](https://user-images.githubusercontent.com/1381617/56422195-852e2d80-62a6-11e9-9d65-b1b53b5327d3.png)

**Apparently I got a like block for only 185 likes!**

Any ideas on why I get the block? From what I've read I should be able to do much more likes without get into trouble.

**Comment by CharlesCCC** [comment]
I can' tell from your setting with ` limits like 700 likes per day and 60 per hour` 
How often do you run it ?

**Comment by GaWr26** [comment]
> How often do you run it ?

I have this running in a loop. So it runs 24/7. I believe the limits affect multiple runs per day and not each individual execution of the script. Or am I wrong?
Now with the new limits of 300 per day and 22 per hour it stays in these limits no matter how often the script is executed. Of course it sleeps when the limits are hit.

**Comment by CharlesCCC** [comment]
@GaWr26 Yes, it should. I'm just wondering if there is some potential bug within the `set_quota_supervisor` that might have caused your issue.  I personally didn't use `set_quota_supervisor` but with scheduled run every 2 hours and 100 likes each time. ~ so roughly 1200 likes per day, blocked a few times. but mostly stable.

**Comment by GaWr26** [comment]
@CharlesCCC I don't think it's a bug in `set_quota_supervisor` as it does stay within the limits.
I was just wondering why I get the block with _only_ 700 a day. That is a bit strange to me. I have set the limit to 300 now and will keep it running for a while and keep you updated here. Yesterday it did 308 likes which was strange as the day before it did exactly 300.
![Bildschirmfoto 2019-04-23 um 14 37 51](https://user-images.githubusercontent.com/1381617/56581504-68ab3180-65d5-11e9-9469-a3128162f225.png)

**Comment by GaWr26** [comment]
@CharlesCCC today the limit did not trigger a sleep yet. 
So maybe there's really a bug in `set_quota_supervisor`

```
session.set_quota_supervisor(enabled=True,
           sleep_after=["likes", "comments", "follows", "unfollows", "server_calls"],
           sleepyhead=True, stochastic_flow=True,
           notify_me=True,
           peak_likes=(30, 300),
           peak_comments=(10, 150),
           peak_unfollows=(50, 500),
           peak_follows=(50, 500),
           peak_server_calls=(350, 5000))
```
Limit is set to 300 daily likes and currently the account has 345 likes for today.
<img width="733" alt="Bildschirmfoto 2019-04-25 um 15 42 26" src="https://user-images.githubusercontent.com/1381617/56740323-06873380-6771-11e9-8618-06ec09ccd4d3.png">

The records in the database for today show 345 likes as you can see below:
<img width="852" alt="Bildschirmfoto 2019-04-25 um 15 47 38" src="https://user-images.githubusercontent.com/1381617/56740651-a3e26780-6771-11e9-9e71-19ef6fc85781.png">

My second account did go to sleep as expected though:
`Quota Supervisor: daily likes reached quotient!	~going to sleep 13.5 hours long 
time for InstaPy to take a big good nap :-)`

**Comment by oscarbau** [comment]
How do you get those stats?

**Comment by GaWr26** [comment]
> How do you get those stats?

https://github.com/converge/instapy-dashboard

**Comment by CharlesCCC** [comment]
@oscarbau or you can get it from the sqlite db.
