### ISSUE TITLE
Followers list to array

### ISSUE THREAD

**Issue by slinkyone** [InstaPy/InstaPy#4339]
How do i make the list of my followers to an array to pass it to session.set_dont_include() ?

my_followers = session.grab_followers(username="myusername", amount="full", live_match=True, store_locally=True)
my_followers_array = []

session.set_dont_include(my_followers_array)

The main reason why I want to do this is beacuse I dont want to spam my followers profile :D

**Comment by nobodysguilthub** [comment]
@slinkyone how did you get it?

**Comment by slinkyone** [comment]
> @slinkyone how did you get it?

with smart_run(session):
    # HEY HO LETS GO
    # general settings
    my_followers = session.grab_followers(username="my_user_name", amount="full", live_match=True, store_locally=True)
    session.set_dont_include(my_followers)
