### ISSUE TITLE
Server Freeze's

### ISSUE THREAD

**Issue by NewyorkDev** [InstaPy/InstaPy#434]
I run this script on an ubuntu server using a cron job but every like 10 hours the server freeze's cause it runs out of ram (1gb) I've tried creating scripts for Ubuntu but none have been working great.

**Comment by timgrossmann** [comment]
@NewyorkDev You could try to call `reboot` after every "session".

**Comment by converge** [comment]
I'm closing this issue because there isn't interaction for a long time.Please reopen it if you need.
