### ISSUE TITLE
Could not grab any usable comments from this post..

### ISSUE THREAD

**Issue by dlenskyi** [InstaPy/InstaPy#4349]
I tried to fix it with #4236 issue, but it doesn't work for me

here's an error I receive:

Failed to get comments' count!
	b"Message: unknown error: Cannot read property 'count' of undefined\n  (Session info: chrome=73.0.3683.103)\n  (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.15.0-47-generic x86_64)\n"
INFO [2019-04-23 12:46:43] [login]  No interaction did happen.

What should I do?

Upd: I don't have session.set_delimit_commenting in my script

**Comment by jkiehn78** [comment]
I am having the same issue.  I also have tried to fix it with #4236 as well.

Thank you for your time.

**Comment by dlenskyi** [comment]
Does anyone have suggestions?
Really annoying problem, which many users have

**Comment by jkiehn78** [comment]
I Figured it out with mine.  I was having issues because I had Python 3.5 and 3.7 installed.  I somehow installed instapy in both.   When running the script it was using 3.5 instead of 3.7 which is where I made all my adjustments to comment_util i Deleted 3.5 and ran a fresh install of 3.7.  After I still had to update the comment_util.   I hope this helps.

**Comment by dlenskyi** [comment]
@jkiehn78 
I always run instapy with python3.7

I have also installed python2.7 and python 3.5. SO I don;t think there is any problem with conflcting those versions

**Comment by jkiehn78** [comment]
I would check to see if instapy is installed in either of those.

**Comment by dlenskyi** [comment]
Still no solution :/

**Comment by dlenskyi** [comment]
Now I'm having another problem: 
"Could not grab any usable comments from this post.."

But this post had many and many comments!
