### ISSUE TITLE
Not unfollowed but removed from pool

### ISSUE THREAD

**Issue by mheubaum** [InstaPy/InstaPy#4351]
Hey Guys, 

I have to unfollow hundreds accounts by hand every few days. They are removed from the "followedPool" but are not sccessfully unfollowed. Was there a change in the unfollow button?

**Comment by anna-sunberg** [comment]
Noticed the same things. About every third person i supposedly unfollows and removes from the list is not in fact unfollowed.

**Comment by mheubaum** [comment]
Good to know that I'm not alone :D Do yo have any idea where the problem could be?

**Comment by anna-sunberg** [comment]
I'm not gonna have time to investigate this in the near future, but my solution is to periodically save all the people I'm following with `grab_following` and do an intersection of that file with the `_record_all_unfollowed.csv` log file. If someone is in both lists it means there was an attempts to unfollow them. Then I run `unfollow` with a custom list of names.

**Comment by tzeiske** [comment]
its a shadow block of instagram for too many unfollows in a row (usually more than 15 or so) If you only do like 10 and wait a while (which is the default setting I think), it shouldn't happen

**Comment by ortegafernando** [comment]
me too, and i have default settings. help, please.

**Comment by mheubaum** [comment]
So increasing the sleep delay should solve it?

**Comment by matteool** [comment]
Same problem for me. 500 account removed from the pool but not unfollowed.

**Comment by ortegafernando** [comment]
After some days without doing anything, yesterday I have restarted gain and it seems to work again. temporaly banned?
