### ISSUE TITLE
New XPath error?

### ISSUE THREAD

**Issue by peshoss** [InstaPy/InstaPy#4353]
## Expected Behavior : 
to work

## Current Behavior :
 https://gyazo.com/894d6e7e10ee7789074999f08554bd43

## Possible Solution (optional) : 
none

## InstaPy configuration : 
using the simple follow-unfollow activity template

**Comment by JMuffin** [comment]
I have the same error :/
Does anyone have a solution?

**Comment by GeoffreyPG** [comment]
Same error !

**Comment by GeoffreyPG** [comment]
I try to change : Edit unfollow_util.py (line 809)
https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py#L809

Old
dialog_address = "//body/div[3]/div/div[2]"

New
dialog_address = "//body/div[@ROLE="presentation"]/div/div[2]"

But same error
