### ISSUE TITLE
Unable to locate email or phone button, maybe bypass_suspicious_login=True isn't needed anymore.

### ISSUE THREAD

**Issue by dlenskyi** [InstaPy/InstaPy#4354]
bypass suspicious attempt with phone number and email doesn't work
I'm sure that I have two-factor authentication on my account.
after that I receive "Wrong login data" and session ends

Tried #3820, but didn't work. Looked other issues related to this topic, but there is no answer still.

any suggestions?

**Comment by CamiloB** [comment]
you need to disable two-factor authentication, this always cause error

**Comment by dlenskyi** [comment]
@CamiloB so why do we need bypass features? If they cannot afford us what we want

**Comment by CamiloB** [comment]
This features you can use it when you are running the bot on a server, normally the server are not in your region or country, so Instagram take care about you account and ask if this person was you on that case they tell you that they need to confirm that it’s you and give you, if you are running this on your pc or local raspberry or something you don’t need this

**Comment by dlenskyi** [comment]
@CamiloB i’m running my script on my pc, using proxy, so I can assume that im running it on a server
