### ISSUE TITLE
How to rename Instagram account?

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#4366]
Gentlemen - how do I rename instagram account correctly - without loosing Instapy database?

**Comment by crowg** [comment]
whose? yours or anothers? and what is the purpose of this action?

**Comment by thomaslc66** [comment]
I've renamed mine,
 
1)  Change your username on instagram
2)  Change it on you quickstart.py
3) Go in db folder and rename the *.db is linked with your hold profile with your new profile name
(i've used this line in my quickstart.py 
`Settings.database_location = "./db/instapy_{}.db".format(insta_username)`

4) Open the db with an code editor or a program that open *.db and search/replace for your old profile name/new username

5) Run it manualy for tests purpose (but everything went fine for me)

;-)

**Comment by Tachenz** [comment]
So you do need to get into the database to do that... renaming profile folder in Users/Instapy  not enough..
