### ISSUE TITLE
 Grabbed 0 usernames from 'XXXX `Followers` to do following

### ISSUE THREAD

**Issue by pietrobelluno** [InstaPy/InstaPy#4367]
Every time i run the bot i have this message, from all user i put in the follow_user_followers, the bot dont follow anyone only unfollow, have anyone a solution?

**Comment by pietrobelluno** [comment]
im with the last version available btw

**Comment by nickbokaie** [comment]
I'm also experiencing the same issue. I'm utilizing the following template:

- target_followers_of_similar_accounts_and_influencers.py

The error is is throwing is: 

> followers_link` error list index out of range

**Comment by RhaegarTargaryen55** [comment]
having the same issue with 2 different templates

**Comment by jlo-ryan** [comment]
I'm also having the same issue. The bot is therefore taking no actions.
