### ISSUE TITLE
Stuck on Cookie file not found, creating cookie...

### ISSUE THREAD

**Issue by ATizik** [InstaPy/InstaPy#4369]
## Expected Behavior
Cookie file creation or error
## Current Behavior
Last output is: Cookie file not found, creating cookie...

Nothing happens after that. Maybe I could export cookie file from desktop to my vps, but I'm not sure what's the proper process for that(except for doing whole instapy setup on desktop which i'd like to avoid)

**Comment by leviwinks** [comment]
Same thing happens for me when i run a new account

older account is fine though

**Comment by RyukiMizo** [comment]
me too
In case I extract 「with smart_run(session)」, and run 「follow_by_tags」, it stuck on other place(hashtag).

**Comment by leviwinks** [comment]
turns out i moved the quickstart file into another subfile before running the program - looks like you need to run the file in its original destination before moving it.
