### ISSUE TITLE
[Question] sleep delay for follow_by_tags

### ISSUE THREAD

**Issue by brunano21** [InstaPy/InstaPy#4374]
**Feature Request**
Hi, I have started recently to use `follow_by_tags` feature with `interact` enabled and with smart tags. However, I noticed that there is no sleep delay every X follows. Is this a missing functionality or am I missing something?
Thanks.

**Comment by Marzomarz11** [comment]
brunano21 would you be willing to share your code? I"m trying to figure out how to use the follow_by_tags

**Comment by brunano21** [comment]
@Marzomarz11 
this is how I'm using it:
```
session.set_user_interact(amount=3, randomize=True, percentage=60, media='Photo')
session.set_smart_hashtags(['tag1', 'tag2'], limit=7, sort='top', log_tags=True)
session.follow_by_tags(amount=50, skip_top_posts=False, use_smart_hashtags=True, interact=True, randomize=True)
```

**Comment by brunano21** [comment]
@timgrossmann any help with this?
