### ISSUE TITLE
Help needed to convert followers List to an Array. (to not include my followers in the session)

### ISSUE THREAD

**Issue by slinkyone** [InstaPy/InstaPy#4377]
How do i make the list of my followers to an array to pass it to session.set_dont_include() ?

my_followers = session.grab_followers(username="myusername", amount="full", live_match=True, store_locally=True)
my_followers_array = []

session.set_dont_include(my_followers_array)

The main reason why I want to do this is because I dont want to spam my followers profile :D

**Comment by mheubaum** [comment]
I think it should work just using the output of drab_followers.

my_followers = session.grab_followers(username="myusername", amount="full", live_match=True, store_locally=True)
session.set_dont_include(my_followers)
