### ISSUE TITLE
search post by two or more hashtags

### ISSUE THREAD

**Issue by alesiestu** [InstaPy/InstaPy#4378]
Hi, 

is it possible search post with two or more hashtags and put like or follow?

**Comment by someralex** [comment]
hi! 
as a variant you can use :

session.set_mandatory_words('hashtag2','#hashtag3','#hashtag4','[tag5','anyWordsYouWantHere' )  
session.like_by_tags('hashtag1')

same example with 

session.follow_by_tags('hashtag1')

**Comment by alesiestu** [comment]
thank's, i have tested and the my question is: after session.like_by_tags('hashtag1') the bot liked only image that search with session.set_mandatory_words('hashtag2','#hashtag3','#hashtag4','[tag5','anyWordsYouWantHere' )?
