### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by mynameisearl** [InstaPy/InstaPy#438]
Hello i made all the steps except the 4*, but my bot is not working.
*What i have to do in the step 4? add the line inside:
from clarifai.client import ClarifaiApi and it's ok?
once i run the GUI it starts and closes in 2 seconds, i tried to see what is saying and it appears this:
![instabot](https://user-images.githubusercontent.com/29730507/28649898-6fdac94a-7278-11e7-82e9-546c3e82ba47.png)

**Comment by timgrossmann** [comment]
@Nemixalone

**Comment by mynameisearl** [comment]
@timgrossmann Hello Tim, as i see the clarifai word in the console, can you tell me exactly what i need to do in the step 4? i tried to search in the document the line: from clarifai.client import ClarifaiApi but i haven't see it.
So i decided to insert it inside.
But the bot still don't open.

**Comment by timgrossmann** [comment]
@mynameisearl To be honest, I don't know, that's why I linked @Nemixalone , he wrote the GUI with the instructions 😉 
I use the GUI without commenting out the stuff from "step 4"

**Comment by mynameisearl** [comment]
@timgrossmann Oh, well i downloaded the repository and followed the step using windows, this downloaded the GUI too, i'm gonna try without the GUI.

**Comment by timgrossmann** [comment]
@mynameisearl For me, both works fine. Hadn't had any issues with the GUI as well as the command line...

**Comment by komad1na** [comment]
Go to **master** folder then go to **instapy** folder open **instapy.py** file with **notepad** or **notepad++** and find the line **from clarifai.client import ClarifaiApi** and delete it, save it and you will be good to go.

**Comment by mynameisearl** [comment]
@Nemixalone As i tried it's the first thing i tried and when i search for: from clarifai.client import ClarifaiApi It says not found, as if this line isn't there.

**Comment by mynameisearl** [comment]
Is it possible if you can upload the instapy.py file that you have? 
I reinstaled the whole bot, and still have the same screen that i uploaded

**Comment by komad1na** [comment]
Only this [way](https://pastebin.com/RE32prPG)

**Comment by mynameisearl** [comment]
@Nemixalone  Thanks, using that one now it works, , but i get a floating window: Chromedriver.exe - no disc telling: there's no disc in the unity E:
But it looks like the bot is working.
Will test it asap.
edit1: Follow by list not working

**Comment by komad1na** [comment]
@mynameisearl One guy fix it [this](https://github.com/Nemixalone/GUI-tool-for-InstaPy-script/issues/12) way
