### ISSUE TITLE
Multi Account Support

### ISSUE THREAD

**Issue by JTD420** [InstaPy/InstaPy#4382]
Hi,

Does InstaPy support multiple accounts? If I was to pass it through the credentials of multiple accounts how would it handle it?

Could you add support for this if not? And possibly the ability to have those accounts then follow, comment, like on specific users or media etc?

Thanks

**Comment by zaymonoid** [comment]
You can just run two instances of instaPy. You can use command line passing of user details to not copy paste your code.

**Comment by JTD420** [comment]
I was looking to control 100+ accounts from a single application. Running 100+ instances of instaPy and manually controlling each one is unfortunately unrealistic.

Thanks for your reply :)
