### ISSUE TITLE
Need help (new on Python, the bot often crash, please help me ^^)

### ISSUE THREAD

**Issue by Howning** [InstaPy/InstaPy#4384]
My code :

from instapy import InstaPy
from time import sleep
import random
from instapy import smart_run

session = InstaPy(username='', password='')

with smart_run(session):

    session.set_action_delays(enabled=True,
                              like=random.randint(20, 24),
                              comment=random.randint(20, 24),
                              follow=random.randint(20, 24),
                              unfollow=random.randint(20, 24))

    session.set_do_follow(enabled=True,
                          percentage=100,
                          times=4)

    session.set_do_like(enabled=True,
                        percentage=100)
    session.set_delimit_liking(enabled=True,
                               max=200,
                               min=40)

    session.set_skip_users(skip_private=False,
                           skip_no_profile_pic=True,
                           no_profile_pic_percentage=100)

    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=-1.5,
                                    delimit_by_numbers=True,
                                    max_followers=3000,
                                    max_following=7250,
                                    min_followers=100,
                                    min_following=150,
                                    min_posts=1,
                                    max_posts=200)

    session.set_user_interact(amount=3,
                              randomize=True,
                              percentage=100,
                              media='Photo')

    photo_comments = ['Nice shot! @{}',
                      'I love your profile! @{}',
                      'Your feed is an inspiration :thumbsup:',
                      'Just incredible :open_mouth:',
                      'What camera did you use @{}?',
                      'Love your posts @{}',
                      'Looks awesome @{}',
                      'Getting inspired by you @{}',
                      ':raised_hands: Yes!',
                      'I can feel your passion @{} :muscle:']

    session.set_do_comment(enabled=False, percentage=95)
    session.set_comments(photo_comments, media='Photo')

    for i in range(10000):
        session.follow_user_followers(['lucien.mch'],
                                      amount=400,
                                      randomize=True,
                                      sleep_delay=random.randint(180, 300))

        sleep(random.randint(1000, 1444))

        session.follow_user_following(['patricafollowgirl'],
                                      amount=400,
                                      randomize=True,
                                      sleep_delay=random.randint(180, 300))

        sleep(random.randint(1000, 1444))

        session.like_by_tags(['sport', 'music'],
                             amount=800,
                             randomize=True)

        sleep(random.randint(1000, 1444))

        session.unfollow_users(amount=500,
                               InstapyFollowed=(True, "all"),
                               style="FIFO",
                               unfollow_after=48*60*60,
                               sleep_delay=random.randint(60, 180))

        sleep(random.randint(1000, 1444))

        sleep(random.randint(7200, 10000))
    session.end()

The error I always get either for the first action (follow user followers) or for one of the other actions, the bot don't run more than 30 minutes without crashing : 

Traceback (most recent call last):
  File "C:/Users/Utilisateur/Desktop/Dev/Python/Lib/site-packages/ThomasInstagram.py", line 70, in <module>
    sleep_delay=random.randint(180, 300))
  File "C:\Users\Utilisateur\Desktop\Dev\Python\Lib\site-packages\instapy\instapy.py", line 3315, in follow_user_following
    self.logfolder)
  File "C:\Users\Utilisateur\Desktop\Dev\Python\Lib\site-packages\instapy\unfollow_util.py", line 1186, in get_given_user_following
    logger, logfolder)
  File "C:\Users\Utilisateur\Desktop\Dev\Python\Lib\site-packages\instapy\unfollow_util.py", line 810, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "C:\Users\Utilisateur\Desktop\Dev\Python\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Utilisateur\Desktop\Dev\Python\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Utilisateur\Desktop\Dev\Python\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Utilisateur\Desktop\Dev\Python\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[3]/div/div[2]"}
  (Session info: chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

If someone can help me it would be very kind ^^ I'm new here, and I already tried few of the helps gave by other issues previously posted on the forum, thank you so much (Ask me if you have more question and if you want other informations to help me ^^)

**Comment by GeoffreyPG** [comment]
Same error !
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[3]/div/div[2]"}
