### ISSUE TITLE
`followers_link` error list index out of range when headless_browser=True

### ISSUE THREAD

**Issue by xxillyap** [InstaPy/InstaPy#4385]
Hello! It's the first time I am opening an issue, please forgive my lack of knowledge on this matter. 

Really need some help with the issue I have been having for about a week now (everything worked fine and for some reason stopped working recently). 

When I am running the code with "headless_browser=True" I am getting this error:
"""
Logged in successfully!
Saving account progress...
Failed to get followers count of 'my_username'  ~empty list
Failed to get following count of 'my_username'  ~empty list
Unable to save account progress, skipping data update
User 'other_user' [1/3]
`followers_link` error list index out of range
Grabbed 0 usernames from 'other_user's `Followers` to do interaction.
"""
Same happens for all other users 

The code works fine if "headless_browser=False"

I would really appreciate any help on this matter! 

## InstaPy configuration

from instapy import InstaPy
from instapy import smart_run
import schedule
import time

### LOG IN ###
insta_username=' USERNAME '
insta_password=' PSSWORD '

def job1():
  session = InstaPy(username=insta_username,
                    password=insta_password,
                    headless_browser=True)

  with smart_run(session):

    session.set_user_interact(amount=5, randomize=False, percentage=100)
    session.set_relationship_bounds(enabled=True,
                                    #potency_ratio=1.34,
                                    delimit_by_numbers=True,
                                    max_followers=4500,
                                    max_following=800,
                                    min_followers=100,
                                    min_following=100,
                                    min_posts=10)

    session.set_do_comment(enabled=True, percentage=40)
    session.set_comments([ COMMENTS ])
    session.set_do_like(enabled=True, percentage=80)
    session.set_do_follow(enabled=True, percentage=40, times=2)
    session.interact_user_followers([ USERS ], amount=20, randomize=True)

ps. This is only a part of my code, I am using "schedule" to schedule the other parts.

**Comment by GeoffreyPG** [comment]
Same problem !

**Comment by SirCipher** [comment]
I'm having the same issue, however, as a temporary fix I have enabled the use of the Firefox (`use_firefox=True`) and installed the Gecko driver and I can now continue.

**Comment by Harosteadi** [comment]
https://github.com/timgrossmann/InstaPy/issues/4359#issuecomment-488350711

**Comment by xxillyap** [comment]
Thank you! I will give this solution a try.

**Comment by jlo-ryan** [comment]
Switching to Firefox worked for me too!

**Comment by SirCipher** [comment]
It is working for me too, however, I am getting an exception similar to this randomly: 
```
org.openqa.selenium.StaleElementReferenceException: The element reference is stale. Either the element is no longer attached to the DOM or the page has been refreshed.
```
