### ISSUE TITLE
Comment blocked by Instagram but InstaPy continues to try to comment

### ISSUE THREAD

**Issue by KullAxel** [InstaPy/InstaPy#4388]
I got unfortunately got comment blocked by Instagram ( my mistake) but the script didn't recognize it.

## Expected Behavior
The script should recognized that the comment was not posted and stop trying to comment, or at least report an issue in the logs.
## Current Behavior
The script continues to comment even though I was banned and no comment was really posted.
The logs reported 348 comments while in reality I just commented 161 times

**Comment by module17** [comment]
@KullAxel How did you realize you were banned? I am experiencing the same issue with comments as well. The script says it has commented but nothing is appearing on posts. Everything else seems to be working as expected.

**Comment by KullAxel** [comment]
You can try to do comment manually, you should see a pop-up message.

**Comment by module17** [comment]
I guess I have an older client - but I do see 'Can't post' message now when attempted to post from the mobile app.   Any idea what triggered this temporary ban? It shouldn't be frequency of comments as I was doing it pretty gently... perhaps not random enough comments? Any ideas @KullAxel ?

**Comment by KullAxel** [comment]
I'm pretty sure Instagram rates limits!!! do you have an idea of the number of comments per hour and per day? I got banned for 64 comments in one hour in a couple of years old account. I think you should never pass the 60 comments per hour. Please go in logs and check the comments x hour and x day and please report here your experience.  I'm creating an excel file with all my accounts  limits

**Comment by module17** [comment]
Interesting. There was no more than 10 comments every 90 minutes on my end. It is hard to tell exactly where it stopped actually commented based on the fact that log is saying it has commented when in fact it was unable to post.

**Comment by KullAxel** [comment]
are you sure 10 comments in 90 minutes? How old is your account?

**Comment by module17** [comment]
I am positive. However, this is a fairly new account... Started interacting five days ago.

**Comment by SeanFmcdonnell** [comment]
I'm having the same issue, it's been happening for a few months. I've posted on Discord to try to get help and the only workaround I've seen moderate success running a cronjob every 18 hours to space out the time. Commenting for me was the greatest form of engagement, now it has been lagging.

**Comment by KullAxel** [comment]
> I'm having the same issue, it's been happening for a few months. I've posted on Discord to try to get help and the only workaround I've seen moderate success running a cronjob every 18 hours to space out the time. Commenting for me was the greatest form of engagement, now it has been lagging.

Can you post your comments per hours and per days? also your account statistics?

**Comment by SeanFmcdonnell** [comment]
24 comments per hour, every 18 hours. When I check the logs the last few seem to be not showing.

**Comment by module17** [comment]
Even with only 3 comments per 120 minutes, it seems the temporary comment ban has been triggered again. This is interesting. Perhaps it has something to do with the comments themselves; those with emojis are triggering some sort of duplicate comment algorithm maybe? Any thoughts?

**Comment by rzaevtogrul** [comment]
You might get following log Warning:
WARNING [2019-05-23 15:20:50] [XXXXXX]  --> Comment Action Likely Failed!	~encountered `InvalidElementStateException` :/
