### ISSUE TITLE
Video tutorial

### ISSUE THREAD

**Issue by jeffreylm** [InstaPy/InstaPy#439]
Dear Tim,

I have been struggling with this app for some days now. I followed the steps, but there are little things that are missing for a non programmer to understand. Such as when the app starts does Chrome needs to be open, and if so does it need to be logged into the account. When you say comment out Clarifai in the instapy.py file. I opened it up, it is a behemoth of a file with many entries of that name. In your simple sentence you don't say exactly where to do this.

If you do a video tutorial, all those little gaps will have to naturally be filled in as you set it up. When I read your instructions I can clearly see it is meant for someone who clearly understands the hold setting up of Python and all that come with the chrome driver, etc.

Also there is no step by step of how to launch it from the command line. I am using the Gui, but there is something wrong. It starts the CMD then after a moment I see a flash of commands and the window just shuts. No idea whats happening, no error log that I know of to help debug, nothing.

Thanks in advance

**Comment by s6s8** [comment]
I believe this would attract extra unwanted attention to this app. And having users who know what they are doing is what makes this app what it is today.
But again, its up to the dev to decide which way he wants to go.

@jeffreylm Sorry, I don't mean to be rude at all.

**Comment by jeffreylm** [comment]
Hello Tim,
That made total sense. Didn't think of it like that. I am struggling to make it work.
Do I need to have chrome running and logged into my account when I run the script?
Greeting,
Jeffrey

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

**Comment by timgrossmann** [comment]
@jeffreylm Of course this would be a good idea, but this also takes quite some time I currently sadly don't have...
Maybe there is someone here, who could do that, would be amazing!

**Comment by timgrossmann** [comment]
@jeffreylm No, it will start an instance of chrome and log you in by itself.

**Comment by koeniig2** [comment]
i need a tutorial too

**Comment by jeffreylm** [comment]
@timgrossmann Hello,

I have been able to figure alot of stuff out since this post. Being a newbie to python it was quite a bit to take in and on reading over and over, started to see things I missed the first couple reads. It's just alot to grasp and not only remember, but also realize what it means.

**Comment by converge** [comment]
#439
