### ISSUE TITLE
Access denied to instagram

### ISSUE THREAD

**Issue by bjspi** [InstaPy/InstaPy#4396]
## Expected Behavior
I just wanted to grab a list of followers, so I used this code:

`session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)`
`myF = session.grab_followers(username="myusername", amount="full", live_match=False, store_locally=False)`

First, the webdriver opened Chrome and opened www.instagram.com/myusername which was fine, afterwards an URL like this was called:
https://www.instagram.com/graphql/query/?query_hash=37479f2xxxxxxxx4dde7facxxxxxxxxxxx6a&variables={%22id%22:%20%8217436827436%22,%20%22first%22:%2050}

And I got:
_"Access to www.instagram.com was denied 
You don't have authorization to view this page."_

## Current Behavior
"Access to www.instagram.com was denied"
Whenever I open the above mentioned link to https://www.instagram.com/graphql/query/?query_hash=37479f2xxxxxxxx4dde7facxxxxxxxxxxx6a&variables={%22id%22:%20%8217436827436%22,%20%22first%22:%2050} in Chrome browser directly, it works and returns the list of the followers.

## Possible Solution (optional)
Dunno

## InstaPy configuration
Just Python 3.7 with fresh installation of instapy:
"pip install instapy".
So I have instapy 0.4.2 installed with instapy_chromedriver. 

Any ideas?

**Comment by rosinbum** [comment]
Do you have 2 factor authentication turned on? If so you will need to turn it off. The bot uses a different cookie than your normal web browser which is probably already passed the 2FA.

**Comment by bjspi** [comment]
> Do you have 2 factor authentication turned on? If so you will need to turn it off. The bot uses a different cookie than your normal web browser which is probably already passed the 2FA.

Nope, it's turned off.
I can even login in the Chrome opened by the webdriver with username/password combo without anything else.

It's really strange....!!

**Comment by rosinbum** [comment]
try using fire fox is my other recommendation

**Comment by bjspi** [comment]
I have found the problem:
In the Chromedriver Chrome, when the graphql-Page is opened up and I click the small "lock" left of the URL in chrome, I see that no cookies are set.

I tried to replicate the same in my normal browser: I deleted ALL cookies from instagram and then opened up instagram.com/graphql/query/..... and I got the "access denied" error.

Even though Instapy opened up instagram.com mainpage before actually calling this graphql page, there were no cookies. So I went and added "session.login()" after the initialization of the session - now it works :) Because now there are cookies and especially my login cookies set :) Hope it helps anyone later. 

@timgrossmann THIS IS THE FIX HERE

**Comment by rts-global** [comment]
@bjspi thanks for this, I'm very new to all this - I got your script working but where does the followers list output to?

Update - fixed this myself, set store local to True and the script told me where to find the file. 
This is awesome thanks again @bjspi !
