### ISSUE TITLE
follow_commenters doesn't work

### ISSUE THREAD

**Issue by dlenskyi** [InstaPy/InstaPy#4399]
## Expected Behavior
Follow commenters interacts with people who comment posts
## Current Behavior
It grabs all the posts of current username, and just skips all of them:

Scrapping link:  https://www.instagram.com/p/BxFYnVsHhFU/
cant get comments
4  comments.
date of pic:  2019-05-05 14:25:51
Recent pic, continue..

 5  of max  108  ---  95  to go.

Scrapping link:  https://www.instagram.com/p/BxDYBhaHaaT/
cant get comments
13  comments.
date of pic:  2019-05-04 19:42:12
Recent pic, continue..

 6  of max  108  ---  94  to go.

Scrapping link:  https://www.instagram.com/p/BxCh4Iwn3V5/
cant get comments
13  comments.
date of pic:  2019-05-04 11:49:04
Recent pic, continue..

 7  of max  108  ---  93  to go.

Scrapping link:  https://www.instagram.com/p/BxA4YonHu7S/
cant get comments
2  comments.
date of pic:  2019-05-03 20:27:15
Recent pic, continue..

**Comment by anitato** [comment]
I have the exact same problem as well

**Comment by hosnas** [comment]
it doesnt work for me too.

**Comment by beewigs** [comment]
it doesn't work for me tooo.
