### ISSUE TITLE
Unable to get list of followers

### ISSUE THREAD

**Issue by InfraRedApple** [InstaPy/InstaPy#4402]
Trying to get a list of followers returns the error: _`followers_link` error list index out of range_

Chrome Version: Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by someralex** [comment]
Same issue. 
Try:

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

=======

headless_browser = False 

works fine.

**Comment by InfraRedApple** [comment]
This is still a persistent issue with the headless browser.

**Comment by InfraRedApple** [comment]
Anyone else having the same issue?

**Comment by InfraRedApple** [comment]
This affects Mac Chrome 74->71. I am currently using Chrome 69 and it seems to be working again.

**Comment by GoldenPolo** [comment]
Same for me... On Mac too

**Comment by InfraRedApple** [comment]
Anyone know if this is being looked into?

**Comment by alexsmedile** [comment]
`followers_link error list index out of range`

Same issue here. Headless browser solution does not help.
