### ISSUE TITLE
"We Detected an unusual login attempt"

### ISSUE THREAD

**Issue by ceribbo** [InstaPy/InstaPy#4408]
Hey eveyone, I'm having a problem with the bot running on my server that uses a proxy.
The problem is that after the login success, i got stuck because of the challenge as shown in the picture.
I tried to add `bypass_suspisious_attempt=True` but it doesn't solve the problem.
![Immagine](https://user-images.githubusercontent.com/12760497/57399132-f63f7180-71d0-11e9-8931-c63c6e5ac3bc.png)
Shouldn't it be simple to bypass this control? by just checking if the words "suspicious attempt" are present in the document?
By the way, the log after the session started and the succesfully login, when the timeout raises because a stur getting stuck on the challenge page is the following:
```
INFO [2019-05-08 20:25:50] []  Failed to get following count of 'b'stefano.draghi''  ~empty list
WARNING [2019-05-08 20:25:51] []  Unable to save account progress, skipping data update
```

**Comment by ceribbo** [comment]
Actually I have solved the problem by just moving the following code 
```
if bypass_suspicious_attempt is True:
        bypass_suspicious_login(browser, bypass_with_mobile)
```

in the login_util.py from line 270 to the line 183 before the login_state.

By the way I have also another bu to report: the `check_authorization` called in line 177 of the same file is not working correctly. I would suggest to add this simple code to the function: 
`if ("challenge" in current_url):
            return False`
in line 1354 of the util.py, in fact in this way if the current_url contains world challenge, obviously it is not logged.
Hope it helps.

**Comment by lina1101** [comment]
s
