### ISSUE TITLE
Not able to comment any post.

### ISSUE THREAD

**Issue by octavius-1** [InstaPy/InstaPy#4409]
When trying to comment on any post, this message is shown:

INFO [2019-05-08 17:11:04] [username]  --> Not commenting! Failed to get comments' count!
b'Message: TypeError: window._sharedData.entry_data.PostPage[0].graphql.shortcode_media.edge_media_to_comment is undefined\n'

Has anyone had this issue before? I'm not able to comment.

I'm using Firefox with proxy, running under instapy 0.4.2

**Comment by ishandutta2007** [comment]
I tried with both Firefox and Chrome(non headless) the issue is there with both. My logs loook like this

> 
> Not commenting! Failed to get comments' count!
> 	b'Message: TypeError: window._sharedData.entry_data.PostPage[0].graphql.shortcode_media.edge_media_to_comment is undefined\n'

**Comment by ArtwoXYZ** [comment]
I have the same issue with Chrome

**Comment by octavius-1** [comment]
Apparently it was already fixed and merged when I raised this issue, but it hasn't been published to a new pip version, @timgrossmann, Could you help with this? (Also take a look of the FIFO unfollow issue I just opened, that could be fixed in the same release version)

**Comment by dmfaria** [comment]
my log shows a javascript error when trying to comment. Is it the same error?

Not commenting! Failed to get comments' count!
	b"Message: javascript error: Cannot read property 'count' of undefined\n  (Session info: chrome=74.0.3729.131)\n  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)\n"

**Comment by timgrossmann** [comment]
@octavius-1 @dmfaria  It's still in a PR https://github.com/timgrossmann/InstaPy/pull/4425
I'm at work at the moment and can't create a new version and push it to be published.
Will do in ~1 1/2h

Sorry for the delay

**Comment by dmfaria** [comment]
@timgrossmann Is it possible that the code bellow that is inside the funcion verify_commenting is always returning empty values?
            post_desc = browser.execute_script(
                "return window._sharedData.entry_data."
                "PostPage[0].graphql.shortcode_media."
                "edge_media_to_caption.edges[0]['node']['text']"
            ).lower()
......
            first_comment = browser.execute_script(
                "return window._sharedData.entry_data."
                "PostPage[0].graphql.shortcode_media."
                "edge_media_to_comment.edges[0]['node']['text']"


It seems that this code is not running properly. I compared this code to the one inside get_tags() of like_util.py and they are different. Both codes should be used to retrieve the comments of a picture. Can you check if this difference was supposed to be there?

**Comment by timgrossmann** [comment]
Please update your instapy version and try again #4425
