### ISSUE TITLE
Invalid syntax quickstart.py

### ISSUE THREAD

**Issue by jeffreylm** [InstaPy/InstaPy#441]
Hello,

When I start quickstart from the command line in python interpreter I get the following error.

**This is what I type:**

py quickstart.py

**Error message:**

File "<stdin>", line 1
py quickstart.py

SyntaxError: invalid syntax

I am new to Python, and I have used version 3.6.2 python on windows

Here is what is in my quickstart.py ( I removed the login and password naturaly.)
I am using the InstaGUI.

```python
from instapy import InstaPy
import os
session = InstaPy(username='login', password='password')
session.login()
session.like_by_tags(['beautifulthoughts'], amount=50)

session.end()


Kind regards,
Jeffrey

**Comment by timgrossmann** [comment]
@jeffreylm When using the GUI you don't need to start the file from the command line, what is the reason you're doing this?

Did you define `py` as an alias for `python3` ? 
Please try to run the file with `python3.5 quickstart.py` and make sure that the quickstart file is in the root directory of the folder

**Comment by converge** [comment]
@jeffreylm there is no more interaction in this issue for a long time, please reopen if you need some help about it.
