### ISSUE TITLE
Might be temporarily blocked from following

### ISSUE THREAD

**Issue by alatraxx** [InstaPy/InstaPy#4413]
## Expected Behavior
Should make follow as always
## Current Behavior
Today, when i start this script, I encounter this issue. Might be temporarily blocked from following. But if i try to follow somebody from Instagram App it works.
Anybody know what is it going on?

Regards

Moris

## InstaPy configuration
`""" Quickstart script for InstaPy usage """

# imports
import random

from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

# set workspace folder at desired location (default is at your home folder)
set_workspace(path=None)

max_follow_from_list = random.randint(650, 750)

# get an InstaPy session!
session = InstaPy(username="", password="", headless_browser=True, bypass_with_mobile=True)
session.set_simulation(enabled=False)

with open('follow.txt', 'r') as inizio:
        data = inizio.read().splitlines(True)
        sezioneData = slice(60)
inizio.close()

with smart_run(session):
    """ Activity flow """

    w = open("whitelist.txt", "r")
    whitelist = w.read().splitlines()
    w.close()

    #Impostazioni che dicono al bot cosa evitare e cosa no
    session.set_skip_users(skip_private=True,
                       private_percentage=0,
                       skip_no_profile_pic=True,
                       no_profile_pic_percentage=100,
                       skip_business=False,
                       skip_non_business=False,
                       business_percentage=0,
                       )

    #Impostazioni delle quote massime che il bot raggiunge durante il giorno
    session.set_quota_supervisor(enabled=True, sleep_after=["likes_d", "follows_d", "unfollows_d", "server_calls"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(None, 700),
                              peak_follows=(None, 700),
                              peak_unfollows=(None, 600))
                              
    #Controllo che l'utente abbia certi requisiti per essere seguito 

    session.set_relationship_bounds(enabled=True,
                 potency_ratio = None,
				 delimit_by_numbers=True,
                 max_followers=5000,
                 max_following=2000,
                 min_followers=50,
                 min_following=50,
                 min_posts=10)

    #session.set_mandatory_language(enabled=True, character_set='LATIN')
    session.set_action_delays(enabled=True,
                           like=random.randint(30, 40),
                           follow=random.randint(30, 40),
    )

    #WHITELIST
    session.set_dont_include(whitelist)
	   
    session.set_user_interact(amount=3, percentage=50, randomize=True, media='Photo')

    i = 0
    #LO SLEEP DELAY FUNZIONA
    while i < 15:
        session.follow_by_list(followlist=data[sezioneData], times=1, sleep_delay=300, interact=True)
        session.set_do_like(enabled=True, percentage=90)        
        del data[sezioneData]
        i += 1
        if  i == max_follow_from_list:
            break
        elif len(data) == 0:
            print ("-----------------------HAI FINITO LA LISTA-------------------------------")
            break

with open('follow.txt', 'w') as fine:
    fine.writelines(data)
fine.close()    `

**Comment by matkg** [comment]
got the same issue

**Comment by GraduErd** [comment]
same

**Comment by pedro639** [comment]
Yes, i've already asked about the quota supervisor, but still haven't got any answer, but i know it's having some issues because it isn't wotking at all

**Comment by ericjmachado** [comment]
Same issue

**Comment by ericjmachado** [comment]
Any answers?

**Comment by oscarbau** [comment]
up

**Comment by ishandutta2007** [comment]
I think it might be related to QS issue https://github.com/timgrossmann/InstaPy/issues/4430

**Comment by jinayG** [comment]
I am getting the same problem. I have stopped the script since two weeks. But it still says action blocked when I follow somebody in the app. However, after clicking it still follows the person despite showing the error message.

I am running the script on aws.

**Comment by GILL0tine** [comment]
Still happening on my end on the raspberry pi

**Comment by wallydomingo** [comment]
Instapy is dead :(

**Comment by osura** [comment]
happening to me also

**Comment by alex-lechner** [comment]
Same here! Interestingly enough this happened to me when I upgraded from version 0.5.0 to 0.5.6

**Comment by Ericdasg** [comment]
Happening to me too :(

**Comment by Kazansky** [comment]
Same to me also since at least 2-3 weeks

**Comment by Julio-Maldonado** [comment]
My script worked for one night liking and commenting on ~200 and ~30 posts respectively, but it did not follow anybody :(

I left it running last night with 100% chance follow but no dice either. Help appreciated

**Comment by limboy95** [comment]
I found out that it happened to me as well. The weird thing is that on a second account it works fine but on my personal instagram account it throws the error.

**Comment by amacre** [comment]
That happened to me too, the only thing that worked was completely remove instapy from my pc (windows 10) y then re install , after that it started to work again , this is clearly not the way to go, because you lose your database , so it’s like a fresh start , that’s not what we’re looking for.

**Comment by davidvee7** [comment]
This is also happening to me.

**Comment by RemiHATTINGUAIS** [comment]
Happening to me as well

**Comment by dgpb** [comment]
Has anyone solved this problem?

**Comment by manuelrech** [comment]
Same issue here, no updates?
