### ISSUE TITLE
Freezes after getting link

### ISSUE THREAD

**Issue by jayyliss** [InstaPy/InstaPy#4414]
I used to run InstaPy with no problem. I haven't ran it in a few weeks and now I'm encountering an issue. After InstaPy gets the link of a post, it won't do anything after.
 Here is a screenshot. 

![Screen Shot 2019-05-09 at 2 21 12 PM](https://user-images.githubusercontent.com/40965617/57477442-aca16600-7266-11e9-8cf3-e4108a804466.jpg)

Can someone tell me how to fix this please? Thanks.

**Comment by dmfaria** [comment]
I'm also having this issue. Did you find how to solve it?

**Comment by dmfaria** [comment]
I'm running the script on windows. I realized that if I press enter on the command terminal, the script continues.

**Comment by jayyliss** [comment]
Interesting . Im running on mac but i will try it and let you know if it
works
