### ISSUE TITLE
adding proxy

### ISSUE THREAD

**Issue by mando15** [InstaPy/InstaPy#4415]
i cannot seem to be able to understand ,how do you add a proxy to your account . can some please give me a detailed break down on how one adds proxies to accounts

**Comment by mando15** [comment]
this is my script 

from instapy.proxy_extension import create_proxy_extension
from instapy import InstaPy
from instapy.util import smart_run

insta_username = 'xxxxx'
insta_password = 'xxxxx'


# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  proxy_address='123.456.789 ',
                  proxy_port=8080,
                  headless_browser=True,
                  multi_logs=True)

**Comment by mando15** [comment]
this is the result 

Traceback (most recent call last):
  File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quick starts\mealpride.py", line 25, in <module>
    with smart_run(session):
  File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\util.py", line 1676, in smart_run
    session.login()
  File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 378, in login
    self.bypass_with_mobile):
  File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\login_util.py", line 179, in login_user
    "//select[@class='hztqj']/option[text()='English']")
  File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Benson5\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//select[@class='hztqj']/option[text()='English']"}
  (Session info: headless chrome=74.0.3729.131)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

>>>

**Comment by khansaad1275** [comment]
i have same problem and please can someone help us.
my script

`""" Quickstart script for InstaPy usage """
# imports
from instapy.proxy_extension import create_proxy_extension
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = 'username
insta_password = 'passs'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                   proxy_address='170.247.173.134',
                   proxy_port=8080,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                    min_followers=45,
                                    min_following=77)

    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])

    session.set_do_comment(enabled=True, percentage=20)
    session.set_comments([ u'What an amazing shot! :heart_eyes:@{}',
                             u'What an amazing shot! :heart_eyes: @{}',
                             u'Wonderful!! :heart_eyes:@{}',
                             u'Wonderful Click!! :heart_eyes:@{}',
                             u'This is awesome!! :heart_eyes: @{}',
                             u'This is awesome!! :heart_eyes:@{}',
                             u'I really like the way you captured this. @{}',
                             u'I really like the way you captured this Picture.@{}',
                             u'Great capture!! :smiley: @{}',
                             u'Great capture!! :smiley: :thumbsup:@{}'],
                         media='Photo')

    # activity
    #session.set_user_interact(amount=2, randomize=False, percentage=80, media='Photo')
    session.like_by_locations(['216978098','835323930','215244473','213274369','234281926','1020009673','736633939','213155017','213572516','124643380','236927690','218733677','234730336','247419318','240065348','239848220','239296006','968172259982674','219224107','213601591','251013058','221659584','222025060','1012795875','245717485','267501556','235638348','251471588326781','218977767','244861271','274334438','312940437','234739075','234886012','259780921','249657710','776009094','221040727','243738945'], amount=50)
`
