### ISSUE TITLE
Invalid Like Element

### ISSUE THREAD

**Issue by GeorgeYDesign** [InstaPy/InstaPy#4420]
INFO [2019-05-12 08:19:17] [GeorgeYDesign]  --> Image was not able to get Liked! maybe blocked ?
INFO [2019-05-12 08:21:07] [GeorgeYDesign]  --> Invalid Like Element!
I keep getting this no matter what script im running
I have been using the same script for a while now and only last night it stopped working

**Comment by thomaslawn** [comment]
I also have this issue.

**Comment by chuperka-infusemedia** [comment]
Hey guys, just execute InstaPy in non-headless mode, then in the opened chrome window you will see a popup that asks to enable notifications. I've just clicked "Not Now" and then the problem has fixed. It seems that popup creates an overlay that blocks the InstaPy from clicking to page elements.
