### ISSUE TITLE
Unfollowing doesn't work {"method":"xpath","selector":"//body/div[2]/div/div[2]"}

### ISSUE THREAD

**Issue by antwerp14** [InstaPy/InstaPy#4423]
## Expected Behavior
After starting the script, it shuts down after 1 minute with this error code.
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-05-12 14:15:43] [  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

...................................................................
INFO [2019-05-12 14:16:06] []  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-05-12 14:16:06] [  Saving account progress...

________________________________________________________________________
INFO [2019-05-12 14:16:13] []  Starting to unfollow users..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-05-12 14:16:14] []  Unfollowing the users you are following
ERROR [2019-05-12 14:16:41] []  Sorry, an error occurred: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)

INFO [2019-05-12 14:16:42] []  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 617 users & had 284 FOLLOWERS
[Session lasted 1.07 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-05-12 14:16:42] [  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

## InstaPy configuration

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  disable_image_load=True)

with smart_run(session):
    """ Activity flow """
    # general settings   
    session.set_relationship_bounds(enabled=False,
                 potency_ratio=-0.1,
                  delimit_by_numbers=True,
                   max_followers=1200,
                    max_following=2000,
                     min_followers=45,
                      min_following=77)
    session.unfollow_users(amount=500, allFollowing=True, style="LIFO", unfollow_after=3*60*60, sleep_delay=601)

**Comment by antwerp14** [comment]
Using raspberrypi. Chrome has been updated and InstaPy also.

**Comment by antwerp14** [comment]
UPDATE:
When running the script;
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True)

with smart_run(session):
    """ Activity flow """
    # general settings   
    session.set_relationship_bounds(enabled=True,
                 potency_ratio=-0.1,
                  delimit_by_numbers=True,
                   max_followers=1800,
                    max_following=2000,
                     min_followers=45,
                      min_following=77)
    session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')   
    session.set_do_like(enabled=True, percentage=100)
    
    # volgers volgen en interacten
    session.follow_user_followers(['antwerp_hotspots'], amount=60, randomize=True, interact=True)


I get this error aswell:
Traceback (most recent call last):
  File "/home/pi/InstaPy/codes/antwerp.py", line 37, in <module>
    session.follow_user_followers(['antwerp_hotspots'], amount=60, randomize=True, interact=True)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 3082, in follow_user_followers
    self.logfolder)
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 1019, in get_given_user_followers
    logger, logfolder)
  File "/usr/local/lib/python3.5/dist-packages/instapy/unfollow_util.py", line 747, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)

**Comment by antwerp14** [comment]
I'm also running an other script at the same time (which starts one minute earlier). May this cause a problem?

**Comment by tanmald** [comment]
I also have this problem. Tried using the workaround of using dialog_address = "//div[@role='dialog']/div[2]" in line 809 of unfollow_util.py, but then id doesn't grab more than 4/5 users to follow/unfollow.

**Comment by DennyZen** [comment]
I had the same issue.. On windows.. Bot was running about 24 hours. Made just followings. After that it should start unfollow but i got error message insteed..
File "C:\Den\New_life\InstaPy-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Den\New_life\InstaPy-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Den\New_life\InstaPy-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Den\New_life\InstaPy-master\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[3]/div/div[2]"}
  (Session info: chrome=75.0.3770.100)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.14393 x86_64)

**Comment by DennyZen** [comment]
Who know - what's the problem?
If i start script one more time - will it unfollow guys that followed previous time?

**Comment by stevecohenfr** [comment]
Same issue for me.
I just upgraded instapy :

    sudo pip install instapy --upgrade
