### ISSUE TITLE
Once I hit the run command the bot asks for a password for Google Chrome Safe Storage

### ISSUE THREAD

**Issue by pilarfc** [InstaPy/InstaPy#4428]
I have been facing this issue for a while, once I ran the command for quickstart.py the bot asks for a password and it is not following or unfollowing anybody :c I already installed and uninstalled it and also updated it still has the same behaviour. Is somebody facing the same issue? 
<img width="521" alt="Captura de pantalla 2019-05-13 a la(s) 12 44 25" src="https://user-images.githubusercontent.com/26311371/57642410-dd421200-757c-11e9-9d54-b697fe4d15ba.png">

**Comment by ChristinaSch18** [comment]
I have the same issue!

**Comment by underclass** [comment]
+1

**Comment by earenson** [comment]
Also experiencing the same, on MacOS with a fresh InstaPy install. I did some experimenting and found that when `headless_browser` is set to `False`, everything seems to work as expected, but the issue is consistent when `True`.

**Comment by mikediachenko** [comment]
@pilarfc is this a big issue for you? Or just a big paranoidal?)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pilarfc** [comment]
> Also experiencing the same, on MacOS with a fresh InstaPy install. I did some experimenting and found that when `headless_browser` is set to `False`, everything seems to work as expected, but the issue is consistent when `True`.

Thank you, this solved the issue :)
