### ISSUE TITLE
Hi where can i find a multi account example? Or somewhere to learn how to use it.

### ISSUE THREAD

**Issue by JuanSpada** [InstaPy/InstaPy#4429]
Where can i find an example of multi account?

**Comment by ishandutta2007** [comment]
whats your issue, that way to run multiple accounts is same as way to run for single account.
Just have separate quickstart templates for each of them.

If you are concerned about them using same db in backend, then use the flag 
`		  split_db=True,`

more details here : https://github.com/timgrossmann/InstaPy/issues/4268
and https://github.com/timgrossmann/InstaPy/pull/4270
