### ISSUE TITLE
Interact with only Private Users for follow request

### ISSUE THREAD

**Issue by ajaysinghal1010** [InstaPy/InstaPy#4431]
## Current Behavior
We have the existing function to skip the Private profile for not following them. But we do not have any function where we can skip following request with the public profile and send follow request only to the user whose profile is private.

## Possible Solution (optional)
To create similar function like skip_Private  and can be named as skip_Public.

**Comment by ajaysinghal1010** [comment]
The reason for this function is that in in india mostly the genuine user have set their account as private account . In order to target my clothing brand I need to send follow request only to the private user rather then the public user, to keep my followers list clean from any junk.

Any help would be highly appreciated, am ready to do any contribution as part of bounty for this feature.

**Comment by msilin** [comment]
Hello, the easiest way to do this is to edit your util.py file in instapy module folder.
For me this file is located in /usr/local/lib/python3.7/site-packages/instapy

Change line 342 if is_private to if not is_private
By default, now you will only interact with private accounts.

 333     # skip private
 334     if skip_private:
 335         try:
 336             browser.find_element_by_xpath(
 337                 "//*[contains(text(), 'This Account is Private')]"
 338             )
 339             is_private = True
 340         except NoSuchElementException:
 341             is_private = False
 342         if is_private and (random.randint(0, 100) <= skip_private_percentage):
 343             return False, "{} is private account, by default skip\n".format(username)

**Comment by rzanetti2000** [comment]
i receive an error stating Access denied, i do not have permission to edit that file.
