### ISSUE TITLE
Call my custom comment function ?

### ISSUE THREAD

**Issue by citymayor** [InstaPy/InstaPy#4435]
Hi instapy friends! 

Is there a way to call my own "comment" function based on the context of the current image?
Let's say I'd like to make a comment based on the description, location or make some image analyse.

I know there are function that works with predefined  third parties function such as [`set_use_meaningcloud` / `set_use_yandex` / `set_use_clarifai`](https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#interact-by-comments) , but I'd like to do my own text/image analyse

I'm thinking something like that...
```

with smart_run(session):
    session.set_do_comment(enabled=True, percentage=30)
    session.set_do_comment_custom_function(enabled=True, function=my_function)

def my_function():
   # description , text , likes , comments, image variable would be accessible
   do_action(description)
   do_action(...)
   ...
   return comment
```

As an alternative, I could fork instapy and add my function in directly in the library , but I'd like to do this without having to change instapy directly?

Thank you for your help!

**Comment by CharlesCCC** [comment]
Sure thing, just wrote your function and call it within your code. but, if you have something works pretty well, I(we) wouldn't mind to have you share it with the community :)

**Comment by citymayor** [comment]
@CharlesCCC thanks! 

>  just wrote your function and call it within your code

I didn't see any commenting instapy function that allows me to call my custom function for commenting. Would you mind to point me to the right direction?

I'd love to share my code obviously :)

**Comment by citymayor** [comment]
bumping that one to not go stale :)

**Comment by CharlesCCC** [comment]
@citymayor Sorry for the delay, Really busy recently at work:

Here are two places you can get start:

You can mimic the following to set-up which comments method to use (in this case, will be your customized method) 
https://github.com/timgrossmann/InstaPy/blob/master/instapy/instapy.py#L4786

Here is where you should put your customized text analysis comment method:
https://github.com/timgrossmann/InstaPy/blob/master/instapy/text_analytics.py
