### ISSUE TITLE
Temporary block when Unfollowing

### ISSUE THREAD

**Issue by Gevoraway** [InstaPy/InstaPy#4436]
I am having the following error when trying to unfollow. This issue has been raised before, but doesn't seem to be solved.

**WARNING [2019-05-15 12:20:13] [gevor] Phew! Last unfollow is not verified.	~'gevor' might be temporarily blocked from unfollowing
WARNING [2019-05-15 12:23:28] [gevor] There is a serious issue: 'temporary block'!	~leaving Unfollow-Users activity
INFO [2019-05-15 12:23:28] [gevor] --> Total people unfollowed : 0**

That's an error I get trying to unfollow. I'm running with **headless_browser=False** so I can see what's going on. There is an unfollow confirmation window popup, which instapy doesn't seem to register. I can manually click the unfollow button, which works perfectly. So my assumption is that I am not blocked.

Here's my code:
```
session.unfollow_users(amount=random.randint(75, 100),
                           InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=24 * 60 * 60, sleep_delay=600)
```

 ```
 session.unfollow_users(amount=random.randint(75, 100),
                           InstapyFollowed=(True, "all"), style="FIFO",
                           unfollow_after=168 * 60 * 60, sleep_delay=600)
```

**Comment by ishandutta2007** [comment]
I think it might be related to QS issue https://github.com/timgrossmann/InstaPy/issues/4430

**Comment by Gevoraway** [comment]
I don't think it is. First of all I can still manually unfollow. Second, I have not unfollowed anyone in a few days. Doesn't look like a quota issue.

**Comment by Kevdome3000** [comment]
Having same issue and I am only unfollowing 200 per day with very conservative custom action delays

**Comment by ishandutta2007** [comment]
Guys you should understand block defnitely means threshold breach, if you feel you haven't then that question should be asked to instagram.com and not instapy. followers unfollowers numbers are clearly visible on your profile so there can not be such thing that instapy behind your back is unfollowing more people than what it is telling you and thereby making you cross limits. That's not possible.

**Comment by Gevoraway** [comment]
@ishandutta2007 That the thing - there is no block. I can follow and unfollow users manually from my iPhone and Mac. Moreover I am running instapy with chrome browser open so I can see what's going on. I can clearly see that it gets stuck when a popup appears asking for a confirmation to unfollow. It really looks like an instapy glitch rather than instagram.

**Comment by ishandutta2007** [comment]
> @ishandutta2007 That the thing - there is no block. I can follow and unfollow users manually from my iPhone and Mac. Moreover I am running instapy with chrome browser open so I can see what's going on. I can clearly see that it gets stuck when a popup appears asking for a confirmation to unfollow. It really looks like an instapy glitch rather than instagram.

got it 👍
