### ISSUE TITLE
Many bots on local network

### ISSUE THREAD

**Issue by ericjmachado** [InstaPy/InstaPy#4449]
how many bots 24/7 can I run on the same local network without blocking?

**Comment by LuismiLabs** [comment]
You have to use proxies.

Check [Use a proxy (Chrome)](https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#use-a-proxy-chrome)

**Comment by ericjmachado** [comment]
Thanks, it works

**Comment by ishandutta2007** [comment]
@Luismij Luismij any idea how does it work in practice when say multiple accounts of an orgnaisation are connecting over seme wifi ie same network IP address. Why does't it block/shadowban in those case?
