### ISSUE TITLE
Media max like?

### ISSUE THREAD

**Issue by cjsmith015** [InstaPy/InstaPy#445]
Hey there!

This project is fantastic, I'm excited to start using it.
Is there any way to set a media min/max-like limit? I.e., prevent InstaPy from liking the post if it exceeds a certain number of likes? 

Thanks! Looking forward to all the awesome things from InstaPy!

**Comment by timgrossmann** [comment]
@cjsmith015 No, I'm sorry this, at the moment, isn't supported. You can only filter by the number of followers the owner of the post has.

**Comment by cjsmith015** [comment]
@timgrossmann Hey - just found a closed issue (https://github.com/timgrossmann/InstaPy/issues/249) that mentioned this same thing. Sorry I didn't find that sooner (I was only looking through open issues the first time)! Reasoning makes sense, and thanks for the quick response!

**Comment by cjsmith015** [comment]
@timgrossmann One more question: is it possible to have the bot skip all the top, trending posts? I want to interact with smaller accounts so I set the upper limit of followers to be around 6,000 - all the users that have trending posts in big tags likely have more than that. Might as well start within recent posts and save the bot from opening the first 9 trending/top posts.
