### ISSUE TITLE
mac_start.command Error

### ISSUE THREAD

**Issue by FreudsMothr** [InstaPy/InstaPy#4453]
Unable to run the mac_start command 

I'm getting the following error in terminal:

"Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
ImportError: No module named instapy
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]"

**Comment by MD-coderunner** [comment]
did you resolve it? I have the same issue

**Comment by Moggertron80** [comment]
Hi
I'm struggling with it too. I get the below.

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kzmogvz3/future/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kzmogvz3/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1ymk050t
         cwd: /tmp/pip-install-kzmogvz3/future/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output
