### ISSUE TITLE
Refreshing the page

### ISSUE THREAD

**Issue by PaPaScoRp** [InstaPy/InstaPy#4454]
I am trying to accept follow requests and well when it accepts all of them the script stops because there is no new requests. Does anyone know a way to make the program refresh the page every time there is no other requests?

**Comment by dp0920** [comment]
This has code that may help you out: https://stackoverflow.com/questions/10245641/refreshing-web-page-by-webdriver-when-waiting-for-specific-condition . Does that fix your issue?

**Comment by PaPaScoRp** [comment]
> This has code that may help you out: https://stackoverflow.com/questions/10245641/refreshing-web-page-by-webdriver-when-waiting-for-specific-condition . Does that fix your issue?

I mean i do already press f5 but I have 2 issues, 1st is that i cant/dont know how to get access to the browser that instapy opens so i cant use the .refresh() method.
Second is that because i cant/dont know how to get access to it, i have to make it oress f5 in general which makes it impossible to press anywhere other than the app itself.
