### ISSUE TITLE
How to setup proxy?

### ISSUE THREAD

**Issue by sebo361** [InstaPy/InstaPy#4457]
Hello,

i am trying to use proxy as i have several scripts running on my Digital ocean server. I user the following code:

```
def follow():

  session = InstaPy(username=insta_username, password=insta_password, proxy_address='8.8.8.8', proxy_port=8080, bypass_suspicious_attempt=True, headless_browser=True, disable_image_load=True)

  with smart_run(session):
 .....
```

Can I really use '8.8.8.8' as proxy address and '8080' as proxy port or do i have to change it to another address?

**Comment by synchronizing** [comment]
That is an invalid proxy -- you would have to utilize your own proxy. If you have experience with Docker, I recommend using [Frontman](https://github.com/waultics/Frontman), which simply wraps [ProxyBroker](https://github.com/constverum/ProxyBroker) in a Docker container for easy data transfer through random proxies (disclaimer: I am involved with Frontman). Otherwise, you can just use ProxyBroker directly for your needs. 

Edit: As @ishandutta2007 mentioned below, this method does not guarantee that the proxies aren't being used by other people to log in to Instagram. If you do require a _private_ proxy, I would instead recommend opening a droplet on DigitalOcean or booting up an AWS EC2.

**Comment by ishandutta2007** [comment]
@synchronizing aren't those free proxies being used by humdreds of other peoples ? How does it gurantee it is not being used by more than 5 instagram accounts ?

**Comment by synchronizing** [comment]
@ishandutta2007 It doesn't guarantee at all, unfortunately. The only thing that would ensure you proxy (private or free) wasn't being used for more than `n` Instagram accounts is if you set one up yourself. Unless, of course, you specifically buy some sort of proxy service that has a dedicated IP per customer (which is not the default buy-in for paid proxies, from my understanding).

**Comment by ishandutta2007** [comment]
@synchronizing  How is your experience with Frontman , have you ever got shadowbanned or soft blocked ?

**Comment by synchronizing** [comment]
> @synchronizing How is your experience with Frontman , have you ever got shadowbanned or soft blocked ?

I have personally not bothered. I am running 5 accounts and I made sure to put enough randomness in my calls that the entire system looks more like a social media manager logging in to every single account individual and doing tasks than a bot doing its routine. I would even go as far as recommending that if your intention is **not** to  _spam_, than to not use ProxyBroker/Frontman. I don't think the risks outweigh the benefits, as public proxies are not the best as you mentioned. 

If you do chose to use it anyhow, let me mention that I made an update very recently to Frontman to use a modified version of ProxyBroker, which will certainly break with InstaPy, so I would recommend instead using ProxyBrokers original repo.

**Comment by ishandutta2007** [comment]
> > 
> 
> I have personally not bothered

Didn't get you. Do you mean you haven't got affected by using Frontman or do you mean you haven't used Frontman ever as you deal with only 5 accounts ?

**Comment by ishandutta2007** [comment]
> like a social media
How does it matter ? if that person's designation is social media manager is he allowed to use more than 4  accounts from same ip ?

**Comment by synchronizing** [comment]
> Didn't get you. Do you mean you haven't got affected by using Frontman or do you mean you haven't used Frontman ever as you deal with only 5 accounts ?

I have not bothered using Frontman myself since I have only 5 accounts. 

> How does it matter ? if that person's designation is social media manager is he allowed to use more than 4 accounts from same ip ?

Well, it is case-by-case that Instagram bans or shadowbans. I have logged into more than 5 accounts in the span of 15 minutes and didn't have any affected. It's truly about the randomness, in my opinion, and not making it obvious you are running a bot.

**Comment by ishandutta2007** [comment]
@synchronizing  do you post regularly and have you surely checked with all your hashtags that you are not shadowbanned ?

**Comment by synchronizing** [comment]
> @synchronizing do you post regularly with all the accounts and have you surely checked with all your hashtags that you are not shadowbanned ?

Shadowbanned from 1 account because it is artsy pre-nudity stuff, but the rest are all fine. Posting 3 times a day to each account, business accounts on all of them, using [Buffer](https://buffer.com/) to upload automatically.

**Comment by ishandutta2007** [comment]
You must be having Buffer paid accounts ? 
Its funny that just few days back I was trying to write [BufferPy](https://github.com/socialbotspy/BufferPy) (similar to [InstaPy](https://github.com/timgrossmann/InstaPy)) to schedule more than 10 posts for free tier accounts. Moved on thinking maybe it's not worth the time, so ended up writing [scheduler](https://github.com/ishandutta2007/InstaSchedule) for remote client login

**Comment by synchronizing** [comment]
> @synchronizing You must be having Buffer paid accounts ?
> Its funny that just few days back I was trying to write [BufferPy](https://github.com/socialbotspy/BufferPy) (similar to [InstaPy](https://github.com/timgrossmann/InstaPy)) to schedule more than 10 posts for free tier accounts. Gave up thinking maybe it's not worth the time, so ended up writing [scheduler](https://github.com/ishandutta2007/InstaSchedule) for remote client login

Very interesting. My only concern with using an open-source project for this use case is that it frankly looks less legit from Instagrams end. A business account with an affiliated payed-service business partner of Instagram just looks more legit and my belief is it makes your account look less sketchy. I'll check out the projects regardless, thanks for the share!

**Comment by ishandutta2007** [comment]
@synchronizing yeah check only BufferPy, for the reason you mentioned direct scheduler of more than 5 accounts from same IP is not only risky but also to be interrupted by failures, so focusing on making BufferPy move from selenium to buffers APIs

**Comment by Housain-maina** [comment]
> > Didn't get you. Do you mean you haven't got affected by using Frontman or do you mean you haven't used Frontman ever as you deal with only 5 accounts ?
> 
> I have not bothered using Frontman myself since I have only 5 accounts.
> 
> > How does it matter ? if that person's designation is social media manager is he allowed to use more than 4 accounts from same ip ?
> 
> Well, it is case-by-case that Instagram bans or shadowbans. I have logged into more than 5 accounts in the span of 15 minutes and didn't have any affected. It's truly about the randomness, in my opinion, and not making it obvious you are running a bot.

From my own experience after getting my account banned. I think the number of accounts in a single droplet does matter, and also the IP location of your droplet. Let's say you normally log in to your Instagram account from your smartphone in China and then you created a droplet with a server in Dallas, then Instagram could easily detect that you're using a bot. It makes more sense to use a server not too far from your location.
