### ISSUE TITLE
Use clarifai to like specific post

### ISSUE THREAD

**Issue by lucasghelal** [InstaPy/InstaPy#4458]
## Expected Behavior
I want to use the clarifai api to like posts that  contain photos of "food", for example. 
## Current Behavior

The code simply goes through the clarifai and does not check if it has that element (food) in the photo.
## Possible Solution (optional)
Maybe make a function to check if it has the element in the photo.

## InstaPy configuration
'''
# activity
    session.set_use_clarifai(enabled=True, api_key='key')
    session.clarifai_check_img_for(['food'])
    
    session.like_by_tags(['tag1'], amount=15)
   
    session.like_by_locations(['123456'], amount=15)
    session.set_do_like(True, percentage=100)
'''

**Comment by arieller** [comment]
bumping,
can one like a post based on clarifai?
