### ISSUE TITLE
Chrome error

### ISSUE THREAD

**Issue by thaysen13** [InstaPy/InstaPy#4461]
## Expected Behavior
Normal installation
## Current Behavior
Error when I do the installation
## InstaPy configuration
I have already chrome installed and I installed pip but get always te same error.

directory found.. checking for chrome
chrome not installed
you must install chrome before using InstaPy. please visit https://www.google.com/chrome/ and download the correct version for your operating system.
python installed: yes
pip installed: yes
chrome installed: no
InstaPy installation: incompleted

Can anyone help me please?

**Comment by JoeFertig** [comment]
think you wont get answers without providing any information about your system.

**Comment by thaysen13** [comment]
Just normal start configuration
