### ISSUE TITLE
small problem

### ISSUE THREAD

**Issue by Blu3Blood** [InstaPy/InstaPy#4462]
Hi, please help me, i dont understend  why is not working 
I need
1) Follow to 15 profile from location
2) like 3 photo in each profile for which follow
And now how does it work
1)Follow to profile from location - (ok, it's work)
2)like 3 photo in this profile - ( it's not working)

`with smart_run(session):
    # general settings

     session.set_relationship_bounds(enabled=True, delimit_by_numbers=True, max_followers=8500, max_following=4490, min_followers=100, min_following=56, min_posts=10, max_posts=500)
     session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
     session.set_do_like(enabled=True)
     #action

     session.follow_by_locations (['224586674/megion/'], amount=15)

    # activity

     session.unfollow_users(amount=7500, nonFollowers=True, style="RANDOM",
     unfollow_after=42*60*60, sleep_delay=3)`

**Comment by mheubaum** [comment]
Take a look in the documentation. 
I think `session.follow_by_locations` should be modified with `interact=true`

**Comment by Anupamadke** [comment]
Same here brother its liking only one photo in my case
