### ISSUE TITLE
error Mac 

### ISSUE THREAD

**Issue by alblz** [InstaPy/InstaPy#4468]
Collecting instapy
  Using cached https://files.pythonhosted.org/packages/04/d5/ef4e7196d9593e24bc6c44d3f22e2d60139b87819c0b6976820a0baa1ffa/instapy-0.4.3-py2.py3-none-any.whl
Collecting six>=1.11.0 (from instapy)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting clarifai>=2.4.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/d2/e3/5c2e868bd49db72a8a771e9c8fa66c96ef6e8fa1bc8b9de4a28c47a3e5c6/clarifai-2.6.1-py2-none-any.whl
Collecting emoji>=0.5.1 (from instapy)
Collecting certifi>=2018.10.15 (from instapy)
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Collecting jsonschema>=2.6.0 (from instapy)
  Using cached https://files.pythonhosted.org/packages/aa/69/df679dfbdd051568b53c38ec8152a3ab6bc533434fc7ed11ab034bf5e82f/jsonschema-3.0.1-py2.py3-none-any.whl
Collecting PyVirtualDisplay>=0.2.1 (from instapy)
Collecting urllib3>=1.24.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/39/ec/d93dfc69617a028915df914339ef66936ea976ef24fa62940fd86ba0326e/urllib3-1.25.2-py2.py3-none-any.whl
Collecting instapy-chromedriver (from instapy)
Collecting chardet>=3.0.4 (from instapy)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting future>=0.17.1 (from instapy)
Collecting protobuf>=3.6.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/6d/4d/b4ba2bb8bd7e7ef6846f295a095e07f61ce896c83786dcea48a1dd4149f5/protobuf-3.7.1-cp27-cp27m-macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting plyer>=1.3.1 (from instapy)
Collecting selenium>=3.141.0 (from instapy)
  Using cached https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl
Collecting configparser>=3.5.0 (from instapy)
  Using cached https://files.pythonhosted.org/packages/ba/05/6c96328e92e625fc31445d24d75a2c92ef9ba34fc5b037fe69693c362a0d/configparser-3.7.4-py2.py3-none-any.whl
Collecting PyYAML>=3.13 (from instapy)
Collecting MeaningCloud-python>=1.1.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/28/c6/deb6c9d113f94ec99116ec4017b333660ce54344734d29f0cb98fdf32945/MeaningCloud_python-1.1.1-py2.py3-none-any.whl
Collecting regex>=2018.11.22 (from instapy)
Collecting grpcio>=1.16.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/41/c0/6bf54d407de0931c080c1f177823929ad0543634b5016e288d7f21889035/grpcio-1.20.1-cp27-cp27m-macosx_10_9_x86_64.whl
Collecting idna>=2.7 (from instapy)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting requests>=2.20.1 (from instapy)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting EasyProcess>=0.2.3 (from instapy)
Collecting enum34<2,>=1.1 (from clarifai>=2.4.1->instapy)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting googleapis-common-protos<2,>=1.5.0 (from clarifai>=2.4.1->instapy)
Collecting typing>=3.6 (from clarifai>=2.4.1->instapy)
  Using cached https://files.pythonhosted.org/packages/cc/3e/29f92b7aeda5b078c86d14f550bf85cff809042e3429ace7af6193c3bc9f/typing-3.6.6-py2-none-any.whl
Collecting attrs>=17.4.0 (from jsonschema>=2.6.0->instapy)
  Using cached https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting functools32; python_version < "3" (from jsonschema>=2.6.0->instapy)
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from jsonschema>=2.6.0->instapy) (18.5)
Collecting pyrsistent>=0.14.0 (from jsonschema>=2.6.0->instapy)
Collecting futures>=2.2.0; python_version < "3.2" (from grpcio>=1.16.1->instapy)
  Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
ERROR: clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.
Installing collected packages: six, protobuf, configparser, enum34, urllib3, certifi, chardet, idna, requests, attrs, functools32, pyrsistent, jsonschema, googleapis-common-protos, typing, future, futures, grpcio, clarifai, emoji, EasyProcess, PyVirtualDisplay, instapy-chromedriver, plyer, selenium, PyYAML, MeaningCloud-python, regex, instapy
  Found existing installation: six 1.4.1
ERROR: Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by idnr** [comment]
> ERROR: clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.

this issue you can do a quick

> sudo pip install jsonschema==2.6.0

**Comment by alblz** [comment]
ERROR: Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

any idea?¿?

**Comment by flxdhc** [comment]
@alblz you can try 
sudo python -m pip install clarifai --upgrade --ignore-installed six
