### ISSUE TITLE
How do I reduce wait time...

### ISSUE THREAD

**Issue by TheSentinel36** [InstaPy/InstaPy#4469]
## Expected Behavior
Would like to sleep only a few minutes between calls... 
## Current Behavior
INFO [2019-05-21 20:13:49] [userid]  Unfollowed 8 new users  ~sleeping about 9.76 minutes
[more unfollowing...]
INFO [2019-05-21 20:44:34] [userid]  Unfollowed 11 new users  ~sleeping about 11.18 minutes

## Possible Solution (optional)
I think my sleep or quota supervisor settings are out of whack...

Do I reduce the sleep delay, or is there another setting that will reduce the sleep time from ~9 minutes to 2-3 minutes?

## InstaPy configuration
` session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "comments_d", "follows",
                                              "unfollows", "server_calls_h"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(100, 700),
                                 peak_comments=(100, 600),
                                 peak_follows=(48, 375),
                                 peak_unfollows=(35, 400),
                                 peak_server_calls=(None, 3000))
    """ End of parameter setting """

    """ Actions start here """
    # Unfollow users
    """ Users who were followed by InstaPy, but not have followed back will 
    be removed in
        One week (168 * 60 * 60)
        Yes, I give a liberal one week time to follow [back] :)
    """
    session.unfollow_users(amount=75, InstapyFollowed=(True, "nonfollowers"),
                           style="RANDOM",
                           unfollow_after=168 * 60 * 60,
                           sleep_delay=600)
`

**Comment by JoeFertig** [comment]
https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#custom-action-delays

**Comment by mheubaum** [comment]
`sleep_delay=600` means appr. 10 minutes

**Comment by TheSentinel36** [comment]
Thanks guys!

I had read through the documentation but for some reason didn't think about the sleep delay aspect.
