### ISSUE TITLE
Chrome not installed (after fresh install of everything)

### ISSUE THREAD

**Issue by mareekkk** [InstaPy/InstaPy#4470]
InstaPy supposed to be working just fine on my computer until I did a full reformat and fresh installation of Windows.

Installed Python and installed InstaPy using pip install then tried running quickstart.py which actually just closes the window.

Then I tried installing it via the instapy-quickstart-master installation but it says I have not installed Chrome which I actually did. Is there a path I should change or download a file and put it somewhere? I would be very much thankful.

*InstaPy is located in: C:\Users\username\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy
* Using the latest version of Chrome and latest version of Python too.
* All of these are fresh install including my Windows 10 64bit 
** In the screenshot, I need to write the entire path of pip.exe to be able to use it because I cannot just use pip install directly.

Also. I have another question, after I installed it using pip, did it create another directory somewhere where quickstart.py is located or perhaps a workspace folder? The installation doesnt say anything.

![Uploading 2019-05-22_2107.png…]()
![Uploading 2019-05-22_2107_001.png…]()

**Comment by mareekkk** [comment]
![Uploading 2019-05-22_2122.png…]()

**Comment by clovisolivier** [comment]
Same issue there

**Comment by mareekkk** [comment]
I hope someone could really help us. I searched a lot already but no solution til now.

**Comment by isonlaxman** [comment]
Yep same issue, no idea what is wrong

**Comment by clovisolivier** [comment]
Hi there,
I've found a way to make it run on my raspbian.
Just use `python3 quickstart.py -hb`
It's working for me

**Comment by clovisolivier** [comment]
Hi there, 
Here is a potential fix : 
`
sudo apt-get remove chromium-browser
sudo apt-get install chromium-browser
`
then execute quickstart.py with option -hb
