### ISSUE TITLE
Not unfollowing properly

### ISSUE THREAD

**Issue by dmfaria** [InstaPy/InstaPy#4479]
I found similar issues from 2018 (#2111 #2259 #1859 #2105) but no solution. 

The script can not unfollow all the users followed by instapy. 

I checked that all the unfollowed users are recorded in the log "_record_all_unfollowed.csv" and removed from the following pool, this means that instapy don't check these users anymore. The problem is that some of these users remain in my following list.

Is there any solution? Is there a way for the script to only remove from the following pool log file when the user is really unfollowed?

**Comment by mheubaum** [comment]
You should not unfollow too many users in a short time. Insta will let you unfollow them, but they will appear again in your followings list. It's like a ban. So increase the sleep time and decrease the amount.

**Comment by schneid201** [comment]
I tried unfollowing the non-followers and the amount to your following amount. Currently it's working (meaning that every user is being unfollowed). I'll update when I have more info.

Probably not the best solution but it is a temporary fix.

ps: I have absolutely 0 coding skills so this comment could be really dumb for all I know ;)
