### ISSUE TITLE
can't use proxy on windows 

### ISSUE THREAD

**Issue by theRouter** [InstaPy/InstaPy#4480]
hi, i have problem with using proxy after new update.
when i use headless or not it didn't worked and didn't load instagram page.
can any body help me?

## Current Behavior

Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

**Comment by fintzd** [comment]
What did you use in QuickStart? (paste the code)

**Comment by theRouter** [comment]
> What did you use in QuickStart? (paste the code)

session = InstaPy(username=insta_username,
					password=insta_password,
					proxy_address='5.190.211.49', proxy_port=143,
					split_db=True,
					headless_browser=False,
					disable_image_load=True,
					bypass_suspicious_attempt=True,
					bypass_with_mobile=True)
					
with smart_run(session):
	session.set_dont_include(["taniya_saadi", "chehrazimag", "modiresabz""])		
	session.set_quota_supervisor(enabled=True, sleep_after=["likes", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
								  peak_likes=(50, 500),
								  peak_follows=(40, None),
								  peak_unfollows=(39 ,402),peak_server_calls=(None, 4700))
									  

	session.set_skip_users(skip_private=False,
						   private_percentage=100,
						   skip_no_profile_pic=False,
						   no_profile_pic_percentage=100,
						   skip_business=True,
						   skip_non_business=False,
						   business_percentage=100,
						   skip_business_categories=[],
						   dont_skip_business_categories=['Local Business','Local Business','Photographer','Photography Videography'])

	session.set_relationship_bounds(enabled=True,
					 potency_ratio=None,
					  delimit_by_numbers=True,
					   max_followers=8500,
						max_following=4490,
						 min_followers=50,
						  min_following=30,
						   min_posts=None,
							max_posts=1000)
							
	session.set_action_delays(enabled=True,
							   like=3,
							   comment=5,
							   follow=4.17,
							   unfollow=28)	
							   
	session.set_delimit_liking(enabled=True, max=1005, min=0)
						   
	session.follow_by_locations(['297648288/yasuj/'], amount=100, skip_top_posts=True)
	session.like_by_locations(['297648288/yasuj/'], amount=100, skip_top_posts=True)

	accs = session.grab_followers(username="yasujconcert", amount="full", live_match=True, store_locally=True)
	session.set_user_interact(amount=3, randomize=False, percentage=100, media='Photo')
	session.set_do_follow(enabled=True, percentage=100, times=1)
	session.set_do_like(enabled=True, percentage=100)
	session.follow_by_list(followlist=accs, times=1, sleep_delay=840, interact=True)

	session.set_user_interact(amount=3, randomize=False, percentage=100, media='Photo')
	session.set_do_follow(enabled=True, percentage=100, times=1)
	session.set_do_like(enabled=True, percentage=100)
	session.follow_likers (['zahra__s.j'], photos_grab_amount = 1, follow_likers_per_photo = 1700, randomize=False, sleep_delay=11000, interact=True)


	session.join_pods()

**Comment by theRouter** [comment]
i took this error now when use headless_browser=True

Cookie file not found, creating cookie...

INFO [2019-06-03 12:43:27] [.......] Sessional Live Report:
|> No any statistics to show

and when use headless_browser=False :

instapy.exceptions.InstaPyError: ensure chromedriver is installed at C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\instapy_chromedriver\chromedriver_win32.exe

i check that path and chromedriver was there :(
