### ISSUE TITLE
Send Session logs through Telegram - NO ANSWER :(

### ISSUE THREAD

**Issue by fintzd** [InstaPy/InstaPy#4483]
## InstaPy configuration

Hey! 

I'm trying to get the information that is shown at the end of the session to be sent to me via the Telegram API, any ideas on how to do that? I keep on getting an array of different errors, and after hours of research I'm about to give up ... 

Thank you!

**Comment by Joker6888** [comment]
Interesting thing, I am really interested in it too.

**Comment by fintzd** [comment]
Anyone guys? @timgrossmann ?

**Comment by mostafa8026** [comment]
did you find any solution?
