### ISSUE TITLE
IMPORTANT REQUEST: Only follow private accounts

### ISSUE THREAD

**Issue by davidkessler-ch** [InstaPy/InstaPy#4486]
So I analysed data from the last few month and noticed that private users will follow back A LOT more than public ones. I think this may be due to the fact that private users actively have to interact with your account, either accepting or refusing your request.

I think it would be a fairly basic feature that can make a huge difference. I would also post a bounty for this if anyone is interested.
## Expected Behavior
following only private users, skipping public users
## Current Behavior
following both private and public accounts

**Comment by synchronizing** [comment]
This is already implemented, from my understanding, under `set_skip_users()` function:

```python
session.set_skip_users(skip_private=false, skip_no_profile_pic=true, skip_business=true, skip_non_business=true)
```
