### ISSUE TITLE
Unfollow function unfollows all instead of non-followers

### ISSUE THREAD

**Issue by alinakhay** [InstaPy/InstaPy#4488]
Hi! I have an issue running unfollow function - instead of unfollowing only non-followers, it unfollows everyone. I am using:
` session.unfollow_users(amount=random.randint(200, 250), nonFollowers=True, style="RANDOM", unfollow_after=42 * 60 * 60, sleep_delay=655)`

Can you kindly help please? Thank you!

**Comment by fintzd** [comment]
Could you try to run the script and paste what the output is that you get when it starts running?

It should be something like this:

`INFO [2019-06-02 23:55:18] [username]  Unfollowing the users who do not follow back`

`INFO [2019-06-02 23:55:18] [username]  Retrieving live Followers data of username at "full" range
  582/582 [===================================+]  100%    |> Elapsed: 33.26 seconds    |> ETA: 0.0 seconds`

`INFO [2019-06-02 23:55:54] [username]  Grabbed 582 usernames from Followers in 33.26 seconds`
`INFO [2019-06-02 23:55:54] [username]  Stored Followers data at /root/InstaPy/logs//relationship_data/username/followers/02-06-2019~full~582.json local file`

`INFO [2019-06-02 23:57:07] [username]  Retrieving live Following data of username at "full" range
  1314/1314 [===================================+]  100%    |> Elapsed: 1.09 minutes    |> ETA: 0.0 seconds`

`INFO [2019-06-02 23:58:19] [username]  Grabbed 1314 usernames from Following in 1.09 minutes
INFO [2019-06-02 23:58:19] [username]  Stored Following data at /root/InstaPy/logs//relationship_data/username/following/02-06-2019~full~1314.json local file`
