### ISSUE TITLE
Following by a list - Total followers (treshhold 1000 limiter)

### ISSUE THREAD

**Issue by jeffreylm** [InstaPy/InstaPy#449]
What determines the total follow amount?

I want to avoid passing the 1000 treshhold. Is there a mechanism in place to keep track of the scripts total
follows from all the different session calls? So a counter of sorts.

Is there a counter in place to protect against the passing of the different tresholds?
I am also using this "session.set_do_follow(enabled=True, percentage=10, times=1)" in my script, so I wonder if the right hand knowns what the left hand is doing.

**Comment by timgrossmann** [comment]
@jeffreylm There is no mechanism for that, as of right now.

**Comment by snakelab** [comment]
i did this feature by adding a sqlite db/table, maybe we should merge ;-)

**Comment by timgrossmann** [comment]
@snakelab Sounds good, are you open for a PR?

**Comment by snakelab** [comment]
hi tim, sure, i am just fixing some typos and will do a PR ;-)
