### ISSUE TITLE
 "user" has already been followed 1 times

### ISSUE THREAD

**Issue by jinayG** [InstaPy/InstaPy#4492]
## Current Behavior
Hi,
I am using follow user followers and for 90% of the users it is giving the error  "user has already been followed 1 times" and does not follow them. I suspect that the usernames that are being extracted are same for each time. 

After sessions in the summary it shows:

Already followed: 0
Followed:0

I do not know how to solve this issue.

**Comment by kalebic** [comment]
I also have this issue. Here's an output from my logs:
```
INFO [2019-06-01 03:15:39] [myusername]  Grabbed 17 usernames from 'user1's `Following` to do following

INFO [2019-06-01 03:15:39] [myusername]  Ongoing Follow [1/17]: now following 'user2'...
INFO [2019-06-01 03:15:42] [myusername]  ---> user2 has already been followed 1 times

INFO [2019-06-01 03:15:43] [myusername]  Follow per user: 0  |  Total Follow: 0

INFO [2019-06-01 03:15:43] [myusername]  Ongoing Follow [2/17]: now following 'user3'...
INFO [2019-06-01 03:15:46] [myusername]  ---> user3 has already been followed 1 times

INFO [2019-06-01 03:15:47] [myusername]  Follow per user: 0  |  Total Follow: 0
```

At the end I'll get something like this:
```
INFO [2019-06-01 03:16:44] [myusername]  Sessional Live Report:
	|> LIKED 0 images  |  ALREADY LIKED: 0
	|> COMMENTED on 0 images
	|> FOLLOWED 3 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> LIKED 0 comments
	|> REPLIED to 0 comments
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0
```

So far I've tried changing from `like_by_tags` to `follow_user_followers` in case it was a method-related bug, but still experiencing the same issue. I've also tried doing a fresh install of my DigitalOcean environment in case cookies / logs were the issue. 

Here's my current code that's scheduled to run every 6 hours:
```
# imports
from instapy import InstaPy
from instapy import smart_run
import random

# login credentials
insta_username = 'myusername'
insta_password = 'mypassword'

comments = [u':heart_eyes: :heart_eyes: :heart_eyes:',
                u':ok_hand:',
                u':thumbsup:',
                u':heart:',
                u':100: :100: :100:',
                u':fire: :fire: :fire:',
                u':yum:',
                u':ok_hand: :ok_hand: :ok_hand:',
                u':two_hearts:',
                u':yum: :yum: :yum:']

target_accounts = ['user1', 'user2', 'user3']

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

with smart_run(session):
  session.set_do_like(enabled=True, percentage=50)
  session.set_do_comment(enabled=True, percentage=10)
  session.set_comments(comments, media='Photo')

  session.set_user_interact(amount=random.randint(2,3), percentage=50)

  session.follow_user_following(target_accounts,
                                amount=random.randint(30,50),
                                randomize=False,
                                interact=True)

  # Joining Engagement Pods
  session.join_pods()
```

Lastly, if I check from the account the bot is running on, it will say that I don't follow the user's profile. However, if I search the user's profile from another account, it will show that my bot account is following that person in the search results. In both cases, when I search the user's list of followers the bot account is not listed. 

Any thoughts? This is pretty crippling for my script :( so would love to figure out the root cause. @timgrossmann

**Comment by jinayG** [comment]
I have the exact problem. My script is as below :
```

"""
This template is written by @Nuzzo235
What does this quickstart script aim to do?
- This script is targeting followers of similar accounts and influencers.
- This is my starting point for a conservative approach: Interact with the
audience of influencers in your niche with the help of 'Target-Lists' and
'randomization'.
NOTES:
- For the ease of use most of the relevant data is retrieved in the upper part.
"""

import random
import datetime
from instapy import InstaPy
from instapy import smart_run

#Get hours
hh = float(datetime.datetime.now().strftime('%H'))

# login credentials
insta_username = 'username'
insta_password = 'password'

# restriction data
dont_likes = ['#sex', '#nude', '#naked', 'beef', 'pork', 'seafood',
              'egg', 'chicken', 'sausage', 'lobster',
              'fish', 'schwein', 'lamm', 'rind', 'kuh', 'meeresfrüchte',
              'schaf', 'ziege', 'essen', 'mahl','turkey', 'truthahn','bacon',
              'sushi', 'salmon', 'shrimp', 'steak',
              'schnitzel', 'goat', 'oxtail', 'mayo', 'fur', 'leather',
               'slaughter', 'pussy','meme','joke',
              ]
ignore_users = ['user1', 'user2', 'user3']

""" Prevent commenting on and unfollowing your good friends (the images will 
still be liked)...
"""
friends = []

""" Prevent posts that contain...
"""
ignore_list = []

# TARGET data
""" Set similar accounts and influencers from your niche to target...
"""
targets = []

""" Skip all business accounts, except from list given...
"""
#target_business_categories = ['Home Goods Stores','Food & Personal Goods','Food & Personal Goods','Personal Goods & General Merchandise Stores']

# COMMENT data
comments = [
                             u'Great Work',
                             u':heart_eyes::heart_eyes::heart_eyes:',
                             u':thumbsup:',
                             u':heart::heart:',
                             u'Amazing',
                             u'Wow',
                             u'Wow :thumbsup:',
                             u'Superb',
                             u'Wow :heart_eyes::heart_eyes:',
                             u'Beautiful',
                             u'Beautiful :heart_eyes::heart_eyes:'
                             ]


# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  multi_logs=True)

# let's go! :>
with smart_run(session):
    # HEY HO LETS GO
    # general settings
#    session.set_dont_include(friends)
    session.set_dont_like(dont_likes)
 #   session.set_ignore_if_contains(ignore_list)
   # session.set_ignore_users(ignore_users)
    session.set_simulation(enabled=True)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=0.1,
                                    delimit_by_numbers=True,
                                    max_followers=7500,
                                    max_following=13000,
                                    min_followers=20,
                                    min_following=0,
                                    min_posts=1)
    session.set_skip_users(skip_private=False,
                           skip_no_profile_pic=True,
                           skip_business=True,
                           dont_skip_business_categories=[
                               'Creators & Celebrities','Arts & Entertainment','Artist','Public Figure'])
    session.set_action_delays(enabled=True,
                           like=4,
                           comment=6,
                           follow=15,
                           unfollow=15,
						   randomize=True, random_range=(70, 140))
						   
    session.set_user_interact(amount=1, randomize=True, percentage=50,
                              media='Photo')
    session.set_do_like(enabled=True, percentage=90)
    session.set_do_comment(enabled=True, percentage=40)
    session.set_comments(comments, media='Photo')
    session.set_do_follow(enabled=True, percentage=40, times=1)

    # activities

    # FOLLOW+INTERACTION on TARGETED accounts
    """ Select users form a list of a predefined targets...
    """
    number = random.randint(1, 3)
    random_targets = targets

    if len(targets) <= number:
        random_targets = targets

    else:
        random_targets = random.sample(targets, number)
	
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments", "follows", "unfollows", "server_calls"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(57, 585),
                               peak_comments=(21, 182),
                                peak_follows=(50, 400),
                                 peak_unfollows=(70, 402),
                                  peak_server_calls=(300, 6000))
								  
    """ Interact with the chosen targets...
    """
    session.follow_user_followers(random_targets,
                                  amount=random.randint(50, 100),
                                  randomize=True, sleep_delay=300,
                                  interact=True)


    # UNFOLLOW activity
    """ Unfollow nonfollowers after one day...
    """
    if hh > 18:
        session.unfollow_users(amount=random.randint(500, 1000),
                            InstapyFollowed=(True, "nonfollowers"),
                             style="FIFO",
                              unfollow_after=48 * 60 * 60, sleep_delay=300)
        """ Unfollow all users followed by InstaPy after one week to keep the 
        following-level clean...
        """
        session.unfollow_users(amount=random.randint(500, 1000),
                            InstapyFollowed=(True, "all"), style="FIFO",
                             unfollow_after=168 * 60 * 60, sleep_delay=600)
    """ Unfollow all users followed by InstaPy after one week to keep the 
    following-level clean...
    """
        

    """ Joining Engagement Pods...
    """
    session.join_pods()
```

I believe, it is extracting the same users because which checked the username in the logs, it was present. However, the follower list is quite huge and has not been exhausted.

**Comment by jinayG** [comment]
@uluQulu @timgrossmann Any idea of what we can do?

**Comment by fintzd** [comment]
> @uluQulu @timgrossmann Any idea of what we can do?

May be a dumb question, but are they in your followers already?

**Comment by jinayG** [comment]
No, they are not in my followers, I am following them.

**Comment by fintzd** [comment]
Sorry, but I'm a bit confused here, you already followed them, what is the issue? I must not understand something.

**Comment by kalebic** [comment]
The issue is that even though the script indicates I'm following them, in reality I'm not. From my post above: `Lastly, if I check from the account the bot is running on, it will say that I don't follow the user's profile. However, if I search the user's profile from another account, it will show that my bot account is following that person in the search results. In both cases, when I search the user's list of followers the bot account is not listed.`

This is also seen when the script says
```
INFO [2019-06-01 03:15:39] [myusername]  Ongoing Follow [1/17]: now following 'user2'...
INFO [2019-06-01 03:15:42] [myusername]  ---> user2 has already been followed 1 times

INFO [2019-06-01 03:15:43] [myusername]  Follow per user: 0  |  Total Follow: 0
```
 but in the final output gives `	|> FOLLOWED 3 users  |  ALREADY FOLLOWED: 0`. It's not actually doing anything, because for some reason it thinks I'm already following that person. There is no record of any of these individuals being unfollowed in my logs (I haven't even included unfollows in my script - see above). @hollossy hope that makes sense! Let me know

**Comment by fintzd** [comment]
> The issue is that even though the script indicates I'm following them, in reality I'm not. From my post above: `Lastly, if I check from the account the bot is running on, it will say that I don't follow the user's profile. However, if I search the user's profile from another account, it will show that my bot account is following that person in the search results. In both cases, when I search the user's list of followers the bot account is not listed.`
> 
> This is also seen when the script says
> 
> ```
> INFO [2019-06-01 03:15:39] [myusername]  Ongoing Follow [1/17]: now following 'user2'...
> INFO [2019-06-01 03:15:42] [myusername]  ---> user2 has already been followed 1 times
> 
> INFO [2019-06-01 03:15:43] [myusername]  Follow per user: 0  |  Total Follow: 0
> ```
> 
> but in the final output gives `	|> FOLLOWED 3 users | ALREADY FOLLOWED: 0`. It's not actually doing anything, because for some reason it thinks I'm already following that person. There is no record of any of these individuals being unfollowed in my logs (I haven't even included unfollows in my script - see above). @hollossy hope that makes sense! Let me know

Well I'm not really sure sorry :/ I'm not sure I understand the issue 100% 

Maybe try to reinstall InstaPy, just save and import your Quickstart file. You'll also reset the followed db in this case, but that actually may help. 

Sorry about that!

**Comment by michn** [comment]
Your bots have already followed this user in the past, subsequently unfollowed them and by default you will not follow them again as it will come across as spamming. Your summary states that you did not follow anyone you had previously followed, which is consistent with your bot's performance

**Comment by kalebic** [comment]
The strange thing is that this is on a brand new install of InstaPy and my script does not have any unfollowing capabilities. Here's the code that I posted above:
```
# imports
from instapy import InstaPy
from instapy import smart_run
import random

# login credentials
insta_username = 'myusername'
insta_password = 'mypassword'

comments = [u':heart_eyes: :heart_eyes: :heart_eyes:',
                u':ok_hand:',
                u':thumbsup:',
                u':heart:',
                u':100: :100: :100:',
                u':fire: :fire: :fire:',
                u':yum:',
                u':ok_hand: :ok_hand: :ok_hand:',
                u':two_hearts:',
                u':yum: :yum: :yum:']

target_accounts = ['user1', 'user2', 'user3']

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

with smart_run(session):
  session.set_do_like(enabled=True, percentage=50)
  session.set_do_comment(enabled=True, percentage=10)
  session.set_comments(comments, media='Photo')

  session.set_user_interact(amount=random.randint(2,3), percentage=50)

  session.follow_user_following(target_accounts,
                                amount=random.randint(30,50),
                                randomize=False,
                                interact=True)

  # Joining Engagement Pods
  session.join_pods()
```

So there is no way that I have already followed and then unfollowed them, and the fresh install also eliminates the chance of it being attributable to old logs from when unfollow used to be part of my script.

**Comment by eduaf** [comment]
99% of the users trow same message. 200 targets grabbed only 1 or 2 are valid. 

INFO [2019-07-08 15:31:30] [xxx]  Ongoing Follow [51/65]: now following 'xyz'...
INFO [2019-07-08 15:31:33] [xxx]  User: 'xyz'  |> followers: 38  |> following: 61  |> relationship ratio: 0.62
INFO [2019-07-08 15:31:33] [xxx]  ---> xyzhas already been followed 1 times
INFO [2019-07-08 15:31:39] [xxx]  Follow per user: 0  |  Total Follow: 0

INFO [2019-07-08 15:32:50] [xxx]  Simulated follow : 1
INFO [2019-07-08 15:32:50] [xxx]  ---> abc has already been followed 1 times
INFO [2019-07-08 15:32:50] [xxx]  Not followed 'abc'  ~inappropriate user

**Comment by univers3** [comment]
Still same problem here.
Looks like InstaPy is taking the users that I'm already following in place to take the target likers/followers...
