### ISSUE TITLE
Oops an error occurred Instagram can't login

### ISSUE THREAD

**Issue by henrich01** [InstaPy/InstaPy#4493]
Hello,
I had a copyright issue with Instagram and now when I click I acknowledge and proceed I can't login in my account but an error appears "Oops an error occurred". It has been more than 2 days now and my page is active and online but I can't find anyway on how to login. Can someone please help me?

**Comment by Robbattie** [comment]
I have the same problem.. Have you made any progress yet?

**Comment by henrich01** [comment]
@Robbattie nothing yet. I can't login in my account yet.

**Comment by theRouter** [comment]
i cant login with proxy in windows. please help me

**Comment by octavius-1** [comment]
Why did the copyright issue happened at the first place?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by henrich01** [comment]
Hello @octavius-1 I took a video from a page which I thought belonged to the person that shared it. He gave me permissions and I tagged him but he wasn’t the real owner and that’s when I got a report from the actual owner.

**Comment by henrich01** [comment]
@Robbattie @theRouter my login worked finally check yours now.

**Comment by theRouter** [comment]
> @Robbattie @theRouter my login worked finally check yours now.

what chrome and chromedriver version did you used?
i took this error now when use headless_browser=True
Cookie file not found, creating cookie...

INFO [2019-06-03 12:43:27] [.......]  Sessional Live Report:
        |> No any statistics to show


 and when use headless_browser=False :

instapy.exceptions.InstaPyError: ensure chromedriver is installed at C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\instapy_chromedriver\chromedriver_win32.exe

i check that path and chromedriver was there :(
