### ISSUE TITLE
Could not grab any usable comments from this post

### ISSUE THREAD

**Issue by dlenskyi** [InstaPy/InstaPy#4497]
#4349 reopening

I tried to fix it with #4236 issue, but it doesn't work for me

here's an error I receive:

Failed to get comments' count!
b"Message: unknown error: Cannot read property 'count' of undefined\n (Session info: chrome=73.0.3683.103)\n (Driver info: chromedriver=2.44.609551 (5d576e9a44fe4c5b6a07e568f1ebc753f1214634),platform=Linux 4.15.0-47-generic x86_64)\n"
INFO [2019-04-23 12:46:43] [login] No interaction did happen.

What should I do?

Upd: I don't have session.set_delimit_commenting in my script

**Comment by fintzd** [comment]
Could this be the issue: #4505 ?
