### ISSUE TITLE
Comment on User Followers

### ISSUE THREAD

**Issue by DuncanTLaw** [InstaPy/InstaPy#4498]
I am trying to get a bot that ONLY comments on a users' followers, but not sure why the bot doesn't do anything and exits on its own...

`# imports
from instapy import InstaPy
from instapy import smart_run

# login
session = InstaPy(username='****',
                  password='****',
                  headless_browser=False)

# run sesh
with smart_run(session):
    
# parameters
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=False,
                                    max_followers=12000,
                                    max_following=1000,
                                    min_followers=25,
                                    min_following=25,
                                    #min_posts=6
                                    )
    session.set_skip_users(skip_private=True, skip_no_profile_pic=True)
    
# activity
    session.set_user_interact(amount=10, randomize=True, 
                              percentage=100, media='Photo')
    session.set_do_follow(enabled=True, percentage=0)
    session.set_do_like(enabled=True, percentage=0)
    session.set_comments(["****"])
    session.set_do_comment(enabled=True, percentage=100)
    session.interact_user_followers(['****'], amount=10, randomize=True)`

**Comment by octavius-1** [comment]
You need to like the picture in order to comment it, otherwise the action will just jump 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DuncanTLaw** [comment]
@octavius-1 thank you so much for the prompt reply! I've been scratching my head in understanding why.

Just a quick one: for session.set_user_interact(amount=10 and session.interact_user_followers(['****'], amount=10, do the amounts need to be the same? What do they actually mean?

**Comment by octavius-1** [comment]
The methods that begin with “set” are configurations that apply for everything, that means that you will interact 10 different posts for every user.
The other method, interact_user_followers is an action, that means that it will interact 10 different user followers from every element of the list.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
