### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by ianjuma** [InstaPy/InstaPy#45]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 119: ordinal not in range(128) for some links

```log
--> Image Liked!
Traceback (most recent call last):
  File "./quickstart.py", line 19, in <module>
    .like_by_tags(['#dog', '#messi', '#cr7', 'top'], amount=100) \
  File "/home/synod/AT/cronos/InstaPy/instapy/instapy.py", line 271, in like_by_tags
    print('Invalid Page: ' + str(err))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 119: ordinal not in range(128)
```

**Comment by maxinedotdev** [comment]
This is probably because of the encoding of the console you are using. To set for example Powershell to UTF-8, write the following in the console.

`chcp 65001`

Hope that works!

**Comment by hariom282538** [comment]
This is a terminal encoding issue. 
Follow below mentioned steps:
1. Open CMD(for windows) 
2. Open directory (cd InstaPy)
3. Command: set PYTHONIOENCODING=UTF-8 
4. Execute this command every time before running python script.

Hope this works!

**Comment by tibor** [comment]
Hi @hariom282538,

when I use your solution under CentOS, Chrome crashes immediately when the script starts.
Do you know any other solution?

Kind regards

Tibor

**Comment by hariom282538** [comment]
Please share screenshot.

**Comment by tibor** [comment]
Hi,

attached you can find the screenshot:

![img_0571](https://cloud.githubusercontent.com/assets/3136416/25307341/da201e5a-279f-11e7-86f6-0c807aeab005.PNG)

**Comment by hariom282538** [comment]
Hey @tibor ,

First of all,This is not an encoding issue and i request my friend @timgrossmann  to look into this matter. Meanwhile you can check log here
"chromedriver.log"
.
Please execute with super user and have a look "
http://stackoverflow.com/questions/23653461/chrome-failed-to-start-on-centos-using-chromedriver2-9
".

Thanks,
Hariom Vashisth

**Comment by timgrossmann** [comment]
@tibor probably too low on RAM 😉

**Comment by hojabbr** [comment]
Just add these lines to `quickstart.py` and `instapy.py`:

```
# -*- coding: UTF-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

**Comment by suchendra-h** [comment]
I tried all solutions I still get this error. I am using Pycharm. Any suggestions?
