### ISSUE TITLE
Simulated Follow even when disabled

### ISSUE THREAD

**Issue by DuncanTLaw** [InstaPy/InstaPy#4502]
Hi all, having a problem with my code, where it simulates a follow or two every time I run it but I thought I disabled it?

`# imports
from instapy import InstaPy
from instapy import smart_run

# login
session = InstaPy(username='',
                  password='',
                  headless_browser=False)

# run sesh
with smart_run(session):
    
# parameters
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=False,
                                    max_followers=12000,
                                    max_following=1000,
                                    min_followers=25,
                                    min_following=25,
                                    #min_posts=6
                                    )
    session.set_skip_users(skip_private=True, skip_no_profile_pic=True)
    
# activity
    session.set_user_interact(amount=1, randomize=False, 
                              percentage=100, media='Photo')
    session.set_do_follow(enabled=False, percentage=0)
    session.set_do_like(enabled=True, percentage=100)
    session.set_comments([""])
    session.set_do_comment(enabled=True, percentage=100)
    session.interact_user_followers([''], amount=100, randomize=True)`

**Comment by fintzd** [comment]
I'm not sure I understand what the issue is here, could you give some more details?

**Comment by DuncanTLaw** [comment]
![image](https://user-images.githubusercontent.com/37959890/58914202-d343a700-8715-11e9-9581-ef2e5e613b39.png)
There is a simulated follow, just one, before the bot goes on about its business...

**Comment by dmfaria** [comment]
Put -1 in the percentage 
session.set_do_follow(enabled=False, percentage=-1)

The bot has a bug in the verification of the percentages.
