### ISSUE TITLE
View stories

### ISSUE THREAD

**Issue by 0x366** [InstaPy/InstaPy#4503]
Hello!

How to mark insta stories as seen ? I found a lot of implementations of downloading stories on github. But there is no implementation of "viewing" story.

May be someone knows the url of such request?

I found such code on php - https://github.com/mgp25/Instagram-API/blob/849f81b3032c0c495ef4619aa8e6c9332b228502/src/Request/Internal.php#L1372

**Comment by dmfaria** [comment]
Interesting feature request

**Comment by fintzd** [comment]
Would love this to happen!
