### ISSUE TITLE
wrong character appearing at the end of comments.

### ISSUE THREAD

**Issue by rnmhdn** [InstaPy/InstaPy#4504]
## Expected Behavior
Get the text "good one" in my comment.
## Current Behavior
Get the text "good one �" in my comment.
## InstaPy configuration
```
comments=[
    ...
    u"good one", 
    ...
]
session.set_do_comment(enabled=True, percentage=25)                                 
session.set_comments(comments)      
```
## This is what I get in the logs:
 --> Commented: b'good one'
### P.S.
don't worry about the u'' it's because I have some unicode comments also so I just put u before all my comment strings. the same thing happens if I don't have the u there.

I'm on archlinux, python 3.
`$ pip show selenium`
Name: selenium
Version: 3.141.0
Summary: Python bindings for Selenium
Home-page: https://github.com/SeleniumHQ/selenium/
Author: UNKNOWN
Author-email: UNKNOWN
License: Apache 2.0
Location: /home/aran/.virtualenvs/instapy/lib/python3.7/site-packages
Requires: urllib3
Required-by: instapy

And that character is:  U+FFFD : REPLACEMENT CHARACTER

**Comment by octavius-1** [comment]
You must be using firefox, right?

**Comment by rnmhdn** [comment]
@octavius-1 Yes I'm using firefox.

**Comment by rnmhdn** [comment]
Well, I don't really think this is an unimportant issue...
