### ISSUE TITLE
Chrome version must be between 70 and 73

### ISSUE THREAD

**Issue by gyrex** [InstaPy/InstaPy#4505]
I keep getting this error message:

ERROR [2019-06-03 00:00:16] [instagram-username]  Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.75,platform=Linux 4.19.38-sunxi64 aarch64)

**Comment by gyrex** [comment]
I found an older ChromeDriver v72.0.3626.121 and copied it into the assets folder and it's working now but I note that the current chromedriver version is v74 - is there any particular reason why instapy is limited to < v73?

**Comment by jeremycjang** [comment]
Is this part of the Instapy 0.5.0 update and will it affect RPi users (Pi only works with Chromium 65)? @timgrossmann
