### ISSUE TITLE
modify log settings.

### ISSUE THREAD

**Issue by rnmhdn** [InstaPy/InstaPy#4509]
Is it possible to disable the dercription logs while liking? it's really such a spam for me and I don't need it.

**Comment by Herrox** [comment]
Start Instapy in background or tmux or screen ?

**Comment by rnmhdn** [comment]
@Herrox I want the rest of the logs. I only don't want the description logs. description of post and page. it prints a huge text in my terminal which is pretty useless to me.

**Comment by rnmhdn** [comment]
I ended up removing this line from like_util:
`logger.info("Description: {}".format(image_text.encode("utf-8"))) `

**Comment by Herrox** [comment]
@aranmohyeddin Oh I see, great you made it! Maybe you should propose a new feature (PR) to be able to enable/disable such kind of logs :)

**Comment by rnmhdn** [comment]
does PR mean pull request? do you mean that I implement it and make a pull request? I can't do that very soon because I'm not familiar with the codebase at all yet.
