### ISSUE TITLE
run 3 account at the same time

### ISSUE THREAD

**Issue by spikerang** [InstaPy/InstaPy#451]
i have 3 accounts. if i run 3 programe at the same time with same computer, same ip, will i get banned?

**Comment by bardascat** [comment]
I'am also interested about this question...

**Comment by balakedev** [comment]
@bardascat , @spikerang 

I currently run 2 at a time, but I have 3 unique accounts that I run instapy on. I have done extensive research on this and this is what I have discovered:

1. Running multiple accounts from the same IP address is dangerous. Instagram looks at activity from IP addresses and if there is too much coming from the same IP address it will assume that there is suspicious activity at that locaton; ie a bot farm - this can lead to a shadowban

^^^ that being said, I've run 2 accounts, daily and the 3rd once every three days or so for almost 40 days now on the same computer and I haven't had a problem. Each account at a maximum likes 279 posts in total and normally passes around 300 as I have A LOT of banned words to keep the bot as accurate as possible to specific industries. 

2. The location of the IP address is important. if you have instapy running on an account that is regularly accessed in Melbourne, Australia, and the bot is being highly active from another geographical location (like Los Angeles) within an unreasonable time frame - this can also be seen as suspicious and can lead to a shadowban. 

There is evidence to suggest that instagram now allows a single account to be accessed by multiple devices, as Instagram is aware that is a driving force behind marketing for companies all over the world. 

What I have mentioned above is just what I've read and experienced. Could be totally inaccurate tho haha.

All the best

**Comment by bardascat** [comment]
@blakemmw - thanks for tbe reply.
Do you know if the "multiple accounts" problem can be avoided using some proxy servers ?
Or instagram would know that you are using proxy and ban your account. ? 
Any info on this one ?

**Comment by mathmorrison** [comment]
I want run raspberries 8 simultaneity together to ride the power shouldn't I get banned?

**Comment by RomeoJuliett** [comment]
Thanks for clearing that up Blakemmw. I was actually thinking of running multiple Ubuntu instances in order to make this happen properly. Good to know we can run a small amount from the same IP.

**Comment by wizarduk** [comment]
You would need more ram so if you wanted lots running it would cost you more mine is running 61% ram on 1GB ram so if i run two im maxed out...

**Comment by wizarduk** [comment]
Yes running two accounts is fine but all depends some ig bots you can run 10 on 1 account depending what its doing///

**Comment by bardascat** [comment]
Why would you want to run multiple instances of bot for one instagram
accont in the same time ?

**Comment by wizarduk** [comment]
@bardascat i changed that i mean two separate ig accounts it works fine with two but even having a few more is fine if you have some dedicated ip's....

**Comment by RomeoJuliett** [comment]
I run 2-3 different accounts at a time on my local machine from the same IP and have not had a problem so far. 

I have an Amazon Ubuntu instance where I run my personal account, but will probably attempt to run another on that same instance at the same time. Not sure how it'll work being SSH'd in to the same Ubuntu instance from 2 separate terminal windows, but we'll see.

**Comment by wizarduk** [comment]
@RomeoJuliett yeah that's good I use to run on the local machine but I wanted it up with a server so I don't need to worry about internet dropping out or powercuts I got a decent one cheap that I'm testing with two accounts at the moment... Yeah, thats the same what I'm doing 2 separate terminals will be adding another one to that...

**Comment by wizarduk** [comment]
@RomeoJuliett does it cost anything to use amazon do u get a dedicated ip ?

**Comment by RomeoJuliett** [comment]
@wizarduk costs me nothing right now. It's free for the first year and gives a designated IP depending on which location you select. For each new instance you spin up you get a new IP.

**Comment by wizarduk** [comment]
@RomeoJuliett Will it be free so no charge the whole year ?
So your getting a dedicated ip per ig account your using a bot with ?

**Comment by RomeoJuliett** [comment]
@wizarduk yes, it's free for the entire year as long as you don't go over a massive amount of traffic per month. It's something ridiculously high though. You'd have to run like 5 accounts 24 hours a day every single day and even then you probably wouldn't hit it.

**Comment by RomeoJuliett** [comment]
@wizarduk I haven't tried running multiple accounts on the same instance, but with each new instance you get a new IP so you could run individual accounts on an instance and each one would have their own IP

**Comment by wizarduk** [comment]
@RomeoJuliett the issue is amazon service is not a true private dedicated ip so would be risk of banning etc so think ill stick with my VPS

**Comment by wizarduk** [comment]
@RomeoJuliett are u running yours on cron ?

**Comment by RomeoJuliett** [comment]
@wizarduk No I don't have mine set up on Cron. I just remember to run it everyday.

**Comment by wizarduk** [comment]
@RomeoJuliett i would forget i have tested 1 account with cron that starts everyday so i don't have to do anything

**Comment by rzfzr** [comment]
I have just managed this, by importing multiprocessing, currently running 8 accounts on the same .py file. 5% CPU on 35w dual core but with quite high +-1500MB of RAM in headless mode so improvements to be made.
I'll clean it up and upload to the example folder if I can

**Comment by MrBeardedGuy** [comment]
@rzfzr Are you running all 8 under the same IP? 
I was trying to set up just some sessions under the proxy, not sure if it's possible https://github.com/timgrossmann/InstaPy/issues/1810

Also, would you mind if we take a look at the code??? Not sure how to set it up.

**Comment by unipython** [comment]
@rzfzr  Could you please upload your example files? Would be awesome to help out

**Comment by rzfzr** [comment]
> @rzfzr Could you please upload your example files? Would be awesome to help out

It seems that things changed around here, the example folder doesn't exist anymore, you can still get it from my fork, [here's ](https://github.com/rzfzr/InstaPy/blob/master/examples/multi-account.py) the older version of it with the credentials as lists, and [here's ](https://github.com/rzfzr/InstaPy/blob/master/examples/multiAccounts.py) the last version of it with the creds being loaded from a json file

**Comment by converge** [comment]
https://github.com/timgrossmann/InstaPy/tree/master/quickstart_templates

**Comment by SYasJ** [comment]
If used AWS, and it has its own IP address.. if we check Instagram from the phone would it not detect different IP addresses?
