### ISSUE TITLE
No element error? Newbie cracking head to seek solution.

### ISSUE THREAD

**Issue by kelvintoys93** [InstaPy/InstaPy#4512]
Okay guys, I am pretty noob in this. Just started using python for instapy a few weeks back. and I mainly used the "basic follow unfollow" code only. Today when I tried executing it, it failed with the error code below. I have done some light research on it and found that it could be due to the xpath error and the solution apparently can be found here: #2042. I am not sure if this is right solution and I don't know how to incorporate the solution too as I dont understand it. Appreciate if anyone could shed some light on the poor soul here.  

# imports
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = ''
insta_password = '' #removed my username and password for safety reason

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=1000,
                                    min_followers=45,
                                    min_following=77)

    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])

    # activities

    """ Massive Follow of users followers (I suggest to follow not less than
    3500/4000 users for better results)...
    """
    session.follow_user_followers(['travelandleisure'], amount=420,
                                  randomize=False, interact=False)

    """ First step of Unfollow action - Unfollow not follower users...
    """
    session.unfollow_users(amount=20, InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=601)

    """ Second step of Massive Follow...
    """
    session.follow_user_followers(['travelandleisure'], amount=420,
                                  randomize=False, interact=False)

    """ Second step of Unfollow action - Unfollow not follower users...
    """
    session.unfollow_users(amount=20, InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=601)

    """ Third step of Massive Follow...
    """
    session.follow_user_followers(['camayabali'], amount=220,
                                  randomize=False, interact=False)

    """ Clean all followed user - Unfollow all users followed by InstaPy...
    """
    session.unfollow_users(amount=150, InstapyFollowed=(True, "all"),
                           style="FIFO", unfollow_after=12 * 60 * 60,
                           sleep_delay=601)

Error that I am getting:
Traceback (most recent call last):
  File "C:\Users\My name\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\basic_follow_unfollow.py", line 50, in <module>
    randomize=False, interact=False)
  File "C:\Users\My name\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 3082, in follow_user_followers
    self.logfolder)
  File "C:\Users\My name\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\unfollow_util.py", line 1019, in get_given_user_followers
    logger, logfolder)
  File "C:\Users\My name\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\unfollow_util.py", line 747, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "C:\Users\My name\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\My name\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\My name\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\My name\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

**Comment by kelvintoys93** [comment]
any kind soul willing to help?

**Comment by ajgrover** [comment]
i think there's a bug with the library, it's not working for me either. here's a simplified example case:

```python
from instapy import InstaPy
from instapy.util import smart_run

session = InstaPy(username='', password='', headless_browser=True)

with smart_run(session):
    session.like_by_tags(['hashtag'], amount=3)
```

cc @timgrossmann @uluQulu

**Comment by alex-grover** [comment]
are you using the latest version of the library? usually this happens when instagram changes how their website looks and instapy isn't updated to know where the new buttons etc are.
