### ISSUE TITLE
With New Update "image not liked: more likes exists off maximum

### ISSUE THREAD

**Issue by Mikikk001** [InstaPy/InstaPy#4516]
Yesterday Instapy started to not follow people, but I wasn't blocked by Instagram so I updated Instapy and now the bot just search for tags and say: Image not liked: b"none"
Not liked this post! more likes exists off maximum limit at "number of likes of the post"

What can I do?

## Expected Behavior
Image Liked
User Followed
Followed
## Current Behavior
Image not liked: b"none"
Not liked this post! more likes exists off maximum limit at "number of likes of the post"

**Comment by socialsplice** [comment]
My accounts got banned too.. what is happening? Should we change the actions per hour? Sleep delay higher? I am already at 800..

**Comment by leaopedro** [comment]
Since last week Instagram is hunting automation behaviors and blocking the accounts they find suspicious. I would recommend stop running Instapy at least for some days, untill this get solved, as we don't have any sure about anything. Issue #4490 has a more in-depth discussion about it.

**Comment by Mikikk001** [comment]
So after my ban was disappeared I tried to run the bot but the same error occurred so I've tried to install a previous version of instapy and all seems to work. Any Idea?
