### ISSUE TITLE
Logs are only written after completion

### ISSUE THREAD

**Issue by wiardvanrij** [InstaPy/InstaPy#452]
I run the script on an ubuntu 16 server. 

My issue is that I cannot see the 'progress' in the logs. I start the command with 'nohup' so I can close the terminal. I would expect to see progress in the logs, rather they work a bit dodgy. Sometimes I get a little output (such as; 'started at xx-xxx time'). 

It is a bit unclear for me what the issue really is and it might even be my setup..

**Comment by converge** [comment]
It's fixed.
