### ISSUE TITLE
BUG in all percentage checks (when you set 0%, the bot will still comment,like or follow ocasionally)

### ISSUE THREAD

**Issue by dmfaria** [InstaPy/InstaPy#4524]
All the percentage checks in the form bellow have a small problem that can be bad in times of instagram blocks:
random.randint(0,100) <= self.follow_percentage
random.randint(0,100) <= self.comment_percentage
random.randint(0,100) <= self.like_percentage

All these checks should be changed to random.randint(1,100) <=...... otherwise, when you set 0% on your bot, you still have about 1% of chance of commenting, liking or following.

Explanation:  random.randint(0,100) returns 101 numbers (from 0 to 100), it should return only 100 numbers. So the percentage check will fail in the case when you set your bot to 0% and randint(0,100) returns zero.

**Comment by sionking** [comment]
you correct but we also have the flag.. do follow do likes...
