### ISSUE TITLE
interact_user_followers refuses to work for me

### ISSUE THREAD

**Issue by jeffdt52** [InstaPy/InstaPy#4526]
I LOVE THIS COMMUNITY. I'm so thankful to the creators and supporters of this tool. I'm using it to broadcast my art and without InstaPy, I wouldn't be nearly as motivated today doing it. 
I have lurked the forums for half a year looking for a solution to get this feature to work. 

I have seen a variety of failures, including error reports of not being able to detect the element and syntax errors within the code. I've rotated my configurations a number of ways to bootstrap a solution but can't seem to figure it out. So I'm turning to the experts:

I should mention I'm on a Mac.

interact_user_followers successfully goes to user's profile, performs 5 'Simulated follows' and reports that its grabbed 264 followers. 

Then it starts returning some strange messages:

> INFO [2019-06-08 17:45:45] [wanderbread_sandwich]   line 2748 
> INFO [2019-06-08 17:45:45] [wanderbread_sandwich]  User 'rightengel' [1/264]
> INFO [2019-06-08 17:45:45] [wanderbread_sandwich]   line 2752 
> INFO [2019-06-08 17:45:49] [wanderbread_sandwich]  User: 'rightengel'  |> followers: 243  
> |> following: 584  |> relationship ratio: 0.41

Then it ends the session and returns this error message

> Traceback (most recent call last):
>   File "joshwork_influencers.py", line 82, in <module>
>     session.interact_user_followers(['chadgoesdeep'], amount=300, randomize=False)
>   File "/Users/jeffstreitmatteriv/InstaPy/instapy/instapy.py", line 2755, in interact_user_followers
>     self.logger.info('validation_user_call = ' + validation)
> TypeError: can only concatenate str (not "bool") to str

Here it is in the [silicony] flesh
![error report](https://user-images.githubusercontent.com/23081968/59152781-68e27d80-8a19-11e9-8931-25ee0c05bb5d.png)

**My Configuration:**
```

session.set_quota_supervisor(enabled=True,
                                 #sleep_after=["likes", "follows", "comments_d"],
                                 sleep_after=["likes"],
                                 stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(200, 800),
                                 peak_comments=(160, 250),
                                 peak_follows=(100, 500))

    #session.set_user_interact(amount=1, randomize=False, percentage=100)

    # activity
    session.set_user_interact(amount=2, randomize=False, percentage=50)
    session.set_do_follow(enabled=True, percentage=80, times=1)
    session.set_do_comment(enabled=True, percentage=70)
    session.set_comments(commentsListCheer,media='Photo')
    session.set_do_like(enabled=True, percentage=100)
    session.interact_user_followers(['myUser'], amount=300, randomize=False)


```

**Comment by lezlea** [comment]
Hey Jeff,
Sorry I'm not sure of the 'strange' messages or the simulated problems you're mentioning as I'm not versed with that code and I'm not sure what it's supposed to do... I presume others who know more would need more info to diagnose.

But in terms of the error you've highlighted, as it states it's a "type" error which means the variable trying to be used is the wrong type.  The logger can only print out (display) strings.

bool means boolean which is True or False
str means string

So the line above is where the error is coming from, line 2755 in InstaPy.py;
**self.logger.info(‘validation_user_call = ‘ + validation)**

So to change the variable validation into a string you can do the following and wrap the variable in a str() 

str(validation)

_**self.logger.info(‘validation_user_call = ‘ + str(validation))**_


I'm not sure if this is the answer you're looking for but hopefully it helps a little.
Thanks,
Lezlea
