### ISSUE TITLE
like_by_tags not skip top posts & logout

### ISSUE THREAD

**Issue by dopa1213** [InstaPy/InstaPy#4527]
## Expected Behavior
skip to posts
Continuously action like

## Current Behavior
not skip top posts
Logout when finish top posts like

## InstaPy configuration
instapy 0.5.0
instapy-chromedriver 2.46

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  )

with smart_run(session):
    """ Activity flow """
    # settings
    session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=1500,
                                        min_followers=50,
                                        min_following=0)
    session.set_quota_supervisor(enabled=True, peak_likes=(100, None))
    session.set_dont_like(words)
    session.like_by_tags(tags, amount=random.randint(25,35))

**Comment by alex-grover** [comment]
i think there's a bug with the library, it's not working for me either. here's a simplified example case:

```python
from instapy import InstaPy
from instapy.util import smart_run

session = InstaPy(username='', password='', headless_browser=True)

with smart_run(session):
    session.like_by_tags(['hashtag'], amount=3)
```

cc @timgrossmann @uluQulu

**Comment by DemonionFF** [comment]
As a work around we can add top posts count to expected posts.
Expected to like - 4 posts, top posts 9, so setting 13 posts to like will work. At least while this function will be fixed.
