### ISSUE TITLE
Unfollow end prematurelly 

### ISSUE THREAD

**Issue by jeffreylm** [InstaPy/InstaPy#453]
Hello I made the following script, but after it unfollows 19 people it neatly ends the session.
Why is it ending prematurly? 

from instapy import InstaPy
import os
session = InstaPy(username='login', password='pass')
session.login()
session.set_do_follow(enabled=True, percentage=97, times=1)
##session.set_upper_follower_count(limit = 6500)
#session.set_dont_like('nsfw')
#session.set_dont_like('#exactmatch', '[startswith', ']endswith', 'broadmatch')
session.unfollow_users(amount=500)

#session.follow_by_list(accs, times=1)

session.end()

**Here is the CMD line:**

Logged in successfully!
Number of people followed automatically remaining: 776
--> Ongoing Unfollow 1, now unfollowing: b'amar_tafilovic'
--> Ongoing Unfollow 2, now unfollowing: b'super_car_heaven_'
--> Ongoing Unfollow 3, now unfollowing: b'la2natural'
--> Ongoing Unfollow 4, now unfollowing: b'lusinelusarts'
--> Ongoing Unfollow 5, now unfollowing: b'khfitfam'
--> Ongoing Unfollow 6, now unfollowing: b'nicksforzarealty'
--> Ongoing Unfollow 7, now unfollowing: b'kymu.motivation'
--> Ongoing Unfollow 8, now unfollowing: b'roger.despres'
--> Ongoing Unfollow 9, now unfollowing: b'biene141291'
--> Ongoing Unfollow 10, now unfollowing: b'trendynclassy_acce
sleeping for about 10min
--> Ongoing Unfollow 11, now unfollowing: b'lizzy.pg'
--> Ongoing Unfollow 12, now unfollowing: b'chrisprandy'
--> Ongoing Unfollow 13, now unfollowing: b'faits.n.quotes'
--> Ongoing Unfollow 14, now unfollowing: b'mindsetleader'
--> Ongoing Unfollow 15, now unfollowing: b'55totalpackage55'
--> Ongoing Unfollow 16, now unfollowing: b'sorelleshoes'
--> Ongoing Unfollow 17, now unfollowing: b'babymugglemom'
--> Ongoing Unfollow 18, now unfollowing: b'karrcomedy'
--> Ongoing Unfollow 19, now unfollowing: b'roninisgolden'
--> Total people unfollowed : 19

Session ended
-------------

Thank you in advance,
Jeffrey

**Comment by sionking** [comment]
I think it does not scroll down, I see it im my unfollow, only for followed users "onlyInstapyFollowed=True" so it only check the first page but not scroll down.

**Comment by jeffreylm** [comment]
I tried it with and without. Same result of it stopping. So I added the unfollow command twice and it did 2 times unfollow 19 people, then ends the session. It does scroll down.

Did try it to see what it does?

**Comment by sionking** [comment]
It will scroll down if an unfollow user appear on the screen then pressing the unfollow button will scroll down a bit, if  no user show on screen it will stop.
This is the behiver I see, Hope to be fixed soon.

**Comment by jeffreylm** [comment]
Thank you Sionking for taking the time to try it out also.

**Comment by jeffreylm** [comment]
Even when I grab the scroll bar and drag it down so that it has a long list on screen, when it reaches 19, it stops and ends the session.

Greetings,
Jeffrey

**Comment by jeffreylm** [comment]
When I put 3 of these in the script : session.unfollow_users(amount=500)
The script executes in three times, but when I add 5 in total. The script gives command errors. And when I return it back to 3 and execute, the same error keep coming. But once I reduce it back to 1, execute then increase back to 3. It works normal once again.

Maybe someone knows what is going on.

**Comment by jeffreylm** [comment]
Bear in mind with the following I changed nothing, just kept retyping start.bat
So after the script executing like above for a few times (10-12) 

It logins in then this error below shows in the prompt

**On typing start.bat it gave this error:**

C:\Users\jeffrey\Documents\GitHub\InstaPy>py quickstart.py
Logged in successfully!
Number of people followed automatically remaining: 642
Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    session.unfollow_users(amount=500)
  File "C:\Users\jeffrey\Documents\GitHub\InstaPy\instapy\instapy.py", line 530, in unfollow_users
    self.automatedFollowedPool)
  File "C:\Users\jeffrey\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 52, in unfollow
    dialog = browser.find_element_by_xpath('/html/body/div[3]/div/div[2]/div/div[2]')
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line
    'value': value})['value']
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line
    self.error_handler.check_response(response)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", li
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","select
  (Session info: chrome=60.0.3112.78)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by jeffreylm** [comment]
Now the script doesn't execute anymore. It logins pulls up the unfollow screen, then prints the following on screen before quiting in the command prompt. Just for clarity, I have never tickerd in the code, only added the lines needed in the quickstart.py 

Before the error below the script worked and would execute 19 unfollows and end prematurly, but other than that it worked.

Logged in successfully!
Number of people followed automatically remaining: 642
Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    session.unfollow_users(amount=500)
  File "c:\Users\jeffrey\Documents\GitHub\InstaPy\instapy\instapy.py", line 530, in unfollow_users
    self.automatedFollowedPool)
  File "c:\Users\jeffrey\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 52, in unfollow
    dialog = browser.find_element_by_xpath('/html/body/div[3]/div/div[2]/div/div[2]')
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div/div[2]/div/div[2]"}
  (Session info: chrome=60.0.3112.78)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by jeffreylm** [comment]
Now the script doesn't execute anymore. It logins pulls up the unfollow screen, then prints the following on screen before quiting in the command prompt. Just for clarity, I have never tickerd in the code, only added the lines needed in the quickstart.py 

Before the error below the script worked and would execute 19 unfollows and end prematurly, but other than that it worked.

Logged in successfully!
Number of people followed automatically remaining: 642
Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    session.unfollow_users(amount=500)
  File "c:\Users\jeffrey\Documents\GitHub\InstaPy\instapy\instapy.py", line 530, in unfollow_users
    self.automatedFollowedPool)
  File "c:\Users\jeffrey\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 52, in unfollow
    dialog = browser.find_element_by_xpath('/html/body/div[3]/div/div[2]/div/div[2]')
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div/div[2]/div/div[2]"}
  (Session info: chrome=60.0.3112.78)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by mbancha** [comment]
I'm now having what seems to be the exact same problem:

Traceback (most recent call last):
  File "C:\Users\Matt\instapy\UNFOLLOW.py", line 13, in <module>
    session.unfollow_users(amount=10, onlyInstapyFollowed = True )
  File "C:\Users\Matt\instapy\instapy\instapy.py", line 530, in unfollow_users
    self.automatedFollowedPool)
  File "C:\Users\Matt\instapy\instapy\unfollow_util.py", line 52, in unfollow
    dialog = browser.find_element_by_xpath('/html/body/div[3]/div/div[2]/div/div[2]')
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 313, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 791, in find_element
    'value': value})['value']
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div/div[2]/div/div[2]"}
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.15063 x86_64)

**Comment by JMuffin** [comment]
There is a simple solution that I tried:
In instapy/unfollow_util.py in line 52 change dialog = ... to
dialog = browser.find__element_by_xpath("//div[contains(@class, '_4gt3b')]")

It should work ;)

**Comment by jeffreylm** [comment]
@JMuffin I am not a programmer, so what does this new re-write say to do?
What got you to this re-write?
Just trying to understand, starting to learn Python.

Also why is it that it just all of a sudden started acting this way, with no changes done on my side?

**Comment by jeffreylm** [comment]
@JMuffin the modification did not work. Here is the new error

Logged in successfully!
Number of people followed automatically remaining: 1151
Traceback (most recent call last):
  File "quickstart.py", line 10, in <module>
    session.unfollow_users(amount=20)
  File "c:\Users\jeffrey\Documents\GitHub\InstaPy\instapy\instapy.py", line 530, in unfollow_users
    self.automatedFollowedPool)
  File "c:\Users\jeffrey\Documents\GitHub\InstaPy\instapy\unfollow_util.py", line 52, in unfollow
    dialog = browser.find__element_by_xpath("//div[contains(@Class, '_4gt3b')]") #dialog = browser.find_element_by_xpath('/html/body/div[3]/div/div[2]/div/div[2]')
AttributeError: 'WebDriver' object has no attribute 'find__element_by_xpath'

**Comment by jeffreylm** [comment]
What I just want to do is unfollow atleast 800 people so I can get my follow/followers ratio nearer to each other.

As to the follow pool, I just want it to unfollow people wether they are in the pool or not.

**Comment by sionking** [comment]
find_element_by_xpath instead of find__element_by_xpath

**Comment by sionking** [comment]
jeffreylm try captivate for IOS to unfollow, it has a white list and many other features.

**Comment by jeffreylm** [comment]
@sionking I am on android, do you have a solution for that platform?

**Comment by jeffreylm** [comment]
@sionking in your comment above about the xpath, you wrote the same thing twice. Can you rewrite what you were trying to say, also I'm not a programmer so could you write it out clearly what you were suggesting I do?

**Comment by sionking** [comment]
jmuffin seggested replace line to this line:
dialog = browser.find__element_by_xpath("//div[contains(@Class, '_4gt3b')]")
but he has a typo, extra _, __ instaed of _

Anyway I tried it and it doesnt work also.
I am not familiar with selenium and have no time to learn, soI have no idea of this code.

Sion.

**Comment by sionking** [comment]
please try:
-    dialog = browser.find_element_by_xpath('/html/body/div[3]/div/div[2]/div/div[2]')
 +    dialog = browser.find_element_by_xpath('/html/body/div[4]/div/div[2]/div/div[2]')

This works for me

**Comment by sionking** [comment]
https://github.com/timgrossmann/InstaPy/pull/460/commits/a61c74286b766955a87e54381de1e27a37e4fe5a

**Comment by jeffreylm** [comment]
@sionking It worked!!!!!!

Thank you, really. I am starting to see that others are experiencing the same problem, and it won't surprise me if this problem resurfaces. I take it tim is looking for a better solution. Because with out the unfollow feature, the follow feature is kind of useless to a certain degree.

Do you think you have a quick fix for the issue of it conly doing 19 unfollows eventhough I specified 500?

**Comment by jeffreylm** [comment]
@sionking do you also have the issue that it only unfollows 19?

**Comment by andresuman** [comment]
Well, i think its not working well.
I'm trying to unfollow:
session.unfollow_users(amount=1000, onlyInstapyFollowed = True)

Number of people followed automatcally raimaining: 4598
The result was random numbers of unfollow for 3 or 4 times... and now the result is always 0 unfollows and End Session.

**Comment by fegomess** [comment]
im having the same message. I follow almost 900 people, but it keep saying that there is 0 people to unfollow how is it possible?
