### ISSUE TITLE
[Features Suggestion] - dont comment base on caption

### ISSUE THREAD

**Issue by AKwoKWH** [InstaPy/InstaPy#4532]
You definitely dont want to comment on a phone which is expressing something bad.
If someone post a pic on instagram saying that he/she got an accident an in a hospital or  someone dead or broken up a relationship.  you surely dont want to comment "Wow!! Great!"
or "Nice~~ I like it =]"

Therefore we need something stop the action.
This is what I want to suggest - a stop word in caption.

We do have something similar for like "set_dont_like".
Why dont extend it to comment ?

```python
session.set_dont_like(['rip', 'r.i.p', 'accident'])
session.set_dont_comment(['rip', 'r.i.p', 'accident'])
```

**Comment by fintzd** [comment]
I think that would be great too, also posted about this.

Any ways this could happen @timgrossmann ? :)
