### ISSUE TITLE
Problems on Login - creating cookie...

### ISSUE THREAD

**Issue by Javi4** [InstaPy/InstaPy#4533]
## Expected Behavior
Trying to log in to a new account from a remote server with ubuntu and headless_browser=True. With the two factor authentication disabled.
## Current Behavior
"CRITICAL [2019-06-11 06:42:42] [xxxxxxxxx]  Wrong login data!"
## InstaPy configuration
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True,
                  multi_logs=True)

**Comment by SeoMinbong** [comment]
Try it not headless_browser to see what show up.

**Comment by Javi4** [comment]
This is whithout headless_browser

https://imgur.com/a/A9lg0d8#7eMG2RK

**Comment by sydney-d** [comment]
Same here,

After entering security code I'm redirected to the home screen.
Instapy 0.4.3

**Comment by zuest** [comment]
im getting the same error any suggestions?

**Comment by mikediachenko** [comment]
Chrome driver version?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zuest** [comment]
google-chrome --version
Google Chrome 75.0.3770.80

**Comment by zuest** [comment]
Using built in instapy-chromedriver executable (version 2.46)

**Comment by zuest** [comment]
running on digital ocean clone the quick repo and ran..

USER:~/instapy-quickstart# python3 quickstart.py 

 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-06-12 21:06:42] [USERNAME]  Using built in instapy-chromedriver executable (version 2.46)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-06-12 21:06:43] [USERNAME]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...

........................................................
CRITICAL [2019-06-12 21:07:43] [USERNAME]  Wrong login data!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2019-06-12 21:07:47] [USERNAME]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING XXX users & had XXX FOLLOWERS
[Session lasted 1.07 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-06-12 21:07:47] [USERNAME]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by zuest** [comment]
@timgrossmann can you please take a look it this bro?

**Comment by Javi4** [comment]
Same problem for my trying to run in AWS ubuntu instance

**Comment by papillon-ux** [comment]
Same on raspbian, while I was running Instapy without problem till then. Maybe Instagram has changed his code.

**Comment by JustAskMarina** [comment]
The same is happening to me on Win10. I was able to access Instagram on Chrome manually but the bot wasn't, then I tried deleting all Instagram related cookies on the browser and I'm not able to access manually via Chrome anymore. Gonna sent a ticket today to facebook.
Have you received lately email notifications on suspicious login attempt even for your own logins? The person I've set up this Instapy version naively told it wasn't legitimate login and since then all troubles began. The same was happening to my personal set up but I never told those access weren't mine, so I was able to unlock the situation entering the security code received by email after few tries to manually log in while Instapy was running.

**Comment by papillon-ux** [comment]
Everything went back to normal for me, I didn't change the code or touched anything.

**Comment by zuest** [comment]
my for my case the issue still remains...

**Comment by RiboPg** [comment]
> my for my case the issue still remains...

for me, too....

**Comment by danniefraim** [comment]
I'm getting the same error. On an AWS VM using headless browser and using a proxy server. I have no problems logging in manually through an incognito browser window. Here's a more complete log extract:

```OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-06-13 12:21:09] [danniefraim]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

...........................................................
CRITICAL [2019-06-13 12:22:14] [danniefraim]  Wrong login data!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''```

**Comment by JustAskMarina** [comment]
1 out of 3 bots (the first problematic one) that were having troubles is now working as it's supposed to. The other 2 keeps requiring manually entering the security code sent by email, but this makes me think we just have to wait that Instagram deals with their things.
Even though I wanna point out the message "Cookie file not found" is still there and I don't know if this is how the bot should be or not.

**Comment by carsonmclarson** [comment]
Having the same issue but with an account I've been running for months.

**Comment by danniefraim** [comment]
I have done some further troubleshooting on this. I downloaded my bot to my local computer to try to see what causes this issue. What I've found so far is that if I run it in headless mode with proxy settings on, this error is triggered. If I just remove the proxy settings but keep headless turned on, it works - even though I'm currently behind the same router as the proxy server and I'm using the same IP address.

So my current theory is that this is caused by Instagram detecting my proxy and somehow objecting to it. I am running Squid and I'm using it in "stealth mode", meaning I've configured it to strip all the proxy headers and try to hide its own existence, but maybe I'm not doing a good enough job of that. I'll report back when I know more.

**Comment by danniefraim** [comment]
Okay, so I found what was causing this error for me, and it's actually a bit embarrassing... The computer I was running my proxy server on was turned off. It had failed to reboot after a power outage. So the proxy server could not be reached, and this led to the very cryptic and misleading error messages I got.

As soon as I fired up the computer and the proxy again, everything was working just fine. So to everyone else who's having this problem: check if it might be a proxy or connection issue.

**Comment by JustAskMarina** [comment]
All my 3 setups are now working but we still have to sometime enter the email security code because of that "Cookie not found". No proxy, PCs with dynamic IP, Chromium and Chromedriver version 75. These bots were already working for months with these settings.

**Comment by zuest** [comment]
i'd like update my current state: 

I followed this tutorial and luckily, i got it working..XD

https://www.digitalsupply.co/using-open-source-software-to-build-your-instagram-followers/

just one thing to notice in this tutorial,

do 
"sudo apt-get -f install" before "sudo dpkg -i google-chrome-stable_current_amd64.deb" and simply just modify quickstart.py to your needs.

My setup: 5 dollar digital ocean droplet ubuntu 18.04 x64 (running on singapore server if that matters)


Hope it works with you guys & please share your feedback.

**Comment by JustAskMarina** [comment]
I've solved it downgrading Chrome to version 73, the last supported by the last version of instapy-chromedriver. Now is perfectly working on every PC.

**Comment by 4taras4** [comment]
has the same problem only in one account how to fix it, any idea?

**Comment by zuest** [comment]
@4taras4 you can try my solution and @Belsea solution.

**Comment by azmankristjan** [comment]
> I've solved it downgrading Chrome to version 73, the last supported by the last version of instapy-chromedriver. Now is perfectly working on every PC.

Hi How did you efficiently downgraded Chrome? I cant find any old versions. Is there a website with instructions?

**Comment by JustAskMarina** [comment]
I found it on filepuma. After the installation immediately close the window and go to the installation folder/Update and rename the updater exe. Is quite an ugly solution but the only one that worked for me.

**Comment by AKwoKWH** [comment]
same problem

**Comment by 4taras4** [comment]
just try in another day and now it's works
