### ISSUE TITLE
proxy error in Instapy

### ISSUE THREAD

**Issue by meladbader** [InstaPy/InstaPy#4535]
when i use proxy and run code show to me this error :

Traceback (most recent call last):
  File "C:\Users\user\Desktop\instagrambots\other\test.py", line 14, in <module>
    headless_browser=False)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 262, in __init__
    self.proxy_address and self.proxy_port > 0) or \
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by fintzd** [comment]
Did you setup the proxy IP and port too?

**Comment by meladbader** [comment]
> Did you setup the proxy IP and port too?

[#1531](https://github.com/timgrossmann/InstaPy/pull/1531)

I noticed that I did not it and I have done this now and I added everything that exists on this page but I have a new problem and it is :

chrome_options.add_argument('user-agent={user_agent}'.format(user_agent=user_agent))
                                                                                       ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by meladbader** [comment]
@timgrossmann Help please
