### ISSUE TITLE
Losing selenium session when using Quota Supervisor

### ISSUE THREAD

**Issue by chatelp** [InstaPy/InstaPy#4537]
## Expected Behavior
InstaPy able to resume activity after hitting quota

## Current Behavior

I'm using latest version of InstaPy Docker with external Selenium in another container.

Everything works fine, until quota supervisor reaches a quotient, then instapy is put to sleep for the rest of the hour. When it comes back, it can't find any active session in selenium, then crashes.

I checked both Instapy and Selenium logs, and indeed, the current session is being removed (automatically) from Selenium after 30+ minutes, befores Instapy has finished sleeping from quota supervisor. 

**Log from Instapy**

`INFO [2019-06-11 07:25:56] [xxxx]  Quota Supervisor: hourly server calls reached quotient!	~going to sleep 45 minutes long
	take a grey tea break? :>
/usr/local/lib/python3.7/site-packages/plyer/platforms/linux/notification.py:68: UserWarning: The Python dbus package is not installed.
Try installing it with your distribution's package manager, it is usually called python-dbus or python3-dbus, but you might have to try dbus-python instead, e.g. when using pip.
  warnings.warn(msg)
/usr/local/lib/python3.7/site-packages/plyer/platforms/linux/notification.py:72: UserWarning: notify-send not found.
  warnings.warn("notify-send not found.")
ERROR [2019-06-11 08:11:16] [xxxx]  Error occurred while deleting cookies from web browser!
	b'Message: No active session with ID 489ab9a813863582239d99fb4351c7cd\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/instapy/util.py", line 1680, in smart_run
    yield
  File "/code/docker_quickstart.py", line 132, in job_tags
    amount=random.randint(10, 25), interact=True)
  File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 1907, in like_by_tags
    self.user_interact_media)
  File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 2079, in like_by_users
    total_liked_img)
  File "/usr/local/lib/python3.7/site-packages/instapy/like_util.py", line 684, in like_image
    liked_elem = browser.find_elements_by_xpath(unlike_xpath)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 410, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: No active session with ID 489ab9a813863582239d99fb4351c7cd
`

**Log from Selenium**
`06:57:59.270 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver 75.0.3770.8 (681f24ea911fe754973dda2fdc6d2a2e159dd300-refs/branch-heads/3770@{#40}) on port 11881
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1560236279.347][SEVERE]: bind() failed: Cannot assign requested address (99)
06:58:01.856 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
06:58:01.905 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 489ab9a813863582239d99fb4351c7cd (org.openqa.selenium.chrome.ChromeDriverService)
07:55:59.880 INFO [ActiveSessions$1.onStop] - Removing session 489ab9a813863582239d99fb4351c7cd (org.openqa.selenium.chrome.ChromeDriverService)
`
## Possible Solution (optional)

My guess is that there is a default timeout on selenium sessions (_webdriver.server.session.timeout_ maybe?). Maybe being able to extend it from docker environment would manage the problem?

## InstaPy configuration

`
import yaml
import os
import random
from instapy import InstaPy
from instapy.util import smart_run
from instapy import set_workspace
from instapy import get_workspace
import schedule
import time

"""
Loading data
"""
current_path = os.path.abspath(os.path.dirname(__file__))
data = yaml.safe_load(open("%s/data.yaml" % (current_path)))

insta_username = data['username']
insta_password = data['password']
friendlist = data['friendlist']
hashtags = data['hashtags']

#path to your workspace
set_workspace(current_path)

"""
Generating 5 comments built with random selection and amount of emojis from 
characters
"""
comments = ['Nice shot! @{}',
        'Awesome work! @{}',
        'Cool capture @{}',
        'Just incredible. And very original too!',
        'Love what you did here @{}',
        'Love your art @{}',
        'This really looks amazing, congrats @{}',
        'Nice capture you got here',
        'Really beautiful, love it']
characters = [u'👍', u'📸', u'😃', u'😎', u'👏', u'🙌', u'✌️', u'💪', u'👌', u'😺']
for comment in range(5):
    comment = ''.join(random.sample(characters, random.randint(3, 6)))
    comments.append(comment)

"""
Like posts in Tags
"""
dont_likes = ['sex', 'nude', 'naked', 'beef', 'pork', 'seafood',
              'egg', 'chicken', 'cheese', 'sausage', 'lobster',
              'fisch', 'schwein', 'lamm', 'rind', 'kuh', 'meeresfrüchte',
              'schaf', 'ziege', 'hummer', 'yoghurt', 'joghurt', 'dairy',
              'meal', 'food', 'pancake', 'cake', 'dessert',
              'protein', 'essen', 'mahl', 'breakfast', 'lunch',
              'dinner', 'turkey', 'truthahn', 'plate', 'bacon',
              'sushi', 'burger', 'salmon', 'shrimp', 'steak',
              'schnitzel', 'goat', 'oxtail', 'mayo', 'fur', 'leather',
              'cream', 'hunt', 'gun', 'shoot', 'slaughter', 'pussy',
              'breakfast', 'dinner', 'lunch' 'dick', 'squirt', 'gay', 'homo', 
              '#fit', '#fitfam', '#fittips', '#abs', '#kids', '#children', '#child',
              'nazi', 'promoter', 'jew', 'judaism', 'muslim', 'islam', 'bangladesh',
              'hijab', 'niqab', 'farright', 'rightwing', '#conservative', 'death', 'racist']

def job_tags():
    session = InstaPy(username=insta_username,
                  password=insta_password,
                  selenium_local_session=False,
                  disable_image_load=True,
                  multi_logs=False)
    session.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub')

    with smart_run(session):    
        # settings
        session.set_relationship_bounds(enabled=True,
                                        max_followers=15000)

        session.set_dont_include(friendlist)
        session.set_dont_like(dont_likes)

        session.set_user_interact(amount=2, randomize=True, percentage=60)
        session.set_do_follow(enabled=False)
        session.set_do_like(enabled=True, percentage=80)

        if data['do_comments']:
            session.set_comments(comments)
            session.set_do_comment(enabled=True,
                               percentage=25)

        """
        Setting quota supervisor
        """
        session.set_quota_supervisor(enabled=True,
                                 sleep_after=["server_calls_h"],
                                 sleepyhead=True,
                                 stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(100, 800),
                                 peak_follows=(10, None),
                                 peak_unfollows=(10, 200),
                                 peak_server_calls=(500, None))

        """
        Setting smooth behavior
        """
        session.set_simulation(enabled=True,
                           percentage=66)
        session.set_action_delays(enabled=True,
                              like=3,
                              comment=10,
                              follow=4.17,
                              unfollow=28)

        """
        Setting user bounderies
        """
        session.set_dont_include(friendlist)
    
        #session.set_blacklist(enabled=True,
        #                 campaign='blacklist')
        #session.set_relationship_bounds(enabled=True,
        #                            potency_ratio=-1.21,
        #                            delimit_by_numbers=True,
        #                            max_followers=99999999,
        #                            max_following=5000,
        #                            min_followers=2000,
        #                            min_following=10)

        """
        Run
        """
        session.like_by_tags(random.sample(hashtags, 10),
                             amount=random.randint(10, 25), interact=True)

"""
Like last two posts from friendlists
"""

def job_friends():
    if data['friends_interaction']:
        friends = InstaPy(username=insta_username,
                          password=insta_password,
                          selenium_local_session=False,
                          disable_image_load=True,
                          multi_logs=False)
        friends.set_selenium_remote_session(
            selenium_url='http://selenium:4444/wd/hub')
        with smart_run(friends):
            friends.set_relationship_bounds(enabled=False)
            friends.set_skip_users(skip_private=False)
            friends.set_do_like(True,
                                percentage=100)
            friends.interact_by_users(friendlist,
                                      amount=2,
                                      randomize=False)

job_tags()
job_friends()

schedule.every().day.at("08:02").do(job_tags)
schedule.every().day.at("16:05").do(job_tags)

schedule.every().day.at("12:05").do(job_friends)
schedule.every().day.at("22:10").do(job_friends)

while True:
  schedule.run_pending()
  time.sleep(10)

`

**Comment by InfraRedApple** [comment]
Check out #4538 for an abstract idea of how to fix your issue. They may be related. Currently I have only submitted a fix for the Mac. But the same concepts apply to Windows and Raspberry Pi.

**Comment by chatelp** [comment]
> Check out #4538 for an abstract idea of how to fix your issue. They may be related. Currently I have only submitted a fix for the Mac. But the same concepts apply to Windows and Raspberry Pi.

Thanks for your answer. I'm afraid these issues are not directly related. In my case, it looks like a "normal" behavior of Selenium which closes unused sessions. And I was able to track the cause of the error/exception. What I don't understand is why other people would not encounter the same problem, so there's still a possibility it's a problem with my configuration...
