### ISSUE TITLE
Interact user followers not working 

### ISSUE THREAD

**Issue by sp3nc3r813** [InstaPy/InstaPy#4539]
## Expected Behavior

# get a session!
session = InstaPy(username=insta_username,
                 password=insta_password,
                 headless_browser=True,
                 multi_logs=True)

# let's go! :>
with smart_run(session):
   # general settings
   session.set_blacklist(enabled=True, campaign='test')

session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
session.set_do_follow(enabled=False, percentage=70)
session.set_do_like(enabled=True, percentage=70)
session.set_comments(["Cool", "Super!"])
session.set_do_comment(enabled=True, percentage=80)
session.interact_user_followers(['natgeo'], amount=10, randomize=True)
## Current Behavior
Currently pulls the user info but traceback error happens instantly 

ANY HELP???

**Comment by huy41** [comment]
Try headless_browser=False. 
I also get an error when I set it to True for some reason.

**Comment by sp3nc3r813** [comment]
O [2019-06-13 10:20:26] [x]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-06-13 10:20:26] [x]  Saving account progress...
INFO [2019-06-13 10:20:29] [x]  User 'rosewinemansion' [1/1]
**********************************************************************
If raising an issue, please also upload the file located at:
C:\Users\x\AppData\Local\Temp\20190613-102059.html
**********************************************************************

INFO [2019-06-13 10:21:01] [x]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 867 users & had 5768 FOLLOWERS
[Session lasted 47.31 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-06-13 10:21:01] [x]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



still getting an error

**Comment by giansimo** [comment]
Same bug...no errors display, but the bot crash!
