### ISSUE TITLE
session.set_action_delays do not work

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#4540]
Hi guys... recently got banned on Instagram because - 
session.set_action_delays(enabled=True,
                           like=90) setting started to get completely ignored.

Before it would rest for 90 seconds after liking. Now - it just going non stop... Did that get broken somehow?

Running latest version of instapy. Been working fine untill about 10 days ago.

**Comment by pneumokoniose** [comment]
Same here

**Comment by Tachenz** [comment]
For now I am just using sleep delay in like util py again, but that is obviously not ideal - as it will be the same for all accounts running from the same installation

**Comment by billidani7** [comment]
Same here on a raspberry pi 3+

**Comment by Svmurvj** [comment]
I can confirm that 

Here is how I set that: 
**session.set_action_delays(enabled=True, like=30, follow=30, random_range=(80, 140))**

So follow delays should be:

- min 30s * 80% = 24s
- max 30s * 140% = 42s

Here is peace from log:

INFO [2019-06-18 11:52:30]   Ongoing Follow [25/42]: now following 'x'...
INFO [2019-06-18 11:52:32]   User: 'x'  |> followers: 62  |> following: 306  |> relationship ratio: 0.2
INFO [2019-06-18 11:52:40]   --> Followed 'b'x''!
INFO [2019-06-18 11:52:40]   --> x added to blacklist for z campaign (action: followed)
INFO [2019-06-18 11:52:46]   Follow per user: 24  |  Total Follow: 24

INFO [2019-06-18 11:52:46]   Ongoing Follow [26/42]: now following 'y'...
INFO [2019-06-18 11:52:51]   User: 'y'  |> followers: 192  |> following: 367  |> relationship ratio: 0.52
INFO [2019-06-18 11:52:58]   --> Followed 'b'y''!
INFO [2019-06-18 11:52:58]   --> y added to blacklist for z campaign (action: followed)
INFO [2019-06-18 11:53:06]   Follow per user: 25  |  Total Follow: 25

I see the time difference between    Followed 'b'x''!    and    Followed 'b'y''!     is 18s, depend on setting it should be >= 24s. 

Is my measurement correct in that case depending on log ? Even when I set this to 50s the result was similar. 

Can anybody check that and confirm ?

**Comment by dpascoa** [comment]
Mine is not working too. Something happened with action_delay

**Comment by octavius-1** [comment]
My action_delay is not working either, any updates? I'm massively following people with no wait times between actions

**Comment by octavius-1** [comment]
What I did was to modify the low default values in util.py in the meantime. I don't think this is the best approach but I don't want to get banned again.
@timgrossmann Is this already tracked?
Running version: 0.5.1

**Comment by dpascoa** [comment]
> What I did was to modify the low default values in util.py in the meantime. I don't think this is the best approach but I don't want to get banned again.
> @timgrossmann Is this already tracked?
> Running version: 0.5.1

Please tell me how to change that. To fix until not fixed!

**Comment by octavius-1** [comment]
@dpascoa go to get_action_delay method in the util.py file and modify the first dict with your new values.

**Comment by dpascoa** [comment]
@octavius-1 thank you! already working!

**Comment by dpascoa** [comment]
@octavius-1 do you use sleep delay along with action delay? or the first one is not necessary when using more than 30 secs delay in each action?

**Comment by Good-Kat** [comment]
> @dpascoa go to get_action_delay method in the util.py file and modify the first dict with your new values.

Thank you! this fix is working
and set_action_delays doesn't work for me as of yet

**Comment by murilo-campaner** [comment]
I'm with the same problem....
Anyone can make a PR with this fix?

**Comment by Svmurvj** [comment]
@murilo-campaner This is not fix, they just change default values in util.py file which is kind of bypass.

**Comment by Tachenz** [comment]
And also changing those default values is a so so fix. As you can not randomize those delays. At least i don't know how :D

**Comment by h2jun** [comment]
In my case, I solved it with type method, not isinstance method.
isinstance(config[action], (int, float)) -> type(config[action]) not in [int, float]
all((isinstance(i, (type(None), int, float)) for i in -> all((type(i) in [type(None), int, float] for i in
any(not isinstance(i, type(None)) for i in config["random_range"])): -> any(type(i) is not None for i in config["random_range"])):

good luck.

**Comment by h2jun** [comment]
In my case, I solved it with type method, not isinstance method.

> util.py

`isinstance(config[action], (int, float))`
-> `type(config[action]) not in [int, float]`

`all((isinstance(i, (type(None), int, float)) for i in`
-> `all((type(i) in [type(None), int, float] for i in`

`any(not isinstance(i, type(None)) for i in config["random_range"])):`
-> `any(type(i) is not None for i in config["random_range"])):`

good luck.

**Comment by octavius-1** [comment]
@h2jun That's what the previous version had written. Maybe reverting that commit could work

**Comment by octavius-1** [comment]
@h2jun BTW, even using that older version, random_range is not working, I'm printing the return variable of that method and it always prints the base number.

**Comment by octavius-1** [comment]
@h2jun Nevermind, forgot to add randomize=True variable when calling the method

**Comment by h2jun** [comment]
@octavius-1 You're right. This is the previous version.
However, it worked even if the code was modified in the current version.
When i printed a variable named naply in like_util.py,
It appeared as follows.

INFO [2019-07-03 12:52:12] [username]  Like# [1/10]
INFO [2019-07-03 12:52:12] [username]  https://www.instagram.com/p/
INFO [2019-07-03 12:52:16] [username]  Image from: b'fahd_salam'
INFO [2019-07-03 12:52:16] [username]  Link: b'https://www.instagram.com/p/'
INFO [2019-07-03 12:52:16] [username]  Description: b
INFO [2019-07-03 12:52:19] [username]  User: 'username'  |> followers: 5241  |> following: 1722  |> relationship ratio: 3.04
INFO [2019-07-03 12:52:23] [username]  --> Image Liked!
`11.875121682005947`
INFO [2019-07-03 12:52:35] [username]  --> Not commented
INFO [2019-07-03 12:59:10] [username]  --> Not following

If random_range is not working, it will not appear like this.

**Comment by Elektronenhirn108** [comment]
I am the current docker image version but that problem still exists.
Is there a way to fix that?
