### ISSUE TITLE
Still having issues with chromedriver

### ISSUE THREAD

**Issue by nesnes425** [InstaPy/InstaPy#4550]
Hi, 

I've searched through the existing reported issues and still couldn't find the solution for these two errors I get: 

- selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /Users/xyz/Documents/InstaPy/assets/chromedriver
instapy.instapy.InstaPyError: ensure chromedriver is installed at /Users/xyz/Documents/InstaPy/assets/chromedriver

I'm running it from MacOs; chromedriver is in assets folder; correct version for my chrome, read and write permissions.. so what am I missing?

Thanks for the help!

**Comment by AlexKnoch** [comment]
Have you set it's PATH?

**Comment by mikediachenko** [comment]
@nesnes425 firstly, you should check, if the installation of python and pip were correct with no errors. After, check installation of InstaPY and all dependencies run without errors. And all should work fine.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
