### ISSUE TITLE
Follow users followers failing to get the list of followers

### ISSUE THREAD

**Issue by azmankristjan** [InstaPy/InstaPy#4551]
When I run follow users followers on some profiles it fails to load the list of followers then it exits the program. The same problem appears when I don’t run Instapy and try to open followers list from a specific user. Is that Instagram’s problem and does someone know a workaround to get the list?
Thank you

**Comment by dpascoa** [comment]
Hello! Just update your InstaPy using:

`pip install instapy -U`

**Comment by azmankristjan** [comment]
i have tried that but it seem this is a problem with Instagram. it is present for a long time now and it really bothers me.

**Comment by AlexKnoch** [comment]
Have you tried using a different browser/driver? I was having this issue on chrome but not firefox

**Comment by mikediachenko** [comment]
@azmankristjan What about headless_browser and nogui options in your config?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by azmankristjan** [comment]
> @azmankristjan What about headless_browser and nogui options in your config?
> 
> Sent with [GitHawk](http://githawk.com)

I have headless_browser on False and nogui options set as default, I didn't change them.
do you have any idea why it isn't working?
Thanks

**Comment by azmankristjan** [comment]
> Have you tried using a different browser/driver? I was having this issue on chrome but not firefox
@AlexKnoch  I have tried Firefox, Chrome, Edge it doesn't load the followers list even when I am not ruining InstaPy
Thanks
