### ISSUE TITLE
Wrong Password

### ISSUE THREAD

**Issue by leobragarj** [InstaPy/InstaPy#4552]
Hi, I have one issue with login.

Data is all right and checked at the app, but Instpy can´t login and the message apears. I have 2 accounts working but no one more is ok.
![erro instapy](https://user-images.githubusercontent.com/52015667/59805538-fbabd380-92c7-11e9-93d5-7bcd80f43c0e.png)

**Comment by VNRARA** [comment]
I have the same issue... it's inputting just the four first chars of my pass...
