### ISSUE TITLE
Despite disable top posts almost no posts below 300 likes limit

### ISSUE THREAD

**Issue by mheubaum** [InstaPy/InstaPy#4558]
## Expected Behavior
The bot should not interact with the first 9 posts if using the hashtag or location feature. Then it should interact with the following posts which have usually also often under 300 likes.

## Current Behavior
The bot is mostly not interacting anymore cause every post has about 1000 likes and I use set_delimit_liking with a value of 300. (I think this 300 is reasonable.) So the bot is skipping most of the posts.

Idk whether Instagram has changed anything, but usually I followed about 15-20 accounts per session. Now it's e.g. 3.

Is anyone experiencing the same?

**Comment by mheubaum** [comment]
I think skip_top_posts=True is not working in my like_by_tags and like_by_location features.

**Comment by rvoets** [comment]
Same issue here. Top posts aren't skipped anymore which probably has to do with IG's UI update.

**Comment by rvoets** [comment]
@discreated I suggest to change the title to "skip_top_posts is not working anymore".
