### ISSUE TITLE
Everything was working fine until...

### ISSUE THREAD

**Issue by n0sw34r** [InstaPy/InstaPy#456]
Script was working fine (Ubuntu 14.04) until I saw that it stoped working and when I try to run it I got this...
Anybody help please?
![image](https://user-images.githubusercontent.com/30392165/28857181-b8f1fc74-7747-11e7-96ca-c932442713bf.png)

**Comment by lgr** [comment]
I've observed thae same issue, working on a fix now

**Comment by JMuffin** [comment]
There is a simple solution that I tried:
In instapy/unfollow_util.py in line 52 change dialog = ... to
dialog = browser.find__element_by_xpath("//div[contains(@Class, '_4gt3b')]")

It should work ;)

**Comment by lgr** [comment]
The CSS class names seem to have hashed/random names, so IMHO it's better to refer to the DOM elements in a relative manner - as it was done so far.

**Comment by JMuffin** [comment]
If instagram is changing so fast... there should be a better way to find this dialog box :/
I'm using XPath Helper for Chrome and it give me that path or
/html/body/div[4]/div/div[2]/div/div/div/div - as You done it.

**Comment by lgr** [comment]
Yeah... another option is to search for the label "Following" in the dialog itself, however I guess not everyone has an English version of the UI

**Comment by JMuffin** [comment]
I've tried it, but with no luck as the box is under div with label :/

**Comment by timgrossmann** [comment]
#458
