### ISSUE TITLE
Supervisor limits for not getting blocked

### ISSUE THREAD

**Issue by sebo361** [InstaPy/InstaPy#4561]
hi guys, what are your quota supervisor limits in order to not get blocked? i got blocked after the instapy update 2 weeks ago. i had following quotes:

session.set_quota_supervisor(enabled=True,
                             sleep_after=["likes_h", "likes_d", "follows_d"],
                             sleepyhead=True,
                             stochastic_flow=True,
                             notify_me=True,
                             peak_likes=(20, 300),
                             peak_follows=(45, 500),
                             peak_unfollows=(50, 200))

with running the scirpt 10x a day

**Comment by AlexKnoch** [comment]
I don't think this update was because of like and follows. It was targeted towards people who buy followers and that have fake followers. 

Try targeting your audience better so you have better engagement on your posts and try not to get fake followers ie. follow for follow, like for like

**Comment by octavius-1** [comment]
@sebo313 Try not to go over 200 daily follows, keep the followers at least for 5 days in your pool and randomize everything. You could have an instruction that randomizes those numbers daily from 90% to 110% for example.
