### ISSUE TITLE
Code was working well, traceback is now very unhappy.

### ISSUE THREAD

**Issue by Alouwk** [InstaPy/InstaPy#4564]
Hi GitHub, hi Instapy wizards !
Looking for some help with a very basic script. Thanks a lot in advance !

## Expected Behavior
Just wanted a small script to like, follow and unfollow people picked from a shortlist of users.
Almost unedited Quickstart by Nuzzo.

## Current Behavior
Unfollow doesn't work at all, and traceback now displays a lot of errors :

  File "C:\Users\alek\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 101, in <module>
    interact=True)
  File "C:\Users\alek\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 3255, in follow_user_followers
    interact)
  File "C:\Users\alek\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 1088, in follow_by_list
    self.logfolder)
  File "C:\Users\alek\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\unfollow_util.py", line 701, in follow_user
    logfolder)
  File "C:\Users\alek\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\unfollow_util.py", line 1543, in verify_action
    reload_webpage(browser)
  File "C:\Users\alek\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\util.py", line 1706, in reload_webpage
    browser.execute_script("location.reload()")
  File "C:\Users\alek\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\alek\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\alek\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=75.0.3770.100)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17763 x86_64)

## InstaPy configuration

import random
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'XXXXX'
insta_password = 'XXXXX'

# restriction data
dont_likes = ['#exactmatch', '[startswith', ']endswith', 'broadmatch']
ignore_users = ['user1', 'user2', 'user3']

""" Prevent commenting on and unfollowing your good friends (the images will 
still be liked)...
"""
friends = ['friend1', 'friend2', 'friend3']

""" Prevent posts that contain...
"""
ignore_list = []

# TARGET data
""" Set similar accounts and influencers from your niche to target...
"""
targets = ['XXXX', 'XXXX', 'XXXX']

""" Skip all business accounts, except from list given...
"""
target_business_categories = ['category1', 'category2', 'category3']

# COMMENT data
comments = ['Nice shot! @{}',
        'I love your profile! @{}',
        'Your feed is an inspiration :thumbsup:',
        'Just incredible :open_mouth:',
        'What camera did you use @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Getting inspired by you @{}',
        ':raised_hands: Yes!',
        'I can feel your passion @{} :muscle:']

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True,
                  multi_logs=True)

# let's go! :>
with smart_run(session):
    # HEY HO LETS GO
    # general settings
    session.set_dont_include(friends)
    session.set_dont_like(dont_likes)
    session.set_ignore_if_contains(ignore_list)
    session.set_ignore_users(ignore_users)
    session.set_simulation(enabled=True)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=7500,
                                    max_following=3000,
                                    min_followers=25,
                                    min_following=25,
                                    min_posts=10)

    session.set_skip_users(skip_private=True,
                           skip_no_profile_pic=True,
                           skip_business=True,
                           dont_skip_business_categories=[
                               target_business_categories])

    session.set_user_interact(amount=3, randomize=True, percentage=80,
                              media='Photo')
    session.set_do_like(enabled=True, percentage=90)
    session.set_do_comment(enabled=False, percentage=15)
    session.set_comments(comments, media='Photo')
    session.set_do_follow(enabled=True, percentage=40, times=1)

    # activities

    # FOLLOW+INTERACTION on TARGETED accounts
    """ Select users form a list of a predefined targets...
    """
    number = random.randint(3, 5)
    random_targets = targets

    if len(targets) <= number:
        random_targets = targets

    else:
        random_targets = random.sample(targets, number)

    """ Interact with the chosen targets...
    """
    session.follow_user_followers(random_targets,
                                  amount=random.randint(30, 60),
                                  randomize=True, sleep_delay=600,
                                  interact=True)

    # UNFOLLOW activity
    """ Unfollow nonfollowers after one day...
    """
    session.unfollow_users(amount=random.randint(75, 100),
                           InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=24 * 60 * 60, sleep_delay=600)

    """ Unfollow all users followed by InstaPy after one week to keep the 
    following-level clean...
    """
    session.unfollow_users(amount=random.randint(75, 100),
                           InstapyFollowed=(True, "all"), style="FIFO",
                           unfollow_after=168 * 60 * 60, sleep_delay=600)

    """ Joining Engagement Pods...
    """
    session.join_pods()

**Comment by mikediachenko** [comment]
@Alouwk did you try running the script with option `headless_browser=False` ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Alouwk** [comment]
> @Alouwk did you try running the script with option `headless_browser=False` ?
> 
> Sent with [GitHawk](http://githawk.com)

Yes I did, nothing weird happens until the end of the script. It just ended the session without unfollowing anyone.
