### ISSUE TITLE
How can I downgrade Chromium from version 72 to 65?

### ISSUE THREAD

**Issue by thejeromelouis** [InstaPy/InstaPy#4565]
## Current Behavior
if i use: `sudo apt-get install chromium-browser` the chromium-browser (72.0.3626.121-0+rpt4) will be installed.

How can I install chromium 65 on my raspberry pi? 

Maybe the How_to_Raspberry.md should be updated. Because there is no working chromedriver for chromium 72 for the raspberry pi (only 32bit).

**Comment by AlexKnoch** [comment]
https://github.com/timgrossmann/InstaPy/issues/4441
