### ISSUE TITLE
CRITICAL Wrong login data!

### ISSUE THREAD

**Issue by itsdiemond** [InstaPy/InstaPy#4572]
Hey everyone,

I already run two working accounts on a server.
I bought another server for a friend so he can also use it but, with the same exact code as the two I mentioned, I get this error:

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-06-23 23:10:17] [myuser]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...

..........................................................
CRITICAL [2019-06-23 23:11:20] [myuser]  Wrong login data!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

I don't really know what to do. Can anyone help me please?

**Comment by AlexKnoch** [comment]
Try reinstalling everything. You haven't given enough info/source to figure it out.

**Comment by itsdiemond** [comment]
> Try reinstalling everything. You haven't given enough info/source to figure it out.

I already tried! 
My code works perfectly on the two other accounts I have on another server, but when I try to run it on this new fresh account it gives me that error I wrote above. The exact same code, I only changed username/password.
