### ISSUE TITLE
skip_top_posts is not working anymore

### ISSUE THREAD

**Issue by rvoets** [InstaPy/InstaPy#4584]
Something got changed on IG and now the top posts aren't skipped anymore even when skip_top_posts=TRUE

**Comment by mheubaum** [comment]
This is a big issue for me too. Cause usually they are posts with over 1000 likes, which are not my targets..

**Comment by rvoets** [comment]
@timgrossmann any idea if they changed the UI again?

**Comment by webkris** [comment]
Encountered this problem as well.
My current workaround is to add 9 to the amount of likes I want and:
`session.set_delimit_liking(enabled=True, max=300, min=5)`
Most of those "most popular" posts have over 300 likes, thus skipping these until I get to recent posts. I tried tinkering with the code in like-util.py - to no avail.

**Comment by rvoets** [comment]
Thanks for the temporary workaround @webkris

**Comment by patacalas** [comment]
You can remove the first 9 elements of link's list.
Modify return in get_links function (like_util.py).
` return links[9:]`

**Comment by webkris** [comment]
> You can remove the first 9 elements of link's list.
> Modify return in get_links function (like_util.py).
> ` return links[9:]`

Thanks!

on line 375 of like_util.py I changed
`return links[9:amount]`

and I kept my session.like_by_tags(tag_list, amount=14, skip_top_posts=True) so this likes 14-9=5 likes per tag. This is much faster than my solution.

**Comment by rvoets** [comment]
Nice!

**Comment by danniefraim** [comment]
Thanks for the workaround! My bot was just running around the same posts all the time, with accounts either being way above my follower limit, or photos already being liked. I couldn't figure out why, I even suspected my proxy server had started caching or something. Now I realized it's this error.

Anyone working on a permanent fix? I might have a look but I'm on vacation now and I don't have much time for it.

**Comment by Paris704** [comment]
I tried to implement this but it didn't change anything, my bot keeps liking the top posts.
Has it worked for anyone?

**Comment by Mehran** [comment]
@webkris Thais is a really bad bug, I hope it will fix 

anyway @patacalas  solution work nice for me :) Thanks.

**Comment by Mehran** [comment]
@timgrossmann  why this issue does not fix in the new release?
