### ISSUE TITLE
Unable to Install on PyCharm

### ISSUE THREAD

**Issue by browningtons** [InstaPy/InstaPy#4587]
## Expected Behavior
installing package instapy into my PyCharm project
## Current Behavior
cannot install the instapy package in PyCharm
## Possible Solution (optional)
Error code below:
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
## InstaPy configuration
0.5.1

**Comment by AlexKnoch** [comment]
Are you on a Mac? I think the problem is with xcode. Have you tried reinstalling xcrun? https://apple.stackexchange.com/questions/321858/xcrun-missing-installing-xcode-command-line-tools-not-fixing-issue
