### ISSUE TITLE
Clarifai API // Need some help 

### ISSUE THREAD

**Issue by vvnsrzn** [InstaPy/InstaPy#459]
Hello,

First of all, thank you for your tool, very useful.
Currently I try to play with Clarifiai, but it doesn't work.

When I copy paste your snippet :

```python
from instapy import InstaPy

InstaPy(username='test', password='test')\
  .login()\
  .set_do_comment(True, percentage=10)\
  .set_comments(['Cool!', 'Awesome!', 'Nice!'])\
  .set_dont_include(['friend1', 'friend2', 'friend3'])\
  .set_dont_like(['food', 'girl', 'hot'])\
  .set_ignore_if_contains(['pizza'])\
  .set_use_clarifai(enabled=True)\
  .clarifai_check_img_for(['nsfw'])\
  .clarifai_check_img_for(['food', 'lunch', 'dinner'], comment=True, comments=['Tasty!', 'Nice!', 'Yum!'])\
  .like_by_tags(['dog', '#cat'], amount=100)\
  .end()`
```
The script does'nt start :
![image](https://user-images.githubusercontent.com/9358572/28877716-7af270a6-779d-11e7-81ae-2ecb4c4ce468.png)

I double checked my ids and the Clarifai's ID.

Someone has faced this issue before?

**Comment by timgrossmann** [comment]
@VivianSolide Did you ad the clarifai secret and token?

**Comment by vvnsrzn** [comment]
@timgrossmann : Yes!
I tried with export and after adding the keys like this :
`.set_use_clarifai(enabled=True, secret='xyz', proj_id='123')`

**Comment by timgrossmann** [comment]
@VivianSolide You really shouldn't post this here, but yes, these are the right keys

**Comment by vvnsrzn** [comment]
@timgrossmann : You're right, I deleted the screenshot. And I'll generate new credentials :) 
I'll retry until he works :)
Thanks!

**Comment by vvnsrzn** [comment]
I just edit the docker-compose.yml with version 2.0
Might it be a problem?

**Comment by vvnsrzn** [comment]
When I run Docker :
![image](https://user-images.githubusercontent.com/9358572/29022836-43aedcde-7b6b-11e7-883e-cee6861b3ccf.png)

However, I get the latest version
![image](https://user-images.githubusercontent.com/9358572/29022872-6676f4f4-7b6b-11e7-8359-f0fc0f28b17a.png)

The only way to make docker working is to change the version by `"2"`

Thanks for helping!

**Comment by ahmadtibrahim** [comment]
![clarifai](https://user-images.githubusercontent.com/32173056/30756441-c4709cbc-9f98-11e7-9422-ab483410c090.png)

Guys am getting this error, and my second question is where do you add your clarifai api keys? which file do you edit?

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.

**Comment by vvnsrzn** [comment]
Still the same here
Do I need to repost my issue?
