### ISSUE TITLE
 can anybody help me?

### ISSUE THREAD

**Issue by lucicocosta** [InstaPy/InstaPy#4590]
I am running 1 week with my instance in amazon, with only 2 acconts per instace and after a certain time appears "wong longin" and I went to see what it was, it is the instagram asking for a verification by phone ... how can I do that my acconts are not asked for this verification?

  im running this...

**from instapy import InstaPy
from instapy.util import smart_run

while True:
    session = InstaPy(username='',
                  password='',
                  headless_browser=True,
                  disable_image_load=True,
                  multi_logs=True)

    with smart_run(session):

          session.set_relationship_bounds(enabled=True,
          delimit_by_numbers=True, max_followers=12000, max_following=1500,
          min_followers=305, min_following=200)
          session.set_user_interact(amount=2, randomize=True, percentage=100,
          media='Photo')
          session.set_do_follow(enabled=True, percentage=100, times=2)
          session.set_do_like(enabled=True, percentage=60)
          session.set_quota_supervisor(enabled=True,
             sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], 
               sleepyhead=True, 
                stochastic_flow=True, 
                 notify_me=True,
                   peak_likes=(70, 750), 
                     peak_follows=(50, 600),
                       peak_unfollows=(30, 600), 
                         peak_server_calls=(600,None))

    
    # activity

          session.follow_likers ([''], photos_grab_amount = 2, follow_likers_per_photo = 500, randomize=False, sleep_delay=5, interact=True)   
    
          session.unfollow_users(amount=500, nonFollowers=True, style="FIFO",
          unfollow_after=42*60*60, sleep_delay=3)

          session.follow_likers ([''], photos_grab_amount = 2, follow_likers_per_photo = 500, randomize=False, sleep_delay=5, interact=True)
                          

          session.unfollow_users(amount=500, nonFollowers=True, style="FIFO",
          unfollow_after=42*60*60, sleep_delay=3)
             
    session.end()**

**Comment by hijak** [comment]
this is probably because you are using the account on your phone sometimes which is a different geolocation/ISP from amazon. You might want to look into using a proxy server back to your home for the bot so it always appears like your accessing the account from similar geolocation/ISP
