### ISSUE TITLE
Cronjob for server

### ISSUE THREAD

**Issue by rahulkapoor90** [InstaPy/InstaPy#46]
@timgrossmann Thanks for the scripts! I have the whole server with the scripts running but the last part of automating is difficult. Can you let me know at what time you run the script? and using cronjob or screen?

Can you share the command  and where should I add it? 

Here's my cronjob file contents:

```
SHELL=/bin/bash
HOME=/
MAILTO=rahulkapoorbbps@outlook.com

*/30 * * * * source /var/venv/bin/activate && python /var/InstaPy/quickstart.py >> /var/InstaPy/logs/cron.log


```

I did got an cron.log file created but it was empty don't know what's wrong. please help.

**Comment by timgrossmann** [comment]
@rahulkapoor90 I just used crontab -e...

Here is my crontab: 

```bash
0 */4 * * * cd /root/InstaPy && ./tester.py
```
