### ISSUE TITLE
delete private account requests that have been sent

### ISSUE THREAD

**Issue by AvocadoStyle** [InstaPy/InstaPy#4600]
I've been following with my InstaPy after private accounts, 570 of them didn't accept my follow request, and now it seems instagram temporary banned me because of this, i can't see another reason, my  only comment is:
`session.follow_user_followers([name], amount=amount, randomize=True, sleep_delay=1000)`
with delay of 1000! so it's seems to be ok, the only problem is with the follow requests to the private accounts,
so i want to remove this requests, i can see those requests via the settings, can see the name of the people...
I ask if there is functionality in the InstaPy to make this requests to be canceled...?
### how to delete private account requests that have been sent?

**Comment by Robin-taylor97** [comment]
Did you find a way to solve this, please write it down 🌹
