### ISSUE TITLE
How to use a proxy

### ISSUE THREAD

**Issue by leviwinks** [InstaPy/InstaPy#4601]
## Expected Behavior
Could anyone point me in the right direction to correctly set up a proxy. I'm running chrome and have bought 5 proxies which comes with a proxy username and password IP address ,IP's username and password, HTTP Port and Socks Port
Cheers!
## Current Behavior
Can't run the script
## InstaPy configuration
session = InstaPy(session = InstaPy(username=insta_username,
                                    password=insta_password,
                                    proxy_address='11.111.111.111',
                                    proxy_port='11111',
                                    bypass_suspicious_attempt=True,
                                    headless_browser=True,
                                    disable_image_load=True)

**Comment by JuanSpada** [comment]
Proxy dosnt work for me too

**Comment by ghost** [comment]
Port shouldn't be in the apostrophes, because Python considers that as a string.

**Comment by IKDH** [comment]
Hi,

I am using a proxy with my InstaPy bot and since, the cookies are not used to login so everytime I launch the script, news cookies are created. 

Is it a commom problem ?

Thank you.
