### ISSUE TITLE
Please help me  with the error

### ISSUE THREAD

**Issue by jjkuba27** [InstaPy/InstaPy#4604]
I launched Instapy on configuration below everything worked and the bot started to fill in login and password but instagram found me suspicious so they asked me for verification. I did it manually and after that app closed with that information:

Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\Lenovo\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py 

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/Lenovo/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-07-01 18:11:02] [mylogin]  Using built in instapy-chromedriver executable (version 2.46)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-07-01 18:11:09] [my login]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...

............................................................
CRITICAL [2019-07-01 18:12:42] [my login]  Wrong login data!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2019-07-01 18:12:48] [my login]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 731 users & had 713 FOLLOWERS
[Session lasted 1.77 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-07-01 18:12:48] [my login]  Session ended!

## InstaPy configuration
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'my login'
insta_password = 'my password'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                    min_followers=45,
                                    min_following=77)
    
    # activities

    """ Massive Follow of users followers (I suggest to follow not less than
    3500/4000 users for better results)...
    """
    session.follow_user_followers(['user1', 'user2', 'user3'], amount=800,
                                  randomize=False, interact=False)

    """ First step of Unfollow action - Unfollow not follower users...
    """
    session.unfollow_users(amount=500, InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=601)

    """ Second step of Massive Follow...
    """
    session.follow_user_followers(['user1', 'user2', 'user3'], amount=800,
                                  randomize=False, interact=False)

**Comment by module17** [comment]
Looks like IG has detected bot activity from your bot IP and is preventing login.
