### ISSUE TITLE
Bot won't comment on any photo/video

### ISSUE THREAD

**Issue by ato09** [InstaPy/InstaPy#461]
Beside the problem with "follow by list" (which I saw others having issues with it as well), it also can't comment on photo/video. It start normal but once log in successfully, it close. I've tried reinstalling from top to bottom. Tried combining it with other function and on its own, but whenever it come to commenting task it abruptly close. It showed session ended. No error. Nothing. 
Thanks anyway for the great apps. 

```python
from instapy import InstaPy
import os
session = InstaPy(username='name', password='pwd')
session.login()
session.set_do_comment(enabled=True, percentage=25)
session.set_comments(['my_comment'])
session.end()
```

Do I need to put the instapy folder in C:, or is it doesn't matter where I put it?

**Comment by timgrossmann** [comment]
@ato09 You actually need a `.like_by_...` method to make the script start running

**Comment by ato09** [comment]
I tried this as well:

```python
from instapy import InstaPy
import os
session = InstaPy(username='username', password='pwd')
session.login()
session.like_by_tags(['tag1','tag2'], amount=50)
session.set_lower_follower_count(limit = 100)
session.set_do_comment(enabled=True, percentage=25)
session.set_comments(['comment1','comment2'])
session.end()
```


The photo with the tag is liked, but not commented.

**Comment by timgrossmann** [comment]
@ato09 As stated several times before, all the `.set_...` methods need to be called before any of the `.like_by_...` methods.
