### ISSUE TITLE
Using the image's alt properties

### ISSUE THREAD

**Issue by uni1783** [InstaPy/InstaPy#4618]
Since all the posts are being provided with alt properties by Facebook/Instagram, would it be possible to make use of them?
They all follow the same patern:
alt="Image may contain: grass, outdoor and nature"

I'm interested to see them in de log (just print the entire alt property), but also be able to filter on them (both inclusive and exclusive). This might also lessen the requirement on Clarifai

**Comment by Gallax** [comment]
This is perfect for comments_mandatory_words option
