### ISSUE TITLE
InstaPod quota

### ISSUE THREAD

**Issue by maxxfly** [InstaPy/InstaPy#4623]
Currently, it is hard to use instapod because the limitation of free hosting solution.

I think that it can be a good solution to improve the popularity of your instagram account.

For that, are you ready to participate to fee?

It is possible to imagine a high proprioty for the contributors and keep a free solution.

What is your point of you about that ?

(cf @ishandutta2007 )

**Comment by ishandutta2007** [comment]
@maxxfly Create a google surveys poll and link it here. In short term I am in favour of having separate server for each topics, lets see what everyone else votes for.

**Comment by maxxfly** [comment]
Before that, I would like know if the topic can be popular or not. If it is
not the case, the survey is useless 😕

"Wait and see"

Le sam. 6 juil. 2019 à 00:27, ishan dutta <notifications@github.com> a
écrit :

**Comment by ishandutta2007** [comment]
closing thank to https://github.com/timgrossmann/InstaPy/pull/4762
