### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by Guitrentz** [InstaPy/InstaPy#4624]
Is it possible to grab a list of users that marked a location? That would be VERY good. I love the followers grab tool, and miss the chance to grab users from a location.

**Comment by ishandutta2007** [comment]
There are:

- https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#like-by-locations
- https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#comment-by-locations
- https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#follow-by-locations


Doesn't combination of these three satisfy your needs ?

**Comment by Guitrentz** [comment]
Thank you very much for the reply. But what i mean is to get a list of users and save it to a file, I can do that with user followers, following and etc (using session.grab_followers). but can't do it by location (or i dunno how to).
