### ISSUE TITLE
HELP!! Instagram blocked the Selenium Browser

### ISSUE THREAD

**Issue by LuismiLabs** [InstaPy/InstaPy#4625]
Hello
I'm running instapy, but I have blocked several accounts to follow and likes, this only happens to me with selenium.
If I log in to mobile and in chrome of my laptop, I do not have the blockade, any idea of how to solve it?
It seems that instagram knows that I use selenium for automation.

**Comment by DoJoMast3r** [comment]
I have the exact same issue, would it be possible to use the automation extension with a normal version of chrome?

**Comment by DoJoMast3r** [comment]
> I have the exact same issue, would it be possible to use the automation extension with a normal version of chrome?

I tried running on firefox, same issue...

**Comment by ishandutta2007** [comment]
@Luismij Luismij How many accounts from same IP ?

**Comment by mh2git** [comment]
del cookie

**Comment by mh2git** [comment]
and change ip and stay 24 hour

**Comment by poupkine** [comment]
Have the same issue! InstaPy does not work, but the android app works fine.

**Comment by LuismiLabs** [comment]
I'll try changing the IP

**Comment by ishandutta2007** [comment]
instagram allows no more than 4 accounts from one IP. And everytime you change IP, they might as for phone verification (separate phone number for each of the 4).

**Comment by Good-Kat** [comment]
> del cookie

Where is cookie in InstaPy or chromedriver ? location

**Comment by mh2git** [comment]
windows
c:\users \youruser\instapy

**Comment by Good-Kat** [comment]
found.
~/InstaPy/logs/your_user_name/your_user_name_cookie.pkl

**Comment by Good-Kat** [comment]
I have deleted the mentioned cookie. Bot worked about few hours and then get the same error -
Phew! Last follow is not verified.	~'username' might be temporarily blocked from following.
But I still can like and follow from instagram application

**Comment by roncam82** [comment]
I have the same error !

**Comment by JuanSpada** [comment]
Same error. Someone know how many accounts i can run on 1 ip?

**Comment by LuismiLabs** [comment]
I delete the cookie and all is working again, but i only can follow 32 accounts until i get blocked again.

**Comment by mgconejero** [comment]
Same issue with ubuntu in AWS... i am able to follow with my phone but not from server... somebody tried nogui?

**Comment by marcosgb** [comment]
Same here!! Any News??

**Comment by majidpk** [comment]
I tried changing 'user-agent' header in chromeOptions, and it solved the issue.

checkout this [link](https://stackoverflow.com/questions/49565042/way-to-change-google-chrome-user-agent-in-selenium).
