### ISSUE TITLE
Instapy Crash on first like / Error Reading Broken Pipe 

### ISSUE THREAD

**Issue by Cece94** [InstaPy/InstaPy#4626]
Hi everyone, Before updating the bot, it was liking normally (except with more frequents like action block since the instagram update).

The problem is that i updated Instapy to the last version and now,  I have this behavior now:
Try to like and always this message: "Not liked this post ! more likes exist off maximum limit at " (number, exemple: 206). 
And when it reaches the like  10/60, it finds a picture to like: "Image liked !" and then Crash of the bot, browser closed and not even the "error reading broken pipe" error that i had before.

I'm using the last version of instapy and my quickstart is just the quickstart is just the "good commenting strategy and new qs system" with some reasonnable like comment and follow to avoid the ban. Everything was working well before 3 days and i'm not even ban, it just crashed :/

Thank you :)

**Comment by poupkine** [comment]
Have the same problem! This ([https://github.com/timgrossmann/InstaPy/issues/4610#issuecomment-508556623]) seems to be working, but still have a message "WARNING! Image was NOT liked! You are have a BLOCK on likes!", but can like from the android phone so actually was not blocked).

**Comment by beatdeddeer** [comment]
Same issue same behavior.
