### ISSUE TITLE
is Instapy liking and then unliking?

### ISSUE THREAD

**Issue by 46960** [InstaPy/InstaPy#4632]
My instapy seems to be running through the hashtags and liking them as usual. But when I check my account, under "posts you've liked", I am not seeing any of the pictures that were liked through instapy. However, when I normally like pictures in my feed/in hashtags through my phone, they appear under "posts you've liked". 

Can anyone explain what is happening and how I can fix this?

**Comment by DoJoMast3r** [comment]
Likley an action block, instapy isnt able to like at all... refresh the page next time it tries to like to confirm it actually happened

**Comment by beatdeddeer** [comment]
Same issue. I am able to like on iPhone and on an other Chrome instance, but Likes and comments made by Instapy get blocked by Instagram. I tried updating an older versions but no difference.

**Comment by 46960** [comment]
> Likley an action block, instapy isnt able to like at all... refresh the page next time it tries to like to confirm it actually happened

@DoJoMast3r Yep, it seems to be an action block. Is there anything that can be done?

**Comment by GitNees** [comment]
I had the same problem, but not in chrome or firefox, only within selenium. I tested it by trying to like a picture in another tab in that session. Didnt work. Now deleted my cookie, and now likes work again!
