### ISSUE TITLE
Does Instagram know traffic coming from ubuntu?

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4633]
Hello,

When I run from my local - whether it's headless or not, my following works fine. However, when I put on ubuntu server it gets like blocks. It's using the same proxy for both. Could Insta know it's coming from a server and blocking it? If so - how?

```
proxy = 'xxxxxxxxx'
proxy_chrome_extension = create_proxy_extension(proxy)

print('Attempting to login to "{}"'.format(username))
session = InstaPy(
                    username = 'xxx', 
                    password = 'xxx' ,
                    proxy_chrome_extension=proxy_chrome_extension,
                    headless_browser =True)
session.login()
```

**Comment by leo1in88** [comment]
yes i wonder about it myself, anyone else face with this issue?

**Comment by lezlea** [comment]
Wow interesting!  Love to follow this and know if you find any info, sorry I don't have anything useful to add.

**Comment by Tr1pke** [comment]
> Hello,
> 
> When I run from my local - whether it's headless or not, my following works fine. However, when I put on ubuntu server it gets like blocks. It's using the same proxy for both. Could Insta know it's coming from a server and blocking it? If so - how?
> 
> ```
> proxy = 'xxxxxxxxx'
> proxy_chrome_extension = create_proxy_extension(proxy)
> 
> print('Attempting to login to "{}"'.format(username))
> session = InstaPy(
>                     username = 'xxx', 
>                     password = 'xxx' ,
>                     proxy_chrome_extension=proxy_chrome_extension,
>                     headless_browser =True)
> session.login()
> ```

Off course they know. When I login on my Ubuntu I even get a email from Instagram saying I’m logged in from an Ubuntu computer in this area with this browser

**Comment by lezlea** [comment]
They could have another home computer that's Ubuntu on the same IP - so I'm not quite sure why that's a trigger and why it would work on one but not the other with a proxy!?

**Comment by Tr1pke** [comment]
He uses headless...

Headless instagram sees : Ubuntu & unknown browser.

Non headless instagram sees l: Ubuntu & chrome

Non headless could be a another home computer 
Headless is just a server on the same ip 

;-)

**Comment by lezlea** [comment]
Ahhh I see, my apologies!  Yes I don't use headless anymore ;)

**Comment by Tr1pke** [comment]
> Ahhh I see, my apologies! Yes I don't use headless anymore ;)

> ok thank you, will backup instapy folder and will migrate it to desktop version of ubuntu.

http://vanerom.be/Screenshot%202019-07-15%20at%2009.37.17.png 
there you have 2 reasons not using headless anymore.
if they see "linux" "unknow browser" its a reason to keep an eye on that account and follow their movements, put on top of that an ip that never changes or stays the same for days or weeks, no location change and reason enough to block

**Comment by LexLinux** [comment]
Headless is ok provided you have the correct User Agent applied so it doesn't show linux / unknown location :P

**Comment by ghost** [comment]
@LexLinux how can I change user agent? Where?

**Comment by LexLinux** [comment]
edit browser.py line 106 
            # replaces browser User Agent from "HeadlessChrome".
            user_agent = "Chrome"
            chrome_options.add_argument('user-agent={user_agent}'
                                        .format(user_agent=user_agent))

Change "Chrome" to something that reflects your mobile device.

**Comment by ghost** [comment]
@LexLinux thank you so much. So I edited bworser.py, added my browser of mobile, seems it works fine now. Do I need to change any other things? What about IP? Have public static IP address.


img https://drive.google.com/file/d/12OXLwuLFeBoYKecHwlzT88n_zZgF1Bi8/view?usp=sharing

**Comment by ghost** [comment]
after changed user agent, I'm getting a problem with bot.
ua: 
> #replaces browser User Agent from "HeadlessChrome".
> #user_agent = "Chrome"
> user_agent = "Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G975F Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.2 Chrome/67.0.3396.87 Mobile Safari/537.36"
> chrome_options.add_argument('user-agent={user_agent}'
> .format(user_agent=user_agent))
> 
> capabilities = DesiredCapabilities.CHROME

errors:

> Cookie file not found, creating cookie...
> 
> ...............................................................
> INFO [2019-07-16 14:09:18] [myinstausername]  Logged in successfully!
> '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
> INFO [2019-07-16 14:09:18] [myinstausername]  Saving account progress...
> 
> ____________________________________________________________________
> INFO [2019-07-16 14:09:22] [myinstausername]  Starting to unfollow users..
> """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> INFO [2019-07-16 14:09:22] [myinstausername]  Unfollowing the users followed by InstaPy
> 
> INFO [2019-07-16 14:09:22] [myinstausername]  Total 58 users available to unfollow  ~didn't pass `unfollow_after`: 62
> 
> INFO [2019-07-16 14:09:22] [myinstausername]  Ongoing Unfollow [1/30]: now unfollowing 'b'justafollower89''...
> ERROR [2019-07-16 14:10:18] [myinstausername]  --> Unable to detect the following status of 'b'justafollower89''!
> INFO [2019-07-16 14:10:18] [myinstausername]  Pinging 'instagram.com' to check the connectivity...
> PING instagram.com (52.21.14.7) 56(84) bytes of data.
> 64 bytes from ec2-52-21-14-7.compute-1.amazonaws.com (52.21.14.7): icmp_seq=1 ttl=236 time=116 ms
> 
> --- instagram.com ping statistics ---
> 1 packets transmitted, 1 received, 0% packet loss, time 0ms
> rtt min/avg/max/mdev = 116.385/116.385/116.385/0.000 ms
> INFO [2019-07-16 14:10:18] [myinstausername]  Checking if 'myinstausername' is logged in...
> WARNING [2019-07-16 14:10:18] [myinstausername]  --> Couldn't unfollow 'justafollower89'!     ~unexpected failure
> INFO [2019-07-16 14:10:18] [myinstausername]  Ongoing Unfollow [1/30]: now unfollowing 'b'russia''...
> ERROR [2019-07-16 14:11:13] [myinstausername]  --> Unable to detect the following status of 'b'russia''!
> INFO [2019-07-16 14:11:13] [myinstausername]  Pinging 'instagram.com' to check the connectivity...
> PING instagram.com (34.232.137.142) 56(84) bytes of data.
> 64 bytes from ec2-34-232-137-142.compute-1.amazonaws.com (34.232.137.142): icmp_seq=1 ttl=236 time=113 ms

**Comment by LexLinux** [comment]
> after changed user agent, I'm getting a problem with bot.
> ua:
> 
> > #replaces browser User Agent from "HeadlessChrome".
> > #user_agent = "Chrome"
> > user_agent = "Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G975F Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.2 Chrome/67.0.3396.87 Mobile Safari/537.36"
> > chrome_options.add_argument('user-agent={user_agent}'
> > .format(user_agent=user_agent))
> > capabilities = DesiredCapabilities.CHROME
> 
> errors:
> 
> > Cookie file not found, creating cookie...
> > ...............................................................
> > INFO [2019-07-16 14:09:18] [myinstausername]  Logged in successfully!
> > '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
> > INFO [2019-07-16 14:09:18] [myinstausername]  Saving account progress...
> > 
> > INFO [2019-07-16 14:09:22] [myinstausername]  Starting to unfollow users..
> > """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> > INFO [2019-07-16 14:09:22] [myinstausername]  Unfollowing the users followed by InstaPy
> > INFO [2019-07-16 14:09:22] [myinstausername]  Total 58 users available to unfollow  ~didn't pass `unfollow_after`: 62
> > INFO [2019-07-16 14:09:22] [myinstausername]  Ongoing Unfollow [1/30]: now unfollowing 'b'justafollower89''...
> > ERROR [2019-07-16 14:10:18] [myinstausername]  --> Unable to detect the following status of 'b'justafollower89''!
> > INFO [2019-07-16 14:10:18] [myinstausername]  Pinging 'instagram.com' to check the connectivity...
> > PING instagram.com (52.21.14.7) 56(84) bytes of data.
> > 64 bytes from ec2-52-21-14-7.compute-1.amazonaws.com (52.21.14.7): icmp_seq=1 ttl=236 time=116 ms
> > --- instagram.com ping statistics ---
> > 1 packets transmitted, 1 received, 0% packet loss, time 0ms
> > rtt min/avg/max/mdev = 116.385/116.385/116.385/0.000 ms
> > INFO [2019-07-16 14:10:18] [myinstausername]  Checking if 'myinstausername' is logged in...
> > WARNING [2019-07-16 14:10:18] [myinstausername]  --> Couldn't unfollow 'justafollower89'!     ~unexpected failure
> > INFO [2019-07-16 14:10:18] [myinstausername]  Ongoing Unfollow [1/30]: now unfollowing 'b'russia''...
> > ERROR [2019-07-16 14:11:13] [myinstausername]  --> Unable to detect the following status of 'b'russia''!
> > INFO [2019-07-16 14:11:13] [myinstausername]  Pinging 'instagram.com' to check the connectivity...
> > PING instagram.com (34.232.137.142) 56(84) bytes of data.
> > 64 bytes from ec2-34-232-137-142.compute-1.amazonaws.com (34.232.137.142): icmp_seq=1 ttl=236 time=113 ms

0.5.5 has an issue with unfollowing right now, try with version 0.5.2 :)

**Comment by ghost** [comment]
@LexLinux so you think user agent is right? How can I downgrade instapy? Didn't find it in documentation

**Comment by LexLinux** [comment]
@USRGH I can't prove it but it certainly won't hurt to mod the user agent, https://github.com/uluQulu/InstaPy.git this fork is a solid build and is what i'm currently using.
pip3 install instapy==0.5.2 should do the trick to downgrade but I really like uluQulu's version :)

**Comment by mgconejero** [comment]
Same issue in ubuntu at AWS... works as normal i my phone but cannot follow in server...

**Comment by buringlist** [comment]
> edit browser.py line 106
> # replaces browser User Agent from "HeadlessChrome".
> user_agent = "Chrome"
> chrome_options.add_argument('user-agent={user_agent}'
> .format(user_agent=user_agent))
> 
> Change "Chrome" to something that reflects your mobile device.

Hello, pls tell me where is 'browser.py' ? I can't find it in the instapy folder
