### ISSUE TITLE
Stop from following when blocked from following

### ISSUE THREAD

**Issue by ianpierreg** [InstaPy/InstaPy#4635]
## Expected Behavior
When the script indentifies that the account is blocked from following it should stop trying to follow because if keeps attempting the Instagram account will be banned forever
## Current Behavior
Keeps trying

**Comment by nafferro** [comment]
add this at line 1562:
 sys.exit(0)

```
elif retry_count == 3:
                    logger.warning("Phew! Last {0} is not verified."
                                   "\t~'{1}' might be temporarily blocked "
                                   "from {0}ing\n"
                                   .format(action, username))
                    sys.exit(0)
```

**Comment by ebubekirboyun** [comment]
hi @nafferro  i have this problem. witch file change ?

**Comment by nafferro** [comment]
go to instapy directory and open edit like_util.py

**Comment by nafferro** [comment]
> hi @nafferro i have this problem. witch file change ?
go to instapy directory and open edit like_util.py

**Comment by nafferro** [comment]
> hi @nafferro i have this problem. witch file change ?

go to instapy directory and open edit like_util.py

**Comment by muygd** [comment]
@nafferro I found the file however there is no 

`elif retry_count == 3:
                    logger.warning("Phew! Last {0} is not verified."
                                   "\t~'{1}' might be temporarily blocked "
                                   "from {0}ing\n"
                                   .format(action, username))`
