### ISSUE TITLE
Inoperative: session.set_dont_unfollow_active_users

### ISSUE THREAD

**Issue by ExportEh** [InstaPy/InstaPy#4638]
## Expected Behavior
Scan last 6 posts for likes and not unfollow those users
## Current Behavior
INFO [2019-07-08 21:27:43] [XXXXXX]  Getting active users who liked the latest 6 posts:
  ~collecting the usernames from posts with the boundary of 500

INFO [2019-07-08 21:30:46] [XXXXXX]  Post 1  |  Likers: found 465, catched 465

ERROR [2019-07-08 21:30:47] [XXXXXX]  Unable to go to next profile post
INFO [2019-07-08 21:31:07] [XXXXXX]  Post 2  |  Likers: found 465, catched 11

ERROR [2019-07-08 21:31:09] [XXXXXX]  Unable to go to next profile post
INFO [2019-07-08 21:31:34] [XXXXXX]  Post 3  |  Likers: found 465, catched 15

ERROR [2019-07-08 21:31:36] [XXXXXX]  Unable to go to next profile post

## Description of error
It is unable to go to next profile. Keeps scanning the first post. 
## InstaPy configuration
Also occurs with:
pip install -I https://github.com/timgrossmann/InstaPy/zipball/master
&, 0.5.0, 0.5.3, 0.5.4

## Quickstart code
    session.set_dont_unfollow_active_users(enabled=True, posts=6)
    session.unfollow_users(amount=300, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=300*60*60, sleep_delay=500)

## My comments
Any help would be greatly appreciated.
If it makes a difference: I'm using Windows 10

**Comment by riccardovalente** [comment]
Similar issue here, always stuck on post 1. This loop went on for 4 hours.

`INFO [2019-07-10 11:40:40] [x]  video found, try next post until we run out of posts
ERROR [2019-07-10 11:41:05] [x]  Unable to go to next profile post
INFO [2019-07-10 11:41:33] [x]  Failed to get likers count on your post 1
INFO [2019-07-10 11:41:58] [x]  video found, try next post until we run out of posts
ERROR [2019-07-10 11:42:23] [x]  Unable to go to next profile post
INFO [2019-07-10 11:42:50] [x]  Failed to get likers count on your post 1
`

After 4 hours:

`
INFO [2019-07-10 12:21:48] [x]  Gathered total of 0 unique active followers from the latest 3 posts in 242 minutes and 31 seconds
`

**Comment by ExportEh** [comment]
Just tested with Zip 0.5.5 and still doesn't work. :(

**Comment by riccardovalente** [comment]
Anyone? I've had a look at what happens in Chrome; the browser is stuck on the first post even if you set `session.set_dont_unfollow_active_users(enabled=True, posts=6)`. In practice, it seems to behave as if you set `posts=1`. If post 1 happens to be a video (where the likers are not displayed by IG), then this function seems to get stuck in a loop.
