### ISSUE TITLE
Can anybody check my simple template?

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4643]
Hello,
newbie in InstaPy. Can anybody check my template?

What I want?
- follow as much as possible users per day (by tags)
- like as much as possible photos per day (by tags)
- unfollow users followed by InstaPy after 48 hours

I'm afraid of block so I have lower counts now. What is preffered count of daily likes etc?
If it's possible, try to improve my template, will be very thankful.

Running it on Ubuntu 18.04 Server.
Crontab (but don't know if it works :) ) - I want to run crontab in random minutes between 5-42
`5-42 7,10,14,15,18,20,21,22 * * * cd /home/user/InstaPy && /usr/bin/python3 ~/scripts/instapy-quickstart/instagram.py`

Thank you so much.

```
""" InstaPy script """
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'myusername'
insta_password = 'mypassword'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
password=insta_password,
headless_browser=True)

with smart_run(session):

# activity
session.like_by_tags(["tag1", "tag2", "tag3", "tag4", "tag5", "tag6", "tag7", "tag8", "tag9", "tag10"], randomize=True, amount=5)
session.follow_by_tags(['tag1', 'tag2', 'tag3'], randomize=True, amount=5)
session.unfollow_users(amount=20, InstapyFollowed=(True, "all"), style="RANDOM", unfollow_after=48*60*60, sleep_delay=600)

session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
peak_likes=(50, 307),
peak_comments=(21, 182),
peak_follows=(35, None),
peak_unfollows=(40, 200),
peak_server_calls=(None, 4700))
```

**Comment by yoannes** [comment]
I dont know everyone, but going headless is a pain in the butt.. Many people are getting blocked for that (inculing me)

Before I used to do 600 likes and 200follow/unfollow a day. But from two weeks I'm happy when I can like 50 pictures/day

**Comment by ghost** [comment]
@yoannes so you think I have high counters? Likes, follows..

**Comment by yoannes** [comment]
> @yoannes so you think I have high counters? Likes, follows..

I dont think so, but you need to test it.

And your code seems fine, it should be ok.

**Comment by ghost** [comment]
ok. Any ideas from other users?

**Comment by riccardovalente** [comment]
I run headless and it works for me. I randomise all users and tags at every run. I unfollow non-followers after 3 days, then all after 1 week. This are my settings: 

```
session.set_action_delays(enabled=True, 
                    like = 7, 
                    comment = 10,
                    follow = 10,
                    unfollow = 30,
                    randomize=True, random_range=(None, 150))

    session.set_quota_supervisor(enabled=True,
                    sleep_after=['likes', 'comments_d', 'follows', 'unfollows', 'server_calls'],
                    sleepyhead=True, stochastic_flow=True,
                    notify_me=True,
                    peak_likes=(59, 572),
                    peak_comments=(21, 182),
                    peak_follows=(49, 675),
                    peak_unfollows=(38, 421),
                    peak_server_calls=(300, 4700))
```
It's slow but it works.

**Comment by Tr1pke** [comment]
Headless ? You will be banned in a couple of weeks. 
FYI Headless people are ruing it for the rest

**Comment by ghost** [comment]
So headless is really bad choice? Will be ok if I will use instapy in ubuntu desktop without headless?

**Comment by Tr1pke** [comment]
Headless instagram sees : Ubuntu & unknown browser. 

Non headless instagram sees l: Ubuntu & chrome 

;-)

**Comment by ghost** [comment]
Uhm. So instagram will not ban my account if I will use "chrome in ubuntu"?

**Comment by Tr1pke** [comment]
> Uhm. So instagram will not ban my account if I will use "chrome in ubuntu"?

no because you use a know browser, if you use a unknot browser its already a flag for instagram put on top some extra automatic actions and its easy to find out your running an automatic script

**Comment by ghost** [comment]
ok thank you, will backup instapy folder and will migrate it to desktop version of ubuntu.

**Comment by Tr1pke** [comment]
> ok thank you, will backup instapy folder and will migrate it to desktop version of ubuntu.

http://vanerom.be/Screenshot%202019-07-15%20at%2009.37.17.png 
this is the difference that calls flags
Linux, Unknow browser, 2 reasons to think its a server

**Comment by LexLinux** [comment]
Been running headless for more than 3 weeks and no ban, you need to mod the User Agent of browser.py then it doesn't show linux / unknown location, changing IP every few days seems to help.

**Comment by ghost** [comment]
@LexLinux still running headless?

**Comment by LexLinux** [comment]
> @LexLinux still running headless?

yes I am :)

**Comment by LexLinux** [comment]
![Screen Shot 2019-07-15 at 22 37 29](https://user-images.githubusercontent.com/34457292/61251067-531b5300-a751-11e9-8ec1-4aba3061b2ba.png)
After modded User Agent... no action block.

**Comment by yoannes** [comment]
@LexLinux 

I didn't have same luck as you. At least could like 155 pictures before action block

![image](https://user-images.githubusercontent.com/11369576/61287050-127a1300-a7ff-11e9-8895-51a78d797811.png)

        |> LIKED 155 images  |  ALREADY LIKED: 5
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> LIKED 0 comments
        |> REPLIED to 0 comments
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 222

        [Session lasted 7.35 hours]

**Comment by ghost** [comment]
@LexLinux
after changed user agent, I'm getting a problem with bot.
ua: 
> #replaces browser User Agent from "HeadlessChrome".
> #user_agent = "Chrome"
> user_agent = "Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G975F Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.2 Chrome/67.0.3396.87 Mobile Safari/537.36"
> chrome_options.add_argument('user-agent={user_agent}'
> .format(user_agent=user_agent))
> 
> capabilities = DesiredCapabilities.CHROME

errors:

> Cookie file not found, creating cookie...
> 
> ...............................................................
> INFO [2019-07-16 14:09:18] [myinstausername]  Logged in successfully!
> '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
> INFO [2019-07-16 14:09:18] [myinstausername]  Saving account progress...
> 
> ____________________________________________________________________
> INFO [2019-07-16 14:09:22] [myinstausername]  Starting to unfollow users..
> """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> INFO [2019-07-16 14:09:22] [myinstausername]  Unfollowing the users followed by InstaPy
> 
> INFO [2019-07-16 14:09:22] [myinstausername]  Total 58 users available to unfollow  ~didn't pass `unfollow_after`: 62
> 
> INFO [2019-07-16 14:09:22] [myinstausername]  Ongoing Unfollow [1/30]: now unfollowing 'b'justafollower89''...
> ERROR [2019-07-16 14:10:18] [myinstausername]  --> Unable to detect the following status of 'b'justafollower89''!
> INFO [2019-07-16 14:10:18] [myinstausername]  Pinging 'instagram.com' to check the connectivity...
> PING instagram.com (52.21.14.7) 56(84) bytes of data.
> 64 bytes from ec2-52-21-14-7.compute-1.amazonaws.com (52.21.14.7): icmp_seq=1 ttl=236 time=116 ms
> 
> --- instagram.com ping statistics ---
> 1 packets transmitted, 1 received, 0% packet loss, time 0ms
> rtt min/avg/max/mdev = 116.385/116.385/116.385/0.000 ms
> INFO [2019-07-16 14:10:18] [myinstausername]  Checking if 'myinstausername' is logged in...
> WARNING [2019-07-16 14:10:18] [myinstausername]  --> Couldn't unfollow 'justafollower89'!     ~unexpected failure
> INFO [2019-07-16 14:10:18] [myinstausername]  Ongoing Unfollow [1/30]: now unfollowing 'b'russia''...
> ERROR [2019-07-16 14:11:13] [myinstausername]  --> Unable to detect the following status of 'b'russia''!
> INFO [2019-07-16 14:11:13] [myinstausername]  Pinging 'instagram.com' to check the connectivity...
> PING instagram.com (34.232.137.142) 56(84) bytes of data.
> 64 bytes from ec2-34-232-137-142.compute-1.amazonaws.com (34.232.137.142): icmp_seq=1 ttl=236 time=113 ms

**Comment by LexLinux** [comment]
This is the exact process i use when starting with a fresh IP.
I clear my instagram data on my mobile.
Change the config for my openvpn gateway.
Login with my phone and check i've got the correct ip address.
I'll then check my email and make sure the location and device email has come through.
Perform a few actions on the mobile, likes some follows etc.
Fire up my lxc for InstaPy and confirm i've got the same ip from my gateway and the same one used on my mobile.
Clear my cookie file from the python venv and backup my blacklist campaign.
Start out with like by feed template or something with around 30-60 actions.
When it finishes I then start up my main template and run as normal.
When I was faced with an action block i do the same process only with a new IP, I ALWAYS put my mobile phone on the new IP first, not sure if that helps ... it's just the process i do.

**Comment by ghost** [comment]
@LexLinux but I don't have dynamic IP so I can't change it :)

**Comment by LexLinux** [comment]
You need to invest in a VPN or some sort of proxy, this might not work for you it's just the process i've been using and had very little issues, nordVPN is the provider i already used before using instapy and they have LOADS of servers and 6 IP's per account at one time works for my 4 bots.
