### ISSUE TITLE
[Question] Stop bot if action blocked  

### ISSUE THREAD

**Issue by brunano21** [InstaPy/InstaPy#4650]
Hi,
if not available already, I would like to suggest implementing to stop the bot as soon as an action is blocked, like "like", "follow", etc.

I believe it would make sense to stop it and not to continue with actions, because they would be unsuccessful.

**Comment by mh2git** [comment]
Yeah also . I think instapy should read the past logs and take action accordingly

**Comment by leo1in88** [comment]
yes its should be like that.

**Comment by michn** [comment]
agreed

**Comment by yoannes** [comment]
A very dirty and quick solution until such feature is implemented:

go to `instapy/` directory and open the file `like_util.py`

at beginning of the file (under `import re`) add
`import sys`

find and change this function:

```
def verify_liked_image(browser, logger):
    """Check for a ban on likes using the last liked image"""

    browser.refresh()
    unlike_xpath = read_xpath(like_image.__name__, "unlike")
    like_elem = browser.find_elements_by_xpath(unlike_xpath)

    if len(like_elem) == 1:
        return True
    else:
        logger.info('-------- WARNING! Image was NOT liked! You are have a BLOCK on likes!')
        sys.exit(0)          # <------------------- ADD THIS LINE
        return False
```

**This is not a permanent solution, but it's better then keep trying to like while blocked.**
