### ISSUE TITLE
Quickstart by Nuzzo session ended

### ISSUE THREAD

**Issue by zaz7zaz** [InstaPy/InstaPy#4661]
Hello! :)
I recently started using the Quickstart script from Nuzzo235.
I really like the way the script works!

I'd like to run the bot 24/7 permanently.
Unfortunately, the script stops with the message "Session ended!" after about 1-2 hours.

What do I have to do for the script to continue working permanently?

Thank you for your help!

Best regards,
zaz7zaz

**Comment by Nuzzo235** [comment]
@zaz7zaz You can automate Instapy, have a look at the [documentation](https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#automate-instapy). Just keep in mind that you will pretty soon run into Instagrams daily limits with this script running 24/7.
