### ISSUE TITLE
O Instapy acabou?

### ISSUE THREAD

**Issue by user134134134** [InstaPy/InstaPy#4662]
Depois das mudanças do Instagram, o Instapy vai continuar funcionando? Se não, alguém conhece um bom substituto?

**Comment by yoannes** [comment]
Se achar compartilha ai.. aqui nao funciona mais tambem.

**Comment by andremorganti** [comment]
e o instabot? já usaram?

**Comment by user134134134** [comment]
> e o instabot? já usaram?

Nunca ouvi falar, alguém já usou?

Meu instapy ainda roda, mas nos primeiros likes bloqueia e não volta mais,

**Comment by yoannes** [comment]
Meu tambem, bloqueia rapidinho

**Comment by andremorganti** [comment]
O que vocês querem dizer com bloqueia rapidinho? Pára de funcionar ou o instagram bloqueia o acesso? Pergunto pois estou começando a mexer com esses bots, olhei o instapy e também o instabot. O instapy funciona por selenium e o instabot por API's do instagram. Mas, independente de qualquer um, pelo que entendi, o instagram verifica o IP que está acessando e isso pode levar a ele bloquear por parecer sem um bot. Vocês usam proxy? Sinceramente, gostei mais do instapy, mas se não está funcionando...

**Comment by yoannes** [comment]
> O que vocês querem dizer com bloqueia rapidinho? Pára de funcionar ou o instagram bloqueia o acesso? Pergunto pois estou começando a mexer com esses bots, olhei o instapy e também o instabot. O instapy funciona por selenium e o instabot por API's do instagram. Mas, independente de qualquer um, pelo que entendi, o instagram verifica o IP que está acessando e isso pode levar a ele bloquear por parecer sem um bot. Vocês usam proxy? Sinceramente, gostei mais do instapy, mas se não está funcionando...

Desde a ultima atualização do Instagram (uns dias atrás), meio que esta acabando com robos de automação. Minha conta por exemplo, eu faço 30 likes e já era, o Instagram bloqueia minha conta pra likes.. sempre que tenta fazer um like aparece uma mensagem de bloqueado e nao realiza a curtida

**Comment by guztavoalves** [comment]
Eu usei o instabot por alguns meses, porem na segunda quinzena de junho todas as interações feitas pelo bot eram 'canceladas' no ato da interação, mas sem exibir notificação de bloqueio. Em algumas contas tbm ficou impossível logar com o bot, mesmo usando diferentes proxy's, acredito que o instagram marca a própria conta como 'suspeita' e trata de forma diferenciada tudo o que você faz.

Agora usando o InstaPy eu consigo logar normalmente, porem após cerca de 30 likes recebo notificação de bloqueio.

**Comment by yoannes** [comment]
Estou com mesmo problema no instapy tambem.

Estava analisando a forma de trabalho, existem muitos padroes detectaveis realmente. Principalmente depois de uma curtida ele atualiza a pagina pra ver se realmente foi curtido, ninguem fica curtindo e atualizando pagina toda vez..

Depois com mais calma vou mexer no metodo de curtidas pra tentar deixar algo mais "natural"

**Comment by guztavoalves** [comment]
Eu configurei um delay, mas mesmo assim não resolveu

```
# Delay
session.set_action_delays(
	enabled = True,
	like = 60*60*24 / 100,
	comment = 60*60*24 / 50,
	follow = 60*60*24 / 200,
	unfollow = 60*60*24 / 180)
```

**Comment by yoannes** [comment]
Comigo tambem nada funciona
