### ISSUE TITLE
Action Blocked on Instapy

### ISSUE THREAD

**Issue by duncanbla974** [InstaPy/InstaPy#4675]
Hi! I have used Instapy for a while and it was perfect.
But now when I run it all actions are blocked. But it is blocked only on instapy not on my phone or a random browser.

I tried to uninstall and install again but nothing has changed.

Do someone have an issue with it?

**Comment by bjspi** [comment]
Yes I've got the same.
See also my thread, I think for me I have temporarly found a solution:
https://github.com/timgrossmann/InstaPy/issues/4676#issuecomment-513121748

Please check whether it helps you too

**Comment by dlenskyi** [comment]
@bjspi hey, I have the same issue, I tried to change line in Chromium conf, but firstly, I didn't find conf named `default`. Secondly, I find approximately same in `/etc/chromium-browser/customizations/pepperflashplugin-nonfree`. I changed line that you proposed, but nothing changed. Could you help with it?

**Comment by bjspi** [comment]
I dont have too much clue to be honest. I just found out that this seems to be the default config of Chromium via google. Maybe this default file could be created manually and will be used by Chromium as config???

Otherwise, did you try the other solution by modifying the Instapy code and commenting the line "browser.add_cookie(cookie)" so that the cookie-file which is created by Instapy will never be loaded, hence instapy will login your user everytime freshly.

**Comment by dlenskyi** [comment]
@bjspi same.. I tried both with this line and without :(

**Comment by bjspi** [comment]
@dlenskyi hmm dunno then. What happens if you manually delete the cookie pkl file within the instapy folder? Does the bot work for one session than?

**Comment by GabrieleAnsaldo** [comment]
If you still get blocked with InstaPy read this:

So I actually found a fix if you really want to have an instagram bot. Basically instagram got very good at detecting bots so I tried to work around that. Basically I have connected my old android phone to the Raspberry (you can connect it to any computer) and I just send a bunch of adb commands to it. I wrote a little script. Its been working so well.

I guess instagram finds it hard to find bots from someone using the app itself and not the browser version.

Hit me up if you are interested in developing this project with me, there is still a lot to do to make it very efficient.

**Comment by bjspi** [comment]
That sounds awesome. How is it possible to send adb devices to control the
usage within the app?

What commands are working already using that? Liking? Commenting?
Following? Thanks


GabrieleAnsaldo <notifications@github.com> schrieb am Do., 21. Mai 2020,
23:37:

**Comment by gvmturl** [comment]
> If you still get blocked with InstaPy read this:
> 
> So I actually found a fix if you really want to have an instagram bot. Basically instagram got very good at detecting bots so I tried to work around that. Basically I have connected my old android phone to the Raspberry (you can connect it to any computer) and I just send a bunch of adb commands to it. I wrote a little script. Its been working so well.
> 
> I guess instagram finds it hard to find bots from someone using the app itself and not the browser version.
> 
> Hit me up if you are interested in developing this project with me, there is still a lot to do to make it very efficient.

Why not sharing? The community is always interested on help developing good ideas...

**Comment by GabrieleAnsaldo** [comment]
@gvmturl Yeah I was thinking of opening a repository for this project, but yeah as I said I don't have much knowledge on programming so my files will be super messy I guess. But will do let you know so that you all guys can have a loot at it and perhaps improve it!

**Comment by gvmturl** [comment]
> @gvmturl Yeah I was thinking of opening a repository for this project, but yeah as I said I don't have much knowledge on programming so my files will be super messy I guess. But will do let you know so that you all guys can have a loot at it and perhaps improve it!

Thank you!

Do that, for sure we gonna have good results!

Let me know when repo is done, thanks for contributing.

**Comment by GabrieleAnsaldo** [comment]
@gvmturl  I have just made a quick repository for it. Take a look https://github.com/GabrieleAnsaldo/Andro-Insta-Bot.git

**Comment by GabrieleAnsaldo** [comment]
@gvmturl I think the above link does not work anymore, this should work now
https://github.com/GabrieleAnsaldo/Andro-Bot-Insta
