### ISSUE TITLE
Which chromedriver for MacOS + Chrome 75.0.3770.142

### ISSUE THREAD

**Issue by cuckforlife** [InstaPy/InstaPy#4677]
I'm setting up InstaPy, tried with the instapy-chromedriver + Chrome 75 it didn't work. So I downloaded chromedriver 75 and I still have the same issue (see exception below). Is there a working chromedriver for Chrome 75? Don't want to have to use an old Chrome version (if possible).

> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[3]/div/div[2]"}
>   (Session info: chrome=75.0.3770.142)
>   (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.5 x86_64)

**Comment by breuerfelix** [comment]
thats not a chromedriver bug but a bug related to Instapy changes. do you know when this happens ? what does the bot currently do when this occurs ?

could it be when trying to get users in the modal ?

**Comment by GoldenPolo** [comment]
Same for me, here's the entire log :

Last login: Wed Jul 17 22:35:54 on ttys000
MBPdeMac:~ $ python /quickstart.py

 ..  ..  ..  ..  ..  ..  ..  ..  ._. 
Workspace in use: "/Users/Mac/InstaPy"

 ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ._. 
INFO [2019-07-20 00:04:49] [***]  Using built in instapy-chromedriver executable (version 2.46)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-07-20 00:05:49] [***]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo


...................................................................
INFO [2019-07-20 00:06:22] [***]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-07-20 00:06:22] [***]  Saving account progress...

_________________________________________________________________________________
INFO [2019-07-20 00:06:27] [***]  Starting to follow user `Followers`..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-07-20 00:06:27] [***]  User '***' [1/1]
**********************************************************************
If raising an issue, please also upload the file located at:
/var/folders/43/b_3vm7712kg58_y2yq87ylr80000gn/T/20190720-000658.html
**********************************************************************

INFO [2019-07-20 00:07:00] [***]  Sessional Live Report:
	|> No any statistics to show

On session start was FOLLOWING 13 users & had 14 FOLLOWERS
[Session lasted 2.17 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-07-20 00:07:00] [***]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "/quickstart.py", line 48, in <module>
    session.follow_user_followers(['secret.wood'], amount=150, randomize=True, sleep_delay=100, interact=False)
  File "/Library/Python/2.7/site-packages/instapy/instapy.py", line 3191, in follow_user_followers
    self.logfolder)
  File "/Library/Python/2.7/site-packages/instapy/unfollow_util.py", line 1079, in get_given_user_followers
    logger, logfolder)
  File "/Library/Python/2.7/site-packages/instapy/unfollow_util.py", line 807, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[3]/div/div[2]"}
  (Session info: chrome=75.0.3770.142)
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.14.5 x86_64)


Any ideas ?

**Comment by GoldenPolo** [comment]
Just make the update if chrome, it worked for me

**Comment by miya2017** [comment]
my chrome is  Chrome 75.0.3770.142, I 'd like to install selenium which supported by chromedirver.
 so I go to the download page for driver on http://chromedriver.chromium.org/downloads
it shows the below matches:
-----------
Current Releases
If you are using Chrome version 76, please download ChromeDriver 76.0.3809.68
If you are using Chrome version 75, please download ChromeDriver 75.0.3770.140

--------------
I download  ChromeDriver 75.0.3770.140 to match my chrome75 as it suggested.
after I run "chromedriver" on terminal, it shows below warnings:
`Starting ChromeDriver 75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
`
shall I downgrade Chrome to 74 to match other chromedriver?
Because there is no specific driver version is 75.0.3770.142 to match Chrome 75.0.3770.142

**Comment by xyfzkd** [comment]
just put chromedrive into /usr/local/bin, no need to double-click
