### ISSUE TITLE
Stoped working 

### ISSUE THREAD

**Issue by wemakefuture** [InstaPy/InstaPy#468]
Hey :)

Sorry for asking but 22 hours ago the script stoped working 

I screenshoted the issue...I didn't change anything but it just stoped. 

Server is update to date 

![img-20170803-wa0004](https://user-images.githubusercontent.com/28114725/28936270-80df1d44-7887-11e7-8544-f0a380afa6d9.jpg)

**Comment by converge** [comment]
same here

**Comment by converge** [comment]
this fix the problem: https://github.com/timgrossmann/InstaPy/pull/465/commits/112b1796c51f4eb86c72f4536d5d323aa8c17522

**Comment by wemakefuture** [comment]
Sorry guys i didnt find it. just scrolled over it using my smartphone. just saw it thank you for helping me out man. nice one >)

**Comment by wemakefuture** [comment]
@timgrossmann closed <3

**Comment by Naramsim** [comment]
@wecanfuture before filing issues, please check if somebody already did it.
