### ISSUE TITLE
couldn't post comment tap to retry  (instapy)

### ISSUE THREAD

**Issue by tooxiic49** [InstaPy/InstaPy#4680]
Hello, 
j'ai un soucis.
quand je lance instapy depuis 2 jours, lorsque le bot vient like ou commenter un post celui ci affiche : 
couldn't post comment tap to retry 
pourquoi ? :(

**Comment by tooxiic49** [comment]
tout fonctionne avec mon autre compte, mais pas celui ci ! :(

**Comment by redsector72** [comment]
Bonjour @tooxiic49,
de ce que je comprends il est question de temps et aussi l'autre compte aura le meme problème.
Il y a quelque chose qui fait comprendre qui est un bot and not une personne

**Comment by tooxiic49** [comment]
Bonjour,
je n'est pas compris ton message ? 
J'ai actuellement deux comptes instagram. 
sur l'un le bot fonctionne parfaitement mais sur l'autre, celui ne veux pas liker n'y commenter.
Pourtant le script est identique :(

**Comment by tooxiic49** [comment]
--> Image Liked!
INFO [2019-07-19 12:42:52] [romain.m__]  -------- WARNING! Image was NOT liked! You are have a BLOCK on likes!
INFO [2019-07-19 12:42:52] [romain.m__]  Tag: b'pikefishing'
INFO [2019-07-19 12:42:52] [romain.m__]  Tag [2/5]
INFO [2019-07-19 12:42:52] [romain.m__]  --> b'brochet'

voici ce qu'il me mets

**Comment by ghost** [comment]
> --> Image Liked!
> INFO [2019-07-19 12:42:52] [romain.m__] -------- WARNING! Image was NOT liked! You are have a BLOCK on likes!
> INFO [2019-07-19 12:42:52] [romain.m__] Tag: b'pikefishing'
> INFO [2019-07-19 12:42:52] [romain.m__] Tag [2/5]
> INFO [2019-07-19 12:42:52] [romain.m__] --> b'brochet'
> 
> voici ce qu'il me mets

There are tons of discussions in this project forum.

**Comment by tooxiic49** [comment]
> > -> Image aimé! 
> > INFO [2019-07-19 12:42:52] [romain.m__] -------- AVERTISSEMENT! L'image n'a PAS été aimée! Vous avez un BLOC sur les goûts! 
> > INFO [2019-07-19 12:42:52] [romain.m__] Tag: b'pikefishing ' 
> > INFO [2019-07-19 12:42:52] [romain.m__] Tag [2/5] 
> > INFO [ 2019-07-19 12:42:52] [romain.m__] -> b'brochet '
> > voici ce qu'il me mets
> 
> Il y a des tonnes de discussions dans ce forum de projet.

je ne trouve pas grand chose :(

**Comment by tooxiic49** [comment]
de plus je suis repasser sur chrome 72 et non 75 mais ça ne fonctionne toujours pas
----------------------
INFO [2019-07-21 14:01:14] [maudet.r_design]  Like# [1/10]
INFO [2019-07-21 14:01:14] [maudet.r_design]  https://www.instagram.com/p/B0LGNxbBZgk/
INFO [2019-07-21 14:01:18] [maudet.r_design]  Image from: b'mynorway'
INFO [2019-07-21 14:01:18] [maudet.r_design]  Link: b'https://www.instagram.com/p/B0LGNxbBZgk/'
INFO [2019-07-21 14:01:18] [maudet.r_design]  Description: b'Magical moment in the Lofoten Islands \xf0\x9f\x87\xb3\xf0\x9f\x87\xb4\xe2\x9c\xa8\n#norway\nPhoto by @ingridraadim'
INFO [2019-07-21 14:01:18] [maudet.r_design]  Location: b'Norway'
INFO [2019-07-21 14:01:31] [maudet.r_design]  --> Image Liked!
INFO [2019-07-21 14:01:34] [maudet.r_design]  --> Not commented
INFO [2019-07-21 14:01:35] [maudet.r_design]  --> Not following
INFO [2019-07-21 14:01:36] [maudet.r_design]  Like# [2/10]
INFO [2019-07-21 14:01:36] [maudet.r_design]  https://www.instagram.com/p/B0LUt_wgNa3/
INFO [2019-07-21 14:01:40] [maudet.r_design]  Image from: b'aritz_atela'
INFO [2019-07-21 14:01:40] [maudet.r_design]  Link: b'https://www.instagram.com/p/B0LUt_wgNa3/'
INFO [2019-07-21 14:01:40] [maudet.r_design]  Description: b'[ Stunning sunset at Gaztelugatxe ]\n.\n.\n.\n#addicted_to_basque #gaztelugatxe #visiteeuskadi #bizkaiaturismo #bbctravel #fujifilmglobal #fujifilm_xseries #earthpix #earthofficial #earthcapture #officialstoppers #depthofearth #dragonstone #esfujifilmxprint #earth_shotz #special_shots #earth #natgeo #awesome_earthpix #naturelovers_gr'
INFO [2019-07-21 14:01:40] [maudet.r_design]  Location: b'San Juan de Gaztelugatxe'

no problem whit my second account !

**Comment by tooxiic49** [comment]
Up? :/

**Comment by Pangolino2a** [comment]
Tooxiic Supprime le fichier cookie dans les logos et ça va marcher baisse tes likes ou ajoute un délais entre les likes
