### ISSUE TITLE
(randomly?) alternate actions

### ISSUE THREAD

**Issue by FeatherKamisori** [InstaPy/InstaPy#4681]
Hi,
i think i had seen an old question without answer on the subject but i cannot find it anymore.

I would like to know if it is possible to alternate, and what is more randomly alternate, between action types?

For example follow/like/comment/unfollow/follow one day
unfollow/follow/comment/like/follow the next

thank you.

**Comment by bjspi** [comment]
I think you should code it yourself.
E.g. do a for-loop, and than randomly do one of your desired actions randomly.

**Comment by FeatherKamisori** [comment]
I have absolutely no idea how to do this but i'll just google it then. Thank you.
