### ISSUE TITLE
Code is ridden with repetition

### ISSUE THREAD

**Issue by ctrlsam** [InstaPy/InstaPy#4682]
There is a lot of code that is repeated multiple times throughout. For example `relationship_tools` is a 900 line file and has A LOT of repeated code, seen by looking at the start of every function. This needs to be cleaned up as it's not maintainable in it's current state.

**Comment by breuerfelix** [comment]
are you able to help us refactoring this code ? this would help ALOT since refactoring the code base is always a step in the right direction :)

**Comment by ctrlsam** [comment]
Done some changes, have a look here #4807
