### ISSUE TITLE
Temp Block on Linux but not Windows

### ISSUE THREAD

**Issue by Mr-HaleYa** [InstaPy/InstaPy#4686]
## Expected Behavior
run on both platforms
## Current Behavior
I have ran Instapy on Linux for months and it has worked flawlessly, but since the last few Instagram updates, instapy won't follow anybody. As soon as it tries to follow someone it says "might be temporarily blocked" then repeats that. I have tried uninstalling and reinstalling multiple times to no avail, I even tried a whole new server to rule out IP blocking. Also, I waited a whole month to see if it was a timed block. 
It seems since the last update Instapy in a headless browser has stopped working. When I run Instapy on my windows PC it works perfectly, no errors at all except when I try to run it in headless mode. 
## Possible Solution (optional)
If you're experiencing an issue on any type of Linux computer or server try switching to Windows to see if will work (at least until the code is fixed)...
## InstaPy configuration
 My modified version of quickstart.py
This is the code I run on Windows and Linux, the only difference is I change headless_browser=True to headless_browser=False on Windows (otherwise it doesn't work)

```
# imports

from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'Username'
insta_password = 'pass'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    # general settings

    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_following=6000,
                                    min_followers=30,
                                    min_following=100)

    session.set_skip_users(skip_private=False)

    # activities

    session.follow_likers(['Users I want it to follow'], photos_grab_amount = 1, follow_likers_per_photo = 800, randomize=False, sleep_delay=7000, interact=False)
```

**Comment by sionking** [comment]
headless_browser is highly detectable.
