### ISSUE TITLE
ANYONE has Instapy still running? Read this!

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#4687]
Guys, there definitely has been an attack on what we all here hold most dear :P Likes blocked/not registering, follow blocks etc.

For me and many others pausing for a week AND then going at immaterial speeds (1 like per couple of hours) - still results in blocks again.

QUESTION:
If you are still running Instapy regularly AND either did not have a block at all OR were able to overcome it - can you please post:

1. Platform/browser/version
2. Session length/speed/frequency
3. Autorun settings (any adjustments/settings you are using)
4. Your country/account status (new/old/how long with instapy/etc)

I hope people like that still exist and maybe it will help to figure out a way...
So, anyone? :)

**Comment by nazariyv** [comment]
There was no attack. They just changed their html mark up a bit from what I can tell. I have opened a PR with the fix: https://github.com/timgrossmann/InstaPy/pull/4689

**Comment by ardagoktas** [comment]
There is a new monthly limit of 6000 follows. So if you were following 1000 people a day, you should wait a month for your blocks to disappear. Because even after a week maybe you will be able to follow 1-2 people or perform other actions but after that little action, you'll be blocked again. I've been through the same thing. After blocks have gone for good, you should follow 180-190 people per day at most.

**Comment by Mr-HaleYa** [comment]
I run it on windows and it works. I run it on Linux and it doesn't (I get instantly blocked). [https://github.com/timgrossmann/InstaPy/issues/4686](#4686)

**Comment by Tachenz** [comment]
@nazariyv this thread is about like blocks.

@ardagoktas - I was never even close to that limit. Talking about like block...

**Comment by Tachenz** [comment]
But basically, what are your settings now and how long have you been running since the last block?

**Comment by ljacobo** [comment]
Anyone still blocked? At this moment i can only do Likes, follows are blocked.

**Comment by Good-Kat** [comment]
running on unix server. headless. still blocked follows and likes

**Comment by cleversonledur** [comment]
I am blocked for following. Just a few likes per day and my account get locked for likes also.

**Comment by Tachenz** [comment]
I think everyone is blocked one way or another.
@breuerfelix is trying to find a workaround. Message him if you know Python and want to help testing
