### ISSUE TITLE
No Likes given by bot

### ISSUE THREAD

**Issue by tourhuntr** [InstaPy/InstaPy#4695]
I'm currently having a problem: i'm using the bot to like and comment some posts and then sleep. control it with quota supervisor.
The bot says in the logs, that he likes the post, but if i check the url in the browser, there are no like to see. it also dont comments anymore... pls help.

running it on a raspi 3+

## InstaPy configuration

# !/usr/bin/python2.7
import random
import yaml
import os
from instapy import InstaPy
from instapy.util import smart_run

# let's go! :>
while True:
 current_path = os.path.abspath(os.path.dirname(__file__))
 data = yaml.safe_load(open("%s/data.yaml" % (current_path)))
 friendlist = data['friendlist']
 session = InstaPy(username='xxx', password='xxx',headless_browser=False,multi_logs=True)

 with smart_run(session):
    hashtags = ['xxx']]
    random.shuffle(hashtags)
    my_hashtags = hashtags[:10]

    # general settings
    session.set_blacklist(enabled=True, campaign='bike')
    session.set_dont_like(['sad', 'rain', 'depression'])
    session.set_dont_include('friendlist')
    session.set_do_comment(enabled=True, percentage=100)
    session.set_comments([
                             u'What an amazing shot! :heart_eyes: What do '
                             u'you think of my recent shot?',
                             u'Wonderful!! :heart_eyes: I would be honored '
                             u'if you would checkout my images and tell me '
                             u'what you think. :wink:',
                             u'This is awesome!! :heart_eyes: Any feedback '
                             u'for my photos? :wink:',
                             u'This is awesome!! :heart_eyes:  maybe you '
                             u'like my photos, too? :wink:',
                              ],
                           media='Photo')
    session.set_do_like(True, percentage=100)
    session.set_delimit_liking(enabled=True, max=50, min=0)
    session.set_delimit_commenting(enabled=True, max=5, min=0)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=15000,
                                    max_following=2000,
                                    min_followers=0,
                                    min_following=0)

    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes","comments"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes=(100, 800),
                                 peak_comments=(20, 250),
                                 peak_follows=(200, None))

    session.set_user_interact(amount=1, randomize=False, percentage=100)

    # activity
    session.like_by_tags(my_hashtags, amount=150, media=None)
    session.end()

**Comment by bjspi** [comment]
https://github.com/timgrossmann/InstaPy/issues/4676
