### ISSUE TITLE
InstaPy is skipping everything

### ISSUE THREAD

**Issue by fraphy** [InstaPy/InstaPy#4703]
## Expected Behavior
It worked just fine, from today it changed

## Current Behavior
INFO [2019-07-24 01:53:45] [gregy]  Ongoing Follow [1/135]: now following 'the_lovely_warrior'...
INFO [2019-07-24 01:53:48] [gregy]  User: 'the_lovely_warrior'  |> followers: 288  |> following: 455  |> relationship ratio: 0.63
INFO [2019-07-24 01:53:48] [gregy]  the_lovely_warrior is private account, by default skip

INFO [2019-07-24 01:53:48] [gregy]  Ongoing Follow [2/135]: now following 'nobodyknowwhoamlhahahahaha'...
INFO [2019-07-24 01:53:51] [gregy]  User: 'nobodyknowwhoamlhahahahaha'  |> followers: 12  |> following: 121  |> relationship ratio: 0.09
INFO [2019-07-24 01:53:51] [gregy]  User 'nobodyknowwhoamlhahahahaha's followers count is less than minimum limit  ~skipping user

INFO [2019-07-24 01:53:51] [gregy]  Ongoing Follow [3/135]: now following 'juanknavarro17'...
INFO [2019-07-24 01:53:54] [gregy]  User: 'juanknavarro17'  |> followers: 239  |> following: 1357  |> relationship ratio: 0.17
INFO [2019-07-24 01:53:54] [gregy]  juanknavarro17 is private account, by default skip

INFO [2019-07-24 01:53:54] [gregy]  Ongoing Follow [4/135]: now following 'joyycccce'...
INFO [2019-07-24 01:53:57] [gregy]  User: 'joyycccce'  |> followers: 188  |> following: 140  |> relationship ratio: 1.34
INFO [2019-07-24 01:53:57] [gregy]  joyycccce is private account, by default skip

INFO [2019-07-24 01:53:57] [gregy]  Ongoing Follow [5/135]: now following 'catherine_890413'...
INFO [2019-07-24 01:53:59] [gregy]  User: 'catherine_890413'  |> followers: 183  |> following: 670  |> relationship ratio: 0.27
INFO [2019-07-24 01:53:59] [gregy]  catherine_890413 is private account, by default skip

INFO [2019-07-24 01:53:59] [gregy]  Ongoing Follow [6/135]: now following 'evellynmalves'...
INFO [2019-07-24 01:54:02] [gregy]  User: 'evellynmalves'  |> followers: 832  |> following: 795  |> relationship ratio: 1.04
INFO [2019-07-24 01:54:02] [gregy]  evellynmalves is private account, by default skip

INFO [2019-07-24 01:54:02] [gregy]  Ongoing Follow [7/135]: now following 'jaancikaaa'...
INFO [2019-07-24 01:54:05] [gregy]  User: 'jaancikaaa'  |> followers: 165  |> following: 275  |> relationship ratio: 0.6
INFO [2019-07-24 01:54:05] [gregy]  jaancikaaa is private account, by default skip

INFO [2019-07-24 01:54:05] [gregy]  Ongoing Follow [8/135]: now following 'chiara_m_love'...
INFO [2019-07-24 01:54:08] [gregoriophotography]  User: 'chiara_m_love'  |> followers: 6  |> following: 204  |> relationship ratio: 0.02
INFO [2019-07-24 01:54:08] [gregy]  User 'chiara_m_love's followers count is less than minimum limit  ~skipping user

INFO [2019-07-24 01:54:08] [gregy]  Ongoing Follow [9/135]: now following 'juna.baxtadze'...
INFO [2019-07-24 01:54:11] [gregy]  User: 'juna.baxtadze'  |> followers: 673  |> following: 3279  |> relationship ratio: 0.2
INFO [2019-07-24 01:54:11] [gregy]  Number of posts (2865) of 'juna.baxtadze' exceeds the maximum limit given 1000

INFO [2019-07-24 01:54:11] [gregy]  Ongoing Follow [10/135]: now following 'facundolarracochea'...
INFO [2019-07-24 01:54:13] [gregy]  User: 'facundolarracochea'  |> followers: 211  |> following: 1665  |> relationship ratio: 0.12
INFO [2019-07-24 01:54:13] [gregy]  facundolarracochea is private account, by default skip

INFO [2019-07-24 01:54:13] [gregy]  Ongoing Follow [11/135]: now following 'ledesma_antonella'...
INFO [2019-07-24 01:54:15] [gregy]  User: 'ledesma_antonella'  |> followers: 355  |> following: 1830  |> relationship ratio: 0.19
INFO [2019-07-24 01:54:15] [gregy]  ledesma_antonella is private account, by default skip

INFO [2019-07-24 01:54:15] [gregy]  Ongoing Follow [12/135]: now following '_.__kobra__._'...
INFO [2019-07-24 01:54:18] [gregy]  User: '_.__kobra__._'  |> followers: 596  |> following: 3225  |> relationship ratio: 0.18
INFO [2019-07-24 01:54:18] [gregy]  _.__kobra__._ is private account, by default skip

INFO [2019-07-24 01:54:18] [gregy]  Ongoing Follow [13/135]: now following 'veronica_f._costa'...
INFO [2019-07-24 01:54:20] [gregy]  User: 'veronica_f._costa'  |> followers: 603  |> following: 1538  |> relationship ratio: 0.39
INFO [2019-07-24 01:54:21] [gregy]  veronica_f._costa is private account, by default skip

INFO [2019-07-24 01:54:21] [gregy]  Ongoing Follow [14/135]: now following 'alle.gragironi'...
INFO [2019-07-24 01:54:23] [gregy]  User: 'alle.gragironi'  |> followers: 1  |> following: 9  |> relationship ratio: 0.11
INFO [2019-07-24 01:54:23] [gregy]  User 'alle.gragironi's followers count is less than minimum limit  ~skipping user

INFO [2019-07-24 01:54:23] [gregy]  Ongoing Follow [15/135]: now following 'yesskaraca'...
INFO [2019-07-24 01:54:26] [gregy]  User: 'yesskaraca'  |> followers: 300  |> following: 288  |> relationship ratio: 1.04
INFO [2019-07-24 01:54:26] [gregy]  yesskaraca is private account, by default skip

INFO [2019-07-24 01:54:26] [gregy]  Ongoing Follow [16/135]: now following 'magabi.fk'...
INFO [2019-07-24 01:54:29] [gregy]  User: 'magabi.fk'  |> followers: 394  |> following: 386  |> relationship ratio: 1.02
INFO [2019-07-24 01:54:29] [gregy]  magabi.fk is private account, by default skip

INFO [2019-07-24 01:54:29] [gregy]  Ongoing Follow [17/135]: now following 'mariadi_maro'...
INFO [2019-07-24 01:54:31] [gregy]  User: 'mariadi_maro'  |> followers: 59  |> following: 155  |> relationship ratio: 0.38
INFO [2019-07-24 01:54:31] [gregy]  mariadi_maro is private account, by default skip

INFO [2019-07-24 01:54:31] [gregy]  Ongoing Follow [18/135]: now following 'nr_ns6'...
INFO [2019-07-24 01:54:34] [gregy]  User: 'nr_ns6'  |> followers: 300  |> following: 1340  |> relationship ratio: 0.22
INFO [2019-07-24 01:54:34] [gregy]  Number of posts (4) of 'nr_ns6' is less than the minimum limit given 10

INFO [2019-07-24 01:54:34] [gregy]  Ongoing Follow [19/135]: now following 'peppe_contegreco'...
INFO [2019-07-24 01:54:36] [gregy]  User: 'peppe_contegreco'  |> followers: 453  |> following: 427  |> relationship ratio: 1.06
INFO [2019-07-24 01:54:36] [gregy]  peppe_contegreco is private account, by default skip

INFO [2019-07-24 01:54:36] [gregy]  Ongoing Follow [20/135]: now following 'rodybecerril'...
INFO [2019-07-24 01:54:39] [gregy]  User: 'rodybecerril'  |> followers: 390  |> following: 1439  |> relationship ratio: 0.27
INFO [2019-07-24 01:54:39] [gregy]  rodybecerril is private account, by default skip

INFO [2019-07-24 01:54:39] [gregy]  Ongoing Follow [21/135]: now following 'ramirezccam'...
INFO [2019-07-24 01:54:41] [gregy]  User: 'ramirezccam'  |> followers: 925  |> following: 2255  |> relationship ratio: 0.41
INFO [2019-07-24 01:54:41] [gregy]  ramirezccam is private account, by default skip

## InstaPy configuration
 session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=9999,                                        
                                        max_following=5000,
                                        min_followers=29,
                                        min_following=29,
                                        min_posts=10,
                                        max_posts=1000)
    
    
    session.set_dont_like(["pizza", "#store"])
    
    
    # activity
    amount_number=200
    session.set_user_interact(amount=1, randomize=True, percentage=29, media='Photo')
    session.set_do_like(enabled=True, percentage=100)
    session.set_do_comment(enabled=False, percentage=0)
    session.follow_user_following(['friend1', 'friend2'], amount=amount_number, randomize=False, interact=True, sleep_delay=300)

**Comment by fpibbs** [comment]
Same problem here...

**Comment by christophe-duc** [comment]
this is caused by an instagram change, they decided now to return only private accounts first. In an obvious attempt to minimize bot interaction. You can try to use follow_likers to replace follow_user_followers or follow_user_following.

**Comment by LRB-DD-00** [comment]
I have the exact same problem. Did anyone find the solution ?

**Comment by NLJames** [comment]
> this is caused by an instagram change, they decided now to return only private accounts first. In an obvious attempt to minimize bot interaction. You can try to use follow_likers to replace follow_user_followers or follow_user_following.

did this work for anyone?

**Comment by gitpash** [comment]
> > this is caused by an instagram change, they decided now to return only private accounts first. In an obvious attempt to minimize bot interaction. You can try to use follow_likers to replace follow_user_followers or follow_user_following.
> 
> did this work for anyone?

yes, this works for me, in fact this `follow_likers` method is not exact same as `follow_user_followers` but kinda do the job
