### ISSUE TITLE
row 120 of instapy.py error

### ISSUE THREAD

**Issue by Millee94** [InstaPy/InstaPy#4704]
Hey
Getting an error when i try and us the run mac file

/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 120
    random_user_agent: bool = False)
                     ^
SyntaxError: invalid syntax

is the error showing up in the terminal.

Had a look, tried removing the code, and it bumps the error to line 119 if i do this. This is the first time ive ever used python so unclear how to fix this. The file running is the default install one.

**Comment by christophe-duc** [comment]
i don't think instapy supports python 2.7 anymore.

**Comment by roncam82** [comment]
I have the same error but on python 3.7.0

Traceback (most recent call last):
  File "simple_but_effective_follow_followers_unfollow_unfollowers_aftertfivedays.py", line 9, in <module>
    from instapy import InstaPy
  File "/home/pi/Python-3.7.0/Python/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/home/pi/Python-3.7.0/Python/InstaPy/instapy/instapy.py", line 120
    random_user_agent: bool = False)
                     ^
SyntaxError: invalid syntax

**Comment by christophe-duc** [comment]
May be @breuerfelix can help.

**Comment by Millee94** [comment]
I did download the newest version of python, but that’s how it installed for some reason?


On 25/07/2019, at 9:35 AM, Christophe <notifications@github.com<mailto:notifications@github.com>> wrote:


May be @breuerfelix<https://github.com/breuerfelix> can help.

**Comment by ajankuv** [comment]
> I have the same error but on python 3.7.0
> 
> Traceback (most recent call last):
> File "simple_but_effective_follow_followers_unfollow_unfollowers_aftertfivedays.py", line 9, in 
> from instapy import InstaPy
> File "/home/pi/Python-3.7.0/Python/InstaPy/instapy/**init**.py", line 3, in 
> from .instapy import InstaPy
> File "/home/pi/Python-3.7.0/Python/InstaPy/instapy/instapy.py", line 120
> random_user_agent: bool = False)
> ^
> SyntaxError: invalid syntax

@roncam82

I had the same issue, I had to rebuild my stack. And also remove virtenv and reinstall with pip3 and it worked

**Comment by breuerfelix** [comment]
well we don't support python2 thats for sure but we also removed this random user agent again in the next update which will be released today :)

well but it passed the tests on python 3.3 so I think it should work 100% :)

are you sure you installed it with pip3 and python3 ?

**Comment by Millee94** [comment]
I suspect the issue is that I have python 2 by default on my mac, and have now installed python 3. how can i specify to use python 3?

**Comment by breuerfelix** [comment]
when executing you type `python Quickstart.py` right ? now just do `python3 Quickstart.py` :)
