### ISSUE TITLE
Feature request - Run processes asynchronously

### ISSUE THREAD

**Issue by jeffreylm** [InstaPy/InstaPy#471]
**Unfollow process**

One of the processes that would lend it's self to being run asynchronously is the unfollow processes. During the 10 min break so much could be done.  

There are most probally other processes that could come to mind by others who know the ins and out of the script from a programming level, but for now this is what I have come to realize.

**Comment by sionking** [comment]
Just run the 2 process thoghter it will work ( I run 3 processes: unfollow/interact user/interact tag)
more than 3 monthes and it works fine!

**Comment by imbarismustafa** [comment]
@sionking do you keep restarting the program? is there a way to make a loop so it keeps repeating with 5 minute break at the end of the 3rd process?
