### ISSUE TITLE
-------- WARNING! Image was NOT liked! You are have a BLOCK on likes!

### ISSUE THREAD

**Issue by brocool** [InstaPy/InstaPy#4711]
I have no blocks at all. when i access my account via my smartphone it's not blocked to like. hmm????

**Comment by kubelkowaty** [comment]
Delete file with cookies. It helped me in similar situation :)

**Comment by Cathaldus** [comment]
> Delete file with cookies. It helped me in similar situation :)

This is just a temporary thing though. I struggle with the same problem. I delete it and a couple of hours later the same problem appears. 
Although it's just one of three accounts, they all have the same settings but this one account causes that problem. Maybe a coder is able to help us with this problem.

**Comment by maxxfly** [comment]
hi.

I try with 2 different accounts : I have the same issue.
If I check on the target picture, I can see that instapy did not like the picture... hum...
It is for this raeson ze have the error message.

The good question is to know why @Catalystshu can like with 2 accounts and not on the 3th.

Indeed, I try manually to like a picture with  my 2 accounts and I have no problem.

**Comment by breuerfelix** [comment]
https://github.com/timgrossmann/InstaPy/pull/4696 try this :)

**Comment by maxxfly** [comment]
in my case, I have just need to clean my cookies

**Comment by saahil1292** [comment]
i tried deleting cookies and creating them again, but this doesn't work. i am still getting this warning. Perhaps they are tracing the IP?

**Comment by Tkd-Alex** [comment]
Same for me, re-create the cookie doesn't help

**Comment by dimhvm** [comment]
> Same for me, re-create the cookie doesn't help

Same for me as well! I have tried almost everything, i deleted all the cookies several times, changed the IP address...nothing worked! Moreover my max number of likes is set to 50, i don't think instagram blocked me for 50 likes... please help :(

**Comment by johnvfitness** [comment]
Same Error :(

**Comment by maxxfly** [comment]
Currently I try without the headless with Firefox. Less issues. Just something I have a popin in instagram that explain the action is blocked and I need to try later. But for instapy the like is okay (in fact no).

I changed the value of the nap after the like for avoid that

**Comment by Pangolino2a** [comment]
Same error !!!
