### ISSUE TITLE
couldnt post comment 

### ISSUE THREAD

**Issue by amirrezasbr** [InstaPy/InstaPy#4712]
`
with smart_run(session):
  """ Activity flow """	
	
  session.set_do_comment(enabled=True, percentage=35)

  session.set_comments(['awesome', 'fantastic', 'terrefic'])
`

i try to post comments but it shows this error every time:
INFO [2019-07-25 16:38:30]  Sessional Live Report:

	|> No any statistics to show

INFO [2019-07-25 16:38:30] Session ended!

**Comment by breuerfelix** [comment]
you have to add some interactions like interact_with_followers or smth like that :)
