### ISSUE TITLE
Like specific tag: actually liking individual letters

### ISSUE THREAD

**Issue by FeatherKamisori** [InstaPy/InstaPy#4713]
## Expected Behavior
like by specific tag

## Current Behavior
liking individual letters from the tag: t,a,g, etc.

## InstaPy configuration
#session.like_by_tags("taginquestion", amount=5, randomize=True)

note that i also use like session.like_by_tags(randomtags, amount=5, randomize=True) from a list and that this works perfectly. 

Thank you for any help.

**Comment by christophe-duc** [comment]
try with ["taginquestion"] (add the brackets around your taginquestion)

**Comment by FeatherKamisori** [comment]
Yeah all good now sorry and thank you.
