### ISSUE TITLE
Last follow is not verified!!!

### ISSUE THREAD

**Issue by davanderlinden** [InstaPy/InstaPy#4717]
im running follow by tags and every time it finds someone to follow i get the same message "last follow could not be verified, you might be clocked from following" but im definitly not blocked from following.

within session im using---session.follow_by_tags(['craft'], amount=300)

**Comment by univers3** [comment]
Same happening here!
Look like that Instapy miss to hit the "Follow" button properly and when it check the follow status of the user it sees that is still unfollowed.

Maybe a new web Instagram's UI?

Did you find any workaround?

Instapy became useless for me :(

**Comment by tjorion** [comment]
same here : "Last follow is not verified" and it definitely doesn't work. I'm pretty sure I'm not blocked, at least not via my phone
