### ISSUE TITLE
New error third time in a row... :(

### ISSUE THREAD

**Issue by n0sw34r** [InstaPy/InstaPy#472]
Hello I got new error anybody have same issue or know how to fix it?
Thanks a lot!
![image](https://user-images.githubusercontent.com/30392165/28972394-c8ca891a-792f-11e7-9250-5012c5f716f2.png)

**Comment by westondeboer** [comment]
The login box was moved, if you update to the latest version, It should fix that error.

**Comment by n0sw34r** [comment]
New version is working fine :+1:
