### ISSUE TITLE
Story View - Feature Request

### ISSUE THREAD

**Issue by kushpvo** [InstaPy/InstaPy#4720]
Just the way we can like posts of users by finding them through hashtags, we should add an option to view story of users by finding them through hashtags. (I do not mean watching the hashtag story but finding users with hashtags and viewing their stories)

In the same manner, a feature where you could view story of users who are following a certain account e.g. take the followers of @instagram and view those followers' stories

Ignore me if this has already been suggested

**Comment by kushpvo** [comment]
Reference : https://jarvee.com/knowledge-base/instagram-story-viewer-tool/

**Comment by tacocat777** [comment]
add this feature please
