### ISSUE TITLE
WARNING! Image was NOT liked! You are have a BLOCK on likes!

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#4721]
Hello i get having always this error : 

 -------- WARNING! Image was NOT liked! You are have a BLOCK on likes!
same problem for comments.

but i still can like and comment when i open browser manually or on my phone.

any ideas please ? @uluQulu 

Many thanks.

**Comment by doricardo-zz** [comment]
The same for here, I don't what is happening

**Comment by dsmh** [comment]
I'm Facing the same issue. Is there any way to prevent this?
