### ISSUE TITLE
RPi cron not executing

### ISSUE THREAD

**Issue by kevmok** [InstaPy/InstaPy#4735]
## Expected Behavior
I am trying to execute my instapy script every 30 minutes from 8am-2pm and 6pm-11pm
## Current Behavior
Not executing at all

## InstaPy configuration
This is what I wrote on cron
*/30 8-14,18-23  * * * cd /home/pi/InstaPy && /usr/bin/python3 ./quickstart.py

My instapy script is on that folder "/home/pi/InstaPy" and I guess I need to use python3 since that's the command I use whenever I run the script on the command line...

**Comment by jctommasi** [comment]
try: 
`*/30 8-14,18-23 * * * /usr/bin/python3 /home/pi/InstaPy/quickstart.py`

**Comment by kevmok** [comment]
Still doesn't do anything :/ maybe it isn't python3?

**Comment by gosadaque** [comment]
How do you generally startup your script? Which command do you use in bash?

Other problem may be: Are you using any relative paths like ./ or ../ instead of going by root /path/to/script?

**Comment by kevmok** [comment]
Usually on the RPi's command line I do
`cd InstaPy`
`python3 quickstart.py`

I'm not super advanced with command lines, so the questions about the paths, I am not so sure! 
Thanks for the help

**Comment by kevmok** [comment]
I checked my environmental variables by doing 
`env -i /bin/bash --noprofile --norc`
and ran
`/usr/bin/python3 /home/pi/InstaPy/quickstart.py`

and the script ran, so I don't think I am having issues with pathing... I also checked my syslog and the only thing from cron that shows is:
`"CRON[3859]: (pi) CMD (usr/bin/python3 /home/pi/InstaPy/quickstart.py)"`

but the script does not run

**Comment by gosadaque** [comment]
Can you post your script?
Remember to blank username and password, when you‘re posting it

**Comment by jctommasi** [comment]
I'm facing with this issue with one of my vps, I fix it adding "SHELL=/bin/Bash" at top of cron file.

vps's S.O. is Ubuntu 16.04
