### ISSUE TITLE
says Warning: could be blocked from following, but i can do it manually

### ISSUE THREAD

**Issue by Jbry123** [InstaPy/InstaPy#4738]
## Expected Behavior
follow people
## Current Behavior
says warning: may be blocked from following, but on my phone i can do it.

## Possible Solution (optional)
changed html?
## InstaPy configuration
quickstart and tested multiple types of engagement strategies.

trying to reopen https://github.com/timgrossmann/InstaPy/issues/1140

**Comment by kenita3222** [comment]
i have the same problem

**Comment by Jbry123** [comment]
Yeah I deleted the following portion so it would still like, that’s a hack for now

**Comment by Jbry123** [comment]
Like and comment*

**Comment by papillon-unix** [comment]
same problem on one account only (am running Instapy on two)

**Comment by Jbry123** [comment]
Same^^^ but I haven’t even been following many people, are there new limits?
