### ISSUE TITLE
isdownorjustme website not opened in some ISPs

### ISSUE THREAD

**Issue by Mehran** [InstaPy/InstaPy#4739]
I have some loading issue with website on some ISP's, any better way?

**Comment by redsector72** [comment]
Seems like this new addition has led me to be banned also from isitdownorjust.me, not only instagram. I have disabled it.

To me there is no sense in checking if internet is working (check1) and if instagram is (up).
In both cases, no harm will be done.

**Comment by converge** [comment]
It will be great if you guys could help us testing it. We(community) tested the 0.5.7 for some days and had no issues.

join us: https://discord.gg/aDMxgR

InstaPy has no control over the connection process before, and when something went wrong, we didn't have much information. This new feature add this layer of verification before moving forward, if there is something wrong in the connection process, it will show exactly where there is something wrong.

This is also nice for the one that uses proxies, the proxy connection is checked on its first step. Something IG is down, or slow, and people think there is something wrong, and it's just a IG server issue.

**Comment by mwargan** [comment]
@redsector72 how did you disable it? I’m running into a similar issue where it says Instagram servers are down :/

**Comment by converge** [comment]
Should we have this feature as optional?

**Comment by redsector72** [comment]
To disable it just edit login_util.py just comment the line 195 at the moment, like this

#return False

**Comment by mwargan** [comment]
@converge not necessarily as it doesn’t really affect the end process of the scripts. I’ve updated InstaPy on another machine and it works fine. Let me do some more debugging to figure out what the issue is with the account I’m trying to log in to.

**Comment by Mehran** [comment]
some content is not loaded on some ISP's, I think this use some API to connect another site, after 3 Mins it continues, time-out would help?

**Comment by mwargan** [comment]
@converge I think the bigger issue is that this new try and except clause masks other issues, specifically: before we were able to see messages like “chrome not reachable” and such, now it’s just this error. This confuses people as to what the issue is, and I suspect that’s what’s happening in the latest issues raised.
