### ISSUE TITLE
Following photo likers of a user not working

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4740]
## Current Behavior
INFO [2019-07-30 21:10:42] []  ---> ..... has already been followed 1 times

Few likes, not guaranteed you don't follow these likers already.
Got photo likers: ['.-']

INFO [2019-07-30 21:10:48] ----]  ---> .. has already been followed 1 times

## Possible Solution (optional)
Seems he's getting the first likes obviously he's going to pick the users who have already follow, that's how insta works.

## InstaPy configuration

    session.follow_likers([''], photos_grab_amount = 2, follow_likers_per_photo = 10, randomize=True, sleep_delay=600, interact=False)

**Comment by sharmanshah** [comment]
+1. I've been facing the same issue since yesterday. I've updated to 0.5.7 and don't know if it's got something to do with that.

**Comment by Carmeli13** [comment]
+1 Same issue here. Also after I updated to 0.5.7

**Comment by pezzotto** [comment]
+1 same here

**Comment by octavius-1** [comment]
+1 Same here.
Two issues I'm facing:
1. The one with the "Few likes, not guaranteed you don't follow these likers already." warning
2. Couldn't find like button, might be a video. But when you open the link IS NOT A VIDEO.

**Comment by AdriaanRoets** [comment]
+1 same here

**Comment by pamsn** [comment]
+1 same here

**Comment by christophe-duc** [comment]
the pull request that correct this has been merged into dev, so it will be included into 0.5.8.

[https://github.com/timgrossmann/InstaPy/pull/4734](url)

**Comment by pezzotto** [comment]
> the pull request that correct this has been merged into dev, so it will be included into 0.5.8.
> 
> [https://github.com/timgrossmann/InstaPy/pull/4734](url)

I've updated to 0.5.8 but still facing same issue, any advice?

**Comment by christophe-duc** [comment]
tested again here, and works without problem (0.5.8), may be you are not really running 0.5.8?

log here:

Getting likers from user:  lamebook 

Got  24 , returning  2  links:  ['https://www.instagram.com/p/B0nIAc9AhCO/', 'https://www.instagram.com/p/B0l71nggF7o/']
opening likes
  17/10 [===================================+]  170%    |> Elapsed: 1.73 seconds    |> ETA: 0.71 seconds      

Got 17 likers shuffled randomly whom you can follow:
['paolorigotti', 'octobertessie', 'hyderkelly', 'williamstopford', 'drich1515', 'martinisky725', 'jassvinder', 'margaret_d_h', 'mikemilford', 'misschristina40', 'thehoneysuckleblue', 'chemsnacks', 'bassethoundfromitaly', 'ainecarr', 'marieelyselavallee', 'momentomori8', 'therealpanderella']

INFO [2019-08-02 10:36:13] [xxx]  ---> martinisky725 has already been followed 1 times

INFO [2019-08-02 10:36:16] [xxx]  User: 'paolorigotti'  |> followers: 15047  |> following: 2099  |> relationship ratio: 7.16
INFO [2019-08-02 10:36:16] [xxx]  --> Not a valid user: User 'paolorigotti's followers count exceeds maximum limit  ~skipping user

INFO [2019-08-02 10:36:16] [xxx]  ---> momentomori8 has already been followed 1 times

INFO [2019-08-02 10:36:19] [xxx]  User: 'hyderkelly'  |> followers: 164  |> following: 290  |> relationship ratio: 0.56
INFO [2019-08-02 10:36:19] [xxx]  --> Not a valid user: hyderkelly is private account, by default skip

INFO [2019-08-02 10:36:22] [xxx]  User: 'margaret_d_h'  |> followers: 60  |> following: 244  |> relationship ratio: 0.24
INFO [2019-08-02 10:36:22] [xxx]  --> Not a valid user: margaret_d_h is private account, by default skip

INFO [2019-08-02 10:36:22] [xxx]  ---> chemsnacks has already been followed 1 times

INFO [2019-08-02 10:36:25] [xxx]  User: 'octobertessie'  |> followers: 219  |> following: 405  |> relationship ratio: 0.54
INFO [2019-08-02 10:36:25] [xxx]  --> Not a valid user: octobertessie is private account, by default skip

INFO [2019-08-02 10:36:28] [xxx]  User: 'thehoneysuckleblue'  |> followers: 468  |> following: 369  |> relationship ratio: 1.26
INFO [2019-08-02 10:36:28] [xxx]  --> Not a valid user: thehoneysuckleblue is private account, by default skip

INFO [2019-08-02 10:36:32] [xxx]  User: 'bassethoundfromitaly'  |> followers: 845  |> following: 546  |> relationship ratio: 1.54
INFO [2019-08-02 10:36:34] [xxx]  Last follow is verified after reloading the page!
INFO [2019-08-02 10:36:34] [xxx]  --> Followed 'b'bassethoundfromitaly''!

**Comment by pezzotto** [comment]
@christophe-duc yes pip show confirm that it’s updated but still follow the first user..

Idk where is the problem, I’m using a raspberry pi 3b+

Edit: could be a problem with chromedriver? I’m using the latest symlinked in the asset folder instead the 2.36.post0

**Comment by alexsmedile** [comment]
Same issue here.
`Few likes, not guaranteed you don't follow these likers already.`
`Couldn't find liked counter button. May be a video.`

I've updated and nothing changed.

Any solution?

**Comment by pezzotto** [comment]
Hey guys.. is possible that this problem is caused by the new feature of ig that will hide count of likes?
I think it’s rolling up in these days.
But on my profile I still see the number of likes..

Edit: as ig says here: https://mobile.twitter.com/instagram/status/1151605657642029056?s=21

Are u from from a mentioned country?
