### ISSUE TITLE
Actions blocked with headless undetectable and proxy

### ISSUE THREAD

**Issue by bobdo12** [InstaPy/InstaPy#4743]
## Expected Behavior
Not get blocked. :)
## Current Behavior
I've added a residential rotation IP + disabled headless, but still get action blocked after few trials. Does anyone have an idea what could be the issue? Also, why even use headless in the first place? We can still run on linux machines without the --headless option enabled. It seems the detection of bots might be coming from something else. Please help!
## Possible Solution (optional)
Proxy and undetectable headless
## InstaPy configuration
Max 100 likes per day

**Comment by Tkd-Alex** [comment]
I think the problem is not related to instapy but with all types of automation.

I've the same issue with other bots, also with script made by my self.

I've a custom 4G proxy and the action blocked come anyway :sob:

- 20, 40s delay between likes
- 15 likes max per half hour
- random pause 15/30m
