### ISSUE TITLE
Bug google Version

### ISSUE THREAD

**Issue by raihan001** [InstaPy/InstaPy#4745]
new bug for chrome version. latest chrome version using 76 but in modul instapy only run in version 71-75...just install old version and work good again.. here the link  https://www.slimjet.com/chrome/download-chrome.php

**Comment by Tr1pke** [comment]
Same for me

**Comment by raihan001** [comment]
Just install manually google version 71-75 from this link https://www.slimjet.com/chrome/download-chrome.php

**Comment by raihan001** [comment]
I hope this resolve your problem
Command:
cd /usr/local/lib/python3.5/dist-packages/instapy_chromedriver
rm -f chromedriver_linux64
wget https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_linux64.zip
unzip chromedriver_linux64.zip
mv chromedriver chromedriver_linux64
rm -f chromedriver_linux64.zip
Go to your directory template and run your template
python3 example.py
and enjoy it
