### ISSUE TITLE
Not liked this post! ~more likes exist off maximum limit at XXX & BLOCK on likes

### ISSUE THREAD

**Issue by jamezun** [InstaPy/InstaPy#4746]
## Current Behavior

I have tried not to load the cookies by commented the line but I still have the following issues:

> Not liked this post! ~more likes exist off maximum limit at 712

> -------- WARNING! Image was NOT liked! You are have a BLOCK on likes!

Is there a big fix coming soon or is there a way to fix it? Because I tried a number of way to fix it but the problem still exisit :-(

## InstaPy configuration
session = InstaPy(username='donaldtrumpkissmyask', password='ineedhelp',headless_browser=True, disable_image_load=True, multi_logs=True)

    session.set_quota_supervisor(enabled=True,
                                  sleep_after=["likes", "comments_d", "follows", "unfollows"],
                                  sleepyhead=True, stochastic_flow=True, notify_me=True,
                                   peak_likes=(100, 700),
                                   peak_comments=(20, 200),
                                   peak_follows=(50, 700),
                                   peak_unfollows=(50, 700))

**Comment by dsmh** [comment]
I'm facing same problem

**Comment by jamezun** [comment]
I’m surprised why so little people talk about it:-(

**Comment by papillon-unix** [comment]
Same pb on one account, while the other account still continues to work perfectly fine..

**Comment by theveloped** [comment]
Try deleting your cookies before retrying and avoid opening Instagram on other windows or mobile. Does that help?

**Comment by papillon-unix** [comment]
no. Still banned. Will I have another account that runs Instapy and mobile app from the same IP and not get blocked.
The same script is running for these two accounts. Only difference is one being a little bit younger (the one that is blocked) than the other.

**Comment by jamezun** [comment]
@thevloped where does the cookies stored? Which directory?

**Comment by theveloped** [comment]
@jamezun have a look at issue #4077 

> you@server:~/InstaPy/logs/IG/IGMyNextCompany_cookie.pkl
> have you ever searched for it in the terminal? locate/find etc
> it has cookie in the name ;-)

**Comment by jamezun** [comment]
the problem still exist no matter how many times i deleted the cookies..

**Comment by jamezun** [comment]
is that true that chrome doesnt work anymore?
