### ISSUE TITLE
Instapy chromedriver in the repository needs an Update to work with the latest Chrome 76

### ISSUE THREAD

**Issue by xRyul** [InstaPy/InstaPy#4747]
Just had a fresh InstaPy reinstall. And noticed that it won't work with most up-to-date Chrome version 76. 

Chromedriver inside repository supports only 71-75 versions. As such it would require an update to work with the newest Chrome. 

It was an easy fix, I simply downloaded the new chromedriver from the official website. And then replaced the file in "C:\Users\...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\instapy_chromedriver"  with the new one. 

And it works now.

**Comment by Tr1pke** [comment]
Same for me

**Comment by raihan001** [comment]
I hope this resolve your problem

**Command:**
cd /usr/local/lib/python3.5/dist-packages/instapy_chromedriver
rm -f chromedriver_linux64
wget https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_linux64.zip
unzip chromedriver_linux64.zip
mv chromedriver chromedriver_linux64
rm -f chromedriver_linux64.zip
Go to your directory template and run your template
python3 example.py
and **enjoy it**

**Comment by xRyul** [comment]
> 
> 
> I hope this resolve your problem
> 
> **Command:**
> cd /usr/local/lib/python3.5/dist-packages/instapy_chromedriver
> rm -f chromedriver_linux64
> wget https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_linux64.zip
> mv chromedriver chromedriver_linux64
> rm -f chromedriver_linux64.zip
> Go to your directory template and run your template
> python3 example.py
> and **enjoy it**

yeah, this should work too if you are on Linux or Mac. 

Although, would be nice if @timgrossmann could update InstaPy, so it would come with the new updated chromedriver by **default**.

**Comment by ajankuv** [comment]
`latest_version=$(wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE -O -) && wget https://chromedriver.storage.googleapis.com/${latest_version}/chromedriver_linux64.zip`

Use this to ALWAYS snatch the newest drivers. I have a script that does then then drops it in the lib/python3.5/site-packages/instapy_chromedriver/ folder.

**Comment by HassenIO** [comment]
> I hope this resolve your problem
> 
> **Command:**
> cd /usr/local/lib/python3.5/dist-packages/instapy_chromedriver
> rm -f chromedriver_linux64
> wget https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_linux64.zip
> unzip chromedriver_linux64.zip
> mv chromedriver chromedriver_linux64
> rm -f chromedriver_linux64.zip
> Go to your directory template and run your template
> python3 example.py
> and **enjoy it**

Works for me :+1: Just add `chmod 755 chromedriver_linux64` to make it executable (otherwise you'll get `executable may have wrong permissions`).

Any idea when version 76 will be supported? Thanks

**Comment by beld159** [comment]
I'm super newbie to all this, could somebody add screenshots for where this replacement goes? That would be incredibly helpful.

**Comment by e1x4** [comment]
for me in windows:
1. download this https://chromedriver.storage.googleapis.com/index.html?path=76.0.3809.68/ 
2. go in C:\Users\....\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy_chromedriver
3. replace chromedriver_win32.exe with the new one

**Comment by bajaloreto** [comment]
This worked for me in macOS Mojave 10.14.5, using Instapy Quickstart:
1. Download latest chromedriver (76) from here: [https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_mac64.zip](https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_mac64.zip)
unzip the file and name it _chromedriver_mac64_
2. Launch Terminal to view hidden files with this commands: 
`$ defaults write com.apple.finder AppleShowAllFiles TRUE`
`$ killall Finder`
3. Using Finder go to: /Users/username/.pyenv/versions/3.7.4/lib/python3.7/sitepackages/instapy_chromedriver/
4. Replace the file chromedriver_mac64 with the new dowloaded version
5. Using Finder ALSO go to:
/usr/local/lib/python3.7/site-packages/instapy_chromedriver/
6. Again, replace the file chromedriver_mac64 with the new dowloaded version
7. Go back to terminal to hide back files with this commands:
`$ defaults write com.apple.finder AppleShowAllFiles FALSE`
`killall Finder`

**Comment by beld159** [comment]
@bajaloreto I cannot find a folder that is .pynev under my user, please help
<img width="778" alt="Screen Shot 2019-08-13 at 12 44 59 PM" src="https://user-images.githubusercontent.com/50464617/62968433-43cb0c00-bdc8-11e9-8ad5-f0502ca6e0bd.png">
