### ISSUE TITLE
InstaPy stops work for me.. Again..

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4750]
Hello,
instapy doesn't work for me again. Using Ubuntu 18.04 Desktop. Didn't change anything. Can anybody help me please? Thank you

`  INFO [2019-08-01 18:12:07] [myinstausername]Using built in instapy-chromedriver executable (version 2.46)
  ERROR [2019-08-01 18:12:08] [myinstausername]Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 5.0.0-23-generic x86_64)
  Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/instapy/browser.py", line 163, in set_selenium_local_session
  chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
  desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
  self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
  response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
  self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
  raise exception_class(message, screen, stacktrace)
  selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 5.0.0-23-generic x86_64)`

**Comment by ghost** [comment]
I manually downloaded 3 versions of chromedriver.
74.0.3729.6
75.0.3770.90
75.0.3770.140

Tried to replace chromedriver in /usr/local/lib/python3.6/dist-packages/instapy_chromedriver with downloaded files
same result

**Comment by ghost** [comment]
Tried:
sudo python3 -m pip uninstall instapy-chromedriver
sudo python3 -m pip uninstall instapy-chromedriver

still doesn't work instapy

**Comment by guztavoalves** [comment]
Try chromedriver v2.46
https://chromedriver.storage.googleapis.com/index.html?path=2.46/

**Comment by Tr1pke** [comment]
Same problem

**Comment by raihan001** [comment]
I post how to fix this issue before this post 😇🙏

**Comment by raihan001** [comment]
Just install manually google version 71-75 from this link https://www.slimjet.com/chrome/download-chrome.php

**Comment by Tr1pke** [comment]
The pity of course is that only servers and bots use out  dated software and instagram will also know this. Is it not possible to make it work with the latest version?

**Comment by raihan001** [comment]
Nope...for the reason may be developers need to fix this issue for update crome driver on instapy library..

**Comment by raihan001** [comment]
I hope this help you all
**My google version:**
root@xxxx:/usr/local/lib/python3.5/dist-packages/instapy_chromedriver# google-chrome --version
Google Chrome 76.0.3809.87

**My log:**
INFO [2019-08-02 02:31:01] [silvashop_acc]  Using built in instapy-chromedriver executable (version 2.46)
INFO [2019-08-02 02:31:03] [silvashop_acc]  Session started!
INFO [2019-08-02 02:31:03] [silvashop_acc]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2019-08-02 02:31:04] [silvashop_acc]  - Internet Connection Status: ok
INFO [2019-08-02 02:31:04] [silvashop_acc]  -- Connection Checklist [2/2] (Instagram Server Status)
INFO [2019-08-02 02:31:08] [silvashop_acc]  - Instagram WebSite Status: Currently Up
INFO [2019-08-02 02:31:08] [silvashop_acc]  - Instagram Response Time: 45.014 ms
INFO [2019-08-02 02:31:08] [silvashop_acc]  - Instagram Reponse Code: 200
INFO [2019-08-02 02:31:08] [silvashop_acc]  - Instagram Server Status: ok

 ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/root/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...
Issue with cookie for user silvashop_acc. Creating new cookie...
Instagram detected an unusual login attempt
A security code was sent to your Email: s*******4@gmail.com
Type the security code here: INFO [2019-08-02 02:31:44] [silvashop_acc]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 43.52 seconds]
INFO [2019-08-02 02:31:44] [silvashop_acc]  Session ended!


It's work for me only under 5 minutes resolved
Install last version chrome

**Command:**
cd /usr/local/lib/python3.5/dist-packages/instapy_chromedriver
rm -f chromedriver_linux64
wget https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_linux64.zip
mv chromedriver chromedriver_linux64
rm -f chromedriver_linux64.zip

Go to your directory template and run your template
python3 example.py
and **enjoy it**

**Comment by ghost** [comment]
@raihan001 thank you. tried it but got same result, instapy doesn't work

**Comment by raihan001** [comment]
Are you sure change the name from "chromedriver" to "chromedriver_linux64" after unzip?
I just try same your way, but the different only change the name in:
 /usr/local/lib/python3.6/dist-packages/instapy_chromedriver/<new download> to
 /usr/local/lib/python3.6/dist-packages/instapy_chromedriver/chromedriver_linux64

If you not change the name, that don't work and give you an error...

**Comment by raihan001** [comment]
My python version is 3.5
So in my way, i go to this directory
/usr/local/lib/python3.5/

For your python version just go to
/usr/local/lib/python3.6/

**Comment by Tr1pke** [comment]
Same result for me also

**Comment by ghost** [comment]
@raihan001 check:
root@ubuntu-server:/usr/local/lib/python3.6/dist-packages/instapy_chromedriver# ls
chromedriver_linux64  chromedriver_mac64  chromedriver_win32.exe  __init__.py  __pycache__
root@ubuntu-server:/usr/local/lib/python3.6/dist-packages/instapy_chromedriver# rm -f chromedriver_linux64
root@ubuntu-server:/usr/local/lib/python3.6/dist-packages/instapy_chromedriver# wget https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_linux64.zip
--2019-08-02 17:56:25--  https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_linux64.zip
Resolving chromedriver.storage.googleapis.com (chromedriver.storage.googleapis.com)... 216.58.201.80, 2a00:1450:4014:800::2010
Connecting to chromedriver.storage.googleapis.com (chromedriver.storage.googleapis.com)|216.58.201.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5231218 (5,0M) [application/zip]
Saving to: ‘chromedriver_linux64.zip’

chromedriver_linux64.zip     100%[=============================================>]   4,99M  33,0MB/s    in 0,2s

2019-08-02 17:56:25 (33,0 MB/s) - ‘chromedriver_linux64.zip’ saved [5231218/5231218]

root@ubuntu-server:/usr/local/lib/python3.6/dist-packages/instapy_chromedriver# unzip chromedriver_
chromedriver_linux64.zip  chromedriver_win32.exe
root@ubuntu-server:/usr/local/lib/python3.6/dist-packages/instapy_chromedriver# unzip chromedriver_linux64.zip
Archive:  chromedriver_linux64.zip
  inflating: chromedriver
root@ubuntu-server:/usr/local/lib/python3.6/dist-packages/instapy_chromedriver# ls
chromedriver  chromedriver_linux64.zip  chromedriver_mac64  chromedriver_win32.exe  __init__.py  __pycache__
root@ubuntu-server:/usr/local/lib/python3.6/dist-packages/instapy_chromedriver# mv chromedriver chromedriver_linux64
root@ubuntu-server:/usr/local/lib/python3.6/dist-packages/instapy_chromedriver# ls
chromedriver_linux64      chromedriver_mac64      __init__.py
chromedriver_linux64.zip  chromedriver_win32.exe  __pycache__
root@ubuntu-server:/usr/local/lib/python3.6/dist-packages/instapy_chromedriver# rm -f chromedriver_linux64.zip
root@ubuntu-server:/usr/local/lib/python3.6/dist-packages/instapy_chromedriver# cd
root@ubuntu-server:~# exit

**Comment by ghost** [comment]
._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
No any custom workspace provided.       ~using existing..

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/ubuntu/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
INFO [2019-08-02 18:33:00] [myinstausername]  Using built in instapy-chromedriver executable (version 2.46)
ERROR [2019-08-02 18:33:01] [myinstausername]  Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 5.0.0-23-generic x86_64)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/instapy/browser.py", line 163, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 5.0.0-23-generic x86_64)

Traceback (most recent call last):
  File "instagram.py", line 37, in <module>
    schedule.run_pending()
  File "/usr/local/lib/python3.6/dist-packages/schedule/__init__.py", line 563, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.6/dist-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.6/dist-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.6/dist-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()
  File "instagram.py", line 15, in job
    session = InstaPy(username=insta_username, password=insta_password)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /usr/local/lib/python3.6/dist-packages/instapy_chromedriver/chromedriver_linux64

**Comment by ghost** [comment]
Last check: google-chrome --version
Google Chrome 76.0.3809.87 
So anyone knows how to downgrade or wait for Instapy

**Comment by amir5121** [comment]
Download chrome driver from here .. for version 76

https://chromedriver.chromium.org/downloads

replace it with 
`your_virtual_enviroment/lib/python3.6/site-packages/instapy_chromedriver/chromedriver_linux64`

you have to rename the downloaded file for me i had to change it to `chromedriver_linux64` there is also a mac and windows version there..

**Comment by alxhoff** [comment]
Same problem for me here. Using chromium version 76.0.3809.87 and driver 76.0.3809.68.

**Comment by fer-ri** [comment]
@amir5121 Thanks, it works for me

**Comment by robertobarlocci** [comment]
Works for me with chromedriver 75 (https://chromedriver.storage.googleapis.com/index.html?path=75.0.3770.140)
put it in the /usr/local/lib/python3.6/dist-packages/instapy_chromedriver/, 
unzip, renamed it to chromedriver_linux64 (or mac or whatever) and give the folder "instapy_chromedriver" the rights (i set the whole folder to 777 for testing purposes).

**Comment by steliosnikas** [comment]
This is a permissions issue. 

You need to just give the chromedriver file access.

Try sudo chmod 777 chromedriver_linux64
