### ISSUE TITLE
There was a problem logging you into Instagram. Please try again soon.

### ISSUE THREAD

**Issue by thedruny** [InstaPy/InstaPy#4751]
This inscription is written in the browser: There was a problem logging you into Instagram. Please try again soon.

INFO [2019-08-01 20:35:04] [thedruny]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2019-08-01 20:35:07] [thedruny]  - Internet Connection Status: ok
INFO [2019-08-01 20:35:07] [thedruny]  -- Connection Checklist [2/2] (Instagram Server Status)
INFO [2019-08-01 20:35:10] [thedruny]  - Instagram WebSite Status: Currently Up
INFO [2019-08-01 20:35:10] [thedruny]  - Instagram Response Time: 38.095 ms
INFO [2019-08-01 20:35:10] [thedruny]  - Instagram Reponse Code: 200
INFO [2019-08-01 20:35:10] [thedruny]  - Instagram Server Status: ok
Cookie file not found, creating cookie...
WARNING [2019-08-01 20:35:33] [thedruny]  There was a problem logging you into Instagram. Please try again soon.

......................................................................................................................
CRITICAL [2019-08-01 20:35:33] [thedruny]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2019-08-01 20:35:33] [thedruny]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.
[9576:9652:0801/203534.103:ERROR:broker_win.cc(55)] Error reading broker pipe: ╩рэры с√ы чръЁ√Є. (0x6D)
[9576:9652:0801/203534.105:ERROR:command_buffer_proxy_impl.cc(94)] ContextResult::kFatalFailure: AllocateAndMapSharedMemory failed
[1104:8988:0801/203534.108:ERROR:broker_win.cc(55)] Error reading broker pipe: ╩рэры с√ы чръЁ√Є. (0x6D)
[1104:8988:0801/203534.109:ERROR:broker_win.cc(137)] Error sending sync broker message: ╚фхЄ чръЁ√Єшх ърэрыр. (0xE8)
[1104:8988:0801/203534.110:ERROR:command_buffer_proxy_impl.cc(94)] ContextResult::kFatalFailure: AllocateAndMapSharedMemory failed

INFO [2019-08-01 20:35:37] [thedruny]  Sessional Live Report:
        |> No any statistics to show

[Session lasted 35.84 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-01 20:35:37] [thedruny]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by o365geek** [comment]
Check and make sure you have not make error on your login details.

**Comment by IKDH** [comment]
Try to change your IP.

**Comment by instapy-user** [comment]
Raspberry right?
Same issue here:
https://github.com/timgrossmann/InstaPy/issues/4755

**Comment by brnskn** [comment]
> Raspberry right?
> Same issue here:
> #4755

Instagram couldn't allow me too to log in on Rasberry, the solution is: log in with InstaPy on the Windows pc and move your cookie file from the InstaPy/logs folder and paste it to the raspberry /home/pi/InstaPy/logs folder. InstaPy will log in automatically with this cookie.
