### ISSUE TITLE
follow_likers is not working properly in 0.5.8 release

### ISSUE THREAD

**Issue by pamsn** [InstaPy/InstaPy#4753]
## Expected Behavior

The bot should get a set of likers that liked a photo from a given account. 

## Current Behavior

I believe that the bot is getting photo likers from a given account, but instapy follow likers from likers and not from the given list (follow_likes([account1,account2]))

Getting likers from user:  user1 
shuffling links
Got  0 , returning  0  links:  []

Getting likers from user:  user2
shuffling links
Got  12 , returning  2  links:  ['https://www.instagram.com/p/B0HKHPn1/', 'https://www.instagram.com/p/B0M4H1rc/']
Couldn't find liked counter button. May be a video.
Moving on..

**Comment by christophe-duc** [comment]
Hi,

  Could you share some details to try to reproduce it? (how your follow_likers is configured, and may be the account/post where we can see the problem happens?. I've tried the 2 links you mentioned but I just see a "page not found" from instagram.

  I've been running the 0.5.8 with follow_likers for 2 days now without a problem

**Comment by pamsn** [comment]
Here is my script:

@catch_exceptions(cancel_on_failure=True)
def job_follow_concorrentes_likers():  # 340 follows
    session = InstaPy(username=insta_username, password=insta_password, headless_browser=False)
    session.login()
    lista_final = []

    lista1 = ['op9portal', 'jc_pe', 'diariodepernambuco', 'folhape', 'tvclubeoficial', 'cnnbrasil', 'tvcidadepe']
    lista2 = ['globopernambuco', 'globonews', 'globointernacional', 'redeglobo', 'globoreporter', 'recordnews']
    lista3 = ['jornaloglobo', 'globoesportecom', 'radio.globo', 'portalne10', 'recordtvoficial', 'bbcbrasil']
    lista4 = ['jornaldarecord', 'cbnrecife', 'pesquisaeopiniao', 'cbnoficial', 'leiaja', 'poraqui.news']
    lista5 = ['jornalaquipe', 'jornalvanguarda', 'cafejornal', 'veja', 'vejanoinsta', 'estadao', 'portalpenews']
    lista6 = ['colunadoestadao', 'estadaoesporte', 'estadaocultura', 'folhadesaopaulo', 'theintercept', 'theinterceptbrasil', 'revistaistoe', 'pernambuconatv']
    lista7 = ['revistaepoca', 'revistaalgomais', 'revistapegn', 'revistacontinente', 'caruarunoface', 'tvtribuna', 'tvtribunape', 'tvpernambuco', ]

    if datetime.datetime.today().weekday() == 0:
        lista_final = session.grab_followers(username=random.choice(lista1), amount=350, live_match=True,
                                             store_locally=False)
    if datetime.datetime.today().weekday() == 1:
        lista_final = session.grab_followers(username=random.choice(lista2), amount=350, live_match=True,
                                             store_locally=False)
    if datetime.datetime.today().weekday() == 2:
        lista_final = session.grab_followers(username=random.choice(lista3), amount=350, live_match=True,
                                             store_locally=False)
    if datetime.datetime.today().weekday() == 3:
        lista_final = session.grab_followers(username=random.choice(lista4), amount=350, live_match=True,
                                             store_locally=False)
    if datetime.datetime.today().weekday() == 4:
        lista_final = session.grab_followers(username=random.choice(lista5), amount=350, live_match=True,
                                             store_locally=False)
    if datetime.datetime.today().weekday() == 5:
        lista_final = session.grab_followers(username=random.choice(lista6), amount=350, live_match=True,
                                             store_locally=False)
    if datetime.datetime.today().weekday() == 6:
        lista_final = session.grab_followers(username=random.choice(lista7), amount=350, live_match=True,
                                             store_locally=False)

    with smart_run(session):
        session.follow_likers(lista_final, photos_grab_amount=2, follow_likers_per_photo=15, randomize=True, sleep_delay=600, interact=False)

**Comment by christophe-duc** [comment]
I see, I don't think there is an actual problem in follow_likers. The fact you are trying to follow_like the list of followers of those accounts, will probably get you with a lot of private and accounts that don't even have a photo to grab likers from.

probably the more effective way would be to do:
`follow_likers(lista1,....)`
or
`follow_likers(random.sample(lista1,3),....)`

**Comment by pamsn** [comment]
I changed as you suggested but it shows:

Getting likers from user:  estadao 

shuffling links
Got  24 , returning  2  links:  ['https://www.instagram.com/p/B0npbGsAW87/', 'https://www.instagram.com/p/B0qMnbkASbv/']
Couldn't find liked counter button. May be a video.
Moving on..

None of the links are videos.

**Comment by martin-schmidt** [comment]
Same Problem here. It seems `likers_from_photo` always prints 

> Couldn't find liked counter button. May be a video

and returns an empty list. 

Has the buttons xpath changed?

**Comment by muygd** [comment]
I’m also receiving **Couldn't find liked counter button. May be a video** when I run instapy follow_likers. 

I’ve tried with different accounts to follow but I receive the same error.

**Comment by christophe-duc** [comment]
> I changed as you suggested but it shows:
> 
> Getting likers from user: estadao
> 
> shuffling links
> Got 24 , returning 2 links: ['https://www.instagram.com/p/B0npbGsAW87/', 'https://www.instagram.com/p/B0qMnbkASbv/']
> Couldn't find liked counter button. May be a video.
> Moving on..
> 
> None of the links are videos.

I've tried again with a fresh install of 0.5.8 and here is the log:

Getting likers from user:  estadao 

Got  24 , returning  2  links:  ['https://www.instagram.com/p/B0sAi5dgO-u/', 'https://www.instagram.com/p/B0rz15YglJP/']
opening likes
  17/10 [===================================+]  170%    |> Elapsed: 1.95 seconds    |> ETA: 0.8 seconds      

Got 17 likers shuffled randomly whom you can follow:
['aghattar_shantos', 'robinsonneyrn', 'paodonadeja', 'claudiabrotobambu', 'dejanira.peressutti', 'there_lima_eoli', 'claudianedjesus', 'fabiohmes', 'denianetoesilva', 'barros4125', '72lmandrade', 'marcosantoniomonteiro7', 'alexandreamc', 'joaocscardoso', 'celebreproducoesoficial', 'pinheiroseli', 'm.azevedo.78']

INFO [2019-08-03 07:38:47] [xxx]  User: 'claudianedjesus'  |> followers: 326  |> following: 403  |> relationship ratio: 0.8
INFO [2019-08-03 07:38:47] [xxx]  --> Not a valid user: Number of posts (1) of 'claudianedjesus' is less than the minimum limit given 10

INFO [2019-08-03 07:38:50] [xxx]  User: 'alexandreamc'  |> followers: 858  |> following: 893  |> relationship ratio: 0.96
INFO [2019-08-03 07:38:50] [xxx]  --> Not a valid user: alexandreamc is private account, by default skip

INFO [2019-08-03 07:38:54] [xxx]  User: 'denianetoesilva'  |> followers: 837  |> following: 473  |> relationship ratio: 1.76
INFO [2019-08-03 07:39:02] [xxx]  --> Followed 'b'denianetoesilva''!

using `use_firefox=True` and `            session.follow_likers(['estadao'],
                                      photos_grab_amount=2,
                                      follow_likers_per_photo=10,
                                      randomize=False,
                                      sleep_delay=600,
                                      interact=True)`

The only thing I can think of is that we are not running the same code. Look in xpath_compile.py where your instapy is installed (tell me where you looked) and copy/paste here the last xpath you see in the file.

**Comment by pamsn** [comment]
After delete database and remove cookies it starts to work. However, the bot is not following private accounts. Is it the expected behaviour?

INFO [2019-08-09 16:30:56] [xxxx]  --> Not a valid user: relmosousa is private account, by default skip

INFO [2019-08-09 16:31:00] [xxxx]  --> Not a valid user: juscelino.mendes.advogado is private account, by default skip

INFO [2019-08-09 16:31:02] [xxxx]  --> Not a valid user: silviarsmonteiro is private account, by default skip
