### ISSUE TITLE
Unable to login to Instagram - Installing instapy 

### ISSUE THREAD

**Issue by Mathieu-5** [InstaPy/InstaPy#4755]
## Current Behavior
Workspace in use: "/home/pi/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-08-02 10:49:54] [user]  Using built in instapy-chromedriver executable (version 2.36.post0)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-02 10:49:57] [user]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2019-08-02 10:49:57] [user]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2019-08-02 10:49:57] [user]  - Internet Connection Status: ok
INFO [2019-08-02 10:49:57] [user]  -- Connection Checklist [2/2] (Instagram Server Status)
WARNING [2019-08-02 10:49:59] [user]  - Instagram Server Status: error

.......................................................................................................................
CRITICAL [2019-08-02 10:49:59] [user]  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2019-08-02 10:49:59] [user]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.
ERROR [2019-08-02 10:49:59] [user]  Error occurred while deleting cookies from web browser!
	b'Message: chrome not reachable\n  (Session info: headless chrome=74.0.3729.157)\n  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.58-v7+ armv7l)\n'
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/browser.py", line 247, in close_browser
    browser.delete_all_cookies()
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 878, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=74.0.3729.157)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.58-v7+ armv7l)

INFO [2019-08-02 10:50:00] [user]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 5.65 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-02 10:50:00] [user]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

## Possible Solution (optional)
I have try : Install chromedriver 46 , Deletes cookies
## InstaPy configuration
Raspberry Pi 3b+
Raspbian
Instapy 0.5.8
Python 3.7.3
Chromedriver 36
Chromium 74

**Comment by brnskn** [comment]
Same for me (Raspberry pi 4 model b)

**Comment by bvanhou** [comment]
It is caused by you using the pods function without having 10 comments preset.
```
ERROR [2019-08-02 10:49:59] [user] You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.
```

**Comment by instapy-user** [comment]
Same for me...

```
Connection Checklist [1/2] (Internet Connection Status)
INFO [2019-08-03 08:55:26] [user]  - Internet Connection Status: ok
INFO [2019-08-03 08:55:26] [user]  -- Connection Checklist [2/2] (Instagram Server Status)
WARNING [2019-08-03 08:55:31] [user]  - Instagram Server Status: error

......................................................................................................................
CRITICAL [2019-08-03 08:55:31] [user]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2019-08-03 08:55:31] [user]  Error occurred while deleting cookies from web browser!
        b'Message: chrome not reachable\n  (Session info: headless chrome=74.0.3729.157)\n  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.58-v7+ armv7l)\n'
Traceback (most recent call last):
  File "/root/InstaPy/instapy/browser.py", line 247, in close_browser
    browser.delete_all_cookies()
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 878, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=74.0.3729.157)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.58-v7+ armv7l)


INFO [2019-08-03 08:55:31] [user]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 9.57 seconds]
```

**Comment by Mathieu-5** [comment]
> It is caused by you using the pods function without having 10 comments preset.
> 
> ```
> ERROR [2019-08-02 10:49:59] [user] You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.
> ```

I'm using more than 10 comments (15)

**Comment by brnskn** [comment]
> > It is caused by you using the pods function without having 10 comments preset.
> > ```
> > ERROR [2019-08-02 10:49:59] [user] You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.
> > ```
> 
> I'm using more than 10 comments (15)

Hey, I realised that the error messages are wrong, my real problem was about the chromedriver. I downgraded it and my problem is fixed.

**Comment by Mathieu-5** [comment]
> > > It is caused by you using the pods function without having 10 comments preset.
> > > ```
> > > ERROR [2019-08-02 10:49:59] [user] You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.
> > > ```
> > 
> > 
> > I'm using more than 10 comments (15)
> 
> Hey, I realised that the error messages are wrong, my real problem was about the chromedriver. I downgraded it and my problem is fixed.

Which version ?

**Comment by brnskn** [comment]
> > > > It is caused by you using the pods function without having 10 comments preset.
> > > > ```
> > > > ERROR [2019-08-02 10:49:59] [user] You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.
> > > > ```
> > > 
> > > 
> > > I'm using more than 10 comments (15)
> > 
> > 
> > Hey, I realised that the error messages are wrong, my real problem was about the chromedriver. I downgraded it and my problem is fixed.
> 
> Which version ?

2.33 chromedriver and chromium 65. 2.33 chromedriver works only with chromium 65

**Comment by Mathieu-5** [comment]
Can you send me the command line to install the good version of chromium and chromedriver ? Thanks a lot !

**Comment by brnskn** [comment]
https://github.com/timgrossmann/InstaPy/issues/4441#issuecomment-494371736
