### ISSUE TITLE
story watching while interacting doesn't work

### ISSUE THREAD

**Issue by EduardKov** [InstaPy/InstaPy#4756]
## Expected Behavior
https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#instapy-stories

Will add story watching while interacting with users
session.set_do_story(enabled = True, percentage = 70, simulate = True)

## Current Behavior
Traceback (most recent call last):
  File "/Users/***/Documents/instagram/InstaPy/long.py", line 125, in <module>
    session.set_do_story (enabled=True, percentage=70, simulate=False)
AttributeError: 'InstaPy' object has no attribute 'set_do_story'

## InstaPy configuration
Name: instapy
Version: 0.5.8
session.set_do_story(enabled = True, percentage = 70, simulate = True)
session.interact_user_followers(['123'], amount=300, randomize=True)

**Comment by christophe-duc** [comment]
Same here, not able to reproduce. It seems somehow you are not running 0.5.8, even if it seems you believe you are.

**Comment by EduardKov** [comment]
you are right, the version that was installed is not the one installed by pip, but located in a different folder.
thanks for the help
