### ISSUE TITLE
Unable to locate element: "method":"xpath","selector"

### ISSUE THREAD

**Issue by EduardKov** [InstaPy/InstaPy#4757]
## Expected Behavior
interact_user_followers must collect followers

## Current Behavior
Traceback (most recent call last):
  File "/Users/ххх/Documents/instagram/InstaPy/long.py", line 128, in <module>
    session.interact_user_followers(['alicefoxgo'], amount=300, randomize=True)
  File "/Users/ххх/Documents/instagram/InstaPy/instapy/instapy.py", line 2749, in interact_user_followers
    self.logfolder)
  File "/Users/ххх/Documents/instagram/InstaPy/instapy/unfollow_util.py", line 1019, in get_given_user_followers
    logger, logfolder)
  File "/Users/ххх/Documents/instagram/InstaPy/instapy/unfollow_util.py", line 747, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[2]/div/div[2]"}
  (Session info: chrome=73.0.3683.103)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Mac OS X 10.14.2 x86_64)

## InstaPy configuration
Name: instapy
Version: 0.5.8
chrome=73.0.3683.103
chromedriver=73.0.3683.68

    session.set_user_interact (amount=random.randint(2,3), percentage=100, randomize=False, media="Photo")
    session.set_do_like (enabled=True, percentage=100)
    session.set_do_follow (enabled=False, percentage=100, times=1)        
    session.interact_user_followers(['123'], amount=300, randomize=True)

**Comment by christophe-duc** [comment]
I've tested it n 0.5.8 with Chrome and could not reproduce the error:


`
INFO [2019-08-02 10:19:29] [xxx]  User 'alicefoxgo' [1/1]
  169/150 [===================================+]  112%    |> Elapsed: 12.42 seconds    |> ETA: 1.33 seconds      
INFO [2019-08-02 10:20:28] [xxx]  Grabbed 50 usernames from 'alicefoxgo's Followers to do interaction.
INFO [2019-08-02 10:20:28] [xxx]  User 'umorsovsegosveta' [1/50]
INFO [2019-08-02 10:20:32] [xxx]  User: 'umorsovsegosveta'  |> followers: 913  |> following: 6562  |> relationship ratio: 0.13
INFO [2019-08-02 10:20:32] [xxx]  Interaction [1/50]  |  Total Interaction: 1

________________________________________________________________________
INFO [2019-08-02 10:20:32] [xxx]  Starting to interact by users..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-08-02 10:20:32] [xxx]  Username [1/1]
INFO [2019-08-02 10:20:32] [xxx]  --> b'umorsovsegosveta'
INFO [2019-08-02 10:20:32] [xxx]  username actions: following=False commenting=False liking=False story=True
INFO [2019-08-02 10:20:32] [xxx]  Getting umorsovsegosveta image list...
INFO [2019-08-02 10:20:34] [xxx]  Post [1/2]
INFO [2019-08-02 10:20:34] [xxx]  https://www.instagram.com/p/BuCMAEugRq8/
INFO [2019-08-02 10:20:37] [xxx]  Image from: b'umorsovsegosveta'
INFO [2019-08-02 10:20:37] [xxx]  Link: b'https://www.instagram.com/p/BuCMAEugRq8/'
INFO [2019-08-02 10:20:37] [xxx]  Description: b'\xd0\xa2\xd1\x8b \xd1\x83\xd0\xbd\xd0\xb8\xd0\xba\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9 \xd1\x87\xd0\xb5\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x87\xd0\xb5\xd0\xba;)'
INFO [2019-08-02 10:20:37] [xxx]  --> Image not liked: b'Mandatory language not fulfilled'
INFO [2019-08-02 10:20:37] [xxx]  Post [2/2]
INFO [2019-08-02 10:20:37] [xxx]  https://www.instagram.com/p/BxMD3a9gmdD/
INFO [2019-08-02 10:20:40] [xxx]  Image from: b'umorsovsegosveta'
INFO [2019-08-02 10:20:40] [xxx]  Link: b'https://www.instagram.com/p/BxMD3a9gmdD/'
INFO [2019-08-02 10:20:40] [xxx]  Description: b'\xf0\x9f\x86\x92.....'
INFO [2019-08-02 10:20:42] [xxx]  --> Image Liked!
INFO [2019-08-02 10:21:34] [xxx]  --> Not commented
INFO [2019-08-02 10:21:35] [xxx]  --> Not following
INFO [2019-08-02 10:21:36] [xxx]  Loading stories with User --> b'umorsovsegosveta'
INFO [2019-08-02 10:21:42] [xxx]  no stories to watch (either there is none) or we have already watched everything
INFO [2019-08-02 10:21:42] [xxx]  -------------
INFO [2019-08-02 10:21:42] [xxx]  --> Given amount not fullfilled, image pool reached its end

INFO [2019-08-02 10:21:43] [xxx]  User 'miss_katerina555' [2/50]
INFO [2019-08-02 10:21:47] [xxx]  User: 'miss_katerina555'  |> followers: 8863  |> following: 4075  |> relationship ratio: 2.17
INFO [2019-08-02 10:21:47] [xxx]  User 'miss_katerina555's followers count exceeds maximum limit  ~skipping user

INFO [2019-08-02 10:21:47] [xxx]  User 'samer_sampo' [3/50]
INFO [2019-08-02 10:21:49] [xxx]  User: 'samer_sampo'  |> followers: 1183  |> following: 5249  |> relationship ratio: 0.22
INFO [2019-08-02 10:21:49] [xxx]  Interaction [2/50]  |  Total Interaction: 2
`

**Comment by EduardKov** [comment]
> I've tested it n 0.5.8 with Chrome and could not reproduce the error:

what version do you have chrome and chromedriver?

**Comment by EduardKov** [comment]
you are right, the version that was installed is not the one installed by pip, but located in a different folder.
thanks for the help
