### ISSUE TITLE
Instapy session interrupted after first following attempt - AttributeError: 'list' object has no attribute 'lower'

### ISSUE THREAD

**Issue by rudyvanbebu** [InstaPy/InstaPy#4760]
Good afternoon,

I'm having issues with InstaPy after an upgrade. The config file was not modified in any way from a previously working config, but the now the sessions end after the first attempt to follow users (following followers and also following commenters with hte same behavior. Logs listed below.

Any of you seeing similar behaviour after upgrade or can determine what is wrong while seeing the logs attached?

Thanks and best regards

## Expected Behavior

Following followers (targets) or following commenters of targets working as before upgrade

## Current Behavior

Sessions end, as with logs listed below

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-02 16:50:07] [***]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2019-08-02 16:50:07] [***]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2019-08-02 16:50:09] [***]  - Internet Connection Status: ok
INFO [2019-08-02 16:50:09] [***]  -- Connection Checklist [2/2] (Instagram Server Status)
INFO [2019-08-02 16:50:14] [***]  - Instagram WebSite Status: Currently Up
INFO [2019-08-02 16:50:14] [***]  - Instagram Response Time: 34.17 ms
INFO [2019-08-02 16:50:14] [***]  - Instagram Reponse Code: 200
INFO [2019-08-02 16:50:14] [***]  - Instagram Server Status: ok
[0802/165022.999:INFO:CONSOLE(0)] "The resource https://www.instagram.com/graphql/query/?query_hash=bd90987150a65578bc0dd5d4e60f113d&variables=%7B%22fetch_media_count%22%3A0%2C%22fetch_suggested_count%22%3A30%2C%22ignore_cache%22%3Atrue%2C%22filter_followed_friends%22%3Atrue%2C%22seen_ids%22%3A%5B%5D%2C%22include_reel%22%3Atrue%7D was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)

...................................................................
INFO [2019-08-02 16:50:27] [***]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-08-02 16:50:27] [***]  Saving account progress...

_________________________________________________________________________________
INFO [2019-08-02 16:50:30] [***]  Starting to follow user `Followers`..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-08-02 16:50:30] [***]  User 'fujifilmglobal' [1/13]
  169/135 [===================================+]  125%    |> Elapsed: 12.84 seconds    |> ETA: 2.56 seconds

INFO [2019-08-02 16:50:53] [***]  Simulated follow : 1
INFO [2019-08-02 16:50:56] [***]  --> Followed 'b'mikesladecanada''!

INFO [2019-08-02 16:50:59] [***]  Simulated follow : 2
INFO [2019-08-02 16:51:06] [***]  --> Followed 'b'10istanbul''!

INFO [2019-08-02 16:51:56] [***]  Grabbed 44 usernames from 'fujifilmglobal's `Followers` to do following

INFO [2019-08-02 16:51:56] [***]  Ongoing Follow [1/44]: now following 'djmrrid'...
INFO [2019-08-02 16:51:59] [***]  User: 'djmrrid'  |> followers: 486  |> following: 3805  |> relationship ratio: 0.12
INFO [2019-08-02 16:51:59] [***]  User 'djmrrid's following count exceeds maximum limit  ~skipping user

INFO [2019-08-02 16:51:59] [***]  Ongoing Follow [2/44]: now following 'zyllaba'...
INFO [2019-08-02 16:52:01] [***]  User: 'zyllaba'  |> followers: 547  |> following: 1456  |> relationship ratio: 0.37
INFO [2019-08-02 16:52:01] [***]  'zyllaba' has a business account

INFO [2019-08-02 16:52:01] [***]  Ongoing Follow [3/44]: now following 'ank_id'...
INFO [2019-08-02 16:52:04] [***]  User: 'ank_id'  |> followers: 99  |> following: 337  |> relationship ratio: 0.29
Traceback (most recent call last):
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\Follow Unfollow Schedule Like Feed Adapted Following CommentersV2.py", line 195, in follow
    interact=True)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\instapy.py", line 3273, in follow_user_followers
    validation, details = self.validate_user_call(person)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\instapy.py", line 1248, in validate_user_call
    self.logfolder)
  File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\util.py", line 382, in validate_username
    if bio_keyword.lower() in profile_bio.lower():
AttributeError: 'list' object has no attribute 'lower'

INFO [2019-08-02 16:52:07] [***]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING *** users & had *** FOLLOWERS
[Session lasted 2.09 minutes]

**Comment by shomanishikawa** [comment]
Seeing the same issue after just updating my package

**Comment by rudyvanbebu** [comment]
> Seeing the same issue after just updating my package

Thanks for letting me know, @shomanishikawa. In a way, good to know it is not an isolated incident on my machine. Will keep trying different configs and keep you posted if I can find anything else. Let's see if any other experience user can help on parallel to our own debugging

**Comment by rudyvanbebu** [comment]
I had tried a fresh install on another machine with same results. 
Toggling "headless_browser" and also switching "disable_image_load". All permutations yield the same results. 
I had also noticed while following the movemtens in Chrome with " headless browser=False"  that the simulated scrolls while listing followers and the simulated following work fine.
The scrip also goes further to recognize if the followers belong to the criteria selected. EG. Bussiness or private accounts are rejected and the script keeps running. It only crashed once it finds a suitable match and while trying enable the following action. Logs below indicating the last calls on user validation

Any other user experiencing similar issues, or able to help? 
Thanks for taking a look

Logs below

### 

>  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
>  ._.  ._.  ._.  ._.  ._.
> INFO [2019-08-05 11:35:01] [***]  Using built in instapy-chromedriver
> executable (version 2.46)
> 
> DevTools listening on ws://127.0.0.1:50326/devtools/browser/cf8156b2-5a2e-4a4f-8
> aea-0068549816ae
> 
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2019-08-05 11:35:03] [***]  Session started!
> oooooooooooooooooooooooooooooooooooooooooooooooooooooo
> 
> INFO [2019-08-05 11:35:03] [***]  -- Connection Checklist [1/2] (Inter
> net Connection Status)
> INFO [2019-08-05 11:35:06] [***]  - Internet Connection Status: ok
> INFO [2019-08-05 11:35:06] [***]  -- Connection Checklist [2/2] (Insta
> gram Server Status)
> INFO [2019-08-05 11:35:11] [***]  - Instagram WebSite Status: Currentl
> y Up
> INFO [2019-08-05 11:35:11] [***]  - Instagram Response Time: 118.679 m
> s
> INFO [2019-08-05 11:35:11] [***]  - Instagram Reponse Code: 200
> INFO [2019-08-05 11:35:11] [***]  - Instagram Server Status: ok
> [0805/113521.950:INFO:CONSOLE(0)] "The resource https://www.instagram.com/graphq
> l/query/?query_hash=bd90987150a65578bc0dd5d4e60f113d&variables=%7B%22fetch_media
> _count%22%3A0%2C%22fetch_suggested_count%22%3A30%2C%22ignore_cache%22%3Atrue%2C%
> 22filter_followed_friends%22%3Atrue%2C%22seen_ids%22%3A%5B%5D%2C%22include_reel%
> 22%3Atrue%7D was preloaded using link preload but not used within a few seconds
> from the window's load event. Please make sure it has an appropriate `as` value
> and it is preloaded intentionally.", source:  (0)
> 
> ...................................................................
> INFO [2019-08-05 11:35:26] [***]  Logged in successfully!
> '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
> INFO [2019-08-05 11:35:26] [***]  Saving account progress...
> 
> ________________________________________________________________________________
> _
> INFO [2019-08-05 11:35:29] [***]  Starting to follow user `Followers`.
> .
> """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> "
> INFO [2019-08-05 11:35:29] [***]  User 'fujixlovers' [1/7]
>   36/132 [=========+--------------------------]  27%    |> Elapsed: 0.77 seconds
>   48/132 [============+-----------------------]  36%    |> Elapsed: 1.85 seconds
>   60/132 [================+-------------------]  45%    |> Elapsed: 3.12 seconds
>   72/132 [===================+----------------]  54%    |> Elapsed: 4.08 seconds
>     |> ETA: 3.48 seconds
> 
> INFO [2019-08-05 11:35:44] [***]  Simulated follow : 1
> INFO [2019-08-05 11:35:47] [***]  --> Followed 'b'golden_ratio_618''!
> 
> 
>   83/132 [======================+-------------]  62%    |> Elapsed: 10.76 second
>   95/132 [=========================+----------]  71%    |> Elapsed: 11.67 second
>   107/132 [=============================+------]  81%    |> Elapsed: 13.05 secon
>   119/132 [================================+---]  90%    |> Elapsed: 14.03 secon
>   131/132 [===================================+]  99%    |> Elapsed: 15.12 secon
>   143/132 [===================================+]  108%    |> Elapsed: 16.05 seco
>   155/132 [===================================+]  117%    |> Elapsed: 17.23 seco
>   167/132 [===================================+]  126%    |> Elapsed: 18.3 secon
> ds    |> ETA: 3.77 seconds
> 
> INFO [2019-08-05 11:35:59] [***]  Simulated follow : 2
> INFO [2019-08-05 11:36:01] [***]  --> Followed 'b'adamkrecl''!
> 
> 
> INFO [2019-08-05 11:36:05] [***]  Simulated follow : 3
> INFO [2019-08-05 11:36:08] [***]  --> Followed 'b'alexaorjuela''!
> 
> 
> INFO [2019-08-05 11:36:11] [***]  Simulated follow : 4
> INFO [2019-08-05 11:36:14] [***]  --> Followed 'b'shprc4''!
> 
> INFO [2019-08-05 11:36:31] [***]  Grabbed 43 usernames from 'fujixlove
> rs's `Followers` to do following
> 
> INFO [2019-08-05 11:36:31] [***]  Ongoing Follow [1/43]: now following
>  'nikkihirokotakano'...
> INFO [2019-08-05 11:36:34] [***]  User: 'nikkihirokotakano'  |> follow
> ers: 609  |> following: 2163  |> relationship ratio: 0.28
> INFO [2019-08-05 11:36:34] [***]  nikkihirokotakano is private account
> , by default skip
> 
> INFO [2019-08-05 11:36:34] [***]  Ongoing Follow [2/43]: now following
>  'scootershooterstreetpics'...
> INFO [2019-08-05 11:36:37] [***]  User: 'scootershooterstreetpics'  |>
>  followers: 522  |> following: 2169  |> relationship ratio: 0.24
> Traceback (most recent call last):
>   File "C:\Users\ITAdmin\AppData\Local\Programs\Python\Python37-32\Lib\site-pack
> ages\Follow Unfollow Schedule Like Feed Adapted Following CommentersV2.py", line
>  195, in follow
>     interact=True)
>   File "C:\Users\ITAdmin\AppData\Local\Programs\Python\Python37-32\Lib\site-pack
> ages\instapy\instapy.py", line 3273, in follow_user_followers
>     validation, details = self.validate_user_call(person)
>   File "C:\Users\ITAdmin\AppData\Local\Programs\Python\Python37-32\Lib\site-pack
> ages\instapy\instapy.py", line 1248, in validate_user_call
>     self.logfolder)
>   File "C:\Users\ITAdmin\AppData\Local\Programs\Python\Python37-32\Lib\site-pack
> ages\instapy\util.py", line 382, in validate_username
>     if bio_keyword.lower() in profile_bio.lower():
> AttributeError: 'list' object has no attribute 'lower'
> 
> 
> INFO [2019-08-05 11:36:39] [***]  Sessional Live Report:
>         |> No any statistics to show
> 
> On session start was FOLLOWING *** users & had *** FOLLOWERS
> [Session lasted 1.64 minutes]
> 
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2019-08-05 11:36:39] [***]  Session ended!
> oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by Mathieu-5** [comment]
Same here

**Comment by fgisslen** [comment]
Any solutions?

**Comment by fgisslen** [comment]
#4784

**Comment by rudyvanbebu** [comment]
Thanks all for revising this, tested after editing as suggested on #4784. Exiting script / session with the following traceback log

Traceback (most recent call last):
File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\Follow Unfollow Schedule Like Feed Adapted Following CommentersV2.py", line 195, in follow
interact=True)
File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\instapy.py", line 3273, in follow_user_followers
validation, details = self.validate_user_call(person)
File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\instapy.py", line 1248, in validate_user_call
self.logfolder)
File "C:\Users\Engineering\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy\util.py", line 383, in validate_username
if bio_keyword.lower() in profile_bio:
AttributeError: 'list' object has no attribute 'lower'

**Comment by rudyvanbebu** [comment]
Fixed by @uluQulu suggestion on #4784
