### ISSUE TITLE
blocked at the very beginning

### ISSUE THREAD

**Issue by loookazs** [InstaPy/InstaPy#4763]
Hi, I get blocked on Windows right at the very beginning of the action. I use quickstart from youtube. As soon as I have on the shell simulated follow, I see "Action blocked" on Chrome. I haven't been using instapy for about 4-5 days and I got blocked without taking any actions like following or liking.

**Comment by ajankuv** [comment]
Including errors may help. Full errors.

**Comment by beewigs** [comment]
Hard to use now, verrrrrrrrrrrrrrrrrrrrrrrrrrry easy to be banded current now.

**Comment by loookazs** [comment]
no errors. i'm simply blocked and that's it

**Comment by Bijiboom** [comment]
Is there going to be a solution for this or is this the end of instapy? 😭😭

**Comment by KMLnk** [comment]
> Is there going to be a solution for this or is this the end of instapy? 😭😭
It seems that solving this problem is out of power

**Comment by GaWr26** [comment]
try 0.6.0 which was released today!
