### ISSUE TITLE
Error occurred while deleting cookies from web browser!

### ISSUE THREAD

**Issue by jamezun** [InstaPy/InstaPy#4767]
## Expected Behavior
Run smoothly without error.

## Current Behavior
I do not know why I keep having this error, but I have commented out login_util.py in line 22 as follow to avoid errors in like blocks plus I am using chromedriver=2.42 (will this matter?):
`
#browser.add_cookie(cookie)`

> 
> INFO [2019-08-03 22:07:51] [donaldtrumpy]  Location: b'USA'
> INFO [2019-08-03 22:08:00] [donaldtrumpy]  User: 'jamie_liyi'  |> followers: 93  |> following: 111  |> relationship ratio: 0.83
> INFO [2019-08-03 22:08:16] [donaldtrumpy]  --> Image Liked!
> INFO [2019-08-03 22:08:49] [donaldtrumpy]  --> Commented: b'wonderful one! \xf0\x9f\x92\x95 '
> ERROR [2019-08-03 22:19:12] [donaldtrumpy]  Error occurred while deleting cookies from web browser!
> 	b'Message: timeout\n  (Session info: chrome=75.0.3770.142)\n  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 6.3.9600 x86_64)\n'
> Traceback (most recent call last):
>   File "C:\Users\user\Desktop\Instagram Automation\Instapy - New\instapy\util.py", line 1678, in smart_run
>     yield
>   File "C:\Users\user\Desktop\Instagram Automation\Instapy - New\run-donaldtrumpy.py", line 132, in <module>
>     session.like_by_locations(['182053561695/city-university-of-hong-kong/'], amount=40)
>   File "C:\Users\user\Desktop\Instagram Automation\Instapy - New\instapy\instapy.py", line 1504, in like_by_locations
>     self.logfolder)
>   File "C:\Users\user\Desktop\Instagram Automation\Instapy - New\instapy\unfollow_util.py", line 701, in follow_user
>     logfolder)
>   File "C:\Users\user\Desktop\Instagram Automation\Instapy - New\instapy\unfollow_util.py", line 1550, in verify_action
>     reload_webpage(browser)
>   File "C:\Users\user\Desktop\Instagram Automation\Instapy - New\instapy\util.py", line 1704, in reload_webpage
>     browser.execute_script("location.reload()")
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
>     'args': converted_args})['value']
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.TimeoutException: Message: timeout
>   (Session info: chrome=75.0.3770.142)
>   (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 6.3.9600 x86_64)
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\user\Desktop\Instagram Automation\Instapy - New\instapy\browser.py", line 247, in close_browser
>     browser.delete_all_cookies()
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 878, in delete_all_cookies
>     self.execute(Command.DELETE_ALL_COOKIES)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.TimeoutException: Message: timeout
>   (Session info: chrome=75.0.3770.142)
>   (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 6.3.9600 x86_64)
> 
> ERROR [2019-08-03 22:19:30] [donaldtrumpy]  Pow! Error occurred while dumping record activity data to a local JSON:
> 	b'Expecting property name enclosed in double quotes: line 1 column 98365 (char 98364)'
> INFO [2019-08-03 22:19:30] [donaldtrumpy]  Sessional Live Report:
> 	|> LIKED 1 images  |  ALREADY LIKED: 7
> 	|> COMMENTED on 1 images
> 	|> FOLLOWED 1 users  |  ALREADY FOLLOWED: 0
> 	|> UNFOLLOWED 0 users
> 	|> LIKED 0 comments
> 	|> REPLIED to 0 comments
> 	|> INAPPROPRIATE images: 10
> 	|> NOT VALID users: 15
> 	|> WATCHED 0 story(ies)  |  WATCHED 0 reel(s)
> 
> On session start was FOLLOWING 909 users & had 2466 FOLLOWERS
> [Session lasted 1.27 hours]
> INFO [2019-08-03 22:19:30] [donaldtrumpy]  Session ended!
> 

## InstaPy configuration
session = InstaPy(username='donaldtrumpy', password='kissmyask',headless_browser=False, disable_image_load=True, multi_logs=True)

    session.set_user_interact(amount=3, randomize=True, percentage=95, media='Photo')
    session.set_relationship_bounds (enabled=True,
                                      potency_ratio=None,
                                      delimit_by_numbers=True,
                                       max_followers=5000,
                                       max_following=1000,
                                       min_followers=50,
                                       min_following=50)
                                       
    session.set_quota_supervisor(enabled=True,
                                  sleep_after=["likes", "comments_d", "follows", "unfollows"],
                                  sleepyhead=True, stochastic_flow=True, notify_me=True,
                                   peak_likes=(100, 700),
                                   peak_comments=(20, 200),
                                   peak_follows=(50, 700),
                                   peak_unfollows=(50, 700))

**Comment by githubbbie** [comment]
Still problem.
