### ISSUE TITLE
Instagram behavior 

### ISSUE THREAD

**Issue by ljacobo** [InstaPy/InstaPy#4772]
Hi,

Since we all get blocked activity, i made some tests to trying to understand how is instagram behaving. I get blocked using headless mode, even using the app, but now im using instapy without headless mode and is working. Don’t know is Instagram can detect the usage of selenium, or is the hour limits that had changed. Will test to some random sleep_delay.

I try to interact as random as a human being do, that’s maybe one key to keep working.

How you doing it?

Thanks.

-UPDATE-
Seeing the log,  sometimes i get the error **Phew! Last follow is not verified.**, and i was thinking that i was blocked but working with the headless mode False, i saw that the problem was that the program wasn't reloading the page, once i saw the error, i refresh the page and saw that the follow was made it.

-UPDATE 2-
That happens when the follow is requested to a private account, with open accounts the follow is verified with the reload of the page.

@breuerfelix @timgrossmann @uluQulu

**Comment by pilarfc** [comment]
@ljacobo so you solved it just with `headless mode False`?

**Comment by ljacobo** [comment]
> @ljacobo so you solved it just with `headless mode False`?

no, yesterday i was working good, but today i get blocked. :/

**Comment by lezlea** [comment]
Ahh thanks for testing and letting us know!  I haven't figured out a solution either.

**Comment by jonap339** [comment]
I am working with 9 accounts and little by little they are blocking me all to follow, comment and likear :( No longer correct or delete cookies :(
