### ISSUE TITLE
WARNING! Image was NOT liked! You are have a BLOCK on likes! I need Help Please.

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#4773]
I need Help Please
WARNING! Image was NOT liked! You are have a BLOCK on likes!
0 like 
0 comment
0 follow

**Comment by ph94** [comment]
Hi. If you can like, comment and follow manually, you just have to delete the cookie file and start instapy again.

**Comment by johnvfitness** [comment]
I find it where 
bro

**Comment by SiLentBoB2019** [comment]
C:\Users\xxx\InstaPy\logs\xxx

**Comment by johnvfitness** [comment]
Thx @SiLentBoB2019

**Comment by johnvfitness** [comment]
I same error after delete logs folder
@ph94

**Comment by johnvfitness** [comment]
Traceback (most recent call last):
  File "C:\Users\VFit-Family\Google Drive\Bot\John-Bot.py", line 17, in job1
    session = InstaPy(username=insta_username, password=insta_password, headless_browser=True, multi_logs=False)
  File "C:\Users\VFit-Family\Google Drive\Bot\instapy\instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "C:\Users\VFit-Family\Google Drive\Bot\instapy\instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at C:\Users\VFit-Family\InstaPy\assets\chromedriver.exe

**Comment by ozzysahin** [comment]
same problem
