### ISSUE TITLE
WORK AGAIN after FOLLOW BLOCK , but...

### ISSUE THREAD

**Issue by babalau** [InstaPy/InstaPy#4775]
After several days when instapy did not work (i received fallow block after one attempt) i managed to get it to work. (small changes)
The problem is that the time interval between fallows and likes is too small.
Does anyone know the new hourly limits of fallow and like, also unfallow?

Thank you

**Comment by e1x4** [comment]
I think 20 follow/unfollow an hour

**Comment by babalau** [comment]
> I think 20 follow/unfollow an hour

thank you!
