### ISSUE TITLE
Installation fails due to conflicting jsonschema  version

### ISSUE THREAD

**Issue by NeolithEra** [InstaPy/InstaPy#4778]
Hi, users are unable to run **_InstaPy_** due to dependency conflict with _**jsonschema**_ package. 
As shown in the following full dependency graph of **_InstaPy_**, **_InstaPy_** requires _**jsonschema>=2.6.0**_，while **_clarifai 2.6.2_** requires _**jsonschema >=2.5,<3**_.

According to pip’s “first found wins” installation strategy, _**jsonschema 3.0.2**_ is the actually installed version. 
However, _**jsonschema 3.0.2**_ does not satisfy _**jsonschema >=2.5,<3**_.

### Dependency tree
```
InstaPy-legacy
| +-certifi(version range:>=2018.10.15)
| +-chardet(version range:>=3.0.4)
| +-clarifai(version range:>=2.4.1)
| | +-configparser(version range:>=3.5,<4)
| | +-future(version range:>=0.15,<2)
| | +-googleapis-common-protos(version range:>=1.5.0,<2)
| | +-grpcio(version range:>=1.13.0,<2)
| | | +-coverage(version range:>=4.0)
| | | +-cython(version range:>=0.29.8)
| | | +-enum34(version range:>=1.0.4)
| | | +-protobuf(version range:>=3.5.0.post1)
| | | +-six(version range:>=1.10)
| | | +-wheel(version range:>=0.29)
| | +-jsonschema(version range:>=2.5,<3)
| | +-protobuf(version range:>=3.6,<4)
| | +-requests(version range:>=2.13,<3)
| | | +-certifi(version range:>=2017.4.17)
| | | +-chardet(version range:<3.1.0,>=3.0.2)
| | | +-idna(version range:>=2.5,<2.9)
| | | +-urllib3(version range:<1.26,>=1.21.1)
| +-configparser(version range:>=3.5.0)
| +-easyprocess(version range:>=0.2.3)
| +-emoji(version range:>=0.5.1)
| +-future(version range:>=0.17.1)
| +-googleapis-common-protos(version range:>=1.5.5)
| +-grpcio(version range:>=1.16.1)
| | +-coverage(version range:>=4.0)
| | +-cython(version range:>=0.29.8)
| | +-enum34(version range:>=1.0.4)
| | +-protobuf(version range:>=3.5.0.post1)
| | +-six(version range:>=1.10)
| | +-wheel(version range:>=0.29)
| +-idna(version range:>=2.7)
| +-jsonschema(version range:>=2.6.0)
| +-meaningcloud-python(version range:>=1.1.1)
| | +-requests(version range:*)
| | | +-certifi(version range:>=2017.4.17)
| | | +-chardet(version range:<3.1.0,>=3.0.2)
| | | +-idna(version range:>=2.5,<2.9)
| | | +-urllib3(version range:<1.26,>=1.21.1)
| +-plyer(version range:>=1.3.1)
| +-protobuf(version range:>=3.6.1)
| +-pyvirtualdisplay(version range:>=0.2.1)
| | +-easyprocess(version range:*)
| +-pyyaml(version range:>=3.13)
| +-regex(version range:>=2018.11.22)
| +-requests(version range:>=2.20.1)
| | +-certifi(version range:>=2017.4.17)
| | +-chardet(version range:<3.1.0,>=3.0.2)
| | +-idna(version range:>=2.5,<2.9)
| | +-urllib3(version range:<1.26,>=1.21.1)
| +-selenium(version range:>=3.141.0)
| +-six(version range:>=1.11.0)
| +-urllib3(version range:>=1.24.1)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

1.	Fix your direct dependency to be **_jsonschema >=2.5,<3_**.
 I have checked this revision will not affect your downstream projects now.
2.	Remove your direct dependency **_jsonschema_**, and use **_jsonschema_** transitively introduced by **_clarifai_**.

Which solution do you prefer, 1 or 2?
@timgrossmann Please let me know your choice. I can submit a PR to solve this issue.

**Comment by pql4** [comment]
Hi, 

Could you give more detail to solve this problem?

**Comment by mikediachenko** [comment]
I do not think it is an issue of jsonschema, because I also have this error every time I run instaPy, but it continues to work.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NeolithEra** [comment]
@mikediachenko I think maybe your project is not developed under a clean virtual environment.
There are some local installations of libraries affect the exposure of dependency conflict problem. ^_^
