### ISSUE TITLE
Is the bot not longer usable?!

### ISSUE THREAD

**Issue by Bijiboom** [InstaPy/InstaPy#4785]
Like the title says it... 
Im new here and started using instapy for like 2 weeks now and I really liked the progress... 2 days now everytime I start it it gets blocked, and my reach on my profile dropped (which I think is a shadowban) 
Can you guys please tell me if that's common and it gets fixed and continued or is this it?

Thank you guys

**Comment by pttnx** [comment]
Depends on how many likes your bot performed, try using quota_supervisor to reduce server requests. This lets your bot take a nap after every now and then, depending on your settings.

**Comment by converge** [comment]
help testing `dev` brach, all issues should be fixed now. let us know if you find some new bug

**Comment by shhackleton** [comment]
@converge is there a new update availiable?

**Comment by converge** [comment]
maybe tomorrow @shhackleton
