### ISSUE TITLE
-------- WARNING! Image was NOT liked! You are have a BLOCK on likes!

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#4790]
I have delete cookie and Same Error after 30 like 
I have last version instapy and update.

Help Please bro.
@converge

**Comment by converge** [comment]
help testing `dev` branch, it's fixing all the issues. let me know if you find some bug

**Comment by ArdyBeheshti** [comment]
@converge a new error is coming from the Dev repo... 

**File "\InstaPy-dev\instapy\util.py", line 2386, in take_rotative_screenshot
    browser.save_screenshot("{}{}_1.png".format(logfolder, logger.name))
AttributeError: 'LoggerAdapter' object has no attribute 'name'**


Below is my "quickstart" - what do you think the issue is here?

`"""
This template is written by @ArdeshirBeheshti

What does this quickstart script aim to do?
- This is my simple but effective script.
"""

import time
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

#insta_username = 
#insta_password = 

# get a session!
session = InstaPy(username='ardybeheshti',
                  password='Abear120609_#@!',
                  headless_browser=True)

# let's go! :>
with smart_run(session):
    # general settings

    session.set_user_interact(amount=2, randomize=True, percentage=10, media='Photo')
    session.set_do_like(enabled=True, percentage=100)
    session.set_do_comment(enabled=True, percentage=60)
    session.set_comments(['oh, this is good', 'nice one here!', 'i like this one', 'how amazing is this!'])

    session.like_by_locations(['212983635/san-diego-california/', '212999109/los-angeles-california/', '7226110/tokyo-japan/', '213755156/tehran-iran/', '745256841/seoul-south-korea/', '566976999/china/', '127963847/madrid-spain/', '212991559/toronto-ontario/', '212988663/new-york-new-york/', '44961364/san-francisco-california/'], amount=100)
    session.like_by_tags(['finalfantasy', 'cosplay', 'artists', 'books'], amount=100)
    time.sleep(21600)
    session.like_by_locations2(['204517928/chicago-illinois/', '213385402/london-united-kingdom/', '6889842/paris-france/', '213270076/mexico-city-mexico/', '213941548/seattle-washington/', '213136562/kyoto-japan/', '/271456804/japan/', '287620626/busan-south-korea/', '214288771/taipei-taiwan/', '216161580/encinitas-california/'], amount=100)
    session.like_by_tags2(['photography', 'anime', 'lofi', 'graphicdesign'], amount=100)
    time.sleep(21600)
    session.like_by_locations3(['4599325/denver-colorado', '2807792/la-jolla-california', '212988663/new-york-new-york', '13404453/bangkok-thailand', '270531492/italy', '31499759/rome-italy', '212964995/austin-texas', '217271987/bel-air-los-angeles', '214288771/taipei-taiwan', '213270076/mexico-city-mexico'], amount=100)
    session.like_by_tags3(['budlightdivetour', 'python', 'raybans', 'danielwellington'], amount=100)`

**Comment by ArdyBeheshti** [comment]
@converge a new error is coming from the Dev repo... 

**File "\InstaPy-dev\instapy\util.py", line 2386, in take_rotative_screenshot
    browser.save_screenshot("{}{}_1.png".format(logfolder, logger.name))
AttributeError: 'LoggerAdapter' object has no attribute 'name'**


Below is my "quickstart" - what do you think the issue is here?

`"""
This template is written by @ArdeshirBeheshti

What does this quickstart script aim to do?
- This is my simple but effective script.
"""

import time
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

#insta_username = 
#insta_password = 

# get a session!
session = InstaPy(username='user',
                  password='pass',
                  headless_browser=True)

# let's go! :>
with smart_run(session):
    # general settings

    session.set_user_interact(amount=2, randomize=True, percentage=10, media='Photo')
    session.set_do_like(enabled=True, percentage=100)
    session.set_do_comment(enabled=True, percentage=60)
    session.set_comments(['oh, this is good', 'nice one here!', 'i like this one', 'how amazing is this!'])

    session.like_by_locations(['212983635/san-diego-california/', '212999109/los-angeles-california/', '7226110/tokyo-japan/', '213755156/tehran-iran/', '745256841/seoul-south-korea/', '566976999/china/', '127963847/madrid-spain/', '212991559/toronto-ontario/', '212988663/new-york-new-york/', '44961364/san-francisco-california/'], amount=100)
    session.like_by_tags(['finalfantasy', 'cosplay', 'artists', 'books'], amount=100)
    time.sleep(21600)
    session.like_by_locations2(['204517928/chicago-illinois/', '213385402/london-united-kingdom/', '6889842/paris-france/', '213270076/mexico-city-mexico/', '213941548/seattle-washington/', '213136562/kyoto-japan/', '/271456804/japan/', '287620626/busan-south-korea/', '214288771/taipei-taiwan/', '216161580/encinitas-california/'], amount=100)
    session.like_by_tags2(['photography', 'anime', 'lofi', 'graphicdesign'], amount=100)
    time.sleep(21600)
    session.like_by_locations3(['4599325/denver-colorado', '2807792/la-jolla-california', '212988663/new-york-new-york', '13404453/bangkok-thailand', '270531492/italy', '31499759/rome-italy', '212964995/austin-texas', '217271987/bel-air-los-angeles', '214288771/taipei-taiwan', '213270076/mexico-city-mexico'], amount=100)
    session.like_by_tags3(['budlightdivetour', 'python', 'raybans', 'danielwellington'], amount=100)
    
    `

**Comment by ArdyBeheshti** [comment]
> 
> 
> @converge a new error is coming from the Dev repo...
> 
> **File "\InstaPy-dev\instapy\util.py", line 2386, in take_rotative_screenshot browser.save_screenshot("{}{}_1.png".format(logfolder, logger.name)) AttributeError: 'LoggerAdapter' object has no attribute 'name'**
> 
> Below is my "quickstart" - what do you think the issue is here?
> 
> `"""
> This template is written by @ardeshirbeheshti
> 
> What does this quickstart script aim to do?
> 
>     * This is my simple but effective script.
>       """
> 
> 
> import time
> from instapy import InstaPy
> from instapy import smart_run
> from instapy import set_workspace
> 
> #insta_username =
> #insta_password =
> # get a session!
> 
> session = InstaPy(username='user',
> password='pass',
> headless_browser=True)
> # let's go! :>
> 
> with smart_run(session):
> # general settings
> 
> ```
> session.set_user_interact(amount=2, randomize=True, percentage=10, media='Photo')
> session.set_do_like(enabled=True, percentage=100)
> session.set_do_comment(enabled=True, percentage=60)
> session.set_comments(['oh, this is good', 'nice one here!', 'i like this one', 'how amazing is this!'])
> 
> session.like_by_locations(['212983635/san-diego-california/', '212999109/los-angeles-california/', '7226110/tokyo-japan/', '213755156/tehran-iran/', '745256841/seoul-south-korea/', '566976999/china/', '127963847/madrid-spain/', '212991559/toronto-ontario/', '212988663/new-york-new-york/', '44961364/san-francisco-california/'], amount=100)
> session.like_by_tags(['finalfantasy', 'cosplay', 'artists', 'books'], amount=100)
> time.sleep(21600)
> session.like_by_locations2(['204517928/chicago-illinois/', '213385402/london-united-kingdom/', '6889842/paris-france/', '213270076/mexico-city-mexico/', '213941548/seattle-washington/', '213136562/kyoto-japan/', '/271456804/japan/', '287620626/busan-south-korea/', '214288771/taipei-taiwan/', '216161580/encinitas-california/'], amount=100)
> session.like_by_tags2(['photography', 'anime', 'lofi', 'graphicdesign'], amount=100)
> time.sleep(21600)
> session.like_by_locations3(['4599325/denver-colorado', '2807792/la-jolla-california', '212988663/new-york-new-york', '13404453/bangkok-thailand', '270531492/italy', '31499759/rome-italy', '212964995/austin-texas', '217271987/bel-air-los-angeles', '214288771/taipei-taiwan', '213270076/mexico-city-mexico'], amount=100)
> session.like_by_tags3(['budlightdivetour', 'python', 'raybans', 'danielwellington'], amount=100)
> 
> `
> ```

Think I just solved the issue by removing 

vvv (line 408 in instapy.py)

`if not login_user(
            self.browser,
            self.username,
            self.password,
            self.logger,
            self.logfolder,
            self.bypass_with_mobile,
        ):
            message = (
                "Unable to login to Instagram! "
                "You will find more information in the logs above."
            )
            highlight_print(self.username, message, "login", "critical", self.logger)

            self.aborting = True
            return self`


However, the block still applies when liking an image...will continue testing and update.

**Comment by martin-schmidt** [comment]
@converge
> help testing `dev` branch, it's fixing all the issues. let me know if you find some bug

```
File "/home/xxx/.local/lib/python3.7/site-packages/instapy/relationship_tools.py", line 351, in get_following
    use_firefox = Settings.use_firefox
AttributeError: type object 'Settings' has no attribute 'use_firefox'

```

**Comment by johnvfitness** [comment]
(Phew! Last follow is not verified.     ~'mr_and_mrs_vfit' might be temporarily blocked from following)
And same error
------ WARNING! Image was NOT liked! You are have a BLOCK on likes!
After Test this error.

@converge

**Comment by converge** [comment]
@ArdyBeheshti are you sure you're using the latest version of `dev`? I copy/paste your setup and It's running without issues

**Comment by converge** [comment]
@martin-schmidt how do I reproduce it?

**Comment by converge** [comment]
how do I reproduce that @johnvfitness ?

**Comment by krazybean** [comment]
For me, when i get the prompt asking for code via Email, i enter the code provided by email as the security code in the prompt, but then the script fails and I immediately get a text afterwards from instagram with another security code.

Is something being done twice? Invalidating the first attempt? What's the new flow?

**Comment by converge** [comment]
@krazybean what's the error msg?

**Comment by krazybean** [comment]
```
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-07 08:59:33] [instauser]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-08-07 08:59:33] [instauser]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-08-07 08:59:34] [instauser]  - Internet Connection Status: ok
INFO [2019-08-07 08:59:34] [instauser]  -- Connection Checklist [2/3] (Hide Selenium Extension)
INFO [2019-08-07 08:59:34] [instauser]  - window.navigator.webdriver response: False
INFO [2019-08-07 08:59:34] [instauser]  - Hide Selenium Extension: ok
INFO [2019-08-07 08:59:34] [instauser]  -- Connection Checklist [3/3] (Instagram Server Status)
INFO [2019-08-07 08:59:39] [instauser]  - Instagram WebSite Status: Currently Up 
INFO [2019-08-07 08:59:39] [instauser]  - Instagram Response Time: 37.07 ms 
INFO [2019-08-07 08:59:39] [instauser]  - Instagram Reponse Code: 200
INFO [2019-08-07 08:59:39] [instauser]  - Instagram Server Status: ok
Cookie file not found, creating cookie...
Instagram detected an unusual login attempt
A security code was sent to your Email: k*******n@email.com

.........................................................................................................................
CRITICAL [2019-08-07 09:00:26] [instauser]  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2019-08-07 09:00:27] [instauser]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 56.22 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-07 09:00:27] [instauser]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo

```

**Comment by ghost** [comment]
Just tried the DEV branch, it worked for 50 likes, then blocked again.
I have used it on VPS with CentOS 7 there installed.

**Comment by johnvfitness** [comment]
Same error 30 like and block

**Comment by ghost** [comment]
Same. I set 1 like and 1 follow for 63 seconds.
Unfollows also don't work.
Instagram got us the a** 😇

**Comment by converge** [comment]
delete cookie file and try again (with 0.6.0/dev) branch

**Comment by krazybean** [comment]
tried on 0.6.0/dev, was able to get through about 30 before i got the dreaded
```-------- WARNING! Image was NOT liked! You are have a BLOCK on likes!```

**Comment by Cathaldus** [comment]
I get this error when I try to run it on dev branch ->
Traceback (most recent call last):

>   File "quickstart.py", line 51, in <module>
>     session.set_delimit_liking(enabled=True, max=421, min=0)
> TypeError: set_delimit_liking() got an unexpected keyword argument 'max'

**Comment by johnvfitness** [comment]
I Same 11 like block 0.6.0 dev instapy

**Comment by alexsmedile** [comment]
Might help:
[https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver](https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver)

Apparently, Instagram is starting to detect patterns.
I tried scheduling a cache delete every few hours but it didn't fix the problem, every 10-30 server calls I got detected anyway. Action delays don't help for what I can understand...

### TEMPORARY FIX
1. Change your Instagram password
2. Delete InstaPy cookies (you'll find it in `InstaPy/logs` directory)
2b. I also deleted browsing data manually in Chrome
3. Change your IP
4. Add your new password to your code
5. Enjoy for a few hours

**Comment by dickensac** [comment]
English
Your Account Was Compromised
It looks like you shared your password with a service to help you get more likes or followers, which goes against our Community Guidelines.
Change your password to continue using Instagram. If you share your new password with one of these services, you may get blocked from following, liking or commenting.

**Comment by rvoets** [comment]
I also tried the dev branch and got blocked after 15 likes.

**Comment by johnvfitness** [comment]
Same error blocked account ☹️

**Comment by Affenjimbo** [comment]
Same for me on 2 accounts. But I can like on phone and browser manually when I delete the cashe.

**Comment by kranechan** [comment]
@converge I have a hypothesis. Could it be that they are detecting how we interact with photo and they implemented some event/javascript from the profile/photo icon?

Cause right now we are 
1) Gather all the photo/profile URL
2) Direct access URL (without heading back to the profile)
3) Click like/follow/url

For like: Could the bot detection issue solved by clicking the photo -> then only like instead?
For follow: Use the search bar to search for the profile name / click from user following/follower?

I believe IG are detecting by identifying version of browser then analyze the pattern proceed with ban if they direct access using URL (cause no human will remember so many URL and directly access them) 

Let me know if this sounds logical.

**Comment by CharlesCCC** [comment]
@converge Not sure if you seem this, but there is a good discussion on here regarding to some headless browser detection [link](https://news.ycombinator.com/item?id=20480915)

Maybe something to consider.

**Comment by converge** [comment]
@CharlesCCC thanks, I did that, but they're still recognizing it

**Comment by rvoets** [comment]
@converge What kind of setup do you use? Using like by tags or something else?

**Comment by converge** [comment]
@rvoets I just develop

**Comment by lguizi** [comment]
try using one function 1 or 2 times than use another random function 1 or 2 and keep doing this...

**Comment by Mehran** [comment]
no any Solution for this till now?

**Comment by martin-schmidt** [comment]
@converge
> @martin-schmidt how do I reproduce it?

Use the dev-branch and call `get_following` from `instapy/relationship_tools.py`. Hit the line 351.

**Comment by Mehran** [comment]
@martin-schmidt dev-branch helping to prevent from blocking?

**Comment by martin-schmidt** [comment]
@Mehran 

> @martin-schmidt dev-branch helping to prevent from blocking?

No, I still get blocked after ~30 likes.

**Comment by johnvfitness** [comment]
Same Error blocked 
Last dev instapy

**Comment by Mehran** [comment]
seems bot dead now

**Comment by Zettt** [comment]
@converge 
> help testing `dev` branch, it's fixing all the issues. let me know if you find some bug

How to test the `dev` branch? Your answer appears multiple times here but I couldn't find documentation how to test `dev`.

**Comment by ghost** [comment]
> @converge
> 
> > help testing `dev` branch, it's fixing all the issues. let me know if you find some bug
> 
> How to test the `dev` branch? Your answer appears multiple times here but I couldn't find documentation how to test `dev`.

You should create another branch, different than master one, and then pull dev into it.

**Comment by converge** [comment]
0.6.0 was released, `pip3 install instapy -U` will update it for you.

**Comment by Mehran** [comment]
Good Job , still blocked after 10 on firefox :( @converge

**Comment by alinakhay** [comment]
Getting this same `AttributeError: 'LoggerAdapter' object has no attribute 'name'` error on Chrome.

**Comment by johnvfitness** [comment]
Same error after last update bro 
@converge 

INFO [2019-08-12 15:13:42] [vfit.concept]  Location: b'Brussels, Belgium'
INFO [2019-08-12 15:13:49] [vfit.concept]  --> Image Liked!
INFO [2019-08-12 15:14:17] [vfit.concept]  -------- WARNING! Image was NOT liked! You are have a BLOCK on likes!
INFO [2019-08-12 15:14:17] [vfit.concept]  Location: b'213633143'
INFO [2019-08-12 15:14:17] [vfit.concept]  Liked: 0
INFO [2019-08-12 15:14:17] [vfit.concept]  Already Liked: 0
INFO [2019-08-12 15:14:17] [vfit.concept]  Commented: 0
INFO [2019-08-12 15:14:17] [vfit.concept]  Followed: 0
INFO [2019-08-12 15:14:17] [vfit.concept]  Inappropriate: 0
INFO [2019-08-12 15:14:17] [vfit.concept]  Not valid users: 0

**Comment by converge** [comment]
the block depends on the account, I have one I forced a lot, and it's blocked, I have another one that I dont use much, and now it's working well.

**Comment by johnvfitness** [comment]
Ok thx bro 💪

**Comment by GaWr26** [comment]
> the block depends on the account, I have one I forced a lot, and it's blocked, I have another one that I dont use much, and now it's working well.

I can absolutely second this. Two of my accounts don't work and one works fine.
Just tried on one of the blocked ones after 4 days and get the block again right away. 
Anybody have an idea on how long to wait until the block gets removed? Does it ever?

**Comment by kranechan** [comment]
> the block depends on the account, I have one I forced a lot, and it's blocked, I have another one that I dont use much, and now it's working well.

@converge what is the rate of your another account that doesn't get blocked? 50 likes an hour? And how long does it rest?

**Comment by mario1105** [comment]
> > the block depends on the account, I have one I forced a lot, and it's blocked, I have another one that I dont use much, and now it's working well.
> 
> @converge what is the rate of your another account that doesn't get blocked? 50 likes an hour? And how long does it rest?

+1 The action delays config you got might be helpful for all of us who are being blocked everytime

**Comment by kranechan** [comment]
And also those who get like ban, which platform are you using (eg. Windows, rapsberry, etc)

**Comment by ghost** [comment]
+1 for me... blocked on all actions for instapy but in the app, on my phone, it works fine.

Windows 10 using the latest instapy with firefox.

**Comment by mario1105** [comment]
> And also those who get like ban, which platform are you using (eg. Windows, rapsberry, etc)

I'm runnning it in a server with an Ubuntu VM

**Comment by Affenjimbo** [comment]
I am running it on win.

**Comment by ghost** [comment]
I have different stories: totally unable to run on a cloud vps server (CentoOS-7) with both my accounts, I get blocked after 1 like attempt.
At home I run a Synology NAS with a VM with CentOS-7 installed: at the moment (and hope it will continue) both my accounts are running well, without issues.

**Comment by converge** [comment]
my "other" account, it was inactive for months, I just tested it for some hours, all good with that.

**Comment by ghost** [comment]
do you have action delays in your script? if so, are you able to share your settings along with your quota supervisor settings? @converge

**Comment by converge** [comment]
Don't follow my setup, it's the worst, I just do like by tags, folllow user followers and unfollow. nothing fancy about it.

**Comment by ArdyBeheshti** [comment]
import time
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

insta_username = 'username'
insta_password = 'password'

# custom session
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

# custom session settings
with smart_run(session):
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=.001,
                                    delimit_by_numbers=True,
                                    max_followers=1000000000,
                                    max_following=1000000000,
                                    min_followers=30,
                                    min_following=30)

    session.set_action_delays(enabled=True, like=300, comment=300)
    session.set_user_interact(amount=2, randomize=True, percentage=10, media='Photo')
    session.set_do_like(enabled=True, percentage=100)
    session.set_do_comment(enabled=True, percentage=60)
    session.set_comments(['oh, this is good', 'nice one here!', 'i like this one', 'how amazing is this!'])

    session.like_by_locations2(['204517928/chicago-illinois/', '213385402/london-united-kingdom/', '6889842/paris-france/', '213270076/mexico-city-mexico/', '213941548/seattle-washington/', '213136562/kyoto-japan/', '/271456804/japan/', '287620626/busan-south-korea/', '214288771/taipei-taiwan/', '216161580/encinitas-california/'], amount=100)
    session.like_by_tags2(['photography', 'anime', 'lofi', 'graphicdesign'], amount=100)
    time.sleep(21600)
    session.like_by_locations3(['4599325/denver-colorado', '2807792/la-jolla-california', '212988663/new-york-new-york', '13404453/bangkok-thailand', '270531492/italy', '31499759/rome-italy', '212964995/austin-texas', '217271987/bel-air-los-angeles', '214288771/taipei-taiwan', '213270076/mexico-city-mexico'], amount=100)
    session.like_by_tags3(['budlightdivetour', 'python', 'raybans', 'danielwellington'], amount=100)
    time.sleep(21600)
    session.like_by_locations(['212983635/san-diego-california/', '212999109/los-angeles-california/', '7226110/tokyo-japan/', '213755156/tehran-iran/', '745256841/seoul-south-korea/', '566976999/china/', '127963847/madrid-spain/', '212991559/toronto-ontario/', '212988663/new-york-new-york/', '44961364/san-francisco-california/'], amount=100)
    session.like_by_tags(['finalfantasy', 'cosplay', 'artists', 'books'], amount=100)
    time.sleep(21600)


This sort of build has been running well for me recently! Currently, I am trying to debug how Instgram's API algorithm has been causing this block issue.

**Comment by Jbry123** [comment]
We need @Timgrossmann here 😭

**Comment by ghost** [comment]
So I cleared my logs and deleted my database and now I'm running. It's been running for a few hours just fine. These are my quota settings at the moment. 

`    session.set_quota_supervisor(enabled=True,
                                 peak_likes_hourly=50,
                                 peak_likes_daily=1000,
                                 peak_comments_hourly=10,
                                 peak_comments_daily=100,
                                 peak_follows_hourly=30,
                                 peak_follows_daily=150,
                                 peak_unfollows_hourly=30,
                                 peak_unfollows_daily=150,
                                 sleep_after=["likes", "comments", "follows", "unfollows"],
                                 sleepyhead=True, stochastic_flow=True, notify_me=True)`

**Comment by rvoets** [comment]
Still running? @halalfood

**Comment by Mehran** [comment]
I think it's Risky nowadays use a bot, they Detected it should wait to find a stable and undetectable way.
.
![1](https://user-images.githubusercontent.com/23736885/62920788-f9dc2900-bdbb-11e9-8852-ef945fc4b53d.jpg)
![2](https://user-images.githubusercontent.com/23736885/62920794-fc3e8300-bdbb-11e9-9946-105ff11213ca.jpg)

**Comment by Jbry123** [comment]
My problem is a device block I believe, basically they’re recognizing that it’s not mobile, then watching for patterns, hence I get blocked after 30 likes,

Have you guys looked into Jarvee?

**Comment by Jbry123** [comment]
And I’m still able to like on my phone after that

**Comment by GaWr26** [comment]
> Have you guys looked into Jarvee?

Jarvee does currently not work for Instagram for me. I tested and now two of my accounts get instant blocks. One Account I didn't use in Jarvee works super smooth with InstaPy on 0.6.1 with the new approach using firefox and hiding selenium from my residential IP.

Need to wait a couple of days until I can enable the other accounts again with InstaPy.

I think InstaPy is closest to nailing it again after the recent changes.

**Comment by ghost** [comment]
> Still running? @halalfood

still running but I ran into action blocked unfollow limit. I'm going to lower my hourly/daily follow and unfollow limit because it's still too high.

**Comment by mario1105** [comment]
> > Have you guys looked into Jarvee?
> 
> Jarvee does currently not work for Instagram for me. I tested and now two of my accounts get instant blocks. One Account I didn't use in Jarvee works super smooth with InstaPy on 0.6.1 with the new approach using firefox and hiding selenium from my residential IP.
> 
> Need to wait a couple of days until I can enable the other accounts again with InstaPy.
> 
> I think InstaPy is closest to nailing it again after the recent changes.

How do you set up that firefox feature?

**Comment by sergiosre** [comment]
I have the same error: 

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-15 18:56:45] [tropicrivas]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-08-15 18:56:45] [tropicrivas]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-08-15 18:56:46] [tropicrivas]  - Internet Connection Status: ok
INFO [2019-08-15 18:56:46] [tropicrivas]  - Current IP is "146.158.225.182" and it's from "Spain/ES"
INFO [2019-08-15 18:56:46] [tropicrivas]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-08-15 18:56:50] [tropicrivas]  - Instagram WebSite Status: Currently Up 
INFO [2019-08-15 18:56:50] [tropicrivas]  - Instagram Response Time: 122.204 ms 
INFO [2019-08-15 18:56:51] [tropicrivas]  - Instagram Reponse Code: 200
INFO [2019-08-15 18:56:51] [tropicrivas]  - Instagram Server Status: ok
INFO [2019-08-15 18:56:51] [tropicrivas]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-08-15 18:56:51] [tropicrivas]  - window.navigator.webdriver response: False
INFO [2019-08-15 18:56:51] [tropicrivas]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

.........................................................................................................................
CRITICAL [2019-08-15 18:57:07] [tropicrivas]  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2019-08-15 18:57:11] [tropicrivas]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 33.39 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-15 18:57:11] [tropicrivas]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Someone could help me ?

**Comment by rvoets** [comment]
Try to login manually using your browser (Firefox), fill in the code for the unusual login attempt popup and when that's done try again with instapy. That's how I fixed it @sergiosre

**Comment by sergiosre** [comment]
@rvoets i tried that you said but the error continue.

**Comment by oscarbau** [comment]
Same issue here

**Comment by Skyhowler** [comment]
same issue here.
after deleting cookie and log, it works for few hours then got blocked again

**Comment by luisGithubPeru** [comment]
If this helps someone, I have been running like_by_locations and like_by_tags for months without problem, but 2 days ago tried grab_following, follow_by_followers and inmediatly got an IG notification of  "Your Account Was Compromised" so better stay away of those scrapping methods

**Comment by rvoets** [comment]
@luisGithubPeru I tried running it again after a few months of doing nothing and got blocked after 30+ likes using like_by_tags only. Could you share how many likes you are you doing per hour? Thanks

**Comment by luisGithubPeru** [comment]
> @luisGithubPeru I tried running it again after a few months of doing nothing and got blocked after 30+ likes using like_by_tags only. Could you share how many likes you are you doing per hour? Thanks

Sure @rvoets , after some research I defined the following limits for a 2 months old account (I always use less actions that the ones recommended on IG blogs) :

--------------------

### Daily Limits
daily_likes = 150 # recommended 200 max 
daily_comments = 20 #recommended  30 max 
daily_follows = 40 # recommended 50 max 

### Hour Limits
hour_likes = 50
hour_comments = 5
hour_follows = 10

### Delays
delay_seconds = 40
delay_random_factor = 1.5 # this makes delay go from 40 to 60 seconds (40*1.5)

--------------------

These are the settings I use for my Bot, the engagement is very slow for a viral account but mine is for an online store and it's really helping with sells (It is also helping my facebook which I have no idea how).

I got blocked 2 times, 1 was a full block when using "follow_by_followers" and the other was a comments block using "like_by_tags" which I think was because I made more than 200 likes and 30 comments per day, so I disabled comments and lowered the likes rate. Now I'm getting  from 5 to 10 followers per day and my comments ban dissapeared. 

Also creating original content and then interacting using the right hashtags, locations and follower lists has got me better results than raising the likes rate, good luck!

**Comment by rvoets** [comment]
Thanks a lot @luisGithubPeru for sharing your settings. I'm already seeing big improvements although my bot got blocked on Likes again after running for about 10 hours (which is way longer than before). Are you using like_by_tags or something else? I'm doing 10 likes per tag but maybe this can be improved as well.
