### ISSUE TITLE
I built myself a Dashboard using https://metabase.com/

### ISSUE THREAD

**Issue by GaWr26** [InstaPy/InstaPy#4791]
<img width="1628" alt="Bildschirmfoto 2019-08-07 um 17 36 17" src="https://user-images.githubusercontent.com/1381617/62636630-29adab80-b93a-11e9-8482-ac63ba7629b8.png">
Now I want much more data in the database!

**Comment by ArdyBeheshti** [comment]
Hey this is pretty cool! How did you set this up?

**Comment by mrallanodreman** [comment]
Wow nice!

**Comment by GaWr26** [comment]
First of all I got inspired by https://github.com/converge/instapy-dashboard so thanks a buch for that!
The problem I was facing there was the multiple databases as i run multiple accounts.
If you install metabase which is a written in java and run it you can connect to many databases. 
I just connected it to each sqllite database of instapy. 
Then you need to start building your dashboard which is pretty straight forward and really easy. 
No coding required. 

I have it running on a RaspberryPi 3B and love it. It also starts a webserver and is responsive so now I can always see whats going on. Even on the go.

**Comment by ArdyBeheshti** [comment]
> 
> 
> First of all I got inspired by https://github.com/converge/instapy-dashboard so thanks a buch for that!
> The problem I was facing there was the multiple databases as i run multiple accounts.
> If you install metabase which is a written in java and run it you can connect to many databases.
> I just connected it to each sqllite database of instapy.
> Then you need to start building your dashboard which is pretty straight forward and really easy.
> No coding required.
> 
> I have it running on a RaspberryPi 3B and love it. It also starts a webserver and is responsive so now I can always see whats going on. Even on the go.

Sweet! When you mean multi dbs/account issues, does displaying them not work so seamlessly as showing just one account's information?

**Comment by GaWr26** [comment]
> Sweet! When you mean multi dbs/account issues, does displaying them not work so seamlessly as showing just one account's information?

I use split_db as I had quite some crashes with writing to only one db. The instapy-dashboard can only connect to one db and running multiple instances of it made no sense to me.

Metabase works great with multiple databases.

**Comment by lerra** [comment]
Do you have a docker image + instructions to share? :-)

**Comment by GaWr26** [comment]
> Do you have a docker image + instructions to share? :-)

Sorry, no docker image or documentation. I just played with it and am quite happy with the result. 
It's super straight forward as metabase is a really well built tool with a great UI. All you need to do is install it and select the appropriate database(s) and then go ahead and create a dashboard to your liking.

**Comment by flygohr** [comment]
Trying it out. How did you get the two in the top right? The increase from the previous day?

**Comment by GaWr26** [comment]
> Trying it out. How did you get the two in the top right? The increase from the previous day?

that's a smart Number. This should help:
<img width="912" alt="Bildschirmfoto 2019-08-15 um 09 48 06" src="https://user-images.githubusercontent.com/1381617/63080684-02f70280-bf42-11e9-99ff-23f8242998eb.png">

**Comment by flygohr** [comment]
Gotcha! Now I have them too. And how did you get the reverse ordering by date in the bottom two? Can't get my head around it

**Comment by flygohr** [comment]
![2019-08-15 10_11_13-Window](https://user-images.githubusercontent.com/13753044/63081900-16579d00-bf45-11e9-887c-dade68b9fd91.jpg)

**Comment by GaWr26** [comment]
Reverse ordering can be done on the far right with the three dots menu. There you can sort by created date and then select desc.

Also you could group by created if you want to get only one row per day.
