### ISSUE TITLE
TypeError: set_quota_supervisor() got an unexpected keyword argument 'peak_likes'

### ISSUE THREAD

**Issue by aliasgs** [InstaPy/InstaPy#4793]
## Current Behavior

 File "script01.py", line 38, in <module>
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments", "follows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, peak_likes=(40, 300), peak_comments=(15, 150), peak_follows=(30, 250), peak_server_calls=(None, 4700))
TypeError: set_quota_supervisor() got an unexpected keyword argument 'peak_likes'

## InstaPy configuration
# imports
import random
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = ''
insta_password = '.'

tag_list_01 = ['']
photo_comments_01 = ['']

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)
# interaction 
with smart_run(session):
    # general settings
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments", "follows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, peak_likes=(40, 300), peak_comments=(15, 150), peak_follows=(30, 250), peak_server_calls=(None, 4700))
    session.set_skip_users(skip_private=True,
                       private_percentage=100,
                       skip_no_profile_pic=True,
                       no_profile_pic_percentage=100)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=20000,
                                    max_following=20000,
                                    min_followers=100,
                                    min_following=1)
    session.set_user_interact(amount=3, randomize=False, percentage=70,
                              media='Photo')
    session.set_do_follow(enabled=True, percentage=50, times=1)
    session.set_do_like(enabled=True, percentage=100)
    #session.set_delimit_liking(enabled=True, max=1000)
   
    session.set_simulation(enabled=False)

    
    session.set_do_comment(enabled=True, percentage=50)
    session.set_comments(photo_comments_01, media='Photo')
    session.like_by_tags(tag_list_01, amount=random.randint(10, 15), skip_top_posts=True, interact=True, media='Photo')

**Comment by oscarbau** [comment]
same issue

**Comment by pacresito** [comment]
Hey @aliasgs !
Why did you close this? Where you able to find a solution?
Same thing is happening to me since a couple of weeks ago

**Comment by pacresito** [comment]
Autoanswer:
In the last version, the code changed from:
`peak_likes=(x, y),`
to
```
peak_likes_hourly=x, 
peak_likes_daily=y, 
```

**Comment by Dimaodyvan** [comment]
> Autoanswer:
> In the last version, the code changed from:
> `peak_likes=(x, y),`
> to
> 
> ```
> peak_likes_hourly=x, 
> peak_likes_daily=y, 
> ```

Thanks a lot, man! That helped!!!
