### ISSUE TITLE
ensure chromedriver is installed at ..

### ISSUE THREAD

**Issue by Edhim** [InstaPy/InstaPy#4794]
Hello, all was working well until i get this error since few days

Traceback (most recent call last):
  File "/Users/Edhim/Desktop/INSTAPY/Edhim/quickstart.py", line 14, in <module>
    headless_browser=True)
  File "/Users/Edhim/Desktop/INSTAPY/Edhim/instapy/instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "/Users/Edhim/Desktop/INSTAPY/Edhim/instapy/instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /usr/local/lib/python3.7/site-packages/instapy_chromedriver/chromedriver_mac64

Any ideas please ? 

Many Thanks.

**Comment by mikediachenko** [comment]
@Edhim Please, download latest Chrome. I think it will be version 76. After download suitable chrome driver from https://chromedriver.storage.googleapis.com/index.html?path=76.0.3809.68/ . After you extract chromedriver do `cp chromedriver /usr/local/lib/python3.7/site-packages/instapy_chromedriver/chromedriver_mac64`. And all should work fine.

**Comment by Edhim** [comment]
@mikediachenko   - Thank you worked well 👍

**Comment by Ugar93** [comment]
I have the next issue: Starting ChromeDriver 76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Can anyone help?

**Comment by d3rf** [comment]
I ve downloaded version 75 and now its ok
https://chromedriver.storage.googleapis.com/75.0.3770.90/chromedriver_linux64.zip

Download from the link put in the path and unzip

**Comment by sannyd** [comment]
worked awesome thank you!

**Comment by pilarfc** [comment]
> @Edhim Please, download latest Chrome. I think it will be version 76. After download suitable chrome driver from https://chromedriver.storage.googleapis.com/index.html?path=76.0.3809.68/ . After you extract chromedriver do `cp chromedriver /usr/local/lib/python3.7/site-packages/instapy_chromedriver/chromedriver_mac64`. And all should work fine.

Sorry I don't get this, after extract the chromedriver where I have to put it? Because after the download it extracts it at my downloads folder.
