### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by dickensac** [InstaPy/InstaPy#4799]
English
Your Account Was Compromised
It looks like you shared your password with a service to help you get more likes or followers, which goes against our Community Guidelines.
Change your password to continue using Instagram. If you share your new password with one of these services, you may get blocked from following, liking or commenting.

**Comment by ortegafernando** [comment]
please search others issues, there are lot of them with your problem. it is general

**Comment by ortegafernando** [comment]
and close this
