### ISSUE TITLE
Don't like by location

### ISSUE THREAD

**Issue by yuriscosta-zz** [InstaPy/InstaPy#480]
When I try to run 
`session.like_by_locations(['c1658008/bergen-norway/'], amount=10)`
I got
![image](https://user-images.githubusercontent.com/13898077/28995951-c85a03b4-79cc-11e7-87d3-62d33af2dc21.png)

**Comment by yuriscosta-zz** [comment]
Still not working...

**Comment by timgrossmann** [comment]
@yuriscosta Is this the newest version of the script?

Did you do `git pull`?

**Comment by yuriscosta-zz** [comment]
yeah, I did the git pull today

**Comment by timgrossmann** [comment]
@yuriscosta To be honest, you guys should actually start looking at the Readme and examples before posting issues stating it's not working...

If you look at the location you provided: https://www.instagram.com/explore/locations/c1658008/bergen-norway/

You can see that this is not the final page. 
Compare that to the example: https://www.instagram.com/explore/locations/224442573/salton-sea/

You can see that you should actually select a single location and not one of the location groups...

I don't want to sound rude here, just pointing out that it would help a lot if people started to actually read the documentation 😑

**Comment by yuriscosta-zz** [comment]
I read, but I understood that I can put the location like that. 
Thanks.

**Comment by yuriscosta-zz** [comment]
What about the load button not found?

**Comment by timgrossmann** [comment]
@yuriscosta The load button is not present on the location you provided.
Should work 😉 

Simply reopen if it's not working.
