### ISSUE TITLE
Unusual login attempt because of Useragent

### ISSUE THREAD

**Issue by Josexv1** [InstaPy/InstaPy#4801]
## Expected Behavior

Use current cookie and do the job, if no cookie found or invalid cookie found, try to get a new one.

## Current Behavior

It detects the current cookie as invalid because IG detects a new Useragent, and think it's a new browser, invalidating the login and asking for security code.

I have a setup with Schedule and every time the job runs i need to put the security code, using a VPS or my local machine with my usual IP.

Cookie file not found, creating cookie...
Issue with cookie for user ACCOUNT. Creating new cookie...
Instagram detected an unusual login attempt
A security code was sent to your Email: email @ email . com
Type the security code here:

![toctoc](https://user-images.githubusercontent.com/12077848/62723275-4ac7d800-b9de-11e9-80c0-33e07105685e.png)

## Possible Solution (optional)

Make use of the current useragent without changing every time you login.

## InstaPy configuration

```
def get_session():
    session = InstaPy(
    username=insta_username,
    password=insta_password,
    headless_browser=True,
    disable_image_load=True)
```

**Comment by mrallanodreman** [comment]
I solve this changing the user agent for the user agent of the app on my device... you can google it.

Afther that i never get the login attempt or the email 

"Instagram app user agent samsung a30" 

Looks something like this
You put it on arrows and magic happens!

 Mozilla/5.0 (Linux; Android 9; SM-A305G Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.157 Mobile Safari/537.36 Instagram 95.0.0.21.124 Android (28/9; 420dpi; 1080x2131; samsung; SM-A305G; a30; exynos7885; es_ES; 156514151) 

The user agent on indtabot.py by default
Dont spicify the android plataform or yhe screen resolution or dpi

So i suggest put the most exactly user agent for your device..

**Comment by Josexv1** [comment]
By **inatabot.py** you mean **instapy.py** or the file with your config? I know that using a single User agent helps avoid this situation, hence this issue. Also i would like to setup some config param instead of modifying a source file directly.

**Comment by mrallanodreman** [comment]
Instabot.py

self.user_agent = and replace random.sample(config.get("list_of_ua"), 1)[0] by your user agent 

Yu can edit the "list_of_ua" in the default_config.py

**Comment by senatorlila** [comment]
> self.user_agent

I think you are in the wrong instagram bot application

**Comment by senatorlila** [comment]
> Instabot.py
> 
> self.user_agent = and replace random.sample(config.get("list_of_ua"), 1)[0] by your user agent
> 
> Yu can edit the "list_of_ua" in the default_config.py

I think you are in the wrong instagram bot application. 
Generally the idea is good to change the user agent but where?
