### ISSUE TITLE
Wrong login with Special char FIXED in Chromedriver

### ISSUE THREAD

**Issue by gerfra** [InstaPy/InstaPy#4802]
## Possible Solution (optional)

My final solution, send unicode char from python, this is a bug in Instapy **login_util.py**, because if the pc keyboard use CH Schweiz the character like **!** are trimmed, the easy way is convert in utf-8 like this:

at line 286:    **password = unicode(str(password), "utf-8")**

My settings: 
CH-de keyboard
Chrome Versione 76.0.3809.100 (Build ufficiale) (a 64 bit)
ChromeDriver 76.0.3809.68
Python37
Win10_64bit

I hope it's useful for Swiss developers

**Comment by degiorgig** [comment]
unicode in not present anymore in python3 has been replaced by str

**Comment by gerfra** [comment]
Right, anyway, the output from python is interpreted wrongly. To risolve this problem when using  a swiss keyboard, one  has to modify this file, with:
str(password, 'utf-8')
Ciao.
