### ISSUE TITLE
Session crashes without creating cookie

### ISSUE THREAD

**Issue by GGaitanis** [InstaPy/InstaPy#4804]
## Current Behavior
[Session lasted 25.13 seconds]
INFO [2019-08-09 07:32:13] [xxxx]  Session ended!

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/ec2-user/InstaPy"

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "like_by_tag_interact_unfollow.py", line 38, in <module>
    with smart_run(session):
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/ec2-user/InstaPy/instapy/util.py", line 1691, in smart_run
    session.login()
  File "/home/ec2-user/InstaPy/instapy/instapy.py", line 414, in login
    self.bypass_with_mobile):
  File "/home/ec2-user/InstaPy/instapy/login_util.py", line 345, in login_user
    logger.warn(error_alert.text)
AttributeError: 'LoggerAdapter' object has no attribute 'warn'

**Comment by mikediachenko** [comment]
Strange, I’ve got the same errors after upgrade, but InstaPY continues to work.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mikediachenko** [comment]
Yesterday all was working, but just now I've tried on the same server and InstaPY stopped working with the next message after trying to create a cookie:
`OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-09 15:32:32] []  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2019-08-09 15:32:32] [it_b_s]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2019-08-09 15:32:33] [it_b_s]  - Internet Connection Status: ok
INFO [2019-08-09 15:32:33] [it_b_s]  -- Connection Checklist [2/2] (Instagram Server Status)
INFO [2019-08-09 15:32:38] [it_b_s]  - Instagram WebSite Status: Currently Up 
INFO [2019-08-09 15:32:38] [it_b_s]  - Instagram Response Time: 57.336 ms 
INFO [2019-08-09 15:32:38] [it_b_s]  - Instagram Reponse Code: 200
INFO [2019-08-09 15:32:38] [it_b_s]  - Instagram Server Status: ok
Cookie file not found, creating cookie...
Issue with cookie for user . Creating new cookie...

....................................................................................................................
CRITICAL [2019-08-09 15:33:24] []  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2019-08-09 15:33:24] []  Sessional Live Report:
        |> No any statistics to show`

**Comment by d3rf** [comment]
> Yesterday all was working, but just now I've tried on the same server and InstaPY stopped working with the next message after trying to create a cookie:
> `OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2019-08-09 15:32:32] [] Session started!
> oooooooooooooooooooooooooooooooooooooooooooooooooooooo
> 
> INFO [2019-08-09 15:32:32] [it_b_s] -- Connection Checklist [1/2] (Internet Connection Status)
> INFO [2019-08-09 15:32:33] [it_b_s] - Internet Connection Status: ok
> INFO [2019-08-09 15:32:33] [it_b_s] -- Connection Checklist [2/2] (Instagram Server Status)
> INFO [2019-08-09 15:32:38] [it_b_s] - Instagram WebSite Status: Currently Up
> INFO [2019-08-09 15:32:38] [it_b_s] - Instagram Response Time: 57.336 ms
> INFO [2019-08-09 15:32:38] [it_b_s] - Instagram Reponse Code: 200
> INFO [2019-08-09 15:32:38] [it_b_s] - Instagram Server Status: ok
> Cookie file not found, creating cookie...
> Issue with cookie for user . Creating new cookie...
> 
> ....................................................................................................................
> CRITICAL [2019-08-09 15:33:24] [] Unable to login to Instagram! You will find more information in the logs above.
> ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
> 
> INFO [2019-08-09 15:33:24] [] Sessional Live Report:
> |> No any statistics to show`

Same error here, I dont have a clue whats wrong! I ve tested with another account and Its ok there. Some accounts works, another dont.

**Comment by mikediachenko** [comment]
And after 10-15 seconds of successful script running and I've an error from Instagram, like `Error. Your cookies are not enabled or you are browsing in Private Mode. Please, turn on cookie or turn off Private Mode`. Cookies are enabled, but the script runs in Private Mode. Funny 😂 Seems Insta is becoming more and more smart 😩

**Comment by GGaitanis** [comment]
Can you please indicate how we can perform those activities on linux instance?
