### ISSUE TITLE
"Failed to get followers count" and "user is inaccessible"

### ISSUE THREAD

**Issue by martinkrulltott** [InstaPy/InstaPy#4805]
## Issue
After I came across this issue https://github.com/timgrossmann/InstaPy/issues/4645 I've been monitoring the unfollowing process. I've set up my script to perform multiple smaller unfollow steps in increments of 10 rather than 100 at a time, to prevent one failed unfollow to crash the whole thing. However in my latest run I came across two new issues with the unfollowing (full log below) which crashed all of my unfollow steps.

First there seemed to be an issue with loading the followers list.
After 300 successful attempts of "follow_user_followers" I first started seeing it with getting other users followers count about 10 times.
`INFO [2019-08-08 22:51:55] [myusername]  Failed to get followers count of 'b'anotherusername''  ~empty list`

And it then started happening when trying to load my followers for the unfollowing script:
`INFO [2019-08-08 23:08:57] [myusername]  Failed to get followers count of 'b'myusername''  ~empty list`

I can see in the logs that this has happened once before a few months ago, so maybe thats just a temporary hiccup.

However, after a few iterations of my unfollow script it finally got to load the list, but then something even more strange happened. 

`INFO [2019-08-08 23:11:57] [myusername]  Ongoing Unfollow [1/10]: now unfollowing 'b'someusername''...
WARNING [2019-08-08 23:12:03] [myusername]  The page isn't available!	~the link may be broken, or the page may have been removed...
WARNING [2019-08-08 23:12:03] [myusername]  Couldn't access the profile page of 'someusername'!	~might have changed the username
INFO [2019-08-08 23:12:03] [myusername]  Trying to find the username from the given user ID by loading a post
WARNING [2019-08-08 23:12:14] [myusername]  The page isn't available!	~the link may be broken, or the page may have been removed...
ERROR [2019-08-08 23:12:14] [myusername]  --> Unable to detect the following status of 'b'someusername''!
WARNING [2019-08-08 23:12:14] [myusername]  --> Couldn't unfollow 'someusername'!	~user is inaccessible
INFO [2019-08-08 23:12:14] [myusername]  	Removed '2019-08-05 22:23 ~ someusername ~ 123123123' from myusername_followedPool.csv file`

For some reason it's not being able to access the users page. Worst of all, this was repeated for other users over a 100 times!! And each time it removed the username from the followedPool list, so all of a sudden I've got another 100 rogue users in my following list.

Has anyone experienced anything similar?
I can see that the previous run the same day went perfectly fine, so this seems to be either just a one off thing or something must have changed with the Instapy-Instagram integration thats causing the issues with the followers list and unfollowing process.

## InstaPy configuration

**Bot code**
`unfollowAmount = 100
    successfulUnfollows = 0
    originalUnfollows = unfollowAmount
    if performUnfollowUsers and unfollowAmount > 0:
        while unfollowAmount > 0:
            currentAmount = 10
            if unfollowAmount < currentAmount:
                currentAmount = unfollowAmount
            unfollowAmount = unfollowAmount - currentAmount
            try:
                session.unfollow_users(amount=currentAmount, InstapyFollowed=(True, "all"), style="FIFO", unfollow_after=72*60*60, sleep_delay=randint(600, 700))
                successfulUnfollows += currentAmount
            except Exception as e:
                print("ERROR with unfollow_users: " + str(e))
        print("Looped through " + str(successfulUnfollows) + " unfollows successfully")`

**Log**
`INFO [2019-08-08 23:08:04] [myusername]  Starting to unfollow users..
INFO [2019-08-08 23:08:57] [myusername]  Failed to get followers count of 'b'myusername''  ~empty list
INFO [2019-08-08 23:09:47] [myusername]  Failed to get following count of 'b'myusername''  ~empty list
WARNING [2019-08-08 23:09:47] [myusername]  Unable to find the count of users followed  ~leaving unfollow feature
INFO [2019-08-08 23:09:47] [myusername]  --> Total people unfollowed : 0

INFO [2019-08-08 23:09:48] [myusername]  Starting to unfollow users..
INFO [2019-08-08 23:10:38] [myusername]  Failed to get followers count of 'b'myusername''  ~empty list
INFO [2019-08-08 23:11:29] [myusername]  Failed to get following count of 'b'myusername''  ~empty list
WARNING [2019-08-08 23:11:29] [myusername]  Unable to find the count of users followed  ~leaving unfollow feature
INFO [2019-08-08 23:11:29] [myusername]  --> Total people unfollowed : 0

INFO [2019-08-08 23:11:29] [myusername]  Starting to unfollow users..
INFO [2019-08-08 23:11:57] [myusername]  Unfollowing the users followed by InstaPy

INFO [2019-08-08 23:11:57] [myusername]  Total 58 users available to unfollow  ~didn't pass `unfollow_after`: 295

INFO [2019-08-08 23:11:57] [myusername]  Ongoing Unfollow [1/10]: now unfollowing 'b'someusername''...
WARNING [2019-08-08 23:12:03] [myusername]  The page isn't available!	~the link may be broken, or the page may have been removed...
WARNING [2019-08-08 23:12:03] [myusername]  Couldn't access the profile page of 'someusername'!	~might have changed the username
INFO [2019-08-08 23:12:03] [myusername]  Trying to find the username from the given user ID by loading a post
WARNING [2019-08-08 23:12:14] [myusername]  The page isn't available!	~the link may be broken, or the page may have been removed...
ERROR [2019-08-08 23:12:14] [myusername]  --> Unable to detect the following status of 'b'someusername''!
WARNING [2019-08-08 23:12:14] [myusername]  --> Couldn't unfollow 'someusername'!	~user is inaccessible
INFO [2019-08-08 23:12:14] [myusername]  	Removed '2019-08-05 22:23 ~ someusername ~ 123123123' from myusername_followedPool.csv file
ing Unfollow [1/10]: now unfollowing 'b'anotherusername''...
WARNING [2019-08-08 23:12:21] [myusername]  The page isn't available!	~the link may be broken, or the page may have been removed...
WARNING [2019-08-08 23:12:21] [myusername]  Couldn't access the profile page of 'anotherusername'!	~might have changed the username
INFO [2019-08-08 23:12:21] [myusername]  Trying to find the username from the given user ID by loading a post
WARNING [2019-08-08 23:12:33] [myusername]  The page isn't available!	~the link may be broken, or the page may have been removed...
ERROR [2019-08-08 23:12:33] [myusername]  --> Unable to detect the following status of 'b'anotherusername''!
WARNING [2019-08-08 23:12:33] [myusername]  --> Couldn't unfollow 'anotherusername'!	~user is inaccessible
INFO [2019-08-08 23:12:33] [myusername]  	Removed '2019-08-05 21:04 ~ anotherusername ~ 123123123' from myusername_followedPool.csv file

[REPEATED THE ABOVE LINES OVER A 100 TIMES]

INFO [2019-08-08 23:30:34] [myusername]  --> Total people unfollowed : 1

INFO [2019-08-08 23:30:34] [myusername]  Starting to unfollow users..
INFO [2019-08-08 23:31:28] [myusername]  Failed to get followers count of 'b'myusername''  ~empty list
INFO [2019-08-08 23:32:18] [myusername]  Failed to get following count of 'b'myusername''  ~empty list
WARNING [2019-08-08 23:32:18] [myusername]  Unable to find the count of users followed  ~leaving unfollow feature
INFO [2019-08-08 23:32:18] [myusername]  --> Total people unfollowed : 0

INFO [2019-08-08 23:32:18] [myusername]  Starting to unfollow users..
INFO [2019-08-08 23:32:46] [myusername]  Unfollowing the users followed by InstaPy

INFO [2019-08-08 23:32:46] [myusername]  Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 295

INFO [2019-08-08 23:32:46] [myusername]  There are no any users available to unfollow
INFO [2019-08-08 23:32:46] [myusername]  --> Total people unfollowed : 0

INFO [2019-08-08 23:32:46] [myusername]  Starting to unfollow users..
INFO [2019-08-08 23:32:46] [myusername]  Unfollowing the users followed by InstaPy

INFO [2019-08-08 23:32:46] [myusername]  Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 295

INFO [2019-08-08 23:32:46] [myusername]  There are no any users available to unfollow
INFO [2019-08-08 23:32:46] [myusername]  --> Total people unfollowed : 0

INFO [2019-08-08 23:32:46] [myusername]  Starting to unfollow users..
INFO [2019-08-08 23:32:46] [myusername]  Unfollowing the users followed by InstaPy

INFO [2019-08-08 23:32:46] [myusername]  Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 295

INFO [2019-08-08 23:32:46] [myusername]  There are no any users available to unfollow
INFO [2019-08-08 23:32:46] [myusername]  --> Total people unfollowed : 0

INFO [2019-08-08 23:32:46] [myusername]  Starting to unfollow users..
INFO [2019-08-08 23:32:46] [myusername]  Unfollowing the users followed by InstaPy

INFO [2019-08-08 23:32:47] [myusername]  Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 295

INFO [2019-08-08 23:32:47] [myusername]  There are no any users available to unfollow
INFO [2019-08-08 23:32:47] [myusername]  --> Total people unfollowed : 0

INFO [2019-08-08 23:32:47] [myusername]  Starting to unfollow users..
INFO [2019-08-08 23:32:47] [myusername]  Unfollowing the users followed by InstaPy

INFO [2019-08-08 23:32:47] [myusername]  Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 295

INFO [2019-08-08 23:32:47] [myusername]  There are no any users available to unfollow
INFO [2019-08-08 23:32:47] [myusername]  --> Total people unfollowed : 0

INFO [2019-08-08 23:32:47] [myusername]  Starting to unfollow users..
INFO [2019-08-08 23:32:47] [myusername]  Unfollowing the users followed by InstaPy

INFO [2019-08-08 23:32:47] [myusername]  Total 0 users available to unfollow  ~didn't pass `unfollow_after`: 295

INFO [2019-08-08 23:32:47] [myusername]  There are no any users available to unfollow
INFO [2019-08-08 23:32:47] [myusername]  --> Total people unfollowed : 0`

**Comment by hw711** [comment]
Something maybe wrong with the graphql queries to grab followers/following. 

Example of query to grab following https://www.instagram.com/graphql/query/?query_hash=58712303d941c6855d4e888c5f0cd22f&variables={%22id%22:%2010166260976,%20%22first%22:%2050}

Before today it would just return the json with small portion of following list (and instapy keeps on grabbing next page).  Now the query just returns

"Error
This page could not be loaded. If you have cookies disabled in your browser, or you are browsing in Private Mode, please try enabling cookies or turning off Private Mode, and then retrying your action."

**Comment by instasck** [comment]
Some here scrapping is having this error, maybe graphql change only.

**Comment by converge** [comment]
I was preparing some improvements with GraphQL calls, today it's not working anymore, let's wait a bit, maybe it's some IG bug and they will fix it later.

**Comment by hw711** [comment]
seems to be working again, thank god

**Comment by uni1783** [comment]
I'm getting these errors again today.

**Comment by hw711** [comment]
IG implemented new rate limit around last Friday.  If you look at the browser and see Error try again in a few minutes, that means you are opening profiles too fast and got rate limited.  You just have to wait it out.  It will go away in a few hours

**Comment by ghost** [comment]
i had been having this problem for days, the only place where it doesnt affect me is using intapy gui but there the comments and likes dont work
