### ISSUE TITLE
Cookie file not found, creating cookie... Issue with cookie for user

### ISSUE THREAD

**Issue by Flaunkerton2395** [InstaPy/InstaPy#4811]
## Expected Behavior
Save cookie and use it for every session

## Current Behavior
Cookie is currently saved in proper folder and the file's info even shows that it was modified, but the cookie still is not used

## InstaPy configuration
Current Chrome version: Version 76.0.3809.100 
Python version: 3.7
Instapy version: 0.5.8

Is anyone else still running into this issue over their cookies? The cookie file is definitely being saved and changed with each run, but the file is not being used and I am not sure what 'Issue with cookie for user' could possibly mean.

**Comment by nano2dev** [comment]
God dammit. This sucked up all my Sunday. 

For anyone googling this error:

This seems to be an issue with selenium & chrome.

Here: https://github.com/timgrossmann/InstaPy/blob/f4c6dd2238a03fadfa8324522e2eac4bc3e54f51/instapy/login_util.py#L202

Cookies are not loading into browser. Generic error will be "Cookie file not found, creating cookie..." -- But if we print the exception we see the error is actually:

Message: invalid argument: invalid 'expiry' (Session info: chrome=__YOUR_VERSION__)

Solution:

Edit '/usr/local/lib/python3.6/dist-packages/instapy/login_util.py' @ line 202

Should look like this 

```python
    try:
        for cookie in pickle.load(open('{0}{1}_cookie.pkl'.format(logfolder, username), 'rb')):
            # delete key causing cookie not to be added to browser
            if 'expiry' in cookie:
               del cookie['expiry']            
            browser.add_cookie(cookie)
            cookie_loaded = True
    except (WebDriverException, OSError, IOError):
        print("Cookie file not found, creating cookie...")
```

More: https://stackoverflow.com/questions/56663666/how-to-fix-invalid-argument-invalid-expiry-in-selenium-when-adding-cookies

**Comment by Flaunkerton2395** [comment]
@estebansanti Thank you very much for your time!! My issues still stay the same but I did notice something new. Occasionally when the window first opens, it claims to say that Chrome is out of date. But when I actually check the version under 'About', Chrome says that it is up to date. 

Could that have something to do with the issue?

**Comment by radgezito** [comment]
I'm having this problem using chrome and firefox with instapy 0.6.10

**Comment by filiperivelli** [comment]
> I'm having this problem using chrome and firefox with instapy 0.6.10

The same here
