### ISSUE TITLE
CANT RUN Auto closes after Start.bat also in when i py quickstart.py

### ISSUE THREAD

**Issue by Backlonely** [InstaPy/InstaPy#482]
I have tryed doing it on powershell and cmd i get errors like syntax error line 1. I have kali and windows but no luck at all. Please help me!

**Comment by timgrossmann** [comment]
@Backlonely Could you please copy your quickstart.py file here?

**Comment by Backlonely** [comment]
Yes. I will as soon as I can.

_Sent from my Samsung SM-G935T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Backlonely** [comment]
I also have tried with the GUI I press run and nothing happens exept getting quickstart.py and a START.bat file in my master folder... 

_Sent from my Samsung SM-G935T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Backlonely** [comment]
```python
from instapy import InstaPy
import os
session = InstaPy(username='', password='')
session.login()
session.set_do_follow(enabled=True, percentage=50, times=1)
session.unfollow_users(amount=10)
session.like_by_tags(['follow4follow', 'followforfollow'], amount=500)

session.end()

**Comment by Backlonely** [comment]
I also got these errors when I run the windows.ps1


InstaPy Windows Setup
=============================================================================================
Installing Selenium
pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\No Password\Desktop\InstagramBot\InstaPy-master\scripts\windows.ps1:4 char:1
+ pip install selenium
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\No Password\Desktop\InstagramBot\InstaPy-master\scripts\windows.ps1:5 char:1
+ python -m pip install pyvirtualdisplay
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

C:\Program Files\Python36\python.exe: can't open file 'get-pip.py': [Errno 2] No such file or directory

Installing GUI Tool
mv : Cannot create a file when that file already exists.
At C:\Users\No Password\Desktop\InstagramBot\InstaPy-master\scripts\windows.ps1:11 char:1
+ mv "$pwd\InstaPy-GUI.exe" "$pwd\..\InstaPy-GUI.exe"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\No Pas...InstaPy-GUI.exe:FileInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveFileInfoItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand


Downloading Chrome Driver...
Chrome Driver download completed.

Unzipping Chrome Driver...
mv : Cannot create a file when that file already exists.
At C:\Users\No Password\Desktop\InstagramBot\InstaPy-master\scripts\windows.ps1:26 char:1
+ mv "$pwd\assets\chromedriver.exe" "$pwd\assets\chromedriver"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\No Pas...hromedriver.exe:FileInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveFileInfoItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand

Unzipping completed.

Removing unneeded files...
Removal completed.

python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\No Password\Desktop\InstagramBot\InstaPy-master\scripts\windows.ps1:33 char:1
+ python setup.py install
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Setup is completed.
Press Enter to continue...:

**Comment by djrare** [comment]
Mam reszte doc jesli potrzebne sa_______
