### ISSUE TITLE
Session ends after enter the security code in 2FA

### ISSUE THREAD

**Issue by e1x4** [InstaPy/InstaPy#4820]
After I insert the secutity code I receive by sms, for two factors authentication, the session ends and the chrome and quickstart window are closed. it's been a few days,  before it has always worked well.

**Comment by instasck** [comment]
I think you need to manually remove the line "remove_session ..." under cordinates (the one before login) so the session cookie will stay as a file.

**Comment by joshuazmiller** [comment]
I have the same issue, both for headless and non-headless. Also stalebot closed #4742 which was not resolved.
