### ISSUE TITLE
Couldn't install on OSX 10.13 | trouble with clarifai and 'six'

### ISSUE THREAD

**Issue by isampeace** [InstaPy/InstaPy#4826]
## Current Behavior
ERROR: clarifai 2.6.2 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.2 which is incompatible.

Found existing installation: six 1.4.1
ERROR: Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by redsector72** [comment]
Mac uses python 2.7. You have to upgrade it to python 3. Google how to as there are many ways
