### ISSUE TITLE
Wont run after update

### ISSUE THREAD

**Issue by Dimon1011** [InstaPy/InstaPy#4830]
Traceback (most recent call last):
  File "The_Best_So_Far.py", line 29, in <module>
    peak_server_calls=(120, 2000))
TypeError: set_quota_supervisor() got an unexpected keyword argument 'peak_comments'

My layout:

    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,                            
                             peak_comments=(20, 120),
                             peak_likes=(10, 120),
                             peak_follows=(20, 160),
                             peak_unfollows=(20, 160),
                             peak_server_calls=(120, 2000))

**Comment by sannyd** [comment]
I noticed the new update requires Firefox.  Do you have that installed?  I had only chrome installed before, now I have Firefox.

**Comment by Dimon1011** [comment]
Yeah,
 I installed Firefox and the script executed fine until that error.

**Comment by sannyd** [comment]
mine doesn't work either, it cannot find the "lower" confirmation. :(

**Comment by converge** [comment]
have a look on docs, the feature was updated.
