### ISSUE TITLE
Watching stories does not move forward with 0.6.1

### ISSUE THREAD

**Issue by Zettt** [InstaPy/InstaPy#4831]
## Expected Behavior
After last story is watched, continue watching the remaining reels.

## Current Behavior
Firefox goes into some sort of fullscreen mode, then after the last story is watched it exits, but InstaPy doesn't pick it up.

## InstaPy configuration
```
session.set_do_story(enabled = True, percentage = 80, simulate = False)
session.story_by_tags(['tag1', 'tag2'])    
```

**Comment by christophe-duc** [comment]
yes, known issue, please use simulate = True meanwhile

**Comment by Zettt** [comment]
Thanks. Does this function just mark all stories as watched, or does it still wait for each story inside a reel to finish?

**Comment by Zettt** [comment]
This is not stale.

**Comment by arpitjacob** [comment]
Does this work
