### ISSUE TITLE
Not sure exactly what the issue is

### ISSUE THREAD

**Issue by GreatMalboro** [InstaPy/InstaPy#4836]
## Expected Behavior
I just need it to simply run now. Was working till about 3 days ago.  No changes were made to my original startup, So since it doesnt run now I put it in a seperate folder. I also noticed and installed firefox to no avail, and gecko driver.exe opens for no reason.
## Current Behavior
`=== RESTART: C:\Users\Higher Thoughts\Desktop\InstaPy-master\quickstart.py ===

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/Higher Thoughts/InstaPy"
Traceback (most recent call last):
  File "C:\Users\Higher Thoughts\Desktop\InstaPy-master\quickstart.py", line 14, in <module>
    headless_browser=False)
  File "C:\Users\Higher Thoughts\Desktop\InstaPy-master\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "C:\Users\Higher Thoughts\Desktop\InstaPy-master\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`

## Possible Solution (optional)
Im not sure, but ive been working on it and will still be, but It may have something to do with the versions of my drivers. And at this point I think I just need and update on that unless its currently in progress or my solution is solved, then I guess this means nothing. I did a bunch of pip installs including chromedriver and gecko. Not sure if those paths are causing trouble for each other or something.

## InstaPy configuration

""" Quickstart script for InstaPy usage """
`# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = name  # <- enter username here
insta_password =  pass # <- enter password here

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                    min_followers=45,
                                    min_following=77)

    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])

    # activity
    session.like_by_tags(["natgeo"], amount=10)`

**Comment by GreatMalboro** [comment]
Found new issue and im working that out PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Higher Thoughts\\InstaPy\\assets\\geckodriver.exe'

**Comment by ramoe728** [comment]
I have these exact same issues.  Have you worked it out?  I haven't yet.

**Comment by J3store** [comment]
What

> ## Expected Behavior
> I just need it to simply run now. Was working till about 3 days ago. No changes were made to my original startup, So since it doesnt run now I put it in a seperate folder. I also noticed and installed firefox to no avail, and gecko driver.exe opens for no reason.
> 
> ## Current Behavior
> `=== RESTART: C:\Users\Higher Thoughts\Desktop\InstaPy-master\quickstart.py ===
> 
> ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._.
> Workspace in use: "C:/Users/Higher Thoughts/InstaPy"
> Traceback (most recent call last):
> File "C:\Users\Higher Thoughts\Desktop\InstaPy-master\quickstart.py", line 14, in
> headless_browser=False)
> File "C:\Users\Higher Thoughts\Desktop\InstaPy-master\instapy\instapy.py", line 318, in **init**
> self.logger,
> File "C:\Users\Higher Thoughts\Desktop\InstaPy-master\instapy\browser.py", line 114, in set_selenium_local_session
> options=firefox_options,
> File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in **init**
> keep_alive=True)
> File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "C:\Users\Higher Thoughts\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`
> 
> ## Possible Solution (optional)
> Im not sure, but ive been working on it and will still be, but It may have something to do with the versions of my drivers. And at this point I think I just need and update on that unless its currently in progress or my solution is solved, then I guess this means nothing. I did a bunch of pip installs including chromedriver and gecko. Not sure if those paths are causing trouble for each other or something.
> 
> ## InstaPy configuration
> """ Quickstart script for InstaPy usage """
> `# imports
> from instapy import InstaPy
> from instapy import smart_run
> 
> # login credentials
> insta_username = name # <- enter username here
> insta_password = pass # <- enter password here
> 
> # get an InstaPy session!
> # set headless_browser=True to run InstaPy in the background
> session = InstaPy(username=insta_username,
> password=insta_password,
> headless_browser=False)
> 
> with smart_run(session):
> """ Activity flow """
> # general settings
> session.set_relationship_bounds(enabled=True,
> delimit_by_numbers=True,
> max_followers=4590,
> min_followers=45,
> min_following=77)
> 
> ```
> session.set_dont_include(["friend1", "friend2", "friend3"])
> session.set_dont_like(["pizza", "#store"])
> 
> # activity
> session.like_by_tags(["natgeo"], amount=10)`
> ```

@GreatMalboro what's the solution?
