### ISSUE TITLE
Like different pictures of a user's profile

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#484]
> This again has high priority, therefore this will be another **BountyHunt**
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=47972754)](https://www.bountysource.com/issues/47972754-like-different-pictures-of-a-user-s-profile?utm_source=47972754&utm_medium=shield&utm_campaign=ISSUE_BADGE)

### Single use 
*Key to this feature* is that it includes all the `.set_...` calls, therefore it will interact with different pictures of given users but still make sure that nothin inappropriate is liked or commented. (e.g exclude friends, filter for keywords, etc.)

```python
# this will move to the given users profiles and 
# randomly like 10 of his posts taking into account
# restrictions set and e.g. the comment ratio
.like_by_users(['natgeo', 'geo'], amount=10, random=True)
```

### Combined use
In addition to that, we need to extend the `.follow_user_followers` and `.follow_user_following` with a new parameter called `interact` => `.follow_user_followers(..., interact=True)`.
This will, for every user in the list of followers, move to their profile and like the given amount of pictures (also taking into account settings like the `comment`-rate).
To make sure the method call won't get too big, we will introduce a new `.set_...` method which will work as a setup for the `.follow_user_followers` interaction.

> Take into account, that this could also be interesting to be used with e.g. the `.like_by_tag(...)` feature <= make it easily integrateable with the other `.like_by_...` methods

```python
.set_user_interact(percentage=10, amount=10, random=True)
# percentage defaults to 100 so you could also do
.set_user_interact(amount=10, random=True)
```

this will give us the opportunity to do something like this:

```python
# For 10%  of the 20 randomly selected users (~2 users), move to their profile
# and randomly choose 10 pictures to be liked. 
# Take into account the other set options like the comment rate
# and the filtering for inappropriate words or users
.set_user_interact(percentage=10, amount=10, random=True)
.follow_user_follower(['natgeo', 'geo'], amount=20, random=True, interact=True)
```

**DoD**:
- There is a example given in the examples file
- There is documentation added in the README
- I can extend my session with the `.like_by_users()` method
- I can set up my session with the information for the `.follow_user_follower()/following()`
- Both features include the restrictions and settings set up before calling the method (including e.g. comment-ratio and like restrictions)

> **Note:** This Feature is open for improvements and *better* ideas and implementations. The outlines given here only state the wanted features. If you have a cleaner and nicer idea, feel free to state it here and discuss it.
Also if you have some more ideas on what parameters could be used when liking some pictures of a given user, feel free to provide your ideas as comments.

**If there are any question, feel free to ask here, I'd be happy to clarify any wrongly described requirements**

**Comment by timgrossmann** [comment]
@BernardoGO @ahmadudin 😉

**Comment by BernardoGO** [comment]
@timgrossmann I'll take it.

**Comment by timgrossmann** [comment]
#492
