### ISSUE TITLE
user is inaccessible

### ISSUE THREAD

**Issue by skinner12** [InstaPy/InstaPy#4840]
## Current Behavior

When InstaPY find a user to follow, it always show this warning:
    ` --> Couldn't follow 'mr._parker._'!      ~user is inaccessible`

## InstaPy configuration

I'm using `stylish_unfollow_tips_and_like_by_tags.py`, I've changed only tags and username and password.

**Comment by ghost** [comment]
I have the same problem

**Comment by ghost** [comment]
same

**Comment by SadArmadillo** [comment]
same here it goes constantly "user is inaccessible" for following function after 0.6.1 update

**Comment by KeenonT** [comment]
downgrade to 0.6.0. if it works there, might need to stick with that build until the bug in the latest version with that is worked out

**Comment by ghost** [comment]
downgraded, same result

**Comment by GitNees** [comment]
Yeah, same on 0.6.1 and 0.6.0, hope a fix will come soon. Really looks broken now since the big change.

**Comment by SeRealMF** [comment]
Same here :(

**Comment by ozzysahin** [comment]
Same problem

**Comment by KeenonT** [comment]
https://github.com/timgrossmann/InstaPy/pull/4858

**Comment by skinner12** [comment]
Even with new update, I have the same problem

EDIT: I don't know why pip didn't update Instapy, now that I checked the right version this fix seems to work.
