### ISSUE TITLE
Digital Ocean nano 

### ISSUE THREAD

**Issue by beld159** [InstaPy/InstaPy#4847]
I have gotten all the way through the installation and steps for Digital Ocean, and when I get to this point after the install, and type in "nano qii" I get a blank black screen. Help?
<img width="672" alt="Screen Shot 2019-08-13 at 2 47 15 PM" src="https://user-images.githubusercontent.com/50464617/62976416-c4463880-bdd9-11e9-837e-d9be620f2fae.png">

**Comment by Josexv1** [comment]
Read nano [documentation](https://www.nano-editor.org/docs.php) using `nano somefile.ext` will create a new file if it doesn't exist.

The file `qii` doesn't exist, so it will create a blank file. the correct usage is `nano quickstart.py`
