### ISSUE TITLE
Improve the .like_by_feed feature

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#485]
> This is some minor improvement, but will help a lot of people with their followings.
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=47972974)](https://www.bountysource.com/issues/47972974-improve-the-like_by_feed-feature?utm_source=47972974&utm_medium=shield&utm_campaign=ISSUE_BADGE)

This one should be quite simple.
Reimplement the `.like_by_feed` feature so that it not only *stupidly* likes the pictures on the feed page, but actually **takes into account all the settings** like the commenting and like-restrictions as well as the clarifai image checking. 
Also add some randomisation to provide the possibility to not like every single picture.

One nice little enhancement would also be to add an `unfollow` on inappropriate content.
So e.g. a user posts something I declared as inappropriate, the bot would then **automatically 
unfollow this account.**

> A nice little "take into account" here would be to implement it in a way that the soon to come feature #484 could be added easily with a `interact=True` parameter.

could look something like this:

```python
# This will like 100 posts, taking into account my settings
# of commenting, like restrictions etc...
# Randomly select the posts to be liked
# and if it comes across some posts I declared as inappropriate
# it will automatically unfollow given user
 .like_by_feed(amount=100, random=True, unfollow=True)

# random=False would mean we simply go top-down
```

**DoD**:
- There is an example in the example file for this feature
- There is documentation given in the README
- I can simply add this to my InstaPy session after my settings
- It takes into account the settings like commenting, like restriction etc...
- I can set a random flag to make sure it won't like every single post on my feed
- I can set a flag to make the bot automatically unfollow accounts that post inappropriate stuff

> **Note:** If you have any ideas to make this feature better, feel free to post them as comments here.

**Comment by vitormvasc** [comment]
I'm working on it.

**Comment by timgrossmann** [comment]
#495
