### ISSUE TITLE
Please, Write your limit to not be banned, best pratice

### ISSUE THREAD

**Issue by gerfra** [InstaPy/InstaPy#4853]
## Expected Behavior
I found four non exhaustive threads, would you like to create a more detailed statistic? What techniques should be used to avoid ban?
Example: 
comment limit
like limit
etc....
Tricks:
delay script....
VPN....

Thx
This because I would like to know the limits of a campaign.

**Comment by ShubhamBhatt** [comment]
hi i am facing this probelm i am a noob
Traceback (most recent call last):
  File "C:\Users\Jalebee\Desktop\nepi\instapy-quickstart-master\quickstart_templates\good_commenting_strategy_and_new_qs_system.py", line 89, in <module>
    session.like_by_tags(my_hashtags, amount=60, media=None)
  File "C:\Users\Jalebee\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\instapy.py", line 1939, in like_by_tags
    liked_img,
  File "C:\Users\Jalebee\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\like_util.py", line 726, in like_image
    if quota_supervisor("likes") == "jump":
  File "C:\Users\Jalebee\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\quota_supervisor.py", line 41, in quota_supervisor
    quota_state = controller(job)
  File "C:\Users\Jalebee\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\quota_supervisor.py", line 59, in controller
    supervise, interval, target = inspector(job, peaks)
  File "C:\Users\Jalebee\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\quota_supervisor.py", line 118, in inspector
    if hourly_record >= hourly_peak:
TypeError: '>=' not supported between instances of 'int' and 'tuple'

**Comment by GaWr26** [comment]
This is what my script did yesterday running at home from my residential IP.
I have random delays up to half an hour between each new operation.


Created: Day | Follows | Un Follows | Likes | Comments | Server Calls
-- | -- | -- | -- | -- | --
13 August, 2019 | 106 | 5 | 64 | 0 | 1497

```
session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments", "follows", "server_calls"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes_hourly=30,
                              peak_likes_daily=250,
                              peak_comments_hourly=5,
                              peak_comments_daily=10,
                              peak_follows_hourly=30,
                              peak_follows_daily=150,
                              peak_unfollows_hourly=50,
                              peak_unfollows_daily=600,
                              peak_server_calls_hourly=200,
                              peak_server_calls_daily=2500)
```
Quotas catch on the hourly limits

 Gained 25 new followers and no blocks. I have two other accounts which I've been running in Jarvee for a while and these get instant blocks with same settings. I believe I have to wait at least a week to get them going again.

**Comment by gerfra** [comment]
> This is what my script did yesterday running at home from my residential IP.
> I have random delays up to half an hour between each new operation.
> 
> Created: Day	Follows	Un Follows	Likes	Comments	Server Calls
> 13 August, 2019	106	5	64	0	1497
> Gained 25 new followers and no blocks. I have two other accounts which I've been running in Jarvee for a while and these get instant blocks with same settings. I believe I have to wait at least a week to get them going again.

Ok, you understand exacltly... a online public Google Sheets... with the function name and limit, time, etc... Thx
PS: 6000 actions four month is the Instagram limit..... it's true?

**Comment by gerfra** [comment]
> TypeError: '>=' not supported between instances of 'int' and 'tuple'

Update python to 37.

**Comment by skinner12** [comment]
If you get blocked, for example to make new likes, is it possible to use Instagram on phone like normale use? Or is it blocked on official app too?

Also, from your experience, does this block desappears after few days?

**Comment by gerfra** [comment]
The sum of the action 4 month is less than 6000 actions!

**Comment by e1x4** [comment]
> session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments", "follows", "server_calls"], sleepyhead=True, stochastic_flow=True, notify_me=True,
>                               peak_likes_hourly=30,
>                               peak_likes_daily=250,
>                               peak_comments_hourly=5,
>                               peak_comments_daily=10,
>                               peak_follows_hourly=30,
>                               peak_follows_daily=150,
>                               peak_unfollows_hourly=50,
>                               peak_unfollows_daily=600,
>                               peak_server_calls_hourly=200,
>                               peak_server_calls_daily=2500)

Can you paste here your quickstart? I'm looking for a script with follow and likes.

**Comment by skinner12** [comment]
> Like 22 or 23 days, after this you are able to interact again. Remember 6000 actions is the limit!

6000 in a month? But for what? 6000 likes to month or server calls?

**Comment by gerfra** [comment]
I did not find an official reference with these declared values, everyone says his opinion, but everyone talks about 6000 cumulative actions.
for this reason I opened this discussion to collect data. Ciao
Ps:I am following a limit of 5500 without problems, and I would like to increase it
