### ISSUE TITLE
POPULAR posts being liked, not RECENT -  like_by_tags broken

### ISSUE THREAD

**Issue by GitNees** [InstaPy/InstaPy#4859]
## Expected Behavior
Like recent posts, not top posts
## Current Behavior
Likes posts from POPULAR, not recent tab

Manual still says it will skip 9 TOP posts by default, also that is broken, instagram also loads more then 9 at POPULAR tab.
This ofcourse also breaks interaction, because you never like new posts and keep loading liked images that will stay there for hours or a day?

**Comment by GitNees** [comment]
Ah now it makes sense, we are now using mobile agent, this is different from the normal agent. 
Not sure how to fix that, except disable the mobile agent temporary, but also cannot find how to do that.

**Comment by GitNees** [comment]
Ok so I tested some more.

Check your phone, search a tag, start scrolling, it will continu loading pics and those are the ones liked, not the recent ones.

The other that load from the Popular tab, are not show in the browser, but will get likes and not start at all with the recent ones.

**Comment by jamezun** [comment]
I indeed have the same problem, i thought they will start like the recent posts after the 9 posts... this problem need to be solved...

**Comment by GitNees** [comment]
Anyone got an idea? Tried to play with xpath, but cant get it to work.

**Comment by GitNees** [comment]
Seems noone else has this problem? Or noone really noticed it. But its a main feature that really brakes the interaction.

**Comment by prototype127** [comment]
@GitNees hey, how can i use those documents of instapy ... where i have to copy and paste those small scripts ?? suppose i have to do comments by hashtags can i do it ? iam noob plz help !!!
