### ISSUE TITLE
latest update is the quota_supervisor not working anymore 

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#4861]
Since today, (latest update is the quota_supervisor not working anymore for me, anyone else?

## Current Behavior
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-14 16:49:01] [xxxxx]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "InstaPy/xxxxxxx.py", line 34, in <module>
    peak_server_calls=(None, 4700))
TypeError: set_quota_supervisor() got an unexpected keyword argument 'peak_likes'
No Sockets found in /run/screen/S-xxxxxx.

## InstaPy configuration
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(10, 300),
                              peak_comments=(10, 200),
                              peak_follows=(4, 50),
                              peak_unfollows=(20, 200),
                              peak_server_calls=(None, 4700))

**Comment by ghost** [comment]
there are changes in new version of instapy. 
Read the docs.
https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#quota-supervisor

**Comment by Tr1pke** [comment]
Thanks
