### ISSUE TITLE
crashing at session.like_by_tags(amount=10, use_smart_hashtags=True)

### ISSUE THREAD

**Issue by omerbadawy11** [InstaPy/InstaPy#4866]
## Expected Behavior
to like images based on smart tags?
## Current Behavior
Traceback (most recent call last):
  File "D:\InstaPy-0.6.1\InstaPy-0.6.1\instapy\util.py", line 1061, in get_relationship_counts
    "return window._sharedData.entry_data."
  File "C:\Users\Omer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Omer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Omer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window._sharedData.entry_data.ProfilePage[0].graphql is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 66, in <module>
    session.like_by_tags(amount=10, use_smart_hashtags=True)
  File "D:\InstaPy-0.6.1\InstaPy-0.6.1\instapy\instapy.py", line 1924, in like_by_tags
    validation, details = self.validate_user_call(user_name)
  File "D:\InstaPy-0.6.1\InstaPy-0.6.1\instapy\instapy.py", line 1313, in validate_user_call
    self.logfolder,
  File "D:\InstaPy-0.6.1\InstaPy-0.6.1\instapy\util.py", line 207, in validate_username
    browser, username, logger
  File "D:\InstaPy-0.6.1\InstaPy-0.6.1\instapy\util.py", line 1069, in get_relationship_counts
    str(read_xpath(get_relationship_counts.__name__, "followers_count"))
  File "D:\InstaPy-0.6.1\InstaPy-0.6.1\instapy\util.py", line 1002, in format_number
    formatted_num = number.replace(",", "")
AttributeError: 'FirefoxWebElement' object has no attribute 'replace'
## InstaPy configuration

```
import random
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'fgfg  # <- enter username here
insta_password = 'gfgf'  # <- enter password here

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username='fgfg', 
                 password='gfgf', 
                 headless_browser=False)

# let's go! :>
with smart_run(session):
    # general settings
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes_hourly=57,
                              peak_likes_daily=585,
                               peak_comments_hourly=21,
                               peak_comments_daily=182,
                                peak_follows_hourly=48,
                                peak_follows_daily=None,
                                 peak_unfollows_hourly=35,
                                 peak_unfollows_daily=402,
                                  peak_server_calls_hourly=None,
                                  peak_server_calls_daily=4700)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=-1.3,
                                    delimit_by_numbers=True,
                                    max_followers=10000,
                                    max_following=15000,
                                    min_followers=75,
                                    min_following=75)
    session.set_do_comment(True, percentage=10)
    session.set_comments([u'Nice :laughing: ', 'Lol'])
    session.set_use_clarifai(enabled=False, api_key='')
    session.clarifai_check_img_for(
        ['nsfw', 'gay', 'hijab', 'niqab', 'religion', 'shirtless', 'fitness',
         'yamaka', 'rightwing'], comment=False)
    session.set_dont_like(
        ['dick', 'squirt', 'gay', 'homo', '#fit', '#fitfam', '#fittips',
         '#abs', '#kids', '#children', '#child',
         '[nazi',
         'jew', 'judaism', '[muslim', '[islam', 'bangladesh', '[hijab',
         '[niqab', '[farright', '[rightwing',
         '#conservative', 'death', 'racist'])
    session.set_do_follow(enabled=True, percentage=25, times=2)

    # like by tags activity
	
    #session.set_smart_hashtags(
    #    ['memes'],
    #    limit=10, sort='random', log_tags=True)
    #session.set_dont_like(['promoter', 'nightclub'])
    #session.set_delimit_liking(enabled=True, max_likes=1005, min_likes=20)
    #session.like_by_tags(amount=12, use_smart_hashtags=True)

    # interact user followers activity
    session.set_user_interact(amount=5, randomize=True, percentage=50,
                              media='Photo')
    session.set_do_follow(enabled=True, percentage=70)
    session.set_do_like(enabled=True, percentage=70)
    session.set_comments(['uNice :laughing: ', 'Lol', 'Lmao', 'u:laughing: :laughing: ',
			'u:open_mouth:'])
    session.set_do_comment(enabled=True, percentage=30)
    session.interact_user_followers([''], amount=random.randint(1, 10),
                                    randomize=True)

    # unfollow activity
    session.set_dont_unfollow_active_users(enabled=True, posts=3)
    session.unfollow_users(amount=random.randint(30, 100),
                           InstapyFollowed=(True, "all"), style="FIFO",
                           unfollow_after=90 * 60 * 60, sleep_delay=501)

    """ Joining Engagement Pods...
    """
    session.join_pods(topic='funny')
```

**Comment by brnskn** [comment]
same issue +1

**Comment by brnskn** [comment]
I guess graphql javascript functions don't work anymore, and xpaths are not correct. Can you check it out? @timgrossmann @converge

**Comment by omerbadawy11** [comment]
im still having this issue+

**Comment by wildwilly18** [comment]
Is there no solution to this issue?
