### ISSUE TITLE
my acount action blocked too while  I did used version Instapy 0.6.1version 

### ISSUE THREAD

**Issue by KMLnk** [InstaPy/InstaPy#4867]

**Comment by KMLnk** [comment]
Isn't this a problem to be solved?

**Comment by Josexv1** [comment]
You didn't provide any info about your issue, you've been blocked, but what are your limits, or the usage of InstaPy? Provide more info, and if it's a problem with the software then it's an issue, if it's just you using it wrong then it's not an issue.

**Comment by KMLnk** [comment]
> You didn't provide any info about your issue, you've been blocked, but what are your limits, or the usage of InstaPy? Provide more info, and if it's a problem with the software then it's an issue, if it's just you using it wrong then it's not an issue.

When I run the robot with the following settings it will be blocked:
It seems that Instagram servers estimate the behavior of the robot as inhumane  and block account activity
I use IPs that are not blacklisted on Instagram servers, and I spot the number of robot activities to be less than 500 per day.
Why is Instagram blocking my account?

`

with smart_run(session):

    session.set_relationship_bounds(enabled=False, delimit_by_numbers=False)
    session.set_skip_users(skip_private=False)
    session.set_action_delays(enabled=True, like = 40, comment = 80, follow = 3*60, unfollow = 3*60, story=10)
    session.set_user_interact(amount=1, randomize=True, percentage=100, media='Photo')
    session.set_do_follow(enabled=True, percentage=50)
    session.set_do_like(enabled=True, percentage=100)
    session.set_comments([u'like',
                          u'very good',
                          u'beutifull',
                          u'nice',
                          u'good'])
    session.set_do_comment(enabled=True, percentage=50)
    session.interact_user_followers(['worldbtob'], amount=10, randomize=False)
    session.unfollow_users(amount=5, nonFollowers=True, style="RANDOM", unfollow_after=48*60*60, sleep_delay=655)
    session.like_by_feed(amount=700, randomize=False, unfollow=False, interact=False)

    print('------------------')
    print('Finished.')
    while True:
        time.sleep(10)

`

**Comment by e1x4** [comment]
for me the same, today after 7 follow, sleep for 28 minutes, and then for the next follows I got the action blocked, but in my instagram app with the smartphone I can follow without any block...

**Comment by KMLnk** [comment]
> for me the same, today after 7 follow, sleep for 28 minutes, and then for the next follows I got the action blocked, but in my instagram app with the smartphone I can follow without any block...

that's right, I think this is due to a direct link to the target account, while accounts must be searched first.
Using direct links to get to the target page is not a human behavior

**Comment by erekhshe** [comment]
I have same issue, I guess, the Instagram can easily detect the instapy pattern, The Instapy does its jobs with direct profile's links that can be detected by a simple referral link check. a simple solution would be, the Instapy search the usernames in the Instagram search box and click on found user to bypass referral link check instead of directly open username page.

**Comment by KMLnk** [comment]
> I have same issue, I guess, the Instagram can easily detect the instapy pattern, The Instapy does its jobs with direct profile's links that can be detected by a simple referral link check. a simple solution would be, the Instapy search the usernames in the Instagram search box and click on found user to bypass referral link check instead of directly open username page.

I agree with you

**Comment by e1x4** [comment]
Yes I think you are right, an human behavior would be scrolling followers of a user, check every profile and then follow according to the set parameters.

**Comment by amatadev98** [comment]
1. Stop bot.
2. Reset your password.
3. Use your account normally with IG app for at least a week (two weeks recommended)
4. Login with bot. 
5. Start from only 2 likes and 2 follows a day. Increase it daily, for example:
day 1: 2 follows , 2 likes
day 2: 5 follows, 5 likes
day 3: 10 follows, 10 likes
day 4: 20 follows, 20 likes
stay under 100 follows and 100 likes per day. 
Don't follow and unfollow in the same day.

**Comment by KMLnk** [comment]
> 1. Stop bot.
> 2. Reset your password.
> 3. Use your account normally with IG app for at least a week (two weeks recommended)
> 4. Login with bot.
> 5. Start from only 2 likes and 2 follows a day. Increase it daily, for example:
>    day 1: 2 follows , 2 likes
>    day 2: 5 follows, 5 likes
>    day 3: 10 follows, 10 likes
>    day 4: 20 follows, 20 likes
>    stay under 100 follows and 100 likes per day.
>    Don't follow and unfollow in the same day.

It's not a robot
100 interaction can be done manually

**Comment by amatadev98** [comment]
> > 1. Stop bot.
> > 2. Reset your password.
> > 3. Use your account normally with IG app for at least a week (two weeks recommended)
> > 4. Login with bot.
> > 5. Start from only 2 likes and 2 follows a day. Increase it daily, for example:
> >    day 1: 2 follows , 2 likes
> >    day 2: 5 follows, 5 likes
> >    day 3: 10 follows, 10 likes
> >    day 4: 20 follows, 20 likes
> >    stay under 100 follows and 100 likes per day.
> >    Don't follow and unfollow in the same day.
> 
> It's not a robot
> 100 interaction can be done manually

That 800 follows/likes per days are gone. 100 or 200 follow/like per day is safe and it's not that easy to do it manually everyday, especially if you have multiple accounts.

**Comment by KMLnk** [comment]
> > > 1. Stop bot.
> > > 2. Reset your password.
> > > 3. Use your account normally with IG app for at least a week (two weeks recommended)
> > > 4. Login with bot.
> > > 5. Start from only 2 likes and 2 follows a day. Increase it daily, for example:
> > >    day 1: 2 follows , 2 likes
> > >    day 2: 5 follows, 5 likes
> > >    day 3: 10 follows, 10 likes
> > >    day 4: 20 follows, 20 likes
> > >    stay under 100 follows and 100 likes per day.
> > >    Don't follow and unfollow in the same day.
> > 
> > 
> > It's not a robot
> > 100 interaction can be done manually
> 
> That 800 follows/likes per days are gone. 100 or 200 follow/like per day is safe and it's not that easy to do it manually everyday, especially if you have multiple accounts.

thanks man but I think change bot behavior it will be so better than now

**Comment by masto182** [comment]
I'm getting this as well.  I mainly use the follow_user_followers action
