### ISSUE TITLE
How can i use chrome with newest update?

### ISSUE THREAD

**Issue by leo1in88** [InstaPy/InstaPy#4871]
Newest update got error with firefox. How i can i back to use chrome with newest update. So i can use chrome and still have newest features. Dont want to downgrade it.

**Comment by Flaunkerton2395** [comment]
I've had trouble storing cookies with my current Chrome setup. I have Chrome 76 and Chromedriver 2.4.6

**Comment by KeenonT** [comment]
newest update doesn't use chrome. you'll have to downgrade to the ones that did or figure out your firefox errors

**Comment by mwargan** [comment]
> newest update doesn't use chrome. you'll have to downgrade to the ones that did or figure out your firefox errors

Beware to all those that do - the x-paths are changing constantly and I've found previous versions now unreliable as the Instagram UI has changed.
