### ISSUE TITLE
Proxy does not work Ubuntu Firefox

### ISSUE THREAD

**Issue by DrPeryCox** [InstaPy/InstaPy#4872]
Private Proxy doesn't work with firefox at all. I tried few scripts and settings of InstaPy was like in the documentation, but this did not work. So far I just every time get error with this message:
"Proxy Authentication is not working anymore due to the Selenium bug report: https://github.com/SeleniumHQ/selenium/issues/7239"
How I can switch to Chrome browser? 
I am using Ubuntu 18.04.

**Comment by cutzenfriend** [comment]
Same issue here! I also need a private proxy :(

**Comment by DrPeryCox** [comment]
Do anyone have some updates?
