### ISSUE TITLE
Problems with Chromedriver/Selenium

### ISSUE THREAD

**Issue by Flaunkerton2395** [InstaPy/InstaPy#4874]
## Expected Behavior
Work correctly
## Current Behavior
I recently updated Instapy and Chrome but every time I start a session, Instapy says there is a problem with my cookie and I have to enter in a security code.

Cookie file not found, creating cookie...
Issue with cookie for user ***. Creating new cookie...

The cookie file is created and modified but still not used. I have tried deleting the file to start from scratch but it is the same issue with the cookie every time. The sessions will also randomly end and Instapy has stopped reporting statistics at the end as it usually does. I have Chrome 76, Chromedriver 2.4.6 and current version of Instapy as well on Mac. 

Also strangely when the session begins, there is a line in Chrome that says my version is out of date even though when I click 'About Chrome', it says the version is 76 and is up to date.
## InstaPy configuration

Traceback (most recent call last):
This is the latest log that is printed when the session randomly ends:

  File "/Users/**/Downloads/instapy-quickstart-master/quickstart_templates/Like_Comment_By_TagSP11.py", line 51, in <module>
    amount=20, skip_top_posts=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/instapy.py", line 1847, in like_by_tags
    liked_img)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/like_util.py", line 707, in like_image
    like_elem = browser.find_elements_by_xpath(like_xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 410, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: unable to send message to renderer
  (Session info: chrome=76.0.3809.100)

**Comment by KeenonT** [comment]
chrome support has been discontinued. download the latest firefox

**Comment by papillon-unix** [comment]
@intellem0s yes but I guess you noticed we are many to get this "selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities" error when updating to the latest version.. Still no idea how to fix it?

**Comment by posittron** [comment]
> @intellem0s yes but I guess you noticed we are many to get this "selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities" error when updating to the latest version.. Still no idea how to fix it?

I got that too I guess I did git pull origin master and pip install instapy -U and those two fixed it

**Comment by papillon-unix** [comment]
@posittron I'm so confused, I've just done the same as you and I still get the same error

```
Traceback (most recent call last):
  File "Projects/instagram/instajoseph.py", line 13, in <module>
    disable_image_load=True)
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/instapy.py", line 318, in __init__
    self.logger,
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```
I lose hope

**Comment by posittron** [comment]
> @posittron I'm so confused, I've just done the same as you and I still get the same error
> Traceback (most recent call last):
>   File "Projects/instagram/instajoseph.py", line 13, in <module>
>     disable_image_load=True)
>   File "/home/joseph/.local/lib/python3.5/site-packages/instapy/instapy.py", line 318, in __init__
>     self.logger,
>   File "/home/joseph/.local/lib/python3.5/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
>     options=firefox_options,
>   File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
>     keep_alive=True)
>   File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
> 
> I lose hope

Try this, download geckodriver from the mozilla site and place it in the instapy master directory and also in local/programs/python/python(yourpythonversion)

**Comment by papillon-unix** [comment]
@posittron thank you very much for your help.
Assuming that on a Raspberry, the instapy master directory is for me `/home/joseph/Instapy/` and the python directory is `/usr/lib/python3.5/`: I just tried and it seems things are moving because I get a new error:

```
Workspace in use: "/home/joseph/InstaPy"
Traceback (most recent call last):
  File "Projects/instagram/instajoseph.py", line 13, in <module>
    disable_image_load=True)
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/instapy.py", line 318, in __init__
    self.logger,
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
```

**Comment by posittron** [comment]
> @posittron thank you very much for your help.
> Assuming that on a Raspberry, the instapy master directory is for me /home/joseph/Instapy/ and the python directory is /usr/lib/python3.5/: I just tried and it seems things are moving because I get a new error:
> Workspace in use: "/home/joseph/InstaPy"
> Traceback (most recent call last):
>   File "Projects/instagram/instajoseph.py", line 13, in <module>
>     disable_image_load=True)
>   File "/home/joseph/.local/lib/python3.5/site-packages/instapy/instapy.py", line 318, in __init__
>     self.logger,
>   File "/home/joseph/.local/lib/python3.5/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
>     options=firefox_options,
>   File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
>     self.service.start()
>   File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 76, in start
>     stdin=PIPE)
>   File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
>     raise child_exception_type(errno_num, err_msg)
> OSError: [Errno 8] Exec format error

Great, you're right, things are moving. This error is something exclusive to raspi and you'll fix it by reinstalling everything using sudo pip3

**Comment by papillon-unix** [comment]
@posittron Well, thanks again for your help, but I still got the same error after re-installing instapy with sudo pip3.
I've search on other posts about this 'Errno 8' issue and one suggest downgrading selenium by `sudo pip3 install selenium==2.53.6` - I tried and it got worst:

```
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/joseph/InstaPy"
Traceback (most recent call last):
  File "Projects/instagram/instajoseph.py", line 16, in <module>
    disable_image_load=True)
  File "/root/.local/lib/python3.5/site-packages/instapy/instapy.py", line 318, in __init__
    self.logger,
  File "/root/.local/lib/python3.5/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
TypeError: __init__() got an unexpected keyword argument 'options'
```

I reinstalled the latest selenium and got back to Errno 8.. :(

**Comment by Flaunkerton2395** [comment]
@posittron What did you command exactly when you say you did git pull origin master? Also are we not supposed to reference pip3 and use pip when installing Instapy?

**Comment by papillon-unix** [comment]
yeah, I'm still getting the same "[Errno 8] Exec format error". I tried everything, I don't understand whats wrong..

**Comment by papillon-unix** [comment]
I re-installed everything following the instapy doc for raspberry. 
Then I copy the geeckodriver in my `InstaPy/` folder as well as in `/usr/bin/python3.5/` and I'm back to the previous error `Unable to find a matching set of capabilities`
I did everything twice : once with sudo, once without.
And I always end up to this same error. I'm diying. Stuck on this since two weeks. What can I do? Is Instapy dead on raspberry?

**Comment by posittron** [comment]
I'm on windows so it's not that bad just the loading is super slow but tell
you what I don't have such a good feeling about using instapy right now so
imma let the devs figure the Firefox only instapy cause that is definitely
the cause for 90% of the problems.

**Comment by vbotics** [comment]
> I re-installed everything following the instapy doc for raspberry.
> Then I copy the geeckodriver in my `InstaPy/` folder as well as in `/usr/bin/python3.5/` and I'm back to the previous error `Unable to find a matching set of capabilities`
> I did everything twice : once with sudo, once without.
> And I always end up to this same error. I'm diying. Stuck on this since two weeks. What can I do? Is Instapy dead on raspberry?

Please let me know if you found a fix for RPi. I am facing the same issue :(

**Comment by papillon-unix** [comment]
@vbotics [4890](https://github.com/timgrossmann/InstaPy/issues/4890#issuecomment-528782908)
