### ISSUE TITLE
Error with extension.xpi

### ISSUE THREAD

**Issue by John9421** [InstaPy/InstaPy#4878]
Hi guys, 

I get the following output:

Traceback (most recent call last):
  File "start.py", line 150, in <module>
    multi_logs=True)
  File "C:\Users\X\AppData\Roaming\Python\Python37\site-packages\instapy\instapy.py", line 330, in __init__
    self.logger,
  File "C:\Users\X\AppData\Roaming\Python\Python37\site-packages\instapy\browser.py", line 132, in set_selenium_local_session
    browser.install_addon(create_firefox_extension(), temporary=True)
  File "C:\Users\X\AppData\Roaming\Python\Python37\site-packages\instapy\browser.py", line 49, in create_firefox_extension
    with zipfile.ZipFile(zip_file, "w", zipfile.ZIP_DEFLATED, False) as zipf:
  File "C:\Users\X\AppData\Local\Continuum\anaconda3\envs\instagram\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\X\\InstaPy\\assets\\extension.xpi'

I tried to uninstall and install InstaPy again, and also I have used different scripts, but I keep getting this problem. Can someone help me? Thank you in advance

**Comment by jonap339** [comment]
The same happens to me!

**Comment by otomay** [comment]
do you fix it out?

**Comment by otomay** [comment]
I'm having that problem when I try to run 2 or more scripts in the same time.

But if a run a ' taskkill -f -im firefox.exe /-t ' and starts a script again, it will work. But only once :/ to run a different script (not at the same time) I have to run a taskkill again.

**Comment by manualvarez** [comment]
Same issue, I reinstal everything again with out succes.

**Comment by tomerBZ** [comment]
Same here

**Comment by NooriP** [comment]
Same here

**Comment by NooriP** [comment]
@tomerBZ  @manualvarez  @otomay @jonap339  @John9421  Did you find a solution ?

**Comment by tomerBZ** [comment]
Using an old version, works like a charm 😂

**Comment by manualvarez** [comment]
which version are you ussing?

**Comment by issamarmas** [comment]
> Using an old version, works like a charm 😂

which version

**Comment by issamarmas** [comment]
i found a solution...  just delete this file C:\Users\X\InstaPy\assets\extension.xpi  

it worked for me :)

**Comment by knezzit** [comment]
> which version are you ussing?

Hey. Same problem with me. Any update?
which version are you using?

**Comment by roberterzen** [comment]
I have the same problem.
I run five scripts and if I want to start a new one and get 
`OSError: [Errno 22] Invalid argument: 'C:\Users\X\InstaPy\assets\extension.xpi'`
I have to stop all five and start over.

**Comment by adamya-singh** [comment]
> > which version are you ussing?
> 
> Hey. Same problem with me. Any update?
> which version are you using?

deleting the extension.xpi file works for me, it is located in c/users/user/instapy/assets/extention.xpi

**Comment by ARUNMOHANRAJ471** [comment]
closing the firefox browser windows and started the application worked for me. :)

**Comment by sherxyar** [comment]
> closing the firefox browser windows and started the application worked for me. :)

And make sure you close it from Task Manager as well.
