### ISSUE TITLE
Quickstart Template Question

### ISSUE THREAD

**Issue by sukesharay** [InstaPy/InstaPy#4879]
Hey guys, I'm new to the Instapy community :)

Is there anyone who can help me with a script that runs safely for 24 hours, 40 likes an hour, and 20 comments an hour? Multiple users and interaction by hashtags as well? I know its simple and I feel like a newb but I would really appreciate it!!

Have an awesome and blessed day!

Sukesha

**Comment by GaWr26** [comment]
Those amounts will quite certainly get you a block very quickly.
I run my scripts once a day and they run for around 6-7 hours with 100 follows and 100 likes. 
This gives me an average of 25 new followers per day.

**Comment by vyctorbrzezowski** [comment]
@GaWr26 would you share your code, without the follow items? 

I want a code that likes every post on a given hashtag and 3 posts of each poster. Is this possible?
