### ISSUE TITLE
Error Workspace in use after update Instapy

### ISSUE THREAD

**Issue by iltonjm** [InstaPy/InstaPy#4881]
Hello, 

Error at 16/08 11am: "Workspace in use"
 after install Instapy version 1.9.2

**Comment by poupkine** [comment]
the same issue. Have you resovled it?

**Comment by poupkine** [comment]
used  quickstart.py file  from newly downloaded InstaPy archive, that problem dissapeared
but appeared new problem witnh geckodriver...
OSError: [Errno 26] Text file busy: '/root/InstaPy/assets/gecko/v0.24.0/geckodriver-v0.24.0-linux64/geckodriver'

**Comment by decoge** [comment]
Installing Firefox solved this problem for me.

**Comment by beld159** [comment]
Same Problem, installing firefox did not work for me. Any suggestions here?

**Comment by hamzasafdar01** [comment]
i have already firefox installed but the same problem appeared to me. Any Solution?
