### ISSUE TITLE
KeyError: 'media'

### ISSUE THREAD

**Issue by mario1105** [InstaPy/InstaPy#4882]
I'm getting this error right before the bot is about to like a post:
`File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 1914, in like_by_tags self.logger, File "/usr/local/lib/python3.6/dist-packages/instapy/like_util.py", line 606, in check_link media = post_page[0]["media"] KeyError: 'media'`

This is the last step it always reaches:

> .................................................................
> INFO [2019-08-16 12:07:55] [accountname]  Logged in successfully!
> '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
> INFO [2019-08-16 12:07:55] [accountname]  Saving account progress...
> INFO [2019-08-16 12:08:00] [accountname]  Location [1/7]
> INFO [2019-08-16 12:08:00] [accountname]  --> b'213385402/london-united-kingdom'
> INFO [2019-08-16 12:08:11] [accountname]  desired amount: 25  |  top posts [disabled]: 9  |  possible posts: 44373096
> INFO [2019-08-16 12:08:18] [accountname]  Like# [1/25]
> INFO [2019-08-16 12:08:18] [accountname]  https://www.instagram.com/p/B1OO9VTHmlO/
>  
> INFO [2019-08-16 12:08:24] [accountname]  Sessional Live Report:
>     |> No any statistics to show
>  
> On session start was FOLLOWING xxx users & had xxx FOLLOWERS
> [Session lasted 1.77 minutes]
>  
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2019-08-16 12:08:24] [accountname]  Session ended!
> oooooooooooooooooooooooooooooooooooooooooooooooooooooooo

If anybody has an idea about what's going on I'll be very grateful

**Comment by Mockapapella** [comment]
I have the same problem, but I've got some sort of idea why this is happening. `post_page` is equal to `[{}]` for some reason. Logs:
```
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-17 12:39:49] [username]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
C:\Users\Quinten\InstaPy\logs\username\relationship_data
INFO [2019-08-17 12:39:49] [username]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-08-17 12:39:49] [username]  - Internet Connection Status: ok
INFO [2019-08-17 12:39:49] [username]  - Current IP is "X.X.X.X" and it's from "United States/US"
INFO [2019-08-17 12:39:49] [username]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-08-17 12:39:55] [username]  - Instagram WebSite Status: Currently Up 
INFO [2019-08-17 12:39:55] [username]  - Instagram Response Time: 112.239 ms 
INFO [2019-08-17 12:39:55] [username]  - Instagram Reponse Code: 200
INFO [2019-08-17 12:39:55] [username]  - Instagram Server Status: ok
INFO [2019-08-17 12:39:55] [username]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-08-17 12:39:55] [username]  - window.navigator.webdriver response: False
INFO [2019-08-17 12:39:55] [username]  - Hide Selenium Extension: ok
```
The second to last line, `window.navigator.webdriver response: False` is what's causing issues I think. If I had to guess, there was a change in how the json parser works which results `post_page` being set to what it is. What's odd though, is that `post_page` is supposed to [return](https://github.com/timgrossmann/InstaPy/blob/dev/instapy/like_util.py#L570) when it is set to `None`, so I don't know why there is an error being thrown beyond that point.

**Comment by Mockapapella** [comment]
OK, so after further inspection, when viewing the source code for a post I was monitoring, the `post_page` element of the json file actually equals `[{}]`...I have no idea where to go from here.

**Comment by mario1105** [comment]
Thanks for the hints. I'm still trying to fix it but nothing yet...

**Comment by aiktubaiktu** [comment]
Same issue.

**Comment by beatdeddeer** [comment]
I have the same problem.

**Comment by flug** [comment]
same problem

**Comment by yapizza** [comment]
I have the same problem

**Comment by enilsen16** [comment]
After a little investigation (and I'm not familiar with what the old format was) it looks like `window._sharedData.entry_data` was removed in favor of `window.__additionalData`.

**Comment by enilsen16** [comment]
Similar to https://github.com/timgrossmann/InstaPy/pull/4892 it looks like some references need to be updated.

Specifically something like this: https://github.com/timgrossmann/InstaPy/pull/4892/files#diff-870c589a51f82fb50caf6a78df9e4273R1576

**Comment by enilsen16** [comment]
I created #4918 to close this issue

**Comment by santiagosantamaria** [comment]
Im having the same issue on mac 
* Using built in instapy-chromedriver executable (version 2.44) *

**Comment by regeyang** [comment]
same problem

**Comment by florianvazelle** [comment]
I had the same problem, make sure to use `pip3` and `python3`

**Comment by santiagosantamaria** [comment]
Hi, I re-installed everything and it worked (it's working with firefox now anyway)
I always used pip3 and python3. Cheers!

**Comment by Knrd2** [comment]
@santiagosantamaria i re-installed instapy (Version 0.5.8) as well, but its still not working with the same error (KeyError: 'media') and its not using firefox.. can you please post the steps you've done to use firefox? Gracias

**Comment by griffink3** [comment]
same problem with chrome
