### ISSUE TITLE
Sleep delay in script.

### ISSUE THREAD

**Issue by SeRealMF** [InstaPy/InstaPy#4883]
## My Script:
![Screenshot from 2019-08-16 16-159-03](https://user-images.githubusercontent.com/54042386/63182182-3b860180-c052-11e9-8324-38da26be40fe.png)

## What I want to do:
I would like to insert a sleep_delay option for **liking, commenting and following**, but unfortunately the parameter sleep_delay=xxx does not work in the session.interact_user_followers function (or any other function shown in the picture).

## Question:
Does anybody of you know the solution to my problem?
I would be so glad if anybody could help me.

## PS:
I am a beginner. Please respect that.

**Comment by GitNees** [comment]
Everything 100% what you "look" at is just asking for trouble. It screems BOT!
As for delay, might be broken in latest versions, not sure.

**Comment by Flaunkerton2395** [comment]
I had this function working in 0.6.1 but it looks like the 'random_range' variable no longer can work:

session.set_action_delays(enabled=True, like=5, randomize=True, random_range=(100, 180))

**Comment by riccardovalente** [comment]
It's not broken. You need to read the documentation
```
    session.set_action_delays(enabled=True, 
                    like = 7, 
                    comment = 10,
                    follow = 10,
                    unfollow = 30,
                    story = 20,
                    randomize=True, random_range_from=None, random_range_to=150)
```

**Comment by SeRealMF** [comment]
Thank you. What does the number stand for? A delay after 7 likes or 10 comments (etc.)?
