### ISSUE TITLE
Feature request / Idea - Human mode

### ISSUE THREAD

**Issue by jeffreylm** [InstaPy/InstaPy#489]
What if you let the bot run in a mode named human mode.

What the mode would intale is that Instapy would look at the list of todo's and randomize or packed a series of actions.

So for instance when I go on instagram I visit an acount then it read the post, like it then read peoples comments, then like certain comments then follow fome people and visit other post and so on.

The feature would basically go to different given accounts and execute the todo list in this humaly fashion until it's quota is met.

Do bear in mind this idea just came to me, but you get the picture. There is naturally some processes that must always happen before other processes, but that is where good programmers well be able to shine.
The bot will look like a highly active users.

**The attributes that can be given is:** 

- Work tag oriented
- Work user oriented
- Work tag oreinred in discover mode ( It first finds a post via a tag, then goes to the users account, then likes a few post from the user, then looks for active comments likes those, follows a few in the list who liked, then buries down into this list.) An attribute of how deep to bury can also be set.

**Work tag oreinred in discover mode** - good mode  for instance you find an artist (Beyonce) you are trowing a pop festival so you focus on her followers and a certain circl of interest of her follows, becasue her followers are birds of a feather flock together. Then the scrip comes back up to beyonce level and buries back down into the next user. This is the discovery mode.

**Comment by mathmorrison** [comment]
Cool
