### ISSUE TITLE
dead on raspberry ?

### ISSUE THREAD

**Issue by papillon-unix** [InstaPy/InstaPy#4890]
Hello everyone
I tried everything to run the last version of Instapy on a Raspberry Pi-2, I've been following all topics about it, tried ton install, re-install, copy and copy again the geekodriver everything it could be needed, I'm really thankfull to all people who tried to help, but yet, I still end up to the same errors. Either it's `Unable to find a matching set of capabilities` or `[Errno 8] Exec format error`.
May I ask if someone can tell me step by step how to delete everything (firefox, python, instapy, driver, etc) and re-install the good way..?
Thank you very much, I'm stuck to this since days.

**Comment by Mr-HaleYa** [comment]
same problem....

**Comment by riccardovalente** [comment]
Not at all - it does work, and if broken it can be made to work. Not sure about the Pi-2, but it works just fine on my Pi 3B+.

The `matching set of capabilities` error means that the installed version of Firefox is incompatible with the geckodriver, or Firefox is not installed at all.

The `exec format error` means you're using a geckodriver binary which was not compiled for the ARM processor.

so first of all make sure that Firefox is installed with `sudo apt-get install firefox-esr`.

Then remove the installed version of geckodriver, and download the correct version from here: https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-arm7hf.tar.gz.

Unpack it with tar `zxvf geckodriver-v0.23.0-arm7hf.tar.gz` and put the binary in /usr/bin or /usr/local/bin:

sudo /bin/cp geckodriver /usr/bin
sudo chmod 755 /usr/bin/geckodriver.

**Comment by papillon-unix** [comment]
@riccardovalente 
I must be doing something wrong, and be the most unlucky raspberry user, because it still doesn't work for me.

Firefox is correctly installed:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
firefox-esr is already the newest version (52.9.0esr-1~deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```

```
wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-arm7hf.tar.gz
sudo cp geckodriver /usr/local/bin
sudo chmod 755 /usr/local/bin/geckodriver
```

I started by `Error 8` and after doing what you've said I got back to `matching set of capabilities` error.

```
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/joseph/InstaPy"
Traceback (most recent call last):
  File "Projects/instagram/instajoseph.py", line 15, in <module>
    geckodriver_path='/usr/local/bin/geckodriver')
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/instapy.py", line 318, in __init__
    self.logger,
  File "/home/joseph/.local/lib/python3.5/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/joseph/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

Where am I wrong?

**Comment by riccardovalente** [comment]
What O/S are you running on the Pi? I have a much newer version of firefox:

$ apt show firefox-esr
Package: firefox-esr
Version: 60.8.0esr-1~deb10u1+rpi1
Priority: optional

I have little time today, but I will pick this up this evening (GMT)

**Comment by papillon-unix** [comment]
@riccardovalente thank you very much for your time
I'm running Raspian 9.9

```
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
```

And yes, not the same firefox as you apparantly 

```
Package: firefox-esr
Version: 52.9.0esr-1~deb9u1
Priority: optional
```

**Comment by GaWr26** [comment]
try adding the path to the geckodriver in the contructor:

`geckodriver_path="assets/geckodriver"`

**Comment by papillon-unix** [comment]
@GaWr26 I did it already, and just tried again: still `Unable to find a matching set of capabilities`

**Comment by papillon-unix** [comment]
@riccardovalente any idea?

**Comment by papillon-unix** [comment]
Guys, I moved from raspberry pi 2 to pi 3. I re-installed everything, geckodriver included after I got an Error 8 again, and now I get this:

```
InstaPy Version: 0.6.2
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "Bots/instagram/instajoseph_light.py", line 14, in <module>
    geckodriver_path="/usr/local/bin/geckodriver")
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 321, in __init__
    self.logger,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```

**Comment by mwargan** [comment]
Recieving the same error on InstaPy Version: 0.6.3 (as described just above me: https://github.com/timgrossmann/InstaPy/issues/4890#issuecomment-525943112). Upon looking at the gecko logs, here's what I found:
```
1567472292087   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "-headless" "-foreground" "-n$
*** You are running in headless mode.
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
```

When not in headless:
```
1567472206293   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-$
Error: no DISPLAY environment variable specified
```

Specifying the display in the CLI via `export DISPLAY=:0.0` changed nothing :/.

**Comment by papillon-unix** [comment]
@mwargan For me it worked with `export DISPLAY=:0.0` but I had to move before from Raspberry Pi 2 to Pi 3 and run Raspbian Buster with desktop.

**Comment by mwargan** [comment]
@papillon-unix I've done the same just not running with desktop, rather booting directly into CLI. Do you think I need to run Desktop and not headless? Never had issues with Chrome before...

**Comment by papillon-unix** [comment]
I don't know what `rather booting directly into CLI` actually means, but I'm sure you should run it with desktop.
Also, Chrome is not used anymore, Instapy runs with firefox only now.

**Comment by mwargan** [comment]
@papillon-unix in your raspi-config you can choose to boot into the CLI and not load any GUI (desktop) at all - especially useful if you have no GUI to begin with like a Lite version of the official OS :P https://thepihut.com/blogs/raspberry-pi-tutorials/boot-to-command-line-raspbian-jessie and https://www.digikey.com/en/maker/blogs/2018/how-to-boot-to-command-line-and-ssh-on-raspberry-pi

You would do this often to conserve memory/ram on the Pi, especially if you don't actually need a graphical interface (as is my case cause I have no screen).

Ugh with Chrome everything was fine... still don't get why it was removed...

**Comment by papillon-unix** [comment]
@mwargan yes, but it can't work this way, how would you run firefox without a desktop ? You don't need to actually have a screen to run Desktop, you can you use VNC to watch instapy in action and figure out what's going on. I could make instapy working this way. (but now I'm getting new issues, not related, like block on follow. Instagram has become very rude with suspected bots)

**Comment by mwargan** [comment]
@papillon-unix not sure *how* it worked, but with Chrome headless mode didn't even open a browser window, so I could run it without a desktop interface whatsoever. I am thinking the same is true for Firefox. The no GUI option would open a window, but put it out of view - and this *would* require some sort of desktop.

Besides a raspberry pi, consider how this would need to work on a server. Same issue as there isn't a GUI from the get-go on most servers. I'll be trying to reinstate Chrome with these suggestions: https://github.com/timgrossmann/InstaPy/issues/5051
