### ISSUE TITLE
Unfollowing the non-followers isn't really working

### ISSUE THREAD

**Issue by SadArmadillo** [InstaPy/InstaPy#4893]
## Expected Behavior
Unfollowing the non-followers
## Current Behavior
It says in the log that people are unfollowed successfully:

INFO [2019-08-18 08:07:01] [xxx]  Ongoing Unfollow [26/600]: now unfollowing 'b'stewws''...
INFO [2019-08-18 08:07:41] [xxx]  Last unfollow is verified after reloading the page!
INFO [2019-08-18 08:07:41] [xxx]  --> Unfollowed 'stewws'!
INFO [2019-08-18 08:07:52] [xxx]  Ongoing Unfollow [27/600]: now unfollowing 'b'eljuanca''...
INFO [2019-08-18 08:08:30] [xxx]  Last unfollow is verified after reloading the page!

but in fact no unfollowing is happening in Instagram.

## InstaPy configuration

session = InstaPy(username=insta_username, password=insta_password, nogui=True)
session.login()
session.set_relationship_bounds(enabled=True,
                                 potency_ratio=-0.8,
                                  delimit_by_numbers=True,
                                   max_followers=2000,
                                    max_following=2000,
                                     min_followers=50,
                                      min_following=100,
                       min_posts= 6,
                                            max_posts= 1300)
session.set_skip_users(skip_private=False, skip_no_profile_pic=True, skip_business=True)
session.unfollow_users(amount=600, nonFollowers=True, style="RANDOM", unfollow_after=None, sleep_delay=30)
.
.
.

**Comment by Tr1pke** [comment]
have the same issue

**Comment by jm-willy** [comment]
How many were unfollowed, not even one?

**Comment by SadArmadillo** [comment]
Thanks for replying,

Not even one single user .

I tried for a list of 300, nothing happend

**Comment by jm-willy** [comment]
Since your setting are a little aggresive, could be Instagram blocked your unfollow action because in some moment you hit the unfollow limit ?

**Comment by Tr1pke** [comment]
I have the same issue. And I haven’t unfollowed a single users for a month before this day. On the website and app itself I can unfollow without a problem

**Comment by andreescocard** [comment]
same problem, seems like an xpath problem

**Comment by mikediachenko** [comment]
Strange, for me unfollowing works fine. Already unfollowed almost 1k accounts.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andreescocard** [comment]
@mikediachenko which Instapy version? Which Instapy function?

**Comment by andreescocard** [comment]
I find a workaround for this:
Using a raspberry pi in headless mode, i have the output that the users was unfollowed, but none of them was unfollowed.
Installed InstaPy on Windows and runned the script to unfollow who the profile don't follow
Somehow viewing in browser the action works
I copied the nonfollowers in .json file located in "C:\Users\WINDOWSPROFILE\InstaPy\logs\INSTAGRAMPROFILE\relationship_data\INSTAGRAMPROFILE\nonfollowers" and pasted in the array in python file (to avoid listing again the nonfollowers that takes some time)
hope it helps anyone :)

**Comment by NooriP** [comment]
Same problem here. Is there any solution ?

**Comment by simba531** [comment]
I figured out the problem. I'm not able to fix it though... The get_following_status() function is looking for a "follow" or "unfollow" button on the page to determine if you are in fact currently following the user. But the Instagram "Suggested for you" section has plenty of "follow" buttons. So unfollowing a user is mostly failing for this reason. See screenshot. 
![image](https://user-images.githubusercontent.com/55585275/65323402-8e9b2900-dba9-11e9-82ff-199729cac16b.png)

**Comment by simba531** [comment]
It seems that there is another scenario for why it fails. The "confirm unfollow" dialogue only appears if the browser is in the foreground, which doesnt allow the bot to click the follow. Some action needs to be taken to force the dialoge to always show
