### ISSUE TITLE
Chrome Driver issue on Chrome76 & Instapy 6.0.1

### ISSUE THREAD

**Issue by jackaryas** [InstaPy/InstaPy#4899]
## Expected Behavior
Instapy should run with specified config
## Current Behavior
On Instapy 0.6.1 and Chrome 76 the following error is thrown `Message: Unable to find a matching set of capabilities` or `

On Instapy < 0.6.0 and Chrome 76 the following error is thrown ` Chrome version must be between 71 and 75` 

## Possible Solution (optional)
I found a workaround by replacing the matching chrome driver from https://chromedriver.chromium.org/downloads in your instapy_chromedriver directory (for pip) which in my case was `C:\Users\jacka\AppData\Local\Programs\Python\Python36\Lib\site-packages\instapy_chromedriver`, being sure to overwrite the old one with the same name.

There is probably a much more elegant solution but im still learning Instapy config :) 

## InstaPy configuration

- Chrome 76.0.3809.10
- Instapy 0.6.1 (same on 0.6.0)
- installed with pip

**Comment by Mr-HaleYa** [comment]
Ummm, no there's not really a more "elegant" way of doing so. What you did is the only way as of right now.

**Comment by LouisDuncan** [comment]
I am getting this same problem but on Mac, once i open the chromedriver it just opens it in terminal and i still cant run the script.

Also does anyone know if I use this for a business is it breaking any instagram guidlines?

**Comment by MaxErfurt** [comment]
Fantastic, worked for me. Thank you @jackaryas

**Comment by arthasisacat** [comment]
this is working for me! 
To be specific, matching chromedriver means: go to your chrome -> about google chrome-> version.
then go to https://chromedriver.chromium.org/downloads to find that chromedriver that matches the version.
replace it to the place such as `/Users/<yourusername>/Library/Python/2.7/lib/python/site-packages/instapy_chromedriver/`
