### ISSUE TITLE
Do we need a better how-to-build-and-run guide?

### ISSUE THREAD

**Issue by sunnypatel165** [InstaPy/InstaPy#49]
Hi! Looks like a fun project to work on!
Just followed your steps - try to setup using setup.py. Kept getting permission denied and such:
```
Checking .pth file support in /Library/Python/2.7/site-packages/
  error: can't create or remove files in install directory

   The following error occurred while trying to add or remove files in the
   installation directory:
   [Errno 13] Permission denied: /Library/Python/2.7/site-packages/test-easy-install-4896.pth

   The installation directory you specified (via --install-dir, --prefix, or the distutils default setting) 
    was:
     /Library/Python/2.7/site-packages/
```
Then figured this needs to be run via Python 3.

So ran the same command as `python3 setup.py install `

Now I get this:
![image](https://cloud.githubusercontent.com/assets/9017668/24825954/8bd0f844-1c48-11e7-89e6-0293dbd629ba.png)

So was wondering if we need a better guide or need a good dependency management?
(Saw someone has an open PR for Docker +1 for that!)
PS - sorry if this is lame, been a Java developer all of my life except a couple of projects 😝

**Comment by victorsc** [comment]
@sunnypatel165 I got the exact same error.

**Comment by apertureless** [comment]
You should considering using pythons `virtualenv` to create a seperated environment for it. This way you don't pollute your system with the dependencies. Pyhton is kind of weird because you have still 2.7 and 3.x running seperately. 

1. `pip install virtualenv`
2. `virtualenv -p python3 instapy`
3. `source instapy/bin/activate`
4. `pip install -U pip`
5. `pip install .`

**Comment by sunnypatel165** [comment]
Thanks @apertureless , getting this now! 😞 
![image](https://cloud.githubusercontent.com/assets/9017668/24828464/37f1755e-1c7b-11e7-8425-5d1c5fe259e9.png)

**Comment by apertureless** [comment]
Seems to be a problem with pillow.
Try to close the terminal session, reopen a new one and then 

` xcode-select --install`

and then swap into the virtual env with `source instapy/bin/activate`  and try to install again.

**Comment by sunnypatel165** [comment]
Thank you sir @apertureless 💯
