### ISSUE TITLE
No 'xpath_compile.py' for Mac installation of 0.6.1?

### ISSUE THREAD

**Issue by Flaunkerton2395** [InstaPy/InstaPy#4902]
I have seen a lot of solutions for the 'A/B test' error coming from 0.6.1 that involve changing the 'xpath_compile.py' file like #4887 and #4895 but the file is not in the Instapy folder for my Mac installation. Has anyone been able to fix this current issue for Macs?

**Comment by Mr-HaleYa** [comment]
Message me on discord if you can screen share and I will help you find your file

**Comment by Flaunkerton2395** [comment]
Fixed with #4908
