### ISSUE TITLE
"cannot get if user is private" Error

### ISSUE THREAD

**Issue by Jacobean0** [InstaPy/InstaPy#4906]
i have been facing this kind of problem pls let me know how to fix that problem. 
Thank you
 
"ERROR [2019-08-19 11:45:31] [xxx]  ~cannot get if user is private"
"INFO [2019-08-19 11:45:31] [xxx]  ---> Sorry, couldn't get if user is private"

## InstaPy configuration

session.set_user_interact(amount=5, randomize=True, percentage=100,
                              media='Photo')
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=False,
                                    max_followers=300000,
                                    max_following=7000,
                                    min_followers=50,
                                    min_following=50)
    session.set_simulation(enabled=True, percentage=70)
    session.set_do_like(enabled=True, percentage=100)

    session.set_ignore_users([])
    session.set_do_comment(enabled=True, percentage=35)
    session.set_do_follow(enabled=True, percentage=100, times=1)
    session.follow_by_tags([], amount=10, interact=True)
    session.unfollow_users(amount=40, nonFollowers=True, style="RANDOM", unfollow_after=42 * 60 * 60, sleep_delay=300)
    session.set_ignore_if_contains([])
    session.set_action_delays(enabled=True, like=5.2, randomize=True, random_range=(70, 140))

**Comment by GreatMalboro** [comment]
I literally just noticed my bot not working correctly, I am also looking for the reason of this.

Edit: Here you go brotha try this one :: https://github.com/timgrossmann/InstaPy/pull/4689

**Comment by AdriaanRoets** [comment]
I ran InstaPy yesterday, getting this message for hours on end before I realized it and stopped the bot.

**Comment by Jacobean0** [comment]
> I literally just noticed my bot not working correctly, I am also looking for the reason of this.
> 
> Edit: Here you go brotha try this one :: #4689

I tried but still it doesnt work
