### ISSUE TITLE
Login A/B test detected! Trying another string...

### ISSUE THREAD

**Issue by flygohr** [InstaPy/InstaPy#4907]
## Expected Behavior

I have multiple instances of InstaPy running, and I succesfully updated them all to the latest version, struggled a bit with firefox and with the new syntax and got them all running. All of them share the same configuration (digitalocean droplet with ubuntu lts, same updates, same stuff installed, five different droplets btw different ip). All of them are working good since last week.

## Current Behavior

All of them except one! This one refuses to start and continues giving me this A/B test thing. Tried searching past issues and found no solution, logging in manually or checking suspicious activity notification doesn't work. 

Btw, don't know how to start a desktop environment on DigitalOcean, I am doing everything from command line.

`
INFO [2019-08-19 13:34:00] [.]  - Instagram WebSite Status: Currently Up
INFO [2019-08-19 13:34:00] [.]  - Instagram Response Time: 42.961 ms
INFO [2019-08-19 13:34:00] [.]  - Instagram Reponse Code: 200
INFO [2019-08-19 13:34:00] [.]  - Instagram Server Status: ok
INFO [2019-08-19 13:34:00] [.]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-08-19 13:34:00] [.]  - window.navigator.webdriver response: False
INFO [2019-08-19 13:34:00] [.]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

...........................................................................................................................
CRITICAL [2019-08-19 13:34:16] [.]  Unable to login to Instagram! You will find more information in the logs above.

**Comment by ghost** [comment]
Hello, this solution worked for me.

Try it: https://github.com/timgrossmann/InstaPy/issues/4877#issuecomment-522282119

**Comment by depayem** [comment]
Check this #4908
