### ISSUE TITLE
Pay 50$ if anyone install instapy

### ISSUE THREAD

**Issue by IyanArce99** [InstaPy/InstaPy#4913]
If anyone install instapy on my windows server 2019 I pay 50$. writte me = iyiarce@gmail.com

**Comment by ghost** [comment]
> If anyone install instapy on my windows server 2019 I pay 50$. writte me = [iyiarce@gmail.com](mailto:iyiarce@gmail.com)

do you have discord? what is your problem you cant have this working for you right?

**Comment by IyanArce99** [comment]
I have email, send me one and we speak by that. iyiarce@gmail.com

**Comment by ilovetosharing** [comment]
@IyanArce99 for now InstaPy run only one instance (just one account) in windows, if you want me to set it up to run in your windows server for just one account then contact me on telegram @ILoveToSharing https://t.me/ILoveToSharing

**Comment by ilovetosharing** [comment]
@IyanArce99 The old version 0.5.8? because for InstaPy dev branch, run only one instance (just one account) in windows (geckodriver problem), if you want me to set it up to run in your windows server for just one account then contact me on telegram @ILoveToSharing https://t.me/ILoveToSharing
