### ISSUE TITLE
Last Follow is not verified

### ISSUE THREAD

**Issue by IyanArce99** [InstaPy/InstaPy#4916]
When i do follow unfollow, it says every 4 accounts:

Last Follow is not verified "username" might be temporarly blocked from follow

But on my phone works why?

**Comment by skinner12** [comment]
Blocked for bot..

**Comment by Sam-Morgan** [comment]
I has this issue. I found that the follow went ahead correctly, but was not registered by instapy (and unfortunately not added to the database). I found that having instapy operate in a browser (I use firefox) when full screened makes the issue far more infrequent, so maybe it is an issue with recognising UI changes. Try the full-screen fix (you can then minimise the browser it seems).
