### ISSUE TITLE
Sometimes getting error on start up.

### ISSUE THREAD

**Issue by KirjoZzZ** [InstaPy/InstaPy#4919]
Hello.

Sometimes it works normally, sometimes I'm getting this error:

[https://i.imgur.com/DEIBFae.jpg](url)

Does anyone know how can I fix it?

Thank you in advance.

**Comment by mikediachenko** [comment]
@KirjoZzZ the image is not accessible. Past the error code here.

**Comment by KirjoZzZ** [comment]
> 
> 
> @KirjoZzZ the image is not accessible. Past the error code here.

` ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Administrator/InstaPy"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\InstaPy\Likesstart.py", line 45, in <modu
le>
    headless_browser=True)
  File "C:\Users\Administrator\Desktop\InstaPy\instapy\instapy.py", line 318, in
 __init__
    self.logger,
  File "C:\Users\Administrator\Desktop\InstaPy\instapy\browser.py", line 118, in
 set_selenium_local_session
    browser.install_addon(create_firefox_extension(), temporary=True)
  File "C:\Users\Administrator\Desktop\InstaPy\instapy\browser.py", line 46, in
create_firefox_extension
    with zipfile.ZipFile(zip_file, "w", zipfile.ZIP_DEFLATED, False) as zipf:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\zipfil
e.py", line 1207, in __init__
    self.fp = io.open(file, filemode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Administrator\\InstaPy\\assets
\\extension.xpi'
`

**Comment by NooriP** [comment]
Same

**Comment by mikediachenko** [comment]
@KirjoZzZ Please, send us `python —version` and `python -m pip --version ` .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NooriP** [comment]
For the python version : 3.6 and for the pip 19.2.3

**Comment by mikediachenko** [comment]
>For the python version : 3.6 and for the pip 19.2.3

@NooriP And seems you have python3.7 in your system. Does command `python37` or `python3.7` gives any result?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
