### ISSUE TITLE
Unable to follow anyone (InstaPy 0.6.1)

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4920]
Hello,
I have just upgraded to InstaPy 0.6.1, running on a Windows 10 machine.
I am unable to follow anyone.

Are you in my same situation?

I have installed InstaPy through the "instapy-quickstart-master" repository.

Thanks.

**Comment by siddhantchimankar** [comment]
same

**Comment by br551** [comment]
Same problem, unable to follow 
https://github.com/timgrossmann/InstaPy/issues/5452
