### ISSUE TITLE
Unable to login to Instagram!

### ISSUE THREAD

**Issue by alexandre-maicol** [InstaPy/InstaPy#4921]
python3 quickstart.py

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/user/InstaPy"

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-18 23:24:15] [e3veiculos]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-08-18 23:24:15] [e3veiculos]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-08-18 23:24:16] [e3veiculos]  - Internet Connection Status: ok
INFO [2019-08-18 23:24:16] [e3veiculos]  - Current IP is "143.255.150.6" and it's from "Brazil/BR"
INFO [2019-08-18 23:24:16] [e3veiculos]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-08-18 23:24:22] [e3veiculos]  - Instagram WebSite Status: Currently Up 
INFO [2019-08-18 23:24:22] [e3veiculos]  - Instagram Response Time: 50.086 ms 
INFO [2019-08-18 23:24:22] [e3veiculos]  - Instagram Reponse Code: 200
INFO [2019-08-18 23:24:22] [e3veiculos]  - Instagram Server Status: ok
INFO [2019-08-18 23:24:22] [e3veiculos]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-08-18 23:24:22] [e3veiculos]  - window.navigator.webdriver response: False
INFO [2019-08-18 23:24:22] [e3veiculos]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

........................................................................................................................
CRITICAL [2019-08-18 23:24:38] [e3veiculos]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2019-08-18 23:24:38] [e3veiculos]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2019-08-18 23:24:48] [e3veiculos]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 45.58 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-18 23:24:48] [e3veiculos]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo

I am using Ubuntu, the program even opens the most unsuccessful browser!

**Comment by Flaunkerton2395** [comment]
Update to dev branch

pip install -U git+https://github.com/timgrossmann/InstaPy@dev

**Comment by mikediachenko** [comment]
Or downgrade to 0.5.8 instapy version.

**Comment by patrickgodinho** [comment]
@Flaunkerton2395 when I run pip install -U git+https://github.com/timgrossmann/InstaPy@dev I got this:

`ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.5/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/th/zxc_ssz10sn3q9fnv2d4m33c0000gn/T/pip-req-build-6twufzc7/setup.py'"'"'; __file__='"'"'/private/var/folders/th/zxc_ssz10sn3q9fnv2d4m33c0000gn/T/pip-req-build-6twufzc7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/th/zxc_ssz10sn3q9fnv2d4m33c0000gn/T/pip-req-build-6twufzc7/
    Complete output (7 lines):
    /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in instapy setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected ',' or end-of-list in PyVirtualDisplay>=0.2.1; sys_platform != 'win32' at ; sys_platform != 'win32'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

Have you any idea to help me?

**Comment by elfacu0** [comment]
@patrickgodinho Try using
pip install -U git+https://github.com/timgrossmann/InstaPy@dev --user
It worked for me
