### ISSUE TITLE
Selenium not recognize firefox -> add a way to set binary property

### ISSUE THREAD

**Issue by meriturva** [InstaPy/InstaPy#4923]
I still have a problem with selenium on windows.

`selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`

Related to: https://github.com/mozilla/geckodriver/issues/1601

The only solution is to add on browse.py file line:

`firefox_options.binary = r'C:\Program Files\Mozilla Firefox\firefox.exe';`

Any way to accept it as a args on InstaPy main class?

**Comment by clementizard** [comment]
You just saved my day with this line. Thank you.

**Comment by prototype127** [comment]
@clementizard  hey iam getting this error on firefox (  Unable to login to Instagram! You will find more information in the logs above ) plz help me

**Comment by prototype127** [comment]
@meriturva  firefox_options.binary = r'C:\Program Files\Mozilla Firefox\firefox.exe'; .......... what i have to do with this ?? plz help instapy unable to log in to instagram

**Comment by meriturva** [comment]
@prototype127 do you see firefox open or not?

**Comment by DenisKot** [comment]
@meriturva It helped, thanks a lot! :)

**Comment by cormo1990** [comment]
same problem but on OS, firefox is opened but can't login on Ig

**Comment by meriturva** [comment]
if firefox is opened please search or open a new issue!

**Comment by JuanSpada** [comment]
@meriturva Hi where i need to add that line?
firefox_options.binary = r'C:\Program Files\Mozilla Firefox\firefox.exe';

**Comment by meriturva** [comment]
Here: https://github.com/timgrossmann/InstaPy/blob/master/instapy/browser.py#L81

**Comment by adamlh** [comment]
What must be done after adding that line in? Many thanks for any help to get this working!

**Comment by gagannagarm** [comment]
@meriturva Thanks dear, now it's working.

**Comment by breuerfelix** [comment]
@meriturva you could do a PR to accept that in the constructor :)

**Comment by meriturva** [comment]
Sorry @breuerfelix but I'm really full and I don't use anymore `instapy`
