### ISSUE TITLE
ERROR: private account

### ISSUE THREAD

**Issue by Bijiboom** [InstaPy/InstaPy#4926]
Hey guys,

Im new here and don't understand that much.
I was using insteps this evening and everything was workin smoothly.

And now the code is not doin anything and keeps repeating this:

ERROR [2019-08-21 20:25:02] ~cannot get if user is private
INFO [2019-08-21 20:25:02] ---> Sorry, couldn't get if user is private
INFO [2019-08-21 20:25:02] Like# [3/50]
INFO [2019-08-21 20:25:02] https://www.instagram.com/p/B1UyDI5BH2I/
INFO [2019-08-21 20:25:06] Image from: b'jcezaaaaar'
INFO [2019-08-21 20:25:06] Link: b'https://www.instagram.com/p/B1UyDI5BH2I/'
INFO [2019-08-21 20:25:06] Description: b'\xf0\x9f\x92\x8a\n.\n. .\n.\n\n#clout #mensfashion#swag#hypebeast#streetwear#streetstyle#streetfashion#fashion#styleins

Can somebody help me please?! appreciate it

**Comment by Flaunkerton2395** [comment]
I also have this error. When I turn headless mode off, I can see Firefox trying to access the page but the page itself comes to an error for every user

**Comment by patrickgodinho** [comment]
Same here, `Sorry, couldn't get if user is private ` but the user is not... :/ any suggestions?

**Comment by riccardovalente** [comment]
Same here. But the strange thing is that I only get this with ONE of my accounts. All the others are working ok.

**Comment by cutzenfriend** [comment]
Same issue here for 3 Accs...
But not for all users. Somehow I think the detection of private users keeps failing...

**Comment by brnskn** [comment]
PR #4892 fixes this
