### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by dar2015** [InstaPy/InstaPy#4927]
I'm trying to set proxy. I checked with my browser and proxy is valid and working 
My proxy doesn't have any authentication

```
Connection Checklist [1/3] (Internet Connection Status)
- Proxy is set, but it's not working properly
- Expected Proxy IP is "80.116.1.123", and the current IP is "43.132.80.111"
- Try again or disable the Proxy Address on your setup
- Aborting connection...
............................................................................
 Unable to login to Instagram! You will find more information in the logs 
```

**Comment by converge** [comment]
hey @dar2015 , how are you setting it up?

**Comment by superryeti** [comment]
Hi @converge .  Instapy seems to be unable to use the authenticated proxy with the update. 
I had to downgrade to 0.5.8 to use the proxy. I cannot use soo many features of the new updates.
Any suggestions?

Here is the setting
```
session = InstaPy(username=insta_username,
                      password=insta_password,
                      proxy_address=proxy_host,
                      proxy_port=proxy_port,
                      proxy_username=proxy_username,
                      proxy_password=proxy_password,
                      )

```

**Comment by dar-intsights** [comment]
> hey @dar2015 , how are you setting it up?

session = InstaPy(username='instauser',
                      password='password,
                      proxy_address='80.116.1.123',
                      proxy_port='8080',
       )

**Comment by dar-intsights** [comment]
> Hi @converge . Instapy seems to be unable to use the authenticated proxy with the update.
> I had to downgrade to 0.5.8 to use the proxy. I cannot use soo many features of the new updates.
> Any suggestions?
> 
> Here is the setting
> 
> ```
> session = InstaPy(username=insta_username,
>                       password=insta_password,
>                       proxy_address=proxy_host,
>                       proxy_port=proxy_port,
>                       proxy_username=proxy_username,
>                       proxy_password=proxy_password,
>                       )
> ```

That why I mention that my proxy is without authentication. just address and port.

**Comment by dar2015** [comment]
> hey @dar2015 , how are you setting it up?
```

session = InstaPy(username='instauser',
                      password='password,
                      proxy_address='80.116.1.123',
                      proxy_port='8080',
       )

```


> Hi @converge . Instapy seems to be unable to use the authenticated proxy with the update.
> I had to downgrade to 0.5.8 to use the proxy. I cannot use soo many features of the new updates.
> Any suggestions?
> 
> Here is the setting
> 
> ```
> session = InstaPy(username=insta_username,
>                       password=insta_password,
>                       proxy_address=proxy_host,
>                       proxy_port=proxy_port,
>                       proxy_username=proxy_username,
>                       proxy_password=proxy_password,
>                       )
> ```

That why I mention that my proxy is without authentication. just address and port.

**Comment by superryeti** [comment]
> > Hi @converge . Instapy seems to be unable to use the authenticated proxy with the update.
> > I had to downgrade to 0.5.8 to use the proxy. I cannot use soo many features of the new updates.
> > Any suggestions?
> > Here is the setting
> > ```
> > session = InstaPy(username=insta_username,
> >                       password=insta_password,
> >                       proxy_address=proxy_host,
> >                       proxy_port=proxy_port,
> >                       proxy_username=proxy_username,
> >                       proxy_password=proxy_password,
> >                       )
> > ```
> 
> That why I mention that my proxy is without authentication. just address and port.

yes, I could see that in question but there are already issues asking how to use authentication in firefox. So I didn't want to open a new issue.

Since converge was following the issue. I just wanted to know if i was doing something wrong.

**Comment by dar-intsights** [comment]
> > > Hi @converge . Instapy seems to be unable to use the authenticated proxy with the update.
> > > I had to downgrade to 0.5.8 to use the proxy. I cannot use soo many features of the new updates.
> > > Any suggestions?
> > > Here is the setting
> > > ```
> > > session = InstaPy(username=insta_username,
> > >                       password=insta_password,
> > >                       proxy_address=proxy_host,
> > >                       proxy_port=proxy_port,
> > >                       proxy_username=proxy_username,
> > >                       proxy_password=proxy_password,
> > >                       )
> > > ```
> > 
> > 
> > That why I mention that my proxy is without authentication. just address and port.
> 
> yes, I could see that in question but there are already issues asking how to use authentication in firefox. So I didn't want to open a new issue.
> 
> Since converge was following the issue. I just wanted to know if i was doing something wrong.

I did another check. I took firefox setting and create an python script that run with exact setting (gekodriver and firefox profile) with the proxy and open "http://ifconfig.co" and proxy was worked. 
Probably something in Instapy code that broke in the chain of setting right the proxy.

**Comment by dar2015** [comment]
> > > Hi @converge . Instapy seems to be unable to use the authenticated proxy with the update.
> > > I had to downgrade to 0.5.8 to use the proxy. I cannot use soo many features of the new updates.
> > > Any suggestions?
> > > Here is the setting
> > > ```
> > > session = InstaPy(username=insta_username,
> > >                       password=insta_password,
> > >                       proxy_address=proxy_host,
> > >                       proxy_port=proxy_port,
> > >                       proxy_username=proxy_username,
> > >                       proxy_password=proxy_password,
> > >                       )
> > > ```
> > 
> > 
> > That why I mention that my proxy is without authentication. just address and port.
> 
> yes, I could see that in question but there are already issues asking how to use authentication in firefox. So I didn't want to open a new issue.
> 
> Since converge was following the issue. I just wanted to know if i was doing something wrong.

I did another check. I took firefox setting and create an python script that run with exact setting (gekodriver and firefox profile) with the proxy and open "http://ifconfig.co" and proxy was worked. 
Probably something in Instapy code that broke in the chain of setting right the proxy.

**Comment by dar2015** [comment]
Found the issue. If there is locally clone of instapy on the machine it cause this issue. you should delete it and use pip library of instapy.
