### ISSUE TITLE
cookies or logs are not being created

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4929]
my profile for some reason isnt making cookies. any help please?

insta_username = 'instagram'
insta_password = 'password'

bot = InstaPy(username=insta_username, password=insta_password, multi_logs=True, selenium_local_session=False)
bot.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub')
bot.login()
bot.set_simulation(enabled=False)
bot.set_relationship_bounds(enabled=True,
potency_ratio=None,
delimit_by_numbers=True,
max_followers=3000,
max_following=2000,
min_followers=45,
min_following=10)

**Comment by depayem** [comment]
Check this #4908. Should help

**Comment by ghost** [comment]
> Check this #4908. Should help

thank you for you reply, but this is the weird part, im using the dev branch.

**Comment by ghost** [comment]
i mean something real weird is happening with instapy. i have 2 versions in my mac
0.5.7 and the dev version.

using the old classic version everything was working flawless, the only reason i downloaded dev was because using this old version of instapy for some reason it started to not read cookies and every time i was running it up, it was making new cookies which gave me suspicious logging for some reason and the bypass flags arent working.

this cause Instagram to block my comments and likes some times. they even got me to reset everything, like password, ect. saying they noticed i was using a bot and that if i keep doing that i will get my account block. 

so this is why i decided to get the new 6.0 or dev version. because the old version stopped using cookies. now the the problem with this new version is that i cant run it using `bot.set_selenium_remote_session` using this way i was able to see everything just using a vnc. now i cant, i can only run it local and only see the logs not what the script is doing like i used to.

`bot.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub', logger=False)` to use this you have to have `logger=False` just as is here but for some reason isnt working.

**Comment by dandy27** [comment]
> i mean something real weird is happening with instapy. i have 2 versions in my mac
> 0.5.7 and the dev version.
> 
> using the old classic version everything was working flawless, the only reason i downloaded dev was because using this old version of instapy for some reason it started to not read cookies and every time i was running it up, it was making new cookies which gave me suspicious logging for some reason and the bypass flags arent working.
> 
> this cause Instagram to block my comments and likes some times. they even got me to reset everything, like password, ect. saying they noticed i was using a bot and that if i keep doing that i will get my account block.
> 
> so this is why i decided to get the new 6.0 or dev version. because the old version stopped using cookies. now the the problem with this new version is that i cant run it using `bot.set_selenium_remote_session` using this way i was able to see everything just using a vnc. now i cant, i can only run it local and only see the logs not what the script is doing like i used to.

`bot.set_selenium_remote_session` running this line you will have to add `logger=False` to get it working... but for some reason isnt working, it give me errors

**Comment by mikediachenko** [comment]
>i mean something real weird is happening with instapy. i have 2 versions in my mac ...

@dandy27 That is all because you have tons of python versions, pip version and instapy version on your mac. I hade the same issue on mine and I need to insta instaPy and modules using pup3.7, pip3, pip, etc., until I just reinstalled macOS, install latest python and pip properly and now all is good with no errors and issue. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ghost** [comment]
> > i mean something real weird is happening with instapy. i have 2 versions in my mac ...
> 
> @dandy27 That is all because you have tons of python versions, pip version and instapy version on your mac. I hade the same issue on mine and I need to insta instaPy and modules using pup3.7, pip3, pip, etc., until I just reinstalled macOS, install latest python and pip properly and now all is good with no errors and issue.
> 
> Sent with [GitHawk](http://githawk.com)

no is not my case, im even running this in ENV. i only have 3.7 and pip 3 in my system nothing algo

**Comment by mikediachenko** [comment]
>> > i mean something real weird is happening with instapy. i have 2 versions in my mac ... ...

@dandy27 `python —version`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
