### ISSUE TITLE
InstaPy not liking pictures (wait a few minutes), liking manually works.

### ISSUE THREAD

**Issue by Zettt** [InstaPy/InstaPy#4931]
## Current Behavior
Right now InstaPy is unable to like pictures again. I'm assuming there's been an Xpath change again?
Firefox goes to the error page almost instantly,

```
Error

Please wait a few minutes before you try again.
```

```
INFO [2019-08-23 06:19:46] [me]  Failed to get followers count of 'b'in_love_with_streetart''  ~empty list
INFO [2019-08-23 06:20:36] [me]  Failed to get following count of 'b'in_love_with_streetart''  ~empty list
INFO [2019-08-23 06:20:36] [me]  User: 'in_love_with_streetart'  |> followers: unknown  |> following: unknown  |> relationship ratio: unknown
ERROR [2019-08-23 06:20:38] [me]  ~cannot get number of posts for username
INFO [2019-08-23 06:20:38] [me]  ---> Sorry, couldn't check for number of posts of username
```

**Comment by poupkine** [comment]
I have the same issue. Maybe it is a ban of your IP, I do not know how to deal with this issue at the moment.

**Comment by Zettt** [comment]
As written, I can like manually in Firefox when it's running though InstaPy.

**Comment by A5ura69** [comment]
Same problem here... 
I'm using a quickstart.py with a simple:

`# imports
from instapy import InstaPy
from instapy.util import smart_run



# login credentials
insta_username = 'user'
insta_password = 'pass'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)


with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=15000,
                                        min_followers=45,
                                        min_following=50)
    
    session.like_by_tags(['tag1', 'tag2', 'tag3', 'tag4', 'tag5', 'tag6'], amount=100, interact=True)`

After a couple of hours i got this: 
![image_2019-08-23_21-48-11](https://user-images.githubusercontent.com/40309637/63619716-b9688080-c5ef-11e9-8a41-556f33c0b825.png)

Deleting the cookie didn't solve the problem...
No problem liking posts from the app or even from the regular firefox browser logged in with the sam profile..
Someone can help?

**Comment by dtypo** [comment]
Same problem here :(
After a couple of hours of work I got this error:
![image_2019-08-23_21-48-11](https://user-images.githubusercontent.com/40309637/63620178-e6696300-c5f0-11e9-8557-ba52e5b299d4.png)

I'm using this simple quickstart.py:

```
# imports
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = 'user'
insta_password = 'pass'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=15000,
                                        min_followers=45,
                                        min_following=50)
    
    session.like_by_tags(['tag1', 'tag2', 'tag3', 'tag4', 'tag5', 'tag6'], amount=100, interact=True)
```
The weird part is that i'm able to like posts with regular firefox browser logged with the same account, but instagram has temporary disabled the search function... 
I can see the instagram main feed but can't search for tags or profiles...
I've even tried to delete the cookies, but the problem has not solved.

Someone can help?

**Comment by jamezun** [comment]
it happens to me too, it appears after a number of likes that i performed, i guess they disable our instagram when we reach to a certain limits of likes which the parameters might be different for every accounts..

**Comment by mikediachenko** [comment]
I had the same issue in past. It was due to IP blocking by Instagram.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Zettt** [comment]
> I had the same issue in past. It was due to IP blocking by Instagram.

Then why does liking manually through the same browser work?

**Comment by Pangolino2a** [comment]
Like work manually with the same browser but on bot im blocked.... Please help !!!

**Comment by Knrd2** [comment]
Im gettin the same error: 
Error
Please wait a few minutes before you try again.

What to do ?

**Comment by NooriP** [comment]
Same error here !

**Comment by orsi-dev** [comment]
same here, anyone knows how long it's the "ban" ? 
it should be related to the account, i've got the same error using https proxy and different user-agent.

**Comment by CharlesCCC** [comment]
It seems like Instagram put lots of effort attacking automated solution like the InstaPy. 
They must have some way to detect we are automating things, and so it blocked the activity.
 @sionking used to did lots of research on that.

**Comment by meth0xy** [comment]
Same issue here. Hope there is a fix for that?

**Comment by meth0xy** [comment]
found out that clearing localStorage in Firefox let you visit sites again, but dont know how ling this works.

**Comment by turtlebking** [comment]
> Same problem here :(
> After a couple of hours of work I got this error:
> ![image_2019-08-23_21-48-11](https://user-images.githubusercontent.com/40309637/63620178-e6696300-c5f0-11e9-8557-ba52e5b299d4.png)
> 
> I'm using this simple quickstart.py:
> 
> ```
> # imports
> from instapy import InstaPy
> from instapy.util import smart_run
> 
> # login credentials
> insta_username = 'user'
> insta_password = 'pass'
> 
> # get an InstaPy session!
> # set headless_browser=True to run InstaPy in the background
> session = InstaPy(username=insta_username,
>                   password=insta_password,
>                   headless_browser=False)
> 
> with smart_run(session):
>     """ Activity flow """
>     # general settings
>     session.set_relationship_bounds(enabled=True,
>                                       delimit_by_numbers=True,
>                                        max_followers=15000,
>                                         min_followers=45,
>                                         min_following=50)
>     
>     session.like_by_tags(['tag1', 'tag2', 'tag3', 'tag4', 'tag5', 'tag6'], amount=100, interact=True)
> ```
> 
> The weird part is that i'm able to like posts with regular firefox browser logged with the same account, but instagram has temporary disabled the search function...
> I can see the instagram main feed but can't search for tags or profiles...
> I've even tried to delete the cookies, but the problem has not solved.
> 
> Someone can help?

it is a soft ban

**Comment by dtypo** [comment]
> > Same problem here :(
> > After a couple of hours of work I got this error:
> > ![image_2019-08-23_21-48-11](https://user-images.githubusercontent.com/40309637/63620178-e6696300-c5f0-11e9-8557-ba52e5b299d4.png)
> > I'm using this simple quickstart.py:
> > ```
> > # imports
> > from instapy import InstaPy
> > from instapy.util import smart_run
> > 
> > # login credentials
> > insta_username = 'user'
> > insta_password = 'pass'
> > 
> > # get an InstaPy session!
> > # set headless_browser=True to run InstaPy in the background
> > session = InstaPy(username=insta_username,
> >                   password=insta_password,
> >                   headless_browser=False)
> > 
> > with smart_run(session):
> >     """ Activity flow """
> >     # general settings
> >     session.set_relationship_bounds(enabled=True,
> >                                       delimit_by_numbers=True,
> >                                        max_followers=15000,
> >                                         min_followers=45,
> >                                         min_following=50)
> >     
> >     session.like_by_tags(['tag1', 'tag2', 'tag3', 'tag4', 'tag5', 'tag6'], amount=100, interact=True)
> > ```
> > 
> > 
> > The weird part is that i'm able to like posts with regular firefox browser logged with the same account, but instagram has temporary disabled the search function...
> > I can see the instagram main feed but can't search for tags or profiles...
> > I've even tried to delete the cookies, but the problem has not solved.
> > Someone can help?
> 
> it is a soft ban

The problem is... how to avoid it? :/

**Comment by sunny744** [comment]
Same issue with my script as well. Did someone got a fix for this?

**Comment by ghost** [comment]
I have that same problem. I don't have any problems on my phone, different browser, firefox browser. This problem only occurs when i run the program/script. And i don't think it's a soft ban. Because i only got this error after following 10-15 people with delay. Without like/comment also i don't use suspicious attractive instagram tags.

**Comment by matheusgregorio** [comment]
this problem lasts how long?

**Comment by Alexjpinto** [comment]
any fix for this?
