### ISSUE TITLE
Unable to login to Instagram! You will find more Information .....

### ISSUE THREAD

**Issue by sandy1812** [InstaPy/InstaPy#4935]
## Expected Behavior
Should login 
## Current Behavior
Workspace in use: "/root/InstaPy"

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-23 19:01:17] [XXX]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-08-23 19:01:17] [XXX]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-08-23 19:01:18] [XXX]  - Internet Connection Status: ok
INFO [2019-08-23 19:01:18] [XXX]  - Current IP is "167.71.xxx.xxx" and it's from "India/IN"
INFO [2019-08-23 19:01:18] [XXX]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-08-23 19:01:25] [XXX]  - Instagram WebSite Status: Currently Up 
INFO [2019-08-23 19:01:25] [XXX]  - Instagram Response Time: 40.422 ms 
INFO [2019-08-23 19:01:25] [XXX]  - Instagram Reponse Code: 200
INFO [2019-08-23 19:01:25] [XXX]  - Instagram Server Status: ok
INFO [2019-08-23 19:01:25] [XXX]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-08-23 19:01:25] XXX]  - window.navigator.webdriver response: False
INFO [2019-08-23 19:01:25] [XXX]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

.....................................................................................................................
CRITICAL [2019-08-23 19:01:41] [XXX]  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2019-08-23 19:01:41] XXX]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2019-08-23 19:01:46] [XXX]  Sessional Live Report:
        |> No any statistics to show

[Session lasted 34.13 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-23 19:01:46] [XXX]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooo
## InstaPy configuration

# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'user'
insta_password = 'pass'

comments = ['Nice shot! @{}',
        'I love your profile! @{}',
        'Your feed is an inspiration :thumbsup:',
        'Just incredible :open_mouth:',
        'What camera did you use @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Getting inspired by you @{}',
        ':raised_hands: Yes!',
        'I can feel your passion @{} :muscle:',
        'Amazing photo']

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

with smart_run(session):
  """ Activity flow """
  # general settings
  session.set_dont_include(["friend1", "friend2", "friend3"])

  # activity
  session.like_by_tags(["natgeo"], amount=10)

  # Joining Engagement Pods
  session.set_do_comment(enabled=True, percentage=35)
  session.set_comments(comments)
  session.join_pods(topic='sports', engagement_mode='heavy')

I am using it on Ubuntu 64 on Digital ocean, there is no issue with login details, however, I tried putting the wrong password and getting the same error.

Please help.

**Comment by Flaunkerton2395** [comment]
Update to dev version

pip install -U git+https://github.com/timgrossmann/InstaPy@dev

**Comment by sandy1812** [comment]
I did and got this message 

`Installing collected packages: PyYAML, instapy
  Found existing installation: PyYAML 3.12
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

And same error after running quickstart.py

**Comment by mikediachenko** [comment]
Try:
pip install -U git+https://github.com/timgrossmann/InstaPy@dev —user

**Comment by sandy1812** [comment]
Now getting this error - 

`Traceback (most recent call last):
  File "quickstart.py", line 27, in <module>
    with smart_run(session):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/InstaPy/instapy/util.py", line 1834, in smart_run
    session.login()
  File "/InstaPy/instapy/instapy.py", line 408, in login
    self.proxy_address,
  File "/InstaPy/instapy/login_util.py", line 310, in login_user
    dismiss_notification_offer(browser, logger)
  File "/InstaPy/instapy/login_util.py", line 519, in dismiss_notification_offer
    browser, "VOEL", [offer_elem_loc, "XPath"], logger, 4, False
  File "/InstaPy/instapy/util.py", line 1698, in explicit_wait
    result = wait.until(condition)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/expected_conditions.py", line 415, in _find_element
    raise e
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: [Exception... "Unexpected error"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://marionette/content/driver.js :: GeckoDriver.prototype.sendAsync/< :: line 351"  data: no]`

**Comment by intothevoid** [comment]
I'm having the same issue. 

Edit: pip install -U git+https://github.com/timgrossmann/InstaPy@dev worked for me

**Comment by clementizard** [comment]
I'm having the same issue too, using
```
pip install -U git+https://github.com/timgrossmann/InstaPy@dev
```
Didn't help.

EDIT: I downloaded the zip in the dev branch, fixed (again) firefox default path, and it finally works. See  #4923 for the firefox issue.

**Comment by prototype127** [comment]
@intothevoid (I'm having the same issue.

Edit: pip install -U git+https://github.com/timgrossmann/InstaPy@dev worked for me) can you explain this ??

**Comment by NooriP** [comment]
I running the dev branch and having the same issue

**Comment by CamiloB** [comment]
i had the same issue on ubuntu server 18 and this
pip install -U git+https://github.com/timgrossmann/InstaPy@dev
worked for me

**Comment by orsi-dev** [comment]
i had the issue and updating with @dev repo worked.
pip install -U git+https://github.com/timgrossmann/InstaPy@dev

**Comment by programmerpinggiran** [comment]
i had the issue and updating with @dev repo worked.
pip install -U git+https://github.com/timgrossmann/InstaPy@dev

this my working code

```
"""
This template is written by @Tachenz
What does this quickstart script aim to do?
- Interact with user followers, liking 3 pictures, doing 1-2 comment - and
25% chance of follow (ratios which work the best for my account)
NOTES:
- This is used in combination with putting a 40 sec sleep delay after every
like the script does. It runs 24/7 at rather slower speed, but without
problems (so far).
"""


from instapy import InstaPy
from instapy import smart_run

# get a session!
session = InstaPy(username='user', password='pass',headless_browser=True,nogui=True,bypass_suspicious_attempt=True,bypass_with_mobile=True,multi_logs=True)

with smart_run(session):

    # session.set_user_interact(amount=2, randomize=True, percentage=100,
    #                           media='Photo')
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=3000,
                                    max_following=900,
                                    min_followers=50,
                                    min_following=50)
    session.set_simulation(enabled=False)
    session.set_do_like(enabled=True, percentage=100)

    session.set_do_comment(enabled=True, percentage=50)
    # session.set_do_follow(enabled=True, percentage=80, times=1)
    
    

    
    session.set_comments(['random','etc', 'n commnet'])
    
 
 
    
  
    session.like_by_tags(['hastag'], amount=15, interact=True)

    session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
    
    session.set_action_delays(enabled=True,like=20,comment=35,follow=10)

"""
-- REVIEWS --
@Andercorp:
- This would probably be the best temp for new accounts to start slowly and 
gently and then as your account gather IG authority, you could put some more 
power to your temp/bot...
@uluQulu:
- @Tachenz, the values in your script took my attention, it will be very 
good for new starters, as @Andercorp said. Stunning!
"""

```

**Comment by cjinghong** [comment]
I have the same exact issue. I found out by restarting the script again and again and eventually it will work. What I did was wrap the entire function in a loop with `Try Except` and then restart the loop whenever an `Exception` occur. If you're doing this make sure you set a maximum number of retries to prevent an infinite loop.

I know this is the hacky way to do it, but it's the only way I'm able to get it working for now.

**Comment by sepi2048** [comment]
@cjinghong I did restart the script several times manually, and made it work! Could you share a `Try Except` restart example?

**Comment by cjinghong** [comment]
@sepi2048 Sure, here's what I used:
```
for i in range(0,100):
    try:
        # ... 
        # ...
        # get a session!
        session = InstaPy(username=insta_username,
                        password=insta_password)

        with smart_run(session):
            # ...
            # ...               
    except:
        continue
```

**Comment by sepi2048** [comment]
@cjinghong Cool! Thanks, this is gold!

**Comment by nazihheni** [comment]
Hi @cjinghong I did try it your solution but seems not working after how many time it works for you please ? 
```
Cookie file not found, creating cookie...
INFO [2020-06-08 00:43:36] [vensazia]  Timed out with failure while explicitly waiting until title contains 'Login' string!

......................................................................................................................
CRITICAL [2020-06-08 00:43:55] []  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2020-06-08 00:43:55] []  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2020-06-08 00:43:56] []  Sessional Live Report:
        |> No any statistics to show

```
