### ISSUE TITLE
Unable to follow when Likes based on tags is processed

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#4937]
Hello,
does anyone know why if I set the following code `session.set_do_follow(enabled=True, percentage=10, times=2)` along with the likes based on tags procedure, **no users have been followed**, while if I create an InstaPy session for following only with the code `session.follow_by_tags(['tag1', 'tag2'], amount=10)` I am able to follow?

Thank you.

**Comment by greyslater** [comment]
interact must be true

```
# Like posts based on hashtags and like 3 posts of its poster
session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
session.like_by_tags(['natgeo', 'world'], amount=10, interact=True)
```
