### ISSUE TITLE
Comments not working on Raspberry Pi 3

### ISSUE THREAD

**Issue by gitpatrickhub** [InstaPy/InstaPy#494]
> [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=48418062)](https://www.bountysource.com/issues/48418062-error-using-interact_user_followers-on-rpi3?utm_source=48418062&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Running the latest version on Raspberry Pi 3 headless with Firefox, Python 2.7, xvfb. Receive the below warning;
```
Warning: Comment Action Likely Failed: Comment Element not found
```
Verified the post and no comment was left.

**Comment by mathmorrison** [comment]
Help me raspberries won't do work

**Comment by andrewjburnett** [comment]
@gitpatrickhub Any news on this?

**Comment by gitpatrickhub** [comment]
@andrewjburnett nothing yet. Not sure if anyone running on RPI3 can comment successfully.

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.

**Comment by gitpatrickhub** [comment]
@converge I can confirm this is working.

**Comment by StefanUPB** [comment]
So, what was the solution? Seems like I started having the issue once I activated clarifai.

**Comment by estebancortero** [comment]
So what was the solution?

**Comment by deniskrafczyk** [comment]
im getting the same issue: 

`INFO [2018-03-24 15:28:44] [xxx]  Commented: 0
--> Warning: Comment Button Not Found: May cause issues with browser windows of smaller widths
WARNING [2018-03-24 15:30:00] [xxx]  --> Warning: Comment Action Likely Failed: Comment Element not found
INFO [2018-03-24 15:30:00] [xxx]  --> Commented: 👌`

it does say: [xxx]  --> Commented: 👌, but it didnt comment :/
