### ISSUE TITLE
When trying to use "like_by_tags" I get this error: TypeError: '<' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by panchoma** [InstaPy/InstaPy#4940]
Hi everyone! 

After the upgrade, when trying to use "like_by_tags" I get the following error: 

> TypeError: '<' not supported between instances of 'int' and 'NoneType'

Anyone having an idea on how to solve it?

@uluQulu , @timgrossmann , @CharlesCCC , @Mr-HaleYa

Thank you in advance!!

## ERROR

> Traceback (most recent call last):
>   File "likes1.py", line 73, in <module>
>     session.like_by_tags(tags, amount=5, skip_top_posts=True, randomize=True, media='Photo')
>   File "C:\Users\User\AppData\...\site-packages\instapy\instapy.py", line 1919, in like_by_tags
>     self.browser, self.max_likes, self.min_likes, self.logger
>   File "C:\Users\User\AppData\...\site-packages\instapy\like_util.py", line 907, in verify_liking
>     elif min is not None and likes_count < minimum:
> TypeError: '<' not supported between instances of 'int' and 'NoneType'

## InstaPy configuration

```
# imports
from instapy import InstaPy
from instapy.util import smart_run
import time
import os
import random
from instapy import Settings
from random import sample
from clarifai.rest import ClarifaiApp
from clarifai.rest import Workflow
from selenium.common.exceptions import NoSuchElementException

# login credentials
insta_username = '...'
insta_password = '...'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  disable_image_load=True)

#Database
Settings.database_location = "./db/instapy_{}.db".format(insta_username)

with smart_run(session):
    """ Activity flow """
    # general settings

    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "server_calls"], sleepyhead=True, stochastic_flow=True, notify_me=False,
                                 peak_likes_hourly=15,
                                 peak_likes_daily=290,
                                 peak_server_calls_hourly=125,
                                 peak_server_calls_daily=2000)

    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=10000,
                                    max_following=2000,
                                    min_followers=30,
                                    min_following=30,
                                    min_posts=5)

    session.set_delimit_liking(enabled=True, max_likes=500, min_likes=None)

    session.set_skip_users(skip_private=False, private_percentage=0,
                           skip_no_profile_pic=True, no_profile_pic_percentage=100,
                           skip_business=True,
                           dont_skip_business_categories=['Camera/Photo','Photographer', 'Creators & Celebrities'])

    session.set_action_delays(enabled=True, like=35, randomize=True, random_range_from=86, random_range_to=114, safety_match=False)

    # activity

    for cycle in range(6):
        print("\n\nLOOP {}\n".format(cycle+1))

        tags = ['#tag1', '#tag2', '#tag3', '#tag4',
                '#tag5']
        tags = sample(tags, 5)
        session.like_by_tags(tags, amount=5, skip_top_posts=True, randomize=True, media='Photo')

        time.sleep(0) #take a 50 seconds of break after finishing the feature above

    session.end()
```

**Comment by panchoma** [comment]
I think I have solved the Error:

Line 907, from the like_util
`    elif min is not None and likes_count < minimum:
`
Change to:
`    elif minimum is not None and likes_count < minimum:
`
Anyone can check if it's correct?

Thanks!

**Comment by prototype127** [comment]
hey iam getting this error while trying to use 'comment by tags'

Workspace in use: "C:/Users/DMPS/InstaPy"
Traceback (most recent call last):
  File "C:\Users\DMPS\AppData\Local\Programs\Python\Python37\Lib\site-packages\quickstart.py", line 26, in <module>
    proxy_port='xxxx', headless_browser=True)
  File "C:\Users\DMPS\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\instapy.py", line 295, in __init__
    self.proxy_address and self.proxy_port > 0) or \
TypeError: '>' not supported between instances of 'str' and 'int'
>>>

**Comment by iux** [comment]
> Hi everyone!
> 
> After the upgrade, when trying to use "like_by_tags" I get the following error:
> 
> > TypeError: '<' not supported between instances of 'int' and 'NoneType'
> 
> Anyone having an idea on how to solve it?
> 
> @uluQulu , @timgrossmann , @CharlesCCC , @Mr-HaleYa
> 
> Thank you in advance!!
> 
> ## ERROR
> > Traceback (most recent call last):
> > File "likes1.py", line 73, in 
> > session.like_by_tags(tags, amount=5, skip_top_posts=True, randomize=True, media='Photo')
> > File "C:\Users\User\AppData...\site-packages\instapy\instapy.py", line 1919, in like_by_tags
> > self.browser, self.max_likes, self.min_likes, self.logger
> > File "C:\Users\User\AppData...\site-packages\instapy\like_util.py", line 907, in verify_liking
> > elif min is not None and likes_count < minimum:
> > TypeError: '<' not supported between instances of 'int' and 'NoneType'
> 
> ## InstaPy configuration
> ```
> # imports
> from instapy import InstaPy
> from instapy.util import smart_run
> import time
> import os
> import random
> from instapy import Settings
> from random import sample
> from clarifai.rest import ClarifaiApp
> from clarifai.rest import Workflow
> from selenium.common.exceptions import NoSuchElementException
> 
> # login credentials
> insta_username = '...'
> insta_password = '...'
> 
> session = InstaPy(username=insta_username,
>                   password=insta_password,
>                   headless_browser=False,
>                   disable_image_load=True)
> 
> #Database
> Settings.database_location = "./db/instapy_{}.db".format(insta_username)
> 
> with smart_run(session):
>     """ Activity flow """
>     # general settings
> 
>     session.set_quota_supervisor(enabled=True, sleep_after=["likes", "server_calls"], sleepyhead=True, stochastic_flow=True, notify_me=False,
>                                  peak_likes_hourly=15,
>                                  peak_likes_daily=290,
>                                  peak_server_calls_hourly=125,
>                                  peak_server_calls_daily=2000)
> 
>     session.set_relationship_bounds(enabled=True,
>                                     delimit_by_numbers=True,
>                                     max_followers=10000,
>                                     max_following=2000,
>                                     min_followers=30,
>                                     min_following=30,
>                                     min_posts=5)
> 
>     session.set_delimit_liking(enabled=True, max_likes=500, min_likes=None)
> 
>     session.set_skip_users(skip_private=False, private_percentage=0,
>                            skip_no_profile_pic=True, no_profile_pic_percentage=100,
>                            skip_business=True,
>                            dont_skip_business_categories=['Camera/Photo','Photographer', 'Creators & Celebrities'])
> 
>     session.set_action_delays(enabled=True, like=35, randomize=True, random_range_from=86, random_range_to=114, safety_match=False)
> 
>     # activity
> 
>     for cycle in range(6):
>         print("\n\nLOOP {}\n".format(cycle+1))
> 
>         tags = ['#allsmiles', '#alwaysmiling', '#behappyandsmile', '#bestfriends',
>                 '#bestmoments']
>         tags = sample(tags, 5)
>         session.like_by_tags(tags, amount=5, skip_top_posts=True, randomize=True, media='Photo')
> 
>         time.sleep(0) #take a 50 seconds of break after finishing the feature above
> 
>     session.end()
> ```

Hello,
i had the same problem, try to change this:
session.set_delimit_liking(enabled=True, max_likes=500, min_likes=None)
to:
session.set_delimit_liking(enabled=True, max_likes=500, min_likes=0)

**Comment by CharlesCCC** [comment]
Please check this change log here

https://github.com/timgrossmann/InstaPy/blob/10f2171b9bee5a54b824710dde7878d142c193dc/instapy/unfollow_util.py#L560

**Comment by dudiqo** [comment]
Hi, in 'min_likes=None' please change  'None' to '1' and it should work fine ;)
Somehow now 'None' is not respected here and you have to provide an int value.
Took me some time to figure out, but worked for me.

**Comment by uluQulu** [comment]
Well guys,
In my original implementation it was 'pure'ish 🍪

I guess, it's Joao who renamed my _max_ & _min_ naming to _maximum_ & _minimum_. Possibly  cos of `max` & `min` are reserved names. It's fine but he forgot something behind.
![image](https://user-images.githubusercontent.com/33269249/64074185-429b4980-ccb9-11e9-92a8-69a3b9e62531.png)
@panchoma's inspection is correct about it as above.

----
How it happens?

![image](https://user-images.githubusercontent.com/33269249/64074618-abd18b80-ccbe-11e9-8b04-04e1c4729ae5.png)

![image](https://user-images.githubusercontent.com/33269249/64074465-a2472400-ccbc-11e9-9549-148808f80ead.png)

Well, `min` is a built-in function. It is not `None` - never ever. And It was sort of my naiveness to use reserved names in here and there (_still using sometimes_ 😑).

Now, but, how it worked out earlier - Once I put _min_ as a formal argument it overwrite built-in `min` for that scope. So it worked as my expectations.
```python
# earlier
elif min is not None and likes_count < min:
```
But now there is no custom _min_.
And instead custom one is called `minimum`:
```python
# current
elif min is not None and likes_count < minimum:
```
so, it first checks the built-in `min` which is never `None` and then goes for our argument _minimum_ and in case it is `None`, it throws your **error** - cannot compare an _int_ to the `None` value.
```python
#solution
elif minimum is not None and likes_count < minimum:
```
So, as the user enables delimiting liking ands sets the minimum like's count as `None` or not defines it, it will be handled like a boss as in above 😎




---

Cheers 😁
---
