### ISSUE TITLE
 Firefox Error  Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#4943]
My firefox after start bot 5mn

Error

Please wait a few minutes before you try again.

**Comment by issamarmas** [comment]
do this it will make it slow and safe 

#sleep rules !important
    session.set_action_delays(enabled=True,
                           like=30,
                           comment=29,
                           follow=71,
                           unfollow=28,
                           story=10,
                           randomize=True, random_range_from=70, random_range_to=140)
