### ISSUE TITLE
Firefox  Error  Please wait a few minutes before you try again. help Please

### ISSUE THREAD

**Issue by johnvfitness** [InstaPy/InstaPy#4944]
instapy 0.6.1 and 0.6.2 same error

Firefox Error

Please wait a few minutes before you try again.

**Comment by v8u1er** [comment]
Same here. Seems like it is not related to instapy or firefox. When I navigate to anybody's profile on instagram on a browser, it says "page not found" in the title and "Please wait a few minutes before you try again" in the body of web page.

**Comment by johnvfitness** [comment]
Yes Same error :(

**Comment by jamezun** [comment]
it happens to me too, it appears after a number of likes that i performed, i guess they disable our instagram when we reach to a certain limits of likes which the parameters might be different for every accounts..

**Comment by johnvfitness** [comment]
@converge 
do you have an idea ? bro

**Comment by Pangolino2a** [comment]
Same error :I

**Comment by naldoxable** [comment]
Your account have triggered the instagram rate limiter. Try slowing down the flow

**Comment by Pangolino2a** [comment]
Thanks you so much !!!

Le mar. 27 août 2019 à 17:17, Matteo Naldoni <notifications@github.com> a
écrit :

**Comment by Zettt** [comment]
There's already an issue open for this. #4931 .

**Comment by issamarmas** [comment]
>     do this it will make it slow and safe 

```
#sleep rules !important
    session.set_action_delays(enabled=True,
                           like=30,
                           comment=29,
                           follow=71,
                           unfollow=28,
                           story=10,
                           randomize=True, random_range_from=70, random_range_to=140)
```

**Comment by lkmh** [comment]
anyone knows how long will it take to stop ?

**Comment by naldoxable** [comment]
Each day Instagram reset the server calls limit, so to be sure wait 24h

**Comment by ghost** [comment]
Same issue
