### ISSUE TITLE
Getting en error on startup

### ISSUE THREAD

**Issue by KirjoZzZ** [InstaPy/InstaPy#4947]
Hello everyone. I'm getting this error:

`._. ._. ._. ._. ._. ._. ._. ._. ._. ._. Workspace in use: "C:/Users/Administrator/InstaPy" Traceback (most recent call last): File "C:\Users\Administrator\Desktop\InstaPy\Likesstart.py", line 45, in <modu le> headless_browser=True) File "C:\Users\Administrator\Desktop\InstaPy\instapy\instapy.py", line 318, in __init__ self.logger, File "C:\Users\Administrator\Desktop\InstaPy\instapy\browser.py", line 118, in set_selenium_local_session browser.install_addon(create_firefox_extension(), temporary=True) File "C:\Users\Administrator\Desktop\InstaPy\instapy\browser.py", line 46, in create_firefox_extension with zipfile.ZipFile(zip_file, "w", zipfile.ZIP_DEFLATED, False) as zipf: File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\zipfil e.py", line 1207, in __init__ self.fp = io.open(file, filemode) OSError: [Errno 22] Invalid argument: 'C:\\Users\\Administrator\\InstaPy\\assets \\extension.xpi'`

**Comment by NooriP** [comment]
Same here

**Comment by NooriP** [comment]
@KirjoZzZ Did you find a solution ?

**Comment by NooriP** [comment]
Did anyone find a solution to this issue ?

**Comment by issamarmas** [comment]
same

**Comment by richjack888** [comment]
Just delete non-English str in you quickstart.py, I had Chinese str in hashtags and report the same error. When I delete it that fine to work.

**Comment by marcosgb** [comment]
Same here. Any solution?

**Comment by yaxum** [comment]
Could not solve it...

**Comment by jis0324** [comment]
I have same problem.
help me!
