### ISSUE TITLE
account is private

### ISSUE THREAD

**Issue by Bijiboom** [InstaPy/InstaPy#4950]
Doesnt matter what I change ... It always hit me with the "account is private" and nothing gets done?
Am I the only one or what is going on.
Thanks in advance for any help.

**Comment by mikediachenko** [comment]
@Bijiboom Hi. Could you, please, give us more info? OS used, InstaPY version, your config?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Bijiboom** [comment]
Im quit new at this and don't really know where to look that stuff up ^^
I use instapy on a Mac book air ... where can I get the other information u guys need

**Comment by ejscheepers** [comment]
> @Bijiboom Hi. Could you, please, give us more info? OS used, InstaPY version, your config?
> 
> Sent with [GitHawk](http://githawk.com)

The same thing happened to me. Linux, newest InstaPY.

**Comment by Flaunkerton2395** [comment]
I have this same problem. I observed the behavior by turning off headless browser and it seems Instapy will get to a photo then immediately to an error page. Is it possible instagram changed up something Instapy references to while trying to like and comment?
