### ISSUE TITLE
Armv6 + Raspian I'm looking for collaboration

### ISSUE THREAD

**Issue by gerfra** [InstaPy/InstaPy#4951]
## Expected Behavior
I open this discussion to clarify the installation of instapy on raspberry devices.

1. Identify your CPU Arm model https://en.wikipedia.org/wiki/Raspberry_Pi
2. From cmd line architectures **"getconf LONG_BIT" and "uname -a" or "lscpu"**

Now if you have a 32 bit like my Armv6, you can compile a 32 geckodriver but your limit is firefox-esr, because you must respect this compatibility chart!!
https://i.stack.imgur.com/vRK7K.png

In my test this configuration work: gecko version 0.18.0 with firefox 52.3.0 and selenium 3.4, but finally I think the Armv6 is very slow with InstaPy. Use other bots if you have 32bit cpu.

Anyway.
I have read many similar posts for trivial errors, it would be better to read the documentation of what you are using. The best thing to do is to use logs or better define the exact position where the programs are located. Here is an exhaustive example for linux:

`driver = webdriver.Firefox(firefox_options=options, executable_path="/home/pi/geckodriver",**firefox_profile="/home/pi/.mozilla/firefox/pnctm5ap.default"**, **log_path="/home/pi/.Log/geckodriver.log"**)`

with these logs you can find the solution to your problems.

list options avaible https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/firefox/FirefoxOptions.html

good test at all!

**Comment by mikediachenko** [comment]
@gerfra Good post 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
