### ISSUE TITLE
InstaPy on RPi 1 B+

### ISSUE THREAD

**Issue by orhan-drsn** [InstaPy/InstaPy#4952]
Hello,

I tried to install InstaPy on Raspian Lite on a RPi 1B+ (because it's useless for pther projects).
The Problem is, it can't be installed on the RPi B+ because it gets stuck during the installation.

Does anyone have any experience with the installation or a suggestion for me?

**Comment by mikediachenko** [comment]
@orhan-drsn How are you trying to install it? Via pip or from source code?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gerfra** [comment]
Before ask, read, look here https://github.com/timgrossmann/InstaPy/issues/4951

**Comment by orhan-drsn** [comment]
I tried to install with pip

**Comment by orhan-drsn** [comment]
@gerfra

From your post it is not possible with armv6, right?

**Comment by gerfra** [comment]
> @gerfra
> 
> From your post it is not possible with armv6, right?

orhan-drsn no, with the right configuration you can do it, but is very slow and you must use an older geckodriver version, older browser...... and consider Marionette compatibility... bla bla bla.
1. change bot and use one light script 4 example instabot with your Armv6
2. buy one Armv7 or v8 etc... or a 64bit architecture and run InstaPy bot
Ciao!

**Comment by orhan-drsn** [comment]
Thanks!
