### ISSUE TITLE
Can not run instapy anyway!

### ISSUE THREAD

**Issue by maziiiarkrm** [InstaPy/InstaPy#4953]
I have these logs in my terminal
when a run any class of insta py!

Workspace in use: "C:/Users/MaaaaaaaaaXXXXXxxxxx/InstaPy"
Traceback (most recent call last):
  File "D:/Projects/InstaPy-master/Test.py", line 24, in <module>
    headless_browser=True)
  File "D:\Projects\InstaPy-master\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "D:\Projects\InstaPy-master\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "D:\Projects\InstaPy-master\venv\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "D:\Projects\InstaPy-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\Projects\InstaPy-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Projects\InstaPy-master\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Projects\InstaPy-master\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by clementizard** [comment]
Found a workaround in this issue: #4923

Add on browse.py file line 81 your firefox's path.
Default should be:

firefox_options.binary = r'C:\Program Files\Mozilla Firefox\firefox.exe'

**Comment by maziiiarkrm** [comment]
@clementizard  thanks dude but after that my problem changed to down
What is this for ?! 


OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-08-27 16:38:51] [pranadevs]  Session started!
INFO [2019-08-27 16:38:51] [pranadevs]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-08-27 16:38:52] [pranadevs]  - Internet Connection Status: ok
INFO [2019-08-27 16:38:52] [pranadevs]  - Current IP is "151.239.178.245" and it's from "Iran, Islamic Republic of/IR"
INFO [2019-08-27 16:38:52] [pranadevs]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-08-27 16:39:22] [pranadevs]  - Instagram WebSite Status: Currently Up 
INFO [2019-08-27 16:39:22] [pranadevs]  - Instagram Response Time: 36.941 ms 
INFO [2019-08-27 16:39:22] [pranadevs]  - Instagram Reponse Code: 200
INFO [2019-08-27 16:39:22] [pranadevs]  - Instagram Server Status: ok
INFO [2019-08-27 16:39:22] [pranadevs]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-08-27 16:39:22] [pranadevs]  - window.navigator.webdriver response: False
INFO [2019-08-27 16:39:22] [pranadevs]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...
CRITICAL [2019-08-27 16:39:40] [pranadevs]  Unable to login to Instagram! You will find more information in the logs above.

.......................................................................................................................
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooo



INFO [2019-08-27 16:39:41] [pranadevs]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 1.01 minutes]
INFO [2019-08-27 16:39:41] [pranadevs]  Session ended!

Process finished with exit code 0

**Comment by yuricroci** [comment]
I have the same problem of @maziiiarkrm 
thanks in advance for any answer

**Comment by maziiiarkrm** [comment]
@merboy hi bro
i fixed it
download dev branch in instaPy and make the change @clementizard  said in second message of this issue
it will work :)

**Comment by merboy** [comment]
Hi @maziiiarkrm , I should repeat the update?

**Comment by jonap339** [comment]
Instagram is blocking accounts that use bots. Already blocked me 3. My clients are not happy at all.

**Comment by Tr1pke** [comment]
> Instagram is blocking accounts that use bots. Already blocked me 3. My clients are not happy at all.

Tell them they are a bunch of ungrateful **** and that they should be happy with a free open source instagram bot.

**Comment by jonap339** [comment]
Hahaha, of course, the responsibility is mine, we agree with that. We all know the risk you run. Only no one intends to use the bot to block their accounts;)

**Comment by Tr1pke** [comment]
They got free followers they don’t have any right to complain
