### ISSUE TITLE
Story view enhancements?

### ISSUE THREAD

**Issue by tiaringhio** [InstaPy/InstaPy#4955]
Hi guys, first of all i'd like to thank you for the amazing work you've done so far, what you've achieved is truly great!
Next up, why i'm writing this feature request.

Today i came across an interesting website (it's Italian):
https://www.instaviews.it/

This tool allows to see hundreds of thousands of stories to better interact with users and possibily increasing the account interactions, there are three plans, the difference between them is just about the numbers. What i was wondering is: since there's already a feature for stories viewing, could it be possible to enhance it with the objective of acheiving the same numbers as the service linked above?
Thank you for your attention.

**Comment by uni1783** [comment]
That's already possible I think. Here's my relevant config:

```
with smart_run(session):
  following_list = session.grab_following(username="my_username", amount="full", live_match=True, store_locally=True)
  like_tags=(['natgeo', 'world', 'pizza'])

  session.set_do_story(enabled = True, percentage = 95, simulate = True)
  session.story_by_users(following_list)
  session.story_by_tags(like_tags)
```

**Comment by tiaringhio** [comment]
The problem is that it will do max 20 stories per hashtag, to able to reach the numbers I was talking about I would need thousands of hashtags, which would theoretically be possibile but after a certain number they’d become dissimilar to the first hashtag.
Thank you for your settings though!

**Comment by Velvet2045** [comment]
The function is the same but you can't post at the same speed. If you want to see 500,000 stories a day, you need to request 600 posts per a minute to the server. However, on a typical network environment, the chances of hitting the rate limit are very high.

**Comment by PiratesGomez** [comment]
What about to **watch the story**, **like_by_tags** and **set_do_follow**, all at the same time?
