### ISSUE TITLE
Error: all Following option is not working at the moment, leaving...

### ISSUE THREAD

**Issue by panchoma** [InstaPy/InstaPy#4957]
Hi there! 

When I try to use the  Unfollow method: "unfollow, regardless of a user follows you or not", the following error appears:

> all Following option is not working at the moment, leaving...

I don't know if something is wrong with my quickstart code or if this function is not activated for the new update yet. 

Do someone know anything about this method of Unfollow?

Thanks!

@uluQulu, @timgrossmann, @CharlesCCC , @Mr-HaleYa 

## Expected Behavior
Unfollow all users, regardless of a user follows you or not.

## Current Behavior

> ERROR [2019-08-27 13:15:16] [User]  Error occurred while generating a user list from the followed pool!
>         b"[Errno 2] No such file or directory: 'C:\\\\Users\\\\User\\\\...\\\\...\\\\...\\\\InstaPy\\\\logs\\\\...\\\\..._followedPool.csv'"
> INFO [2019-08-27 13:15:16] [...]  Unfollowing the users you are following
> WARNING [2019-08-27 13:15:16] [...]  all Following option is not working at the moment, leaving...
> INFO [2019-08-27 13:15:16] [...]  --> Total people unfollowed : 0

## InstaPy configuration
```
""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy.util import smart_run
import time
import os
import random
from instapy import Settings
from instapy import InstaPy
from instapy import set_workspace

# Carpeta
set_workspace("C:\\Users\\...\\InstaPy\\")

# login credentials
insta_username = '...'
insta_password = '...!'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  page_delay=25,
                  disable_image_load=True)

#Database
Settings.database_location = "./db/instapy_{}.db".format(insta_username)

with smart_run(session):
    """ Activity flow """
    # general settings

    # whitelist
    session.set_dont_include(["User1"])

    session.set_quota_supervisor(enabled=True, sleep_after=["unfollows"], sleepyhead=True, stochastic_flow=True, notify_me=False,
                                 peak_unfollows_hourly=20,
                                 peak_unfollows_daily=200,
                                 peak_server_calls_hourly=200,
                                 peak_server_calls_daily=2500)

    session.set_action_delays(enabled=True, unfollow=30, randomize=True, random_range_from=86, random_range_to=114, safety_match=False)

    # activity

    for cycle in range(5):
        print("\n\nLOOP {}\n".format(cycle+1))

        session.unfollow_users(amount=5, allFollowing=True, style="RANDOM", unfollow_after=0*60*60, sleep_delay=0)

        time.sleep(150) #take a 50 seconds of break after finishing the feature above

    session.end()


```

**Comment by tunidev** [comment]
same here

**Comment by Jostino** [comment]
same here

**Comment by korialstratz** [comment]
same too

**Comment by Segfaultd** [comment]
Same here
