### ISSUE TITLE
Raspberries pi no work under pressure

### ISSUE THREAD

**Issue by mathmorrison** [InstaPy/InstaPy#496]
The pressure of High and temperature are infernal along with the raspberries I can not use any king of coomend the use it won't load because I think the power surge is efficient although not too much like the other I've seen the community users uses used to feed the power to this beast.

It only opens the chrome or the fox on fire no deal no work no followers.
@timgrossmann @calvinclaus @ahmadudin @gitpatrickhub @CodeMaster1 @bernardogo @vitormvasc

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
