### ISSUE TITLE
Message: Reached error page: 

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#4960]
> Traceback (most recent call last):
> File "InstaPy/steven.py", line 54, in <module>
> session.like_by_tags(['x','x','x','x','x','x','x','x_x','x'], amount=20)
> File "/home/steven/.local/lib/python3.7/site-packages/instapy/instapy.py", line 1943, in like_by_tags
>   liked_img,
> File "/home/steven/.local/lib/python3.7/site-packages/instapy/like_util.py", line 760, in like_image
>   if total_liked_img % 10 == 0 and not verify_liked_image(browser, logger):
> File "/home/steven/.local/lib/python3.7/site-packages/instapy/like_util.py", line 784, in verify_liked_image
>   browser.refresh()
> File "/home/steven/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 831, in refresh
>   self.execute(Command.REFRESH)
> File "/home/steven/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>   self.error_handler.check_response(response)
> File "/home/steven/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=https%3A//www.instagram.com/p/B1tjnHXoMg_/&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20www.instagram.com.
> 

They changed a button/link

**Comment by tobimate** [comment]
Same problem. Thanks for helping.

**Comment by issamarmas** [comment]
same

**Comment by issamarmas** [comment]
so what we have to do ?

**Comment by Jostino** [comment]
```
Traceback (most recent call last):
  File "/root/InstaPy/assets/onesimo.py", line 35, in <module>
    session.like_by_tags(['boxe', 'boxing', 'boxingday', 'boxeo', 'boxinglife', 'coaching', 'coach', 'fit', 'fitness'], amount=20, skip_top_posts=True)
  File "/root/.local/lib/python3.7/site-packages/instapy/instapy.py", line 1941, in like_by_tags
    web_address_navigator(self.browser, link)
  File "/root/.local/lib/python3.7/site-packages/instapy/util.py", line 1184, in web_address_navigator
    browser.get(link)
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/root/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=nssFailure2&u=https%3A//www.instagram.com/p/B2O2gXPHtuH/&c=UTF-8&f=regular&d=The%20connection%20to%20www.instagram.com%20was%20interrupted%20while%20the%20page%20was%20loading.

```

My script just ended with this error, I think it's correlated to this issue

**Comment by turtlebking** [comment]
every 10 liked images, the page will be refresh for checking on the 'Block on likes'.
if the page did not load up as it should be (ie. error page), the script may break.
This routine (10 liked images & refresh) leaves a trace of Bot activity which is very easy pick up by instagram.  May be we can try add a random range for that. Let me know if it works.

in like_util.py, at lines 762
From
```
            # after every 10 liked image do checking on the block
            if total_liked_img % 10 == 0 and not verify_liked_image(browser, logger):
                return False, "block on likes"

            return True, "success"
```

change to:
```
            # after every 5-20 liked image do checking on the block
            like_image_chk = random.randint(5,20)
            if total_liked_img % like_image_chk == 0 and not verify_liked_image(browser, logger):
                return False, "block on likes"

            return True, "success"
```

**Comment by Jostino** [comment]
> every 10 liked images, the page will be refresh for checking on the 'Block on likes'.
> if the page did not load up as it should be (ie. error page), the script may break.
> This routine (10 liked images & refresh) leaves a trace of Bot activity which is very easy pick up by instagram. May be we can try add a random range for that. Let me know if it works.
> 
> in like_util.py, at lines 762
> From
> 
> ```
>             # after every 10 liked image do checking on the block
>             if total_liked_img % 10 == 0 and not verify_liked_image(browser, logger):
>                 return False, "block on likes"
> 
>             return True, "success"
> ```
> 
> change to:
> 
> ```
>             # after every 5-20 liked image do checking on the block
>             like_image_chk = random.randint(5,20)
>             if total_liked_img % like_image_chk == 0 and not verify_liked_image(browser, logger):
>                 return False, "block on likes"
> 
>             return True, "success"
> ```

Ok then, I've done the fix on mine RaspBi3+ I will let you now!

**Comment by turtlebking** [comment]
at the time when instagram block likes, the page refresh layout will be different from before.
mobile layout -> desktop layout
from my emulator mobile layout, i can not see the like/unlike button there
but when i expand it to full screen, it is there.
seems like the desktop layout won't adjust to other screen size.

**Comment by Nadorozhnyy** [comment]
Message: Reached error page: about:neterror?e=nssFailure2&u=https%3A// have this problem,
