### ISSUE TITLE
Unknow Error Login

### ISSUE THREAD

**Issue by herisna** [InstaPy/InstaPy#4962]
## Unknow Error Login

Hi all, I'm newbie. please help me it showed like this now, I'm using windows:

`D:\InstaPy\InstaPy-master>python quickstart.py --headless-browser

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/User/InstaPy"

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-29 11:32:12] [xxxxxxxxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-08-29 11:32:12] [xxxxxxxxx]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-08-29 11:32:13] [xxxxxxxxx]  - Internet Connection Status: ok
INFO [2019-08-29 11:32:13] [xxxxxxxxx]  - Current IP is "192.168.xxx.xxx" and it's from "xxxxxxxx"
INFO [2019-08-29 11:32:13] [xxxxxxxxx]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-08-29 11:32:20] [xxxxxxxxx]  - Instagram WebSite Status: Currently Up
INFO [2019-08-29 11:32:20] [xxxxxxxxx]  - Instagram Response Time: 35.804 ms
INFO [2019-08-29 11:32:20] [xxxxxxxxx]  - Instagram Reponse Code: 200
INFO [2019-08-29 11:32:20] [xxxxxxxxx]  - Instagram Server Status: ok
INFO [2019-08-29 11:32:20] [xxxxxxxxx]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-08-29 11:32:20] [xxxxxxxxx]  - window.navigator.webdriver response: False
INFO [2019-08-29 11:32:20] [xxxxxxxxx]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

........................................................................................................................
CRITICAL [2019-08-29 11:32:37] [xxxxxxxxx]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2019-08-29 11:32:39] [xxxxxxxxx]  Sessional Live Report:
        |> No any statistics to show

[Session lasted 43.2 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-29 11:32:39] [xxxxxxxxx]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo`

**Comment by kerogenesis** [comment]
Same problem :(

**Comment by its0x08** [comment]
same here !!!

**Comment by westworldcj** [comment]
I installed from the dev clone and it seem to fix that. run your browser when you do it and see what happens

**Comment by bvanhou** [comment]
It’s a thing with the headless browser. Which makes things difficult when you want to automate it.

I believe it’s related to my response here:
https://github.com/timgrossmann/InstaPy/issues/4958

**Comment by herisna** [comment]
> It’s a thing with the headless browser. Which makes things difficult when you want to automate it.
> 
> I believe it’s related to my response here:
> #4958

i tried already, and still same :(

**Comment by bvanhou** [comment]
@herisna What did you try? Did you review my response in the post I referenced? The solution I have come up with works very well, though I haven't posted the code yet as its more to do with the cloud implementation

**Comment by cezareremia** [comment]
Hey,
I understand what creates this error and it's silly.

When starting up your quickstart.py script the code does some checks:
Internet connection ? --- it goes to google.com and loads it up stuff like that.
One of the these steps are : Is instagram online ? and they load up https://isitdownorjust.me/

And quite simply, what happens every time you base the working of your code on external sites and apps and code ... sometimes the site is down... like right now. That kills the instapy script.
![image](https://user-images.githubusercontent.com/54893147/64251091-598fa500-cf20-11e9-849f-1521e390cceb.png)

**Comment by cezareremia** [comment]
Also if you want to bypass this error while the site is down, what I did was just go to : instapy/login_util.py and comment out the **Instagram Server Status** try/except step. 
That fixes it!
