### ISSUE TITLE
window.navigator.webdriver response: False

### ISSUE THREAD

**Issue by CamiloB** [InstaPy/InstaPy#4966]
## Expected Behavior
The bot does not start
## Current Behavior
  -- Connection Checklist [1/3] (Internet Connection Status)
 - Internet Connection Status: ok
[kingrambot]  - Current IP is "xxxxx" and it's from "Colombia/CO"
 -- Connection Checklist [2/3] (Instagram Server Status)
 - Instagram WebSite Status: Currently Up 
 - Instagram Response Time: 38.631 ms 
  - Instagram Reponse Code: 200
 - Instagram Server Status: ok
  -- Connection Checklist [3/3] (Hide Selenium Extension)
 - window.navigator.webdriver response: False
  - Hide Selenium Extension: ok
## Possible Solution (optional)
https://github.com/timgrossmann/InstaPy/pull/4892/files/503192b9604c58308fb53a4d56161ec997c3bd73#diff-25f3e8aeae2acd69dc243945588dfff9 

but i dont know how to implement it
## InstaPy configuration
its the quickstart.py

**Comment by FeatherKamisori** [comment]
Same issue.

**Comment by apostolescus** [comment]
me too

**Comment by erezacohen** [comment]
Same.
Running on Raspbian GNU/Linux 10 (buster), headless.

**Comment by plastikmind** [comment]
is anyone try to update instapy? things changed in the last update. how are you guys? who has a problem?

**Comment by CamiloB** [comment]
hi guys i already found the solution if you update with @dev repo worked.
pip install -U git+https://github.com/timgrossmann/InstaPy@dev now is working just fine

**Comment by SprezzaturaV** [comment]
It seems to me, that this issue is coming back. While on OS X(Catalina) it kind of works fine, but on my RaPi I geht the Error: window.navigaor.webdriver response: False. And actions - even with me using the mouse - are blocked.
