### ISSUE TITLE
Tor Browser?

### ISSUE THREAD

**Issue by Fid999** [InstaPy/InstaPy#4967]
Is there a way of using Tor Browser on Linux instead of Firefox via Geckodriver?

Firefox keep getting blocked for me.

**Comment by hijak** [comment]
if you think tor will help you in this situation you are wrong

**Comment by Fid999** [comment]
What will help then?

**Comment by westworldcj** [comment]
Instagram is blocking bots. I tried a couple other bots i have off my android phone and my mac and same thing

**Comment by hijak** [comment]
the bots keep hitting a 429 http code from instagram which is rate limiting 
try to give it a rest for a couple of days and then reintroduce the bot with action delays of about 20 secs see if that helps
