### ISSUE TITLE
error running

### ISSUE THREAD

**Issue by issamarmas** [InstaPy/InstaPy#4968]
i tried every single thing .. can you help please

Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py 

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/M/InstaPy"
Traceback (most recent call last):
  File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 30, in <module>
    headless_browser=True)
  File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 318, in __init__
    self.logger,
  File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

>>>

**Comment by issamarmas** [comment]
> i tried every single thing .. can you help please
> 
> Python 3.7.4 (tags/v3.7.4:e09359112e, Jul 8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
> Type "help", "copyright", "credits" or "license()" for more information.
> 
> > > >
> 
> RESTART: C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py
> 
> ._. ._. ._. ._. ._. ._. ._. ._.
> Workspace in use: "C:/Users/M/InstaPy"
> Traceback (most recent call last):
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 30, in 
> headless_browser=True)
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 318, in **init**
> self.logger,
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
> options=firefox_options,
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in **init**
> keep_alive=True)
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
> 
> > > >

**Comment by issamarmas** [comment]
> i tried every single thing .. can you help please
> 
> Python 3.7.4 (tags/v3.7.4:e09359112e, Jul 8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
> Type "help", "copyright", "credits" or "license()" for more information.
> 
> > > >
> 
> RESTART: C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py
> 
> ._. ._. ._. ._. ._. ._. ._. ._.
> Workspace in use: "C:/Users/M/InstaPy"
> Traceback (most recent call last):
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 30, in 
> headless_browser=True)
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 318, in **init**
> self.logger,
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
> options=firefox_options,
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in **init**
> keep_alive=True)
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
> 
> > > >

**Comment by J3store** [comment]
> > i tried every single thing .. can you help please
> > Python 3.7.4 (tags/v3.7.4:e09359112e, Jul 8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
> > Type "help", "copyright", "credits" or "license()" for more information.
> > > > >
> > 
> > 
> > RESTART: C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py
> > ._. ._. ._. ._. ._. ._. ._. ._.
> > Workspace in use: "C:/Users/M/InstaPy"
> > Traceback (most recent call last):
> > File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 30, in
> > headless_browser=True)
> > File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 318, in **init**
> > self.logger,
> > File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
> > options=firefox_options,
> > File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in **init**
> > keep_alive=True)
> > File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in **init**
> > self.start_session(capabilities, browser_profile)
> > File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
> > response = self.execute(Command.NEW_SESSION, parameters)
> > File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> > self.error_handler.check_response(response)
> > File "C:\Users\M\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> > raise exception_class(message, screen, stacktrace)
> > selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
> > > > >

@issamarmas any solution?
