### ISSUE TITLE
^ SyntaxError: invalid syntax . username: str = None

### ISSUE THREAD

**Issue by thankmelater23** [InstaPy/InstaPy#4974]
## Current Behavior
Traceback (most recent call last):
  File "belize-lottery.py", line 3, in <module>
    from instapy import InstaPy
  File "/Users/AndreVillanueva_Com/Dropbox/bots/InstaPy/instapy/__init__.py", line 3, in <module>
    from .instapy import InstaPy
  File "/Users/AndreVillanueva_Com/Dropbox/bots/InstaPy/instapy/instapy.py", line 104
    username: str = None,
            ^
SyntaxError: invalid syntax

**Comment by carmenhchung-zz** [comment]
+1 on having this error

**Comment by thankmelater23** [comment]
> +1 on having this error

Are you having the same issue?

**Comment by carmenhchung-zz** [comment]
> Are you having the same issue?

Yes - using the latest version that I just downloaded today. I haven't seen this error on any of the previous versions though.

**Comment by marius93rm** [comment]
you are using Python 🐍 2 instead of Python 🐍 3

**Comment by nocomment-bln** [comment]
I got the same problem after using git pull :( any fixes ?

**Comment by thankmelater23** [comment]
So I just have to delete python 2??  Is there anything I should be worried about when deleting python 2? 

Thank you!

**Comment by naldoxable** [comment]
Im facing the same issue, it works on laptop but not on my desktop. seems some libraries missing maybe

**Comment by thankmelater23** [comment]
i put this code into my quickstart and it worked . Its something to do witht he workspace.


`from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace
from instapy import get_workspace

set_workspace(path= None)

session = InstaPy(username="abc", password="123")

with smart_run(session):
  # lots of code
  workspace_in_use = get_workspace()
  print(workspace_in_use["path"])
# code code
`

**Comment by thankmelater23** [comment]
`
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace
from instapy import get_workspace

set_workspace(path= None)

session = InstaPy(username="abc", password="123")

with smart_run(session):
  workspace_in_use = get_workspace()
  print(workspace_in_use["path"])
`

**Comment by naldoxable** [comment]
Nope, it dosn't help

**Comment by nocomment-bln** [comment]
same here. it does not work :( who can finally help us ? :(

**Comment by naldoxable** [comment]
Found the fix for me. **JUST download and install firefox :)**

**Comment by nocomment-bln** [comment]
another solution anybody ? :/

**Comment by nycrom** [comment]
Same problem here :(

**Comment by derryberni** [comment]
same problem +1

**Comment by JennaDoll** [comment]
Same issue for months, can someone please help or direct us in anyway. Much appreciated. @timgrossmann

**Comment by Archax** [comment]
**FIX**
try  `python3 quickstart.py` 
after that install clarifai and another packages  `pip3 clarifai` 
InstaPy use python 3 version)

**Comment by nbhankes** [comment]
I went into the "mac.start.command" file and changed the last line from "python quickstart.py" to "python3 quickstart.py"
