### ISSUE TITLE
follow just 10 from user's followers

### ISSUE THREAD

**Issue by issamarmas** [InstaPy/InstaPy#4976]
## Expected Behavior
following all user's followers
## Current Behavior
following only first 10 user's followers & return "Session ended!"

## InstaPy configuration
    session.follow_user_followers(['hinatas.chakra', 'kitsunekohime', 'iiiiclothing'], randomize=False)
    session.follow_user_followers(['iiiiclothing'], amount=20, randomize=False, sleep_delay=60)
![Capture](https://user-images.githubusercontent.com/40734509/64056598-c14a9680-cb94-11e9-8416-76deec99e5bf.JPG)

**Comment by issamarmas** [comment]
anyone have the same problem?!

**Comment by ghost** [comment]
Got banned for only 10...

**Comment by issamarmas** [comment]
> Got banned for only 10...

change the version
