### ISSUE TITLE
Want to skip likes and do comments. PLEASE Help

### ISSUE THREAD

**Issue by MalinowskiR** [InstaPy/InstaPy#4977]
I'm using this code:

with smart_run(session):
    """ Activity flow """
    # settings
    session.set_relationship_bounds(enabled=True,
                                      delimit_by_numbers=True,
                                       max_followers=10500,
                                        min_followers=10,
                                        min_following=10)
    
    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])
    
    
    # actions
    session.set_do_comment(enabled=True, percentage=100)
    session.set_do_like(enabled=True, percentage=100)
    session.set_comments(['świetne zdjęcie! @{}',
        'Masz super profil! @{}',
        '@{} Super!',
        'Uwielbiam Twoje posty @{}',
        'Świetne ujęcie @{}',
        'Super to wygląda @{}',
        'Zaje...cie!!! @{}',
        'Obłęd @{}',
        'Genialnie @{}',
        'Perfekcja!',  
        ':muscle: :muscle: :muscle: @{}',
        ':raised_hands: Mistrz!',
        ':fire: Ogień!',
        'kozak!',                   
        '@{}:fire::fire::fire:'])
    session.like_by_tags(["sklepfuria"], amount=5)
    
everything is working fine on my second acount but on the first one i got blocked on likes so bot 
 is turning off without comment. 
I get this:
-------- WARNING! Image was NOT liked! You are have a BLOCK on likes!

But I wish to put comment without likes
tried this:

   session.set_do_like(enabled=True, percentage=0)

and this:

   session.set_do_like(enabled=False, percentage=100)

but nothing seems to skip likes. Got warning and its turning off without comments.

PLEASE HELP

**Comment by Immelstorn** [comment]
I was actually trying to do the same and also failed. Anybody knows how to do comments without likeks?
