### ISSUE TITLE
Comments are not visible on mobile

### ISSUE THREAD

**Issue by dudiqo** [InstaPy/InstaPy#4980]
Hi, I noticed some weird behavior and I am wondering if this is how it should work. 

So the bot seems to be running OK, when I check the links where the comments were posted in a different browser on the desktop they show up as expected, but when I look for the commented image manually on mobile (in Instagram App), it shows me that there is e.g. 1 comment but when I click on it to read it, nothing shows up. It's like the comment is not really posted.

Does someone know why is this happening? And if this is correct behavior?

**Comment by 21spock** [comment]
Hey! I am having this same issue. It seems like instagram can tell if a bot is commenting and limits comments once the bot has reached the post that it wants to comment on. 
You can verify this by going in the app and checking the post while the bot is attempting to comment on it. 
Instagram is getting very smart and we have to do something to make our actions seem less bot like.
