### ISSUE TITLE
use_firefox=True, script don't works with firefox

### ISSUE THREAD

**Issue by Arcdorian** [InstaPy/InstaPy#4981]
Hi,

Even when I put the geckodriver in the folder python 37-32, the program have an error with firefox launching

here is the code:

`session = InstaPy(username='', password='', use_firefox=True)`

Here is the error message:

`Exception has occurred: TypeError
__init__() got an unexpected keyword argument 'use_firefox'
  File "C:\Users\doria\OneDrive\Python Loris\Instapy\quickstart.py", line 13, in <module>
    session = InstaPy(username='', password='', use_firefox=True)`

Thanks a lot for your answer  :)

**Comment by lopjf** [comment]
Same problem for me, I got :
`TypeError: __init__() got an unexpected keyword argument 'use_firefox'`

The weird thing is that when I get rid of the `use_firefox=True` in the session, it works just fine and run the firefox web browser.

**Comment by mwargan** [comment]
Firefox is the default browser since InstaPy 0.6.0, and Chrome is no longer available; you can/should omit `use_firefox` in the constructor.

**Comment by breuerfelix** [comment]
solved :)

**Comment by meko137** [comment]
How did you solved it ? I got the same problem since instapy 0.6.0

**Comment by codewithnick** [comment]
update instapy to lastest version

**Comment by breuerfelix** [comment]
`use_firefox` simply does not exist anymore. instapy only runs with firefox :) there are not alternatives.  
although i might create a new branch to test a patched chromedriver version
