### ISSUE TITLE
0.6.3 - Problems with following

### ISSUE THREAD

**Issue by yuricroci** [InstaPy/InstaPy#4983]
I have updated with 0.6.3 but when I do following the message is always the same:

INFO [2019-09-01 13:03:55] [xxxx]  Ongoing Follow [2/30]: now following 'yy'...
WARNING [2019-09-01 13:04:35] [xxxx]  Last follow is not verified.   ~'xxxx' might be temporarily blocked from following

but I have verified that I have not the actions blocked.

Any idea to solve the problem?

**Comment by yuricroci** [comment]
I understood where is the problem.
The latest version of Instapy, use emulation and when instapy verify following, it should check directly xpath of follow_span_XP_following, but it doesn't .

Could you have a look to this problem?

**Comment by spikeyhair** [comment]
I notice that whenever i see "Last follow is not verified" then I go to check the user manually (from the same server that the bot is running) using the browser, it was followed successfully by the bot actually.

**Comment by yuricroci** [comment]
it's the same that I have noticed @spikeyhair  , the problem is in unfollow_util.py when in the code try to identify the following button. The code, in the emulation mode, should enter in NoSuchElementException, but it doesn't

```
try:
        browser.find_element_by_xpath(
            read_xpath(get_following_status.__name__, "follow_button_XP")
        )
        follow_button_XP = read_xpath(get_following_status.__name__, "follow_button_XP")
    except NoSuchElementException:
        try:
            follow_button = browser.find_element_by_xpath(
                read_xpath(get_following_status.__name__, "follow_span_XP_following")
            )
            return "Following", follow_button
        except:
            return "UNAVAILABLE", None
```

**Comment by spikeyhair** [comment]
Another worry is that, it didn't count towards the follower counter. This might affect the accuracy of quota supervisor on the follower limit that I set. 

Let's say I set the hourly limit as 10, after following 10 but failed verification, then it will continue to follow again and over the limit set. I worry IG will block me again if I keep on following like this.

**Comment by yuricroci** [comment]
yes!! but nobody is answering :(

**Comment by tunidev** [comment]
Same issue. It's a false positive message

**Comment by Tr1pke** [comment]
> Another worry is that, it didn't count towards the follower counter. This might affect the accuracy of quota supervisor on the follower limit that I set.
> 
> Let's say I set the hourly limit as 10, after following 10 but failed verification, then it will continue to follow again and over the limit set. I worry IG will block me again if I keep on following like this.

it also does not add to the followedPool so unfolling after with the command InstaPyFollowed=True will not work ...

**Comment by tunidev** [comment]
@Tr1pke did you fix that ?

**Comment by fgisslen** [comment]
If you put a sleep the first thing in:
def verify_action(
    browser, action, track, username, person, person_id, logger, logfolder
):

it will work

**Comment by fgisslen** [comment]
Like sleep(15)

**Comment by yuricroci** [comment]
thanks @fgisslen  , I will try with this

**Comment by yuricroci** [comment]
good, I have modified as you suggest and it works, but after 4 follow actions, ig has blocked my actions

**Comment by fgisslen** [comment]
@merboy Okay, I don't know why.
Are you doing a lot of other actions?

**Comment by yuricroci** [comment]
no, only these actions, I have stopped every king of f/u since 10th of August

**Comment by sharmanshah** [comment]
+1

The issue isn't solved in 0.6.4. When I disable headless mode, I can see the account getting followed in Firefox but Instapy shows:

WARNING [2019-09-19 19:26:17] [myAccount]  Last follow is not verified.	~'myAccount' might be temporarily blocked from following.

The follow is not getting added to the followed pool either.

**Comment by vinigabriel** [comment]
+1 from me

**Comment by ortegafernando** [comment]
Hi, I have the same problem. It is also appears in https://github.com/timgrossmann/InstaPy/issues/5034

Does anybody has a good solution?

**Comment by Dacaramo** [comment]
same problem in 2020, it still doesnt work, any fixes yet guys?

**Comment by BuZZy1337** [comment]
@Dacaramo @ortegafernando https://github.com/timgrossmann/InstaPy/issues/5305#issuecomment-659684494
