### ISSUE TITLE
Issue with first time running on debian - Selenium

### ISSUE THREAD

**Issue by elrazez** [InstaPy/InstaPy#4985]
## Expected Behavior
To start Instapy from Quickstart.py

## Current Behavior
results like this. tried everything:

root@berbidvps:~# cd Instapy-quickstart
root@berbidvps:~/Instapy-quickstart# python3 quickstart.py
InstaPy Version: 0.6.2
 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 19, in <module>
    disable_image_load=True)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 321, in __init__
    self.logger,
  File "/usr/local/lib/python3.5/dist-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

## InstaPy configuration

!/usr/bin/python
 -*- coding: utf8 -*-

 imports
import os, sys
from instapy import InstaPy
from instapy import smart_run
import random

 login credentials
insta_username = 'xxxxxx'
insta_password = 'xxxxxx'

.get an InstaPy session!
 set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True)

with smart_run(session):

    general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=2000,
                                    min_followers=80,
                                    min_following=50)

    session.set_skip_users(skip_private=False,
                           private_percentage=0,
                           skip_no_profile_pic=True,
                           no_profile_pic_percentage=100,
                           skip_business=True,
                           skip_non_business=False,
                           business_percentage=100)

    session.set_quota_supervisor(enabled=True, sleep_after=["likes_h", "follows_h", "unfollows_h", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=False,
                                 peak_likes=(random.randint(24, 36), 850),
                                 peak_follows=(random.randint(28, 40), None),
                                 peak_unfollows=(22, 505),
                                 peak_server_calls=(random.randint(475, 525), None))

    session.set_do_follow(enabled=True, percentage=100)
    session.set_do_like(enabled=True, percentage=75)
    session.set_smart_hashtags(
        [u'گرافیک','هویت_بصری'], limit=5, sort='top', log_tags=True)

     activities
    session.follow_likers(['studiokargah', 'roozrang'], photos_grab_amount=30,
                          follow_likers_per_photo=10, randomize=True, interact=False)
    session.like_by_tags(amount=200, use_smart_hashtags=True)

    session.unfollow_users(amount=100, InstapyFollowed=(True),
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=601)

So how can i fix this?

**Comment by elrazez** [comment]
Found a solution.
Install Firefox using this page: https://wiki.debian.org/Firefox

**Comment by swang45** [comment]
Hello, I am experiencing the same problem as you do. however, I am not sure when shall I install the Firefox. Or which step shall I do it?
Thank you so much for your help!

**Comment by elrazez** [comment]
> Hello, I am experiencing the same problem as you do. however, I am not sure when shall I install the Firefox. Or which step shall I do it?
> Thank you so much for your help!

 it doesn't matter when you install it.
