### ISSUE TITLE
Not able to use chrome because use_firefox parameter is gone

### ISSUE THREAD

**Issue by octavius-1** [InstaPy/InstaPy#4986]
Right now, after updating to latest version, use_firefox parameter is gone, forcing us to use Firefox without asking, how can I set chrome as my default browser again? I already had a cookie setup completely up and running FOR CHROME. 
Could anyone help?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mwargan** [comment]
@octavius-1 Since version 0.6.0 Chrome is no longer available, and Firefox is the default browser.
