### ISSUE TITLE
ERROR : extension.xpi

### ISSUE THREAD

**Issue by issamarmas** [InstaPy/InstaPy#4988]
i get this error when i run it
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/M/InstaPy"
Traceback (most recent call last):
  File "e:/Djanget/InstaPy-master/quickstart.py", line 16, in <module>
    headless_browser=False)
  File "e:\Djanget\InstaPy-master\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "e:\Djanget\InstaPy-master\instapy\browser.py", line 118, in set_selenium_local_session
    browser.install_addon(create_firefox_extension(), temporary=True)
  File "e:\Djanget\InstaPy-master\instapy\browser.py", line 46, in create_firefox_extension
    with zipfile.ZipFile(zip_file, "w", zipfile.ZIP_DEFLATED, False) as zipf:
  File "C:\Paython3\lib\zipfile.py", line 1207, in __init__
    self.fp = io.open(file, filemode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\M\\InstaPy\\assets\\extension.xpi'

**Comment by issamarmas** [comment]
it was fine .. i didn't change anything

**Comment by richjack888** [comment]
Just delete non-English str in you quickstart.py, I had Chinese str in hashtags and report the same error. When I delete it that fine to work.

**Comment by NooriP** [comment]
@richjack888 Can you explain because i have the same error and i don't have non english str 
Thank you

**Comment by issamarmas** [comment]
> Just delete non-English str in you quickstart.py, I had Chinese str in hashtags and report the same error. When I delete it that fine to work.

no i don't have any kind of that

**Comment by richjack888** [comment]
@NooriP @issamarmas 
If you guys still have problems just change quickstart.py.
Here are some templates：
https://github.com/InstaPy/instapy-quickstart/tree/master/quickstart_templates
after changed if still not working, I don't know either.

**Comment by GitNees** [comment]
delete extension.xpi, that helped for me to get further.

**Comment by issamarmas** [comment]
> delete extension.xpi, that helped for me to get further.

hell yeaah works    .... thanks

**Comment by issamarmas** [comment]
> @NooriP @issamarmas
> If you guys still have problems just change quickstart.py.
> Here are some templates：
> https://github.com/InstaPy/instapy-quickstart/tree/master/quickstart_templates
> after changed if still not working, I don't know either.

thank you too 

> @NooriP @issamarmas
> If you guys still have problems just change quickstart.py.
> Here are some templates：
> https://github.com/InstaPy/instapy-quickstart/tree/master/quickstart_templates
> after changed if still not working, I don't know either.
thank you i was lokking for these too

**Comment by spacemishka** [comment]
i have the same issue. I figured out that it is not possible to install this plugin. When you try it manually, it will fail, because it is not signed. It will either fail, if you turn of the verification it a addon is signed or not.

I am on W10

**Comment by Yomonger** [comment]
[problem solved]
I've found an easy way to deal with that issue.
just drag the extension.xpi in directory:

C:\Users\user\InstaPy\assets 
and place it in...
C:\Users\user\Downloads\InstaPy-master\instapy\firefox_extension

DO NOT COPY THE FILE!
you will have do that every time you face this issue.

Just change the name of the extension.xpi in the directory (firefox_extension) before you drag the new one from (assets)

in my case I named it extension1.xpi... you will just have to give a it nieuw number everytime
I have like 4 of time in the firefox_extension folder. Starting from 1 to 4.
and next one will be called 5.

Well that was it. Pretty easy right.
I really hope this can help you like it helped me!

Much love to y'all

**Comment by roberterzen** [comment]
> I really hope this can help you like it helped me!

It did indeed.
Thanks for digging log files and sharing the solution.

**Comment by roberterzen** [comment]
If anyone still have this problem...
... here is what I did.
I have multiple accounts on which InstaPy is running.
Use 
`from instapy import set_workspace`
and different 
`set_workspace(path='PATH_TO_INSTAGRAM_ACCOUNT_WORKSPACE')`
PATH_TO_INSTAGRAM_ACCOUNT_WORKSPACE should be different for each account.

**Comment by Jasiri-w** [comment]
> [problem solved]
> I've found an easy way to deal with that issue.
> just drag the extension.xpi in directory:
> 
> C:\Users\user\InstaPy\assets
> and place it in...
> C:\Users\user\Downloads\InstaPy-master\instapy\firefox_extension
> 
> DO NOT COPY THE FILE!
> you will have do that every time you face this issue.
> 
> Just change the name of the extension.xpi in the directory (firefox_extension) before you drag the new one from (assets)
> 
> in my case I named it extension1.xpi... you will just have to give a it nieuw number everytime
> I have like 4 of time in the firefox_extension folder. Starting from 1 to 4.
> and next one will be called 5.
> 
> Well that was it. Pretty easy right.
> I really hope this can help you like it helped me!
> 
> Much love to y'all

Thank You very much,
   however I had to tweak my solution slightly as my firefox_extension directory was not the same as what you supplied (possibly since I was not using a python environment). So for anyone still experiencing issues, search (I used a program called search Everything) to find your specific firefox_extension directory and follow the same instructions of moving and renaming the extension.api file. 

Mine was in:
 C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\firefox_extension

**Comment by EPkravec** [comment]
> PATH_TO_INSTAGRAM_ACCOUNT_WORKSPACE

what do you mean by this (login, password in a separate fault, or is this the path to the browser?)

**Comment by andrea83ny** [comment]
I'm usi

> If anyone still have this problem...
> ... here is what I did.
> I have multiple accounts on which InstaPy is running.
> Use
> `from instapy import set_workspace`
> and different
> `set_workspace(path='PATH_TO_INSTAGRAM_ACCOUNT_WORKSPACE')`
> PATH_TO_INSTAGRAM_ACCOUNT_WORKSPACE should be different for each account.

Could you pleas explain what I should use instead of  PATH_TO_INSTAGRAM_ACCOUNT_WORKSPACE  ?

**Comment by ahlawataman** [comment]
If firefox is alreading running, close that down using task manager, and then try again running the script.
Worked for me :)
