### ISSUE TITLE
Load button not found working with current images

### ISSUE THREAD

**Issue by gitpatrickhub** [InstaPy/InstaPy#499]
On raspberry pi 3 headless using Firefox. 

After login receive “Load button not found working with current images”

Just started seeing this about same time as others reporting login issues.

**Comment by smallredcape** [comment]
Same here - script can't find the load button on Chrome - using Terminal on a mac.

**Comment by sionking** [comment]
same

**Comment by anuragbjain** [comment]
They have changed the classes for the Load More url, updating the class on line 34 and line 111 of like_util.py to  ('//a[contains(@class, "_1cr2e _epyes")]') made it work for me.  On both Raspberry pi and Mac

**Comment by timgrossmann** [comment]
#504

**Comment by kuzne4eg** [comment]
And so we have the same problem again. Layout is changed and there is no “load more” button any more...

**Comment by kashyapsagar** [comment]
Facing this issue and wont work beyond that.

**Comment by NeoMechDragon** [comment]
+ I get "Load button not found, working with current images!"
