### ISSUE TITLE
Cannot run with proxy

### ISSUE THREAD

**Issue by dlenskyi** [InstaPy/InstaPy#4990]
My error is
`InstaPy Version: 0.6.2
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/dlenskyi/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-02 10:22:12] [smart_gear_pro]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-09-02 10:22:12] [smart_gear_pro]  -- Connection Checklist [1/3] (Internet Connection Status)
WARNING [2019-09-02 10:22:12] [smart_gear_pro]  - Proxy is set, but it's not working properly
WARNING [2019-09-02 10:22:12] [smart_gear_pro]  - Expected Proxy IP is "176.107.176.76", and the current IP is "46.219.213.136"
WARNING [2019-09-02 10:22:12] [smart_gear_pro]  - Try again or disable the Proxy Address on your setup
WARNING [2019-09-02 10:22:12] [smart_gear_pro]  - Aborting connection...
............................................................................................................................
CRITICAL [2019-09-02 10:22:12] [smart_gear_pro]  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''`

Configuration is

`session = InstaPy(username=insta_username, 
                        password=insta_password, 
                        proxy_username='',
                        proxy_password='',
                        proxy_address=proxy[2],
                        proxy_port=proxy[3],
                        nogui=True,
                        bypass_security_challenge_using='sms')`

It's a private proxy, with login and pass, but as it mentioned on docs, we dont need to use pass and login
what's wrong?

**Comment by selene-y** [comment]
same

**Comment by superryeti** [comment]
I had same issue. So now i am using LUMINATI proxy manager. It will route your proxy with a local address such as 
127.0.01.:2500

**Comment by unclrd** [comment]
had the same issue. for some reason it checks the dedicated ip (that you use for the login ) against external ip which instagram will see. but these are different in most cases. 
as a workaround i ended up making a custom browser profile for firefox and i am using the proxy through an add on. (foxy proxy), deactivated in instapy and you are good to go.

**Comment by superryeti** [comment]
yes i had to modify the login_utils.py to get it working. It sucks that i have to modify every time.
