### ISSUE TITLE
InstaPy liking history does not match the posts I like history in my instagram (go to photo link but not like the photo)

### ISSUE THREAD

**Issue by swang45** [InstaPy/InstaPy#4992]
Expected Behavior:
I have tried multiple templates. I expected to use the templates that allow me to like the photo that contains hashtags "food" in it. After running Quickstart.py, in my terminal, cookies says it has liked tons of the images. 
I expect those likes to be showed up on my account, so that when I check the posts I liked, they do match. Or at least I could see there are new posts that I've liked. 

## Current Behavior
There is no update on the posts I liked on my Instagram account. And in my cookies, it shows that it has liked a lots of posts. 

Here's a quick screenshot from terminal:
INFO [2019-09-02 12:07:18] [p]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-09-02 12:07:18] [p]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-09-02 12:07:18] [p]  - Internet Connection Status: ok
INFO [2019-09-02 12:07:18] [p]  - Current IP is "XXXX" and it's from "XXX"
INFO [2019-09-02 12:07:18] [p]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-09-02 12:07:23] [p]  - Instagram WebSite Status: Currently Up 
INFO [2019-09-02 12:07:23] [p]  - Instagram Response Time: 43.406 ms 
INFO [2019-09-02 12:07:23] [p]  - Instagram Reponse Code: 200
INFO [2019-09-02 12:07:23] [p]  - Instagram Server Status: ok
INFO [2019-09-02 12:07:23] [p]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-09-02 12:07:23] [p]  - window.navigator.webdriver response: False
INFO [2019-09-02 12:07:23] [p]  - Hide Selenium Extension: ok
.........................................................................
INFO [2019-09-02 12:07:35] [p]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-09-02 12:07:35] [p]  Saving account progress...
INFO [2019-09-02 12:08:27] [p]  Failed to get followers count of 'b'p''  ~empty list
# I was never able to get followers count from in Instagram account. Is that normal?/Have this happened to anyone?
INFO [2019-09-02 12:09:17] [p]  Failed to get following count of 'b'p''  ~empty list
WARNING [2019-09-02 12:09:17] [p]  Unable to save account progress, skipping data update
INFO [2019-09-02 12:09:26] [p]  Tag [1/9]
INFO [2019-09-02 12:09:26] [p]  --> b'parisfood'
INFO [2019-09-02 12:09:37] [p]  desired amount: 30  |  top posts [disabled]: 9  |  possible posts: 250914
INFO [2019-09-02 12:09:43] [p]  Like# [1/30]
INFO [2019-09-02 12:09:43] [p]  https://www.instagram.com/p/B14LxqkJF7e/
INFO [2019-09-02 12:09:46] [p]  Image from: b'paris.foodguide'
INFO [2019-09-02 12:09:46] [p]  Link: b'https://www.instagram.com/p/B14LxqkJF7e/'

But when I go back and check on my Instagram. I don't see the record of liking this post.

**Comment by Tr1pke** [comment]
and are you blocked? check the screenshots

**Comment by swang45** [comment]
> and are you blocked? check the screenshots

How would I know if I am blocked? I have rerun the program. And here's what I got.
INFO [2019-09-02 12:07:18] [p]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-09-02 12:07:18] [p]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-09-02 12:07:18] [p]  - Internet Connection Status: ok
INFO [2019-09-02 12:07:18] [p]  - Current IP is "XXXX" and it's from "XXX"
INFO [2019-09-02 12:07:18] [p]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-09-02 12:07:23] [p]  - Instagram WebSite Status: Currently Up 
INFO [2019-09-02 12:07:23] [p]  - Instagram Response Time: 43.406 ms 
INFO [2019-09-02 12:07:23] [p]  - Instagram Reponse Code: 200
INFO [2019-09-02 12:07:23] [p]  - Instagram Server Status: ok
INFO [2019-09-02 12:07:23] [p]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-09-02 12:07:23] [p]  - window.navigator.webdriver response: False
INFO [2019-09-02 12:07:23] [p]  - Hide Selenium Extension: ok
.........................................................................
INFO [2019-09-02 12:07:35] [p]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-09-02 12:07:35] [p]  Saving account progress...
INFO [2019-09-02 12:08:27] [p]  Failed to get followers count of 'b'p''  ~empty list
# I was never able to get followers count from in Instagram account. Is that normal?
INFO [2019-09-02 12:09:17] [p]  Failed to get following count of 'b'p''  ~empty list
WARNING [2019-09-02 12:09:17] [p]  Unable to save account progress, skipping data update
INFO [2019-09-02 12:09:26] [p]  Tag [1/9]
INFO [2019-09-02 12:09:26] [p]  --> b'parisfood'
INFO [2019-09-02 12:09:37] [p]  desired amount: 30  |  top posts [disabled]: 9  |  possible posts: 250914
INFO [2019-09-02 12:09:43] [p]  Like# [1/30]
INFO [2019-09-02 12:09:43] [p]  https://www.instagram.com/p/B14LxqkJF7e/
INFO [2019-09-02 12:09:46] [p]  Image from: b'paris.foodguide'
INFO [2019-09-02 12:09:46] [p]  Link: b'https://www.instagram.com/p/B14LxqkJF7e/'
#my account didn't actually like this photo when I checked back.
