### ISSUE TITLE
Just updated to 0.6.2, still getting the AttributeError: 'list' object has no attribute 'lower'

### ISSUE THREAD

**Issue by flygohr** [InstaPy/InstaPy#4993]
## Expected Behavior
Instapy should start normally
## Current Behavior
Mind that I originally fixed this error fidgeting with the instapy.py code as suggested in another issues, but then some other errors came up like 'no connection' stuff and others so I decided to wait for an update
## Possible Solution (optional)
Can someone help me fix the script? I have a dozen running for friends (different locations so no ip problems)
## InstaPy configuration
Maybe this is the problem? Is the documentation up to date? I built my script over a year ago and never changed it, maybe some syntax changed? Can't get the script to work since mid July

**Comment by Mathieu-5** [comment]
Same here : https://github.com/timgrossmann/InstaPy/issues/4995
