### ISSUE TITLE
WARNING [2019-09-02 16:56:09] [smart_gear_pro]  --> Comment Button Not Found!	~may cause issues with browser windows of smaller widths

### ISSUE THREAD

**Issue by dlenskyi** [InstaPy/InstaPy#4994]
WARNING [2019-09-02 16:56:09] [smart_gear_pro]  --> Comment Button Not Found!	~may cause issues with browser windows of smaller widths

selenium.common.exceptions.WebDriverException: Message: TypeError: rect is undefined

I have this mistake after 2-5 hours (randomly)  Instapy session started

**Comment by turtlebking** [comment]
similar to the case in
https://github.com/timgrossmann/InstaPy/issues/4960
