### ISSUE TITLE
AttributeError: 'list' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Mathieu-5** [InstaPy/InstaPy#4995]
## Expected Behavior
Since i have updating Instapy, my script don't work ..
Thanks for your help !

## Current Behavior
 File "script.py", line 459, in <module>
    interact=True)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 3481, in follow_user_followers
    validation, details = self.validate_user_call(person)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 1317, in validate_user_call
    self.logfolder,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/util.py", line 417, in validate_username
    if bio_keyword.lower() in profile_bio.lower():
AttributeError: 'list' object has no attribute 'lower'

## InstaPy configuration
InstaPy configuration
Instapy V.0.6.2
Raspberry 3
Home network
Firefox
Headless mode
i use this script : https://github.com/InstaPy/instapy-quickstart/blob/master/quickstart_templates/target_followers_of_similar_accounts_and_influencers.py

**Comment by flygohr** [comment]
Same here! Please help!

**Comment by flygohr** [comment]
The fix is here in the issues somewhere and consists of switching the order of lines 1314 and 1315 of the instapy.py file (use pip show instapy to locate your package). It's still an issue tho, as we need to manually change the file. How are the others managing to start their script???
