### ISSUE TITLE
Instagram figuring out i am using instapy and blocking account

### ISSUE THREAD

**Issue by pythoncoder15** [InstaPy/InstaPy#4996]
## Expected Behavior
Hi guys! I have been using instapy for the last year or so. Since June, though, when the "It seems you are using a 3rd party application" popup started showing up, i limited my actions on the platform.

What i did in the last year was as following:
- I would get the latest five photos from a profile which is in the same audience
- Foreach photo i would have grabbed all of the photo likers
- Foreach liker i would grab 3-4-5 photos
- Foreach photo i would have given a like action

This helped me raise the acount i am working on from 2k to 6.5k followers and a slow and steady increase.

After the june warnings i added a liking speed coutner which made sure i stayed under a predefined likes number per hour. I still would have received a 24 hour ban sometimes when the script was doing too many likes per hour i believe.

The script was runing all day and night, regardless.

## Current Behavior
Last week when i came back from holiday and wanted to restart instapy processes, i updated the project to the latest version and left it working all day. At noon i had received an instagram notification that i am blocked for a whole week. I was unable to post, like, comment, etc. I was just able to view.

I am now affraid if i turn it on again i will be banned for a week again or who knows, maybe i get my account deleted.

I also started noticing that afer that one week where i was blocked i am getting much lesser likes per post. Around 100-200 maximum although i used to get around 1k likes per photo on average. Is this because instagram added me to a "blacklist" ? 

Did any of you had this issue and managed to succesfully convince isntagram that you are not a bot ?

## InstaPy configuration
I am using instapy with chromedriver,
The browser is running on the screen, not headless, so i can see what the script is doing.

Thank you guys, looking forward to your response!

**Comment by Tr1pke** [comment]
Yes. Suspicious accounts will be on a blacklist. 
They will watch you closely. If you make a new account. Use it for 2 months normally run instapy in it and you have at least one month without anything problems. Then they notice again you have a 3th party on that account and that account also get on the blacklist. 

They see bots like cheating 
It’s a matter of time and bots are done. 
Use it as much you can it will be over before you know.

**Comment by Mizi91** [comment]
Did you solve this somehow with the black-listed account? Maybe set some low action count limit? Or should we stop using instapy for that account completely?

**Comment by pythoncoder15** [comment]
@Tr1pke - thanks for the reply. Did this happen to you too ?
@Mizi91  - I didn't use instapy after i got blocked for a week. I am affraid it might delete my acoutn completely.

Did this happen to somebody else ?

**Comment by Tr1pke** [comment]
Yes but they warned me a couple of times. So in the end it’s my own fault

**Comment by jonap339** [comment]
I have stopped using instapy. I do the work manually and continue to receive this blocking message for the use of third-party applications and do not even open Instapy. I can't keep working. The strange thing is that I work with 5 different accounts. I begin to follow 30 followers on the first account, some likes, and comments, no more than 5. Then I follow 30 in the second and they already blocked me forcing me to change the password. The strange thing is that I enter the third account and I am directly blocked without being able to do anything. Will they block my IP? After blocking, whatever account I open, I am blocked.

**Comment by ghost** [comment]
Are you running InstaPy without any problems? May I have your quickstart.py file?

**Comment by Flaunkerton2395** [comment]
Can you show your script? @pythoncoder15

**Comment by pythoncoder15** [comment]
@jonap339 Thanks for sharing. That did not happen to me, i am able to use the account normally, but no with isntapy without getting blocked.

@Flaunkerton2395  @Avatar1964 
I've created a repository so you can see my code:
https://github.com/pythoncoder15/instapy-pythoncoder15

Let me know if you have any ideas on how to bypass the blocking. :(

**Comment by Flaunkerton2395** [comment]
I am trying to recreate the issue but I am not sure how to commit your custom functions. I downloaded the custom_functions file and I am trying to run your quick start but it isn't utilizing the custom functions.

**Comment by pythoncoder15** [comment]
Yes, the custom functions are only as a backup in case i overwrite the modifications, they arent used. 
I couldnt figure out how to import it or make it overwrite a function.
The code i use is in the instapy.py file.

**Comment by Tr1pke** [comment]
We followed +-100 users and unfollowed over 100 users a day for a week and nobody got blocked. 
I did it with a group of 4 and everyone did one day constantly following and constantly unfollowing only with the APP on the phone and not a single block 

We did the same with another account everything went perfect , at day 2 we started the bot and directly blocked. 

Reason enough to assume that the period of bots is coming to an end

**Comment by Tr1pke** [comment]
The good thing is that you can filter on ‘last followed user’ so it’s easy to do manually. 
I get more done in 15 min then a whole day with a bot ...

We need to emulate an Android in sort of a VM else this will be dead within months

**Comment by ghost** [comment]
I'm having the same problems here. Blocked for a few days because they identified I am using a bot.

**Comment by Tr1pke** [comment]
Try to do the same actions with the app on your phone you can even do double or triple and not being blocked

**Comment by GabrieleAnsaldo** [comment]
So I actually found a fix if you really want to have an instagram bot. Basically instagram got very good at detecting bots so I tried to work around that. Basically I have connected my old android phone to the Raspberry (you can connect it to any computer) and I just send a bunch of adb commands to it. I wrote a little script. Its been working so well.

I guess instagram finds it hard to find bots from someone using the app itself and not the browser version.

Hit me up if you are interested in developing this project with me, there is still a lot to do to make it very efficient.

**Comment by alexal1** [comment]
I had a look at GabrieleAnsaldo's code and tried some more universal approach: https://github.com/alexal1/Insomniac

Instead of sending touch events to the device I use UI Automator frameworks. It works just like InstaPy but with your Android app. Instagram limits for mobile apps are much bigger.
