### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a  matching set of capabilities

### ISSUE THREAD

**Issue by alejbarea** [InstaPy/InstaPy#4997]
C:\Users\...\Desktop\InstaPy-master>python quickstart.py
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
No any custom workspace provided.       ~using existing..
InstaPy Version: 0.6.2
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/.../InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    session = InstaPy(username="ouraccount",password="ourpass")
  File "C:\Users\...\Desktop\InstaPy-master\instapy\instapy.py", line 321,
 in __init__
    self.logger,
  File "C:\Users\...\Desktop\InstaPy-master\instapy\browser.py", line 114,
 in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\lib\site-pa
ckages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\lib\site-pa
ckages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\lib\site-pa
ckages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\lib\site-pa
ckages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37-32\lib\site-pa
ckages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a
 matching set of capabilities

I don't know why this is happening (I put ourpass and ouraccount in order to protect our privacy)

**Comment by dev4jam** [comment]
Having the same issue on Ubuntu

**Comment by FabrizioConrado** [comment]
Having the same issue.  I'm using Mac OS (Mojave) with Chrome

RESOLVED: I installed Firefox and this particular problem was resolved.  If you are already using Firefox and still having trouble, please see [#4923](https://github.com/timgrossmann/InstaPy/issues/4923)

**Comment by stryker77** [comment]
I'm having the same issue can anyone help me with this please

**Comment by prototype127** [comment]
download the dev branch version and try running it on firefox

**Comment by LuismiLabs** [comment]
Same here in Digital Ocean!

**Comment by lorenzoPrimi** [comment]
@Luismij apt-get install firefox solved for me on digitalocean

**Comment by poupkine** [comment]
Firefox installation really helped! :)

**Comment by ianmihura** [comment]
What helped for me was switching from firefox to chrome, which requires a bit of touching the core files of the project, but works just fine now :)

**Comment by nduka-junior** [comment]
Iiii
