### ISSUE TITLE
Latest 0.6.x versions are not working in RPi3 -setWindowRect-

### ISSUE THREAD

**Issue by octavius-1** [InstaPy/InstaPy#4998]
I've been trying so long to make these new versions work for me, but I haven't been able to do it. I even had to downgrade my version to 0.5.8 because of it.

Since firefox was forced as the one and only browser of this tool, the message: setWindowRect has been showing up with no fix.

Has anyone else seen this? I thought it was because of my low resolution but when I increased it the same issue was showing up.

**Comment by Mathieu-5** [comment]
Did you try to reinstall Raspian and make a new setup of Instapy ?

**Comment by Jangojack14** [comment]
I had the same issue,  I reinstall the OS, And Create a new User with permission ( Pi was rejected ) And it fix the problem' !!!! 💃  💃
