### ISSUE TITLE
can not pull account data, Instagram account page broken

### ISSUE THREAD

**Issue by swang45** [InstaPy/InstaPy#5000]
## Expected Behavior
Be able to pull my Instagram page, and count my account followers
## Current Behavior
Sessional Live Report:
	|> No any statistics to show
And it login to my Instagram page, shows my page for 5 seconds. And then it says: 

## SORRY this page isn't available.
The link you followed may be broken, or the page may have been removed. Go back to Instagram.

**Comment by mehrdadmms** [comment]
@swang45 
Hi I have the same problem I keep getting this response 
what should i do ? 
Did you make any break through ?
