### ISSUE TITLE
instapy start fail ( Internet connection status= error)

### ISSUE THREAD

**Issue by oh2thirteen** [InstaPy/InstaPy#5002]
if i run instapy on win7 64 bit i become this error 
InstaPy Version: 0.6.2
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/chris/InstaPy"
Traceback (most recent call last):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 24, in <module>
    headless_browser=False)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

if some one can help it will be make me really happy

**Comment by oh2thirteen** [comment]
i solved the problem but now i got a newe problem the bot starts but not login and say this 
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-04 09:39:51] [Nick]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-09-04 09:39:52] [Nick]  -- Connection Checklist [1/3] (Internet Connection Status)
WARNING [2019-09-04 09:39:54] [Nick]  - Internet Connection Status: error
................................................................................................................................
CRITICAL [2019-09-04 09:39:54] [Nick]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2019-09-04 09:39:58] [Nick]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 20.86 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-04 09:39:58] [Nick]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by meinert** [comment]
Please make a more meaningful/descriptive headline to your post.

**Comment by ceribbo** [comment]
When launching a session, instapy initally checks if instagram is offline using the website [https://isitdownorjust.me/instagram-com/](https://isitdownorjust.me/instagram-com/) in order to prevent error caused by instagram not working errors.
Unfortunately the website isitdownorjustme is offline too 👎 so instapy will not start interacting with instagram because it is believed to be offline

**Comment by oh2thirteen** [comment]
@ceribbo thanks for help but manually i come in, my internet connection is normal. it comes directly with internet connection status : error  
and  i do all steps like it was in tutorial.
 and i update everything what instapy detect at install what whas not freshest version like jsonschema

**Comment by synchron** [comment]
@oh2thirteen Could you share how to solve the first problem? I have the same issue. 
I will happy if you help me.

**Comment by oh2thirteen** [comment]
@synchron yes i can dude.
This is a install problem if you got a 64 bit system use python for amd64 its for intel 64 bit too. And update in cmd pip and if the instapy say after install in cmd jsonschema or other not the version you need install with pip in cmd the version who instapy want. In my situation i got jsonsschema 3.0 but instapy whas want 2.5

**Comment by oh2thirteen** [comment]
Please community help mee :D im not a idiot if some one help i understand fast :D

**Comment by oh2thirteen** [comment]
@synchron  make fresh install with steps i write.

**Comment by ghost** [comment]
> if i run instapy on win7 64 bit i become this error
> InstaPy Version: 0.6.2
> ._. ._. ._. ._. ._. ._. ._. ._. ._.
> Workspace in use: "C:/Users/chris/InstaPy"
> Traceback (most recent call last):
> File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\quickstart.py", line 24, in
> headless_browser=False)
> File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\instapy.py", line 321, in **init**
> self.logger,
> File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
> options=firefox_options,
> File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in **init**
> keep_alive=True)
> File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "C:\Users\chris\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
> 
> if some one can help it will be make me really happy

How did you solved this problem?

**Comment by oh2thirteen** [comment]
@INeedHelp6 this can be different to your problem. 
i recommended to make a fresh clean instal best way manual with cmd between pip.
download install right jsonsschema version. but dont forget start everything like cmd as admin. 
and after clean install start through cmd a easy quickstart.py to look if its work.
i got much problems with instapy because this i use now other bot

**Comment by ianmihura** [comment]
Same issue and found that bypassing the check_browser function does the trick in my case
The fix is: comment out the lines 274 & 275 from the file login_util.py
That's it

NOTE: this only works because I know that the browser checks that instapy does give me an error when it should give me none. Might not work if you're running a server or need the browser checks.

**Comment by AlexProstyakov** [comment]
**IT's easy!!! Instapy start test for check connection!!**  we must abort it!!

> **program/instapy/login_until.py**

this tring 

> 

 # check connection status
    try:
        logger.info("-- Connection Checklist [1/3] (Internet Connection Status)")
        browser.get("view-source:https://api.myip.com/")
        pre = browser.find_element_by_tag_name("pre").text
        current_ip_info = json.loads(pre)
        if (
            proxy_address is not None
            and socket.gethostbyname(proxy_address) != current_ip_info["ip"]
        ):
            logger.warn("- Proxy is set, but it's not working properly")
            logger.warn(
                '- Expected Proxy IP is "{}", and the current IP is "{}"'.format(
                    proxy_address, current_ip_info["ip"]
                )
            )
            logger.warn("- Try again or disable the Proxy Address on your setup")
            logger.warn("- Aborting connection...")
            return False
        else:
            logger.info("- Internet Connection Status: ok")
            logger.info(
                '- Current IP is "{}" and it\'s from "{}/{}"'.format(
                    current_ip_info["ip"],
                    current_ip_info["country"],
                    current_ip_info["cc"],
                )
            )
            update_activity(
                browser,
                action=None,
                state="Internet connection is ok",
                logfolder=logfolder,
                logger=logger,
            )
    except Exception:
        logger.warn("- Internet Connection Status: error")
        update_activity(
            browser,
            action=None,
            state="There is an issue with the internet connection",
            logfolder=logfolder,
            logger=logger,
        )
        return False

    # check Instagram.com status
    try:
        logger.info("-- Connection Checklist [2/3] (Instagram Server Status)")
        browser.get("https://isitdownorjust.me/instagram-com/")
        sleep(2)
        # collect isitdownorjust.me website information
        website_status = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "website_status")
        )
        response_time = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "response_time")
        )
        response_code = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "response_code")
        )

        logger.info("- Instagram WebSite Status: {} ".format(website_status.text))
        logger.info("- Instagram Response Time: {} ".format(response_time.text))
        logger.info("- Instagram Reponse Code: {}".format(response_code.text))
        logger.info("- Instagram Server Status: ok")
        update_activity(
            browser,
            action=None,
            state="Instagram servers are running correctly",
            logfolder=logfolder,
            logger=logger,
        )
    except Exception:
        logger.warn("- Instagram Server Status: error")
        update_activity(
            browser,
            action=None,
            state="Instagram server is down",
            logfolder=logfolder,
            logger=logger,
        )
        return False

**We must skip this test**
 in this file - **login_until.py**

delete 274, 275 string
next

 if not check_browser(browser, logfolder, logger, proxy_address):
        return False

**Comment by raviriley** [comment]
@AlexProstyakov @ianmihura 
How do I make those changes locally? I installed Instapy through [instapy-quickstart](https://github.com/InstaPy/instapy-quickstart) so I am unsure how to proceed. Do I need to clone the main repo? If so, then what? Thanks!

**Comment by kami4ka** [comment]
Can this be improved in the main repo by using some flag for example?

**Comment by brb72** [comment]
Hey! After months of being down and "having a block on likes" (but not really), I was able to get this up and running. 

Basically, I put the script so it showed the browser window while doing the checks:

`session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)`

I then saw the "Error Establishing Database Connection" message from the "isitdownorjust.me" website, and realized this is where the process was breaking down.

I then tried commenting out the following lines (472-473 in [0.6.6)](https://github.com/timgrossmann/InstaPy/commit/4220e9d508e2f9bd28f564febb0694fa68278c8e) however I still got the same error:

`    #if "instagram.com/accounts/onetap" in browser.current_url:
        #browser.get("https://instagram.com")`

I then went into \InstaPy\Login_Util.py and used a string literal to additionally comment out the entire section of code performing this "isitdownorjust.me" check (starts with the triple quotes and ends with the same, lines 210-246):


'    
# check Instagram.com status
    """try:
        logger.info("-- Connection Checklist [2/3] (Instagram Server Status)")
        browser.get("https://isitdownorjust.me/instagram-com/")
        sleep(2)
        # collect isitdownorjust.me website information
        website_status = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "website_status")
        )
        response_time = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "response_time")
        )
        response_code = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "response_code")
        )

        logger.info("- Instagram WebSite Status: {} ".format(website_status.text))
        logger.info("- Instagram Response Time: {} ".format(response_time.text))
        logger.info("- Instagram Reponse Code: {}".format(response_code.text))
        logger.info("- Instagram Server Status: ok")
        update_activity(
            browser,
            action=None,
            state="Instagram servers are running correctly",
            logfolder=logfolder,
            logger=logger,
        )
    except Exception:
        logger.warn("- Instagram Server Status: error")
        update_activity(
            browser,
            action=None,
            state="Instagram server is down",
            logfolder=logfolder,
            logger=logger,
        )
        return False"""

    # check if hide-selenium extension is running
    logger.info("-- Connection Checklist [3/3] (Hide Selenium Extension)")
    webdriver = browser.execute_script("return window.navigator.webdriver")
`

I'm now back up and liking! Hope this helps everyone else!!

**Comment by sylvie7788** [comment]
Ok GUYS, I've been trying for so long and finally got it to work.

Two steps needed:
1.  Download firefox browser
2. Go to    /lib/python3.7/instapy/login.util.py --> thencomment out line 211-246


**KEY**: DO NOTE COMMENT MORE than LINE 211-246 out.
I tried following the comment above and it DID NOT WORK for me.


1.Download firefox browser when you're seeing:

  File "quickstart.py", line 24, in <module>
    headless_browser=False)
  File "/Users/sylsyl/env/lib/python3.7/site-packages/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/Users/sylsyl/env/lib/python3.7/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/Users/sylsyl/env/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/Users/sylsyl/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/sylsyl/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/sylsyl/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/sylsyl/env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities




2. Go to    /lib/python3.7/instapy/login.util.py --> thencomment out line 211-246
when you're seeing this error:


OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-11-14 15:36:26] [urbangardenernow]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-11-14 15:36:26] [urbangardenernow]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-11-14 15:36:26] [urbangardenernow]  - Internet Connection Status: ok
INFO [2019-11-14 15:36:26] [urbangardenernow]  - Current IP is "148.76.126.18" and it's from "United States/US"
INFO [2019-11-14 15:36:26] [urbangardenernow]  -- Connection Checklist [2/3] (Instagram Server Status)
WARNING [2019-11-14 15:36:33] [urbangardenernow]  - Instagram Server Status: error
..............................................................................................................................
CRITICAL [2019-11-14 15:36:33] [urbangardenernow]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2019-11-14 15:36:33] [urbangardenernow]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2019-11-14 15:36:34] [urbangardenernow]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 13.29 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-11-14 15:36:34] [urbangardenernow]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



login_util.py:

line 211- 246

    try:
        logger.info("-- Connection Checklist [2/3] (Instagram Server Status)")
        browser.get("https://isitdownorjust.me/instagram-com/")
        sleep(2)
        # collect isitdownorjust.me website information
        website_status = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "website_status")
        )
        response_time = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "response_time")
        )
        response_code = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "response_code")
        )

        logger.info("- Instagram WebSite Status: {} ".format(website_status.text))
        logger.info("- Instagram Response Time: {} ".format(response_time.text))
        logger.info("- Instagram Reponse Code: {}".format(response_code.text))
        logger.info("- Instagram Server Status: ok")
        update_activity(
            browser,
            action=None,
            state="Instagram servers are running correctly",
            logfolder=logfolder,
            logger=logger,
        )
    except Exception:
        logger.warn("- Instagram Server Status: error")
        update_activity(
            browser,
            action=None,
            state="Instagram server is down",
            logfolder=logfolder,
            logger=logger,
        )
        return False

**Comment by khansaad1275** [comment]
> @oh2thirteen Could you share how to solve the first problem? I have the same issue.
> I will happy if you help me.

i just downloaded Firefox and geckodriver then run the quickstart.py (for me its only opening using terminal , because  you will se another error (the second error on this page)

**Comment by t0in4** [comment]
> **IT's easy!!! Instapy start test for check connection!!** we must abort it!!
> 
> > **program/instapy/login_until.py**
> 
> this tring
> 
> > 
> 
> # check connection status
> ```
> try:
>     logger.info("-- Connection Checklist [1/3] (Internet Connection Status)")
>     browser.get("view-source:https://api.myip.com/")
>     pre = browser.find_element_by_tag_name("pre").text
>     current_ip_info = json.loads(pre)
>     if (
>         proxy_address is not None
>         and socket.gethostbyname(proxy_address) != current_ip_info["ip"]
>     ):
>         logger.warn("- Proxy is set, but it's not working properly")
>         logger.warn(
>             '- Expected Proxy IP is "{}", and the current IP is "{}"'.format(
>                 proxy_address, current_ip_info["ip"]
>             )
>         )
>         logger.warn("- Try again or disable the Proxy Address on your setup")
>         logger.warn("- Aborting connection...")
>         return False
>     else:
>         logger.info("- Internet Connection Status: ok")
>         logger.info(
>             '- Current IP is "{}" and it\'s from "{}/{}"'.format(
>                 current_ip_info["ip"],
>                 current_ip_info["country"],
>                 current_ip_info["cc"],
>             )
>         )
>         update_activity(
>             browser,
>             action=None,
>             state="Internet connection is ok",
>             logfolder=logfolder,
>             logger=logger,
>         )
> except Exception:
>     logger.warn("- Internet Connection Status: error")
>     update_activity(
>         browser,
>         action=None,
>         state="There is an issue with the internet connection",
>         logfolder=logfolder,
>         logger=logger,
>     )
>     return False
> 
> # check Instagram.com status
> try:
>     logger.info("-- Connection Checklist [2/3] (Instagram Server Status)")
>     browser.get("https://isitdownorjust.me/instagram-com/")
>     sleep(2)
>     # collect isitdownorjust.me website information
>     website_status = browser.find_element_by_xpath(
>         read_xpath(login_user.__name__, "website_status")
>     )
>     response_time = browser.find_element_by_xpath(
>         read_xpath(login_user.__name__, "response_time")
>     )
>     response_code = browser.find_element_by_xpath(
>         read_xpath(login_user.__name__, "response_code")
>     )
> 
>     logger.info("- Instagram WebSite Status: {} ".format(website_status.text))
>     logger.info("- Instagram Response Time: {} ".format(response_time.text))
>     logger.info("- Instagram Reponse Code: {}".format(response_code.text))
>     logger.info("- Instagram Server Status: ok")
>     update_activity(
>         browser,
>         action=None,
>         state="Instagram servers are running correctly",
>         logfolder=logfolder,
>         logger=logger,
>     )
> except Exception:
>     logger.warn("- Instagram Server Status: error")
>     update_activity(
>         browser,
>         action=None,
>         state="Instagram server is down",
>         logfolder=logfolder,
>         logger=logger,
>     )
>     return False
> ```
> 
> **We must skip this test**
> in this file - **login_until.py**
> 
> delete 274, 275 string
> next
> 
> if not check_browser(browser, logfolder, logger, proxy_address):
> return False
comment strings 276,277,278
#if want_check_browser:
    #if not check_browser(browser, logfolder, logger, proxy_address):
        #return False

**Comment by xandrade** [comment]
> Ok GUYS, I've been trying for so long and finally got it to work.
> 
> Two steps needed:
> 
> 1. Download firefox browser
> 2. Go to    /lib/python3.7/instapy/login.util.py --> thencomment out line 211-246
> 
> **KEY**: DO NOTE COMMENT MORE than LINE 211-246 out.
> I tried following the comment above and it DID NOT WORK for me.
> 
> 1.Download firefox browser when you're seeing:
> 
> File "quickstart.py", line 24, in
> headless_browser=False)
> File "/Users/sylsyl/env/lib/python3.7/site-packages/instapy/instapy.py", line 319, in **init**
> self.logger,
> File "/Users/sylsyl/env/lib/python3.7/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
> options=firefox_options,
> File "/Users/sylsyl/env/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in **init**
> keep_alive=True)
> File "/Users/sylsyl/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "/Users/sylsyl/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "/Users/sylsyl/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "/Users/sylsyl/env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
> 
> 1. Go to    /lib/python3.7/instapy/login.util.py --> thencomment out line 211-246
>    when you're seeing this error:
> 
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2019-11-14 15:36:26] [urbangardenernow] Session started!
> oooooooooooooooooooooooooooooooooooooooooooooooooooooo
> INFO [2019-11-14 15:36:26] [urbangardenernow] -- Connection Checklist [1/3] (Internet Connection Status)
> INFO [2019-11-14 15:36:26] [urbangardenernow] - Internet Connection Status: ok
> INFO [2019-11-14 15:36:26] [urbangardenernow] - Current IP is "148.76.126.18" and it's from "United States/US"
> INFO [2019-11-14 15:36:26] [urbangardenernow] -- Connection Checklist [2/3] (Instagram Server Status)
> WARNING [2019-11-14 15:36:33] [urbangardenernow] - Instagram Server Status: error
> ..............................................................................................................................
> CRITICAL [2019-11-14 15:36:33] [urbangardenernow] Unable to login to Instagram! You will find more information in the logs above.
> ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
> ERROR [2019-11-14 15:36:33] [urbangardenernow] You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.
> 
> INFO [2019-11-14 15:36:34] [urbangardenernow] Sessional Live Report:
> |> No any statistics to show
> 
> [Session lasted 13.29 seconds]
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2019-11-14 15:36:34] [urbangardenernow] Session ended!
> ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
> 
> login_util.py:
> 
> line 211- 246
> 
> ```
> try:
>     logger.info("-- Connection Checklist [2/3] (Instagram Server Status)")
>     browser.get("https://isitdownorjust.me/instagram-com/")
>     sleep(2)
>     # collect isitdownorjust.me website information
>     website_status = browser.find_element_by_xpath(
>         read_xpath(login_user.__name__, "website_status")
>     )
>     response_time = browser.find_element_by_xpath(
>         read_xpath(login_user.__name__, "response_time")
>     )
>     response_code = browser.find_element_by_xpath(
>         read_xpath(login_user.__name__, "response_code")
>     )
> 
>     logger.info("- Instagram WebSite Status: {} ".format(website_status.text))
>     logger.info("- Instagram Response Time: {} ".format(response_time.text))
>     logger.info("- Instagram Reponse Code: {}".format(response_code.text))
>     logger.info("- Instagram Server Status: ok")
>     update_activity(
>         browser,
>         action=None,
>         state="Instagram servers are running correctly",
>         logfolder=logfolder,
>         logger=logger,
>     )
> except Exception:
>     logger.warn("- Instagram Server Status: error")
>     update_activity(
>         browser,
>         action=None,
>         state="Instagram server is down",
>         logfolder=logfolder,
>         logger=logger,
>     )
>     return False
> ```

Brilliant! That web page is banned here
