### ISSUE TITLE
Instagram Server Status: error

### ISSUE THREAD

**Issue by Sc0l10** [InstaPy/InstaPy#5003]
Hi folks,
I'm on a ubuntu 19.04 up-to-date. Yesterday Instapy works smoothly, but today I'm struggling with a strange issue. It stops with an Instagram Server Status Error, with no additionnal logs:

InstaPy Version: 0.6.2
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/toor/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-04 10:48:41] [scolyo]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-09-04 10:48:41] [scolyo]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-09-04 10:48:41] [scolyo]  - Internet Connection Status: ok
INFO [2019-09-04 10:48:41] [scolyo]  - Current IP is "194.57.109.109" and it's from "France/FR"
INFO [2019-09-04 10:48:41] [scolyo]  -- Connection Checklist [2/3] (Instagram Server Status)
WARNING [2019-09-04 10:49:19] [scolyo]  - Instagram Server Status: error
....................................................................................................................
CRITICAL [2019-09-04 10:49:20] [scolyo]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
[smart hashtag generated: breakfast]
[smart hashtag generated: cleaneating]
[smart hashtag generated: breakfast]
[smart hashtag generated: cleaneating]
[smart hashtag generated: musculation]
[smart hashtag generated: regime]
[smart hashtag generated: breakfast]
[smart hashtag generated: cleaneating]
[smart hashtag generated: musculation]
[smart hashtag generated: regime]
[smart hashtag generated: instacool]
[smart hashtag generated: webstagram]
[smart hashtag generated: breakfast]
[smart hashtag generated: cleaneating]
[smart hashtag generated: musculation]
[smart hashtag generated: regime]
[smart hashtag generated: instacool]
[smart hashtag generated: webstagram]
[smart hashtag generated: stylish]
[smart hashtag generated: lookbook]
[smart hashtag generated: breakfast]
[smart hashtag generated: cleaneating]
[smart hashtag generated: musculation]
[smart hashtag generated: regime]
[smart hashtag generated: instacool]
[smart hashtag generated: webstagram]
[smart hashtag generated: stylish]
[smart hashtag generated: lookbook]
[smart hashtag generated: money]
[smart hashtag generated: business]

INFO [2019-09-04 10:49:29] [scolyo]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 56.66 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-04 10:49:29] [scolyo]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooo

I've upgraded the chromedriver to the latest stable (ChromeDriver 76.0.3809.126)
My chromium-browser version is 76.0.3809.100
But nothing change the issue

Below is my instapy script.

## InstaPy configuration

from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'XXXX'
insta_password = 'XXXXXXXXX'

#comments = ['Nice shot! @{}',
#        'I love your profile! @{}',
#        'Your feed is an inspiration :thumbsup:',
#        'Just incredible :open_mouth:',
#        'What camera did you use @{}?',
#        'Love your posts @{}',
#        'Looks awesome @{}',
#        'Getting inspired by you @{}',
#        ':raised_hands: Yes!',
#        'I can feel your passion @{} :muscle:']

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
  """ Activity flow """		
  # general settings
  session.set_action_delays(enabled=True, like=18.3, follow=15.8, unfollow=12.4, randomize=True, random_range_from=70, random_range_to=140)
  session.set_dont_include(["XXXXXXX", "XXXXXXXX"])

  session.set_skip_users(skip_private=True,
                       private_percentage=98,
                       skip_no_profile_pic=True,
                       no_profile_pic_percentage=100)

  session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes_hourly=24,
				peak_likes_daily=127,
                                peak_follows_hourly=21,
				peak_follows_daily=168,
                                 peak_unfollows_hourly=23,
					peak_unfollows_daily=179,
                                  peak_server_calls_hourly=550,
					peak_server_calls_daily=7500)		
  
  session.set_relationship_bounds(enabled=True, delimit_by_numbers=True, max_followers=30000, max_following=15000, min_followers=75, min_following=75)

  session.set_dont_like(
        ['dick', 'squirt', 'gay', 'homo',
         '#kids', '#children', '#child',
         '[nazi',
         'jew', 'judaism', '[muslim', '[islam', 'bangladesh', '[hijab',
         '[niqab', '[farright', '[rightwing',
         '#conservative', 'death', 'racist'])

  # activity
  session.set_user_interact(amount=3, randomize=True, percentage=50, media="None")
  session.set_smart_hashtags(["vegan", "fitfrench", "picoftheday", "fashionblogger", "goodlife"], limit=2, sort='top', log_tags=True)
  
#"fitover40", "fitness", "fitnessmotivation", "fitfrench", "crossfit", "firefighter", "honorthefallen", "fitfam", "vegan", "goodlife", "workout", "healthy", "mensphysique", "scoliosis", "workout", "ctschristophecarrio", "picoftheday", "photooftheday", "blogging", "blogger", "lifestyleblogger", "fashionblogger", "functionaltraining", "gymmotivation", "instagood", "photography", "strengh"

  session.follow_by_tags(amount=5, interact=True, use_smart_hashtags=True)

  session.unfollow_users(amount=7, instapy_followed_enabled=True, instapy_followed_param="all", style="FIFO", unfollow_after=90*60*60, sleep_delay=501)
		
  session.like_by_tags(amount=9, interact=True, use_smart_hashtags=True)

  session.like_by_feed(amount=18, randomize=True, unfollow=True, interact=True)

  

  # Joining Engagement Pods
#  session.set_do_comment(enabled=True, percentage=35)
#  session.set_comments(comments)
#session.join_pods()

Thanks in advance for any help :-)

**Comment by Sc0l10** [comment]
It seems that the script attempt to open this page

https://isitdownorjust.me/instagram-com/

But it fails...

**Comment by aniltumkaya** [comment]
I've got the same problem. Ironically, the website to check if websites are down, is down. I tried fixing it in the login_util.py file, by trying a similar website. I used this site: https://downforeveryoneorjustme.com/instagram You can find it in line 179. It opens the site, but doesn't know how to read it to get the logger.info('- Instagram Server Status: ok') result.

**Comment by jase5760** [comment]
Same issue..

**Comment by dimebt** [comment]
**Solution 1:** 
Add `want_check_browser=False`
```
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  want_check_browser=False)
```

**Solution 2:** 
Edit the **login_util.py** file:

Find and comment this block of code:

    # # check Instagram.com status
    # try:
    #     logger.info('-- Connection Checklist [2/2] (Instagram Server Status)')
    #     browser.get("https://isitdownorjust.me/instagram-com/")

    #     # collect isitdownorjust.me website information
    #     website_status = browser.find_element_by_xpath(
    #         read_xpath(login_user.__name__, "website_status"))
    #     response_time = browser.find_element_by_xpath(
    #         read_xpath(login_user.__name__, "response_time"))
    #     response_code = browser.find_element_by_xpath(
    #         read_xpath(login_user.__name__, "response_code"))

    #     logger.info('- Instagram WebSite Status: {} '.format(website_status.text))
    #     logger.info('- Instagram Response Time: {} '.format(response_time.text))
    #     logger.info('- Instagram Reponse Code: {}'.format(response_code.text))
    #     logger.info('- Instagram Server Status: ok')
    # except Exception:
    #     logger.warn('- Instagram Server Status: error')
    #     return False

With this instapy will not even go to check the instagram server status. 
Good luck 👍

**Comment by aniltumkaya** [comment]
Works like a charm! Thanks!

**Comment by issamarmas** [comment]
> Edit the **login_util.py** file:
> 
> Find and comment this block of code:
> 
> ```
> # # check Instagram.com status
> # try:
> #     logger.info('-- Connection Checklist [2/2] (Instagram Server Status)')
> #     browser.get("https://isitdownorjust.me/instagram-com/")
> 
> #     # collect isitdownorjust.me website information
> #     website_status = browser.find_element_by_xpath(
> #         read_xpath(login_user.__name__, "website_status"))
> #     response_time = browser.find_element_by_xpath(
> #         read_xpath(login_user.__name__, "response_time"))
> #     response_code = browser.find_element_by_xpath(
> #         read_xpath(login_user.__name__, "response_code"))
> 
> #     logger.info('- Instagram WebSite Status: {} '.format(website_status.text))
> #     logger.info('- Instagram Response Time: {} '.format(response_time.text))
> #     logger.info('- Instagram Reponse Code: {}'.format(response_code.text))
> #     logger.info('- Instagram Server Status: ok')
> # except Exception:
> #     logger.warn('- Instagram Server Status: error')
> #     return False
> ```
> 
> With this instapy will not even go to check the instagram server status.
> Good luck 👍

works thanks .. but why it has even exist ??.. what it does?

**Comment by jase5760** [comment]
works thank you!

**Comment by prototype127** [comment]
Did not worked for me ... can any one help ?

**Comment by hyp3rur4n1um** [comment]
> 
> 
> > Edit the **login_util.py** file:
> > Find and comment this block of code:
> > ```
> > # # check Instagram.com status
> > # try:
> > #     logger.info('-- Connection Checklist [2/2] (Instagram Server Status)')
> > #     browser.get("https://isitdownorjust.me/instagram-com/")
> > 
> > #     # collect isitdownorjust.me website information
> > #     website_status = browser.find_element_by_xpath(
> > #         read_xpath(login_user.__name__, "website_status"))
> > #     response_time = browser.find_element_by_xpath(
> > #         read_xpath(login_user.__name__, "response_time"))
> > #     response_code = browser.find_element_by_xpath(
> > #         read_xpath(login_user.__name__, "response_code"))
> > 
> > #     logger.info('- Instagram WebSite Status: {} '.format(website_status.text))
> > #     logger.info('- Instagram Response Time: {} '.format(response_time.text))
> > #     logger.info('- Instagram Reponse Code: {}'.format(response_code.text))
> > #     logger.info('- Instagram Server Status: ok')
> > # except Exception:
> > #     logger.warn('- Instagram Server Status: error')
> > #     return False
> > ```
> > 
> > 
> > With this instapy will not even go to check the instagram server status.
> > Good luck 👍
> 
> works thanks .. but why it has even exist ??.. what it does?

it use third party website tracker to verify instagram is online

the tracker itseld is now offline hence the error

**Comment by hyp3rur4n1um** [comment]
> 
> 
> Edit the **login_util.py** file:
> 
> Find and comment this block of code:
> 
> ```
> # # check Instagram.com status
> # try:
> #     logger.info('-- Connection Checklist [2/2] (Instagram Server Status)')
> #     browser.get("https://isitdownorjust.me/instagram-com/")
> 
> #     # collect isitdownorjust.me website information
> #     website_status = browser.find_element_by_xpath(
> #         read_xpath(login_user.__name__, "website_status"))
> #     response_time = browser.find_element_by_xpath(
> #         read_xpath(login_user.__name__, "response_time"))
> #     response_code = browser.find_element_by_xpath(
> #         read_xpath(login_user.__name__, "response_code"))
> 
> #     logger.info('- Instagram WebSite Status: {} '.format(website_status.text))
> #     logger.info('- Instagram Response Time: {} '.format(response_time.text))
> #     logger.info('- Instagram Reponse Code: {}'.format(response_code.text))
> #     logger.info('- Instagram Server Status: ok')
> # except Exception:
> #     logger.warn('- Instagram Server Status: error')
> #     return False
> ```
> 
> With this instapy will not even go to check the instagram server status.
> Good luck 👍

I am using a containerazed version, would you know another workaround ?

**Comment by prototype127** [comment]
> Edit the **login_util.py** file:
> 
> Find and comment this block of code:
> 
> ```
> # # check Instagram.com status
> # try:
> #     logger.info('-- Connection Checklist [2/2] (Instagram Server Status)')
> #     browser.get("https://isitdownorjust.me/instagram-com/")
> 
> #     # collect isitdownorjust.me website information
> #     website_status = browser.find_element_by_xpath(
> #         read_xpath(login_user.__name__, "website_status"))
> #     response_time = browser.find_element_by_xpath(
> #         read_xpath(login_user.__name__, "response_time"))
> #     response_code = browser.find_element_by_xpath(
> #         read_xpath(login_user.__name__, "response_code"))
> 
> #     logger.info('- Instagram WebSite Status: {} '.format(website_status.text))
> #     logger.info('- Instagram Response Time: {} '.format(response_time.text))
> #     logger.info('- Instagram Reponse Code: {}'.format(response_code.text))
> #     logger.info('- Instagram Server Status: ok')
> # except Exception:
> #     logger.warn('- Instagram Server Status: error')
> #     return False
> ```
> 
> With this instapy will not even go to check the instagram server status.
> Good luck
After pasting this in login_util.py (check instagram.status) it shows me the same error while running quickstart.py ..... firefox opens and error 552 occurs ..

**Comment by prototype127** [comment]
> works thank you!

hey can i contact you somewhere ?
plz help

**Comment by prototype127** [comment]
finally the website in not offline anymore

**Comment by spikeyhair** [comment]
I changed "return False" to "return True" at line #242, and it by pass the down checker.
I personally found it not useful, so no harm to bypass the checker.

**Comment by Sc0l10** [comment]
It seems that the script attempt to open this page

https://isitdownorjust.me/instagram-com/

But it fails...

**Comment by Sc0l10** [comment]
Thanks for all,
Works like a charm :-)

**Comment by lamaledetta** [comment]
It happens again. Website used as Instagram tracker is down. 
I’m running InstaPy in a Docker container, how can I modified the code in order to override the check?

**Comment by riccardovalente** [comment]
Setting `want_check_browser` has been around for a while. Set it to `False` in your quickstart file.

**Comment by lamaledetta** [comment]
> Setting `want_check_browser` has been around for a while. Set it to `False` in your quickstart file.

Worked like a charm, thank you!

**Comment by nirmalnarayanan** [comment]
It Worked. Thank you!!!

**Comment by viplove29** [comment]
it worked.thank you
