### ISSUE TITLE
TypeError: set_delimit_liking() got an unexpected keyword argument 'max'

### ISSUE THREAD

**Issue by sadegh-khan** [InstaPy/InstaPy#5004]
when i run my quickstart.py, i have following error :

Workspace in use: "/home/pi/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-04 15:02:05] [copper..]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-09-04 15:02:05] [copper..]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-09-04 15:02:07] [copper..]  - Internet Connection Status: ok
INFO [2019-09-04 15:02:07] [copper..]  - Current IP is "....." and it's from "...."
INFO [2019-09-04 15:02:07] [copper..]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-09-04 15:03:08] [copper..]  - Instagram WebSite Status: Currently Up 
INFO [2019-09-04 15:03:08] [copper..]  - Instagram Response Time: 40.963 ms 
INFO [2019-09-04 15:03:08] [copper..]  - Instagram Reponse Code: 200
INFO [2019-09-04 15:03:08] [copper..]  - Instagram Server Status: ok
INFO [2019-09-04 15:03:08] [copper..]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-09-04 15:03:08] [copper..]  - window.navigator.webdriver response: False
INFO [2019-09-04 15:03:08] [copper..]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
INFO [2019-09-04 15:03:59] [copper.art.]  Timed out with failure while explicitly waiting until page fully loaded!

................................................................................................................................
CRITICAL [2019-09-04 15:04:04] [copper.art.]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
Traceback (most recent call last):
  File "Copper_main.py", line 82, in <module>
    session.set_delimit_liking(enabled=True, max=500, min=None)
TypeError: set_delimit_liking() got an unexpected keyword argument 'max'

**Comment by Ewwwer** [comment]
you need to change the max argument: 
session.set_delimit_liking(enabled=True, max_likes=500, min_likes=None)

;)
