### ISSUE TITLE
Change the using browser 

### ISSUE THREAD

**Issue by oh2thirteen** [InstaPy/InstaPy#5005]
hay in which file i can change the code to using other browser ???

instapy use automatik firefox at my system but i want them using Chrome ??? 

i use win7 64 biit

**Comment by ghost** [comment]
Have the same question

**Comment by amphoterism** [comment]
You'll be banned after one follow on chrome. It's why they switched to firefox.

**Comment by oh2thirteen** [comment]
@amphoterism 
Thanks but my bot do this at first start directly without login in instagram.

**Comment by abuyusif01** [comment]
but wait what of doing it with brave cuz am trying to use the brave its shows me errors
