### ISSUE TITLE
Comments not being posted.

### ISSUE THREAD

**Issue by superryeti** [InstaPy/InstaPy#5007]
## Expected Behavior
Comments should be posted.
## Current Behavior
When disabling the headless mode i can see the bot writes comments but never hits the post button. But in logs it says commented:...

**Comment by prototype127** [comment]
same error , but only when i add a @username to it

**Comment by prototype127** [comment]
as it cant select the profile while adding the "@username" .. below the list is shown and the bot skips that bcoz there is no command or idk what is that ... but when i use  simple comment .. it works fine
