### ISSUE TITLE
Unable to login to Instagram! cookie issue

### ISSUE THREAD

**Issue by id0ntbyte** [InstaPy/InstaPy#5012]
## Expected Behavior
For the script to login and start working correctly.

## Current Behavior
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
No any custom workspace provided.	~using existing..
InstaPy Version: 0.6.2
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-05 11:54:12] [username]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-09-05 11:54:12] [username]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-09-05 11:54:13] [username]  - Internet Connection Status: ok
INFO [2019-09-05 11:54:13] [username]  - Current IP is "IP_ADDRESS" and it's from "United States/US"
INFO [2019-09-05 11:54:14] [username]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-09-05 11:54:30] [username]  - Instagram WebSite Status: Currently Up 
INFO [2019-09-05 11:54:30] [username]  - Instagram Response Time: 35.963 ms 
INFO [2019-09-05 11:54:30] [username]  - Instagram Reponse Code: 200
INFO [2019-09-05 11:54:30] [username]  - Instagram Server Status: ok
INFO [2019-09-05 11:54:31] [username]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-09-05 11:54:31] [username]  - window.navigator.webdriver response: False
INFO [2019-09-05 11:54:31] [username]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
............................................................................................................................
CRITICAL [2019-09-05 11:55:07] [username]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2019-09-05 11:55:11] [username]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 1.25 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-05 11:55:11] [username]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
## Possible Solution (optional)
I believe there is a problem with cookie creation

## InstaPy configuration
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

set_workspace(path=None)
session = InstaPy(username=insta_username,
          password=insta_password,
          headless_browser=True)
with smart_run(session):
    session.set_relationship_bounds(enabled=True,
    delimit_by_numbers=True,
    max_followers=10000)
    session.like_by_tags(['insta'], amount=numLikes)

**Comment by Tr1pke** [comment]
start your instapy with headless_browser=False , then you see you have to click on a button "remember/Not Now" after that you will log in successfully  and find other problems :-D

**Comment by id0ntbyte** [comment]
Thank you that fixed the issue
