### ISSUE TITLE
WARNING [2019-09-05 18:07:23] [My.Insta]  Unavailable Page: b'https://www.instagram.com/p/B2CRf3CgQnI/'

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#5013]
## Expected Behavior
working like it worked before
## Current Behavior
WARNING [2019-09-05 18:06:49] [My.Insta.Account]  Unavailable Page: b'https://www.instagram.com/p/B2CRsf5grJl/'
INFO [2019-09-05 18:06:49] [My.Insta.Account]  --> Image not liked: b'Unavailable Page'
INFO [2019-09-05 18:06:49] [My.Insta.Account]  Like# [8/59]
INFO [2019-09-05 18:06:49] [My.Insta.Account]  https://www.instagram.com/p/B2CRrdEIwYB/
WARNING [2019-09-05 18:06:52] [My.Insta.Account]  Unavailable Page: b'https://www.instagram.com/p/B2CRrdEIwYB/'
INFO [2019-09-05 18:06:52] [My.Insta.Account]  --> Image not liked: b'Unavailable Page'
INFO [2019-09-05 18:06:52] [My.Insta.Account]  Like# [9/59]
INFO [2019-09-05 18:06:52] [My.Insta.Account]  https://www.instagram.com/p/B2CRppVgvQ0/
WARNING [2019-09-05 18:06:56] [My.Insta.Account]  Unavailable Page: b'https://www.instagram.com/p/B2CRppVgvQ0/'
INFO [2019-09-05 18:06:56] [My.Insta.Account]  --> Image not liked: b'Unavailable Page'
INFO [2019-09-05 18:06:56] [My.Insta.Account]  Like# [10/59]
INFO [2019-09-05 18:06:56] [My.Insta.Account]  https://www.instagram.com/p/B2CRnHIgEd-/
WARNING [2019-09-05 18:07:00] [My.Insta.Account]  Unavailable Page: b'https://www.instagram.com/p/B2CRnHIgEd-/'
INFO [2019-09-05 18:07:00] [My.Insta.Account]  --> Image not liked: b'Unavailable Page'
INFO [2019-09-05 18:07:00] [My.Insta.Account]  Like# [11/59]
INFO [2019-09-05 18:07:00] [My.Insta.Account]  https://www.instagram.com/p/B2CRleMItjQ/
WARNING [2019-09-05 18:07:03] [My.Insta.Account]  Unavailable Page: b'https://www.instagram.com/p/B2CRleMItjQ/'
INFO [2019-09-05 18:07:03] [My.Insta.Account]  --> Image not liked: b'Unavailable Page'
INFO [2019-09-05 18:07:03] [My.Insta.Account]  Like# [12/59]
INFO [2019-09-05 18:07:03] [My.Insta.Account]  https://www.instagram.com/p/B2CRk4WAKp2/
WARNING [2019-09-05 18:07:06] [My.Insta.Account]  Unavailable Page: b'https://www.instagram.com/p/B2CRk4WAKp2/'
INFO [2019-09-05 18:07:06] [My.Insta.Account]  --> Image not liked: b'Unavailable Page'
INFO [2019-09-05 18:07:06] [My.Insta.Account]  Like# [13/59]
INFO [2019-09-05 18:07:06] [My.Insta.Account]  https://www.instagram.com/p/B2CRk1eIxnq/
WARNING [2019-09-05 18:07:10] [My.Insta.Account]  Unavailable Page: b'https://www.instagram.com/p/B2CRk1eIxnq/'
INFO [2019-09-05 18:07:10] [My.Insta.Account]  --> Image not liked: b'Unavailable Page'
INFO [2019-09-05 18:07:10] [My.Insta.Account]  Like# [14/59]
INFO [2019-09-05 18:07:10] [My.Insta.Account]  https://www.instagram.com/p/B2CRkBsobkg/
WARNING [2019-09-05 18:07:13] [My.Insta.Account]  Unavailable Page: b'https://www.instagram.com/p/B2CRkBsobkg/'
INFO [2019-09-05 18:07:13] [My.Insta.Account]  --> Image not liked: b'Unavailable Page'
INFO [2019-09-05 18:07:13] [My.Insta.Account]  Like# [15/59]
INFO [2019-09-05 18:07:13] [My.Insta.Account]  https://www.instagram.com/p/B2CRiFbgSPS/
WARNING [2019-09-05 18:07:16] [My.Insta.Account]  Unavailable Page: b'https://www.instagram.com/p/B2CRiFbgSPS/'
INFO [2019-09-05 18:07:16] [My.Insta.Account]  --> Image not liked: b'Unavailable Page'
INFO [2019-09-05 18:07:16] [My.Insta.Account]  Like# [16/59]
INFO [2019-09-05 18:07:16] [My.Insta.Account]  https://www.instagram.com/p/B2CRgyShSnw/
WARNING [2019-09-05 18:07:19] [My.Insta.Account]  Unavailable Page: b'https://www.instagram.com/p/B2CRgyShSnw/'
INFO [2019-09-05 18:07:19] [My.Insta.Account]  --> Image not liked: b'Unavailable Page'
INFO [2019-09-05 18:07:19] [My.Insta.Account]  Like# [17/59]
INFO [2019-09-05 18:07:19] [My.Insta.Account]  https://www.instagram.com/p/B2CRf3CgQnI/
WARNING [2019-09-05 18:07:23] [My.Insta.Account]  Unavailable Page: b'https://www.instagram.com/p/B2CRf3CgQnI/'
INFO [2019-09-05 18:07:23] [My.Insta.Account]  --> Image not liked: b'Unavailable Page'
INFO [2019-09-05 18:07:23] [My.Insta.Account]  Like# [18/59]
INFO [2019-09-05 18:07:23] [My.Insta.Account]  https://www.instagram.com/p/B2CRN2PlQeh/
WARNING [2019-09-05 18:07:26] [My.Insta.Account]  Unavailable Page: b'https://www.instagram.com/p/B2CRN2PlQeh/'
INFO [2019-09-05 18:07:26] [My.Insta.Account]  --> Image not liked: b'Unavailable Page'
INFO [2019-09-05 18:07:26] [My.Insta.Account]  Like# [19/59]
INFO [2019-09-05 18:07:26] [My.Insta.Account]  https://www.instagram.com/p/B2CReHNioWz/
## Possible Solution (optional)
get the old version back
## InstaPy configuration
like always

It says that the page is unavailable while i see instapy live going to the page, so the page is available

**Comment by csvchou** [comment]
Still got [Image not liked: b'Unavailable Page'] after the bug fixes #5028

**Comment by turtlebking** [comment]
check out the fixed on my pull request
https://github.com/timgrossmann/InstaPy/pull/5046
