### ISSUE TITLE
how to tag someone in comment ?

### ISSUE THREAD

**Issue by prototype127** [InstaPy/InstaPy#5015]
Hello ,
I want to mention a profile in my comments but when i use @username the comment is not posted .. any solutions ? 
thanks in advance :)

**Comment by prototype127** [comment]
the '@' makes the error .. but i dont know how to use it perfectly what changes i can make into it

**Comment by bilkefpv** [comment]
"@prototype127"

**Comment by prototype127** [comment]
> "@prototype127"

haha, i tried the same but didnt worked for me as it just skips posting
