### ISSUE TITLE
Pagination not working (I got a quick fix-- class was renamed)

### ISSUE THREAD

**Issue by benvegel** [InstaPy/InstaPy#502]
Hey the "load more" button class was renamed yielding this error: 'Load button not found, working with current images!'

The issue was a class name change for the "load more"button. I fixed my bot by updating instapy/like_util.py both lines 35 and 115 (they were identical) from:
('//a[contains(@class, "_8imhp _glz1g")]')

to:
('//a[contains(@class, "_1cr2e _epyes")]')

**Comment by timgrossmann** [comment]
@benvegel I'll look into this.
Do you want to create a PR for this fix?

**Comment by thehon** [comment]
I just got mine working by de-capitalizing the C in class
('//a[contains(@class, "_1cr2e _epyes")]') (seems to autocorrect to capital C in github)
