### ISSUE TITLE
Clarifai stoped legal Auth key

### ISSUE THREAD

**Issue by wemakefuture** [InstaPy/InstaPy#503]
Hello @timgrossmann, 

there is no longer the opportunity to create auth keys. Just if you have an old account you can use it till late 2017 but for new Clarifai Accs its no longer supported.

is there a chance for a fast fix in the clarifai_util.py?

![image](https://user-images.githubusercontent.com/28114725/29059088-2244e378-7c14-11e7-9972-68aa302c9b73.png)

Thanks for your outstanding work and support so far :)

**Comment by edwardh5** [comment]
I made a PR #521 which updates this.

**Comment by timgrossmann** [comment]
@wecanfuture @NedYork Will be merges as soon as the documentation changes has been made.
Thank you!
