### ISSUE TITLE
Traceback: self.error_handler.check_response(response)

### ISSUE THREAD

**Issue by rubinho101** [InstaPy/InstaPy#5030]
Hi there, I keep getting the following issue, any idea? 

`Traceback (most recent call last): File "quickstart2.py", line 28, in <module> session.like_by_tags(['1','2', '3', '4', '5', '6'], amount=1, skip_top_posts=True) File "/Users/1/Downloads/InstaPy-master/instapy/instapy.py", line 1797, in like_by_tags user_name) File "/Users/1/Downloads/InstaPy-master/instapy/instapy.py", line 1214, in validate_user_call self.logfolder) File "/Users/1/Downloads/InstaPy-master/instapy/util.py", line 188, in validate_username logger) File "/Users/1/Downloads/InstaPy-master/instapy/util.py", line 945, in get_relationship_counts browser.find_element_by_xpath(read_xpath(get_relationship_counts.__name__,"followers_count")).text) File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath return self.find_element(by=By.XPATH, value=xpath) File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element 'value': value})['value'] File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute self.error_handler.check_response(response) File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: 'value' must be a string (Session info: headless chrome=71.0.3578) (Driver info: chromedriver=2.46.6284 (),platform=Mac OS X 10.11 x86_64)`

**Comment by CJSparrow** [comment]
same error
