### ISSUE TITLE
Issue running session.like_by_tags

### ISSUE THREAD

**Issue by lopjf** [InstaPy/InstaPy#5031]
Hello,
I have some issues running the classic
`session.like_by_tags(['natgeo'], amount=1, randomize=True, media='Photo')`

Indeed, during execution I got this error message
`File "c:\Users\Administrator\Desktop\Instapy\mysoft.py", line 42, in instapy
    session.like_by_tags(['natgeo'], amount=1, randomize=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 1817, in like_by_tags
    self.logger)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\like_util.py", line 589, in check_link
    media = post_page[0]['media']
KeyError: 'media'`

Do someone has an idea about what to do in order to solve this issue ?

Thanks :)

**Comment by poonasor** [comment]
I'm also experiencing this problem, doesn't seem to be solved from the looks of the other threads

**Comment by turtlebking** [comment]
also related to https://github.com/timgrossmann/InstaPy/issues/4949


in like_util.py @line 617
```
        media = post_page[0]["media"]
```
change to:
```
        media = post_page[0]["shortcode_media"]
```
