### ISSUE TITLE
Issue Getting Follower Count of Other Users

### ISSUE THREAD

**Issue by yogaheart** [InstaPy/InstaPy#5032]
## Expected Behavior
INFO [2019-09-02 18:11:15] [username]  Image from: b'xyz'
INFO [2019-09-02 18:11:15] [username]  Link: b'https://www.instagram.com/p/xyz/'
INFO [2019-09-02 18:11:15] [username]  Description: b'xyz'
INFO [2019-09-02 18:11:15] [username] User: 'xyz'  |> followers: 925  |> following: 753  |> relationship ratio: 1.22

## Current Behavior
INFO [2019-09-02 18:11:15] [username]  Image from: b'xyz'
INFO [2019-09-02 18:11:15] [username]  Link: b'https://www.instagram.com/p/xyz/'
INFO [2019-09-02 18:11:15] [username]  Description: b'xyz'
**INFO [2019-09-02 18:12:08] [username]  Failed to get followers count of 'b'xyz''  ~empty list**

## InstaPy configuration

like_tag_list = ['abc']

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True)

while True:
    with smart_run(session):

        # settings
        session.set_action_delays(enabled=True,
                               like=12,
                               follow=14,
                               unfollow=16)
        session.set_relationship_bounds(enabled=True,
                                potency_ratio=0.9,
				                delimit_by_numbers=True,
				                max_followers=6000,
				                max_following=3000,
				                min_followers=50,
				                min_following=50,
				                min_posts=25,
                                max_posts=1500)
        amount_number=500
        session.set_skip_users(skip_private=True,
                       private_percentage=100,
                       skip_no_profile_pic=True,
                       no_profile_pic_percentage=100,
                       skip_business=True,
                       business_percentage=100)
        session.set_user_interact(amount=2, randomize=True, percentage=20, media='Photo')
        session.set_do_follow(enabled=False, percentage=0)
        session.set_do_like(enabled=True, percentage=100)
        session.set_do_comment(enabled=False, percentage=0)
        session.set_dont_unfollow_active_users(enabled=True, posts=5)

        # activity
        session.follow_user_followers(['user33'], amount=amount_number, randomize=False, interact=True, sleep_delay=300)

        session.end()

**Comment by poupkine** [comment]
I have the same issue. hope it is IG built-in limits. I have 2 accounts with InstaPy, one worked yesterday, but several restarts of script lead to this trouble. The second script runs without problems with the same code.

**Comment by realsnad** [comment]
Related to issue #5042.

**Comment by yogaheart** [comment]
That isn’t the problem I’m having

**Comment by realsnad** [comment]
> 
> That isn’t the problem I’m having
> […](#)
> On Sep 10, 2019, at 3:24 AM, ym85 ***@***.***> wrote: Related to issue #5042. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Most likely it is the problem that you're having. I have the same problem. And it happens when IG starts showing "Please try again" page instead of regular page, where the bot knows where to click.

**Comment by dyrgutt** [comment]
I started getting this today as well--been working fine for a month prior :/

**Comment by papillon-unix** [comment]
I'm having the same problème.
It started with `might be temporarily blocked from following` then this: `Failed to get followers count` and not trying to follow at all.
