### ISSUE TITLE
Instapy says i'm blocked while i'm not so doesn't add users to followedPool.csv 

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#5034]
## Expected Behavior
add users to the followed pool after following and don't say i'm blocked while i ain't blocked
## Current Behavior
INFO [2019-09-08 08:53:23] [account]  Ongoing Follow [3/3]: now following 'ljrje'...
INFO [2019-09-08 08:53:26] [account]  User: 'ljrje'  |> followers: 521  |> following: 4546  |> relationship ratio: 0.11
WARNING [2019-09-08 08:54:02] [account]  Last follow is not verified.  ~'account' might be temporarily blocked from following
## InstaPy configuration
    session.follow_user_followers(['abc','abc','abc','abc'], amount=3, randomize=True, interact=False)

Instapy says i'm blocked while i'm not so doesn't add users to followedPool.csv what means 
Instapy follows the user, says i'm blocked so instapy thinks it didn't followed the user so it doesn't add him to toe followedPool, means instapy will not unfollow them after 48 hours because the followedPool is empty... any advice?

INFO [2019-09-08 08:53:23] [account]  Ongoing Follow [3/3]: now following 'ljrje'...
INFO [2019-09-08 08:53:26] [account]  User: 'ljrje'  |> followers: 521  |> following: 4546  |> relationship ratio: 0.11
WARNING [2019-09-08 08:54:02] [account]  Last follow is not verified.  ~'account' might be temporarily blocked from following

but my instagram acc is following ljrje after instapy says 'account' might be temporarily blocked from following

**Comment by yuricroci** [comment]
same problem here

**Comment by papillon-unix** [comment]
Same for me since today, but it does NOT follow the user.

**Comment by BuZZy1337** [comment]
Solution: https://github.com/timgrossmann/InstaPy/issues/5305#issuecomment-659684494
