### ISSUE TITLE
Instagram forces me to change password

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5036]
Hello,
some days ago Instagram app showed me that maybe I'm sharing my account with bot apps. I closed it. Yesterday application forces me to change the password.

I changed the password and I stoped to use InstaPy. Can I run instapy again? Is it safe? Don't want to get account ban.
Thank you

**Comment by MalinowskiR** [comment]
its safe but if u will start to use it again they will block your likes and coments (probably follows) and will ask u to change it again. Some how Instagram start to look for bots

**Comment by ghost** [comment]
Ok. But will wait for mor answers

**Comment by ReagentX** [comment]
Here is the error message itself:

![](https://media.discordapp.net/attachments/510385886869979138/621008659375325184/image0.png)

**Comment by Tr1pke** [comment]
Have it also

**Comment by kami4ka** [comment]
Same problem. Looks like instagram starts recognizing of bots on next level.

**Comment by ghost** [comment]
any fix?

**Comment by MalinowskiR** [comment]
What to do now? Anyway Instagram start to put some more information about blocking. Before they just block you. Now they block and send a message that tells you till when u will be blocked and why. Which is much better but now they start to fight harder with bots.

**Comment by Tr1pke** [comment]
Got the same thing today
