### ISSUE TITLE
Unable to login to Instagram! You will find more information in the logs above.

### ISSUE THREAD

**Issue by thankmelater23** [InstaPy/InstaPy#5037]
## Current Behavior
$ python3 myfitz_unfollow.py
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Custom workspace set: "/Users/AndreVillanueva_Com/InstaPy" :]
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/Users/AndreVillanueva_Com/InstaPy"
/Users/AndreVillanueva_Com/InstaPy
InstaPy Version: 0.6.2
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/Users/AndreVillanueva_Com/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-08 15:51:57] [Myfitz_BBS]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-09-08 15:51:57] [Myfitz_BBS]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-09-08 15:51:57] [Myfitz_BBS]  - Internet Connection Status: ok
INFO [2019-09-08 15:51:57] [Myfitz_BBS]  - Current IP is "" and it's from "United States/US"
INFO [2019-09-08 15:51:58] [Myfitz_BBS]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-09-08 15:52:05] [Myfitz_BBS]  - Instagram WebSite Status: Currently Up
INFO [2019-09-08 15:52:05] [Myfitz_BBS]  - Instagram Response Time: 35.536 ms
INFO [2019-09-08 15:52:05] [Myfitz_BBS]  - Instagram Reponse Code: 200
INFO [2019-09-08 15:52:05] [Myfitz_BBS]  - Instagram Server Status: ok
INFO [2019-09-08 15:52:05] [Myfitz_BBS]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-09-08 15:52:05] [Myfitz_BBS]  - window.navigator.webdriver response: False
INFO [2019-09-08 15:52:05] [Myfitz_BBS]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
........................................................................................................................
CRITICAL [2019-09-08 15:52:37] [Myfitz_BBS]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2019-09-08 15:52:38] [Myfitz_BBS]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 54.65 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-08 15:52:38] [Myfitz_BBS]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo
## InstaPy configuration
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.6 (18G29g)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#fastlane_version "2.62.1"
default_platform :ios
platform :ios do
#
# Learn more here: https://docs.fastlane.tools/getting-started/ios/beta-deployment/
#             and: https://docs.fastlane.tools/getting-started/android/beta-deployment/
#
  
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "" # The bundle identifier of your app
apple_id ".com" # Your Apple email address

itc_team_id "" # iTunes Connect Team ID
team_id "" # Developer Portal Team ID

#team_name "Bang Bang Studios"

#To select a team for iTunes Connect use
#itc_team_name "Bang Bang Studios"

apple_dev_portal_id ".com"  # Apple Developer Account
itunes_connect_id ".com"     # iTunes Connect Account

scheme "Belize Lottery"

slack_url ""
# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.130.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| multi_json                | 1.13.1       |
| signet                    | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.1        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.12.0       |
| unicode-display_width     | 1.6.0        |
| addressable               | 2.7.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| excon                     | 0.66.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| json                      | 2.2.0        |
| rubyzip                   | 1.2.3        |
| dotenv                    | 2.7.5        |
| mime-types-data           | 3.2019.0331  |
| os                        | 1.0.1        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| openssl                   | 2.1.2        |
| date                      | 2.0.0        |
| fileutils                 | 1.2.0        |
| ipaddr                    | 1.2.2        |
| psych                     | 3.1.0        |
</details>

*generated on:* **2019-09-08**
</details>

**Comment by Jostino** [comment]
Take a look here:
https://github.com/timgrossmann/InstaPy/issues/5035#issuecomment-529238015

**Comment by thankmelater23** [comment]
> Take a look here:
> [#5035 (comment)](https://github.com/timgrossmann/InstaPy/issues/5035#issuecomment-529238015)

Thank you, that worked.
