### ISSUE TITLE
Unexpected keyword argument 'bypass_suspicious_attempt'

### ISSUE THREAD

**Issue by JuanSpada** [InstaPy/InstaPy#5041]
## Expected Behavior
To log in
## Current Behavior
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
No any custom workspace provided.	~using existing..
Traceback (most recent call last):
  File "default.py", line 76, in <module>
    job()
  File "default.py", line 36, in job
    multi_logs=True)
TypeError: __init__() got an unexpected keyword argument 'bypass_suspicious_attempt'

## InstaPy configuration
from instapy import smart_run
from instapy import set_workspace
import schedule
import time
import random
from instapy import InstaPy

def job():

    #your login credentials
    insta_username = ''
    insta_password = ''

    #referencias
    referencias = ['DeTurista.argentina', 'Turismocity_ar', 'Almundo_ar', 'evanescenceofficial']

    #locations
    # 26914683/santiago-chile/
    # 214397193/montevideo-uruguay/
    # 567465404/colombia/
    locations = ['226142803/ciudad-autonoma-de-buenos-aires/']
    # locations = ['213270076/mexico-city-mexico/']

    #hashtags
    # tags = ['rocknacional', 'punkfashion', 'punkpop', 'lol']

    #path to your workspace
    set_workspace(path=None)

    session = InstaPy(username=insta_username,
                    password=insta_password,
                    headless_browser=True,
                    disable_image_load=True,
                    bypass_suspicious_attempt=True,
                    bypass_with_mobile=False,
                    multi_logs=True)

    with smart_run(session):
        """ Activity flow """
        # settings
        session.set_relationship_bounds(enabled=True,
                                        max_followers=15000)

        session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes=(57, 350),
                               peak_comments=(21, 182),
                                peak_follows=(15, 400),
                                 peak_unfollows=(35, 402),
                                  peak_server_calls=(None, 4700))

        session.set_skip_users(skip_private=False,
                       private_percentage=100)

        session.set_user_interact(amount=2, randomize=True, percentage=60)
        session.set_do_follow(enabled=True, percentage=40)
        session.set_do_like(enabled=True, percentage=80)

        # activity
        #LOCATIONS
        session.follow_by_locations(locations, amount=50, skip_top_posts=False)
        session.like_by_locations(locations, amount=50) 

        # #REFERENCIAS
        session.follow_user_followers(referencias, amount=random.randint(20, 100), randomize=True, sleep_delay=60)

        # #TAGS
        # session.like_by_tags(random.sample(tags, 3),
        #                      amount=random.randint(25, 50), interact=True)
        # session.follow_by_tags(tags, amount=50)

        #UNFOLLOW
        session.unfollow_users(amount=random.randint(200, 400),
                               InstapyFollowed=(True, "all"), style="FIFO",
                               unfollow_after=60 * 60, sleep_delay=501)
        # session.join_pods()
job()
schedule.every().day.at("09:00").do(job)
schedule.every().day.at("10:10").do(job)
schedule.every().day.at("11:00").do(job)
schedule.every().day.at("12:05").do(job)
schedule.every().day.at("13:00").do(job)
schedule.every().day.at("14:20").do(job)
schedule.every().day.at("15:00").do(job)
schedule.every().day.at("16:09").do(job)
schedule.every().day.at("17:10").do(job)
schedule.every().day.at("18:20").do(job)
schedule.every().day.at("19:00").do(job)
schedule.every().day.at("20:10").do(job)
schedule.every().day.at("21:05").do(job)
schedule.every().day.at("22:00").do(job)
while True:
  schedule.run_pending()
  time.sleep(10)

**Comment by Jostino** [comment]
https://github.com/uluQulu/InstaPy/blob/master/DOCUMENTATION.md#bypass-suspicious-login-attempt

It was changed
