### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by realsnad** [InstaPy/InstaPy#5042]
## Expected Behavior
Not getting error page "Please wait a few minutes before you try again."
## Current Behavior
Requests get rejected due to 429 too many requests.
## Possible Solution (optional)
Come up with new delay algorithm for all bot actions.
## InstaPy configuration

My conf is as follows (it is really slow with plenty of wait time):

```
session.follow_user_followers(accounts, amount=150, randomize=True, interact=True, sleep_delay=1800)

session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments", "follows", "unfollows", "server_calls"], sleepyhead=True, stochastic_flow=True, notify_me=False,
                              peak_likes_hourly=90,
                               peak_likes_daily=350,
                                peak_comments_hourly=25,
                                 peak_comments_daily=150,
                                  peak_follows_hourly=20,
                                   peak_follows_daily=150,
                                    peak_unfollows_hourly=30,
                                     peak_unfollows_daily=300,
                                      peak_server_calls_hourly=500,
                                       peak_server_calls_daily=4700)

session.set_action_delays(enabled=True,
                               like=30,
                                comment=7,
                                 follow=120,
                                  unfollow=60,
                                   story=10,
                                    randomize=True, random_range_from=95, random_range_to=105, safety_match=True)
```

I even added my own sleep (random.randint(35, 47)) before the bot tries to follow the next profile (regardless of whether it followed the previous one or not). Nothing helps. During the last run it started giving me "Please wait a few minutes before you try again." page just after TOTAL follow of **9** accounts. Basically, we are hitting instagram limits (429 too many requests, you can see that in the screenshot):

![Error](https://user-images.githubusercontent.com/46596410/64564862-29e6ff80-d35b-11e9-8aab-656cba2e59c4.png)

Now, if I login into my account from another PC and try to open any profile (even my own), it still keeps showing this error page. I also tried going through VPN and still the same. So they are not blocking the particular IP but the profile itself.

I think we have to add random waits **NOT** just between successful follows/unfollow/etc. but in between **ANY** action that the bot does. It clicks any link or button, it needs to wait before it does something else. That's how real user would interact with the website.

**Comment by realsnad** [comment]
'Sorry, couldn't check for number of posts of username' errors are coming from this issue.

**Comment by jase5760** [comment]
I have the same problem

 `session.set_skip_users(skip_private=False,
								private_percentage=100,
								skip_no_profile_pic=True,
								no_profile_pic_percentage=100,
								skip_business=True,
								business_percentage=100,
							#	skip_business_categories=[],
							#	dont_skip_business_categories=[]
							)
							
  #Custom delay
  session.set_action_delays(enabled=True,
                           like=30,
                           comment=29,
                           follow=71,
                           unfollow=28,
                           story=10,
                           randomize=True, random_range_from=70, random_range_to=140)`

This is my configuration

It will run at the start of each day but after some time this error occures.

i think it is something with the unfollow command becouse as i run it without unfollowing it was running for 5 hours without an issue ans as i wrote this line to the code it failed instantly . I am using this one `session.unfollow_users(amount=100, allFollowing=True, style="LIFO", unfollow_after=0*60*60, sleep_delay=450)`

**Comment by realsnad** [comment]
I tried on my second account, same deal. 13 follows in (5.5 hours) and "Sorry, couldn't check for number of posts of username".

**Comment by realsnad** [comment]
> 
> 
> I have the same problem
> 
> `session.set_skip_users(skip_private=False,
> private_percentage=100,
> skip_no_profile_pic=True,
> no_profile_pic_percentage=100,
> skip_business=True,
> business_percentage=100,
> # skip_business_categories=[],
> # dont_skip_business_categories=[]
> )
> 
> #Custom delay
> session.set_action_delays(enabled=True,
> like=30,
> comment=29,
> follow=71,
> unfollow=28,
> story=10,
> randomize=True, random_range_from=70, random_range_to=140)`
> 
> This is my configuration
> 
> It will run at the start of each day but after some time this error occures.
> 
> i think it is something with the unfollow command becouse as i run it without unfollowing it was running for 5 hours without an issue ans as i wrote this line to the code it failed instantly . I am using this one `session.unfollow_users(amount=100, allFollowing=True, style="LIFO", unfollow_after=0*60*60, sleep_delay=450)`

Interesting. I have no problem with unfollowing. I can run it really fast without any issues.

**Comment by jase5760** [comment]
Ok tested again. its not the unfollowing.. its randomly

**Comment by NooriP** [comment]
Same for the unfollow, it gets blocked right away. Is there any solution ?

**Comment by jase5760** [comment]
still not solved :/

**Comment by InfraRedApple** [comment]
Having the same issue.

**Comment by papillon-unix** [comment]
same

**Comment by hijak** [comment]
seems to be instant now

my suspicions are the sequence that instapy runs when it starts up is noticed

**Comment by dyrgutt** [comment]
^agreed, coupled with prior flags that we've set off in the past I imagine - my setup has always been super careful as well, nothing but 'likes' (heavily randomized) - but is discovered within a few minutes :/

**Comment by flygohr** [comment]
It's instant for me too now. What can we do? My set up is extremely conservative and rn I even shut it down and I run it once or twice a day to check on this bug, and it INSTANTLY fails to start

**Comment by realsnad** [comment]
I suppose IG came up with some kind of ML algorithm in its backend that “blocks” profile based on amount of actions from this profile during some time interval. I think limits are different for each profile and exist only for the web version.
I’ve tried signing out in the app, deleting all authorizations and leaving only InstaPy working. Still the same issue. And I have two-factor authentication enabled too.

**Comment by InfraRedApple** [comment]
It would be great if we could somehow find a way to mock the official Instagram app. From my research, Instagram uses SSL pinning to validate that the content is coming from the official app.

Here is a [StackOverflow  question](https://stackoverflow.com/questions/52862256/charles-proxy-for-mobile-apps-that-use-ssl-pinning) that deals with SSL pinning. I'll look into it some, but certificates and SSL are not my area of expertise.

**Comment by realsnad** [comment]
> It would be great if we could somehow find a way to mock the official Instagram app. From my research, Instagram uses SSL pinning to validate that the content is coming from the official app.
> 
> Here is a [StackOverflow question](https://stackoverflow.com/questions/52862256/charles-proxy-for-mobile-apps-that-use-ssl-pinning) that deals with SSL pinning. I'll look into it some, but certificates and SSL are not my area of expertise.

Don't you think that they use completely different APIs when it comes to the app? I don't believe that SSL has anything to do with that, unfortunately. There are much easier ways for them to know what is being used by the user.

**Comment by Strubbl** [comment]
> Don't you think that they use completely different APIs when it comes to the app?

Why should they double the effort and maintain two APIs?

**Comment by InfraRedApple** [comment]
What? No since in making two apis.... I’m talking about rubber stamping all our requests by signing them with the certificate.

**Comment by realsnad** [comment]
> > Don't you think that they use completely different APIs when it comes to the app?
> 
> Why should they double the effort and maintain two APIs?

Even if they use the same APIs, it is not the certificates they use to differentiate requests from the app and the web.

**Comment by ghost** [comment]
can someone try to implement #5068 and we'll see if it helps?

**Comment by realsnad** [comment]
> 
> 
> can someone try to implement #5068 and we'll see if it helps?

Already did in that issue. Please test.

**Comment by webkris** [comment]
I think it has to be set WAY LOW - even lower than this.
I noticed an Instagram Bot Company change to list "1250" actions per day.
I have been cutting my likes and actions - in half - for a few days now, and I still don't think it's enough. I got an "Action Blocked" this morning, and "Please wait a few minutes before you try again." after about 3 hours of run time every day.

The good news is if I wait for 24 hours (and it appears to be exactly 24) and I'm able to run again. 
```
peak_likes_hourly=27,
peak_likes_daily=350,
peak_server_calls_hourly=104,
peak_server_calls_daily=1250

session.set_action_delays(enabled=True, like=30, follow=71, unfollow=28, story=10, randomize=True, random_range_from=70, random_range_to=140)
```

**Comment by realsnad** [comment]
I think that I have an idea on how to deal with the IG limits (at least for following functions). However, implementing this feature might take some time. 

First my idea was to create a dataset of accounts to follow **without** logging in. That way we don't go over the IG limits and log in into the account just to follow based on the collected data. Unfortunately, that wouldn't work since not all popup dialogs, functions and so on are available without logging in.

But what we can do is use a **second dummy account** that would be used for the sole purpose of collecting data for the main account to work on. So the workflow would be as follows: login into dummy account -> collect people to follow based on tags, locations, etc. Of course, taking into consideration all other settings as potency_ratio, max_following, min_posts and so on. As we collect accounts to follow, we store them in a list or SQLite db. After we collected enough (user can set to whatever number), we login into main account and **just** follow the accounts that are in the list without performing any other actions (keeping action_delays in place). That would take fewer server calls from the main account. I believe server calls are counted for the particular IG account and not for the IP address. Right now we are generating lots of server calls; for every action InstaPy is performing there is a call. Yes, we can lower **peak_server_calls_hourly** and **peak_server_calls_daily** but that way it takes too much time to follow just several accounts. We are spending precious server calls on unnecessary things :)

What do you guys think?

**Comment by Tr1pke** [comment]
It would be better if we can emulate a android VM with the instagram app on it for automatisation
i follow already for at least 10 days about 300+ people each day and also unfollow about 300+ people each day already for about 2 weeks now...

I do it manually on the OFFICIAL IG APP (on the bus) every morning and every evening and NEVER had any block or limitation. I can do more in my daily 20 min bus ride then in one complete week running instapy ...

Also I need to do it on the MOBILE APP because even manually on the website it will block me directly or it will stops my actions. So in other works the IG website is just limited for actions.
means, If you make a bot that needs the website to perform actions the bot will be useless.

InstaPy is directly detected by Instagram so its time to get over it and find other solutions

**Comment by flygohr** [comment]
@ym85 , wouldn't it be possible even without a dummy account? couldn't instapy open an incognito window and browse instagram while logged out, and passing the correct information to the other instance?

**Comment by realsnad** [comment]
> @ym85 , wouldn't it be possible even without a dummy account? couldn't instapy open an incognito window and browse instagram while logged out, and passing the correct information to the other instance?

As I mentioned earlier, I don't think we could use all IG functions while logged out. For instance, if you try to see followers of a certain profile while logged out, IG takes you to the login page.

**Comment by flygohr** [comment]
Ooooh, gotcha! That's right!

------------------------------


Flygohr

Freelance comic book artist and illustrator

info@flygohr.com

www.flygohr.com

<http://bit.ly/2kIXAKA>

<http://bit.ly/2malsad>

<http://bit.ly/2lQ0nBR>

<http://bit.ly/2mdl76J>

<https://rdbl.co/2kdPj0U>

<http://bit.ly/2lUEWPZ>

<http://bit.ly/2lUF7uD>

**Comment by InfraRedApple** [comment]
Good thinking. Have one bot harvest info and one bot in a different session acting on it

**Comment by IcebergRage** [comment]
@Tr1pke I have the same conclusion but I get one time the error block message on Instagram Applicion in smartphone (at the third message, I retry and it definitely works).
What do you suggest ? An android bot ?

**Comment by Tr1pke** [comment]
For now I do It like this with success.
I follow manually (app on the phone) 200 person every 2 days, 
then I let the InstaPy bot unfollow except my friends (I have whitelisted them).
this works fine already for a couple of days. 
lets see how long it will run fine, sometimes I also turn off everything for a day or 2.

And android emulation with a bot would be the idea.
Or just accept that instragrams blocks bots ...
