### ISSUE TITLE
Xpath issue:  Message: no such element: Unable to locate element:

### ISSUE THREAD

**Issue by jeffreylm** [InstaPy/InstaPy#505]
@BernardoGO You were able to fix the DIV issue last time.
Yesterday it worked fine. Woke up this morning and started the script, and I got this.
Seems as though instagram has changed the login page again.

**Here is the CMD prompt error**

Traceback (most recent call last):
  File "quickstart.py", line 4, in <module>
    session.login()
  File "C:\Users\jeffrey\Documents\GitHub\Instapy477\instapy\instapy.py", line 124, in login
    if not login_user(self.browser, self.username, self.password):
  File "C:\Users\jeffrey\Documents\GitHub\Instapy477\instapy\login_util.py", line 11, in login_user
    browser.find_element_by_xpath("//footer[@class='_oofbn']/div[@class='_mhrsk _pcuq6']/nav["
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", lin
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", lin
    'value': value})['value']
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", lin
    self.error_handler.check_response(response)
  File "C:\Users\jeffrey\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py",
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","sele
p1gbi']/ul[@class='_fh0f2']/li[@class='_fw3ds'][10]/span[@class='_17z9g _c4mil']/select[@class='_nif11']/option[text()='Englis
  (Session info: chrome=60.0.3112.90)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by ghost** [comment]
Getting this same issue

**Comment by timgrossmann** [comment]
@jeffreylm @Spyd3r0us Did you guys actually do a `git pull` before opening/commenting this issue?

**Comment by jeffreylm** [comment]
@timgrossmann So I had the issue before I downloaded the new last update #477 , then I donwloaded the zipfile and copied over the chromedriver and the quickstart.py

And still got the same error.

Are you not getting the same error?

And do bear in mind yesterday it worked perfectly ok logging in. I left the computer on overnight, and on waking up, I just typed start.bat

Greetings,
Jeffrey

**Comment by timgrossmann** [comment]
@jeffreylm Yes, we had to change it **this morning**. The newest version has no problems with logging in.

**Comment by jeffreylm** [comment]
@timgrossmann still not clear how to do git updates via the git desktop app.

**Comment by timgrossmann** [comment]
You probably have a Windows system, do you?

**Comment by jeffreylm** [comment]
@timgrossmann Yes, I have windows. I read of stackoverflow that it doesn't have all the bells and whils as the other platforms.

**Comment by timgrossmann** [comment]
@jeffreylm Download this: https://git-scm.com/download/win

Then use it to do a:

`git clone https://github.com/timgrossmann/InstaPy.git`

once you've done that you can simply do:

`git pull`

to update it with the newest version

**Comment by ogerasymenko** [comment]
got same issue and seems instagram again change //form/div/div/input location. some time ago was same issue - fix was in changing //form/div/input to //form/div/div/input in login_util.py file.

fixed by updating login_util.py file.

**Comment by jeffreylm** [comment]
@timgrossmann Thank you. How will it know which directory to write to? Or will it make a directory and then always do it automatically from that moement on?

Where will the files be placed? So I know where to copy the start.bat and quickstart.py files to.
Also could you add that git code you just wrote to the main help page for windows install, because only now that you typed this do I know that it had to be done in this manner. I had everthing else except this, also it isn't apparent that the windows version of the desktop is limited in functionality for a newbie.

**Comment by jeffreylm** [comment]
The funny thing is the last time that I was busy in the cmd line like this is in '94 with Dos 6.22. The good old days.

**Comment by jeffreylm** [comment]
Would it be an idea to scrape the page to find input, then use that to set the variable for your input field?
I am noticing that the are just messing with the div, probally to have the bots have issues that use Xpath. I can't imagine a good technical reason for keep messing with the depth of the input field.  

So in short, Xpath receives a variable from a scrape, from for instance scrapy.

**Comment by timgrossmann** [comment]
@jeffreylm Please gather that info from google.
