### ISSUE TITLE
Windows:  Message: The element reference of <button class="_5f5mN.."

### ISSUE THREAD

**Issue by meth0xy** [InstaPy/InstaPy#5063]
## Expected Behavior

Working InstaPy

## Current Behavior

Can't find the Button after DOM is refreshed

## Possible Solution (optional)

Compare DOM before reload with DOM after reload, to change stale element.

## InstaPy configuration
Windows 10 Pro 1903
InstaPy Version: 0.63 (dev-branch)
Selenium
Refference: https://github.com/timgrossmann/InstaPy/issues/5039

**Comment by Jostino** [comment]
https://github.com/timgrossmann/InstaPy/issues/5039

**Comment by hamzadiaz** [comment]
I have the same error
