### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by datteba** [InstaPy/InstaPy#507]
Hi! I get this error when I try to interact with user followers

![image](https://user-images.githubusercontent.com/30053143/29073721-ef5e27ce-7c4c-11e7-81ca-3692fb6d55eb.png)

**Comment by timgrossmann** [comment]
@datteba **Could you please post your quickstart.py file?**
Make sure to remove your username and password

@ahmadudin

**Comment by ahmadudin** [comment]
@datteba i could not reproduce the error yet, your quickstart file will be a big help.

**Comment by timgrossmann** [comment]
**@datteba I really can't reproduce this behaviour, please post your quickstart.py!**

**Comment by datteba** [comment]
```python
from random import randint
from random import sample
from time import sleep
from instapy import InstaPy

friend_list = ['friend1', 'friend2']

tag_list = ['tag1', 'tag2']

rnd_1 = randint(20, 100)
rnd_2 = randint(20, 40)
rnd_3 = randint(30, 50)
rnd_interact = randint(2, 10)

InstaPy(username="user", password="pass") \
  .login() \
  .set_upper_follower_count(limit=5000) \
  .set_lower_follower_count(limit=10) \
  .set_dont_include(friend_list) \
  .set_do_follow(enabled=True, percentage=10, times=1) \
  .set_user_interact(amount=rnd_interact, random=True, percentage=100, media='Photo') \
  .follow_user_followers(['user1'], amount=rnd_3, random=True, interact=True) \
  .like_by_feed(amount=rnd_1) \
  .like_by_tags(sample(tag_list, 40), amount=20) \
.end()

```

**Comment by timgrossmann** [comment]
@datteba Does the error occur every time?

@ahmadudin

**Comment by datteba** [comment]
yes @timgrossmann every time

**Comment by ahmadudin** [comment]
I still can not reproduce the error. The error occurs when second parameter of `sample()` is non-int datatype. So i used `ceil()` to round up any decimal number produced by the `self.user_interact_percentage*len(userFollowed)/100` and make sure the type is int.

**Comment by datteba** [comment]
@ahmadudin @timgrossmann 

I removed ceil() and now it works fine!

userFollowed = sample(userFollowed, self.user_interact_percentage*len(userFollowed)/100)
instead of
userFollowed = sample(userFollowed, ceil(self.user_interact_percentage*len(userFollowed)/100))
