### ISSUE TITLE
ACTION BLOCKED BY LIKING AND COMMENTING 

### ISSUE THREAD

**Issue by prototype127** [InstaPy/InstaPy#5074]
Yesterday it was all fine but today it gives me the action blocked message idk whats happening ...iam running the super simple script ... if someone knows how to fix this plz help
thanks in advance

**Comment by Tr1pke** [comment]
In Linux Press ctrl+c

**Comment by prototype127** [comment]
@Tr1pke can you plz expain this ?

**Comment by Tr1pke** [comment]
Then instapy stops and you do it manually on the mobile app, forget the bot 
Instagram recognizes instapy.

**Comment by prototype127** [comment]
Jahajahaj

**Comment by prototype127** [comment]
Lmeee find a solution then :P

**Comment by Tr1pke** [comment]
There isn’t. It’s already going on for months

**Comment by prototype127** [comment]
No it was working fine only since yesterday i got this issue

**Comment by Tr1pke** [comment]
With how many follows or likes ?

**Comment by johnvfitness** [comment]
same error

**Comment by iamklaus** [comment]
Same, the bot even cannot login

**Comment by prototype127** [comment]
It logins for more work for 30 mins and then it shows action blocked

**Comment by prototype127** [comment]
For me *

**Comment by andropovleva** [comment]
Same problem. Block liking and commenting
