### ISSUE TITLE
ERROR cannot get the post profile pic url

### ISSUE THREAD

**Issue by Jostino** [InstaPy/InstaPy#5075]
Instapy 0.6.3
RaspBerry Pi 3+
RaspBian Buster

This error occurs on every single picture my bot try to like:
```
ERROR [2019-09-14 14:24:21] [username]  ~cannot get the post profile pic url
INFO [2019-09-14 14:24:21] [username]  --> Not a valid user: ---> Sorry, couldn't get if user profile pic url
```
(i've searched the error but I've found a very old topic of Feb 2018 that was a bitter different from this error).

**Comment by turtlebking** [comment]
This is similar to “window.insta_data is undefined” in other file (util.py?)
I remember come across those line of code when I look at this file.
I will fix it :)

**Comment by Jostino** [comment]
Apparently after changed IP on my connection, the problem disappeared, so maybe it was a soft block (another account was giving me the BLOCK LIKE warning). So this 2 behavior are linked?!?

**Comment by turtlebking** [comment]
in web browser development console, type:
window._sharedData.entry_data.ProfilePage[0].graphql.user.profile_pic_url

should return sth like
"https://instagram.fhkg4-2.fna.fbcdn.net/vp/49306ef483e457f5dab6ab398daa5ad5/5DFF3F5C/t51.2885-1....

i guess IG directed to other page when they giving you BLOCK LIKE warning,
so no profile_pic_url return
![debug](https://user-images.githubusercontent.com/37171296/64916136-e4d32b00-d7a9-11e9-9edf-854f783901a5.jpg)
