### ISSUE TITLE
IG app vs IG website (Website is limited for actions bot or no bot)

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#5081]
I did a test, and this is what I found out:

i follow already for at least 10 days about 300+ people each day and also unfollow about 300+ people each day already for about 2 weeks now... maybe longer and more because I really exaggerate on the app.
I do it manually on the OFFICIAL IG APP (on the bus) every morning and every evening and NEVER had any block or limitation. I can do more in my daily 20 min bus ride then in one complete week running instapy ...

I need to do it on the MOBILE APP because when I try to do it manually on the IG website it will block me directly or it will stops my actions. So in other words the IG website is just generally limited for actions. bot or no bot (no bod=manual clicks)
this means, If you make a bot that needs the website to perform actions the bot will be useless.

only solution is a virtual environment with a android emulator + IG APP what will be automated.
The website is simply limited

**Comment by lucasvictor3** [comment]
I hav the same conclusion as you... The bot doesn't offers miraculous results, unless you hav an script to interact perfectly.. and Yes, apparently they are focused on tracking these bots, probabily firefox will soon be obsolete for this activity. Otherwise, what's the secret of these sites that offer these services? Like https://socialcaptain.com/ ? Must be more than a android simulator and VPN.

**Comment by Tr1pke** [comment]
Maybe it is a android emulator since the website is limited, or they have a deal with IG because that brings them money and in the end it’s about money

**Comment by webkris** [comment]
All of my Instagram web activities have been blocked this time around.
I had the settings on 1/3rd of the "conservative don't get banned" settings - and it's not enough. Also 30 likes a day from a bot that could get banned is useless.

Angry - I did the same thing - I opened up the app on my phone and spent a lunchtime doing what I wanted the bot to do for that last week in ONE HOUR. I must have done 300 likes in 45 min. Comments, block, follows, un-follows, etc. The app is seemingly unrestricted (for now of course). I think I can cobble a phone running some basic screen macros... YMMV

**Comment by Tr1pke** [comment]
Indeed. You can do even more in 30 min manually on the app then your bot in a couple of weeks , FYI yes I mean couple of weeks

**Comment by noesiscode** [comment]
I tried a mobile simulator extension on a desktop version of chrome. It opens up instagram like the app and I'm able to read direct messages and post photos. I'm guessing if using instagram like that on a browser has limitations like your test cases or not....

**Comment by jeremycjang** [comment]
Do you guys think this could be true for the Instagram Microsoft Store app as well? It's official/developed by Instagram too, but can be used on Windows desktops

**Comment by Tr1pke** [comment]
Can you try? i don't have windows

**Comment by jeremycjang** [comment]
I'll test and share results

**Comment by jeremycjang** [comment]
@Tr1pke @webkris  Can you please confirm if you did 300 follows in an hour? Even in-app, the limit before seemed to be 60 max follows/hour

**Comment by Tr1pke** [comment]
I have 249 users that I follow and I always go above 500 then I stop now I leave it for 2 days then I unfollow a day because else it asks me constantly to change my password 

And believe me it’s not 60 a hour 
Don’t use your bot a couple of days and please try to follow 200 to start in one go. It works on the app not the website. The website is useless

**Comment by jeremycjang** [comment]
I was able to successfully follow 250 people from the Windows store app somewhat spread out throughout the day without any issues, going to try unfollowing tonight

**Comment by Tr1pke** [comment]
You can leave them for a couple of days and gain some extra followers 🙂

**Comment by dwai03** [comment]
@Tr1pke So I have been manually doing this for about 2 weeks and got a action block yesterday on all follows and likes.  I was doing the same about what you were 300 a day or so follows and unfollows.  Are you able to still manually go at this pace??

**Comment by Tr1pke** [comment]
I do 200 a day. Not on Saturday or Sunday. I don’t take the bus then 😃

**Comment by dwai03** [comment]
I was thinking of taking the saturday sunday off to rest it.  Ok ill lower
my numbers.   Thanks
And how long have you been doing it?  and thats 200 follow and then 200
unfollows a day?  Not one of each?

**Comment by Tr1pke** [comment]
I unfollowed 200 person during the day itself

**Comment by dwai03** [comment]
So is it 400 total actions or 200?

Thanks

**Comment by Tr1pke** [comment]
Yes 400 during the day. Now I follow manually and after I unfollow with the bot. I have all my real friends white listed 
The only problem I have I can only unfollow people that doesn’t follow me back. If I use the unfollow all line it comes back ‘unfollow all is unavailable at this moment, skipping’ 

If that would work I can unfollow with the bot and follow manually. 
Now I unfollow with the bot people that doesn’t follow me back and after I do the rest

**Comment by dwai03** [comment]
Yea I couldn't get that function working I tried to debug code awhile ago.
I just do lastest followes and go manually do it

**Comment by Tr1pke** [comment]
Yes but still the nonfollowers=true is working perfectly, so it’s strange that allfollowers is not working.

**Comment by jeremycjang** [comment]
@dwai03  Did you get that block while following manually inside the official app?

@Tr1pke Does unfollowing from a custom list still work correctly?

**Comment by dwai03** [comment]
Yes I was manually doing it and still got the block.

**Comment by tjuzen** [comment]
Same problem here, using instagram via a navigator result in an almost instant block.
Either u find a bot that works on an emulation either u do it manually on your phone.

Doing it manually I can reach 250 follows/day then unfollow them at night without problem regarding Instagram but its taking +1h/day which is A LOT of time

**Comment by theflyingmantis** [comment]
@Tr1pke  Can you share Instagram Web results? After how much engagement manually, does the instagram web restricts?

**Comment by Tr1pke** [comment]
Like the comments above it works. If you want details and numbers you need to try it yourself. I just want to be above 10k followers which I have. Now I just do it slowly with 100 followers and 100 unfollows a day to make a buffer 

PS it’s time to forget about InstaPy and move on. It’s dead. Deal with it. It was fun, but everything ends. This ended a couple months ago, don’t sit on dead bodies it stinks

**Comment by theflyingmantis** [comment]
@Tr1pke Quoting you - ```I need to do it on the MOBILE APP because when I try to do it manually on the IG website it will block me directly or it will stops my actions. So in other words the IG website is just generally limited for actions.```
@lucasvictor3 - also, could you also write your conclusions on instagram web (if any).
I am building my own chrome extension over instagram web and it's in the midway. So just want to gain you insight on do they block instagram web actions even without a bot? If yes, what is the limit as you said so. Which test did you perform to come to this conclusion? 
Thanks

**Comment by Tr1pke** [comment]
In all honestly stay away from the Instagram website. Bot or no bot. Use the app if you don’t want to get blocked directly

**Comment by theflyingmantis** [comment]
@Tr1pke 
Thanks mate. But still you didn't answer the question. 

> Which test did you perform to come to this conclusion? Or is it just your inner feeling? If there is any test, do you remember any data?

**Comment by Tr1pke** [comment]
On the website I got blocked after about 20 follows. On the app I follow every day about 100 ppl and never had a block. Is enough for me to know that I have to stay away from the website

**Comment by alexal1** [comment]
Created a script for mobile app: https://github.com/alexal1/Insomniac
It works with Android devices through Android Debug Bridge. Like InstaPy using Selenium, it uses Android UI testing framework called UI Automator. Please have a look, should I continue working on it?
