### ISSUE TITLE
Question re: Interact with someone else's followers/following

### ISSUE THREAD

**Issue by gitpatrickhub** [InstaPy/InstaPy#509]
Does this feature support only interacting with someone else's followers? I.E., I don't want to follow any of the provided user accounts followers, I only want to interact with the followers by liking & commenting on posts. If so, how do you configure the lines below?

```
session.set_user_interact(amount=5, random=True, percentage=50, media='Photo') 
session.follow_user_followers(['friend1', 'friend2', 'friend3'], amount=10, random=False, interact=True)
```

**Comment by timgrossmann** [comment]
@gitpatrickhub Unfortunately, this feature is not supported yet...

**Comment by gitpatrickhub** [comment]
@timgrossmann can this be added to the list of features to be created? This would be very helpful feature, as not all InstaPy users want to systematically follow or unfollow users.

**Comment by timgrossmann** [comment]
@gitpatrickhub Hmm... I think we can at least keep this issue open.
If you posted this earlier, we could've made this part of #492

**Comment by gitpatrickhub** [comment]
@timgrossmann thanks! I requested it, but failed to explicitly state that following should not be required to support the "interact with".

**Comment by datteba** [comment]
Really interested in this too! I only want to like posts of user followers without follow them. Possibly I would like to always like also the last uploaded photo. (ignoring private profiles)

@timgrossmann I could pay 10$ for this implementation

**Comment by gitpatrickhub** [comment]
@timgrossmann @datteba I'd be willing to contribute, as well, to get this delivered soon

**Comment by timgrossmann** [comment]
@datteba @gitpatrickhub Well, then let's open up a bounty to get this implemented ASAP 😉 

I think with more than 10$ we'll get this implemented in no time.
I'll create a bounty issue for that soon.

**Comment by timgrossmann** [comment]
@BernardoGO <strike>Would you be interested in refactoring your `follow_user_followers/following` a little bit? 
25$ Bounty? 😉 </strike>

**Comment by BernardoGO** [comment]
Yes, I'm interested. 
I'll start working on it later today. Thanks

**Comment by timgrossmann** [comment]
@BernardoGO <strike>Oh perfect, I'll write an Bounty Issue for it.
This will be the first issue where some of the interface will be changed.
We will move from a `.like_by...` and `.follow_...` to a global `.interact_with`

I think this will be way better since people want to choose on what they do and don't, e.g. like in this example where they only want to get all the users and like their stuff without following.
Or the people that want to only follow from tags instead of always liking and maybe following.</strike>

**Comment by timgrossmann** [comment]
@BernardoGO I think we have to discuss how this should look first... I just tried to write an issue for it and came across some problematic things.

However, you could modify the code to the needs of @datteba and @gitpatrickhub and at least get that 10$ for the small changes.

I will open up an issue to discuss the mentioned interface change and gather some information. 

Adding this change should be a good start for the big refactor.

**Comment by timgrossmann** [comment]
@datteba @gitpatrickhub Feel free to post the bounty you mentioned here: https://www.bountysource.com/issues/48047739-question-re-interact-with-someone-else-s-followers-following

**Comment by gitpatrickhub** [comment]
@timgrossman $10 added to bounty

**Comment by datteba** [comment]
bounty posted ;)

**Comment by ahmadudin** [comment]
i think the requested feature is simply resolved by skipping the following script

**Comment by BernardoGO** [comment]
It is done: #528

**Comment by timgrossmann** [comment]
@datteba @gitpatrickhub Could you do a `git pull` and test if the behaviour is what you wanted? We will then close this issue.

**Comment by gitpatrickhub** [comment]
I’m out of town and don’t have remote access configured for my rpi3. Will try tomorrow evening. Thanks @timgrossmann  @bernardgo

**Comment by datteba** [comment]
@timgrossmann I have always the same problem with Ceil(). If I remove it mannualy from instapy.py it seems to work. I use windows 10, I don't know if this may be the cause.

![image](https://user-images.githubusercontent.com/30053143/29268643-fcc2f9f8-80ed-11e7-83d0-fd46f9e46166.png)

Then, it would be nice if it was possible to always like the last uploaded photo.

If I want to like + follow a list of user followers and then only like another list of user followers how should I configure my quickstart?

.set_user_interact(amount=3, random=True, percentage=100) \
.set_do_like(enabled=True, percentage=100) \
.follow_user_followers(['users'], amount=10, random=True, interact=True) \
.interact_user_followers(['users'], amount=10, random=True) \

Is this correct?

**Comment by BernardoGO** [comment]
@datteba, it is correct. Did it work?

~~About the ceil error, I've been trying to reproduce it without success since @timgrossmann mentioned it.
Can you post a picture of what's on the browser when it happen?~~

**Comment by BernardoGO** [comment]
@datteba The error is fixed by #552.

**Comment by datteba** [comment]
Thank you very much @BernardoGO! It works now!

**Comment by timgrossmann** [comment]
@datteba Can the issue be closed now so that @BernardoGO can claim the bounty?

**Comment by datteba** [comment]
Of course Tim! 

@timgrossmann

**Comment by gitpatrickhub** [comment]
@timgrossmann sorry, haven't had a chance to do a pull, but trust that it works. Thanks @BernardoGO 
 
Will this be merged into the Master now?

**Comment by timgrossmann** [comment]
@gitpatrickhub It already is 😉

**Comment by BernardoGO** [comment]
Thanks, @gitpatrickhub and @datteba.

**Comment by gitpatrickhub** [comment]
@BernardoGO @timgrossmann 
Can you confirm this is the correct setup if I want to Like 3 posts each of 300 followers of a specified user account?

```
.set_user_interact(amount=3, random=False, percentage=100)
.set_do_like(enabled=True, percentage=100)
.interact_user_followers(['accountOfUser'], amount=300, random=False)
```

**Comment by BernardoGO** [comment]
@gitpatrickhub, it is correct. It will like the first 3 posts.
@datteba Since you've posted a bounty you also have to set it as solved [here](https://www.bountysource.com/issues/48047739-question-re-interact-with-someone-else-s-followers-following).

**Comment by datteba** [comment]
@BernardoGO done ;)

Would it be possibile to always ignore private profiles, users without uploaded photos and without profile picture?

**Comment by salbatron** [comment]
#1458
