### ISSUE TITLE
unfollow alle users except "list"

### ISSUE THREAD

**Issue by Tr1pke** [InstaPy/InstaPy#5090]
I would like to perform this action: session.unfollow_users(amount=126, nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)
in this action I want that insteps ignores users from a list, what option is that?
I know the option that instapy unfollows from a list but I want the opposite 

I follow manually every day 250 users (takes me 5 minutes) but I also want to unfollow them after 50 hours in a crontab

I just want to check if this works since the web base version of instagram has e low limit of actions ...

**Comment by spikeyhair** [comment]
you may use session.set_dont_include. Users listed in session.set_dont_include will be white listed.

**Comment by Tr1pke** [comment]
session.set_dont_include(custom_list_enabled=True, custom_list=friends.txt, custom_list_param="all")


Can i not make a list.txt instead of a whole like with 250 users?

and i also get this error 

On session start was FOLLOWING 412 users & had 9835 FOLLOWERS
[Session lasted 56.32 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-09-22 10:05:17] [***]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "InstaPy/***.py", line 58, in <module>
    session.set_dont_include(custom_list_enabled=True, custom_list=friends.txt, custom_list_param="all")
NameError: name 'friends' is not defined
There is a screen on:



My customlist looks like this:
["friend", "friend", "friend"]
