### ISSUE TITLE
Instagram blockes me again

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5091]
Hi,
using latest dev branch.
After about 30 likes, 14 follows and about 20 unfollows instagram blocked me for 3 days. In mobile I can't like, follow, unfollow too.

Any idea why? Instagram app shows me I was using 3rd party app etc etc.

**Comment by prototype127** [comment]
same

**Comment by tjuzen** [comment]
Hey. I do have the same. Maybe our limits are too high? 
I have 300 likes/day and 170 follow/day.

**Comment by davidvee7** [comment]
I can't do any likes, follows or unfollows per day.  I am totally blocked and it's been this way for weeks.

**Comment by danniefraim** [comment]
I've noticed that when I'm running my bot from an IP adress that belongs to Amazon Web Services, I get blocked almost immediately. But when I proxy through a server at home, I can do many, many more requests before being blocked. So there is some IP filtering going on in the bot detection.
