### ISSUE TITLE
ERROR: clarifai 2.6.2 has requirement configparser<4,>=3.5, but you'll have configparser 4.0.2 which is incompatible.

### ISSUE THREAD

**Issue by Dimac16S** [InstaPy/InstaPy#5094]
Hi can anyone help me? When i write `pip install instapy` in **cmd** i get this error:
`ERROR:` clarifai 2.6.2 has requirement configparser<4,>=3.5, but you'll have configparser 4.0.2 which is incompatible.`

**Comment by bigjjjim** [comment]
I have the same error, did you find a way to fix it? I am a beginner and I am not sure how to replace configparser for an ulterior version inside the package or even if it is what I am supposed to do. I saw somewhere I had to modify the requirement.txt file but still confused about where this file is or if I should create it.

**Comment by Vadoid** [comment]
Try "pip install clarifai --upgrade"

**Comment by sclmaomao** [comment]
> Try "pip install clarifai --upgrade"

Yes, this one works for me, thank you!

**Comment by magcrider** [comment]
> > Try "pip install clarifai --upgrade"
> 
> Yes, this one works for me, thank you!

Worked for me adding `python3 -m`

`python3 -m pip install clarifai --upgrade`

**Comment by gaelsantos** [comment]
> Try "pip install clarifai --upgrade"

thank u, work from me too!

**Comment by peidrao** [comment]
> Try "pip install clarifai --upgrade"

goodd

**Comment by Xnuvers007** [comment]
> Try "pip install clarifai --upgrade"

Thank You ^^

**Comment by irfannurzaman** [comment]
> Coba "pip install clarifai --upgrade"
Yes, this one works for me, thank you!
