### ISSUE TITLE
Weird issue ..I don't know how to explain.. sorry

### ISSUE THREAD

**Issue by issamarmas** [InstaPy/InstaPy#5098]
When instapy open firefox browser and tying to following people ... they say "this action is blocked"
but when i try by myself to follow someone on chrome it works fine

**Comment by InfraRedApple** [comment]
You're blocked. You'll have to wait a week or so before you are  unblocked.

**Comment by issamarmas** [comment]
> You're blocked. You'll have to wait a week or so before you are unblocked.
yes i know.. but it happen only when i use instapy

**Comment by issamarmas** [comment]
it doesn't make sence

**Comment by MariuSStar** [comment]
![71391854_687446348423251_2074117291527634944_n](https://user-images.githubusercontent.com/54725727/65549829-f98c8d00-df26-11e9-8425-09541a717de9.png)
This is the issue right? "This action was blocked. Please try again later. We restrict certain content and actions to protect our community...." and the script sees this as a true unfollow, it even looks right in the page, until you refresh the page... 

I think Instagram can now see that this is a bot. As a manual unfollow on different browser works, also on mobile.

Any fixes or recommendations for this ? 

Thank you

**Comment by davidvee7** [comment]
This actually started happening to me a couple weeks ago - I tried again today and I'm still blocked.  I agree that I think instagram knows we are using bots now and is immediately blocking us.

**Comment by issamarmas** [comment]
> This actually started happening to me a couple weeks ago - I tried again today and I'm still blocked. I agree that I think instagram knows we are using bots now and is immediately blocking us.

exactly .. we need to fix this

**Comment by Wakkox** [comment]
Happened to me too today. Until now I only got: Error try again later.

**Comment by issamarmas** [comment]
I found a solution : change username when you want to run your boot 
it works.

**Comment by InfraRedApple** [comment]
What?

**Comment by denis-gref** [comment]
> I found a solution : change username when you want to run your boot
> it works.

@issamarmas what exactly do you mean?

**Comment by MariuSStar** [comment]
@issamarmas, you mean use the boot for another account? That doesn't really fix my issue for my account.... Does it?
