### ISSUE TITLE
Rewrite README

### ISSUE THREAD

**Issue by nickbullll** [InstaPy/InstaPy#510]
I have a bot that works with cronjob on Ubuntu server, all works fine for months and today I decided to pull InstaPy from Github and see what is going on with the project.
And....
I don't understand how to work with new changes....docker?microservice architecture?....in readme I see 10% of new changes (that I can't understand without deep learning how to work with docker...really??) and 90% of old. How to work and develop InstaPy if you can't understand what is going on ? 

Please take the time and change the readme and all the integration examples, as 99% of the new audience does not understand how to start.

**Comment by timgrossmann** [comment]
@abraztsov You still simply need to follow the Getting Started part and run a file, for example one that's called `quickstart.py` and add the functionality there.

**Comment by nickbullll** [comment]
@timgrossmann  There is no such file anymore, now there is a `docker_quickstart`. 
The problem is that I myself formatted README file a month ago and did pull request.

**Comment by timgrossmann** [comment]
@abraztsov Well, we can add that again

**Comment by nickbullll** [comment]
@timgrossmann So for the previous work flow I just need to add `quickstart` and ignore `docker_ quickstart` ?

**Comment by timgrossmann** [comment]
@abraztsov Yes exactly, it works the exact same way as before 😉

**Comment by converge** [comment]
We reorganized the README.md this week, I think it's easier to use it because we have a table of content. If you wanna update it, or have some doubt, please reopen this issue.
