### ISSUE TITLE
Let's see if I get at least 1 comment!  Chrome driver compatibility with Chrome on MacOS.  

### ISSUE THREAD

**Issue by Wisdomlocker** [InstaPy/InstaPy#5102]
## Expected Behavior

Mac_start command works

## Current Behavior

Hello ladies and gentlemen.   

This has been discussed several times but my error is slightly different and none of the proposed solutions work (such as #4800 or 2386)

Error: 

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2019-09-24 23:42:41] [toucheys_]  Using built in instapy-chromedriver executable (version 2.46)
ERROR [2019-09-24 23:42:43] [toucheys_]  Message: session not created: This version of ChromeDriver only supports Chrome version 75
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/instapy/browser.py", line 163, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 75

Traceback (most recent call last):
  File "../quickstart.py", line 24, in <module>
    headless_browser=True)
  File "/Library/Python/2.7/site-packages/instapy/instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "/Library/Python/2.7/site-packages/instapy/instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /Library/Python/2.7/site-packages/instapy_chromedriver/chromedriver_mac64
logout
Saving session…
…copying shared history…
…saving history…truncating history files…
…completed.

[Process completed]

## Possible Solution (optional)

the problem is that Chrome 75 can't be found (for mac) - links provided don't work...  and installing another Chrome driver doesn't work!  

tried installing  chrome driver 76 here - no result. 

/usr/local/lib/python3.7/site-packages/instapy_chromedriver/chromedriver_mac64
with the new downloaded and unzipped chromedriver(make sure to change the name to chromedriver_mac64

gonna ask some stupid questions here.. please bear with me. Great project BTW! thanks @timgrossmann 
 - Is Instapy using both Python 2.7 AND 3.7? (I have 3.7 in my local/lib folder) 
 - error say that instapy is using chrome driver executable 2.46.  Why is the latest chromedriver is version 77? 
 - what is the real rub here...?  is Instapy not always working with the latest copy of Chrome and/or Chromedriver and the trick is to figure out which versions to use? Obviously it is impossible to keep up with constant chrome / CD updates, right? 
 - My comp is rather old - can it be that my macOS release just don't jive? (sierra 10.12.1)
 - also tried to delete all instapy and to reinstall again using "clone or download" function from github site

sorry, not an IT guy, + trying mac OS with Instapy for the first time!  no luck...  hope not breaking any rules here.   Cheers! 

## InstaPy configuration

mac OS Sierra 10. 12.1
Chrome 77 and tried 74 
Chrome driver (I think tried just about all of them by now)

**Comment by cprkrn** [comment]
I get a similar message:
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy_chromedriver/chromedriver_mac32

Hate to say I don't have an answer for you. I'm having issues on both OSx and Linux. Used to find workarounds and fixes but haven't been able to lately. Will update if I do!

**Comment by Wisdomlocker** [comment]
thanks @cooperkernan .  will also keep looking for answers ! have a great day!

**Comment by yeyou4760** [comment]
https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#dealing-with-selenium-common-exception-issues

**Comment by cprkrn** [comment]
Wow that worked! Swapped out chromedriver for an older version to work with Chrome 77. Thanks so much @yeyou4760. Let me know if it works for you, @Wisdomlocker!

**Comment by largalaga** [comment]
thanks a lot. this worked great. Finally. 

> https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#dealing-with-selenium-common-exception-issues

**Comment by Skorp00** [comment]
Now this LMAO


 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/spammyboy420/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2020-09-15 12:13:40] [xxxx]  Using built in instapy-chromedriver executable (version 2.46)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-09-15 12:13:41] [xxxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2020-09-15 12:13:41] [xxxx]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-09-15 12:13:42] [xxxx]  - Internet Connection Status: ok
INFO [2020-09-15 12:13:42] [xxxx]  -- Connection Checklist [2/2] (Instagram Server Status)
INFO [2020-09-15 12:13:45] [xxxx]  - Instagram WebSite Status: Currently Up 
INFO [2020-09-15 12:13:45] [xxxx]  - Instagram Response Time: 115.942 ms 
INFO [2020-09-15 12:13:45] [xxxx]  - Instagram Reponse Code: 200
INFO [2020-09-15 12:13:45] [xxxx]  - Instagram Server Status: ok
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

.............................................................................................................................
CRITICAL [2020-09-15 12:14:00] [xxxx]  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2020-09-15 12:14:00] [xxxx]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 20.12 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-09-15 12:14:00] [xxxx]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
