### ISSUE TITLE
INSTAPY IS DEAD ??

### ISSUE THREAD

**Issue by prototype127** [InstaPy/InstaPy#5105]
Getting action block message .. instagram is very strict nowadays .. we need changes in instapy as it gets blocked eveytime :(. . Is it still working for you guys?

**Comment by riccardovalente** [comment]
Yes it is still working if you don’t abuse the system, I.e. you’re careful with rate control and delays, and don’t keep trying while you’re blocked without taking a break.

Go to Discord and you’ll see plenty of advice.

**Comment by prototype127** [comment]
> Yes it is still working if you don’t abuse the system, I.e. you’re careful with rate control and delays, and don’t keep trying while you’re blocked without taking a break.
> 
> Go to Discord and you’ll see plenty of advice.

Thankyou for your reply ! Can you send me the discord server link or id ..

**Comment by prototype127** [comment]
> Yes it is still working if you don’t abuse the system, I.e. you’re careful with rate control and delays, and don’t keep trying while you’re blocked without taking a break.
> 
> Go to Discord and you’ll see plenty of advice.

"""
This template is written by @Edhim
What does this quickstart script aim to do?
- I am using simple settings for my personal account with a crontab each 3H,
it's been working since 5 months with no problem.
"""

from instapy import InstaPy
from instapy.util import smart_run

# get a session!
session = InstaPy(username='', password='')

# let's go! :>
with smart_run(session):
    # settings
    session.set_relationship_bounds(enabled=False,
                                    potency_ratio=-1.21,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                    max_following=5555,
                                    min_followers=45,
                                    min_following=77)
    session.set_do_comment(True, percentage=50)
    session.set_comments(['aMazing!', 'So cool!!', 'Nice!', 'wow looks nice!',
                          'this is awesome!'])

    # activity
    session.like_by_tags(
        ['xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx',
         'xxx', 'xxx', 'xxx'],
        amount=8, skip_top_posts=True)



Iam using this script ... not follow unfollow . . So can you tell me where i can set delays and rate control ?

**Comment by riccardovalente** [comment]
> > Yes it is still working if you don’t abuse the system, I.e. you’re careful with rate control and delays, and don’t keep trying while you’re blocked without taking a break.
> > Go to Discord and you’ll see plenty of advice.
> 
> Thankyou for your reply ! Can you send me the discord server link or id ..

It's in the README!! https://github.com/timgrossmann/InstaPy/blob/master/README.md

**Comment by ghost** [comment]
so sad :/

**Comment by Tr1pke** [comment]
> > Yes it is still working if you don’t abuse the system, I.e. you’re careful with rate control and delays, and don’t keep trying while you’re blocked without taking a break.
> > Go to Discord and you’ll see plenty of advice.
> 
> """
> This template is written by @Edhim
> What does this quickstart script aim to do?
> 
> * I am using simple settings for my personal account with a crontab each 3H,
>   it's been working since 5 months with no problem.
>   """
> 
> from instapy import InstaPy
> from instapy.util import smart_run
> 
> # get a session!
> session = InstaPy(username='', password='')
> 
> # let's go! :>
> with smart_run(session):
> # settings
> session.set_relationship_bounds(enabled=False,
> potency_ratio=-1.21,
> delimit_by_numbers=True,
> max_followers=4590,
> max_following=5555,
> min_followers=45,
> min_following=77)
> session.set_do_comment(True, percentage=50)
> session.set_comments(['aMazing!', 'So cool!!', 'Nice!', 'wow looks nice!',
> 'this is awesome!'])
> 
> ```
> # activity
> session.like_by_tags(
>     ['xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx',
>      'xxx', 'xxx', 'xxx'],
>     amount=8, skip_top_posts=True)
> ```
> 
> Iam using this script ... not follow unfollow . . So can you tell me where i can set delays and rate control ?

in the readme on he main page

**Comment by 4antii** [comment]
> Yes it is still working if you don’t abuse the system, I.e. you’re careful with rate control and delays, and don’t keep trying while you’re blocked without taking a break.
> 
> Go to Discord and you’ll see plenty of advice.

@riccardovalente, can you share a link with me?

**Comment by kevXZY** [comment]
@riccardovalente @4antii need link too please

**Comment by riccardovalente** [comment]
on the README https://github.com/timgrossmann/InstaPy/blob/master/README.md
