### ISSUE TITLE
New Login Bug

### ISSUE THREAD

**Issue by marudon** [InstaPy/InstaPy#511]
Since a few days there is the following bug when trying to login the script. Maybe any changes in code of instagram? Does anybody know a solution?

login_util.py", line 27, in login_user
    action = ActionChains(browser).move_to_element(inputs[0]).click().send_keys(username) \
IndexError: list index out of range

**Comment by timgrossmann** [comment]
@marudon Did you actually do a `git pull` before submitting this issue?

**Comment by marudon** [comment]
No. Is there a bugfix already? The script worked fine and without changes at the next moment there was this bug :-(

**Comment by FBosler** [comment]
Hey Tim,
I know this is a really dumb question, but I am still curious. Maybe you can help a fella out. How do I update my instaPy version on the server.

Cheers
Fabian

**Comment by marudon** [comment]
@timgrossmann: I pulled login_util.py - now it works again. Thanks :-)

**Comment by timgrossmann** [comment]
@FBosler Follow the instructions in the `How_to_Ubuntu` once you've done that you can simply `cd InstaPy` and in the InstaPy folder you only have to do a `git pull`. 
This will update it with the newest changes
