### ISSUE TITLE
Instapy User Interaction: How to?

### ISSUE THREAD

**Issue by dimhvm** [InstaPy/InstaPy#5115]
Hi, I am quite new at Instapy and I am trying to configure my bot to make him like multiple photos of the same account. That is: if the account has the right requirements I set at the beginning (num followers, not business, no empty profile pic ecc ecc), go in his/her profile and comment/like more than one picture.
All the commands I am using are in the description of Instapy, so I suppose my errors are only in the order of the action.

Up to now, the bot is just following the instruction to like/comment/follow one picture per profile.

I attach my script:

## InstaPy configuration

  session.set_do_like(enabled=True, percentage=90)
    session.set_do_follow(enabled=True, percentage=50, times=1)
    session.set_do_comment(enabled=True, percentage=10)
    session.set_comments(['Nice shot! '], media='Photo')
    
    session.set_comments(['Great Video @{} !'], media='Video')

    session.set_skip_users(skip_private=True,
                       skip_no_profile_pic=True,
                       no_profile_pic_percentage=100) #ignora i profili senza foto
    
    session.set_skip_users(skip_private=True,
                       skip_no_profile_pic=True,
		               skip_business=True,
		               business_percentage=80) #ignora i profili aziendali
 
    session.set_delimit_liking(enabled=True, max_likes=100, min_likes=2)
    session.set_delimit_commenting(enabled=True, max_comments=20, min_comments=0)
    session.set_relationship_bounds(enabled=True,
				 potency_ratio=1.34,
				  delimit_by_numbers=True,
				   max_followers=800,
				    max_following=1000,
				     min_followers=10,
				      min_following=50,
				       min_posts=10,
                max_posts=500)
    session.set_action_delays(enabled=True, like=5.2, randomize=True, random_range_from=10, random_range_to=140)
  
    # activity
    session.set_user_interact(amount=5, randomize=True, percentage=100, media='Photo')
    session.like_by_tags(my_hashtags, amount=15, media=None)
    
    session.unfollow_users(amount=50, InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=168 * 60 * 60, sleep_delay=50)
     
    session.set_do_story(enabled = True, percentage = 70, simulate = False)

    session.join_pods()

Where am I doing it wrong? Thanks

**Comment by kami4ka** [comment]
Looks like you have not too much different comments. Add more comments inside `session.set_comments`

**Comment by dimhvm** [comment]
> Looks like you have not too much different comments. Add more comments inside `session.set_comments`

Ehi Kami4ka thank you for your answer. I have deleted all the comments just in copying the code here on github to make it shorter. In the code there are at least 15 different comments.

**Comment by dimhvm** [comment]
I think the order is completely wrong. There is something which "overwrites" the command to interact. I have tried to move the command set_user_interact at the beginning, at the end, almost everywhere but nothing changed... :(
