### ISSUE TITLE
RPi and Geckodriver

### ISSUE THREAD

**Issue by tE3m** [InstaPy/InstaPy#5118]
## Expected Behavior
The correct geckodriver version for each platform is downloaded.

## Current Behavior
The newest geckodriver version gets downloaded, which doesn't include an arm7hf version.

## Possible Solution (optional)
Downloading a webdriver after recognizing the platform

**Comment by mafredas** [comment]
@TarekJ03  i have the same issue. I tried to downgrade the geckodriver but without success. Maybe there is a conflict between the latest version of Firefox and Geckodrivers for RPi. My logs file returns the following error. I would be grateful, If you have any idea.

> 1570118323582	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.SZrcHUin0ZvH"
> 1570118330720	Marionette	INFO	Listening on port 2828
> [Child 5507] ###!!! ABORT: Aborting on channel error.: file /build/firefox-esr-YKrXxr/firefox-esr-52.9.0esr/ipc/glue/MessageChannel.cpp, line 2152
> [Child 5507] ###!!! ABORT: Aborting on channel error.: file /build/firefox-esr-YKrXxr/firefox-esr-52.9.0esr/ipc/glue/MessageChannel.cpp, line 2152

**Comment by tE3m** [comment]
Sorry if this was misleading, I do know how to fix this, but instead of a workauround I was suggesting for this to be automated. You can simply download the v0.23.0-armh7f file and replace `InstaPy/assets/geckodriver` and `InstaPy/assets/gecko/v0.25.0/geckodriver-linux32` with the extracted executable and put the tar archive to `InstaPy/assets/gecko/v0.25.0/geckodriver-v0.25.0-linux32.tar.gz`(keep the names for all of them). The reason for this is, that there is no arm7hf version of the latest geckodriver, but InstaPy always tries to wnsure the newest webdriver is installed.

**Comment by roncam82** [comment]
> Sorry if this was misleading, I do know how to fix this, but instead of a workauround I was suggesting for this to be automated. You can simply download the v0.23.0-armh7f file and replace `InstaPy/assets/geckodriver` and `InstaPy/assets/gecko/v0.25.0/geckodriver-linux32` with the extracted executable and put the tar archive to `InstaPy/assets/gecko/v0.25.0/geckodriver-v0.25.0-linux32.tar.gz`(keep the names for all of them). The reason for this is, that there is no arm7hf version of the latest geckodriver, but InstaPy always tries to wnsure the newest webdriver is installed.

how can we use the 0.26 geckdriver ?
