### ISSUE TITLE
HAVING ISSUE WITH LOGGING IN 

### ISSUE THREAD

**Issue by yeyou4760** [InstaPy/InstaPy#5123]
## Current Behavior
ffrom instapy import InstaPy
from instapy import smart_run

# get a session!
session = InstaPy(username='user', password='pass',headless_browser=True,nogui=True,bypass_suspicious_attempt=True,bypass_with_mobile=True,multi_logs=True)

with smart_run(session):

    # session.set_user_interact(amount=2, randomize=True, percentage=100,
    #                           media='Photo')
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=3000,
                                    max_following=900,
                                    min_followers=50,
                                    min_following=50)
    session.set_simulation(enabled=False)
    session.set_do_like(enabled=True, percentage=100)

    session.set_do_comment(enabled=True, percentage=50)
    # session.set_do_follow(enabled=True, percentage=80, times=1)
    
    

    
    session.set_comments(['random','etc', 'n commnet'])
    
 
 
    
  
    session.like_by_tags(['hastag'], amount=15, interact=True)

    session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
    
    session.set_action_delays(enabled=True,like=20,comment=35,follow=10)

"""
-- REVIEWS --
@Andercorp:
- This would probably be the best temp for new accounts to start slowly and 
gently and then as your account gather IG authority, you could put some more 
power to your temp/bot...
@uluQulu:
- @Tachenz, the values in your script took my attention, it will be very 
good for new starters, as @Andercorp said. Stunning!
"""

**Comment by mikediachenko** [comment]
I am a bit confused. Is that complete config or just a part of it? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by moorebrb** [comment]
you have two f's at the top of your document. Is that a typo or is that why your code isn't working?

ffrom instapy import InstaPy
