### ISSUE TITLE
isitdownorjust.me is down !

### ISSUE THREAD

**Issue by lopjf** [InstaPy/InstaPy#5124]
Hello everyone !

Instapy doesn't work for half an hour now.. Why?
Because the website that checks if Instagram is down.. is down. What an ironic situation!

https://downforeveryoneorjustme.com/isitdownorjust.me

- Wouldn't be wise to use a more reliable checking website?
- Could I get rid of this checking step? 
I have more trust in the Instagram.com reliability than the checking websites.

You must know that I'm using Intapy 0.5.8 since it works better for me. So I'm not sure the last version of Instapy got the same problem ;)

**Comment by SwellShine** [comment]
Same here.
Instapy 0.6.4

**Comment by mikediachenko** [comment]
Maybe you IP is blocked by Instagram?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bktpgroup** [comment]
> Maybe you IP is blocked by Instagram?
> 
> Sent with [GitHawk](http://githawk.com)

The service is down, not IP blocked

**Comment by brhuman** [comment]
The same. How we can skip this checking?

**Comment by bktpgroup** [comment]
> The same. How we can skip this checking?

I don't think there is a parameter for not checking the connection

**Comment by GaWr26** [comment]
find the following in login_util.py and uncomment

```
# check Instagram.com status
    try:
        logger.info("-- Connection Checklist [2/3] (Instagram Server Status)")
        browser.get("https://isitdownorjust.me/instagram-com/")
        sleep(2)
        # collect isitdownorjust.me website information
        website_status = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "website_status")
        )
        response_time = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "response_time")
        )
        response_code = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "response_code")
        )

        logger.info("- Instagram WebSite Status: {} ".format(website_status.text))
        logger.info("- Instagram Response Time: {} ".format(response_time.text))
        logger.info("- Instagram Reponse Code: {}".format(response_code.text))
        logger.info("- Instagram Server Status: ok")
        update_activity(
            browser,
            action=None,
            state="Instagram servers are running correctly",
            logfolder=logfolder,
            logger=logger,
        )
    except Exception:
        logger.warn("- Instagram Server Status: error")
        update_activity(
            browser,
            action=None,
            state="Instagram server is down",
            logfolder=logfolder,
            logger=logger,
        )
        return False
```

It will skip the check and work

**Comment by quantal-dev-fullstack2** [comment]
The same for me, should have some api to turn off this feature

**Comment by riccardovalente** [comment]
`want_check_browser=False`
