### ISSUE TITLE
Failed to get followers count of 'b'Myusername''  ~empty list

### ISSUE THREAD

**Issue by SHEMSAB** [InstaPy/InstaPy#5125]
Hi! 
I am using the  Simple but effective template. I started it yesterday and worked all fine. But now, it's not working at all. 
I get this when I start it: 

INFO [2019-10-04 12:44:49] [Myusername]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-10-04 12:44:49] [Myusername]  Saving account progress...
INFO [2019-10-04 12:45:42] [Myusername]  Failed to get followers count of 'b'Myusername''  ~empty list
INFO [2019-10-04 12:46:32] [Myusername]  Failed to get following count of 'b'Myusername''  ~empty list
WARNING [2019-10-04 12:46:32] [Myusername]  Unable to save account progress, skipping data update Message: TypeError: window._sharedData is undefined

_____________________________________________________________________
INFO [2019-10-04 12:46:43] [Myusername]  Starting to unfollow users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2019-10-04 12:47:34] [Myusername]  Failed to get followers count of 'b'Myusername''  ~empty list
INFO [2019-10-04 12:48:24] [Myusername]  Failed to get following count of 'b'Myusername''  ~empty list
WARNING [2019-10-04 12:48:24] [Myusername]  Unable to find the count of users followed  ~leaving unfollow feature
INFO [2019-10-04 12:48:24] [Myusername]  --> Total people unfollowed : 0

Can anyone please help me? I searched and I could see the lists in the asset folder.

**Comment by Salchipapu** [comment]
same problem
Update: Let it rest for 12 hours, unistalled firefox and installed it again and now it seems like its working.

**Comment by hadifarnoud** [comment]
@SHEMSAB did you manage to fix this?
