### ISSUE TITLE
ERROR: clarifai 2.6.2 has requirement configparser<4,>=3.5, but you'll have configparser 4.0.2 which is incompatible.`

### ISSUE THREAD

**Issue by bigjjjim** [InstaPy/InstaPy#5126]
I keep getting this error while following the exact same steps as Tim's tutorial for Digitalocean server on youtube (video from February). 

ERROR: clarifai 2.6.2 has requirement configparser<4,>=3.5, but you'll have configparser 4.0.2 which is incompatible.`

I saw the same issue was opened and then closed straight  after, a few days ago. I tried a few things I saw online on similar error like updating the requirement.txt file, creating a new one inside the installation/Linux directory or uninstall configparser to install a prior version but nothing has changed. Any other idea on what I could do to make it work? I had no problem making it work on my desktop.

**Comment by tE3m** [comment]
This looks like a fatal error, but InstaPy won't have any issues because of this error.

**Comment by bigjjjim** [comment]
It does work actually... My script wasnt working because of another issue related to firefox. Thank you!
