### ISSUE TITLE
No Module named instapy

### ISSUE THREAD

**Issue by amoffitt123** [InstaPy/InstaPy#513]
Hello, I am running InstaPy on my raspberryPi 3 and everytime i try and run quickstart.py i get this error-
Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/docker_conf/all_in_one/quickstart.py", line 1, in <module>
    from instapy import InstaPy
ImportError: No module named 'instapy'
>>> 

Not sure what I did wrong as i am new to python.... thanks.

**Comment by iSimonWeb** [comment]
Your script should be in the root folder of InstaPy, either way python
won't find it.
"/home/pi/Projects/InstaPy/" in your case.
Otherwise, I suppose you should change the import at the beginning of the
script.

**Comment by amoffitt123** [comment]
Okay, I moved quickstart.py to the instapy folder, it is still giving me the same error, any ideas? @iSimonWeb

**Comment by amoffitt123** [comment]
Thanks @iSimonWeb, that fixed that problem, but then when I tried running quickstart.py again in the terminal with 

> sudo xvfb-run python quickstart.py

I got these errors
Traceback (most recent call last):
  File "quickstart.py", line 14, in <module>
    InstaPy() \
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 93, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 132, in set_selenium_local_session
    self.browser = webdriver.Chrome(chromedriver_location, chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7628f2b0>> ignored

**Comment by timgrossmann** [comment]
@amoffitt123 Did you put the chromedriver in /assets?

**Comment by amoffitt123** [comment]
No... will try that.

**Comment by amoffitt123** [comment]
Also, this may be a super silly question, but where do you enter your username and password?

**Comment by timgrossmann** [comment]
@amoffitt123 Could you please take a look at the README file here on GitHub?
There is a Getting Started section 😉

**Comment by mkMcMahon** [comment]
hey I know this was a silly question but I read the readme and saved a different script not in the root folder and I was lost until I found this thread and your answers. So I appreciate y'all answering this.

**Comment by PatrickBziuk** [comment]
I followed the instructions on: https://instapy.org/ with just using pip. 
After getting the same error like you, I found the instructions for the Raspberry to install instaPy and got it working. Here is the instruction which worked for me: https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md

I hope this is helpful for anyone.
