### ISSUE TITLE
This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.

### ISSUE THREAD

**Issue by jamezun** [InstaPy/InstaPy#5132]
## Expected Behavior
No blocks on likes. is it because I am using the old version? How can I fix it?

## Current Behavior
"This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake."

## InstaPy configuration
version 0.6.1

```
session.set_user_interact(amount=1, randomize=False, percentage=95, media=None)
    session.set_relationship_bounds (enabled=True,
                                      potency_ratio=None,
                                      delimit_by_numbers=True,
                                       max_followers=5000,
                                       max_following=1000,
                                       min_followers=50,
                                       min_following=50)
                                       
    
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                                  peak_likes_hourly=25,
                                  peak_likes_daily=180,
                                   peak_comments_hourly=20,
                                   peak_comments_daily=200,
                                    peak_follows_hourly=20,
                                    peak_follows_daily=150,
                                     peak_unfollows_hourly=20,
                                     peak_unfollows_daily=150)
        
    session.set_simulation(enabled=False)
    session.set_do_like(enabled=True, percentage=95)
    session.set_do_story(enabled = True, percentage = 95, simulate = True)
    session.set_do_follow(enabled=True, percentage=0, times=1)
    session.set_do_comment(enabled=True, percentage=0)
```

**Comment by Wakkox** [comment]
This is one of the main issues right now. Instapy gets detected very quickly by Instagram and blocks any interaction. I've been blocked for two weeks now. 
The thing is, only happens when I run the script. If I log in manually in Firefox, I can interact normally.

**Comment by riccardovalente** [comment]
You need to limit your server calls as well. I have hourly=188, daily=4200. These limits work for me, but they may not work for you. Some say that limits depend on how old the account is, or whether you've abused the bot in the past. These are not facts, but they seem plausible. Wait a week, or two, remove the cookie then try with lower interaction rates.

**Comment by kevXZY** [comment]
@riccardovalente can you share your configuration please ?

**Comment by Jardelmc** [comment]
Hello, riccardovalente. Do you usually follow how many people on average per day?

**Comment by riccardovalente** [comment]
probably around 50 since I've had to slow down

**Comment by jamezun** [comment]
I still got block even if I like 1 person per minute after 40 likes.... is instapy dead?

**Comment by riccardovalente** [comment]
>  is instapy dead?

No

**Comment by tjuzen** [comment]
> I still got block even if I like 1 person per minute after 40 likes.... is instapy dead?

I think so. I tried changing proxy, reducing server calls, likes, etc..
instapy get detected in few minutes, on any account (even a new one)

**Comment by leventdeniz** [comment]
Instagram recently introduced a new ai to detect bots very quickly. I think that may be related to this. I had read some articles about this, one with a statement from someone at facebook that was part of the anti-bot offensive. Maybe I'll find the link to that article.

**Comment by leventdeniz** [comment]
The new ai basically detects bots even with requests coming from private proxies, random delays, alternating HTTP headers or using "good" accounts within very few requests and blocks accounts. If anyone got any combination that allows a somewhat high number of requests, that would be interesting to hear

**Comment by Lem0nTree** [comment]
>  Maybe I'll find the link to that article.
Update if you find the link, i'm very curious
ty

**Comment by leventdeniz** [comment]
I found some of the articles and resources:

- https://stackoverflow.com/questions/57627864/instagram-user-page-parsing-with-proxy-without-api/57658358#57658358

Unfortunately this really good article is now behind a paywall:
- https://www.businessinsider.com/facebook-review-all-marketing-partners-instagram-data-scraping-2019-8

- https://newsroom.fb.com/news/2019/09/an-update-on-our-app-developer-investigation/

Or just Google "App Developer Investigation facebook"

**Comment by baptx** [comment]
@leventdeniz the full article can be found on archive.org without paying: https://web.archive.org/web/20191105075830/https://www.businessinsider.com/facebook-review-all-marketing-partners-instagram-data-scraping-2019-8

**Comment by khansaad1275** [comment]
> You need to limit your server calls as well. I have hourly=188, daily=4200. These limits work for me, but they may not work for you. Some say that limits depend on how old the account is, or whether you've abused the bot in the past. These are not facts, but they seem plausible. Wait a week, or two, remove the cookie then try with lower interaction rates.

I don't this removing the cookies will solve anything, you to change your passwords in order to let the Instagram algorithm know that the user which was mass liking and commenting was not you.
and then you have to change your user agent and then login with the new username and password , maybe this will solve your problem.

**Comment by GabrieleAnsaldo** [comment]
So I actually found a fix if you really want to have an instagram bot. Basically instagram got very good at detecting bots so I tried to work around that. Basically I have connected my old android phone to the Raspberry (you can connect it to any computer) and I just send a bunch of adb commands to it. I wrote a little script. Its been working so well.

I guess instagram finds it hard to find bots from someone using the app itself and not the browser version.

Hit me up if you are interested in developing this project with me, there is still a lot to do to make it very efficient.

**Comment by ortegafernando** [comment]
> So I actually found a fix if you really want to have an instagram bot. Basically instagram got very good at detecting bots so I tried to work around that. Basically I have connected my old android phone to the Raspberry (you can connect it to any computer) and I just send a bunch of adb commands to it. I wrote a little script. Its been working so well.
> 
> I guess instagram finds it hard to find bots from someone using the app itself and not the browser version.
> 
> Hit me up if you are interested in developing this project with me, there is still a lot to do to make it very efficient.

Great work!!! Have you got a github site? What kind of adb commands do you need to send?

**Comment by GabrieleAnsaldo** [comment]
@ortegafernando have a look here https://github.com/GabrieleAnsaldo/Andro-Bot-Insta

**Comment by smlrcheck** [comment]
Has anyone found any workaround for this issue? I got: 'Image was NOT liked! You have a BLOCK on likes!', so instapy becomes useless.

**Comment by jldmorris** [comment]
Did anyone solved this?

**Comment by sherxyar** [comment]
experiencing the same,
can like,comment, and follow on app and manually on pc but anything instapy tries it shows activity blocked.

**Comment by farshis** [comment]
same there! banned from any platforms, but only for one day 👎

**Comment by EnkhAmar** [comment]
Did anyone solve this using only code?

**Comment by sherxyar** [comment]
> Did anyone solve this using only code?

It's because of too much activity. You would have to stop using the bot for a few days. 

I think Instagram "blacklists" you when this happens. So, it will start to happen more often. 

The only solution is to keep a low-profile by having less activity.
