### ISSUE TITLE
Raspberry Pi fresh install introduces "undefined symbol: __atomic_exchange_8"

### ISSUE THREAD

**Issue by analyticsdept** [InstaPy/InstaPy#5133]
## Expected Behavior
InstaPy should launch without issue after a fresh install on RP3b

## Current Behavior
Error: undefined symbol: __atomic_exchange_8

## Possible Solution
Issue is linked to grpc being imported, downgrading to 1.23.0 solves the issue
EDIT: please try uninstall the package first
> Python:
> sudo pip uninstall grpcio
> sudo pip install grpcio==1.23.0

> Python 3:
> sudo pip3 uninstall grpcio
> sudo pip3 install grpcio==1.23.0 # python 3

## InstaPy configuration
0.6.4

**Comment by k88joshi** [comment]
Did this do the trick for you ? This has been happening to me over and over.  Does downgrading really work ?

**Comment by analyticsdept** [comment]
> Did this do the trick for you ? This has been happening to me over and over. Does downgrading really work ?

Yeah it does - I was just posting this issue with the solution in case anyone else needs it :)

It's a known bug on grpc's github

**Comment by sts-ryan-holton** [comment]
Doesn't seem to work for me

**Comment by analyticsdept** [comment]
> Doesn't seem to work for me

Which version of Python, RP, and Instapy are you using?

**Comment by sts-ryan-holton** [comment]
Python 3, Raspberry Pi 4

**Comment by analyticsdept** [comment]
@sts-ryan-holton sorry but I have to ask the obvious - did you use the python3 version of the command?

I'm running the same so I'm wondering why it didn't work for you.

**Comment by sts-ryan-holton** [comment]
Yes, I did, I tried both Python 1, and Python 3, same result each time when running `pythen3 ...`

**Comment by analyticsdept** [comment]
> Yes, I did, I tried both Python 1, and Python 3, same result each time when running `pythen3 ...`

@sts-ryan-holton did you try uninstalling the package first?

```sudo pip3 uninstall grpcio```

After you've done that it should be able to install the older version of the package and run as expected.
