### ISSUE TITLE
webdriverdownloader, GeckoDriverDownloader

### ISSUE THREAD

**Issue by RhaegarTargaryen55** [InstaPy/InstaPy#5134]
Can somebody please help me out with this?

```
Traceback (most recent call last):
  File "quickstartfollowundollow2.py", line 19, in <module>
    from instapy import InstaPy
  File "/Users/NoOne/Documents/Instabot/InstaPy-master/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/Users/NoOne/Documents/Instabot/InstaPy-master/instapy/instapy.py", line 82, in <module>
    from .browser import set_selenium_local_session
  File "/Users/NoOne/Documents/Instabot/InstaPy-master/instapy/browser.py", line 7, in <module>
    from webdriverdownloader import GeckoDriverDownloader
ModuleNotFoundError: No module named 'webdriverdownloader'
```
I'm on mac, geckodriver and webdriver are both installed and re-installed again a thousand times, can't figure out the problem. Instapy is updated.

**Comment by cprkrn** [comment]
Assumung you've tried 'pip install webdriverdownloader'?

**Comment by RhaegarTargaryen55** [comment]
@cooperkernan yes, it says

```
NoOne:~ NoOne$ pip3 install webdriverdownloader
Requirement already satisfied: webdriverdownloader in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (1.0.0.1)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from webdriverdownloader) (2.22.0)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from webdriverdownloader) (4.34.0)
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from webdriverdownloader) (4.8.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->webdriverdownloader) (1.25.3)
Requirement already satisfied: idna<2.9,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->webdriverdownloader) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->webdriverdownloader) (2019.6.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->webdriverdownloader) (3.0.4)
Requirement already satisfied: soupsieve>=1.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from beautifulsoup4->webdriverdownloader) (1.9.3)
NoOne:~ NoOne$ 

```

**Comment by cprkrn** [comment]
And you're using python3 to also run the program?

> @cooperkernan yes, it says
> 
> ```
> NoOne:~ NoOne$ pip3 install webdriverdownloader
> Requirement already satisfied: webdriverdownloader in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (1.0.0.1)
> Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from webdriverdownloader) (2.22.0)
> Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from webdriverdownloader) (4.34.0)
> Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from webdriverdownloader) (4.8.0)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->webdriverdownloader) (1.25.3)
> Requirement already satisfied: idna<2.9,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->webdriverdownloader) (2.8)
> Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->webdriverdownloader) (2019.6.16)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->webdriverdownloader) (3.0.4)
> Requirement already satisfied: soupsieve>=1.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from beautifulsoup4->webdriverdownloader) (1.9.3)
> NoOne:~ NoOne$ 
> ```

And you're using python3 to also run the program?

**Comment by RhaegarTargaryen55** [comment]
@cooperkernan Yes, i used the bot since February 2019 and everything was fine until that problem i got with the webdriverdownloader, GeckoDriverDownloader. A lot of people have the same problem.
