### ISSUE TITLE
Automate InstaPy with Crontab

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#514]
Hi everybody, can someone tell me why my script does not run from server? So I installed everything correctly and set the crontab to run quickstart.py every 3 hours. If I check with "grep "quickstart.py" /var/log/syslog" it says the file is run every 3 hours... but I cannot see that I really followed anybody new or liked images. Can you help me?

When I start quickstart.py from mac terminal it runs through and works fine. But with crontab it seems like nothing happens..... :/ Do I have to adjust it on the server?

**Comment by timgrossmann** [comment]
@flothousand Did you add the `nogui=True` parameter in the `InstaPy(username="", password="")` constructor?

Make sure to read the part on how to run it on the server from the README

**Comment by Naramsim** [comment]
Commands executed with cron do not have the same env variables you normally have. Check which ones are available by running a `printenv` in a cron job

**Comment by ghost** [comment]
@timgrossmann first of all thanks for your support and the great code :) fun to play with!

So I added now the nogui parameter to the quickstart behind username and password. Will check in the next hours if I am following more people and let you know

**Comment by ghost** [comment]
Okay still not running. I installed all the packages on he server and also running quickstart from mac works fine. I am just wondering which information you need so that you could help me.

Do I have to change anything else than adding nogui=true in quickstart.py file?

**Comment by timgrossmann** [comment]
@flothousand Try to run the quickstart file by hand first.

Do `python3.5 quickstart.py` or whatever your file is called.
If that works, it's your crontab.

Make sure to put your environment vars, if you set them there, in the /etc/environment file.
Make sure your crontab looks something like this: `0 */4 * * * cd /InstaPy && python3.5 quickstart.py`.
The crontab job has to move to the InstaPy folder first

**Comment by ghost** [comment]
okay just checked, quickstart on mac running, got python 3.5
Changed crontab from 0 */3 * * * /home/ubuntu/InstaPy && /usr/bin/python ./quickstart.py
to 0 */3 * * * /home/ubuntu/InstaPy && /usr/bin/python3.5 quickstart.py

Will keep you updated :)

**Comment by timgrossmann** [comment]
@flothousand Make sure to add the `cd` before the directory path `/home/ubuntu/InstaPy` 😉

**Comment by flothousand** [comment]
I now reinstalled everything and went through all steps.... now I tried to run it manually and get this:
~/InstaPy$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/home/ubuntu/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/home/ubuntu/InstaPy/instapy/instapy.py", line 5, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay

@timgrossmann is this maybe the problem? How can I solve it?

**Comment by ghost** [comment]
Yeeees, now it works @timgrossmann 
It was not a fault with my crontab, but had to reinstall pyvirtualdisplay :) Cool!

**Comment by timgrossmann** [comment]
@flothousand Awesome, thanks for sharing the solution!

**Comment by samducker** [comment]
Hi Tim, I am having the same issue with my crontab yet my script is working in bash. How do I setup the script to work with the cron enviroment? I have 0 */3 * * * cd /home/instagram/InstaPy/ && /usr/bin/python3.5 quickstart.py in my crontab file.
