### ISSUE TITLE
Willing to Pay somebody to help me with Chromedriver 

### ISSUE THREAD

**Issue by beld159** [InstaPy/InstaPy#5140]
I have had instapy working on the local, but now errors with chromedriver. I have NO experience coding, and all the doc I have read doesn't make sense to me. Please, somebody who can help with a screen share, will pay. 

Also tried digital ocean and getting a errno 26 error.

**Comment by cprkrn** [comment]
Hey! I got you. Don't think this is the right channel to find someone through but I can help. 

edit: You really just have to double check that your chrome version is compatible with the chrome driver version you're using. Go to Google Chrome -> About Google Chrome, check the version, then https://chromedriver.chromium.org/downloads use the correct version, place it in the folder @ /usr/local/lib/python3.7/site-packages/instapy_chromedriver/

**Comment by beld159** [comment]
Can you email me @cooperkernan 
beldredge159@gmail.com

**Comment by sonnyobrien** [comment]
> 
> 
> Hey! I got you. Don't think this is the right channel to find someone through but I can help.
> 
> edit: You really just have to double check that your chrome version is compatible with the chrome driver version you're using. Go to Google Chrome -> About Google Chrome, check the version, then https://chromedriver.chromium.org/downloads use the correct version, place it in the folder @ /usr/local/lib/python3.7/site-packages/instapy_chromedriver/

This doesnt exist

**Comment by Ristovski** [comment]
Looks like chromedriver support has been removed. Does anyone know the reason?

**Comment by sylvie7788** [comment]
I can'

> Can you email me @cooperkernan
> [beldredge159@gmail.com](mailto:beldredge159@gmail.com)

can't find it either

**Comment by cyberpz** [comment]
Hi guys I just fixed the same problem, 
on run my traceback gave some like "assure that chromedriver in installed in *path* ..."
but the damn driver was there (and even set to full privileges `chmod 777`)...
I solved: 

- [ ] re-installing instapy by pip (the bot runs on 2.7, so check that is not pip3), 
- [ ] download the last driver from google and put in  
```
> on unix
/usr/local/lib/python3.7/site-packages/instapy_chromedriver/
> on mac
/Users/**userLikePeppuz**/Library/Python/2.7/lib/python/site-packages/instapy_chromedriver/
```
- [ ] delete current driver and rename new as default
- [ ] update Chrome to last version, 

Hope that this helps you. When I come back to use the platform is always a pain for me as well.
