### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'want_check_browser'

### ISSUE THREAD

**Issue by andreescocard** [InstaPy/InstaPy#5147]
## Expected Behavior

Bot start

## Current Behavior

File "/XXX/instapy.py", line 129, in __init__
    want_check_browser = cli_args.want_check_browser or want_check_browser
AttributeError: 'Namespace' object has no attribute 'want_check_browser'

## InstaPy configuration

Latest version on dev branch

**Comment by riccardovalente** [comment]
I get that too. I haven't investigated this yet, but you can fix that by setting True or False in instapy.py line 129, like so: ```         want_check_browser = False```.

**Comment by andreescocard** [comment]
Thanks @riccardovalente

**Comment by breuerfelix** [comment]
fixed by @riccardovalente ! thanks alot :)
