### ISSUE TITLE
No module named 'webdriverdownloader'`

### ISSUE THREAD

**Issue by Pauloarjrpro** [InstaPy/InstaPy#5150]
I have this problem a few days ago. It used to work smoothly now that I updated it not working anymore.

It seems that the Firefox driver is being used, I downloaded the browser but it still doesn't work.

Could you help me change the driver for chrome or tell me what is the stable version of Firefox? Any help is of great importance. I thank all involved!

`Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "/Users/homework1/Documents/BOT/InstaPy/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/Users/homework1/Documents/BOT/InstaPy/instapy/instapy.py", line 82, in <module>
    from .browser import set_selenium_local_session
  File "/Users/homework1/Documents/BOT/InstaPy/instapy/browser.py", line 7, in <module>
    from webdriverdownloader import GeckoDriverDownloader
ModuleNotFoundError: No module named 'webdriverdownloader'`

Already tried to update the driver and installed it several times and it didn't work with the latest version of firefox.

**Comment by wyattwade** [comment]
I'm having the same issue. It started when I updated InstaPy. Also tried installing instaPy and using quickstart from a new machine, and received the same geckodriver issue.

**Comment by RhaegarTargaryen55** [comment]
can't resolve the same problem during the past month

**Comment by wyattwade** [comment]
I'm staying tuned to updates of this project. I'm also willing to contribute, although I'm a C# developer (not python). If I see any changes I'll let you know.

**Comment by lucaslrt** [comment]
Just install webdriverdownloader
```
pip install webdriverdownloader
```
