### ISSUE TITLE
How to change web driver to Chrome from Firefox due Proxy Authentication Problem!

### ISSUE THREAD

**Issue by xWHOISF** [InstaPy/InstaPy#5158]
Hi friends,

You know proxy authentication doesn't work on firefox. I tried eveything and i could not.

Do you have any advice about proxy? If not, how do I change it to chrome webdriver?

Thanks..

**Comment by meinert** [comment]
An error has been fix and merged......might help you

https://github.com/timgrossmann/InstaPy/pull/5128

**Comment by xWHOISF** [comment]
> An error has been fix and merged......might help you
> 
> #5128

I solved auth problem with selenium wire, thank you so much :)
