### ISSUE TITLE
grab followers get 0 people

### ISSUE THREAD

**Issue by kshahnazari1998** [InstaPy/InstaPy#5162]
Does anyone know what the issue is?

from instapy import InstaPy
from instapy import smart_run

insta_username = "xxx"
insta_password = "xxx"

session=InstaPy(username=insta_username,password=insta_password)
followers = session.grab_followers(username="shiva_sami", amount="full", live_match=False, store_locally=True)

-----

Grabbed 0 usernames from `Followers` in 0.02 seconds
Zz :[ time to take a good nap  ~sleeping 0.0 seconds

**Comment by mouaadsk** [comment]
Same issue here, any solution?

**Comment by meinert** [comment]
Works for me only when using "pick_nonfollowers" which basiclly calls grab_followers

**Comment by meinert** [comment]
A little investigation shows that it only works when logged in. Believe that it has been possible to grab followers for other users as well.

@kshahnazari1998 , @mouaadsk - Can you confirm that you experience the error when trying to grab users from an account when not logged in?

**Comment by kshahnazari1998** [comment]
@meinert Yes I confirm that I can't grab other peoples followers even when I'm logged in

**Comment by alinakhay** [comment]
Any updates on this one?

**Comment by jkkorn** [comment]
Any news?  Same happening here
