### ISSUE TITLE
SECURE THE BOT

### ISSUE THREAD

**Issue by youremer** [InstaPy/InstaPy#5164]
Hello to all, i started use the instapy bot 2 days ago...
I would like to ask a question for all of us..
There is any guide, how to secure our bot?
How to secure our account to avoid blocking from instagram?

What could we use?
Proxies?
Vpn?
Deleted cookies?
Instagram limits? ( where we could find them? )

Thank you!!

**Comment by brandonmalonson** [comment]
pretty sure vpn
as for guide, here's a link to the documentation on how to do pretty much everything.

https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#liking
