### ISSUE TITLE
Connection Refused error

### ISSUE THREAD

**Issue by anthonytapias** [InstaPy/InstaPy#5168]
Every time I run my quickstart.py file I get this error. I had to insert the geckdriver path in Instapy() so that I do not get the "no matching capabilities" error. I am running this on Digital Ocean and it does work every time I restart my server. However after running the file one or two times I receive a connection refused error. Does anyone have a solution to this? 

<img width="738" alt="Screen Shot 2019-10-22 at 6 04 57 PM" src="https://user-images.githubusercontent.com/41206609/67338325-ddb0e280-f4f6-11e9-9756-a98f166cbfa4.png">

**Comment by alexandre-maicol** [comment]
I have the same problem!

**Comment by ghost** [comment]
me too

**Comment by ghost** [comment]
any solution?

**Comment by ghost** [comment]
anyone?

**Comment by stefanbschneider** [comment]
Same problem, but unfortunately no solution.

**Comment by nath24** [comment]
anyone?
