### ISSUE TITLE
No Module Found Error: Requests

### ISSUE THREAD

**Issue by calixo888** [InstaPy/InstaPy#5169]
Line to run: Instapy(username=[username], password=[password])

## Expected Behavior

Login to Instagram

## Current Behavior

ModuleNotFoundError: No module named 'requests.packages.idna.uts46data'

## Possible Solution (optional)

- Uninstall instapy and install it again (sudo)
- Uninstall requests and install it again (sudo)
- Try an online text editor

**Comment by zeroxyn** [comment]
Got it fixed, just installed python 3.7.0 and it is working now :D with python 3.8.0 there is an issue on win10 so that the module cannot be installed
