### ISSUE TITLE
Unable to locate element

### ISSUE THREAD

**Issue by n0sw34r** [InstaPy/InstaPy#517]
Anyone have same error and know how to fix it please?
![image](https://user-images.githubusercontent.com/30392165/29124103-3306a368-7d18-11e7-9406-2dcf7f4a15ee.png)

**Comment by omidedipidizi** [comment]
yes i get same error right now !! load Instagram registration page instead of login page ...

**Comment by westondeboer** [comment]
If you pull the latest version, it should fix that error.

**Comment by converge** [comment]
as @westondeboer said, latest version should fix it. pls, reopen the issue if you need it.
