### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by sonnyobrien** [InstaPy/InstaPy#5170]
after running the windows run as administrator

starting instapy with quickstart ================================ python: can't open file '../quickstart.py': [Errno 2] No such file or directory Press any key to continue . . .

**Comment by zeroxyn** [comment]
Try downloading python version 3.7.0, this worked for me. It has something to do with grpcio not installing when running pip install instapy

**Comment by muzhaqi16** [comment]
Does it need to be python version 3.7.0 specifically or will the newer version work as well?
