### ISSUE TITLE
key error media

### ISSUE THREAD

**Issue by tooxiic49** [InstaPy/InstaPy#5178]
Hello,
my bot do not want to start anymore,
he tells me:

Traceback (most recent call last):
  File "C:\Users\surfacepro4\Documents\instapy\instapy-commentaires\quickstart.py", line 50, in <module>
    amount=60, skip_top_posts=True)
  File "C:\Users\surfacepro4\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\instapy.py", line 1785, in like_by_tags
    self.logger)
  File "C:\Users\surfacepro4\AppData\Local\Programs\Python\Python36\lib\site-packages\instapy\like_util.py", line 560, in check_link
    media = post_page[0]['media']
KeyError: 'media'
>>> 

I can not find a solution.
Everything worked the days before

**Comment by viktorburjan** [comment]
Having the same issue, running on Ubuntu 18.04 and Python 3.6.7

Seems like the issue is at 
`venv/lib/python3.6/site-packages/instapy/like_util.py:554`

where the following script returns an empty result: 
`
        post_page = browser.execute_script(
            "return window._sharedData.entry_data.PostPage"
        )
`

**Comment by agregorieu** [comment]
Same issue here.

Traceback (most recent call last):
  File "likes.py", line 36, in <module>
    session.like_by_feed(amount=30, randomize=False, unfollow=False, interact=False)
  File "/home/agustin/.local/lib/python3.5/site-packages/instapy/instapy.py", line 3474, in like_by_feed
    for i in self.like_by_feed_generator(**kwargs):
  File "/home/agustin/.local/lib/python3.5/site-packages/instapy/instapy.py", line 3574, in like_by_feed_generator
    self.logger)
  File "/home/agustin/.local/lib/python3.5/site-packages/instapy/like_util.py", line 553, in check_link
    media = post_page[0]['media']
KeyError: 'media'

**Comment by mikestan** [comment]
Does this happen when they change the API?  I'm also having problems accessing my profile on Chrome - would Chromium driver carry the same issue?

FWIW, I'm getting the same issue all of a sudden, too.

**Comment by KeenonT** [comment]
got this issue out of the blue as well. tried to fix the like_util file with a commit I found from September but running into the same issue

**Comment by dimchk** [comment]
Same issue on macOS 10.15 
Error output :
 File "/Library/Python/2.7/site-packages/instapy/like_util.py", line 589, in check_link
    media = post_page[0]['media']
KeyError: 'media'

any news ?

**Comment by KeenonT** [comment]
i thought i was in the clear from having issues with instapy until this KeyError showed up lol

**Comment by mikestan** [comment]
> Does this happen when they change the API? I'm also having problems accessing my profile on Chrome - would Chromium driver carry the same issue?
> 
> FWIW, I'm getting the same issue all of a sudden, too.

A developer has a pretty good explanation of what's going on: https://github.com/LevPasha/Instagram-API-python/issues/704

**Comment by victorraft** [comment]
I am also having this issue...

**Comment by viktorburjan** [comment]
For me, upgrading to the newest version solved the issue.

**Comment by KeenonT** [comment]
@jazzisnice damn i've been avoiding the newest versions. guess i'll have to bite the bullet

**Comment by dimchk** [comment]
> For me, upgrading to the newest version solved the issue.

you mean you just run update.command  from installation dir and then the issue was disappeared?

**Comment by viktorburjan** [comment]
> > For me, upgrading to the newest version solved the issue.
> 
> you mean you just run update.command from installation dir and then the issue was disappeared?

I used pip, as far as I remember upgraded from 0.6.2 to 0.6.5

**Comment by dimchk** [comment]
It doesn't help me 
Can the problem root cause be that I updated the chrome driver for supporting google chrome v.78?

**Comment by hscanlan** [comment]
I have this issue also.

Latest Python and Instapy.

Drive is 2.46

**Comment by ExportEh** [comment]
Same. 0.5.8
Using the new version just kicks Action Block right away. 
The old use to work great.

**Comment by Ebloom59** [comment]
Same issue on Mac

**Comment by cyberpz** [comment]
We are still stuck in this, I was trying this days to see why it crashes. 
The function `check_link` raises a `KeyError: media`, but the `post_page` is not empty. 
I'll keep you update as i try to fix.

**Comment by Knrd2** [comment]
Im getting the same error. Any updates by now?

**Comment by Menelle** [comment]
Instagram changed its js. The data path is back to `__additionalData` and is now behind `post path` root node:
`        post_page = browser.execute_script(
            "return window.__additionalData['{}']".format(post_link[25:]))`

The graphql can be recover with:
`post_page['data']['graphql']`

However, post_link is not available everywhere, so this might imply a refactoring of comment_util.py and like_util.py to pass it as argument

**Comment by Xander8** [comment]
How do we continue to bump this bug? Longest unsolvable bug i've seen!

**Comment by Xander8** [comment]
> 
> 
> For me, upgrading to the newest version solved the issue.

Can you tell us your dependencies? Python version and instapy version?

**Comment by grittdoof** [comment]
I have the same issue but anyone seem to know fix the bug :(

**Comment by ttorelli7** [comment]
I have the same issue :-( Does someone know how to solve it, please?

**Comment by ttorelli7** [comment]
Guys, now it worked for me running with "python3", instead of "python" or "python2"!

**Comment by lucaob** [comment]
hi, after a long stop using InstaPy, I starded again. I updated InstaPy with pip, but error #5359 occurred. Now I solved it, but run across this "key error media". I am unable to solve it. Help apreciated! Before the stop many months ago all was working well.
