### ISSUE TITLE
Commenting and Following doesn't work while liking by location.

### ISSUE THREAD

**Issue by j4ypandey** [InstaPy/InstaPy#518]
```
session.unfollow_users(amount=40, onlyInstapyFollowed = True )
session.like_by_locations(['662544956/raipur-chhattisgrah/'], amount=400)
session.set_do_comment(enabled=True, percentage=60)
session.set_comments([u'Nice', u' Amazing' ])
session.set_do_follow(enabled=True, percentage=60, times=1)
session.like_by_tags(['foodie'], amount=400)

```

This is the script but it only likes images of that location and doesn't comment and follow, even though I have written to do so.
Please Help!

**Comment by timgrossmann** [comment]
@j4ypandey As stated several times now:

Please put all the `.set_...` methods above any of the `.like_by_...` methods, else it will only be taken into account once the `.set_...`method is called
