### ISSUE TITLE
It just run for 20 or 30 likes and then get blocked

### ISSUE THREAD

**Issue by bruno-lindquist** [InstaPy/InstaPy#5181]
I tried many times and with different accounts and different configuration, but it only run for 20 or 30 likes and then i get blocked.

Someone has a solution?

**Comment by aleeepp** [comment]
same here

**Comment by xerZV** [comment]
Same, tried in Raspberry and Windows - same

**Comment by bruno-lindquist** [comment]
I tried on mac end doens't work.

is it still working for someone?

**Comment by brhuman** [comment]
same
