### ISSUE TITLE
Instapy is Dead?

### ISSUE THREAD

**Issue by iltonjm** [InstaPy/InstaPy#5186]
Is any version working? I tested from 0.58 to the latest, none works.

Does anyone recommend any other service?

**Comment by riccardovalente** [comment]
Latest version works for me.

**Comment by curtisraymond** [comment]
I'm using version 0.6.5 and it seems like the code I'm using below isn't actually skipping the top posts. I noticed that this issue was resolved within version 0.6.3 so I'm wondering why I'm still getting this issue?

session.like_by_locations(['212991559'], amount=25, skip_top_posts=True)

**Comment by riccardovalente** [comment]
Ah, I think that has been broken for a while, so I stopped used that function a while ago. I only use the following actions:

like_by_feed
like_by_tags
interact_by_users
follow_user_followers
follow_likers
follow_commenters
unfollow_users

which seems to work ok...

**Comment by Wilane91** [comment]
I used like by locations a few days ago without problem

**Comment by jase5760** [comment]
> Ah, I think that has been broken for a while, so I stopped used that function a while ago. I only use the following actions:
> 
> like_by_feed
> like_by_tags
> interact_by_users
> follow_user_followers
> follow_likers
> follow_commenters
> unfollow_users
> 
> which seems to work ok...

Can you send us your configuration ? 
My Setup is getting blocked each time...

**Comment by riccardovalente** [comment]
if it's getting blocked you need to take a break. Your account is probably flagged, so it's quite likely that you'll get blocked very early no matter what setup you use.

I've shared my setup many times on the Discord channel, below are the bits that control the delays and max interactions. It runs **very** slowly.

```
    session.set_quota_supervisor(
        enabled=True,
        sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls"],
        sleepyhead=True,
        stochastic_flow=True,
        notify_me=True,
        peak_likes_hourly=22,
        peak_likes_daily=80,
        peak_comments_hourly=5,
        peak_comments_daily=182,
        peak_follows_hourly=6,
        peak_follows_daily=27,
        peak_unfollows_hourly=6,
        peak_unfollows_daily=67,
        peak_server_calls_hourly=188,
        peak_server_calls_daily=4200,
    )

    session.set_simulation(enabled=True, percentage=73)

    session.set_action_delays(
        enabled=True,
        like=14,
        comment=10,
        follow=16,
        unfollow=17,
        story=20,
        randomize=True,
        random_range_from=349,
        random_range_to=539,
    )

```

I might actually try shorter delays at some point as I haven't been blocked for a while.

**Comment by riccardovalente** [comment]
Also `sleep_delay=1216` for follows/unfollows.

**Comment by iltonjm** [comment]
Here is the message:

Traceback (most recent call last):
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\quickstart-teste.py", line 24, in <module>
    headless_browser=False)
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\instapy.py", line 319, in __init__
    self.logger,
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by jase5760** [comment]
> Here is the message:
> 
> Traceback (most recent call last):
> File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\quickstart-teste.py", line 24, in 
> headless_browser=False)
> File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\instapy.py", line 319, in **init**
> self.logger,
> File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
> options=firefox_options,
> File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in **init**
> keep_alive=True)
> File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "C:\Users\Administrador\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Check your Geckodriver in the assets folder. If its the 32bit Version you have to get the 64bit an rename it into the 32bit version.
