### ISSUE TITLE
Problems using last version of instapy

### ISSUE THREAD

**Issue by Wilane91** [InstaPy/InstaPy#5187]
## Expected Behavior
Hello, I want to continue using my instapy scripts that worked well but since a few days, i have this error :

`InstaPy Version: 0.6.5
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Utilisateur/InstaPy"
Traceback (most recent call last):
  File "Follow.py", line 13, in <module>
    headless_browser=False)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 319, in __init__
    self.logger,
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`
 I updated to the last version as mentionned in the readme but still got the same error. Can you help me ? Thanks
## Possible Solution (optional)

I guess it's supposed to my firefox driver but I don't know hot to change them

## InstaPy configuration
Version: 0.6.5

**Comment by BroTherReZa** [comment]
I think you should have an active meeting with your Firefox browser on your Target site.
And I suggest you clear your Firefox browser cache and try again

**Comment by BroTherReZa** [comment]
> ## Expected Behavior
> Hello, I want to continue using my instapy scripts that worked well but since a few days, i have this error :
> 
> `InstaPy Version: 0.6.5 ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. Workspace in use: "C:/Users/Utilisateur/InstaPy" Traceback (most recent call last): File "Follow.py", line 13, in <module> headless_browser=False) File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\instapy.py", line 319, in __init__ self.logger, File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy\browser.py", line 114, in set_selenium_local_session options=firefox_options, File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__ keep_alive=True) File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__ self.start_session(capabilities, browser_profile) File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session response = self.execute(Command.NEW_SESSION, parameters) File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute self.error_handler.check_response(response) File "C:\Users\Utilisateur\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`
> I updated to the last version as mentionned in the readme but still got the same error. Can you help me ? Thanks
> 
> ## Possible Solution (optional)
> I guess it's supposed to my firefox driver but I don't know hot to change them
> 
> ## InstaPy configuration
> Version: 0.6.5

I think you should have an active meeting with your Firefox browser on your Target site.
And I suggest you clear your Firefox browser cache and try again
