### ISSUE TITLE
instagram fix instapy?

### ISSUE THREAD

**Issue by blast69** [InstaPy/InstaPy#5188]
4 hours, now error
![error](https://user-images.githubusercontent.com/57127193/67854861-c51e7900-fb43-11e9-9579-07cf1191c56c.jpg)

**The code I used:**

from instapy import InstaPy
from instapy import smart_run

insta_username = 'xxxxxxxxxx'
insta_password = 'xxxxxxxxxx'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True, bypass_suspicious_attempt=True)

with smart_run(session):
  """ Activity flow """	

  session.set_relationship_bounds(enabled=True,
                                    potency_ratio=-0.50,
                                    delimit_by_numbers=True,
                                    max_followers=2000,
                                    max_following=3500,
                                    min_followers=25,
                                    min_following=25)	
  	
  session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
  session.set_do_like(enabled=True, percentage=100)

  ammount_number = 350

  session.follow_user_followers(['black', 'taylorswift', 'blvck', 'saigon', 'chipupu', 'apple', 'instagram', 'hm'], amount=ammount_number, randomize=False, interact=True, sleep_delay=240)

**Comment by blast69** [comment]
my profile page,
mobile working, but pc dont working

**Comment by mikestan** [comment]
You need to change your password on your mobile device then update your quickstart script credentials. IG has essentially blocked your IP and are getting cheeky with the errors they return.

**Comment by blast69** [comment]
> You need to change your password on your mobile device then update your quickstart script credentials. IG has essentially blocked your IP and are getting cheeky with the errors they return.


I changed the password, but it still does not work.

My profile and anyone else is in error

**Comment by mikediachenko** [comment]
It happens. I was doing nothing to fix it, just waiting and it helped.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by blast69** [comment]
3day an now, working
