### ISSUE TITLE
Action blocked

### ISSUE THREAD

**Issue by seotami** [InstaPy/InstaPy#5189]
I got the bot running but on different profiles i get after 5-6 unfollows "action blocked". How can i fix this?

**Comment by mikediachenko** [comment]
It is not an issue of InstaPY script. It is Instagram AI is reacting so on script usage from your side.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by seotami** [comment]
How i have to configure the script that this not happen?
