### ISSUE TITLE
Increase time between the skipped users

### ISSUE THREAD

**Issue by panchoma** [InstaPy/InstaPy#5191]
Hi, everyone! 

I have a few filters for skipping users, like the amount of followers, posts, no profile picture, business accounts, etc...
I'm looking for a form  to increase the time between the skipped users. For example in the image below, 5 users are skipped in only 33 seconds. I want to increase that time to 20/30 seconds per user. Any ideas?

I realized that every time that many users are skipped in a very short period of time, I get the error "Please wait a few minutes before trying again".

![1](https://user-images.githubusercontent.com/47011452/67997880-dd21f580-fc34-11e9-8747-107b930b4cda.jpg)

Thanks!

@uluQulu , @timgrossmann , @CharlesCCC  , @Mr-HaleYa  @breuerfelix

**Comment by blast69** [comment]
+1

**Comment by ghost** [comment]
+1 it goes so fast sometimes.

**Comment by evertonmdz** [comment]
+1
