### ISSUE TITLE
Follow people based on Instagram suggestions.

### ISSUE THREAD

**Issue by karan10** [InstaPy/InstaPy#52]
Would it be nice if, we add a feature which will follow the people suggested by Instagram in SUGGESTIONS FOR YOU box. Also we can like their updates. 
This will increase the chances of following back by that person.

**Comment by ToJen** [comment]
That'll be cool. I've seen a YouTube video that did this for LinkedIn. I'd like to work on something like this.

**Comment by timgrossmann** [comment]
@karan10 Does this feature exist on desktop?
I haven't seen this yet, looks like this is a App-only feature like direct messaging... #6 😞

**Comment by karan10** [comment]
@timgrossmann Yes, this feature exists on desktop too. It is here on instagram home page. 
Find the attachment. 
![instagram](https://cloud.githubusercontent.com/assets/4979940/24829194/0fa789f2-1c8b-11e7-97c1-7055ceb0d1bd.png)

On clicking "See All", we can see more suggestions. Also we have to skip those verified pages, which has rare chance to follow us back. Or it will be done as per need.

**Comment by timgrossmann** [comment]
@karan10 Ohh nice!
Perfect, I'll add an issue for that.

**Comment by karan10** [comment]
@timgrossmann A problem here, It redirects to [this page](https://www.instagram.com/explore/) and it shows only 10 results to follow and there is no load more button.

**Comment by eduardocalazansjr** [comment]
@karan10 only users with the old interface see this box.
Probably it will be discontinued soon.

**Comment by karan10** [comment]
@vlntdds oh, ok. @timgrossmann It seems it is of no use now. 
I am closing this issue.
