### ISSUE TITLE
Bot and Online server: Installation issues?

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#520]
I tried to set up the bot on pythonanywhere, but there might be a problem that I can't figure out! Does someone of you how to make it works? Thanks
Here you can see what happens.... It would be great if someone could help me! Thanks a lot! 
![1](https://user-images.githubusercontent.com/30895126/29164663-836f3902-7dc0-11e7-8ebb-0b130eccd235.png)
![2](https://user-images.githubusercontent.com/30895126/29164666-87c26c9a-7dc0-11e7-97f5-e55e0b334078.png)
![3](https://user-images.githubusercontent.com/30895126/29164673-8cb23280-7dc0-11e7-9159-58b24ea7ac0f.png)

**Comment by NewyorkDev** [comment]
run sudo -s 
and then
```
1. git clone https://github.com/timgrossmann/InstaPy.git
2. cd InstaPy
3. pip install .
or
3. python setup.py install```

**Comment by NewyorkDev** [comment]
1. git clone https://github.com/timgrossmann/InstaPy.git
2. cd InstaPy
3. pip install .
or
3. python setup.py install

**Comment by ghost** [comment]
unfortunately, I get this message when I give the command sudo:
sudo: unknown user: root
sudo: unable to initialize policy plugin

also if I give it sudo --user

**Comment by edison12a** [comment]
You may clone the project to your computer and upload it from there. I do and it works for me

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
