### ISSUE TITLE
Getting the below error

### ISSUE THREAD

**Issue by tathagatadeb** [InstaPy/InstaPy#5201]
ERROR: clarifai 2.6.2 has requirement configparser<4,>=3.5, but you'll have configparser 4.0.2 which is incompatible.
ERROR: clarifai 2.6.2 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.1.1 which is incompatible.
Installing collected packages: six, plyer, urllib3, attrs, pyrsistent, functools32, configparser, more-itertools, zipp, contextlib2, scandir, pathlib2, importlib-metadata, jsonschema, future, protobuf, idna, chardet, certifi, requests, enum34, typing, googleapis-common-protos, futures, grpcio, clarifai, selenium, MeaningCloud-python, fake-useragent, emoji, PyYAML, EasyProcess, regex, instapy-chromedriver, PyVirtualDisplay, instapy
  Found existing installation: six 1.4.1
ERROR: Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by maxsptz** [comment]
i got the exact same
