### ISSUE TITLE
invalid syntax: username: str = None,

### ISSUE THREAD

**Issue by nycrom** [InstaPy/InstaPy#5202]
Hey,

ive installed it according to the Raspberry Pi how-to.  But i always get this error. Firefox is installed i think, i started it in the gui. 

Maybe i have to use an older version of instapy? Can someone tell me the command?

Traceback (most recent call last):
  File "start4.py", line 3, in <module>
    from instapy import InstaPy
  File "/home/pi/Projects/instapy/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/home/pi/Projects/instapy/instapy/instapy.py", line 99
    username: str = None,
            ^
SyntaxError: invalid syntax

**Comment by JennaDoll** [comment]
I have been having this issue for months. someone please help.

**Comment by Archax** [comment]
> I have been having this issue for months. someone please help.

FIX
try python3 quickstart.py
after that install clarifai and another packages pip3 clarifai
InstaPy use python 3 version)
