### ISSUE TITLE
Chrome 71 to 75 Automatic Update Issue

### ISSUE THREAD

**Issue by sylvie7788** [InstaPy/InstaPy#5204]
Hi, my instapy keep showing message below:

Message: session not created: Chrome version must be between 71 and 75

I tried downgrade my chrome for numerous times by two ways:
1. changing Application - Google Chrome - Package Content - info.plist - change KSUpdateURL name to anything or its value to anything.
2. changing in Library - preferences - com.google.Keystone.Agent.plist - checkInterval - set its value to 0. 

Both of these ways were done right after I download and open my chrome (If I don't open and change directly, chrome crashed immediately).
After both operations, Chrome will remain 75 for a little while and then the **KSUpdateURL** will be automatically changed to its original file, then Chrome will automatically update to 78. At this point, checkInterval remains 0.

I don't know what to do anymore to keep using InstPy. Can anyone help please?

**Comment by ghost** [comment]
I also noticed this issue, and don't know how to avoid that.
