### ISSUE TITLE
Internet Connection Status: error

### ISSUE THREAD

**Issue by ebubekirboyun** [InstaPy/InstaPy#5205]
## Expected Behavior
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-11-08 01:30:01] [xxxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-11-08 01:30:02] [xxxxx]  -- Connection Checklist [1/3] (Internet Connection Status)
WARNING [2019-11-08 01:31:33] [xxxx]  - Internet Connection Status: error
...........................................................................................................................
CRITICAL [2019-11-08 01:31:33] [xxxx]  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2019-11-08 01:31:33] [xxxxx]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2019-11-08 01:31:38] [xxxx]  Sessional Live Report:
    |> No any statistics to show

[Session lasted 2.06 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-11-08 01:31:38] [xxxx]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

## Current Behavior
https://ip4.seeip.org/geoip not working

**Comment by roncam82** [comment]
yes the https://ip4.seeip.org/geoip is not working !!!

**Comment by nova168168** [comment]
Same here !

**Comment by mikediachenko** [comment]
Starting from yesterday the same.

**Comment by mikediachenko** [comment]
This helped me out #5002

**Comment by Foxlife345** [comment]
@mikediachenko I looked at the post but could not solve my problem, can I help myself?

**Comment by Foxlife345** [comment]
@mikediachenko if you can copy the part that helped you and send it here I will be grateful

**Comment by Tr1pke** [comment]
Same here 

Worked for me. Thx

**Comment by kazeox** [comment]
Try 

session = InstaPy(username=insta_username,
                  password=insta_password,
                  want_check_browser=False)

**Comment by goldingASS** [comment]
> Try
> 
> session = InstaPy(username=insta_username, password=insta_password, want_check_browser=False)

it worked

**Comment by inri19** [comment]
Thanks you kazeox

**Comment by nicedrm** [comment]
> Try
> 
> session = InstaPy(username=insta_username, password=insta_password, want_check_browser=False)

this leads to instagram page but not login page
