### ISSUE TITLE
stale element and stopping Instapy

### ISSUE THREAD

**Issue by roncam82** [InstaPy/InstaPy#5206]
## Expected Behavior
working
## Current Behavior
File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 3527, in follow_user_followers
    person, self.follow_times, sleep_delay, interact
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 1191, in follow_by_list
    self.logfolder,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/unfollow_util.py", line 606, in follow_user
    browser, track, login, user_name, None, logger, logfolder
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/unfollow_util.py", line 212, in get_following_status
    following_status = follow_button.text
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="_5f5mN       jIbKX  _6VtSN     yZn4P   "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

**Comment by fegomess** [comment]
`Session ended!                                                                                                                                                Traceback (most recent call last):                                                                                                                                                                             File "C:\Users\Dell\Desktop\InstaPy-master\instapy\util.py", line 946, in click_element                                                                                                                        element.click()                                                                                                                                                                                            File "C:\Users\Dell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click                                                                    self._execute(Command.CLICK_ELEMENT)                                                                                                                                                                       File "C:\Users\Dell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute                                                                return self._parent.execute(command, params)                                                                                                                                                               File "C:\Users\Dell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute                                                                  self.error_handler.check_response(response)                                                                                                                                                                File "C:\Users\Dell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response                                                        raise exception_class(message, screen, stacktrace)                                                                                                                                                       selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class=" ffKix sqdOP  L3NKy _4pI4F  y3zKF     " type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                                                                                                       Traceback (most recent call last):                                                                                                                                                                             File "quickstart.py", line 71, in <module>                                                                                                                                                                     session.follow_likers(['xxxxxx' , 'xxxxxxx'], photos_grab_amount = 3, follow_likers_per_photo = 30, randomize=True, sleep_delay=600, interact=True)                                 File "C:\Users\Dell\Desktop\InstaPy-master\instapy\instapy.py", line 1038, in follow_likers                                                                                                                    liker, self.follow_times, sleep_delay, interact                                                                                                                                                            File "C:\Users\Dell\Desktop\InstaPy-master\instapy\instapy.py", line 1191, in follow_by_list                                                                                                                   self.logfolder,                                                                                                                                                                                            File "C:\Users\Dell\Desktop\InstaPy-master\instapy\unfollow_util.py", line 609, in follow_user                                                                                                                 click_visibly(browser, follow_button)  # click to follow                                                                                                                                                   File "C:\Users\Dell\Desktop\InstaPy-master\instapy\util.py", line 1898, in click_visibly                                                                                                                       click_element(browser, element)                                                                                                                                                                            File "C:\Users\Dell\Desktop\InstaPy-master\instapy\util.py", line 960, in click_element                                                                                                                        + "')[0].scrollIntoView({ inline: 'center' });"                                                                                                                                                            File "C:\Users\Dell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 141, in get_attribute                                                           self, name)                                                                                                                                                                                                File "C:\Users\Dell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script                                                           'args': converted_args})['value']                                                                                                                                                                          File "C:\Users\Dell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute                                                                  self.error_handler.check_response(response)                                                                                                                                                                File "C:\Users\Dell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response                                                        raise exception_class(message, screen, stacktrace)                                                                                                                                                       selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class=" ffKix sqdOP  L3NKy _4pI4F  y3zKF     " type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed`


**This is the error that is showing to me. The interesting part is that this error occurred at the same function (session.follow_likers) that was working before the error came. It runs for i while and then something goes wrong.**

**Comment by roncam82** [comment]
any help on this please ?

**Comment by roncam82** [comment]
any help please ?

**Comment by fegomess** [comment]
This error persists. I cant use session.interact_by_comments

**Comment by roncam82** [comment]
any help please ?

**Comment by pezzotto** [comment]
Same here, have u solved?

**Comment by sylvie7788** [comment]
same here, need help
