### ISSUE TITLE
 Does instapy still work?

### ISSUE THREAD

**Issue by blast69** [InstaPy/InstaPy#5207]
What operations still work?

**Comment by jm-willy** [comment]
Not for me, I could solve many errors but now  sessions just end suddenly with no error, had to write my own bot

**Comment by Glyphack** [comment]
I think It can be a better approach to check the status code from the website `isitdownorjust`. clearly when it returns codes 5** website has problem, but when it returns 200 why should we ignore the response?

**Comment by riccardovalente** [comment]
Or, disable the check altogether `want_check_browser=False` (only available in the latest builds).
