### ISSUE TITLE
Supervisor Qouta and randomized sleep delays - Recommended settings 

### ISSUE THREAD

**Issue by rudyvanbebu** [InstaPy/InstaPy#5211]
Good morning,

I have been using Instapy for some time but in the last weeks and after an upgrade to 0.6.5, my account keeps receiving action blocks. 
I have searched for recommended settings on supervisor qouta and sleep delays but most of the posts are outdated. Also checked in Discord with no luck, it seems there is not much activity over there :( 

Can any of you using the bot succesfully list your preferred supervisor qouta values and sleep delay settings. I can share my script when needed with no issues.

thanks for your help

**Comment by muhammedsaid** [comment]
Hi,
I'm in similar situation, how can we solve this problem?

**Comment by fegomess** [comment]
It seens that Instagram is getting harder to use any kind of bot. I'm getting not only action blocked but blocked from accessing others account's profiles, including mine. I tried low quota configurations such as 10 likes/hour, but nothing is stopping Instagram from blocking my actions.
