### ISSUE TITLE
is this repo dead???????????????

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5212]
(venv) Diango (master *) Instapy $ python quickstart.py
InstaPy Version: 0.6.6
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/banginpadr/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-11-11 21:17:19] [chia__]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-11-11 21:17:19] [chia__]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-11-11 21:17:20] [chia__]  - Internet Connection Status: ok
INFO [2019-11-11 21:17:20] [chia__]  - Current IP is "132.27.245.18" and it's from "FRANCE/FR"
INFO [2019-11-11 21:17:20] [chia__]  -- Connection Checklist [2/3] (Instagram Server Status)
WARNING [2019-11-11 21:17:27] [chia__]  - Instagram Server Status: error
......................................................................................................................
CRITICAL [2019-11-11 21:17:27] [chia__]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2019-11-11 21:17:29] [chia__]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 13.88 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-11-11 21:17:29] [chia__]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo

[Errno 2] No such file or directory: '/var/folders/r3/2y0xmpzd46vbw33g_jm0dxxc0000gn/T/tmpbp8ac_5k'

INFO [2019-11-11 21:17:29] [chia__]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 13.89 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-11-11 21:17:29] [chia__]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by ghost** [comment]
for some reason i keep getting this error

**Comment by raviriley** [comment]
Same here! I'm running Xubuntu LTS and did a completely fresh install of the entire OS, so that means a completely new Instapy and Firefox. I keep getting this error! It opens a window that goes to `https://isitdownorjust.me/instagram-com/`. **Ironically, <https://isitdownorjust.me/> is down**, causing the process to falsely say Instagram is down. This is what my `geckodriver.log` contains:

```
1573541706952	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofileYH0IoI"
1573541708614	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1573541708619	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1573541708621	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1573541708621	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1573541718141	Marionette	INFO	Listening on port 33111
1573541718223	Marionette	WARN	TLS certificate errors will be ignored for this session
1573541727834	Marionette	INFO	Stopped listening on port 33111
```

**Comment by raviriley** [comment]
see #5002

**Comment by raviriley** [comment]
the issue was fixed, mine works now

**Comment by ghost** [comment]
brother blessing for you, thank you so much for this
