### ISSUE TITLE
Instagram detects my Firefox session from browser.py as bot

### ISSUE THREAD

**Issue by chrishsr** [InstaPy/InstaPy#5214]
Good evening guys

[browser.py.txt](https://github.com/timgrossmann/InstaPy/files/3838044/browser.py.txt)
 Instagram detects my firefox session from browser.py as bot, but if i open firefoy manually, everything works.
i know that the user agent is the problem, I tried using the useragent from an galaxy S10 (my dayly driver)
but it gets detectet as bot...

can anyone may send me a working user agent, or tell me how to tell the script to use the standart useragent?

my system is Win10 64Bit if this may helps
(and yes, i also tried a useragent therefor)

excuse my bad english, im german ^^
just added.txt to the file name to upload it...
[browser.py.txt](https://github.com/timgrossmann/InstaPy/files/3838045/browser.py.txt)

**Comment by jm-willy** [comment]
What does Instagram return, say or do?
