### ISSUE TITLE
AttributeError: 'LoggerAdapter' object has no attribute 'warn'

### ISSUE THREAD

**Issue by LarsvanSchai** [InstaPy/InstaPy#5216]
![error](https://user-images.githubusercontent.com/43091260/68717584-77742880-05a7-11ea-8c7f-3285abc60fcf.jpg)

**Comment by LarsvanSchai** [comment]
Anyone who knows how to solve this?

**Comment by chrishsr** [comment]
try in the login_util.py file setting parameter Return True (ln246) its false by default.
seems to me like it just cant read the information of the website to check if Insta is down (because the website itself is down)

by setting it to true it just ignores it
