### ISSUE TITLE
Best way to update

### ISSUE THREAD

**Issue by tylergit2** [InstaPy/InstaPy#522]
I've been having issues with the script ever since the bug where instapy was getting stuck at the login screen. I saw a string of comments that others were having the same issue at the time... I guess it was resolved but I still get stuck at the login screen.

I think I missed an update. What's the best way to update my files to the latest version of instapy?

**Comment by gitpatrickhub** [comment]
from the command line cd to the InstaPy directory and then do
``` 
git pull
```
