### ISSUE TITLE
clarifai 2.6.2 - configparse;  clarifai 2.6.2 - jsonschema; Could not install packages due to an EnvironmentError: [Errno 13]

### ISSUE THREAD

**Issue by BogdanPatroi** [InstaPy/InstaPy#5220]
Double-clicking the MacOS Installer, giving me this errors: 

ERROR: clarifai 2.6.2 has requirement configparser<4,>=3.5, but you'll have configparser 4.0.2 which is incompatible.

ERROR: clarifai 2.6.2 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.1.1 which is incompatible.

ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/futures-3.3.0.dist-info'
Consider using the `--user` option or check the permissions.

I've updated PythonV3... but I think my machine is still using v2... and I don't know how to change that

**Comment by zartaz** [comment]
same on raspberry

**Comment by CianPorteous** [comment]
Having the same issue on Windows 10, and I'm using Python 3.

**Comment by boutinjp14** [comment]
So I was able to install and run instapy by creating a virtual enviornment by adding:

python3 -m venv env
source ./env/bin/activate

just before the code in both the install.command and start.command files.

The only thing, which I am not sure if it is normal or not, is that it actually ran on firefox and not on chrome.
