### ISSUE TITLE
Error on upload

### ISSUE THREAD

**Issue by bilyboy785** [InstaPy/InstaPy#5228]
Hello I've got this error on upload : 

```
instapy-cli 0.0.12  |  python 3.7.3
[IG] not found cookie/cookie_file >> login as default
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Error is >>
    Bad Request

Something went bad.
Please retry or send an issue on https://github.com/b3nab/instapy-cli

Traceback (most recent call last):
  File "/usr/local/bin/instapy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/instapy_cli/__main__.py", line 44, in main
    cli.upload(options.file, text, story)
  File "/usr/local/lib/python3.7/dist-packages/instapy_cli/cli.py", line 153, in upload
    raise IOError("Unable to upload.")
OSError: Unable to upload.
```

**Comment by Donearm** [comment]
Same error since today. instapy-cli 0.0.12  |  python 3.8.0 for me

**Comment by vascostmr** [comment]
Same with me. I think the problem is in the [instagram_private_api](https://github.com/ping/instagram_private_api) module. The message "Error parsing error response" is probably thrown by this class from [errors.py](https://github.com/ping/instagram_private_api/blob/fd77fbf2163876842104fbcc054012b47d40475f/instagram_private_api/errors.py).:

```
class ClientCheckpointRequiredError(ClientError):
    """Raise when IG detects suspicious activity from your account"""

    @property
    def challenge_url(self):
        try:
            error_info = json.loads(self.error_response)
            return error_info.get('challenge', {}).get('url') or error_info.get('checkpoint_url')
        except ValueError as ve:
            logger.warning('Error parsing error response: {}'.format(str(ve)))
        return None
```

So either instagram changed the API or yours (and mine) accounts have been flagged.

**Comment by vascostmr** [comment]
@bilyboy785, [InstaPy](https://github.com/timgrossmann/InstaPy) and [instapy-cli](https://github.com/instagrambot/instapy-cli) are not related.

Check the message on your error: 

> `Please retry or send an issue on https://github.com/b3nab/instapy-cli`
