### ISSUE TITLE
Learning Suggestions 

### ISSUE THREAD

**Issue by NewyorkDev** [InstaPy/InstaPy#523]
Are there any books or online resources you guys would recommend to read to try and learn and help with the developing of this project. 

All help is appreciated :)

**Comment by citizenQ** [comment]
For authenticity of the bots I would recommend to do a lot of research about Instagram itself. 
(for ex. there are Tags which obviously reach a lot more people. (http://www.tagsforlikes.com/)
And then in my opinion the **most important** part is to create a **personality for the Bot** like things
he likes / doesn't likes, .. ,  through keyword-filtering and so on. 
Tags & Comments could be randomized through various lists.

**Comment by timgrossmann** [comment]
@NewyorkDev Also make sure to check out www.automatetheboringstuff.com if you need to get a basic understanding of python and working with selenium.

There also is a really small [How to contribute](https://github.com/timgrossmann/InstaPy/wiki/How-to-Contribute) section to get you started 😉

**Comment by NewyorkDev** [comment]
thanks Tim!
