### ISSUE TITLE
I've got banned after first attempt to follow

### ISSUE THREAD

**Issue by kremedved** [InstaPy/InstaPy#5230]
##  Expected Behavior
Bot works fine, without bans.

## Current Behavior
I was using Instapy to following followers from profiles. Recently I started the bot and after the first following attempt I've got banned for 2 days. Any ideas?

# InstaPy configuration
Instapy 0.6.6 + Raspberry Pi 3B+

      `
      from instapy import InstaPy
      from instapy import smart_run

      insta_username = ''
      insta_password = ''
      ammount_number = 24

      while True:

      session = InstaPy(username=insta_username,
                    password=insta_password,
                    headless_browser=False)

      with smart_run(session):

      session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                                peak_likes_hourly=8,
                                peak_likes_daily=70,
                                 peak_comments_hourly=1,
                                 peak_comments_daily=100,
                                  peak_follows_hourly=6,
                                  peak_follows_daily=77,
                                   peak_unfollows_hourly=10,
                                   peak_unfollows_daily=80,
                                    peak_server_calls_hourly=None,
                                    peak_server_calls_daily=3900)

      session.set_relationship_bounds(enabled=True,
                                      potency_ratio=None,
                                      delimit_by_numbers=True,
                                      max_followers=6000,
                                      max_following=1000,
                                      min_followers=30,
                                      min_following=30)
      
      session.set_action_delays(enabled=True,
                               like=20,
                               comment=20,
                               follow=7,
                               unfollow=20,
                               story=8,
                               randomize=True, random_range_from=210, random_range_to=310)

      session.set_user_interact(amount=3, randomize=True, percentage=80, media='Photo')
      session.set_do_like(enabled=True, percentage=80)
      session.set_do_comment(enabled=False, percentage=0)
      session.follow_user_followers([
      'danielkordan'
      ],
                                  amount=ammount_number, randomize=True,
                                   interact=True, sleep_delay=630)

      """ Joining Engagement Pods...
      """
      session.join_pods()

      `

**Comment by redBaron23** [comment]
Same here

**Comment by hamzadiaz** [comment]
Same here, for me it works for few hours then I get banned, I am only following 60 users per day

**Comment by Tr1pke** [comment]
Me too. But what did I expect, It’s a bot that use a web interface... so obvious it’s a bot

**Comment by raaaas** [comment]
its new insta wave for blocking automation . every single tool got banned and the work around still not found.

**Comment by Yakito** [comment]
Maybe it has to do with what I found out here [https://github.com/timgrossmann/InstaPy/issues/5239](https://github.com/timgrossmann/InstaPy/issues/5239
)

Were you using a virtual machine to run your bot?

**Comment by raaaas** [comment]
im using home server, with my prive isp ips and few 4g connection for mix thing out.

since its one of my income i had to take extra steps :).

but yeah many datacenter ip / proxy server / vpn / will get blocked automatically no question about that, 

if you want rule of thumb to make sure you wont get banned think like this:

instagram is for users who use phone not even browser. with that in mind, no user connect with datacenter ip and very few people using vpn to connect, so if your behavior soddenly change aka using one of those your accont will get flagged. and after few flag you will get banned.

hopefully that will explain what you looking
