### ISSUE TITLE
New problem, please help me to solve

### ISSUE THREAD

**Issue by Ewwwer** [InstaPy/InstaPy#5235]
## Expected Behavior
Not commented during the process

## Possible Solution (optional)
I think it's a problem inside the comment docuement & send.keys for comments

## InstaPy configuration
import random
from instapy import InstaPy
from instapy import smart_run

# get a session!
session = InstaPy(username='', password='', headless_browser=False)

# let's go! :>
with smart_run(session):
    # general settings
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                        peak_likes_hourly=80,
                        peak_likes_daily=1200,
                        peak_comments_hourly=20,
                        peak_comments_daily=182,
                        peak_follows_hourly=10,
                        peak_follows_daily=None,
                        peak_unfollows_hourly=10,
                        peak_unfollows_daily=402,
                        peak_server_calls_hourly=400,
                        peak_server_calls_daily=4700)

    session.set_action_delays(
                        enabled=True,
                        like=45,
                        comment=55,
                        follow=75,
                        unfollow=30,
                        randomize=True,
                        random_range_from=10,
                        random_range_to=90)
    
    session.set_relationship_bounds(enabled=True,
                                potency_ratio=None,
                                delimit_by_numbers=True,
                                max_followers=8500,
                                max_following=4490,
                                min_followers=100,
                                min_following=56,
                                min_posts=10)

    session.set_skip_users(skip_private=True,
                       private_percentage=100,
                       skip_no_profile_pic=True,
                       no_profile_pic_percentage=100,
                       skip_business=True,
                       business_percentage=100,)
    
    session.set_do_story(enabled = True, percentage = 89, simulate = False)
    
    session.set_user_interact(amount=2, randomize=True, percentage=50,
                              media='Photo')
    session.set_do_like(enabled=True, percentage=70)
    
    session.set_do_comment(enabled=True, percentage=18)
    session.set_comments(['Amazing!:fire: @{}', 'So cool!!:fire::fire: @{}', 'WOW!:fire:', 'WOW looks nice!:fire:', 'Nice shot! @{}', 'Your feed is an inspiration :thumbsup:', 'What camera did you use @{}?', ':raised_hands: Yes!', 'Insane capture! :fire:', 'I love that prospective :thumbsup:', 'Power photo :fire:'], media='Photo')
    session.set_use_clarifai(enabled=True, api_key='10af91e432b7426dbcdda482da0a27d2')
    session.clarifai_check_img_for(['nsfw', 'gay', 'hijab', 'niqab', 'religion', 'shirtless', 'fitness','yamaka', 'rightwing', 'sexy', 'sex', 'indian'], comment=False)
    session.set_dont_like(['dick', 'squirt', 'gay', 'homo', '#fit', '#fitfam', '#fittips','#abs', '#kids', '#children', '#child','[nazi','jew', 'judaism', '[muslim', '[islam', 'bangladesh', '[hijab', '[niqab', '[farright', '[rightwing','#conservative', 'death', 'racist'])
    session.set_do_follow(enabled=True, percentage=15, times=2)
    

    # like by tags activity
    session.set_smart_hashtags(['travelgram','instatravel','travelphotography','streetphotgrapht'], limit=3, sort='top', log_tags=True)
    session.like_by_tags(amount=2, use_smart_hashtags=True, randomize=True)
    session.set_skip_users(skip_bio_keyword = ['free shipping',' Order', 'visa', 'paypal','travel agency', 'agencia de viajes'])
    session.set_dont_like(['promoter', 'nightclub', 'viajargratis', 'emprendedor', 'money', 'negocio digital'])
    session.set_delimit_liking(enabled=True, max_likes=1500, min_likes=10)
    session.story_by_tags(['travelgram', 'travelphoto', 'travelling', 'igtravel'])

    # interact user followers activity
    session.set_user_interact(amount=2, randomize=True, percentage=30,
                              media='Photo')
    session.set_do_story(enabled = True, percentage = 92, simulate = False)
    session.set_do_follow(enabled=True, percentage=20)  
    session.set_do_like(enabled=True, percentage=85)
    session.set_comments(['Nice shot! @{}',
	    'I love your profile! @{}',
	    'Your feed is an inspiration :thumbsup:',
	    'Just incredible :open_mouth:',
	    'What camera did you use @{}?',
	    'Love your posts @{}',
	    'Looks awesome @{}',
	    'Getting inspired by you @{}',
	    ':raised_hands: Yes!',
            '@{} this is AWESOME! :open_mouth:',
            '@{} where did you take the picture? Is Amazing :thumbsup:',
            '@{} thanks for sharing your art :fire:',])
    session.set_do_comment(enabled=True, percentage=25)
    session.interact_user_followers(['hiclavero'], amount=90,
                                    randomize=True)

    # unfollow activity
    """session.set_dont_unfollow_active_users(enabled=True, posts=5)"""
    session.unfollow_users(amount=60, instapy_followed_enabled=True, instapy_followed_param="all", style="FIFO", unfollow_after=90*60*60, sleep_delay=901)
    
    # follow activity
    ammount_number = 6
    session.follow_user_followers(['hiclavero'],
                                  amount=ammount_number, randomize=True,
                                  interact=True, sleep_delay=501)
    
##Error Find
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\InstaPy-master\quickstart.py", line 67, in <module>
    session.like_by_tags(amount=2, use_smart_hashtags=True, randomize=True)
  File "C:\Users\USER\Desktop\InstaPy-master\instapy\instapy.py", line 2012, in like_by_tags
    self.logfolder,
  File "C:\Users\USER\Desktop\InstaPy-master\instapy\comment_util.py", line 92, in comment_image
    .send_keys(comment_to_be_sent)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\common\action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\common\actions\action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: rect is undefined

**Comment by Ebloom59** [comment]
Same issue for me ...
