### ISSUE TITLE
What servers do you use?

### ISSUE THREAD

**Issue by Yakito** [InstaPy/InstaPy#5239]
I noticed that when I use EC2 (Amazon AWS), Digital Ocean or any other well known server provider, Instagram blocks my actions super fast. 

Doing some tests, logging via a VNC to my virtual machine and launching Firefox I found out that you can't even create an account by visiting instragram.com using an EC2 server. Instagram will tell you that there was "an error". If I do the exact same thing from my local machine, it works. 

Therefore my questions is, what servers are you all using to run the bot? Are you running it from your "home" connection? are you using/buying a proxy?

Any tip will be appreciated!

**Comment by lxknvlk** [comment]
One solution would be to use paid not-blacklisted proxies. Haven't tried it but sounds that it might work.
