### ISSUE TITLE
Question - FIFO

### ISSUE THREAD

**Issue by jeffreylm** [InstaPy/InstaPy#524]
Has the FIFO (First In First Out) been implemented as of yet for the unfollow option?

**Comment by timgrossmann** [comment]
@jeffreylm No, there has been a PR but I was very old and the implementation was really basic.
There were a lot of updates and the PR hasn't been updated so I closed it.

**Comment by jeffreylm** [comment]
@timgrossmann Ok, good to know.

**Comment by paunocu69** [comment]
I could really use that function

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
