### ISSUE TITLE
How I can improve my quickstart code?

### ISSUE THREAD

**Issue by Silver1110011** [InstaPy/InstaPy#5241]
This is my Instapy configuration file, after 1 hour instagram block my actions, what I can do to improve it?

my quickstart.py

""" Quickstart script for InstaPy usage """

# imports
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

# set workspace folder at desired location (default is at your home folder)
set_workspace(path=None)
insta_username='xxxx'
insta_password='xxxx'
# get an InstaPy session!
session = InstaPy( username = insta_username,
                   password = insta_password,
                   headless_browser = False)

with smart_run(session):

SETTINGS
 session.set_quota_supervisor(enabled=True,
                              sleepyhead=True,
                              peak_server_calls_hourly=150,
                              peak_follows_hourly=40,
                              peak_unfollows_hourly=30,
                              peak_comments_hourly=6,
                              peak_likes_hourly=40,        
                              peak_likes_daily=100,     
                              peak_server_calls_daily=3000,
                              peak_follows_daily=120,
                              peak_unfollows_daily=100,
                              peak_comments_daily=15,
                              sleep_after=["follows_h","unfollows_h","comments_h","server_calls_h","follows_h","follows_d","unfollows_d","comments_d","server_calls_d","follows_d"],
                              stochastic_flow=True,
                              notify_me=True)

 session.set_do_like(enabled=True, percentage=40)

 session.set_do_comment(enabled=True, percentage=15)

 session.set_comments(['xxxx','xxxx'])

 session.set_do_follow(enabled=True, percentage=30, times=1)

 session.set_simulation(enabled=True, percentage=100)

 session.set_skip_users(skip_private=False, skip_no_profile_pic=False, skip_business=False)

 session.set_action_delays(enabled=True, like=12,comment=60,follow=10,unfollow=10,story=8,randomize=True,random_range_from=30,random_range_to=100,safety_match=True)

 session.set_do_story(enabled = True, percentage = 70, simulate = False)

#.ACTIONS

 session.like_by_tags(['xxxx','xxxx'], amount=10)

 session.follow_by_tags(['xxxx','xxxx'], amount=10)

 session.unfollow_users(amount=10, allFollowing=True, style="LIFO", unfollow_after=3*60*60)

 session.story_by_tags(['xxxx','xxxx'])

 session.join_pods()

**Comment by umang-malhotra** [comment]
This is really a problem for instapy, after few hours of work instagram starts sending the error - Please wait a few minutes before you try again.

If this issue is not resolved, then this instapy project is pretty useless.

**Comment by kanyethelvdon** [comment]
My actions keep getting blocked too, really hope the issue is fixed.

**Comment by Ewwwer** [comment]
Hi, I have found a good solution by deleting the cookie generated by instapy and running it again with an incorrect password so that permit Instagram todetectthe bot and dive back an error. Then, try with the correct one lowering the parameters.

**Comment by umang-malhotra** [comment]
Hello @Ewwwer  Can you elaborate on how we can delete the cookie generated by instapy?

**Comment by Ewwwer** [comment]
The easiest way to do this is to delete the entire instapy folder,return to install it from github and perform the pip install again

**Comment by kanyethelvdon** [comment]
> The easiest way to do this is to delete the entire instapy folder,return to install it from github and perform the pip install again

Can I just delete the user folder in the path 'logs>user>relationship_data'? Also what parameters do you use for follow scripts?
