### ISSUE TITLE
Disabling simulated follow?

### ISSUE THREAD

**Issue by mikemancode** [InstaPy/InstaPy#5243]
I made a new thread since the another one about this subject is old and i don't understand the solution.
Thanks for help by the way and i hope that will also help someone!
My script is very simple since i don't want anything more.
I read about something like gender option, but didn't find the script. Is that possible? Or is it just an idea?
## Expected Behavior
Disabling simulated follows
## Current Behavior
Doing simulated follows, and most important is that i don't want to follow people that i know and don't like.
## InstaPy configuration
# imports
from instapy import InstaPy
from instapy.util import smart_run

# login credentials
insta_username = '*****'
insta_password = '*****'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):

    session.set_relationship_bounds(enabled=True,
                                    potency_ratio= -1,
                                    delimit_by_numbers=False,
                                    max_followers=9999,
                                    max_following=9999,
                                    min_followers=45,
                                    min_following=45)
                                    
    
    session.follow_user_followers(['*****'],

                                  amount=400,
                                  randomize=True,
                                  sleep_delay=600,
                                  interact=False)

**Comment by Yakito** [comment]
Hey, It is in the docu

https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#simulation

**Comment by uluQulu** [comment]
Hey @mikemancode 

Please read the documentation of _simulations_ at the link @Yakito shared. It's quite a small feature but well-documented to fully understand.

Also, gender filtration is fully implemented that you can have a look at my active PR - #5172. As it is not merged into the main repo, you can read there in description where I wrote about how to use it right away.
