### ISSUE TITLE
Control multiple accounts!

### ISSUE THREAD

**Issue by ASMRcode** [InstaPy/InstaPy#5248]
## Expected Behavior
Working
## Current Behavior
In Progress
## Possible Solution (optional)
Hi, Im new to the community, I have a good amount of accounts in my pocket, is there a way I can make a script that follows specific people by username BUT run it thru all my accounts 1 by 1 without having to do it manually, will be willing to add followers to who helps... THANK YOU!!
## InstaPy configuration
running on kali linux just fine!

**Comment by cyberpz** [comment]
Add some followers to @peppuz_ (on IG) ahahaha
You can run a for loop on top so that it cycles a session for every user in a list.
Hope this suggestion is usefull.
