### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\Downloads\instapy-quickstart-master\instapy-quickstart-master\quickstart.py", line 2, in <module>     from instapy import smart_run ImportError: No module named 'instapy'

### ISSUE THREAD

**Issue by Luis952** [InstaPy/InstaPy#5249]
Kann mir wer dabei helfen?
What is the problem?

Luis

**Comment by cyberpz** [comment]
Edit the title of this issue, and post the full traceback in the description.
Then try `pip install -U instapy`

**Comment by Luis952** [comment]
@Peppuz what title should i edit?

**Comment by cyberpz** [comment]
Of the issue! It sucks to read..
doesn't meet the contribution policy
