### ISSUE TITLE
Logs folder question

### ISSUE THREAD

**Issue by kanyethelvdon** [InstaPy/InstaPy#5250]
Hi,

Just wanted to know if deleting the cookies folder located in: "C:\Users\user\InstaPy\logs" deletes the database of previous follows/unfollows and related activity. In other words, if I delete this folder and run a follow script, will it follow the same people I previously followed and unfollowed?

Thanks

**Comment by uluQulu** [comment]
Hey @kanyethelvdon 

Cookie file ends with `.pkl` extension and only holds the _log in_ information which avoids logging in from scratch each time.

Follow and unfollow data is recorded to the database file (_ends with `.db`_), so clear that cookie file comfortably.
