### ISSUE TITLE
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[3]/div/div[2]"}

### ISSUE THREAD

**Issue by serhatavcu** [InstaPy/InstaPy#5253]
hello, how fix this error 

File "C:\Users\Serhat\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body/div[3]/div/div[2]"}
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90),platform=Windows NT 10.0.18362 x86_64)

**Comment by cyberpz** [comment]
Hi, same issue here #5246! 
Waiting to be merged!

**Comment by thinhago** [comment]
theres a fix for this?
