### ISSUE TITLE
Action blocked

### ISSUE THREAD

**Issue by seotami** [InstaPy/InstaPy#5256]
I use an unfollow script .py and always allworks fine (login and so on) then comes this 

This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.

**Comment by kanyethelvdon** [comment]
Yep, I keep getting the same thing. I think it's just an issue with InstaPy that needs to be fixed.

**Comment by seotami** [comment]
Maybe some wrong settings?

**Comment by ASMRcode** [comment]
It was because your account got detected for using a bot, you'll have to delete all cookies and try again

**Comment by seotami** [comment]
This is the configuration

# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = ''
insta_password = ''

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                    min_followers=45,
                                    min_following=77)

    #session.set_dont_include(["friend1", "friend2", "friend3"])
    #session.set_dont_like(["pizza", "#store"])

    # activities
    session.unfollow_users(amount=50, nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)

**Comment by kanyethelvdon** [comment]
> It was because your account got detected for using a bot, you'll have to delete all cookies and try again

If you delete cookies, does the database/logs of who you followed and unfollowed get deleted? In other words, if I delete the cookies and try a follow script, will it follow people I've already previously followed and unfollowed?

**Comment by seotami** [comment]
but geckodriver starts everytime new.

**Comment by seotami** [comment]
?

**Comment by khansaad1275** [comment]
> > It was because your account got detected for using a bot, you'll have to delete all cookies and try again
> 
> If you delete cookies, does the database/logs of who you followed and unfollowed get deleted? In other words, if I delete the cookies and try a follow script, will it follow people I've already previously followed and unfollowed?

I don't think it will work, and are you talking about deleting cookies from your browser?
it won't change anything , every time you run instapy , it opens a new user window which will not contain any data about your previous use.

**Comment by kanyethelvdon** [comment]
> > > It was because your account got detected for using a bot, you'll have to delete all cookies and try again
> > 
> > 
> > If you delete cookies, does the database/logs of who you followed and unfollowed get deleted? In other words, if I delete the cookies and try a follow script, will it follow people I've already previously followed and unfollowed?
> 
> I don't think it will work, and are you talking about deleting cookies from your browser?
> it won't change anything , every time you run instapy , it opens a new user window which will not contain any data about your previous use.

By cookies, I mean the user folder in the path 'logs>user>relationship_data'?

**Comment by Knrd2** [comment]
Every time i activate the following option in my quickstart.py (session.set_do_follow(enabled=True, percentage=10)) im getting blocked right away: Last follow is not verified '' might be temporarily blocked from following. 
Ive just updated the whole project. Please, does anyone know how to fix it?
