### ISSUE TITLE
Instapy installa tion probleme - Help the french girl *o*

### ISSUE THREAD

**Issue by Rockeuze2** [InstaPy/InstaPy#5258]
### hello ! I ever read all other issues i did not fin the solution that why i need help ! 
I installed python & instapy zip
after i open up "cmd"
and it writte this : pip install instapy
but it say this message : 

__Traceback (most recent call last):_
  File "c:\users\ordinateur\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ordinateur\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ordinateur\AppData\Local\Programs\Python\Python38-32\Scripts\pip.exe\__main__.py", line 9, in <module>
TypeError: 'module' object is not callable_

Can you please help me to install ? 
thank you *o*

**Comment by mattberg88** [comment]
what version of pip do you use? It helped to use pip3 to install then python3 to run the script for me.

**Comment by Rockeuze2** [comment]
@mattberg88 i use python 3.8 and pip 19.3.1 , but i dont know how to correct this error :( !?

**Comment by uluQulu** [comment]
Hey @Rockeuze2 
It seems like a bug from _PIP_, possibly after an upgrade.

Try reinstalling **pip**:
```erlang
python -m pip install -U --force-reinstall  pip
```

---

Meanwhile you can always use this style, comfortably:
```erlang
python -m pip install instapy
```
than confusing (_if you have multiple Python interpreters_):
````erlang
pip install instapy
````

---

Hint: If your _Python_ interpreter in use has the _python alias_ of e.g. `python3`, then invoke that command as below, easily:
```erlang
python3 -m pip install instapy
```

**Comment by Rockeuze2** [comment]
i try this :

python -m pip install instapy

and it say that : 

ERROR: clarifai 2.6.2 has requirement configparser<4,>=3.5, but you'll have configparser 4.0.2 which is incompatible.
Installing collected packages: configparser, plyer, regex, selenium, grpcio, protobuf, soupsieve, beautifulsoup4, tqdm, webdriverdownloader, MeaningCloud-python, future, jsonschema, googleapis-common-protos, clarifai, tornado, pycparser, cffi, cryptography, python-telegram-bot, emoji, EasyProcess, instapy
  WARNING: The script tqdm.exe is installed in 'C:\Users\Ordinateur\AppData\Local\Programs\Python\Python38-32\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script webdriverdownloader.exe is installed in 'C:\Users\Ordinateur\AppData\Local\Programs\Python\Python38-32\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
    Running setup.py install for future ... done
  WARNING: The script jsonschema.exe is installed in 'C:\Users\Ordinateur\AppData\Local\Programs\Python\Python38-32\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

i can not try instapy :(

**Comment by uluQulu** [comment]
Hey

Press `Windows`+`Pause`,
then `Advanced system settings`,
then `Environment Variables`,
inside `User variables for Ordinateur`,
click on `Path` and press `Edit` in dropdown menu.
And click on `New` and paste this:
`C:\Users\Ordinateur\AppData\Local\Programs\Python\Python38-32\Scripts`.
Click lots of OKs now and it solves that error above.

**Comment by Rockeuze2** [comment]
hey ! thank you ! i try your idea and it say no error ! but how can i be sure that instapy is really installed? :O

**Comment by uluQulu** [comment]
Run this command at the command prompt,
```erlang
python -m pip show instapy
```
If it is not installed, it will say
`WARNING: Package(s) not found: instapy`
otherwise it will show the package data.

**Comment by Rockeuze2** [comment]
thanks ! i try your last command and it write :
```
Name: instapy
Version: 0.6.6
Summary: Tool for automated Instagram interactions
Home-page: https://github.com/timgrossmann/InstaPy
Author: Tim Großmann
Author-email: contact.timgrossmann@gmail.com
License: GPLv3
Location: c:\users\ordinateur\downloads\instapy-master\instapy-master
Requires: certifi, chardet, clarifai, configparser, EasyProcess, emoji, future, grpcio, idna, jsonschema, plyer, protobuf, requests, selenium, six, urllib3, regex, MeaningCloud-python, PyYAML, webdriverdownloader, python-telegram-bot
Required-by:
```
so i think it's installed ! *o* 
after i use this command : 
`python quickstart.py
`
but any windows was open :( and it write this :(( 

```
._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
No any custom workspace provided.       ~using existing..
InstaPy Version: 0.6.6
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Ordinateur/InstaPy"
WARNING [2019-12-30 19:37:27] [None]  Heeh! Error occurred while getting a DB profile for 'None':
        b'NOT NULL constraint failed: profiles.name'
Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    session = InstaPy()
  File "C:\Users\Ordinateur\Downloads\InstaPy-master\InstaPy-master\instapy\instapy.py", line 306, in __init__
    get_database(make=True)  # IMPORTANT: think twice before relocating
  File "C:\Users\Ordinateur\Downloads\InstaPy-master\InstaPy-master\instapy\database_engine.py", line 66, in get_database
    get_profile(name, address, logger) if profile_id is None or make else profile_id
  File "C:\Users\Ordinateur\Downloads\InstaPy-master\InstaPy-master\instapy\database_engine.py", line 167, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable
```

so what can i do ?  :)

**Comment by uluQulu** [comment]
You must provide a username either at the quickstart script or from the command line interface like this,
```erlang
python qucikstart.py -u Ordinateur
```

**Comment by Rockeuze2** [comment]
i write that on cmd : python quickstart.py -u Ordinateur
but no windows with my insta account :( 

```
[C:\Users\Ordinateur\Downloads\InstaPy-master\InstaPy-master>python quickstart.py -u Ordinateur
[ ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
No any custom workspace provided.       ~using existing..
InstaPy Version: 0.6.6
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Ordinateur/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    session = InstaPy()
  File "C:\Users\Ordinateur\Downloads\InstaPy-master\InstaPy-master\instapy\instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\Ordinateur\Downloads\InstaPy-master\InstaPy-master\instapy\browser.py", line 110, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\Ordinateur\Downloads\InstaPy-master\InstaPy-master\instapy\browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "C:\Users\Ordinateur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 168, in download_and_install
    with zipfile.ZipFile(os.path.join(self.get_download_path(version), filename), mode="r") as driver_zipfile:
  File "C:\Users\Ordinateur\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1234, in __init__
    self._RealGetContents()
  File "C:\Users\Ordinateur\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1301, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file]
```

need your help please ^^

**Comment by uluQulu** [comment]
Geckodriver is the webdriver to run Firefox automatically through Selenium.

Read the geckodriver usage documentation: https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#custom-geckodriver

You can download geckodriver from its [official page](https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-win64.zip) and put to the assets folder at workspace directory (your home folder by default).

Or delete everything related to geckodriver in the assets folder and let InstaPy download it for you.

**Comment by Rockeuze2** [comment]
i do not understand your last comment i need more details , it is very new for me , but i ever installed instapy last year and it was very more easy =/ at time i'm very lost !last year i never installed geckodriver . I red your link but it not very easy to undertand for me as i'm french :S

**Comment by uluQulu** [comment]
Do you have Firefox installed?

**Comment by Rockeuze2** [comment]
yes i have

**Comment by Knrd2** [comment]
i have reinstalled instapy and it says Version: 0.5.8, but there is a more recent version as i see.. ?! any help ?

**Comment by uluQulu** [comment]
Installing exact version of a package:
```python
python -m pip install instapy==0.6.6
```

Upgrade existing package to the latest version:
```python
python -m pip install instapy -U
```

**Comment by Knrd2** [comment]
Version 0.6.6 is for Win and Mac is different, i guess

**Comment by uluQulu** [comment]
InstaPy is deployed as only 1 build wheel in a [generic package](https://pypi.org/project/instapy/#files)  for all platforms.
Anytime, 
```python
python -m pip search instapy
```
to see which latest version of the package you can currently install.

**Comment by Knrd2** [comment]
i cant upgrade it, after running "python -m pip install instapy -U" i get the following info:
Requirement already up-to-date: instapy in /Library/Python/2.7/site-packages (0.5.8)
And python -m pip install instapy==0.6.7 leads to: 
ERROR: No matching distribution found for instapy==0.6.7

Just with python3 -m pip install instapy -U it worked. There ive got the Version 0.6.7. When i run quickstart.py with python3, the bot is working. How can i assure that im always using python3? 

And the program is still using chrome, this is correct?

**Comment by uluQulu** [comment]
That's nothing special. Just keep in mind that your python interpreter is run by `python3` command. And use it whenever you need that command.

E.g.
```python
python3 quicsktart.py --username abc  --password 123
```
And same for  pip commands,
always run as
```python
python3  -m pip ...
```
But you can also change `python3` command to `python` or whatever else in the _system32 folder_, _python installation folder_ and your _user_ or _system path_.
