### ISSUE TITLE
Have they changed something again?

### ISSUE THREAD

**Issue by FBosler** [InstaPy/InstaPy#526]
Unable to locate element: {"method":"xpath","selector":"//footer[@class='_oofbn']/div[@class='_mhrsk _pcuq6']/nav[@class='_p1gbi']/ul[@class='_fh0f2']/li[@class='_fw3ds'][10]/span[@class='_17z9g _c4mil']/select[@class='_nif11']/option[text()='English']"}

new bug?

**Comment by citizenQ** [comment]
got something similiar 

`selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//li[2]/a/span"}`

was in the process of "follow_user_followers" with interact=True

**Comment by timgrossmann** [comment]
@FBosler Please remember to post your quickstart file with each issue.
This will help find the bug ASAP

**Comment by timgrossmann** [comment]
@FBosler @citizenQ Hmm I just checked and the element should still be found with that selector...

**Comment by citizenQ** [comment]
Still occuring. And like the first time it is happening in the second run of follow_user_followers 

--> Ongoing follow 14, now following: b'...'
`
Traceback (most recent call last):
  File "PycharmProjects/InstaPy/botSession.py", line 33, in <module>
    session.follow_user_followers(friends, amount=15, random=True, interact=True)`

  `File "PycharmProjects/InstaPy/instapy/instapy.py", line 693, in follow_user_followers
    userFollowed += follow_given_user_followers(self.browser, user, amount, self.dont_include, self.username, self.follow_restrict, random)`

`  File "PycharmProjects/InstaPy/instapy/unfollow_util.py", line 247, in follow_given_user_followers
    allfollowing = formatNumber(browser.find_element_by_xpath("//li[2]/a/span").text)`

 ` File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)`

 ` File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']`

 ` File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)`

 ` File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)`

`selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//li[2]/a/span"}`

**Comment by timgrossmann** [comment]
@citizenQ As stated 100 times by now. 
**Please Post Your Quickstart File**

I can't reproduce this error and seeing your exact file could help me.

**Comment by citizenQ** [comment]
```python
from instapy import InstaPy

friends = [
    '...',
    '...',
    '...'
]

tags = [
    "#...",
    "#...",
    "#..."
]

session = InstaPy(username='...', password='...', nogui=True)

 session.login()
 session.set_user_interact(amount=5, random=True, percentage=50, media='Photo')
 session.follow_user_followers(friends, amount=15, random=True, interact=True)`
# (Here at the 2nd index of the list 'friends', the error is occuring)

session.set_user_interact(amount=4, random=True, percentage=50, media='Photo')
 session.follow_user_following(friends, amount=10, random=True, interact=True)

session.end()
```

botSession.py

**Comment by FBosler** [comment]
Sorry about that:

the error from above is the error from the error.log.

```
from instapy import InstaPy
from subprocess import call

excludePpl = ["..."]

try:
  InstaPy(username=name, password=pass, nogui=True)\
    .login()\
    .set_dont_include(excludePpl)\
    .unfollow_users(amount=30)\
    .set_upper_follower_count(limit = 500)\
    .set_do_follow(enabled=True, percentage=10, times=1)\
    .set_do_comment(True, percentage=15)\
    .set_comments([comments]) \
    .set_use_clarifai(enabled=True, secret=secret, proj_id=proj_id)\
    .clarifai_check_img_for(['nsfw'])\
    .like_by_tags([tags], amount=200, media='Photo')\
    .unfollow_users(amount=30)\
    .end()

except Exception as err:
  with open('./logs/error.log', 'w') as err_file:
    err_file.write(str(err))


call(["reboot"])
```

**Comment by timgrossmann** [comment]
@FBosler Did you already do a `git pull` in the last days? This looks like something that already has been resolved.

@citizenQ So the second `set_user_interact` is never reached.
Does the error always happen at the same follower of the second friend?

**Comment by citizenQ** [comment]
I'm running it at atm, but I recognise that the new people being followed are all written into the .csv as the same name. Maybe I should setup my project again?

**Comment by citizenQ** [comment]
It is the **14**. one again

**Comment by timgrossmann** [comment]
@citizenQ Could  you check the profile of the 14th and make sure he/she has a public account, and is actually not a dead profile page or even a "Sorry, this webpage..." error page ?

**Comment by FBosler** [comment]
pull fixed it for me, thx for the pointer. If its up to me, this issue could be closed.

**Comment by timgrossmann** [comment]
@FBosler thank you for the information.

@citizenQ could you give me an update?

**Comment by citizenQ** [comment]
sorry for answering so late, so no the profile is fully accessible and it is again the 14. one.

**Comment by timgrossmann** [comment]
@citizenQ just out of curiosity, could you try to use the '.like_by_user()' Feature with that 14. one ?
Just so I know, that his profile is not the problem

**Comment by citizenQ** [comment]
when I run,
```python
from instapy import InstaPy 

session = InstaPy(username='..' password='..', nogui=True)
session.login()
session.like_by_users(usernames=['..'], amount=5, random=True)
session.end()
```
everything is working, but it is stated that 

`Load button not found, working with current images!`

but still everything is working

**Comment by ahmadudin** [comment]
@timgrossmann i think public or private is not the problem, since the error is in `follow_given_user_follower`, and the `like_by_users()` method not yet executed

@citizenQ did you, by any chance, change the browser window size during the session?

**Comment by citizenQ** [comment]
@ahmadudin No I didn't.
