### ISSUE TITLE
Can't login on Ubuntu 

### ISSUE THREAD

**Issue by janptn** [InstaPy/InstaPy#5262]
Hello, i have a problem on my Ubuntu Server Distribution. I can't longer login by InstaPy. On my windows server it's work fine. 

`InstaPy Version: 0.6.6
 ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/root/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-12-19 01:06:12] [xxxxxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-12-19 01:06:12] [xxxxxx]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-12-19 01:06:13] [xxxxxx]  - Internet Connection Status: ok
INFO [2019-12-19 01:06:13] [xxxxxx]  - Current IP is "1.1.1.1." and it's from "Germany/DE"
INFO [2019-12-19 01:06:13] [xxxxxx]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-12-19 01:06:23] [jaxxxxxxltin]  - Instagram WebSite Status: Currently Up
INFO [2019-12-19 01:06:23] [jaxxxxxxultin]  - Instagram Response Time: 140.753 ms
INFO [2019-12-19 01:06:23] [jaxxxxxxn]  - Instagram Reponse Code: 200
INFO [2019-12-19 01:06:23] [jaxxxxxxltin]  - Instagram Server Status: ok
INFO [2019-12-19 01:06:23] [janxxxxxx]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-12-19 01:06:23] [jaxxxxxxin]  - window.navigator.webdriver response: False
INFO [2019-12-19 01:06:23] [jaxxxxxxtin]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
INFO [2019-12-19 01:07:07] [jxxxxxxn]  Timed out with failure while explicitly waiting until title contains 'Login' string!

WARNING [2019-12-19 01:07:22] [jaxxxxxxn]  There was a problem logging you into Instagram. Please try again soon.
.......................................................................................................................
CRITICAL [2019-12-19 01:07:22] [xxxxxxtin]  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2019-12-19 01:07:22] [jxxxxxxin]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2019-12-19 01:07:23] [jxxxxxxn]  Sessional Live Report:
        |> No any statistics to show

[Session lasted 1.53 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-12-19 01:07:23] [xxxxxxn]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo`

have any othe this issue or any a solution?

**Comment by janptn** [comment]
Now i installed a older version of Ubuntu and use Python 3.5 with a clear installed InstaPy. Exactly the same problem. On Windows its works fine, but i would like to start the bot on my server with linux.

I thinked at the first is a popup, like "Use it in a mobile app", but when i change the User-Agent to Windows or Mac it habe no influence. 

I also noticed that there is now the possibility to send driect messages on the computer in the browser.

**Comment by matej2** [comment]
I have the same problem on Windows. It prints me the same error:
> You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

I see that this is working for you.. What configuration are you using?

**Comment by matej2** [comment]
bump

**Comment by matej2** [comment]
bump

**Comment by matej2** [comment]
bump

**Comment by matej2** [comment]
.

**Comment by matej2** [comment]
,.-,m.

**Comment by stelmakhdigital** [comment]
Just use it in python file
```
# -*- codecs: utf-8 -*-
import codecs
```
and it on your Ubuntu
```
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
locale-gen en_US.UTF-8
sudo dpkg-reconfigure locales

```

**Comment by matej2** [comment]
bump
