### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by ResulBulbul** [InstaPy/InstaPy#5263]
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

I keep getting the same error message and no solution provided before as far as i can see. What should i do??

**Comment by michalpulpan** [comment]
I've the same issue on Ubuntu Server  18.04, anyone found solution?

**Comment by lukeisontheroad** [comment]
yes. The error is because you need selenium configured correctly. The easiest is to run this gist: https://gist.github.com/pcgeek86/a1fd9d26f8ad46b51adf9513f67b95f2

**Comment by ghost** [comment]
Thank you sir for your valuable help but sir I am a windows user and this
solution is for Linux. If you could help with windows it would be of great
help.

Thanking you.

Yours sincerly,
Divyansh Sharma

**Comment by cprkrn** [comment]
> yes. The error is because you need selenium configured correctly. The easiest is to run this gist: https://gist.github.com/pcgeek86/a1fd9d26f8ad46b51adf9513f67b95f2

Wowowww thank u

**Comment by imewish** [comment]
@lukeisontheroad  That worked ! Awesome

**Comment by vihuarar** [comment]
Hi
@Byte-hack 
You need to add firefox to your Windows Path
C:\Program Files\Mozilla Firefox

I added, and everything is working
