### ISSUE TITLE
Liking not working at all

### ISSUE THREAD

**Issue by ribtoks** [InstaPy/InstaPy#5264]
## Expected Behavior

Like functionality works

## Current Behavior

```
INFO [2019-12-23 01:19:44] [xxx]  --> Image Liked!
INFO [2019-12-23 01:20:23] [xxx]  -------- WARNING! Image was NOT liked! You have a BLOCK on likes!
```

While actually I do NOT have block on likes.

## InstaPy configuration

Raspberry Pi setup with Firefox ESR and geckodriver 0.23.0. Tried both instapy package and latest master.

**Comment by cprkrn** [comment]
Same for me, changed .py filename which worked for _one_ like. Think it has to do with the IP but not totally sure yet!

**Comment by ribtoks** [comment]
bump!

**Comment by 0xbuidler** [comment]
up

**Comment by yobre** [comment]
UP UP UP!

**Comment by ribtoks** [comment]
Up!

**Comment by TheColorman** [comment]
up

**Comment by AntouanK** [comment]
same issue here.
from the browser in the same IP like works fine.
any solutions to this?

**Comment by AntouanK** [comment]
I emptied my `tmp` and `root/InstaPy` and it seems to be working fine again.

**Comment by stefanbschneider** [comment]
not stale
