### ISSUE TITLE
Filtering Inappropriate/nsfw content.

### ISSUE THREAD

**Issue by irinhuman** [InstaPy/InstaPy#527]
Hello Tim,

Is there a way to turn off/ exclude the filtering of clarifai? Is there a way to make it include images with certain tags even if clarifai labels the image nsfw?

Thanks in Advance,
J

EDIT: I realize that you can just turn the clarifai image check into a comment to stop the script from running.

**Comment by timgrossmann** [comment]
@irinhuman Exactly

**Comment by Namaslayer** [comment]
Hey @irinhuman and @timgrossmann  I have the same question. I did what @irinhuman mentioned, but it is still skipping over inappropriate photos. I'm running this on a yoga brand, and it thinks women stretching in yoga pants is inapparopriate. It ends up skipping over more images than it likes per session, so I'm wasting a lot of time.

Heres the code I have. Am I missing something?

<img width="642" alt="screen shot 2017-10-05 at 8 59 55 am" src="https://user-images.githubusercontent.com/31394074/31237358-9730c796-a9ab-11e7-9164-cf0aed40abc0.png">

**Comment by timgrossmann** [comment]
@Namaslayer InstaPy sadly still works as it worked before...

This means, all the setup before the actual interactio...
First you do all the `.set_xzy` stuff and then you do `.interact/like/follow`
Please simply move the last lines above your `user_interact` line

Thank you

**Comment by Namaslayer** [comment]
@timgrossmann Thank you! I'll make the correction now.
