### ISSUE TITLE
http://ip4.seeip.org/geoip is down?

### ISSUE THREAD

**Issue by codypratt22** [InstaPy/InstaPy#5270]
connection 1/3 issue ip4.seeip.org/geoip is down. I cannot access the url on any browser is there another site that can fetch this info or a way to get around this?

**Comment by michalpulpan** [comment]
Yep, I'm facing the same problem right now. I tried doing few mods to login_util.py but decided to leave it and turn off my bot for a while and wait if  ip4.seeip.org/geoip gets back to life

**Comment by codypratt22** [comment]
Its still not up... Any other sites?

**Comment by codypratt22** [comment]
Yea so I just deleted the whole try block for connection 1/3 and it works.

**Comment by michalpulpan** [comment]
> Yea so I just deleted the whole try block for connection 1/3 and it works.

Do you mind asking what exactly should I delete? I deleted this block:

```
# check connection status
    try:
        logger.info("-- Connection Checklist [1/3] (Internet Connection Status)")
        browser.get("view-source:https://ip4.seeip.org/geoip")
        pre = browser.find_element_by_tag_name("pre").text
        current_ip_info = json.loads(pre)
        if (
            proxy_address is not None
            and socket.gethostbyname(proxy_address) != current_ip_info["ip"]
        ):
            logger.warn("- Proxy is set, but it's not working properly")
            logger.warn(
                '- Expected Proxy IP is "{}", and the current IP is "{}"'.format(
                    proxy_address, current_ip_info["ip"]
                )
            )
            logger.warn("- Try again or disable the Proxy Address on your setup")
            logger.warn("- Aborting connection...")
            return False
        else:
            logger.info("- Internet Connection Status: ok")
            logger.info(
                '- Current IP is "{}" and it\'s from "{}/{}"'.format(
                    current_ip_info["ip"],
                    current_ip_info["country"],
                    current_ip_info["country_code"],
                )
            )
            update_activity(
                browser,
                action=None,
                state="Internet connection is ok",
                logfolder=logfolder,
                logger=logger,
            )
    except Exception:
        logger.warn("- Internet Connection Status: error")
        update_activity(
            browser,
            action=None,
            state="There is an issue with the internet connection",
            logfolder=logfolder,
            logger=logger,
        )
        return False
```

And it threw error 

```
INFO [2020-01-02 10:47:43] [profile]  -- Connection Checklist [2/3] (Instagram Server Status)
WARNING [2020-01-02 10:47:54] [profile]  - Instagram Server Status: error
........................................................................................................................
CRITICAL [2020-01-02 10:47:55] [profile]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
```

Just - sure it works also if I delete 2/3 test for IG connection as well, but it's a bit dirty solution in my opinion, or at least, it nice to have some soft of protection when IG is down.

Thank you!

**Comment by codypratt22** [comment]
this is what mine looks like 

def check_browser(browser, logfolder, logger, proxy_address):
    # set initial state to offline
    update_activity(
        browser,
        action=None,
        state="trying to connect",
        logfolder=logfolder,
        logger=logger,
    )


    # check Instagram.com status
    try:
        logger.info("-- Connection Checklist [2/3] (Instagram Server Status)")
        browser.get("https://isitdownorjust.me/instagram-com/")
        sleep(2)
        # collect isitdownorjust.me website information
        website_status = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "website_status")
        )
        response_time = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "response_time")
        )
        response_code = browser.find_element_by_xpath(
            read_xpath(login_user.__name__, "response_code")
        )

        logger.info("- Instagram WebSite Status: {} ".format(website_status.text))
        logger.info("- Instagram Response Time: {} ".format(response_time.text))
        logger.info("- Instagram Reponse Code: {}".format(response_code.text))
        logger.info("- Instagram Server Status: ok")
        update_activity(
            browser,
            action=None,
            state="Instagram servers are running correctly",
            logfolder=logfolder,
            logger=logger,
        )
    except Exception:
        logger.warn("- Instagram Server Status: error")
        update_activity(
            browser,
            action=None,
            state="Instagram server is down",
            logfolder=logfolder,
            logger=logger,
        )
        return False

    # check if hide-selenium extension is running
    logger.info("-- Connection Checklist [3/3] (Hide Selenium Extension)")
    webdriver = browser.execute_script("return window.navigator.webdriver")
    logger.info("- window.navigator.webdriver response: {}".format(webdriver))
    if webdriver:
        logger.warn("- Hide Selenium Extension: error")
    else:
        logger.info("- Hide Selenium Extension: ok")

    # everything is ok, then continue(True)
    return True

**Comment by michalpulpan** [comment]
> this is what mine looks like
> 
> def check_browser(browser, logfolder, logger, proxy_address):
> # set initial state to offline
> update_activity(
> browser,
> action=None,
> state="trying to connect",
> logfolder=logfolder,
> logger=logger,
> )
> 
> ```
> # check Instagram.com status
> try:
>     logger.info("-- Connection Checklist [2/3] (Instagram Server Status)")
>     browser.get("https://isitdownorjust.me/instagram-com/")
>     sleep(2)
>     # collect isitdownorjust.me website information
>     website_status = browser.find_element_by_xpath(
>         read_xpath(login_user.__name__, "website_status")
>     )
>     response_time = browser.find_element_by_xpath(
>         read_xpath(login_user.__name__, "response_time")
>     )
>     response_code = browser.find_element_by_xpath(
>         read_xpath(login_user.__name__, "response_code")
>     )
> 
>     logger.info("- Instagram WebSite Status: {} ".format(website_status.text))
>     logger.info("- Instagram Response Time: {} ".format(response_time.text))
>     logger.info("- Instagram Reponse Code: {}".format(response_code.text))
>     logger.info("- Instagram Server Status: ok")
>     update_activity(
>         browser,
>         action=None,
>         state="Instagram servers are running correctly",
>         logfolder=logfolder,
>         logger=logger,
>     )
> except Exception:
>     logger.warn("- Instagram Server Status: error")
>     update_activity(
>         browser,
>         action=None,
>         state="Instagram server is down",
>         logfolder=logfolder,
>         logger=logger,
>     )
>     return False
> 
> # check if hide-selenium extension is running
> logger.info("-- Connection Checklist [3/3] (Hide Selenium Extension)")
> webdriver = browser.execute_script("return window.navigator.webdriver")
> logger.info("- window.navigator.webdriver response: {}".format(webdriver))
> if webdriver:
>     logger.warn("- Hide Selenium Extension: error")
> else:
>     logger.info("- Hide Selenium Extension: ok")
> 
> # everything is ok, then continue(True)
> return True
> ```

Thank you, I got it running!

**Comment by ShiftingKill** [comment]
What I did was commented out lines in login_util.py: ~Line 276
`# Hotfix - this check crashes more often than not -- plus in not necessary, I can verify my own connection
    # if want_check_browser:
    #     if not check_browser(browser, logfolder, logger, proxy_address):
    #         return False`
And then leave `def login_user:` alone.
