### ISSUE TITLE
Pi3 - Message: connection refused

### ISSUE THREAD

**Issue by maury37** [InstaPy/InstaPy#5271]
Hi everyone, 

I have the same problem for a few months now and I'd like to see if anyone managed to resolve this issue. 
I'm using a Raspberry Pi 3b+ and since I updated InstaPy in 0.6.X version, (and so switching from Chromium to Firefox) I have a problem happening randomly. 

## Current Behavior
When I start my quickstart.py, I have an issue 50% of the time at the beginning. I need to run several times to make my script working. So with Crontab, it runs 1/10 of the time...

Thanks a lot for your help :-)

## Versions
InstaPy 0.6.6
Mozilla Firefox 60.9.0
geckodriver 0.23.0 ( 2018-10-04)
Python 3.7.3
Selenium 3.141.0

## Output 
InstaPy Version: 0.6.6
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"
Traceback (most recent call last):
  File "/home/pi/InstaPy/quickstart.py", line 32, in <module>
    want_check_browser=False)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

## Geckodriver.log when it doesn't work
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
1578041032975 mozrunner::runner INFO  Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.u4FXXaha0mKg"

(firefox-esr:18549): Gtk-WARNING **: 09:44:06.328: Theme parsing error: <data>:1:34: Expected ')' in color definition

(firefox-esr:18549): Gtk-WARNING **: 09:44:06.328: Theme parsing error: <data>:1:78: Expected ')' in color definition
[Child 18640, Chrome_ChildThread] WARNING: pipe error (30): Connexion ré-initialisée par le correspondant: file /build/firefox-esr-TDEydZ/firefox-esr-60.9.0esr/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 342

## Geckodriver.log when it works 
1578041169949 mozrunner::runner INFO  Running command: "/usr/bin/firefox" "-marionette" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.hIPxjLKVkwg7"

(firefox-esr:18690): Gtk-WARNING **: 09:46:19.186: Theme parsing error: <data>:1:34: Expected ')' in color definition

(firefox-esr:18690): Gtk-WARNING **: 09:46:19.187: Theme parsing error: <data>:1:78: Expected ')' in color definition
1578041205724 Marionette  INFO  Listening on port 33643
1578041205818 Marionette  WARN  TLS certificate errors will be ignored for this session

## Attempts to resolve
- Switching between different versions of geckodriver (0.17 to 0.26)
- Updating from Raspbian 9 Stretch to 10 Buster
- Complete fresh install with Buster 10 (following exactly the tutorial for RPi in the doc)
- Creating a CONF_SWAPSIZE=500 (from https://github.com/timgrossmann/InstaPy/issues/5001)
- Using xvfb instead of simple Python3 command to launch the script

**Comment by jonauj** [comment]
Hey @maury37, can you tell me how you got firefox 60 to work on your raspberry pi? I can't seem to get insteps to work on firefox-esr 52.9 at all
