### ISSUE TITLE
Someone please guide me to use instapy!!

### ISSUE THREAD

**Issue by blast69** [InstaPy/InstaPy#5273]
I need to follow and like photos of people who comment on an account
... pls!!!

**Comment by elricmarci** [comment]
Have you tried reading the setup and the info in the main page?

**Comment by AnwarAhmedPSU** [comment]
Does it still work for you? @elricmarci

**Comment by jfranecki** [comment]
@blast69
Documentation(This should be the only thing you need): https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md

Free Instapy Udemy Overview: https://www.udemy.com/course/instapy-guide/

Basic Python: https://www.youtube.com/watch?v=YYXdXT2l-Gg&list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU
