### ISSUE TITLE
webdriverdownloader raises RuntimeError

### ISSUE THREAD

**Issue by Alirezamn93** [InstaPy/InstaPy#5282]
hi, I've installed InstaPy by pip3
when I run this
```
import instapy
instapy.InstaPy(username='USERNAME',password='PASSWROD)
```
I get this error

```
Error, unable to determine correct filename for Nonebit linux
"/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for Nonebit linux

```
what is wrong?

**Comment by elvirmuslic** [comment]
Your linux is likely not known and you will have to download the mozila webdriver customly and set it up or use it on a machine with ubuntu or similar.

**Comment by elvirmuslic** [comment]
Nope I was wrong, if you reinstall it gives a similar error on windows too.
RuntimeError: Error, unable to determine correct filename for Nonebit win 

I have used instapy gui to be specific

**Comment by Javit96** [comment]
I´m having the same problem like @Alirezamn93, on a Windows 10 build:1903

**Comment by t0in4** [comment]
sudo vi /usr/local/lib/python3.7/dist-packages/webdriverdownloader-1.1.0.1-py3.7.egg/webdriverdownloader/webdriverdownloader.py

make change in 124 line 
download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
to 
download_url = self.get_download_url(version, os_name=os_name, bitness="64")

**Comment by t0in4** [comment]
if then it will raise such error:
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
just install firefox-esr:
sudo apt-get install firefox-esr

**Comment by faktor73** [comment]
> sudo vi /usr/local/lib/python3.7/dist-packages/webdriverdownloader-1.1.0.1-py3.7.egg/webdriverdownloader/webdriverdownloader.py
> 
> make change in 124 line
> download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
> to
> download_url = self.get_download_url(version, os_name=os_name, bitness="64")

This fixed it for me on Win10_1909. The line is currently 129 (maybe because slightly other py-version).
After the first start of windows_start.bat one more error came up, but after the second start it worked well (started Firefox and did its thing).

**Comment by leojoker** [comment]
No meu caso tambem resolveu estou win 10

**Comment by stefanbschneider** [comment]
Isn't this configurable from the `quickstart.py` somehow? Would be much cleaner than changing source code

**Comment by stefanbschneider** [comment]
Ok, I fixed it for me by downloading geckodriver manually and specifying the path when creating the InstaPy session inside the quickstart:

```python
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  geckodriver_path='driver/geckodriver.exe')
```

**Comment by MarshallJohansson** [comment]
I have the same problem


> Ok, I fixed it for me by downloading geckodriver manually and specifying the path when creating the InstaPy session inside the quickstart:
> 
> ```python
> session = InstaPy(username=insta_username,
>                   password=insta_password,
>                   headless_browser=False,
>                   geckodriver_path='driver/geckodriver.exe')
> ```

and for linux how to configure?

**Comment by egyjs** [comment]
> sudo vi /usr/local/lib/python3.7/dist-packages/webdriverdownloader-1.1.0.1-py3.7.egg/webdriverdownloader/webdriverdownloader.py
> 
> make change in 124 line
> download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
> to
> download_url = self.get_download_url(version, os_name=os_name, bitness="64")

thanks! this is the solution in both [WIN & LINUX]

**Comment by themannuel** [comment]
from instapy import InstaPy
from instapy import smart_run

session = InstaPy(username='xxxxxxx', password='xxxxxxx')

with smart_run(session):
	session.set_do_follow(enabled = True, percentage = 100)
	session.set_do_like(enabled = True, percentage= 100)

	session.like_by_tags(['xxxxxxx', 'xxxxxx', 'xxxxxxxxxx'], amount = 150)

	comentarios = ['xxxxxxxxx']
	session.set_do_comments(enable=True, percentage=95)
	session.set_comments(comentarios, media= 'Photo')
	session.join_pods()

ERROR: WIndows 10 64 bits
Error, unable to determine correct filename for Nonebit win
Traceback (most recent call last):
File "hastag.py", line 4, in <module>
.
.
.
RuntimeError: Error, unable to determine correct filename for Nonebit win

Could the noble colleagues help me, please ??

**Comment by darox** [comment]
I'm currently hitting the same issue.Setting the bitness to "64" doesn't help. 

Workspace in use: "/home/dario/InstaPy"
Error, unable to determine correct filename for 64bit linux
Traceback (most recent call last):
  File "/dockerdata/instapy/getStats.py", line 10, in <module>
    headless_browser=True)
  File "/home/dario/.local/lib/python3.7/site-packages/instapy/instapy.py", line 322, in __init__
    self.logger,
  File "/home/dario/.local/lib/python3.7/site-packages/instapy/browser.py", line 114, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/home/dario/.local/lib/python3.7/site-packages/instapy/browser.py", line 36, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/home/dario/.local/lib/python3.7/site-packages/webdriverdownloader/webdriverdownloader.py", line 177, in download_and_install
    show_progress_bar=show_progress_bar)
  File "/home/dario/.local/lib/python3.7/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness="64")
  File "/home/dario/.local/lib/python3.7/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit linux


Same error on a fresh installation on another machine.

**Comment by taffarel55** [comment]
I have the same error @darox.. 

It doesnt appear more: `RuntimeError: Error, unable to determine correct filename for Nonebit win`

Even setting bitness to 64: `RuntimeError: Error, unable to determine correct filename for 64bit linux`

I've already:
- [x] Reinstall firefox
- [x] Reinstall webdriverdownloader
- [x] Reinstall instapy
- [x] Use another Linux distro

**Comment by ghost** [comment]
Hello all, same error also for me : RuntimeError: Error, unable to determine correct filename for 64bit linux

**Comment by robertcodron** [comment]
Hi, 
On Ubuntu 19.10 : 
**sudo apt install firefox-geckodriver**
fix the issue for me

**Comment by oliyan** [comment]
> Hi,
> On Ubuntu 19.10 :
> **sudo apt install firefox-geckodriver**
> fix the issue for me

^^ This is the correct solution. Please follow this.

**Comment by darox** [comment]
> Hi,
> On Ubuntu 19.10 :
> **sudo apt install firefox-geckodriver**
> fix the issue for me

I can confirm. Thank you!

Fixes the issue for bare metal but not for the docker version of instapy.

**Comment by taffarel55** [comment]
I confirm too. Gracias!

`sudo pacman -S geckodriver` on Arch/Manjaro

**Comment by ghost** [comment]
Solved too! awesome! Thank you!

Il giorno gio 30 lug 2020 alle ore 12:26 robertcodron <
notifications@github.com> ha scritto:

**Comment by alex-wahl** [comment]
> Hi,
> On Ubuntu 19.10 :
> **sudo apt install firefox-geckodriver**
> fix the issue for me

It solved the problem by me as well, thanks!

**Comment by MarceloFullStack** [comment]
> Hi,
> On Ubuntu 19.10 :
> **sudo apt install firefox-geckodriver**
> fix the issue for me

perfect

**Comment by Housain-maina** [comment]
> Hi,
> On Ubuntu 19.10 :
> **sudo apt install firefox-geckodriver**
> fix the issue for me

Worked, thanks.

**Comment by newborngeek** [comment]
iMac ~ % sudo apt install firefox-geckodriver
Password:
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.

**Comment by newborngeek** [comment]
> iMac ~ % sudo apt install firefox-geckodriver
> Password:
> The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
> Please visit http://www.java.com for information on installing Java.

This is what I get after trying **sudo apt install firefox-geckodriver**

**Comment by t0in4** [comment]
You need to visit http://www.java.com and download java dmg setup and install.
