### ISSUE TITLE
Is Anyone having success with InstaPy

### ISSUE THREAD

**Issue by AnwarAhmedPSU** [InstaPy/InstaPy#5283]
Is anyone on this thread using InstaPy smoothly? Or is this not working anymore?

**Comment by AnwarAhmedPSU** [comment]
Anyone??

**Comment by cyberpz** [comment]
I got some trouble updating from 0.6.6 to 0.6.7. Log in doesn't work (for me) anymore. 
Firefox is the only browser that works today.
I'mma look for solutions after my exam tomorrow afternoon.

**Comment by ghost** [comment]
I haven't gotten this to work every since about a year ago. I just now came back to checkout the repo and where it's at. Doesn't seem very alive anymore.

**Comment by cyberpz** [comment]
Never mind! 
I'm running good now, i just set parameters before `smart_run` and it failed to login.

**Comment by ghost** [comment]
> Never mind!
> I'm running good now, i just set parameters before `smart_run` and it failed to login.

can you tell me what version are you using  and your quickstart.py? mine stop working like 6 months ago and i cant get it to work

**Comment by cyberpz** [comment]
@Banginpadr 
> can you tell me what version are you using and your quickstart.py? mine stop working like 6 months ago and i cant get it to work

I'm not using a quickstart but i'm using 0.6.7 and it works good for me, what is your problem?
Give us some Traceback or something.
