### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5284]
File "/Users/banginpadr/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=62132): Max retries exceeded with url: /session/57de098c-1e27-0145-b7cd-2b1bf1600187/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109dc9e48>: Failed to establish a new connection: [Errno 61] Connection refused',))

I KEEP GETTING THIS ERROR. ANYONE THAT CAN HELP PLEASE? THANK YOU

**Comment by meloluan** [comment]
Same problem here:

InstaPy Version: 0.6.7
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 

---------------------------------------------------------------------------
WebDriverException                        Traceback (most recent call last)
<ipython-input-13-35b541e62f64> in <module>
     19     i+=1
     20 
---> 21 session = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
     22 
     23 with smart_run(session):

~/.local/lib/python3.6/site-packages/instapy/instapy.py in __init__(self, username, password, nogui, selenium_local_session, browser_profile_path, page_delay, show_logs, headless_browser, proxy_username, proxy_password, proxy_address, proxy_port, disable_image_load, multi_logs, log_handler, geckodriver_path, split_db, bypass_security_challenge_using, want_check_browser)
    317                 page_delay,
    318                 geckodriver_path,
--> 319                 self.logger,
    320             )
    321             if len(err_msg) > 0:

~/.local/lib/python3.6/site-packages/instapy/browser.py in set_selenium_local_session(proxy_address, proxy_port, proxy_username, proxy_password, headless_browser, browser_profile_path, disable_image_load, page_delay, geckodriver_path, logger)
    112         firefox_profile=firefox_profile,
    113         executable_path=driver_path,
--> 114         options=firefox_options,
    115     )
    116 

~/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py in __init__(self, firefox_profile, firefox_binary, timeout, capabilities, proxy, executable_path, options, service_log_path, firefox_options, service_args, desired_capabilities, log_path, keep_alive)
    172                 command_executor=executor,
    173                 desired_capabilities=capabilities,
--> 174                 keep_alive=True)
    175 
    176         # Selenium remote

~/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py in __init__(self, command_executor, desired_capabilities, browser_profile, proxy, keep_alive, file_detector, options)
    155             warnings.warn("Please use FirefoxOptions to set browser profile",
    156                           DeprecationWarning, stacklevel=2)
--> 157         self.start_session(capabilities, browser_profile)
    158         self._switch_to = SwitchTo(self)
    159         self._mobile = Mobile(self)

~/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py in start_session(self, capabilities, browser_profile)
    250         parameters = {"capabilities": w3c_caps,
    251                       "desiredCapabilities": capabilities}
--> 252         response = self.execute(Command.NEW_SESSION, parameters)
    253         if 'sessionId' not in response:
    254             response = response['value']

~/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py in execute(self, driver_command, params)
    319         response = self.command_executor.execute(driver_command, params)
    320         if response:
--> 321             self.error_handler.check_response(response)
    322             response['value'] = self._unwrap_value(
    323                 response.get('value', None))

~/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py in check_response(self, response)
    240                 alert_text = value['alert'].get('text')
    241             raise exception_class(message, screen, stacktrace, alert_text)
--> 242         raise exception_class(message, screen, stacktrace)
    243 
    244     def _value_or_default(self, obj, key, default):

WebDriverException: Message: connection refused

**Comment by meloluan** [comment]
It looks like it was a temporary thing, it's back to normal now.
