### ISSUE TITLE
invalid Like elemnet 

### ISSUE THREAD

**Issue by Abdulsamipy** [InstaPy/InstaPy#5288]
## Expected Behavior

like image
comment on the user post 

## Current Behavior

1. `invalid Like element `
2. not commenting on post  

## Possible Solution (optional)
not in my knowledge but can try to edit xpath .. maybe Instagram has changed it 
## InstaPy configuration

`from instapy import InstaPy
from instapy import smart_run
import time 

session = InstaPy(username='', password='')

with smart_run(session):

    session.set_relationship_bounds(enabled=True,
                 potency_ratio=None,
                  delimit_by_numbers=True,
                   max_followers=2000000,
                    max_following=10000,
                     min_followers=10,
                      min_following=10)
    session.set_user_interact(amount=2, randomize=True, percentage=100,
    media='Photo')
    session.set_do_follow(enabled=True, percentage=100)
    time.sleep(30)
    session.set_do_like(enabled=True, percentage=100)
    session.set_comments(["Your work is rockin @{}", "Well done @{} :muscle:", "Your posts are excellent :thumbsup: ", "What a really nice photo, great job! @{}"])
    session.set_do_comment(enabled=True, percentage=100)
    session.set_user_interact(amount=2, randomize=True, percentage=100,
    media='Photo')

    # activity

    session.interact_user_followers(['pewdiepie'],
    amount=10, randomize=True)
    session.follow_user_followers(['pewdiepie'],
    amount=10, randomize=True, interact=True)
    session.unfollow_users(amount=100, nonFollowers=True, style="RANDOM",
    unfollow_after=42*60*60, sleep_delay=30)
    session.like_by_tags(['fashion', 'style', 'consciousfashion', 'fashioneveryday', 'lookoftheday', 'womensfashionfinds', 'fashiontech', 'whatiwore'], amount=10)
    time.sleep(20)

    """ Joining Engagement Pods...
    """
    photo_comments = ['I like how you put your posts together @{}',
        'Your work is rockin @{}',
        'Your posts are excellent :thumbsup:',
        'Amazing work. Keep going! :open_mouth:',
        'What a really nice photo, great job! @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Getting inspired by you @{}',
        ':raised_hands: Yes!',
        'Well done @{} :muscle:']
    session.set_do_comment(enabled = True, percentage = 100)
    session.set_comments(photo_comments, media = 'Photo')
    session.join_pods(topic='food')`

**Comment by kami4ka** [comment]
+1

**Comment by ghost** [comment]
same here

**Comment by erikhayton** [comment]
same. Tried changing xpath in like_util.py to multiple different elements that I can call from a scrapy shell. None of them work.

printing like_xpath returns: 
//section/span/button/span[@aria-label='Like']

**Comment by LeandroSummo** [comment]
It's the same for me! (--> Invalid Like Element!) Anyone have find a solution?

**Comment by zipsoft** [comment]
IG changed HTML code 

try next to do:

In the file xpath_compile.py change:

`
xpath["like_image"] = {
"like": "//section/span/button/span[@aria-label='Like']",
"unlike": "//section/span/button/span[@aria-label='Unlike']",
`

to:
Relative path >
`
xpath["like_image"] = {
    "like": "//button[*[local-name()='svg']/@aria-label='Like']",
    "unlike": "//button[*[local-name()='svg']/@aria-label='Unlike']",
}
`

or to Absolute path >
`
xpath["like_image"] = {
    "like": "/html/body/div[1]/section/main/div/div/article/div[2]/section[1]/span[1]/button[*[local-name()='svg']/@aria-label='Like']",
    "unlike": "/html/body/div[1]/section/main/div/div/article/div[2]/section[1]/span[1]/button[svg/@aria-label='Unlike']",
}
`

It's working for me. For now...

**Comment by Abdulsamipy** [comment]
> IG changed HTML code
> 
> try next to do:
> 
> In the file xpath_compile.py change:
> 
> `xpath["like_image"] = { "like": "//section/span/button/span[@aria-label='Like']", "unlike": "//section/span/button/span[@aria-label='Unlike']",`
> 
> to:
> Relative path >
> `xpath["like_image"] = { "like": "//button[*[local-name()='svg']/@aria-label='Like']", "unlike": "//button[*[local-name()='svg']/@aria-label='Unlike']", }`
> 
> or to Absolute path >
> `xpath["like_image"] = { "like": "/html/body/div[1]/section/main/div/div/article/div[2]/section[1]/span[1]/button[*[local-name()='svg']/@aria-label='Like']", "unlike": "/html/body/div[1]/section/main/div/div/article/div[2]/section[1]/span[1]/button[svg/@aria-label='Unlike']", }`
> 
> It's working for me. For now...

so i tried editing the code inside xpath_compile.py and the bot is not evening starting, tried both code 

![code](https://user-images.githubusercontent.com/58009877/72667408-8c54b880-3a3d-11ea-83ae-130f1c129d03.PNG)

**Comment by LeandroSummo** [comment]
> IG changed HTML code
> 
> try next to do:
> 
> In the file xpath_compile.py change:
> 
> `xpath["like_image"] = { "like": "//section/span/button/span[@aria-label='Like']", "unlike": "//section/span/button/span[@aria-label='Unlike']",`
> 
> to:
> Relative path >
> `xpath["like_image"] = { "like": "//button[*[local-name()='svg']/@aria-label='Like']", "unlike": "//button[*[local-name()='svg']/@aria-label='Unlike']", }`
> 
> or to Absolute path >
> `xpath["like_image"] = { "like": "/html/body/div[1]/section/main/div/div/article/div[2]/section[1]/span[1]/button[*[local-name()='svg']/@aria-label='Like']", "unlike": "/html/body/div[1]/section/main/div/div/article/div[2]/section[1]/span[1]/button[svg/@aria-label='Unlike']", }`
> 
> It's working for me. For now...

Perfect! It works. Thanks so much

**Comment by Abdulsamipy** [comment]
> > IG changed HTML code
> > try next to do:
> > In the file xpath_compile.py change:
> > `xpath["like_image"] = { "like": "//section/span/button/span[@aria-label='Like']", "unlike": "//section/span/button/span[@aria-label='Unlike']",`
> > to:
> > Relative path >
> > `xpath["like_image"] = { "like": "//button[*[local-name()='svg']/@aria-label='Like']", "unlike": "//button[*[local-name()='svg']/@aria-label='Unlike']", }`
> > or to Absolute path >
> > `xpath["like_image"] = { "like": "/html/body/div[1]/section/main/div/div/article/div[2]/section[1]/span[1]/button[*[local-name()='svg']/@aria-label='Like']", "unlike": "/html/body/div[1]/section/main/div/div/article/div[2]/section[1]/span[1]/button[svg/@aria-label='Unlike']", }`
> > It's working for me. For now...
> 
> Perfect! It works. Thanks so much

can you post a screenshot of your xpath_compile.py where you add the code

**Comment by LeandroSummo** [comment]
> > > IG changed HTML code
> > > try next to do:
> > > In the file xpath_compile.py change:
> > > `xpath["like_image"] = { "like": "//section/span/button/span[@aria-label='Like']", "unlike": "//section/span/button/span[@aria-label='Unlike']",`
> > > to:
> > > Relative path >
> > > `xpath["like_image"] = { "like": "//button[*[local-name()='svg']/@aria-label='Like']", "unlike": "//button[*[local-name()='svg']/@aria-label='Unlike']", }`
> > > or to Absolute path >
> > > `xpath["like_image"] = { "like": "/html/body/div[1]/section/main/div/div/article/div[2]/section[1]/span[1]/button[*[local-name()='svg']/@aria-label='Like']", "unlike": "/html/body/div[1]/section/main/div/div/article/div[2]/section[1]/span[1]/button[svg/@aria-label='Unlike']", }`
> > > It's working for me. For now...
> > 
> > 
> > Perfect! It works. Thanks so much
> 
> can you post a screenshot of your xpath_compile.py where you add the code

of course!
<img width="892" alt="Schermata 2020-01-18 alle 18 30 31" src="https://user-images.githubusercontent.com/27067633/72667863-b055d100-3a20-11ea-98d2-66f17f812310.png">
