### ISSUE TITLE
cannot import 'InstaPy' (incorrect installation?)

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#529]
Excuse my new-ness, but trying to run InstaPy in a DigitalOcean droplet. I went through the install procedure and all seems well-- I then cd'd into InstaPy/examples and changed example.py with the correct username and password.

I then tried to run it with:
`python3 example.py`
to which I get the error
`Import Error: cannot import name 'InstaPy'`

so I assume something went wrong when I was installing. So I went back and ran
`python setup.py install`
which gives the error:
`The program 'python' can be found in the following packages:`
` *Python-minimal`
`*python3`
`Try: apt get install <selected package>`

So I'm assuming this is where the error is coming from, so I ran
`python3 setup.py install`
which filled the console with all kinds of promising looking stuff that ended with
`Finished processing dependencies for instagram-py==0.0.1`

Which looked good so I navigated back to my python and tried to run it with
`python3 example.py`
but still got 
`Import Error: cannot import name 'InstaPy'`

Suggestions?

**Comment by sojan-official** [comment]
the instapy module exists in the root folder of InstaPy. 
copy the example.py to root folder and try running from there.

https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path

**Comment by ghost** [comment]
@sojan-official I moved example.py into the InstaPy/ folder and ran it, which looks like it made it further then last time, however it ended with error
`selenium.commom.exceptions.WebDriverException: Message unknown error: Chrome Failed to start: excited abnormally`
so now I have an error in my chrome installation? I went through and did the installation steps for chrome again with no error messages-- I am now running example.py from InstaPy/

**Comment by sojan-official** [comment]
do you have the chrome webdriver in assets folder ? 

https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu.md

**Comment by ghost** [comment]
@sojan-official  chromedriver is in ~/InstaPy/assets alongside unicodes.md

**Comment by ghost** [comment]
Solved!

For future people in the same situation, be sure to set nogui=True.
