### ISSUE TITLE
Follow people who follow a certain profile

### ISSUE THREAD

**Issue by Edresson** [InstaPy/InstaPy#5294]
Hi,

Currently instagram is blocking access by instagram browser that access many profiles during the day. This is a great idea to block bots.

Intapy is being blocked.

When we post to follow people who commented/liked a post, we saved the list of users and after we entered our profile and followed it. Given the previous information this is easily detectable, since most people do not use instagram web (website).

To get around this problem I thought of following the person without entering the profile by clicking on followers in a profile for example and go following in the window that opens. This way the traffic is much smaller and it is more difficult to be detected.

Does anyone know how to do this on Instapy?

is there any function to scroll through the list of followers of a profile?

English is not my native language. I'm sorry.

**Comment by cyberpz** [comment]
Interesting topic, I agree when you say the bot make tons of detectable traffic by just grabbing some followers and visiting users page just to follow and fast refresh to check. 

How can we edit the bot to make less traffic and more aggregated actions in a single page?

**Comment by Edresson** [comment]
One way would be to access the followers of a determined (instagram.com/*****/followers), and go by clicking on the "follow" button (note: do not enter the profile just follow). This way you would be able to follow several profiles being in only 1.

**Comment by cyberpz** [comment]
Than the check of follow shouldn't refresh, instead he has to check the button?

**Comment by Edresson** [comment]
I think so, if it were possible it would be much more difficult to detect.

**Comment by cyberpz** [comment]
We should seriosly plan this, currently the bot reaches a peak of `1000` server requests before getting a shadow ban.
Plus, the IP get tracked so using the bot for multiple profiles is not really a good idea.

I experienced pages with general error and specific errors like "actions are limited", so we should plan an exception for error like shadow_ban ( checking if exists the modal with some regex like "actions limited") 
I'll save some errs to share 'em w/ u.
Let's keep in touch.

**Comment by gerfra** [comment]
The party is over, the queries have been drastically reduced, the only solution is to make lists using f.ke accounts .... and use the real account only for the minimum necessary.

**Comment by azmankristjan** [comment]
Does following people still work for you? I have account with 10k and around 40k people reached every week, but I get action block after following 2 people.

**Comment by azmankristjan** [comment]
> The party is over, the queries have been drastically reduced, the only solution is to make lists using f.ke accounts .... and use the real account only for the minimum necessary.

Does following people still work for you? I have account with 10k and around 40k people reached every week, but I get action block after following 2 people.
