### ISSUE TITLE
--> Not commented

### ISSUE THREAD

**Issue by TRiXXER76** [InstaPy/InstaPy#5297]
```
INFO [2020-01-22 01:12:52] [x]  Location: b'Tampa, Florida'
INFO [2020-01-22 01:12:54] [x]  --> Image Liked!
INFO [2020-01-22 01:12:57] [x]  --> Not commented
INFO [2020-01-22 01:12:58] [x]  -------------
INFO [2020-01-22 01:12:58] [x]  --> Given amount not fullfilled, image pool reached its end

INFO [2020-01-22 01:12:58] [x]  User: b'joe.wilsons'
INFO [2020-01-22 01:12:58] [x]  Liked: 1
INFO [2020-01-22 01:12:58] [x]  Already Liked: 1
INFO [2020-01-22 01:12:58] [x]  Commented: 0
INFO [2020-01-22 01:12:58] [x]  Inappropriate: 0
INFO [2020-01-22 01:12:58] [x]  Not valid users: 0
```

Hey I know Instagram has changed its HTML and I applied a fix to the xpath_compile.py and it´s liking pictures now but it never comments. Comments are set to 100 percent in quickstart.py... it´s everytime just printing "--> Not commented" But comment is set to true in my quickstart.py :/

Does someone maybe has an Idea ?

Greetings Lukas

**Comment by Abdulsamipy** [comment]
checkout the following issue 

https://github.com/timgrossmann/InstaPy/issues/5289

**Comment by ronmara** [comment]
PR #5296
