### ISSUE TITLE
 Couldn't follow 'Username'! ~user is inaccessible

### ISSUE THREAD

**Issue by Abdulsamipy** [InstaPy/InstaPy#5298]
## Expected Behavior
follow user
## Current Behavior
 Couldn't follow 'user'! ~user is inaccessible
## Possible Solution (optional)
instagram has changed it's HTML .. can check that 
## InstaPy configuration

` # general settings

    session.set_relationship_bounds(enabled=True,
                 potency_ratio=None,
                  delimit_by_numbers=True,
                   max_followers=2000000,
                    max_following=10000,
                     min_followers=10,
                      min_following=10)
    session.set_user_interact(amount=2, randomize=True, percentage=100,
    media='Photo')
    session.set_do_follow(enabled=True, percentage=100)
    time.sleep(30)
    session.set_do_like(enabled=True, percentage=100)
    session.set_comments(["Your work is rockin @{}", "Well done @{} :muscle:", "Your posts are excellent :thumbsup: ", "What a really nice photo, great job! @{}"])
    session.set_do_comment(enabled=True, percentage=100)
    session.set_user_interact(amount=2, randomize=True, percentage=100,
    media='Photo')

    # activity

    session.interact_user_followers(['pewdiepie'],
    amount=10, randomize=True)
    session.follow_user_followers(['pewdiepie'],
    amount=10, randomize=True, interact=True)
    session.unfollow_users(amount=100, nonFollowers=True, style="RANDOM",
    unfollow_after=42*60*60, sleep_delay=30)
    session.like_by_tags(['fashion', 'style', 'consciousfashion', 'fashioneveryday', 'lookoftheday', 'womensfashionfinds', 'fashiontech', 'whatiwore'], amount=10)
    time.sleep(20)`

**Comment by Abdulsamipy** [comment]
can you guys fix this issue too? 

https://github.com/timgrossmann/InstaPy/pull/5296

**Comment by siddhantchimankar** [comment]
The issue still persists.

**Comment by ghost** [comment]
+1 Issue still persists, running version 0.6.8

**Comment by romain-bsn** [comment]
I have the same issue can anyone help ?

**Comment by AminZibayi** [comment]
@TheFakeWater check #5526

**Comment by AbdelazizGuendez** [comment]
I have the same issue guys...
I really love this tool, I'm just sad that every problem solved brings a new one...

**Comment by metapodcod** [comment]
I have the same issue guys...
I really love this tool, I'm just sad that every problem solved brings a new one...  @uluQulu  @timgrossmann

**Comment by avinash-550** [comment]
In xpath_compile.py

Adding a div before button worked for me!

Update it like following:
```
xpath["get_buttons_from_dialog"] = {
    "follow_button": "//div/button[text()='Follow']",
    "unfollow_button": "//div/button[text() = 'Following']",
}
```

**Comment by HARSHITAGUPTA123** [comment]
@Viwarrior this has worked for me. Thank you.

**Comment by rexonat** [comment]
Got the same issue - tried the fix and it doesnt work

**Comment by natem824** [comment]
Not sure why but when I switched from Sublime Text to Notepad++I started to get the error.
Now switched back to edit the text in Sublime Text and it works again :)

**Comment by rexonat** [comment]
That's so weird - I've been using sublime and not switched!

Maybe there's some kind of formatting error on there. Going to try again when I get some time off - thanks for the heads up 🙂

Kind Regards,
Susanna
________________________________

**Comment by tomnewg** [comment]
I started to get this error message 3-4 days ago. It only happens when trying to follow. Unfollowing is still working.
I tried @Viwarrior solution but unfortunately didn't work for me. Did Instagram change anything in terms of where the follow button is located? Any other idea/solution that I could try?

Many thanks for your help

**Comment by sundayz-hunter** [comment]
HI, 

I have the same problem since two day. 

Adding a div before button not worked for me. 

Thanks in advance if anyone have another tips for that !

**Comment by danielcasanova12** [comment]
did anyone find a solution??
the above codes didn't work for me
same error : Couldn't follow 'search_user'! ~user is inaccessible
