### ISSUE TITLE
get_links_for_username results in get_links generating error: link_elems error local variable 'post_href' referenced before assignment

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5299]
## Expected Behavior
Links identified and iterated

## Current Behavior

> link_elems error local variable 'post_href' referenced before assignment

I have isolated to the following line of code:

`link_elems = element.find_elements_by_xpath('//a[starts-with(@href, "/p/")]')
`
I have disabled Headless mode and can see that the correct page is being navigated to however the links to media are not being populated.

## InstaPy configuration
```
  session.set_do_comment(enabled=True, percentage=10)
  session.set_user_interact(amount=1, randomize=True, percentage=40, media='Photo')
  session.set_do_like(enabled=True, percentage=50)

```

**Comment by ComicBit** [comment]
So what was the solution to the problem?
