### ISSUE TITLE
Add emoji support

### ISSUE THREAD

**Issue by apertureless** [InstaPy/InstaPy#53]
🙏🏻 Emoji support for comments would be great.
Right now it's breaking because of the `send_key()` event which does not recognize the emojis and break.

**Comment by ToJen** [comment]
How are you passing the emojis?

**Comment by apertureless** [comment]
Simply in the comments array.

```python
set_comments(['Cool!', ' ✌️', 'Nice!'])\
```

**Comment by ToJen** [comment]
DId you try the unicodes in the `assets` folder?

**Comment by apertureless** [comment]
Nope, I will try to pass the unicodes directly.

**Comment by ToJen** [comment]
Cool

**Comment by timgrossmann** [comment]
@apertureless Yes, that are the only emojis supported by now...

**Comment by timgrossmann** [comment]
Also look at #2
