### ISSUE TITLE
User customizable delays

### ISSUE THREAD

**Issue by paunocu69** [InstaPy/InstaPy#530]
Hello everyone,

Today I wanted to run a quick demonstration to my clients and the long delays was a pain in the ass.
I know it's useful to avoid being banned and shit but sometimes we just need to test or to show the thing working and we will have to wait too long for it.

My idea is to have something like a method called set_delay_reduction so that we can set a percentage to reduce every sleep in the bot.
This would really make my weekend if implemented

I'm willing to pay for this to whoever comes with a solution

**Comment by sojan-official** [comment]
InstaPy has option for passing `page_delay` as a param. you can reduce the default 25 sec delay using that.

`session = InstaPy(username='username', password='password', page_delay=5)`

**Comment by paunocu69** [comment]
This is not the delay I've meant. The one you've said is relative to the time the browser will wait to least I think.
The one I'm asking for is relative to the sleeps

**Comment by ahmadudin** [comment]
@paunocu69 good idea

**Comment by converge** [comment]
now, follow_user_follower, follow_user_following and unfollow_user has this option sleep_delay.
