### ISSUE TITLE
Hide Selenium Extension: Error

### ISSUE THREAD

**Issue by Sinceless030** [InstaPy/InstaPy#5304]
Hello Guys ... why i become every time the error :::   
Hide Selenium Extension : error ..

any solution here?

Requirement already satisfied: selenium in c:\program files\python38\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\program files\python38\lib\site-packages (from selenium) (1.25.8)

when I create a .py file with :: 

from selenium import webdriver

browser = webdriver.Firefox()
browser.get('http://seleniumhq.org/%27)

the browser also opens and everything is fine, but somehow not with the instapy

[geckodriver.log](https://github.com/timgrossmann/InstaPy/files/4114296/geckodriver.log)

**Comment by Xuij** [comment]
Same error, wondering what's happening here.

**Comment by Cordycodes** [comment]
I'm having the same problem. Any updates?

**Comment by dyrgutt** [comment]
Yeah, and here as well

**Comment by fighterii** [comment]
Me too

**Comment by gvmturl** [comment]
Same here. 
Is the cause of that shows Instagram page working on selenium?
I m new on it. 

Thank you guys.

**Comment by retroworks-main** [comment]
Same problem :(

**Comment by TRiXXER76** [comment]
Same Problem, got a 7 Day Ban now XD Is it maybe a compatibility problem between a Firefox Version and the Selenium Version ? Maybe we must downgrade to a different Version of Firefox or Wait for an Selenium Update ? Or is instapy "faulty" in some way ?

I tried an older Firefox Version and the Selenium Error was away, but now instapy cant open the comment section so -> not commented because he didnt find the comment button. So Older Firefox Version results in no comments and the newest Version of Firefox results in a SoftBan and a 7 Day Ban :/

**Comment by TRiXXER76** [comment]
So I actually read this:

> The Problem
The #1 problem that people complain about is that their Firefox Driver doesn’t work with Selenium 3.0. I get this question about 72 times per day. Let me help.
The Selenium Webdriver team released Selenium 3.0. However, the Mozilla team is making changes to the Firefox architecture to support the in built capabilities for Selenium Webdriver. Therefore, working with the latest versions of Selenium Webdriver and Firefox is going to cause you some issues until the Firefox team finishes implementing Gecko Driver. By the way, you won’t be using Firefox driver any more.
The Solution
If you are starting to use Selenium Webdriver, your easiest route is to start by using Chrome Driver. You can use the latest version of Selenium and the latest version of Chrome Driver. Don’t touch Gecko Driver (replacement of FirefoxDriver) until it is more mature. Otherwise, you’re bound to cause yourself problems.

So my Question now, sorry its a little bit off topic maybe, but maybe some people have the same Question now... I have a Code Line in my instapy quickstart.py Where I define where the Geckodriver for Firefox is located on my PC, can I just add the chromedriver instead of the Geckodriver path ? And Do I need something else to use instapy with Chrome ?

Greetings Lukas

**Comment by katiachumakova** [comment]
How would we go about using Chrome? I am new to Instapy and getting banned, really love the project though and would like to find a solution

**Comment by gvmturl** [comment]
Any solution for that? 

That error results on softban #5311

This error happens on Windows...

Please guys....

@timgrossmann

**Comment by fighterii** [comment]
Anyone interested, should check this post:
https://intoli.com/blog/not-possible-to-block-chrome-headless/

As far as i can see, the created [firefox extension ](https://github.com/timgrossmann/InstaPy/blob/master/instapy/firefox_extension/content.js) covers the majority of the proposed tests of the blog article (and more)..

The quickcheck after starting the script then just checks for the `navigator.webdriver` property.

So I see two possible solutions:
1. Fix the firefox extension, that it does again what it should do
2. Port the code, the firefox extension injects through javascript to Chrome Browser

**Comment by fighterii** [comment]
Could this be related to add-on signing? https://stackoverflow.com/questions/31952727/how-can-i-disable-signature-checking-for-firefox-add-ons

Couldn't dig into this any further yet...

**Comment by azmankristjan** [comment]
> Same Problem, got a 7 Day Ban now XD Is it maybe a compatibility problem between a Firefox Version and the Selenium Version ? Maybe we must downgrade to a different Version of Firefox or Wait for an Selenium Update ? Or is instapy "faulty" in some way ?
> 
> I tried an older Firefox Version and the Selenium Error was away, but now instapy cant open the comment section so -> not commented because he didnt find the comment button. So Older Firefox Version results in no comments and the newest Version of Firefox results in a SoftBan and a 7 Day Ban :/

Hi 
Which version of Firefox and Selenium are you using? Does follow/unfollow still work? I downgraded both of them and I still get action blocked when trying to follow and unfollow people.
Thanks and best regards.

**Comment by maxbigl** [comment]
Same issue here. The bot is superbly complex, but instagram is catching up and soft banning because of this issue.
How can we use Chrome instead of Firefox @timgrossmann ? Or bypass this issue another way?

**Comment by TheKillber** [comment]
Same error here, i tried everything. Get insta-ban every time i turn it on.

**Comment by fegomess** [comment]
As soon as run instapy on my account, i get soft banned from it. I used to use instapy a lot two years ago, liking more then 1000 photos, commenting hundreds of times, following and unfollowing 400 for each action, but now i gave up. The number of actions i can do before i get soft banned is similar to a 1-2min of doing it myself.

**Comment by fighterii** [comment]
Okay: I digged into it a little bit.
The problem seems to be with the arrive function within the firefox extension. For some reason, the custom script from [instapy/firefox_extension/content.js ](https://github.com/timgrossmann/InstaPy/blob/master/instapy/firefox_extension/content.js) is not inserted into the `<head>` section of a page.

I modified:

```
 document.arrive('head', () => {
   var script = document.createElement('script');
   script.innerHTML = customScript;
   script.type = 'text/javascript';
   document.head.insertBefore(script, document.head.children[0]);
 });
```

to 

```
let head = document.getElementsByTagName("head")[0];
var script = document.createElement( 'script' );
script.textContent = customScript;
script.type = 'text/javascript'; 

head.insertBefore( script, head.firstChild );
```

Now i see that the customScript is inserted into the page when instagram loads. I assume this has to be optimized to inject it as early as possible into the DOM. Guess this is the main idea why the arrive code is used. But somethings broken here, so someone has to optimise / fix the insertion code again :) @converge , @breuerfelix , @timgrossmann : Any ideas on that?

**Comment by breuerfelix** [comment]
i wrote the extension back in the days and then the arrive function was the only event i was able to listen to that was firing at the correct time.

if this approach is working, please submit a pull request and it would be awesome if some other people could test this out if this really works all the time (also when switching sites / reloading the current site)

**Comment by Rob192** [comment]
Hello, I had the same issue here so I tried the solution proposed by @fighterii on my installation and it did remove the "Hide Selenium Extension" error. However I am stuck with direct soft ban as soon as I try to like a post.

**Comment by intothevoid** [comment]
Tried the solution by @fighterii the hide selenium extension error went away, but I am still facing the issue when I try to get likers of a post, using function "instapy.commenters_util.users_liked", I get a list containing - ['51 MINUTES AGO', '7 likes', 'myusername'] which doesn't make sense.

**Comment by Abdulsamipy** [comment]
so i tried @fighterii solution and got `Hide Selenium Extension: ok` `window.navigator.webdriver response: False` but im still getting the action block and before instapy gets the post it also gives 
`link_elems error local variable 'post_href' referenced before assignment` does anyone know how to fix it?

**Comment by azmankristjan** [comment]
so i tried @fighterii   solution but it doesn't work for me i still get  Hide Selenium Extension: error
I downgraded Firefox to version 67.0 and now the results are  

> Hide Selenium Extension: ok 
> window.navigator.webdriver response: False

I still get Action blocked sometimes. 
Is deleting cookie file a good practice or simply longing in from fresh every time i run Instapy?

**Comment by jinayG** [comment]
It dosent work for me.

**Comment by franori** [comment]
doesn't worked for me.. any updates on this?

**Comment by Abdulsamipy** [comment]
Please delete .pkl file

**Comment by olishingerz** [comment]
Getting the same issue, have tried all of the solutions above and even installed firefox version 67.0. Any more ideas?

**Comment by rugge89lau** [comment]
same issue here

**Comment by Strannik74** [comment]
Helped on Kali Linux
Removed from all firefox directories. Installed from the repository firefox-esr. The error is gone
WARNING [2020-05-09 00:06:16] [*******_******]  - Hide Selenium Extension: error
INFO [2020-05-09 00:28:55] [*******_******]  - Hide Selenium Extension: ok

**Comment by rugge89lau** [comment]
> Helped on Kali Linux
> Removed from all firefox directories. Installed from the repository firefox-esr. The error is gone
> WARNING [2020-05-09 00:06:16] [_******_******] - Hide Selenium Extension: error INFO [2020-05-09 00:28:55] [_******_******] - Hide Selenium Extension: ok

please be more clear. what I have to do?

**Comment by Strannik74** [comment]
Remove firefox completely. Install firefox 68.8

**Comment by sayedsoft** [comment]
> Remove firefox completely. Install firefox 68.8

it's worked thank you

**Comment by rugge89lau** [comment]
> Remove firefox completely. Install firefox 68.8

I just install the new version of firefox

**Comment by sayedsoft** [comment]
> > Remove firefox completely. Install firefox 68.8
> 
> I just install the new version of firefox

if you use ubuntu you must install firefox 68.8

**Comment by rugge89lau** [comment]
i have windows

> > > Remove firefox completely. Install firefox 68.8
> > 
> > 
> > I just install the new version of firefox
> 
> if you use ubuntu you must install firefox 68.8

**Comment by rugge89lau** [comment]
Oh! i installed 68.0 and it work, sorry! and thanks

**Comment by ediziks** [comment]
I've faced the same issue a couple hours ago and then, found an alternative way to hide selenium webdriver on Firefox. To do that, some preferences on Firefox should be added in browser.py file.
You can try to extend your code with the script between ADDED tags -it's under the set_selenium_local_session function- to hide selenium and, also to change the browser platform to iPhone. Another platform might be needed if you use different user agents.

This setting is working on me for now but not sure if it's a temporary solution or not. So, let me know about the results on you.

```
    # mute audio while watching stories
    firefox_profile.set_preference("media.volume_scale", "0.0")

    # ADDED
    firefox_profile.set_preference('dom.webdriver.enabled', False)
    firefox_profile.set_preference('useAutomationExtension', False)
    firefox_profile.set_preference('general.platform.override', 'iPhone')
    firefox_profile.update_preferences()
    # ADDED

    # prefer user path before downloaded one
    driver_path = geckodriver_path or get_geckodriver()
    browser = webdriver.Firefox(
        firefox_profile=firefox_profile,
        executable_path=driver_path,
        options=firefox_options)
```

**Comment by Strannik74** [comment]
Good evening!
Error
Hide selenium extension: error
It helped me!
Windows 7 remove Firefox. Install Firefox 68.0b3.
Hide selenium extension: ok

**Comment by fabiuhp** [comment]
> > > Remove firefox completely. Install firefox 68.8
> > 
> > 
> > I just install the new version of firefox
> 
> if you use ubuntu you must install firefox 68.8

guy, i`m trying to install firefox 68.8 but i`m having some issues. could you help?

**Comment by powermeza** [comment]
> > > > Remove firefox completely. Install firefox 68.8
> > > 
> > > 
> > > I just install the new version of firefox
> > 
> > 
> > if you use ubuntu you must install firefox 68.8
> 
> guy, i`m trying to install firefox 68.8 but i`m having some issues. could you help?

What version of Ubuntu are you using? There are only a few versions of firefox available... try running:

$ snap info firefox 

and it will tell you what you can install via:

  $ sudo apt-get install firefox

**Comment by dipiana** [comment]
> Okay: I digged into it a little bit.
> The problem seems to be with the arrive function within the firefox extension. For some reason, the custom script from [instapy/firefox_extension/content.js ](https://github.com/timgrossmann/InstaPy/blob/master/instapy/firefox_extension/content.js) is not inserted into the `<head>` section of a page.
> 
> I modified:
> 
> ```
>  document.arrive('head', () => {
>    var script = document.createElement('script');
>    script.innerHTML = customScript;
>    script.type = 'text/javascript';
>    document.head.insertBefore(script, document.head.children[0]);
>  });
> ```
> 
> to
> 
> ```
> let head = document.getElementsByTagName("head")[0];
> var script = document.createElement( 'script' );
> script.textContent = customScript;
> script.type = 'text/javascript'; 
> 
> head.insertBefore( script, head.firstChild );
> ```
> 
> Now i see that the customScript is inserted into the page when instagram loads. I assume this has to be optimized to inject it as early as possible into the DOM. Guess this is the main idea why the arrive code is used. But somethings broken here, so someone has to optimise / fix the insertion code again :) @converge , @breuerfelix , @timgrossmann : Any ideas on that?

Worked for me. Why is it not part of the latest release?

**Comment by fohbo** [comment]
Where do I have to change this (/content.js ?). Is it part of Firefox? I could not find it there. 

I have different start ups. I'd say 90% I get the error and 10% a OK regarding (Hide Selenium Extension: error).

**Comment by pherde** [comment]
> Where do I have to change this (/content.js ?). Is it part of Firefox? I could not find it there.
> 
> I have different start ups. I'd say 90% I get the error and 10% a OK regarding (Hide Selenium Extension: error).

Search in your home path: find /home/your_user/ -name "content.js"
My return: ~/anaconda3/lib/python3.7/site-packages/instapy/firefox_extension/content.js

**Comment by agloks** [comment]
@eemektas I've tried your solution using the version 77.0.1 of firefox at ArcoLinux and did work well with me, thanks.

**Comment by pherde** [comment]
> @eemektas I've tried your solution using the version 77.0.1 of firefox at ArcoLinux and did work well with me, thanks.

Same here, with this lines, works!! (arch, ff 77.0.1, instapy 0.6.9)

**Comment by breuerfelix** [comment]
anybody wants to do a PR with these changes ? :)

would love to merge these !

**Comment by ursetup** [comment]
Hello I Installed Firefox 67.0.0. and it still doesn't work. Anyone any tips? I also changed the code in content.js according to the comments here

**Comment by httsp0werz** [comment]
Good time of day to you gentlemans!

Tried just everything listed here on Windows 10, Windows 7, Ubuntu 16LTS Desktop, Ubuntu 16LTS Server, and latest Kali release.

Tried to downgrade InstaPy too, but with no any progress.

And guess what? Hide selenium: error.
Tried a lot of firefox releases on every system listed before.
Any suggestions?

Regards,
Max

**Comment by gdefagot** [comment]
Same problem here on Mac. Tried with firefox 68.8, 68.10, and also changing the file `instapy/firefox_extension/content.js`.

Still showing Hide Selenium Extension: error

**Comment by mister-vio** [comment]
For everyone who still have this problem.
I found this solution, and it works for me
:
take the login_util.py file from the 0.6.8 version and replace with yours

**Comment by gvmturl** [comment]
https://github.com/alexal1/Insomniac

**Comment by articutis** [comment]
> I've faced the same issue a couple hours ago and then, found an alternative way to hide selenium webdriver on Firefox. To do that, some preferences on Firefox should be added in browser.py file.
> You can try to extend your code with the script between ADDED tags -it's under the set_selenium_local_session function- to hide selenium and, also to change the browser platform to iPhone. Another platform might be needed if you use different user agents.
> 
> This setting is working on me for now but not sure if it's a temporary solution or not. So, let me know about the results on you.
> 
> ```
>     # mute audio while watching stories
>     firefox_profile.set_preference("media.volume_scale", "0.0")
> 
>     # ADDED
>     firefox_profile.set_preference('dom.webdriver.enabled', False)
>     firefox_profile.set_preference('useAutomationExtension', False)
>     firefox_profile.set_preference('general.platform.override', 'iPhone')
>     firefox_profile.update_preferences()
>     # ADDED
> 
>     # prefer user path before downloaded one
>     driver_path = geckodriver_path or get_geckodriver()
>     browser = webdriver.Firefox(
>         firefox_profile=firefox_profile,
>         executable_path=driver_path,
>         options=firefox_options)
> ```

Worked, thanks!

**Comment by fauzi-ar** [comment]
Adding these lines in browser.py, as per @eemektas suggestion:

```
firefox_profile.set_preference('dom.webdriver.enabled', False)
firefox_profile.set_preference('useAutomationExtension', False)
firefox_profile.set_preference('general.platform.override', 'iPhone')
firefox_profile.update_preferences()
```

it works, thank you!

**Comment by FrancoisDeBellescize** [comment]
Seems to be fixed with InstaPy 0.6.10

**Comment by froehlicht** [comment]
> Seems to be fixed with InstaPy 0.6.10

I still get this Error with Version 0.6.13 (Ubuntu)

**Comment by pedromoto4** [comment]
Same here with 
    Ubuntu 18.04
    instapy 0.6.13

Question, if I format this machine which is the best linux extension and version to run InstaPy ?

Best Regards

**Comment by newborngeek** [comment]
This issue is here! 
Mac OS Big Sur ver 11.3.1
what to do?

**Comment by BrownRecluse** [comment]
MacOS 10.14.6
Instapy 0.6.13
Firefox 88.0.1

I did all the corrections and I'm still having issues.

**Comment by newborngeek** [comment]
> Helped on Kali Linux
> Removed from all firefox directories. Installed from the repository firefox-esr. The error is gone
> WARNING [2020-05-09 00:06:16] [_******_******] - Hide Selenium Extension: error INFO [2020-05-09 00:28:55] [_******_******] - Hide Selenium Extension: ok

This helps me.
Step1: Complete delete Firefox (with all files from your machine)
step2: download https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=osx&lang=en-US
Step3: install and enjoy "Hide Selenium Extension: ok"

**Comment by filiperivelli** [comment]
I solved this problem by instaling Firefox 87.

**Comment by BorisTheSlavKing** [comment]
Running 88.0.1 And still keep getting this error.

**Comment by duvide** [comment]
Get this error with Firefox 89.0 on Ubuntu 18.04 server

**Comment by pedinil** [comment]
hi i get same error what to do

**Comment by Serfentum** [comment]
Same problem

**Comment by elulcao** [comment]
This is a useful link "https://bugzilla.mozilla.org/show_bug.cgi?id=1632821"
where is explained why "navigator.webdriver" behave different now.
one WA is to use an old version of FF that doesn't have that bug fix.
