### ISSUE TITLE
How can I randomize amount?

### ISSUE THREAD

**Issue by Jorman** [InstaPy/InstaPy#5306]
Hi, I'm pretty new of this, and I'm also new on python, I understand some but I do a lot of error, so I always have to make a try.

Btw, to start slow I want to like only some images by tags, so my script is pretty standard, I only made some little modification to randomize some actions, here the script:
```
# imports
from instapy import InstaPy
from instapy import smart_run
from random import randint

# login credentials
insta_username = 'username'
insta_password = 'password'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  disable_image_load=False,
                  multi_logs=True,
                  want_check_browser=True,
                  headless_browser=False)

with smart_run(session):

  session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                                peak_likes_hourly=50,
                                peak_likes_daily=400,
                                peak_comments_hourly=21,
                                peak_comments_daily=150,
                                peak_follows_hourly=40,
                                peak_follows_daily=200,
                                peak_unfollows_hourly=35,
                                peak_unfollows_daily=402,
                                peak_server_calls_hourly=None,
                                peak_server_calls_daily=4700)

  """ Activity flow """		
  # general settings		
  session.set_mandatory_language(enabled=True, character_set=['LATIN'])
  session.set_dont_include(["dont_include_this_account"])
  session.set_dont_like(['this', 'that', '#andthis'])

  
  session.set_skip_users(skip_private=True,
                         skip_no_profile_pic=True,
                         no_profile_pic_percentage=100)

  # activity
  session.set_user_interact(amount=randint(1, 3), randomize=True, percentage=90)
  session.like_by_tags(["tag1", "tag2", "tag3", "tag4"],
                        amount=randint(3, 7),
                        interact=True,
                        randomize=True)

  #session.set_do_like(enabled=True, percentage=70)
```
So, I imported randint and I use it to generate a random number, 2 times, one about the interaction and one about the amount of likes.
My question: is right?
I mean each time the script try to generate a number between 1 and 3 and for each user only a random images from 3 to 7 is selected, am I right?

Because to me seems that all the time the script run the random number won't change during the run, for example for each tag I specified, let say 12 (9+3) photos and 1 interaction for each user.

My purpose is, for tag 1/n each time the photo to be liked is a different amount and the user interaction is another random value.

How can I use randint in a better way?

**Comment by fighterii** [comment]
Randint is converted to an integer once it is called, not every time the number is needed.

So in your example, as soon as the settings are fixed in this line:

`session.set_user_interact(amount=randint(1, 3), randomize=True, percentage=90)`
  
There is the random number 2 (for example) generated and passed to the set function... If you would like to have different numbers, you have to call this line multiple times. 

But actually set do like with percentage of 70 also can randomize with 70 %.. So even if you have fixed amount of 3 pictures, each picture individually is liked with a chance of 70% I guess..

**Comment by Jorman** [comment]
Thanks @fighterii for your reply.
I've only little knowledge about python, so the line is passed only one time.
The "problem" is maybe the with smart_run(session) ?

You right, with percentage setting I can set a kind of random inside the function itself
I'm trying to understand if is possible make a kind of loop, I already randomized the tags list, and now the tags are not inside the smart_run, basically is like the comments on default quickstart, so for each tag I want to search a new session with random images and interaction are used, some like:
```
randomTags = [
    'tag1',
    'tag2',
    'tag3',
    'tag4',
    'tag5',
    'tag6',
    'tagN'
   ]

tags = random.sample(randomTags, len(randomTags))

for i in tags:
  session.set_user_interact(amount=random.randint(1, 3), randomize=True, percentage=90)
  session.like_by_tags(i,
                        amount=random.randint(3, 7),
                        interact=True,
                        randomize=True)
```
Is only one idea and maybe is not a good one. Is possible to make it works in that way?
What do you think?
