### ISSUE TITLE
Automatically upload photos in a given folder periodically

### ISSUE THREAD

**Issue by paunocu69** [InstaPy/InstaPy#531]
It would be really useful to have something like a not to automatically upload photos in a given folder periodically

So in my mind I would put tons of dicpics I'm at folder and it would be uploaded daily or monthly or on the weekends.

I know it is not possible to upload using the web desktop client but as for right now I'm using the smartphone website just had to change the thing to iphones

**Comment by timgrossmann** [comment]
@paunocu69 I think this would be an awesome feature.
Problem is that when switching to the mobile page, every single Elements query has to be adjusted. 
Tha is a lot of work as well.
But we can do some testing if it's possible to start there page as modibole and upload pictures

**Comment by ghost** [comment]
Hi, i think this is an interesting feature ... any news on this ?

**Comment by sionking** [comment]
Don't emulate web on mobile, this will rise bot
