### ISSUE TITLE
How to make app that just sends my android notifications randomly

### ISSUE THREAD

**Issue by potentowl** [InstaPy/InstaPy#5317]
This is a little off-topic but how could i make an app that just sends me notifications every 5 minutes as though people are texting me so i get that "ding" sound when I'm walking around so people think I'm getting communication when I'm not.

**Comment by gvmturl** [comment]
1 -  Install PyGame 

pip3 install pygame
or
pip install pygame 

2 - Creat a .py file using the code below
```
# Importing  PyGame
import pygame
import os

# Starting PyGame
pygame.init()

# Loading MP3 file and executing
if os.path.exists('mymusic.mp3'):
    pygame.mixer.music.load('mymusic.mp3')
    pygame.mixer.music.play()
    pygame.mixer.music.set_volume(1)

    clock = pygame.time.Clock()
    clock.tick(10)

    while pygame.mixer.music.get_busy():
        pygame.event.poll()
        clock.tick(10)
else:
    print('mymusic.mp3 isnt on script Python folder')
```

3 - change mymusic.mp3 to the sound u want play

4 -  Change 10 for time u want to repeat sound on  clock.tick(10) line.

Note: .py file and mymusic.mp3 must be at the same folder or you must write entire path on line 
if os.path.exists('mymusic.mp3'):

Eg: if os.path.exists('user/folder/mymusic.mp3'):



---------------------------------------------------------------------------------------------------------

**Dont u think that its easier you set alarm clock each 3min with sound u want?**
