### ISSUE TITLE
[Bug] Unable to login to Instagram! You will find more information in the logs above

### ISSUE THREAD

**Issue by Abdulsamipy** [InstaPy/InstaPy#5320]
## Expected Behavior
login into instagram
## Current Behavior
`InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Lenovo/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-02-05 01:08:43] []  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-02-05 01:08:43] []  -- Connection Checklist [1/3] (Internet Connection Status)
WARNING [2020-02-05 01:08:49] []  - Internet Connection Status: error
.........................................................................................................................
CRITICAL [2020-02-05 01:08:49] []  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2020-02-05 01:08:49] []  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2020-02-05 01:08:54] []  Sessional Live Report:
        |> No any statistics to show

[Session lasted 22.66 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-02-05 01:08:54] []  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo
`

**Comment by gvmturl** [comment]
Hello bro. http://ip4seeip.org/geoip seems to be offline.
to solve that you must go to login_util.py on instapy folder and comment
lines  165 to 208.

**Comment by Abdulsamipy** [comment]
> Hello bro. http://ip4seeip.org/geoip seems to be offline.
> to solve that you must go to login_util.py on instapy folder and comment
> lines 165 to 208.

Should I remove that or change it ?

**Comment by gvmturl** [comment]
Bro, i think its better comment each lines using #. like this:

```
#Try:
        #logger.info("-- Connection Checklist [1/3] (Internet Connection Status)")
        #browser.get("view-source:https://ip4.seeip.org/geoip")
        #pre = browser.find_element_by_tag_name("pre").text
        #current_ip_info = json.loads(pre)
        #if (
            #proxy_address is not None
            #and socket.gethostbyname(proxy_address) != current_ip_info["ip"]
        #):
            #logger.warn("- Proxy is set, but it's not working properly")
            #logger.warn(
                #'- Expected Proxy IP is "{}", and the current IP is "{}"'.format(
                    #proxy_address, current_ip_info["ip"]
                #)
            #)
            #logger.warn("- Try again or disable the Proxy Address on your setup")
            #logger.warn("- Aborting connection...")
            #return False
        #else:
            #logger.info("- Internet Connection Status: ok")
            #logger.info(
               #'- Current IP is "{}" and it\'s from "{}/{}"'.format(
                    #current_ip_info["ip"],
                    #current_ip_info["country"],
                    #current_ip_info["country_code"],
                #)
           # )
            #update_activity(
                #browser,
                #action=None,
                #state="Internet connection is ok",
                #logfolder=logfolder,
                #logger=logger,
            #)
    #except Exception:
       #logger.warn("- Internet Connection Status: error")
        #update_activity(
            #browser,
            #action=None,
           #state="There is an issue with the internet connection",
           #logfolder=logfolder,
           #logger=logger,
        #)
        #return False
```

Because if someone find a new solution for this, you can uncomment that... i think that there is no problem if u remove all lines... 


maybe u can comment multiple lines using 3 x " but i m not sure about that.

you can try it..

```
"""
try:
        logger.info("-- Connection Checklist [1/3] (Internet Connection Status)")
        browser.get("view-source:https://ip4.seeip.org/geoip")
        pre = browser.find_element_by_tag_name("pre").text
        current_ip_info = json.loads(pre)
        if (
            proxy_address is not None
            and socket.gethostbyname(proxy_address) != current_ip_info["ip"]
        ):
            logger.warn("- Proxy is set, but it's not working properly")
            logger.warn(
                '- Expected Proxy IP is "{}", and the current IP is "{}"'.format(
                    proxy_address, current_ip_info["ip"]
                )
            )
            logger.warn("- Try again or disable the Proxy Address on your setup")
            logger.warn("- Aborting connection...")
            return False
        else:
            logger.info("- Internet Connection Status: ok")
            logger.info(
                '- Current IP is "{}" and it\'s from "{}/{}"'.format(
                    current_ip_info["ip"],
                    current_ip_info["country"],
                    current_ip_info["country_code"],
                )
            )
            update_activity(
                browser,
                action=None,
                state="Internet connection is ok",
                logfolder=logfolder,
                logger=logger,
            )
    except Exception:
        logger.warn("- Internet Connection Status: error")
        update_activity(
            browser,
            action=None,
            state="There is an issue with the internet connection",
            logfolder=logfolder,
            logger=logger,
        )
        return False
"""
```

**Comment by Abdulsamipy** [comment]
Oh okay, ill give it a try :) thanks

**Comment by gvmturl** [comment]
> Oh okay, ill give it a try :) thanks

Nop bro, dont forget to tell us about your experience with this solution, it can help another users with the same problem,

If your problem is solved this topic must be closed.

**Comment by Abdulsamipy** [comment]
hey so .. i tried to replace the code you gave that didn't work 

`WARNING [2020-02-05 10:41:44] []  - Internet Connection Status: error
.........................................................................................................................
CRITICAL [2020-02-05 10:41:44] []  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2020-02-05 10:41:44] []  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.`


after that i tried removing the check connection code 1
and it was able to login but its giving following error 

`You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.`

**Comment by Abdulsamipy** [comment]
@gvmturl  the issue is solved :) thanks alot bro ..im closing it now
