### ISSUE TITLE
Can i run 2 scripts at the same time?

### ISSUE THREAD

**Issue by JuanSpada** [InstaPy/InstaPy#5321]
## Expected Behavior
run 2 scripts at the same time in windows with firefox
## Current Behavior
i can only run 1 script at the same time
## InstaPy configuration
No any custom workspace provided.       ~using existing..
InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Juan Spada/InstaPy"
Traceback (most recent call last):
  File ".\default.py", line 85, in <module>
    job()
  File ".\default.py", line 41, in job
    multi_logs=True)
  File "C:\Users\Juan Spada\Desktop\InstaPy\instapy\instapy.py", line 319, in __init__
    self.logger,
  File "C:\Users\Juan Spada\Desktop\InstaPy\instapy\browser.py", line 113, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\Users\Juan Spada\Desktop\InstaPy\instapy\browser.py", line 36, in get_geckodriver
    bin_path, sym_path = gdd.download_and_install()
  File "C:\Users\Juan Spada\AppData\Local\Programs\Python\Python37-32\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 196, in download_and_install
    shutil.copy2(src_file, dest_file)
  File "C:\Users\Juan Spada\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Juan Spada\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Juan Spada\\InstaPy\\assets\\geckodriver.exe'

**Comment by abdoljabbar** [comment]
if you want to use instapy for multiple account you can create multiple session:
session1 = InstaPy(params1)
session2 = InstaPy(params2)

**Comment by orhan-drsn** [comment]
But this will not work on the same time, or?
InstaPy will first finish session 1 and then starts with session 2.

**Comment by dirtyrick007** [comment]
Did you figure out how to run several scripts?

**Comment by AGregorc** [comment]
https://github.com/timgrossmann/InstaPy/issues/5403#issuecomment-615441526

**Comment by henriquedevelops** [comment]
> [#5403 (comment)](https://github.com/timgrossmann/InstaPy/issues/5403#issuecomment-615441526)

I don't get it :(
How do I create a new workspace? 
Could you please explain it in a little more detail?
I would be so thankful

**Comment by henriquedevelops** [comment]
> ## Expected Behavior
> run 2 scripts at the same time in windows with firefox
> 
> ## Current Behavior
> i can only run 1 script at the same time
> 
> ## Possible Solution (optional)
> ## InstaPy configuration
> No any custom workspace provided. ~using existing..
> InstaPy Version: 0.6.8
> ._. ._. ._. ._. ._. ._. ._. ._. ._. ._.
> Workspace in use: "C:/Users/Juan Spada/InstaPy"
> Traceback (most recent call last):
> File ".\default.py", line 85, in
> job()
> File ".\default.py", line 41, in job
> multi_logs=True)
> File "C:\Users\Juan Spada\Desktop\InstaPy\instapy\instapy.py", line 319, in **init**
> self.logger,
> File "C:\Users\Juan Spada\Desktop\InstaPy\instapy\browser.py", line 113, in set_selenium_local_session
> driver_path = geckodriver_path or get_geckodriver()
> File "C:\Users\Juan Spada\Desktop\InstaPy\instapy\browser.py", line 36, in get_geckodriver
> bin_path, sym_path = gdd.download_and_install()
> File "C:\Users\Juan Spada\AppData\Local\Programs\Python\Python37-32\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 196, in download_and_install
> shutil.copy2(src_file, dest_file)
> File "C:\Users\Juan Spada\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 266, in copy2
> copyfile(src, dst, follow_symlinks=follow_symlinks)
> File "C:\Users\Juan Spada\AppData\Local\Programs\Python\Python37-32\lib\shutil.py", line 121, in copyfile
> with open(dst, 'wb') as fdst:
> PermissionError: [Errno 13] Permission denied: 'C:\Users\Juan Spada\InstaPy\assets\geckodriver.exe'

Did you manage to solve this problem? I'm also trying
