### ISSUE TITLE
 session.grab_followers returns 0 followers

### ISSUE THREAD

**Issue by jkkorn** [InstaPy/InstaPy#5325]
Looked up the Instapy Documentation and gave the `.grab_followers` command a try.
https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#grab-followers-of-a-user

`### Grab followers

from instapy import InstaPy
from instapy import smart_run
import random

session = InstaPy(username='username', password='password')

popeye_followers = session.grab_followers(username="popeye", amount="full", live_match=True, store_locally=True)
print (popeye_followers)`

## Expected Behavior
Expected a print, or a file with a list of the popeye followers. Approximately 76K followers
## Current Behavior
 Instead got 0 followers:
![image](https://user-images.githubusercontent.com/320287/74291944-5ab9cf00-4d15-11ea-9283-645b3bc3d7ff.png)

**Comment by FahmiRR** [comment]
same thing happen, especially when grabbing 'big' account

**Comment by gilboz** [comment]
You need to use the `smart_run` context manager:

```python
from instapy import InstaPy, smart_run

session = InstaPy(username='username', password='password')

with smart_run(session):
	popeye_followers = session.grab_followers(username="popeye", amount="full", live_match=True, store_locally=True)

print(popeye_followers)
```

**Comment by AmirShahid** [comment]
you need to login first the code is:
session.login()
