### ISSUE TITLE
Actions blocked with Instapy 0.6.8. on Raspberry 4b 

### ISSUE THREAD

**Issue by Wernerlang** [InstaPy/InstaPy#5327]
Hi guys, my actions are blocked on Instagram, but I can still use apps like flume, the mobile phone and even the same firefox window the instapy uses. 

I am puzzled. 

Running Instapy 0.6.8. with a raspberry 4b since a couple of days. 

The very basic like quickstarter.py worked in the beginning, but now every action is blocked immediately. I am thinking maybe it could be possible to change the start up sequence and also the time set up (sleep etc.) or even launch the firefox browswer manually and then let Instapy do its work. 

What do you guys think?? Has anybody found a solution to the blocking of Instapy? Many thanks in advance and best.

**Comment by fighterii** [comment]
Guess it's all about #5304 . Are you seeing this error during your startup?
