### ISSUE TITLE
ImportError: No module named instapy

### ISSUE THREAD

**Issue by desmotta** [InstaPy/InstaPy#5328]
Hi everyone, i've found a lot of answer about my problem but nothing working..
So i post to you.

When i want to use the quickstart i have this error : 

Starting InstaPy with quickstart
====================
Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
ImportError: No module named instapy

Can you help me ?

I'm mac on os 10.14.6, pip 20.0.2 and Python 3.8

Thank's to all :)

**Comment by lukezielke** [comment]
You have to follow the instructions... Install instapy via pip

**Comment by desmotta** [comment]
> You have to follow the instructions... Install instapy via pip

This is what i've done..

**Comment by ryan0930** [comment]
Same problem

**Comment by ryan0930** [comment]
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography->python-telegram-bot>=12.0.0->instapy) (2.20)
Aruns-MacBook-Air:instapy-quickstart arunchandar$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 2, in <module>
    from instapy import InstaPy
ImportError: No module named instapy
