### ISSUE TITLE
Does instapy still work?

### ISSUE THREAD

**Issue by henriquedevelops** [InstaPy/InstaPy#5329]
I am a while without using instapy, heard that instagram blocked all sort of automation, is it true?

**Comment by poonasor** [comment]
yeah im asking the same question here, I have not touched in a few months the last time I've checked it was giving me a bunch of issues.. not sure if its been cleared up yet

**Comment by Archax** [comment]
> I am a while without using instapy, heard that instagram blocked all sort of automation, is it true?

no, isn't true... just use fresh version

**Comment by tjuzen** [comment]
Tried 2 months ago and got blocked, Im going to try again and I'll tell you if it works
