### ISSUE TITLE
Add user interaction to the like_by_feed feature

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#533]
> Adding interaction to the .like_by_feed feature
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=48199211)](https://www.bountysource.com/issues/48199211-add-user-interaction-to-the-like_by_feed-feature?utm_source=48199211&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Simply add support for the `.set_user_interact` to the `.like_by_feed` feature.

```python
session.set_user_interact(...)
session.like_by_feed(..., interact=True)
```

DoD:
- There is documentation added
- There is an example in examples.py
- The feature takes into account the settings from `.set_user_interact`

**Comment by timgrossmann** [comment]
@vitormvasc

**Comment by AbdulABHILASHA** [comment]
Can I DO IT? I WANTR TO

**Comment by AbdulABHILASHA** [comment]
wow you made me official Contributor!

**Comment by AbdulABHILASHA** [comment]
wait, does #495 fixes it1?

**Comment by timgrossmann** [comment]
@AbdulABHILASHA @vitormvasc Has already implemented this, he only needed an issue

**Comment by AbdulABHILASHA** [comment]
but he didnt upload it yet amiright?

**Comment by timgrossmann** [comment]
@AbdulABHILASHA Yes

**Comment by AbdulABHILASHA** [comment]
i think i can do it then?

**Comment by timgrossmann** [comment]
@AbdulABHILASHA Well, he'll upload it tomorrow. There is no need to redo this... He's already finished

**Comment by AbdulABHILASHA** [comment]
but i can have it done by today

**Comment by timgrossmann** [comment]
@AbdulABHILASHA Really, there is no need to implement this again

**Comment by vitormvasc** [comment]
#541

**Comment by ashu-22** [comment]
Are the issue is still open or closed.
