### ISSUE TITLE
Follow/unfollow Tips and Tricks. Using Chrome?

### ISSUE THREAD

**Issue by azmankristjan** [InstaPy/InstaPy#5330]
Hi

I’ve been using follow/unfollow method for a month on 10k account with photos reaching 40k people a week and it worked the best. Now for two months I can’t follow anyone using Instapy but can follow manually in the browser or phone without getting blocked. I get action blocked after following 2 accounts.

I heard that is happening because of Hide Selenium Extension: Error  [this thing](https://github.com/timgrossmann/InstaPy/issues/5304) I tried downgrading Firefox and it shows Hide Selenium Extension: Ok , but the problem with action block is still there.

Would switching to Chrome fix the issue. I’m new to this thing so I don’t know how to do it. Can someone help with this?

I’m interested if anyone is successfully using follow/unfollow method and what are their experiences? Did you get action blocked and if you did how did you get rid of it? Any tips & tricks?

Thank you and best regards.

## InstaPy configuration

Instapay: 0.6.8
Selenium:  3.141

**Comment by jinayG** [comment]
The issue still exists
