### ISSUE TITLE
ModuleNotFoundError: No module named 'instapy'

### ISSUE THREAD

**Issue by gagannagarm** [InstaPy/InstaPy#5332]
Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
ModuleNotFoundError: No module named 'instapy'

Hi I am facing this issue, can anyone please resolve this issue?
![image](https://user-images.githubusercontent.com/61291257/74967975-09f65480-5440-11ea-8a1b-14fd8c1809ab.png)

**Comment by lukezielke** [comment]
This means you don't have installed instapy. Install it via pip

**Comment by m-cage** [comment]
As Luke commented, probably instapy is not installed. If this is not the case, you can read this article for other possible reasons: [ModuleNotFoundError](http://abcstudyguide.com/solution-modulenotfounderror-no-module-named/)

**Comment by gagannagarm** [comment]
> This means you don't have installed instapy. Install it via pip

Hi @lukezielke 

thanks for your response, can you please guide me, to install instapy step by step.

It will be a great help since I have checked lots of articles, it's not working.

Thanks

**Comment by lukezielke** [comment]
If you are using python 2 run this command: 
`pip install instapy`
If you are using Python 3:
`pip3 install instapy`

If you haven't installed pip install it by running the following in your terminal:

```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
```

If this doesn't help refer to the Website @m-cage sent.

Hope it helps
