### ISSUE TITLE
ERROR: clarifai 2.6.2 has requirement configparser<4,>=3.5, but you'll have configparser 4.0.2 which is incompatible.

### ISSUE THREAD

**Issue by sgodo** [InstaPy/InstaPy#5334]
## Expected Behavior
The error comes during installation.
I tryed to fix it first with:
"python3 -m pip install clarifai --upgrade" 
does not works I tryed 
then:
"pip install configparser==3.5.0" 
but the insallation(install.sh) reinstalled (4.0.2) 
"Using cached configparser-4.0.2-py2.py3-none-any.whl (22 kB)"
and the same error comes again!
Can anyone help?

**Comment by Curioo** [comment]
im getting the same error.

**Comment by redpredator8** [comment]
Same here

**Comment by redpredator8** [comment]
https://github.com/timgrossmann/InstaPy/issues/5094
