### ISSUE TITLE
Problem detecting follow and unfollow buttons. User agent

### ISSUE THREAD

**Issue by ortegafernando** [InstaPy/InstaPy#5336]
Hi, I am using instapy from a fresh installation and Firefox.

I have found that I cant follow or unfollow users. It is not always, but almost all of the time.

I think it is because the photo attached. (in this case this user is try to be unfollow)

![Captura2](https://user-images.githubusercontent.com/8700791/75167660-fd1a7f00-5725-11ea-87bf-dc5e86b79879.PNG)

By default, instapy+firefox "simulates" and iPhone so we can see the image on the left. Message button + an "icon" button.

I have pause my instapy script and in the same firefox windows I have change it to iPad and I get the image on the right.

I dont know how to solve but we must do one of these:
a. change the detection function of follow/unfollow button
b. change the firefox session to use iPad or Pc as user agent.

I have check these user agents:
1. NO OK:
Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/18.1 Mobile/16B92 Safari/605.1.15

2. OK (i can see button text, i will try the script after writting this post)
Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0

Does anybody know what to do?

Thanks

**Comment by Level128** [comment]
I have noticed this as well. But I think I have found the main problem. InstaPy thinks I am already following or unfollowed the user which is wrong. The profiles that it fails on is when the user has NO POSTS (just as you pictured above). 

I do not know what changes under the hood cause the format to change and not allow InstaPy to correctly detect the follow buttons, but this is the issue.

**Comment by sebbyG2** [comment]
This occurs because of the box which appears after the follow with the Suggested users. The script is checking for no 'Follow', but there are because of these Suggested users.

I'm not sure how to fix this in the code though. Is someone looking into this?
