### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by gagannagarm** [InstaPy/InstaPy#5337]
Traceback (most recent call last):
  File "../quickstart.py", line 22, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 309, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 111, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Press any key to continue . . .

Hi Please help

**Comment by xerZV** [comment]
same here

**Comment by vihuarar** [comment]
Same problem...

**Comment by shafaypro** [comment]
@gagannagarm @xerZV @vihuarar 
You guys are missing two things.

1.  Mozilla should be installed in your local machines if you are using Windows download Mozilla
2. Secondly, You need to download specific drivers such as firefox geckodriver and chrome driver. to download those you need to do the following.

- GOTO [GECKODRIVERDOWNLOAD](https://github.com/mozilla/geckodriver/releases )
- Click on the specific version you have whether x32 or x64
- download that and after downloading you should continue to check using the code below whether the driver is downloaded or not.

```

from selenium import webdriver

browser = webdriver.Firefox(executable_path=r'COPYTHECOMPLETEDOWNLOADPATHOFGECKODRIVER\geckodriver.exe')
browser.get("https://www.google.com/")
print("I am on this website ::::: YOYO XOXO , ",browser.title)
```

After this, if the google opens up successful. continue with your Instapy code it will work :) 

The following codes work like a charm 
OPTIONAL.
```
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace
import passcodesboies

# Creating a workspace
set_workspace(path=None)  # currently there is not working path

# That was so difficult !
session = InstaPy(username='REPLACEHERE, password='REPLACEHERE')  # Creating an instagram session

with smart_run(session):
    # Smart run is responsible for the session usage
    # Tags to be followed  !

    session.like_by_tags(tags=["travel"])  # This will like the images with repect to tags
```

**Comment by DunkinDonat** [comment]
@shafaypro which Version of FireFox are you using. Did you do some customisation at installation?

Does the geckodiver find Firefox automaticaly?

**Comment by shafaypro** [comment]
@DunkinDonat Sorry for the late reply,
I am using 75.0 FireFox Browser with 64 Bit. It did it automatically if in case this doesn't work you can do it manually in the session variable. You just need to replace the variable path in the InstaPy() Object declaration parameters 'geckodriver_path' be equal to your own downloaded geckodriver.exe :)

**Comment by dmsierra11** [comment]
> @gagannagarm @xerZV @vihuarar
> You guys are missing two things.
> 
>     1. Mozilla should be installed in your local machines if you are using Windows download Mozilla
> 
>     2. Secondly, You need to download specific drivers such as firefox geckodriver and chrome driver. to download those you need to do the following.
> 
> 
>     * GOTO [GECKODRIVERDOWNLOAD](https://github.com/mozilla/geckodriver/releases)
> 
>     * Click on the specific version you have whether x32 or x64
> 
>     * download that and after downloading you should continue to check using the code below whether the driver is downloaded or not.
> 
> 
> ```
> 
> from selenium import webdriver
> 
> browser = webdriver.Firefox(executable_path=r'COPYTHECOMPLETEDOWNLOADPATHOFGECKODRIVER\geckodriver.exe')
> browser.get("https://www.google.com/")
> print("I am on this website ::::: YOYO XOXO , ",browser.title)
> ```
> 
> After this, if the google opens up successful. continue with your Instapy code it will work :)
> 
> The following codes work like a charm
> OPTIONAL.
> 
> ```
> from instapy import InstaPy
> from instapy import smart_run
> from instapy import set_workspace
> import passcodesboies
> 
> # Creating a workspace
> set_workspace(path=None)  # currently there is not working path
> 
> # That was so difficult !
> session = InstaPy(username='REPLACEHERE, password='REPLACEHERE')  # Creating an instagram session
> 
> with smart_run(session):
>     # Smart run is responsible for the session usage
>     # Tags to be followed  !
> 
>     session.like_by_tags(tags=["travel"])  # This will like the images with repect to tags
> ```

I have two versions of Firefox installed because I need the other one for a different task. How would I know what version it's using?

**Comment by xerZV** [comment]
@dmsierra11 have now another problem - instant action block.
