### ISSUE TITLE
Failed to get followers count and the page isn't available! the link may be broken, or the page may have been removed

### ISSUE THREAD

**Issue by alansyue1020** [InstaPy/InstaPy#5339]
When I run my quickstart.py script, I recently got the error message like this:
```
Failed to get followers count of 'b'myUserName''  ~empty list
```
And the following script also got the message like:
```
INFO [2020-02-26 02:09:09] [myUserName]  Starting to follow user `Followers`..
INFO [2020-02-26 02:09:09] [myUserName]  User 'otherUserName' [1/1]
WARNING [2020-02-26 02:09:13] [myUserName]  The page isn't available!	~the link may be broken, or the page may have been removed...
INFO [2020-02-26 02:09:13] [myUserName]  Grabbed 0 usernames from 'otherUserName's `Followers` to do following
```
But the user account is not private and it is available.

And the following code is my script:
```
    bot.set_do_reply_to_comments(enabled=True, percentage=14)
    bot.set_comment_replies(replies=[u"😎😎😎", u"😁😁😁😁😁😁😁💪🏼", u"😋🎉", "😀🍬", u"😂😂😂👈🏼👏🏼👏🏼", u"🙂🙋🏼‍♂️🚀🎊🎊🎊", u"😁😁😁", u"😂",  u"🎉",  u"😎", u"🤓🤓🤓🤓🤓", u"👏🏼😉"],
                                media="Photo")
    bot.set_user_interact(amount=2,
                 percentage=70,
                  randomize=True,
                   media='Photo')
    bot.set_do_like(enabled=True, percentage=94)
    bot.set_skip_users(skip_private=True,
                       private_percentage=100,
                       skip_no_profile_pic=False,
                       no_profile_pic_percentage=100,
                       skip_business=True,
                       skip_non_business=False,
                       business_percentage=100)
    bot.follow_user_followers(follow_list, amount=1000, randomize=False)
    bot.follow_user_following(follow_list, amount=1000, randomize=False)
    bot.follow_likers(follow_list, photos_grab_amount = 2, follow_likers_per_photo = 3, randomize=True, sleep_delay=600, interact=True)    
    bot.follow_commenters(follow_list, amount=1000, daysold=365, max_pic = 100, sleep_delay=600, interact=False)
    bot.unfollow_users(amount=1000, nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)
    bot.interact_by_comments(usernames=follow_list, posts_amount=1000, comments_per_post=50, reply=True, interact=True, randomize=True, media="Photo")
    bot.interact_user_following(follow_list, amount=1000, randomize=True)
    bot.interact_user_following(follow_list, amount=1000, randomize=True)
    bot.end()
```
thanks for help!

**Comment by ninuki** [comment]
Same problem. Access with Browser on Instagram was not possible for 24h. App still possible.

Message InstaPy:
`Failed to get followers count of 'b'myUserName''  ~empty list`

**Comment by joaostorrer** [comment]
This message is because InstaPy can't find the followers count in the user profile, probably the actual page isn't the profile one or the user profile link is broken.

**Comment by fohbo** [comment]
I had the same problem and solved it.

What did not work: 
user name -> "youremail@hoster.xyz"
user name -> "@yourinstagramloginname"

What solved the problem:

user name -> "yourinstagramloginname"
The user name without the @ did the trick.

of course this is all fictional login credential.

**Comment by krisblarq** [comment]
I'm still getting the following errors.

INFO [2020-07-30 19:41:02] [oaks_furniture]  Failed to get followers count of 'b'lisafolawiyo''  ~empty list

**Comment by asvsfs** [comment]
Same problem here any resolution ?

**Comment by lucasrodes** [comment]
Was not getting this until today... Now my script is basically doing nothing because of this...

I tried using `headless_browser=False` and realized that whenever I attempted to enter a IG profile the following appeared:

![image](https://user-images.githubusercontent.com/18101289/90962054-5a14a900-e4ad-11ea-9120-aaf23177ef13.png)

Will wait for couple of days...

**Comment by mkhazan** [comment]
After a while I encounter Failed to get followers count error. Is there any solution?

**Comment by skiwlkr** [comment]
Same Problem. Already tried to limit stuff aggressively with the quota supervisor but didn't help

**Comment by jmaric** [comment]
same here... i have same problem... please help!

**Comment by 1991Sebastian** [comment]
same here

**Comment by Tr1pke** [comment]
Same here

**Comment by farshis** [comment]
> I had the same problem and solved it.
> 
> What did not work:
> user name -> "[youremail@hoster.xyz](mailto:youremail@hoster.xyz)"
> user name -> "@yourinstagramloginname"
> 
> What solved the problem:
> 
> user name -> "yourinstagramloginname"
> The user name without the @ did the trick.
> 
> of course this is all fictional login credential.

that helps me! thanks bro!

**Comment by opastorello** [comment]
> Was not getting this until today... Now my script is basically doing nothing because of this...
> 
> I tried using `headless_browser=False` and realized that whenever I attempted to enter a IG profile the following appeared:
> 
> ![image](https://user-images.githubusercontent.com/18101289/90962054-5a14a900-e4ad-11ea-9120-aaf23177ef13.png)
> 
> Will wait for couple of days...


same here
