### ISSUE TITLE
webdriver issues

### ISSUE THREAD

**Issue by potentowl** [InstaPy/InstaPy#5340]
File "quickstart.py", line 15, in <module>
    headless_browser=False)
  File "/home/penguin/instabot/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/home/penguin/instabot/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

**Comment by potentowl** [comment]
when i run "pip install instappy" i get these errors too --------------->
```
  WARNING: The script tqdm is installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script webdriverdownloader is installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts futurize and pasteurize are installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

**Comment by J3store** [comment]
hello @loopypanda  -- any solution for this? 
Im running on Ubuntu LInux

**Comment by J3store** [comment]
> File "quickstart.py", line 15, in
> headless_browser=False)
> File "/home/penguin/instabot/instapy/instapy.py", line 319, in **init**
> self.logger,
> File "/home/penguin/instabot/instapy/browser.py", line 114, in set_selenium_local_session
> options=firefox_options,
> File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in **init**
> keep_alive=True)
> File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

Any solution?
