### ISSUE TITLE
Import Error when running command python quickstart.py

### ISSUE THREAD

**Issue by RCAHaertlein** [InstaPy/InstaPy#5342]
## Expected Behavior
Runs the quickstart.py without errors

## Current Behavior
**I get following error importing Instapy**
ImportError: attempted relative import with no known parent package

**Path where instapy is installed**
`C:\Users\[username]\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy`

**Tracelog**
`Traceback (most recent call last):
  File "quickstart.py", line 2, in <module>
    from instapy import InstaPy
  File "C:\Users\[username]\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy\instapy.py", line 20, in <module>
    from . import __version__
ImportError: attempted relative import with no known parent package`

**Folder layout**
![image](https://user-images.githubusercontent.com/15014583/75425427-f61c8800-5942-11ea-96ed-a95d08602736.png)

**InstaPy quickstart configuration**
Just used the quickstart.py from 
https://github.com/InstaPy/instapy-quickstart/blob/master/quickstart.py

## Possible solution
I guess I have my quikstart.py in the wrong place. But have no clue where to place the quickstart.py elsewhere. Can anyone help me out?

**Comment by azmankristjan** [comment]
put it outside the instapy folder 
![Opomba 2020-02-28 082936](https://user-images.githubusercontent.com/46808587/75519926-a7372700-5a04-11ea-8a61-14d08923051d.jpg)

**Comment by RCAHaertlein** [comment]
> put it outside the instapy folder
> ![Opomba 2020-02-28 082936](https://user-images.githubusercontent.com/46808587/75519926-a7372700-5a04-11ea-8a61-14d08923051d.jpg)

Thanks!

**Comment by napuzba** [comment]
For more details about this exception, see [ImportError: attempted relative import with no known parent package](https://napuzba.com/a/import-error-relative-no-parent)
