### ISSUE TITLE
"Invalid Like Element!"

### ISSUE THREAD

**Issue by AnwarAhmedPSU** [InstaPy/InstaPy#5345]
For some reason its not liking any of the posts. Would anyone know why? Or has the liking stop working entirely.

**Comment by AnwarAhmedPSU** [comment]
Also, has story watching worked with anyone?

**Comment by Th0rGer** [comment]
yes got the message: INFO [2020-03-14 18:26:31] --> Invalid Like Element!

**Comment by Radman-1** [comment]
I just started having this same issue.   Uninstalled Instapy and re installed it with no luck.  Also I did try to find xpath to change the code but can't seem to locate it

**Comment by enjoipanda77** [comment]
> I just started having this same issue. Uninstalled Instapy and re installed it with no luck. Also I did try to find xpath to change the code but can't seem to locate it

I am having the exact same issue. I found xpath and changed the code but I still get the same error again and again. Are there multiple xpath files and I'm changing the wrong one or what?

**Comment by Radman-1** [comment]
I'm using two different machines and on one I cant find xpath.  Can someone help...searched in Appdata/local/programs/python/python38/lib/..... can't seem to find it
