### ISSUE TITLE
Running Instapy on PythonAnywhere - Selenium Error

### ISSUE THREAD

**Issue by olishingerz** [InstaPy/InstaPy#5349]
## Expected Behavior
I am trying to run InstaPy but I am receiving an error with selenium when running. Instapy is installed and the Selenium package is also installed in the location it is referencing. Is anyone able to help me please? I would be extremely appreciative. 
## Current Behavior
![image](https://user-images.githubusercontent.com/48222647/76200385-72d41f80-61e9-11ea-87b2-1cc9143a8968.png)

**Comment by Abdulsamipy** [comment]
getting the same problem when I'm scheduling it on windows task manager .. the bot is running fine when I start it manually

**Comment by hackrx** [comment]
I am also facing the same issue.Can somebody please us?

**Comment by Abdulsamipy** [comment]
@olishingerz try adding the drive to the path and a copy of driver inside the bot folder

**Comment by olishingerz** [comment]
@Abdulsamipy can we take a look at this issue together? Can I contact you externally please? I really could do with your help please

**Comment by hackrx** [comment]
@olishingerz Hey guys I solved that issue follow these steps to py script successfully.
1.Update your Firefox to current version.
2>Then download getcko driver according to the latest version.(You can google for it and download it.)
3.Add your getcko exe path location into the instapy file there u find its constructor , there is a variable named gitcko_path , add the exe file path to it.
4.enjoy ur problem will get solved

**Comment by hackrx** [comment]
Driver name is gecko

**Comment by Abdulsamipy** [comment]
@hackrx you can try to schedule the bot?  and check if its giving a selenium error

**Comment by hackrx** [comment]
Now  it is not giving an error but my Instagram account is blocked by Instagram.Now I can not able to perform any  activity eg like, follow 😭.So I suggest you to not run this script on your personal account

**Comment by olishingerz** [comment]
@hackrx  can I can I contact you externally please? I would love to get your help with fixing this

**Comment by hackrx** [comment]
Ya contact me on insta rajatgoyal86

**Comment by dampbossul** [comment]
Nu pot uita momentele frumoase petrecute impreuna si voi insista sa te caut
pana cand imi vei da un raspuns. Nu renunt asa usor la tine, la noi, te
vreau in viata mea si voi incerca sa iti demonstrez acest lucru pe cat de
mult pot
