### ISSUE TITLE
Cookie file not found, creating cookie... Login A/B test detected! Trying another string...

### ISSUE THREAD

**Issue by mrglenean** [InstaPy/InstaPy#5351]
Hi guys in both of my Macs I have the same issue:
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

I've tried the options I saw around here but nothing worked. I'm using the latest version of instapy with chromedriver.

Any help please? 

## Current Behavior
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

**Comment by avimehenwal** [comment]
:heavy_plus_sign:  :one: 
Hey, I have the same issue

```
Python 3.7.7
ubuntu linux
```

```
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...
```

**Comment by gridsome-user** [comment]
+1
I have the same issue

```
Python 2.7
Mac OS Sierra
```

**Comment by xerZV** [comment]
same here on rasp 3

**Comment by arthasisacat** [comment]
Same issue here! do we have a solution?
