### ISSUE TITLE
Not working when I launch using mac_start.command file

### ISSUE THREAD

**Issue by Tomburner** [InstaPy/InstaPy#5354]
When I launch InstaPy using mac_start.command it opens google and then instantly closes it and says: 
![Screen Shot 2020-03-11 at 4 32 13 PM](https://user-images.githubusercontent.com/60519907/76461226-e2970580-63b5-11ea-94f5-b6360945ceed.png)
any idea what is going wrong/how do I fix this?

**Comment by timmoh** [comment]
...ensure chromedriver is installed at /User/nicholaswalsh..."
