### ISSUE TITLE
Relationship bounds not applying to grab_users function 

### ISSUE THREAD

**Issue by imaccormick275** [InstaPy/InstaPy#5357]
## Expected Behavior
Relationship bounds apply to grab_users function - returns users that do not meet specified potency ration.

session.login()
session.set_relationship_bounds(enabled=True, potency_ratio=-1.5, delimit_by_numbers=False)
target_users = session.grab_following(username="testuser", amount=5, live_match=True, store_locally=True)
session.end()

## Current Behavior
Relationship bounds do not apply to grab users function: expecting potency ratio of -1.5.

## InstaPy configuration
instapy                   0.6.8                    pypi_0    pypi

**Comment by imaccormick275** [comment]
Not entirely sure if the relationship bounds should work with the grab_users function - or only works if you are actually interacting with an account in some way. I'd like to try and automate the finding of users that meet certain conditions - but no automate the interactions.

**Comment by mcmarshall** [comment]
@imaccormick275 Did you ever find a way to accomplish this? I am trying to do the same thing.
