### ISSUE TITLE
Unable to locate element: {"method":"xpath","selector":"//article//a[text()='Log in']"}

### ISSUE THREAD

**Issue by lucaob** [InstaPy/InstaPy#5359]
## Expected Behavior
Hi,
after a quite long  non-use period I started again Instapy, but I fout it is no longer working. I upgraded with pip but nothing changes: it is still not working.

Here you can find the output I receive. I also attach (as a .gz file) the file /tmp/20200314-181738.html as requested.

Help Please!

## Current Behavior
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-03-14 18:16:54] [MYUSERNAME]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20200314-181738.html
**********************************************************************

INFO [2020-03-14 18:17:38] [MYUSERNAME]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 47.08 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-03-14 18:17:38] [MYUSERNAME

]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "IGBisonte_2.py", line 29, in <module>
    with smart_run(session):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/pi/Projects/InstaPy/instapy/util.py", line 1602, in smart_run
    session.login()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 360, in login
    self.bypass_with_mobile):
  File "/home/pi/Projects/InstaPy/instapy/login_util.py", line 204, in login_user
    "//article//a[text()='Log in']")
  File "/home/pi/venv36/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/pi/venv36/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/pi/venv36/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/venv36/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//article//a[text()='Log in']"}
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)
[20200314-181738.html.gz](https://github.com/timgrossmann/InstaPy/files/4333094/20200314-181738.html.gz)

**Comment by imsquare** [comment]
I'm having this same issue. Same situation: I haven't used instapy for some time (probably 9 months), started back up, updated to 20.0.2, went to run an old program, got this message.

**Comment by imsquare** [comment]
FYI I tried the fix in PR #5252 but it seems that fix has already been implemented in the v20.0.2 and I'm still having this same issue.

**Comment by lucaob** [comment]
I have the last version of instapy, obtained via pip upgrade but I still have the same problem. Please help!

**Comment by SamuelePignone** [comment]
I finally found a solution!
Go to the file login_util.py in the instapy folder and do the following things:

- Around line 200: comment or delete code from login_elem to end of if

`
    '''
    login_elem = browser.find_element_by_xpath(
        "//article//a[text()='Log in']")

    if login_elem is not None:
        try:
            (ActionChains(browser)
             .move_to_element(login_elem)
             .click()
             .perform())
        except MoveTargetOutOfBoundsException:
            login_elem.click()

        # update server calls
        update_activity()
    '''
`
- Around line 265: change login_button with login_button = browser.find_element_by_xpath("//*[@id=\"react-root\"]/section/main/article/div[2]/div[1]/div/form/div[4]/button")

`
login_button = browser.find_element_by_xpath(
        "//*[@id=\"react-root\"]/section/main/article/div[2]/div[1]/div/form/div[4]/button")
`

You can file all the code of login_util.py here [https://pastebin.com/gfND9VQQ](url)

**Comment by lucaob** [comment]
It worked for me, thank you! But now I have the same error as in #5178 and I do not know how to solve it :-(
