### ISSUE TITLE
Instapy Quickstart Not Commented, Not Followed

### ISSUE THREAD

**Issue by balledictorian** [InstaPy/InstaPy#5367]
## Expected Behavior
Likes, Comments, Follows

## Current Behavior
Likes, Not Commented, Not Followed

## InstaPy configuration
from instapy import InstaPy

from instapy import smart_run

# login credentials

insta_username = '***************'

insta_password = '*************'

comments = ['Nice shot! @{}',

        'Sickkkkkk!',

        'That was insane :thumbsup:',

        'Just incredible :open_mouth:',

        'HOW???',

        'IMPOSSIBLE',

        'Looks awesome',

        'Teach me your ways @balledictorian',

        ':raised_hands: Sick!',

        'That was intense :muscle:',

        'Thats how its done']

# get an InstaPy session!

# set headless_browser=True to run InstaPy in the background

session = InstaPy(username=insta_username,

                  password=insta_password,

                  headless_browser=True)

with smart_run(session):

  """ Activity flow """

  # general settings

  session.set_dont_include(["friend1", "friend2", "friend3"])

  # activity

  session.like_by_tags(["fortnitepro", "fortnitenoob", "quickscope", "victory royale"], amount=50)

  # Joining Engagement Pods

  session.set_do_comment(enabled=True, percentage=35)

  session.set_comments(comments)

  session.join_pods(topic='sports', engagement_mode='no_comments')

**Comment by AbdelazizGuendez** [comment]
I have the same issue
