### ISSUE TITLE
Bypassing instagram bot detection

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5369]
I disabled these requests from Instagram:

- graph.instagram.com/logging_client_events
- www.instagram.com/ajax/bz
- www.facebook.com/ajax/bz
- www.instagram.com/logging/falco

and it works for bypassing the bot detection. problem is, instapy mistakes elements of the page as usernames now. It also pauses until i press Ctrl+C sometimes

## Expected Behavior
Doesn't detect other elements of pages as users.

## Current Behavior
Elements like "@username" "view all 30 comments" "MARCH 5" "21 others" are detected as users
```
opening likes

Scrolling finished

Got 6 likers shuffled randomly whom you can follow:
['iris.wallis', 'kinnunesamu', 'View all 50 comments', 'MARCH 5', '219 others', 'huolmannniko']
```

## Possible Solution (optional)
implementing the request blocking in instapy and modifying the code so it works without the bot detection

**Comment by c0d3x27** [comment]
can you elaborate more on how you bypassed the dectation? what files and line i have to mod to get this done?

**Comment by azmankristjan** [comment]
@c0mr4de  Hi I’m a bit new to this thing. Can you please write a step by step guide on how to disable these requests from Instagram? Thank you.

**Comment by c0d3x27** [comment]
bro can you please respond?

**Comment by JoEr500** [comment]
Sir friend

15 Nis 2020 Çar 17:15 tarihinde boss <notifications@github.com> şunu yazdı:

**Comment by ghost** [comment]
@Banginpadr @azmankristjan @JoEr500 You can search for "Request Blocking" for your own browser. For Firefox, you can press F12 and chose 'Network' from the top bar. Click on the   ⃠  symbol and input the links. But this raises another issue where some features might not work and you might have to press Ctrl+C manually on the console

**Comment by c0d3x27** [comment]
> @Banginpadr @azmankristjan @JoEr500 You can search for "Request Blocking" for your own browser. For Firefox, you can press F12 and chose 'Network' from the top bar. Click on the ⃠ symbol and input the links. But this raises another issue where some features might not work and you might have to press Ctrl+C manually on the console

thank you much i will try this and see how it goes.

**Comment by c0d3x27** [comment]
> @Banginpadr @azmankristjan @JoEr500 You can search for "Request Blocking" for your own browser. For Firefox, you can press F12 and chose 'Network' from the top bar. Click on the ⃠ symbol and input the links. But this raises another issue where some features might not work and you might have to press Ctrl+C manually on the console

hi bro, i didnt find this. im using a mac. when i hit f12 it will open inspect element. maybe im asking for too much, but i will be deeply thank full if you post a screetshot in something like imgur so i can see what you are talking about. because from what you are saying you are using firefox while im using selenium firefox

**Comment by ghost** [comment]
> 
> 
> > @Banginpadr @azmankristjan @JoEr500 You can search for "Request Blocking" for your own browser. For Firefox, you can press F12 and chose 'Network' from the top bar. Click on the ⃠ symbol and input the links. But this raises another issue where some features might not work and you might have to press Ctrl+C manually on the console
> 
> hi bro, i didnt find this. im using a mac. when i hit f12 it will open inspect element. maybe im asking for too much, but i will be deeply thank full if you post a screetshot in something like imgur so i can see what you are talking about. because from what you are saying you are using firefox while im using selenium firefox

Are you using firefox? Because I'm not sure if it's exactly the same with other browsers. Inspect element is on the same exact page with the 'Network' tab.

You press F12, there is couple of tabs: "Inspector", "Console", "Debugger", "Network", etc. What you need to do is click on "Network", you will see a search bar with the text "Filter URLs". Beside it, a pause symbol, a search symbol, and a circle-backslash symbol. Click on the circle backslash symbol and enter the URLs on the "Block resource when URL contains" bar

**Comment by ghost** [comment]
@Banginpadr That's how you manually do it, if you're more familiar with python, you can modify the browser and instapy file to use browsermob-proxy and block the requests everytime you open it
