### ISSUE TITLE
Unable to find a matching set of capabilities (Task Scheduler error) 

### ISSUE THREAD

**Issue by Abdulsamipy** [InstaPy/InstaPy#5372]
## Expected Behavior
Start bot when Scheduled 
## Current Behavior
the task scheduler is starting the bot but when the bot starts im getting 
`selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities `
the bot is working when i start it manually and i did add geckodriver to path and to the bot folder too 
## InstaPy configuration

`# let's go! :>
with smart_run(session):
    # general settings

    session.set_relationship_bounds(enabled=True,
                 potency_ratio=None,
                  delimit_by_numbers=True,
                   max_followers=2000000,
                    max_following=10000,
                     min_followers=10,
                      min_following=10)
    session.set_user_interact(amount=2, randomize=True, percentage=100,
    media='Photo')
    session.set_do_follow(enabled=False, percentage=0)
    time.sleep(30)
    session.set_do_like(enabled=True, percentage=100)
    session.set_comments(["Your work is rockin @{}", "Well done @{} :muscle:", "Your posts are excellent :thumbsup: ", "What a really nice photo, great job! @{}"])
    session.set_do_comment(enabled=True, percentage=100)
    session.set_user_interact(amount=2, randomize=True, percentage=100,
    media='Photo')
    

    # activity

    session.interact_user_followers(['jasoncapital'],
    amount=10, randomize=True)
    #session.unfollow_users(amount=100, nonFollowers=True, style="RANDOM",
    #unfollow_after=42*60*60, sleep_delay=30)
    session.like_by_tags(['garyvee', 'dailyvee', 'tailopez', 'entrepreneur', 'motivated', 'motivation', 'businessminded', 'progress'], amount=8)
   `

**Comment by tommy2049** [comment]
ping
