### ISSUE TITLE
selenium.common.exceptions.StaleElementReferenceException

### ISSUE THREAD

**Issue by Tolmino** [InstaPy/InstaPy#5374]
## Expected Behavior
have a working InstaPy

## Current Behavior
sometime after 10 minutes, sometime after 2 hours, i have 
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="_5f5mN       jIbKX  _6VtSN     yZn4P   "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

## Possible Solution (optional)

i have edited browser.py as described here:
https://github.com/timgrossmann/InstaPy/issues/5039

after that think i have a double error during execution of follow_user_followers :

 raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="_5f5mN       jIbKX  _6VtSN     yZn4P   "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 93, in <module>
    bot.follow_user_followers(follow_list, amount=30, randomize=True)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 3537, in follow_user_followers
    person, self.follow_times, sleep_delay, interact
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 1191, in follow_by_list
    self.logfolder,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/unfollow_util.py", line 609, in follow_user
    click_visibly(browser, follow_button)  # click to follow
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/util.py", line 1898, in click_visibly
    click_element(browser, element)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/util.py", line 960, in click_element
    + "')[0].scrollIntoView({ inline: 'center' });"
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 141, in get_attribute
    self, name)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="_5f5mN       jIbKX  _6VtSN     yZn4P   "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

I'm on a raspberry pi

## InstaPy configuration
""" Quickstart script for InstaPy usage """

from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

set_workspace(path="/home/pi/InstaPy")

bot = InstaPy(username="user",
              password="userpasswd",
              headless_browser=False,
              bypass_security_challenge_using='email')

with smart_run(bot):

    bot.set_quota_supervisor(enabled=True,
                             sleep_after=["likes", "follows", "unfollows", "server_calls"],
                             sleepyhead=True, stochastic_flow=True, notify_me=True,
                             peak_follows_hourly=18,
                             peak_follows_daily=300,
                             peak_likes_hourly=18,
                             peak_likes_daily=585,
                             peak_unfollows_hourly=25,
                             peak_server_calls_hourly=181,
                             peak_server_calls_daily=1200 )

    bot.set_do_follow(enabled=True, percentage=60)
    bot.set_do_like(enabled=True, percentage=80)

    bot.follow_user_followers(follow_list, amount=30, randomize=True)
    bot.end()

**Comment by henriquedevelops** [comment]
Same error here on windows 10

**Comment by ehoraizon** [comment]
I have the same error after running my script for about 2h. But in these last days it only takes approximately 1 hour for the error to occur.
**I'm using:**
- window 10
- python 3.7.7
- instapy 0.6.8
- geckodriver 0.26.8

**Comment by henriquedevelops** [comment]
> I have the same error after running my script for about 2h. But in these last days it only takes approximately 1 hour for the error to occur.
> **I'm using:**
> 
> * window 10
> * python 3.7.7
> * instapy 0.6.8
> * geckodriver 0.26.8

I was able to solve it by removing the commenting function from my quickstart configuration file

**Comment by ehoraizon** [comment]
> > I have the same error after running my script for about 2h. But in these last days it only takes approximately 1 hour for the error to occur.
> > **I'm using:**
> > 
> > * window 10
> > * python 3.7.7
> > * instapy 0.6.8
> > * geckodriver 0.26.8
> 
> I was able to solve it by removing the commenting function from my quickstart configuration file

I already tried it and that fixes it.  But the bug is now that it is impossible to comment.

**Comment by dpetrov** [comment]
I can confirm same behaviour error.

Running on Pi4 8gb
pyhon 3.7.3
instapy 0.6.10
geckodriver 0.27

Does anyone have a fix about that?
