### ISSUE TITLE
Instagram Graph API platform

### ISSUE THREAD

**Issue by waterwaterwater** [InstaPy/InstaPy#5375]
I see it on the official FAQ of instagram will be instapy work after 31 march?

Q: Why should I migrate to the Instagram Graph API platform?
A: In January 2018, we publicly announced our plans to shut down the Instagram Legacy API platform through a sequenced approach. We plan to disable the final permission remaining on the Legacy API ("Basic Permission") on March 31, 2020 and any existing apps using the Legacy API will no longer have access. We encourage you to apply for permissions to Instagram Basic Display API and migrate Legacy API calls before March 31 to avoid interruption of service to your app and business. Note that App Review submissions can take up to a week or longer to process. Refer to the developer documentation to learn more.

**Comment by camachods** [comment]
Instapy does not use the Instagram API, it's a different approach, with selenium webdriver,  as you can see in the documentation and code. So, it will continue to work. I'm doing some tests right now and everything looks ok.

**Comment by amaurypbx** [comment]
@camachods hello you managed to publish a photo on IG ?
