### ISSUE TITLE
You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

### ISSUE THREAD

**Issue by spitsen** [InstaPy/InstaPy#5381]
## Current Behavior
calvinruizendaal@Air-van-Calvin ~ % /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 /Users/calvinruizendaal/Documents/InstaPy-master/quickstart.py 
InstaPy Version: 0.6.6
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/calvinruizendaal/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-03-26 14:30:59] [calvinruizendaal]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-03-26 14:30:59] [calvinruizendaal]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2020-03-26 14:30:59] [calvinruizendaal]  - Internet Connection Status: ok
INFO [2020-03-26 14:30:59] [calvinruizendaal]  - Current IP is "82.161.35.241" and it's from "Netherlands/NL"
INFO [2020-03-26 14:30:59] [calvinruizendaal]  -- Connection Checklist [2/3] (Instagram Server Status)
WARNING [2020-03-26 14:31:07] [calvinruizendaal]  - Instagram Server Status: error
..............................................................................................................................
CRITICAL [2020-03-26 14:31:07] [calvinruizendaal]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2020-03-26 14:31:08] [calvinruizendaal]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 13.63 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-03-26 14:31:08] [calvinruizendaal]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

ERROR [2020-03-26 14:31:08] [calvinruizendaal]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

## Possible Solution (optional)
I already tried to update:
Requirement already up-to-date: instapy-chromedriver in ./Library/Python/3.6/lib/python/site-packages

and tried:

calvinruizendaal@Air-van-Calvin ~ % sudo pip install -U git+https://github.com/timgrossmann/InstaPy@dev
WARNING: The directory '/Users/calvinruizendaal/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/timgrossmann/InstaPy@dev
  Cloning https://github.com/timgrossmann/InstaPy (to revision dev) to /private/tmp/pip-req-build-zybckvpg
  Running command git clone -q https://github.com/timgrossmann/InstaPy /private/tmp/pip-req-build-zybckvpg
  WARNING: Did not find branch or tag 'dev', assuming revision or ref.
  Running command git checkout -q dev
  error: pathspec 'dev' did not match any file(s) known to git
ERROR: Command errored out with exit status 1: git checkout -q dev Check the logs for full command output.

**Comment by matej2** [comment]
I have the same problem

**Comment by orhan-drsn** [comment]
You need at least 10 comments on your script (for example on quickstart.py).
If you only few then 10 comments, instagram could block you because you always use the same comments.

You can use this Templates:
https://github.com/InstaPy/instapy-quickstart/tree/master/quickstart_templates

**Comment by matej2** [comment]
@orhan-drsn  I am using default quickstart script, and i also added two more comments. So i have 12 comments in total and I am still getting the same error.

**Comment by jinayG** [comment]
@matej2 share your script

**Comment by matej2** [comment]
```
"""
This template is written by @cormo1990
What does this quickstart script aim to do?
- Basic follow/unfollow activity.
NOTES:
- I don't want to automate comment and too much likes because I want to do
this only for post that I really like the content so at the moment I only
use the function follow/unfollow.
- I use two files "quickstart", one for follow and one for unfollow.
- I noticed that the most important thing is that the account from where I
get followers has similar contents to mine in order to be sure that my
content could be appreciated. After the following step, I start unfollowing
the user that don't followed me back.
- At the end I clean my account unfollowing all the users followed with
InstaPy.
"""

# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = ''
insta_password = ''

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=4590,
                                    min_followers=45,
                                    min_following=77)

    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])

    # activities

    """ Massive Follow of users followers (I suggest to follow not less than
    3500/4000 users for better results)...
    """
    session.follow_user_followers(['user1', 'user2', 'user3'], amount=800,
                                  randomize=False, interact=False)

    """ First step of Unfollow action - Unfollow not follower users...
    """
    session.unfollow_users(amount=500, InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=601)

    """ Second step of Massive Follow...
    """
    session.follow_user_followers(['user1', 'user2', 'user3'], amount=800,
                                  randomize=False, interact=False)

    """ Second step of Unfollow action - Unfollow not follower users...
    """
    session.unfollow_users(amount=500, InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=601)

    """ Clean all followed user - Unfollow all users followed by InstaPy...
    """
    session.unfollow_users(amount=500, InstapyFollowed=(True, "all"),
                           style="FIFO", unfollow_after=24 * 60 * 60,
                           sleep_delay=601)

    """ Joining Engagement Pods...
    """
    photo_comments = ['Nice shot! @{}',
        'Awesome! @{}',
        'Cool :thumbsup:',
        'Just incredible :open_mouth:',
        'What camera did you use @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Nice @{}',
        ':raised_hands: Yes!',
        'I can feel your passion @{} :muscle:',
        'Nice @{}',
        'Nice @{}']

    session.set_do_comment(enabled = True, percentage = 95)
    session.set_comments(photo_comments, media = 'Photo')
    session.join_pods(topic='food', engagement_mode='no_comments')
```

**Comment by jinayG** [comment]
You have repeated this same comment as 3 times "Nice @{}"

**Comment by matej2** [comment]
This does not make any difference, i also tried with random comments

**Comment by dnkrse** [comment]
Might be your order. Try calling set_comments before set_do_comments.

**Comment by matej2** [comment]
jghjghj
bump

**Comment by matej2** [comment]
dogfihdsf
bump

**Comment by matej2** [comment]
bump

**Comment by MaximVer** [comment]
I am getting the same error, I tried to add about 30 distinct comments but still getting this error.
Could you guys @jinayG  @OpaSieben post an example of your script? That would be helpful. Thanks

**Comment by matej2** [comment]
gdsresw
bump

**Comment by metapodcod** [comment]
I am getting the same error, I tried to add about 30 distinct comments but still getting this error.
Could you guys @jinayG @OpaSieben post an example of your script? That would be helpful. Thanks

**Comment by matej2** [comment]
gftghrthtr

**Comment by matej2** [comment]
@timgrossmann is the issue resolved?

**Comment by matej2** [comment]
For those of you who have the same issue:

This issue is not actually resolved. People just dont wanna take a look at it. 

They have a bot that automatically closes inactive issues so it looks like they care (and solve) issues. However, this issue is still active and was not closed by the bot. The author closed is himself.

**Comment by ghost** [comment]
having the same problem, pls help

**Comment by matej2** [comment]
@venmag they wont help you, you have to pay (donate)

**Comment by pvnotpv** [comment]
Am having the same issue , what to do

**Comment by matej2** [comment]
@VikingStudios-Z you have to pay to get support here
