### ISSUE TITLE
InstaPy in Docker No such file or directory

### ISSUE THREAD

**Issue by tmnunes** [InstaPy/InstaPy#5389]
I am currently running the InstaPy in a docker container. 
It runs but after a few hours it stops with the "current behavior" message. I don't understand why, but if I try to restart it will restart only some times, and other times it will stuck with the same error.

## Expected Behavior
I expect that the container doesn't stop without any intervention. 

## Current Behavior
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo
[Errno 2] No such file or directory: '/tmp/tmp0b7691i4'

## InstaPy configuration
insta_username = 'myuser'
insta_password = 'xxxxxxxxxx'
dont_like = ['food', 'girl', 'hot']
ignore_words = ['pizza']
friend_list = ['friend1', 'friend2', 'friend3']
bot = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
with smart_run(bot):
    bot.set_relationship_bounds(enabled=True,
                                potency_ratio=None,
                                delimit_by_numbers=True,
                                min_followers=500,
                                min_following=500)
    bot.set_do_comment(False, percentage=10)
    bot.set_do_follow(enabled=True, percentage=85, times=2)
    bot.set_dont_unfollow_active_users(enabled=False, posts=5)
    bot.unfollow_users(amount=60, instapy_followed_enabled=True, instapy_followed_param="nonfollowers", style="FIFO", unfollow_after=90*60*60, sleep_delay=501)
    bot.set_comments(['Cool!', 'Awesome!', 'Nice!'])
    bot.set_do_story(enabled = True, percentage = 50, simulate = True)
    bot.set_dont_include(friend_list)
    bot.set_dont_like(dont_like)
    bot.follow_by_tags(['photo', 'canon'], amount=10)
    bot.like_by_feed(amount=100, randomize=True, unfollow=False, interact=True)
    bot.set_ignore_if_contains(ignore_words)
    bot.set_delimit_liking(enabled=True, min_likes=15)
    bot.set_do_like(enabled=True, percentage=82)
    bot.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
    bot.set_quota_supervisor(enabled=True, sleep_after=["likes", "follows"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes_hourly=47,
                              peak_likes_daily=545,
                                peak_follows_hourly=20,
                                peak_follows_daily=100,
                                 peak_unfollows_hourly=20,
     bot.end()

**Comment by samanmohamadi** [comment]
I have this issue too.
 running script directly or with docker every time it crashes with the same error.
**[Errno 2] No such file or directory: '/tmp/tmpxxxxxx'**
