### ISSUE TITLE
[SOLVED] Timeout after trying to follow user's followers

### ISSUE THREAD

**Issue by westonskiff** [InstaPy/InstaPy#5392]
## Current Behavior
I get this error after trying to follow a user's followers

> Traceback (most recent call last):
>   File "quickstart.py", line 102, in <module>
>     interact=True)
>   File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 3466, in follow_user_followers
>     self.logfolder,
>   File "/usr/local/lib/python3.6/dist-packages/instapy/unfollow_util.py", line 1027, in get_given_user_followers
>     logfolder,
>   File "/usr/local/lib/python3.6/dist-packages/instapy/unfollow_util.py", line 767, in get_users_through_dialog_with_graphql
>     browser.get("view-source:{}".format(url))
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
>     self.execute(Command.GET, {'url': url})
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.TimeoutException: Message: Timeout loading page after 300000ms

## InstaPy configuration

> import random
> from instapy import InstaPy
> from instapy import smart_run
> 
> insta_username = 'a'
> insta_password = 'a'
> 
> dont_likes = ['a', 'a', 'a']
> ignore_users = ['a', 'a', 'a']
> 
> friends = ['a', 'a', 'a']
> 
> ignore_list = []
> 
> targets = ['a', 'a', 'a']
> 
> target_business_categories = ['a', 'a', 'a']
> 
> comments = ['a']
> 
> session = InstaPy(username=insta_username,
>                   password=insta_password,
>                   headless_browser=True,
>                   disable_image_load=True,
>                   multi_logs=True)
> 
> with smart_run(session):
>     session.set_simulation(enabled=True)
>     session.set_relationship_bounds(enabled=True,
>                                     potency_ratio=None,
>                                     delimit_by_numbers=True,
>                                     max_followers=7500,
>                                     max_following=3000,
>                                     min_followers=25,
>                                     min_following=25,
>                                     min_posts=10)
> 
>     session.set_user_interact(amount=3, randomize=True, percentage=80,
>                               media='Photo')
>     session.set_do_like(enabled=True, percentage=90)
>     session.set_do_comment(enabled=True, percentage=15)
>     session.set_comments(comments, media='Photo')
>     session.set_do_follow(enabled=True, percentage=40, times=1)
> 
>     number = random.randint(3, 5)
>     random_targets = targets
> 
>     if len(targets) <= number:
>         random_targets = targets
> 
>     else:
>         random_targets = random.sample(targets, number)
> 
>     session.follow_user_followers(random_targets,
>                                   amount=random.randint(30, 60),
>                                   randomize=True, sleep_delay=600,
>                                   interact=True)
> 
>     session.unfollow_users(amount=random.randint(75, 100),
>                            InstapyFollowed=(True, "nonfollowers"),
>                            style="FIFO",
>                            unfollow_after=24 * 60 * 60, sleep_delay=600)
> 
>     session.unfollow_users(amount=random.randint(75, 100),
>                            InstapyFollowed=(True, "all"), style="FIFO",
>                            unfollow_after=168 * 60 * 60, sleep_delay=600)
> 
>     session.join_pods()

**Comment by westonskiff** [comment]
Nevermind, I fixed it by downgrading firefox to 73.0.1

**Comment by finedesignz** [comment]
> Nevermind, I fixed it by downgrading firefox to 73.0.1

How did you downgrade firefox?  I am using Instapy on Digital Ocean. Thanks!

**Comment by rob1nzon** [comment]
Thx! For downgrade on ubuntu i use https://sourceforge.net/projects/ubuntuzilla/files/mozilla/apt/pool/main/f/firefox-mozilla-build/

**Comment by Chenchela** [comment]
@finedesignz : did you manage to downgrade Firefox?

**Comment by lilhamza** [comment]
unfortunately it didn't work. The same error keep poping out: timeout 30000
