### ISSUE TITLE
Insert target users, hashtags etc from text file

### ISSUE THREAD

**Issue by IreneArapogiorgi** [InstaPy/InstaPy#5396]
Hello, I would like to contribute to InstaPy as part of a university course of mine, called Software Engineering in Practice, in which we are supposed to contribute to an open source project of our choice.

### Expected Behavior
Amongst other feature ideas, I thought it would be useful for most users to have the ability to import a text file with their target users, hashtags etc. This implementation will especially benefit businesses using InstaPy as they could store users/hashtags etc in already-made target lists as text files and parse each one of them depending on their campaigns.
### Current Behavior
For all existing functions accepting lists as given parameters, simple user is obliged to edit those lists inside the script, which complicates code comprehension & requires time.
### Possible Solution
Implement the option of reading a text file for each function which accepts lists as given parameters.

_I will be thrilled if you accept my upcoming contribution & I hope we'll have a great collaboration._
_PS: Any advice is more than welcomed._

**Comment by Miladinho** [comment]
This software is heavily dependent on the changes Facebook makes to Instagram and therefore is not itself something that would be that useful for you to speak about as a good project reference when you go into job interviews. Furthermore, I think it depends heavily on the use of selenium, so unless you want to go into a role like SDET or QA engineering, there is not much framework specific knowledge to be gained. I recommend using your time for this school project to work on something that can develop specific skills you want to use in a job that you desire.

**Comment by IreneArapogiorgi** [comment]
@Miladinho I really appreciate your advice. Thank you for responding so fast.

As this is going to be my first contribution to an open source project, I chose InstaPy for being well-written in Python (in which I'm already experienced) and also because I have personally been involved in social media marketing before (and especially Instagram campaigns) and therefore I'm quite familiar with InstaPy's theme and functionality. My goal is actually to manage comprehending other people's code, follow up with their standards and try to make even a small contribution. And then I shall chase bigger projects.

I'm keeping your advice and I already have a list of alternatives, however I would like to give this project a chance.

**Comment by breuerfelix** [comment]
> ... I chose InstaPy for being well-written in Python ...

i don't know if i can sign this :D in germany we say 'Too many cooks spoil the broth.'. But yeah i guess that's the same for every big OS project :)

We already talked about your project. There is just one tip i got for you. Don't change the existing functions. Just program new functions which take a path to a list as a param, parse the list and pass the parsed list to the already existing function :) you can then also pass all other params to the existing function with `*args` and `**kwargs`.  Just some suggestions that comes to my mind!

**Comment by IreneArapogiorgi** [comment]
@breuerfelix thank you for assigning me this feature! I will definitely take into consideration your advice and I'll keep you posted about my progress or if I need any help.
