### ISSUE TITLE
BLOCKED at first or second like

### ISSUE THREAD

**Issue by c0d3x27** [InstaPy/InstaPy#5398]
some weird is happening im getting block almost as soon my script start. i mean it keep working but there is a panel telling me that instagram had blocked me from doing such activity

**Comment by xee95** [comment]
same

**Comment by c0d3x27** [comment]
wow is just sad that this was a nice bot and now is just here and no one take care of it. no one will help with the problems

**Comment by JoEr500** [comment]
my friend, I can not quite understand what he says is Turkish, I can help
if you can text in Turkish.

15 Nis 2020 Çar 17:37 tarihinde boss <notifications@github.com> şunu yazdı:
