### ISSUE TITLE
Error "Please wait a few minutes before you try again."

### ISSUE THREAD

**Issue by henriquedevelops** [InstaPy/InstaPy#5400]
I get this message on the browser when trying to open up a instagram profile page.
This only occurs when logged into my account.
When I'm not logged in, it works fine.

Someone help, please?

Thanks

**Comment by Parazok** [comment]
IG temporary banned your account

**Comment by henriquedevelops** [comment]
I was able to solve this by deleting all cookies and setting up my browser to automatically delete cookies when it closes

**Comment by henriquedevelops** [comment]
It was just talk about it and I have this issue again...
How do you set up your quota supervisor?

**Comment by OdraudeKey** [comment]
Same Issue.

**Comment by Parazok** [comment]
I found out it's because of Ig new limitations for browser base connections.
I have this problem too with even a very low quota supervisor config.

**Comment by henriquedevelops** [comment]
> I found out it's because of Ig new limitations for browser base connections.
> I have this problem too with even a very low quota supervisor config.

How low are your quota supervisor config?

**Comment by Skrohk** [comment]
I have the same issue for the second time, have you successfully solved it or I juste have to reduce my quota supervisor ?

**Comment by henriquedevelops** [comment]
> I have the same issue for the second time, have you successfully solved it or I juste have to reduce my quota supervisor ?

I was able to solve it for now by lowering my quota supervisor configs with hourly and daily sever call limits

**Comment by GCinellu** [comment]
Hi @billyjones123 can you confirm you still resolved the issue? I started running in it now and unfortunately deleting the cookies didn't do the trick.

> I was able to solve this by [...] and **setting up my browser to automatically delete cookies when it closes**

Did you do any configuration on instapy or how did you manage to set up your browser to always delete cookies?

Do you mind elaborating a little bit more about your profile (is it new? is it established?) and sharing your configuration?

This is what happened that led to my ban, lol
<img width="500" alt="Screen Shot 2020-05-08 at 10 11 28 PM" src="https://user-images.githubusercontent.com/9399792/81446256-d7284680-917a-11ea-843a-c152426e6e2b.png">

**Comment by henriquedevelops** [comment]
> Hi @billyjones123 can you confirm you still resolved the issue? I started running in it now and unfortunately deleting the cookies didn't do the trick.
> 
> > I was able to solve this by [...] and **setting up my browser to automatically delete cookies when it closes**
> 
> Did you do any configuration on instapy or how did you manage to set up your browser to always delete cookies?
> 
> Do you mind elaborating a little bit more about your profile (is it new? is it established?) and sharing your configuration?
> 
> This is what happened that led to my ban, lol
> <img alt="Screen Shot 2020-05-08 at 10 11 28 PM" width="500" src="https://user-images.githubusercontent.com/9399792/81446256-d7284680-917a-11ea-843a-c152426e6e2b.png">

I thought I solved the issue, but I was mistaken.
But instapy still liking and commenting even with this issue.

This is my instapy configuration:
session.set_quota_supervisor(enabled=True, sleep_after=["likes", "server_calls"], sleepyhead=True, stochastic_flow=True, notify_me=False,
                              peak_likes_hourly=25, peak_likes_daily=400,
                                 peak_server_calls_hourly=200, peak_server_calls_daily=3500)

My account is about 2 years old.
What do you mean by established?

Also, would you happen to know how to set up multiple instapy running at the same time on different accounts?

Thanks

**Comment by mhdakhtar8** [comment]
> Hi @billyjones123 can you confirm you still resolved the issue? I started running in it now and unfortunately deleting the cookies didn't do the trick.
> 
> > I was able to solve this by [...] and **setting up my browser to automatically delete cookies when it closes**
> 
> Did you do any configuration on instapy or how did you manage to set up your browser to always delete cookies?
> 
> Do you mind elaborating a little bit more about your profile (is it new? is it established?) and sharing your configuration?
> 
> This is what happened that led to my ban, lol
> <img alt="Screen Shot 2020-05-08 at 10 11 28 PM" width="500" src="https://user-images.githubusercontent.com/9399792/81446256-d7284680-917a-11ea-843a-c152426e6e2b.png">

How do I get the data related to my server calls?

**Comment by GCinellu** [comment]
> Also, would you happen to know how to set up multiple instapy running at the same time on different accounts?

@billyjones123 The way I solved it is to define different `job` functions with different account settings and have them run at different timeframes. It's not possible (as far as I'm aware) to run them concurrently, although I would even discourage that since that would easily lead to a flag from Instagram.

> How do I get the data related to my server calls?
@mhdakhtar8 When you run instapy, it usually creates a folder in your user space (`~/Instapy`). There you can find all your `.db` files and I used a simple DB explorer (SQLITE3) to navigate the files :)

**Comment by alexal1** [comment]
Consider this script instead of InstaPy: https://github.com/alexal1/Insomniac.
It works with Android device, not web version. It doesn't make graphql requests, only uses Instagram Android app interface. So there are nearly zero chances to be blocked.

**Comment by esilvaju** [comment]
> https://github.com/alexal1/Insomniac

Thanks !

**Comment by matheusgregorio** [comment]
> IG temporariamente baniu sua conta

this problem lasts how long?
