### ISSUE TITLE
follow_user_followers gives error "Timeout loading page after 300000ms"

### ISSUE THREAD

**Issue by DanielZanchi** [InstaPy/InstaPy#5404]
#4689  Expected Behavior
While trying to load a user followers, it gets stuck and then gives the error that you can see on the log.
## Current Behavior
[terminalLog.txt](https://github.com/timgrossmann/InstaPy/files/4462700/terminalLog.txt)

I am using this QuickStart:

[quickstart.txt](https://github.com/timgrossmann/InstaPy/files/4462703/quickstart.txt)

Why is this happening?
To make it work I installed Firefeox manually.

MacOS 10.15.4
Python 3.7.7

**Comment by kaleidoskopio** [comment]
Getting the same "Timeout loading page after 300000ms" when I'm trying to load 50 followers. 
Should we decrease the number?

Is it normal that now the followers of an account are collected from such a coded page?
(or did I miss an update of the code at some point? 

Thanks in advance for your answers to both topics :)
![2020-04-18 23_12_10-follow_user_followers gives error _Timeout loading page after 300000ms_ · Issue ](https://user-images.githubusercontent.com/53099310/79671381-2a395a00-81ca-11ea-9272-4613848bfe87.png)

**Comment by NickTxD** [comment]
I had the same error too. Any updates?

**Comment by RhymezxCode** [comment]
I found a solution to this error, just downgrade firefox to exactly 73.0.1. 
thats all

**Comment by ntpq** [comment]
> I found a solution to this error, just downgrade firefox to exactly 73.0.1.
> thats all

i tried this. it's working now

**Comment by HackersSpirit** [comment]
I am experiencing the same issue as mentioned above in firefox 77.0.1 64 bit.
Guys i tried downgrading the firefox as mentioned above but still getting the same issue
