### ISSUE TITLE
Like someone else following/followers post - limit 100 post per day

### ISSUE THREAD

**Issue by rezaj1394** [InstaPy/InstaPy#5411]
I need to config instapy to like someone else following/followers posts and limit this action to like 100 posts per days and 6 post of every follower/followin

This is my configuration, How should limit this action per day?

```
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'myUser'
insta_password = 'myPass'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

session.set_user_interact(amount=5, randomize=True, percentage=100)
session.set_do_follow(enabled=False, percentage=70)
session.set_do_like(enabled=True, percentage=70)
session.set_do_comment(enabled=False, percentage=80)
session.interact_user_following(['username'], amount=10, randomize=True)
```

**Comment by rezaj1394** [comment]
Is there any answer for this question?

**Comment by tperas** [comment]
@rezaj1394  Look at the quota supervisor for the daily limit, and the user interact configuration. 
By mixing both you should reach your goal. 
Just be careful as the followers/following extraction is easily detected as bot by instagram
