### ISSUE TITLE
Quota_Supervisor doesnt sleep 'likes_h'

### ISSUE THREAD

**Issue by RobTheTop** [InstaPy/InstaPy#5417]
Hi. 
My quota_supervisor doesnt work. Who can help me? i set it uo to sleep after 30 likes per hour, but it likes more and more.

```
session.set_quota_supervisor(enabled=True, sleep_after=['likes_h'], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes_hourly=30,
                              peak_likes_daily=None)

```

**Comment by mik3bg** [comment]
Same here I change sleep_after=['likes']
 `session.set_quota_supervisor(enabled=True, sleep_after=["likes"],stochastic_flow=True, notify_me=True, peak_likes_hourly=57, peak_likes_daily=585)`
Actually if I change peak_likes_hourly=2 its sleep after second like but when is it 57 its keep going
I counted how much likes produce it`s more then a 57.Wondering why.
