### ISSUE TITLE
Make scripts more random

### ISSUE THREAD

**Issue by jmurphy45** [InstaPy/InstaPy#542]
Could the script become more random where the sleep method in all the functions use a random number in a range like 1 to 4 seconds for example to make it more random.

**Comment by timgrossmann** [comment]
@jmurphy45 Every sleep in the whole script as a random distribution over 1/2 and 1 1/2 the time.

So e.g. on the 4sec sleeps, it will sleep for a random number of seconds between 2 and 6 seconds
