### ISSUE TITLE
How do you stay safe?

### ISSUE THREAD

**Issue by henriquedevelops** [InstaPy/InstaPy#5420]
How do you stay safe against Instagram bans?

This is my current quota supervisor configuration:

session.set_quota_supervisor(enabled=True, sleep_after=["likes", "server_calls"], sleepyhead=True, stochastic_flow=True, notify_me=False,
                              peak_likes_hourly=25, peak_likes_daily=400,
                                 peak_server_calls_hourly=200, peak_server_calls_daily=3500)

My quickstart file is set up to 2 actions only, which is liking and following.
I don't set up a limit to following because it only follows when liking.

I am having issues with Instagram bans.

**Comment by alexal1** [comment]
Consider using https://github.com/alexal1/Insomniac if you have Android device or emulator. It sends touch events to the device using Android Debug Bridge and fully simulates a human.
