### ISSUE TITLE
It doesn't follow or comment

### ISSUE THREAD

**Issue by lucasmirachi** [InstaPy/InstaPy#5422]
I'm running a pretty simple code that was supposed to like, comment and  follow on different posts, just like the code below:

from instapy import instapy
session = InstaPy(username="username", password="password")
session.login()
session.like_by_tags(["bmw", "mercedes"], amount=5)
session.set_do_follow(True, percentage=100)
session.set_do_comment(True, percentage=100)
session.set_comments(["Nice!", "Sweet!", "Beautiful :heart_eyes:"])
session.end()

But it only likes the photos, it doesn't comment or follows regardless of the percentage I put on the respective parameters. I get the following message in the log:

INFO [2020-04-20 03:01:13] [username]  Like# [1/14]
INFO [2020-04-20 03:01:13] [username]  https://www.instagram.com/p/B_MR2CUlMdM/
INFO [2020-04-20 03:01:16] [username]  Image from: b'bmw_club_perm'
INFO [2020-04-20 03:01:16] [username]  Link: b'https://www.instagram.com/p/B_MR2CUlMdM/'
INFO [2020-04-20 03:01:16] [username]  Description: #bmw\xe2\x9d\xa4\xef\xb8\x8f#bmwlove #bmwlife #msk #bmw_club_kuban#bmwkuban#bmwekb #bmw#bmwkuban#bmw23#bmw23sochi#bmw_girls#bmwsochi 
INFO [2020-04-20 03:01:49] [username]  --> **Image Liked!**
INFO [2020-04-20 03:01:52] [username]  --> **Not commented**
INFO [2020-04-20 03:01:53] [username]  --> **Not following**

Is anybody facing this same issue? 
Thank you in advance!

**Comment by lucasmirachi** [comment]
Looking at older issues (**issue #5289** ), I think I've figured out why it isn't commenting or following.
Maybe it is not finding the "comment" and "follow" button to interact with, but I have no idea of how I can get the right XPath to replace the old ones, as people did on this old issue...

@zipsoft, @timgrossmann, or anyone else could, by any chance, explain to me how this XPath works, so I can help to fix this comment/follow issue?

**Comment by AliceNardoni** [comment]
comigo tambem aconteceu esse erro.

**Comment by stairwaysxx23** [comment]
well just a little help..  put your session.like_by_tags on the buttom of session.set_do_
so Instapy can Likes and Comments but still cant Follow if already put likes and comments code..
and yeah..  maybe thats a lot of code at once ??
here is my code : 

session.set_do_comment(enabled=True, percentage=100)
session.set_comments(["flf ? <3<3<3","fff kak??"])
session.set_do_follow(enabled=True, percentage=100)
session.set_user_interact(
    amount=5,
    randomize=True,
    percentage=100,
    media="Photo"
)
session.like_by_tags(["flf","fff"], amount=5)

**Comment by siddhantchimankar** [comment]
@timgrossmann  please look into this, it is one of the core features

**Comment by mantree95** [comment]
I am having the same issue too 
INFO [2020-05-21 01:37:59] [USERNAME]  Like# [2/12]
INFO [2020-05-21 01:37:59] [USERNAME]  https://www.instagram.com/p/CAcX678DElm/
INFO [2020-05-21 01:38:04] [USERNAME]  Image from: b'vacationize'
INFO [2020-05-21 01:38:04] [USERNAME]  Link: b'https://www.instagram.com/p/CAcX678DElm/'
INFO [2020-05-21 01:38:04] [USERNAME]  Description: b'Iceland is a country full of volcanic activity, and this is the reason behind the black sand. The black sediment on Reynisfjara beach has been formed by boiling hot lava, from the currently dormant volcano, floating across the beach, then cooling and solidifying when hitting the cold water. After this cold hit the solid lava starts to break apart and forms small volcanic rock, which then gradually weathers down further to create smaller pebbles, thus black sand.\xc2\xa0\xf0\x9f\x87\xae\xf0\x9f\x87\xb8 -\n-\n-\nFollow: @vacationize\nFollow: @vacationize -\n-\n-\n-\nCredits: @zachtesta \n#iceland #blacksandbeach #icelandtravel #icelandtrip'
INFO [2020-05-21 01:38:04] [USERNAME]  Location: b'Iceland'
INFO [2020-05-21 01:38:44] [USERNAME]  --> Image Liked!
INFO [2020-05-21 01:39:22] [USERNAME]  --> Not commented
INFO [2020-05-21 01:39:22] [USERNAME]  --> Not following
Any progress

**Comment by lucasmirachi** [comment]
> I am having the same issue too
> INFO [2020-05-21 01:37:59] [USERNAME] Like# [2/12]
> INFO [2020-05-21 01:37:59] [USERNAME] https://www.instagram.com/p/CAcX678DElm/
> INFO [2020-05-21 01:38:04] [USERNAME] Image from: b'vacationize'
> INFO [2020-05-21 01:38:04] [USERNAME] Link: b'https://www.instagram.com/p/CAcX678DElm/'
> INFO [2020-05-21 01:38:04] [USERNAME] Description: b'Iceland is a country full of volcanic activity, and this is the reason behind the black sand. The black sediment on Reynisfjara beach has been formed by boiling hot lava, from the currently dormant volcano, floating across the beach, then cooling and solidifying when hitting the cold water. After this cold hit the solid lava starts to break apart and forms small volcanic rock, which then gradually weathers down further to create smaller pebbles, thus black sand.\xc2\xa0\xf0\x9f\x87\xae\xf0\x9f\x87\xb8 -\n-\n-\nFollow: @vacationize\nFollow: @vacationize -\n-\n-\n-\nCredits: @zachtesta \n#iceland #blacksandbeach #icelandtravel #icelandtrip'
> INFO [2020-05-21 01:38:04] [USERNAME] Location: b'Iceland'
> INFO [2020-05-21 01:38:44] [USERNAME] --> Image Liked!
> INFO [2020-05-21 01:39:22] [USERNAME] --> Not commented
> INFO [2020-05-21 01:39:22] [USERNAME] --> Not following
> Any progress

After testing a little and after getting some help from a friend, I figured out why it didn't work. It was actually a problem with my code. 
In my case, the problem was that you must set configuration BEFORE call activity and also set interaction. So, the final code (which now is able to like, comment and follow people according to specific tags) is:

```
from instapy import InstaPy
session = InstaPy(username="your_username", password="your_password", headless_browser=False)
session.login()

#settings
session.set_do_follow(True, percentage=100)
session.set_do_comment(True, percentage=100)
session.set_comments(["Nice!", "Sweet!", "Beautiful heart_eyes"])
session.set_do_like(enabled=True, percentage=100)
session.set_user_interact(amount=3, randomize=True, percentage=100, media="Photo")

#activity
session.like_by_tags(["bmw", "mercedes"], amount=5, interact=True, media="Photo")

session.end()
```
I hope this helps! =)

**Comment by neerajHebbar** [comment]
> > I am having the same issue too
> > INFO [2020-05-21 01:37:59] [USERNAME] Like# [2/12]
> > INFO [2020-05-21 01:37:59] [USERNAME] https://www.instagram.com/p/CAcX678DElm/
> > INFO [2020-05-21 01:38:04] [USERNAME] Image from: b'vacationize'
> > INFO [2020-05-21 01:38:04] [USERNAME] Link: b'https://www.instagram.com/p/CAcX678DElm/'
> > INFO [2020-05-21 01:38:04] [USERNAME] Description: b'Iceland is a country full of volcanic activity, and this is the reason behind the black sand. The black sediment on Reynisfjara beach has been formed by boiling hot lava, from the currently dormant volcano, floating across the beach, then cooling and solidifying when hitting the cold water. After this cold hit the solid lava starts to break apart and forms small volcanic rock, which then gradually weathers down further to create smaller pebbles, thus black sand.\xc2\xa0\xf0\x9f\x87\xae\xf0\x9f\x87\xb8 -\n-\n-\nFollow: @vacationize\nFollow: @vacationize -\n-\n-\n-\nCredits: @zachtesta \n#iceland #blacksandbeach #icelandtravel #icelandtrip'
> > INFO [2020-05-21 01:38:04] [USERNAME] Location: b'Iceland'
> > INFO [2020-05-21 01:38:44] [USERNAME] --> Image Liked!
> > INFO [2020-05-21 01:39:22] [USERNAME] --> Not commented
> > INFO [2020-05-21 01:39:22] [USERNAME] --> Not following
> > Any progress
> 
> After testing a little and after getting some help from a friend, I figured out why it didn't work. It was actually a problem with my code.
> In my case, the problem was that you must set configuration BEFORE call activity and also set interaction. So, the final code (which now is able to like, comment and follow people according to specific tags) is:
> 
> ```
> from instapy import InstaPy
> session = InstaPy(username="your_username", password="your_password", headless_browser=False)
> session.login()
> 
> #settings
> session.set_do_follow(True, percentage=100)
> session.set_do_comment(True, percentage=100)
> session.set_comments(["Nice!", "Sweet!", "Beautiful heart_eyes"])
> session.set_do_like(enabled=True, percentage=100)
> session.set_user_interact(amount=3, randomize=True, percentage=100, media="Photo")
> 
> #activity
> session.like_by_tags(["bmw", "mercedes"], amount=5, interact=True, media="Photo")
> 
> session.end()
> ```
> 
> I hope this helps! =)

Same problem please help please help
