### ISSUE TITLE
It says you need at least 10 comments but i have 12

### ISSUE THREAD

**Issue by matej2** [InstaPy/InstaPy#5423]
## Expected Behavior

Quickstart would run

## Current Behavior

Hello,

When i try to run project as described [here](https://github.com/Herrox/instapy-docker/blob/master/documentation/docker.md) i get this error: 
> ERROR [2019-11-08 14:00:14] [user423]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

## Possible Solution (optional)

I was looking into Instapy issues and one of them mentioned [this possible solution](https://github.com/timgrossmann/InstaPy/issues/4441#issuecomment-494371736).

## InstaPy configuration

My quickstart file includes more than 10 comments: 

```
comments = ['Nice shot! @{}',
        'I love your profile! @{}',
        'Your feed is an inspiration :thumbsup:',
        'Just incredible :open_mouth:',
        'What camera did you use @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Getting inspired by you @{}',
        ':raised_hands: Yes!',
        'I can feel your passion @{} :muscle:',
        'Nice photo',
        'Cool photo']
```

At first i tought that this is the docker issue, so i submitted the issue to [instapy-docker](https://github.com/InstaPy/instapy-docker/issues/57) repo, but they said that this error seems to be related directly to InstaPy and not to Docker.

**Comment by matej2** [comment]
Still not resolved, old issue was closed by bot

**Comment by bradleyshelley99** [comment]
I'm having similar problems. I'm not sure whats causing this but I have well over 10 comments. I've also tried turning off headless browsing which was a solution I saw elsewhere.

**Comment by Dimensionsofahimsa** [comment]
Same issue here, not sure how to get it fixed either!

*edit, I do not use docker

**Comment by Dimensionsofahimsa** [comment]
Sometimes the bot still works, I'd say 30% chance when launching it that it will work.

I didn't change anything to my scripts when the issue came up. Now I updated the instapy installation, no result.

**Comment by lucasmirachi** [comment]
I was having this same issue, but you just have to insist on it a little, and it will eventually work.

My problem is that it doesn't comment or follow the people back, it only likes the photos by the tags I specified and, instead of completing the other actions, it moves to the next one. Do you guys have this problem too?

**Comment by Dimensionsofahimsa** [comment]
> I was having this same issue, but you just have to insist on it a little, and it will eventually work.
> 
> My problem is that it doesn't comment or follow the people back, it only likes the photos by the tags I specified and, instead of completing the other actions, it moves to the next one. Do you guys have this problem too?

Sometimes I need to insist 8 times before it works though!

I don't use these other functions, I only use it for likes and that works fine still

**Comment by matej2** [comment]
> I was having this same issue, but you just have to insist on it a little, and it will eventually work.

Insist? How do you mean.

I ran quickstart script which should work.

Edit: I also tried multiple times, but it always failed

**Comment by Dimensionsofahimsa** [comment]
> > I was having this same issue, but you just have to insist on it a little, and it will eventually work.
> 
> Insist? How do you mean.
> 
> I ran quickstart script which should work.
> 
> Edit: I also tried multiple times, but it always failed

Insist as in, try again and again.
Eventually, it will work sometimes, at least for me it does.

Headless or not seems of no difference, btw

**Comment by matej2** [comment]
Quickstart script out of the box should work on the first try. Just retrying is not the right solution for this. 

Especially if you try to run it in docker container, which is what i am trying to do

**Comment by jhrtrl** [comment]
I had the same problem. I have just added the string "want_check_browser=False" for Instapy to stop the checks.

**Comment by Dimensionsofahimsa** [comment]
> I had the same problem. I have just added the string "want_check_browser=False" for Instapy to stop the checks.

Didn't change anything for me

**Comment by Max604** [comment]
What can we do to fix this. What are you trying to do now @matej2 ?

**Comment by matej2** [comment]
I am trying to run InstaPy in docker container. As i saw in dockerfile, it then tries to run quickstart script. I dont know what to do to fix this, as I am not familiar with code (and i am a beginner in Python), but i can provide debug info regarding the bug.

**Comment by loganjensen** [comment]
I'm having the same issue. Has not worked for me yet, and keeps giving me the error of having too few comments.

**Comment by marouane159** [comment]
I added more than 20 comment and **it works**.

**Comment by matej2** [comment]
@marouane159 I am pretty sure this is not what solved the problem. Can you be more specific what did you change?

**Comment by Dimensionsofahimsa** [comment]
> @marouane159 I am pretty sure this is not what solved the problem. Can you be more specific what did you change?

It's indeed not the solution, otherwise, this thread was not existing IMO!

**Comment by Dimensionsofahimsa** [comment]
For me, it still works after retry retry retry.

I really enjoy InstaPy, would be sad if this becomes a totally unusable bot due to no updates

**Comment by elbambolo** [comment]
same issue. no comment in my quickstart

**Comment by LukaGiorgadze** [comment]
same issue

**Comment by RealDataLLC** [comment]
Is InstaPy dead then?

**Comment by matej2** [comment]
> For me, it still works after retry retry retry.

So I should just retry until it works? Then you dont have the same problem

**Comment by luismec90** [comment]
@matej2 try to set `want_check_browser=False`

```
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  want_check_browser=False)
```

It seems InstaPy tries to validate the Instagram servers using a domain that is broken: https://isitdownorjust.me/instagram-com/ so you need to skip that validation.

**Comment by ndrewgood** [comment]
@luismec90 Didn't work for me either, followed all the suggestions in this thread

**Comment by fabiostein** [comment]
@luismec90 , Did you resolve this issue? I have the same problem. Let me know if you got sucess.

**Comment by CodexAsh** [comment]
This worked for me
 want_check_browser=False

**Comment by chrishoste** [comment]
I'm getting `__init__() got an unexpected keyword argument 'want_check_browser'`. Sometimes it works and sometimes not, but I can live with that. My problem is that I always get the error `You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.` even though I have enough. Is there no way to turn off the check? Once I decide to use InstaPy, I do it at my own risk?

**Comment by CodexAsh** [comment]
> I'm getting `__init__() got an unexpected keyword argument 'want_check_browser'`. Sometimes it works and sometimes not, but I can live with that. My problem is that I always get the error `You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.` even though I have enough. Is there no way to turn off the check? Once I decide to use InstaPy, I do it at my own risk?

Just pass the value. want_check_browser=False. It will work.


Instapy(username = ''hshhs", password = "hdhdbs", want_check_browser=False)

**Comment by matej2** [comment]
This probably will never be solved

**Comment by MaximVer** [comment]
Still an issue. `want_check_browser=False` doesn't help
```
TypeError: __init__() got an unexpected keyword argument 'want_check_browser'
```

**Comment by matej2** [comment]
InstaPy is dead

**Comment by Dimensionsofahimsa** [comment]
> InstaPy is dead

It sadly seems quite true at this point. Sad, is there any alternatives?

**Comment by matej2** [comment]
Sadly, no. There was a prototype for NodeJS version, but this is also dead (it is the same as InstaPy, gets you banned). Also, no communty there

**Comment by matej2** [comment]
dgfd

**Comment by LukaGiorgadze** [comment]
Still.....

**Comment by matej2** [comment]
@timgrossmann is the issue resolved?

**Comment by LukaGiorgadze** [comment]
> @timgrossmann is the issue resolved?

I guess no

**Comment by matej2** [comment]
I cant understand why this repo accepts donations and also at the same time have bot that automatically closes issues? 
And this issue was **active** and you closed it anyway?

**Comment by matej2** [comment]
For those of you who have the same issue:

This issue is not actually resolved. People just dont wanna take a look at it. 

They have a bot that automatically closes inactive issues so it looks like they care (and solve) issues. However, this issue is still active and was not closed by the bot. The author closed is himself.

**Comment by Glyphism** [comment]
Sorry to open this again, but I have been looking everywhere with no luck. I am getting the same "You have too few comments" error, shown in the below context. I am trying to isolate the issue, has anyone had further luck?:

```
Last login: Wed Feb 24 13:29:28 on ttys000
You have mail.
namehidden@Mac ~ % /Users/namehidden/Documents/Tech/Social/Instagram/Instapy/instapy-quickstart-master/run/mac_start.command ; exit;
Starting InstaPy with quickstart
====================
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/namehidden/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-02-24 13:29:50] [namehidden]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-02-24 13:29:50] [namehidden]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-02-24 13:29:51] [namehidden]  - Internet Connection Status: ok
INFO [2021-02-24 13:29:51] [namehidden]  - Current IP is "101.186.42.23" and it's from "Australia/AU"
INFO [2021-02-24 13:29:51] [namehidden]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-02-24 13:29:51] [namehidden]  - window.navigator.webdriver response: None
INFO [2021-02-24 13:29:51] [namehidden]  - Hide Selenium Extension: ok
INFO [2021-02-24 13:29:54] [namehidden]  - Cookie file not found, creating cookie...
.........................................................................................................................
CRITICAL [2021-02-24 13:30:29] [namehidden]  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2021-02-24 13:30:29] [namehidden]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2021-02-24 13:30:30] [namehidden]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 44.4 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-02-24 13:30:30] [namehidden]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by matej2** [comment]
@Glyphism You have to pay (donate) in order to get help. You can see that the owner simply closed this issue

**Comment by Glyphism** [comment]
@matej2 Sorry I wasn't aware I thought this was an open discussion forum. I haven't used GitHub very often. Maybe if anyone else knows the latest status, who doesn't require payment, they can chime in.
