### ISSUE TITLE
ensure chromedriver is installed at...

### ISSUE THREAD

**Issue by Mariuski19** [InstaPy/InstaPy#5429]
![Screenshot 2020-04-22 at 18 33 17](https://user-images.githubusercontent.com/64140128/80008402-ff9c1980-84c7-11ea-8017-82ff1ef669a3.png)

Hi guys I am new in this. I keep having this problem in the last step of the installation phase. I don't know if it is a python problem or something to do with chrome. Ive read a lot of post but could not figure out how to solve it. Than you in advance

**Comment by Dimensionsofahimsa** [comment]
Firefox is installed?

Everything updated?

**Comment by Mariuski19** [comment]
You mean Chrome right?
I just downloaded everything so its has to be up to date.

**Comment by Dimensionsofahimsa** [comment]
> You mean Chrome right?
> I just downloaded everything so its has to be up to date.

Download Firefox as the headless browser uses it, not chrome

**Comment by Mariuski19** [comment]
I have downloaded Firefox and no luck, I try to run Insteps and that's message pop up. Also when I installed it in the first step, this message is shown 
 DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Successfully installed InstaPy!
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by Mariuski19** [comment]
I have Phyton 3.8.

![Screenshot 2020-04-22 at 22 27 05](https://user-images.githubusercontent.com/64140128/80030553-a85a7100-84e8-11ea-9a82-976aa8914eec.png)

**Comment by brintaylor93** [comment]
once you update your pips it doesnt go away even though it is updated. I did the same and mine is updated and still says the same thing.
