### ISSUE TITLE
Mention Friends to Different Posts Comment

### ISSUE THREAD

**Issue by GiannisRallis** [InstaPy/InstaPy#5430]
Hello people i want to create a bot and make comments to post which need to tag a friends.
I read the Documentation but i could not figure out the solution. 

Also i need a solution when post is liked to make comments or multiple comments without end session. I can comment only to posts witch are not liked....

Thank you.

**Comment by ajju2smart** [comment]
Anyone found the solution to this issue. I'm still not able to fix this issue.:(
