### ISSUE TITLE
Login A/B test detected! Trying another string...

### ISSUE THREAD

**Issue by ortegafernando** [InstaPy/InstaPy#5433]
Hi, I have been using Instapy last weeks. Today, I get this error:

```Login A/B test detected! Trying another string...```

I have deleted cookie (just in case) and re-run again manually Instapy seeing what is happening.

Instapy can't log into Instagram loggin windows, may be Instagram has changed again Xpaths? (I dont know exactly how to solve this).

I have also check after deleting my cookie in logs folder. Same problem.

```Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...
..........................................................................................................................
CRITICAL [2020-04-25 08:47:42] [XXXXXXXXXX]  Unable to login to Instagram! You will find more information in the logs above.
```

**Comment by ortegafernando** [comment]
Hi, nobody with this problem?

**Comment by Paris704** [comment]
I do too and I don't know what to do about it. Also I'm on Mac so there is no Xpath file in my version from what I have gathered.

**Comment by Jungmetro** [comment]
same problem here, is there any way to manually log in to get around this?

**Comment by xerZV** [comment]
same problem here on raspberry pi 3

**Comment by kristijandraca** [comment]
I have the same problem on my Macbook

**Comment by arthasisacat** [comment]
I have having the same issue
