### ISSUE TITLE
relationship tools not working - 0 followers/nonfollowers grabbed

### ISSUE THREAD

**Issue by cherrypie121** [InstaPy/InstaPy#5434]
I tried to grab followers, nonfollowers but I always get 0. I googled it but couldn't find a solution

session = InstaPy(username='xxxx',
                  password='xxxx',
                  headless_browser=False)

session.grab_followers(username="xxxx", amount="full", live_match=True, store_locally=True)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-04-25 11:54:07] [xxxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
________________________________________________________________________________
INFO [2020-04-25 11:54:08] [xxxx]  Starting to get the `Followers` data..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2020-04-25 11:54:08] [xxxx]  Retrieving live `Followers` data of xxxx at "full" range
  0/1018 [+-----------------------------------]  0%    |> Elapsed: 0.05 seconds    |> ETA: 5.92 seconds

INFO [2020-04-25 11:54:20] [xxxx]  Grabbed 0 usernames from `Followers` in 0.05 seconds

**Comment by AuthFailed** [comment]
+1
