### ISSUE TITLE
InstaPy works too slow

### ISSUE THREAD

**Issue by sn1l** [InstaPy/InstaPy#5438]
When I want InstaPy to like posts by usernames, it stays on those peoples' profile about 30sec without doing anything. That's too long for me.
My internet connection as well as my hardware is no problem.
I also set custom action delays very low.
Any idea how to speed the bot up?

**Comment by Mohanbarman** [comment]
Bro it's good for not getting ban

**Comment by sn1l** [comment]
> Bro it's good for not getting ban

For sure, but if I do the stuff the bot is meant to do, I am about 5-6 times faster. So the bot could work so much faster without getting banned

**Comment by Mohanbarman** [comment]
They will ban your action if you still do it manually for long time like 3-4hr . I've done it and i do got results of getting banned

**Comment by sn1l** [comment]
yeah, but i only want to do it for max. 30 min. That works. Just need a solution how to decrease the time the bot remains on a person's profile without doing anything.

**Comment by Mohanbarman** [comment]
You can use set_action_delays function but it's not recommended to set it below the default time intervals

**Comment by sn1l** [comment]
I already used set_action_delays and made them smaller. But I want to reduce the time InstaPy remains on a person's profile without doing anything. I am aware of the risks. Let them be my thing.

**Comment by s0urc3-ray** [comment]
Randomness is the key to not getting banned. If anything the program waiting the exact same amount of seconds each time is exactly how to get a ban.

**Comment by sn1l** [comment]
i just want to reduce the time instapy remains on a profile without doing anything. it takes 30 - 60 seconds, but I want it to take 5-15 seconds. That's still longer than a human needs.

**Comment by dyohan9** [comment]
I am also looking for something about it, does anyone have any idea how to solve it?
