### ISSUE TITLE
How do I create new workspace?

### ISSUE THREAD

**Issue by henriquedevelops** [InstaPy/InstaPy#5440]
## Expected Behavior
Run multiple scripts at the same time

## Current Behavior
Running only 1 script at a time

## Possible Solution (optional)
After researching on issues, I found this: #5403 (some guy solved the same issue I'm having) but I don't understand his explanation... How do I create this new workspace?
Could someone PLEASE explain to me in a little more detail?
I would be so thankful

**Comment by naimulh247** [comment]
@billyjones123 include this before session login. 
```
from instapy import set_workspace
set_workspace(path="")
```
Copy the InstaPy folder to anywhere or make a copy and rename it.
Set the path to the new copy of it. 
this is how the path should look like
![image](https://user-images.githubusercontent.com/42220440/81489448-73b61b80-9243-11ea-9141-61e95439415a.png)

**Comment by henriquedevelops** [comment]
> @billyjones123 include this before session login.
> 
> ```
> from instapy import set_workspace
> set_workspace(path="")
> ```
> 
> Copy the InstaPy folder to anywhere or make a copy and rename it.
> Set the path to the new copy of it.
> this is how the path should look like
> ![image](https://user-images.githubusercontent.com/42220440/81489448-73b61b80-9243-11ea-9141-61e95439415a.png)

I did exactly as you said. But still can run only 1 script at a time...
When I try to run the second quickstart (with the first already running), I get this error message: "SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape"

**Comment by dimekmaurer** [comment]
This error occurs because you are using a normal string as a path. You can use one of the following solutions to fix your problem.
Just put "r" before your normal string it converts normal string to raw string (r"C:\Users\Cherry\InstaPy\"). I think so ;)
