### ISSUE TITLE
Wont comment if the image is already liked

### ISSUE THREAD

**Issue by navaniharsh31** [InstaPy/InstaPy#5442]
## Expected Behavior
comment everytime
## Current Behavior
if the image is already like it skips and doesnt comment
using the code from the docs 

```
session.set_do_follow(enabled=False, percentage=50)
session.set_comments(["Cool", "Super!"])
session.set_do_comment(enabled=True, percentage=80)
session.set_do_like(True, percentage=70)
session.interact_by_users_tagged_posts(['user1', 'user2', 'user3'], amount=5, randomize=True, media='Photo')
```

**Comment by navaniharsh31** [comment]
@timgrossmann

**Comment by busbuyukefe** [comment]
@uluQulu @timgrossmann please take a look at this I too have the same problem. Is there a workaround for this problem?

**Comment by tomaspietravallo** [comment]
I have the same issue :(
