### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by manuel-bopp** [InstaPy/InstaPy#5448]
(Content removed by author - this 2020 setup issue is long obsolete.)

**Comment by alinbasuljevic** [comment]
Same issue here!

**Comment by Bernardiho11** [comment]
Check what version of python is install in your system, I'm guessing your PC is 64bit. Most likely you are using 32bit version instead on 64bit. To solve this error. Download the exact version for your system from pythons site.

**Comment by alinbasuljevic** [comment]
Didn't work, same error

**Comment by ucalyptus** [comment]
@Bernardiho11 @alinbasuljevic @manubananu same issue

**Comment by ucalyptus** [comment]
Does it work on colab which is a headless console?
