### ISSUE TITLE
Ability to interact with user's own followers

### ISSUE THREAD

**Issue by drogon34** [InstaPy/InstaPy#545]
I think it might be a good idea to implement a feature for a user to interact with his own followers. As a user's following increases and he doesn't follow some of them back, he should still have the ability to interact with their feed.

Something like this perhaps:
`session.set_user_interact(amount=5, random=False, media='Photo')
 session.like_by_followers_feed(amount=10, random=True, interact=True)`

Maybe the user should have the ability to input the usernames or say choose any 'x' number of random accounts to interact with from his follower list.
If the user's _follower_ list can be stored in a cache/log and referenced each time this feature is used, the same accounts will not be interacted with again unless the user manually clears the log file or deletes it.

I can see a lot of utility for this feature. If you all have any other additions that can be included as part of this then do comment.

**Comment by timgrossmann** [comment]
@drogon34 Reopen this issue if I'm wrong but checkout the `.interact_user_follower()` out. simply provide your own username.

Interact with users that someone else is following
```python
#Interact with the people that a given user is following
#set_do_comment, set_do_follow and set_do_like are applicable
session.set_user_interact(amount=5, random=True, percentage=50, media='Photo')
session.set_do_follow(enabled=False, percentage=70)
session.set_do_like(enabled=False, percentage=70)
session.set_comments(["Cool", "Super!"])
session.set_do_comment(enabled=True, percentage=80)
session.interact_user_following(['natgeo'], amount=10, random=True)
```
Interact with someone else's followers
```python
#Interact with the people that a given user is following
#set_do_comment, set_do_follow and set_do_like are applicable
session.set_user_interact(amount=5, random=True, percentage=50, media='Photo')
session.set_do_follow(enabled=False, percentage=70)
session.set_do_like(enabled=False, percentage=70)
session.set_comments(["Cool", "Super!"])
session.set_do_comment(enabled=True, percentage=80)
session.interact_user_followers(['natgeo'], amount=10, random=True)
```

**Comment by drogon34** [comment]
Oh, this might be it then. I was not aware this had been implemented and merged. Will give it a go. Really appreciate this project and all the time you folks have put into it.
