### ISSUE TITLE
Check if user's account is private

### ISSUE THREAD

**Issue by IreneArapogiorgi** [InstaPy/InstaPy#5451]
Hello, I would like to make another contribution to InstaPy as part of the same university course of mine, in which we are supposed to contribute to an open source project of our choice.

### Expected Behavior
When using [get_followers()](https://github.com/timgrossmann/InstaPy/blob/8f1a12934759af2d3d5b9a5bfb30e33c1de0f9b6/instapy/relationship_tools.py#L18) and [get_followings()](https://github.com/timgrossmann/InstaPy/blob/8f1a12934759af2d3d5b9a5bfb30e33c1de0f9b6/instapy/relationship_tools.py#L297) we should check if user's account is private or not in order to proceed into finding his followers/followings.
### Current Behavior
Both functions search for given user's followers and followings regardless of whether the account is private or not. So, in case of a private account, they return 0 followers/followings without informing the user that this happened because target account was private. Note that there are already two to-do comments related to this implementation inside these functions.
### Possible Solution
Use [is_private_profile()](https://github.com/timgrossmann/InstaPy/blob/master/instapy/util.py#L65) inside [get_followers()](https://github.com/timgrossmann/InstaPy/blob/8f1a12934759af2d3d5b9a5bfb30e33c1de0f9b6/instapy/relationship_tools.py#L18) and [get_followings()](https://github.com/timgrossmann/InstaPy/blob/8f1a12934759af2d3d5b9a5bfb30e33c1de0f9b6/instapy/relationship_tools.py#L297).

_PS: Any advice is more than welcomed._

**Comment by IreneArapogiorgi** [comment]
So far, I've added a few lines of code as you can see [here](https://github.com/timgrossmann/InstaPy/compare/master...IreneArapogiorgi:private_account_checking) and they seem to be working just fine. However, I think I could optimize that by checking whether the user follows this private account, as in this case he should be able to grab its followers/followings.

That could be done by using [get_following_status()](https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py#L147), however adding `from .unfollow_util import get_following_status` inside relationship_tools.py is not allowed because functions of [relationship_tools.py](https://github.com/timgrossmann/InstaPy/blob/master/instapy/relationship_tools.py) are being imported and used inside [unfollow_util.py](https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py) and when trying to import back from unfollow_util.py to relationship_tools.py we create circular (recursive) imports which raises an error.

The only way to overcome this is to create a new file, lets say follow_util.py, in which we are going to move [get_following_status()](https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py#L147) and then import the function inside both [relationship_tools.py](https://github.com/timgrossmann/InstaPy/blob/master/instapy/relationship_tools.py) and [unfollow_util.py](https://github.com/timgrossmann/InstaPy/blob/master/instapy/unfollow_util.py). In the future, more functions related to follow utility could be moved inside this new file.

So, @timgrossmann and @breuerfelix what do you think about that? Can I proceed to the implementation of this idea or should I keep my code as it is and make a pull request?

**Comment by naazneen** [comment]
Hello, I don't find any description about how to contribute here. Can anyone help me out?

**Comment by IreneArapogiorgi** [comment]
@naazneen open a new related issue and I'll help you out.

**Comment by IreneArapogiorgi** [comment]
@timgrossmann @breuerfelix this issue is addressed in PR #5470. Will that PR be integrated in the main code?

**Comment by ManuData** [comment]
I believe that the contribution that IreneArapogiorgi suggests would be awesome!

**Comment by IreneArapogiorgi** [comment]
@ManuData it has already been applied in PR #5918!

**Comment by ManuData** [comment]
@IreneArapogiorgi Maybe I did not understand the focus of your contribution, but what I tried and I did not manage to in an "optimal solution" way, is to:
- select the followers that have **public account** from a target account
I found a very bad way to achieve that, something like: 
`with smart_run(session):
    lista_non_private=[]
    for name in users_target:
        try:
            target = session.grab_followers(username=name, amount=1, live_match=True, store_locally=False)
            if len(target):
                lista_non_private.append(name)
        except:
            pass`

Is there other way? Excuse me in advantage if still missundertood the contribution.

thnks!
