### ISSUE TITLE
Unable to comment and follow, the amount is different from the original.  

### ISSUE THREAD

**Issue by br551** [InstaPy/InstaPy#5452]
## Expected Behavior
session = InstaPy(username=insta_username, password=insta_password,headless_browser=False)

with smart_run(session):
  """ Activity flow """			
  session.set_dont_include(["friend1", "friend2", "friend3"])		
  	
  session.like_by_tags(["wildlife"], amount=5)
  session.set_dont_like(['love','follow','memes'])
     
  session.set_do_comment(enabled=True, percentage=25)
  session.set_comments(['Awesome', 'Really Cool', 'Beautiful'])
  session.follow_by_tags(['natgeo', 'wildlife'], amount=5)

## Current Behavior

The first issue is the amount I set for is 5 to like and follow tags, however, desired amount changed to 14. 
Second, I am unable to post comments.  
Third -  follow by tags is not working, I am not getting any errors.  While running the program it shows that follow 1/12. However, I doesn't apply to the account.  

Please let me know what I am doing wrong.  

![Inkedinstapy2_LI](https://user-images.githubusercontent.com/64700109/80870184-b2ebd780-8c59-11ea-8988-d728114763d2.jpg)

![Inkedinstapy1_LI](https://user-images.githubusercontent.com/64700109/80870110-2d682780-8c59-11ea-8c6f-6c469f2f272b.jpg)

**Comment by naimulh247** [comment]
1. its the amount x the number of tags. So you have 2 tags x 5 =10. Based on the documentation.
2. your comment percent `session.set_do_comment(enabled=True, percentage=25)` is 25% if you want high comment rate change it to something like 90
3. I don't remember on top of my head. but let me know if those 2 works
