### ISSUE TITLE
More like for like_by_location

### ISSUE THREAD

**Issue by Mr-Hodler** [InstaPy/InstaPy#5453]
how do I make sure that for each profile puts more than one like, because it doesn't work interact with location

## InstaPy configuration
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,  # <---------- Graphics!  default true hide
                  disable_image_load=False,  # default true
                  multi_logs=True)

with smart_run(session):
    """ Activity flow """
    # general settings	

    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=4000,
                                    max_following=10000,
                                    min_followers=300,
                                    min_following=150,
                                    min_posts=5)

    session.set_simulation(enabled=True)

    session.set_skip_users(skip_private=True, 
			  skip_no_profile_pic=True,
			  no_profile_pic_percentage = 100)
                         

    # like settings	

    session.set_delimit_liking(enabled=True, max_likes=500, min_likes=10)

    ##### ACTIVITY #####

    # Interact
    session.set_user_interact(amount=3, randomize=True, percentage=100)
    session.like_by_locations(['213181248', '213736946','261059863', '238875664','215032588','252617467'], amount=70)
 #  lugano bellinzona ticino svizzera como milano

**Comment by TrevorWysong** [comment]
Here is an implementation for this. 
Add this function in instapy.py: 
    
    def new_like_by_locations(
            self,
            locations: list = None,
            amount: int = 50,
            media: str = None,
            randomize: bool = False,
            skip_top_posts: bool = True,
            like_amount_per_user: int = 10,
    ):
        """Likes (default) 50 images per given locations"""
        if skip_top_posts == True:
            pass

        if self.aborting:
            return self

        liked_img = 0
        already_liked = 0
        inap_img = 0
        commented = 0
        followed = 0
        not_valid_users = 0
        tempAmount = like_amount_per_user

        locations = locations or []
        self.quotient_breach = False

        for index, location in enumerate(locations):
            user_post_decrementer = tempAmount
            if self.quotient_breach:
                break

            self.logger.info("Location [{}/{}]".format(index + 1, len(locations)))
            self.logger.info("--> {}".format(location.encode("utf-8")))

            try:
                links = get_links_for_location(
                    self.browser, location, amount, self.logger, media, skip_top_posts
                )
            except NoSuchElementException as exc:
                self.logger.warning(
                    "Error occurred while getting images from location: {}  "
                    "~maybe too few images exist\n\t{}\n".format(
                        location, str(exc).encode("utf-8")
                    )
                )
                continue

            for i, link in enumerate(links):
                user_post_decrementer = tempAmount
                if self.jumps["consequent"]["likes"] >= self.jumps["limit"]["likes"]:
                    self.logger.warning(
                        "--> Like quotient reached its peak!\t~leaving "
                        "Like-By-Locations activity\n"
                    )
                    self.quotient_breach = True
                    # reset jump counter after a breach report
                    self.jumps["consequent"]["likes"] = 0
                    break

                self.logger.info("Like# [{}/{}]".format(i + 1, len(links)))
                self.logger.info(link)

                try:
                    inappropriate, user_name, is_video, reason, scope = check_link(
                        self.browser,
                        link,
                        self.dont_like,
                        self.mandatory_words,
                        self.mandatory_language,
                        self.is_mandatory_character,
                        self.mandatory_character,
                        self.check_character_set,
                        self.ignore_if_contains,
                        self.logger,
                    )
                    try:
                        user_links = get_links_for_username(
                            self.browser,
                            self.username,
                            user_name,
                            like_amount_per_user,
                            self.logger,
                            self.logfolder,
                            randomize,
                            media,
                        )
                    except NoSuchElementException:
                        self.logger.warning("Element not found, skipping this username")
                        continue

                    for i, link in enumerate(user_links):
                        if user_post_decrementer > 0:
                            if not inappropriate and self.delimit_liking:
                                self.liking_approved = verify_liking(
                                    self.browser, self.max_likes, self.min_likes, self.logger
                                )

                            if not inappropriate and self.liking_approved:
                                # validate user
                                validation, details = self.validate_user_call(user_name)

                                if validation is not True:
                                    self.logger.info("--> Not a valid user: {}".format(details))
                                    not_valid_users += 1
                                    continue
                                else:
                                    web_address_navigator(self.browser, link)

                                # try to like
                                like_state, msg = like_image(
                                    self.browser,
                                    user_name,
                                    self.blacklist,
                                    self.logger,
                                    self.logfolder,
                                    liked_img,
                                )

                                if like_state is True:
                                    user_post_decrementer -= 1
                                    liked_img += 1
                                    # reset jump counter after a successful like
                                    self.jumps["consequent"]["likes"] = 0

                                    checked_img = True
                                    temp_comments = []

                                    commenting = (
                                            random.randint(0, 100) <= self.comment_percentage
                                    )
                                    following = random.randint(0, 100) <= self.follow_percentage

                                    if self.use_clarifai and (following or commenting):
                                        try:
                                            (
                                                checked_img,
                                                temp_comments,
                                                clarifai_tags,
                                            ) = self.query_clarifai()

                                        except Exception as err:
                                            self.logger.error(
                                                "Image check error: {}".format(err)
                                            )

                                    # comments
                                    if (
                                            self.do_comment
                                            and user_name not in self.dont_include
                                            and checked_img
                                            and commenting
                                    ):

                                        if self.delimit_commenting:
                                            (
                                                self.commenting_approved,
                                                disapproval_reason,
                                            ) = verify_commenting(
                                                self.browser,
                                                self.max_comments,
                                                self.min_comments,
                                                self.comments_mandatory_words,
                                                self.logger,
                                            )
                                        if self.commenting_approved:
                                            # smart commenting
                                            comments = self.fetch_smart_comments(
                                                is_video, temp_comments
                                            )
                                            if comments:
                                                comment_state, msg = comment_image(
                                                    self.browser,
                                                    user_name,
                                                    comments,
                                                    self.blacklist,
                                                    self.logger,
                                                    self.logfolder,
                                                )
                                                if comment_state is True:
                                                    commented += 1

                                        else:
                                            self.logger.info(disapproval_reason)

                                    else:
                                        self.logger.info("--> Not commented")
                                        sleep(1)

                                    # following
                                    if (
                                            self.do_follow
                                            and user_name not in self.dont_include
                                            and checked_img
                                            and following
                                            and not follow_restriction(
                                        "read", user_name, self.follow_times, self.logger
                                    )
                                    ):

                                        follow_state, msg = follow_user(
                                            self.browser,
                                            "post",
                                            self.username,
                                            user_name,
                                            None,
                                            self.blacklist,
                                            self.logger,
                                            self.logfolder,
                                        )
                                        if follow_state is True:
                                            followed += 1

                                    else:
                                        self.logger.info("--> Not following")
                                        sleep(1)

                                elif msg == "already liked":
                                    already_liked += 1

                                elif msg == "block on likes":
                                    break

                                elif msg == "jumped":
                                    # will break the loop after certain consecutive
                                    # jumps
                                    self.jumps["consequent"]["likes"] += 1

                            else:
                                self.logger.info(
                                    "--> Image not liked: {}".format(reason.encode("utf-8"))
                                )
                                inap_img += 1

                except NoSuchElementException as err:
                    self.logger.error("Invalid Page: {}".format(err))

            self.logger.info("Location: {}".format(location.encode("utf-8")))
            self.logger.info("Liked: {}".format(liked_img))
            self.logger.info("Already Liked: {}".format(already_liked))
            self.logger.info("Commented: {}".format(commented))
            self.logger.info("Followed: {}".format(followed))
            self.logger.info("Inappropriate: {}".format(inap_img))
            self.logger.info("Not valid users: {}\n".format(not_valid_users))

        self.followed += followed
        self.liked_img += liked_img
        self.already_liked += already_liked
        self.commented += commented
        self.inap_img += inap_img
        self.not_valid_users += not_valid_users

        return self

then in quickstart call the function:

`session.new_like_by_locations(locations=['212999109'], amount=2, media='Photo', randomize=False, skip_top_posts=False, like_amount_per_user=2)`

amount is number of location posts you want. like_amount_per_user is how many posts per user it likes before returning to the locations loop to go to a different post/link.
