### ISSUE TITLE
Fixing not connecting to instagram because isitdownorjust.me is down

### ISSUE THREAD

**Issue by awsm0** [InstaPy/InstaPy#5455]
## Expected Behavior
Connect to instagram

## Current Behavior
doesnt connect to instagram because the website (isitdownorjust.me) is down
 
## Possible Solution (optional)
I commented out line 211 where it tries to check uptime with isitdownorjust.me in the login_util.py file

**Comment by carloe** [comment]
I think you can bypass the checks by setting `want_check_browser` to `False`. I.e something like:

```python
session = InstaPy(username=..., password=..., want_check_browser=False)
```

**Comment by awsm0** [comment]
> I think you can bypass the checks by setting `want_check_browser` to `False`. I.e something like:
> 
> ```python
> session = InstaPy(username=..., password=..., want_check_browser=False)
> ```

thank you good to know, definitely easier than my solution
