### ISSUE TITLE
skip_top_posts=False  for all top post

### ISSUE THREAD

**Issue by Mr-Hodler** [InstaPy/InstaPy#5456]
## Current Behavior
hi guy, in the roule instapy skip_top_posts=False    do I take all the popular photos or just the first nine?

i I'd like to put like only to the top pictures 
## InstaPy configuration
    """ Activity flow """
    # general settings	

    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=2700,
                                    min_followers=200,
                                    min_following=150,
                                    min_posts=5)

    session.set_simulation(enabled=True)

    session.set_skip_users(skip_private=True,
                           skip_business=False,
                           skip_no_profile_pic=True,
                           no_profile_pic_percentage=100)
                           

    # like settings	

    session.set_delimit_liking(enabled=True, max_likes=600, min_likes=10)

  
    ##### ACTIVITY #####

    # Interact
    session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
    session.set_do_like(enabled=True, percentage=100)
    session.like_by_tags(['lugano', 'bellinzona' , 'switzerland'], amount=200, interact=True, skip_top_posts=False)

**Comment by ttorelli7** [comment]
With "skip_to_posts=False" it will search for all the photos, including the 9 first most popular. If you enable the parameter, it will jump **these 9 first most popular photos**, searching only for the most recent photos.
