### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by theolux** [InstaPy/InstaPy#546]
Hi,

First off, thank you so much for this tool, it's so useful and I'm impressed how well it works!

I've been playing with it the past few days, and I noticed a few problems that I would like to hear your thoughts on:
1. It seems that when trying to like+comment+follow at the same time, issue #335 occurs. How difficult is it to fix?
2. I don't really understand how the like amount per tag works. I mean, I'd set it to 500 per tag and it will only like a random smaller amount of posts per tag, almost never 500. Why is that and is there a way to run the script until a specific amount of posts are liked?
3. I'm trying to run it 24/7 and I already received a 24 hour block, is there a way to limit the script in order to optimize 24/7 use? (I guess this relates to the previous question, if I can run the script until I liked the highest amount of posts possible without a block, I would set it to run automatically every day at a specific hour).

Thanks!

**Comment by westondeboer** [comment]
2. If you have these set:

`.set_lower_follower_count(limit = 1)\
.set_upper_follower_count(limit = 800)\`

It will vary how many images are liked based on the amount of followers the person has, and then based on if they have over 800 followers, it won't like any images. The reason you don't want to like images from user who have a lot of followers, is that they will not be likely to follow you back.

3. You shouldn't really be running it 24/7, you should try and hit below 1000 likes a day. To be safe. 

So you could run it every three hours and like 150 images, and you should hit below 1000 likes a day. If my math is correct.

**Comment by irinhuman** [comment]
2: The reason it only likes so many photos is the parameters of each part of the script (such as likes, don't likes, ignores, etc.). I also believe the clarifai api which is included does some filtering so you could turn it into comment and that should increase the photos you like per tag from what I have experienced. Also, you may get banned liking every photo in a tag so its probably better to not like every photo

3: to run 24hr you need crontab which is explained a bit in the readme under automation. 

Cheers
