### ISSUE TITLE
Any idea why interact_by_URL doesn't comment the provided URL?

### ISSUE THREAD

**Issue by merianos** [InstaPy/InstaPy#5467]
I am new to Python, as well as new to InstaPy. I have configured a custom script to comment posts by provided URLs, but unfortunately, when the InstaPy running, it visiting the posts and doesn't comment them.

Do I have any wrong configuration? Do you see anything I have in wrong?

Otherwise, do you know any other way to achieve the same result?

## Expected Behavior
To comment posts

## Current Behavior
Doesn't comment posts

## InstaPy configuration
```
# imports
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

# set workspace folder at the desired location (default is at your home folder)
set_workspace(path=None)

comments_list = ["comment #1", "comment #2", "... comment #X"]
accounts = [
    "https://www.instagram.com/p/1/",
    "https://www.instagram.com/p/2/",
    "https://www.instagram.com/p/3/",
    "https://www.instagram.com/p/.../",
    "https://www.instagram.com/p/X/",
]

# get an InstaPy session!
session = InstaPy(username="my_username", password="my_password")

with smart_run(session):
    # preparation
    session.set_do_follow(enabled=False)
    session.set_do_like(enabled=False)
    session.set_do_comment(enabled=True, percentage=100)
    session.set_comments(comments_list)
    session.set_user_interact(amount=1, randomize=True, percentage=15)

    # activity
    session.interact_by_URL(urls=accounts, randomize=True)
```

**Comment by Sandz1** [comment]
hi i have just started using instapy and have the same errors. did you find a solution ?

**Comment by luizcarvalho** [comment]
+1 with  this issue =(

**Comment by betobetotech** [comment]
+1

**Comment by joaoguazzelli** [comment]
+1

**Comment by charleskx** [comment]
+1

**Comment by phnahes** [comment]
+1

**Comment by hermasec** [comment]
i am trying to comment on a specific post in instagram
here is my code :

```
from instapy import InstaPy

insta_username = "username"
insta_password = "password"

session = InstaPy(username=insta_username, password=insta_password)
session.login()

# set up all the settings
session.set_relationship_bounds(enabled=True,delimit_by_numbers=True)
session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
session.set_do_comment(enabled=True, percentage=85)

session.interact_by_URL(urls=["https://www.instagram.com/p/CDBdLvUpTYu/?igshid=2im20zz3lvz5"], randomize=False, interact=True)
print("done")
# end the bot session
session.end()
```
this is what i get :
_INFO [2021-05-06 02:18:32] [username] --> Image already liked!
INFO [2021-05-06 02:18:32] [username] Liked: 0
INFO [2021-05-06 02:18:32] [username] Already Liked: 1
INFO [2021-05-06 02:18:32] [username] Commented: 0
INFO [2021-05-06 02:18:32] [username] Followed: 0
INFO [2021-05-06 02:18:32] [username] Inappropriate: 0
INFO [2021-05-06 02:18:32] [username] Not valid users: 0_

can someone plaese help me figure out why it doesnt comment anything!!

**Comment by aey-ck** [comment]
same issue here
