### ISSUE TITLE
Follow issue - "Failed to get the user ID from post page!"

### ISSUE THREAD

**Issue by TiagoDS7** [InstaPy/InstaPy#5469]
![issue](https://user-images.githubusercontent.com/41171767/81416964-649b7480-9142-11ea-85e2-0a45f6f7bb83.jpg)

## Expected Behavior
Getting user ID without throwing an error message
## Current Behavior
Failed to get user ID from post page

Hello everybody. I've been playing around with the bot lately and everytime I try to follow a user, I get this error message, and I can't seem to find a workaround to it.

Thanks in advance  :)

**Comment by mhdakhtar8** [comment]
@TiagoDS7 why did you close this issue? was it resolved? I'm facing the same issue as well.
