### ISSUE TITLE
No module named 'instapy' 

### ISSUE THREAD

**Issue by jb63126** [InstaPy/InstaPy#5471]
Hello Everyone,

First, thank you (@timgrossmann) for orchestrating all of these efforts and contributing so much time and effort. Additionally, big thanks to all the individuals that contributed to this project and troubleshooting. I appreciate your time and knowledge.

To my troubles... I am using a Mac (OS Catalina) and I feel like have exhausted the available resources, but I am still running into this issue:

Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
ModuleNotFoundError:No module named 'instapy'

So I tried the pip3 install instapy:
All the messages say already satisfied. However there is a warning that I am using pip version 19.2.3 and version 20.1 is available.

So I try to upgrade to 20.1:
Then it gives me Deprecation: Python 2.7 reached... 

However, when I check my python version in Command Line it shows 3.7.2.

I have received a message that I have installed Instapy as well:

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Successfully installed InstaPy!
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by naimulh247** [comment]
@jb63126 Have you tired this:
`sudo pip3 install --upgrade pip`
`pip3 install --upgrade pip`
`pip3 install instapy`
let me know if this works

**Comment by jb63126** [comment]
Ran those... 

sudo pip3 install --upgrade pip
WARNING: The directory '/Users/xxxxLibrary/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/Users/jakebuerke/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/54/2e/df11ea7e23e7e761d484ed3740285a34e38548cf2bad2bed3dd5768ec8b9/pip-20.1-py2.py3-none-any.whl (1.5MB)
     |████████████████████████████████| 1.5MB 1.9MB/s 
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-20.1
xxxx-iMac:~ xxxx$ pip3 install --upgrade pip
Requirement already up-to-date: pip in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (20.1)
Could not build wheels for pip, since package 'wheel' is not installed.

Tried to install, but it gave me numerous errors related to inability to build wheels

**Comment by naimulh247** [comment]
soo it updated pip to the latest version, that's a good sign. Now try `pip3 install wheel` use `sudo` if it doesn't install. After wheel install run `pip3 install --upgrade pip` and then `pip3 install instapy` that should do it

**Comment by jb63126** [comment]
followed those steps... installed wheel, upgraded pip, install instapy... no errors or glaring instances.

When I go to run the mac_start.command, I receive the same message (see below):

Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
ModuleNotFoundError: No module named 'instapy'
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

quickstart.py had login information added. Nothing else modified.

**Comment by naimulh247** [comment]
are you running it with `python quickstart.py` or `python3 quickstart.py`? if you are doing the first one do the second one `python3 quickstart.py`

**Comment by jb63126** [comment]
I was just opening the file. If I run the prompts in command, this is what I get.

xxxx:~ xxxx$ python3 quickstart.py
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3: can't open file 'quickstart.py': [Errno 2] No such file or directory
xxxx:~ xxxx$ python quickstart.py
/Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'quickstart.py': [Errno 2] No such file or directory

**Comment by naimulh247** [comment]
if the file is located on your Desktop cd there and then run the command lol

**Comment by jb63126** [comment]
Apologies, but I dont know what that means. I am a total amateur (as if that needed to be said).
I saved the instapy-quickstart master on my desktop, yes.

**Comment by naimulh247** [comment]
no worries, we were all confused at one point. Open up a terminal from search and type `ls` and enter. This basically lists all the folder and files there is in that specific directory. You should see 'Desktop' as one of them. Type `cd Desktop` (change directory to Desktop) and enter. You can press tab to autocomplete after getting the first couple of letters. If you type `ls` again you should see all the files in your desktop, and now you can use the `cd` to go into the folder that has the quickstart.py and run `python3 quickstart.py`

**Comment by jb63126** [comment]
Progress, but a different bridge to cross... 

err_msg = set_selenium_local_session
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by naimulh247** [comment]
No worries! Do you have firefox installed?

**Comment by jb63126** [comment]
Sure do, updated it before this endeavor

**Comment by naimulh247** [comment]
can you join the discord from the [homepage](https://github.com/timgrossmann/InstaPy)? and ping @ga1i1e0 ?

**Comment by jb63126** [comment]
check and check

**Comment by dmsierra11** [comment]
I am having the same `Message: Unable to find a matching set of capabilities` and I also have Firefox installed, version 76.0.1 (64-bit)

**Comment by laforetcan** [comment]
Try this:
 `python3 -m pip install instapy --user`
