### ISSUE TITLE
Action blocked after a couple of actions using Instapy

### ISSUE THREAD

**Issue by brokenhamster321** [InstaPy/InstaPy#5473]
Hi all,

I have an issue with Instapy. I get blocked quite quickly and I do believe it has something to do with this error:

WARNING [2020-05-10 10:58:07] [123456]  - Hide Selenium Extension: error

Does anyone know how to solve this?

Thanks a lot in advance.😉

**Comment by ediziks** [comment]
I've faced the same issue a couple hours ago and then, found an alternative way to hide selenium webdriver on Firefox. To do that, some preferences on Firefox should be added in browser.py file.
You can try to extend your code with the script between ADDED tags -it's under the set_selenium_local_session function- to hide selenium and, also to change the browser platform to iPhone. Another platform might be needed if you use different user agents.

This setting is working on me for now but not sure if it's a temporary solution or not. So, let me know about the results on you. 

```
    # mute audio while watching stories
    firefox_profile.set_preference("media.volume_scale", "0.0")

    # ADDED
    firefox_profile.set_preference('dom.webdriver.enabled', False)
    firefox_profile.set_preference('useAutomationExtension', False)
    firefox_profile.set_preference('general.platform.override', 'iPhone')
    firefox_profile.update_preferences()
    # ADDED

    # prefer user path before downloaded one
    driver_path = geckodriver_path or get_geckodriver()
    browser = webdriver.Firefox(
        firefox_profile=firefox_profile,
        executable_path=driver_path,
        options=firefox_options)
```

**Comment by Tr1pke** [comment]
And this is the reason that this project ended more then a year ago ,,,

**Comment by ediziks** [comment]
Such bad news... I haven't searched about it hardly but, maybe Mozilla's https://github.com/mozilla/contain-facebook repo might give some clues on not tracking. Any idea @Tr1pke ?
