### ISSUE TITLE
Get Hashtag count? 

### ISSUE THREAD

**Issue by quintendewilde** [InstaPy/InstaPy#5475]
Hi, 

Is there a possibility to get a hashtag count of a certain #cat for example and throw me back the nummber, so I can put it in a database? 
And I would let the script run this just every 10minutes. 

I found a solution with Tools-for-Instagram but suddenly it stopped working and started throwing me errors. 

As Instapy always keeps on working I would like to use this tool. Only thing is my python skills are not that good to build this alone.. 

So would this be possible and secondly where would I look at best to get a hashtag count?

Thanks ahead!

**Comment by Jil-e** [comment]
I guess you can do it by using simple "for". Just make a counter with an exception "if".

**Comment by quintendewilde** [comment]
But what part of the InstaPy code make a pull for all the #cat in my
country (for example)?

Kind regards
