### ISSUE TITLE
Comparing followers and following lists

### ISSUE THREAD

**Issue by gypnofrog** [InstaPy/InstaPy#5478]
Hi! Can you help me?
The InstaPY documentation has this code example in the description of the "Grab Followers of a user" method ⬇️
   #get followers of "Popeye" and "Cinderella"
popeye_followers = session.grab_followers(username="Popeye", amount="full", live_match=True, store_locally=True)
sleep(600)
cinderella_followers = session.grab_followers(username="Cinderella", amount="full", live_match=True, store_locally=True)

   **#find the users following "Popeye" WHO also follow "Cinderella" :D**⬅️
popeye_cinderella_followers = [follower for follower in popeye_followers if follower in cinderella_followers]

I want to take the follower's subscribers, compare with my following and leave only those to whom I am not subscribed. How should I do it?

**popeye_cinderella_followers = [follower for follower in popeye_followers if follower in cinderella_followers]**
⬆️This method compares and finds the same. And how do I make a method that will compare and find different? Help me, please!

**Comment by yashwant121** [comment]
Pls clarify , Suppose X is following Y (Subject) .Y wants to compare X's followers with Y's followers =3 .Out of those 3 ,if Y is following 1, the output should be remaining 2.

**Comment by gypnofrog** [comment]
This is a bit different. 
I want to use the "Grab a user" (User1) followers method and get X. 
X = session.grab_followers (username = "User1", amount = "full", live_match = True, store_locally = True). 

Now I take my following users. I apply the "Grab method Following" of a user (mine). This is Y. Y is mine following users. 
Y = session.grab_following (username = "MY_Login", amount = "full", live_match = True, store_locally = True) 

Now you need to subtract Y from the list X and get Z. **Z = X-Y**. 

Please tell me how to get the list Z.

**Comment by tobeyond** [comment]
I got to do it adding NOT:

popeye_cinderella_non_followers = [follower for follower in popeye_followers if follower **not** in cinderella_followers]
