### ISSUE TITLE
"session.set_user_interact" doesn't work.

### ISSUE THREAD

**Issue by Jil-e** [InstaPy/InstaPy#5479]
Hi everyone! 
I have one Q about error that connected with photo list of user. The instapy says that this page is unavailable. Actually action "session.set_user_interact" doesn't work. Maybe you have some advises how to fix it?

**Comment by Tr1pke** [comment]
And it will never work since this project stopped more then a year ago

**Comment by tperas** [comment]
@Jil-e  It's related to the fact that you are having too much actions going to the user profile to check it. 
The project is still living, just need more people involved into it not just using it.

**Comment by mhdakhtar8** [comment]
I'm Learning python, would love to contribute to it once I know how... 😉
