### ISSUE TITLE
possible issue or maybe my fault in like

### ISSUE THREAD

**Issue by rugge89lau** [InstaPy/InstaPy#5480]
I guys. I use only like per hashtag and instagram stop me seeing user profile from webapp after just 1 hour of like cause i saw too many profile.

this because when bot search an hashtag and find a photo it open that photo, open the user profile of this photo re-open the photo and put the like. 

How can I prevent from visit profile and just put like to the photo?

this is my code:

session = InstaPy(username=insta_username,
                  password=insta_password,
                  browser_executable_path=r"C:\Program Files (x86)\Mozilla Firefox\firefox.exe",
                  headless_browser=False)

with smart_run(session):
    # settings
    session.set_do_comment(True, percentage=15)
    session.set_comments([':O'])
    session.set_quota_supervisor(enabled=True, sleep_after=["likes"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes_hourly=50,
                              peak_likes_daily=585,)

    # activity
    session.like_by_tags(
        ['tendermag', 'insomniamag','apricotmagazine','photooftheday','goodvibes','likeforlike'],
        amount=200, skip_top_posts=True)

**Comment by tperas** [comment]
@rugge89lau, i got this problem before because of some options which are checking the profile before acting like : 
- set_skip_user with the profile picture option
- set_relationship_bounds
- set_user_interact

Those options if configured or not can make the script check the user profile before action. As far as i was playing with it's raising the possibility of partial action blocking

**Comment by rugge89lau** [comment]
> @rugge89lau, i got this problem before because of some options which are checking the profile before acting like :
> 
> * set_skip_user with the profile picture option
> * set_relationship_bounds
> * set_user_interact
> 
> Those options if configured or not can make the script check the user profile before action. As far as i was playing with it's raising the possibility of partial action blocking

yeah but in my code none of those are present, so why keep check the profile?

**Comment by rugge89lau** [comment]
no one can say?
