### ISSUE TITLE
How not to retrieve followers and following lists every run?

### ISSUE THREAD

**Issue by tobeyond** [InstaPy/InstaPy#5481]
## Expected Behavior

Save followers and followings lists to use them again. Update those lists from time to time (to be set), saving time.
Example: save the non-following list and only refresh it when unfollowing all of them or every X days.

## Current Behavior

It retrieves followers and following lists every time I run the script, taking long (about half an hour). It doesn't save those lists for future usage.

**Comment by tobeyond** [comment]
Ideas?

**Comment by gypnofrog** [comment]
I wrote about this in the issue #5478. 
Look at this, maybe some ideas will come up.

**Comment by tobeyond** [comment]
I just realized it actually does save the files, still, it refreshes them every time. It would be nice to have an option of when to download it all again.
