### ISSUE TITLE
Action bloked

### ISSUE THREAD

**Issue by Strannik74** [InstaPy/InstaPy#5482]
Good evening!
The script fulfills 60 subscriptions and likes in 50 minutes.
I get a problem
### **Action bloked**
This action was blocked. Please try again later.
We restrict certain content and actions to protect our community.
Tell us if you think we made a mistake.

Changing ip does not help, the script does not work even through vpn.
I work through firefox
Tested on Linux and Windows one error

**Comment by tperas** [comment]
@Strannik74 some repetitive actions like checking the post owner profile can create this situation. 
Just wait some hours and you'll have access to it again. 
Try during this time to check your configuration and remove/reduce action that make the bot consult the owner profile.

**Comment by Strannik74** [comment]
> @ Strannik74 Некоторые повторяющиеся действия, такие как проверка профиля владельца сообщения, могут создать такую ​​ситуацию.
> Просто подождите несколько часов, и вы снова получите доступ к нему.
> Попробуйте в это время проверить свою конфигурацию и удалить / уменьшить действие, которое заставляет бота обращаться к профилю владельца.

Thank After a few hours, everything works again. Left the old settings for now
