### ISSUE TITLE
please solve this issue please!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Berus008** [InstaPy/InstaPy#5484]
No any custom workspace provided.       ~using existing..
InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"
WARNING [2020-05-12 20:58:10] [None]  Heeh! Error occurred while getting a DB profile for 'None':
        b'NOT NULL constraint failed: profiles.name'
Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    session = InstaPy()
  File "/home/kali/Desktop/InstaPy/instapy/instapy.py", line 308, in __init__
    get_database(make=True)  # IMPORTANT: think twice before relocating
  File "/home/kali/Desktop/InstaPy/instapy/database_engine.py", line 66, in get_database
    get_profile(name, address, logger) if profile_id is None or make else profile_id
  File "/home/kali/Desktop/InstaPy/instapy/database_engine.py", line 167, in get_profile
    profile = dict(profile)
TypeError: 'NoneType' object is not iterable

**Comment by IreneArapogiorgi** [comment]
Does your quickstart.py look like this?
```
""" Quickstart script for InstaPy usage """

# imports
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

# set workspace folder at desired location (default is at your home folder)
set_workspace(path=None)

# login credentials
insta_username = "your instagram username"
insta_password = "your instagram password"

# get an InstaPy session
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
      # your actions
```
Maybe that's not the issue, but just saying.

**Comment by tobeyond** [comment]
What it smart_run for?

**Comment by IreneArapogiorgi** [comment]
@tobeyond it is needed to apply your settings and activity of choice. [Here](https://github.com/InstaPy/instapy-quickstart/blob/master/quickstart.py#L26) is an example.

**Comment by Berus008** [comment]
> 
> 
> Does your quickstart.py look like this?
> 
> ```
> """ Quickstart script for InstaPy usage """
> 
> # imports
> from instapy import InstaPy
> from instapy import smart_run
> from instapy import set_workspace
> 
> # set workspace folder at desired location (default is at your home folder)
> set_workspace(path=None)
> 
> # login credentials
> insta_username = "your instagram username"
> insta_password = "your instagram password"
> 
> # get an InstaPy session
> session = InstaPy(username=insta_username,
>                   password=insta_password,
>                   headless_browser=False)
> 
> with smart_run(session):
>       # your actions
> ```
> 
> Maybe that's not the issue, but just saying.

yeah might be this but didnt get the opportunity to open this yet

**Comment by tobeyond** [comment]
I'm not using smart_run and it's working. I didn't get the difference.

**Comment by IreneArapogiorgi** [comment]
@tobeyond I didn't know about that, I've always used smart_run.

**Comment by Berus008** [comment]
so what's the solution of it?

**Comment by IreneArapogiorgi** [comment]
@Berus008 I thought it might had to do with quickstart.py, but if not then I don't know. Someone else might do.
