### ISSUE TITLE
unfollow_users problem

### ISSUE THREAD

**Issue by jedbanger** [InstaPy/InstaPy#549]
I've been getting problems when trying to use the unfollow_users feature. 
When the bot arrives to its followers modal in order to begin unfollowing, i get this error:

`selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div/div[2]/div/div[2]"}`

Anyone else getting this error? Has the xpath of the page changed?

Edit: Just to clarify, this problem did not appear to me before. The feature used to work alright.

**Comment by timgrossmann** [comment]
@jedbanger Please provide other users that face the same problem a quick instruction on how you solved your problem.

Thank you
- Tim
