### ISSUE TITLE
How do I like photos from my own News feed?

### ISSUE THREAD

**Issue by mhdakhtar8** [InstaPy/InstaPy#5492]
I'm looking for a script to like photos from my own News feed. Basically any media which is on my news feed s/b liked until it meets the condition.

Condition could be to run the script for certain amount of time or like certain number of posts.

Thanks and regards!

**Comment by IreneArapogiorgi** [comment]
I think you can use [like_by_feed()](https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#like-by-feeds).

**Comment by mhdakhtar8** [comment]
Yes, it's working like_by_feed().. One problem though - It's moving to the user's profile of every link it has captured and that's an extra step and I do not want it to go to the user profile. I want to save some quota server. How do I turn it off: avoid visiting the user profile?
