### ISSUE TITLE
ensure chromedriver is installed

### ISSUE THREAD

**Issue by sajinstories** [InstaPy/InstaPy#5493]
Chromedriver does not work

Hello,

I am having issues with running Instapy from Mac.

Workflow

- [DONE ] - Install Pythom 3.8.2
- [DONE ] - Install or Update Chrome (if needed)
- [DONE ] - Install brackets
- [DONE ] - Install InstaPy - Quickstart - Link
- [DONE ] - When blocked in Mac, go to settings, general and at the bottom of the window, click ‘open anyway’ next to installer.
- [DONE ] - Install command line developer tools - if needed
- [DONE ] - Then once InstaPy is installed, go back to ‘instapy-quickstart-master’ folder and right-click open ‘quickstart.py’ with Brackets. Save the file
- [DONE ] - Add Instagram credentials
- [PROBLEM] - Open the ‘Run’ folder and click the ‘mac start command’ script.

**Below is the message that is returned:**

Traceback (most recent call last):
  File "../quickstart.py", line 24, in <module>
    headless_browser=False)
  File "/Users/erui33/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 312, in __init__
    self.set_selenium_local_session()
  File "/Users/erui33/Library/Python/2.7/lib/python/site-packages/instapy/instapy.py", line 362, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: **ensure chromedriver is installed at /Users/erui33/Library/Python/2.7/lib/python/site-packages/instapy_chromedriver/chromedriver_mac64**

-----------------

I can confirm that Chromedriver is installed at that location, when trying to run Chromedriver, the following error message appears:

_‘Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code’._

-----------------

Question: What do I need to do here to get the command running. For example is it something with the ChromeDriver settings, port settings etc?

Thanks for your help,
Ben

**Comment by fduschka** [comment]
I have the exact same Issue!
