### ISSUE TITLE
[Errno 2] No such file or directory: '/tmp/tmpc3ow3glx'

### ISSUE THREAD

**Issue by DimIsaev** [InstaPy/InstaPy#5497]
Error starting instapy in docker

------
InstaPy Version: 0.6.8
 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
[Errno 2] No such file or directory: '/tmp/tmpc3ow3glx'

**Comment by samanmohamadi** [comment]
I have this issue which mentioned earlier #5389
I blieve that it is a bug because it occures every time (even with docker).
For me it occures at the end after logging stats. So if you put fewer rules in your script you will get it very soon.

**Comment by DimIsaev** [comment]
> So if you put fewer rules in your script you will get it very soon.

```

from instapy import InstaPy
from instapy.util import smart_run

insta_username = '***************'
insta_password = '***************'


bot = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
with smart_run(bot):

    bot.unfollow_users(amount=100, custom_list_enabled=False,  style="RANDOM", unfollow_after=55*60*60, sleep_delay=600)
    #use a desired occurrence percentage
    bot.set_simulation(enabled=True, percentage=66)
    bot.end()

```

my script has a minimum of rules

**Comment by eddyLazar** [comment]
any update on that have the same issue all the time with docker?

**Comment by DimIsaev** [comment]
the problem is relevant

**Comment by eddyLazar** [comment]
Does someone know if it is specific to Docker or not?

**Comment by DimIsaev** [comment]
@timgrossmann  

someone reads the problems?

**Comment by DimIsaev** [comment]
not solved this problem

**Comment by Jostino** [comment]
I have the same problem.

**Comment by elulcao** [comment]
> I have the same problem.

Try the latest version of InstaPy-Docker

**Comment by nath24** [comment]
Same problem on digitalOcean

**Comment by vadimmm** [comment]
i faced such issue in docker. after making a link to the local directory, the problem did not recur
