### ISSUE TITLE
Instantly Blocked

### ISSUE THREAD

**Issue by GabrieleAnsaldo** [InstaPy/InstaPy#5499]
Hello,
my profile gets blocked after more or less an hour. I am running on a Raspberry Pi 3 with Firefox esr. I only get blocked on Firefox on the raspberry, my insta account still works on my phone and on any other browser on my computer. 
Do you also experience this?

**EDIT: THIS WORKED FOR A BIT**
Try to delete cash from Firefox. Open Firefox-->Preferences-->Privacy-->Clear Cache

Then let Firefox not save cache anymore by doing so:
Type in the address bar about:config and press Enter (promise to be careful, if asked)
Type in the search bar : browser.cache
And look for the preferences :
browser.cache.disk.enable and browser.cache.memory.enable
Change their values to false
Then close and restart Firefox.

**Comment by natabega** [comment]
I have the same issue, I tried changes in firefox as @GabrieleAnsaldo suggest but it's not working

**Comment by xerZV** [comment]
Same here

**Comment by b2point0h** [comment]
Seeing the instant block as well. Tried the above fix to clear and not store cache, no dice.

**Comment by GabrieleAnsaldo** [comment]
So I actually found a fix if you really want to have an instagram bot. Basically instagram got very good at detecting bots so I tried to work around that. Basically I have connected my old android phone to the Raspberry (you can connect it to any computer) and I just send a bunch of adb commands to it. I wrote a little script. Its been working so well. 

I guess instagram finds it hard to find bots from someone using the app itself and not the browser version.

Hit me up if you are interested in developing this project with me, there is still a lot to do to make it very efficient.

**Comment by xerZV** [comment]
@GabrieleAnsaldo sounds great! looking forward to see what have u done

**Comment by GabrieleAnsaldo** [comment]
@xerZV I've been running this new bot for a few days and its working like a charm, super good! It would be great if someone with some more knowledge of python would be willing to help develop this project more. It has a lot of potential

**Comment by gvmturl** [comment]
> @xerZV I've been running this new bot for a few days and its working like a charm, super good! It would be great if someone with some more knowledge of python would be willing to help develop this project more. It has a lot of potential

Share your solution with the community, there are many developers interested on helping!

**Comment by GabrieleAnsaldo** [comment]
@xerZV Here is the repository with the files I am using, take a look: https://github.com/GabrieleAnsaldo/Andro-Insta-Bot.git

**Comment by xerZV** [comment]
@GabrieleAnsaldo Im getting 4o4

**Comment by GabrieleAnsaldo** [comment]
@xerZV https://github.com/GabrieleAnsaldo/Andro-Bot-Insta does it work now?

**Comment by xerZV** [comment]
Still getting insta ban

**Comment by GabrieleAnsaldo** [comment]
@xerZV You tried the code? I think you should set lower likes, I now run it 6 times a day for 3 hashtags and 34 likes which is 612 likes a day. But I am sure you can slowly increase the likes per day. If you need any help for the code hit me up!

**Comment by alexal1** [comment]
I had a look at @GabrieleAnsaldo code and saw hardcoded (x, y) coordinates, are they touch coordinates? They should be different for different devices then.

So consider this script: https://github.com/alexal1/Insomniac
It uses the same approach + UI Automator framework. Works fine on all devices (tested on two phones and one tablet)
