### ISSUE TITLE
Filter by media type

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#55]
Since Instagram has both videos and photos now, it would be nice to filter for media types. Otherwise, comments like “Great photo!” might seem akward when posted on videos.

**Comment by timgrossmann** [comment]
@tibor You're right, this could be a small check-feature... Like to only comment on photos

**Comment by foname** [comment]
I'll work on this ^^

**Comment by pekapa** [comment]
working on it; will make a PR soon.

**Comment by eduardocalazansjr** [comment]
@tibor @timgrossmann  what do you guys think of two distincts comments arrays? one for photos and one for videos?

**Comment by pekapa** [comment]
If we make two comments arrays we might break backward compatibility.
I believe there should be three arrays, a general one and two specific ones (photos e videos).

I'll wait for a definition to implement as a whole and only then I'll submit a PR.

**Comment by eduardocalazansjr** [comment]
Why three?
Keep the original and add another for vids.
If the second is empty, use the first for all cases.

**Comment by pekapa** [comment]
Suppose I have the following comments:

"Amazing" - for both classes
"Great video" - for videos
"Nice shot" - for photos

how would you arrange them in just two arrays? I can't see a way, unless I duplicate the "Amazing" into both arrays, or is there any other way?

**Comment by eduardocalazansjr** [comment]
#56 solves

**Comment by timgrossmann** [comment]
@vlntdds @pekapa I also think three would be better, since you don't want to have like 100's of comments duplicated at two different places

**Comment by pekapa** [comment]
Just submitted PR #68 
Just plain comments, didn't get to work with Spintax for now

**Comment by eduardocalazansjr** [comment]
It's better wait for the spintax implementation for this, isn't?

**Comment by timgrossmann** [comment]
mostly solved by #68
