### ISSUE TITLE
program does not run,

### ISSUE THREAD

**Issue by Cybersolution-inc** [InstaPy/InstaPy#5500]

**Comment by Cybersolution-inc** [comment]
The program does not run, it shows error 
Modulenotfounderror: no module named 'instapy'
please help

**Comment by tobeyond** [comment]
You need to install it prior to using it.
`pip install instapy` will do.

**Comment by laforetcan** [comment]
Try this `python3 -m pip install instapy --user`

**Comment by HFG1PRO** [comment]
Traceback (most recent call last):
  File "C:\Users\MG\Desktop\python\amigos.py", line 1, in <module>
    from instapy import InstaPy
ModuleNotFoundError: No module named 'instapy'
