### ISSUE TITLE
Weird behavior with follow_likers. Help!!

### ISSUE THREAD

**Issue by tobeyond** [InstaPy/InstaPy#5503]
## Current Behavior

When I use follow_likers, all kinds of weird information are collected as followers. Example:

> ['View all 9 comments', 'FEBRUARY 4', '62 others', 'LIKER1', 'MYFRIEND', '@ LIKER1', '#tbt', 'LIKER2']

(I replaced the usernames for LIKER1, LIKER2 and MYFRIEND). User1 appeared duplicated, with and without @. The friend I scrapped was listed. Hashtags, date etc. 

Then it makes my IG act in a bizarre way, trying to open links like "[https://www.instagram.com/View all 9 comments/](url)". I'm afraid I'll get blocked because of this. Anyway, it's a huge loss of time. 

Any ideas on how to fix this code?

**Comment by elulcao** [comment]
Same as #6352
