### ISSUE TITLE
Unable to find a matching set of capabilities (When ex

### ISSUE THREAD

**Issue by woobin0413** [InstaPy/InstaPy#5506]
## Expected Behavior

Expecting to see webdriver popping up and start running 

## Current Behavior
![image](https://user-images.githubusercontent.com/24215136/82169685-43e4c480-9890-11ea-8d48-d6acc0f7366d.png)

Anybody know what's the issue with this capabilities?

**Comment by ctrlsam** [comment]
It's saying that the downloaded driver (Geckodriver) isn't compatible with the Firefox version. This is happening for me. For some reason it downloads the 32bit version when it should download 64bit. Looking into it now.

**Comment by ctrlsam** [comment]
Update: I've found that the [`webdriverdownloader`](https://github.com/leonidessaguisagjr/webdriverdownloader) module is responsible for downloading the wrong bit type gecko driver. Have made a pull request [here](https://github.com/leonidessaguisagjr/webdriverdownloader/pull/11) which fixes this issue.

**Comment by dmsierra11** [comment]
> It's saying that the downloaded driver (Geckodriver) isn't compatible with the Firefox version. This is happening for me. For some reason it downloads the 32bit version when it should download 64bit. Looking into it now.

So I have to downgrade my firefox maybe? I have the latest version. Also, I have two versions installed because need an older one for a different task. How would I know which version it's using?

**Comment by dmsierra11** [comment]
> Update: I've found that the [`webdriverdownloader`](https://github.com/leonidessaguisagjr/webdriverdownloader) module is responsible for downloading the wrong bit type gecko driver. Have made a pull request [here](https://github.com/leonidessaguisagjr/webdriverdownloader/pull/11) which fixes this issue.

So it's still not clear to me... What's the solution?

**Comment by Ciriak** [comment]
@dmsierra11

One possible temp fix that worked for me was :

Download the latest 64bit geckodriver from here : https://github.com/mozilla/geckodriver/releases

Replace the **geckodriver.exe** present in `%userdir%\InstaPy\assets\gecko\v0.26.0`

Rename the folder `geckodriver-v0.26.0-win32` into `geckodriver-v0.26.0-win64` and also replace the **geckodriver.exe** present inside

This is a dirty temp fix for sure but it work ¯\\_(ツ)_/¯

**Comment by dmsierra11** [comment]
The issue for me is that I had multiple versions of Firefox installed and none of them were called ‘Firefox’ but ‘Firefox latest’ and ‘Firefox 58’. So I had to rename one of them to ‘Firefox’
