### ISSUE TITLE
Auto end session on error "Please wait a few minutes before you try again."

### ISSUE THREAD

**Issue by mhdakhtar8** [InstaPy/InstaPy#5510]
We all are aware of Instagram blocking the user from visiting any user profile after it hit a certain number of the server request. we use the quota supervision to get across that but it still happens.

Getting blocked is an entirely different topic of discussion, however, I believe the session should stop running after it encounters the error **"Please wait a few minutes before you try again."** automatically to avoid any more hits and generate the end log as it does for successfully run

## Expected Behavior
End session as soon as the error is encountered
Generate log: # of likes, follow, comment, etc....

## Current Behavior
Keeps running despite the error and result in failure of following/unfollow a user

## Possible Solution (optional)
set criteria check for the error and allow the user to end the session if set to enabled

![image](https://user-images.githubusercontent.com/16105609/82327865-ab1f8780-99fc-11ea-9992-1d83c1c56ab8.png)

**Comment by riccardovalente** [comment]
I have something very crude. It works like `tail`, you pass it the `general.log` file path. It will scan the output and notify of detected blocks and optionally kill `quickstart.py` (change `maxblocks` and `kill` to suit you). I'm not a python developer, so there will be better ways of doing this.


```#!/usr/bin/python3

import sys, time, os, re

maxblocks = 3
kill = True

# Set the regex list that may indicate a block
regexList = [
    "Last follow is not verified",
    "Last unfollow is not verified",
    "You are have a BLOCK on",
    "You have a BLOCK on",
    "temporarily blocked from",
    "serious issue: 'temporary block'",
    "maybe blocked",
    "Traceback",
]


# Set the filename and open the file
logfile = sys.argv[1]

file = open(logfile, "r")

# Find the size of the file and move to the end
st_results = os.stat(logfile)
st_size = st_results[6]
file.seek(st_size)

blockcount = 0

while 1:
    where = file.tell()
    line = file.readline()
    if not line:
        time.sleep(1)
        file.seek(where)
    else:
        sys.stdout.write(line)
        gotMatch = False
        for regex in regexList:
            s = re.search(regex, line)
            if s:
                gotMatch = True
                break
        if gotMatch:
            if regex == 'Traceback':
                print("** exception detected **")
            else:
                print("** possible block detected **")
                if kill:
                    if blockcount >= maxblocks:
                        print("** killing session**")
                        os.system("/usr/bin/pkill quickstart.py)
                    else:
                        blockcount += 1```

**Comment by evertonmdz** [comment]
> I have something very crude. It works like `tail`, you pass it the `general.log` file path. It will scan the output and notify of detected blocks and optionally kill `quickstart.py` (change `maxblocks` and `kill` to suit you). I'm not a python developer, so there will be better ways of doing this.
> 
> ```
> 
> import sys, time, os, re
> 
> maxblocks = 3
> kill = True
> 
> # Set the regex list that may indicate a block
> regexList = [
>     "Last follow is not verified",
>     "Last unfollow is not verified",
>     "You are have a BLOCK on",
>     "You have a BLOCK on",
>     "temporarily blocked from",
>     "serious issue: 'temporary block'",
>     "maybe blocked",
>     "Traceback",
> ]
> 
> 
> # Set the filename and open the file
> logfile = sys.argv[1]
> 
> file = open(logfile, "r")
> 
> # Find the size of the file and move to the end
> st_results = os.stat(logfile)
> st_size = st_results[6]
> file.seek(st_size)
> 
> blockcount = 0
> 
> while 1:
>     where = file.tell()
>     line = file.readline()
>     if not line:
>         time.sleep(1)
>         file.seek(where)
>     else:
>         sys.stdout.write(line)
>         gotMatch = False
>         for regex in regexList:
>             s = re.search(regex, line)
>             if s:
>                 gotMatch = True
>                 break
>         if gotMatch:
>             if regex == 'Traceback':
>                 print("** exception detected **")
>             else:
>                 print("** possible block detected **")
>                 if kill:
>                     if blockcount >= maxblocks:
>                         print("** killing session**")
>                         os.system("/usr/bin/pkill quickstart.py)
>                     else:
>                         blockcount += 1```
> ```

I'm a layman and I didn't understand what to do and where to make this change! Could you help us? Because that night was 6 hours on the screen "Please wait a few minutes before you try again."
