### ISSUE TITLE
BUG: isitdownorjust.me does not work /Scripts fails

### ISSUE THREAD

**Issue by spacemishka** [InstaPy/InstaPy#5512]
https://github.com/timgrossmann/InstaPy/wiki -->
## Expected Behavior
Avaibility check should work with other platforms or just execute the script, when HTTP COde 500 is returned
## Current Behavior
Script does not run because https://isitdownorjust.me/instagram-com/ returns Error 500
## Possible Solution (optional)
Catch 500 and check against another service,..or just run the script anyway
####

**Comment by ekutner** [comment]
Yes, it is failing 90% of the times. You can bypass the check by setting want_check_browser=False on the InstaPy constructor. Like this:

session = InstaPy(username='xxxx', password='yyyy', want_check_browser=False)

**Comment by spacemishka** [comment]
ok, thanks. Havent seen this parameter.
