### ISSUE TITLE
link_elems error local variable 'post_href' referenced before assignment

### ISSUE THREAD

**Issue by mhdakhtar8** [InstaPy/InstaPy#5513]
I'm trying to use "interact by comments" however I'm running into this error when at the user screen.

_Just to mention that same configuration is working on other tags_

Sharing my Log and script

## Log
NFO [2020-05-20 23:10:53] [akkigraphy]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
................................................................
INFO [2020-05-20 23:11:04] [akkigraphy]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2020-05-20 23:11:04] [akkigraphy]  Saving account progress...
___________________________________________________________________________
INFO [2020-05-20 23:11:20] [akkigraphy]  Starting to interact by comments..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
::::::::::::::::::::::::::::::::::::::::::::::::::::
INFO [2020-05-20 23:11:20] [akkigraphy]  User: [1/1]
INFO [2020-05-20 23:11:49] [akkigraphy]  Getting varun.aditya image list...
ERROR [2020-05-20 23:12:17] [akkigraphy]  link_elems error local variable 'post_href' referenced before assignment
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2020-05-20 23:12:20] [akkigraphy]  Post: [1/5]
INFO [2020-05-20 23:12:24] [akkigraphy]  Image from: b'varun.aditya'
INFO [2020-05-20 23:12:24] [akkigraphy]  Link: b'https://www.instagram.com/p/B_gvEraHOEQ/'
INFO [2020-05-20 23:12:24] [akkigraphy]  Description: b'Let\xe2\x80\x99s look at some Family Moments ! \nLa Familia \xe2\x9d\xa4\xef\xb8\x8f #varunaditya #varunadityaphotography #expandedexpeditions #nature #wildlife #wild #wildlifephotography #sonyalphian #sonyalpha #sonyartisan #wildlifephotographer #animal #family #lafamilia #light #composition #clouds #sunrise #love #mother #photooftheday #picoftheday #instagram #instagood #nofilter'
INFO [2020-05-20 23:12:25] [akkigraphy]  Failure
INFO [2020-05-20 23:12:25] [akkigraphy]  No interaction did happen.


## InstaPy configuration

`from instapy import InstaPy

insta_username = ''
insta_password = ''

# if you want to run this script on a server,
# simply add nogui=True to the InstaPy() constructor
session = InstaPy(username=insta_username, password=insta_password, want_check_browser=False)
session.login()

# set up all the settings
session.set_relationship_bounds(enabled=False,
				 potency_ratio=-1.5,
				  delimit_by_numbers=False,
				   max_followers=4590,
				    max_following=5555,
				     min_followers=45,
				      min_following=77)

session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes_hourly=57,
                              peak_likes_daily=585,
                               peak_comments_hourly=21,
                               peak_comments_daily=182,
                                peak_follows_hourly=48,
                                peak_follows_daily=None,
                                 peak_unfollows_hourly=35,
                                 peak_unfollows_daily=402,
                                  peak_server_calls_hourly=400,
                                  peak_server_calls_daily=3500)


session.set_dont_include(['friend1', 'friend2', 'friend3'])
session.set_dont_like(['pizza', 'girl','boy','bitcoin','comic','cartoor','dude','babe','nude','faishon','food','lifestyle','shiv'])
session.set_do_follow(enabled=True, percentage=70, times=1)
session.set_skip_users(skip_bio_keyword = [' Order', 'visa', 'paypal','media','content','follow','pet','free','model','company','Media'])

# session.like_by_feed(amount=100, randomize=False, unfollow=False, interact=False)

""" Unfollow user
"""

# session.unfollow_users(amount=100, instapy_followed_enabled=True, instapy_followed_param="nonfollowers", style="FIFO", unfollow_after=48*60*60, sleep_delay=601)


session.set_do_comment(True, percentage=70)
session.set_comments(['Nice!', 'Lovely', 'Surreal!', 'Beautiful', 'Shandaar :thumbsup:', 'Nice Shot!', 'Lovely Shot!', 'Wow!', 'What lens did you use?', 'What gear?'])

session.interact_by_comments(usernames=["varun.aditya"],
                             posts_amount=5,
                             comments_per_post=5,
                             reply=False,
                             interact=True,
                             randomize=True,
                             media="Photo")

# end the bot session
session.end()
`

**Comment by Sandz1** [comment]
Hi @mhdakhtar8 
 i started using instapy with the comments, likes an follow options. 
the only error displayed : 
>  link_elems error local variable 'post_href' referenced before assignment 

it is logging on, finding the pages requested as per hashtag or userid. it is scrolling through the content and finding the post. But unable to interact with the user or post. 

> INFO [2020-06-15 01:44:15] [capt_] username=straysmatter could not get interacted

INFO [2020-06-15 01:44:15] [capt_]  Getting straysmatter image list...
ERROR [2020-06-15 01:44:19] [capt_]  link_elems error local variable 'post_href' referenced before assignment


> INFO [2020-06-15 01:44:52] [capt_]  Finished interacting on total of 15 images from 3 users! xD

INFO [2020-06-15 01:44:52] [capt_]  Liked: 0
INFO [2020-06-15 01:44:52] [capt_]  Already Liked: 0
INFO [2020-06-15 01:44:52] [capt_]  Commented: 0
INFO [2020-06-15 01:44:52] [capt_]  Followed: 0
INFO [2020-06-15 01:44:52] [capt_]  Already Followed: 0
INFO [2020-06-15 01:44:52] [capt_]  Inappropriate: 0
INFO [2020-06-15 01:44:52] [capt_]  Not valid users: 0

Not sure why its not interacting. i tried to search for this error but didnot find a solution. 

Are you able to use instapy in any mode ? 
Are there any tweaks to carry out once we download it ? 

Thanks in advance
