### ISSUE TITLE
Follow and Comment not workiing

### ISSUE THREAD

**Issue by ShahidTariq** [InstaPy/InstaPy#5518]
## Expected Behavior
Should LIke follow and comment
## Current Behavior
INFO [2020-05-21 20:14:02] [xxxxxxxxxxxxxxxxxxxxxxx]  --> Image Liked!
INFO [2020-05-21 20:14:06] [xxxxxxxxxxxxxxxxxxxxxxx]  --> Not commented
INFO [2020-05-21 20:14:07] [xxxxxxxxxxxxxxxxxxxxxxx]  --> Not following
INFO [2020-05-21 20:14:08] [xxxxxxxxxxxxxxxxxxxxxxx]  Like# [2/11]

## Possible Solution (optional)
Is this the problem with xpath
## InstaPy configuration

session.set_do_like(enabled=True, percentage=70)
session.like_by_tags(["fashion", "travel"], amount=5)
session.set_do_comment(enabled=True, percentage=70)
session.set_do_follow(enabled=True, percentage=70)

**Comment by ShahidTariq** [comment]
Here, Can somebody help me here. I am running a instapy script to follow and comment users but it only does like no comment and follow is done.

**Comment by sipani909** [comment]
You have a percentage set to 70? In that case it will only like 70% of posts. Are you saying it did not comment on 100% of the posts? Please attach log here.

**Comment by ekutner** [comment]
comments won't work because Instagram changed their code and Instapy needs an update to fix it. I've posted a pull request with the required fix + a few new features and it should be ok as soon as the pull request is merged.

**Comment by lucasmirachi** [comment]
You must set configuration BEFORE call activity.
Try to change your code like the one bellow:

```
from instapy import InstaPy
session = InstaPy(username="your_username", password="your_password", headless_browser=False)
session.login()

#First you define the settings
session.set_do_follow(enabled=True, percentage=70)
session.set_do_comment(enabled=True, percentage=70)
session.set_comments(["Comment1","Comment2","Comment3"])
session.set_do_like(enabled=True, percentage=70)

#Then you set the activity
session.like_by_tags(["fashion", "travel"], amount=5)

session.end()
```

Hope this helps you =)

**Comment by FernandoAOliveira** [comment]
Hello!
I tried your option and in my contine with this problem when commenting:

`  --> Image Liked!
Traceback (most recent call last):
  File "quickstart.py", line 12, in <module>
    session.like_by_tags(["fashion", "travel"], amount=5)
  File "/home/fao/.local/lib/python3.8/site-packages/instapy/instapy.py", line 1972, in like_by_tags
    success = process_comments(
  File "/home/fao/.local/lib/python3.8/site-packages/instapy/comment_util.py", line 431, in process_comments
    if not commenting_approved:
UnboundLocalError: local variable 'commenting_approved' referenced before assignment`
