### ISSUE TITLE
help in comments

### ISSUE THREAD

**Issue by pedrovcampos** [InstaPy/InstaPy#5520]
I'm doing a simple application to follow and comment but I'm having the following error

![error2](https://user-images.githubusercontent.com/65798444/82720256-1a5cdc00-9c88-11ea-8126-08ebbc0f5980.jpg)

the login and password are correct but this is giving an error which can help thank you

![error](https://user-images.githubusercontent.com/65798444/82720247-ee415b00-9c87-11ea-8c85-d5b9ff640502.jpg)

**Comment by Fjsmoreira** [comment]
Hi, 
The code you posted is not the one running.
you're invoking set_do_comments instead of set_do_comment

**Comment by pedrovcampos** [comment]
> Hi,
> The code you posted is not the one running.
> you're invoking set_do_comments instead of set_do_comment

### **thank you very much that's right my problem with your help get it resolved thank you**
