### ISSUE TITLE
Run on Android / close Firefox window

### ISSUE THREAD

**Issue by tobeyond** [InstaPy/InstaPy#5524]
Does anyone run the script on the phone (Android)? 
If yes, how?

Also, how can I manage to close the Firefox window when my script stops because of an error (both PC and phone)?
So then I can make it restart (it doesn't work on my computer if an old window is still open, so I need to close it first).

Thanks!

**Comment by mrallanodreman** [comment]
Termux my friend

**Comment by enrifer** [comment]
@mrallanodreman can you explain how to use it on termux? "pip install instapy" some errors are occuring...

Would prefer using it on Android than on PC 🙏

**Comment by ghost** [comment]
https://medium.com/@erfanghaffarie/install-and-running-instapy-on-android-b4b8dae85d5f check this out
