### ISSUE TITLE
Not able to do comments.

### ISSUE THREAD

**Issue by s1de21** [InstaPy/InstaPy#5535]
The bot works great but i can't figure out how to comment:

this is my config:

  session.set_do_comment(enabled=True, percentage=100)
  session.set_comments(['Awesome', 'Really Cool', 'I like your stuff'])

hope someone can give me a hint

**Comment by FunkyRobot73** [comment]
same here ...   I can get it to follow and like pictures but after a few weeks no comments.

**Comment by QuarkSplit** [comment]
Same issue, I too am asking for help

**Comment by romain-bsn** [comment]
Hi,
Try this 
session.set_do_comments(True, percentage=100)
 
session.set_comments(["Awesome", "Really Cool", "I like your stuff"])
 
session.like_by_tags(["hashtag", "hashtag2"], amount=5)

**Comment by FunkyRobot73** [comment]
I'm using this...  I got it from templates.  Just never ever comments or follows.  ever.  Not sure why.  It likes exactly as I expect but that's it.

Any help would be appreciated.

"""
This template is written by @timgrossmann
What does this quickstart script aim to do?
- This script is automatically executed every 6h on my server via cron
"""

import random
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'user'
insta_password = 'password'

dont_likes = ['sex', 'nude']

friends = ['user']

like_tag_list = ['marvel', 'DC', 'comics',
                 'DCComics', 'MCU']

# prevent posts that contain some plantbased meat from being skipped
ignore_list = ['jesus', 'catholic', 'church']

accounts = ['mountain.tire']

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

with smart_run(session):
    # settings
    session.like_by_locations(['8372883/hamilton-ontario/'], amount=100)

    session.set_relationship_bounds(enabled=True,
                                    max_followers=15000)

    session.set_dont_include(friends)
    session.set_dont_like(dont_likes)
    session.set_ignore_if_contains(ignore_list)

    session.set_user_interact(amount=3, randomize=True, percentage=90)
    session.set_do_follow(enabled=True, percentage=66)
    session.set_do_comment(True, percentage=100)
    session.set_comments(['Nice pic! @{}',
        'Awesome! @{}',
        "That's pretty cool",
        'Just awesome.',
        'I just love being a nerd.',
        'Cool @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Nice @{}',
        'Yes!',
        'Pretty cool! @{} :muscle:',
        'coolest thing today'])
    session.set_do_like(enabled=True, percentage=80)

    # activity
    session.like_by_tags(random.sample(like_tag_list, 3),
                         amount=random.randint(50, 100), interact=True)

    session.unfollow_users(amount=random.randint(75, 150),
                           InstapyFollowed=(True, "all"), style="FIFO",
                           unfollow_after=90 * 60 * 60, sleep_delay=501)

    """ Joining Engagement Pods...
    """
    photo_comments = ['Nice shot! @{}',
        'Awesome! @{}',
        "That's pretty cool",
        'Just awesome.',
        'I just love being a nerd.',
        'Cool @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Nice @{}',
        'Yes!',
        'Pretty cool! @{} :muscle:']

    session.set_do_comment(enabled = True, percentage = 95)
    session.set_comments(photo_comments, media = 'Photo')
    session.join_pods(topic='sports', engagement_mode='normal')

**Comment by Karan-Ghatt** [comment]
@TheFakeWater  Hi, I tried your solution and it didn't work. I still seem to be facing the same issue.
using windows 10 and python 3.7.7
Code being used: 
    session.set_user_interact(amount=3, randomize=False, percentage=100)
    session.like_by_tags(['LofiBeats'], amount=5, interact=True)
    session.set_do_comment(enabled=True, percentage=33,)
    session.set_comments(['Check out my page for some DOPE LoFi Beats!'])

session.end()

The code like the correct images, again no commenting. Not too sure whats going on.
Any insight would be awesome!

**Comment by romain-bsn** [comment]
You need to put like by tags function after all your code

**Comment by Karan-Ghatt** [comment]
So, something like this?

` session.set_user_interact(amount=4, randomize=False, percentage=100)
    session.set_do_comment(enabled=True, percentage=25)
    session.set_comments([comment1, comment2, comment3])
    session.like_by_tags([hashtag], amount=5, interact=True)`

This code still dose not seem to be commenting on the posts. 
Thank you for your insight!! I've been struggling with this for days!
