### ISSUE TITLE
Option to prevent double/triple-commenting?

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#554]
I run the script 1-2 times a day on a handful of somewhat niche hashtags, and occasionally, thanks to random chance, it will comment on the same photo three or four times.

Is there a way to check if I have commented on a photo before I do it again? I think I can probably write this myself but I wanted to make sure I wasn't reinventing the wheel.

**Comment by ahmadudin** [comment]
@WillManidis I dont understand how double commenting can happen. If you read the code, Image that already liked cannot be commented on again. Unless you unlike it. cmiiw.

**Comment by ghost** [comment]
@ahmadudin that's what I'm unsure about also -- but I end up seeing photos where when I run the script a handful of times they all end up with three or four comments on them.

**Comment by ahmadudin** [comment]
@WillManidis i think for now, lets wait and see if there is any other people getting this issue

**Comment by ghost** [comment]
@ahmadudin Okay so I've done some digging around and figured out what's happening, just not how to fix it. On the photos where I am seeing multiple-comments they are also the only photos not being liked.

**Comment by timgrossmann** [comment]
@WillManidis Well this is really weird... Sounds like you got yourself a "Like-Ban" for some time where the script actually wanted to like the pic but Instagram rejected it...

There shouldn't be another reason this is happening...

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
