### ISSUE TITLE
Geckodriver. exe doesn't work

### ISSUE THREAD

**Issue by Tatuck** [InstaPy/InstaPy#5542]
ERROR: raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service .\geckodriver.EXE unexpectedly exited. Status code was: 3221225595

I have installed Firefox and geckodriver as in #5337 but when i try to install geckodriver it said that the program haven't been started succesfully. 

My file: 
```
# imports

from instapy import InstaPy

from instapy import smart_run

# login credentials

insta_username = 'acc'

insta_password = 'pass.'
session = InstaPy(username=insta_username,

                  password=insta_password,

                  headless_browser=False)



with smart_run(session):

    """ Activity flow """

    



    # activities



    """ Massive Follow of users followers (I suggest to follow not less than

    3500/4000 users for better results)...

    """

    session.follow_user_followers(['user1', 'user2', 'user3'], amount=800,

                                  randomize=False, interact=False)
```

**Comment by Tatuck** [comment]
Now i think that error was because i had the geckodriver installer in the same directory. Now i have deleted it but it shows me this error:
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by romain-bsn** [comment]
What is your firefox version?

**Comment by MrTob** [comment]
same error, here

**Comment by pabs24** [comment]
hi i am getting same error. any news?
