### ISSUE TITLE
Action blocked

### ISSUE THREAD

**Issue by AnantTan** [InstaPy/InstaPy#5545]
It keep saying that the action is blocked for my account. When it is working fine on my phone. Is there a fix for it ?

**Comment by raymondhuynh1988** [comment]
youre being IP blocked or its being detected you are using automation software

**Comment by AnantTan** [comment]
So, is there any fix to it ?

**Comment by fityanto17** [comment]
no, its blocked. you need to wait like 2-4 days

**Comment by alexal1** [comment]
> When it is working fine on my phone

I recommend you to try https://github.com/alexal1/Insomniac if your phone is Android.
It's like InstaPy, but for mobile devices. I've noticed that Instagram became very suspicious to actions on Web version, but it can't distinguish humans from bots when it comes to mobile devices.

**Comment by marciomvm** [comment]
Same here. After 5 minutes using I got Blocked action. Any Advice?

**Comment by pherde** [comment]
> Same here. After 5 minutes using I got Blocked action. Any Advice?

A not very good solution is to delete the cookies: _~/InstaPy/logs/youruser/yourues_cookie.pkl_
