### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by andrefilipesp** [InstaPy/InstaPy#5547]
Hi guys. so when I try to run Instapy this error appears. Anyone knows what it can be?

![instapy error](https://user-images.githubusercontent.com/49796779/83909892-85ff7880-a761-11ea-9a0a-8ff1cf4b962b.png)

**Comment by stanislavkozlovski** [comment]
It's something related to the Firefox driver you're using. I had the same problem and instead of playing around, I just edited the code to use a Chrome driver that I know works well

**Comment by andrefilipesp** [comment]
> It's something related to the Firefox driver you're using. I had the same problem and instead of playing around, I just edited the code to use a Chrome driver that I know works well

The thing is, I don't even have firefox installed. Can that be related?

**Comment by romain-bsn** [comment]
Hi,
Install a firefox version compatible with your geckodriver.
Also check if your geckodriver is in your path

**Comment by andrefilipesp** [comment]
> Hi,
> Install a firefox version compatible with your geckodriver.
> Also check if your geckodriver is in your path

Problem solved! Thank you!
