### ISSUE TITLE
Unable to login to Instagram! You will find more information in the logs above.

### ISSUE THREAD

**Issue by renanzinth1** [InstaPy/InstaPy#5552]
INFO [2020-06-06 16:21:32] [r2bhub]  Session started!
INFO [2020-06-06 16:21:32] [r2bhub]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2020-06-06 16:21:36] [r2bhub]  - Internet Connection Status: ok
INFO [2020-06-06 16:21:36] [r2bhub]  - Current IP is "191.249.216.18" and it's from "Brazil/BR"
INFO [2020-06-06 16:21:36] [r2bhub]  -- Connection Checklist [2/3] (Instagram Server Status)
WARNING [2020-06-06 16:21:45] [r2bhub]  - Instagram Server Status: error
CRITICAL [2020-06-06 16:21:45] [r2bhub]  Unable to login to Instagram! You will find more information in the logs above.
INFO [2020-06-06 16:21:45] [r2bhub]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2020-06-06 16:21:45] [r2bhub]  - Internet Connection Status: ok
INFO [2020-06-06 16:21:45] [r2bhub]  - Current IP is "191.249.216.18" and it's from "Brazil/BR"
INFO [2020-06-06 16:21:45] [r2bhub]  -- Connection Checklist [2/3] (Instagram Server Status)
WARNING [2020-06-06 16:21:53] [r2bhub]  - Instagram Server Status: error
CRITICAL [2020-06-06 16:21:53] [r2bhub]  Unable to login to Instagram! You will find more information in the logs above.

I got this error. Someone can help me?

**Comment by tiagoassun** [comment]
I have the same error.

There is a Pull Request (#5553 ) saying that the problem is checking the status of the Instagram server ("Instagram Server Status: error"). According to Pull Request, this site is used here to validate the status of the server (https://isitdownorjust.me/instagram-com/) but this site is not so reliable, as it almost always informs that Intagram is down.

**Comment by iwoonder** [comment]
I have the same error !!!

**Comment by giovannipiccinelli** [comment]
same here!!

**Comment by tiagoassun** [comment]
Ther Pull Request (#5553 ) was accepted. And now it works again here.
