### ISSUE TITLE
Login Problem (You have entered an invalid engagement_mode for pods, allowed engagement_modes are : ['light', 'normal', 'heavy']. Exiting...)

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5558]
This is what it displays. I am running this on Mac, does anyone know how to resolve it?

.......................................................................................................................
CRITICAL [2020-06-10 13:21:44] [ianisacat]  Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2020-06-10 13:21:44] [ianisacat]  You have entered an invalid engagement_mode for pods, allowed engagement_modes are : ['light', 'normal', 'heavy']. Exiting...

**Comment by rpesce** [comment]
From the error I assume that you supplied an engagement_mode that is not 'light', 'normal', or 'heavy'. It was supposed to accept 'no_comments' as well, is this what you tried? Check here for more details: https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#parameters-6
