### ISSUE TITLE
bot doesn't comment : "UnboundLocalError: local variable 'commenting_approved' referenced before assignment"

### ISSUE THREAD

**Issue by zentamarina** [InstaPy/InstaPy#5559]
## Expected Behavior
comment on post when activity is like_by_tags

## Current Behavior
bot likes photo but exits with the following error when trying to comment:

File "/Users/InstaPy-master/instapy/comment_util.py", line 411, in process_comments
    if not commenting_approved:
UnboundLocalError: local variable 'commenting_approved' referenced before assignment

## InstaPy configuration
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session)
  session.set_do_follow(True, percentage=100)
  session.set_do_comment(True, percentage=100)
  session.set_comments(['Nice!','Cool!']
  session.set_do_like(enabled=True, percentage=100)
  session.set_user_interact(amount=3, randomize=True, percentage=100)

  session.like_by_tags(["sunset"], amount=10,interact=True)

**Comment by CodePoetPro** [comment]
Having the same issue.

**Comment by ofernander** [comment]
Same issue on latest release.

**Comment by psius1** [comment]
I was having the same issue. I downgraded Instapy to 0.6.8 now its working..

**Comment by 5pwn** [comment]
I have the same issue. It was working great until I upgraded and now it crashes anytime I try to use comments. Works perfect without the comment scripts. I have tried all the other community comment scripts and nothing works.

**Comment by 5pwn** [comment]
I solved the issue by downgrading as well. Just type this into cmd, `pip install instapy==0.6.8
` and make sure none of the comments have `@{}`. Having `@{}` is causing it to crash for some reason. It wasn't the case before.

**Comment by azaitsev** [comment]
try to add:
`session.set_delimit_commenting(enabled=True, max_comments=10000, min_comments=0)`

it shouldn't affect your flow but will be a workaround

**Comment by Sebadier** [comment]
Line 431-433 of comment_util.py should go one tab to the right because they belong to the delimit_commenting option.

**Comment by fberbert** [comment]
> try to add:
> `session.set_delimit_commenting(enabled=True, max_comments=10000, min_comments=0)`
> 
> it shouldn't affect your flow but will be a workaround

Worked for me, thanks!

**Comment by itsvaibhav01** [comment]
Downgrading to 0.6.8 version helped me !!
