### ISSUE TITLE
Can not open quickstart.py

### ISSUE THREAD

**Issue by Psychonics** [InstaPy/InstaPy#556]
![capture](https://user-images.githubusercontent.com/31060084/29350934-275c1f30-8226-11e7-9784-718a74e4a9a8.PNG)
Any ideas on what to do??

**Comment by timgrossmann** [comment]
@Psychonics If you look at the path of your CMD-prompt, it says that you're at `C://Users/Ting`, but you're not in the InstaPy-master folder, where the quickstart is located.

Try another `cd InstaPy-master` before calling `py quickstart.py`

**Comment by Psychonics** [comment]
Thank you
