### ISSUE TITLE
Timed out with failure while explicitly waiting until visibility of element located!

### ISSUE THREAD

**Issue by Cromer17** [InstaPy/InstaPy#5566]
## Expected Behavior
Login to my account

## Current Behavior
The login doesn't work, after login in manually I get the following message:

`"Timed out with failure while explicitly waiting until visibility of element located!"`

```
"Traceback (most recent call last):
  File "../quickstart.py", line 32, in <module>
    with smart_run(session):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 115, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield"
```

## InstaPy configuration

I didn't touch anything, all as default

[20200615-010816.txt](https://github.com/timgrossmann/InstaPy/files/4777991/20200615-010816.txt)

Thanks!

**Comment by alezlam** [comment]
i'm having the same problem here, may i know how do you fixed it ?

**Comment by Cromer17** [comment]
> i'm having the same problem here, may i know how do you fixed it ?

It was solved by itself after restarting my computer and trying some days after!

**Comment by SanielDous** [comment]
I'm facing the same or similar issue on my raspberry pi. Rebooting and switching account does not help :(

**Comment by mandyedi** [comment]
I have the same issue on a Digital Ocean droplet with Ubuntu 20.04 (LTS) x64.
I installed InstaPy using this tutorial: 
[https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_To_DO_Ubuntu_on_Digital_Ocean.md](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_To_DO_Ubuntu_on_Digital_Ocean.md)

**Comment by ove1kenobi** [comment]
I also struggled with this issue for a while. It turned out that I had to click the **Accept** link, log in manually and save account info the first time I ran the bot. Thereafter everything seems to function as expected with no need for manual interaction. Hope this will help someone.
