### ISSUE TITLE
Trying to like media: [number], Not liked: 400

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#557]
Hey everyone,

I'm new to the community so I'm sorry if the tone or the info provided by me here isn't sufficient.

Today I ran InstaPy on pytonanywhere. I set it up only to like and follow/unfollow, but it has problems with the former. While it does follow without problems, when it tries to like it gives the following message:
![not liked](https://user-images.githubusercontent.com/31061724/29352971-f85af7cc-8268-11e7-83f7-0a4394ce7ccb.PNG)

Here are my settings (and mode 0):
![example](https://user-images.githubusercontent.com/31061724/29352972-f85b128e-8268-11e7-9ba8-225594a72c2a.PNG)

I can like on a browser or in apps so the problem isn't a result of a ban.

I've noticed someone had the same problem in the #414 thread, but he didn't seem to cooperate ;). What would you suggest I do? 

Thanks for your time!

**Comment by keivan85** [comment]
This is not the instaPy repo. Your are using instabot.py repo.

**Comment by ghost** [comment]
You're absolutely right, sorry for the mistake. I googled the problem, ended up here at #414 and didn't check it. 

Sorry again!
