### ISSUE TITLE
view-source:https://ip4.seeip.org/geoip - Not loading

### ISSUE THREAD

**Issue by premchugh** [InstaPy/InstaPy#5572]
SEEIP.ORG is not loading. This is causing a startup issue for the account.

Also, when I tried to change the code to refer to Whatsmyip.org, it threw me an exception: Internet Connection Status: error.

    try:
        logger.info("-- Connection Checklist [1/2] (Internet Connection Status)")
        browser.get("view-source:https://www.whatsmyip.org/")

instead of 

    try:
        logger.info("-- Connection Checklist [1/2] (Internet Connection Status)")
        browser.get("view-source:https://ip4.seeip.org/geoip")

What is the program looking for in https://ip4.seeip.org/geoip which it cannot find in https://www.whatsmyip.org.

Please help.

**Comment by premchugh** [comment]
I realized that seeip.org provides API services which whatsmyip does not provide. Please do not judge me, I'm very new to Python.

I found a different ipify API provider. So is there a way I can integrate with them or I need to wait until seeip.org is up and running ?

**Comment by williamp0044** [comment]
Posting a reply in the hopes that there is a solution and I get notified.

**Comment by julianofnascimento** [comment]
To skip the ip check you can set the variable "want_check_browser" to False.
