### ISSUE TITLE
browser = webdriver.Firefox( TypeError: __init__() got an unexpected keyword argument 'options'

### ISSUE THREAD

**Issue by pikki1** [InstaPy/InstaPy#5573]
Hi! I´m trying to run instapy on https://www.pythonanywhere.com and I always have this issue:

https://i.ibb.co/f1XgC2b/error.jpg

Could you please help me to fix it?
Thanks a lot!

**Comment by pherde** [comment]
Only local! Instapy needs to open a firefox instance!

**Comment by pikki1** [comment]
> Only local! Instapy needs to open a firefox instance!

Hi, thanks a lot for your fast reply, so, how I can fix it?
Thanks a lot again
