### ISSUE TITLE
Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by mttr123** [InstaPy/InstaPy#5575]
Microsoft Windows [Version 10.0.18363.900]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\rockm> CD DESKTOP\

C:\Users\rockm\Desktop>DIR
 Volume in drive C has no label.
 Volume Serial Number is EA39-920B

 Directory of C:\Users\rockm\Desktop

06/17/2020  09:42 PM    <DIR>          .
06/17/2020  09:42 PM    <DIR>          ..
06/15/2020  07:41 AM       220,303,518 100 WAYS TO BREAK AN EGG! - Challenge.mp4
06/11/2020  05:31 PM    <DIR>          2019 nd
06/10/2020  07:08 AM       135,527,270 2020-06-10 07-01-54.mkv
06/16/2020  04:04 PM           110,680 2nd cha (125).jpg
05/27/2020  07:40 AM             1,233 Adobe Photoshop 2020.lnk
06/16/2020  06:51 PM             2,449 Aimbot.ahk
06/13/2020  08:41 AM     2,298,423,738 belly flop.mp4
06/13/2020  08:59 AM             8,029 channel tug.jpg
12/13/2019  04:51 PM               219 Counter-Strike Global Offensive.url
06/13/2020  11:17 AM            16,063 crazt .mepx
06/13/2020  09:35 AM             6,215 crh.jpg
06/17/2020  09:22 AM    <DIR>          crop fini
06/17/2020  02:52 PM    <DIR>          crop2
03/01/2020  03:01 PM             2,233 Discord.lnk
06/09/2020  07:54 AM             1,932 download.png
06/17/2020  10:54 AM    <DIR>          emojis
06/15/2020  09:45 PM    <DIR>          EXTRACT_FILES_9267925
06/15/2020  08:15 AM         7,076,086 Flight_To_Tunisia.mp3
05/19/2020  07:31 AM               289 Fortnite.url
06/16/2020  03:06 PM    <DIR>          gamesvids
06/17/2020  05:24 PM                 0 geckodriver.log
06/16/2020  03:25 PM             8,952 ggooglect.mepx
06/16/2020  03:52 PM       643,693,188 ggooglect.mp4
06/15/2020  04:57 PM               395 gram ;link.txt
06/08/2020  06:53 PM             2,130 hoage .ahk
06/10/2020  07:01 AM        27,909,358 HOW TO HOLD FIRE WITHOUT BURNING YOURSELF - FIRE EXPERIMENT.mp4
10/14/2019  07:42 PM               177 idle.bat
06/16/2020  03:44 PM                67 insta list.txt
06/17/2020  04:45 PM    <DIR>          instapy-quickstart-master
06/17/2020  01:52 PM             2,131 Lucky~Рatchеr.lnk
06/09/2020  07:38 AM           169,329 maxresdefault (2).jpg
06/09/2020  07:42 AM    <DIR>          MEMES
06/15/2020  08:24 AM            66,930 MORGGult.jpg
06/15/2020  08:23 AM            28,264 MORGZ EGGSt.mepx
06/17/2020  10:49 AM             1,158 Movavi Video Editor Plus 2020.lnk
05/19/2020  08:10 PM             1,155 MSI Afterburner.lnk
06/17/2020  05:42 PM    <DIR>          New folder
06/17/2020  02:53 PM    <DIR>          New folder (2)
06/17/2020  09:40 AM                 0 New Text Document.txt
06/15/2020  05:21 PM             1,166 NinjaGram.lnk
04/26/2020  08:44 PM             1,438 Opera GX Browser.lnk
12/24/2019  12:37 PM               222 PAYDAY 2.url
06/11/2020  05:36 PM    <DIR>          psf
06/17/2020  05:13 PM                74 python folder.txt
06/17/2020  05:16 PM             2,755 quickstart.py
05/14/2020  08:27 AM               459 Recycle Bin - Shortcut.lnk
06/17/2020  11:08 AM            16,143 redditttttt.mepx
06/10/2020  08:19 AM           142,885 russian thumb sized.jpg
06/10/2020  08:13 AM            39,987 russian thumb.jpg
06/15/2020  08:08 AM            94,594 Screenshot (124).png
06/16/2020  04:03 PM           110,680 Screenshot (125).jpg
06/16/2020  03:57 PM            27,974 Screenshot (125).png
06/17/2020  10:58 AM            19,425 Screenshot (141).png
06/08/2020  09:21 PM             3,462 settings.txt
06/15/2020  09:08 AM       103,683,640 setup.exe
06/14/2020  08:05 PM        78,216,378 Socinator Shared By AmazCode.zip
06/09/2020  06:19 PM        41,310,226 The Best Belly Flops Compilation 2019.mp4
06/09/2020  06:22 PM    <DIR>          thumbs
03/21/2020  05:00 PM               222 Tom Clancy's Rainbow Six Siege.url
03/27/2020  09:29 AM               269 Tormentor X Punisher.url
06/17/2020  09:46 AM       113,706,689 trilll.mp4
06/14/2020  07:13 PM           381,217 Universal.Bypass.for.Chromium-based.browsers.zip
06/09/2020  09:55 PM            12,322 Work.xlsx
06/09/2020  06:18 PM       165,229,533 World Championships in Death Diving 2018 (DødsingStaplesBellyflopp).mp4
03/26/2020  08:59 PM               276 World War Z.url
06/11/2020  06:09 PM        93,953,219 yor mom.mp4
06/09/2020  08:03 AM                 0 yt links.txt
05/12/2020  07:20 AM             1,931 Zoom.lnk
              56 File(s)  3,930,320,374 bytes
              14 Dir(s)  16,676,216,832 bytes free

C:\Users\rockm\Desktop>python quickstart.py
InstaPy Version: 0.6.9
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/rockm/InstaPy"
Traceback (most recent call last):
  File "quickstart.py", line 11, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\rockm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 311, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\rockm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 115, in set_selenium_local_session
    browser = webdriver.Firefox(
  File "C:\Users\rockm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\rockm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\rockm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\rockm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\rockm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

C:\Users\rockm\Desktop>

i have changed settings in browser and selenium is working why is this not running correctly

**Comment by uj17049** [comment]
i have the same issue

**Comment by knezzit** [comment]
I have the same issue

**Comment by omrisavra** [comment]
I have the same issue

**Comment by omrisavra** [comment]
My problem was, I didn't download firefox for selenium
