### ISSUE TITLE
Comments are not sent when interacting with url

### ISSUE THREAD

**Issue by rzvxa** [InstaPy/InstaPy#5577]
## Expected Behavior
openning a post, like it and send a series of comments to it
## Current Behavior
It opens post, like it but won't send comments
## InstaPy configuration
```
session = InstaPy(username=insta_username,
                  password=insta_username,
                  headless_browser=False)

session.login();

for comment in mention_comments:
    session.set_do_like(enabled=True, percentage=100)
    session.set_do_comment(enabled=True, percentage=100)
    session.set_comments([comment])
    session.interact_by_URL(urls=target_post, randomize=True, interact=True)
    # print('commenting ' + comment)
    # with smart_run(session):
    #     session.set_do_like(enabled=True, percentage=100)
    #     session.set_do_comment(enabled=True, percentage=100)
    #     session.set_comments([comment])
    #     session.interact_by_URL(urls=target_post, randomize=True, interact=True)

session.end(False)


```

**Comment by rzvxa** [comment]
I was using too much mentions (more than 5) in a single comment, but after realizing that and fixing it, it didn't work either, i added some code for pressing post button after pressing enter and it worker, do i have to pr? or can you use button instead of enter key? it's more safe i think this way

**Comment by krheart** [comment]
I have the same problem, it doesn't comment when interacting with url

```
from instapy import InstaPy
from instapy import smart_run
session = InstaPy(username='username', password='password', headless_browser=True)
with smart_run(session):
    session.set_do_comment(enabled=True, percentage=100)
    session.set_comments(["test1", "test2", "test3"])
    session.interact_by_URL(urls="url", randomize=False, interact=True)
```

**Comment by rzvxa** [comment]
> I have the same problem, it doesn't comment when interacting with url
> 
> ```
> from instapy import InstaPy
> from instapy import smart_run
> session = InstaPy(username='username', password='password', headless_browser=True)
> with smart_run(session):
>     session.set_do_comment(enabled=True, percentage=100)
>     session.set_comments(["test1", "test2", "test3"])
>     session.interact_by_URL(urls="url", randomize=False, interact=True)
> ```

I've wrote a custom function for that, try using/editing this:
```
def interaction(session, url):
    if session.aborting:
        return session

    message = "Starting to interact by given URL..."
    highlight_print(session.username, message, "feature", "info", session.logger)

    commented = 0

    if "https://www.instagram.com/p/" not in url:
        url = "https://www.instagram.com/p/" + url

    session.logger.info("--> {}".format(url.encode("utf-8")))

    try:
        inappropriate, user_name, is_video, reason, scope = check_link(
            session.browser,
            url,
            session.dont_like,
            session.mandatory_words,
            session.mandatory_language,
            session.is_mandatory_character,
            session.mandatory_character,
            session.check_character_set,
            session.ignore_if_contains,
            session.logger,
        )

        web_address_navigator(session.browser, url)

        if session.delimit_commenting:
            (
                session.commenting_approved,
                disapproval_reason,
            ) = verify_commenting(
                session.browser,
                session.max_comments,
                session.min_comments,
                session.comments_mandatory_words,
                session.logger,
            )
        if session.commenting_approved:
            comment_state, msg = comment_image(
                session.browser,
                user_name,
                session.comments,
                session.blacklist,
                session.logger,
                session.logfolder,
            )

            comment_btn = get_comment_btn(session.browser)

            ActionChains(session.browser) \
                .move_to_element(comment_btn[0]) \
                .click() \
                .perform()

            sleep_amount = random.randint(300, 400)
            session.logger.info("Sleeping for a good amount({}s)".format(sleep_amount))
            sleep(sleep_amount)

            if comment_state is True:
                commented += 1
        else:
            session.logger.info(disapproval_reason)


    except NoSuchElementException as err:
        session.logger.error("Invalid Page: {}".format(err))


```

**Comment by rzvxa** [comment]
Library itself uses enter for sending comments, i had to press the post button, so i've wrote that function the essential diffrence is in this part:
```
def get_comment_btn(browser):
    comment_input = browser.find_elements_by_xpath('//form/button')
    return comment_input
.....
            comment_btn = get_comment_btn(session.browser)

            ActionChains(session.browser) \
                .move_to_element(comment_btn[0]) \
                .click() \
                .perform()
```

**Comment by rzvxa** [comment]
@timgrossmann Should i create a pull request for it? at least on all gecko drivers that I've used this problem exists, And with a simple button press we can fix it.

**Comment by boby-drum** [comment]
> > I have the same problem, it doesn't comment when interacting with url
> > ```
> > from instapy import InstaPy
> > from instapy import smart_run
> > session = InstaPy(username='username', password='password', headless_browser=True)
> > with smart_run(session):
> >     session.set_do_comment(enabled=True, percentage=100)
> >     session.set_comments(["test1", "test2", "test3"])
> >     session.interact_by_URL(urls="url", randomize=False, interact=True)
> > ```
> 
> I've wrote a custom function for that, try using/editing this:
> 
> ```
> def interaction(session, url):
>     if session.aborting:
>         return session
> 
>     message = "Starting to interact by given URL..."
>     highlight_print(session.username, message, "feature", "info", session.logger)
> 
>     commented = 0
> 
>     if "https://www.instagram.com/p/" not in url:
>         url = "https://www.instagram.com/p/" + url
> 
>     session.logger.info("--> {}".format(url.encode("utf-8")))
> 
>     try:
>         inappropriate, user_name, is_video, reason, scope = check_link(
>             session.browser,
>             url,
>             session.dont_like,
>             session.mandatory_words,
>             session.mandatory_language,
>             session.is_mandatory_character,
>             session.mandatory_character,
>             session.check_character_set,
>             session.ignore_if_contains,
>             session.logger,
>         )
> 
>         web_address_navigator(session.browser, url)
> 
>         if session.delimit_commenting:
>             (
>                 session.commenting_approved,
>                 disapproval_reason,
>             ) = verify_commenting(
>                 session.browser,
>                 session.max_comments,
>                 session.min_comments,
>                 session.comments_mandatory_words,
>                 session.logger,
>             )
>         if session.commenting_approved:
>             comment_state, msg = comment_image(
>                 session.browser,
>                 user_name,
>                 session.comments,
>                 session.blacklist,
>                 session.logger,
>                 session.logfolder,
>             )
> 
>             comment_btn = get_comment_btn(session.browser)
> 
>             ActionChains(session.browser) \
>                 .move_to_element(comment_btn[0]) \
>                 .click() \
>                 .perform()
> 
>             sleep_amount = random.randint(300, 400)
>             session.logger.info("Sleeping for a good amount({}s)".format(sleep_amount))
>             sleep(sleep_amount)
> 
>             if comment_state is True:
>                 commented += 1
>         else:
>             session.logger.info(disapproval_reason)
> 
> 
>     except NoSuchElementException as err:
>         session.logger.error("Invalid Page: {}".format(err))
> ```

were do you copy this? into the instapy.py? or coment_util.py?

ive been trying to make it comment, it opens the post but wont comment... :(
