### ISSUE TITLE
Action blocked on Instapy but not on my phone

### ISSUE THREAD

**Issue by HelloRiah** [InstaPy/InstaPy#5578]
I've been using InstaPy for a couple weeks now and it has been perfect.
But now when I run it all actions are blocked, I checked my phone and everything works perfectly so it only happens on instapy.

I tried reinstalling Visual Studio Code but nothing has changed, also the browser Im using is Firefox and I dont know how to make it use Chrome even tho I have both Chromedriver and Geckodriver.
This is how my code looks.

from instapy import InstaPy

session = InstaPy(username="myusername", password="mypassword", headless_browser=False, want_check_browser=False)
session.login()
session.like_by_tags(["makeupartist", "makeuptutorial"], amount=5)
session.follow_by_tags(['makeupartist', 'makeuptutorial'], amount=5)
session.set_comments(["❤️❤️❤️", "Love❤️"])
session.set_do_comment(enabled=True, percentage=80)

**Comment by alexal1** [comment]
Hey @InstapyUserr if everything works fine on your phone and **it is Android**, you might want to try [Insomniac](https://github.com/alexal1/Insomniac). It has less features than InstaPy, but it simulates actions directly on your phone. Even no login/password required, it simply opens the app and presses buttons as you would.

**Comment by HelloRiah** [comment]
@alexal1 Thanks! I will try that but I rather be able to do this on my computer, do you have any idea on how I can make my code open with chrome?
