### ISSUE TITLE
not commenting on posts

### ISSUE THREAD

**Issue by Karan-Ghatt** [InstaPy/InstaPy#5580]
## Expected Behavior:
to like and comment on posts, chosen based on a hashtag

## Current Behavior
likes but dose not comment on post. 

## InstaPy configuration
-- boiler plate from documentation -- 
only real changes: 
``
session.like_by_tags(["musicproducer"], amount=10)
session.set_do_comment(enabled=True, percentage=100)
session.set_comments(['Awesome', 'Really Cool', 'I like your stuff'])
session.set_do_follow(enabled=True, percentage= 50, times= 1)
session.end()
``

**Comment by fauzanafism** [comment]
Having same issue here. 
I tried to swap the 'set_comment" and 'do_comment', it works. 
But it commenting with different words.

**Comment by FranciscoDumont** [comment]
have you tried using `set_user_interact` somewhere in your code ? 
e.g:
``` python
 session.set_user_interact(amount=1, randomize=False, percentage=40)
```

**Comment by VishalPatra** [comment]
I had similar issue at first.
Try putting 'session.like_by_tags(["musicproducer"]' at the end of the code.
