### ISSUE TITLE
Can't login to instagram 

### ISSUE THREAD

**Issue by elfedmorris** [InstaPy/InstaPy#5582]
Hey hey

I have the rigth downloads of chrome, brackets etc but It gets to instagram and can't automatically login 

Here is what it says

<img width="1680" alt="instapy help" src="https://user-images.githubusercontent.com/34919453/85313067-9b89d780-b4af-11ea-9c8c-fe34a4a57c70.png">

Thanks in advance anyone that can help!

**Comment by alokkumarsbg** [comment]
Try Changing the line in login_util.py from browser.get("view-source:https://ip4.seeip.org/geoip") to browser.get("https://ip4.seeip.org/geoip")

Line no 167

Tag pre is not captured as the result is View source.

**Comment by elfedmorris** [comment]
We're using the quick start. Where do we find the line to replace?

**Comment by elfedmorris** [comment]
How do we find the file to ammend this line? Is this in terminal? Thanks for your help so far!

**Comment by alexal1** [comment]
You can use [Insomniac](https://github.com/alexal1/Insomniac) instead, it doesn't require logging in. It simply presses Instagram app buttons on your Android phone (if you have one).

**Comment by elfedmorris** [comment]
Hey hey, This is suitable as we're on iOS. Thank you for recommending.
