### ISSUE TITLE
Session is not defined

### ISSUE THREAD

**Issue by rellis13178** [InstaPy/InstaPy#5589]
Hey

when I am trying to run a command in instapy I am getting this error;

Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    session.like_by_tags(['tag1', 'tag2', 'tag3'], amount=10)
NameError: name 'session' is not defined

the command I am running is;
session.like_by_tags(['tag1', 'tag2', 'tag3'], amount=10)

The initial log in step works fine, just when I try to run this. I am very new to python and coding in general so layman's terms appreciated :)

**Comment by Ficho1** [comment]
Did you find a solution?
