### ISSUE TITLE
Like Media from followers of a acc or likes media from likers of a specific post

### ISSUE THREAD

**Issue by RemmelHemmel** [InstaPy/InstaPy#5590]
Is it possible to write a bot that likes media from followers of a acc or likers of a specific post?

I haven't found anything similar yet.

Thanks for feedback :))

**Comment by alokkumarsbg** [comment]
Those features are available.

Check out the documentation.

https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md
