### ISSUE TITLE
Spintax feature

### ISSUE THREAD

**Issue by mattmezza** [InstaPy/InstaPy#56]
For comment automation it could be interesting to support Spintax in order to vary the comment text.
https://github.com/AceLewis/spintax might be a good candidate.

**Comment by timgrossmann** [comment]
@mattmezza You're right, I did this by simply writing a small python program which generates ~300 unique comments out of a few part of speech dictionaries.

Examples are: Like your content!, Awesome stuff!... Of course all iterated through with different emojis (#2) possible with selenium

**Comment by timgrossmann** [comment]
@mattmezza I really do think, that this should be a separate tool instead of bloating InstaPy like a balloon...
You can then simply import the comment lists and set them were you want to use them in the quickstart.py

**Comment by pekapa** [comment]
@timgrossmann, I think we could add this to v1 as well

**Comment by pekapa** [comment]
Introduced this on #171
