### ISSUE TITLE
Bypassing Bot Detection (2) and Fixing disable_image_load

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5608]
I posted an issue couple months back (#5369) but had no response from the developing team. I had significantly lowered the chance of getting detected by disabling Instagram's event tracker request URLs. The current solution I use is to use browsermob-proxy to block the URLs.

Also I'd like to mention that disable_image_load doesn't work on latest Firefox. The fix is to add a new line to allow content blocker extension which is disabled by Firefox on default. This can save a lot of bandwidth and speed up the loading process.

Since the lack of attention from the developing team, I had implemented both features on my InstaPy myself and confirmed it to be working. I would like to post my script (modified browser.py and instapy.py) but I'm not sure if the mods will pick it up, which would mean I will have to modify the script for every future release

**Comment by sionking** [comment]
Well preventing the events is a bad one, it can lead to disabled account more than just block you.
few thinks are must have:
1. prevent selenium detection
2. add mouse movements events
3. Fake canvas once having multiple accounts on same PC.

BTW, I switched to real phones app-bot rather than browser.

**Comment by pxp920** [comment]
@sionking , can you elaborate on the switch you did and how successful it's been?

**Comment by gvmturl** [comment]
Why don't you guys take a look on Insomniac?


https://github.com/alexal1/Insomniac

**Comment by jamezun** [comment]
> 
> 
> Well preventing the events is a bad one, it can lead to disabled account more than just block you.
> few thinks are must have:
> 
>     1. prevent selenium detection
> 
>     2. add mouse movements events
> 
>     3. Fake canvas once having multiple accounts on same PC.
> 
> 
> BTW, I switched to real phones app-bot rather than browser.

may I ask what phone app do you use?

**Comment by ghost** [comment]
> 
> 
> Well preventing the events is a bad one, it can lead to disabled account more than just block you.
> few thinks are must have:
> 
>     1. prevent selenium detection
> 
>     2. add mouse movements events
> 
>     3. Fake canvas once having multiple accounts on same PC.
> 
> 
> BTW, I switched to real phones app-bot rather than browser.

Preventing the events AND sending simulated touchscreen movements like a real iPhone worked for me. It's almost been two months since I wrote this issue and I have been using the bot at a high rate and I haven't been caught. The key is to record these touches from a smartphone and recreate it through the selenium.
