### ISSUE TITLE
When trying to run the script in linux I get this error

### ISSUE THREAD

**Issue by codc3** [InstaPy/InstaPy#561]
When trying to run the script in linux I get this error

![image](https://user-images.githubusercontent.com/25847896/29391038-d284dbfa-82ca-11e7-81af-bdfea24640cf.png)

**Comment by timgrossmann** [comment]
@pedroricardo Do a reboot and try again, probably zombie instances.

Did you get the right chrome driver and put it in the assets folder?
Did you add `nogui=True` to the `InstaPy()` contstructor?

**Comment by codc3** [comment]
ok 
Yes I put the chromedriver in the correct folder
Follow all the steps and I installed the dependencies as shown in the tutorial

**Comment by westondeboer** [comment]
If you are doing this from OS X you need to install xquartz. 

`brew cask install xquartz`

And then restart

**Comment by converge** [comment]
there is no interaction for a long time, pls reopen it if you need some help.
