### ISSUE TITLE
set_smart_location_hashtags Crashes

### ISSUE THREAD

**Issue by roberterzen** [InstaPy/InstaPy#5612]
Hi,
I'm having problems with `set_smart_location_hashtags` feature. It crashes every single time. Browser shows some errors but it closes immediately, so I can't see what happens there. It doesn't matter which location do I use crash log is always the same. 

My code in quickstart.py is:
```
session.set_smart_location_hashtags(['214512512/dusseldorf-germany', '218470808/kassel-germany'], radius=20, limit=10, log_tags=True)
session.like_by_tags(amount=10, use_smart_location_hashtags=True)
```
And the crash log is:
```
Traceback (most recent call last):
  File "c:\Program Files\Python37\quickstart.py", line 65, in <module>
    session.set_smart_location_hashtags(['214512512/dusseldorf-germany', '218470808/kassel-germany'], radius=20, limit=10, log_tags=True)
  File "c:\program files\python37\lib\site-packages\instapy\instapy.py", line 752, in set_smart_location_hashtags
    data = json.loads(req.text)
  File "c:\program files\python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\program files\python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files\python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Any idea what is going wrong here?
Thanks.
R.

**Comment by badhezi** [comment]
Getting the exact same stuff.
Tried to manually send a GET to` https://query.displaypurposes.com/local/?bbox=170,-171,32,34&zoom=20`, which is what instapy does, but i get 404 and a google error.

I just started using instapy so this never worked for me before. maybe I'm doing something wrong.

Edit:
Looks like the api endpoint changed, should be `https://apidisplaypurposes.com/local/?bbox={}` instead at https://github.com/timgrossmann/InstaPy/blob/master/instapy/instapy.py#L749

Edit 2: Tested that^  locally, works for me. created PR https://github.com/timgrossmann/InstaPy/pull/5617

**Comment by roberterzen** [comment]
Anyone have any clue in this issue?
