### ISSUE TITLE
like_by_feed no longer working?

### ISSUE THREAD

**Issue by dgunawan** [InstaPy/InstaPy#5613]
This seems to have just started a couple of days ago.  

## Current Behavior
After a succesful login etc., it would return "Total of links feched for analysis: 0". 
This will go on for 10 times and stop

See the log below (truncated)

-- Connection Checklist [2/3] (Instagram Server Status)
INFO [2020-07-11 06:53:13] []  - Instagram WebSite Status: Currently Up 
INFO [2020-07-11 06:53:13] []  - Instagram Response Time: 77.748 ms 
INFO [2020-07-11 06:53:13] []  - Instagram Reponse Code: 200
INFO [2020-07-11 06:53:13] []  - Instagram Server Status: ok
INFO [2020-07-11 06:53:13] []  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2020-07-11 06:53:13] []  - window.navigator.webdriver response: False
INFO [2020-07-11 06:53:13] []  - Hide Selenium Extension: ok
INFO [2020-07-11 06:53:25] []  Logged in successfully!
INFO [2020-07-11 06:53:25] []  Saving account progress...
INFO [2020-07-11 06:54:13] []  Total of links feched for analysis: 0
INFO [2020-07-11 06:54:42] []  Total of links feched for analysis: 0
INFO [2020-07-11 06:55:14] []  Total of links feched for analysis: 0
INFO [2020-07-11 06:55:48] []  Total of links feched for analysis: 0
INFO [2020-07-11 06:56:23] []  Total of links feched for analysis: 0
INFO [2020-07-11 06:57:02] []  Total of links feched for analysis: 0
INFO [2020-07-11 06:57:41] []  Total of links feched for analysis: 0
INFO [2020-07-11 06:58:23] []  Total of links feched for analysis: 0
INFO [2020-07-11 06:59:08] []  Total of links feched for analysis: 0
INFO [2020-07-11 06:59:53] []  Total of links feched for analysis: 0
WARNING [2020-07-11 06:59:53] []  Loop error, 0 links for 10 times consecutively, exit loop

(Yes the typo is in the actual code)

## InstaPy configuration
from CLI: python3 quickstart.py
From docker-compose: 
_bot = InstaPy(username=insta_username, password=insta_password, headless_browser=True)
with smart_run(bot):
    bot.set_relationship_bounds(enabled=True,
                                potency_ratio=-1.21,
                                delimit_by_numbers=True,
                                max_followers=4590,
                                max_following=5555,
                                min_followers=45,
                                min_following=77)
    bot.set_do_comment(True, percentage=10)
    #bot.like_by_tags(["natgeo"], amount=10)
    bot.like_by_feed(amount=10)
    bot.end()_

**Comment by rafaelcolombo** [comment]
Same here, and I have no idea why.
I've notice yesterday that _follow_likers_ stoped, so today I tried _like_by_feed_. Not working as well.

**Comment by roberterzen** [comment]
Same here.

**Comment by tthh76** [comment]
Same it was working fine

**Comment by DerLomo** [comment]
Same here
