### ISSUE TITLE
Bot stops in 1-2 mins

### ISSUE THREAD

**Issue by MiChaelinzo** [InstaPy/InstaPy#5616]
## Current Behavior

WARNING [2020-07-12 21:15:25] []  - Hide Selenium Extension: error
INFO [2020-07-12 21:16:09] []  Timed out with failure while explicitly waiting until title contains 'Login' string!

INFO [2020-07-12 21:16:47] []  Timed out with failure while explicitly waiting until visibility of element located!

INFO [2020-07-12 21:16:53] []  Sessional Live Report:
        |> No any statistics to show

[Session lasted 1.67 minutes]
INFO [2020-07-12 21:16:53] []  Session ended!
InstaPy Version: 0.6.9
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/insoa/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
C:\Users\insoa\AppData\Local\Temp\20200712-211652.html
**********************************************************************

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "quickstart.py", line 18, in <module>
    with smart_run(session):
  File "C:\Python38\lib\contextlib.py", line 115, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield

**Comment by MiChaelinzo** [comment]
### **What do I need to do same things happens when running in Linux !!**

**Comment by quaxi228** [comment]
I have the same issue... Is there a solution for this? 
Bought a raspberry for this. worked twice, now it does not work anymore since i switched to the gui.

**Comment by MiChaelinzo** [comment]
How did you made it first worked?

**Comment by DonFuego** [comment]
Try running with option headless_browser=False and see what the error is - for me it was an incorrect password.

**Comment by quaxi228** [comment]
@DonFuego Thanks. This did the trick for me.
Now I need to set up a useful script. I'm still disappointed I can't unfollow more than 200non followers per day

**Comment by RhaegarTargaryen55** [comment]
same

**Comment by Fasteel** [comment]
Remove workspace directory and re-run works for me.

**Comment by RhaegarTargaryen55** [comment]
@Fasteel where is that directory?

**Comment by DonFuego** [comment]
@Fasteel @RhaegarTargaryen55 I would be careful removing that directory as it contains the running database of interactions, logs, assets (gecko drive + cookies) etc. that is integral to the bot working between runs.  You can set that directory to be whatever you like in the "set_workspace()" method or it defaults to your home directory.

**Comment by MiChaelinzo** [comment]
> Try running with option headless_browser=False and see what the error is - for me it was an incorrect password.

it's already on in default, nothing really stands an error other than Cookie file not found, creating cookie...
INFO [2020-09-21 16:17:26]   Timed out with failure while explicitly waiting until title contains 'Login' string!

**Comment by MiChaelinzo** [comment]
I can login properly etc. my profile home is showing. I can use it but it will close after 1:30 min

**Comment by lipeandradecb** [comment]
> I can login properly etc. my profile home is showing. I can use it but it will close after 1:30 min

the same happens to me

**Comment by TianHuangLab** [comment]
same issue

**Comment by MiChaelinzo** [comment]
found a solution it's because of the quickstart.py scripts try using different one other than default etc.

**Comment by jhrtrl** [comment]
Hi @MiChaelinzo, trying using different one, what? What did you do?

Thank you for your help.

**Comment by jhrtrl** [comment]
> found a solution it's because of the quickstart.py scripts try using different one other than default etc.

Coud you help me please?

**Comment by MiChaelinzo** [comment]
> > found a solution it's because of the quickstart.py scripts try using different one other than default etc.
> 
> Coud you help me please?

https://github.com/InstaPy/instapy-quickstart/tree/master/quickstart_templates example scripts from the community of the instapy-quickstart

**Comment by alezlam** [comment]
> > > found a solution it's because of the quickstart.py scripts try using different one other than default etc.
> > 
> > 
> > Coud you help me please?
> 
> https://github.com/InstaPy/instapy-quickstart/tree/master/quickstart_templates example scripts from the community of the instapy-quickstart

Could you elaborate more? please

**Comment by ADartist** [comment]
Hello,

I have the same error as @MiChaelinzo. I am not an advanced programmer and really struggle to understand if there is a solution or not...

@elulcao : you seem to have a solution (in another conversation) but I do not understand anything... Can you help me please ? I would need a step-by-step guidance : where can I change this 'Login' title ?
After that, how to fix the second error ("visibility of element located") please ?
I precise that I read all the related topics, but I didn't understand any solution (if there was any)...

Many thanks in advance from all my heart

**Comment by ADartist** [comment]
Partial good news, I manage to remove the first error (title contains 'Login' string!) by opening the file login_util.py (located in _instapy/_, instapy/ being located in the same folder instaPy-master/ as quickstart.py), and replacing **login_page_title = "Login"** by **login_page_title = "Instagram"**
But I still have the second error (visibility of element located!), for which I am powerless...

**Comment by elulcao** [comment]
> login_page_title =

Hi @ADartist 

In login_util.py try with `login_page_title = "Instagram"`
Im guessing that the other error seems to be related to the new text `Save Your Login Info?`, if that is true you can check the merge-req, the code change is not complicated but it would be better if you can try with the branch (Instagram_title_fix) that have the changes.

**Comment by ADartist** [comment]
Hello @elulcao ,
Thank you so much for your answer. Indeed, the change of login_page_title = "Instagram" in login_util.py solved the first error.
However, I still have the second error. I indeed found your merge-req (https://github.com/timgrossmann/InstaPy/pull/5813/commits/d875c93bcdc8ca199cbd2363fe4038f0d77c1a83), and I changed everything as it is written there : 
- In quickstart.py : **session = InstaPy(..., geckodriver_log_level='trace')**
- In browser.py : **geckodriver_log_level,** and **firefox_options.log.level = geckodriver_log_level** in the **def set_selenium_local_session**
- In instapy.py : **geckodriver_log_level: str = "info",** in **def __init__** and **geckodriver_log_level,** in the **if selenium_local_session:** in line 321

What should I do in this case please ?

**Comment by SanielDous** [comment]
@ADartist I am facing the same issue. I already fixed the line
`INFO [2020-07-12 21:16:09] [] Timed out with failure while explicitly waiting until title contains 'Login' string!`
by replacing the mentioned string in `login_util.py`.

But I am sill struggling with the second issue. I also run instapy on a raspberry pi in headless mode. Currently it produces the following output (even with different accounts):

```
InstaPy Version: 0.6.10
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/pi/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-10-22 13:06:41] []  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-10-22 13:06:41] []  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-10-22 13:06:42] []  - Internet Connection Status: ok
INFO [2020-10-22 13:06:42] []  - Current IP is "123.456.789.0" and it's from ""
INFO [2020-10-22 13:06:42] []  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-10-22 13:06:42] []  - window.navigator.webdriver response: None
INFO [2020-10-22 13:06:42] []  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
INFO [2020-10-22 13:07:31] []  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20201022-130736.html
**********************************************************************

INFO [2020-10-22 13:07:39] []  Sessional Live Report:
        |> No any statistics to show


[Session lasted 1.26 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-10-22 13:07:39] []  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "start_script.py", line 68, in <module>
    with smart_run(session):
  File "/usr/lib/python3.7/contextlib.py", line 114, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield
```
I get the same error when running the bot with `headlessMode=False` on my Ubuntu Laptop.

**Comment by romalino** [comment]
Hi, This did the trick for me.
https://github.com/timgrossmann/InstaPy/issues/5837#issuecomment-713202414

**Comment by SanielDous** [comment]
Thank you very much! That did the trick for me too.

**Comment by bicravix** [comment]
> Hi, This did the trick for me.
> [#5837 (comment)](https://github.com/timgrossmann/InstaPy/issues/5837#issuecomment-713202414)

Not me :( , some help pleasee
