### ISSUE TITLE
Guides>"How to CentOS"- missing

### ISSUE THREAD

**Issue by romankk** [InstaPy/InstaPy#562]
Can you please provide instructions for installation on CentOS

**Comment by timgrossmann** [comment]
@romankk The guide seemed to not work correctly so it got removed.
Please use Ubuntu when using Digital Ocean.

The process is pretty much the same with CentOS though, just make sure to use yum instead of apt-get

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
