### ISSUE TITLE
Invalid Like Element : Docker configuration.

### ISSUE THREAD

**Issue by SRAlexander** [InstaPy/InstaPy#5624]
## Expected Behavior

Liking images

## Current Behavior

When liking images --> Invalid Like Element ! error

## Possible Solution (optional)

Manual modification of xpath route solves this issues for non docker instances... 
xpath["like_image"] = { "like": "/html/body/div[1]/section/main/div/div/article/div[3]/section[1]/span[1]/button/div[*[local-name()='svg']/@aria-label='Like']", "unlike": "/html/body/div[1]/section/main/div/div/article/div[3]/section[1]/span[1]/button/div[*[local-name()='svg']/@aria-label='Unlike']", } .... https://github.com/timgrossmann/InstaPy/issues/5620

Should the XPath settings be modifiable in the config.py to fix this without code changes down the line?

## InstaPy configuration

Can be provided if required.

**Comment by mxmahmoud** [comment]
i have the same issues with liking images..

**Comment by ghost** [comment]
https://github.com/timgrossmann/InstaPy/pull/5626
