### ISSUE TITLE
Comment button not found!

### ISSUE THREAD

**Issue by emrejacky** [InstaPy/InstaPy#5625]
## Expected Behavior
Should open up comment section
## Current Behavior
Not opening comment section. Getting error "Comment button not found!"
## Possible Solution (optional)
Editing xpath_compile.py.
## InstaPy configuration

I have tried to copy XPATH from f12 in mobile width but it does not work when I edit "xpath_compile.py"
Probably Instagram have updated their code recently.

**Comment by buntybatra** [comment]
Update following index as follow :- 
`xpath["open_comment_section"] = {
    "comment_elem": "/html/body/div[1]/section/main/div/div/article/div[3]/section[1]/span[2]/button"
}
`
This solve my problem

**Comment by SkyLakeRT** [comment]
Its work, THANK YOU !!!

**Comment by emrejacky** [comment]
It worked, I appreciated it!

**Comment by emrejacky** [comment]
For some peoples difficult to find "xpath_compile.py" location. It was under "C:\Users\YourUserName\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\instapy" this path for my win10.

So you can find it easily and edit  **open_comment_section** easily.

**Comment by ghost** [comment]
Will be solved with this PR: https://github.com/timgrossmann/InstaPy/pull/5626

**Comment by karlomendoza** [comment]
Sorry for asking in here. I have made this change and it works. But, What happens when a new version of the library comes out. It's overwritten? Python noob. Sorry

**Comment by buntybatra** [comment]
@karlomendoza, @Zbenahmed already created PR for this. So, it should merge in next release.

**Comment by gypnofrog** [comment]
@buntybatra It works! 
But after writing a comment, the Post button is not pressed and the comment is not sent. Please, help me!
