### ISSUE TITLE
Can't get photo likers: "Couldn't find liked counter button. May be a video."

### ISSUE THREAD

**Issue by pezzotto** [InstaPy/InstaPy#5628]
Instagram has changed something so i think xpath links must be updated.

**Comment by ghost** [comment]
Probably related to this : https://github.com/timgrossmann/InstaPy/pull/5626

**Comment by roberterzen** [comment]
> Probably related to this : #5626

I don't think so. 
#5626 is related to locating Like/Unlike button while "Couldn't find liked counter button. May be a video." shows when bot wants to get info who liked some particular post.

**Comment by tanmald** [comment]
same issue here.

**Comment by ghost** [comment]
I see yeah different one my bad, I believe it might come from this : 
https://github.com/timgrossmann/InstaPy/blob/master/instapy/xpath_compile.py#L188 instead it might be :
```"liked_counter_button": "//div/article/div[3]/section[2]/div/div/a",``` from my quick look at the code

**Comment by tanmald** [comment]
> I see yeah different one my bad, I believe it might come from this :
> https://github.com/timgrossmann/InstaPy/blob/master/instapy/xpath_compile.py#L188 instead it might be :
> `"liked_counter_button": "//div/article/div[3]/section[2]/div/div/a",` from my quick look at the code

thank you @zbenahmed but still isn't working :/

**Comment by ghost** [comment]
@tanmald anyway I can reproduce this easily ? I'll test and fix this, that way

**Comment by tanmald** [comment]
hey, has anyone been able to fix this problem? i just updated to 6.10 and this still happens :/

**Comment by mkhazan** [comment]
same issue

**Comment by kevinjulian** [comment]
change to 
`"liked_counter_button": "//div/article/div/div[3]/section[2]/div/div/a",`
works for me

@tanmald

**Comment by ghost** [comment]
haha yeah was missing out a div, would you mind creating a PR @kevinjulian  ?

**Comment by szabizs** [comment]
The problem seems to come from instagram's resolution, if you do not resize the window, it will work, since elements will change based on screen resolution.

Also I've updated my xpath

```
xpath["likers_from_photo"] = {
    "liked_counter_button": "/html/body/div[1]/section/main/div/div/article/div/div[3]/section[2]/div/div[2]/a[1]",
    "second_counter_button": "/html/body/div[1]/section/main/div/div/article/div/div[3]/section[2]/div/div[2]/a[2]",
}
```
![follow](https://user-images.githubusercontent.com/5064872/89371366-d6586f80-d6eb-11ea-8a3e-f4a1f5989150.png)

**Comment by owoki** [comment]
> The problem seems to come from instagram's resolution, if you do not resize the window, it will work, since elements will change based on screen resolution.
> 
> Also I've updated my xpath
> 
> ```
> xpath["likers_from_photo"] = {
>     "liked_counter_button": "/html/body/div[1]/section/main/div/div/article/div/div[3]/section[2]/div/div[2]/a[1]",
>     "second_counter_button": "/html/body/div[1]/section/main/div/div/article/div/div[3]/section[2]/div/div[2]/a[2]",
> }
> ```
> 
> ![follow](https://user-images.githubusercontent.com/5064872/89371366-d6586f80-d6eb-11ea-8a3e-f4a1f5989150.png)

I tried this xpaths but not working. For this reason I wrote xpath myself, anyone can use.

`"liked_counter_button": "//a[contains(@href,'liked_by/')]"`

**Comment by DerLomo** [comment]
Not working any of those changes, any update??

**Comment by renkasiyas** [comment]
This xpath worked for me:

`"/html/body/div[1]/section/main/div/div/article/div[3]/section[2]/div/div/a"`

**Comment by parsabiology** [comment]
Hello,How are you?
Excuse me,I have a problem, can you help?

**Comment by ugurkellecioglu** [comment]
> > The problem seems to come from instagram's resolution, if you do not resize the window, it will work, since elements will change based on screen resolution.
> > Also I've updated my xpath
> > ```
> > xpath["likers_from_photo"] = {
> >     "liked_counter_button": "/html/body/div[1]/section/main/div/div/article/div/div[3]/section[2]/div/div[2]/a[1]",
> >     "second_counter_button": "/html/body/div[1]/section/main/div/div/article/div/div[3]/section[2]/div/div[2]/a[2]",
> > }
> > ```
> > 
> > 
> > ![follow](https://user-images.githubusercontent.com/5064872/89371366-d6586f80-d6eb-11ea-8a3e-f4a1f5989150.png)
> 
> I tried this xpaths but not working. For this reason I wrote xpath myself, anyone can use.
> 
> `"liked_counter_button": "//a[contains(@href,'liked_by/')]"`

This also worked for me ty a lot 👍
