### ISSUE TITLE
Instapy stops at LOG IN screen

### ISSUE THREAD

**Issue by ceylanayberk** [InstaPy/InstaPy#5643]
## Expected Behavior
Hi developers, I am trying to run Instapy 0.5.8 but it is not working. I changed a to button in path_compile.py but it is not logging. It comes to LOG IN screen than it stops. Is there anybody can help me?

## Current Behavior

******:~ ******$ python /Users/*****/Desktop/instapy-quickstart-master/quickstart.py 

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/*****/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
INFO [2020-07-19 00:14:01] [*****]  Using built in instapy-chromedriver executable (version 2.46)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-07-19 00:14:03] [*****]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2020-07-19 00:14:03] [*****]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-07-19 00:14:11] [*****]  - Internet Connection Status: ok
INFO [2020-07-19 00:14:11] [*****]  -- Connection Checklist [2/2] (Instagram Server Status)
INFO [2020-07-19 00:14:22] [*****]  - Instagram WebSite Status: Currently Up 
INFO [2020-07-19 00:14:22] [*****]  - Instagram Response Time: 93.508 ms 
INFO [2020-07-19 00:14:22] [*****]  - Instagram Reponse Code: 200
INFO [2020-07-19 00:14:22] [*****]  - Instagram Server Status: ok
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

..............................................................................................................................
CRITICAL [2020-07-19 00:14:45] [*****]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ERROR [2020-07-19 00:14:45] [******]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.

INFO [2020-07-19 00:14:45] [*****]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 43.32 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-07-19 00:14:45] [******]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by wsmith9897** [comment]
Having the same issue! Even when I add a page delay and login manually Instapy automatically ends the session after 20 seconds
