### ISSUE TITLE
WARNING! Image was NOT liked! You have a BLOCK on likes!

### ISSUE THREAD

**Issue by theinstigator1** [InstaPy/InstaPy#5644]
## Current Behavior
After running for couple of days it always gets blocked by Instagram algorithm returning 
 WARNING! Image was NOT liked! You have a BLOCK on likes!

I tried deleting cookie and changing password and changing behaviour of setup but it is always the same. Any new ideas?

**Comment by pabs24** [comment]
same!

**Comment by clearyusc** [comment]
Same!

**Comment by emrejacky** [comment]
same.. it's been  a 3 days rn.

**Comment by emrejacky** [comment]
Deleting everything under C:\Users\x\InstaPy\logs  worked for me.

**Comment by shashikotte** [comment]
> Deleting everything under C:\Users\x\InstaPy\logs worked for me.

Worked for me too!

**Comment by CamiloB** [comment]
use quota supervisor and do go insane whit the instagram actions

**Comment by gvmturl** [comment]
Take a look on
https://github.com/alexal1/Insomniac

**Comment by elulcao** [comment]
> Deleting everything under C:\Users\x\InstaPy\logs worked for me.

Also deleting only the cookie (pkl file) is enough.
I read in other forums that also modifying the Bio also helps.
