### ISSUE TITLE
Selenium Remote Webdriver Issue on InstaPy

### ISSUE THREAD

**Issue by rouncewell** [InstaPy/InstaPy#5645]
## Overview

I've installed this on my computer that uses Void Linux. I installed via pip3 with the --ignore-installed flag. It seems to run fine but it really doesn't interact with anything. I see a lot of 'image not liked' or 'invalid like element' errors. I'm completely new to InstaPy but have gone over some of the documentation. The error is with the webdriver on selenium. I have chrome-stable and firefox-esr but I do not know much outside of what to do with that. Any help would be appreciated. 

Also, I have tried this on a Debian VPS and a Raspberry Pi 3. Both of those, I followed the written guides to a T and I run into the same issue.

## Current Behavior

Here is the output of the issue I receive

`Traceback (most recent call last):
  File "/home/rouncewell/.local/lib/python3.8/site-packages/instapy/util.py", line 1061, in get_relationship_counts
    followers_count = browser.execute_script(
  File "/home/rouncewell/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "/home/rouncewell/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/rouncewell/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window._sharedData is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Dropbox/InstaPy.py", line 120, in <module>
    # activity
  File "/home/rouncewell/.local/lib/python3.8/site-packages/instapy/instapy.py", line 1916, in like_by_tags
    validation, details = self.validate_user_call(user_name)
  File "/home/rouncewell/.local/lib/python3.8/site-packages/instapy/instapy.py", line 1298, in validate_user_call
    validation, details = validate_username(
  File "/home/rouncewell/.local/lib/python3.8/site-packages/instapy/util.py", line 206, in validate_username
    followers_count, following_count = get_relationship_counts(
  File "/home/rouncewell/.local/lib/python3.8/site-packages/instapy/util.py", line 1069, in get_relationship_counts
    browser.find_element_by_xpath(
  File "/home/rouncewell/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/rouncewell/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/rouncewell/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/rouncewell/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette`

## InstaPy configuration

Here is the config I use ... I took out the hashtags and account info of course.

`

"""
This template is written by @the-unknown

What does this quickstart script aim to do?
- This is my template which includes the new QS system.
  It includes a randomizer for my hashtags... with every run, it selects 10
  random hashtags from the list.

NOTES:
- I am using the bot headless on my vServer and proxy into a Raspberry PI I
have at home, to always use my home IP to connect to Instagram.
  In my comments, I always ask for feedback, use more than 4 words and
  always have emojis.
  My comments work very well, as I get a lot of feedback to my posts and
  profile visits since I use this tactic.

  As I target mainly active accounts, I use two unfollow methods. 
  The first will unfollow everyone who did not follow back within 12h.
  The second one will unfollow the followers within 24h.
"""

# !/usr/bin/python2.7
import random
from instapy import InstaPy
from instapy import smart_run

# get a session!
session = InstaPy(username='', password='', headless_browser=True)

# let's go! :>
with smart_run(session):
    hashtags = []
    random.shuffle(hashtags)
    my_hashtags = hashtags[:10]

    # general settings
    session.set_dont_like([])
    session.set_do_follow(enabled=True, percentage=80, times=1)
    session.set_do_comment(enabled=True, percentage=10)
    session.set_comments([
                             u'I like this a lot!',
                             u'Nice work, keep it up!',
                             u'This is awesome! ',
                             u'This is awesome, lots of character',
                             u'Nice work, your picture turned out great',
                             u'Im liking this a lot',
                             u'I like this a lot! If you have a moment, check out my work :smiley:',
                             u'Stunning work, looking forward to more',
                             u'Turned out awesome! :ok_hand:',
                             u'This looks really good :ok_hand:',
                             u'Nice shot, works very well!',
                             u'Nice shot there, keep it up! :smiley:',
                             u'Well shot :camera_with_flash:! Keep it going :slight_smile:',
                             u'Stunning! I like this a lot!',
                             u'I really like this, nice work!',
                             u'Looks great, cannot wait for more!',
                             u'Nice composition :camera_with_flash:!',
                             u'Looks awesome :ok_hand:'],
                         media='Photo')
    session.set_do_like(True, percentage=80)
    session.set_delimit_liking(enabled=True, max_likes=500, min_likes=None)
    #session.set_delimit_liking(enabled=True, max=random.randint(10,75), min=None)
    session.set_delimit_commenting(enabled=True, max_comments=12, min_comments=None)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=10000,
                                    max_following=2500,
                                    min_followers=10,
                                    min_following=10)

    session.set_skip_users(skip_private=True,
                           private_percentage=100,
                           skip_no_profile_pic=True,
                           no_profile_pic_percentage=100,
                           skip_business=False,
                           skip_non_business=False,
                           business_percentage=10,
                           skip_business_categories=[],
                           dont_skip_business_categories=[])

    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "follows"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes_hourly=120,
                                 peak_likes_daily=480,
                                 peak_comments_hourly=30,
                                 peak_comments_daily=120,
                                 peak_follows_hourly=30,
                                 peak_follows_daily=360,
                                 peak_unfollows_hourly=40,
                                 peak_unfollows_daily=480,
                                 peak_server_calls_hourly=None,
                                 peak_server_calls_daily=4700)

    session.set_user_interact(amount=10, randomize=True, percentage=80)

    # activity
    session.like_by_tags(my_hashtags, amount=90, media=None)
    session.unfollow_users(amount=500, instapy_followed_enabled=True, instapy_followed_param="nonfollowers",
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=501)
    session.unfollow_users(amount=500, instapy_followed_enabled=True, instapy_followed_param="all",
                           style="FIFO", unfollow_after=24 * 60 * 60,
                           sleep_delay=501)
`

**Comment by gustavoavrj** [comment]
In recent days instagram made change to his code, so currently instapy is buggy, you need to update xpaths

**Comment by rouncewell** [comment]
I'm a novice with Linux. What do you mean update xpaths?

**Comment by kr6k3n** [comment]
> I'm a novice with Linux. What do you mean update xpaths?

Xpaths have nothing to do with linux; simply put xpaths are references to where are elements on the instagram's html code. For example one xpath might point to a like button or the login button, they're used by InstaPy's code.

Xpaths are stored in  `xpath_compile.py`,
in your case it seems to be `/home/rouncewell/.local/lib/python3.8/site-packages/instapy/xpath_compile.path`
You can manually find the current ones by using your browser, just google how to do so. Then update them in `xpath_compile.py`
It seems that the faulty section in your case is the get_relationship_counts xpath dictionary on line 122.
Hope that will be helpful,
read more about [xpath](https://www.guru99.com/xpath-selenium.html)
