### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\rammb\\InstaPy\\assets\\geckodriver.exe'

### ISSUE THREAD

**Issue by Rammbike** [InstaPy/InstaPy#5649]
I just wanted to log in to instapy to give likes automatically. I installed it and when I run the code I got "PermissionError: [Errno 13] Permission denied: 'C:\\Users\\rammb\\InstaPy\\assets\\geckodriver.exe'". What does it mean and what to do with it? 

Is there a script that I could use to like new photos of people who I follow?

**Comment by zubus** [comment]
Hi, try to check in task manager if geckodriver.exe is running, and kill it. And then run Instapy

**Comment by Atumos** [comment]
> Hi, try to check in task manager if geckodriver.exe is running, and kill it. And then run Instapy

I have the same issue and killing geckodrive.exe in the taskmanager doesn't help. Do you have an other solution?

**Comment by shivkumar0757** [comment]
facing the same issue,
I tried to find and kill geckodriver.exe from the task manager, but it was not there.

so i killed the python process and restarted Jupyter Notebook.

working fine!!
