### ISSUE TITLE
Versioning and changelog

### ISSUE THREAD

**Issue by Naramsim** [InstaPy/InstaPy#565]
I think we need a proper versioning system (I don't see any version number in the readme) and a `changelog.md` file, so we can track new features

Thanks

**Comment by timgrossmann** [comment]
@Naramsim Good idea, problem is that needs to be maintained... There are no version numbers right now. The release feature of GitHub would be a good fit.

Feel free to start one

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
