### ISSUE TITLE
Invalid Like Element 

### ISSUE THREAD

**Issue by tperas** [InstaPy/InstaPy#5650]
## Expected Behavior

ability to like the targeted element defined on the code

## Current Behavior

this element doesn't exist anymore, so the script is not able to find it

## Possible Solution (optional)

Update the code with the new element definition : 
xpath["like_image"] = {
"like": "//section/span/button/div[[local-name()='svg']/@aria-label='Like']",
"unlike": "//section/span/button/div[[local-name()='svg']/@aria-label='Unlike']",
}

## InstaPy configuration

Modify the definition of the Like element

**Comment by tperas** [comment]
Here some details of a possible resolution from @Lisiadito  : 

xpath["like_image"] = {
    "like": "//section/span/button/div[*[local-name()='svg']/@aria-label='Like']",
    "unlike": "//section/span/button/div[*[local-name()='svg']/@aria-label='Unlike']",
}

It just need to be updated into the code directly

**Comment by Booleboole** [comment]
from today same issue for me
try solution from Mohanbarman in "pull request" but nothing

**Comment by krisnailafat** [comment]
> from today same issue for me
> try solution from Mohanbarman in "pull request" but nothing

any update?

**Comment by Booleboole** [comment]
> > from today same issue for me
> > try solution from Mohanbarman in "pull request" but nothing
> 
> any update?

No..... 
I try Many Version of xpath and i try to modify myself the xpath but nothing 
Waiting for help....

**Comment by ERR999R** [comment]
Same issue here!

**Comment by tanmald** [comment]
same issue here as well.

**Comment by Booleboole** [comment]
Any update about the problem??

**Comment by Lisiadito** [comment]
there is a open PR which should fix this problem. for now you can change these lines in the file `xpath_compile.py`
```
xpath["like_image"] = {
    "like": "//section/span/button/div[*[local-name()='svg']/@aria-label='Like']",
    "unlike": "//section/span/button/div[*[local-name()='svg']/@aria-label='Unlike']",
}
```

**Comment by alfanme** [comment]
> there is a open PR which should fix this problem. for now you can change these lines in the file `xpath_compile.py`
> 
> ```
> xpath["like_image"] = {
>     "like": "//section/span/button/div[*[local-name()='svg']/@aria-label='Like']",
>     "unlike": "//section/span/button/div[*[local-name()='svg']/@aria-label='Unlike']",
> }
> ```

I just tried this, and it worked well. Thanks!

**Comment by tperas** [comment]
> there is a open PR which should fix this problem. for now you can change these lines in the file `xpath_compile.py`
> 
> ```
> xpath["like_image"] = {
>     "like": "//section/span/button/div[*[local-name()='svg']/@aria-label='Like']",
>     "unlike": "//section/span/button/div[*[local-name()='svg']/@aria-label='Unlike']",
> }
> ```

Worked for me too ! Thank you @Lisiadito

**Comment by bronzeboy** [comment]
> there is a open PR which should fix this problem. for now you can change these lines in the file `xpath_compile.py`
> 
> ```
> xpath["like_image"] = {
>     "like": "//section/span/button/div[*[local-name()='svg']/@aria-label='Like']",
>     "unlike": "//section/span/button/div[*[local-name()='svg']/@aria-label='Unlike']",
> }
> ```

Still dosen't  work for me,  just  me?

**Comment by Lisiadito** [comment]
@bronzeboy what version of InstaPy do you have installed?

**Comment by english-coconut** [comment]
@Lisiadito Hello, I've also encountered the 'Invalid like element' problem and I'm using the latest Instapy version and python 3.7 in Spyder. What do you mean by open PR and changing the related x_path code? I've checked the current x_path code and it looks exactly like the code you stated above.

**Comment by Booleboole** [comment]
Tomorrow try to reset my raspberry and reinstall all...
I hope is only a corrupt python library

**Comment by bronzeboy** [comment]
> @bronzeboy what version of InstaPy do you have installed?

The last one 0.6.9 and I manually upgraded  browser.py  and xpath from github latest commit

**Comment by Lisiadito** [comment]
@bronzeboy not sure what you updated in the browser.py but with a clean 0.6.9 install and then modifying the `xpath_compile.py` with the changes i suggested it should work.

**Comment by angelonso** [comment]
> @bronzeboy not sure what you updated in the browser.py but with a clean 0.6.9 install and then modifying the `xpath_compile.py` with the changes i suggested it should work.

Hi!, I did this exactly this and did not work for me. All im using is the feature like by tag on my code... idk still get the invalid like element

**Comment by english-coconut** [comment]
@angelonso I've encountered this problem too.I "was" using python 3.7 in Spyder and Mozilla Firefox (the latest version, I think it's 0.78),Windows 10 64bit. I tried changing the xpath_compile.py 'like-image' codepiece but still gave 1.Invalid like element, and 2. Wrong pathway  error. 

Tried the solutions here, no avail ,so I went to my other device(same python version) but I had Mozilla developer. It works without changing any code(still puzzled why).

If that doesn't work then implement the suggested code above to a lower version of Mozilla or firebug.

**Comment by angelonso** [comment]
@english-coconut Thank you very much for yoy reply! I finally managed to make it work. For me it world using the developer browser and changing the code. Also no idea why but thank you 👍:D

**Comment by tiagofabrica** [comment]
> Tomorrow try to reset my raspberry and reinstall all...
> I hope is only a corrupt python library

did u manage to solve it on raspberry?

**Comment by bronzeboy** [comment]
> @bronzeboy not sure what you updated in the browser.py but with a clean 0.6.9 install and then modifying the `xpath_compile.py` with the changes i suggested it should work.

It was an error by my part, sorry and thanks!

**Comment by Booleboole** [comment]
> > Tomorrow try to reset my raspberry and reinstall all...
> > I hope is only a corrupt python library
> 
> did u manage to solve it on raspberry?

This morning I reset my raspberry .....
try on "rpi3 b+" and "rpi2 b"
And than:

INSTALL OS 
- Fresh install raspian ( ssh enable )
- update and upgrade 
INSTALL FIREFOX-ESR
INSTALL GECKODRIVER
- wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-arm7hf.tar.gz
- tar -xvzf geckodriver-v*
- chmod +x geckodriver
- sudo cp geckodriver /usr/local/bin/
INSTALL INSTAPY ( last build ) and OTHER
- pip3 install -I https://github.com/timgrossmann/InstaPy/zipball/master
- pip3 install future
- pip3 install pyvirtualdisplay
INSTALL XVFB ( NECESSARY IF USE CRON )
- sudo apt-get install xvfb

For work:
xvfb-run python3 yourscript.py

Everything work without any modification
In the last build is already modified browser.py (hide selenium extension) and xpath_compile.py

Cron is ok with xvfb 

I think my old problem was with some python library but i'm unable to remove old library from os

Many than to everyone and may thanks to @Lisiadito

**Comment by tiagofabrica** [comment]
> > > Tomorrow try to reset my raspberry and reinstall all...
> > > I hope is only a corrupt python library
> > 
> > 
> > did u manage to solve it on raspberry?
> 
> This morning I reset my raspberry .....
> try on "rpi3 b+" and "rpi2 b"
> And than:
> 
> INSTALL OS
> 
> * Fresh install raspian ( ssh enable )
> * update and upgrade
>   INSTALL FIREFOX-ESR
>   INSTALL GECKODRIVER
> * wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-arm7hf.tar.gz
> * tar -xvzf geckodriver-v*
> * chmod +x geckodriver
> * sudo cp geckodriver /usr/local/bin/
>   INSTALL INSTAPY ( last build ) and OTHER
> * pip3 install -I https://github.com/timgrossmann/InstaPy/zipball/master
> * pip3 install future
> * pip3 install pyvirtualdisplay
>   INSTALL XVFB ( NECESSARY IF USE CRON )
> * sudo apt-get install xvfb
> 
> For work:
> xvfb-run python3 yourscript.py
> 
> Everything work without any modification
> In the last build is already modified browser.py (hide selenium extension) and xpath_compile.py
> 
> Cron is ok with xvfb
> 
> I think my old problem was with some python library but i'm unable to remove old library from os
> 
> Many than to everyone and may thanks to @Lisiadito

thanks , i'm now able to run it.

Sometimes just with some random instagram errors "Instagram error: The link you followed may be broken, or the page may have been removed..."

trying to figure it out what can be

**Comment by Lisiadito** [comment]
That happens when a user changes the username. So it's normal and doesn't crash the Skript since it is expected.

**Comment by tiagofabrica** [comment]
> That happens when a user changes the username. So it's normal and doesn't crash the Skript since it is expected.

thanks didn't knew that. btw, do you know any way to avoid the block on likes?

**Comment by Lisiadito** [comment]
What are your settings for likes? Obviously there is some kind of limit per hour which is enforced by Instagram. But sometimes the script can verify if the like went through due to a timeout or something and then you get the occasional message that you might be blocked from liking.

**Comment by tiagofabrica** [comment]
session.set_user_interact(amount=2, randomize=True, percentage=60)
    session.set_do_follow(enabled=True, percentage=40)
    session.set_do_like(enabled=True, percentage=80)

    # activity
    session.like_by_tags(random.sample(like_tag_list, 3),
                         amount=random.randint(50, 100), interact=True)

I have it like this. It might be that, because when I got that block message at the script i'm still able to put likes on the app and at the browser

**Comment by alfanme** [comment]
> ## Expected Behavior
> 
> ability to like the targeted element defined on the code
> ## Current Behavior
> 
> this element doesn't exist anymore, so the script is not able to find it
> ## Possible Solution (optional)
> 
> Update the code with the new element definition :
> xpath["like_image"] = {
> "like": "//section/span/button/div[[local-name()='svg']/@aria-label='Like']",
> "unlike": "//section/span/button/div[[local-name()='svg']/@aria-label='Unlike']",
> }
> ## InstaPy configuration
> 
> Modify the definition of the Like element

Instagram just did a change again to the html (couple of minutes ago). The same way you can change to the following lines in `xpath_compile.py` file:

`xpath["like_image"] = {
    "like": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Like']",
    "unlike": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Unlike']",
}`

Actually Instagram added one more html element 'span' after the last 'div'. Try to replace with the code above, it worked for me. Hopefully it'd work for you too :)

**Comment by alfanme** [comment]
> there is a open PR which should fix this problem. for now you can change these lines in the file `xpath_compile.py`
> 
> ```
> xpath["like_image"] = {
>     "like": "//section/span/button/div[*[local-name()='svg']/@aria-label='Like']",
>     "unlike": "//section/span/button/div[*[local-name()='svg']/@aria-label='Unlike']",
> }
> ```

Instagram just did a change again to the html (couple of minutes ago). The same way you can change to the following lines in `xpath_compile.py` file:

```
xpath["like_image"] = {
    "like": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Like']",
    "unlike": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Unlike']",
}
```

Actually Instagram added one more html element 'span' after the last 'div'. Try to replace with the code above, it worked for me. Hopefully it'd work for you too :)

**Comment by dipen412** [comment]
> > there is a open PR which should fix this problem. for now you can change these lines in the file `xpath_compile.py`
> > ```
> > xpath["like_image"] = {
> >     "like": "//section/span/button/div[*[local-name()='svg']/@aria-label='Like']",
> >     "unlike": "//section/span/button/div[*[local-name()='svg']/@aria-label='Unlike']",
> > }
> > ```
> 
> Instagram just did a change again to the html (couple of minutes ago). The same way you can change to the following lines in `xpath_compile.py` file:
> 
> ```
> xpath["like_image"] = {
>     "like": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Like']",
>     "unlike": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Unlike']",
> }
> ```
> 
> Actually Instagram added one more html element 'span' after the last 'div'. Try to replace with the code above, it worked for me. Hopefully it'd work for you too :)

I'm still getting the Invalid Like Element! Error after using that code above, not sure why. I'm using a Mac and I have version 0.6.9, using FireFox to run the script using Selenium. Any Ideas?

**Comment by lucasandguitars** [comment]
I've had this issue before and got it solved https://github.com/timgrossmann/InstaPy/issues/5620#issuecomment-658488523

Worked for a few weeks, but now I'm getting the Invalid Like Element message again... Just checking in.

**Comment by lucasandguitars** [comment]
@alfanme 's solution is working for me, for now

**Comment by exesse** [comment]
Should we add try block to the xpath with several possible options?

**Comment by Booleboole** [comment]
@alfanme work perfect....
Many Thanks

**Comment by tperas** [comment]
> > there is a open PR which should fix this problem. for now you can change these lines in the file `xpath_compile.py`
> > ```
> > xpath["like_image"] = {
> >     "like": "//section/span/button/div[*[local-name()='svg']/@aria-label='Like']",
> >     "unlike": "//section/span/button/div[*[local-name()='svg']/@aria-label='Unlike']",
> > }
> > ```
> 
> Instagram just did a change again to the html (couple of minutes ago). The same way you can change to the following lines in `xpath_compile.py` file:
> 
> ```
> xpath["like_image"] = {
>     "like": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Like']",
>     "unlike": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Unlike']",
> }
> ```
> 
> Actually Instagram added one more html element 'span' after the last 'div'. Try to replace with the code above, it worked for me. Hopefully it'd work for you too :)

This one work for me too! Thanks

**Comment by Mohammed-Ashik-KP** [comment]
Could someone share how you find these paths? i tried with some extentions and  use it in the code, it does'nt worked for me !
However Thank You @alfanme  for the update! :heart_eyes:

**Comment by alfanme** [comment]
> Could someone share how you find these paths? i tried with some extentions and use it in the code, it does'nt worked for me !
> However Thank You @alfanme for the update! 😍

Glad I can help you all guys.

Regarding @Aashiq-Otp request,

Here's the way how you check the path of like and unlike button.
1. Open any post on Instagram on your browser
2. Make sure you open the post page in the full page, not a modal/pop-up page (if you open the post in pop-up mode. Hit the refresh/reload button on the browser)
3. Go to inspect element, if you familiar with inspect element, there's a button with cursor and box around it, I use firefox so it's on the top left corner of the inspect element window. Click the icon, and hover onto the post's like button.
4. There you can see the html structure hierarchy of the button. The very top left tag is the parent, and more tags go along to the bottom right (indentation).
5. In this case, just ignore the outer <div> tag. Start from the <section> one (the child of outer div). Match the path with the html hierarchy from section tag all the way before the <svg> tag. In the previous case, I found out that IG added one more <span> tag before the <svg> tag which is the like icon.

By the way, I made the steps in picture so you can get the visual --> [How to check like/unlike button path](https://drive.google.com/file/d/13eCAjmWxbIoxvShr9cfPL-KHjyZQywtl/view?usp=sharing)

Hopefully this could help you all to solve this problem in the future 👌🏼

**Comment by draceman** [comment]
how do we change the lines in the xpath file?

**Comment by peppe-p** [comment]
> > there is a open PR which should fix this problem. for now you can change these lines in the file `xpath_compile.py`
> > ```
> > xpath["like_image"] = {
> >     "like": "//section/span/button/div[*[local-name()='svg']/@aria-label='Like']",
> >     "unlike": "//section/span/button/div[*[local-name()='svg']/@aria-label='Unlike']",
> > }
> > ```
> 
> Instagram just did a change again to the html (couple of minutes ago). The same way you can change to the following lines in `xpath_compile.py` file:
> 
> ```
> xpath["like_image"] = {
>     "like": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Like']",
>     "unlike": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Unlike']",
> }
> ```
> 
> Actually Instagram added one more html element 'span' after the last 'div'. Try to replace with the code above, it worked for me. Hopefully it'd work for you too :)

I dont know why.. but this dont work for me... 
I checked the HTML, and "span" was added, but despite editing and updating Instapy, it continues to give "Invalid like element".

**Comment by Lisiadito** [comment]
Just updated to the newest version and it seems to work fine now.

**Comment by peppe-p** [comment]
I updated yesterday, and it worked.
But today I try to start the script, and again "Invalid Like Element".
I checked the html of the instagram page, everything is right... idk what is the problem!
