### ISSUE TITLE
Login Problems

### ISSUE THREAD

**Issue by leoleoleole** [InstaPy/InstaPy#5653]
**InstaPy isn't logging in, but isn't recognizing that.** It's trying to like posts and follow accounts, but doesn't know that its not logged in. 
It's also not giving me an error message for that.

## Expected Behavior

InstaPy working. Liking and Following Accounts.

## Current Behavior

InstaPy is trying to like and follow Accounts, while not noticing nothing happening due to it not being logged in. Not giving out an error message.

## InstaPy configuration

I am using InstaPy 0.6.9 on Windows 10 with a custom quickstart template. But this error also occurs when I use the standart quickstart.py

**Comment by Ariel-Esteves** [comment]
i have the same problem

**Comment by zubus** [comment]
Try to delete account folder in Instapy example for win: `C:\Users\<yourusername>\InstaPy\logs\<igaccount>`

**Comment by leoleoleole** [comment]
> Try to delete account folder in Instapy example for win: `C:\Users\<yourusername>\InstaPy\logs\<igaccount>`

that didn't change anything
