### ISSUE TITLE
Element is not clickable at point because another element <path> obscures it

### ISSUE THREAD

**Issue by tanmald** [InstaPy/InstaPy#5660]
## Expected Behavior
follow_likers action follows list of users retrieved.

## Current Behavior
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/util.py", line 946, in click_element
    element.click()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class="sqdOP  L3NKy _4pI4F  y3zKF     " type="button"> is not clickable at point (98,675) because another element <path> obscures it

**Comment by elissonnog** [comment]
Same problem here

**Comment by dwikyrestu** [comment]
Same problem, before it i was change xpath_compile because an invalid image element. Actually Instagram added one more html element 'span' after the last 'div'. So i change xpath_compile.py like this : https://github.com/timgrossmann/InstaPy/issues/5650#issuecomment-665144354 

It works in 3 first image, but after that it return :

`selenium.common.exceptions.ElementClickInterceptedException: Message: Element <span class=""> is not clickable at point (675,558) because another element <div class="q02Nz _0TPg"> obscures it`

**Comment by dwikyrestu** [comment]
I just try to maximize the window and it works for now

**Comment by tataman22** [comment]
I'm having the same problem. It works for a while (about 16 likes) and It fails. I restart ans same issue again and again. Any idea why?

**Comment by gixxerfrank** [comment]
I updated the viewport settings in the browser.py and it seems to be working fine now.

**Comment by elissonnog** [comment]
> I updated the viewport settings in the browser.py and it seems to be working fine now.

Could you post how and where did you change?

**Comment by gixxerfrank** [comment]
I updated line 139 in browser.py to: browser.set_window_size(375, 896)

**Comment by Achleuhi** [comment]
> I updated line 139 in browser.py to: browser.set_window_size(375, 896)

works fine for me thx !

**Comment by alex-wahl** [comment]
The same issue in the mode headless_browser=True

**Comment by gabriel-lemelle** [comment]
linked to #5719

**Comment by elulcao** [comment]
I recently fixed #5809, seems to be a similar issue. 
Reviewing the code.

**Comment by elulcao** [comment]
> ## Expected Behavior
> follow_likers action follows list of users retrieved.
> 
> ## Current Behavior
> Traceback (most recent call last):
> File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instapy/util.py", line 946, in click_element
> element.click()
> File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
> self._execute(Command.CLICK_ELEMENT)
> File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
> return self._parent.execute(command, params)
> File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.ElementClickInterceptedException: Message: Element is not clickable at point (98,675) because another element obscures it
> 
> ## Possible Solution (optional)
> ## InstaPy configuration

What is your configuration for session.follow_likers()?

```python
session.follow_likers(
            ['nike' ,
            'adidasoriginals'
            ],
            photos_grab_amount = 10,
            follow_likers_per_photo = 3,
            randomize=True,
            sleep_delay=600,
            interact=False)
```

**Comment by elulcao** [comment]
After clicked the `Liked xpath` a new window should be displayed, 
in this case (using InstaPy 0.6.11 and macOS with geckodriver 0.27) 
the new page is actually loaded but greyed out, so next info cannot
be extracted. I tried to load the `likers` by hand but same problem 
for loading the page (check screenshot). I believe the issue comes 
from geckodriver and changes from Instagram. 

Enabled debug for gecko driver and found that page was not loaded
```bash
1601748156816	Marionette	DEBUG	0 -> [0,82,"WebDriver:ElementClick",{"id":"0e41efc8-8009-be4d-a13a-ae421fb3ca0e"}]
1601748157081	Marionette	DEBUG	[16] Canceled page load listener because no navigation has been detected <== HERE
1601748157082	Marionette	DEBUG	0 <- [1,82,null,{"value":null}]
1601748157083	webdriver::server	DEBUG	<- 200 OK {"value":null} <== HERE
```

![Captura de Pantalla 2020-10-03 a la(s) 0 06 02](https://user-images.githubusercontent.com/6373960/94998802-27fd6900-057a-11eb-9b20-36cb96705404.png)
