### ISSUE TITLE
Blocked Account

### ISSUE THREAD

**Issue by anagrou** [InstaPy/InstaPy#5661]
Hello,

I was wondering what should I use to don't get blocked in the Instagram browser. After the script has been executed and stopped I can't use my Instagram on the browser, only on the mobile phone. It always gives the error that I can't do the action at the moment and to try later on. I can't access messages, like, post, anything.

Is it because of the IP? How long will I have to wait?

Furthermore, Shall I use the quota supervisor? Does it helps?

Looking forward to hear from you, many thanks!

**Comment by CamiloB** [comment]
hi, you should always use quota supervisor, and i recommend that you need to start very slow like follow 10 people in a day and give 50 likes then you should going up until you find a good way for you account.

**Comment by gvmturl** [comment]
https://github.com/alexal1/Insomniac

@anagrou @CamiloB

Try insomniac + android emulator
