### ISSUE TITLE
failed to check comments (after updating firefox & instapy)

### ISSUE THREAD

**Issue by schaema81** [InstaPy/InstaPy#5665]
## Current Behavior

When trying to act on comments, always receiving a 
 Failed to check comments' status for verification!
        b'Message: TypeError: window.__additionalData[Object.keys(...)[0]] is undefined\n'

(Right before, I updated firefox and all pip's (incl. instapy)
Checked posts: all have "comments enabled" and most have comments (comments exist)

**Comment by gvmturl** [comment]
Why don't you try insomniac + any android emulator?


https://github.com/alexal1/Insomniac
