### ISSUE TITLE
Failed to check comments' status for verification

### ISSUE THREAD

**Issue by rouncewell** [InstaPy/InstaPy#5666]
## Expected Behavior

When ever InstaPy wants to set a comment on a post, I receive the following error:

`--> Not commenting! Failed to check comments' status for verification!
	b'Message: TypeError: window.__additionalData[Object.keys(...)[0]] is undefined\n'`

Any ideas? I've not made any changes to the xpath_compile.py other than "like_image" xpath because of recent IG updates.

**Comment by opamuk** [comment]
Were you able to solve your problem? I have the same right now. As I see there a couple of opened issues but no solution is recorded.

**Comment by nirsky** [comment]
Same here. Using version 0.6.12. Any solution?
