### ISSUE TITLE
Remove Ghost Followers

### ISSUE THREAD

**Issue by majnoonxyz** [InstaPy/InstaPy#5668]
is there anyway to remove ghost followers using instapy?

**Comment by gvmturl** [comment]
Try insomniac 

https://github.com/alexal1/Insomniac

**Comment by Amai98** [comment]
> Try insomniac
> 
> https://github.com/alexal1/Insomniac

Stop spam lol

**Comment by gvmturl** [comment]
> > Try insomniac
> > https://github.com/alexal1/Insomniac
> 
> Stop spam lol

"Stop spam lol" post seems to be spam, my answer seems to be a solution.

Thanks
