### ISSUE TITLE
Cannot Fetch Links For Analysis From Feed : Total of links feched for analysis: 0 Possible Error WIth session.like_by_feed()

### ISSUE THREAD

**Issue by Mohammed-Ashik-KP** [InstaPy/InstaPy#5669]
`session.like_by_feed()`   cant be perfomed !
## Current Behavior 
The Log Shows : 
INFO [2020-07-29 20:45:53] [Aashiq_Otp]  Saving account progress...
INFO [2020-07-29 20:46:45] [Aashiq_Otp]  Total of links feched for analysis: 0
INFO [2020-07-29 20:47:15] [Aashiq_Otp]  Total of links feched for analysis: 0
INFO [2020-07-29 20:47:47] [Aashiq_Otp]  Total of links feched for analysis: 0
INFO [2020-07-29 20:48:20] [Aashiq_Otp]  Total of links feched for analysis: 0
INFO [2020-07-29 20:48:55] [Aashiq_Otp]  Total of links feched for analysis: 0
INFO [2020-07-29 20:49:33] [Aashiq_Otp]  Total of links feched for analysis: 0
INFO [2020-07-29 20:50:13] [Aashiq_Otp]  Total of links feched for analysis: 0
INFO [2020-07-29 20:50:56] [Aashiq_Otp]  Total of links feched for analysis: 0
INFO [2020-07-29 20:51:41] [Aashiq_Otp]  Total of links feched for analysis: 0
INFO [2020-07-29 20:52:30] [Aashiq_Otp]  Total of links feched for analysis: 0
WARNING [2020-07-29 20:52:30] [Aashiq_Otp]  Loop error, 0 links for 10 times consecutively, exit loop

** I cross checked the problem and found that Instagram has removed the links for each post from the news feed. There is no direct hyperlink to a post currently. I don't if this error is because of that!**

**Comment by LeydenJar** [comment]
Yeah, same thing here

**Comment by LeydenJar** [comment]
Well, a lean solution would be to just find and click the like elements, without collecting the links. I suppose this involves sacrificing a lot of functionality from InstaPy when using like_by_feed...

**Comment by Mohammed-Ashik-KP** [comment]
> 
> 
> Well, a lean solution would be to just find and click the like elements, without collecting the links. I suppose this involves sacrificing a lot of functionality from InstaPy when using like_by_feed...

Yeah...I think we can only get first 4 or 5 posts from the feed, i just have a try by finding the like elements and only able to get first few posts 😢

**Comment by LeydenJar** [comment]
> hink we can only get first 4 or 5 posts from the feed, i just have a try by finding the like elements and only able to get first few

Have you scrolled the page down so that more posts load?

**Comment by filipeluizzz** [comment]
Same error here

**Comment by LeydenJar** [comment]
Ok so, I was having a look at the PRs and looks like there's a fix already: https://github.com/timgrossmann/InstaPy/pull/5685
