### ISSUE TITLE
Solution to bug 'Error, unable to determine correct filename for 64bit linux'

### ISSUE THREAD

**Issue by LeydenJar** [InstaPy/InstaPy#5672]
## Expected Behavior
Ok, so, I'm just getting started with InstaPy, but I'm supposing that when you start a session, we check either the geckodriver we have is the latest version or not, and if it is not the case then the expected behavior is to download the new one and start it...
 
## Current Behavior
Turns out that currently, with geckodriver 0.27, you get this error on linux 64 bit when trying to start an InstaPy session.

'Error, unable to determine correct filename for 64bit linux'

## Possible Solution (optional)

The reason is that the code in the webdriverdownloader dependency, wich gets the list of possible geckodriver versions to download and then filters for the ones that match your os and if it is 32 or 64 bit. Then it expects to have only one left in the list, wich it downloads. Turns out there are 2 now, with 2 extensions(something like '.tar.gz' and '.tar.gz.asc'). So the solution is to remove one of them so that we don't fall on the exception.
The one we want to remove is the one that ends on .asc cause apparently the program is expecting the other one

You can do that by changing a single line, i just made a pull request here where you can check it out: https://github.com/leonidessaguisagjr/webdriverdownloader/pull/12

After that all works fine...

**Comment by operador777** [comment]
Thanks man, tested and working.

**Comment by gixxerfrank** [comment]
I am having the same issue running on Digital Ocean and am unsure of how exactly to apply this fix

**Comment by LeydenJar** [comment]
@gixxerfrank So what you should do is go to your virtual environment or wherever your pip is installing your project dependencies and then find the folder webdriverdownloader. The path may be something like this:

/home/ubuntu/apps/InstaPy/venv/lib/python3.6/site-packages/webdriverdownloader

Then, inside this folder you have to edit the file 'webdriverdownloader.py'

Arround the line 320 there's a line like this:
filename = [name for name in filenames if os_name + bitness in name ]

What you want to do is change it to something like this:

filename = [name for name in filenames if os_name + bitness in name and name[-3:] != 'asc' ]

or even this:

filename = [name for name in filenames if os_name + bitness in name and name[-7:] == '.tar.gz' ]

**Comment by elissonnog** [comment]
Works well, thanks a lot

**Comment by colinmasters** [comment]
Nice man thanks!

**Comment by gixxerfrank** [comment]
> @gixxerfrank So what you should do is go to your virtual environment or wherever your pip is installing your project dependencies and then find the folder webdriverdownloader. The path may be something like this:
> 
> /home/ubuntu/apps/InstaPy/venv/lib/python3.6/site-packages/webdriverdownloader
> 
> Then, inside this folder you have to edit the file 'webdriverdownloader.py'
> 
> Arround the line 320 there's a line like this:
> filename = [name for name in filenames if os_name + bitness in name ]
> 
> What you want to do is change it to something like this:
> 
> filename = [name for name in filenames if os_name + bitness in name and name[-3:] != 'asc' ]
> 
> or even this:
> 
> filename = [name for name in filenames if os_name + bitness in name and name[-7:] == '.tar.gz' ]

Thanks so much, it works great!

**Comment by samuellmiller** [comment]
I am having the same issue but when I deploy it in Heroku. How should I do?

**Comment by LeydenJar** [comment]
@samuellmiller The problem is in the webdriverdownloader module. So, I'm not sure on how Heroku works but you must have a way to connect to the server or something. What you have to do then is find out where pip is installing stuff(for example running 'pip show webdriverdownloader' and looking at location) then you go and do the edits that I've mentioned...

**Comment by ansango** [comment]
1. pip show webdriverdownloader
2. search location generated
3.  change line 320 (+-) " filename = [name for name in filenames if os_name + bitness in name ] " by: 

 - filename = [name for name in filenames if os_name + bitness in name and name[-3:] != 'asc' ] 

   or:

 - filename = [name for name in filenames if os_name + bitness in name and name[-7:] == '.tar.gz' ]

4. execute "your_templare.py"


Thank You @LeydenJar <3

**Comment by ArashMM** [comment]
I still get the error "RuntimeError: Error, unable to determine correct filename for 64bit linux"
Here's the full traceback: https://hastebin.com/aralizipaz.sql
Can someone help me?

**Comment by aramodi** [comment]
Thank you very much!

**Comment by lgv-0** [comment]
Verified on Ubuntu 16.04.6 LTS Server, thanks!

**Comment by thyarles** [comment]
**Effective way**

1. Make sure that your version is `webdrivermanager==0.8.0`

1. Go to your `env` dir

1. Create a file called `webdrivermanager.pach` with this content (copy exactly as is)
```
177c177
<             filename = [name for name in filenames if self.os_name + self.bitness in name]
---
>             filename = [name for name in filenames if self.os_name + self.bitness in name and name[-3:] != 'asc']
```
3. Apply the patch
```
patch -p0 $(find ./ -name webdrivermanager.py) < webdrivermanager.patch
```
4. Install your Firefox driver again, now it'll work
```
webdrivermanager firefox
```

**Comment by karan-jagtap** [comment]
> I am having the same issue but when I deploy it in Heroku. How should I do?

Did you find any solution for heroku? I solved the issue locally but unable to solve it on heroku. I'm able to make changes, but dynos does not make permanent changes. And hence it is just for time being.

**Comment by Courxge** [comment]
i cannot find the webdriver folder.. i am very inexperienced with coding and attempted to follow the steps but i cannot find this folder anywhere.. I've located the InstaPy folder but inside of that are assets, db, and logs, none of which lead to webdriver

**Comment by Courxge** [comment]
> i cannot find the webdriver folder.. i am very inexperienced with coding and attempted to follow the steps but i cannot find this folder anywhere.. I've located the InstaPy folder but inside of that are assets, db, and logs, none of which lead to webdriver

i am using ubuntu btw

**Comment by thyarles** [comment]
Hi @Courxge and @kmessilj,

It was fixed on version 0.9.0. Just update your version with

    pip install webdrivermanager==0.9.0

**Comment by thursd4y** [comment]
When starting instapy manually on my raspberry everything works fine, but doing it via cronjob does not work.

I just tried both versions of the proposed script. Both then yield the  new following error: 
OSError: [Errno 8] Exec format error: '/home/pi/InstaPy/assets/geckodriver'

**Comment by ghost** [comment]
-----> Installing requirements with pip
 !     error fetching custom buildpack https://github.com/LeydenJar/webdriverdownloader/tree/fix_linux_64
 !     Push failed

Issue when deploy in heroku

**Comment by saribricka** [comment]
I tried @LeydenJar solution but it isn't working

```
$ python mainrun.py
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/saribricka/InstaPy"
Error, unable to determine correct filename for 64bit linux
Traceback (most recent call last):
  File "mainrun.py", line 30, in <module>
    session = InstaPy(username=insta_username,
  File "/home/saribricka/.local/lib/python3.8/site-packages/instapy/instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/home/saribricka/.local/lib/python3.8/site-packages/instapy/browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/home/saribricka/.local/lib/python3.8/site-packages/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/home/saribricka/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/home/saribricka/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/home/saribricka/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit linux
```

**Comment by RomjanHossain** [comment]
@saribricka make sure you did it right.
1. goto line 320 of webdriverdownloader.py (`~/.local/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py`)
2. edit this line `filename = [name for name in filenames if os_name in name]` to `filename = [name for name in filenames if os_name + bitness in name and name[-3:]!='asc']`
3. Done.

I was having the same issue on Manjaro Linux. 

another solution is: _create a virtual environment and run `instapy` on that._

**Comment by ghost** [comment]
kts@HP-Laptop:~$ python3 /home/kts/Scaricati/gianscript.py 
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/kts/InstaPy"
Error, unable to determine correct filename for 64bit linux
Traceback (most recent call last):
  File "/home/kts/Scaricati/gianscript.py", line 39, in <module>
    session = InstaPy(username=insta_username,
  File "/home/kts/.local/lib/python3.8/site-packages/instapy/instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/home/kts/.local/lib/python3.8/site-packages/instapy/browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/home/kts/.local/lib/python3.8/site-packages/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/home/kts/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/home/kts/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/home/kts/.local/lib/python3.8/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit linux


please help!!!

**Comment by RomjanHossain** [comment]
read previous comments bruh @ITzMirko

**Comment by trankov** [comment]
No, guys, now the changing of line 320 as it shown above doesn't work.
It seems Mozilla renewed filenames again (last release was Apr 29th 2021).
Everything says that problem will appear again and again.

Let me explain quickly how to fix it every time.

First, below is the list of binaries for last release:
https://github.com/mozilla/geckodriver/releases/

Now let's see at `webdriverdownloader.py`
In lines **313**, **314** it tries to find out the correct filename for download:
```python
filenames = [asset['name'] for asset in json_data['assets']]
filename = [name for name in filenames if os_name in name]
```
(The `json_data['assets']` contains list of dicts `{'name', 'browser_download_url'}`, then the script extracts to `filename` items which contains OS name).
F.e. on my MacOS 11.3.1 `filenames` are:
```python
['geckodriver-v0.29.1-linux32.tar.gz', 'geckodriver-v0.29.1-linux32.tar.gz.asc', 'geckodriver-v0.29.1-linux64.tar.gz', 'geckodriver-v0.29.1-linux64.tar.gz.asc', 'geckodriver-v0.29.1-macos-aarch64.tar.gz', 'geckodriver-v0.29.1-macos.tar.gz', 'geckodriver-v0.29.1-win32.zip', 'geckodriver-v0.29.1-win64.zip']
```
And then `filename`:
```python
['geckodriver-v0.29.1-macos-aarch64.tar.gz', 'geckodriver-v0.29.1-macos.tar.gz']
```
After this we comes to our beloved string **320**:
```python
filename = [name for name in filenames if os_name + bitness in name]
```
Here in my case `os_name + bitness == 'macos64'`, and, of course, it cannot find it. The `filename == []` and line **321** raises an Error.
Of course, we can just hardcode the right name of file:
```python
filename = ['geckodriver-v0.29.1-macos-aarch64.tar.gz']
```
Or, we can add more common condition which is checking whether list item contains both `'mac'` and `'64'`:
```python
#filename = [name for name in filenames if os_name + bitness in name]
filename = [name for name in filenames if os_name in name and bitness in name]
```
Now it can find and download the binary. But there is another problem, it's a file for M1 CPU :) My Mac is Intel.

Anyway, now you know how and where to fix this issue. I will not explain the solution for my precise platform*, because we need the common recipe for everyone. Unfortunately, it's a handwork. Fortunately, we know what to do. Just change the condition at the end of the line 320 for your own (also I hope my solution will work correctly for all except of Intel Mac users).

*Okay, I just changed the condition to: `os_name in name and 'aarch' not in name` and got the successfull result.
