### ISSUE TITLE
Fail to detect and like comments under a post

### ISSUE THREAD

**Issue by TR111** [InstaPy/InstaPy#5676]
Hey all,

Unfortunatly, I've run into an issue with the InstaPy package that I could not yet solve and hope that someone here can help me to find a solution. I could not find any existing or solved issue about this here.

## Expected Behavior
I try to build a bot that'll like the comments written under a post on Instagram. I don't want to answer or interact with users, just like the comments.

## Current Behavior
The program does log-in to my account, finds the account of the user whose posts' comments I want to like and opens the posts, but it then does not like the respective comments under the posts and replies:

INFO [2020-07-30 19:32:07] []  There are no any comments available on this post.
INFO [2020-07-30 19:32:07] []  No interaction did happen.

However, I know that there ARE comments and it just does not detect those.

I use the following code on the quickstart.py file:

```
from instapy import InstaPy
from instapy import smart_run

insta_username = '***'
insta_password = '***'

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    session.set_do_like(enabled=True, percentage=100)
    session.interact_by_comments(usernames=["***"],
                                posts_amount=1,
                                comments_per_post=10,
                                reply=True,
                                interact=True,
                                randomize=True,
                                media='Video')
```

Does anyone have an idea where the mistake is in the code?

I already tried a lot of configurations, but all other options did not work at all and often led to an error. Maybe I am not yet experienced enough with programming, but I hope that someone can give me a hint on which part I should focus to solve this issue.

Best,
Tobias

**Comment by TR111** [comment]
Hey guys,
I still could not figure it out. The bot finds the posts but says there are no comments, even though there clearly are. :/ 

@timgrossmann, do you have an opinion where my mistake is and on what I should focus to solve this issue?

Thank you a lot,
Tobias

**Comment by sebet89** [comment]
> Hey all,
> 
> Unfortunatly, I've run into an issue with the InstaPy package that I could not yet solve and hope that someone here can help me to find a solution. I could not find any existing or solved issue about this here.
> 
> ## Expected Behavior
> I try to build a bot that'll like the comments written under a post on Instagram. I don't want to answer or interact with users, just like the comments.
> 
> ## Current Behavior
> The program does log-in to my account, finds the account of the user whose posts' comments I want to like and opens the posts, but it then does not like the respective comments under the posts and replies:
> 
> INFO [2020-07-30 19:32:07] [] There are no any comments available on this post.
> INFO [2020-07-30 19:32:07] [] No interaction did happen.
> 
> However, I know that there ARE comments and it just does not detect those.
> 
> I use the following code on the quickstart.py file:
> 
> ```
> from instapy import InstaPy
> from instapy import smart_run
> 
> insta_username = '***'
> insta_password = '***'
> 
> session = InstaPy(username=insta_username,
>                   password=insta_password,
>                   headless_browser=False)
> 
> with smart_run(session):
>     session.set_do_like(enabled=True, percentage=100)
>     session.interact_by_comments(usernames=["***"],
>                                 posts_amount=1,
>                                 comments_per_post=10,
>                                 reply=True,
>                                 interact=True,
>                                 randomize=True,
>                                 media='Video')
> ```
> 
> Does anyone have an idea where the mistake is in the code?
> 
> I already tried a lot of configurations, but all other options did not work at all and often led to an error. Maybe I am not yet experienced enough with programming, but I hope that someone can give me a hint on which part I should focus to solve this issue.
> 
> Best,
> Tobias

I have the same problem.

Managed to solve?

**Comment by sebet89** [comment]
> Hey guys,
> I still could not figure it out. The bot finds the posts but says there are no comments, even though there clearly are. :/
> 
> @timgrossmann, do you have an opinion where my mistake is and on what I should focus to solve this issue?
> 
> Thank you a lot,
> Tobias

I have the same problem.

Managed to solve?

**Comment by TR111** [comment]
No, not yet, unfortunately. Tried everything that came in my mind, but always get errors or only to liking media itself, but not comments on those pics, etc.

**Comment by Mohanbarman** [comment]
You guys got any solution ?

**Comment by elulcao** [comment]
From documentation: 
```
To use, set replying and interaction configuration(s)

session.set_do_reply_to_comments(enabled=True, percentage=14)
session.set_comment_replies(replies=[u"😎😎😎", u"😁😁😁😁😁😁😁💪🏼", u"😋🎉", "😀🍬", u"😂😂😂👈🏼👏🏼👏🏼", u"🙂🙋🏼‍♂️🚀🎊🎊🎊", u"😁😁😁", u"😂",  u"🎉",  u"😎", u"🤓🤓🤓🤓🤓", u"👏🏼😉"],
                            media="Photo")

session.set_user_interact(amount=2, percentage=70, randomize=False, media="Photo")
# also configure [at least] liking to be used while interacting with the commenters ...
session.set_do_like(enabled=True, percentage=94)

# start the feature
session.interact_by_comments(usernames=["somebody", "other.buddy"], posts_amount=10, comments_per_post=5, reply=True, interact=True, randomize=True, media="Photo")

Note: To be able to reply to comments, you have to turn on text analytics- Yandex & MeaningCloud.
So that they will analyze the content of comments and if it is appropriate, will send a reply to the comment.
To configure those text analytics, see the usage in their sections.
```

**Comment by Mohanbarman** [comment]
> From documentation:
> 
> ```
> To use, set replying and interaction configuration(s)
> 
> session.set_do_reply_to_comments(enabled=True, percentage=14)
> session.set_comment_replies(replies=[u"😎😎😎", u"😁😁😁😁😁😁😁💪🏼", u"😋🎉", "😀🍬", u"😂😂😂👈🏼👏🏼👏🏼", u"🙂🙋🏼‍♂️🚀🎊🎊🎊", u"😁😁😁", u"😂",  u"🎉",  u"😎", u"🤓🤓🤓🤓🤓", u"👏🏼😉"],
>                             media="Photo")
> 
> session.set_user_interact(amount=2, percentage=70, randomize=False, media="Photo")
> # also configure [at least] liking to be used while interacting with the commenters ...
> session.set_do_like(enabled=True, percentage=94)
> 
> # start the feature
> session.interact_by_comments(usernames=["somebody", "other.buddy"], posts_amount=10, comments_per_post=5, reply=True, interact=True, randomize=True, media="Photo")
> 
> Note: To be able to reply to comments, you have to turn on text analytics- Yandex & MeaningCloud.
> So that they will analyze the content of comments and if it is appropriate, will send a reply to the comment.
> To configure those text analytics, see the usage in their sections.
> ```

From documentation:

```
To use, set replying and interaction configuration(s)

session.set_do_reply_to_comments(enabled=True, percentage=14)
session.set_comment_replies(replies=[u"😎😎😎", u"😁😁😁😁😁😁😁💪🏼", u"😋🎉", "😀🍬", u"😂😂😂👈🏼👏🏼👏🏼", u"🙂🙋🏼‍♂️🚀🎊🎊🎊", u"😁😁😁", u"😂",  u"🎉",  u"😎", u"🤓🤓🤓🤓🤓", u"👏🏼😉"],
                            media="Photo")

session.set_user_interact(amount=2, percentage=70, randomize=False, media="Photo")
# also configure [at least] liking to be used while interacting with the commenters ...
session.set_do_like(enabled=True, percentage=94)

# start the feature
session.interact_by_comments(usernames=["somebody", "other.buddy"], posts_amount=10, comments_per_post=5, reply=True, interact=True, randomize=True, media="Photo")

Note: To be able to reply to comments, you have to turn on text analytics- Yandex & MeaningCloud.
So that they will analyze the content of comments and if it is appropriate, will send a reply to the comment.
To configure those text analytics, see the usage in their sections.
```

**Comment by Mohanbarman** [comment]
> From documentation:
> 
> ```
> To use, set replying and interaction configuration(s)
> 
> session.set_do_reply_to_comments(enabled=True, percentage=14)
> session.set_comment_replies(replies=[u"😎😎😎", u"😁😁😁😁😁😁😁💪🏼", u"😋🎉", "😀🍬", u"😂😂😂👈🏼👏🏼👏🏼", u"🙂🙋🏼‍♂️🚀🎊🎊🎊", u"😁😁😁", u"😂",  u"🎉",  u"😎", u"🤓🤓🤓🤓🤓", u"👏🏼😉"],
>                             media="Photo")
> 
> session.set_user_interact(amount=2, percentage=70, randomize=False, media="Photo")
> # also configure [at least] liking to be used while interacting with the commenters ...
> session.set_do_like(enabled=True, percentage=94)
> 
> # start the feature
> session.interact_by_comments(usernames=["somebody", "other.buddy"], posts_amount=10, comments_per_post=5, reply=True, interact=True, randomize=True, media="Photo")
> 
> Note: To be able to reply to comments, you have to turn on text analytics- Yandex & MeaningCloud.
> So that they will analyze the content of comments and if it is appropriate, will send a reply to the comment.
> To configure those text analytics, see the usage in their sections.
> ```

If you have followed any of those 3 text analysis combinations:
It will first analyze comments' content and if it is appropriate, then it will first like, then will reply to it.
All those inappropriate comments will neither be liked, nor replied to.

If you have not followed any of those 3 text analysis combinations OR misconfigured them:
Comments' content will not be able to be analyzed and that's why no any comments will be replied.
Yet, it will like all of the comments that are available.

**Comment by Mohanbarman** [comment]
> > From documentation:
> > ```
> > To use, set replying and interaction configuration(s)
> > 
> > session.set_do_reply_to_comments(enabled=True, percentage=14)
> > session.set_comment_replies(replies=[u"😎😎😎", u"😁😁😁😁😁😁😁💪🏼", u"😋🎉", "😀🍬", u"😂😂😂👈🏼👏🏼👏🏼", u"🙂🙋🏼‍♂️🚀🎊🎊🎊", u"😁😁😁", u"😂",  u"🎉",  u"😎", u"🤓🤓🤓🤓🤓", u"👏🏼😉"],
> >                             media="Photo")
> > 
> > session.set_user_interact(amount=2, percentage=70, randomize=False, media="Photo")
> > # also configure [at least] liking to be used while interacting with the commenters ...
> > session.set_do_like(enabled=True, percentage=94)
> > 
> > # start the feature
> > session.interact_by_comments(usernames=["somebody", "other.buddy"], posts_amount=10, comments_per_post=5, reply=True, interact=True, randomize=True, media="Photo")
> > 
> > Note: To be able to reply to comments, you have to turn on text analytics- Yandex & MeaningCloud.
> > So that they will analyze the content of comments and if it is appropriate, will send a reply to the comment.
> > To configure those text analytics, see the usage in their sections.
> > ```
> 
> If you have followed any of those 3 text analysis combinations:
> It will first analyze comments' content and if it is appropriate, then it will first like, then will reply to it.
> All those inappropriate comments will neither be liked, nor replied to.
> 
> If you have not followed any of those 3 text analysis combinations OR misconfigured them:
> Comments' content will not be able to be analyzed and that's why no any comments will be replied.
> Yet, it will like all of the comments that are available.

Mentioned in the documentation, It should also work without text analytics
