### ISSUE TITLE
Error: Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by draceman** [InstaPy/InstaPy#5678]
I am running instapy and it was working just fine with my IG account then all of a sudden this error starting popping up over and over, it happens when the script gets to the "Saving account progress..." line. 

Does anyone know what is going wrong here?

**Comment by bronzeboy** [comment]
> I am running instapy and it was working just fine with my IG account then all of a sudden this error starting popping up over and over, it happens when the script gets to the "Saving account progress..." line.
> 
> Does anyone know what is going wrong here?

You got soft banned by Instagram for too many API calls, configure a working quota supervisor that work for your account.

**Comment by rouncewell** [comment]
Is every like/comment given a single server call? Or is it a server call every-time a notification is displayed in terminal ? Like when it shows you the link, the name of the account, the description, etc. That would be 4-5 server calls or just 1?
