### ISSUE TITLE
error: im getting "invalid like element" now

### ISSUE THREAD

**Issue by draceman** [InstaPy/InstaPy#5682]
im trying to run the smart run session like by tags but now im getting the ""invalid like element" does anyone know how to fix this ?

**Comment by bronzeboy** [comment]
> im trying to run the smart run session like by tags but now im getting the ""invalid like element" does anyone know how to fix this ?

https://github.com/timgrossmann/InstaPy/issues/5650#issuecomment-665144354

**Comment by draceman** [comment]
How do I unauthor the thread? What does it mean that I authored the thread? That I manually clicked something? 

Moses Moreno
