### ISSUE TITLE
Browser Fehler?

### ISSUE THREAD

**Issue by SAMXODE** [InstaPy/InstaPy#5686]
![wrong](https://user-images.githubusercontent.com/31543427/89180345-e6f4d280-d591-11ea-9ada-f40e097700a7.png)

Wie kann ich diesen Fehler beheben?

Ich habe InstaPy auf DigitalOcean Ubuntu laufen..

**Comment by LeydenJar** [comment]
I've posted the solution for that here:

https://github.com/timgrossmann/InstaPy/issues/5672

**Comment by LeydenJar** [comment]
Ich habe die Lösung dafür hier gepostet:

https://github.com/timgrossmann/InstaPy/issues/5672
