### ISSUE TITLE
no follow / no comment

### ISSUE THREAD

**Issue by olecoding** [InstaPy/InstaPy#5689]
## Expected Behavior
-->Image Liked!
--> Commented!
--> Followed!
## Current Behavior
--> Image Liked!
**--> Not commented**
**--> Not following**
## InstaPy configuration

from instapy import InstaPy

# login-section
session = InstaPy(username='myusername', password='mypassword')
session.login()

# like-section
session.like_by_tags(['hashtagone', 'hashtagtwo'], amount=10)

# follow-section
session.set_do_follow(True, percentage=25)

#comment section
session.set_do_comment(True, percentage=25)
session.set_comments('comment')

session.end()

**Comment by fadimanar** [comment]
Me too same issue

**Comment by drivenrajat** [comment]
I am having the same issue. Any help?

**Comment by aitelkob** [comment]
The same
