### ISSUE TITLE
Like the photo of the URL

### ISSUE THREAD

**Issue by hestuppfodarn** [InstaPy/InstaPy#569]
Hi,

I want to be able to enter multiple URL's and like the specific photo of the url,
Like_from_image only likes the image of the tag of the url.  

.set_do_like(URL='https://www.instagram.com/p/BX5tNWcAkUe/', amount=1)\
Does not work eather.. 

I didn't find anything when searching - if the issue/request already has been solved - please just send me the link to the thread. 
Thanks :)

**Comment by timgrossmann** [comment]
@hestuppfodarn `.set_do_like()` only works with the `.interact_user_...` feature.

 `.set_do_like(URL='https://www.instagram.com/p/BX5tNWcAkUe/', amount=1)` it also does not look like this... it's `.set_do_like(True, percentage=10)`

**Comment by hestuppfodarn** [comment]
Thanks for the quick reply, and sorry for being such a rookie on this. 
But for instance, I have a list of 20 URL's, which I want to like the specific post it directs you to.
How do I write this?

**Comment by timgrossmann** [comment]
@hestuppfodarn You can't... What would be the use case for such a feature? 
If you select the posts which you want to interact with by hand, you could simply like and comment them yourself.

Am I missing something?

**Comment by hestuppfodarn** [comment]
for instance, if i'm in a group of several people and all of them are posting a url.
But I could totally agree that this is not a case for everybody.

I saw something about making a request and setting a reward. How do I do this?
Thanks again @timgrossmann

**Comment by rsabir** [comment]
@timgrossmann This is an interesting feature for all users of pods, for instance: telegram pods. The bots will give you a list of URL to like so you can post your link.
