### ISSUE TITLE
Smart Hashtags are not working

### ISSUE THREAD

**Issue by gixxerfrank** [InstaPy/InstaPy#5690]
## 
Smart Hashtags do not work. It logs in and then crashes. However, the smart location hashtag function works perfect.

```
session.set_smart_hashtags(['cycling',` 'bike'], limit=3, sort='top', log_tags=True)
session.like_by_tags(amount=10, use_smart_hashtags=True)
```
```
Traceback (most recent call last):
  File "/mm/mm/Projects/mm/mm/SMARTTags.py", line 45, in <module>
    session.set_smart_hashtags(['bike', 'cycling'], limit=3, sort='top', log_tags=True)
  File "/mm/mm/Projects/mm/mm/instapy/instapy.py", line 695, in set_smart_hashtags
    data = json.loads(req.text)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
` """Generate smart hashtags based on https://displaypurposes.com/"""
        """ranking, banned and spammy tags are filtered out."""

        if tags is None:
            print("set_smart_hashtags is misconfigured")
            return

        for tag in tags:
            req = requests.get("https://apidisplaypurposes.com/tag/".format(tag))
            data = json.loads(req.text)

            if data["tagExists"] is True:
                if sort == "top":
                    # sort by ranking
                    ordered_tags_by_rank = sorted(
                        data["results"], key=lambda d: d["rank"], reverse=True
                    )
                    ranked_tags = ordered_tags_by_rank[:limit]
                    for item in ranked_tags:
                        # add smart hashtag to like list
                        self.smart_hashtags.append(item["tag"])

                elif sort == "random":
                    if len(data["results"]) < limit:
                        random_tags = random.sample(
                            data["results"], len(data["results"])
                        )
                    else:
                        random_tags = random.sample(data["results"], limit)
                    for item in random_tags:
                        self.smart_hashtags.append(item["tag"])

                if log_tags is True:
                    for item in self.smart_hashtags:
                        print("[smart hashtag generated: {}]".format(item))
            else:
                print("Too few results for #{} tag".format(tag))`

**Comment by tperas** [comment]
Got also an error for two weeks now when starting script with smart hashtag : 

 File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 697, in set_smart_hashtags
    if data["tagExists"] is True:
KeyError: 'tagExists'

**Comment by tperas** [comment]
For what i see, the api of displaypurspose is not working

**Comment by TiagoDS7** [comment]
Bump!

**Comment by ribtoks** [comment]
The same issue

**Comment by Liopark** [comment]
have same issue anyone solve this issue?

**Comment by patrickneulinger** [comment]
same issue here..

**Comment by jasonpoonia** [comment]
I'm also facing this issue, seems like the smart hashtags aren't working still!

**Comment by elulcao** [comment]
`https://apidisplaypurposes.com/tag/` is not working any concern needs to be redirected to them.

```
{
    "info": "Query problem, please contact: contact@influtool.com"
}
```

**Comment by patrickneulinger** [comment]
Anything new?

**Comment by Spareo** [comment]
The API is working if you capture the request the browser makes, it also calls the API but it passes in some headers that the instapy request does not...

```
curl 'https://apidisplaypurposes.com/tag/candles' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15' \
-H 'api-token: 1c68cf4abf746e479b658dc48d811738'
```

That request has the minimum headers that it took to get it to work. If I remove User-Agent or api-token headers, I get the response 

```
{
    "info": "Query problem, please contact: contact@influtool.com"
}
```

So seems like their API changed and Instapy needs to be updated to support it.
