### ISSUE TITLE
Instapy exiting randomly without any errors

### ISSUE THREAD

**Issue by omgsy** [InstaPy/InstaPy#5694]
> """
> This template is written by @the-unknown
> What does this quickstart script aim to do?
> - This is my template which includes the new QS system.
>   It includes a randomizer for my hashtags... with every run, it selects 10
>   random hashtags from the list.
> NOTES:
> - I am using the bot headless on my vServer and proxy into a Raspberry PI I
> have at home, to always use my home IP to connect to Instagram.
>   In my comments, I always ask for feedback, use more than 4 words and
>   always have emojis.
>   My comments work very well, as I get a lot of feedback to my posts and
>   profile visits since I use this tactic.
>   As I target mainly active accounts, I use two unfollow methods. 
>   The first will unfollow everyone who did not follow back within 12h.
>   The second one will unfollow the followers within 24h.
> """
> 
> # !/usr/bin/python2.7
> import random
> from instapy import InstaPy
> from instapy import smart_run
> 
> # get a session!
> session = InstaPy(username='@@@@@', password='@@@@@', headless_browser=False)
> 
> # let's go! :>
> with smart_run(session):
>     hashtags = ['엘에이', '미국', '뉴욕',
>                 '시카고', '엘에이일상', '시애틀', '미국생활', '캘리포니아', '샌프란시코',
>                 '라스베가스']
>     random.shuffle(hashtags)
>     my_hashtags = hashtags[:5]
> 
>     # general settings
>     session.set_dont_like(['여행', '좋아요', '맞팔선팔', '한국', '고딩', '한국', '사진', '데일리', '데일리그램', '맞팔해요', '맞팔', '일상스타그램', '일상사진', '소통하자', '맞팔소통', '선팔하면맞팔'])
>     session.set_do_follow(enabled=True, percentage=80, times=1)
>     session.set_do_comment(enabled=True, percentage=80)
>     session.set_comments(['@@@@@@@@', '@@@@@@@@@@'],
>                          media='Photo')
>     session.set_do_like(True, percentage=70)
>     session.set_delimit_liking(enabled=True, max_likes=None, min_likes=20)
>     session.set_relationship_bounds(enabled=True,
>                                     potency_ratio=None,
>                                     delimit_by_numbers=True,
>                                     max_followers=None,
>                                     max_following=None,
>                                     min_followers=None,
>                                     min_following=150)
> 
>     session.set_quota_supervisor(enabled=True,
>                                      sleep_after=["server_calls_h"],
>                                      sleepyhead=True,
>                                      stochastic_flow=True,
>                                      notify_me=True,
>                                      peak_likes_hourly=200,
>                                      peak_likes_daily=585,
>                                      peak_comments_hourly=80,
>                                      peak_comments_daily=182,
>                                      peak_follows_hourly=48,
>                                      peak_follows_daily=125,
>                                      peak_unfollows_hourly=35,
>                                      peak_unfollows_daily=150,
>                                      peak_server_calls_hourly=200,
>                                      peak_server_calls_daily=4800)
> 
>     session.set_user_interact(amount=3, randomize=True, percentage=80)
> 
>     # activity
>     session.like_by_tags(my_hashtags, amount=100, media=None)
>     session.unfollow_users(amount=500, instapy_followed_enabled=True, instapy_followed_param="nonfollowers",
>                            style="FIFO",
>                            unfollow_after=12 * 60 * 60, sleep_delay=501)
>     session.unfollow_users(amount=500, instapy_followed_enabled=True, instapy_followed_param="all",
>                            style="FIFO", unfollow_after=24 * 60 * 60,
>                            sleep_delay=501)

My instapy is exiting without any errors in the log or anything. Why is it doing this?

**Comment by zubus** [comment]
How are you running the script?

Maybe an encoding problem? check [here](https://stackoverflow.com/questions/2688020/how-to-print-chinese-word-in-my-code-using-python)

#4947
