### ISSUE TITLE
noob install instruction 

### ISSUE THREAD

**Issue by lukasz00500** [InstaPy/InstaPy#57]
I'm trying to install a script, but I'm a total noob
So please help

I downloaded this script and alos chromediver  and python 3.6
and i dont know what to do lol..  i installed python where i should type "cd InstaPy
pip install ."

lol sorry for stupid question...

**Comment by 7ruth** [comment]
In the terminal.... if you are on mac. 

Type that line in the terminal while being in the directory that you cloned from github.
Then to run quickstart.py, open that file, type your username and password into '<user>' and '<password>' lines (make sure to remove brackets <>). Then where you typed in "pip install ." or what worked for me "sudo python setup.py install" (in the terminal), type in "python quickstart.py" to run that quickstart file (will only work if you put the chromedriver into the asset folder)

**Comment by lukasz00500** [comment]
im on WINDOWS  

I tried to type it in CMD
