### ISSUE TITLE
New Block from Instagram Detecting Bot

### ISSUE THREAD

**Issue by asvsfs** [InstaPy/InstaPy#5703]
## Expected Behavior
Follow / UnFollow according to the rate
## Current Behavior
I get a message stating _**We restrict some actions ...**_ and this isn't a regular block because i can follow in same browser when manually logged in.
## Possible Solution (optional)
It seems Instagram is detecting Selenium fast and easy. i can no more use Instapy
## InstaPy configuration

Same as quickstart

**Comment by JManke91** [comment]
Try this: Look for the file `yourUserName_cookie.pkl` and delete it. Rerun your bot and the python script is going to create a new one for you. Sometimes this helps to fix the issue you described.

**Comment by OrenRotaru** [comment]
> Try this: Look for the file `yourUserName_cookie.pkl` and delete it. Rerun your bot and the python script is going to create a new one for you. Sometimes this helps to fix the issue you described.

Where exactly would I find this file?

**Comment by asvsfs** [comment]
@JManke91  after waiting a day and deleting cookies , now i get` Couldn't follow user is inaccessible ! `i literally couldn't use Instapy for following 50 users till now.

**Comment by asvsfs** [comment]
After deleting everything and reinstalling the package it started to work again

**Comment by JManke91** [comment]
@ReflectOnIT The easiest way to find the file is probably using the global search of the finder (when using Mac) and just entering "cookie.pkl". The file path should lead to "<YourUsername>/InstaPy/logs/<IGUsername>"
