### ISSUE TITLE
Unfollow problem - "Unable to find the count of users followed  ~leaving unfollow feature"

### ISSUE THREAD

**Issue by tanmald** [InstaPy/InstaPy#5705]
## Expected Behavior
Checking list of users followed, and unfollowing them according to function "unfollow_users"

## Current Behavior
INFO [2020-08-06 22:00:15] [user]  Failed to get following count of 'user'  ~empty list
WARNING [2020-08-06 22:00:15] [user]  Unable to find the count of users followed  ~leaving unfollow feature
INFO [2020-08-06 22:00:15] [user]  --> Total people unfollowed : 0

## InstaPy configuration
session.unfollow_users(amount=20, instapy_followed_enabled=True, instapy_followed_param="all", style="FIFO", unfollow_after=90*60*60, sleep_delay=501)
(among other lines of code)

**Comment by asproxlejanus** [comment]
Same here :sob: 

I'm using the username (not email) but InstaPy is not able to get the list of users...

Same issue as reported by @tanmald , any reason?
