### ISSUE TITLE
How to open explore page on InstaPy

### ISSUE THREAD

**Issue by thisisare** [InstaPy/InstaPy#5714]
I wanna make some code on InstaPy to open explore page on Instagram and then like popular posts on it. Is it possible? Is such method to make it exists?

**Comment by windowshopr** [comment]
I would like to have this looked into again as I'm having the same issue. I'm using the command:

`session.interact_by_URL(urls=["explore/"], randomize=True, interact=True)`

With default settings, on line 4819-4820 in the `instapy.py` file, it tries to assume the url "https://www.instagram.com/p/explore/". When I log on to Instagram manually, the actual url is "https://www.instagram.com/explore/" (no "p").

Either way, I've tried using both urls, and I get this output:

```
INFO [2021-01-13 13:42:58] [...]  URL [1/1]
INFO [2021-01-13 13:42:58] [...]  --> b'https://www.instagram.com/p/explore/'
WARNING [2021-01-13 13:43:01] [...]  Unavailable Page: b'https://www.instagram.com/p/explore/'
INFO [2021-01-13 13:43:01] [...]  --> Image not liked: b'Unavailable Page'
INFO [2021-01-13 13:43:01] [...]  Liked: 0
INFO [2021-01-13 13:43:01] [...]  Already Liked: 0
INFO [2021-01-13 13:43:01] [...]  Commented: 0
INFO [2021-01-13 13:43:01] [...]  Followed: 0
INFO [2021-01-13 13:43:01] [...]  Inappropriate: 1
INFO [2021-01-13 13:43:01] [...]  Not valid users: 0
```

And then the session ends. So it doesn't seem to like that url/cannot find it, even though the url should be correct in the second case described above. 

How can we interact with the posts on the "explore" page???

**Comment by robix93** [comment]
Here the same ! 

`INFO [2021-01-19 01:07:23] [3dprint_creation]  Like# [1/59]
INFO [2021-01-19 01:07:23] [3dprint_creation]  https://www.instagram.com/p/CKNKksbpTvH/
WARNING [2021-01-19 01:07:25] [3dprint_creation]  Unavailable Page: b'https://www.instagram.com/p/CKNKksbpTvH/'
INFO [2021-01-19 01:07:25] [3dprint_creation]  --> Image not liked: b'Unavailable Page'`

The link -->  https://www.instagram.com/p/CKNKksbpTvH/ is working if I try to reach it through the browser...

I have always this error on alla immages the bot try to like...
