### ISSUE TITLE
Image was NOT liked! You are have a BLOCK on likes!

### ISSUE THREAD

**Issue by emrejacky** [InstaPy/InstaPy#5715]
## Expected Behavior
Image have to be liked.
## Current Behavior
Image cant get like.
## Possible Solution (optional)
Deleting cookie files. It worked before but now it's not working, I deleted everything under log file, still getting this error. I am able to like by phone, or different browsers, so account is not actually blocked or soemthing. What can I do about this problem? It's been a 2 days in a row.

**Comment by elulcao** [comment]
Same like #5702
