### ISSUE TITLE
A way to trigger quota supervisor when soft banned? 

### ISSUE THREAD

**Issue by rouncewell** [InstaPy/InstaPy#5717]
When I get soft banned, I realize that my terminal tells me I 'cannot get profile picture' or 'failed to get follower count' ... I know this means that I am currently soft-banned ... but is there a way to trigger quota supervisor to kick in when it receives these particular reports? 

Also, I seem to be getting soft-banned pretty regularly but I am running super low numbers ... Is it pretty much trial and error with lots of config tweaking? 

Anyways, thank you for the help!

**Comment by chevellebro1** [comment]
api server pulls should be less than 200 per hour

**Comment by rouncewell** [comment]
> 
> 
> api server pulls should be less than 200 per hour

I thought every account is different and it changes based on account interaction over time? I've been playing with 240-300 hourly and it hasn't soft-banned yet. Some days I feel like it changes though.
