### ISSUE TITLE
Instapy Error..

### ISSUE THREAD

**Issue by SAMXODE** [InstaPy/InstaPy#5718]
![fail](https://user-images.githubusercontent.com/31543427/89887948-7112eb80-dbcf-11ea-8ea2-eb767b8465f8.png)

Someone can help?

**Comment by jjpoc** [comment]
Me too!

**Comment by jjpoc** [comment]
Help Us!!

**Comment by Easyside** [comment]
**I try to maximize the window and set zoom scale to 80%, it works**
