### ISSUE TITLE
Username of the poster in comment not working with "@{}"

### ISSUE THREAD

**Issue by zubus** [InstaPy/InstaPy#5721]
## Expected Behavior
Add in comments the username of the poster

## Current Behavior

@{} is posting the username of the account running Instapy

## Possible Solution (optional)

Don't know :(

**Comment by aitelkob** [comment]
the same exiting

**Comment by kron-spar** [comment]
I'm getting the same error here. Has anyone solved this for themselves? @zubus  or @aitelkob
