### ISSUE TITLE
Feature Requests - Better Delay, Better Target List.

### ISSUE THREAD

**Issue by kairosooo** [InstaPy/InstaPy#5722]
### **About Delay:**
**What is the bot doing now?**
-Sleep "seconds" after each like action.

**What could it do?**
-Sleep "seconds" after "amounts" of like action.

### **About Target List:**

**What is the bot doing now?**
-The bot only fetches tag 1/tag 2/tag 3 sequentially in the list.
-The bot couldn't like posts by locations.

**What could it do?**
-Give user an option to fetch hashtags randomly.
-Add a parameter: "Fetch the next hashtag after performing *amount* of likes on the current hashtag.
-Implement "Like_by_Location"

I am hoping these suggestion would make the bot more humane and user-friendly.

**Comment by zubus** [comment]
Hi, Like by location already exists in [documentation](https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#like-by-locations), about random, you always can implement it in python:

for example:
`random.shuffle(hashtags)` 

And _Fetch the next hashtag after performing amount of likes on the current hashtag_ can be done if you set amount:

`session.like_by_tags(['natgeo'], amount=10)`
`session.like_by_tags(['world'], amount=5)`
`session.like_by_tags(['sky'], amount=44)`
