### ISSUE TITLE
Private proxy authorization

### ISSUE THREAD

**Issue by hardi1337** [InstaPy/InstaPy#5728]
## Expected Behavior
I specify a working private proxy - authorization through firefox fails
## Current Behavior
How to solve a problem? Thank you so much

![Снимок](https://user-images.githubusercontent.com/26912439/90161039-3d84bc80-dd9b-11ea-8e4a-2904fcc0c0e0.PNG)

**Comment by kairosooo** [comment]
same problem here, I think it's a coding issue.

**Comment by kairosooo** [comment]
I am willing to pay for 10Euro-20Euro for someone to fix this bug.

**Comment by djcerbero** [comment]
Seems a problem of Selenium, anyone has a different solution?
