### ISSUE TITLE
Running Instapy from Windows Task Scheduler?

### ISSUE THREAD

**Issue by tylergit2** [InstaPy/InstaPy#573]
I can run the program by clicking the start batch file and it's all good.

My quickstart.py is definitely in the same folder as the start batch file but when I run the program from the command line or with task scheduler I get:

C:\Program Files (x86)\Python27\Scripts\TwitterBot\IP>set PYTHONIOENCODING=UTF-8

C:\Program Files (x86)\Python27\Scripts\TwitterBot\IP>py quickstart.py
C:\Python27\python.exe: can't open file 'quickstart.py': [Errno 2] No such file or directory

Any ideas how I can fix this and run instapy with the windows task scheduler?

**Comment by theolux** [comment]
Try adding 'cd C:\Program Files (x86)\Python27\Scripts\TwitterBot\IP' to the beginning of the batch file.

**Comment by tylergit2** [comment]
Thanks!!
