### ISSUE TITLE
IG Soft Ban / Anyone can help me?

### ISSUE THREAD

**Issue by SAMXODE** [InstaPy/InstaPy#5730]
![test](https://user-images.githubusercontent.com/31543427/90310114-c6603d00-deee-11ea-93a0-ab582e8f1a57.png)

I use the Template good_commenting_strategy_and_new_qs_system from Instapy..

**I get everyday a soft ban from ig.. anyone know how to fix it?**

**Comment by itssmaxy** [comment]
Same happened as of today, been using the same settings for 2 months every day now and never occurred before. Im suspecting that the settings need to be milder, a soft ban should go away after being inactive on the account for an unknown time period. I'll give it 2 days. What's weird is that I'm not soft banned on my iPhone but I am when using the bot... Does anyone have other suggestions?

**Comment by farohp** [comment]
so i have the some problem, blocked only on bot and not on broser (firefox) or original application instagram on android

**Comment by gvmturl** [comment]
Its cache guys!
If it happens on app on Android you should reinstall it!

Take a look on Insomniac https://github.com/alexal1/Insomniac
