### ISSUE TITLE
InstaPy RuntimeError on Pydroid 3

### ISSUE THREAD

**Issue by thisisare** [InstaPy/InstaPy#5734]
I have an error when I try to compile my InstaPy code:
from instapy import InstaPy
InstaPy(username="", password="").login()
And I got this message: RuntimeError: Error, unable to determine correct filename for 32bit linux

P.S.: I tried to compile this code on my Android device with Pydroid 3. Idk, I kinda already installed InstaPy, but I dont know where problem is. Can u pls help me?

**Comment by rusithfernando** [comment]
bro i have the same problem
RuntimeError: Error, unable to determine correct filename for 64bit linux
