### ISSUE TITLE
[help] Anyone willing to validate my script?

### ISSUE THREAD

**Issue by fran6will** [InstaPy/InstaPy#574]
Hello! First, I would like to tell @timgrossmann that he made something big. Congrats.

I'm trying to : 
-Follow the users following a specific user.
-Like 5 pictures of them
-30 percent comment them
-Unfollow 10 users at the end of the session.

What's wrong with this :
```
from instapy import InstaPy

session = InstaPy(username='secretsecretsecret(age+33)', password='phonenumber+abc+123', nogui=True)
session.login()


session.set_do_comment(enabled=True, percentage=30)
session.set_comments(['Très cool!', u'👌🏻', u'📷or📱?', 'wow!!!!', 'Beau! Très beau!'])
session.set_do_follow(enabled=True, percentage=20)
session.follow_user_followers(['some_french_guy_from_quebec'], amount=60, random=True, interact=True, sleep_delay=60)

session.unfollow_users(amount=10)
session.end()
```

Thanks for the help!

**Comment by timgrossmann** [comment]
@fran6will You will need the `.set_user_interact()` to make the described behaviour happen 😉 

Simply add `session.set_user_interact(amount=5, random=True)` or false if you want to interact with the latest 5 pics

Also, unfollowing the people you just followed isn't too smart. I'd put the unfollow part on top under the login, it will then first unfollow the users you followed the last time. This way there is a longer timespan in-between following and unfollowing.

**Comment by fran6will** [comment]
Oh! Didn't know it was unfollowing the last follow! Is there a way to randomize it? Thanks for the help!

**Comment by timgrossmann** [comment]
@fran6will Nope, sorry.
That feature is the next that will receive a bounty 😉
