### ISSUE TITLE
Cannot Fetch Links For Analysis From Feed : Total of links feched for analysis: 0 Possible Error WIth session.like_by_feed()

### ISSUE THREAD

**Issue by claylton** [InstaPy/InstaPy#5740]
INFO [2020-08-19 09:47:17] [coisaskun]  Saving account progress...
INFO [2020-08-19 09:48:01] [coisaskun]  Total of links feched for analysis: 0
INFO [2020-08-19 09:48:30] [coisaskun]  Total of links feched for analysis: 0
INFO [2020-08-19 09:49:00] [coisaskun]  Total of links feched for analysis: 0
INFO [2020-08-19 09:49:34] [coisaskun]  Total of links feched for analysis: 0
INFO [2020-08-19 09:50:08] [coisaskun]  Total of links feched for analysis: 0
INFO [2020-08-19 09:50:45] [coisaskun]  Total of links feched for analysis: 0
INFO [2020-08-19 09:51:24] [coisaskun]  Total of links feched for analysis: 0
INFO [2020-08-19 09:52:04] [coisaskun]  Total of links feched for analysis: 0
INFO [2020-08-19 09:52:49] [coisaskun]  Total of links feched for analysis: 0
INFO [2020-08-19 09:53:32] [coisaskun]  Total of links feched for analysis: 0
WARNING [2020-08-19 09:53:32] [coisaskun]  Loop error, 0 links for 10 times consecutively, exit loop

**Comment by chevellebro1** [comment]
i changed xpath compile file back to the previous version and this fixed the problem.

**Comment by claylton** [comment]
It didn't work here :(
