### ISSUE TITLE
Unable to login, Cookie file not found, creating cookie... Login A/B test detected! Trying another string...

### ISSUE THREAD

**Issue by wsmith9897** [InstaPy/InstaPy#5745]
## Expected Behavior
login to instagram
## Current Behavior
instapy does not login. Gets to the instagram homepage and refreshes then ends the session:

## InstaPy configuration
mac os, instapy .058 using firefox

**Comment by wsmith9897** [comment]
Ok, I've got Firefox working but still the same issue as Chrome. No idea what to do here. 


Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...



this is all I get. no other info, just unable to login after this

**Comment by chevellebro1** [comment]
same problem here. happens every 2-3 times i run a session

**Comment by rouncewell** [comment]
I've also encountered this issue. Happens occasionally

**Comment by wsmith9897** [comment]
Anything you guys have done to get instapy working? Mine doesn't just happen occasionally it's _every_ time I run a session. I've yet to get it to work even once :(

**Comment by filiperivelli** [comment]
Same issue here.
