### ISSUE TITLE
mention someone in the comments

### ISSUE THREAD

**Issue by Adnankhaledd** [InstaPy/InstaPy#5753]
is there a way to mention a page in the comments since every time i add an @ tag to the comment it stops from commenting

**Comment by Tmcerlean** [comment]
Having the same issue here, anyone have an idea why?

**Comment by Adnankhaledd** [comment]
The reason is that when you mention someone you need to press enter twice instead of 1 time so i fixed it by changing the comments_util.py and duplicate the enter press key so just go to the comments file and add the following when you reach the enter key

    (
                ActionChains(browser)
                .move_to_element(comment_input[0])
                .send_keys(Keys.ENTER)
                .perform()
                
            )

            (
                ActionChains(browser)
                .move_to_element(comment_input[0])
                .send_keys(Keys.ENTER)
                .perform()
                
            )

            (
                ActionChains(browser)
                .move_to_element(comment_input[0])
                .send_keys(Keys.ENTER)
                .perform()
                
            )

**Comment by Tmcerlean** [comment]
Thanks Adnan, really appreciate it.

**Comment by ajju2smart** [comment]
I tried giving 2 Enter section as you @Adnankhaledd mentioned. But it still didn't work. Please advise.

**Comment by Adnankhaledd** [comment]
Hi @ajju2smart you should add additional 2 enters which means you have a total of 3
