### ISSUE TITLE
~user is inaccessible and document.getElementsByClassName(...)[0] is undefined

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5755]
## Expected Behavior

Im using the good_commenting_strategy_and_new_qs_system.py 
It works quite well but I got a lot of 

~user is inaccessible
and 
document.getElementsByClassName(...)[0] is undefined

## Current Behavior
 I got a lot of 

~user is inaccessible
and 
document.getElementsByClassName(...)[0] is undefined

## Possible Solution (optional)
Dunno!

**Comment by teodorgross** [comment]
Yes i have the same problem, im getting a lot of document.getElementsByClassName(...)[0] is undefined

UPDATE:

I saw that it only happens if the image of the post is very wide....

**Comment by teodorgross** [comment]
I find a workaround for me, try to replace in browser.py the user_agent with this values = 

"Mozilla/5.0 (iPad; CPU OS 13_2 like Mac OS X) AppleWebKit/605.1.15"
"(KHTML, like Gecko) FxiOS/28.0 Mobile/15E148 Safari/605.1.15"

It makes your browser-frame wider/longer and it should fix the error.
