### ISSUE TITLE
Similar Crontab issue to issue #514

### ISSUE THREAD

**Issue by samducker** [InstaPy/InstaPy#576]
Hey, my crontab won't run the script but it works fine in bash/logged in as root.

0 */3 * * * cd /home/instagram/InstaPy/ && /usr/bin/python3.5 quickstart.py

**Comment by timgrossmann** [comment]
@samducker  Did you try to just copy the whole line and execute it yourself?

**Comment by samducker** [comment]
@timgrossmann So currently I'm running the script through tmux then doing cd /home/instagram/InstaPy/ then python3.5 quickstart.py which works a treat but isn't as convenient as running a cron job.

What I've tried doing is doing crontab -e and then adding the line 0 */3 * * * cd /home/instagram/InstaPy/ && /usr/bin/python3.5 quickstart.py

And that hasn't worked for me.

**Comment by timgrossmann** [comment]
@samducker if you're on a DO Ubuntu I can promise you (if you followed the How_To_DO_Ubuntu instructions) that this works:

`* */3 * * * cd /home/instagram/InstaPy && python3.5 quickstart.py`

(is the path `/home/instagram/InstaPy` the right one? Try to `cd` into the InstaPy folder, do a `pwd` and copy that exact path)

**Comment by samducker** [comment]
Yep I did a pwd and I get the following 

```
root@luckyduck-1:/home/instagram/InstaPy# pwd
/home/instagram/InstaPy
```

I used that guide to setup the ubuntu install on digital ocean. My crontab -e saves to /tmp/crontab.IfjidM/crontab

and only contains the following line after the comments.

`* */3 * * * cd /home/instagram/InstaPy && python3.5 quickstart.py`

**Comment by theolux** [comment]
Try replacing the line with this one: * */3 * * * bash -c "cd /home/instagram/InstaPy && python3.5 quickstart.py"

**Comment by timgrossmann** [comment]
@samducker Really weird.

Please take the line `cd /home/instagram/InstaPy && python3.5 quickstart.py` and just execute it when connected to the server like this:

```bash
root@luckyduck-1:/home/instagram/InstaPy# cd /home/instagram/InstaPy && python3.5 quickstart.py
```

If that works, then you should delete that droplet and set up a new one...
I did this more than 20 times now I can't promise that it works 😉

**Comment by ogerasymenko** [comment]
Got same issue with Ubuntu 16.04 and cron job:
in cron I'm launch /fill_path_to/run_app.sh

run_app.sh contain:
#!/bin/bash
cd /home/user/scripts && python3 insta.py

logFile contain:
Session started - 2017-08-25 12:50:04
Logged in successfully!
Tag [1/[]]--> b'#some_tag'
and then goes 5-7 likes.

In same time in memory present launched programs like chrome, insta.py and other related.

**Comment by converge** [comment]
there is no interaction for a long time, pls, reopen it if you need.
