### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by elissonnog** [InstaPy/InstaPy#5764]
Sometimes my script works and some give this issue.
I dont really know why, any help?

  File "quickstart.py", line 31, in <module>
    with smart_run(session):
  File "/usr/lib/python3.6/contextlib.py", line 83, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield

**Comment by RhaegarTargaryen55** [comment]
same

**Comment by sakarimov** [comment]
same problem

**Comment by Fasteel** [comment]
Remove workspace directory and re-run works for me.

**Comment by celestinsoum** [comment]
not work for me
