### ISSUE TITLE
How do I specify the number of interactions my bot is performing on an account?

### ISSUE THREAD

**Issue by supercitron** [InstaPy/InstaPy#5770]
Hi, I'm trying to create a basic set of actions for the first version of my bot.
So I tried the following :

` from instapy import InstaPy`
` from instapy.util import smart_run`
` # login credentials`
` insta_username = 'ThisIsAUsername'`
` insta_password = 'ThisIsAPassword'`
` # get an InstaPy session!`
` session = InstaPy(username=insta_username,`
                `  password=insta_password,`
                 ` headless_browser=True,`
                  `disable_image_load=True)`
`with smart_run(session):`
 `   """ Activity flow """`
  `  # settings`
   ` session.set_do_like(enabled=True, percentage=100)`
    `session.set_do_comment(enabled=True, percentage=100)`
    `session.set_comments(comments=['@ThisIsAUsername'])`
    `session.set_user_interact(randomize=False, media='Photo')`
   ` # actions`
    `session.follow_by_tags(["ThisIsATag"], interact=True)`

## Expected Behavior

- Find a post with a specific tag
- Follow the account from that post
- Like the post
- Comment on the post
- Move on to the next post with the specific tag and repeat

## Current Behavior

- Find a post with a specific tag
- Follow the account from that post
- Like **10** posts from the account
- Comment on the **10** posts
- Move on to the next post with the specific tag and repeat

**Comment by gamethrower** [comment]
`session.set_user_interact(amount=2, randomize=False, media='Photo')`
