### ISSUE TITLE
You have a BLOCK on likes! 

### ISSUE THREAD

**Issue by rouncewell** [InstaPy/InstaPy#5771]
##  Expected Behavior

I am expecting an image that meets my requirements to be liked. 

## Current Behavior

--> Image Liked!
------- WARNING! Image was NOT liked! You have a BLOCK on likes! 

## Possible Solution (optional)

Clearing cache (works for a couple likes then reappears.
Deleting cookie file (works for a couple likes then reappears. 

Waiting a certain amount of time before reusing the script. I have tried a few days without running it and I still run into this issues

Changing IP address of device (running on Linux Desktop) via router configuration ... Have not tried this, but I am going to 

## Ideas ? 

Has anyone encountered this issue? If so, have you been able to get past it? I can like from my mobile phone, just not from this script on my desktop. I can also like on Firefox on my desktop, so IDK what the issue could be.

**Comment by chevellebro1** [comment]
i have the same problem. it just started over the weekend

**Comment by zubus** [comment]
Same here, every action blocked since weekend

**Comment by rouncewell** [comment]
I've waited several day now and retried ... I still encounter the same issue.

**Comment by chevellebro1** [comment]
Only workaround I found for this was to clear /log/cookie at the end of each session. But there are still times my last few likes are blocked

**Comment by rouncewell** [comment]
I just tried this and it seems to work ... Not sure how long. I usually run a cron job for instapy, is there a way to add an automation for cleaning up the cookie within the instapy config?

**Comment by elulcao** [comment]
> I just tried this and it seems to work ... Not sure how long. I usually run a cron job for instapy, is there a way to add an automation for cleaning up the cookie within the instapy config?

as WA you can configure a CRON job to remove the cookie (pkl file).

**Comment by rouncewell** [comment]
> > I just tried this and it seems to work ... Not sure how long. I usually run a cron job for instapy, is there a way to add an automation for cleaning up the cookie within the instapy config?
> 
> as WA you can configure a CRON job to remove the cookie (pkl file).

I suppose I could set a cron for removing the pkl  _before_ my scheduled instapy cronjobs!

**Comment by elulcao** [comment]
> > > I just tried this and it seems to work ... Not sure how long. I usually run a cron job for instapy, is there a way to add an automation for cleaning up the cookie within the instapy config?
> > 
> > 
> > as WA you can configure a CRON job to remove the cookie (pkl file).
> 
> I suppose I could set a cron for removing the pkl _before_ my scheduled instapy cronjobs!

1. If Instagram detects that you are using a bot, then you need to re-configure the InstaPy limits/interactions to emulate a human behave.
2. Modify the CRON job to be executed less frequently.
3. Creating an extra CRON job to remove the cookie is just a WA. 

I've been running the bot for a long time with at least 3 shadow banned periods, the only change I made to reduce the "blocked" damage is running the bot each 24hrs. I tried other WA like modifying the Bio in my account; it seem to help to fool the IG filters.

**Comment by rouncewell** [comment]
I set lower limits in my config file and will be running it much less frequently. Maybe I can change the cronjob weekly and set different hours of operation. 

> I tried other WA like modifying the Bio in my account; it seem to help to fool the IG filters.

Changing your account bio helps reduce blocks?

**Comment by chevellebro1** [comment]
I had mine running for weeks with the same quota turned on and only recently was flagged. It seems like they are changing something about how they detect bots

**Comment by rouncewell** [comment]
> I had mine running for weeks with the same quota turned on and only recently was flagged. It seems like they are changing something about how they detect bots

I am in the same boat ... I had it running via crons several times daily for around 2 weeks and only encountered this issue several days ago.

**Comment by spud-dog** [comment]
similar problem started last week, hoping someone can find a solution! Thank you!

**Comment by shashikotte** [comment]
Delete all files in the folder logs, do not delete the folder itself.

C:\Users\(user name)\InstaPy\logs

This will clear the block, and change the settings in number of likes, comments, follows etc...

**Comment by Lxand3r** [comment]
having the same issue just cleared the log file but Im still showing the same msg issue on follows and likes anyone ?

**Comment by shashikotte** [comment]
Wait for 24 hours, and try again!

**Comment by Lxand3r** [comment]
> Wait for 24 hours, and try again!

so it ended up working after a few tries after I clean cookies thanks

**Comment by pedrobart** [comment]
> Delete all files in the folder logs, do not delete the folder itself.
> 
> C:\Users(user name)\InstaPy\logs
> 
> This will clear the block, and change the settings in number of likes, comments, follows etc...

thank you! it fix my issue.
