### ISSUE TITLE
How can I run more than 1 script at the same time?

### ISSUE THREAD

**Issue by henriquedevelops** [InstaPy/InstaPy#5775]
## Expected Behavior
Run multiple scripts at the same time

## Current Behavior
Running only 1 script at a time

## Possible Solution (optional)
After researching on issues, I found this: #5403 and this #5440 
So I did as they said:

1- Included this before session login:

from instapy import set_workspace
set_workspace(path="")

2- Copied, paste, and renamed the InstaPy folder. (Now I have 2 Instapy folders)

3- Have set the path to the new copy of it.

But when I try to run the second quickstart (with the first already running), I get this error message: "SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape"
And the error points up to the " symbol in the set_workspace(path="C:\Users\henri\new\InstaPy") line

Can someone please give me a light? I'm stuck on it for months...

## InstaPy configuration

""" Quickstart script for InstaPy usage """
# imports
from instapy import InstaPy
from instapy.util import smart_run
from instapy import set_workspace
set_workspace(path="C:\Users\henri\new\InstaPy")

# login credentials
insta_username = 'XXX'
insta_password = 'XXX'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

with smart_run(session):
    """ Activity flow """
    # general settings
    
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "server_calls"], sleepyhead=True, stochastic_flow=True, notify_me=False,
                              peak_likes_hourly=25, peak_likes_daily=400,
                                 peak_server_calls_hourly=200, peak_server_calls_daily=3500)

    # activity

    session.set_do_follow(enabled=True, percentage=100)

**Comment by dimekmaurer** [comment]
This error occurs because you are using a normal string as a path. You can use one of the following solutions to fix your problem.
Just put "r" before your normal string it converts normal string to raw string (r"C:\Users\Cherry\InstaPy\"). I think so ;)

**Comment by henriquedevelops** [comment]
> This error occurs because you are using a normal string as a path. You can use one of the following solutions to fix your problem.
> Just put "r" before your normal string it converts normal string to raw string (r"C:\Users\Cherry\InstaPy"). I think so ;)

Thanks for trying to help, bro. I appreciate it.

But now I'm getting this other error message:

"Timed out with failure while explicitly waiting until visibility of element located!"
"Generator didn't yield"

This only happens when I'm trying to start the second script, the first one works fine

**Comment by dimekmaurer** [comment]
I suggest you help the script to click log in in the selenium browser via headless=False

**Comment by henriquedevelops** [comment]
> I suggest you help the script to click log in in the selenium browser via headless=False

IT WORKED

Thank you so much
