### ISSUE TITLE
instagram.com/explore/tags blocked

### ISSUE THREAD

**Issue by salilramani** [InstaPy/InstaPy#5782]
## Expected Behavior
It should run 
## Current Behavior
I'm also unable to open instagram.com/explore/tags on browser 

INFO [2020-09-14 20:12:52] [alt.vue]  Session started!
INFO [2020-09-14 20:12:52] [alt.vue]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-09-14 20:12:52] [alt.vue]  - Internet Connection Status: ok
INFO [2020-09-14 20:12:52] [alt.vue]  - Current IP is "142.116.105.46" and it's from "Canada/CA"
INFO [2020-09-14 20:12:52] [alt.vue]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-09-14 20:12:52] [alt.vue]  - window.navigator.webdriver response: None
INFO [2020-09-14 20:12:52] [alt.vue]  - Hide Selenium Extension: ok
INFO [2020-09-14 20:13:02] [alt.vue]  Logged in successfully!
INFO [2020-09-14 20:13:02] [alt.vue]  Saving account progress...
INFO [2020-09-14 20:13:15] [alt.vue]  Tag [1/2]
INFO [2020-09-14 20:13:15] [alt.vue]  --> b'imagesofcanada'
INFO [2020-09-14 20:13:43] [alt.vue]  Too few images, skipping this tag
INFO [2020-09-14 20:13:43] [alt.vue]  Tag [2/2]
INFO [2020-09-14 20:13:43] [alt.vue]  --> b'droneoftheday'
INFO [2020-09-14 20:14:09] [alt.vue]  Too few images, skipping this tag
INFO [2020-09-14 20:14:09] [alt.vue]  Liked: 0
INFO [2020-09-14 20:14:09] [alt.vue]  Already Liked: 0
INFO [2020-09-14 20:14:09] [alt.vue]  Commented: 0
INFO [2020-09-14 20:14:09] [alt.vue]  Followed: 0
INFO [2020-09-14 20:14:09] [alt.vue]  Inappropriate: 0
INFO [2020-09-14 20:14:09] [alt.vue]  Not valid users: 0

INFO [2020-09-14 20:14:10] [alt.vue]  Sessional Live Report:
	|> No any statistics to show
## InstaPy configuration
from instapy import InstaPy
from instapy import smart_run

insta_username = 'abc'
insta_password = 'xxx'
comments = ['Nice shot! @{}', ':thumbsup:', 'Incredible :open_mouth:', 'Love this @{}', 'Looks awesome @{}',
            ':raised_hands: Yes!']
session = InstaPy(username=insta_username, password=insta_password)
session.set_quota_supervisor(enabled=True, sleep_after=["likes"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes_hourly=50,
                              peak_likes_daily=585)
#session.set_comments(['Brilliant Shot!','Amazing click!','Superb!',':thumbsup:','Incredible :open_mouth:','Love this @{}','Looks awesome @{}', 'Stunning!', 'Impressive!',':raised_hands: Yes!'])

with smart_run(session):
            #session.set_do_comment(enabled=True, percentage=100)
            session.like_by_tags(["imagesofcanada","droneoftheday"], amount=100)

**Comment by chevellebro1** [comment]
Same problem, just started today. Like by tag and follow not working

**Comment by rowlandwilliams** [comment]
same problem also

**Comment by Booleboole** [comment]
Same problem

**Comment by sakarimov** [comment]
same problem

**Comment by chevellebro1** [comment]
instagram fixed whatever the problem was. started working again an hour ago
