### ISSUE TITLE
Hashtags worked yesterday, today i receive the same message for ALL hashtags 'Too few images, skipping this tag'

### ISSUE THREAD

**Issue by anyway1986** [InstaPy/InstaPy#5784]
Guys, what can be the problem?
everything worked yesterday and today I receive one message for all hashtags - 'Too few images, skipping this tag'

this cannot be true, as 1. it worked yesterday 2. for example, hashtag 'girl' has around 406 millions of posts
thanks a lot!

**Comment by Aassifh** [comment]
Not Working for me at all, also following/followers endpoint not working

**Comment by blackchayenne** [comment]
yes, by today i guess  instagram changed tags path, problem started today, waiting a bugfix or update of instapy for this issue

**Comment by Atrox93** [comment]
same problem here

**Comment by anyway1986** [comment]
Thanks, guys, good to know it's not me ;-)
so waiting for the update

**Comment by Aassifh** [comment]
the explore tags page is also not working anymore on the web app (from the browser)

**Comment by itssmaxy** [comment]
Yeah, basically its on the instagram side of issue. Their webpage isn't working. Guess all we can do is wait

**Comment by anyway1986** [comment]
> the explore tags page is also not working anymore on the web app (from the browser)

Yes, I have noticed this as well!

**Comment by salilramani** [comment]
Same issue

**Comment by roberterzen** [comment]
Me too. It it possible they've done it deliberately to force people to use mobile app and keep bots away?

**Comment by Booleboole** [comment]
Same problem here

**Comment by 1ord5udo** [comment]
Issue still sadly occurs even in mobile view on desktop with the path instagram.com/explore/tags/your_hashtag. 

Strongly considering switching to android just so I can run python scripts and have the tool access it via the mobile app. 

I hope the community considers changing the name of Instapy so it makes it harder for Instagrams engineers to find and locate timgrossmann and the instapy tool on github.

**Comment by 1ord5udo** [comment]
Also stop uploading video tutorials on youtube. 

Dummies.

**Comment by gixxerfrank** [comment]
same here

**Comment by 001lexus** [comment]
Already works

**Comment by chevellebro1** [comment]
functionality has been restored on instagrams side

**Comment by its-ogawa** [comment]
Has this topic been resolved and closed?
I am still having this problem.

I'm baffled by the fact that even prominent tags that get hundreds of millions of hits when I search for them get "Too few images".

```
INFO [2021-11-12 10:14:31] [<username>]  Tag [1/3]
INFO [2021-11-12 10:14:31] [<username>]  --> b'instagood'
INFO [2021-11-12 10:15:01] [<username>]  Too few images, skipping this tag
INFO [2021-11-12 10:15:01] [<username>]  Tag [2/3]
INFO [2021-11-12 10:15:01] [<username>]  --> b'photooftheday'
INFO [2021-11-12 10:15:32] [<username>]  Too few images, skipping this tag
INFO [2021-11-12 10:15:32] [<username>]  Tag [3/3]
INFO [2021-11-12 10:15:32] [<username>]  --> b'happy'
INFO [2021-11-12 10:16:04] [<username>]  Too few images, skipping this tag
```
