### ISSUE TITLE
hello, help me :)

### ISSUE THREAD

**Issue by Skorp00** [InstaPy/InstaPy#5785]
here is the error  

.. .. .. .. .. .. .. .. .. ..
Workspace in use: "/home/spammyboy420/InstaPy"

.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..
INFO [2020-09-15 12:13:40] [] Using built in instapy-chromedriver executable (version 2.46)

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-09-15 12:13:41] [] Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo

INFO [2020-09-15 12:13:41] [] -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-09-15 12:13:42] [] - Internet Connection Status: ok
INFO [2020-09-15 12:13:42] [] -- Connection Checklist [2/2] (Instagram Server Status)
INFO [2020-09-15 12:13:45] [] - Instagram WebSite Status: Currently Up
INFO [2020-09-15 12:13:45] [] - Instagram Response Time: 115.942 ms
INFO [2020-09-15 12:13:45] [] - Instagram Reponse Code: 200
INFO [2020-09-15 12:13:45] [] - Instagram Server Status: ok
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...

.............................................................................................................................
CRITICAL [2020-09-15 12:14:00] [] Unable to login to Instagram! You will find more information in the logs above.
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2020-09-15 12:14:00] [] Sessional Live Report:
|> No any statistics to show

[Session lasted 20.12 seconds]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-09-15 12:14:00] [] Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Probably some error with the cookies.
I'm running it as `headless_browser=True` because im on ubuntu 18 through ssh.

these are the config: 
`session = InstaPy(username=insta_username,
                  password=insta_password,
				  multi_logs=True,
                  headless_browser=True)`

**Comment by amirali1690** [comment]
Try it again, sometimes it happens for me too.

**Comment by dimekmaurer** [comment]
It happens to me too sometimes. It helps to change the headless_browser parameter from True to False

**Comment by Skorp00** [comment]
> It happens to me too sometimes. It helps to change the headless_browser parameter from True to False

i cant use it i dont have a desktop, i use it with ssh
Still doesnt working

**Comment by Skorp00** [comment]
> Try it again, sometimes it happens for me too.

i tried many times

**Comment by shashikotte** [comment]
Hi,

Please clear the logs folder(delete all content of the folder), update instapy using update.bat, it is working for me.

**Comment by filiperivelli** [comment]
Here the same problem
#5799
