### ISSUE TITLE
Cyrillic characters are displayed incorrectly in log

### ISSUE THREAD

**Issue by vvkuryshev** [InstaPy/InstaPy#5787]
## Expected Behavior
INFO [2020-09-17 11:48:08] [insta_account]  Tag [1/12]
INFO [2020-09-17 11:48:08] [insta_account]  --> 'смешные животные'
INFO [2020-09-17 11:48:36] [insta_account]  Too few images, skipping this tag
INFO [2020-09-17 11:48:36] [insta_account]  Tag [2/12]
INFO [2020-09-17 11:48:36] [insta_account]  --> 'смешные животные'
INFO [2020-09-17 11:48:45] [insta_account]  desired amount: 14  |  top posts [disabled]: 9  |  possible posts: 125318
INFO [2020-09-17 11:48:51] [insta_account]  Like# [1/14]
INFO [2020-09-17 11:48:51] [insta_account]  https://www.instagram.com/p/CFOyOpshiZK/
INFO [2020-09-17 11:48:55] [insta_account]  Image from: b'vegfoodrus_'
INFO [2020-09-17 11:48:55] [insta_account]  Link: b'https://www.instagram.com/p/CFOyOpshiZK/'
INFO [2020-09-17 11:48:55] [insta_account]  Description: b'нормальный текст'
## Current Behavior
INFO [2020-09-17 11:48:08] [insta_account]  Tag [1/12]
INFO [2020-09-17 11:48:08] [insta_account]  --> b'\xd1\x81\xd0\xbc\xd0\xb5\xd1\x88\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\xb6\xd0\xb8\xd0\xb2\xd0\xbe\xd1\x82\xd0\xbd\xd1\x8b\xd0\xb5'
INFO [2020-09-17 11:48:36] [insta_account]  Too few images, skipping this tag
INFO [2020-09-17 11:48:36] [insta_account]  Tag [2/12]
INFO [2020-09-17 11:48:36] [insta_account]  --> b'\xd0\xbc\xd0\xb8\xd0\xbb\xd1\x8b\xd0\xb5\xd0\xb6\xd0\xb8\xd0\xb2\xd0\xbe\xd1\x82\xd0\xbd\xd1\x8b\xd0\xb5'
INFO [2020-09-17 11:48:45] [insta_account]  desired amount: 14  |  top posts [disabled]: 9  |  possible posts: 125318
INFO [2020-09-17 11:48:51] [insta_account]  Like# [1/14]
INFO [2020-09-17 11:48:51] [insta_account]  https://www.instagram.com/p/CFOyOpshiZK/
INFO [2020-09-17 11:48:55] [insta_account]  Image from: b'vegfoodrus_'
INFO [2020-09-17 11:48:55] [insta_account]  Link: b'https://www.instagram.com/p/CFOyOpshiZK/'
INFO [2020-09-17 11:48:55] [insta_account]  Description: b'\xd0\x9b\xd0\xb5\xd1\x82\xd1\x83\xd1\

## InstaPy configuration
version 0.6.10

**Comment by knX5Fw** [comment]
Confirm
![изображение](https://user-images.githubusercontent.com/12394295/134604942-3184d013-7931-40be-9c3c-5ae7c67cb97f.png)
