### ISSUE TITLE
Can i run more accounts at the same time?

### ISSUE THREAD

**Issue by rastislavuhrin** [InstaPy/InstaPy#5794]
I tried to open second cmd where i started my another quickstart.py while the first one was already running, and it throwed me this error 

Traceback (most recent call last):
File "insta-rasto.py", line 28, in
session = InstaPy(username=insta_username,
File "C:\Users\Acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\instapy.py", line 312, in init
self.browser, err_msg = set_selenium_local_session(
File "C:\Users\Acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 128, in set_selenium_local_session
browser.install_addon(create_firefox_extension(), temporary=True)
File "C:\Users\Acer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instapy\browser.py", line 46, in create_firefox_extension
with zipfile.ZipFile(zip_file, "w", zipfile.ZIP_DEFLATED, False) as zipf:
File "C:\Users\Acer\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1251, in init
self.fp = io.open(file, filemode)
OSError: [Errno 22] Invalid argument: 'C:\Users\Acer\InstaPy\assets\extension.xpi'

and i found out, that its because my firefox window from first account is still opened - when i close it, than on the first account appears error because of that but the second account run without this error.
But if i leave the old window which was opened by first account, does not matter if there's instagram page or not, the error occurs.
When i opened firefox window and not instapy, than i can run without this error.
I searched for solution and i only found one, to delete extension.xpi but it does not help since it's automatically created every time.

I know that browsers don't allow you to sign in with different accounts on different tabs/windows, unless you log in to incognito mode.

Thank you in forward

**Comment by shubhayu-64** [comment]
InstaPy uses selenium webdriver to automate your instagram tasks and once you open a session for it from your terminal, you can't run another session parallel to the first one. This is because the same webdriver will be triggered for two parallel sessions from the same InstaPy with different session ids. Hence your second session will be considered and the 1st one will have the error.

And also if you run InstaPy with a different firefox window open, It will not give error as the other firefox window is not controlled by the bot and hence there is no conflict of different sessions.

**Comment by elulcao** [comment]
@Shugg53 
You can try Docker-InstaPy, then each account will be isolated in each container.

**Comment by rastislavuhrin** [comment]
@elulcao @shubhayu-64 

thank you both for the answer,
Docker could be a solution, i was just wondering about these posts:

in First post https://github.com/timgrossmann/InstaPy/issues/1469
@lucanello mentioned in his first post that he is using linux screen for more account - or did i just get it wrong, and he didn't mean "paralel" ? also @Tr1pke was mentioning few ideas

in Second post https://github.com/timgrossmann/InstaPy/issues/1668
@DemOnJR posted a link with alleged quickstart "/examples/multi-account.py"
quickstar templates are now located here https://github.com/InstaPy/instapy-quickstart/tree/master/quickstart_templates
but there is multi-account.py not anymore.

I also found more issues where people asked about multiple account but didn't find any useful info

Thank you

**Comment by Tr1pke** [comment]
In the past I did it like this:

/home/instapy/user1/all your files and configs  
/home/instapy/user2/all your files and configs 
Etc

Then you run each account in a different folder in a screen. 

In a different script I had : 

cd /home/instapy 
cd user1; screen -dms user1 ./start.sh 
cd /home/instapy
cd user2; screen -dms user2 ./start.sh 
echo “ all bots started”

I made a crontab I don’t remember the timesframes. This was like 3 years ago

**Comment by elulcao** [comment]
> @elulcao @shubhayu-64
> 
> thank you both for the answer,
> Docker could be a solution, i was just wondering about these posts:
> 
> in First post #1469
> @lucanello mentioned in his first post that he is using linux screen for more account - or did i just get it wrong, and he didn't mean "paralel" ? also @Tr1pke was mentioning few ideas
> 
> in Second post #1668
> @DemOnJR posted a link with alleged quickstart "/examples/multi-account.py"
> quickstar templates are now located here https://github.com/InstaPy/instapy-quickstart/tree/master/quickstart_templates
> but there is multi-account.py not anymore.
> 
> I also found more issues where people asked about multiple account but didn't find any useful info
> 
> Thank you

Hey @Shugg53 
I forgot to mention that you can try setting the workspace in different folder for each acct,
then start each acct*.py in different shell or cron job. The main idea is to avoid accessing the 
db.sqlite at the same time, this is because the locks and race conditions, etc.

```python
acct1.py
set_workspace(path="/Users/user/InstaPy_Info_1")
```

```python
acct2.py
set_workspace(path="/Users/user/InstaPy_Info_2")
```
