### ISSUE TITLE
Syntax error trying to run quickstart.py

### ISSUE THREAD

**Issue by Ties113** [InstaPy/InstaPy#5796]
## Expected Behavior
Start and create a session

## Current Behavior
Doesn' t start instead gives a syntax error
    session.follow_user_followers(['chronischekanker', 'codeinekermit'], amount=4000,
    ^
SyntaxError: invalid syntax

## Possible Solution (optional)
maybe there are some files i miss or need to update
## InstaPy configuration
`# imports
from instapy import InstaPy, smart_run

# login credentials
insta_username = 'yes'
insta_password = 'no'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(  username=insta_username,
                    password=insta_password,
                    headless_browser=True)

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=4000,
                                    min_followers=45,
                                    min_following=77,
                                    max_following=4000)

    session.set_quota_supervisor(enabled=True, sleep_after=["follows", "unfollows"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes_hourly=100,
                               peak_comments_hourly=21,
                               peak_comments_daily=182,
                                peak_follows_daily=1000,
                                 peak_unfollows_daily=1000,

    # activities

    """ Massive Follow of users followers (I suggest to follow not less than
    3500/4000 users for better results)...
    """
    session.follow_user_followers(['igoteggz', 'chronischekanker', 'codeinekermit'], amount=500,
                                  randomize=False, interact=False)

    """ First step of Unfollow action - Unfollow not follower users...
    """
    session.unfollow_users(amount=500, InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=601)

    """ Second step of Massive Follow...
    """
    session.follow_user_followers(['igotzucc', 'memesuppliarr', 'cumcheese'], amount=500,
                                  randomize=False, interact=False)

    """ Second step of Unfollow action - Unfollow not follower users...
    """
    session.unfollow_users(amount=500, InstapyFollowed=(True, "nonfollowers"),
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=601)

    """ Clean all followed user - Unfollow all users followed by InstaPy...
    """
    session.unfollow_users(amount=500, InstapyFollowed=(True, "all"),
                           style="FIFO", unfollow_after=24 * 60 * 60,
                           sleep_delay=601)
`

**Comment by shubhayu-64** [comment]
Please specify the exact syntax error.

Possible Solution: Delete the current InstaPy folder with all contents and then again install by git clone https://github.com/timgrossmann/InstaPy.git

**Comment by Ties113** [comment]
> Please specify the exact syntax error.
> 
> Possible Solution: Delete the current InstaPy folder with all contents and then again install by git clone https://github.com/timgrossmann/InstaPy.git

i deleted all the instapy files but it still gives the same error
    session.follow_user_followers(['chronischekanker', 'codeinekermit'], amount=4000,
    ^
SyntaxError: invalid syntax

**Comment by shubhayu-64** [comment]
Well @Ties113, the syntax error is simple.

session.follow_user_followers(['chronischekanker', 'codeinekermit'], amount=4000,
_______________________ ^

See that " ( " where I marked? That was opened but not closed. This gives the syntax error. 

I would suggest you to find this line in your code where you are using it and comment back again so that I can help you with how to fix it. It is just the " ( " needs a closing " ) " bracket.

**Comment by Ties113** [comment]
@shubhayu-64 thats just the syntax error message

the line of code is the following:

with smart_run(session):
    session.follow_user_followers(['chronischekanker', 'codeinekermit'], amount=4000,
                                  randomize=False, interact=False)

and there is a closing ")"
i think the problem is that i'm missing a file or something because on my laptop it works flawless

**Comment by shubhayu-64** [comment]
@Ties113 try putting the line below i.e, from randomize=False... in the same line as above.

Also you won't have any file missing as in that case, it wouldn't have given you syntax error!

**Comment by shubhayu-64** [comment]
Ahh !! I see it @Ties113. You have a wrong indentation here.
All you have to do is put a tab just before randomize=False!!

Or just put everything in one line!
```
session.follow_user_followers(['chronischekanker', 'codeinekermit'], amount=4000,randomize=False, interact=False)
```

**Comment by Ties113** [comment]
@shubhayu-64 
    session.follow_user_followers(['chronischekanker', 'codeinekermit'], amount=4000, randomize=False, interact=False)
    ^
SyntaxError: invalid syntax
still doesnt work 😕

**Comment by shubhayu-64** [comment]
@Ties113 can you change all ' ' to " "

**Comment by Ties113** [comment]
@shubhayu-64 I did but it didn't change anything

**Comment by elulcao** [comment]
> ## Expected Behavior
> Start and create a session
> 
> ## Current Behavior
> Doesn' t start instead gives a syntax error
> session.follow_user_followers(['chronischekanker', 'codeinekermit'], amount=4000,
> ^
> SyntaxError: invalid syntax
> 
> ## Possible Solution (optional)
> maybe there are some files i miss or need to update
> 
> ## InstaPy configuration
> `# imports
> from instapy import InstaPy, smart_run
> 
> # login credentials
> insta_username = 'yes'
> insta_password = 'no'
> 
> # get an InstaPy session!
> # set headless_browser=True to run InstaPy in the background
> session = InstaPy( username=insta_username,
> password=insta_password,
> headless_browser=True)
> 
> with smart_run(session):
> """ Activity flow """
> # general settings
> session.set_relationship_bounds(enabled=True,
> delimit_by_numbers=True,
> max_followers=4000,
> min_followers=45,
> min_following=77,
> max_following=4000)
> 
> ```
> session.set_quota_supervisor(enabled=True, sleep_after=["follows", "unfollows"], sleepyhead=True, stochastic_flow=True, notify_me=True,
>                           peak_likes_hourly=100,
>                            peak_comments_hourly=21,
>                            peak_comments_daily=182,
>                             peak_follows_daily=1000,
>                              peak_unfollows_daily=1000,
> 
> # activities
> 
> """ Massive Follow of users followers (I suggest to follow not less than
> 3500/4000 users for better results)...
> """
> session.follow_user_followers(['igoteggz', 'chronischekanker', 'codeinekermit'], amount=500,
>                               randomize=False, interact=False)
> 
> """ First step of Unfollow action - Unfollow not follower users...
> """
> session.unfollow_users(amount=500, InstapyFollowed=(True, "nonfollowers"),
>                        style="FIFO",
>                        unfollow_after=12 * 60 * 60, sleep_delay=601)
> 
> """ Second step of Massive Follow...
> """
> session.follow_user_followers(['igotzucc', 'memesuppliarr', 'cumcheese'], amount=500,
>                               randomize=False, interact=False)
> 
> """ Second step of Unfollow action - Unfollow not follower users...
> """
> session.unfollow_users(amount=500, InstapyFollowed=(True, "nonfollowers"),
>                        style="FIFO",
>                        unfollow_after=12 * 60 * 60, sleep_delay=601)
> 
> """ Clean all followed user - Unfollow all users followed by InstaPy...
> """
> session.unfollow_users(amount=500, InstapyFollowed=(True, "all"),
>                        style="FIFO", unfollow_after=24 * 60 * 60,
>                        sleep_delay=601)
> ```
> 
> `

Check your configuration

```python
    session.follow_user_following(
            ['user'
            ], amount=1,
            randomize=True,
            interact=True,
            sleep_delay=60)

    session.follow_user_followers(
            ['user'
            ], amount=1,
            randomize=True,
            interact=True,
            sleep_delay=60)

  def follow_user_followers(
        self,
        usernames: list,
        amount: int = 10,
        randomize: bool = False,
        interact: bool = False,
        sleep_delay: int = 600,
    ):
```
