### ISSUE TITLE
Wrong login data with correct data

### ISSUE THREAD

**Issue by danan46** [InstaPy/InstaPy#580]
Hi,

I tried to execute InstaPy with python2.7 and 3.4 in my local machine with Debian 8:

`InstaPy(username='myUsername', password='myPsw', nogui=True).login()`

and this works fine, but if I try to execute the same line in another machine server with the same OS, I receive the message:
 _Wrong login data!_

Thank you for your help

**Comment by timgrossmann** [comment]
@danan46 You probably have to login to your account with the webbrowser yourself once. 
There will be a page on instagram that asks you if the login from some country was you 😉 
After that it'll work

**Comment by danan46** [comment]
Hi @timgrossmann thank you so much, it works fine.

**Comment by iRatG** [comment]
Hello @timgrossmann , Thank you for your job!)
What I need to do to it is not written :"Wrong Login Data!" 
I start scipt from server not desktop.
![image](https://user-images.githubusercontent.com/25400376/30298192-27b07e58-9753-11e7-8427-21a7188286b7.png)

**Comment by timgrossmann** [comment]
@iRatG Make sure to login to your account on your own once, there will be a "Suspicious Login"-Something you just have to check.
After that It'll work 😉

**Comment by Apao123** [comment]
@timgrossmann  - I also experienced "suspicious login" email, however my phone and my chrome browser was logged as the instagram i run bot on. Will it work later?

I am waiting for the next event to happened in my general log heheh, if log doesn't show anything what should I do?
