### ISSUE TITLE
Keyword randomize doesn't work

### ISSUE THREAD

**Issue by WetkinTeodohr** [InstaPy/InstaPy#5803]
This is the line of code that gives me an error. I didn't put the location for privacy purposes. 
session.like_by_locations(['????'], amount=100, randomize=True)

#5050  Expected Behavior
I want it to randomize the posts it takes a look at.

## Current Behavior
It gives me back this error.
TypeError: like_by_locations() got an unexpected keyword argument 'randomize'

 I've been searching for why it does this but i can't come up with anything because everyone just uses the 'randomize' like this. 

Help would be much appreciated.

**Comment by elulcao** [comment]
> This is the line of code that gives me an error. I didn't put the location for privacy purposes.
> session.like_by_locations(['????'], amount=100, randomize=True)
> 
> #5050 Expected Behavior
> I want it to randomize the posts it takes a look at.
> 
> ## Current Behavior
> It gives me back this error.
> TypeError: like_by_locations() got an unexpected keyword argument 'randomize'
> 
> I've been searching for why it does this but i can't come up with anything because everyone just uses the 'randomize' like this.
> 
> Help would be much appreciated.

def like_by_locations() doesn't have randomize flag, I'm reviewing if a code change is needed
thanks

```python
    def like_by_locations(
        self,
        locations: list = None,
        amount: int = 50,
        media: str = None,
        skip_top_posts: bool = True,
    ):
```
