### ISSUE TITLE
Error during installation on Ubuntu with clarifai / configparser

### ISSUE THREAD

**Issue by filipstrapinadotcz** [InstaPy/InstaPy#5805]
During installation I found out error with compatibility.

`clarifai 2.6.2 requires configparser<4,>=3.5, but you'll have configparser 5.0.0 which is incompatible.`

Please change in the requirments.txt line **configparser>=3.5.0** to **configparser<4,>=3.5**
It will install 3.8.* which works without issue

**Comment by filipstrapinadotcz** [comment]
whoever has this problem with already installed InstaPy just type in cmd **pip install "configparser<4,>=3.5"** which will reinstall configparser to lower version.

**Comment by filiperivelli** [comment]
You can also try to update your PIP.

On Linux or macOS:
`pip install -U pip`

On Windows 4:
`python -m pip install -U pip`

**Comment by filipstrapinadotcz** [comment]
@filiperivelli no, that wont help and your reply to this problem does not make sense at all.
