### ISSUE TITLE
followers list are not loaded after certain number of people in the list, interact with someone else followers 

### ISSUE THREAD

**Issue by keivan85** [InstaPy/InstaPy#581]
I could reproduce this problem almost every time. It seems to be a problem with the Instagram itself that is trying to prevent crawling on pages.
The case is if you use a list of more than 4-5 users in interact_user_followers() input array, the 5th and onward followers of the users in the list are not shown.
Instead the followers window opens with circling animation that shows it is trying to load them. Then this error appears on terminal log
('user_name') -> less users to follow than requested.

**Comment by nnvum** [comment]
I have the feel that there might be a limit on the number of followers instagram is willing to display in a certain amount of time. Do you have a high frequency of changing between the 'user_name' where the new list of followers have to be requested? Does it help anything to simply increase to amount of followers from one user_name to interact with, before switching to a new user_name, hence requesting the new followers list less frequently?

**Comment by keivan85** [comment]
well for now the interact_user_followers() first tries to reach the followers of all the persons in list then starts interacting with them. So I can say it is almost 5-8 seconds pause between each request for list of followers. As you mentioned I guess it is the Instagram limitation.
One work around would be that the list of followers will be loaded. Then start interacting with them. After that next person followers list opens and so on.

**Comment by converge** [comment]
I'm working in this feature to unfollow who is not following me, and the main problem is that I can't get the full list of my account followers.

**Comment by converge** [comment]
@keivan85 I think this bug was fixed, could you confirm ?
