### ISSUE TITLE
Unfollow does not actually unfollow

### ISSUE THREAD

**Issue by gabriel-lemelle** [InstaPy/InstaPy#5812]
## Expected Behavior

When using : 

    session.unfollow_users(amount=randint(45,57), nonFollowers=True, style="FIFO",\
                           unfollow_after=randint(12,24)*60*60, sleep_delay=randint(400,600))

INFO [2020-10-05 11:19:07] [user] Ongoing Unfollow [7/53]: now unfollowing 'b'natachadlte''...

INFO [2020-10-05 11:19:41] [user] Last unfollow is verified after reloading the page!

INFO [2020-10-05 11:19:41] [user] --> Unfollowed 'natachadlte'!

Unfollow should have worked.
## Current Behavior
If I go back later and check if I still follow a user that was supposed to bu unfollowed, I still DO !!

## InstaPy configuration
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True)

docker run --name instapy -v \InstaPy\instapy-docker\docker-compose\runBotDocker.py:/code/docker_quickstart.py -v \InstaPy\instapy-docker\docker-compose\InstaPy:/code/InstaPy -d instapy

**Comment by Booleboole** [comment]
Same problem in some account
