### ISSUE TITLE
HELP 'account' might be temporarily blocked from following

### ISSUE THREAD

**Issue by PepeRender** [InstaPy/InstaPy#5817]
Hi there,

Im running instapy on my linux server, and on average I`m getting temporary block or ban once a day saying "'account' might be temporarily blocked from following". All I can do is to request via email a new password. Once I change password I get my instagram account back working again. Anybody has similar problems? thanks

**Comment by alexal1** [comment]
Yeah I had similar problems and finally implemented a solution for Android phones: https://github.com/alexal1/Insomniac
Limits are better when you run the script on the phone, and even if you get blocked you can simply reinstall Instagram app.

**Comment by PepeRender** [comment]
I don`t have spare Android device that I can leave constantly working with PC via USB cable. That is why I am using mu linux server instead and screen sessions once I`m away. 

There must be some other solution to this. Thanks for your reply.

**Comment by alexal1** [comment]
You can use emulator, e.g. https://www.genymotion.com/cloud/

**Comment by PepeRender** [comment]
> 
> 
> You can use emulator, e.g. https://www.genymotion.com/cloud/

Can I use BlueStacks on my PC instead of genymotion cloud? It seems like this service cost money.

**Comment by alexal1** [comment]
Yes, you can use BlueStacks of course

**Comment by shawnCaza** [comment]
> All I can do is to request via email a new password. Once I change password I get my instagram account back working again. Anybody has similar problems? thanks

I've been manually running instapy fairly infrequently over the past week. By no means hitting big numbers. Twice I've been locked out for suspicious activity that instagram thinks looked like phishing. Needing to change the password is super annoying.

**Comment by beeloved** [comment]
Does instagram say it thinks there was a phishing attempt?

That's what I get and I need to reset my password when it happens.

**Comment by elissonnog** [comment]
> Does instagram say it thinks there was a phishing attempt?
> 
> That's what I get and I need to reset my password when it happens.

I did that a few times too. I am getting this error weekly.
Anyone know how to solve?
