### ISSUE TITLE
LIFO behaving as FIFO

### ISSUE THREAD

**Issue by johannww** [InstaPy/InstaPy#5820]
InstaPy method: unfollow_users

When callin the following function:
**session.unfollow_users(amount=50, nonFollowers=True, style="FIFO", sleep_delay=400)**

## Expected Behavior
First to be unfollowed shoud be the latest user followed.

## Current Behavior
First to be unfollowed is the most recent followed.

## Possible Solution (optional)
- It only happens when nonFollowers = True. 

- When using a custom_list = True or instapy_followed_enabled = True, it works fine.

A possible solution is changing the code snippet on  **unfollow_util.py**

            **# Unfollow only the users who do not follow you back
            unfollow_list = get_nonfollowers(
                browser, username, relationship_data, False, True, logger, logfolder
            )**

**TO**

            **# Unfollow only the users who do not follow you back
            unfollow_list = list(reversed(get_nonfollowers(
                browser, username, relationship_data, False, True, logger, logfolder
            )))**

## InstaPy configuration
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False, page_delay=5)

session.set_blacklist(enabled=True, campaign="unfollow")

**Comment by elulcao** [comment]
> InstaPy method: unfollow_users
> 
> 
> 
> 
> 
> When callin the following function:
> 
> **session.unfollow_users(amount=50, nonFollowers=True, style="FIFO", sleep_delay=400)**
> 
> 
> 
> ## Expected Behavior
> 
> First to be unfollowed shoud be the latest user followed.
> 
> 
> 
> ## Current Behavior
> 
> First to be unfollowed is the most recent followed.
> 
> 
> 
> 
> 
> 
> 
> ## Possible Solution (optional)
> 
> - It only happens when nonFollowers = True. 
> 
> 
> 
> - When using a custom_list = True or instapy_followed_enabled = True, it works fine.
> 
> 
> 
> A possible solution is changing the code snippet on  **unfollow_util.py**
> 
> 
> 
>             **# Unfollow only the users who do not follow you back
> 
>             unfollow_list = get_nonfollowers(
> 
>                 browser, username, relationship_data, False, True, logger, logfolder
> 
>             )**
> 
> 
> 
> **TO**
> 
> 
> 
>             **# Unfollow only the users who do not follow you back
> 
>             unfollow_list = list(reversed(get_nonfollowers(
> 
>                 browser, username, relationship_data, False, True, logger, logfolder
> 
>             )))**
> 
> 
> 
> ## InstaPy configuration
> 
> session = InstaPy(username=insta_username,
> 
>                   password=insta_password,
> 
>                   headless_browser=False, page_delay=5)
> 
> 
> 
> session.set_blacklist(enabled=True, campaign="unfollow")
> 
> 

If you chose style="FIFO", the first element inserted is the first one to be dropped. If you chose FILO the first element inserted is the last one dropped. It seems that FIFO is working as expected based in you previous comment, your comment refers to FIFO.

**Comment by johannww** [comment]
Let me clarify:

Let's say I followed Anne, Bob and Claire in this order. First Anne, Last Claire.

If I perform the call:
**session.unfollow_users(amount=50, nonFollowers=True, style="FIFO", sleep_delay=400)**

The first to be unfollowed should be Anne, since _style="FIFO"_, but what happens is that Claire is the first to be unfollowed.

That's what I meant to explain.

**Comment by elulcao** [comment]
> Let me clarify:
> 
> Let's say I followed Anne, Bob and Claire in this order. First Anne, Last Claire.
> 
> If I perform the call:
> **session.unfollow_users(amount=50, nonFollowers=True, style="FIFO", sleep_delay=400)**
> 
> The first to be unfollowed should be Anne, since _style="FIFO"_, but what happens is that Claire is the first to be unfollowed.
> 
> That's what I meant to explain.


@johannww 

`session.unfollow_users` is using `FIFO` by default, the other two cases for LIFO and RANDOM
are configured until line 404-408, and `unfollow_list` is updated before in lines 318-320; so `unfollow_list` is updated just before starting unfollow actions.

```python
            # Unfollow only the users who do not follow you back
            unfollow_list = get_nonfollowers(
                browser, username, relationship_data, False, True, logger, logfolder
            )
```

```python
        # choose the desired order of the elements
        if style == "LIFO":
            unfollow_list = list(reversed(unfollow_list))
        elif style == "RANDOM":
            random.shuffle(unfollow_list)
```

**Comment by gabriel-lemelle** [comment]
Shouldn't your title be : FIFO behaving as LIFO ? I noticed it too.

**Comment by johannww** [comment]
@Gabyheavy it does not matter, since it goes both ways. FIFO is behaving as LIFO and LIFO is behaving as FIFO.

**Comment by johannww** [comment]
@elulcao I guess `get_nonfollowers` is generating a list where the most recent followed are appearing first, when `style=FIFO`. I don't know how Instagram orders followers/following, but it seems to have some relation with time.

I just tested and got the same behavior again, the most recent followed was the first selected to be unfollowed, with `FIFO`. If you perform a test you may get the same as I am getting (I do not know if you had).

I would naturally expect that, in `FIFO`, the user that I am following for more time would be the first to be unfollowed.

**Comment by elulcao** [comment]
Could you check now, with latest version
