### ISSUE TITLE
Ubuntu 18.04 - Selenium: Connection refused (os error 111) in InstaPy() func

### ISSUE THREAD

**Issue by michalpulpan** [InstaPy/InstaPy#5822]
## Expected Behavior
Start the script using `python3 config_loop.py`, log-in and start following/unfollowing.

## Current Behavior
After running `python3 config_loop.py` I get following error:
```
user@ubuntu:~/InstaPy$ python3 config_loop.py
InstaPy Version: 0.6.6
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/user/InstaPy"
Traceback (most recent call last):
  File "config_loop.py", line 208, in <module>
    follow()
  File "config_loop.py", line 36, in follow
    session = get_session()
  File "config_loop.py", line 20, in get_session
    headless_browser=True)
  File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/usr/local/lib/python3.6/dist-packages/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)
```

## InstaPy configuration
Logging:
```
def get_session():
    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=True)
    return session
```

Selenium version: 3.141.0
Mozilla Firefox 81.0
geckodriver 0.27.0
InstaPy version: 0.6.6

Thank you!

**Comment by elulcao** [comment]
> ## Expected Behavior
> Start the script using `python3 config_loop.py`, log-in and start following/unfollowing.
> 
> ## Current Behavior
> After running `python3 config_loop.py` I get following error:
> 
> ```
> user@ubuntu:~/InstaPy$ python3 config_loop.py
> InstaPy Version: 0.6.6
>  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
> Workspace in use: "/home/user/InstaPy"
> Traceback (most recent call last):
>   File "config_loop.py", line 208, in <module>
>     follow()
>   File "config_loop.py", line 36, in follow
>     session = get_session()
>   File "config_loop.py", line 20, in get_session
>     headless_browser=True)
>   File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 319, in __init__
>     self.logger,
>   File "/usr/local/lib/python3.6/dist-packages/instapy/browser.py", line 114, in set_selenium_local_session
>     options=firefox_options,
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
>     keep_alive=True)
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)
> ```
> 
> ## InstaPy configuration
> Logging:
> 
> ```
> def get_session():
>     session = InstaPy(username=insta_username,
>                       password=insta_password,
>                       headless_browser=True)
>     return session
> ```
> 
> Selenium version: 3.141.0
> Mozilla Firefox 81.0
> geckodriver 0.27.0
> InstaPy version: 0.6.6
> 
> Thank you!

InstaPy version is 0.6.6 but current release is 0.6.11
Try the latest one.

**Comment by michalpulpan** [comment]
> > ## Expected Behavior
> > Start the script using `python3 config_loop.py`, log-in and start following/unfollowing.
> > ## Current Behavior
> > After running `python3 config_loop.py` I get following error:
> > ```
> > user@ubuntu:~/InstaPy$ python3 config_loop.py
> > InstaPy Version: 0.6.6
> >  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
> > Workspace in use: "/home/user/InstaPy"
> > Traceback (most recent call last):
> >   File "config_loop.py", line 208, in <module>
> >     follow()
> >   File "config_loop.py", line 36, in follow
> >     session = get_session()
> >   File "config_loop.py", line 20, in get_session
> >     headless_browser=True)
> >   File "/usr/local/lib/python3.6/dist-packages/instapy/instapy.py", line 319, in __init__
> >     self.logger,
> >   File "/usr/local/lib/python3.6/dist-packages/instapy/browser.py", line 114, in set_selenium_local_session
> >     options=firefox_options,
> >   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
> >     keep_alive=True)
> >   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
> >     self.start_session(capabilities, browser_profile)
> >   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
> >     response = self.execute(Command.NEW_SESSION, parameters)
> >   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> >     self.error_handler.check_response(response)
> >   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> >     raise exception_class(message, screen, stacktrace)
> > selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)
> > ```
> > 
> > 
> > ## InstaPy configuration
> > Logging:
> > ```
> > def get_session():
> >     session = InstaPy(username=insta_username,
> >                       password=insta_password,
> >                       headless_browser=True)
> >     return session
> > ```
> > 
> > 
> > Selenium version: 3.141.0
> > Mozilla Firefox 81.0
> > geckodriver 0.27.0
> > InstaPy version: 0.6.6
> > Thank you!
> 
> InstaPy version is 0.6.6 but current release is 0.6.11
> Try the latest one.

Oh, well that was a stupid one... It runs on 0.6.11. Thank you and sorry.

**Comment by skiwlkr** [comment]
I'm having the same problem.
Running instapy on a Debian Docker 

`selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)`

Selenium version: 3.141.0
Mozilla Firefox 78.7.0esr
geckodriver 0.29.0
InstaPy version: 0.6.13

I'm running the latest instapy build, but I can't get it to work. Any Ideas?
