### ISSUE TITLE
Targets = [''] invalid syntax error

### ISSUE THREAD

**Issue by MajinFou** [InstaPy/InstaPy#5829]
C:\Users\Φου\Desktop\InstaPy-master>thodoris.py
  File "C:\Users\Φου\Desktop\InstaPy-master\thodoris.py", line 32
    targets = ['fourkalides']
    ^
SyntaxError: invalid syntax

**Comment by zubus** [comment]
Copy your file, remeber hide your credentials

**Comment by MajinFou** [comment]
"""
This template is written by @Nuzzo235
What does this quickstart script aim to do?
- This script is targeting followers of similar accounts and influencers.
- This is my starting point for a conservative approach: Interact with the
audience of influencers in your niche with the help of 'Target-Lists' and
'randomization'.
NOTES:
- For the ease of use most of the relevant data is retrieved in the upper part.
"""

import random
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'hihihi'
insta_password = 'hihixd'





""" Prevent posts that contain...
"""
ignore_list = [#herbalife, #wellness]

# TARGET data
""" Set similar accounts and influencers from your niche to target...
"""
targets = ['fourkalides','user2']




# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=True,
                  disable_image_load=True,
                  multi_logs=True)

# let's go! :>
with smart_run(session):
    # HEY HO LETS GO
    # general settings
    session.set_do_comment(enabled=False, percentage=80)
    session.set_dont_include(friends)
    session.set_dont_like(dont_likes)
    session.set_ignore_if_contains(ignore_list)
    session.set_ignore_users(ignore_users)
    session.set_simulation(enabled=True)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=1000,
                                    max_following=1000,
                                    min_followers=100,
                                    min_following=100,
                                    min_posts=10)

    session.set_skip_users(skip_private=True,
                           skip_no_profile_pic=True,
                           skip_business=True,
                           dont_skip_business_categories=[
                               target_business_categories])

    session.set_user_interact(amount=3, randomize=True, percentage=80,
                              media='Photo')
    session.set_do_like(enabled=True, percentage=90)
    session.set_do_comment(enabled=False, percentage=15)
    session.set_comments(comments, media='Photo')
    session.set_do_follow(enabled=False, percentage=40, times=1)

    # activities

    # FOLLOW+INTERACTION on TARGETED accounts
    """ Select users form a list of a predefined targets...
    """
    number = random.randint(1, 3)
    random_targets = targets

    if len(targets) <= number:
        random_targets = targets

    else:
        random_targets = random.sample(targets, number)

    """ Interact with the chosen targets...
    """
    session.follow_user_followers(random_targets,
                                  amount=random.randint(30, 60),
                                  randomize=False sleep_delay=600,
                                  interact=False)

   

    

    """ Joining Engagement Pods...
    """
    session.join_pods()

"""
Have fun while optimizing for your purposes, Nuzzo
"""

**Comment by zubus** [comment]
Please paste as code, maybe an indentation problem?

**Comment by MajinFou** [comment]
> Please paste as code, maybe an indentation problem?

i tried and it showed like this. how should i do this?
