### ISSUE TITLE
---> Image was not able to get Liked! maybe blocked ?

### ISSUE THREAD

**Issue by lucasandguitars** [InstaPy/InstaPy#5832]
Hi, this may have a simple solution, so can some of you more knowledgeable guys help me out?

I am not blocked and this has been happening ever since I have updated Firefox. Afterwards, I have updated python, geckodriver and Instapy altogether and still get the same issue.

I'm not using headless browser mode as similar past issues.

Thanks in advance!

## Expected Behavior
Like pictures

## Current Behavior
Image was not able to get Liked! maybe blocked ?

**Comment by aliciamorrow** [comment]
I am getting the same error as well, but it's not happening on every post so the bot still works overall and I haven't been penalized for using the bot yet. If someone knows what the issue is that'd be great, but at least it's still usable.

**Comment by lucasandguitars** [comment]
> 
> 
> I am getting the same error as well, but it's not happening on every post so the bot still works overall and I haven't been penalized for using the bot yet. If someone knows what the issue is that'd be great, but at least it's still usable.

Yes, it does work, but every other day I get this error most of the time. It doesn't have anything to do with penalization, since I've been testing it with more than a single account.

**Comment by aliciamorrow** [comment]
Ok

**Comment by Teknival** [comment]
@timgrossmann Help us my Bro :)

**Comment by elulcao** [comment]
I noticed that error or message comes from videos with large format, so selenium cannot detect the like button since is out of the scene. pull request (branch instagram_title_fix) has some changes to like and check when this happens. 


```
like_util.py:

like_image now needs to handle images and videos, for now just informing to the user
that a video was liked or not. For now if a video is found, it will move until comment section and verify if post has been liked or not.

It will be necessary to define if more actions needs to be
implemented (ie: play or not a video, detect when user posted a video and image in same post, etc.)

nit: Imports were ordered
handled unbounded variables
fixed some comments were double quotes were not necessary
```

**Comment by lucasandguitars** [comment]
@elulcao I think there may be some truth to your statement, but I have monitored after this. It has happened on "multiple picture posts" that were on potrait resolution, not including video content necessarily. Didn't have the luck of witnessing it happening to video posts. But, seems we're getting closer...

**Comment by lucasandguitars** [comment]
Update... multiple pics or not, it doesn't like some portrait format posts and videos. I think this is it. Can anyone else confirm this?

**Comment by elulcao** [comment]
Yep, is the same for pics or vids. Did you try the transaction? it is intended to scroll down the page until comment section to check if the Like has been clicked or not.

**Comment by lucasandguitars** [comment]
@elulcao actually I didn't, did that fix your problems? What exactly do I have to change and on which file, please?

**Comment by elulcao** [comment]
> @elulcao actually I didn't, did that fix your problems? What exactly do I have to change and on which file, please?

Changes were made in different files, could you check the code in `https://github.com/timgrossmann/InstaPy/pull/5813` it would be easy to fetch the transaction.

**Comment by lucasandguitars** [comment]
@elulcao I'm sorry to ask you this, man, but I'm a total newbie... :>... What exactly should I download/update/type? I'll do exactly as you say like a marionette, but I didn't understand anything on the link you provided as my knowledge is still very limited. :/ Thanks!

**Comment by elulcao** [comment]
@lucasandguitars 

The link provided is the reference for the latest changes, this is part of the process of adding code to an application in production. Automating is not a static task and therefore requires constant adaptation and modifications to the code, however new changes should always be thought of in a way that is generic and portable.

Regarding marionette is the automation driver, It is used to control de Firefox UI. On the other hand, geckodriver is the binary (the bin or exe file) downloaded that is used to start the Firefox browser. Sometimes it will be required to activate high level traces for the driver, by default is `info`, in order to see what's going on behind the scenes. 

I don't mean to sound rude, but my recommendation in these cases is to wait for a new version of Instapy to be published.
