### ISSUE TITLE
Instagram Cookie PopUp prevents automated LogIn [Fixed]

### ISSUE THREAD

**Issue by xSentry** [InstaPy/InstaPy#5834]
Lately Instagram shows the user a PopUp to Accept Cookies.
InstaPy doesn't handle that yet, so every LogIn fails.

I fixed it myself so if you need it too, just copy my Code:

Find your Python Instapy directory. (For me it is somewhere in `C:\Users\YOUR_USER\AppData\Local\Packages\`)
Open the instapy directory and find login_util.py
Go to the line right befor the Login (For me thats around `line 273`)

Copy following Code in there

```
#Check if Cookie PopUp is visible
    try:
        cookie_elem = browser.find_element_by_xpath("//button[text()='Accept']")
    except:
        cookie_elem = None

    if cookie_elem is not None:
        cookie_elem.click()
```

If this is too much for you, just download my attached file and put it in your instapy directory.
[login_util.zip](https://github.com/timgrossmann/InstaPy/files/5396867/login_util.zip)

**Comment by Sebadier** [comment]
Thank you! This worked for me!

**Comment by agutierrezl** [comment]
@xSentry I was having the same issue and this works for me!

**Comment by LukaszKopyszko** [comment]
> Lately Instagram shows the user a PopUp to Accept Cookies.
> InstaPy doesn't handle that yet, so every LogIn fails.
> 
> I fixed it myself so if you need it too, just copy my Code:
> 
> Find your Python Instapy directory. (For me it is somewhere in `C:\Users\YOUR_USER\AppData\Local\Packages\`)
> Open the instapy directory and find login_util.py
> Go to the line right befor the Login (For me thats around `line 273`)
> 
> Copy following Code in there
> 
> ```
> #Check if Cookie PopUp is visible
>     try:
>         cookie_elem = browser.find_element_by_xpath("//button[text()='Accept']")
>     except:
>         cookie_elem = None
> 
>     if cookie_elem is not None:
>         cookie_elem.click()
> ```
> 
> If this is too much for you, just download my attached file and put it in your instapy directory.
> [login_util.zip](https://github.com/timgrossmann/InstaPy/files/5396867/login_util.zip)

Ok, so i swapped the files now i'm getting 
TypeError: login_user() takes 8 positional arguments but 9 were given

**Comment by maxLakh** [comment]
> > Lately Instagram shows the user a PopUp to Accept Cookies.
> > InstaPy doesn't handle that yet, so every LogIn fails.
> > I fixed it myself so if you need it too, just copy my Code:
> > Find your Python Instapy directory. (For me it is somewhere in `C:\Users\YOUR_USER\AppData\Local\Packages\`)
> > Open the instapy directory and find login_util.py
> > Go to the line right befor the Login (For me thats around `line 273`)
> > Copy following Code in there
> > ```
> > #Check if Cookie PopUp is visible
> >     try:
> >         cookie_elem = browser.find_element_by_xpath("//button[text()='Accept']")
> >     except:
> >         cookie_elem = None
> > 
> >     if cookie_elem is not None:
> >         cookie_elem.click()
> > ```
> > 
> > 
> > If this is too much for you, just download my attached file and put it in your instapy directory.
> > [login_util.zip](https://github.com/timgrossmann/InstaPy/files/5396867/login_util.zip)
> 
> Ok, so i swapped the files now i'm getting
> TypeError: login_user() takes 8 positional arguments but 9 were given

Also me

**Comment by maxLakh** [comment]
> > > Lately Instagram shows the user a PopUp to Accept Cookies.
> > > InstaPy doesn't handle that yet, so every LogIn fails.
> > > I fixed it myself so if you need it too, just copy my Code:
> > > Find your Python Instapy directory. (For me it is somewhere in `C:\Users\YOUR_USER\AppData\Local\Packages\`)
> > > Open the instapy directory and find login_util.py
> > > Go to the line right befor the Login (For me thats around `line 273`)
> > > Copy following Code in there
> > > ```
> > > #Check if Cookie PopUp is visible
> > >     try:
> > >         cookie_elem = browser.find_element_by_xpath("//button[text()='Accept']")
> > >     except:
> > >         cookie_elem = None
> > > 
> > >     if cookie_elem is not None:
> > >         cookie_elem.click()
> > > ```
> > > 
> > > 
> > > If this is too much for you, just download my attached file and put it in your instapy directory.
> > > [login_util.zip](https://github.com/timgrossmann/InstaPy/files/5396867/login_util.zip)
> > 
> > 
> > Ok, so i swapped the files now i'm getting
> > TypeError: login_user() takes 8 positional arguments but 9 were given
> 
> Also me

Found solution, do not download the file, just paste the code that @xSentry  posted.

**Comment by xSentry** [comment]
> 
> 
> > > > Lately Instagram shows the user a PopUp to Accept Cookies.
> > > > InstaPy doesn't handle that yet, so every LogIn fails.
> > > > I fixed it myself so if you need it too, just copy my Code:
> > > > Find your Python Instapy directory. (For me it is somewhere in `C:\Users\YOUR_USER\AppData\Local\Packages\`)
> > > > Open the instapy directory and find login_util.py
> > > > Go to the line right befor the Login (For me thats around `line 273`)
> > > > Copy following Code in there
> > > > ```
> > > > #Check if Cookie PopUp is visible
> > > >     try:
> > > >         cookie_elem = browser.find_element_by_xpath("//button[text()='Accept']")
> > > >     except:
> > > >         cookie_elem = None
> > > > 
> > > >     if cookie_elem is not None:
> > > >         cookie_elem.click()
> > > > ```
> > > > 
> > > > 
> > > > If this is too much for you, just download my attached file and put it in your instapy directory.
> > > > [login_util.zip](https://github.com/timgrossmann/InstaPy/files/5396867/login_util.zip)
> > > 
> > > 
> > > Ok, so i swapped the files now i'm getting
> > > TypeError: login_user() takes 8 positional arguments but 9 were given
> > 
> > 
> > Also me
> 
> Found solution, do not download the file, just paste the code that @xSentry posted.

The File is outdated but the Code should work fine, as long as you just copy it like @elmaxsabe said.
@LukaszKopyszko

**Comment by defconV** [comment]
For me this didn't work, so I tried to create something new with my feeble coding skills. This is it:
#Check if Cookie PopUp is visible #5834 altered by DevconV
    try:
        cookie_elem = browser.find_element(
            By.XPATH, "//button[text()='Decline optional cookies']")
    except NoSuchElementException:
        try:
            cookie_elem = browser.find_element(
                By.XPATH, "//button[contains(@class, '_acan')]")
        except NoSuchElementException:
            cookie_elem = None

    if cookie_elem is not None:
        cookie_elem.click()

**Comment by xedthecreative** [comment]
guys,
how it is possile issue has not been fixed until now? There is any support for this code or not?
Could someone help me to fix this? I've tried code attached but didn't works

**Comment by xedthecreative** [comment]
@defconV could you help me please? I'm using InstaPy 0.6.16, if we use same version could you attach your login file here?
