### ISSUE TITLE
Current Instagram Ratios

### ISSUE THREAD

**Issue by OnlyOneMoreHour** [InstaPy/InstaPy#5838]
## Expected Behavior
Get blocked 

## Current Behavior
Not getting blocked :-)

## Possible Solution (optional)
Need more actions

## InstaPy configuration

Hello, 

Does anyone know the current ratios for instagram of liking, commenting, following per hour/day/week?

**Comment by erensunerr** [comment]
Check out this post: https://socialpros.co/instagram-daily-limits

**Comment by OnlyOneMoreHour** [comment]
> 
> 
> Check out this post: https://socialpros.co/instagram-daily-limits

thank you! That helps!
