### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by mcolus** [InstaPy/InstaPy#5840]
## Expected Behavior
Login into Instagram.
## Current Behavior

```
Cookie file not found, creating cookie...
Login A/B test detected! Trying another string...
```
I used an fix about the cookies but the problem still remain

**Comment by Lxand3r** [comment]
Same here it did run for a few minutes and then started showing in this error

**Comment by shifenis** [comment]
A found a workaround for this problem. It seems doesn't present anymore. If this solution would be accepted by the community, we can propose a pull request.

In the attachment, you can find the patch.

[cookie_fix.zip](https://github.com/timgrossmann/InstaPy/files/5431923/cookie_fix.zip) (see #5834)

**Comment by pierrecasenave** [comment]
doesn't seem to be working for me unfortunately. Running InstaPy 0.5.0, will try to update to a more recent version and see if it works
