### ISSUE TITLE
Instapy get blocked instantly 

### ISSUE THREAD

**Issue by Atumos** [InstaPy/InstaPy#5847]
Hi guys
I was using Instapy for like two days and then I get blocked by Instagram. Is there a way to avoid this? I searched for solutions but I din't found one.

**Comment by mcolus** [comment]
Which settings did you use?

**Comment by alexal1** [comment]
You may want to try [Insomniac](https://github.com/alexal1/Insomniac). Same idea as InstaPy, but works on Android phone/emulator, thus limits are much better. There's a quite big community and it's quickly growing. Setup will take a few minutes if you're familiar with InstaPy already.

**Comment by bronzeboy** [comment]
> You may want to try [Insomniac](https://github.com/alexal1/Insomniac). Same idea as InstaPy, but works on Android phone/emulator, thus limits are much better. There's a quite big community and it's quickly growing. Setup will take a few minutes if you're familiar with InstaPy already.

But it's paid to even like by hashtag

**Comment by ghost** [comment]
> But it's paid to even like by hashtag

Yes, but on the other hand it doesn't **get blocked instantly**

**Comment by alexal1** [comment]
@bronzeboy here's a free activation code especially for you

~~`d79b10d1-bc64-416a-875b-fbfd9eaed3e5`~~

It's an early stage and I will appreciate any testing
**UPD**: this activation code doesn't work, but it's not necessary anymore. See my comment below

**Comment by bronzeboy** [comment]
> @bronzeboy here's a free activation code especially for you
> 
> `d79b10d1-bc64-416a-875b-fbfd9eaed3e5`
> 
> It's an early stage and I will appreciate any testing

Thanks, I'm testing it even if on my tablet it dosen't seems to work but it does with android emulation for now

**Comment by Atumos** [comment]
> Which settings did you use?

I've used this script:

with smart_run(session):
    """ Activity flow """
    # general settings
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=3000,
                                    max_following=900,
                                    min_followers=50,
                                    min_following=50)

    session.set_user_interact(amount=3, randomize=True, percentage=100, media='Photo')
    session.set_do_like(enabled=True, percentage=100
    
    session.follow_user_followers(['l'], amount=500, sleep_delay=60,
                                  randomize=False, interact=True)

**Comment by Atumos** [comment]
> @bronzeboy here's a free activation code especially for you
> 
> `d79b10d1-bc64-416a-875b-fbfd9eaed3e5`
> 
> It's an early stage and I will appreciate any testing

Where can i activate it?

**Comment by nikshepsvn** [comment]
hey @alexal1 any chance you can drop me a free activation code? would love to give this a go

**Comment by alexal1** [comment]
@nikshepsvn you can use the same one actually

**Comment by Atumos** [comment]
> @nikshepsvn you can use the same one actually

thank you!

**Comment by alexal1** [comment]
After a bit of a heated discussion 🔥 in our [Discord server](https://discord.gg/59pUYCw) we changed our policy, and now all "core" features are free. It means that **interaction by hashtags' likers, interaction with users' followers, unfollowing, etc.** now work from the box for free. Welcome -> https://github.com/alexal1/Insomniac
