### ISSUE TITLE
"This web browser is no longer supported." error make it impossible to like?

### ISSUE THREAD

**Issue by bronzeboy** [InstaPy/InstaPy#5850]
Hi, if you put headless mode to false, you can see an error "This web browser is no longer supported." and it seems that now I can't like anymore just from the bot. I can like just fine from any other places, After days, the block dosen't go away, anyone got this problem?

**Comment by filiperivelli** [comment]
Same issue here.

**Comment by ghost** [comment]
same problem pls help
