### ISSUE TITLE
error " key play "

### ISSUE THREAD

**Issue by AntouanK** [InstaPy/InstaPy#5856]
getting this error today ( using latest docker image to run it ) : 
```
Traceback (most recent call last):
  File "docker_quickstart.py", line 138, in <module>
    bot.like_by_locations([random.choice(locations)], amount=4, skip_top_posts=True)
  File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 1531, in like_by_locations
    liked_img,
  File "/usr/local/lib/python3.7/site-packages/instapy/like_util.py", line 759, in like_image
    play_xpath = read_xpath(like_image.__name__, "play")
  File "/usr/local/lib/python3.7/site-packages/instapy/xpath.py", line 5, in read_xpath
    return xpath[function_name][xpath_name]
KeyError: 'play'
```

**Comment by elulcao** [comment]
@AntouanK 
Let me check this issue, could you share the details for your env and configuration?

**Comment by AntouanK** [comment]
sure

I have a script that looks like this : 
```
#!bash

ROOT_DIR=$(pwd)/__RootInstaPy

echo '___ pull latest'
docker pull instapy/instapy;

echo '___ remove existing instabot container'
docker stop instabot;
docker rm -f instabot;

echo '___ restore the pools'
mkdir -p $ROOT_DIR/logs/.../
cp ./__csv/* $ROOT_DIR/logs/.../

echo '___ starting docker container...'
docker run \
    --rm \
    --name instabot \
    -v $ROOT_DIR:/root/InstaPy:rw \
    -v $(pwd)/docker_quickstart.py:/code/docker_quickstart.py:ro \
    -v $(pwd)/__tmp:/tmp:rw \
    -v $(pwd)/login_util.py:/usr/local/lib/python3.7/site-packages/instapy/login_util.py:ro \
    instapy/instapy || exit 1;

echo '___ save logs'
tar -xvf general.log.gz
cat $ROOT_DIR/logs/.../general.log >> general.log
tar -cvzf general.log.gz general.log

echo '___ save the pools'
cp $ROOT_DIR/logs/.../*.csv ./__csv/

echo 'remove all temp contents'
rm -rf $ROOT_DIR/*
rm -rf ./__tmp/*
```

and then the `docker_quickstart.py` is like the examples, just modified a bit with other tags, locations, etc.

I tried removing some functions ( like_by_location, or to play stories ) but still same error every time.
I think it happens whenever it likes a photo.

**Comment by elulcao** [comment]
> sure
> 
> I have a script that looks like this :
> 
> ```
> #!bash
> 
> ROOT_DIR=$(pwd)/__RootInstaPy
> 
> echo '___ pull latest'
> docker pull instapy/instapy;
> 
> echo '___ remove existing instabot container'
> docker stop instabot;
> docker rm -f instabot;
> 
> echo '___ restore the pools'
> mkdir -p $ROOT_DIR/logs/.../
> cp ./__csv/* $ROOT_DIR/logs/.../
> 
> echo '___ starting docker container...'
> docker run \
>     --rm \
>     --name instabot \
>     -v $ROOT_DIR:/root/InstaPy:rw \
>     -v $(pwd)/docker_quickstart.py:/code/docker_quickstart.py:ro \
>     -v $(pwd)/__tmp:/tmp:rw \
>     -v $(pwd)/login_util.py:/usr/local/lib/python3.7/site-packages/instapy/login_util.py:ro \
>     instapy/instapy || exit 1;
> 
> echo '___ save logs'
> tar -xvf general.log.gz
> cat $ROOT_DIR/logs/.../general.log >> general.log
> tar -cvzf general.log.gz general.log
> 
> echo '___ save the pools'
> cp $ROOT_DIR/logs/.../*.csv ./__csv/
> 
> echo 'remove all temp contents'
> rm -rf $ROOT_DIR/*
> rm -rf ./__tmp/*
> ```
> 
> and then the `docker_quickstart.py` is like the examples, just modified a bit with other tags, locations, etc.
> 
> I tried removing some functions ( like_by_location, or to play stories ) but still same error every time.
> I think it happens whenever it likes a photo.

Looking at this one, 
I will share my findings soon

**Comment by elulcao** [comment]
This problem is due to outdated `xpath_compile.py` in instapy-docker repo.

Dockerfile replace `xpath_compile.py` in line `28` and hence the file `/usr/local/lib/python3.7/site-packages/instapy/xpath_compile.py` in the Docker image is not the latest one.


You can compare following blocks and adjust in your instapy-docker directory (the host that is running docker), and re-build the image.

```python
xpath["dissmiss_save_information"] = {
    "offer_elem_loc": "//*[contains(text(), 'Save Info')]",
    "dismiss_elem_loc": "//*[contains(text(), 'Not Now')]",
}

xpath["like_image"] = {
    "like": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Like']",
    "unlike": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Unlike']",
    "play": "//*/span[contains(@aria-label, 'Play')]",
}
```

Instapy-docker will start smoothly after added the missing xpath definitions
```bash
root@cd21ef367c5d:/code# python docker_quickstart.py
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/code/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-10-30 14:32:35] [internet]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-10-30 14:32:35] [internet]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-10-30 14:32:36] [internet]  - Internet Connection Status: ok
INFO [2020-10-30 14:32:36] [internet]  - Current IP is "0.0.0.0" and it's from "AC/DC"
INFO [2020-10-30 14:32:36] [internet]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-10-30 14:32:36] [internet]  - window.navigator.webdriver response: None
INFO [2020-10-30 14:32:36] [internet]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
INFO [2020-10-30 14:32:56] [internet]  Do not save Login Info by now
...................................................................
INFO [2020-10-30 14:33:03] [internet]  Logged in successfully!
```

---

This is from outdated `xpath_compile.py`:
```python
root@4fb5c5dbf444:/code# sed -n 32,43p  /usr/local/lib/python3.7/site-packages/instapy/xpath_compile.py

xpath["dismiss_notification_offer"] = {
    "offer_elem_loc": "//div/h2[text()='Turn on Notifications']",
    "dismiss_elem_loc": "//button[text()='Not Now']",
}

xpath["extract_information"] = {
    "close_overlay": "//div/div[@role='dialog']",
    "one_pic_elem": "//section/main/article/div[1]/div/div[10]/div[3]/a/div",
    "like_element": "//a[@role='button']/span[text()='Like']/..",
}

root@4fb5c5dbf444:/code# sed -n 143,148p  /usr/local/lib/python3.7/site-packages/instapy/xpath_compile.py

xpath["like_image"] = {
    "like": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Like']",
    "unlike": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Unlike']",
}
```

Further details in Updating xpath compile #83 (https://github.com/InstaPy/instapy-docker/pull/83)

**Comment by AntouanK** [comment]
thank you so much for looking into this @elulcao ! :+1: 
I'll see how to adapt my setup

**Comment by AntouanK** [comment]
all I did for now is, "cat" that file from the docker image, add the lines you gave me, and mount the new file back with
`-v $(pwd)/xpath_compile.py:/usr/local/lib/python3.7/site-packages/instapy/xpath_compile.py:ro \`

looks fine now.
thank you again.

just wondering though, is the docker image "lagging" behind the latest code in the repo in general?
If so, I might be better building the docker image locally after pulling the latest in the repo?
