### ISSUE TITLE
do you know how to set the supervisor quota without having blocks?

### ISSUE THREAD

**Issue by Polkyanik** [InstaPy/InstaPy#5860]
I always get banned from Instagram by changing my password: (
do you know how to set the supervisor quota without having blocks?

mine is set like this:

>QUOTA SUPERVISOR
 session.set_quota_supervisor(enabled=True, sleep_after=["likes_h", "comments_h", "follows_h", "unfollows_h", "server_calls_h"], 
 sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes_hourly=40,
                              peak_likes_daily=180,
                              peak_comments_hourly=30,
                              peak_comments_daily=180,
                              peak_follows_hourly=48,
                              peak_follows_daily=100,
                              peak_unfollows_hourly=35,
                              peak_unfollows_daily=100,
                              peak_server_calls_hourly=200,
                              peak_server_call_daily=2500)
_________________________

@elulcao 
I don't know how to fix .. ;(

**Comment by elulcao** [comment]
> I always get banned from Instagram by changing my password: (
> do you know how to set the supervisor quota without having blocks?
> 
> mine is set like this:
> 
> > QUOTA SUPERVISOR
> > session.set_quota_supervisor(enabled=True, sleep_after=["likes_h", "comments_h", "follows_h", "unfollows_h", "server_calls_h"],
> > sleepyhead=True, stochastic_flow=True, notify_me=True,
> > peak_likes_hourly=40,
> > peak_likes_daily=180,
> > peak_comments_hourly=30,
> > peak_comments_daily=180,
> > peak_follows_hourly=48,
> > peak_follows_daily=100,
> > peak_unfollows_hourly=35,
> > peak_unfollows_daily=100,
> > peak_server_calls_hourly=200,
> > peak_server_call_daily=2500)
> 
> @elulcao
> I don't know how to fix .. ;(

Hi @Polkyanik 

there is no final combination, I guess it depends of different factors. I have 5 different accounts (3 monitored in one smartphone, 2 monitored in other smartphone), all of them have been blocked at some point. 
If you detect too many `Block on likes` stop the execution for at least other 24hrs, I don't recommend to delete the pkl file. 

Sharing what I'm using in 5 different accounts, what has worked for me is to use the bot every 24 hrs, it means running InstaPy once for each acct.

```python
    session.set_action_delays(
        enabled=True,
        like=5.2,
        randomize=True,
        random_range_from=70,
        random_range_to=140,
    )

    session.set_quota_supervisor(
        enabled=True,
        peak_likes_daily=200,
        peak_likes_hourly=50,
        peak_comments_daily=50,
        peak_comments_hourly=200,
    )

    session.set_delimit_commenting(enabled=True, max_comments=None, min_comments=30)

    session.set_delimit_liking(enabled=True, max_likes=None, min_likes=30)

    session.set_delimit_commenting(enabled=True, max_comments=None, min_comments=10)

    session.set_mandatory_language(enabled=True, character_set=["LATIN"])
```

**Comment by Polkyanik** [comment]
I understand very well.
I counted in your answer, and it arrived, you are always active .. thank you very much it will be a good example for other users too
I'll try so and you
I update you

Thanks again

**Comment by Polkyanik** [comment]
hi @elulcao 

I understand very well.
I counted in your answer, and it arrived, you are always active .. thank you very much it will be a good example for other users too
I'll try this and let you know


Thanks again

**Comment by elulcao** [comment]
@Polkyanik 
Let me add my two cents,

This is the output for my last execution, it runs at least ~4.5hrs and that's why my bot is configured to run every 24hrs; I cannot imagine a real user looking pics at IG ~8hrs per day (but who knows...) 

I'm sure IG can detect when an account is being used in an automated way just because it spends a lot of time looking at and commenting on photos. I even think that if some real user abuses IG, they can also be banned (cool down) for health. 

If you ask me, another way to play IG is to use different combinations per day (other tags, comments, target accts, etc.), in such a way that a pattern of behavior cannot be established.

```bash
INFO [2020-11-02 19:49:58] [user]  Sessional Live Report:
        |> LIKED 171 images  |  ALREADY LIKED: 23
        |> COMMENTED on 8 images
        |> FOLLOWED 47 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 5 users
        |> LIKED 0 comments
        |> REPLIED to 0 comments
        |> INAPPROPRIATE images: 757
        |> NOT VALID users: 0
        |> WATCHED 0 story(ies)  |  WATCHED 0 reel(s)

On session start was FOLLOWING 303 users & had 47 FOLLOWERS
[Session lasted 4.64 hours]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-11-02 19:49:58] [user]  Session ended!
````

sharing my other specs, 
Use them only as reference and adjust based on your requirements; 
**It is worth mentioning that my configuration is not final at all and I am only sharing what has worked for me.**

```python
# general settings
comments=[<your comments>]
tags = [<your tags>]
targets = [<your targets>]

session.set_comments(comments)
session.set_dont_like(<your htags>)
session.set_do_comment(enabled=True, percentage=50)
session.set_dont_include(<Real friend's accounts to skip>)
session.set_action_delays(
        enabled=True,
        like=5.2,
        randomize=True,
        random_range_from=70,
        random_range_to=140,
    )
session.set_quota_supervisor(
        enabled=True,
        peak_likes_daily=200,
        peak_likes_hourly=50,
        peak_comments_daily=200,
        peak_comments_hourly=50,
    )
session.set_delimit_liking(enabled=True, max_likes=None, min_likes=30)
session.set_delimit_commenting(enabled=True, max_comments=None, min_comments=10)
session.set_mandatory_language(enabled=True, character_set=["LATIN"])
session.set_do_story(enabled=True, percentage=45, simulate=False)
session.set_dont_unfollow_active_users(enabled=True, posts=5)
session.interact_user_followers(
        targets, amount=random.randint(30, 60), randomize=True
    )

# activity
session.accept_follow_requests(amount=10, sleep_delay=10)
session.follow_user_following(
        [<Favorite users>],
        amount=5,
        randomize=True,
        interact=True,
        sleep_delay=60,
    )
session.follow_user_followers(
       [<Favorite users>],
        amount=5,
        randomize=True,
        interact=True,
        sleep_delay=60,
    )
session.follow_likers(
        [<Favorite users>],
        photos_grab_amount=10,
        follow_likers_per_photo=3,
        randomize=True,
        sleep_delay=600,
        interact=True,
    )
session.unfollow_users(
        amount=5,
        nonFollowers=False,
        instapy_followed_enabled=True,
        instapy_followed_param="all",
        style="FIFO",
        unfollow_after=90 * 60 * 60,
        sleep_delay=60,
    )
session.like_by_feed(amount=10, randomize=True, unfollow=False, interact=True)
session.like_by_tags(tags, amount=10, use_random_tags=True)
session.like_by_locations(
        [<Favorite locations>],
        amount=10,
        randomize=True,
    )
```
**It is worth mentioning that my configuration is not final at all and I am only sharing what has worked for me.**

**Comment by Polkyanik** [comment]
@elulcao 
fantastic !!, you are of great help to me as always .. i will try and let you know ... thanks a lot

**Comment by elulcao** [comment]
Setting InstaPy limits is responsibility of InstaPy user, 
each user can define the limits to have a better result depending on the audience to be reached. There are some references in different forums on how to circumvent the limits of IG, however it cannot be determined the real values unless someone have access to the source code of the IG algorithms. 🔢
