### ISSUE TITLE
interact_user_followers generates endless GraphQL queries

### ISSUE THREAD

**Issue by McFredward** [InstaPy/InstaPy#5863]
## Expected Behavior
Collect amount of followers of a specific user
## Current Behavior
Last Log: **GraphQL query hash: [...]**
Generates endless GraphQL requests within the browser like:
`{"data":{"user":{"edge_followed_by":{"count":1490809,"page_info":{"has_next_page":false,"end_cursor":null},"edges":[]},"edge_mutual_followed_by":{"count":0,"edges":[]}}},"status":"ok"}`
with the URL:
`view-source:https://www.instagram.com/graphql/query/?query_hash...`
Nothing more happens. No error or termination. Tried it many times, a few hours, even on different machines
## InstaPy configuration
Python3, InstaPy Version: 0.6.12
(dont_likes & targets are lists specified before)

```
with smart_run(session):
    session.set_dont_like(dont_likes)
    session.set_simulation(enabled=True)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=None,
                                    max_following=None,
                                    min_followers=200,
                                    min_following=None,
                                    min_posts=5)

    session.set_skip_users(skip_private=True,
                           skip_no_profile_pic=True,
                           skip_business=False)

    session.set_user_interact(amount=3, randomize=True, percentage=80,
                              media='Photo')
    session.set_do_like(enabled=True, percentage=90)
    session.set_do_comment(enabled=True, percentage=15)
    session.set_comments(comments, media='Photo')```

    session.interact_user_followers(targets,
                                  amount=random.randint(30, 60),
                                  randomize=True)

**Comment by lateleves** [comment]
Have you solved this problem? It happens to me the same issue.

**Comment by HaimBendanan** [comment]
Broken for me too

**Comment by elulcao** [comment]
FYI:
I could not reproduce the issue for `session.interact_user_followers` empty query.
Configuration in #5860 is working fine to me,

**Comment by bangoroo** [comment]
I had the same issue. Here how it can be fixed:
in unfollow_util.py line 820:
` followers_list = []`
Delete or comment this out. 
Otherwise it will always clear the actual followerlist and go into an endless loop.

**Comment by elulcao** [comment]
> I had the same issue. Here how it can be fixed:
> in unfollow_util.py line 820:
> ` followers_list = []`
> Delete or comment this out.
> Otherwise it will always clear the actual followerlist and go into an endless loop.

That's correct, 
Theres a double declaration that needs to be removed.

**Comment by dylzeee** [comment]
Same issue here, the fix didn't work for me, unfortunately, any ideas?

**Comment by elulcao** [comment]
I tried with my IG acct and query is not empty.
(personal info was masked in output)

```python
with smart_run(session):
 session.set_comments(comments)
 session.set_dont_like(own_list)
 session.set_simulation(enabled=True)
 session.set_do_comment(enabled=True, percentage=50)
session.set_relationship_bounds(
        enabled=True,
        potency_ratio=None,
        delimit_by_numbers=True,
        max_followers=None,
        max_following=None,
        min_followers=200,
        min_following=None,
        min_posts=5,
    )
 session.set_skip_users(
        skip_private=True, skip_no_profile_pic=True, skip_business=False
    )
 session.set_user_interact(amount=5, randomize=True, percentage=100, media="Photo")
 session.set_do_like(enabled=True, percentage=90)
 session.interact_user_followers(
        random.sample(targets, random.randint(1, 5)),
        amount=random.randint(30, 60),
        randomize=True,
    )
```


```bash
1605205183257	webdriver::server	DEBUG	<- 200 OK {"value":"{\"data\":{\"user\":{\"edge_followed_by\":{\"count\":3625562,\"page_info\":{\"has_next_page\":true,\"end_cursor\":\"QVFDeUItV1pnaHpUbkh5RlNjX2l3NnVNaXlSbWh
...
,\"username\":\"internet\"}}}}]},\"edge_mutual_followed_by\":{\"count\":50,\"edges\":[{\"node\":{\"id\":\"4523
...
```

**Comment by madwols** [comment]
> Same issue here, the fix didn't work for me, unfortunately, any ideas?

didn't work for me too
