### ISSUE TITLE
InstaPy bot not interacting with posts

### ISSUE THREAD

**Issue by billyk1997** [InstaPy/InstaPy#5875]
## Expected Behavior
InstaPy should like 5 posts each for two different hashtags, plus four others. Of these 14 posts, the bot should follow half of the users who posted these images and/or post one of three comments under half the posts.
## Current Behavior
When run, the program outputs the following (I changed my IP address and Instagram username for privacy reasons):

`InstaPy Version: 0.6.11
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/NAME/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-11-08 19:09:33] [USERNAME]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-11-08 19:09:33] [USERNAME]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-11-08 19:09:36] [USERNAME]  - Internet Connection Status: ok
INFO [2020-11-08 19:09:36] [USERNAME]  - Current IP is "IPADDRESS" and it's from "United States/US"
INFO [2020-11-08 19:09:36] [USERNAME]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-11-08 19:09:36] [USERNAME]  - window.navigator.webdriver response: None
INFO [2020-11-08 19:09:36] [USERNAME]  - Hide Selenium Extension: ok
.................................................................
INFO [2020-11-08 19:09:49] [USERNAME]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2020-11-08 19:09:49] [USERNAME]  Saving account progress...
INFO [2020-11-08 19:10:04] [USERNAME]  Tag [1/2]
INFO [2020-11-08 19:10:04] [USERNAME]  --> b'foodie'
INFO [2020-11-08 19:10:12] [USERNAME]  desired amount: 14  |  top posts [disabled]: 9  |  possible posts: 0
INFO [2020-11-08 19:10:18] [USERNAME]  Tag: b'foodie'
INFO [2020-11-08 19:10:18] [USERNAME]  Tag [2/2]
INFO [2020-11-08 19:10:18] [USERNAME]  --> b'foodporn'
INFO [2020-11-08 19:10:27] [USERNAME]  desired amount: 14  |  top posts [disabled]: 9  |  possible posts: 0
INFO [2020-11-08 19:10:35] [USERNAME]  Tag: b'foodporn'
INFO [2020-11-08 19:10:35] [USERNAME]  Liked: 0
INFO [2020-11-08 19:10:35] [USERNAME]  Already Liked: 0
INFO [2020-11-08 19:10:35] [USERNAME]  Commented: 0
INFO [2020-11-08 19:10:35] [USERNAME]  Followed: 0
INFO [2020-11-08 19:10:35] [USERNAME]  Inappropriate: 0
INFO [2020-11-08 19:10:35] [USERNAME]  Not valid users: 0

INFO [2020-11-08 19:10:38] [USERNAME]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 713 users & had 216 FOLLOWERS
[Session lasted 1.21 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-11-08 19:10:38] [USERNAME]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo
`
## Possible Solution (optional)
Not sure what to do about this, since this exact program was working fine only a couple of weeks ago.
## InstaPy configuration

`import instapy

session = instapy.InstaPy(username="USERNAME", password="PASSWORD!", headless_browser = True)
session.login()
session.like_by_tags(["foodie", "foodporn"], amount = 5)
session.set_do_follow(True, percentage = 50)
session.set_do_comment(True, percentage = 50)
session.set_comments(["Delicious!", "That looks soooo good!", "I'm hungry now! :yum:"])
session.end()`

**Comment by supernova1992** [comment]
This is because instagram is hiding the recent posts temporarily due to the elections in the US. Because the script can't find any recent posts for the hashtag, it reports back 0 possible posts to interact with and moves on.

**Comment by billyk1997** [comment]
> This is because instagram is hiding the recent posts temporarily due to the elections in the US. Because the script can't find any recent posts for the hashtag, it reports back 0 possible posts to interact with and moves on.

Thank you @supernova1992. Would you happen to have any idea of when Instagram will un-hide recent posts?

**Comment by supernova1992** [comment]
Unfortunately, I have no idea.

**Comment by giulioco** [comment]
Also noticing this issue. Is there any work around for the time being?

**Comment by lgv-0** [comment]
Same error, I used `headless_browser=False` to view and I get the "2020 election" error message - but if I use my iPhone, I get the same popup about recent posts being hidden, but posts _load anyway_ - from 3 days ago to 3 hours ago. Might be worth capturing some network traffic and see what url's it's calling

**Comment by Jasonhadzi** [comment]
Did anyone find a workaround for this?

**Comment by jsantoos** [comment]
I find a solution, 

You have to set by mandatory words and like by locations. Will have more requests, it is not so efficient, but works.
