### ISSUE TITLE
WebDriverException: Message: Expected absolute path

### ISSUE THREAD

**Issue by Ericzzzzz** [InstaPy/InstaPy#5876]
## Current Behavior
All Geckodriver, instapy and Firefox are at their latest version. But still this error occur. Any Help will be appreciated. 

selenium.common.exceptions.WebDriverException: Message: Expected absolute path: [Exception... "Component returned f
ailure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]"  nsresult: "0x80520001 (NS_ERROR_
FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: chrome://marionette/content/addon.js :: install :: line 70"  data:
 no]

**Comment by elulcao** [comment]
Could you share more details, 
OS version, if you are using `custom path` for geckodriver, InstaPy version.

**Comment by Ericzzzzz** [comment]
Thank you for your reply,

I'm using InstaPy on Google Cloud Platform with VM instance. I believe I didn't set custom path for geckodriver, and my InstaPy version is 0.6.12

**Comment by Ericzzzzz** [comment]
We solved the issue by manually changing the create_firefox_extension in browser.py to have the absolute path from our home directory
