### ISSUE TITLE
Stuck on GraphQL query hash

### ISSUE THREAD

**Issue by gustavoribeirorg** [InstaPy/InstaPy#5877]
## Expected Behavior
Get the list of the followers from current profile
## Current Behavior
It's opens the source code from the profile and get stuck with the title info on CMD.
## InstaPy configuration
Latest version running in conda enviroment using "basic_follow-unfollow_activity" template.

**Comment by ghost** [comment]
Same issue, used on docker compose. Method: follow_user_followers.

**Comment by utsav1810** [comment]
Same issue. Method: follow_user_followers.

**Comment by elulcao** [comment]
> ## Expected Behavior
> Get the list of the followers from current profile
> 
> ## Current Behavior
> It's opens the source code from the profile and get stuck with the title info on CMD.
> 
> ## Possible Solution (optional)
> ## InstaPy configuration
> Latest version running in conda enviroment using "basic_follow-unfollow_activity" template.

Seems to be the same like issue 5863,

**Comment by bubbatarx** [comment]
Same issue in 2021. Did anyone ever get it working?
