### ISSUE TITLE
Issue: can't apply this __setattr__ to instance object

### ISSUE THREAD

**Issue by zinzinjb** [InstaPy/InstaPy#5879]
Hello, I install Instapy on Mac osx. 
I can't launch Instapy i have this error:

object.__setattr__(self, '_obj', None)
TypeError: can't apply this __setattr__ to instance object

What can i do ?

**Comment by v0lumehi** [comment]
What exactly did you do that made you encounter this error?

**Comment by elulcao** [comment]
This is more often due to how an instance object was accessed.
