### ISSUE TITLE
Unable to login to Instagram! You will find more information in the logs above

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5883]
This is what I am currently getting after running the quickstart.

> 
> INFO [2020-11-12 04:01:25] [ianisacat]  Using built in instapy-chromedriver executable (version 2.46)
> 
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2020-11-12 04:01:26] [ianisacat]  Session started!
> oooooooooooooooooooooooooooooooooooooooooooooooooooooo
> 
> INFO [2020-11-12 04:01:26] [ianisacat]  -- Connection Checklist [1/2] (Internet Connection Status)
> INFO [2020-11-12 04:01:58] [ianisacat]  - Internet Connection Status: ok
> INFO [2020-11-12 04:01:58] [ianisacat]  -- Connection Checklist [2/2] (Instagram Server Status)
> INFO [2020-11-12 04:02:31] [ianisacat]  - Instagram WebSite Status: Currently Up 
> INFO [2020-11-12 04:02:31] [ianisacat]  - Instagram Response Time: 87.367 ms 
> INFO [2020-11-12 04:02:32] [ianisacat]  - Instagram Reponse Code: 200
> INFO [2020-11-12 04:02:32] [ianisacat]  - Instagram Server Status: ok
> Cookie file not found, creating cookie...
> Login A/B test detected! Trying another string...
> 
> .......................................................................................................................
> CRITICAL [2020-11-12 04:02:47] [ianisacat]  Unable to login to Instagram! You will find more information in the logs above.
> '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
> ERROR [2020-11-12 04:02:47] [ianisacat]  You have too few comments, please set at least 10 distinct comments to avoid looking suspicious.
> 
> INFO [2020-11-12 04:02:47] [ianisacat]  Sessional Live Report:
> 	|> No any statistics to show
> 
> 
> [Session lasted 1.36 minutes]
> 
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2020-11-12 04:02:47] [ianisacat]  Session ended!
> oooooooooooooooooooooooooooooooooooooooooooooooooooooo
> 
I have checked that I have more than ten comments, this is my code.

> from instapy import InstaPy
> from instapy import smart_run
> 
> insta_username = 'user'
> insta_password = 'pass'
> 
> # get a session!
> session = InstaPy(username=insta_username,
>                   password=insta_password,
>                   headless_browser=True,
>                   multi_logs=True)
> 
> # let's go! :>
> with smart_run(session):
>     # general settings
>     session.set_relationship_bounds(enabled=True,
>                                     potency_ratio=None,
>                                     delimit_by_numbers=True,
>                                     max_followers=6000,
>                                     max_following=3000,
>                                     min_followers=30,
>                                     min_following=30)
>     session.set_user_interact(amount=2, randomize=True, percentage=30,
>                               media='Photo')
>     session.set_do_like(enabled=True, percentage=100)
>     session.set_do_comment(enabled=False, percentage=5)
>     session.set_comments(
>         ['Nice shot!', 'I love your profile!', 'Love it!',
>         '@{} :heart::heart:',
>         'Love your posts',
>         'Looks awesome',
>         'Getting inspired by you',
>         ':raised_hands: Yes!',
>          'revolving_hearts::revolving_hearts:',
>          'Great Shot!', 'love it!!!'],
>         media='Photo')
> 
>     # unfollow activity
>     session.unfollow_users(amount=126, nonFollowers=True, style="RANDOM",
>                            unfollow_after=42 * 60 * 60, sleep_delay=300)
> 
>     # follow activity
>     ammount_number = 500
>     session.follow_user_followers(['chrisburkard', 'danielkordan'],
>                                   amount=ammount_number, randomize=False,
>                                   interact=True, sleep_delay=240)
> 
>     """ Joining Engagement Pods...
>     """
>     session.join_pods(topic='entertainment', engagement_mode='light')
> 
>

**Comment by ghost** [comment]
bump

**Comment by wsmith9897** [comment]
I have the same exact issue.
