### ISSUE TITLE
Stuck at "Cookie file not found, creating cookie..."

### ISSUE THREAD

**Issue by rever92** [InstaPy/InstaPy#5886]
Hi guys!
Anyone could help me with an issue? Im quite sure its a very common trouble, but i cant seam to fix it :frowning:
I run the script but i get stuck in "Cookie file not found, creating cookie..." and then it crashes :frowning:

This is what i get:

`WARNING [2020-11-12 08:28:59] [USERNAME]  Cookie file not found, creating cookie...
INFO [2020-11-12 08:29:41] [USERNAME]  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
C:\Users\user\AppData\Local\Temp\20201112-082946.html
**********************************************************************

INFO [2020-11-12 08:29:46] [USERNAME]  Sessional Live Report:
        |> No any statistics to show

[Session lasted 57.04 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-11-12 08:29:46] [USERNAME]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File ".\instapytest.py", line 23, in <module>
    with smart_run(session):
  File "C:\Python37\lib\contextlib.py", line 114, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield`

**Comment by ghost** [comment]
I have the same issue on Ubutu 18.04.
Everyting work fine till yestarday

**Comment by v0lumehi** [comment]
Cookies seem to be broken atm. Every time I am starting a session and the bot tries to create a new cookie, the selenium driver crashes. I have to restart the bot until it's not trying to recreate the cookie

**Comment by feelqah** [comment]
Hi,
I stumbled upon this issue today.

The problem is that Instagram added a second Cookie Accept button after the first one when you open instagram for the first time (without cookies), and this wasn't handled in the current code (I'm using InstaPy 0.6.12).

For a quick fix you can add this line:
`browser.find_element_by_xpath("/html/body/div[2]/div/div/div/div[2]/button[1]").click()`

in [login_util.py:269](https://github.com/timgrossmann/InstaPy/blob/8a2366d7e8aaaa7dda133c15cf76083df57e5d6a/instapy/login_util.py#L269) after the `if cookie_loaded:` statement.

I wanted to open a PR, but if I'm not mistaken, I see the issue is already handled by [PR#5894](https://github.com/timgrossmann/InstaPy/pull/5894/commits/0ffb797aa81f18f3f87a01370745ea60d35d22d7)

**Comment by frederikme** [comment]
Hi, 
As feelquah already mentioned, the issue lies with Instagram whom added a second cookie accept form.
However, the solution he mentioned did only work for me when the following line of code was put BEFORE the `if cookie_loaded:` statement on line 269. `browser.find_element_by_xpath("/html/body/div[2]/div/div/div/div[2]/button[1]").click()`

**Comment by frederikme** [comment]
Consider using a WebdriverWait or time.sleep before the statement in case your internet connection isn't flawless. :)

**Comment by fintzd** [comment]
> For a quick fix you can add this line:
> `browser.find_element_by_xpath("/html/body/div[2]/div/div/div/div[2]/button[1]").click()`
> 
> in [login_util.py:269](https://github.com/timgrossmann/InstaPy/blob/8a2366d7e8aaaa7dda133c15cf76083df57e5d6a/instapy/login_util.py#L269) after the `if cookie_loaded:` statement.

@feelqah Major thank you! After looking around for a fix for about 4 hours, you just saved my mental health! :)

**Comment by elulcao** [comment]
@feelqah @rever92 

current version is intended to handle the case cookie does not exist,
actually the intention is not to save the login Info since latter on the cookie will be saved.

```bash
1605405086448	webdriver::server	DEBUG	-> POST /session/5b9b9daa-98e64b52057d/element {"using": "xpath", "value": "//*[contains(text(), 'Not Now')]"}
1605405086448	Marionette	DEBUG	0 -> [0,32,"WebDriver:FindElement",{"using":"xpath","value":"//*[contains(text(), 'Not Now')]"}]
```

```bash
Workspace in use: "/Users/internet/GitHub/InstaPy_Info"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-11-14 19:13:43] [internet]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-11-14 19:13:43] [internet]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-11-14 19:13:44] [internet]  - Internet Connection Status: ok
INFO [2020-11-14 19:13:44] [internet]  - Current IP is "0.0.0.0" and it's from "AC/DC"
INFO [2020-11-14 19:13:44] [internet]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-11-14 19:13:44] [internet]  - window.navigator.webdriver response: None
INFO [2020-11-14 19:13:44] [internet]  - Hide Selenium Extension: ok
WARNING [2020-11-14 19:13:47] [internet]  Cookie file not found, creating cookie...
INFO [2020-11-14 19:14:02] [internet]  Do not save Login Info by now
...................................................................
INFO [2020-11-14 19:14:09] [internet]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2020-11-14 19:14:09] [internet]  Saving account progress...
INFO [2020-11-14 19:14:24] [internet]  Getting active users who liked the latest 5 posts:
  ~collecting the usernames from posts with the boundary of 500
```

**Comment by v0lumehi** [comment]
@feelqah yes, you are right. I am currently working on a fix for this

**Comment by XTANG16** [comment]
I was having this same issue. I was using the FireFox browser and found that the cookie message didn't actually pop out, yet the issue still exists. While tracing the execution, I found that the login_user() function within login_util module has the login_state =False even after the account is actually logged in. The dumb fix I did was to get the following if statement to always pass:
'# if login_state is True:
    if True:
        dismiss_notification_offer(browser, logger)
        dissmiss_save_information(browser, logger)
        return True

this seems to have fixed my issue. So I'm thinking maybe there are some issues with InstaPy to get the login_state, but I don't know how/why.

**Comment by francofilo** [comment]
In which directory do I need to change the login user function?...

**Comment by ghost** [comment]
Its not working for me I try all methods mentioned here

**Comment by christophg88** [comment]
Hey, I also still have the problem. Is there any solution available?

**Comment by francofilo** [comment]
No man

**Comment by skiwlkr** [comment]
Same here. Can't login anymore. Stuck on cookie creation.

**Comment by christophg88** [comment]
Hey, the following solution worked for me: https://github.com/timgrossmann/InstaPy/issues/5834

**Comment by mamadza** [comment]
Hi I have the same issue

**Comment by FrancescoSaverioZuppichini** [comment]
same here

**Comment by scanu92** [comment]
A valid workaround for now is the following:

```
...
    browser.find_element_by_xpath("/html/body/div[3]/div/div/button[1]").click()
    logger.info("+ Accepted panel cookies")
    sleep(2) # Wait that the panel will close
...
```
in the file **login_util.py** before the line:

`if cookie_loaded:`

obviously, if the html of the page change this snippet is not valid anymore

**Comment by DennyWeinberg** [comment]
`"//*[text()='Accept All']"`

**Comment by Scarlatss** [comment]
> `"//*[text()='Accept All']"`

Where do I have to put this ?

**Comment by talib32** [comment]
Insert the following in xpath_compile.py:
xpath["accept_igcookie_dialogue"] = {"accept_button": "//button[text()='Accept All']"}

**Comment by ViralAgency** [comment]
> The last line in xpath_compile.py is currently:
> 
> `xpath["accept_igcookie_dialogue"] = {"accept_button": "//button[text()='Accept']"}`
> 
> The actual button on the Instagram log in page is named "Accept All" so this needs to be changed in that line:
> 
> `xpath["accept_igcookie_dialogue"] = {"accept_button": "//button[text()='Accept All']"}`

This solved for me. Thanks.
