### ISSUE TITLE
Like_by_tag redirection problem ! 

### ISSUE THREAD

**Issue by Aminesanhaji** [InstaPy/InstaPy#5887]
Hello everyone,
So the problem is when I use Like_by_tag, it redirects me to to my username path like this instead of tags page. 
![Screenshot from 2020-11-13 09-55-19](https://user-images.githubusercontent.com/46084510/99049424-1f477c00-2597-11eb-8aca-86ffd7116752.png)
 
that's the code I'm using : 
![Screenshot from 2020-11-13 10-04-38](https://user-images.githubusercontent.com/46084510/99049917-b8769280-2597-11eb-966b-ec1cd43e4c36.png)

**Comment by v0lumehi** [comment]
You don't need to type in your mail address as username. username is simply your instagram username

**Comment by Aminesanhaji** [comment]
Thank you ! it works. i used my username instead of email or mobile ! that was the problem

**Comment by elulcao** [comment]
closing this one, based on latest comment
