### ISSUE TITLE
After loggin sucsessfuly instapy do not do tasks given with session (exit with no replay just close connection)

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5892]
python "instagrambot Final.py" --username techno_booster --password pass! --like_by tags --batch_file tags.txt -a 50
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/jjsol/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-11-13 12:42:15] [techno_booster]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-11-13 12:42:15] [techno_booster]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-11-13 12:42:15] [techno_booster]  - Internet Connection Status: ok
INFO [2020-11-13 12:42:15] [techno_booster]  - Current IP is "162.199.218.100" and it's from "United States/US"
INFO [2020-11-13 12:42:16] [techno_booster]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-11-13 12:42:16] [techno_booster]  - window.navigator.webdriver response: None
INFO [2020-11-13 12:42:16] [techno_booster]  - Hide Selenium Extension: ok
....................................................................
INFO [2020-11-13 12:42:32] [techno_booster]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2020-11-13 12:42:32] [techno_booster]  Saving account progress...
INFO [2020-11-13 12:42:48] [techno_booster]  Tag [1/3]
INFO [2020-11-13 12:42:48] [techno_booster]  --> b'techno'
INFO [2020-11-13 12:42:57] [techno_booster]  desired amount: 59  |  top posts [disabled]: 9  |  possible posts: 0
INFO [2020-11-13 12:43:04] [techno_booster]  Tag: b'techno'
INFO [2020-11-13 12:43:04] [techno_booster]  Tag [2/3]
INFO [2020-11-13 12:43:04] [techno_booster]  --> b'rave'
INFO [2020-11-13 12:43:13] [techno_booster]  desired amount: 59  |  top posts [disabled]: 9  |  possible posts: 0
INFO [2020-11-13 12:43:19] [techno_booster]  Tag: b'rave'
INFO [2020-11-13 12:43:19] [techno_booster]  Tag [3/3]
INFO [2020-11-13 12:43:19] [techno_booster]  --> b'technodj'
INFO [2020-11-13 12:43:26] [techno_booster]  desired amount: 59  |  top posts [disabled]: 9  |  possible posts: 0
INFO [2020-11-13 12:43:35] [techno_booster]  Tag: b'technodj'
INFO [2020-11-13 12:43:35] [techno_booster]  Liked: 0
INFO [2020-11-13 12:43:35] [techno_booster]  Already Liked: 0
INFO [2020-11-13 12:43:35] [techno_booster]  Commented: 0
INFO [2020-11-13 12:43:35] [techno_booster]  Followed: 0
INFO [2020-11-13 12:43:35] [techno_booster]  Inappropriate: 0
INFO [2020-11-13 12:43:35] [techno_booster]  Not valid users: 0
I just use basic config one task per run and its stop when its need to perform an action 

this is the configs.
if(args.proxy and args.username and args.password):
	session = InstaPy(username=args.username, password=args.password, proxy_address=args.proxy, proxy_port=args.port, headless_browser=True)
else:
	session = InstaPy(username=args.username, password=args.password,  headless_browser=True)
session.login()

##Quota Supervisior dhourly and day limits

session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes_hourly=45,
                              peak_likes_daily=1000,
                               peak_comments_hourly=21,
                               peak_comments_daily=182,
                                peak_follows_hourly=48,
                                peak_follows_daily=None,
                                 peak_unfollows_hourly=35,
                                 peak_unfollows_daily=402,
                                  peak_server_calls_hourly=None,
                                  peak_server_calls_daily=4700)

if args.like_by == 'tags' or args.like_by == 'location':
	with open(args.batch_file, 'r') as file:
		data = [line.strip() for line in file]
		if(args.like_by == 'location'):
			session.like_by_locations(data, amount=args.amount)
		elif(args.like_by == 'tags'):
			session.like_by_tags(data, amount=args.amount)

this is the geckodriver log
###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

1605289329583	geckodriver	INFO	Listening on 127.0.0.1:56374
1605289332638	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\jjsol\\AppData\\Local\\Temp\\rust_mozprofileHTslWF"
Can't find symbol 'eglSwapBuffersWithDamageEXT'.
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
1605289335031	Marionette	INFO	Listening on port 56382
1605289335306	Marionette	WARN	TLS certificate errors will be ignored for this session
JavaScript error: resource://gre/modules/URIFixup.jsm, line 271: NS_ERROR_FAILURE: Should pass a non-null uri
1605289430722	Marionette	INFO	Stopped listening on port 56382

###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost

###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv

**Comment by v0lumehi** [comment]
First of all, it would help a lot if you would use Markdown to format your code properly. This allows us to read your code better.
Despite that, I would advise you to take a look at the quickstart templates here:
https://github.com/InstaPy/instapy-quickstart

There is no need for such conditional logic as you have in your script. 
By calling the proper functions that can be seen in the docs (https://instapy.org/settings/) you ensure that the bot is being used properly. Try that and let me know if that helped

**Comment by lgv-0** [comment]
Looks like #5875 to begin with (no posts), issues with connections unrelated though.
