### ISSUE TITLE
[Suggestion] Avoid cron

### ISSUE THREAD

**Issue by Naramsim** [InstaPy/InstaPy#590]
Since cron seems to not be working for everyone...

You can suggest on the README to use alternatively https://github.com/dbader/schedule

**Comment by timgrossmann** [comment]
@Naramsim Would you be interested in creating a PR with the changes?
If yes, make sure to not only describe it but also add a small piece of code that can easily be copied.

Thanks

**Comment by timgrossmann** [comment]
#603
