### ISSUE TITLE
 I pay for those who make everything work for me

### ISSUE THREAD

**Issue by ManuelCode1** [InstaPy/InstaPy#5903]
I have a vps with centos 7 for those who manage to install everything working I pay it!

**Comment by jsantoos** [comment]
Hi...

**Comment by kersvanbinsbergen** [comment]
I'll pay too.

raspberry pi3

**Comment by jsantoos** [comment]
I can configure, send me an e-mail: msn-jp@live.com so we combine values.

**Comment by elulcao** [comment]
Closing it,
not an issue.
