### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by alperglcoglu** [InstaPy/InstaPy#5904]
C:\Users\alper\PycharmProjects\instabot\venv\Scripts\python.exe C:/Users/alper/PycharmProjects/instabot/main.py
InstaPy Version: 0.6.11
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/alper/InstaPy"
Traceback (most recent call last):
  File "C:/Users/alper/PycharmProjects/instabot/main.py", line 12, in <module>
    credentials = InstaPy(username="holy_memmes123",
  File "C:\Users\alper\PycharmProjects\instabot\venv\lib\site-packages\instapy\instapy.py", line 321, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\alper\PycharmProjects\instabot\venv\lib\site-packages\instapy\browser.py", line 134, in set_selenium_local_session
    browser.install_addon(create_firefox_extension(), temporary=True)
  File "C:\Users\alper\PycharmProjects\instabot\venv\lib\site-packages\instapy\browser.py", line 47, in create_firefox_extension
    with zipfile.ZipFile(zip_file, "w", zipfile.ZIP_DEFLATED, False) as zipf:
  File "C:\Users\alper\AppData\Local\Programs\Python\Python38-32\lib\zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\alper\\InstaPy\\assets\\extension.xpi'

Process finished with exit code 1

**Comment by elulcao** [comment]
Check the form for the workspace path:

```
Workspace in use: "C:/Users/alper/InstaPy"
```

```
OSError: [Errno 22] Invalid argument: 'C:\Users\alper\InstaPy\assets\extension.xpi'
```

**Comment by Zayxon-Tech** [comment]
Sorry what do you mean by check the form for workspace path?

**Comment by alperglcoglu** [comment]
> Check the form for the workspace path:
> 
> ```
> Workspace in use: "C:/Users/alper/InstaPy"
> ```
> 
> ```
> OSError: [Errno 22] Invalid argument: 'C:\Users\alper\InstaPy\assets\extension.xpi'
> ```

What should do to workspace path?

**Comment by Zayxon-Tech** [comment]
> > Check the form for the workspace path:
> > ```
> > Workspace in use: "C:/Users/alper/InstaPy"
> > ```
> > 
> > 
> > ```
> > OSError: [Errno 22] Invalid argument: 'C:\Users\alper\InstaPy\assets\extension.xpi'
> > ```
> 
> What should do to workspace path?

For you to solve this error you need to go to the extension.xpi file in the assests folder in your InstaPy folder, and you need to delete the file

**Comment by elulcao** [comment]
In Windows the user is required to specify the location of the geckodriver binary,
in this case the path is pointing to an extension instead to the driver.

ie: 
```python
session = InstaPy(
	username="internet", 
	password="qinDakru4", 
	geckodriver_path="C:\\Users\\internet\\Downloads\\geckodriver",)

# Execution:
PS C:\Users\internet\Downloads\InstaPy-master> python .\quickstart.py
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
No any custom workspace provided.       ~using existing..
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/internet/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-12-01 18:07:22] [internet]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-12-01 18:07:22] [internet]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-12-01 18:07:22] [internet]  - Internet Connection Status: ok
INFO [2020-12-01 18:07:22] [internet]  - Current IP is "0.0.0.0" and it's from "AC/DC"
INFO [2020-12-01 18:07:23] [internet]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-12-01 18:07:23] [internet]  - window.navigator.webdriver response: None
INFO [2020-12-01 18:07:23] [internet]  - Hide Selenium Extension: ok
WARNING [2020-12-01 18:07:28] [internet]  Cookie file not found, creating cookie...
INFO [2020-12-01 18:07:44] [internet]  Do not save Login Info by now
...................................................................
INFO [2020-12-01 18:07:54] [internet]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2020-12-01 18:07:54] [internet]  Saving account progress...
INFO [2020-12-01 18:08:10] [internet]  Tag [1/1]
INFO [2020-12-01 18:08:10] [internet]  --> b'natgeo'
```
