### ISSUE TITLE
Instapy run but don't do anything in DigitalOcean

### ISSUE THREAD

**Issue by MundoBoss** [InstaPy/InstaPy#5906]
## Expected Behavior
Instapy must like and comment people content by tag, like always

## Current Behavior
Logged in successfully!
INFO [2020-11-16 15:20:57] [XXXX]  Saving account progress...
INFO [2020-11-16 15:21:14] [XXXX]  Tag [1/5]
INFO [2020-11-16 15:21:14] [XXXX]  --> b'simplicitevolontaire'
INFO [2020-11-16 15:21:22] [XXXX]  desired amount: 19  |  top posts [disabled]: 9  |  possible posts: 0
INFO [2020-11-16 15:21:28] [XXXX]  Tag: b'simplicitevolontaire'
INFO [2020-11-16 15:21:28] [XXXX]  Tag [2/5]
INFO [2020-11-16 15:21:28] [XXXX]  --> b'viedeparents'
INFO [2020-11-16 15:21:36] [XXXX]  desired amount: 19  |  top posts [disabled]: 9  |  possible posts: 0
INFO [2020-11-16 15:21:41] [XXXX]  Tag: b'viedeparents'
INFO [2020-11-16 15:21:41] [XXXX]  Tag [3/5]
INFO [2020-11-16 15:21:41] [XXXX]  --> b'mamandedeux'
etc..

Nothing more happen, Instapy do just like if his job is done but.. it do nothing..
Just before that I had the same issue but with "Too few images, skip..." issue, and now it just go from a tag to another without liking or commenting nothing;;

## Possible Solution (optional)
Ghostban ? Need to put a proxy? The thing is that Im not sure its that and if its that, is there a way to create a proxy with my home IP that will be used by my bot ? Because its with that IP that I connect to this instagram account normally..
Thanks for your help and sorry for my bad language, Im a poor French instapy user who use your super bot from long time ago..

## InstaPy configuration

```
# !/usr/bin/python2.7
import random
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace


# Creating a workspace
set_workspace(path=None)  # currently there is not working path

# get a session!
session = InstaPy(username='XXXXX', password='XXXXX', headless_browser=True)

# let's go! :>
with smart_run(session):
    hashtags = ['simplicitevolontaire','lesregardergrandir','acompagnementparental','viedeparents','mamandedeux']
    random.shuffle(hashtags)
    my_hashtags = hashtags[:10]

    # general settings
    session.set_dont_like(['saddddd'])
    session.set_do_follow(enabled=True, percentage=25, times=1)
    session.set_do_comment(enabled=True, percentage=70)
    session.set_comments([
                             u'My comments are here, I got so much so I just show this one haha'],
                         media='Photo')
    session.set_do_like(True, percentage=45)
    session.set_delimit_liking(enabled=True, max_likes=100, min_likes=0)
    session.set_delimit_commenting(enabled=True, max_comments=20, min_comments=0)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=15000,
                                    max_following=15000,
                                    min_followers=70,
                                    min_following=70)

    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "follows"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes_hourly=None,
                                 peak_likes_daily=None,
                                 peak_comments_hourly=8,
                                 peak_comments_daily=224,
                                 peak_follows_hourly=None,
                                 peak_follows_daily=None,
                                 peak_unfollows_hourly=None,
                                 peak_unfollows_daily=None,
                                 peak_server_calls_hourly=None,
                                 peak_server_calls_daily=4700)

    session.set_user_interact(amount=2, randomize=True, percentage=70)

    # activity
    session.like_by_tags(my_hashtags, amount=10, media=None)
    session.unfollow_users(amount=10, instapy_followed_enabled=True, instapy_followed_param="nonfollowers",
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=501)
    session.unfollow_users(amount=10, instapy_followed_enabled=True, instapy_followed_param="all",
                           style="FIFO", unfollow_after=24 * 60 * 60,
                           sleep_delay=501)
```

**Comment by lgv-0** [comment]
Looks like #5875

**Comment by MundoBoss** [comment]
Thanks for your reply @lgv-0 ! Look exactly the same issue but when I search a tag with my phone everything look normal, I dont know, that’s because I’m in france possibly ? The IP of my bot is in Amsterdam, dont see relation with US election here either.. 

Other point: when I launch without clearing cookie I get this: « IndexError: list index out of range«  and the bot stop

**Comment by MundoBoss** [comment]
Any suggestion ? The bot work well on my labtop with my home IP in Windows and with headless browser false

**Comment by fintzd** [comment]
Hey @MundoBoss , I'd say it's probably the IP of you DigitalOcean server that could be at the root of the issue indeed. 
As mentioned on [InstaPy's website](https://instapy.org/instance-settings), as apparently Instagram can detect the headless browsers. 

> Warning: Some users discourage the use of this feature as Instagram could detect this headless mode!

So it could be a combination of the IP of your server plus the headless mode. You should either setup a proxy at home, and set the script to run through your home IP, and check if it works that way, or just run it in a VirtualBox for example that you can boot on your computer when using it.

**Comment by Jasonhadzi** [comment]
Do we have an alternative if we want to run the script on the server?

**Comment by fintzd** [comment]
Well that's what I'm trying to figure out too @Jasonhadzi :) I'll let you know once I have some time to try to figure out a way for that. One idea would be to simulate a screen so that you can run the browser without having to put it in headless mode, but that's just where I am now, at the idea level! 

If you've got something up your sleeves, let me know! :)

Cheers

**Comment by elulcao** [comment]
Using docker with VNCserver enabled could be used to run InstaPy, 
the FF window would be hidden since the VNC would not be visible
unless you enter it. I'm not sure it works in this case from DigitalOcean, 
but it doesn't hurt to try.
However, if the problem is the IP, I would recommend using a proxy.

**Comment by fintzd** [comment]
Thank you @elulcao I'll give it a try! :)
