### ISSUE TITLE
Is there a way to use the instaPy library for particular actions?

### ISSUE THREAD

**Issue by oren1991** [InstaPy/InstaPy#5907]
If don't aim to fully automate an instagram page. I would just need to gather some posts, collect comments with certain hashtags etc stuff like that.

This lib seems to be very settingbased and not instructionbased. Does it have an API I could use for specific tasks?

**Comment by Aassifh** [comment]
Same need  for me too !

**Comment by fintzd** [comment]
No sure what either of you guys mean exactly, but you've got the full documentation of [InstaPy's possible functionalities](https://instapy.org/settings/) on its website, pretty neatly documented. I linked it there for you, hope you'll find what you need!

**Comment by elulcao** [comment]
Check `https://instapy.org` for further details.
