### ISSUE TITLE
TypeError: target_list() missing 1 required positional argument: 'file'

### ISSUE THREAD

**Issue by SergeyHat** [InstaPy/InstaPy#5911]
## Expected Behavior
adding people from your friends list
## Current Behavior
Traceback (most recent call last):
  File "C:\Users\serge\Desktop\insta\main.py", line 26, in <module>
    users = session.target_list("C:\\Users\\serge\\Desktop\\insta\\user.txt")
TypeError: target_list() missing 1 required positional argument: 'file'

## InstaPy configuration

users = session.target_list("C:\\Users\\serge\\Desktop\\insta\\user.txt")
session.follow_user_followers(users, amount=10, randomize=False)

**Comment by elulcao** [comment]
Can you share how the users list has been saved.
I didn't see any issue in my local.


```bash

cat ../internet/logs/users.txt
adidas
nike
dolcegabbana

   users = session.target_list("/Users/internet/logs/users.txt")
   session.follow_user_followers(users, amount=10, randomize=False)


INFO [2020-11-23 18:48:07] [internet]  Starting to follow user `Followers`..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2020-11-23 18:48:07] [internet]  User 'adidas' [1/3]
INFO [2020-11-23 18:48:13] [internet]  GraphQL query hash: [c7614642346415203be841dd25a]
INFO [2020-11-23 18:48:16] [internet]  To be followed: [1/10/internet]
INFO [2020-11-23 18:48:16] [internet]  To be followed: [2/10/internet]
INFO [2020-11-23 18:48:16] [internet]  To be followed: [3/10/internet]
```
