### ISSUE TITLE
First login always successful, all login attempts after that always fail

### ISSUE THREAD

**Issue by soshial** [InstaPy/InstaPy#5912]
## Expected Behavior
Logging in should always work.

## My code
```
# imports
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace


# set workspace folder at desired location (default is at your home folder)
set_workspace(path="...")

# get an InstaPy session!
session = InstaPy(username='...', password='...')
session.login()

with smart_run(session):
    # general settings
    # session.set_dont_include(["friend1", "friend2", "friend3"])
    popeye_followers = session.grab_followers(username="...", amount="full", live_match=True, store_locally=True)
    print(popeye_followers)
```

## Current Behavior
```
Traceback (most recent call last):
  File "C:\Users\alens\Desktop\Lonya\InstaPy\quickstart.py", line 14, in <module>
    session.login()
  File "C:\Users\alens\Desktop\Lonya\InstaPy\instapy\instapy.py", line 425, in login
    if not login_user(
  File "C:\Users\alens\Desktop\Lonya\InstaPy\instapy\login_util.py", line 249, in login_user
    browser.add_cookie(cookie)
  File "C:\Users\alens\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium-4.0.0a7-py3.9.egg\selenium\webdriver\remote\webdriver.py", line 1016, in add_cookie
    assert cookie_dict['sameSite'] in ['Strict', 'Lax']
AssertionError
```
## InstaPy configuration
Win 10 (64-bit)
Firefox 83.0 (64-bit)
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:23:07) [MSC v.1927 32 bit (Intel)] on win32

**Comment by fintzd** [comment]
Have you checked issue #5886 ? 

Had the same / similar issue, but the wonderful @feelqah seemed to have found the solution by adding a snippet of code in here:
> in [login_util.py:269](https://github.com/timgrossmann/InstaPy/blob/8a2366d7e8aaaa7dda133c15cf76083df57e5d6a/instapy/login_util.py#L269) after the if cookie_loaded: statement.

> For a quick fix you can add this line:
browser.find_element_by_xpath("/html/body/div[2]/div/div/div/div[2]/button[1]").click()

**Comment by soshial** [comment]
Thank you, but it **didn't help** unfortunately.

**Comment by soshial** [comment]
Any other ideas? I would love to provide as much info as I can.

**Comment by fintzd** [comment]
Hey @soshial , have you tried resetting the firefox cookies? I was suggested to do that to make it work, plus seems like that could be the solution here as per the error message:
`File "C:\Users\alens\AppData\Local\Programs\Python\Python39-32\lib\site-packages\selenium-4.0.0a7-py3.9.egg\selenium\webdriver\remote\webdriver.py", line 1016, in add_cookie
    assert cookie_dict['sameSite'] in ['Strict', 'Lax']`
