### ISSUE TITLE
after last changes in unfollow_util.py by pull #5855 i have an issue

### ISSUE THREAD

**Issue by Tolmino** [InstaPy/InstaPy#5914]
i can't unfollow without that error:
ERROR [2020-11-18 15:13:35] [xxxxxxxxx]  Sorry, an error occurred: get_followers() missing 1 required positional argument: 'logfolder'

this is the command that generate that issue:
bot.unfollow_users(amount=4, instapy_followed_enabled=True, instapy_followed_param="nonfollowers" , style="FIFO", unfollow_after=125*60*60, sleep_delay=210)

if i use that:
  bot.unfollow_users(amount=5, instapy_followed_enabled=True, instapy_followed_param="all" , style="FIFO", unfollow_after=125*60*60, sleep_delay=190)

error don't exist

**Comment by elulcao** [comment]
Hello 

Working on it,
it seems that there is a reference that is missing one argument, 
but it is only seen when using `nonfollowers`

**Comment by Tolmino** [comment]
there is something i can do for help you to debug ?

**Comment by krcha** [comment]
Yup i have same issue 

`Sorry, an error occurred: get_nonfollowers() missing 1 required positional argument: 'logfolder'`

on simple command

`    session.unfollow_users(amount=126, nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)`
