### ISSUE TITLE
Is it possible to add the function "Dislike"?

### ISSUE THREAD

**Issue by tobeyond** [InstaPy/InstaPy#5919]
## Expected Behavior

Instapy is very complete and easy to use. However, it would be very usefull to have the option to dislike the media after a while (the same way it is possible to unfollow).

Is it possible to add this feature?

**Comment by ghost** [comment]
It would probably just increase your server calls on your account so there's no point

More chance of getting banned for no real benefit

Also, it's an unlike not a dislike lol

**Comment by tobeyond** [comment]
Well, it would be useful to have this option anyway.
