### ISSUE TITLE
Problems with unfollow and images already liked

### ISSUE THREAD

**Issue by insta783** [InstaPy/InstaPy#5921]
yes
 no
## Expected Behavior
I expect the script unfollow after an amount of time and that it doesn't try to like images already liked
## Current Behavior
- Unfortunately if I leave the script running after some hours it closes or remains running but if I see in the command line it doens't go ahead. It's like stopped.
- It doesn't unfollow users. It likes pictures, comments and follow, but doesn't unfollow.
- It tries to process and like imaged already liked and fails.
## Possible Solution (optional)
What can I do to adjust these problems?
Consider that I don't use a server but my personal computer to run the script. If I leave running for some hours, then I shut down and then again I run the script, are there any problems (eg recognization about when unfollow instapy follower)?
Thanks

## InstaPy configuration
# !/usr/bin/python2.7
import random
from instapy import InstaPy
from instapy import smart_run

# get a session!
session = InstaPy(username='xxx', password='xxx', headless_browser=False)

# let's go! :>
with smart_run(session):
    hashtags = ['...', '...', '...']
    random.shuffle(hashtags)
    my_hashtags = hashtags[:10]

    # general settings
    session.set_ignore_if_contains(['....', '...', '...')
    session.set_dont_like(['...', '...', '...'])
    session.set_do_follow(enabled=True, percentage=60, times=1)
    session.set_do_comment(enabled=True, percentage=35)
    session.set_comments(['...', '...', '...'],
                         media='Photo')
    session.set_do_like(True, percentage=70)
    session.set_delimit_liking(enabled=True, max_likes=200, min_likes=0)
    session.set_delimit_commenting(enabled=True, max_comments=15, min_comments=0)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=8000,
                                    max_following=4000,
                                    min_followers=30,
                                    min_following=50)

    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "follows"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes_hourly=25,
                                 peak_likes_daily=350,
                                 peak_comments_hourly=15,
                                 peak_comments_daily=100,
                                 peak_follows_hourly=15,
                                 peak_follows_daily=150,
                                 peak_unfollows_hourly=15,
                                 peak_unfollows_daily=150,
                                 peak_server_calls_hourly=None,
                                 peak_server_calls_daily=3500)

    session.set_user_interact(amount=5, randomize=True, percentage=50)

    # activity
    session.like_by_tags(my_hashtags, amount=30, media=None)
    session.unfollow_users(amount=100, instapy_followed_enabled=True, instapy_followed_param="nonfollowers",
                           style="FIFO",
                           unfollow_after=12 * 60 * 60, sleep_delay=501)
    session.unfollow_users(amount=100, instapy_followed_enabled=True, instapy_followed_param="all",
                           style="FIFO", unfollow_after=24 * 60 * 60,
                           sleep_delay=501)

**Comment by elulcao** [comment]
From Changelog, python2 was unsupported
Move to python3, 

```bash
## [0.5.0] - 2019-06-03

### Added

- Additional check for like block.

### Changed

- Remove support for python2
- Information regarding the nogui parameter in documentation.
- XPath Isolation
- Remove redundant assignment of pod_post_ids
- Remove address var assigned multiple times without intermediate usage
- `set_mandatory_language` can maintain multiple character sets
- Feature finetuning comments for pods
``

**Comment by insta783** [comment]
I already have this version.
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32

**Comment by elulcao** [comment]
your description says

```
InstaPy configuration

!/usr/bin/python2.7
```

**Comment by insta783** [comment]
You are right! there is a mistake in the script...
However the Phyton version is 3.8.2
