### ISSUE TITLE
File is not a zip file

### ISSUE THREAD

**Issue by sephml** [InstaPy/InstaPy#5927]
Hi I get this error using instaPy for the first time and I've read an issue telling that since i haven't had any activities the following error occurs, please help me solve this thing?

issue ive read:
  [(https://github.com/timgrossmann/InstaPy/issues/5023)]
or #5023
the error i get:
Traceback (most recent call last):
  File "C:/Users/User/Desktop/insta crawler/main.py", line 49, in <module>
    headless_browser=False)
  File "C:\python3.7\lib\site-packages\instapy\instapy.py", line 335, in __init__
    geckodriver_log_level,
  File "C:\python3.7\lib\site-packages\instapy\browser.py", line 131, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "C:\python3.7\lib\site-packages\instapy\browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "C:\python3.7\lib\site-packages\webdriverdownloader\webdriverdownloader.py", line 195, in download_and_install
    with zipfile.ZipFile(os.path.join(self.get_download_path(version), filename), mode="r") as driver_zipfile:
  File "C:\python3.7\lib\zipfile.py", line 1225, in __init__
    self._RealGetContents()
  File "C:\python3.7\lib\zipfile.py", line 1292, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by elulcao** [comment]
are you using `geckodriver_log_level`?
how did you construct the session?

```python
# ie:
session = InstaPy(
    username="internet",
    password="internet",
    geckodriver_log_level="info",
    headless_browser=True,
)
```

**Comment by aminian-sepehr** [comment]
i left that flag untouched is that the problem?

**Comment by sephml** [comment]
> are you using `geckodriver_log_level`?
> how did you construct the session?
> 
> ```python
> # ie:
> session = InstaPy(
>     username="internet",
>     password="internet",
>     geckodriver_log_level="info",
>     headless_browser=True,
> )
> ```

i left that flag untouched is that the problem?

**Comment by elulcao** [comment]
I don't think so, could you check ifthis template works for you

```python
""" Quickstart script for InstaPy usage """

# imports
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

# set workspace folder at desired location (default is at your home folder)
set_workspace(path=None)

# get an InstaPy session!
session = InstaPy(username="internet", password="internet", )

with smart_run(session):
    # general settings
    session.set_dont_include(["friend1", "friend2", "friend3"])

    # activity
    session.like_by_tags(["natgeo"], amount=1)
```

`geckodriver_log_level ` is optional, you can remove it
