### ISSUE TITLE
ModuleNotFoundError: No module named 'pyvirtualdisplay'

### ISSUE THREAD

**Issue by preenupaul** [InstaPy/InstaPy#593]
ModuleNotFoundError: No module named 'pyvirtualdisplay'
i am new here. when i start this error message comes all time.
please help.
my system is Windos 10. intel i3. HP laptop

**Comment by westondeboer** [comment]
Hi @preenupaul 

I would try this solution and see if it works:
https://github.com/timgrossmann/InstaPy/issues/10#issuecomment-306996077

Hope that helps

**Comment by preenupaul** [comment]
but my python version is 3.6.2 it is the latest

**Comment by iSimonWeb** [comment]
@preenupaul how are you launching your script?
Here, from the official Python Docs, seems that on Windows you should use `py -3 yourscript.py` to correctly use the latest version (if there's any other in your system) --> [Python docs #launcher](https://docs.python.org/3.3/using/windows.html#launcher)

Also, have you installed `pyvirtualdisplay`?

**Comment by randysinnott** [comment]
@preenupaul I was having the same issue because I have python 2 installed side-by-side with python3.  Try running with python3 your_script.py instead.

**Comment by converge** [comment]
@preenupaul did you fix it ? can we close it ?
