### ISSUE TITLE
Instapy 0.6.12 "Couldn't find liked counter button"

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5933]
## Expected Behavior
Follow users
## Current Behavior
"Couldn't find liked counter button - May be a video **(it's not a video)** -  Move on"
## Tried Solutions
I tried zooming out in web browser so Instagram shows desktop site as well as zooming in so it shows mobile version
Does anyone know if this an issue with 0.6.12 (this is the latest version) particularity and downgrading would fix it?
## InstaPy configuration
    users = ['x', 'y', 'z']
    random.shuffle(users)
    my_users = users[:1]
    session.follow_likers(my_users, photos_grab_amount = 3, follow_likers_per_photo = 12, randomize=False, sleep_delay=600, interact=False)

TIA

**Comment by elulcao** [comment]
This is because the target post is actually a video or media from which cannot get likers,
if the likers/viewers button is clicked the same number is displayed in a floating window.
However, if the same button is clicked, lets say in a photo, a new pane is rendered
with a list of users; the likers from photo. 

`"Couldn't find liked counter button - May be a video (it's not a video) - Move on"`
Can you share the link for the post?

**Comment by ghost** [comment]
Thanks for your reply.

It happens on every post (otherwise I wouldn't have posted this if it only happened once)

I can see that the post is a picture not a video

**Comment by elulcao** [comment]
Without traces it is hard to debug. In my local I saw the message but 
this is because the post is not a photo. 

```python
   9 INFO [2020-11-29 21:30:35] [internet]  Got 24 , returning 5 links: ['https://www.instagram.com/p/CIGVDWrJ/', 'https://www.instagram.com/p/CIGVDWrJ/', '     https://www.instagram.com/p/CIGVDWrJ/', 'https://www.instagram.com/p/CIGVDWrJ/', 'https://www.instagram.com/p/CIGVDWrJ/']
   8 INFO [2020-11-29 21:31:30] [internet]  Couldn't find liked counter button. May be a video.
   7 INFO [2020-11-29 21:31:30] [internet]  Trying again for some image, moving on...
```

**Comment by ghost** [comment]
Huh. Weird cuz I thought this would be a widespread issue. 
Yours says "Trying again for some image, moving on" while mine says "May be a video \n Move on"
What verison of instapy are you using?

**Comment by elulcao** [comment]
Hi @Ardy000 
is the same 0.6.12, but with latest changes. Try to pull the latests commits.
Notice that the message is almost the same, but now is displaying a little extra message.

**Comment by ghost** [comment]
Thanks. How do I pull the latest commits. Never done that before. I've just installed stuff with pip3

**Comment by elulcao** [comment]
I see, well in that case the steps are different 
Current version installed by pip must be 0.6.12, since this is the latest published. However, 
here in GiHub the code is the source of thru, and the changes are only published to pip installer 
until a new version is pushed by the Owner; next one will be 0.6.13. 

You must have this in your machine, ` lib/python*/site-packages/instapy/commenters_util.py`:
```bash
$ sed -n '334,338p' commenters_util.py
        else:
            print("Couldn't find liked counter button. May be a video.")
            print("Moving on..")
            return []
```

```bash
# Uninstall current instapy
$ pip3 uninstall instapy

# Install latest commit with pip
$  pip3 install -U https://github.com/timgrossmann/InstaPy/archive/master.zip

Collecting https://github.com/timgrossmann/InstaPy/archive/master.zip
  Using cached https://github.com/timgrossmann/InstaPy/archive/master.zip
Requirement already satisfied: certifi>=2018.10.15 in ./venv_test/lib/python3.8/site-packages (from instapy==0.6.12) (2020.11.8)
Requirement already satisfied: chardet>=3.0.4 in ./venv_test/lib/python3.8/site-packages (from instapy==0.6.12) (3.0.4)
Requirement already satisfied: clarifai>=2.4.1 in ./venv_test/lib/python3.8/site-packages (from instapy==0.6.12) (2.6.2)
...
```

Now, the code must be the latest commit
```bash
 sed -n '355,365p' commenters_util.py
            # If you are here, it is because you discovered that sometimes an
            # xpath does not work, at the moment the number of views in a video
            # does not behave like the number of likes in a photo. Clicking on
            # the number of views only shows the same number in a floating
            # window; no users to get.
            # www.instagram.com/p/CASprIDgOOO/ -> 3,275,561 views -> 11-24-20
            logger.info("Couldn't find liked counter button. May be a video.")
            logger.info("Trying again for some image, moving on...")
            return []

        sleep(1)
```

**Comment by julianofnascimento** [comment]
same issue here.

**Comment by ghost** [comment]
Thanks elulcao!

I will give this a try. 

Kind of worried to do it since it took so long for me to install instapy in a way that it actually worked haha.

Am I understanding this correctly?

**The latest version of instapy on github is newer than the latest version of instapy that pip3 will install.**

So I could also just wait for 0.6.13 to be released and then continue with pip3 update and that will do the same thing?

**Comment by ghost** [comment]
julianofnascimento, did doing this:

```
# Uninstall current instapy
$ pip3 uninstall instapy

# Install latest commit with pip
$  pip3 install -U https://github.com/timgrossmann/InstaPy/archive/master.zip
```

fix your issue?

**Comment by elulcao** [comment]
To use the latest commit from git via pip:

```python
python -m pip install git+https://github.com/timgrossmann/InstaPy.git@b6106ade39d42738b5af8060fe7cdf62d4e72224
```

**Comment by julianofnascimento** [comment]
I actually had to change the xpath to the liker counter button manually in the code. But it worked!

**Comment by ghost** [comment]
Elulcao,

Updating instapy using that fixed the issue. I didn't have to manually change the path to the liker in the code.

Thanks all!

**Comment by Tr1pke** [comment]
and when will the new instapy be available on the pip3 ?

**Comment by ghost** [comment]
I tried this from the official documentation but it didn't work

`pip3 install -I https://github.com/timgrossmann/InstaPy/zipball/master`

I tried this and it worked

`pip3 install git+https://github.com/timgrossmann/InstaPy.git@b6106ade39d42738b5af8060fe7cdf62d4e72224 `

My question is, does this get you the latest version always or just this latest version?

**Comment by elulcao** [comment]
You need to check the latest commit from GitHub,

**Comment by ghost** [comment]
How do I find what to put inside the `** **` so I can get the latest version in the future

`pip3 install git+https://github.com/timgrossmann/InstaPy.git@**b6106ade39d42738b5af8060fe7cdf62d4e72224**`

**Comment by Tr1pke** [comment]
Is pip3 install instapy -U not working anymore?

**Comment by ghost** [comment]
It does. The latest github version is not always released to pip however
