### ISSUE TITLE
Comment on already liked photos not working using interact_by_URL

### ISSUE THREAD

**Issue by sokratis1988** [InstaPy/InstaPy#5936]
## Expected Behavior
Add comment to already liked photos using `interact_by_URL`

## Current Behavior
commenting of already liked photos not possible

## Possible Solution (optional)
Allow commenting of already liked photos

## InstaPy configuration
```python
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = ''
insta_password = ''

comments = ['hello @friend1']

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    session.set_do_like(enabled=True, percentage=100)
    session.set_do_comment(enabled=True, percentage=100)
    session.set_comments(comments)
    session.set_do_follow(enabled=True, percentage=100)
    #session.set_user_interact(amount=6, randomize=False, percentage=100)

    #session.follow_by_list(followlist=['instagram'], times=1, sleep_delay=600, interact=False)

    #session.set_user_interact(amount=10, randomize=True,percentage=100)

    # start the feature
    session.interact_by_URL(urls=["abcdefg"], randomize=True, interact=True)
```

**Comment by n1h4x** [comment]
Hello, I also have the same issue. Could the developers shed some light on this one? Thanks :D

**Comment by trevtravtrev** [comment]
I noticed in the source code that it first checks if the post has already been liked but the comment function is an indented if statement under that. So, if the post has already been liked it skips the comment function. The comment function should be removed from under the if liked and placed in its own if statement.

**Comment by sokratis1988** [comment]
@trevtravtrev Can you share the file an line number of this code?

**Comment by trevtravtrev** [comment]
@sokratis1988 im currently on mobile but I noticed this a few weeks back for almost every function that allows the commenting feature.

interact_by_user was the first one I noticed.

**Comment by elulcao** [comment]
Commenting liked photos could be detected like an automated action,
it could be the case that the bot is commenting several times the same photo, 
then other users will report that the bot is commenting the same photo 
twice or more.
For now the comment occurs after liked an image, like a normal user usually do.

**Comment by sokratis1988** [comment]
@elulcao 
Hey, did you push a new version that fixes this issue?

**Comment by elulcao** [comment]
@sokratis1988 
Nop, is the same version from `pip install instapy`
I used the same template shared in this issue.

```python
python 5936.py
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Custom workspace set: "/Users/internet/GitHub/InstaPy_Info" :]
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/Users/internet/GitHub/InstaPy_Info"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-12-06 13:34:09] [internet]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-12-06 13:34:09] [internet]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-12-06 13:34:09] [internet]  - Internet Connection Status: ok
INFO [2020-12-06 13:34:09] [internet]  - Current IP is "0.0.0.0" and it's from "AC/DC"
INFO [2020-12-06 13:34:09] [internet]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-12-06 13:34:09] [internet]  - window.navigator.webdriver response: None
INFO [2020-12-06 13:34:09] [internet]  - Hide Selenium Extension: ok
...................................................................
INFO [2020-12-06 13:34:26] [internet]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2020-12-06 13:34:26] [internet]  Saving account progress...
________________________________________________________________________________
INFO [2020-12-06 13:34:42] [internet]  Starting to interact by given URLs..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2020-12-06 13:34:42] [internet]  URL [1/3]
INFO [2020-12-06 13:34:42] [internet]  --> b'https://www.instagram.com/p/CIEdTolwk9/'
INFO [2020-12-06 13:34:46] [internet]  Image from: b'user'
INFO [2020-12-06 13:34:46] [internet]  Link: b'https://www.instagram.com/p/CIEdTolwk9/'
INFO [2020-12-06 13:34:46] [internet]  Description: b'Buen d\xc3\xada chic@s'
INFO [2020-12-06 13:35:47] [internet]  --> Image liked!
INFO [2020-12-06 13:36:08] [internet]  --> Commented: b'Hope you see this comment, thanks for sharing !!! '
^C
```

links looks like

```python
11 links = [
12     "https://www.instagram.com/p/CIEdTolwk9/",
13     "https://www.instagram.com/p/CIEdTolwk9g_Aq/",
14     "CIBodH12o",  # https://www.instagram.com/p/CIBodH12o/
15 ]
```

**Comment by sokratis1988** [comment]
You didnt change anything and your script is commenting photos you already liked? @elulcao

**Comment by elulcao** [comment]
correct, is the same, well I just added the `set_workspace` but it doesn't affect the workflow. 
here is the template, just in case.

```python
1  # imports
 1 from instapy import InstaPy
 2 from instapy import smart_run
 3 from instapy import set_workspace
 4
 5 set_workspace(path="/Users/internet/GitHub/InstaPy_Info")
 6
 7 # login credentials
 8 insta_username = "internet"
 9 insta_password = "nibvew-dusru4"
10 comments = ["Hope you see this comment, thanks for sharing !!! "]
11 links = [
12     "https://www.instagram.com/p/CIEdTolwk9/",
13     "https://www.instagram.com/p/CIEdTolwk9_Aq/",
14     "CIBodH12o",  # https://www.instagram.com/p/CIBodH12o/
15 ]
16
17 session = InstaPy(
18     username=insta_username,
19     password=insta_password,
20     geckodriver_log_level="trace",
21     headless_browser=False,
22 )
23
24 with smart_run(session):
25     """ Activity flow """
26     session.set_do_like(enabled=True, percentage=100)
27     session.set_do_comment(enabled=True, percentage=100)
28     session.set_comments(comments)
29     session.set_do_follow(enabled=True, percentage=100)
30     # session.set_user_interact(amount=6, randomize=False, percentage=100)
31     # session.follow_by_list(followlist=['instagram'], times=1, sleep_delay=600, interact=False)
32     # session.set_user_interact(amount=10, randomize=True,percentage=100)
33
34     # start the feature
35     session.interact_by_URL(urls=links, randomize=True, interact=True)
```

**Comment by elulcao** [comment]
@sokratis1988 
The code is commenting a photo after liked, in the same execution,
if a photo is already liked it would be skipped for comments.

Commenting a photo that is already liked sounds more like a new feature,
some extra verifications for previous comments will be needed to avoid 
double comments.

**Comment by n1h4x** [comment]
why was this issue closed since it was not resolved? 
The code still comments only on "not already like" photos.

Can you make the "new feature" available through some "if" statement? Ideally, a flag can let the executor decide whether to comment on already liked photos or not.

This will not be recognized as automated tool in case of instagram competitions that require multiple comments of the same context.

**Comment by elulcao** [comment]
> why was this issue closed since it was not resolved? 
> 
> The code still comments only on "not already like" photos.
> 
> 
> 
> Can you make the "new feature" available through some "if" statement? Ideally, a flag can let the executor decide whether to comment on already liked photos or not.
> 
> 
> 
> This will not be recognized as automated tool in case of instagram competitions that require multiple comments of the same context.

Sounds good, let's see how many people are interested in this new feature. In the meantime you could explain at detail your idea, so other users will also evaluate based on your feedback. 
Then, it will be implemented if there are enough "real" users interested into this new feature.

**Comment by n1h4x** [comment]
i am not experienced with programming and just briefly took a look in the code. 

Where the commenting functionality is implemented, could there be a "liked" flag (boolean argument) that is provided upon execution, then the program could check this boolean argument and if "TRUE" it could comment even though the photo is already liked, if "FALSE" it could skip it.

I guess you know your code more and could determine where these "if" conditions could be put in order to check the provided argument.

Was this helpful??

**Comment by elulcao** [comment]
An extra flag seems to be not mandatory, this feature needs to be transparent
to the InstaPy useir. I mean, thats the intention of the bot, automating the
interacion with others; let's say to save time ;)
It could be something like the following:

* Pick a photo.
    * If the photo is not liked
        * Like the photo, if the criteria are met
        * Comment the photo, if the criteria are met
* If the photo is already liked
    * Search for our previous comment
        * If our comment exist, move to next photo since commenting twice look suspicius.
        * If we didn't comment the photo, time to share our words

**Comment by JulioFig** [comment]
if you downloaded with `pip3 install instapy` you can go to where it was installed and change the like_util.py file line 822  to `return True, "already liked"`
