### ISSUE TITLE
Question about amount in follow_user_followers

### ISSUE THREAD

**Issue by thibautflottat** [InstaPy/InstaPy#5937]
Hello !

It is not an issue strictly speaking, but I looked around here (documentation, discord, other issues) and i cannot find a solution. I am trying to construct a more consistent bot but I am facing a problem.

Let's say I want to follow user follower using `follow_user_followers('user', amount=50, randomize=True, interact=True)`. It randomly selects 50 followers of 'user'. Then this list is filtered according parameters I fixed in `set_relationship_bounds`. So it won't follow 50 users, but less (sometimes the filtered list is empty).

How to make follow_user_followers stops when the amount of 50 I fixed is reached ?

Thank you !

**Comment by elulcao** [comment]
`def follow_user_followers()` should stop once `self.quotient_breach` is reached. 
you would check if the limits can be relaxed or hardened.

```python
  30             for index, person in enumerate(person_list):
  31                 if self.quotient_breach:
  32                     self.logger.warning(
  33                         "--> Follow quotient reached its peak!"
  34                         "\t~leaving Follow-User-Followers activity\n"
  35                     )
  36                     break
  37
```
