### ISSUE TITLE
possible posts: 0

### ISSUE THREAD

**Issue by blue-tomato6** [InstaPy/InstaPy#5942]
Getting `possible posts: 0`, using a simplified [quickstart](https://github.com/InstaPy/instapy-quickstart). Similar to [#2358](https://github.com/timgrossmann/InstaPy/issues/2358). 

Changing `skip_top_posts` doesn't help either. 

Can you still like by tags?

<img width="746" alt="Screen Shh" src="https://user-images.githubusercontent.com/75656359/101442243-c934d280-38cf-11eb-92cb-63bbd459ffbd.png">

**Comment by sanzgiri** [comment]
I am running into the same issue.

**Comment by elulcao** [comment]
Which template from quickstart is the one you used?
Share the gecko log, with trace level.
describe at detail your configuration.

**Comment by sanzgiri** [comment]
@elulcao - This suddenly started working for me again on 12/11. The template I am using is https://github.com/InstaPy/instapy-quickstart/blob/master/quickstart_templates/simple_but_effective.py

I started by setting `skip_top_posts=False` in like_by_tags() and that seemed to work, and after I change the flag back to True, it still worked :-)

**Comment by blue-tomato6** [comment]
Works for me as well, closing this issue.
