### ISSUE TITLE
Not a valid user: ---> Sorry, couldn't get get user bio account active

### ISSUE THREAD

**Issue by sertchan** [InstaPy/InstaPy#5944]
Pls help  fix this
Code:
session.login()
session.set_action_delays(enabled=True,
                           like=1,
                           comment=2,
                           follow=2,
                           unfollow=2,
                           story=5)
session.set_skip_users(skip_private=False,
                       private_percentage=100,
                       skip_no_profile_pic=False,
                       no_profile_pic_percentage=100,
                       skip_business=False,
                       skip_non_business=False,
                       business_percentage=100,
                       skip_business_categories=[],
                       dont_skip_business_categories=[],
                       skip_bio_keyword=["fenerbahçe"],
                       mandatory_bio_keywords=["pfl" , "ptfl"])
session.set_user_interact(amount=2,
                 percentage=70,
                  randomize=True,
                   media='Photo')
session.follow_likers(['_'], photos_grab_amount = 5, follow_likers_per_photo = 5, randomize=True, sleep_delay=3, interact=False)

session.end()
Error: Sorry, couldn't get get user bio account active

**Comment by elulcao** [comment]
@Ardaseyhan 
could you try the following in your local, 

in `util.py` search this line: `if len(skip_bio_keyword) > 0 or len(mandatory_bio_keywords) > 0:`
and append the following:

```python
# Navigate to the user profile to read the Bio
        user_link = "https://www.instagram.com/{}/".format(username)
        web_address_navigator(browser, user_link)
```

**Comment by sertchan** [comment]
![capture](https://user-images.githubusercontent.com/53477192/102017464-26b99b00-3d78-11eb-827a-ddf11127d3e5.PNG)
 @elulcao  is this how i should do

**Comment by elulcao** [comment]
@Ardaseyhan 
Correct, that's it.
With that change, the bot will navigate to the target profile to read the bio. 


```python
# line number could be different in your local, 
433      if len(skip_bio_keyword) > 0 or len(mandatory_bio_keywords) > 0:
   1         # Navigate to the target user profile to read the Bio
   2         user_link = "https://www.instagram.com/{}/".format(username)
   3         web_address_navigator(browser, user_link)
   4
   5         # if contain stop words then skip
   6         try:
```

**Comment by sertchan** [comment]
thx  , you fixed this problem <3
