### ISSUE TITLE
Freezes on GraphQL query hash: [c76146de99bb02f6415203be841dd25a]

### ISSUE THREAD

**Issue by WillianSalceda** [InstaPy/InstaPy#5945]
It just freezes the BOT until the CMD closes (after ~12 minutes). I noticed that the Firefox browser refreshes every ~5 seconds. By the way, i am currently using InstaPy GUI, because with only the InstaPy, even though using any QuickStart default configuration, it doesn't work. And of course, it's all up to date.

## InstaPy configuration
```

"""
This template is written by @Nuzzo235

What does this quickstart script aim to do?
- This script is targeting followers of similar accounts and influencers.
- This is my starting point for a conservative approach: Interact with the
audience of influencers in your niche with the help of 'Target-Lists' and
'randomization'.

NOTES:
- For the ease of use most of the relevant data is retrieved in the upper part.
"""

import random
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'x'
insta_password = 'y'

# restriction data
dont_likes = ['#exactmatch', '[startswith', ']endswith', 'broadmatch']
# completely ignore liking images from certain users
ignore_users = ['user1', 'user2', 'user3']

""" Prevent commenting on and unfollowing your good friends (the images will 
still be liked)...
"""
friends = ['friend1', 'friend2', 'friend3']

""" Prevent posts that contain...
"""
ignore_list = ['Fashion', 'Logotipo', 'Tratamento corporais', 'Descubra lugares', 'Personalizado', 'Agilidade na entrega', 'Acessórios em geral', 'Fashion Designer', 'Jewerly Designer', 'God Bless', 'god bless', 'Um novo conceito em', 'Burguer Delivery', 'Fique em casa, e chame a gente!', 'Pedidos, clique', 'Cores de Esmaltes', 'Esmaltes']

# TARGET data
""" Set similar accounts and influencers from your niche to target...
"""
targets = ['pratafina', 'marcelampc', 'ceudepratas', 'ceuprata', 'aneisemprata', 'damadepratajoias', 'usemiaa']

""" Skip all business accounts, except from list given...
"""
target_business_categories = ['category1', 'category2', 'category3']

# COMMENT data
"""comments = ['Nice shot! @{}',
        'I love your profile! @{}',
        'Your feed is an inspiration :thumbsup:',
        'Just incredible :open_mouth:',
        'What camera did you use @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Getting inspired by you @{}',
        ':raised_hands: Yes!',
        'I can feel your passion @{} :muscle:']"""

# get a session!
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  disable_image_load=True,
                  multi_logs=True,
                  bypass_security_challenge_using='sms'
                  )

# let's go! :>
with smart_run(session):
    # HEY HO LETS GO
    
    # don't like if a post already has more than 150 likes
    session.set_delimit_liking(enabled=True, max_likes=800, min_likes=0)
    
    # general settings
    session.set_dont_include(friends)
    session.set_dont_like(dont_likes)
    session.set_ignore_if_contains(ignore_list)
    session.set_ignore_users(ignore_users)
    session.set_simulation(enabled=True)
    
    """I used to have potency_ratio=-0.85 and max_followers=1200 for 
    set_relationship_bounds()
        Having a stricter relationship bound to target only low profiles 
        users was not very useful,
        as interactions/sever calls ratio was very low. I would reach the 
        server call threshold for
        the day before even crossing half of the presumed safe limits for 
        likes, follow and comments (yes,
        looks like quiet a lot of big(bot) managed accounts out there!!).
        So I relaxed it a bit to -0.50 and 2000 respectively.
    """
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=-0.65,
                                    delimit_by_numbers=True,
                                    max_followers=10000,
                                    max_following=4000,
                                    min_followers=25,
                                    min_following=25,
                                    min_posts=3)

    session.set_skip_users(skip_private=True,
                           skip_no_profile_pic=True,
                           skip_business=True,
                           dont_skip_business_categories=[
                               target_business_categories])

    session.set_user_interact(amount=3, randomize=True, percentage=80,
                              media='Photo')
    session.set_do_like(enabled=True, percentage=90)
    session.set_do_comment(enabled=False, percentage=15)
    #session.set_comments(comments, media='Photo')
    session.set_do_follow(enabled=True, percentage=40, times=1)
    
    
    session.set_quota_supervisor(enabled=True,
                                 # Notice: there can be either "likes" (for both hourly and daily sleep) OR "likes_h" (for hourly sleep only) OR "likes_d" (for daily sleep only).
                                 sleep_after=["likes", "follows", "unfollows", "server_calls_h"],
                                 sleepyhead=True, stochastic_flow=True, notify_me=True,
                                 peak_likes_hourly=57,
                                 peak_likes_daily=585,
                                 
                                 peak_follows_hourly=48,
                                 peak_follows_daily=600,

                                 peak_unfollows_hourly=35,
                                 peak_unfollows_daily=402,
                                 
                                 peak_server_calls_hourly=None,
                                 peak_server_calls_daily=4000)

    # activities
    # FOLLOW+INTERACTION on TARGETED accounts
    """ Select users form a list of a predefined targets...
    """
    number = random.randint(3, 5)
    random_targets = targets

    if len(targets) <= number:
        random_targets = targets

    else:
        random_targets = random.sample(targets, number)

    """ Interact with the chosen targets...
    """
    session.follow_user_followers(random_targets,
                                  amount=random.randint(30, 60),
                                  randomize=True, sleep_delay=600,
                                  interact=True)

    # UNFOLLOW activity
    """ Unfollow nonfollowers after one day...
    """
    session.unfollow_users(amount=random.randint(75, 100),
                           nonFollowers=True,
                           style="FIFO",
                           unfollow_after= 2 * 24 * 60 * 60, sleep_delay=600)

    """ Unfollow all users followed by InstaPy after one week to keep the 
    following-level clean...
    """
    session.unfollow_users(amount=random.randint(75, 100),
                           allFollowing=True,
                           style="FIFO",
                           unfollow_after= 7 * 24 * 60 * 60, sleep_delay=600)

    """ Joining Engagement Pods...
    """
    #session.join_pods()

"""
Have fun while optimizing for your purposes, Nuzzo
"""
```

**Comment by elulcao** [comment]
Not sure if you are running latest from `pip` or `git`
in my case latest from `git` is running fine; I used the template 
you shared.
Same query was done successfully and users were extracted from IG


```python
 python 5945.py
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Custom workspace set: "/Users/internet/GitHub/InstaPy_Info" :]
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/Users/internet/GitHub/InstaPy_Info"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-12-08 22:16:56] [internet]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-12-08 22:16:56] [internet]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-12-08 22:16:57] [internet]  - Internet Connection Status: ok
INFO [2020-12-08 22:16:57] [internet]  - Current IP is "0.0.0.0" and it's from "AC/DC"
INFO [2020-12-08 22:16:57] [internet]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-12-08 22:16:57] [internet]  - window.navigator.webdriver response: None
INFO [2020-12-08 22:16:57] [internet]  - Hide Selenium Extension: ok
INFO [2020-12-08 22:16:59] [internet]  - Cookie file for user 'internet' loaded...
...................................................................
INFO [2020-12-08 22:17:18] [internet]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2020-12-08 22:17:18] [internet]  Saving account progress...
_________________________________________________________________________________
INFO [2020-12-08 22:17:33] [internet]  Starting to follow user `Followers`..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2020-12-08 22:17:33] [internet]  User 'pratafina' [1/5]
INFO [2020-12-08 22:17:41] [internet]  GraphQL query hash: [c76146de99bb02f6415203be841dd25a]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [1/38/jessica_pbraga]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [2/38/gabriela_heinz]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [3/38/brunazander5]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [4/38/yris_7]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [5/38/nicolecarvalho89]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [6/38/nathieleamorim]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [7/38/rosanestupp]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [8/38/victoria_barbosa_f]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [9/38/polianaaoliveira_]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [10/38/lamargarida]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [11/38/vanessaarcanjo.g]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [12/38/gabrielurban_]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [13/38/lusambate]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [14/38/analima.02]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [15/38/roseavii.la]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [16/38/grazibarrosalves]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [17/38/liliankachinski]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [18/38/diix.kaah_moraiis]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [19/38/josianespassos]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [20/38/cleiaazeredo]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [21/38/naatielioliveira]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [22/38/lucianadias8913]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [23/38/marciasonia10]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [24/38/izabella.mont]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [25/38/isaiascarpes]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [26/38/flaviapratas]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [27/38/noiacitytattoo]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [28/38/rodrigo_fio]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [29/38/kauanrosa3002]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [30/38/nataliaa.antoniak]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [31/38/marianafarmaesteta]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [32/38/overdale069]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [33/38/casamaisvoce]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [34/38/18_5781_jamih]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [35/38/taimararossetto]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [36/38/roselar.gomes]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [37/38/zelazowski_dudaa]
INFO [2020-12-08 22:17:51] [internet]  To be followed: [38/38/hellenmarianeliz]

INFO [2020-12-08 22:17:51] [internet]  Grabbed 38 usernames from 'pratafina's `Followers` to do following

INFO [2020-12-08 22:17:51] [internet]  Ongoing Follow [1/38]: now following 'jessica_pbraga'...
INFO [2020-12-08 22:17:54] [internet]  User: 'jessica_pbraga'  |> followers: 256  |> following: 408  |> relationship ratio: 1.59
INFO [2020-12-08 22:17:54] [internet]  jessica_pbraga is private account, by default skip
```

**Comment by bho199** [comment]
Same Problem here. Installed with `pip`

**Comment by WillianSalceda** [comment]
> Not sure if you are running latest from `pip` or `git`
> in my case latest from `git` is running fine; I used the template
> you shared.
> Same query was done successfully and users were extracted from IG
> 
> ```python
>  python 5945.py
>  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
> Custom workspace set: "/Users/internet/GitHub/InstaPy_Info" :]
> InstaPy Version: 0.6.12
>  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
> Workspace in use: "/Users/internet/GitHub/InstaPy_Info"
> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> INFO [2020-12-08 22:16:56] [internet]  Session started!
> oooooooooooooooooooooooooooooooooooooooooooooooooooooo
> INFO [2020-12-08 22:16:56] [internet]  -- Connection Checklist [1/2] (Internet Connection Status)
> INFO [2020-12-08 22:16:57] [internet]  - Internet Connection Status: ok
> INFO [2020-12-08 22:16:57] [internet]  - Current IP is "0.0.0.0" and it's from "AC/DC"
> INFO [2020-12-08 22:16:57] [internet]  -- Connection Checklist [2/2] (Hide Selenium Extension)
> INFO [2020-12-08 22:16:57] [internet]  - window.navigator.webdriver response: None
> INFO [2020-12-08 22:16:57] [internet]  - Hide Selenium Extension: ok
> INFO [2020-12-08 22:16:59] [internet]  - Cookie file for user 'internet' loaded...
> ...................................................................
> INFO [2020-12-08 22:17:18] [internet]  Logged in successfully!
> '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
> INFO [2020-12-08 22:17:18] [internet]  Saving account progress...
> _________________________________________________________________________________
> INFO [2020-12-08 22:17:33] [internet]  Starting to follow user `Followers`..
> """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> INFO [2020-12-08 22:17:33] [internet]  User 'pratafina' [1/5]
> INFO [2020-12-08 22:17:41] [internet]  GraphQL query hash: [c76146de99bb02f6415203be841dd25a]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [1/38/jessica_pbraga]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [2/38/gabriela_heinz]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [3/38/brunazander5]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [4/38/yris_7]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [5/38/nicolecarvalho89]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [6/38/nathieleamorim]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [7/38/rosanestupp]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [8/38/victoria_barbosa_f]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [9/38/polianaaoliveira_]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [10/38/lamargarida]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [11/38/vanessaarcanjo.g]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [12/38/gabrielurban_]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [13/38/lusambate]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [14/38/analima.02]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [15/38/roseavii.la]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [16/38/grazibarrosalves]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [17/38/liliankachinski]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [18/38/diix.kaah_moraiis]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [19/38/josianespassos]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [20/38/cleiaazeredo]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [21/38/naatielioliveira]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [22/38/lucianadias8913]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [23/38/marciasonia10]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [24/38/izabella.mont]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [25/38/isaiascarpes]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [26/38/flaviapratas]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [27/38/noiacitytattoo]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [28/38/rodrigo_fio]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [29/38/kauanrosa3002]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [30/38/nataliaa.antoniak]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [31/38/marianafarmaesteta]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [32/38/overdale069]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [33/38/casamaisvoce]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [34/38/18_5781_jamih]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [35/38/taimararossetto]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [36/38/roselar.gomes]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [37/38/zelazowski_dudaa]
> INFO [2020-12-08 22:17:51] [internet]  To be followed: [38/38/hellenmarianeliz]
> 
> INFO [2020-12-08 22:17:51] [internet]  Grabbed 38 usernames from 'pratafina's `Followers` to do following
> 
> INFO [2020-12-08 22:17:51] [internet]  Ongoing Follow [1/38]: now following 'jessica_pbraga'...
> INFO [2020-12-08 22:17:54] [internet]  User: 'jessica_pbraga'  |> followers: 256  |> following: 408  |> relationship ratio: 1.59
> INFO [2020-12-08 22:17:54] [internet]  jessica_pbraga is private account, by default skip
> ```

I've been using pip install the whole time. I'll be trying use git now to test it

edit¹: Still the same just as before
edit²: After some time, i managed to run the same quickstart in a Ubuntu 20.10 virtual machine, and it came as no surprise to me, still freezing at the same spot.

**Comment by jasonpoonia** [comment]
I'm actually suffering from the same issue, a Hash is generated however the screen just keeps refreshing and nothing happens.

**Comment by AlokinVetob** [comment]
Same issue it gets tuck after it goes to GraphQL query hash: [c76146de99bb02f6415203be841dd25a] and doesnt continue after that need solution please ^^ ty in advance and all the best :)

**Comment by AlokinVetob** [comment]
Managed 2 do something opened a CMD then wrote pip install pip --upgrade then pip install instapy it updated some new files and now it seems 2 work

**Comment by WillianSalceda** [comment]
unfortunately, it didn't work here. It is all up to date already. Tried installing through pip and git, as well another operating system. The problem is that it doesn't even give an error or something.

> Managed 2 do something opened a CMD then wrote pip install pip --upgrade then pip install instapy it updated some new files and now it seems 2 work

**Comment by EORikki** [comment]
Try to delete or comment out line 820 in unfollow_util.py:
followers_list = []

Like was suggested in issue #5863 

This fixed the issue for me

**Comment by madwols** [comment]
> Try to delete or comment out line 820 in unfollow_util.py:
> followers_list = []
> 
> Like was suggested in issue #5863
> 
> This fixed the issue for me

didn't work for me

**Comment by ghost** [comment]
> It just freezes the BOT until the CMD closes (after ~12 minutes). I noticed that the Firefox browser refreshes every ~5 seconds. By the way, i am currently using InstaPy GUI, because with only the InstaPy, even though using any QuickStart default configuration, it doesn't work. And of course, it's all up to date.
> 
> ## InstaPy configuration
> ```
> 
> """
> This template is written by @Nuzzo235
> 
> What does this quickstart script aim to do?
> - This script is targeting followers of similar accounts and influencers.
> - This is my starting point for a conservative approach: Interact with the
> audience of influencers in your niche with the help of 'Target-Lists' and
> 'randomization'.
> 
> NOTES:
> - For the ease of use most of the relevant data is retrieved in the upper part.
> """
> 
> import random
> from instapy import InstaPy
> from instapy import smart_run
> 
> # login credentials
> insta_username = 'x'
> insta_password = 'y'
> 
> # restriction data
> dont_likes = ['#exactmatch', '[startswith', ']endswith', 'broadmatch']
> # completely ignore liking images from certain users
> ignore_users = ['user1', 'user2', 'user3']
> 
> """ Prevent commenting on and unfollowing your good friends (the images will 
> still be liked)...
> """
> friends = ['friend1', 'friend2', 'friend3']
> 
> """ Prevent posts that contain...
> """
> ignore_list = ['Fashion', 'Logotipo', 'Tratamento corporais', 'Descubra lugares', 'Personalizado', 'Agilidade na entrega', 'Acessórios em geral', 'Fashion Designer', 'Jewerly Designer', 'God Bless', 'god bless', 'Um novo conceito em', 'Burguer Delivery', 'Fique em casa, e chame a gente!', 'Pedidos, clique', 'Cores de Esmaltes', 'Esmaltes']
> 
> # TARGET data
> """ Set similar accounts and influencers from your niche to target...
> """
> targets = ['pratafina', 'marcelampc', 'ceudepratas', 'ceuprata', 'aneisemprata', 'damadepratajoias', 'usemiaa']
> 
> """ Skip all business accounts, except from list given...
> """
> target_business_categories = ['category1', 'category2', 'category3']
> 
> # COMMENT data
> """comments = ['Nice shot! @{}',
>         'I love your profile! @{}',
>         'Your feed is an inspiration :thumbsup:',
>         'Just incredible :open_mouth:',
>         'What camera did you use @{}?',
>         'Love your posts @{}',
>         'Looks awesome @{}',
>         'Getting inspired by you @{}',
>         ':raised_hands: Yes!',
>         'I can feel your passion @{} :muscle:']"""
> 
> # get a session!
> session = InstaPy(username=insta_username,
>                   password=insta_password,
>                   headless_browser=False,
>                   disable_image_load=True,
>                   multi_logs=True,
>                   bypass_security_challenge_using='sms'
>                   )
> 
> # let's go! :>
> with smart_run(session):
>     # HEY HO LETS GO
>     
>     # don't like if a post already has more than 150 likes
>     session.set_delimit_liking(enabled=True, max_likes=800, min_likes=0)
>     
>     # general settings
>     session.set_dont_include(friends)
>     session.set_dont_like(dont_likes)
>     session.set_ignore_if_contains(ignore_list)
>     session.set_ignore_users(ignore_users)
>     session.set_simulation(enabled=True)
>     
>     """I used to have potency_ratio=-0.85 and max_followers=1200 for 
>     set_relationship_bounds()
>         Having a stricter relationship bound to target only low profiles 
>         users was not very useful,
>         as interactions/sever calls ratio was very low. I would reach the 
>         server call threshold for
>         the day before even crossing half of the presumed safe limits for 
>         likes, follow and comments (yes,
>         looks like quiet a lot of big(bot) managed accounts out there!!).
>         So I relaxed it a bit to -0.50 and 2000 respectively.
>     """
>     session.set_relationship_bounds(enabled=True,
>                                     potency_ratio=-0.65,
>                                     delimit_by_numbers=True,
>                                     max_followers=10000,
>                                     max_following=4000,
>                                     min_followers=25,
>                                     min_following=25,
>                                     min_posts=3)
> 
>     session.set_skip_users(skip_private=True,
>                            skip_no_profile_pic=True,
>                            skip_business=True,
>                            dont_skip_business_categories=[
>                                target_business_categories])
> 
>     session.set_user_interact(amount=3, randomize=True, percentage=80,
>                               media='Photo')
>     session.set_do_like(enabled=True, percentage=90)
>     session.set_do_comment(enabled=False, percentage=15)
>     #session.set_comments(comments, media='Photo')
>     session.set_do_follow(enabled=True, percentage=40, times=1)
>     
>     
>     session.set_quota_supervisor(enabled=True,
>                                  # Notice: there can be either "likes" (for both hourly and daily sleep) OR "likes_h" (for hourly sleep only) OR "likes_d" (for daily sleep only).
>                                  sleep_after=["likes", "follows", "unfollows", "server_calls_h"],
>                                  sleepyhead=True, stochastic_flow=True, notify_me=True,
>                                  peak_likes_hourly=57,
>                                  peak_likes_daily=585,
>                                  
>                                  peak_follows_hourly=48,
>                                  peak_follows_daily=600,
> 
>                                  peak_unfollows_hourly=35,
>                                  peak_unfollows_daily=402,
>                                  
>                                  peak_server_calls_hourly=None,
>                                  peak_server_calls_daily=4000)
> 
>     # activities
>     # FOLLOW+INTERACTION on TARGETED accounts
>     """ Select users form a list of a predefined targets...
>     """
>     number = random.randint(3, 5)
>     random_targets = targets
> 
>     if len(targets) <= number:
>         random_targets = targets
> 
>     else:
>         random_targets = random.sample(targets, number)
> 
>     """ Interact with the chosen targets...
>     """
>     session.follow_user_followers(random_targets,
>                                   amount=random.randint(30, 60),
>                                   randomize=True, sleep_delay=600,
>                                   interact=True)
> 
>     # UNFOLLOW activity
>     """ Unfollow nonfollowers after one day...
>     """
>     session.unfollow_users(amount=random.randint(75, 100),
>                            nonFollowers=True,
>                            style="FIFO",
>                            unfollow_after= 2 * 24 * 60 * 60, sleep_delay=600)
> 
>     """ Unfollow all users followed by InstaPy after one week to keep the 
>     following-level clean...
>     """
>     session.unfollow_users(amount=random.randint(75, 100),
>                            allFollowing=True,
>                            style="FIFO",
>                            unfollow_after= 7 * 24 * 60 * 60, sleep_delay=600)
> 
>     """ Joining Engagement Pods...
>     """
>     #session.join_pods()
> 
> """
> Have fun while optimizing for your purposes, Nuzzo
> """
> ```

this template remove the problem of query hash?

**Comment by ghost** [comment]
> Managed 2 do something opened a CMD then wrote pip install pip --upgrade then pip install instapy it updated some new files and now it seems 2 work

did not work

**Comment by malarau** [comment]
Well, then update both and:

> Try to delete or comment out line 820 in unfollow_util.py:
> followers_list = []
> 
> Like was suggested in issue #5863
> 
> This fixed the issue for me

**Comment by solanav** [comment]
I tried upgrading pip, removing "followers_list = []" and downgrading the version and still not working.

**Comment by elulcao** [comment]
any volunteer to share the geckodriver.log with `trace` level, to debug further more.
btw, how to activate the trace level is in Documentation,

**Comment by yudhiesh** [comment]
Anyone able to fix this? I tried all the recommendations from the thread but still the same issue.
