### ISSUE TITLE
whenever i click on windows start in run folder it says "__main__" folder not found

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5950]

**Comment by ghost** [comment]
![Screenshot 2020-12-10 202950](https://user-images.githubusercontent.com/75793388/101809761-f1c20400-3b3d-11eb-8a4a-0ec88d88e75a.png)
this is the issue sir

**Comment by elulcao** [comment]
Could you check this stepes,
and set the paths for FF and the geckodriver

### Choose the browser version
If you have more than one Firefox version on your system or if you are using a portable version you can instruct InstaPy to use that version using the `browser_executable_path` argument in the class initializer.

Specifying the Firefox executable path can also help you if you are getting the following error message:

`selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`

Example on a Windows machine (with the right path also works on Linux and macOS)

```python
session = InstaPy(username=insta_username,
                  password=insta_password,
                  browser_executable_path=r"D:\Program Files\Mozilla Firefox\firefox.exe")
```


### Custom geckodriver
By default, InstaPy downloads the latest version of the geckodriver.
Unless you need a specific version of the geckodriver, you're ready to go.

You can manually download the geckodriver binary and put the path as an argument to the InstaPy contructor:

```python
session = InstaPy(..., geckodriver_path = '/path/to/binary', ...)
```
