### ISSUE TITLE
hello someone help me after login to my account it tooks to the target account but then it says "GRAPHQL QUERY HASH" in the command propt. what it actually means im tired of it please help me.

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5953]

**Comment by elulcao** [comment]
Use the template for the issue instead of saturating the subject field, 
it would be easier if you describe your problem in detail attaching the 
current system configuration.

**Comment by Abukevin** [comment]
I have the same problem as soon as the bot is supposed to follow subscribers of user x. error 'GraphQL query hash: [c76146en99bb02f6415203be841dd25a]' display

**Comment by venglov** [comment]
the same

**Comment by ghost** [comment]
> Use the template for the issue instead of saturating the subject field,
> it would be easier if you describe your problem in detail attaching the
> current system configuration.

look im new here i dont know anything about github i joined it just to fix the problem of "GraphQL query hashc 76146en99bb02f6415203be841dd25a" so please tell me the fix

**Comment by ASPredein** [comment]
it worked for me
https://github.com/timgrossmann/InstaPy/issues/5945#issuecomment-743930207

**Comment by elulcao** [comment]
This is the same like #5960 
Closing for now
