### ISSUE TITLE
[Windows] - Firefox portable - Instructions to avoid "binary is not a Firefox executable"

### ISSUE THREAD

**Issue by MCilento93** [InstaPy/InstaPy#5955]
## Expected Behavior
Testing how InstaPy works.

## Current Behavior
 Same troubles even if I tried a lot.
I tried InstaPy, instapy-quickstart, to install drivers for firefox or chrome, setting the drivers in PATH ... nothing
I have not firefox on my pc because I want to use Google Chrome.

## InstaPy configuration
last release
![image](https://user-images.githubusercontent.com/66259011/101986010-a9186100-3c8b-11eb-8ffb-0a57bab5f983.png)

**Comment by elulcao** [comment]
Chrome is not supported, 
use FireFox instead.

```bash
 13 ## [0.6.0] - 2019-08-12
 12
 11 ### Added
 10
  9 - Firefox Extension which hides Selenium
  8 - Black code formatter
  7 - Mobile user agent
  6 - Mobile Mode to enable mobile features
  5 - Screen shots (rotative screen shots are taken and saved in your InstaPy user folde    r)
  4 - Connection State
  3
  2 ### Breaking Changes
  1
216 - removed chromedriver
  1 - signature changes:
  2   - set_action_delays(random_range) -> (random_range_from, random_range_to)
  3   - set_delemit_liking(max, min) ->(max_likes, min_likes)
  4   - set_delemit_commenting(max, min) ->(max_comments, min_comments)
  5   - unfollow_users(customList, instapyfollowed) -> (custom_list_enabled, custom_list    , custom_list_param, instapy_followed_enabled, instapy_followed_param)
  6   - set*quota_supervisor(peak*_) ->(peak\_\_\_hourly, peak_\*\_daily)
```

**Comment by MCilento93** [comment]
Firefox portable will work?

**Comment by elulcao** [comment]
@MCilento93 
I don't know if FF portable will work, you also have to check geckodriver functionality with the FF portable.
However, you could try InstaPy Docker, 
so your host machine will be using Chrome but the Docker container will 
start the InstaPy session with the embebed Firefox.

**Comment by MCilento93** [comment]
Thank you,
I don't use docker commonly

In the afternoon I see from reference of instapy how to callback a Firefox portable

I will give a try

**Comment by MCilento93** [comment]
i switched to portable firefox. i get:

selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable

i tried installing gecko, maybe not correctly. somebody know how to fix this?

**Comment by MCilento93** [comment]
![image](https://user-images.githubusercontent.com/66259011/101996524-8742cc80-3cd3-11eb-8c89-f244a2223674.png)

**Comment by elulcao** [comment]
@MCilento93 

I'm not a Windows lover, but here we are.
To use a portable app, use the binary inside the App directory,
All portables apps so far I know have the same structure.
I'm quite sure your machine is x64, so `cd` to `FFPortable` -> `App` -> `FireFox64` -> `firefox`
That's it, you found the executable file.


```python
session = InstaPy(
	username="iammariocilento", 
	password="qwerty1993", 
	browser_executable_path="C:\\Users\\internet\\Downloads\\FirefoxPortable\\App\\Firefox64\\firefox.exe",
	geckodriver_path="C:\\Users\\internet\\Downloads\\geckodriver",)
```

**Comment by MCilento93** [comment]
> @MCilento93
> 
> I'm not a Windows lover, but here we are.
> To use a portable app, use the binary inside the App directory,
> All portables apps so far I know have the same structure.
> I'm quite sure your machine is x64, so `cd` to `FFPortable` -> `App` -> `FireFox64` -> `firefox`
> That's it, you found the executable file.
> 
> ```python
> session = InstaPy(
> 	username="iammariocilento", 
> 	password="qwerty1993", 
> 	browser_executable_path="C:\\Users\\internet\\Downloads\\FirefoxPortable\\App\\Firefox64\\firefox.exe",
> 	geckodriver_path="C:\\Users\\internet\\Downloads\\geckodriver",)
> ```

YOU ARE A F****** GENIUS!!!
It works greatly as you recommended! 
Finally it is going, the whole day through selenium and the bot finding nothing.

Thank you for you help!


Small guides for everybody using **Conda** and don't want to install Firefox:
1. Install Conda
2. install instapy with `pip install instapy` (create new env. first, recommended, many packages will be installed)
3. download [Firefox Portable](https://portableapps.com/apps/internet/firefox_portable), install the portable file in your project subfolder, like project/firefox 
4. download and extract last geckdriver in the project root (project/geckodriver.exe)
5. copy samewhere the absolute path to geckodriver.exe and firefox.exe (use the one in the nested path of portable installation folder, like FirefoxPortable\App\Firefox64\firefox.exe) and use like below:

```
'''
Setup guide: https://instapy.org/instance-settings
'''
from instapy import InstaPy

username='aa'
password='bb'
session = InstaPy(username=username,
                  password=password,
                  want_check_browser=True,
                  browser_executable_path=r"C:\Users\mario\Documents\Python\01 Works\instabot\FirefoxPortable\App\Firefox64\firefox.exe",
                  geckodriver_path=r'C:\Users\mario\Documents\Python\01 Works\instabot\geckodriver.exe').login()

# Like posts based on hashtags
session.like_by_tags(['tsitsipas', 'tennis'], amount=10)
```

Enjoy

**Comment by elulcao** [comment]
Closing for now,
Solution and instructions described above.
