### ISSUE TITLE
Problem with follow_user_followers

### ISSUE THREAD

**Issue by kamyargerami** [InstaPy/InstaPy#5961]
## Expected Behavior

hi,
I try to follow my friend's followers using a really simple configuration, and I get an error.
I really searched for a way to make it work but I can't find the solution.
please help me out if you can.

I run the app on ubuntu 18.04 VPS with an Xfce desktop environment.
the app login to my account successfully and it goes to my friend page and it gets their followers after it's done my firefox gets closed and I get an error on the terminal.

## Current Behavior

``
Traceback (most recent call last):
  File "insta.py", line 15, in <module>
    session.follow_user_followers(['tina_momenzadeh'], amount=600,
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 3415, in follow_user_followers
    person_list, simulated_list = get_given_user_followers(
  File "/usr/local/lib/python3.8/dist-packages/instapy/unfollow_util.py", line 1070, in get_given_user_followers
    person_list, simulated_list = get_users_through_dialog_with_graphql(
  File "/usr/local/lib/python3.8/dist-packages/instapy/unfollow_util.py", line 888, in get_users_through_dialog_with_graphql
    followers_list = random.sample(followers_list, real_amount)
  File "/usr/lib/python3.8/random.py", line 363, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
``

## InstaPy configuration

``
 imports
from instapy import InstaPy
from instapy import smart_run

insta_username = ''
insta_password = ''

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

session.follow_user_followers(['tina_momenzadeh'], amount=600,
                                  randomize=False, interact=False)
``

**Comment by jbisono26** [comment]
Im having the same issue. Mine wont follow anybody at all.

**Comment by gita-vahdatinia** [comment]
🤔 Issue comes from  `get_users_through_dialog_with_graphql` 
I think it is unable to get the followers list for that person
In line 820 of `unfollow_list.py` can you print(followers_list) before `followers_list = random.sample(followers_list, real_amount)` and see if it canbe printed out?

**Comment by girish-io** [comment]
I'm having the same issue.

@gita-v I have tried printing the `followers_list` like you said and it seems to be an empty list. The account whose users I'm trying to follow has followers and is not a private account either.

I also tried with different accounts but the result is the same, an empty `followers_list`.

**Comment by kamyargerami** [comment]
I think this is because instagram goes to Block Action mode and for seeing that error you must be usigng your phone , or changeing url of browser to see in regular mode (not view source mode)
i recommend you to change your configuration for follow or like with more delay.

**Comment by girish-io** [comment]
Apparently I had to call the `login()` method on the `InstaPy()` instance. Everything seems to work now.

**Comment by TheNighthawk99** [comment]
Hello, what is the solution here? I didn’t understand and I am getting the same error only when running in `headless_browser` mode TRUE.
