### ISSUE TITLE
Allow commenting on specific posts that already contain comment from user

### ISSUE THREAD

**Issue by sokratis1988** [InstaPy/InstaPy#5963]
## Expected Behavior
Comment a specific post that already contain a comment of the user.

## Current Behavior
Double postings on same post is not possible

## InstaPy configuration
not relevant

**Comment by elulcao** [comment]
Why do you want to comment twice a post?
What is the intention of commenting twice or more the same post, trying to get banned or something?

**Comment by sokratis1988** [comment]
I think commenting on the same post twice or more is not prohibited in instagram. So whats the reason for closing this issue?
