### ISSUE TITLE
link_elems error Message:

### ISSUE THREAD

**Issue by Spl01ter** [InstaPy/InstaPy#5970]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-12-21 09:35:19] [spl01ter]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-12-21 09:35:19] [spl01ter]  Tag [1/2]
INFO [2020-12-21 09:35:19] [spl01ter]  --> b'natgeo'
INFO [2020-12-21 09:35:50] [spl01ter]  Too few images, skipping this tag
INFO [2020-12-21 09:35:50] [spl01ter]  Tag [2/2]
INFO [2020-12-21 09:35:50] [spl01ter]  --> b'world'
INFO [2020-12-21 09:36:00] [spl01ter]  desired amount: 19  |  top posts [disabled]: 9  |  possible posts: 65652267
ERROR [2020-12-21 09:36:00] [spl01ter]  link_elems error Message: The element reference of <div> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

INFO [2020-12-21 09:36:04] [spl01ter]  Tag: b'world'
INFO [2020-12-21 09:36:04] [spl01ter]  Liked: 0
INFO [2020-12-21 09:36:04] [spl01ter]  Already Liked: 0
INFO [2020-12-21 09:36:04] [spl01ter]  Commented: 0
INFO [2020-12-21 09:36:04] [spl01ter]  Followed: 0
INFO [2020-12-21 09:36:04] [spl01ter]  Inappropriate: 0
INFO [2020-12-21 09:36:04] [spl01ter]  Not valid users: 0

**Comment by aleeepp** [comment]
Hi, similar issue>

   ```
 raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <body class=""> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
```

**Comment by Spl01ter** [comment]
Just do it with headless mode

**Comment by aleeepp** [comment]
HI, I am using this

`headless_browser=False`
