### ISSUE TITLE
Instapy Script Not following or Commenting

### ISSUE THREAD

**Issue by Emilio-1993** [InstaPy/InstaPy#5977]
## Expected Behavior

The script should like 10 pictures based on my tags list and comment/follow 80% of them. 

## Current Behavior

The script will only like the pictures. Commenting/Following does not work.

## InstaPy configuration

#Imports
from instapy import InstaPy
from instapy import smart_run
import random

#Login Credentials
instaUsername = ''
instaPassword = '!'

comments = ['Awesome!', 'Love it', 'Great pic!', u'\U0001F525' u'\U0001F525' u'\U0001F525', 'Dig it!', 'Cool!', 'Awesome pic!', 'Sweet!', u'\U0001F525', 'Nice!', 'Awesome pic!', 'Sweet pic!']

tags = ['audio', 'recordingartist', 'recording','audioengineer', 'producer', 'music']
testTag = ['audio']

#Get Session//Set Headless Browser
session = InstaPy(username = instaUsername, password = instaPassword, headless_browser = False)

#Activities
with smart_run(session):

    #Shuffle 
    random.shuffle(tags)
    random.shuffle(comments)

    #Interaction based on followers
    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=10000,
                                    min_followers=1000,
                                    min_following=50)

    #Like post based off tags
    session.like_by_tags(testTag, amount = 1, randomize = True, media = 'Photo')

    #Set User Interact
    #session.set_user_interact(amount=1, randomize=True, percentage=50, media='Photo')

    #Follow User
    session.set_do_follow(enabled = True, percentage=80, times = 2)

    #Comment post based off tags    
    session.set_do_comment(enabled=True, percentage=80)
    session.set_comments(comments)

    #Joining Engagement Pods
    session.join_pods(topic='entertainment', engagement_mode='normal')

    #Set daily quotas
    session.set_quota_supervisor(enabled=True,
                                    peak_comments_daily=250,
                                    peak_comments_hourly=50,
                                    peak_likes_daily=250,
                                    peak_likes_hourly=75,
                                    sleep_after=['likes', 'follows'])

    #Unfollow Users who dont follow me back
    session.unfollow_users(amount=100, instapy_followed_enabled=True, instapy_followed_param="nonfollowers", style="FIFO", unfollow_after=48*60*60, sleep_delay=501)
    
    #End session
    session.end()

**Comment by C0D3-BL00D3D** [comment]
@Emilio-1993  I have this issue too. It only likes but doesn't comment or follow. It doesn't even show "--> Not commented". Were you able to find a solution?
