### ISSUE TITLE
Unable to install Instapy

### ISSUE THREAD

**Issue by babbleninja** [InstaPy/InstaPy#5979]
## Expected Behavior
To install instapy

## Current Behavior
I tried 
1. pip install instapy
2. pip3 install instapy

In scenario 1: I am getting the error of 'Building wheel for grpcio (setup.py) ... error' 

In scenario 2: I am getting the error of 'Building wheel for grpcio (setup.py) ... error' along with 'ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly'

## OS used
Mac OS Big Sur

## Python Version
Python 3.8.2

## Pip Version
20.3.3

## Imp note
I have never coded before and this is my first time, and all of this is extremely new to me so please be kind.

**Comment by mehtaarn000** [comment]
What version of Python are you using? (Assuming you are using v3.x) You can check by running:

`python3 --version`

**Comment by babbleninja** [comment]
Python 3.8.2

**Comment by hridyanshdugar** [comment]
Download the whl file for cryptography from https://www.lfd.uci.edu/~gohlke/pythonlibs/ and install that first, should work then install instapy using pip

**Comment by babbleninja** [comment]
> Download the whl file for cryptography from https://www.lfd.uci.edu/~gohlke/pythonlibs/ and install that first, should work then install instapy using pip

The link you have quoted is for Windows, I'm on a Mac OS

**Comment by mehtaarn000** [comment]
@babbleninja what happens when you run: `pip install grpcio`?

**Comment by babbleninja** [comment]
> @babbleninja what happens when you run: `pip install grpcio`?

I get:
ERROR: Command errored out with exit status 1: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5l/6pd3wyxd12n9z_9wdkq_vmxr0000gn/T/pip-install-sBjwNn/grpcio/setup.py'"'"'; __file__='"'"'/private/var/folders/5l/6pd3wyxd12n9z_9wdkq_vmxr0000gn/T/pip-install-sBjwNn/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/5l/6pd3wyxd12n9z_9wdkq_vmxr0000gn/T/pip-record-nvtHhZ/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/rheanilanjanawasan/Library/Python/2.7/include/python2.7/grpcio Check the logs for full command output.

**Comment by babbleninja** [comment]
@mehtaarn000 I get: 
ERROR: Command errored out with exit status 1: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5l/6pd3wyxd12n9z_9wdkq_vmxr0000gn/T/pip-install-sBjwNn/grpcio/setup.py'"'"'; __file__='"'"'/private/var/folders/5l/6pd3wyxd12n9z_9wdkq_vmxr0000gn/T/pip-install-sBjwNn/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/5l/6pd3wyxd12n9z_9wdkq_vmxr0000gn/T/pip-record-nvtHhZ/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/babbleninja/Library/Python/2.7/include/python2.7/grpcio Check the logs for full command output.

**Comment by mehtaarn000** [comment]
Try doing the first answer in [this stackoverflow post](https://stackoverflow.com/questions/56357794/unable-to-install-grpcio-using-pip-install-grpcio).

**Comment by babbleninja** [comment]
@mehtaarn000  I tried to do that earlier, but I got the following- zsh: parse error near `\n'

**Comment by mehtaarn000** [comment]
@babbleninja which command gave you that error?

**Comment by babbleninja** [comment]
@mehtaarn000 pip3 install --no-cache-dir  --force-reinstall -Iv grpcio==1.34.0

I managed to fix that now and I tried: pip3 install instapy 
and I am back to square one, not getting the grpcio on pip3 however I am still getting this: 
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly

**Comment by sriram15crypto** [comment]
Try using .pkg Installer or use python 3
  If still the error presist
        Contact Customercare

**Comment by babbleninja** [comment]
@sriram15crypto Could you please explain?

**Comment by sriram15crypto** [comment]
Restart the application or , try reparing the pkg
Or update your system

**Comment by babbleninja** [comment]
The system is upgraded.
From what I understand cryptography is not yet released for Mac OS Big Sur, hence I am getting the issue on pip3

If I use pip, I still get the grpcio error, and I am guessing the newer versions of grpcio do not support pip anymore. 
Which grpcio version would you recommend to download for pip?

**Comment by sriram15crypto** [comment]
Try the older version .

**Comment by sriram15crypto** [comment]
Or try grprico.pkg install

**Comment by babbleninja** [comment]
There are quite a few older versions present, could you please advise on a version number perhaps?

**Comment by sriram15crypto** [comment]
Grpico.1.8.4 or Grpico.1.4.0

**Comment by babbleninja** [comment]
ERROR: Command errored out with exit status 1: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5l/6pd3wyxd12n9z_9wdkq_vmxr0000gn/T/pip-install-BvacD1/grpcio/setup.py'"'"'; __file__='"'"'/private/var/folders/5l/6pd3wyxd12n9z_9wdkq_vmxr0000gn/T/pip-install-BvacD1/grpcio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/5l/6pd3wyxd12n9z_9wdkq_vmxr0000gn/T/pip-record-3V6Xfn/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/babbleninja/Library/Python/2.7/include/python2.7/grpcio Check the logs for full command output.

**Comment by babbleninja** [comment]
pip is too old, pip3 is new but cryptographer is not yet optimised for my OS.

Is there any work around it?

**Comment by sriram15crypto** [comment]
Contact me on instagram _mr_kettavan *TOMORROW*
 GOOD NIGHT

**Comment by babbleninja** [comment]
Thank you, but I would rather carry this here so that it can be useful for someone else.

**Comment by laurielee525** [comment]
from some fishing around the internet, to fix the error with grpcio i used the command

GRPC_PYTHON_BUILD_SYSTEM_ZLIB=true pip install grpcio

Then, to fix the issues with cryptography, I did the following commands:
export CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS="1"
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

pip3 install cryptography==2.8

Then finally installed instapy with 
pip install instapy

hope this helps... also had the same exact issues as you and this worked for me!

**Comment by laurielee525** [comment]
followed this for problems with grpcio:
https://github.com/grpc/grpc/issues/24677

cryptography errors:
https://stackoverflow.com/questions/64919326/pip-error-installing-cryptography-on-big-sur

**Comment by babbleninja** [comment]
@laurielee525 did you use the brew install command? or just went straight for the export ones?

**Comment by laurielee525** [comment]
I already had openssl installed, so i skipped the brew install openssl

**Comment by babbleninja** [comment]
Could you help me with how to install it since I do not have it on my system :(

**Comment by babbleninja** [comment]
I installed openssl and tried the above, yet, same issue. At this point I think it can be because I am on the M1 chip?

**Comment by elulcao** [comment]
Could you try installing pip packages in a VIRTUALENV,
that will help you to isolate all the requirements for InstaPy.
DOCUMENTATION has an example and also InstaPy-quickstart has 
the example to configure a VIRTUALENV.

**Comment by GarrettKelley** [comment]
@babbleninja Were you ever successful? I'm having the same issue

**Comment by bajohn** [comment]
Hi all, I had a similar issue, my specific case being `google-cloud-bigquery` being unable to install `grpcio` using pipenv on Big Sur.

A quick fix that worked for me was running the following command in terminal:
```
export SYSTEM_VERSION_COMPAT=1
```
Afterwards, clang errors were no longer thrown and I was able to install `grpcio` and `google-cloud-bigquery` via pipenv. Not sure if this fix applies to the original issue but hope it helps!

**Comment by ivanoffalexander** [comment]
@GarrettKelley @babbleninja Were either of you able to get it to work? I'm still not able to install instapy.

**Comment by ivanoffalexander** [comment]
**FINAL UPDATE**: Finally got it to work. So, I specifically [downloaded Python 3.8.6](https://www.python.org/downloads/release/python-386/) (found some post on StackOverflow saying problems arose with 3.9.1, and I don't really use any of the new features that were added). I then set up my venv with python 3.8.6. After, in my venv (venv process with PyCharm located below), I ran this command `pip install git+https://github.com/timgrossmann/InstaPy.git`. It is found here: https://pypi.org/project/instapy/0.1.0/#preferred-installation

Now it all finally works! Hope this helps.


~~**Update**: This doesn't work. Now, I'm getting an `ImportError`, followed by `mach-o, but wrong architecture`.~~

~~If anyone figures it out, please let me know!~~

___
For anyone who encountered this issue, I spent a while trying to figure it out. Here was my solution. My specs:

macOS Big Sur 11.2.3
MacBook Air (M1, 2020)
Python 3.8.2

I'm working on a project in the IDE PyCharm. I kept trying to do a `pip install instapy` , then tried to do `pip install grpcio` and was receiving an error. My error was a massive red wave of text that finished along the lines of `CompileError: command 'clang' failed with exit status 1` followed by the final error of `ERROR: Failed building wheel for grpcio`. 

I am using iTerm2 as my Terminal replacement, but I think the process is basically the same if you have native Terminal. Go to your Applications directory in Finder, then create a duplicate of iTerm (or Terminal). Rename the copy as 'iTerm Rosetta' or something to that effect. Right click on the the newly created 'iTerm Rosetta' and tick the checkmark for it to `Open using Rosetta`. 

Now you should have two Terminals. The native iTerm is Apple chip based while the one we just duplicated is using Rosetta (don't ask me much beyond that). You can open both of these terminals and confirm that one is Apple chip based and the other is Intel based by opening your Activity Monitor. The architecture for one of the iTerm's will be Intel and for the other will be Apple.

Then, if you are using a venv for the project like myself, `cd` into the directory of your project via the Rosetta iTerm.  First, check the version of the python without activating the venv. You can do this by running `which python3`. Before activating, my iTerm shows me `/opt/homebrew/bin/python3`. 

You will then have to activate the environment. I'm not sure how to set up a venv manually -- PyCharm has done it for me. I'm in the directory of my project so when I `ls`, and I only have 1 main.py in my project, so i am returned `main.py         venv`. 

I then run `source venv/bin/activate`. You can confirm you've activated the venv by rerunning `which python3`. Now I am returned `/Users/your_username/your_project_directory/venv/bin/python3`. Now `pip3 install instapy`. This worked for me without any errors. You can then run `deactivate` and it will deactivate the venv in that iTerm window. The PyCharm proj will not be affected.

I'm pretty new to python and command line tutorials so I'm hoping this will help someone like myself who, before this, was not so familiar with venv. Good luck!
