### ISSUE TITLE
Unable to comment using interact_by_URL

### ISSUE THREAD

**Issue by hridyanshdugar** [InstaPy/InstaPy#5980]
## Expected Behavior
To comment on the post using the given url

## Current Behavior
Currently it is only liking the post and not commenting, im a bit of a noob, ive pasted my code below some one please help me out.

## InstaPy configuration
`
from instapy import InstaPy
from instapy import smart_run

class bot:
    def __init__(self,username,password):
        self.session =InstaPy(username=username,password=password,headless_browser=False)

    def follow_followers(self,username):
        self.session.set_skip_users(skip_private=False , skip_no_profile_pic=True)
        number = 100
        with smart_run(self.session):
            while number > 0:
                self.session.follow_user_followers([username], amount=10, randomize=False, sleep_delay=60)
                number -=10
                
    def comment_on_link(self,link):
        
        #define interaction settings
        self.session.set_do_like(enabled=False)
        self.session.set_comments(["Woah!!"])
        self.session.set_do_comment(enabled=True)
        
        
        #start the feature
        with smart_run(self.session):
            self.session.interact_by_URL(urls=[link], randomize=True, interact=True)

bot = bot(username,password)
bot.comment_on_link(url)
`

**Comment by elulcao** [comment]
Try the following template in your machine,
keep in mind that InstaPy could skip images or post
to emulate a real user action.

```python
11 with smart_run(session):
10     """ Activity flow """
 9     session.set_do_like(enabled=True, percentage=100)
 8     session.set_do_comment(enabled=True, comment_liked_photo=True, percentage=100)
 7     session.set_comments(comments)
 6     session.set_do_follow(enabled=True, percentage=100)
 5     # session.set_user_interact(amount=6, randomize=False, percentage=100)
 4     # session.follow_by_list(followlist=['instagram'], times=1, sleep_delay=600, interact=False)
 3     # session.set_user_interact(amount=10, randomize=True,percentage=100)
 2
 1     # start the feature
35     session.interact_by_URL(urls=links, randomize=True, interact=True)
```

**Comment by hridyanshdugar** [comment]
Still doesnt work, it likes some of the pictures, comments on none.

**Comment by arquicanedo** [comment]
@hridyanshdugar did you figure out why this is not working? I'm getting the same behavior. 

```
	|> LIKED 1 images  |  ALREADY LIKED: 0
	|> COMMENTED on 1 images
	|> FOLLOWED 1 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> LIKED 0 comments
	|> REPLIED to 0 comments
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0
	|> WATCHED 0 story(ies)  |  WATCHED 0 reel(s)

```

Although it reports 1 comment, it did not post the comment.

**Comment by arquicanedo** [comment]
It turns out I was using '@' in the comment. There seems to be a problem with mentions in comments. This PR solved the problem for me: https://github.com/timgrossmann/InstaPy/pull/5948

**Comment by hermasec** [comment]
i am trying to comment on a specific post in instagram
here is my code :

```
from instapy import InstaPy

insta_username = "username"
insta_password = "password"

session = InstaPy(username=insta_username, password=insta_password)
session.login()

# set up all the settings
session.set_relationship_bounds(enabled=True,delimit_by_numbers=True)
session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
session.set_do_comment(enabled=True, percentage=85)

session.interact_by_URL(urls=["https://www.instagram.com/p/CDBdLvUpTYu/?igshid=2im20zz3lvz5"], randomize=False, interact=True)
print("done")
# end the bot session
session.end()
```
this is what i get :
_INFO [2021-05-06 02:18:32] [username] --> Image already liked!
INFO [2021-05-06 02:18:32] [username] Liked: 0
INFO [2021-05-06 02:18:32] [username] Already Liked: 1
INFO [2021-05-06 02:18:32] [username] Commented: 0
INFO [2021-05-06 02:18:32] [username] Followed: 0
INFO [2021-05-06 02:18:32] [username] Inappropriate: 0
INFO [2021-05-06 02:18:32] [username] Not valid users: 0__

can someone plaese help me figure out why it doesnt comment anything!!

**Comment by ha-hashem** [comment]
> i am trying to comment on a specific post in instagram
> here is my code :
> 
> ```
> from instapy import InstaPy
> 
> insta_username = "username"
> insta_password = "password"
> 
> session = InstaPy(username=insta_username, password=insta_password)
> session.login()
> 
> # set up all the settings
> session.set_relationship_bounds(enabled=True,delimit_by_numbers=True)
> session.set_comments(['aMEIzing!', 'So much fun!!', 'Nicey!'])
> session.set_do_comment(enabled=True, percentage=85)
> 
> session.interact_by_URL(urls=["https://www.instagram.com/p/CDBdLvUpTYu/?igshid=2im20zz3lvz5"], randomize=False, interact=True)
> print("done")
> # end the bot session
> session.end()
> ```
> 
> this is what i get :
> _INFO [2021-05-06 02:18:32] [username] --> Image already liked! INFO [2021-05-06 02:18:32] [username] Liked: 0 INFO [2021-05-06 02:18:32] [username] Already Liked: 1 INFO [2021-05-06 02:18:32] [username] Commented: 0 INFO [2021-05-06 02:18:32] [username] Followed: 0 INFO [2021-05-06 02:18:32] [username] Inappropriate: 0 INFO [2021-05-06 02:18:32] [username] Not valid users: 0__
> 
> can someone plaese help me figure out why it doesnt comment anything!!

Same issue here. I think it's a bug.
