### ISSUE TITLE
Instapy can not handle cookie page ... Cookie file not found, creating cookie...

### ISSUE THREAD

**Issue by Lion-Frohnatur** [InstaPy/InstaPy#5983]
After showing the cookie acception Page of Instagram Instapy is closing the session

Last login: Fri Dec 25 17:41:07 on console
/Users/liontrautvetter/Desktop/Instapy/instapy-quickstart-master/run/mac_start.command ; exit;
liontrautvetter@Lions-MacBook-Pro ~ % /Users/liontrautvetter/Desktop/Instapy/instapy-quickstart-master/run/mac_start.command ; exit;
Starting InstaPy with quickstart
====================
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/liontrautvetter/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-12-25 17:41:33] [airflowflightschool]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-12-25 17:41:33] [airflowflightschool]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-12-25 17:41:34] [airflowflightschool]  - Internet Connection Status: ok
INFO [2020-12-25 17:41:34] [airflowflightschool]  - Current IP is "176.199.48.206" and it's from "Germany/DE"
INFO [2020-12-25 17:41:34] [airflowflightschool]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-12-25 17:41:34] [airflowflightschool]  - window.navigator.webdriver response: None
INFO [2020-12-25 17:41:34] [airflowflightschool]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
INFO [2020-12-25 17:42:19] [airflowflightschool]  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
/var/folders/r9/bk4slh2j4k75f7jft25fy7kh0000gn/T/20201225-174224.html
**********************************************************************

INFO [2020-12-25 17:42:24] [airflowflightschool]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 56.45 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-12-25 17:42:24] [airflowflightschool]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "../quickstart.py", line 26, in <module>
    with smart_run(session):
  File "/Users/liontrautvetter/.pyenv/versions/3.7.5/lib/python3.7/contextlib.py", line 114, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield

**Comment by shyland89** [comment]
I'm running into the same issue. If anyone can suggest a solution I'd really appreciate it!

Thanks

**Comment by elulcao** [comment]
could you share more details about your session, 
it's not clear if you are using InstaPy from pip or from git.
if you are using from git, the latest commit, then run InstaPy
in graphic mode and check if there is no new windows for
IG cookies; that could be the problem.

**Comment by shyland89** [comment]
Hi there,

I'm running InstaPy through pip and using Jupiter notebook to execute.

So there seems to be an additional 3rd cookies window on Instagram that has been added that InstaPy can't find the element to click on and get to the login screen

I can take a screen recording if that helps?

Thanks!

**Comment by bandidosjr** [comment]
Hi there, i have the same error here :(

root@osboxes:~/Desktop/quickstart# python3 like_.py
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-12-29 09:09:26] [naturalmentericiclato]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-12-29 09:09:26] [naturalmentericiclato]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-12-29 09:09:27] [naturalmentericiclato]  - Internet Connection Status: ok
INFO [2020-12-29 09:09:27] [naturalmentericiclato]  - Current IP is "95.223.74.34" and it's from "Germany/DE"
INFO [2020-12-29 09:09:27] [naturalmentericiclato]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-12-29 09:09:27] [naturalmentericiclato]  - window.navigator.webdriver response: None
INFO [2020-12-29 09:09:27] [naturalmentericiclato]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
INFO [2020-12-29 09:10:11] [naturalmentericiclato]  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20201229-091016.html
**********************************************************************

INFO [2020-12-29 09:10:17] [naturalmentericiclato]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 54.21 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-12-29 09:10:17] [naturalmentericiclato]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "like_.py", line 45, in <module>
    with smart_run(session):
  File "/usr/lib/python3.7/contextlib.py", line 114, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield


i run InstaPy from pip.

**Comment by elulcao** [comment]
Install with pip but use the latest commit,
`python -m pip install git+https://github.com/timgrossmann/InstaPy.git@ad160cb1e72060e1c1a1718db9e394557bf84baf`

**Comment by bandidosjr** [comment]
Hello elulcao :) thanks for your help.
i will post what i receive from the terminal:

root@osboxes:~# sudo python -m pip install git+https://github.com/timgrossmann/InstaPy.git@ad160cb1e72060e1c1a1718db9e394557bf84baf
Collecting git+https://github.com/timgrossmann/InstaPy.git@ad160cb1e72060e1c1a1718db9e394557bf84baf
  Cloning https://github.com/timgrossmann/InstaPy.git (to revision ad160cb1e72060e1c1a1718db9e394557bf84baf) to /tmp/pip-req-build-pQM2Zh
instapy requires Python '>=3, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 2.7.16
root@osboxes:~# sudo python3 -m pip install git+https://github.com/timgrossmann/InstaPy.git@ad160cb1e72060e1c1a1718db9e394557bf84baf
Collecting git+https://github.com/timgrossmann/InstaPy.git@ad160cb1e72060e1c1a1718db9e394557bf84baf
  Cloning https://github.com/timgrossmann/InstaPy.git (to revision ad160cb1e72060e1c1a1718db9e394557bf84baf) to /tmp/pip-req-build-d4pm9iz6
Requirement already satisfied: certifi>=2018.10.15 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (2020.12.5)
Requirement already satisfied: chardet>=3.0.4 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (4.0.0)
Requirement already satisfied: clarifai>=2.4.1 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (2.6.2)
Requirement already satisfied: configparser>=3.5.0 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (3.8.1)
Requirement already satisfied: EasyProcess>=0.2.3 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (0.3)
Requirement already satisfied: emoji>=0.5.1 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (0.6.0)
Requirement already satisfied: future>=0.17.1 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (0.18.2)
Requirement already satisfied: grpcio>=1.16.1 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (1.34.0)
Requirement already satisfied: idna>=2.7 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (2.10)
Requirement already satisfied: jsonschema<3,>=2.6.0 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (2.6.0)
Requirement already satisfied: plyer>=1.3.1 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (2.0.0)
Requirement already satisfied: protobuf>=3.6.1 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (3.14.0)
Requirement already satisfied: requests>=2.20.1 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (2.25.1)
Requirement already satisfied: selenium>=3.141.0 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (3.141.0)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (1.15.0)
Requirement already satisfied: urllib3>=1.24.1 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (1.26.2)
Requirement already satisfied: regex>=2018.11.22 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (2020.11.13)
Requirement already satisfied: MeaningCloud-python>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (2.0.0)
Requirement already satisfied: PyYAML>=3.13 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (5.3.1)
Requirement already satisfied: webdriverdownloader in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (1.1.0.3)
Requirement already satisfied: python-telegram-bot>=12.0.0 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (13.1)
Requirement already satisfied: PyVirtualDisplay>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from instapy==0.6.12) (1.3.2)
Requirement already satisfied: googleapis-common-protos<2,>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from clarifai>=2.4.1->instapy==0.6.12) (1.52.0)
Requirement already satisfied: tornado>=5.1 in /usr/local/lib/python3.7/dist-packages (from python-telegram-bot>=12.0.0->instapy==0.6.12) (6.1)
Requirement already satisfied: APScheduler==3.6.3 in /usr/local/lib/python3.7/dist-packages (from python-telegram-bot>=12.0.0->instapy==0.6.12) (3.6.3)
Requirement already satisfied: pytz>=2018.6 in /usr/local/lib/python3.7/dist-packages (from python-telegram-bot>=12.0.0->instapy==0.6.12) (2020.5)
Requirement already satisfied: cryptography in /usr/local/lib/python3.7/dist-packages (from python-telegram-bot>=12.0.0->instapy==0.6.12) (3.3.1)
Requirement already satisfied: decorator>=4.4.0 in /usr/local/lib/python3.7/dist-packages (from python-telegram-bot>=12.0.0->instapy==0.6.12) (4.4.2)
Requirement already satisfied: setuptools>=0.7 in /usr/local/lib/python3.7/dist-packages (from APScheduler==3.6.3->python-telegram-bot>=12.0.0->instapy==0.6.12) (51.1.1)
Requirement already satisfied: tzlocal>=1.2 in /usr/local/lib/python3.7/dist-packages (from APScheduler==3.6.3->python-telegram-bot>=12.0.0->instapy==0.6.12) (2.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography->python-telegram-bot>=12.0.0->instapy==0.6.12) (1.14.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography->python-telegram-bot>=12.0.0->instapy==0.6.12) (2.20)
Requirement already satisfied: pyOpenSSL>=0.14 in /usr/local/lib/python3.7/dist-packages (from requests>=2.20.1->instapy==0.6.12) (20.0.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from webdriverdownloader->instapy==0.6.12) (4.55.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from webdriverdownloader->instapy==0.6.12) (4.9.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.7/dist-packages (from beautifulsoup4->webdriverdownloader->instapy==0.6.12) (2.1)

and this is the result:

root@osboxes:~/Desktop/quickstart# python3 like_.py
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-12-29 17:43:14] [naturalmentericiclato]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2020-12-29 17:43:14] [naturalmentericiclato]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2020-12-29 17:43:15] [naturalmentericiclato]  - Internet Connection Status: ok
INFO [2020-12-29 17:43:15] [naturalmentericiclato]  - Current IP is "95.223.74.34" and it's from "Germany/DE"
INFO [2020-12-29 17:43:15] [naturalmentericiclato]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-12-29 17:43:15] [naturalmentericiclato]  - window.navigator.webdriver response: None
INFO [2020-12-29 17:43:15] [naturalmentericiclato]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
INFO [2020-12-29 17:44:00] [naturalmentericiclato]  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20201229-174405.html
**********************************************************************

INFO [2020-12-29 17:44:06] [naturalmentericiclato]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 57.39 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-12-29 17:44:06] [naturalmentericiclato]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "like_.py", line 45, in <module>
    with smart_run(session):
  File "/usr/lib/python3.7/contextlib.py", line 114, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield
root@osboxes:~/Desktop/quickstart#

**Comment by elulcao** [comment]
You need to remove the old InstaPy version,
1. pip uninstall instapy
2. python -m pip install git+https://github.com/timgrossmann/InstaPy.git@ad160cb1e72060e1c1a1718db9e394557bf84baf

**Comment by al3xfischer** [comment]
> You need to remove the old InstaPy version,
> 
> 1. pip uninstall instapy
> 2. python -m pip install git+https://github.com/timgrossmann/InstaPy.git@ad160cb1e72060e1c1a1718db9e394557bf84baf

I got the same problem.
After uninstalling the old version and installing the commit I get a slightly different output.
But the problem remains.
```
...
INFO [2020-12-30 08:49:32] [username]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2020-12-30 08:49:32] [username]  - window.navigator.webdriver response: None
INFO [2020-12-30 08:49:32] [username]  - Hide Selenium Extension: ok
INFO [2020-12-30 08:49:35] [username]  - Cookie file not found, creating cookie...
INFO [2020-12-30 08:50:14] [username]  Timed out with failure while explicitly waiting until visibility of element located!
```

**Comment by bandidosjr** [comment]
this is a very pleasure to say you that with quickstart.py (original File, only changed Username and Password) now work it perfectly ^^I would to like to contribute with other people that have for this moment a lot of trouble with this script (I see on YouTube). 
Just for info I use a Virtual Machine, Distro Kali Linux 2019.04 (up to this version doesn't work or probably because you will have an higher version of firefox. You must just to uninstall this (pip uninstall instapy) install this (python3 -m pip install git+https://github.com/timgrossmann/InstaPy.git@ad160cb1e72060e1c1a1718db9e394557bf84baf)
I searched this distro because you have firefox 60 and it could to give no problem with this script. 
but firstly I edited in /usr/local/lib/Python3.7/dist-packages/ the file "webdriverdownloader.py" and at line "321" where "if Len(filename) =! 1" I changed in 2 and than work it without any error with quickstart.py

**Comment by elulcao** [comment]
Guys, IG displays different pages based on region. I was informed that some regions are facing a new page that request to the user to accept the `IG Cookies` for some advertising and some kind of tracking; unfortunately in the geographical area that I am in, that page is not used yet and therefore I have no way to implement the mechanism to accept that new cookie. The only thing I can recommend for now is that you start InstaPy in graphical mode and manually accept that new cookie; that would be a WA for now.

**Comment by Tr1pke** [comment]
> > You need to remove the old InstaPy version,
> > 
> > 1. pip uninstall instapy
> > 2. python -m pip install git+https://github.com/timgrossmann/InstaPy.git@ad160cb1e72060e1c1a1718db9e394557bf84baf
> 
> I got the same problem.
> After uninstalling the old version and installing the commit I get a slightly different output.
> But the problem remains.
> 
> ```
> ...
> INFO [2020-12-30 08:49:32] [username]  -- Connection Checklist [2/2] (Hide Selenium Extension)
> INFO [2020-12-30 08:49:32] [username]  - window.navigator.webdriver response: None
> INFO [2020-12-30 08:49:32] [username]  - Hide Selenium Extension: ok
> INFO [2020-12-30 08:49:35] [username]  - Cookie file not found, creating cookie...
> INFO [2020-12-30 08:50:14] [username]  Timed out with failure while explicitly waiting until visibility of element located!
> ```

Can you click it yourself with the mouse? I do that mostly and it works

**Comment by shyland89** [comment]
> > > You need to remove the old InstaPy version,
> > > 
> > > 1. pip uninstall instapy
> > > 2. python -m pip install git+https://github.com/timgrossmann/InstaPy.git@ad160cb1e72060e1c1a1718db9e394557bf84baf
> > 
> > 
> > I got the same problem.
> > After uninstalling the old version and installing the commit I get a slightly different output.
> > But the problem remains.
> > ```
> > ...
> > INFO [2020-12-30 08:49:32] [username]  -- Connection Checklist [2/2] (Hide Selenium Extension)
> > INFO [2020-12-30 08:49:32] [username]  - window.navigator.webdriver response: None
> > INFO [2020-12-30 08:49:32] [username]  - Hide Selenium Extension: ok
> > INFO [2020-12-30 08:49:35] [username]  - Cookie file not found, creating cookie...
> > INFO [2020-12-30 08:50:14] [username]  Timed out with failure while explicitly waiting until visibility of element located!
> > ```
> 
> Can you click it yourself with the mouse? I do that mostly and it works

I installed the latest suggested version and just manually bypassed the additional cookie in graphical mode however after login a save window is appearing that even when I manually click will just log in but not complete any other commands I've outlined.

Any thoughts?

Thanks!

**Comment by Tr1pke** [comment]
> > > > You need to remove the old InstaPy version,
> > > > 
> > > > 1. pip uninstall instapy
> > > > 2. python -m pip install git+https://github.com/timgrossmann/InstaPy.git@ad160cb1e72060e1c1a1718db9e394557bf84baf
> > > 
> > > 
> > > I got the same problem.
> > > After uninstalling the old version and installing the commit I get a slightly different output.
> > > But the problem remains.
> > > ```
> > > ...
> > > INFO [2020-12-30 08:49:32] [username]  -- Connection Checklist [2/2] (Hide Selenium Extension)
> > > INFO [2020-12-30 08:49:32] [username]  - window.navigator.webdriver response: None
> > > INFO [2020-12-30 08:49:32] [username]  - Hide Selenium Extension: ok
> > > INFO [2020-12-30 08:49:35] [username]  - Cookie file not found, creating cookie...
> > > INFO [2020-12-30 08:50:14] [username]  Timed out with failure while explicitly waiting until visibility of element located!
> > > ```
> > 
> > 
> > Can you click it yourself with the mouse? I do that mostly and it works
> 
> I installed the latest suggested version and just manually bypassed the additional cookie in graphical mode however after login a save window is appearing that even when I manually click will just log in but not complete any other commands I've outlined.
> 
> Any thoughts?
> 
> Thanks!

I bypass everything manually with success

**Comment by shyland89** [comment]
> > > > > You need to remove the old InstaPy version,
> > > > > 
> > > > > 1. pip uninstall instapy
> > > > > 2. python -m pip install git+https://github.com/timgrossmann/InstaPy.git@ad160cb1e72060e1c1a1718db9e394557bf84baf
> > > > 
> > > > 
> > > > I got the same problem.
> > > > After uninstalling the old version and installing the commit I get a slightly different output.
> > > > But the problem remains.
> > > > ```
> > > > ...
> > > > INFO [2020-12-30 08:49:32] [username]  -- Connection Checklist [2/2] (Hide Selenium Extension)
> > > > INFO [2020-12-30 08:49:32] [username]  - window.navigator.webdriver response: None
> > > > INFO [2020-12-30 08:49:32] [username]  - Hide Selenium Extension: ok
> > > > INFO [2020-12-30 08:49:35] [username]  - Cookie file not found, creating cookie...
> > > > INFO [2020-12-30 08:50:14] [username]  Timed out with failure while explicitly waiting until visibility of element located!
> > > > ```
> > > 
> > > 
> > > Can you click it yourself with the mouse? I do that mostly and it works
> > 
> > 
> > I installed the latest suggested version and just manually bypassed the additional cookie in graphical mode however after login a save window is appearing that even when I manually click will just log in but not complete any other commands I've outlined.
> > Any thoughts?
> > Thanks!
> 
> I bypass everything manually with success

Would you mind sharing your code? (Without losing details of course) I just want to make sure I'm doing this right. When I click not now for save info I'm receiving this error "WebDriverException: Message: TypeError: browsingContextFn().currentWindowGlobal is null"

Thanks!

**Comment by elulcao** [comment]
`When I click not now for save info I'm receiving this error` that window is handled by InstaPy,
the other window must be displayed after that. Your will notice that the new window has only an `Accept` button.
That window is intended fo IG tracking purpose, marketing and other stuff.

**Comment by elulcao** [comment]
This is the new window, I copied from other issue.

<img width="456" alt="103455547-52cc9a00-4cee-11eb-97f3-98b07da63952" src="https://user-images.githubusercontent.com/6373960/103470417-b8914400-4d37-11eb-868f-016383672f61.png">

**Comment by Tr1pke** [comment]
> This is the new window, I copied from other issue.
> 
> <img alt="103455547-52cc9a00-4cee-11eb-97f3-98b07da63952" width="456" src="https://user-images.githubusercontent.com/6373960/103470417-b8914400-4d37-11eb-868f-016383672f61.png">

Click accept and your bot starts

**Comment by flaggz** [comment]
I have the same problem and the bot remains stuck on the homepage without scrolling, liking, following, etc.
latest teminal line is 
`INFO [2021-01-04 13:30:03] [xxx]  - Cookie file not found, creating cookie...`

**Comment by Tr1pke** [comment]
> I have the same problem and the bot remains stuck on the homepage without scrolling, liking, following, etc.
> latest teminal line is
> `INFO [2021-01-04 13:30:03] [xxx] - Cookie file not found, creating cookie...`

Then help and click manually

**Comment by flaggz** [comment]
> > I have the same problem and the bot remains stuck on the homepage without scrolling, liking, following, etc.
> > latest teminal line is
> > `INFO [2021-01-04 13:30:03] [xxx] - Cookie file not found, creating cookie...`
> 
> Then help and click manually

It's already logged in and idle at the instagram dashboard. I can navigate instagram with no problems but the bot is not doing anything

**Comment by tspgituser** [comment]
Same here. I have the same issue and when I try to "help" and accept the cookie manually, it's login to the IG page but not doing nothing from that point.
After that getting the time-out message:
"Timed out with failure while explicitly waiting until visibility of element located!"


P.S I am using the last version, on Windows

**Comment by tspgituser** [comment]
Today is working for me guys.
What I did, I deleted the extension.xpi, started the script and when I had the Cookie Page hit Accept, but after that don't do anything more. Wait for it and it will automatically login and choose "Not now" for the save page. 
After that it will create the cookie.

**Comment by flaggz** [comment]
after updating Firefox for Mac to 84.0.1 (64 bit) it doesn't work anymore

Error occurred while deleting cookies from web browser!
	b'Message: Browsing context has been discarded\n'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/util.py", line 1922, in smart_run
    session.login()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 427, in login
    if not login_user(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/login_util.py", line 417, in login_user
    dismiss_get_app_offer(browser, logger)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/login_util.py", line 539, in dismiss_get_app_offer
    offer_loaded = explicit_wait(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/util.py", line 1786, in explicit_wait
    result = wait.until(condition)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 415, in _find_element
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: browsingContextFn().currentWindowGlobal is null


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 189, in close_browser
    browser.delete_all_cookies()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 878, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: Browsing context has been discarded


INFO [2021-01-06 09:22:26] [instagramusername]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 54.04 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-01-06 09:22:26] [instagramusername]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "/Users/user/bot_.py", line 21, in <module>
    with smart_run(session):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/util.py", line 1922, in smart_run
    session.login()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 427, in login
    if not login_user(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/login_util.py", line 417, in login_user
    dismiss_get_app_offer(browser, logger)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/login_util.py", line 539, in dismiss_get_app_offer
    offer_loaded = explicit_wait(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/util.py", line 1786, in explicit_wait
    result = wait.until(condition)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 415, in _find_element
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: browsingContextFn().currentWindowGlobal is null

**Comment by Myloune** [comment]
I have the same on the ubuntu server version

InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/toto/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-01-06 11:01:46] [xx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-01-06 11:01:46] [xxx]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-01-06 11:01:47] [xxx]  - Internet Connection Status: ok
INFO [2021-01-06 11:01:47] [xxx]  - Current IP is "xx" and it's from "World"
INFO [2021-01-06 11:01:47] [xxx]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-01-06 11:01:47] [xxx]  - window.navigator.webdriver response: None
INFO [2021-01-06 11:01:47] [xxx]  - Hide Selenium Extension: ok
INFO [2021-01-06 11:01:51] [xxx]  - Cookie file not found, creating cookie...
INFO [2021-01-06 11:02:31] [xxx]  Timed out with failure while explicitly waiting until visibility of element located!

**Comment by t0bse** [comment]
same here!
