### ISSUE TITLE
raise RuntimeError("generator didn't yield") from None

### ISSUE THREAD

**Issue by debugbee** [InstaPy/InstaPy#5984]
## Expected Behavior
Login and starting to comment and follow by the tags I set

## Current Behavior
with smart_run(session):
  File "lib/python3.7/contextlib.py", line 114, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield

## InstaPy configuration
1. pip install -r requirement.txt within my conda virtual environment (current instapy version = 0.6.12)
2. test the function with my snipet:
```
from instapy import InstaPy
from instapy import smart_run

session = InstaPy(username="my_username", password="my_password", headless_browser=True)

with smart_run(session):
    session.set_smart_hashtags(["nsfw", "naked"], limit=3, sort="top", log_tags=True)
    session.like_by_tags(amount=5, use_smart_hashtags=True)

    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"],
                                 sleepyhead=True, stochastic_flow=True, notify_me=True,
                                 peak_likes_hourly=57,
                                 peak_likes_daily=585,
                                 peak_comments_hourly=21,
                                 peak_comments_daily=182,
                                 peak_follows_hourly=48,
                                 peak_follows_daily=None,
                                 peak_unfollows_hourly=35,
                                 peak_unfollows_daily=402,
                                 peak_server_calls_hourly=None,
                                 peak_server_calls_daily=4700)
    session.set_comments(["Nice!", "Sweet!", "Beautiful :heart_eyes:"], media="Photo")
    session.set_do_follow(enabled=True, percentage=60)
    session.set_do_comment(enabled=True, percentage=50)
```
3. generated html url (https://gist.github.com/debugbee/786ab960ccc5bf6376ee7ad915ba136c)

**Comment by gita-vahdatinia** [comment]
Do you have firefox installed?

**Comment by debugbee** [comment]
> Do you have firefox installed?

Yes, I tested the firefox driver with selenium in my another code, works.

**Comment by gita-vahdatinia** [comment]
Are those the entire error logs?

**Comment by elulcao** [comment]
That log is the HTML, share the STDOUT from the terminal, which is quite similar to the `general.log`

**Comment by debugbee** [comment]
But I can't reproduce the error again.

Here is the STDOUT just ran the snippet.

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/sabel/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-01-05 16:55:56] [4hisake]  Session started!
INFO [2021-01-05 16:55:56] [4hisake]  -- Connection Checklist [1/2] (Internet Connection Status)
.....................................................................................................................
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooo



WARNING [2021-01-05 17:00:56] [4hisake]  - Internet Connection Status: error
CRITICAL [2021-01-05 17:00:56] [4hisake]  Unable to login to Instagram! You will find more information in the logs above.
INFO [2021-01-05 17:00:58] [4hisake]  Sessional Live Report:
    |> No any statistics to show


[Session lasted 5.27 minutes]
INFO [2021-01-05 17:00:58] [4hisake]  Session ended!
Traceback (most recent call last):
  File "/instapy/instapy_login.py", line 7, in <module>
    session.set_smart_hashtags(["nsfw", "naked"], limit=3, sort="top", log_tags=True)
  File "/InstaPy/instapy/instapy.py", line 717, in set_smart_hashtags
    if data["tagExists"] is True:
KeyError: 'tagExists'

Process finished with exit code 1

**Comment by elulcao** [comment]
That error is because the link `apidisplaypurposes.com` for GET request is not working,
something changed in the backend for that service and now InstaPy cannot use the 
service as before. 
Then, the request returns an empty value (or not correct response in JSON format)
and the error you are facing for smart_tags.

For now, you need to use a predefined list for tags or comment the `session.set_smart_hashtags`
to avoid the issue 

```python
        for tag in tags:
            req = requests.get("https://apidisplaypurposes.com/tag/{}".format(tag))
            data = json.loads(req.text)

            if data["tagExists"] is True:
```

**Comment by Knrd2** [comment]
@elulcao 
Hello, im facing the same issue. How can i fix this now? 
![image](https://user-images.githubusercontent.com/51059827/108130201-91a48c80-70af-11eb-9b5b-1da554f41589.png)
InstaPy Version: 0.6.13

**Comment by elulcao** [comment]
Did you face the error after last commit, the one with
the variant for smart "tags"? 
If yes, What exactly is the error?
