### ISSUE TITLE
comments do not work

### ISSUE THREAD

**Issue by lukesilver-italy** [InstaPy/InstaPy#5986]
my bot doesn't comment anything.
i see always "--> Not commented"  
I don't know what  is the matter 
someone have fix it?

**Comment by C0D3-BL00D3D** [comment]
I have the same problem. No comments or follows, only likes. It doesn't even show "Not commented" for me.

**Comment by gita-vahdatinia** [comment]
Can you post your script @lukesilver-italy

**Comment by Spareo** [comment]
@lukesilver-italy have you tried making a comment without the bot using the same account? You might be action banned.

**Comment by HFG1PRO** [comment]
have the same problem someone help!!

**Comment by xkaneko** [comment]
Same problem here!

**Comment by mengqing** [comment]
Same issue here, straight from the example template and no changes made to the script other than the credential
