### ISSUE TITLE
How to set timeout

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5994]
I am using a bash executable to run Instapy in a loop

Sometimes the browser will stop loading and Instapy will stop working for hours until I manually come and close the window which will cause the executable to reopen Instapy, how can I do this automatically?

Method: 
If no new line is shown in the terminal for 2 mins, then quit Instapy 

Thanks and happy new year

**Comment by elulcao** [comment]
My recommendation is to use a `cron` job instead of a bash script.
BTW, you should share the complete bash script to understand what 
you want to achieve.

**Comment by ghost** [comment]
This is what I have right now:

```
while true ; do 
     python3 /Users/Name/Desktop/pythoncode.py
done

```

If no new line is shown in the terminal for 2 mins, then I want it to quit Instapy since it means the browser is not loading

**Comment by elulcao** [comment]
If I got your Idea, you want to run InstaPy in a bash loop. By now, let's imagine you are going to use `bash`.
What you can do is to check the exit status for the python command, if $RC is `0` break the loop since InstaPy finished successfully; otherwise start again the loop.

Since you are using bash, then you can check if the PID (`23324`) for the geckodriver has been created, if there is no PID for the geckodriver then break the loop.

```bash
$ psgrep geckodriver
internet           23324   0.0  0.1  4829292  30132 s004  S+   11:34AM   0:11.04 /Users/internet/InstaPy/assets/geckodriver --port 50622
```

Little example:
```bash
1  #!/bin/bash
 1
 2 while true ; do
 3     CMD='python --version'
 4     $CMD
 5     RC=$?
 6
 7     if [ $RC -eq 0 ]; then
 8         echo $CMD
 9         break
10     else
11         echo "$CMD failed"
12         echo "Start again after some time..."
13     fi
14
15 done
```

**Comment by ghost** [comment]
Thanks for your reply.

But the issue is **not** with Instapy **not starting**.

I am using responsive design mode in Firefox which causes the **browser to freeze sometimes randomly after some time of running Instapy**. I want the bash to notice instapy has not outputted anything into the terminal for 2 mins and I want the bash to kill the python script and run it again.

Thanks

**Comment by ghost** [comment]
In summary, I want to terminate the python script if it doesn’t output anything to the terminal in 2 min

**Comment by elulcao** [comment]
mmm, this should work. the `loop.py` needs to be replaced by your bot. 
The $SENTINEL is the control for the number of executions, change `3` to the number of times you want.
Change the time from `10` to `120`

```bash
1  #!/bin/bash
 1
 2 SENTINEL=0
 3
 4 while true ; do
 5     CMD='python loop.py'
 6     $CMD |
 7         while IFS= read -r line #  conveniently, is a space, a tab, and a newline.
 8         do
 9             if [ -z $line ]; then
10                 sleep 10 # Change the time
11                 break
12             else
13                 echo $line # Print number for python loop
14                 echo "InstaPy running..."
15             fi
16         done
17         SENTINEL=$[$SENTINEL +1]
18
19         if [ $SENTINEL -eq 3 ]; then
20             exit
21         fi
22 done
```

`loop.py`
```python
1 for i in range(3):
1     print(i)
2
3 print("") # this is the $line that the bash script will monitor.
```

**Comment by ghost** [comment]
Thanks so much. Will try this soon and update my comment

**Comment by ghost** [comment]
@elulcao 

Where do I add the 

```
1 for i in range(3):
1     print(i)
2
3 print("") # this is the $line that the bash script will monitor.
```

in `loop.py`? lol thx

```
import random
import time
from instapy import InstaPy
from instapy import smart_run

session = InstaPy(username='', password='', headless_browser=False, bypass_security_challenge_using='sms', page_delay=1)

with smart_run(session):

    users = ['xxx']
    random.shuffle(users)
    my_users = users[:1]

    # general settings
    session.set_dont_like(['sad', 'depression', 'depressed'])
    session.set_do_comment(enabled=True, percentage=50)
    session.set_comments([xxx])
    session.set_do_like(True, percentage=100)
    session.set_user_interact(amount=3, percentage=100, randomize=False)
    session.follow_likers(my_users, photos_grab_amount = 1, follow_likers_per_photo = 100, randomize=False, sleep_delay=1, interact=True)

```

**Comment by ghost** [comment]
Thanks for your help @elulcao 
If you have a paypal donation link, please leave it here I want to say thanks for your help in so many of my posts

**Comment by elulcao** [comment]
> Thanks for your help @elulcao 
> 
> If you have a paypal donation link, please leave it here I want to say thanks for your help in so many of my posts

Hello @Ardy000 
That's not necessary, 😃
I'm happy to share some ideas 💡
