### ISSUE TITLE
Does this get you the latest version always or just this latest version?

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#5996]
I tried this from the official documentation but it didn't work

`pip3 install -I https://github.com/timgrossmann/InstaPy/zipball/master`

A member on GitHub recommended this and it worked

`pip3 install git+https://github.com/timgrossmann/InstaPy.git@b6106ade39d42738b5af8060fe7cdf62d4e72224 `

My question is, does this get you the latest version always or just this latest version?

How do I find what to put inside the ** ** so I can get the latest version in the future

`pip3 install git+https://github.com/timgrossmann/InstaPy.git@**b6106ade39d42738b5af8060fe7cdf62d4e72224**`

**Comment by Ardy000** [comment]
I tried this from the official documentation but it didn't work

`pip3 install -I https://github.com/timgrossmann/InstaPy/zipball/master`

**Comment by Tr1pke** [comment]
What is the latest version? I have 0.6.12 from pip3 install ...

**Comment by elulcao** [comment]
From `https://github.com/timgrossmann/InstaPy/commits/master` you can check the latest `commit`

**Comment by Tr1pke** [comment]
> From `https://github.com/timgrossmann/InstaPy/commits/master` you can check the latest `commit`

Thank you. Got it. :-)
