### ISSUE TITLE
Add direct messaging

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#6]
###### Could look somewhat like this:
```python
.set_do_message(True, percentage=10)\
.set_direct_messages([])\
```

- [ ] add API for direct messaging
- [ ] make sure to exclude the given friends

**Comment by timgrossmann** [comment]
#### Update: Right now, direct messaging, sadly, is not possible on the web client. It's only available for the mobile apps.

###### If they'll add it later, I'll come back to this issue...

**Comment by iransales** [comment]
no updates?

**Comment by thEpisode** [comment]
@timgrossmann  @iransales maybe using another tool for this case

**Comment by joshuachinemezu** [comment]
@timgrossmann, I found out that direct messaging is enabled in the mobile version of instagram's web app, so using this approach https://github.com/timgrossmann/InstaPy/issues/4496#issuecomment-497947408, you can run the web driver from a mobile app web browser and thus have access to a whole lot of features which are not enabled in the desktop version of the web app. I am planning on creating a pull request for my solution to this issue. Notwithstanding, I suggest this features should be incorporated into the package. Thanks.

**Comment by hadifarnoud** [comment]
it is now enabled on desktop version too @joshuachinemezu
