### ISSUE TITLE
Bot block the account after one day use

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#6005]
## InstaPy configuration
I use interact with followers from file after I grab users after one day of use I was blocked from Instagram  My settings are 40 likes per hour 35 following no comments. How can I prevent next time to not block me

**Comment by ghost** [comment]
In my experience. Basically running instapy off a desktop computer is no longer possible.

**Comment by ghost** [comment]
Why that @Ardy000 what's is the diference from server and desktop.

**Comment by ghost** [comment]
Instagram does not allow many operations when not using the actual app (instapy uses the web browser) 

server is even worse

**Comment by ghost** [comment]
Ok that make sense.What alternative it have if not desktop then.

**Comment by ghost** [comment]
I'd start looking at other bots rather than Instapy. Or you could try running Instapy off a mobile phone (i haven't tried that so I don't know if it works better) instructions for that are on a medium.com article you can find it by google search

**Comment by ghost** [comment]
Thanks I see the article I will try.But still need some solution for desktop

**Comment by Tr1pke** [comment]
i run my instapy everyday without being blocked ...........................

**Comment by BoringBears** [comment]
@Tr1pke can you share your limit setting? are you running on a desktop or some other device?

**Comment by Tr1pke** [comment]
I'm running Instapy on UBUNTU that runs in a ESXi VMWARE server, my ubuntu has GNOME installed with firefox
my headless_browser is set to False else its to obvious to track its a bot. headless_browser=True is a big BS (sorry)
Sometimes I need to click on the accept button sometimes not. its not a big deal if you start the bot you want to make sure its started and you can wait 2 min and press is manually don't be lazy, nothing goes automatic except the rising of the sun.

For every different account I have a different Ubuntu OS installed in my VMWARE server so it won't mix files and if I fuck it up i copy a working VM OS and its back to normal.
I have 4 CPU's and 128GB installed in my VM server so got plenty resources, and for small things like instapy you can make you're own VM its easier for instapy 

My VMWARE server is standing in my own server room in my basement (i host small VM's for people)
I change my IP daily or per instapy process I start. (if I restart my modem i get a new IP)
During my instapy run I NEVER open that account on a different IP so only at home, since this is also a trigger for instagram to block you.

Like you will see in my script I change my script all the time that's why some settings have the # in front and some not + i change my amount number every time a start instapy Thats why i have #### and #---# to make it easy on myself.

If you always run the same script it will block you within days...… 
what also helps sometimes I don't run the script for 48 hours and do some manual things like a picture follow a new person etc 
That's also why I have a large "session.set_dont_include" list, in this list are all my _real_ friends that i really want to follow, if i follow a new friend that I want to keep ill add him to the session.set_dont_include list.



My conf: 
```
`
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace

set_workspace(path=None)

insta_username = "PRIVATE"
insta_password = "PRIVATE"
#### als ik browser op True zet kan ik screen gebruiken
#### als ik browser op False zet kan ik alles live zien in chrome
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)
#----#

#### User reqments
with smart_run(session):
    session.set_relationship_bounds(enabled=True,
                                     delimit_by_numbers=True,
                                      max_followers=15000,
                                      min_followers=40,
                                      min_following=40)
#----#

#### Delays
    session.set_action_delays(enabled=True,
                           like=15,
                           comment=20,
                           follow=20.17,
                           unfollow=38)
#----#

#### Supervisor
    session.set_quota_supervisor(enabled=True, sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                              peak_likes_hourly=10,
                              peak_likes_daily=300,
                               peak_comments_hourly=10,
                               peak_comments_daily=200,
                                peak_follows_hourly=10,
                                peak_follows_daily=None,
                                 peak_unfollows_hourly=10,
                                 peak_unfollows_daily=200,
                                  peak_server_calls_hourly=None,
                                  peak_server_calls_daily=4700)
#----#

#### Friends that i want to keep
    session.set_dont_include(["PRIVATE", "PRIVATE", "PRIVATE" etc])

#### Likes and Comments
#    session.set_do_follow(enabled=True, percentage=18, times=1)
#    session.set_do_comment(enabled=True, percentage=75)
#    session.set_comments([
# "Awesome!",
# "Really cool",
# "nice !",
#    session.like_by_tags(["PRIVATE", "PRIVATE", "PRIVATE"])
#    session.set_do_like(enabled=True, percentage=75)
#----#

#### follow
#    session.follow_user_followers(["PRIVATE", "PRIVATE", "PRIVATE"], amount=2, randomize=True, interact=False)
#----#

#### unfollow
#    session.unfollow_users(amount=100, allFollowing=True, style="RANDOM", unfollow_after=24*60*60, sleep_delay=1212)
#    session.unfollow_users(amount=100, instapy_followed_enabled=True, instapy_followed_param="all", style="FIFO", unfollow_after=90*60*60, sleep_delay=1212)
#----#

#### Follow user based on hashtags (without liking the image)
    session.follow_by_tags(["PRIVATE", "PRIVATE", "PRIVATE"], amount=1)
#    session.follow_by_tags(["PRIVATE", "PRIVATE", "PRIVATE"], amount=1)
#----#

#### Follow the likers of photos of users
#    session.follow_likers(["PRIVATE", "PRIVATE", "PRIVATE"], photos_grab_amount=1, follow_likers_per_photo=2, randomize=True, sleep_delay=1212, interact=False)
#----#

#### Unfollow outgoing requests
#    session.remove_follow_requests(amount=500, sleep_delay=1212)
#----#
`
```

remember if you want to make it work you need to work a little bit yourself or pay someone

**Comment by Tr1pke** [comment]
> @Tr1pke can you share your limit setting? are you running on a desktop or some other device?

done

**Comment by Tr1pke** [comment]
> @Tr1pke can you share your limit setting? are you running on a desktop or some other device?

done

**Comment by ghost** [comment]
Thank you for recomendation I use biger limits than this thats why they block me probably

**Comment by Tr1pke** [comment]
> Thank you for recomendation I use biger limits than this thats why they block me probably

You need to act like a human. A human is not following like unfollow the whole day. We eat drink sleep work 😀

**Comment by rxng** [comment]
Any way to 
1) randomise the quotas values

2) make the script sleep for 48 hours break like you mentioned ? 

@Tr1pke

**Comment by Tr1pke** [comment]
> Any way to
> 
> 1. randomise the quotas values
> 2. make the script sleep for 48 hours break like you mentioned ?
> 
> @Tr1pke

 Yes. 
1. Change the script manually with a text editor ......

2. Stop the bot and turn it back on after 48 hours ........

**Comment by rxng** [comment]
Any way to randomise the values programmatically? E.g. using python randint

**Comment by Tr1pke** [comment]
> Any way to randomise the values programmatically? E.g. using python randint

Probably there is, but what's random for a computer? ....

**Comment by rxng** [comment]
if you are going to do this peak_likes_hourly=10,

you could do a random number between 8 to 12 instead, each session

e.g. randint(8,10)

**Comment by davera-017** [comment]
@Tr1pke Hi, I was wondering, what is the use in your code of `session.set_do_follow` and `session.set_do_comment` if you have `interact = False` everywhere else. I'm new in InstaPy, so thanks for any explanaition.

**Comment by Tr1pke** [comment]
> @Tr1pke Hi, I was wondering, what is the use in your code of `session.set_do_follow` and `session.set_do_comment` if you have `interact = False` everywhere else. I'm new in InstaPy, so thanks for any explanaition.

I change my code weekly so have some variations in my actions. If you use the same code for weeks you get blocked. I never have been blocked with this code and variations

**Comment by pedromoto4** [comment]
@Tr1pke thank you for share your experience,
but let me ask you how you deal with the amount of IG accounts in the same IP, you don't have problems with this? our you just have 2 or 3 accounts?

Best regards,

**Comment by Tr1pke** [comment]
> @Tr1pke thank you for share your experience,
> but let me ask you how you deal with the amount of IG accounts in the same IP, you don't have problems with this? our you just have 2 or 3 accounts?
> 
> Best regards,

VPN ...

**Comment by pedromoto4** [comment]
Private! I suppose :)

**Comment by Tr1pke** [comment]
> Private! I suppose :)

i work in a datacenter ;-) got IPs enough and in Belgium when you reset your modem you have a new IP 
so we are basically unlimited with IPs

**Comment by pedromoto4** [comment]
@Tr1pke haha good advantage :) . Other point I have researched the topics and I have already found some where it is said that this project is dead because the web version of the IG is limiting usage a lot, and it blocks very easily, is this still true? or already got around?

**Comment by Tr1pke** [comment]
> @Tr1pke haha good advantage :) . Other point I have researched the topics and I have already found some where it is said that this project is dead because the web version of the IG is limiting usage a lot, and it blocks very easily, is this still true? or already got around?

Here and there you see a change. It’s dead but not rotten yet, it’s more like a zombie

**Comment by caskednow** [comment]
@Tr1pke it is all about setup. I've noticed that blocks occur more frequently from time to time. I run Raspberry Pi setup with geckodriver and sometimes I just have to adjust the action delays, to make bot work for a few hours a day. Sometimes it requires also turning on/off headless mode. Also each time I delete old cookie for InstaPy to make sure it doesn't use the outdated one.

Unfortunately blocking depends also on the account. When I used to run script rarely, there was no problem with blocking. But when I started to use it on a daily basis on one account, the blocking started to happen frequently. Now, almost everyday, IG asks to verify account, but after that I can run a bot for a few hours in a row. My IP is being changed regularly (dynamic IP), but I can't exceed 5-6 hours of work each day.

**Comment by Tr1pke** [comment]
> @Tr1pke it is all about setup. I've noticed that blocks occur more frequently from time to time. I run Raspberry Pi setup with geckodriver and sometimes I just have to adjust the action delays, to make bot work for a few hours a day. Sometimes it requires also turning on/off headless mode. Also each time I delete old cookie for InstaPy to make sure it doesn't use the outdated one.
> 
> Unfortunately blocking depends also on the account. When I used to run script rarely, there was no problem with blocking. But when I started to use it on a daily basis on one account, the blocking started to happen frequently. Now, almost everyday, IG asks to verify account, but after that I can run a bot for a few hours in a row. My IP is being changed regularly (dynamic IP), but I can't exceed 5-6 hours of work each day.

And what is your bot doing? My bot unfollows for 10/12hours in a row 5 days long every 10min 10users. Never got blocked. (That’s 800 users in total in a week)

**Comment by pedromoto4** [comment]
> > @Tr1pke haha good advantage :) . Other point I have researched the topics and I have already found some where it is said that this project is dead because the web version of the IG is limiting usage a lot, and it blocks very easily, is this still true? or already got around?
> 
> Here and there you see a change. It’s dead but not rotten yet, it’s more like a zombie


ohhhh I was so wrong, I was thinking this was a very healthy project :P
Is there any alternative ?

**Comment by Tr1pke** [comment]
> > > @Tr1pke haha good advantage :) . Other point I have researched the topics and I have already found some where it is said that this project is dead because the web version of the IG is limiting usage a lot, and it blocks very easily, is this still true? or already got around?
> > 
> > 
> > Here and there you see a change. It’s dead but not rotten yet, it’s more like a zombie
> 
> ohhhh I was so wrong, I was thinking this was a very healthy project :P
> Is there any alternative ?

It’s still good but people are greedy. They want to run scripts 24/7 while it’s oke when you run it a couple days in a week. 
All bots are using the website so the Instagram rules are everywhere the same.
