### ISSUE TITLE
Restarting after error

### ISSUE THREAD

**Issue by Pormientras** [InstaPy/InstaPy#601]
Hey everyone, I have started learning python and everything is working pretty well, with the only problem that sometimes my script crashes and then I have to manually restart the script, and I was searching online and I couldnt find a way to restart the script automatically after a crash.

Does anybody know if this is posible or if its too complicated?

By the way heres my quickstart.py if theres something wrong with it:
```
InstaPy(username=insta_username, password=insta_password)\
  .login()\
  .set_user_interact(amount=3, random=True, percentage=50, media='Photo')\
  .set_do_like(enabled=True, percentage=70)\
  .set_do_follow(enabled=True, percentage=50)\
  .set_do_comment(enabled=False, percentage=80)\
  .interact_user_followers(['shapeways'], amount=100, random=True)\
  .end()

```

**Comment by Pormientras** [comment]
Forgot to put the error:
`Traceback (most recent call last):
  File "C:\Python36-32\InstaPy-master\quickstart.py", line 12, in <module>
    .interact_user_followers(['something'], amount=100, random=True)\
  File "C:\Python36-32\InstaPy-master\instapy\instapy.py", line 864, in interact_user_followers
    self.like_by_users(userToInteract, self.user_interact_amount, self.user_interact_random, self.user_interact_media)
  File "C:\Python36-32\InstaPy-master\instapy\instapy.py", line 593, in like_by_users
    followed += follow_user(self.browser, self.follow_restrict, self.username, username)
  File "C:\Python36-32\InstaPy-master\instapy\unfollow_util.py", line 136, in follow_user
    follow_button = flwBtn[0]
IndexError: list index out of range`

**Comment by timgrossmann** [comment]
@Pormientras Where are you running the script?

**Comment by Pormientras** [comment]
@timgrossmann Hey Tim! Im running it in the Python 3.6.1 Shell with chrome and in windows

**Comment by sionking** [comment]
Have the same error on the same platform, it is been a week now

**Comment by sionking** [comment]
Should we move to firefox ?

**Comment by converge** [comment]
couldn't reproduce the error since there were a lot of new commits since this report. Please, reopen this issue in case you find this bug again.
