### ISSUE TITLE
Problem running on DigitalOcean

### ISSUE THREAD

**Issue by pereverges** [InstaPy/InstaPy#6049]
## Expected Behavior

To work

## Current Behavior

_.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
No any custom workspace provided.	~using existing..
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-01-24 10:32:07] []  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-01-24 10:32:07] []  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-01-24 10:32:07] []  - Internet Connection Status: ok
INFO [2021-01-24 10:32:07] []  - Current IP is "...." and it's from "...."
INFO [2021-01-24 10:32:07] []  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-01-24 10:32:07] []  - window.navigator.webdriver response: None
INFO [2021-01-24 10:32:07] []  - Hide Selenium Extension: ok
INFO [2021-01-24 10:32:15] []  - Cookie file not found, creating cookie...
INFO [2021-01-24 10:32:54] []  Timed out with failure while explicitly waiting until visibility of element located!

^C
INFO [2021-01-24 10:32:58] []  Sessional Live Report:
	|> No any statistics to show

## InstaPy configuration
Running instapy on DigitalOcean, When I run the quickstart.py in the machine it gets stuck after:
INFO [2021-01-24 10:32:15] []  - Cookie file not found, creating cookie...
and then it times out. I have reproduced the same behaviour in  mi Ubuntu laptop and there it works perfectly

**Comment by elulcao** [comment]
I suspect that this is related to the new IG cookie page,
just guessing,
did you try I graphic mode, to see where the Instapy bot is failing.
btw, I don't recall if DOcean has a graphic mode, could you elaborate

**Comment by pereverges** [comment]
I could solve the problem by executing it locally first to generate the cookie file and after copy it to the digitalOcean server

**Comment by nikipi** [comment]
> I could solve the problem by executing it locally first to generate the cookie file and after copy it to the digitalOcean server

Hi could you please explain this more detailly. I have the same issue would appreciate your help.
