### ISSUE TITLE
Instagram blocks me from liking photos immediately

### ISSUE THREAD

**Issue by vandreadCS** [InstaPy/InstaPy#605]
Hi,

I just set this up quickly and everything works fine except. Immediately when I launched the script and it started liking pictures using chrome browser, my instagram account was blocked from liking more pictures. So I tried again using another account and the same thing happened. What could possibly be wrong?

**Comment by keivan85** [comment]
In case u run the script on server and use your own device Instagram probably starts blocking you. Since you can not like/comment at a same time from different parts of the world. May be that's the case.

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
