### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#6055]

**Comment by SilverMarc0** [comment]
I had the same problem since today, 
I have randomly run : 
($shell)
pip install instapy

Everything seems to work fine now. 

Hope it will work for you too ;)

**Comment by ghost** [comment]
> I had the same problem since today,
> I have randomly run :
> ($shell)
> pip install instapy
> 
> Everything seems to work fine now.
> 
> Hope it will work for you too ;)

It works

**Comment by ghost** [comment]
thx :)
