### ISSUE TITLE
Accept Second Cookie Page

### ISSUE THREAD

**Issue by SanielDous** [InstaPy/InstaPy#6060]
## Expected Behavior
Log into Instagram Account

## Current Behavior
- **Short**: Stuck at second cookie page
- **Long**: Lately, I updated to instapy 0.6.13 and faced the following problem. Instagram is showing a second "cookie accept screen" that is not automatically accepted.

### Log
```
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/user/InstaPy"
INFO [2021-02-01 21:54:05] [username]  Session started!
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-02-01 21:54:05] [username]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-02-01 21:54:06] [username]  - Internet Connection Status: ok
INFO [2021-02-01 21:54:06] [username]  - Current IP is "123.456.789.0" and it's from "earth"
INFO [2021-02-01 21:54:06] [username]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-02-01 21:54:06] [username]  - window.navigator.webdriver response: None
INFO [2021-02-01 21:54:06] [username]  - Hide Selenium Extension: ok
INFO [2021-02-01 21:54:09] [username]  - Cookie file not found, creating cookie...
INFO [2021-02-01 21:54:48] [username]  Timed out with failure while explicitly waiting until visibility of element located!

**********************************************************************
If raising an issue, please also upload the file located at:
/tmp/20210201-215453.html
**********************************************************************
INFO [2021-02-01 21:54:54] [username]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 52.47 seconds]
INFO [2021-02-01 21:54:54] [username]  Session ended!
Traceback (most recent call last):
  File "/path/to/script", line 92, in <module>
    run_script()
  File "/path/to/script", line 31, in run_script
    with smart_run(session):
  File "/usr/lib/python3.8/contextlib.py", line 115, in __enter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
ooooooooooooooooooooooooooooooooooooooooooooooooooooooo
```

### Screenshots
I took some screen shots of both cookie pages...
<img src="https://user-images.githubusercontent.com/26697239/106518153-c45c5b80-64d9-11eb-8828-147effb73d69.png" alt="drawing" width="300"/>
The seconds one appearing after the first page was accepted...
<img src="https://user-images.githubusercontent.com/26697239/106518170-ca523c80-64d9-11eb-84e2-a0649edbe148.png" alt="drawing" width="300"/>

### HTML file
HTML referred in the log (zipped because github doesn't allow .html):
[20210201-215453.zip](https://github.com/timgrossmann/InstaPy/files/5906813/20210201-215453.zip)

**Comment by SanielDous** [comment]
A fix that works for me so far is adding line 283 (as show in the screenshot) to the `login_util.py` file to always try to accept cookies by calling `accept_igcookie_dialogue(browser, logger)` outside of the if statement.
![image](https://user-images.githubusercontent.com/26697239/106524947-89f7bc00-64e3-11eb-89a9-3e024c3fa0a3.png)

**Comment by elulcao** [comment]
I will add the line in a new PR, hope this help others to use InstaPy without manual intervention.

```python
283 # This fix comes from comment in #6060 If not necessary we can remove it
284     accept_igcookie_dialogue(browser, logger)
```

**Comment by SanielDous** [comment]
@elulcao Thank you for taking care of it! I think this is only a workaround that fixes it for now. If they add a third, fourth... (for whatever reason - maybe just to troll around 🤷‍♂️) cookie page the code is broken again. It would be better to somehow detect that the bot is stuck at a cookie page and dismiss as many cookie pages as needed.

Unfortunately, I'm not that familiar with selenium to post some prototype code of my idea...

**Comment by Tr1pke** [comment]
> I will add the line in a new PR, hope this help others to use InstaPy without manual intervention.
> 
> ```python
> 283 # This fix comes from comment in #6060 If not necessary we can remove it
> 284     accept_igcookie_dialogue(browser, logger)
> ```

Thank you

**Comment by orhan-drsn** [comment]
> A fix that works for me so far is adding line 283 (as show in the screenshot) to the `login_util.py` file to always try to accept cookies by calling `accept_igcookie_dialogue(browser, logger)` outside of the if statement.
> ![image](https://user-images.githubusercontent.com/26697239/106524947-89f7bc00-64e3-11eb-89a9-3e024c3fa0a3.png)

Where is the right "login_util.py" located? I added this line to mine (for me in /usr/local/lib/python3.8/dist-packages/instapy), but it does not change.

**Comment by elulcao** [comment]
Closing for now, #6079 has been merged. If the secondary pop up window is still an issue, please feel free to open a new issue. 
Thanks
