### ISSUE TITLE
Reguarly blocked for suspicious activity

### ISSUE THREAD

**Issue by sanc21** [InstaPy/InstaPy#6071]
Hi everyone,

I'd like to start by thanking you guys for this project, such an amazing tool!

My account is being blocked on a daily basis. I have InstaPy running on a Raspberry Pi, running a somewhat conservative script.

I was wondering: is there a way to run this on Android with docker? That might be the safest option, so the platform and IP is the same as the app.

Do you guys manage to run it autonomously for longer periods of time?

Thanks

**Comment by PiratePaprika** [comment]
Does it run in [Termux](https://termux.com/)?
