### ISSUE TITLE
Stale element reference closes the session

### ISSUE THREAD

**Issue by slasksebbe** [InstaPy/InstaPy#6074]
InstaPy keeps encountering stale element references every time I run it, and when it does it just ends the session abruptly rather than just move on. This has made the bot completely unusable as it will just run for a couple of minutes and then crash. 

Here is a link to an article explaining the error:
https://developer.mozilla.org/en-US/docs/Web/WebDriver/Errors/StaleElementReference

And here is a link to another article that suggests solutions and workarounds:
https://www.softwaretestingmaterial.com/stale-element-reference-exception-selenium-webdriver/

Now I am a complete beginner at coding and would not know how to fix this. It seems to be a very common issue with InstaPy as I've found many threads with this issue but no fix. 

## Expected Behavior
When InstaPy encounters a stale element reference, it should reload the webpage and try again or skip the current user.

## Current Behavior
When InstaPy encounters a stale element reference, it just ends the current session.

## Possible Solution (optional)
It seems to me that for now it can be avoided by coding InstaPy to refresh the page and try again, and if it fails again, just move on to the next user, but of course the better solution would be to figure out what is causing InstaPy to encounter stale element references to begin with and fix that.

## InstaPy configuration

    from instapy import InstaPy
    from instapy import smart_run

    insta_username = 'account'
    insta_password = 'password'

    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False)

    with smart_run(session):

    session.set_relationship_bounds(enabled=True,
                                    delimit_by_numbers=True,
                                    max_followers=2500,
                                    max_following=1500, 
                                    min_followers=10,
                                    min_following=10,
                                    max_posts=2500)

    session.set_dont_include(["friend1", "friend2", "friend3"])
    session.set_dont_like(["pizza", "#store"])
    session.set_do_follow(enabled=True, percentage=100, times=1)
    session.set_skip_users(skip_private=False)
    session.set_quota_supervisor(enabled=True, sleep_after=["comments"], sleepyhead=False, stochastic_flow=False, notify_me=False,
                              peak_likes_hourly=None,
                              peak_likes_daily=None,
                               peak_comments_hourly=None,
                               peak_comments_daily=None,
                                peak_follows_hourly=25,
                                peak_follows_daily=100,
                                 peak_unfollows_hourly=25,
                                 peak_unfollows_daily=105,
                                  peak_server_calls_hourly=None,
                                  peak_server_calls_daily=None)

    session.follow_likers(['lofi_aesthetics'], 
                          photos_grab_amount=1,
                          follow_likers_per_photo=120, 
                          randomize=False, 
                          sleep_delay=0,
                          interact=False)
    

## Error message
Traceback (most recent call last):
  File "C:\Users\Sebastian\Downloads\instapy-quickstart-master\instapy-quickstart-master\quickstart.py", line 70, in <module>
    session.follow_likers(['lofi_aesthetics'],
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1076, in follow_likers
    followed = self.follow_by_list(
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1222, in follow_by_list
    follow_state, msg = follow_user(
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\unfollow_util.py", line 554, in follow_user
    click_visibly(browser, follow_button)  # click to follow
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\util.py", line 1981, in click_visibly
    browser.execute_script(
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <button class="sqdOP  L3NKy _4pI4F  y3zKF     " type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed

**Comment by elulcao** [comment]
Could you try with Python3.8, so far I remember P3.9 and Windows
could trigger those errors. Iv been running the bot in unix-like platforms
and everything in a good shape.
Let us know if python3.8 makes some difference, if you don't want to downgrade
the version, there are other options like virtualenv.

**Comment by slasksebbe** [comment]
> Could you try with Python3.8, so far I remember P3.9 and Windows
> could trigger those errors. Iv been running the bot in unix-like platforms
> and everything in a good shape.
> Let us know if python3.8 makes some difference, if you don't want to downgrade
> the version, there are other options like virtualenv.

Thank you so much for your reply! :) I'd be happy to try this but I don't know how to change my Python version and run InstaPy in the older version. Could you please explain how to do this? Do I need to somehow completely uninstall Python and InstaPy and install them all over again but with Python3.8 instead, or is there a different way?

**Comment by elulcao** [comment]
You can have both versions, 3.8 and 3.9, 
1. Download Python3.8
2. Install Python3.8
3. Then use python3.8 instead of python in the Terminal.
4. Create your virtual env, to isolate installations from OS defaults.

Here is the link for a couple of examples:
https://instapy.org/additional-information#how-to-avoid-python--pip-confusion

**Comment by slasksebbe** [comment]
> You can have both versions, 3.8 and 3.9,
> 
> 1. Download Python3.8
> 2. Install Python3.8
> 3. Then use python3.8 instead of python in the Terminal.
> 4. Create your virtual env, to isolate installations from OS defaults.
> 
> Here is the link for a couple of examples:
> https://instapy.org/additional-information#how-to-avoid-python--pip-confusion

Hi again! Thank you! I ended up just formatting my Windows machine and installing Python3.8 and InstaPy again.

I'm afraid I am still getting the same error with Python 3.8 installed, although slightly less often it seems. Before downgrading I would say I got between 0-5 follows in before it crashed, now it seems to be more like 3-10 follows before it crashes.
