### ISSUE TITLE
Running Instapy on two accounts at the same time

### ISSUE THREAD

**Issue by patrickneulinger** [InstaPy/InstaPy#6084]
## Expected Behavior

I've two instagram accounts and I want to run them at the same time
## Current Behavior

if I start both, the second one rises

[Errno 26] Text file busy: '/home/patrickneulinger/InstaPy/assets/gecko/v0.29.0/geckodriver-v0.29.0-linux64/geckodriver'

**Comment by Tr1pke** [comment]
use 2 accounts, problem solved

**Comment by patrickneulinger** [comment]
no its not working if you do that at the same time, I solved it to run it async
