### ISSUE TITLE
Join_pods function, how do I use it ?

### ISSUE THREAD

**Issue by hugos** [InstaPy/InstaPy#6089]
I was wondering how to use the join_pods function?

I currently have this on my script:

`    session.join_pods(topic='entertainment', engagement_mode='light')`

## My specific questions are:

_How does Instapy join and find the pods?_

_What other topics and engagement modes are there?_

I cannot seem to find any relevant information about this topic, the helpful comments from the previous issues regarding this have been deleted so...

Thank you.

**Comment by hadi1hadi2** [comment]
Parameters:

topic: Topic of the posts to be interacted with. general by default.

    Note : Topics allowed are {'general', 'fashion', 'food', 'travel', 'sports', 'entertainment'}.

engagement_mode: Desided engagement mode for your posts. There are four levels of engagement modes 'no_comments', 'light', 'normal' and 'heavy'(normal by default). Setting engagement_mode to 'no_comments' makes you receive zero comments on your posts from pod members, 'light' encourages approximately 10% of pod members to comment on your post, similarly it's around 30% and 90% for 'normal' and 'heavy' modes respectively. Note: Liking, following or any other kind of engagements doesn't follow these modes.
