### ISSUE TITLE
Error: number_of_posts  results NoneType

### ISSUE THREAD

**Issue by MarcoLavoro** [InstaPy/InstaPy#6090]
## Expected Behavior
No error
## Current Behavior
I get this error after a few hours of work

```python
`Traceback (most recent call last):
  File "/home/ma/Desktop/sd/pagina gadget.py", line 310, in <module>
      session.interact_user_followers(random_targets, amount=amountIteraction, randomize=True)
  File "/home/ma/.local/lib/python3.8/site-packages/instapy/instapy.py", line 3159, in interact_user_followers
    validation, details = self.validate_user_call(person)
  File "/home/ma/.local/lib/python3.8/site-packages/instapy/instapy.py", line 1336, in validate_user_call
    validation, details = validate_username(
  File "/home/ma/.local/lib/python3.8/site-packages/instapy/util.py", line 344, in validate_username
    if number_of_posts < min_posts:
TypeError: '<' not supported between instances of 'NoneType' and 'int'`
```

## InstaPy configuration

amountIteraction=random.randint(100, 500)
session.interact_user_followers(random_targets, amount=amountIteraction, randomize=True)
 session.set_relationship_bounds(enabled=True,
                                    potency_ratio=-0.75,
                                    delimit_by_numbers=True,
                                    max_followers=1000,
                                    max_following=3000,
                                    min_followers=8,
                                    min_following=25,
                                    min_posts=10)

**Comment by elulcao** [comment]
Hello @MarcoLavoro 

Would you be willing to try the next little change?
in `util.py` replace with the snippet, to catch comparison between `None` and `int`
The user that could not be found is only shared in your traces, since we don't want to know
that name, it would be easy to give a try to this test-fix to handled the comparison for users
that cannot be queried via graphl.

The execution raises, because we didn’t expect to compare a None, but it actually was None

```python
        try:
            number_of_posts = getUserData(
                "graphql.user.edge_owner_to_timeline_media.count", browser
            )

            if max_posts:
                if number_of_posts > max_posts:
                    inap_msg = (
                        "Number of posts ({}) of '{}' exceeds the maximum limit "
                        "given {}\n".format(number_of_posts, username, max_posts)
                    )
                    return False, inap_msg
            if min_posts:
                if number_of_posts < min_posts:
                    inap_msg = (
                        "Number of posts ({}) of '{}' is less than the minimum "
                        "limit given {}\n".format(number_of_posts, username, min_posts)
                    )
                    return False, inap_msg
        except (WebDriverException, TypeError):  # Catch if number_of_posts is NoneType
            logger.error("~cannot get number of posts for username".format(username))
            inap_msg = "--> Sorry, couldn't check for number of posts of username: '{}'\n".format(
                username
            )
            return False, inap_msg
```
