### ISSUE TITLE
File could not be opened error when attempting to start session.

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#6093]
## Expected Behavior
Session parameters should be accepted and the program should proceed onto launching the web browser. (I must add that I am not very experienced nor very intelligent so please correct me if I am doing or saying something blatantly wrongly)
## Current Behavior
The program halts on the line "session = InstaPy(username=insta_username, password=insta_password, headless_browser=True)" with the error "file could not be opened"
## InstaPy configuration
latest version of InstaPy(0.6.13) on python 3.9.1. All requirements were installed. System is Mac Os Big Sur on a non m1 mac

**Comment by elulcao** [comment]
@Konstantinos24 

Im using Catalina and Python3.9 (virtualenv) and everything is fine,
could you share the STDOUT for the session, it would be easier to
understand the issue if you share more details about it.
In specific, I would like to know which file cannot be opened

```python
(venv3.9)  internet@imac  ~/GitHub/InstaPy   master  python --version
Python 3.9.1
(venv3.9)  internet@mac  ~/GitHub/InstaPy   master 
(venv3.9)  internet@mac  ~/GitHub/InstaPy   master  python internet.py
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/Users/internet/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-02-26 20:16:16] [internet]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-02-26 20:16:16] [internet]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-02-26 20:16:19] [internet]  - Internet Connection Status: ok
```

**Comment by ghost** [comment]
Based on the debug log I saw it seems the last operation the program made was trying to get geckodriver from github. I looked into the workspace directory and found that no executable for geckodriver was present. I proceeded to download it on my own an place it in the directory but the behaviour did not change. Could it be trying to open Geckodriver and be failing due to me improperly installing it?

**Comment by ghost** [comment]
another update, after I read on notarization (since I installed geckodriver through an browser) and performed it now I am getting a new error on the same line "module 'sys' has no attribute 'setcheckinterval'"

**Comment by elulcao** [comment]
If you see something like the following, it means the problem comes from the module sys. In this case instapy is consuming that module thru the Python3.9 interpreter. I guess there is something wrong with the module, I'm not sure...

```
sys.setcheckinterval(1)
AttributeError: module 'sys' has no attribute 'setcheckinterval'
```

Could you try running instapy with other python version like Python3.8?
It would be necessary to install python3.8, if it is not already installed in your machine. 
Finally, try with a virtual environment instead of installing the requirements in the OS.

**Comment by ghost** [comment]
Hi, sorry for forgetting to close this issue, it turns out that I had improperly installed gecko and firefox. After properly doing so, the program goes past that line but ends when trying to find the log in button. I am aware that this is an issue and I have been reading through other comments to find a solution.

**Comment by elulcao** [comment]
Happy to know that, thanks for confirmation 👍
