### ISSUE TITLE
Modify quickstart.py, run request before session

### ISSUE THREAD

**Issue by makiBaraba** [InstaPy/InstaPy#6098]
## Expected Behavior
Note -> I'm javascript developer, don't had experience with Python

In quickstart.py script, I added request to pull profile from some API

```
response = requests.get("http://127.0.0.1:3333/api/v1/internal/profiles/1")
profile = response.text

print(profile)
set_workspace(path="fullpath" + insta_username)
session = InstaPy(username=insta_username,password=insta_password,headless_browser=True)

with smart_run(session):
     session.follow_user_followers(['xxxx'], amount=10, randomize=False)
```

I expected to first execute request, then run Instapy session

## Current Behavior

Currently behavior is that first run instapy script, with INFO rows, follows profile followers and after that prints response and after that sets workspace

log me with this

**Comment by elulcao** [comment]
This is not an issue but a question for a customization,
