### ISSUE TITLE
Add "How to Do" Guides

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#61]
#### It would be nice to also have a full How to guide for the ubuntu platform, since it seems to be used more than CentOS.

- [x] Add a how to for ubuntu droplets
- [x] Add a how to for Windows host-machines

**Comment by timgrossmann** [comment]
@vlntdds Could you modify your CentOS guide to make it work for ubuntu?

**Comment by eduardocalazansjr** [comment]
Sure, will do a from-scratch setup guide today!

**Comment by timgrossmann** [comment]
@vlntdds Awesome!

**Comment by eduardocalazansjr** [comment]
#69, did it!

Will keep this open to do a complete guide to Windows.

**Comment by sugionodjojo** [comment]
hello,

if anyone can help, i am stuck with setup tools here, am not sure if the scripts works

pip instal . has no problem, but when I do python setup.py install, it looks for setuptools module , and no matter I add setuptools anywhere, the command simply does not work.

hope you guys can come up with solution here

**Comment by timgrossmann** [comment]
@sugionodjojo 

On Linux or OS X:
```bash
pip install -U pip setuptools
```

On Windows:
```bash
python -m pip install -U pip setuptools
```

**Comment by sugionodjojo** [comment]
@timgrossmann 

hi,

i am using ubuntu, so it will be linux,

tried pip install -U pip setuptools

it did install setuptools

and command python setup.py install run

return with 

File "setup.py", line 1, in <module>
from setuptools import setup
File "/Instapy/setuptools/__init__.py", line 12, in <module>
import setuptools.version
File "/Instapy/setuptools/version.py", line 1, in <module>
import pkg_resources
import error: No module named pkg_resources

is it correct if i look for documentation setuptools python, look for how to identify the version, then gedit version.py, change the script import pkg-resources into whatever the correct name on documentation to identify version?

regards,
Sugiono

**Comment by eduardocalazansjr** [comment]
Seems like you messed your python installation on this machine.

```
pip install --upgrade setuptools
pip install --upgrade distribute 
apt-get install --reinstall python-pkg-resources
wget https://bootstrap.pypa.io/ez_setup.py -O - | python
```

**Comment by sugionodjojo** [comment]
hello,

did all the above, last sentence was finished processing dependencies for setuptools==33.1.1

and when i input command python setup.py install
the result
File "/InstaPy/setuptools/__init__.py", line 13, in <module>
from setuptools.extension import Extension
File "/InstaPy/setuptools/extension.py", line 7, in <module>
from six.moves import map
ImportError: No module named six.moves

I did all the above you suggest under /InstaPy directory, is it correct? 

regards,
Sugi

**Comment by eduardocalazansjr** [comment]
You definitely have a messed python installation and dependencies on this machine.

Are you SURE that you have `python3-pip python3-dev build-essential` installed?
Are you SURE that they are not reffs for any virtualenv?
Are you SURE that you upgraded pip before running `pip install .`?

**Comment by sugionodjojo** [comment]
yes, i did follow the instruction to set up droplet , and did it till setup virtualenv

hmmm, how to clean it up?

python3-pip python3-dev build essential have been installed many times, under root directory, /InstaPy directory, and maybe virtualenv too

uninstall virtualenv will work?

regards,
Sugi

**Comment by sugionodjojo** [comment]
rm -rf venv ?
will enough?

regards,
Sugi

**Comment by sugionodjojo** [comment]
i remove virtualenv with the above command. then try to upgrade pip

the first command good
the second one, distribution, return with red letter, no version that satisfies the requirement.

is it easier to clean install all over again?

regards,
Sugiono

**Comment by sugionodjojo** [comment]
my bad, please ignore the above ( distribution) i forgot to write --upgrade

**Comment by sugionodjojo** [comment]
yes, that six.moves still a problem, please help me with command to clean up what i already mess up , if there is ?

if not then, maybe better to build another drop let and start all over again?

regards,
Sugiono

**Comment by sugionodjojo** [comment]
hello

yes, i did all over agian and it went smootly
i can do pip install .
i can also do python setup.py install

and then what to do next? i have edit the quickstart.py
and when read again all the comment from Timgrossmann, found i can do trick like python3.5 quickstart.py

which i did, and back with result 

Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 6, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named 'pyvirtualdisplay'

hmmm.....has anyone did this and how your working? i really dying to know 

regards,
Sugiono

**Comment by sugionodjojo** [comment]
forgot to include chromedriver, did it now
re-do all the upgrading, still pyvirtualdisplay is a problem, did search on internet , come up with checking pip version and virtualdisplay, and the result

Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/InstaPy/instapy/instapy.py", line 6, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named 'pyvirtualdisplay'
root@ubuntu-512mb-sgp1-01:/InstaPy# pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
root@ubuntu-512mb-sgp1-01:/InstaPy# pip list | grep pyvirtual
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
root@ubuntu-512mb-sgp1-01:/InstaPy# pip list | grep PyVirtual
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
PyVirtualDisplay (0.2.1)

any one can help / comment, please?
thanks
sugi

**Comment by sugionodjojo** [comment]
perhaps this is the reason?

root@ubuntu-512mb-sgp1-01:/# sudo -H pip3 install --upgrade pip
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

??

**Comment by timgrossmann** [comment]
@sugionodjojo This really is the wrong location to post this...

What language are you using?

**Comment by sugionodjojo** [comment]
Yeah, sorry about this.

"How to do " , i thought is the place to share experience installing InstaPy , turns out I have problem doing it with digitalocean droplet since python always go to 2.7 version although 3.5 installed, and no matter how i update pyvirtualdisplay,it always goes to python 2.7.

I even uninstall python 2.7, then update pip and pyvirtualdisplay, end up haveing problem with folder locale

I do not know how others cope with that....

**Comment by timgrossmann** [comment]
@sugionodjojo 

you can simply "force" it to use 3.5 by typing:

```bash
python3.5 quickstart.py
```

**Comment by sugionodjojo** [comment]
hello, 

am not sure if i can carry on on this thread, but I think it is useful for whoever want to try InstaPy

droplet digital ocean, USA server and singapore server, I have problem when updating pip3, that is why pyvisualdisplay always got problem.

the problem updating pip looks the same, unable to set locale, here is the exact result when i do 
root@ubuntu-512mb-nyc2-01:~# pip3 install --upgrade pip
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

let me know if I can send you email on the progress, or if i can publish progress here....

regards,
Sugiono

**Comment by eduardocalazansjr** [comment]
@sugionodjojo This really is the wrong location to post this [2].
The Ubuntu guide already have the locale settings, all properly tested in AWS and DO.

**Comment by timgrossmann** [comment]
Done by [7d0619f](https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Windows.md)
