### ISSUE TITLE
Question, can you control the browser? 

### ISSUE THREAD

**Issue by 123automator** [InstaPy/InstaPy#6100]
Is there a way to control the browser instapy is using? There is some things that instapy can not do like scraping and would like to make code myself to do that.

**Comment by elulcao** [comment]
Selenium is intended to automate browser actions, and yes you always code your own modulo for scraping users profile.
Tim has another repo if you want some inspiration:
[instagram-profilecrawl](https://github.com/timgrossmann/instagram-profilecrawl)
