### ISSUE TITLE
Error when I try to follow people. 

### ISSUE THREAD

**Issue by 123automator** [InstaPy/InstaPy#6101]
Code:
UserHashTag = 'user'
Session.follow_likers(UserHashTag, photos_grab_amount = 1, follow_likers_per_photo = 20, randomize=True, sleep_delay=10, interact=False)

Error:
Error occured while retrieving data.
    b'Message: The element reference of <main class="SCxLW uzKWK  CsONw"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed\n'

Not sure why this is happening would appreciate any help!

**Comment by elulcao** [comment]
Could you share the complete trace, couple of lines are not enough to understand where the issue comes from
feel free to mask the sensitive info.
