### ISSUE TITLE
Country / Region Specific Engagement

### ISSUE THREAD

**Issue by jsheadwebdev** [InstaPy/InstaPy#6102]
Is there a way to keep the bot's interactions within a specific country? I'm constantly seeing people from India while my business is conducted in America. Any help will be appreciated :)

**Comment by elulcao** [comment]
This is rather a question than an issue

Create an array for locations, check and save your favorite places from IG
 `locations = []`

Define the actions for locations :
`like_by_locations`
`comment_by_locations`
`follow_by_locations`

ie
```python
session.like_by_locations(
        random.sample(locations, random.randint(5, 10)),
        amount=random.randint(1, 5),
        media="all",
        skip_top_posts=False,
        randomize=True,
    )
```
