### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by lukzzhunter** [InstaPy/InstaPy#6103]
Traceback (most recent call last):
  File "PhishX.py", line 32, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'
i have pip 3

**Comment by elulcao** [comment]
Im afraid to said that InstaPy doesn't have any file called like `PhishX.py`
so, it means that's your own file. You need to install the dependencies or install InstaPy via `pip`

**Comment by TheResistanceAZ** [comment]
Traceback (most recent call last):
  File "../quickstart.py", line 2, in <module>
    from instapy import InstaPy
ImportError: No module named instapy
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
