### ISSUE TITLE
Could not pass the login A/B test. Trying last string...

### ISSUE THREAD

**Issue by SeironWP** [InstaPy/InstaPy#6104]
## Expected Behavior
After running the quickstart.py with valid credentials a successful login should happen.

## Current Behavior
INFO [2021-03-04 12:03:08] [...] Cookie file not found, creating cookie...
WARNING [2021-03-04 12:03:13] [...]  Login A/B test detected! Trying another string...
WARNING [2021-03-04 12:03:18] [...]  Could not pass the login A/B test. Trying last string...
...........................................................................................................................
CRITICAL [2021-03-04 12:03:57] [...]  Unable to login to Instagram! You will find more information in the logs above.

## Possible Solution (optional)
Something seems to Pop Up up in the browser window "Save login", "activate notifications" etc. I tried clicking manually.

## InstaPy configuration
Only credentials.

Edit: running on linux with pip install on python 3.9.1

**Comment by leonardozhe** [comment]
same issue.

**Comment by limberger** [comment]
same here!
