### ISSUE TITLE
Running Instapy on Windows Server with multiple sessions.

### ISSUE THREAD

**Issue by dillendillen** [InstaPy/InstaPy#6105]
**Hi there**

Im currently running Instapy on my windows server, I would like to run multiple sessions at once ( different accounts ofc )
I already tried to give every session a specific workspace directory, which fixed it partly, I can run 2 sessions but not 3, Something with the geckodriver I think..( You'll find my config below ) 

Also does someone has tips for ban safety? I use quotasupervisor but im not sure what the best setup is, during testing and making of this config I wasn't been able to like images with the bot anymore ( for 1 day ).

Also is there anyway we can add more commands for the telegram bot ?( I was thinking turning on and off the bot through telegram ) -> Shell bot?. And now every individual  has to make his own bot with fatherbot, Cant I make 1 bot, so different people could join and ask their report with /report?

**Thanks in advance!**

## InstaPy configuration
import random
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace
from instapy import get_workspace
from instapy import Settings
from instapy.plugins import InstaPyTelegramBot

set_workspace(path="C:\\Users\\Administrator\\InstaPy\\********\\")

# get a session!
session = InstaPy(username='*************', password='**************', multi_logs=True, headless_browser=True)
telegram = InstaPyTelegramBot(token='************************', telegram_username='DillenDillen', instapy_session=session)
telegram.send_message(text="*****************")

# let's go! :>
with smart_run(session):
    workspace_in_use = get_workspace()
    print(workspace_in_use["path"])
    hashtags = session.target_list("hashtags.txt")
    random.shuffle(hashtags)
    my_hashtags = hashtags[:10]

    # general settings

    # DO NOT LIKE
    session.set_dont_like(['sad', 'rain', 'depression', '#depression', '#selfhate', '#porn', '[gay'])

    # COMMENTS
    session.set_do_comment(enabled=True, percentage=60)
    session.set_comments([
                             u'Really nice! :thumbsup:',
                             u'Great work! :fire:',
                             u'Love it! :thumbsup:',
                             u'Great Post!',
                             u'you think of my recent photo?'],
                         media='Photo')
    
    session.set_do_like(True, percentage=100)
    # LIKE & COMMENT LIMITS
    session.set_delimit_liking(enabled=True, max_likes=5000, min_likes=0)
    session.set_delimit_commenting(enabled=True, max_comments=None, min_comments=2)
    session.set_relationship_bounds(enabled=True,
                                    potency_ratio=None,
                                    delimit_by_numbers=True,
                                    max_followers=9000,
                                    max_following=2500,
                                    min_followers=150,
                                    min_following=100,
                                    min_posts=6)
    # Skip users if 
    session.set_skip_users(skip_private=True,
                       private_percentage=100,
                       skip_no_profile_pic=True,
                       no_profile_pic_percentage=100,
                       skip_business=False,
		       skip_non_business=False,
                       business_percentage=0,
                       skip_business_categories=[],
                       dont_skip_business_categories=[],
                       mandatory_bio_keywords=[])
    
    # QUOTA SUPERVISOR 
    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "comments_d"],
                                 sleepyhead=True, stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes_hourly=200,
                                 peak_likes_daily=585,
                                 peak_comments_hourly=80,
                                 peak_comments_daily=182,
                                 peak_follows_hourly=48,
                                 peak_follows_daily=None,
                                 peak_unfollows_hourly=35,
                                 peak_unfollows_daily=402,
                                 peak_server_calls_hourly=None,
                                 peak_server_calls_daily=4700)

    session.set_user_interact(amount=1, randomize=True, percentage=100, media='Photo')

    # activity
    session.like_by_tags(my_hashtags, amount=15, interact=True, media='Photo')

**Comment by elulcao** [comment]
Geckodriver is like a link between selenium and Firefox, plus the Marionette that communicates with Firefox;
the flow could be explained like this:
Selenium -> WebDriver -> Geckodriver -> Marionette -> Firefox 

said that, you can figure out how to isolate a session agains other session when running at the same time, ie:

1. Using docker, Instapy-Docker
2. Using different path for the workspace, Firefox and geckodriver binary must be put in a different directory

You could run as many sessions the server can handle.

**Comment by dillendillen** [comment]
> Geckodriver is like a link between selenium and Firefox, plus the Marionette that communicates with Firefox;
> the flow could be explained like this:
> Selenium -> WebDriver -> Geckodriver -> Marionette -> Firefox
> 
> said that, you can figure out how to isolate a session agains other session when running at the same time, ie:
> 
> 1. Using docker, Instapy-Docker
> 2. Using different path for the workspace, Firefox and geckodriver binary must be put in a different directory
> 
> You could run as many sessions the server can handle.

thanks for the explanation !! Since I run it on my own Server I do not see the pro's in Instapy-Docker. 

I already gave each session a different workspace path ( Assest, DB, Logs ) so the geckodriver is in that workspace directory  but do every session needs its own firefox??

And any tips for my safety? cuz im running 4/5 accounts on the same IP.

**Comment by elulcao** [comment]
> > Geckodriver is like a link between selenium and Firefox, plus the Marionette that communicates with Firefox;
> 
> > the flow could be explained like this:
> 
> > Selenium -> WebDriver -> Geckodriver -> Marionette -> Firefox
> 
> > 
> 
> > said that, you can figure out how to isolate a session agains other session when running at the same time, ie:
> 
> > 
> 
> > 1. Using docker, Instapy-Docker
> 
> > 2. Using different path for the workspace, Firefox and geckodriver binary must be put in a different directory
> 
> > 
> 
> > You could run as many sessions the server can handle.
> 
> 
> 
> thanks for the explanation !! Since I run it on my own Server I do not see the pro's in Instapy-Docker. 
> 
> 
> 
> I already gave each session a different workspace path ( Assest, DB, Logs ) so the geckodriver is in that workspace directory  but do every session needs its own firefox??
> 
> 
> 
> And any tips for my safety? cuz im running 4/5 accounts on the same IP. 

The IP banning is something that you can control with a proxy. 
I forgot to mention that you can start bots 🤖 at different times, maybe one after each hour.

**Comment by dillendillen** [comment]
> > > Geckodriver is like a link between selenium and Firefox, plus the Marionette that communicates with Firefox;
> > 
> > 
> > > the flow could be explained like this:
> > 
> > 
> > > Selenium -> WebDriver -> Geckodriver -> Marionette -> Firefox
> > 
> > 
> > > 
> > 
> > 
> > > said that, you can figure out how to isolate a session agains other session when running at the same time, ie:
> > 
> > 
> > > 
> > 
> > 
> > > 1. Using docker, Instapy-Docker
> > 
> > 
> > > 1. Using different path for the workspace, Firefox and geckodriver binary must be put in a different directory
> > 
> > 
> > > 
> > 
> > 
> > > You could run as many sessions the server can handle.
> > 
> > 
> > thanks for the explanation !! Since I run it on my own Server I do not see the pro's in Instapy-Docker.
> > I already gave each session a different workspace path ( Assest, DB, Logs ) so the geckodriver is in that workspace directory  but do every session needs its own firefox??
> > And any tips for my safety? cuz im running 4/5 accounts on the same IP.
> 
> The IP banning is something that you can control with a proxy.
> I forgot to mention that you can start bots 🤖 at different times, maybe one after each hour.

Yes Im running 4 scripts now ( 2 scripts every 2-4hours ). Im not using proxies but may be I should... but I have bad experience with free proxies in the past.

Is there any advice on the minimum  settings for the quotasupervisor? and how many seconds break is the safest?

Also can I add more commands for the telegram bot? 

Ps. I saw that the Instapy dashboard was outdated. Would be nice if my friends were able to edit  couple things in a nice Interface. any suggestions ??
