### ISSUE TITLE
IMPORT ERROR(CIRCULAR IMPORT)

### ISSUE THREAD

**Issue by karolzky** [InstaPy/InstaPy#6106]
## Expected Behavior

Hello!
I succesfully installed the InstaPy, but I cant run it! 

## Current Behavior

When Im clicking windows_start file, the error occurs:
cannot import name 'InstaPy' from partially initialized module 'instapy' (most likely due to a circular import)

**Comment by elulcao** [comment]
check your imports since the Python interpreter detected the same module, that's normal and is user responsibility the correct configuration of their own constructor session.
