### ISSUE TITLE
Wrong behaviour while setting 'skip_bio_keyword'

### ISSUE THREAD

**Issue by amestoyg** [InstaPy/InstaPy#6111]
Function 'evaluate_mandatory_words' fails when passing an empty list. While setting 'skip_bio_keyword' to 'set_skip_users', 'evaluate_mandatory_words' gets called without a list and returns false, wrongly skipping users.

## Expected Behavior
The expected behavior should not 'evaluate_mandatory_words' if not mandatory words were setted.

## Current Behavior
While setting 'skip_bio_keyword' to 'set_skip_users', 'evaluate_mandatory_words' gets called without a list and returns false, wrongly skipping users.

## Possible Solution (optional)
Two alternatives:

1. Validate 'mandatory_bio_keywords' before calling 'evaluate_mandatory_words'
2. Change the function logic to return True when evaluating empty lists

**Comment by besheniy1983** [comment]
True

**Comment by besheniy1983** [comment]
i put an empty list and it works (mandatory_bio_keywords=[''])

**Comment by amestoyg** [comment]
That isn't an empty list but a list with an empty string, that's why it works. When it evaluates the text to this list (''.lower() in text) that's always True. It shouldn't evaluate for mandatory words if there aren't any setted.

**Comment by besheniy1983** [comment]
I agree.
