### ISSUE TITLE
Follow Followers 'amount' not working

### ISSUE THREAD

**Issue by y471n** [InstaPy/InstaPy#612]
`session.follow_user_followers(['user1'], amount=5, random=False)`

The follow users is not limiting at amount, it keeps following. Issue started after yesterday's merge.

**Comment by iSimonWeb** [comment]
I've had this issue before yesterday merge.
Seems to be a problem with the followers iteration.

**Comment by timgrossmann** [comment]
@BernardoGO

**Comment by nnvum** [comment]
I just wanted to add that "session.set_upper_follower_count()" is also ignored for all the following actions but is working for liking and commenting. This could possibly be related to the same underlying issue.

**Comment by gagankumr** [comment]
Same it isnt working for me either. Trying to findout what is the error and will update you guys

**Comment by dylancaponi** [comment]
@timgrossmann @BernardoGO maybe tests should be required for merges and claimed bounties?

**Comment by timgrossmann** [comment]
@dylancaponi Well, the feature worked. That's why the PR has been merged and the bounty paid out.
It's the same as with all the other features. 

Until there is a solution which does **not** rely on the page elements, stuff will break and has to be fixed again

**Comment by converge** [comment]
fixed at #805
