### ISSUE TITLE
instapy import error

### ISSUE THREAD

**Issue by avnitstwt** [InstaPy/InstaPy#6125]
![Screenshot (8)](https://user-images.githubusercontent.com/72193302/111871409-e5a4d880-89af-11eb-90ea-e7c99014f185.png)
I will facing the issue can anyone explain this 
and also i have using 
![Screenshot (7)](https://user-images.githubusercontent.com/72193302/111871408-e3427e80-89af-11eb-88a7-f216de97f73f.png)

**Comment by djalmaberaldo** [comment]
Have you installed Instapy with pip or pip3?

**Comment by Nocturnal-2** [comment]
@sarcasticccccc Looks like you have shared your password by mistake. Please change it!

**Comment by avnitstwt** [comment]
I will changed it
