### ISSUE TITLE
run multiple accounts .. idee ? 

### ISSUE THREAD

**Issue by Polkyanik** [InstaPy/InstaPy#6126]
hi guys, i have no idea if it's Out .. an idea how to run 2 accounts?
@elulcao I need your help ;)

**Comment by matcode1** [comment]
Hi Polkyanik,

You just have to select a diferent workspace:

session = set_workspace(path='C:\\Users\\Polkyanik\\PycharmProjects\\auto_insta_2\\')

Any questions please let me know.
