### ISSUE TITLE
To few comments error message

### ISSUE THREAD

**Issue by TheFoxStudio** [InstaPy/InstaPy#6129]
## Expected Behavior
to run the script
## Current Behavior
exits out with a message that there need to be 10 or more comments. There is 15 comments provided tho
## Possible Solution (optional)
The developer actually supporting his project instead of just collecting donations and bragging on Twitter about his great (not functioning) tool.
## InstaPy configuration
Base quickstart file

**Comment by manufao** [comment]
Hi,
I have the same issue, do you find a solution ?
