### ISSUE TITLE
Relationship tools cannot access my private account

### ISSUE THREAD

**Issue by adlrwbr** [InstaPy/InstaPy#6130]
## Expected Behavior
The bot should grab my private account's followers and store to local file.
## Current Behavior
Even though the session is instantiated with my username and password, the bot fails and exits. This error affects functions `grab_followers()`, `grab_following()`, `pick_nonfollowers`, etc. The bot works correctly if my profile is public.
```
INFO [2021-03-26 20:07:27] [myUsername]  Starting to get the `Followers` data..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2021-03-26 20:07:27] [myUsername]  Retrieving live "Followers" data of myUsername at "full" range
INFO [2021-03-26 20:07:27] [myUsername]  This user is private and we are not following
```
## InstaPy configuration
Firefox, Ubuntu. Tested both the pip3 install and the git clone.
### Code
```
def main():
    insta_username = 'myUsername'
    insta_password = input("enter password: ")

    session = InstaPy(username=insta_username,
                    password=insta_password,
                    headless_browser=False)

    with smart_run(session):
        followers = session.grab_followers(username=insta_username, amount="full", live_match=True, store_locally=True)
```

**Comment by lucianolacurcia** [comment]
This is not working, I am trying to grab following and followers of my own account and it says  "This user is private and we are not following"... any idea?
