### ISSUE TITLE
Commenting based on the number of existing likes an Instagram post has

### ISSUE THREAD

**Issue by sasan007** [InstaPy/InstaPy#6131]
I would like to know that is there any way to put a comment in an Instagram post based on the number of existing likes?

I've read the `instapy `document there was a function which commenting based on the number of existing comments a post has, but this is not what I want (for example):

> session.set_delimit_commenting(enabled=True, min_comments=100, max_comments=200)

What I need exactly is commenting based on the number of existing **likes** a post has.

**Comment by Nocturnal-2** [comment]
It would be nice to have this feature!
