### ISSUE TITLE
Settings to ignore accounts with a higher number of follows?

### ISSUE THREAD

**Issue by DerLomo** [InstaPy/InstaPy#6136]
How I could set the script to ignore liking, following and commenting post of accounts with more than X follows or followers?

**Comment by filiperivelli** [comment]
Try to read this documentation
https://instapy.org/settings#interactions-based-on-the-number-of-followers-andor-following-a-user-has


E.g:
`session.set_relationship_bounds(enabled=True,
                                potency_ratio=1.34,
                                delimit_by_numbers=True,
                                max_followers=8500,
                                max_following=4490,
                                min_followers=100,
                                min_following=56,
                                min_posts=10,
                                max_posts=1000)`
