### ISSUE TITLE
Ensure duplicate likes do not take place

### ISSUE THREAD

**Issue by Glyphism** [InstaPy/InstaPy#6138]
## Current Behavior
When liking followers of a specific user, over multiple sessions, I can't tell if InstPay is ever revisiting the same account and duplicating its likes.

## Possible Solution (optional)
Ideally, a setting that allows this to be set to true or false in the script. ie, do not ever visit the same follower of a user twice.

## InstaPy configuration
Running on a Mac in non-headless mode.

**Comment by jldmorris** [comment]
Hi great idea! Can you let me know if the bot is still working for you? Mine keeps getting me banned lol.
