### ISSUE TITLE
My bot isn't going to sleep after liking

### ISSUE THREAD

**Issue by jldmorris** [InstaPy/InstaPy#6139]
## Expected Behavior
After I set my login information, which I'm not sharing for confidentiality here (lol), I set parameters to have my bot go to sleep after every like. 
## Current Behavior

The log show it's not going to sleep, it also displays the like number as "x/19" and not "x/10" which it should display, if I am understanding this correctly, sorry, I'm new!

## Possible Solution (optional)

I have a feeling it has something to do with my indentation or where I placed the code.

## InstaPy configuration

with smart_run(session):

    # activity
    session.like_by_tags(["like4like"], amount=10)

    session.set_quota_supervisor(enabled=True,
                                 sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"],
                                 sleepyhead=True,
                                 stochastic_flow=True,
                                 notify_me=True,
                                 peak_likes_hourly=10,
                                 peak_likes_daily=245,
                                 peak_comments_hourly=21,
                                 peak_comments_daily=182,
                                 peak_follows_hourly=48,
                                 peak_follows_daily=None,
                                 peak_unfollows_hourly=35,
                                 peak_unfollows_daily=402,
                                 peak_server_calls_hourly=None,
                                 peak_server_calls_daily=500)

    session.set_action_delays(enabled=True,
                              like=3,
                              comment=5,
                              unfollow=28,
                              story=10)

**Comment by doxmey** [comment]
with smart_run(session):

session.set_quota_supervisor(enabled=True,
                             sleep_after=["likes", "comments_d", "follows", "unfollows", "server_calls_h"],
                             sleepyhead=True,
                             stochastic_flow=True,
                             notify_me=True,
                             peak_likes_hourly=10,
                             peak_likes_daily=245,
                             peak_comments_hourly=21,
                             peak_comments_daily=182,
                             peak_follows_hourly=48,
                             peak_follows_daily=None,
                             peak_unfollows_hourly=35,
                             peak_unfollows_daily=402,
                             peak_server_calls_hourly=None,
                             peak_server_calls_daily=500)

session.set_action_delays(enabled=True,
                          like=3,
                          comment=5,
                          unfollow=28,
                          story=10)

# activity
session.like_by_tags(["like4like"], amount=10)


its read from top to bottom so your conditions were never set. try it now
