### ISSUE TITLE
Cannot detect post media type. Skip https://www.instagram.com

### ISSUE THREAD

**Issue by rajbreno** [InstaPy/InstaPy#6144]
from instapy import InstaPy

session = InstaPy(username='xxxxxxxx', password='xxxxxxxx', headless_browser=True)
session.login()
session.set_action_delays(enabled=True, like=120)
session.set_user_interact(amount=3, randomize=True, percentage=100)
session.like_by_tags(['car'], amount=500, interact=True )
session.end()

**Comment by Xeone971** [comment]
me too

**Comment by emiraxxxz** [comment]
Me too

**Comment by mniik** [comment]
well, i have the same issue, it's been there for a while, i don't know if this issue exists since beginning or not, i think it's about post_href in like_util, when instapy try to grab posts, the find_element_by_xpath is not functioning correctly. some url are being ignored and throwing exception.
possible solution: fix url

**Comment by doxmey** [comment]
apparently it's something with the posts that have multiple photos in it and possibly videos.

**Comment by Disembodied** [comment]
Had the same issue and took me some time to figure out.

The issue is because the like_util.py has been changed. A pull request has already been made by user @BitCode-in in #6143 

Change the file as described in his request and you should be fine.

**Comment by RoyalSix** [comment]
> Had the same issue and took me some time to figure out.
> 
> The issue is because the like_util.py has been changed. A pull request has already been made by user @BitCode-in in #6143
> 
> Change the file as described in his request and you should be fine.

How do I change this file? Should I clone the repo or can I change it locally from the pip install

**Comment by rajbreno** [comment]
Hi @Disembodied,

Now it is working locally as I have edited the file you mentioned above but how can I edit this file "like_util.py" on the Ubuntu server?

I am unable to locate this file? do you know anything about it?

**Comment by BitCode-in** [comment]
Hi @rajbreno 
You should find the "python3/site-packages/" folder and find the instapy module there. Then edit the "like_util.py" file.

**Comment by rajbreno** [comment]
> Hi @rajbreno
> You should find the "python3/site-packages/" folder and find the instapy module there. Then edit the "like_util.py" file.

Thanks @BitCode-in 
can you please reverse change your code in this repository?

**Comment by rajbreno** [comment]
Hi @BitCode-in 

showing this output while locating the site pakages:

"-bash: cd: python3/site-packages/: no such file or directory"

**Comment by BitCode-in** [comment]
I can't change this repository. Your python3 folder may be located in /usr/bin/python3/site-packages/. Also try the "which python3" command. More precisely, I can not tell you because I do not fully use linux

**Comment by rajbreno** [comment]
> I can't change this repository. Your python3 folder may be located in /usr/bin/python3/site-packages/. Also try the "which python3" command. More precisely, I can not tell you because I do not fully use linux

This is the exact location: cd /usr/local/lib/python3.8/dist-packages/instapy/

Thank you very much for your hint.

**Comment by filiperivelli** [comment]
> apparently it's something with the posts that have multiple photos in it and possibly videos.

Here the problem is this.

**Comment by Marcaveli** [comment]
I am having the same issue, running locally. I changed the like_util.py per the #6143 and I still am getting the same problem. Any and all advice is welcome.

**Comment by philipesantos136** [comment]
Same problem, I already did #6143 , but it didn't solve for me.

**Comment by pedinil** [comment]
i have same problem it after chaning the like_util.py it keep crashing please help

**Comment by schealex** [comment]
Can u guys try using my develop branch? It's working fine for me. Let me know if I need to do a PR for changes I have on my fork still


pip install -I https://github.com/schealex/InstaPy/zipball/develop

**Comment by filiperivelli** [comment]
I'm using the master branch of InstaPy and made these changes #6202  by hand.
It's working fine.

**Comment by pedinil** [comment]
> Can u guys try using my develop branch? It's working fine for me. Let me know if I need to do a PR for changes I have on my fork still
> 
> pip install -I https://github.com/schealex/InstaPy/zipball/develop



> Can u guys try using my develop branch? It's working fine for me. Let me know if I need to do a PR for changes I have on my fork still
> 
> pip install -I https://github.com/schealex/InstaPy/zipball/develop

dear thank it is working with this version

**Comment by RaspberryPiZero** [comment]
> Can u guys try using my develop branch? It's working fine for me. Let me know if I need to do a PR for changes I have on my fork still
> 
> pip install -I https://github.com/schealex/InstaPy/zipball/develop

Thank you so much. It is finally working! How did you make it? Why is not your version still not featured in the official one?

**Comment by kelvinnlois** [comment]
> Can u guys try using my develop branch? It's working fine for me. Let me know if I need to do a PR for changes I have on my fork still
> 
> pip install -I https://github.com/schealex/InstaPy/zipball/develop

Thanks man. This really works for me.

**Comment by iusupovaav** [comment]
Hi, @kelvinnlois 
Could you help me? I don't understand, what I have to do with this command "pip install -I https://github.com/schealex/InstaPy/zipball/develop". I have to run it in Terminal?
