### ISSUE TITLE
Error, unable to determine correct filename for 64bit macos

### ISSUE THREAD

**Issue by newborngeek** [InstaPy/InstaPy#6145]
This message I get when try to launch my InstaPy bot.
Workspace in use: "/Users/***********/InstaPy"
Error, unable to determine correct filename for 64bit macos

Installed Java updated
New geckodriver set in the same folder (yesterday worked fine)

**Comment by newborngeek** [comment]
> This message I get when try to launch my InstaPy bot.
> Workspace in use: "/Users/***********/InstaPy"
> Error, unable to determine correct filename for 64bit macos
> 
> Installed Java updated
> New geckodriver set in the same folder (yesterday worked fine)

FIXED!!!!!!!
use `brew install gekodriver`

And whoala! Work as a charm!

**Comment by Glyphism** [comment]
Mine is also doing this and remains broken. When I enter the fix above for `brew install gekodriver` I get 

```
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "gekodriver".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

This is all very weird. My InstaPy was working fine a couple of days ago. No changes on my end, and then I ran out today and hit this '64bit macOS' error issue

**Comment by tjirku** [comment]
@Glyphism, @newborngeek Same here - I didn't update my MacOS nor any other related software - Instapy worked well, suddenly I keep getting an error  when running my python script - "Error, unable to determine correct filename for 64bit macos" running in conda envs with Python 3.8.8.

really weird ... 
any more hints ?

Addon: I **can confirm** that running "brew install geckodriver" **_resloved_** the issue and my instapy script is running fine now again - but still wondering what has caused the issue ?

**Comment by Glyphism** [comment]
@tjirku I can confirm that I got it working again. I had inadvertently copy/pasted "brew install gekodriver" from @newborngeek  post, without realising there was a typo in it. When I tried it again, with correct spelling ("brew install geckodriver"), InstaPy started working again. This looks to fix it.
