### ISSUE TITLE
'<' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#6146]
## Expected Behavior
it is a work in progress, focus on the follow task
it is supposed to just follow the followers of the username i input there
## Current Behavior
it hits me with Sorry, an error occurred: '<' not supported between instances of 'int' and 'str'
## Possible Solution (optional)
something to do with the name variable, i tried everything concerning the string, still not working
## InstaPy configuration
from instapy import InstaPy
import random

name = str(input('username?: '))
amount = random.uniform(10, 20)

from creds import username
from creds import password
session = InstaPy(username= str(username), password= str(password))
session.login()

print("DO NOT TERMINATE THE TASK")

session.follow_user_followers([str(name)], amount="full", randomize=False, sleep_delay=float(amount))

session.end()

**Comment by ghost** [comment]
bump for the bot
i have a fork of instapy, ill look into the issue and try fixing it, no guarantees tho
https://github.com/valentino1337/InstaPy/

**Comment by trascenderglobal** [comment]
@ghost 

> bump for the bot i have a fork of instapy, ill look into the issue and try fixing it, no guarantees tho https://github.com/valentino1337/InstaPy/

Could you solved?
