### ISSUE TITLE
RuntimeError: Error, unable to determine correct filename for 64bit macos

### ISSUE THREAD

**Issue by newborngeek** [InstaPy/InstaPy#6157]
## Expected Behavior
Open Firefox and start Instagram 
## Current Behavior
Error, unable to determine correct filename for 64bit macos
Traceback (most recent call last):
  File "/Users/mykhailo/Desktop/Instabot/instapy1.py", line 11, in <module>
    session = InstaPy(username=insta_username,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit macos

**Comment by giacomo-galletti** [comment]
Same issue

**Comment by Sebadier** [comment]
For some reason the browser.py does not find the geckodriver. 
A temporary workaround for this is to change line 32 of the browser.py and add the absolute path to the geckodriver
gecko_path = "[YOU ABSOLUTE PATH HERE]"

But this is a really quick and dirty fix that will break with the next update.

You might also have to manually download the latest gocko driver from https://github.com/mozilla/geckodriver/releases and put it into your ./assets/gecko/##.# folder. Then soft link the ./assets/geckodriver to the latest geckodriver in the subfolder of the latest version that you just downloaded.

**Comment by newborngeek** [comment]
> For some reason the browser.py does not find the geckodriver.
> A temporary workaround for this is to change line 32 of the browser.py and add the absolute path to the geckodriver
> gecko_path = "[YOU ABSOLUTE PATH HERE]"
> 
> But this is a really quick and dirty fix that will break with the next update.
> 
> You might also have to manually download the latest gocko driver from https://github.com/mozilla/geckodriver/releases and put it into your ./assets/gecko/##.# folder. Then soft link the ./assets/geckodriver to the latest geckodriver in the subfolder of the latest version that you just downloaded.

I have gecko driver in the same folder as my script and on another machine it is working fine. I'll try your solution. Thank you

**Comment by Sebadier** [comment]
Ok, great. Let me know if it works. For my Catalina system it worked.

**Comment by newborngeek** [comment]
It works on Big Sur version 11.2.3

**Comment by bencherkihamza** [comment]
So, you replace the line 32 with the gecko_path ?
You deleted this line gecko_path = shutil.which("geckodriver") or shutil.which("geckodriver.exe") and you replaced it with the gecko_path ?

**Comment by Sebadier** [comment]
Exactly. You replace the line with:

gecko_path = "[YOUR ABSOLUTE PATH HERE]"

And of course your put your actual path to the geckodriver inside the quotation marks.

**Comment by bencherkihamza** [comment]
I did that :
    gecko_path = "/Users/mac/InstaPy/assets/gecko/v0.29.1/geckodriver-v0.29.1-macos-aarch64/geckodriver"

Now, i have this error :

File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by bencherkihamza** [comment]
> Exactly. You replace the line with:
> 
> gecko_path = "[YOUR ABSOLUTE PATH HERE]"
> 
> And of course your put your actual path to the geckodriver inside the quotation marks.

Could you please help me with this issue ?

**Comment by newborngeek** [comment]
Here is what I did and everything work fine for me

`brew install geckodriver`
