### ISSUE TITLE
Time out while creating cookie - so login not working

### ISSUE THREAD

**Issue by Sebadier** [InstaPy/InstaPy#6158]
INFO [2021-04-19 12:31:56] []  - Cookie file not found, creating cookie...
INFO [2021-04-19 12:32:40] []  Timed out with failure while explicitly waiting until visibility of element located!

This is probably to a change in the Instagram cookie dialogue. It says "Accept coockies from Instagram on this browser"
and gives two options:
"Accept All" 
"Manage Data Settings"

So I guess the xpaths have to be updated for the login_util to find the proper button to click on.

Anyone else experiencing these problems?

**Comment by caskednow** [comment]
@Sebadier I experience the same issue. This is the most annoying problem recently as it excludes the possibility of running headless. Xpath update should be enough to handle this.

**Comment by leonardozhe** [comment]
i met the same issue.

**Comment by manufao** [comment]
Hi, I met the same issue 😞

**Comment by Tr1pke** [comment]
had the same, manual accept fix the problem

**Comment by tonystam** [comment]
Hello! Having the same issue

**Comment by tonystam** [comment]
Found a solution provided by @Artanox in the issue #6163. You just need to open the login_util.py with your favourite editor and paste the code below right after this: 

ig_homepage = "https://www.instagram.com"
web_address_navigator(browser, ig_homepage)

(for me i had to paste the code around the line 245) The code you need to paste is:

for element in browser.find_elements_by_tag_name('button'):
        if element.text.strip().lower() == 'accept all':
            element.click()
            break

Thank you very much to @Artanox for this fix :)

**Comment by Matduke** [comment]
The Xpath has not been updated but you can stretch the window to load the old UI and it will work. Then it will connect afterwards without worry ! So, if someone know where is the xPath address on the code, I can update it for you.
