### ISSUE TITLE
You have too few comments, please set at least 10 distinct comments to avoid looking suspicious

### ISSUE THREAD

**Issue by manufao** [InstaPy/InstaPy#6165]
## Expected Behavior
Run quickstart.py  found in instapy-quickstart repository

## Current Behavior
I have an issue when I run it : 
`You have too few comments, please set at least 10 distinct comments to avoid looking suspicious `

## InstaPy configuration
InstaPy Version: 0.6.13

**Comment by JacksonHoggard** [comment]
I just ran the script for myself and I don't seem to be having this issue. How are you running the code? That may be how you got to this error.

Did you run it in the terminal like this?
`python python quickstart.py --username abcd --password 1234`

 or did you add to the code in quickstart.py? If you did you may be able to fix it by adding this to your code
```
photo_comments = ['Nice shot! @{}',
        'Awesome! @{}',
        'Cool :thumbsup:',
        'Just incredible :open_mouth:',
        'What camera did you use @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Nice @{}',
        ':raised_hands: Yes!',
        'I can feel your passion @{} :muscle:',
        'Very Cool @{}',
        'This is awesome @{}']

session.set_comments(photo_comments, media = 'Photo')
```
As referenced in issue #5381. And then obviously you can replace the comments with whatever you want.

**Comment by manufao** [comment]
Hi @JacksonHoggard,

thanks for your help. I entered my credentials in the quickstart.py and after I run the command `python3 quickstart.py`.
I tried also with flag `--username` and `--password` but I have the same error.

Yeah I saw this topic and I added the parameter `media =  'Photo'`, but nothing happens. 

After investigation the problem is related to the function `join_pods()` and also `set_comments()`.  In Instapy.py file at this [line](https://github.com/timgrossmann/InstaPy/blob/master/instapy/instapy.py#L180) there are 3 comments defined and after [here](https://github.com/timgrossmann/InstaPy/blob/master/instapy/instapy.py#L5915) when we compare comments list length the result is 3 and not 12 (if I retrieve your comments list above). So the function `set_comment()` not update the `self.comments` variable.

I am not a python developer, so I continue to search. But I wanted to know if anyone else had the same problem and the solution.

**Comment by JacksonHoggard** [comment]
Very interesting. Considering that this issue is fairly common I wonder how it has gone unfixed/unnoticed for so long.

**Comment by manufao** [comment]
It's weird. You tell me that it works for you, how did you get instapy ? by cloning the project or with pip install instapy ?

**Comment by manufao** [comment]
Yeah, I don't know why I have this issue and for all it seems to work perfectly 😕

**Comment by wesguirra** [comment]
Any lucky on this issue?

**Comment by AurelTBE** [comment]
Any solution ?
