### ISSUE TITLE
Can this tool access my user settings and let me change my registration email?

### ISSUE THREAD

**Issue by osher1515** [InstaPy/InstaPy#6167]
## Expected Behavior
Can this tool access my user settings and let me change my registration email?
## Current Behavior
Can this tool access my user settings and let me change my registration email?

**Comment by Lrnvrybthksa** [comment]
It doesn't look like it can, it's more for interacting with users and their posts

**Comment by osher1515** [comment]
Can I get the OTP code using this tool?
