### ISSUE TITLE
Hide Selenium Extension: Error (Instapy location Linux)

### ISSUE THREAD

**Issue by froehlicht** [InstaPy/InstaPy#6169]
Where are the instapy files located on Ubuntu? I having problems finding them. I want to edit browser.py to fix the 'Hide Selenium Extension: Error' like here:

"I've faced the same issue a couple hours ago and then, found an alternative way to hide selenium webdriver on Firefox. To do that, some preferences on Firefox should be added in browser.py file.
You can try to extend your code with the script between ADDED tags -it's under the set_selenium_local_session function- to hide selenium and, also to change the browser platform to iPhone. Another platform might be needed if you use different user agents.

This setting is working on me for now but not sure if it's a temporary solution or not. So, let me know about the results on you."

```
    # mute audio while watching stories
    firefox_profile.set_preference("media.volume_scale", "0.0")

    # ADDED
    firefox_profile.set_preference('dom.webdriver.enabled', False)
    firefox_profile.set_preference('useAutomationExtension', False)
    firefox_profile.set_preference('general.platform.override', 'iPhone')
    firefox_profile.update_preferences()
    # ADDED

    # prefer user path before downloaded one
    driver_path = geckodriver_path or get_geckodriver()
    browser = webdriver.Firefox(
        firefox_profile=firefox_profile,
        executable_path=driver_path,
        options=firefox_options)
```

_Originally posted by @eemektas in https://github.com/timgrossmann/InstaPy/issues/5304#issuecomment-626371289_

**Comment by froehlicht** [comment]
usr/local/lib/python3.9/dist-packages/instapy

**Comment by evertonramires** [comment]
Still getting same error, using instapy 0.6.13. checked browser.py, indeed it has theses added lines, but still getting hide selenium error.

**Comment by dzaczek** [comment]
Same issue on 0.6.13   in this version you workaround  i found in file  browser.py  

@lab:~$ python3 cronbot.py 
I got the lock
InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/ace/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-05-26 21:04:04] [ace]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-05-26 21:04:04] [ace]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-05-26 21:04:05] [ace]  - Internet Connection Status: ok
INFO [2021-05-26 21:04:05] [ace]  - Current IP is "82.198.121.5" and it's from "Switzerland/CH"
INFO [2021-05-26 21:04:05] [ace]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-05-26 21:04:05] [ace]  - window.navigator.webdriver response: True
WARNING [2021-05-26 21:04:05] [ace]  - Hide Selenium Extension: error
INFO [2021-05-26 21:04:08] [ace]  - Cookie file not found, creating cookie...
.............................................................
INFO [2021-05-26 21:04:51] [ace]  Logged in successfully!

**Comment by Mansitos** [comment]
Same problem...

**Comment by dzaczek** [comment]
@Mansitos & @GypsyRobot  I found workaround just  installed  older version ff
```
root@lab:~# apt-cache show firefox | grep Version
Version: 89.0+build2-0ubuntu0.20.04.2
Version: 75.0+build3-0ubuntu1
sudo apt-get install firefox=75.0+build3-0ubuntu1
sudo apt-mark hold firefox

```

**Comment by sherxyar** [comment]
> @Mansitos & @GypsyRobot I found workaround just installed older version ff
> 
> ```
> root@lab:~# apt-cache show firefox | grep Version
> Version: 89.0+build2-0ubuntu0.20.04.2
> Version: 75.0+build3-0ubuntu1
> sudo apt-get install firefox=75.0+build3-0ubuntu1
> sudo apt-mark hold firefox
> ```

how can I make this work for windows? ~i'm new to this all :P

**Comment by dzaczek** [comment]
> > @Mansitos & @GypsyRobot I found workaround just installed older version ff
> > ```
> > root@lab:~# apt-cache show firefox | grep Version
> > Version: 89.0+build2-0ubuntu0.20.04.2
> > Version: 75.0+build3-0ubuntu1
> > sudo apt-get install firefox=75.0+build3-0ubuntu1
> > sudo apt-mark hold firefox
> > ```
> 
> how can I make this work for windows? ~i'm new to this all :P

Hi I have no clue how it works on windows  but I believe you need to install older version of Firefox  for example 75.
Ps. 
 Hot Linux virtual machines waiting for you pc.
