### ISSUE TITLE
Error: DLL load failed while importing _regex

### ISSUE THREAD

**Issue by gustafsom** [InstaPy/InstaPy#6170]
Hi Guys, I'm looking to go back to using Instapy.
But when I go to execute the error occurs:
"ImportError: DLL load failed while importing _regex: The specified module could not be found."

I already downloaded the DLL Regex, and put it in the System32 folder and in the Instapy folder.
I uninstalled and installed the latest python again.
But unfortunately the error keeps showing up.
Does anyone know what may be happening?

Python: 3.9.4
Win 10 - x64

**Comment by Lrnvrybthksa** [comment]
Have you tried running through quickstart.py or cli?

**Comment by gustafsom** [comment]
> Have you tried running through quickstart.py or cli?

Hi Irnvrryth
Trying running quickstart.py

**Comment by Lrnvrybthksa** [comment]
Ok, could you please post the stack trace?

maybe try adding the location to the system path.
