### ISSUE TITLE
 Cannot detect post media type

### ISSUE THREAD

**Issue by blader445** [InstaPy/InstaPy#6172]
I get a cannot detect post media type problem. How to bypass this? Thanks in advance.

**Comment by heyanilthakur** [comment]
same error.

**Comment by Ayub-Khan** [comment]
https://github.com/timgrossmann/InstaPy/pull/6143/files

**Comment by Lrnvrybthksa** [comment]
I think it's because of igtv and/or reels, maybe it has a different label type

**Comment by philipesantos136** [comment]
I am experiencing the same problem, even after change #6143.

**Comment by keeblebogdan** [comment]
Modified as per #6143, still doesn't work
