### ISSUE TITLE
New to IstaPy. No Coder. Can I have multiple instagram accounts?

### ISSUE THREAD

**Issue by AVwebcss** [InstaPy/InstaPy#6184]
Hello,

I just discovered instapy and installed on my Mac.
I still didn't configure as I need to find tutorials to do so.
I just want to be able to like posts with certain hasghtags with some criteria.
I saw the documentation and I noticed all the possible configs that can be made to create laser target solutions.
I also saw that there are templates already made to easily set up the processes.
As I have multiple accounts for different topics, it is possible to have multiple bots running?
I am not a coder at all so if you can reply with that in mind I'll appreciate.
Thank you.

**Comment by conradios** [comment]
Yes. You can use as many accounts as u want, just dupe the InstaPy folder and change the account login in the script

**Comment by AVwebcss** [comment]
> Yes. You can use as many accounts as u want, just dupe the InstaPy folder and change the account login in the script

Thank you!
What script I should use? Where I can find the template?
Also, instead of changing the login, can I add more, so they run simultaneously?
Thank you
