### ISSUE TITLE
Follow by tags doesn't work anymore

### ISSUE THREAD

**Issue by Invochu** [InstaPy/InstaPy#6189]
## Current Behavior
The follow button above a post has disappeared since 21/05. Which the bot uses to follow users.

## Possible Solution (optional)
Solution would be to use the follow button on a user his profile instead.

**Comment by itssmaxy** [comment]
Same for me, would love if someone had a solution to this

**Comment by jjuchara** [comment]
Yep, same for me. Maybe someone can help with this?

**Comment by tomnewg** [comment]
same for me! I tried a few fixes such as #5298 but don't seem to get it to work

**Comment by dragu95** [comment]
Does not work for me, too.
Following through "main" profile page works (e.g. follow through followers method).
Hoping for a fast solution!

**Comment by Invochu** [comment]
> Does not work for me, too.
> Following through "main" profile page works (e.g. follow through followers method).
> Hoping for a fast solution!

Might have to try this for the time being. Is it the function to follow someones else followers?

**Comment by dragu95** [comment]
> > Does not work for me, too.
> > Following through "main" profile page works (e.g. follow through followers method).
> > Hoping for a fast solution!
> 
> Might have to try this for the time being. Is it the function to follow someones else followers?

e.g. session.follow_user_followers(['accountname'],
                                  amount=ammount_number, randomize=False,
                                  interact=True, sleep_delay=240)

**Comment by BitCode-in** [comment]
Hi, this should help https://github.com/timgrossmann/InstaPy/pull/6190

**Comment by dragu95** [comment]
> Hi, this should help #6190

Is it working or just a suggestion?

**Comment by BitCode-in** [comment]
> 
> 
> > Hi, this should help #6190
> 
> Is it working or just a suggestion?

Working!

**Comment by schealex** [comment]
See PR #6195 for WIP fix

**Comment by dragu95** [comment]
> See PR #6195 for WIP fix

Does it work 100%? 
It is not approved yet.

**Comment by schealex** [comment]
@dragu95 just test it yourself? It's working for me and the liking part is at least working for one other user that has tested it. I've not gotten any other feedback jet.

**Comment by dragu95** [comment]
> @dragu95 just test it yourself? It's working for me and the liking part is at least working for one other user that has tested it. I've not gotten any other feedback jet.

The thread is not about the linking part. Please read before posting random stuff and suggest it as a solution.

**Comment by schealex** [comment]
@dragu95 Noone is forcing you to use it. But as I said for me it's working fine. As I'm using it exclusively to follow, like and comment bei tag. But do as you wish 🤷‍♂️🙄

**Comment by itssmaxy** [comment]
@schealex Your fix didn't work for me when it comes to following

**Comment by schealex** [comment]
@itssmaxy have you tried my develop branch which also includes my other PR about this? I'm using it daily and it works flawless. Many others too.

**Comment by itssmaxy** [comment]
@schealex Basically what I did was use your instapy folder instead of mine

**Comment by schealex** [comment]
@itssmaxy which branch though? My master is the same as here. You need to use the develop branch. Easiest way is:

pip install -I https://github.com/schealex/InstaPy/zipball/develop
To ensure you have done it correctly check the version after running instapy it should say "InstaPy Version: 0.6.14-AS"
