### ISSUE TITLE
Like_by_tags gives error  media = post_page[0]["shortcode_media"] KeyError: 0

### ISSUE THREAD

**Issue by alokkumarsbg** [InstaPy/InstaPy#6191]
Hello All,

Facing issue while running like_by_tags function

Traceback (most recent call last):
  File "instagram.py", line 29, in <module>
    session.like_by_tags(['songs'],amount=2,interact=True,skip_top_posts=False)
  File "C:\Users\test\AppData\Local\Programs\Python\Python38\lib\site-packages\instapy\instapy.py", line 1939, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\test\AppData\Local\Programs\Python\Python38\lib\site-packages\instapy\like_util.py", line 634, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

The code below in line 570 of like_util.py is not reading the post. The issue has reoccured which i think was fixed in 2019.
Value of variable post_page is {}

# Check if the Post is Valid/Exists
    try:
        post_page = browser.execute_script(
            "return window.__additionalData[Object.keys(window.__additionalData)[0]].data"
        )

**Comment by ghost** [comment]
Hello,

I am also experiencing the same issue when running the like_by_feed function too. I'm not sure if it is related to this issue but I am seeing the same error code from the same try/catch function. Below is the Traceback.

```
Traceback (most recent call last):
    File "/home/pi/FW-Bot.py", line 26, in interact_by_feed
        session.like_by_feed(amount=posts_in_feed, randomize=False, unfollow=False, interact=False)
    File "/usr/local/lib/python3.7/dist-packages/instapy/instapy.py", line 3922, in like_by_feed
        for _ in self.like_by_feed_generator(amount, randomize, unfollow, interact):
    File "/usr/local/lib/python3.7/dist-packages/instapy/instapy.py", line 4039, in like_by_feed_generator
        self.logger,
    File "/usr/local/lib/python3.7/dist-packages/instapy/like_util.py", line 633, in check_link
        media = post_page[0]["shortcode_media"]
    KeyError: 0
```

I'm not sure what might be causing this issue. I wonder if it might be due to some recent changes by Instagram. Hopefully, someone with more experience can figure it out. I can provide additional info if needed.

### Update
I have now confirmed that I am receiving the same error when running:
1. session.like_by_feed
2. session.interact_user_followers

Note: For session.interact_user_followers I  have properly configured session.set_user_interact and session.set_do_like  before calling session.interact_user_followers. So the error is not caused by some sort of improperly ordered settings-related function calls.

**Comment by schealex** [comment]
can confirm that both

`````
        post_page = browser.execute_script(
            "return window.__additionalData[Object.keys(window.__additionalData)[0]].data"
        )
`````

and

`````
            browser.execute_script("location.reload()")
            update_activity(browser, state=None)

            post_page = browser.execute_script(
                "return window._sharedData.entry_data.PostPage[0]"
            )
`````

in like_util.py are unable to get the post information now. But it's because they are no longer there. If you check the window object on any instagram post right now:


`````
entry_data:
PostPage: Array(1)
0:
__proto__: Object
length: 1
`````

and additonalData is empty object now:

`````
window.__additionalData
{}
`````

**Comment by Ayub-Khan** [comment]
Same.

**Comment by fqpasquetti** [comment]
Same

**Comment by trevtravtrev** [comment]
Same error

**Comment by sherxyar** [comment]
same here

**Comment by techmaharaj** [comment]
The same issue, worked fine until last evening.

**Comment by Nervanas** [comment]
Got the same error, tried to fix it myself. But I can't find where the missing information sould be now, as @schealex mentioned.

If you got a solution, please let us know!

**Comment by schealex** [comment]
> Got the same error, tried to fix it myself. But I can't find where the missing information sould be now, as @schealex mentioned.
> 
> If you got a solution, please let us know!

yeah i'm not so familiar with the code base of instapy but IF instagram did intentionally remove that form the window object then the code at least on this part of the like_util would need to be changed to get the same information directly from the DOM, which would be possible but i'm not a python developer and don't have the time to spend there right now :/

**Comment by Nervanas** [comment]
I searched the window object for strings which are inside a post (eg. the caption) but I did not find any. Maybe they changed that completely. I'm quite new to IG bots, so I don't know how it was solved before.

Could it be that it's now an API call to some new endpoint which is made to get the data from the post?
Kind of stumped here.

**Comment by alokkumarsbg** [comment]
I have found same data in line 274 of post Sourcecode within variable window.__additionalDataLoaded. May be someone can help using this.

![image](https://user-images.githubusercontent.com/20060997/119790909-f1ea6c00-bef1-11eb-9a5a-44da501d215e.png)

**Comment by Nervanas** [comment]
@alokkumarsbg  It seems like ` window._sharedData` contains all the data about the post.
Don't know what else Instapy uses, I'd play around with it, but I don't have any time rn.

Anyone of the community able to try it?

**Comment by ZappMax** [comment]
Same for me

**Comment by Nervanas** [comment]
I give up. Spent one, two hours trying to fix the problem.
Here's where I'm currently at:

`File: like_util.py`
`Function: check_link()`
`Problem: post_page is an empty object ({})`

This right here **should** get ALL the information about the post which InstaPy needs: `post_page = browser.execute_script("return window._sharedData.entry_data.PostPage[0]")`
If you execute within the developer console in a Instagram post: `window._sharedData.entry_data.PostPage[0]`
You see the `graphql` object and that it contains everything you need

**HOWEVER** if you execute `post_page = browser.execute_script("return window._sharedData.entry_data.PostPage[0]")` within `like_util.py` it STILL returns an **empty** object...

Problem with Selenium? I don't know :(

**Comment by schealex** [comment]
> I give up. Spent one, two hours trying to fix the problem.
> Here's where I'm currently at:
> 
> `File: like_util.py`
> `Function: check_link()`
> `Problem: post_page is an empty object ({})`
> 
> This right here **should** get ALL the information about the post which InstaPy needs: `post_page = browser.execute_script("return window._sharedData.entry_data.PostPage[0]")`
> If you execute within the developer console in a Instagram post: `window._sharedData.entry_data.PostPage[0]`
> You see the `graphql` object and that it contains everything you need
> 
> **HOWEVER** if you execute `post_page = browser.execute_script("return window._sharedData.entry_data.PostPage[0]")` within `like_util.py` it STILL returns an **empty** object...
> 
> Problem with Selenium? I don't know :(

where and how do you get the graphql object using dev console and browser? As stated above when i look at the window object then the PostPage[0] is an empty object without anything in it.

**Comment by alokkumarsbg** [comment]
window._sharedData contains mostly user data. I am able to pull the graphql value using different way. We can use that to modify the post_page variable. The code will give the value required for post_page in like_util.py file line 572. The function below which return dictionary also contains owner_comments. So no need to execute script in line 614.
Take this as a workaround or start. We can get a more better way

```
def get_post_page(pagesource):
    soup = BeautifulSoup(pagesource, "html.parser")
    for text in soup(text=re.compile(r"window.__additionalDataLoaded")):
        if re.search("^window.__additionalDataLoaded",text):
            post_page = json.loads(text[48:-2])
    return post_page
```

**Comment by schealex** [comment]
Ok i've got a working version now, was gonna do a clean PR for it but it seems like there are more problems. After fixing the check_link function now the verify_liking is making problems. Seems like the css selectors are not working anymore. I'm investigating right now

[EDIT] ok got that working too but there are more places where this old non working technique is used. Will replace all and do the PR

**Comment by schealex** [comment]
I've just created the PR which does solve the problem in regards to "like by tag" for me. But there is more work to do as there are more places where this old script to get the additional data is used.

PS: Feel free to test and let me know if that fix works for you guys too

**Comment by Nervanas** [comment]
@schealex you're the MVP! Been a hard day, so excuse the dumb question. Your PR contains two commits for the same file, what's the best way to update my current like_util.py now?

Thanks!

**Comment by schealex** [comment]
> @schealex you're the MVP! Been a hard day, so excuse the dumb question. Your PR contains two commits for the same file, what's the best way to update my current like_util.py now?
> 
> Thanks!

haha thanks but i just quickly threw that together as i'm not a python developer :D
The best way would be to merge my PR to your source if you have a fork on github. If you wanna do that manually then copy both the check_link and verify_liking functions from my code to your. In addition you need to copy the new import. And also copy the changes from util.py

**Comment by Nervanas** [comment]
@schealex good job, the liking works. Now we have to do the same sh*t for commenting?
I'm trying to fix that with your solution. If you or anyone else got that working, please create a PR

**Comment by schealex** [comment]
i'm doing that right now. i can update the PR if you can test this as i'm not able to test the changes i made right now?

**Comment by Nervanas** [comment]
@schealex Yes, I'll!

**Comment by schealex** [comment]
comments seem to also be working for me now. Please check my PR and verify

**Comment by Nervanas** [comment]
@schealex first of all, thanks for your work!

When I run it, I get the following error, didn't it happen to you, too?

```Traceback (most recent call last):
  File "pinstapie.py", line 176, in <module>
    session.like_by_tags(my_hashtags, amount=30, media=None)
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/instapy.py", line 2049, in like_by_tags
    self.logfolder,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/comment_util.py", line 404, in process_comments
    logger,
  File "/home/pi/.local/lib/python3.7/site-packages/instapy/comment_util.py", line 160, in verify_commenting
    if maximum is not None and comments_count > maximum:
TypeError: '>' not supported between instances of 'dict' and 'int'
```

**Comment by schealex** [comment]
seems like "get_comments_count" in comment_util does not return a proper int in your case but a dict. Thats weird. It's working fine for me. Need to investigate and maybe get your settings to test on my end. But i'm leaving home right now and won't be back until tomorrow.

i've you are able to debug your code could you check what the value of "comments_count" is in line 155 of comment_util?

**Comment by Nervanas** [comment]
@schealex comments_count is a dictionary and it's comparing against an int.
comments_count:
```
{'count': 0, 'edges': []}
<class 'dict'>
```

It seems as if I'd have to change
`if maximum is not None and comments_count > maximum:`

to
`if maximum is not None and comments_count['count'] > maximum:`

**Comment by schealex** [comment]
Ah ok i know where this is coming from. Just updated the PR with an attempt to fix it. Please have a look. Will not be able to do anything else till tomorrow

**Comment by Nervanas** [comment]
@schealex No worries, you did great. Me and all of the others are grateful for your work. Thanks a lot again and enjoy the rest of your day!

With the mentioned "fix" from above I've just posted the first comment ;)

**Comment by ZappMax** [comment]
Traceback (most recent call last):
  File "D:\PY\Instagram\instagram_bot.py", line 9, in <module>
    session.like_by_tags(["rockfrancais"], amount = 30)
  File "C:\Users\Maxime\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1957, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\Maxime\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\like_util.py", line 633, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0
PS D:\PY\Instagram>



That's my error, I don't now what to do at all. If someone can help me I would very appreciate

**Comment by schealex** [comment]
> Traceback (most recent call last):
> File "D:\PY\Instagram\instagram_bot.py", line 9, in
> session.like_by_tags(["rockfrancais"], amount = 30)
> File "C:\Users\Maxime\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1957, in like_by_tags
> inappropriate, user_name, is_video, reason, scope = check_link(
> File "C:\Users\Maxime\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\like_util.py", line 633, in check_link
> media = post_page[0]["shortcode_media"]
> KeyError: 0
> PS D:\PY\Instagram>
> 
> That's my error, I don't now what to do at all. If someone can help me I would very appreciate

have you tried the fix from my PR?

**Comment by ZappMax** [comment]
@schealex, so sorry but I am a very beginner. 
I downloaded your zip file "instapy" but I don't know what i need to remplace or to do with this zip files.

**Comment by schealex** [comment]
> @schealex, so sorry but I am a very beginner.
> I downloaded your zip file "instapy" but I don't know what i need to remplace or to do with this zip files.

So if you want to test my fork (which also has my fixed PR in it but also some other random fixes i did. You can install instapy from my develop repo:

pip install -I https://github.com/schealex/InstaPy/zipball/develop

To ensure you have done it correctly check the version after running instapy it should say "InstaPy Version: 0.6.14-AS"

feel free to report any problems you encounter ;)

**Comment by saisons** [comment]
@shealex, excellent work, is running fine for me now.

**Comment by WKDavid** [comment]
@schealex Thank you! Vielen hezlichen Dank! It works better than ever.

**Comment by ZappMax** [comment]
@schealex  Thank you so much to solved this !

**Comment by dzaczek** [comment]
Thank you is working for me. Ubuntu 20.08 , Mozilla Firefox 75.0, Mozilla gecodriver  75.0, python 3.8.5

**Comment by ghost** [comment]
@schealex Thank you for solving the original error. I am encountering a new issue which I am not sure if it might be related to the changes made in your PR.

I am using Instapy to like the posts of the followers of other accounts via the interact_user_followers() method. Since applying your fix I am now experiencing an increased number of "Cannot detect post media type." errors. It seems like the function that prints the "Getting [user] image list..." message is returning a list of posts that are sorted by Video post media type first or at least is unable to identify Video posts.

Here is the function I wrote in my Quickstart.py script. I don't believe that anything is misconfigured:

![image](https://user-images.githubusercontent.com/3899974/120018729-91246780-bfb5-11eb-8cb6-a0a97832755f.png)

Init_instapy_session() just creates an instapy session:

![image](https://user-images.githubusercontent.com/3899974/120018813-a5686480-bfb5-11eb-8a2b-40405d28772f.png)

Here is an example of the issue after running that function from my script:

![image](https://user-images.githubusercontent.com/3899974/120019071-fd9f6680-bfb5-11eb-83aa-e89b8e295baa.png)

If you visit the user's Instagram profile from the log you will see that the first 2 most recent posts are Videos and the third is a Photo. However, the bot decided to go through the Videos first and after skipping 10 posts it finally landed on a Photo. Normally, it would go through the posts in order from newest to oldest. Again I'm not sure if it is failing to identify the post media type or grabbing the image list with a different sorting than usual.

Let me know if you need any additional info.

**Comment by Nervanas** [comment]
@erik3165 Already tried https://github.com/timgrossmann/InstaPy/pull/6143?

**Comment by schealex** [comment]
@erik3165 i'm not having those issues on my develop branch. If you like you can try to use that. It has all the PR merged and some other fixes by myself. No gurantees though.

The only issue i'm encountering once a while is that a new follow cannot be verified but i'm likely gonna rewrite that whole mechanism to just use the data that is already there via graphql instead of using the xpaths for that...

**Comment by ghost** [comment]
@schealex I was able to download your development branch and everything is working as expected. Thank you!

@Nervanas I already applied that solution. But now everything is working with the development branch referenced below.

> > @schealex, so sorry but I am a very beginner.
> > I downloaded your zip file "instapy" but I don't know what i need to remplace or to do with this zip files.
> 
> So if you want to test my fork (which also has my fixed PR in it but also some other random fixes i did. You can install instapy from my develop repo:
> 
> pip install -I https://github.com/schealex/InstaPy/zipball/develop
> 
> To ensure you have done it correctly check the version after running instapy it should say "InstaPy Version: 0.6.14-AS"
> 
> feel free to report any problems you encounter ;)

**Comment by fipooo** [comment]
> > @schealex, so sorry but I am a very beginner.
> > I downloaded your zip file "instapy" but I don't know what i need to remplace or to do with this zip files.
> 
> So if you want to test my fork (which also has my fixed PR in it but also some other random fixes i did. You can install instapy from my develop repo:
> 
> pip install -I https://github.com/schealex/InstaPy/zipball/develop
> 
> To ensure you have done it correctly check the version after running instapy it should say "InstaPy Version: 0.6.14-AS"
> 
> feel free to report any problems you encounter ;)

After download your development branch this error appear. Any idea how to fix it?

`Traceback (most recent call last):
  File "/Users/macbook/Documents/instapy_bot.py", line 13, in <module>
    with smart_run(session):
  File "/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/instapy/util.py", line 1931, in smart_run
    session.login()
  File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 470, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "/usr/local/lib/python3.7/site-packages/instapy/print_log_writer.py", line 20, in log_follower_num
    followed_by = getUserData("graphql.user.edge_followed_by.count", browser)
  File "/usr/local/lib/python3.7/site-packages/instapy/util.py", line 462, in getUserData
    data = shared_data["entry_data"]["ProfilePage"][0]
KeyError: 'ProfilePage'`

**Comment by RainbowTob** [comment]
@schealex 

Hi, 

I installed "InstaPy Version: 0.6.14-AS".

But I have a few problems, I get the message: --> Couldn't follow 'User'!     ~user is inaccessible

Following still worked.


And if I unfollow users with this code:

session.unfollow_users(amount=random.randint(2, 5), nonFollowers=True, style="RANDOM", unfollow_after=48*60*60, sleep_delay=655)

It is unfollow Users from the same session, unfollow_after is not working.

Message is:

INFO [2021-05-30 02:22:04] [XXXX]  Total 32 users available to unfollow  ~not found in 'followedPool.csv': 32  |  didn't pass `unfollow_after`: 0

Could you please help me? Thank you!

**Comment by schealex** [comment]
> @schealex
> 
> Hi,
> 
> I installed "InstaPy Version: 0.6.14-AS".
> 
> But I have a few problems, I get the message: --> Couldn't follow 'User'! ~user is inaccessible
> 
> Following still worked.
> 
> And if I unfollow users with this code:
> 
> session.unfollow_users(amount=random.randint(2, 5), nonFollowers=True, style="RANDOM", unfollow_after=48_60_60, sleep_delay=655)
> 
> It is unfollow Users from the same session, unfollow_after is not working.
> 
> Message is:
> 
> INFO [2021-05-30 02:22:04] [XXXX] Total 32 users available to unfollow ~not found in 'followedPool.csv': 32 | didn't pass `unfollow_after`: 0
> 
> Could you please help me? Thank you!

as commented above i'm getting this too from time to time but that does not have anything to do with this issue and is not related to my code changes. It's a seperate issue. Would you open another issue for it? Then i'll be able to link my rewrite / fix there one i'm done with it.

**Comment by schealex** [comment]
> > > @schealex, so sorry but I am a very beginner.
> > > I downloaded your zip file "instapy" but I don't know what i need to remplace or to do with this zip files.
> > 
> > 
> > So if you want to test my fork (which also has my fixed PR in it but also some other random fixes i did. You can install instapy from my develop repo:
> > pip install -I https://github.com/schealex/InstaPy/zipball/develop
> > To ensure you have done it correctly check the version after running instapy it should say "InstaPy Version: 0.6.14-AS"
> > feel free to report any problems you encounter ;)
> 
> After download your development branch this error appear. Any idea how to fix it?
> 
> `Traceback (most recent call last): File "/Users/macbook/Documents/instapy_bot.py", line 13, in <module> with smart_run(session): File "/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__ return next(self.gen) File "/usr/local/lib/python3.7/site-packages/instapy/util.py", line 1931, in smart_run session.login() File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 470, in login self.followed_by = log_follower_num(self.browser, self.username, self.logfolder) File "/usr/local/lib/python3.7/site-packages/instapy/print_log_writer.py", line 20, in log_follower_num followed_by = getUserData("graphql.user.edge_followed_by.count", browser) File "/usr/local/lib/python3.7/site-packages/instapy/util.py", line 462, in getUserData data = shared_data["entry_data"]["ProfilePage"][0] KeyError: 'ProfilePage'`

not with more context. What config are you running?

**Comment by fipooo** [comment]
> > > > @schealex, so sorry but I am a very beginner.
> > > > I downloaded your zip file "instapy" but I don't know what i need to remplace or to do with this zip files.
> > > 
> > > 
> > > So if you want to test my fork (which also has my fixed PR in it but also some other random fixes i did. You can install instapy from my develop repo:
> > > pip install -I https://github.com/schealex/InstaPy/zipball/develop
> > > To ensure you have done it correctly check the version after running instapy it should say "InstaPy Version: 0.6.14-AS"
> > > feel free to report any problems you encounter ;)
> > 
> > 
> > After download your development branch this error appear. Any idea how to fix it?
> > `Traceback (most recent call last): File "/Users/macbook/Documents/instapy_bot.py", line 13, in <module> with smart_run(session): File "/usr/local/Cellar/python@3.7/3.7.8_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__ return next(self.gen) File "/usr/local/lib/python3.7/site-packages/instapy/util.py", line 1931, in smart_run session.login() File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 470, in login self.followed_by = log_follower_num(self.browser, self.username, self.logfolder) File "/usr/local/lib/python3.7/site-packages/instapy/print_log_writer.py", line 20, in log_follower_num followed_by = getUserData("graphql.user.edge_followed_by.count", browser) File "/usr/local/lib/python3.7/site-packages/instapy/util.py", line 462, in getUserData data = shared_data["entry_data"]["ProfilePage"][0] KeyError: 'ProfilePage'`
> 
> not with more context. What config are you running?

I running with this.
```
from instapy import InstaPy
from instapy import smart_run

insta_username = ''
insta_password= ''

session=InstaPy(username=insta_username,
				password=insta_password,
                  headless_browser=False,
                  split_db=True,
                  multi_logs=True)

with smart_run(session):
	session.set_relationship_bounds(enabled=True,
			    potency_ratio=None,
			    delimit_by_numbers=True,
			    max_followers=6000,
				max_following=3000,
				min_followers=30,
				min_following=30)
	session.set_do_like(enabled=True, percentage=100)
	session.set_do_comment(enabled=False, percentage=0)
	session.set_do_follow(enabled=False, percentage=0, times=1)
	session.set_user_interact(amount=1, randomize=True, percentage=35, media='Photo')
	session.follow_user_followers(['xyz'], amount=amount_number, randomize=False, interact=True, sleep_delay=300)
```

**Comment by 0xrfsd** [comment]
any updates?

**Comment by schealex** [comment]
> any updates?

updates regarding what? this issue is fixed...

**Comment by bedouin345** [comment]
Noob question here : I run on Docker. How to update my container and load the fix ?

Thx all for the wealth of info and time invested

**Comment by saisons** [comment]
@schealex, quick question: since installing your fix, (which is working great), when InstaPy cannot like an image, instead of essentially skipping over it and continuing, it's throwing an error and requiring the user to press Enter to continue, which requires the script to be babysat. Can you advise how to disable this new function and revert to the prior behaviour? Thanks.

**Comment by schealex** [comment]
> @schealex, quick question: since installing your fix, (which is working great), when InstaPy cannot like an image, instead of essentially skipping over it and continuing, it's throwing an error and requiring the user to press Enter to continue, which requires the script to be babysat. Can you advise how to disable this new function and revert to the prior behaviour? Thanks.

that is a fix from another PR which should not occur unless your account is blocked from liking. But if you want the bot to continue and disregard maybe getting suspended by insta you can comment out line 787 in like_util.py ;)

**Comment by aleff-github** [comment]
> > @schealex, so sorry but I am a very beginner.
> > I downloaded your zip file "instapy" but I don't know what i need to remplace or to do with this zip files.
> 
> So if you want to test my fork (which also has my fixed PR in it but also some other random fixes i did. You can install instapy from my develop repo:
> 
> pip install -I https://github.com/schealex/InstaPy/zipball/develop
> 
> To ensure you have done it correctly check the version after running instapy it should say "InstaPy Version: 0.6.14-AS"
> 
> feel free to report any problems you encounter ;)

Solved ❤️

**Comment by skoenig** [comment]
> Noob question here : I run on Docker. How to update my container and load the fix ?
> 
> Thx all for the wealth of info and time invested

I solved it by creating a minimal Dockerfile like this:
```
FROM instapy/instapy:0.6.13

RUN pip3 install -I https://github.com/schealex/InstaPy/zipball/develop

RUN \
  # Disabling geckodriver log file
  sed -i "s#browser = webdriver.Firefox(#browser = webdriver.Firefox(service_log_path=os.devnull,#g" /usr/local/lib/python3.7/site-packages/instapy/browser.py \
  # Fix webdriverdownloader not handling asc files
  && sed -i "s#bitness in name]#bitness in name and name[-3:] != 'asc' ]#g" /usr/local/lib/python3.7/site-packages/webdriverdownloader/webdriverdownloader.py

CMD ["python", "docker_quickstart.py"]
```

Build and run it as usual: `docker build -t instapy:0.6.14-AS .`

**Comment by PiratesGomez** [comment]
> > @schealex, so sorry but I am a very beginner.
> > I downloaded your zip file "instapy" but I don't know what i need to remplace or to do with this zip files.
> 
> So if you want to test my fork (which also has my fixed PR in it but also some other random fixes i did. You can install instapy from my develop repo:
> 
> pip install -I https://github.com/schealex/InstaPy/zipball/develop
> 
> To ensure you have done it correctly check the version after running instapy it should say "InstaPy Version: 0.6.14-AS"
> 
> feel free to report any problems you encounter ;)

WORKING TO LIKE !

**Comment by bedouin345** [comment]
> > Noob question here : I run on Docker. How to update my container and load the fix ?
> > Thx all for the wealth of info and time invested
> 
> I solved it by creating a minimal Dockerfile like this:
> 
> ```
> FROM instapy/instapy:0.6.13
> 
> RUN pip3 install -I https://github.com/schealex/InstaPy/zipball/develop
> 
> RUN \
>   # Disabling geckodriver log file
>   sed -i "s#browser = webdriver.Firefox(#browser = webdriver.Firefox(service_log_path=os.devnull,#g" /usr/local/lib/python3.7/site-packages/instapy/browser.py \
>   # Fix webdriverdownloader not handling asc files
>   && sed -i "s#bitness in name]#bitness in name and name[-3:] != 'asc' ]#g" /usr/local/lib/python3.7/site-packages/webdriverdownloader/webdriverdownloader.py
> 
> CMD ["python", "docker_quickstart.py"]
> ```
> 
> Build and run it as usual: `docker build -t instapy:0.6.14-AS .`

Thank you skoenig. I learned a lot in this process. Though I could not build the docker :

  _WARNING: Built wheel for instapy is invalid: Metadata 1.2 mandates PEP 440 version, but '0.6.14-AS' is not_

I guess I will wait for Instapy changes to be committed. That's unfortunate

**Comment by elulcao** [comment]
> > > Noob question here : I run on Docker. How to update my container and load the fix ?
> > > Thx all for the wealth of info and time invested
> > 
> > 
> > I solved it by creating a minimal Dockerfile like this:
> > ```
> > FROM instapy/instapy:0.6.13
> > 
> > RUN pip3 install -I https://github.com/schealex/InstaPy/zipball/develop
> > 
> > RUN \
> >   # Disabling geckodriver log file
> >   sed -i "s#browser = webdriver.Firefox(#browser = webdriver.Firefox(service_log_path=os.devnull,#g" /usr/local/lib/python3.7/site-packages/instapy/browser.py \
> >   # Fix webdriverdownloader not handling asc files
> >   && sed -i "s#bitness in name]#bitness in name and name[-3:] != 'asc' ]#g" /usr/local/lib/python3.7/site-packages/webdriverdownloader/webdriverdownloader.py
> > 
> > CMD ["python", "docker_quickstart.py"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Build and run it as usual: `docker build -t instapy:0.6.14-AS .`
> 
> Thank you skoenig. I learned a lot in this process. Though I could not build the docker :
> 
> _WARNING: Built wheel for instapy is invalid: Metadata 1.2 mandates PEP 440 version, but '0.6.14-AS' is not_
> 
> I guess I will wait for Instapy changes to be committed. That's unfortunate

Download the py file to your local, it means the file that contains the fix.
map this file to the docker container with `-v` and then start the container as usual.

**Comment by olevezinho** [comment]
@schealex thank you!!! 
Working 100% as of now.

**Comment by Lembornik** [comment]
Hi,
I installed "InstaPy Version: 0.6.14-AS".
But I have a few problems, I get the message: Image not liked: b'Unavailable Page'
I use this code: "session.like_by_feed(amount=30, randomize=False, unfollow=False, interact=False)"
Could you please help me? Thank you!

**Comment by Mhdiksn** [comment]
> > @schealex, so sorry but I am a very beginner.
> > I downloaded your zip file "instapy" but I don't know what i need to remplace or to do with this zip files.
> 
> So if you want to test my fork (which also has my fixed PR in it but also some other random fixes i did. You can install instapy from my develop repo:
> 
> pip install -I https://github.com/schealex/InstaPy/zipball/develop
> 
> To ensure you have done it correctly check the version after running instapy it should say "InstaPy Version: 0.6.14-AS"
> 
> feel free to report any problems you encounter ;)

i tried to install (pip install -I https://github.com/schealex/InstaPy/zipball/develop)

and i have this problem 
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\Users\mhdik\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tornado\speedups.cp39-win_amd64.pyd'
Check the permissions.

any idea to fix that?
I tried in administrator user and same think

**Comment by joniler** [comment]
@schealex you, sir, are a hero.

**Comment by Graticool** [comment]
Very beginner here, so please go easy on me :) 

I managed to have a working instabot before May 26.  It broke bc of the Like_by_tags ["shortcode_media"] error described above.  Got it backup and running using @schealex  InstaPy Version: 0.6.14-AS 

It currently likes & follows but doesn't comment.  I'm getting results: "INFO ...  couldn't get post description and comments"

It doesn't error, just won't comment, and continues to next post.  Tried removing mandatory words, as well, same issue.  Bot would comment prior to Schealex's fix , so it was working at some point.

Thanks so much for the fix so far!    Any thoughts on the non-commenting issue are greatly appreciated!

**Comment by Danimal01** [comment]
hey quick question, am using the script @schealex posted which fixed actually liking images, but it seems comments still do not work, can anyone point me to the part of the code I would need to edit to get it to work?

**Comment by VitalyLub** [comment]
> > @schealex, so sorry but I am a very beginner.
> > I downloaded your zip file "instapy" but I don't know what i need to remplace or to do with this zip files.
> 
> So if you want to test my fork (which also has my fixed PR in it but also some other random fixes i did. You can install instapy from my develop repo:
> 
> pip install -I https://github.com/schealex/InstaPy/zipball/develop
> 
> To ensure you have done it correctly check the version after running instapy it should say "InstaPy Version: 0.6.14-AS"
> 
> feel free to report any problems you encounter ;)

1. Thanks a lot!!!
2. Why is it not included in the main install yet?

**Comment by Graticool** [comment]
> hey quick question, am using the script @schealex posted which fixed actually liking images, but it seems comments still do not work, can anyone point me to the part of the code I would need to edit to get it to work?

@Danimal01 yes, same for me too.  Commenting on posts is not working for me.  Anyone else?

**Comment by Python228** [comment]
![image](https://user-images.githubusercontent.com/57003360/130022434-1a4b920a-e61e-43c9-b1d1-577b1b393f68.png)
hepl me
