### ISSUE TITLE
Couldn't follow 'User'! ~user is inaccessible

### ISSUE THREAD

**Issue by RainbowTob** [InstaPy/InstaPy#6200]
## Expected Behavior
No Message, Following detected
## Current Behavior
Following still working, but it will not detected

## InstaPy configuration

session.set_user_interact(amount=1, randomize=True, percentage=100, media='Photo')

        session.set_do_follow(enabled=True, percentage=100)

**Comment by schealex** [comment]
can confirm i'm getting this too once the bot run for a little while. Will check if i can fix that.

**Comment by RainbowTob** [comment]
Thank you!

**Comment by schealex** [comment]
see PR #6204 for the fix which is working fine for me

**Comment by schealex** [comment]
if someone tested it please leave me some feedback if it's working for you too

**Comment by RainbowTob** [comment]
Yes! Now it is fine! Thank you.
