### ISSUE TITLE
  File "C:\Users\12146\Desktop\instagram bot\quickstart.py", line 32, in <module>     session.like_by_tags([ 'bongs' , 'waterpipe'], amount=100)   File "C:\Users\12146\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1957, in like_by_tags     inappropriate, user_name, is_video, reason, scope = check_link(   File "C:\Users\12146\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\like_util.py", line 633, in check_link     media = post_page[0]["shortcode_media"]

### ISSUE THREAD

**Issue by Arucard11** [InstaPy/InstaPy#6208]
File "C:\Users\12146\Desktop\instagram bot\quickstart.py", line 32, in <module>
    session.like_by_tags([ 'bongs' , 'waterpipe'], amount=100)
  File "C:\Users\12146\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1957, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\12146\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\like_util.py", line 633, in check_link
    media = post_page[0]["shortcode_media"]

**Comment by mkMcMahon** [comment]
yeh I'm getting the same error. 'shortcoe_media' telling me to check the link. I'm lost. I tried uninstalling and reinstalling and get the same error.

**Comment by Arucard11** [comment]
Wonder what it is I looked  at the code no idea what to change

**Comment by schealex** [comment]
yo guys please check if that issue already exists before creating a new one. This is duplicate of #6191 and is fixed by PR #6195

**Comment by pcdiks** [comment]
> yo guys please check if that issue already exists before creating a new one. This is duplicate of #6191 and is fixed by PR #6195

When will this be release then?

**Comment by mkMcMahon** [comment]
Its released we just have to pull those fixes since they havent been
merged yet. Thanks and sorry youre right i didnt see the other fix.

**Comment by schealex** [comment]
No worries, just have a second look next time 👌😉

**Comment by Arucard11** [comment]
Thank you for the fix my bad didn't see it  I'm new to this thank you for your patience
