### ISSUE TITLE
Skipping Public accounts only.

### ISSUE THREAD

**Issue by sherxyar** [InstaPy/InstaPy#6215]
## Expected Behavior
A feature to Skip public profiles.
## Current Behavior
Can only skip private, business, or non-business accounts.
## Possible Solution (optional)
adding the skip_public=True to this ;
session.set_skip_users(skip_private=False,
	                            skip_no_profile_pic=True,
                                    skip_business=True,
		                   _**skip_public=True,**_

**Comment by schealex** [comment]
@sheryar-tahir can you please check my PR and test if it works?

**Comment by sherxyar** [comment]
if someone faces any issue, please read the thread of the PR [6221](https://github.com/timgrossmann/InstaPy/pull/6221)
