### ISSUE TITLE
getattr(session, job) & like_by_locations & check_link

### ISSUE THREAD

**Issue by vitguld** [InstaPy/InstaPy#6229]
Hey, 

Setting up InstaPy with one of the `quickstart_templates` e.g. `good_commenting_strategy_and_new_qs_system`.

The bot crashes when it’s about to like a post and shows the following error:

`Traceback (most recent call last):
  File "C:\Users\Windows 10\Desktop\InstagramBot\bot.py", line 141, in <module>
    getattr(session, job['functionName'])(**arguments)
  File "C:\Users\Windows 10\Desktop\InstagramBot\env\lib\site-packages\instapy\instapy.py", line 1516, in like_by_locations
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\Windows 10\Desktop\InstagramBot\env\lib\site-packages\instapy\like_util.py", line 633, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0 `

Any idea what might cause this?

**Comment by schealex** [comment]
Already fixed. Please search before opening issues.

**Comment by vitguld** [comment]
@schealex Hello, sorry if I’m missing something, I have updated InstaPy using the following `pip install Instapy -U` and the problem still exists. Am I doing something wrong?

**Comment by schealex** [comment]
follow these instructions on how to update to current but not jet released version: https://instapy.org/additional-information#-install-or-update-to-the-unreleased-version

**Comment by vitguld** [comment]
@schealex Thanks friend, closing the issue.
