### ISSUE TITLE
Telegram InstaPy Scheduling

### ISSUE THREAD

**Issue by Tkd-Alex** [InstaPy/InstaPy#623]
### Hi to everyone! 
Yesterday I starder to develop a little bot for Telegram which allows to schedule InstaPy bot. 
This is only another solution to run InstaPy on a server and automate it without cron.

For the moment I have implement this command:
-  **/set**
_Set a new job <job_name> <hour:min:sec>. For the moment the job will be execute every day at time setted,  but I think I will give the user option to choose one day or more._
- **/unset** 
_Delete a job <name>. All job are stored inside array. By name of job the user can be delete a job._
- **/print**
_The print command print all setted job (only name for the moment)._
- **/status**
_Show if instaPy bot is already run or not._

 It's very easy to setup!
- Create a bot with @ BotFather 
- Download my code and write in a variable (for the moment) instagram_psw, instagram_username, telegram_token (received from BotFather).  
- Write inside a function the custom instapy code 
```
def instaPy_run():
    try:
        # Login
        session = InstaPy(username=insta_username, password=insta_password)
        session.login()
        
        # Comments
        session.set_do_comment(enabled=True, percentage=50)
        comments = ["Beautiful"]
        session.set_comments(comments)
        
        # Follow
        session.set_do_follow(enabled=True, percentage=50, times=2)
        
        # Like
        hashtags = ["#like","#instapy"]
        session.like_by_tags(hashtags, amount=10)
        
        
        session.end()
    except:
        import traceback
        print(traceback.format_exc())
```

- Run the script on the server.

For the moment i haven't a repo, because  I don't know if I shoul fork this repo and create e subdirectory with telegram bot, or create a new repo with only telegram bot.

_What do you think? Any suggestions?_

**Comment by timgrossmann** [comment]
@Tkd-Alex What a great tool to make using InstaPy even better!

Thank you, make sure to keep us up to date if you have a repository.

**Comment by Tkd-Alex** [comment]
What do you think about this?
I should create my custom repository or fork the InstaPy repo? 

Nobody else?

**Comment by jackfriend** [comment]
Can you make a new repo for this? It sounds really interesting

**Comment by Tkd-Alex** [comment]
Ok, in the next week i will make e new repo only for Telegram InstaPy Bot.

**Comment by timgrossmann** [comment]
@Tkd-Alex Yes, separate Repo would be perfect

**Comment by imewish** [comment]
Hi the tool looks amazing ! Would be nice if we could get more details on the print command. Like status of finished jobs, how many posts liked, commented followed etc.

**Comment by Tkd-Alex** [comment]
I just created the repo. 
As soon as I've made the first commit I'll send you a notification;)

**Comment by Tkd-Alex** [comment]
Suggestions and testers are welcome! 
https://github.com/Tkd-Alex/Telegram-InstaPy-Scheduling
@timgrossmann @imewish @jackfriend

**Comment by converge** [comment]
@Tkd-Alex great idea! how is it going ?

**Comment by Tkd-Alex** [comment]
@converge you can test it on https://github.com/Tkd-Alex/Telegram-InstaPy-Scheduling
