### ISSUE TITLE
unable to like

### ISSUE THREAD

**Issue by diogoribeirodev** [InstaPy/InstaPy#6232]
i get the unable to load media error( for like 4.5 posts )  and after that it gets a media post and 
After getting the post when is time to click the like button the app stops

Traceback (most recent call last):
File "C:\Users\ribei\Downloads\Reddit\insta.py", line 32, in
session.like_by_tags(["cats"], amount=10)
File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\instapy.py", line 1957, in like_by_tags
inappropriate, user_name, is_video, reason, scope = check_link(
File "C:\Users\ribei\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\like_util.py", line 633, in check_link
media = post_page[0]["shortcode_media"]
KeyError: 0
[Finished in 207.3s] #6230

**Comment by BHUMITKATHPALIA** [comment]
I'm having the same issue as well - any solutions?

**Comment by schealex** [comment]
Already fixed, please use the search next time. Use this guide to update to the current master (unreleased version): https://instapy.org/additional-information

**Comment by BHUMITKATHPALIA** [comment]
Sorry for the trouble - and thank you very much! It's working now.

**Comment by dragu95** [comment]
While updating I get this error:
ERROR: Could not install packages due to an OSError: [WinError 5] Zugriff verweigert: 'c:\\users\\user\\appdata\\local\\programs\\python\\python39\\Lib\\site-packages\\tornado\\speedups.cp39-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

How to fix it?

**Comment by sonuhawk** [comment]
> 

URL provided above not working.
I am facing this issue again  . I cloned the instapy( master branch )  and repalced in in lib/site-packages 
but still getting 

\instapy\like_util.py", line 618, in check_link
    media = post_page[0]["shortcode_media"]
