### ISSUE TITLE
Image not liked: b'Unavailable Page'

### ISSUE THREAD

**Issue by Lembornik** [InstaPy/InstaPy#6233]
Hi,
I installed "InstaPy Version: 0.6.14-AS".
But I have a few problems, I get the message: Image not liked: b'Unavailable Page'
I use this code: "session.like_by_feed(amount=30, randomize=False, unfollow=False, interact=False)"
Could you please help me? Thank you!

_Originally posted by @Lembornik in https://github.com/timgrossmann/InstaPy/issues/6191#issuecomment-860957667_

**Comment by ferdasonmez** [comment]
Hi,
I am having the same issue? Did you find a way to fix that?

**Comment by Lembornik** [comment]
Hi,
I corrected the file "like_util.py".

**Comment by Lembornik** [comment]
if post_page is None:
        try:
            post_page = browser.execute_script(
                "return window.__additionalData[Object.keys(window.__additionalData)[0]].data"
        )

        except WebDriverException:  # handle the possible `entry_data` error
            try:
                browser.execute_script("location.reload()")
                update_activity(browser, state=None)

                post_page = browser.execute_script(
                    "return window._sharedData.entry_data.PostPage[0]"
                )

            except WebDriverException:
                logger.warning("Unavailable Page: {}".format(post_link.encode("utf-8")))
                return True, None, None, "Unavailable Page", "Failure"

**Comment by ferdasonmez** [comment]
Hi,
I realized it. Uninstall it and installing like below solved the problem..
pip install -I
https://github.com/schealex/InstaPy/zipball/develop
<https://www.freelancer.com/users/l.php?url=https:%2F%2Fgithub.com%2Fschealex%2FInstaPy%2Fzipball%2Fdevelop&sig=34ed50a4edf167a689b25757e76e712e84364b403679918925c12c438322b81d>

Many thanks,
Ferda

**Comment by ChayseMcGuyer** [comment]
@Lembornik Do I just add this code to the like_util file? or am I supposed to replace something?

**Comment by BanannaCode** [comment]
> ```
> if post_page is None:
>     try:
>         post_page = browser.execute_script(
>             "return window.__additionalData[Object.keys(window.__additionalData)[0]].data"
>     )
> 
>     except WebDriverException:  # handle the possible `entry_data` error
>         try:
>             browser.execute_script("location.reload()")
>             update_activity(browser, state=None)
> 
>             post_page = browser.execute_script(
>                 "return window._sharedData.entry_data.PostPage[0]"
>             )
> 
>         except WebDriverException:
>             logger.warning("Unavailable Page: {}".format(post_link.encode("utf-8")))
>             return True, None, None, "Unavailable Page", "Failure"        
> ```



> ```
> if post_page is None:
>     try:
>         post_page = browser.execute_script(
>             "return window.__additionalData[Object.keys(window.__additionalData)[0]].data"
>     )
> 
>     except WebDriverException:  # handle the possible `entry_data` error
>         try:
>             browser.execute_script("location.reload()")
>             update_activity(browser, state=None)
> 
>             post_page = browser.execute_script(
>                 "return window._sharedData.entry_data.PostPage[0]"
>             )
> 
>         except WebDriverException:
>             logger.warning("Unavailable Page: {}".format(post_link.encode("utf-8")))
>             return True, None, None, "Unavailable Page", "Failure"        
> ```

Hi @Lembornik 
thanks for this - it is working for me now!
However after liking the first pic it pops out an error when it attempts to comment the photo - are you facing similar issues?

I am using the AS version of InstaPy and get the following error:
Traceback (most recent call last):
  File "C:\Users\A\Documents\07_Python\InstaBot\an.py", line 22, in <module>
    session.like_by_tags(["travelgram"], amount = 1)
  File "C:\Python39\lib\site-packages\instapy\instapy.py", line 2056, in like_by_tags
    success = process_comments(
  File "C:\Python39\lib\site-packages\instapy\comment_util.py", line 438, in process_comments
    commented_image, message = verify_commented_image(browser, link, owner, logger)
  File "C:\Python39\lib\site-packages\instapy\comment_util.py", line 359, in verify_commented_image
    data = getMediaData("edge_media_to_parent_comment", browser)
  File "C:\Python39\lib\site-packages\instapy\util.py", line 500, in getMediaData
    data = additional_data["graphql"]["shortcode_media"]
TypeError: 'NoneType' object is not subscriptable

**Comment by Lembornik** [comment]
Hi @BanannaCode 
I have not faced this problem. But I don't use AS version of InstaPy.

**Comment by newdispatcher** [comment]
> > ```
> > if post_page is None:
> >     try:
> >         post_page = browser.execute_script(
> >             "return window.__additionalData[Object.keys(window.__additionalData)[0]].data"
> >     )
> > 
> >     except WebDriverException:  # handle the possible `entry_data` error
> >         try:
> >             browser.execute_script("location.reload()")
> >             update_activity(browser, state=None)
> > 
> >             post_page = browser.execute_script(
> >                 "return window._sharedData.entry_data.PostPage[0]"
> >             )
> > 
> >         except WebDriverException:
> >             logger.warning("Unavailable Page: {}".format(post_link.encode("utf-8")))
> >             return True, None, None, "Unavailable Page", "Failure"        
> > ```
> 
> > ```
> > if post_page is None:
> >     try:
> >         post_page = browser.execute_script(
> >             "return window.__additionalData[Object.keys(window.__additionalData)[0]].data"
> >     )
> > 
> >     except WebDriverException:  # handle the possible `entry_data` error
> >         try:
> >             browser.execute_script("location.reload()")
> >             update_activity(browser, state=None)
> > 
> >             post_page = browser.execute_script(
> >                 "return window._sharedData.entry_data.PostPage[0]"
> >             )
> > 
> >         except WebDriverException:
> >             logger.warning("Unavailable Page: {}".format(post_link.encode("utf-8")))
> >             return True, None, None, "Unavailable Page", "Failure"        
> > ```
> 
> Hi @Lembornik thanks for this - it is working for me now! However after liking the first pic it pops out an error when it attempts to comment the photo - are you facing similar issues?
> 
> I am using the AS version of InstaPy and get the following error: Traceback (most recent call last): File "C:\Users\A\Documents\07_Python\InstaBot\an.py", line 22, in session.like_by_tags(["travelgram"], amount = 1) File "C:\Python39\lib\site-packages\instapy\instapy.py", line 2056, in like_by_tags success = process_comments( File "C:\Python39\lib\site-packages\instapy\comment_util.py", line 438, in process_comments commented_image, message = verify_commented_image(browser, link, owner, logger) File "C:\Python39\lib\site-packages\instapy\comment_util.py", line 359, in verify_commented_image data = getMediaData("edge_media_to_parent_comment", browser) File "C:\Python39\lib\site-packages\instapy\util.py", line 500, in getMediaData data = additional_data["graphql"]["shortcode_media"] TypeError: 'NoneType' object is not subscriptable

I am having same problem with one of account @ErwinKoekoek can you help with this issue

**Comment by workproduct** [comment]
i updated like_util.py and util.py what is the 3rd file to update

**Comment by ErwinKoekoek** [comment]
> i updated like_util.py and util.py what is the 3rd file to update

comment_util.put

**Comment by martini09617** [comment]
When placing the above code in like_util.py I am getting this error message when running the script:

 from .like_util import (
  File "C:\Users\mkamm\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\like_util.py", line 604
    return True, None, None, "Unavailable Page", "Failure"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: 'return' outside function

**Comment by bunvinni** [comment]
hey guys I've tried all the solutions here an nothing is working :(

**Comment by Wolkex3** [comment]
I have th same issue. Is everyone having the issue? Is it a system specific issue? When does it happen?
