### ISSUE TITLE
Couple of questions regarding mandatory_bio_keywords

### ISSUE THREAD

**Issue by LightMoon** [InstaPy/InstaPy#6240]
Hi,

I would like to know if the mandatory_bio_keywords case sensitive and also know if it is support Unicode?
if so, what is the syntax for putting a Unicode in this condition?

Thanks

**Comment by lrnvrryth** [comment]
https://instapy.org/settings/#mandatory-words

I think it is case sensitive, I think unicode works

**Comment by LightMoon** [comment]
found the answer, it is not case sensitive.

```python
for bio_keyword in skip_bio_keyword:
            if bio_keyword.lower() in profile_bio:
                return (
                    False,
                    "{} has a bio keyword of {}, by default skip\n".format(
                        username, bio_keyword
                    ),
```
