### ISSUE TITLE
Cannot detect post media type. skip

### ISSUE THREAD

**Issue by MohakAoki** [InstaPy/InstaPy#6243]
Hi. 
Im working on windows and python 3.9 and latest instapy version.
my code:

from instapy import InstaPy

session = InstaPy(username="<my user>", password="<my pass>")
session.login()
session.like_by_tags(["tag"], amount=1)

**Comment by Lrnvrybthksa** [comment]
try using 

with smart_run(session): 

instead of session.login()

**Comment by LeSchurke** [comment]
I have the same problem. I use smart_run. That's not the problem. I read, you must change everything in the like_util.py

**Comment by Desantnikov** [comment]
Had same issue

https://github.com/timgrossmann/InstaPy/pull/6143/commits/2b3ab2d99e5a9f9ec8130a26823851203faa38db
This worked well for me

**Comment by kharazian** [comment]
It has solved, how ever it is appear recently again. 
 [#6243 (comment)](https://github.com/timgrossmann/InstaPy/issues/6243#issuecomment-879654705)
could you plz check it again and help me to find out the problem.
thanks

**Comment by MohakAoki** [comment]
> It has solved, how ever it is appear recently again. [#6277 (comment)](https://github.com/timgrossmann/InstaPy/issues/6277#issuecomment-892426361) could you plz check it again and help me to find out the problem. thanks

Sorry but i finished the project. i have no access to it right now.

**Comment by dannyarcher** [comment]
@MohakAoki @kharazian removing the class pedicate also works #6340

**Comment by dannyarcher** [comment]
Try #6340

**Comment by kharazian** [comment]
> Thanks, I've tried #6340 but it still didn't work. Here's a screenshot: <img alt="Screenshot 2021-10-08 at 13 27 31" width="1117" src="https://user-images.githubusercontent.com/92159402/136551327-e6ff574b-a940-40f8-99f1-086f00b982a0.png"> :

what is your code? your hashtags? do you test there are reachable manually?

**Comment by fiederich12345** [comment]
Hello again,
thanks for your quick help, I actually got it to work now. Something seemed to be wrong with that hashtag, it now indeed works with a different hashtag. No idea why..

In case it doesn't work for you and you want a test hashtag that worked for me, try this:
session.like_by_tags(['funnyvideos'], amount=5, media='Video')

Best!
