### ISSUE TITLE
Rating stories

### ISSUE THREAD

**Issue by DerLomo** [InstaPy/InstaPy#6267]
It s possible now to rate stories?
Like the following
![image](https://user-images.githubusercontent.com/25827889/125160685-9234e100-e17e-11eb-91ab-33841463b1d3.png)
If not it would be amazing to implement this feature

**Comment by youngtrashbag** [comment]
I don't think that rating is possible, because InstaPy runs via Web Browser. I am not sure and you should check yourself if its possible. I do know that you cannot write text into a question widget in someones story.
