### ISSUE TITLE
getting Cannot detect post media type. Skip

### ISSUE THREAD

**Issue by macd2** [InstaPy/InstaPy#6277]
## Expected Behavior
like a photo

## Current Behavior
doesn't like any photos 

## Possible Solution (optional)
the response from `https://www.instagram.com/explore/tags/tag/` has changed the media types are now defined with numbers not strings this might cause the issue? 

PS: Error message is: `Message: Unable to locate element: //a[@href='/p/CRT-h1RFxdq/']/child::div[@class='u7YqG']/child::span`

## InstaPy configuration
https://github.com/InstaPy/instapy-quickstart/blob/master/quickstart_templates/like_by_tag_interact_unfollow.py

**Comment by mmreuysal** [comment]
same with instapy-gui

**Comment by pascalkania** [comment]
hey, 
pls checkout PR #6202
or this worked for me https://github.com/timgrossmann/InstaPy/issues/6243#issuecomment-879654705

**Comment by kharazian** [comment]
This error appear again. #6202 has solved but I faced again with this issue.

**Comment by kharazian** [comment]
some changes could solve the problem
#6243 [comment](https://github.com/timgrossmann/InstaPy/issues/6243#issuecomment-933261670)

**Comment by dannyarcher** [comment]
Changes in #6340 may help

**Comment by mokhtarakel** [comment]
I stll have the same problem, 
I tested all the solutions suggested above

**Comment by elulcao** [comment]
> I stll have the same problem,
> I tested all the solutions suggested above

Could you check #6346? and verify the fix works for you.
the fix worked fine at my end, but I would like to see the results for different IG's zone
