### ISSUE TITLE
Firefox xpath selectors for "Followers" / "Following" + dialog boxes not working

### ISSUE THREAD

**Issue by sndf3** [InstaPy/InstaPy#628]
Hi everyone,

I set up the InstaPy bot for Chrome and Firefox yesterday and almost everything went easy / is running smooth (very good explanations and help here - thanks a mill!).

The only issue I face is that the xpath selectors can't find the followers / following elements in Firefox - see the following console excerpt. It seems like the selectors are able to alomst locate the right element on the page, because a gray box appears around the e.g. "followers" in the browser before the script crashes, but it's definetly not getting selected/clicked, as not dialog box with followers opens.

**Exception stack** - very last lines - the whole stack is quite long:
`\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[text()='Followers' or text()='Following']/following-sibling::div`

I worked thru the exception stack and probably located the functions in unfollow_util.py which trigger the exception. But with all my amateur webcoding knowhow I wasn't able to fix the issue myself... sorry.

I am using the .follow_users_followers() function in the above mentioned case, but the same issues seems to prevent the .set_do_follow() to work (only strange thing is that this function call does not trigger any exception - it simply doesn't work and then the scripts runs till the end after liking photos, but without a single new follower).

This happened using Firefox 55.0.3 (64bit) version and Geckodriver v0.18.0-win64, as well as python 3.6.2-amd64.
Login, liking and pretty much everything else is working fine with the same setup - it really seems to be an issue with only this xpath command.
Furthermore everything is working fine with chrome... but for certain reasons I want to get firefox  to work, too ;)
(Unfortunatley I can't debug, push or pull at the moment).

Probably related issue: #607 

Thank you very much in advance!
sndf3

**Comment by timgrossmann** [comment]
@sndf3 Is this issue still present? If yes, please reopen!

**Comment by davidrocket** [comment]
@timgrossmann Hi Tim, I've got the same problem since yesterday. But I guess the problem was still not fixed in Firefox. 

In my test, The followers/following dialog was not shown, when instapy was started to do a follow-run. 

It'll be super, when somebody can take a look in constellation with Firefox. Thank you.

**Comment by davidrocket** [comment]
@timgrossmann I just fix the problem of following in Firefox. Please replace:

in file unfollow_util.py, line 717 and 765
`        # following_link[0].send_keys("\n")`

with this line
`        # following_link[0].click()`

They are tested and worked!

**Comment by converge** [comment]
@davidrocket sounds good. We should refactor our code to .click()

**Comment by davidrocket** [comment]
Let replace all, then push. Thank
