### ISSUE TITLE
� Symbol at the end of every comment - only if using Firefox

### ISSUE THREAD

**Issue by ArdySan2012** [InstaPy/InstaPy#631]
Hey guys, I understand that Firefox may not be optimized as well as Chrome.... 

But curious occurance. After every comment (even if this is just a word hello), either using u' ' syntax for emoji, or not - it leaves this symbol: �

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.

**Comment by julienkermarec** [comment]
Same problem with raspberry + firefox
