### ISSUE TITLE
unfollow_users method isn't working. Activity is being restricted.

### ISSUE THREAD

**Issue by Dieg0x17** [InstaPy/InstaPy#6310]
## Expected Behavior
Unfollow users.

## Current Behavior
Showing an alert from instagram
![error_unfollow](https://user-images.githubusercontent.com/6205864/132940488-feb96e25-5832-4c05-823c-a16c6b258a9c.png)

The unfollow action is not blocked on the account only with InstaPy, selenium and geckodriver.
I figured out that they are recognizing some patterns to identify this kind of automation.

## Possible Solution (optional)
- Change the user agent, because unfollow action on instagram is not blocked, only with InstaPy, selenium and geckodriver.
- Change the behaviour of the action, maybe introduce some random activity to avoid repeating patterns.

## InstaPy configuration
```
    session.unfollow_users(amount=random.randint(75, 100),
                           nonFollowers=True,
                           style="FIFO",
                           unfollow_after=24 * 60 * 60, sleep_delay=600)
```

**Comment by elulcao** [comment]
Seems that your account is shadow banned
verify the limited and bot frequency
