### ISSUE TITLE
Won't like even 1 image.

### ISSUE THREAD

**Issue by gdr2404** [InstaPy/InstaPy#6314]
Tried the Discord channel but without much luck. Im running into a issue where its not liking any images on my feed.
Following accounts work, just not liking images. It logs in, goes to the first image in my feed, then to an error page on Instagram. It hangs on the error page for a while then goes back to my feed and starts moving through the images but still not liking any.

Tried clearing cookies, reducing the like amount, adding tags to search before liking and still nothing. Anyone come across this issue before?

Thanks
Gav

![Insta Issues](https://user-images.githubusercontent.com/65822596/133686098-f6773a61-d430-495b-b8b1-27b41d323976.jpg)
![error](https://user-images.githubusercontent.com/65822596/133685979-d884afb7-7d48-434a-a6ef-28303e32abb3.jpg)
![Code](https://user-images.githubusercontent.com/65822596/133686350-768ba67e-f551-41c0-b78c-9d1910e4a3cc.jpg)

.

**Comment by lolicarlos** [comment]
I think this is not working anymore. I'm facing the same issue ... I cant find any solution so I gues is not working and its not important anymore.

**Comment by elulcao** [comment]
IG displayed an error, InstaPy cannot read/interpret anything until an useable page is displayed.
The error message form IG recommends to wait and try again later, did you check why your IG is returning such error?

**Comment by gdr2404** [comment]
How can i check why instagram is displaying this Error? InstaPy will always take me to this error page. After waiting on this error page for a short while, InstaPy tries again. It looks like its working somewhat as each each in my feed appears for a few seconds before going onto the next image down. But still, no likes are happening.

I can manually like the images in my feed when logging in via the browser. I can even like them if i'm quick as its going between the next image. InstaPy just doesn't seem to be seeing the like button.

**Comment by elulcao** [comment]
add this to your session constructor and check the log for the driver in the workspace.

```
geckodriver_log_level="trace",
```

InstaPy only reads the content of the page, so the bot fails if the page is still the same "Please wait few..." 
the interesting problem here is why your acct cannot display anything.

**Comment by elulcao** [comment]
@gdr2404 i suspect the problem is the gecko driver itself. IG detected the bot and then the infinite loop in the page. Could check if the log session says something like hide selenium extension error?
If that's the case try with a FF lower than 88 version.

**Comment by gdr2404** [comment]
Tried the geckodriver_log_level, i dont think it brought up anything new. I've also uninstalled fireforx and installed the 87 version, again it still seems to be doing the same thing. I took a screen recording off it, excuse the slight delay as its a screen-less set up using a  vnc.

https://youtu.be/X3bttxuiLRo

Do you think there's anything that looks out of place with the way its trying to handle the operation? Thanks @elulcao for trying to help me sort this, really appreciate it.

**Comment by elulcao** [comment]
@gdr2404 
Thanks for the video, 👍 
Try with other FFversion older than 88. The problem is that newer versions of FF cannot hide the web.driver value four automated controller. 

Check the error highlighted in the pic. ![image](https://user-images.githubusercontent.com/6373960/134056424-bf8861b7-dd3e-4f38-a972-c02a5c73f7df.jpeg)

**Comment by gdr2404** [comment]
![new1](https://user-images.githubusercontent.com/65822596/134058995-e6351187-a8af-48d3-a41a-c3b18d2f552d.jpg)

downgrading FF to version 60 definitely solved the Selenium Error, but its still not liking the images..

**Comment by elulcao** [comment]
@gdr2404 👍 nice
Where did you download 0.6.14-AS version of instapy? Seems to be another branch 😉 
We have a new problem, could you tell me what happens when you run the bot I graphic mode? I would like to check if the acct is not shadow banned

**Comment by gdr2404** [comment]
Im not actually sure how I got that AS version, i did try some peoples suggestions be updating some of the py files, but have just reverted back to the 'InstaPy Version: 0.6.14'on this github page since anything suggested wasn't working. Im still not getting anywhere though.

How do i run the bot in graphic mode? Someone on the discord page suggested i could be shadow banned. If i leave the firefox window open and close the command window, i am able to like multiple posts if i click them manually. I can also  run a separate script to follow users and that works, which i assume it wouldn't if i was shadow banned?

**Comment by elulcao** [comment]
> Out of curiosity, can anyone let me know if this actually works on their system with their setup? Just so we can rule out that its  a problem with my machine and not something instagram has changed?

Yep, it's working. The recomendación at the moment is to use an old version of FF like 77. 
In my case I'm using FF 88 and macOS for fixing some xpaths and still working

**Comment by lolicarlos** [comment]
> > Out of curiosity, can anyone let me know if this actually works on their system with their setup? Just so we can rule out that its  a problem with my machine and not something instagram has changed?
> 
> Yep, it's working. The recomendación at the moment is to use an old version of FF like 77.
> In my case I'm using FF 88 and macOS for fixing some xpaths and still working

Is the like by feed working for you?
