### ISSUE TITLE
like_by_feed: Total of links feched for analysis: 0

### ISSUE THREAD

**Issue by laboratoriodosfundos** [InstaPy/InstaPy#6321]
I am only receiving "Total links fetched for analysis: 0" when using like_by_feed.
Somebody else?

**Comment by laboratoriodosfundos** [comment]
@elulcao
About this issue, you are already aware of it.
Is there a solution?

**Comment by elulcao** [comment]
@laboratoriodosfundos 
Not yet, 
Could you share some logs or point me to other ticket with more info 
Thanks 
👍

**Comment by laboratoriodosfundos** [comment]
In general.log it only shows this when trying to run like_by_feed:

NFO [2021-09-19 18:27:45] [XXXXXX]  Total of links feched for analysis: 0
INFO [2021-09-19 18:28:20] [XXXXXX]  Total of links feched for analysis: 0
INFO [2021-09-19 18:28:56] [XXXXXX]  Total of links feched for analysis: 0
INFO [2021-09-19 18:29:35] [XXXXXX]  Total of links feched for analysis: 0
INFO [2021-09-19 18:30:17] [XXXXXX]  Total of links feched for analysis: 0
INFO [2021-09-19 18:30:59] [XXXXXX]  Total of links feched for analysis: 0
INFO [2021-09-19 18:31:44] [XXXXXX]  Total of links feched for analysis: 0
INFO [2021-09-19 18:32:31] [XXXXXX]  Total of links feched for analysis: 0
INFO [2021-09-19 18:33:20] [XXXXXX]  Total of links feched for analysis: 0
INFO [2021-09-19 18:34:10] [XXXXXX]  Total of links feched for analysis: 0

WARNING [2021-09-19 18:34:10] [XXXXXX]  Loop error, 0 links for 10 times consecutively, exit loop

INFO [2021-09-19 18:34:10] [XXXXXX]  Liked: 0
INFO [2021-09-19 18:34:10] [XXXXXX]  Already Liked: 0
INFO [2021-09-19 18:34:10] [XXXXXX]  Commented: 0
INFO [2021-09-19 18:34:10] [XXXXXX]  Followed: 0
INFO [2021-09-19 18:34:10] [XXXXXX]  Inappropriate: 0
INFO [2021-09-19 18:34:10] [XXXXXX]  Not valid users: 0
INFO [2021-09-19 18:34:10] [XXXXXX]  Randomly Skipped: 0

INFO [2021-09-19 18:34:28] [XXXXXX]  Sessional Live Report:
	|> LIKED 0 images  |  ALREADY LIKED: 0
	|> COMMENTED on 0 images
	|> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
	|> UNFOLLOWED 0 users
	|> LIKED 0 comments
	|> REPLIED to 0 comments
	|> INAPPROPRIATE images: 0
	|> NOT VALID users: 0
	|> WATCHED 0 story(ies)  |  WATCHED 0 reel(s)

Could you run a simple script with just like_by_feed to test?

**Comment by laboratoriodosfundos** [comment]
@elulcao
Daniel, it seems to me that Instagram has removed the link from the posts in the feed.

**Comment by bilotto** [comment]
I've got the fix. 

https://github.com/timgrossmann/InstaPy/pull/6325

**Comment by elulcao** [comment]
Please, use thread in https://github.com/timgrossmann/InstaPy/pull/6325#issuecomment-926318401
Closing it to avoid back and forth
