### ISSUE TITLE
unfollow: Already unfollowed 'XXX'! or a private user that rejected your req

### ISSUE THREAD

**Issue by laboratoriodosfundos** [InstaPy/InstaPy#6322]
Already unfollowed 'XXX'! or a private user that rejected your req

When using unfollow I get this answer a lot, there are several before I can stop following someone.
Could not unfollow even if it is a private account?

**Comment by elulcao** [comment]
Whats wrong with that message? the user is already unfollowed.

**Comment by laboratoriodosfundos** [comment]
Sorry for not making the problem clear.
Instapy keeps following and shows this message.

**Comment by elulcao** [comment]
I quite sure Instapy cannot follow/unfollow because the acct is shadow banned.
If you try from another device it should works. I saw that users wants to run Instapy and get millions of followers instantly, that's not possible; verify your limits and boundaries for the bot.

**Comment by laboratoriodosfundos** [comment]
Friend, I understand that you deal with people like that all the time, but that's not my case.
My scripts are for the long term, all very slow and with controlled limits on daily activities.
I've been using Instapy for over a year and I know what I'm saying.
This error appears in several profiles but in others the operation proceeds normally.
It seems to me that you are not ceasing to follow private accounts.

**Comment by elulcao** [comment]
Did you add the specific skip actions for specific acct:

```
session.set_skip_users(
        skip_private=True, 
        skip_no_profile_pic=True, 
        skip_business=False
    )
```

**Comment by laboratoriodosfundos** [comment]
I didn't have this tag in my script, nor did I know it had any influence on unfollow, I thought it only worked for following.
But I saw that skip_private by default is true, so I added it as false, but it still didn't work.

Ongoing Unfollow [1/9]: now unfollowing 'b'janderlucas10''...
--> Already unfollowed 'janderlucas10'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'matheus.a.torres''...
--> Already unfollowed 'matheus.a.torres'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'dsat1va''...
--> Already unfollowed 'dsat1va'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'rhavierrocha''...
--> Already unfollowed 'rhavierrocha'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'marcao_bj''...
--> Already unfollowed 'marcao_bj'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'kayronfacundes''...
--> Already unfollowed 'kayronfacundes'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'liga_geek_sorteios''...
--> Already unfollowed 'liga_geek_sorteios'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'cicari0h''...
--> Already unfollowed 'cicari0h'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'dksfbbff''...
--> Already unfollowed 'dksfbbff'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'_fernandoamerico''...
--> Already unfollowed '_fernandoamerico'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'jean5605_''...
--> Already unfollowed 'jean5605_'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'ichbin_igor''...
--> Already unfollowed 'ichbin_igor'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'968x00xx''...
--> Already unfollowed '968x00xx'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'arthur_bcf''...
--> Already unfollowed 'arthur_bcf'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'hackerspro.online''...
--> Already unfollowed 'hackerspro.online'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'rheusmi''...
--> Already unfollowed 'rheusmi'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'nyo.programmer''...
--> Already unfollowed 'nyo.programmer'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'ruan_shp''...
--> Already unfollowed 'ruan_shp'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'costakevy''...
--> Already unfollowed 'costakevy'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'anajuliamendonca.mm''...
--> Already unfollowed 'anajuliamendonca.mm'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'v.victor_t''...
--> Already unfollowed 'v.victor_t'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'tiagodnzz''...
--> Already unfollowed 'tiagodnzz'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'maribclbr''...
--> Already unfollowed 'maribclbr'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'desativei.eitt''...
--> Already unfollowed 'desativei.eitt'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'slajskajdksjfdjgdg''...
--> Already unfollowed 'slajskajdksjfdjgdg'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'marcelohenrique111333777888555''...
--> Already unfollowed 'marcelohenrique111333777888555'! or a private user that rejected your req
Ongoing Unfollow [1/9]: now unfollowing 'b'daiane_cristina_m''...
Last unfollow is verified after reloading the page!
--> Unfollowed 'daiane_cristina_m'!
Ongoing Unfollow [2/9]: now unfollowing 'b'serginhooow''...
Last unfollow is verified after reloading the page!
--> Unfollowed 'serginhooow'!
Ongoing Unfollow [3/9]: now unfollowing 'b'jacksonschirigatti''...
Last unfollow is verified after reloading the page!
--> Unfollowed 'jacksonschirigatti'!
Ongoing Unfollow [4/9]: now unfollowing 'b'nayeliton''...
Last unfollow is verified after reloading the page!
--> Unfollowed 'nayeliton'!
Ongoing Unfollow [5/9]: now unfollowing 'b'kayo_obadia''...
Last unfollow is verified after reloading the page!
--> Unfollowed 'kayo_obadia'!
Ongoing Unfollow [6/9]: now unfollowing 'b'victor_pedro25''...
Last unfollow is verified after reloading the page!
--> Unfollowed 'victor_pedro25'!
Ongoing Unfollow [7/9]: now unfollowing 'b'holdsinas_''...
Last unfollow is verified after reloading the page!
--> Unfollowed 'holdsinas_'!
Ongoing Unfollow [8/9]: now unfollowing 'b'helder_barreto1''...
--> Already unfollowed 'helder_barreto1'! or a private user that rejected your req
Ongoing Unfollow [8/9]: now unfollowing 'b'jaquelin028''...
Last unfollow is verified after reloading the page!
--> Unfollowed 'jaquelin028'!
Ongoing Unfollow [9/9]: now unfollowing 'b'ripasouri''...
Last unfollow is verified after reloading the page!
--> Unfollowed 'ripasouri'!

**Comment by elulcao** [comment]
Could you share your template via email to make some local test, just remove your user and password 
@laboratoriodosfundos 
It would be easy to my to very in my local.

**Comment by laboratoriodosfundos** [comment]
I am noticing that all skipped profiles have 0 posts, I don't know if this is the case or if these are private and therefore I can't see their post count.
That's why I was running tests with set_relationship_bounds, before it was not in the script.
Thanks for your interest.
Is there any way we can talk directly?

--------------------------
session = InstaPy(username=, password=, page_delay=30, headless_browser=False, split_db=True)

with smart_run(session):
session.set_simulation(enabled=False, percentage=0)

session.set_user_interact(amount=1, randomize=True, percentage=100, media=None)
session.set_do_follow(enabled=False, percentage=0)
session.set_do_like(enabled=True, percentage=90)
session.set_do_comment(enabled=False, percentage=0)
session.set_do_story(enabled=True, percentage=50, simulate=False)

session.set_skip_users(skip_private=False, skip_no_profile_pic=False, skip_business=False)

session.set_relationship_bounds(enabled=False, potency_ratio=None, delimit_by_numbers=False, min_followers=None, max_followers=None, min_following=None, max_following=None, min_posts=None, max_posts=None)

session.set_action_delays(enabled=True, like=60, comment=60, follow=60, unfollow=60, story=60, randomize=True, random_range_from=10, random_range_to=100, safety_match=True)

session.set_quota_supervisor(enabled=True, sleep_after=["likes_h", "unfollows_h", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                            peak_likes_hourly = 60, peak_likes_daily =1200,
                            peak_comments_hourly = 60, peak_comments_daily = 600,
                            peak_follows_hourly = 60, peak_follows_daily = 500,
                            peak_unfollows_hourly = 100, peak_unfollows_daily = 800,
                            peak_server_calls_hourly = 400, peak_server_calls_daily = 8000)

session.unfollow_users(amount=100, custom_list_enabled=False, custom_list=[], instapy_followed_enabled=False, nonFollowers=True, allFollowing=False, style="FIFO", unfollow_after=172800, sleep_delay=180)
session.like_by_feed(amount=10, randomize=True, unfollow=True, interact=True)

**Comment by laboratoriodosfundos** [comment]
@elulcao 
I forgot to comment.
I am using the latest version provided by @schealex.
I downloaded it here, https://github.com/schealex/InstaPy/zipball/develop
Even this summer has more than 3 months, I have tried to talk to schealex, but could not.
Do you have any more up to date?

**Comment by elulcao** [comment]
> @elulcao
> I forgot to comment.
> I am using the latest version provided by @schealex.
> I downloaded it here, https://github.com/schealex/InstaPy/zipball/develop
> Even this summer has more than 3 months, I have tried to talk to schealex, but could not.
> Do you have any more up to date?

So, you must create a ticket against that repo,
that branch is out of this scope, so I don't know the changes they implemented.
