### ISSUE TITLE
Unfollow: Already unfollowed 'YYY'! or a private user that rejected your req

### ISSUE THREAD

**Issue by laboratoriodosfundos** [InstaPy/InstaPy#6323]
@elulcao
I downloaded the newest version there from the repository and the behavior persists.
Also, like_by_feed is not working, it only returns Total links fetched for analysis: 0

INFO [2021-09-19 23:02:30] [XXXXXX]  Ongoing Unfollow [1/7]: now unfollowing 'b'coreprojetos01''...
INFO [2021-09-19 23:03:11] [XXXXXX]  Last unfollow is verified after reloading the page!
INFO [2021-09-19 23:03:11] [XXXXXX]  --> Unfollowed 'coreprojetos01'!
INFO [2021-09-19 23:04:13] [XXXXXX]  Ongoing Unfollow [2/7]: now unfollowing 'b'analovecaps''...
INFO [2021-09-19 23:04:53] [XXXXXX]  Last unfollow is verified after reloading the page!
INFO [2021-09-19 23:04:53] [XXXXXX]  --> Unfollowed 'analovecaps'!
INFO [2021-09-19 23:05:53] [XXXXXX]  Ongoing Unfollow [3/7]: now unfollowing 'b'sergio_drywall''...
INFO [2021-09-19 23:06:34] [XXXXXX]  Last unfollow is verified after reloading the page!
INFO [2021-09-19 23:06:34] [XXXXXX]  --> Unfollowed 'sergio_drywall'!
INFO [2021-09-19 23:06:51] [XXXXXX]  Ongoing Unfollow [4/7]: now unfollowing 'b'jrrivelli''...
INFO [2021-09-19 23:07:32] [XXXXXX]  Last unfollow is verified after reloading the page!
INFO [2021-09-19 23:07:32] [XXXXXX]  --> Unfollowed 'jrrivelli'!
INFO [2021-09-19 23:08:31] [XXXXXX]  Ongoing Unfollow [5/7]: now unfollowing 'b'gooinna''...
INFO [2021-09-19 23:09:10] [XXXXXX]  Last unfollow is verified after reloading the page!
INFO [2021-09-19 23:09:10] [XXXXXX]  --> Unfollowed 'gooinna'!
INFO [2021-09-19 23:09:33] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'janderlucas10''...
INFO [2021-09-19 23:09:36] [XXXXXX]  --> Already unfollowed 'janderlucas10'! or a private user that rejected your req
INFO [2021-09-19 23:09:39] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'matheus.a.torres''...
INFO [2021-09-19 23:09:41] [XXXXXX]  --> Already unfollowed 'matheus.a.torres'! or a private user that rejected your req
INFO [2021-09-19 23:09:45] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'dsat1va''...
INFO [2021-09-19 23:09:49] [XXXXXX]  --> Already unfollowed 'dsat1va'! or a private user that rejected your req
INFO [2021-09-19 23:09:51] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'rhavierrocha''...
INFO [2021-09-19 23:09:54] [XXXXXX]  --> Already unfollowed 'rhavierrocha'! or a private user that rejected your req
INFO [2021-09-19 23:09:57] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'marcao_bj''...
INFO [2021-09-19 23:10:00] [XXXXXX]  --> Already unfollowed 'marcao_bj'! or a private user that rejected your req
INFO [2021-09-19 23:10:04] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'kayronfacundes''...
INFO [2021-09-19 23:10:06] [XXXXXX]  --> Already unfollowed 'kayronfacundes'! or a private user that rejected your req
INFO [2021-09-19 23:10:10] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'liga_geek_sorteios''...
INFO [2021-09-19 23:10:13] [XXXXXX]  --> Already unfollowed 'liga_geek_sorteios'! or a private user that rejected your req
INFO [2021-09-19 23:10:16] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'cicari0h''...
INFO [2021-09-19 23:10:19] [XXXXXX]  --> Already unfollowed 'cicari0h'! or a private user that rejected your req
INFO [2021-09-19 23:10:22] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'dksfbbff''...
INFO [2021-09-19 23:10:26] [XXXXXX]  --> Already unfollowed 'dksfbbff'! or a private user that rejected your req
INFO [2021-09-19 23:10:30] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'_fernandoamerico''...
INFO [2021-09-19 23:10:32] [XXXXXX]  --> Already unfollowed '_fernandoamerico'! or a private user that rejected your req
INFO [2021-09-19 23:10:35] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'jean5605_''...
INFO [2021-09-19 23:10:37] [XXXXXX]  --> Already unfollowed 'jean5605_'! or a private user that rejected your req
INFO [2021-09-19 23:10:40] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'ichbin_igor''...
INFO [2021-09-19 23:10:43] [XXXXXX]  --> Already unfollowed 'ichbin_igor'! or a private user that rejected your req
INFO [2021-09-19 23:10:45] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'968x00xx''...
INFO [2021-09-19 23:10:47] [XXXXXX]  --> Already unfollowed '968x00xx'! or a private user that rejected your req
INFO [2021-09-19 23:10:50] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'arthur_bcf''...
INFO [2021-09-19 23:10:53] [XXXXXX]  --> Already unfollowed 'arthur_bcf'! or a private user that rejected your req
INFO [2021-09-19 23:10:56] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'hackerspro.online''...
INFO [2021-09-19 23:10:59] [XXXXXX]  --> Already unfollowed 'hackerspro.online'! or a private user that rejected your req
INFO [2021-09-19 23:11:03] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'rheusmi''...
INFO [2021-09-19 23:11:06] [XXXXXX]  --> Already unfollowed 'rheusmi'! or a private user that rejected your req
INFO [2021-09-19 23:11:09] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'nyo.programmer''...
INFO [2021-09-19 23:11:12] [XXXXXX]  --> Already unfollowed 'nyo.programmer'! or a private user that rejected your req
INFO [2021-09-19 23:11:15] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'ruan_shp''...
INFO [2021-09-19 23:11:18] [XXXXXX]  --> Already unfollowed 'ruan_shp'! or a private user that rejected your req
INFO [2021-09-19 23:11:21] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'costakevy''...
INFO [2021-09-19 23:11:24] [XXXXXX]  --> Already unfollowed 'costakevy'! or a private user that rejected your req
INFO [2021-09-19 23:11:27] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'anajuliamendonca.mm''...
INFO [2021-09-19 23:11:29] [XXXXXX]  --> Already unfollowed 'anajuliamendonca.mm'! or a private user that rejected your req
INFO [2021-09-19 23:11:33] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'v.victor_t''...
INFO [2021-09-19 23:11:35] [XXXXXX]  --> Already unfollowed 'v.victor_t'! or a private user that rejected your req
INFO [2021-09-19 23:11:38] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'tiagodnzz''...
INFO [2021-09-19 23:11:41] [XXXXXX]  --> Already unfollowed 'tiagodnzz'! or a private user that rejected your req
INFO [2021-09-19 23:11:44] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'maribclbr''...
INFO [2021-09-19 23:11:47] [XXXXXX]  --> Already unfollowed 'maribclbr'! or a private user that rejected your req
INFO [2021-09-19 23:11:50] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'desativei.eitt''...
INFO [2021-09-19 23:11:53] [XXXXXX]  --> Already unfollowed 'desativei.eitt'! or a private user that rejected your req
INFO [2021-09-19 23:11:56] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'slajskajdksjfdjgdg''...
INFO [2021-09-19 23:11:59] [XXXXXX]  --> Already unfollowed 'slajskajdksjfdjgdg'! or a private user that rejected your req
INFO [2021-09-19 23:12:02] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'marcelohenrique111333777888555''...
INFO [2021-09-19 23:12:04] [XXXXXX]  --> Already unfollowed 'marcelohenrique111333777888555'! or a private user that rejected your req
INFO [2021-09-19 23:12:08] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'helder_barreto1''...
INFO [2021-09-19 23:12:11] [XXXXXX]  --> Already unfollowed 'helder_barreto1'! or a private user that rejected your req
INFO [2021-09-19 23:12:13] [XXXXXX]  Ongoing Unfollow [6/7]: now unfollowing 'b'desenvolvedormaster''...
INFO [2021-09-19 23:12:54] [XXXXXX]  Last unfollow is verified after reloading the page!
INFO [2021-09-19 23:12:54] [XXXXXX]  --> Unfollowed 'desenvolvedormaster'!
INFO [2021-09-19 23:13:39] [XXXXXX]  Ongoing Unfollow [7/7]: now unfollowing 'b'desablw2''...
INFO [2021-09-19 23:13:42] [XXXXXX]  --> Already unfollowed 'desablw2'! or a private user that rejected your req
INFO [2021-09-19 23:13:45] [XXXXXX]  Ongoing Unfollow [7/7]: now unfollowing 'b'optimizasolucoes''...
INFO [2021-09-19 23:14:27] [XXXXXX]  Last unfollow is verified after reloading the page!
INFO [2021-09-19 23:14:27] [XXXXXX]  --> Unfollowed 'optimizasolucoes'!

My script:
session = InstaPy(username=, password=, page_delay=30, headless_browser=False, split_db=True)

with smart_run(session):
session.set_simulation(enabled=False, percentage=0)

session.set_user_interact(amount=1, randomize=True, percentage=100, media=None)
session.set_do_follow(enabled=False, percentage=0)
session.set_do_like(enabled=True, percentage=90)
session.set_do_comment(enabled=False, percentage=0)
session.set_do_story(enabled=True, percentage=50, simulate=False)

session.set_skip_users(skip_private=False, skip_no_profile_pic=False, skip_business=False)

session.set_relationship_bounds(enabled=False, potency_ratio=None, delimit_by_numbers=False, min_followers=None, max_followers=None, min_following=None, max_following=None, min_posts=None, max_posts=None)

session.set_action_delays(enabled=True, like=60, comment=60, follow=60, unfollow=60, story=60, randomize=True, random_range_from=10, random_range_to=100, safety_match=True)

session.set_quota_supervisor(enabled=True, sleep_after=["likes_h", "unfollows_h", "server_calls_h"], sleepyhead=True, stochastic_flow=True, notify_me=True,
                            peak_likes_hourly = 60, peak_likes_daily =1200,
                            peak_comments_hourly = 60, peak_comments_daily = 600,
                            peak_follows_hourly = 60, peak_follows_daily = 500,
                            peak_unfollows_hourly = 100, peak_unfollows_daily = 800,
                            peak_server_calls_hourly = 400, peak_server_calls_daily = 8000)

session.unfollow_users(amount=100, custom_list_enabled=False, custom_list=[], instapy_followed_enabled=False, nonFollowers=True, allFollowing=False, style="FIFO", unfollow_after=172800, sleep_delay=180)
session.like_by_feed(amount=10, randomize=True, unfollow=True, interact=True)

**Comment by elulcao** [comment]
@laboratoriodosfundos 
This is only an informational message, it indicates the user already followed and unfollowed, nothing wrong for now.
There is a file like *_record_all_unfollowed.csv in the workspace where you can corroborate the unfollowed users. 

```python
        elif following_status in ["Follow", "Follow Back"]:
            logger.info(
                "--> Already unfollowed '{}'! or a private user that "
                "rejected your req".format(person)
            )
            post_unfollow_cleanup(
                ["successful", "uncertain"],
                username,
                person,
                relationship_data,
                person_id,
                logger,
                logfolder,
            )
```

For next user, unfollow action completed successfully; and the next time you executes the bot it will be marked as "Already unfollowed."

```bash
INFO [2021-09-19 23:13:45] [XXXXXX] Ongoing Unfollow [7/7]: now unfollowing 'b'optimizasolucoes''...
INFO [2021-09-19 23:14:27] [XXXXXX] Last unfollow is verified after reloading the page!
INFO [2021-09-19 23:14:27] [XXXXXX] --> Unfollowed 'optimizasolucoes'!
```

**Comment by laboratoriodosfundos** [comment]
Thanks for the clarification.
I was guessing it was something of little relevance, but I preferred to be sure because I had never seen this message.
What about like_by_feed, any idea what's going on?
