### ISSUE TITLE
Internet Connection Status: error

### ISSUE THREAD

**Issue by laboratoriodosfundos** [InstaPy/InstaPy#6326]
Friends I just downloaded the version available here: https://github.com/timgrossmann/InstaPy/zipball/master
But I get the error: Internet Connection Status: error
right when running the script, the previous version this is not happening.
Here is the LOG:
INFO [2021-09-21 12:44:44] [XXX]  Session started!
INFO [2021-09-21 12:44:44] [XXX]  -- Connection Checklist [1/2] (Internet Connection Status)
WARNING [2021-09-21 12:45:05] [XXX]  - Internet Connection Status: error
CRITICAL [2021-09-21 12:45:05] [XXX]  Unable to login to Instagram! You will find more information in the logs above.

**Comment by matcode1** [comment]
I am having the same issue, yesterday it worked fine.
I am guessing... it might be a geckodriver update...
I will keep you posted.

**Comment by rterres** [comment]
@ciwox would know where to find the seeip status?  I'm having the same problem reported above.

**Comment by laboratoriodosfundos** [comment]
@ciwox
Yes, just yesterday I took the test and saw that seeip.org was down.
Is there any parameter to start Instapy that bypasses access checking?

**Comment by matcode1** [comment]
@ciwox @laboratoriodosfundos @rterres 
Indeed the problem is here: https://github.com/timgrossmann/InstaPy/blob/master/instapy/login_util.py#L165
I am not sure what is the purpose of the "Connection Checklist [1/2]" but commenting it seems to work. 
I guess it is the only alternative while seeip.org is offline.

**Comment by ErezAmihud** [comment]
set `want_check_browser=False` when creating instapy
