### ISSUE TITLE
[Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by zooner-edu** [InstaPy/InstaPy#633]
Hello friends,
I'm having a problem, I've uploaded the instapy structure to my server, I've done it step by step. using the documentation and this article:
https://medium.com/@mcnamee/using-open-source-software-to-build-your-instagram-followers-205f908cf657

But when I try to start my script it gets me an error:
root@insta-01:~# sudo python /var/www/instapy/index.py
Traceback (most recent call last):
  File "/var/www/instapy/index.py", line 2, in <module>
    InstaPy(username='<***>', password='<***>', nogui=True) \
  File "/var/www/instapy/instapy/instapy.py", line 53, in __init__
    self.logFile = open('./logs/logFile.txt', 'a')
FileNotFoundError: [Errno 2] No such file or directory: './logs/logFile.txt'

My server is a ubuntu.

**Comment by zooner-edu** [comment]
My Script

from instapy import InstaPy
InstaPy(username='<***>', password='<***>', nogui=True) \
  .login() \
  .set_do_comment(enabled=True, percentage=25) \
  .set_comments(['Nice one', 'Love it!']) \
  .set_do_follow(enabled=True, percentage=10) \
  .set_use_clarifai(enabled=True, secret='<***>', proj_id='<***>') \
  .set_use_clarifai(enabled=True) \
  .clarifai_check_img_for(['nsfw'], comment=False) \
  .clarifai_check_img_for(['foodporn', 'foodie', 'healthyeating'], comment=True, comments=['Tasty!', 'Yes!']) \
  .like_by_tags(['#healthyeating', '#foodie', '#foodporn'], amount=100) \
  .unfollow_users(amount=4000) \
  .end()

**Comment by iSimonWeb** [comment]
Is the InstaPy directory writeable by python?

**Comment by alexmourer** [comment]
I experienced this as well. Changing to the InstaPy directory before running the script solves it for me.

**Comment by converge** [comment]
hey @zooner-edu, you're using Linux right ?
```chmod -R 755 logs```
will fix it. 
pls reopen this issue if it doesn't help.

**Comment by amauryleproux** [comment]
Hi, I've got the same error when I try to run the script via a cron task, I did the chmod -R 755 logs but still got the error :/ 

Any other solutions please?

**Comment by myehrajat** [comment]
same error in windows
