### ISSUE TITLE
Image was not able to get liked! maybe blocked?

### ISSUE THREAD

**Issue by kharazian** [InstaPy/InstaPy#6347]
After the post liked the IG check it is like.
The Ig check an show this message "Image was not able to get liked! maybe blocked?", but post is liked.

**Comment by kharazian** [comment]
> > > I have the exact same issue ,, the bot can open the images related with the hashtag but no liking and no commenting anything.
> > 
> > 
> > It is xpath problem and it could be solved with below changes.
> > source code: xpath["like_image"] = { "like": "//section/span/button/div/span[_[local-name()='svg']/@aria-label='Like']", "unlike": "//section/span/button/div/span[_[local-name()='svg']/@aria-label='Unlike']", "play": "//*/span[contains(@aria-label, 'Play')]", }
> > the changes: "like": "//section/span/button/div/span[*[local-name()='svg']/@aria-label='Like']/../.."
> 
> It's working! Thank you dude!

you are welcome

**Comment by Scarlatss** [comment]
hello in what file do i have to change this ?
like_util ?

**Comment by kharazian** [comment]
Xpath_compile.py
