### ISSUE TITLE
Raspberry P4 - Cannot detect post media type

### ISSUE THREAD

**Issue by JTK-Rob** [InstaPy/InstaPy#6350]
Hi, I installed on my Raspberry P4 InstaPy to test some bot solutions for instagram.
Running the program gives me this error:

Cannot detect post media type

## InstaPy configuration
Python 3.7.3
Firefox ESR

Thanks 
JK

**Comment by kharazian** [comment]
> > No, you are not block. It is xpath problem which could not click on like element. You can test this code.
> > > pip install git+https://github.com/kharazian/InstaPy/tree/master
> 
> Hi is problem is video and images, I am testing but the system does not apply comments or likes to anyone, always an error


Could you send the error. I use this code without any problem.

**Comment by JTK-Rob** [comment]
> > > No, you are not block. It is xpath problem which could not click on like element. You can test this code.
> > > > pip install git+https://github.com/kharazian/InstaPy/tree/master
> > 
> > 
> > Hi is problem is video and images, I am testing but the system does not apply comments or likes to anyone, always an error
> 
> Could you send the error. I use this code without any problem.

Hi Kharazian, I noticed that the likes you have videos and photos are put without problems now, but the comments are not left.
There is a solution ??
