### ISSUE TITLE
Instapy Login A/B and Selenium hide error

### ISSUE THREAD

**Issue by Alexjpinto** [InstaPy/InstaPy#6351]
Hello, i have 2 problems

1º  Hide Selenium Extension: error

2º Login A/B test detected! Trying another string...
     Could not pass the login A/B test. Trying last string...
     
Can you help me, thanks in advance

**Comment by Alexjpinto** [comment]
Thank you, I will have that in mind. 


I'm using droplets,
On my pc everything it's OK,
But on my droplet from digital Ocean with "headless = True " I'm getting that error.

Maybe because of the location of the machine.

**Comment by elulcao** [comment]
> 1º Hide Selenium Extension: error

1º Hide Selenium Extension: error
>>> Use a FF ESR version, the one that doesn't have the web.driver flag for automation in read mode.

2º Login A/B test detected! Trying another string...
>>> After fixing step 1, check if issue number 2 disappears.
