### ISSUE TITLE
[BUG] Tries to lookup and follow non-existent users

### ISSUE THREAD

**Issue by Nathan13888** [InstaPy/InstaPy#6352]
This bug seems to occur when using the follow feature where users who liked a post in feed will be interacted with. However, it seems like InstaPy tries to follow a random label that is scraped from the webpage (like the date of a post).

## Expected Behavior
InstaPy only looks up profiles of real people and not other elements on page.

## Current Behavior
```
[xxx]  Got 4 likers shuffled randomly whom you can follow:
['www', 'yyy', 'SEPTEMBER 30', 'zzz']
...
[xxx]  Failed to get followers count of 'b'SEPTEMBER 30''  ~empty list
[xxx]  Failed to get following count of 'b'SEPTEMBER 30''  ~empty list
[xxx]  User: 'SEPTEMBER 30'  |> followers: unknown  |> following: unknown  |> relationship ratio: unknown
[xxx]  ~could not check if profile is public or private
[xxx]  --> Not a valid user: --> Sorry, could not check if profile is public or private
```

## Possible Solution (optional)

Better scraping and filtering of possible users to follow.

**Comment by elulcao** [comment]
@Nathan13888 

are you willing to try the following fix, basically it ignores the "words" that has spaces in between, 
Somehow, the element.text returns extra metadata as valid string but this cannot be used to access real users. 


```python
# instapy/util.py
def extract_text_from_element(elem):
    """
    As an element is valid and contains text, extract it and return
    Added filter to words that has spaces between them, they for sure are not valid username
    Error looks like: "User: 'NOVEMBER 5'  |> followers: unknown  |> following: unknown  |> relationship ratio: unknown"
                       ^^^^^^^^^^^^^^^^^
    """

    # if element is valid and contains text withou spaces
    if elem and hasattr(elem, "text") and elem.text and not re.search("\s", elem.text):
        return elem.text

    # if the element is not valid, return None
    return None
```

**Comment by Nathan13888** [comment]
Hi @elulcao,

This seems like an interesting way to check for this prompt. Looking at the logic of this seemingly trivial change, **it seems to make sense to look for whitespaces** within the text. However, this is assuming that instagram tags/names could not have spaces in the name which appears to be true.

But I'm not sure since based on Issue #5503, it seems that some possible **text values could be hashtags which won't have any spaces**.

Lastly, I would help test this change however I'm not current using InstaPy anymore for the time being...

Perhaps someone else who would like to see such fix go into action should give this promising solution a try. @tobeyond??
