### ISSUE TITLE
Cannot detect post media type. Skip

### ISSUE THREAD

**Issue by omarsameh** [InstaPy/InstaPy#6355]

**Comment by goproists** [comment]
I have the same error. Could you please check once again and confirm if the error is showing something like the next rows:

like_util.py", line 633, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

--->> Another error shown is:

instapy.py", line 1957, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(

.--->> Could you please check if you have similar error codes?

My complete trace is the nexxt:

Traceback (most recent call last):

  File "c:\Users\gopro\OneDrive\Documents\Programmer\Python\9 timgrossman_instapyorg-quickstart-master\quickstart.py", line 32, in <module>
    session.like_by_tags(["paessaggiodallmessico"], amount=5)


  File "C:\Users\gopro\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 1957, in like_by_tags
    **inappropriate, user_name, is_video, reason, scope = check_link(**


  File "C:\Users\gopro\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\**like_util.py", line 633, in check_link
    media = post_page[0]["shortcode_media"]**
KeyError: 0

If you have similar error then means that maybe something on IG parameters has been changed and this is a real issue,+

Thank you!

**Comment by lextale** [comment]
I have the "Cannot detect post media type. Skip..." error too every time I try to use like_by functions. Also, instapy cannot fetch links for analysis. I don't know if these two are related.

**Comment by lextale** [comment]
I have linux. I run quickstart.py . This is the result.

![Screenshot_3](https://user-images.githubusercontent.com/43947733/137592791-42a099a2-7b2c-4c60-9ecc-3f875f15f5ed.png)
![Screenshot_2](https://user-images.githubusercontent.com/43947733/137592788-6f34f71c-eac9-445c-bdbb-6c8e63e71af2.png)
