### ISSUE TITLE
like_by_feed and like_by_tags

### ISSUE THREAD

**Issue by Alexjpinto** [InstaPy/InstaPy#6369]
## Current Behavior

![bug_instapy](https://user-images.githubusercontent.com/62337176/138078486-7babe00b-8f6e-4bf4-a439-3fe6fc7dd6b8.jpg)
## InstaPy configuration
Workspace in use: "C:/Users/***-/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2021-10-20 11:22:48] [blue_k4_gsxr]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2021-10-20 11:22:48] []  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2021-10-20 11:22:49] [r]  - Internet Connection Status: ok
INFO [2021-10-20 11:22:49] []  - Current IP is "ip" and it's from "country"
INFO [2021-10-20 11:22:49] []  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2021-10-20 11:22:49] []  - window.navigator.webdriver response: None
INFO [2021-10-20 11:22:49] []  - Hide Selenium Extension: ok
INFO [2021-10-20 11:22:52] []  - Cookie file for user '***' loaded...

### Like_util.py
line: 883
                        post_category = element.find_element_by_xpath(
                            "//a[@href='/p/"
                            + post_href.split("/")[-2]
                            + "/']/div[contains(@class,'CzVzU')]/child::div/*[name()='svg']"
                        ).get_attribute("aria-label")

### python file
file.py 

`insta_username = input("User Name:\n")
insta_password = input("Password:\n")

session = InstaPy(username=insta_username, password=insta_password,
                  browser_executable_path=r"C:\firefox_esr\firefox.exe",
                  headless_browser=True)

session.login()

session.set_do_like(True, percentage=90)
session.like_by_feed(amount=100, randomize=False, unfollow=False, interact=True)
session.like_by_tags(['tagexemple'],amount=100,interact=True)`

**Comment by elulcao** [comment]
> @omarsameh thanks for the tip,
> I will try it tomorrow, then I give you the feed back 👍

Hey there 
The new version in GitHub now is the same for pypi. No extra commands from now.
