### ISSUE TITLE
 UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead

### ISSUE THREAD

**Issue by metapodcod** [InstaPy/InstaPy#6393]
```
InstaPy\venv\lib\site-packages\selenium\webdriver\remote\webelement.py:358: UserWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  warnings.warn("find_elements_by_* commands are deprecated. Please use find_elements() instead")
```

instapy version 0.6.14
windows 10

**Comment by elulcao** [comment]
@metapodcod 

Update requirements.txt from `selenium>=3.141.0` to `selenium>=3.141.0,<= 3.150.0`
this error comes from the deprecated `find_elements_by_` in selenium 4.0 and later.

Pinning down the version is not the final solution, but works for now to avoid the message.
