### ISSUE TITLE
Comments percentage

### ISSUE THREAD

**Issue by rahulkapoor90** [InstaPy/InstaPy#64]
@timgrossmann pls mention somewhere in readme.md that changing comments percentage to 100 could lead to a temporary ban and account password reset by Instagram. I didn't knew this and suffered. lol

**Comment by razvanilin** [comment]
Instagram checks for comment duplicates to counter the spammers. Yes, it's not a good idea to have 100% comment rate and you should limit to around 30%. The best idea is to have a huge list of different comments so they don't trigger Instagram's anti-bot protection.

Also make sure the you are not following more than 250 accounts per day and you should also limit your likes below 300/hour. If you do all these then you should be safe from getting caught by a ban.

**Comment by eduardocalazansjr** [comment]
It's on the disclaimer, 30% ratio is pretty extensive use, i think.

The ban is not only for comments, but for likes too.
Excessive likes/hour could lead you to an temp ban/perma ban.
Excessive comments/repetitive comments also lead you to the same cenario.

**Comment by rahulkapoor90** [comment]
yeah.. okay. thanks!
