### ISSUE TITLE
Installation issue : py get-pip.py

### ISSUE THREAD

**Issue by jeffreylm** [InstaPy/InstaPy#640]
Hello Everyone,

I am busy re-installing Instapy on a new system. I have reached the step of py get-pip.py, but when I type it in I get the error:  python.exe: can't open file 'get-pip.py': [Errno 2] No such file or directory

I have executed all the steps from the Advance setup steps. One side note, I didn't reboot when having done the P 

Could someone assist me in this?

Greetings,
Jeffrey

**Comment by webbyy2** [comment]
currently having the same issue, did you find a solution?

**Comment by deendee** [comment]
I had the same problem and I just skipped it the first time I installed and everything was OK.  However I had to update everything and again had this issue so I looked a bit further.  I'm a bit of a novice at these things (I'm more into hardware), but here is how I got around it...

As stated in this thread - https://github.com/timgrossmann/InstaPy/issues/422 you need to find the get-pip.py file download it and save it as "get-pip.py" - here it is again https://bootstrap.pypa.io/get-pip.py.  I put it in the python36-32\scripts folder.

Make sure your terminal or powerShell is in the python36-32\scripts folder and type...
py get-pip.py

Hope that helps someone.

**Comment by constantinosbou** [comment]
Helped me a lot Deendee! Thanks

**Comment by CheapInMadrid** [comment]
Hello I am getting the same problem and a big novice with code...the link above opens into a code...in what format do I put it into the pythonscripts folder...do I copy it and paste onto notepad...?

**Comment by 3Ned5L1f3** [comment]
@deendee ! You rock! for google purposes: I was getting "no such file or directory" when trying to install InstaPy part 3.1 running py get-pip.py and Deendee's solution worked great!

**Comment by yg2dras1** [comment]
@deendee i'm running python 3.6.3, but can't seem to find the folder python36-32\scripts...where can i find it please??

**Comment by yg2dras1** [comment]
@deendee nevermind...i found it! and it worked!! thank you!

**Comment by stoicavali91** [comment]
@yg2dras1  can you tell me how did you save the code from the link ? I don't know what to do with it. i saved it as a py, but the command still can't find it. Thanks

**Comment by ksprashant** [comment]
@stoicavali91 
I had the error as the OP, so I moved the downloaded 'get-pip.py' file to my Python36/Scripts/directory; then I used cd in command prompt to open the directory Python36/Scripts ; and then 'python get-pip.py' command executed successfully.
