### ISSUE TITLE
media = post_page[0]["shortcode_media"] - Like action is failing  instapy-0.6.14

### ISSUE THREAD

**Issue by sonuhawk** [InstaPy/InstaPy#6401]
I am using master branch.

Traceback (most recent call last):
  File "E:\Study\Python_Automation\Insta_Commentor\quickstart.py", line 56, in <module>
    session.like_by_tags(my_hashtags, amount=90, media=None)
  File "C:\Users\sonu3\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 1977, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\sonu3\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\like_util.py", line 618, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

**Comment by sonuhawk** [comment]
Users Should add Profile Pic and Bio to void this issue.

**Comment by kazeox** [comment]
> Users Should add Profile Pic and Bio to void this issue.

Why do you say that ? I've got both and the same issue...

**Comment by kharazian** [comment]
I have same problem

**Comment by Kbcaah** [comment]
I have the same problem!

**Comment by Graticool** [comment]
same

**Comment by casterock** [comment]
same problem, any solution?

**Comment by mouad73** [comment]
Same problem, it's worked before two days, but now I have this problem

**Comment by Graticool** [comment]
Yep, it was working fine for me up until about 2 days ago (1/18/21?).  I don't know if Instagram updated, Selenium updated, or something else changed?  This happenned to me last year, and [this guy] (https://github.com/schealex/InstaPy) provided a [good solution](https://github.com/InstaPy/InstaPy/issues/6189) at the time, maybe check those out?

**Comment by shachar-ash** [comment]
I'm experiencing the same issue

**Comment by simonpacis** [comment]
Same here.

**Comment by hscanlan** [comment]
same exact issue here.

**Comment by camillevingere** [comment]
Same issue

**Comment by carrasboy** [comment]
same here...

**Comment by Adrianahwjsgsj** [comment]
I have the same problem, would guess that instagram updated...

**Comment by Sky1ng** [comment]
same here for me

**Comment by giulioco** [comment]
same ✋

**Comment by giulioco** [comment]
[Here's the fix ](https://github.com/InstaPy/InstaPy/issues/6472#issuecomment-1022552975)

**Comment by adrielkirch** [comment]
> ep, it was w

Have you already solve it ?

**Comment by adrielkirch** [comment]
> Users Should add Profile Pic and Bio to void this issue.

Have you fixed this problem? Im trying to find a solution everywhere

**Comment by adrielkirch** [comment]
> same here for me

Have you already repaired?

**Comment by RikoIV** [comment]
Same problem

**Comment by lucasomigli** [comment]
is there a workaround on this? Do we know why this is happening?

**Comment by mbamrico9** [comment]
There's a fee now.

**Comment by wolf2000-hub** [comment]
I have the same problem

**Comment by mbamrico9** [comment]
There is a fee

**Comment by Graticool** [comment]
@mbamrico9 you're the second person to say there is a fee, please elaborate on what that means and how its related to the issue.  Thanks
