### ISSUE TITLE
cyrillic tag

### ISSUE THREAD

**Issue by jufelka** [InstaPy/InstaPy#642]
Hi. I need to use cyrillic tags (for example 'животные') but can't run script because of error 
`SyntaxError: Non-UTF-8 code starting with '\xec' in file start.py on line 16, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

**Comment by diveu** [comment]
Is there any solution to this? Did you try specifically defining string as unicode characters with smth like `str = u"животные"`?

**Comment by voskresla** [comment]
use 
`# coding=utf-8`
in the first line of *.py file

**Comment by jufelka** [comment]
Thank you, it works!

**Comment by jufelka** [comment]
I've made reinstall to another server and now have the same problem with cyrillic tags. I got error "UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)"
