### ISSUE TITLE
Remove sleep delay in instapy.py

### ISSUE THREAD

**Issue by potentowl** [InstaPy/InstaPy#6420]
After the bot follows roughly 10 people it sleeps roughly 10 minutes, how can i edit this code so it only sleeps 1-2 minutes instead of 10 minutes ?????????????

```

                        # Take a break after a good following
                        if followed_new >= relax_point:
                            delay_random = random.randint(
                                ceil(sleep_delay * 0.85), ceil(sleep_delay * 1.14)
                            )
                            sleep_time = (
                                "{} seconds".format(delay_random)
                                if delay_random < 60
                                else "{} minutes".format(
                                    truncate_float(delay_random / 60, 2)
                                )
                            )
                            self.logger.info(
                                "------=>  Followed {} new users ~sleeping "
                                "about {}".format(followed_new, sleep_time)
                            )
                            sleep(delay_random)
                            relax_point = random.randint(7, 14)
                            followed_new = 0
                            pass
```

**Comment by CodeMasterBond** [comment]
Can you please repeat your comment 1 more time. Your telling me, that when your bot follows 10 accounts, you wait 10 minutes. That’s about a one minute wait every user followed. Right? So isn’t that what your going for?

**Comment by potentowl** [comment]
I make the bot sleep 1 minute after each follow with simple sleep(60), how
do i remove this sleep function that sleeps ~10 minutes randomly.

**Comment by CodeMasterBond** [comment]
Well that makes sense and the function is working properly. If you set the code to sleep 1 minute per follow, then after 10 follows or so, the code should sleep 10 minutes, right? So what is your issue?

**Comment by potentowl** [comment]
@CodeMasterBond Yes my code i added sleeps 60 seconds after each follow i want to remove the
