### ISSUE TITLE
THIS SHIT DONT WORK!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by jayjay992** [InstaPy/InstaPy#6427]
YALL POST THESE DAMN SCRIPTS AND THEY DONT HALF WORK AND DEN YALL DONT WANT TO HELP FIX THE BUGS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by GebbenPlayz** [comment]
ok

**Comment by gerssivaldosantos** [comment]
Shutdown, man
