### ISSUE TITLE
 inappropriate, user_name, is_video, reason, scope

### ISSUE THREAD

**Issue by devrohansharma** [InstaPy/InstaPy#6435]
## Expected Behavior
Though it's working fine with other Account why am I getting the issue with this one?

## Current Behavior
  File "C:\Users\ishus\Desktop\bounds_follow_tags.py", line 20, in <module>
    session.like_by_tags(['hashtag_eg1 ','hastag_example2 '],amount=20)
  File "C:\Users\ishus\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 1977, in like_by_tags
    
inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\ishus\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\like_util.py", line 618, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0
## Possible Solution (optional)
update like_util.py

**Comment by Kbcaah** [comment]
I'm having the same issue.

**Comment by ziqingc** [comment]
I also have the same issue.

**Comment by maury37** [comment]
Hi @elulcao, 

I have the same issue & I hope your fix will help me.
It might be a beginner question, but how can I use your fix ? 
If I do on my RPi "pip3 install instapy==0.6.16 --upgrade --user", there is no matching distribution.

Is there a way to update your fix without doing it manually file per file ? 
Thanks !!! :)

**Comment by gabinfoulard** [comment]
Hi everyone,

I have the same problem with Instapy.
I tried the #6233 and #6381 issues.

The error message is always the same :

`Traceback (most recent call last):
  File "C:\InstaPy_Bot\start_instapy_all.py", line 103, in <module>
    session.like_by_tags(hashtags, amount=int(nombre_like))
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instapy\instapy.py", line 1977, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instapy\like_util.py", line 618, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0`

i tried to install manually these versions with the .bat command :
`pip install -I https://github.com/user/project/zipball/master`

-https://github.com/elulcao/InstaPy/tree/instapy-6352
Result : Same error

-https://github.com/schealex/InstaPy/zipball/develop
Result : the script cannot detect the type of media when it goes on the hashtag page

-https://github.com/timgrossmann/InstaPy/zipball/master 
Result : is not valid (404 error) and it is in the head of the official page of instapy !! : https://instapy.org/additional-information/

I'm learning GihHub each day but I think the @elulcao patch will be added to the 0.6.16 version.

The computer which is not liking proprely the script is not my computer, it have some software like Norton Security which maybe can create conflicts with instapy ??

Firefox version is the same with the two computers : 96.0 (64bit)

On my personnal computer, it works fine so I understand NOTHING !!

Need help plz.

Thanks to all :))

**Comment by elulcao** [comment]
The PR has not been merge, that's why that version doesn't exist 
Reviewing today,

**Comment by maury37** [comment]
Hi @elulcao, 

Thanks for merging ! 
Unfortunately, I just tried with 0.6.16 & I still get the same issue..

Any idea ?

**Comment by elulcao** [comment]
> Hi @elulcao,
> 
> Thanks for merging ! Unfortunately, I just tried with 0.6.16 & I still get the same issue..
> 
> Any idea ?

Hi @maury37 
is the same error for post_page[0]["shortcode_media"]?
Im assuming that you are using a ESR FF version, is this correct

**Comment by maury37** [comment]
@elulcao 

Description:	Ubuntu 21.04
Mozilla Firefox 95.0.1

Does that answer your question ?
If not, let me know which command I should enter !
