### ISSUE TITLE
Does randomize=False in like_by_tags mean it is up-to-date?

### ISSUE THREAD

**Issue by its-ogawa** [InstaPy/InstaPy#6437]
## Expected Behavior
The following page has the following explanation for randomize
```
Randomize Randomize: Determines whether to like the first post. on the first post, or select it randomly.
```
https://github.com/InstaPy/InstaPy/blob/master/docs/actions.md#like-by-tags

Does "first" in this context mean "latest"?

**Comment by CodeMasterBond** [comment]
Yes, I'm pretty sure it means latest.

**Comment by Sergej99** [comment]
> Yes, I'm pretty sure it means latest.

could you please help me with my issue 

https://github.com/InstaPy/InstaPy/issues/6434

**Comment by its-ogawa** [comment]
@CodeMasterBond 
Thank you.
It made me feel more confident.
