### ISSUE TITLE
Issue with raspberrypi how to doc 

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#644]
When following the Firefox guide everything works until I try 
`sudo apt-get install firefox`

The issue is that the package has an unment dependency of libhunspell 1.3-0 (>=1.3-3)

It appears Raspbian has updated the libhunspell libary to 1.4-0 and thus it doesn't work with the version of firefox in the guide. 

Has anyone run into this issue and resolved? Been googling for a while and can't get an answer.

**Comment by gitpatrickhub** [comment]
Found this page, which sounds like the issue you've encountered;

```
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833627
```

Have you tried to install with the specified package below?
Fixed in versions firefox-esr/45.3.0esr-1~deb8u1, firefox-esr/45.3.0esr-1

**Comment by ghost** [comment]
@gitpatrickhub I will trail it tonight and let you know how I go thanks.

**Comment by ghost** [comment]
@gitpatrickhub tried to install and got the below error. Could be that I am not entering correctly in terminal. 

`sudo apt-get install firefox=firefox-esr/45.3.0esr-1~deb8u1, firefox-esr/45.3.0esr-1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package firefox=firefox-esr
E: Release '45.3.0esr-1' for 'firefox-esr' was not found
`

**Comment by gitpatrickhub** [comment]
@imakethefish found this page which provides instructions for installation based upon version of Debian installation;

http://mozilla.debian.net/

Make sure to execute the removal steps and then try the above. If it works, we can ask @timgrossmann to update the install on raspberry pi page.

**Comment by ghost** [comment]
Current version of esr v52 is working so no need to install v45. 

Just run `sudo apt-get install firefox-esr` 

I skipped steps 20 - 23 and did steps 17 - 19 just to be sure. 

@gitpatrickhub thanks for your help really appreciate you

**Comment by ghost** [comment]
Had an issue with my session today below error:

`[Errno 104] Connection reset by peer
Message: Element is not currently visible and so may not be interacted with
Stacktrace:
    at fxdriver.preconditions.visible (file:///tmp/tmplR3HZi/extensions/fxdriver@googlecode.com/components/command-processor.js:10092)
    at DelayedCommand.prototype.checkPreconditions_ (file:///tmp/tmplR3HZi/extensions/fxdriver@googlecode.com/components/command-processor.js:12644)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmplR3HZi/extensions/fxdriver@googlecode.com/components/command-processor.js:12661)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmplR3HZi/extensions/fxdriver@googlecode.com/components/command-processor.js:625)
`

**Comment by gitpatrickhub** [comment]
@imakethefish Does this occur each time you run the script or was this a one time occurrence? Also, can you include your quickstart.py file? I'm not an expert, but I'm thinking the page didn't load correctly or in time for the next click.


@timgrossmann I think the how to doc needs to be updated; steps 20-23 can be replaced with the link to http://mozilla.debian.net/ so people can enter their configuration and get the correct commands to install firefox based on their entries.

**Comment by ghost** [comment]
@gitpatrickhub received a new error in today's sessions below. I've increased the page delay to hopefully fix. I will come back tonight after today's session. 

`Message: The element reference of <a class="_b93kq"> stale: either the element is no longer attached to the DOM or the page has been refreshed

Message: Failed to decode response from marionette

Message: Failed to decode response from marionette

Message:`


`InstaPy(username='xxx', password='xxx.', use_firefox=True, page_delay=25)\
            .set_switch_language(False)\
            .login()\
            .set_dont_like(tag_list)\
            .set_dont_include(friendList)\
            .set_ignore_if_contains(ignore_list)\
            .set_do_comment(enabled=False, percentage=10)\
            .set_do_follow(enabled=True, percentage=10, times=1)\
            .set_comments(comments=normalComments)\
            .set_use_clarifai(enabled=True, api_key='xxx')\
            .clarifai_check_img_for(['nsfw'])\
            .clarifai_check_img_for(['technology', 'screen', 'data', 'internet'], comment=True, comments=codingComments)\
            .clarifai_check_img_for(['lake', 'landscape', 'mountain'], comment=True, comments=natureComments)\
            .clarifai_check_img_for(['food', 'lunch', 'dinner'], comment=True, comments=foodComments)\
            .unfollow_users(amount=randint(followedLastsesh, followedLastsesh * 1.5))\
            .like_by_tags((like_tag_list), amount=tag1)\
            .like_by_tags((like_tag_list, 1), amount=tag2)\
            .like_by_tags((like_tag_list, 1), amount=tag3)\
            .end()`

**Comment by gitpatrickhub** [comment]
@imakethefish maybe double check geckodriver version against this page; https://github.com/mozilla/geckodriver/releases

**Comment by ghost** [comment]
@timgrossmann @gitpatrickhub version 0.19.0 geckodriver fixed the issue.

**Comment by gitpatrickhub** [comment]
@imakethefish what configuration did you land on (versions of Debian, Firefox, Selenium, Python, Geckodriver)? Do all features work as designed, i.e., Liking, Commenting, Following, Unfollowing? 

#660

**Comment by Siksel** [comment]
@imakethefish bumping @gitpatrickhub 's question.  I've been struggling for days trying to get things running on rpi.

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
