### ISSUE TITLE
Python beginner question

### ISSUE THREAD

**Issue by sofiamatulis** [InstaPy/InstaPy#645]
I have cloned the repo, installed Python 3.6, Sellenium, pyvirtualdriver (Although I am not sure if I have to save it somewhere).

I have two questions: 

1) How do I set up path for PY command. -- What does that mean exactly? And what does it do? I have googled that, and I don't have any Python experience so I am having a hard time understanding it.

 2) I have downloaded chromedriver and put it in the assets, but I am having trouble figuring out if what I put there makes sense.

When I run chromedriver, I get this error: `Only local connections are allowed.
[0.011][SEVERE]: bind() returned an error, errno=48: Address already in use (48)`. I have tried killing it, but it says there's nothing to kill.

And when I run python quickstart.py, I get this error Message: '`chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`, which I am assuming is related to the fact that I didn't set a path.

If I run python instapy/login_util.py, I get `File "instapy/login_util.py", line 2, in <module>
    from .time_util import sleep
ValueError: Attempted relative import in non-package`.

Sorry for the long message, I am just hoping to understand everything. I have read the docs and questions from the repo, but I still feel very confused

**Comment by ahmadudin** [comment]
@sofiamatulis 

1. From the error message that you got when run quickstart, your python command path is already correct.
2. What you assumed about the path, is the chromedriver path. 

I am assuming the problem is that you are not placing chromedriver file in the right folder. The chromedriver should be placed on asset folder.

**Comment by sofiamatulis** [comment]
![screen shot 2017-09-12 at 9 14 18 pm](https://user-images.githubusercontent.com/19962891/30355141-61410208-97ff-11e7-86e3-32d57d07c7c8.png)
 
@ahmadudin Thank you for the quick reply! I have actually placed the chromedriver in the correct folder, (what was downloaded). Is that the correct way of doing it? Or maybe I need to re-name it?

**Comment by sofiamatulis** [comment]
@ahmadudin omg! I changed the name to chromedriver and it works :D thanks so much!!!

**Comment by ahmadudin** [comment]
@sofiamatulis lol, great!
