### ISSUE TITLE
Ubuntu server // Hide Selenium Extension: error

### ISSUE THREAD

**Issue by celestinsoum** [InstaPy/InstaPy#6452]
I use Droplet on Digital Ocean _(Ubuntu 20.04 (LTS) x64)_

When I start my quickstart.py, it's fail cause "Hide Selenium Extension: error", I don't found solution for this time, somebody can help me ?

> InstaPy Version: 0.6.15
 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-01-03 23:29:27] [xxxxx]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2022-01-03 23:29:27] [xxxxx]  -- Connection Checklist [1/2] (Internet Connection Status)
INFO [2022-01-03 23:29:28] [xxxxx]  - Internet Connection Status: ok
INFO [2022-01-03 23:29:28] [xxxxx]  - Current IP is "64.227.120.175" and it's from "Germany/DE"
INFO [2022-01-03 23:29:28] [xxxxx]  -- Connection Checklist [2/2] (Hide Selenium Extension)
INFO [2022-01-03 23:29:28] [xxxxx]  - window.navigator.webdriver response: True
WARNING [2022-01-03 23:29:28] [xxxxx]  - Hide Selenium Extension: error
INFO [2022-01-03 23:29:31] [xxxxx]  - Cookie file not found, creating cookie...
WARNING [2022-01-03 23:29:45] [xxxxx]  Login A/B test detected! Trying another string...
WARNING [2022-01-03 23:29:50] [xxxxx]  Could not pass the login A/B test. Trying last string...
......................................................................................................................
CRITICAL [2022-01-03 23:30:24] [xxxxx]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2022-01-03 23:30:25] [xxxxx]  Sessional Live Report:
|> No any statistics to show
[Session lasted 1.04 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-01-03 23:30:25] [xxxxx]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by rubenRP** [comment]
Same problem here. I tried to install a previous version of Firefox and geckodriver (https://www.giters.com/InstaPy/InstaPy/issues/6169) but doesn't work either. Also doesn't work in Mac when headless=true, same warning.

**Comment by ericmil87** [comment]
Same issue here... have tried everything :(

**Comment by CodeMasterBond** [comment]
@celestinsoum @rubenRP @ericmil87 
Hey! The issue you are experiencing is not with Selenium but rather your login and password info. I receive the same message on both my raspberry pi and pc when running instapy, yet the program still functions as normal. Making the warning "Hide Selenium Extension: error," completely alright for users. To fix your issues, make sure you have the correct quickstart file when you run instapy, or type in your login and password info when you are typing out in the command line. For example...
--------------------------
Lets say this is your quickstart.py file....
''
# imports
from instapy import InstaPy
from instapy import smart_run
from instapy import set_workspace


# set workspace folder at desired location (default is at your home folder)
set_workspace(path=None)

# get an InstaPy session!
session = InstaPy()

with smart_run(session):
    # general settings
    session.set_dont_include(["friend1", "friend2", "friend3"])

    # activity
    session.like_by_tags(["natgeo"], amount=10)
''
Then when you are running instapy, you would type... ``python3 quickstart.py --username qwerty1 --password qwerty12`` and replace qwerty1 with your username and qwerty2 with your password. You would type this wherever you are running your code, so it could be the command line, Visual Studio Code, or any other IDE's. I prefer Visual Studio Code personally.
------------------------------
Another way of logging in to instapy is through the quickstart file itself. So before you include ``session = InstaPy`` in your code, make sure to define your username and password as shown below...
``insta_username = 'qwerty1'
insta_password = 'qwerty2'``
And just as before, replace qwerty1 to your username and qwerty2 to your password. Then when you call the command ``session = InstaPy``, be sure to type ``username=insta_username`` and ``password=insta_password`` in the function. An example of this looks like...
``session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)``

FULL QUICKSTART.PY FILE BELOW
``
# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = ''
insta_password = ''

comments = ['Nice shot! @{}',
        'I love your profile! @{}',
        'Your feed is an inspiration :thumbsup:',
        'Just incredible :open_mouth:',
        'What camera did you use @{}?',
        'Love your posts @{}',
        'Looks awesome @{}',
        'Getting inspired by you @{}',
        ':raised_hands: Yes!',
        'I can feel your passion @{} :muscle:']

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
  """ Activity flow """		
  # general settings		
  session.set_dont_include(["friend1", "friend2", "friend3"])		
  
  # activity		
  session.like_by_tags(["natgeo"], amount=10)

  # Joining Engagement Pods
  session.set_do_comment(enabled=True, percentage=35)
  session.set_comments(comments)
  session.join_pods(topic='sports', engagement_mode='no_comments')``

Good luck,
CodeMasterBond

**Comment by rubenRP** [comment]
@celestinsoum Did you solve this?. The previous answer about credentials doesn't work. It does not related with user or password. If you remove headless in a local environment works, but not with headless.

**Comment by celestinsoum** [comment]
Yes, I has instal FF-esr 77 and it fixed it

**Comment by ericmil87** [comment]
I tried install FF-esr and also checked the credentials but nothing works

**Comment by nhondong** [comment]
same error here

**Comment by Chessy11** [comment]
Gekodriver and firefox versions must match.

**Comment by Chessy11** [comment]
Geckodriver and Firefox version must match. maybe there is the issue with path parrameter in selenium service.py file
