### ISSUE TITLE
Invalid Like Element

### ISSUE THREAD

**Issue by alexpzpz** [InstaPy/InstaPy#6455]
Hi, I am not good at programming. But when I like it, it says that the like button was not found. I configured Xpath_compile.py in different ways, nothing changes anyway

1 option
`xpath["like_image"] = {
    "like": "//section/span/button/div[*[local-name()='svg']/@aria-label='Like']/../..",    
    "unlike": "//section/span/button/div[*[local-name()='svg']/@aria-label='Unlike']",
    "play": "//*/span[contains(@aria-label, 'Play')]",
}`

2 option
`xpath["like_image"] = {
    "like": "//section/span/button/div[*[local-name()='svg']/@aria-label='Like']",    
    "unlike": "//section/span/button/div[*[local-name()='svg']/@aria-label='Unlike']",
    "play": "//*/span[contains(@aria-label, 'Play')]",
}`
3 options
`xpath["like_image"] = {
    "like": "/html/body/div[1]/section/main/div/div/article/div[3]/section[1]/span[1]/button[*[local-name()='svg']/@aria-label='Like']",
    "unlike": "/html/body/div[1]/section/main/div/div/article/div[3]/section[1]/span[1]/button[*[local-name()='svg']/@aria-label='Unlike']",
}`

what to do ?

**Comment by alexpzpz** [comment]
Code
`session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    """ Activity flow """
    # general settings    
    session.like_by_tags(["#катаемся"], amount=20)
    session.set_dont_like(["#порно", "#продажа", "#продать", "#автомойка", "#сервис"])`

Log
_INFO [2022-01-07 22:11:59] [carcollapse]  --> Invalid Like Element!
INFO [2022-01-07 22:12:02] [carcollapse]  Like# [11/24]
INFO [2022-01-07 22:12:02] [carcollapse]  https://www.instagram.com/p/CYb2d1zMV_L/
INFO [2022-01-07 22:12:05] [carcollapse]  Image from: b'yy.leoo_'
INFO [2022-01-07 22:12:05] [carcollapse]  Image link: b'https://www.instagram.com/p/CYb2d1zMV_L/'
INFO [2022-01-07 22:12:05] [carcollapse]  Description: b'\xe2\x9d\xa4\xef\xb8\x8f\xd...._

**Comment by CodeMasterBond** [comment]
Try this.... ``xpath["like_image"] = {
    "like": "//*[contains(@class, 'fr66n')]/button/div/*[*[local-name()='svg']/@aria-label='Like']/*",
    "unlike": "//*[contains(@class, 'fr66n')]/button/div/*[*[local-name()='svg']/@aria-label='Unlike']/*",
    "play": "//*/span[contains(@aria-label, 'Play')]",
}``

**Comment by alexpzpz** [comment]
I poked around 100,500 options, and picked up a worker, put a like.
```
xpath["like_image"] = {
    "like": "//section/main/div/div/article/div/div/div/div/section/span/button/div/span[*[local-name()='svg']/@aria-label='Like']/../..",
    "unlike": "//section/main/div/div/article/div/div/div/div/section/span/button/div/span[*[local-name()='svg']/@aria-label='Unlike']",
    "play": "//section/main/div/div/article/div/div/div/div/div/span[contains(@aria-label, 'Play')]",
}
```

**Comment by alexpzpz** [comment]
> Try this.... `xpath["like_image"] = { "like": "//*[contains(@class, 'fr66n')]/button/div/*[*[local-name()='svg']/@aria-label='Like']/*", "unlike": "//*[contains(@class, 'fr66n')]/button/div/*[*[local-name()='svg']/@aria-label='Unlike']/*", "play": "//*/span[contains(@aria-label, 'Play')]", }`

I tried to address the class directly, he wrote the same thing to me. Thank you)

**Comment by gerssivaldosantos** [comment]
Already found the solution for issue  ?

**Comment by alexpzpz** [comment]
> Already found the solution for issue ?

my last message

**Comment by Calamigos** [comment]
Thank you that worked for me.
