### ISSUE TITLE
Ignoring or don't follow again, in follow_user_followers

### ISSUE THREAD

**Issue by theKoap** [InstaPy/InstaPy#646]
Hi,

I tried and search into the method, but how is it possible to add an option like Times, that allow to not followed someone X times because we already unfollowed them ?

And if we add a name of someone in : 
session.set_dont_include(['nofriend1','nofriend2', 'unfollowed1'])
Does it also exclude nofriend1, nofriend2, unfollowed1to be follow ?

Thank you,

**Comment by timgrossmann** [comment]
@theKoap The times feature is already implemented with the 
```python
#default enabled=False, follows ~ 10% of the users from the images, times=1 (only follows a user once (if unfollowed again))

session.set_do_follow(enabled=True, percentage=10, times=2)
```

Yes it also excludes them from following.

**Comment by theKoap** [comment]
Just to be sure, but times = 1 means that while instapy is launched, if it unfollowed userA, it will not follow again userA.

But if I close instapy and launch it again, it didn't save that I unfollowed userA, and it will follow it again, is that right ? I tested it with two people I unfollowed recently with instapy, but they follow back again when I used 
`
accs = ['therock','natgeo']
session.follow_by_list(accs, times=1)`
Or is that because follow_by_list don't care about times ?

Is there a way to keep in log that someone was already unfollowed to be sure to not followed again someone later ? 

Thank you @timgrossmann

**Comment by timgrossmann** [comment]
@theKoap yes follow_By_list currently doesn't care about the `times`

It will save the followed people and know which of if are already followed x-times
