### ISSUE TITLE
post_page[0]["shortcode_media"] KeyError: 0

### ISSUE THREAD

**Issue by Goli777** [InstaPy/InstaPy#6462]
## Expected Behavior
like and comment posts by tag
## Current Behavior

several hours ago script runs well, but suddenly:

INFO [2022-01-19 22:53:14] [kat_berlin_12]  Like# [1/109]
INFO [2022-01-19 22:53:14] [kat_berlin_12]  https://www.instagram.com/p/CY7db85vmmC/
INFO [2022-01-19 22:53:19] [kat_berlin_12]  post_page: {'items': [{'taken_at': 1642632681, 'pk': 2754925061235173762, 'id': '2754925061235173762_49929679974', 'device_timestamp': 1642632562281324, 'media_type': 1, 'code': 'CY7db85vmmC', 'client_cache_key': .....
INFO [2022-01-19 22:53:20] [kat_berlin_12]  Sessional Live Report:
        |> No any statistics to show

[Session lasted 3.0 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-01-19 22:53:20] [kat_berlin_12]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "test.py", line 20, in <module>
    session.like_by_tags(["animegirl", "anime"], amount=100)
  File "/root/insta/lib/python3.8/site-packages/instapy/instapy.py", line 1980, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "/root/insta/lib/python3.8/site-packages/instapy/like_util.py", line 619, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

trying:
local machine (pyCharm + Windows)
remote server (Ubuntu 20.4)
6 or 7 different accounts,
but no luck

code:
```
# -*- coding: utf-8 -*-
from instapy import InstaPy
from instapy import smart_run

session = InstaPy(username='username', password='password', headless_browser=True)

with smart_run(session):
    session.set_do_like(enabled=True, percentage=84)
    session.set_do_comment(enabled=True, percentage=24)
    session.set_comments(['kawaiii!!!😍', 
    						'Cool🔥🔥🔥🔥', 
    						'❤❤❤❤❤Just amaZZZing', 
    						'Awesome❤', 
    						'Really Cool🔥🔥🔥', 
    						'😍I like your stuff😍'])


    session.like_by_tags(["animegirl", "anime"], amount=40)
```

**Comment by RainbowTob** [comment]
Same problem on Win10 with Instapy 0.06.16 and python 3.10.2 🙁

**Comment by wyrw** [comment]
I have exactly the same problem for about 14 hours now, before that everything was fine, windows 10, python 3.10.1, instapy 0.6.16

**Comment by Goli777** [comment]
So what I can explore, is:
Only when my account not logged in, Instagram returns a graphql:
https://www.instagram.com/p/CY8aAflIEx_/?__a=1
```
{
    "graphql": {
        "shortcode_media": {
            "__typename": "GraphVideo",
            "id": "2755191455162059903",
            "shortcode": "CY8aAflIEx_",
            "dimensions": {
                "height": 1167,
                "width": 750
            },
            "gating_info": null,
            "fact_check_overall_rating": null,
            "fact_check_information": null,
            "sensitivity_friction_info": null,
            "sharing_friction_info": {
                "should_have_sharing_friction": false,
                "bloks_app_url": null
            },
```
but since I log in, it returns a privateAPI:
https://www.instagram.com/p/CY8aAflIEx_/?__a=1
```
"items": [
        {
            "taken_at": 1642664518,
            "pk": 2755191455162059903,
            "id": "2755191455162059903_47673378438",
            "device_timestamp": 27943319415527,
            "media_type": 2,
            "code": "CY8aAflIEx_",
            "client_cache_key": "Mjc1NTE5MTQ1NTE2MjA1OTkwMw==.2",
            "filter_type": 0,
            "is_unified_video": true,
            "user": {
                "pk": 47673378438,
                "username": "_meme_chor_bhai",
                "full_name": "Bengali Eren \ud83c\udde7\ud83c\udde9",
                "is_private": false,
```
thus InstaPy can't gather any items

I'm not a fluence in coding or something like that, but I'm sure we should edit
code below in like_util.py and similar files:
```
616    else:
617        logger.info("post_page: {}".format(post_page))
618        media = post_page[0]["shortcode_media"]
619        is_video = media["is_video"]
620        user_name = media["owner"]["username"]
621        image_text = media["caption"]
622        owner_comments = browser.execute_script(
```

**Comment by ErwinKoekoek** [comment]
To fix the shortcut error try this code. https://github.com/ErwinKoekoek/InstaPy

**Comment by wyrw** [comment]
> FIX post_page[0]["shortcode_media"] KeyError: Try this code https://github.com/ErwinKoekoek/InstaPy

doesn't work with me

**Comment by ErwinKoekoek** [comment]
> > FIX post_page[0]["shortcode_media"] KeyError: Try this code https://github.com/ErwinKoekoek/InstaPy
> 
> doesn't work with me

For me it does. There are still issues with 'session.interact_by_comments' but i dont use this function. Fix code is not very clear but works for me right now.

**Comment by wyrw** [comment]
> > > FIX post_page[0]["shortcode_media"] KeyError: Try this code https://github.com/ErwinKoekoek/InstaPy
> > 
> > 
> > doesn't work with me
> 
> For me it does. There are still issues with 'session.interact_by_comments' but i dont use this function. Fix code is not very clear but works for me right now.

Maybe I did something wrong? I install it by code in shell: python - pip install git+https://github.com/ErwinKoekoek/InstaPy.git
Or have to do it some other way?

**Comment by Goli777** [comment]
fix work for me on comment by tag
config:
pycharm + python 3.10+ win10
Not tested yet on remote server and other functions

**Comment by Goli777** [comment]
> 

i 'm simply replace existing files

**Comment by ErwinKoekoek** [comment]
> > 
> 
> i 'm simply replace existing files

The fix is not very neat.., but it works as a workaround... Not working with interact_by_comments yet.

**Comment by Goli777** [comment]
Waitin' for official repo bump

**Comment by ErwinKoekoek** [comment]
There were still some issues further in the run. Fixed again.
Stay tuned ;-) 
https://github.com/ErwinKoekoek/InstaPy

**Comment by wyrw** [comment]
> There were still some issues further in the run. Fixed again. Stay tuned ;-) https://github.com/ErwinKoekoek/InstaPy

works perfectly, thanks man!

**Comment by RainbowTob** [comment]
How can I install this fix?

**Comment by ErwinKoekoek** [comment]
> How can I install this fix?

Just replace the updated files.

**Comment by wyrw** [comment]
> How can I install this fix?

copy/paste files from instapy folder to instapy folder on your computer 
on windows ( C:\Users\name\AppData\Local\Programs\Python\Python310\Lib\site-packages\instapy )

**Comment by RainbowTob** [comment]
works fine, thanks!

**Comment by florent522** [comment]
> > How can I install this fix?
> 
> copy/paste files from instapy folder to instapy folder on your computer on windows ( C:\Users\name\AppData\Local\Programs\Python\Python310\Lib\site-packages\instapy )

it doenst work on w10, i have graphql error

**Comment by ErwinKoekoek** [comment]
> > > How can I install this fix?
> > 
> > 
> > copy/paste files from instapy folder to instapy folder on your computer on windows ( C:\Users\name\AppData\Local\Programs\Python\Python310\Lib\site-packages\instapy )
> 
> it doenst work on w10, i have graphql error

I'm more an linux, debian, mac user. Sorry. But search your folders and replace the files: comment_util.py, like_util.py, util.py
Cheers, 
Erwin

**Comment by ErwinKoekoek** [comment]
So the json structure of the 'post_page' is changed. Some user comments texts are in it but not all of them. Does somebody know if this is an extra API call so we can complete it again.

**Comment by ErwinKoekoek** [comment]
Location_name is also fixed now. Still no idea where all the user comments are. Somebody?

**Comment by wyrw** [comment]
> Location_name is also fixed now. Still no idea where all the user comments are. Somebody?

Mine comments are working with your fix

**Comment by alexpzpz** [comment]
> There were still some issues further in the run. Fixed again. Stay tuned ;-) https://github.com/ErwinKoekoek/InstaPy

Thanks It works.
But apparently with these checks fell under the restriction.
Doesn’t like through the bot, but manually likes doesn’t write that there is a redaction ... hmm

**Comment by voxoff79** [comment]
> > > How can I install this fix?
> > 
> > 
> > copy/paste files from instapy folder to instapy folder on your computer on windows ( C:\Users\name\AppData\Local\Programs\Python\Python310\Lib\site-packages\instapy )
> 
> it doenst work on w10, i have graphql error

I get the same error on mac mojave

Traceback (most recent call last):
  File "bot.py", line 72, in <module>
    session.like_by_tags(my_hashtags, amount=20, interact=True, media=None)
  File "/usr/local/lib/python3.8/site-packages/instapy/instapy.py", line 1994, in like_by_tags
    self.liking_approved = verify_liking(
  File "/usr/local/lib/python3.8/site-packages/instapy/like_util.py", line 934, in verify_liking
    likes_count = post_page["graphql"]["shortcode_media"]["edge_media_preview_like"][
KeyError: 'graphql'

**Comment by Avinash0564** [comment]
> ## Expected Behavior
> like and comment posts by tag
> 
> ## Current Behavior
> several hours ago script runs well, but suddenly:
> 
> INFO [2022-01-19 22:53:14] [kat_berlin_12] Like# [1/109] INFO [2022-01-19 22:53:14] [kat_berlin_12] https://www.instagram.com/p/CY7db85vmmC/ INFO [2022-01-19 22:53:19] [kat_berlin_12] post_page: {'items': [{'taken_at': 1642632681, 'pk': 2754925061235173762, 'id': '2754925061235173762_49929679974', 'device_timestamp': 1642632562281324, 'media_type': 1, 'code': 'CY7db85vmmC', 'client_cache_key': ..... INFO [2022-01-19 22:53:20] [kat_berlin_12] Sessional Live Report: |> No any statistics to show
> 
> [Session lasted 3.0 minutes] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO INFO [2022-01-19 22:53:20] [kat_berlin_12] Session ended! oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
> 
> Traceback (most recent call last): File "test.py", line 20, in session.like_by_tags(["animegirl", "anime"], amount=100) File "/root/insta/lib/python3.8/site-packages/instapy/instapy.py", line 1980, in like_by_tags inappropriate, user_name, is_video, reason, scope = check_link( File "/root/insta/lib/python3.8/site-packages/instapy/like_util.py", line 619, in check_link media = post_page[0]["shortcode_media"] KeyError: 0
> 
> trying: local machine (pyCharm + Windows) remote server (Ubuntu 20.4) 6 or 7 different accounts, but no luck
> 
> code:
> 
> ```
> # -*- coding: utf-8 -*-
> from instapy import InstaPy
> from instapy import smart_run
> 
> session = InstaPy(username='username', password='password', headless_browser=True)
> 
> with smart_run(session):
>     session.set_do_like(enabled=True, percentage=84)
>     session.set_do_comment(enabled=True, percentage=24)
>     session.set_comments(['kawaiii!!!😍', 
>     						'Cool🔥🔥🔥🔥', 
>     						'❤❤❤❤❤Just amaZZZing', 
>     						'Awesome❤', 
>     						'Really Cool🔥🔥🔥', 
>     						'😍I like your stuff😍'])
> 
> 
>     session.like_by_tags(["animegirl", "anime"], amount=40)
> ```


still no fix , facing the same problem. w10 , python 3.10

**Comment by wyrw** [comment]
I’ve got ban for a week.. with the same settings as before :) somebody knows what is the interaction limit for instagram?

**Comment by ErwinKoekoek** [comment]
> I’ve got ban for a week.. with the same settings as before :) somebody knows what is the interaction limit for instagram?

Sorry to hear that... Sorry but i can't solve that. Maybe your settings are to aggressive?

**Comment by ErwinKoekoek** [comment]
> > ## Expected Behavior
> > like and comment posts by tag
> > ## Current Behavior
> > several hours ago script runs well, but suddenly:
> > INFO [2022-01-19 22:53:14] [kat_berlin_12] Like# [1/109] INFO [2022-01-19 22:53:14] [kat_berlin_12] https://www.instagram.com/p/CY7db85vmmC/ INFO [2022-01-19 22:53:19] [kat_berlin_12] post_page: {'items': [{'taken_at': 1642632681, 'pk': 2754925061235173762, 'id': '2754925061235173762_49929679974', 'device_timestamp': 1642632562281324, 'media_type': 1, 'code': 'CY7db85vmmC', 'client_cache_key': ..... INFO [2022-01-19 22:53:20] [kat_berlin_12] Sessional Live Report: |> No any statistics to show
> > [Session lasted 3.0 minutes] OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO INFO [2022-01-19 22:53:20] [kat_berlin_12] Session ended! oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
> > Traceback (most recent call last): File "test.py", line 20, in session.like_by_tags(["animegirl", "anime"], amount=100) File "/root/insta/lib/python3.8/site-packages/instapy/instapy.py", line 1980, in like_by_tags inappropriate, user_name, is_video, reason, scope = check_link( File "/root/insta/lib/python3.8/site-packages/instapy/like_util.py", line 619, in check_link media = post_page[0]["shortcode_media"] KeyError: 0
> > trying: local machine (pyCharm + Windows) remote server (Ubuntu 20.4) 6 or 7 different accounts, but no luck
> > code:
> > ```
> > # -*- coding: utf-8 -*-
> > from instapy import InstaPy
> > from instapy import smart_run
> > 
> > session = InstaPy(username='username', password='password', headless_browser=True)
> > 
> > with smart_run(session):
> >     session.set_do_like(enabled=True, percentage=84)
> >     session.set_do_comment(enabled=True, percentage=24)
> >     session.set_comments(['kawaiii!!!😍', 
> >     						'Cool🔥🔥🔥🔥', 
> >     						'❤❤❤❤❤Just amaZZZing', 
> >     						'Awesome❤', 
> >     						'Really Cool🔥🔥🔥', 
> >     						'😍I like your stuff😍'])
> > 
> > 
> >     session.like_by_tags(["animegirl", "anime"], amount=40)
> > ```
> 
> still no fix , facing the same problem. w10 , python 3.10

Please try the new files on my repo. I fixed the 'verify_liking' and 'location lat lng'
Love to hear if it solves the issue. 
Best
Erwin

**Comment by Avinash0564** [comment]
> > Location_name is also fixed now. Still no idea where all the user comments are. Somebody?
> 
> Mine comments are working with your fix

can you send me the files

**Comment by ErwinKoekoek** [comment]
> > > Location_name is also fixed now. Still no idea where all the user comments are. Somebody?
> > 
> > 
> > Mine comments are working with your fix
> 
> can you send me the files

Scroll up this page or... 
https://github.com/ErwinKoekoek/InstaPy/tree/master/instapy
comment_util.py, like_util.py, util.py

**Comment by Nadorozhnyy** [comment]
I don't know exactly and this is my first comment (trying to interact with the community) but for me all goes to normal when i delete cookie in gekodriver. (i do it for mine one process for firsttime, then i realize what instapy have their own func for this (but i do it wrong, i delete cookie straight after start session). So I start same own func for delete cookie before seesion and "post_page[0]["shortcode_media"] KeyError: 0" didnt show again.

**Comment by Goli777** [comment]
@Nadorozhnyy  Please provide an example

**Comment by Nadorozhnyy** [comment]
> @Nadorozhnyy Please provide an example

self.session.browser.delete_cookie(name=self.login) - at the end of main bot process

or

  def delete_cookie(self):
      path_to_log_text = f'{self.home_directory}/InstaPy/logs/{self.login}/{self.login}_cookie.pkl'
      path_to_log = os.path.abspath(path_to_log_text)
      if os.path.exists(path_to_log):
          os.remove(path_to_log)

find and delete cookie file in instapy/log/login_name

**Comment by ErwinKoekoek** [comment]
It looks like this in an other issue then the "post_page[0]["shortcode_media"]

**Comment by Avinash0564** [comment]
> It looks like this in an other issue then the "post_page[0]["shortcode_media"]

i used your fix but it gives graphql error
 another issue is that it shows---
Image link: b'https://www.instagram.com/p/CZBf9StJzMG/'
INFO [2022-01-22 19:04:35] [jessi_12123]  Description: b'$2 Tuesdays @opyum_8mile \xe2\x80\xbc\xef\xb8\x8f Each & Every Tuesday. \xe2\x9c\xa8Vibes\xe2\x9c\xa8 For Free Birthday & Booth Reservations Text 313.424.2831 or DM #opyumtuesdays'
INFO [2022-01-22 19:04:35] [jessi_12123_]  Location: b'Detroit, Michigan'
INFO [2022-01-22 19:04:43] [jessi_12123]  --> Image not liked: Likes are disabled for the 'Comment-By-Locations' feature
INFO [2022-01-22 19:04:43] [jessi_12123]  --> Image not commented: skipping out of given comment percentage
INFO [2022-01-22 19:04:43] [jessi_12123]  Comment# [2/20]

it says Skipping Out of given comment Percentage 
my Code is 
with smart_run(session):
    # general settings

 session.comment_by_locations(['13261722/detroit-michigan/'], amount=20, skip_top_posts=True)
 session.set_do_comment(enabled=True,percentage=100)
 session.set_comments(["Sales are up to 20% off, the best candy Only at @harris_lahm..."])

**Comment by Nadorozhnyy** [comment]
> 

20/01/2022 bot stop work with "post_page[0]["shortcode_media"], i just try something. maybe it's not related

**Comment by limberger** [comment]
> There were still some issues further in the run. Fixed again. Stay tuned ;-) https://github.com/ErwinKoekoek/InstaPy

Thanks!!! It's worked!!!! You will send a PR?

**Comment by Nadorozhnyy** [comment]
> > @Nadorozhnyy Please provide an example
> 
> self.session.browser.delete_cookie(name=self.login) - at the end of main bot process
> 
> or
> 
> def delete_cookie(self): path_to_log_text = f'{self.home_directory}/InstaPy/logs/{self.login}/{self.login}_cookie.pkl' path_to_log = os.path.abspath(path_to_log_text) if os.path.exists(path_to_log): os.remove(path_to_log)
> 
> find and delete cookie file in instapy/log/login_name

not work. it just work for one account, in other the same error

**Comment by ErwinKoekoek** [comment]
> > It looks like this in an other issue then the "post_page[0]["shortcode_media"]
> 
> i used your fix but it gives graphql error another issue is that it shows--- Image link: b'https://www.instagram.com/p/CZBf9StJzMG/' INFO [2022-01-22 19:04:35] [jessi_12123] Description: b'$2 Tuesdays @opyum_8mile \xe2\x80\xbc\xef\xb8\x8f Each & Every Tuesday. \xe2\x9c\xa8Vibes\xe2\x9c\xa8 For Free Birthday & Booth Reservations Text 313.424.2831 or DM #opyumtuesdays' INFO [2022-01-22 19:04:35] [jessi_12123_] Location: b'Detroit, Michigan' INFO [2022-01-22 19:04:43] [jessi_12123] --> Image not liked: Likes are disabled for the 'Comment-By-Locations' feature INFO [2022-01-22 19:04:43] [jessi_12123] --> Image not commented: skipping out of given comment percentage INFO [2022-01-22 19:04:43] [jessi_12123] Comment# [2/20]
> 
> it says Skipping Out of given comment Percentage my Code is with smart_run(session): # general settings
> 
> session.comment_by_locations(['13261722/detroit-michigan/'], amount=20, skip_top_posts=True) session.set_do_comment(enabled=True,percentage=100) session.set_comments(["Sales are up to 20% off, the best candy Only at @harris_lahm..."])


trying to reproduce... stay tuned...

**Comment by voxoff79** [comment]
> > > It looks like this in an other issue then the "post_page[0]["shortcode_media"]
> > 
> > 
> > i used your fix but it gives graphql error another issue is that it shows--- Image link: b'https://www.instagram.com/p/CZBf9StJzMG/' INFO [2022-01-22 19:04:35] [jessi_12123] Description: b'$2 Tuesdays @opyum_8mile \xe2\x80\xbc\xef\xb8\x8f Each & Every Tuesday. \xe2\x9c\xa8Vibes\xe2\x9c\xa8 For Free Birthday & Booth Reservations Text 313.424.2831 or DM #opyumtuesdays' INFO [2022-01-22 19:04:35] [jessi_12123_] Location: b'Detroit, Michigan' INFO [2022-01-22 19:04:43] [jessi_12123] --> Image not liked: Likes are disabled for the 'Comment-By-Locations' feature INFO [2022-01-22 19:04:43] [jessi_12123] --> Image not commented: skipping out of given comment percentage INFO [2022-01-22 19:04:43] [jessi_12123] Comment# [2/20]
> > it says Skipping Out of given comment Percentage my Code is with smart_run(session): # general settings
> > session.comment_by_locations(['13261722/detroit-michigan/'], amount=20, skip_top_posts=True) session.set_do_comment(enabled=True,percentage=100) session.set_comments(["Sales are up to 20% off, the best candy Only at @harris_lahm..."])
> 
> trying to reproduce... stay tuned...

Im my case gives me this error:

  File "/usr/local/lib/python3.8/site-packages/instapy/instapy.py", line 1994, in like_by_tags
    self.liking_approved = verify_liking(
  File "/usr/local/lib/python3.8/site-packages/instapy/like_util.py", line 934, in verify_liking
    likes_count = post_page["graphql"]["shortcode_media"]["edge_media_preview_like"][
KeyError: 'graphql'


Thanks for your support,

**Comment by Avinash0564** [comment]
session.set_do_follow(enabled=True, percentage=50)
 session.set_do_comment(enabled=True, percentage=80)
 session.set_do_like(True, percentage=70)
 session.set_comments(["Sales are up to 20% off, Only at @harris_lahm ..."])
 session.comment_by_locations(['13261722/detroit-michigan/'], amount=20, skip_top_posts=True,)

**this is the code, everything working good except commenting**

INFO [2022-01-22 23:40:38] [kathryn_cbd]  https://www.instagram.com/p/CZCqByKl_lj/
INFO [2022-01-22 23:40:41] [kathryn_cbd]  Image from: b'timothypaule'
INFO [2022-01-22 23:40:41] [kathryn_cbd]  Image link: b'https://www.instagram.com/p/CZCqByKl_lj/'
INFO [2022-01-22 23:40:41] [kathryn_cbd]  Description: b'Join me in wishing my friend, the creative genious, @mars.primo Happy Birthday! You are loved and well appreciated.\n\nWe are all sent here on earth to fulfill a specific mission, and out of all the many characteristics, skills, and talents you carry -  to simply live in the moment, has taught me many valuable lessons.'
INFO [2022-01-22 23:40:41] [kathryn_cbd]  Location: b'Detroit, Michigan'
INFO [2022-01-22 23:40:49] [kathryn_cbd]  --> Image not liked: Likes are disabled for the 'Comment-By-Locations' feature
INFO [2022-01-22 23:40:49] [kathryn_cbd]  --> Could not found owner's comment in this post, trying to comment...
**ERROR [2022-01-22 23:40:59] [kathryn_cbd]  Message: TypeError: rect is undefined**

INFO [2022-01-22 23:40:59] [kathryn_cbd]  --> Commented: b'Sales are up to 20% off, Only at @harris_lahm ...'

it shows  **Message: TypeError: rect is undefined**

**Comment by ErwinKoekoek** [comment]
> 

Did some fixes again. Please try the new updates 3 files.
I cannot reproduce the 'Message: TypeError: rect is undefined' message..

**Comment by voxoff79** [comment]
> > 
> 
> Did some fixes again. Please try the new updates 3 files. I cannot reproduce the 'Message: TypeError: rect is undefined' message..

Your changes solve my graphql error but now i have this one:

 File "/usr/local/lib/python3.8/site-packages/instapy/instapy.py", line 2118, in like_by_tags
    self.like_by_users(
  File "/usr/local/lib/python3.8/site-packages/instapy/instapy.py", line 2217, in like_by_users
    links = get_links_for_username(
  File "/usr/local/lib/python3.8/site-packages/instapy/like_util.py", line 482, in get_links_for_username
    is_private = is_private_profile(browser, logger, following_status == "Following")
  File "/usr/local/lib/python3.8/site-packages/instapy/util.py", line 94, in is_private_profile
    is_private = data["items"][0]["user"]["is_private"]
KeyError: 'items'


Any thoughts? Thanks

**Comment by Avinash0564** [comment]
Message: TypeError: rect is undefined  

fix this

**Comment by Goli777** [comment]
same as @voxoff79 but in like_by_feed
@ErwinKoekoek 

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 4137, in like_by_feed
    for _ in self.like_by_feed_generator(amount, randomize, unfollow, interact):
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 4386, in like_by_feed_generator
    self.like_by_users(
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 2217, in like_by_users
    links = get_links_for_username(
  File "/usr/local/lib/python3.8/dist-packages/instapy/like_util.py", line 482, in get_links_for_username
    is_private = is_private_profile(browser, logger, following_status == "Following")
  File "/usr/local/lib/python3.8/dist-packages/instapy/util.py", line 94, in is_private_profile
    is_private = data["items"][0]["user"]["is_private"]

**Comment by alexpzpz** [comment]
updated like_util as erwin did, puts 10-15 likes without problems, then closes the session with an error:
`Traceback (most recent call last):
  File "C:\Users\Серв\Desktop\Bot\like_unf.py", line 69, in <module>
    session.interact_user_likers(usernames=["_tomato_333_"],
  File "C:\Users\Серв\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 3419, in interact_user_likers
    self.interact_by_users(
  File "C:\Users\Серв\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 2563, in interact_by_users
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\Серв\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\like_util.py", line 659, in check_link
    image_text = media[media_edge_string]
KeyError: None`

**Comment by Goli777** [comment]
same as @voxoff79 
https://www.instagram.com/makeupguidewyld/?__a=1

@ErwinKoekoek 

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 4137, in like_by_feed
    for _ in self.like_by_feed_generator(amount, randomize, unfollow, interact):
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 4386, in like_by_feed_generator
    self.like_by_users(
  File "/usr/local/lib/python3.8/dist-packages/instapy/instapy.py", line 2217, in like_by_users
    links = get_links_for_username(
  File "/usr/local/lib/python3.8/dist-packages/instapy/like_util.py", line 482, in get_links_for_username
    is_private = is_private_profile(browser, logger, following_status == "Following")
  File "/usr/local/lib/python3.8/dist-packages/instapy/util.py", line 94, in is_private_profile
    is_private = data["items"][0]["user"]["is_private"]
KeyError: 'items'

**Comment by ErwinKoekoek** [comment]
Did some fixing for  'is_private' and 'check_link KeyError: None' crash...
Hopefully they work for you guys. 
Next thing is going to bed ;-)
Cheers

**Comment by Goli777** [comment]
@ErwinKoekoek 🔥🔥🔥🔥

**Comment by voxoff79** [comment]
@ErwinKoekoek Thanks!!

**Comment by alexpzpz** [comment]
> Did some fixing for 'is_private' and 'check_link KeyError: None' crash... Hopefully they work for you guys. Next thing is going to bed ;-) Cheers
Thx. updated all your files, puts likes through a hashtag, but when interacting with a user, does not put likes, but simply skips it. I'll attach the log and code.

```
session.set_do_like(enabled=True, 
                        percentage=100)    
session.set_user_interact(amount=1, 
                                randomize=False, 
                                percentage=100)
session.interact_user_likers(usernames=["user"],
                             posts_grab_amount=1,
                             interact_likers_per_post=20,
                             randomize=True)  
```

```
INFO [2022-01-23 08:54:00] [carcollapse]  Starting to interact by users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2022-01-23 08:54:00] [carcollapse]  Username [1/1]
INFO [2022-01-23 08:54:00] [carcollapse]  --> b'_otabek__06_09'
INFO [2022-01-23 08:54:00] [carcollapse]  username actions: following=False commenting=False liking=True story=False
INFO [2022-01-23 08:54:00] [carcollapse]  Getting _otabek__06_09 image list...
INFO [2022-01-23 08:54:00] [carcollapse]  Cannot find is_private so defined as None
INFO [2022-01-23 08:54:00] [carcollapse]  This user is private and we are not following. 'None':'Follow'
INFO [2022-01-23 08:54:01] [carcollapse]  Liker 'vladmirnai2121' [10/36]
INFO [2022-01-23 08:54:05] [carcollapse]  Interaction [7/36]  |  Total Interaction: 7
```

**Comment by Tequeromtv** [comment]
it worked, may sign this as solved, @ErwinKoekoek thank you so much, I spend almost 2 hours trying to figure out why its not working since its the first time I downloaded it, so I started to think that I made any mistake on the install step hahaha

**Comment by ErwinKoekoek** [comment]
@all PR created. Stay tuned for the merge!
Cheers
Erwin

**Comment by Goli777** [comment]
@ErwinKoekoek thanks a lot and +100500 to your karma
=)
I'll mark this issue as resolved.
All the best!

**Comment by Nadorozhnyy** [comment]
> > Did some fixing for 'is_private' and 'check_link KeyError: None' crash... Hopefully they work for you guys. Next thing is going to bed ;-) Cheers
> 
> Thx. updated all your files, puts likes through a hashtag, but when interacting with a user, does not put likes, but simply skips it. I'll attach the log and code.
> 
> ```
> session.set_do_like(enabled=True, 
>                         percentage=100)    
> session.set_user_interact(amount=1, 
>                                 randomize=False, 
>                                 percentage=100)
> session.interact_user_likers(usernames=["user"],
>                              posts_grab_amount=1,
>                              interact_likers_per_post=20,
>                              randomize=True)  
> ```
> 
> ```
> INFO [2022-01-23 08:54:00] [carcollapse]  Starting to interact by users..
> """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> INFO [2022-01-23 08:54:00] [carcollapse]  Username [1/1]
> INFO [2022-01-23 08:54:00] [carcollapse]  --> b'_otabek__06_09'
> INFO [2022-01-23 08:54:00] [carcollapse]  username actions: following=False commenting=False liking=True story=False
> INFO [2022-01-23 08:54:00] [carcollapse]  Getting _otabek__06_09 image list...
> INFO [2022-01-23 08:54:00] [carcollapse]  Cannot find is_private so defined as None
> INFO [2022-01-23 08:54:00] [carcollapse]  This user is private and we are not following. 'None':'Follow'
> INFO [2022-01-23 08:54:01] [carcollapse]  Liker 'vladmirnai2121' [10/36]
> INFO [2022-01-23 08:54:05] [carcollapse]  Interaction [7/36]  |  Total Interaction: 7
> ```

same. Do you fix that?
