### ISSUE TITLE
logging error

### ISSUE THREAD

**Issue by alexpzpz** [InstaPy/InstaPy#6464]
Hi. 
Out of the blue, nothing foreshadowed trouble.
During the day everything worked, and in the evening it stopped.
Doesn't put likes, just ends the session. Screenshots and logs attached.
Unsubscribes without problems.
Updated selenium (21.3.1), instapy (0.6.16).
There is an assumption that firefox was updated to version 96, I rolled back to 95 but nothing helps.
there are options ?
Find the photo and write "logging error" and after a lot of all sorts of words, after that closes the session

Code 
`session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False)

with smart_run(session):
    session.like_by_tags(["#катаемся"], amount=20)
    session.set_dont_like(["#порно", "#продажа", "#продать", "#автомойка", "#сервис"])`

Link to log screenshots:
https://drive.google.com/drive/folders/1kGBnedVMPpNtPllycQH19wyeuaQJ3ev8?usp=sharing

**Comment by Goli777** [comment]
Same issue as previous 
https://github.com/InstaPy/InstaPy/issues/6462
https://github.com/InstaPy/InstaPy/issues/6463

**Comment by limberger** [comment]
Duplicate of #6462

**Comment by RainbowTob** [comment]
Its the same issue.

**Comment by wyrw** [comment]
ok, should we delete #6463 and this one then?

**Comment by RainbowTob** [comment]
Good idea

**Comment by alexpzpz** [comment]
#6462 solution
