### ISSUE TITLE
Interact user, skip all

### ISSUE THREAD

**Issue by alexpzpz** [InstaPy/InstaPy#6468]
question for @ErwinKoekoek 
updated all your files, puts likes through a hashtag, but when interacting with a user, does not put likes, but simply skips it. I'll attach the log and code. https://github.com/ErwinKoekoek/InstaPy

`session.set_do_like(enabled=True, 
                        percentage=100)    
session.set_user_interact(amount=1, 
                                randomize=False, 
                                percentage=100)
session.interact_user_likers(usernames=["user"],
                             posts_grab_amount=1,
                             interact_likers_per_post=20,
                             randomize=True)  `

```
INFO [2022-01-23 08:54:00] [carcollapse]  Starting to interact by users..
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
INFO [2022-01-23 08:54:00] [carcollapse]  Username [1/1]
INFO [2022-01-23 08:54:00] [carcollapse]  --> b'_otabek__06_09'
INFO [2022-01-23 08:54:00] [carcollapse]  username actions: following=False commenting=False liking=True story=False
INFO [2022-01-23 08:54:00] [carcollapse]  Getting _otabek__06_09 image list...
INFO [2022-01-23 08:54:00] [carcollapse]  Cannot find is_private so defined as None
INFO [2022-01-23 08:54:00] [carcollapse]  This user is private and we are not following. 'None':'Follow'
INFO [2022-01-23 08:54:01] [carcollapse]  Liker 'vladmirnai2121' [10/36]
INFO [2022-01-23 08:54:05] [carcollapse]  Interaction [7/36]  |  Total Interaction: 7
```

I changed the piece of new code to the old one, and everything started working, I am writing this so that you pay attention to this problem. **util.py**

**does not work:**

```
def is_private_profile(browser, logger, following=True):
        is_private=None
    try:
        #DEF: 22jan function refactored
        data = get_additional_data(browser)
        is_private = data["items"][0]
        is_private = is_private["user"]['is_private'] if is_private else None
        logger.info(
            "Checked if '{}' is private, and it is: '{}'".format(
                data["items"][0]["user"]["username"], is_private
            )
        )
    except:
        logger.info("Cannot find is_private so defined as None")
        is_private=None

    return is_private
```

**work:**

```
def is_private_profile(browser, logger, following=True):
    shared_data = get_shared_data(browser)
    data = shared_data["entry_data"]["ProfilePage"][0]

    # Sometimes shared_data["entry_data"]["ProfilePage"][0] is empty, but get_additional_data()
    # fetches all data needed
    if not data:
        data = get_additional_data(browser)

    is_private = data["graphql"]["user"]["is_private"]

    return is_private
```

**Comment by ErwinKoekoek** [comment]
> question for @ErwinKoekoek updated all your files, puts likes through a hashtag, but when interacting with a user, does not put likes, but simply skips it. I'll attach the log and code. https://github.com/ErwinKoekoek/InstaPy
> 
> `session.set_do_like(enabled=True, percentage=100) session.set_user_interact(amount=1, randomize=False, percentage=100) session.interact_user_likers(usernames=["user"], posts_grab_amount=1, interact_likers_per_post=20, randomize=True) `
> 
> ```
> INFO [2022-01-23 08:54:00] [carcollapse]  Starting to interact by users..
> """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> INFO [2022-01-23 08:54:00] [carcollapse]  Username [1/1]
> INFO [2022-01-23 08:54:00] [carcollapse]  --> b'_otabek__06_09'
> INFO [2022-01-23 08:54:00] [carcollapse]  username actions: following=False commenting=False liking=True story=False
> INFO [2022-01-23 08:54:00] [carcollapse]  Getting _otabek__06_09 image list...
> INFO [2022-01-23 08:54:00] [carcollapse]  Cannot find is_private so defined as None
> INFO [2022-01-23 08:54:00] [carcollapse]  This user is private and we are not following. 'None':'Follow'
> INFO [2022-01-23 08:54:01] [carcollapse]  Liker 'vladmirnai2121' [10/36]
> INFO [2022-01-23 08:54:05] [carcollapse]  Interaction [7/36]  |  Total Interaction: 7
> ```
> 
> I changed the piece of new code to the old one, and everything started working, I am writing this so that you pay attention to this problem. **util.py**
> 
> **does not work:**
> 
> ```
> def is_private_profile(browser, logger, following=True):
>         is_private=None
>     try:
>         #DEF: 22jan function refactored
>         data = get_additional_data(browser)
>         is_private = data["items"][0]
>         is_private = is_private["user"]['is_private'] if is_private else None
>         logger.info(
>             "Checked if '{}' is private, and it is: '{}'".format(
>                 data["items"][0]["user"]["username"], is_private
>             )
>         )
>     except:
>         logger.info("Cannot find is_private so defined as None")
>         is_private=None
> 
>     return is_private
> ```
> 
> **work:**
> 
> ```
> def is_private_profile(browser, logger, following=True):
>     shared_data = get_shared_data(browser)
>     data = shared_data["entry_data"]["ProfilePage"][0]
> 
>     # Sometimes shared_data["entry_data"]["ProfilePage"][0] is empty, but get_additional_data()
>     # fetches all data needed
>     if not data:
>         data = get_additional_data(browser)
> 
>     is_private = data["graphql"]["user"]["is_private"]
> 
>     return is_private
> ```

Hi Alex. I don’t get these messages on my configuration. Can you share (DM) your settings with me? Them I try to reproduce the issue.

**Comment by alexpzpz** [comment]
if that's what you mean, then: win10, python 3.10.2, Instapay files are all yours. except xpath
I am not a programmer, there are distant understandings, but no more)

**Comment by Nadorozhnyy** [comment]
> > question for @ErwinKoekoek updated all your files, puts likes through a hashtag, but when interacting with a user, does not put likes, but simply skips it. I'll attach the log and code. https://github.com/ErwinKoekoek/InstaPy
> > `session.set_do_like(enabled=True, percentage=100) session.set_user_interact(amount=1, randomize=False, percentage=100) session.interact_user_likers(usernames=["user"], posts_grab_amount=1, interact_likers_per_post=20, randomize=True) `
> > ```
> > INFO [2022-01-23 08:54:00] [carcollapse]  Starting to interact by users..
> > """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> > INFO [2022-01-23 08:54:00] [carcollapse]  Username [1/1]
> > INFO [2022-01-23 08:54:00] [carcollapse]  --> b'_otabek__06_09'
> > INFO [2022-01-23 08:54:00] [carcollapse]  username actions: following=False commenting=False liking=True story=False
> > INFO [2022-01-23 08:54:00] [carcollapse]  Getting _otabek__06_09 image list...
> > INFO [2022-01-23 08:54:00] [carcollapse]  Cannot find is_private so defined as None
> > INFO [2022-01-23 08:54:00] [carcollapse]  This user is private and we are not following. 'None':'Follow'
> > INFO [2022-01-23 08:54:01] [carcollapse]  Liker 'vladmirnai2121' [10/36]
> > INFO [2022-01-23 08:54:05] [carcollapse]  Interaction [7/36]  |  Total Interaction: 7
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I changed the piece of new code to the old one, and everything started working, I am writing this so that you pay attention to this problem. **util.py**
> > **does not work:**
> > ```
> > def is_private_profile(browser, logger, following=True):
> >         is_private=None
> >     try:
> >         #DEF: 22jan function refactored
> >         data = get_additional_data(browser)
> >         is_private = data["items"][0]
> >         is_private = is_private["user"]['is_private'] if is_private else None
> >         logger.info(
> >             "Checked if '{}' is private, and it is: '{}'".format(
> >                 data["items"][0]["user"]["username"], is_private
> >             )
> >         )
> >     except:
> >         logger.info("Cannot find is_private so defined as None")
> >         is_private=None
> > 
> >     return is_private
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **work:**
> > ```
> > def is_private_profile(browser, logger, following=True):
> >     shared_data = get_shared_data(browser)
> >     data = shared_data["entry_data"]["ProfilePage"][0]
> > 
> >     # Sometimes shared_data["entry_data"]["ProfilePage"][0] is empty, but get_additional_data()
> >     # fetches all data needed
> >     if not data:
> >         data = get_additional_data(browser)
> > 
> >     is_private = data["graphql"]["user"]["is_private"]
> > 
> >     return is_private
> > ```
> 
> Hi Alex. I don’t get these messages on my configuration. Can you share (DM) your settings with me? Them I try to reproduce the issue.

thanks. work for me.

**Comment by Chessy11** [comment]
> ALL.
> Just made a small fix that hopefully catches the last issues...
> Look at this PR for more information. Please close this item if your problem is solved!
> #6467

@ErwinKoekoek 

This is awesome ! Thanks!
