### ISSUE TITLE
got an unexpected keyword argument 'InstapyFollowed'

### ISSUE THREAD

**Issue by Siapa-Nih** [InstaPy/InstaPy#6471]
File "c:\instapy\gglah.py", line 145, in <module>
    session.unfollow_users(amount=10, InstapyFollowed=(True, "all"), style="RANDOM", unfollow_after=90*60*60, sleep_delay=600)
TypeError: InstaPy.unfollow_users() got an unexpected keyword argument 'InstapyFollowed'

i have seen sample templates and also instructions from https://pypi.org/project/instapy/0.3.0/ and configured them according to the instructions on that page then i get the error as above

[](https://github.com/InstaPy/InstaPy/blob/master/instapy/unfollow_util.py#L159)
and also why this line is highlighted ?

**Comment by Ticunas** [comment]
Please check this documentation
https://github.com/InstaPy/InstaPy/blob/master/docs/actions.md
The argument InstapyFollowed=(True, "all") not exists

Example:
3 - Unfollow the users WHO do not follow you back:
session.unfollow_users(amount=126, nonFollowers=True, style="RANDOM", unfollow_after=42*60*60, sleep_delay=655)

**Comment by Siapa-Nih** [comment]
@Ticunas whoops thanks vro!
means I've been looking at the settings for the old version of instapy
and it turns out that all this time instapy has had settings for the latest version

merci @Ticuna

**Comment by Siapa-Nih** [comment]
@Ticunas whoops thanks vro!
means I've been looking at the settings for the old version of instapy
and it turns out that all this time instapy has had settings for the latest version

merci @Ticuna
