### ISSUE TITLE
is it possible to make the script loop?

### ISSUE THREAD

**Issue by omerbadawy11** [InstaPy/InstaPy#648]
instead of
```
"""Ending the script"""
# clears all the cookies, deleting you password and all information from this session
session.end()
```
Is is possible to make it loop ? of course without starting all over and making a new chrome window.
Thanks 😸

**Comment by timgrossmann** [comment]
@omerbadawy11 Simply start it again?

**Comment by omerbadawy11** [comment]
An automated solution would be better don't u agree?
i would rater leave the bot on continuously then open it after every session 
thanks. :)

**Comment by theKoap** [comment]
Just add a while or for loop in your quickstart,
for example : 

```

while currentfollow < maxFollow:
     follow list or usersfollowers
     currentfollow += number of follows
    etc....
```

**Comment by timgrossmann** [comment]
@omerbadawy11 Well, have fun getting banned 😉
