### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#65]
It might be useful to comment only on Posts with a certain language.

So you could comment in german on german posts or skip posts in a language you don’t speak at all (turkish community in big cities).

I’m not sure how to implement this. As far as I know, Instagram isn’t providing language tags for their posts, so we’d need to implement language detection in our scripts ourselves.

**Comment by eduardocalazansjr** [comment]
The old language-detection library by google handles this.
But the python port is a little slow/chunky.

Strange that in my location, 80%+ of the posts are JUST hashtags (or hashtags + emojis) or words that the library can't detect, this filter wouldn't be nice in that cenarios.

**Comment by GiacomoManzoli** [comment]
Maybe this could be useful: [https://detectlanguage.com/](https://detectlanguage.com/)

**Comment by pekapa** [comment]
@GiacomoManzoli, that might be good, but it requires a user key. Should users create their own key if they want to use that feature?

Another options is this library: https://github.com/saffsd/langid.py

**Comment by timgrossmann** [comment]
@pekapa That's an awesome idea!
Just the license seems to be somewhat weird...

**Comment by eduardocalazansjr** [comment]
Well, i think that the use of "detectlanguage.com" is the same that clarifai, you get you API Key and use own your own.

I will test the langid.py and the port of language-detection from google ASAP and see if there's an considerable increase of machine resources needed for the project and share with you, guys.

**Comment by GiacomoManzoli** [comment]
@pekapa Yes, i think that you need to request a key, but i've never used this service. I was just looking around for a way to implement the language support

**Comment by littleswany** [comment]
The detectlanguage.com api looks like it would be very easy to integrate into the project, something like this maybe:

`session.set_use_detectlanguage(enabled=True, secret='xyz', lang='en')`

`if (detectlanguage.simple_detect() != lang)`

I will play around with it once we have sorted out the code clean up.

**Comment by timgrossmann** [comment]
@vlntdds @littleswany @AlainPilon @pekapa I think we also have to discuss whether it is better to use an API (Signup and Keys required) or a light weight dependency...

**Comment by converge** [comment]
do you guys think that the comment feature is cool ? I think that it just breaks the everyone else fun. No one likes the bot comments, it's annoying, and in most cases, people knows it's a bot comment.

**Comment by fran6will** [comment]
Would this be a good alternative!? https://languagelayer.com

**Comment by timgrossmann** [comment]
@fran6will Well, in my opinion, API's are always bad... At least for a project like InstaPy. You always have to get your API keys.
I think clarifai already is annoying to use. 

A locally running tool would be best

**Comment by ahmadtibrahim** [comment]
Hi guys, i know this sounds funny but i have installed InstaPy and all is looking good but the only problem is trying to figure out where to type Clarifai API keys.
Anyone help? :)

**Comment by guifelix** [comment]
I'm modifying the instapy to use this one: https://github.com/Mimino666/langdetect,
so far i've been able to detect the post language and i'm translating the comment to the post detected lang.

**Comment by KingKorSin** [comment]
Has this ever been continued? 
Did anyone make some progress here?
