### ISSUE TITLE
Like Competitors (interacting with accounts followers) : private accounts are skipped

### ISSUE THREAD

**Issue by balakedev** [InstaPy/InstaPy#650]
Any way we could stop the bot from interacting with an account's followers that are private? Kinda annoying and looks unnatural when you're randomly requesting to follow a user that isn't a public account...

**Comment by KevinKeo** [comment]
I have been working on that, so right now it works when you follow given a list of accounts, but it's more hard to test if when you follow by likes or by a users_followers ^^"

And well I need to add some boolean to make it an option.
I will try to make a fork and create a pull request if it seems to work.
but well, I will be kind of busy those next few days-weeks ^^"

**Comment by timgrossmann** [comment]
@icyks Awesome! Thank you

**Comment by balakedev** [comment]
@icyks Sounds good mate!

**Comment by tunidev** [comment]
any news ?
