### ISSUE TITLE
Error to like a picture:  inappropriate, user_name, is_video, reason, scope = check_link()...

### ISSUE THREAD

**Issue by adrielkirch** [InstaPy/InstaPy#6508]
I'm using instaPy for a few days, until now is my favorite library to auto instagram. But I notice even in a few days of using, there are a couple of issues to be fixed in the next release. One , made me upset ,because I couldn't find a solution in the internet is when I tried to like a picture, yesterday I was able to use these functions: like_by_tags , like_by_feed, like_by_location. But suddenly, today, I couldn't use those functions anymore, it always throw a error when the bot try to like a picture:

```
 inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Users\Win10\AppData\Local\Programs\Python\Python39\lib\site-packages\instapy\like_util.py", line 619, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0
```

I tried to reinstall instaPy in the sites-packages folder, but It dind't solve this issue. 
Anyone, got this issue recently ? What can we do to solve it?

**Comment by adrielkirch** [comment]
Solution:

https://github.com/ErwinKoekoek/InstaPy

**Comment by Prince0Fsaiyan** [comment]
What part of the link you provided was a solution?

**Comment by adrielkirch** [comment]
> What part of the link you provided was a solution?

Use should download that code, he fixed it.
