### ISSUE TITLE
error unfollow InstapyFollowed

### ISSUE THREAD

**Issue by rohsshor** [InstaPy/InstaPy#6516]
## Expected Behavior
Hello to all, I cannot unollow the users of instapy

TypeError: unfollow_users() got an unexpected keyword argument 'InstapyFollowed'

## InstaPy configuration

session.unfollow_users(amount=500, InstapyFollowed=(True),
                           style="FIFO",
                           unfollow_after=1 * 60 * 60, sleep_delay=60)

**Comment by oscarsocar** [comment]
I have exactly the same problem, could you solve it?

**Comment by rohsshor** [comment]
> I have exactly the same problem, could you solve it?
> 
> but I get the error:  Couldn't unfollow 'didiexaple'!        ~user is inaccessible
> 
> 

Hello, you have to replace instapyFollowed with instapy_followed_enabled in every templates of unfollow
