### ISSUE TITLE
Can I run a follower users followers script and another like by tag/ user script at the same time?

### ISSUE THREAD

**Issue by KaiHatchman** [InstaPy/InstaPy#652]
Was wondering if I am able to run multiple scripts at the same time without Instagram noticing and banning me. Ideally I'd want to be following and liking at the same time! But following a users followers and liking tags of my choice

**Comment by timgrossmann** [comment]
@mazehoffman You shouldn't do this for the same account. 
If you want to run some simultaneously, then use docker... Else the sessions will cripple each other...
