### ISSUE TITLE
Cookies Login

### ISSUE THREAD

**Issue by RainbowTob** [InstaPy/InstaPy#6533]
Hello, 

I have the problem that my Firefox cookies are no longer available after a few days when I log in. Then I have to create new ones again, for a short time it works again. but after a day it's the same again. 

Does anyone have any idea why this might be? 

Best regards

**Comment by Ilnur786** [comment]
what you mean "my Firefox cookies are no longer available after a few days when I log in" ?

**Comment by RainbowTob** [comment]
The automatic login is not working, because it have to create new cookies.

**Comment by Ilnur786** [comment]
Instapy do it each time. I don't sure that problem in cookies.

**Comment by RainbowTob** [comment]
This fixed my issue:

https://github.com/InstaPy/InstaPy/issues/6384#issuecomment-955745336

**Comment by Ilnur786** [comment]
good job
