### ISSUE TITLE
Grabbed 0 usernames from ''s `Followers` to do following Errorr

### ISSUE THREAD

**Issue by rohsshor** [InstaPy/InstaPy#6537]
## Current Behavior
INFO [2022-03-05 10:26:02] [xxx  User 'nnn' [1/3]       
ERROR [2022-03-05 10:26:31] [xxx]  Could not find followers' link for 'nnn'

INFO [2022-03-05 10:26:31] [xxx]  Grabbed 0 usernames from 'nnn's `Followers` to do following

Hello Guys, 
How Can I solve this error?

**Comment by RainbowTob** [comment]
Have you tested this?

[](https://github.com/InstaPy/InstaPy/issues/6492)

**Comment by rohsshor** [comment]
> Have you tested this?
> 
> #6492

Hello Dear, 
I have copied the xpath_compile.py of [mr-ravicii](https://github.com/mr-ravicii) and it seems to work with follow. but there are two problems:
1) it follows also the first suggested person at left that appears under the person that it has decided to follow
2) it does't load image list and said that that every account is private so it doesn't interact with the profile

**Comment by LPTzocker** [comment]
How did u fixed that problem?

Have the same errors when loading image list of users...
