### ISSUE TITLE
random.randint

### ISSUE THREAD

**Issue by RainbowTob** [InstaPy/InstaPy#6538]
Hi there, 

random.randint does not work on like_by_tags. 

session.like_by_tags(random.sample(like_tag_list, 3), amount=random.randint(5, 7), interact=True) 

For example, it generates an amount of 15. not from 5 to 7.
Is anyone familiar with it?

**Comment by Sergej99** [comment]
Dont do it like that, do this instead:

n = random.randint(5,7)

session.like_by_tags(random.sample(like_tag_list, 3), amount=n, interact=True)

**Comment by RainbowTob** [comment]
Same result 😕

At unfollow it works…

**Comment by RainbowTob** [comment]
Is it possible that the 9 top posts are added to the specified number of 5 to 7 and I therefore have more desired amount?
