### ISSUE TITLE
How do I add 2 scripts to docker for 1 Instagram account so I can like and follow at the same time? 

### ISSUE THREAD

**Issue by KaiHatchman** [InstaPy/InstaPy#654]
How do I add 2 scripts to docker for 1 Instagram account so I can like and follow at the same time? 

Is this possible?

**Comment by tobyf93** [comment]
I think you will run into issues if you try and run the script for two separate accounts.  Reason being there are log files like followRestriction.json that will end up being shared between the two bots (i don't think you want this).

I think the easiest solution right now is to create two branches in git.  While in the master branch run `git branch instagram-account-one` and `git branch instagram-account-two`.  From there you checkout a specific branch depending on which instagram account you want to work with.

**Comment by timgrossmann** [comment]
Or you just download the whole repository twice
