### ISSUE TITLE
ERROR - IndexError: list index out of range

### ISSUE THREAD

**Issue by datteba** [InstaPy/InstaPy#656]
Traceback (most recent call last):
  File "quickstart.py", line 74, in <module>
    .follow_user_followers(sample(user_list, 1), amount=20, random=True, sleep_delay=s_delay) \
  File "D:\Users\user\InstaPy-master\instapy\instapy.py", line 902, in follow_user_followers
    userFollowed += follow_given_user_followers(self.browser, user, amount, self.dont_include, self.username, self.follow_restrict, random, sleep_delay)
  File "D:\Users\user\InstaPy-master\instapy\unfollow_util.py", line 399, in follow_given_user_followers
    personFollowed = follow_through_dialog(browser, user_name, amount, dont_include, login, follow_restrict, allfollowing, random, delay, callbacks=[])
  File "D:\Users\user\InstaPy-master\instapy\unfollow_util.py", line 219, in follow_through_dialog
    .find_elements_by_tag_name("a")[1].text)
IndexError: list index out of range

**Comment by 46960** [comment]
I am having the same problem!

**Comment by Pormientras** [comment]
Same!

**Comment by datteba** [comment]
![image](https://user-images.githubusercontent.com/30053143/30533610-87346b12-9c5a-11e7-8906-5e0866de29d4.png)

**Comment by dominicwhyte** [comment]
Is anybody working on this? Seems to be a recurring issue but I can't figure out why it happens on some login attempts and not others. Thanks!

**Comment by converge** [comment]
Im trying to reproduce this error, so we can fix it, can someone help me to reproduce it ?

I'm trying in this way:
```python
session.set_user_interact(amount=10, random=True, percentage=50, media='Photo')
session.set_do_like(enabled=True, percentage=50)
session.interact_user_followers(['acc_to_interact'], amount=100, random=True)
```

**Comment by timgrossmann** [comment]
> [BountySource](https://www.bountysource.com/issues/49299642-error-indexerror-list-index-out-of-range)

@converge I somehow also can't get this error when using the `interact_user_followers` feature...

Which version of python are you using?
@dominicwhyte @datteba @Pormientras  @46960

**Comment by datteba** [comment]
@timgrossmann i'm using py 2.7

**Comment by timgrossmann** [comment]
@datteba Weird... which accounts do you want to to follow the users from?
Do they have no followers at all?
