### ISSUE TITLE
Can't get it to work on an Ubuntu machine

### ISSUE THREAD

**Issue by MindRave** [InstaPy/InstaPy#658]
Hello!

First of all, thank you for the script. Taught me a thing or two with Python. :)

It works as intended on a Mac. With the chromedriver in the assets folder the quickstart runs perfectly. So far so good.

Got a digitalocean machine for 5$, just to see whether I can get it to run independently from my computer. This isn't my first time on an Ubuntu, even though I'm not that big of a pro, but for the life of me it refuses to run. The chromedriver is in the assets folder. It's also in the PATH (running 'chromedriver' in the terminal launches it). Both the pip and the python setup.py installs run with no hiccups.

But I keep getting this: 
`selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH`
And:
`Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7f58deeae990>> ignored`

It seems like Selenium can't find the chromedriver, even though the path to the executable is specified in instapy.py.

I've scoured the internet for help but all I've found is advice to show Selenium where to find the executable to use with webdriver.Chrome (and that is already taken care of).

If you have any ideas that would be great! Thank you!

**Comment by timgrossmann** [comment]
@MindRave Make sure to have the chrome driver for your system downloaded and in the /assets folder

**Comment by timgrossmann** [comment]
@MindRave Also make sure that you have at **least** a 1GB machine, InstaPy won't work with less

**Comment by MindRave** [comment]
@timgrossmann it already is, that's the thing. 😕 

I'll try upgrading the machine and tell you how it goes!

**Comment by GonzaloZiadi** [comment]
@MindRave You've probably already checked, but make sure it's the right chromedriver (linux, 32 or 64 bit). I made this mistake in my EC2 instance 😁

Also, if you do `pip install -r requirements.txt` you shouldn't need to run setup.py.

This helped me a lot: https://christopher.su/2015/selenium-chromedriver-ubuntu/

**Comment by MindRave** [comment]
@GonzaloZiadi it is the right chromedriver and it launches perfectly from the command line itself. 😕 I can type 'chromedriver' and it'll just start: `Starting ChromeDriver 2.32.498513 on port …`. Have also done `pip install -r requirements.txt` but got no results.

@timgrossmann Upgraded the DigitalOcean droplet. Still getting the same problem. 😕 

Thinking out loud: could it be the Selenium version? (That would be weird since it works perfectly on OSX)

**Comment by GonzaloZiadi** [comment]
@MindRave You need to install both Chrome and ChromeDriver. Also need to install xvfb.

**Comment by MindRave** [comment]
Alright! Removed the install, reinstalled everything from scratch and it works. 👍

Thank you for your help and messages @GonzaloZiadi & @timgrossmann ! You rock.
