### ISSUE TITLE
Internet Connection Status: error instapy

### ISSUE THREAD

**Issue by tooxiic49** [InstaPy/InstaPy#6592]
Hello, I have a problem. It became impossible for me to launch instapy overnight, I don't understand, is it possible to get help?

`INFO [2022-04-26 01:05:14] [***]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2022-04-26 01:05:14] [***]  -- Connection Checklist [1/2] (Internet Connection Status)
WARNING [2022-04-26 01:05:15] [***]  - Internet Connection Status: error
........................................................................................................................
CRITICAL [2022-04-26 01:05:15] [***]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2022-04-26 01:05:16] [***]  Sessional Live Report:
	|> No any statistics to show`

**Comment by tooxiic49** [comment]
oh ! it's perfect ! thank you SO MUCH !!!

**Comment by rogersillyface** [comment]
> in instapy/login_util.py
> 
> https://freegeoip.app/json is down change to http://ip-api.com/json/
> 
> and
> 
> ```
>                 #current_ip_info["ip"],
>                 #current_ip_info["country_name"],
>                 #current_ip_info["country_code"],
>                 current_ip_info["query"],
>                 current_ip_info["country"],
>                 current_ip_info["countryCode"],
> ```
> 
> as well

https://ip-api.com/json/ not http://ip-api.com/json/ ? (https)

Still not working for me.

**Comment by mercadrone** [comment]
PQP aqui deu certo !

**Comment by Tr1pke** [comment]
@skoenig
(https://github.com/skoenig) added a commit to skoenig/InstaPy that referenced this issue [3 days ago](https://github.com/InstaPy/InstaPy/issues/6592#ref-commit-66daa46)
@skoenig
[implement workaround suggested in](https://github.com/skoenig/InstaPy/commit/66daa461e599c918e2c5b302c7e6e72e67569ce0) https://github.com/InstaPy/InstaPy/issues/6592#issuecomment-1109709640

NOPE does not work

**Comment by emiliomarquez** [comment]
Followed @skoenig 's [workaround for this issue](https://github.com/skoenig/InstaPy/commit/66daa461e599c918e2c5b302c7e6e72e67569ce0) and was able to use instaPy again. Note that I'm only using the `follow_user_followers()` and `unfollow_users()` functions. I have not tried any other instaPy functions yet

**Comment by martini09617** [comment]
Please be more detailed how to make these changes? @davidcson

**Comment by cktnico** [comment]
Really helpful for me I didnt know where to edit these path so here a quick tip: 
go to your :C:\Users\(Username)\AppData\Local\Programs\Python\Python310\Lib\site-packages\instapy

**Comment by tommaso-gallo** [comment]
To answer @martini09617 what @davidcson meant is:
go to :C:\Users(Username)\AppData\Local\Programs\Python\Python310\Lib\site-packages\instapy\login_util.py (as said by @cktnico )
Then go to line 175 and change:
        browser.get("view-source:https://freegeoip.app/json") 
to 
        browser.get("view-source:http://ip-api.com/json/")

after you have done this go to lines 195-197 and change them to 
                    current_ip_info["query"], 
                    current_ip_info["country"],
                    current_ip_info["countryCode"],

It solved it for me

**Comment by maartenor** [comment]
Encountered error "message: "SSL unavailable for this endpoint, order a key at https://members.ip-api.com/""

**Line 175**
        browser.get("view-source:https://api.my-ip.io/v2/ip.json")

**Lines 193 - 197 **
            # Using browser.get("view-source:https://api.my-ip.io/v2/ip.json")
            logger.info(
                '- Current IP is "{}" and it\'s from "{}/{}"'.format(
                    current_ip_info["ip"],
                    current_ip_info["country"]["name"],
                    current_ip_info["country"]["code"],
                )
