### ISSUE TITLE
The script pretends to do likes and follow but in reality doesn't - Rapsberry Pi 3

### ISSUE THREAD

**Issue by CrazedRaven** [InstaPy/InstaPy#660]
Rapsberry Pi 3

The script informs that did like and follow:

_--> Image Liked!
--> Commented: b'Awesome!'
--> Now following_

But when I checked and pictures are not liked (the same with following)
but comments are correct.  

Launched script without xvfb-run (from IDE)
- Use FireFox v52 (this one from doc doesn't work)
- geckodriver 0.18.00
- selenium 3.5.0

If I run script from commnand line with xvfb-run
I have error:

_Traceback (most recent call last):
  File "QF.py", line 18, in <module>
    .set_switch_language(False)\
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 161, in login
    if not login_user(self.browser, self.username, self.password, self.switch_language):
  File "/home/pi/Projects/InstaPy/instapy/login_util.py", line 21, in login_user
    action = ActionChains(browser).move_to_element(login_elem).click().perform()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/action_chains.py", line 77, in perform
    self.w3c_actions.perform()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (341, 569) is out of bounds of viewport width (576) and height (361)_

**Comment by ghost** [comment]
What version of selenium are you running?

**Comment by CrazedRaven** [comment]
Use FireFox v52 (this one from doc doesn't work)
geckodriver 0.18.00
selenium 3.5.0

I also tried 
geckodriver 0.16.00
selenium 3.1.0

**Comment by GonzaloZiadi** [comment]
I've run into this:

> The script informs that did like and follow:
--> Image Liked!
--> Commented: b'Awesome!'
--> Now following
But when I checked and pictures are not liked (the same with following)
but comments are correct.

as well.

Furthermore, since the picture is not liked, it leads to comment spam; if, for example, you have like_ by_tags(["a", "b"]) and a picture has both tags "a" and "b", it will leave two comments.

**Comment by gitpatrickhub** [comment]
@GonzaloZiadi what configuration are you running on the RPI3, i.e., version of Firefox, Selenium, Geckodriver, Debian...



I'm running: 
Debian Jessie
Firefox esr 50
Selenium 2.53.6
Geckodriver 0.18.0

I am able to like posts, but not able to comment as documented in #494 and #566 

@imakethefish are you able to comment with your configuration?

**Comment by GonzaloZiadi** [comment]
@gitpatrickhub I jumped on this because I've had the same issue of instapy saying it liked a picture but not actually liking it, but I'm running it on an EC2 instance. 

I'm running:
Ubuntu 16.04.3 LTS
selenium (3.5.0)
chromedriver 2.32

**Comment by gitpatrickhub** [comment]
@GonzaloZiadi thanks! I'm trying to figure out if there is a configuration on the RPI3 that commenting is working as designed, so we can direct people to the appropriate configuration in the How to on Raspberry Pi document.

**Comment by CrazedRaven** [comment]
Problem solved
I've upgraded Firefox to lastest ESR - Mozilla Firefox 52.3.0
and downgraded selenium to: Selenium 2.53.6

I also check with selenium 3.0.1 and 3.5.0 and it pretend only to like and follow but doesn't do it in reality.
So it is important to use  older selenium.


Update
1.) Works only when I run from IDE when I am doing it from command line: ImportError: No module named 'selenium'
2.) Works from command line with Python2 :)

**Comment by ghost** [comment]
Can confirm runs on python2 comment feature not working.

**Comment by ghost** [comment]
@CrazedRaven @gitpatrickhub New release of Geckodriver 0.19.0 fixed comment issue and element issue. Running on Python 3.5. 

Suggest we update the pi how to doc.

**Comment by CrazedRaven** [comment]
for me, on python 2 works everything (liks, comments, follows)
I will check new geckodriver

**Comment by CrazedRaven** [comment]
Python 2 works ok 
but Python 3 even with new geckodriver and selenium open only Firefox and crash

  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 100, in __init__
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 116, in set_selenium_local_session
    self.browser = webdriver.Firefox(firefox_profile=firefox_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 140, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 229, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

**Comment by Siksel** [comment]
@CrazedRaven are you still running Firefox 52.3.0 and Selenium 2.53.6 with the new geckodriver (0.19.0)?

**Comment by CrazedRaven** [comment]
@Siksel yes and works OK :)

**Comment by Siksel** [comment]
Hmm, it seems firefox has updated to 52.4.0, which for me results in a "selenium.common.exceptions.WebDriverException: Message: Can't load the profile." error.  I couldn't find an archived 52.3.0 that would work for raspberry pi.  @CrazedRaven were you running with nogui (with xvfb-run)?

**Comment by bombsandbottles** [comment]
I just set my Raspberry Pi 3 up, running with Selenium 2.53.6, geckodriver (0.19.0), and Firefox 50 from the main README.  No issues so far, it is liking/commenting as normal.  Running it while attached to a monitor so no virtual stuff.

**Comment by estebancortero** [comment]
I use RPi 3 with firefox-esr 52.6, geckodriver 0.18.0 (0.19 isn't compatible with this version of firefox-esr), selenium 2.53.6, and Python 3.5.3. It runs headless and worked well until recently. Now, I get the following warning: `Warning: Comment Action Likely Failed: Comment Element not found` and, indeed, commenting doesn't work...
