### ISSUE TITLE
KeyError: 0 before liking

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#6607]
Hi, as soon as the bot tries to like a photo, the session ends with this error:

Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\instapy-quickstart-master\quickstart.py", line 67, in <module>
    session.like_by_tags(random.sample(like_tag_list, 3),
  File "C:\Python\Python310\lib\site-packages\instapy\instapy.py", line 1980, in like_by_tags
    inappropriate, user_name, is_video, reason, scope = check_link(
  File "C:\Python\Python310\lib\site-packages\instapy\like_util.py", line 619, in check_link
    media = post_page[0]["shortcode_media"]
KeyError: 0

Can you help me?

**Comment by sclab-es** [comment]
Same for me. i dont have any clue why

**Comment by Crashermage** [comment]
Same problem(

**Comment by jay40233** [comment]
Hi y'all, it seems like some APIs got changed and the returned structure of `post_page` became different.
As a workaround, you can try changing https://github.com/InstaPy/InstaPy/blob/master/instapy/like_util.py#L619-#L622 to be:
```
        media = post_page['items'][0]
        is_video = media["media_type"] == 2
        user_name = media["user"]["username"]
        image_text = media["caption"]["text"]
```
and also https://github.com/InstaPy/InstaPy/blob/master/instapy/like_util.py#L625-#L626 to be:
```
 latest_comments = window._sharedData.entry_data.PostPage[
 0].comments;
```

I hope that helps!

**Comment by kevb10** [comment]
this fixed my issues. thanks a lot @jay40233
