### ISSUE TITLE
Database of already followed?

### ISSUE THREAD

**Issue by omerbadawy11** [InstaPy/InstaPy#661]
I'm wondering if the bot keeps a database of the already followed people. i tested it on random profiles and restarted the bot and it tried to follow the private accounts that already declined my follow the first time.. many of them complained too. can i disable that in anyway?
Thanks 💟

**Comment by timgrossmann** [comment]
@omerbadawy11 I keeps track of the people you already followed `times=x` in the `set_do_follow` feature.
However, this is not implemented in every of the actual follows yet....

**Comment by alexmourer** [comment]
I don't believe this works if you are following users followers or who they are following.

**Comment by bombsandbottles** [comment]
So to be safe, we should avoid following a users followers and avoid following who a user follows for now?  I have also just noticed this issue.
