### ISSUE TITLE
No way to create posts?

### ISSUE THREAD

**Issue by kaijif** [InstaPy/InstaPy#6630]
## Expected Behavior
I would think that an Instagram automation library as comprehensive as this one would have a way for one to create posts.
## Current Behavior
However, I am unable to find one.
## Possible Solution (optional)
Perhaps I am mistaken. If not, however, this seems like something that this library should be able to do.

**Comment by juniegrat** [comment]
Just read the bio of the repo it says: "Tooling that automates your social media INTERACTIONS to “farm” Likes, Comments, and Followers on Instagram".(I put an emphasis on interaction) So i think you should look to something like [Instagrapi](https://github.com/adw0rd/instagrapi). Hope it helps.
