### ISSUE TITLE
How can I increase the speed of instaPY?

### ISSUE THREAD

**Issue by albert-galeev** [InstaPy/InstaPy#665]
**How can I increase the speed of instaPY?**

**Comment by timgrossmann** [comment]
@seuraltimez Not at all

**Comment by BernardoGO** [comment]
Reduce page_delay: page_delay=5
Set sleep reduce: session.set_sleep_reduce(25)

**Comment by timgrossmann** [comment]
@BernardoGO This will speed up some of the features but won't make InstaPy faster in general
