### ISSUE TITLE
Liking/following is broken

### ISSUE THREAD

**Issue by GonzaloZiadi** [InstaPy/InstaPy#667]
I am running InstaPy on an EC2 instance. It runs fine and the logs say `--> Image Liked!` and `--> Now Following!`, but when I check the given link the image was not liked and the user was not followed. This happens over and over, it is not a random occurrence.

The comments work fine.

I was on the latest Selenium, but downgraded to 2.53.6 to see if that would make a difference but it did not.

Any ideas?

**Comment by omidedipidizi** [comment]
same issue running on server Ubuntu ....

**Comment by luisramirezdev** [comment]
Same issue with Raspberry Pi

**Comment by hoseinit** [comment]
Same Issue with Ubuntu 64bit

**Comment by cagalindo** [comment]
Instagram could be catching on. I just set this up today, tested running on Ubuntu Digital Ocean and from my Mac, both working fine.

**Comment by converge** [comment]
I think this problem was fixed and there isn't interaction here for a long time. Please, reopen this issue if you need it.
