### ISSUE TITLE
ClarifaiAPP Module Issue

### ISSUE THREAD

**Issue by darksteal** [InstaPy/InstaPy#6697]
When trying to use both quickstart.py or creating my own script and importing instapy I get the message below.

ModuleNotFoundError: No module named 'clarifai.rest'

I have already satisfied all dependencies for clarafai using:
pip install -U clarifai

Get same error message

Running Python 3.10.6 on Ubuntu 22.04.1 LTS

**Comment by maxclax** [comment]
```
pip uninstall clarifai
pip install clarifai==2.6.2
```

**Comment by darksteal** [comment]
That did the trick, thanks!
