### ISSUE TITLE
Can't find the Like button?

### ISSUE THREAD

**Issue by Namaslayer** [InstaPy/InstaPy#670]
I was running InstaPy this morning and it seems like the program couldn't find the like button on one of the posts, and then just quit because it didn't know what to do.

Anyone else have this issue?

<img width="1129" alt="screen shot 2017-09-18 at 10 01 34 am" src="https://user-images.githubusercontent.com/31394074/30557540-7d480010-9c63-11e7-8a4c-8bef75802e59.png">

**Comment by converge** [comment]
the bug is fixed if you update to latest version. pls, reopen if you need.

**Comment by Namaslayer** [comment]
Awesome! How do I update to the latest version?

**Comment by timgrossmann** [comment]
@Namaslayer `git pull`
