### ISSUE TITLE
Problem with following from the List GUI

### ISSUE THREAD

**Issue by creativehunters** [InstaPy/InstaPy#677]
![bez nazwy](https://user-images.githubusercontent.com/32109713/30643906-e64188bc-9e10-11e7-9361-ab7349fcb22a.png)

as on the screenshot.

It is openening the first account from the List (GUI) and follow and then the second account from the List is opened and then there is this problem with following.

Anyone can help me?

**Comment by timgrossmann** [comment]
@creativehunters Please post the solution to your problem once the issue is closed.

**Comment by creativehunters** [comment]
update GUI to version 0.7 helped
