### ISSUE TITLE
AttributeError: 'InstaPy' object has no attribute 'follow_user_following'

### ISSUE THREAD

**Issue by creativehunters** [InstaPy/InstaPy#681]
Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    session.follow_user_following(['natgeo' ], amount = 10, random=True)
AttributeError: 'InstaPy' object has no attribute 'follow_user_following'

**Comment by timgrossmann** [comment]
@creativehunters What was the problem?
Could you quickly describe the solution?

**Comment by creativehunters** [comment]
downloading lastest version of instapy.py and unfollow_util.py helped
