### ISSUE TITLE
session.follow_user_followers() Throws this error randomly>> IndexError: list index out of range

### ISSUE THREAD

**Issue by rokpalash** [InstaPy/InstaPy#684]
While testing session.follow_user_followers(), I ran into this error multiple times randomly. At times this works perfectly and other times it kills the script with this error.

Logged in successfully!
--> Ongoing follow 1, now following: *****
--> Ongoing follow 2, now following: *****
('--> Total followNum reached: ', 2)
--> Ongoing follow 1, now following: ****
--> Ongoing follow 2, now following: *****
('--> Total followNum reached: ', 2)
Traceback (most recent call last):
  File "quickstart.py", line 13, in <module>
    session.follow_user_followers(['dailystoic', 'dailystoic', 'stoicismdaily'], amount=2, random=False, interact=True)
  File "/Users/palash/InstaPy/instapy/instapy.py", line 902, in follow_user_followers
    userFollowed += follow_given_user_followers(self.browser, user, amount, self.dont_include, self.username, self.follow_restrict, random, sleep_delay)
  File "/Users/palash/InstaPy/instapy/unfollow_util.py", line 435, in follow_given_user_followers
    personFollowed = follow_through_dialog(browser, user_name, amount, dont_include, login, follow_restrict, allfollowing, random, delay, callbacks=[])
  File "/Users/palash/InstaPy/instapy/unfollow_util.py", line 255, in follow_through_dialog
    .find_elements_by_tag_name("a")[1].text)
IndexError: list index out of range

**Comment by Pormientras** [comment]
I got exactly the same, I just restart the script but I wish there was a way to fix or make the script restart itself after this error

**Comment by 46960** [comment]
The same thing happens to me too. I just remove the name of the IG User at whom the script encountered the error, and restart it. But it is really starting to happen every time I run the script, so that I constantly have to monitor it and restart it if it crashes. Any leads so far as to how this could be fixed?

**Comment by julianNNss** [comment]
I have the same problem, any solution?

**Comment by converge** [comment]
hey guys @rokpalash @Pormientras @46960 , some news about it ? is it still happening ?

**Comment by converge** [comment]
No interaction for a long time, reopen it if you're having this issue.
