### ISSUE TITLE
No module named requests.

### ISSUE THREAD

**Issue by blobbyblo** [InstaPy/InstaPy#690]
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\Bobby\Documents\GitHub\InstaPy\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "C:\Users\Bobby\Documents\GitHub\InstaPy\instapy\instapy.py", line 15, in <module>
    from .clarifai_util import check_image
  File "C:\Users\Bobby\Documents\GitHub\InstaPy\instapy\clarifai_util.py", line 3, in <module>
    from clarifai import rest
  File "C:\Users\Bobby\AppData\Local\Programs\Python\Python36\lib\site-packages\clarifai-2.0.31-py3.6.egg\clarifai\rest\__init__.py", line 3, in <module>
  File "C:\Users\Bobby\AppData\Local\Programs\Python\Python36\lib\site-packages\clarifai-2.0.31-py3.6.egg\clarifai\rest\client.py", line 14, in <module>
ModuleNotFoundError: No module named 'requests'

Running on Windows 10 right after I used the Windows PowerShell script and configured my username, password, and likes with the GUI.

**Comment by blobbyblo** [comment]
I did not stop the import of clarifai as it was not being imported as said in the Documentation. Is there an updated line I should stop the import of?

**Comment by cclauss** [comment]
On the command line do: __pip install requests__

**Comment by yg2dras1** [comment]
hi guys, i'm having a similar problem - 
C:\Users\Patrick\Documents\GitHub\InstaPy>py -3.6 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "C:\Users\Patrick\Documents\GitHub\InstaPy\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "C:\Users\Patrick\Documents\GitHub\InstaPy\instapy\instapy.py", line 18, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

sorry, newbie here. how do i solve this?

**Comment by cclauss** [comment]
Same answer as above.

**Comment by yg2dras1** [comment]
@cclauss , i've already installed requests:


C:\>pip install requests
Requirement already satisfied: requests in c:\users\patrick\appdata\local\programs\python\python36-32\lib\site-packages
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\patrick\appdata\local\programs\python\python36-32\lib\site-packages (from requests)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\patrick\appdata\local\programs\python\python36-32\lib\site-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\patrick\appdata\local\programs\python\python36-32\lib\site-packages (from requests)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\patrick\appdata\local\programs\python\python36-32\lib\site-packages (from requests)

then when I run quickstart.py:

C:\Users\Patrick\Documents\GitHub\InstaPy>quickstart.py
Traceback (most recent call last):
  File "C:\Users\Patrick\Documents\GitHub\InstaPy\quickstart.py", line 3, in <module>
    from instapy import InstaPy
  File "C:\Users\Patrick\Documents\GitHub\InstaPy\instapy\__init__.py", line 2, in <module>
    from .instapy import InstaPy
  File "C:\Users\Patrick\Documents\GitHub\InstaPy\instapy\instapy.py", line 18, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

can you help please...

**Comment by Tjorriemorrie** [comment]
Run the following and paste the responses:
`which python`
`which pip`

**Comment by yg2dras1** [comment]
is this for looking up the version? for some reason this command doesn't work for me, but i typed the following and got the following responses - 

C:\>pip --version
pip 9.0.3 from c:\users\patrick\appdata\local\programs\python\python36-32\lib\site-packages (python 3.6)

C:\>python --version
Python 3.6.3

**Comment by cclauss** [comment]
__which__ does not work because @yg2dras1 is running on Windows.

**Comment by Tjorriemorrie** [comment]
The answer above should work, else try `python -m pip install -U requests`

**Comment by yg2dras1** [comment]
@Tjorriemorrie , @cclauss , thank you for your input. really appreciate it. still a noob here.

i've tried your suggestion @Tjorriemorrie , it indicated that requests is already installed

maybe i should uninstall and reinstall??

**Comment by cclauss** [comment]
Nope.  Try:
* __pip freeze__ and make sure that requests appears there (I bet it will)
* __python -c "import requests ; print(requests.\_\_version\_\_)"__
* Have you done all of https://github.com/timgrossmann/InstaPy/blob/master/docs/How_to_Windows.md ?

Overall I would guess that there are multiple versions of Python on your computer and the one that is running InstaPy is different from the one that you get when you type __python__ on the command line.

**Comment by yg2dras1** [comment]
@cclauss yes i think i did everything, installed build tools, .net framework, i set the environment, installed selenium, pyvirtualdisplay, i placed chromedriver in assets folder and took out the .exe...

**Comment by yg2dras1** [comment]
@cclauss so I did what you said - 

C:\Users\Patrick>pip freeze
certifi==2018.1.18
chardet==3.0.4
EasyProcess==0.2.3
emoji==0.4.5
idna==2.6
pipenv==11.9.0
PyVirtualDisplay==0.2.1
requests==2.18.4
urllib3==1.22
virtualenv==15.2.0
virtualenv-clone==0.3.0

C:\Users\Patrick>python -c "import requests ; print(requests.__version__)"
2.18.4

so...what does this mean? it means requests is there right...

**Comment by cclauss** [comment]
Correct.  You have a relatively current Python (3.6.3 vs. 3.6.4) and you have a current requests properly installed in it.  That means that you have at least two different versions of Python on your machine and that the version of Python that is running InstaPy is not the same one that you are getting when you type __python__ on the command line.

**Comment by yg2dras1** [comment]
so that's it!! ok so how do i fix it? haha!

**Comment by cclauss** [comment]
Sorry...  I am not a Windows guy.

**Comment by yg2dras1** [comment]
ok. in any case this was very helpful!

**Comment by cclauss** [comment]
@yg2dras1 C:>__python3 quickstart.py__  # Does that work?

**Comment by yg2dras1** [comment]
@cclauss tried it, doesn't work...

it's ok. i'm looking at installing ubuntu now. i've given up on windows. haha!

**Comment by Tjorriemorrie** [comment]
You can try anaconda as well, but you'll have to use `conda` instead of `python` I think to run and install stuff. Can just check their documentation.

**Comment by vnkvp** [comment]
ModuleNotFoundError: No module named 'clarifai'

Anyone getting this error too ?

**Comment by cclauss** [comment]
@vnkvp `python3 -m pip clarifai`
* https://pypi.org/project/clarifai/
