### ISSUE TITLE
How to track username change through Instapy?

### ISSUE THREAD

**Issue by CodeMaster1** [InstaPy/InstaPy#691]
Hi,

I have implemented a change to comment only once per user profile. However, this does not work when the username is changed. Is there a way get the original username or old usernames?

Thanks,
Amitesh

**Comment by timgrossmann** [comment]
@CodeMaster1 Not yet.
Just download the repository again if you want to use 2 users in parallel

**Comment by CodeMaster1** [comment]
@timgrossmann Hi Tim,. I have implemented that functionality to comment only once per user profile. However,  when the user name is changed (for example code_123 to code123), the program is commenting once again after name change. The username here is not referring to one for which the program is run but to the one on which the comment is left on the image. I wonder is there a way to track username change? I hope question is clear now.

**Comment by converge** [comment]
@CodeMaster1 blacklist feature can help you ? #835

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
