### ISSUE TITLE
Does FollowedPool keep track of number of times a user is followed?

### ISSUE THREAD

**Issue by tommyle** [InstaPy/InstaPy#692]
When a user is unfollowed they are removed from the list. How does the script know not to follow them again?

Edit: If you kill the session prematurely InstaPy does not dump_follow_restrictions to the json file. If you unfollow someone during the session that ended prematurely it is possible you may follow them again.

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
