### ISSUE TITLE
Inconsistentcy, and unknown errors

### ISSUE THREAD

**Issue by Namaslayer** [InstaPy/InstaPy#693]
Hey Everyone!

First of all thanks to everyone here! This is amazing information, and I'm so thankful for all of the help.

I am new to this all. Have a couple friends who are programmers who are helping me out, but I'm running into trouble running the program on a server. I followed [this tutorial](https://medium.com/@mcnamee/using-open-source-software-to-build-your-instagram-followers-205f908cf657) for setting up InstaPy on a server, and sometimes it works flawlessly. Others I get different errors, and I am teaching myself all of this as I go so the learning curve is a bit tricky.

Using Digital Ocean Droplets to host InstaPy, how can I get reports of past sessions so I can share my errors here. I want to explain the problems that I'm having, but I don't really know exactly what they are yet.

**Comment by Namaslayer** [comment]
using terminal, I was able to capture this screenshot. This is the current issue I'm having. But just 6 hours ago, I ran the same exact script and it came back with no errors and ran flawlessly for 4.5 hours. Whats happening??????

<img width="975" alt="screen shot 2017-09-25 at 2 46 34 pm" src="https://user-images.githubusercontent.com/31394074/30832595-7b05855a-a200-11e7-8c3a-ba1707b323aa.png">

**Comment by converge** [comment]
hey @Namaslayer , did the latest version fixed it ? pls, reopen the issue if you need.
