### ISSUE TITLE
unfollow command keeps crashing

### ISSUE THREAD

**Issue by ediooo** [InstaPy/InstaPy#694]
i keep getting this error, any idea why?

('unfollow loop error \n', 'Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(), \'Follow\')]"}\n  (Session info: chrome=60.0.3112.113)\n  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.6 x86_64)\n')

Thanks!

**Comment by converge** [comment]
is your repo updated ?

**Comment by converge** [comment]
I'm closing it since there is no reply for a long time. Please reopen it if you need.
