### ISSUE TITLE
Feature: Only unfollow users who don't follow me

### ISSUE THREAD

**Issue by ediooo** [InstaPy/InstaPy#695]
> [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=49761251)](https://www.bountysource.com/issues/49761251-feature-only-unfollow-users-who-don-t-follow-me?utm_source=49761251&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Is this currently possible somehow?

If not any chance to add it to the script?

Thanks!

**Comment by timgrossmann** [comment]
@ediooo Nope, feel free to post a bounty on it on bountyhunt :wink:

**Comment by ediooo** [comment]
@timgrossmann  Would love to, how does it work though? You mean this? https://www.bountysource.com/ or how/where can i do it?

**Comment by timgrossmann** [comment]
@ediooo Yes, you can simply post a bounty here> https://www.bountysource.com/issues/49761251-feature-only-unfollow-users-who-don-t-follow-me

I'll update the issue once you've done that to make sure people see that there is a bounty on this issue

**Comment by timgrossmann** [comment]
#810
