### ISSUE TITLE
Feature suggestion: Blacklist certain users entirely

### ISSUE THREAD

**Issue by ediooo** [InstaPy/InstaPy#696]
Hi,
Again, not sure if i am missing something and its already possible, but i'd love to be able to blacklist a list of users from any instapy actions (liking, following, unfollowing etc)
I know there is something to keep it from unfollowing "friends" but i'd love to see something more broad for people you explicitly don't want to interact with through instapy.

**Comment by timgrossmann** [comment]
```python
Ignoring Users

#completely ignore liking images from certain users

session.set_ignore_users(['random_user', 'another_username'])
```

**Comment by ediooo** [comment]
Thanks, i am aware of that - but would it keep the script from following those too? 
Since it explicitely says "ignore liking images" i assumed it limited to that.

I mean when using the function follow the followers of a certain account (not related to liking images)

**Comment by timgrossmann** [comment]
@ediooo Yes, as far as I know @BernardoGO implemented that into the follow_user_followers feature
