### ISSUE TITLE
Raspberry Pi 3 & Firefox

### ISSUE THREAD

**Issue by kuzne4eg** [InstaPy/InstaPy#698]
In the newest version of raspbian you will not get firefox.
making apt-get install firefox will give you dependecies error with libhumspell so you will need to DOWNGRADE it to 1.3 version...

wget http://ftp.de.debian.org/debian/pool/main/h/hunspell/libhunspell-1.3-0_1.3.3-3_armhf.deb
sudo dpkg -i libhunspell-1.3-0_1.3.3-3_armhf.deb
sudo apt-get -f install

than

sudo aptitude install firefox....

**Comment by ghost** [comment]
@kuzne4eg it will work with firefox-esr v52

**Comment by andresuman** [comment]
Well, i finally did a "clean install" on Raspberry Pi 3 and its working! Easyer than the documentation. the steps:

1. Install Raspbian (use NOOBs)
2. sudo apt-get update && sudo apt-get upgrade
3. mkdir Projects
4. cd Projects
5. git clone https://github.com/timgrossmann/InstaPy.git
6. cd InstaPy
7. sudo pip install .
8. sudo apt-get install firefox-esr
9. open Firefox and skip "import Data from Chromium", close Firefox
10. copy /examples/firefoxExample.py to /Projects/InstaPy and edit file to your liking
11. "python firefoxExample.py" to run

**Comment by emanuelepasin** [comment]
@andresuman I follow all the steps but I'm facing this error:

>      selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by andresuman** [comment]
@emanuelepasin please copy tour firefoxExample.py here (delete your username and password) and i will try do run in my Raspberry. 
I'm getting some random errors, sometimes i run the same script 2 or 3 times and its working. :(

**Comment by emanuelepasin** [comment]
@andresuman here it is:

```
from instapy import InstaPy
InstaPy(username='*****', password='*****', use_firefox=True, page_delay=25)\
    .set_switch_language(False)\
    .login()\
    .set_do_comment(True, percentage=10) \
    .set_comments(['Cool!', 'Awesome!', 'Nice!']) \
    .set_dont_like(['food', 'girl', 'hot']) \
    .like_by_tags(['dog', '#cat'], amount=2) \
    .end()

```

**Comment by gitpatrickhub** [comment]
@emanuelepasin are you using a display/monitor or running it headless? If running headless, you need to use xvfb

Also, what configuration are you using on the pi (version of raspbian, python, selenium, firefox, geckodriver)?

**Comment by emanuelepasin** [comment]
@gitpatrickhub you're right, sorry! I was using ssh (headless) but then I've tried via VNC and now it's working! 

thanks

**Comment by andresuman** [comment]
I'm using VNC, no xvfb needed.
Raspbian 9 (stretch)
Python 2.7.13
selenium 2.53.6
firefox  52.4.0

**Comment by gitpatrickhub** [comment]
I'm using headless;

Raspbian Jessie
Python 2.7.9
Selenium 2.53.6
Firefox 52.3.0
Geckodriver updated to 0.19.0

verified commenting still does not work using Interact_user_followers. Also noticed that it only Likes the first image, even though the script outputs the other 2 images being liked. Commenting also does not account for type of media. #660 #644 #566 

@imakethefish can you confirm you able to comment correctly and provide your configuration

**Comment by ghost** [comment]
@gitpatrickhub out of town at the moment I will update after the weekend

**Comment by gitpatrickhub** [comment]
@imakethefish any chance you confirm these features are working and what your RPI3 configuration is?

@converge you seem to be helping fix all things instapy these days. Any chance you can help out here (#660 #644 #566)

**Comment by converge** [comment]
hey @gitpatrickhub I would love to help, but my RPI is the RPI 1 B model and there isn't chromedriver or geckodriver for it.

If you guys wanna send me one RPI3, I donate my RPI 1 B to https://github.com/fablabjoinville guys.

**Comment by ghost** [comment]
@gitpatrickhub hey totally forgot about this my apologies 

I can confirm interact features working on RPI3 with below config:

Raspbian Jessie
Python 3.5
Selenium 2.53.6
Firefox 52.3.0
Geckodriver updated to 0.19.0

**Comment by gitpatrickhub** [comment]
@imakethefish thanks! I’ll try using python 3.5 later this week and post results.

**Comment by gedankenstrom** [comment]
@imakethefish @gitpatrickhub

It works fine on my Raspberry Pi 3
config:

Raspbian GNU/Linux 9 (stretch) (nogui)
Python 3.5
Selenium 2.53.6
Mozilla Firefox 52.4.0
Geckodriver 0.18.0

**Comment by gitpatrickhub** [comment]
Thanks @imakethefish @bjo3rns @converge 
I upgraded to python 3.5 and is now working as expected.

@timgrossmann we can close the bounty and associated issues: #660 #644 #566
I think we should update the How to Doc for Raspberry Pi to indicate use of known working configurations as documented in this issue, it will help prevent future issues when people try to deploy on RPI3.

**Comment by kuzne4eg** [comment]
Actually there is no any issues on raspberry pi 3 & python 2.7...
This kind of install does work.
The only problem is that Firefox is too slow loading and sometimes gives error loading profile.

**Comment by gitpatrickhub** [comment]
@kuzne4eg I wasn't able to get commenting using Interact_User_Followers to work with python 2.7. The console would indicate the image was Commented, but when I verified the user account for the Comment was not there, nor did it account for the Media specification. I'd be curious if it's working your pi what configuration you have.

**Comment by acortex** [comment]
Hi guys,

I get this error code.. 

I got a raspberry pi 3B

root@raspberrypi:/home/pi/Projects/InstaPy# "python firefoxExample.py"
bash: python firefoxExample.py: opdracht niet gevonden
root@raspberrypi:/home/pi/Projects/InstaPy# python firefoxExample.py
python: can't open file 'firefoxExample.py': [Errno 2] No such file or directory

**Comment by Tjorriemorrie** [comment]
run `find /home/pi/Projects -type f -name "firefoxExample.py"` to find the file.
