### ISSUE TITLE
New Logo for InstaPy

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#699]
Hey InstaPy Community,

since InstaPy isn't going to go away too soon, I think it's time to get a real logo.
If someone of you is interested or knows someone that is interested I'd love them to submit a logo.

We can then show them off in this thread and the community decides which should become the new Logo.

What do you guys think?

**Comment by abhstehRamine** [comment]
I think it could possible be our logo for life.
@datteba @keivan85 @alexmourer @PetrosBl @pekapa @TGlide @lanquemar @wordythebyrd @abraztsov @sunnypatel165 @nosahama @seemethere @cclauss @raj61 @hicay @CuARRONBADO @tobyf93 @jungfish @BernardoGO @tibor @atomhax @binhonglee @littleswany @ahmadudin @onyxim @vlntdds @apertureless @iSimonWeb @Albertmoiseev @vitormvasc @saurabh-kumar-vit @TheXeon81 @sterid @benvegel @calvinclaus @brammittendorff @AlainPilon @alxnorden @Jayphen 


![new logo](https://image.spreadshirtmedia.com/image-server/v1/mp/compositions/P1000736869MPC1001299912/views/1,width=300,height=300,appearanceId=2,backgroundColor=E8E8E8,version=1485256808/like-t-shirts-men-s-t-shirt.jpg
)

**Comment by timgrossmann** [comment]
@abhstehRamine Good that we are serious here... Especially since **Insta**Py has nothing to do with Facebook as the Logo suggests...

**Comment by atomhax** [comment]
This discussion is starting out as a train wreck. 

Back on topic. A serious logo by the community would actually be an important rite of passage for this project. I know many of the users who frequent this project don’t know how to code. This is a good way for the non tech (and techie users) users to contribute. No idea is too absurd.. well almost no idea ;)

**Comment by atomhax** [comment]
Additionally.. congrats Tim on keeping this project alive. I’m sure it’s been no small task. I certainly thought the project was going to get a takedown notice by IG when you first started. You’ve inspired many programmers to pick up python.. Another not so small task. If I’m ever in Germany I owe you a beer. 🎂🍻🎉

**Comment by timgrossmann** [comment]
@atomhax Thank you!

**Comment by binhonglee** [comment]
Did that person just created a new GitHub account to post this inappropriate photo while tagging all the contributors? Wow, that amount of effort.

**Comment by timgrossmann** [comment]
@binhonglee Looks like so 😄

**Comment by monaletham** [comment]
@timgrossmann It's really great, that this is something I can do. Sadly I can't program, so I can't contribute to the project otherwise. But I really like to design things, so here is my submission to the logo search.

![logo](https://user-images.githubusercontent.com/32476928/31112690-0d1563ec-a7ca-11e7-9ab2-445417cccf2d.png)

Love to use your tool by the way!

**Comment by timgrossmann** [comment]
@monaletham Thank you for the serious contribution to this, at least one new Logo design!

I really like it.

**Comment by franksinsan** [comment]
@timgrossmann Hello, I also did logos. Hope they like it.
Which you like better?

![ab_instapy0202](https://user-images.githubusercontent.com/32504695/31160447-4e463c7c-a885-11e7-99d1-13b49c387694.jpg)
![ab_instapy0301](https://user-images.githubusercontent.com/32504695/31160448-4e56a9ae-a885-11e7-85f0-a4577c6cf5d5.jpg)

**Comment by timgrossmann** [comment]
@franksinsan Haha, awesome! 
We are slowly getting somewhere where we actually have a real "competition" 😄

**Comment by jonathandalton** [comment]
@timgrossmann As we like to say over here in Australia, G'Day All!
Even though I'm mostly designing industrial kind of stuff, I thought I'd contribute something to this project as well. 
I use it on my private account to, hopefully, get some freelance opps.

Let me know what you think. I really like the logos so far, probably fits way better than mine.

![3](https://user-images.githubusercontent.com/32505201/31161036-627d465a-a889-11e7-92e9-18da551ea7f1.jpg)

**Comment by cclauss** [comment]
What about one that embeds https://www.python.org/community/logos/ inside the instagram logo?

**Comment by timgrossmann** [comment]
@jonathandalton Hey, thank you for taking part in this! 
They definitely bring some kind of difference into this competition. 

Thanks 👍

**Comment by timgrossmann** [comment]
@cclauss That actually is a really nice idea! Let's see if somebody can come up with something

**Comment by timgrossmann** [comment]
One guy sent me this logos and said he doesn't want to sign up to post something so here they are:
Thanks Sam for contributing!

![mc12m0a_instapy converted -01](https://user-images.githubusercontent.com/16529337/31211736-656cd976-a950-11e7-8443-942d365e0357.jpg)
![mc63m0a_instapy converted -01](https://user-images.githubusercontent.com/16529337/31211737-657cf54a-a950-11e7-9b8e-ca3f2fc3f30e.jpg)

**Comment by remorses** [comment]
Just an idea, let me know if I should refine it [
![instapy](https://user-images.githubusercontent.com/31321188/31248951-dea1831c-aa15-11e7-8223-1596b02a7de8.jpg)
](url)

**Comment by timgrossmann** [comment]
@remorses Really like the simplicity and minimalism of it. 

Thank you for contributing!

**Comment by sunnypatel165** [comment]
@franksinsan that's downright beautiful man!

**Comment by alx-a** [comment]
I like @franksinsan idea. IMHO the robot/automation aspect is more important than the language or application methodology used. Otherwise one might as well throw chrome driver logo into the mix.
What does the application do from the end user perspective ? automated robot activity on instagram accounts. So a riff on a robot and the IG logo feels like an easy visual representation of the applications role.

**Comment by timgrossmann** [comment]
Thank you all, I think we have a winner!
