### ISSUE TITLE
Advanced User Engagement

### ISSUE THREAD

**Issue by tibor** [InstaPy/InstaPy#70]
Following an user just after one like seems a bit implausible.

In my opinion it would be good to like 2 or 3 photos of an user before following them. This way our bot behaves and looks more like a real user and should raise engagement rates.

So the new strategy would be like:

1. Search for Photos by #tag
2. Like (and comment) a photo
For every Xth photo:
3. Visit the profile and like some more randomly chosen photos
4. Follow

**Comment by timgrossmann** [comment]
@tibor Thank you for sharing your thoughts with everyone.
These are some really nice ideas. If you want to implement any of these, feel free to do so.

**Comment by AlainPilon** [comment]
Actually, I dont think we should randomly like photos from the user. Instead, pick those with the same keywords or those which already have the more likes.

**Comment by timgrossmann** [comment]
@AlainPilon Yes, that's probably a good idea. 
But it's way harder, that way you need to look at each picture and compare the "semantic distance" of the posts.
With the random approach it would be way easier to implement

**Comment by CodeMaster1** [comment]
I have an idea that seems pretty legit to me. How do you guys think about this?

Suppose, I only posts travel related photos and I know my audience is mostly 
audience that likes travel related photos. So, I want to increase my engagement
with those kind of users. In this case, I pick up followers of "natgeo" as my audience.
The next step is to fetch followers of "natgeo" and likes/comment their content
and interact with them.

**Comment by timgrossmann** [comment]
@CodeMaster1 Yes, this will be part of V1.
It's a good idea quite some people already suggested

**Comment by timgrossmann** [comment]
#484
