### ISSUE TITLE
Question: session.follow_user_followers

### ISSUE THREAD

**Issue by ediooo** [InstaPy/InstaPy#701]
Hi,

In the readme it says that the set_do_follow function has a "times" parameter to determine how many times to follow a user:
#session.set_do_follow(enabled=True, percentage=10, times=1)

Does the session.follow_user_followers function have this as well?
Would this work:

session.follow_user_followers(['user1', 'user2'], amount=6, random=True, sleep_delay=74, times=1)

Thanks!

**Comment by timgrossmann** [comment]
@ediooo No, the `follow_user_followers` has no separate parameter for this.
The documentation in the readme is complete, so there are no more parameters than you can find there.

As far as I know, the `set_do_follow` functions sets the times attribute globally and the `follow_user_followers` makes use of that

Correct me if I'm wrong @ahmadudin @BernardoGO
