### ISSUE TITLE
Feature: Follow user followers and do like and comment for last image.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#702]
I don't see why we don't do it.

Thanks.

**Comment by sionking** [comment]
Now I see there is a feature like this:
```python
#Interact with the people that a given user is following
#set_do_comment, set_do_follow and set_do_like are applicable
session.set_user_interact(amount=5, random=True, percentage=50, media='Photo')
session.set_do_follow(enabled=False, percentage=70)
session.set_do_like(enabled=False, percentage=70)
session.set_comments(["Cool", "Super!"])
session.set_do_comment(enabled=True, percentage=80)
session.interact_user_followers(['natgeo'], amount=10, random=True)
```

But I can't find more details about each parameter (and there are many)

Thanks.

**Comment by timgrossmann** [comment]
@sionking Please look at the Readme.
Every single one of the methods is described there (what every parameter does as well)

Thank you

**Comment by sionking** [comment]
Isn't that what I quoted in my comment ? there is no much details.
I am also looking at the README.md file, which looks the same.

**Comment by timgrossmann** [comment]
@sionking 

> But I can't find more details about each parameter

No it's not what you quoted.

Example of what set_user_interact does
```python
# For 50% of the 30 newly followed, move to their profile
# and randomly choose 5 pictures to be liked.
# Take into account the other set options like the comment rate
# and the filtering for inappropriate words or users

session.set_user_interact(amount=5, random=True, percentage=50, media='Photo')
session.follow_user_followers(['friend1', 'friend2', 'friend3'], amount=10, random=False, interact=True)
```

Follow/Comment/Like all work the same way
```python
#default enabled=False, follows ~ 10% of the users from the images, times=1 (only follows a user once (if unfollowed again))

session.set_do_follow(enabled=True, percentage=10, times=2)
```

Interact_user_followers is the same like every other method like that is...
amount is the number of people to be interacted with, random means that people will not be interacted with from top to bottom but randomly picked and the list of usernames simply is a list of usernames which will be worked with one after the other
```python
#Interact with the people that a given user is following

session.interact_user_followers(['natgeo'], amount=10, random=True)
```

Hope that helps.
