### ISSUE TITLE
Runig on server , but it not liking !!

### ISSUE THREAD

**Issue by omidedipidizi** [InstaPy/InstaPy#703]
First of all thank you for this wonderful tool !!

I just started to run the app on Digital Ocean Server. it says " Image Liked ,  now commented .... " !! but when i go to my app to see what i just liked , it turn that actually i did not like any photo ... And just realized that this happen when i'm loged in trough my phone too ...

could anyone explain what's happening please

**Comment by jacktator** [comment]
Same issue here. The same code was working yesterday, but today got stuck at the following:
```
$ python3 ./quickstart.py
Logged in successfully!
Tag [1/35]
--> b'#romeandyou'
```
And the whole process just hangs at that tag.

I tried commented out like_by_tag, and use like_by_location, same issue (hang) as well.

**Comment by jacktator** [comment]
Traceback (most recent call last):
  File "./yilanfu.py", line 15, in <module>
    session.like_by_tags(['#romeandyou','#autumnmood','#autumn','#herbststimmung','#darknature','#darkart','#darkatmosphere','#darkphotography','#melancholy','#darkmood','#beautifuldarkness','#shadeofblack','#photoart','#ig_artistry','#architecture','#buildings','#architexture','#city','#buildings','#urban','#design','#minimal','#cities','#town','#perspective','#cityscape','#citybestpictures','#estheticlabel','#bestcitybreaks','#amesterdamview','#vscoaward','#moodygrams','#ig_powerclub','#creatandcapture','#beautifuldestinations'], amount=3)
  File "/srv/users/serverpilot/apps/instapy/public/instapy/instapy.py", line 475, in like_by_tags
    links = get_links_for_tag(self.browser, tag, amount, media)
  File "/srv/users/serverpilot/apps/instapy/public/instapy/like_util.py", line 153, in get_links_for_tag
    load_button.click()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-83-generic x86_64)

**Comment by geewaq** [comment]
Same thing happened with mine. It was working perfectly yesterday. Did Instagram changed their code?

**Comment by omidedipidizi** [comment]
Mine there's no such error !!! it says liking , following ..... but it not in reality ....

<img width="1036" alt="2017-10-01 at 8 30 49 pm" src="https://user-images.githubusercontent.com/25254194/31090275-1b7e4e94-a775-11e7-895c-598874ec893d.png">

**Comment by CrazedRaven** [comment]
I had the same problem with **python3** but when I run it on **python2** with  Firefox 52.3.0 and Selenium 2.53.6 with the new geckodriver (0.19.0) evrything was OK

**Comment by luisramirez-m** [comment]
Hey @CrazedRaven, thanks for this info. But I'm noob.
How to install Firefox 52.3.0 on Raspberry Pi3? I try install with `sudo apt-get install firefox`, but always install Firefox 50.0

**Comment by hoseinit** [comment]
@CrazedRaven Hmmm. Let me check...thanks for sharing by the way

**Comment by hoseinit** [comment]
Nope. not working for me. @CrazedRaven

**Comment by cagalindo** [comment]
Still working for me, just set it up today on a DigitalOcean Droplet Ubuntu, Chrome (the default setup), python3

**Comment by AustineA** [comment]
Start a new droplet in DigitalOcean 

instead of installing python 3 use this to install python 2
`sudo apt-get install build-essential libssl-dev libffi-dev python-dev`

`after pip install . `
you may want to install 
`sudo apt-get install xvfb`

If it doesn't like then instagram probably blocked you from liking try after 24 hours, this happened to me.

**Comment by converge** [comment]
hey guys, some news about it ? @AustineA @cagalindo @hoseinit @CrazedRaven @omidedipidizi @geewaq @jacktator

**Comment by converge** [comment]
Since there is no more interaction here, I'm closing the issue, if you need some help about this topic, please reopen it.

**Comment by espipj** [comment]
@omidedipidizi did you managed to solve it I'm having the same issue! It shows "Photo liked" or "User Followed" but not actually in Instagram. I'm not banned as I can follow/comment/like in the webpage and app. 
Mozilla Firefox 52.5.0
Gecko 0.18
Selenium 2.53.6
