### ISSUE TITLE
why wait 25 seconds on the post page and then like it?

### ISSUE THREAD

**Issue by ujazzz** [InstaPy/InstaPy#705]
I tried to change all the sleep(2) time to sleep (0.5) in instapy.py and the like_until.py (I can do this and get away with it without getting blocked, plus my account is very old and Im capable of liking 400+ pics an hour for some reason)

I calculated the time it took for the automation to like a picture with .likebyfeed feature and it was estimated to be roughly 40 seconds from the time it was on the news feed to going on the posts location tag then to the post then to the user and then back to the post page, stays on the post page for 25 seconds and then likes the pic.

why does it have to wait 25 frustrating seconds on the post page and then like it?
with this calculation it will like only 90 pics an hour or 540 pics in 6 hours on run time. been using this automation since the beginning of its first release. earlier I was hitting more than 1500 pics in 4 hours with reducing the sleep time and less complications.

Is there a way to have this wait time on the post page to be reduced to atleast 5-7 seconds?

Reduce this wait time please its really frustrating.

**Comment by Naramsim** [comment]
@ujazzz you can modify your own code

**Comment by sk1980** [comment]
ujazzz, try to insert 
sleep(3) 

after string 
def like_image(browser, username, blacklist, logger):

in file like_util.py
