### ISSUE TITLE
Question/suggestion:  session.follow_user_followers - times parameter?

### ISSUE THREAD

**Issue by ediooo** [InstaPy/InstaPy#706]
Hi,
Is there a parameter of the amount of times to follow the same account after unfollowing it for:
#session.follow_user_followers

like there is for 
session.set_do_follow(enabled=True, percentage=10, times=1)

If not it would make a lot of sense i think!

**Comment by converge** [comment]
what I see in the horizon is a little database containing profile/user information. In this way we can track if the profile is following us, and if we followed him in the past and informations like that. 

what do you guys think ?

**Comment by tibor-stefan** [comment]
@converge really like the idea. this is absolutely necessary!
