### ISSUE TITLE
Error starting quickstart

### ISSUE THREAD

**Issue by MrTwIXx** [InstaPy/InstaPy#708]
Hey there,

I always get this error message.

from: can't read /var/mail/instapy
./quickstart.py: line 5: syntax error near unexpected token `('
./quickstart.py: line 5: `session = InstaPy(username='***', password='***', nogui=True)'

Can anyone help me. The GUI on Windows didn't work so I changed to Ubuntu

**Comment by converge** [comment]
@MrTwIXx paste your quickstart.py

**Comment by MrTwIXx** [comment]
@converge 
Its the standard quickstart file. I only added my username, password and nogui=True

**Comment by timgrossmann** [comment]
@MrTwIXx Is that a DO Droplet?
Do you have sudo permissions?

**Comment by MrTwIXx** [comment]
@timgrossmann Yep, its a DO Droplet. I use the root user so I have sudo permission

**Comment by timgrossmann** [comment]
Like @converge  already mentione

> @MrTwIXx paste your quickstart.py

**Comment by MrTwIXx** [comment]
Changed to Windows. It works there after a lot fixes. Thanks Google

**Comment by phil1995** [comment]
Add the following line to the top of the script:
`#!/usr/bin/env python`
This will instruct your shell to execute the script via python instead of trying to interpret it on its own.

**Comment by timgrossmann** [comment]
@phil1995 Great spot!

Just after you mentioned the solution realized that he called `./quickstart.py`...
