### ISSUE TITLE
Reinstalled clarifai, still says "no module named clarifai"

### ISSUE THREAD

**Issue by gamerlink123** [InstaPy/InstaPy#711]
I installed everything else correctly: https://gyazo.com/3ff6f248bdd91c6944bc6eb79d98c08b

soon as I run my batch file it gives me this error: https://gyazo.com/74475ea5dc0a58daf7b64214692568e0

I would appreciate any help!

**Comment by MrTwIXx** [comment]
@gamerlink123 
Go to master/Instapy. Open Instapy.py wirh an editor and remove "from .clarifai_util import check_image". Now it should be fixed.

**Comment by gamerlink123** [comment]
@MrTwIXx just did that, now I have this error: https://gyazo.com/e0d43e9f493ea7db9abfe405acd38349

**Comment by gamerlink123** [comment]
Just fixed it by doing:
pip install emoji
in the Scripts folder, thanks for the help!
