### ISSUE TITLE
[NEW FEATURE] Comment by location

### ISSUE THREAD

**Issue by JCADC** [InstaPy/InstaPy#714]
> [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=50057057)](https://www.bountysource.com/issues/50057057-new-feature-comment-by-location?utm_source=50057057&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Hi everyone,

Today we can only like media by location but we can't post comments. I was wondering if someone has an script for that of if we can follow the same syntax than the "regular" comment but changing to something like this:
session.set_comments(['Nice shot!'], location0='XXXX')

Thanks in advance

**Comment by timgrossmann** [comment]
@ahmadudin @BernardoGO Maybe one of you is interested :wink:

**Comment by dennisvandalen** [comment]
So you want location specific comments?

**Comment by JCADC** [comment]
Hi @dennisvandalen ,

Imagine I'm the owner of a restaurant and the people is adding the location to the pictures they're posting. I wanted to comment "Thanks for visiting us" to the pictures tagged at my place.

Basically sending comments to a location id.

Thanks!

**Comment by dennisvandalen** [comment]
You can just start a session and enable commenting.

Or is it that you don't want to like, but only comment?

```
session.set_do_comment(True, percentage=100)
session.set_comments(['Awesome', 'Really Cool', 'I like your stuff'])
session.like_by_locations(['26429/chrysler-building/', '224442573/salton-sea/'], amount=100)
```

If I do this, InstaPy starts to comment to the location posts

**Comment by ahmadudin** [comment]
I think what @dennisvandalen  said will do the job, unless you want to comment without liking the post

**Comment by anchormehra-zz** [comment]
What I did is
session.set_do_comment(True, percentage=whatever)
session.set_comments(['comment'])
session.comment_by_locations(['location'], amount=whatever)
I hope this helps.
