### ISSUE TITLE
follows people fine, then out of no where it crashes and gives me this error

### ISSUE THREAD

**Issue by gamerlink123** [InstaPy/InstaPy#716]
here is the error log: https://gyazo.com/e9fe8e2443e0ec97bb0fd56a5c619304
(as you can see the script ran fine and followed multiple people)

here is a picture of my quickstart.py : https://gyazo.com/5eb473b7c54fa248e1fa215d8a5bb4af

any help would be greatly appreciated.

**Comment by diveu** [comment]
Got the same problem here and have no idea why it happens

**Comment by gamerlink123** [comment]
Actually found a temporary "fix" even though it probably won't work 100%.  The following line of code is where the problem seems to occur.

inside the file "instapy.py" replace both occurrences of:

`followed += follow_user(self.browser, self.follow_restrict, self.username, user_name)`

with

`try:`
`    followed += follow_user(self.browser, self.follow_restrict, self.username,user_name)`
`except Exception as err:`
`    print (1)`

If you get an error about indentation make sure you are either only using spaces or tabs, can't be both in  python. Also can't seem to get the indentation right above on github for some reason, so if you are just copy and pasting make sure the lines that start with "followed" and "print" are both spaced 4 times.

**Comment by converge** [comment]
@gamerlink123 I'm trying to reprouce the error, can you paste your quickstart.py ?

**Comment by converge** [comment]
I think this is our biggest bug.
