### ISSUE TITLE
instapy.py: checked_img is an undefined name

### ISSUE THREAD

**Issue by cclauss** [InstaPy/InstaPy#723]
https://github.com/timgrossmann/InstaPy/blob/master/instapy/instapy.py#L708

__checked_img__ is an undefined name in this context. It is defined as a local variable in several other functions/methods but it is not defined until 50 lines later in this method, interact_by_users().  Undefined names can raise NameError at runtime.

This issue can be seen in: https://travis-ci.org/timgrossmann/InstaPy/jobs/283931737#L500

**Comment by timgrossmann** [comment]
@cclauss Thank you, could you fix it?

**Comment by converge** [comment]
#743 PR

**Comment by converge** [comment]
can we delete interact_by_users method ? it's not in the docs, is it obsolete ?

**Comment by timgrossmann** [comment]
@converge If you can, please leave it and add a little bit of documentation instead. 
Thank you

**Comment by converge** [comment]
#769 interact_by_users is back and InstaPy is almost 100% PEP8 code style.
this will fix this checked_img issue too
