### ISSUE TITLE
Return result of work

### ISSUE THREAD

**Issue by dbrkv** [InstaPy/InstaPy#728]
Proposing return result of script work as an object.
See https://github.com/timgrossmann/InstaPy/compare/master...sunthera:return-task-result
Probably we can include pull request #579 also

@timgrossmann what do you think?

**Comment by dbrkv** [comment]
If we do this, return type changed, then no more fluent interface to action methods like they have now:
```python
InstaPy(username='test', password='test')\
  .login()\
  .like_by_tags(['dog', '#cat'], amount=100)\
  .end()
```
becomes:

```python
instance = InstaPy(username='test', password='test').login()
instance.like_by_tags(['dog', '#cat'], amount=100)
instance.end()
```

Probably for add support of fluent interface instance can be wrapped in pipeline class

**Comment by converge** [comment]
Should we add it as a feature request ?

**Comment by dbrkv** [comment]
Depends need this or not. I noticed it is not so important feature for many and in the same time it breaks compatibility with previous versions of code.

**Comment by converge** [comment]
great work! it's merged.
