### ISSUE TITLE
Chrome driver error Selenium .. Debian

### ISSUE THREAD

**Issue by LoneWolfsMoon** [InstaPy/InstaPy#732]
![screenshot from 2017-10-09 00-56-26](https://user-images.githubusercontent.com/30674228/31321859-d5e4314c-ac8c-11e7-82db-aa1ccb8a5b77.png)

**Comment by ghost** [comment]
I also have some issues with Chrome/Selenium running on ubuntu....
![image](https://user-images.githubusercontent.com/29511257/31328152-c9bd55d2-acd3-11e7-847c-afcb75d68aab.png)

**Comment by converge** [comment]
I´m running at Debian without problem. Do you guys are using the chromedriver latest version ? https://chromedriver.storage.googleapis.com/index.html?path=2.33/

**Comment by ghost** [comment]
I am a bit of semi professional @converge 😅 

Tried to install selenium again and after following Tim's guide I followed this: https://gist.github.com/curtismcmullan/7be1a8c1c841a9d8db2c 

But still same error..... Can you give the commands?

**Comment by converge** [comment]
@LoneWolfsMoon did you follow this steps ?

There another video tutorial about it, I'm using Debian on the video: https://www.youtube.com/watch?v=2Ci-hXU1IEY
