### ISSUE TITLE
Suspicious activity

### ISSUE THREAD

**Issue by bradfordev** [InstaPy/InstaPy#733]
Hello, 
I recently run into a problem after following some more people. Instagram now requires to fill a security code to login. I had a really hard time trying to figure out how to keep logeed in and eventually gave up. Is there a way to keep instagram in chrome selenium logged in or some other way round?
![security](https://user-images.githubusercontent.com/12089887/31354351-68c92b80-ad36-11e7-9b80-ec329e9f42e3.png)

**Comment by converge** [comment]
you just have to enter the secure code and try again.
