### ISSUE TITLE
IntaPy do unfollow without asking.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#734]
I susspect InstaPy doing unfollow to some of the users whom I am following.
I think the secnario is like this:
1. Getting list of users (one of the user in the list is someone I follow after)
2. Trying to do follow to this user.
3. instead of follow it doing unfollow since this is the same button.
Is this scenario possiable ?
It was not One time issue.
my start:
```python
session = InstaPy(username=insta_username, password=insta_password)
session.login()
session.set_upper_follower_count(limit=3500)
session.set_do_follow(enabled=True, percentage=80, times=1)
session.set_do_like(enabled=True, percentage=90)
session.like_by_tags(taglist, amount=70)
session.like_by_feed(amount=50)
session.end()
```

Thanks.

**Comment by timgrossmann** [comment]
@sionking Someone else also reported this I'm not sure how that should happen though since it checks the follow button if the text is "Follow" if not, it will not follow the person.

Someone has to investigate that a bit further.

**Comment by sionking** [comment]
We need to add our following to the ignore list, it may help .

**Comment by sionking** [comment]
I will update if I will get to it

**Comment by sionking** [comment]
I saw it happens ! if a user is already followed than it will unfollow.

**Comment by sionking** [comment]
Hi:
        follow_button = browser.find_element_by_xpath(
            "//*[contains(text(), 'Follow')]")

contains Follow in also "Following" maybe this is the reason ?

**Comment by sionking** [comment]
not really an selenium guy but I see this changes before and after following the user:
![image](https://user-images.githubusercontent.com/7851877/31838782-024ee566-b5e7-11e7-9dc4-e8fe3f7104f0.png)

**Comment by sionking** [comment]
here is a fix:
 follow_button = browser.find_element_by_xpath("//*[text()='Follow']")

But if a user is already followed - it will take time for proccessing it (xpath will over all xml)

**Comment by sionking** [comment]
Guys! I think it is super important ! don't you ?

**Comment by timgrossmann** [comment]
@sionking Feel free to post a bounty on this. This will increase the speed of resolution.

@converge Could you maybe look into this as well, please?

**Comment by converge** [comment]
@timgrossmann for sure, as soon as I have a free time

**Comment by timgrossmann** [comment]
@converge You're awesome!
Thank you very much!

**Comment by converge** [comment]
@timgrossmann @sionking your wish if my command :D

#824 (can someone test it ?)
