### ISSUE TITLE
Comment by Hashtag

### ISSUE THREAD

**Issue by JCADC** [InstaPy/InstaPy#737]
Hello there,

I'm trying to set comments by tag but I don't know how to do it or if I have to set like by hashtag and then it will grab the media and leave a comment.
<img width="605" alt="captura de pantalla 2017-10-10 a las 13 55 55" src="https://user-images.githubusercontent.com/21262014/31393653-87077ee8-addc-11e7-9a67-61cf9967d501.png">

How are you doing it, guys?

Thanks, 

J

**Comment by converge** [comment]
hey @JCADC , you just have to setup like this:
session.set_do_comment(enable=True, percentage=XX) # XX is the percentage of photo/video you want to comment
set_comments([...]) are random comments you set and you can add media param to only comment in photo or video.

best way to understand the use, is using.

**Comment by JCADC** [comment]
Hi @converge ,

I understand the point but the issue here is that I don't know where the comments are going to be posted.

My point is: I want to send comments to tags.
#Cat - Nice cat!

If I set comments percentage or media param I know it will send only to a % or only photo, only video but...what media? 

I don't know if it's clear now.

Thanks

**Comment by converge** [comment]
@JCADC got it, I don't use this function because I don't like random comments in photos. I think everyone here is using clarifai option to read image content, then comment.

Take a look at clarifai bot option.

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
