### ISSUE TITLE
🐋 Help with Docker Idea

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#739]
Hey there,

I'm searching for someone that is kind of skilled in using docker and knows how to run it on a Raspberry. Also, some container clustering (Docker Swarm) would be really helpful.

If you would describe yourself in a similar way, I would love to talk to you to discuss some maybe future ideas with InstaPy!

Thank you @all for being so awesome and helping keeping this tool alive!

**Comment by ingorichter** [comment]
Hey, @timgrossmann,
I have some experience with docker. I experimented with docker on my Raspberry Pi. I took on the next challenge and started using docker on an odroid c2. The results where okay, but the odroid lacked a modern 4.x kernel at that time (this summer). I had to put it aside for some other stuff, but it's still in the back of my mind to get docker running on it and especially InstaPy.

What are you looking for?

**Comment by timgrossmann** [comment]
@ingorichter Hey there.
Sorry for the late reply...

The idea was to get like 20 RaspberryPi's and combine them into a cluster. Then use docker swarm to spin up new containers containing the Setup for one account. That way there could be ~20 parallel sessions running at each given moment. When considering a timely distance of around 4h between every session, we could easily run 40 accounts simultaneously on that cluster of 20 Raspbis.

This could be really useful for people that don't know how to code and just want to enter their settings and done. This would of course cost a small fee/month, but if they want to maintain it themselves, they could still switch over to the completely free version here on GitHub and maintain it themselves. With the new GUI in place and maybe somewhere in the near future, automatic installation, people could easily choose if they want to handle it themselves or pay a small monthly fee to just let it run on their account with their given settings.

Does that make sense to you?

**Comment by ingorichter** [comment]
Hey @timgrossmann

Now I'm really late... Too much stuff happened in the past month. Anyway.

I find the idea very appealing and I believe that it would be a great learning experience to scale it up as you proposed.
What is the new GUI that you referring to? I haven't seen it yet and I'm really curious what it looks like.
I don't have that many Raspis lying around nor do I have space at the moment to run a cluster. I have a handful of them and I will experiment with them on the weekend.

**Comment by timgrossmann** [comment]
@ingorichter The first version of the GUI is this one https://github.com/ahmadudin/electron-instaPy-GUI

Sounds great! 
Looking forward to hearing about it. Thank you
