### ISSUE TITLE
Error which makes it stop

### ISSUE THREAD

**Issue by guncav** [InstaPy/InstaPy#746]
Hello, i'm having the following error. NOTE: Reason why i repeated my hashtags is because i also get the "Could not find the load button". So it doesn't load enough pictures to make it going forward for a few hours. Solution was multiplying hashtags. Maybe there is also another solution for this.

Error code:

Traceback (most recent call last):
  File "quickstart.py", line 23, in <module>
    session.like_by_tags(['ootd', 'amsterdam', 'suitsupply', 'instagood', 'fashion', 'mensfashion', 'boys', 'fashion', 'travel', 'nederland', 'amsterdam', 'ootd', 'amsterdam', 'suitsupply', 'instagood', 'fashion', 'mensfashion', 'boys', 'fashion', 'travel', 'nederland', 'amsterdam', 'ootd', 'amsterdam', 'suitsupply', 'instagood', 'fashion', 'mensfashion', 'boys', 'fashion', 'travel', 'nederland', 'amsterdam', 'ootd', 'amsterdam', 'suitsupply', 'instagood', 'fashion', 'mensfashion', 'boys', 'fashion', 'travel', 'nederland', 'amsterdam', 'ootd', 'amsterdam', 'suitsupply', 'instagood', 'fashion', 'mensfashion', 'boys', 'fashion', 'travel', 'nederland', 'amsterdam', 'ootd', 'amsterdam', 'suitsupply', 'instagood', 'fashion', 'mensfashion', 'boys', 'fashion', 'travel', 'nederland', 'amsterdam', 'ootd', 'amsterdam', 'suitsupply', 'instagood', 'fashion', 'mensfashion', 'boys', 'fashion', 'travel', 'nederland', 'amsterdam', 'ootd', 'amsterdam', 'suitsupply', 'instagood', 'fashion', 'mensfashion', 'boys', 'fashion', 'travel', 'nederland', 'amsterdam', 'ootd', 'amsterdam', 'suitsupply', 'instagood', 'fashion', 'mensfashion', 'boys', 'fashion', 'travel', 'nederland', 'amsterdam', 'ootd', 'amsterdam', 'suitsupply', 'instagood', 'fashion', 'mensfashion', 'boys', 'fashion', 'travel', 'nederland', 'amsterdam', 'ootd', 'amsterdam', 'suitsupply', 'instagood', 'fashion', 'mensfashion', 'boys', 'fashion', 'travel', 'nederland', 'amsterdam', 'ootd', 'amsterdam', 'suitsupply', 'instagood', 'fashion', 'mensfashion', 'boys', 'fashion', 'travel', 'nederland', 'amsterdam'], amount=300)
  File "/Users/Hamdi/InstaPy/instapy/instapy.py", line 530, in like_by_tags
    followed += follow_user(self.browser, self.follow_restrict, self.username, user_name)
  File "/Users/Hamdi/InstaPy/instapy/unfollow_util.py", line 175, in follow_user
    follow_button.click()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.6 x86_64)

**Comment by s6s8** [comment]
Hi,
Did you try doing this? #700

**Comment by gerdmueller2** [comment]
(off topic-question to your session.like_by_tags): you have a lot of tags and each with an amount of 300? 😮 
i thought 1000 actions per day (likes/comments etc) is an limit to get not banned/blocked?
am i wrong?!

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
