### ISSUE TITLE
Keep getting  "Image not liked: Inappropriate"

### ISSUE THREAD

**Issue by uni1783** [InstaPy/InstaPy#747]
I'm using the following (example) config and I keep getting Inappropriate for every image.
Even if I use a single like_by_tags setting I get the same problem.
Am I missing something or is there a conflicting setting?
```
from instapy import InstaPy

session = InstaPy(username='username', password='password', nogui=True)
session.login()
session.set_sleep_reduce(95)
session.set_lower_follower_count(limit=40)
session.set_do_follow(enabled=True, percentage=14, times=2)
session.set_user_interact(amount=16, random=True, percentage=32, media='Photo')
session.set_dont_include(['user1', 'user2', 'user4'])
session.set_ignore_users(['user3', 'user5', 'user6'])
session.set_dont_like('#vegetables')
session.like_by_tags(['pork'], amount=8)
session.like_by_tags(['bbq'], amount=7)
session.end()
```

**Comment by bradfordev** [comment]
try this:
from instapy import InstaPy

```python
session = InstaPy(username='username', password='password', nogui=True)
session.login()
session.like_by_tags(['vegan', 'glutenfree'], amount=15)
session.end()
```

should be working fine.

**Comment by uni1783** [comment]
That works, but still marks a few posts as Inappropriate.
If I add session.set_dont_like('novegan') all of the posts are marked as Inappropriate.

**Comment by converge** [comment]
@uni1783 @bradfordev the problem is **set_dont_like** method uses a list as parameter, when you do:
```session.set_dont_like('vegan')```
the bot don't understand the word **vegan** and check every word in this way:
v
e
g
a
n
if the post text contain **v** or **e** or **g** (and so son), it will mark as inappropriate.

```session.set_dont_like('vegan')```
is the same as
```session.set_dont_like(['v', 'e', 'g', 'a', 'n'])```

**Comment by uni1783** [comment]
@converge That was it! Thank you :)
