### ISSUE TITLE
Re : Debian issue 

### ISSUE THREAD

**Issue by LoneWolfsMoon** [InstaPy/InstaPy#748]
![screenshot from 2017-10-12 19-04-08](https://user-images.githubusercontent.com/30674228/31509011-3699ca9c-af80-11e7-9474-b9f559bf3d3a.png)

I Reinstalled the BOT and 'installed' UNIX.SH
![screenshot from 2017-10-12 19-05-16](https://user-images.githubusercontent.com/30674228/31509041-4fa0736a-af80-11e7-83cc-1f6d13a55cbc.png)

**Comment by LoneWolfsMoon** [comment]
I think I have to ADD CHROME TO PATH ........ I don't know how to do it on Debian , please help me with some example code ..

**Comment by dbrkv** [comment]
as a workaround you can try to do following:

```sh
wget -N https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
unzip chromedriver_linux64.zip
rm chromedriver_linux64.zip
sudo mv -f chromedriver /usr/local/bin/chromedriver
```
Then in `InstaPy#set_selenium_local_session` change:
```python
self.browser = webdriver.Chrome(chromedriver_location, chrome_options=chrome_options)
```
into
```python
self.browser = webdriver.Chrome(chrome_options=chrome_options)
```

**Comment by LoneWolfsMoon** [comment]
HOLLY FUCKKKKKK AAAAAAAAAAAAAAAAAAAAA

**Comment by LoneWolfsMoon** [comment]
<3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3
