### ISSUE TITLE
Newbie error name 'session' is not defined"

### ISSUE THREAD

**Issue by cbyrt** [InstaPy/InstaPy#752]
Hi Everyone
Thank you for the fantastic work. 
Im very new to the code and after a day I managed to get this almost working. I have searched for answers but I can not figured out.
Im getting this error

"Traceback (most recent call last):
  File "quickstart.py", line 9, in <module>
    session.login()
NameError: name 'session' is not defined"

Can anyone give a hand in solving this please. Much appreciated

**Comment by converge** [comment]
@cbyrt maybe you forgot to add this line:

```session = InstaPy(username=insta_username, password=insta_password)```

check your config with this file https://github.com/timgrossmann/InstaPy/blob/master/quickstart.py

**Comment by cbyrt** [comment]
Thanks! got it working
