### ISSUE TITLE
Deploying on heroku

### ISSUE THREAD

**Issue by mwamedacen** [InstaPy/InstaPy#758]
Hi,

Actually this is not an issue, I just don't know where to start. Did someone manage to make it work ? If so, can you provide few key steps please.

Thank you very much

**Comment by converge** [comment]
@Acen1991 https://www.youtube.com/watch?v=I025CEBJCvQ

**Comment by mwamedacen** [comment]
Thank you for your answer though you are not explaining in your video how to deploy the script on Heroku but only general things related with the usage of the library. My question is really related with deployment issues like setuping a selenium server and let the script communicate with it.

**Comment by converge** [comment]
sorry, I had no idea what heroku is

**Comment by RafaelLee** [comment]
Still?
No one knows how to do that?
 :/

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.

**Comment by giovanniciriello** [comment]
Did someone success running instaPy on Heroku?

**Comment by mkMcMahon** [comment]
i feel like all the people running it on heroku are probably making $$ off it. anyone else agree? 

more reason to figure out how we can get it running ourselves..

**Comment by GeoffreyPlitt** [comment]
+1

**Comment by guivinicius** [comment]
I'm not sure you can run this on Heroku as it is. Since InstaPy uses sqlite as database.

Sure you can use sqlite on heroku but it wont persist the data for more than 24h.

I recommend using on amazon EC2 machine or something.

**Comment by itsbrex** [comment]
Interesting about the SQLite data not persisting for more than 24h. More of a hacker here so don’t know much about all the inner workings...will have to research the EC2 machine idea. A one and done solution like the ‘Deploy to  Heroku’ buttons I’ve seen would be great. Of course that just means someone has to do it lol. Is there such a thing as ‘Deploy to EC2’ button for the less tech savvy of us??

**Comment by SirDank** [comment]
https://github.com/ishalyminov/instapy-docker-heroku
https://stackoverflow.com/questions/54000395/python-running-instapy-on-heroku
