### ISSUE TITLE
InstaPy video how to

### ISSUE THREAD

**Issue by converge** [InstaPy/InstaPy#759]
Just uploaded it, what do you guys think ? Should we add it do the docs ?
https://www.youtube.com/watch?v=I025CEBJCvQ

**Comment by timgrossmann** [comment]
@converge Awesome, thank you!
This definitely is a good start.

What would be best though is to have separate set up videos for the different platforms describing the process including installing python (which is especially important for windows).

Thank you very much for this!

**Comment by cbyrt** [comment]
Fantastic! Thank you

**Comment by Louisartmaker** [comment]
@converge Thank you for your help. But we need to install ¨selenium¨and ¨pyvirtualdisplay¨ to run Quickstart.py, no ?

**Comment by cbyrt** [comment]
@timgrossmann thank you for sharing this amazing code.

**Comment by timgrossmann** [comment]
@converge I'll add the tutorial to the Readme and close this issue.
