### ISSUE TITLE
Following a new user is not working (for me)

### ISSUE THREAD

**Issue by rafo** [InstaPy/InstaPy#76]
I dont know why, but for me following new users is not working.

I tried:

` .set_do_follow(True, percentage=25, times=1) \`

and

` .set_do_follow(enabled=True, percentage=25, times=1) \`

**Comment by rafo** [comment]
Thats all i get:
`Liked: 58
Already Liked: 2
Inappropriate: 33
Commented: 19
Followed: 0`

**Comment by timgrossmann** [comment]
@rafo That's really weird...
Do you maybe already follow all the people from given run?

**Comment by rafo** [comment]
No. I tried it several times… with different tags.

**Comment by rafo** [comment]
```
from instapy import InstaPy

#Write your automation here
#Stuck ? Look at the github page or the examples in the examples folder

dont_like = ['food', 'girl', 'hot']
ignore_words = ['pizza']
friend_list = ['friend1', 'friend2', 'friend3']

InstaPy(username=‚xxx', password=‚xxx')\
  .login()\
  .set_do_comment(True, percentage=25) \
  .set_comments(['Thats very cool!', 'I like your POV!', 'Nice.!']) \
  .set_dont_include(friend_list) \
  .set_dont_like(dont_like) \
  .set_ignore_if_contains(ignore_words) \
  .like_by_tags(['minimal'], amount=100) \
  .set_do_follow(True, percentage=25, times=1) \
  .end()
```

**Comment by timgrossmann** [comment]
@rafo like_by_tag always has to be the last command, like in the examples.
If you set it after you already ran it, it won't work.

Change to: 
```python
.set_do_follow(True, percentage=25, times=1) \
.like_by_tags(['minimal'], amount=100) \
```

Will work 😉
