### ISSUE TITLE
Check number of following xpath is incorrect when no following

### ISSUE THREAD

**Issue by pleum** [InstaPy/InstaPy#761]
i found this `//li[3]/a/span` and it for a html tag when no following it turn to span tag and selenium give me exception 
`selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//li[3]/a/span"}` 

should it change to `//li[3]/child::node()/span` ??

**Comment by converge** [comment]
@pleum what is your script setup and when is it occurring ?

**Comment by pleum** [comment]
`session.unfollow_users(amount=1)` use this when you didn't follow anyone it should raise `RuntimeWarning('There are 0 people to unfollow')` right ?

**Comment by converge** [comment]
it happens when you have 0 "following" or when you try to interact with private accounts. there is a pull request to manage it #749 , just need some time to merge it.
