### ISSUE TITLE
insta py Not Commenting

### ISSUE THREAD

**Issue by jpamintuan** [InstaPy/InstaPy#762]
Can you please tell me why the commenting feature does not work?
All it does is login, go to my home page, then exit?? Which post would it comment to? sorry I know this is very easy but im new to instapy.

from instapy import InstaPy

insta_username = 'uname'
insta_password = 'pass'

session = InstaPy(username=insta_username, password=insta_password)
session.login()

#default enabled=False, ~ every 4th image will be commented on
session.set_do_comment(enabled=True, percentage=25)
session.set_comments(['Awesome', 'Really Cool', 'I like your stuff'])

session.end()

**Comment by converge** [comment]
@jpamintuan you configured the "how to" actions, you still need to do the action, try this:
```session.like_by_tags(['fashion'], amount=2)```

**Comment by jpamintuan** [comment]
from instapy import InstaPy

insta_username = 'uname'
insta_password = 'pass'

session = InstaPy(username=insta_username, password=insta_password)
session.login()

#default enabled=False, ~ every 4th image will be commented on
session.set_do_comment(enabled=True, percentage=25)
session.set_comments(['Awesome', 'Really Cool', 'I like your stuff'])

session.like_by_tags(['fashion'], amount=2)
session.end()


Like this??? Thanks man.. BTW I watched your video and it is very helpful thank you!

**Comment by maramiro0** [comment]
@jpamintuan did you get it resolved? I am having the same issue.

**Comment by riccardorighettiphoto** [comment]
totally unable to comment here.
