### ISSUE TITLE
InstaPy no longer working

### ISSUE THREAD

**Issue by samducker** [InstaPy/InstaPy#763]
Hey, 

So my InstaPy has been working as intended for a number of weeks and now the script is still running on my server as intended. But images aren't actually getting liked and commented on anymore.

I'll get output like the following (shortened description and hastags for issue post)

    [11/120]
    Image from: b'lexsped'
    Number of Followers: 263
    Link: b'https://www.instagram.com/p/BaRIpRPgMeE/?tagged=cyclist'
    Description: b'Up at 5.30am & out by 6. Foggy start but turned out to be a beautiful morning & a good 77km ride! '
    --> Image Liked!
    --> Not commented
    --> Not following

Yet I'll look in my images liked on my Instagram account and it won't have worked. The only thing I can think is Instagram is blocking the IP of my server?

heres my quickstart.py without the sensitive info

    from instapy import InstaPy

    insta_username = 'xxx'
    insta_password = 'xxx'

    # if you want to run this script on a server,
    # simply add nogui=True to the InstaPy() constructor

    InstaPy(username=insta_username, password=insta_password, nogui=True)\
      .login()\
      .set_upper_follower_count(limit=2500)\
      .set_do_comment(True, percentage=10)\
      .set_comments(['Awesome'])\
      .like_by_tags(['Cyclist', 'cyclingjersey', 'cyclingfashion', 'fashionforward', 'fixedgear', 'kithunters', 'kitfit', 'cycling', 'fixie', 'crit', 'bikelife'], amount=120)\
      .end()

**Comment by samducker** [comment]
Quick update, I've managed to get it working on my Mac with the gui enabled. But still struggling to get it working on a digital ocean droplet. This is the ideal as I want to run two different bots simultaneously on both my accounts and set it to run automatically with a cron job.

**Comment by elenachoi** [comment]
Same here, not working from DO

**Comment by converge** [comment]
run the bot in DO is not a good option because you will access your IG account from very different ip address in a short time.

an alternative is to setup the bot in your own server.

**Comment by diveu** [comment]
I guess you've faced a "soft ban", which means that you still can push the like button, but nobody will see it.
Instagram can probably see DO servers, because I changed my droplets several times and to several locations. So, the best option for you would be either to run the bot on your PC/Mac, or to run it on your server.
I do it on my own machine, since it's not too resourse dependent. And I plan to move to Raspberry Pi in near future :)

**Comment by converge** [comment]
@samducker some news about it ?

**Comment by samducker** [comment]
Hey, the soft ban was faced on Digital Ocean. I switched my provider, to a different cloud service provider and it's started working a treat again! Try linode or ovh if you are having problems.

@timgrossmann would you recommend running each InstaPy script/account with a unique IP or do you think that it would be ok to run a couple of accounts on the same IP?

**Comment by timgrossmann** [comment]
@samducker To be honest, I never had problem running different accounts from the same IP...

As long as you don't overdue it it should be fine. Please don't run 10 accounts from the same IP

**Comment by wizarduk** [comment]
@timgrossmann how many to be on the safe side with one dedicated ip ?

**Comment by RomeoJuliett** [comment]
@wizarduk

I've run 4 at a time on my local machine and experienced no issues
