### ISSUE TITLE
Feature: don't unfollow active users

### ISSUE THREAD

**Issue by converge** [InstaPy/InstaPy#766]
What do you guys think about this feature ?

**feature**

- users that liked the last 4 posts are saved in a list (active_users)
- when bot runs, it update the (active_users) list, and add the active_users to friends list (set_dont_include option)
- when unfollow is called, it wont unfollow friends list

**updating the list:**

- add users: users that liked at least one of the latest 4 posts
- remove users: users that didn't liked at least one of the latest 4 posts

**Comment by pilotdude** [comment]
I like the idea. It would be cool if you could also adjust the number of posts. I could imagine having an account where posting is more frequent and looking back just 4 posts isn't enough.

**Comment by converge** [comment]
It's almost ready. I need some help in line 21/22 at util.py
https://github.com/converge/InstaPy/commit/50e65e147ceae2a00f877e63dff5a3059153bbae

**Comment by converge** [comment]
#781 PR
