### ISSUE TITLE
Feature request: set_lower/upper_postlike_count

### ISSUE THREAD

**Issue by uni1783** [InstaPy/InstaPy#770]
Would it be possible to add this setting so a post must have at least x other likes before interacting with it? 

session.set_lower_postlike_count ( limit = 5 ) # Don't interact with post with less than 5 likes
session.set_upper_postlike_count ( limit = 6000 ) # Don't interact with post with more than 6000 likes

**Comment by mamartins** [comment]
I also think this is an useful one!

**Comment by converge** [comment]
that's a good idea. we can have better results liking in this way.
