### ISSUE TITLE
Incognito Mode 

### ISSUE THREAD

**Issue by AustineA** [InstaPy/InstaPy#771]
how do run instapy in incognito mode?

**Comment by amtheguy** [comment]
Solved this here's what i did 
go to _instapy/instapy.py_
under line 120 paste the following...
`chrome_options.add_argument("--incognito")`

I wanted to login multiply instagram account simultaneously using virtualenv and incognito mode.

**Comment by AustineA** [comment]
Solved this here's what i did 
go to _instapy/instapy.py_
under line 120 paste the following...
`chrome_options.add_argument("--incognito")`

I wanted to login multiply instagram account simultaneously using virtualenv and incognito mode.

**Comment by timgrossmann** [comment]
@amtheguy How about a PR that introduces that feature as an addable parameter? :wink:

**Comment by converge** [comment]
@amtheguy just curious, why do you use incognito mode ?

**Comment by AustineA** [comment]
@converge To login multiply instagram accounts simultaneously

**Comment by AustineA** [comment]
@timgrossmann Sure that would be awesome. I'm new to python though i'll take that as a challenge.

**Comment by AustineA** [comment]
@timgrossmann done 😎

**Comment by converge** [comment]
@amtheguy I saw you closed your PR for this feature, do you need some help ?

**Comment by AustineA** [comment]
@converge No not at all i was able to implement it. I, saw people are asking why incognito if chrome creates a new profile every time it runs. So i decided to close it and just use it locally.

**Comment by hestuppfodarn** [comment]
is it necessary to use incognito to run multiple accounts at the same time?
I have been running 2, simultaneously without any issues. Could you please tell me why i should which to incognito?

**Comment by AustineA** [comment]
@hestuppfodarn it's just my personal preference I'm not sure if there's any benefit to using incognito over the default.

**Comment by converge** [comment]
as this article[1] shows, incognito mode is nothing more than a way to browser without local history (cache and page history).

[1] https://www.computerhope.com/jargon/i/incognito.htm

**Comment by AustineA** [comment]
Yeah but people are saying the default does the same thing. I didn't know that at the time which is why i wanted incognito mode, i closed the PR in other to avoid duplicate feature. But i still use incognito in my code.
