### ISSUE TITLE
follow_user_following stops after a page/user not found

### ISSUE THREAD

**Issue by uni1783** [InstaPy/InstaPy#774]
I mistyped the first username and it had the effect that InstaPy wouldn't run with the follow_user_following setting. I suspect this is also the case with interact_user_followers.

```
from instapy import InstaPy

session = InstaPy(username=‘username’, password=‘password’, nogui=True)
session.login()
session.follow_user_following([‘non-existent-username’, ‘user2’, ‘user3’,’user4’], amount=12, random=True, sleep_delay=42, interact=True)
#session.interact_user_followers([‘non-existent-username’, ‘user2’, ‘user3’], amount=12, random=True)
session.end()
```

Output
```
Logged in successfully!
Warning: There are 0 people to follow , stopping follow_users
```

**Comment by converge** [comment]
Last change/commit about it made the bot stop crashing when find this kind of situation. Now it goes to the next action without crashing.

Next step could be skip the problematic user, and keep going.

**Comment by 0x00secJinx** [comment]
I could work on this. Instead of calling the for loop inside the try/except statement, the try/except could be inside the for loop. If a runtime exception is caught, just use the continue keyword to go to the next user in the list.
