### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by brazdash** [InstaPy/InstaPy#776]
Anyone with a comprehensive guide for OSMC (debian)? I followed the Rpi instructions but it's missing almost everything..... (I can't even understand what's the main script file that need to be launched) Really need a noob guide to make it work

**Comment by pilotdude** [comment]
I was having the same issue a couple of days ago when I tried to get this script running on my Pi. I was struggling and had to give up because I ran out of time to fiddle with it. Any help would be appreciated.

**Comment by converge** [comment]
It's a fast and basic tutorial, but maybe it can help you guys. #759

**Comment by brazdash** [comment]
Thanks I'll check It out

**Comment by converge** [comment]
closing, as there is no interaction for a long time. reopen it if you need
