### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by thisishotdog** [InstaPy/InstaPy#777]
Hi, none of the images are loading when I execute the script, despite the fact that it is liking and commenting as expected. Even images on the login page are not loading.

I'm using the pi with latest Firefox ESR. Has anyone else experienced this problem?

**Comment by converge** [comment]
#630

**Comment by thisishotdog** [comment]
Thanks, tried searching and didn't know it was a known issue #630 . 

I'll leave this open for now, searching for images not showing doesn't yield results. I'll comment here when the issue is resolved and close the ticket.

**Comment by converge** [comment]
@thisishotdog just found it in the code:
```
# permissions.default.image = 2: Disable images load,
# this setting can improve pageload & save bandwidth
firefox_profile.set_preference('permissions.default.image', 2)
````
you can change it in instapy/instapy.py line 123 (+/-)

I think we should keep this setup like this to save bandwidth. Please, reopen the issue if you need.
