### ISSUE TITLE
follow_user_followers not respecting Amount neither set_user_interact

### ISSUE THREAD

**Issue by mamartins** [InstaPy/InstaPy#779]
I have this configuration:
```
bot.set_lower_follower_count(limit = 10)
bot.set_upper_follower_count(limit = 2550)
bot.set_do_comment(enabled=True, percentage=40)
bot.set_user_interact(amount=6, random=False, percentage=100, media='Photo')

bot.follow_user_followers(['instagood'], amount=30, random=True, interact=True, sleep_delay=120)
```

The script was already following the 50th user, so it did not respected the 30 amount and did not entered any user to like its last 6 pictures.

**Comment by flo1t** [comment]
the "problem" is line 270-272 in unfollow_util.py:
```
if is_random:
        # expanding the popultaion for better sampling distribution
        amount = amount * 3
```

when you set random=True in follow_user_followers it'll triple the set amount. so either you divide your wanted amount through 3 or you set random=False.

**Comment by mamartins** [comment]
Hum, I guess that this should be stated under documentation, no?

Also, the bot will only interact with users after all the following is done? Because it did not enter any profile to interact while I was running it

**Comment by converge** [comment]
@flo1t thanks, just submitted a PR. @mamartins

**Comment by mamartins** [comment]
great!

anyone knows the answer to this question, the bot will only interact with users after all the following is done?

**Comment by timgrossmann** [comment]
@mamartins I'm really sorry for the confusion here... 
There are two features, `follow_user_followers` and `interact_user_followers`... They should both be combined, but somehow they turn ended up being two different methods.

Both first go through the followers of the account given. 
The `follow_user...` will follow given amount of accounts right there before going in and interacting with given amount of the followed.
The `interact_user...` however will only get the given amount of accounts and then start to interact with each of the selected ones, liking their pictures, maybe commenting and maybe following the account. 
 
Hope that clears things up a little. The idea was to have a method that in general does nothing, no like, no comment and no follow.
Then you could simply set up all the interaction with `set_do_like`, `set_do_comment` and `set_do_follow` to make it as customizable as possible...

This still has to be finished...

**Comment by converge** [comment]
@mamartins thank you for your bug report, we just merged a fix, can you test it ? if you find some problem, please, reopen it!

**Comment by mamartins** [comment]
I'll test it. 
Thanks guys!
