### ISSUE TITLE
My PC can't run Windows.ps1.

### ISSUE THREAD

**Issue by VKT16** [InstaPy/InstaPy#783]
I have completed steps 0 to 2, and I am now stuck on step 3. Whenever I try to run the script Windows.ps1, the command line pops up but immediately closes so it does not install anything.

Can someone help please.

P.s. I captured the command line using the print screen key and it says that the **syntax is invalid**.
I also cannot install .Net Framework V3.5 because I have .Net Framework 4.6.1 installed.

**Comment by converge** [comment]
@VKT16 pls show us the command line output.

**Comment by VKT16** [comment]
@converge 
The command line was outputting the following: 

File "C:\Users\MY_USER_NAME\Documents\GitHub\InstaPy\scripts\windows.ps1", Line 1 echo "InstaPy Windows Setup"

SyntaxError: invalid syntax

**I think the above error happened because I did not run the windows.ps1 file as administrator because I do not have such an option when I right click.** 

I then however did my own research, and found a command to execute the windows.ps1 file as administrator from the command line. Running this command installed some of the things but not all of them. I used the following command: 

Powershell.exe -executionpolicy bypass -file "C:\Users\MY_USER_NAME\Documents\GitHub\InstaPy\scripts\windows.ps1"

**I have attached a cmd Log in this post for you to see what has been installed and what not when I executed the above command,**

Any help will be much appreciated.

Thank you.
[cmd Log.txt](https://github.com/timgrossmann/InstaPy/files/1399768/cmd.Log.txt)

**P.S. Running Windows 7**




## **Updated:**

Okay, I carefully read the windows.ps1 script, and found out that the command "py get-pip.py" is the  one that is causing the first problem. The reason I believe this is because there isn't such a file that is named "get-pip.py" anywhere on my system.

**Comment by VKT16** [comment]
**Someone Please Help :(**

**Comment by thedot80** [comment]
Today, I installed the complete App on the AWS Server. The installation went smoothly. My problem was it didnt like the posts and some other few things correclty. I believe the code needs an update, as there have been few changes in Instagram code as well.

For you - you better delete this system and create a new one (Sound to me you work in a cloud as well), if not - just deinstall and reinstall python and if you are the server admin (just guessing because of power shell) you are supposed to be an admin anyway. So just right click the windows file and run it in powershell.

**Comment by converge** [comment]
@VKT16 when you run
```
python quickstart.py
```
what´s your output ?

**Comment by VKT16** [comment]
@converge  
**This is the output:**

`C:\Users\MY_USER_NAME\Documents\GitHub\InstaPy>python quickstart.py`

Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\MY_USER_NAME\Documents\GitHub\InstaPy\instapy\__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "C:\Users\MY_USER_NAME\Documents\GitHub\InstaPy\instapy\instapy.py", line 14, in <module>
    from .clarifai_util import check_image
  File "C:\Users\MY_USER_NAME\Documents\GitHub\InstaPy\instapy\clarifai_util.py", line 3, in <module>
    from clarifai.rest import ClarifaiApp, Image as ClImage
ModuleNotFoundError: No module named 'clarifai'

C:\Users\MY_USER_NAME\Documents\GitHub\InstaPy>




@thedot80 I am not on a cloud, I am running in on a PC. And i already reinstalled everything more than 3-4 times.

**Comment by converge** [comment]
@VKT16 python 3.6 ?
```
pip3.6 install clarifai
```
and try again

**Comment by VKT16** [comment]
@converge Still same error. I have attached the logs for you.
[pip3.6 install clarifai & python quickstart.txt](https://github.com/timgrossmann/InstaPy/files/1404333/pip3.6.install.clarifai.python.quickstart.txt)

**Comment by converge** [comment]
@VKT16 
1)Install the C++ compiler http://landinghub.visualstudio.com/visual-cpp-build-tools
2) Go to the installtion folder (In my case it is): C:\Program Files (x86)\Microsoft Visual C++ Build Tools
3)Open Visual C++ 2015 x86 x64 Cross Build Tools Command Prompt

from: https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed

I googled it "clarifai install error: command 'cl.exe' failed: No such file or directory"

If you want, I'm at #instapy (irc freenode)

**Comment by VKT16** [comment]
What should I do when I open Visual C++ 2015 x86 x64 Cross Build Tools Command Prompt?

And what do you mean by _"If you want, I'm at #instapy (irc freenode)"_

**Comment by VKT16** [comment]
Issue solved. Thank you, I appreciated your help.

**Comment by converge** [comment]
*Windows install doc updated
