### ISSUE TITLE
The username you entered doesn't belong to an account. Please check your username and try again

### ISSUE THREAD

**Issue by ellismarte** [InstaPy/InstaPy#784]
I've been running the program for a while and everything was fine, all of a sudden i'm getting this error on the attempt to log in: "The username you entered doesn't belong to an account. Please check your username and try again"

The login info is correct, I can log in from my phone. Anyone know what's going on??

**Comment by converge** [comment]
@ellismarte take a look https://www.quora.com/Why-does-it-say-the-username-you-entered-doesnt-belong-to-an-account-when-we-temporarily-disable-the-account

sounds like an account problem, if there is something we can do, tell us.

**Comment by converge** [comment]
@ellismarte some news about it ?

**Comment by sionking** [comment]
Happened to me 2 :(  I am able to log from mobile but not from laptop

**Comment by sionking** [comment]
It might be an instagram bug, anyway to solve it log in using your email instaed of username.
than change the password.
I am still not able to log using username only mail, hope it nothing to do with botting

**Comment by imv7** [comment]
changed my user, didn't work. changed password, didn't work. login over facebook works.

**Comment by imv7** [comment]
changed insta's mail equal to facebook, didn't work

**Comment by imv7** [comment]
it looks to be a protection from insta

**Comment by imv7** [comment]
would resolve if Instapy allows login over facebook

**Comment by luigifaticoso** [comment]
Happened to me to right now, did your account got re activated?

**Comment by Jenuan** [comment]
Just happened to me 2... any one could solve it ?

**Comment by josefhelie** [comment]
Check if you use a VPN/proxy whatever.

**Comment by flajer** [comment]
Had the same problem, it worked well on my phone but kept giving me the error on my computer. @mojoego saves the day. I only had to disable VPN.

**Comment by mkhattar** [comment]
any other solutions to this issue?

**Comment by AshuOPragmatikosThrylos** [comment]
> any other solutions to this issue?

try logging in with email...worked for me.
