### ISSUE TITLE
Interact with Followed Users doesn't work for me.

### ISSUE THREAD

**Issue by Marichka310** [InstaPy/InstaPy#787]
Amount = 40
Percentage =20
random = True

And I get logs like `Session started - 2017-10-19 12:10:01

Logged in successfully!

Session ended - 2017-10-19 12:10:09`

I have 745 followed users, so it should work. Need help!

**Comment by converge** [comment]
@Marichka310 what's your full setup ? remember to use some feature to like posts before call interact feature.
