### ISSUE TITLE
Docker issue: port 5900 already allocated

### ISSUE THREAD

**Issue by mbancha** [InstaPy/InstaPy#789]
Is there some way to use a different port or something? I used the build command per the instructions for setting up Docker and it told me that port 5900 had already been allocated. When I try to run it (build docker-compose up -d --build) again it says the same:

> ERROR: for selenium  Cannot start service selenium: driver failed programming external connectivity on endpoint selenium (7a9944b76f2fcbe0ca17f547a6204bfec6098e7580e0027c70614c297a296b5b): Error starting userland proxy: Bind for 0.0.0.0:5900 failed: port is already allocated

**Comment by rotohun** [comment]
What is using the port? 

use this to see.

ps aux | grep 5900

**Comment by mbancha** [comment]
Ah I figured it out, I was running a VPN, whoops!
