### ISSUE TITLE
Scrolling top user followers bottom stops after a while.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#790]
I reached 465 users by InstaPy while doing it manually I could have reach all of them.
Do Instagram detect a scrolling bot ?

Why is that ?

**Comment by converge** [comment]
@sionking if you slow down the scrolling, you can see all of them, but it takes too much time, like hours.

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
