### ISSUE TITLE
'dpkg -i google-chrome-stable_current_amd64.deb' doesn't work with latest chrome

### ISSUE THREAD

**Issue by eracle** [InstaPy/InstaPy#792]
While building with:

docker build -t instapy ./docker_conf/all_in_one

I got this:

 47300K .......... .......... .......... .......... .......... 99% 1.15M 0s
 47350K .......... ...                                        100% 6.56M=9m6s

2017-10-21 16:50:50 (86.7 KB/s) - 'google-chrome-stable_current_amd64.deb' saved [48500124/48500124]

Selecting previously unselected package google-chrome-stable.
(Reading database ... 35604 files and directories currently installed.)
Preparing to unpack google-chrome-stable_current_amd64.deb ...
Unpacking google-chrome-stable (62.0.3202.62-1) ...
dpkg: dependency problems prevent configuration of google-chrome-stable:
 google-chrome-stable depends on lsb-release; however:
  Package lsb-release is not installed.

dpkg: error processing package google-chrome-stable (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 google-chrome-stable
The command '/bin/sh -c cd ~     && wget ${CHROME}     && dpkg -i google-chrome-stable_current_amd64.deb     && apt-get install -y -f     && rm google-chrome-stable_current_amd64.deb' returned a non-zero code: 1

**Comment by eracle** [comment]
By git blaming the source code:
git blame ./docker_conf/all_in_one/Dockerfile

I got this also this line:
570f4503 Dockerfile (timgrossmann   2017-04-11 23:23:10 +0200 56)     && dpkg -i google-chrome-stable_current_amd64.deb \


That means by using chrome build on 2017-04-11 it should work.

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
