### ISSUE TITLE
Setting up on Droplet / Unbutu 

### ISSUE THREAD

**Issue by brookton** [InstaPy/InstaPy#794]
Hey Tim.

I'm kind of new to all of this but really appreciate your code. It's the best of the best.
I'm hoping someone can help me solve this riddle though.

I'm trying to run this script on a Droplet through Digital Ocean with Unbutu from the article that you provided, which is really helpful: https://medium.com/@hoppy/how-to-test-or-scrape-javascript-rendered-websites-with-python-selenium-a-beginner-step-by-c137892216aa

I know this is really specific to my configuration but I'm trying to use these commands to get the script running:

cd InstaPy
python3 quickstart.py

These are the error messages I can't seem to resolve.
I'm not sure if I put the nogui=True in the right place?

Could someone plz plz plz help me make sense of these?

  File "quickstart.py", line 6, in <module>
    session = InstaPy(nogui=True)
  File "/root/InstaPy/instapy/instapy.py", line 48, in __init__
    self.display = Display(visible=0, size=(800, 600))
  File "/root/InstaPy/pyvirtualdisplay/display.py", line 38, in __init__
    **kwargs)
  File "/root/InstaPy/pyvirtualdisplay/xvfb.py", line 33, in __init__
    AbstractDisplay.__init__(self)
  File "/root/InstaPy/pyvirtualdisplay/abstractdisplay.py", line 33, in __init__
    self.display = self.search_for_display()
  File "/root/InstaPy/pyvirtualdisplay/abstractdisplay.py", line 68, in search_for_display
    if len(ls):
TypeError: object of type 'map' has no len()

**Comment by brookton** [comment]
I'm going to try to install the git straight from your link to override the one I made on my account to see if it resolves it. I ended up creating pyvirtualdisplay in the InstaPy directory to see if it would help, I was getting pyvirtualdisplay and Easy Process error messages before so I ran 

cp /usr/local/lib/python3.5/dist-packages/PyVirtualDisplay-0.2.1-py3.5.egg /InstaPy 
cp /usr/local/lib/python3.5/dist-packages/EasyProcess-0.2.3-py3.5.egg /InstaPy
mv /InstaPy/EasyProcess-0.2.3-py3.5.egg /InstaPy/pyvirtualdisplay                                               
mv /InstaPy/PyVirtualDisplay-0.2.1-py3.5.egg /InstaPy/pyvirtualdisplay

Everything is being run at ~ root level, not sure if that makes a difference.
I'm really new to all of this I just learned how to do it  so it's been a huge learning curve and anyone's help on this would be extremely appreciated.

**Comment by converge** [comment]
@brookton take a look
https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md

**Comment by brookton** [comment]
Thank you for your reply. I'm just going to rename my current /InstaPy directory and start over with those steps again. I think I missed some of those.

**Comment by brookton** [comment]
That totally solved my issue! I was being super extra when I should have just kept it simple. Thank you @converge !!!!
