### ISSUE TITLE
Unfollow not working

### ISSUE THREAD

**Issue by avanjool** [InstaPy/InstaPy#799]
Unfollow was working fine for me and suddenly stopped working.

[Error](https://i.imgur.com/P4Osnke.png)

session.unfollow_users (amount=50, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO' )

I have that line set as last right before session.end, everything else goes smoothly and works fine until unfollow.

**Comment by converge** [comment]
the problem is related to set_automated_followed_pool, can you send your *_followedPool.csv file to my email ? joaopaulo.mailfs@gmail.com , so I can reproduce the error.

**Comment by avanjool** [comment]
Alright I just sent it.

**Comment by converge** [comment]
@avanjool sorry I didn't replied yet, I'll do it soon as possible.

**Comment by SamuelPinho** [comment]
I'm with the same error
