### ISSUE TITLE
Wrong login data! - but login data is correct

### ISSUE THREAD

**Issue by remybrillet** [InstaPy/InstaPy#802]
Hi,

I have this error : 

Wrong login data!
Traceback (most recent call last):
  File "bot.py", line 23, in <module>
    session.end()
  File "/root/InstaPy/instapy/instapy.py", line 1401, in end
    self.browser.delete_all_cookies()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriv                            er.py", line 655, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriv                            er.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorha                            ndler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unhandled                             inspector error: {"code":-32601,"message":"'Network.deleteCookie' wasn't found"                            }
  (Session info: chrome=62.0.3202.62)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822c                            c5),platform=Linux 4.4.92-mainline-rev1 x86_64)

someone with the same problem ?
Regards

**Comment by converge** [comment]
take a look #791

**Comment by remybrillet** [comment]
Seem like when I change:

InstaPy/instapy/login_util.py
 if len(nav) == 2: 
to 
if len(nav) == 1: 

then I have this error : 

selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status

**Comment by converge** [comment]
Hello, you need update chromedriver to latest version.

**Comment by remybrillet** [comment]
Hello,
After updating :  

Traceback (most recent call last):
  File "bot.py", line 10, in <module>
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 184, in login
    self.switch_language):
  File "/root/InstaPy/instapy/login_util.py", line 8, in login_user
    browser.get('https://www.instagram.com')
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from tab crashed
  (Session info: chrome=62.0.3202.62)
  (Driver info: chromedriver=**2.9.248304**,platform=Linux 4.4.92-mainline-rev1 x86_64)

**Comment by timgrossmann** [comment]
@remybrillet Looks like you're running it on a linux machine, is it a DO droplet?

If yes, the problem might be that there are zombie instances of XVFB and Chrome running.

Do a `reboot` and try again, please

**Comment by remybrillet** [comment]
Hello @timgrossmann, thanks for your answer.

now, I have this error : 
    session.login()
  File "/root/InstaPy/instapy/instapy.py", line 184, in login
    self.switch_language):
  File "/root/InstaPy/instapy/login_util.py", line 8, in login_user
    browser.get('https://www.instagram.com')
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"9782.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=62.0.3202.62)
  (Driver info: chromedriver=2.9.248304,platform=Linux 4.4.92-mainline-rev1 x86_64)

I run this script from a VPS based in Iran. Maybe Instagram can reset my connection ? 
I live in France.

**Comment by remybrillet** [comment]
Another error, when I run the script for the first time after a reboot :  
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

I think Instagram doesn't want to accept my connection from Iran. 
Somebody know how to bypass it ?

**Comment by converge** [comment]
@remybrillet I don't know why Chromedriver uses versioning in this way, but 2.9 [1] is from 2014, the latest driver is 2.32 [2]

[1] https://chromedriver.storage.googleapis.com/index.html?path=2.9/
[2] https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by remybrillet** [comment]
Hi,

I have install Firefox and set "use_firefox = true".
Then, it's OK.

but, the bot say's he like some pictures : 

[8/100]
Image from: b'geeksnextdoorhq'
Number of Followers: 2007
Link: b'https://www.instagram.com/p/Bav4Z6KFZEU/?tagged=paris'
Description: b'#TRILL #Dope #streetgoth #SWAG #newaccount #fresh #hiphop #follow4follow #coolin #freestyler #fashion #Philadelphia #newyork #Miami #nexttopdesigner #losangeles #bayarea #Memphis #Atlanta #Houston #2017 #Art  #London #Paris #hongkong #Tokyo #Rome\n#anime\n#Toronto\n#artist'
--> Image Liked!

After verification, the picture is not liked.
Somebody have this problem ?

**Comment by converge** [comment]
@remybrillet do you get the same error using latest chromedriver ?

**Comment by remybrillet** [comment]
@converge I have download the latest version (http://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip), put it in assets and then pip install . but the result is the same : 

selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 2.6.32-042stab116.1 x86_64)

**Comment by converge** [comment]
@remybrillet remove chromedriver from your PATH system variable, it's still trying to load ```chromedriver=2.29.461571```

**Comment by remybrillet** [comment]
@converge : How ?
I haven't chromedriver in my PATH system variable : 

root@serveur:~/InstaPy# echo $PATH | tr ":" "\n" | nl
     1  /usr/local/sbin
     2  /usr/local/bin
     3  /usr/sbin
     4  /usr/bin
     5  /sbin
     6  /bin
     7  /usr/games
     8  /usr/local/games

**Comment by chrisscholly** [comment]
Works for me with `chromedriver v2.33` (https://chromedriver.storage.googleapis.com/index.html?path=2.33/).
No need to run `pip install` or whatever. Just drop the downloaded `chromedriver` file in `/assets` and you are good.

**Comment by rodriguesprobr** [comment]
Try to delete the cookie file on logs folder and, then, start your script.
