### ISSUE TITLE
Headless Raspberry Pi w/ Firefox login out of bounds.

### ISSUE THREAD

**Issue by elmerilaakkonen** [InstaPy/InstaPy#803]
## Expected Behavior
To log in normally.

## Current Behavior
InstaPy can't log in because the login-button is out of view.

> Traceback (most recent call last):
>   File "xxx.py", line 11, in <module>
>     session.login()
>   File "/home/xxx/xxx/instapy/instapy.py", line 184, in login
>     self.switch_language):
>   File "/home/xxx/xxx/instapy/login_util.py", line 24, in login_user
>     ActionChains(browser).move_to_element(login_elem).click().perform()
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
>     self.w3c_actions.perform()
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
>     self.driver.execute(Command.W3C_ACTIONS, enc)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (417, 619) is out of bounds of viewport width (720) and height (469)
> 

## Possible Solution (optional)
Fixed this quickly by changing the launch resolution on instapy.py line 54:
`self.display = Display(visible=0, size=(800, 600))`
`self.display = Display(visible=0, size=(1900, 1200))`

## InstaPy configuration

Raspberry Pi 3, Raspbian Stretch Lite (2017-09-07 release)
Mozilla Firefox 52.4.0 (firefox-esr)
Selenium 3.6.0
Pyvirtualdisplay 0.2.1
Xvfb

Running with Python 3, nogui=True and use_firefox=True.

My solution isn't probably the best one, but it worked for me.
Maybe for some reason Display() doesn't launch correctly sized viewport?
Another solution could be to launch the browser maximized?

**Comment by alexsmedile** [comment]
The suggested solution doesn't resolve my problem.
```
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session.login()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 264, in login
    self.bypass_suspicious_attempt):
  File "/home/pi/Projects/InstaPy/instapy/login_util.py", line 121, in login_user
    ActionChains(browser).move_to_element(login_elem).click().perform()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <a> stale: either the element is no longer attached to the DOM or the page has been refreshed
```
I'm trying to run quickstart.py headless_browser=False,use_firefox=True,multi_logs=True
