### ISSUE TITLE
Anything similar for Facebook? 

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#808]

**Comment by sionking** [comment]
I am not sure if this is the place, do you know about a similar tool for Facebook?
Thanks.

**Comment by timgrossmann** [comment]
@sionking Haha, I was thinking about the same thing...

The long term idea is to create an open source organisation here on github which would be called
"BotPy". 
You could find all kinds of social bots there including InstaPy. (And an improved version of TwitPy, maybe FacebooPy and YouTubePy as well...)
But first it would be really nice to have a quite stable version of InstaPy.

However, I don't know of any tool that has requested behaviour yet

**Comment by ishandutta2007** [comment]
Few repos to get started:

https://github.com/clintmcmahon/twitter-retweet-bot
https://github.com/robbiebarrat/twitter-contest-enterer

https://github.com/ayushxx7/Facebook-Auto-Liker
https://github.com/jellevdvliet/facebook-bot-autoresponder
https://github.com/nicopastorello/Selenium-Facebook

@timgrossmann Plese do create dummy repos and let us know we will  try to take the organisation forward.

**Comment by timgrossmann** [comment]
@ishandutta2007 Hey, thank you for the links!

What exactly do you mean by "try to take the organisation forward"?
I think it makes most sense to focus our efforts on making InstaPy stable and nicely done.

Once we've done that, we have a quite some experience and can avoid the problems and faults we made, when developing a new system for facebook, twitter, youtube etc.
