### ISSUE TITLE
Why is the script stopping

### ISSUE THREAD

**Issue by wizarduk** [InstaPy/InstaPy#813]
Why is the script stopping?
Can i set it to run without having to log in each day?

This is the error 

File "quickstart.py", line 22, in <module>
    session.end()
  File "/root/InstaPy/instapy/instapy.py", line 1401, in end
    self.browser.delete_all_cookies()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 655, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32601,"message":"'Network.deleteCookie' wasn't found"}
  (Session info: chrome=62.0.3202.62)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 2.6.32-042stab125.3 x86_64)

**Comment by wizarduk** [comment]
Has anyone got the settings they are using so i can run this on cron and just leave it running ?

**Comment by converge** [comment]
@wizarduk do you have some clue why the cookies aren't being deleted ?

**Comment by wizarduk** [comment]
@converge no clue i ran this and it was working for a good 6 hours then it shut down...

I want to run this and leave it running so wanted to know the best way...

**Comment by wizarduk** [comment]
Does the cron job run in screen ?

**Comment by converge** [comment]
@wizarduk pls, update your chromedriver, they fixed this bug at 2.32 version, you're using 2.29

- Fixes a bug where Chromedriver fails to delete cookies in Chrome 62+. (2.32)

**Comment by wizarduk** [comment]
@converge how do i do that ?

**Comment by wizarduk** [comment]
@converge 

why is the guide saying this then ?>

git clone https://github.com/timgrossmann/InstaPy.git
$ wget "http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip"

**Comment by converge** [comment]
@wizarduk you're right, the doc is outdated, just created an issue to update it.

**Comment by wizarduk** [comment]
@converge When i am setting up cron do i need to do a screen and then cd InstaPy and then crontab -e ?

**Comment by wizarduk** [comment]
@converge i want to start the script once a day via cron what do i need to do to set it can you give me a guide ?

**Comment by converge** [comment]
@wizarduk you just need to setup cron , don't need to use screen for it.

I use cron in this way:
```
1 */3 * * * killall Xvfb
20 */3 * * * cd /opt/InstaPy/ && python /opt/InstaPy/bot.py >> /tmp/cron_debug_instapy.log 2>&1
```

it will run each 3 hrs, 00:20 , 03:20 and so on.

**Comment by wizarduk** [comment]
@converge so if i wanted once every 24hrs its this

 00*** cd/InstaPy && python3.4  /cd/InstaPy/quickstart.py >> /tmp/cron_debug_instapy.log.2>&1

**Comment by PriKahar** [comment]
This does not seem to work for me on 62.0.3202.75 version.
I am getting the same error 'Network.deleteCookie was not found'

**Comment by wizarduk** [comment]
@PriKahar update your chrome driver
