### ISSUE TITLE
How_To_DO_Ubuntu_on_Digital_Ocean.md (update help)

### ISSUE THREAD

**Issue by converge** [InstaPy/InstaPy#814]
Hello everyone, our Linux how to is outdated, can any Linux user update it ?

https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md

**Comment by CruiseDevice** [comment]
Hello @converge. I would like to work on this. Can you please guide me on what exactly are the changes i have to make.

**Comment by converge** [comment]
hey @CruiseDevice , thank you for your interest!
I did it this weekend and forgot to close this issue, sorry. But it would be great if you could test it.

If you have some consideration or changes, you could fork it and propose a pull request with your ideas/changes.
