### ISSUE TITLE
Less users to follow than requested.

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#815]
Hello guys,
I'm using the configuration below to follow and give like in the followers of some specific profiles.

```python
from instapy import InstaPy

insta_username = 'USER'
insta_password = 'PASSW'

#if you want to run this script on a server,
#simply add nogui=True to the InstaPy() constructor

session = InstaPy(username=insta_username, password=insta_password, nogui=True)
session.login()

session.set_do_follow(enabled=True, percentage=100)
session.set_do_like(enabled=True, percentage=99)
session.interact_user_followers(['antonybeautycenter','lf.luizfreitas','virgiliorosa','guriasbeauty','beautybase_lf','labellecenter','silviodpaula','allexgorenmua','nilza_bezerra','Paulaespelho','beautylounge_paulaespelho','jutomazmakeup','luispirinelli_oficial','silpaschoarellimakeup','linferreira','dalvamakeup','fabiolamake','silvio','rickolivveira','annaglam','ricky_cordeiro21','wmichela','vitor_beletatti','thiagoalencarbeaute','andersonsilvahair','thiagoscagliarini','vitorribeirow','jacksonnunesoficial','ivanjosecabelos','gaby.hair'],amount=60, random=True)

session.end()
```

But when I run installpy it shows the second message:

Logged in successfully!
guriasbeauty -> Less users to follow than requested.
beautybase_lf -> Less users to follow than requested.
labellecenter -> Less users to follow than requested.

Could you help me ?

**Comment by sionking** [comment]
I found out scrolling more will give you more users 
```python
   # find dialog box
    dialog = browser.find_element_by_xpath(
        "//div[text()='Followers']/following-sibling::div")

    # scroll down the page
    try:
        print('0')
        scroll_bottom(browser, dialog, allfollowing)
        scroll_bottom(browser, dialog, allfollowing)
        scroll_bottom(browser, dialog, allfollowing)
    except:
        pass

    # get follow buttons. This approch will find the follow buttons and
    # ignore the Unfollow/Requested buttons.
    follow_buttons = dialog.find_elements_by_xpath(
        "//div/div/span/button[text()='Follow']")
    person_list = []

    if amount >= len(follow_buttons):
        amount = len(follow_buttons)
        print(user_name+" -> Less users to follow than requested. == "+str(amount))
```

also print the amount of users captured!

**Comment by antony5617** [comment]
Hello, i got the same error. Can someone help me ? 

Thanks a lot!

**Comment by converge** [comment]
hey @antony5617 , is your InstaPy updated with latest version ?

**Comment by antony5617** [comment]
Yes i do

**Comment by addiman** [comment]
any news about this one?

**Comment by laforetcan** [comment]
Indeed it's an issue I have all the time, it seems that when loading the followers it doesn't scroll enough I tried setting a random time sleep before scrolling but it didn't fix the bug. If someone has a clever idea to fix this I'm interested too!

**Comment by eternaldigger** [comment]
Hi everyone! 
The same problem. I also noticed that  it practically does not depend on the quantity of followers user has.
When problem appears it does not disappear anywhere until session end.

**Comment by eternaldigger** [comment]
And one more. This problem appears only if I use "Interact..." option and does not appear when I use "session.follow_..." options.  Probably it is connected with the message:  "CRITICAL - Sorry, Record Activity is not working on Windows. We're working to fix this soon!", which appears in the beginning of session.

**Comment by santon777** [comment]
Same on linux. Interact not loading full list of users

**Comment by timgrossmann** [comment]
#1066 

We have to restructure some things in order to preserve it working... This will not be minor refactors but some bigger ones that also cover the stated problem...

If you guys could help out, here's the link to support the dev: [Support InstaPy](https://www.paypal.me/supportInstaPy)

This will definitely result in stuff being resolved faster

**Comment by converge** [comment]
just realized you guys forgot to set it:
```python
session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
```
