### ISSUE TITLE
The Bot isn't showing follower users followers

### ISSUE THREAD

**Issue by justinf102** [InstaPy/InstaPy#828]
![image](https://user-images.githubusercontent.com/31114105/32100782-269939a2-bae3-11e7-890c-dc045e321faa.png)

any ideas?

**Comment by justinf102** [comment]
It's basically not showing all the features

**Comment by converge** [comment]
hey @justinf102 , this is InstaPy (the core of InstaPy-GUI),
InstaPy-Gui is at https://github.com/ahmadudin/electron-instaPy-GUI

**Comment by justinf102** [comment]
I downloaded the instapy-gui tho

**Comment by justinf102** [comment]
Fixed!! Thanks
