### ISSUE TITLE
Instagram now using cpatch

### ISSUE THREAD

**Issue by ToJen** [InstaPy/InstaPy#83]
I tried running `quickstart` this morning and found that the login page layout has changed to this:

[Instagram Login Page Update](https://drive.google.com/file/d/0B584NUUwKdOHUDliMVlRTEhsSDg/view?usp=sharing)

**Comment by pekapa** [comment]
This is the sign up page.
For the login page I don't have captcha yet, do you have on in there as well?

**Comment by eduardocalazansjr** [comment]
This always have been the instagram login page.
The class elements for not logged in users is always the same.

Still working as indeed.

If you're experiencing issues, post the log.

Edit: it only change when instagram detects your IP as an possible abuse (but still the class for login button remains the same).

Edit: CPATH? What

**Comment by ToJen** [comment]
@vlntdds I meant CAPTCHA, the only page that loaded was that one then the program crashed. I guess I just have to pull again.

**Comment by pekapa** [comment]
@ToJen,
Mind sharing the traceback?

**Comment by eduardocalazansjr** [comment]
Just tested it again and the class still `_fcn8k`.
Still waiting for the logs.

**Comment by ToJen** [comment]
It's good now. I think I was making changes half asleep haha

**Comment by ToJen** [comment]
However, how do we handle situations where Instagram changes their DOM and all the elements? 
I'm thinking some kind of good natural language parser (which I haven't learnt much about yet) could be used to improve the scraper. What do you think?

**Comment by littleswany** [comment]
@timgrossmann This issue can be closed as it is not an issue and has been resolved.

@ToJen At the moment we have to manually handle issues when Instagram change their DOM.

**Comment by ToJen** [comment]
Sure, I'll close it now.
