### ISSUE TITLE
How to follow only active followers of the users account?

### ISSUE THREAD

**Issue by justinf102** [InstaPy/InstaPy#830]
Sorry for all the questions, I was just wondering if this is a possible feature, and if so, How do you configure it? thanks.

**Comment by justinf102** [comment]
what i mean by active is that they like the user's posts

**Comment by converge** [comment]
@justinf102 we only have today the feature 
```unfollow_active_users(enabled=True, posts=3)```

we should change it's name to dont_unfollow_active_users, it prevents to unfollow users who liked one of our latest "3" posts.

**Comment by justinf102** [comment]
Ok, and do you know how to loop the bot so it can run 24/7? Great bot btw

**Comment by justinf102** [comment]
Or is there anyway to loop it

**Comment by converge** [comment]
@justinf102 thanks, @timgrossmann made most of the work, I'm just helping a little.
you can do it, take a look:

https://github.com/timgrossmann/InstaPy#automate-with-cron
https://github.com/timgrossmann/InstaPy#automate-with-schedule

**Comment by justinf102** [comment]
im too noob to setup schedule lol

**Comment by justinf102** [comment]
Like how would you set up a crontab in windows command prompt?

**Comment by timgrossmann** [comment]
@converge Haha, there are really a ton of people involved in this project. Very few, as actively as you are so you definitely deserve quite a lot of the thank you's!

**Comment by converge** [comment]
pls, reopen it if you need.
