### ISSUE TITLE
Crashing of Script on Firefox

### ISSUE THREAD

**Issue by amoffitt123** [InstaPy/InstaPy#833]
Hello, I am using InstaPy on firefox, and since about 2 days ago, the script crashes after logging in and liking one photo. any help? thanks.
Here is the error;

> Logged in successfully!
> Tag [1/10]
> --> b'photography'
> [1/110]
> Image from: b'ruslaanmumtaz'
> Link: b'https://www.instagram.com/p/Bax0M1QhAAT/?tagged=photography'
> Description: b"I DID NOT WAKE UP LIKE THIS.\nStaying fit for so many years consistently is not easy. Many people need to help you, to inspire you and to support you. \nThank you to my family for eating healthy so that there are less unhealthy options at home, thank you to my friends for not pushing me to drink or smoke, thank you to all the fit and beautiful people in the world for being role models and inspirations, thank you to all the photographer's I've worked with for making me look good and a big thank you to all my followers on Instagram for all the love and encouragement. Without all this it would be much tougher than it already is.\nPhotography @amitagarwalphotography \nMake up and hair @jyoti.90 \nStyling @poshnixilicious \n#fitness #fitnessmodel #fitman #instafit #workoutmotivation #instagood #fitactor #beachbody #beach #juhu #photo #photography #photographer #photoshoot #portrait #beard"
> --> Image Liked!
> Traceback (most recent call last):
>   File "/home/pi/no/firefoxExample.py", line 25, in <module>
>     .like_by_tags(['photography', 'lightphotography', 'photooftheday', 'photogapher', 'explore_ig', 'landscape_ig', 'steelwool', 'portraiture', 'photo', '35mm'], amount=110) \
>   File "/home/pi/no/instapy/instapy.py", line 523, in like_by_tags
>     commented += comment_image(self.browser, comments)
>   File "/home/pi/no/instapy/comment_util.py", line 27, in comment_image
>     comment_input[0].submit()
>   File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 83, in submit
>     self._execute(Command.SUBMIT_ELEMENT)
>   File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
>     return self._parent.execute(command, params)
>   File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
>     self.error_handler.check_response(response)
>   File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.StaleElementReferenceException: Message: Element not found in the cache - perhaps the page has changed since it was looked up
> Stacktrace:
>     at fxdriver.cache.getElementAt (resource://fxdriver/modules/web-element-cache.js:9454)
>     at Utils.getElementAt (file:///tmp/tmp0ldqluge/extensions/fxdriver@googlecode.com/components/command-processor.js:9039)
>     at WebElement.submitElement (file:///tmp/tmp0ldqluge/extensions/fxdriver@googlecode.com/components/command-processor.js:12156)
>     at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmp0ldqluge/extensions/fxdriver@googlecode.com/components/command-processor.js:12661)
>     at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmp0ldqluge/extensions/fxdriver@googlecode.com/components/command-processor.js:625)
>

**Comment by converge** [comment]
hello @amoffitt123 , we fixed it today, please update InstaPy and try again. If the problem persists, please reopen this issue.
