### ISSUE TITLE
"chromedriver is missing!" in GUI even though the newest chromedriver is in \assets

### ISSUE THREAD

**Issue by michaloslav** [InstaPy/InstaPy#834]
I installed the GUI, cloned InstaPy and directed the GUI to the folder. I then downloaded the newest version of chromedriver from the website and put it in the \assets folder but the GUI still says that it's missing. When I try to run it anyway, I get this: "Error: SyntaxError: EOL while scanning string literal"
I tried googling around but I didn't find anyone with a similar problem so I decided to ask here. (I know a bit about programming but I mainly focus on web and game development so please, keep it simple for me, thx)

**Comment by timgrossmann** [comment]
@michaloslav Please post this issue at the GUI repository...

**Comment by CiprianDe** [comment]
Hey There!
I am dealing with the same problem. 
Any idea?
