### ISSUE TITLE
How to setup a Schedule for Windows?

### ISSUE THREAD

**Issue by justinf102** [InstaPy/InstaPy#836]
Would I use schedule task? or would I download Cron for windows?

**Comment by timgrossmann** [comment]
@justinf102 There should be a GUI application provided in the windows system with which you can easily set up scheduled tasks

**Comment by balakedev** [comment]
@justinf102 Hey mate, Suss out running Task Scheduler. You can tell your computer to run .bat files and the .bat files can launch the .python files. I've been doing this for months.

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
