### ISSUE TITLE
Cron Job problem

### ISSUE THREAD

**Issue by narchiii** [InstaPy/InstaPy#837]
I'm running into a problem setting up a cron job. I'm using OSX El Capitan. I have InstaPy running ,from my home directory, with this command.

cd healthy_bot/InstaPy && python ./quickstart.py

However, when I put this in my crontab and save it; nothing happens at the specified time. 

39 0 * * * cd healthy_bot/InstaPy && python ./quickstart.py

Sorry for asking such a basic question. I'm very new to cron.

Thank you for this amazing project. It's very useful. If this is out of the "issues" scope it's no problem." But, any help would be much appreciated.

**Comment by timgrossmann** [comment]
@narchiii to be absolutely sure, please always provide an absolute path for the `cd` part here.
e.g for me it would be `/Users/TG/git/InstaPy`

Also, if you're using `./quickstart.py` you should not add the `python` before it.
Either do `python quickstart.py` or `./quickstart.py`

`./quickstart.py` will also only work if you added 'execute' permissions for the given user and added the shebang line on the top of the file.
Therefore, simply use `python quickstart.py`

Should work then.

**Comment by narchiii** [comment]
Sorry to be annoying. But, I tried it with the absolute path and got the same results. When I run 
cd /Users/appcode/healthy_bot/InstaPy && python ./quickstart.py
everything runs fine. 

But, when I put this into crontab nothing happens. 

11 1 * * * cd /Users/appcode/healthy_bot/InstaPy && python ./quickstart.py

I understand if you can't point me in the right direction because it's not a problem with InstaPy. I'm just too ignorant to figure it out.

Thanks again for this project!

**Comment by timgrossmann** [comment]
@narchiii Can you please read my answer...

**Comment by timgrossmann** [comment]
> # Therefore, simply use python quickstart.py

**Comment by narchiii** [comment]
Thanks! It works now.
