### ISSUE TITLE
cannot use characters like "ü" in hashtags

### ISSUE THREAD

**Issue by akcasoy** [InstaPy/InstaPy#838]
Is this a desired functionality? Or i could not figure it out which Unicode representation i have to use in my hashtag string..

**Comment by timgrossmann** [comment]
@akcasoy please give some more information about where what is not working...

Is it the commenting?
Have you tried `u'Test das ist eine übung'`

**Comment by akcasoy** [comment]
Try to give some hashtag with ü in "Like by Tags". Then you click on run button and see the error.. But the problem may also be sth. related with the "InstaPy GUI"..  I cannot run the app without the GUI right now.

**Comment by akcasoy** [comment]
This is the error when i run your app without GUI:

File "quickstart.py", line 11 (this is the line with session.like_by_tags(['sehenswürdigkeit'], amount=500, media='Photo'))
SyntaxError: Non-ASCII character '\xc3' in file quickstart.py on line 11, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by mohdhazwan** [comment]
facing the same prob above 
- with/without GUI
- `SyntaxError: Non-ASCII character ...`
- tried with `u'Comment 🍕'`

**Comment by hojabbr** [comment]
Just add these lines to `quickstart.py` and `instapy.py`:

```
# -*- coding: UTF-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

**Comment by saroar** [comment]
@hojjabr does not help me http://prntscr.com/m454b9 also try this 
```session.like_by_tags(["маникюрбогатырский"], amount=100)```
