### ISSUE TITLE
[feature] InstaPy statistics

### ISSUE THREAD

**Issue by converge** [InstaPy/InstaPy#839]
Hello,

I'm thinking about this idea and wanna share with you.

Record every InstaPy activity (like, comment, follow, unfollow, account followers, account following) in a statisticas.csv file and organize it by day, like:

```
date,likes,comments,follows,unfollows,instagram_server_call
01.xx.xx,30,15,120,150,1000
02.xx.xx,50,25,110,150,1200
03.xx.xx,10,5,110,100,700
```

**Why ?**
To be able to create reports, measure interactions and measure account grow.

This data can be used by external tools to create reports, in this way, we focus InstaPy for the core/engine and let it be extensible as it's today with InstaPy-GUI.

Chart example that can be created using the statistics.csv data:
![Imgur](https://i.imgur.com/npPBQwg.png)

**Comment by RomeoJuliett** [comment]
I think this is a pretty good idea actually! Custom analytics would go a long way in being able to track our activity. I currently use SocialBlade to monitor how far my reach is extending. Not ideal, but it does work.

**Comment by JCADC** [comment]
That'd be awesome @converge !

**Comment by pilotdude** [comment]
I've been brainstorming how to collect and report analytics for a while now. I definitely want to devote some time to it. I've been debating over whether it would be better to use csv or establish a local SQLite Database. Do you have a reason for suggesting a csv file as opposed to SQLite?

**Comment by converge** [comment]
hey @pilotdude ! A "real" database requires heavy modules (and more modules to be installed), a database diagram well documented and it increases complexibility.

I think the csv approach is good to keep it clean and simple, in this way the database complexibility can be used for front ends for example where way more informations are needed/collected/saved.

I'll propose a pull request tonight, it's 90% done, just need to track more server calls and more testing.

**Comment by pilotdude** [comment]
@converge I just skimmed your OP and thought it was exactly what I was thinking about but it wasn't. For what you proposed a csv file is definitely much better. 

I was thinking of a whole lot more analytics and info that could be used to speed up the process. For example noting the follower counts of specific accounts, noting post IDs that had already been interacted with etc. So then when the script comes across a post it first searches the DB to see if we already have seen that this post is for some reason not appropriate before it has to load a page and check. That I guess is my dream of where I would like to see this end up :)

I'm pretty sure using SQLite wouldn't require any extra installation because it already comes with python.  But for sure we should be using a csv file for what you are proposing.

**Comment by converge** [comment]
hey @pilotdude @JCADC @RomeoJuliett, if you guys have some free time, could you help me testing it ?

**Comment by pilotdude** [comment]
@converge I will see if I can look at it tonight.

**Comment by sionking** [comment]
I made something simieler using pickle, also limit the total likes and follows per hour/day.
I opened  a thread for it!

**Comment by converge** [comment]
hey @sionking , that's good!! I didn't know you were working on it, just made a PR. It will be great if we could work together on it, there is some flaws following/unfollowing in my approach. And I think it generates a bit more code than I was expecting.

PR: #859

**Comment by hestuppfodarn** [comment]
Hi @converge,
What was the outcome of the 'exporting statistics' idea?
I love this feature and would love to have it.

**Comment by converge** [comment]
@hestuppfodarn good to hear that. The feature is ready (for non Windows users), update to latest commit and check /logs/activity.csv

about the graph, it requires a lot of work, maybe I'll wait a BountySource request, it could be a collective work, with collective Bounty. Maybe we could have a designer to design it, don't know yet. We need to elaborate it.

**Comment by hestuppfodarn** [comment]
@converge thanks!
another feature that would be nice to add to this is "USER ID", so you know who you interacted with
