### ISSUE TITLE
Clarifai not working

### ISSUE THREAD

**Issue by songproducer** [InstaPy/InstaPy#84]
```
Image check error: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//img[@class = "_icyx7"]"}
  (Session info: chrome=58.0.3029.54)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.4 x86_64)
```

**Comment by timgrossmann** [comment]
@songproducer Could you also post the link of the image this happened at?

**Comment by songproducer** [comment]
https://www.instagram.com/p/BSyyNlyg48F/?tagged=food

**Comment by saphuttu** [comment]
I had similar problem

https://www.instagram.com/p/BTHmQRkBBqy/?tagged=frenchbulldog

```
Image check error: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//img[@class = "_icyx7"]"}
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.11.6 x86_64)
```

**Comment by timgrossmann** [comment]
@saphuttu This really shouldn't happen...
But thank you for posting, now we know that it definitely is a video-post problem!

**Comment by timgrossmann** [comment]
Interesting, this really shouldn't happen, since the `Error` should be catched...
```python
except Exception as err:
      print('Image check error: {}'.format(err))
      self.logFile.write('Image check error: {}\n'.format(err))
```

**Comment by saphuttu** [comment]
Can i avoid this by some parameter in Clarifai or totally ignore videos while running InstaPy?

**Comment by pekapa** [comment]
Looks like the problem is occurring when you try to send a video to ClarifAI
For now, you can avoid that by setting `.like_by_tags(tags, amount , media='Photo')` when using ClarifAI so it won't try to work with videos.

**Comment by saphuttu** [comment]
Thanks @pekapa!

**Comment by littleswany** [comment]
@timgrossmann or @songproducer This issue can be closed
