### ISSUE TITLE
 follow loop error?

### ISSUE THREAD

**Issue by justinf102** [InstaPy/InstaPy#840]
Anyone know how to fix? And what is the command line to update bot.

**Comment by converge** [comment]
hey @justinf102 , show your full trace back and your current quicktime.py setup

**Comment by bradenjust** [comment]
I am also getting this error. I have attached an image of my quickstart.py file
![error](https://user-images.githubusercontent.com/33287578/32285034-1e63e01c-bef7-11e7-97c4-c44cc2989b79.PNG)

**Comment by converge** [comment]
@bradenjust @justinf102 , pls, show the full error message.

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
