### ISSUE TITLE
Docker all_in_one building issue

### ISSUE THREAD

**Issue by bsnisar** [InstaPy/InstaPy#841]
## Expected Behavior
Build docker immage with all components successfully

## Current Behavior
Build failed:
`
dpkg: dependency problems prevent configuration of google-chrome-stable:
 google-chrome-stable depends on lsb-release; however:
  Package lsb-release is not installed.
`

## Possible Solution (optional)
dpkg will failed on first unmet dependecies. This dependecies should be fixed by `apt-get install -y -f`, but it won't be executed as dpkg returns non-zero code.

It can be fixed by:
`apt-get install -y -f ./google-chrome-stable_current_amd64.deb`

see: https://github.com/bsnisar/InstaPy/pull/1

## InstaPy configuration
clone repository and `docker build -t instapy ./docker_conf/all_in_one`

**Comment by timgrossmann** [comment]
@bsnisar Is this still an issue? Please reopen if it is
