### ISSUE TITLE
Cron Job On Raspberry Pi Not working

### ISSUE THREAD

**Issue by omidedipidizi** [InstaPy/InstaPy#842]
my cron not running at all ...

Could somebody help please ?

This is my configuration 

![crontab](https://user-images.githubusercontent.com/25254194/32206125-b3d15b4a-bdc9-11e7-8ed6-4aa8d17197c0.PNG)

**Comment by timgrossmann** [comment]
@omidedipidizi Assuming you want to run this script every hour at :20 (1:20, 2:20, 3:20)

You just put the * ... */1 does not make any sense to do since the star at that position means every hour.

So just do `20 * * * * cd ............`
