### ISSUE TITLE
Waits in code (Sleep)

### ISSUE THREAD

**Issue by akcasoy** [InstaPy/InstaPy#844]
I have seen in code that you often used some waits with sleep(seconds). Are those just for waiting for HTML Elements? If so, why did not you use sth. like “waitForElement”, and the code simply waits just until the element appears, so all in all everything runs a bit quicker.

Or was that a way of avoiding the Instagram Captcha, so that the Instagram does not see your app as a bot? If so, and if you know, could you please share with me how are those limitations are, and how does your app take those into consideration? (how many likes, comments or follows per hour/day does the bot as max).

Thank you in advance.

**Comment by ujazzz** [comment]
Would really like to see this implemented.

**Comment by pilotdude** [comment]
Sleep is to introduce a delay and some randomness to help avoid being blocked as a bot.

see: #764

**Comment by henrytriplette** [comment]
You can add the sleep function inside your code by importing 

`from InstaPy.instapy.time_util import sleep`

And using it like that:

```
# Sleep for > 10 minutes
print("Sleeping now for 10 minutes")
sleep(random.randint(600,700))
```
