### ISSUE TITLE
my account hacked

### ISSUE THREAD

**Issue by 1saeedsalehi** [InstaPy/InstaPy#848]
i use instapy gui over instapy and my account was hacked
it's not secure really,
i take my account back , but please care about using instapy gui

anybody knows about instapy security?

**Comment by converge** [comment]
hey @1saeedsalehi , sad to hear that. I don't know InstaPy GUI, it's other project and other repository.

Speaking about InstaPy side:
your login/passwd is store in a local file and used in the login page, after that, there is no more interaction with those data.

**Comment by komad1na** [comment]
How did you notice that? Can you explain behaviour of your account?

**Comment by 1saeedsalehi** [comment]
@Nemixalone suddenly I logged out from everywhere, also my password reset email was changed and much more.
morandoron97@gmail.com
is hacker email address,

finally, I take back my account, but I think  instapy GUI is not secure

please remove it from installation document

**Comment by narchiii** [comment]
@1saeedsalehi  How did you manage to get your account back?

**Comment by 1saeedsalehi** [comment]
@narchiii I received an email that let me revert recovery email change  and password change

**Comment by RomeoJuliett** [comment]
You could always just run Instapy in AWS on a Linux instance. That seems to be a bit more secure all things considered.

**Comment by sionking** [comment]
Sound like an Israeli name morandoron97@gmail.com hacking an Arab name 1saeedsalehi :)
Kidding.

**Comment by 1saeedsalehi** [comment]
@romeojuliett 👍good idea

**Comment by 1saeedsalehi** [comment]
@sionking 😁 i am from iran

**Comment by sionking** [comment]
Sorry I know Iran are not Arabs :)

**Comment by converge** [comment]
@1saeedsalehi please, reopen it if you still need some help.
