### ISSUE TITLE
How do I use schedule with docker microservice?

### ISSUE THREAD

**Issue by Radzam** [InstaPy/InstaPy#849]
I am new to docker and not really sure what to do here. I would like to schedule so that my docker microservice is being run several times per day and liking 100 images with specified tags each time. 

I can run it without the scheduling functionality just fine, and when I connect with VNC I can see that selenium is doing its work. However it does not seem to work when I try to add schedule inside docker_quickstart.py.

I am also wondering how can I check the logs in the docker microservice to verify that bots actions have been completed & how many images have been liked each time etc? Thanks

## My  docker_quickstart.py configuration that doesnt seem to work:
```
from instapy import InstaPy
import schedule 
import time

def job():
    try:

bot = InstaPy(username='xxx', password='xxx', selenium_local_session=False)
bot.set_selenium_remote_session(selenium_url='http://selenium:4444/wd/hub')
bot.login()
bot.set_upper_follower_count(limit=5000)
bot.set_do_comment(True, percentage=10)
bot.set_comments(['Testing', 'anothertest'])
bot.like_by_tags(['food', 'blog', 'anothertest'], amount=100)
bot.end()

    except:
        import traceback
        print(traceback.format_exc())

schedule.every().day.at("08:00").do(job)
schedule.every().day.at("13:00").do(job)
schedule.every().day.at("19:00").do(job)

while True:
    schedule.run_pending()
    time.sleep(1)


```

**Comment by Radzam** [comment]
anyone?

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
