### ISSUE TITLE
don't like option

### ISSUE THREAD

**Issue by nick-preda** [InstaPy/InstaPy#85]
hi guys,

does the dont_like option really work?

i've got my array of:

dont_like = ['funny', 'love', 'friendship', 'smile', 'pretty', 'live', 'onedirection', 'profile', 'guy', 'look', 'boy', 'boys', 'gay', 'homo', 'food', 'girl', 'hot', 'sexy', 'cars', 'bride', 'girls', 'luxury', 'shoe', 'shoes', 'legs', 'leg', 'bikini', 'fashion', 'moda', 'me', 'selfie']

but i can see that the script likes and comments photos with at least one of those written in the array.

i've got, both set_dont_like and set_ignore_if_contains, like that:
.set_dont_like(dont_like) \
  .set_ignore_if_contains(dont_like) \

am i missing something?

cheers

**Comment by pekapa** [comment]
You don't need the `.set_ignore_if_contains(dont_like)`
`.set_ignore_if_contains` acts as a overpass for the `.set_dont_like`, meaning that, even if one of the `dont_like` tags is present the image will still be liked.

**Comment by nick-preda** [comment]
made the modification, and I still get the same thing though.

i've got my
`dont_like = ['kid', 'kids', 'child', 'baby', 'daughter', 'son', 'instamum', 'mum', 'mother', 'instakids', 'igbaby', 'igkids', 'instakids', 'bunny', 'children', 'instaselfie', 'funny', 'love', 'friendship', 'smile', 'pretty', 'live', 'onedirection', 'profile', 'guy', 'look', 'boy', 'boys', 'gay', 'homo', 'food', 'girl', 'hot', 'sexy', 'cars', 'bride', 'girls', 'luxury', 'shoe', 'shoes', 'legs', 'leg', 'bikini', 'fashion', 'moda', 'me', 'selfie']
`

and the script liked and commented on a photo, which has:

- #baby
- #instakid
- #igbaby
and some others hashtags in the description of the photo.

do I have to specify the hashtags before each word in the 'dont_like' array?

**Comment by timgrossmann** [comment]
@nick-preda please save us (the collaborators) some work and read through the documentation...

It clearly says, that ```set_dont_like()``` means "I don't want to like posts that contain one of these".
The ```.set_ignore_if_contains()``` means "Even if the post contains one of the don't like ones, i still want to like it"

e.g.

```python
.set_dont_like('food', 'meat', 'milk')  #don't like posts about animal food
.set_ignore_if_contains('vegan') #like the post if vegan is in it even if it contains 'meat'
```
