### ISSUE TITLE
show more likes button not exist! we need to scroll bottom

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#851]
## Current Behavior
in get_active_users:
`               # if there is a button to show more likes
                more_likes = (
                    re.search(r'\b\d+ likes?\b', tmp_list[0].text, re.I)`

I don't see any "more likes" button and since that not all likes in image captured.

**Comment by sionking** [comment]
I mean there is 250 likes and only first 20 captured

**Comment by converge** [comment]
hey @sionking , it's a bit hard to understand, can you explain it better ?

**Comment by sionking** [comment]
when I use the set_unfollow_active_users it going over last x posts, trying to list all "active" users, users which liked my posts.
What really happens is that it only take the first 20, to see the others you need to scroll down, something not done in this script, so instaed of having 250 active users per post I get only 20.

Thanks.

**Comment by RomeoJuliett** [comment]
I'm still confused. You're saying that you want to unfollow anyone who hasn't been active on your last 20 pictures @sionking

**Comment by sionking** [comment]
last 7 pictures. instead of listing the total ppl that liked those picture it is only list the first 20 ppl in each picture (which have total likes of 250 ppl each picture!) So getting all active users is not working !!!

**Comment by sionking** [comment]
session.set_user_interact(amount=2, random=False, percentage=90, media='Photo')
session.interact_user_followers(userFollowlist, amount=1000, random=False)

This configuration should go over 2 of my account posts (last posts) and record all the users which did like. what accutually happenes is that the automation only passes over the first users since it is not scrolling to the bottom!

**Comment by converge** [comment]
Hello @sionking, you're not being clear here, ```set_dont_unfollow_active_users``` has no relation with ```set_user_interact``` and ```interact_user_followers```.

Last week we updated ```set_unfollow_active_users``` to ```set_dont_unfollow_active_users```, now it's clearer what this feature does.

When you say it's not scrolling down, it's true, ```set_dont_unfollow_active_users``` doesn't need to scroll down, it uses the left/right arrow to go to the next posts.

hope it helps.

**Comment by ortegafernando** [comment]
As this is very old, I have opened new one:

https://github.com/timgrossmann/InstaPy/issues/1819
