### ISSUE TITLE
abnormal Ram usage!

### ISSUE THREAD

**Issue by hoseinit** [InstaPy/InstaPy#854]
Hello,
I am currently using the latest version of the bot. 
The problem is when I run the script in a short time I will have all my 2Gig Ram filled with many processes named: 
"/opt/google/chrome/google-chrome --disable-background-networking --disable-client-side-phishing-detection
all the Ram and Swap will be filled and I can't do anything else with my VPS.
please help

**Comment by converge** [comment]
hey @hoseinit , we're working on it #826. Can you help us ? I tried to reproduce it without success.
