### ISSUE TITLE
What's wrong with my script

### ISSUE THREAD

**Issue by Sem7** [InstaPy/InstaPy#856]
Hi guys, 

Having issues with my script as soon as I am adding stuff. I am not a developer, just an enthusiast user looking forward to understand more about code so please, be patient! :) Leaving here the script I am trying to perform. It loads, Login OK and even performs around 15 likes. After that it closes. I'm pretty sure this must be the script. 

Thanks beforehand!

## InstaPy configuration

from instapy import InstaPy

insta_username = 'XXX'
insta_password = 'XXX'

# if you want to run this script on a server,
# simply add nogui=True to the InstaPy() constructor
session = InstaPy(username=insta_username, password=insta_password)
session.login()

# set up all the settings
session.set_upper_follower_count(limit=1500)
session.set_do_comment(True, percentage=10)
session.set_comments(['aMEIzing!', 'Nicey!', 'love your stuff', 'love this one'])
session.set_dont_include(['XXX'])
session.set_dont_like(['hotgirl', 'selfie', 'girl', 'hot'])

# do the actual liking
session.like_by_tags(['roamtheplanet', 'schooloftravel', 'tropicalvibes', 'wanderfolk', 'beautifuldestinations'], amount=100)

session.set_do_follow(enabled=True, percentage=40, times=1)

session.like_by_feed(amount=200, randomize=True, unfollow=True, interact=True)

# end the bot session
session.end()

**Comment by dreamyUB** [comment]
We all have this problem, check it out thin its the same thing #724
