### ISSUE TITLE
"Load button not found"

### ISSUE THREAD

**Issue by amauryleproux** [InstaPy/InstaPy#857]
Hi Guys, does anyone got this error?

When I launch the command "python quickstart.py" I got the message "Load button not found, working with current images!" and so I've got only 10-15 images to like :/

Cheers

**Comment by diveu** [comment]
Got this one too.

**Comment by amauryleproux** [comment]
Do you think it's instagram who block this button when we make too much request in a short time?

**Comment by diveu** [comment]
@amauryleproux Nah, I guess Instagram changed smth and now we should probably change the classname or simply scroll down for additional pics to load

**Comment by diveu** [comment]
I found out that even though there is still a style section for this button, it's not present on the page. So the fix would be the removal of this part and doing smth like "scroll down -> scroll back -> check whether new images were loaded or not -> continue"

**Comment by dreamyUB** [comment]
We all have this problem #724 as I mentioned few times this problem is really annoying

**Comment by diveu** [comment]
And another update: as discussed in #724 scrolling down and up works just fine. I'll try (once more) to make a pull request, but I'll probably need some suggestions about it. How is it common? Should this scrolling method be an exception?

**Comment by converge** [comment]
@diveu that's great! tell me if you need some help, I'm at Slack (link in readme). To make it easier for you, just focus in what works for you, after test it and try using other logins (someone could help you testing).

**Comment by amauryleproux** [comment]
the #724 solution works perfectly : 
in the instapy/like_util.py add 

at the top: "import math"
in the "get_links_for_tag" / "except" block: 
for i in range(int(math.ceil(amount/12))):
            browser.execute_script(
                "window.scrollTo(0, document.body.scrollHeight);")
            sleep(2)

**Comment by kuzne4eg** [comment]
OK
Now just copy-paste on each "load button" in like_util and everything works properly.

**Comment by converge** [comment]
it's already merged, you guys just need to update InstaPy

**Comment by gitpatrickhub** [comment]
@converge I merged and the issue is fixed except when I use Interact_user_followers. Anyone else having the issue after merge with this method?

**Comment by kuzne4eg** [comment]
Yes, but its fixed with copy/paste load button on each “not found” in like_util
@timgrossmann could merge it, I think you understand what am I talking about

**Comment by converge** [comment]
@kuzne4eg I do understand, only like_by_tags is using the bug fix, like by location for example it's not patched. There is a PR #862 on the way, but we need help there (at comments).

**Comment by kuzne4eg** [comment]
Wrong!
Line 79, 171, 291

**Comment by Sillanmaki** [comment]
Yes this needs to be updated also to get_links_for_location and get_links_for_username😄  Works fine in there also.

**Comment by converge** [comment]
hello @kuzne4eg, sorry I didn't got it, what's wrong ?
check it out: https://github.com/timgrossmann/InstaPy/pull/862

#881 fix fixing like_by_feed , can anyone help testing it ?

**Comment by ghost** [comment]
How do I update Instapy? pip update Instapy?

**Comment by converge** [comment]
@Niels1990 best way is cloning it, and doing ```git pull```

**Comment by converge** [comment]
hey guys, there is a new PR for fixing this issue, can anyone help testing it ? #888

**Comment by Jhhoo** [comment]
Still receiving the 'Load button not found' issue after the latest pull

**Comment by converge** [comment]
Hello @Jhhoo , we need your help to test #888.

**Comment by Jhhoo** [comment]
hey @converge, I've done the latest Git Pull, does it include test #888 ? Is there anything I'm missing?

**Comment by converge** [comment]
@Jhhoo take a look at #888 (command line instructions)

**Comment by converge** [comment]
someone with this issue yet ?
