### ISSUE TITLE
Like amount reduced?

### ISSUE THREAD

**Issue by Mattes85** [InstaPy/InstaPy#858]
Currently i face with the Problem that the amount of the liking would not be used greater then 12. Exact this Count are the first results of searching by an specific HashTag, without clicking "Load more" Button. If the script tries to do so, Chrome Report in the Center of the footer "Failed to load RETRY. Tried it on 2 different machines, but there is the same Problem. Could it be something like an ban or else? 

>Error message in Shell: Load button not found, working with current images! 

If i search manualy for an Hashtag, it loads the first 12 Posts, after Scrolling down it loads automatically, but the old load more button is not shown.
I use the script for two accounts, the first one has the issue since thursday, the other from today. 

Any ideas?

## InstaPy configuration
I am using InstaPy on Windows 10 with Chrome @ Version 62.0.3202.75 (Official Build) (64-bit)

**Comment by dreamyUB** [comment]
Check it out I think its the same problem, its so annoying #724

**Comment by Mattes85** [comment]
Correct, i face the same issues!

**Comment by timgrossmann** [comment]
@dreamyUB Well, good thing that there is [Bountysource](https://www.bountysource.com/issues/51124883-like-amount-reduced) where you can easily and quickly add a bounty to that problem and I'm pretty sure that it will be resolved in no time :wink:
