### ISSUE TITLE
Getting pyvirtualdisplay error.

### ISSUE THREAD

**Issue by sankalpsingha** [InstaPy/InstaPy#86]
Running it in my Ubuntu Server raises error :
```
root:~/InstaPy# pip install pyvirtualdisplay
Requirement already satisfied: pyvirtualdisplay in /usr/local/lib/python3.4/dist-packages
Requirement already satisfied: EasyProcess in /usr/local/lib/python3.4/dist-packages (from pyvirtualdisplay)
root:~/InstaPy# python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 6, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay
```

**Comment by timgrossmann** [comment]
@sankalpsingha 
```bash
pip install pyvirtualdisplay
```

....

Please follow the instructions and just do a 

```bash
pip install .
```

**Comment by sankalpsingha** [comment]
I did. I am still getting the error.

```
Processing /root/InstaPy
  Requirement already satisfied (use --upgrade to upgrade): instagram-py==0.0.1 from file:///root/InstaPy in /usr/local/lib/python3.4/dist-packages
Requirement already satisfied: selenium==2.53.6 in /usr/local/lib/python3.4/dist-packages (from instagram-py==0.0.1)
Requirement already satisfied: clarifai==2.0.20 in /usr/local/lib/python3.4/dist-packages (from instagram-py==0.0.1)
Requirement already satisfied: pyvirtualdisplay in /usr/local/lib/python3.4/dist-packages (from instagram-py==0.0.1)
Requirement already satisfied: future==0.15.2 in /usr/local/lib/python3.4/dist-packages (from clarifai==2.0.20->instagram-py==0.0.1)
Requirement already satisfied: Pillow==2.9.0 in /usr/local/lib/python3.4/dist-packages (from clarifai==2.0.20->instagram-py==0.0.1)
Requirement already satisfied: requests==2.13.0 in /usr/local/lib/python3.4/dist-packages (from clarifai==2.0.20->instagram-py==0.0.1)
Requirement already satisfied: configparser==3.5.0 in /usr/local/lib/python3.4/dist-packages (from clarifai==2.0.20->instagram-py==0.0.1)
Requirement already satisfied: jsonschema==2.5.1 in /usr/local/lib/python3.4/dist-packages (from clarifai==2.0.20->instagram-py==0.0.1)
Requirement already satisfied: EasyProcess in /usr/local/lib/python3.4/dist-packages (from pyvirtualdisplay->instagram-py==0.0.1)
root:~/InstaPy#
root:~/InstaPy# python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 6, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay
```

**Comment by timgrossmann** [comment]
Do you run it locally?
http://stackoverflow.com/questions/27109176/importerror-no-module-named-display

**Comment by bigdropgr** [comment]
Hi @timgrossmann, I run it on CentOs VPS but I get the same error.

**Comment by timgrossmann** [comment]
@sankalpsingha @bigdropgr 

apt list --installed | grep Xvfb

Make sure Xvfb is installed

**Comment by wizarduk** [comment]
im getting the same issue

**Comment by converge** [comment]
@wizarduk what's your python version ?

**Comment by wizarduk** [comment]
This is the error @converge 

 python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/root/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/root/InstaPy/instapy/instapy.py", line 8, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay
root@sam:~/InstaPy# python3 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 8, in <module>
    session = InstaPy(username=insta_username, password=insta_password)
  File "/root/InstaPy/instapy/instapy.py", line 106, in __init__
    self.set_selenium_local_session()
  File "/root/InstaPy/instapy/instapy.py", line 152, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 2.6.32-042stab125.3 x86_64)

**Comment by converge** [comment]
@wizarduk have you tried it ?
```pip3.4 install pyvirtualdisplay```

**Comment by wizarduk** [comment]
@converge says this

Requirement already satisfied: pyvirtualdisplay in /usr/local/lib/python3.4/dist-packages
Requirement already satisfied: EasyProcess in /usr/local/lib/python3.4/dist-packages (from pyvirtualdisplay)

**Comment by rotohun** [comment]
I had the same issue, I used pip instead of pip3* and then installed each one individually.

**Comment by rotohun** [comment]
Then started the script using python instead of python3 to use previous python download and installs.

**Comment by wizarduk** [comment]
@rotohun how did u do this ?

**Comment by converge** [comment]
the point is, this error occurs because python version and pip version are differents. for example python command points to python2.7 and pip points to pip3.6 for example, in this way python can't localize the 2.7 version of pyvirtualdisplay.

the fix is, use same version for python and pip, if your

```python --version``` shows 3.6, you should use pip3.6 and so on.

**Comment by wizarduk** [comment]
@converge thanks its sorted i made a silly mistake.
