### ISSUE TITLE
Can't unfollow more than 246 users.

### ISSUE THREAD

**Issue by Namaslayer** [InstaPy/InstaPy#861]
I've got the following unfollow script trying to run via crontab on an Ubuntu Server.

<img width="533" alt="screen shot 2017-11-03 at 10 57 00 pm" src="https://user-images.githubusercontent.com/31394074/32402863-61487b6e-c0ea-11e7-83a8-301d570e2cdb.png">

However it seems to always crash after unfollowing 246 users. exactly at that number everytime.

Here's the error I get. What does this mean?

<img width="562" alt="screen shot 2017-11-03 at 10 55 13 pm" src="https://user-images.githubusercontent.com/31394074/32402869-7f0a11d0-c0ea-11e7-9b5c-a19005ffb208.png">

**Comment by converge** [comment]
hey @Namaslayer , it's a chromedriver bug, youre using 2.29 version, pls update it to latest version and tell us if it fixes the issue.

**Comment by Namaslayer** [comment]
@converge oh ok.

If I run the following commands, will that update it to the latest version?

<img width="671" alt="screen shot 2017-11-04 at 9 42 05 am" src="https://user-images.githubusercontent.com/31394074/32407320-814cb376-c144-11e7-983a-32f35c7b6fad.png">

**Comment by converge** [comment]
@Namaslayer that's chrome, did you cloned instapy? git pull does the work. update your chrome driver too, youre using 2.29, there is some bug fix in the 2.33

**Comment by Namaslayer** [comment]
@converge ok. Did the git pull. Does that update chrome driver though? I'm not sure how to do that.

Thanks for your help!

**Comment by ghost** [comment]
@Namaslayer you need to download the chromedriver from [here](https://sites.google.com/a/chromium.org/chromedriver/downloads). Then put the extracted file in the assets folder within the instapy folder. 

Start a new session and it should be good to go if you've done the pull.

**Comment by Namaslayer** [comment]
Awesome! I think I’ve got it.

running it now. Fingers crossed this solves the problem.

Thanks everyone.

**Comment by Namaslayer** [comment]
@converge so the updates make the bot run cleaner (no memory leaks and sessions are closing instead of crashing) But I still can't get it to unfollow more than 246 users in one session, even though it's set to unfollow 2000

<img width="464" alt="screen shot 2017-11-05 at 8 56 08 am" src="https://user-images.githubusercontent.com/31394074/32416993-32d78a90-c207-11e7-8ef7-e7d56cb06848.png">


Any thoughts on why this might be happening?
