### ISSUE TITLE
ChromeDriver unexpectedly exited. Status code was: -11

### ISSUE THREAD

**Issue by amauryleproux** [InstaPy/InstaPy#863]
I'm trying to launch the script on my Ubuntu 14.04 Server by doing this:
"python3 quickstart.py" but I got this error:
"selenium.common.exceptions.WebDriverException: Message: Service ./assets/chromedriver unexpectedly exited. Status code was: -11"

I already read others issues but still got the error when I try the solutions...
Do you have any ideas, please?

**Comment by amauryleproux** [comment]
<UPDATE>

So now I'm launching it without sudo but I've got this error:

Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form/span/button[text()='Log in']"}

**Comment by converge** [comment]
hey @amauryleproux , how is your quickstart.py file?

**Comment by amauryleproux** [comment]
Hi @converge this is my file: 

from instapy import InstaPy
 
   insta_username = '********'
   insta_password = '********'

   session = InstaPy(username=insta_username, password=insta_password, nogui=True)
   session.login()

   session.set_upper_follower_count(limit=1500)
   session.set_do_comment(True, percentage=50)
   session.set_comments(['Really cool!', 'I like this!', 'Love that!'])
  session.set_dont_include(['friend1', 'friend2', 'friend3'])
  session.set_dont_like(['girl','hot'])
  session.set_do_follow(enabled=True, percentage=30, times=1)
  session.like_by_tags(['london', 'paris', 'berlin', 'dublin', 'barcelona', 'lisboa'], amount=100)
  session.end()

**Comment by converge** [comment]
@amandoabreu did you followed these steps ?

https://github.com/timgrossmann/InstaPy/blob/master/docs/How_To_DO_Ubuntu_on_Digital_Ocean.md

sounds like chrome is not installed (not chromedriver)

**Comment by amauryleproux** [comment]
Yes in fact I reinstalled everything and it was good, thanks
