### ISSUE TITLE
Only liking 12 posts

### ISSUE THREAD

**Issue by amoffitt123** [InstaPy/InstaPy#865]
Hello all,

My bot was successfully running for a while now and suddenly it only likes 12 posts per tag even though I have it set to like 115. I run it and then it says 1/12, then 2/12 and so on, but it used to be 1/115 and so on. I'm not sure what happened. Thanks

**Comment by amauryleproux** [comment]
did you try this solution: #857

**Comment by converge** [comment]
if you update InstaPy, there is a bug fix for like_by_tags(), there is another fix on the way.

**Comment by ghost** [comment]
How do I update InstaPy? I am new to Python so installing packages is new to me. Sorry.

**Comment by converge** [comment]
#881 fixes like_by_feed (load button problem and some minor issues in this feature)

**Comment by amoffitt123** [comment]
@Niels1990 you could try going to the directory in the terminal and running sudo apt-get update but that never works for me. I usually just restart and re download everything and it's the newest version.

**Comment by juandes** [comment]
@converge is #881 suppose to fix the problem? I'm trying the current version from master and I am still encountering the same issue. Any other idea? Thanks.

**Comment by RomeoJuliett** [comment]
@juandes  I'm currently experiencing the issue on my Windows machine and am trying to debug and give @converge a solid answer as to why it's happening.
