### ISSUE TITLE
add_user_to_backlist() error

### ISSUE THREAD

**Issue by pixelcatcher** [InstaPy/InstaPy#870]
## Current Behavior
Logged in successfully!
Campaign stuttgart first run
Tag [1/1]
--> b'stuttgart'
[1/100]
Image from: b'flohmarkt_karlsplatz'
Number of Followers: 109
Link: b'https://www.instagram.com/p/BbFtArvF_0A/?tagged=stuttgart'
Description: b'Pferdle in mehrfacher Ausfertigung und auch ein \xc3\x84ffle. Heute auf dem Flohmarkt Karlsplatz gesehen. Sind halt echte Stuttgarter und gehen zum Verkauf auf den Karlsplatz.  #flohmarkt #fleamarket #flohmarktkarlsplatz #flohmarktinstuttgart #pferdle #pferdleund\xc3\xa4ffle #schleich #stuttgart'
--> Image Liked!
Traceback (most recent call last):
  File "fks.py", line 21, in <module>
    session.like_by_tags(['stuttgart'], amount=100)
  File "/Users/pixel/Downloads/InstaPy-master/instapy/instapy.py", line 587, in like_by_tags
    self.browser, user_name, self.blacklist
  File "/Users/pixel/Downloads/InstaPy-master/instapy/like_util.py", line 501, in like_image
    add_user_to_blacklist(browser)
TypeError: add_user_to_blacklist() missing 3 required positional arguments: 'username', 'campaign', and 'action'

```
## InstaPy configuration
from instapy import InstaPy

insta_username = 'xxxxxx'
insta_password = 'xxxxxx'

# if you want to run this script on a server,
# simply add nogui=True to the InstaPy() constructor
session = InstaPy(username=insta_username, password=insta_password)
session.login()

# set up all the settings
session.set_upper_follower_count(limit=2500)
session.set_do_comment(True, percentage=10)
session.set_comments(['wow!', 'thanks for sharing', 'beautiful light!'])

# do the actual liking
session.set_blacklist(enabled=True, campaign='stuttgart')
session.set_do_comment(True, percentage=50)

session.like_by_tags(['stuttgart'], amount=100)
session.end()
```

**Comment by converge** [comment]
hello @pixelcatcher , we merged the fix some hours ago.
pls update InstaPy and tell us if it's alright.

**Comment by pixelcatcher** [comment]
I'll give it a try. thanks! the funny thing is I just downloaded a few hours ago :)

**Comment by pixelcatcher** [comment]
awesome now it works!

**Comment by converge** [comment]
@pixelcatcher that's great! We had some problem merging it, and fixed it some minutes later :octocat:
