### ISSUE TITLE
Error: (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.16299 x86_64) what should i do?

### ISSUE THREAD

**Issue by kenedy86** [InstaPy/InstaPy#871]
![default](https://user-images.githubusercontent.com/33388585/32412860-fa4eb198-c20c-11e7-858b-0f05f920d16e.png)

**Comment by kenedy86** [comment]
what should I do?

**Comment by dreamyUB** [comment]
Update chrome driver https://sites.google.com/a/chromium.org/chromedriver/downloads
Don't forget to put it in Instapy -> assets

**Comment by converge** [comment]
hi @kenedy86 , did you fix it?

**Comment by davidrocket** [comment]
Try to kill the dangling chrominum processes!
