### ISSUE TITLE
Wrong login data error, then script crashes when phone OTP requested

### ISSUE THREAD

**Issue by gaelangu** [InstaPy/InstaPy#872]
After `quickstart.py` is run with the correct login credentials, my chrome browser opens and the script logs in for me but when I reach the page where the phone OTP is requested, the browser closes and the script throws up the following message:

`Wrong login data!`

`Session ended`

`Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x1059d8e80>>`

`ImportError: sys.meta_path is None, Python is likely shutting down`

I have already logged in to Instagram on my browser, but the same error occurs as if I haven't logged in before. Do I need to deactivate 2-factor authentication for the script to work?

Edit: I am on macOS 10.13.1 if that helps...

**Comment by dreamyUB** [comment]
Yea try to deactivate 2FA

**Comment by gaelangu** [comment]
@dreamyUB ok that worked.. but was hoping for a workaround if that was possible. thanks!
