### ISSUE TITLE
Using another process

### ISSUE THREAD

**Issue by kaanair** [InstaPy/InstaPy#873]
I downloaded again instapy.git for fixing load issue but I got this issue.
Also I would like to thank for  Tim for this great script.

## Expected Behavior
Traceback (most recent call last):
  File "C:\Users\user\Desktop\InstaPy-master\quickstart.py", line 9, in <module>
    session.login()
  File "C:\Users\user\Desktop\InstaPy-master\instapy\instapy.py", line 186, in login
    self.switch_language):
  File "C:\Users\user\Desktop\InstaPy-master\instapy\login_util.py", line 11, in login_user
    update_activity()
  File "C:\Users\user\Desktop\InstaPy-master\instapy\util.py", line 85, in update_activity
    shutil.move(tmpfile.name, './logs/activity.csv')
  File "C:\Python27\lib\shutil.py", line 303, in move
    os.unlink(src)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\user~1\\appdata\\local\\temp\\tmpqbmadb'

**Comment by converge** [comment]
hello @kaanair , I tested it, it's really not working in Windows.

**Comment by converge** [comment]
I looked at it yesterday, and as I said before, unfortunately it's really not working in Windows. When I was developing the feature I didn't tested it on Windows and wasn't expecting Windows problem when copying files. There is a way to fix it, but it would be a headache for Windows user manually download more libs(win32files), choose the right architecture and python version to make it work.

There is a PR #875 on the way, it will avoid Windows users to have this feature for now (to not break InstaPy on Windows, the situation we have at the moment).

That said, my first approach was to be as simples as possible storing so few data, and not creating a real database structure to save few informations, but... after this issue, I/we have to rethink the sqlite idea. I'll begin it as soon as I have some free time.

My apologies for the issue.
