### ISSUE TITLE
Create comments based on like tag

### ISSUE THREAD

**Issue by Radzam** [InstaPy/InstaPy#874]
I would like to create different comments for different tags that are being liked. What would the best way be to do this?

**Comment by balakedev** [comment]
@Radzam I see what you're saying. If a photo has #beach attached to it, you could confidently tell InstaPy to comment "the beach looks amazing!".

I honestly think you'd be better off having high fidelity Clarifai comments. I use clarifai to the absolute extreme and im getting great results. Just bee super specific with comments relating to particular things. 

For example:

`session.clarifai_check_img_for(['hike', 'adventure', 'mountain', 'landscape','alps'], comment=True, comments=['Wow look at the view!', 'It looks so nice!', 'Wish we were there!','What a climb!', 'Amazing views', '#views'])`

`session.clarifai_check_img_for([ 'iceberg', 'ice'], comment=True, comments=["Looks cold!", "Just a little bit chilly? haha"])`
 
`session.clarifai_check_img_for(['fruit', 'healthy', 'blueberry', 'strawberry','drink','vegetable','salad','citrus','rice','watermelon','smoothie','berry','apple','jam','tofu','vegan','lettuce'], comment=True, comments=['Looks so yum!', 'Looks so nice!', 'Yummm','Looks fab', "OMG yum!", 'Looks so yum','Want!'])
`

**Comment by timgrossmann** [comment]
@blakemmw You're right, I did the same

**Comment by wizarduk** [comment]
@blakemmw does the work fine in instapy Clarifai comments?

**Comment by bigmayhem87** [comment]
@blakemmw I'm trying to leverage this same code. Is there a way to ONLY comment on images with certain tags? When I use that the check_img_for function without also using set_do_comment(enabled=True), my script won't comment at all. If I have set_do_comment enabled (at 100 percent just for testing purposes), if an image doesn't have the specified tags, the script will post a generic comment such as "looks good!"

My aim is to only comment on images with the tags I specify.
