### ISSUE TITLE
Like pictures by list of users functionality? 

### ISSUE THREAD

**Issue by tylergit2** [InstaPy/InstaPy#879]
Is there anyway currently to like every user's first post from a list of users? This functionality would be super useful for Instagram engagement groups.

**Comment by tylergit2** [comment]
How hard would it be to do something like this (http://likelistbot.com/faq/) with Instapy?

**Comment by tylergit2** [comment]
```python
from instapy import InstaPy
import os
session = InstaPy(username='***', password='***')
session.login()

session.set_do_follow(enabled=False, percentage=50)
session.set_comments(["Cool", "Super!"])
session.set_do_comment(enabled=False, percentage=80)
session.set_do_like(True, percentage=100)
session.interact_by_users(['garyvee', 'tailopez'], amount=1, random=False)

session.end()
```
---

I got this to work. Super useful and with the comments it's even better than the paid bots on the market for engagement groups!

**Comment by gdesiato** [comment]
Hi! I am trying your code and it is really cool.
But all the process to like one photo is very slow on my computer. It is like that the step "getting xxxx image list_" is very heavy to perform and it takes a lot of time. Do you have the same issue?
Thank you

**Comment by yozaam** [comment]
>  But all the process to like one photo is very slow on my computer. It is like that the step "getting xxxx image list_" is very heavy to perform and it takes a lot of time. Do you have the same issue?

Did you try headless?
