### ISSUE TITLE
Feature Request: InstaPy PlugIns

### ISSUE THREAD

**Issue by converge** [InstaPy/InstaPy#880]
There is some nice features showing up everyday, some of then would be opcional, like Telegram integration, Twillo integration and dashboard for example.

Would it be nice, if we could easily install/load it through a plugin system.

we could use a Telegram plugin in this way for example:

```python
telegram_plugin = plugin_source.load_plugin('telegram_plugin')
telegram_plugin.send_msg('Session started')
```

or scrape data plugin for example:
```python
scraper = plugin_source.load_plugin('scrape_data_plugin')
scraper.do_scrape(account_names=True, account_followers=True, account_liked_posts=True)
```

what do you guys think ?

**Comment by flo1t** [comment]
i like this idea, especially the telegram implementation (but i don't know scrape data). monitoring woul'd be easier with this.

**Comment by converge** [comment]
@flo1t these are examples, we don't need to implement it, the main idea is to have a plugin feature.

**Comment by gitpatrickhub** [comment]
@converge I like the idea, would need some help modifying the text feature into the plugin format.

**Comment by converge** [comment]
@gitpatrickhub count on me!

**Comment by newme616** [comment]
great idea!
