### ISSUE TITLE
InstaPy keeps crashing

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#883]
Hi guys,

InstaPy keeps crashing.

Below is a screenshot
<img width="417" alt="instapy crash" src="https://user-images.githubusercontent.com/33132119/32487900-3d4ad810-c3ab-11e7-813c-40c0aa9fedef.PNG">

Thank you in advance!

**Comment by flo1t** [comment]
are you using the newest version?

**Comment by ghost** [comment]
@flo1t I'm new to Python so I could be wrong but what I did was in command prompt:
pip install InstaPy--upgrade

**Comment by flo1t** [comment]
i don't know the install steps, sorry. i just asked because there's no code like "comment_input[0].send_keys("\b")" in line 25 in comment_util.py. but in an earlier version it was on line 25.

i suggest to update instapy first.

**Comment by converge** [comment]
didn't know we had a pip package. I think it's outdaded as @flo1t said, download or clone it in the github page. as youre using Windows, apply this patch #875 while we dont fix it.

**Comment by timgrossmann** [comment]
@converge There is no pip package... It's some really old package from another guy that has nothing to do with Instagram :wink: 

@Niels1990 Please at least try to read the first 5 lines of the Readme...

**Comment by converge** [comment]
@Niels1990 did you fix it ?

**Comment by converge** [comment]
@Niels1990 please, reopen it if you still need some help.
