### ISSUE TITLE
How to turn off 'inappropriate'?

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#884]
Hi guys,

Almost every picture gets not liked because it is 'inappropriate'.

I use tags like 'fitness' . How do I turn 'inappropriateness' off?

**Comment by gedankenstrom** [comment]
@Niels1990 
Check your config file "session.set_dont_like(['pizza', 'girl'])" ...

**Comment by converge** [comment]
@Niels1990 , as @bjo3rns said, if you define a new ```set_dont_like``` it will overwrite the default
```python
self.dont_like = ['sex', 'nsfw']
```

it can be anything, for example:
```python
session.set_dont_like(['foo-bar'])
```
