### ISSUE TITLE
Correct configuration for Commenting Photo vs. Video?

### ISSUE THREAD

**Issue by gitpatrickhub** [InstaPy/InstaPy#885]
## Expected Behavior
For media= Photo use specified comments
For media = Video use specified comments

## Current Behavior
Randomly posts one of the comments from both sets regardless of media. 

Is the below the correct way to configure this?

## InstaPy configuration
````
session.set_comments([u':clapping_hands: :clapping_hands:', u':thumbs_up:', 'Sweet!'], media='Photo')
session.set_comments(['Sweet vid!', 'Nice edit!'], media='Video')
session.set_do_comment(True, percentage=33)
````
Raspbian Jessie
Python 3.5
Selenium 2.53.6
Firefox 52.3.0
Geckodriver 0.19.0

**Comment by converge** [comment]
I think the second
```python
session.set_comments(['Sweet vid!', 'Nice edit!'], media='Video')
````
overwrite the first set_comments, can anyone confirm it ?

**Comment by guifelix** [comment]
me too, although I'm not a python developer, I think the graphql is the problem. because it is used to find out which type of media it is currently seeing. I was looking in the instagram HTML and found a not so pretty solution to that: Videos has a "a" tag with "videoSpritePlayButton" class...
