### ISSUE TITLE
Making the bot harder to identify

### ISSUE THREAD

**Issue by AlainPilon** [InstaPy/InstaPy#89]
I think we should randomize all the numeric values used in the app (wait time, number of likes, comments, etc..) using a normal distribution. This would be more realistic of human behaviour. 

Any monitoring system would find it odd that the user is always linking exactly 50 images and always waiting 2 seconds between clicks... 

My idea would be to wrap any number into a lambda which would return the randomly normalized number.

Or am I too paranoid?

**Comment by timgrossmann** [comment]
I did a lot of the randomness with cron and the quickstart.py file. But you're right, this should probably be part of the tool

**Comment by pekapa** [comment]
I'm up for doing that as I was thinkg about it just yesterday.

**Comment by ToJen** [comment]
@pekapa same here

**Comment by AlainPilon** [comment]
same here... Push something and we can share ideas.

**Comment by timgrossmann** [comment]
@pekapa @ToJen @AlainPilon Feel free to make a PR with your changes.

**Comment by pekapa** [comment]
Just pushed #100 to help with this.

**Comment by eduardocalazansjr** [comment]
As i said, instagramweb seems to gather all the mouse/keyboard events via javascript.

I think that simulating the page movement is more efficient than random sleep times (also with the page loading times, it will be equivalent to a random sleep time).

Random sleep times without some page interaction will still flag as a bot.

Edit: Selenium has nice mouse movement features, using with random x, y values while doing the movement to the button will result in random times on pages.

[ref](https://seleniumhq.github.io/selenium/docs/api/py/webdriver/selenium.webdriver.common.action_chains.html)
