### ISSUE TITLE
commenting on the same photo each day

### ISSUE THREAD

**Issue by wizarduk** [InstaPy/InstaPy#890]
is there anyway to stop commenting on the same photo each day i only want to comment on it once ?

**Comment by diveu** [comment]
That seems strange, because in my case I get "already liked" message and that stops any further actions on photo.

**Comment by wizarduk** [comment]
@diveu this is not for photos likes this is for comments i have had several pictures that i have commented on 3 times now i only want it to comment once ?

So example 
day 1 comments on pic then 
day 2 comments on same pic 
day 3 comments on same picture again ??

**Comment by diveu** [comment]
Which method do you use? like_by_hashtags() with commenting on?

**Comment by wizarduk** [comment]
@diveu   session.like_by_tags

with comments on yes

**Comment by converge** [comment]
@wizarduk @diveu take a look at ```set_blacklist``` new feature

https://github.com/timgrossmann/InstaPy#blacklist-campaign

**Comment by wizarduk** [comment]
@converge so i need to add this line and all the tags to it ie 

session.set_blacklist(enabled=True, campaign='soccer_campaign' , 'test1')

**Comment by converge** [comment]
@wizarduk no.. let me know if the doc/readme isn't clear and how could we improve it.

https://github.com/timgrossmann/InstaPy#blacklist-campaign

**Comment by ugurozturk** [comment]
@converge i made session.set_blacklist(enabled=True, campaign='generic_campaign') . And gonna use this for all time. So i will not follow second time any person am i right ?

**Comment by converge** [comment]
@ugurozturk that's right
