### ISSUE TITLE
Best Practices for using the Clarifai API?

### ISSUE THREAD

**Issue by akcasoy** [InstaPy/InstaPy#891]
Do you guys have any best practices already about using the Clarifai API? Predict feature of this API is really awesome, but how can we use it effectively? 
As in the homepage of this project states, we can use it like "if there is food, lunch, dinner, comment Yummy!! etc.." But do you have some personal algorithms to handle this in a more clever way avoding any misbehaviour?  Like looking at the percentages etc.. I just wanted to hear from you how you all use it.

**Comment by sionking** [comment]
I would like to have some, since not already using it, I would like to see someone's code who does!
