### ISSUE TITLE
Why don't include function don't work with unfollow?

### ISSUE THREAD

**Issue by JacobSpruce** [InstaPy/InstaPy#892]
I wan't to unfollow everyone except users in don't include list. Am I doing something wrong?

----------------------------------------

```python
instapy import InstaPy

session = InstaPy(username='xxxxxx, password='xxxx')

session.login()

session.set_dont_include(['friend1', 'friend2', 'friend3'])
session.unfollow_users(amount=700)

session.end()
```

**Comment by converge** [comment]
hi @JacobSpruce , nothing wrong. We don't have this feature yet.

**Comment by JacobSpruce** [comment]
In my opinion, it would be a very vital feature. This would allow to preserve loyal followers and root out all unnecessary ones. Thanks for the reply and thumbs up!

**Comment by JacobSpruce** [comment]
In my opinion, it would be a very vital feature. This would allow to preserve loyal followers and root out all unnecessary ones. Thanks @converge for the reply and thumbs up!

**Comment by timgrossmann** [comment]
@JacobSpruce https://www.bountysource.com/issues/51318956-why-don-t-include-function-don-t-work-with-unfollow :wink:
