### ISSUE TITLE
Soft Ban Commenting

### ISSUE THREAD

**Issue by 0xkvai** [InstaPy/InstaPy#893]
## Expected Behavior
Script gets executed daily on digital ocean server with the following crontab
*/30 7-22 * * * cd /root/InstaPy && python3.5 fileName.py

## Current Behavior
instagram asked if the account is hacked and made me reset the password, also Instagram set a temp comment ban on the account

## Possible Solution (optional)
should I adjust my crontab schedule?
or
decrease the tags and amount

## InstaPy configuration
.like_by_tags(['tagOne','tagTwo','tagThree','tagFour','tagFive', 'tagSix', 'tagSeven'], amount=15) \

**Comment by AustineA** [comment]
I would say reduce the number of tags... I'm just curious what did you end up doing?

**Comment by 0xkvai** [comment]
yes,
after posting I realized that there were too many tags resulting in over commenting.
