### ISSUE TITLE
Like multiple photos per profile

### ISSUE THREAD

**Issue by jksyrek** [InstaPy/InstaPy#894]
Is it possible to like multiple photos per account? In the case the bot is looking for a hashtag, can I set the option to like not only one photo but also a few other of the same author?

**Comment by converge** [comment]
hello @jksyrek , it's possible, check the docs for better understanding: https://github.com/timgrossmann/InstaPy#instapy-available-features

**Comment by jksyrek** [comment]
As I've read that it is possible for the photos from thee feed using
```session.like_by_feed(amount=100, randomize=True, unfollow=True, interact=True)```
where `interact` visits the author's profile page of a certain post and likes a given number of his pictures, then returns to feed.

But I'm looking for such a option for the pictures on the hashtag search page. So basically `interact` flag for the `session.like_by_tags(['natgeo', 'world'], amount=10)` command.

Or basically something like  `session.interact_user_following(['natgeo'], amount=10, random=True)` but not for an user but for a hashtag. Like `interact_by_tag` function or something like that.

**Comment by converge** [comment]
hey @timgrossmann , should
```python
session.set_user_interact(amount=3, random=True, percentage=100, media='Photo')
session.like_by_tags(['cyclingshoes'], amount=5)
```
do it ?

**Comment by timgrossmann** [comment]
@converge Yes, that should work out

**Comment by converge** [comment]
@jksyrek please, reopen it if you still need some help.
