### ISSUE TITLE
Could you please make the cross platform GUI for 32 bit systems too

### ISSUE THREAD

**Issue by Mehnou** [InstaPy/InstaPy#895]

**Comment by converge** [comment]
hello @Mehnou , the right place to create this issue is at https://github.com/Nemixalone/GUI-tool-for-InstaPy-script.

**Comment by Mehnou** [comment]
I'm not talking about the third party GUI

**Comment by converge** [comment]
@Mehnou alright. pls extend your question, give us details about your issue.

**Comment by timgrossmann** [comment]
@Mehnou This is still the wrong place to post it...
@ahmadudin is the owner of that GUI repository so you should open that issue there.

As always, begging is good but putting a [Bounty](https://www.bountysource.com/issues/51354112-could-you-please-make-the-cross-platform-gui-for-32-bit-systems-too) on that issue will not only make you get the feature but also will help the developer get something in return for his time!
