### ISSUE TITLE
Ideas for marketing

### ISSUE THREAD

**Issue by sebmer-com** [InstaPy/InstaPy#896]
## Expected Behavior

Crawl the best influencers from hashtags and cities

## Current Behavior

not possible

## InstaPy configuration

How would it be to find out, who is the person with the most followers on the posted hashtag?

Backround for the idea: 
What are local businesses looking for?  People out from their area. People from the city or town where they sell products (food, hairstyle etc.) 

Well here comes the idea. Who is the person with the most followers in my region/area or so? 
The InstaPY searches for geoTag or for a Hashtag for example #berlin it checks out every posted picture from the last 24 hours. Next step it saves all "posters" of the posts and checks theier followers. 

What does it exactly check? it checks the followers of the posting person. It checkes how many people use the same hashtag or comes from the same geoTag (from the same region as the posting person) and writes it into a simpel csv. 

What do we get here?
We got a powerful marketing tool to find out whos the biggest influencer for my product in my region. 

Well i am sharing this idea with you. because i have basic knowlegde but not the skills to devolp this. 

Thanks :) 

kind regards Sebastian

**Comment by converge** [comment]
@Basti922 that's a good feature, but it's hard work. A [Bounty](https://www.bountysource.com/issues/51354671-ideas-for-marketing) for it would be great, I'm sure more people would like to see this feature in action. It's a step forward adding more intelligence to InstaPy.
