### ISSUE TITLE
Smart Hashtags

### ISSUE THREAD

**Issue by converge** [InstaPy/InstaPy#897]
Hey guys, I like this idea, and would like to know if you like it also.

```python
# generate relevant new tags based in each initial tag. 
session.set_smart_hashtags(['music', 'rockband', 'guitarhero'], limit=3, sort='random/top', 
show_tags=True)
# for example, tag music could generate a list like: #guitargod, #guitarlegend, #guitarsolo
# like_by_tag would have this new parameter (use_smart_hashtags), and like each tag 10 times.
like_by_tag(amount=10, use_smart_hashtags=True)
```

Extending it a little:

```python
sort='random' # get a list of generated hashtags randomically
sort='top' # will sort the most relevant generated tags
show_tags=True # will show generated tags at console and logFile.txt
```

What do you think ?

[![](https://api.gh-polls.com/poll/01BYH7JA22PRZ58F868S4CM2DY/Good%20Idea)](https://api.gh-polls.com/poll/01BYH7JA22PRZ58F868S4CM2DY/Good%20Idea/vote)
[![](https://api.gh-polls.com/poll/01BYH7JA22PRZ58F868S4CM2DY/Bad%20Idea)](https://api.gh-polls.com/poll/01BYH7JA22PRZ58F868S4CM2DY/Bad%20Idea/vote)

**Comment by timgrossmann** [comment]
@converge Maybe we can get some ideas on how to easily implement this from their "Hashtag generator" 
https://github.com/MoritzGruber/instabot

**Comment by converge** [comment]
#919 can someone test it ? so we can merge.

**Comment by converge** [comment]
working and merged, more info in the docs.
