### ISSUE TITLE
How to use bot filters 

### ISSUE THREAD

**Issue by justinf102** [InstaPy/InstaPy#902]
Like filter out private users, bots, users without profile pic etc

**Comment by converge** [comment]
unfortunately we don´t have it. Do you know [Bounty Source](https://www.bountysource.com/teams/instapy) ?

**Comment by justinf102** [comment]
No

**Comment by timgrossmann** [comment]
@justinf102 Feel free to post a bounty on this!
https://www.bountysource.com/issues/51400049-how-to-use-bot-filters
