### ISSUE TITLE
[Feature request] Extract data when commenting

### ISSUE THREAD

**Issue by Naramsim** [InstaPy/InstaPy#903]
Hi, Instapy could extract automatically the name of the owner of a photo that has to be commented and gave it back to us, so we can include the owner name in our comment.

**Comment by timgrossmann** [comment]
@Naramsim Yes, that is a great idea!

Shouldn't be too hard to do, are you interested in trying it out?

**Comment by converge** [comment]
count on me if you need some help.

**Comment by Naramsim** [comment]
I will let @converge do the work, I'm busy right now

**Comment by timgrossmann** [comment]
@Naramsim Well... Make sure to at least support him with a Bounty if you don't want to implement it yourself :wink:

**Comment by justinf102** [comment]
how do you update the bot??

**Comment by gitpatrickhub** [comment]
From command line navigate to your InstaPy directory and type git pull

**Comment by sionking** [comment]
We need more complex commenting mechanisem anyway... After 20 same comments instagram will know you are a bot.

**Comment by ghost** [comment]
How did this go?

**Comment by converge** [comment]
@ffext waiting someone to do it, or some Bounty on BountySource.

**Comment by timgrossmann** [comment]
@Naramsim @justinf102 https://www.bountysource.com/issues/51408855-feature-request-extract-data-when-commenting
