### ISSUE TITLE
Unfollow by list as the follow function

### ISSUE THREAD

**Issue by mehdi691** [InstaPy/InstaPy#904]
Hey Friends,

I would like to know if it is possible to unfollow people by enter a list as the following function. For example;

accs = ['friend1','friend2']

session.unfollow_users_by_list(accs)

Thank you very much

**Comment by timgrossmann** [comment]
@mehdi691 Sorry, that's not possible at the moment

**Comment by Abzidian** [comment]
It should be possible given that you have to reverse engineer the codes for follow_users_by_list. Find the source of it all and change the buttons and wordings of it. Basically, to make it easier, it can be defined using def.
