### ISSUE TITLE
Did they change layout again?

### ISSUE THREAD

**Issue by FBosler** [InstaPy/InstaPy#906]
## Expected Behavior
Bot working and not crashing
## Current Behavior
I just set up the bot on a fresh server and tried running it. However, it crashes with the following error: 
```
Unable to locate element: {"method":"xpath","selector":"/html/body/div[4]/div/div/div[2]/div/div[2]"}
  (Session info: chrome=62.0.3202.89)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.4.0-98-generic x86_64)
```
## Possible Solution (optional)
Something like here https://github.com/timgrossmann/InstaPy/issues/730
## InstaPy configuration
Latest installation according to "ubuntu how to"

**Comment by Geczy** [comment]
In unfollow_util.py find `//header/div[2]//li[3]` replace with `//header/section//li[3]`

**Comment by FBosler** [comment]
Seems to be working ... thx! I'll close the issue as soon as I know for sure.

**Comment by timgrossmann** [comment]
@Geczy Could you quickly PR that, please? :wink:

**Comment by converge** [comment]
hey @timgrossmann , #915 already merged it, we're too fast :octocat:

**Comment by timgrossmann** [comment]
@converge You're awesome!
