### ISSUE TITLE
set_lower_following_count

### ISSUE THREAD

**Issue by max-si-m** [InstaPy/InstaPy#908]
Hello, 
what do you think about limitation by following? It can be very helpful:
~~~
.set_lower_following_count(limit = 1000)
~~~

# Behavior
If the following count more than `1000` don't interact with user

**Comment by converge** [comment]
@max-si-m good idea, that worth a [Bounty](https://www.bountysource.com/teams/instapy)

**Comment by fbleite** [comment]
Hi Everyone,

I'll try to work on this one :)

Thanks!
