### ISSUE TITLE
I am trying to "PULL REQUEST" my local changes, but getting "Authentication Failed"

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#909]
"Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository."

I am new to GitHub, I am working with mercurial at work, Anyone can assist?
I have a new branch based on master, I am working with windwos GUI.

Thanks.

**Comment by ugurozturk** [comment]
@sionking if you are trying to push at timgrossmann/InstaPy then you probabbly doesn't have Authentication. You have to Fork the project to your profile. Then do set remote url to your fork. Do push then do new pull request

**Comment by sionking** [comment]
Thanks! I think I did it :)

**Comment by converge** [comment]
If you guys have this issue in the future, use the https version to clone it:

```
git clone https://github.com/timgrossmann/InstaPy.git
```
