### ISSUE TITLE
can't understand what to do in step 4 

### ISSUE THREAD

**Issue by itsedomil** [InstaPy/InstaPy#916]
hi, 
im new to python and github and i cant understand how to do step 44, it says to edit the instapy.py file, but i dont find it anywhere on the github desktop, and cant see how to edit it as well. 
have anyone tried to make a youtube video explaining how to install the file and using it from a-z? 
if anyone is down to making one that will be awesome, and if anyone can help mewhere im stuck that will be great too :)
tnx in advance

**Comment by converge** [comment]
hi @itsedomil , it can help https://www.youtube.com/watch?v=I025CEBJCvQ

**Comment by itsedomil** [comment]
hi joao, I'm using mac as well but I can't really understand how to do all
the steps, do i need to download python for mac before i start the process?
And how can I activate it, I'm sorry but I'm really confused :/
Is there any chance you can make a video explaining everything from start
to end, including all the downloading? It will help me alot
Tnx in advance,
Edomil

**Comment by ugurozturk** [comment]
@itsedomil https://github.com/timgrossmann/InstaPy#getting-started everything is written.

Example : First step "git clone https://github.com/timgrossmann/InstaPy.git" so you need git on your mac to go. its same for python "python setup.py install" so you need python as well.

**Comment by RomeoJuliett** [comment]
@itsedomil do you still need help with this?

**Comment by converge** [comment]
@itsedomil please, reopen it if you still need some help.
