### ISSUE TITLE
Blacklist Problem

### ISSUE THREAD

**Issue by hestuppfodarn** [InstaPy/InstaPy#917]
> [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=51493944)](https://www.bountysource.com/issues/51493944-blacklist-problem?utm_source=51493944&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Hi, 
I'm not succeeding with my blacklist implementation,
Could someone please advise me on this?
```python
from random import sample
from instapy import InstaPy
import random

insta_username = 'xx'
insta_password = 'yy'

users = [
 'x',
 'y'
]

amountLike = random.randint(50,60)
amountTags = random.randint(4,7)
amountLocations = random.randint(4,6)
percentFollow = random.randint(70,85)

InstaPy(username=insta_username, password=insta_password, nogui=False) \
        .login() \
        .set_lower_follower_count(limit=20) \
        .set_upper_follower_count(limit=7000) \
        .set_blacklist(enabled=True, campaign='soccer_campaign')\
        .set_user_interact(amount=2, random=True, percentage=percentFollow, media='Photo') \
        .set_do_like(enabled=True, percentage=percentFollow) \
        .interact_user_followers(sample(users, 2), amount=amountLike, random=True) \
        .end()
```

ERROR MESSAGE:

/Users/xx/InstaPy/venv/bin/python /Users/xx/InstaPy-master/Blacklist.py
Logged in successfully!
Traceback (most recent call last):
  File "/Users/xx/InstaPy-master/Blacklist.py", line 35, in <module>
    .set_blacklist(enabled=True, campaign='soccer_campaign')\
AttributeError: 'NoneType' object has no attribute 'set_user_interact'
Campaign soccer_campaign first run

Process finished with exit code 1

**Comment by converge** [comment]
@hestuppfodarn try in this way:
```python
session = InstaPy(username=insta_username, password=insta_password, nogui=False)
session.login()
session.set_lower_follower_count(limit=20)
session.set_upper_follower_count(limit=7000)
session.set_blacklist(enabled=True, campaign='soccer_campaign')
session.set_user_interact(amount=2, random=True, percentage=percentFollow, media='Photo')
session.set_do_like(enabled=True, percentage=percentFollow)
session.interact_user_followers(sample(users, 2), amount=amountLike, random=True)
session.end()
```

**Comment by hestuppfodarn** [comment]
@converge it works, thanks.
I would love to add the date to the blacklist csv file, is there any way of doing this with a single line of code since it's already in the log/activity.csv?

thanks

**Comment by hestuppfodarn** [comment]
@timgrossmann @converge 
could you create a bountysource for this, I will add a bounty :)

**Comment by converge** [comment]
hi @hestuppfodarn , you can add a Bounty here https://www.bountysource.com/issues/51493944-blacklist-problem

**Comment by hestuppfodarn** [comment]
@converge done!
btw, thanks for the respect upper/lower limit you improved.

**Comment by converge** [comment]
hey @hestuppfodarn , just did it, PR #959. Could you test it ?

**Comment by hestuppfodarn** [comment]
@converge works perfectly,
thanks again!

(do I have to do anything else now to give you the bounty(ies)?)

**Comment by converge** [comment]
thank you @hestuppfodarn ! Did you receive an email to accept it ?
