### ISSUE TITLE
"onlyInstapyMethod" flag not working for unfollow_users()

### ISSUE THREAD

**Issue by squigglesMcW** [InstaPy/InstaPy#921]
The function  appears to be ignoring onlyInstapyMethod='LIFO' / 'FIFO' flags and unfollows the most recent user instead.

**Comment by squigglesMcW** [comment]
Please close this - walked through the code and realised the onlyInstapyMethod flag requires that onlyInstapyFollowed=True because it reads from [user]_followedPool.csv.

I will have to write some additional code so the FIFO works with my full followed list, not just what is managed by InstaPy.

**Comment by Abzidian** [comment]
Please do share this additional code. In a similar situation, but barely find time to decode all the scripts to get to writing the additional codes for it to work. Thanks!

**Comment by squigglesMcW** [comment]
Pretty trivial edit actually... in unfollow_util.py, after line 163: hasSlept = False, add the following:
`    if onlyInstapyMethod == 'FIFO':
           print("Unfollowing FIFO")
           person_list = list(reversed(person_list)) # FIFO 
`

The onlyInstapyMethod  flag will now work even if onlyInstapyFollowed=False

**Comment by squigglesMcW** [comment]
Just add this after line 163: hasSlept = False in unfollow_util.py:
  
       if onlyInstapyMethod == 'FIFO':
                person_list = list(reversed(person_list)) # FIFO 

The onlyInstapyMethod flag will now work even if onlyInstapyFollowed=False
