### ISSUE TITLE
How many followers do I have to follow/unfollow per day?

### ISSUE THREAD

**Issue by clowii** [InstaPy/InstaPy#922]
Hello,
how many followers do I have to folllow/unfollow per day to prevent that Instagram block me?
Thank you!!

**Comment by sionking** [comment]
Basically: start with 100 and increase every 3-5 days until 500.
For old age account limit can be even 1000.
No one really know, better keep it low as max 500.

**Comment by wyattwade** [comment]
Hey, any updated advice on this issue? Much appreciated!
