### ISSUE TITLE
follow_user Should Catch more exception types.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#923]
## Expected Behavior
def follow_user(browser, follow_restrict, login, user_name, blacklist):
Should Catch more exception types.
I fall on:
```
  File "C:\instapy\instaPy\InstaPyOffic\Follow.py", line 30, in <module>
    session.interact_user_followers(userFollowlist, amount=1000, random=False)
  File "C:\instapy\instaPy\InstaPyOffic\instapy\instapy.py", line 1135, in interact_user_followers
    self.user_interact_media)
  File "C:\instapy\instaPy\InstaPyOffic\instapy\instapy.py", line 789, in like_by_users
    self.blacklist)
  File "C:\instapy\instaPy\InstaPyOffic\instapy\unfollow_util.py", line 228, in follow_user
    "arguments[0].style.opacity = 1", follow_button)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.p
y", line 467, in execute_script
    'args': converted_args})['value']
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.p
y", line 238, in execute
    self.error_handler.check_response(response)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandle
r.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to
the page document
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86
_64)
```

## Current Behavior
Catches only one "NoSuchElementException"

## Possible Solution (optional)
catch "StaleElementReferenceException":

exception selenium.common.exceptions.StaleElementReferenceException(msg=None, screen=None, stacktrace=None)[source]
Thrown when a reference to an element is now “stale”.

Stale means the element no longer appears on the DOM of the page.

Possible causes of StaleElementReferenceException include, but not limited to:
You are no longer on the same page, or the page may have refreshed since the element was located.
The element may have been removed and re-added to the screen, since it was located. Such as an element being relocated. This can happen typically with a javascript framework when values are updated and the node is rebuilt.
Element may have been inside an iframe or another context which was refreshed.

**Comment by sionking** [comment]
can change to:
except (NoSuchElementException, StaleElementReferenceException) as e:

**Comment by converge** [comment]
@sionking that's cool! In my point of view, we should fix the issue, so the Exception will never be called.

What do you think ?

**Comment by sionking** [comment]
Maybe we can try do the action 2 times, if it fail in the 3'rd time we shall continue there are many instagram users :)

**Comment by converge** [comment]
We're good programmers, let's debug it, find the cause of the issue and make the world a better place :octocat: 

Exceptions are friends, they tell us where we need to focus to fix the issues.

Count on me if you need some help to fix this issue. I'm working in other stuffs, but I always find some time.

**Comment by sionking** [comment]
My comment related to:
Possible causes of StaleElementReferenceException include, but not limited to:
You are no longer on the same page, or the page may have refreshed since the element was located.

So I meant to reload page than try again (in case of this exception) and if not helping go to next user (print the error) but don't stop the running.

SC
