### ISSUE TITLE
[ Cron task ]: FileNotFoundError: [Errno 2] No such file or directory: './logs/logFile.txt'

### ISSUE THREAD

**Issue by amauryleproux** [InstaPy/InstaPy#924]
## Expected Behavior
I try to set up a cron task but it's not working while it's working when I launch it manually by this command: python3 <Name_of_my_file>

Here is my cron task file:

21 16 * * * /usr/bin/python3 /var/www/aleproux/InstaPy/quickstart_city.py &> /var/www/aleproux/cronInsta_city.log

Here is my log error message:

Traceback (most recent call last):
    File "/var/www/aleproux/InstaPy/quickstart_city.py", line 5, in <module>
      session = InstaPy(username=insta_username, password=insta_password, nogui=True)
    File "/var/www/aleproux/InstaPy/instapy/instapy.py", line 60, in __init__
      self.logFile = open('./logs/logFile.txt', 'a')
  FileNotFoundError: [Errno 2] No such file or directory: './logs/logFile.txt'

Thanks in advance for your help gentleman

**Comment by converge** [comment]
hi @amauryleproux , this is how I do it:
```06 */3 * * * cd /opt/InstaPy/ && python /opt/InstaPy/bot.py >> /tmp/cron_debug_instapy.log 2>&1```

```*/3``` (every 3 hours)

let me know if it help.

**Comment by amauryleproux** [comment]
Now the command launch the task but I've got this into my log file:
The first run had worked until the 4th picture and the second one until the 7th and then I got this:


Traceback (most recent call last):
   File "/var/www/aleproux/InstaPy/quickstart_city.py", line 6, in <module>
     session.login()
   File "/var/www/aleproux/InstaPy/instapy/instapy.py", line 195, in login
     log_follower_num(self.browser, self.username)
   File "/var/www/aleproux/InstaPy/instapy/print_log_writer.py", line 8, in log_follower_num
     browser.get('https://www.instagram.com/' + username)
   File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in get
    self.execute(Command.GET, {'url': url})
    File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
      self.error_handler.check_response(response)
    File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
   raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.TimeoutException: Message: timeout
 (Session info: chrome=62.0.3202.94)
 (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 3.10.23-xxxx-std-ipv6-64 x86_64

**Comment by amauryleproux** [comment]
and another message on the last entry: 

"selenium.common.exceptions.WebDriverException: Message: chrome not reachable"

**Comment by amauryleproux** [comment]
Might be because I tried to launch to script at the same time? 
I commented one of them, will let you know if I get other errors

**Comment by amauryleproux** [comment]
So I've got several error messages:

"selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash from unknown error: cannot determine loading status"

"selenium.common.exceptions.WebDriverException: Message: chrome not reachable"

"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally"
