### ISSUE TITLE
Image check error: 'InstaPy' object has no attribute 'clarifai_id'

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#925]
Hello boys, 

Got an issue while trying to use clarifai with instapy, 
here is my code, basically I would like to have a test on the behavior of clarifai, so just try on two of my friends pictures, I already went on https://www.clarifai.com/demo to get some existing tag on my friends pics
```python
from instapy import InstaPy
insta_username = 'removedtobeposted'
insta_password = 'removedtobeposted'
session = InstaPy(username=insta_username, password=insta_password)
session.login()
session.set_do_comment(True, percentage=100)
session.set_do_like(True, percentage=80)
session.set_use_clarifai(enabled=True, api_key='removedtobepostedhere')
session.clarifai_check_img_for(['nsfw'])
session.clarifai_check_img_for(['landscape', 'nature', 'outdoors', 'beach'], comment=True, comments=['Awesome', 'So beautiful', u':heart_eyes: :100:'])
session.interact_by_users(['user1', 'user2'], amount=5, random=True, media='Photo')
session.end()
```
I tried many things, Do you have any ideas?
Cheers, 
Morgan

**Comment by timgrossmann** [comment]
@MorganPelissier Quick fix, could you please test #926

**Comment by timgrossmann** [comment]
@MorganPelissier Please update your InstaPy `git pull` and try again

**Comment by ghost** [comment]
Great mate thanks, it works well!
