### ISSUE TITLE
How to Add a Korean Tag?

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#927]
## Expected Behavior
Using quickstart.py I tried inserting a Korean hashtag expecting it to run like it did with English tags.
## Current Behavior
The error I get is: SyntaxError: Non-ASCII character
## Possible Solution (optional)
I'm new to coding and I have a feeling I have to convert(?) or allow(?) the program to identify with Non-ASCII characters. Can anybody direct me to a source so as to learn how to do this?

**Comment by timgrossmann** [comment]
@kimelbert have you tried adding the tag in the form of `u'koran_tag'`?

> Note the u before the string quotes here

**Comment by ghost** [comment]
@timgrossmann hey that didn't work. The way I made it work was to comment line 554 (instapy.py) so it doesn't delete white space. It's inefficient because I have to uncomment this line of code to change it to english, but it works. Thanks for commenting Tim. Really enjoy using instapy.

**Comment by hojabbr** [comment]
Just add these lines to `quickstart.py` and `instapy.py`:

```
# -*- coding: UTF-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

**Comment by arminorlik** [comment]
Hi @hojjabr your solution doesn't work any more, do you have any other suggestion how to solve this issue?
