### ISSUE TITLE
Found an error whilst unfollowing

### ISSUE THREAD

**Issue by rossbulat** [InstaPy/InstaPy#928]
## Current Behavior
I'm running the bot and when it gets to unfollow, this following error occurred:

Liked: 6
Already Liked: 0
Inappropriate: 4
Commented: 0
Followed: 0
Number of people followed automatically remaining: 703
('following_link error \n', 'list index out of range')
Traceback (most recent call last):
  File "bot.py", line 23, in <module>
    session.unfollow_users(amount=350, onlyInstapyFollowed = False, onlyInstapyMethod = 'FIFO' )
  File "/var/InstaPy/instapy/instapy.py", line 1217, in unfollow_users
    sleep_delay)
  File "/var/InstaPy/instapy/unfollow_util.py", line 142, in unfollow
    '/html/body/div[4]/div/div/div[2]/div/div[2]')
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[4]/div/div/div[2]/div/div[2]"}
  (Session info: chrome=62.0.3202.75)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.13.0-16-generic x86_64)

**Comment by squigglesMcW** [comment]
Yes there's an error when you set onlyInstapyFollowed=False or omit the flag. My workaround was to replace line 130-132 of unfollow_util.py as follows:

            #following_link = browser.find_elements_by_xpath(
            #    '//header/div[2]//li[3]')
            #following_link[0].click()            
            browser.find_element_by_partial_link_text("following").click() 

Works fine for me after this change. 


cheers

**Comment by RomeoJuliett** [comment]
@rossbulat did this work for you?

**Comment by converge** [comment]
hi @rossbulat , could you upgrade your chromedriver to latest version and tell us if it fixed the issue ?

**Comment by stefanocaioni** [comment]
@converge I don't think it's the chromedriver, I have the same error and I upgraded it a few days ago. Doing what @squigglesMcW suggested seems to fix the problem for now

**Comment by mjortberg521** [comment]
The fix by @squigglesMcW above combined with the change by @cagalindo in #730 (switch line ~144 to browser.find_element_by_xpath('/html/body/div[4]/div/div/div[2]/div/div[2]') made unfollowing work for me
