### ISSUE TITLE
Keyboard and Mouse unresponsive after script finishes or ends unexpectantly

### ISSUE THREAD

**Issue by wyvers** [InstaPy/InstaPy#929]
## Expected Behavior
Script finishes or ends early. Keyboard and Mouse should stay usable.

## Current Behavior
When the script ends, I cannot use my mouse or keyboard until I force a shutdown and reboot. Closing the laptop lid and reopening it puts me in the login/welcome screen and nothing on the keyboard or trackpad is giving feedback. Mute keys on the keyboard works, keyboard back lighting adjustment works. Pushing the power key at this point usually shutsdown the computer. That doesn't happen here. Pushing on the power key does nothing until it's held down to force shutdown.

I've seen this happen since I got everything setup.

## Possible Solution (optional)
Not sure? Driver issue? Re installation does not resolve this.

## InstaPy configuration

Running on a Lenovo laptop with Windows 10.
Latest stuff off github and I'm using the InstaPy GUI. 

Please let me know if you need additional details. My first time playing in this pool. :)

**Comment by RomeoJuliett** [comment]
Not sure if it's related to the InstaPy GUI or not. Have you experienced this issue WITHOUT running the GUI @wyvers

**Comment by wyvers** [comment]
@RomeoJuliett I think it is related to InstaPy GUI after you brought this up. I went through and just filled out a quickstart.py and the script finishes without any issues. Thank you so much for pointing that out. Seems like an issue with that particular GUI app and not InstaPy?
