### ISSUE TITLE
NoSuchElementException - Error

### ISSUE THREAD

**Issue by Eldress** [InstaPy/InstaPy#93]
Hi, thanks for your app and great services ;) PLease could you help me, I have an issue with running this program; NoSuchElementException: Message: no such element: Unable to locate element: {"method":"name","selector":"MYUSERNAME"}. I have tried everything, but still doesnt work :/ 

Thank you anyway, have a great day :)

**Comment by timgrossmann** [comment]
@Eldress could you please provide some context?
What post caused this error?
What were your settings?
Which OS?

**Comment by Eldress** [comment]
Thank you for your quick reply. I use Mac OS (sierra)
I have followed the guide to install everything
then I started quickstart.py, google chrome opened with instagram log in page - (30 sec nothing) - then this error occured.

**Comment by foname** [comment]
@Eldress Does it fill up your username and password? If not, I guess it cannot find username element. In this case, please make sure that you checkout the latest code. 
And double check again that InstaPy/instapy/login_util.py has the line same as below:

`username_elem = browser.find_element_by_name('username')`

**Comment by timgrossmann** [comment]
@Eldress Is the issue solved?

**Comment by Eldress** [comment]
I am sorry, yea it is. I did not use cmd, but jsut python idle.... sorry for late respons and thank yo uvery much for the programm :)
