### ISSUE TITLE
set_dont_unfollow_active_users(enabled=True, posts=2) Crashes the script

### ISSUE THREAD

**Issue by Naramsim** [InstaPy/InstaPy#931]
## Expected Behavior
Work normally
## Current Behavior
`selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//header/div[2]/ul/li[1]/span/span"}`

## InstaPy configuration
On Docker, latest version

**Comment by datteba** [comment]
Same here

  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 309, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 787, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//header/div[2]/ul/li[1]/span/span"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.15063 x86_64)

**Comment by converge** [comment]
I´m preparing a new update to fix this and improve the code quality, it´s not good at the moment.

**Comment by converge** [comment]
hey @Naramsim @datteba , can you test it before we merge ? #935

**Comment by datteba** [comment]
I get this now @converge 

![screen](https://user-images.githubusercontent.com/30053143/32883706-5c7599f0-cab8-11e7-9ae9-3f98d03c5fde.png)

**Comment by converge** [comment]
@datteba , is something in your quickstart file, preffer using it in this way:

https://github.com/timgrossmann/InstaPy/blob/master/quickstart.py

If you paste your quickstar-FIFO.py file will be easier to catch the issue.

**Comment by datteba** [comment]
Thanks @converge !

In this way it seems to work. I will test it for 24 hours and let you know.

**Comment by datteba** [comment]
@converge everything works for now.

**Comment by datteba** [comment]
@converge back again... :(

![image](https://user-images.githubusercontent.com/30053143/32981219-db93b1f6-cc73-11e7-95ac-8d41877b16e2.png)

**Comment by converge** [comment]
@datteba it's because you're using the master version, we didn't merge it yet.

The PR is here #935 , I just tested it today and it's working, could you help testing it ? There is a command line instruction in the end of the PR page. 

I'm just waiting another test to merge it.
