### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Naramsim** [InstaPy/InstaPy#933]
## Expected Behavior
Log in works
## Current Behavior
Log in doesnt work
## Possible Solution (optional)
Double click Log In button
## InstaPy configuration
Latest on docker

Hi, with one of my account Instapy seems to not fully click the login button, leaving greyed out as in the image below
![insta](https://user-images.githubusercontent.com/8996268/32858762-c98b32dc-ca4c-11e7-91bc-cca5de020e12.png)

Duplicating the line below
https://github.com/timgrossmann/InstaPy/blob/f28d38df36d65b153a301153f6c0393692eb2664/instapy/login_util.py#L45
fixes the issue and logs me in successfully.

Is it possible to duplicate the Line45 call, so this error will be fixed?

Thanks very much

**Comment by ghost** [comment]
I have an almost similar Problem: Seems like when entering the password, the InstaPy Bot clicks the wrong field (which leads to google settings). Can someone help? :)

**Comment by ghost** [comment]
Had to download the current Chromedriver and put it into assets 👍 Now working again

**Comment by converge** [comment]
@Naramsim , did the @flothousand solution fixes your issue ?

**Comment by Naramsim** [comment]
@converge Nope, since I run it through Docker Compose and Chromedriver is not necessary using Selenium image

**Comment by tuxity** [comment]
Same here directly in cmdline
```
# python3 quickstart.py
Wrong login data!
```

not sure if it's the same problem tho

**Comment by jbsness** [comment]
Same here with fresh new install on Windows, 
duplicating Line45 solved this issue !

**Comment by theolux** [comment]
I just started receiving the 'wrong login data' error on all my accounts suddenly, even though I changed absolutely nothing with them. They are running on a Scaleway Ubuntu server.
I tried duplicating Line45 and it didn't help, I tried changing the IP and then reactivating one of them and I tried updating chromedriver which didn't help either.
What could it be?

**Comment by Naramsim** [comment]
One thing you can do is take a screenshot with selenium right when instapy prints ('cant login')

**Comment by theolux** [comment]
Hmm how do I do that?

**Comment by Naramsim** [comment]
Google has the answer

after this line

https://github.com/timgrossmann/InstaPy/blob/db6b7cc4670884cb8b000cabad336b26dc865ebb/instapy/login_util.py#L52

put a `browser.save_screenshot('screenie.png')`

**Comment by converge** [comment]
Hey guys, I'm not able to reproduce the issue. I'm at our Slack workspace, if you give me remote access I can try to fix it.

**Comment by theolux** [comment]
OK the screenshot says 'the username you entered doesn't belong to an account'...
I tried both username and email and I still get this error... WTF?

**Comment by theolux** [comment]
Any idea what could cause this and how this could be fixed?
This is how I'm logging into my accounts:
session = InstaPy(username='USERNAME', password='PASSWORD', nogui=True)
This has worked perfectly up to a few days ago...
