### ISSUE TITLE
Inconisistent Performance...pulling my hair out

### ISSUE THREAD

**Issue by Namaslayer** [InstaPy/InstaPy#941]
> [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=50831261)](https://www.bountysource.com/issues/50831261-crashing-of-script?utm_source=50831261&utm_medium=shield&utm_campaign=ISSUE_BADGE)

I have a few bots on a few accounts. For a while they were all super consistent and operating beautifully. Had an issue with out of date chromedriver, updated to 3.33 and still having a bunch of issues.

Running on a server, using crontabs to automate. What would cause a script to start running (log in correctly) and then just fritz out?

Here are graphs from Digital Ocean, I can show crontabs and everything here too. 

My logs are super nonhelpful as they don't tell me any errors. HEEEELP!!!!

<img width="845" alt="screen shot 2017-11-16 at 5 21 51 pm" src="https://user-images.githubusercontent.com/31394074/32924753-ffd1c2c4-caf2-11e7-92cb-45fa3b0a93c5.png">

**Comment by timgrossmann** [comment]
@Namaslayer Sorry you're experiencing this issues... This is already known, I came up with a quick and dirty "solution" to fix at least some of it... #826 

Problem is still present though.

Until the problem is fixed, it's probably easiest to simply add a "reboot" to your quickstart file that reboots the server everytime something fails and throws an error...

**Comment by Namaslayer** [comment]
@timgrossmann I've seen that thread, and I'm a bit confused about how to implement the solution. Any step-by-step you can offer would be super appreciated!

For whatever its worth, my bot only seeming to give me trouble when running the script that interacts with someone else's followers. My unfollow script and like-by-feed script work flawlessly.

Also, I just ran a script in a screen instead of relying on the logs and this is the error that was kicked back.

<img width="1117" alt="screen shot 2017-11-17 at 12 01 55 am" src="https://user-images.githubusercontent.com/31394074/32936913-03586f28-cb2b-11e7-8563-e07731ef50a0.png">

**Comment by Namaslayer** [comment]
Today, even after restarting all of the servers, the interact-with-someones-followers script only got through liking 2 to 5 accounts then crashes.  But liking by feed works perfectly every time.

I've updated everything I know how to, git pull, sudo apt-get update, and my chrome drivers is supposed to be the latest version.

**Comment by RomeoJuliett** [comment]
@Namaslayer The only current solution is the down and dirty version. I don't run on Digital Ocean so I'd have to brush up on your issue.

**Comment by Namaslayer** [comment]
@RomeoJuliett Im not quite sure how to implement the down and dirty fix.

Can you tell me how to do this?

**Comment by timgrossmann** [comment]
@Namaslayer @RomeoJuliett  The problem with the pending PR is that it's not working consistently as well...

Do you use DigitalOcean @Namaslayer ??

If so, you could do something like

```python
import os

try:
    session = InstaPy(....)
    session.....
    .
    .
    .

    os.system(reboot)
except Exception as err:
    with open('./logs/error.log', 'a+') as err_file:
        err_file.write(str(err))

    os.system('reboot')
```

This will lead to the server rebooting after every problem or successful run, but at least guarantee you (some) better performance and a few less issues

**Comment by Namaslayer** [comment]
@timgrossmann Yes I do use DigitalOcean.

My scripts look a little different, so I'll have to learn how to use the code this way, but I can ask some friends to help me implement the change. Thank you so much for the help!

**Comment by timgrossmann** [comment]
@Namaslayer Just post your script here, I'm sure it'll be easy to wrap this around the whole thing 😉
(Will be the quick and dirty way, but at least it will have small impact)

**Comment by rangabears** [comment]
@timgrossmann which file would you insert that code into? And do you suggest running that alongside the quick and dirty fix?

**Comment by timgrossmann** [comment]
@tmurphy00 That is the quick and dirty fix... Unfortunately 😅 

The quickstart.py file (or your copy of it)

**Comment by Namaslayer** [comment]
Thanks @timgrossmann Here is the typical engagement code I use. I've taking usernames and passwords out for discretion

```python
from instapy import InstaPy

session = InstaPy(username='username', password='password', nogui=True)
session.login()

session.set_user_interact(amount=5, random=True, percentage=100, media='Photo')
session.set_do_follow(enabled=True, percentage=50)
session.set_do_like(enabled=True, percentage=100)
session.interact_user_followers(['influencer'], amount=50, random=True)

session.end()

```

**Comment by timgrossmann** [comment]
@Namaslayer Simply use:

```python
import os

from instapy import InstaPy

try:
    session = InstaPy(username='username', password='password', nogui=True)
    session.login()

    session.set_user_interact(amount=5, random=True, percentage=100, media='Photo')
    session.set_do_follow(enabled=True, percentage=50)
    session.set_do_like(enabled=True, percentage=100)
    session.interact_user_followers(['influencer'], amount=50, random=True)

    session.end()

except Exception as err:
    with open('./logs/errors.log', 'a+') as err_file:
        err_file.write(str(err))

finally:
    os.system('reboot')
```

**Comment by converge** [comment]
#1137

**Comment by timgrossmann** [comment]
@converge Good solution, but I'm not confident that this will fix the problem with the performance...
