### ISSUE TITLE
Getting error while 'python setup.py install'

### ISSUE THREAD

**Issue by oscaradams21** [InstaPy/InstaPy#943]
Hey, I am trying to install it via python setup.py install.
And i am getting : 

> `running install
> error: can't create or remove files in install directory
> 
> The following error occurred while trying to add or remove files in the
> installation directory:
> 
>     [Errno 13] Permission denied: 'C:\\Program Files (x86)\\Python36-32\\Lib\\site-packages\\test-easy-install-2924.write-test'
> 
> The installation directory you specified (via --install-dir, --prefix, or
> the distutils default setting) was:
> 
>     C:\Program Files (x86)\Python36-32\Lib\site-packages\
> 
> Perhaps your account does not have write access to this directory?  If the
> installation directory is a system-owned directory, you may need to sign in
> as the administrator or "root" account.  If you do not have administrative
> access to this machine, you may wish to choose a different installation
> directory, preferably one that is listed in your PYTHONPATH environment
> variable.
> 
> For information on other options, you may wish to consult the
> documentation at:
> 
>   https://setuptools.readthedocs.io/en/latest/easy_install.html
> 
> Please make the appropriate changes for your system and try again.
> 

What can I do ?

**Comment by RomeoJuliett** [comment]
Try installing python directly from the website. When running the install package be sure to select the option "Set Python to Path."

**Comment by timgrossmann** [comment]
@RomeoJuliett Thank you for pointing this out!

@oscaradams21 For Windows it's, unfortunately, extremely important to not miss that small checkbox when install Python on the system that says 

- [ ] Add Python to Path

**Comment by converge** [comment]
There is no interaction for a long time, please reopen it if you still need some help.
