### ISSUE TITLE
As of late, chrome automatically opens a new tab with chrome settings

### ISSUE THREAD

**Issue by 46960** [InstaPy/InstaPy#947]
## Expected Behavior
Automatic login to Instagram, start liking / following

## Current Behavior
During login, opens new tab: Chrome settings / "Chrome is up to date".  
Since this has started, my Macbook makes the famous "error" sound with every image it likes and every user it follows. This is disturbing, so I can only run it with my macbook on mute. Though it is not such a huge deal, since InstaPy still runs, I was wondering if someone else has experienced this and found a solution? 

<img width="867" alt="screen shot 2017-11-18 at 3 32 38 pm" src="https://user-images.githubusercontent.com/32015501/32981406-bf78d31e-cc75-11e7-921c-7d390c8e683b.png">

**Comment by timgrossmann** [comment]
@46960 Have also seen that... Have you already updated chrome to the newest version?
Should disappear from then on

**Comment by GabrielleV** [comment]
I had the same issue and it was also saying my password was incorrect (it was correct). I updated Chrome Driver and it works fine now.

**Comment by 46960** [comment]
I thought I had the most updated version but turns out I didn't. Updated again, and it did the trick. Thanks!
