### ISSUE TITLE
Hello, I updated the new fixes on unfollow but

### ISSUE THREAD

**Issue by Luisetty** [InstaPy/InstaPy#949]
I got this error:

  File "quickstart_.py", line 32, in <module>
    session.set_unfollow_active_users(enabled=False, posts=10)
AttributeError: 'InstaPy' object has no attribute 'set_unfollow_active_users'

--- quickstart---
line 32:
session.set_unfollow_active_users(enabled=False, posts=10) 
----

I'm doing something wrong? or what object has not attribute. Any ideas what i should look into?

**Comment by timgrossmann** [comment]
@Luisetty Sorry, make sure to look into the documentation... The api changed shortly after the release of that feature, actually thought nobody was working with it at that point...

```python
set_dont_unfollow_active_users(enabled=False, posts=5)
```
