### ISSUE TITLE
Improving ClarifAI usage

### ISSUE THREAD

**Issue by AlainPilon** [InstaPy/InstaPy#95]
After assessing how InstaPy could help me, I realized that it is liking/commenting a lot of stuff which isnt related to my account interests. So I decided to checkout ClarifAI (made a PR about it #94 ) and realized that image analysis is only used to determine if the post should be commented or not. 

So I propose we also use it to determine if if should be liked or not and later on if we should follow the image account owner or not. What do you think?

Also, I can't figure out the logic behind these lines:
```
  for pair in img_tags:
    if not pair[1]:
      if given_tags_in_result(pair[0], result_tags):
        print('Inappropriate content in Image, not commenting')
        return False, []
    else:
      if given_tags_in_result(pair[0], result_tags):
        return True, pair[2]
```

The variable `pair` is in fact a tuple of 3 values `(tags, comment, comments)` so it should be renamed to something more explicit. Or remove `comment` and simply check for the presence of content in the `comments`...

But the part that I dont understand is if `pair[1]` is `False` (so we dont want to comment) why do we still check for the tags and return `False` if the `given_tags_in_result()` call returns `True`?

**Comment by AlainPilon** [comment]
I did a clean up in pr #106 to make things clearer for the next person looking into this

**Comment by timgrossmann** [comment]
@AlainPilon Sorry for the late response... Been quite busy today.
Glad you found it out and cleaned it up. Thank you!
