### ISSUE TITLE
Interact with Users who like a post

### ISSUE THREAD

**Issue by AustineA** [InstaPy/InstaPy#950]
## InstaPy configuration

Is it possible to interact with users who like a particular post.

eg. Give a Url and instapy will interact with the users who liked the post.

**Comment by converge** [comment]
hi @AustineA , this functionality isn't available yet. If you add a bounty for it, maybe someone could work on it to you.

https://www.bountysource.com/issues/51733313-interact-with-users-who-like-a-post

**Comment by timgrossmann** [comment]
@AustineA @converge I think with the current InstaPy version, this isn't possible at all.
When opening up a post in the web browser, there is no way you can search through the people that actually liked the post.

I don't know if this would work on the mobile webpage

**Comment by converge** [comment]
@timgrossmann that's right. I do think in a less specific solution, for example:

```interact_with_active_users(enabled=True, posts=5)```

**Comment by AustineA** [comment]
Thanks guys, sorry for the late reply... I am currently experimenting on how to implement this myself i think you can grab a link of users who like a post from the heart icon.

I'll keep you updated on my finds if it works.

**Comment by timgrossmann** [comment]
@AustineA Yes! That's the right spirit.

Looking forward to the PR! Thank you very much.
