### ISSUE TITLE
Feed crashes

### ISSUE THREAD

**Issue by Naramsim** [InstaPy/InstaPy#952]
## Expected Behavior
Run
## Current Behavior
Feed crash
## Possible Solution (optional)
Change the line below
## InstaPy configuration
Does not matter

https://github.com/timgrossmann/InstaPy/blob/94b24f487e487c0709c1bf3154069df91138cbaf/instapy/instapy.py#L745

This line crashes because random is boolean, as you see in the named parameter of the function. I suggest 

`import random as rnd`

**Comment by timgrossmann** [comment]
@Naramsim Thank you for reporting this.

Yes, we definitely have to change the `random` part...
Feel free to submit a PR for this, thank you

**Comment by converge** [comment]
thanks @Naramsim , just made a PR #955 , can you help testing it ?

**Comment by converge** [comment]
we fixed this at #955 , thanks @Naramsim for the bug report.
