### ISSUE TITLE
'bool' object has no attribute 

### ISSUE THREAD

**Issue by Namaslayer** [InstaPy/InstaPy#954]
Started over fresh, and getting this error.

<img width="660" alt="screen shot 2017-11-19 at 5 16 33 pm" src="https://user-images.githubusercontent.com/31394074/32998178-b1ee3544-cd4d-11e7-9226-153481b03f7e.png">

What's causing this error?

InstaPy used to work perfectly for me, and now with new updates I can't get it to run one single script!

**Comment by timgrossmann** [comment]
@Namaslayer Sorry to hear that, if you could help test #955 we could get this error out of the way soon

**Comment by Namaslayer** [comment]
oh I didn’t see this! I’ll try it now. Thank you

**Comment by Namaslayer** [comment]
How do I test it? I just switched “random” to “randomize” in all of my scripts and that doesn’t work. I think I need to do something else to get the updated InstaPy program, right?

New to all of this, thanks for helping me learn!

Here's what I've got, usernames and passwords removed.




from instapy import InstaPy

session = InstaPy(username='username', password='passwords', nogui=True)
session.login()


session.set_user_interact(amount=5, randomize=True, percentage=100, media='Photo')
session.set_do_follow(enabled=True, percentage=50)
session.interact_user_followers(['target_influencer'], amount=50, randomize=True)

session.end()

**Comment by Namaslayer** [comment]
did a git pull and that's up-to date

**Comment by converge** [comment]
hey @Namaslayer , there is a link (command line instruction) at the bottom of the #955

**Comment by Namaslayer** [comment]
Am I just missing permissions?

This is what I tried to do

<img width="1031" alt="screen shot 2017-11-19 at 6 50 13 pm" src="https://user-images.githubusercontent.com/31394074/33000063-9fd224a8-cd5a-11e7-851b-b8e68387265c.png">

**Comment by Namaslayer** [comment]
@converge read above. I'm still painfully new to all of this, Guessing im missing permissions or I did something wrong haha

**Comment by mamartins** [comment]
I'm getting same error after last PRs merged locally

**Comment by converge** [comment]
@Namaslayer you downloaded it using the zip file, to use that git commands you do need to download it using git clone (this is easier to update InstaPy later)

**Comment by converge** [comment]
@mamartins could you help testing #955 ? after testing we can merge.

**Comment by mamartins** [comment]
@converge now after your merge I get 
```
| Traceback (most recent call last):
web_1       |   File "docker_quickstart.py", line 348, in <module>
web_1       |     bot.set_user_interact(amount=3, random=False, percentage=100, media='Photo')
web_1       | TypeError: set_user_interact() got an unexpected keyword argument 'random'
```

**Comment by converge** [comment]
@mamartins it's because we renamed every method that uses random parameter/argument, now it have to be ```set_user_interact(amount=3, randomize=False...)```

**Comment by Namaslayer** [comment]
@converge still a bit confused. I tried this

<img width="969" alt="screen shot 2017-11-20 at 2 01 41 pm" src="https://user-images.githubusercontent.com/31394074/33043798-7c59b94a-cdfb-11e7-96d3-672f9893c89f.png">


What is the line command I need to enter?

**Comment by Namaslayer** [comment]
@converge Ah, Nevermind! I see you've updated the regular file with the new paramaters. I did a normal git pull with "randomize" and its working. Thank you for the hard work and help!!

**Comment by mamartins** [comment]
@converge True, sorry! :)
