### ISSUE TITLE
error when bot encounters a private user

### ISSUE THREAD

**Issue by thecaharin** [InstaPy/InstaPy#956]
Hi there, first off thanks so much for creating this program and open sourcing it. Ive been trying to grow my following and hopefully this can help :).  Im receiving an error when the bot encounters a user that is private. Im using the interact_user_followers to like and follow the followers of a certain user and it ends up stoping the program in the terminal and producing an error when it comes across a users page that is private. 
i changed the names of the accounts to username, and usernames for their privacy. 
And below the error message i included how the code is written in Atom. Thanks so much in advance for the help anyone could possibly provide. 

```
Username [7/250]
--> username
('Getting', usernames’, 'image list...')
This user is private...
Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    session.interact_user_followers([‘user’], amount=250, random=True)
  File "/Users/newuser/Desktop/InstaPy-master/instapy/instapy.py", line 1062, in interact_user_followers
    self.user_interact_media)
  File "/Users/newuser/Desktop/InstaPy-master/instapy/instapy.py", line 722, in like_by_users
    self.blacklist)
  File "/Users/newuser/Desktop/InstaPy-master/instapy/unfollow_util.py", line 210, in follow_user
    if follow_button.is_displayed():
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 363, in is_displayed
    return self._execute(Command.IS_ELEMENT_DISPLAYED)['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.6 x86_64)
```

And then how it is written in quickstart:

```python
session.set_user_interact(amount=3, random=True, percentage=100, media='Photo')
session.set_do_follow(enabled=True, percentage=100)
session.set_do_like(enabled=True, percentage=100)
session.set_comments(["nice", ""])
session.set_do_comment(enabled=False, percentage=80)
session.interact_user_followers(['username'], amount=250, random=True)
```

Thanks again :)

**Comment by CharlesCCC** [comment]
curious question, how do you decide which image to like/comment ? by tag or something else, I just wondering how did it end up looking for private user ? because if it private user, they image shouldn't showing up under tag search.

**Comment by uni1783** [comment]
@CharlesCCC I think it's because of the interact_user_followers(['username']) setting. It will try to generate a list of images from a private user that is following the username.

**Comment by thecaharin** [comment]
Hey guys thanks for the responses.  There is an instagram user with a big following who i have had success with his followers liking my photos and following because we looks somewhat similar. So i am trying to target his followers. The bot runs fine when it encounters one of his followers whose account is public, but then when it gets to his followers who are 'private' the error occurs.
 @CharlesCCC Its searching not by tag, but by a users followers. So it cycles through public accounts as well as his followers who are private. 
@uni1783 Yea, im trying to target a users followers. So the bot encounters public profiles as well as Private. :/
Not sure if the fix would be to have the bot skip over private profiles or ignore them? I only just started learning coding so i wouldn't have a clue how to fix such a thing lol.

**Comment by sionking** [comment]
I workaround it by adding:

````
def follow_user(browser, follow_restrict, login, user_name, blacklist, logger):
    """Follows the user of the currently opened image"""

    try:
        follow_button = browser.find_element_by_xpath(
                "//button[text()='Follow']")

        # Do we still need this sleep?
        sleep(2)
		
        errorSkip = False
		
        try:
            follow_button.is_displayed()
        except:
            errorSkip = True

        if not errorSkip and follow_button.is_displayed():
            follow_button.send_keys("\n")
            update_activity('follows')
        else:
            browser.execute_script(
                "arguments[0].style.visibility = 'visible'; "
                "arguments[0].style.height = '10px'; "
                "arguments[0].style.width = '10px'; "
                "arguments[0].style.opacity = 1", follow_button)
            follow_button.click()
            update_activity('follows')

        logger.info('--> Now following')
        log_followed_pool(login, user_name, logger)
        follow_restrict[user_name] = follow_restrict.get(user_name, 0) + 1
        if blacklist['enabled'] is True:
            action = 'followed'
            add_user_to_blacklist(
                browser, user_name, blacklist['campaign'], action, logger
            )
        sleep(3)
        return 1
    except NoSuchElementException:
        logger.info('--> Already following')
        sleep(1)
        return 0
    except:
        print('--> SION:Not following since error occuered')
        sleep(1)
        return 0

````

**Comment by thecaharin** [comment]
Hey @sionking thank you for providing that code to try. Unfortunately once the bot gets to a private user, the same error is occurring and halting the program :/

**Comment by thecaharin** [comment]
Hi @converge sorry to bother you. I see that you are fairly active on the instapy issues page. Is there anyway you would be able to take a quick look at this error please? I would greatly appreciate it. Thanks so much in advance if you are able to. :)

**Comment by converge** [comment]
hi @thecaharin , do it in the InstaPy folder:
```
git pull
``` 
it will update your InstaPy, we added this private account verification this week, after updating it will avoid private accounts and you will see the information in the ```logs/general.log```

**Comment by thecaharin** [comment]
Hey @converge wow thank you very much for the quick response as well as a potential fix to the issue i am having. Sorry to be a bother but im not exactly sure how to execute an update. Im very new to coding. I went into the folder that i have instapy installed on my desktop and couldn't find a link for "git pull" so i tried to execute it in my terminal (running it on a mac) and it produced --->
News-MacBook:~ Mac$ cd desktop/
News-MacBook:desktop mac$ cd instapy-master
News-MacBook:instapy-master Mac$ git pull
fatal: Not a git repository (or any of the parent directories): .git

:/

**Comment by converge** [comment]
your welcome, you don't bother me, helping each other we go further.
do it:
```
git init .
git remote add origin https://github.com/timgrossmann/InstaPy.git
git pull
```

**Comment by thecaharin** [comment]
@converge Wow thank you so much! I like your way of thinking, i agree. I hope as i progress with my coding i will be able to contribute on here one day. It appears to be running smoothly after the git pull. Thank you again so much and for all the work you do on here. I was on a 100$ a month instagram program at one point and im thrilled i will be able to do it on my own now. Thanks again and be well :)

**Comment by thecaharin** [comment]
@converge Thats odd, it was working and then just crashed again.. :/

Username [21/250]
--> _username_
('Getting', u'username', 'image list...')
This user is private...
Traceback (most recent call last):
  File "quickstart.py", line 21, in <module>
    session.interact_user_followers(['username'], amount=250, random=True)
  File "/Users/newuser/Desktop/InstaPy-master/instapy/instapy.py", line 1062, in interact_user_followers
    self.user_interact_media)
  File "/Users/newuser/Desktop/InstaPy-master/instapy/instapy.py", line 722, in like_by_users
    self.blacklist)
  File "/Users/newuser/Desktop/InstaPy-master/instapy/unfollow_util.py", line 210, in follow_user
    if follow_button.is_displayed():
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 363, in is_displayed
    return self._execute(Command.IS_ELEMENT_DISPLAYED)['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.6 x86_64)

**Comment by converge** [comment]
@thecaharin your welcome! this is a know bug, it happens randomly unfortunately.

**Comment by thecaharin** [comment]
@converge Oooo ok i see, thanks. Is there a code to add that would reboot instapy automatically, incase i was away from my computer?

**Comment by converge** [comment]
I think @sionking did something about it.

**Comment by thecaharin** [comment]
@converge Ok thanks so much, i appreciate your time and your assistance. If i don't get it figured out ill read up on how to create a bounty for it lol. Be well :)

**Comment by uni1783** [comment]
I use a simple bash script for that:


```
#!/bin/bash

retry=2
sleeptime=10

function startInstapy {
	`python quickstart.py`
	return $?
}

while [ $exitStatus != 0 ]; do
	startInstapy
	exitStatus=$?
	if (( $exitStatus != 0 )); then
		(( retryCntr = ${retryCntr} + 1 ))
		if (( $retryCntr > ${retry} )); then
			echo "Failed too many times, quiting..."
			exit 2
		fi
	sleep $sleeptime
	fi
done

echo "completed successfully"

```
Put it in the same directory as your quickstart.py, make it executable (chmod +x) and run. It should work on both Linux and Mac.

**Comment by thecaharin** [comment]
Hey @uni1783 thanks in advance for reaching out and posting that script. Im pretty new to coding so im unsure how to make it executable (chmod +x)?
I pasted it in quickstart.py and it produced --->
News-MacBook:instapy-master Mac$ python quickstart.py
  File "quickstart.py", line 19
    function startInstapy {
                        ^
SyntaxError: invalid syntax

Im guessing thats because i didn't make it executable? 

Thanks again :)

**Comment by uni1783** [comment]
It should be pasted in it's own file (call it startbot.sh). So from the command line (in the instapy-master folder):

```
nano startbot.sh
(copy and paste code, ctrl+x y to save)
chmod +x startbot.sh
./startbot.sh
```

**Comment by thecaharin** [comment]
Startbot.sh as a text file? Also when i pasted the nano startbot.sh into my terminal it changed the whole layout and spooked me a tad lol

**Comment by thecaharin** [comment]
Startbot.sh as a text file? Also when i pasted the nano startbot.sh into my terminal it changed the whole layout and spooked me a tad lol @uni1783

**Comment by spacewaffle** [comment]
Just a quick note for the people who are using the bash script above, if you get the following error:

```
./startbot.sh: line 11: [: !=: unary operator expected
completed successfully
```

You need to change line 11 from this:
```
while [ $exitStatus != 0 ]; do
```
To this:
```
while [[ $exitStatus != 0 ]]; do
```
