### ISSUE TITLE
PC shutting down

### ISSUE THREAD

**Issue by elbizzo** [InstaPy/InstaPy#957]
## Expected Behavior
Quickstart script to run for 2-3 hours
## Current Behavior
PC shuts down prematurely 
## Possible Solution (optional)
I have no possible solution to this. I understand the script may terminate prematurely. But how does this relate to the PC shutting down? I raise this issue because it's happened to me 2-3 times and to my friend who just started using InstaPy. I would appreciate any feedback, thank you.
## InstaPy configuration
Running python quickstart.py on Windows Powershell

**Comment by converge** [comment]
hi @elbizzo , I dont know much to say, all I can say is that's probably a hardware issue.
