### ISSUE TITLE
get_active_users can't get formatNumber(browser.find_element_by_xpath(         '//header/div[2]/ul/li[1]/span/span').text)

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#958]
exception: Message: no such element: Unable to locate element: {"method":"xpath"
,"selector":"//header/div[2]/ul/li[1]/span/span"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d902
3f),platform=Windows NT 6.1.7601 SP1 x86_64)

A Workaround is to work without it....

**Comment by converge** [comment]
hi @sionking , can you help testing #935 ?

**Comment by converge** [comment]
it's fixed, just merged it.
