### ISSUE TITLE
Activity.csv not working

### ISSUE THREAD

**Issue by hestuppfodarn** [InstaPy/InstaPy#960]
## Expected Behavior
all interactions being saved in log/activity.csv

## Current Behavior
log/activity.csv is not getting updated
Worked perfectly. Issue starting yesterday 20/11-17

## Possible Solution (optional)
Might be something with the latest updates of Instapy occurring 20 November

## InstaPy configuration
MacOS

**Comment by Naramsim** [comment]
Activities.csv is no more :)

Superseded by SQLite3 😝

**Comment by hestuppfodarn** [comment]
Oh, sorry but what does "Superseded by SQLite3" mean?
If you want to know how many likes, comments, follows and server calls you make per day?

**Comment by Naramsim** [comment]
*replaced

**Comment by hestuppfodarn** [comment]
@Naramsim,
Thanks, solved!
