### ISSUE TITLE
Instagram notices InstaPy use?

### ISSUE THREAD

**Issue by matzeengl** [InstaPy/InstaPy#967]
Hey guys! 

I'm currently using instapy with firefox and proxyserver set over "firefox_profile.set_preference('network.proxy.type', 1)" and authentication with "expected_conditions.alert_is_present()". It works pretty well, but since a few days I'm getting a message, when logging in. 
Instagram says "We Detected An Unusual Login Attempt" and I have to verify my identity over mobile phone. 

Can it have something to do with selenium? I read, that Firefox sets a use_webdriver-variable in javascript.
Does someone else notice this behavior?
Is the proxy responsible for this behavior? It's a private proxy from High Proxies.
Maybe it's because InstaPy always is logging in from new. How do I save cookies, also for different users?

The function I always use is "like_by_tags".

I hope, someone can give me any kind of information concering my issue.

Best regards from bavaria
Matthias Englhardt

**Comment by ethandunford** [comment]
Sounds like you are running your bot too much?

**Comment by matzeengl** [comment]
I'm actually doing about 700 likes a day.
What likelimit did you experience? Is 1.000 a reasonable value?

**Comment by rvarseveld** [comment]
Sounds like a proxy issue. Where's your proxy server located?

**Comment by ethandunford** [comment]
1000 sounds like way too much

**Comment by balakedev** [comment]
Bring it down a notch man! thats way too much. Considering that your script will be skipping posts that are inappropriate too. You must be viewing over 1000 posts.

Play it safe...

**Comment by pr0f-f4rn5w0rth** [comment]
I recently started getting the same notices so I too brought down my engagement to about 2-300 likes. Still seem to be getting notices of Unusual Login Attempts?

I have not setup a proxy and my server is running somewhere in USA but I'm running my IG account from Canada. Not sure what best action plan should be?

**Comment by balakedev** [comment]
@pr0f-f4rn5w0rth hey mate, definitely try and get a server in Canada. Try and make it all local. I run mine on a server in Melbourne, Australia - i am in Melbourne. Never had any issues.

**Comment by Namaslayer** [comment]
Just happened to me too on one of the accounts I'm running. have been liking about 700 photos a day, and logging in 15 times. Too much?

**Comment by balakedev** [comment]
@Namaslayer Hi, yeah I would say its a bit much. Typically my scripts like around 275, skip 300. even then i think its a bit much.... for you to be liking 700 i cant image how many you must be viewing! As I've stated before on usage, think of instaPy as an opportunity to for you to not have to like posts, don't see it as a growth hack, in my opinion. 

I doubt instagrams algorithms consider a single Instagram liking 700+ posts and viewing over a thousand as human usage...
