### ISSUE TITLE
Session.like_by_tags don't work good?

### ISSUE THREAD

**Issue by ManuCit** [InstaPy/InstaPy#971]
Hi guys,
I have a problem with like by tags function, I set an amount of 100 likes for 2 tag for example, sometimes the script make only 12 likes and not 100.
There is a way to resolve this problem?

**Comment by converge** [comment]
anyone knows how to reproduce this error ? I tried it before, without success.

**Comment by ManuCit** [comment]
So you don't have this error? By the way, I don't know, I update instapy, but still nothing, same error, sometimes 100 likes and sometimes 12.

**Comment by converge** [comment]
It doesn't happen to me, I would like to reproduce it, so I can fix it.

**Comment by randomdev42** [comment]
Without reproduction this long this should be closed.
