### ISSUE TITLE
When feature onlyNotFollowMe=True, excluded users are unfollowed

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#974]
## Expected Behavior
users added to ```session.set_dont_include(['friend1', 'friend2', 'friend3'])``` should not be unfollowed when running ```session.unfollow_users(amount=10, **onlyNotFollowMe=True**, sleep_delay=60)```
## Current Behavior
running the unfollow if not following me code  ```session.unfollow_users(amount=10, onlyNotFollowMe=True, sleep_delay=60)```. I notice that it is unfollowing users that are added to ```session.set_dont_include(['friend1', 'friend2', 'friend3'])```

**Comment by wlrd** [comment]
I'll work on this one.

**Comment by converge** [comment]
#998 (fixed)
