### ISSUE TITLE
Search Locations

### ISSUE THREAD

**Issue by harrypython** [InstaPy/InstaPy#976]
Hey everybody!

I test a way to search locations based in the Facebook API. This can be useful if you need to target an audience that frequents a particular type of location / event.

What do you think? Is adding the Facebook API worth it for this feature?

**Comment by timgrossmann** [comment]
@harrypython Do you think this is also possible without the API?
If not, then build a Repo for it and we can integrate it #880

**Comment by harrypython** [comment]
I'll do some research and tests. 
But I don't think this is possible without accessing the API.
It's worth remembering that the venues on Instagram are actually created on Facebook.
