### ISSUE TITLE
Unfollow produces an error 

### ISSUE THREAD

**Issue by mehdi691** [InstaPy/InstaPy#977]
Hi,
I have a problem when I tried to unfollow people. It used to work nicely... (I'm using Selenium + Chrome Driver)
## Current Behavior
`Number of people followed automatically remaining: 696
('unfollow loop error \n', 'Message: unknown error: session deleted because of page crash\nfrom unknown error: cannot determine loading status\nfrom tab crashed
--> Total people unfollowed : 0 

Traceback (most recent call last):
  File "quickstart.py", line 19, in <module>
    session.end()

  File "/Users/Mehdi/Desktop/InstaPy/instapy/instapy.py", line 1467, in end
    self.browser.delete_all_cookies()

  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 692, in delete_all_cookies

    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute

    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response

    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: no such session
`
## Possible Solution (optional)
Delete All cookies. I tried to start a new session and then I deleted all cookies with the command driver.delete_all_cookies()

## InstaPy configuration

Thank you very much

**Comment by ugurozturk** [comment]
@mehdi691 do you using session.set_unfollow_active_users ?

https://github.com/timgrossmann/InstaPy/commit/5389ee1ecc9392e6581ef5e84b6b5c8e3aa2905c in this commit they changed this to session.set_dont_unfollow_active_users

**Comment by mehdi691** [comment]
@ugurozturk, yes I'm using session.unfollow_users(amount=160, onlyInstapyFollowed=True, onlyInstapyMethod='FIFO', sleep_delay=60). 
But I want to unfollow everybody i followed before even if an active user liked one of my pic...

**Comment by ugurozturk** [comment]
@mehdi691 so make like this session.set_dont_unfollow_active_users(enabled=No, posts=5). session.set_unfollow_active_users this fails bacuse this command is deleted

**Comment by mehdi691** [comment]
ok I'm gonna try 
session.set_dont_unfollow_active_users(enabled=No, posts=5) 

Just tried, doesn't work. I think I just have to delete cookies from web driver Chrome...

**Comment by converge** [comment]
hey guys , check it out: https://github.com/timgrossmann/InstaPy#dont-unfollow-active-users

**Comment by mehdi691** [comment]
@converge Yes but guys I'm using session.unfollow_users(amount=10, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=60 ) and this makes an error because of cookies...

**Comment by converge** [comment]
@mehdi691 you just need to upgrade chrome driver to latest version.

**Comment by mehdi691** [comment]
Its already updated. Still the error :( I don't understand because it used to work correctly...

File "/Users/Mehdi/Desktop/InstaPy/instapy/instapy.py", line 1467, in end
    self.browser.delete_all_cookies()

 File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 692, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)

**Comment by mehdi691** [comment]
Still need help ...

**Comment by converge** [comment]
@mehdi691 pls paste the full stacktrace (the error message)
