### ISSUE TITLE
[Feature Request] Filtering - Skip business accounts

### ISSUE THREAD

**Issue by timgrossmann** [InstaPy/InstaPy#980]
> [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=51878654)](https://www.bountysource.com/issues/51878654-feature-request-filtering-skip-business-accounts?utm_source=51878654&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Filters: this option lets you make filter people who act on them.

Implement a way to check if an account is a business accounts and ignore/interact with them if they are.

**Comment by sionking** [comment]
How whould you do it? I think checking if a website is published on bio is a good start.

**Comment by timgrossmann** [comment]
@sionking I'm not really sure how it works in the web view, but on the mobile version there is an extra button that says "Contact"... This might be the best way to find out

Maybe there are some other uniquenesses 

@converge What do you think about this?

**Comment by converge** [comment]
hey @timgrossmann @sionking , I think it's a good idea. The web version of Instagram doesn't show up the contact/email button. 

For me, the best way today is to name the feature something like:
```set_ignore_business_account(...)``` and make it clear in the docs that it will avoid interacting with profiles containing links.

**Comment by timgrossmann** [comment]
@converge Still trying to figure out if we should create single different commands like
`set_filter_business_account(...)`
`set_filter_gender(...)`
`set_filter_...`

or if we should go for a more generalised
`set_filters(...)`

We probably want to have it both ways => **Filter out** business accounts and **filter for only** business accounts

**Comment by converge** [comment]
@timgrossmann great idea, I think ```set_filters(...)``` would be better because it's easier to read:
```python
set_filter(skip_business_account=True,
           gender_to_interact='female',
           option1=True,
           another_option=False)
```

**Comment by sionking** [comment]
gender_to_interact ??? How can you recognize this beside image ?

**Comment by timgrossmann** [comment]
@sionking Seems like there are a lot of ways to do that!
Here are some services that offer exactly that:
- https://captiv8.io/
- https://minter.io/
- https://later.com/blog/first-look-instagram-new-analytics/
- http://www.allin1social.com/instagram-reports

In the worst case, we will get a first basic version by using some ML in the sense of a few hundred/thousand hand tagged profiles where we choose some features to hopefully don't get a too bad classification with e.g. a random forest...

**Comment by sionking** [comment]
I will give a bounty on it !

**Comment by sionking** [comment]
So this can be done using the api. I am creating a server that will check the api with users not running the automation.
