### ISSUE TITLE
Comment only when Clarifai match

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#984]
It is possible to comment only when Clarifai match ?
Because with my config, instaPy comments even when the clarifai_check_img_for function returns false.

My conf : 
```
session.set_do_comment(True, percentage=25)
session.clarifai_check_img_for(['nsfw'])
session.clarifai_check_img_for(['food', 'lunch'], comment=True, comments=foodComments)
```

**Comment by balakedev** [comment]
Hi @brokleen, can you share your whole file? If you don't have anything in your generic comments, I believe it should only comment when it finds the required items specified by session.clarifai_check_img_for in the photo.

**Comment by ghost** [comment]
I found a solution 
`session.set_comments([''])`
