### ISSUE TITLE
[bug] Clarifai full_match

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#986]
`session.clarifai_check_img_for(['food', 'lunch'], comment=True, comments=['Tasty!', 'Yum!'], full_match=True)
`
return 
`TypeError: clarifai_check_img_for() got an unexpected keyword argument 'full_match'`

**Comment by patricmutwiri** [comment]
Current Fix, comment it out. 

`session.clarifai_check_img_for(['food', 'lunch'], comment=True, comments=['Tasty!', 'Yum!'], full_match=True)`

to

`#session.clarifai_check_img_for(['food', 'lunch'], comment=True, comments=['Tasty!', 'Yum!'], full_match=True)`

consider this temporary please

**Comment by Patrikkk-zz** [comment]
Got the same issue just today. Same error
`TypeError: clarifai_check_img_for() got an unexpected keyword argument 'full_match'`
Used the same line as brokleen (from the Readme of the repo) 
Commented it out for now..

**Comment by Tidle999** [comment]
same for me, any solution for this?
