### ISSUE TITLE
logfiles: activity.csv is gone?

### ISSUE THREAD

**Issue by gerdmueller2** [InstaPy/InstaPy#987]
does anybody has the same problem?

i am running on ubuntu aws mashine.

how can i reacticate or force the creation of the logfiles?
-logs /actitity.csv

it seems that the logfile (/logs/logfile.txt) is now the /logs/general.txt

**Comment by hestuppfodarn** [comment]
Yeah it has been replaced by db (database). You have everything in there.

**Comment by gerdmueller2** [comment]
And how can i open it (in terminal)?

with "cat db/instapy.db" i get:
`cat db/instapy.db 
SQLite format 3@  
                  ?
???$!!?tablestatisticsstatisticsCREATE TABLE `statistics` (
  `likes` SMALLINT UNSIGNED NOT NULL,
  `comments` SMALLINT UNSIGNED NOT NULL,
  `follows` SMALLINT UNSIGNED NOT NULL,
  `unfollows` SMALLINT UNSIGNED NOT NULL,
  `server_calls` INT UNSIGNED NOT NULL,
!2!RL2ated` DATETIME NOT NULL)`

**Comment by hestuppfodarn** [comment]
Oh, not sure.
I've downloaded SQLite.
