### ISSUE TITLE
session.set_dont_like() only accepts 2 arguments? 

### ISSUE THREAD

**Issue by clevebounce** [InstaPy/InstaPy#988]
INFO - Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 32, in <module>
    session.set_dont_like('herbalife', 'amyway', 'maione', 'youngliving', 'avon', 'marykay', '#sex', 'follow', 'follower', 'shop', 'doterra', 'forex', 'cryto')
TypeError: set_dont_like() takes at most 2 arguments (14 given)

**Comment by clevebounce** [comment]
and even if I try 2 arguments, it returns an error

INFO - Session started - 2017-11-25 03:34:12
INFO - Logged in successfully!
Traceback (most recent call last):
  File "quickstart.py", line 33, in <module>
    session.set_dont_like('maione', 'shop')
TypeError: set_dont_like() takes at most 2 arguments (3 given)

**Comment by converge** [comment]
hi @clevebounce , do it:
```
session.set_dont_like(['herbalife', 'amyway', 'maione', 'youngliving', 'avon', 'marykay', '#sex', 'follow', 'follower', 'shop', 'doterra', 'forex', 'cryto'])
```

you forgot the [ ] (list)

**Comment by clevebounce** [comment]
@converge  thank you for your response.

could you elaborate? I am sort of a newbie and not very familiar with python

**Comment by sionking** [comment]
a list is a data type which count as one argument..
