### ISSUE TITLE
[Feature Request] Sending email with activity of session

### ISSUE THREAD

**Issue by laforetcan** [InstaPy/InstaPy#989]
> [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=51949487)](https://www.bountysource.com/issues/51949487-feature-request-sending-email-with-activity-of-session?utm_source=51949487&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Before closing the session I imagine a function:
send_report(youremail@internet.com)

The report could have important information about the session:
- time of the start of the session + time of the end
- Number of profiles interacted with
- Number of likes
- Number of comments
- Number of profiles followed
- Number of profiles unfollowed
- Number of requests

**Comment by timgrossmann** [comment]
@tonoli Great Idea!
If you're interested in this, help get it implemented faster by adding a bounty to this: https://www.bountysource.com/issues/51949487-feature-request-sending-email-with-activity-of-session
Thank you.

**Comment by laforetcan** [comment]
I can do it myself, I'll be glad to contribute!

**Comment by timgrossmann** [comment]
@tonoli Even better! 
So awesome, thank you very much!

Already looking forward to it

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
