### ISSUE TITLE
No title is set in the official page of InstaPy

### ISSUE THREAD

**Issue by amarlearning** [InstaPy/InstaPy#99]
No title is set in the official [page](https://timgrossmann.github.io/InstaPy/) of InstaPy
![screenshot from 2017-04-15 18-28-09](https://cloud.githubusercontent.com/assets/9383897/25063696/55b05ce8-2209-11e7-90e8-a0b6b1ae534a.png)

**Comment by timgrossmann** [comment]
@amarlearning Would be interesting to know how this works with the default github pages `.md` and `docs/` folder 😉 
If you get it working, I'd love to know how that works

**Comment by littleswany** [comment]
The fix is to add to _config.yml

`title: InstaPy`

Have updated as such in pull request

**Comment by amarlearning** [comment]
@timgrossmann You should read [this](https://guides.github.com/features/pages/#changes) article if you want to know more about `how to make changes in Github pages`

PR submitted for this issue!

**Comment by timgrossmann** [comment]
solved by #102
