### ISSUE TITLE
InstaPy Like Photo => No Like at Instagram

### ISSUE THREAD

**Issue by FreakyBoy** [InstaPy/InstaPy#993]
Hey I have a problem with the bot... the console output say that I liked a photo

INFO - --> Image Liked!
INFO - --> Not commented
INFO - --> Not following
INFO - [10/10]

But at Instagram (iOS App) I can`t see any Like :S
What do I wrong ?

## InstaPy configuration
`
from instapy import InstaPy
insta_username = '_name_'
insta_password = 'password'
session = InstaPy(username=insta_username, password=insta_password, nogui=True)
session.login()

session.like_by_tags(['berlin'], amount=10)

session.end()
`

**Comment by FreakyBoy** [comment]
ok I test the same configuration now on my mac and it`s working o.O
problem with nogui param ?

**Comment by gerdmueller2** [comment]
i have the same issue on aws, when i run it.
in about 50% of the cases it says:
INFO - --> Image Liked!
INFO - --> Commented: "..."
INFO - --> Now following
but did not like. (follow and comment are working well)

can anybody fix this?

**Comment by gitpatrickhub** [comment]
Same problem. If I try to like a photo from iOS device I receive an error stating the action was blocked, you can select ok or report the problem. It appears to be a soft ban. Waiting for reply of the report problem selection.

**Comment by FreakyBoy** [comment]
@gitpatrickhub that`s not a 'soft ban' problem. I can like all Photos from the iOS App without a problem.

**Comment by RomeoJuliett** [comment]
It could be a "soft ban" based on IP @FreakyBoy  How many pictures are you trying to like at a time?

**Comment by FreakyBoy** [comment]
@RomeoJuliett I try it also on a AWS Instance (with the nogui param) and it doesn't work. 

2 Server:
AWS Instanc with Ubuntu 
vServer with Debian Stretch 
booth with a different IP and nogui param = don't work 

1 MacBook with 10.12.5 and without the nogui param = work

**Comment by ssthormess** [comment]
I migrated my server to another DigitalOcean region because this was happening and it's still happening so it's clearly not a ban. I have even liked photos from the new IP address using VPN.

**Comment by RafaelLee** [comment]
Some problem here :/

**Comment by gerdmueller2** [comment]
@davidrocket posted an solution for this: (same problem, other issues: 
[#1030](https://github.com/timgrossmann/InstaPy/issues/1030) [#1083](https://github.com/timgrossmann/InstaPy/issues/1083) [#993](https://github.com/timgrossmann/InstaPy/issues/993)

To Fix "Like"-Problem, please replace the line 537 in `like_util.py` with this line

like_elem[0].click()

Tested and works!
